[Kotlin Migration] ReviewerUi
ankidroid/Anki-Android pull request #10009
Opened 2021-12-21 19:37 UTC by codingtosh

[Kotlin Migration] ReviewerUi

2021-12-21 21:35 UTC, mikehardy approved these changes

2021-12-22 15:31 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerUi.kt
> +    fun isControlBlocked(): Boolean
cleanup attr: this can probably be converted to a property

2021-12-22 15:31 UTC, david-allison-1 requested changes
tiny change

2021-12-22 18:06 UTC, codingtosh commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerUi.kt
> +    fun isControlBlocked(): Boolean
done, PTAL.

2021-12-23 01:35 UTC, david-allison-1 approved these changes

2021-12-23 01:35 UTC, merged

2021-12-23 01:36 UTC, david-allison-1 commented
Thanks!!