[Kotlin Migration] PeripheralKeymap
ankidroid/Anki-Android pull request #10016
Opened 2021-12-21 19:38 UTC by codingtosh

[Kotlin Migration] PeripheralKeymap

2021-12-21 21:30 UTC, mikehardy approved these changes

2021-12-21 21:31 UTC, mikehardy requested changes
lint failing right now

2021-12-22 15:40 UTC, david-allison-1 approved these changes

2021-12-28 12:26 UTC, mikehardy approved these changes

2021-12-28 12:26 UTC, merged

2022-01-16 19:17 UTC, mikehardy commented
Hi there! December OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for December 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of December)

Thanks!