Added Unit Test to verify audioFocusRequest is NonNull argument
ankidroid/Anki-Android pull request #10025
Opened 2021-12-27 14:33 UTC by raddi1972

## Pull Request template

## Purpose / Description
Adds Unit Test to test if audioFocusrequest is NonNull argument. The test passes after the pull request #9407 is merged but does not work before it.

## Fixes
Fixes #9461 

## Approach
A new class CompatSoundTest.java is added and contains Unit Tests to check for audioFocusrequest is NonNull.

## Checklist

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-12-27 14:35 UTC, raddi1972 commented
This is my first Pull Request, I have tried to fix issue but I might not have, so please provide feedback. I will change code as everyone suggest. Thank you

2021-12-27 14:50 UTC, david-allison-1 requested changes
Thanks!!!

The test looks good, the main issue is that this unit test isn't testing "does the app crash if audio is not found", it's testing "does the app crash if a null is passed to `requestAudioFocus`".

The test should ideally be more general, replicating the cause of the crash: audio not being found inside `Reviewer` causing the app to crash.

Please let me know if you want guidance on where to begin

2021-12-27 14:50 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/compat/CompatSoundTest.java
> +@Config(sdk = { 21, 26 })
This isn't going to do anything if you explicitly create a `CompatV26`, instead of a call to `getCompat()`

2021-12-27 14:50 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/compat/CompatSoundTest.java
> +
```suggestion
```

2021-12-27 14:50 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/compat/CompatSoundTest.java
> +public class CompatSoundTest {
Could you convert this class to Kotlin, we're no longer using Java for new code.

2021-12-27 14:57 UTC, david-allison-1 commented
Just to note: I'd be happy to merge this once the reviewed changes are made, 

"Make a more general test" can be tied up with a follow up pull request.

2021-12-27 15:19 UTC, raddi1972 commented on AnkiDroid/src/test/java/com/ichi2/compat/CompatSoundTest.java
> +public class CompatSoundTest {
Yeah sure, I will do that.

2021-12-27 15:31 UTC, raddi1972 commented on AnkiDroid/src/test/java/com/ichi2/compat/CompatSoundTest.java
> +@Config(sdk = { 21, 26 })
Here should I change `CompatV26` to `Compat` and call `getCompat()` instead?

2021-12-27 15:39 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/compat/CompatSoundTest.java
> +public class CompatSoundTest {
In case you didn't know, there's an automated tool inside Android Studio to do this - right click on the file

2021-12-27 15:40 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/compat/CompatSoundTest.java
> +@Config(sdk = { 21, 26 })
Yep - sounds good to me!

2021-12-27 20:32 UTC, raddi1972 commented
I have changed the code from Java to Kotlin for this test. The suggested changes are also made, if there is something else I missed Let me know.

2021-12-28 10:41 UTC, david-allison-1 approved these changes
Awesome, thanks!!

2021-12-28 11:45 UTC, mikehardy requested changes
I haven't reviewed yet, but definitely needs a copyright header. Thanks for posting this!

2021-12-28 11:45 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/compat/CompatSoundTest.kt
> +package com.ichi2.compat
```

/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/compat/CompatSoundTest.kt:1: Error: All files in AnkiDroid must contain a GPLv3-compatible copyright header [MissingCopyrightHeader from com.ichi2.anki.lint]
```

2021-12-28 12:10 UTC, raddi1972 commented on AnkiDroid/src/test/java/com/ichi2/compat/CompatSoundTest.kt
> +package com.ichi2.compat
Should i just copy that from another file and add?

2021-12-28 12:25 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/compat/CompatSoundTest.kt
> +package com.ichi2.compat
Yes, that can work

2021-12-29 05:37 UTC, ShridharGoel commented on AnkiDroid/src/test/java/com/ichi2/compat/CompatSoundTest.kt
> +    private var afChangeListener: OnAudioFocusChangeListener = OnAudioFocusChangeListener { _: Int -> }
These can be `val` instead of `var`.

2021-12-29 06:01 UTC, raddi1972 commented on AnkiDroid/src/test/java/com/ichi2/compat/CompatSoundTest.kt
> +    private var afChangeListener: OnAudioFocusChangeListener = OnAudioFocusChangeListener { _: Int -> }
Yeah sure will do that

2021-12-29 12:22 UTC, david-allison-1 approved these changes
Still great! Kicked off CI

2022-01-01 18:16 UTC, mikehardy reviewed
:thinking: am I missing something where there is an assertion and in kotlin you simply don't have to specify them in the way I'm used to? I can't see how this is asserting the actual correct functioning of anything here

2022-01-01 19:30 UTC, david-allison-1 commented
> 🤔 am I missing something where there is an assertion and in kotlin you simply don't have to specify them in the way I'm used to? I can't see how this is asserting the actual correct functioning of anything here

The parameter is currently `@Nullable` (due to API21 not accepting it, with a V26 override).

https://github.com/ankidroid/Anki-Android/blob/0e4347289197b101ce84586a836669d23a86d42d/AnkiDroid/src/main/java/com/ichi2/compat/Compat.java#L146-L147

2022-01-02 18:19 UTC, mikehardy approved these changes

2022-01-02 18:19 UTC, merged