Update UI of advanced editor
ankidroid/Anki-Android pull request #10031
Opened 2021-12-31 08:43 UTC by ShridharGoel

## Purpose / Description
Currently, when a new user opens the advanced editor, it may seem that the input field has limited space. Also, there's a lot of blank area below the buttons.

## Approach
This PR aims to make the screen look better by increasing the minimum lines in the FixedEditText and setting its gravity to `Gravity.TOP`.

## Checklist

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

<details>
  <summary>Screenshot</summary>
  
  ![Advanced editor](https://user-images.githubusercontent.com/35566748/147812966-71cb78da-1c7b-4252-9c1a-9384b2698fcc.jpeg)
</details>

2022-01-02 19:42 UTC, mikehardy reviewed
Seems reasonable - can you include screenshots before + after? It's hard to picture

2022-01-10 13:45 UTC, ShridharGoel commented
@mikehardy Updated.

2022-01-10 14:17 UTC, david-allison-1 requested changes

2022-01-10 14:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.java
> +        mEditText.setMinLines(25);
Can we have this fill the screen rather than set `minLines`. 

I presume it'll make the screen scroll on smaller phones, and won't be enough on larger tablets

2022-06-24 16:46 UTC, closed without merging