Add LeakCanary
ankidroid/Anki-Android pull request #10032
Opened 2021-12-31 12:31 UTC by ShridharGoel

## Purpose / Description
Add LeakCanary.

## Fixes
Fixes #8436 

## Approach
Added LeakCanary library for debug versions and added support for matching known memory leaks.

## How Has This Been Tested?
Verified that memory leaks in app are being reported through LeakCanary.

## Learning
https://square.github.io/leakcanary/

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-01-01 11:43 UTC, david-allison-1 approved these changes
LGTM

2022-01-01 11:44 UTC, david-allison-1 requested changes
Spoke too soon - CI failure

2022-01-01 19:32 UTC, david-allison-1 requested changes
CI still failing

2022-01-02 13:14 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        // Passing default values will not be required after migration to Kotlin.
Are the default values "disable"? Is there a reference for these values

Does the config need to be set on debug?

2022-01-02 15:29 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        // Passing default values will not be required after migration to Kotlin.
> Are the default values "disable"? Is there a reference for these values

Default values can be found here: https://github.com/square/leakcanary/blob/9f85fbc988878d0265a9383e0c1bada3177e6fc8/leakcanary-android-core/src/main/java/leakcanary/LeakCanary.kt#L36-L175

> Does the config need to be set on debug?

For debug, it is being set so that we can use `referenceMatchers`.

2022-01-02 16:52 UTC, david-allison-1 requested changes
Thanks! I understand, only nits and should be good to go

2022-01-02 16:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        // Passing default values will not be required after migration to Kotlin.
Ah! I understand

The KotlinCleanup will do, the comment implies that all the values are defaults

```suggestion
```

2022-01-02 16:52 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/constants.xml
> +    <bool tools:ignore="UnusedResources" name="leak_canary_allow_in_non_debuggable_build">true</bool>
Optional: I feel these would be better in `/leakcanary.xml`

2022-01-02 17:50 UTC, david-allison-1 approved these changes
LGTM

2022-01-02 17:51 UTC, ShridharGoel commented on AnkiDroid/src/main/res/values/constants.xml
> +    <bool tools:ignore="UnusedResources" name="leak_canary_allow_in_non_debuggable_build">true</bool>
Updated.

2022-01-02 18:25 UTC, mikehardy commented
Cool! Are there any leaks detected yet? Just out of curiosity, maybe you saw something...we can create a LeakCanary issue label and start logging them if needed

2022-01-02 18:25 UTC, mikehardy approved these changes

2022-01-02 18:42 UTC, merged

2022-01-02 19:17 UTC, ShridharGoel commented
> Cool! Are there any leaks detected yet? Just out of curiosity, maybe you saw something...we can create a LeakCanary issue label and start logging them if needed

Yes, there was one in the `Reviewer`. Will add the details in a new issue after trying to get that memory leak to occur again.

2022-03-06 21:52 UTC, mikehardy commented
Hi there! **JANUARY** OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [January 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-01-01..2022-01-31) (I'll follow this with the same process for February in a week)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of January)

Thanks!