[Kotlin Migration] Themes
ankidroid/Anki-Android pull request #10036
Opened 2021-12-31 15:10 UTC by Akshay0701

2021-12-31 16:24 UTC, david-allison-1 requested changes
Thanks!

This breaks `git blame`, could you use the listed procedure to conserve the history: https://github.com/ankidroid/Anki-Android/blob/master/docs/kotlin-migration.md

2021-12-31 16:58 UTC, Akshay0701 commented
done

2022-01-01 11:46 UTC, david-allison-1 approved these changes
LGTM

2022-01-01 18:17 UTC, mikehardy approved these changes

2022-01-01 18:17 UTC, merged