Follow android system-level dark mode settings
ankidroid/Anki-Android pull request #10035
Opened 2021-12-31 14:03 UTC by Akshay0701

## Pull Request template

## Purpose / Description
To make the AnkiDroid Android App follow the system dark mode

## Fixes
Fixes #5685

## Approach
Followed suggestions in [this ](https://github.com/ankidroid/Anki-Android/pull/9408#issuecomment-944240970) comment

## How Has This Been Tested?

Tested on a real android device running Android 11

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

<img src="https://user-images.githubusercontent.com/52353967/147827176-e3c0cdc8-e435-4432-8d4c-97ea2c132eb0.jpg" width="250" height="500" />

Superseded from #9894

2022-01-01 13:42 UTC, david-allison-1 requested changes
A few comments, `CardAppearance.isInNightMode` is broken.

We'll have conflicts due to the Kotlin changes

2022-01-01 13:42 UTC, david-allison-1 commented on AnkiDroid/src/main/res/xml/preferences_appearance.xml
> +    <PreferenceCategory android:title="@string/pref_cat_fonts" >
spacing changes

2022-01-01 13:42 UTC, david-allison-1 commented on AnkiDroid/src/main/res/xml/preferences_appearance.xml
> +            android:title="@string/pick_single_theme" />
Only one of the two should be visible at once

2022-01-01 13:42 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/constants.xml
> +    <string-array name="app_theme_mode_values">
It would be great to have comments here explaining

2022-01-01 13:42 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/11-arrays.xml
> +        <item>Light</item>
See line 83 - move the arrays to `constants.xml`, and define the strings in `11-arrays`

2022-01-01 13:42 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                restartActivity();
Optional: it would be nice to restart the activity on the theme page

2022-03-11 23:33 UTC, BrayanDSO commented
This seems useful

@Akshay0701, are you working on this or have the intention to continue the job? If not, I could take over

2022-03-12 04:22 UTC, Akshay0701 commented
No, if want to work on this pr, go for it

2022-03-18 14:29 UTC, david-allison commented
Superseded by #10520

2022-03-18 14:29 UTC, closed without merging