Fix crash in select method in Decks class
ankidroid/Anki-Android pull request #10047
Opened 2022-01-01 14:43 UTC by ShridharGoel

## Purpose / Description
Fix crash in select method in Decks class.

## Fixes
Fixes #10046 

## Approach
Added a null check.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-01-01 18:32 UTC, mikehardy approved these changes
interesting - seems like a reasonable guard

2022-01-01 19:25 UTC, david-allison-1 requested changes
We should handle the exception here (and ideally add a regression test in a follow up PR). 

This is caused by a corrupt collection, we should match Anki Desktop in `libAnki` (especially as we lose control of the functionality once  the Rust backend is enabled).

2022-01-02 13:28 UTC, david-allison-1 requested changes
Code for a DB error is one of the below. We want to provide the user with options if there is an issue (including check database):

https://github.com/ankidroid/Anki-Android/blob/6fd41ae687a7dc5cd5fefee673cca38c033e378f/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt#L408-L422

2022-01-02 18:32 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        }
do we need to return after showing this? if control returns here it will then try to continue executing here I think, with an invalid collection?

2022-01-02 18:32 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
> +import com.ichi2.anki.dialogs.DatabaseErrorDialog;
I don't believe there are any code changes in this file, but there were 5 import statements added :thinking:

2022-01-02 19:23 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        }
Valid point, updated accordingly.

2022-01-02 19:23 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
> +import com.ichi2.anki.dialogs.DatabaseErrorDialog;
Removed them, earlier there were changes in this file but I had reverted them after previous reviews. Missed the import statements.

2022-01-02 19:28 UTC, mikehardy approved these changes
LGTM will wait to see if this (much improved...) version where we recognize the corruption looks good to David

2022-01-02 23:57 UTC, david-allison-1 requested changes
The try/catch doesn't match the stack trace of the issue.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.ichi2.utils.JSONObject.getString(java.lang.String)' on a null object reference
at com.ichi2.libanki.Decks.select(Decks.java:1)
at com.ichi2.libanki.Decks.current(Decks.java:2)
at com.ichi2.anki.DeckPicker.__renderPage(DeckPicker.java:32)
at com.ichi2.anki.DeckPicker$UpdateDeckListListener.actualOnPostExecute(DeckPicker.java:9)
at com.ichi2.anki.DeckPicker$UpdateDeckListListener.actualOnPostExecute(DeckPicker.java:1)
at com.ichi2.async.TaskListenerWithContext.onPostExecute(TaskListenerWithContext.java:2)
at com.ichi2.async.CollectionTask.onPostExecute(CollectionTask.java:3)
at android.os.AsyncTask.finish(AsyncTask.java:771)
at android.os.AsyncTask.access$900(AsyncTask.java:199)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8506)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
```

`showDatabaseErrorDialog(DatabaseErrorDialog.DIALOG_DB_ERROR);` is broken, and likely has been for some time:

```
2022-01-02 23:52:14.109 30620-30620/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 30620
    java.lang.NullPointerException
        at com.ichi2.anki.dialogs.DatabaseErrorDialog.onCreateDialog(DatabaseErrorDialog.kt:92)
        at com.ichi2.anki.dialogs.DatabaseErrorDialog.onCreateDialog(DatabaseErrorDialog.kt:36)
        at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:647)
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:561)
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:492)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
        at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:564)
        at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:506)
        at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:491)
        at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:487)
        at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.java:531)
        at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.java:517)
        at com.ichi2.anki.DeckPicker.showDatabaseErrorDialog(DeckPicker.java:1319)
        at com.ichi2.anki.DeckPicker$UpdateDeckListListener.actualOnPostExecute(DeckPicker.java:2188)
        at com.ichi2.anki.DeckPicker$UpdateDeckListListener.actualOnPostExecute(DeckPicker.java:2154)
        at com.ichi2.async.TaskListenerWithContext.onPostExecute(TaskListenerWithContext.java:66)
        at com.ichi2.async.CollectionTask.onPostExecute(CollectionTask.java:228)
        at android.os.AsyncTask.finish(AsyncTask.java:771)
        at android.os.AsyncTask.access$900(AsyncTask.java:199)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

`getCustomView()` returned null

We should probably use `DIALOG_LOAD_FAILED` instead

It'd be useful to get a regression test here: opening a collection, having all the `col` json columns blank aside from `conf`

2022-06-24 15:41 UTC, closed without merging