[Kotlin Migration] Videoplayer
ankidroid/Anki-Android pull request #10044
Opened 2022-01-01 08:10 UTC by Akshay0701

2022-01-01 11:53 UTC, ShridharGoel requested changes

2022-01-01 11:53 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.kt
> +    @Suppress("DEPRECATION")
Comment got removed - It was there in the Java version.

2022-01-01 11:53 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.kt
> +        mVideoView!!.holder.addCallback(this)
Use `?.`

2022-01-01 11:53 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.kt
> +        mSoundPlayer!!.notifyConfigurationChanged(mVideoView)
Use `?.`

2022-01-01 11:53 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.kt
> +        mSoundPlayer!!.stopSounds()
Use `?.`

2022-01-01 11:55 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.kt
> +        mVideoView!!.holder.addCallback(this)
Ideally we shouldn't be refactoring the code in the conversion PR - add a `@KotlinCleanup` to deal with it in a follow-up

2022-01-01 11:58 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.kt
> +        mVideoView!!.holder.addCallback(this)
@david-allison-1 It isn't a refactoring. Using `?.` instead of `!!` is better since `!!` can lead to a `NullPointerException`.

2022-01-01 12:02 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.kt
> +        mVideoView!!.holder.addCallback(this)
It's an existing issue in the Java

I feel it's best to flag it rather than combine a "convert" and a "change functionality" commit.

2022-01-01 12:06 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.kt
> +    @Suppress("DEPRECATION")
thanks, added the missing comment

2022-01-01 12:08 UTC, david-allison-1 approved these changes
LGTM - with a comment still for discussion

2022-01-01 18:23 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.kt
> +        mVideoView!!.holder.addCallback(this)
The same could apply to #10043 I think - I guess KotlinCleanup annotation for both?

2022-01-01 18:24 UTC, mikehardy requested changes
needs KotlinCleanup annotation I suppose, for better possibly-null handling

2022-01-02 18:29 UTC, mikehardy approved these changes

2022-01-02 18:29 UTC, merged