[Kotlin Migration] Htmlcolors
ankidroid/Anki-Android pull request #10043
Opened 2022-01-01 08:04 UTC by Akshay0701

2022-01-01 11:48 UTC, david-allison-1 approved these changes
Seems OK, I hope we can remove this class in 2020

2022-01-01 11:57 UTC, ShridharGoel requested changes
`?.` should be preferred over `!!` at all places.

2022-01-01 11:57 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/themes/HtmlColors.kt
> +        return if (sColorsMap!!.containsKey(normalisedName)) {
Use `?.` since `!!` can lead to `NullPointerException`.

2022-01-01 11:57 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/themes/HtmlColors.kt
> +                if (color!!.length == 4 && color[0] == '#') {
Use `?.`

2022-01-01 18:22 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/themes/HtmlColors.kt
> +        return if (sColorsMap!!.containsKey(normalisedName)) {
good catch - @Akshay0701

2022-01-01 18:22 UTC, mikehardy requested changes
valid comment from @ShridharGoel

2022-01-02 18:28 UTC, mikehardy approved these changes

2022-01-02 18:29 UTC, merged