[Kotlin Migration] TagsDialogListener
ankidroid/Anki-Android pull request #10060
Opened 2022-01-02 07:49 UTC by Akshay0701

2022-01-02 13:30 UTC, david-allison-1 requested changes
```
> Task :AnkiDroid:compilePlayReleaseJavaWithJavac
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:131: error: CardBrowser is not abstract and does not override abstract method <F>registerFragmentResultReceiver(F) in TagsDialogListener
public class CardBrowser extends NavigationDrawerActivity implements
       ^
  where F is a type-variable:
    F extends Fragment,TagsDialogListener declared in method <F>registerFragmentResultReceiver(F)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.java:68: error: CustomStudyDialog is not abstract and does not override abstract method <F>registerFragmentResultReceiver(F) in TagsDialogListener
public class CustomStudyDialog extends AnalyticsDialogFragment implements
       ^
  where F is a type-variable:
    F extends Fragment,TagsDialogListener declared in method <F>registerFragmentResultReceiver(F)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.java:127: error: cannot find symbol
        registerFragmentResultReceiver(this);
        ^
  symbol:   method registerFragmentResultReceiver(CustomStudyDialog)
  location: class CustomStudyDialog
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java:149: error: NoteEditor is not abstract and does not override abstract method <F>registerFragmentResultReceiver(F) in TagsDialogListener
public class NoteEditor extends AnkiActivity implements
       ^
  where F is a type-variable:
    F extends Fragment,TagsDialogListener declared in method <F>registerFragmentResultReceiver(F)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java:49: error: CardTemplatePreviewer is not abstract and does not override abstract method <F>registerFragmentResultReceiver(F) in TagsDialogListener
public class CardTemplatePreviewer extends AbstractFlashcardViewer {
       ^
  where F is a type-variable:
    F extends Fragment,TagsDialogListener declared in method <F>registerFragmentResultReceiver(F)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java:48: error: Previewer is not abstract and does not override abstract method <F>registerFragmentResultReceiver(F) in TagsDialogListener
public class Previewer extends AbstractFlashcardViewer {
       ^
  where F is a type-variable:
    F extends Fragment,TagsDialogListener declared in method <F>registerFragmentResultReceiver(F)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java:115: error: Reviewer is not abstract and does not override abstract method <F>registerFragmentResultReceiver(F) in TagsDialogListener
public class Reviewer extends AbstractFlashcardViewer {
       ^
  where F is a type-variable:
    F extends Fragment,TagsDialogListener declared in method <F>registerFragmentResultReceiver(F)
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
7 errors
```

2022-01-26 17:26 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogListener.kt
> +    }
@mikehardy this is the part I didn't able to understand, error occurring because of this code,
what changes should I do?

2022-01-26 18:16 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogListener.kt
> +    }
Thanks, David! 
Okay, I will research and will make pr...

2022-02-01 02:08 UTC, david-allison-1 requested changes

2022-02-01 02:08 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogListener.kt
> +        fun <F> registerFragmentResultReceiver(fragment: F) where F : Fragment?, F : TagsDialogListener? {
Let's block this on the `@JvmDefault` PR, so we can keep this as a default method

2022-02-28 13:38 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogListener.kt
> +        fun <F> registerFragmentResultReceiver(fragment: F) where F : Fragment?, F : TagsDialogListener? {
@Akshay0701 unblocked now that #10275 is in! 🏃‍♂️

2022-03-03 18:00 UTC, mikehardy commented
Still something going on with this one, but now it should be resolve-able at least...

2022-04-19 14:25 UTC, closed without merging