[Kotlin Migration] DialogHandler
ankidroid/Anki-Android pull request #10061
Opened 2022-01-02 08:05 UTC by Akshay0701

2022-01-02 18:48 UTC, mikehardy requested changes
That is a pile of `!!` seems like it would be worth a kotlincleanup for null handling
otherwise looks good

2022-01-02 21:07 UTC, david-allison-1 reviewed
Agreed - will need a `KotlinCleanup`, treat this as a soft approve

2022-01-03 18:23 UTC, david-allison-1 approved these changes

2022-01-09 18:45 UTC, mikehardy approved these changes

2022-01-09 18:45 UTC, merged