Use safe call operator to prevent NPE in CreateDeckDialog
ankidroid/Anki-Android pull request #10069
Opened 2022-01-02 13:10 UTC by ShridharGoel

## Purpose / Description
Use safe call operator to prevent NPE in CreateDeckDialog.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-01-02 13:13 UTC, david-allison-1 reviewed
It'd seem more reasonable to enforce `nonnull` as a class invariant (probably as a builder pattern) rather than handle the possibility that internal properties are null.

Is this feasible?

2022-01-02 15:02 UTC, ShridharGoel commented
> It'd seem more reasonable to enforce `nonnull` as a class invariant (probably as a builder pattern) rather than handle the possibility that internal properties are null.
> 
> Is this feasible?

Can you provide an example? Not sure how this can be done.

I think we can add a lint check to prevent the usage of `!!`.

2022-03-03 22:12 UTC, david-allison requested changes
For my comment:

A `!!` is an assertion that a property holds, this assertion should not be weakened, as it allows bugs.

Instead of changing `!!` to `?`, the type system can be used to enforce state: for example, having `onPositiveButtonClicked` refer to a type returned from `showDialog`, would allow us to make the following variables non-null + `val`:

* `mShownDialog`
* `mOnNewDeckCreated`

**immutable**
* `mInitialDeckName` - I think this can be non-null as well

I'd accept a PR for changing the types, it's small effort, but has minimal benefit.

As it stands, I feel the `closeDialog` change proposed has value, and the class is better off and more readable without the other changes.

2022-03-03 22:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
> +        deckNameWithParentName?.let {
I believe: the only precondition where this might not hold is a value of `"`, or if `did` is invalid.

We should focus on these, rather than avoiding the problem

2022-03-03 22:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
> +            mOnNewDeckCreated?.accept(newDeckId)
revert - logic error if not defined

2022-03-03 22:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
> +            mOnNewDeckCreated?.accept(newDeckId)
logic error if not defined

2022-03-03 22:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
> +                    parentId?.let {
logic error if not defined

2022-03-03 22:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
> +                val deckId = mPreviousDeckName?.let {
Better off as they were before

2022-03-03 22:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
> +        show.inputEditText?.let {
We call `.input`, `inputEditText` should be defined - should revert. We can fix this with the type system

2022-03-03 22:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
> +        get() = mShownDialog?.inputEditText?.text.toString()
Logic error if not defined. Can be fixed with type system

2022-03-23 12:15 UTC, mikehardy commented
Took a conflict and has unresolved comments

2022-08-23 17:39 UTC, closed without merging