[Kotlin Migration] DeckDropDownAdapter
ankidroid/Anki-Android pull request #10078
Opened 2022-01-04 05:32 UTC by Akshay0701

2022-01-04 13:07 UTC, david-allison-1 requested changes
CI failure

2022-01-07 16:04 UTC, Akshay0701 commented
```
com.ichi2.anki.servicemodel.UpgradeVolumeButtonsToBindingsTest > test_preferences_not_opened_happy_path[1: isValid(TestData(affectedPreferenceKey=gestureVolumeDown, keyCode=25, unaffectedPreferenceKey=gestureVolumeUp, binding=com.ichi2.anki.reviewer.MappableBinding@19753a))={1}] FAILED
    java.lang.AssertionError: 
    Expected: iterable containing ["preferenceUpgradeVersion"]
         but: No item matched: "preferenceUpgradeVersion"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at com.ichi2.anki.servicemodel.UpgradeVolumeButtonsToBindingsTest.test_preferences_not_opened_happy_path(UpgradeVolumeButtonsToBindingsTest.kt:63)
```
I am not getting what the error is...

2022-01-07 21:58 UTC, david-allison-1 requested changes
nit, but LGTM

2022-01-07 21:58 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.kt
> +class DeckDropDownAdapter(private val context: Context, private val decks: List<Deck?>?) : BaseAdapter() {
Could do with a `@KotlinCleanup` to make decks non-null

2022-01-08 13:25 UTC, david-allison-1 approved these changes
Thanks!!!

2022-01-09 18:50 UTC, mikehardy approved these changes

2022-01-09 18:50 UTC, merged