[Kotlin Migration] Lookup
ankidroid/Anki-Android pull request #10083
Opened 2022-01-04 06:41 UTC by Akshay0701

2022-01-04 13:49 UTC, david-allison-1 requested changes
CI failure

2022-01-05 19:55 UTC, david-allison-1 requested changes
few nits, should be good to go after

2022-01-05 19:55 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Lookup.kt
> +    // Chinese, Russian
nit/Cleanup: comments were changed, ideally turn into doccomment

2022-01-05 19:55 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Lookup.kt
> +    private var mContext: Context? = null
Cleanup: lateinit

2022-01-05 20:17 UTC, david-allison-1 approved these changes
LGTM

2022-01-09 18:51 UTC, mikehardy approved these changes

2022-01-09 18:51 UTC, merged