[Kotlin Migration] CardUtils
ankidroid/Anki-Android pull request #10080
Opened 2022-01-04 06:15 UTC by Akshay0701

2022-01-04 13:08 UTC, david-allison-1 requested changes
LGTM, one nit

2022-01-04 13:08 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardUtils.kt
> +    fun isIn(array: LongArray, `val`: Long): Boolean {
`KotlinCleanup("rename val")

2022-01-09 17:16 UTC, david-allison-1 approved these changes
LGTM

2022-01-09 18:50 UTC, mikehardy approved these changes

2022-01-09 18:50 UTC, merged