[Kotlin Migration] StudyOptionsFragment
ankidroid/Anki-Android pull request #10088
Opened 2022-01-04 07:39 UTC by Akshay0701

2022-01-04 07:40 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +    }
all other conversion is right, but the problem occurring here, what should I do?

2022-01-04 14:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +    }
```
    private val mUndoListener: TaskListener<Unit, ComputeResult> = object : TaskListener<Unit, ComputeResult>() {
        override fun onPreExecute() {}
        override fun onPostExecute(result: ComputeResult) {
```

You also likely need a `@JvmOverloads` for `refreshInterface`

2022-01-04 18:39 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +    }
Thanks! cleared all errors

2022-01-04 19:32 UTC, david-allison-1 requested changes
```
    var mOnRequestReviewActivityResult = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result: ActivityResult ->
Fix the issues identified by lint, or add the following to your build script to proceed with errors:
    ^
...
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt:475: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki.lint]
android {
        /**
    lintOptions {
        ^
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt:479: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki.lint]
        abortOnError false
        /**
    }
}
...
        ^
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt:483: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki.lint]
        /**
        ^
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt:487: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki.lint]
        /**
        ^
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt:491: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki.lint]
        /**
        ^
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt:495: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki.lint]
        /**
        ^
7 errors, 0 warnings
```

2022-01-04 19:40 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +//noinspection MissingCopyrightHeader #10088
Why? There is a copyright header

2022-01-04 19:40 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +        val d = instantiate(ankiActivity, CustomStudyDialog::class.java)
cleanup: give it a better name

2022-01-04 19:40 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +    private fun refreshInterfaceAndDecklist(resetSched: Boolean) {
KotlinCleanup: `default value + JvmOverloads`

2022-01-04 19:40 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +    // This may happen if the backend is locked or similar.
comment was duplicated

2022-01-04 19:40 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +    // This may happen if the backend is locked or similar.
comment was duplicated

2022-01-05 14:53 UTC, david-allison-1 approved these changes
LGTM, thansk

2022-01-09 18:54 UTC, mikehardy approved these changes

2022-01-09 18:54 UTC, merged