[Kotlin Migration] ImportUtils
ankidroid/Anki-Android pull request #10105
Opened 2022-01-08 12:42 UTC by Akshay0701

2022-01-08 13:15 UTC, david-allison-1 requested changes
```
> Task :AnkiDroid:compilePlayReleaseKotlin
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt: (211, 51): Smart cast to 'String' is impossible, because 'mFileName' is a mutable property that could have been changed by this time
```

2022-01-08 13:17 UTC, Akshay0701 commented
yes solving....

2022-01-08 13:18 UTC, david-allison-1 requested changes
Should save a second review cycle

2022-01-08 13:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
> +        private fun validateZipFile(ctx: Context, filePath: String?): ImportResult? {
`KotlinCleanup`: nonnull path

2022-01-08 13:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
> +            if (`in` == null) {
`kotlinCleanup`: rename

2022-01-08 13:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
> +            private fun sendShowImportFileDialogMsg(path: String?) {
kotlinCleanup: nonnull path

2022-01-08 13:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
> +                var `in`: InputStream? = null
`in` again

2022-01-08 23:16 UTC, david-allison-1 approved these changes
LGTM

2022-01-09 18:55 UTC, mikehardy approved these changes

2022-01-09 18:55 UTC, merged