[Kotlin Migration] BasicTextFieldController
ankidroid/Anki-Android pull request #10111
Opened 2022-01-08 13:30 UTC by Akshay0701

2022-01-08 14:20 UTC, david-allison-1 requested changes
Seems reasonable, but to be honest, I'm not familiar with this screen (some functionality is likely broken, others would be best moved to mani's addon PR).

Could you check this one manually to ensure that things aren't more broken

2022-01-08 14:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.kt
> +    private var mEditText: EditText? = null
KotlinCleanup: `lateinit`

2022-01-08 14:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.kt
> +                if (curField.text.isEmpty()) {
Hmm... might be possible to add a null assertion inside `isEmpty()`, so we don't need `text!!` later on: worth investigating

2022-01-08 14:25 UTC, Akshay0701 commented
okay, will test this manually

2022-01-08 18:44 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.kt
> +                if (curField.text.isEmpty()) {
yeah there is one method which check both things `isNullorEmpty()`, I just used that here

but even after using this method it still giving the same warning "use !! to text..."
![Capture](https://user-images.githubusercontent.com/52353967/148655862-6d316178-150e-4054-a771-c3a7257ef18c.PNG)

2022-01-08 19:09 UTC, Akshay0701 commented
tested this in my phone and emulator, tried almost every features, no crash or aberrant behavior so far...

2022-01-30 20:01 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.kt
> +                if (curField.text.isEmpty()) {
Check this: https://github.com/ankidroid/Anki-Android/pull/10111#discussion_r795241044

2022-02-05 16:36 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.kt
> + * <p>
I guess it's to separate paragraphs of the Javadoc output...

2022-02-06 12:23 UTC, david-allison-1 approved these changes
LGTM

2022-02-06 15:48 UTC, mikehardy approved these changes

2022-02-06 16:03 UTC, merged