[Kotlin Migration] GestureMapper
ankidroid/Anki-Android pull request #10115
Opened 2022-01-08 14:19 UTC by Akshay0701

2022-01-08 23:20 UTC, david-allison-1 requested changes
one nit

2022-01-08 23:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/GestureMapper.kt
> +            val `val` = floor(value)
cleanup: val

2022-01-09 17:19 UTC, david-allison-1 requested changes

2022-01-09 17:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.kt
> +        return execute(gesture!!)
`gesture` can be null, the method likely wants to accept a nullable

2022-01-09 18:24 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.kt
> +        return execute(gesture!!)
changes are done by reference from previous [java file](https://github.com/ankidroid/Anki-Android/blob/e5405ed2ec19090858997ac68b2ce6f09a9c2d58/AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.java#L128)

2022-01-09 19:10 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.kt
> +        return execute(gesture!!)
https://github.com/ankidroid/Anki-Android/blob/e5405ed2ec19090858997ac68b2ce6f09a9c2d58/AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.java#L105-L108

To my understanding, Gesture is nullable here

`mapGestureToCommand` returns `COMMAND_NOTHING`

2022-01-09 19:13 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.kt
> +        return execute(gesture!!)
yes did the changes

2022-01-09 19:15 UTC, david-allison-1 approved these changes
LGTM

2022-01-09 19:42 UTC, mikehardy approved these changes

2022-01-09 19:42 UTC, merged