String _feedback_manual_toast_text_ has been edited.
ankidroid/Anki-Android pull request #10120
Opened 2022-01-09 06:29 UTC by AayushSolanki

Fixes #10029 

String _feedback_manual_toast_text_ has been edited with appropriate message.

**Before**
![earlier](https://user-images.githubusercontent.com/75438613/148671746-2a5171d6-baca-4a0a-8e1f-7749724b6b10.png)

**After**
![after](https://user-images.githubusercontent.com/75438613/148671750-cd22646e-2276-4df3-b9f1-9cb87c7dc6ff.png)

2022-01-12 13:45 UTC, mikehardy requested changes
Doesn't force a re-translation, I was under the impression we wanted to force a re-translation

2022-01-12 13:45 UTC, mikehardy commented on AnkiDroid/src/main/res/values/05-feedback.xml
> +    <string name="feedback_manual_toast_text">A report is being generated for the reference of developers…</string>
As mentioned in the related issue, we want to force a retranslation. That implies that you need to change the key name so that crowdin removes the old translations and requests a new translation in all locales 

comment reference that has not been taken in to account yet https://github.com/ankidroid/Anki-Android/issues/10029#issuecomment-1007988700

2022-01-14 05:48 UTC, david-allison-1 reviewed
Implementation looks good, thanks!

Suggestion attached. 

For discussion with others, doesn't need to be accepted immediately

2022-01-14 05:48 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/05-feedback.xml
> +    <string name="feedback_for_manual_toast_text">A report is being generated for the reference of developers…</string>
```suggestion
    <string name="feedback_for_manual_toast_text">An error report is being prepared for the developers…</string>
```

2022-01-14 16:17 UTC, david-allison-1 requested changes
References to the new string need to be updated
```
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:600: error: cannot find symbol
                toastBuilder.setResText(R.string.feedback_manual_toast_text);
                                                ^
  symbol:   variable feedback_manual_toast_text
  location: class string
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
```

2022-01-14 18:12 UTC, david-allison-1 requested changes

2022-01-14 18:12 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +import androidx.core.content.pm.PackageInfoCompat;
Let's keep the change as targeted as possible, could you revert the import changes.

These will be fixed in the upcoming Kotlin migration of this file

2022-01-16 09:26 UTC, david-allison-1 commented
Deleting AnkiDroidApp seems to be a mistake

2022-01-16 09:29 UTC, AayushSolanki commented
@david-allison-1 by mistake i have deleted the project now i am setting it up again sorry for the inconvenience

2022-01-16 16:53 UTC, mikehardy commented
This is beyond repair really since it has a merge commit (better to do a rebase...) and has a random deleted file. Start a new PR I think

2022-01-16 16:53 UTC, closed without merging