[Kotlin Migration] AnkiDroidWidgetSmall
ankidroid/Anki-Android pull request #10125
Opened 2022-01-10 00:34 UTC by codingtosh

[Kotlin Migration] AnkiDroidWidgetSmall

2022-01-10 02:07 UTC, david-allison-1 requested changes

2022-01-10 02:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
> +        @Deprecated("")
Cleanup: fill this in

2022-01-10 02:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
> +        @Suppress("SameParameterValue")
KotlinCleanup: fix this

2022-01-10 02:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
> +                            val action = intent.action
Can you `KotlinCleanup` here to rename context so it's not used: I explicitly re-assigned context here to ensure that the original param value would never be used.

Now, we run the risk of a new developer using the param value (which may not have had a custom language applied).

PS: I agree that it's best to have `AnkiDroidApp.getInstance().unregisterReceiver` as it explicitly mirrors below

2022-01-10 03:47 UTC, codingtosh commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
> +                            val action = intent.action
Done. I wanted to retain the original reassignment but that could not be possible since parameters are immutable in kotlin.

2022-01-10 03:47 UTC, codingtosh commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
> +        @Suppress("SameParameterValue")
Done, ptal.

2022-01-10 03:47 UTC, codingtosh commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
> +        @Deprecated("")
Done, ptal.

2022-01-10 13:35 UTC, david-allison-1 approved these changes
LGTM

2022-01-11 21:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
> -                            context = AnkiDroidApp.getInstance();
See: https://github.com/ankidroid/Anki-Android/pull/10110

2022-01-12 15:37 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
> -                            context = AnkiDroidApp.getInstance();
Then shouldn't it be two distinct commits? Or even two distinct PRs?
In order to remain as close as possible from the original java code, I guess that the paramater should be renamed to context_. And then a variable context, initialized at context, should be introduced. This way, we are not limited by this. 
And the change can be considered by itself in a limited PR

Or if Mike is confortable giving the second review, great.

2022-01-12 16:55 UTC, codingtosh commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
> -                            context = AnkiDroidApp.getInstance();
@Arthur-Milchior Actually, I had tried to do this initially, I renamed the parameter Context to` paramContext`. Then created a local `var context`, but it was shadowing the parameter context of `buildUpdate()`. So we have to have a different name, say 
`_context`, then initialize it to to the paramContext of onReceive in order to retain the java code originality:
`var _context = paramContext`

And then reassign it with 
`_context =  AnkiDroidApp.getInstance()`

At this point, not only do we have 3 contexts in the same scope but there is also a warning that
**Variable '_context' initializer is redundant.** 

That is why I decided to just use AnkiDroidApp.getInstance() directly, although it is possible to assign to a var and then use it if that would mean retaining the original java code behaviour. I have no strong opinion here, please let me know how I should proceed.

2022-01-16 19:55 UTC, mikehardy approved these changes
I'm okay with it given the KotlinCleanup annotation, confirmed passes all CI locally with current master

2022-01-16 19:59 UTC, merged

2022-01-16 20:52 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
> -                            context = AnkiDroidApp.getInstance();
Thanks for the explanation