[Kotlin Migration] DrawableContainer
ankidroid/Anki-Android pull request #10132
Opened 2022-01-10 00:35 UTC by codingtosh

[Kotlin Migration] DrawableContainer

2022-01-10 13:53 UTC, david-allison-1 requested changes
Less sure on this one

2022-01-10 13:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt
>  @SuppressLint("NonPublicNonStaticFieldName")
Again: I believe this can be removed

2022-01-10 15:22 UTC, codingtosh commented on AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt
>  @SuppressLint("NonPublicNonStaticFieldName")
Done, PTAL.

2022-01-10 17:12 UTC, david-allison-1 approved these changes
LGMT

2022-01-12 17:54 UTC, Arthur-Milchior approved these changes

2022-01-12 17:54 UTC, merged