[Kotlin Migration] PlotSheet
ankidroid/Anki-Android pull request #10131
Opened 2022-01-10 00:35 UTC by codingtosh

[Kotlin Migration] PlotSheet

2022-01-10 02:23 UTC, david-allison-1 requested changes
A small question. `wildplot` isn't our code, so this is lower priority for `KotlinCleanup` - maybe we'll want to move this to a dependency in future years.

2022-01-10 02:23 UTC, david-allison-1 commented on .idea/codeStyles/Project.xml
> +      <option name="NAME_COUNT_TO_USE_STAR_IMPORT" value="99" />
I think this was accidental

2022-01-10 04:08 UTC, codingtosh commented on .idea/codeStyles/Project.xml
> +      <option name="NAME_COUNT_TO_USE_STAR_IMPORT" value="99" />
Ah yes..I was trying to turn off the automatic wildcard imports. Do we want to retain them in our project?

2022-01-10 04:52 UTC, codingtosh commented on .idea/codeStyles/Project.xml
> +      <option name="NAME_COUNT_TO_USE_STAR_IMPORT" value="99" />
Oh, and about `wildplot` , didn't realise it was low priority. I've actually migrated most of it... 😅

2022-01-10 13:43 UTC, david-allison-1 commented on .idea/codeStyles/Project.xml
> +      <option name="NAME_COUNT_TO_USE_STAR_IMPORT" value="99" />
> Ah yes..I was trying to turn off the automatic wildcard imports. Do we want to retain them in our project?

I (slightly) prefer wildcards - the only conflict we typically have is `libanki.Collection` / `Collection<T>`. 
Open to discussion if we want to change this.

But, if we do make a change, it should have a commit message explaining why

2022-01-10 13:45 UTC, david-allison-1 requested changes
I'm going to leave this on "waiting for feedback" due to the project.xml change. Looks fine otherwise.

2022-01-10 13:46 UTC, david-allison-1 commented on .idea/codeStyles/Project.xml
> +      <option name="NAME_COUNT_TO_USE_STAR_IMPORT" value="99" />
And about `wildplot` - not a bother. Convert what you like!

2022-01-10 15:17 UTC, codingtosh commented on .idea/codeStyles/Project.xml
> +      <option name="NAME_COUNT_TO_USE_STAR_IMPORT" value="99" />
Sounds good, made the required changes, PTAL. 
We can defer the wildcard import style settings for later since it is a non-issue and not really actionable right now.

2022-01-10 17:12 UTC, david-allison-1 requested changes

2022-01-10 17:12 UTC, david-allison-1 commented on .idea/codeStyles/Project.xml
> +</component>
nit: EOL change

2022-01-12 18:09 UTC, codingtosh commented on .idea/codeStyles/Project.xml
> +</component>
Done, PTAL.

2022-06-24 00:53 UTC, closed without merging