[Kotlin Migration] CsvReaderIterator
ankidroid/Anki-Android pull request #10134
Opened 2022-01-10 00:35 UTC by codingtosh

[Kotlin Migration] CsvReaderIterator

2022-01-10 14:11 UTC, david-allison-1 requested changes
`@KotlinCleanup("ensure code style matches https://github.com/python/cpython/blob/c88239f864a27f673c0f0a9e62d2488563f9d081/Modules/_csv.c")`

2022-01-10 14:16 UTC, david-allison-1 requested changes
This wasn't a fun class to write, and won't be a fun class to convert

2022-01-10 14:16 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/python/CsvReader.kt
> +        val _iter = iter as MutableIterator<List<String>>?
I don't think this is correct. 

`MutableIterator<List<String>?>`, not `MutableIterator<List<String>>?`. This implies the code signature of the class is incorrect.

This code is in use in one of my draft PRs, which may be used to test

2022-01-10 14:16 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/python/CsvReaderIterator.kt
> +                /* start of record */if (c == '\u0000') { /* empty line - return [] */
Issues with spacing here. It should match the `c` file as much as possible, but this looks incorrect enough to fix in the PR as it's just spacing.

2022-01-12 19:25 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/python/CsvReaderIterator.kt
> +        START_RECORD, START_FIELD, IN_QUOTED_FIELD, EAT_CRNL, AFTER_ESCAPED_CRNL, ESCAPED_CHAR, IN_FIELD, ESCAPE_IN_QUOTED_FIELD, QUOTE_IN_QUOTED_FIELD
If this is not too much work, I'd love to see the list with one element by line.
Not only it's currently a long line, but it'd also help the diff displaying correctly

2022-01-12 19:59 UTC, codingtosh commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/python/CsvReaderIterator.kt
> +        START_RECORD, START_FIELD, IN_QUOTED_FIELD, EAT_CRNL, AFTER_ESCAPED_CRNL, ESCAPED_CHAR, IN_FIELD, ESCAPE_IN_QUOTED_FIELD, QUOTE_IN_QUOTED_FIELD
Sure, done. May I also suggest that we enable trailing commas in the project codestyle settings?

2022-01-12 20:21 UTC, codingtosh commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/python/CsvReaderIterator.kt
> +                /* start of record */if (c == '\u0000') { /* empty line - return [] */
I'm running lint checks
`./gradlew ktlintcheck --info`
and there are issues with indentation and newline if I try to make it similar to `_csv.c`

2022-05-09 18:40 UTC, closed without merging