[Kotlin Migration] CustomTabActivityHelper
ankidroid/Anki-Android pull request #10156
Opened 2022-01-10 17:58 UTC by Akshay0701

2022-01-10 18:27 UTC, david-allison-1 requested changes

2022-01-10 18:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.kt
> +// Copyright 2015 Google Inc. All Rights Reserved.
Needs `//noinspection MissingCopyrightHeader #8659` - this isn't a GPL header and needs a preamble.

2022-01-10 18:27 UTC, david-allison-1 requested changes
```
com.ichi2.compat.customtabs.CustomTabActivityHelperTest > invalidClientMeansFallbackIsCalled FAILED
    java.lang.NullPointerException: Parameter specified as non-null is null: method com.ichi2.compat.customtabs.CustomTabActivityHelper$Companion.openCustomTab, parameter customTabsIntent
        at com.ichi2.compat.customtabs.CustomTabActivityHelper$Companion.openCustomTab(CustomTabActivityHelper.kt)
        at com.ichi2.compat.customtabs.CustomTabActivityHelper.openCustomTab(CustomTabActivityHelper.kt)
        at com.ichi2.compat.customtabs.CustomTabActivityHelperTest.invalidClientMeansFallbackIsCalled(CustomTabActivityHelperTest.java:77)
```

2022-01-13 14:34 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.kt
> +        val packageName = CustomTabsHelper.getPackageNameToUse(activity) ?: return
Is this standard Kotlin good practice that I'll have to learn to be used to. Or is it some unusual but technically correct feature that we avoid.
I'd find it harder to read than using an if. I'd have kept the if, unless it forces to use !! everywhere

2022-01-13 14:39 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.kt
> +     * @see {@link CustomTabsSession.mayLaunchUrl
Why is this shortened?

2022-01-13 14:54 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.kt
> +        val packageName = CustomTabsHelper.getPackageNameToUse(activity) ?: return
i understand that its hard to ready but it is new clean way to check null value and return the method from that point(its called [return_and_jump](https://kotlinlang.org/docs/returns.html)), i am not fan of this practice, kotlin conversion suggested me to do so, 

should i use if here?

2022-01-13 14:55 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.kt
> +     * @see {@link CustomTabsSession.mayLaunchUrl
oh my bad! Thanks i will revert this change

2022-01-13 14:56 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.kt
> +         * @param customTabsIntent a CustomTabsIntent to be used if Custom Tabs is available.
okay, can i add kotlinCleanup instead of todo here? 
in most of the kotlin conversions, we do add kotlincleanup to do things later

2022-01-13 14:57 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.kt
> +        activity.unbindService(mConnection!!)
I agree with you

2022-01-13 15:49 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.kt
> +        activity.unbindService(mConnection!!)
@Arthur-Milchior `mConnection.let { activity.unbindService(it) }` is the typical pattern

2022-01-14 18:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.kt
> +        mConnection.let { activity.unbindService(it!!) }
`mConnection?.let { activity.unbindService(it) }`

2022-01-14 18:19 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.kt
> +        mConnection.let { activity.unbindService(it!!) }
tried this, it was giving error to add "!!"

2022-01-14 18:20 UTC, david-allison-1 requested changes

2022-01-14 18:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.kt
> +    fun bindCustomTabsService(activity: Activity?) {
cleanup:nonnull

2022-01-14 18:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.kt
> +        fun openUri(activity: Activity?, uri: Uri?)
cleanup: consider nullability

2022-01-14 18:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.kt
> +        @KotlinCleanup("make activity nullable")
`Consider nullability`: we should probably get rid of the test if it's now impossible due to Kotlin

2022-02-01 01:49 UTC, david-allison-1 approved these changes
LGTM, pending a comment of Arthur's. 

I like `:? return` for guard clauses, but I'm open to fixing the style guide

2022-02-01 14:47 UTC, mikehardy commented
similar to nullish-coalescing (a typescript/javascript thing) jump and return is like a nullish-coalesce and logical "early return / short circuit". It doesn't bother me stylistically. I'd merge personally but also in matters of style I don't care that much. So also pending @Arthur-Milchior  :-)

2022-02-06 15:51 UTC, mikehardy approved these changes

2022-02-06 16:09 UTC, merged