[Kotlin Migration] DiffEngine
ankidroid/Anki-Android pull request #10155
Opened 2022-01-10 17:47 UTC by Akshay0701

2022-01-10 18:08 UTC, Akshay0701 commented
solving errors....

2022-01-10 18:29 UTC, david-allison-1 requested changes
Besides the errors, one nit

2022-01-10 18:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/DiffEngine.kt
> +        private fun wrapBad(`in`: String): String {
Cleanup: `in`

2022-01-13 15:48 UTC, david-allison-1 approved these changes
LGTM

2022-01-16 20:25 UTC, mikehardy approved these changes

2022-01-16 21:28 UTC, merged