[Kotlin Migration] WidgetStatus
ankidroid/Anki-Android pull request #10157
Opened 2022-01-10 18:09 UTC by Akshay0701

2022-01-10 18:31 UTC, david-allison-1 requested changes

2022-01-10 18:31 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
> +    @Suppress("deprecation")
This was added, `AsyncTask` again?
Is it possible to move it closer to the error?

2022-01-10 18:31 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
> + * this program.  If not, see <http:></http:>//www.gnu.org/licenses/>.                           *
Header needs fixing (failed lint)

2022-01-13 14:09 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
> +    @Suppress("deprecation")
nope this deprecation is not for `AsyncTask` but for `doInBackground`

2022-01-13 14:14 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
> +    @Suppress("deprecation")
doInBackground and onPostExecute is deprecation, thats why I added this here.

2022-01-14 03:37 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
> +    @Suppress("deprecation")
Can you move this to the methods themselves. `@Suppress("deprecation")` should ideally be as close to the source as possible, or it can mask additional issues.

2022-01-14 17:08 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
> +    @Suppress("deprecation")
understood, done

2022-01-14 18:15 UTC, david-allison-1 approved these changes
LGTM, thanks!

2022-01-16 20:26 UTC, mikehardy approved these changes

2022-01-16 21:37 UTC, mikehardy commented
Looks like this had an interaction with a different PR:

```
> Task :AnkiDroid:compilePlayDebugKotlin FAILED
e: /home/mike/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt: (95, 42): Type mismatch: inferred type is Context? but Context was expected

> Task :AnkiDroid:compilePlayReleaseKotlin FAILED
e: /home/mike/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt: (95, 42): Type mismatch: inferred type is Context? but Context was expected

```

2022-01-17 14:58 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
> +                result?.let { UpdateService().doUpdate(it) }
let me know if this is a right way or should I use `!!`

2022-01-30 19:42 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
> +                result?.let { UpdateService().doUpdate(it) }
This is better than using `!!`.

2022-01-30 19:46 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
> +                result?.let { UpdateService().doUpdate(it) }
Okay thanks!

2022-01-30 19:53 UTC, ShridharGoel approved these changes

2022-02-01 13:46 UTC, mikehardy approved these changes

2022-02-01 13:53 UTC, merged