[Kotlin Migration] SimpleCardQueue
ankidroid/Anki-Android pull request #10150
Opened 2022-01-10 04:17 UTC by codingtosh

[Kotlin Migration] SimpleCardQueue

2022-01-10 16:52 UTC, david-allison-1 requested changes

2022-01-10 16:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/SimpleCardQueue.kt
> +internal class SimpleCardQueue(sched: AbstractSched?) : CardQueue<Card.Cache?>(sched) {
Cleanup: make sched non-null

2022-03-16 19:04 UTC, codingtosh commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/SimpleCardQueue.kt
> +internal class SimpleCardQueue(sched: AbstractSched?) : CardQueue<Card.Cache?>(sched) {
Done, PTAL.

2022-03-16 19:46 UTC, david-allison approved these changes
LGTM

2022-03-18 21:00 UTC, mikehardy approved these changes
nice

2022-03-18 21:00 UTC, merged