[Kotlin Migration] ActivityExportingDelegate
ankidroid/Anki-Android pull request #10159
Opened 2022-01-10 18:41 UTC by Akshay0701

2022-01-13 16:00 UTC, david-allison-1 requested changes
Few cleanups. Seems good though

2022-01-13 16:00 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +    override fun saveExportFile(exportPath: String?) {
cleanup: non-null

2022-01-13 16:00 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +    private fun exportToProvider(intent: Intent?, deleteAfterExport: Boolean): Boolean {
I'd be tempted to make this non-null

2022-01-14 18:17 UTC, david-allison-1 approved these changes
LGTM, thanks

2022-01-16 20:29 UTC, mikehardy approved these changes
:sweat_smile: lots of tech debt was embodied in those nullables, better that it's obvious at least, thanks!

2022-01-16 21:45 UTC, merged