[Kotlin Migration] BackupManager
ankidroid/Anki-Android pull request #10164
Opened 2022-01-10 19:28 UTC by Akshay0701

2022-01-13 16:06 UTC, david-allison-1 requested changes
```
> Task :AnkiDroid:compilePlayReleaseJavaWithJavac
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:1039: error: no suitable method found for performBackupInBackground(String,Time)
        BackupManager.performBackupInBackground(getCol().getPath(), getCol().getTime());
                     ^
    method BackupManager.performBackupInBackground(String,int,boolean,Time) is not applicable
      (actual and formal argument lists differ in length)
    method BackupManager.performBackupInBackground(String,boolean,Time) is not applicable
      (actual and formal argument lists differ in length)
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
```

2022-01-13 16:26 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
> +    fun performDowngradeBackupInForeground(path: String?): Boolean {
non-null

2022-01-13 17:56 UTC, david-allison-1 requested changes
```
com.ichi2.anki.BackupManagerTest > noBackupPerformedIfBackupAlreadyExists FAILED
    java.lang.NullPointerException
        at com.ichi2.anki.BackupManager$Companion.getBackups(BackupManager.kt:364)
        at com.ichi2.anki.BackupManager.performBackupInBackground(BackupManager.kt:70)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
        at java.base/java.lang.Thread.run(Thread.java:829)

com.ichi2.anki.BackupManagerTest > noBackupPerformedIfNoBackupNecessary FAILED
    java.lang.NullPointerException
        at com.ichi2.anki.BackupManager$Companion.getBackups(BackupManager.kt:364)
        at com.ichi2.anki.BackupManager.performBackupInBackground(BackupManager.kt:70)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
        at java.base/java.lang.Thread.run(Thread.java:829)

com.ichi2.anki.BackupManagerTest > testPassingSpy FAILED
    java.lang.NullPointerException
        at com.ichi2.anki.BackupManager$Companion.getBackups(BackupManager.kt:364)
        at com.ichi2.anki.BackupManager.performBackupInBackground(BackupManager.kt:70)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
        at java.base/java.lang.Thread.run(Thread.java:829)

com.ichi2.anki.BackupManagerTest > noBackupPerformedIfCollectionTooSmall FAILED
    java.lang.NullPointerException
        at com.ichi2.anki.BackupManager$Companion.getBackups(BackupManager.kt:364)
        at com.ichi2.anki.BackupManager.performBackupInBackground(BackupManager.kt:70)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
        at java.base/java.lang.Thread.run(Thread.java:829)

com.ichi2.anki.BackupManagerTest > passesIfNoBackupsAllowedAndForceIsEnabled FAILED
    java.lang.NullPointerException
        at com.ichi2.anki.BackupManager$Companion.getBackups(BackupManager.kt:364)
        at com.ichi2.anki.BackupManager.performBackupInBackground(BackupManager.kt:70)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

2022-01-13 17:58 UTC, Akshay0701 commented
Yes, I am solving this error now, 
but confused on how to solve this..

2022-01-17 23:21 UTC, david-allison-1 requested changes
Hmm... problem in testing,

we pass in "" as the path, the parent is null

But `File(null, "backups")` inside `getBackupDirectory` returns `C:\GitHub\Anki-Android-Git\Anki-Android\AnkiDroid\backup` so things work. We mostly use mocks here, so things pass

To fixup: 

And add a GitHub issue that the tests should be changed to use the temp directory, then fix the nullability. `.parent` shouldn't return null.

```
        @JvmStatic
        fun getBackups(colFile: File): Array<File?> {
            var files = getBackupDirectory(colFile.parentFile).listFiles()
            if (files == null) {
                files = arrayOfNulls(0)
            }
            val deckBackups = ArrayList<File?>(files.size)
            for (aktFile in files) {
                if (aktFile!!.name.replace("^(.*)-\\d{4}-\\d{2}-\\d{2}-\\d{2}-\\d{2}.(apkg|colpkg)$".toRegex(), "$1")
                    == colFile.name.replace(".anki2", "")
                ) {
                    deckBackups.add(aktFile)
                }
            }
            sort(deckBackups)
            val fileList = arrayOfNulls<File>(deckBackups.size)
            deckBackups.toArray(fileList)
            return fileList
        }
```

for now, accept null in `getBackupDirectory()`

2022-01-30 17:00 UTC, closed without merging