[Kotlin Migration] PickStringDialogFragment
ankidroid/Anki-Android pull request #10160
Opened 2022-01-10 18:47 UTC by Akshay0701

2022-01-10 22:08 UTC, david-allison-1 requested changes
nit, then LGTM

2022-01-10 22:08 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/PickStringDialogFragment.kt
> -        AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
cleanup: `requireActivity`

2022-01-13 16:02 UTC, david-allison-1 approved these changes

2022-01-16 20:39 UTC, mikehardy approved these changes

2022-01-16 23:20 UTC, merged