[Kotlin Migration] CardTemplateEditor
ankidroid/Anki-Android pull request #10165
Opened 2022-01-10 19:48 UTC by Akshay0701

2022-01-10 19:50 UTC, Akshay0701 commented
this one might require time for error-free and all correct migration, but I picked this file because I am familiar with most of its parts...

2022-01-15 10:00 UTC, Akshay0701 commented
this pr is ready to review now,

I tested this on emulator and physical device, there were several crashes and bugs, but finally all are resolved,

review this and let me know if i miss any part of this CardTemplateEditor.

2022-01-15 10:01 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/utils/KotlinCleanup.kt
> +    AnnotationTarget.VALUE_PARAMETER, AnnotationTarget.EXPRESSION, AnnotationTarget.FIELD, AnnotationTarget.PROPERTY, AnnotationTarget.PROPERTY_GETTER
I added this because I wanted to use kotlincleanup to getters and others..

2022-01-15 10:04 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +    @Suppress("UNCHECKED_CAST")
this Suppress is for line 127(Serializable to hashmap conversion), 
should I mention this in a comment here?

2022-01-15 10:10 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +            supportActionBar!!.subtitle = tempModel!!.model.optString("name")
why kotlin want me to check for nullability if I already did in `if` statement?

2022-02-01 02:10 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +            supportActionBar!!.subtitle = tempModel!!.model.optString("name")
It's a member variable, may have been changed by a different thread `?.let { }` is typically used

2022-02-01 02:18 UTC, david-allison-1 requested changes
Minor changes. Please also rebase onto master as additional checks were added in the new AGP.

Then treat this as an "approve". 

I trust the testing of this class very much and there's a lot of code, don't put a massive amount of weight into this review.

2022-02-01 02:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +    private var mEditorPosition: HashMap<Int, Int?>? = null
lots of these can be `lateinit`

2022-02-01 02:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +    @KotlinCleanup("use lateinit")
Let's move this to the class - we need to check each variable

2022-02-01 02:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +    @Suppress("UNCHECKED_CAST")
Sounds good!

2022-02-01 02:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +        @KotlinCleanup("use lateinit")
ditto - many variables need consideration. I feel this is a high priority class

2022-02-03 00:37 UTC, david-allison-1 requested changes
Yep, rebase caught some changes added by the new AGP

```
> Task :AnkiDroid:lintPlayRelease FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt:319: Error: Use requireArguments() instead of arguments!! [UseRequireInsteadOfGet from fragment-1.4.1]
            val position = arguments!!.getInt("position")
                           ~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt:330: Error: Use requireArguments() instead of arguments!! [UseRequireInsteadOfGet from fragment-1.4.1]
            mEditorPosition = arguments!!.getInt(EDITOR_POSITION_KEY)
                              ~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt:350: Error: Use requireArguments() instead of arguments!! [UseRequireInsteadOfGet from fragment-1.4.1]
            bottomNavigation.selectedItemId = arguments!!.getInt(EDITOR_VIEW_ID_KEY)
                                              ~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt:350: Error: Use requireArguments() instead of arguments!! [UseRequireInsteadOfGet from fragment-1.4.1]
            bottomNavigation.selectedItemId = arguments!!.getInt(EDITOR_VIEW_ID_KEY)
                                              ~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt:582: Error: Use requireArguments() instead of arguments!! [UseRequireInsteadOfGet from fragment-1.4.1]
            val noteId = arguments!!.getLong("noteId")
                         ~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt:656: Error: Use requireArguments() instead of arguments!! [UseRequireInsteadOfGet from fragment-1.4.1]
                arguments!!.getInt("position")
                ~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt:874: Error: Use requireArguments() instead of arguments!! [UseRequireInsteadOfGet from fragment-1.4.1]
            val oldPosition = arguments!!.getInt("position")
                              ~~~~~~~~~~~
```

```
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (106, 93): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type TemporaryModel?

e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (111, 57): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type TemporaryModel?
> Task :AnkiDroid:deleteSingleFileInGradle UP-TO-DATE
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (133, 89): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type TemporaryModel?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (143, 88): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type TemporaryModel?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (156, 57): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type TemporaryModel?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (188, 89): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type TemporaryModel?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (197, 93): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type TemporaryModel?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (201, 57): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type TemporaryModel?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (239, 89): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type TemporaryModel?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (276, 89): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type TemporaryModel?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (321, 89): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type TemporaryModel?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (347, 91): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type TemporaryModel?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (3[72](https://github.com/ankidroid/Anki-Android/runs/5026040888?check_suite_focus=true#step:8:72), 89): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type TemporaryModel?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (378, 89): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type TemporaryModel?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (387, 30): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ViewPager2?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (398, 30): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ViewPager2?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (446, 89): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type TemporaryModel?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (460, 30): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ViewPager2?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (4[75](https://github.com/ankidroid/Anki-Android/runs/5026040888?check_suite_focus=true#step:8:75), 84): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type TemporaryModel?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (483, 85): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type TemporaryModel?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (486, 30): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ViewPager2?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (501, 84): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type TemporaryModel?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (517, 40): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type TemporaryModel?
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt: (547, 81): Only sa [...]

2022-02-03 08:08 UTC, david-allison-1 commented
```
com.ichi2.anki.CardTemplateEditorTest > testDeleteTemplateWithGeneratedCards FAILED
    java.lang.NullPointerException
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment$SaveModelAndExitHandler.actualOnPostExecute(CardTemplateEditor.kt:735)
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment$SaveModelAndExitHandler.actualOnPostExecute(CardTemplateEditor.kt:716)
        at com.ichi2.async.TaskListenerWithContext.onPostExecute(TaskListenerWithContext.java:66)
        at com.ichi2.async.ForegroundTaskManager.executeTaskWithListener(ForegroundTaskManager.java:71)
        at com.ichi2.async.ForegroundTaskManager.launchCollectionTaskConcrete(ForegroundTaskManager.java:54)
        at com.ichi2.async.TaskManager.launchCollectionTask(TaskManager.java:93)
        at com.ichi2.anki.TemporaryModel.saveToDatabase(TemporaryModel.java:152)
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.onOptionsItemSelected(CardTemplateEditor.kt:558)
        at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:3154)
        at androidx.fragment.app.FragmentManager.dispatchOptionsItemSelected(FragmentManager.java:2937)
        at androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:427)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:334)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
        at org.robolectric.shadows.ShadowActivity.clickMenuItem(ShadowActivity.java:515)
        at com.ichi2.anki.CardTemplateEditorTest.testDeleteTemplateWithGeneratedCards(CardTemplateEditorTest.kt:356)

com.ichi2.anki.CardTemplateEditorTest > testDeleteTemplate FAILED
    java.lang.NullPointerException
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment$SaveModelAndExitHandler.actualOnPostExecute(CardTemplateEditor.kt:735)
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment$SaveModelAndExitHandler.actualOnPostExecute(CardTemplateEditor.kt:716)
        at com.ichi2.async.TaskListenerWithContext.onPostExecute(TaskListenerWithContext.java:66)
        at com.ichi2.async.ForegroundTaskManager.executeTaskWithListener(ForegroundTaskManager.java:71)
        at com.ichi2.async.ForegroundTaskManager.launchCollectionTaskConcrete(ForegroundTaskManager.java:54)
        at com.ichi2.async.TaskManager.launchCollectionTask(TaskManager.java:93)
        at com.ichi2.anki.TemporaryModel.saveToDatabase(TemporaryModel.java:152)
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.onOptionsItemSelected(CardTemplateEditor.kt:558)
        at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:3154)
        at androidx.fragment.app.FragmentManager.dispatchOptionsItemSelected(FragmentManager.java:2937)
        at androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:427)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:334)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
        at org.robolectric.shadows.ShadowActivity.clickMenuItem(ShadowActivity.java:515)
        at com.ichi2.anki.CardTemplateEditorTest.testDeleteTemplate(CardTemplateEditorTest.kt:157)

com.ichi2.anki.CardTemplateEditorTest > testTemplateAdd FAILED
    java.lang.NullPointerException
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment$SaveModelAndExitHandler.actualOnPostExecute(CardTemplateEditor.kt:735)
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment$SaveModelAndExitHandler.actualOnPostExecute(CardTemplateEditor.kt:716)
        at com.ichi2.async.TaskListenerWithContext.onPostExecute(TaskListenerWithContext.java:66)
        at com.ichi2.async.ForegroundTaskManager.executeTaskWithListener(ForegroundTaskManager.java:71)
        at com.ichi2.async.ForegroundTaskManager.launchCollectionTaskConcrete(ForegroundTaskManager.java:54)
        at com.ichi2.async.TaskManager.launchCollectionTask(TaskManager.java:93)
        at com.ichi2.anki.TemporaryModel.saveToDatabase(TemporaryModel.java:152)
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.onOptionsItemSelected(CardTemplateEditor.kt:558)
        at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:3154)
        at androidx.fragment.app.FragmentManager.dispatchOptionsItemSelected(FragmentManager.java:2937)
        at androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:427)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:334)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
        at org.robolectric.shadows.ShadowActivity.clickMenuItem(ShadowActivity.java:515)
        at com.ichi2.anki.CardTemplateEditorTest.testTemplateAdd(CardTemplateEditorTest.kt:202)

com.ichi2.anki.CardTemplateEditorTest > testEditTemplateContents FAILED
    java.lang.NullPointerException
        at com.ichi2.anki.CardTemplateEditor.showDiscardChangesDialog$lambda-0(CardTemplateEditor.kt:207)
        at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:410)
        at android.view.View.performClick(View.java:7140)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.robolectric.shadows.ShadowView$_View_$$Reflector23.performClick(Unknown Source)
        at org.robolectric.shadows.ShadowView.performClick(ShadowView.java:238)
        at android.view.View.performClick(View.java)
        at com.ichi2.anki.RobolectricTest.clickDialogButton(RobolectricTest.kt:186)
        at com.ichi2.anki.CardTemplateEditorTest.testEditTemplateContents(CardTemplateEditorTest.kt:[84](https://github.com/ankidroid/Anki-Android/runs/5048040189?check_suite_focus=true#step:8:84))

com.ichi2.anki.CardTemplateEditorTest > testDeletePendingAddExistingCardCount FAILED
    java.lang.NullPointerException
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment$SaveModelAndExitHandler.actualOnPostExecute(CardTemplateEditor.kt:735)
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment$SaveModelAndExitHandler.actualOnPostExecute(CardTemplateEditor.kt:716)
        at com.ichi2.async.TaskListenerWithContext.onPostExecute(TaskListenerWithContext.java:66)
        at com.ichi2.async.ForegroundTaskManager.executeTaskWithListener(ForegroundTaskManager.java:71)
        at com.ichi2.async.ForegroundTaskManager.launchCollectionTaskConcrete(ForegroundTaskManager.java:54)
        at com.ichi2.async.TaskManager.launchCollectionTask(TaskManager.java:[93](https://github.com/ankidroid/Anki-Android/runs/5048040189?check_suite_focus=true#step:8:93))
        at com.ichi2.anki.TemporaryModel.saveToDatabase(TemporaryModel.java:[152](https://github.com/ankidroid/Anki-Android/runs/5048040189?check_suite_focus=true#step:8:152))
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.onOptionsItemSelected(CardTemplateEditor.kt:558)
        at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:3[154](https://github.com/ankidroid/Anki-Android/runs/5048040189?check_suite_focus=true#step:8:154))
        at androidx.fragment.app.FragmentManager.dispatchOptionsItemSelected(FragmentManager.java:2937)
        at androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:427)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:334)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
        at org.robolectric.shadows.ShadowActivity.clickMenuItem(Shadow [...]

2022-05-10 13:14 UTC, closed without merging