[Kotlin Migration] LoadPronounciationActivity
ankidroid/Anki-Android pull request #10161
Opened 2022-01-10 19:03 UTC by Akshay0701

2022-01-10 22:09 UTC, david-allison-1 requested changes
```
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronounciationActivity.kt:54: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki.lint]
Fix the issues identified by lint, or add the following to your build script to proceed with errors:
    var mSource: String? = null
...
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2022-01-10 22:10 UTC, david-allison-1 requested changes
one nit, this could do with a manual test

2022-01-10 22:10 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronounciationActivity.kt
> +    private var mTranslationAddress: String? = null
`KotlinCleanup`: `lateinit`

2022-01-13 16:11 UTC, david-allison-1 requested changes

2022-01-13 16:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronounciationActivity.kt
> +        private var mAddress: String? = null
cleanup: lateInit (I think)

2022-01-13 16:13 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronounciationActivity.kt
> +         */
in kotlin there is no methods of get and set, so where must I put this comment?

2022-01-14 17:15 UTC, Akshay0701 commented
Tested this on devices, no crash

2022-01-14 18:16 UTC, david-allison-1 approved these changes
Thanks for your time here, LGTM

2022-01-16 20:42 UTC, mikehardy approved these changes

2022-01-16 23:26 UTC, merged