NF: Add more details to Kotlin Migration
ankidroid/Anki-Android pull request #10167
Opened 2022-01-11 15:17 UTC by Arthur-Milchior

Some details were not clear during my first try of this feature.

In particular, I didn't have the "commit" window. Instead I had a different
non-modal window, which did not offer as many option. So I had to explain how to
get the modal window.

I also added instructions about what to do if build fail, at the place where we
expect failure.

I also added sub-sections. This way, if the process fail, it's easier to know
where we are.

2022-01-11 20:17 UTC, mikehardy approved these changes
LGTM, for what it's worth, but David has been mowing through these more than I

2022-01-11 21:04 UTC, david-allison-1 requested changes
Looks good! Great to have a second pair of eyes on this

A few rewordings (all optional), I'd like to move the added standard git operations to an appendix to remove duplication and so an experienced user won't be bogged down by irrelevant content.

2022-01-11 21:04 UTC, david-allison-1 commented on docs/kotlin-migration.md
> +* Find the line `def className = ""`.
This should mention setting `def source = Source.MAIN` to `Source.TEST` / `Source.ANDROID_TEST` if the file was not in `/main`

2022-01-11 21:04 UTC, david-allison-1 commented on docs/kotlin-migration.md
> +If you already know how to amend in git, great. Otherwise, follow those steps:
This shouldn't be copy/pasted and should be moved to an appendix

2022-01-12 15:40 UTC, Arthur-Milchior commented on docs/kotlin-migration.md
> +* Find the line `def className = ""`.
Thanks. I have not understood this.
I assume that in this case, they should also build the test, and not only the main project. Or does "rebuild" rebuild all tests too?

2022-01-12 15:48 UTC, Arthur-Milchior commented on docs/kotlin-migration.md
> +If you already know how to amend in git, great. Otherwise, follow those steps:
I preferred to refer to the first section from the second one

2022-01-12 17:22 UTC, david-allison-1 commented on docs/kotlin-migration.md
> +* Find the line `def className = ""`.
They need to build the tests

2022-01-12 17:23 UTC, david-allison-1 commented on docs/kotlin-migration.md
> +If you already know how to amend in git, great. Otherwise, follow those steps:
OK! Not going to bikeshed.

2022-01-12 17:24 UTC, david-allison-1 reviewed
Thanks for this, one comment still open, but this looks so much better, thanks for your time

2022-01-12 18:22 UTC, Arthur-Milchior commented on docs/kotlin-migration.md
> +* Find the line `def className = ""`.
That's now explicitly specified

2022-01-12 20:58 UTC, david-allison-1 approved these changes
LGTM, merge after build on master passes

2022-01-16 19:39 UTC, merged