[Kotlin Migration] NoSuchDeckException
ankidroid/Anki-Android pull request #10196
Opened 2022-01-13 23:18 UTC by codingtosh

[Kotlin Migration] NoSuchDeckException 
package: com.ichi2.libanki.exception

2022-01-14 02:45 UTC, david-allison-1 requested changes

2022-01-14 02:45 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/exception/NoSuchDeckException.kt
> + * <br></br>
replace with newline

2022-01-14 20:28 UTC, codingtosh commented on AnkiDroid/src/main/java/com/ichi2/libanki/exception/NoSuchDeckException.kt
> + * <br></br>
Done, PTAL.

2022-01-14 21:28 UTC, david-allison-1 approved these changes
LGTM

2022-01-14 21:28 UTC, david-allison-1 commented
Note: I've added a "Good First Issue" to handle the `<br>` issue: https://github.com/ankidroid/Anki-Android/issues/10209

2022-01-16 20:56 UTC, mikehardy approved these changes

2022-01-17 02:38 UTC, merged