[Kotlin Migration] SchedTimingToday
ankidroid/Anki-Android pull request #10199
Opened 2022-01-13 23:30 UTC by codingtosh

[Kotlin Migration] SchedTimingToday 
package com.ichi2.libanki.backend.model

2022-01-14 02:46 UTC, david-allison-1 requested changes

2022-01-14 02:47 UTC, david-allison-1 requested changes
one nit, then good to go, no need for a `cleanup` here

2022-01-14 19:23 UTC, codingtosh commented on AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/SchedTimingToday.kt
> +     * Timestamp of the next day rollover.<br></br>
Done, PTAL.

2022-01-14 21:26 UTC, david-allison-1 approved these changes

2022-01-15 13:35 UTC, Akshay0701 requested changes
just two `<br>` missing, otherwise LGTM

2022-01-15 13:35 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/SchedTimingToday.kt
> +     * Timestamp of the next day rollover.
`<br/>`is missing

2022-01-15 13:35 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/SchedTimingToday.kt
> -    int days_elapsed();
`<br/>`is missing

2022-01-16 21:00 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/SchedTimingToday.kt
> +     * Timestamp of the next day rollover.
@Akshay0701 the br comment seems valid - if you require changes in a PR can you add the label "waiting for feedback"? When I work on AnkiDroid I move really quickly through PR searches defined by the labels, and if it has that label then I skip it until the label is removed. Helps me move faster :-)

2022-01-16 21:01 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/SchedTimingToday.kt
> +     * Timestamp of the next day rollover.
@Akshay0701 the br comment seems valid - if you require changes in a PR can you add the label "waiting for feedback"? When I work on AnkiDroid I move really quickly through PR searches defined by the labels, and if it has that label then I skip it until the label is removed. Helps me move faster :-)

2022-01-17 00:07 UTC, codingtosh commented on AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/SchedTimingToday.kt
> +     * Timestamp of the next day rollover.
@Akshay0701 The `<br>` tags  were replaced with a newline as per David's suggestion, PTAL
https://github.com/ankidroid/Anki-Android/pull/10199#discussion_r784472143

2022-01-17 02:22 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/SchedTimingToday.kt
> +     * Timestamp of the next day rollover.
Ah! I'm rolling through the queue now and re-checked this based on the update notification. I can see what you mean, after showing the resolved conversations above. Marking for merge. Thanks to both of you for checking + working through these migrations, much appreciated

2022-01-17 02:22 UTC, mikehardy approved these changes

2022-01-17 02:46 UTC, merged