[Kotlin Migration] DroidBackend
ankidroid/Anki-Android pull request #10197
Opened 2022-01-13 23:22 UTC by codingtosh

[Kotlin Migration] DroidBackend 
package com.ichi2.libanki.backend

2022-01-14 02:53 UTC, david-allison-1 requested changes

2022-01-14 02:53 UTC, david-allison-1 commented on AnkiDroid/build.gradle
> +        freeCompilerArgs += ["-Xjvm-default=all-compatibility"]
Could you explain this one in the commit message, or here

Typically this can be handled by adding an explicit override, but I'm open to a compiler option if it's safe to explicitly generate the overrides.

2022-01-14 02:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.kt
> +interface DroidBackend {
Cleanup: needs better nullable definitions

2022-01-17 18:52 UTC, codingtosh commented on AnkiDroid/build.gradle
> +        freeCompilerArgs += ["-Xjvm-default=all-compatibility"]
Wanted to retain as much as the old code so thought of using `@JvmDefault ` to avoid changing the other files, but since that got deprecated, this was the recommended way according to [this jetbrains' blogpost](https://blog.jetbrains.com/kotlin/2020/07/kotlin-1-4-m3-generating-default-methods-in-interfaces/)

Explicit overrides also sound reasonable, waiting for #10143 to get merged.

2022-03-03 16:40 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidV16Backend.kt
> +
I don't understand the spacing change here :thinking:  ?

2022-03-15 22:33 UTC, david-allison commented
```
> Task :AnkiDroid:lintPlayDebug FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.kt:1: Error: Tags were corrupted by the Kotlin migration. For example: <br></br> [KotlinMigrationFixLineBreaks from com.ichi2.anki.lint]
/*
~~
1 errors, 0 warnings
```

2022-03-15 22:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.kt
> +     * For the given timestamp, return minutes west of UTC in the local timezone.<br></br><br></br>
tag issues in this comment

2022-03-15 22:45 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.kt
> +     * For the given timestamp, return minutes west of UTC in the local timezone.</br></br>
```suggestion
     * For the given timestamp, return minutes west of UTC in the local timezone.
```

2022-03-15 22:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.kt
> +     * eg, Australia at +10 hours is -600.</br>
```suggestion
     * eg, Australia at +10 hours is -600.<br>
```

2022-03-15 23:03 UTC, codingtosh commented on AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidV16Backend.kt
> +
Just an oversight, not included in the latest patchset, ptal.

2022-03-16 00:58 UTC, david-allison approved these changes
Thanks!

2022-03-18 21:22 UTC, mikehardy approved these changes
:boom:

2022-03-18 21:22 UTC, merged