[Kotlin Migration] Counts
ankidroid/Anki-Android pull request #10192
Opened 2022-01-13 22:59 UTC by codingtosh

[Kotlin Migration] Counts 
package com.ichi2.libanki.sched

2022-01-14 02:41 UTC, david-allison-1 requested changes

2022-01-14 02:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Counts.kt
> +            else -> throw RuntimeException("Index $index does not exist.")
Cleanup: I think we can remove the `else` branch in Kotlin

2022-01-14 20:20 UTC, codingtosh commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Counts.kt
> +            else -> throw RuntimeException("Index $index does not exist.")
asd

2022-01-14 20:26 UTC, codingtosh commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Counts.kt
> +            else -> throw RuntimeException("Index $index does not exist.")
getting this warning: 
`'when' expression on enum is recommended to be exhaustive, add 'NEW' branch or 'else' branch instead`

2022-01-14 21:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Counts.kt
> +            else -> throw RuntimeException("Index $index does not exist.")
Looks like we handle `NEW`, but not worth questioning further

2022-01-14 21:27 UTC, david-allison-1 approved these changes
LGTM, ignoring one nit

2022-01-16 20:53 UTC, mikehardy approved these changes

2022-01-17 02:10 UTC, merged