[Kotlin Migration] CollectionTest
ankidroid/Anki-Android pull request #10218
Opened 2022-01-15 14:25 UTC by Akshay0701

2022-01-20 21:48 UTC, david-allison-1 requested changes

2022-01-20 21:48 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
> +        MatcherAssert.assertThat("db should be closed", CollectionHelper.getInstance().colIsOpen(), Matchers.`is`(false))
For discussion: Given that tests are much less likely to be broken, I feel it's worth fixing `MatcherAssert/Assert etc...` having imports removed, and changing `is` to something valid for Kotlin (`equalTo`, maybe `eq` is defined)

2022-01-23 20:59 UTC, david-allison-1 requested changes

2022-01-23 20:59 UTC, david-allison-1 commented on AnkiDroid/kotlinMigration.gradle
> +def className = "com/ichi2/libanki/CollectionTest.kt"
`/`

2022-02-07 13:00 UTC, Akshay0701 commented on AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
> +        MatcherAssert.assertThat("db should be closed", CollectionHelper.getInstance().colIsOpen(), Matchers.`is`(false))
I agree, did it

2022-02-07 13:12 UTC, david-allison-1 requested changes

2022-02-07 13:12 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
> +        MatcherAssert.assertThat("db should be closed", CollectionHelper.getInstance().colIsOpen(), equalTo(false))
`MatcherAssert` import

2022-02-07 13:12 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
> +        Assert.assertEquals(2, col.cardCount().toLong())
`Assert` import

2022-02-07 13:12 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
> +        Assert.assertEquals(2, n.toLong())
`toLong()` shouldn't be needed

2022-02-07 13:12 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
> +        MatcherAssert.assertThat(c0.q(), Matchers.containsString("three"))
`Matchers` import

2022-02-07 13:12 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
> +        Assert.assertEquals(-0x3d594fc1, col.db.queryLongScalar("select csum from notes"))
ouch! Can we revert this to `0xc2a6b03f`?

2022-02-11 17:17 UTC, david-allison-1 commented
````
com.ichi2.libanki.CollectionTest > test_timestamps FAILED
    java.lang.AssertionError: expected: java.lang.Long<5> but was: java.lang.Integer<5>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at com.ichi2.libanki.CollectionTest.test_timestamps(CollectionTest.kt:176)
```

2022-02-11 17:19 UTC, david-allison-1 requested changes
This looks beautiful, consider this an approve once the test passes

2022-02-11 18:05 UTC, Akshay0701 commented
removed some more toLong, hope this time it works,

I can't able to check this test locally, because i always get javaheap error, i tried every other solution to solve this but same java heap error occurring while running the tests, i assume its my ram issue...

2022-02-11 18:05 UTC, david-allison-1 commented
> removed some more toLong, hope this time it works,
> 
> I can't able to check this test locally, because i always get javaheap error, i tried every other solution to solve this but same java heap error occurring while running the tests, i assume its my ram issue...

Could you mention this in Discord. We've seen this problem before and it should be investigated.

2022-03-03 15:49 UTC, mikehardy commented
```

com.ichi2.libanki.CollectionTest > test_timestamps FAILED
    java.lang.AssertionError: expected: java.lang.Long<105> but was: java.lang.Integer<105>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at com.ichi2.libanki.CollectionTest.test_timestamps(CollectionTest.kt:180)
```

2022-03-03 20:36 UTC, david-allison requested changes
Didn't submit this one, should be easy to fix

2022-06-25 21:55 UTC, mikehardy approved these changes
I can't see any comments here that are not addressed
running CI tasks locally after rebase to make sure

2022-06-25 21:56 UTC, mikehardy commented
Wow, this is from *January* :sweat_smile: :hourglass_flowing_sand:

2022-06-25 22:00 UTC, merged