[Kotlin Migration] FlagTest
ankidroid/Anki-Android pull request #10219
Opened 2022-01-15 14:42 UTC by Akshay0701

2022-01-23 20:59 UTC, david-allison-1 requested changes

2022-01-23 20:59 UTC, david-allison-1 commented on AnkiDroid/kotlinMigration.gradle
> +def className = "com/ichi2/libanki/FlagTest.kt"
`/`

2022-02-03 11:42 UTC, david-allison-1 requested changes

2022-02-03 11:42 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/libanki/FlagTest.kt
> +        Assert.assertEquals(0, c.userFlag().toLong())
remove `Assert` and `ToLong()`

2022-02-06 12:21 UTC, david-allison-1 approved these changes
Lovely!

2022-02-06 12:22 UTC, david-allison-1 requested changes
```
w: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/libanki/FlagTest.kt: (20, 24): 'Assert' is deprecated. Deprecated in Java
> Task :AnkiDroid:compilePlayDebugUnitTestKotlin FAILED
```

Remove the import and use the non-deprecated version

2022-02-12 16:28 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/libanki/FlagTest.kt
> +        val origBits = 5 shl 3
Is there a trouble in keeping it in binary? If we simplify, then we could also directly put 40. 
5 seems less clear that 101 of we want to understand the bits

2022-02-13 05:35 UTC, Akshay0701 commented on AnkiDroid/src/test/java/com/ichi2/libanki/FlagTest.kt
> +        val origBits = 5 shl 3
to be honest, I have no understanding of binary or bits, and kotlin conversion did these changes, 
I will request @david-allison and @mikehardy or any other contributor to discuss this...

2022-02-13 11:58 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/FlagTest.kt
> +        val origBits = 5 shl 3
I agree with Arthur. `0b101` is more sensible. 

----

As a quick introduction to binary: it's a different way to represent a number (base 2 instead of base 10)

Each digit represents a power of 2, with the rightmost representing `2^0 = 1`, the second rightmost representing`2^1 = 2` ... `2^2 = 4` and the represented value doubles each time

`0b` = use binary to represent an integer.  
`1` = 1 × 2^2 = 4  
`0` = 0 × 2^1 = 0
`1` = 1 × 2^0 = 1

`0b101` = 4 + 0 + 1 = 5

So:

`0b111` = 4 + 2 + 1 = 7
`0b010` = 0 + 2 + 0 = 2
`0b1000` = 8 + 0 + 0 + 0 = 8

2022-03-03 15:47 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/libanki/FlagTest.kt
> +        val origBits = 5 shl 3
needs binary comment addressed

2022-03-03 17:29 UTC, Akshay0701 commented on AnkiDroid/src/test/java/com/ichi2/libanki/FlagTest.kt
> +        val origBits = 5 shl 3
addressed

2022-03-03 17:56 UTC, merged