[Kotlin Migration] MultimediaEditFieldActivityTestBase
ankidroid/Anki-Android pull request #10215
Opened 2022-01-15 14:05 UTC by Akshay0701

2022-01-19 01:24 UTC, david-allison-1 requested changes
On tests: if they pass and comments aren't removed, I'm happy

2022-01-19 01:24 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivityTestBase.kt
> +        Mockito.`when`(activity.resources).thenReturn(editFieldActivity.resources)
We typically want to use the `mockito-kotlin` library to remove the `when`. 

Could you `@KotlinCleanup` here (maybe we need a disabled lint check for this as it's a common issue/operation - your call).

2022-01-31 17:51 UTC, Akshay0701 commented on AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivityTestBase.kt
> +        Mockito.`when`(activity.resources).thenReturn(editFieldActivity.resources)
do i need to use `[this](https://github.com/mockito/mockito-kotlin)` libary

2022-03-03 19:21 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivityTestBase.kt
> +        Mockito.`when`(activity.resources).thenReturn(editFieldActivity.resources)
I'm not sure this is actually a valid comment, the scoped storage area uses when also, and I haven't seen any references to `mockito-kotlin` in the codebase when I do full text search

no results on mockito-kotlin
```
mike@bistromath:~/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/src (master) % grep -ri mockito-kotlin *
mike@bistromath:~/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/src (master) % 
```

lots of results on when in kotlin files
```
test/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldControllerTest.kt:import org.mockito.Mockito.`when`
test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileTest.kt:            Mockito.doAnswer { Timber.w("testing: do nothing on copy") }.`when`(it).copyFile(any(), any())
test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileTest.kt:                Mockito.doThrow(TestException("test-copyFile()")).`when`(it).copyFile(any(), any())
test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileTest.kt:            Mockito.doThrow(TestException("test-deleteFile()")).`when`(it).deleteFile(any())
test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileTest.kt:                Mockito.doThrow(TestException("test-deleteFile()")).`when`(it).deleteFile(any())
```

2022-03-03 19:22 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivityTestBase.kt
> +        Mockito.`when`(activity.resources).thenReturn(editFieldActivity.resources)
kotlin cleanup was added

2022-03-03 19:23 UTC, mikehardy approved these changes
LGTM - pending local check after rebasing to current master

2022-03-03 19:27 UTC, david-allison approved these changes
If CI passes, I'm happy

2022-03-03 19:33 UTC, mikehardy commented
went through locally no problem vs API24 / API31, CI e2e was a flake, going to merge

2022-03-03 19:33 UTC, merged