[Kotlin Migration] TagsTest
ankidroid/Anki-Android pull request #10220
Opened 2022-01-15 14:48 UTC by Akshay0701

2022-01-23 20:59 UTC, david-allison-1 requested changes

2022-01-23 20:59 UTC, david-allison-1 commented on AnkiDroid/kotlinMigration.gradle
> +def className = "com/ichi2/libanki/TagsTest.kt"
`/`

2022-03-03 15:46 UTC, mikehardy commented
I've converted all the PRs that have sat for a long time as waiting for freedback to draft so I can exclude them in PR searches, same here

2022-04-18 15:58 UTC, david-allison commented
Fixed in e46c876d22267df9ffa904e1da0568e4385517de

2022-04-18 15:58 UTC, closed without merging