[Kotlin Migration] UtilsIntegrationTest
ankidroid/Anki-Android pull request #10222
Opened 2022-01-15 15:03 UTC by Akshay0701

2022-01-23 20:59 UTC, david-allison-1 requested changes

2022-01-23 20:59 UTC, david-allison-1 commented on AnkiDroid/kotlinMigration.gradle
> +def className = "com/ichi2/libanki/UtilsIntegrationTest.kt"
`/`

2022-03-03 15:02 UTC, mikehardy approved these changes

2022-03-03 15:26 UTC, mikehardy commented
comment addressed, passes local checking after rebasing

2022-03-03 15:26 UTC, merged