[Kotlin Migration] BasicImageFieldControllerTest
ankidroid/Anki-Android pull request #10225
Opened 2022-01-15 15:16 UTC by Akshay0701

2022-01-23 20:54 UTC, david-allison-1 requested changes
LGTM otherwise

2022-01-23 20:54 UTC, david-allison-1 commented on AnkiDroid/kotlinMigration.gradle
> +def className = "com/ichi2/anki/multimediacard/fields/BasicImageFieldControllerTest.kt"
`/`

2022-02-03 00:01 UTC, david-allison-1 requested changes
Coming back to this: could we re-import `MatcherAssert, Matchers, Mockito`

Only nits though, happy regardless

2022-02-03 08:07 UTC, david-allison-1 approved these changes

2022-02-03 08:52 UTC, ShridharGoel approved these changes

2022-02-03 08:53 UTC, merged

2022-02-03 10:43 UTC, david-allison-1 commented
@ShridharGoel please rebase merge, rather than squash merge in future. 

We lose `git blame` otherwise.

2022-02-04 12:05 UTC, ShridharGoel commented
@david-allison-1 Okay, thanks for letting me know.

Is there a way to fix it for this PR?

2022-02-04 12:08 UTC, Akshay0701 commented
yes but it's okay for this pr, because it is a test, and the chances of breaking tests is also less, so no worries for now

2022-02-04 13:13 UTC, david-allison-1 commented
Not without rebasing master

2022-02-05 16:06 UTC, mikehardy commented
@ShridharGoel  Also when I merge PRs I add them to the next release milestone - which is what I use to make the changelogs for release. And of course, that's not documented anywhere ;-)