String feedback_manual_toast_text and the reference to it has been updated
ankidroid/Anki-Android pull request #10237
Opened 2022-01-16 17:22 UTC by AayushSolanki

Fixes #10029
String feedback_manual_toast_text has been edited with appropriate message and the reference to it is also updated.

2022-01-16 17:55 UTC, Akshay0701 requested changes
Hey @AayushSolanki,
Thank you for your contribution...

I have one question on feedback_for_manual_toast_text

2022-01-16 17:55 UTC, Akshay0701 commented on AnkiDroid/src/main/res/values/05-feedback.xml
> +    <string name="feedback_for_manual_toast_text">An error report is being prepared for the developers…</string>
can I get to know why did you mention the `error report`, did we encounter any bug while showing this toast message? 
to what I understand by issues discussion is our main aim for this fix is to ensure users that there is no problem, right?

According to @ShridharGoel from [comment](https://github.com/ankidroid/Anki-Android/issues/10029#issuecomment-1005136940), I think we should use `A report is being generated for the reference of developers`

2022-01-16 18:01 UTC, mikehardy commented on AnkiDroid/src/main/res/values/05-feedback.xml
> +    <string name="feedback_for_manual_toast_text">An error report is being prepared for the developers…</string>
@Akshay0701 this was by specific request from the first iteration of this PR if I understand correctly: https://github.com/ankidroid/Anki-Android/pull/10120#pullrequestreview-852502937

2022-01-16 18:01 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +                toastBuilder.setResText(R.string.feedback_for_manual_toast_text);
I am also curious to know the reason why you changed the `feedback_manual_toast_text` -> `feedback_for_manual_toast_text` 

previous names looks good to me.

2022-01-16 18:03 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +                toastBuilder.setResText(R.string.feedback_for_manual_toast_text);
we needed to force a re-translation, to do that you have to change the key

2022-01-16 18:06 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +                toastBuilder.setResText(R.string.feedback_for_manual_toast_text);
Oh okay🤝

2022-01-17 05:27 UTC, Akshay0701 commented
Some issues:
```
> Task :AnkiDroid:compileAmazonDebugAndroidTestJavaWithJavac FAILED
/Users/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ACRATest.java:131: error: cannot find symbol
        assertToastMessage(R.string.feedback_manual_toast_text);
                                   ^
  symbol:   variable feedback_manual_toast_text
  location: class string
/Users/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ACRATest.java:214: error: cannot find symbol
        assertToastMessage(R.string.feedback_manual_toast_text);
                                   ^
  symbol:   variable feedback_manual_toast_text
  location: class string
/Users/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ACRATest.java:226: error: cannot find symbol
        assertToastMessage(R.string.feedback_manual_toast_text);
                                   ^
  symbol:   variable feedback_manual_toast_text
  location: class string
3 errors
```

2022-01-17 06:13 UTC, Akshay0701 approved these changes
@AayushSolanki Thanks,
LGTM, wanting for Shridhar's review...

2022-01-17 11:33 UTC, ShridharGoel approved these changes
Looks good.

2022-01-17 11:45 UTC, ShridharGoel approved these changes
Looks good.

2022-01-17 11:47 UTC, merged

2022-03-06 21:48 UTC, mikehardy commented
Hi there! **JANUARY** OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [January 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-01-01..2022-01-31) (I'll follow this with the same process for February in a week)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of January)

Thanks!

2022-03-27 17:24 UTC, AayushSolanki commented
> Hi there! **JANUARY** OpenCollective Notice
> 
> Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [January 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-01-01..2022-01-31) (I'll follow this with the same process for February in a week)
> 
> If you are interested in compensation for this work, the process with details is here:
> 
> https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid
> 
> (I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of January)
> 
> Thanks!

Thank you @mikehardy for the notice but i have contributed only for the sake of gaining knowledge and to give my contribution to the app and will be definitely contributing in future i don't want any compensation for my contribution.