[Kotlin Migration] GestureProcessorTest
ankidroid/Anki-Android pull request #10232
Opened 2022-01-16 10:50 UTC by Akshay0701

2022-01-23 20:51 UTC, david-allison-1 requested changes

2022-01-23 20:51 UTC, david-allison-1 commented on AnkiDroid/kotlinMigration.gradle
> +def className = "com/ichi2/anki/cardviewer/GestureProcessorTest.kt"
`/com`

2022-01-23 20:51 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
> +            utilities!!.`when`<Any> { ViewConfiguration.get(ArgumentMatchers.any()) }.thenReturn(Mockito.mock(ViewConfiguration::class.java))
Untested: try `<ViewConfiguration>` to fix the test error. 

Needs looking at again @Akshay0701

2022-02-01 02:26 UTC, david-allison-1 requested changes
Tests fail. provided fix in comments

2022-02-01 02:26 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
> +        fun before() {
Could you revert the fix that I previously suggested.

Pulled the change. The proper fix is to add `@JvmStatic`

2022-02-01 02:27 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
> +        private var utilities: MockedStatic<ViewConfiguration>? = null
let's make this `lateinit` - no need for a `cleanup` since we're in test code

2022-02-07 12:44 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
> +        fun before() {
Add `@JvmStatic` to `before()`, unless this was tested and worked with it on `utilities`

2022-04-18 15:57 UTC, david-allison commented
Done in 410d88700f9127b90ddbfa86adc55144a2649b5f

2022-04-18 15:57 UTC, closed without merging