[Kotlin Migration] CollectionLoader
ankidroid/Anki-Android pull request #10249
Opened 2022-01-19 05:36 UTC by codingtosh

[Kotlin Migration] CollectionLoader 
package: com.ichi2.async

2022-01-19 15:33 UTC, codingtosh commented
@Akshay0701 Could you please kick off the CI here?

2022-01-20 21:44 UTC, david-allison-1 requested changes
minor nit, LGTM otherwise

2022-01-20 21:44 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionLoader.kt
> +// #7108: AsyncTask
move the comment to be on the same line as the suppress

2022-01-21 01:39 UTC, codingtosh commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionLoader.kt
> +// #7108: AsyncTask
Since we're extending `android.os.AsyncTask<Void?, Void?, Collection?>()`, had to suppress the warning at class level. Though redundant, I have added the annotation within the class again wherever it was originally required for better readability. PTAL.

2022-01-21 03:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionLoader.kt
> +// #7108: AsyncTask
Seemed reasonable to me, thanks!

2022-01-21 03:41 UTC, david-allison-1 approved these changes
LGTM

2022-01-21 12:59 UTC, mikehardy approved these changes

2022-01-21 12:59 UTC, merged