[Kotlin Migration] WrongId
ankidroid/Anki-Android pull request #10253
Opened 2022-01-19 22:05 UTC by puranjayK

[Kotlin Migration] WrongId
package com.ichi2.libanki

2022-01-19 22:25 UTC, david-allison-1 requested changes
First commit looks good, could you rebase the second commit to fix the issue

2022-01-19 22:25 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/WrongId.kt
> + * Copyright (c) 2020 Arthur Milchior <arthur></arthur>@milchior.fr>                              *
The copyright header was corrupted. Can you make sure it's not changed.

This should be flagged as a lint warning within Android Studio

2022-01-20 06:40 UTC, puranjayK commented on AnkiDroid/src/main/java/com/ichi2/libanki/WrongId.kt
> + * Copyright (c) 2020 Arthur Milchior <arthur></arthur>@milchior.fr>                              *
Done.

2022-01-20 12:24 UTC, david-allison-1 commented
Please squash the final two commits so this PR only contains two commits:

* Rename
* Conversion

2022-01-20 12:50 UTC, puranjayK commented
> Please squash the final two commits so this PR only contains two commits:
> 
> * Rename
> * Conversion

Done

2022-01-20 13:40 UTC, Akshay0701 requested changes

2022-01-20 13:40 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/libanki/WrongId.kt
> + * this program.  If not, see <http:></http:>//www.gnu.org/licenses/>.                           *
copyright header got corrupted, could you revert this change.

2022-01-20 13:43 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/libanki/WrongId.kt
> + * this program.  If not, see <http:></http:>//www.gnu.org/licenses/>.                           *
instead of fixing this manually, it would be good if you simply paste the `WrongId.java` file copyright header here.

2022-01-20 14:53 UTC, puranjayK commented on AnkiDroid/src/main/java/com/ichi2/libanki/WrongId.kt
> + * this program.  If not, see <http:></http:>//www.gnu.org/licenses/>.                           *
Done.

2022-01-20 14:57 UTC, Akshay0701 approved these changes

2022-01-20 14:57 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/libanki/WrongId.kt
> + */
(really sorry to pin again and again for this header) you have to copy-paste the entire copy right header to avoid these unnecessary changes.

```

/****************************************************************************************
 * Copyright (c) 2020 Arthur Milchior <arthur@milchior.fr>                              *
 *                                                                                      *
 * This program is free software; you can redistribute it and/or modify it under        *
 * the terms of the GNU General Public License as published by the Free Software        *
 * Foundation; either version 3 of the License, or (at your option) any later           *
 * version.                                                                             *
 *                                                                                      *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY      *
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A      *
 * PARTICULAR PURPOSE. See the GNU General Public License for more details.             *
 *                                                                                      *
 * You should have received a copy of the GNU General Public License along with         *
 * this program.  If not, see <http://www.gnu.org/licenses/>.                           *
 ****************************************************************************************/
```

2022-01-20 14:59 UTC, Akshay0701 requested changes

2022-01-20 14:59 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/libanki/WrongId.kt
> + */
(really sorry to pin again and again for this header) you have to copy-paste the entire copy right header to avoid these unnecessary changes.

```

/****************************************************************************************
 * Copyright (c) 2020 Arthur Milchior <arthur@milchior.fr>                              *
 *                                                                                      *
 * This program is free software; you can redistribute it and/or modify it under        *
 * the terms of the GNU General Public License as published by the Free Software        *
 * Foundation; either version 3 of the License, or (at your option) any later           *
 * version.                                                                             *
 *                                                                                      *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY      *
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A      *
 * PARTICULAR PURPOSE. See the GNU General Public License for more details.             *
 *                                                                                      *
 * You should have received a copy of the GNU General Public License along with         *
 * this program.  If not, see <http://www.gnu.org/licenses/>.                           *
 ****************************************************************************************/
```

2022-01-20 16:42 UTC, puranjayK commented on AnkiDroid/src/main/java/com/ichi2/libanki/WrongId.kt
> + */
I have copy pasted this whole header.

2022-01-21 07:26 UTC, david-allison-1 approved these changes
Looks good to me, thanks! 👍👍

2022-01-21 07:27 UTC, david-allison-1 requested changes
Wait... additional files have been changed. Can you rebase this onto the current `master`?

2022-01-21 07:48 UTC, puranjayK commented
> Wait... additional files have been changed. Can you rebase this onto the current `master` and ensure that you're only changing `WrongId` and `kotlinMigration.gradle`

Actually I have another open PR #10021 which has commits on my master branch. So should I proceed with rebasing?

2022-01-21 07:50 UTC, Akshay0701 commented
Try you can rebase with upstream-master

2022-01-21 08:00 UTC, puranjayK commented
> Try if you can rebase with upstream-master

PTAL @Akshay0701 @david-allison-1

2022-01-21 08:18 UTC, david-allison-1 approved these changes
LGTM

2022-01-21 10:25 UTC, Akshay0701 approved these changes
LGTM, Thanks for the efforts @puranjayK

2022-01-21 13:08 UTC, merged