[Kotlin Migration] Consts
ankidroid/Anki-Android pull request #10263
Opened 2022-01-23 20:52 UTC by puranjayK

[Kotlin Migration] Consts
package com.ichi2.libanki

2022-01-23 21:20 UTC, david-allison-1 submitted a review, later dismissed
One question for discussion

I think we should hold this one for a while if it's an automated change. I prefer the Java here due to the locality of the annotations

2022-01-23 21:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    annotation class NEW_CARD_ORDER
Were these moved in automatically by lint? 

It would make more sense to move them closer to the definitions

2022-01-23 21:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    @kotlin.annotation.Retention(AnnotationRetention.SOURCE)
import `Retention`

2022-01-24 19:00 UTC, puranjayK commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    annotation class NEW_CARD_ORDER
Yes all this was done automatically. 
The only change I made was changing the annotation to `@kotlin.annotation.Retention(AnnotationRetention.SOURCE)`, otherwise I was getting a build failure with the previous one.

2022-01-24 19:01 UTC, puranjayK commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    @kotlin.annotation.Retention(AnnotationRetention.SOURCE)
I should amend which commit - 1st or 2nd?

2022-01-24 22:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    @kotlin.annotation.Retention(AnnotationRetention.SOURCE)
Second - the kotlin annotation should have been added here

2022-01-24 22:36 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    annotation class NEW_CARD_ORDER
@mikehardy @Arthur-Milchior 

Is this an acceptable change? I'd personally like to hold off on this for a while to see if we can make the lint less strict around annotation classes (or if Kotlin has different structures which work better, such as valued enums)

2022-02-08 15:03 UTC, puranjayK commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    @kotlin.annotation.Retention(AnnotationRetention.SOURCE)
Done.

2022-02-09 08:27 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    annotation class NEW_CARD_ORDER
I've no opinion. Really don't know anything about how Kotlin works. But unless there is a trouble with keeping constants in Java, I'm totally fine waiting.
I mean, Kotlin is often more readable, but with constant, there is not as much gain as with most other classes

2022-03-03 16:20 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    annotation class NEW_CARD_ORDER
@david-allison as I sweep through old PRs I find I feel much more strongly about partially finished work than perfection. We have an incredible amount of partially finished work and I think perfection to some extent is the root cause, as it blocks completion. Of course this is a tension between quality (of developer experience in this case) and some idea of "progress", but I think finishing Kotlin migration (as "progress") vs "location of annotation classes" here may be resolved by simple comments saying to edit the annotation classes that use the constants below if you change the constants, then moving on

$0.02

2022-03-03 16:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    annotation class NEW_CARD_ORDER
@puranjayK what was "the previous one" you mentioned? 

I tried to move those three lines and put them below the constants, and compilation was fine and `./gradlew lint` was fine. So I'd assume that we can just move it back manually. Will you do it @puranjayK or do you want to leave this PR and let somebody else finish it?

2022-03-03 17:07 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    annotation class NEW_CARD_ORDER
@Arthur-Milchior I think you might need to run `./gradle ktlint` ? (vs lint) - but not sure! did not check locally

2022-03-03 17:45 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    annotation class NEW_CARD_ORDER
> Task 'ktlint' is ambiguous in project ':AnkiDroid'. Candidates are: 'ktlintAmazonDebugSourceSetCheck', 'ktlintAmazonDebugSourceSetFormat', 'ktlintAmazonReleaseSourceSetCheck', 'ktlintAmazonReleaseSourceSetFormat', 'ktlintAmazonSourceSetCheck', 'ktlintAmazonSourceSetFormat', 'ktlintAndroidTestAmazonDebugSourceSetCheck', 'ktlintAndroidTestAmazonDebugSourceSetFormat', 'ktlintAndroidTestAmazonSourceSetCheck', 'ktlintAndroidTestAmazonSourceSetFormat', 'ktlintAndroidTestDebugSourceSetCheck', 'ktlintAndroidTestDebugSourceSetFormat', 'ktlintAndroidTestPlayDebugSourceSetCheck', 'ktlintAndroidTestPlayDebugSourceSetFormat', 'ktlintAndroidTestPlaySourceSetCheck', 'ktlintAndroidTestPlaySourceSetFormat', 'ktlintAndroidTestReleaseSourceSetCheck', 'ktlintAndroidTestReleaseSourceSetFormat', 'ktlintAndroidTestSourceSetCheck', 'ktlintAndroidTestSourceSetFormat', 'ktlintCheck', 'ktlintDebugSourceSetCheck', 'ktlintDebugSourceSetFormat', 'ktlintFormat', 'ktlintGenerateBaseline', 'ktlintKotlinScriptCheck', 'ktlintKotlinScriptFormat', 'ktlintMainSourceSetCheck', 'ktlintMainSourceSetFormat', 'ktlintPlayDebugSourceSetCheck', 'ktlintPlayDebugSourceSetFormat', 'ktlintPlayReleaseSourceSetCheck', 'ktlintPlayReleaseSourceSetFormat', 'ktlintPlaySourceSetCheck', 'ktlintPlaySourceSetFormat', 'ktlintReleaseSourceSetCheck', 'ktlintReleaseSourceSetFormat', 'ktlintTestAmazonDebugSourceSetCheck', 'ktlintTestAmazonDebugSourceSetFormat', 'ktlintTestAmazonReleaseSourceSetCheck', 'ktlintTestAmazonReleaseSourceSetFormat', 'ktlintTestAmazonSourceSetCheck', 'ktlintTestAmazonSourceSetFormat', 'ktlintTestDebugSourceSetCheck', 'ktlintTestDebugSourceSetFormat', 'ktlintTestPlayDebugSourceSetCheck', 'ktlintTestPlayDebugSourceSetFormat', 'ktlintTestPlayReleaseSourceSetCheck', 'ktlintTestPlayReleaseSourceSetFormat', 'ktlintTestPlaySourceSetCheck', 'ktlintTestPlaySourceSetFormat', 'ktlintTestReleaseSourceSetCheck', 'ktlintTestReleaseSourceSetFormat', 'ktlintTestSourceSetCheck', 'ktlintTestSourceSetFormat'


Also, there were some AmazonLint issue, but unrelated to Consts (for exhaustivity)

2022-03-03 17:51 UTC, puranjayK commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    annotation class NEW_CARD_ORDER
I'll move the three lines if that is fine. 
The 'previous one' was `@Retention(RetentionPolicy.SOURCE)`

2022-03-03 17:56 UTC, david-allison approved these changes
Only had one comment, I feel that's resolved (fine to move annotation classes)

2022-03-03 18:25 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    annotation class NEW_CARD_ORDER
@puranjayK sure - whatever it takes to move it forward :-)

2022-03-03 18:26 UTC, mikehardy commented
Okay - I think current status on this is to see if moving the annotation classes back up near constant definitions is okay (criteria: passes `./gradlew ktlintCheck`), and if it does we merge, if it does not pass ktlintCheck that is still okay, we should just leave a constant near the constant definitions that if you edit them you need to edit the annotation classes down below - then we merge

2022-03-03 18:35 UTC, puranjayK commented
> Okay - I think current status on this is to see if moving the annotation classes back up near constant definitions is okay (criteria: passes `./gradlew ktlintCheck`), and if it does we merge, if it does not pass ktlintCheck that is still okay, we should just leave a constant near the constant definitions that if you edit them you need to edit the annotation classes down below - then we merge

So the conclusion is that I move them close to the definitions?

2022-03-03 18:46 UTC, mikehardy commented
My statement was a decision tree and specified which actions to take for the result of each attempt.
Moving them close to definitions is the first thing to try yes
It may be that moving them close to definitions fails `./gradlew ktlintCheck`, if so I explained what to do

2022-03-03 19:29 UTC, Arthur-Milchior commented
I moved one close to definition, and then ran `./gradlew ktlintCheck` and add no issue. 
So yeah, just move the interfaces near the constants

2022-03-06 23:07 UTC, mikehardy requested changes
This is just waiting on moving `annotation class` lines up near the const definitions if i understand correctly.

Then it's good for merge

2022-03-09 18:30 UTC, puranjayK commented
> This is just waiting on moving `annotation class` lines up near the const definitions if i understand correctly.
> 
> Then it's good for merge

Done. PTAL

2022-03-09 20:43 UTC, david-allison approved these changes
Still looks great. One optional suggestion

2022-03-09 20:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    @Retention(AnnotationRetention.SOURCE)
May want to import `AnnotationRetention.SOURCE` (as was done in Java) to change this line to `@Retention(SOURCE)`

2022-03-11 21:40 UTC, mikehardy approved these changes
I think this is fine as is, I'd rather keep moving and work the PR queue down - thanks @puranjayK !

2022-03-11 21:51 UTC, merged