[Kotlin Migration] CardBrowserSearchView
ankidroid/Anki-Android pull request #10266
Opened 2022-01-24 22:20 UTC by puranjayK

[Kotlin Migration] CardBrowserSearchView
package com.ichi2.ui

2022-01-24 22:34 UTC, david-allison-1 requested changes
CI failure - could you rebase the fix in
This should have been handled in the pre-commit hook

```
* What went wrong:
Execution failed for task ':AnkiDroid:ktlintMainSourceSetCheck'.
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt:1:1 File must end with a newline (\n)
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.ConsoleReportWorkAction
   > KtLint found code style violations. Please see the following reports:
     - /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/build/reports/ktlint/ktlintMainSourceSetCheck/ktlintMainSourceSetCheck.txt
```

2022-01-25 09:19 UTC, david-allison-1 approved these changes
LGTM

2022-01-25 09:34 UTC, Akshay0701 requested changes
Hey @puranjayK, Thank you for the contributions...

attribute `attrs` from constructor was nonnull in java file, add a kotlinCleanup

2022-01-25 09:34 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt
> +    constructor(context: Context, attrs: AttributeSet?, defStyleAttr: Int) : super(context, attrs, defStyleAttr) {}
add kotlinCleanup: `make attrs nonnull`

2022-01-25 09:49 UTC, puranjayK commented on AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt
> +    constructor(context: Context, attrs: AttributeSet?, defStyleAttr: Int) : super(context, attrs, defStyleAttr) {}
Done. PTAL

2022-01-25 19:31 UTC, sud007 approved these changes
Changes look fine

2022-01-25 22:57 UTC, mikehardy approved these changes
nice, thank you!

2022-01-25 23:02 UTC, merged

2022-03-06 21:47 UTC, mikehardy commented
Hi there! **JANUARY** OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [January 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-01-01..2022-01-31) (I'll follow this with the same process for February in a week)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of January)

Thanks!