freeCompilerArgs in tasks.KotlinCompile
ankidroid/Anki-Android pull request #10275
Opened 2022-01-27 06:39 UTC by Akshay0701

## Pull Request template

## Purpose / Description

A list of additional compiler arguments

## Fixes
[comment](https://github.com/ankidroid/Anki-Android/pull/10060#discussion_r792913468)

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-01-27 06:46 UTC, david-allison-1 reviewed
Ideally the commit message should explain the flag and why the `all` value was chosen. Maybe some of this explanation could be in a comment with a link to the docs

2022-02-24 13:15 UTC, mikehardy requested changes
@Akshay0701 this looks like it could go in but I agree with this in principle:

> Ideally the commit message should explain the flag and why the all value was chosen. Maybe some of this explanation could be in a comment with a link to the docs

To be most specific, as I'm maintaining gradle files here a lot, I want it in a comment with a link to the docs. I am certain I'll click that in the future when making some change...

2022-02-27 14:27 UTC, Akshay0701 commented
sorry, for the delay

2022-02-27 14:30 UTC, david-allison requested changes
> I want it in a comment with a link to the docs. I am certain I'll click that in the future when making some change...

Could this be in a code comment as well as the commit message? Message looks good

2022-02-27 14:35 UTC, Akshay0701 commented
okay

2022-02-27 14:42 UTC, david-allison approved these changes
LGTM

2022-02-27 21:45 UTC, mikehardy requested changes
I was totally confused by the comment personally, I couldn't figure out *why*.
What do you think of my suggestion?

2022-02-27 21:45 UTC, mikehardy commented on AnkiDroid/build.gradle
> +
I'm sorry, but this comment is not illuminating at all - I had no idea what was going on here when I went to review it.
So I chased down the docs.

None of the part about task naming is important to understanding the build.gradle setting
Of course there was no freeCompilerArgs before, that's why we're adding it, but future reviewers won't care whether it was here before or not, they will want to know *what it does*

What it does is enable Kotlin<->Java interop for concrete implementations of functions inside Kotlin interfaces.

So the important link and comment is explaining that and linking to the interop documentation

```suggestion
Kotlin allows concrete function implementations inside interfaces.
For those to work when Kotlin compilation targets the JVM backend, you have to enable the interoperability via
'freeCompilerArgs' in your gradle file, and you have to choose one of the appropriate '-Xjvm-default' modes.

https://kotlinlang.org/docs/java-to-kotlin-interop.html#default-methods-in-interfaces

```

2022-02-28 11:50 UTC, Akshay0701 commented on AnkiDroid/build.gradle
> +
Thanks Mike for improving comments

2022-02-28 13:35 UTC, mikehardy approved these changes
documentation is harder than code, in many ways 😅 - LGTM!

2022-02-28 13:37 UTC, merged