[Kotlin Migration] CustomStudyDialog
ankidroid/Anki-Android pull request #10274
Opened 2022-01-27 02:33 UTC by codingtosh

[Kotlin Migration] CustomStudyDialog
package com.ichi2.anki.dialogs.customstudy

2022-01-27 05:11 UTC, david-allison-1 requested changes
```
com.ichi2.anki.dialogs.CustomStudyDialogTest > learnAheadCardsRegressionTest FAILED
    java.lang.NullPointerException: whatever() must not be null
        at com.ichi2.anki.dialogs.CustomStudyDialogTest.learnAheadCardsRegressionTest(CustomStudyDialogTest.kt:60)

com.ichi2.anki.dialogs.CustomStudyDialogTest > increaseNewCardLimitRegressionTest FAILED
    java.lang.NullPointerException: whatever() must not be null
        at com.ichi2.anki.dialogs.CustomStudyDialogTest.increaseNewCardLimitRegressionTest(CustomStudyDialogTest.kt:101)
```

2022-01-28 12:32 UTC, codingtosh commented
Done, PTAL.

2022-01-28 18:37 UTC, david-allison-1 requested changes
LGTM, only nits

2022-01-28 18:37 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +class CustomStudyDialog(private val collection: Collection?, private val customStudyListener: CustomStudyListener?) : AnalyticsDialogFragment(), TagsDialogListener {
cleanup: non-null collection

2022-01-28 18:37 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +    @KotlinCleanup("Inspect Nullability")
cleanup: map dialogID to enum to make exhaustive

2022-01-29 07:58 UTC, codingtosh commented
@david-allison-1 Done, PTAL.
 
Note: If we make collection non-null in the future, the test will fail with the same error as above: 
```
com.ichi2.anki.dialogs.CustomStudyDialogTest > learnAheadCardsRegressionTest FAILED
    java.lang.NullPointerException: whatever() must not be null
        at com.ichi2.anki.dialogs.CustomStudyDialogTest.learnAheadCardsRegressionTest(CustomStudyDialogTest.kt:60)

com.ichi2.anki.dialogs.CustomStudyDialogTest > increaseNewCardLimitRegressionTest FAILED
    java.lang.NullPointerException: whatever() must not be null
        at com.ichi2.anki.dialogs.CustomStudyDialogTest.increaseNewCardLimitRegressionTest(CustomStudyDialogTest.kt:101)
```

2022-01-29 09:15 UTC, david-allison-1 approved these changes
LGTM

2022-01-30 16:48 UTC, mikehardy approved these changes

2022-01-30 16:48 UTC, merged

2022-03-06 21:47 UTC, mikehardy commented
Hi there! **JANUARY** OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [January 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-01-01..2022-01-31) (I'll follow this with the same process for February in a week)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of January)

Thanks!