Disable "html_javascript_debugging" for unit/android tests
ankidroid/Anki-Android pull request #10288
Opened 2022-01-30 12:13 UTC by murugu-21

## Pull Request template

## Purpose / Description
enable html/js debugging only for debugging and not for tests

## Fixes
Fixes #9751

## Approach
check for org.junit.Test class being imported.
All CI's passing in my fork.

## How Has This Been Tested?

used timber logging to verify isDebug is true during normal run in avd and false when running unit/android tests.

## Learning
[stackoverflow](https://stackoverflow.com/questions/28550370/how-to-detect-whether-android-app-is-running-ui-test-with-espresso)

## Checklist
_Please, go through these checks before submitting the PR._

- [ X ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ X ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ X ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ X ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-01-30 12:22 UTC, david-allison-1 requested changes
Thanks! Small change for performance

2022-01-30 12:22 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        if (BuildConfig.DEBUG && isDebug) {
Could you extract the above to `AdaptionUtil` and call it after the &&. 

Having it after the && will mean that the "slow" code is only executed if `BuildConfig.DEBUG` is true.

2022-01-30 12:23 UTC, david-allison-1 commented
As an aside: it'd be useful to put the stackoverflow link, and a little more detail of why the change is occurring (issue ref + possibly explain the issue) into the commit message.

Expecting to see an improvement on test speed from this, so thanks!

2022-01-30 12:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        Timber.d("isDebug: %s", Boolean.toString(isDebug));
untested, I'd be surprised if it didn't work

```suggestion
        Timber.d("isDebug: %b", isDebug);
```

2022-01-30 12:45 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        } catch (ClassNotFoundException e) {
```suggestion
        } catch (ClassNotFoundException ignored) {
```

2022-01-30 12:45 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +            Class.forName ("org.junit.Test");
```suggestion
            Class.forName("org.junit.Test");
```

2022-01-31 04:44 UTC, murugu-21 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        if (BuildConfig.DEBUG && isDebug) {
made the changes [here](#554835b)

2022-01-31 05:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
> +    val isDebug: Boolean
Rename to `isUnitTest` (+ the Timber log), add a doccomment and good to go, thanks!

2022-01-31 05:14 UTC, david-allison-1 requested changes
Last round of feedback I think, looks "much" better, thanks!

2022-01-31 05:14 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
> +    val isDebug: Boolean
Rename to `isRunningAsUnitTest`, flip the return values and invert the call, and fixup the `Timber` logs (if you want to use them)

2022-01-31 05:14 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
> +    // make default HTML / JS debugging true for debug build and disable for unit/android tests
Could you change this to doccomnents (`/** */`) and document the method quickly

2022-01-31 06:15 UTC, murugu-21 commented on AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
> +    val isDebug: Boolean
[done](#83bbe90)

2022-01-31 06:15 UTC, murugu-21 commented on AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
> +    // make default HTML / JS debugging true for debug build and disable for unit/android tests
[done](#83bbe90)

2022-01-31 07:08 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        if (BuildConfig.DEBUG && AdaptionUtil.isRunningAsUnitTest()) {
```suggestion
        if (BuildConfig.DEBUG && !AdaptionUtil.isRunningAsUnitTest()) {
```

2022-01-31 07:09 UTC, david-allison-1 approved these changes
Looks great, thanks!

2022-02-01 13:54 UTC, mikehardy approved these changes
nice!

2022-02-01 14:27 UTC, merged

2022-04-10 00:39 UTC, mikehardy commented
Hi there! FEBRUARY OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [February 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-02-01..2022-02-28) (I'll do my best to follow this with the same process for March in a week)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of January)

Thanks!