Note editor toolbar new item string as icon
ankidroid/Anki-Android pull request #10290
Opened 2022-01-30 17:44 UTC by krmanik

## Pull Request template

## Purpose / Description
The Note Editor toolbar add new items as number from 1...N, so I created this PR for adding string / single character as icon for the new items. It helps in recognize the button instead of memorizing button action with the number. 

## Fixes
Fixes _Link to the issues._

## Approach
1. I have added new variable `icon` after `index`. 
2. Earlier buttons saved in SharedPrefs as `index, prefix and suffix`. 
Now when new buttons added it saved to SharedPrefs as `index, icon, prefix and suffix`
3. Now every action like button position for delete.

## How Has This Been Tested?
Test on Emulator on device
<img src="https://user-images.githubusercontent.com/12841290/151710697-9c933d41-bac9-4dc4-b3c1-945832af8019.png" height=450px></img> <img src="https://user-images.githubusercontent.com/12841290/151710702-ecc1da05-027c-48bf-bba9-84436850a8a3.png" height=450px></img>

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-01-30 19:29 UTC, ShridharGoel requested changes

2022-01-30 19:29 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/CustomToolbarButton.kt
> +            val icon: String = try {
Is try-catch needed here? For index, I think it's added to handle NumberFormatException, but here it does not seem to be required.

2022-01-30 21:20 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/CustomToolbarButton.kt
> +            val icon: String = try {
Thanks I have update it.

2022-01-31 07:44 UTC, david-allison-1 requested changes
Looks good! Main question is about the user losing data, which should be handled by 

https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt

2022-01-31 07:44 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        if (TextUtils.isEmpty(icon) && TextUtils.isEmpty(prefix) && TextUtils.isEmpty(suffix)) {
This allows a button to be added with only an icon, it doesn't seem correct. What's the intended logic? 

Exiting without an icon seems like the correct move

Previously: either a prefix, a suffix, or both is acceptable.

2022-01-31 07:44 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/CustomToolbarButton.kt
> +class CustomToolbarButton(var index: Int, var icon: String, private val prefix: String, private val suffix: String) {
For documentation: it would be good to have a Kotlin `typealias` over a string that we can document in one place. `icon` is ambiguous to me.

Maybe we want to use `ButtonText/IconText`

2022-01-31 07:44 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="note_editor_toolbar_icon">Character As Icon</string>
`Icon text` would also seem reasonable

```suggestion
    <string name="note_editor_toolbar_icon">Button text</string>
```

2022-01-31 07:44 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/CustomToolbarButton.kt
> +            if (fields.size != 4) {
If I'm understanding correctly, this removes the current buttons that a user has saved.

It would be useful to add a `PreferenceUpgrade` subclass (ideally + unit tests) so the user does not lose data

2022-01-31 10:40 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/CustomToolbarButton.kt
> +class CustomToolbarButton(var index: Int, var icon: String, private val prefix: String, private val suffix: String) {
I am updating it.

2022-01-31 10:40 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/CustomToolbarButton.kt
> +            if (fields.size != 4) {
Okay, I will update it.

2022-01-31 10:40 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        if (TextUtils.isEmpty(icon) && TextUtils.isEmpty(prefix) && TextUtils.isEmpty(suffix)) {
So, there is no need to check the if `icon` empty, if empty number will be used.

2022-01-31 10:44 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        if (TextUtils.isEmpty(icon) && TextUtils.isEmpty(prefix) && TextUtils.isEmpty(suffix)) {
> Exiting without an icon seems like the correct move

This will be good. If no input for button text provided then number will be used.

2022-02-01 05:48 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/CustomToolbarButton.kt
> +            if (fields.size != 4) {
I have implemented the method for updating preferences with test. The test is passed but when I test is by checking out master branch add buttons to toolbar then checking out this branch, the toolbar buttons removed.
Is anything more to be added?

2022-02-10 22:24 UTC, david-allison-1 approved these changes
Looks great!

2022-02-17 17:05 UTC, mikehardy approved these changes
Looks good to me, thank you!

2022-02-17 17:08 UTC, merged