[Kotlin Migration] TranslationActivity
ankidroid/Anki-Android pull request #10299
Opened 2022-02-01 18:53 UTC by Akshay0701

2022-02-01 19:06 UTC, Akshay0701 commented
forgot to add file name in first commit...

2022-02-01 19:26 UTC, david-allison-1 requested changes
few nits, thanks!!!

2022-02-01 19:26 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.kt
> +import com.ichi2.utils.AdaptionUtil.isUserATestClient
I'd prefer for `AdaptionUtil.isUserATestClient` to be at the call site, so remove this import

2022-02-01 19:26 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.kt
> +open class TranslationActivity : FragmentActivity(), DialogInterface.OnClickListener, DialogInterface.OnCancelListener {
`KotlinCleanup("lateinit")`

2022-02-01 19:26 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.kt
> +        val objectMapper = objectMapper
Original call was cleaner: `AnkiSerialization.getObjectMapper();`

2022-02-01 19:26 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.kt
> +        if (mPossibleTranslations!!.isEmpty()) {
could you keep the spacing as it was, quite a bit of this method has changed

2022-02-01 19:26 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.kt
> +            for (tuc in tucs) {
`KotlinCleanup("mapNotNull")

2022-02-06 12:20 UTC, david-allison-1 approved these changes
LGTM

2022-02-06 15:46 UTC, mikehardy approved these changes

2022-02-06 15:57 UTC, merged