[Kotlin Migration] UsageAnalytics
ankidroid/Anki-Android pull request #10300
Opened 2022-02-01 19:07 UTC by Akshay0701

2022-02-01 19:18 UTC, david-allison-1 requested changes
I think there's one issue which this flagged. Rest are nits

2022-02-01 19:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
> +     * Determine whether we are disabled or not
Split the documentation between the get and the set, it's been combined.

2022-02-01 19:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
> +    fun sendAnalyticsScreenView(`object`: Objects) {
rename the variable (or add a `cleanup`)

2022-02-01 19:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
> +     * Send an arbitrary analytics event - these should be noun/verb pairs, e.g. "text to speech", "enabled"
Documentation was duplicated due to overloads. Should be combined

2022-02-01 19:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
> +        while (null != result.cause.also { cause = it!! } && result != cause) {
This looks to be incorrect. 

Could you KotlinCleanup("unit test required") if it was incorrect

2022-02-07 12:42 UTC, david-allison-1 requested changes
```
> Task :AnkiDroid:compilePlayReleaseKotlin FAILED
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnalyticsDialogFragment.kt: (24, 24): None of the following functions can be called with the arguments supplied: 
public final fun sendAnalyticsScreenView(`object`: Objects): Unit defined in com.ichi2.anki.analytics.UsageAnalytics
public final fun sendAnalyticsScreenView(screenName: String?): Unit defined in com.ichi2.anki.analytics.UsageAnalytics
```

2022-02-07 13:24 UTC, mikehardy commented
A lot of these PRs are being rejected based on automated CI tests. Please do not push commits until you know they pass `./gradlew clean jacocoTestReport :api:lintRelease :AnkiDroid:lintPlayRelease ktlintCheck` locally - the review cycles are really expensive, the compute cycles are cheap

2022-04-18 15:56 UTC, closed without merging