[Kotlin Migration] DeckDueTreeNode
ankidroid/Anki-Android pull request #10306
Opened 2022-02-01 19:46 UTC by Akshay0701

2022-02-01 20:51 UTC, david-allison-1 requested changes
```
e: warnings found and -Werror specified
w: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.kt: (93, 25): The corresponding parameter in the supertype 'AbstractDeckTreeNode' is named 'other'. This may cause problems when calling this function with named arguments.
```

2022-02-02 23:54 UTC, david-allison-1 requested changes

2022-02-02 23:54 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.kt
> +    override fun setChildren(children: MutableList<DeckDueTreeNode?>, addRev: Boolean) {
KotlinCleanup: non-null

2022-02-07 11:57 UTC, david-allison-1 requested changes

2022-02-07 11:57 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.kt
> +class DeckDueTreeNode(col: Collection?, name: String?, did: Long, private var mRevCount: Int, private var mLrnCount: Int, private var mNewCount: Int) : AbstractDeckTreeNode<DeckDueTreeNode?>(col, nam
`kotlinCleanup: mRevCount -> revCount`

This will remove the getters

2022-02-07 11:58 UTC, david-allison-1 requested changes
```
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.kt:35: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki.lint]
FAILURE: Build failed with an exception.
class DeckDueTreeNode(col: Collection?, name: String?, did: Long, private var mRevCount: Int, private var mLrnCount: Int, private var mNewCount: Int) : AbstractDeckTreeNode<DeckDueTreeNode?>(col, name, did) {
                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~

/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.kt:35: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki.lint]
* What went wrong:
class DeckDueTreeNode(col: Collection?, name: String?, did: Long, private var mRevCount: Int, private var mLrnCount: Int, private var mNewCount: Int) : AbstractDeckTreeNode<DeckDueTreeNode?>(col, name, did) {
Execution failed for task ':AnkiDroid:lintPlayRelease'.
                                                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~
> Lint found errors in the project; aborting build.
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.kt:35: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki.lint]
  
class DeckDueTreeNode(col: Collection?, name: String?, did: Long, private var mRevCount: Int, private var mLrnCount: Int, private var mNewCount: Int) : AbstractDeckTreeNode<DeckDueTreeNode?>(col, name, did) {
  Fix the issues identified by lint, or create a baseline to see only new errors:
                                                                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~
  ```

2022-03-03 17:59 UTC, mikehardy approved these changes
Looks good, running through checks locally

2022-03-03 18:03 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.kt
> +class DeckDueTreeNode(col: Collection?, name: String?, did: Long, private var mRevCount: Int, private var mLrnCount: Int, private var mNewCount: Int) : AbstractDeckTreeNode<DeckDueTreeNode?>(col, nam
Still needs this kotlin cleanup annotation so that at least revCount and lrnCount getters may go away after migration

2022-03-03 18:04 UTC, mikehardy commented
passes tests locally just needs annotation then merge

2022-03-03 18:09 UTC, Akshay0701 commented
within minutes it completes all tests? I must say your local machine is so fast, 

mine some time takes half an hours :(

2022-03-03 18:13 UTC, mikehardy commented
10 minutes total to run all CI tests locally vs android API24 and API31 emulator simultaneously yes :nerd_face: https://www.gigabyte.com/Laptop/AORUS-15G--RTX-30-Series/sp#sp - it's an absolute beast but is also capable (ask me how I know!) of actually causing 1st degree burns on my legs and the fan noise is outrageous when it's running all this stuff :hot_face:

2022-03-03 19:21 UTC, david-allison approved these changes
LGTM. I'm not sure if the `KotlinCleanup` is now actionable - half was completed, but we can try in a follow-up.

2022-03-05 13:13 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.kt
> +class DeckDueTreeNode(col: Collection?, name: String?, did: Long, private var revCount: Int, private var lrnCount: Int, private var newCount: Int) : AbstractDeckTreeNode<DeckDueTreeNode?>(col, name,
```suggestion
@KotlinCleanup("maybe possible to remove gettres for revCount/lrnCount")
class DeckDueTreeNode(col: Collection?, name: String?, did: Long, private var revCount: Int, private var lrnCount: Int, private var newCount: Int) : AbstractDeckTreeNode<DeckDueTreeNode?>(col, name, did) {
```

2022-03-05 14:04 UTC, merged