[Kotlin Migration] BadgeDrawableBuilder
ankidroid/Anki-Android pull request #10309
Opened 2022-02-04 19:34 UTC by puranjayK

[Kotlin Migration] BadgeDrawableBuilder
package com.ichi2.ui

2022-02-04 19:46 UTC, david-allison-1 requested changes
```
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/ui/BadgeDrawableBuilder.kt:27: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki.lint]
class BadgeDrawableBuilder(private val mResources: Resources) {
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2022-02-04 19:46 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/ui/BadgeDrawableBuilder.kt
> +    private var mChar = 0.toChar()
unsure. '\u0000' at the very least, but needs investigation

2022-02-07 18:07 UTC, puranjayK commented on AnkiDroid/src/main/java/com/ichi2/ui/BadgeDrawableBuilder.kt
> +    private var mChar = 0.toChar()
The java code was `mChar !='\0'`. 
I got an [answer ](https://stackoverflow.com/questions/36269488/how-do-i-make-a-null-character-in-kotlin)on stackoverflow regarding the same. 
Even from kotlinlang, I got to understand that `'\u0000'` is null char

2022-02-08 04:49 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/ui/BadgeDrawableBuilder.kt
> +    private var mChar = 0.toChar()
`\u0000` looks better to me: https://stackoverflow.com/questions/36269488/how-do-i-make-a-null-character-in-kotlin

2022-02-08 16:57 UTC, david-allison-1 approved these changes
LGTM

2022-02-09 08:26 UTC, Arthur-Milchior approved these changes

2022-02-09 08:26 UTC, merged