Issue10212
ankidroid/Anki-Android pull request #10316
Opened 2022-02-08 10:54 UTC by viciousAegis

## Pull Request template

## Purpose / Description
Adding an explicit `Add video clip` button to the Note Editor popup multimedia menu, which does the same thing as `Add audio clip` button. 

## Fixes
Fixes #10212 

## Approach
AnkiDroid supports adding video clips to notes, but through the `Add audio clip` button. Adding an explicit button for video clips that does the same thing as `Add audio clip` is the first step in splitting out the functionality between audio and video. 
The approach used was:
1. Creating a vector icon for the button. 
2. Creating a string for `Add video clip` in `AnkiDroid/src/main/res/values/16-multimedia-editor.xml`
3. Adding the button as an item in `AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml` with the same ID as `Add audio clip` to get the same functionality.

### Final result:
1. UI change in Note Editor:
<img src="https://user-images.githubusercontent.com/86671025/152964217-0c65c287-1608-4b50-b088-ade826609b08.png" width="300">

2. Video showing functionality:
https://user-images.githubusercontent.com/86671025/152965551-f87f90c3-4963-4351-9745-b00a30cfadb7.mp4

## How Has This Been Tested?
The changes were run and tested on the v2.16alpha41 build of AnkiDroid both on an emulator and an android device (details below). No unit tests were run, Testing was only done by running the app on both the emulator and the device. During this testing an issue #10315 also came up, but it does not affect the actual implementation of the feature. 

Emulator:
Pixel 5 API 32

Device:
Xaomi Redmi Note 8 Pro API 28 (Android 9)
## Learning (optional, can help others)
1. How to traverse the AnkiDroid code, find usages of methods and variables in Android Studio. 
2. How to create a new drawable vector icon in Android Studio. 
3. How to add Strings to the code. 
## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-02-08 12:20 UTC, ShridharGoel commented on AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml
> +            android:id="@+id/menu_multimedia_audio_clip"
I think we should have a separate ID and add the same functionality to both IDs. This would keep the ID unique. Also, I would have expected an error on using the same ID for different items, does that work without an error?

2022-02-08 12:47 UTC, viciousAegis commented on AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml
> +            android:id="@+id/menu_multimedia_audio_clip"
Yes, I realised IDs should be unique, so that is what I did initially. But when I created the ID ` "@+id/menu_multimedia_video_clip"`, for the `video clip` item, and then went into NoteEditor.java in the `setMMButtonListener` function and copy-pasted the functionality for Audio Clips (code with the initial change below), it crashed the app as soon as it started (error given below). When I tried it by giving them the same ID, it works just as intended (The video given is with both of them having the same ID)

`src/main/java/com/ichi2/anki/NoteEditor.java`:
```java
private void setMMButtonListener(ImageButton mediaButton, final int index) {
        mediaButton.setOnClickListener(v -> {
            Timber.i("NoteEditor:: Multimedia button pressed for field %d", index);
            if (mEditorNote.items()[index][1].length() > 0) {
                final Collection col = CollectionHelper.getInstance().getCol(NoteEditor.this);
                // If the field already exists then we start the field editor, which figures out the type
                // automatically
                IMultimediaEditableNote note = getCurrentMultimediaEditableNote(col);
                startMultimediaFieldEditor(index, note);
            } else {
                // Otherwise we make a popup menu allowing the user to choose between audio/image/text field
                // TODO: Update the icons for dark material theme, then can set 3rd argument to true
                PopupMenuWithIcons popup = new PopupMenuWithIcons(NoteEditor.this, v, true);
                MenuInflater inflater = popup.getMenuInflater();
                inflater.inflate(R.menu.popupmenu_multimedia_options, popup.getMenu());

                popup.setOnMenuItemClickListener(item -> {

                    int itemId = item.getItemId();
                    if (itemId == R.id.menu_multimedia_audio) {
                        Timber.i("NoteEditor:: Record audio button pressed");
                        startMultimediaFieldEditorForField(index, new AudioRecordingField());
                        return true;

                    // ISSUE 10212: initial change below, crashes the app as soon as opened

                    } else if (itemId == R.id.menu_multimedia_audio_clip || itemID == R.id.menu_multimedia_video_clip) {
                        Timber.i("NoteEditor:: Add audio clip button pressed");
                        startMultimediaFieldEditorForField(index, new AudioClipField());
                        return true;
                    } else if (itemId == R.id.menu_multimedia_photo) {
                        Timber.i("NoteEditor:: Add image button pressed");
                        startMultimediaFieldEditorForField(index, new ImageField());
                        return true;
                    } else if (itemId == R.id.menu_multimedia_text) {
                        Timber.i("NoteEditor:: Advanced editor button pressed");
                        startAdvancedTextEditor(index);
                        return true;
                    } else if (itemId == R.id.menu_multimedia_clear_field) {
                        Timber.i("NoteEditor:: Clear field button pressed");
                        clearField(index);
                    }
                    return false;
                });
                if (AdaptionUtil.isRestrictedLearningDevice()) {
                    popup.getMenu().findItem(R.id.menu_multimedia_photo).setVisible(false);
                    popup.getMenu().findItem(R.id.menu_multimedia_text).setVisible(false);
                }
                popup.show();
            }
        });
    }
```

ERROR on running:
```
2022-02-08 18:03:13.840 5007-5007/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 5007
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.DeckPicker}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.navigation.NavigationView.setNavigationItemSelectedListener(com.google.android.material.navigation.NavigationView$OnNavigationItemSelectedListener)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3685)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.navigation.NavigationView.setNavigationItemSelectedListener(com.google.android.material.navigation.NavigationView$OnNavigationItemSelectedListener)' on a null object reference
        at com.ichi2.anki.NavigationDrawerActivity.initNavigationDrawer(NavigationDrawerActivity.java:131)
        at com.ichi2.anki.DeckPicker.onCreate(DeckPicker.java:443)
        at android.app.Activity.performCreate(Activity.java:8054)
        at android.app.Activity.performCreate(Activity.java:8034)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3666)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7842) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

2022-02-08 13:39 UTC, david-allison-1 commented on AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml
> +            android:id="@+id/menu_multimedia_audio_clip"
```
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java	(revision bfa5d8709b2363580e91011e9c8a27e32e33fb42)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java	(date 1644327087011)
@@ -1555,7 +1555,7 @@
                         Timber.i("NoteEditor:: Record audio button pressed");
                         startMultimediaFieldEditorForField(index, new AudioRecordingField());
                         return true;
-                    } else if (itemId == R.id.menu_multimedia_audio_clip) {
+                    } else if (itemId == R.id.menu_multimedia_audio_clip || itemId == R.id.menu_multimedia_video_clip) {
                         Timber.i("NoteEditor:: Add audio clip button pressed");
                         startMultimediaFieldEditorForField(index, new AudioClipField());
                         return true;
Index: AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml b/AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml
--- a/AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml	(revision bfa5d8709b2363580e91011e9c8a27e32e33fb42)
+++ b/AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml	(date 1644327038328)
@@ -10,16 +10,9 @@
             android:title="@string/multimedia_editor_popup_image" />
         <!-- issue #10212: creating "add video clip" item -->
         <item
-            android:id="@+id/menu_multimedia_audio_clip"
+            android:id="@+id/menu_multimedia_video_clip"
             android:icon="@drawable/ic_popup_menu_item_video"
             android:title="@string/multimedia_editor_popup_video_clip" />
-
-        <!--
-        The ID is same as audio clips because their functionality is the same(for now)
-        Thus, Both these buttons do the exact same function. Separating their
-        functionality is a future task.
-        -->
-
         <item
             android:id="@+id/menu_multimedia_audio_clip"
             android:icon="@drawable/ic_popup_menu_item_audio"

```

2022-02-08 15:03 UTC, viciousAegis commented on AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml
> +            android:id="@+id/menu_multimedia_audio_clip"
@david-allison-1 Just tried these changes again, by doing the above, the app on emulator is crashing, and the error mentioned in the previous reply is being outputted in Logcat. Any idea what that error could be?

2022-02-08 16:51 UTC, david-allison-1 commented on AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml
> +            android:id="@+id/menu_multimedia_audio_clip"
Could you post the emulator details here and I'll see if I can duplicate. That's beyond strange

2022-02-08 17:25 UTC, ShridharGoel commented on AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml
> +            android:id="@+id/menu_multimedia_audio_clip"
The error log doesn't seem related to the change. Are you getting the crash only after making the changes?

2022-02-08 19:13 UTC, viciousAegis commented on AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml
> +            android:id="@+id/menu_multimedia_audio_clip"
@david-allison-1 I'll get the relevant details and create a new branch with the above changes and update in a while. 

@ShridharGoel Yep. Before creating the new ID and adding it to the NoteEditor.java file, everything works perfectly. After making these changes the app just doesn't start.

2022-02-08 20:23 UTC, viciousAegis commented on AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml
> +            android:id="@+id/menu_multimedia_audio_clip"
@david-allison-1 @ShridharGoel 
I created a new branch off of the newest master branch, and when I made the same changes, they worked! Not sure what went weird in the issue10212 branch.
Regardless, creating a new ID no longer causes the app to crash in the new branch. Should I just commit and push the changes to that branch and create a new pull request from there and close this one for simplicity?

2022-02-08 21:04 UTC, david-allison-1 commented on AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml
> +            android:id="@+id/menu_multimedia_audio_clip"
Keep this PR open. 

Feel free to `git push --force-with-lease` if you rebase your changes locally.

2022-02-08 21:53 UTC, viciousAegis commented on AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml
> +            android:id="@+id/menu_multimedia_audio_clip"
@david-allison-1 Okay, rebasing is done, and I have added the correct code with the correct IDs for the buttons. Rebasing caused some weird duplicated codes as well, but took care of them and the app is now working fine. Please review, thanks!

2022-02-12 05:49 UTC, viciousAegis commented
@david-allison-1 Should I squash all of these into 1 commit and force push onto the branch?

2022-02-12 07:36 UTC, ShridharGoel approved these changes

2022-02-12 09:44 UTC, david-allison-1 commented
If it's one commit, we can easily review it by the "files changed", and squash merge from GitHub when it's reviewed.

It's a nice thing to do, but not required here. The main advantage is that you get to write a clean commit message which will go into master

2022-02-12 09:45 UTC, david-allison-1 commented
If it's one commit, we can easily review it by the "files changed", and squash merge from GitHub when it's reviewed.

It's a nice thing to do, but not required here. The main advantage is that you get to write a clean commit message which will go into master

2022-02-12 10:15 UTC, viciousAegis commented
> If it's going to be one commit, we can easily review it by the "files changed", and squash merge from GitHub when it's reviewed.
> 
> It's a nice thing to do, but not required here. The main advantage is that you get to write a clean commit message which will go into master

Okay, so I'll let this be unless cleaner commit messages are required, and go work on something else :)

2022-02-12 11:19 UTC, david-allison-1 requested changes
I apologize. My initial statement in https://github.com/ankidroid/Anki-Android/issues/10212#issuecomment-1013344624 that video was supported was incorrect, as you pointed out in #10315.

I'd consider this functionality to be blocked on #10315, which I'll aim to resolve today.

After this is resolved, you'd want a slight change to open the new "Add Video Clip" activity.

2022-02-12 11:30 UTC, viciousAegis commented
Got it, I'll make the necessary changes after issue is resolved.

2022-02-12 19:05 UTC, david-allison commented
Blocked on PR: #10331. Should be resolved soon

2022-02-13 19:41 UTC, mikehardy commented
#10331 just merged, this should be unblocked

2022-02-13 19:53 UTC, david-allison requested changes
String conflict, not caught by CI. Will need to rebase this onto `master` and fix issues

2022-02-14 04:46 UTC, viciousAegis commented
> String conflict, not caught by CI. Will need to rebase this onto `master` and fix issues

Merged the new changes, and this time when I try to create the `add video clip` button in the popup menu, the app crashes on launch in the emulator (even though build is successful). 
Without the button, the app opens successfully

Logcat:
```
2022-02-14 10:08:08.001 5779-5779/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 5779
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.DeckPicker}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.navigation.NavigationView.setNavigationItemSelectedListener(com.google.android.material.navigation.NavigationView$OnNavigationItemSelectedListener)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3685)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.navigation.NavigationView.setNavigationItemSelectedListener(com.google.android.material.navigation.NavigationView$OnNavigationItemSelectedListener)' on a null object reference
        at com.ichi2.anki.NavigationDrawerActivity.initNavigationDrawer(NavigationDrawerActivity.java:131)
        at com.ichi2.anki.DeckPicker.onCreate(DeckPicker.java:443)
        at android.app.Activity.performCreate(Activity.java:8054)
        at android.app.Activity.performCreate(Activity.java:8034)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3666)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7842) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
</details>

2022-02-14 05:03 UTC, david-allison commented
> EDIT: Also, is the text here supposed to be this? ![image](https://user-images.githubusercontent.com/86671025/153802230-fa9218cb-4c86-4720-915e-648c55847ed4.png)

? Something's very wrong there

2022-02-14 05:24 UTC, viciousAegis commented
> > EDIT: Also, is the text here supposed to be this?
> 
> ? Something's very wrong there
> 
> ```
> > Task :api:javaPreCompileDebug
> ERROR:/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/16-multimedia-editor.xml: Resource and asset merger: Found item String/multimedia_editor_popup_video_clip more than one time
> ```

Oh no, that is fine, that's because both of us added the `multimedia_editor_popup_video_clip` string in different branches, and then merged. The above that I'm running is run by removing the additional string.

2022-02-14 07:44 UTC, david-allison commented
Could you check in Discord to see if anyone can reproduce this? It worked fine when I tested the feature

2022-02-14 17:18 UTC, viciousAegis commented
@david-allison Works as intended now. Please check!

2022-02-17 13:01 UTC, david-allison commented
Thanks! Could you test on night mode to ensure the tint passes through? Happy besides that

2022-02-17 13:20 UTC, viciousAegis commented
> Thanks! Could you test on night mode to ensure the tint passes through? Happy besides that

Added night mode screenshot [here](https://github.com/ankidroid/Anki-Android/pull/10316#issue-842669833). Looks good to me, please check!

2022-02-17 17:17 UTC, merged