Image paste clipboard
ankidroid/Anki-Android pull request #10320
Opened 2022-02-09 17:16 UTC by murugu-21

## Pull Request template

## Purpose / Description
android 11 seems to return content uri for clipboard images. this breaks existing method to get filename from uri

## Fixes
Fixes #10240 #8880

## Approach
content uri doesn't have MediaStore.MediaColumns.DISPLAY_NAME column in cursor.
When i listed all columns, there was only _id and _data.
_data contained original path of file. I found display_name from path through substring.

## How Has This Been Tested?

Images pasted properly on my testing machine and it worked.
(test machine is running oneUI 3.1, android 11).

## Learning (optional, can help others)

https://stackoverflow.com/questions/13275007/contentresolver-how-to-get-file-name-from-uri

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-03-03 14:41 UTC, mikehardy requested changes
Hi there! Thanks for posting this up, users will really appreciate the fix.
I have a question about the method of getting that path, and then if this method is used a suggestion to use a constant vs string

2022-03-03 14:41 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt
> +                        val dataIndex = c.getColumnIndexOrThrow("_data")
should use the constant I think? MediaStore.MediaColumns.DATA

2022-03-03 14:41 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt
> +                        return path.substring(path.lastIndexOf('/') + 1)
How is this approach better than simply asking the Uri for it's last path segment? https://developer.android.com/reference/android/net/Uri#getLastPathSegment()

2022-03-05 17:17 UTC, murugu-21 commented on AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt
> +                        return path.substring(path.lastIndexOf('/') + 1)
since cursor returns string, rather than uri, I resorted to string manipulation.

2022-03-06 06:35 UTC, murugu-21 commented on AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt
> +                        val dataIndex = c.getColumnIndexOrThrow("_data")
The constant appears to be depricated. But content uri contains only id and _data columns.

2022-03-06 18:16 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt
> +                        val dataIndex = c.getColumnIndexOrThrow("_data")
That's an important signal! They are trying to tell us something with the deprecation, I'm really glad you mentioned that.
It appears that we need to use different behavior on Android < 29 and Android >= 29
For < 29 we should use DATA, for >= 29, does https://developer.android.com/reference/android/provider/MediaStore.MediaColumns#RELATIVE_PATH work? You mention it *only* has id and _data columns which is just bizarre given the documentation.

I'm afraid _data will go away given they deprecate it, but who knows. If relative_path really doesn't exist even on API29+ then I'm confused but I guess it has to be _data. Would be useful to leave a comment then, in the code, something like:

```java
// use `_data` column label directly, MediaStore.MediaColumns.DATA is deprecated in API29+ but
// the recommended MediaStore.MediaColumns.RELATIVE_PATH does not appear to  be available

2022-03-06 18:17 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt
> +                        return path.substring(path.lastIndexOf('/') + 1)
I would do that if possible - I have learned to fear URL handling and will rely on library code for URI parsing / decomposition *at all times* now so as to avoid bugs handling the seemingly infinite variety of acceptable URIs

2022-03-07 04:45 UTC, murugu-21 commented on AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt
> +                        return path.substring(path.lastIndexOf('/') + 1)
61949f refactored

2022-03-07 04:53 UTC, murugu-21 commented on AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt
> +                        val dataIndex = c.getColumnIndexOrThrow("_data")
this appears to be a samsung specific issue too. gboard clipboard contains MediaStore.MediaColumns.DISPLAY_NAME and works as expected. shall I add that too in the comments?

2022-03-07 17:46 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt
> +                        val dataIndex = c.getColumnIndexOrThrow("_data")
oh why, that's keyboard specific! What a pain! :laughing: - yes, mentioning MediaColumns availability appears to be keyboard-specific, gboard has them but Samsung does not, would be useful

2022-03-07 17:48 UTC, mikehardy commented
Also apparently a test issue?

```

com.ichi2.utils.ContentResolverUtilTest > testViaQueryWorking FAILED
    java.lang.AssertionError: 
    Expected: is "filename_from_cursor.jpg"
         but: was "image.jpeg"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at com.ichi2.utils.ContentResolverUtilTest.testViaQueryWorking(ContentResolverUtilTest.java:51)

```

2022-03-08 04:24 UTC, murugu-21 commented
The test issue is because of a missing return statement, fixed with 8917d92.

2022-03-08 04:53 UTC, murugu-21 commented on AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt
> +                        val dataIndex = c.getColumnIndexOrThrow("_data")
7cbacd0

2022-03-08 14:54 UTC, murugu-21 commented
> 🤔 as a developer note, adding that merge commit makes this commit trail immediately really messy. Merge commits are permitted by git, and we can deal with them but it is strongly preferred to pull rebase vs merge so the commits may remain separate and clean. The only way to really merge a pull request back to main branch after you've done a merge commit is to squash.
> 
> Of course, there are 17 different commits here which means the commit trail is already a hash, so a squash merge would have been the only way to merge anyway, but in the future, you might play around with ingesting PR comments as local edits then doing local git rebases to _edit_ your commits (instead of adding new ones) and force-pushing back to your branch. The end result then is just a few (maybe only 1) clean commit that we can rebase merge here. You can look at PRs from Arthur, David or myself with multiple commits in the past to see what that looks like

I am very new to open source and didn't know about rebase vs merge. will do rebase with future pr's.

2022-03-08 15:23 UTC, mikehardy commented
Honestly that's the sort of thing that we should have in the development guide, because git knowledge, and our preferences, and how to operate git as a tool like a master requires a lot of explanation of the why first, and then the how. And we have explained it to lots of people but I'm not sure we ever wrote it down? 

@Arthur-Milchior I feel you have spent a lot of time explaining this before, in a lot of detail, in PR comments, @david-allison I've seen a few comments from yourself as well. Is this in our development guide anywhere? I only see this https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#git-workflow but it seems like we could really use a quick explanation of `git rebase`, why we use it (for clean, separate, easy to review commits that can go cleanly into the main tree, vs a squash), and how to use it (a quick example plus pointer to other tutorials?)

This is something we should really really do before GSoC goes any further I think - it will be a huge benefit and may be just as easy as lifting one of your previous PR comments in to the development guide?

2022-03-10 19:46 UTC, Arthur-Milchior reviewed
You stated that you tested this behavior on your current device.
To be clear, with current alpha/main, pasting images fail on your current device ? 
Because ideally, we would want to know that it solves the issue for people whose app was failing, and not only that it keep working for people for which it already work


If you answer yes, then I approve this PR. I'm fine if you ignore my suggestion and fine if you apply it

2022-03-10 19:46 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt
>                  if (c != null) {
I'd suggest doing 
```
if (c == null){
  return null
}
```
This way we avoid having extra levels of imbrication (I realize that this was not introduced in your PR. But since we are already working in this file, let's improve it even more)

2022-03-10 19:57 UTC, mikehardy commented
It was my understanding from comment back and forth that it not only failed for @murugu-21 , but it fails differently depending on keyboard (the keyboard - which you can change on android - controls the copy/paste buffer and each keyboard exports the paste buffer with different implementations of ContentResolver). I expect that's what we will here anyway, but now I'm on record with my understanding

2022-03-11 03:26 UTC, murugu-21 commented
> You stated that you tested this behavior on your current device. To be clear, with current alpha/main, pasting images fail on your current device ? Because ideally, we would want to know that it solves the issue for people whose app was failing, and not only that it keep working for people for which it already work
> 
> If you answer yes, then I approve this PR. I'm fine if you ignore my suggestion and fine if you apply it

I can confirm from my testing that current release of ankidroid on playstore does not work with my phone default clipboard implementation (samsung clipboard), but works perfectly with gboard's inbuilt clipboard images. On debugging the current alhpa/main, I was able to find out the reason for samsung clipboard failing is it only implements id and _data columns for content uris, whereas gboard implements the mediacolumns.DISPLAY_NAME field reffered in code to find file name.

2022-03-11 03:27 UTC, murugu-21 commented on AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt
>                  if (c != null) {
f919b5c

2022-03-11 05:05 UTC, merged