Keep image file names
ankidroid/Anki-Android pull request #10329
Opened 2022-02-11 15:04 UTC by BrayanDSO

## Purpose / Description
Keep the selected images original file names or appends its checksum in it if not unique, like Anki desktop does.

## Fixes
Fixes #9116 

## Approach
Most of the descriptions is [here](https://github.com/ankidroid/Anki-Android/issues/9116#issuecomment-1035609316). 

## How Has This Been Tested?

Couldn't run the automated tests or build new ones because of #8482

Tested it manually with Android Studio Emulator (API 32, Pixel 2) and on my android phone (Samsung Galaxy Note 10 Lite SM-N770F/DS)

Procedure:
1. Attach an image
2. Check if file name was kept
3. Attach other image with the same file name
4. Check if checksum was appended to its name
5. Attach the first image again
6. Check if file name was kept (checksum shouldn't be appended when reading it)

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

## Personal considerations
1. As I've already said on my approach, by changing [internalizeUri()](https://github.com/ankidroid/Anki-Android/blob/v2.16alpha42/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java#L451), drawings file names now keep their original file names too. Since going from `imgRandomNumberSequence.extension`  to `unixtimestamp.extension` doesn't matter much IMO, I kept it to keep things simple
2. [saveMedia()](https://github.com/BrayanDSO/Anki-Android/blob/keepImgNames/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt#L122) isn't being used anywhere anymore, what to do about it?
3. Audioclip filenames are edited as well to `ankidroid_audioclip_filename_with_underscoresRandomNumberSequence.extension`, but since they are handled by other methods, I think this deserves its own issue and PR

2022-02-13 16:38 UTC, BrayanDSO commented
A bigger issue this solves is don't making copies when someone reattachs the same image later in another note with the attach button. So, less storage and performance is wasted with time with copies of the same files

2022-02-14 04:41 UTC, david-allison requested changes
Since it's a change to `libAnki`, requesting a couple of tests

----

One of our "big" problems which the filename solved was Google Images: It downloads to the same filename in some cases, and users were getting frustrated that their images were being replaced. 

Your comment on "reattaches the same image" flags a concern, as we may be re-introducing this bug.

2022-02-14 04:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
> +            root = root + "-" + csum;
We're moving away from `libAnki` soon (replacing with upstream's Rust code), would it be possible to add a couple integration tests for this functionality (has conflict/no conflict) to ensure that we don't get regressions when we switch this out for Anki Desktop's code.

2022-02-14 11:06 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
> +            root = root + "-" + csum;
Since I fixed my problem with #8482, I can build the tests now.

By what I understood, the tests should avoid dealing directly with `libanki` since it won't be used anymore.

I believe the tests should assert the same file won't make a copy when reattaching the same file and when reattaching a different file with same name, its behavior should be the same as upstream.

If both my assumptions are correct, I'll work on it when I get time

2022-02-14 13:59 UTC, BrayanDSO commented
> Since it's a change to `libAnki`, requesting a couple of tests 

Made one, let me know if more is needed

> One of our "big" problems which the filename solved was Google Images: It download/replaces the same filename on phones in many cases, and users were getting frustrated that their images were being replaced/not uploaded as Anki assumed `same filename == same content`.
> 
> Your comment on "reattaches the same image" flags a concern, as we may be re-introducing this bug.

I don't know if I understood you correctly. This is I got:
- People commonly use google images to download images and it's easy to get files with the same name (e.g. download.jpg)
- The random image names added by Ankidroid were useful to avoid not importing files because they have the same name, since `same filename == same content`, as you said.

If this is what you meant, this now isn't a problem. 
If someone try to attach a different file with the same filename, it will add a `-checksum` suffix to it, like upstream does. 

Tecnically, before my PR, Ankidroid `libanki` was already checking if the imported image had another file with the same name and checksum. I only updated the naming pattern on it to follow upstream `file (index).extension` to `file-checksum`). 

The main problem was the `<img>` tags not updating if the file name was changed, which is fixed as well now. Neither Ankidroid, nor Anki desktop treated `same filename == same content`, it was just a lack of update after importing file.

2022-02-17 10:33 UTC, BrayanDSO commented
A demo:

https://user-images.githubusercontent.com/69634269/154457879-1ba0a9ed-b6a0-4ca2-abbf-fcd3977f468c.mp4

2022-02-28 22:19 UTC, BrayanDSO commented
Audios have this problem of making copies when reattaching the same file. It should behave like Anki desktop does:
- Keep the original filename
- Check its checksum when another file has the same name to see if they are equal. If not, append its checksum

https://user-images.githubusercontent.com/69634269/156067337-3caacbe8-754f-4b35-90b1-383a533e096e.mp4

Anki desktop behavior:
(reuploaded the same audio 3 times and it does not make any unnecessary copies. Tried with a different audio and its checksum was added)
![2022_02_28-19_08_01](https://user-images.githubusercontent.com/69634269/156067516-68bc3c8a-3fad-420f-a5d6-5c82c8128e5f.png)

If this should be fixed in this PR or in another one, let me know

2022-03-01 17:28 UTC, david-allison approved these changes
I like this and it's a great improvement. Thanks!

All my comments are nitpicks.

2022-03-01 17:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
> +        return cachedFile;
```suggestion
        return new File(mAnkiCacheDirectory, filename);
```

2022-03-01 17:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
> +            root = root + "-" + csum;
We'll have `libAnki`, but it'll be a wrapper around Anki Desktop for the most part. I agree that in this case it's best to test at the outer edges

2022-03-01 17:28 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.java
> +        try(FileWriter fileWriter = new FileWriter(firstFile)) {
```suggestion
        try (FileWriter fileWriter = new FileWriter(firstFile)) {
```

2022-03-01 17:28 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.java
> +        try(FileWriter fileWriter = new FileWriter(secondFile)) {
```suggestion
        try (FileWriter fileWriter = new FileWriter(secondFile)) {
```

2022-03-01 17:28 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.java
> +        File firstFile = folder.newFile("testImage.png");
Just to note: I added `createTransientFile()` which may be useful here (should be less code)

2022-03-01 17:54 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.java
> +        File firstFile = folder.newFile("testImage.png");
They need to have the same name, but different content. `createTransientFile()` doesn't take names

2022-03-01 18:24 UTC, mikehardy approved these changes
Nice! Looks like a solid test by my read as well, this will be a nice user improvement, quite a few complaints came in about current behavior

2022-03-01 18:33 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.java
> +        File firstFile = folder.newFile("testImage.png");
Okay - happy for additional params to be added to the method. I'm happy with this solution

2022-03-01 20:32 UTC, merged