Move file stream
ankidroid/Anki-Android pull request #10364
Opened 2022-02-19 20:26 UTC by Arthur-Milchior

This commit ensure that, starting at API 26, Operation uses a stream instead of a list of directory.
It uses the same set of tests than previous `MoveDirectory`.

2022-02-19 20:56 UTC, Arthur-Milchior commented
Good news, according to https://github.com/Arthur-Milchior/Anki-Android/tree/speed_list_dir  , MoveDirectoryStream execute takes only .15 seconds instead of 10 seconds for MoveDirectoryList. So really no worry about preemption here

2022-02-20 10:21 UTC, david-allison requested changes
I might be missing something here.

From an abstraction perspective, it would seem better to have `iterateFiles()` in `Compat`, with the warning that it may NOT stream on lower APIs

* We remove the subclasses
* The operation to use is (psedocode): `getCompat().streamFiles(directory).map(::toMoveOperation) + DeleteEmptyFolder()`
* We can mock `getCompat()` via `Mockito.spy` so we can keep the tests almost as-is (I like the use of the parameter). 
  * Maybe we want `getCompat()` as a `default` method in the `Operation` class - we use it a little and we'd benefit in a few more test classes from testing different Compat implementations
  * Maybe we can use a `@Rule` or different executor for different compat classes - I think this is a follow-up issue rather than something to be handled here.

2022-02-20 10:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryList.kt
> +data class MoveDirectoryList(override val source: Directory, override val destination: File) : MoveDirectory(source, destination) {
I don't think you need to `override val source: Directory, override val destination: File`, you can use the properties of the base class.

2022-02-20 10:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryStream.kt
> +    val stream = newDirectoryStream(source.directory.toPath()).iterator()
You likely don't want to perform this on `init {}` as the constructor throws and performs IO, rather than the operation.

2022-02-20 10:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryStream.kt
> +@RequiresApi(Build.VERSION_CODES.O)
Can we move the streaming operation into Compat, so we don't require subclasses?

2022-02-20 10:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryStream.kt
> +            if (!createDirectory(context)) {
Didn't we already call `createDirectory` just before the call to `executeMoveByRecursiveCopy`?

2022-02-20 10:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryStream.kt
> +        return listOf(moveContent, this)
Why don't we want to delete the folder if we perform a move like this?

2022-02-20 10:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryStream.kt
> +        if (!stream.hasNext()) {
We probably want either a Kotlin `sequence/yield` or a `foreach` here. The `hasNext()` seems very low-level.

2022-02-20 14:40 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryList.kt
> +data class MoveDirectoryList(override val source: Directory, override val destination: File) : MoveDirectory(source, destination) {
The trouble is that I need to give argument to the constructor of `MoveDirectory`, and if i don't get them in the constructor of MoveDirectoryList I see no other way to get them.
If it were not a data class, it seems like `class MoveDirectoryList(source: Directory, destination: File) : MoveDirectory(source, destination) {` also works. I'm not sure whether it was important that the operation was a data class, I don't get have a great intuition of when to use it

2022-02-20 17:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryList.kt
> +data class MoveDirectoryList(override val source: Directory, override val destination: File) : MoveDirectory(source, destination) {
I think the further comments suggesting removal of the subclass will handle this

To answer:

You shouldn't need the "override val" then.

Feel free to remove "data". It performs printing of the class data and comparison, we don't use comparison, and printing can be done via tostring

2022-02-21 19:18 UTC, david-allison reviewed
took a conflict

2022-02-21 19:43 UTC, david-allison reviewed
took a conflict

2022-02-21 19:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> +        if (!source.hasNext()) {
This leaks resources if `hasNext()` throws

2022-02-21 19:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> +        return listOf(toMoveOperation(source.next()), this)
This needs to be commented, it'll catch people out

2022-02-21 19:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> +        return listOf(toMoveOperation(source.next()), this)
Modifying a collection while it's being iterated is a very common source of bugs. Are we sure we want to do this?

2022-02-21 21:04 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> +        if (!source.hasNext()) {
You're right. I've updated `contentOfDirectory` to ensure it does not throw but return false instead.

2022-02-21 21:06 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> +        return listOf(toMoveOperation(source.next()), this)
Which collection am I modifying?
I'm returning a new list.

The list returned will indeed be inserted in a collection, but that is already the case with the current `MoveDirectory`.

2022-02-23 16:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> +        return listOf(toMoveOperation(source.next()), this)
Modifying the underlying file system (a collection of files) while iterating over it. 

Typically, this style of modification causes a `ConcurrentModificationException`, or risks introducing bugs.

I'm happy to have this in as it is, but could you comment to explain what's going on when returning a list containing `this`.

Alternately, move it to a variable: `continueMovingDirectoryContent`

2022-02-24 13:13 UTC, mikehardy commented
also needs rebase + push

2022-02-24 16:09 UTC, mikehardy commented
perhaps some interaction amongst the PRs, similar to the other one you just pushed

```

> Task :AnkiDroid:compilePlayDebugKotlin FAILED
w: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectory.kt: (53, 119): Unnecessary non-null assertion (!!) on a non-null receiver of type FileStream

```

2022-02-28 16:41 UTC, mikehardy commented
@david-allison parallelizing review just a little here with the inter-related PRs but I think the last 3 commits are the only ones in question remaining on this PR, and they seemed fine to me? First 4 commits are #10375 which also seems fine to me but I don't think you've given them a hard look. The MoveDirectoryContentFactory structure starts in #10375 then is used here, so if it's a problem it'll touch both

2022-03-01 13:52 UTC, david-allison reviewed
Looks good! Mostly test stuff and nitpicks. One question about exceptions

2022-03-01 13:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> +        fun MoveDirectoryContentFactory(source: Directory, destination: File): MoveDirectoryContent =
rename to `createInstance`

2022-03-01 13:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> + * This operation moves content of source to destination. This Operation is called one time for each file in the directory, and one last time. Unless an exception occurs. Use the `MoveDirectoryConten
Nit: Use `[MoveDirectoryContentFactory]` instead of backticks - that makes it a link

Same with [source] and [destination]

2022-03-01 13:52 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt
> +        assertThat("First result's first operation should be move_operation", result1[1], equalTo(moveOperation))
```suggestion
        assertThat("First result's second operation should be move_operation", result1[1], equalTo(moveOperation))
```

2022-03-01 13:52 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt
> +        assertThat("more-file should be deleted at source", moreFiles.exists(), equalTo(false))
```suggestion
        assertThat("'more files' should be deleted at source", moreFiles.exists(), equalTo(false))
```

2022-03-01 13:52 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt
> +        val moveDirectoryContentSpied = spy(moveDirectoryContent) {
Can we extract this to a method if it's necessary, it's plumbing and harder to read

2022-03-01 13:52 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt
> +    fun empty_directory_is_not_deleted() {
This needs an explanation (that `MoveDirectory` is responsible), and the assertion message seems inverted

"source directory should not be deleted"

2022-03-01 13:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> +        fun MoveDirectoryContentFactory(source: Directory, destination: File): MoveDirectoryContent =
This should be commented that it could be a slow operation.

Can this throw, or would only the iterator throw?

If it can throw, can this code path be tested?

2022-03-02 01:45 UTC, david-allison requested changes
```
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectory.kt: (52, 58): Unresolved reference: MoveDirectoryContentFactory
> Task :AnkiDroid:compilePlayDebugKotlin FAILED
```

2022-03-03 16:23 UTC, mikehardy commented
I restarted emulator test (failed due to emulator timing out, flake). Compilation seems fine. I think this should be in needs review state again in David's queue

2022-03-03 20:39 UTC, david-allison commented
I feel this is blocked on dependencies: https://github.com/ankidroid/Anki-Android/pull/10398 -> https://github.com/ankidroid/Anki-Android/pull/10418

2022-03-03 22:58 UTC, Arthur-Milchior commented
If you are happy with the whole PR you can merge it and close the other one. I just didn't expect it to occur

2022-03-05 21:24 UTC, mikehardy commented
This is actually waiting on #10375 now I think, the 4 commits there are the first 4 commits here, and #10375 is the area of current conversation in the commit stream

2022-03-05 23:19 UTC, Arthur-Milchior commented
Not waiting on anything anymore as  #10375 is now merged

2022-03-06 00:15 UTC, david-allison requested changes
I'm happy. Just testing-based nitpicks which can be ignored. Implementer's choice

2022-03-06 00:15 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt
> +        val moveDirectoryContentSpied = spy(moveDirectoryContent) {
Non-blocking, but I stand by this comment

2022-03-06 00:15 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt
>      fun executeAll(op: Operation) {
I think the next PR would look better if `executeAll(Operation)` was changed to a `executeAll(varargs Operation)` https://kotlinlang.org/docs/functions.html#variable-number-of-arguments-varargs.

This would change

```
        val subOperationsDeque = ArrayDeque(listOf(moveDirectoryContentSpied, deleteDirectory))
        executeAll(subOperationsDeque)
```

into 

```
        executeAll(moveDirectoryContentSpied, deleteDirectory)
```

2022-03-06 00:17 UTC, david-allison requested changes
I stand by my comments, and like the additional change which was added.

56858065fe2b835a971cfb3bcbc51a3cd428f15c is a badly named commit

2022-03-06 00:24 UTC, Arthur-Milchior commented
Done

2022-03-06 00:29 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt
> +        }
``` 
    val opsDequeue = ArrayDeque(ops.toList())
```

2022-03-06 00:37 UTC, david-allison commented
```
> Task :AnkiDroid:bundlePlayDebugClassesToRuntimeJar
> Task :AnkiDroid:bundlePlayDebugClasses
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt: (185, 20): Type mismatch: inferred type is ArrayDeque<MigrateUserData.Operation> but MigrateUserData.Operation was expected
```

2022-03-06 01:13 UTC, david-allison approved these changes
LGTM

2022-03-06 02:31 UTC, merged

2022-03-14 19:52 UTC, mikehardy commented
#5304