Move content directory
ankidroid/Anki-Android pull request #10375
Opened 2022-02-21 04:27 UTC by Arthur-Milchior

This PR adds an operation that allow to move the content of a directory.

It's a step toward creating "MoveDirectory" with atomic operations starting on API O. It requires PR #10369, #10372, #10373 and #10374

2022-02-23 16:46 UTC, david-allison commented
This needs a force push

2022-02-24 13:13 UTC, mikehardy commented
Ready for another rebase + push :-)

2022-02-24 16:09 UTC, mikehardy commented
```

w: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt: (161, 89): Unnecessary non-null assertion (!!) on a non-null receiver of type FileStream
> Task :AnkiDroid:compilePlayDebugUnitTestKotlin FAILED
w: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt: (212, 45): Unnecessary non-null assertion (!!) on a non-null receiver of type FileStream

```

2022-02-24 17:46 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt
> +import com.ichi2.testutils.withTempFile
these imports are added even though the only thing happening in this file on this commit is deleting code :thinking:

2022-02-24 17:46 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt
> +import timber.log.Timber
this import is not actually needed until the next commit I think

2022-02-24 17:47 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt
> +import com.ichi2.anki.RobolectricTest
this import is not needed here and I think is removed 2 commits later?

2022-02-24 18:00 UTC, mikehardy reviewed
Some little things - I generally approve / looks good, and just in general in the scoped storage migration area as a whole I am really excited to see you and David both working on it with such a high level of testing...it's going to work I am sure

2022-02-24 19:11 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> +            source.close()
My first answer, Mike, is simply "how would you do it?"
On a theoretical level, I entirely agree with you. I would prefer if we could get things done automatically. That would be wonderful.
However, as far as I understand, `AutoClose` would only be useful if we were able to use the resource all at once, at a single point in time, be done with it, and close it. When we actually need the ressource to remain opens and use it in a lot of different call, there is no way to use AutoClose. At best, if we had `finally`, I'd state to close it when the object is collected, but it does not to be an option anymore. So we need to explicitly note when we are done with the stream and when we can close it.

As far as I understand, `IOException` do not state what could cause an IOException or what would be the effect. I'm fine catching it and calling Close explicitly. It may indeed help.

Maybe i'm missing something, because I've little idea what's the big deal with leaking ressources in this case. We have a single instance of ankidroid running, with normally two folders to move, and streaming don't even forbid to do anything with them. Hence in practice, the number of resource leaked is very very small, and if anyway the move fails, it will be tried again, maybe with the app restarted.

2022-02-24 19:17 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt
> +        val moveOperation = moveDirectoryContent(source, destinationFile)
Right

2022-02-24 19:17 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> +        return listOf(moveNextFile, moveRemainingOfTheContent)
Done

2022-02-24 19:17 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> +        // Which implies that it is acceptable to change the directory content while the stream is open.
Do you want to be it more strongly worded?

2022-02-24 19:23 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> +        // Which implies that it is acceptable to change the directory content while the stream is open.
I want it in a different spot entirely:

> I'd prefer for the Compat API you added to instead get a strongly-worded documentation note

If the API you are using contains the documentation for the contract you are counting on, then it's documented at the API source. Right now this documentation is worthless in the sense that it is not connected to the Compat API (so perhaps a PR goes in there later with a slight alteration that we are not expecting...) but is discussing the Compat APIs guarantees.

Discuss Compat API guarantees on the Compat APIs, I think - I don't see the comment at all now though? Nor do I see a commit on the Compat interface :thinking:

2022-02-24 19:33 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> +            source.close()
Structurally it's just one perspective I look at PRs from, like one criteria I judge with, out of a bunch of criteria.
Specifically this is in the area of "rules of resource handling for me", and the rule I try to follow is, "the code that allocates a resource should free the resource". Here we have a resource coming in (the directory stream) that was not allocated by us, yet we are freeing it.

Is that a big problem? Your argument that the number of resources allocated is small so leaking them is not a resource-exhaustion risk is persuasive. It may not cause any problems.

But structurally it violates the rule I try to follow. What code is allocating this resource, and why can't that code free the resource? If there is some structural reason it can't, then I guess this is an exception to the rule. 

"How would I do it?" - I'm not sure. In practice it looks like you do this:

```kotlin

    private fun moveDirectoryContent(source: Directory, destinationDirectory: File): MoveDirectoryContent {
        val iterator = CompatHelper.getCompat().contentOfDirectory(source.directory)
        assertThat("Iterator over ${source.directory.absolutePath} should not be null", iterator, not(equalTo(null)))
        return MoveDirectoryContent(iterator, destinationDirectory)
    }
```

So that's where you get the iterator resource, and I remember in the docs for that compat method you indicate it allocates something but caller must free it. And in this method you are freeing on exception and on iterator exhaustion. Maybe that's as good as it gets versus having the method I pasted here save a return value then close the iterator (thus conforming to my general rule of "code that allocates should free".

If the exception to the rule is maintained then I think there should at least be a documentation comment on MoveDirectoryContent indicating it will close the iterator under all circumstances

2022-02-24 20:03 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> +            source.close()
I believe I know see two solutions to your issues. 

The first one is to add an extra operation "free the ressource", before or after deleting the folder. Or maybe in the same operation. This only work as long as we know that new operations are done before already planned information.
This ensure that "free the resource" is "at the same level"; in the sens that we open the resource in the last operation before MoveDirectoryContent and we close the resource in the first operation after it.

The second solution would be that `MoveDirectoryContent` create the stream. Creation and freedom would be done by the same object. I like it less simply because the stream creation would then need to be done either during `MoveDirectoryContent` initialization (which would then be costly) or during its first run (which mean a run will be more costly than the other one)

Let me know which one you prefer, if you like any of them, and I'll implement it

2022-02-24 20:46 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> +            source.close()
Structurally I prefer the second option because another rule I try to use with resources that are created and have to be freed later is to keep them as local as possible, and it seems the second solution would keep it all in one small area of code where it is easy to keep track.

Since the cost must be paid somewhere, moving it around doesn't seem like too big a burden. It feels a little strange to me to contemplate opening the resource as a side effect of the first run, but opening it during operation initialization feels like a reasonable spot - object initialization can certainly have side effects, opening a resource seems like a reasonable one.

2022-02-24 21:10 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> +            source.close()
I suspect you'll be disagreeing with @david-allison here. Each time I tried to do anything more than initializing variables with given values, he objected. At least asked for a factory method.

I'm pretty sure in one of the many version of the code I asked you both to review, I was actually creating the stream object in init{} and David objected. 

Which I understand, because `Operation` in general is supposed to only be costly in `execute`; which is actually why I created the stream in `execute`. After all, generating the stream may well take 10 seconds when it uses `listFiles`.

I'll use a factory method and document it can be slow. This way, the same class allocate and deallocate, even if it's not the same object

2022-02-25 09:22 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> +        // Which implies that it is acceptable to change the directory content while the stream is open.
Actually, the promise is in `FileStream`. Isn't it sufficient?

2022-02-25 13:37 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> +        // Which implies that it is acceptable to change the directory content while the stream is open.
If the contract for the API is documented at the source, then I think that is sufficient, and then I think there is no reason to defend the implementation details of the API contract you are relying on here

2022-02-25 16:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> +        // Which implies that it is acceptable to change the directory content while the stream is open.
In cases you missed it, i removed this argumentation here. I relied on FileStream's documentation to explain what is promised.

Is there anything else you expect @mikehardy before approving? Any change you want.

2022-02-28 16:28 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> + * @param source: an iterator over File content.
```suggestion
 * @param source: an iterator over File content, source will be closed when execute is called
```

2022-02-28 16:30 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
> + * This operation moves content of source to destination.
```suggestion
 * This operation moves content of source to destination. Use the MoveDirectoryContentFactory to instantiate the object,
 * it will convert the given Directory source to a FileStream. This conversion is a potentially long-running operation
 * 
```

2022-02-28 21:03 UTC, Arthur-Milchior reviewed
Yeah, I'm sorry, but I really failed to get what mean by comment; which is why I asked for clarification. Thanks for providing the suggestion. I corrected it to be more accurate. I'll let you review, and merge if you're happy with it (or even unhappy but want to write your own PR to correct it)

2022-02-28 21:36 UTC, mikehardy approved these changes
I think your final (since I'm going to merge it :-) ) version of the comments are the best+most complete yet. I like them, I can see how my version was not quite right and this is now complete+accurate I think. If I was using this API I think I would be aware of the tradeoffs and usage now.  Thanks!

2022-02-28 21:37 UTC, mikehardy commented
Oh wait - I intended to let @david-allison have a look pre-merge, I thought he had seen these. I'm +1 though, it's pending merge for me at least but David may have some insight on something I missed

2022-03-01 18:40 UTC, david-allison commented
I'm sure I wrote a review for this one, but can't find it.

2022-03-01 18:42 UTC, david-allison commented
I requested changes as part of https://github.com/ankidroid/Anki-Android/pull/10364

2022-03-02 01:17 UTC, Arthur-Milchior commented
I pushed changes on #10364

2022-03-05 13:10 UTC, david-allison requested changes
LGTM, just removing dead code

2022-03-05 13:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
> +    boolean isFileNotFoundOrNoSuchFileException(IOException exception);
revert?

2022-03-05 13:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
> +    }
revert?

2022-03-05 13:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
> +    }
revert?

2022-03-05 13:10 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt
> +    }
This seems duplicated between here and `OperationTest`

2022-03-05 18:03 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
> +    boolean isFileNotFoundOrNoSuchFileException(IOException exception);
Done.

2022-03-05 18:07 UTC, Arthur-Milchior reviewed
extra commit and duplication are removed

2022-03-05 18:07 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt
> +    }
Thanks, removed

2022-03-05 21:27 UTC, mikehardy approved these changes
Still LGTM - @david-allison - may be good to go?

2022-03-05 22:19 UTC, david-allison approved these changes
Looks great!

2022-03-05 23:14 UTC, merged

2022-03-14 19:53 UTC, mikehardy commented
#5304