Execute test in utils
ankidroid/Anki-Android pull request #10376
Opened 2022-02-21 05:07 UTC by Arthur-Milchior

This allow to factorize code that are either duplicate in multiple Operation's class test, or that will be in my next PR

2022-02-21 18:03 UTC, david-allison requested changes
Appears to have a performance regression/unnecessary dependency on `RobolectricTest`

I don't really see the point in the last few commits - the methods are only used in one class, so might as well stay in the class until they're factored out, I'm happy to see the change in if you want it, but I'm ambivalent on its value.

2022-02-21 18:03 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt
> +open class OperationTest : RobolectricTest() {
It would be best to use an `interface` + default members instead

2022-02-21 18:03 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt
> +    internal fun createDirectory(): Directory =
`Utils` is also an option

2022-02-21 20:21 UTC, Arthur-Milchior reviewed
I only moved methods that either are already used in two tests at least. Or that I actually use in tests of MoveContentDirectory

2022-02-21 20:21 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt
> +open class OperationTest : RobolectricTest() {
Oh right, I had forgotten the exitsence of default member. Thanks.

2022-02-21 20:21 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt
> +    internal fun createDirectory(): Directory =
I'm sorry, but I've no idea what this comment means

2022-02-22 09:38 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt
> +    internal fun createDirectory(): Directory =
https://github.com/ankidroid/Anki-Android/blob/8f33f2373a709d69409fc416f96aeb087152b95a/AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/Utils.kt already exists

2022-02-22 09:41 UTC, david-allison requested changes
I'd much rather see a different strategy for `OperationTest`, or reverting. There shouldn't be a dependency on `RobolectricTest` at all ideally.

We should be aiming to remove the dependency, not increase its usages.

2022-03-06 01:23 UTC, david-allison reviewed
@Arthur-Milchior I think this is deprecated by other PRs with the same functionality which have gone into `master`. Is there anything left that's useful to you?

2022-03-06 05:01 UTC, closed without merging