"Deck Search" display now same as the Deck Viewer
ankidroid/Anki-Android pull request #10389
Opened 2022-02-24 07:34 UTC by viciousAegis

## Pull Request template

## Purpose / Description
As described in #10378, the way decks are currently displayed in the "Deck Search" subscreen is not intuitive nor easy to understand, especially with multiple subdeck levels. This PR aims to make it more user friendly by indenting decks the same way as the main "Deck Viewer" screen.

I feel the code can be better formatted and commented.

## Fixes
Fixes #10378 

## Approach
instead of displaying the entire deck path, now only the subdeck name is displayed along with appropriate indentation. Deck and subdeck creation works just like before.

### Before
![image](https://user-images.githubusercontent.com/86671025/155477017-9d49348b-3b9f-4ffb-a703-c11f49e414be.png)

### After
![image](https://user-images.githubusercontent.com/86671025/155477034-571d8ca7-34d7-4198-88e1-cc91de3ae103.png)

Video showing creation of subdecks:
<img src="https://user-images.githubusercontent.com/86671025/155477447-830af4bd-16de-452e-a9ca-1d7584240f03.gif" width="300" inline = "true" >

Video showing search capability:

https://user-images.githubusercontent.com/86671025/155478620-26e90d7c-cab6-4425-93a3-55ee93fd7405.mp4

## How Has This Been Tested?

Emulator:
Pixel 5 API 32

Device:
Xaomi Redmi Note 8 Pro API 28 (Android 9)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-02-24 11:19 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            return displayName
Do we need check null for name?

2022-02-24 11:20 UTC, krmanik approved these changes

2022-02-24 11:46 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            return displayName
A null check for `deck.name`? I didn't see one before I changed things around, maybe it was already taken care of? If needed, I'm happy to add it. Will wait for another review.

2022-02-24 12:16 UTC, david-allison requested changes
You asked for a thorough review.

My only other comment would be that it'd be great to get a unit test on `.displayName`, optional, but nice to have.

2022-02-24 12:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            displayName = "\t\t".repeat(name.count { "::".contains(it) } / 2) + displayName
It would be better (both more readable and faster) to perform `.split("::")` and use the final element of the array, along with the size of the array for the number of `\t\t` to include

2022-02-24 12:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            return displayName
No null check is required.

2022-02-24 12:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +
I don't feel this comment is necessary. It represents code which has been deleted.

It would warrant a note in the commit message, and ideally in the main post of the PR

2022-02-24 12:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +        // The name to be displayed in the Recycler View
```suggestion
        // The name to be displayed to the user
```

2022-02-24 12:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +        // contains only subdeck name, not "deck::subdeck"
Maybe provide an example in the comment: `foo::bar` -> `\t\tbar`

2022-02-24 12:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +        /*
```suggestion
        /**
```

2022-02-24 12:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +        and returns only the name of the deck/subdeck
Use [Kotlin's Doc Comments](https://kotlinlang.org/docs/kotlin-doc.html) here: `@param` for an input parameter. `@return` for what it returns.

You don't need to say "The getDisplayName function": the context is obvious.

2022-02-24 12:24 UTC, viciousAegis commented
> You asked for a thorough review. Hope this helps!
> 
> 
> 
> My only other comment would be that it'd be great to get a unit test on `.displayName`, optional, but nice to have.

Yep, it does! I'll make the changes soon. For the unit test, are there any docs I could look at to see how to get those? Don't  know a lot about them.

2022-02-24 13:02 UTC, krmanik commented
I had also difficulty in implementing test earlier but now I can implement test.
I have learned by viewing existing test class in AnkiDroid source code.

My general workflow for implementing test class
1. Create test class if not exist in `src/test/java/com/ichi2/` with name end with `Test`
E.g. for `TypeAnswer`
`src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt`

   `src/test/java/com/ichi2/anki/cardviewer/TypeAnswerTest.java`

3. Add  function name to test with `@Test` annotation, then use functions in `MatcherAssert` to test if result is equal to expected. 
```kt
    @Test
    fun testMediaIsNotExpected() {
        // #0096 - Anki Desktop did not expect media.
        val input = "ya[sound:36_ya.mp3]<div><img src=\"paste-efbfdfbff329f818e3b5568e578234d0d0054067.png\" /><br /></div>"
        val expected = "ya"
        val actual: String = cleanCorrectAnswer(input)
        MatcherAssert.assertThat(actual, Matchers.equalTo(expected))
    }
```

Docs
https://junit.org/junit5/docs/current/user-guide/
https://developer.android.com/training/testing/local-tests
https://www.vogella.com/tutorials/JUnit/article.html

_May be I missed something above, so google it or chat in discord._

2022-02-25 12:34 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            this.displayName = getDisplayName(name)
Is using `get()` like this fine?
```kotlin
val displayName: String
            get() {
                return getDisplayName(name)
            }
```

2022-02-25 13:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            this.displayName = getDisplayName(name)
Yes, the only issue is that `displayName` is calculated more than once if it's called more than on

2022-02-25 13:34 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            this.displayName = getDisplayName(name)
I tried writing this as:
```
val displayName: String by lazy { getDisplayName(name)}
```
But, it gave me an error: `Variable 'name' must be initialized`, but `name` is already initialised, so I don't know what's wrong.

2022-02-25 18:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            this.displayName = getDisplayName(name)
Lazy option: Go with `get()` and leave a comment that it should be a lazy

2022-02-25 19:47 UTC, viciousAegis commented
Resolved all the changes suggested. PR not final, will add a test in the next commit. (Or, can add a test in another PR, either way fine with me. )

2022-02-25 20:36 UTC, david-allison approved these changes
Beautiful

2022-02-25 20:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            var nameArr = name.split("::")
Beauty

2022-02-25 20:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            get() {
note: `Alt+Enter` on the opening brace and Android Studio will offer a quickfix to collapse it into a less verbose structure.

2022-02-25 20:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            get() {
note: Could inline `getDisplayName` here

2022-02-25 20:48 UTC, viciousAegis commented
Started working on the test, I think I'm making good progress. Will address the comments along with it. It should be done by tomorrow. If so, we can add it do this PR, otherwise, will let you know! :)

2022-02-26 07:18 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            get() {
How's this?
```kt
val displayName: String // TODO should be a lazy value
            get() = getDisplayName(name)
```

2022-02-26 20:55 UTC, david-allison commented
@viciousAegis This is a bug on our side. We do not build `io.github.david-allison-1:anki-android-backend-testing` for M1 Macs.
 
I have an M1 Mac arriving sometime late March, so I'll be personally invested in testing

As a workaround: 
* Remove `@RunWith(AndroidJUnit4::class)`
* Remove `:RobolectricTest()`
* This will only work because the test does not depend on the Anki Database

As a workaround, please enable GitHub actions on your GitHub clone of `Anki-Android` and test there

## Properly fixing this

**Issue**  
* We have a library written in rust: `librsdroid`. This is compiled for Android
* Robolectric doesn't run Android, it runs tests via the JVM on your PC
* Therefore, `librsdroid` needs to be compiled for native platforms
* We have a separate library: `anki-android-backend-testing` which contains the `dlls` and `dylibs` needed
* When this was written, M1 macs didn't exist

Please see: https://github.com/ankidroid/Anki-Android-Backend/tree/main/rsdroid-testing

* First of all, this isn't well documented. Please submit a PR with better documentation if you want
* Most of the work is performed via GitHub actions
* Feel free to submit a pull request to the GitHub actions get this working. 
  * Compile the dylib for `arm64e` (I have no idea how to do this, but it should be possible)
    * The code should be: https://github.com/ankidroid/Anki-Android-Backend/blob/9302b3f89e09643e95c42166743f8563a3822ddc/rsdroid-testing/build.gradle#L184-L202
  * Include two `dylibs` in the `jar`
  * Fix this code to select the correct `dylib` based on your architecture:
    * https://github.com/ankidroid/Anki-Android-Backend/blob/9302b3f89e09643e95c42166743f8563a3822ddc/rsdroid-testing/src/main/java/net/ankiweb/rsdroid/testing/RustBackendLoader.java#L55-L64

2022-02-26 20:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            get() {
Fantastic!

2022-02-26 22:16 UTC, mikehardy commented
Alternatively: run the test somehow under Rosetta2?

Github Actions does not have any M1 runners unfortunately, and no concrete plans to add them.

I have an M1 mac though and can likely generate the libraries if it had to build on an M1 mac.

I think cross-compiling is possible though, to an M1 mac target (arm64e as you mention) from a different github action runner assuming it has the right toolchain stuff setup, that's what the code link above seems to do, and it should be a good path forward

Not sure if there are better ways to do this but here's a shell way to detect architecture (and Rosetta2 execution status, if needed), may help

```bash

if [ "$(uname)" == "Darwin" ]; then
  # We do not want to run under Rosetta 2, brew doesn't work and compiles might not work after
  arch_name="$(uname -m)"
  if [ "${arch_name}" = "x86_64" ]; then
    if [ "$(sysctl -in sysctl.proc_translated)" = "1" ]; then
      echo "Running on Rosetta 2"
      echo "This is not supported. Run \`env /usr/bin/arch -arm64 /bin/bash --login\` then try again"
      exit 1
    else
      echo "Running on native Intel"
    fi
  elif [ "${arch_name}" = "arm64" ]; then
    echo "Running on ARM"
  else
    echo "Unknown architecture: ${arch_name}"
  fi
fi
```

2022-02-27 01:35 UTC, david-allison commented
We should be able to cross-compile Rust for `arm64e`. This /should/ be doable by adding  `aarch64-apple-darwin` in:

https://github.com/ankidroid/Anki-Android-Backend/blob/9302b3f89e09643e95c42166743f8563a3822ddc/rsdroid-testing/build.gradle#L109-L114

and installing the target platform: https://github.com/ankidroid/Anki-Android-Backend/blob/9302b3f89e09643e95c42166743f8563a3822ddc/.github/scripts/install_rust_robolectric_targets.sh

* An option in the .java to detect an M1 and pull the correct dylib
* A fix to to [check_robolectric_assets.sh](https://github.com/ankidroid/Anki-Android-Backend/blob/9302b3f89e09643e95c42166743f8563a3822ddc/.github/scripts/check_robolectric_assets.sh) allow 2 dylibs in the `.jar`

Note that `aarch64-apple-darwin` is a [Tier 2 target](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-2-with-host-tools)

2022-02-27 01:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            return displayName
```suggestion
            return "\t\t".repeat(nameArr.size - 1) + nameArr[nameArr.size - 1]
```

2022-02-27 06:40 UTC, viciousAegis commented
I think this PR should be complete now, will move onto figuring out implementing tests on the m1 mac. Please review one final time for the `displayName` test, and let me know if any changes are needed!

2022-02-27 14:32 UTC, david-allison approved these changes
Awesome!

2022-02-27 14:32 UTC, Akshay0701 commented
Nice!

2022-02-27 14:33 UTC, merged

2022-04-10 00:38 UTC, mikehardy commented
Hi there! FEBRUARY OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [February 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-02-01..2022-02-28) (I'll do my best to follow this with the same process for March in a week)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of January)

Thanks!