Enhancements in CardBrowserMySearchesDialog.kt
ankidroid/Anki-Android pull request #10395
Opened 2022-02-24 19:49 UTC by ShridharGoel

## Purpose / Description

- Removed nullability at some places where it wasn't required.
- Used `?.` and `let` instead of `!!`
- Fixed unchecked cast
- Other small changes

## Learning (optional, can help others)
https://stackoverflow.com/a/58657456
https://blog.mindorks.com/what-are-reified-types-in-kotlin
https://stackoverflow.com/questions/45949584/how-does-the-reified-keyword-in-kotlin-work
https://kotlinlang.org/docs/inline-functions.html#reified-type-parameters

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-02-24 21:17 UTC, david-allison reviewed
Looks great! One question

2022-02-24 21:17 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +                ?.positiveText(getString(android.R.string.ok))
Only question is why the null-safe handling here and above. Shouldn't `builder.title()` be guaranteed to be non-null?

2022-02-24 21:20 UTC, david-allison requested changes

2022-02-24 21:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +                mySearchesDialogListener?.onRemoveSearch(searchName)
I don't think this is correct. We have a problem because we have two states (two dialogs in one class) and this further confuses the issue. These /should/ be non-null if `onPositive` is called

2022-02-25 05:45 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +                mySearchesDialogListener?.onRemoveSearch(searchName)
But here I have only changed `!!` to `.?`. Does that create a confusion?

2022-02-25 06:03 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +                ?.positiveText(getString(android.R.string.ok))
Safe calls were not required here. Updated.

2022-02-25 13:30 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +                mySearchesDialogListener?.onRemoveSearch(searchName)
It should be !! as the variables should exist

2022-02-25 13:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +            arguments?.getSerializable("savedFilters").tryCast<HashMap<String, String>> {
Doesn't this now allow failure if the cast fails?

2022-02-25 20:02 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +            arguments?.getSerializable("savedFilters").tryCast<HashMap<String, String>> {
Earlier if the cast would have failed then an exception would be thrown which can lead to a crash. Now, I think it would just not execute without any crash.

2022-02-25 20:23 UTC, david-allison requested changes

2022-02-25 20:23 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +    private var savedFilters: HashMap<String, String> = hashMapOf()
These are, and should be `null` until the two states of the class are split out

2022-02-25 20:26 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +            arguments?.getSerializable("savedFilters").tryCast<HashMap<String, String>> {
We should explicitly handle if preconditions for the class are broken. 

Ideally with a message, an error report and closing the screen, or providing good defaults.

In my mind:

Continuing with bad data < crashing + reporting < gracefully handling and closing + reporting < fixing bad data

2022-02-27 15:35 UTC, david-allison requested changes
Much better! The TODO is definitely going to make things a lot cleaner once it's completed.

2022-02-27 15:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/KotlinUtils.kt
> +    inline fun <reified T> Any?.tryCast(context: Context, task: T.() -> Unit): Boolean {
EDIT: One of my comments suggests removing this, read first.

This would be better returning a `Computation<T>` (AnkiDroid's `Result<>` monad).

The problem with this is that the `T` accessed in was used to set to a variable, which wasn't guaranteed to be non-null by the type system.

2022-02-27 15:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/KotlinUtils.kt
> +            UIUtils.showThemedToast(context, R.string.something_wrong, false)
We typically want to push IO code outside of computations. This would be best at the call site

2022-02-27 15:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +            if (!isCastSuccessful) return Dialog(requireContext())
This was better with the `UNCHECKED_CAST` + crashing if it was the wrong type

2022-02-27 15:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +            val isCastSuccessful = arguments?.getSerializable("savedFilters").tryCast<HashMap<String, String>>(requireContext()) {
Instead of `tryCast`, add the extension: `requireArguments().getSerializable<T>(key)` which crashes if the type is incorrect.

2022-02-27 15:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +            buttonItemAdapter?.notifyAdapterDataSetChanged() // so the values are sorted.
Would be better with a kotlin scope function than `?.`

2022-02-27 15:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +                    dialog?.dismiss()
Better with `!!`

2022-02-27 15:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +            buttonItemAdapter?.let { buttonItemAdapter ->
Better how it was previously

2022-02-27 15:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +                    getDialog()?.dismiss()
Better how they were previously (except the rename)

2022-02-27 15:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +            val cardBrowserMySearchesDialog = CardBrowserMySearchesDialog()
Well needed!

2022-03-08 16:56 UTC, david-allison reviewed
One question, the others are just comments

2022-03-08 16:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +        val layoutManager = dialog.recyclerView.layoutManager as LinearLayoutManager
Is `if (dialog.recyclerView != null) {` true for both cases?

2022-03-08 16:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +                buttonItemAdapter?.apply {
Would prefer `!!.apply`

2022-03-08 16:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/ArgumentUtils.kt
> +    inline fun <reified T> Bundle.getSerializableWithCast(key: String): T {
Awesome!

2022-03-08 16:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +                mySearchesDialogListener?.onRemoveSearch(searchName)
It's a nullable variable, just not on this code path.

2022-03-08 16:58 UTC, david-allison requested changes
```
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/utils/ArgumentUtilsTest.kt: (42, 22): Type mismatch: inferred type is Class<ClassCastException> but Runnable was expected
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/utils/ArgumentUtilsTest.kt: (42, 54): Too many arguments for public inline fun <reified T : Throwable> assertThrows(r: Runnable): T defined in com.ichi2.testutils in file AnkiAssertKt.kt
```

2022-03-09 10:13 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +        val layoutManager = dialog.recyclerView.layoutManager as LinearLayoutManager
No, updated.

2022-03-09 12:51 UTC, mikehardy commented
git merges @ShridharGoel, why ? :weary:

2022-03-09 13:15 UTC, ShridharGoel commented
@mikehardy Fixed it.

2022-03-09 13:37 UTC, david-allison approved these changes
LGTM

2022-03-11 21:43 UTC, mikehardy approved these changes
LGTM

2022-03-11 22:01 UTC, merged