`hasFiles` raises exception
ankidroid/Anki-Android pull request #10398
Opened 2022-02-25 10:48 UTC by Arthur-Milchior

The primary goal how this commit is to have a clear way to catch #10358.
It changes the way the method behaves when method assumption are not satisfied;
and raising an exception seems at least as acceptable than returning null. Plus
it will lead to more specific error cause if we care about them.

2022-02-25 14:13 UTC, david-allison requested changes
```
com.ichi2.anki.model.DirectoryTest > has_files_is_false_if_no_longer_exists FAILED
    java.lang.AssertionError: Expected 'IOException' got 'FileNotFoundException'
        at com.ichi2.testutils.AnkiAssert.assertThrows(AnkiAssert.java:70)
        at com.ichi2.anki.model.DirectoryTest.has_files_is_false_if_no_longer_exists(DirectoryTest.kt:123)

        Caused by:
        java.io.FileNotFoundException: /tmp/1[81](https://github.com/ankidroid/Anki-Android/runs/5334076550?check_suite_focus=true#step:8:81)36204017[83](https://github.com/ankidroid/Anki-Android/runs/5334076550?check_suite_focus=true#step:8:83)713[90](https://github.com/ankidroid/Anki-Android/runs/5334076550?check_suite_focus=true#step:8:90)94
            at com.ichi2.compat.CompatV21.contentOfDirectory(CompatV21.java:278)
            at com.ichi2.compat.Compat.hasFiles(Compat.java:170)
            at com.ichi2.anki.model.Directory.hasFiles(Directory.kt:50)
            at com.ichi2.anki.model.DirectoryTest.has_files_is_false_if_no_longer_exists$lambda-1(DirectoryTest.kt:95)
            at com.ichi2.testutils.AnkiAssert.assertThrows(AnkiAssert.java:57)
            ... 1 more
```

2022-02-28 16:32 UTC, mikehardy approved these changes
seems fine to me, passes tests now

2022-02-28 16:35 UTC, mikehardy commented
I think needs rebase vs #10400 - that's the first commit from these 2 if I understand correctly

2022-02-28 17:03 UTC, Arthur-Milchior commented
It didn't really need a rebase. But I just gave it if it simplifies the review.
It just mean the first commit do not appear anymore as part of this PR

2022-03-01 13:36 UTC, david-allison reviewed
One question, one nitpick, seems good!

2022-03-01 13:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/DeleteEmptyDirectory.kt
> +        val hasFile = try {
rename to `directoryContainsFiles`

2022-03-01 13:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/DeleteEmptyDirectory.kt
> +        } catch (ex: NoSuchFileException) {
I thought `NoSuchFileException` was API 26+: https://developer.android.com/reference/java/nio/file/NoSuchFileException . Does this work on lower APIs?

2022-03-01 21:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/DeleteEmptyDirectory.kt
> +        } catch (ex: NoSuchFileException) {
This was Kotlin.io.NoSuchFileException. Thanks a lot for catching it.

2022-03-02 00:52 UTC, Arthur-Milchior commented
It now depends of #10418

2022-03-04 13:08 UTC, mikehardy commented
unblocked I think!

2022-03-04 14:20 UTC, david-allison commented
Unblocked, next candidate for merging/review after a rebase

2022-03-04 17:14 UTC, david-allison requested changes
Overall, I like this. It's unpleasant complexity, but required due to your bug with `listFiles()`

Could I get more context here for `hasFiles()/listFiles()` failing and how we handle it in all cases? 

I don't feel the test cases that we have explicitly mention it, or try to emulate it from an API 21/26 perspective, and therefore it's hard to get a handle on whether this is all we need.

2022-03-04 17:14 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/compat/CompatHasFilesTest.kt
> +        }
The message seems wrong

2022-03-04 17:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
> +     * @throws [NoSuchFileException] if the file do not exists (starting at API 26)
What about `FileNotFoundException`?

2022-03-04 17:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/DeleteEmptyDirectory.kt
> +        if (!directory.directory.exists()) {
This needs documentation on why it's here

2022-03-04 19:00 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
> +        return contentOfDirectory(directory).hasNext();
Nice catch.

2022-03-04 19:01 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/compat/CompatHasFilesTest.kt
> +        }
Indeed

2022-03-04 19:11 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
> +     * @throws [NoSuchFileException] if the file do not exists (starting at API 26)
Oh right, it does not raise NoSuchFileExceptino anymore. I thought this was corrected. I'm surprised

2022-03-04 19:23 UTC, Arthur-Milchior commented
> Overall, I like this. It's unpleasant complexity, but required due to your bug with `listFiles()`

I agree. Not pleasant to have to write all of this.

> Could I get more context here for `hasFiles()/listFiles()` failing and how we handle it in all cases?

Right now, `hasFiles` and `listFiles` only throw an exception. In the case of the bug I had, the operation is not going to catch them (since the folder exists but can't be listed); that means that we'll need to decide in the executor what occurs if an exception is thrown by an operation. Right now, I don't plan to do anything with this exception. After all, I don't even have an activity to display a message, nor an executor that can do anything.

> I don't feel the test cases that we have explicitly mention it, or try to emulate it from an API 21/26 perspective, and therefore it's hard to get a handle on whether this is all we need.

I believe I see what you mean here. Would you accept to merge this PR and use another one to add tests that deals with mocking the file and making it fail the way my bg occured?

2022-03-04 19:27 UTC, david-allison requested changes
One change, rest looks good

2022-03-04 19:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
> +        stream.close();
do this in a try with resources block, otherwise `hasNext()` can fail

2022-03-04 19:28 UTC, david-allison commented
> I believe I see what you mean here. Would you accept to merge this PR and use another one to add tests that deals with mocking the file and making it fail the way my bg occured?

Of course!

2022-03-04 19:31 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
> +        return contentOfDirectory(directory).hasNext();
my fears realized :laughing:

2022-03-05 00:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
> +        stream.close();
Done

2022-03-05 00:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
> +        stream.close();
Done

2022-03-05 00:55 UTC, david-allison approved these changes
Nit: Implementers choice

2022-03-05 00:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
> +        FileStream stream = contentOfDirectory(directory);
Use a try with resources block

Pseudo code:

```java
try (FileStream stream...) {
    return stream.hasNext()
}
```

2022-03-05 03:14 UTC, merged

2022-03-14 19:54 UTC, mikehardy commented
#5304