Introduce Compat(Helper)ForTest
ankidroid/Anki-Android pull request #10418
Opened 2022-03-02 00:11 UTC by Arthur-Milchior

I wanted to ensure that there is a method that check whether we use the expected
exception for absent file depending on the API. So I decided to extend Compat
and CompatHelper for tests and use it to simplify a test. It'll be used again in
other PR which need to deal with missing files, in particular ensuring hasFile raises

2022-03-02 00:56 UTC, david-allison requested changes
(for discussion, not a "must").

This is a significant amount of code to avoid the following line in `Compat`:

https://github.com/ankidroid/Anki-Android/blob/babb9ffbe8ec69fbf67c7fed63fa1338690e2684/AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java#L111-L113

I'd be in support of unifying the exception, which would reduce the amount of consumer code, documentation, and remove the need for this PR.

2022-03-02 13:55 UTC, mikehardy commented
I don't see why the Compat infrastructure can't also serve whatever needs are present for tests. Compat is all internal-use anyway

My criteria for answering the question "should we duplicate Compat as an object hierarchy in the test tree" is then "Would the test code we need to add to Compat make it incompatible with non-test usage".

If your new code goes in to the main Compat infrastructure and has no side effects in non-test usage, just add it to Compat I think

Otherwise...okay a full test-only set of subclasses for Compat but that seems like a maintenance burden over time

2022-03-02 14:11 UTC, david-allison commented
I've looked at https://github.com/ankidroid/Anki-Android/pull/10398/files, and I'm still of the opinion:

throw `FileNotFoundException` instead of `NoSuchFileException` in `Compat26` and remove all the boilerplate. 

I'm concerned I'm missing some nuance. I don't see any benefit from this approach.

2022-03-03 23:35 UTC, Arthur-Milchior commented
Simplified a lot as i hope you want. I won't rebase other PR before this one is merged, too much work, and I'm not certain this is what you want

2022-03-04 01:08 UTC, david-allison approved these changes
Lovely, thanks!

2022-03-04 01:09 UTC, david-allison commented
```
w: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/compat/DirectoryContentTest.kt: (83, 13): Variable 'exception' is never used
> Task :AnkiDroid:compilePlayDebugUnitTestKotlin FAILED

> Task :AnkiDroid:deleteSingleFileInGradle UP-TO-DATE
```

2022-03-04 01:09 UTC, david-allison requested changes
Ci Failure. Treat this as an "approve" after it's fixed.

```
w: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/compat/
DirectoryContentTest.kt: (83, 13): Variable 'exception' is never used
> Task :AnkiDroid:compilePlayDebugUnitTestKotlin FAILED
```

2022-03-04 04:22 UTC, mikehardy approved these changes
If David's happy with this one, I'm happy with this one ;-)
same - fix CI and merge works for me

2022-03-04 12:31 UTC, david-allison approved these changes
Awesome! Awaiting CI

2022-03-04 13:07 UTC, merged

2022-03-14 19:54 UTC, mikehardy commented
#5304