Do not make a copy when reattaching the same audio or video file
ankidroid/Anki-Android pull request #10422
Opened 2022-03-03 15:24 UTC by BrayanDSO

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes #10419

## Approach
1. Fix outdated/broken behaviors
    - MediaClipField files weren't being deleted
    - The illegal chars on media names were outdated
2. Cache temporary audio files (like the ImageField behavior) and keep their names
3. Updated the field preview
    - i.e. the text added after confirming the file selection, below the `AUDIO` and `VIDEO` buttons (0:06 on the procedure video)
5. Make tests to guarantee cached temporary files deletion and audio importing with same name
6. Cleaned unused functions/variables

## How Has This Been Tested?

Tested on my phone (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 30)

Procedure:

https://user-images.githubusercontent.com/69634269/156594640-dc006633-a7da-4943-9c17-b3a292687a9d.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-03-03 17:22 UTC, mikehardy requested changes
Oh nice! I had some small comments but this looks pretty good

2022-03-03 17:22 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
> +    private static final Pattern fIllegalCharReg = Pattern.compile("[\\[\\]><:\"/?*^\\\\|\\x00\\r\\n]");
Nice catch! Can you add a comment with a link to what is hopefully the current line for future maintenance? Something like:

// Upstream illegal chars defined in https://github.com/ankitects/anki/blob/main/rslib/src/media/files.rs#L70

2022-03-03 17:22 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldController.kt
> +        return File(mAnkiCacheDirectory, filename)
do we want to set File.deleteOnExit() just in case? :thinking:  Previously we got that behavior because it is built in to File.createTempFile

2022-03-03 17:22 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
> -    fun saveMedia(col: com.ichi2.libanki.Collection, noteNew: MultimediaEditableNote) {
This is only tangentially related, but this act of saving new media related to a note is something that is apparently not working currently from the Ankidroid API - #10335 - is/was this method in the call chain there at all? I wonder if our current tests in `src/androidTest` are covering adding media at all?

2022-03-03 20:42 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
> +    private static final Pattern fIllegalCharReg = Pattern.compile("[\\[\\]><:\"/?*^\\\\|\\x00\\r\\n]");
Done

2022-03-03 20:43 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldController.kt
> +        return File(mAnkiCacheDirectory, filename)
This is a nice touch. Added to it and image importing too

2022-03-03 20:52 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
> -    fun saveMedia(col: com.ichi2.libanki.Collection, noteNew: MultimediaEditableNote) {
saveMedia() is not used anywhere. None of the functions at `NoteService` are being used on JS API.

For importing media, I know there are `MediaTest.java` and `NoteServiceTest`, but I haven't seen any on `src/androidTest`.

Unrelated: there are 2 `MediaTest.java` for some reason. It looks like someone copied it to tests folder, then forgot to delete the old one.

2022-03-03 20:55 UTC, BrayanDSO commented
I added 9f0abb0 too based on Mike's suggestion about `file.deleteOnExit()`. May not be directly related to audio and video, but they are part of media importing, so I think it's better to fix it now

2022-03-03 21:25 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
> -    fun saveMedia(col: com.ichi2.libanki.Collection, noteNew: MultimediaEditableNote) {
> saveMedia() is not used anywhere. None of the functions at `NoteService` are being used on JS API.

I meant the ContentProvider API that native developers can use, the JS API is sort of (in my mind) the other end of the system. The API that's having problems with media add at the moment is the one from here https://github.com/ankidroid/Anki-Android/tree/master/api with sample here https://github.com/ankidroid/apisample - but, this is likely completely unrelated

> 
> For importing media, I know there are `MediaTest.java` and `NoteServiceTest`, but I haven't seen any on `src/androidTest`.
> 

This is what I was referring to https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java - it's in the same area but I don't think it's actually related here


> Unrelated: there are 2 `MediaTest.java` for some reason. It looks like someone copied it to tests folder, then forgot to delete the old one.

:facepalm: well, anything you see that's worthy of cleanup, if you send a PR that's awesome :laughing: :+1:

2022-03-03 21:26 UTC, mikehardy commented
Did that perturb an unrelated preferences test somehow? Or just a flaky test?

```

com.ichi2.anki.servicemodel.UpgradeVolumeButtonsToBindingsTest > if_gesture_already_exists_then_do_not_modify_list[0: isValid(TestData(affectedPreferenceKey=gestureVolumeUp, keyCode=24, unaffectedPreferenceKey=gestureVolumeDown, binding=com.ichi2.anki.reviewer.MappableBinding@1900db))={1}] FAILED
    java.lang.AssertionError: Binding gestures should not be changed
    Expected: iterable containing ["preferenceUpgradeVersion", "gestureVolumeUp"]
         but: item 0: was "gestureVolumeUp"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at com.ichi2.anki.servicemodel.UpgradeVolumeButtonsToBindingsTest.if_gesture_already_exists_then_do_not_modify_list(UpgradeVolumeButtonsToBindingsTest.kt:164)
```

I'm re-running it to see if it was flaky, if so, should go in separate issue

2022-03-03 21:30 UTC, mikehardy approved these changes
All looks good to me at the moment, thanks!

2022-03-03 21:43 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
> -    fun saveMedia(col: com.ichi2.libanki.Collection, noteNew: MultimediaEditableNote) {
`I meant the ContentProvider API that native developers can use, the JS API is sort of (in my mind) the other end of the system. The API that's having problems with media add at the moment is the one from here https://github.com/ankidroid/Anki-Android/tree/master/api with sample here`

Ohhhhhhhh, makes more sense. But there aren't any more calls to `Noteservice.saveMedia()`, so the bug ir probably somewhere else

`Unrelated: there are 2 MediaTest.java for some reason. It looks like someone copied it to tests folder, then forgot to delete the old one`

I was wrong, kind of. A bunch of updated upstream tests were ported to Java again in #6708, but some files weren't united, like this `MediaTest` and now there are two of them

2022-03-04 16:53 UTC, Akshay0701 approved these changes
LGTM

2022-03-04 16:53 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldController.kt
> +    private var mAnkiCacheDirectory: String? = null
```suggestion
    private var ankiCacheDirectory: String? = null
```

2022-03-04 17:26 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldController.kt
> +    private var mAnkiCacheDirectory: String? = null
Done. Thanks

2022-03-04 20:56 UTC, mikehardy approved these changes

2022-03-04 20:56 UTC, merged