NF: add test for contentOfDirectory for file access exception
ankidroid/Anki-Android pull request #10430
Opened 2022-03-05 03:16 UTC by Arthur-Milchior

This simulates https://github.com/ankidroid/Anki-Android/issues/10358

I'm not happy with the introduction of `mNewDirectoryStream` but have no other idea to force this method to throw. Any improvement welcomed. Otherwise, when this is merged, I'll ensure that similar tests are used with all methods that indirectly uses `contentOfDirectory` such as `asFile` and `MoveContentOfDirectory`

2022-03-05 13:05 UTC, david-allison requested changes
I would: 

* extract `newDirectoryStream` to a `internal` `VisibleForTests` method (no visibility modifier for the method in Java)
* use a `spy` to override the implementation of the method: return null or throw

```
w: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/compat/DirectoryContentTest.kt: (112, 13): Variable 'nds' is never used
> Task :AnkiDroid:compilePlayDebugUnitTestKotlin FAILED
```

2022-03-05 18:54 UTC, david-allison approved these changes
Looks great! One question

2022-03-05 18:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
> +    interface NewDirectoryStream {
I don't believe this is required

2022-03-05 21:22 UTC, mikehardy approved these changes
looks good - quite an odyssey to pin that strange error down!

2022-03-05 21:22 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
> +    interface NewDirectoryStream {
agreed - unless I'm missing something this is no longer needed - if that's correct feel free to just remove + push and mark pending ci etc etc :-)

2022-03-05 23:19 UTC, Arthur-Milchior commented
Interface removed

Well, it's only a first step. I'll need to reproduce this test on every method that indirectly uses this list of directory's file

2022-03-06 00:04 UTC, david-allison approved these changes

2022-03-06 00:04 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/compat/DirectoryContentTest.kt
> +                    doThrow(AccessDeniedException(directory)).`when`(it).newDirectoryStream(any())
(please don't block on this):

`whenever` is a kotlin method which replaces `when`, as it's now a reserved keyword. 

There's also an open issue in the Kotlin mockito to make this syntax nicer to use Right now, it's pretty nasty

2022-03-06 00:08 UTC, merged

2022-03-14 19:54 UTC, mikehardy commented
#5304