Fix `setDid()` when did is null
ankidroid/Anki-Android pull request #10435
Opened 2022-03-05 18:00 UTC by BrayanDSO

## Fixes
Fixes #10434

## Approach
Check if "did" property in model is not null before trying to get its value

## How Has This Been Tested?

Tested on my device (where the problem first happened) (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 30)

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-03-06 00:38 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +            } else if (!model.isNull("did")) {
This solve your issue, no doubt about it. However, that clearly do not solve the underlying issue, which is that a model has no did.

Ideally, I'd love if you would create in Model a method `getDid(default=1L) : Long` that would return the property did if it is set, otherwise default value, and use it everywhere. In this case you'd use `mCurrentDid` as default.
It would ensure the problem is solved everywhere

Please wait until a second reviewer validate my suggestion before doing so.

2022-03-06 18:08 UTC, mikehardy requested changes
~~I think we discussed on discord, but dropping it here - as far as we know this is corrupt data relative to something we consider to be an invariant (that deck id is never null), so this should not be null-checked it should prompt the "help user run check database to fix corrupt collection" flow~~ [edited to note it's not corrupt data! v11 schema allows null on deck id, "Today I learned..."]

2022-03-07 15:15 UTC, mikehardy approved these changes
LGTM, follows conversation from linked issue (informed by Damien) with regard to nullability on deck id in schema v11+, thanks @BrayanDSO !

2022-03-07 15:16 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +            } else if (!model.isNull("did")) {
discussed on linked issue, we learned deck id is now nullable in v11+ schema, so this PR in current form appears to be minimal + correct to handle that

2022-03-07 15:31 UTC, merged