Permission exception operation
ankidroid/Anki-Android pull request #10441
Opened 2022-03-06 06:33 UTC by Arthur-Milchior

This begins with #10439.
It checks that if there is no permission to list directory content, then the exception is not catched in:
* creation of MoveDirectoryContent
* execution of DeleteDirectory
* entire execution of MoveDirectory
* Directory's hasFile

2022-03-06 13:50 UTC, david-allison reviewed
Looks good. Implementer's choice on the comments, they're just nitpicks/refactorings.

2022-03-06 13:50 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/compat/CompatDirectoryContentTest.kt
> +        fun assertThrowIOExceptionSubclassWhenPermissionIsDenied(test: () -> Unit): IOException {
This is verbose, possibly `assertThrowsWhenPermissionDenied`

2022-03-06 13:50 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/compat/CompatDirectoryContentTest.kt
> +         * Allow to ensure that `test` throw an IOException.
[test], not using backticks

2022-03-06 13:50 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/compat/CompatDirectoryContentTest.kt
> +            return exception!!
(nit/implementer's choice) The `!!` here may be fixable:

1) Kotlin may have similar functionality to JetBrains' `[InstantHandle]` for C#. I expect it would
2) (more practically):

`return runWithPermissionDenied { assertThrowsSubclass<IOException>(test) }` and change `runWithPermissionDenied ` to:

```
fun <T> runWithPermissionDenied(test: () -> T): T {
```

2022-03-06 13:50 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/model/DirectoryTest.kt
> +        val directory = Directory.createInstance(permissionDenied.directory)!!
I'd like to see this as a method on `permissionDenied`.

2022-03-06 17:52 UTC, mikehardy commented
unblocked, needs rebase+push, I'll wait to see what happens with the comments before a check

2022-03-10 20:22 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/compat/CompatDirectoryContentTest.kt
> +        fun assertThrowIOExceptionSubclassWhenPermissionIsDenied(test: () -> Unit): IOException {
Thanks
I blame Objective-C for it.  Longest method name I've ever see. Takes time to get used to it, but that's acceptable

2022-03-10 21:14 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/compat/CompatDirectoryContentTest.kt
> +            return exception!!
Nice.
Clearly, I'm not yet used to Kotlin

2022-03-10 22:50 UTC, david-allison requested changes
Missing `@RunWith(Parameterized::class)`

```
com.ichi2.anki.model.DirectoryTest > initializationError FAILED
    org.junit.runners.model.InvalidTestClassError: Invalid test class 'com.ichi2.anki.model.DirectoryTest':
      1. Test class should have exactly one public zero-argument constructor
        at org.junit.runners.ParentRunner.validate(ParentRunner.java:525)
        at org.junit.runners.ParentRunner.<init>(ParentRunner.java:102)
        at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:84)
        at org.junit.runners.JUnit4.<init>(JUnit4.java:23)
        at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
        at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
        at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
        at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:[78](https://github.com/ankidroid/Anki-Android/runs/5503495413?check_suite_focus=true#step:8:78))
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at jdk.internal.reflect.GeneratedMethodAccessor131.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:[94](https://github.com/ankidroid/Anki-Android/runs/5503495413?check_suite_focus=true#step:8:94))
        at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:[100](https://github.com/ankidroid/Anki-Android/runs/5503495413?check_suite_focus=true#step:8:100))
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

2022-03-10 23:50 UTC, david-allison approved these changes
LGTM

2022-03-11 01:42 UTC, mikehardy approved these changes
issue 10358 will live on in infamy forever now ;-)

2022-03-11 01:42 UTC, merged

2022-03-14 19:55 UTC, mikehardy commented
#5304