[JS Addons] Extract .tgz file to provided directory with tests
ankidroid/Anki-Android pull request #10451
Opened 2022-03-07 09:11 UTC by krmanik

## Pull Request template

## Purpose / Description
In JS Addons the addon packages are downloaded from npm registry. The file format of downloaded file is .tgz, so I created this class to extract .tgz file to provided directory. This first PR is in series of JS Addons feature implementation. There will be about 4-5 PRs. I have created this small PR for faster review and easier to maintain the code.

## Fixes
Fixes #7959

## Approach
I have used [TarUtil.java](https://android.googlesource.com/platform/tools/tradefederation/+/master/src/com/android/tradefed/util/TarUtil.java) and converted to kotlin. Also added zip slip safety. 

## How Has This Been Tested?
I have added test class with sample .tgz file to test untar, ungzip and extract to addons folder.

## Learning (optional, can help others)
[TarUtil.java](https://android.googlesource.com/platform/tools/tradefederation/+/master/src/com/android/tradefed/util/TarUtil.java)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-03-07 23:41 UTC, david-allison requested changes
Looks great!

Could you rebase this and add more detail to the commit message, especially where you got the files and the changes which were made. (copied from the PR should be fine)

This would be ideal in the header of `TgzPackageExtract` as well

2022-03-07 23:59 UTC, david-allison approved these changes
LGTM

2022-03-08 15:17 UTC, mikehardy requested changes
Nice! Thanks for picking out at least one part of the JS Addons work and pushing it through again. You continue to have my personal apology for not collaborating with you more on this work, my actions haven't matched my words here but I really am still quite excited to see this work land.

I feel like all the strings should be translatable as noted, then most of the rest of my comments are dealing with safety (size expansion, directory clobbers) or error handling. Nothing in here feels far from being merge-able I just want to make sure that if we're handling files and unpacking things that we handle all the nefarious corner cases.

Think like a hacker and imagine not just posting up a package that is malicious, but one that is really specifically malicious: it contains a massive all-zero file (so it expands tremendously!) and the file is named the same thing something important in a popular add-on directory so it will corrupt some other add-on people love (like image occlusion) while filling the phone. Super irritating, but possible right now, and you as the developer have to protect people from that malicious addon publisher

2022-03-08 15:17 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +            throw ArchiveException(String.format("Entry is outside of the target dir: %s", outputFileCanonicalPath))
I think this should be more strongly worded, but also should be pulled in to a string constant for translation since I think these errors will be exposed to users in future PRs

```suggestion
            throw ArchiveException(String.format("Malicious archive. Contains entry outside of the target dir: %s", outputFileCanonicalPath))
```

2022-03-08 15:17 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +        require(isGzip(tarballFile)) { String.format("%s is not a valid .tgz file.", tarballFile.absolutePath) }
Just a tiny wording change to be more user-friendly, but I think it should be in a string constant as I think these will be exposed as errors to the user eventually?

```suggestion
        require(isGzip(tarballFile)) { String.format("%s is not a valid javascript addon package.", tarballFile.absolutePath) }
```

2022-03-08 15:17 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +            check(addonsDir.mkdirs()) { String.format("Couldn't create directory %s.", addonsDir.absolutePath) }
string constant so you can expose them to users eventually?

2022-03-08 15:17 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +        outputStream.close()
will these close automatically if there was some problem with the copy? or do they need to be in the kotlin equivalent of a try/catch from java? I'm unsure, my kotlin is not very good

2022-03-08 15:17 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +        IOUtils.copy(tarInputStream, outputFileStream)
this can also run out of space, we either need to guard against that at the initial stage by checking for 2x the space requirement, or perhaps the gzip/untar can be combined into one chained stream operation based off the single backing .tgz so we don't need to temporarily expand the tgz to a tar before unpacking? Granted, these packages should all be tiny so it shouldn't really matter - it may not be worth any complication it creates (like, making it difficult to read tar info to check directory location for overwrite safety)

2022-03-08 19:29 UTC, krmanik commented
I have started implementing the suggested changes. I will push the changes to PR considering the security points.

2022-03-10 13:49 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +        IOUtils.copy(inputStream, outputStream)
I have created check on space by following
1. Before extracting files, it will check the required space for .tgz file with 2x length
2. Then before writing data to outputstream, a function will iterate over the files inside tar files and get the size
3. The size then checked with available size, if size available then it will proceed with `unTar` by writing data to outputstream.

2022-03-10 13:49 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +    fun extractTarGzipToAddonFolder(tarballFile: File, addonsDir: File) {
The naming collisions will handled by following approach
1. When user download, then it creates folder with name that is also id for npm packages which are unique
2. Before extracting, it needs to create a folder inside `AnkiDroid/addons` where the files will be extracted
3. There will be check if folder exists on UI class, if folder exists then it will prompt user that the addon already exists
4. If folder does not exists then it extract the tar file simply 
5. Otherwise the user will have two option `Update/Overwrite` and `Cancel`

2022-03-10 13:50 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +        unTar(tarTempFile, addonsDir)
I think the catch block should be added on UI class where the extract method called.
Throw exception added to unTar method.

2022-03-11 02:15 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +    fun extractTarGzipToAddonFolder(tarballFile: File, addonsDir: File) {
okay, that works

2022-03-11 02:35 UTC, mikehardy requested changes
You should take a 100GB file of all zeros (or something of similar ridiculous size, and tar.gz it so you have an invalid test too, then you can test my comment about gzip bombs. `cat /dev/zero > bigfile.zero` will get you one. You can even do a sparse file on unix so you don't take up your actual filesystem space if you use dd 

I think this is even closer than last time, I still want the temp file deleted just in case, and I want to make sure a malicious archive with unexpectedly huge compression ratio can't mess up users, but this is otherwise good to go now

2022-03-11 02:35 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +        // Make sure we have sufficient free space (twice)
just a wording change / nitpick

```suggestion
        // Make sure we have 2x the tar file size in free space (1x for tar file, 1x for unarchived tar file contents)
```

2022-03-11 02:35 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +        unTar(tarTempFile, addonsDir)
but if you throw, the UI class will have no knowledge of the tarTempFile which is internal to this class.
I don't see why you wouldn't both set deleteOnExit and catch here (to delete the temp file) even if you re-throw for UI to handle

2022-03-11 02:35 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +        val requiredMinSpace = tarballFile.length() * 2
This needs a similar calculation here in case the gzip is a decompression bomb - I read up on it, apparently the only way to know reliably is by decompressing it as a stream and throwing away the bytes but adding them up and returning the size

https://stackoverflow.com/questions/9715046/find-the-size-of-the-file-inside-a-gzip-file

I think for the expected sizes we will see that is acceptable, and to make sure we don't completely crash while doing it you could stop as soon as the decompression would hit 0.5x max available space ? Decompression bombs are computational trivial so something like that wouldn't freeze the app too long before throwing a malicious archive error ?

2022-03-11 16:33 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +        val requiredMinSpace = tarballFile.length() * 2
I have implemented checks inside unTar method but I think the process of extract will be slower, because of multiple checks but necessary to security purposes
1. Iterating entries of tar to get size before extract
2. Extract the entries of tar file and checking available space is not increased 50% space of previous available space

2022-03-11 21:33 UTC, mikehardy requested changes
I still have concerns about compression bombs and temp file deletion but I also continue to maintain it's not far from being +1

2022-03-11 21:33 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +            tarballFile.deleteOnExit()
This is a layering violation - the resource (tarballFile) was given to the method (our layer) by some caller (a higher level, calling down in to this method). The caller, since it sent the file, needs to maintain control over the resource. If it needs to be deleted, that's up to the caller, you can unpack it here (that's the API) but you may not delete it  or set it to be deleted

2022-03-11 21:33 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +            tarTempFile.deleteOnExit()
This is a slight misunderstanding of my goal with regard to the tarTempFile resource.
We create this here, so we are in control of it, and we must make sure it is cleaned up.
You should call deleteOnExit *the moment it is created*, not in a finally block.
In the finally block you should actually delete it, as you no longer need it, right?

2022-03-11 21:33 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +        }
This right here is still susceptible to a compression bomb. You haven't addressed that.
Correctness is more important than performance, performance does not matter if it is not correct.
So you have to get correctness first, then you go for performance.

The correctness-oriented approach is to attempt the decompression first while discarding the bytes, stopping at some  pre-determined size that's obviously ridiculous for an addon (100MB? I don't know something high) or one half the free space remaining (so there is room for the tarfile and it's expansion). You keep track of the bytes expanded and that's the decompressed size, or you throw IOException with malicious archive message

The computational cost of ungzipping (twice), unpacking the tar etc of an addon *of normal size* (some handful of kilobytes?) is inconsequential. I argue the performance doesn't matter. But I don't want anyone to accidentally trash someone's phone via our code if possible

2022-03-11 22:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +        outputStream.close()
```kotlin
class.use {

}
```

2022-03-12 04:53 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +        }
I have removed `IOUtils.copy` method and used `BufferedOutputStream` to handle compression bombs.
Here the .tgz file have to checked two times for compression bombs
1. when it converted to .tgz to .tar
2. when .tar file untar 

So, I have used global variable `count` for counting number of bytes get written and checking if the bytes is less than 100 MB otherwise throw exception.

The performance will not be issue of files normal file sizes.

2022-03-12 05:06 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +            tarTempFile.deleteOnExit()
That's right because the here there are two files
1. tgz npm package which will be delete by caller of this method
2. tar file which created after unGzip so if untar succeed or failed delete the files

In catch block if files being untar and failed then the directory also need to clean.

2022-03-12 05:08 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +            tarballFile.deleteOnExit()
I have removed the line which delete the file to avoid `layering violation`.

2022-03-12 05:15 UTC, krmanik commented
The things I have learned in this PR, which also be useful for others
1. layering violation
>This is a layering violation - the resource (tarballFile) was given to the method (our layer) by some caller (a higher level, calling down in to this method). The caller, since it sent the file, needs to maintain control over the resource. If it needs to be deleted, that's up to the caller, you can unpack it here (that's the API) but you may not delete it or set it to be deleted.
https://github.com/ankidroid/Anki-Android/pull/10451#discussion_r825119872

2. compression bomb
> https://github.com/ankidroid/Anki-Android/pull/10451#pullrequestreview-906696147
https://wiki.sei.cmu.edu/confluence/display/java/IDS04-J.+Safely+extract+files+from+ZipInputStream

3. zip slip safety
https://snyk.io/research/zip-slip-vulnerability

_This comments will be updated with new topics from this PR_

2022-03-12 12:20 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +            tarballFile.deleteOnExit()
I'm not sure "layering violation" is a real technical term :sweat_smile: but it is how I think of systems yes. You can use any words that make sense but the essence of the idea is "the code that created a system resource should have absolute control over the system resource if at all possible". There are exceptions but they should be rare. So where ever you create a file, now in that same code you are responsible for closing/deleting the file in all circumstances.

I think of a system as vertical layers (why? I don't know) so to me they are layers, but others think in terms of control or maybe something different, and that's all fine. I think another term people use for this is "coherence" or "locality", which has the idea that the same type of operation (resource create + delete) should be in the same spot

2022-03-12 12:34 UTC, mikehardy requested changes
Still some issues with resource handling but as always, getting closer...definitely not vulnerable to compression bombs now!

2022-03-12 12:34 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +
right here - this is where you should set deleteOnExit
This is a very very minor improvement in error handling, since you are already deleting it in a finally it should be good right? But, what if the system actually puts the app in the background while calculating size, or kills the app for memory pressure etc? Before you get to the finally? If you set deleteOnExit it will clean up even then!

```suggestion
        val tarTempFile = unGzip(tarballFile, addonsDir)
        tarTempFile.deleteOnExit()

```

2022-03-12 12:34 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +        }
This whole block should be in a try/catch, and in the catch you should delete outputFile then re-throw, otherwise it will be orphaned, right? This is kind of a layering violation as well. I did not notice it before, but you are creating the file down here and returning it (so you lose control of it). I think that's okay as long as you only leave the file on the filesystem if it is a known good result of gunzip. If gunzip fails we must clean up our temp work

2022-03-12 12:34 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +                    if (total + BUFFER > TOO_BIG_SIZE) {
if the total + BUFFER > TOO_BIG_SIZE *or* greater than half the remaining space we should throw, because if it's more than 0.5x remaining space, we won't be able to make the tar-file *and* unpack the tar file, right?

2022-03-12 12:34 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +        total = 0
I don't think you need to worry about expansion sizes in tar files. They do not have compression built in that I know of? So during untar you just need to worry about the total size once, and about zipslip

2022-03-12 12:34 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +            addonsDir.deleteRecursively()
Oh my, isn't this the whole addons directory? With all the addons? Don't we want to clean up just the one that we were unpacking in to ? :thinking:

2022-03-12 16:11 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +            addonsDir.deleteRecursively()
I want to remove the folder where the files gets extracted. And the code turn out to remove the whole addon folder get removed on fail. 
I have fixed it.

2022-03-12 16:11 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +        total = 0
It is not required to test expansion sizes because size can be spoofed but still it is good check before writing files.
The function will get called once.

2022-03-12 16:11 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +                    if (total + BUFFER > TOO_BIG_SIZE) {
That's right. I have added `calculateUnTarSize` in `extractTarGzipToAddonFolder` which will call once. Also the size can be spoofed but still it good to check. Then in unTar where loop used to iterate through each files, there `total + BUFFER <= TOO_BIG_SIZE` checked. So if malicious managed to pass though first check then it will not pass in second checks where buffer size check. Also in same method, there is check if available is increased to 50% of space then it will throws exception.

2022-03-12 16:11 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +        }
I have implemented it. I have try/catch.

2022-03-14 16:03 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +        total = 0
okay - better more safe than sorry

2022-03-14 16:11 UTC, mikehardy requested changes
Still in nearly the same spot as last time. Vulnerable to compression bombs, not fully deleting the tar temp file under all conditions - see comments, they are basically the same as the last set of comments.

2022-03-14 16:11 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +        }
we know that we are done working with the tarTempFile now, and it may have been huge relative to available space, let's be kind to the user and delete the file immediately. The deleteOnExit is just to make sure that we delete even if we somehow go in background and are killed by system, we can still be proactive here

```suggestion
        try {
            // If space available then unTar it
            unTar(tarTempFile, addonsDir)
        } catch (e: IOException) {
            Timber.w("Failed to unTar file")
        } finally {
            tarTempFile.delete();
        }
```

2022-03-14 16:11 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +            // file being unGzipped must not be greater than 100MB
You are still not taking in to account that *during ungzip you could have less than the space needed for the tar file or the unpacking of tar file. If at any time the count of bytes ungzipped is more than .5x space available at start, you must throw.

```suggestion
            // file being unGzipped must not be greater than TOO_BIG_SIZE or half of available space
```

2022-03-15 06:41 UTC, krmanik commented
> Still in nearly the same spot as last time. Vulnerable to compression bombs, not fully deleting the tar temp file under all conditions - see comments, they are basically the same as the last set of comments.

I have implemented to remove temp file just before throw exception.
Also the `unTarFile` and `zipPathSafety` is wrapped in try/catch so in catch block the temp file deleted. 

In `unTar` method all checks happen in try catch so when exception happen it will delete the temp file.

2022-03-15 13:13 UTC, mikehardy requested changes
file handling looks good now - no temp files remaining on any code path I can think of
still one tiny bit of gzip size detection I think?

2022-03-15 13:13 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +                        if (total + BUFFER > TOO_BIG_SIZE) {
comment says, and I intended it to be implemented, that:

>             // file being unGzipped must not be greater than TOO_BIG_SIZE or half of available space

while conditional and if conditional are checking our arbitrary limit only, not .5x available space

What happens if available space was 198MB and zip file expands to 99MB? You will ungzip it but then not have enough room to untar, so the gzip should be aborted

2022-03-15 15:17 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +                        if (total + BUFFER > TOO_BIG_SIZE) {
Okay, Now it will check for both .5x available space and 100MB size limit.
I have extracted check to a method and called it where data written using buffer.
Also the method called inside another method which wrapped inside try/catch.

2022-03-15 17:01 UTC, mikehardy requested changes
A few tiny things now - I believe we're protected from compression bombs now which is great, just want the method you used to have a name that is seriousness enough future programmers understand what it could do if they called it

2022-03-15 17:01 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +        val currentFile = File(outputDir, entry!!.name)
How is entry nullable in your parameter list, then force-de-rereferenced, in an APIs that we have made for the first time? The null handling here worries me.

2022-03-15 17:50 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +                    throw IllegalStateException("File being untar is too big")
I have updated the comments in the file.

2022-03-15 17:50 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +    fun checkNewSpaceAvailable(outputDir: File) {
I got this. Thanks

2022-03-24 13:27 UTC, mikehardy commented
I think this is good to go, going to set a timebox on it and merge on Monday if no other feedback

2022-03-28 22:56 UTC, merged

2022-03-28 23:33 UTC, david-allison reviewed
Nothing blocking - sorry I didn't get to this sooner. Optional issue for follow-ups, or leave it as it is.

2022-03-28 23:33 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="malicious_archive_exceeds_limit">Malicious archive. Size exceeds 100MB or contains more than 1024 files</string>
This likely wants formatting so we can change the limits without forcing a retranslation

2022-03-28 23:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +        val outputFile = File(outputDir, inputFile.name.substring(0, inputFile.name.length - 4) + ".tar")
kotlin has `nameWithoutExtension`

2022-03-28 23:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +            throw IOException(context.getString(R.string.import_log_insufficient_space_error, Formatter.formatFileSize(context, requiredMinSpace), Formatter.formatFileSize(context, availableSpace)))
Would be useful to subclass this so it's catchable

2022-03-28 23:33 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/TgzPackageExtractTest.kt
> +        assertTrue(File(packageJsonPath.toString()).exists())
`FileMatchers` allows for better assertions

2022-03-28 23:53 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="malicious_archive_exceeds_limit">Malicious archive. Size exceeds 100MB or contains more than 1024 files</string>
Oo that's a good one @krmanik could you do a quick follow-on with at least this one? I haven't pushed strings out yet for translation, and the flexibility will be nice, plus it's a super quick change.
Rest are up to you if you want to include them in a follow-on

2022-03-29 00:08 UTC, krmanik commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="malicious_archive_exceeds_limit">Malicious archive. Size exceeds 100MB or contains more than 1024 files</string>
I will do it now.

2022-03-29 00:57 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +            throw IOException(context.getString(R.string.import_log_insufficient_space_error, Formatter.formatFileSize(context, requiredMinSpace), Formatter.formatFileSize(context, availableSpace)))
It needs some time to think, I will do in follow up PR.

2022-03-29 02:13 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +            throw IOException(context.getString(R.string.import_log_insufficient_space_error, Formatter.formatFileSize(context, requiredMinSpace), Formatter.formatFileSize(context, availableSpace)))
I am trying to figure out subclass, should I extract it a function and call here?

2022-03-29 03:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +            throw IOException(context.getString(R.string.import_log_insufficient_space_error, Formatter.formatFileSize(context, requiredMinSpace), Formatter.formatFileSize(context, availableSpace)))
Pseudocode (it's late, sorry):

```kotlin
class InsufficientSpaceException(val required, val available, context) : IOException(format(a, b, c)) {

    companion object {
        fun throwIfInsufficientSpace(context, requiredMinSpace, availableSpace) {
            if (requiredMinSpace > availableSpace) {
                Timber.e("Not enough space to extract file, need %d, available %d", requiredMinSpace, availableSpace)
                throw InsufficientSpaceException(requiredMinSpace, availableSpace, context)
        }
    }
}
```

Usage:

`InsufficientSpaceException.throwIfInsufficientSpace(context, requiredMinSpace, availableSpace)`

2022-03-29 03:31 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +            throw IOException(context.getString(R.string.import_log_insufficient_space_error, Formatter.formatFileSize(context, requiredMinSpace), Formatter.formatFileSize(context, availableSpace)))
I pushed it follow up PR.