Add hint gesture/command
ankidroid/Anki-Android pull request #10462
Opened 2022-03-09 00:12 UTC by BrayanDSO

## Fixes
Fixes #7354

## Approach
- Insert javascript to toggle hint one by one in `Toggle hint`, assigned to H hotkey
- Insert javascript to toggle all hints in `Toggle all hints`, assigned to G hotkey

Personally, I think the toggle hint js code isn't the most beautiful thing ever ~~as most of javascript~~, but I prefer it because it is easier to understand/mantain.

A shorter version, but somewhat harder to grasp is:
```javascript
[...document.querySelectorAll('a.hint')].every(el=>{ if (el.style.display === 'none') { return true; } else { el.click(); return; } })
```
If necessary, I can exchange them.

## How Has This Been Tested?

On my phone (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 30)

### One hint

https://user-images.githubusercontent.com/69634269/157347222-21f4f5cc-2000-4a7f-95a4-24b9ac826004.mp4

### All hints

https://user-images.githubusercontent.com/69634269/157347245-296e001a-e241-4f4e-a747-8abe2659c1ce.mp4

### New strings

![Screenshot_20220308-211100_AnkiDroid](https://user-images.githubusercontent.com/69634269/157347364-3182426b-e947-47c8-a17f-87d7758da4a7.png)

![Screenshot_20220308-211052_AnkiDroid](https://user-images.githubusercontent.com/69634269/157347370-bdacd032-c1d1-43a8-a97a-856c51fe6183.png)

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-03-09 00:28 UTC, david-allison requested changes
This is awesome!

One request to define the functions in `card.js`, but this is fantastic, thank you!

We /may/ want to add this to "app bar buttons", but I'll leave that for a user request.

2022-03-09 00:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                        "javascript: var hints = document.querySelectorAll('a.hint'); " +
I'd prefer if this were defined as a JavaScript function which is called here, rather than defining the Javascript in Java.

2022-03-09 00:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                loadUrlInViewer("javascript: document.querySelectorAll('a.hint').forEach(el=>el.click());");
ditto

2022-03-09 22:55 UTC, BrayanDSO commented
I was not completely sure if  the uses of `loadUrlInViewer` are a problem and I should have eliminated them. I just ported the functions to `card.js`.

Note: I changed `Toggle` to `Show` because it makes more sense (hints show `Show FieldName` after all)

A question: Is there a way to automate javascript testing? 
I'd rather being secure these won't break if someone changes `card.js` in the future

2022-03-09 23:24 UTC, david-allison approved these changes
LGTM. I prefer the verbose code, but I'm not a JS expert

2022-03-10 00:31 UTC, BrayanDSO commented
Made `showHint()` a little shorter in 189f1a0

2022-03-11 08:48 UTC, ShridharGoel approved these changes
Just a small formatting change

2022-03-11 08:48 UTC, ShridharGoel commented on AnkiDroid/src/main/assets/scripts/card.js
> +    document.querySelectorAll('a.hint').forEach(el=>el.click());
```suggestion
    document.querySelectorAll('a.hint').forEach(el => {
        el.click();
    });
```

2022-03-11 09:47 UTC, BrayanDSO commented on AnkiDroid/src/main/assets/scripts/card.js
> +    document.querySelectorAll('a.hint').forEach(el=>el.click());
Done

2022-03-11 11:50 UTC, mikehardy commented
For javascript (now that I'm much much better at it then when I started helping on AnkiDroid!), we should really have a .prettierrc and integrate a prettier check in our lint run, against our javascript.
Even if we don't require a full development toolchain for javascript for contributors (not something I recommend), it's easy to use the github setup-node action then do an `npx prettier` run on the files as part of the lint.yml workflow definition

2022-03-11 20:12 UTC, mikehardy commented on AnkiDroid/src/main/assets/scripts/card.js
> +        }
I'm not going to enforce a non-existent styleguide so to be very clear: no changes should be done in response to this

however,

-  != is bad form, you almost always want !== and an eslint config would/should enforce it
- a simple iterator on an array is usually better as Array.forEach(element => function) - this exposes the idea that you may have more than one hint, do you show them all? Probably? so break isn't needed, or if it is you can do hints.length = 0 to force a break from forEach
- if we were using typescript like sane humans I think it would tell you style and display are potentially null, so you should do `style?.display?` but that implies typescript and we're not doing that, I guess you could check for `!== undefined` or the truthy test shortcut of `if hints[i] && hints[i].style && hints[i].style.display !== 'none'`
- click may not exist on the node? same issue

As mentioned, none of this should result in a change here. This is fine for the javascript we have and the environment we operate in, but perhaps in the future we move to a system more like AnkiDesktop where our javascript stuff is professional + modern, that is, it's a javascript bundle produced from solid typescript code with standards enforced etc. Maybe in 2024 ;-)

2022-03-11 20:14 UTC, mikehardy approved these changes
I think this is great, a nice new feature for the gesture system

2022-03-11 20:30 UTC, mikehardy commented
passed my testing locally, ready to go

2022-03-11 20:31 UTC, merged