Edit feature added to custom toolbar button
ankidroid/Anki-Android pull request #10464
Opened 2022-03-09 15:14 UTC by BishyanKar

## Pull Request template

## Purpose / Description
Adding edit feature to custom toolbar button in Add Note screen.

## Fixes
Fixes #10436

## Approach
- Added "Edit" button to the remove dialog and changed its text slightly to suggest the feature. 
- On clicking "Edit" button a dialog similar to create item appears with "Create" button replaced with "Save"
- On clicking "Save" saved the changes to the button

## How Has This Been Tested?

Tested it manually.

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

![feature_edit_option_6](https://user-images.githubusercontent.com/54733471/157710083-37992b92-e3fc-4cba-9859-175177e221d1.jpeg)
![feature_edit_option_5](https://user-images.githubusercontent.com/54733471/157710093-ccad2e8f-24e9-4449-972e-b9e1c62a9d5f.jpeg)

https://user-images.githubusercontent.com/54733471/157710110-2563733b-9cdf-49f4-a7cc-ef19bb61ebff.mp4

2022-03-09 15:39 UTC, david-allison requested changes
Looks great! A few lint errors were tripped, and a couple questions

`gradlew lint` should pick these up so you don't need to use CI to test

```
> Task :AnkiDroid:lintPlayDebug FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/02-strings.xml:360: Error: The resource R.string.remove_toolbar_item appears to be unused [UnusedResources]
    <string name="remove_toolbar_item">Remove Toolbar Item?</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/02-strings.xml:104: Error: Duplicate string value "Save", used in dialog_positive_save, save [DuplicateCrowdInStrings from com.ichi2.anki.lint]
    <string name="save">Save</string>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/03-dialogs.xml:116: Duplicates value in save. Add a comment attribute on both strings to explain this duplication
2 errors, 0 warnings
```

To fix:

* Delete `remove_toolbar_item` from `/values`
* Remove `dialog_positive_save` and use `R.string.save`

2022-03-09 15:39 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="remove_or_edit_toolbar_item">Remove or Edit Toolbar Item?</string>
```suggestion
    <string name="remove_or_edit_toolbar_item">Edit or Delete Toolbar Item?</string>
```

2022-03-09 15:39 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="remove_or_edit_toolbar_item">Remove or Edit Toolbar Item?</string>
Keep the text congruent with the button options.

2022-03-09 16:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +                    removeButton(currentButton);
Can we fix this to ensure the buttons stay in order?

2022-03-09 16:51 UTC, BrayanDSO commented
My personal opinion:
When I use something like this in any app, the default dialog is the edit dialog, and deleting is just a option there.

This is the contrary. The default dialog is the delete and editing is a option. Having to tap an additional button to edit, which is a more common task than deleting, adds friction to the user.

I suggest opening the edit dialog by default, with a delete button below, which leaves less friction.
But, as I said in the beginning, this is just my opinion

2022-03-09 17:12 UTC, BishyanKar commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +                    removeButton(currentButton);
Done

2022-03-09 17:12 UTC, BishyanKar commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="remove_or_edit_toolbar_item">Remove or Edit Toolbar Item?</string>
Done

2022-03-09 20:44 UTC, david-allison commented
> My personal opinion: When I use something like this in any app, the default dialog is the edit dialog, and deleting is just a option there.

I was considering asking for this, and agree

2022-03-09 20:54 UTC, BishyanKar commented
@BrayanDSO @david-allison Alright, I will try and get this done asap.

2022-03-09 22:04 UTC, BrayanDSO commented
And I think the edit dialog should be populated with the previous values

2022-03-10 16:23 UTC, BishyanKar commented
@BrayanDSO Yes I had this in mind as well. Added it in this commit.

2022-03-10 18:23 UTC, Akshay0701 commented
Thanks for your contributions! 

apart from code, I have suggestions for UI, 

it's an inconsistent UI, instead of adding the button "delete" at the bottom of the view, why don't you add delete icon button at top right corner of the view, it's just a suggestion and open to other's feedback :) 

![Capture](https://user-images.githubusercontent.com/52353967/157728948-f5f18a7d-8e57-45c6-907b-c08bafd6e5b8.PNG)

2022-03-10 18:29 UTC, BrayanDSO commented
> Keep the text congruent with the button options.
👆

> it's an inconsistent UI, instead of adding the button "delete" at the bottom of the view, why don't you add delete icon button at top right corner of the view, it's just a suggestion and open to other's feedback :)

I agree. Maybe reuse the `Delete note` icon or an X in the top right

2022-03-10 18:29 UTC, BrayanDSO commented
> Keep the text congruent with the button options.
👆

> it's an inconsistent UI, instead of adding the button "delete" at the bottom of the view, why don't you add delete icon button at top right corner of the view, it's just a suggestion and open to other's feedback :)

I agree. Maybe reuse the `Delete note` icon or an X in the top right

2022-03-13 06:45 UTC, BishyanKar commented
![WhatsApp Image 2022-03-13 at 12 13 29](https://user-images.githubusercontent.com/54733471/158048516-57fc7334-5940-40f3-b952-5d2b9bb85593.jpeg)
![WhatsApp Image 2022-03-13 at 12 13 29 (1)](https://user-images.githubusercontent.com/54733471/158048517-4d09f21a-a4f6-4ea7-b908-48a418f2552d.jpeg)

@BrayanDSO @Akshay0701 which one looks better? Or should I try something else?

2022-03-13 12:28 UTC, BrayanDSO commented
> ![WhatsApp Image 2022-03-13 at 12 13 29 (1)](https://user-images.githubusercontent.com/54733471/158048517-4d09f21a-a4f6-4ea7-b908-48a418f2552d.jpeg)

Pretty neat. 
I personally prefer the trashbin icon. I think it would be better if a little smaller and with one of the theme colors (the same of the buttons would be best I guess).

2022-03-13 14:23 UTC, david-allison commented
I don't see the icon in the diff, but I'd also prefer if it wasn't red.

2022-03-13 14:54 UTC, BishyanKar commented
![WhatsApp Image 2022-03-13 at 20 23 38](https://user-images.githubusercontent.com/54733471/158065470-4a9b02f4-c355-4c23-92e9-7af52c82d1b5.jpeg)
@BrayanDSO

2022-03-13 14:59 UTC, BrayanDSO commented
> ![WhatsApp Image 2022-03-13 at 20 23 38](https://user-images.githubusercontent.com/54733471/158065470-4a9b02f4-c355-4c23-92e9-7af52c82d1b5.jpeg)

Wonderful! For me, this is it. 

Let's hear the others.

A night mode screenshot would be nice too

2022-03-13 15:19 UTC, david-allison commented
Looks good! Could you push the code so we can check it out on our devices?

2022-03-13 15:52 UTC, BishyanKar commented
> Looks good! Could you push the code so we can check it out on our devices?

Pushed it.

2022-03-14 18:10 UTC, BishyanKar commented
> I like this in general, thank you very much for posting it! However it appears that in your version control you have done a merge commit instead of a rebase commit, so I can't tell exactly what changed. Briefly change to my perspective as a reviewer trying to make sure the source code edits are good and imagine reviewing this - https://github.com/ankidroid/Anki-Android/pull/10464/files 😅
> 
> It's not possible. Can you do a _rebase_ merge from main?

Noticed it, sorry for the mistake. Trying to fix it.

2022-03-15 17:04 UTC, david-allison commented
Something's gone wrong with the merge, please fix it, ideally by `rebasing` out the bad commits, or `rebasing` this branch onto the current `main`

2022-03-21 18:50 UTC, BishyanKar commented
Couldn't find a way around for the version control issue, it's getting worse, so I had to create a separate pull request. Sorry for the inconvenience caused and would like request you guys to review the other PR. (#10594).

2022-03-21 19:00 UTC, david-allison commented
> Couldn't find a way around for the version control issue, it's getting worse, so I had to create a separate pull request. Sorry for the inconvenience caused and would like request you guys to review the other PR. (#10594).

Please spend more time trying to rebase this branch's commits onto `main`. Otherwise we lose the review history.

2022-03-22 14:41 UTC, mikehardy approved these changes
Wow, this is a serious feature! LGTM, requesting a quick look from others for final go

2022-03-27 07:21 UTC, BishyanKar commented
@david-allison fixed the version control issue.

2022-03-27 15:55 UTC, david-allison approved these changes
Looks good to me. One copyright question

2022-04-02 04:00 UTC, BishyanKar commented on AnkiDroid/src/main/res/layout/note_editor_toolbar_edit_custom_item.xml
> +  ~  Copyright (c) 2020 David Allison <davidallisongithub@gmail.com>
@david-allison Correct, changed it.

2022-04-02 05:06 UTC, david-allison requested changes
Caught an accessibility issue

2022-04-02 05:06 UTC, david-allison commented on AnkiDroid/src/main/res/layout/note_editor_toolbar_edit_custom_item.xml
> +            android:layout_width="25dp"
Touch targets should be 48x48 for accessibility, and should have a description so blind users know what the icon does.

The icon doesn't need to be 48x48, but the padding/margin should add up to 48x48 to allow users to click.

This is handled by the item in the PR description: 'UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)'

2022-04-02 06:01 UTC, BishyanKar commented on AnkiDroid/src/main/res/layout/note_editor_toolbar_edit_custom_item.xml
> +            android:layout_width="25dp"
![76f57ac4-b66e-4e12-85b8-8053edcf3ee1](https://user-images.githubusercontent.com/54733471/161368930-b5d5d4cc-da33-4bad-a2ca-724490f5ade2.jpg)
![1c5f3c63-9185-4cea-a0ec-38e63d6f8b8a](https://user-images.githubusercontent.com/54733471/161368971-bfff7968-aa62-45e1-b839-98f23ae32f03.jpg)


@david-allison modified the xml file accordingly. Attached ss above.

2022-04-02 15:35 UTC, david-allison approved these changes
Thanks!!

2022-04-02 15:36 UTC, merged

2022-04-02 22:56 UTC, mikehardy commented on AnkiDroid/src/main/res/layout/note_editor_toolbar_edit_custom_item.xml
> +            android:layout_width="25dp"
Fantastic catch! We have not historically done a good job with accessibility (I personally have done a terrible job, I'm not casting blame) so at least myself, I missed that. Great you caught it David

2022-06-05 21:02 UTC, mikehardy commented
Hi there! APRIL OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [April 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-04-01..2022-04-30)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of March.

Please note that GSoC contributions are okay for this process. Our philosophy is that our users have donated to AnkiDroid for all contributions. The only PRs that will not go through the OpenCollective process are ones directly related to am accepted GSoC project from a selected participant, since those receive a stipend from GSoC itself.

Please understand that this means the monthly budget we have for payments might be stretched a bit and the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!