searchdeck button appearing issue fix
ankidroid/Anki-Android pull request #10470
Opened 2022-03-10 15:31 UTC by sampath-houde

## Pull Request template

## Issue
fixes #10445

## Purpose / Description
search deck button was showing even when decks count >= 10

## Fixes
Removed the icons setVisibility property outside a if else block

## Approach
Debugged the deck counts, after debugging got to know that the count is correct. Then I found out because it was inside if else bock the particular line of code wasnt being executed

## How Has This Been Tested?
Have manually tested this bug, and its working as expected

2022-03-10 15:32 UTC, sampath-houde commented
Hey @david-allison please review this PR

2022-03-10 15:49 UTC, viciousAegis commented
Hi, even if you have personally verified that the fix works, it would be great if you could include screenshots/videos to show how it looks after the fix :)

2022-03-10 16:01 UTC, sampath-houde commented
https://drive.google.com/file/d/1JFWaAUCTJ7xA9cyK4Nyogw0mmwvkZ_F4/view?usp=sharing
@david-allison @viciousAegis

2022-03-10 16:02 UTC, BrayanDSO commented
Duplicate of #10468.

@sampath-houde, whenever you want to edit a PR, you should fix it and then push the editions again, not close it and open another one.

There are some git tools like `commit --amend` and `rebase` you can see [here](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) which can help you do your editions while keeping a clean commit history. 

Feel free to ask for help if you need it

2022-03-10 16:05 UTC, sampath-houde commented
Okay, thanks for letting me know

On Thu, 10 Mar, 2022, 9:33 pm Brayan Oliveira, ***@***.***>
wrote:

> Duplicate of #10468 <https://github.com/ankidroid/Anki-Android/pull/10468>
> .
>
> @sampath-houde <https://github.com/sampath-houde>, whenever you want to
> edit a PR, you should fix it and then push the editions again, not close it
> and open another one.
>
> There are some git tools like commit --amend and rebase you can see here
> <https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History> which can
> help you do your editions while keeping a clean commit history.
>
> Feel free to ask for help if you need it
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ankidroid/Anki-Android/pull/10470#issuecomment-1064220341>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM6QOBT2FHVX2GHXDKJN5O3U7IMLJANCNFSM5QM7LU2Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-10 16:46 UTC, Akshay0701 requested changes

2022-03-10 16:46 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
correct me if i am wrong, but i don't think we should take this line of code out of the if statement, 

```java
if (colIsOpen()) {
  displaySyncBadge(menu);
  // Show / hide undo
  if (mFragmented || !getCol().undoAvailable()) {
      menu.findItem(R.id.action_undo).setVisible(false);
  } else {
      Resources res = getResources();
      menu.findItem(R.id.action_undo).setVisible(true);
      String undo = res.getString(R.string.studyoptions_congrats_undo, getCol().undoName(res));
      menu.findItem(R.id.action_undo).setTitle(undo);
  }

  // Remove the filter - not necessary and search has other implications for new users.
  menu.findItem(R.id.deck_picker_action_filter).setVisible(getCol().getDecks().count() >= 10);
}
```

this if statement check whether collection is open or not, and below line also uses collection, 

> menu.findItem(R.id.deck_picker_action_filter).setVisible(getCol().getDecks().count() >= 10);

so to avoid exceptional error, I think we should keep the line of code in the if statement.

2022-03-10 16:57 UTC, sampath-houde commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
@Akshay0701 can you explain what does collectionIsOpen mean here? How is it relevant

2022-03-10 17:30 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
[colIsOpen](https://github.com/sampath-houde/Anki-Android/blob/19c81954d59acf53da59bdec3e0d985e7d3f4b19/AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java#L195) this is method is used to check whether collection is loaded successfully or not, 

> How is it relevant

See `getCol()` is used in the above statement, that method interact and retrive values from collection, and inorder to do that, collection must be loaded first, right?

so that is the reason for using `colIsOpen`.

2022-03-10 17:32 UTC, sampath-houde commented
Okay, when the collections are loaded then only I can get the decks count?

On Thu, 10 Mar, 2022, 11:00 pm Akshay Vilas Jadhav, <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> <https://github.com/ankidroid/Anki-Android/pull/10470#discussion_r823975701>
> :
>
> > -
> -            // Remove the filter - not necessary and search has other implications for new users.
> -            menu.findItem(R.id.deck_picker_action_filter).setVisible(getCol().getDecks().count() >= 10);
>          }
> +        // Remove the filter - not necessary and search has other implications for new users.
> +        menu.findItem(R.id.deck_picker_action_filter).setVisible(getCol().getDecks().count() >= 10);
>
>
> colIsOpen
> <https://github.com/sampath-houde/Anki-Android/blob/19c81954d59acf53da59bdec3e0d985e7d3f4b19/AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java#L195>
> this is method is used to check whether collection is loaded successfully
> or not,
>
> How is it relevant
>
> See getCol() is used in the above statement, that method interact and
> retrive values from collection, and inorder to do that, collection must be
> loaded first, right?
>
> so that is the reason for using colIsOpen.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ankidroid/Anki-Android/pull/10470#discussion_r823975701>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM6QOBSO6I4TQQZGGOYRCTTU7IWSNANCNFSM5QM7LU2Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-10 22:07 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
@Akshay0701 is correct, we should not touch the collection (our sqlite database) to get counts if the collection is not open (that is, we have verified that the collection exists, is not corrupt, and have actually attached a sqlite driver to it and started read/write operations against the database). To touch the collection without knowing it is open (and valid, etc) is asking for a crash

2022-03-13 06:48 UTC, sampath-houde commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
@Akshay0701 @mikehardy whenever I press on sync the search deck button appears, even if the count of decks <= 10. But when my mobile wakes up again, the search deck button disappears. I am not understanding why its happening.

2022-04-07 16:57 UTC, mikehardy commented
> Okay, when the collections are loaded then only I can get the decks count?

Sorry for the delay! Until collections are loaded we cannot know *anything* about the user's data, so without collection loaded, we do not know decks count

2022-04-10 10:17 UTC, islam-yousry commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> @Akshay0701 @mikehardy I just debugged, whenever I press the sync button, in onCreateOptionsMenu the colIsOpen() function is returning false. And as we are implemented visibility condition inside the if else block, the block is not being executed.

I approve that happens. onCreateOptionsMenu method is called before the synchronization process is done which is executed using the async task. to solve the issue we need to make sure that the synchronization dialog finishes after the synchronization is done or change the visibility when recycle data view is updated.

clarifying what's actually happened is mCollection.getDb() returns null when is colIsOpen() function is called which skip the condition after that the value changed to by not null from the backend synchronization process.

2022-04-12 15:33 UTC, winstoncooke commented
Left a comment in #10445 about how after synchronization, I'm having the opposite problem where all action bar items (i.e. Search, Sync, and the 3 dot menu) disappear.

2022-06-25 14:37 UTC, closed without merging