Enable RedundantNamespace Lint
ankidroid/Anki-Android pull request #10485
Opened 2022-03-11 18:09 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description

Enable RedundantNamespace Lint

## Fixes
Fixes #10480 
## Approach
 issue id="RedundantNamespace" severity="ignore" 
Change ignore to fatal
fix the issues

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-03-11 18:16 UTC, david-allison requested changes
Thanks!! Looks good, a few questions

2022-03-11 18:16 UTC, david-allison commented on .idea/codeStyles/Project.xml
> -      <option name="PACKAGES_TO_USE_STAR_IMPORTS">
This shouldn't be changed

2022-03-11 18:16 UTC, david-allison commented on .idea/codeStyles/Project.xml
> +      <option name="CODE_STYLE_DEFAULTS" value="KOTLIN_OFFICIAL" />
same

2022-03-11 18:16 UTC, david-allison commented on lint-release.xml
> +<?xml version="1.0" encoding="UTF-8"?><!-- INFORMATION ABOUT USAGE
did this need to change? it doesn't seem relevant

2022-03-11 18:16 UTC, david-allison commented on lint-release.xml
> +    <issue id="RedundantNamespace" severity="fatal" />
Awesome!

2022-03-11 18:39 UTC, Prince-kushwaha commented on .idea/codeStyles/Project.xml
> -      <option name="PACKAGES_TO_USE_STAR_IMPORTS">
sorry it done by mistake

2022-03-11 18:40 UTC, Prince-kushwaha commented on .idea/codeStyles/Project.xml
> +      <option name="CODE_STYLE_DEFAULTS" value="KOTLIN_OFFICIAL" />
it done by mistake i undo the changes

2022-03-11 18:41 UTC, Prince-kushwaha commented on lint-release.xml
> +<?xml version="1.0" encoding="UTF-8"?><!-- INFORMATION ABOUT USAGE
it done by mistake i undo the changes

2022-03-11 22:27 UTC, david-allison requested changes
One minor change: `<?xml version="1.0" encoding="UTF-8"?><!-- INFORMATION ABOUT USAGE`

Rest is fantastic

2022-03-12 03:32 UTC, david-allison approved these changes
Looks great, thanks!

2022-03-12 09:03 UTC, Akshay0701 approved these changes
LGTM

2022-03-13 22:40 UTC, mikehardy commented
took a conflict from a related change - lots of lint additions right now so that is a hot spot on the file, probably just need to move it into place again, but without losing the other lint rule change to fatal of course

2022-03-14 10:54 UTC, Prince-kushwaha commented
@ShridharGoel i do not understand what you want to say?

2022-03-14 11:10 UTC, ShridharGoel commented
https://www.git-tower.com/learn/git/faq/git-squash
https://www.baeldung.com/ops/git-squash-commits

2022-03-14 14:57 UTC, mikehardy approved these changes
The changes, when looked at as a single unit, are good - thank you!
We can squash merge these, I'm okay with that
However, when you say "no" to a request that is related to source code management, you must realize that the actual use of the source code tools (git, and learning how to do rebases and squashes in git) is a very very powerful area of knowledge, and it's really important when interacting with large open source projects since reviewer time is really limited. Having clean commit histories makes review more efficient, so this is an area of programming I strongly encourage you to play around with - make a branch, make a few commits on it that are just to play with (simple text changes) and get used to running `git show -p HEAD~2` or similar, running `git rebase -i HEAD~4` (or similar) and playing with moving the commits around, squashing them, dropping, rewording etc, and force-pushing to your branch to see what happens. Then you'll be a :mage: - definitely worth it

2022-03-14 15:04 UTC, mikehardy commented
Now this one took a conflict - but it's actually because we have merged another of your PRs (congratulations :-) ) - this is now the *perfect* opportunity to play with git rebase! Take the time, it's worth it

First, you will want to squash this all down to one commit:
`git rebase -i HEAD~4` - and then you will have an editor with the 4 commits, leave the first alone and change the last 3 to "squash" instead of "pick". Then edit the commit message and now you will have one commit with the new message.

Then do a `git fetch upstream` in order to get your local system up to date with upstream, and now do `git rebase upstream main`. You will have a conflict in lint.xml. Resolve it by re-applying your change, do a `git add -A` to tell git rebase you've fixed things, then `git rebase --continue`

Then `git push origin +enable-RedundantNamespace-lint` to push the changes back out to your fork on github and poof, you've done it.

At any point in the rebase you can say `git rebase --abort` to rewind to just your new squashed commit and try again fresh.

2022-03-15 03:40 UTC, Prince-kushwaha commented
@mikehardy i made so many commit in this pull request and i do wrong squash commit can  i made another separate  pull request for this issue   and close this pull request

2022-03-15 03:41 UTC, Prince-kushwaha commented
@mikehardy thank you for guide me

2022-03-15 11:46 UTC, Prince-kushwaha commented
@mikehardy can i create another PR for this and close this pull request ?

2022-03-15 12:10 UTC, mikehardy commented
No, power through it. Learn git. Learn how to force push your branch on GitHub to clean it. It's an important skill for contribution to this project

2022-03-17 04:41 UTC, closed without merging