Enabled lint check "ObsoleteLayoutParam"
ankidroid/Anki-Android pull request #10498
Opened 2022-03-12 08:21 UTC by anamansari062

## Pull Request template

## Purpose / Description
Enabled lint check for "ObsoleteLayouParam", changed "ignore" to "fatal" and took the line above.

## Fixes
Fixes  #10482 

## How Has This Been Tested?

Ran ./gradlw lint and resolved errros in activity_drawing.xml

2022-03-12 08:21 UTC, anamansari062 commented
@david-allison Please Check.

2022-03-12 09:29 UTC, Akshay0701 requested changes
@anamansari062 Thanks for your contributions!

I just have one question for changes you made on the drawing XML file, the rest looks good.

2022-03-12 09:29 UTC, Akshay0701 commented on AnkiDroid/src/main/res/layout/activity_drawing.xml
> -        android:layout_below="@id/whiteboard_editor"
@anamansari062 you changed the alignment of UI here, any specific reason for these changes?

2022-03-14 17:00 UTC, anamansari062 commented
@Akshay0701 @david-allison  do i need to any more changes?

2022-03-14 17:29 UTC, Akshay0701 commented on AnkiDroid/src/main/res/layout/activity_drawing.xml
> -        android:layout_below="@id/whiteboard_editor"
revert this changes

2022-03-14 18:20 UTC, david-allison requested changes
Did you run `gradlew lint`? It should have listed changes to make.

2022-03-14 18:23 UTC, anamansari062 commented
@david-allison 
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/85510030/158236480-a544a341-b0cf-4d0a-ac15-fcbedeb8917f.png">
It requested the same changes i did in earlier commit, but reverted in the new one.

2022-03-14 18:47 UTC, anamansari062 commented
@david-allison Can you tell me the steps to go to drawing activity, I am new to the code base thatswhy.

2022-03-15 05:03 UTC, anamansari062 commented
# Ran gradlew lint and got no errors
<img width="1792" alt="Screenshot 2022-03-15 at 12 01 22 AM" src="https://user-images.githubusercontent.com/85510030/158308663-51de4218-8b63-4547-bd61-50740a9afaa2.png">

# Also the alignment is proper in drawing activity

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/85510030/158309965-3d2d7448-5b60-41b2-b9b1-2b80f7fb0b6f.png">

2022-03-15 05:03 UTC, anamansari062 commented
@david-allison Can i commit the changes now?

2022-03-15 16:14 UTC, david-allison approved these changes
As long as this has been tested in an emulator, I'm happy. Thanks!!!!

2022-03-15 16:17 UTC, mikehardy approved these changes
Very nice! Thanks for this @anamansari062

2022-03-15 17:03 UTC, merged

2022-04-22 14:34 UTC, mikehardy commented
Hi there! MARCH OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [March 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-03-01..2022-03-31)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of March.

Please note that GSoC contributions are okay for this process. Our philosophy is that our users have donated to AnkiDroid for *all* contributions. The only PRs that will not go through the OpenCollective process are ones *directly* related to a GSoC project from a selected participant, since those receive a stipend from GSoC itself.

Please understand that this means the monthly budget we have for payments might be stretched a bit and the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!