Fixed with Enable Lint:DrawAllocation #10488
ankidroid/Anki-Android pull request #10499
Opened 2022-03-12 11:52 UTC by Bhawna1203

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-03-12 11:59 UTC, Bhawna1203 commented
Please check @david-allison .
Thanks

2022-03-12 12:01 UTC, viciousAegis commented
Hey! It would be great if you could fill up the Pull Request template, and especially add a link to the issue that this is fixing under the `Fixes` heading.

Apart from that, I see that the commit changes the `README` file? 
Please correct me if I'm wrong, but from my understanding of the issue I don't think changes should me made to this file.

2022-03-12 12:04 UTC, viciousAegis commented on lint-release.xml
> +    <issue id="DrawAllocation" severity="fatal" />
Since you've changed the severity to `fatal`, it would be great if you moved the entire statement a few lines above this big block of `ignore` issues along with the other `fatal` issues. You can place it along with those issues as you see fit.

2022-03-12 12:21 UTC, viciousAegis commented on lint-release.xml
> +    <issue id="DrawAllocation" severity="fatal" />
Since you've changed the severity to `fatal`, it would be great if you moved the entire statement a few lines above this big block of `ignore` issues along with the other `fatal` issues. You can place it along with those issues as you see fit.  see https://github.com/ankidroid/Anki-Android/issues/10488#issue-1166759351:  

> Move the line in the XML to be somewhere near the top of the file (before the large block of ignore elements.
> The exact position is up to you, but if there's no comment associated with the check, a large nearly alphabetical block of fatal warnings seems sensible

2022-03-12 14:31 UTC, david-allison requested changes
Something is wrong with `gradlew lint`. Try it again. It should have been fatal

```
> Task :AnkiDroid:lintAmazonDebug FAILED
C:\GitHub\Anki-Android-Git\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\stats\ChartView.kt:52: Error: Avoid object allocations during draw/layout operations (preallocate and reuse instead) [DrawAllocation]
            val paint = Paint(Paint.LINEAR_TEXT_FLAG)
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\GitHub\Anki-Android-Git\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\stats\ChartView.kt:55: Error: Avoid object allocations during draw/layout operations (preallocate and reuse instead) [DrawAllocation]
            val g = GraphicsWrap(canvas, paint)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\GitHub\Anki-Android-Git\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\stats\ChartView.kt:56: Error: Avoid object allocations during draw/layout operations (preallocate and reuse instead) [DrawAllocation]
            val field = Rect()
                        ~~~~~~
3 errors, 0 warnings


```

2022-03-12 14:31 UTC, david-allison commented on README.md
> +<p>
this file shouldn't have been changed

2022-03-12 16:19 UTC, Bhawna1203 commented on lint-release.xml
> +    <issue id="DrawAllocation" severity="fatal" />
Thanks for helping me i will again create pull request tomorrow with fixing this issue.

2022-03-12 16:21 UTC, Bhawna1203 commented on README.md
> +<p>
I did this by mistake .I will change this tomorrow sir.Thanks for helping me sir.

2022-03-12 16:23 UTC, viciousAegis commented on lint-release.xml
> +    <issue id="DrawAllocation" severity="fatal" />
No, you don't have to make another pull request, and don't close this one. You can just add these in another commit, and push (possibly force-push) them to the branch you have created. If you don't have much knowledge about these git commands, don't worry, I was there not even a month ago, but some googling can help you here. 

TLDR: Don't make another PR, add commits in this one only.

2022-03-12 16:28 UTC, Bhawna1203 commented on lint-release.xml
> +    <issue id="DrawAllocation" severity="fatal" />
Okk sir .Thanks for helping .Actually this one is my first big codebase code so i am facing issues.

2022-03-12 16:43 UTC, Bhawna1203 commented on README.md
> +<p>
Actually here the paragraph tag is not opened before closing so it gives error so i think to fix it. 
Sorry for that sir

2022-03-12 17:15 UTC, Bhawna1203 commented on lint-release.xml
> +    <issue id="DrawAllocation" severity="fatal" />
Now please check i did some changes .If issue again persist then let me know

2022-03-12 18:26 UTC, viciousAegis commented on lint-release.xml
> +    <issue id="DrawAllocation" severity="fatal" />
@Bhawna1203 I can only see one commit. Did you push the commits to your remote branch?

2022-03-13 03:09 UTC, Bhawna1203 commented on lint-release.xml
> +    <issue id="DrawAllocation" severity="fatal" />
Yess

2022-03-13 14:14 UTC, david-allison commented
Still waiting for feedback to be addressed

2022-03-14 01:48 UTC, Bhawna1203 commented
@david-allison sir, Please check i do some commit .
 If it works then let me know Or need to change something then again please let me know

2022-03-14 14:50 UTC, mikehardy requested changes
still needs the changes requested to be visible on github.com so we can see them

2022-03-14 14:50 UTC, mikehardy commented on README.md
> +<p>
I am looking at all commits in this file. I still see this change to README in here. README may indeed have problems but they are unrelated to enabling a lint check, thus no changes to README should be mixed in to this PR.
This change must be removed from the PR

2022-03-14 14:50 UTC, mikehardy commented on lint-release.xml
> +    <issue id="DrawAllocation" severity="fatal" />
I am not sure what changes exist on your local system, but they have not been pushed to github.
This change from ignore to fatal is still buried in the ignore block of checks and should be moved up per previous comments

2022-03-15 13:18 UTC, Bhawna1203 commented
Okk @mikehardy sir i will do the changes and let you know when i completed the same.Thanks for helping and continuous support.

2022-03-17 13:04 UTC, Bhawna1203 commented
@david-allison sir after completing all the changes as instructed in the issue page .I run gradlew-lint and getting some warning .Could i commit these changes or need to change something?
![Screenshot from 2022-03-17 18-29-36](https://user-images.githubusercontent.com/81790585/158814058-dffdf4de-e8bd-4039-a534-7547581e8146.png)

2022-03-17 15:35 UTC, david-allison commented
Those are fine

2022-03-18 10:38 UTC, Bhawna1203 commented
So @david-allison sir ,Can i now commits the changes for review

2022-03-18 14:03 UTC, david-allison commented
No need to ask! I can't review what I can't see

2022-03-19 09:50 UTC, Bhawna1203 commented
Sir, After solving  gradlew-lint issue . Sir i am getting this issue. Do i need to solve these issues to . 
Could you please help there as a teacher or mentor.


![Screenshot from 2022-03-19 15-17-08](https://user-images.githubusercontent.com/81790585/159116327-baa0fd26-5697-4b92-bc43-7b1e49fa6629.png)

2022-03-19 11:00 UTC, david-allison commented
That doesn't look related. 

If you were able to build AnkiDroid before, it's probably a bug that you introduced, and need to fix

If you weren't, you should focus on getting AnkiDroid to build before taking on issues.

2022-03-19 14:12 UTC, Bhawna1203 commented
@david-allison sir Sorry for inconvenience. I solved this issue earlier. But due to updation in Ubantu today when i open this project again in my Android Studio. It gives me issue that i shared above. I tried to solve issue but i am unable to solve about 6 hours of constant efforts.
Then again i cloned the project and solved the issue  https://github.com/ankidroid/Anki-Android/issues/10488 again  and its solved. so i need to put new PR, i tested with gradlew lint and also it succeed .I added the screenshot here too.I am embarrassed for this convenience Hope you understand.  
So can I push that new cloned version ? and add new PR?

![Screenshot from 2022-03-19 17-40-24](https://user-images.githubusercontent.com/81790585/159124474-ae2028f4-3d04-4b35-816e-dc655a7fdf8b.png)
![Screenshot from 2022-03-19 17-26-21](https://user-images.githubusercontent.com/81790585/159124493-98a748b5-ed66-4f4f-a34c-bb96ec639252.png)

2022-03-19 17:44 UTC, david-allison commented
Use this branch: `[Bhawna1203:bhawna-changes](https://github.com/Bhawna1203/Anki-Android/tree/bhawna-changes)`. Don't make a new PR.

There's no time pressure. First contributions typically take a lot longer than expected, but momentum builds up. There's no need to feel embarrassed, and no need to say how long something took, unless you want to share it. 

I've definitely had pull requests that are only a few lines that took hours or days to write. It's fine.

2022-03-20 10:38 UTC, Bhawna1203 commented
@david-allison sir check i am done with the changes. Also i am not getting any issue on gradlew lint 
![Screenshot from 2022-03-20 15-54-22](https://user-images.githubusercontent.com/81790585/159158415-c6fd1101-4596-4383-bd6e-4aec2951b904.png)

2022-03-22 08:06 UTC, david-allison requested changes

2022-03-22 08:06 UTC, david-allison commented on README.md
> +
Please revert all changes to this file

2022-03-22 08:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartView.kt
> +    @SuppressLint("DrawAllocation")
We should be fixing the errors, not ignoring them. They're actual problems

2022-03-22 08:16 UTC, Bhawna1203 commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartView.kt
> +    @SuppressLint("DrawAllocation")
Okk sir

2022-03-22 08:17 UTC, Bhawna1203 commented on README.md
> +
okkk sir

2022-03-23 11:36 UTC, mikehardy commented
I'm going to change this to draft so it doesn't show up in the scans I do for actionable PRs yet - it's easy to toggle it back and forth though - just a button on Github's Web UI to set it back to ready when it's ready

2022-03-23 13:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartView.kt
> +    @SuppressLint("DrawAllocation")
> DrawAllocation:
> 
> Memory allocations within drawing code
> 
> Explanation:
> 
> Looks for memory allocations within drawing code. You should avoid allocating objects during a drawing or layout operation. These are called frequently, so a smooth UI can be interrupted by garbage collection pauses caused by the object allocations.
> 
> The way this is generally handled is to allocate the needed objects up front and to reuse them for each drawing operation.
> 
> Some methods allocate memory on your behalf (such as Bitmap.create), and these should be handled in the same way.

Additional information: https://stackoverflow.com/a/27719578/

2022-06-23 19:36 UTC, closed without merging