Enabled UselessParent Lint
ankidroid/Anki-Android pull request #10490
Opened 2022-03-11 20:28 UTC by ken1000minus7

## Pull Request template

## Purpose / Description
Enabling the UselessParent lint

## Fixes
Fixes #10479 

## Approach
1. Changed the severity value of the UselessParent lint from `ignore` to `fatal`
2. Fixed the following problems appearing on running `gradlew lint`
![image](https://user-images.githubusercontent.com/78747188/157957011-4963af84-2f16-4ff1-bc37-9d20a61e603e.png)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-03-11 20:36 UTC, david-allison reviewed
Additional note: aim to rebase onto `main` rather than merging when bringing changes back into a branch

2022-03-11 20:36 UTC, david-allison commented on AnkiDroid/src/main/res/layout/card_info.xml
> +                tools:ignore="UselessParent">
Why are we ignoring these rather than fixing them?

2022-03-11 20:40 UTC, ken1000minus7 commented on AnkiDroid/src/main/res/layout/card_info.xml
> +                tools:ignore="UselessParent">
Removing this parent was causing problems with the ui so I think it shouldn't be removed 🤔

2022-03-11 20:41 UTC, ken1000minus7 commented
> Additional note: aim to rebase onto `main` rather than merging when bringing changes back into a branch

Sure, will take care from next time 😄

2022-03-11 20:45 UTC, david-allison commented on AnkiDroid/src/main/res/layout/card_info.xml
> +                tools:ignore="UselessParent">
Isn't the lint check telling us that this shouldn't be a problem?

2022-03-11 20:51 UTC, ken1000minus7 commented on AnkiDroid/src/main/res/layout/card_info.xml
> +                tools:ignore="UselessParent">
Well I did try and the elements of the table row ended up appearing vertically instead of horizontally 😓 
![image](https://user-images.githubusercontent.com/78747188/157962414-943331a3-ef0d-4ff9-98db-da42099bb1c5.png)

2022-03-11 21:01 UTC, david-allison commented on AnkiDroid/src/main/res/layout/card_info.xml
> +                tools:ignore="UselessParent">
That one's reasonable. Add a comment that rows are added dynamically, so it needs to exist

 What about the other two?

2022-03-11 21:01 UTC, ken1000minus7 commented on AnkiDroid/src/main/res/layout/card_info.xml
> +                tools:ignore="UselessParent">
I can remove them if it's required, I was just worried about messing up the ui so avoided removing them, sorry for that 😓

2022-03-11 21:06 UTC, david-allison commented on AnkiDroid/src/main/res/layout/card_info.xml
> +                tools:ignore="UselessParent">
Not a problem at all! The point of lint is to flag up potential errors. 

If we ignore all the errors without checking them, then it's not worth having the check in the first place.

2022-03-11 21:10 UTC, ken1000minus7 commented on AnkiDroid/src/main/res/layout/card_info.xml
> +                tools:ignore="UselessParent">
Yeah 😅 
Among the other two, the TableLayout has multiple TableRows under it, so I guess that shouldn't be removed either🤔 
Maybe that RelativeLayout can be removed.

2022-03-11 21:13 UTC, david-allison commented on AnkiDroid/src/main/res/layout/card_info.xml
> +                tools:ignore="UselessParent">
Did you try the other `TableLayout`? The problem with this one is that we're dynamically adding rows: 

https://github.com/ankidroid/Anki-Android/blob/6cbe2cb49941fbbb39725fee045532118908939c/AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.java#L126-L139

The others might be fine to remove.

2022-03-11 21:33 UTC, ken1000minus7 commented on AnkiDroid/src/main/res/layout/card_info.xml
> +                tools:ignore="UselessParent">
The other TabLayout has TableRows under it and so removing it causes them to not appear. I think instead of removing the TableLayout, we can remove the LinearLayout above it as it seems to serve no purpose. 🤔 
https://github.com/ankidroid/Anki-Android/blob/6cbe2cb49941fbbb39725fee045532118908939c/AnkiDroid/src/main/res/layout/studyoptions_fragment.xml#L68-L171

2022-03-11 21:34 UTC, david-allison commented on AnkiDroid/src/main/res/layout/card_info.xml
> +                tools:ignore="UselessParent">
Sounds good to me!

2022-03-12 09:07 UTC, Akshay0701 requested changes
```
> Task :AnkiDroid:compilePlayDebugKotlin
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt: (213, 62): Unresolved reference: studyoptions_deckinformation

FAILURE: Build failed with an exception.
```

2022-03-12 10:30 UTC, ken1000minus7 commented
Made changes, I hope there won't be any more problems 😅

2022-03-12 11:45 UTC, david-allison commented
Did you test these changes on your device?

2022-03-12 16:04 UTC, ken1000minus7 commented
Yeah, everything seems to be working fine, these are the layouts that were changed
<img src="https://user-images.githubusercontent.com/78747188/158025368-d7119a40-0191-4db4-a690-90c7c0f6211a.png" height=500> <img src="https://user-images.githubusercontent.com/78747188/158025379-88cf8d7f-736b-40e6-9ecf-4f1349bef995.png" height=500>

2022-03-16 19:45 UTC, david-allison approved these changes
LGTM.

Maintainers: squash merge

2022-03-18 21:59 UTC, mikehardy approved these changes
I checked it on a Pixel C emulator in landscape to make sure we hadn't wrecked the tablet layout (it's happened a few times!), it looks perfect. Thanks!

2022-03-18 21:59 UTC, merged

2022-04-22 14:34 UTC, mikehardy commented
Hi there! MARCH OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [March 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-03-01..2022-03-31)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of March.

Please note that GSoC contributions are okay for this process. Our philosophy is that our users have donated to AnkiDroid for *all* contributions. The only PRs that will not go through the OpenCollective process are ones *directly* related to a GSoC project from a selected participant, since those receive a stipend from GSoC itself.

Please understand that this means the monthly budget we have for payments might be stretched a bit and the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!