added prettier check
ankidroid/Anki-Android pull request #10500
Opened 2022-03-12 13:09 UTC by tharun634

## Purpose / Description
Added prettier lint check feature

## Fixes
Fixes #10475

## Approach
Now, with every PR, prettier check will be run against the codebase

## How Has This Been Tested?
Ran the following commands from the root directory
- `npx prettier --check AnkiDroid/**/*.js`
- `npx prettier --write AnkiDroid/**/*.js`

2022-03-12 13:15 UTC, david-allison requested changes
We want to exclude `jquery` and `mathjax`

2022-03-12 13:28 UTC, ShridharGoel commented
It's better to run prettier only for the changed files instead of running it on all the files.

2022-03-12 13:39 UTC, david-allison commented
I'm not knowledgeable here, this isn't a request for a change

I'll defer to @mikehardy for JS knowledge, but personally:

* doublequotes and 4 spaces per tab

2022-03-12 14:05 UTC, ShridharGoel commented on .github/workflows/lint.yml
> +          # This part is also where you can pass other options, for example:
This comment can be removed.

2022-03-12 14:06 UTC, ShridharGoel requested changes

2022-03-12 14:06 UTC, ShridharGoel commented on .github/workflows/lint.yml
> +          fetch-depth: 0
This seems to be an extra change. It is causing the lint CI check to fail.

2022-03-12 14:07 UTC, tharun634 commented on .github/workflows/lint.yml
> +          fetch-depth: 0
I think it's the `ref`, I removed the ref now. Let's wait for another workflow run.

2022-03-12 14:08 UTC, ShridharGoel commented on .github/workflows/lint.yml
> +          fetch-depth: 0
You have updated it, so it should be fine now. Is `fetch-depth: 0` still required?

2022-03-12 14:09 UTC, ShridharGoel commented on .github/workflows/lint.yml
> +          fetch-depth: 0
Is `fetch-depth: 0` still required?

2022-03-12 14:10 UTC, tharun634 commented on .github/workflows/lint.yml
> +          fetch-depth: 0
from the documentation of the action in use: https://github.com/creyD/prettier_action

![image](https://user-images.githubusercontent.com/53267275/158021227-3238bedd-d2fb-43a2-a603-0aeca6ff1e09.png)

2022-03-12 14:15 UTC, ShridharGoel commented
Can you try adding a test commit with wrongly formatted code to check what happens with the CI check in that case? You can later remove the commit.

2022-03-12 14:26 UTC, tharun634 commented
> Can you try adding a test commit with wrongly formatted code to check what happens with the CI check in that case? You can later remove the commit.

Working as intended
https://github.com/ankidroid/Anki-Android/pull/10500/checks#step:11:36

2022-03-12 14:27 UTC, ShridharGoel commented
Looks good. Can you consider adding a pre-commit hook which would only run when there is a change in a JS file?

2022-03-12 14:28 UTC, ShridharGoel commented
Pre-commit hook file: https://github.com/ankidroid/Anki-Android/blob/main/pre-commit

2022-03-12 14:30 UTC, tharun634 commented
The hook must check for prettier as well? just like the workflow?

2022-03-12 14:31 UTC, ShridharGoel commented
> The hook must check for prettier as well? just like the workflow?

Yes. You can check how it's being done for Ktlint.

2022-03-13 02:02 UTC, david-allison commented on pre-commit
> +echo "$CHANGED_JS_FILES" | xargs npx prettier --ignore-unknown --check
This adds a developer dependency on node. 

I'm fairly strongly opposed to this as it adds friction to our new user onboarding process. 

Right now the process is pretty much as simple as it could be: 

* Clone
* Open in Android Studio
* Wait an age for dependencies to be downloaded
* Run

Again, wait for @mikehardy to weigh in, this is not my area of expertise, but I'd much prefer this to only execute if `node` and `prettier` are available on the system.

In the CI failure, we can point towards installing the dependencies, but if the user can't commit, we don't get CI or the PR to tell them what they did incorrectly (if anything).

2022-03-13 04:39 UTC, ShridharGoel commented on pre-commit
> +    echo "npx could not be found, but it is required for pre-commit Prettier check."
We can also include the message that the check is being skipped so that the developer knows that this is not an error.

2022-03-13 04:43 UTC, tharun634 commented on pre-commit
> +    echo "npx could not be found, but it is required for pre-commit Prettier check."
If there is a change in a Javascript file, and `npx` could not be found (in order to run prettier). Shouldn't it be treated as an error?

NOTE: The `npx` check is done if and only if there are any changed Javascript files

2022-03-13 05:03 UTC, ShridharGoel commented on pre-commit
> +    echo "npx could not be found, but it is required for pre-commit Prettier check."
Not really because we'll be allowing the commit to proceed even if `npx` is not present. That's what @david-allison meant that the commit should proceed even if `npx` is not present.

2022-03-13 05:03 UTC, ShridharGoel commented on pre-commit
> +    exit 1
This should be `exit 0`.

2022-03-13 05:04 UTC, ShridharGoel commented on pre-commit
> +    echo "npx could not be found, but it is required for pre-commit Prettier check."
@david-allison Can you confirm this?

2022-03-13 05:11 UTC, tharun634 commented on pre-commit
> +    echo "npx could not be found, but it is required for pre-commit Prettier check."
Right, I misunderstood

2022-03-13 05:51 UTC, ShridharGoel commented
The prettier check doesn't seem to be running locally even when there are changes in `card.js`. Did you try it locally?

2022-03-13 06:43 UTC, tharun634 commented
> The prettier check doesn't seem to be running locally even when there are changes in `card.js`. Did you try it locally?

I've fixed it now

2022-03-13 08:25 UTC, ShridharGoel approved these changes

2022-03-13 08:32 UTC, ShridharGoel commented
> > The prettier check doesn't seem to be running locally even when there are changes in `card.js`. Did you try it locally?
> 
> I've fixed it now

The previous code would have also worked. Noticed later that the pre-commit file wasn't updated in `.git/hooks` in my system because of which prettier check wasn't running. It's working fine now. Anyways, the updated code is better structured, so we can keep that.

2022-03-13 08:38 UTC, ShridharGoel commented
Suggestion: Use `--write` instead of `--check` to autoformat the files.

2022-03-13 08:55 UTC, ShridharGoel approved these changes

2022-03-14 15:25 UTC, mikehardy requested changes
I love this! Our javascript skills / integration will be taking a large step forward this - professionalism actually does start with consistent formatting and tool support for automated verification of things (starting with spacing...)
Thank you!

Mostly just curious what you think about cleaning the whole JS right now (via prettier) then just checking the whole thing each time.

2022-03-14 15:25 UTC, mikehardy commented on .github/workflows/lint.yml
> +          fetch-depth: 0
Out of curiosity - it appears that you have fixed all the prettier issues that would be detected so really, we could turn off "only_changed" for the prettier action, then we could leave fetch-depth alone? I say that because sometimes changes to fetch-depth have unexpected consequences, so:

1- less change is better (not changing fetch-depth)
2- and full verification (not just last commit) is arguably more thorough anyway

What do you think?

2022-03-14 15:25 UTC, mikehardy commented on pre-commit
> +    CHANGED_JS_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.js/ { print $2 }')"
why not just run prettier every time on all files, and have all files start clean from now?
Over the whole codebase of kotlin etc, that might be onerous, but with prettier and our current (tiny) javascript codebase this seems it wouldn't be a problem? then the whole check here gets much simpler too

2022-03-14 15:27 UTC, mikehardy commented
Oh - and to be clear about actual formatting choices - I've been doing this long enough that these days I almost don't care about any formatting decision *as long as it is enforced by prettier* :-). So I don't really care about contents of .prettierrc. Using Visual Studio Code (which you should do, if you code javascript...) with the prettier extension, it's always just auto-formatting all the time anyway, so formatting melts away and no one should even think about it.

2022-03-14 18:25 UTC, david-allison reviewed
one request to see how things look.

No more comments after that, happy if others are

2022-03-14 18:33 UTC, david-allison approved these changes
Love this. Needs a squash+merge from maintainers

2022-03-14 20:07 UTC, mikehardy approved these changes
Yeah, this looks great, thank you! Not many people go into the .github/workflows directory, neat (to me) to see others in there

For anyone else that comes in here later curious about our prettier settings: if something about the formatting really bothers you, make a case for your change and make a PR that implements it via a change to .prettierrc and does the reformatting. Formats are a community decision and they don't have to be unchanging, they just have to be consistent + enforced.

2022-03-14 20:09 UTC, merged

2022-03-14 20:11 UTC, david-allison commented
Ditto. I like this because it's consistent with the style of code that already existed. Now we've committed this, we **only** get the changes from the config change, so I'm more than open to see changes stemming from changing the config after discussion.