Kotlin  CleanUp
ankidroid/Anki-Android pull request #10546
Opened 2022-03-16 10:04 UTC by jals413

Kotlin Cleanup: integerListToArray #10530

## Fixes
Replaced the method integerListToArray to Kotlin method .toIntArray( ) , also removed the method integerListtoArray

2022-03-16 10:16 UTC, ShridharGoel requested changes

2022-03-16 10:16 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
> +            return ContextMenuHelper.itemIds.toIntArray()
This needs to be fixed.

2022-03-16 10:35 UTC, jals413 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
> +            return ContextMenuHelper.itemIds.toIntArray()
okay , trying

2022-03-17 05:32 UTC, jals413 commented
I did run it on my device , it was working fine

2022-03-18 08:46 UTC, jals413 commented
ok I will fix it , need some time

2022-04-02 23:32 UTC, mikehardy commented
superceded by #10664

2022-04-02 23:32 UTC, closed without merging