[Kotlin Migration] BasicAudioRecordingFieldController
ankidroid/Anki-Android pull request #10553
Opened 2022-03-16 17:27 UTC by kilitr

## Purpose / Description
Migrate BasicAudioRecordingFieldController.java to kotlin

## Fixes
/

## Approach
As explained in the kotlin migration manual.

## How Has This Been Tested?

local testing, fixing one unit test was necessary however (ce2ee44075b7851119de004bb712f636b3a894d8).

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-03-16 17:45 UTC, david-allison requested changes
Needs two commits in a migration PR, as listed in the docs: https://github.com/ankidroid/Anki-Android/blob/main/docs/kotlin-migration.md

2022-03-16 17:47 UTC, david-allison reviewed
Conversion looks good. Added a few suggestions for `KotlinCleanup`

2022-03-16 17:55 UTC, kilitr commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt
> +        mAudioView = createRecorderInstance(
how about i don't add the Annotation but instead just clean this already?

2022-03-16 17:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt
> +        mAudioView = createRecorderInstance(
Sure! In general we want to aim for minimal changes in a migration PR - separate out the machine-produced changes from the human-produced follow up, as that reduces the likelihood of bugs.

In this case, there's 0 risk.

2022-03-17 17:42 UTC, Akshay0701 approved these changes
LGTM, with one comment

2022-03-17 17:42 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt
> +                textView.text = field!!.text
```suggestion
                textView.text = field?.text ?: ""
```

just a suggestion: I think it would be good if we use here an elvis, so that in any case we got null our app will not through the NPE.

2022-03-17 22:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt
> +                textView.text = field!!.text
We could do with a `KotlinCleanup` here - I feel `getInitialField` shouldn't return a nullable

2022-03-18 11:59 UTC, kilitr commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt
> +                textView.text = field!!.text
> just a suggestion: I think it would be good if we use here an elvis, so that in any case we got null our app will not through the NPE.

Good one, i replaced `!!` by elvis.

> We could do with a `KotlinCleanup` here - I feel `getInitialField` shouldn't return a nullable

added `@KotlinCleanup` to the interface of `getInitialField`

2022-03-18 14:08 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt
> +        context.apply {
Typically we want to avoid additional refactorings in the migration commit (besides adding `@KotlinCleanup` and fixing bugs & compile errors) - 

This ensures that we can get a good 1:1 comparison between the Java and the Kotlin: the process itself can produce bugs. 

I'll leave this as 'pending merge': it's a minor change and looks correct.

2022-03-18 22:04 UTC, merged

2022-04-22 14:33 UTC, mikehardy commented
Hi there! MARCH OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [March 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-03-01..2022-03-31)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of March.

Please note that GSoC contributions are okay for this process. Our philosophy is that our users have donated to AnkiDroid for *all* contributions. The only PRs that will not go through the OpenCollective process are ones *directly* related to a GSoC project from a selected participant, since those receive a stipend from GSoC itself.

Please understand that this means the monthly budget we have for payments might be stretched a bit and the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!