Kotlin conversion preferences test
ankidroid/Anki-Android pull request #10564
Opened 2022-03-17 09:35 UTC by divyansh-dxn

## Purpose / Description
Kotlin conversion : PreferencesTest.java -> PreferencesTest.kt

## Approach
1. Convert JAVA file to Kotlin
2. Do some small changes manually

## How Has This Been Tested?
Runs test as expected

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-03-17 14:51 UTC, david-allison reviewed
Looks good - small requests

2022-03-17 14:51 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/PreferencesTest.kt
> +    val instance: Preferences
`@KotlinCleanup("use scope function")`

2022-03-18 13:37 UTC, david-allison requested changes
There needs to be 2 commits on a Kotlin Migration. Please squash the last two

Some feedback hasn't been addressed

2022-03-18 14:29 UTC, divyansh-dxn commented
> 

I didn't get the using scope function. Use scope function for what?
Did you mean ?
```kotlin
     val instance: Preferences
            get() = Preferences().apply { this.attachBaseContext(targetContext) }

2022-03-18 14:31 UTC, david-allison commented
> > 
> 
> I didn't get the using scope function. Use scope function for what? Did you mean ?
> 
> ```kotlin
>      val instance: Preferences
>             get() = Preferences().apply { this.attachBaseContext(targetContext) }
> ```

Add a `@KotlinCleanup` annotation for the user who performs the cleanup, to suggest they use a scope function here.

We shouldn't refactor the code in the conversion, as this makes it much harder to understand the history.

2022-03-18 15:10 UTC, divyansh-dxn commented
> 

When I try to add this annotation to the field, it throws an error `This annotation is not applicable to target 'member property without backing field or delegate`. 
It needs to add `AnnotationTarget.PROPERTY` to KotlinCleanup.kt annotation class.
Even this is true for the getter method.
What should I do?

2022-03-18 15:16 UTC, david-allison commented
Rebase your branch onto main: https://github.com/ankidroid/Anki-Android/pull/10544

2022-03-18 20:20 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/PreferencesTest.kt
> +            MatcherAssert.assertThat(getDayOffset(col), Matchers.`is`(i))
This comment is still pending

2022-03-18 20:37 UTC, divyansh-dxn commented on AnkiDroid/src/test/java/com/ichi2/anki/PreferencesTest.kt
> +            MatcherAssert.assertThat(getDayOffset(col), Matchers.`is`(i))
You meant 
```kotlin
import org.hamcrest.MatcherAssert.assertThat
import org.hamcrest.Matchers.equalTo
```
right?

2022-03-18 20:39 UTC, divyansh-dxn commented on AnkiDroid/src/test/java/com/ichi2/anki/PreferencesTest.kt
> +            MatcherAssert.assertThat(getDayOffset(col), Matchers.`is`(i))
It's my first conversion task, that's why not going that smooth  🥲🥲

2022-03-18 20:45 UTC, david-allison approved these changes
Looks great, thanks!

2022-03-18 21:27 UTC, mikehardy approved these changes
Nice!

2022-03-18 21:27 UTC, merged

2022-04-22 14:33 UTC, mikehardy commented
Hi there! MARCH OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [March 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-03-01..2022-03-31)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of March.

Please note that GSoC contributions are okay for this process. Our philosophy is that our users have donated to AnkiDroid for *all* contributions. The only PRs that will not go through the OpenCollective process are ones *directly* related to a GSoC project from a selected participant, since those receive a stipend from GSoC itself.

Please understand that this means the monthly budget we have for payments might be stretched a bit and the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!