startActivityForResult migration to newer API in AbstractFlashCardViewer
ankidroid/Anki-Android pull request #10562
Opened 2022-03-17 07:49 UTC by divyansh-dxn

## Purpose / Description
Removed dependency on deprecated code

## Fixes
Fixes a part of #8602

## Approach
1. Create launchers equivalent to `onActivityResult`
2. Replace use of `startActivityForResult`

## How Has This Been Tested?
Works as expected on Realme 6i and emulator pixel 4 api 27,28 

https://user-images.githubusercontent.com/69595691/158761544-198a10c1-6567-494d-b126-094b0b4d90bf.mp4

https://user-images.githubusercontent.com/69595691/158761557-a1ce6ac4-3471-482c-b7b4-bdc31ec6f888.mp4

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-03-17 07:54 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            }
Android studio auto-formats inserted these extra tabs. should I revert this or it's fine?

2022-03-17 07:54 UTC, divyansh-dxn commented on AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
> +
Didn't knew handling test for this, so commented it. Should I remove completely?

2022-03-17 17:05 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            }
its unnecessary changes, revert it

2022-03-17 17:07 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            }
no need to revert

2022-03-17 17:11 UTC, Akshay0701 requested changes

2022-03-17 17:11 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        if( resultCode == RESULT_OK) {
```suggestion
        if(resultCode == RESULT_OK) {
```

2022-03-17 17:11 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        launchActivityForResultWithAnimation(editCard,mEditCurrentCardLauncher,START);
```suggestion
        launchActivityForResultWithAnimation(editCard, mEditCurrentCardLauncher, START);
```

2022-03-17 17:11 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            launchActivityForResultWithAnimation(intent,mDeckOptionsLauncher,FADE);
```suggestion
            launchActivityForResultWithAnimation(intent, mDeckOptionsLauncher, FADE);
```

2022-03-17 17:11 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +    protected ActivityResultLauncher<Intent> mEditCurrentCardLauncher = getResultLauncher((resultCode,data)->{
```suggestion
    protected ActivityResultLauncher<Intent> mEditCurrentCardLauncher = getResultLauncher((resultCode, data)->{
```

2022-03-17 17:11 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        return registerForActivityResult(new ActivityResultContracts.StartActivityForResult(),result -> {
```suggestion
        return registerForActivityResult(new ActivityResultContracts.StartActivityForResult(), result -> {
```

2022-03-17 17:13 UTC, Akshay0701 commented
just a small code style changes requested, 

i request you to go through the [code-style](https://github.com/ankidroid/Anki-Android/wiki/Code-style) guide

2022-03-17 17:21 UTC, Akshay0701 commented on AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
> +
here you can [startActivityForResult ](https://developer.android.com/reference/android/app/Activity#startActivityForResult(android.content.Intent,%20int)) instead of old onActivityResult

https://stackoverflow.com/a/13060588

2022-03-17 17:28 UTC, divyansh-dxn commented on AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
> +
Cool!

2022-03-17 17:58 UTC, david-allison requested changes
A few minor formatting changes (as the class hasn't yet been moved to Kotlin).

The tests need work so that they pass, or a strong proof of why they were changed, and why that's not a problem

2022-03-17 17:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            callback.onResult(resultCode,data);
```suggestion
            callback.onResult(resultCode, data);
```

2022-03-17 17:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +    protected ActivityResultLauncher<Intent> mEditCurrentCardLauncher = getResultLauncher((resultCode, data)->{
```suggestion
    protected ActivityResultLauncher<Intent> mEditCurrentCardLauncher = getResultLauncher((resultCode, data) -> {
```

2022-03-17 17:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        if(resultCode == RESULT_OK) {
```suggestion
        if (resultCode == RESULT_OK) {
```

2022-03-17 17:58 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
> +        assertThat(nafv.getCorrectTypedAnswer(), is("David")); */
The test needs to either be fixed, or we need to prove that it's not broken and rewrite it.

2022-03-17 17:58 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.java
> +        assertThat("Should be previewing selected card after edit", previewer.getCurrentCardId(), is(cardToPreview.getId())); */
ditto

2022-03-17 17:58 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.java
> +        assertThat("Card content should be updated after editing", previewer.getCardContent(), containsString("Hi")); */
ditto

2022-04-07 17:00 UTC, mikehardy commented
Oh no - while this was waiting, this class moved to Kotlin, the solution needs to be re-applied in Kotlin.
It appeared that the PR was basically ready to go except for some formatting issues, and on kotlin it at least we just use an auto-formatter (ktlint) so that will be easy to fix.
@divyansh-dxn do you still plan to get this merged or should we look for a new dev for it? No trouble either way, I just want to know since the work you've done so far looks really close

2022-04-07 18:49 UTC, mikehardy commented
No problems, life (and college of course) come first - good luck in your studies!

2022-06-25 12:46 UTC, closed without merging