Display instructions in generated translated files
ankidroid/Anki-Android pull request #10566
Opened 2022-03-17 14:19 UTC by Tinkidinki

## Pull Request template

## Purpose / Description
Explained in the title

## Fixes
Fixes issue #10557

## Approach
As described in the issue, the current header has been *replaced* with the instructions. This is because the translated files already contain the license header, so there doesn't seem to be a need for a repeat. 

I also want to confirm that this is okay, or whether the instructions have to be appended to the license information. 

The current file's header has also been modified in two places, to (1) correct the path of the Ankidroid translations zip file, and (2) a variable name in the instructions. 

Would like to confirm that these two changes are okay as well. 

## How Has This Been Tested?
I was able to make some changes to sync_translations.xml and run the Sync Translations workflow to ensure changes are made. 

## Learning (optional, can help others)
I found the blogpost on Github Workflow syntax to be useful: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

## Checklist
_Please, go through these checks before submitting the PR._

- [ v] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ v] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ v] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [v ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-03-17 14:31 UTC, david-allison requested changes
Needs a few small changes. Looks good!

Could you copy the user-readable message that's displayed, as that's easier to review than a long line with `\n`s in it.

2022-03-17 14:31 UTC, david-allison commented on tools/update-localizations.py
> +                line = "<?xml version=\"1.0\" encoding=\"utf-8\"?> \n <!-- \n ~ THIS IS AN AUTOMATICALLY GENERATED FILE. PLEASE DO NOT EDIT THIS FILE. \n ~ 1. If you would like to edit the original x
We shouldn't remove people's copyrights.

When people are here, there are typically two goals:
* Fixing a translation (these instructions are excellent)
* Modify, add or delete strings

For this, we want to guide them to https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#adding-translations which should explain exactly what's needed

2022-03-19 09:32 UTC, Tinkidinki commented
This is the comment that I will be adding: 

<!-- 
 ~ Copyright (c) 2009 Andrew <andrewdubya@gmail> 
 ~ Copyright (c) 2009 Edu Zamora <edu.zasu@gmail.com> 
 ~ Copyright (c) 2009 Daniel Svaerd <daniel.svard@gmail.com> 
 ~ Copyright (c) 2009 Nicolas Raoul <nicolas.raoul@gmail.com> 
 ~ Copyright (c) 2010 Norbert Nagold <norbert.nagold@gmail.com> 
 ~ This program is free software; you can redistribute it and/or modify it under 
 ~ the terms of the GNU General Public License as published by the Free Software 
 ~ Foundation; either version 3 of the License, or (at your option) any later 
 ~ version. 
 ~ 
 ~ This program is distributed in the hope that it will be useful, but WITHOUT ANY 
 ~ WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
 ~ PARTICULAR PURPOSE. See the GNU General Public License for more details. 
 ~ 
 ~ You should have received a copy of the GNU General Public License along with 
 ~ this program.  If not, see <http://www.gnu.org/licenses/>. 
 ~ 
 ~ THIS IS AN AUTOMATICALLY GENERATED FILE. PLEASE DO NOT EDIT THIS FILE. 
 ~ 1. If you would like to add/delete/modify the original translatable strings, follow instructions here: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#adding-translations
 ~ 2. If you would like to provide a translation of the original file, you may do so using Crowdin. 
 ~    Instructions for this are available here: https://github.com/ankidroid/Anki-Android/wiki/Translating-AnkiDroid. 
 ~    You may also find the documentation on Contributing to Anki useful: https://github.com/ankidroid/Anki-Android/wiki/Contributing
 -->

2022-03-23 06:47 UTC, Tinkidinki commented
Is there something else that needs to be done here?

2022-03-23 11:40 UTC, mikehardy approved these changes
This looks good to me, thank you!

2022-03-23 13:40 UTC, david-allison requested changes

2022-03-23 13:40 UTC, david-allison commented on tools/update-localizations.py
> +                line = "<?xml version=\"1.0\" encoding=\"utf-8\"?> \n <!-- \n ~ Copyright (c) 2009 Andrew <andrewdubya@gmail> \n ~ Copyright (c) 2009 Edu Zamora <edu.zasu@gmail.com> \n ~ Copyright (c
I think we should put the "autogenerated file"/instructions before the copyrights in this case. 

We need to ensure that the maximal number of users see this.

Message looks great!

2022-03-23 13:41 UTC, mikehardy commented on tools/update-localizations.py
> +                line = "<?xml version=\"1.0\" encoding=\"utf-8\"?> \n <!-- \n ~ Copyright (c) 2009 Andrew <andrewdubya@gmail> \n ~ Copyright (c) 2009 Edu Zamora <edu.zasu@gmail.com> \n ~ Copyright (c
That's a great point. Put it right at the top - that's better. Sorry for asking for another change but I think David's suggestion will really improve it @Tinkidinki - this ends up wasting a lot of people's time, and I hate to see that happen if we can avoid it...

2022-03-30 19:46 UTC, Tinkidinki commented
Made the change! I apologise for the delay!

2022-03-30 19:51 UTC, Tinkidinki commented
Made a change with the comment symbol

2022-04-07 17:02 UTC, mikehardy approved these changes
David's comment is addressed! Thanks for your patience @Tinkidinki this looks great

2022-04-07 17:02 UTC, merged

2022-04-07 17:04 UTC, mikehardy commented
I'm running our translations sync job right now in order to exercise the code :crossed_fingers: :four_leaf_clover: :smile: 

https://github.com/ankidroid/Anki-Android/runs/5872757979?check_suite_focus=true

2022-06-05 21:01 UTC, mikehardy commented
Hi there! APRIL OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [April 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-04-01..2022-04-30)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of March.

Please note that GSoC contributions are okay for this process. Our philosophy is that our users have donated to AnkiDroid for all contributions. The only PRs that will not go through the OpenCollective process are ones directly related to am accepted GSoC project from a selected participant, since those receive a stipend from GSoC itself.

Please understand that this means the monthly budget we have for payments might be stretched a bit and the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!