[kotlin Migration]-IntentHandler
ankidroid/Anki-Android pull request #10577
Opened 2022-03-18 19:02 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
kotlin migration of intentHandler .java

## Approach

1.Convert JAVA file to Kotlin
2.Do some small changes manually

## How Has This Been Tested?
1.run it unit test 
2. test the app on Android Device :Redmiy3

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-03-18 19:12 UTC, david-allison requested changes
CI fails

```
> Task :AnkiDroid:ktlintMainSourceSetCheck FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt:1:1 File must end with a newline (\n)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt:46:9 Missing space after //
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt:81:1 Unexpected indentation (16) (should be 12)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt:81:108 Missing newline before ")"
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt:137:5 Missing space after //
```

2022-03-19 03:41 UTC, Prince-kushwaha commented
@david-allison i do not understand what i have to do in change request ?

2022-03-19 09:30 UTC, david-allison commented
Your commit didn't compile.

Fix the code, then either `git commit --amend`

Or commit, then `git rebase -i HEAD~3` and squash the last two commits

2022-03-19 17:46 UTC, david-allison requested changes
There's only one commit here. You need to follow the procedure: https://github.com/ankidroid/Anki-Android/blob/main/docs/kotlin-migration.md

2022-03-19 17:50 UTC, Prince-kushwaha commented
@david-allison in above commit you say`   git rebase -i HEAD~3` and squash the last two commits

2022-03-19 17:51 UTC, Prince-kushwaha commented
you say to squash the last two commits

2022-03-19 18:06 UTC, david-allison commented
> you say to squash the last two commits

You had three commits. Squashing the last two leaves two commits.

2022-03-20 05:29 UTC, Akshay0701 requested changes
Thanks for contribution @Prince-kushwaha,

conversion looks good, just made one comment,

and please add file name in first commit as [Rename IntentHandler.java to IntentHandler.kt](https://github.com/ankidroid/Anki-Android/pull/10577/commits/d4a8bcaeec623ac4e5a2dfa689809c9fbdc5b1a4)

2022-03-20 05:29 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java
> -                launchDeckPickerIfNoOtherTasks(reloadIntent);
you missed this in kotlin conversion

2022-03-20 05:29 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
> +        @JvmStatic
no need `jvmstatic` here

2022-03-20 05:50 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java
> -                launchDeckPickerIfNoOtherTasks(reloadIntent);
when i add else branch  it give error `[when is exhaustive so else is redundant]`

2022-03-20 05:51 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java
> -                launchDeckPickerIfNoOtherTasks(reloadIntent);
we not need default case because when statement  cover all the case

2022-03-20 05:55 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
> +        @JvmStatic
i  used jvmstatic here to call  `getLaunchType()` easily  from  `IntentHandlerTest.java`

2022-03-22 14:52 UTC, mikehardy approved these changes
LGTM - verified original comments addressed, commits looks clean, flagging for second approval

2022-03-23 13:29 UTC, merged