NF: EnsureDirectoryExists
ankidroid/Anki-Android pull request #10571
Opened 2022-03-18 02:40 UTC by Arthur-Milchior

2022-03-18 03:06 UTC, david-allison commented
```
com.ichi2.anki.servicelayer.scopedstorage.MoveDirectoryTest > a_move_failure_is_not_fatal[CompatV21] FAILED
    java.lang.ClassCastException: class com.ichi2.anki.servicelayer.scopedstorage.EnsureDirectoryExists cannot be cast to class com.ichi2.anki.servicelayer.scopedstorage.MoveDirectoryContent (com.ichi2.anki.servicelayer.scopedstorage.EnsureDirectoryExists and com.ichi2.anki.servicelayer.scopedstorage.MoveDirectoryContent are in unnamed module of loader 'app')
        at com.ichi2.anki.servicelayer.scopedstorage.MoveDirectoryTest.a_move_failure_is_not_fatal(MoveDirectoryTest.kt:131)
```

2022-03-18 03:10 UTC, david-allison requested changes
This would be better as a utility method in `Compat`, an `Operation` seems overkill here.

This would give a stronger exception on failure for the functionality:

`internal fun createDirectory(directory: File) = directory.exists() || directory.mkdirs()`

2022-03-18 03:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/EnsureDirectoryExists.kt
> +class EnsureDirectoryExists(val directory: File) : Operation() {
Doesn't need to be an operation, this can just exist in `Compat`

2022-03-18 03:51 UTC, Arthur-Milchior commented
I fail to understand what using Compat would bring to us.
For MoveDirectoryContent, it allowed to use streams and avoid long blocking operation. In this case, using `mkdirs` for all API seems to be as efficient as using `Files::makeDirectories` when available.
On discord you mentioned that `Files::makeDirectories` send more specific exception. Can you clarify what you expect in term of exception? Because the only exception more specific I see is `FileAlreadyExistsException`, which anyway is not available on API21, so it's not like I can actually use it in the code that call Compat.

2022-03-18 17:12 UTC, david-allison commented
It's not about having a more specific exception in terms of the type system, it's about having a more specific exception in terms of the error, so we can more easily perform diagnosis of why a failure occurred (or display this to the user).

With `mkdirs()`, we get a return value of `false`. It doesn't throw an `IOEeception`

With `createDirectories()`, we get an `IOException`, or similar exception. The `IOException` is strictly better from an informational perspective.

And this needs to provide a consistent experience over all levels of `Compat`

2022-03-19 01:01 UTC, Arthur-Milchior commented
Better?

2022-03-19 01:08 UTC, Arthur-Milchior commented
No idea what occured. clearly not what was expected

2022-03-19 19:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
> +    class NotDirectoryException extends IOException {
Probably best to remove this, but if we're keeping it:

Could be:

`class NotDirectoryException(val file: File) extends IOException`

2022-03-19 19:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
> +    }
It seems unnecessarily risky to recreate `mkdirs`:

```
    if (directory.exists() || directory.mkdirs()) {
        return;
    }
    throw IOException("failed to create " + directory)
```

2022-03-20 00:46 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
> +    }
I thought that your point was to get to to know details about the failure. So knowing what creation failed, or which ancestor was a file, was the kind of things you'd want to know. Which would not be known from mkdirs.

I am sorry, but I feel like I totally fail to understand what exactly you are looking for, would you mind taking this PR over, please?

2022-03-27 03:12 UTC, closed without merging