[Kotlin Migration] TriStateCheckBox
ankidroid/Anki-Android pull request #10583
Opened 2022-03-19 00:46 UTC by david-allison

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-03-19 01:20 UTC, david-allison commented
Tested on my phone, not 100% confident, but it seems OK

2022-03-19 05:26 UTC, Akshay0701 requested changes
It Looks Good, just i have one doubt in arrayOfNulls

2022-03-19 05:26 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +                }
```suggestion
                
                    mClientListener?.let{ it.onCheckedChanged(this, this.isChecked) }
               
```

2022-03-19 05:26 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +                    return arrayOfNulls(size)
just have a doubt: in the previous java version file, Tarek used `SavedState` here, and now you used `arrayOfNulls`, do both works in the same?

2022-03-19 05:26 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +        }
i think it would be good, if we include the state var before the when, like state = when....

2022-03-19 05:26 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +     */
I think because of conversion the comments are changed.

2022-03-19 06:44 UTC, TheScriptan commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +    var state: State
Nitpick: 

There is `mState` (mutable state) & `state`. If we want to ensure immutability by private `mState`, shouldn't we disable setter for `var state` and manipulate only `mState`?

2022-03-19 10:25 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +                    return arrayOfNulls(size)
Docs for the method:

```
        /**
         * Create a new array of the Parcelable class.
         * 
         * @param size Size of the array.
         * @return Returns an array of the Parcelable class, with every entry
         * initialized to null.
         */
```

2022-03-19 10:25 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +        }
Handled in `@KotlinCleanup("IDE-based lint")`

2022-03-19 10:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +    var state: State
`m` is legacy Hungarian Notation for a `Non-public, non-static field name`. AnkiDroid used to (incorrectly IMO) use the AOSP naming guidelines:

https://source.android.com/setup/contribute/code-style#follow-field-naming-conventions

Once we move to Kotlin, this is impossible to implement in many cases. Currently in those cases we'll move to "regular" variable names, and hopefully later on add a lint rule to get rid of all the legacy names.

2022-03-19 10:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +                    return arrayOfNulls(size)
Also unsure here. I've tested and it seems fine, but we should ideally move to `@Parcelize` to remove the question

2022-03-19 10:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +                }
Added a cleanup

2022-03-19 12:45 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +        mState = if (checked) State.CHECKED else State.UNCHECKED
Should be according to code style.

2022-03-19 17:50 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +        mState = if (checked) State.CHECKED else State.UNCHECKED
Added a `KotlinCleanup`, but how would you prefer this is written?

2022-03-19 20:38 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +        mState = if (checked) State.CHECKED else State.UNCHECKED
```
mState = if (checked) {
    State.CHECKED
} else {
    State.UNCHECKED
}
```

2022-03-19 20:39 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +        mState = if (checked) State.CHECKED else State.UNCHECKED
According to this: https://github.com/ankidroid/Anki-Android/wiki/Code-style#the-if-else-class-of-statements-should-have-the-following-form

2022-03-19 20:40 UTC, ShridharGoel reviewed
A `KotlinCleanup` to rename `in` variable name can be added.

2022-03-21 08:02 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +        val ss = state as SavedState
`KotlinCleanup` for better variable name can be added.

2022-03-23 18:54 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +                    return arrayOfNulls(size)
Should this be a KotlinCleanup then? Seems like a dangling review comment

2022-03-23 20:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +                    return arrayOfNulls(size)
Already done with `    @KotlinCleanup("https://stackoverflow.com/a/69476454")`

2022-03-23 20:38 UTC, mikehardy approved these changes
All comments addressed

2022-03-23 20:39 UTC, merged