[JS Addons] Map package.json to AddonModel and check if is valid addon package or not
ankidroid/Anki-Android pull request #10586
Opened 2022-03-19 10:00 UTC by krmanik

## Pull Request template

## Purpose / Description
This is second PR in JS Addons series. 
Before downloading addon tgz packages, it needs to check if the addon package is valid or not for AnkiDroid using `package.json`.
The validity checked using three fields `addonTitle`, `ankiDroidJsApi` and `ankidroid-js-addon` keyword which are not present in other npm package's `package.json` file. These fields will be used to distinguish it from other npm packages. It is required for addon developer to add these fields to `package.json` file otherwise the packages will not be downloaded and extracted. 

Also it needs to check that name should be valid npm packages. The `validatename` method is implemented to check if name follow the naming convention of npm packages.

## Fixes
Fixes #7959 

## Approach
1. A class with the fields that may be present in package.json file. Then mapper will be used to map `package.json` to AddonModel class. 
```js
val mapper = AnkiSerialization.objectMapper
```
2. `updatePrefs` method will be used to enable and disable addon, the prefs will stored as HashSet
3. `isValidAnkiDroidAddon` method have multiple checks like empty name or fields present or not in package.json and `validateName` for naming convention

## How Has This Been Tested?
There are test class for each class.

## Learning (optional, can help others)
https://github.com/npm/validate-npm-package-name
https://github.com/lassjs/is-valid-npm-name
https://stackoverflow.com/questions/50050436/use-npm-package-to-validate-a-package-name

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-03-19 10:17 UTC, TheScriptan commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +    fun updatePrefs(preferences: SharedPreferences, jsAddonKey: String?, remove: Boolean) {
Maybe it is possible to make `jsAddonKey` non-nullable?

2022-03-23 12:14 UTC, mikehardy requested changes
Nice! I left some comments that are mostly about developer experience. The big question I have is about what is going in the SharedPrefs and that will affect how to get this finished I think

2022-03-23 12:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +        return false
Can you add a Timber.w here? It's not an error, but from a programming perspective we will have developers attempting to code packages and when they go to test them this will represent failed functionality, even if recoverable. They will really need our help to diagnose *why* their package is not loaded when they are hacking at 3 in the morning and make silly mistakes

2022-03-23 12:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmUtils.kt
> +        return false
We should leave Timber.i messages describing each failure. Really quickly, it is just developer support to avoid people logging issues in the future like "AnkiDroid JS API is not loading my module, why not !??"

Anything like `Timber.i("Invalid Name: isBlank");

2022-03-23 12:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +        return false
I left comments inside validateName, those will be Timber.i to inform *why* it's not valid, then this can `Timber.w("Package name failed validation")` and now if you are a developer you can fix it without hunting for any information, everything you need to move forward at speed is there

2022-03-23 12:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +                (addonType == REVIEWER_ADDON || addonType == NOTE_EDITOR_ADDON)
will have to split these in order to provide the messages if any validation here fails but I think "DX" (Developer Experience) is really important to get adoption of the API, so it's worth it

2022-03-23 12:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +    fun updatePrefs(preferences: SharedPreferences, jsAddonKey: String, remove: Boolean) {
I see this is used in the tests, but I don't understand what's actually going in here? What does each string going in here *mean* to the system? Depending on the answer, it might be best to store this in the deck configuration so that extension state is synced across multiple devices. That's the first thing people want in a multi-device system with extensions...

2022-03-24 05:17 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +    fun updatePrefs(preferences: SharedPreferences, jsAddonKey: String, remove: Boolean) {
I have used sharedPrefs to store enable and disabled addon status. For enabled addon, `getEnabledAddonsContent` (Separate PR) function will return contents to reviewer webview or note editor.

In image the addon toggled on to make it enabled and the status stored in shared prefs.  
<img src="https://user-images.githubusercontent.com/12841290/159846991-05d4ff7e-5b72-4265-9995-16f3498e6518.png" height=450></img>

2022-03-24 05:21 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +                (addonType == REVIEWER_ADDON || addonType == NOTE_EDITOR_ADDON)
I have split into individual `if/else` with timber messages.

2022-03-24 05:22 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +        return false
I have implemented it.

2022-03-24 05:22 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +        return false
I have added the timber messages.

2022-03-24 05:23 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +     * https://stackoverflow.com/questions/19949182/android-sharedpreferences-string-set-some-items-are-removed-after-app-restart/19949833
I have added the description for added links.

2022-03-24 05:23 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmUtils.kt
> +    const val NOTE_EDITOR_ADDON = "note-editor"
I have created a separate class for all constants related to js addons.

2022-03-24 13:13 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +    fun updatePrefs(preferences: SharedPreferences, jsAddonKey: String, remove: Boolean) {
Oh I like this! So we can sync addon config (and maybe list of addons) but per-device you may enable or disable them. By default are they enabled? Hopefully they are enabled by default, so by default in multi-device everything "just works" but now maybe for this specific device you can disable it locally. I think that's perfect.

2022-03-24 13:15 UTC, mikehardy requested changes
This LGTM with exception of the registry string as commented directly
This is great progress and I do think the error messages will help the poor developer trying to figure something out when using the system :-)

2022-03-24 13:15 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="npmjs_registry" translatable="false">https://registry.npmjs.org/%s/latest</string>
I don't see why this is a string here, for translation?
This will be a fundamental aspect of the system, we will always be using the npmjs registry and there is no (for example) spanish registry.
However, similar to the AnkIWeb sync server, perhaps this could be *configurable* (maybe later) so you could use yarnpkg or github package registry or maybe a private registry.

But I don't think this will ever have a valid translation, maybe just a fully separate URL (if registry config is added once this is all up and running)

2022-03-24 14:08 UTC, krmanik commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="npmjs_registry" translatable="false">https://registry.npmjs.org/%s/latest</string>
I have used this only in test. I have moved the url to test class. 

Because npm registry does not provide better way to get tarball url. Here we have to check the valid npm package then get tarball url. So, I created [anki-js-addon-json](https://github.com/krmanik/anki-js-addon-json) repository that will fetch all the valid js addons from npm registry (other repo can also added if required) and give a `anki-js-addon.json` file which contains only valid and allowed addons info with package download  link. 

This will help in listing the addons file in recycler view nicely.

2022-03-24 14:19 UTC, krmanik commented
I am using this feature on local build. The split PR is faster than earlier single PR.

2022-03-29 01:00 UTC, krmanik commented
Resolve the conflicts.

2022-03-29 14:15 UTC, david-allison requested changes

2022-03-29 14:15 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/AddonModelTest.kt
> +        val addonModel: AddonModel = mapper.readValue(URL(VALID_NPM_PACKAGE_NAME_URL), AddonModel::class.java)
I don't think we want a network dependency in our unit tests.

@mikehardy Can we handle this with a CI option (JUnit category)

2022-03-29 14:32 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +fun AddonModel.isValidAnkiDroidAddon(): Boolean {
Okay, This is I have to learn first. I will implement type system for AddonModel.

2022-03-29 14:34 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +        val versionCurrent = Version.valueOf(AnkiDroidJsAPIConstants.sCurrentJsApiVersion)
The addons uses AnkiDroid JS API. So, in JS API I used version before calling the JS API functions. So, if addons contains version below than required version then return addon as not valid.

I will re-implement this.

2022-03-29 14:35 UTC, krmanik commented on AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/AddonModelTest.kt
> +        val addonModel: AddonModel = mapper.readValue(URL(VALID_NPM_PACKAGE_NAME_URL), AddonModel::class.java)
I will move the json file to assets folder for test. So, network fetch will be removed.

2022-03-30 04:02 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +fun AddonModel.isValidAnkiDroidAddon(): Boolean {
I have created a function which take file path of json file. Then in function `AnkiSerialization` used to map json to AddonModel. For not matched conditions the error messages added an errors string list. Then the function returns `Pair<AddonModel, List<String>>` . For valid addons the error list will be empty but for not valid errors list will contains the errors where conditions not matched.

2022-04-13 15:12 UTC, mikehardy commented
This appears to be ready for a re-scan?

2022-04-15 14:14 UTC, david-allison requested changes

2022-04-15 14:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +data class AddonModel(
Do we need `data` here?

If we do, we need to handle equals/getHashCode manually due to the array properties

2022-04-15 14:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +fun getAddonModelFromJson(packageJsonPath: String): Pair<AddonModel?, List<String>> {
We should rename `AddonModel` to `AddonData`, and we should return an `AddonModel` with all the validated properties as non-null types.

2022-04-15 14:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +        errorStr = "Invalid addon package: package.json must have 'addonType' fields of 'reviewer' or 'note-editor'"
We should list the value

2022-04-15 14:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +        errorStr = "Invalid addon package: package.json must have 'ankidroid-js-addon' in keywords"
should list the value

2022-04-15 15:40 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +        errorStr = "Invalid addon package: package.json must have 'ankidroid-js-addon' in keywords"
Values added to list

2022-04-15 15:40 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +        errorStr = "Invalid addon package: package.json must have 'addonType' fields of 'reviewer' or 'note-editor'"
Values added to the list

2022-04-15 15:40 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +fun getAddonModelFromJson(packageJsonPath: String): Pair<AddonModel?, List<String>> {
I have rename the `AddonModel` to `AddonData` and created typealias for AddonModel

2022-04-15 15:41 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +data class AddonModel(
Removed `data` and changed to class.

2022-04-15 15:51 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +typealias AddonModel = AddonData
Use a different class, but with the properties as non-null, this will save a lot of `!!`s

2022-04-15 16:41 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +typealias AddonModel = AddonData
I don't understand how to implement this?

The `package.json` file contains key/value fields. Using Jackson it mapped to `AddonData`. It is class and other class created `AddonModel` so should I typecast AddonData to AddonModel?

```
fun getAddonModelFromJson(packageJsonPath: String): Pair<AddonModel?, List<String>> {
    val mapper = AnkiSerialization.objectMapper
    val addonData: AddonData = mapper.readValue(File(packageJsonPath), AddonData::class.java)
```

I have created `AddonModel` class
```
class AddonModel(
        val name: String,
        val addonTitle: String,
        val icon: String,
        val version: String,
        val description: String,
        val main: String,
        val ankidroidJsApi: String,
        val addonType: String,
        val keywords: Array<String>,
        val author: Map<String, String>,
        val license: String,
        val homepage: String,
        val dist: Map<String, String>
)
```

2022-04-15 17:25 UTC, krmanik commented
In this commit https://github.com/ankidroid/Anki-Android/pull/10586/commits/56a00b914a1e2ee5607fd9f7771dbcb596ab8aed, I have created AddonData class then mapped json then validate the data. After validation, created AddonModel and returned.
Is this correct implementation?

2022-04-15 17:25 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +typealias AddonModel = AddonData
What you've got looks good to me, one for serde, and one validated model for usage within the code

2022-04-15 17:27 UTC, david-allison requested changes
Looks great! Two minor changes

2022-04-15 17:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonData.kt
> +
```kotlin
    val icon = if (addonData.addonType == NOTE_EDITOR_ADDON) addonData.icon!! else ""
```

then use icon below - means all properties are immutable

2022-04-15 17:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +) {
Ideally all of these should be `val`

2022-04-15 17:38 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonData.kt
> +
Updated,
Thanks

2022-04-15 17:38 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +) {
Updated

2022-04-15 17:38 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +typealias AddonModel = AddonData
Thanks

2022-04-15 17:46 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +) {
So, I should change `Map` to `ImmutabMap`?

2022-04-15 18:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +) {
If it works, then yes, but treat it as an extension

2022-04-15 18:13 UTC, david-allison approved these changes
One optional extension to make `AddonModel` fully immutable.

Happy to merge when CI passes

2022-04-15 19:13 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +) {
I have tried but test failed, to make it `ImmutableMap` the fields in AddonData also needs to change then following exception occurs.
```
com.ichi2.anki.jsaddons.AddonModelTest > updatePrefsTest FAILED
    com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.acra.collections.ImmutableMap` (no Creators, like default constructor, exist): no default constructor found
     at [Source: (File); line: 1, column: 556] (through reference chain: com.ichi2.anki.jsaddons.AddonData["author"])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1904)
        at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1349)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:427)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3494)
        at com.ichi2.anki.jsaddons.AddonDataKt.getAddonModelFromJson(AddonData.kt:66)
        at com.ichi2.anki.jsaddons.AddonModelTest.updatePrefsTest(AddonModelTest.kt:87)
```

2022-04-15 19:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +) {
You want immutability in `AddonModel`, not in `AddonData`. AddonData has a reason to be mutable.

2022-04-15 19:34 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +) {
I get it worked. Test is running locally. I will rebase and squash some commit then push the changes.

2022-04-15 19:52 UTC, david-allison approved these changes

2022-04-15 19:54 UTC, mikehardy commented
Another JS Add Ons PR about to merge
![rubbinghandstogether](https://user-images.githubusercontent.com/782704/163626030-7d1908a5-3388-47cb-8597-290de24a039e.gif)

2022-04-15 20:07 UTC, mikehardy commented
@krmanik  lint issue - I'm testing it locally:

```

* What went wrong:
Execution failed for task ':AnkiDroid:ktlintTestSourceSetCheck'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.ConsoleReportWorkAction
   > KtLint found code style violations. Please see the following reports:
     - /home/mike/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/build/reports/ktlint/ktlintTestSourceSetCheck/ktlintTestSourceSetCheck.txt


```

2022-04-15 20:13 UTC, krmanik commented
Thanks, I am also running the lint.

2022-04-15 20:17 UTC, mikehardy commented
passes all the other tests though, for me locally. Just some "needless blank lines" away from a merge :-)

> /home/mike/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/AddonModelTest.kt:37:1 Needless blank line(s)

2022-04-15 20:19 UTC, krmanik commented
I should push the changes or leave it?

2022-04-17 15:27 UTC, krmanik commented
I came up with the idea of adding content to reviwer using index.js.
But as it grows, there will be need of adding content like
```
style: style.css
front: front.js
back: back.js
```
Addon developer may need to add styling using style.css file and AnkiDroid should inject it to reviewer. The same task can be done using JS. 

Currently I use `index.js` to do the content addition to front, back and styling, e.g. if `style` field will be added to package.json then following code will be more shorter. Same for front and back fields. 

I will push these three fields. Any thoughts?

```js
var progressDiv = document.createElement("div");
progressDiv.id = "h-progress";
progressDiv.className = "progress-1";
progressDiv.innerHTML = '<div class="progress-bar-1" id="h-bar"></div>';
// v0.5.2 - https://github.com/SimonLammer/anki-persistence/blob/62463a7f63e79ce12f7a622a8ca0beb4c1c5d556/script.js
if (void 0 === window.Persistence) { var _persistenceKey = "github.com/SimonLammer/anki-persistence/", _defaultKey = "_default"; if (window.Persistence_sessionStorage = function () { var e = !1; try { "object" == typeof window.sessionStorage && (e = !0, this.clear = function () { for (var e = 0; e < sessionStorage.length; e++) { var t = sessionStorage.key(e); 0 == t.indexOf(_persistenceKey) && (sessionStorage.removeItem(t), e--) } }, this.setItem = function (e, t) { void 0 == t && (t = e, e = _defaultKey), sessionStorage.setItem(_persistenceKey + e, JSON.stringify(t)) }, this.getItem = function (e) { return void 0 == e && (e = _defaultKey), JSON.parse(sessionStorage.getItem(_persistenceKey + e)) }, this.removeItem = function (e) { void 0 == e && (e = _defaultKey), sessionStorage.removeItem(_persistenceKey + e) }) } catch (e) { } this.isAvailable = function () { return e } }, window.Persistence_windowKey = function (e) { var t = window[e], i = !1; "object" == typeof t && (i = !0, this.clear = function () { t[_persistenceKey] = {} }, this.setItem = function (e, i) { void 0 == i && (i = e, e = _defaultKey), t[_persistenceKey][e] = i }, this.getItem = function (e) { return void 0 == e && (e = _defaultKey), t[_persistenceKey][e] || null }, this.removeItem = function (e) { void 0 == e && (e = _defaultKey), delete t[_persistenceKey][e] }, void 0 == t[_persistenceKey] && this.clear()), this.isAvailable = function () { return i } }, window.Persistence = new Persistence_sessionStorage, Persistence.isAvailable() || (window.Persistence = new Persistence_windowKey("py")), !Persistence.isAvailable()) { var titleStartIndex = window.location.toString().indexOf("title"), titleContentIndex = window.location.toString().indexOf("main", titleStartIndex); titleStartIndex > 0 && titleContentIndex > 0 && titleContentIndex - titleStartIndex < 10 && (window.Persistence = new Persistence_windowKey("qt")) } }

var UA = navigator.userAgent;
var isMobile = /Android/i.test(UA);
var isAndroidWebview = /wv/i.test(UA);

if (isMobile && isAndroidWebview) {
    progressBarInit();
} else {
    progressBarHide();
}

function progressBarHide() {
    document.getElementById("h-progress").style.display = "none";
    document.getElementById("h-bar").style.display = "none";
}

function progressBarInit() {
    document.body.insertBefore(progressDiv, document.body.firstChild);
    var cardCount = parseInt(AnkiDroidJS.ankiGetNewCardCount()) + parseInt(AnkiDroidJS.ankiGetLrnCardCount()) + parseInt(AnkiDroidJS.ankiGetRevCardCount());

    var totalCardCount = 1;
    if (Persistence.isAvailable()) {
        totalCardCount = Persistence.getItem("total");
        if (totalCardCount == null) {
            totalCardCount = cardCount;    // count set to total card count at first card, it will not change for current session
            Persistence.setItem("total", totalCardCount);
        }
    }

    // progress bar percentage
    var per = Math.trunc(100 - cardCount * 100 / totalCardCount) + "%";
    document.getElementById("h-bar").style.width = per;
}

var progressBarCSS = `
.progress-1 {
width: 100%;
border-radius: 2px;
background-color: #e6e6e6;
}
.progress-bar-1 {
height: 12px;
border-radius: 2px;
background-color: limegreen;
}
`;

var styleSheet = document.createElement("style");
styleSheet.type = "text/css";
styleSheet.innerText = progressBarCSS;
document.head.appendChild(styleSheet);
```

2022-04-17 15:29 UTC, david-allison commented
Do we have anywhere else to discuss this? It doesn't seem relevant to the PR.

2022-04-17 15:30 UTC, krmanik commented
> Do we have anywhere else to discuss this? It doesn't seem relevant to the PR.

To the original issue. I hide it and paste there

2022-04-17 18:45 UTC, krmanik commented
I checked the implementation again I think front/back/styling content addition should be handled in JS API. I will create PR if needed till then this PR does not need any changes.

2022-04-17 19:56 UTC, merged

2022-04-17 19:58 UTC, mikehardy commented
Passed local re-integration with current main!
![giphy](https://user-images.githubusercontent.com/782704/163730265-873fed2b-cbed-43cf-8a65-bb2abc4c0a23.gif)

2022-04-18 13:55 UTC, krmanik commented
Thanks, three more PR to go

![](https://i.giphy.com/media/vPuszmHgeWnIhTkSr5/giphy.webp)