Migrate ModelFieldEditor to Kotlin
ankidroid/Anki-Android pull request #10602
Opened 2022-03-22 09:38 UTC by ShridharGoel

2022-03-22 13:40 UTC, Akshay0701 submitted a review, later dismissed

2022-03-22 13:40 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +    }
in the java version, there were methods with a `closeActivity` name with two different parameters, this kotlin file only has one of that methods, is there any reason to remove the other one?

2022-03-22 13:40 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +        }
`?` would be best here for null handling

2022-03-22 23:57 UTC, david-allison requested changes
Awesome! Only a few imports and newlines - rest are for the cleanup queue :)

2022-03-22 23:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +        mFieldLabelView = findViewById(R.id.note_type_editor_fields)
it would be great if we kept the blank newlines from the previous code - that allows for easier line:line comparisons

2022-03-22 23:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +        if (supportActionBar != null) {
`KotlinCleanup`: `?.let { }` to remove the `!!`

2022-03-22 23:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +            update(this)
Remove the import for `WidgetStatus`, this makes less sense

2022-03-22 23:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +    private fun createfieldLabels() {
`cleanup`: scope function

2022-03-22 23:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +        mNoteFields = mMod!!.getJSONArray("flds")
likewise with the spacing

2022-03-22 23:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +    private fun addField(fieldName: String?, listener: ChangeHandler, modSchemaCheck: Boolean) {
`Cleanup`: See if we can make `fieldName` non-null

2022-03-22 23:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +        if (mFieldLabels!!.size < 2) {
spacing/newlines

2022-03-22 23:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +    private fun deleteFieldDialog() {
cleanup: add scope functions

2022-03-22 23:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +        for (s in mFieldLabels!!) {
`kotlincleanup`: stream/extension function

2022-03-22 23:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +                // Need this as we can't switch on a @RequiresApi
KotlinCleanup: can probably do this in Kotlin

2022-03-22 23:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +        val dialogFragment: DialogFragment = newInstance(this)
Change to `LocaleSelectionDialog.newInstance`

2022-03-22 23:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +    }
We should keep it and flag it for `KotlinCleanup` (unless it's now a compile error), but it was useless and this change is correct.

`closeActivity(int)` called to `closeActivity` and the int was never used

2022-03-23 08:08 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +    }
Removed the parameter because it's a compile error now.

2022-03-23 11:45 UTC, mikehardy approved these changes
one KotlinCleanup annotation to go I think but otherwise good if it gets that and a second approve

2022-03-23 11:45 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +                // Need this as we can't switch on a @RequiresApi
This is the only one that does not seem to be addressed yet? I'm +1 merge after adding KotlinCleanup per David here

2022-03-23 11:59 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +                // Need this as we can't switch on a @RequiresApi
Updated

2022-03-23 13:48 UTC, david-allison approved these changes

2022-03-23 13:50 UTC, merged

2022-04-22 14:32 UTC, mikehardy commented
Hi there! MARCH OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [March 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-03-01..2022-03-31)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of March.

Please note that GSoC contributions are okay for this process. Our philosophy is that our users have donated to AnkiDroid for *all* contributions. The only PRs that will not go through the OpenCollective process are ones *directly* related to a GSoC project from a selected participant, since those receive a stipend from GSoC itself.

Please understand that this means the monthly budget we have for payments might be stretched a bit and the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!