added New Lint rule for Detecting invalid string formats.
ankidroid/Anki-Android pull request #10628
Opened 2022-03-26 11:46 UTC by justdvnsh

## Purpose / Description
The main issue was an invalid format string: https://github.com/ankidroid/Anki-Android/pull/10548/files which caused a crash.

We want to ensure that a string on the left is caught by the lint-rules project, and fails the CI. We want this both for plurals and standard strings (this may be a plural only issue).

## Fixes
#10604 

## Approach
Added a new lint rule to check for such errors. 

## How Has This Been Tested?
Added a test for the rule as well.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-03-26 13:22 UTC, david-allison requested changes
This is really nice! Thanks!!!

This doesn't pass the lint checks (`gradlew lint`):

* Special-case: `XXX%` as valid - we use this as a format String
* It looks like this has picked up two issues in `stats_cumulative_correct_percentage`
  * Check if they crash.
  * If they don't, the lint needs to pass on this case
  * If they do crash, fix them in this commit

<details><summary>Issues</summary>

2022-03-26T13:16:31.9515745Z > Task :AnkiDroid:lintPlayDebug FAILED
2022-03-26T13:16:31.9516769Z /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/02-strings.xml:23: Error: You have specified the string in wrong formatPlease check that '%' sign been applied only to valid parameters. Your string might be having a regular word with '%' sign after it. eg: 'I have completed% %s cards.'  [InvalidStringFormat from com.ichi2.anki.lint]
2022-03-26T13:16:31.9517921Z     <string name="preference_summary_percentage">XXX%</string>
2022-03-26T13:16:31.9518277Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-26T13:16:31.9519278Z /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-af/02-strings.xml:42: Error: You have specified the string in wrong formatPlease check that '%' sign been applied only to valid parameters. Your string might be having a regular word with '%' sign after it. eg: 'I have completed% %s cards.'  [InvalidStringFormat from com.ichi2.anki.lint]
2022-03-26T13:16:31.9520202Z     <string name="preference_summary_percentage">XXX%</string>
2022-03-26T13:16:31.9520555Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-26T13:16:31.9521978Z /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-am/02-strings.xml:42: Error: You have specified the string in wrong formatPlease check that '%' sign been applied only to valid parameters. Your string might be having a regular word with '%' sign after it. eg: 'I have completed% %s cards.'  [InvalidStringFormat from com.ichi2.anki.lint]
2022-03-26T13:16:31.9522745Z     <string name="preference_summary_percentage">XXX%</string>
2022-03-26T13:16:31.9523027Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-26T13:16:31.9523936Z /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-be/02-strings.xml:42: Error: You have specified the string in wrong formatPlease check that '%' sign been applied only to valid parameters. Your string might be having a regular word with '%' sign after it. eg: 'I have completed% %s cards.'  [InvalidStringFormat from com.ichi2.anki.lint]
2022-03-26T13:16:31.9524612Z     <string name="preference_summary_percentage">XXX%</string>
2022-03-26T13:16:31.9524886Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-26T13:16:31.9525770Z /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-bg/02-strings.xml:42: Error: You have specified the string in wrong formatPlease check that '%' sign been applied only to valid parameters. Your string might be having a regular word with '%' sign after it. eg: 'I have completed% %s cards.'  [InvalidStringFormat from com.ichi2.anki.lint]
2022-03-26T13:16:31.9526412Z     <string name="preference_summary_percentage">XXX%</string>
2022-03-26T13:16:31.9526665Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-26T13:16:31.9527530Z /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-bn/02-strings.xml:42: Error: You have specified the string in wrong formatPlease check that '%' sign been applied only to valid parameters. Your string might be having a regular word with '%' sign after it. eg: 'I have completed% %s cards.'  [InvalidStringFormat from com.ichi2.anki.lint]
2022-03-26T13:16:31.9528152Z     <string name="preference_summary_percentage">XXX%</string>
2022-03-26T13:16:31.9528422Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-26T13:16:31.9529544Z /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-ca/02-strings.xml:42: Error: You have specified the string in wrong formatPlease check that '%' sign been applied only to valid parameters. Your string might be having a regular word with '%' sign after it. eg: 'I have completed% %s cards.'  [InvalidStringFormat from com.ichi2.anki.lint]
2022-03-26T13:16:31.9530176Z     <string name="preference_summary_percentage">XXX%</string>
2022-03-26T13:16:31.9530427Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-26T13:16:31.9531322Z /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-ckb/02-strings.xml:42: Error: You have specified the string in wrong formatPlease check that '%' sign been applied only to valid parameters. Your string might be having a regular word with '%' sign after it. eg: 'I have completed% %s cards.'  [InvalidStringFormat from com.ichi2.anki.lint]
2022-03-26T13:16:31.9532182Z     <string name="preference_summary_percentage">XXX%</string>
2022-03-26T13:16:31.9532457Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-26T13:16:31.9533340Z /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-cs/02-strings.xml:42: Error: You have specified the string in wrong formatPlease check that '%' sign been applied only to valid parameters. Your string might be having a regular word with '%' sign after it. eg: 'I have completed% %s cards.'  [InvalidStringFormat from com.ichi2.anki.lint]
2022-03-26T13:16:31.9534008Z     <string name="preference_summary_percentage">XXX%</string>
2022-03-26T13:16:31.9534349Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-26T13:16:31.9535222Z /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-da/02-strings.xml:42: Error: You have specified the string in wrong formatPlease check that '%' sign been applied only to valid parameters. Your string might be having a regular word with '%' sign after it. eg: 'I have completed% %s cards.'  [InvalidStringFormat from com.ichi2.anki.lint]
2022-03-26T13:16:31.9535872Z     <string name="preference_summary_percentage">XXX%</string>
2022-03-26T13:16:31.9536131Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-26T13:16:31.9537009Z /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-el/02-strings.xml:42: Error: You have specified the string in wrong formatPlease check that '%' sign been applied only to valid parameters. Your string might be having a regular word with '%' sign after it. eg: 'I have completed% %s cards.'  [InvalidStringFormat from com.ichi2.anki.lint]
2022-03-26T13:16:31.9537647Z     <string name="preference_summary_percentage">XXX%</string>
2022-03-26T13:16:31.9538065Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-26T13:16:31.9538957Z /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-eo/02-strings.xml:42: Error: You have specified the string in wrong formatPlease check that '%' sign been applied only to valid parameters. Your string might be having a regular word with '%' sign after it. eg: 'I have completed% %s cards.'  [InvalidStringFormat from com.ichi2.anki.lint]
2022-03-26T13:16:31.9539620Z     <string name="preference_summary_percentage">XXX%</string>
2022-03-26T13:16:31.9539891Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-26T13:16:31.9540805Z /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-es-rAR/02-strings.xml:42: Error: You have specified the string in wrong formatPlease check that '%' sign been applied only to valid parameters. Your string might be having a regular word with '%' sign after it. eg: 'I have completed% %s cards.'  [InvalidStringFormat from com.ichi2.anki.lint]
2022-03-26T13:16:31.9541476Z     <string name="preference_summary_percentage">XXX%</string>
2022-03-26T13:16:31.9541744Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-26T13:16:31.9542624Z /home/runner/ [...]

2022-03-26 13:22 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/InvalidStringFormatDetector.kt
> +        println(text)
```suggestion
```

2022-03-26 13:22 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/InvalidStringFormatDetector.kt
> +            if (it.matches(INVALID_FORMAT_PATTERN.toRegex())) {
performance: extract `INVALID_FORMAT_PATTERN.toRegex()` to the variable to save a `.toRegex()` call on each iteration of the loop

2022-03-26 13:24 UTC, justdvnsh commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/InvalidStringFormatDetector.kt
> +            if (it.matches(INVALID_FORMAT_PATTERN.toRegex())) {
Hey. Sorry. I missed this. I already had this in mind, but I committed this before sending in the PR XD. My bad @david-allison . I'll fix these in my next commit.

2022-03-26 13:27 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/InvalidStringFormatDetector.kt
> +            if (it.matches(INVALID_FORMAT_PATTERN.toRegex())) {
No worries, really appreciate you taking the time for this :)

2022-03-26 14:32 UTC, justdvnsh commented
@david-allison Fixed the errors and handled special cases.

2022-03-27 01:26 UTC, david-allison reviewed
One question, but the rest looks fantastic, thanks so much for the quick turnaround

2022-03-27 01:26 UTC, david-allison commented on AnkiDroid/src/main/res/values-mr/06-statistics.xml
> +    <string formatted="false" name="stats_cumulative_correct_percentage">संचयी बरोबर %</string>
Does this not crash? What does it look like?

2022-03-27 08:30 UTC, justdvnsh commented on AnkiDroid/src/main/res/values-mr/06-statistics.xml
> +    <string formatted="false" name="stats_cumulative_correct_percentage">संचयी बरोबर %</string>
Crash ? I didn't quite get you ? Can you please elaborate on this ?

2022-03-27 18:46 UTC, david-allison commented on AnkiDroid/src/main/res/values-mr/06-statistics.xml
> +    <string formatted="false" name="stats_cumulative_correct_percentage">संचयी बरोबर %</string>
Just confirming that the issue is:

*  a character, followed by %
* rather than any raw % in the string.

To test: in app, select the language and load a screen which uses the string

2022-03-27 18:46 UTC, david-allison approved these changes

2022-03-27 18:47 UTC, david-allison commented
For maintainers: before merging, we need to move the string changes to CrowdIn, perform a translation sync, then rebase this.

2022-03-30 03:51 UTC, justdvnsh commented on AnkiDroid/src/main/res/values-mr/06-statistics.xml
> +    <string formatted="false" name="stats_cumulative_correct_percentage">संचयी बरोबर %</string>
Hi @david-allison Sorry for the late response. The issue is a character followed by %. A random % in the string won't affect anything.

On further research I found out that, actually, the string wasn't formatted correctly, in this issue. https://github.com/ankidroid/Anki-Android/issues/10545#issuecomment-1075376989

For positional arguments we write %s to position any arguments at that place, but in the marathi translation for the same, % was added after the word. This lint , as you suggested, should be a part of the IDE, but since it's not, we have this PR 😅

2022-03-30 13:59 UTC, david-allison commented
@mikehardy pinging for a review

2022-03-31 18:47 UTC, mikehardy commented on AnkiDroid/src/main/res/values-te/06-statistics.xml
> +    <string formatted="false" name="stats_cumulative_correct_percentage">సంచిత సరైన %</string>
fixed directly in crowdin just now

2022-03-31 18:48 UTC, mikehardy approved these changes
Looks good. I've made the edits on crowdin and it's ready for a sync

2022-03-31 18:50 UTC, mikehardy commented
sync happening, I'll pull this local to rebase it and push it so I can merge

2022-03-31 20:30 UTC, mikehardy commented
`./gradlew clean jacocoTestReport lint ktlintCheck` passed locally after:

`gh pr checkout 10628 && git fetch origin && git rebase origin/main` (where origin is set to `git@github.com:ankidroid/Anki-Android` 

I added your fork as a remote @justdvnsh and force-pushed the result of that rebase back to this branch on your fork, and this should all pass CI, then be ready for merge

:rocket:

2022-03-31 21:00 UTC, merged

2022-04-22 14:32 UTC, mikehardy commented
Hi there! MARCH OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [March 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-03-01..2022-03-31)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of March.

Please note that GSoC contributions are okay for this process. Our philosophy is that our users have donated to AnkiDroid for *all* contributions. The only PRs that will not go through the OpenCollective process are ones *directly* related to a GSoC project from a selected participant, since those receive a stipend from GSoC itself.

Please understand that this means the monthly budget we have for payments might be stretched a bit and the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!