[Bug] After creating a subdeck, the parent deck's menu is displayed again
ankidroid/Anki-Android pull request #10635
Opened 2022-03-27 07:14 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

After creating a subdeck, the parent deck's menu is displayed again

## Fixes
Fixes #10632 

## How Has This Been Tested?
Android Device:Redmi y3

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-03-28 17:54 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
> +            .autoDismiss(true)
If user click `Cancel` then also the Deck options popup will be dismissed?

2022-04-02 03:42 UTC, Prince-kushwaha commented
@david-allison can review this PR

2022-04-02 22:54 UTC, mikehardy requested changes
I don't understand why *this* change is the change that fixes it.
This is where our Kotlin migration process really shines, because git blame is still connected through the java->kotlin transition

I traced this line back in time and it has always been autoDismiss false
https://github.com/ankidroid/Anki-Android/blame/640381c6e60edbe98b17df11ebc180a7554fc9fe/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt

Or at least, for the last 7 years? So, why does it need to be auto-dismiss true when the behavior appears correct in 2.15, where it was false?

2022-04-13 14:38 UTC, mikehardy commented
@Prince-kushwaha this has feedback to address but I see you've requested another icon issue. Please address all feedback in existing PRs at minimum before taking on new ones - completion / follow-through / responsiveness is as important as volume of work I think, so that PRs don't stall and clutter the PR queue / slow down overall project throughput

2022-04-13 17:08 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
> +                (activity as AnkiActivity?)!!.dismissAllDialogFragments()
previous dialog get  dismissed

2022-04-13 21:30 UTC, krmanik commented
@Prince-kushwaha Add dismiss all fragments here. Add `dismissAllDialogFragments();` to this function. It should dismiss when `Ok` pressed. The UI should be similar to `Rename Deck`.
https://github.com/ankidroid/Anki-Android/blob/621701574a7fddbde22a57e8603fd4c8cd5ecdc9/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L2655-L2666

2022-04-14 11:53 UTC, krmanik approved these changes
Thanks

2022-04-14 11:56 UTC, krmanik commented
Build is failing but not related to this PR
```
e: D:\a\Anki-Android\Anki-Android\AnkiDroid\src\test\java\com\ichi2\anki\CardBrowser_CardCollectionTest.kt: (32, 38): Cannot access 'position': it is private in 'Positioned'
e: D:\a\Anki-Android\Anki-Android\AnkiDroid\src\test\java\com\ichi2\anki\CardBrowser_CardCollectionTest.kt: (35, 38): Cannot access 'position': it is private in 'Positioned'
e: D:\a\Anki-Android\Anki-Android\AnkiDroid\src\test\java\com\ichi2\anki\CardBrowser_CardCollectionTest.kt: (46, 30): Cannot weaken access privilege 'public' for 'position' in 'PositionAware'
e: D:\a\Anki-Android\Anki-Android\AnkiDroid\src\test\java\com\ichi2\anki\CardBrowser_CardCollectionTest.kt: (46, 42): 'position' hides member of supertype 'PositionAware' and needs 'override' modifier
e: D:\a\Anki-Android\Anki-Android\AnkiDroid\src\test\java\com\ichi2\anki\CardBrowser_CardCollectionTest.kt: (48, 9): 'getPosition' overrides nothing
e: D:\a\Anki-Android\Anki-Android\AnkiDroid\src\test\java\com\ichi2\anki\CardBrowser_CardCollectionTest.kt: (52, 9): 'setPosition' overrides nothing

```

2022-04-14 12:04 UTC, Prince-kushwaha commented
Build is failing due to this PR https://github.com/ankidroid/Anki-Android/pull/10827

2022-04-14 14:22 UTC, mikehardy commented
Build no longer failing if you want to rebase this and re-try, sorry for the hassle!

2022-04-14 19:00 UTC, krmanik approved these changes

2022-04-14 19:20 UTC, mikehardy approved these changes
Still a bit odd to me that this is failing now, but after a deck is created it seems logical to dismiss all fragments, we should be looking at the deck list at that point

2022-04-14 19:20 UTC, merged