[kotlincleanUp]  AudioRecorder.kt,AudioView.kt,StatsMetaInfo.kt
ankidroid/Anki-Android pull request #10666
Opened 2022-03-31 12:48 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
**kotlincleanUp of AudioRecorder.kt,AudioView.kt,StatsMetaInfo.kt**

## Fixes
Fixes #10489 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-03-31 12:52 UTC, david-allison requested changes
Thanks! Little work on `StatsMetaInfo`, rest are great!

2022-03-31 12:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/StatsMetaInfo.kt
>      fun setmSeriesList(seriesList: Array<DoubleArray>) {
All of these can be changed: make the `var` public and remove the methods (and `"JvmName` if necessary)

2022-04-01 02:52 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/StatsMetaInfo.kt
>      fun setmSeriesList(seriesList: Array<DoubleArray>) {
@david-allison I think properties are private is good becouse property are modified by  setter and acesss by getter method   setter and getter method make easy to access and modify value

2022-04-01 02:53 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/StatsMetaInfo.kt
>      fun setmSeriesList(seriesList: Array<DoubleArray>) {
i think their is not need to remove setter and getter method

2022-04-01 03:05 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/StatsMetaInfo.kt
>  @SuppressLint("VariableNamingDetector")
i did  kotlinCleanUp to remove suppression

2022-04-01 03:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/StatsMetaInfo.kt
>      fun setmSeriesList(seriesList: Array<DoubleArray>) {
But the setter methods are equivalent to the property accessors, just with a lot more code, and worse names?

2022-04-01 19:41 UTC, david-allison approved these changes
We can rebase this if commits 1 and 2 are squashed, otherwise squash merge

2022-04-02 23:30 UTC, mikehardy approved these changes
Nice! Thank you @Prince-kushwaha - the java formatting in AdvancedStatistics is not quite to our normal coding conventions but as we approach the end of our Java to Kotlin migration I'm inclined to let it go. Time is better spent actually migrating the code instead...

2022-04-02 23:30 UTC, merged