[kotlinCleanUp] ModelFieldEditor.kt
ankidroid/Anki-Android pull request #10668
Opened 2022-03-31 18:52 UTC by islam-yousry

## Pull Request template

## Purpose / Description
kotlinCleanUp of ModelFieldEditor.kt

## Fixes
Fixes part of #10489 

## Approach
Remove Hungarian notation
Use scope functions

## How Has This Been Tested?
Android Device: Samsung a03s
Run all the unit test

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [X] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-03-31 21:36 UTC, david-allison requested changes
Looks great, thanks!

One small change and we're good to go

2022-03-31 21:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +    private var collectionCol: Collection? = null
Either `collection` or `col`, up to you!

2022-03-31 22:21 UTC, david-allison approved these changes
Looks great, thanks!!

2022-04-02 23:26 UTC, mikehardy approved these changes
Nice! The separate commits actually is a great demonstration of specific / useful kotlin language features

2022-04-02 23:26 UTC, merged

2022-06-05 21:01 UTC, mikehardy commented
Hi there! APRIL OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [April 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-04-01..2022-04-30)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of March.

Please note that GSoC contributions are okay for this process. Our philosophy is that our users have donated to AnkiDroid for all contributions. The only PRs that will not go through the OpenCollective process are ones directly related to am accepted GSoC project from a selected participant, since those receive a stipend from GSoC itself.

Please understand that this means the monthly budget we have for payments might be stretched a bit and the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!