setting mBackButtonPressedToExit to false in onPause of DeckPicker
ankidroid/Anki-Android pull request #10679
Opened 2022-04-02 07:42 UTC by UvrajSB

## Pull Request template

## Purpose / Description
Double back pressed to exit feature wasn't working properly.

## Fixes
#10638 

## Approach
The variable storing the number of back pressed wasn't getting reset when we were moving to the next activity. So I reset the variable in the onPause function of the activity.

## How Has This Been Tested?

Physical Device: Realme 8i

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-02 11:44 UTC, prateek-singh-3212 commented
Thanks @UvrajSB for contributing to ankidroid. Can you attach the video describing the fix of this issue?

2022-04-02 12:04 UTC, UvrajSB commented
> Thanks @UvrajSB for contributing to ankidroid. Can you attach the video describing the fix of this issue?
Done

2022-04-02 13:50 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        mBackButtonPressedToExit = false;
Why do we want `onPause` rather than `onStop`?

2022-04-02 17:35 UTC, UvrajSB commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        mBackButtonPressedToExit = false;
1) Because onPause will cover all the cases of onStop callback as onStop is never called without onPause.
2) In case when a dialog box appears the UI (Activity) is still partially visible and just onPause() is called. So in case the user clicks on the back button and then opens up some dialog box and closes it back (or a dialog box pops up on its own) the count of back presses will not change if we use onStop() so I used onPause()

2022-04-02 22:39 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        mBackButtonPressedToExit = false;
Solid defense, I think I agree with onPause as a choice

2022-04-02 22:40 UTC, mikehardy approved these changes

2022-04-02 22:41 UTC, mikehardy commented
A thought - is this also useful in AbstractFlashcardViewer? It has the same feature - these two locations are the only places it exists tho https://github.com/ankidroid/Anki-Android/blob/c3c42cd59738ec461c805483e91221d7750a92fd/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L235

2022-04-03 07:23 UTC, UvrajSB commented
> A thought - is this also useful in AbstractFlashcardViewer? It has the same feature - these two locations are the only places it exists tho
> 
> https://github.com/ankidroid/Anki-Android/blob/c3c42cd59738ec461c805483e91221d7750a92fd/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L235

According to my understanding,
We don't need to the same thing in this case because
1) In last case i.e. of DeckPicker Activity, we were going to the next activity and coming back but here we are on the same activity and its no longer a problem of the activity stack.
2) Moreover, whenever answer is displayed or question is changed mBackButtonPressedToReturn is set false in the code already
[Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java](https://github.com/ankidroid/Anki-Android/blob/c3c42cd59738ec461c805483e91221d7750a92fd/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L1550)


[Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java](https://github.com/ankidroid/Anki-Android/blob/c3c42cd59738ec461c805483e91221d7750a92fd/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L1584)

2022-04-04 00:33 UTC, UvrajSB commented
I have also resolved issue #10634 in this pr

2022-04-04 00:54 UTC, david-allison commented
Looks good, but please aim for 1 pull request per issue

2022-04-04 11:42 UTC, UvrajSB commented
I have added the time constraint to press the back key second time such that if a user presses back key once and then doesn't presses it under next 2sec (i.e. the time duration of the Toast.LENGTH_SHORT) then the counter of the back press resets itself back to zero.

2022-04-04 11:44 UTC, UvrajSB commented
> A thought - is this also useful in AbstractFlashcardViewer? It has the same feature - these two locations are the only places it exists tho
> 
> https://github.com/ankidroid/Anki-Android/blob/c3c42cd59738ec461c805483e91221d7750a92fd/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L235

@mikehardy 
Yes there also we should add the same time constraint, do you want me to add this it in the same PR or do you want me to open a new issue and then do a pr over there?

2022-04-04 12:37 UTC, mikehardy commented
It's the same feature to me I think keeping it in this PR for consolidated discussion is best
This changes the feature somewhat and I'm not sure if 2sec (even if it has a reference in the duration of the toast) is really what we want. It might be - it very well might be the best value - but I'm curious for other's opinions just in case, since it is qualitative)

2022-04-05 15:55 UTC, mikehardy requested changes
minor change requests, but the java->kotlin migration thing is obviously a major change for the PR, even if it is hopefully easier to handle

This looks good though as a solution the UX issue of otherwise-infinite 2-back-press time window

2022-04-05 15:55 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            }, 2000);
I feel like this should be a constant somewhere and just referenced here. I think we have a Constants file, could put it in there and just statically import it then reference it here

2022-04-05 15:55 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                        mBackButtonPressedToExit=false;
```suggestion
                        mBackButtonPressedToExit = false;
```

2022-04-05 15:55 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                }, 2000);
same thought that this should be a constant. Perhaps we already have a toast length constant, or there is a toast length constant we may refer to, since we are tying it to that?

2022-04-06 22:46 UTC, mikehardy requested changes
something went wrong with the imports? Really made the PR messy unfortunately - can you make sure to *only* change lines of code (or imports) that you absolutely must change for the purpose of the PR?

And I think the name could be better - but the PR is still close

2022-04-06 22:46 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +        return com.ichi2.anki.AnkiDroidJsAPI(this)
I don't understand why this is changed?

2022-04-06 22:46 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +import android.os.*
I don't understand why the imports are changed (vs just adding one)

2022-04-06 22:46 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    /** Time duration for toasy **/
typo

2022-04-06 22:46 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    const val LENGTH_SHORT: Long = 2000
this name is not really descriptive, if it was SHORT_TOAST_DURATION it would be much more descriptive I think?

2022-04-06 22:46 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +import android.provider.SyncStateContract;
why is this import here :thinking:

2022-04-06 22:46 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +import kotlin.io.ConstantsKt;
examine all the imports, I won't comment on all of them but I think you only needed to add Consts

2022-04-06 23:36 UTC, UvrajSB commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +        return com.ichi2.anki.AnkiDroidJsAPI(this)
As I have logged a new issue, where #10734 .
So I had to go to the commit before the one which created the issues and there this thing might have changed most probably. Likewise, for all the extra import and all, it all happened because the file I was working upon changed and the ankidroid:main had issues so I had to search the latest commit which was stable.
And hence during the process of doing it and adding Constant it resulted in many imports than required.
Apologies for it, Ill remove all the clutter

2022-04-07 15:08 UTC, david-allison approved these changes
Code looks good. I'll follow up with a small improvement after some refactoring is done

2022-04-07 15:08 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +            Handler(Looper.getMainLooper()).postDelayed(
`HandlerUtils.executeFunctionWithDelay` would be less code

2022-04-07 15:09 UTC, merged