kotlin cleanup of Reviewer.kt,BasicAudioRecordingFieldController.kt
ankidroid/Anki-Android pull request #10690
Opened 2022-04-03 13:24 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
kotlin cleanup of Reviewer.kt,BasicAudioRecordingFieldController.kt
## Fixes
Fixes some of https://github.com/ankidroid/Anki-Android/issues/10489
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-03 14:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt
> +            mTempAudioPath = generateTempAudioFile(mActivity)!!
`generateTempAudioFile` returns null, we shouldn't be using `!!` here

2022-04-04 06:06 UTC, justdvnsh commented
@Prince-kushwaha The builds are failing. Please ensure that they are fixed. Also, the branch is having merge conflicts. Please make sure to resolve them.

2022-04-04 19:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> -    @KotlinCleanup("improve nextIvlStr - make inner function")
Why are these being removed if they're not being handled?

2022-04-05 02:38 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> -    @KotlinCleanup("improve nextIvlStr - make inner function")
this function is  override function  we not make them inner  function

2022-04-05 03:23 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> -    @KotlinCleanup("improve nextIvlStr - make inner function")
I'd move `mSched!!.nextIvlStr(this, mCurrentCard!!, Consts.BUTTON_ONE)` into an inner function:

`fun nextIvlStr(button: ???) = mSched!!.nextIvlStr(this, mCurrentCard!!, button)`

```
mEaseButton1!!.nextTime = mSched!!.nextIvlStr(this, mCurrentCard!!, Consts.BUTTON_ONE) 
|
V
mEaseButton1!!.nextTime = nextIvlStr(Consts.BUTTON_ONE) 
```

2022-04-06 12:22 UTC, david-allison requested changes

2022-04-06 12:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +    private lateinit var mTextBarNew: TextView
These need to be moved to `onCreate`, otherwise they're called from `onCollectionLoaded`, which may be async

2022-04-06 12:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> -    @KotlinCleanup("tempAudioPath!!")
This wasn't addressed

2022-04-06 12:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> -    @KotlinCleanup("maybe scope function")
This wasn't addressed

2022-04-06 12:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> -    @KotlinCleanup("mCurrentCard handling")
I don't think this was handled

2022-04-06 12:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> -    @KotlinCleanup("mCurrentCard handling")
I don't think this was handled

2022-04-06 12:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.kt
> +                ""
This looks incorrect to me

2022-04-06 12:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt
> -    private var mTempAudioPath: String? = null
Are you sure this is correct?

2022-04-06 12:22 UTC, david-allison commented
In general, I feel there's too many cleanups here to easily review. I'd prefer smaller PRs in future.

2022-04-06 15:27 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt
> -    private var mTempAudioPath: String? = null
i think their is not need to make mTempAudioPath lateinit or non-null

2022-04-06 15:33 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> -    @KotlinCleanup("mCurrentCard handling")
i not understand what i have to do in mCurrentCard handling

2022-04-06 15:34 UTC, Prince-kushwaha commented
> In general, I feel there's too many cleanups here to easily review. I'd prefer smaller PRs in future.

I agree with you

2022-04-13 10:03 UTC, david-allison requested changes

2022-04-13 10:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> -    @KotlinCleanup("mCurrentCard handling")
So don't remove the annotation and leave it for someone else

2022-04-13 10:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> -    @KotlinCleanup("mCurrentCard handling")
ditto

2022-04-13 10:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt
> -    private var mTempAudioPath: String? = null
Both of them can't be non-null currently

2022-04-13 13:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +    private lateinit var mTextBarNew: TextView
This is still an issue

2022-04-13 13:51 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +    private lateinit var mTextBarNew: TextView
it is not possible to move  these variable to oncreate becouse these variable also used outside the Oncreate 
we get errors  Unresolved reference: answerTimer,mTextBarReview

2022-04-13 14:22 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                return true
when i add `return true` outSide(below) the `when` it give Unreachable code error 
i think their is not need to add `return true` outSide(below)  the `when`

2022-04-13 14:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                return true
The problem is that every line has a `return true` except the else. That's a waste.

We can move all but one of the `return true` blocks outside the `when`. this makes it both less code and easier to reason about

2022-04-13 14:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        mTextBarNew = findViewById(R.id.new_number)
I don't see where the associated line of code was removed

2022-04-13 18:30 UTC, david-allison approved these changes

2022-04-13 19:07 UTC, mikehardy approved these changes
much cleaner after this work thanks @Prince-kushwaha

2022-04-13 19:07 UTC, merged