fix: Minibar Flag Inconsistency
ankidroid/Anki-Android pull request #10720
Opened 2022-04-05 21:51 UTC by Kshitij09

Signed-off-by: Kshitij Patil <kshitijpatil98@gmail.com>

## Pull Request template

## Purpose / Description
Due to some refactorings around `AbstractFlashCardViewer`, especially the revision 66300a61a4c91227423308b6492964a7403dd7eb, which extracts Flag/Mark functionality from this Class, a regression bug was introduced which managed to remain unnoticed for quite a few alpha releases. Since we show certain options on the minibar as per their visibility on AppBar, the order in which we toggle their visibility pre/post invalidating Options Menu, causes this bug. This PR proposes a solution that fixes the ordering issue.

## Fixes
Fixes #10691 

## Approach
The refactor performed in the mentioned commit (66300a61a4c91227423308b6492964a7403dd7eb) moved Flag/Mark toggle responsibility to `Reviewer` class from `AbstractFlashCardViewer`. 
1. While most of the method calls shifted to their respective positions in the subclass, one instance of invoking `drawFlag()` & `drawMark()` in the `onPageFinished()` method of `CardViewerWebClient` wasn't taken care of.2. 
1. A call from `fillFlashCard` to `onFlagChanged()` & `onMarkChanged()` was supporting this expectation to some extent but this wasn't covering all the cases which could invalidate the AppBar Options Menu, rendering the minibar flag/mark inconsistent.
1.  `CardViewerWebClient` actually reacts to an url that starts with `signal:flag_` by calling `executeCommand` method of `AbstractFlashCardViewer` but since we've removed the commands handling flag actions from this class (moved to `Reviewer`), it wasn't updating the flag state.

I have added a callback that's invoked from `onPageFinished` which provides a hook for `CardViewer` subclasses to perform required actions (Calling `onFlagChanged()` & `onMarkChanged()` in our case).

## How Has This Been Tested?

As of now, by manually running it on a physical device (Pixel 4a)

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-09 14:39 UTC, Kshitij09 commented
@BrayanDSO @david-allison Could you please have a look at this PR once?

2022-04-13 10:48 UTC, david-allison requested changes
Looks great, pending copyright header

Could you either add a Unit test (which would have previously failed), or a `@NeedsTest` annotation

2022-04-13 10:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/OnPageFinishedCallback.kt
> +interface OnPageFinishedCallback {
This /could/ be an open function on `AbstractFlashvardViewer`, but I prefer this architecturally

2022-04-14 14:58 UTC, mikehardy commented
@BrayanDSO you have a unique combination in that you noticed quite a few of the menu bar issues and you can build the app quickly from the fork/branch of a PR to check PRs if I remember correctly. It would be really useful to check the effect of this PR on the 7-issue multi-bug that is the app bar state right now...

2022-04-14 16:08 UTC, david-allison commented
> Hey, sorry for not getting back on this soon. Where can I find the respective Copyright header for this file? I could see different files have different Years and authors in the header.
> 
> I will think about a unit test for this scenario, but any guidance/reference would be much appreciated

Never any rush. Instructions:

https://github.com/ankidroid/Anki-Android/blob/4745b60d40af443bf0fff4f9d1e39685578ca01b/lint-rules/src/main/java/com/ichi2/anki/lint/rules/CopyrightHeaderExists.java#L61-L72

2022-04-14 16:46 UTC, merged

2022-04-14 17:00 UTC, Kshitij09 commented
Damm! I was late to notice, I am really shocked how this is working but if you check I have added the callback implementation to `AbstractFlashvardViewer` but haven't really passed `this` reference while creating an instance of `CardViewerWebClient` here https://github.com/ankidroid/Anki-Android/blob/bcae6dc760bc981c7c74ce77490d1445849577b2/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt#L1021


Would you mind if I fix this by raising another PR with the suggested change?
cc: @david-allison @mikehardy

2022-04-14 23:59 UTC, BrayanDSO commented
I'm late to the party. Tested it on main and it looks nice! Thanks Kshitj!