Kotlin Cleanup for HelpDialog.kt file
ankidroid/Anki-Android pull request #10747
Opened 2022-04-07 17:28 UTC by Umesh-01

## Pull Request template

## Purpose / Description
Kotlin Cleanup for HelpDialog.kt

## Fixes
Fixes part of #10489 

## Approach
1. Changed val to lateinit var
2. Changed to Kotlin Functional Interface

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-07 17:42 UTC, mikehardy requested changes
Thanks for posting this! I left a couple specific questions

2022-04-07 17:42 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +import com.arcao.slf4j.timber.BuildConfig
I don't understand why this import was added? There are no other changes in the file, so an import addition shouldn't be required unless I am missing something?

2022-04-07 17:42 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
> +            }
func cannot be null can it? I don't see `ActivityConsumer?` I see `ActivityConsumer` so it appears not-null, and then you don't have to use the `!!` later I think

2022-04-07 18:08 UTC, Umesh-01 commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +import com.arcao.slf4j.timber.BuildConfig
It was showing some unexpected [errors](https://github.com/ankidroid/Anki-Android/issues/10489#issuecomment-1091981347) when I opened the project. After importing this everything get resolved.

2022-04-07 18:11 UTC, Umesh-01 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
> +            }
Yes, I also thought the same. But it was showing error over there and suggested to surround it with if else or use `!!` operator.

2022-04-07 18:23 UTC, Umesh-01 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
> +            }
I have checked it again, now it's working. Maybe it was my mistake. And I have done the changes.

2022-04-08 06:42 UTC, Umesh-01 commented
@mikehardy It is showing that `lateinit` is not necessary.

![image](https://user-images.githubusercontent.com/83420185/162373433-60cdf927-c2d8-4004-93d3-760eaef96e3b.png)

when I build project it is showing me this error:

![image](https://user-images.githubusercontent.com/83420185/162374941-795b32f9-991c-4c8a-8c61-e7e696529fbd.png)


And I used `gradlew assemble --stacktrace` command to check what is causing the problem, it was showing me these errors:

![image](https://user-images.githubusercontent.com/83420185/162375062-865ff007-6470-45e5-9719-77fbfe7fc28b.png)


Now, when I removed the `lateinit` keyword then the BUILD is successful. And output looks like this:

![image](https://user-images.githubusercontent.com/83420185/162374445-e39afe3f-d530-4338-9c28-489babe84f75.png)

Should I commit the changes in this PR??

2022-04-08 07:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +import com.arcao.slf4j.timber.BuildConfig
This is incorrect

2022-04-08 07:56 UTC, david-allison commented
Yes, commit them, otherwise we can't review them

Does it need to be a var? Can we make it a val?

2022-04-08 08:00 UTC, Umesh-01 commented
> Yes, commit them, otherwise we can't review them
> 
> Does it need to be a var? Can we make it a val?

Yes, we can make it, should I change it to val??

2022-04-08 08:13 UTC, david-allison commented
Most of the Kotlin cleanup boils down to: "use your best judgement", `val` sounds good here

2022-04-08 08:34 UTC, david-allison approved these changes
Have you tested this?

If it works, looks great!

2022-04-08 08:47 UTC, Umesh-01 commented
> Have you tested this?
> 
> If it works, looks great!

Yes it was working.

2022-04-08 13:44 UTC, mikehardy commented
I want to add something else though - those images are basically illegible to me on a mobile device. If there is a textual error, it's always better to just paste the text in, inside either triple-backticks enclosure or a `>` for quoting like

```
this is some error message I got and it's huge
so it is in a big block
of quoted text
etc
```

or 

> this small line of text was shown

2022-04-08 14:02 UTC, Umesh-01 commented
Okk, got it.

2022-04-09 17:20 UTC, ShridharGoel approved these changes

2022-04-09 21:36 UTC, mikehardy approved these changes
Nice!

2022-04-09 21:36 UTC, merged

2022-06-05 20:59 UTC, mikehardy commented
Hi there! APRIL OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [April 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-04-01..2022-04-30)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of March.

Please note that GSoC contributions are okay for this process. Our philosophy is that our users have donated to AnkiDroid for all contributions. The only PRs that will not go through the OpenCollective process are ones directly related to am accepted GSoC project from a selected participant, since those receive a stipend from GSoC itself.

Please understand that this means the monthly budget we have for payments might be stretched a bit and the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!