@KotlinCleanup("iteration with i") in Preferences.kt done
ankidroid/Anki-Android pull request #10754
Opened 2022-04-08 08:16 UTC by UvrajSB

## Pull Request template

## Purpose / Description
KotlinCleanup("iteration with i") in Preferences.kt

## Fixes
Part of #10489

## Approach
Converted the map into list with elements as (key, value) and then used "items.toList()[i - 1].first" to obtain key and "items.toList()[i - 1].second" to obtain its value and then used it in for loop with "i" as iterator.

## How Has This Been Tested?
I have tried to create similar code on Kotlin Playground to test it
![image](https://user-images.githubusercontent.com/73571511/162394323-3d47ba86-cb13-4f6a-a9ca-99a24e3faef8.png)

![image](https://user-images.githubusercontent.com/73571511/162394372-cf089bf9-6b21-4379-867f-31fa8537f181.png)

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-08 08:24 UTC, david-allison requested changes

2022-04-08 08:24 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +                    languageDialogLabels[i] = items.toList()[i - 1].first
Calling toList on each iteration is inefficient. Extract it outside the loop if it's immutable

2022-04-08 08:29 UTC, UvrajSB commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +                    languageDialogLabels[i] = items.toList()[i - 1].first
Yes, keeping it outside will make it actually much more efficient.

2022-04-08 08:30 UTC, UvrajSB commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +                    languageDialogLabels[i] = items.toList()[i - 1].first
Also, I checked this change also on Kotlin Playground, it works 
![image](https://user-images.githubusercontent.com/73571511/162397212-06e8b484-a6f3-47f5-954f-8f76757b8017.png)

![image](https://user-images.githubusercontent.com/73571511/162397259-66d92eb5-2e93-40be-b53a-85026eef101d.png)

2022-04-08 08:32 UTC, david-allison requested changes

2022-04-08 08:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +                for (i in 1..items.size) {
Doesn't this skip the final element?

Typically you want `itemsList.size`

2022-04-08 09:00 UTC, UvrajSB commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +                for (i in 1..items.size) {
1) I don't think that it skips the last element 
2) The value of itemsList.size will be equal to items.size
![image](https://user-images.githubusercontent.com/73571511/162402618-42a4a6de-b150-44d9-b6af-d59e1acf3f24.png)

2022-04-08 09:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +                for (i in 1..items.size) {
You're right - first one is fine.

For the second one: it's good practice to use the collection that you're iterating over in a loop

2022-04-08 10:01 UTC, UvrajSB commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +                for (i in 1..items.size) {
Understood, change made!!

2022-04-09 07:08 UTC, UvrajSB commented
@david-allison are any further changes required in this PR?

2022-04-09 09:06 UTC, david-allison approved these changes
Awesome!

2022-04-09 16:52 UTC, ShridharGoel approved these changes

2022-04-09 16:53 UTC, merged

2022-04-09 21:20 UTC, mikehardy commented
@krmanik I love your github bot, thanks again for doing that