Cleanup compat v21
ankidroid/Anki-Android pull request #10750
Opened 2022-04-07 20:51 UTC by Jatin887

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-08 08:10 UTC, david-allison requested changes
Please rebase this and follow the migration guide: https://github.com/ankidroid/Anki-Android/blob/main/docs/kotlin-migration.md

I'd strongly recommend starting from scratch here. This also isn't the easiest class to start with from a migration perspective

2022-04-08 10:10 UTC, oyeraghib commented
@Jatin887 I think compatV21.java is not one of those files which can be easily migrated to Kotlin without proper code changes. You might need to see the whole functionality of the code written in that file and maybe re-write some part of it again Kotlin.

2022-04-08 14:35 UTC, Jatin887 commented
> @Jatin887 I think compatV21.java is not one of those files which can be easily migrated to Kotlin without proper code changes. You might need to see the whole functionality of the code written in that file and maybe re-write some part of it again Kotlin.

What changes should I supposed to do? because when I changed it to kotlin the project was successfully build. and i have one more doubt there are many async function should I change one of them to coroutines because it's a whole project for gsoc so should I add a proposal for that or should I open a pr?

2022-04-08 14:36 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +    public static boolean isAcraEnabled(@SuppressLint("UnknownNullness") Context context, boolean defaultValue) {
I didn't get you what kind of value it supposed to be have . Can you please explain a little more ?

2022-04-09 07:30 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +    public static boolean isAcraEnabled(@SuppressLint("UnknownNullness") Context context, boolean defaultValue) {
> It'd be ideal if we decided on a value rather than ignored it

i updated it in the new commit plese check

2022-04-09 09:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +    public static boolean isAcraEnabled(@SuppressLint("UnknownNullness") Context context, boolean defaultValue) {
Please note the 'main' message on the review. I feel it would be easier to start from scratch to get this PR to a mergeable state.

2022-04-10 14:22 UTC, oyeraghib commented
@Jatin887 yes you are right. There are few async functions in that. You can add proposal if you want to apply for GSOC but make sure if you meet all the requirements. Or you can wait until someone starts working with Coroutines for AnkiDroid and then you can make changes to it or add a pull request. 
I would better recommend you to join the Anki Droid discord server and discuss with other devs there.

2022-04-10 14:35 UTC, divyansh-dxn commented
Hi @Jatin887, thank you for your contributions. Please try to follow the migration guidelines properly, for migration you should only be changing required files. I don't think changes in Project.xml are significant here.
And also as mentioned in the guideline, a Kotlin migration should contain exactly two commits.
Following the guidelines, helps maintainers review your changes easily. And I agree with @oyeraghib , you should be joining our discord channel.

2022-04-10 14:40 UTC, divyansh-dxn commented
Also you should be using the kotlinMigration.gradle file for migrating. I didn't see anything such in your commit.

2022-04-10 18:56 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +    public static boolean isAcraEnabled(@SuppressLint("UnknownNullness") Context context, boolean defaultValue) {
> It'd be ideal if we decided on a value rather than ignored it

It was not there initially i just changed it to remove the error then i realised it wasn't needed so i updated it in the new commit

2022-04-10 19:43 UTC, Jatin887 commented
> Hi @Jatin887, thank you for your contributions. Please try to follow the migration guidelines properly, for migration you should only be changing required files. I don't think changes in Project.xml are significant here. And also as mentioned in the guideline, a Kotlin migration should contain exactly two commits. Following the guidelines, helps maintainers review your changes easily. And I agree with @oyeraghib , you should be joining our discord channel.

yes! you are right but i didn't make any changes in project.xml. Intially there was some problem with my android studio version so after updating it i guess it added those lines automatically in project.xml . These lines implements kotlin official code styles.
but as you are saying it's not needed i will change it in my next commit. Apologies for the same i didn't check in my initial commit. and reagrding the commits i will keep that in mind from the next time the number of commits will not go above two.
I already joined the discord channel

2022-04-11 05:00 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
> -    public static final int FLAG_MUTABLE = 1 << 25;
Why did the definition of both flags disappear?

2022-04-11 05:00 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
> -    public static final int FLAG_MUTABLE = 1 << 25;
Why did the definition of both flags disappear?

2022-04-11 05:08 UTC, Arthur-Milchior commented
Welcome @Jatin887 

In case you do not know, git allow for interactive rebase. That is, you can squash all commits in a single commits. Then you can follow the instruction given in the migration page mentioned by @divyansh-dxn and @david-allison. 
David mentioned that starting from scratch may be easier, and I slightly agree with him. At this point, it may be easier to restart than to correct the current state. @oyeraghib mentioned that Compat21 is a complex file, and he is totally right. The compat folder is the only one dealing with various level of API, so it's really not an easy place to start. If the job is done right, that will be extremely appreciated. However, if you already find complex to follow the migration instruction, then I'd advise working on a simpler file first.
In any case, to be frank, until the PR has exactly two commits as we require, we will not merge it. Personally, I won't even spend time reviewing it, because https://github.com/ankidroid/Anki-Android/pull/10750/files does not show the diff between two files, while usually, with the technique we devised, git diff shows something relatively helpful

2022-04-11 21:29 UTC, Jatin887 commented
> Welcome @Jatin887
> 
> In case you do not know, git allow for interactive rebase. That is, you can squash all commits in a single commits. Then you can follow the instruction given in the migration page mentioned by @divyansh-dxn and @david-allison. David mentioned that starting from scratch may be easier, and I slightly agree with him. At this point, it may be easier to restart than to correct the current state. @oyeraghib mentioned that Compat21 is a complex file, and he is totally right. The compat folder is the only one dealing with various level of API, so it's really not an easy place to start. If the job is done right, that will be extremely appreciated. However, if you already find complex to follow the migration instruction, then I'd advise working on a simpler file first. In any case, to be frank, until the PR has exactly two commits as we require, we will not merge it. Personally, I won't even spend time reviewing it, because https://github.com/ankidroid/Anki-Android/pull/10750/files does not show the diff between two files, while usually, with the technique we devised, git diff shows something relatively helpful

Ok! I will squash all commits and will start working on it from scratch.

2022-04-19 12:31 UTC, mikehardy commented
I marked this as draft, which is a strong signal that it is not ready.
You have done this

> [](https://github.com/Jatin887)@[Jatin887](https://github.com/Jatin887) Jatin887 marked this pull request as ready for review [4 days ago](https://github.com/ankidroid/Anki-Android/pull/10750#event-6440310803)

without actually pushing any changes. I don't understand what signal you are trying to send, but the signal I heard was "you should look at this again", but since there were no actual changes it was not a valid use of my time

2022-05-11 02:53 UTC, lukstbit commented
@mikehardy This can be closed as it was already done in #11074

2022-05-11 03:06 UTC, closed without merging