feat(scoped-storage): Refactorings and Storage Locking
ankidroid/Anki-Android pull request #10777
Opened 2022-04-11 00:13 UTC by david-allison

## Pull Request template

## Purpose / Description
I want to add a "Migrate Essential Files" PR, and smaller refactorings and Storage locking makes this a smaller PR when it goes in.

## Fixes
Associated with #5304

## Approach
* `isLegacySotrage`: move to ScopedStorageService, fix & refactor
* Add `Storage.lockCollection`
* Make it easier to create a `Directory`

## How Has This Been Tested?
Unit Tested, the end result is tested on my Android 11

## Learning (optional, can help others)
FileChannel.lock did not lock an Anki Database on macOS

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-11 12:16 UTC, BrayanDSO reviewed
Looks great overall.
Commented on some typos and a question about the implementation.

2022-04-11 12:16 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
> +
The logic seems correct. But right now I can only guess what is the purpose of this. What is your intention with it? Make a throwable "soft" lock?

This isn't a proper SQLite lock like the one made by the backend. So one needs to have in mind this is a "soft" lock only made for AnkiDroid insides, which is only obvious if someone reads the implementation since there isn't any sign of it on the methods' docs, especially with it saying that it throws an `SQLiteDatabaseLockedException`

Is this new throw going to be handled in some way, as the current database locked dialog on `DatabaseErrorDialog` or is it supposed to throw in some context of the scoped migration?

2022-04-13 00:09 UTC, mikehardy requested changes
I have a small concern about synchronization, but you will either explain to me how it's not a problem (it might not be a problem :-) ) or just try the classic AtomicBoolean idiom I think ?

2022-04-13 00:09 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
> +
Yep - not ideal but I remember discussing it with you. There's no literature on it that I can see in robolectric guides or issues / PR lists, or on stackoverflow, but the locking behavior is definitely different by OS, and that's not okay for tests. I agree with the general idea this is not great then, but good enough

2022-04-13 00:09 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
> +    private static boolean sIsLocked = false;
Out of curiosity, I can't see how it could happen but this seems like the classic case for AtomicBoolean - https://developer.android.com/reference/java/util/concurrent/atomic/AtomicBoolean#compareAndSet(boolean,%20boolean) - if not, then it seems like the methods should at least be synchronized ?

2022-04-13 00:09 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/libanki/StorageLockingTest.kt
> +    }
without synchronization, if you had two threads and set up a race, I bet the results would occasionally be two opens happen

2022-04-13 00:22 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/StorageLockingTest.kt
> +    }
Our access to the collection: `CollectionHelper.getCol` is synchronized.

This is safe in our use case. I don't actually believe it's possible to be safe without a call to `getCol` afterwards to ensure that the collection actually is locked.

https://github.com/ankidroid/Anki-Android/pull/10799/commits/74e0683f3e0f70d5af52fb83a070c91041a70288#diff-413f3b08b9928ac38e3b27bc1e924669ad6537c4f2c792a858d3c7083cd78438R231-R240

Looking for advice here: I believe the code above is bulletproof, I'd like to move this closer to the source if possible, but that risks introducing a libAnki -> CollectionHelper dependency.

2022-04-13 00:28 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/libanki/StorageLockingTest.kt
> +    }
Yeah - I just reviewed that PR, I think with the lock / re-try stuff in there, it should be safe? I can accept that.

2022-04-13 00:29 UTC, mikehardy approved these changes
linked PR does a lot of check/lock/re-check, it ...should be safe

2022-04-13 12:22 UTC, Arthur-Milchior approved these changes
Fine to merge by me. Two really small change I'd like in comment, fine by me to do it in a next PR

2022-04-13 12:22 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/testutils/FileSystemUtils.kt
> + * @param extension The file extension. Does not require a "."
> Must not contain a "."

With this statement, it seems like the . is optional, nto that it is forbidden

2022-04-13 12:22 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
> +    private static boolean sIsLocked = false;
I'd love a comment explain what exactly is locked.
I'd thought that the whole storage access is locked, but that would mean that you can't access media or database. 
While in this case, it only limits accessing the collection through Storage. It don't limit anything on already existing collection

2022-04-13 15:29 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
> +    private static boolean sIsLocked = false;
I wish there was a diff view between two commit hashes from a force push :-), Anyway if this looks good @Arthur-Milchior - do the merge 🙏 - thanks!

2022-04-13 16:02 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
> +    private static boolean sIsLocked = false;
This wasn't modified in the force push, still pending

2022-04-13 16:16 UTC, Arthur-Milchior commented
I don't get it. @david-allison , you are waiting for feedback from yourself? Or does the tag now changed meaning?

2022-04-13 16:27 UTC, mikehardy commented
> I don't get it. @david-allison , you are waiting for feedback from yourself? Or does the tag now changed meaning?

I was unclear as well - asked him on Discord :-)

2022-04-14 08:28 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
> +    private static boolean sIsLocked = false;
@mikehardy you can go to `https://github.com/ankidroid/Anki-Android/compare/7e44aa7ae2c6df7dba5816fae09619a5591499de..e918ee7166e07443bc472a8303d448868f1c53be`
Essentially, our URL, /compare/hash1..hash2. 

While it certainly is not ideal, as you need the full commit of both, it's not very long to get

2022-04-14 14:24 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
> +    private static boolean sIsLocked = false;
Okay - going to say this is just wait for feedback / pending merge - trusting you to successfully add the comments requested since that's pretty easy. Then can merge and keep moving 🚜

2022-04-14 17:02 UTC, david-allison commented
Updated the comments in `Storage`, pending CI, or a second review of the comments

2022-04-14 18:12 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
> +    private static boolean sIsLocked = false;
Documentation is quite detailed now! I was thoroughly unable to get a compare of the diff for just the last force push with your URL pointers Arthur but I'll try again another time

2022-04-14 18:43 UTC, merged