Add a tools/migrate.sh file for Kotlin migration
ankidroid/Anki-Android pull request #10779
Opened 2022-04-11 05:56 UTC by Arthur-Milchior

Once actual code migration is done, once the code compiles correctly, tests
passes, and before any commit is done, run `tools/migrate.sh`. This will create the
two commits, as we want them in the migration process.

I tested it with a PR I'll post in a moment

2022-04-11 06:27 UTC, lukstbit commented
@Arthur-Milchior In #10780 , in the first commit `className` doesn't start with `/`.

2022-04-11 06:43 UTC, Arthur-Milchior commented
> @Arthur-Milchior In #10780 , in the first commit `className` doesn't start with `/`.

Thanks a lot. I missed that.
Corrected.

2022-04-11 11:43 UTC, Arthur-Milchior commented on tools/migrate.sh
> +sed -i "s:def className = .*:def className = \"\":" AnkiDroid/kotlinMigration.gradle
Corrected.
However, this means I know need to use bash instead of sh. Not perfect, but i still hope it'll work on most machines.
I don't know how to search for pattern without [[

2022-04-11 15:21 UTC, david-allison requested changes
<details><summary>macOS run</summary>

```
davidallison@Davids-MBP Anki-Android % gh pr checkout 10779
remote: Enumerating objects: 1160, done.
remote: Counting objects: 100% (942/942), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 1160 (delta 940), reused 942 (delta 940), pack-reused 218
Receiving objects: 100% (1160/1160), 1.29 MiB | 1.01 MiB/s, done.
Resolving deltas: 100% (1002/1002), completed with 81 local objects.
From https://github.com/ankidroid/Anki-Android
 * [new ref]             refs/pull/10779/head -> migrate
 * [new tag]             v2.16alpha56         -> v2.16alpha56
Switched to branch 'migrate'
davidallison@Davids-MBP Anki-Android % ./tools/migrate.sh  
        AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt is the new file
AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics is the base
AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java is the deleted file
UsageAnalytics is the file name
SOURCE=MAIN
/com/ichi2/anki/analytics/UsageAnalytics is the path in source
Saved working directory and index state WIP on migrate: 85da78f76 Add a tools/migrate.sh file for Kotlin migration
stash
sed: 1: "AnkiDroid/kotlinMigrati ...": invalid command code A
sed: 1: "AnkiDroid/kotlinMigrati ...": invalid command code A
No Kotlin staged files. Hence, skipping pre-commit Ktlint run.
AnkiDroid/src/main/assets/scripts/card.js 54ms
Completed npx prettier run.
Completed the pre-commit hook.
[migrate 86c78925c] rename UsageAnalytics.java to .kt\n\n/com/ichi2/anki/analytics/UsageAnalytics
 1 file changed, 0 insertions(+), 0 deletions(-)
 rename AnkiDroid/src/main/java/com/ichi2/anki/analytics/{UsageAnalytics.java => UsageAnalytics.kt} (100%)
first commit
rm 'AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt'
On branch migrate
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerAnalyticsOptInDialog.kt

Dropped refs/stash@{0} (ec2ea39d8f61908b801c6a64f527c5f3abf1e559)
sed: 1: "AnkiDroid/kotlinMigrati ...": invalid command code A
sed: 1: "AnkiDroid/kotlinMigrati ...": invalid command code A
Running Ktlint over these files:
AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerAnalyticsOptInDialog.kt
Completed ./gradlew ktlintFormat run.
AnkiDroid/src/main/assets/scripts/card.js 62ms
Completed npx prettier run.
Completed the pre-commit hook.
[migrate 840ab2d63] Convert UsageAnalytics.kt to Kotlin\n\n/com/ichi2/anki/analytics/UsageAnalytics
 2 files changed, 250 insertions(+), 252 deletions(-)
second commit
davidallison@Davids-MBP Anki-Android % 

```

**issues**

```
sed: 1: "AnkiDroid/kotlinMigrati ...": invalid command code A
sed: 1: "AnkiDroid/kotlinMigrati ...": invalid command code A
```

Commit message is:
```
rename UsageAnalytics.java to .kt\n\n/com/ichi2/anki/analytics/UsageAnalytics
```

* Commit message users `/` rather than `.` in the package name
* `kotlinMigration.gradle` isn't modified

2022-04-11 15:21 UTC, david-allison commented on tools/migrate.sh
> +# This file assumes that a single file was converted from java to kotlin, and
This wants instruction at the start of the file, ideally with bullet points.

2022-04-12 06:46 UTC, Arthur-Milchior commented
Do you know what differs on mac and linux?
 I don't understand the sed message.

I'd be fine stating that this is the tool for linux user and someone knowing more about mac then editing the tool or creating a new one following mac standard

2022-04-13 12:30 UTC, Arthur-Milchior commented
@BrayanDSO If I understand correctly, does it mean the script worked directly on windows? You didn't have to change anything with it? I clearly would not have expected it. 

I added a test that should fail on mac with a clear message. 

I was not specifically asking you to correct it David, I hope we can find other people knowing scripts and mac here and who don't like repetitive work

2022-04-13 13:20 UTC, BrayanDSO commented
> @BrayanDSO If I understand correctly, does it mean the script worked directly on windows? You didn't have to change anything with it? I clearly would not have expected it.

That's correct. I haven't changed a single character in the script. Neither I had to configure anything on my PC. I just ran it and it worked perfectly. Thank you for the script, it's really, really nice.

IIRC, I have never changed my Git BASH settings, so they should be the default ones.

2022-04-14 20:48 UTC, Arthur-Milchior commented on tools/migrate.sh
> +if ["$OSTYPE" == "darwin"];
Thanks. Corrected

2022-04-14 20:49 UTC, Arthur-Milchior commented on tools/migrate.sh
> +if ["$OSTYPE" == "darwin"];
Even if hopefully @mikehardy may help avoid this second commit altogether

2022-04-15 00:34 UTC, david-allison requested changes

2022-04-15 00:34 UTC, david-allison commented on tools/migrate.sh
> +elif [[ $FILEPATH == *AnkiDroid/androidTest/test* ]];
this path is untested in `kotlinMigration.gradle` and should be before this script is released (as people won't look to see this in the file)

The path looks incorrect (`AnkiDroid/src/androidTest`)

2022-04-15 00:34 UTC, david-allison commented on tools/migrate.sh
> +    exit 1
should exit 1 with a reason

2022-04-15 00:34 UTC, david-allison commented on tools/migrate.sh
> +git commit -am "Convert $FILENAME.kt to Kotlin
This no longer lists the package, I'm fine with this.

```
Convert X.kt to Kotlin

com.ichi2.package.X
```

2022-04-15 00:34 UTC, david-allison commented on tools/migrate.sh
> +git commit -am "Convert $FILENAME.kt to Kotlin
We may want a `refactor: ` suffix on both the PR titles

2022-04-15 19:23 UTC, Arthur-Milchior commented on tools/migrate.sh
> +git commit -am "Convert $FILENAME.kt to Kotlin
Do you mean "commit" title?

2022-04-15 19:25 UTC, david-allison commented on tools/migrate.sh
> +git commit -am "Convert $FILENAME.kt to Kotlin
Yes, sorry (I also use this for the PR title)

2022-04-15 19:26 UTC, Arthur-Milchior commented on tools/migrate.sh
> +elif [[ $FILEPATH == *AnkiDroid/androidTest/test* ]];
What does it mean to test it? You mean converting a androidTest file?

2022-04-15 19:51 UTC, Arthur-Milchior commented on tools/migrate.sh
> +    exit 1
Done

2022-04-15 19:52 UTC, Arthur-Milchior commented on tools/migrate.sh
> +git commit -am "Convert $FILENAME.kt to Kotlin
In case you missed it, the line you commented don't have a " ending it.
The package name appears two lines below, in the commit message

2022-04-15 19:53 UTC, Arthur-Milchior commented on tools/migrate.sh
> +git commit -am "Convert $FILENAME.kt to Kotlin
In case you missed it, the line you commented don't have a " ending it.
The package name appears two lines below, in the commit message

2022-04-15 19:53 UTC, david-allison commented on tools/migrate.sh
> +elif [[ $FILEPATH == *AnkiDroid/androidTest/test* ]];
Yes, this code path hasn't been used for `androidTest`

https://github.com/ankidroid/Anki-Android/blob/d3ede33b297f5824b1d3d98ccafec39375633f5a/AnkiDroid/kotlinMigration.gradle#L51

2022-04-15 19:54 UTC, david-allison commented on tools/migrate.sh
> +git commit -am "Convert $FILENAME.kt to Kotlin
Oh, I did

2022-04-15 20:21 UTC, Arthur-Milchior commented
I've added test that there is a single deleted/added file and that it's the same file name appart from kt/java extension. As I can imagine that it may be your next safety request

I've a main question. Do you foresee any issue here?
Because, in the best case, people win time. In the worst, e.g. on mac, people can see use the old system. It's not like with Scoped Storage where we can lose a lot of people data.
Since Kotlin migration are still occurring, I would have expected that merging this quickly to save time to people who can use it, and then improving depending on pain point (or simply adding mac test in a different PR) would be acceptable and a better outcome for the contributors

2022-04-15 21:01 UTC, Arthur-Milchior commented on tools/migrate.sh
> +elif [[ $FILEPATH == *AnkiDroid/androidTest/test* ]];
I'd be happy to deactivate this path in the script right now and have the script available for the two tested directories. Or put a warning, or fail.
It make no sens not to let developers win time and delay more because a path may break. It's not like it was end-users or data will be lost if one path do not exists

2022-04-16 00:30 UTC, david-allison commented
I'd like to merge this quickly. Remove `androidTest` as that's buggy and I'd love to see it in ASAP

2022-04-16 22:18 UTC, Arthur-Milchior commented
Changed.
However, I don't know what to tell to user in this case. Should we state to just do a single commit? Should we ask them to try to correct ankidroidTest to work with the two-commit pr?

2022-04-16 23:00 UTC, david-allison commented
Definitely tell them to correct it

2022-04-16 23:01 UTC, david-allison approved these changes
Can't test it, so relying on reviewer 2 a lot here

2022-04-16 23:14 UTC, Arthur-Milchior commented
Right now it just fails and state that we don't yet support androidTest

2022-04-16 23:51 UTC, david-allison commented
I'm fine with that

2022-04-17 07:06 UTC, raymondwzeng commented on tools/migrate.sh
> +if ["$OSTYPE" =~ ^darwin];
Minor hiccup on my system, though it could be just a "me" thing on MinGW. I had to add a second set of brackets surrounding this if statement (and add a space after ^darwin) in order for the script to run.

2022-04-17 11:12 UTC, BrayanDSO commented
0f46138e01c0dd8aec43d5d3dc00cf65017a6c67 is the last commit that works correctly here on my Windows PC. 
After it, the file isn't renamed on the first commit, only `kotlinMigration.gradle` is changed

2022-04-17 21:53 UTC, Kshitij09 commented
I fixed it for the macOS. Please try this script on other platforms https://github.com/Arthur-Milchior/Anki-Android/pull/2

2022-04-17 22:17 UTC, raymondwzeng commented
Deleted my last comment.

Oddly enough, the script ran successfully without issue today (and starting fresh following nuking the FUBAR'd branch). The previous issue was due to the parser interpreting the `[` in the MacOS if statement as an instruction. Windows 10, 21H1.

2022-04-20 10:59 UTC, Arthur-Milchior commented
Thanks a lot @Kshitij09. I pushed (keeping you as author of the commit change)

I didn't know bak, thanks for adding it too, always nice to have backup.

@raymondwzeng since that deletes the line that created the issue, I won't spend time on it

2022-04-20 11:13 UTC, david-allison reviewed
Still not working on my mac

* A Kotlin conversion is staged

```
./tools/migrate.sh
DELETED=''
NB_DELETED=
FILEPATH=''
Deleted file is not Java
```

2022-04-21 06:18 UTC, Kshitij09 commented
@david-allison it's not working even with my changes? It did work on my mac. Can you share the steps you followed and file you tried to migrate

2022-04-22 13:24 UTC, mikehardy commented
Can we just make this work where it works and fail fast where it doesn't?
This is a lot of effort for a temporary tool with a modest time savings in my opinion. I'd like to clear it from the queue

2022-04-23 19:51 UTC, david-allison commented
Can we put this through one more test, the last time I recall, this didn't modify `kotlinMigration`: https://github.com/ankidroid/Anki-Android/pull/10925

I don't mind that it doesn't work on my Mac. That's not blocking.

2022-04-23 19:53 UTC, david-allison commented
Tested. Now works.

2022-04-23 21:05 UTC, merged

2022-04-23 21:06 UTC, mikehardy commented
Nice!