[@KotlinCleanup] file AutoSizeCheckBoxPreference.kt
ankidroid/Anki-Android pull request #10775
Opened 2022-04-10 21:53 UTC by Jatin887

## Pull Request template

## Purpose / Description
Kotlin cleanup of file AutoSizeCheckBoxPreference.kt

## Fixes
Issue [https://github.com/ankidroid/Anki-Android/issues/10489]

## Approach
Using lint removed all the unnecessary error

## How Has This Been Tested?
By mannualy bulding the project
## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-11 05:20 UTC, Akshay0701 commented
@Jatin887 @UvrajSB both of you made pr on the same issue, 

while I definitely appreciate your efforts but before working on any issues, it's good practice to get that issue assigned to yourself and then make a pr.

2022-04-11 05:58 UTC, Jatin887 commented
@david-allison please review the pr

2022-04-11 21:33 UTC, david-allison reviewed
Seems good. Are some issues remaining? You haven't removed the annotation

2022-04-11 21:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.kt
>  @KotlinCleanup("auto-lint (except unused class)")
This wasn't removed

2022-04-11 21:50 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.kt
>  @KotlinCleanup("auto-lint (except unused class)")
What the @Suppress("deprecation")?

2022-04-11 21:57 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.kt
>  @KotlinCleanup("auto-lint (except unused class)")
The annonation is required because otherwise it shows 
![image](https://user-images.githubusercontent.com/71597104/162840154-a04f6b55-48bc-47dd-8401-8d1112b26afc.png)

2022-04-11 22:24 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.kt
>  @KotlinCleanup("auto-lint (except unused class)")
No, the KotlinCleanup

2022-04-11 22:30 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.kt
>  @KotlinCleanup("auto-lint (except unused class)")
removed now please check

2022-04-12 00:01 UTC, david-allison requested changes
Thanks! Probably the last round of fixes

2022-04-12 00:01 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.kt
> +@Suppress("DEPRECATION")
Why was this changed?

```suggestion
@Suppress("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/5019
```

2022-04-12 00:01 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.kt
> +class AutoSizeCheckBoxPreference : CheckBoxPreference {
```suggestion
class AutoSizeCheckBoxPreference : android.preference.CheckBoxPreference {
```

2022-04-12 03:17 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.kt
> +class AutoSizeCheckBoxPreference : CheckBoxPreference {
@david-allison all the changes are done . please review the pr

2022-04-12 10:39 UTC, david-allison commented
One change in my requests remaining

2022-04-12 18:30 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.kt
> +@Suppress("deprecation")
```suggestion
@Suppress("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/5019
```

2022-04-12 18:32 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.kt
> +@Suppress("deprecation")
@david-allison is all changes done?
can i squash all commits?

2022-04-12 18:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.kt
> +@Suppress("deprecation")
we can, but it'd be ideal if you did first so the commit message is 100% relevant.

2022-04-12 18:36 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.kt
> +@Suppress("deprecation")
ok

2022-04-12 18:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.kt
> +package com.ichi2.ui
Could you revert this change - not necessary

2022-04-12 18:45 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.kt
> +@Suppress("deprecation")
Just this one left

2022-04-12 18:59 UTC, Jatin887 commented
@david-allison squash all the commits please check

2022-04-12 19:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.kt
> +@Suppress("deprecation")
This is still pending

2022-04-12 19:29 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.kt
> +@Suppress("deprecation")
is it solved in the new commit? so i can squash if it's done

2022-04-12 20:03 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.kt
> +@Suppress("deprecation")
@david-allison i think all changes are done
Can i go ahead and squash all commits?

2022-04-12 21:34 UTC, david-allison approved these changes
Looks great, thanks!

2022-04-12 23:34 UTC, mikehardy approved these changes
Great thanks!

2022-04-12 23:58 UTC, merged