Migration of Text importer
ankidroid/Anki-Android pull request #10780
Opened 2022-04-11 05:56 UTC by Arthur-Milchior

What really matters here is that both commits are done with #10779

2022-04-11 11:00 UTC, david-allison requested changes
ClassName is incorrect. See comment above the line in kotlinMigration for the expected format

I'm on my phone and it won't let me comment on the commit

2022-04-11 12:22 UTC, david-allison commented on AnkiDroid/kotlinMigration.gradle
> +def className = "/AnkiDroid/src/main/java/com/ichi2/libanki/importer/TextImporter.kt"
/com/ichi2/libanki/importer/TextImporter.kt

2022-04-11 12:24 UTC, david-allison requested changes
Looks good, very few comments

2022-04-11 12:24 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/TextImporter.kt
> +                mTagstoadd = tags.split(" ".toRegex()).toTypedArray()
cleanup: doesn't need regex

2022-04-11 12:24 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/TextImporter.kt
> +        mTagstoadd = emptyArray()
cleanup: inline

2022-04-13 15:32 UTC, mikehardy commented
Appears to have taken a legitimate (non-flake) emulator test failure:

```
com.ichi2.anki.tests.libanki.ImportTest > testCsv[TestingAVD(AVD) - 11] FAILED 
	java.lang.AssertionError:
	Expected: iterable containing ["‘多すぎる too many fields’ had 3 fields, expected 2", "‘not, enough, fields’ had 1 fields, expected 2", "Appeared twice in file: 飲む", "Empty first field:  to play", "5 notes added, 0 notes updated, 0 notes unchanged."]
```

I re-ran emulator tests just in case it was a flake though.

It is marked as "waiting for feedback" not sure what the actual status is, and it will depend a little bit on emulator CI passing or not (if it fails again it's definitely "waiting for feedback", otherwise it might be "ready for review" again?

2022-06-25 12:46 UTC, closed without merging