Preference extensions test
ankidroid/Anki-Android pull request #10784
Opened 2022-04-11 13:23 UTC by Arthur-Milchior

Yet another test of https://github.com/ankidroid/Anki-Android/pull/10779

2022-04-11 19:55 UTC, david-allison requested changes
Some fixes, some cleanups

commit messages still need work

2022-04-11 19:55 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.kt
> +    private val mMockPreferences: SharedPreferences? = null
cleanup: see if we can `lateinit` the `@Mock`s

2022-04-11 19:55 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.kt
> +        Mockito.`when`(mMockPreferences!!.contains(VALID_KEY)).thenReturn(true)
cleanup: `whenever`

2022-04-11 19:55 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.kt
> +        Mockito.`when`(mMockEditor!!.putString(ArgumentMatchers.anyString(), ArgumentMatchers.anyString())).thenReturn(mMockEditor)
fix: import `ArgumentMatchers`

2022-04-11 19:55 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.kt
> +        Assert.assertEquals(ret, VALID_RESULT)
fix: import `Assert`

2022-05-11 02:56 UTC, lukstbit commented
@mikehardy Can be closed because it was already done in #11241

2022-05-11 03:06 UTC, closed without merging