Migrate AnkiDroid/src/main/java/com/ichi2/libanki/importer/Importer.java
ankidroid/Anki-Android pull request #10781
Opened 2022-04-11 06:12 UTC by Arthur-Milchior

The goal is to create a new test of #10779 ,

2022-04-11 06:39 UTC, Arthur-Milchior commented
I don't get it. `./gradlew ktlintCheck` don't fail while 

> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/libanki/importer/Importer.kt:29: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki.lint]
    protected var mNeedDelimiter = false
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

is a lint error

2022-04-11 13:46 UTC, david-allison commented
> ktlintCheck

needs `gradlew lint` as well

2022-04-11 13:55 UTC, david-allison requested changes

2022-04-11 13:55 UTC, david-allison commented on AnkiDroid/kotlinMigration.gradle
> +def className = "/AnkiDroid/src/main/java/com/ichi2/libanki/importer/Importer.kt"
Was this commit tested? Should have failed

`/com/ichi2/libanki/importer/Importer.kt`

2022-04-11 13:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Importer.kt
> + */
Fix the newlines. No changes should occur in a copyright header

2022-04-11 13:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Importer.kt
> +    fun setProgressCallback(progressCallback: TaskManager.ProgressCallback<String>?) {
cleanup: convert to property

2022-04-11 13:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.kt
>          val mDue: Long = 0
What's happening here? I don't see how this would be affected if there's no inheritance

2022-04-11 13:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.kt
> -    private val mNeedMapper = true
This is a functional change, previously we shadowed the variable, now we set it.

I think this is going to be correct, but we should re-test the functionality.

2022-04-11 13:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.kt
>          mTagsMapped = false
What's happening here?

2022-04-11 13:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +            getLog().add(getRes().getString(R.string.import_succeeded_but_check_database, e.getLocalizedMessage()));
No. It was converted to `log`, which failed compilation.

I'm fine with doing other file first. Honestly, I just took a random file to test my script, which was what I really care about.

2022-04-13 10:31 UTC, david-allison commented
Supersedes #10304

2022-04-13 15:33 UTC, mikehardy commented
emulator CI failure, similar to other PR 🤔 

```

com.ichi2.anki.tests.libanki.ImportTest > testCsv[TestingAVD(AVD) - 11] FAILED 
	java.lang.AssertionError:
	Expected: iterable containing ["‘多すぎる too many fields’ had 3 fields, expected 2", "‘not, enough, fields’ had 1 fields, expected 2", "Appeared twice in file: 飲む", "Empty first field:  to play", "5 notes added, 0 notes updated, 0 notes unchanged."]
```

2022-06-25 12:46 UTC, closed without merging