Resolve @KotlinCleanup and fix build for CardBrowser_CardCollectionTest.kt
ankidroid/Anki-Android pull request #10845
Opened 2022-04-14 13:40 UTC by lukstbit

## Purpose / Description
At the moment the build fails because of some errors in this class. I fixed the `@KotlinCleanup` issues to make the code build.

## How Has This Been Tested?

Ran the usual tests

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-14 14:21 UTC, mikehardy commented
#10844 just merged if you want to rebase this

2022-04-14 18:40 UTC, david-allison requested changes
one minor additional cleanup

2022-04-14 18:40 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserCardCollectionTest.kt
>      }
Removes the `*` and the `?`

```kotlin
    private fun createCollection(vararg toInsert: Positioned): CardCollection<Positioned> {
        val cardCollection = CardCollection<Positioned>()
        cardCollection.replaceWith(toInsert.toMutableList())
        return cardCollection
    }
```

2022-04-15 13:54 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserCardCollectionTest.kt
>      }
Done, I should have used that method from the start.

2022-04-15 14:05 UTC, mikehardy approved these changes
All comments addressed (i carefully double-checked)

2022-04-15 14:37 UTC, david-allison approved these changes

2022-04-15 14:37 UTC, merged