Replace the string, 'Add note', of Decks-screen's-add-button-menu item with 'Add' #10773
ankidroid/Anki-Android pull request #10853
Opened 2022-04-14 19:43 UTC by Shane-Patrick-Roach

## Purpose / Description

Replaced the string, "Add note", of Decks-screen's-add-button-menu item with "Add". This is a topic of open discussion and we simply made a PR for the proposed change. 

## Fixes
Fixes [#10773](https://github.com/ankidroid/Anki-Android/issues/10773)

![#10773](https://i.imgur.com/v7PkSAj.png)

## Approach
Changed the value of the "menu_add_note" string resource to "Add".

## How Has This Been Tested?

Manually verified correct output rendered emulator. 

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner]

2022-04-14 19:58 UTC, mikehardy commented
For reviewers, this is based on this comment in linked issue:

> Anki Desktop uses only Add in the option and window, so it isn't useful to follow it.

...and my personal experience both with live in-person user support and lots of play store reviews that people don't know how to add cards (and related, they don't know how to add new cards to an existing deck).

Note that many (most?) users have no idea what the difference is between a "note" and a "card", the most they are always just "adding cards" even though we know it's a note they add and we generate cards etc etc.

So that's the idea. Might be a terrible idea though. Voice your opinion...

2022-04-14 20:08 UTC, david-allison requested changes
lint is failing. run `./gradlew lint` to diagnose

2022-04-14 20:09 UTC, david-allison commented
The concept, I like.

The implementation: we already have a `"add"` string, but I don't want to delete `Add Note` just yet if we're voting. It's been there for a long time

2022-04-15 00:15 UTC, david-allison commented
@Shane-Patrick-Roach, we'd prefer if you force pushed changes to the branch, rather than starting a new PR if changes are requested, it reduces our notifications, and more importantly keeps the history of the review in one place.  

New PR: https://github.com/ankidroid/Anki-Android/pull/10858

2022-04-15 00:35 UTC, Shane-Patrick-Roach commented
@david-allison I apologize for the inconvenience. Would you like reopen this branch and make the proposed changes? Or moving forward keep this in mind.

2022-04-15 00:47 UTC, david-allison commented
> @david-allison I apologize for the inconvenience. Would you like reopen this branch and make the proposed changes? Or moving forward keep this in mind.

If you can, let's reopen this one, if not, learning experience :)

2022-04-18 10:11 UTC, snowtimeglass commented
@mikehardy I'm glad that you pay attention to this issue, and thank you for handling it carefully. As you say, it is probably the areas of serious user confusion. I'm looking forward to the new user introduction system.

> If Anki Desktop just uses "Add" that might actually be most useful, 1) ecosystem compatibility, and 2) no confusion about note or card! It's just "Add".
> 
> This is one of the areas of serious user confusion - I answer a lot of reviews where people complain "they don't know how to add a card to an existing deck". Our new user introduction system (when it eventually launches) will help a lot I think. But eliminating card/note word confusion (by just deleting that word - following Anki Desktop) might be a plus too. I think it would be worth the string re-translation cost, it really is a lot of user confusion

https://github.com/ankidroid/Anki-Android/issues/10773#issuecomment-1099261309

After reading your comment, I agreed with it once since the concept, "compatibility", carries weight; but after reading the following @david-allison's comment, 

>The concept, I like.
>
>The implementation: we already have a "add" string, but I don't want to delete Add Note just yet if we're voting. It's been there for a long time

https://github.com/ankidroid/Anki-Android/pull/10853#issuecomment-1099581184



I begun hesitating to agree with your suggestion, and consider this issue again.

>Sure @Shane-Patrick-Roach - it's a really easy change but please note my warning that could be frustrating in a way. The PR itself will be a sort of "vote" to see what other maintainers think and it may very well result in my suggestion (switch to "Add") being rejected and the PR going nowhere. But it's quick at least! :-)

https://github.com/ankidroid/Anki-Android/issues/10773#issuecomment-1099520521

Maintainers, I would like to specify some viewpoints of design/layout/"visual context". 

On the upper area of Anki Desktop main window screen, there seems to be a regularity/pattern/rule: "one word per an item (like the items of the menu bar)" is it. 
![image](https://user-images.githubusercontent.com/10436072/163765856-a4bc4724-eb13-4499-9c89-dd44fe8db6cc.png)
On the area, two words would look too long for one item from viewpoints of design/layout/"visual context". Anki Desktop just uses "Add" for sure; but it's probably not mainly because the string can avoid confusion about "note" and "card" (on the contrary, it rather seems to promote confusion by its ambiguousness), but chiefly because using two words only for one particular item on the area is out of the question from the viewpoints. It would be out of the regularity/pattern/rule.
![image](https://user-images.githubusercontent.com/10436072/163775314-d27e09b9-a1f3-45c1-96ae-2ba3ddee2ccc.png)

Now, the currently discussed item on AnkiDroid is in a far different design/layout/"visual context" from Anki Desktop: it has enough space to show two or more words, the other items of the floating action button have two or three words respectively, Each of the other items consists of a transitive verb and its object, all of the items have its icons severally (so, there is no need for the items to work as sign-like ones by themselves).
![image](https://user-images.githubusercontent.com/10436072/163776937-dd79bad0-3454-4bf7-8f2e-5242331fc94e.png)
In such situation, "Add" would seem to be too short. It wouldn't seem to be so much concise as defective. Using "Add" for the item wouldn't seem to be so much compatible as over-adaptive.

In contrast to "Add", "Add card" will be in harmony with the other elements on AnkiDroid: the length of other items, the composition of them (i.e. Vt + O), its card-shaped icon, and many (or perhaps most) user's intuition that they are adding cards. 
![image](https://user-images.githubusercontent.com/10436072/163777262-d851dfaf-a7ac-4b0a-8719-15f4d38454aa.png)

Speaking of the intuition, in fact, from a point of view, it is right since adding a note eventually results in adding one or more cards: adding cards is the goal of the action of the item, and adding note is the first step to the goal. What AnkiDroid should do doesn't seem to make the relationship more vague by deleting the object word of "add", but rather to make the relationship clearer by adding some guidance/explanation.

Maintainers, for the above reasons, I would like to request you to consider the following plan.

- Keep the current card-shaped icon unchanged
- Replace the current name of the item (`Add note`) "Add card" (its string already exists on Crowdin)
- Keep the title of `Add note` screen unchanged
- Show some toast when `Add note` screen gets shown; it helps users to understand the relationship between "note" and "card" smoothly. Its message is something like this: "please add a note to generate card(s)"

2022-04-18 10:29 UTC, dae commented
While you make a good point about uniformity in the main Anki window, please note that the titlebar of the Add screen also is just "Add", because I thought either "Add Cards" or "Add Notes" would be a little unclear, as you can't add cards without adding notes, and vice versa. "Add card" may be more recognizable to new users, but it is potentially a bit more confusing for users who start to learn about the difference between cards and notes. One other possible idea would be "Add cards/notes", though it is a bit longer.

2022-04-18 12:43 UTC, snowtimeglass commented
@dae thank you so much for the comment. 

>please note that the titlebar of the Add screen also is just "Add",

Um, to be honest, I inadvertently didn't take it into consideration (I'm blushing. Thank you for letting me know), but pardon me, now I'm concerned about whether the title of the Add screen is a better choice because I think it would be more helpful to tell users that they are adding a note with the note editor at the moment. 

>"Add card" may be more recognizable to new users, but it is potentially a bit more confusing for users who start to learn about the difference between cards and notes.

I think so too about the latter users if tapping "Add card" opens the note editor screen without any explanation, but
I would have another opinion if it did with some helpful explanation. Couldn't some toast message like the above play a role in reducing such confusion and promoting understanding about cards and notes?

2022-04-19 02:59 UTC, dae commented
The Add screen is one of the first parts of the Anki interface a user may discover. By avoiding mention of "note" and "card", I hoped that new users could avoid having to think about/understand the distinction between the two - at least if they are adding simple front→back cards. They can think: "I click Add, I type some text, I press the Add button, and a card is added", and they don't need to understand the difference between cards and notes. They will probably need to understand it in the future, especially if they want to use notetypes that generate more than one card. But the goal was to try and keep things simple for the basic case.

I'm not super enthusiastic about showing a toast/popup - it forces the user to become aware of the differences between cards/notes at the start, and showing a popup each time a screen is opened will annoy some power users, and confuse some new users who don't read it quickly enough, then wonder if they missed some important information.

I am not firmly set on the idea of using "Add", I just wanted to explain the thought process behind it. Maybe I'm naive to think that new users can avoid thinking about cards/notes at the start. :-)

2022-04-19 03:22 UTC, mikehardy commented
Based on the comments I read on the play store, users really *want* to avoid thinking of cards/notes at the start ;-)

2022-04-19 13:57 UTC, snowtimeglass commented
@dae, @mikehardy, thanks to you two, now I can understand the consideration behind the idea of using "Add". I think that it is important and should take precedence over viewpoints of appearance. I'm pleased to agree with the choice which is based on abundant experience and knowledge. Thank you so much for mentoring me :-D

2022-04-23 19:08 UTC, mikehardy commented
@Shane-Patrick-Roach okay I think consensus is "Add" is the best choice in a delicate balance of tensions between new user friendly and more detail

Here's the last comment from David:

> The concept, I like.
> 
> The implementation: we already have a "add" string, but I don't want to delete Add Note just yet if we're voting. It's been there for a long time

Sounds like we can remove Add Note then, and re-use whatever existing Add string there is? (assuming it's uppercase first initial)

2022-04-28 23:10 UTC, BrayanDSO commented
So, here are the places where `Add Note` is used:

- One of the 3 app shortcuts
- NoteEditor
- FAB
- Gestures selection
- Reviewer menu

Just to be sure, which of these 5 places are going to change `Add note` to `Add`? The current approach would change all of them. 

I particularly think `Gestures` and `Reviewer menu` shouldn't be changed because the user has a lot of options there: "Add what? Tags? A flag? A mark star?" and I don't want to make users think to get by exclusion or testing that it means "Add note/card".
The other places are fine to me, so here's my two cents worth

2022-04-29 12:19 UTC, snowtimeglass commented
@BrayanDSO thanks for the valuable opinion. I agree with you.

2022-04-29 17:08 UTC, mikehardy commented
> I particularly think Gestures and Reviewer menu shouldn't be changed because the user has a lot of options there: "Add what? Tags? A flag? A mark star?" and I don't want to make users think to get by exclusion or testing that it means "Add note/card".
> The other places are fine to me, so here's my two cents worth

Good analysis - I agree - keep gestures + reviewer menu, change rest to "Add"

2022-05-10 15:20 UTC, mikehardy commented
@Shane-Patrick-Roach this took a while to reach consensus - nothing like changing the wording on something to require a lot of back and forth - but I think we have a final desired state now. Are you still interested in finishing this up?

2022-07-19 07:24 UTC, closed without merging