[Kotlin migration ] AnalyticsTest
ankidroid/Anki-Android pull request #10850
Opened 2022-04-14 18:24 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
Kotlin migration of AnalyticsTest.java

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-14 18:29 UTC, david-allison requested changes
Tests failing. Please rebase this onto `main` as we had a relevant PR just go in.

2022-04-14 18:30 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.kt
> +class AnalyticsTest {
`cleanup: when -> whenever`

2022-04-14 18:30 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.kt
> +        Mockito.`when`(mMockContext!!.resources)
fix (in this commit): import `Mockito`

2022-04-14 18:31 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.kt
> +        Mockito.mockStatic(PreferenceManager::class.java).use { _ ->
I'm surprised this works in Kotlin, can you check the tests in a debugger

2022-04-15 12:14 UTC, Prince-kushwaha commented on AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.kt
> +        Mockito.`when`(mMockContext!!.resources)
i not understand what i have to do?

2022-04-15 12:25 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.kt
> +        Mockito.`when`(mMockContext!!.resources)
Import `Mockito`, so the line starts with 
```
`when`(mMockContext!!.resources)
```

2022-04-15 12:26 UTC, david-allison commented
WARN: conflicts with https://github.com/ankidroid/Anki-Android/pull/10864

2022-04-15 12:31 UTC, Prince-kushwaha commented on AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.kt
> +        Mockito.`when`(mMockContext!!.resources)
i have cleanup: when -> whenever

2022-04-15 19:57 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.kt
> +        whenever((mMockResources!!.getBoolean(R.bool.ga_anonymizeIp)))
Please use `when`. The second commit should be the minimum effort required to get CI passing, keeping as true to CI as possible 

With the exception of imports, which want to be as true to the Java as possible - the Kotlin migration messes up imports, adding or removing them in a lot of cases

2022-04-16 12:13 UTC, david-allison reviewed
Looks great! Think this is going to be it

2022-04-16 12:13 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.kt
> +@file:Suppress("DEPRECATION")
Move this back to `testSendException`

2022-04-16 12:13 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.kt
> +class AnalyticsTest {
Add a `KotlinCleanup` for `when` usage to be converted to `whenever`

2022-04-16 12:13 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.kt
> +    private val mMockContext: Context? = null
KotlinCleanup to see if these can be made `lateinit`

2022-04-16 12:54 UTC, david-allison approved these changes

2022-04-16 12:55 UTC, david-allison commented
Great! Thanks

2022-04-17 18:19 UTC, mikehardy approved these changes
Nice, thank you!

2022-04-17 18:27 UTC, merged