Resolves accessiblity issue in toolbar hamburger icon
ankidroid/Anki-Android pull request #10879
Opened 2022-04-15 16:54 UTC by Propo41

## Pull Request template

## Purpose / Description
- resolves #10786 
- Added a test to check if the invertCode function works by correctly inverting the color codes from white to black

## Fixes
- fixes #10786 

[Before]
![162765578-906445ab-627f-4312-a65e-f70974ffb722](https://user-images.githubusercontent.com/46298019/163598232-cde188de-9d4b-425e-a0d0-f0956abe590b.png)

[After]
![277826953_1160124364762908_4251923265400219823_n](https://user-images.githubusercontent.com/46298019/163598469-abd42dc0-2430-4b13-b426-d35f564cfeef.jpg)

## Approach
It adds the content description of the hamburger icon by adding the descriptions to the ActionBarToggle initialization

## How Has This Been Tested?
Manual testing by long pressing on the hamburger icon.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-15 17:07 UTC, david-allison requested changes
Thanks!!!

Some changes requested to ensure the commit only. shows relevant changes

CI fails:

```
> Task :AnkiDroid:lintPlayDebug FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/02-strings.xml:27: Error: Duplicate string value "Open drawer", used in ankidroid_navigation_drawer_open, drawer_open [DuplicateCrowdInStrings from com.ichi2.anki.lint]
    <string tools:ignore="UnusedResources" name="drawer_open">Open drawer</string>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/02-strings.xml:278: Duplicates value in drawer_open. Add a comment attribute on both strings to explain this duplication
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/02-strings.xml:28: Error: Duplicate string value "Close drawer", used in ankidroid_navigation_drawer_close, drawer_close [DuplicateCrowdInStrings from com.ichi2.anki.lint]
    <string tools:ignore="UnusedResources" name="drawer_close">Close drawer</string>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/02-strings.xml:279: Duplicates value in drawer_close. Add a comment attribute on both strings to explain this duplication
2 errors, 0 warnings
```

2022-04-15 17:07 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +
could you revert these unnecessary line changes, they add noise to the diff

2022-04-15 17:07 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +    private @LayoutRes
ditto

2022-04-15 17:12 UTC, Propo41 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +
on it

2022-04-15 17:55 UTC, Propo41 commented
@david-allison hey, can you shed some light on why the checks are failing? I removed the unnecessary indents.

2022-04-15 22:21 UTC, david-allison requested changes
Functionality looks great!

Few refactorings and it can go in.

The spacing changes are much less of a problem in our Kotlin code, one of the reasons we migrated.

2022-04-15 22:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +package com.ichi2.anki;
revert: spacing change

2022-04-15 22:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +        mDrawerToggle = new ActionBarDrawerToggle(this, mDrawerLayout, R.string.drawer_open, R.string.drawer_close) {
This is great!

2022-04-15 22:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +
spacing change: revert

2022-04-15 22:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +}
spacing change: revert

2022-04-15 22:21 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/themes/HtmlColorsTest.kt
> +    fun testCorrectColorInversion() {
Split this off into another branch, aim to keep a PR to one "topic"

2022-04-15 22:21 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="drawer_close">Close drawer</string>
Awesome!

2022-04-15 23:04 UTC, Propo41 commented on AnkiDroid/src/test/java/com/ichi2/themes/HtmlColorsTest.kt
> +    fun testCorrectColorInversion() {
alright

2022-04-15 23:05 UTC, Propo41 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +}
I really can't seem to find how to revert this.

2022-04-16 00:50 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +}
@Propo41 What OS are you using?

@mikehardy any advice here? Seems like a line ending issue. Maybe `core.autocrlf` related, but I'm lost

2022-04-16 06:36 UTC, Propo41 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +}
I'm using windows.

2022-04-16 06:40 UTC, Propo41 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +}
Should I fork the repo again and do the changes from scratch and make a new PR instead?

2022-04-16 12:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +}
nono, this should be fixable. It's incredibly rare to need to send in a new PR, let alone re-fork the repo.

I'd bring this to Discord to see if anyone has suggestions. I didn't have this issue on my Windows PC

2022-04-16 13:38 UTC, Propo41 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +}
> nono, this should be fixable. It's incredibly rare to need to send in a new PR, let alone re-fork the repo.
> 
> I'd bring this to Discord to see if anyone has suggestions. I didn't have this issue on my Windows PC

Alright. But I was hoping to proceed with the GSOC proposal this season, and it would really help if I could do the merge process quickly.

2022-04-16 13:53 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +}
No ideas sorry I would need to know the exact steps taken to reach this state and the exact steps of any experiments. I personally detest working on windows for code specifically because of CRLF/LF issues for this reason - it's so hard.

2022-04-16 14:01 UTC, Propo41 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +}
> No ideas sorry I would need to know the exact steps taken to reach this state and the exact steps of any experiments. I personally detest working on windows for code specifically because of CRLF/LF issues for this reason - it's so hard.

I guess creating a new PR  and starting fresh would be a quicker approach? Even if I could fix this, I would have to squash a whole list of commits!

2022-04-16 14:13 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +}
To maintain perspective: Squashing a whole list of commits should be considered zero cost on your part. Interactive rebase, squashing etc: your goal should be to get so good at doing those things that it has zero cost. I don't even consider those things in my thought process when I am deciding how to proceed with things.

So, squash away. No problem.

The problem is perhaps related to checkout of the file etc. I do not ever consider creating a new PR (based on my above perspective) but you might need to do a fresh local checkout with the autocrlf idea David mentioned above. You may need to use your favorite package manager (like choco) to install dos2unix or similar and play with running it through that. I don't know...

2022-04-16 15:15 UTC, Propo41 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +}
Alright thanks! I'll give it a try

2022-04-17 11:11 UTC, Propo41 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +
fixed

2022-04-17 12:20 UTC, Propo41 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +}
@david-allison The line ending issue has been fixed. Never gonna use windows again for git! Is it mandatory to squash the commits? I'm having some serious difficulty in the squashing process. After I did the squash in vim, all the commits (including others) had my name on it @.@

2022-04-17 12:33 UTC, david-allison approved these changes
Looks great, thanks!

2022-04-17 12:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +}
We can do it, but you should learn.

Inside Android Studio:

* Select all the commits in the `Git` window
* Right click -> Squash

OR:

* Select the first commit to squash
* Right click - interactively rebase
* select all the commits to squash

Inside git:

`git rebase -i HEAD~5` where 5 is the number of commits that you MAY want to squash.
`git commit --amend` if you want to squash instead of make a new commit
`git push --force-with-lease` - if you've changed commits and want to update your PR 

You should learn (especially as it's a vital skill), and will need to for larger contributions to the repo, but for the first few contributions, it's fine to spend time gaining confidence with other things.

2022-04-17 12:50 UTC, Propo41 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +}
Thanks, I'll play around with this in a dummy repo to understand how it works.

2022-04-17 12:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +}
There's a lot of people that would strongly disagree, but the IntelliJ (Android Studio) GUI tools for rebasing are great and give a good mental model of how the process works

2022-04-17 13:11 UTC, Propo41 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +}
Yeah seems like it gives a better visualization!

2022-04-17 18:22 UTC, mikehardy approved these changes
Nice! Thanks a bunch for this, we can *always* use accessibility help

2022-04-17 18:24 UTC, merged