[Kotlin Migration] TagsTest.java
ankidroid/Anki-Android pull request #10890
Opened 2022-04-16 09:57 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
Kotlin migration of TagsTest.java

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-16 12:06 UTC, david-allison requested changes
Looks good. Two comments

Could you fix the spacing of the code to match how it previously looked?

2022-04-16 12:06 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/TagsTest.kt
> +        Assert.assertNotEquals(tags_list1, tags.split("Todo todo Needs Revision"))
import `assert`

2022-04-16 12:06 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/TagsTest.kt
> +        TestCase.assertEquals(tags_list2, tags.split("Todo todo Needs Revision"))
import `TestCase`

2022-04-16 19:45 UTC, david-allison requested changes
Still line spacing changes which should be reverted to improve clarity

![Screenshot 2022-04-16 at 20 45 03](https://user-images.githubusercontent.com/62114487/163689304-2be873df-727e-42c9-bcc6-29b30ed1ad25.png)

2022-04-17 12:43 UTC, david-allison approved these changes
Thanks!

2022-04-17 18:32 UTC, mikehardy approved these changes
Nice! Thanks

2022-04-17 19:21 UTC, merged