Improved Preferences instantiation
ankidroid/Anki-Android pull request #10897
Opened 2022-04-16 16:23 UTC by divyansh-dxn

## Pull Request template

## Purpose / Description
Initially, it was a `KotlinCleanup` task, but going through the file, I thought we can have a better implementation of it. 

## Fixes
Improves code quality

## Approach
Using JUnit's `@Before` method to create a new instance of `Preferences` rather than creating it each time manually.

## How Has This Been Tested?
Tests run fine, and app works as expected on Realme 6i API 30

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-16 19:47 UTC, david-allison reviewed
Seems good, one minor improvement to ensure correctness

2022-04-16 19:47 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/PreferencesTest.kt
> +    fun setup() {
you want to override the `@Setup` method in `RobolectricTest`

2022-04-16 19:48 UTC, david-allison requested changes
Conflicts also need fixing - marking as 'changes needed'

2022-04-17 12:31 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/PreferencesTest.kt
> +    override fun setUp() {
And `@Before` (I beleive)

2022-04-19 10:28 UTC, divyansh-dxn commented on AnkiDroid/src/test/java/com/ichi2/anki/PreferencesTest.kt
> +    override fun setUp() {
I don't know whether annotations get inherited or not, but still, in other tests, it has been written again in the subclass, so I'm writing it.

2022-04-19 21:33 UTC, david-allison approved these changes

2022-04-19 22:41 UTC, mikehardy approved these changes
excellent - thank you!

2022-04-19 23:17 UTC, merged

2022-06-05 20:56 UTC, mikehardy commented
Hi there! APRIL OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [April 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-04-01..2022-04-30)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of March.

Please note that GSoC contributions are okay for this process. Our philosophy is that our users have donated to AnkiDroid for all contributions. The only PRs that will not go through the OpenCollective process are ones directly related to am accepted GSoC project from a selected participant, since those receive a stipend from GSoC itself.

Please understand that this means the monthly budget we have for payments might be stretched a bit and the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!