DeckOverview screen Overflow menu icon changed #10868 error solved
ankidroid/Anki-Android pull request #10906
Opened 2022-04-17 12:24 UTC by siddharthsingh025

## # Error : #10868  *SOLVED ✅ * : Show "Deck options" icon on Actionbar of Deck overview screen instead of its three dot menu icon

## Output i get : 

<img width="430" alt="Screenshot 2022-04-17 at 4 54 57 PM" src="https://user-images.githubusercontent.com/87073574/163713426-77fcea1b-7960-4773-8c61-32caa9ed6937.png">

<img width="450" alt="Screenshot 2022-04-17 at 4 55 06 PM" src="https://user-images.githubusercontent.com/87073574/163713423-75643cd8-9ad4-478a-95fc-a3389e2ca255.png">

###  **Changes i do :** 
_1. Define new style with New icon_  { https://github.com/siddharthsingh025/Anki-Android/blob/c43ae29e1ad9155e0587789534b8aa9250773b31/AnkiDroid/src/main/res/values/styles.xml#L196 }

    
    <style name="MyOverflow" parent="android:style/Widget.Holo.ActionButton.Overflow" >
    <item name="android:src">@drawable/ic_baseline_tune_24</item>
    </style>

_2.Then copy old actionbar style and ADD our new overflow style_  { https://github.com/siddharthsingh025/Anki-Android/blob/c43ae29e1ad9155e0587789534b8aa9250773b31/AnkiDroid/src/main/res/values/styles.xml#L121 }

    
    
    <style name="OverflowStyle" parent="Base.ThemeOverlay.AppCompat.ActionBar">
    
    <item name="android:textColorPrimary">@color/white</item>
    
    <item name="android:textColorSecondary">@color/white</item>
    
    <item name="popupTheme">@style/ActionBar.Popup</item>

    
    <item name="android:actionOverflowButtonStyle">@style/MyOverflow</item>

    </style>

_3.  Add our new theme {"OverflowStyle "}  to  fragment page of DeckOverview like :_  {https://github.com/siddharthsingh025/Anki-Android/blob/c43ae29e1ad9155e0587789534b8aa9250773b31/AnkiDroid/src/main/res/layout/studyoptions_fragment.xml#L5}

    android:theme="@style/OverflowStyle”   

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-17 12:46 UTC, david-allison commented
Is there a reason this change wasn't made in the XML layout for the menu:

https://github.com/ankidroid/Anki-Android/blob/0c544371db268cb520e1f89dbc7aa2f499153452/AnkiDroid/src/main/res/menu/study_options_fragment.xml

2022-04-17 12:50 UTC, BrayanDSO commented
We have a tune icon already `ic_tune_white.xml`, so it would be better if the icons was reused

2022-04-17 13:52 UTC, siddharthsingh025 commented
okay i will do it

2022-04-17 14:07 UTC, siddharthsingh025 commented
done : abee522062085202ee75616cc956fa5018a38c98

2022-04-17 14:29 UTC, siddharthsingh025 commented
> Is there a reason this change wasn't made in the XML layout for the menu:
> 
> https://github.com/ankidroid/Anki-Android/blob/0c544371db268cb520e1f89dbc7aa2f499153452/AnkiDroid/src/main/res/menu/study_options_fragment.xml#L22-L26


# **if you want change i can do it ??**

2022-04-17 14:33 UTC, david-allison commented
> > Is there a reason this change wasn't made in the XML layout for the menu:
> > https://github.com/ankidroid/Anki-Android/blob/0c544371db268cb520e1f89dbc7aa2f499153452/AnkiDroid/src/main/res/menu/study_options_fragment.xml#L22-L26
> 
> # **if you want change i can do it ??**

yes please, it should make the code a lot more maintainable

2022-04-17 15:04 UTC, siddharthsingh025 commented
> yes please, it should make the code a lot more maintainable

> i think thier is no need of change in menu xml bcoz i creat theme for Overflow icon so , you want it on Deckoverview page  , its done

2022-04-17 15:06 UTC, siddharthsingh025 commented
can you help me with this failing check ?? 
 *" Unit Tests / JUnit Tests (windows-latest) (pull_request) "*

2022-04-17 15:08 UTC, david-allison commented
> can you help me with this failing check ?? 
>  *" Unit Tests / JUnit Tests (windows-latest) (pull_request) "* 

Rebase onto main, I've fixed that in a recent commit

2022-04-17 15:17 UTC, siddharthsingh025 commented
> 

can you give the link of commit?

2022-04-17 19:53 UTC, mikehardy requested changes

2022-04-17 19:53 UTC, mikehardy commented on AnkiDroid/src/main/res/values/styles.xml
> +    <style name="MyOverflow" parent="android:style/Widget.Holo.ActionButton.Overflow" >
Seems reasonable - just the name doesn't mean anything without full context. Ideally the name contains the necessary context, something more like this? Though anything more descriptive would work for me

```suggestion
    <style name="TuneIconOverflow" parent="android:style/Widget.Holo.ActionButton.Overflow" >
```

(and then the reference above on line 132 would change to match)

2022-04-18 05:38 UTC, siddharthsingh025 commented
can you help me with this " Emulator Tests / Android Emulator Test (pull_request) "

2022-04-18 11:20 UTC, mikehardy commented
re-ran CI test just now, hopefully it goes green this time, might be a flaky test?

2022-04-19 11:27 UTC, siddharthsingh025 commented
what should i do now?? this PR will merged or not ??

2022-04-19 12:41 UTC, mikehardy approved these changes
"what you do now" is wait with just a bit of patience while all the volunteer reviewers here find another batch of time to work through the batch of PRs scanning for PRs that are ready for review again :-)

This looks good to me now, thank you!

2022-04-19 12:55 UTC, siddharthsingh025 commented
> "what you do now" is wait with just a bit of patience while all the volunteer reviewers here find another batch of time to work through the batch of PRs scanning for PRs that are ready for review again :-)
> 
> This looks good to me now, thank you!

thankyou too @mikehardy

2022-04-23 19:49 UTC, david-allison requested changes
Is there a reason we're not modifying a menu xml file for this?

2022-04-24 04:17 UTC, siddharthsingh025 commented
Actually @david-allison i don't understand why we need to change in  "menu / study_options_fragment"  XML file , bcoz our overflow menu icon is a part of our actionbar , and i made a style for new action bar with new overflow menu icon , and then add this to theme and after that i assign this theme to a particular layout fragment where we want change the new action bar with Tune icon menu Overflow like in studyoptions_fragment LAYOUT ........so why we need any change in menu xml of studyOption and how i can add this theme to it.

2022-04-24 04:24 UTC, siddharthsingh025 commented
> Is there a reason we're not modifying a menu xml file for this?

  Actually @david-allison i don't understand why we need to change in "menu / study_options_fragment" XML file , bcoz our       overflow menu icon is a part of our actionbar , and i made a style for new action bar with new overflow menu icon , and then    add assign this  to a theme of a particular layout fragment where we want change the new action bar with Tune icon menu Overflow like in studyoptions_fragment LAYOUT ........so why we need any change in menu xml of studyOption and how i can add this theme to it.

2022-04-24 04:36 UTC, siddharthsingh025 commented
@david-allison  are you wanting this 

https://user-images.githubusercontent.com/87073574/164956851-7e704734-fbf5-4f37-8d75-1a7c89243a07.mov


>>>>

2022-04-24 15:12 UTC, david-allison commented
My understanding is that @snowtimeglass would prefer that the menu was removed, rather than reskinned, and the 'deck options' item appeared in the action bar instead of in the menu.

Right now, we reskin the menu item from `...` to the preference icon, but it's still a submenu with one item

2022-04-24 16:43 UTC, siddharthsingh025 commented
So , @david-allison now , can i remove the style that i creat for Overflow menu  from studyoptions_fragment LAYOUT  and than only add  Tune icon to Deckoption in "menu / study_options_fragment" XML file and make its "Showaction"  to " ifroom " .

2022-04-24 17:02 UTC, david-allison requested changes
Looks great! Just a few unnecessary line changes to clean up

2022-04-24 17:02 UTC, david-allison commented on AnkiDroid/src/main/res/values/styles.xml
> +
could you revert this line change

2022-04-24 17:02 UTC, david-allison commented on AnkiDroid/src/main/res/values/styles.xml
> +
and this one

2022-04-24 17:02 UTC, david-allison commented on AnkiDroid/src/main/res/menu/study_options_fragment.xml
> +    xmlns:ankidroid="http://schemas.android.com/apk/res-auto">
and this line change

2022-04-24 17:14 UTC, siddharthsingh025 commented on AnkiDroid/src/main/res/menu/study_options_fragment.xml
> +    xmlns:ankidroid="http://schemas.android.com/apk/res-auto">
yes

2022-04-24 18:55 UTC, david-allison commented on AnkiDroid/src/main/res/menu/study_options_fragment.xml
> +        />
I'll approve when this is the only change in the diff.

Typically: if you avoid merge commits and rebase when bringing changes in from `main`, you can use Android Studio to compare and revert the line changes easily.

2022-04-25 12:17 UTC, snowtimeglass commented
@siddharthsingh025 @david-allison thank you so much for tackling this issue.
 
> Yes.
> 
> My understanding is that @snowtimeglass would prefer that the menu was removed, rather than reskinned,

I'm sorry for my insufficient explanation. Either will be fine for me. I think that it's also good to leave the three dot icon as it is (if there are some appropriate items in the menu). I hope you select a not-exhausting way :-)

2022-04-26 19:11 UTC, david-allison commented
I'm moving this to a draft to keep my queue clean, when the spacing changes are fixed, this can go in.

2022-04-30 13:51 UTC, david-allison commented
If you click 'Files Changed', there are still files changed which shouldn't have been

2022-05-01 13:10 UTC, david-allison requested changes
One change in the header, then good to go, thanks!

2022-05-01 13:36 UTC, siddharthsingh025 commented
> One change in the header, then good to go, thanks!

where to change? which line?

2022-05-01 14:03 UTC, david-allison approved these changes
LGTM. Thanks!

2022-05-06 21:01 UTC, mikehardy approved these changes

2022-05-06 21:02 UTC, merged