[KotlinCleanup] LoadPronunciationActivity.kt
ankidroid/Anki-Android pull request #10900
Opened 2022-04-16 23:22 UTC by Jatin887

## Pull Request template

## Purpose / Description
Kotlin CleanUp

## Fixes
Part of #10489

## Approach
Using lint and some code changes which were mentioned in the comments and  required to make the code more reliable

## How Has This Been Tested?
Physical Device One Plus Nord2

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-16 23:24 UTC, Jatin887 commented
@david-allison please review

2022-04-16 23:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +    private lateinit var mAddress: String
Why was `mAddress` moved here?

2022-04-16 23:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +    private lateinit var mTranslationAddress: String
Some of these aren't instantiated in onCreate. 

Were these all confirmed to not have an impact? A lot of these seem concerning to me,

2022-04-17 04:23 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +    private lateinit var mAddress: String
i feel like it is a good practice to declare all lateint var in one place.
I can change it's position again if you want?

2022-04-17 04:41 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +    private lateinit var mTranslationAddress: String
I need a suggestion here like in the current scenario all of these variable will be created when the activity object is created. and if i instantiated the variable in onCreate it will create variables when system calls onCreate(). previously all the varibales was declared outside the onCreate() so i didn't change it. but if you want it to be inside onCreate()? Let me know i will add the changes. but i feel it does not have an impact as such

2022-04-17 06:06 UTC, raymondwzeng commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +    private lateinit var mTranslationAddress: String
Gonna +1 on the original comment, I found *a* crash that may stem from mPostPronunciation not being initialized. Double checked, and this doesn't seem to happen on main branch.

Here's the crash snippet from ADB:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 7679
    java.lang.RuntimeException: Unable to pause activity {com.ichi2.anki/com.ichi2.anki.multimediacard.activity.LoadPronunciationActivity}: kotlin.UninitializedPropertyAccessException: lateinit property mPostPronunciation has not been initialized
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4932)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4883)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4834)
        at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property mPostPronunciation has not been initialized
        at com.ichi2.anki.multimediacard.activity.LoadPronunciationActivity.stopAllTasks(LoadPronunciationActivity.kt:353)
        at com.ichi2.anki.multimediacard.activity.LoadPronunciationActivity.onPause(LoadPronunciationActivity.kt:362)
        at android.app.Activity.performPause(Activity.java:8180)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1671)
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4922)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4883) 
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4834) 
        at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:233) 
        at android.app.ActivityThread.main(ActivityThread.java:8010) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978) 
```

Repro Steps:
1. Add a note, go to field, add audio from Beolingus
2. Search up a word that does not exist in the library (I chose "yeah")
3. Go back.

Here's a quick video to show what happens:

https://user-images.githubusercontent.com/13594022/163702824-c5961def-7fd4-4cda-8f00-e73db94fa42a.mp4

2022-04-17 11:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +    private lateinit var mAddress: String
It's better to scope a variable as tightly as possible.

In this case, in the inner class

2022-04-25 04:58 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +    private lateinit var mTranslationAddress: String
Yes you are right. I made the changes now it's working fine

2022-04-25 05:21 UTC, Jatin887 commented
@mikehardy can you please again open this pr as i am working on it.

2022-04-25 11:12 UTC, mikehardy commented
You may mark it ready for review whenever you feel it's no longer draft, the control for same is near top right in GitHub web UI

2022-04-25 16:19 UTC, Jatin887 commented
@david-allison please review

2022-04-25 16:27 UTC, david-allison requested changes
CI is failing

```
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
    var mStopped = false
    ~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt:56: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
    lateinit var mAddress: String
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt:57: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
    lateinit var mTranslationAddress: String
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt:58: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
    lateinit var mPronunciationAddress: String
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt:60: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
    lateinit var mActivity: LoadPronunciationActivity
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt:61: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
    lateinit var mLoadingLayoutTitle: TextView
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt:62: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
    lateinit var mLoadingLayoutMessage: TextView
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt:63: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
    lateinit var mLoadingLayout: View
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt:64: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
    lateinit var mMainLayout: LinearLayout
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt:68: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
    lateinit var mLanguageLister: LanguageListerBeolingus
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt:70: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
    lateinit var mSpinnerFrom: Spinner
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11 errors, 0 warning
```

2022-04-25 16:28 UTC, david-allison reviewed
Main question: did you make the `lateinit` variables by checking how they're initialized?

2022-04-25 16:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +    lateinit var source: String
why are these now public?

2022-04-25 16:46 UTC, Jatin887 commented
> CI is failing

yes i checked

2022-04-25 17:14 UTC, Jatin887 commented
> CI is failing
> 
> ```
> w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
>     var mStopped = false
>     ~~~~~~~~~~~~~~~~~~~~
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt:56: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
>     lateinit var mAddress: String
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt:57: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
>     lateinit var mTranslationAddress: String
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt:58: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
>     lateinit var mPronunciationAddress: String
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt:60: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
>     lateinit var mActivity: LoadPronunciationActivity
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt:61: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
>     lateinit var mLoadingLayoutTitle: TextView
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt:62: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
>     lateinit var mLoadingLayoutMessage: TextView
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt:63: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
>     lateinit var mLoadingLayout: View
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt:64: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
>     lateinit var mMainLayout: LinearLayout
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt:68: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
>     lateinit var mLanguageLister: LanguageListerBeolingus
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt:70: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
>     lateinit var mSpinnerFrom: Spinner
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 11 errors, 0 warning
> ```

I am not getting it. all the variables were initialized previously i changed it to lateinit and lateinit variables can't be intialized.

2022-04-25 17:34 UTC, Jatin887 commented
I tested it in my physical device and  it is working fine
https://user-images.githubusercontent.com/71597104/165142789-2c4d7226-781f-455d-86ac-1206a2b1ceb1.mp4

2022-04-25 17:48 UTC, david-allison requested changes

2022-04-25 17:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +    private lateinit var mAddress: String
This hasn't been addressed

2022-04-25 17:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +        source = intent.extras!!.getString(EXTRA_SOURCE).toString()
Do we want the string `"null"` in here? Probably better to `!!`

2022-04-25 18:04 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +        source = intent.extras!!.getString(EXTRA_SOURCE).toString()
done

2022-04-25 18:23 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +    private lateinit var mAddress: String
changes done

2022-04-25 23:54 UTC, david-allison approved these changes
Awesome!

2022-04-26 13:14 UTC, merged