Fixed "CheckMedia" causing crash
ankidroid/Anki-Android pull request #10926
Opened 2022-04-17 22:17 UTC by dorrin-sot

## Pull Request template

## Purpose / Description
App crashed if checkmedia was done after an update from v2.15.6

## Fixes
Fixes #10892 

## Approach
Added `READ_EXTERNAL_STORAGE` permision to the permissions list in `DeckPicker::requestStoragePermission`

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-17 22:33 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE
does it make sense to request READ and WRITE since WRITE contains READ 🤔

2022-04-17 22:34 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE
never mind - I just read the related issue more closely and see that this is some bizarre case apparently where WRITE does *not* contain READ, contrary to the docs, and that's the whole point of the PR really, sorry!

2022-04-17 22:36 UTC, mikehardy approved these changes
This seems like it should address the issue, thanks so much for pursuing this.
Since I can recreate this also I'll queue it for release in the alpha I do in a little bit and then check it, hopefully it works!

2022-04-17 22:36 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE
yes because it seems like android has changed something about the permissions so unlike before, they dont automatically grant read permission if user granted write permission.

2022-04-17 22:50 UTC, mikehardy commented
Oh crud - you fixed this right as DeckPicker just went java -> kt in #10924 so now this needs a full re-do
Sincere apologies but I guess it's better than contemplating converting DeckPicker to kt ourselves 😆 -  monster file

2022-04-17 22:51 UTC, mikehardy requested changes
needs a re-do but in kotlin now

2022-04-17 23:17 UTC, mikehardy commented
I'm going to start doing this on the Kotlin version since I want to test it and you've already done all the good work diagnosing + thinking about it. It's a simple re-do - if you're already working on it just let me know, otherwise I'll post a PR that supercedes this one but for credit purposes (not sure if you are a GSoC candidate or not, sorry if I'm just oblivious 😅 ) this and the kotlin version are definitely yours!

2022-04-17 23:33 UTC, dorrin-sot commented
Oh I can do it 😁

2022-04-17 23:35 UTC, mikehardy commented
Ok! Feel free. My kotlin is terrible, since I have never actually coded kotlin so I was doing it mostly just to exercise the new skill. I'll be very curious if you come up with the same thing I did, I *think* this is reasonable Kotlin?

```diff

diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.ktindex 7e0500d05..15df27c56 100644
--- a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
@@ -473,13 +473,13 @@ open class DeckPicker : NavigationDrawerActivity(), StudyOptionsListener, SyncEr
     @KotlinCleanup("remove parameters named _")
     @KotlinCleanup("return early and remove else")
     fun requestStoragePermission() {
+        val storagePermissions = arrayOf(
+            Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE
+        )
         if (mClosedWelcomeMessage) {
             // DEFECT #5847: This fails if the activity is killed.
             // Even if the dialog is showing, we want to show it again.
-            ActivityCompat.requestPermissions(
-                this, arrayOf(Manifest.permission.WRITE_EXTERNAL_STORAGE),
-                REQUEST_STORAGE_PERMISSION
-            )
+            ActivityCompat.requestPermissions(this, storagePermissions, REQUEST_STORAGE_PERMISSION)
         } else {
             Timber.i("Displaying initial permission request dialog")
             // Request storage permission if we don't have it (e.g. on Android 6.0+)
@@ -490,10 +490,7 @@ open class DeckPicker : NavigationDrawerActivity(), StudyOptionsListener, SyncEr
                 .positiveText(R.string.dialog_ok)
                 .onPositive { _: MaterialDialog?, _: DialogAction? ->
                     mClosedWelcomeMessage = true
-                    ActivityCompat.requestPermissions(
-                        this, arrayOf(Manifest.permission.WRITE_EXTERNAL_STORAGE),
-                        REQUEST_STORAGE_PERMISSION
-                    )
+                    ActivityCompat.requestPermissions(this, storagePermissions, REQUEST_STORAGE_PERMISSION)
                 }
                 .cancelable(false)
                 .canceledOnTouchOutside(false)
@@ -719,8 +716,8 @@ open class DeckPicker : NavigationDrawerActivity(), StudyOptionsListener, SyncEr

     override fun onRequestPermissionsResult(requestCode: Int, permissions: Array<String>, grantResults: IntArray) {
         super.onRequestPermissionsResult(requestCode, permissions, grantResults)
-        if (requestCode == REQUEST_STORAGE_PERMISSION && permissions.size == 1) {
-            if (grantResults[0] == PackageManager.PERMISSION_GRANTED) {
+        if (requestCode == REQUEST_STORAGE_PERMISSION && permissions.isNotEmpty()) {
+            if (grantResults.all { it == PackageManager.PERMISSION_GRANTED }) {
                 invalidateOptionsMenu()
                 handleStartup()
             } else {
```

2022-04-17 23:41 UTC, dorrin-sot commented
ohh i haven't written any kotlin before either and just saw it's similar to java/react😅. but this is exactly how I was planning to write it 👀

2022-04-17 23:51 UTC, dorrin-sot commented
@mikehardy is it ok if I commit it? because it's excatly like yours😅

2022-04-17 23:54 UTC, mikehardy commented
Yes please do! It's your solution after all. I was just playing with Kotlin and I got that value out of it :-)

2022-04-17 23:56 UTC, mikehardy commented
Be careful with #10928 just going in as well literally just now - but as I was reviewing that I was looking for how it would merge with this...I don't think it will conflict, code changes in separate areas.

2022-04-18 00:07 UTC, mikehardy approved these changes
Looks great, and hey! Kotlin! Thanks a bunch for this @dorrin-sot I've got high hopes it nails the problem on my device (which I've kept "broken" so it's a great test). 🤞

2022-04-18 00:16 UTC, mikehardy commented
I have to go to dinner shortly and really really want this in so I just dropped the first (java) commit to fix the lint error and re-pushed, I'm testing this PR locally and if it works I'll merge and we'll get an alpha

2022-04-18 00:20 UTC, david-allison approved these changes

2022-04-18 00:27 UTC, mikehardy commented
Boom - local tests all good (I run the same suite of gradle tasks that CI runs)

2022-04-18 00:28 UTC, merged

2022-04-18 13:10 UTC, dorrin-sot commented
@mikehardy Could you reoopen this PR too? I added a commit which fixed it for me