Kotlin Migration of CardBrowserTest
ankidroid/Anki-Android pull request #10925
Opened 2022-04-17 22:15 UTC by raymondwzeng

## Purpose / Description
This is a redo of #10903 as some self-inflicted branching issues made it difficult to review. Mainly a test of #10779, this time following the instructions to the letter.

## Approach
It seems like there were some issues that occurred last time due to slight variations in how I followed the instructions. I directly shadowed the instructions highlighted in `migrate.sh`, and this time it ran without issues.

I also included the previous suggestions in the last PR.

## How Has This Been Tested?
Build succeeded, ran the test without issues.

![CardBrowserKt](https://user-images.githubusercontent.com/13594022/163734127-ba4c4e07-c775-4a84-a8dd-4080c8d318db.jpg)

## Learning (optional, can help others)
Rebasing makes things a _bit_ cleaner than merge commits.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-17 22:16 UTC, david-allison requested changes
The rename commit is incorrect, the file is not renamed to .java

2022-04-17 22:20 UTC, david-allison requested changes
```
> Task :AnkiDroid:lintPlayDebug FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt:490: Error: Use kotlin.test.assert[Not]Null OR kotlin.test.junit.JUnitAsserter instead of JUnit in Kotlin [LegacyNullAssertionDetector from com.ichi2.anki.lint]
        Assert.assertNotNull(shownDialog)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt:493: Error: Use kotlin.test.assert[Not]Null OR kotlin.test.junit.JUnitAsserter instead of JUnit in Kotlin [LegacyNullAssertionDetector from com.ichi2.anki.lint]
        Assert.assertNull(dialogAfterRecreate)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors, 0 warnings
```

2022-04-17 22:25 UTC, raymondwzeng commented
Interesting. Yeah, I did miss that. Not sure how it managed to build in the first place.

2022-04-17 22:26 UTC, david-allison commented
> Interesting. Yeah, I did miss that. Not sure how it managed to build in the first place.

That's lint, it still builds. The first commit is still an issue.

2022-04-17 22:40 UTC, mikehardy commented
> The rename commit is incorrect, the file is not renamed to .kt

I think this is still an issue, the diff in github web UI is the tell-tale sign of it. Instead of showing it as a diff between the java and kt they are showing up as a delete (all red file, separate) and an add (all green file, separate) so review is not really possible 🤔

2022-04-17 23:30 UTC, raymondwzeng commented
Thanks for the heads-up to both of you. Testing it again on another fresh branch, it seems like git is not having fun with `mv` in particular, which is causing the first commit to fail to comply with expectations. Not sure if it's an issue on my end.

2022-04-18 00:33 UTC, david-allison requested changes
Thanks! Looks great, few import changes which we should revert.

2022-04-18 00:33 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
> +        assertThat(browser.isShowingSelectAll, Is.`is`(false))
import `Is`

2022-04-18 00:33 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
> +        assertThat(browser.cardCount(), Matchers.equalTo(5L))
import `Matchers` to match the old code

2022-04-18 00:33 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
> +        val b = getBrowserWithNotes(5)
ideally aim to add back the newlines which were removed. Same for all the file

2022-04-18 00:33 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
> +    fun cannotChangeDeckToDynamicDeck() {
`@KotlinCleanup(".any()")`

2022-04-18 00:33 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
> +        val shadowActivity = Shadows.shadowOf(browser)
import `Shadows`

2022-04-18 00:33 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
> +        Assert.assertTrue(cards[0].isLoaded)
import `Assert`

2022-04-18 00:52 UTC, raymondwzeng commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
> +        assertThat(browser.isShowingSelectAll, Is.`is`(false))
I'm a bit confused about this directive (same with the other import requests). The test already imports the object as a whole, and attempting to import the method directly seems to make the compiler unhappy. Is there something I'm missing?

2022-04-19 06:08 UTC, raymondwzeng commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
> +        assertThat(browser.isShowingSelectAll, Is.`is`(false))
@david-allison just checking in about the above comment regarding imports (not sure if GitHub comments not directly rooted to the issue/PR sends a notification).

2022-04-19 22:25 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
> +        assertThat(browser.isShowingSelectAll, Is.`is`(false))
Sorry! Missed this

* `gh pr checkout 10925`
* Open `CardBrowserTest`
* Press Alt+Enter when cursor is over `Is`
* Select `Import members from org.hamcrest.Is`
* It compiles and runs

2022-04-20 17:42 UTC, raymondwzeng commented
Phew, that was a journey. Thanks for the help. The methods have been imported, and things seem to be running smoothly.

![CardBrowserKt](https://user-images.githubusercontent.com/13594022/164290598-1a82d3d3-9f2e-44dd-81d9-b6cb57d2e508.jpg)

2022-04-25 22:58 UTC, david-allison requested changes
I'm really sorry this sat, please ping me if things are waiting for me for more than a day, and every 2 days after that. My notification queue is really busy and things sadly do get lost, this was one of them, it's great and it's so close to going in!

2022-04-25 22:58 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
> +            Arrays.stream(cardBrowser.cardIds)
import `Arrays`

2022-04-25 22:58 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
> +                .noneMatch { flag1: Long -> flag1 != flagForAll.toLong() }
remove the `toLong()` (I think)

2022-04-27 06:22 UTC, raymondwzeng commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
> +                .noneMatch { flag1: Long -> flag1 != flagForAll.toLong() }
Compiler throws an error at me. The implied data type is `Int`. Changing declaration to explicitly long type causes another issue with `cardBrowser.flagTask()` @ 304 because that expects an int. Between the either/or for casting, I prefer leaving it as-is, unless a better solution is possible?

2022-04-27 11:42 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
> +                .noneMatch { flag1: Long -> flag1 != flagForAll.toLong() }
Let's leave it as is

2022-04-28 15:28 UTC, david-allison approved these changes

2022-04-29 18:02 UTC, mikehardy approved these changes
That's a huge one - thank you!

2022-04-29 18:22 UTC, merged