Migrate SeekBarPreferenceCompat to kotlin
ankidroid/Anki-Android pull request #10929
Opened 2022-04-18 04:10 UTC by lukstbit

## Purpose / Description

Migrates the SeekBarPreferenceCompat.java file to kotlin following the kotlin migration guide. This finishes the migration for the `com.ichi2.preferences` package.

## How Has This Been Tested?

Ran the usual tests.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-18 13:04 UTC, david-allison requested changes

2022-04-18 13:04 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/preferences/SeekBarPreferenceCompat.kt
> +    override fun onSetInitialValue(restore: Boolean, defaultValue: Any) {
bug: this should be `Any?`

2022-04-18 13:04 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/preferences/SeekBarPreferenceCompat.kt
> +class SeekBarPreferenceCompat : DialogPreference {
I believe we can move some of the `onCreateDialogView` variables to `lateinit`

2022-04-18 13:41 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/preferences/SeekBarPreferenceCompat.kt
> +    override fun onSetInitialValue(restore: Boolean, defaultValue: Any) {
Fixed!

2022-04-18 13:43 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/preferences/SeekBarPreferenceCompat.kt
> +class SeekBarPreferenceCompat : DialogPreference {
@david-allison I've added a `@KotlinCleanup` to `mSuffix: String?` which could be made a `lateinit var`, the others are `Int` primitives and can't be made lateinit.

2022-04-18 13:44 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/preferences/SeekBarPreferenceCompat.kt
> +class SeekBarPreferenceCompat : DialogPreference {
Sounds good to me, thanks!

2022-04-18 13:45 UTC, david-allison approved these changes

2022-04-19 13:20 UTC, mikehardy approved these changes
works for me - thanks!

2022-04-19 13:38 UTC, merged