Unit test: for catch part in JSONObject
ankidroid/Anki-Android pull request #10933
Opened 2022-04-18 14:55 UTC by UvrajSB

## Pull Request template

## Purpose / Description
Unit test: for catch part of the getBoolean, getInt, getLong, getStrong functions in JSONObject

## How Has This Been Tested?
I have tested by running it on my local machine
![image](https://user-images.githubusercontent.com/73571511/163826812-e84de5a9-99c3-49c7-8318-f8b9b3cb3b1e.png)

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-18 15:24 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
> +        Assert.assertThrows(JSONException::class.java) {
Inside `AnkiAssert`:

`assertThrows<JSONException> { }`

2022-04-18 15:24 UTC, david-allison requested changes
minor request to make the code slightly more readable

2022-04-19 13:10 UTC, mikehardy reviewed
This looks okay to me with the minor thought that I'm not sure if the name `object` is poorly chosen since it seems to require backticks to differentiate from a reserved word. Couldn't any non-reserved word be used there to avoid the backticks?

2022-04-19 13:36 UTC, mikehardy commented
> This change is not just there for my part but for the all the other tests as well and it has already been acknowledged as a kotlin cleanup in the file. So it doesn't come under the scope of this PR in my opinion.
> I'll change that and open a new PR for that

Oh - good point - I'm +1 then - on the new PR please use a descriptive title, I see it linked here as "Kotlin Cleanup" which as a reviewer makes me think "wow, they cleaned up ALL the KotlinCleanup fantastic - but it's going to be a big PR" ;-). Probably a file name would be good in title

2022-04-19 13:36 UTC, mikehardy approved these changes

2022-04-19 13:37 UTC, mikehardy commented
also it will probably conflict when I merge this - all the details all the time - that's programming :sweat_smile:

2022-04-19 13:37 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
> +        Assert.assertThrows(JSONException::class.java) {
this has been addressed I checked

2022-04-19 13:39 UTC, mikehardy commented
Sorry for the extra noise via comments @UvrajSB - I see that you were actually just commenting on the general Kotlin Cleanup issue now, so of course the comment makes sense. Ignore me - will merge this in a moment, running re-integration tests against head of main branch now locally

2022-04-19 13:49 UTC, merged