Fixed "CheckMedia" causing crash
ankidroid/Anki-Android pull request #10931
Opened 2022-04-18 13:18 UTC by dorrin-sot

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes #10892 

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-18 13:27 UTC, dorrin-sot commented
if this actually fixes it, I would like to check other instances where write permission was previously checked to see if read permission check is also needed

2022-04-18 13:28 UTC, mikehardy requested changes
:thinking: the first commit is already merged, so it should be dropped from this PR
I can't think of a situation where we would want to have write but not read?
Seems like the rename is not necessary and the hasStorageAccessPermission check should be extended to check READ too every time?

2022-04-18 13:45 UTC, mikehardy approved these changes
Could do it :-), curious second set of eyes from @david-allison

2022-04-18 14:02 UTC, dorrin-sot commented
Do I add to the tests that test permission requirements?

2022-04-19 21:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +        return hasStorageReadAccessPermission(context) && hasStorageWriteAccessPermission(context)
I believe this means we show 'Welcome to AnkiDroid' for existing users. Can we go through this logic with a fine-tooth comb to ensure that the UX is correct.

https://github.com/ankidroid/Anki-Android/blob/cf0cef3c3285af22986804411e63836d83e513d8/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt#L473-L498

2022-04-20 15:52 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +        return hasStorageReadAccessPermission(context) && hasStorageWriteAccessPermission(context)
Oh If the welcome dialog shouldn't be shown to non-first-time users, shouldn't we save it in sharedpreferences instead of savedInstanceState in order to avoid it getting displayed on every startup?

https://user-images.githubusercontent.com/59933477/164271542-2090cb6e-9304-493d-885e-71b0a5f65fab.mov

2022-04-22 13:27 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +        return hasStorageReadAccessPermission(context) && hasStorageWriteAccessPermission(context)
> Oh If the welcome dialog shouldn't be shown to non-first-time users, shouldn't we save it in sharedpreferences instead of savedInstanceState in order to avoid it getting displayed on every startup?

I think if shared preferences has any entry in it for version information, that indicates that it is not the first startup, and the welcome dialog should not be shown

2022-04-23 20:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +        return hasStorageReadAccessPermission(context) && hasStorageWriteAccessPermission(context)
> ```diff
> getSharedPreferences("", MODE_PRIVATE).all.isEmpty()
> ```

Could you submit this?

This is incorrect at the very least, we should be using `AnkiDroidApp.getSharedPreferences()`

2022-04-26 14:35 UTC, dorrin-sot commented
@david-allison Still awaiting your feedback 😁👀

2022-04-26 15:41 UTC, david-allison requested changes
Sorry for the delay, lots to think about when working here and I wanted to be 'fresh'

2022-04-26 15:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        if (hasStorageAccessPermission(this)) {
(nit): this doesn't seem necessary

2022-04-26 15:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        val sharedPrefsIsntEmpty = AnkiDroidApp.getSharedPrefs(this).all.isNotEmpty()
This no longer shows the 'welcome' dialog

2022-04-26 17:50 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        val sharedPrefsIsntEmpty = AnkiDroidApp.getSharedPrefs(this).all.isNotEmpty()
Can I add a boolean shared preference for `firstStartup` with a default of true?

2022-04-26 18:02 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        val sharedPrefsIsntEmpty = AnkiDroidApp.getSharedPrefs(this).all.isNotEmpty()
I'd say "welcomeMessageDismissed", but really: up to you

2022-04-26 19:00 UTC, david-allison approved these changes

2022-04-26 20:43 UTC, mikehardy approved these changes
Alright! Here we go  - thanks for this @dorrin-sot

2022-04-26 20:56 UTC, merged