Test coverage for the login method of `MyAccount.kt`
ankidroid/Anki-Android pull request #10937
Opened 2022-04-18 16:46 UTC by Propo41

## Pull Request template

## Purpose / Description

added test coverage for the login method of `MyAccount.kt` using instrumentation tests.

## Approach
Used Espresso to do the tests

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-18 17:26 UTC, krmanik commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/MyAccountTest.kt
> +        val testEmail = "randomEmail@gmail.com"
This email is also okay. But we should consider this RFC standard email.
https://en.wikipedia.org/wiki/Email_address

2022-04-18 17:37 UTC, krmanik commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/MyAccountTest.kt
> +    fun testLoginFails_noEmailProvided() {
```suggestion
    fun testLoginFailsNoEmailProvided() {
```

2022-04-18 17:38 UTC, krmanik commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/MyAccountTest.kt
> +    fun testLoginFails_noPasswordProvided() {
```suggestion
    fun testLoginFailsNoPasswordProvided() {
```

2022-04-18 17:38 UTC, krmanik commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/MyAccountTest.kt
> +    fun testLoginFails_invalidCredentials() {
```suggestion
    fun testLoginFailsInvalidCredentials() {
```

2022-04-18 18:11 UTC, Propo41 commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/MyAccountTest.kt
> +        val testEmail = "randomEmail@gmail.com"
Changed it to "random.email@domain.com". Sounds good?

2022-04-18 18:16 UTC, krmanik commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/MyAccountTest.kt
> +        // @TODO: remove hardcoded string and use string resource "R.string.email_id_empty"
flagging TODO, it should be completed in this PR

2022-04-18 19:12 UTC, mikehardy commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/MyAccountTest.kt
> +        val testEmail = "randomEmail@gmail.com"
@Propo41 the RFC is specific, `domain.com` is not a valid domain for testing purposes. It's kind of interesting that this is needed, and is important to understand for future - otherwise if you use a real domain it might end up getting used somehow in real life, then a real mailbox gets stuffed with test junk

https://datatracker.ietf.org/doc/html/rfc2606#page-2

```

   To safely satisfy these needs, four domain names are reserved as
   listed and described below.

                   .test
                .example
                .invalid
              .localhost

      ".test" is recommended for use in testing of current or new DNS
      related code.

      ".example" is recommended for use in documentation or as examples.

      ".invalid" is intended for use in online construction of domain
      names that are sure to be invalid and which it is obvious at a
      glance are invalid.

      The ".localhost" TLD has traditionally been statically defined in
      host DNS implementations as having an A record pointing to the
      loop back IP address and is reserved for such use.  Any other use
      would conflict with widely deployed code which assumes this use.
```

As @krmanik indicated, use `example.com` exactly. Do not invent domains for testing

2022-04-18 19:13 UTC, Propo41 commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/MyAccountTest.kt
> +        // @TODO: remove hardcoded string and use string resource "R.string.email_id_empty"
I had a difficulty in this part. How do I use the string resources without the context here? I know that we can use `withText(int id)` but I can't seem to combine this with `hasErrorText(string str)`. Some suggestions would be helpful!

2022-04-18 19:21 UTC, Propo41 commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/MyAccountTest.kt
> +        val testEmail = "randomEmail@gmail.com"
Thanks! Didn't know this before. I'll make the changes.
It's quite fascinating that just within 2 days I've gathered some really interesting knowledge. First about that github squash and line endings and now this. And also learned about testing in Android which I've never tried before! I guess open source contributions are indeed the best way to learn new stuff!

2022-04-18 22:17 UTC, Propo41 commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/MyAccountTest.kt
> +        // @TODO: remove hardcoded string and use string resource "R.string.email_id_empty"
@krmanik I used one approach. Can you please check if it's appropriate?

2022-04-19 09:35 UTC, krmanik commented
@Propo41 
Is it possible to move this test from `androidTest` to `test`? Because our 90% tests is in `test`.
You can check multiple implementation in `test` folder, which may be helpful.
This is example [DeckPickerTest](https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java)

2022-04-19 09:35 UTC, krmanik commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/MyAccountTest.kt
> +        // @TODO: remove hardcoded string and use string resource "R.string.email_id_empty"
@Propo41 
There is `getTestContext` function defined in codebase. You can use this also.
```java
Context targetContext = getTestContext();
```

2022-04-19 11:24 UTC, krmanik commented
@Propo41 
I have tested and it is possible to use only `test` instead of `androidTest`
This code example related to this PR will be helpful.
```kotlin
@RunWith(AndroidJUnit4::class)
class MyAccountTest : RobolectricTest() {

    @Test
    fun testLoginFailsNoEmailProvided() {
        val controller = buildActivity(MyAccount::class.java)
                .create().start().resume()
        saveControllerForCleanup(controller)
        val myAccount = controller.get()

        myAccount.findViewById<TextInputEditField>(R.id.password).setText("password")
        myAccount.findViewById<Button>(R.id.login_button).performClick()
        val error = myAccount.findViewById<TextInputEditText>(R.id.username).error
        assertEquals(error, targetContext.getString(R.string.email_id_empty))
    }
}
```

2022-04-19 11:46 UTC, Propo41 commented
> @Propo41 
> I have tested and it is possible to use only `test` instead of `androidTest`
> This code example related to this PR will be helpful.
> ```kotlin
> @RunWith(AndroidJUnit4::class)
> class MyAccountTest : RobolectricTest() {
> 
>     @Test
>     fun testLoginFailsNoEmailProvided() {
>         val controller = buildActivity(MyAccount::class.java)
>                 .create().start().resume()
>         saveControllerForCleanup(controller)
>         val myAccount = controller.get()
> 
>         myAccount.findViewById<TextInputEditField>(R.id.password).setText("password")
>         myAccount.findViewById<Button>(R.id.login_button).performClick()
>         val error = myAccount.findViewById<TextInputEditText>(R.id.username).error
>         assertEquals(error, targetContext.getString(R.string.email_id_empty))
>     }
> }
> ```

Thanks. I'll make the changes by tonight!

2022-04-19 14:25 UTC, mikehardy commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/MyAccountTest.kt
> +        val testEmail = "randomEmail@gmail.com"
That's been my experience, it's a bit of a firehose at first (so much to learn! like, seriously, so much) but when working on commercial projects with time pressure and budget pressure most of that stuff gets ignored in the name of just shipping something, so open source really does allow for all sorts of deeper knowledge sharing / learning

2022-04-20 00:52 UTC, david-allison requested changes
I don't think we want to be connecting to AnkiWeb in the final test, we probably want to mock out the connection response.


This puts a nontrivial load on the server from our GitHub runners, and becomes an end-to-end test.

Is there a reason we're testing under Espresso rather than Robolectric?

2022-04-20 11:47 UTC, Propo41 commented
> I don't think we want to be connecting to AnkiWeb in the final test, we probably want to mock out the connection response.
> 
> This puts a nontrivial load on the server from our GitHub runners, and becomes an end-to-end test.
> 
> Is there a reason we're testing under Espresso rather than Robolectric?

I didn't know about this until @krmanik mentioned it. I will make the changes using Roboelectric.

2022-04-20 12:21 UTC, krmanik commented
@Propo41 
Also you have to mock webserver in test for correct and incorrect responses.
https://duckduckgo.com/?q=mock+webserver+in+junit

2022-04-28 09:31 UTC, Propo41 commented
@krmanik updated the changes.

2022-04-28 09:36 UTC, krmanik approved these changes

2022-04-28 09:37 UTC, krmanik commented
Final test for login using both username and password not implemented. It may be in separate PR.

2022-04-28 16:36 UTC, david-allison approved these changes

2022-04-28 16:36 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/MyAccountTest.kt
> +        val myAccount = controller.get()
`startActivityNormallyOpenCollectionWithIntent` is less code

2022-04-29 08:45 UTC, Propo41 commented
Did the squash thing for the first time. Feels good!

2022-04-29 10:13 UTC, david-allison commented
Much appreciated! We can squash commits via GitHub

For larger changes, if you write atomic commits which all compile, we can rebase them onto `main` for a clean history.

So, rebasing/squashing/editing your work and force-pushing here is strongly encouraged, it's very powerful and really glad you got to grips with it :)

2022-04-29 17:05 UTC, mikehardy approved these changes
Nice!

2022-04-29 18:01 UTC, merged

2022-06-05 20:55 UTC, mikehardy commented
Hi there! APRIL OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [April 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-04-01..2022-04-30)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of March.

Please note that GSoC contributions are okay for this process. Our philosophy is that our users have donated to AnkiDroid for all contributions. The only PRs that will not go through the OpenCollective process are ones directly related to am accepted GSoC project from a selected participant, since those receive a stipend from GSoC itself.

Please understand that this means the monthly budget we have for payments might be stretched a bit and the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!