Fixed issue #10917
ankidroid/Anki-Android pull request #10941
Opened 2022-04-18 18:50 UTC by Elizalll

## Pull Request template

## Purpose / Description
Add the 'Always Show' and 'Show if room',  two choices to the item of "Set TTS language".

## Fixes
Fixes _Link to the issues._

## Approach

I replaced

`@array/custom_button_labels_menu_and_disabled` and `@array/custom_button_values_menu_and_disabled`

with

`@array/custom_button_labels` and `@array/custom_button_values`

for entry and values array of Set TTS language List Preference.

## How Has This Been Tested?

It is tested on my computer and android phone.

## Checklist

- [x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-19 06:28 UTC, raymondwzeng commented
Ouch, looks like it hit a lint snag. Probably commenting out that line within the resource file would do the trick.

As a side note, it would be awesome to have a more descriptive PR title (e.g. "Added more choices for customButtonSelectTts" in a similar vein to the last PR of the type) so that other contributers can get some context at a glance. Cheers!

2022-04-19 06:50 UTC, Elizalll commented
> Ouch, looks like it hit a lint snag. Probably commenting out that line within the resource file would do the trick.
> 
> As a side note, it would be awesome to have a more descriptive PR title (e.g. "Added more choices for customButtonSelectTts" in a similar vein to the last PR of the type) so that other contributers can get some context at a glance. Cheers!

Thank you for your friendly reminder! This is my first pr and I will remember your word. Thanks again.🌹

2022-04-19 12:23 UTC, mikehardy commented
Hi @Elizalll :wave: 
I cannot tell from your issue title what this PR is doing. There is no actual meaningful context in the title
The "link to the issues" part of the template is empty, so github does not crosslink them and there is no easy way for a reviewer to navigate back and forth

2022-04-19 12:25 UTC, mikehardy requested changes
To keep this PR focused on one task (so it reviews more easily and is more easily tested) please revert the changes I indicated were unrelated

2022-04-19 12:25 UTC, mikehardy commented on .idea/codeStyles/Project.xml
> -          <package name="java.util" alias="false" withSubpackages="false" />
Do not commit unrelated items in a PR --> A PR should solve *one thing* and *one thing only*
More explicitly, this change should be reverted, nothing in this file should be changed in this PR

2022-04-19 12:25 UTC, mikehardy commented on AnkiDroid/jacoco.gradle
> +        xml.required = true
Nothing in this file should be changed as part of this PR. It is not related to fixing TTS languages
Revert this change please, and propose it as a separate PR if desired

2022-04-19 12:43 UTC, Elizalll commented on AnkiDroid/jacoco.gradle
> +        xml.required = true
@mikehardy Hi, I'm sorry. I know what you mean. I know I should not change jacobo.gradle, but actually my last commit in this pr got ERROR in here:

<img width="1390" alt="image" src="https://user-images.githubusercontent.com/85177562/164004762-00a9807a-a254-438d-8052-a28b893f4c20.png">

So I try to find this bug in local. And after I run `gradle --warning-mode all`, I found:

```
The Report.enabled property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the required property instead. See https://docs.gradle.org/7.2/dsl/org.gradle.api.reporting.Report.html#org.gradle.api.reporting.Report:enabled for more details.
        at jacoco_1m4pq0der21kf1nj1k6hmfe38$_run_closure7$_closure18.doCall(/Users/elizalll/My/SoftwareEngineering/Anki-Android/AnkiDroid/jacoco.gradle:121)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
```
So in order to pass the check of my commit, I have no way but do this.
#### Could you please tell me how to deal with this situation? Thank you very much.

ps: Here are the remaining of the output of `gradle --warning-mode all`, but I haven't change the file that it needs.
```
> Configure project :api
The AbstractArchiveTask.destinationDir property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the destinationDirectory property instead. See https://docs.gradle.org/7.2/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:destinationDir for more details.
        at build_7hegmw43s5ne7yculnuemuhig$_run_closure8.doCall(/Users/elizalll/My/SoftwareEngineering/Anki-Android/api/build.gradle:132)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
The AbstractArchiveTask.archiveName property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the archiveFileName property instead. See https://docs.gradle.org/7.2/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:archiveName for more details.
        at build_7hegmw43s5ne7yculnuemuhig$_run_closure8.doCall(/Users/elizalll/My/SoftwareEngineering/Anki-Android/api/build.gradle:133)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

```

2022-04-19 12:50 UTC, Elizalll commented
> Hi @Elizalll 👋
> I cannot tell from your issue title what this PR is doing. There is no actual meaningful context in the title
> The "link to the issues" part of the template is empty, so github does not crosslink them and there is no easy way for a reviewer to navigate back and forth

Got that! Thank you🌹. Now I have changed them. Please tell me if something still get wrong.

2022-04-19 13:24 UTC, mikehardy commented on AnkiDroid/jacoco.gradle
> +        xml.required = true
Deprecations are not errors. You may safely ignore deprecation *warnings* unless you are doing a PR to specifically address the warnings

Errors in androidTest locally should be investigated (and handled in a separate PR or tracking issue). androidTest failures in CI are because of flaky emulator startup behavior and are tracked in #10672 

Please revert the changes, there is nothing to handle in this PR.

2022-04-19 14:03 UTC, Elizalll commented on AnkiDroid/jacoco.gradle
> +        xml.required = true
OK, the reverse is done. Sorry and thanks again.

2022-04-19 14:31 UTC, mikehardy requested changes
You checked this box:

>  UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

But you have not provided any before / after screenshots, I can't judge if this change actually has the intended effect?

2022-04-19 14:31 UTC, mikehardy commented on AnkiDroid/src/main/res/values/constants.xml
> +<!--     <string-array name="custom_button_labels_menu_and_disabled">
If we make changes in the app we just go ahead and delete things. Git history will always allow us to see the delete and revert if needed, but can you imagine what the code would look like in a couple years if we just left commented-out code everywhere? And the app is 10+ years old! You wouldn't be able to read anything.

Instead of commenting out these two chunks, if your proposed change is to remove them, go ahead and delete the lines

2022-04-19 14:41 UTC, Elizalll commented on AnkiDroid/src/main/res/values/constants.xml
> +<!--     <string-array name="custom_button_labels_menu_and_disabled">
OK, I will delete it right now(I just afraid that something unexpected will happen...). Thank you for your advice!

2022-04-19 15:01 UTC, Elizalll commented
> You checked this box:
> 
> > UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
> 
> But you have not provided any before / after screenshots, I can't judge if this change actually has the intended effect?

Sorry, I forgot to put them on. Now I got the after screenshot:
<img width="319" alt="image" src="https://user-images.githubusercontent.com/85177562/164030356-7c8f86ea-8857-4bc4-b1e0-f1759211c892.png">
And I didn't get the before screenshot which I forgot take it. But according to the `entryValues="@array/custom_button_values_menu_and_disabled"` is the array[0,3], I think it is the image that the in the issue description like this:
<img width="513" alt="image" src="https://user-images.githubusercontent.com/85177562/164034286-be187484-2f9c-4d38-afda-b8811f47dd87.png">

2022-04-20 03:28 UTC, Elizalll commented
@mikehardy hello there. I don't know what to do now. Could you please tell me should I change some code(and soon delete) to make another check until it turns green or just stay waiting? And I saw :
```
Ensure to add the custom icons to Preferences.java's reset functionality
TODO: Add a unit test
```
in AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml and I would like to write the unit test, **do you think it is necessary?** And, I can't find Preferences.java in the respository(may be it is because preferences_custom_buttons.xml is written in 2016), may you tell me which class I should look into? Thank you very much!

2022-04-20 12:05 UTC, mikehardy approved these changes
This looks good to me now - I'm not sure on the other questions you have I'll flag this for a second review so someone mentoring for GSoC can pick it up but the code looks okay and the tests should pass now

2022-05-06 21:03 UTC, merged