Add support for hierarchy tag
ankidroid/Anki-Android pull request #10966
Opened 2022-04-19 18:07 UTC by RogerDTZ

# Purpose / Description
Anki Desktop has already supported hierarchical tags. Users have asked for its implementation in AnkiDroid.

## Fixes
Fixes #10095 

## Approach
Based on Anki Desktop's way to parse hierarchical tags, a tag is still stored in pure string format. The tag parser uses double colons `::` to split levels. A sample tag would be `folder1::folder2::mytag`.

For `com.ichi2.anki.dialogs.tags.TagsList`, it now automatically adds virtual intermediate tags (i.e., ancestors of all real tags). In this way, a tag tree can be built and displayed properly and tag queries relevant to intermediate tags can be constructed. These virtual tags will not be added into database unless they are checked. An intermediate tag will be marked as indeterminate if one of its descendants is checked.

In `com.ichi2.libanki.Finder._findTag`, the SQL construction is updated so that a query matches descendants of the target tag.

In `com.ichi2.anki.dialogs.tags.TagsArrayAdapter`, a tag tree is maintained, so that tags are shown in a collapsible view.

![tag_view](https://user-images.githubusercontent.com/38598790/164067573-deb77d3e-d31d-4e91-bd26-5f01745135d0.jpg)
![filter_result](https://user-images.githubusercontent.com/38598790/164067015-f39dfbc5-aadb-4a6c-ba55-7b6109806b49.jpg)

## How Has This Been Tested?

For new utilities related to hierarchical tag in `com.ichi2.utils.TagsUtil`, tests are added to make sure that hierarchical tag is decomposed correctly.

For `com.ichi2.libanki.Finder`, tests are added to make sure that the tag query supports hierarchical query correctly.

For `com.ichi2.anki.dialogs.tags.TagsDialog`, test are added to make sure that the tag filter and the new tag operation work properly. These tests also implicitly check if `TagsArrayAdapter` works fine with the tree data structure.

Old tests related to these classes are all passed. Unit tests are all passed. The GUI is tested on a physical device, Huawei P40 Pro.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-19 23:24 UTC, mikehardy commented
Awesome! Took a conflict - probably because of kotlin migration but it appears to just be in the test file, so - hopefully easy to handle? I flagged it for review in the interim but it does need de-conflicting so we can run CI on it. Thanks!

2022-04-20 02:16 UTC, david-allison requested changes
This is awesome! I'm really happy with the testing!

**Actionable Feedback**

* Tapping on the `>` arrow doesn't expand the tags
* The animation on tapping an expandable tag does not play to the end
  * Create one "root" tag, and one "parent" tag with a child
  * The 'root' animation is much smoother 

**Maybe actionable**

I'll think about this and will get back to you, please message me if there's no reply within 24 hours.

There's quite a lot of complexity in:

* `getRealPosition`
* `buildTagTree`
* `toggleExpansionState`
* `TagUtils`

My first thought is that this complexity be reduced if we either:
* Define a `sequence` over the visible nodes 
* change the `Int`s  into `TagTreeNode`s
  * Moves the complexity inside `TagTreeNode` 
  * Generally a maintenance issue when creating the tree, due to circular references 

I'll have a think tomorrow and come up with concrete suggestions

2022-04-20 02:43 UTC, RogerDTZ commented
Indeed, current method maintains the tree using `Int`s directly, which is not that good for organization. I started with this method since the `mFilteredList` was also indexed using `Int`.

Seems like I looked down upon the number of tags and the complexity they bring, so I used literally brute force to implement the tree query and maintenance. Is it necessary to introduce advanced data structure for optimization?

For tag prefix comparison (i.e., decide whether a tag is the ancestor of another), a prefix-hash in the perspective of level may be used.

2022-04-20 05:02 UTC, RogerDTZ commented
I have fixed issues related to UI. Waiting for your furthur suggestions! :smiley:

2022-04-21 10:43 UTC, RogerDTZ commented
Hi @david-allison , I am still not sure if your mentioning "complexity" means the time complexity of string processing, the time complexity of tree maintenance, or the code complexity in implementation.

> **Maybe actionable**
> 
> I'll think about this and will get back to you, please message me if there's no reply within 24 hours.
> 
> There's quite a lot of complexity in:
> 
> * `getRealPosition`
> * `buildTagTree`
> * `toggleExpansionState`
> * `TagUtils`
> 
> My first thought is that this complexity be reduced if we either:
> 
> * Define a `sequence` over the visible nodes
> * change the `Int`s  into `TagTreeNode`s
>   
>   * Moves the complexity inside `TagTreeNode`
>   * Generally a maintenance issue when creating the tree, due to circular references
> 
> I'll have a think tomorrow and come up with concrete suggestions

2022-04-21 22:56 UTC, david-allison commented
Hi, sorry for the lack of response, I've had a few busy days and still haven't had the time to go through the code to confirm my thoughts.

I'm referring to code complexity: I'd rather the code was as simple as possible. We're unlikely to have tag trees which are large enough to warrant complex data structures.

It feels feasible to do the following to reduce complexity:

*  using `sequence { }` to implement 
  * the iterator in `getRealPosition`
  * the iterator in `toggleExpansionState`

converting the following to a nested function
```
                        mTree[y].children.add(x)
                        mTree[y].subtreeSize += mTree[x].getContributeSize()
```

* (maybe reduces complexity) `buildTagTree` combines the concerns of building the tree and modifying the members of the class, is it possible to split these concerns

2022-04-21 22:58 UTC, david-allison reviewed
This is awesome! I'm probably not going to be in a position to dive deep into suggesting simplifications in the next few days, and the code is **really** high quality.

I'm happy for it to be merged, as long as you've taken a look through my comment on the main PR and either implemented the changes, or decided that it didn't do anything to improve complexity or wasn't feasible to implement. 

Both are fine.

2022-04-21 22:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
> +            if (!TextUtils.isEmpty(mExpandTarget)) {
use `.isNotEmpty` - that should remove the !! in the next line

2022-04-21 22:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
> +        if (!TextUtils.isEmpty(rawTag)) {
ditto - isNotEmpty

2022-04-22 10:37 UTC, RogerDTZ commented
Thank @david-allison for your reply and appreciation! :smile:

I have managed to change all `Int`s into `TagTreeNode`s and move complexity into the node class. It seems much more organized now! Meanwhile, the utilities in `TagsUtil` have been rewritten using sequence so that they are more intelligible.

---
After the above modification,
* `getVisibleTagTreeNode` (was `getRealPosition`) 
* `TagTreeNode.toggleExpandState` (was `toggleExpansionState`) 

have become really short. I'm not sure if it is a good idea to use `sequence { }` to implement them again, especially for `TagTreeNode.toggleExpandState`. I made a trial in `getVisibleTagTreeNode` using `sequence`, with the original version commented below. Please let me know if you intend to the style like this, or it should be implemented more subtly, or it is OK to use the original implementation.

---

I am confused about using `isNotEmpty`. I cannot find the corresponding function except `com.brsanthu.googleanalytics.internal.GaUtils.isNotEmpty`, which is also not able to remove the `!!` given that `mExpandTarget` and `rawTag` are nullable objects. Statements like `!TextUtils.isEmpty()` seem to have been used everywhere in the project :open_mouth:

---

There is an upsetting issue about testing. In this test for #8807, `Collections` class is used to for `mockStatic`

https://github.com/ankidroid/Anki-Android/blob/22c5da65224a6bbd6c619dbed5c7adc27fe91573/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsListTest.kt#L410-L423

I found that once `java.util.Collections.singletonList` is invoked inside the mock, it triggers an infinite recursion. To reproduce that, simply add
```kotlin
assertEquals(listOf("test"), listOf("test"))
```
anywhere in the test.
![image](https://user-images.githubusercontent.com/38598790/164691224-fa451941-f5a5-42cc-8ff9-fafb9881c2d8.png)

The bug of test stops me from passing all tests (this is the only failed test), since utilities in `TagsUtil` can naturally produce singletonList (calling `.split("::")` on a string that does not contain `::` will produce a singletonList, which definitely makes sense). Sure, I can bypass it, but that will add unnecessary complexity to the code.

2022-04-22 14:13 UTC, RogerDTZ commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
> +        /*
Is it OK to use the below commented implementation?

2022-04-22 17:43 UTC, RogerDTZ commented
Seems like Mockito suggests in `MockedStatic`:
> Note: We recommend against mocking static methods of classes in the standard library or classes used by custom class loaders used to executed the block with the mocked class. A mock maker might forbid mocking static methods of know classes that are known to cause problems. Also, if a static method is a JVM-intrinsic, it cannot typically be mocked even if not explicitly forbidden.

The test mocks the entire `Collections` class to check whether `Collections.sort()` has never been called. Is it reasonable to mock a standard library to test that?

2022-04-23 03:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
> +        /*
This isn't how I'd lay things out - I'll have a hard look first thing tomorrow.

2022-04-23 03:56 UTC, david-allison commented
`isNotEmpty`: it's a kotlin extension on lists and `CharSequence`:

`"".isNotEmpty()` - should work in a .kt file

2022-04-23 16:16 UTC, david-allison requested changes
I've had a thorough look through this. 

* `@Ignore` the unit test - I had a shot at mocking just the method  using `mockk`, and there were problems with the generic in parameter, and the fact that `sort` has two overrides 

**Bugs:**

* tag: `foo::bar::baz`
* tag: `baz`
* `bar` becomes indeterminate
* untag: `baz`
* `bar` remains indeterminate

----
**Questionable behavior** - for discussion. I don't think there's a good solution

* tag: `foo::bar::baz`
* tag: `baz`
* tag: `foo`
* `foo` is checked, although `bar` is unchecked

UX:

We /may/ want tapping on a 'leaf' node to toggle the checkbox - implementer's choice.

* Performing a search of "" resets the expand state to false of all the tags

2022-04-23 16:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
> +        var remain = index
Let's use this code rather than the sequence

2022-04-23 16:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
> +    // root node of the tag tree
`/*` for comments

2022-04-23 16:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
> +            while (node.parent != null && node.expandState) {
maybe: 

```kotlin
val delta = ...
for (parentNode in iterateParentsOf(this) {
    if (!parentNode.expandState) break
    parentNode.subtreeSize += delta
}
```

2022-04-23 16:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
> +        var expandState: Boolean
I'd rename to `isExpanded`

2022-04-23 16:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
> +            if (!TextUtils.isEmpty(mExpandTarget)) {
`mExpandTarget.isNotEmpty()`

2022-04-23 16:21 UTC, RogerDTZ commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
> +    data class TagTreeNode(
Yes, I am currently working on better documentation.

2022-04-23 17:38 UTC, RogerDTZ commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
> +        if (!TextUtils.isEmpty(rawTag)) {
```kotlin
 if (!rawTag.isNullOrEmpty()) {
```
works fine here and removes `!!` in the next line.

`isNotEmpty` cannot be called on a nullable object.

2022-04-23 17:40 UTC, RogerDTZ commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
> +            if (!TextUtils.isEmpty(mExpandTarget)) {
I have changed `mExpandTarget` into a non-nullable `String` so that `isNotEmpty()` will work fine here.

2022-04-24 02:56 UTC, RogerDTZ commented
I have implemented the feature that a checkbox turns from indeterminate to unchecked if all descendants are not checked. Besides, clicking on an indeterminate checkbox will check it instead of uncheck it. The cycle will be `INDETERMINATE -> CHECKED -> UNCHECKED (or INDETERMINATE if some descendant is checked) -> CHECKED -> UNCHECKED (or INDETERMINATE) -> ...`. Corresponding tests have been added.

Expand states are now persistent between filtering.

Tapping on a leaf node now directly toggles the checkbox.

2022-04-25 13:52 UTC, david-allison requested changes
This is awesome! A few design tweaks and we're good to go.

**Accessibility**

* Can we add a `contentDescription` to `holder.mExpandButton`
   * I'd imagine something like: `getString(R.string.expand_tag, holder.node.tag.replace("::", " "))`

**Design**

On a root tag with children, make the horizontal spacing between`mExpandButton` and the dialog/tag label equal.

----

If there are no 'nested' tags in the hierarchy, remove the additional padding on the root elements.

**UX**

unsure - please push back if you don't like it: When the dialog is opened and a subtag is 'checked', I feel the tree should be expanded to the subtag.

* `foo::bar::baz`
* `baz` is tagged
* Open Dialog
* `foo` is currently not expanded

----

If the user presses "space" in the "Add Tag" dialog, it should be replaced with "::" rather than not working

https://github.com/ankidroid/Anki-Android/blob/9b3d462246b699bf91f4fdf5b5baf0786106c28b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt#L179-L188

**Dev**

If there are tests which aren't written, could you add `@NeedsTest("description")` to them (space -> :: in the tag dialog for example).

* I'd like to get better at unit testing, and this feels like a good intermediate step

**To be moved to new issues**

Long-press a tag to add a subtag: open "add tag" with: `$current_tag + ::` as the input

Double the size of the checkbox to 48x48 - I misclick this a little

2022-04-25 13:53 UTC, david-allison commented
@mikehardy @Akshay0701 Could you take a look when feasible?

2022-04-25 15:59 UTC, Akshay0701 reviewed
Thanks! @RogerDTZ, 

really appreciate your efforts, Code looks good to me, just minor comments,

most of the UI and other suggestions given by David, and I agree with his points, especially:
-> Long-press a tag to add and 
-> expand when subtag is checked

2022-04-25 15:59 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
> +        return "((n.tags like ? escape '\\') or (n.tags like ? escape '\\'))";
both statements before and after or are the same, I am missing something here?

2022-04-25 15:59 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
> +    private var mTreeRoot: TagTreeNode?
```suggestion
    /**
     * The root node of the tag tree.
     */
    private var mTreeRoot: TagTreeNode?
```

2022-04-25 15:59 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
> +        holder.node = getVisibleTagTreeNode(position)!!
in `getVisibleTagTreeNode` there are two cases that will return null values, you should handle it here, otherwise it might give nullexpections and crash the app.

2022-04-25 15:59 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
> +        return if (mTreeRoot != null) mTreeRoot!!.subtreeSize else 0
```suggestion
        return mTreeRoot?.subtreeSize ?: -0
```
optional

2022-04-25 17:09 UTC, RogerDTZ commented on AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
> +        return "((n.tags like ? escape '\\') or (n.tags like ? escape '\\'))";
The tag search needs to match the tag itself and its descendants, so there are two different search patterns to be filled in the SQL query.

2022-04-25 17:14 UTC, RogerDTZ commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
> +        holder.node = getVisibleTagTreeNode(position)!!
For `onBindViewHolder`, the `position` argument is limited by `getItemCount()` whose return value is provided by the size of the tree. Therefore, `getVisibleTagTreeNode` will never return null when called in `onBindViewHolder` if the tree is well maintained.

2022-04-25 17:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
> +        return "((n.tags like ? escape '\\') or (n.tags like ? escape '\\'))";
See the lines above. `?` is substituted  with `args`

2022-04-25 17:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
> +                    return@InputFilter "::"
There was a bug here that this doesn't fix:

* If a keyboard suggestion is made with a trailing space, it was replaced with ""

I'm fine to leave this for another PR, just to be sure you're aware if any testing issues occur

2022-04-25 17:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +    }
if you're adding anew variable, feel free to stop with the Hungarian notation, we'll be moving away from it.

2022-04-25 18:02 UTC, RogerDTZ commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +    }
Got it. I was simply trying to keep the name in parallel to another variable `mCycleBackToIndeterminate`. Should I fix the other one too?

2022-04-25 18:03 UTC, RogerDTZ commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
> +                    return@InputFilter "::"
Sorry, I have just noticed that you mentioned a bug related to the filter in another issue. So far the, changing does not cause any testing trouble as it passes all unit tests.

2022-04-25 18:25 UTC, RogerDTZ commented
Hi @david-allison and @Akshay0701 ! Thank you for your great suggestions! 👍 

I have already fixed nearly all your suggestions, except fot the long-press feature. Maybe this should be put into a new issue, as david suggested.

The failed unit test (windows) is related to `SchedV2`, a `NullPointerException` happens at
https://github.com/ankidroid/Anki-Android/blob/9de60878ba191f5bde01ff7896763346bdde594f/AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java#L1050
which is strange since
* I did not touch any code related to the database manipulation, except the query constructor in `Finder.java`
* I develop the project in windows, and all unit tests pass locally.
* Unit tests on other 2 platforms pass normally on Github.

I will see what I can do with this problem. Meanwhile I will wait for your furthur instruction if there are still more problems :sparkles:

2022-04-25 23:00 UTC, david-allison commented
I believe that's a flaky test, I've rerun CI and we'll see. I really appreciate your effort and quick responses, this really is great and I'd like to get it in as soon as feasible.

2022-04-25 23:03 UTC, david-allison requested changes
* Add tag
* type `foo`
* type a blank space
* content is replaced with `::`

Also the comment above the method which handles this needs to be changed

2022-04-25 23:16 UTC, RogerDTZ commented
I think it will be better if we let the expander of leaves display something (for example, a small hollow circle) rather than nothing . The padding for leaf is sometimes confusing in complicated hierarchy --- it is hard too see which level a leaf belongs to.

New asset required since I have not found any apt one.

2022-04-25 23:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
> +            filter.refresh()
```suggestion
            mTagsArrayAdapter!!.filter.apply {
                setExpandTarget(tag)
                refresh()
            }
```

2022-04-25 23:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +    }
sure!

2022-04-25 23:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
> +            val delta = if (vh!!.mCheckBoxView.state == CheckBoxTriStates.State.CHECKED) 1 else -1
I'd consider extracting `vh!!.mCheckBoxView.state` into a private property, and importing `CheckBoxTriStates.State` to make this be 

`if (checkBoxState == CHECKED)`

2022-04-25 23:30 UTC, david-allison commented
Sure! Sounds good to me. I've made a few in Inkscape, or feel free to ask in our Discord

2022-04-25 23:40 UTC, RogerDTZ commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
> +            val delta = if (vh!!.mCheckBoxView.state == CheckBoxTriStates.State.CHECKED) 1 else -1
Agree, I will work on that.

2022-04-26 10:05 UTC, RogerDTZ commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
> +                    return@InputFilter "::"
I have fixed this bug and improve the colon completion as well (see my comments for details).

2022-04-26 10:14 UTC, RogerDTZ commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
> +        holder.node = getVisibleTagTreeNode(position)!!
Hi @Akshay0701, does my explanation makes sense to you? I really cannot find a good way to "handle" the null value. It will either make `getVisibleTagTreeNode` strange or make `onBindViewHolder` loss its binding target. However the null value should never occur in normal situations.

2022-04-26 13:02 UTC, Akshay0701 commented
I am also in favour of getting this merge asap, let's just bring out follow issues and approve this,

David, see if anything is pending...

2022-04-28 15:50 UTC, david-allison approved these changes
Thanks so much, could you make the 'follow-on' issues mentioned in the review so they don't get lost

2022-04-28 16:45 UTC, RogerDTZ commented
I have created some issues for further development. Anything else pending? 🎉

2022-04-28 21:10 UTC, david-allison commented
> I have created some issues for further development. Anything else pending? 🎉

Waiting for a second review, should bea quick process. ping me if you hear nothing in 24 hours

2022-04-29 14:38 UTC, Akshay0701 commented
Not sure about that, but
![Capture](https://user-images.githubusercontent.com/52353967/165966262-35da7b9b-15a0-43ab-b226-6c840ae8f977.png)

David or mike might have an idea about this?

2022-04-29 14:54 UTC, Akshay0701 approved these changes
LGTM, @RogerDTZ 

<img src="https://media4.giphy.com/media/ZfK4cXKJTTay1Ava29/giphy.gif"/>

2022-04-29 18:36 UTC, mikehardy approved these changes
That is a really substantial feature, thank you!!

2022-04-29 18:56 UTC, merged

2022-06-05 20:53 UTC, mikehardy commented
Hi there! APRIL OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [April 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-04-01..2022-04-30)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of March.

Please note that GSoC contributions are okay for this process. Our philosophy is that our users have donated to AnkiDroid for all contributions. The only PRs that will not go through the OpenCollective process are ones directly related to am accepted GSoC project from a selected participant, since those receive a stipend from GSoC itself.

Please understand that this means the monthly budget we have for payments might be stretched a bit and the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!