Added custom layout to the spinner adapter in the card browser activity to prevent the overlapping of various interactive components on the screen
ankidroid/Anki-Android pull request #10968
Opened 2022-04-19 19:57 UTC by jaivsh

## Purpose / Description
In the card browser, when the spinner 2 is clicked, it expands to the whole of the screen height wise, which is causing the overlap of the spinner items on top of UI elements on the upper action bar. 

<img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhqD1Es_njfpeXKVtEORwFBgKuJuzleHng3_WnJgF_UipB6jlIQmTeZ9BI3ie1Sdio0qd5I8C6Ny-SFdztFnm4HzRPSaiqSJI_8f7oW79GT5afU_FDajZ5gHGq6CG10PRYH85g0abVbRr3ipyl5vh8wj_DXBG_-G_0yKo8reBG51jOR28rocr6ldsn08g/s1920/Screenshot_20220420_010445.png" width="225" height="400" />

<img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjniOukXvGx--049xg65ITitLGQuNbPtRxlTAGcpfQNbU03ZCSCCe22lgNJB3c8Y6ph8OI7cyodRSPrRH_H9Iz77CXkq0YWk2Ht1dnBYrf8LgFsUvqWjKZGw6NEL_mMY1X0O4KLXLfNSYSs6cmMaqdq13Q-KenVbYHje-qnVHaCwDV0ChJOAYN15-YiIQ/s1920/ankiinitialscreenshot.png" width="225" height="400" />

## Fixes
I've rescaled the layout of the spinner options so as  

<img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjNN8TxGTntMl-KmW2y6jqKU6mjU4mbIjqHFlztWk35IM9B_KB5-fZKkvfwbzfunItRIunPuKbzpQ06wDj1A0d9u8APUsBuUePmHr8xzDVM-Fs2U8Xd6m1Xuohi0OjvPtU-OaKSbCTooeoikBvnPylSm-52wZyhLYyBeUOZDJ18ESyJ8PsJOGWh1wiCeg/s1920/ankidroid_workdone1.png" width="225" height="400" />

## Approach
I've created a custom layout to be used as the drop down view resource of the spinner adapters. In that layout, I've rescaled the sizes of spinner options by observing its behavior on various different testing devices, so as to fix the overlap problem and make the user experience better. 

## How Has This Been Tested?

I've run and verified the implementation on pixel 2(1080x1920) mobile, pixel 3a(1080x2220) mobile, and nexus 7(1220x1920) tablet emulators. Apart from that, I've also tested it on Motorola zoom tablet and Redmi note 3 physical devices to verify the new design and behavior.

## Checklist

- [Y] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [Y] You have a descriptive commit message with a short title (first line, max 50 chars).
- [Y] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [Y] You have commented your code, particularly in hard-to-understand areas
- [Y] You have performed a self-review of your own code
- [Y] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [Y] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-19 23:25 UTC, mikehardy commented
It appears to have a tiny lint error:

```

> Task :AnkiDroid:ktlintMainSourceSetCheck FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:583:9 Missing space after //

```

I'll still flag it for review though, missing one space character must be fixed but should not block review I think

2022-04-23 08:01 UTC, jaivsh commented
Hello, @mikehardy, I've updated all the things here. Thanks for telling this!

2022-05-10 15:38 UTC, mikehardy requested changes
Thorough testing - fantastic, one nit typo, and one question on deck spinner interaction with the change to action bar draw on top boolean

2022-05-10 15:38 UTC, mikehardy commented on AnkiDroid/src/main/res/values/styles.xml
> +        <item name="android:layout_height">40dp</item>ac
Looks like a typo in there ?

```suggestion
        <item name="android:layout_height">40dp</item>
```

2022-05-10 15:38 UTC, mikehardy commented on AnkiDroid/src/main/res/values/styles.xml
> +        <item name="android:drawSelectorOnTop">false</item>
will this affect other selectors? I don't think so but we have deck spinners in lots of dialogs, your testing on this specific change was very thorough (thank you!) and I just want to know if you also looked at note edit screen deck selection, card-browser long-press multi-select mode change deck spinner

2022-05-10 15:39 UTC, mikehardy commented
By the way - really sorry for the delay, it's taken me this long to get back to just the "review" queue from the "pending merge" and "second review" queues - really hectic the last couple weeks!

2022-08-18 21:29 UTC, mikehardy approved these changes
comments appear resolved

2022-08-18 21:42 UTC, merged