Migrate AssetHelperTest to Kotlin
ankidroid/Anki-Android pull request #10999
Opened 2022-04-21 06:50 UTC by oyeraghib

## Pull Request template

## Purpose / Description
Migrate AssetHelperTest to Kotlin

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-22 13:45 UTC, mikehardy requested changes
Looks great! One small change to note the needed future change to a non reserved word

2022-04-22 13:45 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/utils/AssetHelperTest.kt
> +    fun guessMimeTypeTest() {
Can you add this and re-push the second commit?

```suggestion
    @KotlinCleanup("is --> equalTo")
    fun guessMimeTypeTest() {
```

2022-04-22 15:07 UTC, oyeraghib commented on AnkiDroid/src/test/java/com/ichi2/utils/AssetHelperTest.kt
> +    fun guessMimeTypeTest() {
Okay, but what is it for ?

2022-04-22 15:08 UTC, david-allison requested changes
One nit regarding imports

2022-04-22 15:08 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/utils/AssetHelperTest.kt
> +        MatcherAssert.assertThat(guessMimeType("test.txt"), CoreMatchers.`is`("text/plain"))
Re-import `MatcherAssert` and `CoreMatchers`.

Remove the import of `AssetHelper` so it's `AssetHelper.guessMimeType`

The Kotlin Migration process often fails to handle imports, OR adds imports to static methods unnecessarily.

2022-04-22 19:57 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/utils/AssetHelperTest.kt
> +        MatcherAssert.assertThat(guessMimeType("test.txt"), CoreMatchers.`is`("text/plain"))
Still an issue: 

> Remove the import of AssetHelper so it's AssetHelper.guessMimeType

2022-04-22 21:38 UTC, david-allison approved these changes
Awesome, thanks!

2022-04-23 19:14 UTC, mikehardy approved these changes
nice! Thank you

2022-04-23 19:45 UTC, merged