Migrate CollectionUtilsTest to Kotlin
ankidroid/Anki-Android pull request #11000
Opened 2022-04-21 07:04 UTC by oyeraghib

## Pull Request template

## Purpose / Description
Migrate CollectionUtilsTest to Kotlin

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-22 13:46 UTC, mikehardy requested changes
Thanks!
one kotlincleanup notation needed I think

2022-04-22 13:46 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/utils/CollectionUtilsTest.kt
> +        MatcherAssert.assertThat(getLastListElement(testList), CoreMatchers.`is`(3))
kotlincleanup is -> equalto

2022-04-22 20:21 UTC, david-allison requested changes

2022-04-22 20:21 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/utils/CollectionUtilsTest.kt
> +        MatcherAssert.assertThat(getLastListElement(testList), CoreMatchers.`is`(3))
import `MatcherAssert`, `CoreMatchers`

2022-04-22 20:21 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/utils/CollectionUtilsTest.kt
> +        AnkiAssert.assertEqualsArrayList(arrayOf(1, 2, 3), toTest)
import: `AnkiAssert`

2022-04-22 20:21 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/utils/CollectionUtilsTest.kt
> +import com.ichi2.utils.CollectionUtils.getLastListElement
Remove these two lines and use `CollectionUtils.method` at the call site (to match the Java)

2022-04-22 21:46 UTC, david-allison approved these changes

2022-04-23 19:15 UTC, mikehardy approved these changes
excellent

2022-04-23 21:04 UTC, merged