Migrate MaxExecFunctionTest to Kotlin
ankidroid/Anki-Android pull request #11009
Opened 2022-04-21 14:54 UTC by oyeraghib

## Purpose / Description
Migrate MaxExecFunctionTest to Kotlin

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-22 16:06 UTC, david-allison requested changes
one nitpick, thanks!

2022-04-22 16:06 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/utils/MaxExecFunctionTest.kt
> +        mFunction = Mockito.mock(Runnable::class.java)
import `Mockito`

2022-04-22 17:40 UTC, oyeraghib commented on AnkiDroid/src/test/java/com/ichi2/utils/MaxExecFunctionTest.kt
> +        mFunction = Mockito.mock(Runnable::class.java)
I am sorry but isn't Mockito already imported here ? Or should I import Mockito.mock so that it can be removed from here ?

2022-04-22 20:00 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/utils/MaxExecFunctionTest.kt
> +        mFunction = Mockito.mock(Runnable::class.java)
Sorry for the lack of clairty, shorthand for "import members from org.mockito.Mockito".

We want the 'before' code to be as similar to the 'after' code with respect to imports.

2022-04-22 20:05 UTC, oyeraghib commented on AnkiDroid/src/test/java/com/ichi2/utils/MaxExecFunctionTest.kt
> +        mFunction = Mockito.mock(Runnable::class.java)
Thanks for clarifying :)

2022-04-22 20:06 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/utils/MaxExecFunctionTest.kt
> +        mFunction = Mockito.mock(Runnable::class.java)
Should be on the Alt+Enter menu if you have the cursor over `Mockito`

2022-04-22 21:48 UTC, david-allison approved these changes

2022-04-23 19:18 UTC, mikehardy approved these changes
:boom:

2022-04-23 21:44 UTC, merged