Migrate ContentResolverUtilTest to Kotlin
ankidroid/Anki-Android pull request #11001
Opened 2022-04-21 07:13 UTC by oyeraghib

## Pull Request template

## Purpose / Description
Migrate ContentResolverUtilTest to Kotlin

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-22 13:51 UTC, mikehardy requested changes
Thank you!
Has a couple kotlincleanups to do post migration

2022-04-22 13:51 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/utils/ContentResolverUtilTest.kt
> +        MatcherAssert.assertThat(filename, Is.`is`("filename_from_cursor.jpg"))
kotlincleanup is -> equalto

2022-04-22 13:51 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/utils/ContentResolverUtilTest.kt
> +        Mockito.`when`(uri.scheme).thenReturn(ContentResolver.SCHEME_CONTENT)
kotlincleanup when -> whenever - should annotate the whole class with it, it is in a couple methods

2022-04-22 20:27 UTC, david-allison requested changes
The newlines in the Java have been removed in the conversion, could you add them back in

2022-04-22 20:27 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/utils/ContentResolverUtilTest.kt
> +        val mock = Mockito.mock(ContentResolver::class.java)
import: `Mockito`

2022-04-22 20:27 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/utils/ContentResolverUtilTest.kt
> +        MatcherAssert.assertThat(filename, Is.`is`("filename_from_cursor.jpg"))
import: `MatcherAssert`, `Is`

2022-04-22 20:27 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/utils/ContentResolverUtilTest.kt
> +        Mockito.`when`(mock.getType(ArgumentMatchers.any())).thenReturn("image/gif")
import: `ArgumentMatchers`

2022-04-22 22:08 UTC, oyeraghib commented
@david-allison Android Studio is suggesting to convert the methods to private and make the class open (final). Should I do that ?

![ss2](https://user-images.githubusercontent.com/40427461/164801994-b47485cb-6cf0-45dc-a99b-5ade9a8da0a4.png)

2022-04-22 22:26 UTC, david-allison commented
> @david-allison Android Studio is suggesting to convert the methods to private and make the class open (final). Should I do that ?
> 
> ![ss2](https://user-images.githubusercontent.com/40427461/164801994-b47485cb-6cf0-45dc-a99b-5ade9a8da0a4.png)

Add `@KotlinCleanup("IDE-based lint")`

2022-04-23 00:04 UTC, david-allison approved these changes

2022-04-23 00:04 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/utils/ContentResolverUtilTest.kt
> +    @KotlinCleanup("is --> equalTo")
Feel free to stick this on the class in future

2022-04-23 19:16 UTC, mikehardy approved these changes
thank you!

2022-04-23 21:10 UTC, merged