kotlin Migration of cloze Test
ankidroid/Anki-Android pull request #11014
Opened 2022-04-21 16:45 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
Kotlin migration of clozeTest .

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-21 16:47 UTC, ShridharGoel commented on AnkiDroid/src/test/java/com/ichi2/libanki/ClozeTest.kt
> +        assertThat(d.addNote(f), Matchers.`is`(Matchers.greaterThan(0)))
Import the method directly

2022-04-22 16:02 UTC, david-allison requested changes
nits, then good to go

2022-04-22 16:02 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/ClozeTest.kt
> +        assertEquals(1, d.addNote(f).toLong())
`toLong()` gets added incorrectly by the conversion, could you remove it

2022-04-22 16:02 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/ClozeTest.kt
> +@RunWith(AndroidJUnit4::class)
`@KotlinCleanup("is -> equalTo")`

2022-04-24 14:07 UTC, mikehardy approved these changes
Looks good thanks!

2022-04-24 14:12 UTC, david-allison approved these changes

2022-04-24 14:58 UTC, merged