[Kotlin Migration] ReviewerNoParamTest
ankidroid/Anki-Android pull request #11011
Opened 2022-04-21 15:42 UTC by BrayanDSO

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-22 16:08 UTC, david-allison requested changes
Awesome! One nitpick

2022-04-22 16:08 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
> +    @KotlinCleanup(".edit {}")
I thought I'd caught something, awesome, thanks so much!!!

2022-04-22 16:08 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
> +            Gesture.SWIPE_UP -> "gestureSwipeUp"
import `Gesture`

2022-04-22 16:17 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
> +            Gesture.SWIPE_UP -> "gestureSwipeUp"
Gesture is imported. Should I directly import each gesture?

2022-04-22 17:30 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
> +            Gesture.SWIPE_UP -> "gestureSwipeUp"
> Gesture is imported. Should I directly import each gesture?

As it was on the 'before' side, so yes, or import `*` if feasible.

2022-04-22 19:58 UTC, david-allison approved these changes

2022-04-23 19:22 UTC, mikehardy approved these changes
:rocket:

2022-04-24 01:20 UTC, merged