[Kotlin Migration ] MediaTest
ankidroid/Anki-Android pull request #11013
Opened 2022-04-21 16:05 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
Kotlin migration of MediaTest .

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-22 16:04 UTC, david-allison requested changes
minor nit, rest looks good

2022-04-22 16:04 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/MediaTest.kt
> -     *****************/
revert to how it was

2022-04-23 14:01 UTC, david-allison approved these changes

2022-04-23 19:23 UTC, mikehardy approved these changes
thank you!

2022-04-24 01:27 UTC, merged