enhancements: get list of addons model from json containing array of addons data
ankidroid/Anki-Android pull request #11023
Opened 2022-04-22 11:50 UTC by krmanik

## Pull Request template

## Purpose / Description
In download/install addon screen, the addons are listed in with addon model info. It needs to parse addon data then addon model from json strings. 

(In next PR mapping [anki-js-addon.json](https://github.com/krmanik/anki-js-addon-json/blob/main/anki-js-addon.json) to view)
<img src="https://user-images.githubusercontent.com/12841290/164708516-132c4123-4b0e-4033-a436-83342604687e.png" height=500px></img>

## Fixes
Fixes 

## Approach
1. Created a repository for listing and exporting all valid addons containing `ankidroid-js-addon` keywords from npmjs using GitHub actions
https://github.com/krmanik/anki-js-addon-json
2. There are two json file exported. 
    a) `anki-js-addon.json` - will be used in download/install screen, containing all addons with  `ankidroid-js-addon` keywords
    b) `test-js-addon.json` - will be used in unit test, containing only two addons info
3. Used this to map json to AddonData list 
```kotlin
val mapper = AnkiSerialization.objectMapper
val addonsData = mapper.readValue(packageJsonUrl, object : TypeReference<MutableList<AddonData>>() {})
```
4. Then used `getAddonModelFromAddonData` in loop to get all valid AddonModel and added to list
5. Finally returned list of addon model

## How Has This Been Tested?
Created unit test for this in `AddonModelTest.kt`

## Learning (optional, can help others)

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-22 20:35 UTC, david-allison requested changes
small nitpicks, seems reasonable in general

2022-04-22 20:35 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/AddonModelTest.kt
> +        shadowOf(getMainLooper()).idle()
Shouldn't be needed

2022-04-22 20:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonData.kt
> +    return Pair(addonsModelList, ImmutableList(errorList))
```suggestion
    return Pair(addonsModelList, errorList.toList())
```

2022-04-22 20:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonData.kt
> +            errorList.add(result.second.toString())
interesting: one "string" per addon, maybe we want an `errorList.addAll()` here 

Implementer/Reviewer2's choice

2022-04-22 20:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonData.kt
> +    val addonsData = mapper.readValue(packageJsonUrl, object : TypeReference<MutableList<AddonData>>() {})
can you comment above that this is a network request

2022-04-22 20:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonData.kt
> +        addonsModelList.add(result.first!!)
Hmm... I'm surprised the !! is needed. There may be a bug, but it looks fine

2022-04-22 20:35 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/AddonModelTest.kt
> +        addon1.dist["tarball"]?.let { assertTrue(it.endsWith(".tgz")) }
Shouldn't this test fail if the tarball is null?

2022-04-23 09:14 UTC, krmanik commented on AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/AddonModelTest.kt
> +        addon1.dist["tarball"]?.let { assertTrue(it.endsWith(".tgz")) }
Change the test null pointer exception will thrown when null

2022-04-23 09:15 UTC, krmanik commented on AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/AddonModelTest.kt
> +        addon1.dist["tarball"]?.let { assertTrue(it.endsWith(".tgz")) }
Change the test null pointer exception will thrown when null

2022-04-23 21:53 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/AddonModelTest.kt
> +        assertTrue(addon1.dist["tarball"]!!.endsWith(".tgz"))
`assertThat(, endsWith())` - gives a better message

2022-04-24 03:03 UTC, krmanik commented on AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/AddonModelTest.kt
> +        assertTrue(addon1.dist["tarball"]!!.endsWith(".tgz"))
Done, Thanks

2022-04-24 14:26 UTC, david-allison approved these changes

2022-04-24 14:26 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonData.kt
> +            Timber.i("Not a valid addon for AnkiDroid, the errors for the addon:\n %s", result.second.toString())
```suggestion
            Timber.i("Not a valid addon for AnkiDroid, the errors for the addon:\n %s", result.second)
```

2022-04-24 14:26 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/AddonModelTest.kt
> +        val url = URL("https://raw.githubusercontent.com/krmanik/anki-js-addon-json/main/test-js-addon.json")
Second reviewer: flagging that this unit test needs network access

2022-04-24 14:48 UTC, krmanik commented on AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/AddonModelTest.kt
> +        val url = URL("https://raw.githubusercontent.com/krmanik/anki-js-addon-json/main/test-js-addon.json")
I have put json and tgz file in assets folder. I will also move this to assets folder.

2022-04-24 15:51 UTC, krmanik commented on AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/AddonModelTest.kt
> +        val url = URL("https://raw.githubusercontent.com/krmanik/anki-js-addon-json/main/test-js-addon.json")
Moved to assets folder.

2022-04-24 15:57 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/AddonModelTest.kt
> +        addonsPackageListTestJson = FileOperation.getFileResource("test-js-addon.json")
test does not need network access, thankfully @david-allison

2022-04-24 16:00 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonData.kt
> +    val addonsData = mapper.readValue(packageJsonUrl, object : TypeReference<MutableList<AddonData>>() {})
The test itself has a JSON in test resources, which is nice as it won't have external resources required
And then this method takes the JSON URL as a param which is also nice. I'm not against having a curated collection of them like in the krmanik repo but I would like to have the URL be configurable or for there to be an easy way to do a wide search on npmjs.com or whatever URL people want. The idea being to make the easy stuff easy (krmanik repo) but the hard stuff possible (install some random package from whatever new package repo in the future)

2022-04-24 16:00 UTC, mikehardy approved these changes
This looks good to me - all my comments were just adding context as I understand it

2022-04-24 16:09 UTC, merged

2022-04-24 16:10 UTC, mikehardy commented
For anyone watching order of operations here - with all the kotlin migrations going in - which have a tendency to create cross-PR build failures on main when merged, I'm pulling every PR that goes "pending merge", running all tests from CI locally, and then merging them when they pass, one by one. So I am occasionally merging stuff before GitHub Actions is passing but I'm definitely running tests....

2022-04-24 16:12 UTC, krmanik commented
Thanks