[Kotlin Migration] ImportUtilsTest
ankidroid/Anki-Android pull request #11029
Opened 2022-04-22 18:26 UTC by BrayanDSO

## Pull Request template

## Purpose / Description
My semicolon key broke

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-22 20:13 UTC, david-allison requested changes
minor: Cleanup added an unexpected import

2022-04-22 20:13 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/utils/ImportUtilsTest.kt
> +import com.ichi2.utils.ImportUtils.isValidPackageName
remove this and use `ImportUtils.isValidPackageName` at the call sites - same as the Java

2022-04-22 21:47 UTC, david-allison approved these changes

2022-04-23 19:27 UTC, mikehardy approved these changes
nice

2022-04-24 02:04 UTC, merged