Migrate ResourceLoader to Kotlin
ankidroid/Anki-Android pull request #11030
Opened 2022-04-22 19:04 UTC by oyeraghib

## Pull Request template

## Purpose / Description
Migrate ResourceLoader to Kotlin

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-22 20:09 UTC, david-allison requested changes
looks good! only nitpicks

2022-04-22 20:09 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/utils/ResourceLoader.kt
> +    @KotlinCleanup("is --> equalTo")
`inputStream`

2022-04-22 20:09 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/utils/ResourceLoader.kt
>          if (!TextUtils.isEmpty(name)) {
`@KotlinCleanup("name.isNotEmpty()")`

2022-04-22 20:09 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/utils/ResourceLoader.kt
> +            Assert.assertTrue(dir.mkdir())
import `Assert`

2022-04-22 21:39 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/utils/ResourceLoader.kt
> +    @KotlinCleanup("is --> equalTo")
```
    @KotlinCleanup("is --> inputStream")
```

2022-04-22 21:40 UTC, david-allison requested changes
one nit

2022-04-22 21:47 UTC, david-allison approved these changes
that was fast! Thank you!

2022-04-23 19:28 UTC, mikehardy approved these changes
excellent

2022-04-24 02:10 UTC, merged