Migrate CardContentProvider to kotlin
ankidroid/Anki-Android pull request #11044
Opened 2022-04-23 08:25 UTC by lukstbit

## Purpose / Description

Migrates the CardContentProvider.java file to kotlin following the migration guide. For reviewers:
- there are a lot of IDE lint issues to solve so I added a single @KotlinCleanup for the class instead of littering the code with tens of annotations
- special care for reviewing the first when clause in the query() method:
```
switch (match) {
            case NOTES_V2: {
                /* Search for notes using direct SQL query */
                String[] proj = sanitizeNoteProjection(projection);
                String sql = SQLiteQueryBuilder.buildQueryString(false, "notes", proj, selection, null, null, order, null);
                //noinspection RedundantCast
here--->   return col.getDb().query(sql, (Object[]) selectionArgs); // Needed for varargs of query
            }
```
The code used by the converter produced an error in the backend in tests for the query method. I had to manually change the code to make it work:

```
                if (selectionArgs == null) {
                    col.db.query(sql)
                } else {
                    col.db.query(sql, *selectionArgs)
                }
```

## How Has This Been Tested?

Rand the usual tests.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-23 14:22 UTC, david-allison requested changes
This is excellent, thanks so much!

2022-04-23 14:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +                    val args = selection.split(",".toRegex()).toTypedArray() // split selection to get arguments like "limit=?"
question on `toRegex` here

2022-04-23 14:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +                }
Can you move this to an extension method on `Db` so we can stay closer to the original implementation

2022-04-25 07:45 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +                    val args = selection.split(",".toRegex()).toTypedArray() // split selection to get arguments like "limit=?"
@david-allison Added by the converter. The java split() method expects a regex so kotlin adds the toRegex() to match it. I deleted it because kotlin also has the split(delimiter) method which is the same thing.

2022-04-25 07:47 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +                }
I've added this method:
```
 /**
     * Helper function to handle calling a java function with vararags from kotlin code
     */
    @KotlinCleanup("After migrating DB.java to kotlin see if this function is still needed")
    private fun DB.queryWithNullSelection(sql: String, selectionArgs: Array<String>?): Cursor? {
        return if (selectionArgs == null) {
            this.query(sql)
        } else {
            this.query(sql, *selectionArgs)
        }
    }
```

Hope it's ok.

2022-04-26 15:45 UTC, david-allison approved these changes
Looks great!

2022-04-26 20:56 UTC, mikehardy approved these changes
Wow! Huge conversion, thank you!

2022-04-26 20:58 UTC, mikehardy commented
@hanpingchinese - please note this PR converting our CardContentProvider from Java to Kotlin. It looks good to us but I know you're an interested party. If you could verify interop between 2.16alpha62 (when it's out, later today) and your app, that would help give us confidence the conversion was sound. Thanks!

2022-04-26 21:23 UTC, merged

2022-05-18 11:26 UTC, mikehardy commented
Hey! Won't be in prod for a while, it's only the alpha releases now