[Kotlin Migration ] MathJaxClozeTest
ankidroid/Anki-Android pull request #11041
Opened 2022-04-23 05:24 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
Kotlin migration of MathJaxClozeTest .

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-23 14:09 UTC, david-allison requested changes

2022-04-23 14:09 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/MathJaxClozeTest.kt
> +        val f = c.newNote(c.models.byName("Cloze"))
ad a newline around this like it was in the Java

2022-04-23 14:09 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/MathJaxClozeTest.kt
> +class MathJaxClozeTest : RobolectricTest() {
cleanup: rename `f` to something usable

We no longer have the type to suggest what it is

2022-04-24 14:13 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/libanki/MathJaxClozeTest.kt
> +class MathJaxClozeTest : RobolectricTest() {
done directly

2022-04-24 14:13 UTC, mikehardy approved these changes
LGTM

2022-04-24 14:13 UTC, david-allison approved these changes

2022-04-24 15:11 UTC, merged