Fix Overflow Icon Color Change on Config Change (Orientation Change)
ankidroid/Anki-Android pull request #11061
Opened 2022-04-24 08:59 UTC by dorrin-sot

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes #11060 

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-24 10:29 UTC, krmanik requested changes

2022-04-24 10:29 UTC, krmanik commented on AnkiDroid/src/main/res/values/theme_plain.xml
> -        <item name="toolbarIconColor">@color/black</item>
This is not recommended fix because it makes note editor toolbar icon white.

<img src="https://user-images.githubusercontent.com/12841290/164972082-48452b0b-5024-4dd5-b66e-3233dae0f9ac.png" height=450px></img>

2022-04-24 13:28 UTC, krmanik commented on AnkiDroid/src/main/res/values/styles.xml
> +        <item name="tint">@color/material_blue_600</item>
It may changes color for other view in different activity. Have you checked it?

2022-04-24 15:56 UTC, dorrin-sot commented
@krmanik Oh I found out that the flags menu was being set to blue too. Turns out, the issue was that if activity was restarted while the action menu was open, `onMenuOpened` would be called **before** `onCreateOptionsMenu` which would reset the colors.
I added a variable for optionsMenu being open, that would be saved in state and if at the end of `onCreateOptionsMenu` it was open, `shouldUseDefaultColor` would be called on menu items to set their color to blue

2022-04-24 16:08 UTC, mikehardy commented
@BrayanDSO the above comment :point_up: might be related to the huge count of "menu bar is acting funny" issues perhaps?

2022-04-24 17:13 UTC, BrayanDSO commented
I pulled this, there is only one issue with the menu items changing their colors 👇
![2022_04_24-13_55_17](https://user-images.githubusercontent.com/69634269/164987954-4066b8fb-b844-49f2-b6de-de131ede0318.png)

#11017, #10697 and #11060 (same as #10732) are the "App bar items color issues". Only the `Undo button` wasn't solved since it's the same as the above.

I think the path taken by @dorrin-sot is right, only the above issue needs to be fixed.

Some other of the app bar issues may be related, but the connection is less clear, so needs investigation.

2022-04-24 19:02 UTC, david-allison commented
Can we add a `@NeedsTest` or two around this area? 

Menu items + colors are new in 2.16, and seem to be the cause of a fair few issues

2022-04-24 20:13 UTC, mikehardy commented
I think per @BrayanDSO investigation (maybe @dorrin-sot as well?) that it was a commit factoring out a chunk of abstract card viewer to reviewer and some order of operations thing that is causing a lot of issues actually...there is some interaction of invalidating items and setting them up again that's not working. It's documented on the related issues at least and they are cross-linked

2022-04-24 20:18 UTC, david-allison commented
> I think per @BrayanDSO investigation (maybe @dorrin-sot as well?) that it was a commit factoring out a chunk of abstract card viewer to reviewer and some order of operations thing that is causing a lot of issues actually...there is some interaction of invalidating items and setting them up again that's not working. It's documented on the related issues at least and they are cross-linked

I thought that was only flags appearing. If it's more issues, then I wasn't aware, and it's on me to fix.

2022-04-24 20:33 UTC, BrayanDSO commented
I guess that commit only affected the flags/marked since IIRC it only changed them. But overall, yes, I believe too that there is a problem with the order of operations of the action bar (and overflow)

2022-04-25 12:16 UTC, dorrin-sot commented
> I pulled this, there is only one issue with the menu items changing their colors 👇 ![2022_04_24-13_55_17](https://user-images.githubusercontent.com/69634269/164987954-4066b8fb-b844-49f2-b6de-de131ede0318.png)

Sorry I don't understand. Do you mean the part that non-overflow icons are also changing color? If so, I did try to research how to check if an icon ended up outside the overflow menu or not (if it was "showAsAction"="ifRoom") but couldn't find anything 😕. Would appreciate any tips and/or tricks on how to check and exclude them from getting colored 👀

2022-04-25 12:42 UTC, dorrin-sot commented
BTW while testing this I found that if Reviewer is opened while on Landscape mode and then rotated, the icons that were marked as `showAsAction="ifRoom"` won't get back in Overflow menu and therefore take alot of space.

https://user-images.githubusercontent.com/59933477/165091031-da7b7ac8-90e0-4339-8025-551dbba76e88.mov

2022-05-10 15:54 UTC, merged