Fix Issue #9978
ankidroid/Anki-Android pull request #11077
Opened 2022-04-24 19:54 UTC by RaidenCHEN

Half Fixed, need to add a refresh function after pressing OK button

## Pull Request

## Purpose / Description
Change  the syncStatus properly for correctly presenting sync badge.

## Fixes
Fixes #9978 

## Approach
Call `SyncStatus.markDataAsChanged()` to change the FSN so when page refresh happens (`onCreateOptionsMenu()`), the badge will show up as expected.

## How Has This Been Tested?

Tested on emulator in Android Studio.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-24 20:01 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +                        if (oldRevValue != n) {
it would make sense to me to do a `col.save()` when this dialog is closed/accepted, rather than manually call `markDataAsChanged`.

Does that seem feasible?

2022-04-24 20:01 UTC, david-allison requested changes
Doesn't compile

```
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt: (220, 29): Unresolved reference: SyncStatus

> Task :AnkiDroid:compilePlayDebugKotlin FAILED
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt: (235, 29): Unresolved reference: SyncStatus
```

2022-04-24 20:05 UTC, RaidenCHEN commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +                        if (oldRevValue != n) {
Yes, I would go try adding it. I had not thought of col.save() before, thanks for the advice, i would keep on working!

2022-05-10 12:55 UTC, david-allison requested changes

2022-05-10 12:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +        // Whether or not to jump straight to the reviewer, default true.
That's a change in functionality, not in a default.

If a user is on a tablet, they can change the custom study options, and it shouldn't jump to the reviewer. 

Instead, we should signal to the DeckPicker that it should refresh the action bar when the dialog is closed.

2022-05-15 12:41 UTC, RaidenCHEN commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +        // Whether or not to jump straight to the reviewer, default true.
Sorry but i have been busy recently. I understand what you said about should not jump to the reviewer, but the deprecated method you mentioned before seemed to have no effect. That's why i thought of forcing the user jump to the reviewer.(I think if they don't need to review, they could just push the back button. Maybe add ) 

And the "if (oldRevValue != n)" part is designed to check whether the value has been change to a different one, since i thought that, if user just select the option but not making a change, the app should not show the sync badge.

Hmmm, so the main problem is on how to refresh a page without switching to other pages, and i don't think that i am capable to write a method for it right now. So, since this version still got some problems, maybe need to find someone else i think. Sorry for not helping with the issue.

2022-08-02 08:42 UTC, closed without merging