Make animation transitions use the same direction of used swipe gesture
ankidroid/Anki-Android pull request #11095
Opened 2022-04-25 18:54 UTC by BrayanDSO

## Fixes
Fixes #11094

## Approach
1. Rename the `DOWN` direction to `DEFAULT` since it was meant to follow the default animation and the default animation (at least on my phone) doesn't come from down
2. Add right and left transitions
3. Pass the used gesture to `executeCommand()`
4. Map swipe gestures to animations with `FADE` as default
5. Pass the mapped animation transitions to the gestures which opens other activities (i.e. Edit card, Card Info and Add Note)

## How Has This Been Tested?

On my phone (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 31, One UI 4.0)

https://user-images.githubusercontent.com/69634269/165154680-fcea43ee-6447-4bf7-a836-7e6e2242083b.mp4

## Learning (optional, can help others)

- Learned a little about android XML animations by reading the existing ones

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-25 19:00 UTC, BrayanDSO commented
I think `executeCommand()` can be moved (on another PR) from `AbstractFlashCardViewer` to `Reviewer` since `Previewer` doesn't use the method

2022-04-25 19:09 UTC, BrayanDSO commented
After reviewing the video, I noticed the opened activities could use the inverse animation when finishing, which may better fit on a following PR

2022-04-25 19:11 UTC, BrayanDSO commented
And maybe changing the default `UP` and `DOWN` animation would be fine. Instead of using a push up/down animation, a cover transition would be prettier IMO, like a card covering the screen

2022-04-25 22:15 UTC, BrayanDSO commented
I particularly don't like both the UP and DOWN animation. I think a "cover" animation, like pulling a card, would be better than the current "Push" animation

2022-04-25 22:35 UTC, david-allison commented
> After reviewing the video, I noticed the opened activities could use the inverse animation when finishing, which may better fit on a following PR or in this one, reviewers' choice

Agreed, follow on PR. Agreed with all the comments, but do what you prefer. I like this as an incremental improvement

2022-04-25 22:35 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt
> +        override fun editCard(fromGesture: Gesture?) {
Is there any way we can `@JvmOverloads` and `= null` this here to stop the question of 'what does editCard(null) mean`

2022-04-25 22:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.kt
> +                ret = ret or processor.executeCommand(command, null)
can we make the arg default to null?

2022-04-25 22:36 UTC, david-allison commented
> I think `executeCommand()` can be moved (on another PR) from `AbstractFlashCardViewer` to `Reviewer` since `Previewer` doesn't use the method

I've been slowly working on cutting down both the CardViewer and the Reviewer.

Agreed, but there's a lot of coupling between both of our JavaScript APIs and the CardViewer.

There really shouldn't be, but it's a large task that I occasionally pick up and make slow progress towards

2022-04-25 22:37 UTC, david-allison requested changes
```
> Task :AnkiDroid:compilePlayDebugAndroidTestJavaWithJavac
/Users/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/androidTest/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.java:45: error: incompatible types: invalid method reference
        PeripheralKeymap peripheralKeymap = new PeripheralKeymap(MockReviewerUi.displayingAnswer(), processed::add);
                                                                                                    ^
    incompatible types: ViewerCommand cannot be converted to int
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error
```

2022-04-25 23:40 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt
> +        override fun editCard(fromGesture: Gesture?) {
Yep

2022-04-26 00:02 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.kt
> +                ret = ret or processor.executeCommand(command, null)
On executeCommand no, because it's a abstract functional interface which means it can't have default values. This applies to the classes that override it as well

2022-04-26 00:04 UTC, david-allison requested changes

2022-04-26 00:04 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +        return executeCommand(which, null)
could you add named argument: `gesture = null`

2022-04-26 00:04 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.kt
> +                ret = ret or processor.executeCommand(command, null)
I half want to say to try an extension method... but I think it'd be best to leave this with `gesture = null` as a named argument

2022-04-26 00:26 UTC, david-allison approved these changes
If it passes CI, awesome!

Do add the follow-up issue to fix the exits as well

2022-04-26 13:34 UTC, mikehardy approved these changes
Nifty tricks right here, and the commit separation made review a breeze, excellent
Gotta say, I personally dislike animations when really focused but when I first encounter an app and see them - so by implication for demos - people love love love them and I do like them as well. Bending animations to your will is a great skill and big crowd-pleaser.
And then for these effects specifically the animations aren't in "deep work" areas of the app, so +1 all around

2022-04-26 13:42 UTC, mikehardy commented
> Anyone like that can disable animations in the Android developer options.

oh for sure - it's a fine line for me anyway, because...they are kinda fancy and I do kinda like them :-). Human brain, strange

2022-04-26 13:42 UTC, merged