kotlin Migration UtilsTest
ankidroid/Anki-Android pull request #11093
Opened 2022-04-25 16:58 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
Kotlin migration of UtilsTest
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-25 17:07 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/UtilsTest.kt
> +class UtilsTest {
`KotlinCleanup("IDE Lint")` - presumably quite a lot of IDE suggestions here

2022-04-25 17:07 UTC, david-allison requested changes
looks great!

2022-04-25 17:57 UTC, david-allison approved these changes
awesome!

2022-04-26 13:28 UTC, mikehardy approved these changes
Nice!

2022-04-26 13:56 UTC, merged