build(deps): fix build issues
ankidroid/Anki-Android pull request #11096
Opened 2022-04-25 20:19 UTC by mikehardy

## Pull Request template

## Purpose / Description
Each commit here does a thing in our build scripts - 

1- a simple jacoco version update (dependabot doesn't see these for whatever reason)
2- using gradle-build-action in all our workflows (I trialed it in emulator tests, works well)
3- hamcrest is used in multiple modules, extract version, update it in lagging module
4- extract our build best practices so lint-rules gets `-Werror` compiler arg "for free" (Fixes #11083)
5- post-process androidTest XML to make sure non-zero # of tests ran (Fixes #11078)

## Fixes
Linked above

## Approach

## How Has This Been Tested?

I tested the -Werror / "extract build common practices" by doing `git revert a70c0f6a381b31ad205388d4b5e3d6e1f3198f15` then running the build - :heavy_check_mark: got the expected error 

```
mike@bistromath:~/work/AnkiDroid/Anki-Android (batch-of-build-work) % !2142
./gradlew clean jacocoTestReport ktlintCheck lint lint-rules:test --rerun-tasks

> Task :AnkiDroid:processPlayDebugMainManifest
/home/mike/work/AnkiDroid/Anki-Android/AnkiDroid/src/test/AndroidManifest.xml:39:9-45:51 Warning:
        provider#org.acra.attachment.AcraContentProvider@android:authorities was tagged at AndroidManifest.xml:39 to replace other declarations but no other declaration present

> Task :lint-rules:compileKotlin FAILED
e: warnings found and -Werror specified
w: /home/mike/work/AnkiDroid/Anki-Android/lint-rules/src/main/java/com/ichi2/anki/lint/rules/NonPositionalFormatSubstitutions.kt: (57, 28): The corresponding parameter in the supertype 'ResourceXmlDetector' is named 'folderType'. This may cause problems when calling this function with named arguments.

FAILURE: Build failed with an exception.
```

I tested the zero tests by starting android API21 locally by itself, API21 + API31, and API31 by itself. 31 by itself passes (:heavy_check_mark:) but any time 21 is in - by itself or in combo with others - :heavy_check_mark:  get the expected error:

```
> Task :AnkiDroid:assertNonzeroAndroidTests FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/mike/work/AnkiDroid/Anki-Android/AnkiDroid/build.gradle' line: 216

* What went wrong:
androidTest executed 0 tests for TEST-TestingAVD_API-31_TAG-PLAY(AVD) - 12-AnkiDroid-play.xml - Probably a bug with the emulator. Try another image.
```

## Learning (optional, can help others)

- Groovy is pretty powerful
- Project-level "afterEvaluate" is pretty powerful to extract common build elements
- Gradle lifecycle task dependency features always have what you need

2022-04-25 20:32 UTC, mikehardy commented on AnkiDroid/build.gradle
> +        File[] listOfFiles = folder.listFiles({d, f-> f ==~ /.*.xml/ } as FilenameFilter)
each emulator generates one XML file per test run, in the flavor directory, and we run Play variant for the jacoco test which we use in CI (and which people should be checking locally...)

2022-04-25 22:47 UTC, david-allison requested changes
Always amazing seeing you do this.

A few questions, then let's get this in

2022-04-25 22:47 UTC, david-allison commented on AnkiDroid/jacoco.gradle
> +    toolVersion = "0.8.8"
(another issue): we might want to extract these

I've ben thinking about a `dependencyVersions.gradle` - it's hard to git log on `build.gradle` as we have so many version number bumps

2022-04-25 22:47 UTC, david-allison commented on .github/workflows/lint.yml
> +          command: ./gradlew :AnkiDroid:compilePlayDebugJavaWithJavac compileLint lint-rules:compileTestJava --daemon
Where in CI do we disable the daemon? Could you add this to the commit message as it's unclear to me

2022-04-25 22:47 UTC, david-allison commented on lint-rules/build.gradle
>      testImplementation "com.android.tools.lint:lint-tests:$lint_version"
in the line below this one, we still leave in `hamcrest-all`. This commit doesn't remove hamcrest from the LHS of the diff?

2022-04-25 22:47 UTC, david-allison commented on AnkiDroid/build.gradle
> -//To be removed when upstream gets patched
flagging for removal

2022-04-25 22:47 UTC, david-allison commented on AnkiDroid/build.gradle
> +            String[] matches = file.readLines().findAll { it.contains('testsuite tests="0"')}
We should be testing for the presence of a known good (nonzero) value, rather than the absence of a value. 

This one would fail silently if the format of the string changed

2022-04-25 23:10 UTC, mikehardy commented on AnkiDroid/jacoco.gradle
> +    toolVersion = "0.8.8"
Switch dependency management to single file of versions and Renovate

Agreed - I've been thinking of switching to renovate at same time, how about this as a separate issue - peel if you agree, I made the first sentence a good title

Renovate because it handles more ecosystems (Backend uses so many...) and it's open source and we're not super wedded to dependabot so it won't be hard to untangle. I've seen renovate in action on ACRA and it works well, plus you can disable it on forked repos (bonus, my fork's main branch won't have skew from main repo to turn off dependabot!)

2022-04-25 23:12 UTC, mikehardy commented on .github/workflows/lint.yml
> +          command: ./gradlew :AnkiDroid:compilePlayDebugJavaWithJavac compileLint lint-rules:compileTestJava --daemon
Ah, disabling the daemon is a default for the community gradle-build-action I'm using, and this is their recommended way to use the daemon if that's what you want

Since our runners are ephemeral I'm not worried about cross-workflow pollution, so this should just be a tiny optimization intra-build / inter-step

I'll reword the commit message to have link to https://github.com/gradle/gradle-build-action/issues/113#issuecomment-1003204780

2022-04-25 23:14 UTC, mikehardy commented on AnkiDroid/build.gradle
> +            String[] matches = file.readLines().findAll { it.contains('testsuite tests="0"')}
Hmm I don't want to be in the business of having the test memorize the correct number of tests but you are right that this will fail silently

How about I positively match on the regex equivalent of `\d+` in the tests match to make sure I am matching a test count, then I extract the number and make sure it is not zero?

That way if format changes I will fail to match at all, but successful match of bad number (0) will fail too?

2022-04-25 23:16 UTC, mikehardy commented on lint-rules/build.gradle
>      testImplementation "com.android.tools.lint:lint-tests:$lint_version"
![image](https://user-images.githubusercontent.com/782704/165189551-3aaf0a76-0027-4b26-91ae-0530180263b5.png)

![image](https://user-images.githubusercontent.com/782704/165189567-b5730c77-9afb-4c64-a7e6-ea96be6b8be8.png)


These are what I expect to see based on the link in commit message explaining you need both in order to get the transitive dep moved to 2.x correctly in junit 4.x ?

2022-04-25 23:19 UTC, david-allison commented on AnkiDroid/build.gradle
> +            String[] matches = file.readLines().findAll { it.contains('testsuite tests="0"')}
That's my thoughts: we don't want the exact number, but: 

* we want there to be **A** number
* we don't want that number to be 0

2022-04-25 23:19 UTC, david-allison commented on AnkiDroid/jacoco.gradle
> +    toolVersion = "0.8.8"
Done - no clue about Renovate. Could you link docs in [the issue](https://github.com/ankidroid/Anki-Android/issues/11101)

2022-04-25 23:19 UTC, david-allison commented on AnkiDroid/jacoco.gradle
> +    toolVersion = "0.8.8"
Done - no clue about Renovate. Could you link docs in [the issue](https://github.com/ankidroid/Anki-Android/issues/11101)

2022-04-25 23:19 UTC, david-allison commented on AnkiDroid/build.gradle
> +            String[] matches = file.readLines().findAll { it.contains('testsuite tests="0"')}
That's my thoughts: we don't want the exact number, but: 

* we want there to be **A** number
* we don't want that number to be 0

2022-04-25 23:21 UTC, david-allison commented on lint-rules/build.gradle
>      testImplementation "com.android.tools.lint:lint-tests:$lint_version"
Line 24/27: https://github.com/ankidroid/Anki-Android/pull/11096/files#diff-63b4e1c61db7eeab4f6a80d1ed5a06a35a354c7119d40dda1b493bb8e9d63fb7R24

> testImplementation 'org.hamcrest:hamcrest-all:1.3'

I don't think it's necessary.

2022-04-25 23:22 UTC, david-allison commented on lint-rules/build.gradle
>      testImplementation "com.android.tools.lint:lint-tests:$lint_version"
unresolving - in case you missed the above reply.

Otherwise, I'm happy it's been taken into consideration

2022-04-25 23:29 UTC, mikehardy commented on AnkiDroid/build.gradle
> -//To be removed when upstream gets patched
Added extra commit which removes that, and adds explanation + URL to check for when the version override itself may be removed

2022-04-25 23:29 UTC, mikehardy commented on AnkiDroid/build.gradle
> +            String[] matches = file.readLines().findAll { it.contains('testsuite tests="0"')}
working on this, will re-ping when done - other items are done but not pushed

2022-04-25 23:35 UTC, mikehardy commented on lint-rules/build.gradle
>      testImplementation "com.android.tools.lint:lint-tests:$lint_version"
Oh crap! :facepalm: thanks for holding firm there, fixed will re-push

2022-04-26 00:42 UTC, mikehardy commented on AnkiDroid/build.gradle
> +            String[] matches = file.readLines().findAll { it.contains('testsuite tests="0"')}
fixed!

2022-04-26 00:57 UTC, david-allison approved these changes

2022-04-26 00:57 UTC, david-allison commented on AnkiDroid/build.gradle
> +            println matches.length
unsure about debug printlines - implementer's choice

2022-04-26 00:58 UTC, david-allison commented
One confirmation I'd like to check is that the "0 emulator" case was re-tested

2022-04-26 03:05 UTC, mikehardy commented
Tested the snot out of it, my local API21 is a great test. So I redid tests of API21 solo, API21+API31, API31 solo, got expected results (with bonus debugging output to help verify which I will remove, good spot).
After doing nothing other than removing println, if it goes green I'll merge. Thanks for the help, definitely better for it

2022-04-26 03:09 UTC, mikehardy commented on AnkiDroid/build.gradle
> +            println matches.length
:disappointed:

2022-04-26 03:25 UTC, merged