Extract ACRA related code from Application class
ankidroid/Anki-Android pull request #11109
Opened 2022-04-26 10:32 UTC by lukstbit

## Purpose / Description

Extracts code related to ACRA configuration from the application class to a configuration object based on the discussion from [here](https://github.com/ankidroid/Anki-Android/pull/10988#issuecomment-1104440076). There are still some calls to the ACRA instance directly in the application class, I can migrate those as well if requested:

```
        //Stop after analytics and logging are initialised.
        if (ACRA.isACRASenderServiceProcess()) {
            Timber.d("Skipping AnkiDroidApp.onCreate from ACRA sender process");
            return;
        }
```

and:

```
        ACRA.getErrorReporter().putCustomData("origin", origin);
        ACRA.getErrorReporter().putCustomData("additionalInfo", additionalInfo);
        ACRA.getErrorReporter().handleException(e);
```

## How Has This Been Tested?

Ran the usual tests.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-26 11:10 UTC, david-allison approved these changes
This is awesome!

2022-04-26 11:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ACRAConfiguration.kt
> +        prefs.edit().putString(FEEDBACK_REPORT_KEY, FEEDBACK_REPORT_NEVER).apply()
edit { }

2022-04-26 11:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ACRAConfiguration.kt
> +        val webViewInfo = HashMap<String, String>()
This can use hashMapOf

2022-04-26 11:36 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/ACRAConfiguration.kt
> +        prefs.edit().putString(FEEDBACK_REPORT_KEY, FEEDBACK_REPORT_NEVER).apply()
Done!

2022-04-26 11:36 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/ACRAConfiguration.kt
> +        val webViewInfo = HashMap<String, String>()
Made the switch.

2022-04-26 12:24 UTC, mikehardy requested changes
This *is* fantastic. It had the possibly unfortunate (depending on perspective?) effect of just making me want more. One of the issues I have while forward-porting to ACRA 5.9.x (#10627 - in progress / will rework after this goes in) is that the ACRA internals are scattered everywhere.

As long as we are extracting ACRA stuff, I think, let's *really* extract it. Let's encapsulate all of it :pray: :pray:  - normally this would seem risky but I have been testing ACRA lot in the last week or three, and I will be testing it again thoroughly with the forward port, so this is a rare good opportunity to take the risk of changing up the code a lot as it will receive a lot of scrutiny.

I left comments to that affect. What do you think? If  you've got time awesome, if not, I can take it from this point here - which is already good - and do it

2022-04-26 12:24 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        ACRAConfiguration.setupACRAWebViewIfNeeded();
If this method is called every time, and ACRAConfiguration.initialize is called every time, it would be nice to just move this to ACRAConfiguration.initialize I think, and clear the ACRA detail out of AnkiDroidApp

2022-04-26 12:24 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
>              val lastReportTimestamp = getTimestampOfLastReport(activity)
getTimestampOfLastReport also should be extracted/moved to proposed CrashReportService I think - it's all internal ACRA details, now that we're in Kotlin we can do named parameters I think? Could remove 'deleteACRALimiterData` and change add a named parameter to sendExceptionReport that is something like 'ignoreThrottle'  default to false, and if that param is present and true then delete limiter data in sendExceptionReport

2022-04-26 13:47 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        ACRAConfiguration.setupACRAWebViewIfNeeded();
Done! It was possible and I should have moved it to the new ACRA class from the beginning.

2022-04-26 13:51 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +            String reportMode = getSharedPrefs(getInstance().getApplicationContext()).getString(ACRAConfiguration.FEEDBACK_REPORT_KEY, FEEDBACK_REPORT_ASK);
The name `CrashReportService` is much nicer, I refactored ACRAConfiguration to use it. The `sendExceptionReport` methods were moved to the new class, at this moment the application class doesn't have any more direct ACRA usages in it. This unfortunately produced a lot of changed files but they should be easy to review as the changes are basically just a name and maybe an import.

The only thing that remains in the application class is the `sSentExceptionReportHack` field which has a TODO set on it. I don't have experience with ACRA to really know how to tackle this, some help here would be appreciated.

2022-04-26 13:56 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
>                  preferences.edit().putBoolean(ACRA.PREF_DISABLE_ACRA, true).apply()
Judging by the fact that there's only one usage of this type of code(like the one in `HelpDialog`) I think it could be extracted to our CrashReportService class into a sendReport(ankiActivity) method. I didn't do any work on this to maybe merge some of the previous code I did in this PR.

2022-04-26 13:57 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
>              val lastReportTimestamp = getTimestampOfLastReport(activity)
Could we really delete the  'deleteACRALimiterData` method? It's being used in tests on its own.

2022-04-26 14:21 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +            String reportMode = getSharedPrefs(getInstance().getApplicationContext()).getString(ACRAConfiguration.FEEDBACK_REPORT_KEY, FEEDBACK_REPORT_ASK);
I will happily review more changed files and do more testing on it personally to get this whole area cleaned up. I really really appreciate you taking it on!

2022-04-26 14:39 UTC, mikehardy requested changes
I am much more excited about this than I should be about code extraction. The ACRA stuff was a real mess, I just read through this whole PR again in it's current state and it's great. I left two specific comment on the HelpDialog and the analytics-package acra companion as those are the only remaining opportunities for extraction/encapsulation.

Crash reporting will be in a much better state app-wide with all this

2022-04-26 14:39 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/Acra.kt
> +            CrashReportService.deleteACRALimiterData(ctx)
:exploding_head: why is this even in the analytics package as a companion object? Now that we're encapsulating ACRA APIs and prefs and internals in CrashReportService this seems really odd doesn't it? This *whole* object, all of it's 3 APIs should go in CrashReportService I think, and then the only thing referencing it (I think?) which is Preferences just starts referencing it in the new location?

2022-04-26 14:39 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt
> +            CrashReportService.deleteACRALimiterData(this)
Oh - here's a nice corner case! Defintely need the deleteACRALimiterData method but at same time for the one area we were discussing - the HelpDialog where we want to temporarily ignore ACRA limits, that's an implementation detail we can hide inside sendExceptionReport with a named parameter saying basically "no really send it + force the thing + ignore all limits"

2022-04-26 14:39 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/Utils.kt
> +import com.ichi2.anki.CrashReportService
@david-allison amazing how many objects were only importing AnkiDroidApp for `sendExceptionReport`, I wonder if this provides an opportunity for lighter tests via a MockCrashReportService in pure junit or a default Robolectric super-class setup stub? Just a thought since I know you're well-versed in the area.

2022-04-26 14:39 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
>              val lastReportTimestamp = getTimestampOfLastReport(activity)
This is the only part left I think - trying to hide this inside CrashReportService too

2022-04-26 15:17 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/Utils.kt
> +import com.ichi2.anki.CrashReportService
Gets us closer, we'll need to tackle it on a case-by-case basis, I feel our main problem is `Context` for translations. 

Once we move to the Anki Desktop backend, we have a second mechanism for translations, and it'll be worth having the discussion of 'can we do better than `Context`'.

2022-04-26 15:48 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/Acra.kt
> +            CrashReportService.deleteACRALimiterData(ctx)
I removed that class, only the onPreferenceChanged() method was actually used.

2022-04-26 15:49 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
>                  preferences.edit().putBoolean(ACRA.PREF_DISABLE_ACRA, true).apply()
@mikehardy I've extracted the ACRA related code from HelpDialog.

2022-04-26 17:24 UTC, mikehardy commented
Changed so much I re-pinged @david-allison in case they want to take a look. If it passes my testing I'm fine with a merge after a couple days timebox to give anyone a chance. I'll re-base my work on #10627 on top of this assuming that this exact PR or same PR with just some minor changes will be what is merged. :muscle:

2022-04-26 17:46 UTC, david-allison approved these changes
If CI passes, I'm happy, excellent job

2022-04-26 17:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +    fun sendExceptionReport(e: Throwable?, origin: String?, additionalInfo: String?, onlyIfSilent: Boolean) {
e should be non-null

2022-04-27 05:06 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +    fun sendExceptionReport(e: Throwable?, origin: String?, additionalInfo: String?, onlyIfSilent: Boolean) {
Made the parameter non null!

2022-04-27 05:07 UTC, lukstbit commented
I fixed the conflicts introduced after the latest merged PRs and also addressed the parameter nullability change.

2022-04-27 11:47 UTC, mikehardy commented
Ah great! Thanks again, on me to test then, hoping to get to it shortly so conflicts don't creep in again

2022-04-27 14:28 UTC, mikehardy commented
Verified Item 4 is not a regression. If you trigger a test crash (which is only possible with debug builds anyway), even if it is set to always report, you get a dialog. So this passes all of my testing. Good to go!

2022-04-27 14:29 UTC, merged

2022-04-27 17:40 UTC, david-allison commented
> Verified Item 4 is not a regression. If you trigger a test crash (which is only possible with debug builds anyway), even if it is set to always report, you get a dialog. So this passes all of my testing. Good to go!

You want the dialog on a test crash to provide the user with an opportunity to write a message

2022-04-27 17:45 UTC, mikehardy commented
I think you got it backwards - that would be item 5, but at the time anyway, we figured the user was interacting with support already because they wanted to have a fresh crash from a known ACRA UUID, so always just toasting was fine

For item 4 I think it would be better to just toast personally, it's literally a debug mode "crash now" button to just test reporting, not feedback, but I guess it's best to check the dialog too? I dunno. Mostly just wanted to make sure this was effectively "NF" / non-functional, and it definitely passed that. Anything else would be a requirements change / new issue. I'm not motivated to change any of it, I think it's okay as is