Fixed SearchDecks Icon visibility not updating if DeckCount changed
ankidroid/Anki-Android pull request #11113
Opened 2022-04-26 22:54 UTC by dorrin-sot

## Purpose / Description
Search Decks Icon would not change (show or unshow) if deck count was changed (added or deleted) unless app was restarted

## Fixes
Fixes #11112

## Approach
Since after DeckList was changed, `renderPage()` will be called, added a deckcount check there and if deckcount was 9 or 10 it would invalidate options menu. Also added the 

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-26 23:09 UTC, david-allison requested changes
It would be ideal to add unit tests to this.

If that's not feasible, add a few `@NeedsTest("")` annotations to the relevant method or class

2022-04-26 23:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        if (deckCount == 9 || deckCount == 10) {
extract the 10 to a constant and compare against that.

2022-04-26 23:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        updateSearchDecksIconVisibility(menu)
We can't do this here as `updateSearchDecksIconVisibility` has a reference to `col`, which may be null

2022-04-26 23:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        val deckCount = col.decks.count()
What happens if the user deletes a node of the deck tree? Or adds A::B::C::D, therefore potentially adding/deleting more than 1 deck

2022-04-27 00:28 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        val deckCount = col.decks.count()
Oh I wasn't handling that but I made a few changes that would recognize DeckTree adding and deleting more than one deck. Hopefully it passes unit tests so I can commit it 🤞🏻

2022-04-28 15:55 UTC, dorrin-sot commented
> It would be ideal to add unit tests to this.

I've been trying to write a few but when I try to create a deck with `CreateDeckDialog` and then call `DeckPicker::updateDeckList()` inside its listener, I can't get the `onPrepareOptionsMenu()` to run (so the visibility won't update and it fails the asserts) 😕

2022-04-28 16:01 UTC, dorrin-sot commented
```diff
Index: AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java b/AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
--- a/AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java	(revision 95531f7647e7cf5835567e2527a6eb3c19233e95)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java	(date 1651161300163)
@@ -284,6 +291,116 @@
         }
     }
 
+    @Test
+    public void deckCreationMakesSearchDecksIconVisible() {
+        DeckPicker deckPicker = startActivityNormallyOpenCollectionWithIntent(DeckPicker.class, new Intent());
+
+        DeckManager decks = deckPicker.getCol().getDecks();
+
+        AtomicInteger expectedDeckCount = new AtomicInteger(1);
+
+        CreateDeckDialog createDeckDialog = new CreateDeckDialog(deckPicker, R.string.new_deck, CreateDeckDialog.DeckDialogType.DECK, null);
+        createDeckDialog.setOnNewDeckCreated(did -> {
+            deckPicker.updateDeckList();
+            advanceRobolectricLooperWithSleep();
+
+            String deckName = decks.name(did);
+
+            Timber.d("Deck \"%s\" Created", deckName);
+
+            assertThat(deckName + " must be created", deckPicker.getDeckCount(), is(expectedDeckCount.getAndIncrement()));
+            if (deckPicker.getDeckCount() >= 10)
+                assertTrue(deckName + " should be visible", deckPicker.mSearchDecksIcon.isVisible());
+            else
+                assertFalse(deckName + " should be invisible", deckPicker.mSearchDecksIcon.isVisible());
+        });
+        for (int i = 1; i <= 15; i++) {
+            createDeckDialog.createDeck("Deck" + i);
+        }
+
+        advanceRobolectricLooperWithSleep();
+    }
```

2022-04-28 18:28 UTC, dorrin-sot commented
> I could be wrong but I thought there was support added recently so you could change the collection path during androidTest tests 🤔 - @Arthur-Milchior may know more, I know this was a real issue for him running androidTests.

ooo what if I change this variable with reflection at the start of tests 😳

2022-04-28 19:35 UTC, mikehardy commented
I would discourage getting fancy in tests and relfection change on statics etc is in area I think of as "fancy" :laughing: - better if there is an official (or common) way to slice into the object hierarchy or if you use existing configuration pathways to reconfigure it. I think we already use Rule / grant storage permission so theoretically you could use any directory path in an androidTest and it would work / init a new collection there?

2022-04-28 19:49 UTC, dorrin-sot commented
> I would discourage getting fancy in tests and relfection change on statics etc is in area I think of as "fancy" 😆 - better if there is an official (or common) way to slice into the object hierarchy or if you use existing configuration pathways to reconfigure it. I think we already use Rule / grant storage permission so theoretically you could use any directory path in an androidTest and it would work / init a new collection there?

😂
Oh think I found it. There's a `AnkiDroidApp.INSTRUMENTATION_TESTING` that is for setting a specific `androidTest` directory

2022-05-07 22:35 UTC, david-allison requested changes

2022-05-07 22:35 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java
> +        INSTRUMENTATION_TESTING = true;
Was `NewCollectionPathTestRunner` not feasible here?

2022-05-07 22:35 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java
> +        int iconId = R.id.deck_picker_action_filter;
can these tests ensure that they're running on an emulator:

`        assumeTrue(InstrumentedTest.isEmulator());`

2022-05-07 22:35 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java
> +        deleteAllDecks();
I'm not comfortable here, 

* `INSTRUMENTATION_TESTING` is new and not well tested
* It seemingly wasn't set automatically (above comment), which implies something is wrong and it would be useful to diagnose this.
* There's no check in this code to ensure that we're running in an emulator
* We probably don't want this here:
  * It should be under specific tests which require it, AFTER we've checked the user is running on an emulator

2022-05-08 08:46 UTC, dorrin-sot commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java
> +        INSTRUMENTATION_TESTING = true;
I couldnt find any example of that class. is this ok?


```diff
diff --git a/AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java b/AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java
--- a/AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java	(revision 0797f84d7be9a7aa6d9aeac6f503569e93d2dc3c)
+++ b/AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java	(date 1651999314187)
@@ -70,13 +71,6 @@
 
 @SuppressLint("DirectSystemCurrentTimeMillisUsage")
 public class DeckPickerTest {
-    @Before
-    public void setup() {
-        INSTRUMENTATION_TESTING = true;
-        deleteAllDecks();
-    }
-
-
     private void deleteAllDecks() {
         deleteAllNotes();
 
@@ -161,7 +155,11 @@
 
 
     @Test
-    public void deckNormalCreationAndDeletionMakesSearchDecksIconVisible() {
+    public void deckNormalCreationAndDeletionMakesSearchDecksIconVisible() throws ClassNotFoundException, IllegalAccessException, InstantiationException {
+        assumeTrue(InstrumentedTest.isEmulator());
+        NewCollectionPathTestRunner.newApplication(DeckPicker.class, getInstrumentation().getTargetContext());
+        deleteAllDecks();
+
         int iconId = R.id.deck_picker_action_filter;
         ensureIsGone(iconId);
 
@@ -178,7 +176,11 @@
 
 
     @Test
-    public void subdeckCreationAndDeletionMakesSearchDecksIconVisible() {
+    public void subdeckCreationAndDeletionMakesSearchDecksIconVisible() throws ClassNotFoundException, IllegalAccessException, InstantiationException {
+        assumeTrue(InstrumentedTest.isEmulator());
+        NewCollectionPathTestRunner.newApplication(DeckPicker.class, getInstrumentation().getTargetContext());
+        deleteAllDecks();
+
         int iconId = R.id.deck_picker_action_filter;
         ensureIsGone(iconId);
 

```

2022-05-08 20:55 UTC, david-allison reviewed
Comments regarding ensuring it's running on an emulator do not seem to have been addressed

2022-05-09 15:56 UTC, dorrin-sot commented
> Comments regarding ensuring it's running on an emulator do not seem to have been addressed

Regarding the boolean `INSTRUMENTATION_TEST`, do I just need to move it or do I wait for `NewCollectionPathTest` to be fixed?

2022-05-19 08:52 UTC, dorrin-sot commented
unit tests added 😁

2022-06-15 00:30 UTC, david-allison approved these changes

2022-06-15 00:31 UTC, david-allison commented
```
> Task :AnkiDroid:lintPlayDebug FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:147: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
    var mSearchDecksIcon: MenuItem? = null
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 errors, 0 warnings
```

Other than that, code is good

2022-06-15 06:22 UTC, dorrin-sot commented
Done :)

2022-06-15 09:47 UTC, david-allison reviewed
Coming back to this: can you check to see if `deckCount` is the number of decks, or the number of expanded decks

2022-06-15 10:38 UTC, dorrin-sot commented
It's only the number of decks expanded. for example here it's 6:
<img width="213" alt="image" src="https://user-images.githubusercontent.com/59933477/173807970-dcc74205-1f82-466c-aec2-912fb83ffeeb.png">

2022-06-15 16:37 UTC, dorrin-sot commented
Done 😄

2022-06-15 18:08 UTC, david-allison requested changes
I'd say it should be the total number of decks. People may want to search for a 'collapsed' deck

2022-06-15 22:03 UTC, david-allison approved these changes

2022-06-25 21:38 UTC, mikehardy approved these changes
all those tests :heart_on_fire:

2022-06-25 21:50 UTC, merged