Migrate UndoTest to kotlin
ankidroid/Anki-Android pull request #11129
Opened 2022-04-28 04:37 UTC by lukstbit

## Purpose / Description

Migrates the UndoTest.java file to kotlin following the migration guide. In this class one test is set as ignored and the other test is also ignored due to an exception at the last `assumeThat()` call in the method(happens for both java and kotlin versions).

## Fixes

Closes #10233

## How Has This Been Tested?

Ran the usual tests.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-28 15:33 UTC, david-allison requested changes

2022-04-28 15:33 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/UndoTest.kt
> +        Assert.assertEquals(QUEUE_TYPE_LRN, c.queue)
import `Assert`

2022-04-28 15:33 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/UndoTest.kt
> +        MatcherAssert.assertThat(col.undoType(), Matchers.`is`(Matchers.instanceOf(UndoReview::class.java)))
import `MatcherAssert` and `Matchers`

2022-04-28 15:33 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/UndoTest.kt
> +        @KotlinCleanup("Change `is`() to equalTo()")
You can add this at the top of the class in future

2022-04-28 16:08 UTC, lukstbit commented
All requests for changes have been handled.

2022-04-29 00:35 UTC, david-allison approved these changes

2022-04-29 00:35 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/UndoTest.kt
> +        Assert.assertEquals(QUEUE_TYPE_LRN, c.queue)
This wasn't handled, not going to block on it

2022-04-29 18:30 UTC, mikehardy approved these changes
Looks great, thanks

2022-04-29 19:34 UTC, merged