[KotlinCleanup] OverviewStatsBuilder.kt
ankidroid/Anki-Android pull request #11132
Opened 2022-04-28 13:41 UTC by Jatin887

## Pull Request template

## Purpose / Description
Kotlin CleanUp

## Fixes
Part of [https://github.com/ankidroid/Anki-Android/issues/10489]

## Approach
Using lint and some code changes which were mentioned in the comments and required to make the code more reliable

## How Has This Been Tested?
Physical Device One Plus Nord2

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-28 15:37 UTC, david-allison requested changes

2022-04-28 15:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.kt
> +        stringBuilder.append(res.getString(string.stats_overview_forecast_due_tomorrow, oStats.forecastDueTomorrow))
`R.string.xxx` - imported too much`

2022-04-28 16:10 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.kt
> +        stringBuilder.append(res.getString(string.stats_overview_forecast_due_tomorrow, oStats.forecastDueTomorrow))
changes added

2022-04-29 00:33 UTC, david-allison approved these changes

2022-04-29 00:34 UTC, david-allison commented
I guess that works

2022-04-29 20:10 UTC, mikehardy approved these changes
thank you!

2022-04-29 20:15 UTC, merged