Category heading on the toolbar of settings section
ankidroid/Anki-Android pull request #11165
Opened 2022-04-29 13:56 UTC by UvrajSB

## Purpose / Description
To display the name of the category on the category setting screen's toolbar

## Fixes
Fixes #11119 

## How Has This Been Tested?

My physical device : Realme 8i

https://user-images.githubusercontent.com/73571511/165958773-0277f5ee-7431-4747-b851-0d09da94e6a7.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-29 14:27 UTC, krmanik commented
```
> Task :AnkiDroid:lintPlayDebug FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/10-preferences.xml:25: Error: Duplicate string value "General", used in deck_conf_general, pref_cat_general [DuplicateCrowdInStrings from com.ichi2.anki:lint-rules]
    <string name="pref_cat_general">General</string>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/10-preferences.xml:238: Duplicates value in pref_cat_general. Add a comment attribute on both strings to explain this duplication
1 errors, 0 warnings
```

2022-04-29 14:28 UTC, krmanik requested changes

2022-04-29 14:28 UTC, krmanik commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="pref_cat_general">General</string>
Either it is commented or changed.

2022-04-29 14:38 UTC, UvrajSB commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="pref_cat_general">General</string>
Should I add a comment here or should I use the `deck_conf_general` instead of creating a new one by the name of `pref_cat_general`
I prefer the former as that makes the value's use more logical to understand.
What are your views?

2022-04-29 14:55 UTC, krmanik commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="pref_cat_general">General</string>
If you want to use the `pref_cat_general`, then add comment explaining it. It will pass the CI.

2022-04-29 16:36 UTC, david-allison requested changes
minor nitpick

2022-04-29 16:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +            is GeneralSettingsFragment -> resources.getString(R.string.pref_cat_general)
Could you add `@NeedsTest("check all settings fragments have defined titles")`

2022-04-30 09:36 UTC, krmanik commented
```
 Add a comment attribute on both strings to explain this duplication
```

https://github.com/ankidroid/Anki-Android/blob/fbac739c16018bb016f93dc72cb27a75def62ddf/AnkiDroid/src/main/res/values/10-preferences.xml#L238

2022-04-30 11:09 UTC, david-allison requested changes
Also needs a comment on the other `general` string

https://github.com/ankidroid/Anki-Android/blob/cadcc3ddf7d277f350a04c5fc44f5a238317c619/AnkiDroid/src/main/res/values/10-preferences.xml#L237

2022-04-30 11:09 UTC, david-allison commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="pref_cat_general" comment = "name of the general preference category">General</string>
```suggestion
    <string name="pref_cat_general" comment="name of the general preference category">General</string>
```

2022-05-01 12:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +    override fun setChecked(checked: Boolean) {
This change doesn't feel relevant, does it need to have occurred in this PR?

2022-05-01 12:40 UTC, UvrajSB commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
> +    override fun setChecked(checked: Boolean) {
No, I am sorry.
Let me rectify

2022-05-01 13:08 UTC, david-allison approved these changes

2022-05-04 01:44 UTC, mikehardy approved these changes
nice!

2022-05-04 01:58 UTC, merged