refactor: Convert MultimediaEditFieldActivity to Kotlin
ankidroid/Anki-Android pull request #11173
Opened 2022-04-29 18:04 UTC by david-allison

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-09 21:46 UTC, BrayanDSO requested changes
I'd like this one in soon, so here's some help.

2022-05-09 21:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +        var bChangeToText = false
Maybe a cleanup to rename `bChangeToText` to remove the prefix? 
If not relevant to the repository's WIP kotlin code style, please ignore this.

2022-05-09 21:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +        resultData.putExtra(EXTRA_RESULT_FIELD_INDEX, mFieldIndex)
Cleanup: `Scope function`

2022-05-09 21:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +            showThemedToast(this, getString(R.string.multimedia_editor_failed), false)
Keep `UIUtils.`

2022-05-09 21:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +            showThemedToast(
Ditto

2022-05-09 21:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +                showThemedToast(
Ditto

2022-05-09 21:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +        showThemedToast(this, getString(R.string.mutimedia_editor_assertion_failed), false)
Ditto

2022-05-09 21:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +        val controllerFactory = instance
Keep `BasicControllerFactory.`

2022-05-09 21:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +        if (field is AudioRecordingField && !canRecordAudio(this)) {
Keep `Permissions.`

2022-05-09 21:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +            !canUseCamera(this)
Keep `Permissions.`

2022-05-09 21:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +        if (field is ImageField && manifestContainsPermission(this) &&
Keep `CheckCameraPermission.`

2022-05-09 21:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +        fieldController.loadInstanceState(savedInstanceState)
Cleanup: `scope function`

2022-05-10 01:19 UTC, david-allison commented
I'll get this one fixed up tomorrow, thanks for the review

2022-05-10 19:57 UTC, mikehardy approved these changes
I used this as a test and I think I would have caught 2/3rds, maybe 3/4s of what @BrayanDSO saw. I did not see anything else. nice work

2022-05-10 20:00 UTC, mikehardy commented
tested locally and everything worked - the unit test failure is likely a flake, I'll note it

2022-05-10 20:00 UTC, merged