[Kotlin Cleanup] GestureProcessorTest
ankidroid/Anki-Android pull request #11184
Opened 2022-04-30 04:54 UTC by oyeraghib

## Pull Request template

## Purpose / Description
[Kotlin Cleanup] GestureProcessorTest

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-04-30 04:55 UTC, oyeraghib commented on AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
>  @KotlinCleanup("use mockk for all mocking")
I am not sure what has to be done for this cleanup?

2022-04-30 17:24 UTC, mikehardy approved these changes

2022-04-30 17:24 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
>  @KotlinCleanup("use mockk for all mocking")
it looks to me like it is already being used via mockkStatic in the file ? :thinking: 
I'll approve but mark it for second review from David to see if he has something in mind

2022-04-30 18:34 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
>  @KotlinCleanup("use mockk for all mocking")
We're using a mixture of mocking frameworks - it would be useful to move everything to using `mockk` in this class, that would involve replacing the tests that use `mockito` with ones that use `mockk`

2022-04-30 18:35 UTC, david-allison requested changes

2022-04-30 18:35 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
> +            }
I don't understand this one

2022-04-30 23:58 UTC, oyeraghib commented on AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
> +            }
The Kotlin cleanup says `@KotlinCleanup("scope function")` so I thought we have to introduce a scope function so I tried using `let` but I think it is not required here.

2022-05-01 00:06 UTC, oyeraghib commented on AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
> +            }
The Kotlin cleanup says `@KotlinCleanup("scope function")` so I thought we have to introduce a scope function so I tried using `let` but I am not sure if it is required here. Can you tell me what has to be done for this cleanup?

2022-05-01 04:20 UTC, lukstbit requested changes

2022-05-01 04:20 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
> +            }
There's no need to use a scope function:
```
mockkStatic(ViewConfiguration::class)
every { ViewConfiguration.get(any()) } answers { mockk(relaxed = true) }
```

This replaces the Mockito.mock usage and the relaxed parameter also returns default values for methods used from the ViewConfiguration class.

2022-05-01 04:20 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
>          val prefs = mock(SharedPreferences::class.java, RETURNS_DEEP_STUBS)
To replace Mockito usage with mockk:

```
val prefs = mockk<SharedPreferences>(relaxed = true)
every { prefs.getString(any(), any()) } returns "0"
every { prefs.getString("gestureTapCenter", any()) } returns "1"
every { prefs.getBoolean("gestureCornerTouch", any()) } returns true
mSut.init(prefs)
```

2022-05-01 05:41 UTC, oyeraghib commented on AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
>          val prefs = mock(SharedPreferences::class.java, RETURNS_DEEP_STUBS)
Thanks!! worked perfectly.

2022-05-01 12:06 UTC, david-allison requested changes

2022-05-01 12:06 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
>  @KotlinCleanup("use mockk for all mocking")
This is done

2022-05-06 21:07 UTC, mikehardy approved these changes
Nice! Verified that final comment from David was addressed

2022-05-06 21:32 UTC, merged