[Kotlin Cleanup] DirectGregorianInstantiation
ankidroid/Anki-Android pull request #11191
Opened 2022-05-01 02:23 UTC by oyeraghib

## Pull Request template

## Purpose / Description
[Kotlin Cleanup] DirectGregorianInstantiation

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-01 11:09 UTC, Akshay0701 requested changes
Changes look good to me, but you forgot to remove the kotlinCleanup lines,
anyway, Thanks for your contributions!

2022-05-01 11:53 UTC, david-allison requested changes

2022-05-01 11:53 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectGregorianInstantiation.kt
>          return forbiddenMethods
```suggestion
        return mutableListOf("from")
```

2022-05-01 11:53 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectGregorianInstantiation.kt
>          return forbiddenConstructors
```suggestion
        return mutableListOf("java.util.GregorianCalendar")
```

2022-05-07 20:36 UTC, david-allison requested changes

2022-05-07 20:36 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectGregorianInstantiation.kt
> +@file:Suppress("UnstableApiUsage", "KDocUnresolvedReference")
Fix `KDocUnresolvedReference`

2022-05-08 20:38 UTC, david-allison approved these changes

2022-05-08 20:39 UTC, merged