refactor: CardBrowser - IDE Lint
ankidroid/Anki-Android pull request #11200
Opened 2022-05-01 14:01 UTC by david-allison

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-01 15:25 UTC, Akshay0701 requested changes
just minor suggestions

2022-05-01 15:25 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                    mSaveSearchItem!!.isVisible = !TextUtils.isEmpty(newText)
isNotEmpty can be used here

2022-05-01 15:25 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        when (item.itemId) {
```suggestion
       return when (item.itemId) {
```
and we can remove all other `return's`

2022-05-01 15:25 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        val searchText: String? = if (mSearchTerms!!.contains("deck:")) {
maybe using `?.` is better option here, because in case  `mSearchTerms` is null, then it will execute the else statement, instead of giving null exceptions error

2022-05-01 15:25 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            when (val lastDeckId = lastDeckId) {
what is the reason for creating variable for when statement?

is it because of the first lastDeckId is var and we can only use the val variable in the when statement?

2022-05-01 18:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            when (val lastDeckId = lastDeckId) {
Unsure - this was automated by the IDE, seems I can get rid of it

2022-05-01 20:11 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                    mSaveSearchItem!!.isVisible = !TextUtils.isEmpty(newText)
I didn't want to get through the "non-IDE lint" on this file in this cleanup - there's still a lot to go.

But I've done this in a separate commit, it's 100% correct, and something I'll want to lint for in the future

2022-05-01 20:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        when (item.itemId) {
Got to be a better way - leaving a cleanup to think about it

2022-05-01 20:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        val searchText: String? = if (mSearchTerms!!.contains("deck:")) {
Guaranteed to be null above

2022-05-01 20:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            when (val lastDeckId = lastDeckId) {
`Smart cast to 'Long' is impossible, because 'lastDeckId' is a property that has open or custom getter`

2022-05-02 05:57 UTC, Akshay0701 approved these changes
LGTM

2022-05-04 01:48 UTC, mikehardy approved these changes
okay :sweat_smile:

2022-05-04 02:06 UTC, merged