Use JUnit5 on tests
ankidroid/Anki-Android pull request #11202
Opened 2022-05-01 17:48 UTC by BrayanDSO

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes #11201 

## Approach
1. Extract JUnit version to a constant, so all 3 testImplementations uses the same version
2. Add JUnitPlatform use to `build.gradle`
3. Fix imports to `kotlin.test.junit5.JUnit5Asserter`
4. Fix `AbstractFlashcardViewerTest.getSignalFromUrlTest`
    - It is currently the only parameterized test that uses jupiter-params. It wasn't being discovered before, so it haven't raised any exception.
    - Now that it's discovered, it needed to be fixed

## How Has This Been Tested?

gradlew lint+ jacocoUnitTestReport

## Learning (optional, can help others)

https://docs.gradle.org/current/userguide/java_testing.html#using_junit5
https://stackoverflow.com/a/68934967

Android JUnit isn't officially updated yet (links taken from a [3rd party Android JUnit5 repo](https://github.com/mannodermaus/android-junit5#official-support))

[InstantTaskExecutorRule uses @RestrictTo(RestrictTo.Scope.LIBRARY_GROUP) -- why? (issuetracker.google.com)](https://issuetracker.google.com/u/0/issues/79189568)
[Add support for JUnit 5 (issuetracker.google.com)](https://issuetracker.google.com/issues/127100532)
https://github.com/android/android-test/issues/224

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)
https://docs.gradle.org/current/userguide/java_testing.html#using_junit5 and https://stackoverflow.com/a/68934967

2022-05-01 17:50 UTC, BrayanDSO commented on AnkiDroid/build.gradle
> + // Gradle plugin portal
I haven't changed this whitespace, but I can't amend it either on Android Studio or VS Code (here it doesn't show the whitespace diff) 😬.

2022-05-01 18:02 UTC, BrayanDSO commented
Now we can use junit parameterized tests, building some custom annotations later would be good IMO. 

As an example here https://github.com/ankidroid/Anki-Android/pull/11202/files#diff-ec045306ef509765aeb114371f47e8e180c58c5ef7bfbe88f4bf51f7c0396378R255-R269 it could be passed the args directly to a annotation, so there is less boilerplate. Somewhat similar to python's [pytest parameterized annotations](https://docs.pytest.org/en/6.2.x/example/parametrize.html)

2022-05-01 18:03 UTC, mikehardy requested changes
This looks great - my comments are both about maybe taking it farther, that is not just Anki-Android but also api and lint-rules module

2022-05-01 18:03 UTC, mikehardy commented on AnkiDroid/build.gradle
> +    testImplementation "org.junit.vintage:junit-vintage-engine:$junit_version"
where is junit_version defined? Seems like we should have it here https://github.com/ankidroid/Anki-Android/blob/ac79fcd3768b14a6a1e2be1052cb4038ca2197de/build.gradle#L7-L11

And it should be used in lint-rules and api module as well?

2022-05-01 18:03 UTC, mikehardy commented on AnkiDroid/build.gradle
> +            useJUnitPlatform()
If api and lint-rules module are using junit platform as well, this may be centralized for don't-repeat-yourself purposes here: https://github.com/ankidroid/Anki-Android/blob/ac79fcd3768b14a6a1e2be1052cb4038ca2197de/build.gradle#L46-L51

I just implemented that centralization a week or so ago, would be nice to see it used if it applied :-)

2022-05-01 18:23 UTC, BrayanDSO commented on AnkiDroid/build.gradle
> +    testImplementation "org.junit.vintage:junit-vintage-engine:$junit_version"
> where is junit_version defined? Seems like we should have it here

It is exactly there ;-)

> And it should be used in lint-rules and api module as well?

Sure. Done.

2022-05-01 18:24 UTC, BrayanDSO commented on AnkiDroid/build.gradle
> +            useJUnitPlatform()
Oh, this is great. Thanks! Updated it

2022-05-01 21:50 UTC, mikehardy approved these changes
did I just miss the junit in ext before? 😆 🤷 
This looks great though, thanks for helping clean up the build files, been a while since I groomed them and entropy seemed to have taken over pretty quickly! Looking better now

2022-05-01 21:51 UTC, mikehardy commented
@david-allison asking for high priority review since A) should be quick and B) blocks something else, I always try to clear blockers when possible. Thanks!

2022-05-01 23:39 UTC, david-allison approved these changes
LGTM. Thanks so much! Added one comment which has no action needed

@mikehardy - pinging in case you want to run this though your CI

2022-05-01 23:39 UTC, david-allison commented on AnkiDroid/build.gradle
> + // Gradle plugin portal
You should be able to fix this in Android Studio using 'compare [before] with local'

2022-05-02 00:13 UTC, mikehardy commented
Nope - this one can't really have cross-contamination. The ones we have been unlucky on are when Kotlin vs Java null/non-null typings have changed while there's 10 other PRs in the queue. For any of the normal stuff that can't cross-contaminate, I'm all for hitting the button personally

2022-05-02 00:13 UTC, merged