Migrate TagsList to kotlin
ankidroid/Anki-Android pull request #11206
Opened 2022-05-02 05:49 UTC by lukstbit

## Purpose / Description

Migrates the TagsList.java file to kotlin following the migration guide.

## Fixes

Closes #10158 

## How Has This Been Tested?

Ran the usual tests.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-05 19:32 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt
> +     */
you can merge these comments

2022-05-06 08:24 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt
> +     */
Those I left as a `@KotlinCleanup` with a notice on the class main constructor to keep the migration as simple as possible:
```
@KotlinCleanup(
    "the migration assigned the docs of the 2 previous java constructors to the init{} block, " +
        "try to refactor that documentation into the class documentation"
)
class TagsList @JvmOverloads constructor(
```

2022-05-07 06:06 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt
>      }
init replaces the public TagsList constructor (Line 80 in java file).
I think init should be moved above. (Below Line 54 in the new kotlin file)
This would help us get a cleaner diff.

2022-05-07 06:06 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt
> +        prepareTagHierarchy()
init replaces the public TagsList constructor (Line 80 in java file).
I think init should be moved above. (Below Line 54 in the new kotlin file)
This would help us get a cleaner diff.

2022-05-07 07:03 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt
> +        prepareTagHierarchy()
Done! I usually try to keep the migration as done by the IDE tool but in this case moving the *init* block does help with the review.

2022-05-10 13:36 UTC, david-allison requested changes

2022-05-10 13:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt
> +            .stream().filter { s: String -> !isChecked(s) }
cleanup: remove `.stream` and use kotlin iterators

2022-05-10 15:42 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt
> +            .stream().filter { s: String -> !isChecked(s) }
Done, added a kotlin cleanup.

2022-05-10 15:45 UTC, lukstbit commented
@david-allison There's also #11237 with two approving reviews and a lingering waiting for feedback tag.

2022-05-11 00:55 UTC, merged

2022-05-11 02:24 UTC, lukstbit commented
#11297 is a duplicate of this and can be closed as well.

2022-05-11 02:26 UTC, david-allison commented
Done