[Kotlin Migration] PieChartTest
ankidroid/Anki-Android pull request #11212
Opened 2022-05-02 16:05 UTC by BrayanDSO

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-05 19:39 UTC, Akshay0701 commented on AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTest.kt
> +    private val mGraphics: GraphicsWrap? = null
Instead of adding cleanups, you can make changes in migration itself, because there is little chance of breaking things in test files

2022-05-06 21:37 UTC, mikehardy commented on AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTest.kt
> +    private val mGraphics: GraphicsWrap? = null
we haven't been doing that historically, would complicate things as a precedent I think

2022-05-06 21:38 UTC, mikehardy approved these changes
LGTM as a conversion, w/cleanups as noted

2022-05-06 22:14 UTC, mikehardy requested changes
I think I justified the time I spend doing the local CI simulator after locally doing a pull rebase from main - this appears to have some type cross-contamination with another PR, if you rebase this to main, maybe you'll reproduce this error? 

```
> Task :AnkiDroid:connectedPlayDebugAndroidTest
Starting 183 tests on TestingAVD_API-31_TAG-PLAY(AVD) - 12

> Task :AnkiDroid:compilePlayDebugUnitTestKotlin FAILED
e: /home/mike/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.kt: (6, 52): Unresolved reference: createRectangleMock
e: /home/mike/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.kt: (69, 17): Unresolved reference: createRectangleMock

```

2022-05-06 22:41 UTC, BrayanDSO commented
Thanks! Fixed.

2022-05-06 22:49 UTC, mikehardy approved these changes
perfect! Looking forward to end of kotlin migration with all these changes that make CI less valid as a signal - my laptop is burnin' hot from re-running all the tests all the time

2022-05-06 23:07 UTC, merged