[Kotlin Cleanup] DirectCalendarInstanceUsage
ankidroid/Anki-Android pull request #11225
Opened 2022-05-04 06:36 UTC by oyeraghib

## Purpose / Description
[Kotlin Cleanup] DirectCalendarInstanceUsage

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-06 21:35 UTC, mikehardy approved these changes
Seems fine? Thanks!

2022-05-07 01:38 UTC, david-allison requested changes

2022-05-07 01:38 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectCalendarInstanceUsage.kt
> +@file:Suppress("UnstableApiUsage", "KDocUnresolvedReference")
KDocUnresolvedReference should be fixed if possible.

2022-05-07 19:33 UTC, david-allison requested changes

2022-05-07 19:33 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectCalendarInstanceUsage.kt
> + * This custom Lint rules will raise an error if a developer uses the <Calendar.getInstance> method instead
If you import `Calendar`, the links should work

2022-05-08 19:43 UTC, david-allison approved these changes

2022-05-08 19:43 UTC, merged