Update general category title
ankidroid/Anki-Android pull request #11233
Opened 2022-05-04 14:05 UTC by BrayanDSO

## Purpose / Description

#11165 introduced a new name for the first preferences category and added it to the appBar, but not to the category title, so it kept using the app name as title. So it should be updated to be coherent with the appBar title

## Approach
Use the correct string for the category

## How Has This Been Tested?

Went to the preferences initial screen on my device (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 31, One UI 4.1)

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

## Screenshots

<details><summary>Before</summary>
_See the difference between the category name and the app bar after opening it_

![Screenshot_20220504-105702_AnkiDroidA](https://user-images.githubusercontent.com/69634269/166698202-14f6e31c-7fde-4f80-950c-920e2ea90030.png)
![Screenshot_20220504-105645_AnkiDroid](https://user-images.githubusercontent.com/69634269/166698347-81baf481-42bc-4100-a2fc-ecaa960941d4.png)

</details>

<details><summary>After</summary>

![Screenshot_20220504-105638_AnkiDroid](https://user-images.githubusercontent.com/69634269/166698497-99d0ef30-3b6a-42d2-9409-3c14105a61d6.png)

</details>

2022-05-05 19:13 UTC, Akshay0701 commented
Just my personal opinion: General title text and General Settings subtext, don't it sound repetitive?

a solution would be giving a short description of what the general setting will contain like change ankiweb acc or system lang etc

2022-05-05 20:55 UTC, BrayanDSO commented
Agreed completely. If this is accepted, I can change it

Em qui., 5 de mai. de 2022 16:13, Akshay Vilas Jadhav <
***@***.***> escreveu:

> Just my personal opinion: General title text and General Settings subtext,
> don't it sound repetitive?
>
> a solution would be giving a short description of what the general setting
> will contain like change ankiweb acc or system lang etc
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ankidroid/Anki-Android/pull/11233#issuecomment-1118957589>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQTIRXKR3TSNNKSLRV2APC3VIQMXDANCNFSM5VCCY6JQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-05-05 23:27 UTC, david-allison approved these changes

2022-05-06 03:22 UTC, Tinkidinki commented
1. One possible string that can be written instead of "General Settings" is "Sync, language, notifications and more" -> as I feel these are the most important settings available. 

2. While we're on the topic of strings, I feel it is a bit odd that when "Settings" is selected menu on the left, it opens up a page titled "Preferences". Perhaps there should be consistency between the two?

2022-05-06 21:20 UTC, mikehardy commented
> 1. One possible string that can be written instead of "General Settings" is "Sync, language, notifications and more" -> as I feel these are the most important settings available.

This is too long to show up on some of my test devices, we need to keep it short

> 2. While we're on the topic of strings, I feel it is a bit odd that when "Settings" is selected menu on the left, it opens up a page titled "Preferences". Perhaps there should be consistency between the two?

This could be a good separate issue if you want to log it

2022-05-06 21:23 UTC, mikehardy approved these changes

2022-05-06 21:23 UTC, mikehardy commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="pref_cat_general_summ">Sync, language, notifications and more</string>
Ah, I see it's the summary, that makes sense

2022-05-06 21:23 UTC, mikehardy commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="pref_cat_general_summ">Sync, language, notifications and more</string>
Only problem with this now is that if you want it to be re-translated, and it seems like it should be ?, then you really need to change the key name or it won't be seen as a change for other languages when we re-sync.

I'm not sure it's worth the churn, but...maybe it is? I'll go +1 on it  *pending agreement we should change key to `pref_cat_general_summ_new` (and update usage as appropriate)  but defer to one more set of :eyes:  - otherwise it needs to stay as is I think

2022-05-06 21:51 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="pref_cat_general_summ">Sync, language, notifications and more</string>
If it is worth the retranslation (which I think yes), would `pref_cat_general_summary` be fine as the new key?

2022-05-06 21:58 UTC, mikehardy commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="pref_cat_general_summ">Sync, language, notifications and more</string>
Sure, only strict requirement is that it be a new/different key, I'm indifferent on the name so long as it's reasonable

2022-05-07 01:37 UTC, david-allison requested changes

2022-05-07 01:37 UTC, david-allison commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="pref_cat_general_summ">Sync, language, notifications and more</string>
I don't like this, we will need a new translation each time we add functionality.

AND we should be working towards fixing our preferences, not solidifying the current structure

2022-05-07 02:05 UTC, Tinkidinki commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="pref_cat_general_summ">Sync, language, notifications and more</string>
> AND we should be working towards fixing our preferences, not solidifying the current structure

Just want to clarify what you mean by this: do you mean that the way all preferences have been organised are not necessarily the best, and we might make changes to them, so it doesn't make sense to write the summary as "Sync, language, notifications and more" as that sort of fixes what the general settings does?

2022-05-07 09:01 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="pref_cat_general_summ">Sync, language, notifications and more</string>
> I don't like this, we will need a new translation each time we add functionality.

Very good point. For now, I believe it would be better to revert the summary.

I agree that categories need a reorg, that's why is part of my GSoC proposal.

For the future, I see two options to avoid this problem of retranslating summaries:
1. Get rid of them, assuming the category title, icon, and organization are enough to lead the user to the right place
2. Build the summary with extracted preferences names. Similar to the below picture of Samsung's settings. 


![Screenshot_20220507-054632_Settings](https://user-images.githubusercontent.com/69634269/167247171-0466619a-5417-4b96-a9ef-dd580e394e3f.png)

2022-05-07 13:23 UTC, Tinkidinki commented
> > 1. One possible string that can be written instead of "General Settings" is "Sync, language, notifications and more" -> as I feel these are the most important settings available.
> 
> This is too long to show up on some of my test devices, we need to keep it short
> 
> > 2. While we're on the topic of strings, I feel it is a bit odd that when "Settings" is selected menu on the left, it opens up a page titled "Preferences". Perhaps there should be consistency between the two?
> 
> This could be a good separate issue if you want to log it

Done! https://github.com/ankidroid/Anki-Android/issues/11267

2022-05-09 17:10 UTC, david-allison approved these changes

2022-05-09 17:11 UTC, merged