[Kotlin Migration ] CsvProcessIntegrationTest
ankidroid/Anki-Android pull request #11245
Opened 2022-05-06 02:32 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
Kotlin migration of CsvProcessIntegrationTest
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-06 21:29 UTC, mikehardy requested changes

2022-05-06 21:29 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/libanki/importer/python/CsvProcessIntegrationTest.kt
> +        assertThat("doublequote", dialect.mDoublequote, `is`(true))
kotlinclean is -> equalsTo I think?

2022-05-07 01:34 UTC, david-allison requested changes
This diff modified three files, only one should be modified

`tools/migrate.sh` should be used in the future as it produces better commit names

It's ideal to keep the diff as clean as possible, therefore adding a `KotlinCleanup` rather than changing `is` to `eqaulTo` in this PR

2022-05-07 20:29 UTC, david-allison approved these changes

2022-05-09 16:57 UTC, mikehardy approved these changes
:boom:

2022-05-09 17:06 UTC, merged