[Kotlin Migration ] PreferenceExtensionsTest
ankidroid/Anki-Android pull request #11241
Opened 2022-05-05 13:26 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
Kotlin migration of PreferenceExtensionsTest
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-05 18:44 UTC, Akshay0701 requested changes
Thanks for the contribution @Prince-kushwaha

2022-05-05 18:44 UTC, Akshay0701 commented on AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.kt
> +        Mockito.`when`(mMockPreferences!!.contains(VALID_KEY)).thenReturn(true)
you can import this, to reduce repetitive `Mockito.`

2022-05-05 18:44 UTC, Akshay0701 commented on AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.kt
> +    private val mMockPreferences: SharedPreferences? = null
can be convert to lateinit

2022-05-06 02:44 UTC, Prince-kushwaha commented on AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.kt
> +        Mockito.`when`(mMockPreferences!!.contains(VALID_KEY)).thenReturn(true)
@Akshay0701 I did many kotlin Migration according to david-allison  kotlin code is same as it is in java  
No need to Import `Mockito.`

2022-05-06 03:19 UTC, Akshay0701 approved these changes

2022-05-06 17:38 UTC, david-allison approved these changes

2022-05-09 14:57 UTC, merged