[Kotlin Migration] NumberAtom
ankidroid/Anki-Android pull request #11243
Opened 2022-05-05 20:30 UTC by n1snt

## Checklist
_Please, go through these checks before submitting the PR._

- [ x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x ] You have commented on your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code
- [ x ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [  ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-05 21:59 UTC, david-allison requested changes
Please use `tools/migrate.sh` and follow the migration guide.

https://github.com/ankidroid/Anki-Android/blob/main/docs/kotlin-migration.md

2022-05-06 21:31 UTC, mikehardy requested changes
:thinking: I feel like the methods have all been moved around so the diff has no value - is it possible to have the methods in the same order so the review is higher quality?

2022-05-06 22:02 UTC, mikehardy commented on AnkiDroid/src/main/java/com/wildplot/android/parsing/AtomTypes/NumberAtom.kt
> -    }
I could easily be missing something but...where did this method go? Was it unused, thus just discarded in the migration?

2022-05-06 22:11 UTC, n1snt commented on AnkiDroid/src/main/java/com/wildplot/android/parsing/AtomTypes/NumberAtom.kt
> -    }
atomType was private before so to access it this method was needed.
And during the migration, it made atom type not private. Now it can directly be accessed by using getAtomType()
I noticed this when I tried to make atomType private. It didn't compile the project because getAtomType() was not found but when I removed the private part it compiled & was able to access getAtomType() in Atom.java

2022-05-06 22:12 UTC, mikehardy approved these changes
Hmm - okay this is not quite a pure migration in the sense that the diffs line up cleanly, I think ideally we would keep getAtomType in the migration with the instance var private, then put a kotlincleanup to make it a val with private setter. Will defer to second reviewer on that. As code, it does look right, and thank you for that :-)

2022-05-06 22:14 UTC, n1snt commented
When I try to add getAtomType again to this kotlin migration this error is shown:
`Platform declaration clash: The following declarations have the same JVM signature (getAtomType()Lcom/wildplot/android/parsing/Atom$AtomType;):`

2022-05-07 01:31 UTC, david-allison requested changes
Please squash this to two commits

2022-05-07 20:02 UTC, david-allison approved these changes

2022-05-09 15:59 UTC, merged