[Kotlin Migration] Noteinfo
ankidroid/Anki-Android pull request #11269
Opened 2022-05-07 18:38 UTC by n1snt

## Checklist

- [ x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x ] You have commented on your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code
- [ x ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-07 19:37 UTC, david-allison requested changes
kotlinMigration.gradle does not support the `api` project.

A `kotlinMigration-api.gradle` will be required.

2022-05-07 20:13 UTC, n1snt commented
Can I try creating a Gradle file for kotlinMigration for `api` project?
Where should I start?
And why wouldn't the `kotlinMigration.gradle` file work?
Would it need updating the paths in Source?

2022-05-07 20:17 UTC, david-allison commented
kotlinMigration isn't included in the API 'build.grade': https://github.com/ankidroid/Anki-Android/blob/25473eeaff65c06c68d0d0e6fe79805da479437a/api/build.gradle

See: c16aae062ad470513e2d09640ef028f3a4a41c4b and https://github.com/ankidroid/Anki-Android/pull/11037 for how to make this file.

Ensure that you test it by building the first commit

2022-05-09 18:18 UTC, n1snt commented
Now updated it to using `kotlinMigration-api.gradle`

2022-05-11 04:19 UTC, david-allison commented
Blocked on resolution of https://github.com/ankidroid/Anki-Android/pull/11286#issuecomment-1123167003

2022-05-12 14:36 UTC, n1snt commented
@david-allison I think this could be merged now.
Have a look at this & let me know if I should make any changes to it.

2022-05-15 01:51 UTC, david-allison commented on api/src/main/java/com/ichi2/anki/api/NoteInfo.kt
> +    private val id: Long
Are you sure these weren't renamed by hand?

2022-05-16 18:07 UTC, n1snt commented on api/src/main/java/com/ichi2/anki/api/NoteInfo.kt
> +    private val id: Long
These were named like this automatically during migration.

2022-05-16 18:48 UTC, david-allison approved these changes

2022-05-18 17:41 UTC, merged