[Kotlin Migration] DeckOptions
ankidroid/Anki-Android pull request #11274
Opened 2022-05-08 12:32 UTC by BrayanDSO

Definetely not my favorite class. Tested manually on my phone.
There were too many deprecations (even on imports) so I suppressed the whole file.

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-08 20:50 UTC, david-allison requested changes
If it makes you feel better the 'non-deprecated' preferences library is pretty awful. I've done the main 'preferences' activity, and will do these in time.

Soft approve as both changes are minor and the code seems correct.

2022-05-08 20:50 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
> +                mPref.mSummaries[key] = if (s != null) pref.summary.toString() else null
cleanup: ?.

2022-05-08 20:50 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
> +            for (childDid in children.values) {
or change to a `.sum {}`

2022-05-08 21:00 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
> +            for (childDid in children.values) {
Do you mean `.count {}`? As in:

```kotlin
children.values.count { !mCol!!.decks.get(it).isDyn }
```

2022-05-08 21:11 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
> +            for (childDid in children.values) {
Oh -  if we're only incrementing by 1 then count would be better yes!

2022-05-09 17:14 UTC, mikehardy approved these changes
boom!

2022-05-09 17:16 UTC, david-allison approved these changes

2022-05-09 17:51 UTC, merged