[KotlinCleanup] ActivityExportingDelegate.kt
ankidroid/Anki-Android pull request #11289
Opened 2022-05-09 18:24 UTC by Jatin887

## Pull Request template

## Purpose / Description
Kotlin CleanUp

## Fixes
Part of #10489
## Approach
Using lint and some code changes which were mentioned in the comments and required to make the code more reliable
## How Has This Been Tested?

Physical Device One Plus Nord2

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-09 19:22 UTC, david-allison requested changes

2022-05-09 19:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
> +                listener.emailFile(exportPath!!)
maybe move the `!!` to the variable declaration

2022-05-09 19:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +    private fun Boolean.exportToProvider(intent: Intent): Boolean {
I don't think this should be an extension

2022-05-09 19:45 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
> +                listener.emailFile(exportPath!!)
![image](https://user-images.githubusercontent.com/71597104/167485838-70fa0890-3764-4240-b7ab-8ca17d5712ba.png)
is it ok?

2022-05-09 19:50 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
> +                listener.emailFile(exportPath!!)
yes

2022-05-09 20:29 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +    private fun Boolean.exportToProvider(intent: Intent): Boolean {
changes added

2022-05-10 15:02 UTC, mikehardy approved these changes
nice!

2022-05-10 15:14 UTC, merged