[Kotlin Migration] BasicModel
ankidroid/Anki-Android pull request #11286
Opened 2022-05-09 17:44 UTC by n1snt

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-09 17:45 UTC, david-allison commented on api/src/main/java/com/ichi2/anki/api/BasicModel.kt
> +internal object BasicModel {
Why is this now internal?

2022-05-11 04:18 UTC, david-allison commented
@mikehardy I feel this warrants a bump in the major version of the API project (Kotlin visibility change on package protected). Do you agree?

It's a breaking change which probably won't affect consumers as they're unlikely to put code under our package.

2022-05-11 04:20 UTC, mikehardy commented
I'll trust you on that - I haven't reviewed and am heading away from keyboard from a while
but philosophically I'm a semver robot: if it smells like a breaking change it probably is, version numbers are free, documentation explaining the break is golden, so add a changelog doc, do the major version and move on. zero drama, it's unemotional

2022-05-11 04:21 UTC, david-allison commented
Let's wait to confirm then, no need to rush this

2022-05-11 05:02 UTC, n1snt commented
Yeah, I too think this justifies a bump in the major version of the API project.
I will update it to use `internal` 👍

2022-05-11 14:59 UTC, mikehardy commented on api/src/main/java/com/ichi2/anki/api/BasicModel.kt
> +internal class BasicModel {
> Should I create another issue "release a new version of API"? 

Yep, you can use the three-dot menu at top right of the comment to create a new issue and it pre-populates it with text of my comment and helpful links back to the comment that generated the issue

> Sorry I didn't understand what you mean by "putting a v2.0.0 here".

I mean literally change that string to 2.0.0, that's how you change the version

2022-05-11 17:27 UTC, n1snt commented on api/src/main/java/com/ichi2/anki/api/BasicModel.kt
> +internal class BasicModel {
Created the issue.
Should I change the comment to "2.0.0"? or the version string in build.gradle file?

2022-05-11 17:42 UTC, mikehardy commented on api/src/main/java/com/ichi2/anki/api/BasicModel.kt
> +internal class BasicModel {
Go ahead and change the version to 2 in this PR so we don't forget, and this is the PR that creates the break, so having the version changed at same time makes sense. The API module is not auto-versioned like the AnkiDroid module

2022-05-12 09:13 UTC, david-allison requested changes
Commit 1: Explain in the commit message why we're bumping the version number

2022-05-12 10:46 UTC, n1snt commented
Done

2022-05-12 13:48 UTC, david-allison approved these changes

2022-05-12 13:52 UTC, mikehardy approved these changes
nice!

2022-05-12 14:21 UTC, merged