View binding analytics package
ankidroid/Anki-Android pull request #11292
Opened 2022-05-09 21:00 UTC by Jatin887

## Pull Request template

## Purpose / Description
Added ViewBinding for AnkidroidCrashReportDialog

## Fixes
Part of (https://github.com/ankidroid/Anki-Android/issues/11116)

## Approach
Removed findViewById with the help of implementing binding class for feedback.xml

## How Has This Been Tested?
Physical Device OnePlus Nord2

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-09 21:15 UTC, Jatin887 commented
@david-allison Please review and let me know if the commit-message format is correct and whether I should continue with this and submit pull requests for all remaining packages. Are any adjustments required?

2022-05-10 05:04 UTC, lukstbit requested changes

2022-05-10 05:04 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt
> +        val rootView = binding.root // when you inflate into an alert dialog, you have no parent view
Not needed anymore:
- @SupressLint
- the comment
- the extra variable rootView because we could simply do `return binding.root`

2022-05-10 08:55 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt
> +        val rootView = binding.root // when you inflate into an alert dialog, you have no parent view
changes added

2022-05-10 08:55 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt
>      private var mUserComment: EditText? = null
i added the changes

2022-05-10 13:42 UTC, david-allison requested changes

2022-05-10 15:19 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt
> -    private var mUserComment: EditText? = null
Should I change the I'd name of etfeefdbacktext as etusercomment or usercomment in XML file? Or should I make a get property in the file.
I think the first option will be great because we don't have to declare extra variable. need suggestions?

2022-05-10 15:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt
> -    private var mUserComment: EditText? = null
If the XML file is ours, then yes. I presumed this was one defined by ACRA

2022-05-10 17:29 UTC, mikehardy commented
Please just keep to one commit, no need for little tack-on commits - you can locally squash + force-push

![image](https://user-images.githubusercontent.com/782704/167687631-1f12630e-cde9-4a39-a850-232f99cc2586.png)

2022-05-10 18:40 UTC, mikehardy commented
Ah, that makes sense. And depending on what the follow-on work is doing, I can see having separate commits (until everything is resolved) actually aiding the reviewer. It's a matter of taste then, your workflow works for me - usually it's because people are new to git and simply don't squash / rebase at all, so I try to nudge them there ;-)

2022-10-30 17:15 UTC, BrayanDSO commented
I'm going to draft this, as the PR got conflicts and the author hasn't been on github for months, to simplify the reviews' queue

2023-01-05 17:36 UTC, closed without merging