Allow only single imports on the .colpkg option.
ankidroid/Anki-Android pull request #11303
Opened 2022-05-10 16:23 UTC by n1snt

## Purpose / Description
Allow only importing single files when .colpkg option is selected in the import dialog as mentioned [here](https://github.com/ankidroid/Anki-Android/pull/10851#pullrequestreview-965378466).

## Approach
Added an optional flag to ImportFileSelectionFragment to enable or disable multiple file selection. 

## How Has This Been Tested?
Tested on: 
- A physical device with Android 12
- Virtual Device with Android 7.0

## Checklist

- [ x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x ] You have commented your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code
- [  ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [  ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-10 16:40 UTC, david-allison requested changes

2022-05-10 17:38 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
> +        var multipleFiles = false
I have now made the above changes.
Please have a look at it.

2022-05-10 17:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
> +            class OpenFilePicker(var multiple: Boolean = false) : FunctionItem.ActivityConsumer {
Has this been tested? Does the class work without being marked as Serialisable?

2022-05-10 18:01 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
> +            class OpenFilePicker(var multiple: Boolean = false) : FunctionItem.ActivityConsumer {
Yes, I have tested this & it is working.

2022-05-10 22:46 UTC, david-allison approved these changes

2022-05-10 22:47 UTC, david-allison requested changes
Actually... could you add some `@NeedsTest` annotations explaining the unit tests which would be desired:

* Selecting APKG allows multiple files
* Selecting COLPKG does not allow multiple files

2022-05-10 22:48 UTC, david-allison commented
Just to note: if you remove the spaces from the `[ x ]` in the main post, they appear as checkboxes:

`[ x ]` -> `[x]`

2022-05-10 23:03 UTC, BrayanDSO commented
> Actually... could you add some `@NeedsTest` annotations explaining the unit tests which would be desired:
> 
> * Selecting APKG allows multiple files
> * Selecting COLPKG does not allow multiple files

Add one more @NeedsTest please

* `Choose another` option on Restore backup dialog does not allow multiple files

(with the current code, by the logic, yes, it works fine there too)

2022-05-11 06:52 UTC, n1snt commented
I have also tested the restore backup dialog & it seems to be working fine.

2022-05-11 07:22 UTC, david-allison approved these changes
Thanks!!

2022-05-11 13:13 UTC, mikehardy approved these changes
Looks good, thank you!

2022-05-11 13:47 UTC, merged