refactor: Convert Collection to Kotlin
ankidroid/Anki-Android pull request #11309
Opened 2022-05-10 19:28 UTC by david-allison

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-10 19:30 UTC, david-allison commented
@BrayanDSO If you have the time, you're normally fantastic with these reviews, and it'd be really appreciated.

Note that the Kotlin Conversion corrupted pretty much all of the variables (with an off-by one error in the references), so a reference to `DB` became a reference to `server`. I can't guarantee that I've fixed everything

2022-05-10 22:10 UTC, BrayanDSO commented
Yayyy, time to migrate libanki. This is gonna be so fun. Let me read this through

2022-05-10 22:39 UTC, mikehardy commented
$deity help us :see_no_evil: 
Might be easier - no really it might be - to take up the v16 schema migration and removal of more and more of libanki. There's no "easy" here I don't think

2022-05-10 22:43 UTC, david-allison commented
I'm very open to not converting the V11 classes for `libAnki`.

`Collection` is mostly dual use though, and will remain after V16 is live: https://github.com/ankidroid/Anki-Android/blob/c08a17b93c9258a6ac71ab2ddca21ae35eae5f29/AnkiDroid/src/main/java/com/ichi2/libanki/CollectionV16.kt

2022-05-10 22:49 UTC, mikehardy commented
> I'm very open to not converting the V11 classes for libAnki.

That seems like a good idea, impact of converting v11 to kotlin vs ... finishing new user introduction for example, or actually doing v16 schema integration. This kotlin stuff is like a non-stop avalanche of "gotta get it through, but leaves no time for anything else"

2022-05-10 22:56 UTC, BrayanDSO requested changes
Oh this is big. I probably missed something, but overall looks good. 

I really want the beautiful day when kotlin migration is done to come

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +            cursor?.close()
Cleanup: make `cursor` a val + move `cursor` and `cursor.close()` to the try block

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        var deckConf: String?
Add back `= ""` to deckConf. I think it's safer to be explicit here

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +                val db = db.database
Cleanup: `remove val db`

It's used only one time and creates confusion to distinguish from the others `db` in the method

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +            db.execute("UPDATE $t SET usn=0 WHERE usn=-1")
I'd like to avoid adding values directly to SQL query strings. 
If reasonable, probably it would be better to add a cleanup above the class, because it happens many times along the code.

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        return _newCard(note, template, due, flush)
Cleanup: `inline flush=true`

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        return _newCard(note, template, due, did, flush)
ditto

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        return _newCard(note, template, due, did, flush)
ditto

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +            val r = Random()
Cleanup: `use Kotlin's random library instead of Java's`

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        values.put("ls", mLs)
Cleanup: scope function

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +            values.put("type", type)
Cleanup: scope function

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +            db.insert("graves", values)
Cleanup: scope function

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +    fun findReplace(nids: List<Long?>?, src: String?, dst: String?, field: String?): Int {
Cleanup: make non-null

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +    fun findDupes(fieldName: String?, search: String?): List<Pair<String, List<Long>>> {
Cleanup: `search: String = ""`

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        var changed = 0
Cleanup: `Use count`

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        if (ids.size != 0) {
Cleanup: `.isNotEmpty()`

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        if (ids.size != 0) {
ditto

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        if (ids.size != 0) {
ditto

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        if (ids.size != 0) {
ditto

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        var fixCount = 0
Cleanup: `.count{}`

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +                    var fldsCount = 0
Cleanup: `.count{}`

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +                    @CARD_TYPE val type = cur.getInt(5)
Keep `Consts.`

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +    fun _logRem(ids: kotlin.collections.Collection<Long>, @REM_TYPE type: Int) {
Keep `Consts.`

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        private val fClozePatternQ = Pattern.compile("\\{\\{(?!type:)(.*?)cloze:")
Cleanup: Use kotlin's regex methods

2022-05-10 22:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        private val fSupportedSchedulerVersions = Arrays.asList(1, 2)
Cleanup: listOf()

2022-05-11 01:45 UTC, david-allison commented
![](https://media.giphy.com/media/jTGbRuSppfEJunnSK6/giphy.gif)

2022-05-11 01:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +    private var mLs: Long = 0
Manually - defaults for variables in Java

Fixes error: `Property must be initialized or be abstract`

Added a cleanup

2022-05-11 01:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        var deckConf: String?
Compiler error - Variable 'deckConf' initializer is redundant

2022-05-11 01:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +                val db = db.database
Just to note that we have `db` and we have `db.database`, we want to retain a reference to the underlying database

But: added

2022-05-11 01:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +            db.execute("UPDATE $t SET usn=0 WHERE usn=-1")
We'll get rid of this one (and most of the SQL) in the Rust conversion - do you mind if we leave this one and see where things lie once we rip out most of libAnki?

2022-05-11 08:35 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +    private var mLs: Long = 0
Understood

2022-05-11 08:36 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        var deckConf: String?
Okey dokey

2022-05-11 08:38 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +            db.execute("UPDATE $t SET usn=0 WHERE usn=-1")
Fine to me. It was working before and if Rust is going to replace it, awesome

2022-05-14 22:06 UTC, mikehardy approved these changes
Just reading it is a grind :sweat_smile: - I read it twice and I still don't see anything, let's go

2022-05-14 22:16 UTC, merged

2022-05-14 23:32 UTC, david-allison commented
> Just reading it is a grind 😅 - I read it twice and I still don't see anything, let's go

Thanks!

Most painful one I've done as the automatic conversion completely failed. Fingers crossed that's all!