[View binding] Dialogs package
ankidroid/Anki-Android pull request #11308
Opened 2022-05-10 18:54 UTC by Jatin887

## Pull Request template

## Purpose / Description
Added ViewBinding for 
1) LocaleSelectionDialog
2) DeckSelectionDialog
3) MediaCheckDialog
4) ScopedStorageMigrationDialog

## Fixes
Part of (https://github.com/ankidroid/Anki-Android/issues/11116)

## Approach
Removed findViewById with the help of implementing binding class for all the files

## How Has This Been Tested?
Physical Device OnePlus Nord2

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-10 19:16 UTC, Jatin887 commented
@david-allison the checks are failed because no viewBinding is available in buildGradle so when the pull request [https://github.com/ankidroid/Anki-Android/pull/11292] will be merged it will work fine
![image](https://user-images.githubusercontent.com/71597104/167705161-b892d93f-e08c-4e7e-97f6-7845925e5f6d.png)

2022-05-10 19:19 UTC, david-allison commented
This doesn't compile.

I thought you said you were going to put in one PR?

2022-05-10 19:23 UTC, Jatin887 commented
> This doesn't compile.
> 
> I thought you said you were going to put in one PR for this change?
Because the main branch doesn't have viewBinding  = true in buildGradle
I added this in pull request [https://github.com/https://github.com/ankidroid/Anki-Android/pull/11292]

no i clearly mentioned that i will open one pr for all the files which are available in each package of ichi2\anki and one commit for each file should i change the fomat? What's your opinion

2022-05-10 19:25 UTC, david-allison commented
I misread, apologies. How many PRs is this going to be?

2022-05-10 19:27 UTC, Jatin887 commented
> I misread, apologies. How many PRs is this going to be?

Approximately 4-5 Pull requests

2022-05-10 19:32 UTC, david-allison commented
That's fine with me

2022-05-11 04:11 UTC, david-allison commented
> > That's fine with me. Could you 'draft' them until they're all ready?
> 
> But all the checks for the pr's will going to be failed because this pr [https://github.com/[/pull/11292](https://github.com/ankidroid/Anki-Android/pull/11292)] contain the changes in build gradle and that should be merged in main I guess to run all checks?

I wouldn't be opposed to cherry picking one commit onto the 'base' of each PR to get CI to go green, as long as the PRs are drafts

2022-05-11 09:45 UTC, lukstbit commented
@Jatin887 You should add the code to enable viewBinding to all of your PRs. If you place the lines on the same position you shouldn't get a conflict and we get the ability to run the checks.

2022-05-11 09:52 UTC, lukstbit requested changes

2022-05-11 09:52 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt
> +            return TextViewHolder(bindingDialogFragment.root)
Use a better, more descriptive, name for the binding, like `bindingRowView`, `rowViewBinding`. `bindingDialogFragment` would suggest a binding for the entire dialog view which is not the case.

Also, pass the binding directly to the ViewHolder. Right now, if the row would change then you would have to modify not only the ViewHolder itself but also the onCreateViewHolder method. If you pass the binding then only the ViewHolder would need to change.

2022-05-11 10:08 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> +                val binding = MediaCheckDialogBodyBinding.inflate(layoutInflater)
Use a better name, local to the layout it represents if you're not targeting the main layout.

2022-06-08 23:39 UTC, david-allison requested changes

2022-06-08 23:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt
> +            return TextViewHolder(bindingDialogFragment.root)
@Jatin887 this should be addressed in the initial commit, not by an additional commit

2022-06-08 23:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt
> +                parent, false
add a named argument to this call

2022-06-08 23:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> +                val binding = MediaCheckDialogBodyBinding.inflate(layoutInflater)
Shouldn't this be a member variable?

2022-06-08 23:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ScopedStorageMigrationDialog.kt
> +        val checkboxesRequiredToContinue = listOf(binding.scopedStorageNoUninstall, backupMethodToUse)
`scopedStorageNoUninstall` - probably needs a better name

2022-12-18 12:43 UTC, closed without merging