View binding multimedia card actitvity package
ankidroid/Anki-Android pull request #11324
Opened 2022-05-11 07:27 UTC by Jatin887

## Pull Request template

## Purpose / Description
ViewBinding
## Fixes

## Approach

## How Has This Been Tested?

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-11 10:49 UTC, lukstbit requested changes

2022-05-11 10:49 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +        progressBarLayoutBinding = ProgressBarLayoutBinding.inflate(layoutInflater)
The second binding is not ok and it introduces a bug. The layout containing the ProgressBar is included in the activity layout but you're inflating a layout which is not connected to anything(you'll not see the ProgressBar). The proper way to access the Progressbar is to go to the activity layout, give to the included layout an id(like the root view id from the inflated layout) and then you can use:

`binding.idOfIncludedLayout.includedLayoutView`

2022-05-11 10:53 UTC, lukstbit requested changes

2022-05-11 10:53 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.kt
> +    private lateinit var progressBarLayoutBinding: ProgressBarLayoutBinding
The same mistake as in the LoadPronunciationActivity with the two bindings.
Also this activity will most likely be removed soon(in #11194 )

2022-05-11 10:55 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +        progressBarLayoutBinding = ProgressBarLayoutBinding.inflate(layoutInflater)
I know this contain a bug(I was just  trying to try this method). I marked all the pr as draft i request that please give your comments when I mark it as ready for review. I am still working on these pull requests .

2022-05-11 10:59 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.kt
> +    private lateinit var progressBarLayoutBinding: ProgressBarLayoutBinding
Translation activity is going to be removed or Load Pronunciation?

2022-05-11 11:11 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.kt
> +    private lateinit var progressBarLayoutBinding: ProgressBarLayoutBinding
TranslationActivity will be removed.

2022-05-11 11:26 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.kt
> +    private lateinit var progressBarLayoutBinding: ProgressBarLayoutBinding
I changed asyncTask to coroutines for translationActivity last night was just going to open a pull request :(

2022-05-11 13:40 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.kt
> +    private lateinit var progressBarLayoutBinding: ProgressBarLayoutBinding
Oh bummer - very sorry about that, it was on the "probably to remove" list for a while based on our usage statistics and how frequently the code breaks, but there is not a good way to communicate that. We remove things almost never so we don't really have a process, and there's nothing else pending remove so not worth making a process for it. But sincerely, condolences I *hate* working on things that go poof and disappear, I really do sympathize

2022-06-06 02:15 UTC, Arthur-Milchior reviewed
My questions are real questions. You're using a tool I don't know, and I'm trying to get a better understanding of the change you want and how to review it.
So, even more than always, feel free to disagree with what I say and let me know why I was wrong

2022-06-06 02:15 UTC, Arthur-Milchior commented on AnkiDroid/build.gradle
> +        viewBinding = true
Could you maybe put this alone in a first commit alone please?

2022-06-06 02:15 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> -        progressBarLayoutBinding = ProgressBarLayoutBinding.inflate(layoutInflater)
I'd personally go with `progressBarLayoutBinding = ProgressBarLayoutBinding.progressBar`, unless there is anything wrong with this idea.
This would in particular allow to have this commit as easy as possible to review, with a change as small as possible.

2022-06-06 02:15 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +        progressBarLayoutBinding = ProgressBarLayoutBinding.inflate(layoutInflater)
I'm confused. It's not marked as a draft anymore, but it seems @lukstbit remark is still present in this commit. Did you finally believe it's a good change, or was it forgotten to be corrected.

2022-06-07 16:09 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +        progressBarLayoutBinding = ProgressBarLayoutBinding.inflate(layoutInflater)
I chnaged it and it's working fine

2022-06-07 16:16 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> -        progressBarLayoutBinding = ProgressBarLayoutBinding.inflate(layoutInflater)
I removed  progressBarLayoutBinding = ProgressBarLayoutBinding.inflate(layoutInflater) this and added a id for the layout in xml file progressbar now we can use it as progressBarLayoutBinding = ProgressBarLayoutBinding.progressBar

2022-12-17 19:36 UTC, closed without merging