[Kotlin Cleanup] ReminderServiceTest
ankidroid/Anki-Android pull request #11338
Opened 2022-05-12 14:51 UTC by oyeraghib

## Purpose / Description
[Kotlin Cleanup] ReminderServiceTest

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-12 14:59 UTC, david-allison requested changes

2022-05-12 14:59 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/services/ReminderServiceTest.kt
> +        assertThat("No notifications exist", notificationManagerShadow.size(), Matchers.equalTo(0))
import `Matchers`.

See if you can use `Matchers.hasSize` instead

2022-05-13 11:57 UTC, oyeraghib commented on AnkiDroid/src/test/java/com/ichi2/anki/services/ReminderServiceTest.kt
> +        assertThat("No notifications exist", notificationManagerShadow.size(), Matchers.equalTo(0))
using `hasSize` is causing

`Type mismatch.
Required:
(MutableCollection<out TypeVariable(E)!>..Collection<TypeVariable(E)!>?)`
`Found:
Int!`

2022-05-13 11:59 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/services/ReminderServiceTest.kt
> +        assertThat("No notifications exist", notificationManagerShadow.size(), Matchers.equalTo(0))
Import `Matchers` and it's done then

2022-05-13 12:05 UTC, oyeraghib commented on AnkiDroid/src/test/java/com/ichi2/anki/services/ReminderServiceTest.kt
> +        assertThat("No notifications exist", notificationManagerShadow.size(), Matchers.equalTo(0))
Not sure but I guess the `hasSize` requires `MutableCollection` something. It still shows a mismatch :

`Type mismatch.
Required:
(MutableCollection<out TypeVariable(E)!>..Collection<TypeVariable(E)!>?)`
`Found:
ShadowNotificationManager!`

2022-05-13 12:14 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/services/ReminderServiceTest.kt
> +        assertThat("No notifications exist", notificationManagerShadow.size(), Matchers.equalTo(0))
Sure, fine to leave it then

2022-05-13 12:14 UTC, david-allison approved these changes

2022-05-13 15:18 UTC, mikehardy approved these changes
:boom:

2022-05-13 15:18 UTC, merged