[Kotlin Cleanup] CollectionUtils
ankidroid/Anki-Android pull request #11335
Opened 2022-05-12 14:11 UTC by oyeraghib

## Pull Request template

## Purpose / Description
[Kotlin Cleanup] CollectionUtils

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-12 22:22 UTC, david-allison requested changes

2022-05-12 22:22 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/testutils/CollectionUtils.kt
> -    @KotlinCleanup("use mockito-kotlin")
Keep this as `use mockito-kotlin after DB.java is converted`

2022-05-13 11:46 UTC, david-allison approved these changes

2022-05-13 15:28 UTC, mikehardy approved these changes
nice!

2022-05-13 15:30 UTC, merged