[Kotlin Cleanup] ActionButtonStatusTest
ankidroid/Anki-Android pull request #11337
Opened 2022-05-12 14:33 UTC by oyeraghib

## Pull Request template

## Purpose / Description
[Kotlin Cleanup] ActionButtonStatusTest

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-12 15:06 UTC, david-allison requested changes

2022-05-12 15:06 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/reviewer/ActionButtonStatusTest.kt
> +            containsInAnyOrder(*requireNonNull<Array<Any>>(actualPreferenceKeys.toTypedArray()))
```suggestion
            containsInAnyOrder(*actualPreferenceKeys.toTypedArray())
```

2022-05-13 12:14 UTC, david-allison approved these changes

2022-05-27 16:07 UTC, oyeraghib commented
@mikehardy I am not sure but I think this branch doesn't have any issues and is also approved. Please have a look.

2022-05-31 21:13 UTC, merged