[Kotlin migration] AnkiPackageExporterTest
ankidroid/Anki-Android pull request #11356
Opened 2022-05-16 04:58 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
Kotlin migration of AnkiPackageExporterTest
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-01 00:20 UTC, Arthur-Milchior requested changes

2022-06-01 00:20 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.kt
> +        for (x in files) {
add a cleanup to use a mapIndexed

2022-06-01 00:20 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.kt
> + 	 <!-- Comment
Nope, I'm sorry, but this is not readable. I believe automated translation correctly transformed unicode code in its unicode equivalent. But there is no easy way for a human reading code to see all symbols here. 
There is even a risk that some automated cleaning tool want to remove the tab, and that it's not catched at review.

Actually, I'd even love if you'd consider adding a cleanup to document what are the various unicode characters we use here.

2022-06-01 00:20 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.kt
> +        val text = """
cleanup `@language("html")`

2022-06-01 00:20 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.kt
> +    private fun checkMediaExportStringIs(files: Array<File?>, s: String) {
Can you have `Array<File>` instead?

2022-06-22 10:49 UTC, Prince-kushwaha commented on AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.kt
> +    private fun checkMediaExportStringIs(files: Array<File?>, s: String) {
not possible to make array not nullable

2022-06-26 06:31 UTC, Prince-kushwaha commented
@david-allison Doesn't compile is due to CI https://github.com/ankidroid/Anki-Android/issues/11091#issuecomment-1130226317

2022-06-26 13:58 UTC, mikehardy commented
@Prince-kushwaha 

> Doesn't compile is due to CI [#11091 (comment)](https://github.com/ankidroid/Anki-Android/issues/11091#issuecomment-1130226317)


Nope - that's not how it works

1- it is compiling (now at least?), so "doesn't compile" is not the correct statement. "Doesn't pass unit tests..." is the correct statement

2- your linked comment is a flaky test I am tracking, but you are failing on **exactly the code you altered** not that test.

Something you have done here has broken unit tests somehow

```

AnkiPackageExporterTest > fileInExportIsCopied FAILED
    java.lang.AssertionError: 
    Expected: iterable with items ["collection.anki2", "media", "0"] in any order
         but: not matched: ["collection.anki2", "0", "media"]
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at com.ichi2.libanki.AnkiPackageExporterTest.fileInExportIsCopied(AnkiPackageExporterTest.kt:109)
AnkiPackageExporterTest > missingFileInDeckExportDoesSkipsFile FAILED
    java.lang.AssertionError: 
    Expected: iterable with items ["collection.anki2", "media"] in any order
         but: not matched: ["collection.anki2", "media"]
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at com.ichi2.libanki.AnkiPackageExporterTest.missingFileInDeckExportDoesSkipsFile(AnkiPackageExporterTest.kt:76)
```

2022-08-23 21:29 UTC, david-allison commented
Superseded by https://github.com/ankidroid/Anki-Android/pull/12100

2022-08-23 21:29 UTC, closed without merging