[Kotlin Migration] CopyrightHeaderExistsTest Lint TEST
ankidroid/Anki-Android pull request #11362
Opened 2022-05-16 19:34 UTC by prateek-singh-3212

Migrated CopyrightHeaderExistsTest.java to CopyrightHeaderExistsTest.kt

2022-05-17 00:25 UTC, david-allison requested changes
Minor fix, then looks good to go, thanks!

2022-05-17 00:25 UTC, david-allison commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/CopyrightHeaderExistsTest.kt
> +        TestLintTask.lint()
Could do with fixing the imports to match the Java:

`TestLintTask`, `JavaTestFile`, `Assert`

2022-05-17 06:31 UTC, prateek-singh-3212 commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/CopyrightHeaderExistsTest.kt
> +        TestLintTask.lint()
kindly check

2022-05-17 16:51 UTC, david-allison approved these changes

2022-05-18 14:41 UTC, mikehardy approved these changes
another one converted :muscle:

2022-05-18 16:08 UTC, merged