Fix Type Answer Diff for combining marks not showing up
ankidroid/Anki-Android pull request #11374
Opened 2022-05-18 19:29 UTC by dorrin-sot

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes #10665 

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-18 19:37 UTC, dorrin-sot commented
This is how anki desktop handles this:

https://github.com/ankitects/anki/blob/638286a3fcbcaaa3d95fbcb1bc2dd32c4b97a749/qt/aqt/reviewer.py#L715

2022-05-19 01:47 UTC, david-allison requested changes
Could you add a unit test 

AND

Run the unit test you added with this and `SCHEMA_VERSION` set to 16:

https://github.com/ankidroid/Anki-Android/blob/599c50575148ed8259cf8eda7fd858244f773a62/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java#L82-L90

We will be removing this functionality shortly, and I want to ensure we don't revert this when moving to the new method.

2022-05-19 09:03 UTC, dorrin-sot commented
@david-allison 
Like this?

```diff
diff --git a/AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt b/AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
@@ -106,7 +106,7 @@
 
     // deck schema & syncing vars
     @JvmField
-    var SCHEMA_VERSION = 11
+    var SCHEMA_VERSION = 16
 
     /** The database schema version that we can downgrade from  */
     const val SCHEMA_DOWNGRADE_SUPPORTED_VERSION = 16
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
@@ -87,7 +87,7 @@
      *
      * Set this and {@link com.ichi2.libanki.Consts#SCHEMA_VERSION} to 16.
      */
-    public static boolean TESTING_USE_V16_BACKEND = false;
+    public static boolean TESTING_USE_V16_BACKEND = true;
 
     public static final String XML_CUSTOM_NAMESPACE = "http://arbitrary.app.namespace/com.ichi2.anki";
```

2022-05-27 12:15 UTC, david-allison approved these changes
Tentatively approving, with the expectation that a comment is added. Thanks so much!

Sorry about the delay - life's really busy right now

2022-05-27 12:15 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/DiffEngine.kt
> +        fun escapeLoneMarks(`in`: String): String {
nit: rename the variable to avoid backticks

2022-05-27 12:15 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/DiffEngine.kt
> +        fun escapeLoneMarks(`in`: String): String {
Could you add a doc-comment here, this would be difficult for the next user to understand

2022-05-27 12:16 UTC, david-allison commented
Forgot to reply, that's perfect!

2022-05-30 02:20 UTC, mikehardy commented
:disappointed: took a conflict while waiting - apologies, been quite busy myself playing catch-up after the GSoC barrage over here :-)

2022-05-30 05:43 UTC, dorrin-sot commented
Cherry-picked the kt-migrate commits and added the test back as kotlin :)

2022-06-03 13:47 UTC, mikehardy approved these changes
LGTM! thanks for plowing through the conflicts and all that, honestly this is the busiest repository I work on including the react-native repository :sweat_smile: - you have to be persistent to get a change committed in here!

2022-06-03 13:49 UTC, merged