[Kotlin migration] FieldEditLineTest.kt
ankidroid/Anki-Android pull request #11378
Opened 2022-05-19 10:52 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
Kotlin migration of FieldEditLineTest
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-19 15:58 UTC, david-allison requested changes

2022-05-19 15:58 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/FieldEditLineTest.kt
> +@RunWith(AndroidJUnit4::class)
I'd add a cleanup to use scope functions as well

2022-05-19 15:58 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/FieldEditLineTest.kt
> +    protected val fieldEditLine: FieldEditLine
cleanup to move this back to a method

2022-05-31 21:51 UTC, Arthur-Milchior commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/FieldEditLineTest.kt
> +@RunWith(AndroidJUnit4::class)
@Prince-kushwaha 
Do you plan to do it?
No emergency, I just want to know whether this is an abandonned commit or not

2022-06-17 23:55 UTC, david-allison approved these changes

2022-06-25 21:35 UTC, mikehardy approved these changes
LGTM thanks!

2022-06-25 21:42 UTC, merged