[Kotlin Migration] ModeTest
ankidroid/Anki-Android pull request #11381
Opened 2022-05-19 11:40 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
Kotlin migration of ModelTest
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-31 22:53 UTC, Arthur-Milchior requested changes

2022-05-31 22:53 UTC, Arthur-Milchior commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ModelTest.kt
> +    private var mTestCol: Collection? = null
Please add kotlincleanup lateinit

2022-06-13 19:28 UTC, mikehardy commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ModelTest.kt
> +    private var mTestCol: Collection? = null
verified comment addressed :+1:

2022-06-13 19:28 UTC, mikehardy approved these changes
Nice, thank you!

2022-06-13 20:03 UTC, merged