Kotlin migration HttpTest
ankidroid/Anki-Android pull request #11385
Opened 2022-05-19 13:40 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
Kotlin migration of HttpTest
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-19 17:52 UTC, david-allison requested changes
```
> Task :AnkiDroid:lintReportPlayDebug
Wrote HTML report to file:///home/runner/work/Anki-Android/Anki-Android/AnkiDroid/build/reports/lint-results-playDebug.html

> Task :AnkiDroid:lintPlayDebug FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/HttpTest.kt:1: Error: Comment contents were corrupted by the Kotlin migration. For example: <http:></http:> [KotlinMigrationBrokenEmails from com.ichi2.anki:lint-rules]
/***************************************************************************************
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/HttpTest.kt:91: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
        internal var mDisconnectedCalled = false
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors, 0 warnings
```

2022-05-31 23:12 UTC, Arthur-Milchior requested changes

2022-05-31 23:12 UTC, Arthur-Milchior commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/HttpTest.kt
> +    @Test // #7108: AsyncTask
Please leave the comment on the suppression, since the reason we have deprecation warinng is async task

2022-06-17 23:56 UTC, david-allison requested changes
Only one commit

2022-06-18 18:59 UTC, david-allison approved these changes

2022-06-25 14:32 UTC, krmanik approved these changes

2022-06-25 14:33 UTC, merged