[Kotlin Migration] FinderTest
ankidroid/Anki-Android pull request #11389
Opened 2022-05-19 21:31 UTC by n1snt

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-31 22:08 UTC, Arthur-Milchior requested changes

2022-05-31 22:08 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
> +        Assert.assertEquals(5, col.findCards("tag:*").size.toLong())
Can you remove the `toLong`? I tested locally and it semes to work without it

2022-05-31 22:12 UTC, Arthur-Milchior commented
Once this one is merged, finish #11388

2022-06-01 08:52 UTC, n1snt commented
@Arthur-Milchior Just made all the changes you request please have a look at this & let me know if there are any changes to be made.

2022-06-01 15:34 UTC, david-allison submitted a review, later dismissed
Thanks!

2022-06-01 15:34 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
> +            Matchers.hasItem(manuallyBuriedCard.id)
import: `Matchers`

2022-06-01 15:34 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
> +@RunWith(AndroidJUnit4::class)
`@KotlinCleanup("is -> equalTo")`

2022-06-01 15:34 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
> +import com.ichi2.libanki.SortOrder.UseCollectionOrdering
Remove both these imports and qualify the callers with `SortOrder.`

2022-06-01 15:34 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
> +        val col = col
would be nice to fix the spacing of this method to match the Java

2022-06-01 15:34 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
> +        val `val` = "*Yr1::Med2::CAS4::F4: Renal::BRS (zanki)::HY"
`@KotlinCleanup("rename val")`

2022-06-01 15:34 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
> +        val toAnswer: Card? = sched.card
Don't refactor code in a migration commit, this should be as close to the Java as possible

2022-06-03 16:51 UTC, n1snt commented on AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
> +        val col = col
Done

2022-06-03 16:52 UTC, n1snt commented on AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
> +@RunWith(AndroidJUnit4::class)
Done

2022-06-03 16:52 UTC, n1snt commented on AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
> +            Matchers.hasItem(manuallyBuriedCard.id)
Done

2022-06-03 16:52 UTC, n1snt commented on AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
> +        val buriedCards = Finder(col).findCards(searchQuery, NoOrdering())
Done

2022-06-03 21:49 UTC, Arthur-Milchior approved these changes

2022-06-03 21:50 UTC, merged