[Kotlin Cleanup] DeckPickerCheckDatabaseListenerTest
ankidroid/Anki-Android pull request #11399
Opened 2022-05-21 07:45 UTC by n1snt

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-26 14:06 UTC, Arthur-Milchior reviewed
Thanks for this clean-up.

For a future PR, I'd love to ask you for atomic commits. I would have found simpler to review if you had one commit with lateinit. One commit where you replace `didDisplayDialogLoadFailed` from a function to a variable, and so on.
Or at least, that your commit message state that you're doing three things simultaneously. Because right now, I started the review with no idea of what I'd found, and I don't even know which parts are related and which parts are independant.

2022-05-27 15:49 UTC, n1snt commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.kt
> +    class DeckPickerTestImpl : DeckPicker() {
I had removed protected because the IDE suggested it, It displayed the following message:
` 'protected' visibility is effectively 'private' in a final class`

2022-05-27 15:50 UTC, n1snt commented
@Arthur-Milchior I have updated this PR to use atomic commits. Have a look at this & let me know if there are any changes to be made.

2022-05-27 15:50 UTC, n1snt commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.kt
>  @KotlinCleanup("IDE lint")
Done.

2022-05-31 21:39 UTC, Arthur-Milchior requested changes

2022-05-31 21:39 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.kt
>  @KotlinCleanup("IDE lint")
What means "Signed-off-by: Nishant <getrooted0019@hotmail.com>" in your commit message? Not especially a problem, but we're not used to this, here. Especially, we have no way to check whether you are actually the one who signed it, at least in a cryptographic sense.

Also, I'd love that you explain in the commit message why the lateinit is valid. It can simply be that the value is setted in a setup or onCreate. But at least, if someone look at the history of the lateinit line, they'll see the reasonning

2022-05-31 21:39 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.kt
> +        var didDisplayDialogLoadFailed = false
Please make the setter private, so that outside of this class, people can't change the value.

2022-05-31 21:39 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.kt
> -        private var mDidDisplayMessage = false
same here

2022-05-31 21:39 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.kt
> -        private var mDidDisplayDbLocked = false
and here

2022-07-10 08:02 UTC, n1snt commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.kt
> +        var didDisplayDialogLoadFailed = false
What does "replace getters with variables" mean here? I'm a bit confused.

2022-07-10 13:36 UTC, Arthur-Milchior approved these changes

2022-07-10 13:36 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.kt
>  @KotlinCleanup("IDE lint")
I'd appreciate an answer. Not blocking, but still, would love to understand.

2022-07-10 13:36 UTC, merged

2022-07-10 14:53 UTC, n1snt commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.kt
>  @KotlinCleanup("IDE lint")
Sorry for the late reply, I think android studio does this by default if we enable the sign-off commit option in
![image](https://user-images.githubusercontent.com/46300244/178150081-d888ad73-e6c4-4038-875d-f76469bf2781.png)