Fixed the bug that filtered study decks don't show in Card browser
ankidroid/Anki-Android pull request #11401
Opened 2022-05-21 11:42 UTC by MrPenguins

## Purpose / Description
Filtered study decks don't show in the card browser's deck search dialog.

## Fixes
Fixes [#10684](https://github.com/ankidroid/Anki-Android/issues/10684)

## Approach
The problem is caused by the `displayDeckSelectionDialog` function. In this function, only non-dynamic decks will be displayed in the dialog. I changed the filter requirements to display all the decks in the card browser's deck search dialog. This function is called by `setSpinnerListener` and `onKeyUp` in `com/ichi2/anki/NoteEditor.kt`. I create another two functions `setSpinnerListenerForNoteEditor` and `displayDeckSelectionDialogForNoteEditor`, so the behavior of the deck search dialog in the card browser is fixed and the behavior in the note editor screen is not affected.

## How Has This Been Tested?

It was manually tested on the emulator (Pixel 2 API 29).
The deck search dialog in the card browser screen:
![image](https://user-images.githubusercontent.com/56572306/169650070-92e66154-ff16-4447-9da3-058acb1cd495.png)

The deck search dialog in the note editor screen:
![image](https://user-images.githubusercontent.com/56572306/169650104-fb6e91e0-2f7d-4e1b-a8a5-46b9d3e415fe.png)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-26 14:47 UTC, Arthur-Milchior commented
Nice to meet you @MrPenguins, and thanks a lot for correcting this bug.
However, I fear that I'll have to require some change from you. It seems you are using a lot of copy pasting, leading to code duplication. Code duplication is generally avoided, because if one day we must change the function, it mean we change it in two places. And we risk to forget to change it into one place.
On top of that, it means that we must test two functions (at least the day when we add test for this)

If you look at the class you changed in details, you may see it already takes many parameters. To indicate whether it should display "all decks" whether it should display the default deck even if empty, and so on. In this case, we can do the same thing, adding an extra parameter, let's say `showFilteredDecks`.

Are you willing to update the PR taking this into account?

2022-05-28 06:34 UTC, MrPenguins commented
Sure, I will fix it.

2022-05-31 21:41 UTC, Arthur-Milchior commented
@MrPenguins Wonderful. Let me know when you want me to re review it

2022-06-03 08:24 UTC, MrPenguins commented
@Arthur-Milchior Hi, I added `showFilteredDecks` in `DeckSpinnerSelection.kt`. So now we can decide whether show filtered decks by changing the value of `showFilteredDecks`.

The deck search dialog in the card browser screen will show the filtered decks:
![image](https://user-images.githubusercontent.com/56572306/171817065-c79a6385-23e0-4269-9040-06037a08c2b6.png)

The deck search dialog in the Statistics screen will show the filtered decks:
![image](https://user-images.githubusercontent.com/56572306/171817223-6df3d17d-bfa5-4b27-9d97-38047b935253.png)

The deck search dialog in the note editor screen will not show the filtered decks:
![image](https://user-images.githubusercontent.com/56572306/171817355-848260f2-b07a-4a40-82f4-9c8a804ee5b2.png)

2022-06-05 02:54 UTC, Arthur-Milchior requested changes
Thank you so much for taking time to take my requests into consideration.
I admit it's far easier to read now.
Still a few nits, but nothing as massive as last time.

2022-06-05 02:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
> +    private val showFilteredDecks: Boolean
If you please, I'd love a comma after the last val. So if we need to add yet another parameter, the last line won't be changed.
Alternatively, we can but showFilteredDecks earlier in the list, just to ensure that we don't add a comma to alwaysShowDefault.

2022-06-05 02:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            DeckSpinnerSelection(this, col, findViewById(R.id.note_deck_spinner), false, true, false)
I think it may be nice to copy Statistics.kt and make names explicit. It is true that false true false is not clear, as it don't state what are each boolean associated to

2022-06-05 02:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
> +            FunctionalInterfaces.Filter { _: Deck? -> true }
You could simplify yet again with `FunctionalInterfaces.Filter { d: Deck? -> showFilteredDecks || !Decks.isDynamic(d) }`

2022-06-05 02:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
> + * @param showFilteredDecks If true, always show filtered decks
I'd go with "whether to show filtered decks". I'm not fan of "if true", always seems redundant to me.
Admittedly, you're copying previous line form, so implementor's choice.

2022-06-06 06:46 UTC, Arthur-Milchior commented
Thanks very much.
Would you mind rebasing onto main (so that you'll also deal with the conflict), and adding the changes in the commit where you touched the lines, instead of correcting everything in a last commit

2022-06-06 07:33 UTC, MrPenguins commented
Is it right now? I'm not very familiar with git so I'm not sure whether I messed up.

2022-06-26 20:35 UTC, Arthur-Milchior commented
Sorry for the delay. it was probably right, but in the meantime, some more changes led to conflict, so I'll need in any case to have you rebase on top of main.
(Be sure to rebase on top of ankidroid's main and not the main of your clone)

2022-08-18 22:13 UTC, mikehardy approved these changes
I've resolved things and rebased it over main with all commits squashed
LGTM

2022-08-18 23:38 UTC, merged