Migrate LaTeX to kotlin
ankidroid/Anki-Android pull request #11415
Opened 2022-05-25 04:43 UTC by lukstbit

## Purpose / Description

Migrates the LaTeX.java file to kotlin following the migration guide. Had to wrap the latex tag listing in the class docs with **```** as kotlin uses `[]` for references.

## How Has This Been Tested?

Ran the usual tests.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-26 22:02 UTC, Arthur-Milchior requested changes

2022-05-26 22:02 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.kt
> +        var ext = "png"
At least as cleanup, us a val. You can just do 
`val ext = if (model.optBoolean("latexsvg", false)) "svg" else "png"`

2022-05-26 22:02 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.kt
> +        l = Utils.stripHTML(l)
as cleanup, return immediately. Or even juste a single line. In any case use val instead of var

2022-05-27 16:05 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.kt
> +        l = Utils.stripHTML(l)
Added a @KotlinCleanup for this.

2022-05-27 16:06 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.kt
> +        var ext = "png"
Added a @KotlinCleanup for this

2022-05-27 16:07 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.kt
> +        var matcher = STANDARD_PATTERN.matcher(html)
Addressed all requested issues with @KotlinCleanup notices.

2022-05-29 10:34 UTC, Arthur-Milchior approved these changes
thanks a lot for taking my remarks into account

2022-05-29 10:34 UTC, merged