Factorize close
ankidroid/Anki-Android pull request #11425
Opened 2022-05-25 17:31 UTC by Arthur-Milchior

Yet another part of https://github.com/ankidroid/Anki-Android/pull/11418 which can be considered separately

It considers the actions that can close preferences

2022-08-03 16:43 UTC, BrayanDSO commented
`AppCompatPreferenceActivity.kt` will be gone when someone takes up #5019 and DeckOptions/FilteredDeckOptions probably will inherit from `AnkiActivity` then. Even so, these refactors may help in the future, so I'm just stating it.

2022-08-03 23:34 UTC, Arthur-Milchior commented
Thanks.
FYI, @BrayanDSO , even if you can't merge a PR, you can review it. Since you seemed to already have an idea about it, you should be able to use github to approve it (or require change)

2022-08-18 23:24 UTC, mikehardy approved these changes
LGTM but needs de-conflicting

2022-08-19 15:54 UTC, Arthur-Milchior commented
@mikehardy done

2022-08-19 18:12 UTC, BrayanDSO requested changes
I think that this may have been contaminated by one of the other related PRs. The rest looks good to me.

2022-08-19 18:12 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
> +        updateSummaries()
This seems like it is from #11423 / doesn't fit the commit purpose

2022-08-19 18:16 UTC, BrayanDSO approved these changes
LGTM. Thanks for the changes. DeckOptions/FilteredDeckOptions aren't very pleasant files, so this cleaning helps a lot.

Waiting CI

2022-08-19 18:50 UTC, merged