[ViewBinding]-ankiPacakge
ankidroid/Anki-Android pull request #11438
Opened 2022-05-28 08:10 UTC by Jatin887

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-28 08:13 UTC, Jatin887 commented
@david-allison i converted all the activities and fragments.
I have one doubt do you want me to create viewBinding classes for progress bars and toolbars? Because only that part is left

2022-06-08 23:47 UTC, david-allison requested changes

2022-06-08 23:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
> +        binding = CardBrowserAppearanceBinding.inflate(layoutInflater)
can this be moved to `onCreate`?

2022-06-08 23:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.kt
> +    private lateinit var bindingReviewerWhiteboardEditorBinding: ReviewerWhiteboardEditorBinding
This needs shortening, maybe `whiteboardBinding`?

2022-06-08 23:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.kt
> +                if (bindingReviewerWhiteboardEditorBinding.whiteboardEditor.visibility == View.GONE) {
Is this only a color palette?

This one might want a rename

2022-06-08 23:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
> +            binding.leftButton.setOnClickListener {
This needs either a refactoring or fixing, `marketButton` is much more readable

2022-06-08 23:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
> +                binding.info.loadUrl("file:///android_asset/changelog.html")
again: `webView` provides more information on the type

2022-06-08 23:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
> +            append(
changed without a reason

2022-06-08 23:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
> +            showThemedToast(
changed without a reason

2022-06-08 23:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
> +            append(
ditto

2022-06-08 23:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
> +                            mCardCounts!![mModelListPosition]
was this change intended? Seems good, but not part of the PR's scope

2022-06-08 23:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
> +        binding.resetPasswordButton.setOnClickListener { resetPassword() }
this change is awesome!

2022-06-08 23:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
> +    private val mLoginListener: Connection.TaskListener = object : Connection.TaskListener {
this is a refactoring and shouldn't be included in a 'viewbinding' change

2022-06-08 23:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
> +    private fun getHumanReadableLoginErrorMessage(exception: Exception?): String? {
ditto

2022-06-11 05:21 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.kt
> +                if (bindingReviewerWhiteboardEditorBinding.whiteboardEditor.visibility == View.GONE) {
Yes it is i will shorten the name

2022-06-13 07:04 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
> +                            mCardCounts!![mModelListPosition]
no i just solve that. so these files should not be fall into Kotlin Cleanup issue :)

2022-06-13 09:20 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
> +    private fun getHumanReadableLoginErrorMessage(exception: Exception?): String? {
done

2022-06-13 09:20 UTC, Jatin887 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
> +    private val mLoginListener: Connection.TaskListener = object : Connection.TaskListener {
done

2022-06-13 09:20 UTC, Jatin887 commented
@david-allison added-changes

2022-08-19 09:38 UTC, closed without merging