Solving issue #11275
ankidroid/Anki-Android pull request #11434
Opened 2022-05-27 08:47 UTC by L-keeey

## Purpose / Description
Like AnkiDesktop, I make the interval never be reseted when rescheduling, with prompt. But unfortunately I fail to add the checkbox in the dialog, to completely add the feature to choose to reset the interval or not. However, change the relevant method for preparation.

## Fixes
Fixes [[#11275]()](https://github.com/ankidroid/Anki-Android/issues/11275)

## Approach
By changing `reschedCards` in `AbstractSched.kt` and `SchedV2.java,  I enable the option of choosing whether change the interval. And I change the args for relevant test file.

## How Has This Been Tested?
Through manual multiple tests, this scheme is verified to be feasible. <br/>
Before: <br/>
![image](https://user-images.githubusercontent.com/67989850/170664147-d44fadf8-102b-4209-8b1b-407d1aa55536.png)
Scheduling: <br/>
![image](https://user-images.githubusercontent.com/67989850/170664366-b7ef8b60-ea97-4fbc-a15d-3d90eb4ef1cc.png)
![image](https://user-images.githubusercontent.com/67989850/170664456-03581518-1be8-4c62-b0a3-578946d1fbfb.png)
After: <br/>
![image](https://user-images.githubusercontent.com/67989850/170665028-5394d1f3-d42e-4b13-8f9a-ecabc4ddbe6e.png)

2022-05-27 10:34 UTC, Arthur-Milchior commented
Nice to meet you @L-keeey .
A first feedback, I'd appreciate a lot if you can give descriptive name to your PR. I have no idea what is 11434 from the top of my head. Which means that no reviewer can know by just looking at your PR whether it's an issue they want to consider or to leave to someone else.
Same remark with commit. If at some point we need to revert one, if it causes a bug, I want the commit name to explain why the change was made. "Update filename" is really not helpful. When I look at history of a file, I don't want to see the name again; I want to see the reason the line was modified/added

2022-05-27 10:48 UTC, Arthur-Milchior requested changes
As I stated in inline comment, I'd really love atomic commits, or even atomic PR. So that I can review and accept one change at a time. 19 commits will be a nightmare to review, and most things will be taking a lot of time to get merged, delayed by the few change I require
.

I did not go after the first commit, given the size, I'll wait until the PR are more atomic, so that reviewing gets simpler

2022-05-27 10:48 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +        return mFieldNames;
Why do you need to add it? On the first commit, I don't see use of them

2022-05-27 10:48 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                boolean isFMTValid = true;
I'm sorry, I have no idea what's going on. Do you think you may add all of this in a function, with a meaningful name and documentation. That would allow to unit test it. 
And most important, the commit where you introduce it should really explain why you're doing it; because I can't really review this commit if nothing explain the goal of the change.

In particular, when looking at file history, it must be clear why that was done without even opening a link. Details may be behind a link if it's complex, but we need at least a first paragraph explaining the main idea

2022-05-27 11:18 UTC, L-keeey commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +        return mFieldNames;
Sorry. It is about another issuse about the `CardTemplateEditor`. I didn't clear that for current branch. You can ignore all modification in `CardTemplateEditor`. I will update this file with the official released one.

2022-05-27 11:18 UTC, L-keeey commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                boolean isFMTValid = true;
Sorry. It is about another issuse about the CardTemplateEditor. I didn't clear that for current branch. You can ignore all modification in CardTemplateEditor. I will update this file with the official released one.

2022-05-27 11:33 UTC, L-keeey commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +        return mFieldNames;
@Arthur-Milchior 
![image](https://user-images.githubusercontent.com/67989850/170690783-016146f6-e569-4790-83ab-42f494f574b5.png)
In current branch version `CardTemplateEditor.java` doesn't exist and  `CardTemplateEditor.kt` is updated with the offical one. I realy don't know what is going on.

2022-05-27 11:37 UTC, L-keeey commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +        return mFieldNames;
Maybe `CardTemplateEditor.java` is the old version of `CardTemplateEditor.kt`. You may just delete  `CardTemplateEditor.java` file, but I am not quite sure about whether doing so will affect `CardTemplateEditor.kt`.

2022-05-27 11:47 UTC, L-keeey commented
Sorry about get so much irrelevant commits about `CardTemplateEditor.java` involved, I don't know why it happens. But following commits is really used in this pr.  As I mentioned `reschedCards` in `AbstractSched.kt` and `SchedV2.java` are modified to enable the option of choosing whether change the interval. And othet test file are changed due to args modifictaion of `reschedCards`.
![image](https://user-images.githubusercontent.com/67989850/170692720-99974178-26bf-495f-9338-d61aa0ffa6cb.png)

2022-05-27 11:59 UTC, L-keeey commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                boolean isFMTValid = true;
@Arthur-Milchior Same reason as above. May be only focus an the changed file can help the code review. Again I am sorry about getting those irrelevant commits involved.
![image](https://user-images.githubusercontent.com/67989850/170694982-b283cd82-1818-4f46-bd2f-1496f1c91579.png)

2022-05-28 08:26 UTC, L-keeey commented
I have cleaned up those unneccassary commit records. The rest are actual commits corresponding to Issue #11275.

2022-08-03 08:42 UTC, closed without merging