[Kotlin Cleanup] Cardbrowser pt1
ankidroid/Anki-Android pull request #11458
Opened 2022-05-30 17:04 UTC by dorrin-sot

2022-05-31 16:15 UTC, Arthur-Milchior requested changes

2022-05-31 16:15 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        deck ?: return
I agree with the comment you deleted.
In my mind, it would lead to something such as
```kotlin
deck?.let {
     mDeckSpinnerSelection!!.initializeActionBarDeckSpinner(this.supportActionBar!!)
     mDeckSpinnerSelection!!.selectDeckById(it.deckId, true)
  }
}
```

2022-05-31 16:15 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
>              s = if (showFileNames) Utils.stripSoundMedia(s) else Utils.stripSoundMedia(s, " ")
You can keep the sequence by doing
`.let{ if (showFileNames) Utils.stripSoundMedia(it) else Utils.stripSoundMedia(it, " ")}` and same below

2022-06-02 09:58 UTC, Arthur-Milchior commented
Please don't merge main into your branch. Rebase your branch onto main

2022-06-02 16:47 UTC, dorrin-sot commented
Done 😄

2022-06-05 00:34 UTC, Arthur-Milchior reviewed
One remaining question and either an answer or a change, then good to go

2022-06-05 00:34 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        deck?.deckId?.let { deckId ->
I'm sorry. It seems `deckId` can't be nul. So `deckId.let` should suffice. Why do you need `deckId?.let`?

2022-06-10 18:51 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        deck?.deckId?.let { deckId ->
this was because since we want to skip doing anything if deck is null. so if `deck` is null then `deck?.deckId` is null and so the predicate inside `deck?.deckId?.let{ ... }` wouldnt be called

2022-08-16 20:38 UTC, closed without merging