[Kotlin Cleanup] Cardbrowser pt10
ankidroid/Anki-Android pull request #11467
Opened 2022-05-30 18:19 UTC by dorrin-sot

Continued from #11466

2022-05-31 20:58 UTC, Arthur-Milchior requested changes

2022-05-31 20:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -                val cardIds = selectedCardIds
I want to keep this variable. Because `selectedCardIds` is a getter that do some work, transforming a list of card in a list of id. Not saving it mean duplicate workds.

2022-07-14 06:27 UTC, lukstbit requested changes

2022-07-14 06:27 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                        setArgs(getString(R.string.reposition_card_dialog_title), getString(R.string.reposition_card_dialog_message), 5)
This is going to fail. You're fetching some strings in the context of a fragment(because of the apply{}) which isn't yet added to an activity. It will not have a valid android context to get the strings. Use a proper context:

`this@CardBrowser.getString...`

2022-07-14 06:27 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -                val selectedCardIds = selectedCardIds
Please don't delete this line. The value of the selectedCardIds property is used again in this when case and it does a iteration over a (possible) large list.

2022-07-15 04:51 UTC, lukstbit approved these changes

2022-07-30 18:10 UTC, mikehardy commented
Needs a de-conflict + re-push and a fresh review from @Arthur-Milchior to move forward I think?

2022-07-31 18:09 UTC, Arthur-Milchior commented
I'll wait for the conflict to be resolved before re reviewing since it's not totally trivial to resolve. 
Sorry for the delay @dorrin-sot.

2022-08-07 22:16 UTC, Arthur-Milchior commented
Can you please rebase to resolve conflict.
Sorry, too many things to review simultaneously, hard to keep track

2023-02-09 05:37 UTC, closed without merging