[Kotlin Cleanup] Cardbrowser pt9
ankidroid/Anki-Android pull request #11466
Opened 2022-05-30 18:03 UTC by dorrin-sot

Continued from #11465

2022-05-30 21:53 UTC, Arthur-Milchior requested changes

2022-05-30 21:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            savedFiltersObj ?: return
I'd personally go with 
```kotlin
savedFiltersObj?.optStrings(searchName).let { mSearchTerms ->
 ...
}
```
I agree early returns are generally nice. However, in this particular case, my short Kotlin experience seems to indicate that putting all of the "non-null" part behind .? and a scope function is even nicer to have a natural ongoing flow of reading

2022-05-30 21:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            if (savedFiltersObj?.has(searchName) == true) {
This one is really strange. First time ever I see a `== true` that can't be removed. I feel like it's not great that it simultaneously for non-nullity and value. Maybe just because I'm not used to it. But I'd love to get a second opinion about it. I'd consider not taking this line change.

2022-05-30 21:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -        val ids = selectedCardIds
I'm sorry but this is not as good as you may initially think.
`selectedCardIds` has a getter, and if you read it, you can see it actually do some work. By using this value multiple time, you are doing the getter's work multiple time, costing more.
In this case, doing an initial computation and saving it is useful. 
Admittedly, it would make sens to move this assignment after the two early returns below, so that if don't use this value, you don't compute it.

This is one thing where I'm ambivalent with Kotlin to be honest, and with any class which don't distinguish between properties and getter. Accessing a property can actually be costly

2022-05-30 21:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        val undo = mActionBarMenu?.findItem(R.id.action_undo)
You may want to get yourself familiar with Kotlin's scope function: https://kotlinlang.org/docs/scope-functions.html 
You are doing great improvement work. On such huge files, it's really useful to improve it's readability; and I believe you are still missing some cases where they may be obvious tools.

In this case, I'd go with 
```Kotlin
mActionBarMenu?.findItem(R.id.action_undo)?.run { undo ->
  isVisible = col.undoAvailable()
  title = resources.getString(R.string.studyoptions_congrats_undo, col.undoName(resources))
}
```
Using `run` you don't even have to repeat `undo` multiple time.

2022-05-31 19:17 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            savedFiltersObj ?: return
I'm totally okay with you selecting a different solution than the one I asked for. I'd please ask that in this case, you put a small word explaining why, and not to resolve the discussion.
I have a preference for the other one, but it's really a matter of taste and am okay with merging this version. I just want to know that when it's "resolved" it means that we agreed before

2022-05-31 19:20 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -        val ids = selectedCardIds
Please do not resolve without following my remark or explaining why you disagree. In this commit, I still see selectedCardIds removed, without explanation and without being reverted

2022-05-31 19:21 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        val undo = mActionBarMenu?.findItem(R.id.action_undo)
same

2022-06-01 06:23 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -        val ids = selectedCardIds
I added `selectedCardIds.run {...}` so we don't create a new variable but also don't repeat computation

2022-06-01 06:27 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            if (savedFiltersObj?.has(searchName) == true) {
I agree that `== true` but I actually prefer this more than multiple `!=` checks

2022-06-05 14:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            if (savedFiltersObj?.has(searchName) == true) {
You're perfectly right. I have accepted other `== true` since. I guess I just have to get used to it.

2022-06-05 15:01 UTC, Arthur-Milchior approved these changes
One last part I don't really understand. Why you resolved something without answering or applying my request. But work is good enough now to just merge the change, and hopefully @dorrin-sot , you'll do the last bit in another PR (or explain why you disagreed)

2022-06-05 15:01 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        val undo = mActionBarMenu?.findItem(R.id.action_undo)
This is another one where I don't understand why you resolved it.
I'll repeat, but I'm fan if you disagree. There is nothing wrong if you believe that scope function here is worse than using `undo?.` twice. I just would love for you to explain why instead of resolving if you disagree

2022-06-05 15:01 UTC, merged

2022-06-10 17:36 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        val undo = mActionBarMenu?.findItem(R.id.action_undo)
I could swear I made and pushed those changes 😟