[Kotlin Cleanup] Cardbrowser pt6
ankidroid/Anki-Android pull request #11463
Opened 2022-05-30 17:56 UTC by dorrin-sot

Continued from #11462

2022-05-30 22:24 UTC, Arthur-Milchior requested changes

2022-05-30 22:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -            // update Q & A etc
I'd appreciate if you could keep some comment. 
Admittedly, it may not be the best place to put it. Instead, adding javadoc indicating what the function do may be better

2022-05-30 22:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            .filter { c -> !idToRemove.contains(c.id) }
I'd go with a `filterNot` which would allow to remove the negation from the predicate itself

2022-05-30 22:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            .mapIndexed { i, c -> CardCache(c, i) }
Nice. I know I looked at lines similar to this one and regretted not to be able to use `mapIndexed`. I didn't realize it is possible to filter and then to add index. I like it.

2022-05-30 22:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        val idToPos = getPositionMap(mCards)
I agree this commit is valid.
It's yet again a case where I'd think being more atomic can help the reviewer. Or anyone who want to understand this commit later when looking at our history to investigate a bug.
In this case, the part about `newMCards` is independant from the part above.

The part `mReloadRequired`  could be done separately. By removing it first from the loop, it'll be opvious why your map is valid in the following commit.

2022-05-30 22:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            mReloadRequired = true
I'd even go with
`mReloadRequires = mReloadRequired || cardsIds.contains(reviewerCardId)`

This way, if you are already true, you don't need to run the test

2022-05-30 22:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        get() = mCards.find { c -> c.id == mOldCardId }?.position
I'm amazed. Really love those kind of cleaning, really improve things, thanks a lot!

2022-05-31 20:01 UTC, Arthur-Milchior approved these changes
squash I think

2022-06-01 05:24 UTC, dorrin-sot commented
> Ideally, I'd love rebasing interactively into atomic commits that don't need to be corrected. But if not, at least, you'll need to resolve conflict here

Done :)

2022-06-05 15:17 UTC, Arthur-Milchior commented
You are ending with a merge commit. Please do rebase onto main instead of merging.
Anyway, you know have also conflict to resolve

2022-06-26 20:32 UTC, Arthur-Milchior commented
Really sorry that you were blocked only because I forgot to add a need second approval label

2022-06-27 15:23 UTC, david-allison reviewed
Is this functionality tested via unit tests?

2022-06-28 17:44 UTC, dorrin-sot commented
> Is this functionality tested via unit tests?

Hi Which one?

2022-06-28 23:26 UTC, david-allison commented
Each method. It's a risk to be changing untested code. Otherwise, we're taking on risk for code style improvements, which isn't a good tradeoff.

2022-07-05 15:48 UTC, mikehardy approved these changes
LGTM

2022-07-05 15:56 UTC, merged