Cardbrowser kt cleanup pt11
ankidroid/Anki-Android pull request #11468
Opened 2022-05-30 18:20 UTC by dorrin-sot

Continued from #11467

2022-05-31 21:10 UTC, Arthur-Milchior requested changes

2022-05-31 21:10 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -        val selectedCardIds = selectedCardIds
Still not okay with removing `selectedCardIds` because it's a getter doing work. But okay with changing this so that it's not a getter anymore and it become clear it's a function

2022-05-31 21:10 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            if (lastDeckId?.let { id -> id > 0 } == true) {
If we want to be very Kotlin, I'd even state
`lastDeckId?.takeIf { id -> id > 0 }?.let {id -> intent.putExtra(NoteEditor.EXTRA_DID, lastDeckId)}`

I don't state it's better. Just that I'll have a hard time accepting that `== true` is not code smell

2022-06-01 06:57 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -        val selectedCardIds = selectedCardIds
Is it ok if I make it `selectedCardIds.run{ .. }`? Because I think it being a getter instead of a function makes more sense since it is still _**getting**_ a value(even though it is doing some work to get it) and not doing actual work (ie creating/deleting/editing anything)

2022-06-01 07:30 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            if (lastDeckId?.let { id -> id > 0 } == true) {
I can change it to that too but `== true`/`== false` is also _the_ way to check if a `Boolean?` value is true/false. [source](https://stackoverflow.com/questions/32830904/use-of-boolean-in-if-expression)

2022-06-05 15:13 UTC, Arthur-Milchior approved these changes
Thanks a lot for working with me on improving your PR. I'm happy to be able to merge them now

2022-06-05 15:13 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -        val selectedCardIds = selectedCardIds
I'm fine with it too, thanks

2022-06-05 15:13 UTC, merged