[Kotlin Cleanup] CardBrowser pt3
ankidroid/Anki-Android pull request #11460
Opened 2022-05-30 17:25 UTC by dorrin-sot

Continued From

2022-05-31 11:49 UTC, Arthur-Milchior requested changes

2022-05-31 13:55 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                tag = toIds.map { id -> this.findViewById(id) as View }.toTypedArray()
I can remove the `this`, I only left it there because I thought it would help readability. About the cast to View, even though the type of `findViewById` _should_ be View, I still would get error from IDE saying "Not enough info to infer type"

2022-05-31 15:17 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                tag = toIds.map { id -> this.findViewById(id) as View }.toTypedArray()
Even when you added `map<View>` instead of just `map`?
Because I did check on my computer and once the type of map was explicited, I didn't need to add it inside of the function. So I'm surprised
Full line would be
`tag = toIds.map<View> { id -> this.findViewById(id)}.toTypedArray()`

2022-05-31 15:24 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                tag = toIds.map { id -> this.findViewById(id) as View }.toTypedArray()
Oh I added it like this `.map { id -> findViewById<View>(id)}` is that ok?

2022-05-31 19:01 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                tag = toIds.map { viewId -> findViewById<View>(viewId) }.zipWithNext()[0]
Sorry, I was not clear enough. I was considering something such as #11486
In this case, I think this commit alone is not obviously an improvement. Especially if pairs are used only in tags and then go back to list later

2022-06-01 05:40 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            val card = mCards[position]
Sorry, I changed it back to cards in a new commit. I'll rebase interactive it onto the  same commit

2022-06-01 05:44 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                tag = toIds.map { id -> this.findViewById(id) as View }.toTypedArray()
Done :)

2022-06-01 05:49 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                tag = toIds.map { viewId -> findViewById<View>(viewId) }.zipWithNext()[0]
Oh In that case, do I revert mine back to list so you merge #11486?

2022-06-05 15:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                tag = toIds.map { viewId -> findViewById<View>(viewId) }.zipWithNext()[0]
We can also wait until the other PR is merged and rebase onto it.

In any case, please don't revert. Insteade use interactive rebase to just remove this commit.  Or at least this very change

2022-08-07 22:15 UTC, Arthur-Milchior commented
Can you please rebase to resolve conflict.
Sorry, too many things to review simultaneously, hard to keep track

2022-12-15 07:36 UTC, closed without merging