[Kotlin Cleanup] Cardbrowser pt7
ankidroid/Anki-Android pull request #11464
Opened 2022-05-30 17:58 UTC by dorrin-sot

Continued from #11463

2022-05-30 22:07 UTC, Arthur-Milchior requested changes

2022-05-30 22:07 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            if (!customFont.isNullOrEmpty()) {
This would be the kind of small change I'd love to get in an atomic PR. I'd immediately merge it

2022-05-30 22:07 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                (other != null && javaClass == other.javaClass && id == (other as CardCache).id)
I admit this is valid.
I'd have gone with rewritting in many commit just to be extra certain of each mathematical equivalence step.

```kotlin
            if (this === other) {
                return true
            }
            if (other == null) {
                return false
            }
            return if (javaClass != other.javaClass) {
                false
            } else id == (other as CardCache).id
```
then 
```kotlin
            if (this === other) {
                return true
            }
            if (other == null) {
                return false
            }
            return javaClass == other.javaClass && id == (other as CardCache).id
```
then 
```kotlin
             (this === other) || (other != null && javaClass == other.javaClass && id == (other as CardCache).id)
```

Or at least put this sequence in commit message to help understand someone not used to boolean arithmetic that much

2022-06-01 15:56 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -            val cards = cards
Is it ok if I return `cards` in line `val size = cards.size()` instead of `val size = mCards.size()`?

2022-06-01 16:00 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            if (!customFont.isNullOrEmpty()) {
Done #11494 :)

2022-06-01 23:43 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -            val cards = cards
I don't understand what you means by "return cards". Sorry, this mean I don't know how to answer

2022-06-10 16:20 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -            val cards = cards
like if at line 2091, it's `val size = cards.size()` the getter would be called and no more extra variable

2022-08-16 17:10 UTC, mikehardy commented
sorry, we're all still catching up all over in the repo, not intentional to let PRs go stale

2022-08-16 21:30 UTC, Arthur-Milchior commented
@dorrin-sot can you solve the merge conflict please?

2022-08-17 04:31 UTC, dorrin-sot commented
Hi sorry I've been super busy with internship this past month. I'll get back to these when I'm done

2022-12-11 03:38 UTC, closed without merging