Cardbrowser kt cleanup pt5
ankidroid/Anki-Android pull request #11462
Opened 2022-05-30 17:51 UTC by dorrin-sot

Continued from #11461

2022-05-30 22:44 UTC, Arthur-Milchior requested changes

2022-05-30 22:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        val selectableDecks = ArrayList(
I don't think you actually need to convert to ArrayList. 
I think that changing getChangeDeckDialog type to List would actually work correctly.

2022-05-30 22:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        get() = ArrayList(
You don't need to put the result in an Array list, since the type only guarantees result to be a List

2022-05-30 22:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        val sb = StringBuilder(
this is another case where, as far as I'm the reviewer, I believe I'd be even more helped if the first when was done separately, since it is easy to review and would have confirmed my suspicion that it is unrelated to the tags work below

2022-05-30 22:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        val tagsConcat = selectedTags.joinToString(" or ") { tag -> "\"tag:$tag\"" }
I consider suggesting `""""tag:$tag"""" ` but I must admit it's not really more readable here

2022-05-31 15:23 UTC, Arthur-Milchior reviewed
thanks for taking care into some of my requests.
Sadly, I don't really get the last commit. 

I'd also have just removed the `ArrayList` in the commit touching the ArrayList line. Avoiding doing conversion to ArrayList in a commit to remove it later

2022-05-31 15:23 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        sb.append(
What is this doing in this last commit ? I don't get it?

2022-05-31 15:26 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        sb.append(
It is related to the 3rd review

2022-05-31 15:52 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        sb.append(
done :)

2022-05-31 18:23 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        sb.append(
I'm sorry bu the last commit is still strange.
Not only it is not related, as far as I can tell, to other commit of this PR. But also, why is there so many change in imports. It seems they have nothing to do in this commit. I'd love if you could revert those import changes or keep only exactly what you need in them for code to compile

2022-05-31 19:09 UTC, Arthur-Milchior approved these changes

2022-05-31 19:09 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        sb.append(
Thanks. Now I'm okay with it. But still have to review the first commit just to be certain.

2022-05-31 22:47 UTC, merged