Cardbrowser kt cleanup pt16
ankidroid/Anki-Android pull request #11473
Opened 2022-05-30 18:22 UTC by dorrin-sot

Continued from #11472

2022-05-31 20:36 UTC, Arthur-Milchior requested changes

2022-05-31 20:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                                newInstance(getString(R.string.vague_error), getString(R.string.reposition_card_not_new_error), false)
You can put the return false inside of the apply. I suspect it'd be more readable than checking for non null and having a if

2022-05-31 20:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -import com.ichi2.utils.HashUtil.HashMapInit
Please merge this in the commit where HashMapInit is not useful anymore. It should not be its own commit

2022-06-11 03:39 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                    .find { cId -> col.getCard(cId).queue != Consts.QUEUE_TYPE_NEW }
Why not `any {}`?

2022-06-11 14:58 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                    .find { cId -> col.getCard(cId).queue != Consts.QUEUE_TYPE_NEW }
ah you're right thanks 😄

2022-07-14 04:05 UTC, lukstbit requested changes

2022-07-14 04:05 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        val allTags = col.tags.all()
Not ok, the code isn't the same. The initial code used `ArrayList(col.tags.all())` which creates a **new** list with the items from `col.tags.all()` your new code simply uses col.tags.all(). Might be ok but there's no need for this change.

It's ok to delete the java package and use the ArrayList kotlin alias.

2022-07-14 04:05 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            TagsDialog.DialogType.FILTER_BY_TAG, ArrayList(0), col.tags.all()
The same as above, you probably wanted to delete only the package.

2022-07-14 04:05 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        get() = mDeckSpinnerSelection!!.dropDownDecks
The same, code is not equivalent, keep the ArrayList.

2022-07-14 18:41 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        val allTags = col.tags.all()
I thought the arraylist conversion would be unnecesary since the only usages of `allTags` is:
- in line 1404 and 1391, the `withArguments` method: which accepts List
- in line 1398: the filter method is the same for both list and arraylist
So I thought removing this conversion would save time.

2022-07-14 18:42 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            TagsDialog.DialogType.FILTER_BY_TAG, ArrayList(0), col.tags.all()
also same as above :) the `withArguments` method accepts list so the conversion takes extra time for nothing

2022-07-15 08:39 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        val allTags = col.tags.all()
Ok, I checked it. Here on Github I can't see where it is being used or the types of withArguments().

2022-07-15 08:47 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        get() = mDeckSpinnerSelection!!.dropDownDecks
Looks ok. I don't known why it was written like this, probably some leftover from when it was written in java.

2022-07-15 08:55 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                repositionDialog.setCallbackRunnable { position: Int? -> repositionCardsNoValidation(cardIds.toList(), position) }
This is a bug. You deleted line 1188 in this when case:

`val cardIds = selectedCardIds // cardIds is a List<Long>`

and then in

`repositionDialog.setCallbackRunnable { position: Int? -> repositionCardsNoValidation(cardIds.toList(), position) }`

you used the `cardIds` property from the class which is indeed a LongArray(they don't have the same meaning).

Please keep the line `val cardIds = selectedCardIds`  because it caches the work in the selectedCardIds.

2022-07-15 09:53 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                repositionDialog.setCallbackRunnable { position: Int? -> repositionCardsNoValidation(cardIds.toList(), position) }
Ohh sorry I fixed it

2022-07-15 11:04 UTC, lukstbit approved these changes

2022-07-17 12:17 UTC, david-allison requested changes

2022-07-17 12:17 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                            newInstance(getString(R.string.vague_error), getString(R.string.reposition_card_not_new_error), false)
`SimpleMessageDialog.newInstance`. Also use named arguments

2022-07-17 12:17 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                selectedCardIds.let { cardIds ->
This `let` serves no purpose as `cardIds` is only used once

2022-07-17 12:21 UTC, david-allison requested changes

2022-07-17 12:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                            this@CardBrowser.getString(R.string.reposition_card_dialog_message),
use named arguments

Remove `this@CardBrowser.` and just use `getString`

2022-07-22 16:15 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                            this@CardBrowser.getString(R.string.reposition_card_dialog_message),
I can't because then it would use `IntegerDialog#getString` because of the `apply { ... }` and since the dialog doesn't have a context yet the app would crash

<details><summary>Open log</summary>

```
2022-07-22 20:35:02.554 28866-28866/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 28866
    java.lang.IllegalStateException: Fragment IntegerDialog{85cb77e} (0afbb0ab-25f2-4894-873b-397394e199f2) not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:919)
        at androidx.fragment.app.Fragment.getResources(Fragment.java:983)
        at androidx.fragment.app.Fragment.getString(Fragment.java:1005)
        at com.ichi2.anki.CardBrowser.onOptionsItemSelected(CardBrowser.kt:1197)
        at android.app.Activity.onMenuItemSelected(Activity.java:4269)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:328)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:66)
        at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:221)
        at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
        at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
        at android.widget.AdapterView.performItemClick(AdapterView.java:330)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1187)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3179)
        at android.widget.AbsListView$3.run(AbsListView.java:4097)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

</details>

2022-07-24 17:25 UTC, Arthur-Milchior approved these changes

2022-07-24 17:26 UTC, merged