Cardbrowser kt cleanup pt13
ankidroid/Anki-Android pull request #11470
Opened 2022-05-30 18:21 UTC by dorrin-sot

Continued from #11469

2022-05-31 15:49 UTC, Arthur-Milchior requested changes

2022-05-31 15:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                val isRestorePossible = newPositionOfSelectedCard != CARD_NOT_AVAILABLE
I'm sorry, but actually, `newPositionOfSelectedCard` is a method that do some actual work, so it was nice to save its result.
Admittedly, given the amount of work it takes, I guess it should not be a getter but looks like an actual function

2022-05-31 15:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                val isRestorePossible = newPositionOfSelectedCard != CARD_NOT_AVAILABLE
Maybe
`newPositionOfSelectedCard.takeUnless { it == CARD_NOT_AVAILABLE }?.let { autoScrollTo(it) }` would work if you want it to be small, but strange too. 

I think mostly, here, it's better to just avoid a getter and have a actual method call

2022-05-31 15:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            title = if (hasUnmarked) R.string.card_browser_mark_card else R.string.card_browser_unmark_card
Nice one. 
I'd state that you can replace var by val, since both value of title are unrelated. Then call it `titleSuspend` and `titleMark` for example, same for icon

2022-05-31 15:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
>              val suspendItem = actionBarMenu.findItem(R.id.action_suspend_card)
I believe this is one place when 
```kotlin
actionBarMenu.findItem(R.id.action_suspend_card).run {
  title = browser.getString(title)
  setIcon(icon)
}
```
would be even nicer (for a next commit. Same or different PR)

2022-07-14 05:41 UTC, lukstbit requested changes

2022-07-14 05:41 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                newPositionOfSelectedCard
This doesn't read better than the original code.
The only change the original code needed was to remove the temporary isRestorePossible variable:

```
val newPosition = newPositionOfSelectedCard
if (newPosition != CARD_NOT_AVAILABLE) {
    autoScrollTo(newPosition)
}
```

2022-07-15 04:55 UTC, lukstbit approved these changes

2022-07-30 18:11 UTC, mikehardy commented
@Arthur-Milchior based on your comment, this needs a decision from you to move forward

2022-07-30 22:01 UTC, Arthur-Milchior approved these changes

2022-07-30 22:02 UTC, merged