[Kotlin Cleanup] OverviewStatsBuilderTest
ankidroid/Anki-Android pull request #11476
Opened 2022-05-30 23:04 UTC by oyeraghib

## Purpose / Description
[Kotlin Cleanup] OverviewStatsBuilderTest

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-31 20:08 UTC, Arthur-Milchior requested changes

2022-05-31 20:08 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/stats/OverviewStatsBuilderTest.kt
> +    @Language("HTML")
Can you please explain me what serve the `Language` here? 
As far as I know, the only point is that, in android studio (and potentially other IDEs) you'll get syntax coloring. In this case, you don't get it, at least on my version of android studio. Because the way you wrote it, it means that the function returns HTML string.
Instead, you should put it before val/var which contains HTML. So in this case before `val expected`.

Same below

2022-06-01 17:03 UTC, oyeraghib commented on AnkiDroid/src/test/java/com/ichi2/anki/stats/OverviewStatsBuilderTest.kt
> +    @Language("HTML")
thanks for the correction

2022-06-01 21:39 UTC, Arthur-Milchior requested changes

2022-06-01 21:39 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/stats/OverviewStatsBuilderTest.kt
> +    @Language("HTML")
Please, either explain, or remove this `Language`. Since this language here is useless as far as I understand it

2022-06-02 01:07 UTC, oyeraghib commented on AnkiDroid/src/test/java/com/ichi2/anki/stats/OverviewStatsBuilderTest.kt
> +    @Language("HTML")
I am sorry for not answering it previously. Honestly I didn't knew what is the use of `@Language` annotation but I added because it was mentioned there as a `KotlinCleanup`.

I spent some time to understand what is it exactly and I found out that you mentioned it correctly here. `"As far as I know, the only point is that, in android studio (and potentially other IDEs) you'll get syntax coloring."` This is what Official documentation says as well https://www.jetbrains.com/help/idea/using-language-injections.html#language_annotation

The docs also says that we need to install some `IntelliLang` plugin to use `@Language` annotation. I tried finding it in Android Studio IDE marketplace and found something called as `CLion IntelliLang` which is basically for CLion IDE and not for Android Studio.

So coming to the main point I myself didn't find the exact purpose of `@Language` annotation here, so I have removed it.

2022-06-04 22:05 UTC, oyeraghib commented on AnkiDroid/src/test/java/com/ichi2/anki/stats/OverviewStatsBuilderTest.kt
> +    @Language("HTML")
Thanks for the explanation!! Yeah, I will make sure to ask before writing anything which don't make sense to me. Thanks again.

2022-06-04 22:59 UTC, Arthur-Milchior commented
FYI I'm waiting for your update to review.

2022-06-05 00:12 UTC, Arthur-Milchior reviewed
I fear something went wrong. Only one of the commit remains.
And there still is no `@language("HTML")` before strings containing it

2022-06-05 00:12 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/stats/OverviewStatsBuilderTest.kt
> -@KotlinCleanup("Add @Language to HTML")
Please remove this in the very commit where you add the `Language("html")`

2022-06-05 00:19 UTC, oyeraghib commented
> I fear something went wrong. Only one of the commit remains. And there still is no `@language("HTML")` before strings containing it

Actually I removed those commits. And made a new commit with just `IDE` lint changes and forced push it.

Reason was that I thought it would add to wrong **commit history** where I first added `@Language("HTML")`  in one of the commits and then removed it in the next commit.

2022-06-05 00:36 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/stats/OverviewStatsBuilderTest.kt
> -@KotlinCleanup("Add @Language to HTML")
I'm fine with just merging a commit with just IDE lint and not any `@Language` change. However, in this case, please keep this KotlinCleanup in the commit.

2022-06-05 00:42 UTC, oyeraghib commented on AnkiDroid/src/test/java/com/ichi2/anki/stats/OverviewStatsBuilderTest.kt
> -@KotlinCleanup("Add @Language to HTML")
sure I just added that!

2022-06-05 01:13 UTC, Arthur-Milchior approved these changes

2022-06-05 01:13 UTC, merged