Implemented Service to store Deck Meta Data
ankidroid/Anki-Android pull request #11487
Opened 2022-05-31 19:16 UTC by prateek-singh-3212

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-01 05:49 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckMetaDataPreference.kt
> +        context.getSharedPreferences("DeckMetaData", Context.MODE_PRIVATE)
you using sharedpreferences for storing all the data of only due deck data for further notifications, am I right or missing anything?

2022-06-01 05:49 UTC, Akshay0701 commented on AnkiDroid/build.gradle
> +    implementation 'com.google.code.gson:gson:2.9.0'
maybe giving little description on why GSON

2022-06-01 12:00 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckMetaDataPreference.kt
> +class DeckMetaDataPreference(context: Context) {
Could you comment explaining what this does, and why?

2022-06-01 12:00 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/services/DeckMetaDataService.kt
> +class DeckMetaDataService : Service() {
Could you comment what this class does, any why?

2022-06-02 17:09 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckMetaDataPreference.kt
> +        context.getSharedPreferences("DeckMetaData", Context.MODE_PRIVATE)
Yes, I am using shared preference to store deck meta data

2022-06-02 17:31 UTC, prateek-singh-3212 commented on AnkiDroid/build.gradle
> +    implementation 'com.google.code.gson:gson:2.9.0'
I have an option to us JsonObject that we are using in our code. But with the help of Json Object  I have to itrate over all the decks and store to Json Object. eg: [stackoverflow](https://stackoverflow.com/a/49359395). This approch will take more time if their is more decks.

2022-06-02 17:31 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckMetaDataPreference.kt
> +        sharedPreferences.edit()
Done

2022-06-02 17:47 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/services/DeckMetaDataService.kt
> +class DeckMetaDataService : Service() {
This class is responsible to Collect all the metadata and store it share preference. So I can say that this is used to refersh or meta data. Whenever this service is called then I will collect the new data of decks.

2022-06-02 17:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckMetaDataPreference.kt
> +class DeckMetaDataPreference(context: Context) {
Does this need to be a service, or can it be a responsibility of our existing `NotificationService`? Or run under the WorkManager?

2022-06-02 17:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/services/DeckMetaDataService.kt
> +class DeckMetaDataService : Service() {
Could you move this comment to the code, for future documentation?

2022-06-02 17:53 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/services/DeckMetaDataService.kt
> +class DeckMetaDataService : Service() {
Yup!!

2022-06-02 18:07 UTC, prateek-singh-3212 commented
Please check this video for clarification. (for now I am starting this service when app starts and when `onDestroy()` of activity is called. But I want to change this in future.)

https://user-images.githubusercontent.com/76490368/171696647-41ba5eab-af7e-4e01-90ba-f52c55906e32.mp4


Snip of deck meta data [Shared Preference]...

![Screenshot 2022-06-02 224113](https://user-images.githubusercontent.com/76490368/171686117-bd566a03-9aee-4226-90b2-e5cda7103d69.jpg)

creating json with this model class ⬇️ 
https://github.com/prateek-singh-3212/Anki-Android/blob/257bb949313aaca19c954100c90e185631996fe8/AnkiDroid/src/main/java/com/ichi2/anki/services/DeckMetaDataService.kt#L113

Json body...
```
{
  "deckName": "dtc",
  "did": 1621523610764,
  "eta": 0,
  "lrn": 0,
  "new": 0,
  "rev": 2
}
```

2022-06-02 18:16 UTC, david-allison commented on AnkiDroid/src/main/AndroidManifest.xml
> +        <service
Intuitively, I believe that `WorkManager` would be a better fit, what are the downsides of this? Android has a lot of issues with both Foreground and Background services in general due to energy constraints.

2022-06-03 00:22 UTC, david-allison commented
Tests are falling

2022-06-03 09:10 UTC, prateek-singh-3212 commented
@david-allison Fixed the Issue. Kindly check now.

2022-06-03 23:18 UTC, david-allison commented on AnkiDroid/build.gradle
> +    implementation 'com.google.code.gson:gson:2.9.0'
I don't think we should use gson if we can use our existing mechanism

2022-06-04 17:08 UTC, prateek-singh-3212 commented on AnkiDroid/build.gradle
> +    implementation 'com.google.code.gson:gson:2.9.0'
Done Changes. Kindly see this in Commit `Improved Performance and Added Documentation`

2022-06-04 17:08 UTC, Akshay0701 commented
conflict is still there

2022-06-04 17:15 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/AndroidManifest.xml
> +        <!-- Disabled the Initialization at startup. Using custom work manager Initialization-->
The tests are failing earlier because Work Manager is not inialized properly. The fix of this is to implement the custom Work Manager 
Check: https://developer.android.com/topic/libraries/architecture/workmanager/advanced/custom-configuration

Line in current code: 
1. https://github.com/prateek-singh-3212/Anki-Android/blob/8ebe6ba8740ff56fa2963f503676aa53c7486367/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java#L71

2. https://github.com/prateek-singh-3212/Anki-Android/blob/8ebe6ba8740ff56fa2963f503676aa53c7486367/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java#L449

2022-06-04 17:22 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        Timber.tag("META").e("Setting up deck meta data worker...");
I used the tag `META` and `e` to debug easily & To make review prosses easy. By running in localmachine and using tag "META"

2022-06-04 17:26 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/DeckMetaDataWorker.kt
> +        const val DECK_META_WORKER = "DeckMetaData"
I used this in AnkiDroidApp class. Created here because this tag is exclusive for DeckMetaWorker.

see: https://github.com/prateek-singh-3212/Anki-Android/blob/8ebe6ba8740ff56fa2963f503676aa53c7486367/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java#L434

2022-06-04 17:29 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/DeckMetaDataWorker.kt
> +        deckList.forEach {
DeckDueTreeNode Might be null. Called in line 44

2022-06-04 17:31 UTC, david-allison commented on AnkiDroid/src/main/AndroidManifest.xml
> +        <!-- Disabled the Initialization at startup. Using custom work manager Initialization-->
The docs state that this is a performance optimisation, is that the case? Otherwise, why wouldn't it be initialised properly by the default setup?

2022-06-04 17:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        Timber.tag("META").e("Setting up deck meta data worker...");
Our logs should be consistent with the rest of the application

2022-06-04 17:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/DeckMetaDataWorker.kt
> +        deckList.forEach {
Why? I believe the signature is incorrect in `AbstractSched`

2022-06-04 17:42 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/DeckMetaDataWorker.kt
> +        deckList.forEach {
Yes, You are correct It is written wrong in `AbstractSched`
See: https://github.com/ankidroid/Anki-Android/blob/f4dd885a99f6c92b233f9f7a483056d3a086592a/AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java#L531

2022-06-04 17:44 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/AndroidManifest.xml
> +        <!-- Disabled the Initialization at startup. Using custom work manager Initialization-->
> is that the case?
Yes
> why wouldn't it be initialised properly by the default setup?
I was unable to find the reason. 😞

2022-06-04 17:45 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        Timber.tag("META").e("Setting up deck meta data worker...");
Okay, I will fix this before merging. Sounds Good?

2022-06-04 17:47 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckMetaDataPreference.kt
> +            .putString(key, value)
Done 👍🏽

2022-06-04 18:05 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/DeckMetaDataWorker.kt
> +        val col = colHelper.getCol(context)
Used `getColSafe`. It will handle this case now.

2022-06-04 18:09 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/DeckMetaDataWorker.kt
> +    private lateinit var colHelper: CollectionHelper
No, Used this as singleton now.

2022-06-04 18:28 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +public class AnkiDroidApp extends Application implements androidx.work.Configuration.Provider {
Yes, It need to be in Application & I was unble to find the way to extract it in seprate in new class. If you know then please let me know.

2022-06-04 18:52 UTC, prateek-singh-3212 commented
@david-allison I was unable to found why tests are failing. Could you please help?

2022-06-04 20:16 UTC, mikehardy commented on AnkiDroid/build.gradle
> +    implementation "androidx.work:work-runtime-ktx:2.7.1"
we don't need the comment and I expect this to be up with the rest of the implementation dependencies please

2022-06-04 20:18 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        Timber.tag("META").e("Setting up deck meta data worker...");
just fix it now and use a grep in logcat for your classname - class names are tagged in development I think, and multiple tags may be OR'd together with egrep, should be adequate? it's how I work...

2022-06-04 20:18 UTC, prateek-singh-3212 commented on AnkiDroid/build.gradle
> +    implementation "androidx.work:work-runtime-ktx:2.7.1"
I will do that... 👍🏽

2022-06-04 20:19 UTC, david-allison commented on AnkiDroid/src/main/AndroidManifest.xml
> +        <!-- Disabled the Initialization at startup. Using custom work manager Initialization-->
Okay, that's fine

2022-06-04 20:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +public class AnkiDroidApp extends Application implements androidx.work.Configuration.Provider {
Okay, works for me

2022-06-04 20:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/DeckMetaDataWorker.kt
> +        deckList.forEach {
Can we fix it instead of working around it?

2022-06-04 20:24 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/DeckMetaDataWorker.kt
> +            storeInPreference(data)
I tried with almost 700 decks (which includes the subdecks) and it too aroung to 10 sec to store the data. But fetching all the data in one go takes around 2 sec.

2022-06-04 20:24 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/DeckMetaDataWorker.kt
> +            storeInPreference(data)
I actually think it will be fine until maybe 100,000 key/val pairs. We have to assume that there may be someone with a pathological case like a million decks so it should at least never break even if it does slow down in terrible cases, I think if performance is good up to 1000 decks that's pretty solid though, then just not breaking even if there are 1,000,000 just to test. Will it run out of memory?

It appears to be a file loaded into a Hashmap on first read and kept in memory until application close, so how much memory *exactly* does one deck take? doing a quick profile at for example 10,000 decks and 20,000 decks should allow us to determine a per-deck memory usage to make sure it's okay.

For performance it is probably depending on operation. I think specifying the operation is important and volume of operations. For instance using apply to save is async but if you call it enough time with a large enough set you may saturate storage. Calling commit would be terrible. Reading it the first time, as long as it is asynchronous (it should be?) should not matter much to a user

2022-06-04 20:25 UTC, mikehardy commented
What the heck? Nothing but this over and over and over

```
AbstractFlashcardViewerKeyboardInputTest > spaceDoesNotShowAnswerIfTextFieldFocused FAILED
    java.lang.UnsatisfiedLinkError: 'long net.ankiweb.rsdroid.NativeMethods.openBackend(byte[])'
        at net.ankiweb.rsdroid.NativeMethods.openBackend(Native Method)
        at net.ankiweb.rsdroid.BackendV1Impl.ensureBackend(BackendV1Impl.java:91)
        at net.ankiweb.rsdroid.BackendV1Impl.openAnkiDroidCollection(BackendV1Impl.java:128)
        at net.ankiweb.rsdroid.BackendMutex.openAnkiDroidCollection(BackendMutex.java:977)
        at net.ankiweb.rsdroid.BackendUtils.openAnkiDroidCollection(BackendUtils.java:29)
        at net.ankiweb.rsdroid.database.RustV11SupportSQLiteOpenHelper.createRustSupportSQLiteDatabase(RustV11SupportSQLiteOpenHelper.java:45)
        at net.ankiweb.rsdroid.database.RustSupportSQLiteOpenHelper.getWritableDatabase(RustSupportSQLiteOpenHelper.java:69)
        at com.ichi2.libanki.DB.<init>(DB.java:80)
        at com.ichi2.libanki.backend.RustDroidBackend.openCollectionDatabase(RustDroidBackend.kt:42)
        at com.ichi2.libanki.Storage.Collection(Storage.java:97)
        at com.ichi2.anki.CollectionHelper.openCollection(CollectionHelper.java:138)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:157)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:128)
        at com.ichi2.anki.CollectionHelper.getTimeSafe(CollectionHelper.java:190)
        at com.ichi2.anki.worker.DeckMetaDataWorker$Companion.setupNewWorker(DeckMetaDataWorker.kt:[112](https://github.com/ankidroid/Anki-Android/runs/6739991733?check_suite_focus=true#step:8:113))
        at com.ichi2.anki.AnkiDroidApp.setupDeckMetaDataWorker(AnkiDroidApp.java:443)
        at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:236)
        at org.robolectric.android.internal.AndroidTestEnvironment.lambda$installAndCreateApplication$2(AndroidTestEnvironment.java:350)
        at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:86)
        at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:350)
        at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$0(AndroidTestEnvironment.java:229)
        at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
        at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$1(AndroidTestEnvironment.java:226)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
        at org.robolectric.RuntimeEnvironment.getApplication(RuntimeEnvironment.java:71)
        at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:194)
        at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:325)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:265)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1[128](https://github.com/ankidroid/Anki-Android/runs/6739991733?check_suite_focus=true#step:8:129))
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Does the ankidroid backend use a provider also, and this is disrupting it?

2022-06-04 20:27 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/DeckMetaDataWorker.kt
> +        deckList.forEach {
Shall I create new pr for this. Or new commit will be fine?

2022-06-05 08:48 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/DeckMetaDataWorker.kt
> +            storeInPreference(data)
> Will it run out of memory?
Yes, I tried with approximatly 10500 and it throwed `OutOfMemoryError` and application is also lagging although WorkManager runs asyncronously.

> Failed to allocate a 24 byte allocation with 5200200 free bytes and 5078KB until OOM, target footprint 536870912, growth limit 536870912; failed due to fragmentation (largest possible contiguous allocation 169082880 bytes)
        at java.util.HashMap.newNode(HashMap.java:1746)
        at java.util.HashMap.putVal(HashMap.java:641)
        at java.util.HashMap.putMapEntries(HashMap.java:514)
        at java.util.HashMap.<init>(HashMap.java:489)
        at android.app.SharedPreferencesImpl$EditorImpl.commitToMemory(SharedPreferencesImpl.java:531)
        at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:478)
        at com.ichi2.anki.DeckMetaDataPreference.setMetaData(DeckMetaDataPreference.kt:182)
        at com.ichi2.anki.worker.DeckMetaDataWorker.storeInPreference(DeckMetaDataWorker.kt:218)
        at com.ichi2.anki.worker.DeckMetaDataWorker.doWork(DeckMetaDataWorker.kt:145)
        at androidx.work.Worker$1.run(Worker.java:86)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
        
        
> memory exactly does one deck take?

It takes around 2.5 MB to store the XML File.

2022-06-05 08:58 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        Timber.tag("META").e("Setting up deck meta data worker...");
Done.... 👍🏽

2022-06-05 09:32 UTC, prateek-singh-3212 commented
I was my mistake. I was opening collection in companion object i.e calling it in static function that's why It throwed the error. Fixed it now.

2022-06-05 11:49 UTC, david-allison commented
> Does the ankidroid backend use a provider also, and this is disrupting it?

No

Initialization is:

https://github.com/ankidroid/Anki-Android/blob/599c50575148ed8259cf8eda7fd858244f773a62/AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackendFactory.kt#L45-L50

https://github.com/ankidroid/Anki-Android-Backend/blob/0c095aa8eb6f6b72bd88661d44fdf9a630f34f45/rsdroid/src/main/java/net/ankiweb/rsdroid/BackendV11Factory.java#L29-L33


My first place to look would be to see if we're initialising `anki-android-backend-testing` library correctly:

https://github.com/ankidroid/Anki-Android/blob/8741aae7215366ed95ad466474906492e77e88c6/AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt#L92-L120

----

I'd also say: we're adding a dependency on a valid collection inside AnkiDroidApp. 

We need to handle if a collection is corrupt etc...

2022-06-05 11:52 UTC, david-allison commented
@Arthur-Milchior, this is probably the time to decouple `Time` from the collection

2022-06-05 18:30 UTC, Arthur-Milchior commented
> @Arthur-Milchior, this is probably the time to decouple `Time` from the collection

Done : #11546

By the way, I trust you it was necessary. I have not looked in details why it was blocking here

2022-06-05 21:56 UTC, Arthur-Milchior reviewed
I must admit I'm quite lost.
This is a huge change. Really impressive. But since I don't know this part of the code, it's also hard to follow. Also, it's architectural change, introducing new tools that I plainly admit I'm not used too.
So I'd appreciate a lot if you could do two things.

First, add a lot more documentation, each commit message should explain in English what is being done and why. We don't always require it, recently we had lot of migration+cleanup, they are easy to follow, don't require to learn anything. Here, I would love if commit message + code documentation ensure that any reader looking at git blame, trying to understand why things were done, would get enough with it. A good rule of thumb is that if someone asked you a question about your design, the answer should also be somewhere in the commit itself, so that someone reading the code don't have to try to find the PR to see whether it was discussed or rediscover the answer by themselves. 
As example, it would be "we store decks in memory, so we assume the number of deck is reasonnable. For 20k decks, it may well crash" and "using GSon because ...."
Speaking of GSON, I think we still have issues open for migrating JSON to other library. 
Sadly, nobody finished the work. And it took so much conflict it should probably be started from scratch

Another request, if possible, would be to have smaller commits. It's hard for me to really understand and know whether it is possible. But seing the number of part of code that are touched, I was hoping maybe you could find some place of the code you could modify, where the modification have sense by itself, can be explained in the commit message, so that I can hope to review and get an opinion without having to read hundred of lines and understand everything at once

2022-06-05 21:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/AndroidManifest.xml
> -        <service
I don't get it. Why do you add it in commit 1 and remove it in commit two?
I have seen we asked you to remove it, but then, why don't you just remove it from the first commit and force push?

More generally my question really is: are those three atomic commits, or is this a single change that is here in three commits because you had to update it twice? I assume you already know we generally force push on branch and just try to ensure to have a bunch of atomic commits in our history

2022-06-05 22:03 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/AndroidManifest.xml
> -        <service
I implemented the same thing by two methods
1. Service
2. WorkManager

I just kept first case intentionaaly because I was testing workmanager and I case things does'nt work as planned then I can easily switch back. But I think WorkManager is doing the fantastic job so I will remove the 1st commit.

No we will use WorkManager (so Please review from second commit)

2022-06-05 22:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/AndroidManifest.xml
> -        <service
In similar case in the future, may I suggest using two branchs? You can push the one you are not currently considering on github, you can link to it.

Should I also review the third commit?
I prefer to wait until you remove first commit, because otherwise, reviewing second commit alone, it's hard to really know what part I should care about and which one correspond to deletion of first commit work. 
Plus, ideally, I'll wait until you answer the bigger remark above if you can, so that it becomes easier

2022-06-06 09:35 UTC, prateek-singh-3212 commented
@Arthur-Milchior Deleted the unessary commit and Added the documentation. Please check now.

2022-06-06 09:39 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/AndroidManifest.xml
> -        <service
Done.... 👍🏽  Please check now

2022-06-07 08:40 UTC, Akshay0701 reviewed
Hey pratik, you did a major changes, its better to included things you did in descriptions of PR, or some checklist.

2022-06-07 08:40 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckMetaDatastore.kt
> +            jsonObject.put("eta", value.eta)
Optional: i see you use this same json attributes for setting and getting, i think it would good to create sperate model class for these, for example [model](https://github.com/Akshay0701/PingoAppSocialApp/blob/master/app/src/main/java/com/example/pingoapp/models/ModelChat.java)

2022-06-07 08:40 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/DeckMetaDataWorker.kt
> +//            val time = CollectionHelper.getInstance().getTimeSafe(context).currentDate
if it's not required anymore then how about removing it?

2022-06-07 15:22 UTC, prateek-singh-3212 commented
@Arthur-Milchior @david-allison Dine the atomic commits and added the documentation. I think now it will be easier for you to review

2022-06-07 16:10 UTC, david-allison requested changes
As mentioned in Discord, I'm still not sure if we need this persistence layer for what we're trying to accomplish, and I'd like a justification for the additional complexity that this adds.

Code seems reasonable, and I'm generally happy here. Just needs some more docs

2022-06-07 16:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckMetaDatastore.kt
> +        return listMeta
```suggestion
        return readAllKeys().mapNotNull { getMetaData(it) }
```

2022-06-07 16:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckMetaDatastore.kt
> +        }
```suggestion
        val jsonData = context.deckMetaDataStore.data.map { metaData ->
            metaData[key] as String
        }.firstOrNull() ?: return null

        Timber.d(jsonData)

        return DeckMetaDataModel.fromJson(jsonData)
```

2022-06-07 16:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckMetaDatastore.kt
> +            return INSTANCE ?: DeckMetaDatastore(context)
INSTANCE is never set

2022-06-07 16:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/model/DeckMetaDataModel.kt
> +        } catch (e: JSONException) {
This shouldn't be possible, let the exception be raised if this is the case.

2022-06-07 16:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/DeckMetaDataWorker.kt
> +            val rev = it.revCount
style: I'd switch these: define `Counts()` here, and use `counts.new|lr|n|rev` in the constructor

2022-06-07 19:10 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +     * We are using custom work manager because UNIT TESTS are failing.
I  did all the things correctly as mentioned in the documentation and I did not faced any issue while testing locally but the Unit test failed and looked a little bit more and found this. https://issuetracker.google.com/issues/138465476. So the simple fix for this is to use custom initalization.

2022-06-07 19:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +     * We are using custom work manager because UNIT TESTS are failing.
Can we document this and reopen the issue with a reproducible test case?

2022-06-07 19:22 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +     * We are using custom work manager because UNIT TESTS are failing.
Yeah - "working locally" + "failing in CI" is a bad smell, something's wrong, leaving it is not a good idea. 
I'd love to see the full stack trace.
That issue was closed as non-reproducible and I have seen work manager work just fine including in github CI environments through my work on notifee.app / https://github.com/invertase/notifee - it really should init okay

2022-06-19 08:15 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckMetaDatastore.kt
> +            return INSTANCE ?: DeckMetaDatastore(context)
Fixed

2022-06-19 08:22 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckMetaDatastore.kt
> +        return listMeta
Fixed... 👍🏽

2022-06-19 08:26 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckMetaDatastore.kt
> + * WARNING: Their should be one and only instance of this class more specifically **preferencesDataStore**
This class is singelton. Improved the documentation

2022-06-19 14:41 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/DeckMetaDataWorker.kt
> +            val rev = it.revCount
Done 👍🏽

2022-06-19 14:42 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/DeckMetaDataModel.kt
> +        } catch (e: JSONException) {
Done 👍🏽

2022-06-19 14:46 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/DeckMetaDataWorker.kt
> +        if (collection.getColSafe(it) != null) {
Fixed

2022-06-19 14:47 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/DeckMetaDataModel.kt
> +    private val emptyData = """
Used this to send empty data if exception is raised while parsing json. But removed this now

2022-06-19 16:03 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/DeckMetaDataWorker.kt
> +            storeInPreference(data)
Resolved this by using preference-datastore

2022-06-23 07:18 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +     * We are using custom work manager because UNIT TESTS are failing.
@mikehardy ran the tests now locally and now it is failing. And I is also failing in this issue. Fix of this is to use custom initalization. I will document this is in issue. 
Tests Failing: https://github.com/ankidroid/Anki-Android/runs/7017952570?check_suite_focus=true

2022-06-23 18:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +     * We are using custom work manager because UNIT TESTS are failing.
@prateek-singh-3212 Do you have a commit ref we can check out?

2022-06-23 18:33 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +     * We are using custom work manager because UNIT TESTS are failing.
No, Their is no commit present right now which can reproduce the issue. Shall I create the commit?

2022-06-23 23:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +     * We are using custom work manager because UNIT TESTS are failing.
Yes, once we have a commit reference, we can investigate.

2022-06-24 08:22 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +     * We are using custom work manager because UNIT TESTS are failing.
Done. Checkout https://github.com/prateek-singh-3212/Anki-Android/tree/Sync_Deck_Meta_Data_Test

2022-06-25 18:10 UTC, mikehardy commented
Is there some place that is tracking this discussion on whether a persistence layer is needed or not?

A change this size with questions on *design* and *need* needs to have some conclusive discussion on whether we really need it or not. GSoC has deadlines so even though we are not deadline oriented and all of us are having various personal reasons for low availability right now :weary: it seems like some sort of synchronous discussion needs to happen? Maybe on the discord channel?

Or if a solid defense for this has already been made and accepted, it should be documented so that all future readers (like myself) can say "okay, it seems iffy but everyone had the discussion and we did agree it was justified"

2022-06-25 18:28 UTC, prateek-singh-3212 commented
@mikehardy I understood your point. This is the drastic change in the AnkiDroid. I designed the complete flow of this mechanism. on the basis of concluding the following disscussion. 
https://github.com/ankidroid/Anki-Android/issues/6476
https://github.com/ankidroid/Anki-Android/issues/8114
https://github.com/ankidroid/Anki-Android/issues/4944 (UI is inspired from your disscusion with timrae)

Yes, I too feel that we all needs to be on same page. I would like to propose the of Idea of setting up meet to discuss this issue.

2022-06-25 18:33 UTC, mikehardy commented
for the record I think it may be justified - even though it is a big change, I just want to make sure we all agree so there are no lingering doubts. I don't like lingering doubts - I prefer to be decisive even if we all discover it is a mistake later (which is okay, it happens). I'm sure you saw I mentioned it on discord. Hopefully we can settle it quickly so you are not delayed

2022-06-25 18:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +     * We are using custom work manager because UNIT TESTS are failing.
Most of these errors can be fixed with `WorkManagerTestInitHelper`

```
/*
 *  Copyright (c) 2022 David Allison <davidallisongithub@gmail.com>
 *
 *  This program is free software; you can redistribute it and/or modify it under
 *  the terms of the GNU General Public License as published by the Free Software
 *  Foundation; either version 3 of the License, or (at your option) any later
 *  version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT ANY
 *  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 *  PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with
 *  this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.ichi2.anki

import androidx.work.testing.WorkManagerTestInitHelper
import org.robolectric.TestLifecycleApplication
import java.lang.reflect.Method

class TestAnkiDroidApp : AnkiDroidApp(), TestLifecycleApplication {
    override fun onCreate() {
        WorkManagerTestInitHelper.initializeTestWorkManager(this)
        super.onCreate()
    }
}
```

2022-06-25 19:23 UTC, prateek-singh-3212 commented
@david-allison  @Akshay0701  @mikehardy  @Arthur-Milchior 

**What is the issue?**
The complete issue is documented in #6476. The main issue is that Current notification system is coupled with widget and notification is only triggered when user use widget. 
Secondly, Notification is triggered when user is using the app. How? Whenever deck review completes the deck the widget data is updated Hence Notification is shown (Because it is tightly coupled).

**Solution of this issue**
![image](https://user-images.githubusercontent.com/76490368/175786716-9eb5c469-5b45-405a-943b-dbdd98d1468f.png)

Create a class which is used to store the deck meta data. But does this solves the issue? Yes, because 
1. it removes the calls which updates the data on onStop or onPause which in not optimized at all.
2. It removes the call which opens the collection after regular interval of time just to update the card count. for eg. If notification services opens the collection and after 5  min Widget update service opens the collection to get the same total cards count. (Open collection is expensive task). In future if other serivce want to access the data then it can use meta data persistant layer

**Why we need to store all the decks detail?**
Why cant we store the Total card due count? This is because we have to show the individual deck notification to user. In future we will provide the feature to show notification of particular deck at the given time if due card is above (for eg. 10). If we did'nt store individual deck details then we encounter problem metioned in poin 2 above.

**Current Solution Explanation**
This PR uses new librarys:
1. WorkManager: used after concluding (https://github.com/ankidroid/Anki-Android/pull/11487#discussion_r888258029)
2. Datastore Preference: Used because Shared Preference is causing the OOM Exception. See: https://discord.com/channels/368267295601983490/977324896352862258/982979582804246548

**Class Structure**
`DeckMetaWorker`
`DeckMetaDatastore`

**Future Plan**
I this PR mereges then I will use the work manager chaning to do:
1. Update Widget
2. Send Notification

How??? 
After 30 min Deck Meta Data Updates ------------> Checks the is there any notification that need to be send?-------------------->Updates the widget.

More on Chaining: https://developer.android.com/topic/libraries/architecture/workmanager/how-to/chain-work

**Above Solution Solves the 2 isses which I addressed ☺️**

2022-06-25 19:41 UTC, mikehardy commented
Okay, so what I understand is:
1- people want notifications at specific times, which implies waking up and working maybe when the app is not running, and WorkManager is the best choice for that by far, so that justifies the WorkManager stuff
2- people want per-deck notification settings which means we need to store and access an amount of data that is O(n) where n is number of decks and will cause OOMs so we either need to store it in the collection or we need some other place to store it

I understand from 2 above that *if* we are not storing it in the collection then [datastore-preferences appears to be a good choice](https://android-developers.googleblog.com/2022/03/jetpack-datastore-wrap-up.html) for this probably small but maybe large set of data that is nevertheless pretty simple (so SharedPreferences won't work but Room is more than we need)

So just one question then: could we / should we store this in the collection? I think it's *possible* to do so but right now deck conf is read in / written out as one big chunk and I think it would have all the problems SharedPreferences has with OOM risk and performance. In newer Anki rust code I think it's possible to do per-deck metadata but then we'd block a GSoC project on that which is not acceptable.

So if I understand things correctly, I believe the dependencies are justified by the requirements and the specific dependencies are the correct choices. My opinion

2022-06-26 23:57 UTC, Arthur-Milchior commented
> Solution of this issue image

I think the image is missing

2022-06-27 00:31 UTC, Arthur-Milchior commented
Regarding storing data in the collection, as suggested by Mike. Wouldn't there be a problem with the fact that it would require to open the actual collection? Potentially a big file, that must be entirely read to be used by sqlite. Plus it probably would require loading at least a big part of our codebase in memory. If there is a way to ensure that we can avoid actually opening the database and actually opening the CollectionHelper method to open the actual collection, I believe that it's an actual win.
Or am I missing something here?

2022-06-27 02:05 UTC, mikehardy commented
> open the actual collection? Potentially a big file, that must be entirely read to be used by sqlite

That's not how the database read works with sqlite - you can have a 2GB sqlite db and open it and it doesn't map the whole thing in to RAM. It will only read the data it needs to read. I think collection open is actually pretty efficient too, I'm not worried about that. I do worry that this O(n) storage requirement would be in one single JSON object in the collection though and *that* (even if sqlite is efficient) would be a burden

2022-06-28 13:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +     * We are using custom work manager because UNIT TESTS are failing.
I'm fine for this code to be in, as there will be a significant amount of effort to fix about 14 failing tests, which I don't have time for currently. As long as there's a TODO that this can be fixed with the above code, I'm happy.

2022-06-28 14:45 UTC, prateek-singh-3212 commented
Yes, Sorry droped some changes while rebasing. Fixed Now 🙌

2022-06-28 15:02 UTC, david-allison requested changes
Architectural question about one "unit of work" per time, rather than per deck.

2022-06-28 15:02 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +
seems to be removed

2022-06-28 15:07 UTC, prateek-singh-3212 commented
@david-allison I think thir is SDK error while running android emulator test. Can you re-run it

2022-06-28 15:07 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +
Thanks, I will do it.

2022-06-28 15:10 UTC, david-allison commented
> @david-allison I think thir is SDK error while running android emulator test. Can you re-run it

done

2022-06-28 15:11 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationManagerModel.kt
> +data class NotificationManagerModel(
This isn't storing the data which was discussed in Discord.

Could it be split out into a separate PR so we can get the WorkManager work in?

2022-06-29 20:17 UTC, prateek-singh-3212 commented
> Architectural question about one "unit of work" per time, rather than per deck.

@ankidroid/gsoc-mentor Please take a look.

Gave a thought to this and designed the algo
**ALGO FOR DECK NOTIFICATION**
Input: Map<time, List<DeckId>>

We store the the time and list of decks whose notification needs to be send on that time.
Calculation of time is as follows we round to minutes to it nearest `%10` so decks with time 11:56 11:58 is counted in 12:00

Working of algo:
1. Takes the input time and does the round off as explained above and adds the deckid in the respective timing.
2. If (new decklist contains only 1 entry then [Which we added up] ) Then Run the work Manager and calculate the new timing to restart the work manager.
3. else (new decklist contains more than 1 entry then [Which we added up]) then do noting i.e don't run the workmanager.

Cancelation of alarm
1. Takes the input time and does the round off as explained above.
2. if (list of decks contains only 1 deck) then delete the time from map run the worker and calaculate the next time of worker to start. 
5. else (list of decks contains more then 1 deck) Simply pop out that deck id from list.

**ALGO FOR ALL DECK NOTIFICATION**
All deck notification will work in the syncronization with above algo and addintion to this If Thier is no scheduled notification in next 1 hour then also work manager will run after 1 hour and check the all deck status.

2022-06-29 20:20 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationManagerModel.kt
> +data class NotificationManagerModel(
> This isn't storing the data which was discussed in Discord.

@david-allison 
Yaa, I think have to add this if we want remove our dependency from dconf reminder. It will be more helpful when I implement the UI of Customizing deck notification.

2022-06-29 20:20 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationManagerModel.kt
> +data class NotificationManagerModel(
> Could it be split out into a separate PR so we can get the WorkManager work in?

I will do in next time

2022-07-02 10:23 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +                val did = inputData.getLong(DECK_ID, Long.MIN_VALUE)
Done. Implemented new algo

2022-07-03 21:03 UTC, david-allison requested changes
Thanks! looking MUCH better.

My main question: in your design, is `TreeMap<String, List<did>>` going to be a source of truth, or should it be regenerated from the user preferences? It's a concern that the system runs without any input from the current user's preferences because the two can easily get out of sync.

My previous review comments weren't taken into account

I don't think this handles Daylight Savings correctly

2022-07-03 21:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        totalDueCount.count()
I'd extract this to a method on `SchedulerService`. 

(no action needed): Realistically all this does is `val sum = deckList.sum { it.lrnCount + it.newCount + it.revCount }`

2022-07-03 21:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
>          mNotifications.observeForever(unused -> NotificationService.triggerNotificationFor(this));
Can we add a TODO to remove this once the `Helper` is fully operational?

2022-07-04 08:13 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +    private val mCollection: (context: Context) -> Collection? = {
Fixed 👍🏽

2022-07-04 08:22 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val title = "Don't forget to study today"
Done 👍🏽

2022-07-04 08:24 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +
Fixed 👍🏽

2022-07-04 08:26 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/AndroidManifest.xml
> +<!--        Using custom work manager initialization-->
@david-allison I think we should use it as of now. I will fix this by writing the tests whenever this PR mergs.

2022-07-04 08:42 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +    private fun fireDeckNotification(did: DeckDueTreeNode) {
Done 👍🏽

2022-07-04 08:54 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +import androidx.work.ExistingPeriodicWorkPolicy;
Removed 👍🏽

2022-07-04 08:59 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
>          mNotifications.observeForever(unused -> NotificationService.triggerNotificationFor(this));
Add TODO ✅

2022-07-04 09:02 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
>          mNotifications.observeForever(unused -> NotificationService.triggerNotificationFor(this));
Extra TODO for boot service also

2022-07-04 11:57 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +        }
Fixed. Now it is THREAD SAFE.
Reference: https://stackoverflow.com/questions/40398072/singleton-with-parameter-in-kotlin

2022-07-04 12:52 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +    override suspend fun doWork(): Result {
I will do it in the upcomming commits. Created a TODO in the `fire deck notification` function

2022-07-04 12:56 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +            fireDeckNotification(deckList.first { it.did == deckId })
I will execute the cancel deck notification whenever user deletes a particular deck. Added TODO for now.

2022-07-04 12:59 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        totalDueCount.count()
Removed 👍🏽

2022-07-04 13:00 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        totalDueCount.count()
Read and did'nt chaned anything.

2022-07-04 13:03 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +                ?: return currentTime + 3600000 // No deck for complete day. Restarting after 1 hour for all deck notification
Chanded to constant `ONE_HOUR_MS`

2022-07-04 13:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +            fireDeckNotification(deckList.first { it.did == deckId })
It needs to be handled here as well.

2022-07-04 13:30 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        totalDueCount.count()
I'd extract this to a method on SchedulerService, but it's a minor style change

2022-07-05 18:55 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +            fireDeckNotification(deckList.first { it.did == deckId })
Fixed

2022-07-05 19:43 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    ) {
Done.... 👍🏽

2022-07-05 20:19 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            calendar.set(MINUTE, minutesOfHour)
Done 👍🏽

2022-07-05 20:29 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        return data
Best approch according to you?

2022-07-05 20:34 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +            NotificationHelper(context).startNotificationWorkManager(3600000, true)
Done

2022-07-05 20:37 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        }
Replaced 👍🏽

2022-07-05 20:43 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +                    ?: TreeMap<String, MutableList<Long>>()
Done 👍🏽

2022-07-05 20:50 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            val newMap: TreeMap<String, MutableList<Long>>
Remove duplication 👍🏽

2022-07-05 20:54 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    }
Done Created extention function for append

2022-07-05 21:04 UTC, prateek-singh-3212 commented
@david-allison done with major fixes. couple of them needs disscussion. Use of TreeMap is intentional as it store data in sorted form. In our case it stores the notification time in ascending order.

2022-07-05 21:09 UTC, prateek-singh-3212 commented
> e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt: (139, 23): None of the following functions can be called with the arguments supplied: 
public constructor JSONObject(copyFrom: JSONObject) defined in com.ichi2.utils.JSONObject
public constructor JSONObject(x: JSONTokener?) defined in com.ichi2.utils.JSONObject
public constructor JSONObject(source: String?) defined in com.ichi2.utils.JSONObject
public constructor JSONObject(copyFrom: Map<Any?, Any?>) defined in com.ichi2.utils.JSONObject

I am passing the treeMap and it raned earlier. I think I is not running because I used Type alis

2022-07-11 23:37 UTC, david-allison commented on AnkiDroid/src/main/AndroidManifest.xml
> +<!--        Using custom work manager initialization-->
I'm fine with leaving it in, as long as there's an explanation as to why it's there and how to fix it

2022-07-11 23:38 UTC, david-allison requested changes
```
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt: (140, 23): None of the following functions can be called with the arguments supplied: 
public constructor JSONObject(copyFrom: JSONObject) defined in com.ichi2.utils.JSONObject
public constructor JSONObject(x: JSONTokener?) defined in com.ichi2.utils.JSONObject
public constructor JSONObject(source: String?) defined in com.ichi2.utils.JSONObject
public constructor JSONObject(copyFrom: Map<Any?, Any?>) defined in com.ichi2.utils.JSONObject
```

2022-07-12 18:57 UTC, prateek-singh-3212 commented
I was unable to fix this issue I don'nt know why. I used type alias but I tried it to pass using type casting as mentioned below. but it didn't worked.
```
val mapData = data as Map<String, MutableList<Long>> 
val jsonObj = JSONObject(mapData)
```
@mikehardy @Akshay0701

2022-07-12 23:27 UTC, david-allison commented
Let's avoid the alias so it compiles and I can move on with a review.

2022-07-13 07:01 UTC, prateek-singh-3212 commented
@david-allison done with the changes

2022-07-13 14:39 UTC, prateek-singh-3212 commented
Use of TreeMap is intentional as it store data in sorted form (ascending). In our case it stores the notification time in ascending order so most recent notification will always at top i.e index 0. I will be stored in deck  notification datastore.

2022-07-13 17:38 UTC, david-allison commented
I am asking about the **source of truth** of the notifications.

In my understanding: Right now, the current notification data depends entirely on past notification data, rather than on the data in the preferences.

If the user is on a flight, or the user's clocks change, then their notifications have shifted in time relative to the user's clock. 

If I have a notification at 8AM, and fly to Ecuador, then my notifications will be firing at 2AM, even though my notifications are still at 8AM because it's depending on the previous notification time.

2022-07-13 17:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            if (currentTimeMS < scheduleTimeMS) {
I don't feel this is as clean as the factoring I'd mentioend, but it seems correct to me.

I'll follow up on this if I have time, happy to let it in.

2022-07-13 19:51 UTC, prateek-singh-3212 commented
> In my understanding: Right now, the current notification data depends entirely on past notification data, rather than that and the data in the preferences.

> If the user is on a flight, or the user's clocks change, then their notifications have shifted in time

 >If I have a notification at 8AM, and fly to Ecuador, then my notifications will be firing at 2AM, even though my notifications are 
 still at 8AM because it's depending on the previous notification time.

Completly agree with you, current senirio doesn't handels the timezone diff. 
To handle this case we can use time zone change broadcast reciver and handels that their. 

Main algo would be 
1 timezone change detected
2. a = get the previous timezone which is stored in the preference and get the current time in ms of that timezone
3. b = get the new timezone  and get the current time in ms of that timezone
4. we do a-b i.e previousTimeZone - CurrentTimeZone = we get time diff in ms
5. we will add this in the current scheduled times of notification

Reference: https://stackoverflow.com/a/26905894

what are your thoughts on this?

2022-07-14 11:36 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        @NonNull hourOfDay: Int,
Fixed

2022-07-14 18:44 UTC, david-allison commented
> what are your thoughts on this?

This feels like we're adding more complexity, and more risk of things going wrong.

What would be the downsides of using the user's notification settings as the source of truth?

2022-07-14 18:52 UTC, prateek-singh-3212 commented
> What would be the downsides of using the user's notification settings as the source of truth?

From my point of view user will not get the notification at accurate time.  Yes, It is going to add lot of complexity and which increeas chances of failura as I am encountering challanges as I started working on it (Chalanges like fast forwading the notification when timezone diff is +ve and expanding the timezone when diff is -ve ). To avoid the complexity we can add the button `Calibrate notfication` which reschedules all the motification according to current timezone.  We can do this in future after succesful implementation on deck notification UI.

2022-07-14 19:13 UTC, david-allison commented
My stated worry was that time zone changes would permanently cause issues with the scheduling.

Moving the source of truth to the notification preferences means that this issue may only happens once (if the notification is moved to occur in less time).

Using the above model. The additional issue: changing timezones so the current notification appears earlier doesn't need the complexity of calculating deltas. 

1. Set a recurring timer to see if the timezone has changed.
2. If it has, recalculate notifications based on the current time

2022-07-14 19:16 UTC, prateek-singh-3212 commented
Oh understood! 😅

> Set a recurring timer to see if the timezone has changed.

We can check timezone whenever app starts. Works?

2022-07-14 20:36 UTC, prateek-singh-3212 commented
Okay, this works for me I will create plan for this. 

@david-allison shall we finialize this PR and move to all deck Notification UI? After creating the new UI I will link that UI with this PR for complete functionality.
I am open for changes in this PR and we can further optimization if required.

2022-07-14 20:42 UTC, david-allison commented
You'll need to fix the code quality lint. If you write TODOs, where the direction will change, and revert activating the functionality, then I don't see why we can't merge.

2022-07-14 21:15 UTC, prateek-singh-3212 commented
Done with lint

2022-07-15 11:39 UTC, mikehardy commented
> Oh understood! 😅
> 
> > Set a recurring timer to see if the timezone has changed.
> 
> We can check timezone whenever app starts. Works?

There is a broadcast intent you can listen for actually. Probably for this reason

2022-07-15 11:45 UTC, prateek-singh-3212 commented
Yes, I wrote about this in the above comment (https://github.com/ankidroid/Anki-Android/pull/11487#issuecomment-1183616055). I am currently using broadcast intent & completed 80% of work. So I will push it  by EOD. After that we can have discussion.

2022-07-15 12:59 UTC, david-allison commented
The broadcast intent is reported as being terrible (constantly firing): https://stackoverflow.com/questions/16113459/timezone-changed-intent-being-received-every-few-seconds/

2022-07-15 13:11 UTC, prateek-singh-3212 commented
Yes, but I tried the solution which is mentioned in stackoverflow then it is working fine. I triggers for 1st time only.

2022-07-15 13:19 UTC, david-allison commented
> Yes, but I tried the solution which is mentioned in stackoverflow then it is working fine. I triggers for 1st time only.

Can I confirm what this means, because the code from StackOverflow looks like it just ignores the spam of events:

* Do we get spammed with intents, and only filter them to ones which actually do things?
* Does this also stop the intents from being broadcast in the first place?

2022-07-16 13:08 UTC, prateek-singh-3212 commented
> Do we get spammed with intents, and only filter them to ones which actually do things?

I tested this situtation and it is triggring the intent for 2 time. From which I filter it out once and recreate the notification.

Done code refactoring and tested in my device and It is working as exected. 

References for review:
1. 1st Commit: It contains the integration of workmanager and datastorepreference with current codebase.
2. 2nd Commit: It contains the implementaion of notification datastore preference. It helps in storing and retriving
     a. all time deck data: `TreeMap<String, List<did>>`
     b. deck notification model: It is used to store the time and all the notification setting of particular deck.
3. 3rd Commit: This commit contains the intital implementaion of `Notification Work Manager` main highlight in this commit is the implementaion of `getTriggerTime` function. This function is used to calculate the next trgger time of the notification work manager.
4.  4th Commit: Implemantaion of `Notification Helper Class` This class is helps in building notification, tiggering notification, calibarting the notification according to timezone, computing notification work type etc...
5. `NEW` 5th Commit: Implemented broadcast reciver when timezone changes. I will trigger when timezone of user changed so I calibrates the notificoation according to new timezone of user.
6. 6th Commit: It integrates the notification helper functionality with notification work manger.
7. 7th Commit: Integrated work manager with AnkdroidApp 
8. 8th Commit: It is temporary commit. It is for testing only.

@david-allison

2022-07-16 23:13 UTC, david-allison requested changes
I'm happy here, minus the copy and commits which don't compile.

2022-07-16 23:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            oldTimeDeckData.filterValues { listOfDeck.addAll(it) }
I believe:

```kotlin
            val listOfDeck = oldTimeDeckData.values.flatten()
```

2022-07-16 23:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +            ) {
reverse the `if` for readability

2022-07-16 23:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +         * Get current time according the timezone of user.
What's returned? epoch time in milliseconds?

2022-07-16 23:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +            NotificationHelper(context).startNotificationWorkManager(initialDelay = ONE_HOUR_MS.toLong(), force = true)
as seen in my older comment, having two code paths to return here adds duplicated code and complexity.

I'd push harder for this one to be fixed

2022-07-16 23:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val filteredTimeDeckData = timeDeckData.filter { it.key.toLong() <= currentTime }
Ideally in an earlier commit to reduce line noise

2022-07-16 23:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        Timber.d("$title $message")
⚠️ Most of the commits don't compile, just comment out the code to get the variables in the commit where you introduce them

2022-07-16 23:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val ALL_DECK_NOTIFICATION_ID = 11
extract to a constant, or reuse if this variable was used elsewhere

2022-07-16 23:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
>          if (totalDueCount.count() > minCardsDue) {
nit: invert the `if` to reduce nesting

2022-07-16 23:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +                ),
⚠️ This isn't the correct way to format a string, use `context.getString(x, y, z)`

Note: Actually, use `getQuantityString` as well (see below)

2022-07-16 23:13 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="all_deck_notification_new_message">%1$d cards are waiting for you to review them. It only take %2$d mins</string>
This should be a `<plurals>`

2022-07-16 23:13 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="all_deck_notification_new_message">%1$d cards are waiting for you to review them. It only take %2$d mins</string>
We should keep the copy 'boring' for now.

`%d cards due`

2022-07-17 16:52 UTC, mikehardy commented
Huh 🤔 I use it in another app and have not seen pathological behavior, perhaps I have simply been lucky. That is direct experience of it working well. Perhaps the old/new comparison is sufficient. It's definitely the event driven / system of record way to do it

2022-07-17 16:55 UTC, david-allison commented
Prateek's done some digging, and it seems to be viable.

My guess is that some mobile network operators will be behaving badly, which is a concern as that makes it very hard to reproduce in the field. But I'm happy with including it in the PR and working around this if it becomes a true issue.

2022-07-17 22:03 UTC, mikehardy commented
> Prateek's done some digging, and it seems to be viable.
> 
> My guess is that some mobile network operators will be behaving badly, which is a concern as that makes it very hard to reproduce in the field. But I'm happy with including it in the PR and working around this if it becomes a true issue.
> 
> 

Okay - that will manifest as android system showing the high battery use warning for AnkiDroid because of wakeups to service the intent, and I guess analytics on what carriers and devices are in play. Perhaps doing an analytics hit now when timezone sets would pre-answer the question since it logs those things I think? Then can maybe Blocklist them somehow

2022-07-31 17:34 UTC, Arthur-Milchior reviewed
Thanks a lot for all of this work. It's a very huge amount, 887 lines. I'm also thankful for having plenty of commits, it would have been a nightmare to review otherwise.
I first expected to wait until you applied David remark before reviewing, so that I get to see his remark taken into account. but I finally decided to change my mind, given that already two weeks passed.

My most general request is to add far more explanations. No reviewer spent as much time as you did on notification and worker (even if I went to read worker documentation). so you really need to help us review. And sometime even if the method implementation is simple to read, having some javadoc not only ensure that someone can call your method without having to read the implementation, but also that we can check that the implementation agrees with what you expected to do.

2022-07-31 17:34 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> + * Broadcast receiver to listen timezone change of user.
Can you also please note what it does. Right now, I only know when it's called

2022-07-31 17:34 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +                NotificationHelper(context).calibrateNotificationTime(newCurrTimeMS, timeDiffMS)
I don't understand whether you are changing the notification time in order to ensure that it still appears at the same absolute time or whether you ensure that it arrives at the same clock hour, and that when the user move to another time zone, the notification is moved. Ideally specify it in the method documentation, and potentially here

2022-07-31 17:34 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        new NotificationHelper(this).startNotificationWorkManager(0, false);
For ed3f834734cf77cb2b6171403805aefb0cfc8f4c can you make a commit message that gives more explanation. What are you connection to what?

2022-07-31 17:34 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +                did,
I understand your commit message state its for test. But what is it doing here outside of the test folder and not even in a method written for test.

2022-07-31 17:34 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
> +                                NotificationHelper(this@DeckOptions)
Shouldn't you add a "todo " to note to remove the previous notification manager? I assume it's alarm manager

2022-08-05 16:31 UTC, prateek-singh-3212 reviewed
Thanks, @david-allison @Arthur-Milchior  for reviewing my PR. Sorry for taking this much time in implementing the suggestion. I was stuck somewhere that's why I was unable to complete it on time. I saw your changes as you posted them and slowly and steadily fixed them. 

I fixed most of the changes but some of them require discussion so I left them.

2022-08-05 16:31 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +     * @return Value that needs to be fetched <b>(VALUE WILL BE STRING)</b>.
Done changes

2022-08-05 16:31 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +        return context.notificationDatastore.data.map { metaData ->
Changed.

2022-08-05 16:31 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +        }.catch {
done

2022-08-05 16:31 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +     * It stores the data asynchronously.
Done

2022-08-05 16:31 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +        val objToJson = ObjectMapper()
Done create a member variable

2022-08-05 16:31 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/DeckNotification.kt
> +    val deckName: String,
The deck E which has correct id

2022-08-05 16:31 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/DeckNotification.kt
> +    val deckName: String,
Removed. I didn't think this case. Thanks for informing me. I can access the deck name if required using deckid in the notification work manager.

2022-08-05 16:31 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +        }.catch {
Changed and throw the custom exception

2022-08-05 16:31 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +        return runCatching {
How to send it to ACRA??

2022-08-05 16:52 UTC, prateek-singh-3212 commented
Done, Mistake I here I tried to reply to your comments but I accidentally reviewed the PR.

2022-08-06 05:05 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +            val did = deckList.firstOrNull { it.did == deckId }
Finding the optimum way.

2022-08-06 05:09 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +            NotificationHelper(context).startNotificationWorkManager(initialDelay = ONE_HOUR_MS.toLong(), force = true)
Fixed this by creating the function `rescheduleNextWorker`

2022-08-06 05:11 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val filteredTimeDeckData = timeDeckData.filter { it.key.toLong() <= currentTime }
Done

2022-08-06 05:12 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        Timber.d("$title $message")
Used timber to use variable initally

2022-08-06 05:29 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val ALL_DECK_NOTIFICATION_ID = 11
Done

2022-08-06 05:32 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +                ),
Used

2022-08-06 05:36 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="all_deck_notification_new_message">%1$d cards are waiting for you to review them. It only take %2$d mins</string>
Used

2022-08-06 05:36 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="all_deck_notification_new_message">%1$d cards are waiting for you to review them. It only take %2$d mins</string>
Done

2022-08-09 11:14 UTC, david-allison requested changes

2022-08-09 11:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * Create the Scheduled Deck Notification using WorkManager.
```suggestion
     * Adds a daily recurring notification for the provided deck to the notification schedule.
     * This method may cause the next reminder notification to be shown sooner
```

2022-08-09 11:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +                .getOffset(now) == TimeZone.getTimeZone(newTimezone).getOffset(now)
style: extract `TimeZone.getTimeZone(oldTimezone).getOffset(now)` into a [nested function](https://www.oreilly.com/library/view/functional-kotlin/9781788476485/6725edd3-33dc-41d3-8b0d-fcab12de7898.xhtml#:~:text=Kotlin%20allows%20you%20to%20nest,cannot%20be%20accessed%20from%20outside.)

```
fun getOffsetFromNow(timezone: String) = TimeZone.getTimeZone(timeZone).getOffset(now)
```

2022-08-09 11:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        deckIdsToTrigger.forEach { deckId ->
Not discussed @Arthur-Milchior do you have an opinion here?

2022-08-09 11:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +//        TODO: Start work manager with initial delay though Notification Helper.
needs to be fixed before merging

2022-08-09 11:14 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="all_deck_notification_new_title">Where are you??</string>
I don't agree with this style of notification messages. We need to be very careful when injecting personality into the app, and I don't think we want to do it yet.

2022-08-10 11:59 UTC, prateek-singh-3212 commented on AnkiDroid/build.gradle
> +    testImplementation "io.mockk:mockk:1.12.4"
By mistake

2022-08-10 12:01 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/AndroidManifest.xml
> +            <!-- If you are using androidx.startup to initialize other components -->
Done

2022-08-10 12:09 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/AndroidManifest.xml
> +        <!-- Using custom work manager initialization-->
Done added link of google issue tracker

2022-08-10 12:13 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        // TODO: Notification CleanUP. Remove the Boot Service after successful merge of PR #11487 (Notification Work Manager)
Done: Changed to 
> // TODO: Notification CleanUP. Delete the Boot Service after successful implementation of Notification Work Manager.

2022-08-10 12:59 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +     * We are using custom work manager because UNIT TESTS are failing.
@david-allison Added a TODO in code. Is it fine?

2022-08-10 13:44 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +                NotificationDatastore(context).also {
Done. Added a check

2022-08-10 14:10 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +//        TODO: Start work manager with initial delay though Notification Helper.
It is fixed in the `Integrated NotificationWorkManager with NotificationHelper` commit

2022-08-10 18:13 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +            val did = deckList.firstOrNull { it.did == deckId }
Added the logic which avoids O(n^2) operation

2022-08-10 18:17 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        deckIdsToTrigger.forEach { deckId ->
Sorry, But I didn't have any edge case my mind. @david-allison Can you please explain any one edge case?

Changed the logic here a bit. Please wait for a while till the new commits go live.

2022-08-10 18:19 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * Create the Scheduled Deck Notification using WorkManager.
Done, Thanks

2022-08-10 18:26 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun createScheduledDeckNotification(
Done changed.

2022-08-10 18:27 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            )
Done

2022-08-10 18:39 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="all_deck_notification_new_title">Where are you??</string>
Changed this to `All Deck reminder for now`

2022-08-10 18:43 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
> +                                // TODO: Remove Alarm manager after successful merge of PR#11487
Removing this because TODO in AnkiDroiApp and this one is referencing to the same thing.

2022-08-10 18:43 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            // FIXME: FOR TEST ONLY Remove this.
Dropping the last commit.

2022-08-10 18:50 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +                .getOffset(now) == TimeZone.getTimeZone(newTimezone).getOffset(now)
Done

2022-08-10 21:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +     * We are using custom work manager because UNIT TESTS are failing.
That's good to me

2022-08-13 11:03 UTC, david-allison requested changes
One bug, mainly requesting @Arthur-Milchior 's opinion on the architecture

2022-08-13 11:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        }
This is over-complicated. No need to sort

```kotlin
        
        val deckIdsToTrigger = timeDeckData
            .filter { it.key.toLong() <= currentTime } // all the notifications which are due
            .flatMap { it.value } // obtain the DeckIds
            .toHashSet()
        
        val deckNotificationData = deckList.filter { deckIdsToTrigger.contains(it.did) }
        for (deck in deckNotificationData) {
            fireDeckNotification(deck)
        }
        
        // Decks may have been deleted
        if (deckIdsToTrigger.size != deckNotificationData.size) {
            Timber.d("Decks deleted")
            // TODO: Cancel deck notification when user deletes a particular deck to handle case [user deletes a deck between the notification being added and executed]
        }
```

2022-08-13 14:05 UTC, prateek-singh-3212 reviewed
Done with final changes and This PR is ready for merge from my side. I mention one Time Complexity issue below. else We are good to go 🚀 
Change Log: 
1. Removed the previous O(n^2).
2. Changed the listOfDeck from MutableList<Long> to HashSet<Long> for future optimization.
3. Completed all TODO's which can be fixed now. But some of them require the future PR to be merged.

2022-08-13 14:05 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        }
@Arthur-Milchior @mikehardy @david-allison Need your help here. I tried to remove this O(n^2) complexity. But to remove a particular deck from the list we will be requiring the timeOfNotification (which is a key in time deck notification). 
I tried to reduce the time complexity but didn' t found any solution.

2022-08-13 14:37 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +            if (oldTimezone != "null" || getOffsetFromNow(oldTimezone) == getOffsetFromNow(newTimezone)) {
Fixed. Used nested function here

2022-08-13 15:59 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        }
Tried different approch

2022-08-13 16:44 UTC, david-allison approved these changes
LGTM, awaiting an architectural question

2022-08-13 16:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        }
Why?

2022-08-13 16:49 UTC, david-allison requested changes
On second look, code provided wasn't used.

2022-08-13 16:57 UTC, prateek-singh-3212 commented
@david-allison I used your approach but moving one step ahead i.e integrating the cancel deck notification  I want timeOfNotification also so in getting that time complexity changed to O(n^2) about which I raised query above

2022-08-13 16:59 UTC, david-allison commented
I feel you're making the code a lot more complicated to attempt to remove an O(n^2) operation from the unhappy path: a deck being deleted.

I wouldn't bother with this.

Instead, change ` fun removeDeckNotification(deckSchedTime: TimeOfNotification, did: Long) {` into ` fun removeDeckNotifications(vararg deckIds: Long)`

Handle the O(n^2) operation in that method, and mark it as such, if it ever becomes a performance problem, we have all the information we need to deal with it at the right level of abstraction

2022-08-13 23:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +            if (deckList.containsKey(deckAndTime.key)) {
HashMap return null if value do not exists.
So you can do simply
```Kotlin
deckList[deckAndTime.key]?.let(::fireDeckNotification)
```

2022-08-13 23:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val deckIdsToTrigger: HashMap<Long, TimeOfNotification> = HashMap()
I'm sorry, but I fail to understand why you needed to reverse the map. For iterating over pairs, you could have done it from the initial map, even if it requires two `forEach`

2022-08-13 23:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        NotificationDatastore.getInstance(context).setTimeDeckData(timeDeckData)
I don't think all of those intermediate variables containing maps are necessary. 
the principle of having forEach, filters and maps means that we can just cascade most of it, such as
```kotlin
        val timeToDecks = NotificationDatastore.getInstance(context).getTimeDeckData() ?: return
        timeToDecks.filter {it.key.toLong() <= currentTime}
            .forEach {
                val triggerTime = it.key
                val dids = it.value
                dids.forEach { did ->
                    // Handles case when deck is deleted.
                    deckList[did] ?.let (::fireDeckNotification) ?:
                    // Deck deleted. Removing from list.
                    NotificationHelper(context)
                        .removeDeckNotification(triggerTime, did)
                }

                timeToDecks.remove(triggerTime)
                timeToDecks[triggerTime + ONE_DAY_MS] = dids
            }

        // Saving the new Time Deck Data.
        NotificationDatastore.getInstance(context).setTimeDeckData(timeToDecks)
```

2022-08-13 23:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +    private fun fireDeckNotification(deckDueTreeNode: DeckDueTreeNode) {
Please write it explicitly in the javadoc then. 
```
/**
* Fire the notification for [deck] if needed. 
* We consider it is needed if [deck] or any of its subdecks have cards, we trigger notification only for [deck] itself in any case
*/
```

2022-08-13 23:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +    private fun fireDeckNotification(deckDueTreeNode: DeckDueTreeNode) {
I think the variable could be named `deck` simply. It'll clearly explain what it actually represents. No need to repeat the type

2022-08-13 23:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +    private fun fireAllDeckNotification(deckList: HashMap<Long, DeckDueTreeNode>) {
Please, don't call `list` something that is not a list.
In this case, `decks` would suffice, the typing would be enough to note that it's did to the node of the deck

2022-08-13 23:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        Timber.d("Next trigger time $initialDiff")
I think the variable you want is `nextTriggerTime`, because right know you'll only show the delay until then.
Also, you may watn to transform this, because a timestamp in milisecond will almost never be useful as far as log goes, unless we start to analyze them automatically

2022-08-13 23:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        Timber.d("Firing deck notification for did -> ${deckDueTreeNode.did}")
Please don't use Format string in linter. See #12022 for explanation.
You can use
`Timber.d("Firing deck notification for did -> %d", deckDueTreeNode.did)`

2022-08-13 23:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        fun getTriggerTime(data: AllTimeAndDecksMap): Long {
Please use a more descripitive variable name than `data`

2022-08-13 23:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +         * Calculates the next time to trigger the Notification WorkManager.
Please document that it's not the next time a notification should be shown, but a time at most in one hour. (And indicate why we trigger the manager even if we have no notification to show)

2022-08-14 05:50 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +     * This Method sets the Work Manager Configuration. We are using Custom work manager Initialization.
No issues, As we disabled the default work manager we need to enable/set the new custom work manager i.e with custom work manager we provide our own setting to start the work manager.
See: https://developer.android.com/topic/libraries/architecture/workmanager/advanced/custom-configuration

2022-08-14 05:51 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +     * This Method sets the Work Manager Configuration. We are using Custom work manager Initialization.
> Also, as far as I understand, this return the the configuartion, but it does not seems to set it.

The work manager does it automatically.

> Not useful to start with "this method", since it's already obvious you document this method.

Removed

2022-08-14 05:52 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +     * **Custom work manager is disabled in Manifest**.
I was saying ByDefault is disabled. Removing this as It is confusing + It is implementation detail

2022-08-14 05:57 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +     * We are using custom work manager because UNIT TESTS are failing.
Done as suggested.

2022-08-14 06:00 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +                .setMinimumLoggingLevel(android.util.Log.INFO)
I am not aware. Removed this now

2022-08-14 06:06 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> + * A list of DeckIds which is going to trigger at particular time.
No, I am saying that for eg there is 100 decks out of which 10 trigger at 5:00 AM. So with this "list of DeckIds" means 10 deckids which is going to trigger at 5 AM

2022-08-14 06:08 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +typealias TimeOfNotification = String
Okay, Changed

2022-08-14 06:09 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> + * This class is singleton use [getInstance]
Done

2022-08-14 06:13 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +     * It stores the data asynchronously. It will create Coroutine Scope Internally.
Done mistake in documentation here. Sorry Fixed this now.

2022-08-14 06:17 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +     * It stores the data synchronously.
I don't want to remove this function now because I used this in future commits and It is useful in upcoming PRs.
If this is not used then I will remove this.

2022-08-14 06:19 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +     * Stores the Map of time and deck list to Datastore
> "the mapping from time to deck"
This one is not clear.
Changed the language a bit.

2022-08-14 06:26 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +     * Fetches the Map of time and respective of deck-id at that time from Datastore.
changed the doc little bit for better understanding

2022-08-14 06:34 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +     * Stores the details of particular deck scheduling.
Done changed to "Stores the details of the [DeckNotification] scheduling of deck [did]"

2022-08-14 06:35 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +    suspend fun setDeckSchedData(did: Long, data: DeckNotification): Boolean {
Done

2022-08-14 06:37 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +    suspend fun setDeckSchedData(did: Long, data: DeckNotification): Boolean {
I will use this in future PR while implementing the new Deck Notification UI

2022-08-14 06:37 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +    suspend fun setDeckSchedData(did: Long, data: DeckNotification): Boolean {
Done, Thanks

2022-08-14 06:41 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +            objectMapper.readValue(
Done

2022-08-14 06:43 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +         * There should be only 1 instance of preferencesDataStore. It is THREAD SAFE.
Done

2022-08-14 06:46 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +                val newInstance = INSTANCE ?: NotificationDatastore(context).also {
Done

2022-08-14 06:52 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +        private var INSTANCE: NotificationDatastore? = null
Used this

2022-08-14 08:35 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> + * Store all the time and list of deck ids for a particular time.
Treemap store the values in ascending order by default so the most recent notification which is going to trigger will be at the top.

2022-08-14 08:36 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +        private var INSTANCE: NotificationDatastore? = null
Implemented your solution.

2022-08-14 08:38 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/DeckNotification.kt
> + * Stores the notification details of particular deck.
Done

2022-08-14 08:42 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +    CoroutineWorker(context, workerParameters) {
I used default kotlin indentation here.

2022-08-14 08:49 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +    // Lambda to check the collection is not null.
created a private method

2022-08-14 08:51 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        fun getTriggerTime(data: AllTimeAndDecksMap): Long {
Used

2022-08-14 08:52 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +         * @param data map of deck trigger time and list of deck at particular time. [AllTimeAndDecksMap]
Done

2022-08-14 08:59 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +         * Calculates the next time to trigger the Notification WorkManager.
Done

2022-08-14 09:05 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        Timber.d("Next trigger time $initialDiff")
changed. 
Used this for testing purpose. It will be easier to test in when time is in long

2022-08-14 09:09 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +    private suspend fun rescheduleNextWorker(result: Result): Result {
Yes, sort of but my major aim is to run the reschedule the next worker whether the worker failed or passed. 
I might use this in the future when we want to reschedule a worker after 5 min In case it fails.

2022-08-14 09:11 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        Timber.d("Firing deck notification for did -> ${deckDueTreeNode.did}")
done

2022-08-14 09:12 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +    private fun fireDeckNotification(deckDueTreeNode: DeckDueTreeNode) {
done

2022-08-14 09:13 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +    private fun fireDeckNotification(deckDueTreeNode: DeckDueTreeNode) {
done

2022-08-14 09:17 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        NotificationDatastore.getInstance(context).setTimeDeckData(timeDeckData)
It is creating O(n^2) time complexity

2022-08-14 09:18 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        }
Sure, I will add

2022-08-14 11:05 UTC, prateek-singh-3212 commented on AnkiDroid/build.gradle
> +    testImplementation "io.mockk:mockk:1.12.4"
Fixed earlier

2022-08-14 11:06 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +     * TODO: Remove custom implementation after implementing 14 tests using WorkManagerTestInitHelper. SEE: https://github.com/ankidroid/Anki-Android/pull/11487/commits/6c164ec897df16c8545767570b18c7
Changed the line. added reference of offical google doc

2022-08-14 12:51 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +    private fun fireAllDeckNotification(deckList: HashMap<Long, DeckDueTreeNode>) {
Fixed

2022-08-14 12:54 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        }
```
        // Sorted all the decks whose notification time is less than current time.
        val filteredTimeDeckData = timeDeckData.filterTo(HashMap()) { it.key.toLong() <= currentTime }

        // Creating list of all decks whose notification is going to trigger
        val deckIdsToTrigger = filteredTimeDeckData
            .flatMap { it.value }
            .toHashSet()

        // Triggering the deck notification
        val deckNotificationData = deckList.filter { deckIdsToTrigger.contains(it.did) }
        for (deck in deckNotificationData) {
            fireDeckNotification(deck)
            deckIdsToTrigger.remove(deck.did)
        }

        // Decks may have been deleted
        if (deckIdsToTrigger.size != 0) {
            Timber.d("Decks deleted")
            NotificationHelper(context).removeDeckNotification(deckIds = deckIdsToTrigger.toLongArray())
        }

```
Changed the logic a bit

2022-08-14 12:57 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +    private fun fireAllDeckNotification(deckList: HashMap<Long, DeckDueTreeNode>) {
fixed

2022-08-15 04:29 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * @param did Unique identifier for deck.
Done

2022-08-15 04:32 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            // Fetch all the time deck data.
Removed the calculate time comment

2022-08-15 04:33 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            // Fetch all the time deck data.
done

2022-08-15 04:36 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            // Calculate the work type and schedule time
Changed

2022-08-15 04:37 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        // Set the calender for schedule time. It will return the time according to user time zone.
Done

2022-08-15 04:38 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * @return pair of schedule time in long and work type [NotificationWorkType]
Done

2022-08-15 04:40 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        val scheduleTimeMS = calendar.timeInMillis
changed to notificationTimeInMS because it is more clear

2022-08-15 04:42 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    private fun computeNotificationTime(
changed this to `getNotificationData`

2022-08-15 04:43 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            Timber.d("Scheduled time is gone for today")
Done

2022-08-15 04:44 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            // Scheduled time is gone for today.Add one day in current schedule time as calendar is set for today
Done

2022-08-15 04:46 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            // Scheduled time will come today only. But No previous time deck data exist creating new data.
add in new line

2022-08-15 04:47 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            Timber.d("Scheduled time will come today only. And it will come before the current schedule deck.")
means the notification will trigger before the currently scheduled deck.

2022-08-15 04:59 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        timeDiff: Long
I used this earlier. Removed all params now

2022-08-15 05:15 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    private fun AllTimeAndDecksMap.append(
changed

2022-08-15 05:16 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            // Replacing old work manager with new one. (initialDiff = currentTime - nextTriggerTime)
It is for general explanation about what I did below in simple terms

2022-08-15 05:17 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        if (scheduleTimeMS < currentTimeMS) {
done

2022-08-15 05:20 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * See [saveScheduledNotification]
It requires while syncing the deck. But it makes code more cleaner and redable

2022-08-15 05:24 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * Calculates the notification and type of work that needs to be done to trigger notification.
changed

2022-08-15 05:31 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +typealias AllTimeAndDecksMap = TreeMap<TimeOfNotification, ListOfDeck>
Added.

2022-08-15 22:42 UTC, Arthur-Milchior reviewed
I've finally read all of this.

For the next code you upload for us to review, please add javadoc on every single method, every single parameter of method, every single class member. Write every assumption you make. 

This would generally be more than what is required. But you have a strong tendency to add not enough documentation, even after I asked in the first reviews. And this means that reviewing is extremely slow because I've got to guess what you want to be doing.
I spent almost my entire week-end on this PR. And I won't do it again. 

And, on the opposite side, I'm not asking you to write comment for each line of code. Only do it when doing so add informations that is not already clear to someone knowing how to read Kotlin.

Finally, now that I've read everything, I can give more feedback on the architecture.
One thing I fear is that testing will be hard.
All of the code I see now seems to assume we already know the list of deck for which we must send a notification. Even when you recalibrate, you don't check whether there are new decks to add. 
I'd prefer very strongly if a function, maybe recalibrate, was in charge of restarting everything from scratch. Because the nice thing with starting things from scratch is that we won't have any problem with debugging; indeed, in case of bug we erase all data and we restart. We won't have problem with test where a failed first test impact a second test. 
I don't know how hard such a change would be. but it would be really helpful.

I'm not approving for two reasons.
First: if I'm right `Exception Occurred during fetching of data."` will send far too many crash report for us to be able to accept it 
Second: I really want more texts in all commit messages. And that's not something that can be done after the PR is merged. We can correct most documentation, but the commit message will stay forever. And given how important each commit is, I care about having a lot of explanations about what is done from the user point of view, from the developer using your library point of view, from the point of view of the data store, of the notification system, etc...

2022-08-15 22:42 UTC, Arthur-Milchior commented on AnkiDroid/src/main/AndroidManifest.xml
> +                <action android:name="android.intent.action.TIMEZONE_CHANGED" />
Do you know what "the commit message" is? 

When you create a commit, you should give it a title. Here it is "Implemented Timezone Change broadcast receiver & Calibrated notification."

And you usually must add more lines that explain what is occurring in the commit. That must contains all information that may be useful for a future reader to understand why you made this change.
Most informations should be in the code, and so maybe you can use 
```
<!--Ensure notification are adapted to local timezone instead of absolute time. This is required because Android store notification in GMT time -->
```
But it can also be simply if the commit message. For example, knowing whether we'll need to request more permission from the user through android play store is something we'll only do once, so it can be okay to note it in the commit message.

2022-08-15 22:42 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +        private const val TIMEZONE_KEY = "TIMEZONE"
Please add as javadoc its a key for the datastore. Right now it's clear. Still, for future reader exploring the codebase, might be good to indicate where value is used

2022-08-15 22:42 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +         * Get current time according the timezone of user.
Please indicate what is zoneId. Or just to go `@see [TimeZone.getTimeZone]`

2022-08-15 22:42 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +         * Registers timezone change receiver on app start.
I think this should be two sentences.

Registers a receiver for notification about timezone change.
This method should be called on app start

2022-08-15 22:42 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="all_deck_notification_new_title">All Deck Reminder</string>
I don't think this is a title we actually want to show users.
Maybe simply "AnkiDroid reminder" or "Cards due reminder". I don't believe it's useful to note "all decks", it's not adding information here

2022-08-15 22:42 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        // Creates an explicit intent for an DeckPiker Activity.
a DeckPicker activity

2022-08-15 22:42 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        // Creates an explicit intent for an DeckPiker Activity.
Those lines up to the creation of resultPendingIntent seems to be repeated twice exactly the same way.
Can you please move them into a function or a constant together.
And please find a more specific name. For example "DeckPickerOpeningIntent"

2022-08-15 22:42 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val resultIntent = Intent(context, DeckPicker::class.java)
Actually, I don't understand. If we are dealing with a specific deck, why do you create an intent for the deck picker.
We should have an intent for the Reviewer that open the specified deck.

2022-08-18 17:52 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +* We use TimeOfNotification as key of json object. So it must be string.
Done added `NOTE: it's in decimal.
Hexadecimal would make the conversion faster and takes less space, but really not worth the code complexity added.`

2022-08-18 18:11 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +typealias NotificationTodo = TreeMap<TimeOfNotification, SimultaneouslyTriggeredDeckIds>
Added
```/*
* NOTE: In Time Of Notification String will break when timestamp gets an extra digit because we'll get new timestamps
* starting with a 1 that will be a number greater than previous numbers but alphabetically shorter
* This will occur on 20 NOVEMBER 2286
*/```

2022-08-18 18:19 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +    suspend fun getDeckSchedData(did: Long): DeckNotification? {
@Arthur-Milchior  Added. I think the below situation will not occur because the JSON format will be correct almost every time because we are serializing and deserializing JSON using jackson.
    *  * if there is a preference whose entry for this key can't be cast to DeckNotification, throw

2022-08-18 18:30 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +        }.firstOrNull()
Changed this thanks for pointing this out

2022-08-18 19:42 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +        }.catch { ex ->
Fixed this with the new  implementation.

2022-08-18 19:59 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> + * **NOTE: It is a coroutine worker i.e it will run asynchronously on the Dispatcher.DEFAULT**
Done 👍🏽

2022-08-18 20:16 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +    override suspend fun doWork(): Result {
Discussed on call

2022-08-18 20:16 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        // Access the collection.
Removed

2022-08-18 20:24 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val sched = collection?.sched ?: kotlin.run {
Done, Thanks for helping me out here. This solves the problem.

2022-08-18 20:27 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val deckList = sched.deckDueTree().map { it.value }
Done

2022-08-18 20:30 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +    private suspend fun processSingleDeckNotifications(deckList: List<DeckDueTreeNode>) {
Done thanks

2022-08-18 20:30 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +    private suspend fun processSingleDeckNotifications(deckList: List<DeckDueTreeNode>) {
Done

2022-08-18 20:32 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        Timber.d("Processing all deck notification...")
Sorry for mis leading comment here. Changed this

2022-08-18 20:40 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +     * Fire the notification for due cards in all decks including subdecks.
Done

2022-08-18 20:51 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +     * Reschedule Next Worker which need to be done irrespective of worker failed or succeed.
Done

2022-08-18 20:55 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +            Timber.d("Decks deleted")
Done aaded 
Decks %s might be deleted but we didn't cancel deck notification for those decks. Canceling deck notification for these decks.".format(deckIdsToTrigger.toString())

2022-08-18 20:58 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        // Decks may have been deleted
Done

2022-08-18 21:02 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +            deckIdsToTrigger.remove(deck.did)
> You could obtain the same effect by just keeping a boolean which notes whether you did not found a deck. That would save us the use of one extra set.
I think it will complicate the thing. and we are not using extra set I am reusing the previous data set.

> Shouldn't you delete those missing decks from the set associated to its timestamp too? And if there is no more deck, ensure that the time stamp (plus one day) is not rescheduled?

Yes, what I am doing the same thing below. you can refer removeDeck in notificationHelper

2022-08-18 21:04 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val deckNotificationData = deckList.filter { deckIdsToTrigger.contains(it.did) }
Added a comment

2022-08-18 21:06 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        // Creating list of all decks whose notification is going to trigger
Changed

2022-08-18 21:15 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        if (timeDeckData.isNullOrEmpty()) {
> Is it only for efficiency?

Yes

2022-08-18 21:16 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +            Timber.d("No time deck data found, returning")
done

2022-08-18 21:23 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val filteredTimeDeckData = timeDeckData.filterTo(HashMap()) { it.key.toLong() <= currentTime }
Used hasmap for easy comparision because O1 complexity

2022-08-18 21:25 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val filteredTimeDeckData = timeDeckData.filterTo(HashMap()) { it.key.toLong() <= currentTime }
changed to timeDeckDataToTrigger

2022-08-18 23:31 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val sched = collection?.sched ?: kotlin.run {
You can simplify this with `withCol`: https://github.com/ankidroid/Anki-Android/pull/11849

2022-08-19 17:15 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        // Sorted all the decks whose notification time is less than current time.
changed that to filter

2022-08-19 17:22 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    private fun getNotificationData(
Okay, changed to `notificationData`

2022-08-19 17:32 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +                notificationTimeInMS + NotificationWorkManager.ONE_DAY_MS,
Done added thanks for suggesting

2022-08-19 17:32 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        did: Long,
Done

2022-08-19 17:39 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * Calibrates the notification time. i.e It recreates the deck time Map.
Done

2022-08-19 17:44 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * Generally used when user time zone changes.
I think It would be difficult to do so. While scheduling the notification we saves the data in datastore So, Data in datastore will be always fresh.

2022-08-19 17:51 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            // Fetch all the time deck data.
Removed the "Fetch all the time deck data." and changed to "Notification. Their timestamp may be wrong". Did you mean this?

2022-08-19 17:52 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            // Creating new time deck data
Done

2022-08-19 17:54 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            for (element in 0..listOfDeck.size) {
Done

2022-08-19 17:57 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * @param force if true then it will destroy the existing work manager and recreates the new one.
Done

2022-08-19 18:03 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun removeDeckNotification(vararg deckIds: Long) {
Done

2022-08-19 18:06 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        .setColor(ContextCompat.getColor(context, R.color.material_light_blue_700))
Yes, I think there is no light mode and night mode for notification. So yes it will be hard coted

2022-08-19 18:09 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +                        allTimeAndDecksMap[timeDeckData.key] = deckList
Removed, Thanks

2022-08-19 19:21 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +                        val deckList = timeDeckData.value
Done

2022-08-19 19:25 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +                        allTimeAndDecksMap.remove(timeDeckData.key)
Done

2022-08-19 19:26 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        CoroutineScope(Dispatchers.Default).launch {
Yes, but there also I have to do O(n^2) operation so David told me to do that here

2022-08-19 19:28 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun removeDeckNotification(vararg deckIds: Long) {
@Arthur-Milchior How can I put the lock? added doc

2022-08-19 19:34 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +                newTimeDeckData.append(deckData.did, notificationData.scheduleTime)
Yes, But I am recreating it to avoid complexity  and bugs

2022-08-19 19:44 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/AndroidManifest.xml
> +                <action android:name="android.intent.action.TIMEZONE_CHANGED" />
Done. added new commit message 
``` Ensure notification are adapted to local timezone instead of absolute time. This is required because Android store notification in GMT time ```

2022-08-19 19:46 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +        private const val TIMEZONE_KEY = "TIMEZONE"
done

2022-08-19 19:47 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +         * Registers timezone change receiver on app start.
Done

2022-08-19 19:48 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +         * Get current time according the timezone of user.
Done added

2022-08-19 20:12 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        // Creates an explicit intent for an DeckPiker Activity.
Doen

2022-08-19 20:16 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        // Creates an explicit intent for an DeckPiker Activity.
Done

2022-08-19 20:17 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="all_deck_notification_new_title">All Deck Reminder</string>
Done

2022-08-19 20:28 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        new NotificationHelper(this).startNotificationWorkManager(0, false);
Done. added did intetn

2022-08-19 20:28 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val resultIntent = Intent(context, DeckPicker::class.java)
Done. added did intetn

2022-08-19 20:29 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        // Creates an explicit intent for an DeckPiker Activity.
changed. Implemented below solution

2022-08-19 20:34 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        new NotificationHelper(this).startNotificationWorkManager(0, false);
Done

2022-08-19 20:49 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val sched = collection?.sched ?: kotlin.run {
@dae How can I handel this case
`  This guarantee does not hold if legacy code calls [getColUnsafe]. `
I want to fail the worker when I didn't get the data.

2022-08-19 21:09 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +                    newTimeDeckData
Done

2022-08-19 21:10 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +                        val deckList = timeDeckData.value
Fixed

2022-08-19 21:16 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        SAVE_AND_RESCHEDULE,
Done add bit of documentation

2022-08-19 23:28 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="all_deck_notification_new_title">All Deck Reminder</string>
Was this done?

2022-08-20 03:37 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val sched = collection?.sched ?: kotlin.run {
withCol() will throw an exception if the collection has been closed by something like a colpkg import or full sync with the legacy schema, so you can use a try/catch.

2022-08-20 09:07 UTC, Arthur-Milchior commented
Linter has a real (and simple to solve) failure
> > Task :AnkiDroid:ktlintMainSourceSetCheck FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt:19:1 Imports must be ordered in lexicographic order without any empty lines in-between with "java", "javax", "kotlin" and aliases in the end

2022-08-20 16:22 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="all_deck_notification_new_title">All Deck Reminder</string>
Sorry lost this commit. Done now

2022-08-20 16:32 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val sched = collection?.sched ?: kotlin.run {
Thanks. Handled this with try and catch

2022-08-20 17:13 UTC, prateek-singh-3212 commented
@ankidroid/gsoc-mentor Done with checks.

2022-08-20 17:25 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * Start the new notification Work Manager.
As we are using onTimeWorkManager. So it runs at a particular time does its task and reschedules the next worker. That means that there is one and only one notification worker is scheduled every time the app runs.

2022-08-21 03:47 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val topLevelDecks = sched.deckDueTree().map { it.value }
This is not the correct way to use withCol. The call to deckDueTree() should be inside withCol, as outside of it there is no guarantee that the collection is open.

2022-08-21 18:41 UTC, Arthur-Milchior reviewed
Thanks for all of those changes.

A few general remarks.

# Regarding commit message.

Usually, commit messages starts with a one-line title. That's what's assumed by most GUI, in particular github. That makes long line not displayed properly

Then, there should be a message. Most commit do not change a lot of the behavior of the app, so often just the title is fine.
However, you're writing non trivial changes, adding new feature to the codebase and even new features. So it's relatively important for you to put potentially multiple paragraph by commit message. First because the reviewer know what to expect when they'll review the commit. Secondly because a future reader who wants to understand why a change was done and look at history later, should be able to undersatnd the context without reading the whole PR discussion.

# what to do while waiting

While I still require a lot of changes, for example due to still one daylight saving bug, the behavior is now stable enough that you can still use this code and build on top of it without risking too much to have your work be useless.

So, while you wait for a reviewer to answer you, which I do as fast as I can, but not always easy due to the length, I would like to be sure you know what to do.

1. you can probably already add tests. I really would love to see tests, because that ensure that I finally am certain of what's the expected behavior. Plus, that'll force us to see what is required to create the test. For example, to ensure that when you start a new test, datastore is empty (and ideally that we only empty it at end of a test that have some datastore behavior, so that we don't pay extra cost in test)
2. You can also start already the UI to display and add decks to the data store. I suspect that you can do most of the UI with only the first two commits merged. So maybe it will be worth having a PR that only deals with `Datastore`. It can hopefully be merged faster (since it'll be quicker to review and we already agree on most of what should go in there). So that the current PR will only get 5 commits, and the UI can be done on top of it already
3. or whatever you consider the next step, I believe you can do it on top of this PR, assuming it won't change much, and even if it requires this entire PR to be merged, you can always put it in a draft PR

2022-08-22 05:58 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +     * Our configuration for custom work manager.
I think It is not right to specify only for Notification. We can use work manager at different location may be Sync

2022-08-22 06:05 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +        }.firstOrNull() ?: default
No issues, Done

2022-08-22 06:06 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +                throw Exception("Unable to find schedule data of given deck id: $did")
Done, Thanks

2022-08-22 06:07 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/DeckNotification.kt
> +        Long.MAX_VALUE,
Sure, Thanks for telling me

2022-08-22 06:23 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +     * Reschedule Next Worker.It is calculated on the basis of [NotificationTodo] data by [getTriggerTime]
Dpone

2022-08-22 06:46 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            Timber.v("Notifications disabled, returning")
****

2022-08-22 06:48 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        const val ONE_DAY_MS = ONE_HOUR_MS * 24
Added an new lambda funcation. 
``` 
 val ONE_DAY_MS: (calendar: Calendar) -> Long = {
            it.apply {
                add(Calendar.DAY_OF_YEAR, 1)
            }
            it.timeInMillis
        }
```

2022-08-22 06:50 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +     * Fire the notification for [deck] if needed.
Done. added

2022-08-23 19:12 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +            timeDeckData[it.key + ONE_DAY_MS] = it.value
``` 
This won't be valid due to time saving on the day of time change. You'll get the notification one hour later /sooner.
I know I mentioned only over a single use of + ONE_DAY_MS; I would have thought implicit that the same issue would occur everywhere.
```
Used Calendar

```
Actually, there is another issue here. Let's say your phone remained turned off for a full week. Your process will lead to have notification sent for 7 days ago, then it'll update the notification time for 6 days ago, then for 5 and so on.... You'll send 7 notifications for the same deck. I believe we should ensure that we only plan the next notification for a time in the future.

If we really want to merge it now, it requires at least a TODO
```
Thanks for pointing this out. I have a solution in my mind but I will Implement this in the future. added a TODO For not so that we can merge this now.

2022-08-23 19:19 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val topLevelDecks = sched.deckDueTree().map { it.value }
Thanks 
```
// Collect the deck details
        val topLevelDecks = try {
            withCol {
                val sched = sched
                sched.deckDueTree().map { it.value }
            }
        } catch (ex: Exception) {
            // Unable to access collection
            return Result.failure()
        }

        processSingleDeckNotifications(topLevelDecks)
        fireAllDeckNotification(topLevelDecks)
```
I think this works?

2022-08-23 19:21 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +class NotificationWorkManager(val context: Context, workerParameters: WorkerParameters) :
I think NotficationWorker look fine. Changed

2022-08-23 19:22 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +    override suspend fun doWork() = notifies().also {
Yup 🚀

2022-08-23 19:29 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val timeDeckDataToTrigger = timeDeckData.filterTo(HashMap()) { it.key.toLong() <= currentTime }
> Do you know whether they can be run in advance, or only after the schedule time?

No, the Notification manager cant trigger it in advance. I will trigger it after the given time

2022-08-23 19:31 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +            deckIdsToTrigger.remove(deck.did)
I am not closing this. I will optimize this in the future thanks for suggesting it.

2022-08-23 19:42 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        // Decks may have been deleted. This means that there are decks that should have been triggered but were not, which
Changed now pls check.

2022-08-23 19:48 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +            val nextTimeKey = allTimeDeckData.keys.firstOrNull { it.toLong() >= currentTime }
Changed this to 
> No deck within 1 hour. Restarting after 1 hour for all deck notification
```
That is to say, I'd suggest having a WorkerContext that contains the startTime and maybe whatever all data we may find relevant to put in a context eventually.
```
Did you mean to pass the start  time as a workerParameters in NotificationWorker?

2022-08-23 20:00 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +/**
> I'd like you to document, for any reader who don't know workers:

what occurs when the device is turned off at this time
why do we care about one hour when we know there is nothing to do

Added


> To the second question, I could assume that it matters if we add a new deck to review. But I don't understand when this occur why we wouldn't instead immediately schedule the worker if the new deck is the one coming the sooner.

While adding the new deck we are recalculating the new trigger time for deck notification and reschedule the worker.

>Plus, it seems that we are not searching for deck we didn't yet process, which led me to believe that this is not even why we start the worker in an hour.

If I got this right then we are starting the worker in hour because we want to trigger all deck notification. So if in case their is some pending deck to trigger then we are also processing it.

2022-08-23 20:06 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * @return [NotificationData] which contains schedule time and notification work type.
Done added.

2022-08-23 20:12 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            val initialDiff = nextTriggerTime - TimeManager.time.intTimeMS()
I my machine this commit is compiling.  I used initalDiff in line 185
>            startNotificationWorkManager(initialDiff, true)

2022-08-23 20:13 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        did: Long
Done

2022-08-23 20:17 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * Generally used when user time zone changes.
Added a comment here
> While scheduling the notification we saves the data in datastore So, Data in datastore will be always fresh.

I will take care of this in future.

2022-08-23 20:18 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            // Filtering all deck ids form the map
Done

2022-08-23 20:23 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * Start the new notification Work Manager.
Changed this. 
I did change the name very often so I forgot to rewrite the documentation from scratch.

2022-08-23 20:26 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        // Register the periodic work manager.
Changed this to
> Enqueue the periodic work manager.
Looks good?

2022-08-23 20:27 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * It will check internally that notification is enabled or not
Done

2022-08-23 20:28 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            Timber.v("Notifications disabled, returning")
Removed.

2022-08-23 20:32 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +         * @return epoch time in milliseconds
Done

2022-08-23 20:40 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +            Timber.d("Timezone: Current time -> $newCurrTimeMS Time difference -> $timeDiffMS")
Remove as I does'nt require anymore.

2022-08-23 20:48 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +                deckIds = deckIdsToTrigger.toArray(
Done

2022-08-23 20:49 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="all_deck_notification_new_title">>AnkiDroid reminder</string>
Done

2022-08-24 05:54 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +                newTimeDeckData.append(deckData.did, notificationData.scheduleTime)
> If you are recreating, why are you iterating over listOfDeck = oldTimeDeckData.values.flatten() instead of iterating over all top level decks.

As I am using the old-time deck data I contain all the decks whose notification is scheduled. So I am collecting all the deckids and recreating them.
See case:
I scheduled the notification at ms 1661320125132 i.r `August 24, 2022 11:18:45 AM`
and while scheduling new notification at ms 1661320125134 i.e `Wednesday, August 24, 2022 11:18:45 AM )` 
So in above case sched time is same but time in ms is different. So handle this case I am recreating each deckid notification from scratch,

2022-08-24 06:27 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/AndroidManifest.xml
> +        <receiver android:name=".receiver.TimeZoneChangeReceiver"
Done

2022-08-24 06:45 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val topLevelDecks = sched.deckDueTree().map { it.value }
val sched = sched is unnecessary

2022-08-24 09:44 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorkManager.kt
> +        val topLevelDecks = sched.deckDueTree().map { it.value }
Done

2022-08-29 18:45 UTC, Arthur-Milchior commented
@prateek-singh-3212 you got merge conflict, sorry

2022-08-29 21:49 UTC, Arthur-Milchior approved these changes
I've done the correction myself, since they don't fundamentally change your PR, so that we can move on to other things.

2022-08-29 21:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> + * If their is no deck notification within 1 hour then also notification work manager will run after 1 hour to trigger all deck notification.
there is

2022-08-29 21:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +            timeDeckData[ONE_DAY_MS(calendar).toString()] = it.value
ONE_DAY_MS is a really strange name. Not the way we call functions usually.
Plus, it has a side effect that is not documented, it change calendars.

Also, it's really strange to take a calendar and return a long.
I understand that you don't want to take a long, because you are reusing the same calendar over and over which saves time, so that's great. 

Since it's used a single time, I find this method too unatural to be worth it. 

`calendar.add(Calendar.DAY_OF_YEAR, 1)` above would suffice

2022-08-29 21:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +         * @return next trigger time in Milli Seconds.
milliseconds, a single word

2022-08-29 21:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +        val initialDiff = TimeManager.time.intTimeMS() - nextTriggerTime
In "implemented NotificationWorkManager Logic", we can't compile because this variable is unused. 
If you can't easily do it in one commit, please do either:
* `@Suppress("UNUSED_VARIABLE") val initialDiff = TimeManager.time.intTimeMS() - nextTriggerTime` so that it compiles
* or just timper the value, so that Kotlin see it's used.

Ideally, we really want each commit to compile, so that if we ever need to bisect, we don't fail.

I understand it's hard to check properly because of the number of changes we required.

2022-08-29 21:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            val initialDiff = nextTriggerTime - TimeManager.time.intTimeMS()
Sorry, I meant to note this on the `initialDiff` of  `rescheduleNextWorker`. 
Did you by accident compile the commit where "saveScheduledNotification" is added instead of the commit "implemented NotificationWorkManager Logic" I mentionned?

2022-08-29 21:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        CoroutineScope(Dispatchers.Default).launch {
Please don't resolve without correcting or explaining why you don't

2022-08-29 21:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * Work that needs to be so that notification should trigger.
to be done

So that notification CAN trigger.

It already should, even if no work is done. Simply, it can't trigger if the work is not done

2022-08-29 21:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +        // Creates an explicit intent for an DeckPiker Activity.
You don't need to indicate you "create". Just indicate what's the result in this variable, and only if the variable can't indicate explicitly. 
So no comment and `deckPickerIntent` should be sufficient

2022-08-29 21:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +        // Build the notification
Same here, I don't believe the comment add anything that the variable name don't already indicate.

2022-08-29 22:09 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            val initialDiff = nextTriggerTime - TimeManager.time.intTimeMS()
Yes, I misunderstood here. Done now

2022-11-10 14:28 UTC, Arthur-Milchior commented on AnkiDroid/src/main/AndroidManifest.xml
> +        <service
For the context, the commit that was commented and discussed here is https://github.com/ankidroid/Anki-Android/commit/257bb949313aaca19c954100c90e185631996fe8

2023-01-16 15:37 UTC, closed without merging