[Kotlin Cleanup] CardTemplateEditor
ankidroid/Anki-Android pull request #11481
Opened 2022-05-31 16:04 UTC by oyeraghib

## Purpose / Description
[Kotlin Cleanup] CardTemplateEditor

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-05-31 17:44 UTC, Arthur-Milchior requested changes

2022-05-31 17:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
>          if (supportActionBar != null) {
You can remove this if. The .? is already taking care of checking that this variable is nonNull

2022-05-31 17:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +            val m = Regex("(?s)(.+)<hr id=answer>(.+)").find(afmt)
In this case, I don't see the point of `when`. Even a `if m == null` would seems to make sense.

2022-05-31 17:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +    private lateinit var mSlidingTabLayout: TabLayout
When adding a lateinit; which is a case which can easily bug if done improperly, I really want your commit messages to explain how you did ensure it work correctly. 
I'd have merged with each other remark and ask you to correct them later. This is the first issue that makes me block to merge this commit. In case of error, I really want the comment of commit to explain what was done to someone investigating a debug later.

By the way, as I probably already wrote, I love atomic PR. A lot of changes are unrelated and so could be done in many distinct PR. That would have allowed to merge those PR immediately and not block everything. Better, it would allow me not to review everything on the next round.

In case the reason you are making so little PR is because it requires too much work, you may want to consider https://github.com/cli/cli , which allows you, when you are on a working branch, to use `gh pr create` to create a pr automatically with the content of your branch

2022-06-01 17:19 UTC, oyeraghib commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +    private lateinit var mSlidingTabLayout: TabLayout
Yes I thought of making a new PR, but since it was just being used at one place I thought making a commit would be better. But yeah I will keep in mind to have atomic PR's in case of lateinit as it makes more sense. Thanks!

2022-06-01 17:34 UTC, oyeraghib commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +            if (this@CardTemplateEditor.editorPosition!![position] != null && this@CardTemplateEditor.editorViewId!![position] != null) {
Thanks for noticing it, actually I got a bit confused as this happened at the time of renaming the variable `private var mEditorViewId: HashMap<Int, Int?>? = null`. On further investigation I find that there is an another variable inside `createFragment()` called as `val editorViewId: Int`.

So it was added by the compiler to avoid any errors. But this makes the code little complicated to read so I would rather give the two variables different names instead of using `this@CardTemplateEditor`

2022-06-01 17:44 UTC, oyeraghib commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +            mTabLayoutMediator = TabLayoutMediator(mTemplateEditor.mSlidingTabLayout, mTemplateEditor.viewPager) { tab: TabLayout.Tab, position: Int ->
I have a question that what if in the future there is a requirement of `mSlidingTabLayout` at other places then it would need to be initialize globally again. So is it ideal to make it a local variable?

2022-06-01 18:05 UTC, oyeraghib commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +            if (this@CardTemplateEditor.editorPosition!![position] != null && this@CardTemplateEditor.editorViewId!![position] != null) {
Thanks for noticing actually it happened because of some wrong naming. I have fixed it with a commit.

2022-06-01 21:28 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +    private lateinit var mSlidingTabLayout: TabLayout
I beg your pardon, If was unclear.
I don't require atomic PR for lateinit. I believe they are a good idea in general, but not mandatory. My point is only that, in this case, it would have avoided blocking other commits.

My main point is really that your commit should really explain why lateinit is valid to be clear

2022-06-01 21:34 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +            mTabLayoutMediator = TabLayoutMediator(mTemplateEditor.mSlidingTabLayout, mTemplateEditor.viewPager) { tab: TabLayout.Tab, position: Int ->
Good point. It's true that it is not an absurd hypothesis that it'll eventually be needed. 
I guess the main issue is that we are not proper MVC or any other settings, so it was not obvious to me we want to keep access to all part of the current view. 
i'll go with implementor choice here

2022-06-02 01:42 UTC, oyeraghib commented
> You have a conflict.
> 
> Given that I agreed with a remark you made and have a conflict, I'll wait until you resolve it and let me know whether you are done before reviewing again this commit

I fixed the conflict. It was due to the change in variable names.

2022-06-02 09:27 UTC, Arthur-Milchior requested changes
Please rebase onto ankidroid/main, instead of merging.

2022-06-02 09:27 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +            val m = Regex("(?s)(.+)<hr id=answer>(.+)").find(afmt)
In this case, I'd love you to edit the commit where you were adding the `when`, so that it's not added in the history of ankidroid just to be removed. Instead you added it in the commit just after that

2022-06-02 09:27 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +    private lateinit var mSlidingTabLayout: TabLayout
and in this case, I still don't see a comment in the commit message explaining why it work. In this case, you can do rebase interactive and just change the commit message

2022-06-02 09:27 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> -    private var editorPosition: HashMap<Int, Int?>? = null
I love this change.
However, in this case, it would be really really nicer to have ONE name change by commit.
I assume you use the "rename" feature of android-studio, so it's not that hard to recreate those commit hopefuly. But right now, I can't easily check that all renames were done properly; while on the other hand with one name change by commit, it becomes trivial to review

2022-06-02 09:27 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> -    @KotlinCleanup("Unchecked cast")
I'd love if you could either:
* remove it in the commit where the issue is solved
* note in the commit message the id of the commit where the issue was removed (which may mean to remove one cleanup message by commit, for the sake of clarity)

2022-06-02 19:32 UTC, oyeraghib commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +            mTabLayoutMediator = TabLayoutMediator(mTemplateEditor.mSlidingTabLayout, mTemplateEditor.viewPager) { tab: TabLayout.Tab, position: Int ->
_"i'll go with implementor choice here"_ I am sorry but what does that mean. Does it mean I should declare it as a local variable for the time being ?

2022-06-03 16:12 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +            mTabLayoutMediator = TabLayoutMediator(mTemplateEditor.mSlidingTabLayout, mTemplateEditor.viewPager) { tab: TabLayout.Tab, position: Int ->
"Implementor's Choice" means, reviewer does not feel strongly about it, and you are doing the work (you are the implementor) so pick your favorite from discussed solutions and go for it!

2022-06-03 17:03 UTC, oyeraghib commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +            mTabLayoutMediator = TabLayoutMediator(mTemplateEditor.mSlidingTabLayout, mTemplateEditor.viewPager) { tab: TabLayout.Tab, position: Int ->
Oh okay!!! Thanks a lot for making it clear.

2022-06-03 22:55 UTC, oyeraghib commented
@Arthur-Milchior I made the required changes, but I see that there are few conflicts. If I try to resolve these conflicts using `Resolve conflicts` here on GitHub I might end up merging them. But you said I should rather do rebase instead of merging. May I please know how do I do that here?

2022-06-04 14:25 UTC, Arthur-Milchior commented
Admittedly, I'm sorry, I fear it must be done on computer.

You can simply do `git pull --rebase` from command line, so that the pull is done with rebasing onto ankidroid's main (if you track it)

You can also do `git config pull.rebase true` to ensure that all pull are done with rebase.

If your local branch is not tracking ankidroid/main, you can also do `git rebase ankidroid/main` (assuming the remote from ankidroid is called ankidroid. If it is called "origin" then replace "ankidroid" by "origin")

Once everything is merged, you can do `git push --force-if-includes` to push back to the pull request. 


You may want to do `git config rerere.enabled true` first. This ensure that if you have the same conflict many time, you only have to solve it once. I doubt it'll be a problem with this PR, but when you have huge PR it can sometime help

2022-12-10 15:36 UTC, closed without merging