Update androidx.core:core-ktx dependency to 1.8.0
ankidroid/Anki-Android pull request #11509
Opened 2022-06-02 15:44 UTC by lukstbit

## Purpose / Description

This PR update the core-ktx dependency to the latest version(1.8.0 at this moment). This update produces some build errors due to some changes into the declared nullability in the library api:

- ActionProvider declares now onCreateActionView() as returning a non null value, I changed all the overrides to throw an error(to catch any issues now) which should be safe as the platform uses the version which takes a MenuItem
- IconCompat.createWithResource() now requires a non null Context which can be provided safely from where the method was used(DeckPicker.createIcon -> DeckPickerContextMenu)
- ConfigurationCompat.getLocales().getLocale() is declared now to return a nullable value, I added `!!` to keep the current code intact
- MenuItemCompat declares getActionProvider() now as returning a nullable value, in Reviewer where it is used I added `!!` which is safe because the MenuItems for which it is called get an ActionProvider set on them unconditionally

## Fixes

Closes #11505 

## How Has This Been Tested?

Ran the tests, used the area of the app touched by changes.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-02 15:55 UTC, mikehardy requested changes
I worry about the !!s ...

2022-06-02 15:55 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        return ConfigurationCompat.getLocales(resources.configuration)[0]!!
This and the other `!!` concern me. I'd prefer to never see a !! to be honest, unless it's accompanied with a comment explaining how and why in every case you know that you will not crash the app
I'd prefer a null check + fallback with logging

2022-06-02 15:55 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                if (!MenuItemCompat.getActionProvider(item)!!.hasSubMenu()) {
some comment explaining exactly why we know for certain the !! is safe seems appropriate, or perhaps a safer alternative would be an optional dereference `?` ?

!! means "if I haven't thought of something for some reason or if assumptions change in the future, let's just crash here" if I read it correctly

That's a pretty aggressive stance to take in code

2022-06-02 16:10 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                if (!MenuItemCompat.getActionProvider(item)!!.hasSubMenu()) {
The !! is safe **now** because both menu items get associated with an ActionProvider unconditionally so one will be available to retrieve there. I could do something like this to avoid !!:

```
MenuItemCompat.getActionProvider(item)?.hasSubMenu()?.let { isAvailable ->
                    if (!isAvailable) {
                        Timber.d("Bury card due to no submenu")
                        buryCard()
                    }
                }
```
or add a comment.

> That's a pretty aggressive stance to take in code

Someone changing code related to menu items has to check those menu items. A failure with !! signals an error pretty clear.

2022-06-02 16:24 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        return ConfigurationCompat.getLocales(resources.configuration)[0]!!
I've reviewed the code and walked the call stack and updated the nullability of the methods involved to take in consideration getLocales()[] possible returning null.

2022-06-02 16:36 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                if (!MenuItemCompat.getActionProvider(item)!!.hasSubMenu()) {
> A failure with !! signals an error pretty clear.

...at runtime, with a NullPointerException crash

> Someone changing code related to menu items has to check those menu items

I read this as: "if someone is changing code related to menu items, they *should* check ..."

I guess I've just seen so many NullPointerException runtime crashes in my life I just never want to see them again. Ever ever ever ever. I'd prefer defensive code

2022-06-02 16:42 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> -            return null // Just return null for a simple dropdown menu
We can't return null, both methods are annotated in the newer library version with @NonNull.

2022-06-02 18:47 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> -            return null // Just return null for a simple dropdown menu
It doesn't compile, `onCreateActionView(forItem: MenuItem?) : View?` fails for both the MenuItem and the return View being null, the correct signature of the method is:

`override fun onCreateActionView(forItem: MenuItem) : View = something`

This work just great and I think it improves the code:
```

/**
 * Fix for [ActionProvider]'s [ActionProvider.onCreateActionView] deprecation on API 16+
 *
 * @see ActionProvider
 */
abstract class ActionProviderCompat(context: Context): ActionProvider(context) {
    @Deprecated("Use onCreateActionView(item)")
    override fun onCreateActionView(): View {
        // This does not work in Kotlin 1.8 - previously we returned null here
        throw UnsupportedOperationException("This should no longer be called. onCreateActionView(item) should be used")
    }
}
```
using it as a superclass for our implementations.

2022-06-02 18:51 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> -            return null // Just return null for a simple dropdown menu
Gah, was on the wrong branch, that seems like a good compromise

2022-06-02 18:56 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> -            return null // Just return null for a simple dropdown menu
Thanks a ton for working through this @lukstbit - really appreciated

2022-06-02 19:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> -            return null // Just return null for a simple dropdown menu
+1, massively appreciated for going through these

2022-06-03 08:14 UTC, lukstbit commented
@mikehardy @david-allison I pushed a commit with the requested changes, I think every raised issue was addressed.

2022-06-03 14:04 UTC, mikehardy approved these changes
Fantastic, now when I look through my pessimistic-crystal-ball looking for future crashes, no matter how rare, even the pessimistic-crystal-ball shows a sunny day. And the comments are pretty clear too, thank you!

David's comments were all addressed as well

2022-06-03 14:04 UTC, merged