[GSoC] Extract sync preferences to a new category
ankidroid/Anki-Android pull request #11512
Opened 2022-06-02 22:36 UTC by BrayanDSO

## Purpose / Description
Create a separate preferences category for the sync preferences

## Approach
On the commits

## How Has This Been Tested?

<details><summary>On my phone</summary>

![Screenshot_20220602-193336_AnkiDroid](https://user-images.githubusercontent.com/69634269/171749315-b6a0f7a4-c9ba-4484-82b7-b7da9fa4b501.png)

![Screenshot_20220602-191356_AnkiDroid](https://user-images.githubusercontent.com/69634269/171748662-955189b5-73e0-44d5-92b4-38e76d034258.png)

![Screenshot_20220602-191404_AnkiDroid](https://user-images.githubusercontent.com/69634269/171748670-7b6eb236-1211-4ed8-a8d7-a8096885087c.png)

![Screenshot_20220602-193305_AnkiDroid](https://user-images.githubusercontent.com/69634269/171749320-02e398cf-0627-496f-85f7-be43bf4e5e49.png)

</details>

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-02 23:12 UTC, david-allison requested changes
In addition: could we get a quick screenshot of the UI change

2022-06-02 23:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +        protected fun <T : Preference?> requirePreference(resId: Int): T {
can `@StringRes` be used on this parameter

2022-06-02 23:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +         * by the key defined with given resource Id, or throws  */
I think this doc could explain it a little better, as it's a GREAT helper method.

Could you give a code example in the docs, and link to the file which contains the constant

2022-06-02 23:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt
> -            if (isDisabled) {
I would like to see this in a separate PR so this doesn't block a change that I generally agree with

We did have complaints about the badge not being dismissible if the user does not have an account, and I feel that's a valid 'annoying' use case (we probably can do better than a preference, but there's a better UX than just removing the feature)

2022-06-02 23:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +        fun buildSummary(vararg strings: String): String {
nit: maybe a little consideration on the name, unsure here and I'm fine for it to go in as-is as the documentation is great. Maybe `buildCategorySummary`?

I'd be fine with this being `internal` and `@VisibleForTesting`

2022-06-02 23:12 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/PreferencesTest.kt
> +        assertThat(Preferences.buildSummary(*strings), equalTo(expected_summary))
Lovely stuff

2022-06-03 08:29 UTC, BrayanDSO commented
> In addition: could we get a quick screenshot of the UI change

There are four on the PR text under a details tag

2022-06-03 08:55 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +         * by the key defined with given resource Id, or throws  */
Done

2022-06-03 10:16 UTC, david-allison approved these changes

2022-06-03 10:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +         * the preference whose key is `@string/day_theme_key`
in `values/preferences.xml`

2022-06-03 13:44 UTC, mikehardy requested changes
I question on RTL languages, otherwise seems sensible

2022-06-03 13:44 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +            return strings.joinToString(separator = " • ")
How does this handle RTL languages like Hebrew or Arabic?

Checking it from Character seems to be the right way, e.g. https://stackoverflow.com/a/23203698/9910298 - there are notes about TextUtilsCompat being dangerous in this case because it's not just 'L' or 'R', there is also 'AR' and TextUtilsCompat misclassifies, according to random people on stackoverflow

2022-06-03 15:39 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +            return strings.joinToString(separator = " • ")
TBH, I'm not sure if it's being handled correctly, but it is seems that the elements already being added from right to left somehow (I've built a test case which shows it better). 

I may be wrong, but I really can't tell with my complete ignorance about RTL languages.


![Screenshot_20220603-123144_AnkiDroid](https://user-images.githubusercontent.com/69634269/171892866-7410a07b-17bb-48ff-b177-4477ecfe9fbf.png)

2022-06-03 16:02 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +            return strings.joinToString(separator = " • ")
Mmmm - maybe it's because we build the string RTL, but the string is reversed on display, correctly?
We need a goto speaker from this list I think :sweat_smile:  https://www.worldatlas.com/articles/which-languages-are-written-from-right-to-left.html

2022-06-03 16:19 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +            return strings.joinToString(separator = " • ")
GitHub and IDE are displaying the test differently, so I'm quite confused.

After following GitHub's text order and some logic, I *think* I fixed it, and apparently is right on new screenshot, but I definetely can't know for sure

![Screenshot_20220603-130336_AnkiDroid](https://user-images.githubusercontent.com/69634269/171905387-c9c81640-d2fa-4aab-b908-1a0dfb997731.png)

2022-06-03 16:21 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +            return strings.joinToString(separator = " • ")
In another language, but with incomplete translations:

![Screenshot_20220603-120427_AnkiDroid](https://user-images.githubusercontent.com/69634269/171905728-4766a937-2f63-4206-a2d6-e61cd1d2d874.png)

2022-06-03 16:49 UTC, mikehardy approved these changes
That looks exactly like what I'd expect, now that I've read one stack overflow question answer and thus am an expert in detection of RTL ;-)

2022-06-03 16:51 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/PreferencesTest.kt
> +    @Config(qualifiers = "ar")
this is great by the way - not just the test but if you think about the ridiculous mountain of framework you're sitting on with robolectric etc, and you just have to say, "make it arabic this time" ;-)

2022-06-03 17:02 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +            is SyncSettingsFragment -> getString(R.string.pref_cat_sync)
I think an issue about this needs to be raised. (Something like https://github.com/ankidroid/Anki-Android/issues/11449)
Because there are 100+ occurrences of `resources.getString`. It isn't something major but it will look clean.

2022-06-03 19:00 UTC, merged