WindowInsets
ankidroid/Anki-Android pull request #11531
Opened 2022-06-04 21:37 UTC by n1snt

## Purpose / Description
Deprecated UI flags were replaced by WindowInsets.

## Fixes
Fixes #9332

## How Has This Been Tested?
Ran tests & tested on:
- Physical Device (Android 12)
- Virtual Device (Android 7)

## Learning (optional, can help others)
I read [this ](https://medium.com/swlh/modifying-system-ui-visibility-in-android-11-e66a4128898b) guide & went through [this ](https://github.com/ankidroid/Anki-Android/pull/9406) pull request.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-05 15:19 UTC, mikehardy requested changes
Hey - this looks like a good start but not exactly the way Compat works. Probably  not too hard to reshape until it does work right though, it appears you have done the hard part of figuring out how the new API30 insets are supposed to work already and that is most of the task I think

2022-06-05 15:19 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
> +        sdkVersion >= Build.VERSION_CODES.R -> CompatV30()
```suggestion
        sdkVersion >= Build.VERSION_CODES.R -> CompatV30()
        sdkVersion >= Build.VERSION_CODES.Q -> CompatV29()
        sdkVersion >= Build.VERSION_CODES.O -> CompatV26()
        sdkVersion >= Build.VERSION_CODES.M -> CompatV23()
```

These must be in decreasing order or the fall through doesn't work correctly

2022-06-05 15:19 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV30.kt
> +class CompatV30 : CompatV26(), Compat {
```suggestion
class CompatV30 : CompatV29(), Compat {
```

must extend the next lower-one for the overriding to chain correctly and include the 29 overrides (and 28, and 27) vs 26

2022-06-05 15:19 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
I don't understand why you have implemented the Compat base implementation (21) and "new style" (30) but then have a VERSION_CODES check here? It seems like you implemented the Compat stuff mostly correctly (the version chaining was off - but that's a quick fix) but then did not use it?

use the Compat stuff here and implement it in such a way that you do not need a version check - you just call the methods on the Compat object returned from CompatHelper and then this should shrink down a lot, with all the complexity in CompatV21/CompatV30

2022-06-12 11:52 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
> +        sdkVersion >= Build.VERSION_CODES.R -> CompatV30()
Done.

2022-06-12 11:52 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV30.kt
> +class CompatV30 : CompatV26(), Compat {
Done.

2022-06-12 11:53 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
I have removed the VERSION_CODES checks.
But I'm not sure if I have done it correctly.
Can you please check this.

2022-06-15 10:16 UTC, david-allison reviewed
Definite request; `CompatV31` needs to inherit from `CompatV30`.

I don't think the code is correct now for V21-V29.

Could a few videos be shown with the full screen behaviour?

2022-06-15 10:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> -            }
This logic doesn't seem to map to the new compat code

2022-06-27 15:29 UTC, david-allison commented
I know the feeling! no rush

2022-12-08 05:04 UTC, n1snt commented
I forgot about this issue. Will fix the merge conflicts & start working on it again once I'm done with my exams.

2023-02-13 07:36 UTC, closed without merging