fix: exit message when using the review shortcut
ankidroid/Anki-Android pull request #11547
Opened 2022-06-05 19:06 UTC by fred-sab

## Purpose / Description
When using a [shortcut](https://developer.android.com/guide/topics/ui/shortcuts) for review, we may need to inform the user when exiting the activity:
- If we successfully completed the review (otherwise the user is surprised of the sudden exit #10841)
- If there's nothing to review (otherwise the user doesn't understand why the app just opens and closes #10840)

The shortcuts were recently introduced with #8648.

## Fixes
Fixes #10841: display a message when the review is completed
Partially fixes #10840: display a message when no card to review (but ideally the message should be "no cards to review" rather than "review finished")

## Approach
As suggested [here](https://github.com/ankidroid/Anki-Android/issues/8648#issuecomment-822581182), use a Toast to inform the user.

#10840 and #10841 suggested to return to the main view when finishing. 
However, in my opinion, the purpose of shortcuts is to quickly perform the desired action (add note, review, view notes). Therefore, exiting when finishing or having no cards to review is more coherent, wdyt?
Also, the current approach allows to keep the complexity minimal.

## How Has This Been Tested?
- With a Pixel 5 API 31 Emulator
- With a Samsung Galaxy S7

Test that a message is displayed when the review is completed #10841:
![10841_review_completed](https://user-images.githubusercontent.com/88279943/172066030-f55ed082-0211-463b-bc51-9db2343d2dbd.gif)

Test that a message is displayed when nothing to review #10840:
![10840_no_card](https://user-images.githubusercontent.com/88279943/172066037-cf1ff507-12bd-4fa5-aec6-3ba0a1c12cc7.gif)

## Learning (optional, can help others)
About shortcuts: https://developer.android.com/guide/topics/ui/shortcuts

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars). 
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)
  - Is it relevant for this change?

2022-06-05 19:12 UTC, mikehardy approved these changes
This seems like a nice approach to me, and is a nice small + tidy change

2022-06-05 19:40 UTC, david-allison requested changes
Looks great, thanks! One minor request so we can improve testing in future

2022-06-05 19:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +                if (intent.getBooleanExtra(EXTRA_STARTED_WITH_SHORTCUT, false)) {
Very minor: could you add a `@NeedsTest("explanation")` annotation to the the top of the method where you've added the functionality

2022-06-06 19:47 UTC, fred-sab commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +                if (intent.getBooleanExtra(EXTRA_STARTED_WITH_SHORTCUT, false)) {
I added a test instead, does it look good to you?

2022-06-07 17:53 UTC, david-allison requested changes
Absolutely going above & beyond! One nitpick to allow the tests to run on non-English machines (this may not be necessary)

2022-06-07 19:14 UTC, david-allison approved these changes
Beautiful, if tests pass, I'm happy

2022-06-07 19:17 UTC, fred-sab commented on AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
> +    fun shortcutShowsToastOnFinish() {
Thanks for the hint! And referencing the resource string seems like a good practice :)

2022-06-07 19:27 UTC, mikehardy approved these changes
really nice!

2022-06-09 13:08 UTC, merged

2022-06-09 13:09 UTC, david-allison commented
Thanks so much for this!