upload, build, download and update translations to/from Crowdin using js client api
ankidroid/Anki-Android pull request #11557
Opened 2022-06-06 11:43 UTC by krmanik

## Pull Request template

## Purpose / Description
Move to new Crowdln JS Client API

## Fixes
Fixes #8274

## Approach
1. Created a yarn project in `tools/localization` dir
```
mkdir ./tools/localization
cd ./tools/localization
mkdir src
yarn init
```

2. Installed required dependencies
```
yarn add @crowdin/crowdin-api-client
```
3. Created following files in src dir
**`index.ts`**:  For running functions defined below files
**`upload.ts`**:  For uploading English res/values files to Crowdin
**`download.ts`**:  For building/downloading English res/values files to Crowdin
**`update.ts`**:  For updating the files from extracted ankidroid.zip file

4. Updated `sync_translations.yml` file
5. The script in `ts` files are line to line conversion of python code to typescript

## How Has This Been Tested?
It is tested on local repository.  (Needs to add `tests` dir with test script and sample xml `files`)
**Actions result**
https://github.com/krmanik/Anki-Android-Copy/runs/6754662446?check_suite_focus=true

**PR result**
https://github.com/krmanik/Anki-Android-Copy/pull/10

**i18n_sync branch**
https://github.com/krmanik/Anki-Android-Copy/compare/main...i18n_sync

(_Change i18n_sync are all in English because not translated_)

## Learning (optional, can help others)
https://yarnpkg.com/cli/install
https://www.typescriptlang.org/docs/
https://github.com/crowdin/crowdin-api-client-js
https://support.crowdin.com/api/v2/#section/Introduction/Crowdin-API-Clients

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-06 12:07 UTC, krmanik commented on tools/localization/src/upload.ts
> +const projectId = 520224;
needs to change project id

2022-06-06 12:08 UTC, krmanik commented on tools/localization/src/update.ts
> +                let regexp = new RegExp(/%[0-9]s\$/g);
update regex for other invalid expression in files

2022-06-06 12:09 UTC, krmanik commented on tools/localization/src/update.ts
> +    } else {
else block can be removed (not sure)

2022-06-06 12:10 UTC, krmanik commented on tools/localization/src/update.ts
> +        if (language == "yu") {
needs to create this custom language on Crowdin

2022-06-06 12:26 UTC, david-allison commented on .github/workflows/sync_translations.yml
> +          git config --global user.email github-actions@github.com
Is there a reason to change this?

2022-06-06 12:26 UTC, david-allison commented on tools/localization/src/update.ts
> +        if (language == "yu") {
Cantonese: https://crowdin.com/project/ankidroid/yu

2022-06-06 12:29 UTC, krmanik commented on tools/localization/src/update.ts
> +        if (language == "yu") {
Thanks

2022-06-06 12:30 UTC, krmanik commented on .github/workflows/sync_translations.yml
> +          git config --global user.email github-actions@github.com
I will revert it, testing on local branch so changed

2022-06-06 12:30 UTC, david-allison reviewed
Looks great! Couple of questions

2022-06-06 12:30 UTC, david-allison commented on tools/localization/src/update.ts
> +                anyError = res;
Doesn't this want to be `|=`, if one fails, and the next succeeds, it succeeds

2022-06-06 12:36 UTC, krmanik commented on tools/localization/src/update.ts
> +                anyError = res;
It can be, will be updated.

2022-06-07 23:19 UTC, Arthur-Milchior commented
I'm looking at the API. It seems, if I understand correctly, that there is now a way to interact with screenshot too. If so, do you think you could, in another PR, maybe have a way to:
* download all screenshot (right now, I can't find a way to make a back-up. Which means if crowd-in stop, we lose hours of work)
* upload screenshot from PR; which will hopefully win a lot of time and avoid forgetting to do the work.

I'm still reviewing.

2022-06-07 23:43 UTC, david-allison commented
We do have a way to download screenshots, let's move this to: https://github.com/ankidroid/Anki-Android/issues/8621

2022-06-08 00:41 UTC, Arthur-Milchior reviewed
Thanks for the change. Clearly, it seems we are late to leave V1, so that's really cool you work on it. Thanks also because this lead me to learn things while reviewing it. I'm not that used to JS to be honest. So having to open JS file in intellij tool, and check the API description from crowdin is a new experience that is nice to have

I reviewed up to "fix regex, string replacement" and then I discovered that some of the questions from early commits were already answered in later one. 
It seems like still there are some suggestions and question that are still relevant now.
I'll do another pass when I get feedback on those first questions and remarks, so that I can use your experience to improve my review
I thought it was atomic commits, as often here. Is it instead supposed to be a single squashed commit where everything should be reviewed together?

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +const fileNames = ['01-core', '02-strings', '03-dialogs', '04-network', '05-feedback', '06-statistics', '07-cardbrowser', '08-widget', '09-backup', '10-preferences', '11-arrays', '14-marketdescriptio
Same for this in a separate constant file

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +const languages = ['af', 'am', 'ar', 'az', 'be', 'bg', 'bn', 'ca', 'ckb', 'cs', 'da', 'de', 'el', 'eo',
I'm really note fan. I guess it'd be nice to ask Crowdin whether they'd consider an api call to get list in which translation is started. 

It becomes important that anyone that can add more translation know they must edit this file
Looking at the list of current managers, I believe that @david-allison , @mikehardy and myself are the people who have the highest probability to add some new translation here.
I doubt Arthus, Hssm, Irfo, ospalh or Tim Rae ever does it. However, @nicolas-raoul still sometime answer email, and I honestly can imagine you'd be nice enough to a new translator to activate their language, without knowing the process changed. So just in case, this is a warning that if you ever want to help translators start, you should either edit this or let us know. (you can also remove yourself from a manager in the crowdin tool, so that we know you don't intend to do it.)

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +async function replacechars(fileName: string, fileExt: string, isCrowdin: boolean) {
replaceChars.
Please add a comment also

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/upload.ts
> +                    fs.readFile(I18N_FILE_SOURCE_NAME, {encoding: 'utf-8'}, function(err, data){
Implementor choice.
readFile has `__promisify__`. I'd find it nicer in general to use `then` and `catch`

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +                line = "<?xml version=\"1.0\" encoding=\"utf-8\"?> \n <!--\n ~ THIS IS AN AUTOMATICALLY GENERATED FILE. PLEASE DO NOT EDIT THIS FILE. \n ~ 1. If you would like to add/delete/modify th
I'd suggest

```js
line = `<?xml version="1.0" encoding="utf-8"?> 
 <!--
 ~ THIS IS AN AUTOMATICALLY GENERATED FILE. PLEASE DO NOT EDIT THIS FILE. 
 ~ 1. If you would like to add/delete/modify the original translatable strings, follow instructions here:  https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#adding-translations  
 ~ 2. If you would like to provide a translation of the original file, you may do so using Crowdin. 
 ~    Instructions for this are available here: https://github.com/ankidroid/Anki-Android/wiki/Translating-AnkiDroid. 
 ~    You may also find the documentation on contributing to Anki useful: https://github.com/ankidroid/Anki-Android/wiki/Contributing   
 ~ 
 ~ Copyright (c) 2009 Andrew <andrewdubya@gmail> 
 ~ Copyright (c) 2009 Edu Zamora <edu.zasu@gmail.com> 
 ~ Copyright (c) 2009 Daniel Svaerd <daniel.svard@gmail.com> 
 ~ Copyright (c) 2009 Nicolas Raoul <nicolas.raoul@gmail.com> 
 ~ Copyright (c) 2010 Norbert Nagold <norbert.nagold@gmail.com> 
 ~ This program is free software; you can redistribute it and/or modify it under 
 ~ the terms of the GNU General Public License as published by the Free Software 
 ~ Foundation; either version 3 of the License, or (at your option) any later 
 ~ version. 
 ~ 
 ~ This program is distributed in the hope that it will be useful, but WITHOUT ANY 
 ~ WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
 ~ PARTICULAR PURPOSE. See the GNU General Public License for more details. 
 ~ 
 ~ You should have received a copy of the GNU General Public License along with 
 ~ this program.  If not, see <http://www.gnu.org/licenses/>. 
 -->
`
```
to avoid \n and escaping double quote

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +                // line = line.replace('amp;', '');
please delete it if you don't use it.

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +                    line = "    <item>0</item>\n";
I'd really appreciate a comment explaining what's going on here. I assume there is a good reason, but I can't guess it

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +                line = line.replace('\'', '\\\'');
may I suggest using double-quote on the outside, so that you don't have to escape the single-quote?

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +                let regexp = new RegExp('%[0-9]\\s\\$|%[0-9]\\$\\s');
Can I ask for a comment detailing the meaning in English? So that instead of trying to decipher, I just try to check whether I agree that it's doing what is intended

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +            console.log(line);
I understand line was changed, but do you really want to log it twice?
Maybe just log it a second time iff it changed, to limit log duplicate

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +                line = "<?xml version=\"1.0\" encoding=\"utf-8\"?> \n <!--\n ~ THIS IS AN AUTOMATICALLY GENERATED FILE. PLEASE DO NOT EDIT THIS FILE. \n ~ 1. If you would like to add/delete/modify th
Same suggestion with other big block

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +                line = "<?xml version=\"1.0\" encoding=\"utf-8\"?> \n <!--\n ~ THIS IS AN AUTOMATICALLY GENERATED FILE. PLEASE DO NOT EDIT THIS FILE. \n ~ 1. If you would like to add/delete/modify th
I'd also suggest removing the copyright header here. In most files, none of those people wrote any words, nor the scripts generating those files. It seems stranger to quote them here than not to

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +    } else {
In this case, I'll skip the review for now. It's already long enough

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +function createIfNotExisting(directory: string) {
`createDirIfNotExisting`. Just for extra clarity during reading or autocompletion

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +        let olfFile = path.join(__dirname, '../../../docs/marketing/localized_description/oldVersionJustToCompareWith.txt');
nit: oldFile

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +                start = content.search('\",\"') + 3;
Why do you escape this double quote while not being in a double quoted string?

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +        if (!anyError) {
It seems wrong. It's probably if anyError is true that you want to log an error

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +        if (language == "yu") {
Maybe a switch would be better here

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +        if (localizedRegions.includes(language.split("-", 1)[0])) {
I'd add a variable
`let languageCode = language.split("-", 1)[0]`
just for readability

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +            console.log("At least one file of the last handled language contains an error.");
console.error

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +let anyError = false;
It seems it's used in a single function. So maybe it don't have to be file level

2022-06-08 00:41 UTC, Arthur-Milchior commented on tools/localization/src/update.ts
> +            await update(valuesDirectory, f, content, fileExt, true, language).then(res => {
Can't it be simplified into res = await update ...

2022-06-08 00:47 UTC, mikehardy commented on tools/localization/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
re point 1 - it's traditional in projects to commit the yarn.lock file
re point 2 - it's true that any commit which changes package.json (where dependencies are defined) should go with it's correct/current-at-time-of-that-package.json yarn.lock change, is that not the case here? If there was no change in package.json I expect the  yarn.lock would not change either. I haven't reviewed, but that's the general way it goes

2022-06-08 00:51 UTC, mikehardy commented on tools/localization/src/upload.ts
> +                    fs.readFile(I18N_FILE_SOURCE_NAME, {encoding: 'utf-8'}, function(err, data){
or just readFileSync since from a human perspective this is all blocking https://nodejs.org/api/fs.html#fsreadfilesyncpath-options

2022-06-08 10:05 UTC, krmanik commented
I went through each review and updated it. If I missed any review let me know.

2022-06-08 10:29 UTC, krmanik commented
Getting url undefined errors, may be 30 minutes wait.

```
$ node ./dist/index.js download
downloading...
Building ZIP on server...
Built.
Downloading Crowdin file
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at Url.parse (node:url:168:3)
    at Object.urlParse [as parse] (node:url:155:13)
    at dispatchHttpRequest (/home/runner/work/Anki-Android-Copy/Anki-Android-Copy/tools/localization/node_modules/axios/lib/adapters/http.js:133:22)
    at new Promise (<anonymous>)
    at httpAdapter (/home/runner/work/Anki-Android-Copy/Anki-Android-Copy/tools/localization/node_modules/axios/lib/adapters/http.js:4[9](https://github.com/krmanik/Anki-Android-Copy/runs/6791577721?check_suite_focus=true#step:9:10):[10](https://github.com/krmanik/Anki-Android-Copy/runs/6791577721?check_suite_focus=true#step:9:11))
    at dispatchRequest (/home/runner/work/Anki-Android-Copy/Anki-Android-Copy/tools/localization/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/home/runner/work/Anki-Android-Copy/Anki-Android-Copy/tools/localization/node_modules/axios/lib/core/Axios.js:109:[15](https://github.com/krmanik/Anki-Android-Copy/runs/6791577721?check_suite_focus=true#step:9:16))
    at wrap (/home/runner/work/Anki-Android-Copy/Anki-Android-Copy/tools/localization/node_modules/axios/lib/helpers/bind.js:9:15) {
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 1.
```

2022-06-08 10:51 UTC, krmanik commented on tools/localization/src/upload.ts
> +                continue;
Not correct.

2022-06-25 16:51 UTC, mikehardy commented on tools/localization/src/index.ts
> -uploadI18nFiles();
historically in typescript we (that is: every typescript project I work on across lots of teams, so "we" as in "typescript users") use "[prettier](https://prettier.io/)" - either with pure default settings or maybe some minor tweaks, and then there is no discussion of spacing, you just auto-format. Probably best to integrate it exactly as ankitects does since we will share code and they have it installed with this config already https://github.com/ankitects/anki/blob/main/.prettierrc

2022-06-25 17:38 UTC, mikehardy requested changes
I feel like all of my comments were either sort of "structural" or minor, with the exception of the "maybe ESM works?" request for an attempt

In general this looks pretty close to good, I'm excited to get it merged and have the translations stuff in a language I prefer more and which will share skillsets with "modern" Anki (typescript) vs python which I am always a bit lost in...

2022-06-25 17:38 UTC, mikehardy commented on tools/localization/src/index.ts
> +            console.log("uploadin...");
```suggestion
            console.log("uploading source strings to crowdin...");
```

2022-06-25 17:38 UTC, mikehardy commented on tools/localization/src/index.ts
> +            console.log("downloading...");
```suggestion
            console.log("requesting fresh translation build and downloading from crowdin...");
```

2022-06-25 17:38 UTC, mikehardy commented on tools/localization/src/index.ts
> +            console.log("extracting...");
```suggestion
            console.log("extracting downloaded translation bundle to temporary directory...");
```

2022-06-25 17:38 UTC, mikehardy commented on tools/localization/src/index.ts
> +            console.log("updating...");
```suggestion
            console.log("Copying downloaded translations to android resources directories...");
```

2022-06-25 17:38 UTC, mikehardy commented on .github/workflows/sync_translations.yml
> +          sudo npm install yarn -g
I think if we do this it is cross-platform, [18 is already "current" and will be LTS in a couple months](https://nodejs.org/en/about/releases/) so best to try now?, and yarn (1.2.x) is installed on the machines already (for [macos](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md) and [ubuntu](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2204-Readme.md) virtual environments)

```suggestion
      - uses: actions/setup-node@v3
        with:
          node-version: 18
```

2022-06-25 17:38 UTC, mikehardy commented on tools/localization/tsconfig.json
> +    "module": "commonjs",                                /* Specify what module code is generated. */
This is speculative! It may not work. However since we are starting from scratch here I would really like to base this off ESM modules if possible, otherwise it will be a job to do later, and we'll have to re-test everything https://www.typescriptlang.org/docs/handbook/esm-node.html

```suggestion
    "module": "node16",                                /* Specify what module code is generated. */
```

I think this will imply some alteration to the package.json and maybe to the import/export statements, but since we are still testing everything here anyway, this is a good time to try it? :crossed_fingers:

2022-06-25 17:38 UTC, mikehardy commented on .github/workflows/sync_translations.yml
> +    runs-on: ubuntu-latest
There was a reason for running it on macos vs ubuntu:

https://github.com/ankidroid/Anki-Android/blob/dab8245d76ff4eb854a233110a301735b60096de/tools/find-broken-strings-variables.sh#L23

Which was called here:

https://github.com/ankidroid/Anki-Android/blob/dab8245d76ff4eb854a233110a301735b60096de/tools/update-localizations.py#L227-L229

But it does not look like it is called anymore? That should be run as a workflow step I suppose, before the git commit - around line 66 in this workflow as currently committed here?

2022-06-25 17:38 UTC, mikehardy commented on .github/workflows/sync_translations.yml
> +      - name: Commit changes
this is about the spot to run the find-broken-strings-variables.sh script and check it for exit value, implying macos runner as mentioned above

2022-06-25 17:38 UTC, mikehardy commented on tools/localization/src/download.ts
> +const extract = require('extract-zip');
if we try ESM modules, this require may need to change to an await or something but I think node 14+ / typescript 3.8+ has top level await so that works. should work...

2022-06-25 17:38 UTC, mikehardy commented on tools/localization/src/update.ts
> +async function replacechars(fileName: string) {
Arthur noticed this the casing, I also propose strongly typing the return value, I think it is boolean?

```suggestion
async function replaceChars(fileName: string): boolean {
```

2022-06-25 17:38 UTC, mikehardy commented on tools/localization/src/update.ts
> + * @returns correct/replaced strings in the files
```suggestion
 * @returns boolean true if any corrections were made, false if no corrections were needed
```

2022-06-25 17:38 UTC, mikehardy commented on tools/localization/package.json
> +    "ts-node": "^10.8.1"
`yarn add --dev prettier`, pull this config file https://github.com/ankitects/anki/blob/main/.prettierrc and a script entry "format" that runs prettier in write mode 

Also - same idea - perhaps eslint+eslint-config-prettier+eslint-plugin-prettier, same .prettierrc and something like this setup with a lint:js target? https://github.com/invertase/react-native-google-mobile-ads/blob/main/package.json#L70

2022-06-26 18:22 UTC, krmanik commented on .github/workflows/sync_translations.yml
> +          sudo npm install yarn -g
This is better way to setup nodejs. Thanks

2022-06-26 18:25 UTC, krmanik commented on tools/localization/tsconfig.json
> +    "module": "commonjs",                                /* Specify what module code is generated. */
`node16` is showing errors, may be I have to use different options in setup in different file. I will check it. 

![Screenshot (1)](https://user-images.githubusercontent.com/12841290/175828691-1fe70b4c-2c81-453e-a996-52fa24f53908.png)

2022-06-26 18:26 UTC, krmanik commented on .github/workflows/sync_translations.yml
> +    runs-on: ubuntu-latest
I have added `find broken strings` before commit in yml file.

2022-06-26 18:26 UTC, krmanik commented on .github/workflows/sync_translations.yml
> +      - name: Commit changes
Done

2022-06-26 18:36 UTC, krmanik commented
I get following messages in `Find broken strings` in this [actions results](https://github.com/krmanik/Anki-Android-Copy/runs/7062582182?check_suite_focus=true) and actions run on macos. So it is ok?
```
Found grep errors but if you are not on macOS they are likely false positive. Ignoring
No issues found.
Exiting with status 0
```

Also first run gave following errors, after re-run it run successfully.
```
node ./dist/index.js download
downloading...
Building ZIP on server...
Built.
Downloading Crowdin file
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
```

2022-06-26 19:33 UTC, mikehardy commented on tools/localization/tsconfig.json
> +    "module": "commonjs",                                /* Specify what module code is generated. */
Yes - this part is the most experimental. Please don't spend too much time on it, I think it would be a positive to have ESM modules in use but I personally would put like a 10-15 minute time box on it to try, then if I didn't have it working would just say "well, maybe next time..." and move on without it

2022-06-28 21:34 UTC, mikehardy commented
> Found grep errors but if you are not on macOS they are likely false positive. Ignoring

:weary: - ugh, that whole script may be bogus now, I can't remember the last time it flagged anything, perhaps we are ignoring it completely in current execution as well so adding it has no real value? I'm not sure. If you look in there and discover either a) we're ignoring it full time in current i18n sync or b) it's worthless for some other reason, maybe just kill the script (don't use it / delete it)

If node16 is still not working, don't worry about it, bail and just use the "regular" (non-ESM) modules now

```
Building ZIP on server...
Built.
Downloading Crowdin file
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
```

That's worrisome. Does it happen every time ?

2022-06-28 21:37 UTC, mikehardy reviewed
I don't see anything in here in the code at the moment. Just some questions on the find broken translations script (maybe delete?) and the error you mentioned

2022-06-29 14:59 UTC, krmanik commented
> I don't see anything in here in the code at the moment. Just some questions on the find broken translations script (maybe delete?) and the error you mentioned

I have removed `find broken string` from yml. I think script can be translated to TypeScript for finding broken string.
The error occurs often I think some wait time need to add using timeout function. I am testing it.
Now it needs to add test for comparing result with correct xml file and replacement using regex.

2022-08-16 10:53 UTC, krmanik commented
I have used setInterval to wait for building the translations which takes approx. 1 min. Then download the build translations. The error now fixed. Now next is fixing the broken strings using typescript.

2022-08-28 05:37 UTC, krmanik commented
I have used https://regexr.com/6spn2 to build regex for matching broken strings. It should be added more to regex for matching more broken strings.

2022-08-29 14:44 UTC, david-allison commented
> I have used https://regexr.com/6spn2 to build regex for matching broken strings. It should be added more to regex for matching more broken strings.

This class/documentation may be of use. It's originally converted from the C++ which handled 'valid' format string testing:

 https://github.com/ankidroid/Anki-Android/blob/f40239ddadd0c57d053c3ce5fbe313f5c42b40b5/lint-rules/src/main/java/com/ichi2/anki/lint/utils/Aapt2Util.kt#L51

2022-08-29 15:10 UTC, krmanik commented
I think `Aapt2Util.kt` and `NonPositionalFormatSubstitutionsTest.kt` should translated to typescript used because regex approach may be not find errors. For e.g. `%s %s`, I will try to translate it to typescript. 
Thanks

2022-08-29 15:52 UTC, david-allison commented
> I think `Aapt2Util.kt` and `NonPositionalFormatSubstitutionsTest.kt` should be translated to TypeScript because regex approach may be not find errors, for e.g. `%s %s`. I will try to translate it to typescript. Thanks

I'd consider using https://cs.android.com/android/platform/superproject/+/master:frameworks/base/tools/aapt2/util/Util.cpp;drc=fbb7fe0da32896a871dd395845f1f510b075f8d5 as a base.

The C++ -> Java -> Kotlin probably wasn't the cleanest translation, and it may be a good idea to go to the original source

2022-08-29 16:54 UTC, krmanik commented
> I'd consider using https://cs.android.com/android/platform/superproject/+/master:frameworks/base/tools/aapt2/util/Util.cpp;drc=fbb7fe0da32896a871dd395845f1f510b075f8d5 as a base.
> 
> The C++ -> Java -> Kotlin probably wasn't the cleanest translation, and it may be a good idea to go to the original source

I will use the original source.

2022-09-07 06:09 UTC, david-allison commented
@krmanik Ready for review? Will you want this squashed or rebased when you're done?

2022-09-07 06:46 UTC, krmanik commented
It is not done yet, the check.ts file needs improvement. The check.ts file in tests dir fail on `pluralMultiple` and `validStr`. I am trying to fix it but not passing the tests.

```pwsh
PS C:\Users\mani\Documents\GitHub\Anki-Android\tools\localization> ts-node ./tests/check.ts

Assertion failed: [pluralMultiple] <plurals name="reschedule_card_dialog_interval">
    <item quantity="one">Current interval: %d day</item>
    <item quantity="few">Keisti Kortelių mokymosi dieną</item>
    <item quantity="many">Current interval: %d days</item>
    <item quantity="other">Current interval: %d days</item>
</plurals>
Assertion failed: [validStr] <resources>
    <string name="testString">I am a test String</string>
    <string name="testString2">test</string>
    <string name="testString3">test string</string>
    <string name="testString4">test string %s</string>
    <string name="testString5">%%</string>
    <string name="testString6">%1$'d' is expected</string>
    <plurals name="PluralTestString1">
        <item quantity="one">%1$'d' card (0 due)</item>
        <item quantity="other">%1$'d' cards (0 due)</item>
    </plurals>
    <plurals name="pluralTestString2">
        <item quantity="one">आज %1${'$'}'d' मध्ये %2${'$'}'s' कार्डचा अभ्यास केला</item>
    </plurals>
    <string name="testString7">XXX%</string>
</resources>
```

2022-09-08 19:22 UTC, krmanik commented
I have tried to implement the `check.ts` for finding broken strings but it is not catching the errors for `pluralMultiple `. 

```js
const pluralMultiple = `<plurals name="reschedule_card_dialog_interval">
    <item quantity="one">Current interval: %d day</item>
    <item quantity="few">Keisti Kortelių mokymosi dieną</item>
    <item quantity="many">Current interval: %d days</item>
    <item quantity="other">Current interval: %d days</item>
</plurals>`
```

I am getting same result for the kotlin class mentioned above (on kotlin playground https://pl.kotl.in/07ZnNzCxV), and how the test class mark it as clean?

https://github.com/ankidroid/Anki-Android/blob/f40239ddadd0c57d053c3ce5fbe313f5c42b40b5/lint-rules/src/test/java/com/ichi2/anki/lint/rules/NonPositionalFormatSubstitutionsTest.kt#L173-L180

2022-09-10 17:28 UTC, krmanik commented
The `plurals` will be implemented in next commit. More tests will be added also. 

<img height="300px" src="https://user-images.githubusercontent.com/12841290/189494828-99a1bb5a-5440-4e34-a9ef-13518cc8a6e3.png"></img>

2022-12-03 13:56 UTC, mikehardy commented
scoped storage will finish, one of these days, and I can hopefully turn attention back to all the javascript work + crowdin API updates

2023-08-30 00:56 UTC, mikehardy commented
Scoped storage is done!! Note that the list of languages in lint_release needs an update when a language is added - just needs an addition to the comment in that area of the new implementation

2023-10-21 06:33 UTC, eginhard commented
@krmanik @mikehardy It looks like the Crowdin API v1 will finally be shut down at the end of November (https://github.com/microsoft/pxt/issues/9539, https://github.com/PrestaShop/PrestaShop/issues/33655), so this is getting more urgent. Not sure what is left to be done for this?

2023-10-21 11:26 UTC, mikehardy commented
Oh! We'll happy coincidence at least, I have time to finish getting it merged in now so we should make the deadline. I really appreciate the heads-up thank you!

2023-10-22 15:11 UTC, krmanik commented
This PR is almost functional, I have not tested it yet. Thanks to @mikehardy looking into this.

2023-11-04 03:55 UTC, krmanik commented
@mikehardy 
should I continue this?

2023-11-04 17:09 UTC, mikehardy commented
@krmanik if you have time, sure! We have a deadline here of the end of the month and the work is (as you mentioned) almost done. I have not had time to look into it yet, so any help is appreciated of course

2023-11-05 12:51 UTC, krmanik commented
I am also out of time but I will complete this PR.

2023-11-23 17:08 UTC, mikehardy commented
fixed fairly trivial merge conflict and pushed it back
starting process of final review+testing+fixups, not 100% committing that I personally have time to do it but I think I will, and the deadline is now rapidly approaching 😬 😄

2023-11-23 19:09 UTC, mikehardy commented
TODO list for me as I look at this

- [ ] eliminate string checking from this PR / the new implementation
  - it appears that the previous string checking that happened on crowdin import is now handled well by default lint which is run in CI on any commit and is where these failures show up in current process, so it is not a regression
  - Current (python) implementation only works on certain operating systems so was not great to begin with
  - new typescript implementation is slow and is apparently just duplicating lint
- [ ] verify this:  the list of languages in lint_release needs an update when a language is added - just needs an addition to the comment in that area of the new implementation
- [ ] use new personal access token generated for ankidroid org
- [ ] use correct project id
- [ ] verify download/extract/update generates minimal diff
- [ ] verify upload generates zero diff for no changes, correct diff for new strings / string deletes

2023-11-23 20:08 UTC, mikehardy commented
This is ready to go pending #14801 - it's a workflow that we can only (or should only...) run on main so post-merge it will need a few runs to make sure the yaml looks good, and careful monitoring for the first few string update/deletes, but I think it's good to go

2023-11-23 20:09 UTC, mikehardy approved these changes
ran this a bunch locally while testing, fixed every little thing I saw during execution

re-read the manage-crowdin and update-localizations python (which I've worked with a bunch in the past) and compared it to everything in here while working here - I think it all checks out and to help future explorers (or future me) I added comments for anything I had to think about at all

2023-11-23 21:13 UTC, mikehardy commented
I'm busy rest of the day today but will merge this tomorrow morning my time (about 16hrs from now?) assuming no one sees anything dire

Then I can do the first few runs with it and make sure it is well behaved. Strings are up to date so we'll have small diffs to start...

2023-11-24 02:30 UTC, david-allison approved these changes
Nothing blocking, a few nits for optional follow-ups

2023-11-24 02:30 UTC, david-allison commented on tools/localization/package.json
> +    "scripts": {
`private: true`?

2023-11-24 02:30 UTC, david-allison commented on tools/localization/src/constants.ts
> +    "sc",
LGTM - last addition

2023-11-24 02:30 UTC, david-allison commented on tools/localization/src/download.ts
> +        }, 10000);
nit: preference for `10_000`

2023-11-24 02:30 UTC, david-allison commented on tools/localization/src/download.ts
> +            if (progress.data.progress === 100 && progress.data.status === "finished") {
Are there failure modes here (infinite loop without crashing)?

Regardless, is there a reasonable timeout?

2023-11-24 02:30 UTC, david-allison commented on tools/localization/src/update.ts
> +        // The language is defined by a two-letter ISO 639-1 language code, optionally followed by a two letter ISO 3166-1-alpha-2 region code (preceded by lowercase r).
But we use `fil`, which is a 3-letter code

2023-11-24 02:30 UTC, david-allison commented on tools/localization/src/update.ts
> +            androidLanguage = language.replace("-", "-r"); // zh-CW becomes zh-rCW
zh-CN? CW is Curaçao

2023-11-24 05:20 UTC, krmanik commented
I have tested it locally and it is working as expected. I have added Readme file for the commands.

2023-11-24 12:38 UTC, mikehardy commented
Fantastic, thanks again @krmanik - I'll do what I can on David's suggestion then merge this and do some careful runs of the i18n sync afterwards. There is always some tiny thing so I won't be surprised if there is some little thing on the yaml changes in the workflow but this is fantastic and I'm excited to get this in

2023-11-24 13:04 UTC, mikehardy commented on tools/localization/package.json
> +    "scripts": {
agreed - code is still licensed open but this toggle will ensure it is not accidentally published
we don't intend to have this become a supported project with an entry in npmjs.com etc...

2023-11-24 13:04 UTC, mikehardy commented on tools/localization/src/constants.ts
> +    "sc",
yeah I very very carefully went through the language lists one by one 😅 - but they were all in sync going in

2023-11-24 13:15 UTC, mikehardy commented on tools/localization/src/download.ts
> +        }, 10000);
TIL I learned that numeric separators existed, and they exist in all the languages I commonly use! Fascinating.

Also learned that while they are neat and I agree with your suggestion here for this constant and constants in general, apparently the various string-to-number methods like parseInt etc do not support them? Untested https://2ality.com/2018/02/numeric-separators.html#parsing-numbers-with-separators

2023-11-24 13:21 UTC, mikehardy commented on tools/localization/src/download.ts
> +            if (progress.data.progress === 100 && progress.data.status === "finished") {
There may be. There are options in their API to set retries and you can set HTTP-level timeouts as well
In practice crowdin is very reliable though - I've never seen timeouts in years.

So, balancing the thought of putting in a lot of code here to set retries, http timeouts, javascript timeouts...

I'm inclined to let the github actions workflow timeout (or human impatience and a ctrl-c locally) handle that and just have the whole workflow fail at a coarse level then account for it here unless future flakiness shows it to have value

2023-11-24 13:44 UTC, mikehardy commented on tools/localization/src/update.ts
> +            androidLanguage = language.replace("-", "-r"); // zh-CW becomes zh-rCW
typo in original pre-port source probably from MikePast of 4 years ago, but fixed

2023-11-24 13:59 UTC, david-allison commented on tools/localization/src/download.ts
> +            if (progress.data.progress === 100 && progress.data.status === "finished") {
Sounds good to me, as long as the GitHub action has a reasonable default timeout

2023-11-24 14:01 UTC, david-allison approved these changes
Just to confirm: it was good to go before and is still good to go

2023-11-24 14:15 UTC, merged

2023-11-24 14:17 UTC, mikehardy commented
Okay - now bear with me while I do the first couple runs.

I *know* that it will do some html-entitification on the first run as I've seen it locally (but not committed it, saving it for the run...) and I've verified it is actually what we want, so it has a nice first test case

I'm probably going to YOLO fixes direct on main to the YAML though until I get it working. I can't risk having the cloud state of crowdin (which is unbranchable) not tracking the local state of workflow runs here. Not my favorite thing to do to walk on a tightrope without a net but I believe it will work out...