Refactor themes
ankidroid/Anki-Android pull request #11555
Opened 2022-06-06 10:28 UTC by BrayanDSO

## Purpose / Description
Most of Themes.kt code is mine and I find it ugly. Since I'm a wiser man now, I'll try to improve it.

## Approach
On the commits (kinda hard to split them, but let me know if anything isn't clear)

## How Has This Been Tested?

On my phone (API 31)

https://user-images.githubusercontent.com/69634269/172143330-90de628c-a12b-45a6-9ee5-0d2a356e0b20.mp4

Upgrading from 2.15.6. Good news is themes aren't becoming corrupted, although I don't know why the previous theme (plain) didn't persist

https://user-images.githubusercontent.com/69634269/172143421-7c7afd8a-5292-4f4e-927f-2b51d14961e1.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-06 12:48 UTC, david-allison requested changes
One change needed

2022-06-06 12:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
> +                if (previousVersionCode < 21600168) {
This should be in `PreferenceUpgradeService`. 

Version codes no longer work due to our split between architectures.

2022-06-06 12:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +            (appThemePref.value == Themes.FOLLOW_SYSTEM_MODE).also {
style: I find this harder to read.

2022-06-06 12:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +                (newValue == Themes.FOLLOW_SYSTEM_MODE).also {
ditto

2022-06-06 13:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
> +                if (previousVersionCode < 21600168) {
This should be in a new 'upgrade' class. 

`versionCode` no longer works due to changing how our version numbering works

2022-06-06 13:31 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
> +                if (previousVersionCode < 21600168) {
That should probably be added in a comment here in the code so future developers are not lured in, and/or could use a blurb in developer guide "how to do a preferences upgrade"...

2022-06-06 19:23 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
> +                if (previousVersionCode < 21600168) {
And I should have read the whole file. Thanks.

2022-06-06 19:26 UTC, BrayanDSO commented
Upgrade works now. Thanks.

https://user-images.githubusercontent.com/69634269/172232778-8736b971-5444-4ac0-b40b-f7e70991e7ac.mp4

2022-06-06 20:15 UTC, BrayanDSO commented
Drafting while I fix the test

2022-06-06 22:29 UTC, BrayanDSO commented
A thought, if we go _downgrade_ the app, it will corrupt the theme, since the new theme values can't be used on the older code, which requires cleaning the app's data to make it work again OR go back to the new version.

How much of a problem is this? (i.e. should I handle downgrades or not?)

2022-06-07 22:27 UTC, BrayanDSO commented
Deconflicted and fixed the problem with systemIsInNightMode initialization on tests with `@EmptyApplication`

2022-06-07 22:35 UTC, david-allison reviewed
Two questions, but generally looks good

2022-06-07 22:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.kt
> +            if (currentTheme == Theme.DARK) {
This is confusing. We have `isDark` and `== DARK` meaning two different things.

Maybe `isNightMode`?

Note: we do want to remove this code fairly soon

2022-06-07 22:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
> +                }
can theoretically remove `invertedColors` as well?

2022-06-07 22:52 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.kt
> +            if (currentTheme == Theme.DARK) {
Have thought about it and  `current theme is night mode` didn't sound  very natural to me. But it's not something I care much, so I'll do the change.

2022-06-07 23:08 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
> +                }
Sure

2022-06-07 23:13 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
> +                        putString("dayTheme", "2")
Might this be a good time to use more descriptive values than stuff like "2"?

2022-06-07 23:17 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
> +                        putString("dayTheme", "2")
IMO the values don't matter. 

And changing them would mean having to upgrade the app theme values as well, which is an unnecessary work.

2022-06-07 23:23 UTC, david-allison approved these changes

2022-06-08 00:24 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
> +                        putString("dayTheme", "2")
It's not that this really matters, but [magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)) are usually regarded as anti-pattern.

2022-06-18 10:40 UTC, BrayanDSO commented
Rebased to solve conflicts

2022-06-25 21:33 UTC, mikehardy approved these changes
LGTM - just ran it through CI tasks locally after rebase to make sure, all good

2022-06-25 21:33 UTC, merged