migrated createChart to suspend function
ankidroid/Anki-Android pull request #11556
Opened 2022-06-06 10:58 UTC by divyansh-dxn

## Pull Request template

## Purpose / Description
AsyncTask to coroutines migration

## Approach
Replaced the usage of AsyncTask to create a chart with the suspend function. Since with coroutines we can easily switch context between the main and background thread, there is no need for a callback-based approach. 

## How Has This Been Tested?
Runs as expected on Realme 6i

https://user-images.githubusercontent.com/69595691/172148243-bd5180e7-a201-4816-9695-61a68c84d2f8.mp4

https://user-images.githubusercontent.com/69595691/172148207-af2cdad3-ef88-46dd-8d37-c0db10433265.mp4

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-06 14:05 UTC, lukstbit requested changes

2022-06-06 14:05 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
> +    ) = withContext(defaultDispatcher) {
The initial code made sure that the code in the task doesn't run on multiple threads even if there are multiple tasks. The current coroutine code doesn't offer this assurance, we use one dispatcher which has a pool of threads behind it. Multiple calls to createChart() will create multiple coroutines possibly running on different threads.

2022-06-07 13:49 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
> +    ) = withContext(defaultDispatcher) {
I am looking for solutions, one was to use mutex but then here I think we want to run this method concurrently for different charts but don't want to launch multiple coroutines which alter the same chart. Using mutex will stop other charts from loading parallelly, isn't it? Do you have any solutions in your mind?

2022-06-07 14:09 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
> +    ) = withContext(defaultDispatcher) {
I am looking for solutions but still wasn't able to figure it out. Here we want to load different charts concurrently (since there are multiple charts to load), but don't want multiple coroutines to interfere with the same chart (view), don't we?

2022-06-07 15:14 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
> +    ) = withContext(defaultDispatcher) {
We could replicate the lock with a [Mutex](https://kotlinlang.org/docs/shared-mutable-state-and-concurrency.html#mutual-exclusion) by placing the current code of the `createChart()` method inside `mutex.withLock {}`.

2022-06-08 03:36 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
> +    ) = withContext(defaultDispatcher) {
But won't it prevent other charts to load concurrently ?

2022-06-08 04:41 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
> +    ) = withContext(defaultDispatcher) {
Yes, but it would just replicate the initial code which also runs the task sequentially. 

The code around this classes could be definitely improved but that is another discussion.

2022-06-08 10:07 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
> +    ) = withContext(defaultDispatcher) {
Is there some reason to prevent concurrency here? Or is it only because the previous code was implemented in that way?

2022-06-08 10:09 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
> +    ) = withContext(defaultDispatcher) {
Is there some reason to prevent concurrency here? Or is it only because the previous code was implemented in that way?

2022-06-08 11:37 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
> +    ) = withContext(defaultDispatcher) {
> Or is it only because the previous code was implemented in that way?

This.

2022-06-10 19:32 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
> +                taskHandler!!.createChart(getChartTypeFromPosition(mSectionNumber), mProgressBar, mChart)
Prefer `?.`

2022-06-13 07:31 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
> +                taskHandler!!.createChart(getChartTypeFromPosition(mSectionNumber), mProgressBar, mChart)
But here the nullability is arising due to type casting of `requireActivity() as Statistics` so it should be non-null. If it is null, then there is an issue and it should throw the NullPointerException.

2022-06-13 08:41 UTC, ShridharGoel approved these changes

2022-06-13 19:00 UTC, mikehardy approved these changes
Looks great, pulled it locally and verified charts all drew / updated as expected while changing time span graphed and/or data set graphed, including seeing the spinner show up and go away. Nice

2022-06-13 19:00 UTC, merged

2022-06-13 19:01 UTC, mikehardy commented
For GSoC PRs feel free to label them as "review high priority" - normally open source has no deadlines so we just kind of review what we have time for and/or what we are interested in, but GSoC actually *has* a deadline. So once a PR is in, treating them as higher priority is simply recognizing reality I think. Cheers

I'll post the same on discord :-)