Kotlin CleanUp of IMultimediaEditableNote.kt
ankidroid/Anki-Android pull request #11596
Opened 2022-06-11 04:37 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description

Kotlin CleanUp of IMultimediaEditableNote.kt

2022-06-18 09:15 UTC, Prince-kushwaha commented
@david-allison can you review this PR

2022-06-25 14:38 UTC, krmanik approved these changes
@Prince-kushwaha Rebase it to main, if CI pass then it will be merged.

2022-06-25 21:27 UTC, mikehardy requested changes
As commented in a specific spot: `!!` worries me

2022-06-25 21:27 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/impl/MultimediaEditableNote.kt
> +        return cloneField(mInitialFields!![index])!!
I don't know :thinking: - I see `!!` and I think "I wonder how long before I get a crash report on this line..." and in my experience the answer is just a couple weeks. 

This is just using type annotation to move the problem around (we have exchanged `?` on callers for `!!` on method) without necessarily solving the problem - do we *know* it is not null?

We need to either know it is not-null in some way so that `!!` is not necessary or I'm not sure we can remove the `?` without the risk of a crash

2022-06-26 04:06 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/impl/MultimediaEditableNote.kt
> +        return cloneField(mInitialFields!![index])!!
The `cloneField()` method delegates to Acra's `IOUtils.deserialize()` method which has its return annotated with `@ Nullable`. I don't think forcing the non null with `!!` here is ok.

2022-06-26 04:10 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/impl/MultimediaEditableNote.kt
> +        return cloneField(mInitialFields!![index])!!
yes i agree with you

2022-06-26 04:36 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/impl/MultimediaEditableNote.kt
> +        return cloneField(mInitialFields!![index])!!
@mikehardy it is not possible to make  IField non-null . I don't think forcing the non null with !! here is ok
IField  nullable is fine

2022-06-27 15:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/impl/MultimediaEditableNote.kt
> +        return cloneField(mInitialFields!![index])!!
I'm fine for !! to be used on `cloneField`, or for it to be recoded

it shouldn't return null, an exception should occur if the clone fails.

2022-07-05 15:39 UTC, merged