Kotlin migration single task manager
ankidroid/Anki-Android pull request #11598
Opened 2022-06-11 08:57 UTC by divyansh-dxn

## Purpose / Description
Kotlin conversion : SingleTaskManager.java -> SingleTaskManager.kt

## Approach
- Convert JAVA file to Kotlin
- Do some small changes manually

## How Has This Been Tested?
Runs test as expected on `Realme 6i API 30` and `Pixel 4 Emulator API 31`

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-11 11:38 UTC, lukstbit requested changes

2022-06-11 11:38 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.kt
> + * Copyright (c) 2020 Arthur Milchior <arthur></arthur>@milchior.fr>                              *
The migration tool doesn't handle too well this type of documentation so you should go over this copyright documentation and make sure it's the same as in the java file.

2022-06-11 11:38 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.kt
> +@file:Suppress("DEPRECATION")
Add the deprecation annotation as closely as possible to the code raising it(like statement or method), suppressing for the entire file would hide future deprecation warnings .

2022-06-12 18:04 UTC, divyansh-dxn commented
@Arthur-Milchior For confirmation on discord `divyansh#5182`

2022-06-13 13:13 UTC, divyansh-dxn commented
What makes a unit test pass on some Operating Systems but fail on others? And how can I tackle it?

2022-06-13 15:03 UTC, mikehardy commented
> What makes a unit test pass on some Operating Systems but fail on others? And how can I tackle it?

Nothing specific. There is nothing that should cause it to fail on one vs the other, but you have not included details of what you mean.

If you mean right here in this set of runs the standard method is just to click on details and note them:

```

UpgradeVolumeButtonsToBindingsTest > [0: isValid(TestData(affectedPreferenceKey=gestureVolumeUp, keyCode=24, unaffectedPreferenceKey=gestureVolumeDown, binding=com.ichi2.anki.reviewer.MappableBinding@1900db))={1}] > com.ichi2.anki.servicemodel.UpgradeVolumeButtonsToBindingsTest.gesture_set_no_conflicts[0: isValid(TestData(affectedPreferenceKey=gestureVolumeUp, keyCode=24, unaffectedPreferenceKey=gestureVolumeDown, binding=com.ichi2.anki.reviewer.MappableBinding@1900db))={1}] FAILED
    java.lang.AssertionError: 
    Expected: iterable with items ["preferenceUpgradeVersion", "gestureVolumeUp", "binding_SHOW_ANSWER"] in any order
         but: no item matches: "preferenceUpgradeVersion", "gestureVolumeUp", "binding_SHOW_ANSWER" in []
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at com.ichi2.anki.servicemodel.UpgradeVolumeButtonsToBindingsTest.gesture_set_no_conflicts(UpgradeVolumeButtonsToBindingsTest.kt:97)
```

Then search for the failure string, in this case https://github.com/ankidroid/Anki-Android/issues?q=is%3Aissue+UpgradeVolumeButtonsToBindingsTest

At which point you see this issue which contains the string if you search for it, leading to this comment:

https://github.com/ankidroid/Anki-Android/issues/11091#issuecomment-1130226317

How do you tackle it? Run it a bunch on your local machine - I see failures for this test pretty frequently, not sure what the problem or fix would be but I would love it :pray: :pray: if you could figure it out and fix it. This test is failing a lot

2022-06-13 21:40 UTC, Arthur-Milchior commented
In case it was not clear from @mikehardy's answer: it's a flaky test. It means that fails or succeed sometime randomly, not related to your PR

2022-06-13 23:08 UTC, Arthur-Milchior approved these changes
Just some cleanup I'd love noted for later, otherwise good, thanks

2022-06-13 23:08 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.kt
> +    override fun removeTaskConcrete(task: CollectionTask<*, *>): Boolean {
Kotlin cleanup:

Once all managers are moved to Kotlin, check whether it's possible to remove `concrete` without having ambiguity between the static and the non-static.

2022-06-14 06:54 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.kt
> +        val newTask = CollectionTask(task, listener, mLatestInstance)
Should I add the cleanup annotations in the same PR, or after getting it merged?

2022-06-14 13:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.kt
> +        result = result and waitToFinish(timeoutSeconds / 4)
Cleanup to remove it (as it's unused)

2022-06-15 00:32 UTC, david-allison requested changes
Treat this as an approval once a cleanup is added

2022-06-15 04:29 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.kt
> +    override fun removeTaskConcrete(task: CollectionTask<*, *>): Boolean {
Pardon me, but I didn't understand what you mean by this cleanup.

2022-06-15 10:52 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.kt
> +        val newTask = CollectionTask(task, listener, mLatestInstance)
In the same PR (you can look at other migration PR to check how they did it)

2022-06-15 10:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.kt
> +        result = result and waitToFinish(timeoutSeconds / 4)
It’s not unused. Actually, this is what led me to create #11619, which uses it again.
While this PR is blocked because it adds flakyness, I believe the method should remain until we have really considered what to do for #11619.

2022-06-15 10:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.kt
> +    override fun removeTaskConcrete(task: CollectionTask<*, *>): Boolean {
`@KotlinCleanup("See if removeTaskConcrete could be renamed to removeTask (and similar for other method) once all TaskManagers are in Kotlin)`

Right now, I believe we will still need both a static and a member object, but at least we may avoid duplicating name.

2022-06-15 11:32 UTC, david-allison approved these changes

2022-06-15 12:45 UTC, merged