[Kotlin Migrate] JSONObject
ankidroid/Anki-Android pull request #11604
Opened 2022-06-11 16:51 UTC by dorrin-sot

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-15 10:27 UTC, david-allison requested changes
LGTM, only future cleanups

2022-06-15 10:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt
> -/*
spacing should be unchanged

2022-06-15 10:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt
> +    constructor(x: JSONTokener?) : this() {
`kotlinCleanup: non-null`

2022-06-15 10:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt
> +        private fun checkName(name: String?): String {
`@KotlinCleanup("remove, always called with non-null")`

2022-06-15 10:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt
> +        fun numberToString(number: Number?): String {
`@KotlinCleanup:  non-null`

2022-06-15 10:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt
> + */ open class JSONObject : org.json.JSONObject, Iterable<String?> {
add a newline here

2022-06-15 18:03 UTC, david-allison approved these changes

2022-06-16 18:10 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt
> +open class JSONObject : org.json.JSONObject, Iterable<String?> {
@KotlinCleanup("Simplify null comparison, !! -> ?.")

2022-06-16 18:12 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt
> +     * Integer, Long, Double, [.NULL] or null. May not be [     ][Double.isNaN] or [infinities][Double.isInfinite].
extra "[]" between comment

2022-06-17 17:12 UTC, dorrin-sot commented
e: warnings found and -Werror specified
[228](https://github.com/ankidroid/Anki-Android/runs/6939905220?check_suite_focus=true#step:6:229)
w: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/async/Connection.kt: (181, 29): Condition 'hostkey != null' is always 'true'
[229](https://github.com/ankidroid/Anki-Android/runs/6939905220?check_suite_focus=true#step:6:230)
[230](https://github.com/ankidroid/Anki-Android/runs/6939905220?check_suite_focus=true#step:6:231)
> Task :AnkiDroid:compilePlayDebugKotlin FAILED

What 😳

2022-06-25 21:24 UTC, mikehardy commented
@dorrin-sot - yep, warnings are treated as errors and the changes to JSONObject mean this one is non-null now, so the conditional is warned as unnecessary and then fails

This appears to make the build work for me

```diff
diff --git a/AnkiDroid/src/main/java/com/ichi2/async/Connection.kt b/AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
index 109c5efe9..a0c025fdb 100644
--- a/AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
@@ -178,7 +178,7 @@ class Connection : BaseAsyncTask<Connection.Payload, Any, Connection.Payload>()
                 try {
                     val response = JSONObject(ret.body!!.string())
                     hostkey = response.getString("key")
-                    valid = hostkey != null && hostkey.length > 0
+                    valid = hostkey.isNotEmpty()
                 } catch (e: JSONException) {
                     Timber.w(e)
                     valid = false
```

...and after that, the normal CI check run I test things with works

> /bin/nice -n 19 ./gradlew clean jacocoTestReport :api:lintRelease :AnkiDroid:lintPlayRelease ktlintCheck lint-rules:test --rerun-tasks

> BUILD SUCCESSFUL in 9m 1s

2022-06-26 05:27 UTC, dorrin-sot commented
Oh sorry. I was confused because I didn't get that error while building locally😅

2022-06-26 05:30 UTC, dorrin-sot commented
Also should I amend the changes of 838ebf8 and 914e860 onto 2a77137 to make the whole migration PR into two commits?

2022-06-26 13:55 UTC, mikehardy commented
> Also should I amend the changes of the last 2 commits onto the "Migrate JSONObject to Kotlin" to make the whole migration PR into two commits?

Looking those two over, it does seem they should be part of the second (kotlin conversion) commit. Other than a flaky test (which I restarted anyway) this passes CI now though - it's close!

2022-06-26 14:13 UTC, dorrin-sot commented
Done :)

2022-06-26 20:19 UTC, Arthur-Milchior requested changes

2022-06-26 20:19 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt
> +    constructor(x: JSONTokener?) : this() {
I must state that I don't understand why it's a cleanup. `x` must obviously be non-null, and even the way code is read would be closer to original java code if we didn't uselessly put it nullable here

2022-06-26 20:19 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt
> -    public static JSONObject objectToObject(org.json.JSONObject obj){
Can you please explain in the commit message why you removed this constructor?

2022-06-26 20:19 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt
> +    override fun put(name: String, value: Boolean): JSONObject {
You can even simplify into:

```
override fun put(name: String, value: Boolean) = 
  try {
    super.put(name, value)
    this
  } catch (e.org.json.JSONException) {
    throw JSONException(e)
  }
```
and similar below

2022-06-26 20:19 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt
> +open class JSONObject : org.json.JSONObject, Iterable<String?> {
There is one very important Kotlin Cleanup missing.
That can be done only once this class, Array class, JSONException classes, are used only in Kotlin files, and not used in any java file anymore

It consists in deleting this classes, and exporting the few helpers functions that are not in org.json.JSONObject in other files.
Indeed, the only purpose of having some json classes in this very package, com.ichi2.utils, is that this ensure that those functions sends non checked exceptions. This did allow, years ago, to avoid checking for JSON exception everywhere around the code, making the code far more readable, but sadly also slightly slower.
Once we are in Kotlin and we stop caring about checked exception, those classes becomes entirely useless, and we can delete them. I think they may be my first big contribution to AnkiDroid, and I'll be happy to have it deleted!

2022-06-26 20:19 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
> +        assertEquals("\"\"", org.json.JSONObject.quote(null))
nope. You want to test our JSONObject, not org.json's one

2022-06-26 20:19 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
> +        Assert.assertEquals(mCorrectJsonObjectBasic.toString(), JSONObject(mCorrectJsonObjectBasic!!).toString())
Kotlin cleanup: move mCorrectJsonObjectBasic and related values to lateinit

2022-06-26 21:04 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidV16Backend.kt
> +                to_json_bytes(JSONObject(templateRenderContext._template!!.toMap())),
It's because of `_template` being 
https://github.com/ankidroid/Anki-Android/blob/ce1fa3679dd9587f96c3e1e91d24e500a36ea033/AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt#L126
which is actually
https://github.com/ankidroid/Anki-Android/blob/ce1fa3679dd9587f96c3e1e91d24e500a36ea033/AnkiDroid/src/main/java/com/ichi2/libanki/PythonTypes.kt#L26
so since the constructor parameter here
https://github.com/ankidroid/Anki-Android/blob/ce1fa3679dd9587f96c3e1e91d24e500a36ea033/AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt#L58
is `Map<Any, Any>` we can't give it `HashMap<Any, Any>` or `HashMap<String, String>` and so we need to convert it to Map with that method

2022-06-26 21:12 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt
> -    public static JSONObject objectToObject(org.json.JSONObject obj){
just because it was unused but I can return it

2022-06-26 21:17 UTC, dorrin-sot commented on AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
> +        assertEquals("\"\"", org.json.JSONObject.quote(null))
Oh But we don't actually have a static method `quote` in ours which was confusing for me too but I tracked the one from before the migration and it was actually calling `org.json.JSONObject.quote(null)`

2022-06-26 21:48 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt
> +    constructor(x: JSONTokener?) : this() {
Actually since this test exists it should be nullable (unless the test is unnecessary due to migration to kotlin?).

https://github.com/ankidroid/Anki-Android/blob/b792e9b0ab0074ec489feac1612e496598349ffa/AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt#L685

2022-06-26 21:53 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt
> -    public static JSONObject objectToObject(org.json.JSONObject obj){
It's still here:
https://github.com/ankidroid/Anki-Android/blob/b792e9b0ab0074ec489feac1612e496598349ffa/AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt#L354

2022-07-05 04:04 UTC, mikehardy commented
Conflict purgatory :weary:

2022-07-05 17:40 UTC, merged

2022-07-05 17:40 UTC, mikehardy commented
passes locally for me