Changing note type to cloze while in edit mode bug fix
ankidroid/Anki-Android pull request #11627
Opened 2022-06-14 17:17 UTC by dorrin-sot

## Purpose / Description
Changing note type to cloze while in edit mode would disable the `FieldEditLine`s and also saving a cloze-type note without any cloze deletions, wouldn't show error toast

## Fixes
Fixes #11626

## Approach
_How does this change address the problem?_

## How Has This Been Tested?
on emulator

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-15 00:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        if (isClozeType && !hasClozeDeletions()) {
This was moved outside `mAddNote`: does this mean a user can't edit a cloze deletion note with no clozes (if imported from Anki Desktop)?

2022-06-15 06:16 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        if (isClozeType && !hasClozeDeletions()) {
No It's just that it prevents the user from saving a cloze note with no deletions (while in "Edit Note" mode), which can be if user has changed note type to cloze and not added any deletions or the user has edited an already cloze note and removed its deletions. Showing this error message and returning was the default behavior when a note was being **added** but it should also happen if a note is being **edited**

2022-06-15 09:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        if (isClozeType && !hasClozeDeletions()) {
We have 3 states:

* new note (`mAddNote = true`)
* editing a note (`mAddNote = false`)
* changing the type of the note (remapping) (`mAddNote = false`)

I feel we're mistaking the 'remapping' state with the 'editing a note' state

2022-06-15 10:52 UTC, david-allison requested changes
This removes the ability to map the fields when changing the note type.

I feel it'd be best to move the discussion back to the issue. 

We have a lot of UX tech debt around editing note types, and it'd be best to resolve this properly rather than adding more complexity.

2022-06-15 10:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        if (isClozeType && !hasClozeDeletions()) {
Users currently aren't able to edit a card until it's been saved (if we are changing the note type, this lets users fix the field mapping).

This PR lets users edit the fields, but it disallows a user from setting the mapping if moving from a note type with 3 fields to a note type with 2 fields.

2022-06-17 17:32 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        if (isClozeType && !hasClozeDeletions()) {
But they can change note type type. they just can't save a cloze note with no deletions (which was previously the case for when user was creating a cloze note without deletions but not when editing note).

https://user-images.githubusercontent.com/59933477/174349048-05c2ec2f-3ba9-4853-a05e-73638693e3cf.mov

2022-06-18 19:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        if (isClozeType && !hasClozeDeletions()) {
They can't change the field mapping of a note type. 

Change a note type with 4 fields to a note type with two, and you'll see what I mean

2022-06-18 19:20 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        if (isClozeType && !hasClozeDeletions()) {
Do you mean the last two fields getting cut off?

2022-06-18 23:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        if (isClozeType && !hasClozeDeletions()) {
No, AnkiDroid changes the 'attachment' icon to a 'select field' icon

![image](https://user-images.githubusercontent.com/62114487/174459898-d4a4e4ea-1009-4851-bf23-497b88d98a04.png)

2022-06-19 11:10 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        if (isClozeType && !hasClozeDeletions()) {
Oh sorry. So, if a user is changing model to "Cloze" this is the expected behaviour?
1- `FieldEditText` stay enabled
2- if number of fields is decreasing when model was changed, `editModelMode = true`
3- if user tries to save the note without any deletions, prevent

2022-12-09 08:38 UTC, closed without merging