[GSoC] Kotlin migration Connection.java
ankidroid/Anki-Android pull request #11633
Opened 2022-06-15 12:05 UTC by divyansh-dxn

## Purpose / Description
This PR is a part of `GSoC 2022 - AsyncTask to Coroutines`. This class uses AsyncTask, which needs to be migrated to Kotlin first before using Coroutines.
Kotlin conversion : Connection.java -> Connection.kt

## Approach
- Convert the JAVA file to Kotlin
- Do some small changes manually

## How Has This Been Tested?
Runs as expected on `Realme 6i API 30` and `Pixel 4 Emulator API 31`
Passes all written tests.

https://user-images.githubusercontent.com/69595691/173822488-5faedc58-29c7-46e6-a59d-b200ebb1e724.mp4

https://user-images.githubusercontent.com/69595691/173822466-caae38e3-5744-4d12-9cc0-ad86723af249.mp4

_entering credentials part has been removed_

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-15 12:41 UTC, david-allison reviewed
```

> Task :AnkiDroid:compilePlayDebugAndroidTestJavaWithJavac FAILED
/Users/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/HttpTest.java:68: error: cannot find symbol
        if (!Connection.isOnline()) {
                       ^
  symbol:   method isOnline()
  location: class Connection
1 error
```

2022-06-15 13:59 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
> +//                            }
what is the reason for commenting this code?

2022-06-15 14:38 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
> +//                            }
Nothing, I just forgot to remove it. Earlier based on the nullability of `ret`, the message was returned but after conversion, it is of non-null type. I'll just remove it.

2022-06-15 14:41 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
> +                        """.trimIndent()
After conversion, this part is dangling with spaces and quotes, should I mark it for cleanup or just correct it in the 2nd commit?

2022-06-15 14:41 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
> +                        """.trimIndent()
same

2022-06-15 16:55 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
> +                        """.trimIndent()
if it's a small change, correct it right away

2022-06-15 23:42 UTC, BrayanDSO requested changes

2022-06-15 23:42 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
> +class Connection : BaseAsyncTask<Connection.Payload, Any, Connection.Payload>() {
KotlinCleanup: IDE-lint

2022-06-15 23:42 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
> +        override fun toString(): String {
KotlinCleanup: use formatted string

2022-06-15 23:42 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
> +    private fun doInBackgroundLogin(data: Payload): Payload {
KotlinCleanup: Scoped function

2022-06-15 23:42 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
> +        var colCorruptFullSync = false
KotlinCleanup: Make colCorruptFullSync a val

2022-06-15 23:42 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
> +        private fun returnGenericError(data: Payload): Payload {
KotlinCleanup: remove `return` from the method name
KotlinCleanup: scoped function

2022-06-15 23:42 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
> +    private fun doInBackgroundSync(data: Payload): Payload {
KotlinCleanup: scoped function

2022-06-15 23:42 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
> +        private fun launchConnectionTask(listener: TaskListener, data: Payload): Connection? {
KotlinCleanup: Scoped function

2022-06-15 23:42 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
> +                /* NetworkInfo is deprecated in API 29 so we have to check separately for higher API Levels */return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
return if... etc should be on the next line

2022-06-15 23:42 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
> +    private var mListener: TaskListener? = null
KotlinCleanup: lateinit

2022-06-15 23:42 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
> +import com.ichi2.utils.Permissions.canUseWakeLock
Remove this import

2022-06-16 06:34 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
> +import java.util.*
Avoid wildcard imports

2022-06-16 16:48 UTC, BrayanDSO approved these changes
LGTM

2022-06-16 18:00 UTC, Akshay0701 approved these changes

2022-06-16 18:00 UTC, Akshay0701 commented
Thanks @divyansh-dxn

2022-06-16 18:36 UTC, david-allison approved these changes

2022-06-16 18:36 UTC, merged