[Kotlin Cleanup] DeckAdapter
ankidroid/Anki-Android pull request #11634
Opened 2022-06-15 18:23 UTC by dorrin-sot

2022-06-15 18:35 UTC, david-allison requested changes
In general, looks much ore Kotlin-y, thanks!

2022-06-15 18:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
>      fun findDeckPosition(did: Long): Int {
Can we add unit tests if we're seriously refactoring. This adds risk for little reward otherwise.

2022-06-15 18:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
>      private fun processNodes(nodes: List<TreeNode<AbstractDeckTreeNode>>) {
unit test please

2022-06-15 19:43 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
>      fun findDeckPosition(did: Long): Int {
I removed the bit at the end since it was causing stackoverflow in tests; so only the `for` loop is getting cleaned up. Does it still need unit test?

2022-06-15 19:45 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
>      private fun processNodes(nodes: List<TreeNode<AbstractDeckTreeNode>>) {
Is it ok if I just add a `@NeedsTest` because I have no idea what this method does or how to test it :(

2022-06-15 20:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
>      fun findDeckPosition(did: Long): Int {
I want to encourage refactoring tested code, or adding tests while refactoring. But: use your judgment.

Everyone has different ideas about style. The most important thing to me is that we document the functions, and add tests, and make sure that we're not introducing regressions (such as the stack overflow). Those are less likely to change than the 'style' of the code, and to an extent, they'll help enable future refactorings.

2022-06-15 20:17 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
>      private fun processNodes(nodes: List<TreeNode<AbstractDeckTreeNode>>) {
Hardline stance: if you don't know what the method did beforehand, it shouldn't be refactored, as you don't know whether it's doing the same thing now. 

More time should be spent on understanding it, and documentation/documentation via tests/readability refactorings should be added first.

This is increasing the risk of bugs for a code style change. It's not a good tradeoff to take.

Note: I haven't touched this method at all, and also would need some time to understand it.

2022-06-16 08:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
>      private fun processNodes(nodes: List<TreeNode<AbstractDeckTreeNode>>) {
Still pending

2022-06-16 11:04 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
>      private fun processNodes(nodes: List<TreeNode<AbstractDeckTreeNode>>) {
Oh In that case, can I drop the commit related to this method?

2022-06-16 11:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
>      private fun processNodes(nodes: List<TreeNode<AbstractDeckTreeNode>>) {
Either or: understand and document, or drop. 

Dropping would be better for velocity if you have other plans

2022-06-16 11:13 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
>      private fun processNodes(nodes: List<TreeNode<AbstractDeckTreeNode>>) {
As you mentioned it's too much for little payoff (it's not that much cleaner. I'd go as far as to say  in some parts it's borderline harder to read even😂)

2022-06-16 19:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
>      fun findDeckPosition(did: Long): Int {
Don't use exceptions for non-exceptional circumstances.

Extract `mCol!!.decks.parents(did).last().optLong("id", 0)` to `DeckService` and document it, rather than trying to make it more terse.

We should be testing functionality that we're refactoring, otherwise we're introducing risk


I'd imagine this would be:

```kotlin
    /**
     * Return the position of the deck in the deck list. If the deck is a child of a collapsed deck
     * (i.e., not visible in the deck list), then the position of the parent deck is returned instead.
     *
     * An invalid deck ID will return position 0.
     */
    fun findDeckPosition(did: Long): Int {
        return mCurrentDeckList.indices
            .find { mCurrentDeckList[it].value.did == did }
             // If the deck is not in our list, we search again using the immediate parent
            ?: getParentDid(did)?.let { parentDid -> findDeckPosition(parentDid) } ?: 0
    }
```

2022-06-17 17:47 UTC, dorrin-sot commented
> > [Merge branch 'main' into Kotlin_Cleanup_DeckAdapter](https://github.com/ankidroid/Anki-Android/pull/11634/commits/accf615905f443a28f16fd55ece841bfceb8114f)
> 
> 😱

What happenned 😳

2022-06-18 19:17 UTC, david-allison commented
Hi, please remove the merge commit and rebase onto `main` instead.

2022-06-18 19:50 UTC, dorrin-sot commented
Oh sorry done😅

2022-06-18 23:28 UTC, david-allison requested changes
A few questions on style

2022-06-18 23:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/utils/IterableUtils.kt
> +    fun <T> Iterable<T>.nullableIndexOf(element: T): Int? {
This can be a bare function, outside the object.

2022-06-18 23:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
> +            .nullableIndexOf(did)
The standard Kotlin suffix is `OrNull`. So `indexOfOrNull`. Kotlin already defines this on `String`.

I don't see why this wasn't shortened to `.indexOfOrNull { it.value.did == did }

2022-06-20 16:37 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
>      fun findDeckPosition(did: Long): Int {
Oh, I see it was actually changed in later commit. Would you mind doing an interactive rebase and do the change as expected in the first commit changing those lines, so it gets easier to review

2022-06-20 16:37 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/utils/IterableUtils.kt
> +    fun <T> Iterable<T>.nullableIndexOf(element: T): Int? {
Please don't resolve, it seems to be still inside object.

Also, it'd be great two get tests. Just one with null and one with a number would be sufficient

2022-06-20 17:12 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
> +        get() = mCol.sched.eta(Counts(mNew, mLrn, mRev)).takeIf { mNumbersComputed }
Hi I fixed this and https://github.com/ankidroid/Anki-Android/pull/11634#discussion_r901120215 in later commits

2022-06-20 17:17 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
> +            return listOf(Locale.getDefault(), Locale.ROOT)
Finally kotlin added these🤩 I converted all the "convertable into expression body" functions

2022-06-20 17:31 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
> +        get() = mCol.sched.eta(Counts(mNew, mLrn, mRev)).takeIf { mNumbersComputed }
I just thought of this but I'm not sure how I feel about it
```
val eta: Int?
    get() = mNumbersComputed
        .takeIf { it }
        ?.let { mCol.sched.eta(Counts(mNew, mLrn, mRev)) }
```

2022-06-20 18:08 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
> +        val leftPadding = deckLayout.resources.getDimension(
I tried running with persian too. the values of `leftPadding` and `rightPadding` are the same. but also the padding amounts look the same. so maybe RTL is being handled internally (inside android's `RelativeLayout`)?🤔

<div style="display: flex; flex-direction: row">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/59933477/174657455-3dcae3b8-c2d7-415e-b3e3-71b1bc30dfe3.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/59933477/174657567-fd0c8e36-a383-4dc7-a691-abd00888436d.png">
</div>

2022-06-20 18:46 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
> -            holder.deckExpander.visibility = View.VISIBLE
Oh sorry I missed it

2022-06-28 02:22 UTC, david-allison reviewed
LGTM. One potential further cleanup

2022-06-28 02:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DeckService.kt
> +    }
Can this use `lastOrNull`: 

```kotlin
return col.decks.parents(did).lastOrNull()?.optLong("id", 0)
```

2022-06-28 23:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DeckService.kt
> +    }
Why was this changed to use `.run`?

2022-06-30 10:23 UTC, dorrin-sot commented
also how can I fix a translation string I just noticed was mistranslated in [this comment](https://github.com/ankidroid/Anki-Android/pull/11634#discussion_r901914986)? can I just change the string xml file?

2022-07-15 17:08 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
> +        get() = (mNew + mLrn + mRev).takeIf { mNumbersComputed }
I'm not fan of `takeIf` here since it means the work is done before the condition is checked. 
It's a sum, so not such a big deal. But I needed to note it at least

2022-07-15 17:13 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
> +        fun <T> Iterable<T>.indexOfOrNull(predicate: (T) -> Boolean): Int? =
I'd move it to com.ichi2.utils.CollectionUtils if it's okay

2022-07-15 17:31 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
> +        val leftPadding = deckLayout.resources.getDimension(
Is it ok if I set them to "start padding" and "end padding" since in xml layouts the android's padding attributes are named like this?

2022-12-09 07:36 UTC, closed without merging