Update to work with desktop 2.1.53 code
ankidroid/Anki-Android pull request #11644
Opened 2022-06-16 13:29 UTC by dae

Depends on https://github.com/ankidroid/Anki-Android-Backend/pull/202

Due to the removal and change of a few backend methods, syncing, importing
and the card templates screen will not work when the schema16 setting is
active (actually schema18 now). To get them working again, those code
paths will need to switch to the backend implementations.

A few notes:
- Downgrading happens automatically when loading the collection in schema11
mode, so the extra code dealing with downgrades & "can downgrade" reporting
can be stripped.
- Added the ability to run col.set_config("key", JSONObject.NULL), as
unit tests were attempting to write the entire collection config to accomplish
this, which is no longer supported.
- All tests pass on both old and new backends, though the latter required
disabling a few failed tests when running with the new schema
(eg notetype updating).

Integrates, and thus closes #11579 and closes #11581

2022-06-18 14:33 UTC, dae commented
Before I spend much more time on this, I'd appreciate it if you could let me know whether you're amenable to the changes in https://github.com/ankidroid/Anki-Android/pull/11644/commits/b02515b0f6a403a4e9f278d21620a1b07d0b1232. I was planning to build upon them to look into adding some new backend functionality, and don't really relish the thought of having to add all the extra boilerplate to do so.

2022-06-18 15:39 UTC, mikehardy commented
> Before I spend much more time on this, I'd appreciate it if you could let me know whether you're amenable to the changes in [b02515b](https://github.com/ankidroid/Anki-Android/commit/b02515b0f6a403a4e9f278d21620a1b07d0b1232). I was planning to build upon them to look into adding some new backend functionality, and don't really relish the thought of having to add all the extra boilerplate to do so.

I am personally okay with it, in the first instance by criteria of "implementor's choice" but also by scanning the overview doc and reasoning about the initial motivation:

https://github.com/ankidroid/Anki-Android-Backend/blob/main/docs/OVERVIEW.md#droidbackendrustdroidbackend

> Allows a testable comparison between the Java and the Rust during the conversion

I think this was useful but may have served it's purpose. We're definitely going to use rslib. The babel's tower of build toolchains and languages in use is a bit baroque, but we're using it live, we're not going back. How much value does a comparison with a java implementation that's never going to keep up with rslib development have? My opinion, none in future

> Allows a pure Java conversion afterwards (if deemed appropriate due to AGPL concerns)

I don't think we have those concerns? I do not have those concerns

> Encapsulates all access to the Rust, allowing the implementation to later be swapped out within one file.

Similar to first statement above: swapped out with what? I don't intend to get into an Anki development competition with rslib development so there will never be a full-featured swapout


https://github.com/ankidroid/Anki-Android-Backend/blob/main/docs/OVERVIEW.md#rustbackend-interface

One point here is interesting:

> Allows for easy mocking, and method discovery

Is easy mocking for testability interesting? Is this even the appropriate layer for testing the code - that is who would be mocking out RustBackend, is it a facility actually used now, and would any change proposed here alter that? I don't have a feel for it

In general, if this goes ahead it would be good to update the docs / diagrams for future intrepid explorers: 

> Source: docs/sources/sequence_method_call.plantuml. Created with [planttext](https://www.planttext.com/)


I personally don't see a problem. We're going to use rslib, no way around it. We either commit (which again: is not user hostile, I just scanned exception reports again) or are in a dev race with rslib which is a non-starter. The interfaces are code-gen'd so just calling in as simply as possible seems right to me.

2022-06-18 15:40 UTC, mikehardy commented
I know @david-allison had some specific architectural thoughts so despite a wish to be non-blocking it would be nice to get a thought from him otherwise I'd just merge it perhaps against wishes :see_no_evil:

2022-06-19 14:24 UTC, dae commented
I noticed that https://github.com/ankidroid/Anki-Android/pull/11651 refactors code that this PR cuts out. While unfortunate, that PR was a useful reference as I tried to piece together a working demo on https://github.com/ankidroid/Anki-Android/pull/11644/commits/5b83b31b3d5ff3d57130516317a778634070e86d. Maybe @divyansh-dxn might be interested in improving on this prototype code in the future, if it happens to be merged?

2022-06-20 14:09 UTC, dae commented
So, this is fun - rebasing the code onto the latest main breaks two test classes on my machine (the backend fails to load). It appears to be some sort of flake or race condition related to the number or order of the tests. If I comment out the RobolectricTestAnnotationTest class, the issue goes away. If I set set forkEvery to 1, the issue goes away. If I set forkEvery to 30, different tests fail. Is there an easy way to run the roboelectric and non-roboelectric tests in separate processes to see if that helps?

2022-06-20 17:55 UTC, mikehardy commented
With regret, I've got to say that you are past the frontier of my experience in this area. I've got nothing

2022-06-25 18:00 UTC, mikehardy commented
@dae are you still seeing test failures like:

> So, this is fun - rebasing the code onto the latest main breaks two test classes on my machine (the backend fails to load). It appears to be some sort of flake or race condition related to the number or order of the tests

I'm about to unpack tools and look through this again and I'm curious what to expect as known issues vs unknown issues to flag

2022-06-25 18:03 UTC, mikehardy commented
https://github.com/ankidroid/Anki-Android-Backend/issues/209 logged to capture need to sync overview / UML diagrams with restructured code flow from this and https://github.com/ankidroid/Anki-Android-Backend/pull/202

2022-06-25 23:48 UTC, dae commented
No, all tests pass for me on both the legacy and new schema settings after https://github.com/ankidroid/Anki-Android/pull/11644/commits/89f44661548133055eec178b1ab164fe6ca17716 and the latest commit

2022-06-25 23:53 UTC, mikehardy commented
> No, all tests pass for me on both the legacy and new schema settings after [89f4466](https://github.com/ankidroid/Anki-Android/commit/89f44661548133055eec178b1ab164fe6ca17716) and the latest commit

Man, that's subtle. Nice one

2022-06-27 01:38 UTC, dae commented
In https://github.com/ankidroid/Anki-Android/pull/11644/commits/0a1ce9a837453482551c9033fb37ff2532cd663c I had to put the code outside of the docstring or ktlint mangles it. Any ideas?

2022-06-27 02:11 UTC, mikehardy commented
> In [0a1ce9a](https://github.com/ankidroid/Anki-Android/commit/0a1ce9a837453482551c9033fb37ff2532cd663c) I had to put the code outside of the docstring or ktlint mangles it. Any ideas?

local disable? https://ktlint.github.io/#faq-error-suppression

2022-06-27 03:15 UTC, mikehardy reviewed
I'm out of time for the day but here's a note for my future self and anyone else following along at home:

- reviewed related Anki-Android-Backend changes, they are good to go except maybe some git housekeeping items which won't affect the built artifact :heavy_check_mark: 
- worked through a review of 9/101 of the files here so far in this pass and have been watching the commits as they come, not expecting anything major but need to peel todos / unfinished business out to new tasks (so far: progress reporting for new sync code, sync indicator doesn't go away with new sync code)
- in testing, I have no issues at the moment running against the same collection regardless of starting it with local.properties::legacy_schema=true or false, and then using settings developer options to toggle on v16 (or not) and run sync or not. I have not been able to crash it basically and I am trying all the different state combos I can think of along with "regular" usage on API31 simulator

need to test API21 simulator, and beat on it some more, peel issues out and finish review but this is looking good so far

2022-06-27 20:11 UTC, mikehardy reviewed
now that the backend library is published (though local integration has some issue for me...) I looked at the changes from the perspective of a commit stream and left myself some notes with regards to ordering with the idea of preserving git bisection capability

2022-06-27 20:11 UTC, mikehardy commented on build.gradle
> +    ext.ankidroid_backend_version = '0.1.13-anki2.1.53'
this version was never published, so unless the future 0.1.14-anki2.1.54 is squashed into this it will fail git bisect
I could squash it to avoid that but then I think the kotlin migrations would be suspect.

I'll try to squash the future bump into here so we have the dependency available and check the commit for compile

2022-06-27 20:11 UTC, mikehardy commented on AnkiDroid/build.gradle
> +    localProperties.load(project.rootProject.file('local.properties').newDataInputStream())
this fails CI because it's not protected by a check for local.properties existence, as does the next one. I've got a commit locally I will squash into this then push

```diff
diff --git a/AnkiDroid/build.gradle b/AnkiDroid/build.gradle
index e7cf130b7..4d9f9c205 100644
--- a/AnkiDroid/build.gradle
+++ b/AnkiDroid/build.gradle
@@ -270,7 +270,9 @@ dependencies {
     implementation 'com.google.protobuf:protobuf-kotlin:3.21.2' // This is required when loading from a file
 
     Properties localProperties = new Properties()
-    localProperties.load(project.rootProject.file('local.properties').newDataInputStream())
+    if (project.rootProject.file('local.properties').exists()) {
+        localProperties.load(project.rootProject.file('local.properties').newDataInputStream())
+    }
     if (localProperties['local_backend'] == "true") {
         implementation files("../../Anki-Android-Backend/rsdroid/build/outputs/aar/rsdroid-release.aar")
         testImplementation files("../../Anki-Android-Backend/rsdroid-testing/build/libs/rsdroid-testing-${ankidroid_backend_version}.jar")
diff --git a/build.gradle b/build.gradle
index 97a973de4..94f9d1cd8 100644
--- a/build.gradle
+++ b/build.gradle
@@ -40,7 +40,9 @@ allprojects {
 }
 
 Properties localProperties = new Properties()
-localProperties.load(project.rootProject.file('local.properties').newDataInputStream())
+if (project.rootProject.file('local.properties').exists()) {
+    localProperties.load(project.rootProject.file('local.properties').newDataInputStream())
+}
 Boolean fatalWarnings = !(localProperties['fatal_warnings'] == "false")
 
 // Here we extract per-module "best practices" settings to a single top-level evaluation
```

2022-06-27 20:11 UTC, mikehardy commented on build.gradle
> +localProperties.load(project.rootProject.file('local.properties').newDataInputStream())
needs file existence check pasted above to be squashed into this and repushed so this commit builds

2022-06-27 20:11 UTC, mikehardy commented on build.gradle
> +    ext.ankidroid_backend_version = '0.1.14-anki2.1.54'
probably need to squash this with previous backend update

2022-06-27 20:11 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/BackendImporting.kt
> +import anki.import_export.ImportResponse
probably need to squash this with initial implementation

2022-06-27 20:11 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/ChangeManager.kt
> +import anki.import_export.ImportResponse
probably need to squash this with initial implementation

2022-06-27 20:24 UTC, mikehardy commented
Hey @dae - can you give me the ability to push to your new-anki2 branch on ankitects?

```
mike@bistromath:~/work/AnkiDroid/Anki-Android-Upstream (new-anki2) % git push ankitects +new-anki2 
ERROR: Permission to ankitects/Anki-Android.git denied to mikehardy.
fatal: Could not read from remote repository.
```

2022-06-27 20:44 UTC, dae commented
For some reason it's not giving me the option to change the permissions, either here or when I try to create a new PR.  I've sent you a collaborator invite instead, which will hopefully work.

Liberal use of squashing is probably a good idea here to avoid broken builds when bisecting - no objections from me if you want to bundle everything up into just a few commits.

2022-06-27 21:00 UTC, dae commented
(If you’d like me to look into that, I can do so later today)

On Tue, 28 Jun 2022 at 6:25 am Mike Hardy ***@***.***> wrote:

> Hey @dae <https://github.com/dae> - can you give me the ability to push
> to your new-anki2 branch on ankitects?
>
> ***@***.***:~/work/AnkiDroid/Anki-Android-Upstream (new-anki2) % git push ankitects +new-anki2
> ERROR: Permission to ankitects/Anki-Android.git denied to mikehardy.
> fatal: Could not read from remote repository.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ankidroid/Anki-Android/pull/11644#issuecomment-1167848448>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABMCPQHBF253GSZOCTFM7LVRIE2LANCNFSM5Y62ABSA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-27 22:59 UTC, mikehardy commented
Strange re: perms, usually it's a matter of a checkbox on the PR for PR author somewhere on the middle-top right side. Anyway, I'm a collaborator on ankitects/Anki-Android now so that should do the trick.

I've got some sort of java protobuf error right now with the Anki-Android-Backend artifact I published when in use on an emulator, so that's the current hold up:

```
6-27 15:50:25.138 21899 21899 I CollectionHelper: Begin openCollection: /storage/emulated/0/AnkiDroid/androidTest/collection.anki2
06-27 15:50:25.172 21899 21899 W Backend$checkMainThreadOp: Op on UI thread: com.ichi2.anki.CollectionHelper.getOrCreateBackend(CollectionHelper.java:154)
06-27 15:50:25.172 21899 21899 D Backend : Opening rust backend with lang=[en]
06-27 15:50:25.183 21899 21899 D AndroidRuntime: Shutting down VM
06-27 15:50:25.184 21899 21899 E AndroidRuntime: FATAL EXCEPTION: main
06-27 15:50:25.184 21899 21899 E AndroidRuntime: Process: com.ichi2.anki, PID: 21899
06-27 15:50:25.184 21899 21899 E AndroidRuntime: java.lang.NoSuchMethodError: No static method addAll(Ljava/lang/Iterable;Ljava/util/List;)V in class Lcom/google/protobuf/AbstractMessageLite$Builder; or its super classes (declaration of 'com.google.protobuf.AbstractMessageLite$Builder' appears in /data/app/~~YX_81XE_Yg7LwLUkoVIpag==/com.ichi2.anki.tests-_D-HBgvKefYM4lCsZ22Rkg==/base.apk)
06-27 15:50:25.184 21899 21899 E AndroidRuntime: 	at anki.backend.BackendInit$Builder.addAllPreferredLangs(BackendInit.java:629)
06-27 15:50:25.184 21899 21899 E AndroidRuntime: 	at net.ankiweb.rsdroid.Backend.<init>(Backend.kt:80)
06-27 15:50:25.184 21899 21899 E AndroidRuntime: 	at net.ankiweb.rsdroid.BackendFactory.getBackend(BackendFactory.kt:48)
06-27 15:50:25.184 21899 21899 E AndroidRuntime: 	at net.ankiweb.rsdroid.BackendFactory.getBackend$default(BackendFactory.kt:45)
06-27 15:50:25.184 21899 21899 E AndroidRuntime: 	at net.ankiweb.rsdroid.BackendFactory.getBackend(Unknown Source:11)
06-27 15:50:25.184 21899 21899 E AndroidRuntime: 	at com.ichi2.anki.CollectionHelper.getOrCreateBackend(CollectionHelper.java:154)
06-27 15:50:25.184 21899 21899 E AndroidRuntime: 	at com.ichi2.anki.CollectionHelper.openCollection(CollectionHelper.java:146)
06-27 15:50:25.184 21899 21899 E AndroidRuntime: 	at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:190)
06-27 15:50:25.184 21899 21899 E AndroidRuntime: 	at com.ichi2.anki.services.BootService.getColSafe(BootService.kt:67)
06-27 15:50:25.184 21899 21899 E AndroidRuntime: 	at com.ichi2.anki.services.BootService.onReceive(BootService.kt:30)
06-27 15:50:25.184 21899 21899 E AndroidRuntime: 	at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:239)
06-27 15:50:25.184 21899 21899 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)

```

I'm working through reverification of everything to eliminate the initial assumption I always have that I've just built something wrong (maybe the protobuf stuff didn't build right? I dunno), but posting here in case you've seen it before.

2022-06-28 00:46 UTC, mikehardy commented
I pushed a commit that fixes the local.properties file reading so CI chewed on it, and I see the problem there as well:

```

com.ichi2.anki.DeckPickerTest > checkIfStudyOptionsIsDisplayedOnTablet[test(AVD) - 10] FAILED 
	java.lang.NoSuchMethodError: No static method addAll(Ljava/lang/Iterable;Ljava/util/List;)V in class Lcom/google/protobuf/AbstractMessageLite$Builder; or its super classes (declaration of 'com.google.protobuf.AbstractMessageLite$Builder' appears in /data/app/com.ichi2.anki.tests-AhTddKaU0bzaf6mst4eaEg==/base.apk)
	at anki.backend.BackendInit$Builder.addAllPreferredLangs(BackendInit.java:629)
Tests on test(AVD) - 10 failed: There was 1 failure(s).

```

I worked backwards a bit on commits both in Ank-Android and Anki-Android-Repo and now I can't get *anything* to work even on commit hashes that were working beofre? So I'm not sure what happened here.

@dae are you able to do a `./build-current.sh` in Anki-Android-Backend and a `./gradlew jacocoAndroidTest` in Anki-Android with local.properties::local_backend=true ? because I can't get that to work at all now and I'm stumped currently + out of time for a while

2022-06-28 01:14 UTC, david-allison requested changes
Note: 867394fea9236c77bd78aa3d2bd4a8925b07aaa4 did not compile. Didn't check other commits.

What's your preference for committing this? 
It's in the awkward position where we'll lose a lot of context if we squash, but some changes don't compile yet, the rebase would be a fair amount of work (and either some clever uses of `git rerere`, or some nasty merge conflict resolution). 

----

My ideal first step would be to extract the Kotlin conversion of `Storage`. 

Kotlin conversions are rebased to keep `git blame` working.

<details><summary>reviewer notes (incomplete review)</summary>

Reviewed up to https://github.com/ankidroid/Anki-Android/pull/11644/commits/9f4744742e293dbf4f891f1ca1367fb607848841
First commit needs a re-review

</details>

2022-06-28 01:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +            BackendFactory.INSTANCE.setDefaultLanguagesFromLocales(Arrays.asList(langConfig.locale));
(for reviewer), flagging for second review. This one appears to be safe, but it's in a very risky position in app startup.

https://github.com/ankidroid/Anki-Android-Backend/blob/8e09b32c34ea5659581dce2764a911367f9e1706/rsdroid/src/main/java/net/ankiweb/rsdroid/BackendFactory.kt#L56-L58

2022-06-28 01:14 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFilesTest.kt
> +        CompatHelper.compat.deleteFile(File(defaultCollectionSourcePath, "collection.anki2"))
flagging for reviewer 2, seems reasonable

2022-06-28 01:17 UTC, mikehardy commented
@david-allison 

> What's your preference for committing this?

I've flagged things I'm pretty sure wouldn't compile and I was going to do some commit re-ordering squashing so we get a lot of context but preserve bisect. Currently halted at emulator test failure as mentioned, but that was my plan

2022-06-28 01:18 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +            BackendFactory.INSTANCE.setDefaultLanguagesFromLocales(Arrays.asList(langConfig.locale));
It's part of the call chain that's failing right now, apropos

2022-06-28 01:50 UTC, david-allison commented
Replies:

> Before I spend much more time on this, I'd appreciate it if you could let me know whether you're amenable to the changes in [b02515b](https://github.com/ankidroid/Anki-Android/commit/b02515b0f6a403a4e9f278d21620a1b07d0b1232). I was planning to build upon them to look into adding some new backend functionality, and don't really relish the thought of having to add all the extra boilerplate to do so.

It's getting in the way. 100% remove it. No AGPL concerns. It's rare that we have focused, motivated and knowledgeable changes, and I do not want to block these or slow these down. 

This PR starts to leak Proto classes into the view layer (DeckPicker)
- proto classes are (were?) difficult to construct from inside Java, making testing and mocking difficult
- rust's API was unstable, 
- classes were not well documented due to being autogenerated

I have no problem with pure proto usage inside `libAnki`. I'd like to push to not expose them to consumers.

But for now: `@RustCleanup("")` and keep up velocity.

2022-06-28 01:50 UTC, dae commented
I'm back, and will start looking into the issues now.

2022-06-28 06:32 UTC, dae commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/ScopedStorageMigrationIntegrationTest.kt
> +        val INTEGRATION_INTENDED_REMAINING_FILE_COUNT: Int = if (BackendFactory.defaultLegacySchema) 5 else 3
Since this only applies to the legacy_schema=false path, it's probably not a big deal to have it come later

2022-06-28 06:56 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/libanki/DB.java
> +    public static class SupportSQLiteOpenHelperCallback extends AnkiSupportSQLiteDatabase.DefaultDbCallback {
It's protected on the -Backend side as well, since DefaultDbCallback does not call super either

2022-06-28 06:58 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/libanki/DB.java
> +        SupportSQLiteDatabase db = AnkiSupportSQLiteDatabase.withFramework(context, path, new SupportSQLiteOpenHelperCallback(1));
It'll require another backend release to implement

2022-06-28 11:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/DB.java
> +        SupportSQLiteDatabase db = AnkiSupportSQLiteDatabase.withFramework(context, path, new SupportSQLiteOpenHelperCallback(1));
https://github.com/ankidroid/Anki-Android-Backend/issues/214 - deferred

2022-06-28 12:02 UTC, david-allison reviewed
Second round of reviews. One more on the first commit (aiming to get the time to do this later on today)

2022-06-28 12:10 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.kt
> +    abstract fun<T : AbstractDeckTreeNode> quickDeckDueTree(): List<TreeNode<T>>
Even with the large speed improvements of the backend tree code, gathering the deck tree without counts is still faster, and presumably you'd want to take the faster path in the sidebar work that's being done.

2022-06-28 12:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.kt
> +    abstract fun<T : AbstractDeckTreeNode> quickDeckDueTree(): List<TreeNode<T>>
If I'm reading the comment correctly, the 'slow' path is 70 millis on Arthur's collection?

I would expect the `DeckDueTree` to only be used by the DeckPicker, with the other classes using a more specialised class which only cares about `(name, id, isFiltered)` rather than any inkling of scheduling data.

https://github.com/ankidroid/Anki-Android/pull/11644/commits/d4b31eeed5c4cb760a3bfb04648f01e186c77324

@Arthur-Milchior, what are your thoughts on this? I still lean towards future removal, but I'm not massively invested either way.

2022-06-28 12:24 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.kt
> +    abstract fun<T : AbstractDeckTreeNode> quickDeckDueTree(): List<TreeNode<T>>
That's in the emulator on a fast machine; it may be somewhat slower on a slow device. In comparison, I seem to recall the non-count version being around 5ms, since it doesn't need to check cards.

Agreed that QuickDeckDueTree's naming is not great, but the underlying functionality is worth keeping IMHO.

2022-06-28 13:04 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.kt
> +    abstract fun<T : AbstractDeckTreeNode> quickDeckDueTree(): List<TreeNode<T>>
Okay, no pushback. 14x is significant. Thanks

2022-06-28 13:12 UTC, david-allison reviewed
Nothing scary here individually, but it's a massive amount of changes. Treat this as a soft approve and a 'how do we get this merged'?

@mikehardy definitely need to check that each commit compiles, get a second approval, then rebase?

2022-06-28 13:12 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/utils/EnumMirrorTest.kt
> +// class EnumMirrorTest(val clazz: TestData) {
I'm fine for this to go

2022-06-28 14:07 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFilesTest.kt
> +        CompatHelper.compat.deleteFile(File(defaultCollectionSourcePath, "collection.anki2"))
I thought it was alright when I was reading through

2022-06-28 14:11 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
> +            // position 0 is default deck. Different from upstream
Yeah - Damien and I talked about this in a related thing - the idea was that anything flagged or gated with "legacy" or "legacy schema" is about the same compilation fail / greppable power as a RustCleanup so it wasn't a huge deal. They'll be impossible to miss. But RustCleanup is our convention at the moment. I had the same thought here then though "well can't miss it when legacy schema's ripped out" and left it

2022-06-28 14:13 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        }
Agreed good catch - I hadn't considered the filenames-are-PII angle but we don't want to have a round of news articles where *this* time flashcards are used to betray secret military things because filenames are like "the-ICBM-launch-code-is-1235.jpg" or whatever and our Acrarium instance is hacked :facepalm:

2022-06-28 14:14 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/libanki/utils/EnumMirrorTest.kt
> +// class EnumMirrorTest(val clazz: TestData) {
I was curious for your take on this, I had it pending in my current review reading. If you're okay, I'm okay, so EnumMirrorTest is just a delete?

2022-06-28 14:18 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/utils/EnumMirrorTest.kt
> +// class EnumMirrorTest(val clazz: TestData) {
We're removing the one use case it was required for.

We can add the code back in if/when we want to, but most of the reasons for needing it are no longer necessary (better tolling, AnkiDroid is Kotlin, rslib's API is much more stable).

2022-06-28 22:25 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
> +            AlertDialog.Builder(this).setTitle("Not yet supported on new backend").show()
:see_no_evil: nightmare

2022-06-28 22:37 UTC, mikehardy approved these changes
- I'm still n the process of testing commit series now for bisect-ability (that is: each commit compiles and works)
- We need to log an umbrella issue for "fix all things gated by "legacy schema" but otherwise it's good go I think
- I need to test import/export of apkg and colpkg with and without legacy schema

2022-06-28 23:21 UTC, mikehardy commented
Issues with non-legacy schema:

- settings -> sync -> force full sync seems to have no effect with non-legacy schema? Doing a drag-down-to-refresh while on the deck list did seem to affect it though, if you are logged in as one account and have imported some other collection (so they were incompatible). Seems to be just the flag is not set to force it somehow?
- loading card browser in "all decks" mode on a large collection (like, 60,000cards in a colpkg) takes a O(n) on number of cards instead of just visible ones?
- I'm not sure where exporting a deck drops the apkg? It did not pop up a prompt or anything (import of new shared deck worked though...)
- calling "check database" while diagnosing someone's collection problem and also on a known-good collection crashed:

```
06-28 18:06:32.682 21152 21820 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: Caused by: kotlin.NotImplementedError: An operation is not implemented: no longer in backend
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at com.ichi2.libanki.backend.RustTagsBackend.register_tags(RustTagsBackend.kt:27)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at com.ichi2.libanki.TagsV16.register(TagsV16.kt:71)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at com.ichi2.libanki.TagManager.register$default(TagManager.kt:51)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at com.ichi2.libanki.TagsV16.registerNotes(TagsV16.kt:89)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at com.ichi2.libanki.TagManager.registerNotes(TagManager.kt:54)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at com.ichi2.libanki.Collection.rebuildTags(Collection.kt:1964)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at com.ichi2.libanki.Collection.fixIntegrity$lambda-19(Collection.kt:1680)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at com.ichi2.libanki.Collection.$r8$lambda$UED_RUQNy2I1NK8XWD0ZLoOn9xk(Unknown Source:0)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at com.ichi2.libanki.Collection$$ExternalSyntheticLambda16.apply(Unknown Source:4)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at com.ichi2.libanki.Collection.fixIntegrity$lambda-9(Collection.kt:1575)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at com.ichi2.libanki.Collection.$r8$lambda$0Jt_J79UycQZHgRsRUazvOrbiic(Unknown Source:0)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at com.ichi2.libanki.Collection$$ExternalSyntheticLambda13.accept(Unknown Source:8)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at com.ichi2.libanki.Collection.fixIntegrity(Collection.kt:1678)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at com.ichi2.async.CollectionTask$CheckDatabase.task(CollectionTask.kt:717)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at com.ichi2.async.CollectionTask$CheckDatabase.task(CollectionTask.kt:713)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at com.ichi2.async.TaskDelegate.execTask(TaskDelegate.kt:50)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.kt:136)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.kt:98)
06-28 18:06:32.682 21152 21820 E AndroidRuntime: 	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.kt:64)
```

None of these problems happen with legacy schema, so we need to log them but they are not blockers to getting this batch of work merged

2022-06-28 23:21 UTC, mikehardy commented
Now it's just commit series alignment for bisection, I'd like to merge this with no other changes (except commit movement) so I don't have to re-test. Further work should happen on separate PRs if at all possible so we can close off this massive batch o' change

2022-06-28 23:23 UTC, david-allison approved these changes
As long as issues are logged, good to go!

2022-06-29 00:27 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
> +            AlertDialog.Builder(this).setTitle("Not yet supported on new backend").show()
Hah :-) Shouldn't be too bad - most of the business logic is handled by the backend now, so the UI just needs to take care of adding/removing/mutating an in-memory list of templates, then telling the backend to save the changes at the end.

2022-06-29 00:28 UTC, dae commented
I reordered and squashed some of the commits earlier, so further movement is (hopefully) not required. I tested a selection of commits, but did not run the unit tests through every single one since rebasing.

Exporting logs the exported filename with timber, but doesn't go through the rest of the UI process yet (which is bound to the CollectionTask infrastructure)

2022-06-29 00:33 UTC, mikehardy commented
> I reordered and squashed some of the commits earlier, so further movement is (hopefully) not required. I tested a selection of commits, but did not run the unit tests through every single one since rebasing.

Yeah, ktlint fails on the unused import at the end that's from the huge squash. It does look mostly good, I'm just running through a brute force while loop looking for the base commit via rev-parse and popping commits one by one with our CI gradle targets hit, squashing where needed. Nearly out of day for the day, but will finish tomorrow morning certainly

Regarding the CardTemplateEditor

> Hah :-) Shouldn't be too bad - most of the business logic is handled by the backend now, so the UI just needs to take care of adding/removing/mutating an in-memory list of templates, then telling the backend to save the changes at the end.

I saw that magic word "just" (UI just needs to...) hahaha. Doing that in memory list of templates was my first PR in this repo and was perhaps the biggest yak shave of my life. We'll see!

2022-06-29 12:53 UTC, mikehardy commented
(I've got about 5 commits I'm moving around in tiny ways, then the whole commit series is working - the storage migration extraction was pretty easy)

2022-06-29 12:55 UTC, dae commented
Dang, I should have posted when I started on it. :sweat_smile:

2022-06-29 13:08 UTC, mikehardy commented
I've got it completely organized now - sorry for the collision - commit series that I think is bisectable is here, doing a (hopefully final) while loop where I run our CI targets against each commit popping them off one after another

https://github.com/ankidroid/Anki-Android/tree/new-anki2

- merged / rebased on to a test flake PR #11730 
- merged / rebased on to extracted storage migration #11728 
- squashed 3 commits into big commit so that tests worked
- squashed 1 commit into big commit so that ktlint worked 
- squashed 2 code review commits into one
- squashed 2 adjacent commits about deck picker speed / remove argument so it compiled

...and I think it's going to go, we'll see :sweat_smile:

2022-06-29 13:24 UTC, dae commented
I've got a local copy, so feel free to push into the branch whenever it's convenient

2022-06-29 15:23 UTC, mikehardy commented
Local verification done, apart from the comment above I found one more teeny tiny compile break in the series. All patched up now, rebased again on main, pushed to your fork+branch and final CI running now (going to close and re-open to force it)

2022-06-29 15:28 UTC, mikehardy commented
Oh sigh :facepalm: 

> Update - GitHub Actions is now experiencing degraded performance. We are still investigating and will provide an update when we have one.

https://www.githubstatus.com/

2022-06-29 16:12 UTC, merged

2022-06-29 16:13 UTC, mikehardy commented
Wow, what an odyssey, but all in a good way. @dae, thank you  :fist_right: :fist_left: - really cool to be on up to date anki code and have a such a solid base for future work

2022-06-29 16:23 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +fun DeckPicker.handleNewSync(
Any thoughts here would still be potentially interesting as a follow-on PR, if needed

2022-06-29 16:41 UTC, david-allison commented
YESS!!!

![](https://media.giphy.com/media/vtr89lUZqtQRqDmOFP/giphy-downsized.gif)

2022-06-29 20:39 UTC, dae commented
Thanks for all the hard work on pushing this through guys. I'm preparing a follow-up PR that will address some of the posted issues.

2022-06-29 21:42 UTC, mikehardy commented
I'm headed out for some family travels end of this week through mid-August so I won't be able to push nearly that hard (if at all?) for a while but I'll try to keep an eye out and will hit any green github web UI buttons that look good to hit :-)

2022-07-04 17:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +            import anki.search.searchNode
Thanks a lot for this clear documentation. Clearly useful, not only to understand ow to call the function, but also to find out where to search for the different values, given that they are not directly in our codebase so can't be find by a standard search