replaced string.format
ankidroid/Anki-Android pull request #11658
Opened 2022-06-18 18:43 UTC by suman-somu

## Purpose / Description
change the way strings are formatted to improve code quality

## Fixes
Fixes #11449 

## Approach
change ```String.format()``` to ```${ }```

## How Has This Been Tested?
Passed all the test done by  "./gradlew jacocoUnitTestReport" 

## Checklist

- [x] You have not changed whitespaces unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-18 18:56 UTC, david-allison requested changes
Thanks!

the call to `String.format` is no longer necessary if there's no arguments

2022-06-19 01:45 UTC, suman-somu commented
There was a mistake in the description and I have changed it now.

There was arguments in the code, but I didn't mentioned it in the description of the PR.

2022-06-19 02:55 UTC, suman-somu commented
okay, I just understood what did you meant. 

I'm on changing that.

2022-06-21 04:07 UTC, lukstbit approved these changes

2022-06-24 09:32 UTC, krmanik approved these changes

2022-06-24 23:04 UTC, mikehardy approved these changes

2022-06-24 23:04 UTC, merged

2022-07-28 22:04 UTC, Arthur-Milchior commented
@suman-somu By the way, since you were the last one touching bug #11449, do you know whether it was the last format replacement needed, or whether there remains work to do here? To know if it can be closed

2022-08-01 11:17 UTC, suman-somu commented
@Arthur-Milchior There are still files left to do formatting.