Fix paste from browser into note field not working
ankidroid/Anki-Android pull request #11656
Opened 2022-06-17 21:14 UTC by dorrin-sot

## Purpose / Description
Pasting plain text from samsung native browser into note fields wouldn't work.

## Fixes
Fixes #11574

## Approach
rewrote `FieldEditText::onTextContextMenuItem` to paste as plain text using `coerceToText` in `primaryClip.getItemAt(0).coerceToText(context)`.

## How Has This Been Tested?
Emulator:

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-18 00:07 UTC, david-allison requested changes
Looks great to me!

2022-06-18 00:07 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> +            } else if (mClipboard?.hasPrimaryClip() == true) {
don't need an `else` - previous statement is a return

2022-06-18 00:07 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> +                        setText("${text}${getItemAt(0).coerceToText(context)}")
`get(0)` can throw an IndexOutOfBoundsException if you don't check the size.

2022-06-18 19:01 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> +                            setSelection(text!!.length)
Is this correct? If I paste something in, typically I don't want the whole text to be selected. This doesn't match typical UX

2022-06-18 19:05 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> +                            setSelection(text!!.length)
this sets the cursor at the end. `setSelection(0, text!!.length)` would select all

2022-06-18 23:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> +                            setSelection(text!!.length)
Oh, sorry. But again: that isn't the standard UX, right?

2022-06-19 10:37 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> +                            setSelection(text!!.length)
Oh Sorry I didn't think of that. I fixed it now and also added a test

2022-06-28 10:18 UTC, david-allison requested changes

2022-06-28 10:18 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> +            selectionStart.run {
This feels like overuse of scope functions

2022-06-28 10:18 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> +                return true
`selectionStart` is not guaranteed to be smaller than `selectionEnd`. A user can select backwards using a keyboard.

2022-06-28 11:46 UTC, david-allison requested changes

2022-06-28 15:04 UTC, david-allison approved these changes
Thanks! Selection code is horrible

2022-07-05 16:36 UTC, mikehardy approved these changes
alright then :-), quite a fix on this one, thanks!

2022-07-05 16:44 UTC, merged