[GSoC] migrate PerformDowngradeTask to Coroutines
ankidroid/Anki-Android pull request #11651
Opened 2022-06-17 13:33 UTC by divyansh-dxn

## Pull Request template

## Purpose / Description
AsyncTask to Coroutines Migration

## Fixes
Fixes a part of #7108

## Approach
Replaced AsyncTask usage with equivalent suspend function. 

## How Has This Been Tested?
Passes all the unit test and android test

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-19 06:41 UTC, lukstbit requested changes

2022-06-19 06:41 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +            deckPicker.showProgressBar()
There's no need to use the mainDispatcher to show the ProgressBar as we are already on the main thread(because of Activity.lifecycleScope). If this method were to get called from another thread it will immediately fail as we are accessing a view from a background thread.

```
) {
    deckPicker.showProgressBar()
    var exception: Throwable? = null
    // rest of the method
```

2022-06-19 06:41 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +                runCatching {
I would prefer that we keep using `try/catch` instead of `runCatching`. Also, as we look for the general Exception type, I think it would be better to add a check for the exception being a `CancellationException` and rethrow it if it is. This way we guard against the code inside `downgradeCollection()` being migrated to coroutines, throwing CancellationException and us catching that exception. More info about this can be found [here](https://kotlinlang.org/docs/cancellation-and-timeouts.html#cancellation-is-cooperative):

```
} catch (e: Exception) {
    if (e is CancellationException) {
        throw e
    }
    Timber.w(e)
    mException = e
}
```

2022-06-19 08:11 UTC, divyansh-dxn commented
Fixing the failing tests

2022-06-21 12:45 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +                downgradeCollection(deckPicker, deckPicker.backupManager!!)
What about the comment "It would be great if we could catch the OutOfSpaceException here"?

Let's either address it or it can be added back here.

2022-06-21 13:55 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +                downgradeCollection(deckPicker, deckPicker.backupManager!!)
I think current code is pretty clean. Adding on more catch will require one more context switch code. Also `deckpicker.hideProgressBar()` would be called twice for `OutOfSpaceException`.
```kotlin
      try {
               downgradeCollection(deckPicker, deckPicker.backupManager!!)
            } catch (e:CancellationException){
                throw e
            } catch (e: OutOfSpaceException){
                withContext(mainDispatcher) {
                    deckPicker.displayDowngradeFailedNoSpace()
                }
            } catch (e: Exception) {
                Timber.w(e)
                exception = e
            }
            withContext(mainDispatcher) {
                deckPicker.hideProgressBar()
                if (exception != null) {
                    deckPicker.displayDatabaseFailure()
                } else {
                    Timber.i("Database downgrade successful - starting up")
                    // no exception - continue
                    deckPicker.handleStartup()
                    // This call should probably be in handleStartup - but it's also called there onRefresh
                    // TODO: PERF: to fix the above, add test to ensure that this is only called once on each startup path
                    deckPicker.refreshState()
                }
            }
```

2022-06-21 14:41 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        var exception: Throwable? = null
Should be var exception: `Exception?` = null

2022-06-21 15:26 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +                downgradeCollection(deckPicker, deckPicker.backupManager!!)
I think the comment meant that instead of catching that exception in `onPostExecute`, it can be done in `doInBackground`. Anyways, seems like that shouldn't be required now after migrating to coroutines.

2022-06-21 15:27 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +                downgradeCollection(deckPicker, deckPicker.backupManager!!)
@david-allison Can you explain that comment since you had written it?

2022-06-21 15:27 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        var exception: Throwable? = null
Have you written this here as a note to yourself?

2022-06-22 03:06 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        var exception: Throwable? = null
Yes, I wasn't with my laptop and I saw this piece of code so wrote it down so that it doesn't get missed 🥲

2022-06-23 10:05 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +                downgradeCollection(deckPicker, deckPicker.backupManager!!)
Any updates?

2022-06-23 13:29 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +                downgradeCollection(deckPicker, deckPicker.backupManager!!)
Let us merge this.

2022-06-23 13:31 UTC, ShridharGoel approved these changes

2022-06-23 18:29 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> -        Timber.i("Downgrading backend")
And also `I disapprove, but it's best to keep consistency with the rest of the app`, what does it mean?

2022-06-24 04:18 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> -        Timber.i("Downgrading backend")
>  What about the previous comment It would be great if we could catch the OutOfSpaceException here?

I think ShridharGoel is right and it meant to handle the exception directly in doInBackground. As we use coroutines , let the comment be removed.

>  And also I disapprove, but it's best to keep consistency with the rest of the app, what does it mean?

Could be the usage of the AsyncTask could be something else. The comment itself is not very useful and the issue it closes doesn't mention something special as well. I say to remove it.

2022-06-24 08:10 UTC, divyansh-dxn commented
So no more changes, I presume?

2022-06-24 13:53 UTC, lukstbit approved these changes

2022-06-24 13:53 UTC, lukstbit commented
@divyansh-dxn No more changes, I approved the PR.

2022-06-24 19:04 UTC, merged