Kotlin migration ModelTest
ankidroid/Anki-Android pull request #11665
Opened 2022-06-21 05:38 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
Kotlin Migration of ModelTest

2022-06-25 16:12 UTC, Prince-kushwaha commented
@david-allison how i fix below unit test error if i not made change in UpgradeGesturesToControlsTest.kt
<img width="620" alt="Screenshot 2022-06-25 213851" src="https://user-images.githubusercontent.com/65972015/175781826-e39a833a-06ce-4c88-bd89-ce0050c4fda4.png">

2022-06-25 16:34 UTC, mikehardy commented
@Prince-kushwaha that failure is a flaky test - it's actually our most common flake at the moment, pretty irritating - hopefully either someone has time to fix it soon or I'll have to disable it in CI https://github.com/ankidroid/Anki-Android/issues/11091#issuecomment-1130226317

2022-07-07 05:34 UTC, lukstbit requested changes
Has conflicts at the moment.

2022-07-10 08:13 UTC, lukstbit requested changes

2022-07-10 08:13 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
> +class ModelTest : RobolectricTest() {
Add two cleanups:
```
@KotlinCleanup("fix IDE lint issues")
@KotlinCleanup("improve kotlin code where possible")
```

2022-07-10 08:13 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
> -    public void getDid_test() {
Why did you delete this test method?

2022-07-10 10:53 UTC, Prince-kushwaha commented on AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
> +class ModelTest : RobolectricTest() {
ok

2022-07-10 16:56 UTC, lukstbit approved these changes

2022-07-30 18:13 UTC, mikehardy commented
Oh no, @Prince-kushwaha sorry about this - it appears to have taken a conflict before I had any time to work through the second review queue and get things merged. I'm really sorry about that. Do you have time to fix the conflict?

2022-07-31 14:50 UTC, Prince-kushwaha commented
@mikehardy i fixed the conflict

2022-07-31 18:26 UTC, Arthur-Milchior approved these changes

2022-07-31 18:26 UTC, merged