Kotlin Migration TimePreferenceTest
ankidroid/Anki-Android pull request #11666
Opened 2022-06-21 13:27 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
Kotlin Migration Of TimePreference Test

2022-07-02 13:04 UTC, lukstbit requested changes

2022-07-02 13:04 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/preferences/TimePreferenceTest.kt
> + *
When doing a migration the copyright header shouldn't be changed. Please revert all changes done to this copyright block.

2022-07-03 21:51 UTC, david-allison reviewed
Happy to merge once copyright is fixed

2022-07-05 16:59 UTC, Prince-kushwaha commented
@david-allison copyright is fixed

2022-07-05 17:01 UTC, Prince-kushwaha commented on AnkiDroid/src/test/java/com/ichi2/preferences/TimePreferenceTest.kt
> + *
it is fixed

2022-07-07 00:26 UTC, david-allison commented
> @david-allison copyright is fixed

There should be no diff on the copyright, it's still showing: https://github.com/ankidroid/Anki-Android/pull/11666/commits/8cd00a482e9c69ffe4ad1906e5b4f9e8a277eebf

2022-07-09 09:54 UTC, Prince-kushwaha commented
how i revert all changes done to this copyright block?

2022-07-10 07:34 UTC, lukstbit commented
@Prince-kushwaha 
- copy the copyright header from before(here's the [current file](https://github.com/ankidroid/Anki-Android/blob/7082f6ee93ed165180b935dbca44598a6566b3cc/AnkiDroid/src/test/java/com/ichi2/preferences/TimePreferenceTest.java) that you can use) and paste it instead of the copyright that you changed from your PR
- use `git commit --amend` to change the last commit in this PR 
- then force push this PR

2022-07-10 10:49 UTC, Prince-kushwaha commented
@lukstbit [](https://github.com/ankidroid/Anki-Android/blob/7082f6ee93ed165180b935dbca44598a6566b3cc/AnkiDroid/src/test/java/com/ichi2/preferences/TimePreferenceTest.java)[current file](https://github.com/ankidroid/Anki-Android/blob/7082f6ee93ed165180b935dbca44598a6566b3cc/AnkiDroid/src/test/java/com/ichi2/preferences/TimePreferenceTest.java) copyright header  and my  kotlin file copyright header is same

2022-07-10 10:52 UTC, Prince-kushwaha commented
@lukstbit i apply [this method](https://github.com/ankidroid/Anki-Android/pull/11666#issuecomment-1179674242) to revert copyright header but it not work because  java file copyright header and my kotlin file copyright header is same

2022-07-10 10:54 UTC, Prince-kushwaha commented
I not understand why git show difference

2022-07-10 17:03 UTC, lukstbit reviewed
The copyright still shows a diff but I'm approving, there's no need to get hung up on this with such a small class.

2022-07-10 17:04 UTC, lukstbit approved these changes

2022-07-30 18:15 UTC, mikehardy approved these changes
yeah, no reason to hang up on spacing for the copyright on a small test file, since the copyright *is* still correct, let's get this in + done. Thanks for the help @Prince-kushwaha

2022-07-30 18:15 UTC, merged