[GSoC] Filter Bottom Sheet implementation
ankidroid/Anki-Android pull request #11663
Opened 2022-06-20 11:15 UTC by viciousAegis

## Pull Request template

## Purpose / Description
Add a Bottom Sheet with filter options like those of Anki Desktop

## Approach
A Modal Bottom Sheet has been used to create the filter screen, and an FAB has been created in Card Browser to open the bottom sheet.
The Filters are displayed as items in a RecyclerView layout, with a different layout for each heading.
For the underlying filtering mechanism, the names of the selected items are stored in lists, and then a search query is generated using those items.

## How Has This Been Tested?

TODO: need to add tests
![1655723333265](https://user-images.githubusercontent.com/86671025/174589362-4d4b7d77-bd87-4b5d-8dc1-bb2f3bd47d62.jpg)
![1655723333258](https://user-images.githubusercontent.com/86671025/174589640-40d296c8-f6c6-494a-b2b2-7d7a50f2a855.jpg)

![1655723333252](https://user-images.githubusercontent.com/86671025/174589393-18cde119-46d8-4e9a-9854-8e3c821a20a7.jpg)
![1655723333226](https://user-images.githubusercontent.com/86671025/174589399-e49f490b-6024-4433-abb9-9f5e7fd92246.jpg)
![1655723333219](https://user-images.githubusercontent.com/86671025/174589409-27a55c88-3c1b-48d3-8db9-d117cde136e9.jpg)

https://user-images.githubusercontent.com/86671025/174589517-d2861f67-bafe-4397-a607-5f70d7dbf7ba.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-20 18:27 UTC, Akshay0701 requested changes
Nice work @viciousAegis, More imporvements can be done in UI part, 
as BrayanDSO suggested on discord that colour can be primary for apply button and gray or some dull colour to cancel button, 

and do you planned to implement any search option for filter? i personally don't see any major use of it, but because you mentioned in your proposal regrading search bar for filters,

I commented few questions

2022-06-20 18:52 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/BottomSheetFragment.kt
> +            deckSearchItems.remove(item)
Yes, as query is constructed only when "apply" is clicked

2022-06-20 19:08 UTC, BrayanDSO commented
Copying from discord:

I don't have the time currently to review anything, but I've noticed that the icons files has filter_sheet_ on their names
And since I believe that icons should be reusable on other places of the app, I think it would be best to remove this prefix from the file names

2022-06-21 03:20 UTC, viciousAegis commented
> and do you planned to implement any search option for filter? i personally don't see any major use of it, but because you mentioned in your proposal regrading search bar for filters,

@Akshay0701 as you can see here, i have around 30-40 decks and even more tags, so it will take a lot of scrolling and searching to find them, and for people with even more decks and cards, it will be very tedious to search. That is why I think a search bar will be really helpful

2022-06-21 03:25 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/BottomSheetFragment.kt
> +                    " OR is:'${cardStateList[cardStateIndex]}'"
AND in filters is being used to join two different types of filters: eg: if we select `deck1`, `deck2`, and `tag1`, The search query will be `(deck:deck1 OR deck:deck2) (tag:tag1). Using them in parenthesis signifies `AND`. So for the same type of filters I am using OR and two join with different filter I am using AND.

I couldn't think of a way I can give the user a choice between the query `deck:deck1 OR deck:deck2` and `deck:deck1 AND deck2`, so this is based on what I think is natural while selecting. In this example, I would like to see cards with the `tag1` tag, which also belong to either of `deck1` or `deck2`

2022-06-21 03:30 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/BottomSheetFragment.kt
> +     */
Currently, if I select filters and before I can press `APPLY`, if I accidentally swipe down, the filters are cleared. This is not ideal as we would only want the filters to be cleared if a `Clear` button is clicked (not added yet) or `CLOSE` is clicked. I hope this explains the problem well

2022-06-21 03:31 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/BottomSheetFragment.kt
> +            }
Yes, the final state of the filter sheet will be with a tree structure, currently I am not well versed with it but I will take reference to the deck and tag selection dialogs which implement this

2022-06-21 03:31 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/BottomSheetFragment.kt
> +        val cardStates = listOf("New", "Learn", "Review", "Suspended", "Buried")
I will look for it, not sure

2022-06-21 03:32 UTC, viciousAegis commented on AnkiDroid/src/main/res/drawable/rounded_bottom_sheet_dark.xml
> +    <solid android:color="@color/theme_dark_primary" />
Yes, I think you are right, I'll make the changes and test them

2022-06-24 08:50 UTC, david-allison commented
Is there plans for this to use hierarchical tags later?

2022-06-24 09:18 UTC, viciousAegis commented
@david-allison Yes, the final plan is to implement both tags and decks hierarchically; I'm not well versed with hierarchical setups yet, so I will implement it later on

2022-06-25 13:17 UTC, viciousAegis commented
@BrayanDSO @Akshay0701 updated the media for the newer UI [here](https://github.com/ankidroid/Anki-Android/pull/11663#issue-1276769039)

2022-06-25 13:20 UTC, Akshay0701 commented
looks better, I will test this on my phone

2022-06-25 14:07 UTC, david-allison requested changes
```

> Task :AnkiDroid:lintPlayDebug FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/drawable/filter_sheet_deck_names_icon.xml:1: Error: The resource R.drawable.filter_sheet_deck_names_icon appears to be unused [UnusedResources]
<vector android:height="24dp" android:tint="#000000"
^
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/drawable/filter_sheet_tag_names_icon.xml:1: Error: The resource R.drawable.filter_sheet_tag_names_icon appears to be unused [UnusedResources]
<vector android:height="24dp" android:tint="#000000"
^
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/strings.xml:4: Error: The resource R.string.filter_sheet_heading appears to be unused [UnusedResources]
    <string name="filter_sheet_heading">Filters</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 errors, 0 warnings

```

I'm tempted to ask for a "semi-hierarchical" approach if it seems good with you:

* Copy the section of the string after the last `::`
* Count the number of `::` in the original string. 
* For each `::`: Add a tab character to the start of the "string copy"

I'm happy for you to say "no" or "it doesn't look good", only the CI issues are blocking to me

2022-06-25 16:41 UTC, BrayanDSO commented
Haven't looked at the code, but I see as future TODOs:
1. Add the respective flag icon before each flag (Red, Blue, etc)
2. Fix some colors (in the video I can't read the text of selected items)
3. Rename BottomSheetFragment.kt because it's not a generic bottom sheet fragment we can use anywhere else.

2022-06-25 18:04 UTC, viciousAegis commented
> ```
> 
> > Task :AnkiDroid:lintPlayDebug FAILED
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/drawable/filter_sheet_deck_names_icon.xml:1: Error: The resource R.drawable.filter_sheet_deck_names_icon appears to be unused [UnusedResources]
> <vector android:height="24dp" android:tint="#000000"
> ^
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/drawable/filter_sheet_tag_names_icon.xml:1: Error: The resource R.drawable.filter_sheet_tag_names_icon appears to be unused [UnusedResources]
> <vector android:height="24dp" android:tint="#000000"
> ^
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/strings.xml:4: Error: The resource R.string.filter_sheet_heading appears to be unused [UnusedResources]
>     <string name="filter_sheet_heading">Filters</string>
>             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 3 errors, 0 warnings
> ```
> 
> I'm tempted to ask for a "semi-hierarchical" approach if it seems good with you:
> 
> * Copy the section of the string after the last `::`
> * Count the number of `::` in the original string.
> * For each `::`: Add a tab character to the start of the "string copy"
> 
> I'm happy for you to say "no" or "it doesn't look good", only the CI issues are blocking to me

I'll be happy to do that; I was the one who did the [semi-hierarchical display](https://github.com/ankidroid/Anki-Android/pull/10389) of the deck selection dialog anyway, so I know what I have to do :P Will be ready soon!

2022-06-25 18:07 UTC, viciousAegis commented
> 2. Fix some colors (in the video I can't read the text of selected items)

I'm using the same text colors as the Navigation Drawer currently, didn't use accessibility scanner on it; Should I go darker?

2022-06-25 18:12 UTC, viciousAegis commented
Also, @david-allison , The FAB to open the filter sheet is still only a temporary solution, as FABs are not meant to be used to open  bottom sheets according to material guidelines.

What I had in mind was shifting the search icon in the app bar to a search bar, and putting the filter button there instead like below:

![image](https://user-images.githubusercontent.com/86671025/175785507-50bb77e0-5656-4b46-892f-7b87f8d872d9.png)

Is that taking too much vertical space on the browser? Any other suggestions on how to accommodate an easy to access button for the filter sheet?

2022-06-26 19:37 UTC, viciousAegis commented
@david-allison Semi hierarchical decks/tags are a go
<img width="300" alt="image" src="https://user-images.githubusercontent.com/86671025/175830985-a307928e-2e1f-44f0-a407-993c0b916641.png">
<img width="291" alt="image" src="https://user-images.githubusercontent.com/86671025/175831001-31a264c1-fe89-4a93-b12c-930b0281e445.png">

2022-06-26 20:12 UTC, david-allison reviewed
I like this. I'd be happy to merge as-is, as it's a massive improvement already

I think we need to talk about the commits, and whether we want to squash this, or split it into clean atomic commits. @viciousAegis, what do you think is best?

From a UX perspective:

- We need to think about what happens when the user taps away to close the modal (probably a 'apply/discard/cancel' dialog?)
- I think we want to preserve state: the filters should be additive or subtractive to the current query, rather than replacing it.
- EDIT: I want to mention animations as something to add to the 'If we have time' list, not in this commit.

2022-06-26 20:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +        "\t\t".repeat(nameArr.size - 1) + nameArr[nameArr.size - 1]
nit: I'd use `.last()`

2022-06-26 21:52 UTC, Arthur-Milchior commented
@viciousAegis 

In case you missed it, a test fails

> CollectionTaskSearchCardsTest > searchCardsNumberOfResultCount FAILED
    Wanted but not invoked:
    taskListener.onPostExecute(
        <Capturing argument>
    );
    -> at com.ichi2.async.CollectionTaskSearchCardsTest.searchCardsNumberOfResultCount(CollectionTaskSearchCardsTest.kt:57)
    However, there were exactly 2 interactions with this mock:
    taskListener.onPreExecute();
    -> at com.ichi2.async.CollectionTask.onPreExecute(CollectionTask.kt:140)
    taskListener.onProgressUpdate(
        [com.ichi2.anki.CardBrowser$CardCache@c7b8224b]
    );
    -> at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.kt:146)
        at com.ichi2.async.CollectionTaskSearchCardsTest.searchCardsNumberOfResultCount(CollectionTaskSearchCardsTest.kt:57)

2022-06-26 21:57 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/BottomSheetFragment.kt
> +        val cardStates = listOf("New", "Learn", "Review", "Suspended", "Buried")
This is kind of similar com.ichi2.libanki.Consts.Card_QUEUE, except that this one has even more option, such as distinguishing manually buried and buried as a sibling of a reviewed card.

I admit I can't imagine where else we would have used this list otherwise

2022-06-26 21:58 UTC, Arthur-Milchior commented
Love what I'm seeing. One small nit for a next time. It would be nice if you could activate the option in your phone to record where you press. This can be done with accessibility option, as it highlights the part of the screen that is pressed. I suppose most app can do it automatically. 
I find videos easier to follow when I know what the person did instead of having to guess it.

2022-06-26 23:25 UTC, Arthur-Milchior commented
Regarding decks and subdecks. When you search for a deck, you also get the results from subdeck. It would be nice to reflect it by automatically selecting all subdeck when you click on a deck. And if you unselect a subdeck, unselecting its parent.

As David mentioned, I'd love for last selection to be recorded, to be able to edit it next time I open the menu.
This would mean that we also need to be able to just clear the selection entirely, so that we don't have to manually cancel everything.

I believe that as soon as you select at least one deck, you should automatically remove the current cardbrowser deck restriction (because otherwise you can have contradictory and unsatisfiable deck constraints)

I think it would be nice if a long click would allow to select things such as "excluding". E.g. being able to state I want to do a search excluding cards with red flag.

Opening the list of deck takes more than a second on my collection. And clicking a second time has the consequence of closing the deck again. So I believe it would be nice to ensure that when you double click, the second click is not taken into account.
A symbol indicating that the request was received would be nice, but I don't see a way to make it work properly without it being flickery for people with a small number of decks.

It seems to me there is a quite a lot of copy-pasted code. I'm sure there are at least some utilities function that can be created to avoid some of it. Maybe even  having some abstract class that is implemented once for each section, which have abstract method in charge of listing content of the lines the user can select, and generating the search content. I'd love it for at least two reasons:
* It would separate the architectural decision we take, and the actual implementation for the five categories
* if we decide to do some change (e.g. long press, or selecting while a keyboard modifier is pressed, or whatever), we don't have to do the change five times

As far as committing goes, this seems to be far too big for me to realistically review and discuss architectural decisions. So I believe I'd love:
1. to have a first PR with Models.all_names. This one should be merged very quickly, and is easy to test. 
2. To have one PR which concentrate on one kind of selection. Maybe just flags, it's a really easy one. This way, it'll be simple to review and we should relatively quickly be able to add this first feature
3. once we agree it's a good implementation, abstract the code we obtained, so that we got our architectural pattern that we can repeat four times, and the concrete implementation from flags.
4. then add another PR for another kind, let's say tags, and check that our abstraction was the right one in that it indeed allows to easily extend it to do create the tag part of the browser filtering
5. finally add the three extra search. As I've already hinted above, I am certain the hierarchical search will have discussions in their own right, so it may be nice to have a PR to discuss each one individually

2022-06-26 23:40 UTC, Arthur-Milchior requested changes

2022-06-26 23:40 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +            for (deckIndex in deckList.indices) {
I'd love if we could avoid the parenthesis when there is a single deck.

2022-06-26 23:40 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +                    "(deck:'${deckList[deckIndex]}'"
Actually, anki only allow double quote around search, not single one. Which is probably a good think as single quote can appear in deck name, and that would break your search

2022-06-26 23:40 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +        var filterQuery = ""
If you need to change a string by appending to it a lot, you should use a buffer instead. If people do big search, it may be more efficient (I admit that this would require a lot of selected deck to matter here)
In any case, it's not a proper way to do this in Kotlin

2022-06-26 23:40 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +            for (deckIndex in deckList.indices) {
In Kotlin, you can often avoid doing explicit loop. In this case, you could do 

`deckList.indices.joinToString(prefix="(", separator = " OR ", postfix =")") { """"deck:${deckList[it]}"""" }`

2022-06-26 23:40 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +            filterQuery += ')'
It would be nice to have a space between ) and (.

2022-06-27 01:39 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +            for (deckIndex in deckList.indices) {
I suggest you hold off on this part until https://github.com/ankidroid/Anki-Android/pull/11644 is merged. I've exposed the backend method to build search queries, which will take care of correctly quoting text and escaping wildcards: https://github.com/ankidroid/Anki-Android/pull/11644/commits/0a1ce9a837453482551c9033fb37ff2532cd663c

2022-06-27 02:12 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +            for (deckIndex in deckList.indices) {
Chiming in on that one :point_up: / #11644 Damien and I are pretty close on it, could be tomorrow (it's night here, I'm almost done for the day). So this will not be a long wait, I intend to complete it before I shift attention to other work so it doesn't drag out anymore

2022-06-27 19:05 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +            for (deckIndex in deckList.indices) {
parenthesis is there for using the `AND` operator with other filter types. To remove the parenthesis we will have to check if all other filter types are empty

2022-06-27 22:38 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +            for (deckIndex in deckList.indices) {
Wonderful.
There are still a lot of things to work on in this PR anyway, there is chance you are done before the PR is ready for merge even if you didn't ask to hold off.

What I still fail to understand is how you came to comment here. Even with the PR title, unless you already know GSoC project well enough to correctly guess that "filter bottom sheet" are related to implementing search in the browser, I can't guess how you found out that you had one relevant comment to put here.

2022-06-27 23:09 UTC, david-allison reviewed
Checked the code. Nothing major, just style/readability.

I'd like at least one test here, to prove that it's possible to test, and to make sure the architecture of the class allows for testing.

2022-06-27 23:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> + * TODO: can these be unified?
Don't worry about this for now, it's easier to fix no abstraction than it is to fix a bad abstraction

2022-06-27 23:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/ModelManager.kt
> +    abstract fun allNames(): List<String>
can be rebased onto main so this commit can be dropped.

2022-06-27 23:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +@Suppress("DEPRECATION")
This shouldn't be on the top of the class, it should be on the specific methods and explain why they're deprecated

2022-06-27 23:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +    var cardStateSearchItems = mutableListOf<String>()
Could you typealias `String` here and briefly document what each of these represents

2022-07-24 17:11 UTC, Arthur-Milchior commented
I removed the review tags since this one will not be actually be reviewed for merging, but is split in parts

2022-08-19 01:26 UTC, mikehardy commented
If it will be split apart I'll move it to draft so it falls into a different queue of mine, cheers

2022-12-04 15:36 UTC, closed without merging