replaced lifecycleScope.launch() with lifecycleScope.launchCatching()
ankidroid/Anki-Android pull request #11679
Opened 2022-06-22 15:56 UTC by divyansh-dxn

## Description
Extracted away repeating code to an extension function and replaced it.

## How Has This Been Tested?
Unit tested

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-23 04:22 UTC, lukstbit requested changes

2022-06-23 04:22 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/async/CoroutineHelpers.kt
> +            Timber.w(throwable, errorMessage)
I think we should use `Timber.e()` as we are dealing with exceptions.

2022-06-23 04:38 UTC, dae commented
I have very little experience with AnkiDroid's code, so apologies if I have misunderstood something here.

My reading of this code is that it logs the error to the Android logs, and then silently returns without notifying the user - only developers, or users who have logcat attached will actually be able to see the message. Is that correct? If so, might it not perhaps be better to notify the user than an error occurred?

2022-06-23 06:54 UTC, divyansh-dxn commented
That's appropriate. In this case, I think your implementation is quite robust. So will use that.

https://github.com/ankidroid/Anki-Android/commit/e20ad8a5fb01abec12ec7d95ab8b0156b3c92328#diff-ab2a7a47110cd7660b276c059e8612c4586f636533d31b36f631808c6558cc73R30

2022-06-23 12:22 UTC, ShridharGoel commented
Can you include a video showing how the SnackBar looks like in case on an error?

2022-06-23 12:44 UTC, divyansh-dxn commented
Also, the default LENGTH_LONG wasn't long enough (2750 ms), so I set a default value of 5000 ms. I think would be enough timeout to read the error.

2022-06-23 13:12 UTC, ShridharGoel commented
@divyansh-dxn The SnackBar is a little above the bottom of the screen. Is that expected here because of some reason?

2022-06-23 14:49 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/async/CoroutineHelpers.kt
> +            Timber.w(throwable, errorMessage)
Thanks Shridhar - indeed - "dealing with exceptions" can happen in entirely normal code flows that only warrant a Timber.d in some cases (think: attempting reflection on a method you know may not be there). So "dealing with exceptions" is !== Timber.e for me. My thought process is always "what does this *mean* for the app?" when deciding level. Is it something I want to know was a near-disaster when I look at the crashlog from ACRA and follow the logcat snippet (error)? Or is it serious but we thought we recovered (warn)? Is it an important clue to where the user was but not a problem (info)?

2022-06-23 15:20 UTC, divyansh-dxn commented
<img width="200px" src="https://user-images.githubusercontent.com/69595691/175334228-a85dafd3-87af-498a-9f9a-0b727998cb31.jpeg"></img>

Behaviour is the same in the main branch as well, for login and probably everywhere.

2022-06-23 18:16 UTC, lukstbit commented
> Only happens when I'm in gesture navigation mode. IDK, maybe a Realme UI thing, if you could check it out on any other device let me know. I have only Realme devices around me sweat_smile.

It happens on an emulator as well, most likely because the showDismissibleSnackbar() method is looking for a parent with an id R.id.root_layout which is not found in Statistics for example. When used with android.R.id.content it shows correctly.

The current coroutine code using CoroutineExceptionHandler does indeed silence exceptions to Logcat.  The previous code using AsyncTasks simply crashed when encountering an exception and let the user send a report though a dialog if he wanted.

I would say to simply use a launch coroutine builder without the exception handler and follow the previous behavior of crashing and sending a report.

2022-06-23 19:37 UTC, ShridharGoel commented
We can also handle the exception and trigger an ACRA report directly through code.

2022-06-24 04:19 UTC, lukstbit commented
I'm ok with either versions(simple launch vs launch with exception handler and sending an ACRA report).

2022-06-24 13:58 UTC, divyansh-dxn commented
I see that `CrashReportService.sendExceptionReport(e,activity::class.java.simpleName)` silently sends the crash report, wouldn't it be nice to show a popup with the error report and ask user to click on `send or cancel`. I am just asking, not an expert in UX.

2022-06-24 16:01 UTC, mikehardy commented
> I see that `CrashReportService.sendExceptionReport(e,activity::class.java.simpleName)` silently sends the crash report, wouldn't it be nice to show a popup with the error report and ask user to click on `send or cancel`. I am just asking, not an expert in UX.

No, these are specifically for things that we are tracking "if possible" for technical reasons, like "the rust library loading seems to fail about one in ever million times for some reason, but we're not sure *exactly* how often so we do not know if we should worry or not. In the rare cases it fails we will try to track it".

It only sends the report if the user has accepted "send always" as a specific opt-in on their part, otherwise they are dropped and that's okay. It's a lossy non-interactive method on purpose

2022-06-24 18:57 UTC, ShridharGoel approved these changes

2022-06-25 15:51 UTC, lukstbit requested changes

2022-06-25 15:51 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt
> +        val root = activity.findViewById<View>(R.id.root_layout)
Using R.id.root_layout causes the mentioned visual artifact. Could you please use instead the activity root Framelayout which has the id `android.R.id.content`?

2022-06-25 15:51 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/async/CoroutineHelpers.kt
> +    } catch (e: BackendException) {
There's no need to have two catch clauses doing the same thing(the difference in strings is too small). We should simply use just:

    } catch (e: Exception) {
        // TODO: localize
        Timber.w(e, errorMessage)
        showDismissibleSnackbar(activity, "An error occurred: $e", R.string.close)
        CrashReportService.sendExceptionReport(e, activity::class.java.simpleName)
    }

2022-06-26 04:30 UTC, divyansh-dxn commented
Test restart is required

2022-06-26 05:11 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> -import androidx.lifecycle.lifecycleScope
This import can't be deleted because there's another usage of `lifecycleScope` inside DeckPicker which makes the CI fail completely.

2022-06-27 03:39 UTC, lukstbit approved these changes

2022-06-28 00:50 UTC, mikehardy approved these changes
All seems reasonable, thanks @divyansh-dxn for posting this and @ShridharGoel + @lukstbit for the review!

2022-06-28 00:55 UTC, merged