[GSoC] migrated LoadPronunciationActivity to Coroutines
ankidroid/Anki-Android pull request #11681
Opened 2022-06-24 07:38 UTC by divyansh-dxn

## Purpose / Description
AsyncTask to Coroutines migration

## Fixes
Fixes a part of #7108

## How Has This Been Tested?
Runs as expected on Pixel 3a Emulator API 31 and Realme 6i API 30

https://user-images.githubusercontent.com/69595691/175486531-272b16ff-5713-4fdd-bca1-654da9526a27.mp4

https://user-images.githubusercontent.com/69595691/175486304-da932a38-54cc-4c4e-bea3-15178c47c4b6.mp4

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-24 18:57 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +import kotlinx.coroutines.*
Let's avoid wildcard imports.

2022-06-24 18:58 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +    private lateinit var mPostTranslationJob: Job
Remove usage of Hungarian notation,

2022-06-24 19:01 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +                mPostPronunciationJob = lifecycleScope.launch { backgroundPost(mPronunciationAddress) }
Is the `launchCatching` method not needed here?

2022-06-24 19:02 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +                mDownloadMp3Job = lifecycleScope.launch { downloadFile(mMp3Address) }
Is the `launchCatching` method not needed here?

2022-06-25 03:11 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +                mDownloadMp3Job = lifecycleScope.launch { downloadFile(mMp3Address) }
It is on a different branch that hasn't been merged yet.

2022-06-25 03:18 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +    private lateinit var mPostTranslationJob: Job
All the variables? I think that could another PR in itself. Trying to keep the migration independent of other changes.

2022-06-25 15:30 UTC, lukstbit requested changes

2022-06-25 15:30 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
>          } catch (e: Exception) {
This try/catch will not work. So this catch code needs to go inside a CoroutineExceptionHandler placed on the above coroutine.

2022-06-25 15:30 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
>              } catch (e: Exception) {
This try/catch is useless, also there's no need to use launchCatching because this is a coroutine stated inside another coroutine and an CoroutineExceptionhandler is not triggered for inner coroutines.

2022-06-25 15:30 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
>              } catch (e: Exception) {
Same as above for this try/catch.

2022-06-25 16:01 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +    private lateinit var mPostTranslationJob: Job
Only the variables which have been changed in this PR.

2022-06-27 08:56 UTC, lukstbit requested changes
With the two requested changes, I'm ok with the code. It can be refactored and improved but in its current form it lets us get rid of the AsyncTask deprecation for this class.

2022-06-27 08:56 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +            postPronunciationJob = lifecycleScope.launch { backgroundPost(mPronunciationAddress) }
We need to add a CoroutineExceptionHandler with the code in the deleted catch block to this `launch` because this coroutine is created directly from the scope so its a root coroutine.

2022-06-27 08:56 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +            downloadMp3Job = lifecycleScope.launch { downloadFile(mMp3Address) }
Same, needs a CoroutineExceptionHandler with the code from the catch block.

2022-06-28 11:08 UTC, lukstbit approved these changes

2022-06-28 18:54 UTC, ShridharGoel approved these changes

2022-06-28 18:54 UTC, merged