Change flag colors for light and dark themes for better accesibility
ankidroid/Anki-Android pull request #11687
Opened 2022-06-24 20:38 UTC by viciousAegis

## Pull Request template

## Purpose / Description
To make the text on flagged cards more readable

## Fixes
Fixes #11671 
## Approach
Choose shades of colors that pass the accessibility scanner

## How Has This Been Tested?

### Before
![1655962500220](https://user-images.githubusercontent.com/86671025/175663824-4399842b-1101-492d-ad84-ff93bcef9347.jpeg)

### After
### Light mode
![1656102804254](https://user-images.githubusercontent.com/86671025/175663514-8be1258c-6bfc-4922-abc6-d0861972b0ba.jpeg)

### Dark mode - only the orange color doesn't pass accessibility, but if I make it any darker it wouldn't be a shade of orange anymore so left it there
![1656102804261](https://user-images.githubusercontent.com/86671025/175663540-6fb6f029-f8b8-4828-accb-524024a13aa6.jpeg)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-24 21:27 UTC, BrayanDSO commented
This changes not only the background colors but the flag colors as well (i.e. the flags shown on the reviewer). 

Can you keep the flag colors separated from the background colors? Mostly because
1. These new colors will contrast well with text color, but not with the background color on the reviewer
2. Keeping resemblance of the flags (not necessary for the backgrounds you are changing) with Anki Desktop would be best for people to recognize the flags (especially for color blind people)

2022-06-25 11:17 UTC, dorrin-sot commented
Can you also change the color for marked cards? The purple flags look very similar to the color of marked cards.

2022-06-25 13:26 UTC, viciousAegis commented
@dorrin-sot how do you think marked cards should be shown? We can have a star icon, but I would not like to shift the card to the right as there is already limited horizontal shift.  Would it be better if, say, a marked card is shown with a star on the top right/left ?
Open to suggestions for this

2022-06-25 14:28 UTC, dorrin-sot commented
> Would it be better if, say, a marked card is shown with a star on the top right/left ?

Hmm sounds good :)

2022-06-25 20:21 UTC, BrayanDSO commented
Here how Anki desktop handle marked (down) VS purple (upper)

![image](https://user-images.githubusercontent.com/69634269/175789359-89388984-37f9-4f31-a3d1-060c48d375d0.png)

![image](https://user-images.githubusercontent.com/69634269/175789362-5d894a0d-76ea-46c3-a468-9d7cc9f34645.png)

Dark theme marked color doesn't pass acessibility, but the overall idea persists:

dark/strong purple for purple flag
light purple for marked

2022-06-26 04:24 UTC, dorrin-sot commented
@BrayanDSO But the issue of cards that are marked and flagged only being shown as flagged still exists there too (I can report the issue in their repo too)

2022-06-26 19:57 UTC, BrayanDSO commented
> @BrayanDSO But the issue of cards that are marked and flagged only being shown as flagged still exists there too (I can report the issue in their repo too)

I'd propose the change on upstream first then here. But this is open source, so whatever

2022-06-27 04:04 UTC, viciousAegis commented
For now, I will change the color of marked to a different shade of purple, and then when I work on the card views, I'll see how to implement it

2022-06-27 15:17 UTC, david-allison requested changes
One request so we have the reviewer colors consistent and documented. Rest looks good to me

2022-06-27 15:17 UTC, david-allison commented on AnkiDroid/src/main/res/drawable/ic_flag_orange.xml
> +      android:fillColor="#ff9800"/>
Can we extract these "reviewer" constants to resources?

2022-06-27 23:16 UTC, david-allison approved these changes
Beautiful

2022-06-28 16:11 UTC, merged