[GSoC] Filter Sheet: Add filters for flags
ankidroid/Anki-Android pull request #11713
Opened 2022-06-27 19:50 UTC by viciousAegis

## Pull Request template

## Purpose / Description
To add a filter sheet, currently having filters based on flags

## Approach
Create bottom sheet for filter options

## How Has This Been Tested?

![image](https://user-images.githubusercontent.com/86671025/176023656-7b56fafc-97e3-44b1-94df-6d2212e0b7e2.png)

![image](https://user-images.githubusercontent.com/86671025/176023735-22bae61f-6bb5-47c9-b2e1-2614156e5ae6.png)

https://user-images.githubusercontent.com/86671025/176023621-be344b1b-4a1b-412c-b8c0-3d5b36bde23a.mp4

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-27 19:51 UTC, viciousAegis commented
@ankidroid/gsoc-mentor The first PR for the actual bottom sheet with filters only for flags implemented.

2022-06-27 23:11 UTC, Arthur-Milchior reviewed
Thanks a lot. Great work. Quite a lot of small remarks here and there. I'm really thankful that you split the original PR, I feel like it's far easier to review now. And hopefully, concentrating on just flags means other part will be easier since some part of the work can be abstracted or modified in the same way

2022-06-27 23:11 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +        if (BottomSheetFragment().flagSearchItems.contains(itemName.text)) {
I'm pretty sure this is wrong. You probably do NOT want to be creating a new bottom sheet fragment here. Plus than means that you're using a new `flagSearchItems` that is always empty, so the condition must always be false

2022-06-27 23:11 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/strings.xml
> +    <string name="apply_filter">apply</string>
We probably want upper case for the first letter, as most commands I believe

2022-06-27 23:11 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/strings.xml
> +    <string name="filter_by_card_state">Card State</string>
Please be consistent. Use plural here since you used it everywhere else

2022-06-27 23:11 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +    private val DELAY_TIME = 500
probably want it to be a const, since it never change and don't seems to be related to an object instance specifically

2022-06-28 03:59 UTC, viciousAegis commented on AnkiDroid/src/main/res/drawable/label_icon_card_states.xml
> +<vector android:height="24dp" android:tint="?attr/toolbarIconColor"
These files are not actually being used right now because we only have filters for flags, so it was failing lint checks
I deleted all the unrelated media for now and will add them back with the concerned filter

2022-06-28 04:00 UTC, viciousAegis commented on AnkiDroid/src/main/res/values/strings.xml
> +    <string name="filter_by_card_state">Card State</string>
This is copied from upstream Anki, it also uses `Card State` in singular. If that isn't a problem I will change it

2022-06-28 04:04 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +        if (BottomSheetFragment().flagSearchItems.contains(itemName.text)) {
Yes, this was some old code that got copied while cherry picking, removed it

2022-06-28 05:39 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +class BottomSheetFragment :
No, sorry; I refactored the code to rename the file, but it for some reason didn't rename the class. Fixed it.

2022-06-28 05:41 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +@Suppress("DEPRECATION")
I was testing some features in my local branch which were deprecated, didn't end up using them. Forgot to remove the  supression

2022-06-28 10:48 UTC, david-allison reviewed
Looks great, thanks!

2022-06-28 10:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +    @SuppressLint("VariableNamingDetector", "DirectToastMakeTextUsage")
These shouldn't be suppressed

2022-06-28 10:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +class FilterItemFlag(val name: String, val flagNumber: Int)
Could you add a quick comment that `name` is displayed in the GUI

2022-06-28 10:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +    // Return the size of your dataset (invoked by the layout manager)
I don't think this comment is useful
```suggestion
```

2022-06-28 10:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +    // Replace the contents of a view (invoked by the layout manager)
```suggestion
```

2022-06-28 10:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +     */
```suggestion
```

2022-06-28 10:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +                )
This is repeated a lot and we could get a lot of readability from extracting this to a helper extension method somewhere in `utils`

```
    @ColorInt
    fun Fragment.getThemedColor(@AttrRes attribute: Int): Int {
        return Themes.getColorFromAttr(
            activity,
            attribute
        )
    }
```

2022-06-28 10:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +    var flagSearchItems = mutableListOf<String>()
Agreed - no issue here with storing the `FilterItemFlag` here

2022-06-28 10:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +    ): StringBuffer {
Use `StringBuilder`, `StringBuffer` is synchronized, which means a performance hit that we don't need

2022-06-28 10:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +        }
`mLastClickTime` is going to be a common pattern, and we should abstract this out into a helper method if at all possible

2022-06-28 10:52 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +     * Provide a reference to the type of views that you are using
Changed it a bit to sound more passive

2022-06-28 10:52 UTC, david-allison commented on AnkiDroid/src/main/res/values/strings.xml
> +    <string name="filter_by_card_state">Card State</string>
Use the same Anki Desktop strings. We'll be unifying our translation mechanisms

2022-06-28 10:54 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +class FilterItemFlag(val name: String, val flagNumber: Int)
Okay 👍

2022-06-28 11:21 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +        )
I am using an enum class as such now, and the following doesn't work:
```kotlin
enum class Flags(val flagName: String, val flagNumber: Int) {
        RED(R.string.menu_flag_card_one.toString(), 1),
        ORANGE(R.string.menu_flag_card_two.toString(), 2),
        GREEN(R.string.menu_flag_card_three.toString(), 3),
        BLUE(R.string.menu_flag_card_four.toString(), 4),
        PINK(R.string.menu_flag_card_five.toString(), 5),
        TURQUOISE(R.string.menu_flag_card_six.toString(), 6),
        PURPLE(R.string.menu_flag_card_seven.toString(), 7)
    }
```
How do I access string resources in an enum class

2022-06-28 11:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +        )
```kotlin
    enum class Flags(@StringRes private val flagNameRes: Int, val flagNumber: Int) {
        RED(R.string.menu_flag_card_one, 1),
        ORANGE(R.string.menu_flag_card_two, 2),
        GREEN(R.string.menu_flag_card_three, 3),
        BLUE(R.string.menu_flag_card_four, 4),
        PINK(R.string.menu_flag_card_five, 5),
        TURQUOISE(R.string.menu_flag_card_six, 6),
        PURPLE(R.string.menu_flag_card_seven, 7);
        
        fun getFlagName(context: Context): String = context.getString(flagNameRes)
    }
```

2022-06-28 11:40 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +        )
Okay, committing this in a short while.

2022-06-28 11:42 UTC, david-allison commented
```
> Task :AnkiDroid:lintPlayDebug FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt:95: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
        val mFlagListAdapter = FlagsAdapter(activity, Flags.values(), this)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 errors, 0 warnings
```

2022-06-28 12:14 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +    ): StringBuffer {
Done 👍

2022-06-28 12:33 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        mSearchTerms = filterQuery.toString()
It is giving me the following error: 
```
Type mismatch.
Required:
String?
Found:
Unit
Type mismatch.
Required:
String?
Found:
Unit
```

2022-06-28 13:15 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +        }
Hmm... let's not block this PR on refactoring. Let's split into a different PR

2022-06-28 13:17 UTC, david-allison requested changes
Soft approve after strings are moved

2022-06-28 13:17 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +        /**
```suggestion
        /*
```

2022-06-28 13:17 UTC, david-allison commented on AnkiDroid/src/main/res/values/strings.xml
> +    <string name="filter_by_flags">Flags</string>
These need to be in `02-strings.xml`, not `strings.xml`

2022-06-28 13:21 UTC, david-allison commented on AnkiDroid/src/main/res/values/strings.xml
> +    <string name="filter_by_flags">Flags</string>
(off-topic: renamed this class to stop this from happening: https://github.com/ankidroid/Anki-Android/pull/11720)

2022-06-28 13:32 UTC, viciousAegis commented
@david-allison JIC you missed it, this [comment](https://github.com/ankidroid/Anki-Android/pull/11663#issuecomment-1166337132) mentions my thoughts on the important decision of where in the Browser to place the button to open the bottom sheet from. Material guidelines are against FABs, saying they should only be used for actions.
Need to make a decision on this

2022-06-28 13:32 UTC, viciousAegis commented on AnkiDroid/src/main/res/values/strings.xml
> +    <string name="filter_by_flags">Flags</string>
All done

2022-06-28 13:39 UTC, david-allison commented
I don't want a FAB as an end goal, but I want to keep up velocity, and it's not at all difficult to replace the FAB when we finalize the design. I'm happy with it fornow.

2022-06-28 13:40 UTC, david-allison approved these changes
Looks great!

2022-06-29 15:16 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +    var flagSearchItems = mutableListOf<String>()
@Arthur-Milchior I'm a little confused on how this would be implemented, can you elaborate?

2022-07-03 18:40 UTC, BrayanDSO commented
I miss the "No flag" option and the flag icons of Anki desktop.

2022-07-03 19:28 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +    private lateinit var mFlagRecyclerView: RecyclerView
Hungarian notation should be avoided.

2022-07-03 19:28 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +    private var mLastClickTime = 0
Same.

2022-07-04 16:35 UTC, Arthur-Milchior commented
FYI you have conflict, so you'll need to rebase on your own before merge

2022-07-05 03:43 UTC, mikehardy commented
I don't see a conflict @Arthur-Milchior nor a push to fix it :thinking: - looks okay. @ShridharGoel is this good to go for you? You've to the remaining pending comments I think, so I'm holding off on merge for this

2022-07-05 23:25 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +    // Create new views (invoked by the layout manager)
I beg your pardon, but I don't see the added value of this comment and the comment below. It seems like it essentially repeats the overridden documentation.
In this case, if I understand correctly, this create the view for the flag number `viewType + 1`. This may already be more specific to this case if I got it right

2022-07-05 23:25 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +
Nit: I think you can remove the newline here

2022-07-09 10:40 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +    enum class Flags(@StringRes private val flagNameRes: Int, val flagNumber: Int) {
How can I create an `anki.search.Flag`? Can you guide me to some resources, thanks!

2022-07-09 12:26 UTC, viciousAegis commented
@Arthur-Milchior, @BrayanDSO, @ShridharGoel 

I believe this resolves all your queries and requests for this PR. Let me know if I missed anything!

2022-07-10 13:37 UTC, Arthur-Milchior commented
I'm sorry, yet other conflicts.

2022-07-10 13:41 UTC, viciousAegis commented
@Arthur-Milchior I can't see any conflicts, status shows ready to merge for me 🤔. Where does it show conflict?

2022-07-10 14:18 UTC, Arthur-Milchior approved these changes
Still a few nits. Nothing blocking. I'll have merged if not for current conflict

2022-07-10 18:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        mSearchTerms = filterQuery.toString()
Oh right. It should have been `also`, not `let`. As you wanted the variable to be assigned to the string and not the `setQuery`'s output.

Anyway, not very important here. My bad

2022-07-15 13:30 UTC, Arthur-Milchior commented
I'm sorry but there is still a conflict. Given that I already reviewed multiple time, I'll prefer to wait until all conflicts are resolved, and hopefully can merge directly after that

2022-07-15 13:32 UTC, david-allison commented
@Arthur-Milchior We can squash merge this without a conflict.

2022-07-15 14:54 UTC, Arthur-Milchior approved these changes
One small nit, nothing blocking

2022-07-15 14:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
> +    override fun getCol(): Collection {
Is there a reason for it to implement `CollectionGetter`. Otherwise, I'd consider either:
`val col: Collection = CollectionHelper.getInstance().getCol(activity)`
or 
```
val col : Collection
        get() = CollectionHelper.getInstance().getCol(activity)
```

2022-07-15 14:54 UTC, merged

2022-07-15 15:05 UTC, david-allison commented
Yesssss!!!! 

![](https://media.giphy.com/media/3rgXBQBQyt98Dvh1sI/giphy.gif)

2022-08-03 14:59 UTC, oakkitten commented
I updated my AnkiDroid to find this new filter sheet. I daresay it is _a little bit_ broken. Here are some of the issues in no particular order.

* When choosing filter, previous search input is deleted!!!
* After applying filter, e.g. after choosing the red flag, and opening the bottom sheet again, red flag is not selected!!
* If tapping on Flags fast, some taps are ignored!
* Closing the bottom sheet pops up keyboard even if it was minimized before!
* No row appearance/disappearance animation! I hope you are not using `notifyDatasetChanged`!
* Please set proper padding on the bottom sheet! Everything is way too close to the edges.
* Bottom sheet edges are waaay too round for the app style.
* The upper buttons are missing touch background.
* The upper buttons seem to have material letter spacing which the other buttons don't have.
* Probably don't use separate rows for different flags in the first place. Take a look at how the clock app allows picking week days for an alarm.
   <img src=https://user-images.githubusercontent.com/1710718/182638156-13e51662-8a38-4581-8eaa-41d072a74490.png width=300>
* Please ditch the separator lines, these have been uncool since about Android 6.
* Individual flags are children of Flags and should probably appear idented.
* Please use the same text style for "Flags" and flag rows.
* Fab positioned differently than on main screen--lower and probably too close to the edge?
* The current fab uses a sort icon, but performs filtering. Perhaps use a filter icon?
* In black mode, sheet background is black. It probably should be dark gray, like the dialogs or the menus.
* In black theme, the background for flag rows isn't the same as for the sheet. Individual rows probably shouldn't have background.
* When selecting a row, don't change text color to blue, instead, change the background color to blue, which will also help to separate it from the touch color.

This is more of just a thought, but I have to expand flags in order to tap on one of them. Perhaps the sheet could have some actions that are immediately useful, e.g. if the user often taps on red flag, they can select the red flag right away, without expanding anything. Perhaps have a section with the most commonly used actions in a form of horizontally scrolled pills?

Also I would like to have tapping on items do the search instantly in the background, so if I am unsure which flag I want I can just click through them without having to press Apply and opening the filter again and again.

Also, why not use pill strip filters such as the ones in Gmail, Files, etc? These are modern, easy to access, and I think are a good fit for the search of AnkiDroid. Look at Labels, From, To in the screenshot below. These could be `Flags`, `Tags`, `Suspended`, etc.
<img width=300 src=https://user-images.githubusercontent.com/1710718/182638963-aa442f9c-e04c-48ae-b6ad-bd670a2a7768.png>

2022-08-08 13:06 UTC, viciousAegis commented
@oakkitten hello, thank you for the thorough feedback for the sheet, I'll address them in the same order as above. Please keep in mind though that the sheet is in no way in its final form, in terms of both design and usability, and some of the flaws the you have mentioned are known and will be ironed out in further commits.

1.  The previous search input being deleted is not the final behavior, in the coming commits I will address the fact that the search input is reset every time.
2.  This point is related to the one above, and will be fixed alongside it.
3. That is by choice, we have prevented double taps on any of the filter items.
4. Can you post this as a separate issue with a video of the bug? Will help me iron it out.
5. Again, since this is a very early build, I have not considered animations.
6. I believe I am using the padding used in the card browser itself, I'll double check it, but I intentionally want the padding to be the same for both for consistency's sake.
7. The bottom sheet being too rounded can be opened up as a separate issue for discussion.
8. The upper buttons were intentionally made to use the `Text Button` styles after discussion, hence their appearance.
9. Same as above.
10. I'm following Anki Desktop's sidebar, which was my original goal, hence the flags appearing in a line.
11. Separator lines can again be ditched, shouldn't make a huge difference.
12. I agree, indentation still has to be worked upon.
13. Personally, I find the text style distinction to be helpful, but again, a separate issue is best for discussion
14. The FAB will not be part of the final design, and is only there as a temporary way to access the filter sheet.
15. I'll look into the theming for the Black theme
16. ^
17. That was what was originally done, but for consistency around the app, we changed it to being the text color blue.

For the last paragraphs, again, I would appreciate if you could open up issues for them so they can be discussed in detail. Thanks for the feedback, hope my explanation clears up some of your points!

2022-08-08 16:52 UTC, oakkitten commented
> That is by choice, we have prevented double taps on any of the filter items.

Why? Other apps don't do this.

> Closing the bottom sheet pops up keyboard even if it was minimized before!
> > Can you post this as a separate issue with a video of the bug? Will help me iron it out.

You basically search for anything by typing whatever and pressing the magnifying glass icon in the keyboard. This will trigger the search, and close the keyboard. Then you press the fab, and then you either press back or Cancel, and the keyboard will pop up.

> Again, since this is a very early build, I have not considered animations.

RecyclerView comes with animations by default. In order to have no animations, you have to either disable them or use it imporperly, e.g. by calling `notifyDatasetChanged()` instead of `notifyItemInserted()` & pals, or calculating and applying a diff. It might be harder to fix this later on; it's best to use it propely from get go.

> I believe I am using the padding used in the card browser itself, I'll double check it, but I intentionally want the padding to be the same for both for consistency's sake.

I think there's currently about 1-2 dp of padding in the card browser. A bottom sheet is a separate element, with different kinds of items, and with icons. I am not sure if it makes sense to try to have similar padding here; in either case, a padding of 1-2 dp is unacceptable. The browser is an odd case as you want to squeeze as much info as you can into it, at least in its current state; not sure if it's wise modeling other things after it. I would just go with material design guidelines, or the looks of other apps.

> The upper buttons were intentionally made to use the Text Button styles after discussion, hence their appearance.
> Same as above.

Is it intentional that they use a different style and no touch background?... Uhh

> Personally, I find the text style distinction to be helpful, but again, a separate issue is best for discussion

Anki doesn't do this and other apps I have don't do this

> That was what was originally done, but for consistency around the app, we changed it to being the text color blue.

That's fair. (Hope it's changed towards a more conventional approach—along with the other parts of the app!)

P.S. I think that using checkboxes, as in the in Gmail screenshot above, would help to stress that you are choosing to display either of several flags. In fact, changing background to select is nearly always used with some kind of immediate action such as move or delete or whatever. This selection is not retained. Unlike the checkboxes. 

P.P.S. As for the other points that might be best to open as other issues, I suppose I'll wait until this thing is more... ready.