[GSoC] Kotlin migration TaskManager.java
ankidroid/Anki-Android pull request #11729
Opened 2022-06-29 09:29 UTC by divyansh-dxn

## Purpose/Description

Kotlin migration TaskManager.java -> TaskManager.kt

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-29 14:05 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
> +        }
We shouldn't be introducing functional changes in a conversion commit.

This introduces a bug: 
* `previousTask` is not set to null if result is null. 
* Logs are not produced if the previous task is null

2022-06-30 05:38 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +            progressCallback.resources?.getString(R.string.check_db_message) + " " + current + " / " + total
Also two java files are affected by this change. When resource is null, message isn't displayed correctly. So I'll first convert those two. Meanwhile putting this PR in draft.

2022-07-05 07:37 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
>      override fun onPostExecute(result: Result?) {
Is it appropriate?

2022-07-06 03:33 UTC, lukstbit requested changes

2022-07-06 03:33 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
> +        result?.let { listener?.onPostExecute(it) }
Keep the functionality as close as the original java code as possible. So just pass the `result` to `onPostExecute()` with `!!`.

2022-07-06 03:33 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.kt
> +    override fun waitForAllToFinishConcrete(timeoutSeconds: Int?): Boolean {
Make the timeoutSeconds parameter as non null as there's only one usage of this method and in there it just receives a value of 4. Also revert the `div()`.

2022-07-06 03:33 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/async/TaskManager.kt
> +        fun removeTask(task: CollectionTask<*, *>?): Boolean {
When converting static methods from java always add the `@JvmStatic` annotation so the java call site doesn't need changes(to add the `Companion` reference).

2022-07-06 03:33 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
> +    @NeedsTest("logs are correctly produced and previous task is null")
I don't think the `@ NeedTest` is needed if you don't introduce functional changes to the code(see my other review for this method).

2022-07-06 15:00 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/TaskManager.kt
> +        fun waitForAllToFinish(timeoutSeconds: Int): Boolean {
How can I flag `timeoutSeconds`  as JVM `Integer` and not `int`?

2022-07-06 15:01 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
> +        result?.let { listener?.onPostExecute(it) }
tried it, but causes more tests to fail with `NullPointerException`

2022-07-06 15:02 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/TaskManager.kt
> +        fun waitForAllToFinish(timeoutSeconds: Int): Boolean {
Causing the test failure.

2022-07-06 15:06 UTC, divyansh-dxn commented on AnkiDroid/src/test/java/com/ichi2/async/ForegroundTaskManager.java
> +    public boolean waitForAllToFinishConcrete(int timeoutSeconds) {
this

2022-07-07 17:36 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
> +        result?.let { listener?.onPostExecute(it) }
Yes, I saw that. Looking through the code it seems why either:
- keep your code knowing that we are modifying the behavior
- change the type system around TaskListener to handle a null result. I've done this in a migration PR for this class which can be seen [here](https://github.com/ankidroid/Anki-Android/commit/c7ec2cae08ca0a274a2c59f760cf58cbbc684aa4). There are a decent amount of changes but they are small(mostly making types nullable and adding !! to handle the new nullability)

@david-allison Any thoughts?

2022-07-08 05:56 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/TaskManager.kt
> +        fun waitForAllToFinish(timeoutSeconds: Int): Boolean {
Because `non-null Int `gets converted to primitive `int` so it cannot override as Integer.

2022-07-08 06:01 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
> +        result?.let { listener?.onPostExecute(it) }
Have you checked for any existing test failures, on the modified code? Because I also was trying this but got many more test failures with NPE, so I stuck with this change.

2022-07-08 06:35 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
> +        result?.let { listener?.onPostExecute(it) }
Ran the tests, and everything is fine.

2022-07-09 17:37 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
> +        result?.let { listener?.onPostExecute(it) }
@lukstbit should I make changes according to your suggestions?

2022-07-10 06:25 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
> +        result?.let { listener?.onPostExecute(it) }
@divyansh-dxn Yes, although my PR has more(small) changes I think it follows the initial code.

2022-07-10 07:10 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
> +        result?.let { listener?.onPostExecute(it) }
Agree!

2022-07-10 15:36 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
> +        result?.let { listener?.onPostExecute(it) }
@lukstbit please review the changes.

2022-07-10 16:48 UTC, lukstbit approved these changes
Looks good

2022-07-12 23:48 UTC, david-allison approved these changes

2022-07-12 23:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
> +        result?.let { listener?.onPostExecute(it) }
I'd pass this on to @Arthur-Milchior for an opinion on the final nullability here.

I'm happy with the changes as they are for now

2022-07-15 02:56 UTC, merged