[GSoC] Remove XXX replacement on preferences summaries
ankidroid/Anki-Android pull request #11725
Opened 2022-06-28 19:42 UTC by BrayanDSO

## Purpose / Description
Use Android's default methods instead + general cleanup + prep for preferences searchBar

## Approach
On the commits (only for reviewing purposes)

## How Has This Been Tested?

On my phone
https://user-images.githubusercontent.com/69634269/176271050-9c21af82-291a-4942-b243-1c5748b01f17.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-28 22:18 UTC, david-allison requested changes
I'll be honest, I found this one difficult to grok commit-by-commit. 

Overall, it looks good, and I'd be happy to squash merge it.

2022-06-28 22:18 UTC, david-allison commented on AnkiDroid/src/main/res/values/preferences.xml
> +    <string name="pref_card_browser_font_scale_key">relativeCardBrowserFontSize</string>
This is not used by the preference

2022-06-28 22:18 UTC, david-allison commented on AnkiDroid/src/main/res/values/preferences.xml
> +    <string name="pref_computation_precision_key">advanced_forecast_stats_compute_precision</string>
This is not used by the preference

2022-06-28 22:18 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +                            .onNegative { _, _ -> text = CollectionHelper.getDefaultAnkiDroidDirectory(requireContext()) }
`this.text` would be nicer here

2022-06-28 22:18 UTC, david-allison commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +<resources xmlns:tools="http://schemas.android.com/tools">
revert this

2022-06-28 22:20 UTC, david-allison commented on AnkiDroid/src/main/res/values/preferences.xml
> +    <string name="pref_summary_percentage">%s\%%</string>
I don't /think/ this one needs to be translated. Flagging for reviewer 2

2022-06-28 22:40 UTC, mikehardy commented on AnkiDroid/src/main/res/values/preferences.xml
> +    <string name="pref_summary_percentage">%s\%%</string>
LTR. Different symbols. Translate all the things
https://phrase.com/blog/posts/number-localization/#Percentages

2022-06-28 23:20 UTC, david-allison commented on AnkiDroid/src/main/res/values/preferences.xml
> +    <string name="pref_summary_percentage">%s\%%</string>
😫 Thanks for being right

2022-06-29 00:30 UTC, mikehardy commented on AnkiDroid/src/main/res/values/preferences.xml
> +    <string name="pref_summary_percentage">%s\%%</string>
I wouldn't have looked it up except my natural instict is to be naturally contrary. If you had said "we need to translate this" I would have tried to prove it wrong ;-) (and then been wrong). TIL...

2022-06-29 12:29 UTC, david-allison requested changes
```
* What went wrong:
Execution failed for task ':AnkiDroid:processPlayDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     warn: removing resource com.ichi2.anki:string/day_offset_summ without required default value.
     warn: removing resource com.ichi2.anki:string/preference_summary_percentage without required default value.
     warn: removing resource com.ichi2.anki:string/time_limit_summ without required default value.
     com.ichi2.anki.AnkiDroid-main-50:/xml/preferences_advanced.xml:34: error: resource string/preference_summary_literal (aka com.ichi2.anki:string/preference_summary_literal) not found.
     com.ichi2.anki.AnkiDroid-main-50:/xml/preferences_advanced_statistics.xml:22: error: resource string/advanced_forecast_stats_compute_precision (aka com.ichi2.anki:string/advanced_forecast_stats_compute_precision) not found.
     com.ichi2.anki.AnkiDroid-main-50:/xml/preferences_appearance.xml:117: error: resource string/relativeCardBrowserFontSize (aka com.ichi2.anki:string/relativeCardBrowserFontSize) not found.
     error: failed linking file resources.
```

2022-06-29 15:13 UTC, BrayanDSO commented
Commits reorganized. Fixed some things as well. PR text updated with new video of me testing the screens

2022-06-30 10:45 UTC, BrayanDSO commented
All commits /*should*/ compile now, but testing them one by one is too much time, so I'm fine with squash.

PR video reupdated with last changes. @ankidroid/gsoc-mentor PTAL.

2022-06-30 13:18 UTC, mikehardy commented
> All commits /_should_/ compile now, but testing them one by one is too much time, so I'm fine with squash.
> 
> PR video reupdated with last changes. @ankidroid/gsoc-mentor PTAL.

Just to say:

```bash
reset && while [ `git rev-parse HEAD` != "79483d6a3b228a118604fc5488725deaec7ca4a6" ]; do echo not there yet currently at; git rev-parse HEAD; ./gradlew clean uninstallPlayDebug jacocoTestReport :api:lintRelease :AnkiDroid:lintPlayRelease ktlintCheck lint-rules:test; git reset --hard HEAD~1; done
```

nerd power :muscle:  :nerd_face:

2022-07-02 13:49 UTC, BrayanDSO commented
> > All commits /_should_/ compile now, but testing them one by one is too much time, so I'm fine with squash.
> > PR video reupdated with last changes. @ankidroid/gsoc-mentor PTAL.
> 
> Just to say:
> 
> ```shell
> reset && while [ `git rev-parse HEAD` != "79483d6a3b228a118604fc5488725deaec7ca4a6" ]; do echo not there yet currently at; git rev-parse HEAD; ./gradlew clean uninstallPlayDebug jacocoTestReport :api:lintRelease :AnkiDroid:lintPlayRelease ktlintCheck lint-rules:test; git reset --hard HEAD~1; done
> ```
> 
> nerd power 💪 🤓

Thanks for the tip, but I still haven't got the time to check them, neither I care about squashing, so I'm fine with it

2022-07-03 21:48 UTC, david-allison approved these changes
LGTM

2022-07-04 09:35 UTC, lukstbit approved these changes

2022-07-05 03:36 UTC, merged