[GSoC] Kotlin migration TextImporter.java
ankidroid/Anki-Android pull request #11739
Opened 2022-06-30 05:56 UTC by divyansh-dxn

## Purpose / Description

Kotlin Migration

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-06-30 16:50 UTC, david-allison approved these changes

2022-07-01 17:44 UTC, lukstbit requested changes

2022-07-01 17:44 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/TextImporter.kt
> +    private fun noteFromFields(fields: List<String?>): ForeignNote {
Add a KotlinCleanup for this function: simply fun with scope function.

2022-07-01 17:44 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/TextImporter.kt
> +                val tags = firstLine.substring("tags:".length).trim { it <= ' ' }
Did the tool used in the conversion the trim(predicate) method or did you added it yourself?

2022-07-01 17:49 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/TextImporter.kt
> +                val tags = firstLine.substring("tags:".length).trim { it <= ' ' }
Found this while searching about it: https://stackoverflow.com/a/45652573

2022-07-01 17:56 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/TextImporter.kt
> +                val tags = firstLine.substring("tags:".length).trim { it <= ' ' }
@ShridharGoel Thank you, I did a quick migration of the file and saw that indeed the tool used the trim(predicate) method.

2022-07-01 18:17 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/TextImporter.kt
> +                val tags = firstLine.substring("tags:".length).trim { it <= ' ' }
@lukstbit Welcome.

2022-07-01 18:39 UTC, lukstbit approved these changes

2022-07-01 20:38 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/TextImporter.kt
> +    @KotlinCleanup("simply fun with scope function")
Should have been "simplify".

2022-07-02 03:26 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/TextImporter.kt
> +    @KotlinCleanup("simply fun with scope function")
It's a temporary annotation so I don't think it's that important as long as it's understandable.

2022-07-02 07:47 UTC, merged