cleanup: add scope function for Intent in CardTemplateBrowserAppearanceEditor
ankidroid/Anki-Android pull request #11749
Opened 2022-07-01 01:01 UTC by oyeraghib

## Purpose / Description
cleanup: add scope function for Intent in CardTemplateBrowserAppearanceEditor

## Fixes

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-07-01 13:28 UTC, david-allison requested changes
Loosks better, minor suggestions

2022-07-01 13:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
> +        data.apply {
Why not `Intent().apply {`

2022-07-01 13:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
>              return intent
```suggestion
            return Intent(context, CardTemplateBrowserAppearanceEditor::class.java).apply {
                putExtra(INTENT_QUESTION_FORMAT, questionFormat)
                putExtra(INTENT_ANSWER_FORMAT, answerFormat)
            }
```

2022-07-01 16:41 UTC, oyeraghib commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
> +        data.apply {
fixed that!

2022-07-01 18:03 UTC, lukstbit approved these changes

2022-07-10 08:14 UTC, lukstbit commented
@oyeraghib Please apply David's suggestion from above.

2022-07-10 12:30 UTC, oyeraghib commented
> @oyeraghib Please apply David's suggestion from above.

sorry for being late. Just updated.

2022-07-10 16:51 UTC, lukstbit approved these changes

2022-07-30 18:21 UTC, mikehardy approved these changes
Verified David's suggestions are implemented, and in general looks to good to me - thanks!

2022-07-30 18:22 UTC, merged