Add Toast for "max one word" pronunciation
ankidroid/Anki-Android pull request #11752
Opened 2022-07-01 15:46 UTC by dorrin-sot

## Purpose / Description
In Pronunciation, If a string with more than one word was entered, the proper error toast wouldn't show up

## Fixes
Fixes #11748 

## Approach
Added toast in LoadPronunciationActivity::DownloadFileTask for if `source` is more than one word

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-07-01 17:52 UTC, ShridharGoel requested changes

2022-07-01 17:52 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +                if (source.split(" ").size > 1) {
Use `source.contains(" ")`

2022-07-01 18:17 UTC, ShridharGoel commented
Is it possible for `source` to contain leading or trailing whitespaces? If yes, then I think `trim` should be used before the check for whitespace.

2022-07-01 18:44 UTC, dorrin-sot commented
I added an "if" for trailing/leading spaces before the multiple-word check

2022-07-01 20:36 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +                if (source.startsWith(" ") || source.endsWith(" ")) {
Wouldn't it be a better user experience to trim the string and use it instead of this?

2022-07-02 06:02 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +                if (source.startsWith(" ") || source.endsWith(" ")) {
But then it wouldn't be caught if user entered " Hello"

2022-07-02 07:46 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +                if (source.startsWith(" ") || source.endsWith(" ")) {
What I meant is that use `intent.extras!!.getString(EXTRA_SOURCE)!!.trim()` instead of `intent.extras!!.getString(EXTRA_SOURCE)!!` while assigning the value of source.

2022-07-02 12:21 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +                if (source.startsWith(" ") || source.endsWith(" ")) {
Oh it was already like that so no need to check for trailing and leading space(s)

2022-07-03 03:24 UTC, lukstbit requested changes

2022-07-03 03:24 UTC, lukstbit commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
> +    <string name="multimedia_editor_only_one_words">Only one word at a time is supported</string>
Small typo: _multimedia_editor_only_one_word_

2022-07-03 03:24 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
> +                } else if (source.matches(".*[A-Z]+.*".toRegex())) {
Use a kotlin function like _any_ instead of a regular expression:

`source.any { it.isUpperCase() }`

2022-07-03 07:28 UTC, lukstbit approved these changes

2022-07-03 15:43 UTC, ShridharGoel commented
Any reason for not using `trim` on `source`? Or is it already being done somewhere?

2022-07-03 17:26 UTC, dorrin-sot commented
> Any reason for not using `trim` on `source`? Or is it already being done somewhere?

yes it was already `intent.extras!!.getString(EXTRA_SOURCE)!!.trim()`

2022-07-03 19:03 UTC, ShridharGoel approved these changes

2022-07-03 19:03 UTC, merged

2022-07-03 19:09 UTC, mikehardy commented
@ShridharGoel please be careful with PRs that affect stings - we got in the way of each other here - the best practice in my experience is to do an I18N sync *before* merging something that affects all strings, because otherwise the review of the string changes with translation contributions mixed in takes way more time. So you do one sync for I18N, merge it, then merge the PR with a new string / whole translations string change, and do another sync

Of course, this is not documented, apologies

2022-07-03 19:22 UTC, ShridharGoel commented
@mikehardy Thanks for the information, will take care of this from now onwards.

2022-07-03 19:23 UTC, ShridharGoel commented
@mikehardy Thanks for the information, will take care of this from now onwards.

2022-07-03 19:32 UTC, mikehardy commented
okay - I had already run one sync prior to the merge (I just beat you to it :-) ) - so I had a "clean" review run of just translations only. And good thing to, there were 3 different issues and they showed up easily. I'll re-sync now that I've repaired those translations and then this will be ready for an alpha release with the fresh string in place