Remove extra whitespace in collection synchronized dialog
ankidroid/Anki-Android pull request #11759
Opened 2022-07-02 12:00 UTC by oakkitten

## Purpose / Description

Remove extra whitespace in collection synchronized dialog. You see this dialog a lot when syncing with Anki's sync server, as it does not support syncing media yet.

## Approach

Reverted the statement to what it was before being converted to Kotlin.

## How Has This Been Tested?

Tested on my device running Android 11. Before & after

<img src=https://user-images.githubusercontent.com/1710718/176999699-ef4e15b3-5418-45de-afc7-7a3ff00125e3.png width=300> <img src=https://user-images.githubusercontent.com/1710718/176999705-786e864e-4514-41ea-ab9a-9f1eb2445c32.png width=300>

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-07-02 12:48 UTC, lukstbit requested changes
Could you please use a string template instead:

`"${res.getString(R.string.sync_database_acknowledge)}\n\n${data.data[2]}"`

instead?

2022-07-02 12:53 UTC, oakkitten commented
I think a string template would make the statement less readable in this case.

2022-07-03 02:15 UTC, lukstbit commented
@oakkitten I'm not fixed on this, I'm leaving it to a second reviewer. If he's fine I'm fine and will approve.

2022-07-03 18:31 UTC, mikehardy approved these changes
I'm going to go with "implementor's choice" as I don't care much, and for formatting issues if ktlint doesn't actually enforce it I don't want to get into formatting discussions - a slippery slope with little value over time

However - whether to enforce it or not is a separate issue: open an issue for discussion and PR for a ktlint rule change/addition if you feel strongly, and we can either add a rule or not. I could see it maybe being a rule, but that would be how to make this change - auto-formatted + auto-enforce.

Separate from all that, thanks for the fix! Also, you might like playing with V16 developer options menu, it has the rust-library / background sync - no UI yet so you'd have to see the logcat to see it syncing but background sync is coming, slowly but it's coming...

2022-07-03 18:31 UTC, merged