Kotlin migration Anki2Importer.java
ankidroid/Anki-Android pull request #11757
Opened 2022-07-02 08:38 UTC by divyansh-dxn

## Purpose / Description
Kotlin Migration

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-07-02 13:52 UTC, lukstbit requested changes

2022-07-02 13:52 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
> +            mProgress.publishProgress(
cleanup: Could simplify with `?.`

2022-07-02 15:12 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
> +        mDupeOnSchemaChange = false
cleanup: combined declaration and initialization.
@lukstbit agree?

2022-07-02 15:13 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
> +        mDupeOnSchemaChange = false
Yes, I forgot about that.

2022-07-02 15:39 UTC, lukstbit approved these changes

2022-07-03 21:53 UTC, david-allison approved these changes
That looked like a difficult one, thanks!

2022-07-03 21:53 UTC, merged