Removed "paste as plain text"
ankidroid/Anki-Android pull request #11753
Opened 2022-07-01 18:00 UTC by shivam-2701

## Pull Request template

## Purpose / Description
This commit fixes the issue #10377  and removes "paste as plain text" option from the context menu in NoteEditor activity

## Fixes
Fixes #10377 

![Fix](https://user-images.githubusercontent.com/98466713/176946985-d295376e-1f35-4778-ac56-b32e306459be.jpeg)

## Approach
The issue was solved by removing the menu item with id android.R.id.pasteAsPlainText in 
onPrepareActionMode() method in 

>NoteEditor.kt

line no 2065

## How Has This Been Tested?

I has been test on physical device running android 11 and pixel 4 emulator.
It has also been tested using automated test mentioned on the Development Guide of AnkiDroid

> ./gradlew jacocoTestReport

## Learning (optional, can help others)
The resources used are from the issue page which directs to the android documetation

> [developer.android.com/reference/android/widget/TextView#setCustomInsertionActionModeCallback(android.view.ActionMode.Callback)](https://developer.android.com/reference/android/widget/TextView#setCustomInsertionActionModeCallback(android.view.ActionMode.Callback))

> [developer.android.com/reference/android/widget/TextView#setCustomSelectionActionModeCallback(android.view.ActionMode.Callback)](https://developer.android.com/reference/android/widget/TextView#setCustomSelectionActionModeCallback(android.view.ActionMode.Callback))

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-19 01:36 UTC, mikehardy requested changes
I attempted to resolve the conflict, and I reviewed it, just nitpicks, it seems like this could go in

2022-08-19 01:36 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            // Test commit
No reason a real commit should include a comment like this

```suggestion
```

2022-08-19 01:36 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +
unnecessary newline I think?

```suggestion
```

2022-08-19 01:36 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +
don't alter spacing unnecessarily

```suggestion
```

2022-08-19 01:37 UTC, mikehardy approved these changes
If it passes CI this could go in I think

2022-08-28 13:54 UTC, david-allison approved these changes

2022-08-28 23:44 UTC, merged

2022-08-28 23:44 UTC, david-allison commented
Merged, congrats!!!

If you're on [our Discord](https://discord.gg/qjzcRTx), send me a PM and I'll add some roles