Migrated preferences title length test [Lint Test]kotlin
ankidroid/Anki-Android pull request #11765
Opened 2022-07-03 19:27 UTC by prateek-singh-3212

2022-07-03 21:42 UTC, david-allison requested changes
Thanks!

2022-07-03 21:42 UTC, david-allison commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt
> +    companion object {
move this back to the top of the file - makes the diff much easier to read and having it here adds no value

2022-07-05 16:50 UTC, prateek-singh-3212 commented
@mikehardy Sorry I chaged the value of string. Fixed Now

2022-07-05 17:30 UTC, prateek-singh-3212 commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt
> +    companion object {
done

2022-07-07 04:33 UTC, lukstbit approved these changes

2022-07-07 19:12 UTC, merged