Fixed `ExportCompleteDialog`'s neutral buttons deprecation
ankidroid/Anki-Android pull request #11789
Opened 2022-07-06 07:34 UTC by dorrin-sot

- lint: Note Editor (#11632)
- Remove some usages of MaterialDialog
- refactor: Rename Connection.java to .kt
- refactor: Convert Connection to Kotlin
- fix: Ensure Robolectric's super.setUp() is called
- Fix crash for Reviewer menu action providers when set to always show
- refactor: non-null col
- Add categories icons
- Updated strings from Crowdin
- [GSoC] Unify gestures with controls (#11647)
- Updated strings from Crowdin
- migrated createStatisticsOverview() to suspend function
- cleanup: IDE lint (Collections.sort)
- Rename prefIconColor to iconColor
- Use `iconColor` as fillColor on sync icon
- migrated AnkiStatsTaskHandler.createReviewSummaryStatistics() to suspend function
- added extension function launchCatching
- LoadPronunciationActivity now extends AnkiActivity
- Enabled Toolbar in LoadPronunciationActivity
- Create `Advanced` subcategory on Reviewing
- Rename `Behavior` category to `Scheduling`
- Remove Whiteboard stroke width preference
- Move Display settings from Reviewing to Appearance and Accessibility
- refactor: rename DirectSystemTimeInstantiationTest to .kt
- refactor: Convert DirectSystemTimeInstantiationTest to Kotlin
- refactor: Rename DirectSystemCurrentTimeMillisUsageTest to .kt
- refactor: Convert DirectSystemCurrentTimeMillisUsageTest to Kotlin
- fix: `setOnNavigationItemSelectedListener` deprecation in CardTemplateEditor
- fix: `toLowerCase` deprecation in BeolingusParser
- Remove `ConfirmationPreferenceCompat.kt`
- Simplify devOptions preference's fragment assignment
- Remove `ResetLanguageDialogPreference.kt`
- docs: DeckPicker
- migrate PerformDowngradeTask from AysncTask to Coroutines
- Updated strings from Crowdin
- cleanup: scope function for Paint object
- fix: `setBackgroundDrawable` deprecation in FieldEditText
- cleanup: `is` -> `equalTo` in CheckMediaTest
- Replace dpToPixels() with convert dp method from utils
- Inline shouldScrollToolbar method from companion
- Fix some @KotlinCleanup for FieldModelEditor
- Make fields ListView property non null
- Make the collection property in ModelFieldEditor as not null
- Make the model property in ModelFieldEditor as not null
- replaced string.format
- Updated strings from Crowdin
- Bumped version to 2.16alpha69
- [GSoC] NF: clean ControlPreference.kt (#11684)
- Rename DirectDateInstantiation .java to .kt
- Converted DirectSnackbarMakeUsageTest [Lint Test] to Kotlin
- Delete unused StatsAsyncTask
- Rename TagsUtilTest.java to TagsUtilTest.kt
- Migrate TagsUtilTest.java to Kotlin
- Rename HttpTest.java to HttpTest.kt
- Migrate HttpTest.java to HttpTest.kt
- scoped storage: Make MigrateUserData a task
- lint: fix warnings
- Remove AnkiActivity.finish deprecation
- NF: activities finish cleanup
- Add Theme class
- Remove unnecessary theme check from NavigationDrawerActivity
- Refactor themes
- Rename Theme.isDark to isNightMode
- Enable DrawAllocation lint check
- Rename FieldEditLineTest.java to FieldEditLineTest.kt
- Migrate FieldEditLineTest.java to Kotlin
- Fixed SearchDecks Icon visibility not updating if DeckCount changed (#11113)
- Renamed CollectionTest.java to CollectionTest.kt
- [Kotlin Migration] CollectionTest
- Create function to retrieve names of all models
- [GSoC] enhanced error handling when launching coroutines (#11679)
- chore: Set permissions for GitHub actions
- Refactor Preferences fragments initialization
- chore: add ColorInt annotation
- refactor: rename DuplicateCrowdInStringsTest.java to .kt
- refactor: convert DuplicateCrowdInStringsTest to Kotlin
- refactor: Rename DirectToastMakeTextUsageTest.java to .kt
- refactor: convert DirectToastMakeTextUsageTest to Kotlin
- Change flag colors for light and dark themes
- Restore flag icon colors to original
- Extract flag colors to color resources
- rename: strings.xml to analytic_constants.xml
- migrated LoadPronunciationActivity to Coroutines
- Rename DuplicateTextInPreferencesXmlTest.java to .kt
- Migrate DuplicateTextInPreferencesXmlTest.java to kotlin
- test: comment out flaky model editor context menu tests
- test: ignore tests flaky in CI
- refactor: Rename Storage.java to .kt
- refactor: Convert Storage to Kotlin
- Set the correct default values for day and night themes
- Add onConfigurationChanged for non AnkiActivity classes
- Update theme in case system dark mode was changed on another activity
- Update to Anki 2.1.54 backend
- Set the backend language on app startup
- Enable backend media handling; add media check
- Implement syncing with the backend
- Don't store collection reference in DeckTreeNode
- Add some new flags to local.properties
- Expose card info/graph methods
- Use named args in backend calls
- Add some coroutine helpers; simplify error handling in sync code
- Add support for new backend backup naming scheme
- Add support for colpkg import/export & backups
- Tweak withProgress() to work without collection; handle colpkg progress
- Remove some unnecessary DB queries when legacy schema disabled
- Add mention of TRACESQL env var for debugging
- Add code to import/export apkg files via the backend
- Fix test failure after rebasing over latest main
- Restrict backend logging to sync actions
- Fix V16 toggle in preferences not working
- Expose backend method to build a search query
- Apply suggestions from code review
- Updated strings from Crowdin
- Bumped version to 2.16alpha70
- refactor: Rename TextImporter.java to .kt
- refactor: Convert TextImporter to Kotlin
- Replaced String.format in CustomStudyDialog
- Make fullscreen reviewer occupy system bars
- Remove extra whitespace in collection synchronized dialog
- Fix Sync Error after cancelling sync before
- Fixed Help Dialog Crash if "Don't keep activities" enabled
- Add Toast for "max one word" pronunciation (#11752)
- refactor: Rename Anki2Importer.java to .kt
- refactor: Convert Anki2Importer to Kotlin
- fix: remove duplicate "TextFields" lint
- Bump fragments library dependency to 1.5.0
- Updated strings from Crowdin
- Bump annotation from 1.3.0 to 1.4.0
- Bump desugar_jdk_libs from 1.1.5 to 1.1.6
- Bump activity-ktx from 1.4.0 to 1.5.0
- Bump jsoup from 1.15.1 to 1.15.2
- [GSoC] Remove XXX replacement on preferences summaries (#11725)
- Rename CardQueue.java to CardQueue.kt
- Migrate CardQueue.java to Kotlin
- refactor: Rename Importer.java to .kt
- refactor: Convert Importer to Kotlin
- Updated strings from Crowdin
- Kotlin CleanUp of IMultimediaEditableNote.kt
- reloadRequired cleanup
- MultiColumnListAdapter::bindView cleanup
- checkCardsAtPositions for cleanup
- getPositionMap for cleanup
- updateCardsInList
- removeNotesView
- newPositionOfSelectedCard
- hasSelectedAllDecks
- refactor: lateinit mDeckSpinnerSelection
- cleanup: Arrays.asList() -> listOf()
- Update material dialog library
- Add test to check for duplication in lint-release.xml
- Fix paste from browser into note field not working (#11656)
- Removed "send email" and "save file" button and added "share" button in ExportCompleteDialog
- Removed export_send_button and export_save_button strings

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particul [...]

2022-07-06 16:36 UTC, dorrin-sot commented
Added it to the end

![photo_2022-07-06 21 06 31](https://user-images.githubusercontent.com/59933477/177600276-082477cd-9d35-4b68-b380-48d6009e57a7.jpeg)

2022-07-06 17:35 UTC, BrayanDSO commented
Title of the dialog "Send Anki Package" and the action "Share"  
aren't equivalent. To keep consistency, I suggest renaming the title as well to "Share Anki Package"

2022-07-06 17:38 UTC, BrayanDSO commented
And it's only necessary to remove the string at the `values` folder. The CI handles the rest.

2022-07-09 10:48 UTC, lukstbit commented
@dorrin-sot I've edit your PR to remove the keyword "fixes" so the issue isn't closed if this PR is merged, there are still other usages of `neutralButton()`.

2022-08-19 01:41 UTC, mikehardy commented
You clearly did a huge batch of work, and it was sadly right as a bunch of other stuff happened, so now it's all piled up with conflicts. I'm really sorry, I understand that's no fun. This one has conflicts too

2022-09-06 07:03 UTC, dorrin-sot commented
@mikehardy done :)

2022-09-07 00:58 UTC, david-allison requested changes
I'm happy with this, I love the video.

I have a few small requests regarding documentation, and one investigation regarding the title of the dialog.

Would be happy to approve as-is if there's pushback, but would prefer to wait for these changes

2022-09-07 00:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
> +        fun shareFile(path: String)
Document the `file` param here to state that it's the path of the file to be shared

2022-09-07 00:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
>          }
nit (implementer's choice): `bundleOf` can be used here

2022-09-07 00:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +                0 // isn't actually used
docs: could you specify the parameter names

optional: It may be useful to extract `LabeledIntentUntils.NO_ICON` to a constant of 0

2022-09-07 00:58 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="export_share_title">Send Anki package using</string>
I don't see this on your video, could you check you're using it right?

2022-09-07 00:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +        for (ri in resInfo) {
Needs a comment in this method on why we have this ordering

2022-09-18 16:58 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
> +        fun shareFile(path: String)
I added a commit that documents it

2022-09-18 16:59 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
>          }
I used bundleOf in a new commit

2022-09-18 16:59 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +                0 // isn't actually used
I specified the parameter names and did not extract to constant mentioned in comment exactly what 0 meant

2022-09-18 16:59 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +        for (ri in resInfo) {
I explained it after surmising that this was how you added save to file to the share sheet

2022-09-18 17:02 UTC, mikehardy commented
I'm clearing strings out in #12436
I've rebased this to master without the merge commit so it's current passes tests locally
I've added a commit that implements all reviewer suggestiong (none of them functional, so very low risk) from David
I've added a commit that ignores a test as logged in #12437 so I can assert that this runs cleanly locally:

`/bin/nice -n 19 ./gradlew clean jacocoTestReport :api:lintRelease :AnkiDroid:lintPlayRelease ktlintCheck lint-rules:test`

This should be good to go

2022-09-18 17:02 UTC, mikehardy approved these changes

2022-09-18 17:26 UTC, dorrin-sot commented
@mikehardy thanks alot 🙏🏻🙏🏻

2022-09-18 19:54 UTC, mikehardy commented
I want to generate a release, I want to merge what's possible before the release, and I just cleared strings out, going to go with this one

2022-09-18 19:54 UTC, merged