cleanup in CustomStudyDialog
ankidroid/Anki-Android pull request #11793
Opened 2022-07-06 19:07 UTC by oyeraghib

## Purpose / Description
add scope functions for `args` and `dialogOptions` variable
fix: IDE lint

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-07-06 23:28 UTC, david-allison approved these changes

2022-07-07 03:38 UTC, lukstbit requested changes

2022-07-07 03:38 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +                dialogOptions.apply {
Call apply on the line above: 

`val dialogOptions = mutableListOf<ContextMenuOption>().apply {`

2022-07-07 08:22 UTC, oyeraghib commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +                dialogOptions.apply {
done 👍

2022-07-08 03:23 UTC, lukstbit approved these changes

2022-07-09 06:29 UTC, merged