refactor: make `fieldEditLine` as a function in FieldEditLineTest
ankidroid/Anki-Android pull request #11799
Opened 2022-07-07 20:36 UTC by oyeraghib

## Purpose / Description
refactor: make `fieldEditLine` as a function in FieldEditLineTest

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-07-08 04:09 UTC, lukstbit requested changes

2022-07-08 04:09 UTC, lukstbit commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/FieldEditLineTest.kt
> +            reference.set(
Contract this lines into a single line, there's no need to have them spread out on 4 lines.

2022-07-08 04:09 UTC, lukstbit commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/FieldEditLineTest.kt
> +        return reference
Please keep the original code and return a FieldEditLine.

2022-07-08 05:08 UTC, oyeraghib commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/FieldEditLineTest.kt
> +            reference.set(
done!

2022-07-08 05:08 UTC, oyeraghib commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/FieldEditLineTest.kt
> +        return reference
fixed that

2022-07-09 03:25 UTC, lukstbit approved these changes

2022-07-09 09:51 UTC, mikehardy approved these changes

2022-07-09 09:51 UTC, merged