Add support for the V3 scheduler; drop support for V1
ankidroid/Anki-Android pull request #11808
Opened 2022-07-09 09:00 UTC by dae

Includes https://github.com/ankidroid/Anki-Android/pull/11740 and https://github.com/ankidroid/Anki-Android/pull/11802, and requires a new backend release with https://github.com/ankidroid/Anki-Android-Backend/pull/221 - will rebase once those are in.

- Users still on V1 will be prompted to update when they tap on a deck. The update uses the backend code so that learning cards are not lost.
- By default, AnkiDroid will continue to use V2 with a V3 collection. The V3 path is only enabled when legacy_schema=false
- Tests pass, and in my brief tests in the emulator, reviewing/undoing seems to work.

2022-07-09 10:00 UTC, mikehardy commented
:exploding_head: :smile:

2022-07-22 00:08 UTC, mikehardy commented
Ready for rebase and hopefully I'll have time for a review tomorrow (nearly dinner time here in New Orleans 😁)

2022-07-22 00:45 UTC, dae commented
- Have confirmed tests pass in each commit locally.
- Have moved the commit from #11881 onto the tail of this one, so the final commit switches AD over to the latest backend. Can be kept in a separate PR if you'd prefer.

2022-07-22 04:56 UTC, dae commented
(made a trivial change to re-trigger the flakey emulator test)

2022-07-22 21:46 UTC, mikehardy reviewed
I only had enough time to look at the first commit :weary: - but had a couple things worth posting about it now

2022-07-22 21:46 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                this.openUrl(Uri.parse("https://faqs.ankiweb.net/the-anki-2.1-scheduler.html#updating"))
I'm not sure - but want to make sure the `openurl` method goes through the (oddly named) `AdaptionUtil` such that devices with browser deliberately stripped don't have issues

2022-07-22 21:46 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +    message: String = "Processing...",
I'm concerned about both this string and relying on new backend's `tr` method below, we haven't (I haven't?) fully analyzed translation language sets to see how compatible they are etc, and I don't have the time to do that right now. I fear it'll hang up this PR unless we just use AnkiDroid-level translation strings for the moment *or* we (where "we" is someone other than me at the moment, and through mid-August) can harmonize the languages and update AnkiDroid docs to point at Anki's translation service as well for people that want to translate non-crowdin strings etc etc and kick off that whole process

2022-07-23 05:50 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                this.openUrl(Uri.parse("https://faqs.ankiweb.net/the-anki-2.1-scheduler.html#updating"))
Done

2022-07-23 05:51 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +    message: String = "Processing...",
For the "processing..." string, I figured you'd want to do that in a follow-up commit after an i18n sync.

I've gone through and checked the languages mappings, and they should all be ok now. For any languages that the backend doesn't currently support, it will just fall back on the English strings like if it hadn't been translated yet.

2022-07-24 21:56 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +    message: String = "Processing...",
> For the "processing..." string, I figured you'd want to do that in a follow-up commit after an i18n sync.

Historically, user-visible strings are always added into strings file at time of first usage, and I just label the PR with the strings label so I remember to do the sync action / PR after - we never let user-visible stuff through with hard-coded strings in PRs, or at least not intentionally

> I've gone through and checked the languages mappings, and they should all be ok now.

Thank you!

> For any languages that the backend doesn't currently support, it will just fall back on the English strings like if it hadn't been translated yet. New languages can be added when users follow the instructions on https://translating.ankiweb.net/

I think this is a pretty solid start - and I am biased towards action, so let's go with it. I guess all that's left is an edit to the translation page to give people a handle to the new-to-us system you've got with Pontoon - I just did that https://github.com/ankidroid/Anki-Android/wiki/Translating-AnkiDroid/_compare/7c0ba5c393040654691f8ed44d2d44c3617d845e...002935cd2bc07effc17b8f3a409a846bde79e2be

2022-07-24 22:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
> +        Context context = AnkiDroidApp.getInstance();
nice one - thanks - hopefully avoids the semi-false positives I was seeing with LeakCanary which were making me think things were crashing

2022-07-24 22:15 UTC, mikehardy commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java
> +    @BlocksSchemaUpgrade("some of these tests are failing; need to investigate why")
this works for me - doesn't break bisect, doesn't halt momentum but clearly flags it. Can work like this for anything similar, in my opinion

2022-07-24 22:18 UTC, mikehardy requested changes
This all seems great to me - nothing seems to jump out and be obviously off. Just need the user-visible string extracted to something (03-dialogs maybe?) and I'm +1. V3 scheduler support, this is huge

2022-07-24 22:18 UTC, mikehardy commented
Oh, and it took a conflict but I am assuming (hopefully not naively) that it'll be trivial

2022-07-24 22:20 UTC, mikehardy commented
All other reviewers: I really want to maintain momentum in this connected chain of anki/Anki-Android-Backend/Anki-Android work, and it threatens to stall all the time because of my poor availability and the pushing it needs between the components. So I'd like to set a 1-2 day timer on this one before I merge by default. If you want to review and need more time just say so! No problem. Otherwise if it's quiet on this PR I'm going to merge it as soon as the string + de-conflict are in

2022-07-24 23:27 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +    message: String = "Processing...",
String added

2022-07-27 14:21 UTC, mikehardy approved these changes
timer expired + string extracted == let's go!

2022-07-27 14:21 UTC, merged

2022-08-02 07:18 UTC, SnipeAT commented
This is a feature I've been checking daily for.  Will it will show up in the next alpha?

2022-08-02 08:01 UTC, dae commented
AFAIK it's already in the latest alpha, but it requires opting in to the new backend, which is a big change that has not received any user testing so far, so you may be exposing yourself to bugs in unrelated functionality. If you're happy to live life on the edge and make lots of backups, you can opt in for a session by tapping on the V16 option in the developer options in the preferences screen. Please report any issues you encounter.

2022-08-02 15:24 UTC, mikehardy commented
@dae unfortunately this is not 100% accurate:

>  the V16 option in the developer options in the preferences screen.

That "developer options" screen is dynamically added only to "debug" builds, that is when you build from source. So it's not generally accessible to users yet.

The next step in progression of V16+ schema testing is to make that specific option a toggle with state stored/used in/from preferences, and to move it to advanced menu. I'd love to see that soon as folks like @SnipeAT are (assuming they understand the risk) a really really really valuable source of testing since they are motivated to try it. Whatever we can do to get to this state where end users can get a warning but then try V16 would be a big step forward IMHO

2022-08-06 00:07 UTC, BrayanDSO commented
@mikehardy, actually with the new About screen, users on RELEASE build can use developer options as well.

Tap the logo 6 times and a big warning will show asking if the user wants to enable it or not.

And FWIW, I'm in favor of out adding the V16 option to the alpha/beta releases on `Advanced`, so anyone can find them.

2022-08-16 21:44 UTC, SnipeAT commented
Just wanted to report that I've been using the new backend and the v3 scheduler for a week or so and it's been working out pretty great. The app might crash in a couple situations but reports seem to be being sent back home.  Just updated to the alpha released today and will continue using (after making another backup of my collection).

2022-08-16 22:21 UTC, dae commented
Thanks for letting us know! Please note that there's currently a bug where review times are being saved incorrectly. Until the next alpha, I recommend you set your maximum answer time in the deck options to your average answer time, and/or adjust the previous review records using something like this in the debug console of the desktop version (5000 is 5 seconds), which will reset 60s answers in the last month:

mw.col.modSchema(check=True)
mw.col.db.execute("update revlog set time = 5000 where time = 60000 and id > 1658096427000")

https://docs.ankiweb.net/misc.html#debug-console

#12024

2022-08-16 23:01 UTC, BrayanDSO commented
complementing: You get the Acra ID together with the debug info on `Settings > About > Copy Debug Info`

2022-08-23 18:44 UTC, mikehardy commented
@dae follow-up on this one: I attempted to document it here for early testers, did I get all the information correct? https://github.com/ankidroid/Anki-Android/issues/10411#issuecomment-1224591312

Secondly, seems we may need an "enable v3 scheduler" switch? Or do we have one already and I missed it? That's my main doubt but I could be wrong on any of it of course

2022-08-23 20:14 UTC, BrayanDSO commented
We don't have a v3 Scheduler switch. I have a draft branch for it here https://github.com/BrayanDSO/Anki-Android/tree/v3pref, but it has a bug that the preference is always re-enabled, both here and Anki desktop, after sync

2022-08-23 22:26 UTC, mikehardy commented
No worries - it will be needed in the future yes - but right now as a way to feed new testers into new backend / v3, having it be a requirement that the collection is v3-enabled on desktop perhaps feeds them in at a measured pace. Not a bad thing - I'm not looking for ease of use, just the possibility of use, and real testing. I think our current state fits that

2022-08-24 08:48 UTC, dae commented
LGTM. There's a bug where the scheduler version is not updated after a sync (will fix), so recommend you tell people to restart the app after they have synced the setting from the desktop.

2022-08-24 15:07 UTC, mikehardy commented
@dae thanks for the review, I updated the comment with a link the PR you just posted for the same. I see a fair bit of traffic today on V3/new-backend related items but it doesn't seem overwhelming? Do you get the same feeling? Like, there are issues but it is at capacity and not over-capacity? I ask because I'm gradually widening my audience where I publicize this and right now it feels like "no more new testers for a few days" but maybe by end of week I can start mentioning it's available again. Perhaps in a week or so we can make a real call for testers but that's not a decision now

2022-08-25 06:13 UTC, dae commented
#12157 should address the crashes I'm aware of. No particular preference on timing on my end.