[GSoC] Create a new about category
ankidroid/Anki-Android pull request #11803
Opened 2022-07-08 12:26 UTC by BrayanDSO

## Approach
- Stop using the old webView one
- Create a new Android layout
- Add an icon and top category for it
- Factorize some methods related to developer options
- Enable developer options on release builds under a secret

![image](https://user-images.githubusercontent.com/69634269/177991521-64d2f77e-27b6-42fb-916d-6f0d1d0a4fb4.png)

## How Has This Been Tested?

https://user-images.githubusercontent.com/69634269/177991459-a54223b4-f344-4364-841c-89271b3a04d8.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-07-08 12:31 UTC, BrayanDSO commented
@ankidroid/gsoc-mentor 

As I've said on Discord
> Copy debug info will be there until I implement the Report problems/Help category (low priority) and will be replaced with Changelog at the same time 

> In the future, it would be nice to have a libraries heading there

And I'm not 100% about the words' choice here. Pretty happy to change it if necessary.

2022-07-10 03:34 UTC, lukstbit commented
I'm not going to comment on language as a non native english speaker.
I like the UI, with the observation if it isn't better to have the app icon side be side with the name and the version(to save a bit of vertical space).

2022-07-10 15:02 UTC, BrayanDSO commented
Descriptions' color should be textColorSecondary (https://github.com/ankidroid/Anki-Android/pull/11824)

2022-07-10 15:47 UTC, Arthur-Milchior commented
A few notes. Nothing blocking.
I created #11825 so that we eventually can list all licences we use. In the meantime, I believe we should at least note that:
* some of our code is under AGPLv3. This one is very important as some people would use this fact to decide that even running the code on their platform is a legal risk. 
* uses code from third-parties under various open source licences.

I'm not a fan of your links regarding contributors. I really don't want contributors to be listed with a small numbers near to them, counting lines and commits. Not only are we not competing. But even if we were trying to really show who has been the most useful, this would ignore ankiweb, this would ignore time spent investigating complex bug, this would ignore time reviewing and doing maintainer work.

If we decide to do still use this page, I would prefer we sort by number of lines deleted, this metric is so absurd that at least it shows that the metric really don't mean anything relevant. On the other hand we already have [credits](https://github.com/ankidroid/Anki-Android/#credits) who also list non-code contributors (or at least, will as soon as my PR for translators is merged). And I believe that it's important that we list translators too. There are 1400 of them, I can't cease to be amazed by this thought. That's a huge number. And thanks, we almost never interact with most of them, but they are doing incredible work for our usability around the world.


Regarding the video, I'd really love @BrayanDSO if next time, you can activate the accessibility setting that put a highlight where you click, so that I can follow what you are doing. 

I think I'd love to see standard buttons with round corner around the three last links. Because right now, without underline, with a color that is close to main text color, I don't find it intuitive

2022-07-10 16:25 UTC, lukstbit commented
> I've given a try to your idea, but I personally like it better on the current way.

@BrayanDSO Agreed, for some reason it doesn't look to good.

2022-07-10 16:33 UTC, Arthur-Milchior reviewed
First commit, I don't understand what mean 

> Info.kt is kept until the changelog isn't renewed as well

Given the length of the commit, I'd weakly argue to separate removal and addition in two distinct commits for the ease of review. Implementor choice

2022-07-10 16:54 UTC, BrayanDSO commented
> First commit, I don't understand what mean

I've edited the message to this:
> And remove the code of the previous About section from `Info.kt`
> The `Info.kt` activity can't be removed yet entirely because it is still used to show the changelog
> Info.kt is kept until the changelog isn't renewed as well

I hope it's more clear now.

> Given the length of the commit, I'd weakly argue to separate removal and addition in two distinct commits for the ease of review. Implementor choice

As the motivation for removing the old `About` section and methods is because of the implementation of the new one, I personally think that it's easier to follow the changes by keeping them together (e.g. you know where `copyDebugInfo()` came from without jumping back and forth between commits)

2022-07-10 17:07 UTC, BrayanDSO commented
Updated screenshots after last changes and with #11824

![image](https://user-images.githubusercontent.com/69634269/178154693-f7f56c85-9dc1-4e70-a854-667998899e6c.png)

![image](https://user-images.githubusercontent.com/69634269/178154705-b80e50a2-477e-4139-a1b6-8fa177efa66d.png)

![image](https://user-images.githubusercontent.com/69634269/178154711-f1e025d6-538c-4144-bc50-ad9ba09f6dd0.png)

![image](https://user-images.githubusercontent.com/69634269/178154720-766cd48d-38b9-42f3-bd70-8c30f7fd5286.png)

2022-07-10 17:15 UTC, BrayanDSO commented
> some of our code is under AGPLv3. This one is very important as some people would use this fact to decide that even running the code on their platform is a legal risk.
> uses code from third-parties under various open source licences.

Okay, will change that.

> I'm not a fan of your links regarding contributors. I really don't want contributors to be listed with a small numbers near to them, counting lines and commits. Not only are we not competing. But even if we were trying to really show who has been the most useful, this would ignore ankiweb, this would ignore time spent investigating complex bug, this would ignore time reviewing and doing maintainer work.

Same link of the README page. I really don't care about the lines, commits, etc. If there is any list of the code contributors somewhere, I'm fine with it. 

Haven't added a translators link because I can't find one on Crowdin. 

Probably [credits](https://github.com/ankidroid/Anki-Android/#credits) is the best option here, but I'm open to suggestions.

> Regarding the video, I'd really love @BrayanDSO if next time, you can activate the accessibility setting that put a highlight where you click, so that I can follow what you are doing.

Didn't know about it. Thanks for the tip. I'll use it next time

2022-07-10 18:04 UTC, BrayanDSO commented
Updated the video.

2022-07-10 21:01 UTC, david-allison requested changes

2022-07-10 21:01 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
> +                }
These settings are dangerous (will probably break the app or corrupt the collection). 

I really think we should also have a message box here.

2022-07-10 21:02 UTC, david-allison commented
Oh, as a comment, the page looks great and I'm really happy with how it looks

2022-07-10 21:50 UTC, BrayanDSO commented on AnkiDroid/src/main/res/layout/about_base_layout.xml
> +        tools:text="AnkiDroid is released under the GPL-3.0 and AGPL-3.0 licenses, with the source code available on GitHub" />
> Probably a conscious decision to not use the @string, but it would work

yep

> (albeit showing $1 and HTML)

Here's the reason. XML preview looked quite bad and the text would change on runtime anyway, so I used `tools:text` to have a better XML preview. I think that's fine?

2022-07-10 21:51 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +            if (DevOptionsFragment.isEnabled(requireContext())) {
I beg your pardon but I haven't got what you mean here. Is this a note or something I should change?

2022-07-10 21:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
> +                }
I don't understand why. I'd be curious if you could explain

2022-07-10 22:11 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/preferences.xml
> +    <string name="pref_dev_options_screen_key">devOptionsKey</string>
Fixed. Thanks!

2022-07-10 22:19 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/anki/InfoTestNoOnCreate.kt
> -class InfoTestNoOnCreate : RobolectricTest() {
👍🏻 Added it on the first commit message.

> Remove `InfoTestNoOnCreate.kt` because it was only used to check if the app wouldn't crash while building the HTML string for the old about screen

2022-07-10 22:21 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
> +                }
I'm not against the extra safety. Besides the it being hidden and the dangerous options having a message saying this ("These settings are dangerous (will probably break the app or corrupt the collection").

![image](https://user-images.githubusercontent.com/69634269/178164073-69e1f26d-06e7-42c9-9f3b-a0560b4e12fd.png)

I'll push it soon

2022-07-10 22:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +            if (DevOptionsFragment.isEnabled(requireContext())) {
It's a note that the second commit drops functionality, which is added back in the third commit

2022-07-10 22:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
> +                }
> I don't understand why. I'd be curious if you could explain

One of the options is literally "lock the database and don't release the lock". 
We also give users the new anki schema, which has the potential to corrupt collection. 
No users should be using any of the settings.

2022-07-10 22:44 UTC, david-allison commented on AnkiDroid/src/main/res/layout/about_base_layout.xml
> +        tools:text="AnkiDroid is released under the GPL-3.0 and AGPL-3.0 licenses, with the source code available on GitHub" />
It is, as long as it's a conscious decision.

2022-07-10 23:59 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +            if (DevOptionsFragment.isEnabled(requireContext())) {
Oh, now I get it. Fixed, thanks.

2022-07-11 00:04 UTC, BrayanDSO commented
Updated with dialog to confirm dev options activation

![image](https://user-images.githubusercontent.com/69634269/178167349-5efb46eb-7fe3-4637-9da6-85d4f6907116.png)

2022-07-11 22:25 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
> +                        DevOptionsFragment.setDevOptionsEnabledByUser(view.context, true)
I personally don't like this level of indentation. It requires lot of reading to understand that it is "what occurs if you have clicked clickLimit time on the about app, then have seen the material dialog shown, then click on okay.

I would have a strong preference to split this in two methods, or at least one. This can even more easily be done because the only information in common in all methods is the context.
One method can be what occurs when we "ok". One other method would be in charge of showing the material dialog.

There are two distinct reasons for my preferences. First, because as a reviewer, I'd find it easier to consider separately: "is `ok` doing what I want", "is the dialog as I want" and "is the dialog show function called at the right time". 
Also, if at some point we actually want to really test it, it'll be far easier. For example, we can use a mock to check that if we click `clickLimit` time, the method to show the dialog is called.

Same remarks applies to `setOnPreferenceChangeListener` above for example.


I know that this is not consistent with an important part of our current codebase. But honestly, I'd consider that it'd be something to change for cleaning and clarity purpose, not something to imitate

2022-07-12 12:15 UTC, david-allison approved these changes

2022-07-14 19:42 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
> +import com.ichi2.anki.*
Wildcard imports can be avoided, though this is not a blocker for PR merge.

2022-07-14 23:32 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
> +import com.ichi2.anki.*
Another possible issue is to create a lint rule (or maybe there is one we can activate, or maybe isn't necessary) to avoid wildcard imports on the codebase.

2022-07-14 23:43 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
> +import com.ichi2.anki.*
I'll resolve the comment as I think this is a thing that could be enforced automatically

2022-07-17 04:33 UTC, lukstbit commented on AnkiDroid/src/main/res/layout/about_scrollable_layout.xml
> +<include android:id="@+id/about_layout" layout="@layout/about_base_layout"/>
Curiosity: Why you didn't create a single layout for the about fragment?

2022-07-17 04:37 UTC, lukstbit commented on AnkiDroid/src/main/res/values/preferences.xml
> +    <string name="dev_options_enabled_msg">Enabled developer options</string>
Do you plan to extract this string? Seems weird to have this string in the file where all(?!) strings are preferences keys.

2022-07-17 04:40 UTC, lukstbit approved these changes
Looks good!

2022-07-17 10:49 UTC, BrayanDSO commented on AnkiDroid/src/main/res/layout/about_scrollable_layout.xml
> +<include android:id="@+id/about_layout" layout="@layout/about_base_layout"/>
There was a comment on both layouts explaining why.
Basically, for some reason, if I wrap the base layout with a `ScrollView` directly, the Android Studio preview becomes worse.

While I tried to reproduce it to take a screenshot, Idk what I did different but the preview looks fine, so I joined them on the last commit, thanks!

2022-07-17 10:50 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/preferences.xml
> +    <string name="dev_options_enabled_msg">Enabled developer options</string>
> Do you plan to extract this string? Seems weird to have it in the file where all strings are preferences keys.

Nope. But I agree that's a little weird. I added a comment on the last commit to help.

2022-07-17 10:53 UTC, BrayanDSO commented
git push -f was out of habit. Last changes are on ee04599

2022-07-17 11:39 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/preferences.xml
> +    <!-- Enabled dev options message isn't translated as dev options shouldn't be used by most users -->
```
<!--
Messages displayed after the user enabled developer options, and warned remaining messages will be in English.
-->
```

2022-07-17 12:45 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/preferences.xml
> +    <!-- Enabled dev options message isn't translated as dev options shouldn't be used by most users -->
Really liked it. Thanks.

2022-07-17 12:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
> +            if (clickCount == clickLimit) {
Amended it on the last commit.

2022-07-17 15:55 UTC, merged