Added regression test for DeckPickerContextMenu
ankidroid/Anki-Android pull request #11812
Opened 2022-07-09 14:52 UTC by dorrin-sot

- Add Cancel option to Add key and Add gesture dialogs
- Fix code style checks failures due to @CheckResult
- Properly initialize unit tests related to preferences
- Enable the preferences tests which were ignored for being flaky
- Rename .java to .kt
- Converted FixedPreferencesTitleLengthTest[LINT TEST] to Kotlin
- Fix context menu in CustomStudyDialog
- fix: ide lint
- cleanup in CustomStudyDialog (#11793)
- Fix functionality for dialogs of NoteEditor toolbar
- refactor: make fieldEditLine as a function
- cleanup: `is` -> `equalTo`
- cleanup: `is` -> `equalTo`
- cleanup: fix IDE lint
- cleanup: IDE lint
- Rename .java to .kt
- Migrate DeckPickerTest to Kotlin
- undo button in onCreateOptionsMenu cleanup
- Bumped version to 2.16alpha73
- Some setup
- added test for `BROWSE_CARDS`
- added test for `RENAME_DECK`
- added test for `CREATE_SUBDECK`
- added test for `DECK_OPTIONS`
- added test for `DELETE_DECK`
- added test for `CREATE_SHORTCUT`
- added test for `UNBURY`
- added test for `CUSTOM_STUDY_REBUILD` and `CUSTOM_STUDY_EMPTY`
- tiny lint fixes

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-07-09 14:55 UTC, dorrin-sot commented
Can't test for `EXPORT_DIALOG` until #11810 is fixed

2022-07-10 19:24 UTC, mikehardy commented
Unblocked, thanks to your own efforts, nice

2022-07-10 21:27 UTC, david-allison reviewed
Can we attach the fragment instead of using a singleton?

2022-07-10 21:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
> +    }
We shouldn't be doing this.

2022-07-10 21:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +    init { instance = this }
ditto, we shouldn't need a singleton to access a dialog

2022-08-19 01:42 UTC, mikehardy commented
OMG another one, seriously I am so sorry

2022-09-07 18:01 UTC, david-allison requested changes

2022-09-07 18:01 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
> +
we don't want this coupling just for testing. Can another method for obtaining the dialog be used?

2022-09-21 12:08 UTC, david-allison requested changes
One request to keep DeckPicker somewhat clean, rest looks great!

2022-09-21 17:02 UTC, dorrin-sot commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckPickerContextMenuTest.kt
> +            openContextMenuAndSelectItem(recyclerView, 7)
I don't think so since this is the index of the item in the RecyclerView not its itemId and I couldn't find a view to get the item list and for example check each item's title

2022-09-21 17:26 UTC, BrayanDSO approved these changes
Only conflicts to fix.

2022-09-26 12:04 UTC, dorrin-sot commented
@BrayanDSO hi sorry I don't understand I don't have any conflicts 👀

2022-09-26 16:03 UTC, merged