HttpSyncerTest Kotlin Migration
ankidroid/Anki-Android pull request #11814
Opened 2022-07-09 17:49 UTC by divyansh-dxn

## Purpose / Description
Kotlin Migration

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-07-10 08:39 UTC, david-allison reviewed
Very nice, two nits, then good to go

2022-07-10 08:39 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/sync/HttpSyncerTest.kt
> +        MatcherAssert.assertThat(syncUrl, Matchers.`is`(sDefaultUrlNoHostNum))
re-import `MatcherAssert` and `Matchers`

2022-07-10 08:39 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/sync/HttpSyncerTest.kt
> +@RunWith(AndroidJUnit4::class)
cleanup: `is` => `equalTo`

2022-07-11 01:07 UTC, lukstbit requested changes

2022-07-11 01:07 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sync/HttpSyncerTest.kt
> +        userPreferences.edit().putBoolean("useCustomSyncServer", true).apply()
Add a kotlin cleanup to use the `edit{}` extension function on SharedPreferences.Editor.

2022-07-11 01:07 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sync/HttpSyncerTest.kt
> +        private const val sCustomServerWithNoFormatting = "https://sync.example.com/"
Add a cleanup to rename this constants.

2022-07-11 08:17 UTC, lukstbit approved these changes

2022-07-12 10:46 UTC, ShridharGoel approved these changes

2022-07-13 05:59 UTC, divyansh-dxn commented
I mistakenly had pushed more commits to this branch, but I dropped them instantly.

2022-07-14 19:35 UTC, merged