Add translators to the credits
ankidroid/Anki-Android pull request #11828
Opened 2022-07-10 15:31 UTC by Arthur-Milchior

2022-07-10 17:02 UTC, BrayanDSO commented
Just asking, does Crowdin have a public link listing all Ankidroid translators?

2022-07-10 21:24 UTC, Arthur-Milchior commented
Can anyone not an admin let me know whether, on https://crowdin.com/project/ankidroid/members , you see a thousand of contributors, or only the few people with privileges?

FYI you can see crowdin's API on https://developer.crowdin.com/api/v2/#operation/api.user.get 
and so yes, there is.

However, we have not gathered translator permissions, and I don't want to play with giving people's name without having checked whether it's alright with them.
We can send them all a message through crowdin, so we can ask them to fill a google form and ask them whether they want to be credited for their work and what name to use. However, I've currently no idea how to deal with someone who later may want to change their name. In particular, between Google history and git history (if we download the list of names on git), it seems impossible to delete their name from history. I've no idea how to be compliant with various privacy laws here, in particular GPRD, the right to be forgotten, or just ensuring we do not keep a record of people's [deadnames](https://en.wikipedia.org/wiki/Deadnaming).

2022-07-10 21:31 UTC, david-allison commented
Consent and GDPR/CCPA compliance lies with CrowdIn/GitHub. 

I think we're overcomplicating this. A link is fine.

2022-07-10 21:32 UTC, david-allison commented on README.md
> +### [Translators](https://opencollective.com/ankidroid#contributors)
This link is incorrect. It should point to CrowdIn.

2022-07-10 21:33 UTC, david-allison requested changes
link fix needed

2022-07-10 21:36 UTC, david-allison commented
> https://crowdin.com/project/ankidroid/members

This link is a 403 if a user is not logged in. 

Let's link to the activity stream: https://crowdin.com/project/ankidroid/activity-stream. That has the added advantage of showing people the activity and how easy it is to get started.

2022-07-10 21:47 UTC, Arthur-Milchior commented
This stream don't allow to easily see the full list of contributors; unless you press "show more" a nonsensical number of time.

I admit it's not very important. I still believe it would have been a nice gesture to have a full list of people agreeing to it in the app.

2022-07-18 00:58 UTC, Arthur-Milchior commented
Ready for re-review

2022-07-18 01:02 UTC, david-allison approved these changes

2022-07-19 00:19 UTC, mikehardy approved these changes

2022-07-19 00:20 UTC, merged