PR asks to notes licences on the wiki
ankidroid/Anki-Android pull request #11826
Opened 2022-07-10 15:12 UTC by Arthur-Milchior

This would ensure that once #11825 is done, we are not forgetting any new dependencies.

2022-07-14 03:00 UTC, lukstbit requested changes

2022-07-14 03:00 UTC, lukstbit commented on .github/pull_request_template.md
> +- [ ] I added all extra licences, dependencies, libraries to [the wiki](https://github.com/ankidroid/Anki-Android/wiki/Licences)
How about:

_[ ] I recorded all changes to licences, dependencies, libraries to [the wiki](https://github.com/ankidroid/Anki-Android/wiki/Licences)_

?

2022-07-14 08:42 UTC, david-allison commented
The more barriers we put up to entry, the less contributions we get.

Can we move this to a CI check?

2022-07-15 02:11 UTC, mikehardy commented
> * Can we move the dependencies to a file with specific usage instructions?

Yes! #11101 - If there are no serious complaints, how bout we add this as a requirement for the final solution on that issue? It is meant to centralize dependency version management in one file and as part of that we can add a huge comment there about license attribution / credit ?

2022-07-15 16:20 UTC, Arthur-Milchior commented
If all dependencies are in a single file, I see how you'd get the CI for dependencies.
However, for code that are ported to Kotlin from another language, which occurred at least twice (CSV and template parsing), I don't. 
But I'm also fine just relying on the fact that, once we have actually a list of licence, we'll trust reviewer to let contributors that translated code/imported it, to know one extra change is required,

2022-07-30 18:28 UTC, mikehardy commented
I think we could actually change the template a little and have a **reviewer** checklist

That is, still have the reminder in there but in a second "Hey Reviewers, thanks for helping! Please check these things as you review:" list, and have a "Is there a new dependency added in this PR? Is the license for the dependency on this /link here/ page?"

Still a "light process" - as opposed to a CI check - but puts the barrier (if any) on a reviewer that can do it easily

2022-07-30 21:36 UTC, Arthur-Milchior commented
I love your way of thinking Mike.

2022-07-31 22:23 UTC, closed without merging