[Kotlin Migration] SchedTest
ankidroid/Anki-Android pull request #11837
Opened 2022-07-11 16:35 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
Kotlin Migration of SchedTest

2022-07-11 23:22 UTC, dae commented
This looks like it's not based on latest main, as some of these changes were already made in https://github.com/ankidroid/Anki-Android/pull/11802

2022-07-13 02:26 UTC, lukstbit requested changes

2022-07-13 02:26 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
> +class SchedTest : RobolectricTest() {
Add two more KotlinCleanup:
```
@KotlinCleanup("fix IDE lint issues")
@KotlinCleanup("improve kotlin code where possible")
```

2022-07-14 02:50 UTC, lukstbit approved these changes
Ok!

2022-07-30 18:30 UTC, mikehardy commented
This is an area of really fast change - which is both unfortunate (it keeps blowing up the PR, I'm so sorry) but also rare and amazing (as Damien has taken the time to make really big/important advances in the scheduler support with #10411 ) - it means this needs another scan though since I just merged #10411 so now scheduler code changed up again. I'm not aware of any other PRs against the scheduler at the moment, at least

2022-07-31 18:27 UTC, Arthur-Milchior commented
And now there is a conflict, sorry

2022-08-01 17:05 UTC, Arthur-Milchior reviewed
Thanks a lot. A few nit if you please.

Your `assertEqual` longs, make me thought about https://github.com/ankidroid/Anki-Android/issues/11965

2022-08-26 16:01 UTC, closed without merging