[Kotlin Migration ] DeckTest
ankidroid/Anki-Android pull request #11843
Opened 2022-07-13 03:39 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
Kotlin Migration of DecksTest

2022-07-13 15:15 UTC, david-allison requested changes
Looks great! One nitpick

2022-07-13 16:33 UTC, Prince-kushwaha commented on AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.kt
> +class DecksTest : RobolectricTest() {
ok

2022-07-13 17:39 UTC, david-allison approved these changes

2022-07-14 02:56 UTC, lukstbit approved these changes

2022-07-15 02:23 UTC, merged