[Unit Test]: Check trimming of extra spaces
ankidroid/Anki-Android pull request #11841
Opened 2022-07-12 08:32 UTC by oyeraghib

## Purpose / Description
Unit Test to check trimming of extra spaces entered in Beolingus Search while loading the pronunciation of a word. 
It checks if an entered string search of (" Hello ") matches (Hello)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-07-12 11:40 UTC, lukstbit requested changes

2022-07-12 11:40 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParserTest.kt
> +    fun `Test to check trimming of extra spaces`() {
To be honest I don't see what's the value of this test.

> _// confirm " Hello " matches "Hello" when loading pronunciation using Beolingus search_

The code in your test doesn't do this because of  `" Hello ".trim()`, so you're calling the `getPronunciationAddressFromTranslation` with just `Hello`. This is almost identical with another test in BeolingusParserTest, `testPronunciation()`(there it uses _Wasser_ instead of _Hello_)

Also, it's the activity which trims the word for extra spaces.

2022-07-12 12:53 UTC, oyeraghib commented on AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParserTest.kt
> +    fun `Test to check trimming of extra spaces`() {
I saw that `getPronunciationAddressFromTranslation()` inside the `LoadPronunciationActivity` uses the `trim()` to trim down the extra spaces in `wordToSearchFor`. So this test is for that purpose, as it conforms that in `mPronunciationAddress = BeolingusParser.getPronunciationAddressFromTranslation(result, source.trim())` we get the trimmed word after doing `source.trim()`

Though I agree, technically it becomes identical to `testPronunciation()` but still confirms the trim functionality the other way.

2022-07-14 03:05 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParserTest.kt
> +    fun `Test to check trimming of extra spaces`() {
> So this test is for that purpose, as it conforms that in mPronunciationAddress = BeolingusParser.getPronunciationAddressFromTranslation(result, source.trim()) we get the trimmed word after doing source.trim()

That would need to be a test on the activity itself, otherwise you just created a test that the `trim()` method from the kotlin library works, which doesn't provide value.

Anyway, **I** don't see the value of this changes so I'm not going to approve them but I leave it up to another reviewer.

2022-07-24 13:24 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParserTest.kt
> +    fun `Test to check trimming of extra spaces`() {
Agreed with @lukstbit (thanks for your analysis). 
To try to state it another way, one goal of this kind of tests would be to ensure that if we change the implementation of the Beolingus class in a way that breaks URL, it is detected by the test and immediately fail.
If you hard code current implementation in the test itself, the test won't detect the class breaking

2022-07-24 18:28 UTC, oyeraghib commented on AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParserTest.kt
> +    fun `Test to check trimming of extra spaces`() {
Thanks a lot for your feedback @lukstbit and @Arthur-Milchior . I understand what I have been doing wrong here. Actually I am new to testing, so I am just trying to learn how to write unit tests. This time it was great for understanding, and I hope I'll be able to write better and meaningful tests in future.

2022-07-24 18:28 UTC, closed without merging

2022-07-24 19:33 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParserTest.kt
> +    fun `Test to check trimming of extra spaces`() {
You're welcome. Happy to see you take it as a way to learn and do better. 
By the way, no need to explain yourself. A lot of us learned a lot thanks to AnkiDroid, and I've clearly been at your place a few years ago.