Fix `DeckPicker#searchDecksIcon` flash
ankidroid/Anki-Android pull request #11851
Opened 2022-07-14 22:36 UTC by dorrin-sot

- Add Cancel option to Add key and Add gesture dialogs
- Fix code style checks failures due to @CheckResult
- Properly initialize unit tests related to preferences
- Enable the preferences tests which were ignored for being flaky
- Rename .java to .kt
- Converted FixedPreferencesTitleLengthTest[LINT TEST] to Kotlin
- Fix context menu in CustomStudyDialog
- fix: ide lint
- cleanup in CustomStudyDialog (#11793)
- Fix functionality for dialogs of NoteEditor toolbar
- refactor: make fieldEditLine as a function
- cleanup: `is` -> `equalTo`
- cleanup: `is` -> `equalTo`
- cleanup: fix IDE lint
- cleanup: IDE lint
- Rename .java to .kt
- Migrate DeckPickerTest to Kotlin
- undo button in onCreateOptionsMenu cleanup
- Bumped version to 2.16alpha73
- Fix `DeckPicker#searchDecksIcon` flash

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-04 21:37 UTC, BrayanDSO reviewed
FWIW, I've cherry-picked this to my local AnkiDroid build and have been using it for ~3 weeks now and it works perfectly.

2022-08-04 21:37 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        }
Can you please add a comment here stating what kind of error this can throw and why it should be catch?

2022-08-05 06:12 UTC, david-allison requested changes
I believe that this will crash if the collection cannot be opened (for example: corruption).

2022-08-05 06:13 UTC, david-allison approved these changes
Actually... mirroring @BrayanDSO's comment. This will work in all cases, but a comment would be much appreciated

2022-08-05 14:50 UTC, BrayanDSO requested changes

2022-08-05 14:50 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    // Try setting it to `col.decks.count() >= 10`. If there was any issue (e.g. corrupt collection), set it to false
```suggestion
    /**
      * Show [searchDecksIcon] if there are more than 10 decks.
      * Otherwise, hide it if there are less than 10 decks 
      * or if a exception is thrown while getting the decks count (e.g. corrupt collection)
      */
```

Using a javadoc here may be more useful, as the user will be able to see this description while hovering the method on the IDE

2022-08-05 15:30 UTC, BrayanDSO commented
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:642:1 Unexpected indentation (6) (should be 5)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:643:1 Unexpected indentation (6) (should be 5)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:643:59 Trailing space(s)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:643:60 Unnecessary long whitespace
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:644:1 Unexpected indentation (6) (should be 5)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:645:1 Unexpected indentation (6) (should be 5)

My suggestion had one more space than necessary, not it needs a fix, I'm sorry

2022-08-05 17:55 UTC, BrayanDSO approved these changes

2022-08-07 09:31 UTC, lukstbit approved these changes

2022-08-07 09:32 UTC, merged