Add `getThemedColor` helper function
ankidroid/Anki-Android pull request #11863
Opened 2022-07-15 20:28 UTC by viciousAegis

## Pull Request template

## Purpose / Description

As suggested by David in this [comment](https://github.com/ankidroid/Anki-Android/pull/11713#discussion_r908323915)

> This is repeated a lot and we could get a lot of readability from extracting this to a helper extension method somewhere in the utils package
```kotlin
    @ColorInt
    fun Fragment.getThemedColor(@AttrRes attribute: Int): Int {
        return Themes.getColorFromAttr(
            activity,
            attribute
        )
    }
```
## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-07-15 20:31 UTC, viciousAegis commented
@david-allison Here's the first helper function, works perfectly, I'll add a small test if you feel the need, otherwise not too big of a change.

2022-07-16 08:11 UTC, ShridharGoel approved these changes

2022-07-17 12:09 UTC, david-allison requested changes
I love this! No need for a test

Can we also apply this to `Context` in a second commit? Which would make even more code cleaner

2022-07-17 12:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/FilterSheetUtils.kt
> +            activity,
(optional): I'd prefer it as `this.activity` here

2022-07-17 12:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/FilterSheetUtils.kt
> +object FilterSheetUtils {
This is a general utility, not just for `FilterSheet`

2022-07-17 16:48 UTC, Arthur-Milchior reviewed
I appreciate it.
I was wondering whether you could use it in other use of `getColorFromAttr`, but after a test locally, I wasn't able to succeed easily

2022-07-17 16:48 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/FilterSheetUtils.kt
> +        return Themes.getColorFromAttr(
Optional:
Replace `: Int {return` by  `=`

2022-07-17 16:48 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/FilterSheetUtils.kt
> +object FilterSheetUtils {
I believe it could be in com.ichi2.themes.Themes , since it uses its method and is dealing with Themes.

2022-07-18 18:41 UTC, david-allison commented
Oh, since Shridhar approved, let's get this in

2022-07-18 18:41 UTC, merged