[GSoC] Refactor preferences update
ankidroid/Anki-Android pull request #11874
Opened 2022-07-17 00:19 UTC by BrayanDSO

Continuation of #11873

## Purpose / Description

Updating preferences was problematic, with [updatePreference](https://github.com/ankidroid/Anki-Android/blob/abd1f8bfc316cdf11aba51af7bda7f5b05c493d7/AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt#L438) being ran every time any preference is changed. Also, the preferences activity had the responsability of mananing methods of specific preferences, which isn't a good design (e.g. [this](https://github.com/ankidroid/Anki-Android/blob/abd1f8bfc316cdf11aba51af7bda7f5b05c493d7/AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt#L280))

To keep things tidy, concise, and keep the preferences' configuration responsability on themselves and on their screens, I've done some refactors on the preferences activity

## Approach

1. Extract the preferences update to their screens on the `Update X preference individually` commits
- The required changes that escape the previous 2 patterns are marked on the commits as a `**` on the message beginning and are described as well

## How Has This Been Tested?

Manually opened/changed all preferences and it still works correctly. I should upload a video of it later.

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-07-17 13:19 UTC, david-allison requested changes
Thank you! This is refactoring that I would have done if I had the time

2022-07-17 13:19 UTC, david-allison commented on AnkiDroid/src/main/res/values/10-preferences.xml
> -    <string name="sync_account_summ_logged_in" comment="The summary for the account setting when logged in. Parameter is the username (email)">%s</string>
Agreed

2022-07-17 13:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +                (requireActivity() as Preferences).closePreferences()
optional: comment here would be useful

2022-07-17 13:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +                }
This feels like a functional change. Could you explain it in the commit message.

2022-07-17 13:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +                CrashReportService.onPreferenceChanged(requireContext(), newValue as String)
⚠️  Has this been tested?

2022-07-17 13:19 UTC, david-allison commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="anki_card_context_menu_summary">Enables the ‘Anki Card’ option globally. With it, you can send any selected words to the note editor to quickly create new notes</string>
@mikehardy Unsure about this one, tagging for comment

2022-07-17 13:50 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +                CrashReportService.onPreferenceChanged(requireContext(), newValue as String)
Logic is right to me. And with manual tests of `Dev options > Trigger test crash`, it works right as well.

Anyway, adding automated tests is always good, so I should add one on this PR later.

2022-07-17 13:55 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +                (requireActivity() as Preferences).closePreferences()
added
```
// It's only possible to change the language by recreating the activity,
// so do it if the language has changed.
// TODO recreate the activity and keep its previous state instead of just closing it
```

2022-07-17 13:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +                }
It is. Added it to the commit message.
```
In order to work correctly, Automatic Display Answer enables Keep Screen on automatically. But, if the user disabled Automatic Display Answer, Keep Screen on would be disabled as well, which isn't expected if the user wanted only Keep Screen On enabled. So this fixes it as well.
```

2022-07-17 15:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +                CrashReportService.onPreferenceChanged(requireContext(), newValue as String)
Appreciated! Automated tests are great, but I wouldn't block this PR on it.

2022-07-17 15:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
> +                }
I believe there was an issue about this, but I can't see it now

Anyway, that's fine

2022-07-17 15:43 UTC, david-allison requested changes
I believe I posted this on another PR in the stack, but I'd like to see the doc comments on the constants moved to the `preferences.xml`

2022-07-17 17:09 UTC, BrayanDSO commented
> I believe I posted this on another PR in the stack, but I'd like to see the doc comments on the constants moved to the preferences.xml

I moved them to above their preferences (https://github.com/ankidroid/Anki-Android/pull/11873/commits/1baac16182a08fa49bf1d86ede427894d41326dd) as I think that's more useful there than on `preferences.xml`. Let me know if this approach is okay

2022-07-17 17:24 UTC, david-allison commented
> > I believe I posted this on another PR in the stack, but I'd like to see the doc comments on the constants moved to the preferences.xml
> 
> I moved them to above their preferences ([1baac16](https://github.com/ankidroid/Anki-Android/commit/1baac16182a08fa49bf1d86ede427894d41326dd)) as I think that's more useful there than on `preferences.xml`. Let me know if this approach is okay

works for me

2022-07-17 21:49 UTC, mikehardy commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="anki_card_context_menu_summary">Enables the ‘Anki Card’ option globally. With it, you can send any selected words to the note editor to quickly create new notes</string>
🤔 hmmm 
I think "context menu entry"
I think something like "device's system context menu for text selections" so people know it isn't just our system but is unambiguously the whole phone and they know when the entries are triggered?

Anything like that, to be more specific, works for me

2022-07-18 02:22 UTC, david-allison commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="anki_card_context_menu_summary">Enables the ‘Anki Card’ option globally. With it, you can send any selected words to the note editor to quickly create new notes</string>
The diff moves from `Show ‘%s’ context menu` to `Show ‘Anki Card’ context menu` and `Show ‘Card Browser’ context menu`

I'm unsure if this is a localization issue and would like a second opinion, especially as it adds a place where issues in the translation can occur (`'Anki Card'` now needs to be consistent with the string for `Anki Card`)

2022-07-18 14:57 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="anki_card_context_menu_summary">Enables the ‘Anki Card’ option globally. With it, you can send any selected words to the note editor to quickly create new notes</string>
> `Anki Card' here now needs to be consistent with the string for Anki Card`

So I'll keep the previous title and adapt the summaries, as I still believe that they should have a descriptive message

2022-07-18 19:39 UTC, david-allison approved these changes
I approve, but do not approve of the dependent PR

2022-07-24 17:10 UTC, Arthur-Milchior approved these changes

2022-07-24 17:10 UTC, merged