Fix crash during deck filtering
ankidroid/Anki-Android pull request #11880
Opened 2022-07-18 01:14 UTC by shaiguelman

## Pull Request template

## Purpose / Description
Fixes issue where search bar was not filtering properly and crashing the app.

## Fixes
Fixes [#11877](https://github.com/ankidroid/Anki-Android/issues/11877)

## Approach
Creates a copy of the list of decks before filtering. The error was caused by using the same list in filtering as in the UI. I also made a small optimization of the containsFilterString method as well as added error catching in TypedFilter in case error happens again.

## How Has This Been Tested?

Reproduced error using process described in the issue before and after code changes. Screenshot of results after code changes:

![Screenshot_20220717-200601](https://user-images.githubusercontent.com/42308480/179432656-e1b62b2c-d71c-4b30-aa97-9e3ec5cbac7e.png)

## Learning (optional, can help others)

[Stack overflow post that helped me narrow the issue](https://stackoverflow.com/questions/41316886/concurrentmodificationexception-inside-publishresult-arrayadapter)

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-07-18 02:18 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
> +                childrenCopy.addAll(ret)
It seems to me that the original bug is here. Am I correct in this assumption?

I believe the intention of the code was that `children` referred to the TreeNode, but instead it referred to `val children = root.children`

2022-07-18 03:29 UTC, shaiguelman commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
> +                childrenCopy.addAll(ret)
Yea, I just tested changing children to this.children and that fixed the issue. No idea how I missed that. I'll update PR

2022-07-18 03:31 UTC, shaiguelman commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
> +                childrenCopy.addAll(ret)
It's weird that my solution also worked, but yours uses much less memory

2022-07-18 16:40 UTC, david-allison requested changes
I love this, thank you!

Revert the `publishResults` change (or discuss if I'm wrong) and it's good to go

2022-07-18 16:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt
> +        }
I'd prefer to fail fast here. This should be caught further up the call stack where the context is understood.

2022-07-18 16:40 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckAdapterFilterTest.kt
> +class DeckAdapterFilterTest {
LOVE THIS. THANK YOU!

2022-07-18 17:39 UTC, shaiguelman commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
> +            return deckName.contains(filterPattern, ignoreCase = true)
Well I learned something new about the Turkish alphabet from this comment. I would say in that situation we probably would not want to match but I am happy to defer to whatever you think is best

2022-07-18 17:46 UTC, shaiguelman commented on AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt
> +        }
Yea, I'm not sure exactly where else I could catch it without putting a generic catch in publishResults(). I'll just remove this completely on the assumption that the unit tests should stop this from happening

2022-07-18 17:46 UTC, shaiguelman commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckAdapterFilterTest.kt
> +class DeckAdapterFilterTest {
Yay!

2022-07-18 19:24 UTC, david-allison approved these changes
looks great, thank you so much

2022-07-18 20:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt
> +        val list = try {
I think an explicit call to `if results == null` would be better. Try are more costly than conditional in general, and anyway clearer.

2022-07-18 20:55 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckAdapterFilterTest.kt
> +                TreeNode(DeckTreeNode("Chanson", 0)),
Thanks very much for adding test. Really appreciated!

2022-07-18 21:08 UTC, shaiguelman commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
> +            return deckName.contains(filterPattern, ignoreCase = true)
No, it's not directly related. I figured it would be a slight optimization but as mentioned by David above, it does have a small change in behavior in different alphabets. I can revert this change we don't want this change

2022-07-18 21:11 UTC, shaiguelman commented on AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt
> +        val list = try {
I've since reverted this code since David said it was better to have it crash

2022-07-18 21:12 UTC, shaiguelman commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckAdapterFilterTest.kt
> +                TreeNode(DeckTreeNode("Chanson", 0)),
My pleasure!

2022-07-19 05:52 UTC, shaiguelman commented on AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt
> +        val list = try {
I changed it to use a nullable to avoid an awkward if check

2022-07-19 06:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt
> +        val list = try {
I think I'd prefer a crash here, as it's an assertion which doesn't hold, but I'll leave the final decision to you. Implementer's choice, I'm happy either way =)

2022-07-19 17:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
> +            return deckName.contains(filterPattern, ignoreCase = true)
I'd appreciate if you revert it please. Just so that it does not block until we are convinced that this change is acceptable

2022-07-19 18:58 UTC, shaiguelman commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
> +            return deckName.contains(filterPattern, ignoreCase = true)
Reverted

2022-07-19 19:10 UTC, shaiguelman commented on AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt
> +        val list = try {
Yea that's a good question. I did no results since that was simpler to implement but it's not necessarily the best UX choice.  It would require a sizeable refactor though to return all results.

I think since we're getting a little outside the scope of the PR I'll revert it to original for now and leave it for a non-urgent issue.

2022-07-21 04:48 UTC, lukstbit approved these changes

2022-07-21 11:36 UTC, merged

2022-07-21 11:37 UTC, david-allison commented
Thank you!


![](https://media.giphy.com/media/vmon3eAOp1WfK/giphy.gif)