fixed automatic creation of deck with name 'All decks'
ankidroid/Anki-Android pull request #11907
Opened 2022-07-22 18:29 UTC by divyansh-dxn

## Purpose / Description
Bug fix

## Fixes
Fixes #10800

## How Has This Been Tested?
Unit tested and on Realme 6i API 30

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-07-22 18:51 UTC, BrayanDSO commented
I don't think the toast is necessary. Just doing nothing if the user long tap All Decks is fine to me

2022-07-22 19:06 UTC, divyansh-dxn commented
I thought it would be confusing if nothing happened on long click because everything else in the list has long click. 
Let's wait for someone else's feedback then will do.

2022-07-23 10:04 UTC, lukstbit requested changes

2022-07-23 10:04 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +                            showThemedToast(context, "You cannot create a subdeck for all decks", true)
Personally I'm ok with the toast because the row displays a visual indicator when long pressed. 
If you keep the toast, please extract the string to a resource string.

2022-07-23 16:19 UTC, divyansh-dxn commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="cannot_create_subdeck_for_all_decks">You cannot create a subdeck for all decks</string>
extracted the string, but wasn't sure where to properly put it. Suggest if any changes required.

2022-07-24 05:51 UTC, lukstbit requested changes

2022-07-24 05:51 UTC, lukstbit commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="cannot_create_subdeck_for_all_decks">You cannot create a subdeck for all decks</string>
This is a dialog and we have a 03-dialogs strings file so I would move it there(maybe with a comment above it `<!-- Deck selection dialog -->`)

2022-07-24 08:06 UTC, lukstbit approved these changes

2022-07-24 19:03 UTC, mikehardy approved these changes
This works for me - thanks all, for the fix and for the reviews

Maintainers note - I want to get a translations sync in before merging this so it's clean in the translations

So, blocked merge waiting on #11911

2022-07-24 19:41 UTC, merged