fix: IDE lint in SchedTimingToday
ankidroid/Anki-Android pull request #11901
Opened 2022-07-21 13:10 UTC by oyeraghib

## Purpose / Description
discussed in #11900

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-07-21 13:57 UTC, david-allison approved these changes

2022-07-22 05:29 UTC, lukstbit requested changes

2022-07-22 05:29 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/SchedTimingToday.kt
> +@Suppress("FunctionName")
I think we should add an explanatory comment here:

`// keep method names for consistency with Anki desktop naming`

2022-07-23 13:26 UTC, lukstbit approved these changes

2022-07-23 13:27 UTC, merged