[GSoC] Reorganize some preferences + refactors
ankidroid/Anki-Android pull request #11934
Opened 2022-07-27 23:54 UTC by BrayanDSO

## Purpose / Description
On top of #11919

This is the last preferences reorganization PR I want to do for GSoC. Previously I'd thought about moving all the preferences from Advanced to the other screens, but after thinking a while, I've come to the conclusion that the it's best to keep it as a bucket of "Things most users won't need or are really advanced, therefore they shouldn't be dispute space with the more relevant ones".

As an example we have `Simple typed answer formatting`, only useful if typed answer is used AND the typed answer uses Polytonic Greek characters AND older webviews are being used.

Other preferences there will be gone some day (e.g. `Replace newlines with HTML` when the visual editor is implemented). Others can be moved to the activities they impact (e.g. `Default deck when opening statistics` being moved to the statistics screen). And others need analytics (#11642) to evaluate if they can be discarded.

So, overall there isn't anything else I want to move right now.

## Approach
- Moved preferences:
    - `HTML/Javascript debug`: Advanced → Developer options
    - `Card browser` and `Anki card` context menus, and `Press back twite to go back/exit`: Advanced → General
    - `Card browser font scaling`: Appearance → Accessibility
- Removed `V2 scheduler` preference
    - 142f789a7bddaf46fbc4f9bd7e32defd3e4ae84d forces requires/prompts to use the V2 scheduler when the user tries to study, so this preference is no longer necessary
- Build summaries for the remaining categories (General, Appearance and Advanced)
    - ![image](https://user-images.githubusercontent.com/69634269/181390035-2cfe1506-e7fa-4a2f-8fde-3591821f123a.png)
- Some cleanups around HeaderFragment.kt

## How Has This Been Tested?

Opened the app and opened the preferences categories to see if I get any crash

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-07-30 19:53 UTC, david-allison requested changes
Some of the summaries don't explain things well as we don't have subcategories, this makes them more confusing (General in particular)

2022-07-30 20:16 UTC, BrayanDSO commented
> Some of the summaries don't explain things well as we don't have subcategories, this makes them more confusing (General in particular)

@david-allison 
Hmmmmm, maybe for General:

```
Category summary: Language º Studying º System-wide

Items:
- Language
- Share feature usage
- Error reporting mode
- Paste Images as PNG (i really don't know where to put this)

# Studying (or another name)
- Deck for new cards
- Press back twice to leave

# System-wide
- Anki Card Menu
- Card Browser Menu
```

The only ones I don't see fitting Advanced right now are:
1. AnkiDroid directory: I expect the preference to be changed after Scoped storage, so better evaluate it after it
2. Max backups number: will have a top category in the future
3. Open changelog: will be moved to `About` some day.

2022-07-30 21:23 UTC, Arthur-Milchior approved these changes
Globally fine. Some question regarding commit messages. A suggestion.

2022-07-30 21:23 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/PreferenceUtils.kt
> +fun <T : Preference> PreferenceFragmentCompat.requirePreference(key: String): T {
I noted only after creating this comment that it was actually a code you moved and not that you created. So I'm okay with not changing the method right now and leaving this change to #11948. As you want

2022-07-30 21:23 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/PreferenceUtils.kt
> +@Suppress("UNCHECKED_CAST")
I don't understand the meaning of the commit a7263c955d4117104c55ed571817f7b3cdd4d420 's message
> SettingsFragment previous equivalent

2022-07-30 23:51 UTC, BrayanDSO commented on AnkiDroid/src/main/res/xml/preferences_dev_options.xml
>          android:title="Trigger test crash"
Nice idea! Done it, thanks

2022-07-30 23:51 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/GeneralSettingsFragment.kt
> -        if (isRestrictedLearningDevice) {
Sure

2022-07-30 23:52 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
> +    private fun buildCategorySummary(@StringRes vararg resIds: Int): String {
Definitely. I should have remembered to add it. Done.

2022-07-30 23:53 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/PreferenceUtils.kt
> +fun <T : Preference> PreferenceFragmentCompat.requirePreference(key: String): T {
This is great. Implemented it.

2022-07-30 23:55 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/PreferenceUtils.kt
> +@Suppress("UNCHECKED_CAST")
Basically, the methods are moved from `SettingsFragment` to `PreferencesFragmentCompat`, so `HeaderFragment` can use the same methods, while the functionality is kept on the inheritors of `SettingsFragment` because it inherits from `PreferencesFragmentCompat` too.

Updated the commit message to make it more clear.

2022-07-31 00:37 UTC, BrayanDSO commented
Reorganized more "Advanced" prefs on the last 2 commits

2022-07-31 06:27 UTC, krmanik commented on AnkiDroid/src/main/res/xml/preferences_dev_options.xml
> +        android:summary="Enable remote WebView connections, and save card HTML to AnkiDroid directory"
The webview connection will help in debugging the html/css/js files for card template/reviewer screen. I think addons will add functionality to the app and it not connected to remote webview. The remote webview connection will not required by addons when reviewing the cards.  This settings mostly for card template developer and user may not need this because if any errors happen in the card template AnkiDroid show toast messages for the error e.g. http request, image not found etc.

The string should be translated.

2022-07-31 10:12 UTC, BrayanDSO commented on AnkiDroid/src/main/res/xml/preferences_dev_options.xml
> +        android:summary="Enable remote WebView connections, and save card HTML to AnkiDroid directory"
The strings can be removed on the future if they aren't really necessary, so I'll keep them for now to avoid blocking the PR.

2022-07-31 10:49 UTC, david-allison commented
your suggestion: LGTM

2022-07-31 11:52 UTC, Arthur-Milchior approved these changes

2022-07-31 11:53 UTC, Arthur-Milchior commented
Fine by me. @david-allison I let you merge/remove your requested change if you're okay with it

2022-07-31 12:03 UTC, david-allison commented
Will merge once changes are made + tested

2022-07-31 13:05 UTC, BrayanDSO commented
Last changes on 89640b20fc2f9c0415de8f2957ae2b44d2bb0898

2022-07-31 13:44 UTC, mikehardy commented on AnkiDroid/src/main/res/xml/preferences_dev_options.xml
> +        android:summary="Enable remote WebView connections, and save card HTML to AnkiDroid directory"
This feature is intended for non debug builds, for end users. It greatly reduced our issue load for motivated users with template problems

2022-08-05 06:09 UTC, david-allison approved these changes

2022-08-05 06:09 UTC, david-allison commented
@BrayanDSO Looks great! Would you want this rebased or squashed?

2022-08-05 09:43 UTC, BrayanDSO commented
@david-allison Squash, please.

2022-08-07 15:45 UTC, merged