[GSoC] Migrated CollectionTask.AddNote to Coroutines
ankidroid/Anki-Android pull request #11952
Opened 2022-07-31 18:21 UTC by divyansh-dxn

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-01 09:28 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/coroutines/CoroutineJob.kt
> +    open fun onCancelled() {}
Isn't there some way to make an open function private
Needed behaviour is, children class can override the but its instances cannot call them. Currently an instance call these callbacks but should not. Kind of insecure here. I wasn't able to find any such mechanism.

2022-08-01 19:24 UTC, divyansh-dxn commented
And one thing is on the todo is to improve the documentation, haven't done it for now just removed the irrelevant parts.

2022-08-02 17:50 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/coroutines/CoroutineJob.kt
> +    }
Inspired  from com.android.os.AsyncTask::get()

2022-08-03 14:29 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/async/coroutines/CoroutineJob.kt
> +    open fun onCancelled() {}
@david-allison Do you have any suggestion here?

2022-08-03 14:51 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/async/coroutines/CoroutineJob.kt
> +abstract class CoroutineJob<Params, Progress, Result>(
Would be good to include coroutine exception handling in this class.

2022-08-03 17:37 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/coroutines/CoroutineJob.kt
> +abstract class CoroutineJob<Params, Progress, Result>(
Could you explain where should I add exception handling, because as far as I understand it should be caller's responsibility to check for error as we don't know what code goes inside doInBackground, might be network call, database query etc, so catching it here would silence the exception.

2022-08-03 17:39 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/coroutines/CollectionTask.kt
> +            }
@ShridharGoel like here caller knows which exception to expect and handle it accordingly.

2022-08-03 18:42 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/async/coroutines/CollectionTask.kt
> +            }
Okay, but what about CancellationException?

2022-08-04 06:05 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/coroutines/CollectionTask.kt
> +            }
CancellationException is not for us to handle, see [here](https://kotlinlang.org/docs/exception-handling.html#cancellation-and-exceptions). These are internally used to manage of children jobs lifecycle.

2022-08-04 06:11 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/coroutines/CoroutineJob.kt
> +            Timber.d("$taskName has been cancelled.")
Cancelled and then logged

2022-08-05 12:27 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/async/coroutines/CoroutineJob.kt
> +abstract class CoroutineJob<Params, Progress, Result>(
It's okay if it's being handled at the caller side.

2022-08-06 13:25 UTC, dae commented
Disclaimer: I am not an AnkiDroid maintainer, and have not spent much time working with AnkiDroid's code, so I can only offer comments as an external observer. Hopefully a maintainer will offer their own thoughts when they have a chance.

I can see you've put a lot of effort into integrating coroutines into the existing CollectionTask API, and what you've done is technically impressive. That said, I am not sure this is the best path forward.

As an occasional contributor, my view of the CollectionTask API is not great - it makes it hard to follow the flow of the code, as it relies on a bunch of callbacks. IMHO, the main appeal of coroutines in that they allow asynchronous code to be written in a more straight-forward way without the use of callbacks. By keeping the existing CollectionTask API, I feel like this main benefit of coroutines is being lost.

Instead of keeping to the existing API, maybe there would be more value in rewriting the code to use coroutines natively? This will be more work in the short term, but should lead to easier to read code going forward.

Because I found CollectionTask hard to understand, I avoided it in the V16 code paths. For example, the sync code launches a coroutine instead of a collection task: https://github.com/ankidroid/Anki-Android/blob/bbeaf6dc926b9d5365675faa3e65269c1a59baef/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt#L1505, https://github.com/ankidroid/Anki-Android/blob/bbeaf6dc926b9d5365675faa3e65269c1a59baef/AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt#L44. Perhaps a similar approach could be used for existing CollectionTasks?

There's also the question of what else CollectionTask is providing. For serialization of requests, that should hopefully be addressed in https://github.com/ankidroid/Anki-Android/pull/11849. Are there other things that CollectionTask provides that would be missed?

2022-08-06 20:31 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/async/coroutines/CollectionTask.kt
> +            } catch (e: RuntimeException) {
Catch `Exception` and rethrow if it is `CancellationException`.

2022-08-06 20:36 UTC, ShridharGoel requested changes

2022-08-06 20:36 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/async/coroutines/CoroutineJob.kt
> +import kotlinx.coroutines.*
Avoid usage of wildcard imports.

2022-08-06 20:36 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/async/coroutines/TaskListenerWithContext.kt
> +    private val mContext = WeakReference(context)
Variable name should be `context`.

2022-08-06 20:36 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/async/coroutines/TaskManager.kt
> +        private var sTaskManager: TaskManager = SingleTaskManager()
Variable name should be `taskManager`.

2022-08-06 20:36 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/async/coroutines/SingleTaskManager.kt
> +    private val mTasks = Collections.synchronizedList(LinkedList<CollectionTask<*, *>>())
`tasks`

2022-08-06 20:36 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/async/coroutines/SingleTaskManager.kt
> +    private var mLatestInstance: CollectionTask<*, *>? = null
`latestInstance`

2022-08-06 20:36 UTC, ShridharGoel commented
@divyansh-dxn Is there a reason for not using `CoroutineExceptionHandler`?

2022-08-06 20:42 UTC, ShridharGoel commented
@dae has provided some good advice, it would be better to rewrite this flow instead of trying to migrate to coroutines using the existing code.

2022-08-07 07:17 UTC, divyansh-dxn commented
@dae @ShridharGoel  I would suggest to take a look on the recent push.

2022-08-07 07:20 UTC, divyansh-dxn commented
> Disclaimer: I am not an AnkiDroid maintainer, and have not spent much time working with AnkiDroid's code, so I can only offer comments as an external observer. Hopefully a maintainer will offer their own thoughts when they have a chance.
> 
> I can see you've put a lot of effort into integrating coroutines into the existing CollectionTask API, and what you've done is technically impressive. That said, I am not sure this is the best path forward.
> 
> As an occasional contributor, my view of the CollectionTask API is not great - it makes it hard to follow the flow of the code, as it relies on a bunch of callbacks. IMHO, the main appeal of coroutines in that they allow asynchronous code to be written in a more straight-forward way without the use of callbacks. By keeping the existing CollectionTask API, I feel like this main benefit of coroutines is being lost.
> 
> Instead of keeping to the existing API, maybe there would be more value in rewriting the code to use coroutines natively? This will be more work in the short term, but should lead to easier to read code going forward.
> 
> Because I found CollectionTask hard to understand, I avoided it in the V16 code paths. For example, the sync code launches a coroutine instead of a collection task:
> 
> https://github.com/ankidroid/Anki-Android/blob/bbeaf6dc926b9d5365675faa3e65269c1a59baef/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt#L1505
> 
> https://github.com/ankidroid/Anki-Android/blob/bbeaf6dc926b9d5365675faa3e65269c1a59baef/AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt#L44
> 
> Perhaps a similar approach could be used for existing CollectionTasks?
> 
> There's also the question of what else CollectionTask is providing. For serialization of requests, that should hopefully be addressed in #11849. Are there other things that CollectionTask provides that would be missed?

I was also thinking to re-implement it, but was afraid that other maintainers wouldn't allow to change from existing CollectionTask api. And yes, it is very hard to follow the current implementation. Took a lot of time for me also to just get to proper control-flow.

2022-08-07 15:49 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTasks.kt
> +}
I think this might be easier to follow if it's placed in NoteEditor instead of a separate file. I realise a lot of the V16 code uses separate files - the main reasons I did that is a) to keep the V16 separate, and b) reduce the chances of conflicts if the PRs took a long time to merge.

2022-08-07 15:49 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTasks.kt
> +        onProgress(noOfSavedNotes!!)
onProgress is another callback - why not eliminate it and return the number instead? You could change the Boolean to an Int?, where null denotes that the routine failed.

2022-08-07 15:49 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTasks.kt
> +            noOfSavedNotes = col.addNote(note, Models.AllowEmpty.ONLY_CLOZE)
It's the number of cards, not the number of notes

2022-08-07 15:49 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        mProgressDialog = StyledProgressDialog.show(this, null, resources.getString(R.string.saving_facts), false)
If https://github.com/ankidroid/Anki-Android/pull/11849 gets merged, progress can be handled more easily by wrapping the suspend fun in withProgress(message="..."): https://github.com/ankidroid/Anki-Android/blob/7c917defa789bf1106d34408a30509349fd430df/AnkiDroid/src/main/java/com/ichi2/anki/BackendUndo.kt#L27

2022-08-07 16:15 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTasks.kt
> +}
I thought of the function more of a utility rather than any member-function of NoteEditor. I'll just ask @ShridharGoel once what's his opinion to this.

2022-08-07 16:17 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTasks.kt
> +        onProgress(noOfSavedNotes!!)
Done the changes, you were right. Add note doesn't used contrinous progress updated anyhow. So it is more better to return the result instead of a callback. Also it is more cleaner now.

2022-08-07 16:17 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTasks.kt
> +            noOfSavedNotes = col.addNote(note, Models.AllowEmpty.ONLY_CLOZE)
updated

2022-08-07 16:18 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        mProgressDialog = StyledProgressDialog.show(this, null, resources.getString(R.string.saving_facts), false)
will keep this conversation open for future follow-ups.

2022-08-07 16:43 UTC, Arthur-Milchior commented
@divyansh-dxn Is this something that must be squashed or should we kept all commits?

To ask the same question in a different way. If I review the first commit alone, will it makes sens, or should I directly review the whole PR?

2022-08-07 16:48 UTC, divyansh-dxn commented
> @divyansh-dxn Is this something that must be squashed or should we kept all commits?
> 
> To ask the same question in a different way. If I review the first commit alone, will it makes sens, or should I directly review the whole PR?

Changes are to be squashed. Reviewing whole PR is better. Because first commit consisted of codes that I tried to replicated, and now no longer required.

2022-08-07 18:49 UTC, Arthur-Milchior reviewed
First, thanks a lot for this PR. I can't compare to previous versions since I didn't read them. This one is long but I feel relatively easy to follow, especially given the architectural change.

I feel like this commit message is far too short especially for a commit that has non trivial difficult to notice side effect.
I noted one about context/garbage collection.
Another side effect is that this `addNote` task is ignored by request to `waitToFinish`. To the best of my understanding it means that Connection::doInBackgroundSync may get to lockCollection while a note is saved.

Admittedly, this is a very theoretical concern, because ankidroid can only start sync from the DeckPicker activity, which requires NoteEditor to be closed, which in practice means that any edition must have been saved already. I'm totally fine merging this PR without taking this theoretical issue into account and wait to see whether it can actually lead to a crash before worrying. But at the very least, it really must be documented that this is a choice that was made.

Since those commits message are going to be pretty similar for each migration to coroutine, you may either:
* create a web page (on github probably) where this is discussed. Let's say an issue that details everything and link to this issue.
* document in details on the this commit, and then reference this commit from future commits to indicate that the changes are essentially the same

2022-08-07 18:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTasks.kt
> +package com.ichi2.async
I fear I don't understand this file. 
The name makes sens only in relation to `CollectionTask`, which itself was really derived from "`AsyncTask` that affects the collection". This is not a task anymore.

Also, I fear that in 6 months already people who tries to read our codebase have a strong risk to be confused by why there are two fines with similar name, may lose time openiing one when they want the other, not knowing the difference, get confused by why they don't find the method they are lookng for, etc...
And also not understand how the various methods in this file relate.
Admittedly, that's also a problem with today's CollectionTask, but that is at least something you may be solving with your work

So either you leave this method in `CollectionTask`, which seems as acceptable as being in this file, and avoid creating a new file.
Or you can move this to `NoteEditor` since it's the only place where it's called, this seems quite natural (actually, I don't understand why I didn't moved it when I changed the architecture)

2022-08-07 18:49 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
> +    private val testDispatcher = StandardTestDispatcher()
I suggest moving this to RobolectricTest to avoid code duplication.
If it's costly to construct (honestly, no idea), then maybe just put it behind a singleton factory that ensures it's constructed only when required

2022-08-07 18:49 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
> +    fun clozeNoteWithNoClozeDeletionsDoesNotSave(): Unit = runTest(testDispatcher) {
I'd suggest creating

```kotlin
public fun runTest(
    context: CoroutineContext = testDispatcher,
    dispatchTimeoutMs: Long = DEFAULT_DISPATCH_TIMEOUT_MS,
    testBody: suspend TestScope.() -> Unit
) =
kotlinx.coroutines.test.runTest(context, dispatchTimeoutMs, testBody)
```
potentially annotated with `@ExperimentalCoroutinesApi`

this way, you'll avoid having to repeat `testDispatcher` everywhere

2022-08-07 18:49 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
> +    fun clozeNoteWithNoClozeDeletionsDoesNotSave(): Unit = runTest(testDispatcher) {
nit: ": Unit" seems to be useless. If so, you can remove it

2022-08-07 18:49 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/async/CollectionTasksTest.kt
> +    @Ignore("needs to be implemented")
Can you please be more clear. What exactly needs to be implemented?

2022-08-07 18:56 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> -        override fun actualOnPostExecute(context: NoteEditor, result: Boolean?) {
Yes this was one of the problem with the older AsyncTask API. But for activities we have lifecycleScope launcher functions to start a coroutine from activity or any lifecycleOwner. Any coroutine launched using it will automatically get cancelled once the lifecycle ends. So there is no risk of memory leaks while using coroutines with lifecycle components.

2022-08-07 18:58 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> -        override fun actualOnPostExecute(context: NoteEditor, result: Boolean?) {
This is one way how coroutines make life easier :)

2022-08-07 20:36 UTC, divyansh-dxn commented
@Arthur-Milchior Now I think individual commit make more sense and it would be easy to follow up from previous to next commits.

2022-08-07 20:44 UTC, divyansh-dxn commented on AnkiDroid/src/test/java/com/ichi2/async/CollectionTasksTest.kt
> +    @Ignore("needs to be implemented")
not required now

2022-08-07 20:49 UTC, divyansh-dxn commented on AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
> +    private val testDispatcher = StandardTestDispatcher()
I also don't know about cost of its creation but the idea is to have a single test dispatcher for testing, this way it is evident that a coroutine launched, returns to its launcher and doesn't dangle around via other dispatchers. BTW, moved to RobolectricTest. I was avoiding it because of ExperimentalCoroutinesApi but I guess just adding on the field is okay and doesn't needs to be followed up by there  test classes.

2022-08-07 20:50 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTasks.kt
> +package com.ichi2.async
Moved to NoteEditor

2022-08-08 20:49 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTasks.kt
> +}
Let's keep it in NoteEditor itself.

2022-08-10 17:22 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            noOfSavedCards!!
I suspect lambda in db.executeInTransaction executes on different thread, so might it be possible that db-transaction is still going but we return noOfSavedCards? I'm asking because IDK how it goes and threads go internally in db.executeInTransaction. Would be helpful if someone else look into and let me know.

2022-08-10 23:42 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            noOfSavedCards!!
Did you try to read the source of that function? :-) It's not a suspend fun and it returns the output from the provided closure, so it must be blocking.

2022-08-11 04:38 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            noOfSavedCards!!
But the passed lambda is a runnable and internally it calls r.run();, so won't it launch that on a new thread.

2022-08-11 05:32 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            noOfSavedCards!!
I can see how that might be confusing, but there are no thread calls in executeInTransaction() - it merely takes the passed runnable and calls .run() on it. Runnable is just an interface - there is no magic behind it.

2022-08-11 11:47 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            noOfSavedCards!!
Yes got it now, seen under the hood it is just an interface with run method.

2022-08-12 11:25 UTC, divyansh-dxn commented
@ShridharGoel @Arthur-Milchior requires review.

2022-08-13 00:10 UTC, Arthur-Milchior reviewed
Generally I approve. My only question that may be blocking would be, why is progressDialog not dismissed anymore.

Not merging, not only because I'll want a second review, but also because I'd like you to add far far more javadoc and commit explanation. Not only would I'd love to be helped more, but I'd also want for the future readers to ensure they can understand exactly what the code does, and if they have a doubt, how we came to create such a code.

But generally, it seems great. And I can't wait until the entire artitecture and process is totally agreed, so that we can make the other ones even simpler

2022-08-13 02:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            db.executeInTransaction {
Once #12017 is merged, hopefully, you can just do 
`{collection.addNote(note, Models.AllowEmpty.ONLY_CLOZE)}` and it'll return the value directly.

2022-08-13 03:55 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +    public static CoroutineDispatcher backgroundDispatcher = Dispatchers.getDefault(); // CPU intensive work should be done on this
#10305 takes a bit of a different approach - instead of relying on callers to switch to the correct dispatcher, they use higher-level APIs like 'withCol { ... }' that automatically run the provided block on a a custom dispatcher that ensures operations are serialized, eg instead of `withContext(ioDispatcher) { val col = getCol(); ... }`, it becomes `withCol { ... }`. Because the provided block is not suspendable, it also keeps nesting to a minimum, eg code like this is not possible:

```
withContext(ioDispatcher) {
   val result = getCol().doSomething()
   withContext(main) {
     someUiStuff(result)
   }
}
```

Instead it would look like:

```
val result = withCol { doSomething() }
someUiStuff()
```

Since this PR is sort of setting the stage for how how AnkiDroid will be adopting coroutines in the future, it may be worth considering the changes in #11849 around the same time.

I believe the distinction between CPU-intensive and IO-intensive dispatchers is mainly about how many threads are used to back them. In this case of withCol, since requests are serialized, it probably doesn't matter which one is picked.

2022-08-13 03:55 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                catchingLifecycleScope(this) { saveNote() }
Related: https://github.com/ankidroid/Anki-Android/pull/12011

2022-08-13 04:03 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                catchingLifecycleScope(this) { saveNote() }
Related: https://github.com/ankidroid/Anki-Android/pull/12011

2022-08-13 10:45 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/async/coroutines/CoroutineJob.kt
> +    open fun onCancelled() {}
@ShridharGoel did you still need my advice here?

2022-08-15 03:17 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/async/coroutines/CoroutineJob.kt
> +    open fun onCancelled() {}
@david-allison No, this code is outdated now.

2022-08-15 03:24 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        } catch (e: RuntimeException) {
https://github.com/ankidroid/Anki-Android/pull/11952#discussion_r939572691

Also, any reason for not using `CoroutineExceptionHandler` here?

2022-08-15 18:01 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                    this@NoteEditor,
This was from previous implementation, at that time this would point to SaveNoteHandler instance. Not required now, removing it.

2022-08-15 18:42 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        private var mainDispatcher: CoroutineDispatcher = Dispatchers.Main
Clearly for current implementation it is not required, but still adding a comment would be good, 
`create a backgroundDispatcher = Dispatchers.Default for CPU intensive works` for future implementation if required any

2022-08-15 22:50 UTC, Arthur-Milchior commented
FYI you have a merrge conflict

2022-08-16 17:04 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            db.executeInTransaction {
done

2022-08-16 17:04 UTC, divyansh-dxn commented on AnkiDroid/src/test/java/com/ichi2/anki/stats/AnkiStatsTaskHandlerTest.kt
> -    private val testDispatcher = StandardTestDispatcher()
done

2022-08-16 20:04 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            handleSaveNote(col, mEditorNote!!)
Now that #11849 is merged, you can use withCol:

```
            mReloadRequired = true
            withProgress {
              withCol {
                models.current()!!.put("tags", tags)
                models.setChanged()
                handleSaveNote(this, mEditorNote!!)
             }
           }
```

- This automatically switches context to a background dispatcher, so withIO is not required in doInBackgroundSaveNote
- This takes care of showing the progress dialog if the routine takes time, so the progress code in handleSaveNote/postSaveNote can be removed
- Because withCol expects a non-suspend closure, doInBackgroundSaveNote() and handleSaveNote() will need to be made synchronous.
Note this automatically switches context to a background queue, so

2022-08-17 17:58 UTC, divyansh-dxn commented
Create a new PR #12059 for the first commit. Going through the discussion I finally agree, as @Arthur-Milchior earlier said, it would be clean, merge fastly and make this PR to review easier.

2022-08-18 07:27 UTC, divyansh-dxn commented
##12070 Combines the logic of onProgressUpdate and onPostExecute in SaveNoteHandler. Merging #12059 would also simplify changes on this one.

2022-08-18 20:27 UTC, divyansh-dxn commented
For the first commit, function copy-pasted and moved elsewhere. While doing at the same place, lines were getting jumbled in git diff and that would have been harder to review as compared to copy-paste elsewhere.

2022-08-19 03:08 UTC, dae reviewed
Looking good!

2022-08-19 03:08 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                // prepare UI: no need because it is already handled by withProgress
This comment appears to be talking about the migration, but will not be useful for people visiting this code in the future.

2022-08-19 03:08 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                    // add note in background, withCol itself performs operation on IO dispatcher
This may come down to personal preference, but this comment feels a bit unnecessary - withCol will hopefully be used throughout the codebase in the future, and it would be a bit redundant to explain it each time.

2022-08-19 03:08 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +    }
I know this was discussed earlier, but having looked more closely at the code, I think it might be best to stop catching errors here, and return an Int instead of an Int?. The original code swallows the error, then calls context.closeNoteEditor(DeckPicker.RESULT_DB_ERROR, null) to close the editing screen. I think that's a bad idea - the user may have typed a lot of text in, and it gets discarded when an error occurs. Instead, I'd recommend you just rely on launchCatchingTask to display an error to the user. Once they close it, the stuff they typed in will still be there, and if they wish to preserve it, they could copy and paste it into a notes app, and manually close the screen when they're done. Without the try/catch, doInBackgroundAddNote() also becomes simpler, and it may be worth embedding the remaining code inside the withCol call below, and removing this separate function.

2022-08-19 20:31 UTC, divyansh-dxn commented
Before and after comparison for handled error. Throw an Exception manually to test this behaviour.

https://user-images.githubusercontent.com/69595691/185702339-6156eaaa-afdc-459e-b97b-181445cbd881.mp4

https://user-images.githubusercontent.com/69595691/185702329-80a27aa2-168f-47e4-b332-4d66f9fe9d4f.mp4

2022-08-20 03:43 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            // update UI based on the result from doInBackgroundAddNote
```suggestion
```

2022-08-20 03:43 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        }
This progressDialog code can be removed I think?

2022-08-20 05:55 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            context.sourceText = null
Also I believe this condition can be removed because addNote never returns n<0.
```kotlin
fun addNote(note: Note, allowEmpty: Models.AllowEmpty? = Models.AllowEmpty.ONLY_CLOZE): Int {
        // check we have card models available, then save
        val cms = findTemplates(note, allowEmpty)
        // Todo: upstream, we accept to add a not even if it generates no card. Should be ported to ankidroid
        if (cms.isEmpty()) {
            return 0
        }
        note.flush()
        // deck conf governs which of these are used
        val due = nextID("pos")
        // add cards
        var ncards = 0
        for (template in cms) {
            _newCard(note, template, due)
            ncards += 1
        }
        return ncards
    }
```

2022-08-20 06:12 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        }
Yes, since we are not dealing with progress dialog here anymore.

2022-08-20 06:25 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            // update UI based on the result from doInBackgroundAddNote
// update UI based on the result, noOfAddedCards

2022-08-21 21:32 UTC, Arthur-Milchior approved these changes

2022-08-22 15:10 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +     * @param noOfAddedCards noOfSavedCards, null if any exception occurred internally
Repetetion,

2022-08-22 15:11 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +     * @param noOfAddedCards noOfSavedCards, null if any exception occurred internally
Repetition, can be removed.

2022-08-22 15:22 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +    }
Yes, In fact first commit actually just a copy-paste. I've made the suggested changes in the last commit "Improved error handling while adding note"

2022-08-22 15:47 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +    private val context = this
Yeah, got your point. I thought had done it but missed, my bad.

2022-08-22 17:49 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        mProgressDialog = StyledProgressDialog.show(this, null, resources.getString(R.string.saving_facts), false)
Since already done, resolving it.

2022-08-22 18:14 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        if (!addNote || caller == CALLER_NOTEEDITOR || aedictIntent) {
Implementer's choice:  Can be replaced with `when`.

2022-08-22 18:56 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        } else if (!mEditFields!!.isEmpty()) {
Use `isNotEmpty`

2022-08-22 18:58 UTC, divyansh-dxn commented
@ShridharGoel I believe these are kotlin cleanup, and deserve independent PRs. That would unnecessarily populate this PR. I believe ?

2022-08-22 19:33 UTC, ShridharGoel commented
@divyansh-dxn Okay, you can add them in the cleanup then.

On Tue, 23 Aug 2022 at 00:28, Divyansh Kushwaha ***@***.***>
wrote:

> @ShridharGoel <https://github.com/ShridharGoel> I believe these are
> kotlin cleanup, and deserve independent PRs. That would unnecessarily
> populate this PR. I believe ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ankidroid/Anki-Android/pull/11952#issuecomment-1222788046>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIPLJHCTBZ4UOUVCNAGY6XLV2PEW5ANCNFSM55FJ4G6A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-24 10:50 UTC, dae commented
No more objections on my end - this is a nice improvement over what there was before. :-)

2022-08-24 19:49 UTC, ShridharGoel approved these changes

2022-08-24 19:49 UTC, merged