NF: browser use two columns explicitly
ankidroid/Anki-Android pull request #11956
Opened 2022-07-31 22:27 UTC by Arthur-Milchior

I believe this version
is more readable.

2022-08-19 03:08 UTC, mikehardy approved these changes
works for me, thanks

2022-08-22 14:54 UTC, lukstbit requested changes
Changes break functionality in CardBrowser by not showing the answer(the second column), see images below(first images shows the current main branch, second image shows CardBrowser with the changes from this PR):

<img src="https://user-images.githubusercontent.com/52494258/185950619-1b4dde57-95b7-484e-a656-3e030ca5bd9f.png" width="300" height="600"/><img src="https://user-images.githubusercontent.com/52494258/185951707-98087f5c-affd-4a1a-9521-08d2c55cf37c.png" width="300" height="600"/>

Most likely related to the two issues below.

2022-08-22 14:54 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            COLUMN1_KEYS[mColumn2Index],
Duplicated column here where the original code used  COLUMN1_KEYS and COLUMN2_KEYS.

2022-08-22 14:54 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            columnOneView.text = card.getColumnHeaderText(columnTwo)
Duplicated code from two lines above with column one, should have been `columnTwoView.text`.

2022-08-23 14:24 UTC, david-allison reviewed
At least personally, I'd like to move to a CardBrowser which has more than two columns in the future.

2022-08-23 17:12 UTC, mikehardy commented
> I'd like to move to a CardBrowser which has more than two columns in the future. I'm not sure if this is a shared opinion

Maybe if it was configurable? Otherwise I am thinking you have a bigger phone and keener eyesight then I do, good sir

2022-08-23 17:49 UTC, david-allison commented
> > I'd like to move to a CardBrowser which has more than two columns in the future. I'm not sure if this is a shared opinion
> 
> Maybe if it was configurable? Otherwise I am thinking you have a bigger phone and keener eyesight then I do, good sir

We also support tablets

2022-08-23 18:31 UTC, mikehardy commented
Those are use cases I could see it making sense but 2 still seems like a nice starter default. Maybe this is one of the rare-ish places where having different layouts for width >= 600dbp really does make sense. I do like responsive layouts a lot

2022-08-23 21:25 UTC, david-allison commented
I fear I misspoke. For phones, I want 2 columns as a default.

For tablets, we can calculate this and may want more than two.

I don't think that fixing the number of columns to 2 brings us closer to this goal, so I don't agree with the premise of this PR

2022-08-23 22:02 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            columnOneView.text = card.getColumnHeaderText(columnTwo)
Thanks a lot!

2022-08-23 22:03 UTC, Arthur-Milchior commented
I can understand having many columns. I believe that this will need so much rewritting that this PR don't really oppose it, because anyway, even current code would be hard to directly use to add more columns. Because size two is already hard coded here and both columns are distinct

2022-08-23 22:28 UTC, mikehardy commented
I agree with both - column flexibility in future would be good but if I remember correctly from my review here, this is just making the previous hard code of 2 really obvious. Not a bad thing

2022-08-23 23:32 UTC, david-allison commented
I don't like this for reasons stated above, but won't block it going in

2022-08-24 00:48 UTC, mikehardy commented
Okay - may be sideways motion from a flexible layout perspective, but I don't think it hurts and it did seem like at least a marginal improvement

2022-08-24 00:48 UTC, merged