View animation
ankidroid/Anki-Android pull request #11961
Opened 2022-07-31 23:02 UTC by Arthur-Milchior

2022-08-04 15:43 UTC, lukstbit requested changes

2022-08-04 15:43 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anim/ViewAnimation.kt
> +    private fun translateAnimation(fromXValue: Float, toXValue: Float, fromYValue: Float, toYValue: Float) =
This method is unused, I'm assuming you wanted it to replace the direct `TranslateAnimation` instantiation below.

2022-08-05 06:18 UTC, david-allison approved these changes

2022-08-05 06:18 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anim/ViewAnimation.kt
> +            interpolator = when (type) {
style: This would be more readable with a variable + without the apply. 
The code block fees too large to scope.

2022-08-07 16:52 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anim/ViewAnimation.kt
> +    private fun translateAnimation(fromXValue: Float, toXValue: Float, fromYValue: Float, toYValue: Float) =
Thanks a lot.
You're right.

2022-08-07 16:52 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anim/ViewAnimation.kt
> +            interpolator = when (type) {
Fine. Removed the last commit. Should be good now

2022-08-08 05:37 UTC, lukstbit approved these changes

2022-08-08 05:39 UTC, merged