NF: simplify Time and improve lint message
ankidroid/Anki-Android pull request #11970
Opened 2022-08-02 22:30 UTC by Arthur-Milchior

Lint message around system time was not update when Time was moved to Collection
from TimeManager.

In my opinion, code is more readable if you just uses `Time.s` and `Time.ms`
than `TimeManager.Time.intTime`. On top of that, it becomes clear when time is
returned in seconds.

This way, most developer can just write code without needing to have any
knowledge about time management, unless they have a test that requires to
manipulate it explicitly.

As a next step, we may try to figure out whether methods that require Time
really need them. Most seems to directly gets `TimeManager.time` in all
call. But this seems less important than lint (this one is mandatory) and
simplifying our abstraction for new contributors.

2022-08-03 08:55 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                    mLastRenderStart = Time
@Arthur-Milchior have you kept variable name with first letter caps for any specific reason?

2022-08-03 14:42 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                    mLastRenderStart = Time
Oops, no. I wanted to rename currentTime method, I didn't saw there was variables too

2022-08-03 23:29 UTC, Arthur-Milchior commented
This one was strange. Backticks in Description made the test failed. For some reason, Kotlin would just not print two backticks. However if the string has a single backtick, it works. No idea why. Not important for this case either

2022-08-05 12:29 UTC, ShridharGoel commented
Conflicts need to be resolved.

2022-08-07 15:05 UTC, Arthur-Milchior commented
Done

2022-08-08 08:54 UTC, lukstbit requested changes

2022-08-08 08:54 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java
> +            long CurrentTime = TimeManager.INSTANCE.getTime().intTime();
Why the change to uppercase and why not replace `TimeManager.INSTANCE.getTime().intTime()` with the new method?

2022-08-08 15:17 UTC, divyansh-dxn commented
Nothing more from me, just the question lukstbit asked.

2022-08-23 22:26 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java
> +            long CurrentTime = TimeManager.INSTANCE.getTime().intTime();
No idea for the cap.
I would assume the absence of correction was that I mostly automated it for kotlin, but I may be wrong.

2022-08-23 23:42 UTC, david-allison requested changes
These should be functions, not properties.

> Prefer a property over a function when the underlying algorithm:
> * does not throw
> * is cheap to calculate (or cached on the first run)
> * **returns the same result over invocations if the object state hasn't changed**

https://kotlinlang.org/docs/coding-conventions.html#functions-vs-properties

Emphasis mine

----
non-blocking, for discussion

* We're moving away from Anki desktop's naming
* We should `typealias` the return values

2022-08-24 01:07 UTC, Arthur-Milchior commented
What kind of typealias do you want? milisecond and Second?

2022-08-26 15:14 UTC, david-allison commented
`EpochS` and `EpochMs` seems sensible

2022-11-30 20:37 UTC, closed without merging