[GSoC] Add `Use V16 backend` (persistent) and `Enable CSV importer` dev options
ankidroid/Anki-Android pull request #11977
Opened 2022-08-05 18:00 UTC by BrayanDSO

## Purpose / Description
- The V16 pref is useful to testing in case the dev forgot to set `legacy_schema=false` on `local.properties` while not having to re-enable every time the app is reopened.
- The CSV importer dev option will be useful while it is being developed + the new schema isn't used by default on the app

## Fixes
A tiny bit of #6772

## Approach
On the commits

## How Has This Been Tested?

Emulator SDK 25

[untitled.webm](https://user-images.githubusercontent.com/69634269/183134062-0567319e-86a3-4bf0-ad59-d61f066f9273.webm)

(not so sure why Android Studio recording is getting dark, maybe I should buy a faster computer)

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-05 22:10 UTC, dae commented
Would it be worth moving these into the Advanced section so alpha testers can try too? https://github.com/ankidroid/Anki-Android/pull/11808#issuecomment-1202816430

2022-08-05 22:16 UTC, dae commented
Also, I don't really see the benefit of the separate csv pref. The csv importer will require v16 to be enabled, so it's going to be hidden by default even without a separate preference.

2022-08-06 00:19 UTC, BrayanDSO commented
> Would it be worth moving these into the Advanced section so alpha testers can try too? [#11808 (comment)](https://github.com/ankidroid/Anki-Android/pull/11808#issuecomment-1202816430)

I'm particularly quite in favor of releasing it as an Advanced preference. If I get a green light of the maintainers, I'll do it.

> Also, I don't really see the benefit of the separate csv pref. The csv importer will require v16 to be enabled, so it's going to be hidden by default even without a separate preference.

I actually prefer enabling the CSV importer if the new backend is active instead of a preference as well. Good to hear that another person find this reasonable too. Better than taking the "safe" approach (the CSV importer screen is self contained, so shouldn't break the rest of the app).

2022-08-06 21:24 UTC, BrayanDSO commented
Noticed that I should refactor some of the file selection code, so I'll keep this PR only for the V16 option

2022-08-07 15:47 UTC, Arthur-Milchior commented
you have a merge conflict

2022-08-07 15:57 UTC, Arthur-Milchior approved these changes

2022-08-07 15:57 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
> +        val useV16TemporarilyPref = requirePreference<Preference>(getString(R.string.pref_rust_backend_key)).apply {
Would you mind renaming to `pref_rust_temp_backend_key`, for the sake of similarity with `pref_persistent_rust_backend_key`. Not a big deal but still good to avoid a slight confusion riskwhen reading code

2022-08-08 06:58 UTC, lukstbit commented
I reviewed the changes and I'm questioning if we really need the temporary backend change. The permanent backend change preference has several advantages:
- offers the user full control about the backend choice
- it has a status indicator which shows what backend implementation we use

The temporary backend change:
- it doesn't have a a status indicator to show what backend implementation we use. See below why this might be a problem
- it doesn't work as its description mentions as Android doesn't really have the concept of "app close"(apps just come and go as the user does he's thing). Example:
 _I'm clicking the temporary backend preference -> I'm being taken to the DeckPicker -> I press BACK -> reopen the app x minutes later._

At this point did I close the app? I would say yes, and others might as well
Is the backend reverted ? No, it isn't.

At this point, although I left the app, the backend wasn't changed back. Can I see/realize this by looking at the preferences? No, as the temporary backend change doesn't offer any visual feedback. 

So the text would need to be changed to mention that the user has to kill the app from the task manager. At this point, if we require the user to go to the task manager and kill the app, we might as well just use the permanent backend change. 

Also, I really think that changing any of these preferences should bring up a confirmation dialog. When I was first checking the preferences, as I scrolled, I accidentally touched the permanent backend change preference and I enabled it. A simple misplaced touch shouldn't enable such preferences.

2022-08-08 07:21 UTC, dae commented
Fair points about visibility and confirmation. I think the reason David originally added the temporary toggle is out of concern that the user might turn it on, find it crashes the app on startup due to some code path/condition we didn't anticipate, and then will be unable to revert to the old setting. That's a legitimate concern while this code is so fresh, and I actually encountered such a situation today - if the collection has the current deck id stored incorrectly as a string (which happened with old AnkiDroid versions IIRC), the new schema path currently crashes AnkiDroid on startup.

2022-08-08 11:48 UTC, BrayanDSO commented
Added confirmation and visual indication if temporary pref is enabled or not

https://user-images.githubusercontent.com/69634269/183411279-358e6efd-14ef-4423-a6be-58205b7b88ad.mp4

2022-08-08 21:02 UTC, BrayanDSO commented
Okey dokey. No temporary preference it is. Make your backups and have fun testing, people! Cheers.

2022-08-09 15:43 UTC, david-allison requested changes
I don't think this should be offered as an option. 

The preference existed specifically for developers to test v16 only if the app was built under DEBUG. 

The preference specifically reverts after an 'app close' to allow the app to be usable in the case of catastrophic failure.

Instead of implementing this, we should focus on getting the new backend stable, and then switching to it permanently. 

If we do not feel that the new code is stable enough to offer to users, users should not be able to enable it.

2022-08-09 16:26 UTC, BrayanDSO commented
FWIW, my opinion is:
1. The temporary preference should be removed or kept only at "Developer options"
    - It is useful only for developers. Non-devs shouldn't/wouldn't use it. And it's only useful for the specific case that something makes the app crash before the developer can go disable the setting. Even if that happens, the developer should just fix the problem or clear the app data.
2. We should have a persistent option (at least on "Developer options")
     - It's more useful than the temporary preference, as it isn't necessary to do the burden of re-enabling the preference on every app startup
     - It's still useful for motivated alpha users that want to test it can do it be enabling Dev options on the About screen secret
3. Advanced X Developer options
    - I lean more to putting it on "Advanced"
    - I don't want it, or any experimental preference, to go to the play store release versions once we are able to, but I still want more people to be able to test it. Many of the bugs that appear on `main` are only discovered by chance. The same will happen with the V16 changes, so we need more testers before releasing it to the general public.
    - So, I'm personally in favor of putting it, along with any other experimental preference, as a alpha-only Advanced option.
    - I don't know how AnkiDroid's beta program works, as the app releases were already blocked when I started to contribute, so I can't give an opinion if beta users should be able or not to use it.

I'm strong on the first two points. I've stated my opinion about the third point, but I'm happy with any path taken.

2022-08-10 13:02 UTC, mikehardy commented
I still want this. There's a chicken-and-egg problem of getting enough testing to feel that it's stable enough to offer to "users", and "users" is not just two classes ("people with debug builds from source" and "people using alphas / betas / etc"). There is at the moment one specific group of people - our alpha users - that are installing manually a thing labeled "alpha" and if they want to test, they would specifically tap a thing that warns them about the danger. At that point it could eat the family pet and we have clean conscience I think.

In the meantime a subset of these people (v3 scheduler requesters) is motivated to try it, and we'll start getting some real usage of the backend. Realistically, I think this will net us probably 4-5 testers max, 2 alpha / non-developer v3 people, and 2-3 of "us" (people that regular test / PR things)

Sync works, review works, undo works, those are the basic use cases. And for problems, we've got Damien and myself ready for fixes.

My vision for duration of v3 stabilization is just a couple weeks and I'm happy to re-hide this if there are problems and/or if we're about to go to beta, if for some reason it takes a lot longer or it becomes a problem.

Where to put it? Definitely "advanced" but it can't be in "developer options" since that is for debug-builds only

Note that I have still not reviewed the text - when I do so I'll make sure it says something about "There is a chance this could corrupt your installation completely, requiring app uninstall and deletion of /sdcard/AnkiDroid, and has a chance of propagating corruption via sync to ankiweb. We welcome the testing, but please make sure you have a valid non-AnkiWeb backup." (or similar)

2022-08-10 15:23 UTC, BrayanDSO commented
I'm happy with any text. When you do review it, if text changes are required, please suggest the one you'd like 🙏

2022-08-11 14:39 UTC, mikehardy commented
With a warning like that, I believe any "reasonable person" (yes, that's vague, but it's a US legal standard at least, I'm being sincere) can agree that if something goes wrong, *you were warned...*...

2022-08-11 14:44 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
> +        MaterialDialog(requireContext()).show {
I just want to give a quick shout to @ShridharGoel for muscling through the material dialogs update - Shridhar you've done a few cross-cutting changes, which are mostly still pending! That's on the rest of us though and hopefully we get the other ones in. Also thanks to @lukstbit for nailing down the loose ends on it. Unrelated to the change here but that update deserves some more gratitude I think. Cheers

2022-08-11 14:48 UTC, mikehardy commented
maintainer note: doing i18n sync *prior* to merging this, so the string change from this does not mix with unrelated translations (a real string review velocity killer...)

2022-08-11 16:45 UTC, merged