NF: replace Long by CardId
ankidroid/Anki-Android pull request #11985
Opened 2022-08-07 15:09 UTC by Arthur-Milchior

CardId is defined in cards.py upstream. Since Cards.java may not be converted,
Consts.kt may be the better place for it.

Values were found by searching "cid: Long" and "ardId: Long".

2022-08-10 10:00 UTC, lukstbit requested changes
Tests are failing

2022-08-14 12:40 UTC, david-allison requested changes
Doesn't compile

```
> Task :AnkiDroid:ktlintMainSourceSetCheck FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt:1:1 File must end with a newline (\n)
```

2022-08-16 04:45 UTC, lukstbit commented
@Arthur-Milchior Everything looks ok but there's an unrelated change in `Consts` which makes lint fail.

2022-08-16 12:21 UTC, lukstbit approved these changes

2022-08-16 13:08 UTC, david-allison approved these changes

2022-08-16 13:08 UTC, merged