Cleanup in CardBrowser Part 1
ankidroid/Anki-Android pull request #11998
Opened 2022-08-10 14:13 UTC by oyeraghib

## Purpose / Description
cleanup: replace TextUtils for checking empty or null 

## Learning (optional, can help others)
https://stackoverflow.com/a/59321544/9062752

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-10 15:59 UTC, lukstbit requested changes
You have failing tests.

2022-08-10 15:59 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            if (mTempSearchQuery!!.isNotEmpty() || mSearchTerms.isNotEmpty()) {
`!TextUtils.isEmpty(mTempSearchQuery)` and `mTempSearchQuery!!.isNotEmpty()` are not equivalent, `mTempSearchQuery` is assigned null several lines above.

2022-08-10 21:05 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            if (mTempSearchQuery!!.isNotEmpty() || mSearchTerms.isNotEmpty()) {
Using `!isNullOrEmpty()` should do the trick

2022-08-11 10:12 UTC, oyeraghib commented
Tests are failing here but passing on local

2022-08-11 16:48 UTC, lukstbit approved these changes

2022-08-18 20:41 UTC, mikehardy approved these changes
nice, thank you!

2022-08-18 20:42 UTC, merged