Make possible to commit hunks again on Kotlin
ankidroid/Anki-Android pull request #11995
Opened 2022-08-10 10:08 UTC by BrayanDSO

## Fixes
Fixes #9390

## Approach
Replaced the old runKtlint() code with the one generated by `./gradlew addKtlintFormatGitPreCommitHook`

for reference, see https://github.com/JLLeitschuh/ktlint-gradle#additional-helper-tasks, and for the implementation, https://github.com/JLLeitschuh/ktlint-gradle/blob/master/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/GitHook.kt

 The idea came from https://github.com/ankidroid/Anki-Android/issues/9390#issuecomment-950353851

## How Has This Been Tested?

https://user-images.githubusercontent.com/69634269/183875558-937f7fc7-a4a6-4178-ad20-cb597f11de31.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-10 10:11 UTC, BrayanDSO commented
> Perhaps if we used one of the plugins (this is most popular: https://github.com/jlleitschuh/ktlint-gradle#additional-helper-tasks) and just integrated it's pre-commit hook (and IDEA style file generation) we'd get editor support for style in Android Studio, and we'd get formatting as a pre-commit hook, and everyone else already using that plugin will have solved all the problems we're cutting our teeth on?

> I'd like to see a Proof of concept that killed our pre-commit hook and tried integrating that plugin with it's IDEA style + commit hook)

This PR is only for fixing the pre-commit problem. As I found very reasonable to try using the plugin IDEA style as well and the repo's kotlin code style barely exists, I'll peel it to a separate issue.

2022-08-13 10:40 UTC, david-allison requested changes
This committed `// don't commit this hunk` when committed via the IDE. 

Did I need to run any any commands to test this other than checking out the PR?

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/AsyncLayer.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/AsyncLayer.kt b/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/AsyncLayer.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/AsyncLayer.kt	(revision a1115f2951583c49969a0be2db3cbd7b70f5b497)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/AsyncLayer.kt	(date 1660387130493)
@@ -79,16 +79,17 @@
 
 /** Extension which allows a return value from a transaction */
 fun <T> DB.executeInTransactionReturn(task: () -> T): T {
-    // Ported from code which started the transaction outside the try..finally
     database.beginTransaction()
     try {
-        val ret = task()
+            val ret = task()
         if (database.inTransaction()) {
             try {
                 database.setTransactionSuccessful()
             } catch (e: Exception) {
                 // Unsure if this can happen - copied the structure from endTransaction()
                 Timber.w(e)
+
+                // don't commit this hunk
             }
         } else {
             Timber.w("Not in a transaction. Cannot mark transaction successful.")
```

2022-08-13 10:49 UTC, lukstbit commented
@david-allison I cleaned and then rebuilt the project before testing it.

2022-08-13 10:59 UTC, BrayanDSO commented
AFAIK, git hooks only works if they are on the ".git/hooks" directory, and AnkiDroid uses gradle to make a copy of "./pre-commit" on it. So yeah, rebuild the app again.

2022-08-13 14:44 UTC, david-allison approved these changes
This leaves a small bug in which you can now perform an empty commit (if committing a change the linter fully reverts)

But I don't mind, this is a massive improvement. Thank you!

2022-08-13 14:45 UTC, merged