Migrate db.java to kotlin
ankidroid/Anki-Android pull request #12016
Opened 2022-08-13 02:36 UTC by Arthur-Milchior

Due to typing issue, it's based on top of #12011 and #12013.

2022-08-13 07:34 UTC, dae commented
I seem to recall finding DB.java difficult to convert to Kotlin when I tried it, so well done in pushing this through. :-)

2022-08-13 07:51 UTC, lukstbit requested changes
Looks ok with two small issues.

2022-08-13 07:51 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
> + * *
Small format issue: align the `*` and `*/`.

2022-08-13 07:51 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
> +    init {
@KotlinCleanup("remove init by directly initializing the properties")

2022-08-13 14:50 UTC, david-allison requested changes
This contains unrelated changes, please only have the two commits

2022-08-13 22:26 UTC, Arthur-Milchior commented
It was ready for review. Being clear that the the only interesting commit is the migration itself. 
I'd have make a PR with only those two commits, but it wouldn't compile without the dependencies being taken care of first.

If I put it as "draft", I'd assume nobody would review it. Which is clearly not what I wanted, since it could be reviewed independently

2022-08-14 05:15 UTC, lukstbit approved these changes

2022-08-14 12:39 UTC, david-allison approved these changes

2022-08-14 12:39 UTC, merged