fixed: deck search not scrolling to current deck in statistics
ankidroid/Anki-Android pull request #12030
Opened 2022-08-15 08:30 UTC by yshubham8419

## Purpose / Description
fix: deck search not scrolling to current deck in statistics

## Fixes
Fixes #9935 

## Approach
1.Passed the current deck Id as argument to the dialog fragment
2.found the position of the deck in recycler view
3.Scroll to that position

## How Has This Been Tested?
Tested on my personal device.

2022-08-19 03:00 UTC, mikehardy approved these changes
seems reasonable, thank you!

2022-08-23 21:19 UTC, david-allison requested changes
Can you use `DeckId` instead of `Long` for the type. It should  already exist as a `typealias`

2022-08-23 21:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +    }
```suggestion
    private fun getPositionOfDeck(did: Long, decks: List<SelectableDeck>)
        = decks.sorted().indexOfFirst { it.deckId == did }
```

2022-08-23 21:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +        for (item in decks.sorted()) {
Explain in a comment why `sorted()` is needed (both 'all decks' and the individual ids I presume)

I'd prefer that the sorted (immutable) list from `DecksArrayAdapter` was provided to this function so we don't need to be concerned with the implementation details of other classes

2022-08-27 11:33 UTC, yshubham8419 commented
@david-allison thanks for the hints

2022-08-27 11:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +    }
My suggestion was not applied here. Was there a reason?

2022-08-28 10:25 UTC, david-allison approved these changes
Looks great, thanks!

2022-08-28 23:42 UTC, merged

2022-08-28 23:43 UTC, david-allison commented
Done, congrats!!!

If you're on [our Discord](https://discord.gg/qjzcRTx), send me a PM and I'll add some roles