Add a lint rule to use string resources for preferences keys + extract deck options/filtered deck options keys
ankidroid/Anki-Android pull request #12032
Opened 2022-08-15 13:19 UTC by BrayanDSO

## Fixes
Fixes #10423

## Approach
For the key extractions, just used a regex to replace the strings for keys, searching for `android:(?:key|dependency)="([^@].*?)"`

## How Has This Been Tested?

Ran lint and the unit tests created

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-15 13:40 UTC, david-allison requested changes
Looks great! Minor nitpicks

2022-08-15 13:40 UTC, david-allison commented on AnkiDroid/src/main/res/values/preferences.xml
> +    <string name="deck_options_deckConf_key">deckConf</string>
Could we move these to a separate file

2022-08-15 13:40 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/HardcodedPreferenceKey.kt
> +        val ID = HardcodedPreferenceKey::class.simpleName!!
Use a constant, we don't want this changing if the class is renamed

2022-08-15 13:40 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/HardcodedPreferenceKey.kt
> +            context.report(ISSUE, element, context.getLocation(attrNode), DESCRIPTION)
Love seeing the location here

2022-08-17 15:14 UTC, lukstbit approved these changes
Everything looks ok, but please add your copyright to the two new xml files.

2022-08-17 20:16 UTC, david-allison approved these changes

2022-08-18 04:15 UTC, merged