[DRAFT] feat: App Intro
ankidroid/Anki-Android pull request #12033
Opened 2022-08-15 23:30 UTC by david-allison

## Pull Request template

## Purpose / Description
If we add an app introduction, we can use this for the 'restore' operation in scoped storage, which allows a user to select a 'safe, but slow' folder to restore from.

The UX of this is not ideal on the Android side, so sadly a 'safe' folder can't be the default. In addition to this, it is significantly slower to perform disk operations, which leads to a large number of complaints about slow sync times.

## How Has This Been Tested?
Emulator on Android 12

* New collection - Get Started
* New collection - Sync from AnkiWeb
* New collection - Sync from AnkiWeb (if already logged in)
* Upgrade
* App Intro is not shown twice

## Learning (optional, can help others)
* DeckPicker needs a lot of work - we can't use app results well as the collection init code still is used by the lifecycle

<img width="384" alt="Screenshot 2022-08-16 at 00 27 48" src="https://user-images.githubusercontent.com/62114487/184743143-a332835c-9392-4644-bfcf-19fb09d1b580.png">
<img width="377" alt="Screenshot 2022-08-16 at 00 27 55" src="https://user-images.githubusercontent.com/62114487/184743141-b5ae0cc6-4f51-4882-874b-4c4f1d5c8d48.png">

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-15 23:31 UTC, david-allison commented
This is a draft:

* Unit tests need fixes
* I probably want to abstract out the `showedActivityFailedScreen` code which was copied from the original PR

2022-08-16 21:31 UTC, Arthur-Milchior commented
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/02-strings.xml:455: Error: Duplicate string value "Get started", used in fab_tutorial_title, intro_get_started. Use android:inputType or android:capitalize to treat these as the same and avoid string duplication. [DuplicateCrowdInStrings from com.ichi2.anki:lint-rules]
    <string name="intro_get_started">Get Started</string>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/19-onboarding.xml:3: Duplicates value in intro_get_started. Add a comment attribute on both strings to explain this duplication (case varies, but you can use android:inputType or android:capitalize in the presentation)

Is a real lint error

2022-08-19 16:52 UTC, lukstbit commented
@david-allison Just a note that the introduction layout breaks for phones in landscape. I'll be reviewing this tomorrow morning if no one beats me to it.

2022-08-20 09:01 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +        // If we don't kill the process, the backup is not "done" and reopening the app show the same message.
I didn't get what you mean here, can you explain in more detail?

2022-08-20 09:06 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +    // This method has been taken from AnkiActivity.
Conversation from original PR: https://github.com/ankidroid/Anki-Android/pull/9130/files#r834337943

2022-08-20 09:09 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +            deckPicker.putExtra("syncFromLogin", true)
Use constant for `syncFromLogin`.

2022-08-20 10:38 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> + *  Copyright (c) 2022 David Allison <davidallisongithub@gmail.com>
This file has two copyright blocks.

2022-08-20 11:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +    // This method has been taken from AnkiActivity.
I'll soft-block this on Kotlin conversion of `AnkiActivity` (this is probably going to be a mistake, and we have alternatives if AnkiActivity takes too long to convert)

2022-08-21 10:04 UTC, lukstbit requested changes
I reviewed the code and checked the functionality and this is an approving comment with the notice that the layout still breaks for phones in landscape. I don't know if you want to address this here or get this PR merged to unblock other work(in this case I think a TODO or cleanup should be placed in the code).

2022-08-21 14:15 UTC, BrayanDSO commented
If anyone asks how this looks on a tablet (Emulator SDK 25, Nexus 9, 2048x1536):
![image](https://user-images.githubusercontent.com/69634269/185795251-d7ffd373-1dc4-47d9-a2ab-c848bf6f09b8.png)

2022-08-21 14:19 UTC, BrayanDSO requested changes
one question: Why the status bar is being hidden? Seems unusual and it may show a black bar on phones with a notch/camera hole (it does on my phone at least)

![Screenshot_20220821-080438_AnkiDroid](https://user-images.githubusercontent.com/69634269/185795466-24b690f3-a9ff-47a6-a77b-a44256ecf347.png)

2022-08-21 14:19 UTC, BrayanDSO commented on AnkiDroid/src/main/res/layout/introduction_layout.xml
> +            android:textSize="18dp"
always sp for text
```suggestion
            android:textSize="18sp"
```

2022-08-21 14:19 UTC, BrayanDSO commented on AnkiDroid/src/main/res/layout/introduction_layout.xml
> +            android:textSize="18dp"
```suggestion
            android:textSize="18sp"
```

2022-08-22 21:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +    // This method has been taken from AnkiActivity.
Blocked on https://github.com/ankidroid/Anki-Android/pull/12132

2022-08-23 20:18 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +    // This method has been taken from AnkiActivity.
Done

2022-08-24 22:19 UTC, mikehardy commented on AnkiDroid/src/main/res/layout/introduction_layout.xml
> +            android:textSize="18dp"
Huh. TIL... https://material.io/design/layout/pixel-density.html#pixel-density-on-android

2022-08-24 22:28 UTC, mikehardy requested changes
- tiny method nitpick
- one wording bikeshed (opinion weakly held)
- a desire for the orientation on IntroActivity to be locked, I dropped the necessary manifest xml in a comment (I think)

This looks great

2022-08-24 22:28 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="intro_short_ankidroid_explanation">AnkiDroid\'s scheduler saves time by strengthening your weakest memories and preserving your strongest</string>
I already like this a lot. Could merge as is.

As a bikeshed, I like a subtle nod to the general name of the system, subtle credit to it for the scheduler, and using the chars to add an idea of *what* is being scheduled. What do you think?

```suggestion
    <string name="intro_short_ankidroid_explanation">Anki\'s card scheduler saves time by strengthening your weakest memories and preserving your strongest</string>
```

2022-08-24 22:28 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        if (!hasShowedAppIntro()) {
```suggestion
        if (!hasShownAppIntro()) {
```

because English

2022-08-24 22:28 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    private fun hasShowedAppIntro(): Boolean {
```suggestion
    private fun hasShownAppIntro(): Boolean {
```

2022-08-26 11:15 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/introduction/SetupCollectionFragment.kt
> +        }
What is the purpose of this? Do you want to change the "Study less" title for something else?

2022-08-26 11:22 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
> +            get(LoginActivity::class.java),
keeping a trailing comma on here (TIL this [is allowed in Kotlin](https://kotlinlang.org/docs/coding-conventions.html#trailing-commas)) is great. I wouldn't mind a PR to enable this in ktlint if it were possible

cleaner diffs on multiple PRs that touch this at same time

2022-08-26 11:25 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/introduction/SetupCollectionFragment.kt
> +        }
Just a guess but I bet that was part of the original app introduction system, where a generic "intro slide displayer" could show arbitrary content. Just a hypothesis

2022-08-26 11:26 UTC, mikehardy approved these changes
I have nothing I would change, this looks great
It fixes landscape orientation, and I cannot think of things to bikeshed even ;-)

2022-08-26 12:29 UTC, BrayanDSO commented
I won't consider this blocking as progress is my priority, but I'd like to notice that the background still doesn't shown on emulator SDK 25 (not a special SDK version, it's just my default emulator). 

Up to the implementer if they want to investigate it now or leave it as a TODO

![image](https://user-images.githubusercontent.com/69634269/186903210-b7cb7a9a-c6a0-4c33-aaff-09d367c4364a.png)

2022-08-26 13:01 UTC, david-allison commented
I've added a TODO, I can't install API 25 right now due to dodgy internet. 

Let's get this merged and circle back to it

2022-08-26 13:02 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/introduction/SetupCollectionFragment.kt
> +        }
Removed, thanks

2022-08-26 13:03 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
> +            get(LoginActivity::class.java),
https://github.com/ankidroid/Anki-Android/issues/12185

2022-08-26 13:27 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/introduction/SetupCollectionFragment.kt
> +/****************************************************************************************
Two copyright headers

2022-08-26 13:35 UTC, mikehardy requested changes
Wait! The comment on API25 got me curious since I have one laying around and I also have our minSdk (21) laying around. Checked them. Repro on 25 - not a huge deal, but 21 crashes, have not investigated too deeply yet but upstream repo does not have bugs logged that fit?

```
E/AndroidRuntime( 3051): android.view.InflateException: Binary XML file line #36: Error inflating class ImageView
E/AndroidRuntime( 3051): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
E/AndroidRuntime( 3051): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
E/AndroidRuntime( 3051): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
E/AndroidRuntime( 3051): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
E/AndroidRuntime( 3051): 	at com.ichi2.anki.introduction.SetupCollectionFragment.onCreateView(SetupCollectionFragment.kt:64)
E/AndroidRuntime( 3051): 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
E/AndroidRuntime( 3051): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
E/AndroidRuntime( 3051): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
E/AndroidRuntime( 3051): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
E/AndroidRuntime( 3051): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1808)
E/AndroidRuntime( 3051): 	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1720)
E/AndroidRuntime( 3051): 	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
E/AndroidRuntime( 3051): 	at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:249)
E/AndroidRuntime( 3051): 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
E/AndroidRuntime( 3051): 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
E/AndroidRuntime( 3051): 	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
E/AndroidRuntime( 3051): 	at android.view.View.measure(View.java:17430)
E/AndroidRuntime( 3051): 	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:811)
E/AndroidRuntime( 3051): 	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:632)
E/AndroidRuntime( 3051): 	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:452)
E/AndroidRuntime( 3051): 	at androidx.constraintlayout.core.widgets.analyzer.Direct.solveVerticalMatchConstraint(Direct.java:750)
E/AndroidRuntime( 3051): 	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:503)
E/AndroidRuntime( 3051): 	at androidx.constraintlayout.core.widgets.analyzer.Direct.solvingPass(Direct.java:224)
E/AndroidRuntime( 3051): 	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:693)
E/AndroidRuntime( 3051): 	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:160)
E/AndroidRuntime( 3051): 	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:291)
E/AndroidRuntime( 3051): 	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:120)
E/AndroidRuntime( 3051): 	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1594)
E/AndroidRuntime( 3051): 	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1708)
E/AndroidRuntime( 3051): 	at android.view.View.measure(View.java:17430)
E/AndroidRuntime( 3051): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
E/AndroidRuntime( 3051): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
E/AndroidRuntime( 3051): 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
E/AndroidRuntime( 3051): 	at android.view.View.measure(View.java:17430)
E/AndroidRuntime( 3051): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
E/AndroidRuntime( 3051): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
E/AndroidRuntime( 3051): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
E/AndroidRuntime( 3051): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
E/AndroidRuntime( 3051): 	at android.view.View.measure(View.java:17430)
E/AndroidRuntime( 3051): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
E/AndroidRuntime( 3051): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
E/AndroidRuntime( 3051): 	at android.view.View.measure(View.java:17430)
E/AndroidRuntime( 3051): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
E/AndroidRuntime( 3051): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
E/AndroidRuntime( 3051): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
E/AndroidRuntime( 3051): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
E/AndroidRuntime( 3051): 	at android.view.View.measure(View.java:17430)
E/AndroidRuntime( 3051): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
E/AndroidRuntime( 3051): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
E/AndroidRuntime( 3051): 	at com.android.internal.policy.impl

```

(side note, I really miss our full emu matrix from Travis, I've got to do at least a min/max here I think)

2022-08-26 13:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/introduction/SetupCollectionFragment.kt
> +/****************************************************************************************
It feels like something's wrong with my IDE, I'm definitely not touching these

2022-08-26 14:37 UTC, david-allison commented
Tracked to the lines in `ankidroid_logo`

```
        <aapt:attr name="android:fillColor">
            <gradient
                android:startY="98.7147"
                android:startX="79.9001"
                android:endY="151.12"
                android:endX="170.6686"
                android:type="linear">
                <item android:offset="0" android:color="#FF29B6F6"/>
                <item android:offset="1" android:color="#FF0288D1"/>
            </gradient>
        </aapt:attr>
```

2022-08-26 14:46 UTC, david-allison commented
@mikehardy I'm going to be unable to test on the proper API spread until Sunday. I've fixed this for API 21, but don't know if API 22 etc... will also need this new drawable. Is it feasible to test on an API spread beforehand to get this merged?

API 21 screenshot
<img width="432" alt="Screenshot 2022-08-26 at 15 40 07" src="https://user-images.githubusercontent.com/62114487/186931230-8ee6f124-0762-4969-a421-4761737a057c.png">

2022-08-26 15:05 UTC, mikehardy commented
Sure! On it

```
mike@bistromath:~/work/AnkiDroid/Anki-Android-Upstream (main) % alias |grep andemu
alias andemu21-google_apis='/home/mike/Android/Sdk/emulator/emulator -no-boot-anim @TestingAVD_API-21_TAG-GAPI &'
alias andemu22-google_apis='/home/mike/Android/Sdk/emulator/emulator -no-boot-anim @TestingAVD_API-22_TAG-GAPI &'
alias andemu23-google_apis='/home/mike/Android/Sdk/emulator/emulator -no-boot-anim @TestingAVD_API-23_TAG-GAPI &'
alias andemu24-google_apis='/home/mike/Android/Sdk/emulator/emulator -no-boot-anim @TestingAVD_API-24_TAG-GAPI &'
alias andemu25-google_apis='/home/mike/Android/Sdk/emulator/emulator -no-boot-anim @TestingAVD_API-25_TAG-GAPI &'
alias andemu25_chromeos='/home/mike/Android/Sdk/emulator-chromeos/emulator -no-boot-anim @Chromebook_Pixel_2015_beta_API_25 &'
alias andemu26-google_apis_playstore='/home/mike/Android/Sdk/emulator/emulator -no-boot-anim @TestingAVD_API_26_TAG_PLAY &'
alias andemu27-google_apis_playstore='/home/mike/Android/Sdk/emulator/emulator -no-boot-anim @TestingAVD_API_27_TAG_PLAY &'
alias andemu28-google_apis_playstore='/home/mike/Android/Sdk/emulator/emulator -no-boot-anim @TestingAVD_API_28_TAG_PLAY &'
alias andemu29-google_apis_playstore='/home/mike/Android/Sdk/emulator/emulator -no-boot-anim @TestingAVD &'
alias andemu30-google_apis_playstore='/home/mike/Android/Sdk/emulator/emulator -no-boot-anim @TestingAVD_API-30_TAG-PLAY &'
alias andemu31-google_apis_playstore='/home/mike/Android/Sdk/emulator/emulator -no-boot-anim @TestingAVD_API-31_TAG-PLAY &'
alias andemuTablet='/home/mike/Android/Sdk/emulator/emulator -no-boot-anim @Pixel_C_API_30_GAPI &'
``

:iphone: :iphone: :iphone: :iphone: :iphone: 

Something went wrong though: 

```
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt: (116, 78): Unresolved reference: getWebViewErrorMessage

```

2022-08-26 15:13 UTC, david-allison commented
Conflict with `AnkiDroidApp` migration

2022-08-26 16:59 UTC, mikehardy commented
Crash:
- That fixed on API21
- Fails on API22 API23 (same layout inflater business)
- Starts working on API24+

When I move the drawable from v22 to v24 (making v22 empty so can be removed) then all APIs work

Shading:
- API21/22 have shading
- API23/25/26/27/28 no gradient shading 
- API29+ (Android 10+) has shading


I'm okay with a TODO on the layout portrait lock and shading issue as those can be cleaned up off critical path

@david-allison --> I can force push --force-with-lease my change to the drawable vFolder - but don't want to collide with you, just let me know

2022-08-26 17:18 UTC, david-allison commented
> Crash:
> - That fixed on API21
> - Fails on API22 API23 (same layout inflater business)
> - Starts working on API24+
> 
> When I move the drawable from v22 to v24 (making v22 empty so can be removed) then all APIs work
> 
> Shading (tested with drawable in v24):
> 
> - API21/22 have shading
> - API23/25/26/27/28 no gradient shading 
> - API29+ (Android 10+) has shading
> 
> 
> I'm okay with a TODO on the layout portrait lock and shading issue as those can be cleaned up off critical path
> 
> @david-allison --> I can force push --force-with-lease my change to the drawable vFolder - but don't want to collide with you, just let me know

I'm happy with a force push. No changes on my side

2022-08-26 18:05 UTC, mikehardy approved these changes
This will work everywhere without crashing now

2022-08-26 18:08 UTC, mikehardy commented
Fix style on App Intro screen (gradient in lower APIs, unlock landscape + fix layout)

The new App Intro screen has a problem with layout where it does not look quite right on landscape. For this reason the Activity definition in AndroidManifest.xml has been locked to portrait. The layout should be more responsive and rotation unlocked

The new App Intro screen looks great on higher APIs (29+)
On APIs 23-28 the shading is missing and it is a bit boring compared to API29+
Ideally the gradient could be in place in all APIs.

2022-08-26 18:12 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/introduction/SetupCollectionFragment.kt
> +/****************************************************************************************
I see this as well, when fixed I suppose it'll clear Brayan's requested changes then this is ready for an i18n-sync/merge/i18n-sync cycle

2022-08-27 04:39 UTC, merged

2022-08-27 04:40 UTC, mikehardy commented
I'm merging this with a strict focus on progress, but there were some display/design issues noted, everyone interested please go for it on those, but this will hopefully keep scoped storage migration critical path clear

Also it had strings and I had just cleared those out, so it takes advantage of a clear "strings sync" window

Cheers