refactor: Convert AbstractSchedTest to Kotlin
ankidroid/Anki-Android pull request #12043
Opened 2022-08-16 20:48 UTC by david-allison

2022-08-17 05:19 UTC, lukstbit requested changes
Looks ok with two extra cleanups.

2022-08-17 05:19 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.kt
> +        init {
@KotlinCleanup("remove init and initialize the properties directly")

2022-08-17 05:19 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.kt
> +        val hasMatch = decks.all().stream().anyMatch { x: Deck -> name == x.getString("name") }
@KotlinCleanup("Replace stream() with kotlin collection operators")

2022-08-17 16:05 UTC, lukstbit approved these changes

2022-08-18 19:00 UTC, mikehardy approved these changes
nice - looks good
passes local regression check, let's go

2022-08-18 19:00 UTC, merged