refactor: Convert NotificationChannelTest to Kotlin
ankidroid/Anki-Android pull request #12042
Opened 2022-08-16 20:30 UTC by david-allison

Difficult one. First time we needed `assertNotNull` (which was caught via a lint check).

There was difficulty in implementing `junit5` (known TODO on the Google Side), so I used the `kotlin-test` `assertNotNull`

2022-08-16 21:29 UTC, BrayanDSO requested changes

2022-08-16 21:29 UTC, BrayanDSO commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/NotificationChannelTest.kt
> +    private var mManager: NotificationManager? = null
cleanup: lateinit

2022-08-16 21:29 UTC, BrayanDSO commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/NotificationChannelTest.kt
> +        Assert.assertEquals(
import `Assert.asserEquals` back

2022-08-16 21:29 UTC, BrayanDSO commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/NotificationChannelTest.kt
> +@KotlinCleanup("JUnit 5")
I can't tell what this cleanup wants exactly. Could you explain it on the code?

2022-08-17 17:49 UTC, BrayanDSO approved these changes

2022-08-19 02:33 UTC, mikehardy approved these changes
LGTM - passes local re-integration test

2022-08-19 02:33 UTC, merged