Replacing more Long by types
ankidroid/Anki-Android pull request #12050
Opened 2022-08-17 04:52 UTC by Arthur-Milchior

Also renaming dcid to DeckConfId which is more Kotlin-like

Those IDs were not found by the initial simple search. For those, I had to look at context to verify which type is appropriate

2022-08-17 04:56 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +    private fun getModelIdFromUri(uri: Uri, col: Collection): NoteTypeId {
Recent desktop versions use "NotetypeId" instead of "NoteTypeId", FWIW.

2022-08-17 05:37 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +    private fun getModelIdFromUri(uri: Uri, col: Collection): NoteTypeId {
Corrected, thanks.
What's the rationale if I can ask. Especially compared to DeckConfigId?

Even if, to be perfectly honest, while I believe that replacing Long improve readability, I have almost no opinion regarding whether "notetype" is a single word or two words

2022-08-17 05:49 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +    private fun getModelIdFromUri(uri: Uri, col: Collection): NoteTypeId {
Mainly for readability - "deck config" reads easily as two words, but "note type" feels a bit more awkward, and it's less clear whether we're talking about a particular's note's type, or the notetype itself. Not a big deal, just thought it better to be consistent.

2022-08-19 02:55 UTC, mikehardy commented
batch of conflicts on this one

2022-08-20 23:32 UTC, BrayanDSO requested changes
Only some fixes on `NF: introduce collection of NoteTypeId`

2022-08-20 23:32 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
> +            val NotetypeId = mModelIds!![position]
keep the old name here

2022-08-20 23:32 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
> +            noteOpenIntent.putExtra("NotetypeId", NotetypeId)
undo this change

2022-08-20 23:32 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +        val collectionModel = collection.models.get(NotetypeId)
undo these

2022-08-20 23:32 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.kt
> +                    intent.putExtra("NotetypeId", findModelIdByName(modelName))
ditto

2022-08-21 19:17 UTC, Arthur-Milchior commented
Thanks. I added a constant for intent key so that at least it'll be certain to always be consistent

2022-08-21 21:59 UTC, david-allison commented
Lint is failing

2022-08-24 20:32 UTC, BrayanDSO approved these changes

2022-08-24 20:33 UTC, BrayanDSO commented
And... there are new conflicts

2022-08-26 06:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
> +    constructor(col: Collection, id: CardId) {
This changes the definition of a `CardId` to an unvalidated ID.

I don't agree, but don't feel strongly. 

If we are making this change, can we define it in a separate commit

2022-08-26 06:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +    fun getNote(id: NoteId): Note {
not relevant to the commit

2022-08-26 06:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/SimpleCardQueue.kt
> +    fun add(id: CardId) {
this commit can be squashed into the other `CardId` one

2022-08-26 06:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    const val DEFAULT_DECK_ID: DeckId = 1
not valid for commit

2022-08-26 06:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
> +    override fun didsForConf(conf: DeckConfig): List<DeckId> =
not valid for commit

2022-08-26 11:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
> +    constructor(col: Collection, id: CardId) {
I fear I don't understand. What is an unvalidated ID? I assume it's an id where we don't actually know whether the ID is in the CARDS table of the database.
Which beg the question: where would this invalid ID come from? If you're right, the same problem with typing occurs with at least one function that call this constructor, up to some function that generates an id.

The trouble is that the only function that I can imagine that generates an ID, the ids come either:
* from current time (for card creation, in which case we don't use this constructor, and the id is valid since this is by definition a card we are adding in the db)
* from the CARDS table. Indeed, only CARDS, REVLOG and deletion references card id. Revlog can have ID of deleted cards, that's true, but as far as I can tell, we never get card from id that comes from revlog or deletion. And while it can be theoretically possible that a we keep somewhere in memory a card id while another process delete the card, I don't believe it's especially worth considering the question since this can occur everywhere and in this case, the type CardID becomes useless

2022-08-26 11:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +                var noteID: NoteId = -1
On this one, I'll admit that if we want the type to imply that the ID is valid, this line should be reverted.
Or modified to use either a nullable type or something different than the negative value to indicate the id is not yet set

I personally believes that for all intent and purpose this represents a note id, since, as long as it's -1, essentially, no action is done

2022-08-27 14:21 UTC, mikehardy commented
Another conflict, and may take yet one more when JSON object nullability refactor goes in

2023-02-02 15:37 UTC, closed without merging