[GSoC] Add option to import text files
ankidroid/Anki-Android pull request #12072
Opened 2022-08-18 14:15 UTC by BrayanDSO

## Purpose / Description
This just adds the option, not the actual text/csv import implementation. which will be the next PR

As the CSV importer will require the new backend, the options is only shown if the new backend is enabled

## Approach
On the commits

## How Has This Been Tested?

1. Enable the new backend
2. Tap the three dot menu on the Deck picker > Import
3. Choose "Text file (.txt, .csv)
4. Select a text file
5. See if the "CSV importer is not implemented yet" is shown

![image](https://user-images.githubusercontent.com/69634269/185417119-c7add351-da1b-4221-b6aa-c9f624f2ab8a.png)

![image](https://user-images.githubusercontent.com/69634269/185417176-c72ebc9f-b8ee-438f-9523-22c919e65c7d.png)

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-18 15:05 UTC, krmanik requested changes

2022-08-18 15:05 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
> +                return ImportResult.fromErrorString("CSV importer isn't implemented yet")
The string should be extracted to resources.

2022-08-18 15:18 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
> +                return ImportResult.fromErrorString("CSV importer isn't implemented yet")
This is a temporary warning. I don't expect it to be here more than 1 week, so I hardcoded it to spare the translators' work. 

If there is a problem with this, I'd rather join this commit with the actual CSV importer PR. Whatever it's better for the reviewers.

2022-08-18 15:33 UTC, krmanik approved these changes

2022-08-18 19:41 UTC, BrayanDSO commented
"Waiting for Feedback" because I've noticed that I have more work to do on `ImportUtils` than I expected

2022-08-18 20:55 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
> +                return ImportResult.fromErrorString("CSV importer isn't implemented yet")
I think this 

> This is a temporary warning. I don't expect it to be here more than 1 week, so I hardcoded it to spare the translators' work.

is reasonable but also really appreciate Mani looking out for the strings

works for me

2022-08-18 21:25 UTC, BrayanDSO commented
ImportUtils.kt could be way more cleaner, as it seems that it has got change on top of change and became somewhat messy. And there is https://github.com/ankidroid/Anki-Android/issues/12079, which is especially relevant. 

Currently my top priority is pushing the actual CSV importer, so I don't know when/if I am going to refactor ImportUtils

2022-08-20 05:21 UTC, lukstbit approved these changes

2022-08-20 05:28 UTC, merged