refactor: Convert Models to Kotlin
ankidroid/Anki-Android pull request #12082
Opened 2022-08-19 05:15 UTC by david-allison

2022-08-25 12:14 UTC, lukstbit requested changes
Some cleanups...

2022-08-25 12:14 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/Models.kt
> +        val b = arrayOfNulls<String>(nbFields)
@KotlinCleanup("Array(size) {initialize here} instead of arrayOfNulls")

2022-08-25 12:14 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/Models.kt
> +        const val DEFAULT_MODEL = (
@KotlinCleanup("Use """ """ for this properties and maybe @Language("json")")

2022-08-25 12:14 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/Models.kt
> +        fun newTemplate(name: String?): JSONObject {
@KotlinCleanup("direct return and use scope function")

2022-08-26 03:19 UTC, Arthur-Milchior commented
You've got a conflict

2022-08-26 06:34 UTC, lukstbit approved these changes

2022-08-26 11:42 UTC, mikehardy approved these changes
Huge one - pending re-run of CI-alike checks local

2022-08-26 12:05 UTC, merged