refactor: Convert ImportTest to Kotlin
ankidroid/Anki-Android pull request #12102
Opened 2022-08-19 12:26 UTC by david-allison

2022-08-20 22:49 UTC, BrayanDSO requested changes
for the other reviewers: the CSV tests are going away soon, so no need to create cleanups on them

2022-08-20 22:49 UTC, BrayanDSO commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.kt
> -import static org.junit.Assume.assumeThat;
import these back

2022-08-20 22:49 UTC, BrayanDSO commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.kt
> +        Assume.assumeThat(defaultLegacySchema, Matchers.`is`(true))
`is` -> equalTo

2022-08-20 22:49 UTC, BrayanDSO commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.kt
> +    private var mTestCol: Collection? = null
lateinit

2022-08-20 22:49 UTC, BrayanDSO commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.kt
> +class ImportTest : InstrumentedTest() {
IDE lint

2022-08-21 11:29 UTC, BrayanDSO approved these changes

2022-08-21 12:30 UTC, lukstbit approved these changes

2022-08-21 12:42 UTC, merged