New schema fixes
ankidroid/Anki-Android pull request #12108
Opened 2022-08-20 02:53 UTC by dae

2022-08-20 16:08 UTC, mikehardy requested changes
LGreatTM - just a duplicate import

2022-08-20 16:08 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +import anki.search.searchNode
duplicate import? Also, I assume we get the anki packages semi-auto from the Anki-Android-Backend? I mean, I'm 99% sure on that but my knowledge in this whole area is still thin so I'm figuring can't hurt to confirm

2022-08-20 16:09 UTC, mikehardy commented
Also if you rebase on main the emulator tests should be non-flaky now, here's some android fun for you #12113 - in particular the root cause https://www.rainforestqa.com/blog/hunting-race-condition-in-android-10-emulator

2022-08-20 20:47 UTC, david-allison approved these changes
LGTM, the `postExecute` does the same as the `onProgress` in `CardBrowser` so it's fine to skip this

2022-08-20 20:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +import anki.search.searchNode
One is a class, one is a method

2022-08-20 22:15 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +import anki.search.searchNode
Oh, where is the :facepalm: reaction when I need it? Thanks

2022-08-20 22:15 UTC, mikehardy approved these changes

2022-08-20 22:15 UTC, merged

2022-08-21 03:44 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +import anki.search.searchNode
> Also, I assume we get the anki packages semi-auto from the Anki-Android-Backend?

Yes, they're generated from .proto files in the desktop repo