Removed method name from translatable string "import_error_copy_file_to_cache"
ankidroid/Anki-Android pull request #12109
Opened 2022-08-20 08:04 UTC by pratyaksh1610

## Purpose / Description
Removed method name "copyFileToCache()" from translatable string "import_error_copy_file_to_cache"

## Fixes
Fixes #12080

## Approach
Removed the method name from the file.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-20 08:06 UTC, pratyaksh1610 commented
Previous PR got closed due to merge conflicts.

2022-08-20 08:08 UTC, pratyaksh1610 commented
@lukstbit @mikehardy Please review.
Thanks.

2022-08-21 04:33 UTC, pratyaksh1610 commented
@david-allison Please review.
Thanks.

2022-08-22 05:48 UTC, pratyaksh1610 commented
@lukstbit Is there any change required or is it ready for merge ?

2022-08-22 15:07 UTC, lukstbit requested changes

2022-08-22 15:10 UTC, lukstbit commented
@pratyaksh1610 Please don't spam reviewers, that's not going to make your pull request to be merged faster. Also please don't close your pull requests when they get conflicts(and then make another pull request), instead you should rebase on main and fix the conflicts then force push to your branch. This is a workflow most open source project require.

2022-08-22 16:56 UTC, pratyaksh1610 commented
@lukstbit This is my first PR, So sorry for the inconvenience caused.

2022-08-22 21:25 UTC, BrayanDSO requested changes
Hello there. Thanks a lot for your contribution. As lukstbit has said, please don't spam any of the reviewers. We are all volunteers here and we will eventually get to your PR when the time is right, so please be patient.

I've requested some changes. Feel free to ask anything if needed.

2022-08-22 21:25 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="import_error_copy_file_to_cache">Failed to cache file(possibly out of storage space)</string>
```suggestion
    <string name="import_error_copy_to_cache">Failed to cache file (possibly out of storage space)</string>
```

2022-08-22 21:25 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="import_error_copy_file_to_cache">Failed to cache file(possibly out of storage space)</string>
Add a space before the parenthesis. The string name needs to be changed in order to trigger a retranslation.

2022-08-23 05:24 UTC, lukstbit commented
@pratyaksh1610 No harm done :+1:

2022-08-23 06:45 UTC, pratyaksh1610 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="import_error_copy_file_to_cache">Failed to cache file(possibly out of storage space)</string>
@BrayanDSO Done

2022-08-23 07:41 UTC, pratyaksh1610 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="import_error_copy_file_to_cache">Failed to cache file(possibly out of storage space)</string>
Added the space and refactored the string name, is this the required change ?

2022-08-23 09:27 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="import_error_copy_file_to_cache">Failed to cache file(possibly out of storage space)</string>
Almost. It's only necessary to change the string name on the `values/` folder. The translation infrastructure takes care of changing it on all the others values folders (e.g. values-ja, values-zn, etc).

So I'd like you to keep only the string change on `values` and drop the others

2022-08-23 09:50 UTC, pratyaksh1610 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="import_error_copy_file_to_cache">Failed to cache file(possibly out of storage space)</string>
Done.

2022-08-23 11:36 UTC, BrayanDSO approved these changes
LGTM! Thanks for the contribution 😁

2022-08-23 13:55 UTC, mikehardy commented
Maintainer note: do not merge this until an i18n sync is done *before* this merge, so it is easy to review.
If you merge this before a translations PR goes through then you will have real translation work (which frequently contains errors that are hard to see) mixed in with an ocean of changes in every language brought about by this

2022-08-23 14:39 UTC, merged