refactor: Convert Utils to Kotlin
ankidroid/Anki-Android pull request #12106
Opened 2022-08-19 20:56 UTC by david-allison

This one was horrible, lots of work + incorrect automatic conversions. Please review carefully

2022-08-25 10:02 UTC, lukstbit requested changes

2022-08-25 10:02 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/Utils.kt
> +        val fonts: MutableList<AnkiFont> = ArrayList(fontsCount)
@KotlinCleanup("See if code in for loop an be improved")

2022-08-26 01:50 UTC, lukstbit commented
@david-allison Got a conflict...

2022-08-26 07:38 UTC, lukstbit approved these changes

2022-08-26 11:47 UTC, mikehardy approved these changes
Another massive one, amazing
pending local CI re-run as these Kotlin ones are in my merge train

2022-08-26 12:47 UTC, mikehardy commented
@david-allison good to go except merge-train local CI run just caught this one from Models cross-contamination:

```

> Task :AnkiDroid:compilePlayDebugKotlin FAILED
e: /home/mike/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/src/main/java/com/ichi2/libanki/Models.kt: (470, 46): Type mismatch: inferred type is Array<String?> but Array<String> was expected
e: /home/mike/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/src/main/java/com/ichi2/libanki/Models.kt: (470, 59): Type mismatch: inferred type is Array<String> but Array<String?> was expected
e: /home/mike/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/src/main/java/com/ichi2/libanki/Models.kt: (626, 43): Type mismatch: inferred type is String? but String was expected

> Task :AnkiDroid:compilePlayReleaseKotlin FAILED
e: /home/mike/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/src/main/java/com/ichi2/libanki/Models.kt: (470, 46): Type mismatch: inferred type is Array<String?> but Array<String> was expected
e: /home/mike/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/src/main/java/com/ichi2/libanki/Models.kt: (470, 59): Type mismatch: inferred type is Array<String> but Array<String?> was expected
e: /home/mike/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/src/main/java/com/ichi2/libanki/Models.kt: (626, 43): Type mismatch: inferred type is String? but String was expected

```

2022-08-26 18:42 UTC, mikehardy commented
This one has nullability cross-contamination from the Utils convertion:

> e: /home/mike/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt: (526, 67): Type mismatch: inferred type is Array<String?> but Array<String> was expected

I had a look at fixing it but the variable is defined as an array of nulls to start, not sure how far we want to go on forcing that or where the best place is. Could be as simple as a cast since it's a test and if it blows up in testing, great, but I didn't feel confident

2022-08-26 19:11 UTC, david-allison commented
Re-pushed

2022-08-26 23:00 UTC, mikehardy commented
Clean!

2022-08-26 23:00 UTC, merged