refactor: Convert TextNoteExporterTest to Kotlin
ankidroid/Anki-Android pull request #12118
Opened 2022-08-20 20:26 UTC by david-allison

2022-08-21 16:42 UTC, BrayanDSO requested changes

2022-08-21 16:42 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/libanki/TextNoteExporterTest.kt
> +class TextNoteExporterTest(
lateinit wherever possible

IDE-lint

2022-08-22 05:23 UTC, lukstbit approved these changes

2022-08-22 09:27 UTC, BrayanDSO approved these changes

2022-08-22 09:32 UTC, merged