refactor: Convert AnkiActivity to Kotlin
ankidroid/Anki-Android pull request #12115
Opened 2022-08-20 19:12 UTC by david-allison

Please note the changes to DeckPickerTest and SchedTest

Now .col will throw instead of returning null

2022-08-20 21:21 UTC, BrayanDSO requested changes

2022-08-20 21:21 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +    fun restartActivity() {
I dislike this method. `recreate()` tends to the best choice as it keeps the `savedInstanceState` and delivers a betters restart. 

New contributors with low experience with Android may end up using this method without knowing that this cleans the activity entirely, as I did before.

This needs investigation if the current uses indeed want to clear the previous `savedInstanceState` and if it should be kept, it would be nice to add a javadoc to it and maybe renaming it.

2022-08-20 21:21 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        super.startActivity(intent)
Here I'd add a cleanup to do the same I did with `finish()`, which is "Remove deprecation and make it call startActivityWithAnimation(DEFAULT)"

Reasons (from #11699)
> The sole purpose of the deprecation is to force to use finishWithAnimation our finishWithoutAnimation, methods which create the possibility of disabling the animations on E-ink devices
> But this didn't block uses of requireActivity().finish() or (x as Activity).finish(), some animations would show regardless of the E-ink setting
> Removing the deprecation and setting it to use the default animation fixes the problem while keeping finish() default behavior

And new contributors won't have to stress why `startActivity` is deprecated and have to use startActivityWithoutAnimation even if they didn't want to disable the animation

2022-08-20 21:21 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +    var customTabActivityHelper: CustomTabActivityHelper? = null
cleanup: lateinit

2022-08-20 21:21 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +    /** The name of the parent class (Reviewer)  */
Remove "(Reviewer)" from the comment

2022-08-20 21:21 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +                resources.getString(R.string.no_browser_notification) + url,
How strings are joined on RTL languages? Idk if this string should have a `%s` placeholder or not. Better to ask one of the translators

2022-08-20 21:21 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +            showThemedToast(
cleanup: Replace with a snackbar

2022-08-20 21:21 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +    private val colorScheme: Int
This is only useful for custom tabs, so I'd add a cleanup to rename it

2022-08-20 21:50 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        if (mPreviousTheme !== Themes.currentTheme) {
Presumably we should have used `.equals` in the Java. Agreed

2022-08-20 22:24 UTC, BrayanDSO requested changes
More one

2022-08-20 22:24 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +            ActivityTransitionAnimation.slide(activity, UP)
Cleanup to fix this. UP -> FADE

2022-08-21 04:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +            ActivityTransitionAnimation.slide(activity, UP)
This is a functional change, I'd rather extract this to an issue rather than have `@KotlinCleanup`s which can cause functional changes to the code

2022-08-21 04:15 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +            ActivityTransitionAnimation.slide(activity, UP)
https://github.com/ankidroid/Anki-Android/issues/12123

2022-08-21 08:58 UTC, BrayanDSO approved these changes

2022-08-21 16:01 UTC, lukstbit approved these changes
Ok!

2022-08-21 16:13 UTC, merged