refactor: Convert Sound to Kotlin
ankidroid/Anki-Android pull request #12110
Opened 2022-08-20 12:10 UTC by david-allison

2022-08-24 15:08 UTC, lukstbit requested changes

2022-08-24 15:08 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
> +class Sound {
I think we should add(here and for other big classes being migrated):

`@KotlinCleanup("improve kotlin code where ever possible")`

as an alternative to littering the class with a lot of smaller cleanups.

2022-08-24 15:08 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
> +import com.ichi2.compat.CompatHelper.Companion.compat
style: keep the CompatHelper import as in the original code, using `compat.something()` is not that great.

Same requests for:
```
import com.ichi2.anki.ReadText.stopTts
import com.ichi2.utils.DisplayUtils.getDisplayDimensions
import net.ankiweb.rsdroid.BackendFactory.defaultLegacySchema
```

2022-08-24 16:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
> +class Sound {
I prefer the opposite - I use `@KotlinCleanup("lots to do")` to imply that the annotation should be broken down into more targeted annotations.

It's good to list acceptance criteria associated with an issue. Having a fixed number of easy cleanups is better than one general "complete everything" cleanup, as it's harder to determine when this cleanup annotation is completed.

2022-08-25 08:04 UTC, lukstbit requested changes
I've added some of the cleanups that I had in mind when first reviewing, everything looks ok.

2022-08-25 08:04 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
> +            return false
@KotlinCleanup("simplify code with ?. ")

2022-08-25 08:04 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
> +                mMediaPlayer!!.setDataSource(
@KotlinCleanup("simplify with scope function on mediaPlayer ")

2022-08-26 01:44 UTC, lukstbit approved these changes

2022-08-26 16:06 UTC, BrayanDSO commented
This one will need a rebase into main to replace "AnkiDroidApp.getInstance()"

2022-08-26 21:28 UTC, BrayanDSO approved these changes

2022-08-26 21:29 UTC, merged