Fix a few issues with Custom sync server
ankidroid/Anki-Android pull request #12112
Opened 2022-08-20 14:23 UTC by oakkitten

There's a few issues with custom sync servers. One of the settings is not consistent with the other and with what Anki expects; when using backend, custom sync servers and some other settings are not respected. Please see the commits for the list of changes. 

## Approach

One of the preferences was upgraded to match Anki. Environmental variables are set to make the backend use the custom servers. A new argument `syncMedia` is added to a few backend sync methods.

I tried splitting the first commit into several, but the result was just harder to understand, so. A few identifiers could have better names, but I opted for a smaller diff & consistency with surrounding identifiers.

One preference screen was slightly changed to include summaries.

<img src=https://user-images.githubusercontent.com/1710718/185750183-d3e26b82-b0b7-4035-b8db-38f9184421b8.png width=300>

## How Has This Been Tested?

Added a test for preference upgrade. Otherwise, tested on my Xiaomi MI A2 against Anki and ankisyncd.

## Remaining issues

There's a few issues at the end of the day.

* The custom sync URL preferences must have `/` at the end of the URLs. Most people consider `http://foo` to be equivalent to `http://foo/`, so they might omit the slash at the end. The legacy code will correctly append the `/` when adding suffixes, that is `http://foo/sync` will become `http://foo/sync/meta`. However the backend does that via a [simple string concatenation](https://github.com/ankitects/anki/blob/576b141e2b4e8a092f3cbf71ac57f6eb84531a9d/rslib/src/sync/http_client.rs#L280). This can lead to some quite obscure errors, e.g. inputting `http://192.168.1.90:8080` yields a dialog saying 

  > A network error occurred.
  >             
  > Error details: ⁨builder error: invalid port number⁩ 

  I did not try to work around this behavior, because this is also what Anki does, and if it is going to be fixed, it should be fixed in the backend. Alternatively, we could add a note that the user probably wants to have a `/` on the end of the stuff they put into these settings. @dae thoughts? Also you might be interested in other issues listed here.

* You could before, and you still can, specify either, or both, or none of the two sync servers—collection and media. If a server is not specified, the default AnkiWeb server, collection or media, is used instead. This is not reflected in the preferences UI, and is especially confusing considering there's a single switch that disables both settings. Also, the preference that opens the preference screen only says the name of the collection sync server in its summary, showing blank if it is not set.

  I suggest the following preference structure (Bold = title, regular = summary):

  * **Custom sync servers** *(opens screen)*
    Collection: http://192.168.1.90:8080/sync/
    Media: default

    * As an alternative to using AnkiWeb, you can use your own servers for synchronization between devices. You can specify either of the servers, or both; if not set, the default AnkiWeb server will be used instead. For example, you could use the sync server built into Anki to synchronize the collection while you are off the grid, and AnkiWeb to synchronize media while online. Learn more *(tappable)*.

    * **Collection sync server | *(switch)***
      http://192.168.1.90:8080/sync/

    * **Media sync server | *(switch)***
      Not set
  
  Here, the items on both sides of | are separately tappable:

  * If the sync server is not specified, tapping both the title and the switch will open a text input dialog, and if the user specifies a valid URL, it is set, and the switch turns on.

  * If the sync server is specified:

    * Tapping on the server will open a text input dialog. If user specifies a valid URL, it is set, and the switch stays or turns on; if user clears the input, URL is unset, and the switch turns off.

    * Tapping on the switch turns using this server on or off, without removing the URL.

  This description looks complicated but I think this would be easy to operate.

* If using Rust backend, In the case of server error, a dialog window is shown, saying
  
  > AnkiWeb encountered a problem. Please try again in a few minutes.

  As a custom sync server is probably not AnkiWeb, this might be misleading. Also, it would help if the actual error was shown.

* Also, if using Rust backend, in the case when the server is not accessible (or no internet), you will see

  > Please check your internet connection.
  >
  > Error details: ⁨error sending request for url (): error trying to connect: dns error: failed to lookup address information: No address associated with hostname⁩ 

  It would be helpful if this showed the actual URL.

* If using Rust backend, in the case of a successful collection sync and a failing media sync, you will see both the success snackbar and an error dialog. This is very confusing. The legacy error is not perfect but still much better than that.

  Also, there's no confirmation of media sync finishing.

* Not really an issue but if using Rust backend, there's no “You are offline. Try anyway” snackbar.

There are many more small issues that are rather obvious so I'm not mentioning them, however none of them seem to be preventing the sync from actually working.

P.S. For some reason AnkiDroid seems to be not migrating (upgrading) preferences unless app version changes. So if this is merged and a version bump doesn't follow soon after, the devs that use the Sync url preference will see its value vanish.

## Checklist

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-20 16:23 UTC, mikehardy commented
Wow, you are moving the entire mountain in order get custom sync servers working, and improving every single thing for everyone on the way. It is amazing to watch.

In general I'm going to go with "implementor's choice" in most cases where there is a really motivated person, so your thoughts on preferences / splitting collection+media sync server control seem fine, but do realize that long text strings increase translation burden. For technical writing and user interface I always fight my innate verbosity and remember: as brief as humanly possible, and prescriptive is best.

I asked for @dae review here in general and will give it a look shortly I hope

2022-08-20 20:58 UTC, david-allison requested changes
One commit to drop, the rest looks great, thanks!

2022-08-20 20:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/web/CustomSyncServer.kt
> +        val preferences = AnkiDroidApp.getSharedPrefs(context)
style (optional): We will always call this inside `if (!BackendFactory.defaultLegacySchema) {` it would make sense to move this as a guard clause

2022-08-20 20:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomSyncServerSettingsFragment.kt
> +                    .setTitle(R.string.custom_sync_server_collection_url_invalid)
(unconfirmed) I believe this commit will remove all of the translations (we push the english and pull the other languages).

Therefore I'd like it dropped unless it's done for anything other than a rename

2022-08-20 22:54 UTC, mikehardy commented on AnkiDroid/src/main/res/values/10-preferences.xml
> -    <string name="custom_sync_server_base_url_invalid">Sync url invalid</string>
David is correct on translations, if you remove a key from `/values/*.xml` it will drop all translations in all languages, which is perhaps lost work. In this case I contend it is lost work as the actual strings we want are the same. If a key is close to the right name and has translations, best to just add a comment explaining the key's purpose but leave it, so the translations are maintained

2022-08-21 03:16 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +                null -> handleNormalSync(deckPicker, auth, syncMedia)
This may come down to personal preference, but if you had syncMedia() check the preference directly, it could just return at the top of the function if media is disabled, and you wouldn't have to pass it through to all these routines.

2022-08-21 03:16 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +            if (syncMedia) handleMediaSync(deckPicker, auth)
@david-allison what's the policy on braces on if statements in Kotlin? The linter doesn't seem to be flagging the lack of them.

https://github.com/ankidroid/Anki-Android/commit/e2e07068ccb46f2e520fb4a31455d9756474bfaf

(personally, I prefer them)

2022-08-21 03:35 UTC, dae commented
Your approach looks good.

> The custom sync URL preferences must have / at the end of the URLs
> I did not try to work around this behavior, because this is also what Anki does, and if it is going to be fixed, it should be fixed in the backend. 

A PR that adds a trailing / if missing would be welcome.

> As a custom sync server is probably not AnkiWeb, this might be misleading

The strings are created in network.rs. I'd be happy to accept a PR that uses an alternative wording when those env vars are set.

> It would be helpful if this showed the actual URL.

It's redacted because it may contain auth info in the query string, and the URL is not useful for the typical use case of people syncing with AnkiWeb.

> If using Rust backend, in the case of a successful collection sync and a failing media sync, you will see both the success snackbar and an error dialog. This is very confusing. The legacy error is not perfect but still much better than that.

> Also, there's no confirmation of media sync finishing.

There's certainly room for improvement here. My knowledge of Android's UI is limited, so you are probably more qualified to address these issues.

2022-08-21 04:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +            if (syncMedia) handleMediaSync(deckPicker, auth)
Moved to https://github.com/ankidroid/Anki-Android/issues/12122

The Kotlin migration often automatically introduced guard clauses without brackets, and I personally like these.

https://github.com/ankidroid/Anki-Android/blob/d38434ce703f49b50f93ab1f084a5eb594461192/AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AutomaticAnswer.kt#L135-L141

In this case I, agree and would prefer NOT to have unbracketed `if` statements as shown here, but this does not match the Android Style Guide

> Braces are not required for when branches and if expressions which have no more than one else branch **and which fit on a single line.**

https://developer.android.com/kotlin/style-guide#braces

----

side-note: I don't want to move back to a world where code reviews are focusing on lintable style issues. I'd like this formalised and/or added to the lint depending on the outcome.

2022-08-22 18:01 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/web/CustomSyncServer.kt
> +        val preferences = AnkiDroidApp.getSharedPrefs(context)
If this is optional I'd want to keep this as is. As I said elsewhere, I prefer not to use maybe-methods if I can reasonably avoid them. Guard clauses IMO should be not used for control flow. They should prevent a method, that is meant to be run, from running in case of state where it's not possible, think null arguments or destroyed activities.

Keeping the `if` outside also helps with refactoring the outside code. Maybe the outside code will get refactored so that it is only run when using legacy backend, then it's easy to see that you can just remove the entire `if`.

2022-08-22 18:03 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomSyncServerSettingsFragment.kt
> +                    .setTitle(R.string.custom_sync_server_collection_url_invalid)
Dropped this change. While it's a minor thing and not really important, especially considering how the translations themselves are on point despite the key, I wonder if you can rename the strings keys on Crowdin itself? I suppose people do want that from time to time

2022-08-22 18:05 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +                null -> handleNormalSync(deckPicker, auth, syncMedia)
I opted for passing that as an argument as it's less intrusive; I am not making any functions depend on state more. Also, from a brief glance, it looked to me like that code can be refactored in such a way that media sync will only be called in a single place, so I hope this will take care of itself.

2022-08-22 18:09 UTC, oakkitten commented
Refactored to remove the offending commit.

> Wow, you are moving the entire mountain in order get custom sync servers working

Well, I am actually using the sync servers 😛

> but do realize that long text strings increase translation burden. For technical writing and user interface I always fight my innate verbosity and remember: as brief as humanly possible, and prescriptive is best.

I think in some places verbosity is okay, and this might be one of those places. Verbose explanations in preference screens is not uncommon in Android. It's okay to just point people to the manual but the people should understand the gist of it so they can decide if they indeed want to look at the manual or not. Besides, there's room in this screen!

The translation burden is a concern but then I like to translate text like that. It might look long but it often requires little effort. This is just text. With short phrases you need to investigate what exactly it means to translate it right. Sometimes picking the right title can be hard! And you need to think about how to make it short. And you need to make sure that the terms you pick are consistent with the rest of the app.

Anyway, this is something extra. I wasn't going to do this as a part of this PR.

> A PR that adds a trailing / if missing would be welcome.

One day I might try to touch a little Rust, but that day is not today 😔

2022-08-22 21:20 UTC, david-allison approved these changes

2022-08-24 00:36 UTC, mikehardy approved these changes
This looks great on full read, and I remember you noted because of the preference upgrade there can be some inconsistency for non-release users if the version doesn't bump after merge so I'll do a release with this as soon as the merge has settled. Thanks for this!

2022-08-24 00:37 UTC, merged

2022-08-24 02:10 UTC, mikehardy commented
Scrounged up a few more PRs I could merge but I'm releasing this now (essentially as fast as possible) to trigger the prefs upgrade for all