feat: improve deck creation/rename UX
ankidroid/Anki-Android pull request #12139
Opened 2022-08-23 22:35 UTC by david-allison

## Purpose / Description

When a deck was created, there was little visual feedback on success/failure:

* When a deck was invalid, the dialog just closed
* When a deck was created/renamed, the user was not informed

## Fixes
* Fixes #10528
* Solves part of #11668: deck creation

## Approach
* toasts are used when a success occurs, 
* validation on the form is used if a deck couldn't be created
  * The OK button is greyed out 
  * A message is shown if the name is used

## How Has This Been Tested?

<img width="382" alt="Screenshot 2022-08-23 at 23 15 19" src="https://user-images.githubusercontent.com/62114487/186277910-6e97131b-0839-4a24-a6c2-7112bddc8aa9.png">
<img width="381" alt="Screenshot 2022-08-23 at 23 15 11" src="https://user-images.githubusercontent.com/62114487/186277917-126f364d-7119-4f50-af06-ec6843789a88.png">
<img width="352" alt="Screenshot 2022-08-23 at 23 14 58" src="https://user-images.githubusercontent.com/62114487/186277920-b6a30472-70cf-437a-b76b-f50b24105af5.png">

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-23 22:43 UTC, BrayanDSO commented
I'd rather use Snackbars instead of toasts, as per Material design [recommendation](https://material.io/components/snackbars/android#using-snackbars)

> Android also provides a [Toast](https://developer.android.com/reference/android/widget/Toast.html) class with a similar API that can be used for displaying system-level notifications. Generally, snackbars are the preferred mechanism for displaying feedback messages to users, as they can be displayed in the context of the UI where the action occurred. Reserve Toast for cases where this cannot be done.

And on a future PR, or on this if you want to, an Undo button can be added

2022-08-23 22:52 UTC, david-allison commented
I'd like a sample pattern of how the Dialog -> Snackbar relationship should be defined first.

Maybe via `Dialog.ownerActivity`?

2022-08-23 22:59 UTC, BrayanDSO commented
> I'd like a sample pattern of how the Dialog -> Snackbar relationship should be defined first.

> Maybe via Dialog.ownerActivity, but this would cause code complexity if not handled carefully

Seems fine. Maybe `context` parameter could be replaced with activity, as activity serves as context too

2022-08-23 23:02 UTC, david-allison commented
As defined currently, we have no `Activity`

2022-08-23 23:05 UTC, BrayanDSO commented
WDYM? That AnkiDroid activities are all `AppCompatActivity`/`FragmentActivity` under the hood?

2022-08-23 23:09 UTC, david-allison commented
We're in `CreateDeckDialog`, which has no specific reference to an `Activity`, only a `Context`

2022-08-23 23:12 UTC, BrayanDSO commented
Oh, sorry, misunderstood that.  

My suggestion is to replace the `context: Context` parameter, with a `activity: Activity` parameter.

So we can use `activity` as context where `context` was used + use snackbars with `activity.showSnackbar()`

2022-08-23 23:23 UTC, david-allison commented
I'll hold off on this and will add a TODO. This is because I'm unfamiliar with the standard Android pattern for handling this situation and architecturally I'd like to think about other options,

We may not want a hard dependency on `Activity` in the constructor

1. I'd like to move to a fragment-based app at some point in the future,
2. It holds a hard reference to an Activity context instead of allowing for an `Application` context
3. Requires a change from `Context` -> `Activity` in `DeckPickerFloatingActionMenu`, which ins't the end of the world

2022-08-23 23:47 UTC, BrayanDSO approved these changes

2022-08-24 13:22 UTC, lukstbit requested changes
The changes don't take in consideration creating sub decks with a name already in use. Scenario:

_I have decks A and B => create a sub deck in A named B => receive error the deck name is already used although it should permit the usage of the name_ 

Another scenario:

_I have deck A with sub deck A1 => attempt to create again a sub deck in A named A1 => no error visual indicator in the dialog that A1 already exists + also get toast with deck created_

2022-08-24 16:58 UTC, david-allison commented
Good catch, will add the missing unit tests now a bug's been found.

2022-08-28 13:47 UTC, lukstbit requested changes
App behaves as expected, tests pass.
Just the small issue with the extensions placement and LGTM.

2022-08-28 13:47 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/MaterialDialogUtils.kt
> +var MaterialDialog.input
We already have a file containing extensions on MaterialDialog(although its name is not so great): https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/java/com/ichi2/utils/MaterialBuilderUtil.kt

I think this extensions should go there.

2022-08-28 15:42 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/MaterialDialogUtils.kt
> +var MaterialDialog.input
I would like these to be test-only functions, would you want the class renamed?

2022-08-28 15:56 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/MaterialDialogUtils.kt
> +var MaterialDialog.input
Sorry, I completely missed, when I reviewed, that this class is in the test source sets. So I'm happy as it is now, the name is perfectly fine.

2022-08-28 15:57 UTC, lukstbit approved these changes
Looks good!

2022-08-31 19:58 UTC, BrayanDSO approved these changes
LGTM. Pending solving conflicts

2022-08-31 22:05 UTC, merged

2022-08-31 22:09 UTC, BrayanDSO commented
Good bot, I didn't pay attention to the label. Though it's under my impression that you only warned me after I merged it. I'll be more careful next time

2022-09-01 05:27 UTC, krmanik commented
I think it is bug, there needs to do some check if PR merged or not. This needs to fix. I will update it.