refactor: KotlinCleanup - DeckPicker
ankidroid/Anki-Android pull request #12137
Opened 2022-08-23 20:07 UTC by david-allison

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-23 22:11 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        @KotlinCleanup("Material Progress Dialog")
There isn't a Material Progress Dialog. Perhaps for the same reason they deprecated progress dialog on Android O.

> This class was deprecated in API level 26. ProgressDialog is a modal dialog, which prevents the user from interacting with the app. Instead of using this class, you should use a progress indicator like ProgressBar, which can be embedded in your app's UI. Alternatively, you can use a notification to inform the user of the task's progress.

(https://developer.android.com/reference/android/app/ProgressDialog)

We use ProgressDialog on other places of the code and would be nice to have an issue to discuss what to do on each case

2022-08-23 22:33 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        @KotlinCleanup("Material Progress Dialog")
I think we're going to need a general purpose progress notification (media sync...) as a task, but some things will still need interaction-blocking progress like database check and media check. those would go into UI I guess, an updating screen that is sort of like what the dialog is now if you flattened the dialog into the screen itself, so those would become fragments or something I guess?

Maybe a common fragment activity that can take dialog-like inputs: title, description, okay/cancel, and a facility for a runnable with progress listener and text area to post. None of this is ground-breaking (or concrete enough from just this brainstorming) - definitely needs a real issue and an accounting with plan per item

2022-08-24 20:10 UTC, BrayanDSO approved these changes

2022-08-25 08:59 UTC, lukstbit requested changes
Small style issue before merging.

2022-08-25 08:59 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                sharedPrefs.edit().putBoolean("welcomeDialogDismissed", true).apply()
If you touched this code could you please use the edit { } extension function as well?

2022-08-26 01:25 UTC, lukstbit approved these changes

2022-08-26 05:55 UTC, merged