refactor: Convert ContentProviderTest to Kotlin
ankidroid/Anki-Android pull request #12146
Opened 2022-08-24 06:58 UTC by david-allison

2022-08-25 15:21 UTC, lukstbit requested changes

2022-08-25 15:21 UTC, lukstbit commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
> +    fun testInsertAndUpdateModel() {
@KotlinCleanup("use apply when initializing ContentValues")

2022-08-25 15:21 UTC, lukstbit commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
> +    fun testUnsupportedOperations() {
@KotlinCleanup("use assertThrows")

2022-08-25 15:21 UTC, lukstbit commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
> +        values.put(FlashCardsContract.ReviewInfo.NOTE_ID, noteId)
@KotlinCleanup("move ContentValues instantiation here and use apply scope function")

2022-08-25 15:21 UTC, lukstbit commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
> +        values.put(FlashCardsContract.ReviewInfo.NOTE_ID, noteId)
@KotlinCleanup("move ContentValues instantiation here and use apply scope function")

2022-08-25 15:21 UTC, lukstbit commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
> +        values.put(FlashCardsContract.ReviewInfo.NOTE_ID, noteId)
@KotlinCleanup("move ContentValues instantiation here and use apply scope function")

2022-08-25 15:21 UTC, lukstbit commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
> +        val suspend = 1
@KotlinCleanup("rename, while valid suspend is a kotlin soft keyword")

2022-08-25 15:21 UTC, lukstbit commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
> +class ContentProviderTest : InstrumentedTest() {
@KotlinCleanup("try to replace try{query database...}finally{cursor.close()} with databaseQuery.use { cursor -> ...}")

2022-08-26 01:48 UTC, lukstbit approved these changes

2022-08-26 10:18 UTC, BrayanDSO requested changes

2022-08-26 10:18 UTC, BrayanDSO commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
> +    var schedVersion = 0
lateinit

2022-08-26 10:18 UTC, BrayanDSO commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
> +    private var mNumDecksBeforeTest = 0
lateinit

2022-08-26 10:18 UTC, BrayanDSO commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
> +        if (isEmulator()) {
Keep `InstrumentedTest.`

2022-08-26 12:39 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
> +    var schedVersion = 0
On a `@Parameter§?

2022-08-26 12:42 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
> +        if (isEmulator()) {
This is now an IDE error

2022-08-26 13:22 UTC, BrayanDSO approved these changes

2022-08-26 15:56 UTC, merged