NF: uses assertThrows instead of try{expectToFail}catch{}
ankidroid/Anki-Android pull request #12142
Opened 2022-08-23 23:19 UTC by Arthur-Milchior

It was not corrected in `testToJSONArrayNull` because the test should fail (but since the author didn't actually add `fail()` in it, it was not detected)

2022-08-23 23:26 UTC, david-allison requested changes
I don't believe we should be calling `fail()` here

2022-08-23 23:33 UTC, Arthur-Milchior commented
I noticed and corrected it in between

2022-08-23 23:45 UTC, david-allison approved these changes
If tests pass, I'm happy

2022-08-23 23:45 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.kt
>          }
nit: would be nicer over 1 line

```
        assertThrows<JSONException> { array[1] }
```

2022-08-24 16:04 UTC, BrayanDSO commented
This has got a conflict. Otherwise, looks good.

2022-08-24 16:50 UTC, david-allison commented
```
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.kt: (33, 45): Unresolved reference: classify_handle
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.kt: (34, 45): Unresolved reference: handlebar_token
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.kt: (35, 45): Unresolved reference: legacy_handlebar_token
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.kt: (36, 45): Unresolved reference: new_handlebar_token
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.kt: (37, 45): Unresolved reference: new_to_legacy
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.kt: (38, 45): Unresolved reference: next_token
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.kt: (39, 45): Unresolved reference: text_token
```

2022-08-24 19:54 UTC, BrayanDSO approved these changes

2022-08-24 19:55 UTC, merged