refactor: Convert SchedTest to Kotlin
ankidroid/Anki-Android pull request #12144
Opened 2022-08-24 06:39 UTC by david-allison

2022-08-25 12:40 UTC, lukstbit requested changes
Looks ok, some small cleanups...

2022-08-25 12:40 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
> +class SchedTest : RobolectricTest() {
@KotlinCleanup("is -> equalTo")
@KotlinCleanup("fix ide lint issues")

2022-08-25 12:40 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
> +import net.ankiweb.rsdroid.BackendFactory.defaultLegacySchema
Revert this import

2022-08-25 12:40 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
> +    private fun getCountsForDid(didToFind: Double): DeckDueTreeNode {
@KotlinCleanup("simplify fun with firstOrNull and ?: ")

2022-08-25 12:40 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
> +        c.type = CARD_TYPE_REV
@KotlinCleanup("use scope function")

2022-08-25 12:40 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
> +        c.due = 0
@KotlinCleanup("use apply")

2022-08-25 12:40 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
> +        c.ivl = 100
@KotlinCleanup("use scope function")

2022-08-25 12:40 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
> +        c2.id = 0
@KotlinCleanup("use apply")

2022-08-25 12:40 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
> +        c.ivl = 100
@KotlinCleanup("use scope function")

2022-08-25 12:40 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
> +        c.type = CARD_TYPE_REV
@KotlinCleanup("use scope function")

2022-08-25 12:40 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
> +            c.type = CARD_TYPE_REV
@KotlinCleanup("use scope function")

2022-08-25 12:40 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
> +        c.queue = QUEUE_TYPE_REV
@KotlinCleanup("use scope function")

2022-08-25 12:40 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
> +        c.type = CARD_TYPE_REV
@KotlinCleanup("use scope function")

2022-08-25 12:40 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
> +        c.type = CARD_TYPE_REV
@KotlinCleanup("use scope function")

2022-08-26 01:52 UTC, lukstbit approved these changes

2022-08-26 11:41 UTC, BrayanDSO approved these changes

2022-08-26 16:01 UTC, merged