refactor: Convert AnkiDroidApp to Kotlin
ankidroid/Anki-Android pull request #12160
Opened 2022-08-24 17:14 UTC by david-allison

Main change: `instance` is now non-null and `lateinit`

2022-08-25 08:38 UTC, lukstbit commented
@david-allison Checks are still failing...

2022-08-26 10:44 UTC, BrayanDSO requested changes

2022-08-26 10:44 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +        // After we move past API 19, we're good to go.
We are past SDK 19, so this comment can go

2022-08-26 10:44 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +        // Note: this may be null if AnkiDroid is run via BackupManager
```suggestion
        // Note: this may be null if AnkiDroid is run via BackupManager
```
```suggestion
        // Note: this may not be initialized if AnkiDroid is run via BackupManager
```

2022-08-26 10:48 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +        // Note: this may be null if AnkiDroid is run via BackupManager
Oh, and please make a cleanup to replace this comment with a javadoc

2022-08-26 12:37 UTC, david-allison commented
@BrayanDSO Done. Tagging as this has a large chance of conflicts and want to get it in ASAP

2022-08-26 13:23 UTC, BrayanDSO approved these changes

2022-08-26 14:25 UTC, lukstbit approved these changes

2022-08-26 14:28 UTC, merged