Simplified asynctask callbacks
ankidroid/Anki-Android pull request #12166
Opened 2022-08-25 11:59 UTC by divyansh-dxn

When updating a single card, it is not required to show continuous progress since it a short task and user can be notified after the task has been finished. So instead of using onProgressUpdate callback, it is good to use onPostExecute for UI updates after the card has been updated.

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-25 16:13 UTC, lukstbit requested changes
LGTM with two styles issues.

2022-08-25 16:13 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +            if (result != null) {
You could reduce the indentation by returning early:
```

if (result == null) {
    closeReviewer(DeckPicker.RESULT_DB_ERROR, false)
    return
}
if (mCurrentCard !== result) {
```

to actually use the return statement which is currently redundant.

2022-08-25 18:37 UTC, lukstbit approved these changes

2022-08-25 18:41 UTC, divyansh-dxn commented
I like the simplification that is going on. Previously the showing and hiding of progress bar and handling error in CardBrowser is extracted into some base-classes, while going through the code it as hard to follow up and navigating class to class. TBH, some code repetition in more understandable way is better that code reuse which is hard to understand. Event these components were not too long to be extracted out even.

This is my opinion. Also when migrating to coroutines, progress will be handled by withProgress{} and error with launchCatchingtask{}, amazing wrappers implemented by @dae.

2022-08-26 02:39 UTC, Arthur-Milchior approved these changes
I agree it's a change that does not change the behavior*, so I'm fine merging it. One remark, but that can wait for the time where this task is transformed into a coroutine

* at least in the case where there is no exception

2022-08-26 02:39 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +                    showProgressBar()
I believe you can remove the `showProgressBar`. It was (theoretically) useful if we assumed some time may take until we end the computation. But now it makes no sense anymore

2022-08-26 02:39 UTC, merged