Add Anki's new Statistics page
ankidroid/Anki-Android pull request #12173
Opened 2022-08-25 17:19 UTC by BrayanDSO

## Purpose / Description
Anki has a pretty statistics screen that we can use, and the best part is that we can get it for free!

## Approach
- Add the screen
- Show it instead of the old one if the new backend is enabled

### Points to discuss
- What to do with `Default deck when opening statistics` preference, as it doesn't work with the new screen
- What to do with `Advanced statistics` preference, as it doesn't work with the new screen

## How Has This Been Tested?

- Enable the new backend
- Go to statistics

![Screenshot_20220825-141310_AnkiDroid](https://user-images.githubusercontent.com/69634269/186728544-d5c770eb-4fed-4539-991d-879025ecac24.png)

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-25 18:21 UTC, krmanik approved these changes
Finally with Anki stats page and import-csv PR, `review heatmap` also available to AnkiDroid. 
Thanks @BrayanDSO

2022-08-25 18:23 UTC, krmanik commented
I think we need one more alpha release because the PR related to import-csv (implemented on top of it).

2022-08-25 18:56 UTC, mikehardy commented
> Points to discuss
> What to do with Default deck when opening statistics preference, as it doesn't work with the new screen

If there is no ability to pass a parameter to the page, then we have to disable it for new schema

> What to do with Advanced statistics preference, as it doesn't work with the new screen

I think this just goes away, and if people want better statistics, now we work on them upstream and whole ecosystem gets them at once. Mostly advanced was augmenting the simulation to generate better estimates, and I used it for that. Not sure the upstream statistics will even need it?

2022-08-25 19:02 UTC, mikehardy requested changes
Oh! I just realized we need to put some RustCleanup annotation on the old CardInfo and also this one should include a RustCleanup on the old statistics object

also as commented that advanced prefs probably needs to be disabled for new schema, and prefs deck preference needs an examination to see if we can open stats to the deck we want

Excited for the heatmap! This will fix #6778 and #5399

2022-08-25 19:37 UTC, krmanik commented
I have attached the image for the prefs discussed above. These features should be requested if needed to upstream. 

<img src="https://user-images.githubusercontent.com/12841290/186748481-f740bf80-e453-4d09-8060-f808773a9d66.jpg" width="450px"></img>

When page loads, `deck:current` is in input box. If `show stats for all decks` is selected in AnkiDroid prefs, then `collection` should be selected. I think there should be option to send data (need to explore more).

Forecasts should be feature requests to upstream.

2022-08-25 22:04 UTC, BrayanDSO commented
In a nutshell, if someone wants one of those features, propose it to upstream and then we will automatically have it here? If so, I like this line of thought and I think that it's the easier to maintain.

IIRC, the "Default deck when opening statistics" was introduced some months ago, so only a very vew people may miss it.

2022-08-25 23:51 UTC, mikehardy commented
> In a nutshell, if someone wants one of those features, propose it to upstream and then we will automatically have it here? If so, I like this line of thought and I think that it's the easiest/most effective way to maintain it

Exactly that, and if Damien is going to get some reciprocation for all his effort, in the form of us heading over to ankitects and improving things, that's perfect synergy in my opinion, I'm looking forward to making PRs over there in the future

> IIRC, the "Default deck when opening statistics" was introduced some months ago, so only a very vew people may miss it.

Indeed - I personally like this feature, but not as much as I like deleting a bunch of finicky code and turning into a WebView in a fragment loading code with a much larger maintainer-base ;-)

2022-08-25 23:57 UTC, mikehardy approved these changes
This looks great on all counts now, fantastic. I'm going to have to turn the new backend on in my real device just to see the heatmap now

2022-08-25 23:57 UTC, merged

2022-08-26 12:24 UTC, snowtimeglass commented
Awesome. Thanks @BrayanDSO