Migrate Shared.java to kotlin
ankidroid/Anki-Android pull request #12174
Opened 2022-08-25 17:23 UTC by lukstbit

## Purpose / Description

Migrates Shared.java to kotlin following the migration guide.

## How Has This Been Tested?

Ran the tests.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-25 21:03 UTC, david-allison requested changes
One minor issue, rest looks great!

2022-08-25 21:03 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/Shared.kt
> +        Assert.assertTrue(f.delete())
re-import `Assert`

2022-08-25 23:13 UTC, BrayanDSO commented
Very good. Treat this comment as an approve once David's comment is addressed

2022-08-25 23:14 UTC, BrayanDSO approved these changes

2022-08-26 06:13 UTC, david-allison approved these changes

2022-08-26 09:03 UTC, merged