Add Anki's new Deck Options page
ankidroid/Anki-Android pull request #12175
Opened 2022-08-25 17:37 UTC by BrayanDSO

## Purpose / Description
Free screen + spare a lot of work migrating DeckOptions.kt to use fragments and the androidx.Preference

## Approach
- Add the CollectionV16's deck options methods on BackendDeckOptions.kt
- Add the new page
- Use it if the new backend is enabled

## How Has This Been Tested?

https://user-images.githubusercontent.com/69634269/186731680-548ff459-7c7d-46e3-a973-b12d6124a46f.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-25 17:44 UTC, BrayanDSO commented
Drafting because of some issues shown on the video.

1. the restore option spins eternally
2. "Remove preset" doesn't work
3. There isn't any feedback after taping "Save"
4. a big right margin shows up if you open one of the preset dialogs
    - ![image](https://user-images.githubusercontent.com/69634269/186733201-d7eb6dbd-5845-42e3-b3ad-4eca799850cb.png)
 
I barely have explored/tested this screen, so some of these are probably my fault. Not sure when I'll be available to work on this

2022-08-26 11:31 UTC, snowtimeglass commented
Splendid! Thanks a lot for this work!

2022-08-29 14:44 UTC, dae commented
- The spinning is the same on the desktop - I believe Henrik intended it to be that way, though I can see how it could be seen as unintentional.
- The feedback on save should be provided by AnkiDroid when it processes the save request

2022-09-02 23:57 UTC, BrayanDSO commented
> Preset removal relies on the JavaScript confirm() and alert(), which AnkiDroid may have to add support for.

I believe that these come from [here](https://github.com/ankitects/anki/blob/1bab947c9c16f3725076462a702c880a083afe90/qt/aqt/webview.py#L151-L155) on upstream, which are [QWebEnginePage methods](https://doc.qt.io/qt-6/qwebenginepage.html#javaScriptAlert) and which I need to find the Android methods to intercept them

2022-09-03 01:55 UTC, dae commented
Appears to be possible: https://stackoverflow.com/questions/2726377/how-to-handle-a-webview-confirm-dialog

2022-09-03 09:37 UTC, BrayanDSO commented
On top of/blocked by #12289

2022-09-03 09:48 UTC, BrayanDSO commented
Now that I noticed that if you tap "Restore this setting to its default value", it stops spinning, but that's something to solve on upstream.

https://user-images.githubusercontent.com/69634269/188265140-0dc78a22-33f9-4ff6-b16a-6cc352bede66.mp4

About the previous problems, only `a big right margin shows up if you open one of the preset dialogs` remains and this big margin:

![image](https://user-images.githubusercontent.com/69634269/188265312-eca8bc69-bdc8-4ca0-87b5-4804601e97aa.png)

As those aren't vital and I won't have time to investigate it any time soon, I think this can be reviewed.

2022-09-13 12:58 UTC, mikehardy commented
I just rebased to main and did `git push --force-with-lease` on the reomte fork/branch mostly to re-start CI really easily but also to make sure this is up to date. Hoping to review shortly and get this in

2022-10-13 23:41 UTC, BrayanDSO commented
This is getting dusty, but conflict-proof 😎

2022-10-14 20:45 UTC, mikehardy commented
focused on scoped storage right now but I do want to get this in (obviously, I even pull/pushed the branch myself ha), just have to prioritize those PR reviews, thanks for your patience

2022-10-31 00:41 UTC, mikehardy requested changes
I want to approve this but it is not working for me on an android 21 google-apis emulator?
It works on API33

2022-10-31 01:18 UTC, mikehardy commented
Ah ha! I'll try a play store emulator for 21, it can update I think. Subtle, good info thank you

2022-10-31 01:20 UTC, mikehardy approved these changes
going with it

2022-10-31 01:20 UTC, merged

2022-11-03 12:57 UTC, snowtimeglass commented
How nice. Now we can specify intervals with units of hours (e.g. 3h) and days (e.g. 3d) on AnkiDroid as well as Anki Desktop. It's so useful. Information icons beside each items are also so helpful. Thanks a lot.