refactor: Convert JSONArray to Kotlin
ankidroid/Anki-Android pull request #12198
Opened 2022-08-27 14:12 UTC by david-allison

2022-08-27 16:08 UTC, mikehardy approved these changes
Surprisingly this passes local CI runs even after the merge of a bunch of semi-related kotlin migrations and nullability refactors. Looks good to go to me

2022-08-27 16:13 UTC, lukstbit requested changes
Looks good with some small cleanups.

2022-08-27 16:13 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/utils/JSONArray.kt
> +    fun toStringList(key: String?): List<String> {
@KotlinCleanup("simplify fun with apply and forEach")

2022-08-27 16:13 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/utils/JSONArray.kt
> +    override fun put(value: Double): JSONArray {
Your choice for this cleanup but I was thinking about reducing the lines of code by introducing a helper method:
```

private fun <T> withProperException(action: () -> T): T = try {
        action()
    } catch (e: org.json.JSONException) {
        throw JSONException(e)
    }
```

Then most of the line here will be a one liner(JsonObject could benefit from this also):
```

override fun put(value: Double): JsonArray = withProperException { 
   super.put(value)
   this
 }
```

2022-08-27 16:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/JSONArray.kt
> +    override fun put(value: Double): JSONArray {
Since Kotlin doesn't have checked exceptions, I'm not sure if this class still needs to exist

2022-08-28 11:18 UTC, lukstbit approved these changes

2022-08-28 11:45 UTC, merged