refactor: Kotlin Cleanup: Collection/Note
ankidroid/Anki-Android pull request #12201
Opened 2022-08-27 22:14 UTC by david-allison

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-28 11:59 UTC, lukstbit requested changes

2022-08-28 11:59 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +    fun findDupes(fieldName: String?, search: String? = ""): List<Pair<String, List<Long>>> {
This method is used only from kotlin code so the above @JvmOverloads cleanup is not needed anymore.

2022-08-28 11:59 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        nids: List<Long?>,
This method is unused so I would add a cleanup with @KotlinCleanup("see if method can be removed").
Also, I would remove the cleanup for jvm overloads. While Finder.findReplace has default parameters and we could make the findReplace methods here with default parameter I wouldn't do it as it ties the two classes together(a change in Finder.findReplace default values would need to be replicated in Collection.findReplace).

2022-08-28 12:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        nids: List<Long?>,
Done

I believe this is functionality which Anki Desktop exposes, and we'll want. to expose this to advanced users in the future.

2022-08-28 13:13 UTC, lukstbit approved these changes

2022-09-02 16:17 UTC, mikehardy approved these changes
:broom: :broom:

2022-09-02 16:17 UTC, merged