Solved backendUndoAndShowPopup() snackbar on top of answer button
ankidroid/Anki-Android pull request #12207
Opened 2022-08-28 07:37 UTC by sparkyniner

## Pull Request template

## Purpose / Description
The backendUndoAndShowPopup() was showing snackbar on top of the answer button

## Fixes
Now the backendUndoAndShowPopup() does not show on top of the answer button

## Approach
I have changed the position of where the snackbar appears using  the setAnchorView method to make a Snackbar appear above a specific view.

## How Has This Been Tested?

I have tested this in various emulators such as Pixel 4a API 31, Pixel 5 API 31, samsung A10

##Learning 
the following stackoverflow answer helped me: https://stackoverflow.com/a/58665768 and can be used as a reference if a similar problem arises in the future

##Screenshot solving the problem
https://imgur.com/a/LLnYPem
## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](![right](https://user-images.githubusercontent.com/110723606/187063335-7c7b99b1-57bb-4019-a23d-6fc7da2ad12b.png))

2022-08-28 08:58 UTC, david-allison requested changes
Thanks!!!

Few comment. In addition to this, please aim to `rebase` your changes before pushing so only relevant commits are included. 

The test commit + rollback + merge commits don't add value to the codebase and we shouldn't merge them.

2022-08-28 08:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/BackendUndo.kt
> +        snackbar.show()
There's a lot of IDE Lint issues here. Before submitting a change, you should aim for these to be resolved. The IDE proposes auto-fixes for these issues, such as `snackbar.anchorView = ans_button`

2022-08-28 08:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/BackendUndo.kt
> +@SuppressLint("DirectSnackbarMakeUsage")
We should be using the following pattern rather than ignoring the lint. The code which was written avoids all our fixes for Android snackbars

```kotlin
showSnackbar(TR.undoActionUndone(changes.operation)) {  
    // additional init code. `this` is a Snackbar instance
}
```

2022-08-28 08:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/BackendUndo.kt
> +        snackbar.setAnchorView(ans_button) // sets the anchorview as answerbutton
This comment adds no value, if you're adding a comment, aim to explain the 'why', and the 'what' if it's a complex operation

2022-08-28 08:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/BackendUndo.kt
> +        val ans_button = findViewById(R.id.flip_card) as Button
This is tied to the `AbstractFlashvardViewer`, it would be ideal if this was a 'generic' method which would work for any activity.

We have two choices here:

1. Apply a tag and use `root_layout?.findViewByTag`
2. Also apply a known constant ID to the view element the snackbar should be above and search for this.

I'd personally prefer '1'

2022-08-28 12:57 UTC, sparkyniner commented on AnkiDroid/src/main/java/com/ichi2/anki/BackendUndo.kt
> +        val ans_button = findViewById(R.id.flip_card) as Button
Hello!, so I'll make the recommended changes and get back to you soon?

2022-08-28 13:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/BackendUndo.kt
> +        val ans_button = findViewById(R.id.flip_card) as Button
Nl rush, thank you!

2022-08-30 04:06 UTC, sparkyniner commented on AnkiDroid/src/main/java/com/ichi2/anki/BackendUndo.kt
> +        val ans_button = findViewById(R.id.flip_card) as Button
Hello!, I have made the recommended changes, I was a bit busy moving in to my college so I couldn't do this sooner.

2022-08-30 04:19 UTC, dae commented
backendUndoAndShowPopup() is used on other screens like the CardBrowser screen. Does it still work on those screens after this change? Instead of tying this to a particular screen, perhaps an optional anchor view should be passed into the function instead.

2022-08-30 04:42 UTC, david-allison commented
> backendUndoAndShowPopup() is used on other screens like the CardBrowser screen. Does it still work on those screens after this change? Instead of tying this to a particular screen, perhaps an optional anchor view should be passed into the function instead.

Passing in `null` removes the anchor if set. It appears to work as it did previously

2022-08-30 12:16 UTC, sparkyniner commented
> Passing in `null` removes the anchor if set. It appears to work as it did previously

Is there anything else I can do? Or should I just wait for feedback?

2022-08-30 12:24 UTC, dae commented
I am not an AnkiDroid maintainer, so I have no say here, but IMHO changing the function to take an optional view argument that the reviewer passes in would be cleaner, as currently Reviewer-specific functionality has leaked into a general routine. The comment you've left there also doesn't match what it's doing - it's not using a tag, it's hard-coding a specific button.

Minor style note, and may come down to personal preference: I think the comment if preserved in some form should come above the code, instead of to the right.

2022-08-30 13:46 UTC, david-allison requested changes

2022-08-30 13:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/BackendUndo.kt
> +            val ans_button = findViewById(R.id.flip_card) as Button
* extract `ans_button` to an optional argument: anchorView
  * document the usage of the argument 
* supply it here:
https://github.com/ankidroid/Anki-Android/blob/d980933392cc2e14a00036fd72bf4749134e2426/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt#L848-L851 
* change `this.setAnchorView(ans_button)` to `anchorView?.let { }`

----

```kotlin
/** @param anchorView The view to display the snackbar above */
suspend fun FragmentActivity.backendUndoAndShowPopup(anchorView: View? = null): Boolean {
    return try {
        val changes = withProgress() {
            undoableOp {
                undoNew()
            }
        }

        showSnackbar(TR.undoActionUndone(changes.operation)) {
            // A snackbar may obscure vital elements (e.g: the answer buttons on the Reviewer)
            // `anchorView` stops this
            anchorView?.let { setAnchorView(anchorView) }
        }
```

2022-08-30 13:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/BackendUndo.kt
> +        showSnackbar(TR.undoActionUndone(changes.operation), Snackbar.LENGTH_LONG) {
`Snackbar.LENGTH_LONG` was an unnecessary change

2022-08-30 13:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/BackendUndo.kt
> +            val ans_button = findViewById(R.id.flip_card) as Button
This doesn't use the IDE suggestions

2022-08-31 06:49 UTC, sparkyniner commented
Hello!, added your recommended changes

2022-08-31 18:05 UTC, david-allison commented
You missed the comment on the first line

2022-09-01 13:25 UTC, sparkyniner commented
done

2022-09-01 13:34 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
>                      // TODO make backendUndoAndShowPopup() snackbar don't show on top of the answer buttons
I think this is the comment David was referring to.

2022-09-01 13:35 UTC, sparkyniner commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
>                      // TODO make backendUndoAndShowPopup() snackbar don't show on top of the answer buttons
alright i'll make the change asap

2022-09-01 13:39 UTC, sparkyniner commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
>                      // TODO make backendUndoAndShowPopup() snackbar don't show on top of the answer buttons
you mean this? "// TODO make backendUndoAndShowPopup() snackbar don't show on top of the answer buttons" shoudn't I remove this comment since this issue will be sorted out?

2022-09-02 00:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
>                      // TODO make backendUndoAndShowPopup() snackbar don't show on top of the answer buttons
```suggestion
```

2022-09-02 00:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/BackendUndo.kt
> +        showSnackbar(TR.undoActionUndone(changes.operation), Snackbar.LENGTH_LONG) {
This is still an issue

2022-09-02 13:13 UTC, sparkyniner commented
Please ignore the last commit, it was for another PR.

2022-09-03 13:06 UTC, sparkyniner commented
Can you please review this PR?

2022-09-03 16:10 UTC, david-allison approved these changes
Looks great!

2022-09-03 16:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +                    if (!backendUndoAndShowPopup(findViewById(R.id.flip_card))) {
implementer's choice: I'd consider naming the argument here

2022-09-04 09:16 UTC, sparkyniner commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +                    if (!backendUndoAndShowPopup(findViewById(R.id.flip_card))) {
What name would you suggest?

2022-09-05 03:03 UTC, sparkyniner commented
Can someone please review this PR so that I can start working on another issue?

2022-09-05 18:01 UTC, mikehardy commented
Hey @sparkyniner :wave:  thanks for working through this

Some thoughts on collaboration:
1- we're all volunteers, and the maintainers get a *lot* of notifications. Please be patient with the reviews and don't ping people unless it has really been a week or so
2- no reason to wait! You can start working on anything else while a PR is enqueued. Some people have 5-10 PRs open at once. That said, make sure that things are getting completed before moving on
3- please read up (and practice locally) on how to make multiple commits to a branch, how to interactively rebase them to squash commits, re-order them, drop them, and force push back to your branch. That makes reviewing much easier - right now this commit history is impossible to follow:

![image](https://user-images.githubusercontent.com/782704/188498095-059fd975-23a8-4a53-acc2-ec3e8ed19bba.png)


Getting used to a rebase-heavy workflow takes some time and practice but it pays off with a clean commit history and helps you think about the changes you make to software in a really clear way. It also helps maintainers when they review your PRs as you can keep each commit focused on one simple + easy-to-review thing like "extracting this method for future reuse", "using extracted method in this new way here", "fixing lint issues", and the diffs are still readable. This is only really possible when you can rebase code and move changes around in commits then push them back out. Give it a shot on the next PR

2022-09-05 18:06 UTC, mikehardy approved these changes
Looks good to me - thanks!

2022-09-05 18:07 UTC, merged

2022-09-06 02:46 UTC, sparkyniner commented
> Hey @sparkyniner :wave:  thanks for working through this
> 
> 
> 
> Some thoughts on collaboration:
> 
> 1- we're all volunteers, and the maintainers get a *lot* of notifications. Please be patient with the reviews and don't ping people unless it has really been a week or so
> 
> 2- no reason to wait! You can start working on anything else while a PR is enqueued. Some people have 5-10 PRs open at once. That said, make sure that things are getting completed before moving on
> 
> 3- please read up (and practice locally) on how to make multiple commits to a branch, how to interactively rebase them to squash commits, re-order them, drop them, and force push back to your branch. That makes reviewing much easier - right now this commit history is impossible to follow:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/782704/188498095-059fd975-23a8-4a53-acc2-ec3e8ed19bba.png)
> 
> 
> 
> 
> 
> Getting used to a rebase-heavy workflow takes some time and practice but it pays off with a clean commit history and helps you think about the changes you make to software in a really clear way. It also helps maintainers when they review your PRs as you can keep each commit focused on one simple + easy-to-review thing like "extracting this method for future reuse", "using extracted method in this new way here", "fixing lint issues", and the diffs are still readable. This is only really possible when you can rebase code and move changes around in commits then push them back out. Give it a shot on the next PR

Thank you for all the recommendations and tips will definitely keep this in mind working on the next PR.