Migrate Factor to kotlin
ankidroid/Anki-Android pull request #12206
Opened 2022-08-28 07:04 UTC by lukstbit

## Purpose / Description

Migrates Factor.java to kotlin following the kotlin migration guide. Class from the doomed wildplot package so no cleanups.

Note for reviewers: In getValue() I suppressed a warning about "recursive property access" for lines:

```
            FactorType.PLUS_FACTOR -> factor!!.value
            FactorType.MINUS_FACTOR -> -factor!!.value
```

My reasoning is this doesn't call the getValue() method from this object but from another object `factor` so there's no recursive call and an error from the IDE. Review carefully.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-28 08:18 UTC, david-allison requested changes

2022-08-28 08:18 UTC, david-allison commented on AnkiDroid/src/main/java/com/wildplot/android/parsing/Factor.kt
> +    @Suppress("RecursivePropertyAccessor")
only request: can this be commented to explain that it's an IDE bug. I've confirmed the logic and it seems buggy to me as well

2022-08-28 09:00 UTC, david-allison approved these changes

2022-09-02 14:08 UTC, BrayanDSO approved these changes

2022-09-02 14:08 UTC, merged