Migrate ParsedNodes to kotlin
ankidroid/Anki-Android pull request #12212
Opened 2022-08-28 10:19 UTC by lukstbit

## Purpose / Description

Migrates ParsedNodes.java to kotlin following the migration guide.

## How Has This Been Tested?

Ran the tests.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-28 10:26 UTC, david-allison approved these changes

2022-08-31 19:34 UTC, BrayanDSO approved these changes

2022-08-31 22:17 UTC, BrayanDSO requested changes

2022-08-31 22:17 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/template/ParsedNodes.kt
> +        return "$t))"
for a KotlinCleanup: Either this method should be removed as it isn't used, or it should have the result changed, as Kotlin doesn't use `new` nor should use `Arrays.asList`.

I'd vote to remove, but I'm fine either way

2022-09-01 04:56 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/template/ParsedNodes.kt
> +        return "$t))"
You never can delete too much code. Added a cleanup.

2022-09-01 09:11 UTC, BrayanDSO approved these changes

2022-09-01 09:11 UTC, merged