DRAFT: refactor: Convert CollectionHelper to Kotlin
ankidroid/Anki-Android pull request #12216
Opened 2022-08-28 15:06 UTC by david-allison

The third commit felt too large to sneak in

I'd like to cherry pick changes from it to reduce the size, then squash with commit 2

2022-08-31 18:31 UTC, david-allison commented
https://github.com/ankidroid/Anki-Android/pull/12217 merged, rebased on `main` + ready for review

2022-09-01 00:14 UTC, BrayanDSO commented
```
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt:1: Error: Tags were corrupted by the Kotlin migration. For example: <br></br> [KotlinMigrationFixLineBreaks from com.ichi2.anki:lint-rules]
/***************************************************************************************
```

```
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt: (180, 32): Unresolved reference: runTest
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt: (224, 40): Unresolved reference: runTest
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt: (356, 45): Unresolved reference: runTest
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt: (369, 42): Unresolved reference: runTest
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt: (583, 31): Unresolved reference: runTest
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt: (641, 40): Unresolved reference: runTest
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt: (147, 40): Unresolved reference: runTest
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt: (159, 31): Unresolved reference: runTest
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt: (179, 9): Suspend function 'undo' should be called only from a coroutine or another suspend function
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt: (188, 35): Unresolved reference: runTest
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt: (212, 9): Suspend function 'undo' should be called only from a coroutine or another suspend function
```

+ conflicts

2022-09-01 00:25 UTC, dae commented
The rebase has reverted the runTest/awaitJob changes from #12226

2022-09-02 16:13 UTC, BrayanDSO requested changes
For the future, I'd consider using [object](https://kotlinlang.org/docs/object-declarations.html#object-declarations-overview) on CollectionHelper. It would reduce the boilerplace of writing `.instance` and make possible to import/use the methods directly.

Only `setInstanceForTesting` would need changes to adapt to it

2022-09-02 16:13 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
> +         * The AnkiDroid directory is a user preference stored under [.PREF_COLLECTION_PATH], and a sensible
```suggestion
         * The AnkiDroid directory is a user preference stored under [PREF_COLLECTION_PATH], and a sensible
```

2022-09-03 00:45 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
> +     * This operation does not call [.initializeAnkiDroidDirectory] and does not set the singleton instance's [.mCollection]
The dot before mCollection wasn't removed

2022-09-03 00:46 UTC, BrayanDSO approved these changes
LGTM, not worth blocking on a comment

2022-09-03 01:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
> +     * This operation does not call [.initializeAnkiDroidDirectory] and does not set the singleton instance's [.mCollection]
`mCollection` isn't a valid symbol, I've done it, but it'll be changed in a later cleanup

2022-09-03 11:49 UTC, lukstbit approved these changes
LGTM

2022-09-03 12:03 UTC, merged