refactor: Convert ApiUtilsTest to Kotlin
ankidroid/Anki-Android pull request #12211
Opened 2022-08-28 09:51 UTC by david-allison

com.ichi2.anki.api.ApiUtilsTest

Git hooks were disabled for this commit due to the extra commit for the
java -> kt rename

(irrelevant) Issue with conversion file was listed: 12209

added `kotlin-test` for null-safe: `assertNull` required for lint

2022-08-28 12:15 UTC, lukstbit requested changes

2022-08-28 12:15 UTC, lukstbit commented on api/src/test/java/com/ichi2/anki/api/ApiUtilsTest.kt
> +import org.junit.Assert
Import again Assert.assertEquals

2022-08-28 12:15 UTC, lukstbit commented on api/src/test/java/com/ichi2/anki/api/ApiUtilsTest.kt
> +class ApiUtilsTest {
@KotlinCleanup("replace Assert.assertEquals with kotlin.test.assertEquals")

2022-08-28 12:15 UTC, lukstbit commented on api/src/test/java/com/ichi2/anki/api/ApiUtilsTest.kt
> +        val set: MutableSet<String?> = HashSet()
@KotlinCleanup("use mutableSetOf, use scope function")

2022-08-28 12:15 UTC, lukstbit commented on api/src/test/java/com/ichi2/anki/api/ApiUtilsTest.kt
> +import com.ichi2.anki.api.Utils.fieldChecksum
Revert the imports of the individual methods from Utils.

2022-08-28 12:21 UTC, david-allison commented
Done. Using `TODO` as there's no cleanup attribute in the API module

2022-08-28 13:15 UTC, lukstbit approved these changes
LGTM

2022-09-01 04:10 UTC, lukstbit commented
I merged #12250 if you want to rebase and get rid of that array of nullable strings.

2022-09-02 10:39 UTC, BrayanDSO approved these changes

2022-09-02 10:39 UTC, merged