fix: replace cloze with blank within <tts> tag
ankidroid/Anki-Android pull request #12236
Opened 2022-08-29 23:03 UTC by KendallPark

resolves ankidroid/Anki-Android#12233

## Pull Request template

## Purpose / Description
#12233

## Fixes
Fixes #12233

## Approach
Adds `replace` to another line of code which handles text within a `tts` tag.

## How Has This Been Tested?

Added a test for the `<tts service="android">` tag. It fails without the fix, passes with the fix.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-29 23:08 UTC, KendallPark commented
Didn't add comments as changes are trivial.

2022-08-29 23:15 UTC, david-allison approved these changes
Awesome, thanks so much!

2022-08-29 23:22 UTC, mikehardy requested changes
Thanks for taking this up! I'm unsure on the `!!` treatment, given it's an optional param, what happens when it's null?

2022-08-29 23:22 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt
> +            textsToRead.add(localisedText(element.text().replace(TemplateFilters.CLOZE_DELETION_REPLACEMENT, clozeReplacement!!), element.attr("voice")))
:thinking: clozeReplacement is `String?` coming in, but then `!!`ed here. Is that right?

2022-08-29 23:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt
> +            textsToRead.add(localisedText(element.text().replace(TemplateFilters.CLOZE_DELETION_REPLACEMENT, clozeReplacement!!), element.attr("voice")))
Yes, still pending Kotlin nullability fixes 

`context.getString(R.string.reviewer_tts_cloze_spoken_replacement)`

2022-08-29 23:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt
> +            textsToRead.add(localisedText(element.text().replace(TemplateFilters.CLOZE_DELETION_REPLACEMENT, clozeReplacement!!), element.attr("voice")))
I'll put in a follow-up PR to clean this

2022-08-29 23:48 UTC, KendallPark commented on AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt
> +            textsToRead.add(localisedText(element.text().replace(TemplateFilters.CLOZE_DELETION_REPLACEMENT, clozeReplacement!!), element.attr("voice")))
@mikehardy I'm not a Kotlin dev, so I couldn't say what that's about. I simply copied the code and conventions from line 32 and the surrounding function.

Seems to be a side effect of: https://github.com/ankidroid/Anki-Android/commit/effe98771a40cd12286a55e5a3677cbd8eeb194a

2022-08-29 23:50 UTC, KendallPark commented
Tested on my phone and it is working as expected.

2022-08-30 00:01 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt
> +            textsToRead.add(localisedText(element.text().replace(TemplateFilters.CLOZE_DELETION_REPLACEMENT, clozeReplacement!!), element.attr("voice")))
Thanks David - that makes sense, and thanks again Kendall

2022-08-30 00:02 UTC, mikehardy approved these changes

2022-08-30 00:02 UTC, merged