[GSoC] Implemented Notification Datastore and Work Manager
ankidroid/Anki-Android pull request #12234
Opened 2022-08-29 21:52 UTC by prateek-singh-3212

## Pull Request template

## Purpose / Description
 Implemented Notification Datastore and Work Manager for new notification subsystem. child of (#11487 )

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-29 22:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +* This will occur on 20 NOVEMBER 2286
We should handle this now. 

For example, why can't we use a `Long` timestamp in the map, if that's our implementation, or provide a custom comparator

2022-08-29 22:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +    private val objectMapper = ObjectMapper()
could this be in the companion object? It doesn't seem to have state

2022-08-29 22:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +     * Calling this function guarantees to store value in database.
What do you mean by this? It's strange to read

2022-08-29 22:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +    suspend fun getString(key: String, default: String): String {
Why is this `suspend` without an `async` suffix?

2022-08-29 22:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +    @Suppress("BlockingMethodInNonBlockingContext")
Why?

2022-08-29 22:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +            synchronized(this) {
explain that we're using this pattern because we need a `Context` to get an instance

2022-08-29 22:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/model/DeckNotification.kt
> +) {
⚠️ 

I don't think this accurately models our users needs from notifications. 

What did your research into our use cases provide?

<details><summary>my uninformed thoughts - to read after commenting</summary>

I would wager that most people want:

- Remind me once in the day
- Remind me once at 23:00 if I haven't done any reviews

I suspect a more nuanced view is that users care about:

- Reviewing one card (to keep up their streaks)
- Finishing the decks they care about ('completed Anki for the day')

I suspect that some decks will want to be excluded from this calculation

I suspect that we'll want a different mode for 'catching up': a user is happy if they've completed X cards per day from a deck which they've fallen behind from.

</details>

2022-08-30 10:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +* NOTE: It's in decimal. Hexadecimal would make the conversion faster and takes less space, but really not worth the code complexity added.
Oh sorry, ; was the one suggesting it.
Timestamps are stored as string, which is slightly unusual, but required to be keys of json object. 
I noted that hexadecimal would be more efficient for parsing, but not worth the complexity added. 
I'm not sure that adding an example of timestamp (that is, a string encoding a long in decimal) would help that much

2022-08-30 10:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +* This will occur on 20 NOVEMBER 2286
That was explained in `TimeOfNotification`'s javadoc. Because jsonobject requires string as map key.
Personally, I don't believe that blocking over an issue that will occur in 260 years is required. I highly doubt this code will still be in use by then

2022-08-30 10:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +    suspend fun getString(key: String, default: String): String {
`sync` and `async` were added only when both version exists for disambiguating.
I don't believe it's useful to add it when there is a single version. Typing, compiler and intellij will make it clear enough if it's used in the wrong place

2022-08-30 10:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +    @Suppress("BlockingMethodInNonBlockingContext")
I admit that this suppress should be added just before the method that is theoretically blocking.

In this case, it's `readValue`, and while it's true that Parsing JSON can be very long, I don't expect we get the issue here. Anyway, I don't expectt that we want to reencode the method to read json in a way that can be interrupted.

2022-08-30 10:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/model/DeckNotification.kt
> +) {
<details><summary>Comment before reading your thoughts:</summary>
* not having warning if there is only 2 cards seems not that bad. Going back to ankidroid while you did most of the work seems not necessarily a great use of time. At least offering the option to the user seems nice.
* I admit that I was used to notification on deck options. But especially if e limit ourself to top level deck, having the notification chosen at the deck level don't seems absurd
</details>
<details><summary>Comment after reading your thoughts:</summary>
* We can always add more data in the data class than necessary. If we decide for example not to let the user select minutes, fine, it should still work.
* I admit that adding an extra field to note "don't warn" if I already did N card seems nice
* Since this notification is done at the deck level, I don't think we need anything specific to exclude some deck
</details>

2022-08-30 12:45 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +* This will occur on 20 NOVEMBER 2286
The issue occurs immediately if the user has a temporary issue with their calendar returning 'Jan 1 1970'

2022-08-30 13:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/model/DeckNotification.kt
> +) {
My issue is that we don't seem to have gone through the use cases, and this structure seems very far from what the 'ideal' would be.

<details>

<summary>Again, uninformed</summary>

```typescript
type NotificationTime = {hour: int; minute: int}

// TODO: terms prefixed with 'NotStudiedX' needs work
// excluding a deck will never complete to these items
type AdditiveTrigger = 'NotStudied' | 'NotStudiedXCards' | 'NotStudiedXCardInstances' | 'NotStudiedXMinutes'
// Excluding a deck could cause these conditions to be completed
type ReductiveTrigger =  'NotCompleted' 
type Trigger = [AdditiveTrigger; { ReductiveTrigger; excludedDecks: DeckId } ]

type Reminder = {
    time: NotificationTime;
    trigger: Trigger;
    enabled: boolean;
}

type AllDeckReminder = Reminder

// The majority of users will use 'All Deck' settings
type AllDeckNotificationSettings = {
    excludeDecks: DeckId[]; // globally excluded from checks
    reminders: AllDeckReminder[];
}

type IndividualDeckReminder = Reminder() = {
    deckIds: DeckId[];
    includeChildren: boolean; // edge case: otherwise we can't set notifications on a 'parent' deck without excluding child decks
}

type NotificationSettings = {
    allDeckNotifications: AllDeckNotificationSettings;
    individualDeckReminders: IndividualDeckReminder[]
}

let defaultNotificationSettings = {
  individualDeckReminders = [];
  allDeckNotifications = {
      excludeDecks = [];
      reminders = [{
          time: "8:00 AM";
          trigger: "NotStudied";
      }, {
          time: "6:00 PM";
          trigger: "NotCompleted";
      }, {
          time: "23:00 PM";
          trigger: "NotStudied";
      ]
  };
}

// TODO: Should handle the use case of 'coming back from a break', but happy for this to be non-automated


```

</details>

2022-09-02 23:41 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +* This will occur on 20 NOVEMBER 2286
Regarding epoch, I admit I had not thought about it. I have no real idea of what to do in this case because, if this occur, the whole system breaks. It assumes time is increasing and valid. Everything needs to be think through again. This is not just a problem of number of digits

Regarding changing their time, do you mean that we may consider the case where a user set time 260 years in the future? Or enough years in the past to get a digit less? In this case, again, the whole notification system will fail, since if you add even 24 hours, all notifications will be seen as overdue.

If you really want to consider the entire Long, then I guess we should use a Map whose keys are Long, and convert it to a map whose keys are String when writting it (and reciprocally). So at least conversions are done only once and not each time there is a search, insertion or deletion from the map

2022-09-03 15:51 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +* This will occur on 20 NOVEMBER 2286
All this takes to fix is constructing the class with a comparator. 

We have a known bug which will be a nightmare to diagnose with an easy fix. I don't see why we're shying away from this fix


```kotlin
                NotificationTodo { o1, o2 -> o1.toLong().compareTo(o2.toLong()) }
```

2022-09-03 15:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +* NOTE: It's in decimal. Hexadecimal would make the conversion faster and takes less space, but really not worth the code complexity added.
I'd remove the mention of hexadecimal, it massively overcomplicates a simple class

2022-09-18 21:17 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +     *  We are using custom work manager because UNIT TESTS are failing.
Done

2022-09-18 21:23 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/AndroidManifest.xml
> +        is not initialize properly SEE: https://issuetracker.google.com/issues/138465476 -->
Okay. Removed this.
new one is: 
```      
  <!-- Using custom work manager initialization -->
```

2022-09-18 21:23 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +* NOTE: It's in decimal. Hexadecimal would make the conversion faster and takes less space, but really not worth the code complexity added.
Okay removing this.

2022-09-18 21:35 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +    private val objectMapper = ObjectMapper()
Done

2022-09-18 21:37 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +    suspend fun getString(key: String, default: String): String {
I think that the above clears the doubt. I am not changing anything here.

2022-09-18 21:40 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +            synchronized(this) {
Done

2022-09-18 21:48 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +     * Calling this function guarantees to store value in database.
Actually I divided it into 3 points instead of a complete sentence

2022-09-18 21:49 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +     * Calling this function guarantees to store value in database.
Changed this into
```
/**
     * 1. Stores the String in Notification Datastore.
     * 2. It stores the data asynchronously.
     * 3. Calling this function guarantees to store value in database.
     * @param key The Key of value. Used in fetching the data.
     * @param value Value that needs to be stored <b>(VALUE MUST BE STRING)</b>.
     * */
   ```

2022-09-18 22:18 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +* This will occur on 20 NOVEMBER 2286
Sorry I did't got the above explanation. I implemented the extension function.
```

/**
 * Compare the [TimeOfNotification]. It avoid the failure of comparing 2 [TimeOfNotification] when timestamp gets an extra digit because we'll get new timestamps
 * starting with a 1 that will be a number greater than previous numbers but alphabetically shorter
 * */
fun TimeOfNotification.compare(timeOfNotification: TimeOfNotification) = this.toLong().compareTo(timeOfNotification.toLong())
```

2022-09-19 04:44 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +    @Suppress("BlockingMethodInNonBlockingContext")
I think the above explanation is clear. So not removing this.

2022-09-21 22:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/model/DeckNotification.kt
> +) {
My proposal above rests on the fact that `minCardsDue` is not a good abstraction of the user desires.

The in my mind, the desires should be: "started" (streak) and "completed" (done for the day), and these can't be derived from `minCardsDue`

2022-09-21 22:07 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +    @Suppress("BlockingMethodInNonBlockingContext")
Could it be transferred to a comment?

2022-09-21 22:07 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +* This will occur on 20 NOVEMBER 2286
This needs to be passed into the constructor of `TreeMap` for it to perform sorting correctly

2022-09-21 22:08 UTC, david-allison commented on AnkiDroid/src/main/AndroidManifest.xml
> +        is not initialize properly SEE: https://issuetracker.google.com/issues/138465476 -->
Point the user to where they can find more information

2022-09-21 22:09 UTC, david-allison requested changes
Mainly discussion on the schema pending

2022-09-27 08:09 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/AndroidManifest.xml
> +        is not initialize properly SEE: https://issuetracker.google.com/issues/138465476 -->
Done

2022-09-27 08:43 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +    @Suppress("BlockingMethodInNonBlockingContext")
Comment is already present
`We actually are not blocking the thread. This method throws an exception. It will not create problem for us.`

2022-09-28 14:14 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/DeckNotification.kt
> +) {
`started` is Long i.e day on which deck started.
`completed` is Boolean (true if Completed for day else false)
@david-allison

2022-09-28 14:45 UTC, david-allison commented on AnkiDroid/src/main/AndroidManifest.xml
> +        <!-- Using custom work manager initialization -->
link to the method that explains why we're doing this: (`getWorkManagerConfiguration`)

2022-09-28 14:45 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +* This will occur on 20 NOVEMBER 2286
This still isn't handled

2022-09-28 14:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/model/DeckNotification.kt
> +) {
I don't think these of those are part of this data structure. This is what a user defines, not the current state of notifications

2022-10-01 05:35 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +* This will occur on 20 NOVEMBER 2286
@david-allison I am thinking correct then when we create the object of `NotificationTodo` then only we can pass the constructor and can write the below line
```                 NotificationTodo { o1, o2 -> o1.compare(o2) }
```
And In the current PR we are not creating the construstor

2022-10-06 11:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +* This will occur on 20 NOVEMBER 2286
Why not make it so the object can only be constructed correctly?

2022-10-07 05:16 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +* This will occur on 20 NOVEMBER 2286
Done added 
```
/**
 * Default object for [NotificationTodo]. This object adds comparator for string values.
 * */
fun NotificationTodoObject() = NotificationTodo { timeOfNotification1, timeOfNotification2 ->
    timeOfNotification1.compare(timeOfNotification2)
}
```

2022-10-07 05:16 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/DeckNotification.kt
> +) {
Done please check now.

2022-10-08 19:19 UTC, prateek-singh-3212 commented
@david-allison Done with the suggested changes kindly review it.

2022-10-26 14:14 UTC, oakkitten commented
I put some suggestions in #12635, of which this seems to be a part. Not entirely sure why this is a separate PR but I'd like the comments from there addressed here as well.

(Why does this need several PRs?)

2022-10-26 16:36 UTC, prateek-singh-3212 commented
@oakkitten That PR is built up on this PR. I did this because notification UI requires the preference datastore. I have created multiple PR's. I want this PR to get merged first.

2022-11-29 22:42 UTC, BrayanDSO commented
This seems like a WIP and fails lint, so I'm going to draft it to clean a little the PRs queue

2023-10-20 18:03 UTC, closed without merging