Migrate FlashCardsContractto kotlin
ankidroid/Anki-Android pull request #12232
Opened 2022-08-29 17:31 UTC by lukstbit

## Purpose / Description

Migrates FlashCardsContract.java to kotlin following the migration guide.

For reviewers:

While the code migration was trivial the documentation failed completely as snippets of code and the tables failed to render. KDoc apparently isn't able to show tables so I had to change the docs to use ``` which keeps the indentation and manually create the tables. I think it looks pretty decent but it has two issues: we can't  reference other classes(with brackets like using [Note] ) and we can't create links inside the triple ` blocks. These two issues can be seen in the table from the documentation for the Note object.

I added two cleanups on the main FlashCardsContract object(in a TODO as we don't have the annotation here), one for the usual ide lint cleanups and one as an improvement for the code in this module with kotlin's explicitapi mode (see https://kotlinlang.org/docs/whatsnew14.html#explicit-api-mode-for-library-authors )

## How Has This Been Tested?

Ran the tests.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-29 22:40 UTC, david-allison requested changes
The main documentation looks better now in my opinion.

There's one question about moving the database structure links around, but this looks good

I do worry about the potential API changes, but we are calling this a 'major' version bump, so I'm happy

2022-08-29 22:40 UTC, david-allison commented on api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
> +     * long   | DATA   | read-only  | see [main documentation](https://github.com/ankidroid/Anki-Android/wiki/Database-Structure)
These links don't work, as they're within code blocks

2022-08-30 10:25 UTC, lukstbit commented on api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
> +     * long   | DATA   | read-only  | see [main documentation](https://github.com/ankidroid/Anki-Android/wiki/Database-Structure)
Yes, I mentioned this in the origin message. What do you have in mind?
I was changing it to:

> _See more at https://github.com/ankidroid/Anki-Android/wiki/Database-Structure_

2022-08-30 12:11 UTC, david-allison commented on api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
> +     * long   | DATA   | read-only  | see [main documentation](https://github.com/ankidroid/Anki-Android/wiki/Database-Structure)
That works

2022-08-30 13:48 UTC, david-allison approved these changes

2022-09-02 16:33 UTC, mikehardy commented
Just tagging @hanpingchinese with another note that the underlying AnkiDroid API should undergo integration testing with your app on next release. We are not changing anything - *we think* - but simply converting it to Kotlin means there may be null/non-null changes that might affect you and other API users

2022-09-02 16:34 UTC, mikehardy approved these changes
Seems fine - thank you for this!

2022-09-02 16:55 UTC, merged