refactor: Convert SchedV2 to Kotlin   @david-allison
ankidroid/Anki-Android pull request #12240
Opened 2022-08-30 03:03 UTC by david-allison

2022-08-31 06:17 UTC, lukstbit requested changes
Finally managed to review this, looks good with some minor cleanups.

2022-08-31 06:17 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt
> +import com.ichi2.libanki.Utils.ids2str
Please revert the imports for these two methods from Utils.

2022-08-31 06:17 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt
> +        val allDecksSorted = ArrayList<DeckTreeNode>()
@KotlinCleanup("simplify with map {}")

2022-08-31 06:17 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt
> +    private fun _rescheduleGraduatingLapse(card: Card, early: Boolean) {
@KotlinCleanup("simplify with scope function on card")

2022-08-31 06:17 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt
> +        card.ivl = _graduatingIvl(card, conf, early)
@KotlinCleanup("simplify with scope function on card")

2022-08-31 06:17 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt
> +    protected open fun _resetRevCount(cancelListener: CancelListener?) {
@KotlinCleanup("see if the two versions of this function can be combined")

2022-08-31 06:17 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt
> +        val dict = JSONObject()
@KotlinCleanup("simplify with return and scope function on dict")

2022-08-31 06:17 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt
> +        val dict = JSONObject()
@KotlinCleanup("simplify with return and scope function on dict")

2022-09-01 03:58 UTC, lukstbit approved these changes
LGTM

2022-09-02 16:37 UTC, mikehardy approved these changes
incredible

2022-09-02 17:28 UTC, merged