refactor: Cleanup: CustomTabActivityHelperTest
ankidroid/Anki-Android pull request #12241
Opened 2022-08-30 03:36 UTC by david-allison

2022-08-31 03:10 UTC, lukstbit requested changes
Looks good, one minor issue.

2022-08-31 03:10 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/compat/customtabs/CustomTabActivityHelperTest.kt
> +        getValidTabHandler().apply {
There's no need for this apply function, the three lines can be inlined.

2022-09-01 00:31 UTC, BrayanDSO approved these changes

2022-09-01 02:52 UTC, lukstbit approved these changes

2022-09-01 03:03 UTC, merged