[Cleanup] Removed Android 4.2 proguard workaround
ankidroid/Anki-Android pull request #12255
Opened 2022-08-31 13:56 UTC by n1snt

## Purpose / Description
[This](https://github.com/ankidroid/Anki-Android/pull/3942) workaround was initially implemented for app crashing on Samsung devices on Android 4.2.
We are currently only supporting API 21+ (Android 5.0) so there is no need for this workaround now & this can be removed.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-31 14:21 UTC, mikehardy requested changes
Interesting!

This is a revert of only a third the proguard stuff from the PR you link

The PR you link - that PR: 1) *turned on proguard* 2) then disabled a bunch of stuff 3) logged an error if Samsung devices still had a problem

Here, you have undone item 2 - which means that *if* proguard runs, it will now run almost fully enabled, a huge functional difference in what happens while building release builds

But item 1 was not reverted, so proguard will now run: https://github.com/ankidroid/Anki-Android/blob/298c5e6b94b31ff3106d389cb238dafdcb149d82/AnkiDroid/build.gradle#L105

So this is a big change in how release builds are minified.

You have deleted the "Testing" section of the PR template, where I would expect to see a description of how you turned on minifyEnabled in debug builds so that you could see what the differences were, you compared apk size before/after, looked at the mapping file, checked all the functionality in the app to make sure it did not crash on missing (shrunken) implementations of things 

Without solid testing, minify/proguard errors are a really really common source of  crashes in apps, and they can happen almost anywhere in the app so they require really solid testing.

Without that testing I'm afraid touching these options is not safe.

2022-09-02 04:12 UTC, n1snt commented
I'll test it with proguard enabled on a few devices & report back. 
Will also try to report back the differences in size in a few days.
If not we can set minifyEnabled as false.

2022-09-02 12:37 UTC, mikehardy commented
> If not we can set minifyEnabled as false.

This will likely also have an effect, as it may not strip out unused library code, so it would also need a size comparison

This stuff is really subtle!

2022-09-03 15:05 UTC, oakkitten commented
I suggest also checking if switching on R8's [full mode](https://stackoverflow.com/questions/58726616/what-really-r8-full-mode-do-aggressive-optimizations) will cause any issues. That got me a 13% reduction in APK size for free! (After I got Google to fix a bug in R8.)

Touching anything related to R8 can cause super weird crashes. You basically want to test all API versions on as many devices as possible, and you want to test as much of what the app can do as possible, especially anything related to crypto and serialization. Also a few times I got reports of crashes that I also couldn't reproduce, that was fun dealing with.

Also, enabling “minification” will IIRC enable obfuscation, which can significantly reduce APK size but also it makes tracebacks unreadable. R8 produces mappings that can be used to decode the tracebacks, and Google Play Console can also understand them. Still, not enabling obfuscation makes life a little bit easier eh.

2022-11-26 23:34 UTC, mikehardy commented
This is still useful, it just requires really careful testing. I'd prefer to have the bugfix release cycle for 2.16 done first and tackle this early in the 2.17 cycle if possible

2022-11-27 20:44 UTC, n1snt commented
I'm a bit busy at the moment, will get back to fixing this as soon as I get some time free.

2023-01-04 13:33 UTC, n1snt commented
I'll start working on this issue again as I am done with my exams now.

2023-01-04 13:34 UTC, n1snt commented
So the first rule tells Proguard to keep all class attributes. 
The second rule tells Proguard to keep all classes that do not match a set of specified patterns, except for certain classes that are listed explicitly. 
The third and fourth rules tell Proguard to keep certain specific classes. 
The remaining rules tell Proguard to disable specific optimizations and not generate a warning or note messages for specific patterns.

2023-02-16 02:38 UTC, david-allison commented
`ActionBarOverflow` has just been removed, so the rules related to it can go.

2023-02-24 17:18 UTC, n1snt commented
### Updates: 
_(Just started work on this again)_

1. 
These lines do not seem to do anything:
```
-keep class !android.support.v7.view.menu.**,!android.support.design.internal.NavigationMenu,!android.support.design.internal.NavigationMenuPresenter,!android.support.design.internal.NavigationSubMenu,** {*;}
-keep public class android.support.v7.internal.view.menu.** { *; }
```
Because android.support packages are deprecated in favour of androidx. Source: https://developer.android.com/topic/libraries/support-library/packages

2. 
`-keepattributes **`
This option preserves all non-class attributes of classes and class members in the processed output. This means that all attributes except for those explicitly excluded by other directives will

3.
```
-dontpreverify
-dontoptimize
-dontshrink
```
These lines completely disable Proguard and do not perform any optimization. These directives instruct Proguard to skip obfuscation, optimization, and preverification steps, effectively disabling Proguard.
 
4. 
```
-dontwarn **
-dontnote **
```

The "-dontwarn **" and "-dontnote **" directives in a Proguard configuration file instruct Proguard to suppress all warning and note messages that would otherwise be generated during the processing of the input.
The "-dontwarn" directive tells Proguard not to issue warnings for any classes or members that it encounters during processing, while the "-dontnote" directive tells Proguard not to issue any informational notes.

### So wasn't proguard disabled using this configuration?

2023-02-25 22:12 UTC, mikehardy commented
I believe it is *mostly* disabled, however I seem to remember that the debug APK vs the release APK was quite a different size indicating there is still part of the system enabled and "helping" (from perspective of reducing APK size delivered to device).

Ideally we would enable as much of it as we can, but without causing crashes - again to reduce size of transfer and install size on device

2023-02-28 18:43 UTC, n1snt commented
In the release apk it seems like R8 mode mentioned by  @oakkitten is enabled for some reason.

2023-03-15 06:14 UTC, n1snt commented
Commenting to keep this open.

2023-04-05 08:37 UTC, closed without merging