Switch JDK in GitHub Actions from adopt to temurin
ankidroid/Anki-Android pull request #12260
Opened 2022-08-31 19:13 UTC by RSBat

## Pull Request template

## Purpose / Description
According to the [docs](https://github.com/marketplace/actions/setup-java-jdk#supported-distributions)

> Adopt OpenJDK got moved to Eclipse Temurin and won't be updated anymore. It is highly recommended to migrate workflows from adopt to temurin to keep receiving software and security updates. See more details in the [Good-bye AdoptOpenJDK post](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/).

## Fixes
Fixes #11992 

## Approach
Replaced all uses of `adopt` with `temurin`

## How Has This Been Tested?

Tested by running actions several times in my fork [here](https://github.com/RSBat/Anki-Android/actions?query=branch%3Ajdk-temurin++).

## Learning (optional, can help others)

I found it by accident, so I have no ideas how to track such deprecations. AnkiDroid already uses dependabot for GitHub actions, but it didn't do anything either.

For an overview of different JDKs there is [whichjdk.com](https://whichjdk.com).

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-08-31 19:24 UTC, n1snt commented on .github/workflows/lint.yml
>        - name: Configure JDK 1.11
I think this string needs to be updated from `JDK 1.11` to `JDK 11`.

2022-08-31 21:08 UTC, david-allison approved these changes

2022-08-31 21:08 UTC, david-allison commented on .github/workflows/lint.yml
>        - name: Configure JDK 1.11
Check with @mikehardy then let's split it out into a separate issue

2022-08-31 21:09 UTC, david-allison commented
Thanks!!

2022-09-01 17:20 UTC, mikehardy requested changes
Thanks for this - @n1snt noticed the docs are now out of date and I left a comment regarding the same. In general of course this is the right functional change though, thank you

2022-09-01 17:20 UTC, mikehardy commented on .github/workflows/lint.yml
>        - name: Configure JDK 1.11
I think it can just go in the same PR, separate commit or same commit - it's just a "documentation" change. In fact what would be ideal is to just remove the version from the name so it is future proof. No need to churn on it, just "setting up JDK" is a sufficient name

2022-09-02 10:44 UTC, RSBat commented on .github/workflows/lint.yml
>        - name: Configure JDK 1.11
I've removed version number from this but it is still present in the next action. Should I rename it to something like "Verify JDK version"?

2022-09-02 13:05 UTC, mikehardy approved these changes
I think the verify action is okay, it is specifically geared towards checking the version since there was a problem way back where we were starting to move away from JDK8 and there were some discrepancies. Not sure that even applies anymore, honestly we should probably delete it and just trust the action, but this PR is good enough to go I think

Thanks!

2022-09-02 13:05 UTC, merged