[GSoC] Migrated CollectionTask.UpdateMultipleNotes to Coroutines
ankidroid/Anki-Android pull request #12272
Opened 2022-09-01 08:39 UTC by divyansh-dxn

## Purpose / Description
Migrated CollectionTask.UpdateMultipleNotes to Coroutines

## Fixes
Fixes a part of #7108

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-03 23:18 UTC, Arthur-Milchior reviewed
Still a problem with the removal of progress bar

2022-09-03 23:30 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -            context.showProgressBar()
It's partially handled by the call to withProgress above, but there's room for improvement there - will leave a comment.

2022-09-03 23:30 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +
Currently this routine is divided into two parts:

1) fetch the notes and modify them
2) save the updated notes to the DB

For 2), you're using withProgress and withCol, which is great. But for 1), you're accessing the collection without withCol, and you're not showing any progress while doing so. I'd recommend the entire fetch+modify+save is wrapped in the withProgress/withCol, as that way the progress bar will also show if the fetch+modify takes too long, and access to the collection is properly guarded. That would also allow you to use the background dispatcher that withCol provides, instead of needing a separate withContext call.

2022-09-04 07:11 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +
Done one a separate PR #12311, hope to get it merged faster. On this PR that would unnecessarily be blocked.

2022-09-04 09:39 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -            context.showProgressBar()
https://github.com/ankidroid/Anki-Android/pull/12311,

2022-09-04 09:40 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    fun doInBackgroundUpdateMultipleNotes(
see #12314

2022-09-04 09:41 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
> +        fun doInBackgroundUpdateMultipleNotes(
see https://github.com/ankidroid/Anki-Android/pull/12314

2022-09-04 14:53 UTC, Arthur-Milchior commented
@divyansh-dxn you've got a conflict

2022-09-05 11:23 UTC, divyansh-dxn commented
will finally resolve when #12311 is merged

2022-09-06 01:40 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            doInBackgroundUpdateMultipleNotes(this, selectedNotes)
I'd suggest renaming this to something like `updateMultipleNotes`, as the function does not guarantee the code is run in the background (it relies on the caller to have switched to the correct context already)

2022-09-06 01:40 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
> +    shouldUpdateCards: Boolean = false // Do we intend to use it somewhere?
If it's not used by anything, better to remove it and the condition below

2022-09-06 06:56 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
> +    shouldUpdateCards: Boolean = false // Do we intend to use it somewhere?
Removing it further simplified the code and is no longer requires a separate function because it is just three lines of execution. 
But I don't want to increase the length of this PR, so added a TODO. Will do in a follow-up PR.

2022-09-06 06:56 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            doInBackgroundUpdateMultipleNotes(this, selectedNotes)
done 👍

2022-09-06 07:00 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
> -    shouldUpdateCards: Boolean = false
Removing it further simplified the code and is no longer requires a separate function because it is just three lines of execution.
But I don't want to increase the length of this PR, so added a TODO. Will do in a follow-up PR.

2022-09-06 07:05 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
> -    shouldUpdateCards: Boolean = false
My personal preference is to make such changes in the same PR, but my opinion may differ from that of AnkiDroid maintainers. Given you plan to make this change in a follow-up, the current PR seems ok to me.

2022-09-06 19:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
> -    shouldUpdateCards: Boolean = false
I find those PR already hard to review, and we often require some change because of one or two issues that blocks the remaining. Then we must read again the whole PR before merging. 
So, I personally prefer small PR, as long as I expect that the follow-up PR won't require to revert the current one.

I understand there is no unanimous decision here, and I guess if we had enough mentors that I would be confident that this could be merged and correct without my input, I'd be as happy with a single big PR than with small ones. But as long as I review, I admit I appreciate a lot being helped in saving time reviewing

2022-09-06 20:25 UTC, Arthur-Milchior approved these changes
Would love a few more notes in the commit message. Once done, I approve

2022-09-06 20:25 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -            context.hideProgressBar()
The progress bar used to be hidden before the updates of the cards. Now it's after.
To be clear, I believe this is a right choice.  But that's still worth noting the difference of behavior in the commit if you please

2022-09-06 20:25 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -        withProgress {
Can you add a comment explaining why only the part where you save the note and cards deals with a progress bar?
Getting card data from database may be long. And editing tags certainly is

2022-09-06 20:25 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
>                  .map { cardId: CardId? -> getCard(cardId!!).note() }
You can remove the ? after CardId. Typing contains only non null cards ids

2022-09-06 20:25 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
> -    shouldUpdateCards: Boolean = false // Do we intend to use it somewhere?
I'm fine with this change, as indeed it was never used and its current absence does not result from a mistake in a previous PR.

So I'd like to add to the commit message
> introduced id a1fd4336f1c8930583ff9ac846c8f2524426cdc9 and used for the first time in b9108e61d81ba0fc3f32857fb14c525814347563 it was never called with an explicit value for this variable, so it's fine to delete it.

Just so that if we ever have bugs related to editing tags, and we question whether it was introduced in this PR, we can recall what analysis was made

2022-09-07 17:11 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -        withProgress {
Actually, this is from the previous commit https://github.com/ankidroid/Anki-Android/pull/12272/commits/bf54ab16803a4d46ffbe16bc8e5248405318eab6 which replaced TaskManager.launchCollectionTask. In previous commit this behavior was same, progress was shown only when saving notes, not updating them locally. And in this commit I enhanced that by wrapping up the whole process with progressbar.

2022-09-07 17:14 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -        withProgress {
Added to commit message, should I add in code as well? I think is understandable by itself.

2022-09-07 17:18 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
>                  .map { cardId: CardId? -> getCard(cardId!!).note() }
done 👍

2022-09-07 17:19 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
> -    shouldUpdateCards: Boolean = false // Do we intend to use it somewhere?
done

2022-09-08 08:46 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -            context.hideProgressBar()
@divyansh-dxn Are you planning to address this? Needs confirmation before merging.

2022-09-08 11:03 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -            context.hideProgressBar()
I've added the comments in the commit message.

2022-09-09 09:15 UTC, ShridharGoel approved these changes

2022-09-09 09:16 UTC, ShridharGoel requested changes
Lint check is failing due to an unused import.

2022-09-10 19:55 UTC, ShridharGoel approved these changes

2022-09-10 19:55 UTC, merged