Migrate BarGraph to kotlin
ankidroid/Anki-Android pull request #12270
Opened 2022-09-01 05:23 UTC by lukstbit

## Purpose / Description

Migrates BarGraph.java to kotlin following the migration guide. No cleanups as this class is from the doomed wildplot package.

The migration tool failed completely by combining the override color property and fillColor into a single property. Had to manually fix this.
Also I needed to improve the type system in ChartBuilder to make this to build.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-01 11:32 UTC, david-allison requested changes
This was one that I had issues with, and presumed would be easier after other files were merged. 

These mirror my fixes, one MINOR issue then good to go

2022-09-01 12:12 UTC, lukstbit commented on AnkiDroid/src/main/java/com/wildplot/android/rendering/BarGraph.kt
> + * this program.  If not, see /http://www.gnu.org/licenses/>.                           *
Sorry about that.

2022-09-01 13:36 UTC, david-allison approved these changes

2022-09-02 16:38 UTC, mikehardy approved these changes
Thanks for this!

2022-09-02 17:39 UTC, merged