Use upstream's new filtered deck name pattern
ankidroid/Anki-Android pull request #12283
Opened 2022-09-02 10:32 UTC by BrayanDSO

Only possible on the new backend

## Pull Request template

## Purpose / Description
AnkiDroid filtered deck default name scheme does not follow upstream current behavior.

## Fixes
Fixes #10662

## How Has This Been Tested?

Deck picker > Three dot menu > Create filtered deck > see if the dialog follows `Filtered deck HH:mm`

![image](https://user-images.githubusercontent.com/69634269/188121216-7c3edea8-ab67-4d01-abb1-34b1a26866fc.png)

## Learning (optional, can help others)

- Can't be used with the old schema because it throws a SQlite error

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-02 10:44 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
> +            col.backend.getOrCreateFilteredDeck(0).name
To keep things clean, the GUI code should avoid accessing .backend directly - a method on CollectionV16 should be created instead, which calls the backend method. It should also use deckId=0 instead of just 0

2022-09-02 10:45 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
> +            col.backend.getOrCreateFilteredDeck(0).name
(the new method should return the full deck and not just the name, as AnkiDroid will want to take advantage of the full deck in the future and not have to create the filtered deck itself)

2022-09-02 10:55 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
> +            col.backend.getOrCreateFilteredDeck(0).name
I've added `0` as the default value for `CollectionV16.getOrCreateFilteredDeck`'s did. 

Should the CollectionV16 keep as close as possible to the backend methods they call, i.e. if the backend method doesn't have a default value, the CollectionV16 shouldn't have a default value too, or is it fine?

2022-09-02 15:56 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
> +fun CollectionV16.getOrCreateFilteredDeck(did: Long = 0): FilteredDeckForUpdate {
We have a typealias defined called DeckId for Long.

2022-09-02 23:40 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
> +    return backend.getOrCreateFilteredDeck(did)
Sorry, I wasn't clear - I meant that when calling backend methods, explicit parameter names should be used to reduce the chances of accidental breakages in future backend updates, eg

```suggestion
    return backend.getOrCreateFilteredDeck(did=did)
```

2022-09-02 23:40 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
> +            col.backend.getOrCreateFilteredDeck(0).name
There's no hard rule here - default args or a different API on the wrapping functions can sometimes make sense.  In this particular instance since the routine is designed to deal with both creating and fetching existing decks, I'm not sure I'd add a default that focuses on one of those cases, but it's not a big deal either way.

2022-09-03 00:12 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
> +    return backend.getOrCreateFilteredDeck(did)
Oh, makes sense. Idk if Kotlin has something to force using naming arguments, but if yes, it would be good for the future

2022-09-05 12:30 UTC, lukstbit commented
@dae I'm seeing:

_W/Backend$checkMainThreadOp: Op on UI thread: com.ichi2.anki.dialogs.CreateDeckDialog.showFilteredDeckDialog(CreateDeckDialog.kt:59)_

line 59 being the backend call: `(col as CollectionV16).getOrCreateFilteredDeck(did = 0).name` 

Should this be moved in the background?

2022-09-05 13:48 UTC, BrayanDSO commented
> Should this be moved in the background?

I think so. Good catch.

I'm still too ignorant on coroutines and I'm with my hands full, so I don't have much time to experiment and learn with it. If anyone has a code suggestion to put this on the background approprietely, I'd be more than thankful

2022-09-06 01:49 UTC, dae commented
Yep, good catch.

2022-09-06 16:19 UTC, lukstbit requested changes

2022-09-06 16:19 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    createFilteredDeckDialog.showFilteredDeckDialog()
I would also wrap this inside a `withProgress {}` call to show to the user that something is happening until the dialog is actually displayed:

```
withProgress {
    createFilteredDeckDialog.showFilteredDeckDialog()
}
```

2022-09-06 16:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    createFilteredDeckDialog.showFilteredDeckDialog()
I believe that `withProgress { withCol {} }` may become a common pattern in the future, so a helper would be nice perhaps. But I'll leave that for AnkiDroid's Coroutines gang

2022-09-11 09:06 UTC, lukstbit approved these changes
I added the `withProgress {}` call and I think this is good to be merged.

2022-09-18 17:05 UTC, mikehardy approved these changes
This looks good to me. Seems like the last 2 commits are integral to the thing and both small, going with squash

2022-09-18 17:06 UTC, merged