Update FAB UI for more intuitive double tapping
ankidroid/Anki-Android pull request #12280
Opened 2022-09-01 19:50 UTC by oyeraghib

## Purpose / Description
Updating FAB UI for more intuitive double tapping

## Fixes
#11121

## Approach
1. Removed all instances of `mAddNoteLayout` as we don't need that view anymore. We will handle that functionality inside the FAB.

2. Initially the FAB has the `+` icon so inside showFloatingActionMenu() when animationEnabled() is true we set the new drawable using `setImageDrawable` and this new drawable is the Add Note icon.

3. As we remove the `mAddNoteLayout` instances from the code we make sure that the `mAddSharedLayout` and `mAddDeckLayout` takes place of the previous `mAddNoteLayout`. So keeping that in mind the duration is changed.

4. Similar actions are performed with `mAddSharedLayout` and `mAddDeckLayout` inside closeFloatingActionMenu() where `translationY` and `duration` is changed keeping in mind that we replace the position earlier occupied by the `mAddNoteLayout`.

5. In `closeFloatingActionMenu` we again call the `setImageDrawable` and this time to use the `+` icon when the user tries to close the FAB

6. Also added icon for Add Note in `onDoubleTap` and `onUnconfirmedSingleTap` which makes sure that the icon does not shows `+` when we perform the respective actions.

## How Has This Been Tested?
Manually tested on my Physical Device

- Before

https://user-images.githubusercontent.com/40427461/187999753-8305ecad-b309-41ac-b93b-4cbcf0632bad.mp4

- After

https://user-images.githubusercontent.com/40427461/187999843-d8db89da-e046-409c-bb64-bb94ae1d6095.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-01 20:03 UTC, david-allison requested changes
Some pending discussion on the Discord.

Current feedback: we need a label for the action.

2022-09-10 09:09 UTC, oyeraghib commented
> I suggest making the Fab _only_ add new notes. Other actions can be moved to the menu or to the bottom of the deck list.
> 
> Alternatively, remove the fab entirely and put the Add note action into the navigation drawer. If we do that, we could also make it possible to leave the Add note activity without saving changes; you could leave it and come back and see your unsaved input restored.

Sounds like a decent new change. Should make it as a new issue, so that everyone can have their views before someone even start to work on it.

2022-09-10 13:56 UTC, oyeraghib commented
Unit Tests are failing because of removal of Add Note Layout from DeckPickerFloatingActionMenu

2022-09-10 13:58 UTC, oyeraghib commented
This is how it looks currently :

https://user-images.githubusercontent.com/40427461/189486678-910613cb-8e40-4093-a937-3199a54365c5.mp4

2022-09-10 23:35 UTC, BrayanDSO commented
Only saw the video / haven't looked at the code deeply.

1. David's request about keeping the label wasn't addressed
2. Tests fail
3. Indigo doesn't look good to me and won't match Plain, Dark and Black themes. I suggest creating an attribute and set it on each. `themePrimaryDark` should be good for the day themes and `themePrimaryLight` for the night themes should be good. If any of them doesn't exist, you can create it or propose another

2022-09-11 09:10 UTC, oyeraghib commented
@BrayanDSO I am sorry but I didn't understood it "We need label for the action". Can you explain like what has to be done for this or what does it mean ?

2022-09-15 23:00 UTC, oyeraghib commented
**This is how it looks currently :** 

https://user-images.githubusercontent.com/40427461/190522960-a8f72a0b-ebdb-4393-b0b0-07a9107bc539.mp4

2022-09-15 23:15 UTC, david-allison requested changes
Video looks great! One initial question on code style

2022-09-15 23:15 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
> +    fun closeFloatingActionMenuCaseTwo() {
`CaseTwo` provides no meaning

Is there any way to combine this with the "normal' case? For example:

`fun closeFloatingActionMenu(applyRiseShrinkAnimation: Boolean = false)`

2022-09-15 23:38 UTC, oyeraghib commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
> +    fun closeFloatingActionMenuCaseTwo() {
Great feedback. Thanks

2022-09-17 11:44 UTC, BrayanDSO commented
It is a little bugged on `Plain` theme. A white halo/ripple persists after tapping the button. Tested on API 31 device and API 25 emulator

![image](https://user-images.githubusercontent.com/69634269/190854813-8418b1df-01fb-4c23-9d76-65699e5511be.png)

2022-09-20 22:40 UTC, oyeraghib commented
@BrayanDSO I checked it on my API 29 device and it doesn't seem to be there. 

![plain theme](https://user-images.githubusercontent.com/40427461/191377136-beadf94e-c3b0-43d4-80ea-09ea2cbae6e7.png)

Can you try checking on the build without this PR. As far as I know, I did not introduced anything which might have caused something like (`halo`) this. But still I would like to know if anyone else can also check this up and let me know.

2022-10-18 19:24 UTC, oyeraghib commented
My apologies for being late on this one. So finally fixed the halogen artifact being shown on Plain themes ( I found it while running the app on Android 13 physical device ).

Before : 


https://user-images.githubusercontent.com/40427461/196524715-77954d8c-683b-4ae4-8489-7255d843282d.mp4


After : 


https://user-images.githubusercontent.com/40427461/196523959-f7d34d8b-fb4f-4ded-a52e-be2bcf03af2f.mp4


The reason : 
That halogen icon was Android's material shadow artifact, which comes on translucent backgrounds ( therefore it was only visible on the Plain themes - because on pressing the FAB for plain themes we use a different color for background which has lower opacity. 

One of the solutions for it on SO mentioned the use of libraries : https://stackoverflow.com/questions/70227950/how-can-we-fix-the-elevation-shadows-on-transparent-translucent-views-without-ch
which I thought would not be a good decision considering we only need it inside FAB. So the most ideal solution which I found for it was to make the background color of FAB opaque (in plain themes - on pressing the FAB) which fixes the issue.

Also added couple of animation tweaks ( by updating the durations, translations etc) to make animation look more smoother.

2022-10-30 17:36 UTC, BrayanDSO commented
Question: do we still need to have a `DoubleTapListener` set up after this PR?

2022-11-05 06:21 UTC, Arthur-Milchior commented
One meta advice, @oyeraghib: you can update your initial PR message. That would be great so that it always has the most up to date video, so that a new reader, or someone who forgot what this PR contains, know in what state the issues currently is.

Regarding the potential action in the FAB: I really want to keep "shared deck" in it. Because the FAB is probably the most obvious things on a first openining of the application, when the user is trying anki* for the first time with us. And so, ensuring they get an easy way to find some shared deck, and try the app without having to create their own cards immediately seems very important to me.
Plus, if we were to remove the FAB, we should change the message shown when the collection is empty

2022-11-05 08:18 UTC, oyeraghib commented
@Arthur-Milchior Thanks for the feedback. I have updated the PR message with updated before and after videos. Regarding the FAB, I agree with your view 
> The FAB is probably the most obvious things on a first opening of the application, when the user is trying anki* for the first time with us. And so, ensuring they get an easy way to find some shared deck, and try the app without having to create their own cards immediately seems very important to me.

2023-02-22 17:46 UTC, david-allison commented
needs rebasing onto `mai` & de-conflicting

2023-02-26 20:24 UTC, oyeraghib commented
> needs rebasing onto `main` & de-conflicting

made the required changes.

2023-02-27 16:56 UTC, david-allison approved these changes
Tested on API 21 emulator, looks great!

Implementer's choice: I don't like the instant change in color if the user has disabled animations and would rather it didn't occur

2023-03-03 07:11 UTC, oyeraghib commented
> Tested on API 21 emulator, looks great!
> 
> Implementer's choice: I don't like the instant change in color if the user has disabled animations and would rather it didn't occur

To me it makes bit of sense in a way - that it tells the user that functionality of that button has been changed. For users who have been using AnkiDroid for long time might press it again (thinking it's a cross symbol) to close it . A bit of change in color can be a reason of focus and make them see that pressing it again will open the note instead of closing it.

2023-03-04 16:01 UTC, Arthur-Milchior approved these changes

2023-03-04 16:13 UTC, Arthur-Milchior commented
I missed the change in color. Thanks David for catching it.
I'll agree with David here. 

Some people, in particular on e-ink device, really care about the lack of animation. I believe that noting a change in behaviour does not justify the cost for them. After all, it's really not clear they'll notice the color started changing. And in the worst case, they may learn very quickly that the behavior changed

2023-03-04 16:24 UTC, david-allison submitted a review, later dismissed
Okay, with two agreements, I'll block on fixing the color change if animations are disabled.

2023-03-05 18:17 UTC, oyeraghib commented
Updated with discussed changes.

After updating : 

https://user-images.githubusercontent.com/40427461/222978128-655dd0e2-c194-4875-be8e-92cf96075eec.mp4

2023-03-05 18:48 UTC, david-allison commented
I have animations disabled in the Developer settings, this doesn't handle that case.

2023-03-05 19:01 UTC, oyeraghib commented
@david-allison do you have any idea if there already defined function in AnkiDroid that can be used to check device's animation status ? Or should I be writing a new one.

2023-03-05 20:29 UTC, oyeraghib commented
I am not very experienced with testing at the moment. Seems like tests are failing due to adding that function which returns the status of ( if device's animation ) is enabled or not. Any suggestions how can I use it inside the 'DeckPickerFloatingActionMenuTest.kt' to make tests pass.

2023-03-05 20:38 UTC, mikehardy commented
I believe it is a preferences setting, settings -> advanced -> safe display mode

And then there is a key in preferences (safeDisplay I think?) you may check

2023-03-05 22:37 UTC, david-allison commented
I don't believe we have the functionality yet. 

To enable: https://www.androidpolice.com/how-to-speed-up-animations-on-your-android-phone/

2023-03-06 20:35 UTC, david-allison commented
> > I don't believe we have the functionality yet.
> > To enable on your device: https://www.androidpolice.com/how-to-speed-up-animations-on-your-android-phone/
> 
> In developer options we have 3 animations. "Window animation", "Transition animation" and "animation duration". @david-allison may I know which of the following you have disabled so you are seeing the color change?

All 3

2023-03-11 18:25 UTC, oyeraghib commented
> All 3
> 
> EDIT: Tried again. Failed with the same error as in the unit tests:
> 
> ```
> 
> 2023-03-04 03:49:22.072 19988-19988 MessageQueue-JNI        com.ichi2.anki.debug                 E  android.provider.Settings$SettingNotFoundException: window_animation_scale
>                                                                                                     	at android.provider.Settings$Global.getInt(Settings.java:15261)
>                                                                                                     	at com.ichi2.anki.DeckPickerFloatingActionMenu.deviceAnimationEnabled(DeckPickerFloatingActionMenu.kt:69)
>                                                                                                     	at com.ichi2.anki.DeckPickerFloatingActionMenu.showFloatingActionMenu(DeckPickerFloatingActionMenu.kt:88)
>                                                                                                     	at com.ichi2.anki.DeckPickerFloatingActionMenu.access$showFloatingActionMenu(DeckPickerFloatingActionMenu.kt:33)
>                                                                                                     	at com.ichi2.anki.DeckPickerFloatingActionMenu$1.onUnconfirmedSingleTap(DeckPickerFloatingActionMenu.kt:279)
>                                                                                                     	at com.ichi2.anki.ui.DoubleTapListener$detector$2.onSingleTapUp(DoubleTapListener.kt:86)
> ```

@david-allison please try with latest commits if possible and let me know if it is having any issues

2023-03-11 23:13 UTC, Arthur-Milchior reviewed
I tested manually. Both setting the devs settings to 0, and enabling the "safe display". Both seemed to work fine for me. So, fine for the result. 
Some nits, and I'd love to understand why you didn't use the method "animationDisabled" instead of creating a new one. That's at the very least worth a code comment to explain when you should use which one

2023-03-11 23:13 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
> +                if (areSystemAnimationsEnabled()) {
I don't understand why you don't just use `animationEnabled` that is already defined. If there is a reason, please document it.

2023-03-12 06:17 UTC, oyeraghib commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
> +                if (areSystemAnimationsEnabled()) {
`animationEnabled` gives the (`boolean`) value based on the safe display settings inside the AnkiDroid app. 
`Window animation`, `Transition animation` and `Animation duration scale` are phone's animations from developer's options. 

That's why we needed to create a new function which gives functionality based on Device's animations.
Sure, documenting it there.

2023-03-12 11:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
> +                if (areSystemAnimationsEnabled()) {
So, yeah, I understand that we are checking different things. You're checking the android settings instead of the ankidroid setting.
My question is: why, for the first time ever, do we want to consider developer's options in Android instead of considering the AnkiDroid option? Is it a request from some user? Is it because the fab coloring require a different treatment for technical reason I don't know of? 
Was this discussed somewhere?


My understanding is that the developer settings are useful for you to test manually. To see what would be the result if you were on an e-ink device (assuming you are not already on an e-ink device). But that's not something we ever took into account in our code. And I believe if we start doing so, it should be written somewhere what changed, why didn't use those options before. Why we keep code that don't consider those developer options but consider the ankidroid settings

2023-03-12 15:47 UTC, oyeraghib commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
> +                if (areSystemAnimationsEnabled()) {
@Arthur-Milchior this was discussed in the above comments. Check from here : https://github.com/ankidroid/Anki-Android/pull/12280#issuecomment-1455171508

2023-03-26 17:25 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
> +                if (areSystemAnimationsEnabled()) {
This link to David's comment
> I have animations disabled in the Developer settings, this doesn't handle that case.

I don't understand how this answer my question. If the answer is below, I don't easily see it.
In any case, given that it seems non trivial, and requested discussing it, I believe that it's at the very least necessary to add the comment in the code. Potentially some comment in the commit message, but given that this PR will be squashed (I assume), this would be hard to do unless you just re do the list of commits.

2023-03-26 17:30 UTC, Arthur-Milchior commented
Sorry, you got a resolve conflict. Our fault, given two weeks without answer. Admittedly, scoped storage, as you may know, have priority.
I answered your answer. I admit personally, I still don't understand. So I'll either wait for a comment in the code explaining away my surprise, or having someone who understand your code to review it, sorry.

2023-03-30 08:47 UTC, oyeraghib commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
> +                if (areSystemAnimationsEnabled()) {
@Arthur-Milchior Yes I surely understand that scoped storage is a high priority and I don't mind waiting more for this PR to be merged. Regarding the animations from the Android developer's settings, I agree we haven't used it before. But @david-allison mentioned that the PR should handle the case in which animations are disabled from developer's settings.

Additionally I can add a comment stating the reason why the function was added. But would wait for @david-allison feedback to make any changes further.

2023-04-25 21:28 UTC, oyeraghib commented
Please open - PR requires a review.

2023-04-25 21:29 UTC, david-allison commented
Done, thanks! Please resolve the conflicts

2023-05-05 09:16 UTC, oyeraghib commented
@david-allison I have resolved the conflicts and rebased on current `main` . Please review if possible.

2023-05-17 11:48 UTC, BrayanDSO commented
The rise and shrink animation persists even with dev options animation settings disabled

https://github.com/ankidroid/Anki-Android/assets/69634269/232d3a08-e4cf-4ba1-8703-ddc595116df5

2023-05-29 16:39 UTC, BrayanDSO commented
When I tap an option other than `add`, the add button reverts temporarily to the `+` button. Is this avoidable?


https://github.com/ankidroid/Anki-Android/assets/69634269/f3567a36-110c-423d-840f-07aa37744d84

2023-05-29 16:44 UTC, oyeraghib commented
Hmm Interesting. Will check and update, if we can possibly stop it from happening

2023-05-29 20:35 UTC, oyeraghib commented
@BrayanDSO so ideally what behavior are we expecting here?
Like when any of the options are selected, we need to close the FAB right?
So ideally we are doing it at when the option is selected. When let's say shared deck is selected we bring back the FAB to it's normal state. What other behavior can we use here.. looking for suggestions.

Similar goes for Create Deck option. If we plan to close the FAB when a dialog is shown on UI, we would need to do it in front of the user ( with or without animation ). We can leave the FAB open as it is but that might look weird. 
Let me know your thoughts.

2023-06-09 23:23 UTC, BrayanDSO commented
Here I don't want the `+` button blinking just before opening the new activity. So if someone taps the shared deck download button, it will simply open the new activity, and have it closed/closing when they are back to the deck picker

2023-06-10 14:52 UTC, oyeraghib commented
@BrayanDSO please do checkout the new changes and let me know. Also waiting for final review from @david-allison

2023-06-10 16:43 UTC, BrayanDSO approved these changes
LGTM. David has been absent in the past few weeks and I don't want to delay this further (PR is from september 2022!). Any changes can be made on other PRs

2023-06-10 16:43 UTC, merged

2023-06-10 18:54 UTC, oyeraghib commented
Awesome!! 💯

2023-06-11 07:11 UTC, lukstbit commented
I'm leaving my opinion here for history:

I don't think this is an improvement. The main action as the fab instead of x really works for the calendar app because creating an event is an action which the user is expected to do the majority of the times when he opens the app. I don't think this would be the case for our "Add note" action.