Make some Browser variables lateinit
ankidroid/Anki-Android pull request #12292
Opened 2022-09-02 22:59 UTC by Arthur-Milchior

I was spending to much time reading this code with plenty of pointless !!

2022-09-02 23:37 UTC, BrayanDSO approved these changes
LGTM

2022-09-03 14:49 UTC, david-allison requested changes

2022-09-03 14:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -    var mDeckSpinnerSelection: DeckSpinnerSelection? = null
This is null if `onCollectionLoaded` has not executed. It's not guaranteed to be a sync call in `onCreate`

2022-09-03 14:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        cardsListView = findViewById(R.id.card_browser_list)
This should be moved to `onCreate` and then this is a good change

2022-09-03 14:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    lateinit var cardsAdapter: MultiColumnListAdapter
ditto: this is nullable before `onCollectionLoaded`

2022-09-03 14:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -    private var mRestrictOnDeck: String? = null
ditto: `onCollectionLoaded` is not guaranteed to be called synchronously for the CardBrowser

2022-09-03 23:43 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -    var mDeckSpinnerSelection: DeckSpinnerSelection? = null
I think we need to go back a step.

With `lateinit` my understanding is that we are guaranteeing that the variable is only used after it has been initialized, and that we accept the risk. It seems to me that in our case `onCollectionLoaded` is as relevant as `onCreate` as far as function that are meant to be called during the start of the object life, before more interesting actions. So anything initialized there is relevant as lateinit.

On a more concrete level, moving this variable to lateinit don't add any risk compared to current code. Each access to it is through !! and we never ever check whether it's null or not beforehand. So if there is a risk that this value is accessed before onCollectionLoaded occurs, this risk is as present before and after this change. The only difference is that the risk is now indicated in the only symbol `lateinit` instead of on each call

I won't answer to similar remarks as my answer would be similar

2022-09-04 02:07 UTC, david-allison commented
unit tests are failing

2022-09-04 15:11 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        cardsListView = findViewById(R.id.card_browser_list)
Once move to `onCreate` the tests fails. It seems that it fails to find the view.

2022-09-04 17:45 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -    var mDeckSpinnerSelection: DeckSpinnerSelection? = null
@ankidroid/reviewers - to comment, this is likely controversial.

`lateinit` is used to make a nullable variable non-null, even if it's not instantiated in the constructor.

`onCollectionLoaded` is a bad pattern: it can be called at any time in the UI lifecycle (or not called at all). Functionality such as `onCreateOptionsMenu` cannot rely on `onCollectionLoaded` having been called for example. AnkiDroid can be launched into `CardBrowser`

We should work on rearchitecting this, but I don't have the capacity right now.

In the context of the activity, there is no guarantee that `onCollectionLoaded` will ever be called. We want to warn the developer that the variables that they're accessing have the ability to be null, so they can make appropriate decisions about whether they want to use `!!` or not.

Outside the context of the Activity, we can assert that these variables are non-null via the type system, but not inside the Activity.

This change adds risk by telling developers 'don't worry about the Anki lifecycle when accessing these variables', which is a major cause of bugs

2022-09-18 03:11 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -    var mDeckSpinnerSelection: DeckSpinnerSelection? = null
I have to agree with David here. onCollectionLoaded may never be called and historically we crash because of it, in a variety of ways. Faking non-null in the type system with lateinit is a form of pretending, and the crash system doesn't pretend unfortunately

2022-09-18 09:05 UTC, closed without merging