refactor: Convert Sched to Kotlin
ankidroid/Anki-Android pull request #12301
Opened 2022-09-03 14:57 UTC by david-allison

2022-09-03 15:52 UTC, lukstbit requested changes
Looks good, just some minor cleanups.

2022-09-03 15:52 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +    override fun _fillNextCard(): Array<CardQueue<out Card.Cache?>> {
@KotlinCleanup("simplify fun with when")

2022-09-03 15:52 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +    override fun _resetLrnCount(cancelListener: CancelListener?) {
@KotlinCleanup("see if these functions can be combined into one")

2022-09-03 15:52 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +    override fun _resetRevCount(cancelListener: CancelListener?) {
@KotlinCleanup("see if these functions can be combined into one")

2022-09-03 15:52 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
>          if (ease == Consts.BUTTON_TWO) {
@KotlinCleanup("simplify with when")

2022-09-03 15:52 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +    private fun _adjRevIvl(idealIvl: Int): Int {
@KotlinCleanup("simplify fun")

2022-09-03 15:52 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +        val dict = JSONObject()
@KotlinCleanup("use apply with dict")

2022-09-03 15:52 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +        val dict = JSONObject()
@KotlinCleanup("use apply with dict")

2022-09-03 15:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
>          if (ease == Consts.BUTTON_TWO) {
IDE lint

2022-09-03 16:49 UTC, lukstbit approved these changes

2022-09-04 02:24 UTC, Arthur-Milchior reviewed
I probably missed some cleanup, this class is incredibly long. (And I plead guilty for part of it)
Still, I believe a bunch of cleanup that may improve code eventually

2022-09-04 02:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
>      /* Need to override. Otherwise it get SchedV2.mName variable*/
Kotlin cleanup: don't need "get"

2022-09-04 02:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +    override fun haveBuried(did: Long): Boolean {
Kotlin cleanup maybe: transform into an expression.
This and below

2022-09-04 02:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +    override fun haveBuried(): Boolean {
KotlinCleanup: remove ": Boolean {"

2022-09-04 02:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +        return if (conf.getInt("dyn") == DECK_STD) {
Kotlin cleanup: `conf.getInt("dyn") == DECK_STD or conf.getBoolean("resched")`

2022-09-04 02:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +        var delays = conf.optJSONArray("delays")
KotlinCleanup: uses ?:

2022-09-04 02:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
>          if (delays == null) {
cleanup: uses ?:

2022-09-04 02:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +        if (card.lapses >= lf && (card.lapses - lf) % Math.max(lf / 2, 1) == 0) {
KotlinCleanup: uses `card.apply` or even define it as a member of Card. `Card._checkLeech(conf: JSONObject)`

2022-09-04 02:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +        var search = terms.getString(0)
KotlinCleanup: transform this into val

2022-09-04 02:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +        } catch (e: JSONException) {
KotlinCleanup:  remove this catch/throw.
It was only useful to ensure we don't need to explicitly throw it in the method's declaration. That's not usefuly anymore

2022-09-04 02:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
>          if (ease == Consts.BUTTON_TWO) {
KotlinCleanup: do `val interval = ` with a last `else { 0}`

2022-09-04 02:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +        card.lastIvl = card.ivl
KotlinCleanup: Either `card.apply` or even define it as `Card._rescheduleRev`.
Same for other methods rescheduling cards

2022-09-04 02:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +                        mRevQueue.shuffle(r)
KotlinCleanup: `mRevQueue(Random().apply(setSet(mToday!!.toLong()))`
 (same in schedv2)

2022-09-04 02:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +    override fun counts(card: Card): Counts {
I don't think this is an improvement

2022-09-04 02:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +                that(
This was an issue in the conversion. Fixed.

2022-09-04 02:50 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +                val parentLims = lims[Decks.normalizeName(p)]
This breaks the `Assert` below

2022-09-04 02:50 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +        var c = _getLrnCard(false)
This matched libAnki

2022-09-04 02:50 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +                card.due = Math.max((mToday!! + 1).toLong(), card.oDue)
This matched libAnki

2022-09-04 02:50 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +    override fun haveBuried(): Boolean {
Moving this to an expression does this

2022-09-04 02:50 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +        if (card.lapses >= lf && (card.lapses - lf) % Math.max(lf / 2, 1) == 0) {
I disagree that this makes the code bettter

2022-09-04 02:50 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +        var search = terms.getString(0)
This breaks `libAnki` compat

2022-09-04 02:50 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
>          if (ease == Consts.BUTTON_TWO) {
this is handled in the IDE lint

2022-09-04 02:51 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +        card.lastIvl = card.ivl
This breaks `libAnki` compat

2022-09-04 03:45 UTC, dae commented
I don't recommend expending much effort on this file, since reviewing with the v1 scheduler is no longer possible since https://github.com/ankidroid/Anki-Android/pull/11808

2022-09-04 04:13 UTC, david-allison commented
Agreed, just want to get to 0% Java so we can cut down the excess code and hopefully reduce compile times

2022-09-04 14:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +    override fun counts(card: Card): Counts {
ok

2022-09-04 14:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +    override fun haveBuried(): Boolean {
Yes, that what I meant. `haveBuried` can be replaced by an expression directly eventually

2022-09-04 14:59 UTC, merged

2022-09-04 15:00 UTC, Arthur-Milchior commented
Merged. If we don't care about cleanup because the code will disappear, no need to wait for the cleanup