tests: check if all preferences fragments don't throw on creation
ankidroid/Anki-Android pull request #12315
Opened 2022-09-04 19:18 UTC by BrayanDSO

## Pull Request template

## Purpose / Description
Depending on the changes, a preferences fragment throws on creation, which sould be only seen while running the app, so here's a test for it

## Approach
On the commits

## How Has This Been Tested?

this is a test

## Learning (optional, can help others)

Use `.commitNow` if you are looping fragments, as `commit` is async

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-04 19:33 UTC, david-allison approved these changes
LGTM, optional thoughts on refactors

2022-09-04 19:33 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferenceUtils.kt
> +        }
```suggestion
        for (fragment in fragments.filterIsInstance<SettingsFragment>()) {
            fragments.addAll(getFragmentsFromXml(context, fragment.preferenceResource))
        }
```

2022-09-04 19:33 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferenceUtils.kt
> +    }
```suggestion
    fun getFragmentsFromXml(context: Context, @XmlRes xml: Int): List<Fragment> =
        getFragmentsClassNamesFromXml(context, xml).map { getInstanceFromClassName(it) }
```

2022-09-04 19:35 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferenceUtils.kt
> +        }
I think this will change the size of the list during the iteration and throw Concurrent Modification Exception

2022-09-04 19:37 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferenceUtils.kt
> +        }
I don't believe so: `filterIsInstance` returns a `List`, not a stream

2022-09-04 19:38 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferenceUtils.kt
> +        }
Oh... I see what you're doing. Nevermind

2022-09-04 19:45 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferenceUtils.kt
> +        }
> I don't believe so: filterIsInstance returns a List, not a stream

You are right here, well thought. `fragments.filterIsInstance<SettingsFragment>()` is a different list, so no problems looping it, thanks

2022-09-04 19:47 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferenceUtils.kt
> +        }
silly question: I believe in previous code, you were modifying and iterating over the collection, which meant that the first element added from inside the loop would also be iterated over. 

Was this the intention? Because we no longer do this

2022-09-04 19:56 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferenceUtils.kt
> +        }
Before it was iterating the initial size of the list, so it wouldn't iterate the new elements. 

The results of the two approaches is the same here: 14 unique fragments

2022-09-04 20:27 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferenceUtils.kt
> +        // then loop recursively to find fragments within the children
my logic is wrong. This isn't recursive (although the result will be the same, as there are at maximum 2 levels deep of prefs screens). Drafting this

2022-09-04 21:10 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferenceUtils.kt
> +        // then loop recursively to find fragments within the children
fixed

2022-09-04 21:12 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferenceUtils.kt
> +    }
@david-allison deliberetely changed the `.map` approach back because I wanted a `MutableList` to reuse it more easily on `getFragmentsFromXmlRecursively`, and `.map` returns `.List`

2022-09-04 21:58 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferenceUtils.kt
> +    }
Could maybe use `.map {}.toMutableList()`, but it's a nitpick and I trust your judgment

2022-09-05 05:11 UTC, lukstbit requested changes
To be honest I don't like the mutable return types at all.

Also, do you plan to use the first three methods in the near future? The IDE marks them to be private and I would like to not introduce IDE lint issues with new code.

2022-09-05 05:11 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferenceUtils.kt
> +        val fragments = getFragmentsFromXml(context, xml)
The same issue with the return type. 
`fragments` could be initialized to a `mutableList()` and then use `getFragmentsFromXml().filterIsInstance<SettingsFragment>()`.

2022-09-05 05:11 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferenceUtils.kt
> +        fragments.add(HeaderFragment()) // include the initial fragment as well
You could have wrote:

```
// include the initial fragment as well
val fragments =
     getFragmentsFromXmlRecursively(context, R.xml.preference_headers) + HeaderFragment()
return fragments.distinctBy { it::class } // and remove any repeated fragments
```

to avoid the mutable types.

2022-09-05 09:36 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferenceUtils.kt
> +    fun getFragmentsFromXml(context: Context, @XmlRes xml: Int): MutableList<Fragment> {
I'd like to keep the methods separated, because I or someone else may use them later on different tests

2022-09-05 09:59 UTC, lukstbit approved these changes
Thank you!

2022-09-05 10:06 UTC, merged