Fix Title to recall what gesture the window is for
ankidroid/Anki-Android pull request #12329
Opened 2022-09-05 20:15 UTC by pratyaksh1610

## Purpose / Description
Fixed the title to recall what gesture the window is for.

## Fixes
fixes #12326

2022-09-05 21:23 UTC, BrayanDSO reviewed
Hello there. By looking at the code and based on the fact that lint fails, I assume that you haven't tested the result of your changes.

Before you push any changes you make, I'd like if you could run at least the linter (see the Development guide in the repository wiki to know how). Also, run the app, see the result of your changes on Settings > Controls, then take a screenshot and post it here.

2022-09-05 21:23 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
> +    @SuppressLint("StringFormatInvalid")
This shouldn't be necessary

2022-09-05 21:23 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
> -        entryTitles.add(context.getString(R.string.binding_add_key))
Not needed. We only want to change the dialog title, not the options names

2022-09-05 21:23 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
> +            entryTitles.add(context.getString(R.string.binding_add_gesture, ADD_GESTURE_INDEX.toString()))
Ditto

2022-09-05 21:23 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
> +                    title(context.getString(R.string.binding_add_gesture, ADD_GESTURE_INDEX.toString()).toInt())
If you look at it, you will see that ADD_GESTURE_INDEX is a int constant, not the title of the preference.

As there is a `title` property on the class you are editing, you can access and pass it as parameter here

2022-09-05 21:23 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
> +                    title(context.getString(R.string.binding_add_key, ADD_KEY_INDEX.toString()).toInt())
Ditto

2022-09-05 21:23 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="binding_add_gesture">Add gesture for %s</string>
It's probably best to discuss on the original issue which strings would be best

2022-09-06 04:46 UTC, pratyaksh1610 commented
> Hello there. By looking at the code and based on the fact that lint fails, I assume that you haven't tested the result of your changes.
> 
> Before you push any changes you make, I'd like if you could run at least the linter (see the Development guide in the repository wiki to know how). Also, run the app, see the result of your changes on Settings > Controls, then take a screenshot and post it here.

Just ran all the tests again, found that all lint tests are passing on my machine, I think lint failed due to ` @SuppressLint("StringFormatInvalid")`

2022-09-06 05:48 UTC, pratyaksh1610 commented on AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
> +                    title(context.getString(R.string.binding_add_gesture, ADD_GESTURE_INDEX.toString()).toInt())
So in the title we need to pass `ADD_GESTURE_INDEX` only.
`title(ADD_GESTURE_INDEX)`

2022-09-06 13:25 UTC, david-allison commented
> Just ran all the tests again, found that all lint tests are passing on my machine, I think lint failed due to ` @SuppressLint("StringFormatInvalid")`

You can either see the output on GitHub, or run `./gradlew lintPlayDebug ktLintCheck`

See: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#lint

2022-09-06 17:01 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
> +                    title(context.getString(R.string.binding_add_gesture, ADD_GESTURE_INDEX.toString()).toInt())
Type `this` in your IDE and it will show some options. One of them will be the class you are editing `this@ControlPreference`, so you can get the control title with `this@ControlPreference.title`. Then pass it as parameter of `context.getString`

2022-09-06 18:36 UTC, Arthur-Milchior commented
Also, can you please provide screenshot, so it's easy to see what it looks like

2022-09-07 14:09 UTC, pratyaksh1610 commented on AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
> +                    title(context.getString(R.string.binding_add_gesture, ADD_GESTURE_INDEX.toString()).toInt())
I am unable to comprehend this part, can you please explain, how it should be passed, as title should be `string`.

2022-11-04 01:45 UTC, david-allison commented
The lint check still fails, please see the linked GitHub action, or run `./gradlew lint`

2022-11-04 06:26 UTC, Arthur-Milchior commented
While it's not the main problem to solve here, generally, we try to rebase onto main, and not merge it. Don't hesitate to force push on this branch after that

2022-11-04 06:48 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
> +                    title(context.getString(R.string.binding_add_gesture, ADD_GESTURE_INDEX.toString()).toInt())
`title(text=context.getString(R.string.binding_add_gesture, ))`
Using `text=` you ensure that you can pass an explicit string.

`toInt` could not have worked. Indeed, the typing works, the trouble is that `title()`'s int is supposed to be a string resource id. The issue is that `toInt` was not a string resource id. Actually, it was not even working, since, the way `toInt` work is that `"42".toInt()` would return the number `42`. But if your string is not actually a number, then it can't create a relevant number out of it.

Personally, I'd put `val actionName = title` (in between `ADD_GESTURE_INDEX` and the `MaterialDialog(context)`, and then use this value in `title(text=context.getString(R.string.binding_add_gesture, actionName))`, I find it easier to read.

Is it more understandable @pratyaksh1610 ?

2022-11-05 03:50 UTC, Arthur-Milchior commented
By the way @pratyaksh1610 , are you still working on it?

2022-11-05 08:23 UTC, pratyaksh1610 commented
> By the way @pratyaksh1610 , are you still working on it?

I am working on it.

2022-11-06 23:47 UTC, david-allison requested changes
I don't feel we need 'add gesture/key for' in the title:

* 'Add key for Answer Button 1' -> 'Answer Button 1'
* 'Add gesture for Answer Button 1' -> 'Answer Button 1'

I feel the additional context is redundant given the user's action to get here, and the UX of the dialog. Adding more text makes the purpose of the dialog less clear as the user needs to read more to get the context

2022-11-06 23:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
> +                    title(text = context.getString(R.string.binding_add_gesture_title, actionName))
You can use `this@` to remove the need for the variable, combining this with my previous suggestion:

```kotlin
                    title(text = this@ControlPreference.title?.toString())
```

2022-11-07 00:16 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
> +                    title(text = context.getString(R.string.binding_add_gesture_title, actionName))
You can just directly refer to `title` without `this@ControlPreference`. But I actually like `actionName`, it says more about the contents that just `title`.

2022-11-07 04:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
> +                    title(text = context.getString(R.string.binding_add_gesture_title, actionName))
Right you are, thanks!

2022-11-07 14:06 UTC, david-allison approved these changes
Looks great, thanks!

2022-11-09 20:59 UTC, mikehardy approved these changes
Also looks good to me now - this is now a very small + focused change, nice

2022-11-09 21:00 UTC, merged

2022-11-10 07:49 UTC, Arthur-Milchior commented
Thanks a lot @pratyaksh1610. Using Gesture a lot, it'll really save me ... well seconds. But those are frustrating seconds.