Migrated LoadDeckCounts and LoadDeck to Coroutines
ankidroid/Anki-Android pull request #12328
Opened 2022-09-05 18:45 UTC by divyansh-dxn

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-06 13:29 UTC, david-allison reviewed
(I understand this is a draft, sorry if this is hasty)

nit: at least one of the commits didn't build: https://github.com/ankidroid/Anki-Android/pull/12328/commits/4985994e5d9ab26d5d8eb6378b279d8dd45bef4f

It's a strong aim that we do not have any commits in the git history which do not build, as this makes `git bisect` much harder to run.

Could you either:
* fix/squash the failing commit
* Request that we squash merge this pull request when

2022-09-06 14:21 UTC, divyansh-dxn commented
![Screenshot 2022-09-06 at 7 32 06 PM](https://user-images.githubusercontent.com/69595691/188659652-2f03012b-e6cf-485f-b9b4-537483d0ed43.png)

This was it 🥹

2022-09-06 20:28 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        launchCatchingTask {
Is `launchCatchingTask` required here? `onDecksLoaded` is already being called from inside launchCatchingTask.

2022-09-07 16:10 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        launchCatchingTask {
Yes, `onDecksLoaded` is called from both the launchCatchingTask above and the listener for LoadDeckCounts task.
I'm assuming this is just temporary until LoadDeckCounts is migrated( @divyansh-dxn)?

2022-09-07 16:12 UTC, lukstbit requested changes
Looks ok with the small nullability type issue below.

2022-09-07 16:12 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    val decks: List<TreeNode<com.ichi2.libanki.sched.DeckTreeNode>>? =
There's no need for `?`

2022-09-07 17:27 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        launchCatchingTask {
when LoadDeckCounts is migrated (next to this pr), onDecksLoaded will be a suspendable then we can get rid of launchCatchingTask

2022-09-07 19:21 UTC, Arthur-Milchior approved these changes
this allright to me if I understand correctly. I'd appreciate that you can confirm my understanding.

2022-09-07 19:21 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
> +fun loadDeck(col: Collection): List<TreeNode<DeckTreeNode>>? {
Thanks a lot for doing individual commit. Review can be done in 30 seconds and that's really a pleasure not to have to wonder what went where and what was deleted.

Do you want us to squash?

2022-09-07 19:21 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        launchCatchingTask {
can you please confirm that I understand correctly. If we had actually a `launchCatchingTask` inside another one, the impact would be:
* we schedule to do `AnkiStatsTaskHandler.createReviewSummaryStatistics(col, mReviewSummaryTextView)`
* `Timber.d("Startup - Deck List UI Completed")` is done immediately (in this case I guess it should be inside the `launch` too.
* the current function could probably returns slightly faster while the stats may wait slightly more to appear

Or do I misunderstand something?

2022-09-07 19:21 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    val decks: List<TreeNode<com.ichi2.libanki.sched.DeckTreeNode>>? =
Why do you put a type explicitly? It seems to work well without.

Implementor choice: Actually, you can even do `withCol(::loadDeck)` (to be honest, the more I think about it, the less I understand why it works, but it seems to work)

2022-09-07 19:21 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    onDecksLoaded(decks)
I agree this commit seems correct (even if, after so much time of AsyncTask, it seems counter intuitive to be allowed to touch UI from inside of Task).
However, I would have love a little help in the commit message, just to explain that `updateDeckListener` only deals with progress bar and `onDecksLoaded` so this commit just copy `updateDeckListener` inside this `updateDeckList` but do not delete it because it's used elsewhere in the code

2022-09-07 20:30 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        launchCatchingTask {
You've got it right.

2022-09-07 20:32 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    onDecksLoaded(decks)
Yeah, and will be deleted when LoadDeckCounts is also migrated. Which would be much simpler as we already have extracted out handler's function.

2022-09-07 20:35 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    onDecksLoaded(decks)
The commit https://github.com/ankidroid/Anki-Android/pull/12328/commits/de5ea39e1e1740a1d4bd22347125c1bc4095d6d7 exactly does the same. 
`copy updateDeckListener inside this updateDeckList but do not delete it because it's used elsewhere in the code`

2022-09-07 20:37 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
> +fun loadDeck(col: Collection): List<TreeNode<DeckTreeNode>>? {
Yes, that would make sense. All the commits individually do not add much but together it explains everything. If squashed, "Migrated LoadDeck to Coroutines" would be best suited title.

2022-09-08 04:02 UTC, lukstbit approved these changes

2022-09-08 04:52 UTC, ShridharGoel approved these changes

2022-09-08 04:53 UTC, merged