[GSoC] Coroutines migration CollectionTask.SaveCollection
ankidroid/Anki-Android pull request #12330
Opened 2022-09-06 17:56 UTC by divyansh-dxn

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-08 12:23 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt
> +    fun saveCollectionInBackground(activity: AnkiActivity, syncIgnoresDatabaseModification: Boolean = false) {
Any idea why this method is inside UIUtils? Can we move this to a better place?

2022-09-08 12:27 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt
> +    fun saveCollectionInBackground(activity: AnkiActivity, syncIgnoresDatabaseModification: Boolean = false) {
No idea why a function that schedules saving of collection in background is inside UIUtils 🙄🙄?

2022-09-08 12:29 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt
> +    fun saveCollectionInBackground(activity: AnkiActivity, syncIgnoresDatabaseModification: Boolean = false) {
That is why I've added a toto, would be good to do in the same PR with a next commit.

2022-09-08 15:28 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt
> +    fun saveCollectionInBackground(activity: AnkiActivity, syncIgnoresDatabaseModification: Boolean = false) {
I have moved the function to AnkiActivity but want to know why was it inside UIUtils, was it just went with or there was some specific reason?

@Arthur-Milchior if you have something to add.

2022-09-08 22:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt
> +    fun saveCollectionInBackground(activity: AnkiActivity, syncIgnoresDatabaseModification: Boolean = false) {
I'll play the mentor role and ask question instead of answering.
Did you investigate yourself, looking at git blame?
Last change to this line is during Kotlin migration. But you should be able to follow the track to the time it was added in java code. Then check whether it was explained, or maybe even ask the author of this code. In any case, it's nice to link to the commit number in your message so that you save the time to other people looking at it.

2022-09-08 22:51 UTC, Arthur-Milchior approved these changes

2022-09-08 22:51 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
> +): Void? {
Now that you are not inheriting anymore, you can remove the return type. It's plainly useless. Even if it means you must return `null` directly when you call `saveCollection`

2022-09-08 22:51 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt
> +    fun saveCollectionInBackground(activity: AnkiActivity, syncIgnoresDatabaseModification: Boolean = false) {
But generally, unless you find a great reason not to, I'm fine with moving this inside AnkiActivity

2022-09-09 09:13 UTC, ShridharGoel approved these changes

2022-09-09 09:14 UTC, ShridharGoel commented
Is a squash merge required here?

2022-09-09 10:10 UTC, divyansh-dxn commented
No I don't think so, because moving the function from UIUtils to AnkiActivity has to have a separate commit.

2022-09-10 19:56 UTC, ShridharGoel commented
Conflict needs to be resolved.

2022-09-10 19:57 UTC, divyansh-dxn commented
On it 👍

2022-09-10 20:13 UTC, divyansh-dxn commented
@ShridharGoel I guess can improve the error handling part here too. So will keep this one open, probably will be done by tomorrow then we can merge.

2022-09-11 08:55 UTC, divyansh-dxn commented
Ready for review, first three commits are already reviewed. Last one remains.

2022-09-11 08:56 UTC, divyansh-dxn commented
Also, earlier I thought not to squash, but I think it is okay for this one to be squashed.

2022-09-11 09:05 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +                    }
I want a second opinion here. We are only catching RuntimeException here, so if any other exception is thrown it would crash the app in background (cuz this fun is called from onStop()). When user then returns to the app, it would simply show App Crashed dialog (typical 'App Keeps Crashing' message) and user won't have any idea what happened. So either I can keep launchCathingTask and remove the try-catch which would catch and show a dialog when user returns to the app or can silently log "Exception" instead of "RuntimeException" to logcat.

2022-09-11 09:05 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +                    }
Which would be more preferred?

2022-09-11 19:35 UTC, Arthur-Milchior approved these changes

2022-09-11 19:35 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +                    }
Honestly, I’ve no idea.
Main trouble is that I can’t even guess what we are trying to catch here. What can actually occurs. 
So ideally, what I’d want is to go through git history (I suggest using `gitk` to do so, but any tools you know how to use is fine), figure out when this was added for the first time (looking at the first introduction of "Error on saving deck in background" should suffices), and read the comment to understand what we were trying to do.

If we don’t know what was going on, I’m fine with catching exactly the same thing as before and leaving your very relevant question as a separate issue.
I believe actually the issue can be generalized. We can just ask to go over each general catch (one where we catch all Exceptions, RuntimeException or even Throwable) and asses them individually. 
For this one, I believe the right things to do is to throw an Exception to Acra, so that we can learn what bugs are actually encounted, and, hopefully, correct them, or if it never occurs, remove the try/catch.
Obviously, this is blocked by actually creating releases, so it must just remains an issue. 
At best, put a todo with a link to the issue

2022-09-11 19:50 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +    fun saveCollectionInBackground(syncIgnoresDatabaseModification: Boolean = false) {
> Also, earlier I thought not to squash, but I think it is okay for this one to be squashed.

@Arthur-Milchior Not required as this is to be squashed. Actually looking the overall PR is understandable by itself.

2022-09-15 17:34 UTC, divyansh-dxn commented
Resolved conflicts

2022-09-16 17:44 UTC, divyansh-dxn commented
Had some seroius conflicts with the recent pushes, because of that I've re-made the changes but a slightly different manner.  Have exchanged commits two and three as mentioned by Arthur. 

@lukstbit @ShridharGoel , want your reivews especially on the last commit.

2022-09-16 20:56 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +                    }
Makes sense to catch `Exception` and send it to ACRA.

2022-09-17 16:44 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +                    }
Like @ShridharGoel  I would catch `Exception` there. Sending to ACRA will trigger the same issue of a dialog appearing from the background(all this time the app functioned without sending a report).

So I would say catch `Exception` and add a todo in the catch block:
```

} catch (e: Exception) {
    Timber.e(e, "Error on saving deck in background")
    // TODO should this error be reported through our error reporting service?
}
```

2022-09-17 16:45 UTC, lukstbit requested changes
Looks ok with an action required where I left a comment.

2022-09-17 17:59 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +                    }
done

2022-09-17 20:18 UTC, ShridharGoel approved these changes

2022-09-18 02:54 UTC, lukstbit approved these changes

2022-09-18 02:54 UTC, merged