Cleanup FlashCardContract for new api release
ankidroid/Anki-Android pull request #12334
Opened 2022-09-07 10:00 UTC by lukstbit

## Purpose / Description

Part of #12310.

This cleanup includes:

- fixing ide lint issues
- adding extra `@JvmField` annotations to replicate the initial static fields in java, the targets were `Uri`s and the projection arrays(without the annotations these would have ended in the final bytecode as private static field + getter method)
- as I said when I migrated the class, I enabled the [explicit api mode](https://kotlinlang.org/docs/whatsnew14.html#explicit-api-mode-for-library-authors) as this is a library project and I think would be a good addition going forward. I made the violations as warnings for now( to be able to suppress them for the other api classes) and fixed them for `FlashCardContract`. When we finish cleaning up the api module we should move from warning to strict.
This included specifying the visibility modifiers and the actual properties types(nothing to note here as we have only strings, not null Uris and not null arrays of not null strings)
- added some @ Suppress annotations for naming(_ID)  and properties not being used(I'm assuming not used but replicating upstream?)

## How Has This Been Tested?

Ran checks and tests.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-07 10:01 UTC, lukstbit commented
@david-allison Please have a look at this. I think it is ready but if you have something to add/change let me know.

2022-09-07 18:19 UTC, david-allison requested changes
Obviously a step in the right direction

This all looks good! One comment probably to be moved to a separate issue

I'm not normally strict on this, but since it's an API change, please include your relevant GitHub comments in either the code or the commit message

2022-09-07 18:19 UTC, david-allison commented on api/build.gradle
> +        freeCompilerArgs += '-Xexplicit-api=warning'
>  When we finish cleaning up the api module we should move from warning to strict.

This should be documented in the code

2022-09-07 18:19 UTC, david-allison commented on api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
> +     *       |        | Deck chooser dialog of the App       |
```suggestion
     *       |        | Deck chooser dialog of the App      |
```

2022-09-07 18:19 UTC, david-allison commented on api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
> +        public val DEFAULT_PROJECTION: Array<String> = arrayOf(
API Query - probably for new issue: is `DEFAULT_PROJECTION` intended to be mutable? We have a few of these and this appears to be an oversight. Should this be a get-only property returning a clone of the array?

It was a `String[]` before - so also mutable values, but not size.

2022-09-07 18:24 UTC, david-allison commented on api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
> +        @Suppress("MemberVisibilityCanBePrivate")
This could do with an explanation somewhere of the suppression: this is part of the default projection.

Any string constant in the default projection is valid to for a client to use in their own projection (which may be a subset of the default projection to improve performance). This exposes the individual possible values to the client

2022-09-08 04:35 UTC, lukstbit commented on api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
> +        @Suppress("MemberVisibilityCanBePrivate")
Added a comment :   _// field is part of the default projection available to the clients_

2022-09-08 04:35 UTC, lukstbit commented on api/build.gradle
> +        freeCompilerArgs += '-Xexplicit-api=warning'
Added todo in the build file.

2022-09-08 04:44 UTC, lukstbit commented on api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
> +        public val DEFAULT_PROJECTION: Array<String> = arrayOf(
>  is DEFAULT_PROJECTION intended to be mutable?

I don't know but there's no reason to have the default projection as mutable in any way.

To be honest I wouldn't use an `Array` as a return type for an API so I'm leaning towards making the projection as a read only `List<String>`. A get only property returning a clone of the private projection array is also a good option as it would  ease the transition after the new api release.

2022-09-08 17:05 UTC, david-allison commented on api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
> +        public val DEFAULT_PROJECTION: Array<String> = arrayOf(
Agreed, moved this to a separate issue, and I'd welcome this comment being made here as well

2022-09-08 17:06 UTC, david-allison approved these changes

2022-09-18 03:05 UTC, mikehardy approved these changes
Thank you for this @lukstbit !

2022-09-18 03:05 UTC, mikehardy commented
Took a conflict though, --> :cry:

2022-09-18 12:32 UTC, merged