Changed String.format to string template
ankidroid/Anki-Android pull request #12333
Opened 2022-09-07 04:55 UTC by sparkyniner

## Pull Request template

## Purpose / Description
Cleaning code and making it more readable by changing String.format to string template

## Fixes
Changed instances of string.format to string template

## Approach
It changes String.format to string template

## How Has This Been Tested?

Tested this in various pixel emulators without any problem

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-07 06:05 UTC, david-allison requested changes
This wasn't tested, please read the [docs on how Kotlin string interpolation works](https://kotlinlang.org/docs/java-to-kotlin-idioms-strings.html#concatenate-strings).

It's visible from the string formatting in the IDE that the change is incorrect.

<img width="1011" alt="Screenshot 2022-09-07 at 07 05 47" src="https://user-images.githubusercontent.com/62114487/188800925-b3db2b55-33d1-4554-ab0d-7bbcfe9ffc2d.png">


and visible in the debugger:

<img width="1140" alt="Screenshot 2022-09-07 at 07 04 16" src="https://user-images.githubusercontent.com/62114487/188800667-c0e21246-693d-441b-8c8d-2ca67a1464cd.png">


----
**changes in this PR**

* This PR contains 18 changes, please fix this:

* squash your changes to one commit
* force push to `main`

Once this PR is merged, for your next PR, branch from `main` and send a PR from that branch, this avoids the problem as `main` will then never contain additional commits not contained in `upstream`

2022-09-07 14:09 UTC, Arthur-Milchior commented
You may also want to add "Bug: #11449" somewhere in your PR message so that it's clear that it's related to this bug (and so that, from this bug, we can see that there is one PR advancing on it"

2022-09-07 14:16 UTC, Arthur-Milchior requested changes

2022-09-07 14:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -            browser.mActionBarTitle!!.text = String.format(LanguageUtil.getLocaleCompat(browser.resources), "%d", browser.checkedCardCount())
Also, you may want to avoid touching strings format that have an explicit locale, because Kotlin format don't respect them. That's why we didn't just use `browser.checkedCardCount().toString()`

2022-09-14 03:12 UTC, sparkyniner commented
> This wasn't tested, please read the [docs on how Kotlin string interpolation works](https://kotlinlang.org/docs/java-to-kotlin-idioms-strings.html#concatenate-strings).
> 
> It's visible from the string formatting in the IDE that the change is incorrect.
> 
> <img alt="Screenshot 2022-09-07 at 07 05 47" width="1011" src="https://user-images.githubusercontent.com/62114487/188800925-b3db2b55-33d1-4554-ab0d-7bbcfe9ffc2d.png">
> 
> and visible in the debugger:
> 
> <img alt="Screenshot 2022-09-07 at 07 04 16" width="1140" src="https://user-images.githubusercontent.com/62114487/188800667-c0e21246-693d-441b-8c8d-2ca67a1464cd.png">
> 
> **changes in this PR**
> 
> * This PR contains 18 changes, please fix this:
> * squash your changes to one commit
> * force push to `main`
> 
> Once this PR is merged, for your next PR, branch from `main` and send a PR from that branch, this avoids the problem as `main` will then never contain additional commits not contained in `upstream`


> This wasn't tested, please read the [docs on how Kotlin string interpolation works](https://kotlinlang.org/docs/java-to-kotlin-idioms-strings.html#concatenate-strings).
> 
> It's visible from the string formatting in the IDE that the change is incorrect.
> 
> <img alt="Screenshot 2022-09-07 at 07 05 47" width="1011" src="https://user-images.githubusercontent.com/62114487/188800925-b3db2b55-33d1-4554-ab0d-7bbcfe9ffc2d.png">
> 
> and visible in the debugger:
> 
> <img alt="Screenshot 2022-09-07 at 07 04 16" width="1140" src="https://user-images.githubusercontent.com/62114487/188800667-c0e21246-693d-441b-8c8d-2ca67a1464cd.png">
> 
> **changes in this PR**
> 
> * This PR contains 18 changes, please fix this:
> * squash your changes to one commit
> * force push to `main`
> 
> Once this PR is merged, for your next PR, branch from `main` and send a PR from that branch, this avoids the problem as `main` will then never contain additional commits not contain
<img width="373" alt="Screenshot 2022-09-14 at 8 42 03 AM" src="https://user-images.githubusercontent.com/110723606/190050194-309eb5f6-140f-462c-ad71-ee86101bc9f4.png">
ed in `upstream`

I tried to squash my changes to one commit but I'm getting this error, do you know how I can solve this or start afresh?

2022-09-14 06:51 UTC, david-allison commented
* `git reset c744c99c41f02f7f6b476c1d4cacf58ec6f86eff`
* Stash/shelve your changes
* rebase onto the current `main`
* re-apply your changes

2022-09-14 10:02 UTC, sparkyniner commented
> That's a real hole that's been dug. I'd `git reset` my way out of it
> 
> * `git reset c744c99c41f02f7f6b476c1d4cacf58ec6f86eff`
> * Stash/shelve your changes
> * rebase onto the current `main`
> * re-apply your changes
> * force push with a clean history

Thanks a lot, I was able to reduce my commit history and reduce it from 22 to 5 commits. Will start working on this issue asap .

2022-09-14 10:04 UTC, david-allison commented
Reduce it to 0 by rebasing onto master, then start

2022-09-15 10:51 UTC, closed without merging

2022-09-15 10:52 UTC, sparkyniner commented
Hello, when I deleted all my commit, this pull request closed, I'll open a new one again?