NF: uses only assertNotNull from kotlin.test
ankidroid/Anki-Android pull request #12353
Opened 2022-09-08 23:53 UTC by Arthur-Milchior

This ensure that the value is non null by contract, so we can remove ulterior !!

Replace and improve #12352

2022-09-10 23:58 UTC, BrayanDSO approved these changes
I really like the changes. The contracts help very much here.

2022-09-11 00:00 UTC, BrayanDSO commented
I believe that https://github.com/ankidroid/Anki-Android/blob/main/lint-rules/src/main/java/com/ichi2/anki/lint/rules/JUnitNullAssertionDetector.kt isn't working as expected. If it were the case, these changes should have been flagged by lint ages ago

2022-09-11 01:50 UTC, david-allison requested changes
Strong disagree (as listed in the PR this supersedes): we want one consistent method to do assertions.

Making it inconsistent in one of our most important test classes isn't a good idea

2022-09-12 13:42 UTC, BrayanDSO commented
@david-allison, in your goal of consistency, is the approach of https://github.com/ankidroid/Anki-Android/pull/12352#issuecomment-1242825257 fine?

I believe that both kotlin.test and kotlin.test.junit both have contracts

2022-09-12 16:50 UTC, Arthur-Milchior commented
Before https://github.com/ankidroid/Anki-Android/pull/12352  was merged, the IDE noted that this `assertNotNull` was used 80 times, so I thought I was being consistent. I now understand the IDE was wrong, and since we don't use this anywhere, I now agree with your note that my implementation was not right

2022-09-12 22:39 UTC, david-allison requested changes

2022-09-12 22:39 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/CollectionTest.kt
> +        assertNotNull(col, "Collection could not be opened")
We do not want to introduce an ambiguous manner of specifying the message for a test. 

Historically the message has been first, and we want one convention or the other.

With this, if `col` was a string, both `assertNotNull(col, "message")` and `assertNotNull("message", col)` would compile

I don't want to have to think about which one is correct.

2022-09-12 22:40 UTC, david-allison commented
> @david-allison, in your goal of consistency, is the approach of https://github.com/ankidroid/Anki-Android/pull/12352#issuecomment-1242825257 fine?
> 
> I believe that both kotlin.test and kotlin.test.junit both have contracts, and as the junit module delegates to the same asserter of junit, shouldn't be a problem 

I don't think I described consistency, I've elaborated in a review comment

2022-09-14 06:58 UTC, david-allison commented
Can we take this back to a GitHub issue or Discord? 

This is a massive undertaking. I'd struggle to find justification to accept the PR, and I don't feel this is a productive use of time.

2022-11-25 02:55 UTC, closed without merging