NF: cleanup of NoteEditorTest
ankidroid/Anki-Android pull request #12350
Opened 2022-09-08 22:49 UTC by Arthur-Milchior

2022-09-09 17:50 UTC, lukstbit requested changes
Note that with the changes in NoteEditorTest one of its subclasses(FieldEditLineTest) crashes due to a null pointer exception.

The cause is isInvalid accessing invalidSdkImpl which accesses invalidSdk at the wrong time.

2022-09-09 17:50 UTC, lukstbit commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
> +            return mutableListOf(Build.VERSION_CODES.N_MR1).apply { addAll(invalidSdks) }
Delete the kotlin cleanup on this property as it was fixed.

2022-09-09 17:50 UTC, lukstbit commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
> -        // Rules mean that we get a failure on API 25.
We should keep these comments on the class.

2022-09-09 17:50 UTC, lukstbit commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.kt
> +        listOf(Build.VERSION_CODES.N_MR1)
Build.VERSION_CODES.N_MR1 integer value is 25 not 30 like in the original code.

2022-09-09 17:50 UTC, lukstbit commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.kt
> +        wrapped.get()?.let {
Cleanup was done so delete the cleanup annotation reference on the class.

2022-11-18 09:29 UTC, Arthur-Milchior reviewed
Thanks @lukstbit
Sorry I missed your review. Corrected

2022-11-18 09:29 UTC, Arthur-Milchior commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.kt
> +        listOf(Build.VERSION_CODES.N_MR1)
I'm confused. I can't imagine how I got this wrong

2023-01-24 11:36 UTC, closed without merging