ManageSpaceActivity created.
ankidroid/Anki-Android pull request #12371
Opened 2022-09-10 18:21 UTC by Noxor11

## Pull Request template

## Purpose / Description
Fix the issue #12366 creating the activity with a small warning stating the only way to manage data is deleting it.

## Fixes
Fix the issue #12366.

## Approach
Created a Kotlin class to show the activity after declaring it in the Android Manifest. 

## How Has This Been Tested?
Compiled and ran on my cellphone, using Android Studio's run configuration to directly run the Activity. 

## Checklist

- [ x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x] You have commented your code, particularly in hard-to-understand areas
- [ x] You have performed a self-review of your own code
- [ x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility   ##Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

![1](https://user-images.githubusercontent.com/54048112/189496383-d56383c2-1ece-4355-b7c8-4512d88653c6.jpeg)
![2](https://user-images.githubusercontent.com/54048112/189496391-4c1516e5-2e79-4230-a659-27eec847c7fb.jpeg)

2022-09-10 20:14 UTC, ShridharGoel requested changes

2022-09-10 20:14 UTC, ShridharGoel commented on AnkiDroid/src/main/res/layout/activity_manage_space.xml
> +<?xml version="1.0" encoding="utf-8"?>
This file seems mostly copied from `card_template_editor_activity.xml`. It can be much simplified, you can just use a ConstraintLayout with a TextView in the center of the screen.

2022-09-10 20:14 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceActivity.kt
> + * Copyright (c) 2021 Shridhar Goel <shridhar.goel@gmail.com>                           *
Replace with your name and email.

2022-09-10 21:02 UTC, Noxor11 commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceActivity.kt
> + * Copyright (c) 2021 Shridhar Goel <shridhar.goel@gmail.com>                           *
Oops. Thanks for the feedback!

2022-09-11 08:37 UTC, Arthur-Milchior reviewed
Can you check the last box of the PR message please, since it’s a UI change

> UI Changes: You have tested your change using the [Google Accessibility ##Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)


Hi,

Thanks a lot for your work.
The failure is a real one, can you take a look at it please?

```
ActivityStartupMetaTest > ensureAllActivitiesAreTested FAILED
    java.lang.AssertionError: 
    Expected: iterable with items ["com.ichi2.anki.ManageSpaceActivity", "com.ichi2.anki.DrawingActivity", "com.ichi2.anki.pages.PagesActivity", "com.ichi2.anki.IntentHandler", "com.ichi2.anki.DeckPicker", "com.ichi2.anki.StudyOptionsActivity", "com.ichi2.anki.CardBrowser", "com.ichi2.anki.ModelBrowser", "com.ichi2.anki.ModelFieldEditor", "com.ichi2.anki.Reviewer", "com.ichi2.anki.VideoPlayer", "com.ichi2.anki.MyAccount", "com.ichi2.anki.preferences.Preferences", "com.ichi2.anki.DeckOptions", "com.ichi2.anki.FilteredDeckOptions", "com.ichi2.anki.Info", "com.ichi2.anki.NoteEditor", "com.canhub.cropper.CropImageActivity", "com.ichi2.anki.Statistics", "com.ichi2.anki.Previewer", "com.ichi2.anki.CardTemplatePreviewer", "com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity", "com.ichi2.anki.multimediacard.activity.LoadPronunciationActivity", "com.ichi2.anki.CardTemplateEditor", "com.ichi2.anki.CardTemplateBrowserAppearanceEditor", "com.ichi2.anki.CardInfo", "com.ichi2.anki.SharedDecksActivity", "com.ichi2.anki.LoginActivity", "com.ichi2.anki.IntroductionActivity"] in any order
         but: no item matches: "com.ichi2.anki.ManageSpaceActivity" in ["com.ichi2.anki.ModelFieldEditor", "com.ichi2.anki.Info", "com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity", "com.ichi2.anki.VideoPlayer", "com.ichi2.anki.FilteredDeckOptions", "com.ichi2.anki.multimediacard.activity.LoadPronunciationActivity", "com.ichi2.anki.IntentHandler", "com.ichi2.anki.IntroductionActivity", "com.ichi2.anki.MyAccount", "com.ichi2.anki.CardTemplateEditor", "com.ichi2.anki.SharedDecksActivity", "com.ichi2.anki.CardInfo", "com.ichi2.anki.Previewer", "com.canhub.cropper.CropImageActivity", "com.ichi2.anki.CardTemplatePreviewer", "com.ichi2.anki.DeckPicker", "com.ichi2.anki.preferences.Preferences", "com.ichi2.anki.CardBrowser", "com.ichi2.anki.StudyOptionsActivity", "com.ichi2.anki.Reviewer", "com.ichi2.anki.Statistics", "com.ichi2.anki.NoteEditor", "com.ichi2.anki.LoginActivity", "com.ichi2.anki.DrawingActivity", "com.ichi2.anki.DeckOptions", "com.ichi2.anki.pages.PagesActivity", "com.ichi2.anki.ModelBrowser", "com.ichi2.anki.CardTemplateBrowserAppearanceEditor"]
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at com.ichi2.anki.ActivityStartupMetaTest.ensureAllActivitiesAreTested(ActivityStartupMetaTest.kt:55)
```

Also, can you update your screenshot? If you

2022-09-11 08:37 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/layout/activity_manage_space.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:app="http://schemas.android.com/apk/res-auto"
I suspect this lead to a change in the appearance of the app. If so, can you take a screenshot of the new appearance.

2022-09-11 15:52 UTC, Noxor11 commented on AnkiDroid/src/main/res/layout/activity_manage_space.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:app="http://schemas.android.com/apk/res-auto"
done.

2022-09-11 21:06 UTC, Arthur-Milchior commented
Hi,

FYI usually here, we amend commit and force push.
No big deal since it’s going to squashed I assume. But when we actually use atomic commit, that helps ensure each commit has a single change.

Seems fine to me. Waiting for tests to run. It failed earlier but seems unrelated

2022-09-17 19:57 UTC, ShridharGoel approved these changes

2022-09-17 20:01 UTC, Arthur-Milchior commented
I realize this was adding as string. However, we hopefully will never release with only this message, the string will be replaced by buttons. So no need to do all the work to send it to translators. 

So I added a commit that hard code the string in English.

2022-09-17 20:11 UTC, BrayanDSO commented
This currently impedes someone to clear the app data manually, besides uninstalling. I wouldn't merge this until a provisory button to clear the app data is on the activity

2022-09-17 20:29 UTC, Arthur-Milchior commented
On the one hand, I'm totally fine with not being able to delete without uninstalling. 
Either the data are on ~/AnkiDroid and the button don't do anything
Or the user is on alpha using scoped storage, and there should be virtually nobody that is not a dev' doing it. And I don't know of anyone 

On the other hand, I guess that starting to add buttons would be nice, since that's what the UI should looks like and what the the next step should be. However, asking for one or a few entries in the menu may be easy. Ensuring they are linked to correctly implemented actions is going to be really hard for a first PR request.


@Noxor11 Can you please let us know how you fill about:
* adding element(s) in this activity that are clickable
* ensuring that the "Delete collection" ask for confirmation and delete the folder containing the collection
* or otherwise some other action mentioned in #12366 that you believe you can implement

2022-09-17 21:34 UTC, Noxor11 commented
> @Noxor11 Can you please let us know how you fill about:
> * adding element(s) in this activity that are clickable
> * ensuring that the "Delete collection" ask for confirmation and delete the folder containing the collection
> * or otherwise some other action mentioned in #12366 that you believe you can implement

I believe I can add elements in the activity using the already existing Preference classes, and creating a ManageSpaceFragment which uses the requirePreference method from PreferenceUtils.kt to leave empty click listeners for later implementing. If that's the case and you find it appropiate, I think I can do it.

I'm not so sure about implementing the "Delete collection" button though, but I'll try my best.

2022-09-18 09:29 UTC, Arthur-Milchior commented
Not even the first step?
Creating a list of actions in a menu is standard Android action. Opening a confirmation activity that can be confirmed or cancelled too. It's okay if it do nothing in a first commit, we can always call the function that deletes the collection later.
You can also look at our code to see how some actions are done. Or come on discord and discuss with us to ask where to ask questions

2022-09-18 12:32 UTC, mikehardy commented
This does not seem to be actually pending merge, re-labeling

2022-09-28 22:08 UTC, Noxor11 commented
> Not even the first step?
> Creating a list of actions in a menu is standard Android action. Opening a confirmation activity that can be confirmed or cancelled too. It's okay if it do nothing in a first commit, we can always call the function that deletes the collection later.
> You can also look at our code to see how some actions are done. Or come on discord and discuss with us to ask where to ask questions

I managed to do it. If anything needs a change please let me know.

2022-09-29 17:23 UTC, mikehardy requested changes

2022-09-29 17:23 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +        File(col!!.media.db!!.path).delete()
First things first, thank you! Thank you for taking this on

I'm concerned on these lines that we have some pretty heavy work (full data delete!) going into something called "ManageSpaceFragment". I'm not sure exactly where this should go, but this seems like it should be in a more general spot, perhaps on the Collection object itself? Or on CollectionHelper or CollectionManager? @dae you just restructured those (Helper + Manager) what do you think about the proper home for a *full* delete of the collection?

Separately I am always concerned when I see `!!` - I'm just waiting to get a crash report later on unsafe null object access...

2022-09-29 17:23 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +        col!!.modSchemaNoCheck()
I don't believe we need to worry about schema modification when we've just deleted the collection entirely

2022-09-29 17:23 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +        UIUtils.showThemedToast(context, getString(R.string.collection_deleted_message), false)
@BrayanDSO toast, or snackbar :thinking:  ?

2022-09-29 17:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +        UIUtils.showThemedToast(context, getString(R.string.collection_deleted_message), false)
As the screen isn't closed/changed after the action is done, snackbar

2022-09-30 05:48 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +        File(col!!.media.db!!.path).delete()
Yes, this belongs in CollectionManager, and should ensure everything happens in the queue, similar to importColpkg(). That will avoid all the !!s, and ensure other operations don't run concurrently. 

Also:
- The call should be wrapped in withProgress().
- You should list the files in the folder instead of relying on the media DB, as the two may not be in sync
- You should close the collection before deleting the file

2022-09-30 17:52 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceActivity.kt
> +/****************************************************************************************
I think we should create a subdirectory for ManageSpace. I think `com.ichi2.managespace` would be acceptable, since, from the point of view of the app, it's really a separate app

2022-09-30 17:52 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceActivity.kt
> +class ManageSpaceActivity : AnkiActivity() {
Do we really need an AnkiActivity? It seems overkill to create such a simple task. We may want to ensure we can get collection in the ManageSpaceFragment. However, as long as we are only trying to get sometihng to manage space, I don't think it's actually useful to use more than the bare minimum.

(I'm far from expert in UI, so please feel free to let me know I'm wrong here.

2022-09-30 17:52 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceActivity.kt
> +class ManageSpaceActivity : AnkiActivity() {
I'd love a javadoc. Developer may stumble upon this file without knowing what is "Manage space". So maybe just an indication that it's in "Android Setting > Storage > Apps > AnkiDroid > Manage storage"

2022-09-30 17:52 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +        File(col!!.media.db!!.path).delete()
I'd even add, you should avoid opening the collection if it's already closed.

2022-09-30 17:52 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +    // Deletes collection and media
We need to use 
```kotlin
/**

*/
```
Otherwise, kotlin don't consider it to be the documentation of the function.

2022-09-30 17:52 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="restore_from_backup_summary">Restore from backup if something isn\'t working correctly.</string>
I think right now we may want to have a single entry, with "delete directory" since it's the one we are working with. We'll decide each other one in different PR and different issues.

2022-10-02 19:11 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +        UIUtils.showThemedToast(context, getString(R.string.collection_deleted_message), false)
It does not seems, as far as I can tell, that our snackbars can be called on fragments. They expect a coordinator layout.

2022-10-02 19:24 UTC, Arthur-Milchior commented
So I just pushed a new version. I hope back-end code is better. However, I admit I've been blocked by Front-End. I wished to used snackbar, as @BrayanDSO wanted, but it requires to have "An [Activity] that has a [CoordinatorLayout] with id `root_layout`.". And there is no coordinatorLayout here.
Also, even trying to use a toast fail to show anything. (Even when directly called in `initSubscreen`, so it should not be a question of scope here). @Noxor11 , when you tried your function, where you able to see the toast?

Same problem with the progress bar, which requires a Fragment activity.

2022-10-02 20:41 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +        UIUtils.showThemedToast(context, getString(R.string.collection_deleted_message), false)
:thinking: - @oakkitten who is the Master of Snackbars even though I think you proclaimed that was not a desired title :laughing: - is the assertion that snackbars cannot be called on fragments / snackbars expect a coordinator layout a) true b) a constraint that may be relaxed?

2022-10-03 00:41 UTC, Arthur-Milchior commented
I've just added number of back-up. However, #12562 also applies to it. We don't have something to directly delete extra back-ups. So still need to be done

2022-10-03 21:59 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +        UIUtils.showThemedToast(context, getString(R.string.collection_deleted_message), false)
Without coordinator layout a snackbar will show but not work properly. I don't think it matters that you have a fragment there, but why not use a coordinator layout? And why use a fragment in the first place?

2022-10-09 00:41 UTC, oakkitten reviewed
Noone asked me to review but I'm rehoming a kitten and it makes me very sad I wanted to take my mind off things.

I'd like to be able to delete everything from this screen, also to delete individual backups and to see how much space those are taking. Also it probably should have a toolbar?

2022-10-09 00:41 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
> +    fun fullCheck(): List<List<String>> {
“Full check” is a noun, I'd prefer `performFullCheck()`. I'd also prefer it to return a data class. I think introducing a data class in this PR is a good idea.

2022-10-09 00:41 UTC, oakkitten commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="delete_collection_summary">Permanently erases your AnkiDroid collection and media.</string>
This probably doesn't need a period at the end.

2022-10-09 00:41 UTC, oakkitten commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="delete_data_confirmation">Are you sure you want to delete your whole collection and media?\n\nThis can\'t be undone.</string>
Probably better to say `can’t` instead of `can\'t`.

2022-10-09 00:41 UTC, oakkitten commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="delete_data_ongoing">Your AnkiDroid collection, medias and back-ups are currently being deleted.</string>
This text gets cut off on my device. Even if it didn't, it's too long

2022-10-09 00:41 UTC, oakkitten commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="delete_data_confirmation">Are you sure you want to delete your whole collection and media?\n\nThis can\'t be undone.</string>
Also, why the above says `delete_collection` and this says `delete_data`?

2022-10-09 00:41 UTC, oakkitten commented on AnkiDroid/src/main/res/xml/manage_space.xml
> +      android:title="@string/check_media"/>
The title says “check media” but what it really does is said in the summary. Change the title to `Delete unused media files`, remove the summary, and make the dialogs behave accordingly.

2022-10-09 00:41 UTC, oakkitten commented on AnkiDroid/src/main/res/values/manage_space.xml
> +    <string name="delete_collection_key">deleteCollectionManageSpace</string>
Nit: actual key names don't really name but putting the “parent” on the end is kind of weird.

2022-10-09 00:41 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +        val numberOfUnusedMedias = unused.size
I'd inline this (as `unusedFiles.size`)

2022-10-09 00:41 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
>      suspend fun checkMedia() = withCol {
Probably best to inline this method at this point.

2022-10-09 00:41 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceActivity.kt
> +            replace(R.id.manage_space_layout, mainFragment, mainFragment::class.java.simpleName)
Nit: best not to use `simpleName`, AnkiDroid might use r8 (in an useful mode) one day

2022-10-09 00:41 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceActivity.kt
> +        val mainFragment = ManageSpaceFragment()
I'd go with the more concrete `val manageSpaceFragment = ...` for simplicity

2022-10-09 03:15 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +        UIUtils.showThemedToast(context, getString(R.string.collection_deleted_message), false)
@oakkitten to be honest, simply because I'm just discovering UI and interfaces. So I was trying to check if anyone know how to do things, because I've no idea and right now other priorities.

2022-10-09 03:18 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
> +     * @return whether deletion succeeded.
Not returning anything. It's not like I plan to use it

2022-10-09 03:22 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
> +    private fun expectedCollectionPath() =
* You can indeed change the directory to various places with the settings, you can also have a directory AnkiDroid.A if you install a second AnkiDroid. So yeah, there may be collections at the not expected path. 
* If you even see a "Path" whose actual type is a File, please let me know, we need to correct it. I believe that we always mean that it is the address (admittedly, sometime as a String, sometime as the class Path. But Path is not available in all APIs sadly)
* This function return a String, it indicates where the directory is. So Path seems right. While above, we actually cared about whether a directory exists

2022-10-09 03:25 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +                    val progressDialog = StyledProgressDialog.show(requireContext(), getString(R.string.delete_data_ongoing), null)
If we go to it, I'd hope we could use `withProgress` eventually, if someone work on it and understand what blocks it from working right now. But I guess you are probably right

2022-10-09 03:33 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +                        MainScope().launch {
The actual answer is that I thought that `launchCatchingTask` meant we leaved the main thread.
It's implemented as `lifecycle.coroutineScope.launch` and I would have thought that the main and the lifecycle threads are distinct. After all, that would explain why we could ask the background work to be done in a `launchCatchingTask` without blocking the main thread

2022-10-09 10:12 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
> +     * @return whether deletion succeeded.
If it's not going to be a part of this PR it's just something that can be decided later

2022-10-09 10:30 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
> +    private fun expectedCollectionPath() =
* Are you suggesting that deleting the collection from this screen only deletes the collection from the default location, and fails to delete it if a different location is specified in the settings? I don't think that's true. As for collections not associated with the app, not sure how these are relevant.
* [Here's](https://github.com/ankidroid/Anki-Android/blob/2704fcb8667c20a14656541ffcaaec1e326dd49c/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt#L40) a path that points to a file. Note how it says “file path”, if this would say “directory path” this would be better, but it doesn't. The word “path” can mean three things, an abstract path to something with or without concrete methods (e.g. `http://domain/this/is/path`), a string representation, as in “file path”, or some kind of a `Path` object. I would prefer `val collectionDirectoryString` to `val collectionDirectoryPath` to reduce the ambiguity, and `val collectionDirectory` to the above because this is Kotlin. I'd try refactoring this to return `File`, too.

2022-10-09 10:42 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +                        MainScope().launch {
Lifecycle refers to the lifecycle of the activities and fragments (`onCreate`...`onDestroy`). `LifecycleCoroutineScope` is a main thread scope that's cancelled when the activity is destroyed. You can easily switch to another thread with something like `withContext(Dispatchers.IO)`, `withQueue` does something like that.

2022-10-09 12:09 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +                        val checkLists = withCol { media.fullCheck() }
Actually, it moved to a dataclass since. But I had to wait until this PR gets merged

2022-10-09 12:19 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +                            // Let the user know there is nothing to do
Thanks

2022-10-09 12:21 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +    // TODO: give a list of media, as in DeckPicker.
Improved, hopefully

2022-10-09 12:22 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +    private fun confirmDelete(
Do you have any link you recommand? I've never heard about those. I can't even imagine how you could avoid needing to have either a tree or extracting things

2022-10-09 12:23 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +            message(text = context.resources.getQuantityString(R.string.check_media_summary, numberOfUnusedMedias))
I beg your pardon. What is puzzling?
`check_media_summary` is a plural string resource, to be precise. Once you apply `getQuantityString` then you get a string

2022-10-09 12:25 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +    fun noCollection() {
`disableMenuEntries` then.
The name you gave seems to imply the function is in charge of cehcking whether the collection directory does not exists.

2022-10-09 12:26 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +        for (key in listOf(R.string.delete_collection_key, R.string.check_media_key, R.string.pref_backup_max_key)) {
Unless I use a sequence of collection instruction, I must admit that I don't see the point. Maybe we'll make a rule of it later. Right now, I think that `key in` is nicer than `key -> `

2022-10-09 12:28 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +                shouldDisableView = true
Thanks, I misunderstood the meaning of this line

2022-10-09 12:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
> +    fun fullCheck(): List<List<String>> {
I'll wait to see if there is a second opinion. I don't feel like we had any specific issue with this kind of name. We have many `full foo` in the code.

2022-10-09 12:32 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="delete_data_confirmation">Are you sure you want to delete your whole collection and media?\n\nThis can\'t be undone.</string>
Why not use the standard single quote? It seems to be what's usually used everywhere

2022-10-09 12:33 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="delete_data_ongoing">Your AnkiDroid collection, medias and back-ups are currently being deleted.</string>
Replaced the whole list by "data"

2022-10-09 12:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/xml/manage_space.xml
> +      android:title="@string/check_media"/>
I prefer to remain consistent with AnkiDroid and Anki. It's called "check media" everywhere. And we are really using the same class, that optimize the media db and I think do some other work on top of offering to delet

2022-10-09 12:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +        val numberOfUnusedMedias = unused.size
I prefer to keep it, just because I can imagine we improve this later and show the number of files, if not even the list of files

2022-10-09 12:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
>      suspend fun checkMedia() = withCol {
I'd be curious to learn what makes you decide to do so.
I don't disagree. I see no harm. Used only once, it will decrease the size of the binary. By very little. It will save time, but very little; as it's clearly not a hotpath

2022-10-09 12:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceActivity.kt
> +            replace(R.id.manage_space_layout, mainFragment, mainFragment::class.java.simpleName)
r8? As far as I know, it's the mode to optimize an app by removing what's not used. Is there more to it? Do you have a link explaining how it relates to name? I would have assumed that as soon as it seems that ManageSpaceFragment() is called, it'd now not to delete it. And so the name would not actually matter. After all, the name is only used, if I trust `replace` documentation, to be able to retrieve the fragment later

2022-10-09 13:00 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceActivity.kt
> +            replace(R.id.manage_space_layout, mainFragment, mainFragment::class.java.simpleName)
If you're right, we should also change preferences screen.  And if it's a general rule against `name`, we use it in 21 places right now

2022-10-09 13:05 UTC, Arthur-Milchior commented
@oakkitten Thanks a lot. Applied or answered to all.
In case it was not clear, we rarely ask specific people for review, unless we believe we actually must uses this very person feedback. Your review is very welcomed, and it's welcome anywhere. As I tried to explain on wiki and sometime on discord, anyone can review. One person with the reviewer status must give a review, but we want two reviews, the second review can be anyone. And that's what we use to decide who to offer the reviewer status to

2022-10-09 13:13 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +    private fun confirmDelete(
I've never seen those but just looking it up on Google yields [this](https://federicokt.medium.com/smarter-dialogs-with-coroutines-b83e1d0e06a0) which is more or less what I had in mind.

2022-10-09 13:14 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +            message(text = context.resources.getQuantityString(R.string.check_media_summary, numberOfUnusedMedias))
It's not a plural though? It's just a string.

2022-10-09 13:21 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +    fun noCollection() {
I don't think it disables menu entries though? Right, my bad, it does imply that, maybe `disablePreferencesThatAreOnlyRelevantIfCollectionDirecotoryExists()` or `disablePreferencesThatRequireCollectionDirectory()` or `disablePreferencesDealingWithCollection()`...

2022-10-09 13:23 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +        for (key in listOf(R.string.delete_collection_key, R.string.check_media_key, R.string.pref_backup_max_key)) {
Yeah this is not important, I only prefer this for easier chaining and consistency. Choose one way and never think of which way to do it

2022-10-09 13:27 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
> +    fun fullCheck(): List<List<String>> {
This is a common convention. E.g. https://stackoverflow.com/a/1991341/1449683 or https://developer.android.com/kotlin/style-guide

> Function names are written in camelCase and are typically verbs or verb phrases. For example, `sendMessage` or `stop`.

I think AnkiDroid should introduce a guide on naming things, quite a few names are horrible

2022-10-09 13:32 UTC, oakkitten commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="delete_data_confirmation">Are you sure you want to delete your whole collection and media?\n\nThis can\'t be undone.</string>
`’` is [more preferred](https://en.wikipedia.org/wiki/Apostrophe#Unicode) and you will see it and not `'` on most news websites. Also it doesn't require `\`

2022-10-09 13:35 UTC, oakkitten commented on AnkiDroid/src/main/res/xml/manage_space.xml
> +      android:title="@string/check_media"/>
I think Anki does more than this. I'd prefer either make this do what Anki does or changing the title.

2022-10-09 13:42 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +        val numberOfUnusedMedias = unused.size
Even if you do show the list of files I don't see the need for this extra name. If you go with `unusedFiles`, that's just one name for the concept that's used throughout the code, and `unusedFiles.size` is easy enough to read, I think. By referring to `files` as `medias` you only create a little confusion, and I'm not sure about the value of `.size` → `numberOf`.

2022-10-09 13:45 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
>      suspend fun checkMedia() = withCol {
Not for performance reasons. It's just that this method adds so little to what it calls that I'd just be annoyed that I have to Ctrl-click once more. Also, I think something like `withCol` belongs in the call site.

2022-10-09 13:50 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceActivity.kt
> +            replace(R.id.manage_space_layout, mainFragment, mainFragment::class.java.simpleName)
R8, if fully enabled, will rename classes to short strings. So you can end up with fragments `a.b.c` and `a.c`, and `simleName` for both will be `c`, which might be a problem. But r8 is 99% disabled now so this is not a present issue.

2022-10-09 13:54 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
>      suspend fun checkMedia() = withCol {
OH I didn't mean make it `inline`, I meant removing the method altogether and replacing its calls with `withCol { media.fullCheck() }`!

2022-10-09 15:10 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceActivity.kt
> +            replace(R.id.manage_space_layout, mainFragment, mainFragment::class.java.simpleName)
I would love to see a deep link into a document on R8 that talks specifically about the simpleName issue, also, I do not want to have latent R8 issues in case we do enable it in its more aggressive modes, so best to change it if this is a problem. What's the specific line you would suggest?

2022-10-09 15:16 UTC, oakkitten reviewed
A bit more nitpicking since it's “very welcome” 😛

P.S. You are probably thinking that I'm super fussy about names, and you are right; I think great names make great code!

2022-10-09 15:16 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +        return v
Just a note: A matter of taste but I *think* that idiomatic Kotlin here would be `return block().also { progressDialog.dismiss() }`

2022-10-09 15:16 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +    // deleting those files. Instead of just asking "are you okay to deleting unused files"
You can have a multi-line TODO if the lines after first have some spaces, e.g.

    // TODO: Show the content of [unused] to the user and ask them to confirm they are okay with
    //   deleting those files. Instead of just asking "are you okay to deleting unused files"

Otherwise, only the first line is shown in the TODO window

2022-10-09 15:16 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +    // deleting those files. Instead of just asking "are you okay to deleting unused files"
Also that javadoc can probably be removed.

2022-10-09 15:16 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
> +     * @return A list containing three lists of files (missingFiles, unusedFiles, invalidFiles)
This better be updated

2022-10-09 15:22 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceActivity.kt
> +            replace(R.id.manage_space_layout, mainFragment, mainFragment::class.java.simpleName)
It's not a specific r8 + `simpleName` issue, it's just that `simpleName` of both `a.b.c` and `a.c` is `c`. Actually, found an article on Google https://medium.com/mobile-app-development-publication/the-danger-of-using-class-getsimplename-as-tag-for-fragment-5cdf3a35bfe2

In this case you probably don't need the tag at all, just `replace(R.id.manage_space_layout, ManageSpaceFragment())` should work I think

2022-10-09 15:25 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceActivity.kt
> +            replace(R.id.manage_space_layout, mainFragment, mainFragment::class.java.simpleName)
Great link, thank you. Most relevant part (assuming the problem is understood) - the prescriptive statement:


> I know the chance might not be high that the getSimpleName() will be the same on post proguard; but if it happens to me, it could happen to anyone. One should use either one of the below perhaps
> 
> the full name
> canonical name
> a constant explicitly defined

2022-10-09 20:50 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +    private fun confirmDelete(
I can barely read `askUserToConfirmUnusedMediaDeletionAndPerformDeletion`.

I'd rather use `confirmAndPerformMediaDeletion` or anything shorter

2022-10-09 21:09 UTC, BrayanDSO requested changes
Also, you added `NF:`  on the title of some commits with functional changes

2022-10-09 21:09 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="check_media_summary">Delete unused medias from your collection.</string>
```suggestion
    <string name="check_media_summary">Delete unused media files</string>
```

2022-10-09 21:09 UTC, BrayanDSO commented on AnkiDroid/src/main/res/xml/manage_space.xml
> +      android:title="@string/check_media"/>
Agreed with changing the title to `Delete unused media files` here. Much more descriptive and fits more the idea of a `Manage space` screen.

2022-10-09 23:32 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/ManageSpaceFragment.kt
> +        return v
I think this should be wrapped in a try/finally block like withProgress does, or the dialog will not be dismissed if the block throws.

2022-10-27 13:49 UTC, oakkitten commented
I've been tinkering with this, and I have a small question about finding unused media. [The method that calculates unused media](https://github.com/ankidroid/Anki-Android/blob/add3d2c0af75aa3ee53dfc8c570fc506b88c898e/AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt#L305) is attempting to normalize fields of cards that refer to media files, and the names of media files themselves. What is the problem that this solves? I am also not entirely sure if this solves the problem in a good way. If both normalized and non-normalized files exist, the non-normalized is silently deleted. Also, do we really at this point expect non-normalized *card fields*? In order to properly refactor this, or make a more suitable alternative, I want to have a better understanding of this. Any clues? @dae

2022-10-28 10:49 UTC, dae commented
If the filenames on disk and in fields are not normalized, it can lead to copies being created with a different encoding when syncing across platforms due to the normalization macOS performs, or images failing to appear because the field encoding does not match the disk encoding. Anki ensures the correct encoding is used when writing files into the media folder, so "check media" should only perform changes when users manually write files into the media folder. And no, you can't rely on fields being in the correct encoding, since users can disable automatic normalization.

I would not waste time on refactoring the linked code, since the backend already provides its own implementation.

2022-10-28 15:02 UTC, oakkitten commented
I see. I made manage space activity start calculating unused media files when it is shown, so I'd prefer that opening it doesn't result in any changes in files or notes. Also, the legacy `check()` method seems to be performing normalization unconditionally. So I guess I'll create another method for calculating unused media files only, that returns a marker if media check is required. As I understand, the backend doesn't support this at the time being.

2022-10-30 19:14 UTC, mikehardy commented
I rebased this to main and pushed it out (`--force-with-lease`) so CI would run and it was up to date - just trying to push it forward a bit

2022-10-30 19:32 UTC, oakkitten commented
I'll make another PR that will supersede this. (Because I can't add commits here.)

2022-12-03 13:54 UTC, closed without merging