Kotlin Cleanup: scoped functions
ankidroid/Anki-Android pull request #12376
Opened 2022-09-11 18:44 UTC by divyansh-dxn

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-11 20:51 UTC, Arthur-Milchior approved these changes

2022-09-11 20:57 UTC, Arthur-Milchior requested changes

2022-09-11 20:57 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
> +                progressDialog.dismiss()
Shouldn’t the dialog be dismissed after the list is rebuilt and the summary updated?
I don’t expect it to take a lot of time usually. Still, it may not be entirely immediate as it’s fetching values from preferences. I believe actually it’s not worth risking such a change only for introducing `apply`.
At best, you can introduce a val to get the `deckOptions` and avoid repeating it many time.

Speaking of which I guess a better name would be `deckOptionsUI` because the way it’s named, I’d thought first that it contains the model of a deck option

2022-09-12 07:39 UTC, lukstbit approved these changes
Ok.
I don't like nesting apply in apply.

2022-09-12 07:40 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
> +                progressDialog.dismiss()
deckOptionsActivity would be more decriptive.

2022-09-12 09:55 UTC, ShridharGoel approved these changes
Can consider updating the class name as well.

2022-09-12 10:51 UTC, divyansh-dxn commented
Changing the class name would be a bigger change and might not be best idea to do it here.

2022-09-12 19:09 UTC, ShridharGoel commented
@divyansh-dxn Consider adding a TODO for the same in a second commit.

2022-09-12 19:17 UTC, Arthur-Milchior approved these changes

2022-09-12 19:21 UTC, BrayanDSO commented
FWIW, this whole class will be replaced by the new Anki HTML, so I wouldn't suggest dedicating more time refactoring it or leaving TODOs

2022-09-13 07:23 UTC, merged