[GSoC] Coroutines migration CheckMedia
ankidroid/Anki-Android pull request #12375
Opened 2022-09-11 17:30 UTC by divyansh-dxn

## Fixes
Fixes a part of #7108

## How Has This Been Tested?
Passes existing unit tests and runs as expected on Pixel 4a API 31 AVD

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-11 18:05 UTC, divyansh-dxn commented
Waiting for #12374 to be merged. Unused ressource will be then used to show title of the error dialog.

2022-09-13 20:59 UTC, divyansh-dxn commented
I was thinking, is the last commit is fine to have here or should I make another PR for that?

2022-09-14 16:30 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> + * Copyright (c) 2022 Ankitects Pty Ltd <https://apps.ankiweb.net>                      *
Revert these changes in the copyright.
Looks good, but I don't have time now to run the changes and fully review.

2022-09-14 16:33 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> + * Copyright (c) 2022 Ankitects Pty Ltd <https://apps.ankiweb.net>                      *
Just corrected the indentation, any specific reason to get it reverted?

2022-09-14 16:48 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> + * Copyright (c) 2022 Ankitects Pty Ltd <https://apps.ankiweb.net>                      *
@divyansh-dxn Nevermind, I thought this was some formatting error but it look ok with your changes.

2022-09-15 18:17 UTC, lukstbit requested changes
Reviewed the PR and I'm ok with the changes up to the last commit. Several issues with the last commit:

- the launchCatchingTask is receiving errorMessage to be used in logging and not as a title
- it doesn't replicate the initial behavior when the string check_media_failed was used as the message for the dialog and not its title
- I don't think it's very helpful to the user to see the title "check media failed" and the message "java.lang.NullPointerException"(for example). It doesn't know what it is and he can't act on it.
- it's kind of unrelated to the main changes in the PR

I would recommend that you replace the changes in the last commit with something like this, in `mediaCheck()`:
```

// TODO show to the user this message when failing
@Suppress("Unused")
val failedCheck = getString(R.string.check_media_failed)
```

to get rid of the unused string lint issue. Then we can merge this PR.
Then you could make another PR where in the first commit you could insert the errorMessage in the dialog showed by runCatchingTask:

```
} catch (exc: Exception) {
        Timber.e(exc, extraInfo)
        showError(this, "$extraInfo\n(Exception: $exc.toString())")
}
```

This way we have the option of showing a custom message and also the exception.
In the second commit of the future PR you could then fix the above todo for check media and use the string as you do now.

2022-09-15 18:41 UTC, divyansh-dxn commented
> Reviewed the PR and I'm ok with the changes up to the last commit. Several issues with the last commit:
> 
> * the launchCatchingTask is receiving errorMessage to be used in logging and not as a title
> * it doesn't replicate the initial behavior when the string check_media_failed was used as the message for the dialog and not its title
> * I don't think it's very helpful to the user to see the title "check media failed" and the message "java.lang.NullPointerException"(for example). It doesn't know what it is and he can't act on it.
> * it's kind of unrelated to the main changes in the PR
> 
> I would recommend that you replace the changes in the last commit with something like this, in `mediaCheck()`:
> 
> ```
> 
> // TODO show to the user this message when failing
> @Suppress("Unused")
> val failedCheck = getString(R.string.check_media_failed)
> ```
> 
> to get rid of the unused string lint issue. Then we can merge this PR. Then you could make another PR where in the first commit you could insert the errorMessage in the dialog showed by runCatchingTask:
> 
> ```
> } catch (exc: Exception) {
>         Timber.e(exc, extraInfo)
>         showError(this, "$extraInfo\n(Exception: $exc.toString())")
> }
> ```
> 
> This way we have the option of showing a custom message and also the exception. In the second commit of the future PR you could then fix the above todo for check media and use the string as you do now.

done

2022-09-15 18:41 UTC, divyansh-dxn commented
@lukstbit  done!

2022-09-16 10:25 UTC, lukstbit approved these changes
Ok!

2022-09-16 12:08 UTC, Arthur-Milchior approved these changes
Approved. Ideally after you do the very small change I want, but I won't complain if it's merged as-is if you don't want

2022-09-16 12:08 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            launchCatchingTask {
The new schema didn't had the `check_media_message` message. Now it has.
I believe this change is fine, but I'd like to see it documented in the commit message.

2022-09-16 12:08 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    withCol { if (!BackendFactory.defaultLegacySchema) media.check() else checkMedia(this) }
This reads as `if it's not the legacy system then uses media.check`. it would be simpler to read without negation. Can you move it to `if(Backendfactory.defaultLegacySchema) checkMedia(this) else media.check()` in a next commit ?
(i agree this was good, this commit is more readable by keeping the conditions in the same order)

2022-09-18 05:58 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        mProgressDialog?.dismiss()
See [here](https://github.com/ankidroid/Anki-Android/pull/12373#discussion_r967831631)

2022-09-18 05:58 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        mProgressDialog?.dismiss()
Will add in the commit message also.

2022-09-18 06:20 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    withCol { if (!BackendFactory.defaultLegacySchema) media.check() else checkMedia(this) }
done some more simplification, see last two commits.

2022-09-18 06:21 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
>  fun checkMedia(col: Collection): Computation<List<List<String>>> {
done

2022-09-18 12:42 UTC, ShridharGoel approved these changes

2022-09-18 12:49 UTC, mikehardy approved these changes
This is the first one of these coroutine migrations I've had the time to read. Really nice, and the progression of commits made it quite easy for me to follow. Great work

2022-09-18 14:30 UTC, Arthur-Milchior approved these changes

2022-09-18 14:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    postMediaCheck(result)
Do we really want to have the message (failure or success) to be done inside inside the catching part, even if we don't expect anything to catch (and if there is an exception there, we probably want to know it)

2022-09-18 14:35 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    postMediaCheck(result)
I din't understood your concern here, and launchCatchingTask reports the exception to ACRA so we'll know if there was an exception or not.

2022-09-18 14:37 UTC, merged