Rename the string of "This deck is empty" snackbar action
ankidroid/Anki-Android pull request #12389
Opened 2022-09-13 09:40 UTC by snowtimeglass

## Pull Request template

## Purpose / Description
Replace the string of "This deck is empty" snackbar action ("ADD CARD") with "ADD" to keep a consistency with the other note-adding strings 

![image](https://user-images.githubusercontent.com/10436072/189846526-29efd935-daca-49fe-9945-64e25bff9db4.png)

## Approach
Replace `R.string.empty_deck_add_note` with `R.string.empty_menu_add` on DeckPicker.kt

## How Has This Been Tested?
Build an app and check it on my physical device
![image](https://user-images.githubusercontent.com/10436072/189839708-67fe9bcc-3396-4468-8de5-6b1d0ddd8072.png)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-14 07:07 UTC, david-allison requested changes
```
> Task :AnkiDroid:lintPlayDebug FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/01-core.xml:145: Error: The resource R.string.empty_deck_add_note appears to be unused [UnusedResources]
    <string name="empty_deck_add_note">Add card</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~
1 errors, 0 warnings
```

To fix: remove the string from **ONLY** `/Anki-Android/AnkiDroid/src/main/res/values/01-core.xml`, amend the current commit + `git push --force-with-lease`

To test:

`./gradlew lintPlayDebug`

2022-09-14 16:16 UTC, snowtimeglass commented
@david-allison thanks for pointing it out and the guidance. I've tried the fix with stumbling many times.

I failed to do the test. The following error message was shown. I'll do the setting if it is necessary.
```
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

2022-09-14 16:49 UTC, david-allison commented
@snowtimeglass It's sorted in CI.

I'm sorry, I don't have the free time to help you through this issue, could you check with [Discord](https://discord.gg/qjzcRTx) (`#ankidroid-dev`)

2022-09-14 16:49 UTC, david-allison approved these changes

2022-09-14 21:27 UTC, BrayanDSO approved these changes
great. I always like having less strings == less job for the translators

2022-09-14 21:27 UTC, merged

2022-09-15 13:04 UTC, snowtimeglass commented
Thanks for the checks!

>I'm sorry, I don't have the free time to help you through this issue, could you check with [Discord](https://discord.gg/qjzcRTx) (#ankidroid-dev)

@david-allison Never mind, of course. Thank you always for your dedication to the great works. I'll check with the community if I get stuck.