NF: Kotlin cleanup of SeekBarPreferenceCompat
ankidroid/Anki-Android pull request #12387
Opened 2022-09-12 23:38 UTC by BrayanDSO

## Approach
One cleanup per commit

## How Has This Been Tested?

CI

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-14 08:38 UTC, david-allison requested changes
Could you confirm you've tested one commit with functional changes.

Ideally a few unit tests around here or `@NeedsTest` to confirm new behaviour

I'd accept this PR with the mentioned commit dropped and split off into a separate PR

2022-09-14 08:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/preferences/SeekBarPreferenceCompat.kt
> +                max = preference.relativeMax
reviewer 2: `getPreference()` was a slightly complex call which was factored out to a variable.

I agree the reduction in code complexity is worth it in this case

2022-09-14 08:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/preferences/SeekBarPreferenceCompat.kt
> +        get() = getPersistedInt(default)
Original code is from 2011

:warning: I don't feel this was non-functional, we persist the value at different times (especially persisting the value earlier), but this seems simpler and correct

Previously we did this during `onProgressChanged`. with `fromUser = true`

Now we do this on all changes to `mValue`. We also no longer take `shouldPersist()` into account

2022-09-14 10:11 UTC, BrayanDSO commented
I think I'll drop the whole PR and start using androidx SeekBarPreference. We aren't on 2011 anymore when someone had to do their own implementation of a seek bar preference

2022-09-14 10:17 UTC, david-allison commented
Strong approve. Didn't realise it was now Android native

2022-09-17 19:16 UTC, BrayanDSO commented
I'm going to keep this one. I can get replace of most of the previous usages, as shown on the screenshot below, but not `Start of the next day` preference, so I'll keep the class while `Start of the next day` isn't migrated to a different class (a TimePreference with hour-only set would be the best I guess)

![image](https://user-images.githubusercontent.com/69634269/190872950-1fd11e71-4ee1-42f8-8537-208d5a1f26f0.png)

2022-09-17 20:24 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/preferences/SeekBarPreferenceCompat.kt
> +        get() = getPersistedInt(default)
Dropped the commit

2022-09-17 20:25 UTC, BrayanDSO commented
Dropped the perhaps functional commits

2022-09-18 12:35 UTC, mikehardy commented
For what it's worth, in my opinion the "start of next day" preference seems like it would be a fit for this idea of yours:

> TimePreference with hour-only set

2022-09-18 12:42 UTC, mikehardy approved these changes
LGTM - I don't think there's anything functional left and that was the only hangup prior

2022-09-18 12:42 UTC, merged