[GSoC] Show total lapses of note of card in notes mode
ankidroid/Anki-Android pull request #12399
Opened 2022-09-14 09:51 UTC by viciousAegis

## Pull Request template

## Purpose / Description
Continuation of #12035. Show total lapses of the note in notes mode

## Approach
Show sum of lapses of all cards in notes mode.

## How Has This Been Tested?
Manually on device.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-14 09:59 UTC, david-allison requested changes

2022-09-14 09:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
> +    fun totalLapsesOfNote() = totalLapses(note())
ditto - don't depend on `NoteService`. Instead, define this as an extension function in `NoteService`

2022-09-14 09:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                Column.LAPSES -> if (inCardMode) card.lapses.toString() else card.totalLapsesOfNote().toString()
Optional: I believe you could extract to `(if (inCardMode) card.lapses else card.totalLapsesOfNote()).toString()`

2022-09-14 16:43 UTC, david-allison requested changes
```
> Task :AnkiDroid:compilePlayDebugKotlin
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt: (227, 32): Unresolved reference: totalLapses
```

2022-09-15 01:23 UTC, david-allison approved these changes

2022-09-15 11:44 UTC, Arthur-Milchior commented
For future PR, I'd suggest adding a screenshot of the new result. Simply because when I review, it gives me immediately an intuitino of what you're doing

2022-09-15 18:01 UTC, Arthur-Milchior approved these changes
Approving because it works and is consistent with `Ease`. But still have trouble understanding why code is where it is and what not directly sql.
I let you decide whether you want to reply, edit, or just tell us to merge as is

2022-09-15 23:43 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
> +    fun totalLapses(note: Note): Int {
I know SQL, but I have not spent enough time with the schema to know where and how to make a query yet. I also feel like I should put more emphasis on filter sheets for now, as that project requires a lot more commitment. I will add a TODO here, and if/when I do find time, I'll make the change myself

2022-09-16 02:24 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
> +fun Card.totalLapsesOfNote() = NoteService.totalLapses(note())
`Card` is part of libAnki, you don't want functions in that library which aren't part of upstream.

In the past, we added additional functionality out of necessity, and it was a massive pain to migrate this to V16. I strongly want to discourage divergence from happening again.

2022-09-16 10:46 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
> +    fun totalLapses(note: Note): Int {
Edit done.

2022-09-16 11:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
> +fun Card.totalLapsesOfNote() = NoteService.totalLapses(note())
Then I believe we should at least have a discussion about the best way to add features that should naturally be in Card and are not due to technical purpose instead of being due to logical purpose.
If we want to call it a servicelayer, at least, let's call it a CardService.  And let's document at the top of the file the meaning of this new file.

I'll create a new issue to discuss this, as it's clearly not blocking this PR.
I believe however that the other questions are still relevant. Why some extensions and some are not extension. Why some are in the objects and some other not

2022-09-16 11:26 UTC, merged