[GSoC] Show Avg Interval in Notes Mode
ankidroid/Anki-Android pull request #12396
Opened 2022-09-14 09:43 UTC by viciousAegis

## Pull Request template

## Purpose / Description
Continuation of #12035. Adds functionality to see average interval of note in notes mode of browser.

## Approach
Create a function to average the intervals of non-new and non-learning cards

## How Has This Been Tested?

Unit Test added and tested on device.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-14 09:53 UTC, david-allison requested changes
One structural change, rest looks good

2022-09-14 09:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
> +    fun avgIntervalOfNote() = avgInterval(note())
We shouldn't have dependencies from Card -> `NoteService`

Define these as extensions on `Card` within the `NoteService` file

2022-09-14 09:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
> +    fun avgInterval(note: Note): Int? {
quick 'javadoc' explaining what a null return means

2022-09-14 09:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        private fun getAvgIntervalForNotes(): String {
I'd call this `getAvgIntervalForNotes` - work occurs, and `get` implies that it's a quick operation

2022-09-14 09:55 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
> +    fun avgIntervalOfNote() = avgInterval(note())
What is the format for doing that?

2022-09-14 16:44 UTC, david-allison approved these changes
Beauty

2022-09-16 11:39 UTC, viciousAegis commented
Needs #12400 to merge first

2022-09-16 12:57 UTC, viciousAegis commented
Ready 👍

2022-09-16 13:13 UTC, Arthur-Milchior approved these changes

2022-09-16 15:06 UTC, david-allison commented
This is in `main`, this PR needs to be rebased once `main` is green again

2022-09-17 14:07 UTC, Arthur-Milchior commented
I resolved the conflict

2022-09-17 14:13 UTC, Arthur-Milchior approved these changes

2022-09-17 14:13 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
> +    fun avgInterval(note: Note): Int? {
Personally, I'd even go with 
```kotlin
    fun avgInterval(note: Note) = 
        note.
        cards().
        filter { it.type != Consts.CARD_TYPE_NEW && it.type != Consts.CARD_TYPE_LRN }.
        average { it.ivl }?.
        toInt()
```
or even
```Kotlin
    fun Note.avgInterval() =
        cards().
        filter { it.type != Consts.CARD_TYPE_NEW && it.type != Consts.CARD_TYPE_LRN }.
        average { it.ivl }?.
        toInt()
```

2022-09-17 16:47 UTC, merged