Make things rounder and stop screaming at users
ankidroid/Anki-Android pull request #12409
Opened 2022-09-15 18:25 UTC by oakkitten

For the most part this makes various popup corners rounder and removes button labels in ALL CAPS. Roundness now follows the default Android 11 looks. Also, menus with icons were tweaked to have better looking padding and regular colors. I also changed a few things around the stuff I touched. As usual, please see individual commit messages for details.

This does not cover everything, particularly in places that might require significant overhaul. Notably,

* Filter by flag in Card browser menu—hopefully this is turned into a chip;
* Editor Tags & Cards buttons—these probably better be reworked into something else;
* Advanced editor—I think it should be removed altogether;
* Crop image—it does not follow app theming at all;
* Deck options—this one is fine on recent Android versions but shows jagged edges on 6. It would probably be better to deal with this by rooting out all the hacky stuff from it;
* TEXT in Statistics → Overview;
* Probably I missed something else?

Anyway, screenshots. Left: before; right: after.

<img src="https://user-images.githubusercontent.com/1710718/190480527-365eece3-89c4-4855-b2bf-faeb79f91064.png" width=300><img src="https://user-images.githubusercontent.com/1710718/190480163-1e3c18a4-56c1-4ece-9474-8ed44dc4abd1.png" width=300>
<img src="https://user-images.githubusercontent.com/1710718/190480165-3e5ce484-7c76-44a8-8fc8-bba1fdd7a3f8.png" width=300><img src="https://user-images.githubusercontent.com/1710718/190480168-6e81b8b0-8de4-41aa-8fef-c5ec235e0a07.png" width=300>
<img src="https://user-images.githubusercontent.com/1710718/190480169-46d01290-ec61-4006-87fa-f23e65b9f108.png" width=300><img src="https://user-images.githubusercontent.com/1710718/190480172-298b5ee0-8850-4ab6-b365-83e805465fc6.png" width=300>
<img src="https://user-images.githubusercontent.com/1710718/190480176-724bb1d3-e52e-45c2-9564-ac7ed68afbb8.png" width=300><img src="https://user-images.githubusercontent.com/1710718/190480180-f1a4b280-0414-48ec-8cf3-979025a7435d.png" width=300>
<img src="https://user-images.githubusercontent.com/1710718/190480182-dbb148da-df52-4a32-956d-c8305dbb6aea.png" width=300><img src="https://user-images.githubusercontent.com/1710718/190480184-1dbc23c3-0507-4a30-8a9d-7e7261102bf7.png" width=300>
<img src="https://user-images.githubusercontent.com/1710718/190480185-6e78cf31-ac05-41c1-8a0e-2d56fd99d5fe.png" width=300><img src="https://user-images.githubusercontent.com/1710718/190480189-f38839c9-bac5-4766-a93f-ddb37a02bff1.png" width=300>
<img src="https://user-images.githubusercontent.com/1710718/190480192-88ce6a10-2193-46e1-ae08-24d04a09e16e.png" width=300><img src="https://user-images.githubusercontent.com/1710718/190480193-7035b357-e0c0-409f-8058-a54e06fd51b1.png" width=300>
<img src="https://user-images.githubusercontent.com/1710718/190480196-0b6d0990-97f5-4ffe-b15b-7a8bc4431068.png" width=300><img src="https://user-images.githubusercontent.com/1710718/190480199-d8a1c299-47c8-4ba2-9c7e-6168f84aa083.png" width=300>
<img src="https://user-images.githubusercontent.com/1710718/190480201-51f08f94-b081-446a-8e31-98ee9ec9cbf9.png" width=300><img src="https://user-images.githubusercontent.com/1710718/190480204-b4569ceb-48fb-4915-8e52-8aaf1689dbc2.png" width=300>
<img src="https://user-images.githubusercontent.com/1710718/190480208-40ce2eb9-c69e-4549-81ea-f8b3b903fd79.png" width=300><img src="https://user-images.githubusercontent.com/1710718/190480211-d97688a5-eebd-4ee8-ac1c-47ad321bd282.png" width=300>
<img src="https://user-images.githubusercontent.com/1710718/190480212-aaf17fe6-01bb-41e1-81e8-3c75853d5b1d.png" width=300><img src="https://user-images.githubusercontent.com/1710718/190480214-327b8f04-cb1c-4841-b77a-f82fbc7ba8a6.png" width=300>
<img src="https://user-images.githubusercontent.com/1710718/190480215-4704e1bf-d00e-4750-b6e2-494676d91ec1.png" width=300><img src="https://user-images.githubusercontent.com/1710718/190480216-e66ab3b5-85d6-4664-9b05-22e3a67f9c80.png" width=300>
<img src="https://user-images.githubusercontent.com/1710718/190480218-3908dd00-1023-46d0-8cd9-d58b6fa2f637.png" width=300><img src="https://user-images.githubusercontent.com/1710718/190480220-9c584b53-1f4b-404b-8df7-98eb07e1dd6d.png" width=300>
<img src="https://user-images.githubusercontent.com/1710718/190480222-edd1b40c-e1a3-44ed-a396-d2e229f985fa.png" width=300><img src="https://user-images.githubusercontent.com/1710718/190480223-8da0f723-5981-4dd1-950c-cc56b469cc37.png" width=300>
<img src="https://user-images.githubusercontent.com/1710718/190480225-0c584fe9-6efd-4a42-bbce-5c5bd8054b32.png" width=300><img src="https://user-images.githubusercontent.com/1710718/190480228-b18cd459-3753-4da5-b799-3092f531e193.png" width=300>
<img src="https://user-images.githubusercontent.com/1710718/190480232-7a72cfe0-2e46-43f6-9e56-ea4040211dde.png" width=300><img src="https://user-images.githubusercontent.com/1710718/190480233-af4d149f-9ffe-451a-bf62-1fe91ca046f1.png" width=300>
<img src="https://user-images.githubusercontent.com/1710718/190480235-e3908957-c124-4dd7-bbb6-be60795d693d.png" width=300><img src="https://user-images.githubusercontent.com/1710718/190480238-6eade627-4ae9-4a32-ac72-535ee5a69e84.png" width=300>
<img src="https://user-images.githubusercontent.com/1710718/190480240-1bfb0c05-4c65-45a8-a9b1-d5f88a4bde92.png" width=300><img src="https://user-images.githubusercontent.com/1710718/190480241-70ba22f9-7627-4a03-b648-6f5c0daf8f78.png" width=300>

I suppose the next big step would be to fully move to material theming. At this point gradual changes become counterproductive; I'd love to rip out every customization, switch to material and rebuild the UI top down. Big big work. Some of the above points should be addressed first though.

Accessibility scanner complains about the white text on blue/gray background in tab layout. This is an ongoing problem with the toolbar color being too light in light themes and should be solved by changing toolbar color.

## How Has This Been Tested?

Manually tested on my Xiaomi Mi A2 (Android 11) and Motorola Moto G 1st Gen (Android 6).

## Checklist

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-15 19:32 UTC, BrayanDSO commented
Overall, I really like the changes and agree with the path to take about the UI. I don't have time to review it right now, but I should do it on the weekend if nobody else beats me up.

About the points on the PR description, I agree with them, although I don't recommend spending time on Deck options or Statistics, as they eventually are going to be replaced by upstream's HTML pages when the new backend is the default

And I would include Filtered Deck options on the pending list, which is quite hacky as well

Also this have an Lint issue

2022-09-16 13:41 UTC, oakkitten commented
Updated to fix the lint issue. Also I found a menu with flags in Card browser so I dealt with that as well, and I decided that at this point it's better to go recursive with fixing up the menus.

2022-09-17 12:33 UTC, BrayanDSO requested changes
Overall, LGTM. My review comments are only nits.

The only thing that is blocking to me is the bottom navigation's pill background contrast (I guess that the same may apply to the night themes).

![image](https://user-images.githubusercontent.com/69634269/190856742-529a42b1-3620-4ab0-9db1-921f161c0286.png)
![image](https://user-images.githubusercontent.com/69634269/190856751-8f9370d6-d345-4e59-bb8b-d956fb0f544f.png)

I know that before the PR, it didn't pass the accessibility scanner either, but this makes the contrast ratio even lower and it's best to move forward.

2022-09-17 12:33 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/utils/MenuUtils.kt
> + */
```suggestion
/**
 * Recursively tints the icons of the items of the given overflow or popup menu
 * with the color specified in the theme with [R.attr.overflowAndPopupMenuIconColor]. 
 * Has no effect for items that have no icon.
 */
```

2022-09-17 12:33 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
> +     *
unnecessary. The javadoc is for the method, so clearly it's speaking about it

2022-09-17 12:33 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
> +        //   If duplicate names are not undesirable, add a comment stating so.
just flagging so someone remembers to create an issue later

2022-09-17 12:33 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
> +        //   that you are cloning. I suggest reworking the strings so this is less confusing.
ditto

2022-09-18 15:28 UTC, snowtimeglass commented
The rounder corners look good.

>Also, menus with icons were tweaked to have better looking padding and regular colors. 

@oakkitten Personally, about the color of the icons of the menu of Study screen, I like and am attached to the current blue one, 
![image](https://user-images.githubusercontent.com/10436072/190913592-f975cb3e-af65-466d-8154-c9625ea0a95f.png)
but, as you probably think, it may not be the standard style of the latest Material Design. I've thought so since seeing the following the designs of Google Chrome and Gmail. I've begun to prepare myself to say goodbye to the current blue icons.
![image](https://user-images.githubusercontent.com/10436072/190912282-7610fff4-6970-4491-9b16-ff8822810f80.png)

>Accessibility scanner complains about the white text on blue/gray background in tab layout. This is an ongoing problem with the toolbar color being too light in light themes and should be solved by changing toolbar color.

I support the solution like the following one, using white or pale gray or pale blue. Google Chrome and Gmail do so. 

>- White theme with dark text (instead of every theme having light text)

_Originally posted by @nickdvlpr in https://github.com/ankidroid/Anki-Android/issues/5126#issuecomment-451238994_

![image](https://user-images.githubusercontent.com/10436072/190911861-0b962aec-aa19-46c1-b0b4-fc17d79e5945.png)



![image](https://user-images.githubusercontent.com/10436072/190911824-1077c95f-dc31-4106-b4f0-626011259645.png)

_Originally posted by @nickdvlpr in https://github.com/ankidroid/Anki-Android/issues/5126#issue-383325736_

Blue toolbar doesn't seem to suit the dark gray icons (even if the color of the bar becomes darker). 
![image](https://user-images.githubusercontent.com/10436072/190913019-78e36a6e-ef52-463f-b931-10bcd3f4b883.png)

2022-09-23 16:14 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
> +     *
Done

2022-09-23 16:14 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/utils/MenuUtils.kt
> + */
Done, I slightly changed the wording though

2022-09-23 17:11 UTC, oakkitten commented
Rebased to address some of the suggestions. I have absolutely no idea what's going on with the failing unit tests here.

> The only thing that is blocking to me is the bottom navigation's pill background contrast

This is a problem, but I think this change is a step in the right direction. Previously it wasn't immediately clear which item is selected, as you can have both darker and lighter color for selection. Of course, the big clue is that of the three items only one can be selected, but this is still confusing. This changes the behavior to a more standard, Android way, and the problem will disappear once the toolbar color is changed to a light color like @snowtimeglass mentions.

> but, as you probably think, it may not be the standard style of the latest Material Design. I've thought so since seeing the following the designs of Google Chrome and Gmail. I've begun to prepare myself to say goodbye to the current blue icons.

I think I would prefer the icons to be the same color as text. Blue toolbar indeed seems to be not agreeing with the dark grey icons somewhat, but if the icons are the same color as text, there's the agreement! I definitely don't like the blue color though. I didn't change it all the way to the color I like because this is probably best done as a part of a PR that changes the entire theme. I didn't want to make such decisions just yet so opted for what seems to be the more standard and uncontroversial color.

2022-09-23 21:18 UTC, BrayanDSO commented
1: CI is broken

2: I'm okay with the light pill color depending on the time frame of changing the bars colors, as I'm already foreseeing someone complaining about the low contrast in the future. This will probably take some time/discussion, as this is a "big" change on the app appearance. I think that there is a `colorPrimaryDark` attribute already chosen for `Light` and `Plain` themes, which may be a good temporary solution while the bar's color isn't changed.

2022-09-24 11:42 UTC, oakkitten commented
I was thinking about inverting the colors, displaying a fully white pill and making the icon itself blue. I didn't go with it as this effectively makes the icon appear flipped. These icons need to be changed anyway, I guess I just might draw some that can be inverted, how about this? I planned to do this later but might as well do it now.

2022-09-24 12:24 UTC, BrayanDSO commented
👍🏻

2022-09-24 12:59 UTC, oakkitten commented
Updated to include this. What do you think?
<img src="https://user-images.githubusercontent.com/1710718/192099234-c1e77235-b9a9-4538-bdb7-45a12cc27104.png" width=300>

2022-09-25 10:56 UTC, BrayanDSO commented
Fine by me. I've reran CI tests. 

Optional: have you tried using filled icons when they are selected? (as Material recommends https://m3.material.io/components/navigation-bar/overview)

2022-09-25 14:11 UTC, oakkitten commented
I don't know what's happening with CI, tests pass (on ubuntu/macos) [in my repo](https://github.com/oakkitten/Anki-Android/actions/runs/3122322628).

I thought about filled icons, but
  * It would be better for consistency to make the CSS icon behave similarly. I am not sure what'd be a good way to do that, simply outlining the letters CSS seems like a bad idea;
  * TBH I just don't want to deal with this right now, and it can be done later anyway.

2022-09-25 16:57 UTC, BrayanDSO commented
Odd. I've rerun 5 times I think? My PC is currently busy, so I can't run it locally for the moment.

About the filled icons, I don't think it's bad to have one icon that is not outlined (in this case, CSS). You can have Google Maps as an example. But that's an issue for another day.

2022-09-29 00:04 UTC, BrayanDSO commented
@oakkitten finally got to run this on my PC and the same errors appear here.

2022-09-29 16:15 UTC, oakkitten commented
Rebased onto current main, also changing `DrawableWrapper` to `DrawableWrapperCompat` to appease CI.

2022-09-30 12:57 UTC, BrayanDSO approved these changes

2022-10-09 18:08 UTC, BrayanDSO commented
CI fails

2022-10-13 14:22 UTC, mikehardy commented
I think the before / afters are a tangible user-visible improvement and will go a long way towards reducing the "Ugh, this app looks like it's from 2008" complaints on our play store reviews

Needs a compile fix 

>  e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt: (129, 17): Unresolved reference: addNewNoteTypeDialog

2022-10-13 21:25 UTC, mikehardy commented
The conflict has somehow survived your force push :thinking:

2022-10-13 21:57 UTC, oakkitten commented
It was another one. 🤯 Hope it's good now

2022-10-14 20:39 UTC, mikehardy approved these changes
Sam Elliot approves

![hat-tip-gif-6](https://user-images.githubusercontent.com/782704/195939380-6e6a38cc-8f17-45ae-b184-4b8842f352c3.gif)

2022-10-14 20:39 UTC, merged