added CompatV33
ankidroid/Anki-Android pull request #12410
Opened 2022-09-15 20:51 UTC by criticalAY

## Intent.getSerializable

## Purpose / Description
deprecation: compileSdk 33 issues #12364

## Fixes
Added compatv33 file and made required changes in the other files

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-15 21:02 UTC, david-allison requested changes
Looks good, few improvements

2022-09-15 21:34 UTC, criticalAY commented
> Looks good, few improvements

implemented the required changes

2022-09-15 21:37 UTC, david-allison approved these changes
Looks great, thanks!

2022-09-16 00:47 UTC, BrayanDSO approved these changes
nice! thanks a lot for this

2022-09-16 00:48 UTC, merged