Localised the string "clear"
ankidroid/Anki-Android pull request #12429
Opened 2022-09-17 19:16 UTC by pratyaksh1610

## Purpose / Description

Localised the string "clear"

## Fixes
fixes #12426

## How Has This Been Tested?

Tested on physical device.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

![a](https://user-images.githubusercontent.com/76740999/190873073-c084f89d-314e-47f4-b186-f245806c4e8f.jpeg)

2022-09-17 20:43 UTC, viciousAegis requested changes
Lint check failing because of duplicate strings

2022-09-17 20:43 UTC, viciousAegis commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="clear_filter">Clear</string>
@pratyaksh1610, as Brayan mentioned in the issue, there is already a string resource for `Clear`, which can be used here (lint also failing due to the duplicate value). So instead of creating a new resource, you can either use the one already present in the codebase, or you can add a `comment=` attribute in both the instances to differentiate their uses (I would prefer the former)

2022-09-17 20:59 UTC, pratyaksh1610 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="clear_filter">Clear</string>
Done

2022-09-17 21:05 UTC, viciousAegis commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="clear_filter">Clear</string>
Can you force push the branch to only include the correct commit? We would like to keep commit history clean, so you should squash commits where you add and remove code

2022-09-17 21:06 UTC, BrayanDSO approved these changes
LGTM. As a note: you could have rebased the PR, so we'd have only one commit and this would be easier to review

2022-09-17 21:09 UTC, pratyaksh1610 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="clear_filter">Clear</string>
Actually I am getting issue by doing some changes from git , it shows `no kotlin staged files found`, but they are already present, that's why did this way.
Can you help me out with this error .
Thanks.

2022-09-17 21:30 UTC, mikehardy commented
strings PR just merged

2022-09-18 06:16 UTC, ShridharGoel approved these changes

2022-09-18 06:16 UTC, ShridharGoel commented
This no longer contains changes in string resources.

2022-09-18 06:16 UTC, merged