Compat33 parcelable fix
ankidroid/Anki-Android pull request #12422
Opened 2022-09-16 19:11 UTC by criticalAY

##deprecation: compileSdk 33 issues #12364

## fixes the issue  Intent.getParcelableExtra 

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-16 19:35 UTC, david-allison requested changes
Thanks!

In future, please rebase your changes onto `main`, rather than merging. There shouldn't be merge commits in a PR that you send

There are 4 commits here, whereas there should only be one.

2022-09-16 19:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
> + *CRITI
unnecessary change

2022-09-16 19:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.kt
> +        val animation = intent.getParcelableExtraCompat<Parcelable>(FINISH_ANIMATION_EXTRA)
```
        val animation = intent.getParcelableExtraCompat<ActivityTransitionAnimation.Direction>(FINISH_ANIMATION_EXTRA)
```

And use  `if (animation != null)` below

2022-09-16 19:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
>          if (animation is ActivityTransitionAnimation.Direction) {
same comment as above: we know the class we want, pass that in

2022-09-16 19:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        val animation = intent!!.getParcelableExtraCompat<Parcelable>(FINISH_ANIMATION_EXTRA)
This shouldn't have been changed to `intent!!` as intent is nullable.

@BrayanDSO Can you confirm that this is meant to use `getIntent()` (I feel the docs could be a little clearer)

2022-09-16 19:49 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        val animation = intent!!.getParcelableExtraCompat<Parcelable>(FINISH_ANIMATION_EXTRA)
@david-allison  getIntent() need to be there then?

2022-09-16 19:57 UTC, criticalAY commented
> Thanks!
> 
> Please rebase this so the commit messages are useful to future developers
> 
> In future, please rebase your changes onto `main`, rather than merging. There shouldn't be merge commits in a PR that you send
> 
> There are 4 commits here, whereas there should only be one.

Will keep that in mind in the future Thanks!

2022-09-16 20:28 UTC, criticalAY commented
have done the changes

2022-09-16 23:10 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        val animation = intent!!.getParcelableExtraCompat<Parcelable>(FINISH_ANIMATION_EXTRA)
Here I want the activity's intent, not the the method argument with the name of `intent`.
Changing getIntent to `this.intent` may help here

2022-09-17 06:20 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        val animation = intent!!.getParcelableExtraCompat<Parcelable>(FINISH_ANIMATION_EXTRA)
this.intent would work fine ?

2022-09-17 06:36 UTC, criticalAY commented
I have changed the `intent!!` to the required one

2022-09-17 21:02 UTC, BrayanDSO requested changes
Left some comments. Should be easy to fix

2022-09-17 21:23 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
> +        className: Class<T>
yes but there was some confusion so clearly mentioned that clazz is a class name

2022-09-17 21:48 UTC, david-allison approved these changes

2022-09-17 22:59 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
> +        className: Class<T>
This doesn't take a class name. If it did, it would use `String` as type, but it uses `Class<T>` which literally means a class. As `class` is a protected name, `clazz` is used instead

2022-09-18 01:28 UTC, BrayanDSO approved these changes

2022-09-18 01:30 UTC, merged