[GSoC] Coroutines migration add field
ankidroid/Anki-Android pull request #12434
Opened 2022-09-18 14:43 UTC by divyansh-dxn

## Fixes
Fixes a part of #7108

## How Has This Been Tested?

Passes unit tests and on Pixel 4 API 31
HAVEN'T TESTED IT YET ON REAL DEVICE, will update when done

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-18 19:55 UTC, ShridharGoel requested changes

2022-09-18 19:55 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +            Timber.d("doInBackgroundRepositionField")
It should be `doInBackgroundAddField`. Even though you have taken this from the older code, it's good to fix such things.

2022-09-19 15:43 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +            Timber.d("doInBackgroundRepositionField")
missed it, but done now.

2022-09-19 16:41 UTC, lukstbit approved these changes

2022-09-19 16:49 UTC, ShridharGoel approved these changes

2022-09-19 16:50 UTC, merged