Bundle Serializable updated for API33
ankidroid/Anki-Android pull request #12433
Opened 2022-09-18 07:41 UTC by criticalAY

## deprecation: compileSdk 33 issues #12364 

## Purpose 
 Bundle.getSerializable fix

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-18 12:34 UTC, ShridharGoel requested changes

2022-09-18 12:34 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
> +        clazz: Class<T>
`clazz` is not being used here.

2022-09-18 12:34 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
> +            return null
Remove `return` from here since it is already there outside try-catch.

2022-09-18 13:30 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
> +            return null
ok gotchu!

2022-09-18 14:26 UTC, ShridharGoel approved these changes

2022-09-18 14:51 UTC, criticalAY commented
@ShridharGoel I was trying to rebase the code this 3rd commit came can we handle it here only as this was unnecessary.

2022-09-18 14:57 UTC, ShridharGoel commented
@criticalAY We can use squash-merge but it would be good to learn and practice about rebasing properly. You can search about it.

2022-09-18 15:02 UTC, criticalAY commented
> @criticalAY We can use squash-merge here but it would be good to learn and practice about rebasing properly. You can search about it.

yes I am trying to

2022-09-18 17:18 UTC, mikehardy requested changes
I'm curious about the type system usage in SharedDecksDownloadFragment as commented directly in place

2022-09-18 17:18 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        val fileToBeDownloaded = arguments?.getSerializableCompat<Serializable>(DOWNLOAD_FILE) as DownloadFile
Out of curiosity, since the Compat methods have all sorts of casting and return type logic, why are we using the Compat function here *then* casting via `as DownloadFile` ?

Should it be 

```suggestion
        val fileToBeDownloaded = arguments?.getSerializableCompat<DownloadFile>(DOWNLOAD_FILE)`
```

...or similar, or am I missing something?

2022-09-18 17:27 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        val fileToBeDownloaded = arguments?.getSerializableCompat<Serializable>(DOWNLOAD_FILE) as DownloadFile
that was giving an error at line 111 because it requires `DownloadFile` but doing so gives `DownloadFile?`

2022-09-18 17:31 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        val fileToBeDownloaded = arguments?.getSerializableCompat<Serializable>(DOWNLOAD_FILE) as DownloadFile
`val fileToBeDownloaded = arguments?.getSerializableCompat<DownloadFile>(DOWNLOAD_FILE)!!` can  we change that to this?

2022-09-18 17:32 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        val fileToBeDownloaded = arguments?.getSerializableCompat<Serializable>(DOWNLOAD_FILE) as DownloadFile
So...if I am understanding correctly, it's entirely possible that the de-serialization fails and does not return something.
And the choice is between casting it directly as non-Null DownloadFile or handling the nullability.
Why not handle the nullability? Timber.w the unexpected error case and I think we have a generic "Something went wrong" error message dialog we can pop up?

2022-09-18 17:33 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        val fileToBeDownloaded = arguments?.getSerializableCompat<Serializable>(DOWNLOAD_FILE) as DownloadFile
It is always possible to corrupt a type system with direct casting or ignore real nullability concerns with !!, but doing either inevitably leads to errors when the assumption you made while forcing (via cast or !!) is unexpectedly incorrect

Type systems are there to help, and if we agree the types are correct and the nullability is correct in the type system, it's best to pay attention to that instead of forcefully disregarding it

2022-09-18 17:43 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        val fileToBeDownloaded = arguments?.getSerializableCompat<Serializable>(DOWNLOAD_FILE) as DownloadFile
> So...if I am understanding correctly, it's entirely possible that the de-serialization fails and does not return something. And the choice is between casting it directly as non-Null DownloadFile or handling the nullability. Why not handle the nullability? Timber.w the unexpected error case and I think we have a generic "Something went wrong" error message dialog we can pop up?

there is a try again option that pops up I guess because it is given down there.

2022-09-18 18:20 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        val fileToBeDownloaded = arguments?.getSerializableCompat<Serializable>(DOWNLOAD_FILE) as DownloadFile
So do we need to change anything here or we are good to go ?

2022-09-18 23:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        val fileToBeDownloaded = arguments?.getSerializableCompat<Serializable>(DOWNLOAD_FILE) as DownloadFile
If you read the code, the fragment should always be initialised

* with arguments
* which include `DOWNLOAD_FILE`

It is an error otherwise. I'm happy to fail at this point if the contract isn't satisfied.

```suggestion
        val fileToBeDownloaded = requireArguments().getSerializableCompat<DownloadFile>(DOWNLOAD_FILE)!!
```

2022-09-18 23:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        val fileToBeDownloaded = arguments?.getSerializableCompat<Serializable>(DOWNLOAD_FILE) as DownloadFile
If you read the code, the fragment should always be initialised

* with arguments
* which include `DOWNLOAD_FILE`

It is an error otherwise. I'm happy to fail at this point if the contract isn't satisfied.

```suggestion
        val fileToBeDownloaded = requireArguments().getSerializableCompat<DownloadFile>(DOWNLOAD_FILE)!!
```

2022-09-18 23:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
>          } catch (e: ClassCastException) {
```kotlin
        try {
            mTemplateChanges = bundle.getSerializableCompat("mTemplateChanges")!!
        } catch (e: Exception) {
```

2022-09-18 23:44 UTC, david-allison requested changes

2022-09-18 23:44 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +            return intent.extras!!.getSerializableCompat(EXTRA_FIELD) as IField?
```suggestion
            return intent.extras!!.getSerializableCompat<IField>(EXTRA_FIELD)
```

2022-09-18 23:44 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/BundleUtils.kt
>      }
Could `@KotlinCleanup("inline this")` be added

2022-09-18 23:46 UTC, david-allison commented
Review feedback: spend a little more time understanding the context of the calling code.

You're in the best position to understand what's being done, and whether the code can be simplified (given you know the code being called well enough to put it behind `Compat`)

2022-09-18 23:47 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        val fileToBeDownloaded = arguments?.getSerializableCompat<Serializable>(DOWNLOAD_FILE) as DownloadFile
If it's truly always initialized, I'd rather see a !! then a cast then, works for me

2022-09-19 00:51 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/utils/BundleUtils.kt
>      }
Hm. The repo doesn't have a preference on its code style for using `=` on functions (this is what I suppose you mean by `inline this`) instead of `return`. 

I particularly don't want to spend anyone's (either reviewer's or programmer's) energy and time on this matter, because it doesn't matter. So, to me, whatever way the implementer wants is fine. 

Therefore, I believe that this cleanup should not be added, so we spare the author's time adding the cleanup, and the reviewers' time if someone do this cleanup in the future

2022-09-19 03:04 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/BundleUtils.kt
>      }
inline: use the IDE's inline functionality to remove the function (I'd ask here but don't want to enforce a 'you must rebase to two commits before we merge this' just yet with a new contributor).

2022-09-19 03:04 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/BundleUtils.kt
>      }
![Screenshot 2022-09-19 at 04 04 34](https://user-images.githubusercontent.com/62114487/190943481-c58f609e-4355-44ca-b79f-35a9e8998871.png)

2022-09-19 03:16 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/utils/BundleUtils.kt
>      }
ahhh sorry I did get this last one ?

2022-09-19 03:23 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/BundleUtils.kt
>      }
Add `@KotlinCleanup("inline this")` above the method

2022-09-19 15:00 UTC, criticalAY commented
Can we go ahead now?

2022-09-19 23:46 UTC, david-allison commented
Look at the checks below, all of the unit tests and the code quality checks are failing:

```
> Task :AnkiDroid:ktlintMainSourceSetCheck FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt:462:1 Unexpected indentation (10) (should be 12)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt:43:1 Unused import
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt:36:1 Unused import
```

2022-09-20 02:38 UTC, criticalAY commented
hey! I can we please close this PR as I can't fix this on my end so I have made a new PR sorry

2022-09-20 12:56 UTC, mikehardy commented
Also, for what it's worth, I see two "Merge branch..." commits in this PR commit chain.
I strongly suggest learning how to use git rebase, so you can just pull changes from main into your branch *without* a merge commit.
We do not like merge commits in this repo (it is our preference to avoid them) and encourage a clean + linear commit history via rebasing.

I will close it per request

2022-09-20 12:56 UTC, closed without merging

2022-09-20 15:00 UTC, criticalAY commented
> hat it's worth, I see two "Merge branch..." commits in this PR commit chain.
> I strongly suggest learning how to use git rebase,

Thankyou! Have made a new PR to account for these changes properly