Note service cleaning
ankidroid/Anki-Android pull request #12438
Opened 2022-09-18 17:46 UTC by Arthur-Milchior

2022-09-18 21:16 UTC, BrayanDSO approved these changes
LGTM

2022-09-18 23:33 UTC, david-allison requested changes
I like this.

A few questions. One issue with the imports being changed (which can be split out into a project-level issue to investigate).

2022-09-18 23:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
> -object NoteService {
why?

2022-09-18 23:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +import android.content.BroadcastReceiver
I don't get this change. It doesn't happen automatically when I commit from a0eed20e8232d02fabda38660fd02e53e711c993, and we should enforce this with a lint rule one way or the other, rather than have automatic tools expand and contract the imports.

* You've expanded `android.content.*` into its constituent imports
* You've condensed into imports: `import com.ichi2.anki.servicelayer.SchedulerService.*`

It feels like either I or you have settings which are inconsistent with the project

2022-09-18 23:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/CardService.kt
> + * This program is free software; you can redistribute it and/or modify it under        *
ideally needs copyright

2022-09-19 11:25 UTC, viciousAegis approved these changes
Great!

2022-09-19 19:00 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
> -object NoteService {
My understanding is that `object` where useful when we needed java, as it could not directly access at the package level. Now that we are pure Kotlin, they don't really have any interest, except if we actually want to keep seeing the name in the function call.
However, `NoteService.createEmptyNote(mEditorNote!!.model())` is less readable than `createEmptyNote(mEditorNote!!.model())` and same for every other examples I see.

This makes lines shorter in every place that uses its methods. They are also technically shorter in this file, but I'll admit the identation does not impede readability as much.

2022-09-19 19:03 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/CardService.kt
> + * This program is free software; you can redistribute it and/or modify it under        *
The authors of NoteService were not relevant here. All moved lines were by @viciousAegis I believe. This VA didn't add his copyright, it seems strange to add it for him. But I can if he wants

2022-09-19 19:07 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +import android.content.BroadcastReceiver
I almost never touch import by hand. Leaving it to the IDE and automated cleaning tool to deal with it. I clearly admit that the way it dealt with this files makes no sense to me at all.
I'm fine with reverting, or being consistent. I didn't pay attention to it, but I see your point.

For what it's worth https://github.com/ankidroid/Anki-Android/wiki/Code-style#imported-classes-should-always-be-listed-explicitly requires importing classes explicitly. But the change in https://github.com/ankidroid/Anki-Android/pull/12438/files/b22bc5d23b10c1d3bfc01f5ca42196d7456509b3#diff-6d9f7ea7bba9cc72513b5078633cee9bdbbd1ea7646114869679f302ad607459R73 is itself inconsistent with this rule.

In any case, I guess it would make sense to ensure linter respect one rules

2023-11-24 12:50 UTC, mikehardy commented
was curious if this was retrievable, massive pile of conflicts (had to open it to see) and no activity since Feb
Going to close this and delete the branch since it's in the main repo

2023-11-24 12:50 UTC, closed without merging