Fix crash due to probable race condition
ankidroid/Anki-Android pull request #12459
Opened 2022-09-20 02:00 UTC by dae

Resuming the app would trigger a redraw of the counts, and this probably coincided with a card being automatically answered.

Closes #12453

2022-09-20 14:02 UTC, mikehardy requested changes
Thanks a bunch for all of these, the runTest{} change should be a big help as the false-negative rate right now is awful for S/N

Just a couple comments hoping for sage advice in form of annotations on one of the fixes

2022-09-20 14:02 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
> +        col.db.execute("update col set mod = 0")
No philosophical problem with the pragmatism, however, what's the future state look like for this code?
My goal for the question is to have an annotation in here indicating it needs cleanup, ideally with a note (or comment) indicating "Hey future dev, when we're all on the new schema, you'll want to do this instead..."

2022-09-20 14:02 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
> +        val updatedMod = col.db.queryScalar("select mod from col")
same hope here, for annotation with comment for future dev on what the future-state should look like with new schema only

2022-09-21 03:24 UTC, dae commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
> +        col.db.execute("update col set mod = 0")
I've added a RustCleanup annotation (though in the grand scheme of things, it's not a big deal if the test is left as it is)

2022-09-21 12:25 UTC, mikehardy approved these changes
Great - looks good to me, thanks again

2022-09-21 12:25 UTC, merged