Migrated CollectionTask.Flag to Coroutines
ankidroid/Anki-Android pull request #12462
Opened 2022-09-20 20:54 UTC by divyansh-dxn

Previous implementation of Flag was really messy and very hard to follow unless you've gone line by line code (took me enough time to understand). Currently it is single commit, and I couldn't figure out to break this commit into smaller ones. Will try though.  I guess this migration makes it really easy to follow up what happens and where. 

## Fixes
Fixes a part of #7108

## How Has This Been Tested?
Unit tests and Pixel 4a API 32

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-21 18:08 UTC, lukstbit requested changes
Looks ok with two minor issues.

2022-09-21 18:08 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                col.db.database.beginTransaction()
The collection is already(from withCol) available so there's no need for `col.db....`.

2022-09-21 18:08 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        updateCardsInList(updatedCards)
Add a todo above this method:

```
// try to offload the cards processing in updateCardsInList() on a background thread, 
// otherwise it could hang the main thread
```

2022-09-22 10:52 UTC, lukstbit approved these changes

2022-09-26 20:27 UTC, ShridharGoel approved these changes

2022-09-26 20:27 UTC, merged