Uses Kotlin tuples
ankidroid/Anki-Android pull request #12465
Opened 2022-09-21 01:40 UTC by Arthur-Milchior

This has better typing.

2022-09-21 04:26 UTC, david-allison requested changes
In general, looks good. Thanks!

Diffs need to be cleaned up via fixing the imports which were unnecessarily changed)

2022-09-21 04:26 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +import android.os.Build
revert all unnecessary import changes

2022-09-21 04:26 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/Triple.kt
> -class Triple<First, Second, Triple> constructor(val first: First, val second: Second, val third: Triple)
Very surprised this compiled (it does!)

2022-09-23 09:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/Triple.kt
> -class Triple<First, Second, Triple> constructor(val first: First, val second: Second, val third: Triple)
why surprised?

2022-09-23 10:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/Triple.kt
> -class Triple<First, Second, Triple> constructor(val first: First, val second: Second, val third: Triple)
References weren't changed in the other files in this commit

2022-09-23 10:33 UTC, david-allison approved these changes

2022-09-23 13:27 UTC, merged