API 33 serializable bundle deprecation update
ankidroid/Anki-Android pull request #12463
Opened 2022-09-20 21:06 UTC by criticalAY

Fixes the deprecation of bundle.Serializable in new API33 or older versions

## Checklist

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-26 03:02 UTC, criticalAY commented
Can we please review this PR when we are free, I know we are busy and have a lot of work to do so whenever we are comfortable, Thanks!

2022-09-30 08:49 UTC, criticalAY commented
Hey! can we please review this PR?

2022-09-30 13:52 UTC, mikehardy requested changes
I'm not sure on the API choice for CompatV33, as indicated - I think if the clazz arguments is required for the future direct use of Bundle API, it should be in the compat interfaces and used in the calling code

2022-09-30 13:52 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
> +    override fun <T : Serializable?> getSerializable(bundle: Bundle, name: String, clazz: Class<T>): T? {
So the future state - when we are minSdkVersion >= 33, is that we will replace *all* uses of CompatHelper.getSerializable with the *direct* call to `bundle.getSerializable`

It takes two arguments, name and clazz

Yet the choice of API for the Compat interface has the second argument optional, meaning that the API is not *actually* compatible with the future direct use of bundle API.

2022-09-30 17:26 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
> +    override fun <T : Serializable?> getSerializable(bundle: Bundle, name: String, clazz: Class<T>): T? {
possible amendment? but we already discussed it in #12433. But still if we feel like changing things cool.

2022-09-30 17:34 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
> +    override fun <T : Serializable?> getSerializable(bundle: Bundle, name: String, clazz: Class<T>): T? {
Please point to the exact spot - with a link to the comment - where we discussed the mismatch between the direct use of the new API33 API and the Compat interface.

I only saw something about nullability.

2022-09-30 19:48 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
> +    override fun <T : Serializable?> getSerializable(bundle: Bundle, name: String, clazz: Class<T>): T? {
not the API 33 I was saying about this discussion only

2022-09-30 19:49 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
> +    override fun <T : Serializable?> getSerializable(bundle: Bundle, name: String, clazz: Class<T>): T? {
What's the possible solution you suggest ?

2022-09-30 20:23 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
> +    override fun <T : Serializable?> getSerializable(bundle: Bundle, name: String, clazz: Class<T>): T? {
> I think if the clazz arguments is required for the future direct use of Bundle API, it should be in the compat interfaces and used in the calling code

From my review comment. What's the point? In the future we will use the Bundle API directly. So the Compat interface should look as close as possible to the Bundle API. Usually the Compat interface looks like an argument list with 1) the object you cannot use directly because of compatibility needs with older APIs, 2) the complete list of arguments that are on the newly added API.

So cleanup, later when minSdkVersion advances far enough, is to just call the API directly by removing the Compat call and the object parameter

2022-09-30 20:37 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
> +    override fun <T : Serializable?> getSerializable(bundle: Bundle, name: String, clazz: Class<T>): T? {
there is Compat which is the interface, then CompatV21 (our current baseline) and CompatV33
All three are touched, as you have already done
*I am just talking about the shape of the API, the parameter list is the focus of my review request for changes*

Alter the parameter list.

2022-10-19 09:51 UTC, closed without merging