Fix night mode by bumping appcompat to 1.6.0-rc01
ankidroid/Anki-Android pull request #12461
Opened 2022-09-20 14:28 UTC by JalinWang

Night mode changing is broken by https://github.com/ankidroid/Anki-Android/pull/12343. This PR is going to fix it by bumping `appcompat` to [appcompat:1.6.0-rc01](https://developer.android.google.cn/jetpack/androidx/releases/appcompat#1.6.0-rc01).

fix https://github.com/ankidroid/Anki-Android/issues/12404#issuecomment-1252331711

2022-09-20 15:14 UTC, david-allison requested changes
Change is great, thanks so much for the investigation!!!

Could you include a regression test I included on the issue:

```kotlin
/*
 *  Copyright (c) 2022 David Allison <davidallisongithub@gmail.com>
 *
 *  This program is free software; you can redistribute it and/or modify it under
 *  the terms of the GNU General Public License as published by the Free Software
 *  Foundation; either version 3 of the License, or (at your option) any later
 *  version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT ANY
 *  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 *  PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with
 *  this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.ichi2.anki

import android.content.Intent
import android.content.res.Configuration
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.ichi2.themes.Theme
import com.ichi2.themes.Themes
import org.hamcrest.MatcherAssert.assertThat
import org.hamcrest.Matchers.equalTo
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class AnkiActivityTest : RobolectricTest() {
    @Test
    fun themeChangeIsValid() {
        val activity = startActivityNormallyOpenCollectionWithIntent(
            AnkiActivity::class.java, Intent()
        )
        assertThat(Themes.currentTheme, equalTo(Theme.LIGHT))

        val newConfig = Configuration(activity.resources.configuration)
        newConfig.uiMode = 33
        activity.onConfigurationChanged(newConfig)

        assertThat(Themes.currentTheme, equalTo(Theme.BLACK))
    }
}
```

2022-09-20 18:29 UTC, mikehardy approved these changes
I was specifically okay with the rc dep in conversation on this one after looking at appcompat development / release history.
David's ask for the regression test inclusion is right on - consider me an approve but pending that
Thanks!

2022-09-21 02:48 UTC, JalinWang commented
> Could you include a regression test I included on the issue:

Hi~ Is it okay now (about location or something of this sort)? I'm a bit of a novice.

> I was specifically okay with the rc dep in conversation on this one after looking at appcompat development / release history.

Thank you for the info in the preceding discussion as well as the approval!😀

2022-09-21 04:18 UTC, david-allison approved these changes

2022-09-21 04:18 UTC, david-allison commented
Beauty - thank you

2022-09-21 04:19 UTC, merged