NF: uses listOf instead of asList
ankidroid/Anki-Android pull request #12467
Opened 2022-09-21 02:23 UTC by Arthur-Milchior

Improve typing

2022-09-25 12:16 UTC, BrayanDSO requested changes

2022-09-25 12:16 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/template/ParsedNode.kt
>      }
```suggestion
    fun template_is_empty(vararg nonempty_fields: String): Boolean {
        return template_is_empty(nonempty_fields.toSet())
    }
```

the callers (only tests) always send non-null args, so the param can be made non-null

2022-09-25 12:16 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/template/Replacement.kt
> +        filters.map { it!! },
```suggestion
    constructor(key: String, vararg filters: String) : this(
        key,
        filters.toList(),
```
the callers (only tests) always send non-null args, so the param can be made non-null

2022-09-25 13:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/template/ParsedNode.kt
>      }
Your change is valid, but I don't think it belongs to this commit or even PR

2022-09-25 15:52 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
> +            var isVideo = listOf(*VIDEO_WHITELIST).contains(extension)
You probably can just say `var isVideo = extension in VIDEO_WHITELIST`

(I wonder if a better use of time would be to refactor entire methods/classes at once rather than changing the function that creates lists; if we assume that the methods will get eventually refactored this is just more work and git blame clutter.)

2022-09-25 15:56 UTC, BrayanDSO approved these changes

2022-09-25 17:51 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
> +            var isVideo = listOf(*VIDEO_WHITELIST).contains(extension)
I disagree. This commit could be made almost automatically, in a few minutes. Doing one class at a time will take far more time, since you need to go over everything.
Also, I believe it's far easier to review a commit that contains a single change over and over again, while a class correction will have plenty of different improvements, each require thoughts from the reviewer

2022-09-29 17:11 UTC, lukstbit approved these changes
OK.
Left three comments on kotlin cleanups that should be deleted as the changes in the PR fixed them. As those are not breaking I'll wait a bit and then merge to avoid conflicts on this.

2022-09-29 17:11 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
>              @KotlinCleanup("listOf")
This kotlin cleanup is not needed anymore as the change in the PR fixed it.

2022-09-29 21:13 UTC, Arthur-Milchior commented
Thanks @lukstbit 
pushed again

2022-09-29 21:36 UTC, merged