Migrated RepairCollection to Coroutines
ankidroid/Anki-Android pull request #12498
Opened 2022-09-23 18:10 UTC by divyansh-dxn

## Fixes
Fixes a part of #7108

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-27 07:53 UTC, lukstbit requested changes

2022-09-27 07:53 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
> -            Timber.i("RepairCollection: Closing collection")
Also add in your code the two Timber calls.

2022-09-27 07:53 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
> -    class RepairCollection : UnsafeTaskDelegate<Void, Boolean>() {
`UnsafeTaskDelegate` becomes unused as `RepairCollection` was its only child so delete that class as well.

2022-09-27 07:53 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                withCol {
Add the cleanup from `RepairCollection` as a todo here:

_// todo doesn't work on null collection-only on non-openable(still applicable with withCol?)_

2022-09-27 07:53 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> -                context.showCollectionErrorDialog()
This method call is not present in your code when result is false.

2022-09-27 17:34 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> -                context.showCollectionErrorDialog()
https://github.com/ankidroid/Anki-Android/pull/12498/files/15d4976693082a8fbec3b93693ccdc259b81e796#diff-1c9f8440ee3813eda89e500bf5db95d90730eda462a22fb54b2d832e8fb06e2cR1438-R1440

2022-09-27 18:09 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                withCol {
done

2022-09-27 18:09 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
> -    class RepairCollection : UnsafeTaskDelegate<Void, Boolean>() {
done

2022-09-27 18:28 UTC, Arthur-Milchior submitted a review, later dismissed
Still one question.
I guess we should squash

2022-09-27 18:28 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> -                context.showCollectionErrorDialog()
I don't understand your answer @divyansh-dxn . The line you selected in your link contains the showThemedToast but not the `context.showCollectionErrorDialog()`

2022-09-27 18:28 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
> -            Timber.i("RepairCollection: Closing collection")
Please wait until you have uploaded the code with the correction to resolve. It saves me time, as I was going to note the same things.
Or at least to ask you why you deleted those Timber; it may be justified, but have to be explained

2022-09-27 18:39 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> -                context.showCollectionErrorDialog()
Sorry I missed that one, I thought of showThemedToast only but indeed showCollectionErrorDialog is an important part of the failure because it shows what can be done to fix this.

2022-09-28 16:06 UTC, lukstbit approved these changes

2022-09-28 16:30 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
> -            Timber.i("RepairCollection: Closing collection")
Squashed the changes ...will be on the same commit now, so no issues.

2022-09-29 10:29 UTC, ShridharGoel approved these changes

2022-09-29 20:18 UTC, merged