bundle Parcelable API33 fixed
ankidroid/Anki-Android pull request #12505
Opened 2022-09-25 18:37 UTC by criticalAY

[[## Pull Request template
](deprecation: compileSdk 33 issues #12364)](deprecation: compileSdk 33 issues #12364)
## Purpose / Description
Bundle Parcelable fixed for API 33 and above

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-30 13:56 UTC, mikehardy requested changes

2022-09-30 13:56 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
> +        }
This doesn't look like it should be part of a Parcelable fix? Are your PRs intermingled?

2022-09-30 13:56 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
> +        return bundle.getParcelable(name, clazz)
If this is what the direct getParcelable calls look like, why do the callers of the compat interface not specify the second class argument? It seems like we won't be able to immediately convert to the direct API when we are at minSdkVersion >= 33 :thinking: ?

2022-10-02 11:48 UTC, criticalAY commented
I need a little help with it. Please

2022-10-02 13:09 UTC, david-allison commented
Specifically what do you need help with?

2022-10-02 13:39 UTC, criticalAY commented
> Specifically what do you need help with?

Mike stated that we need to use the clazz which is currently missing in the calling code and I am not able to figure out exactly how?

2022-10-02 20:35 UTC, mikehardy commented
I want our Compat APIs to all have this format:

`Compat.<name of the new API method that only works in higher APIs>(<object the API is on>, [<list of all arguments to the new API>])`

I am not sure I can state it any more clearly, except perhaps by example, which I believe I have already done a couple times but I'll try again in the hopes I communicate clearly.

If the [new method](https://developer.android.com/reference/android/os/Bundle#getSerializable(java.lang.String,%20java.lang.Class%3CT%3E)) is `public T getSerializable (String key, Class<T> clazz)`

Then I am expecting the Compat API to be

`Compat.getSerializable(String key, Class<t> clazz)`

I expect see that API in all the affected code. I expect to see:

`deserializedFoo = Compat.getSerializable(CONSTANT_WITH_KEY_NAME, foo::class.java)`

@david-allison am I crazy? I might be crazy. But what I'm looking for is a mechanical transformation, in the future, from the Compat API(s) to the direct APIs later as minSdkVersion moves up. I have been the one to trim older CompatV objects in the past, and when the APIs are as I describe, it is a dead simple process. That's what I want.

2022-10-02 20:50 UTC, criticalAY commented
> 

I am so sorry. I seriously don't have intentions to irritate you. 
But we have the new methods in compat 33, so we want these new methods to be also defined in the compat helper file adding extra paramter in there i.e. clazz ?

2022-10-02 21:14 UTC, mikehardy commented
Compat.kt is where all the APIs are defined for export.
CompatHelper just resolves the current runtime to the correct CompatV<nn>.kt file.
CompatV21.kt is our current baseline implementation (because it matches our minSdkVersion)
CompatV33.kt is our newest CompatV<nn> implementation

For this to work, Compat.kt must have the API as I described it.
CompatV21.kt must have the API as I described it (to override Compat.kt with a runtime implementation, unless Kotlin has the feature of letting you define a baseline implementation in an interface? I admit I have not worked with Kotlin much so I don't know)
CompatV33.kt must have the API as I described it, as an override of CompatV21 / implementation of Compat API

2022-10-02 21:17 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
> +        return bundle.getParcelable(name, clazz)
> Compat.kt is where all the APIs are defined for export. CompatHelper just resolves the current runtime to the correct CompatV.kt file. CompatV21.kt is our current baseline implementation (because it matches our minSdkVersion) CompatV33.kt is our newest CompatV implementation
> 
> For this to work, Compat.kt must have the API as I described it. CompatV21.kt must have the API as I described it (to override Compat.kt with a runtime implementation, unless Kotlin has the feature of letting you define a baseline implementation in an interface? I admit I have not worked with Kotlin much so I don't know) CompatV33.kt must have the API as I described it, as an override of CompatV21 / implementation of Compat API

compat.kt already have ` fun <T : Parcelable?> getParcelable(bundle: Bundle, name: String, clazz: Class<T>): T?`

2022-10-02 21:19 UTC, criticalAY commented
> Compat.kt is where all the APIs are defined for export. CompatHelper just resolves the current runtime to the correct CompatV.kt file. CompatV21.kt is our current baseline implementation (because it matches our minSdkVersion) CompatV33.kt is our newest CompatV implementation
> 
> For this to work, Compat.kt must have the API as I described it. CompatV21.kt must have the API as I described it (to override Compat.kt with a runtime implementation, unless Kotlin has the feature of letting you define a baseline implementation in an interface? I admit I have not worked with Kotlin much so I don't know) CompatV33.kt must have the API as I described it, as an override of CompatV21 / implementation of Compat API

compat.kt already have` fun <T : Parcelable?> getParcelable(bundle: Bundle, name: String, clazz: Class<T>): T?`
Which works according to the new API, I mean that's the new API call for version 33>=

2022-10-02 21:26 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
> +        mPreviousImageUri = savedInstanceState.getParcelableCompat("mPreviousImageUri")
Why does this not look like the new API with a class parameter?

2022-10-02 21:31 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
> +        mPreviousImageUri = savedInstanceState.getParcelableCompat("mPreviousImageUri")
```
 inline fun <reified T : Parcelable> Bundle.getParcelableCompat(name: String): T? {
            return compat.getParcelable(this, name, T::class.java)
        }
```
we are calling the code through this and this is defined in compat helper the only place where one parameter is passed otherwise whenever I have defined the code I have created two parameter fields i.e compat21,compat and compat33

2022-10-02 21:32 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
> +        mPreviousImageUri = savedInstanceState.getParcelableCompat("mPreviousImageUri")
Plus once we remove the suppress deprecation from the code we can directly access the new method as the SDK version is already updated.

2022-10-03 00:25 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
> +        mPreviousImageUri = savedInstanceState.getParcelableCompat("mPreviousImageUri")
> Plus once we remove the suppress deprecation from the code we can directly access the new method as the SDK version is already updated.

No, the API will not be available at runtime on devices that are < API33, and attempting to access it directly would cause a crash at runtime on those devices.

That's why we have a Compat subsystem. It allows for use of the new APIs easily on devices that support it, with fallbacks to reasonable use of old APIs, and allowing easy transformation in the future as we raise **minSdkVersion**. The process is 1) raise *compileSdkVersion*, add Compat stuff, then raise *minSdkVersion* some years later and you can finally go back to direct API usage.

> we are calling the code through this and this is defined in compat helper the only place where one parameter is passed

Okay.

I quote myself: "For this to work, Compat.kt must have the API as I described it."

So, why is Compat not defined with the two arguments? I have stated that as a design goal we want to allow for easy future transformation to direct API calls. I don't want to have to try to figure out some new arguments years from now when we transform back to direct API calls on the underlying object.

2022-10-03 03:08 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
> +        mPreviousImageUri = savedInstanceState.getParcelableCompat("mPreviousImageUri")
I would like to have some intervention @david-allison in here

2022-10-03 04:25 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
> +        mPreviousImageUri = savedInstanceState.getParcelableCompat("mPreviousImageUri")
I agree - this is quite possibly some Kotlin type system thing that I'm simply unaware of because I haven't set myself to learning the language well enough yet, and I'm bringing a Java mindset to it. If not David, someone with solid skills in Kotlin typing would be great to have take a look at it

2022-10-19 09:51 UTC, closed without merging