Changed cursor colour in light theme
ankidroid/Anki-Android pull request #12503
Opened 2022-09-24 18:45 UTC by pratyaksh1610

## Purpose / Description

Changed the cursor colour in light theme for visibility.

## Fixes
fixes #12337

Reference #12340
Got closed due to force push.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

## After the change

2022-09-24 18:46 UTC, pratyaksh1610 commented
@BrayanDSO PTAL.
Thanks.

2022-09-24 19:07 UTC, pratyaksh1610 commented
Why are these checks failing ?

2022-10-15 11:17 UTC, BrayanDSO requested changes

2022-10-15 11:17 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/theme_light.xml
> +        <item name="colorControlActivated">?attr/colorPrimaryDark</item>
This changes the color on other places than the cursor color

2022-12-21 12:45 UTC, closed without merging