Fixed the navigation of filtered deck options activity
ankidroid/Anki-Android pull request #12506
Opened 2022-09-25 21:18 UTC by pratyaksh1610

## Purpose / Description
Fixed the navigation of filtered deck options activity, after tapping it goes back to the deck picker.

## Fixes
Fixes #12480

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

https://user-images.githubusercontent.com/76740999/192166026-eb3eab92-1c05-4242-a2c7-b7dcbe81f604.mp4

2022-10-03 18:25 UTC, pratyaksh1610 commented
@BrayanDSO PTAL. Thanks.

2022-10-03 22:41 UTC, BrayanDSO commented
Here you are clearing all the opened activities and putting the deck picker behind the filtered deck options screen.

Ideally, the study options screen should not be shown at all, and that's it

2022-10-04 19:58 UTC, pratyaksh1610 commented
@BrayanDSO I have made the change. 
PTAL. Thanks.

2022-10-05 15:30 UTC, pratyaksh1610 commented
@BrayanDSO Why these checks are failing ?

2022-10-09 13:45 UTC, BrayanDSO requested changes

2022-10-09 13:45 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
> +        slide(this, ActivityTransitionAnimation.Direction.END)
Unnecessary change

2022-10-09 13:45 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            intent.setClass(this, FilteredDeckOptions::class.java)
This breaks other functionalities, as startActicityForResult below

2022-10-09 14:38 UTC, pratyaksh1610 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
> +        slide(this, ActivityTransitionAnimation.Direction.END)
@BrayanDSO I have made the change.

2022-10-09 14:38 UTC, pratyaksh1610 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            intent.setClass(this, FilteredDeckOptions::class.java)
Fixed the navigation

2022-10-09 14:39 UTC, pratyaksh1610 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            intent.setClass(this, FilteredDeckOptions::class.java)
Updated the recording in the PR comment.

2022-10-09 15:12 UTC, mikehardy commented
> [Merge branch 'ankidroid:main' into branch-12480](https://github.com/ankidroid/Anki-Android/pull/12506/commits/072b215d984255dd462cd1c89192580103c1bd3b)

Why the merge commit?  https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#git-workflow

2022-10-09 15:16 UTC, pratyaksh1610 commented
@mikehardy Did this so as to sync the branch

2022-10-09 15:20 UTC, mikehardy commented
Read the link I posted. Notice the word "rebase" in the flow...

2022-10-13 10:53 UTC, pratyaksh1610 commented
PTAL @BrayanDSO

2022-10-13 10:58 UTC, BrayanDSO requested changes

2022-10-13 10:58 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            } else {
Ideally, the method called `openStudyOptions` should only open the study options fragment, respecting the princple of the least surprise. 

So, the filtered deck options opening should be rerouted into another method (probably a new one)

2022-10-13 11:59 UTC, pratyaksh1610 commented
@BrayanDSO I have created a separate method. PTAL.

2022-10-13 12:02 UTC, pratyaksh1610 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            } else {
Done

2022-10-20 11:11 UTC, pratyaksh1610 commented
PTAL @BrayanDSO

2022-10-20 12:17 UTC, BrayanDSO commented
Hi. Sorry, but we are all volunteers here, and I'm quite busy at the moment. Repinging me won't help at all, so I'd like if you would be patient and just wait and some day this will get reviewed. Insisting on repinging would actually reduce any will of mine to review this.

2022-11-08 07:59 UTC, pratyaksh1610 commented
Okay, cool , no worries.

2022-12-07 17:29 UTC, pratyaksh1610 commented
I think it's been a long while now, would like to know the status of the PR if possible. Thanks !

2023-02-12 07:15 UTC, pratyaksh1610 commented
@BrayanDSO PTAL.

2023-02-23 03:56 UTC, david-allison approved these changes
Tested on tablet and mobile. Works.
Rebased on `main` and it didn't break lint, but we should be careful here.

@pratyaksh1610 If possible, could you `squash` this into 1 commit and `rebase` it onto `main` so we can run this against our current CI

2023-02-23 15:57 UTC, mikehardy approved these changes
OK

2023-02-23 15:57 UTC, merged