cleanup: inControlBlocked to property
ankidroid/Anki-Android pull request #12508
Opened 2022-09-26 18:08 UTC by RobozinhoD

## Pull Request template

## Purpose / Description
Part of Kotlin cleanup #10489

## Fixes
Part of Kotlin cleanup #10489

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-26 20:35 UTC, david-allison requested changes
Thanks for the contribution! 

You need to provide a custom getter on the property for this to be a full fix

2022-09-26 20:35 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/testutil/MockReviewerUi.kt
> +    override val isControlBlocked: Boolean = false
You want to use a property with a custom getter here. search the below for `get()` to see the syntax

https://kotlinlang.org/docs/properties.html

Unit tests are failing due to this

2022-09-26 21:46 UTC, BrayanDSO commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/testutil/MockReviewerUi.kt
> +    override val isControlBlocked: Boolean = false
Do I need to do it only on this class?

2022-09-26 21:48 UTC, BrayanDSO commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/testutil/MockReviewerUi.kt
> +    override val isControlBlocked: Boolean = false
Be free to ask anything if you have any questions.

2022-09-27 15:53 UTC, david-allison submitted a review, later dismissed

2022-09-27 15:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +    override val isControlBlocked: Boolean = controlBlocked !== ControlBlock.UNBLOCKED
this is incorrect still, as are the other usages.

2022-09-27 17:31 UTC, RobozinhoD commented
Checks pass now

2022-09-27 23:03 UTC, BrayanDSO approved these changes
LGTM. Thanks for the contribution

2022-09-28 17:03 UTC, merged