Coroutines migration mark note multi
ankidroid/Anki-Android pull request #12525
Opened 2022-09-28 18:28 UTC by divyansh-dxn

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-30 16:25 UTC, divyansh-dxn commented
Conflicts resolved

2022-09-30 17:48 UTC, lukstbit requested changes
Looks good with two minor issues

2022-09-30 19:57 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        if (result.map { card -> card.id }.contains(reviewerCardId)) {
Can you move this outside of the if statement? Will improve the readability.

2022-09-30 19:59 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            val hasUnmarked = !originalUnmarked.isEmpty()
isNotEmpty can be used. Either update in this PR or add a TODO.

2022-09-30 20:00 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                if (NoteService.isMarked(n)) originalMarked.add(n) else originalUnmarked.add(
Needs to be formatted properly.

2022-09-30 20:01 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            val originalMarked: MutableList<Note> = java.util.ArrayList()
Use `mutableListOf`.

2022-09-30 20:01 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            val originalUnmarked: MutableList<Note> = java.util.ArrayList()
Use `mutableListOf`.

2022-09-30 20:01 UTC, ShridharGoel requested changes
Would be good to improve the previous code while you are moving it.

2022-09-30 21:14 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            val notes = CardUtils.getNotes(Arrays.asList(*cards))
Can you please add a "TODO: get note directly without loading cards". We can create a db query that directly fetch the nids from the cards without loading all data from card table

2022-10-01 20:40 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            showProgressBar() // from MarkCardHandler.preExecute()
@divyansh-dxn Are you planning to update this?

2022-10-02 11:22 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            showProgressBar() // from MarkCardHandler.preExecute()
Yeah done. Actualluy with the privious implementation I was seeing a progress bar when toggling but when I used withProgress{} I wasn't seeing, at that moment I wasn't sure and left it for later. Actually withProgress{} starts progress dialog after 600ms so that was the reason And this is actually a good desision by dae, because I don't want to see flashes of progress dialog when my operation is less than about 600ms. Maybe worth documenting it, I should have to peek into code to know that.

2022-10-02 14:21 UTC, Arthur-Milchior approved these changes

2022-10-03 11:11 UTC, lukstbit approved these changes
LGTM.
I think all raised issues were addressed, unless @ShridharGoel  has anything to add.

2022-10-04 20:40 UTC, ShridharGoel approved these changes

2022-10-04 20:40 UTC, merged

2022-10-04 20:40 UTC, ShridharGoel commented
@divyansh-dxn Merged.