Export selected cards from Browser
ankidroid/Anki-Android pull request #12524
Opened 2022-09-28 17:02 UTC by viciousAegis

## Pull Request template

## Purpose / Description
Add functionality to be able to select cards/notes in the browser and export them from the browser themselves

## Fixes
Fixes #8045

## Approach
With the new backend (see https://github.com/ankidroid/Anki-Android/pull/8159#issuecomment-1186151840), exporting selected cards and notes is supported. This PR handles the UI of exporting selected cards, and adds this case to utilise the functionality being provided by collectionV16.

## How Has This Been Tested?
### Exporting

https://user-images.githubusercontent.com/86671025/192843998-dce39526-6bc3-4358-96cc-3a20f287e1f1.mp4
### Importing

https://user-images.githubusercontent.com/86671025/192843979-3e780d71-76fb-4ca7-9da9-6222aebde173.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-28 17:13 UTC, david-allison requested changes
As (quickly) discussed on Discord. The method parameters have low cohesion, and I'd like this to be fixed

2022-09-28 18:58 UTC, Arthur-Milchior reviewed
Thanks a lot. I've been wanting this feature for so long!
Quite a lot of change here, to keep codes s maintainable as possible please

2022-09-28 18:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/BundleUtils.kt
> +        } else bundle.getLongArray(key)
`getLongArray` already returns null if the key is not here. 
So `bundle?.getLongArray(key)` is exactly the same method, but simpler. I don't believe the method is actually useful here

2022-09-28 18:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt
> +fun CollectionV16.exportCardsAsAnkiPackage(
For the sake of the consistency, it would be nice to split `exportAnkiPackage` in two. Ones which deck a non-nullable `DeckId` and one that takes nothing.

2022-09-28 18:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +    override fun exportCardsAsApkg(path: String?, cardIds: List<CardId>, includeSched: Boolean, includeMedia: Boolean) {
There is a lot of code duplicated from `fun exportApkg` and with the method below. Do you think you'd have a way to refactor. Extract in `exportApkg` the part that is specific to deck in a separate methods, the part that is specific to whole collection in a separate method, and finally the part that is used everywhere in a last method.

2022-09-28 18:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.kt
>          fun exportApkg(path: String?, did: DeckId?, includeSched: Boolean, includeMedia: Boolean)
For the sake of the consistency, I believe it would be nicer to either:
* have two distinct functions for deck and whole collection or
* to have a single function that takes as argument an `anki.import_export.ExportLimit?`, since this is sufficient to determine what to export; and you can still use the data encoded in it even if you're not in the back-end

2022-09-28 18:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/BackendImporting.kt
> +suspend fun AnkiActivity.exportCardsAsApkg(
There is a lot of code duplicated from fun exportApkg and with the method below. Do you think you'd have a way to refactor. Extract in exportApkg the part that is specific to deck in a separate methods, the part that is specific to whole collection in a separate method, and finally the part that is used everywhere in a last method.

2022-09-28 18:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        return (getNotes(selectedCards).map { it.id }).toList()
`map` already returns a list, so `toList` seems useless here.

2022-09-28 18:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        selectedCardIds.forEach {
`forEach` followed by a `add` could be simply transformed into a `map(col::getCard)`

2022-09-28 18:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    fun getSelectedNoteIds(): List<NoteId> {
I'm sorry, but plenty of things in it are not correct.

2022-09-28 18:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Can you please add some javadoc. While the name seems clear, actually, there is one point that is not clear from the name itself: what occurs if card from the same notes are selected multiple times.
So either:
*  you should add the assumption that we have at most one card by note (this is the case with your code)
* you should note that there may be duplicate
* you should return a set instead of a list, ensuring unicity

2022-09-28 18:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        selectedCardIds.forEach {
AnkiDroid stores cards through CardCache. Which means that we probably already have the whole card object. This is especially possible because, if you manually selected the cards, then the cards had been loaded. (Admittedly, you may be able to do some "select all", so it may not be useful all of the time). So I'd appreciate if you could use `mCheckedCards` instead

2022-09-28 18:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    fun getSelectedNoteIds(): List<NoteId> {
For the sake of the consistency, I believe `selectedNoteIds` and `selectedCardIds` should either be both properties or both functions.
Since we already have a property, lets keep with property for both

2022-09-28 18:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +    fun showExportDialog(msg: String, ids: List<Long>, isCardList: Boolean) {
Could you please also add javadoc

2022-09-28 18:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.kt
> +     * @param ids A list of longs which specifies the card/note ids to be exported
The type already indicate it's a list of longs. Please only add in javadoc what can't be easily inferred from the type system. There should be no case where the developer can read the javadoc and not the type itself

2022-09-28 19:00 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.kt
> +        if (did != null || cardIds != null || noteIds != null) {
What does Anki do here? Could do with a `@NeedsTest`

2022-09-28 19:00 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        return (getNotes(selectedCards).map { it.id }).toList()
this should be reducable to a chain of `.map`

```
val selectedCards = selectedCardIds.map { col.getCard(it) }
```

2022-09-28 19:00 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            mExportingDelegate.showExportDialog(msg, selectedCardIds, true)
use a named arg instead of true/false

2022-09-28 19:00 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="confirm_apkg_export_selected_notes">Export %d selected note(s) as apkg file?</string>
Use `<plurals>`, not `card(s)`

2022-09-28 19:00 UTC, david-allison commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="card_browser_export_notes">Export notes</string>
Again, does this want to be a plural

2022-09-29 06:52 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt
> +fun CollectionV16.exportCardsAsAnkiPackage(
Okay, will do

2022-09-29 06:54 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
`getNotes()` returns a set, thus ensuring no duplicate notes exist. I will refactor this in the next commit and make it clearer

2022-09-29 10:14 UTC, viciousAegis commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="card_browser_export_notes">Export notes</string>
Making this plural will then require additional logic to change this title frequently every time we check multiple cards, or uncheck to just one card.
Other options like `Delete notes` and `suspend cards` don't use plurals either and I am not sure if the extra work is worth the change

2022-09-29 10:35 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        selectedCardIds.forEach {
the `getNotes()` function returns a set of Notes from a given collection of Cards, to use this function i used a list of Cards instead of `mCheckedCards`

2022-10-01 13:07 UTC, Arthur-Milchior commented
@viciousAegis the first commit was really hard to read, to understand all of what was going on. So I splited it in 6 commits. I'd really appreciate, even if we end squashing, if you could ensure to help the reviewers. Because, now, I believe most commits are really trivial to review as they don't change anything (expectedly), and we separate the commit that actually do something; which are themselves simple to review as they are similar to already existing code

2022-10-01 13:17 UTC, Arthur-Milchior reviewed
As noted above, it was hard to read. Given how much I worked on it, clearly, I'll want another approval.
It's fine-ish here, but still, lot of code repetition. Some part seems hard to avoid simply because we deal with two back-ends, but some clearly can. I'd prefer this to be solved before merging it.

2022-10-01 13:17 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +        exportPath = if (path != null) {
You could directly put the `val ` here. No need to declare the exportPath first, before defining it.

2022-10-01 13:17 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +        val limit = exportLimit { this.noteIds = this.noteIds.toBuilder().addAllNoteIds(noteIds).build() }
It seems this line is the only difference between card and note. So really, I'd appreciate if you could factorize it. I'm pretty sure this could take a limit as input already, and be used even for deck the day we are defaulting to the legacy schema. 
If we can't factor it already, we could at least extract the whole part that is computing the path in a separate method we reuse

2022-10-01 13:19 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="card_browser_export_notes">Export notes</string>
@viciousAegis there may be a compromise here.

It's important that we directly introduce plural in the string because otherwise we are going to mess with CrowdIn, and, more importantly, with translators work. So, I agree with David, we should use plural immediately.
We can choose not to use the plural right now if it's too hard. Just put a todo in the code, and always give 10 as an argument to force the use of plural until we are ready to change singular/plural

2022-10-02 13:56 UTC, Arthur-Milchior approved these changes
I'm fine-ish with this. Still way to get it simpler I believe, but don't want to be blocking on that

2022-10-02 13:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +        File(exportDir, "${collectionSupplier.get().decks.current().getString("name")}${getTimeStampSuffix()}.apkg")
Nope. You don't know if the deck you are exporting, `did`, is the current deck.

2022-10-02 13:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +
It feels like the three functions could be a single function, taking as argument "deckName", "cards", "notes", or even "All Decks" in the first example. 
This means that you can still use a single function such as `getExportFileName` that has no conditional and deals with all apkgs

2022-10-02 14:26 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        selectedCardIds.forEach {
I think the cards are accessible from the cache; so you can simply gets the cards from the cache if you need them.

2022-10-03 05:31 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +        File(exportDir, "${collectionSupplier.get().decks.current().getString("name")}${getTimeStampSuffix()}.apkg")
This is the original code that was already present, haven't changed it

2022-10-04 01:22 UTC, david-allison approved these changes
LGTM, one nitpick. Implementer's choice

2022-10-04 01:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            ).map { it.id }
This should be extracted to a function in a service, with a comment that we can do much better with performance here.

(I don't think this matters much, as it's an uncommon feature), this will also block the UI, and should have a TODO to fix this

2022-10-04 13:03 UTC, viciousAegis commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            ).map { it.id }
done 👍

2022-10-04 22:20 UTC, Arthur-Milchior approved these changes
I approve the last commit too

2022-10-07 08:02 UTC, viciousAegis commented
removed merge conflict

2022-10-13 14:36 UTC, mikehardy commented
> Task :AnkiDroid:ktlintMainSourceSetCheck FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:161:1 Needless blank line(s)

I ran `./gradlew ktlintFormat` and pushed the resulting commit

2022-10-13 17:34 UTC, mikehardy approved these changes
I did not like the merge commit in here after so many other commits were cleanly split, I backed the merge commit out, fixed the small merge conflict on commit 8, fixed the ktlint (again) and squashed that into commit 8 also, and re-pushed.
Should be good to go with a rebase-merge now, I'm running it through ./tools/test-commits right now to make sure each commit still works

2022-10-13 17:53 UTC, david-allison approved these changes

2022-10-13 19:59 UTC, merged