Implement new backend for notetypes fields
ankidroid/Anki-Android pull request #12529
Opened 2022-09-29 07:55 UTC by lukstbit

## Purpose / Description

Built on top of #12486 to use the helper function from there and to connect the two related classes(the last commit is the new one).

This PR enables the new backend for viewing and changing the fields of notetypes. With the new implementation:

- new activity for new backend implementation, ManageNotetypeFields(the old activity ModelFieldEditor should be deleted)
- full support for coroutines(and with progress) with all backend calls
- improve UI for the fields list by using CardView(ideally we would use the material cards but we don't currently
inherit from the material themes)
- fix some of the UX reported issues, like providing a uniform add action(by using the platform FloatingActionButton)
  and stop using the hard to discover context menu in favor of in layout actions for each item(with a side menu as we
  have too many options to display all inline)
- enable some checks for the field names when renaming or adding new entries to avoid duplicates
- use some of the translated strings from anki desktop

What doesn't work:
- ~~no tests for now~~(will be done in a new PR after enabling testing the new backend)
- setting a language hint for a field. The previous implementation simply added a property in the json Model, not sure how to approach this with the fields coming from the backend

Some images with the new implementation:
<img src="https://user-images.githubusercontent.com/52494258/192972734-1b67262c-b7cb-40ee-b5ab-52837bdd9455.png" width="300px" height="680px"/><img src="https://user-images.githubusercontent.com/52494258/192972723-2ddb84ba-b5d8-4ba5-9eb5-937d2bd5e595.png" width="300px" height="680px"/>
<img src="https://user-images.githubusercontent.com/52494258/192972745-b83636ab-1edb-4ca2-8761-6550a7696c45.png" width="300px" height="680px"/><img src="https://user-images.githubusercontent.com/52494258/192972740-2977b708-ba88-4457-bced-6a1e3e806d93.png" width="300px" height="680px"/>

## How Has This Been Tested?

Ran checks, manually verified the features.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-09-30 05:55 UTC, dae commented
> setting a language hint for a field

Fields have an 'other' property that stores encoded JSON, so you can decode it / modify it / re-encode it to store custom properties that are not in the protobuf.

2022-09-30 06:28 UTC, dae reviewed
My review is limited to the backend/coroutine sections, but no obvious issues jumped out at me, and again the code is nice and neat. Curiosity makes me wonder whether some of the newBuilder() calls could be done with the Kotlin DSL, but if the current code works I wouldn't bother to rewrite it, as the gains would be minor if at all.

2022-11-01 16:41 UTC, oakkitten requested changes
Haven't yet had the chance to run the code but it is pretty decent. Would love the cards to show more info and be repositionable via drag and drop.

2022-11-01 16:41 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeFieldsAdapter.kt
> +) : RecyclerView.ViewHolder(rowView) {
Make `NotetypeFieldViewHolder` inner class of `NotetypeFieldsAdapter` and you won't need to pass listeners here

2022-11-01 16:41 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeFieldsAdapter.kt
> +    private var name: String? = null
View holders have access to adapter position, it's more common to get the item through that instead of directly. I think having `name` is dangerous here, IIRC it might be possible to trigger a button click on a holder while it is animating or something. It's best to go the standard route I think.

2022-11-01 16:41 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeFieldsAdapter.kt
> +    }
I would like the cards to show more data, such as sticky, sort by status, language hint, description, etc.

2022-11-01 16:41 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeFieldsAdapter.kt
> +                )
Refactor into two statements

2022-11-01 16:41 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeFieldsAdapter.kt
> +            with(TR) {
Oh god. I see the point, but it really should be `getTranslatons()` or something. I'd add a TODO in `TR` saying it should be renamed.

2022-11-01 16:41 UTC, oakkitten commented on AnkiDroid/src/main/res/layout/activity_note_types_fields.xml
> +            android:paddingBottom="104dp"
I'd add a comment explaining the padding

2022-11-01 16:41 UTC, oakkitten commented on AnkiDroid/src/main/res/layout/item_note_type_field.xml
> +    <LinearLayout
Can't we flatten the layout by putting everything inside `ConstraintLayout`?

2022-11-01 16:41 UTC, oakkitten commented on AnkiDroid/src/main/res/layout/item_note_type_field.xml
> +            tools:text="Basic (and reversed card)"
Will user ever see this text?

2022-11-01 16:41 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
>  suspend fun AnkiActivity.userAcceptsSchemaChange(): Boolean {
Why not `suspendCancellableCoroutine`?

2022-11-01 16:41 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> + */
* Not sure if `routine` is an acceptable contraction of `coroutine`
* Coroutines don't “return” in the same sense as methods. Just say `` the method returns `true` ``
* This doesn't form a good sentence and I'm not sure if this is helpfu;, maybe delete?
  > The version of [userAcceptsSchemaChange] which uses the Collection internally without the need to pass it in.

2022-11-01 16:41 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
>  suspend fun AnkiActivity.userAcceptsSchemaChange(): Boolean {
Also, perhaps remove the method that takes `col`? It's barely used

2022-11-03 16:13 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt
>  class LocaleSelectionDialog : AnalyticsDialogFragment() {
That class should be refactored but this is out of the scope of this PR.

2022-11-03 16:18 UTC, lukstbit commented on AnkiDroid/src/main/res/layout/item_note_type_field.xml
> +            tools:text="Basic (and reversed card)"
No, `tools:attribute` is to set attributes for the IDE's layout design panel.

2022-11-03 16:25 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypeFields.kt
> +    @SuppressLint("CheckResult")
None, some leftover.

2022-11-03 16:35 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypeFields.kt
> +    private val fieldsAdapter: NotetypeFieldsAdapter by lazy {
Leftover, I initially wanted to create the adapter when the data was first fetched in onCreate.

2022-11-03 16:46 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypeFields.kt
> +    private val fieldsAdapter: NotetypeFieldsAdapter by lazy {
Crash as I'm accessing the Context in the adapter.

2022-11-03 16:56 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt
>      }
> I would not keep fun onSelectedLocale(selectedLocale: Locale). Make the old class take the two-argument method, and just ignore one of the parameters

I liked this.

> Also, I'd change the interface to the following. “On (selected locale)” is not a very good grammar

Out of scope, I would also point that the _onSomething_ pattern is used in the Android SK  with callbacks.

2022-11-03 17:03 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypeFields.kt
> +    private fun repositionField(name: String) {
I'm going to keep `repositionField` as I see the dialog as part of the actual repositioning process. 

> I suggest investigating how easy it would be to implement repositioning by dragging and dropping

Should be pretty easy using ItemTouchHelper but I don't have time to extensively test it. I'll add a TODO.

2022-11-03 17:27 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypeFields.kt
> +            if (allFieldsNames.size <= 1) {
Nope, the idea was that if we have 1 field(we can't really have 0 fields) we alert the user that he can't proceed with the deletion and leave the note without any fields.

2022-11-03 17:29 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypeFields.kt
> +                return@launchCatchingTask
Nope, adds an extra indentation just to have:

```
else {
    if (userAcceptsSchemaChange()) {
```

2022-11-03 17:34 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypeFields.kt
> +        action: Collection.(Notetype) -> Notetype? = { null }
It's used in onCreate. I admit that's not ideal but I'm ok with using it like this.

2022-11-03 17:37 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeFieldsAdapter.kt
> +            with(TR) {
Out of scope.

2022-11-03 17:43 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeFieldsAdapter.kt
> +    }
Could be discussed at a later point, my goal was to just enable the backend for this part of the application.
Also, the desktop version only shows the sort status, if I'm not mistaken.

2022-11-03 17:50 UTC, lukstbit commented on AnkiDroid/src/main/res/layout/item_note_type_field.xml
> +    <LinearLayout
Yes, it would be more efficient.

2022-11-03 18:24 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
>  suspend fun AnkiActivity.userAcceptsSchemaChange(): Boolean {
> Why not suspendCancellableCoroutine?

Copied the method above(in CoroutineHelpers) which is also not cancellable. 
But it should definitely be cancellable, will do this in another PR.

2022-11-03 18:28 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> + */
The documentation was copied from the method above, the last line was added by me but it's not needed. I'll change the method's javadoc to:

_If a full sync is not already required, confirm the user wishes to proceed. If the user agrees, 
the schema is bumped and the method will return true. On false, calling coroutine should abort._

2022-11-03 18:31 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypeFields.kt
> +                    updateLanguageHint(selectedLocale, field.config.other.toStringUtf8())
Your code would not compile. I can inline `updateLanguageHint(selectedLocale, field.config.other.toStringUtf8())` but I don't think it would be an improvement.

2022-11-03 20:46 UTC, oakkitten commented on AnkiDroid/src/main/res/layout/item_note_type_field.xml
> +            tools:text="Basic (and reversed card)"
Ahh, didn't know that, never use that thing. Thanks!

2022-11-03 20:49 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypeFields.kt
> +                return@launchCatchingTask
You can combine `else` and `if` to have
    
    } else if (userAcceptsSchemaChange()) {

2022-11-03 20:50 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypeFields.kt
> +            if (allFieldsNames.size <= 1) {
O sorry I thought I saw `size < 1`! Should have realized that would give the warning.

2022-11-03 21:11 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypeFields.kt
> +                    updateLanguageHint(selectedLocale, field.config.other.toStringUtf8())
I was thinking about my suggestion +

```kt
fun NotetypeKt.FieldKt.ConfigKt.Dsl.setLanguageHint(locale: Locale) {
    val otherJsonObject = if (other.isEmpty) JSONObject() else JSONObject(other.toStringUtf8())
    otherJsonObject.put(ManageNotetypeFields.LANGUAGE_HINT_PROP, locale.toLanguageTag())
    other = ByteString.copyFromUtf8(otherJsonObject.toString())
}
```

Or even

```kt
field.copy {
    setLanguageHint(selectedLocale)
}
```

plus

```kt
fun NotetypeKt.FieldKt.Dsl.setLanguageHint(locale: Locale) {
    config = config.copy {
        val otherJsonObject = if (other.isEmpty) JSONObject() else JSONObject(other.toStringUtf8())
        otherJsonObject.put(ManageNotetypeFields.LANGUAGE_HINT_PROP, locale.toLanguageTag())
        other = ByteString.copyFromUtf8(otherJsonObject.toString())
    }
}
```

The big idea is to hide all the ugly Json juggling from dsl

2022-11-03 21:20 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypeFields.kt
> +    private fun repositionField(name: String) {
I **_strongly_** believe the method with a name `repositionField` should be unconditionally repositioning a field. Having function names that exactly reflect what they do immensely improves readability. Sometimes it is not possible, or hard to achieve, but in this case there is some reasonable precise phrasing.

2022-11-03 21:26 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypeFields.kt
> +    private val fieldsAdapter: NotetypeFieldsAdapter by lazy {
Ah, I see. This is commonly done via `lateinit var` but this works as well

2022-11-03 21:34 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt
>      }
I think in `onSomething` `Something` should be an action, like `Click` in `onClick`, something you can perform. Or a past tense verb, as in `onClicked`. If you follow this “rule” you get `onLocaleSelected` and `onLocaleSelection` but the latter is just weird. `Selected locale` on the other hand is like currently selected locale... When selected locale happens... You can't “perform” a selected locale... Well, at least that's how I read it, this is not very important

2022-11-03 21:39 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypeFields.kt
> +        action: Collection.(Notetype) -> Notetype? = { null }
If you change the signature to `action: (Collection.(Notetype) -> Notetype)? = null` you can also call it without arguments. Just have to explicitly handle the case when the action is `null`, and explicit is good I think

2023-10-23 07:17 UTC, lukstbit commented
Already implemented so I'm closing this for now, I'm planning to create a better UI for manage notetypes/notetypes fields.

2023-10-23 07:17 UTC, closed without merging