Fixed getPackageInfo deprecation.
ankidroid/Anki-Android pull request #12548
Opened 2022-10-01 17:44 UTC by n1snt

## Purpose / Description
_Describe the problem or feature and motivation_

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-10-02 03:16 UTC, david-allison requested changes

2022-10-02 03:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.kt
> +                val pInfo = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
ditto of my other review, this needs to be in `compat`

2022-10-02 14:27 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.kt
> +                val pInfo = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
Thanks, will move this to `compat` once I get home.

2022-10-09 06:51 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.kt
> +                val pInfo = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
Implemented it using Compat can you please have a look at it?

2022-10-24 10:01 UTC, n1snt commented
@david-allison made the requested changes.

2022-10-25 10:09 UTC, david-allison requested changes
Much better! Some code style improvements/docs remaining

2022-10-25 10:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
> +        }
The point of these functions is that they're extensions. This should likely be an extension on `Context`

2022-10-25 10:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
> +    fun getPackageInfoCompat(context: Context, packageName: String, flags: Int): PackageInfo
Should this be `@PackageInfoFlagsBits flags`

2022-10-25 10:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
> +    @Throws(NameNotFoundException::class)
```suggestion
    /**
     * Retrieve overall information about an application package that is
     * installed on the system.
     * 
     * @see PackageManager.getPackageInfo
     */
    @Throws(NameNotFoundException::class)
```

2022-10-25 10:16 UTC, david-allison requested changes
This doesn't seem to be all of the usages: 

![Screenshot 2022-10-25 at 11 15 47](https://user-images.githubusercontent.com/62114487/197747633-9b2269b1-4f69-4b9d-9830-bd6c42805bc2.png)

2022-11-05 02:28 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
> +    @Throws(NameNotFoundException::class)
Done.

2022-11-05 02:28 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
> +        }
Done.

2022-11-05 02:29 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
> +    fun getPackageInfoCompat(context: Context, packageName: String, flags: Int): PackageInfo
Should I change 
`@Throws(NameNotFoundException::class)`
with 
`@PackageInfoFlagsBits flags`? 🫤

2022-11-05 02:50 UTC, n1snt commented
@david-allison can you please have a look at the changes I made?
There is one usage left in isSystemApp in AdaptationUtil & I'm not sure how to use compact there as it's accessing getPackageInfo from the PackageManager which is passed to it as an argument.

2023-01-04 18:41 UTC, n1snt commented
Hey @david-allison can I please get a review on this one?

2023-02-16 10:42 UTC, closed without merging