Coroutines migration check card selection
ankidroid/Anki-Android pull request #12556
Opened 2022-10-02 18:09 UTC by divyansh-dxn

## Fixes
Fixes a part of #7108

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-10-02 18:57 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
>      return Pair(hasUnsuspended, hasUnmarked)
Want more attention on this one, took me a while to understand. Pardon me if I got something wrong (will be really simplified if I got it right)

2022-10-02 19:18 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
>      return Pair(hasUnsuspended, hasUnmarked)
Till the last commit, everything is fine by me. If this one also is okay, i'll be probably move where it was called (makes less sense to have a function for just two lines)

2022-10-03 11:39 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
>      return Pair(hasUnsuspended, hasUnmarked)
The changes are ok.

2022-10-04 16:44 UTC, lukstbit requested changes
Got to the third commit and left some comments which would invalidate the changes in the last 3 commits.

2022-10-04 16:44 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -        TaskManager.cancelAllTasks(CheckCardSelection::class.java)
This deleted line doesn't have a corresponding `checkSelectedCardsJob?.cancel` call.

2022-10-04 16:44 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
> -                if (collectionTask.isCancelled()) {
Arthur's comment on Discord about not handling coroutine cancellation is correct. 

We can handle this by:
- removing the `withCol {}` from the `launchCatchingTask`(no need to access the collection) and replace it with a `withContext{}` call
- moving the code from `CheckCardSelection.task()` inside the `withContext` call above(while keeping the for loop)
- call `ensureActive()` at the beginning of the for loop to make sure the coroutine was not cancelled

2022-10-06 04:54 UTC, lukstbit approved these changes
LGTM, with the observation below.

2022-10-06 04:54 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    private fun onSelectedCardsChecked(result: Pair<Boolean, Boolean>?) {
We could make `result` as not null because `checkCardSelection` always returns a `Pair`. This will allow us to remove the `result != null` check below.

2022-10-06 07:45 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    private fun onSelectedCardsChecked(result: Pair<Boolean, Boolean>?) {
done!

2022-10-06 08:51 UTC, merged