Fixed PackageManager.resolveActivity deprecation.
ankidroid/Anki-Android pull request #12550
Opened 2022-10-01 18:34 UTC by n1snt

## Purpose / Description
Fixes `resolveActivity` depreciation issue in https://github.com/ankidroid/Anki-Android/issues/12364#issuecomment-1264426702
I'm still a bit unsure about the fix I implemented in `AdaptionUtil`, it does not seem clean enough. I would love to hear if there is any better way to implement it.

## How Has This Been Tested?

- Tests
- Physical device
- API 33 Emulator

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-10-01 23:35 UTC, david-allison requested changes
Please look into the `compat` package for how we handle deprecation.

You can see how this works: https://github.com/ankidroid/Anki-Android/pull/12422

2022-11-13 20:33 UTC, n1snt commented
Hey, @david-allison can I please get a review on this?

2022-11-27 13:36 UTC, lukstbit requested changes
I've looked at the code and I'm not sure this is how we should move forward. The code changes the call site and would require additional changes when we would get to 33 being the minimum API level.
I would recommend instead:

1. Create an extension method in CompatHelper which fully replicates the newer non deprecated version of the method. This would be:

   `fun PackageManager.resolveActivity(intent: Intent, flags: ResolveInfoFlags): ResolveInfo?`

    which will simply delegate to `compat`

2. Create the new  method in `Compat`, also we can't use the newer class ResolveInfoFlags so we need to create our own implementation. This would be something like this:

    ```
    fun resolveActivity(packageManager: PackageManager, intent: Intent, flags: ResolveInfoFlags): ResolveInfo?

    data class ResolveInfoFlags(val value: Long) {
        companion object {
            fun of(value: Long) = ResolveInfoFlags(value = value)
        }
    }
    ```
    In `Compatv21` the implementation would call the resolveActivity version which receives an int from our custom ResolveInfoFlags:

   `packageManager.resolveActivity(intent, flags.value.toInt())`

    In `CompatV33` the newer method will be used:

    `packageManager.resolveActivity(intent, ResolveInfoFlags.of(flags.value))`

3. Use the previously declared method in CompatHelper instead of the deprecated ones. Make sure to make the imports look like the platform one. So we should have:
    
     `packageManager.resolveActivity(intent, ResolveInflFlags.of(0))`

      and not:

      ` packageManager.resolveActivity(intent, Compat.ResolveInfoFlags.of(0))`

      Note that there's one more usage in CustomTabsHelper that you hadn't addressed. You can check usages by using the `Find in files` view with `CTRL+SHIFT+F`(Linux) and searching for `.resolveActivity(` on a PackageManager instance.

With the changes above, when 33 will be the minimum API level we can simply delete the code above and only change some imports to use the newer version(of course assuming the we don't get other deprecations).

@david-allison @mikehardy Any opinions on what I said above?

2022-12-28 10:59 UTC, n1snt commented
Hey, @lukstbit thanks a lot for this write-up. 👍
It made me understand how compact is implemented here.
I have reimplemented the resolveActivity compact stuff, please check if everything is correct.

2022-12-29 17:21 UTC, lukstbit requested changes
Thanks for taking time to work on this. I've left some notes on minor issues, plus I'm mentioning another usage of resolveActivity that wasn't handled:

https://github.com/ankidroid/Anki-Android/blob/2eeed6570ec37f89405d5e68ccef39d3bd49fccf/AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabsHelper.kt#L60

2022-12-29 17:21 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
> +     * @param context
As the _@ params_ are empty they should be deleted.

2022-12-29 17:21 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
> +    data class ResolveInfoFlags(val value: Long) {
This class should also have documentation to explain it's role:

```
/**
 * Placeholder class(replicating the API 33 ResolveInfoFlags class) which is used to
 * provide a consistent API on all supported Android versions.
 */
```

2022-12-29 17:21 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
> +        return ctx.packageManager.resolveActivity(intent, Compat.ResolveInfoFlags.of(0)) != null
The ResolveInfoFlags class should be used without the Compat prefix. Then, when the minimum API level will be 33,  we could simply change the imports:

```
    private fun isIntentResolved(ctx: Context, intent: Intent): Boolean {
        return ctx.packageManager.resolveActivity(intent, ResolveInfoFlags.of(PackageManager.MATCH_DEFAULT_ONLY.toLong())) != null
    }
```
I think these are the imports needed:

```
import com.ichi2.compat.Compat.ResolveInfoFlags
import com.ichi2.compat.CompatHelper.Companion.resolveActivity
```

2022-12-29 17:21 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +                    if (packageManager.resolveActivity(intent, Compat.ResolveInfoFlags(0)) == null) {
The same issue like I mentioned below that our `ResolveInfoFlags` should be used without the Compat identifier. Make sure you are using the resolveActivity method from CompatHelper(it should be in italic as it's an extension method).

2023-01-04 09:33 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
> +    data class ResolveInfoFlags(val value: Long) {
Done

2023-01-04 09:33 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
> +     * @param context
Can you please check if this is fixed in the latest commits?

2023-01-04 09:33 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
> +        return ctx.packageManager.resolveActivity(intent, Compat.ResolveInfoFlags.of(0)) != null
Done

2023-01-04 09:33 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +                    if (packageManager.resolveActivity(intent, Compat.ResolveInfoFlags(0)) == null) {
Done

2023-01-04 09:35 UTC, n1snt commented
@lukstbit I have also replaced the usage of resolveActivity in CustomTabsHelper which you mentioned in your comment above. ✅

2023-01-06 14:06 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
> +     * @param context
It isn't fixed.

2023-01-06 14:13 UTC, lukstbit requested changes
One more issue below to fix and we are all set.

2023-01-06 14:13 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
> -        return ctx.packageManager.resolveActivity(intent, PackageManager.MATCH_DEFAULT_ONLY) != null
This isn't correct as `PackageManager.MATCH_DEFAULT_ONLY` doesn't have a value of 0. So it should be `ResolveInfoFlags.of(PackageManager.MATCH_DEFAULT_ONLY.toLong())`.

2023-01-13 08:44 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
> -        return ctx.packageManager.resolveActivity(intent, PackageManager.MATCH_DEFAULT_ONLY) != null
Made this change 👍

2023-01-13 15:39 UTC, david-allison requested changes
This looks good.

change requested:
I'd like documentation on what `ResolveInfoFlags(0)` means, and see if we can add this as a method on the data class to reduce confusion

One optional nitpick

2023-01-13 15:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
> +            fun of(value: Long) = ResolveInfoFlags(value = value)
This is only used once - the constructor is used the other two times.

2023-01-13 17:10 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
> +            fun of(value: Long) = ResolveInfoFlags(value = value)
This is more than  a nitpick, it's a valid observation and one that I missed when I reviewed. The platform `ResolveInfoFlags` class doesn't have a public constructor and only uses the `.of(value)` method to be intialized.

@n1snt Usages of the constructor(like `ResolveInfoFlags(0)`) should be replaced with `ResolveInfoFlags.of(0)` to replicate the platform class.

2023-01-14 21:17 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
> +            fun of(value: Long) = ResolveInfoFlags(value = value)
I'd remove this class (isn't useful at all, only the app heavier and slower to compile) and make the method take a Long flag argument restricted to the [same flags of ResolveInfoFlags with a @LongDef](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/content/pm/PackageManager.java;l=753-773;drc=bbed027319b21ad822443aea9d29433d14f28003)

2023-01-31 16:31 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
> +            fun of(value: Long) = ResolveInfoFlags(value = value)
@BrayanDSO Let's be honest, the class is not going to affect the build time at all. My reasoning was to do as much work as possible now so we can migrate to the platform version later, if we keep the flags version then I don't see the point of fixing these deprecations now, we are doing work now and will be doing work later, double the work no real benefit.

I would say that the issue with these api level 33 deprecations should be closed:

- we are doing work now for a very far future when API 33 will be the minimum. We, all the people in this thread,  almost 100% will not be there when it happens(the app might not even exist by then).
- there's a chance that switching to the new backend will eliminate the code containing them.
- these deprecations are not breaking, just makes the methods more type safe/ kotlin friendly
- it clutters the Compat  related classes which should be kept for real deprecations(like a complete difference between old/new way of doing something(not just one extra class parameter))

What do you think?

2023-01-31 21:39 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
> +            fun of(value: Long) = ResolveInfoFlags(value = value)
> Let's be honest, the class is not going to affect the build time at all.

It shouldn't be relevant right now. But things like this pile up with time and then it becomes relevant.

> we are doing work now for a very far future when API 33 will be the minimum. We, all the people in this thread, almost 100% will not be there when it happens(the app might not even exist by then).

100% agreed with your points, especially this one. And I'm always in favor of doing less and avoiding doing temporary job.

I think that we could add an annotation for "accepted deprecations" that would do the same function of the supress annotation, but only to a curated list of methods, so it's easier to find what should be fixed and what shouldn't

2023-02-01 22:52 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
> +            fun of(value: Long) = ResolveInfoFlags(value = value)
Replaced with `ResolveInfoFlags.of(0)` ✅

2023-02-15 22:34 UTC, david-allison approved these changes

2023-02-15 22:34 UTC, david-allison commented
Pending conflict resolution

2023-03-10 18:55 UTC, n1snt commented
@david-allison Fixed merge conflict.

2023-03-11 05:49 UTC, lukstbit requested changes
Thanks for still working in this.
It would be better if you would rebase this PR on top of the latest changes so it's easier to review.

2023-03-11 05:49 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +                    if (packageManager.resolveActivity(intent, ResolveInfoFlags.of(0)) == null) {
In #13110 we introduced a class `ResolveInfoFlagsCompat` which better models the new API method parameter. That's the one that should be used.

2023-03-11 05:49 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
> + *  this program.  If not, see <http://www.gnu.org/licenses/>.want to keep this issue as an 'easy first step' to onboard users, or to be handled on a case-by-case basis when it causes issues with PRs
Extra comment?!?!

2023-03-11 05:49 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
> +    fun canUseContextMenu(): Boolean {
I'm not sure what's up with this piece of code?

2023-04-01 07:36 UTC, closed without merging