Migrated EmptyCram to Coroutines
ankidroid/Anki-Android pull request #12551
Opened 2022-10-01 18:38 UTC by divyansh-dxn

Both implementations run the task within withProgress and run post-operation tasks from their respective handlers from previous implementations.

## Fixes
Fixes a part of #7108

## How Has This Been Tested?
Unit tests and pixel 4a API 30 Emulator

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-10-02 11:52 UTC, divyansh-dxn commented
Think it would be an over-do for this one to break. Fairely simple, just need to peek into the handler code to check with previous and new impls. Since same handlers are used elsewhere as well, so haven't deleted yet, but will be deleted in subsequent PRs.

2022-10-02 14:50 UTC, Arthur-Milchior approved these changes

2022-10-03 04:54 UTC, lukstbit requested changes

2022-10-03 04:54 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    updateValuesFromDeck(col, true)
We are inside the `withCol` block but we still use the outside `col` reference. Instead:
```
sched.emptyDyn(decks.selected())
updateValuesFromDeck(this, true)
```
The same issue for the other class, StudyOptionsFragment.

2022-10-03 07:07 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    updateValuesFromDeck(col, true)
Actually, it is the col from `this` instance inside withCol{} so okay. But nice to clean it up. 

com.ichi2.libanki.Collection
```kotlin
    /**
     * Allows a collection to be used as a CollectionGetter
     * @return Itself.
     */
    override val col: Collection
        get() = this
```

2022-10-03 07:11 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    updateValuesFromDeck(col, true)
Done

2022-10-03 09:42 UTC, lukstbit approved these changes
Ok, will merge once the change requested below is done.

2022-10-03 09:44 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    updateValuesFromDeck(col, true)
I think that indirection should be removed and it will be helpful to remove usages whenever possible.

2022-10-03 09:47 UTC, divyansh-dxn commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +                col.sched.emptyDyn(decks.selected())
done

2022-10-03 10:25 UTC, merged