[KotlinCleanup] - turn set/hasTemporaryMedia into a property
ankidroid/Anki-Android pull request #12563
Opened 2022-10-03 03:35 UTC by Kenny50

## Pull Request template

## Purpose / Description
demand -
  1. replace setHasTemporaryMedia(), hasTemporaryMedia() to property

modify -
  1. replace with `var hasTemporaryMedia:Boolean` in IField.kt, and the following class relay on this property

## Fixes
1. A small step towards getting #10489 out of the way
2. Limit the mutability of `currentHasTemporaryMedia` in `AudioField`, exposing multiple mutable point might cause unexpected result.

## Approach
Refactored the code to be more Kotlin-y.

## How Has This Been Tested?
Since changing interface affects on its children classes, I simply choose
`./gradlew jacocoTestReport`
to check all the tests works fine.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-10-04 09:34 UTC, BrayanDSO approved these changes
For the PR scope, LGTM. Thanks

2022-10-04 09:34 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt
> +    private var currentHasTemporaryMedia = false
Can you add a cleanup to use `hasTemporaryMedia` directly instead of this intermidiate variable?

2022-10-05 06:34 UTC, Kenny50 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt
> +    private var currentHasTemporaryMedia = false
Should I cleanup code directly, or add `@KotlinCleanup` instead?

2022-10-05 08:43 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt
> +    private var currentHasTemporaryMedia = false
I prefer cleaning it directly. If you don't want to do it on this PR, you can add a `@KotlinCleanup` instead

2022-10-06 08:17 UTC, Kenny50 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt
> +    override var hasTemporaryMedia: Boolean = false
Done, `hasTemporaryMedia` was mentioned with `name` in the `KotlinCleanup` here, I fix it together with previous cleanup task

2022-10-13 14:42 UTC, mikehardy commented
It appears android tests were not run locally during the development of the change, they fail compile:

```

> Task :AnkiDroid:compilePlayDebugAndroidTestKotlin FAILED
e: /Users/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt: (186, 22): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public operator fun MatchGroupCollection.get(name: String): MatchGroup? defined in kotlin.text
e: /Users/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt: (186, 25): No get method providing array access
e: /Users/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt: (190, 18): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public operator fun MatchGroupCollection.get(name: String): MatchGroup? defined in kotlin.text
e: /Users/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt: (190, 21): No get method providing array access

```

2022-10-13 14:43 UTC, mikehardy requested changes
seems fine as a change - thank you! - but the androidTest compile errors are real

locally start an android emulator and run `./gradlew jacocoTestReport` to run local unit tests and android tests (which implicitly checks compile of both)

2022-10-18 04:50 UTC, Kenny50 commented
@mikehardy 
Thank you for your time, I did check the local test, all test seems passed, then I checked the commit I redefine as the base, which is [6d9e8c7](https://github.com/ankidroid/Anki-Android/commit/6d9e8c72909cb34228eb02327f09cb49c74afef3), found the same issue, so I update the base to latest commit, now it looks fine

2022-10-31 16:42 UTC, lukstbit approved these changes
Thank you for the contribution!

2022-10-31 17:00 UTC, merged