[KotlinCleanup] FieldEditText
ankidroid/Anki-Android pull request #12568
Opened 2022-10-03 19:15 UTC by n1snt

## How Has This Been Tested?
- Tested on a physical device

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-10-04 09:26 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> +                return onImagePaste(getImageUri(clipboard)!!)
Can you guarantee that `getImageUri` will always return non-null?

2022-11-27 08:20 UTC, lukstbit requested changes

2022-11-27 08:20 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> +    protected fun onImagePaste(imageUri: Uri): Boolean {
The kotlin annotation was removed recently because the uri could be null following the platform declared nullability. So if you could revert the changes related to this method I could merge the other change.

2022-11-27 08:20 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> +        return sp.getBoolean("disableExtendedTextUi", false)
We could further improve this by inlining the method call:

`return AnkiDroidApp.getSharedPrefs(this.context).getBoolean....`

2022-12-28 06:36 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> +    protected fun onImagePaste(imageUri: Uri): Boolean {
Reverted this change. 👍

2022-12-28 06:51 UTC, n1snt commented
Fixed the merge conflict & made the requested changes ✅

2022-12-28 06:51 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> +        return sp.getBoolean("disableExtendedTextUi", false)
Done ✅

2022-12-28 16:16 UTC, lukstbit approved these changes
Great!

2022-12-28 16:18 UTC, merged