CardBrowser cleanup
ankidroid/Anki-Android pull request #12587
Opened 2022-10-06 07:01 UTC by SySagar

## Purpose / Description
Follow up to issue #10489 . Requires Kotlin clean up

## Fixes
Made clean up in CardBrowser.kt class.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2022-10-06 07:16 UTC, oyeraghib commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    lateinit var cardsListView: ListView
As it is mentioned the cleanup, maybe you should try initializing `cardsListView` and `mSearchView` inside the `onCreate()` method as it will make sure that the the variables are successfully initialized before the screen is visible.

2022-10-06 08:03 UTC, SySagar commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            mSaveSearchItem?.isVisible = false // the searchview's query always starts empty.
Fine. Will do.

2022-10-07 17:59 UTC, Arthur-Milchior commented
@SySagar you should look at test result. When everything is red usually it's a real issue

2022-10-10 16:10 UTC, criticalAY commented
> @SySagar you should look at test result. When everything is red usually it's a real issue

he touched the gradle file for no reason I think that wasn't needed in here?

2022-10-10 16:32 UTC, SySagar commented
@criticalAY Sorry for that . Two lines in the gradle showed red . So I was worried about it. I deleted those lines but the app did run fine . Would not do that mistake again :-(

2022-10-13 15:40 UTC, criticalAY commented
> @criticalAY Sorry for that . Two lines in the gradle showed red . So I was worried about it. I deleted those lines but the app did run fine . Would not do that mistake again :-(

There is no need to apology I would say I am myself a learner

2022-10-13 15:42 UTC, david-allison requested changes
Tests don't compile

```
e: warnings found and -Werror specified
w: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt: (712, 58): Unnecessary non-null assertion (!!) on a non-null receiver of type ListView
w: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt: (722, 53): Unnecessary non-null assertion (!!) on a non-null receiver of type ListView
w: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt: (723, 92): Unnecessary non-null assertion (!!) on a non-null receiver of type ListView
w: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt: (740, 53): Unnecessary non-null assertion (!!) on a non-null receiver of type ListView
w: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt: (741, 92): Unnecessary non-null assertion (!!) on a non-null receiver of type ListView
```

2022-11-04 04:53 UTC, Arthur-Milchior commented
Are you still working on it @SySagar ?

2022-11-04 07:24 UTC, SySagar commented
> Are you still working on it @SySagar ?

No actually. I have been stuck on the same bug [crashing of  app on different devices  other than emulators].

2023-01-10 07:37 UTC, closed without merging