NF: add comment on sync
ankidroid/Anki-Android pull request #12612
Opened 2022-10-09 19:31 UTC by Arthur-Milchior

I also renamed "normal" that is really not descriptive.

2022-10-09 19:48 UTC, BrayanDSO approved these changes
There are some other changes that aren't documented on the commit description, but it doesn't matter enough to block this

edit: pressed the wrong buttons

2022-10-09 20:05 UTC, BrayanDSO requested changes

2022-10-09 20:05 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
>      private fun fetchSyncStatus(col: Collection): SyncIconState {
The method actually returns a `SyncStatus` instead of a `SyncIconState` which makes its name confusing. And the javadoc doesn't describe what the method does either.

Something like `@return badge which should be displayed above the sync icon` would be better IMO

2022-10-10 11:34 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt
> +     * Whether the user settings ask not to show badge on top of the sync icon
The name `BADGE_DISABLED` seems self-explanatory. Adding a doc for this feels like extra noise in the code.

2022-10-10 11:38 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt
>          private val isDisabled: Boolean
Variable could use better naming like `isSyncStatusBadgeDisabled` or just `isBadgeDisabled`.

2022-10-10 21:35 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt
>          private val isDisabled: Boolean
Since it's used like once I'd go with what reads like plain English: `syncIconBadgeIsDisabledInPreferences` and nuke that javadoc

2022-10-12 19:40 UTC, Arthur-Milchior reviewed
Thanks.
@BrayanDSO I suspect a lot of comment may need to be updated, I feel like we usually use ankiweb to mean the sync server.

2022-10-12 19:40 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
>      private fun fetchSyncStatus(col: Collection): SyncIconState {
What?
It returns the icon state.That's even in the name of the returned enum. This enum directly maps to the way the badge should be displayed

2022-10-12 19:40 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +     * told the user they need to do a full sync. This should show more emergencies to act than [PendingChanges].
Both PendingChange and FullSync requires a badge that invite to do an action.
However, the FullSync should indicate that the action is really important while the PendingChange only notes that it should happen sometime. One is more important than the other

2022-10-12 23:06 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +     * There has been local changes since last update. We invite the user to upload it to ankiweb.
Actually in the new schema case, pending changes will be set if either the client or AnkiWeb has pending changes.

2022-10-13 15:00 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +     * There has been local changes since last update. We invite the user to upload it to ankiweb.
I'm confused. How can we ever know that? As far as I know, this requires to communicate with ankiweb, which only occurs during sync. Appart in the case where a sync started and failed.

Or are we adding extra network communication somewhere that are not sync?

2022-10-13 22:27 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
>      private fun fetchSyncStatus(col: Collection): SyncIconState {
The name says `fetchSyncStatus` but instead of `SyncStatus` it returns `SyncIconState`. 

(This is bound to happen when you have two things that should be one thing!)

2022-10-14 00:04 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +     * There has been local changes since last update. We invite the user to upload it to ankiweb.
If there are no local changes, it checks with AnkiWeb.

2022-10-31 00:33 UTC, mikehardy commented
Wasn't sure what to do with this one - didn't have strings so did not push so hard on it for merge
- needs a de-conflict
- if issues are resolved please mark them as resolved, I see many that github says are "outdated" but I don't know if they are truly handled or not

2023-01-06 02:05 UTC, closed without merging