NF: uses edit with block
ankidroid/Anki-Android pull request #12611
Opened 2022-10-09 16:24 UTC by Arthur-Milchior

To shorten slightly the code

2022-10-09 18:20 UTC, BrayanDSO requested changes

2022-10-09 18:20 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            CardUtils.markAll(ArrayList(notes), hasUnmarked)
unrelated

2022-10-09 18:20 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/anki/OnboardingFlagTest.kt
> +        AnkiDroidApp.getSharedPrefs(targetContext).edit { putBoolean(SHOW_ONBOARDING, true) }
functional change. This method didn't return anything before, nor it should

2022-10-09 18:20 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/libanki/sync/RemoteMediaServerTest.kt
> +        AnkiDroidApp.getSharedPrefs(AnkiDroidApp.instance)
ditto + the KotlinCleanups above can be removed

2022-10-10 11:39 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            CardUtils.markAll(ArrayList(notes), hasUnmarked)
I think we should allow unrelated changes if they tend to improve the code.

2022-10-11 08:21 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            CardUtils.markAll(ArrayList(notes), hasUnmarked)
Correct, I meant few unrelated changes which don't clutter the actual changes should be fine.

2022-10-11 08:21 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            CardUtils.markAll(ArrayList(notes), hasUnmarked)
Regarding the code history, maybe we can have code changes in a different commit if it is a part of the same PR.

2022-10-16 14:15 UTC, BrayanDSO approved these changes
LGTM. only a cleanup to remove, but not worth blocking this, as it may get conflicts easily

2022-10-16 14:15 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/libanki/sync/RemoteMediaServerTest.kt
>      @KotlinCleanup("use edit{} extension function")
can be removed

2022-10-17 04:00 UTC, mikehardy approved these changes
LGTM ("Let's Get This Merged" :laughing: )

2022-10-17 04:00 UTC, merged