Cleanup in [AbstractFlashcardViewer]
ankidroid/Anki-Android pull request #12626
Opened 2022-10-12 07:42 UTC by oyeraghib

## Purpose / Description
Cleanup in [AbstractFlashcardViewer]

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-10-15 11:10 UTC, BrayanDSO requested changes

2022-10-15 11:10 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +    public override val currentCardId: CardId? get() = currentCard!!.id
currentCard is nullable and this may throw a NPE. 

`currentCard?.id` should work here

2022-10-19 21:55 UTC, BrayanDSO approved these changes

2022-10-19 21:55 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +                val filename = when (val tag = currentCard?.let { getAvTag(it, url) }) {
Overall, I don't like this kind of change (moving variable declaration to inside the when paramater) as this makes it less readable. But as it is currently proposed by the IDE lint, LGTM.

I'd be personally in favor of creating an issue to remove this lint option on the project codestyle

2022-10-22 10:09 UTC, oyeraghib commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +                val filename = when (val tag = currentCard?.let { getAvTag(it, url) }) {
I agree.

2022-10-23 15:34 UTC, lukstbit approved these changes
Ok!

2022-10-23 15:36 UTC, merged