[KotlinCleanup] NavigationDrawerActivity
ankidroid/Anki-Android pull request #12621
Opened 2022-10-11 13:12 UTC by n1snt

## How Has This Been Tested?
- Tested on a physical device
- Tests

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-10-13 08:51 UTC, lukstbit requested changes

2022-10-13 08:51 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
> +            toolbar.isEnabled = true
Why was this added?

2022-10-14 03:18 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
> +            toolbar.isEnabled = true
I think I may have confused `.isEnabled` with `.apply` from the KotlinCleanup on line 107.

2022-10-24 09:59 UTC, n1snt commented
@lukstbit Made the requested changes.

2022-10-24 15:56 UTC, lukstbit approved these changes
Thanks!

2022-10-25 10:21 UTC, david-allison approved these changes

2022-10-25 10:22 UTC, merged