Kotlin Cleanup [Reviewer.kt]
ankidroid/Anki-Android pull request #12627
Opened 2022-10-12 08:48 UTC by oyeraghib

## Purpose / Description
Kotlin Cleanup [Reviewer.kt]

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-10-12 23:46 UTC, n1snt approved these changes

2022-10-13 06:59 UTC, david-allison requested changes

2022-10-13 06:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                }
this is worse, remove the cleanup and keep the code the same

2022-10-13 07:02 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                }
Possibly (needs testing):

```
        audioView?.let {
            it.visibility = if (it.visibility != View.VISIBLE) View.VISIBLE else View.GONE
            return
        }
```

2022-10-13 17:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
>          } else {
I posted a suggestion which I feel was cleaner, didn't it work?

2022-10-13 18:24 UTC, oyeraghib commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
>          } else {
Just pushed the changes. Tests passed on local.

2022-10-23 15:26 UTC, lukstbit requested changes

2022-10-23 15:26 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        override fun ankiGetLrnCardCount(): String {
These changes will not produce the expected behavior. Because `mLrnCount` and `mRevCount` are nullable types calling `toString()` on them when they are null will result in the `"null"` string being returned(which isn't probably what it's expected). You should revert these changes, when we handle the nullability of those properties then maybe we can also safely change the return type.

2022-10-24 02:11 UTC, david-allison approved these changes
Thanks!

2022-10-24 04:40 UTC, lukstbit approved these changes

2022-10-24 04:42 UTC, merged