Cleanup in [FieldEditText.kt]
ankidroid/Anki-Android pull request #12625
Opened 2022-10-12 06:43 UTC by oyeraghib

## Purpose / Description
Cleanup in [FieldEditText.kt]

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-10-13 09:06 UTC, lukstbit requested changes

2022-10-13 09:06 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> +        fun onImagePaste(editText: EditText, uri: Uri): Boolean
While editText can be safely be made not null, can you prove that uri can also be made not null? I remember looking at this code and seeing that this can be null based on the method's usages.

2022-10-14 16:35 UTC, lukstbit approved these changes

2022-10-14 19:49 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
>          }
this can be a `val`

2022-10-14 20:37 UTC, oyeraghib commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
>          }
I am not sure if `text` can be `val` because we are changing the values again inside the `if/else if` block

2022-10-15 09:25 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
>          }
```kotlin
val text = if (content == null) {
            ""
        } else if (replaceNewLine) {
            content.replace("<br(\\s*/*)>".toRegex(), NEW_LINE)
        } else {
            content
        }
```

2022-10-19 22:01 UTC, BrayanDSO approved these changes

2022-10-19 22:01 UTC, merged