NF: Add "postpone migration" backend util
ankidroid/Anki-Android pull request #12649
Opened 2022-10-13 21:20 UTC by Arthur-Milchior

2022-10-14 20:30 UTC, mikehardy requested changes
mostly just wanting interval to be a constant, and wanting it to be a smaller constant.
The pushiness is maybe non-trivial but the code suggestions are trivial I think, pending consensus on how hard to push the user

2022-10-14 20:30 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        if (delaySyncPostpone > 10 * 24 * 60 * 60) {
More generic comment, really just so that as we discuss timing we only have to change one spot.
Use constant

```suggestion
     * That is, the last time the user postponed was longer than our postpone time.
     */
    fun shouldWaitMoreToOfferToMigrate(): Boolean {
        val secondWhenMigrationWasPostponedLast = getSharedPrefs(baseContext).getLong(POSTPONE_MIGRATION_KEY, -1)
        if (secondWhenMigrationWasPostponedLast == -1L) return false
        val delaySyncPostpone = TimeManager.time.intTime() - secondWhenMigrationWasPostponedLast
        if (delaySyncPostpone > POSTPONE_MIGRATION_INTERVAL_DAYS * 24 * 60 * 60) {
```

2022-10-14 20:30 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +val POSTPONE_MIGRATION_KEY = "secondWhenMigrationWasPostponedLast"
extract migration interval to constant, I propose being more pushy: 5 days not 10

```suggestion
val POSTPONE_MIGRATION_KEY = "secondWhenMigrationWasPostponedLast"
val POSTPONE_MIGRATION_INTERVAL_DAYS = 5
```

2022-10-14 20:30 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
> +                (TimeManager.time as MockTime).addD(10)
```suggestion
                (TimeManager.time as MockTime).addD(POSTPONE_MIGRATION_INTERVAL_DAYS)
```

2022-10-14 20:30 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
> +                assertThat("When postpone occurred after 10 days, it should be time to offer migration", !deckPicker.shouldWaitMoreToOfferToMigrate())
```suggestion
                assertThat("When postpone occurred after our interval elapsed, it should be time to offer migration", !deckPicker.shouldWaitMoreToOfferToMigrate())
```

2022-10-14 20:30 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
> +                assertThat("When postpone occurred after 10 days twice, it should be time to offer migration", !deckPicker.shouldWaitMoreToOfferToMigrate())
```suggestion
                assertThat("When postpone occurred after our interval twice, it should be time to offer migration", !deckPicker.shouldWaitMoreToOfferToMigrate())
```

2022-10-14 21:13 UTC, david-allison reviewed
Are we definitely doing a timed 'postpone' dialog? 

I noted on the Figma that this would frustrate users

2022-10-16 22:59 UTC, Arthur-Milchior commented
Added similar functions for offering to back-up.
Since it's hard to know if a sync was offered by our flow or is standard, I believe that it's easier and acceptable to just record the last time this was offered

2022-10-17 02:21 UTC, mikehardy approved these changes
This works for me. I am open to and fine with any disagreement on the "5 days" level for the constant, I do not feel strongly about it. Happy to merge this and move on with whatever people feel strongly about, no need to re-ask

2022-10-21 00:26 UTC, BrayanDSO approved these changes

2022-10-21 00:26 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    fun shouldNotWaitMoreToOfferToMigrate(): Boolean {
I tend to avoid using negatives on boolean method names so it's more natural when you need to invert the condition. Probably this is the python coder in me that finds writing `if not shouldNotDoThis` confusing.

But FWIW, not worth blocking the PR

2022-10-21 00:28 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    fun shouldNotWaitMoreToOfferToMigrate(): Boolean {
And `DeckPicker` is already a huge scary monster. I'd appreciate if things could be organized on other files or even a package.

2022-10-21 00:31 UTC, merged