Dont sync in migration
ankidroid/Anki-Android pull request #12645
Opened 2022-10-13 19:22 UTC by Arthur-Milchior

You can test it by ensuring that `userMigrationIsInProgress()` return true.
![2022-10-13-212224_284x505_scrot](https://user-images.githubusercontent.com/357361/195690614-d1257f39-aa6f-4e03-a7db-aa5228221306.png)

2022-10-13 19:31 UTC, david-allison requested changes

2022-10-13 19:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
> +        AnkiDroidApp.getSharedPrefs(this).userMigrationIsInProgress()
style: I don't like this as an extension method. `Context` is already a god object.

2022-10-13 19:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            }
I don't think this is needed - it's the default

2022-10-13 19:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                startActivity(browserIntent)
Why not use `openUrl`?

2022-10-13 19:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                startActivity(browserIntent)
What is this URL? Doesn't seem valid

2022-10-13 19:31 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="migration_done">Update is done. You can sync again.</string>
This needs a lint ignore

2022-10-13 19:31 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="migration_done">Update is done. You can sync again.</string>
```suggestion
    <string name="migration_done">Storage migration completed successfully</string>
```

The sync icon will change, signifying visually that the sync can be started

2022-10-13 19:31 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="sync_impossible_during_migration">You can not sync your collection until the update is done.</string>
Don't use periods in single sentences (Material UI guidelines)

Provide the context the user needs

```suggestion
    <string name="sync_impossible_during_migration">Please wait for the storage migration to complete</string>
```

2022-10-13 19:43 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                startActivity(browserIntent)
I wanted link_scoped_storage_faq I'm confused how I got this one wrong.
And I missed openUrl

2022-10-13 19:43 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
> +        AnkiDroidApp.getSharedPrefs(this).userMigrationIsInProgress()
removed

2022-10-13 19:43 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="migration_done">Update is done. You can sync again.</string>
It needs to be put in the correct PR mostly. That was not the right one.

2022-10-13 19:43 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="migration_done">Update is done. You can sync again.</string>
Fine.

2022-10-13 20:43 UTC, mikehardy requested changes
just bike-shedding on the language a little bit otherwise fine

2022-10-13 20:43 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <!-- TODO: add "%1$d/%2$d media remains to update." to previous string.-->
I thought David's suggestion was pretty good - we're hard-blocking the user, we can at least be polite. Also I believe we are using migrate in a few places, so prefer migrate over update

```suggestion
    <string name="sync_impossible_during_migration">Please wait for storage migration to complete</string>
```

I cannot sync out a TODO really - is there a todo in strings to be aware of prior to pushing crowdin strings?

2022-10-13 20:59 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <!-- TODO: add "%1$d/%2$d media remains to update." to previous string.-->
Can we put in the strings with 'fake' values, as we did with `10` in the Card Export PR?

2022-10-13 21:14 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <!-- TODO: add "%1$d/%2$d media remains to update." to previous string.-->
Done. Assuming I understood your request (I have not looked at this PR recently)

2022-10-13 21:16 UTC, david-allison requested changes

2022-10-13 21:16 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +        %1$d/%2$d media remains to update.</string>
What does this mean?

`%1$d/%2$d files updated`

2022-10-16 12:28 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/02-strings.xml
> +        %1$d/%2$d media remains to update.</string>
10/90 files updated
I'd assume that would be clearly read as "out of 90 files, 10 are updated"
Admittedly, I know see it should be migrated for consistency with Mike's request

2022-10-17 04:15 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +        %1$d/%2$d media remain to migrate.</string>
I thought it was a little complex to read and I'm not sure how well it will translate. I think the total number of files is actually not useful info, where as the remaining count is, so maybe just the remaining count

```suggestion
        %1$d media files left to migrate.</string>
```

2022-10-17 04:16 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="sync_impossible_during_migration">You can not sync your collection until the update is done.\n
Just more direct language, and update -> migrate

```suggestion
    <string name="sync_impossible_during_migration">Sync is disabled until the migration is done.\n
```

2022-10-17 04:17 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            message(text = resources.getString(R.string.sync_impossible_during_migration, 5, 10))
only one (fake) parameter if you all like my suggestion of just showing files remaining, vs remaining vs total

```suggestion
            message(text = resources.getString(R.string.sync_impossible_during_migration, 5))
```

2022-10-17 14:25 UTC, mikehardy approved these changes
LGTM

2022-10-30 19:19 UTC, mikehardy approved these changes
I believe all feedback has been addressed

2022-10-30 19:23 UTC, mikehardy commented
rebased, fixed conflict, re-pushed, I cleared the strings out yesterday so I there are only a couple (based on crowdin activity log) of real changes - pending merge

2022-10-30 20:40 UTC, merged