Add window to Offer to migrate
ankidroid/Anki-Android pull request #12650
Opened 2022-10-13 21:32 UTC by Arthur-Milchior

You can test it by calling `offerToMigrate` in `onCreate()`
![Uploading 2022-10-13-233148_381x684_scrot.png…]()

2022-10-14 19:30 UTC, mikehardy commented
Material guidelines is only two buttons - so, Learn More could be a link, then the two buttons, I'll propose a text change

2022-10-14 19:36 UTC, mikehardy requested changes
A lot of wording suggestions - and the material dialog 2-button + link versus 3-button suggestion
All pretty trivial I think :crossed_fingers:

2022-10-14 19:36 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="scoped_storage_migrate">Update</string>
```suggestion
    <string name="scoped_storage_migrate">Migrate Storage</string>
```

I really want consistent messaging. Google calls it "Scoped Storage", and for us this is migrating our use of storage from legacy to scoped storage. Those are real terms, they are in use all over the internet, we use them internally, the name of the key is even "scoped_storage_migrate".

I would like to achieve consensus on this immediately, and I personally want to call it "Storage Migration".

I think it is useful to align with real terms in use by everyone else on the internet, and I think people generally have a feeling for what migrating storage might mean - moving files and such - and they can have immediately a sense of what's involved with regards to speed and risk.

Update sounds like it could just change your icons, it's so vague

2022-10-14 19:36 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="migration_update_request_warning_download">If you uninstall AnkiDroid, you\'ll need to download your full collection.</string>
Contractions are hard for non-english users to understand, I have learned, and not all languages will get translated quickly or ever, best to keep even the English version simple

```suggestion
    <string name="migration_update_request_warning_download">If you uninstall AnkiDroid, you will need to download your full collection again.</string>
```

2022-10-14 19:36 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="migration_update_request">Android new policies require us to make an update. It\'ll make AnkiDroid faster and your data more secure.
```suggestion
    <string name="migration_update_request">Android storage access policy requires us to change where we store your collection. When your data is migrated AnkiDroid will be faster and your data will be more secure.
```

2022-10-14 19:36 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    You won\'t be able to sync during the update.</string>
```suggestion
    You will not be able to sync during the storage migration.</string>
```

2022-10-15 15:04 UTC, Arthur-Milchior commented
Updated the screenshot

2022-10-15 15:07 UTC, Arthur-Milchior commented
> Material guidelines is only two buttons - so, Learn More could be a link, then the two buttons, I'll propose a text change

I don't understand what you mean. On https://material.io/components/dialogs#usage there are even examples of case with three actions.
Admittedly, when moving to four actions, I should stop using MaterialDialog class and find another way to create dialog. So maybe I'll just have to quickly remove all MaterialDialog classes for consistency, since you noted you don't like them generally.
But in this PR, I don't see a problem keeping it

2022-10-15 16:28 UTC, Arthur-Milchior commented
> A lot of wording suggestions - and the material dialog 2-button + link versus 3-button suggestion
All pretty trivial I think crossed_fingers

I found the place that state to use at most two buttons. Fine. But if you know how to put a link in a TextView I'd love to know about it. Because right now, no idea.

2022-10-15 18:54 UTC, oakkitten reviewed
I also strongly suggest moving these methods outside of `DeckPicker`, I don't think they belong there.

Also, while the names such as `shouldNotWaitMoreToOfferToMigrate()` are not bad they don't mention scoped storage. Migration can refer to such things as database schemas and preferences, so I would prefer this to mention scoped storage in some way, e.g. `shouldNotWaitMoreToOfferToMigrateScopedStorage()` or, better, `ScopedStorage.shouldNotWaitMoreToOfferToMigrate()`.

2022-10-15 18:54 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +val POSTPONE_MIGRATION_KEY = "secondWhenMigrationWasPostponedLast"
`POSTPONE_MIGRATION_KEY` says nothing about its purpose. I suggest either:

* `MIGRATION_WAS_LAST_POSTPONED_AT` + using milliseconds since epoch, or
* `MIGRATION_WAS_LAST_POSTPONED_AT_SECONDS` + unix time

Suffix “At” is my personal convention for timestamps. I think it works pretty well. I also prefer to store all time in milliseconds since that is the most common unit that various calls give you. (Or `Instant` if I can get away with it.)

2022-10-15 18:54 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +     * Show a window offering to migrate, postpone or learn more.
A “window” means something else in Android. Just “dialog”

2022-10-15 18:54 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        val messageSuffixId =
I'd use `when` instead of `if` if only not to have a 3-line `if` without `{}`s. Also i'd prefere a more useful name

```kt
val ifYouUninstallMessage = when {
    syncAuth() == null -> R.string.migration_update_request_warning_lost
    else -> R.string.migration_update_request_warning_download
}
```

P.S. `syncAuth() == null` is a bit confusing, might there be a better method?

2022-10-15 18:54 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        val message = """${getString(R.string.migration_update_request)}
I think this would be much more readable with good ol' string concatenation, as in

```kt
val message = getString(R.string.migration_update_request)
     + "\n\n"
     + getString(ifYouUninstallMessage )
```

2022-10-15 18:54 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                it.dismiss()
I'm not sure if this call is necessary. Also below

2022-10-15 18:54 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    fun postponeMigration() {
It's not clear what it means “to postpone a migration”. I suggest `val migrationWasLastPostponedAt` with `set()` and `get()`, or something like `setMigrationWasLastPostponedAtToNow()`, and removing the comment

2022-10-15 18:54 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    fun shouldWaitMoreToOfferToMigrate(): Boolean {
Given the above, I suggest simplifying the method to

```kt
fun shouldNotWaitMoreToOfferToMigrate(): Boolean {
    val timeSinceLastPostponed = currentTimeMillis() - migrationWasLastPostponedAt
    return timeSinceLastPostponed > MIGRATION_POSTPONE_INTERVAL
}
```

2022-10-15 18:54 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        if (delaySyncPostpone > 10 * 24 * 60 * 60) {
Extract `10 * 24 * 60 * 60` into a constant

2022-10-15 18:54 UTC, oakkitten commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="scoped_storage_migrate">Migrate Storage</string>
I was thinking, “migrate” is a term that users might not undestand well. Maybe “Move the collection”?

2022-10-15 18:54 UTC, oakkitten commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="migration_update_request_warning_lost">If you uninstall AnkiDroid, your data will be lost.</string>
* `migration_update_request_warning_lost` is a **super** confusing name, change to something else? To me it sounds like
 
    ![image](https://user-images.githubusercontent.com/1710718/196002927-094ae760-44e1-45f5-8094-a276b9649656.png)

* I don't think that data will be actually lost though?

2022-10-15 18:54 UTC, oakkitten commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
> +    fun testStartMigrationProcessNoPostpone() {
From this name I have no idea what this method is testing. I suggest removing the text from assertion, and putting it as the name, as in

```kt
@Test
fun `If user never postponed migration, shouldNotWaitMoreToOfferToMigrate() returns true`() {
    ActivityScenario.launch(DeckPicker::class.java).use { scenario ->
        scenario.onActivity { deckPicker: DeckPicker ->
            assertThat(deckPicker.shouldNotWaitMoreToOfferToMigrate())
        }
    }
}
```

I suggest changing the other test in a similar fashion

2022-10-15 18:54 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    fun offerToMigrate() {
I'd prefer a more concrete `showDialogThatOffersToMigrateStorage`

2022-10-15 19:17 UTC, Arthur-Milchior reviewed
Done the first part. However, @oakkitten , the point of drafting and having the first commit in its own PR was to have the comments in https://github.com/ankidroid/Anki-Android/pull/12649 so that we have a single point of discuss postponing

2022-10-15 19:17 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +val POSTPONE_MIGRATION_KEY = "secondWhenMigrationWasPostponedLast"
Took `MIGRATION_WAS_LAST_POSTPONED_AT_SECONDS`

2022-10-15 19:17 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        if (delaySyncPostpone > 10 * 24 * 60 * 60) {
The number of day is moved to a constnat to be easily changed when we discuss it. But the number of second in a day, I feel, is almost simpler this way, 24 60 60 it's simpler than "NUMBER_OF_SECOND_IN_A_DAY"

2022-10-15 19:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        val messageSuffixId =
Corrected with an helper method

2022-10-15 19:57 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        val message = """${getString(R.string.migration_update_request)}
Added new line again. But I like format

2022-10-15 19:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                it.dismiss()
indeed. Strange. I'd assume you can get the app not to close window, but it seems I was wrong

2022-10-15 20:08 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="scoped_storage_migrate">Migrate Storage</string>
Go discuss it with @mikehardy. Right now, I'll keep his choice!

2022-10-15 20:08 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="migration_update_request_warning_lost">If you uninstall AnkiDroid, your data will be lost.</string>
Yeah, we already discussed this. Data will just be hard to access, not actually lost

2022-10-15 21:18 UTC, Arthur-Milchior commented
Thanks @oakkitten, result seems great now

2022-10-15 22:48 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        val html = Html.fromHtml(message)
I think you can do `message.parseAsHtml()` btw

2022-10-15 22:48 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        val message = """${getString(R.string.migration_update_request)}
Maybe with `trimIndent()` then? I think this should be something like

```kt
@Language("HTML") val message = """
    ${getString(R.string.migration_update_request)}
    <br>
    <br>${getString(ifYouUninstallMessageId)}
    <br>
    <br><a href='$learnMoreURL'>${getString(R.string.scoped_storage_learn_more)}</a>
""".trimIndent()

2022-10-15 22:48 UTC, oakkitten commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="migration_update_request_warning_lost">If you uninstall AnkiDroid, your data will be lost.</string>
A bit more of correct horse battery staple below this line

2022-10-15 23:48 UTC, Arthur-Milchior commented
@oakkitten Can I please ask you to add a commit on top of it that just provides better name. I prefer that to guessing what names to use

2022-10-15 23:53 UTC, Arthur-Milchior commented
Thanks @oakkitten

2022-10-16 00:50 UTC, oakkitten commented
A wise man once said, naming is the most subtle art of programming. (Not really, it was me and I'm not wise.) Anyway, first of all,

* I still don't quite understand these strings. “If you uninstall AnkiDroid, your data will be lost.” is just wrong, isn't it? IIRC, the data won't be lost, but since AnkiDroid doesn't have the machinery to import it, the user would have to move it manually. Why not say it like that? Or for that matter, why not allow importing the data in the first place?
* As for the name, well, one simple way is just to put the string into its key, as in `migration_if_you_uninstall_you_will_have_to_redownload`.

By the way I have my own scheme for string keys, it's like this:
* A key is composed of chunks separated by `__` (double underscores)
* Chunks are words separated by `_`, and in case of view names, the name of the class verbatim

For instance:
* `etc__application_name`: App name
* `error__etc__not_connected`: A generic “Not connected” error
* `error__pref_validation__ssh_host_not_set`: More specific error
* `pref__connection__ssl__client_certificate`: Preferences → SSL settings → Client sertificate (title)
* `pref__connection__ssl__client_certificate__summary`: Preferences → SSL settings → Client sertificate (summary)
* `pref__ClearCertPreference__prompt`: Prompt message of a `ClearCertPreference`

Given this scheme, the above would be `dialog__storage_migration__if_you_uninstall_you_will_have_to_redownload`

2022-10-16 00:58 UTC, Arthur-Milchior commented
As you otherwise seems to be someone we can hold conversation with and discuss difficult subject, I really wonder how it is possible you do not understand what, as far as I recall, multiple people tried to explain on discord when you asked a similar question.
If I were the only one having trouble, I'd blame my communication skills. However, I suspect this is not the case here.
Yeah, we are imprecise. Technically false even. You're perfectly right. But we are NOT going to help people individually. They won't even reach to us. They may not be able to understand how to access a folder, may not have control over their device if it's managed, may not have a computer to help. For all intent and purpose, data will be lost for many in this situation.
It feels to me like you are asking why we state that some data are erased when some software could find back the erased bytes  that have not been overwritten. Yeah, technically, data is not deleted, it's only not referenced in the storage tables, and so it's technically possible to access them. Still, for all intent and purposes, the user is better thinking about them as deleted and not being told that there may be complex way to get back data

2022-10-16 01:45 UTC, oakkitten commented
I remember the conversation; I must have missed the end of the discussion. I just hate to lie to the user. You don't have to lie, you can just say something along “If you reinstall AnkiDroid, it will not be able to open your collection.” I don't see the reason to lie, this is about just as scary for a regular Joe and does not confuse the more tech savvy people. And I mean, you don't have to be very tech savvy to know that folders in your storage don't get deleted with apps? This will be confusing to *a lot* of people for no good reason, IMO.

Anway, there will be users who for some reason will install a new version of AnkiDroid after deleting the old one. Why not just allow importing collection folders?

2022-10-16 14:08 UTC, Arthur-Milchior commented
I'm sorry if I break the news to you, but it's an actual problem in CS undergrad. More and more students have only used smartphone and has no idea what a folder/directory is, because it's generally hidden from you. So yeah, today, knowing what a directory hierarchy is is actually tech savy knowledge. And I don't want to have to explain to a user how to navigate.

But I agree that your sentence is fine

2022-10-16 14:46 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="scoped_storage_migrate">Migrate Storage</string>
TMK, as this doesn't change the key, only the english translation would be changed.

My suggestion is to use the `scoped_storage_title` (`Storage migration`) as the dialog title, and `scoped_storage_migrate` (`Migrate`, which means that you should revert this change) as the positive button text, which are good enough strings IMO and would keep the translations

2022-10-16 14:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="scoped_storage_migrate">Migrate Storage</string>
dONE

2022-10-17 02:25 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="scoped_storage_migrate">Migrate Storage</string>
"Storage migration" for all the things in my opinion. I don't often use "current political discourse" as a ... positive lesson but if I have learned one thing from it, it is that using the exact same phrase every time all the time never varying it has a quality all it's own. And I *think* "storage migration" is an okay phrase. We're already re-using that specific key (`scoped_storage_title`) in this way in 2 places, I'm fine chaining all sorts of things to it

2022-10-17 02:26 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="migration_update_request_warning_lost">If you uninstall AnkiDroid, your data will be lost.</string>
"See? you already memorized it!"

2022-10-17 02:30 UTC, mikehardy commented
> More and more students have only used smartphone and has no idea what a folder/directory is, because it's generally hidden from you. So yeah, today, knowing what a directory hierarchy is is actually tech savvy knowledge.

This is a really interesting point. I actually re-did an interface aimed at 20-30 year old users specifically after reading what I *guess* is the article you read (here's a handle: https://news.slashdot.org/story/21/09/27/2032200/students-dont-know-what-files-and-folders-are-professors-say)

I switched the UI from a hierarchical nav system with objects and sub-objects etc to ... a big list with a search. They **LOVED** it. Elated. I was disappointed (those whippersnappers!! but also happy, the users are the important part)

Anyway, a bit of a tangent, but I do see a point about not actually lying to users. If it is at all possible to hide the part about filesystems and folders and whatever while *still* being technically accurate, I'm for that.

2022-10-17 02:35 UTC, mikehardy approved these changes
I'm okay with all of this as is right now.

I see you sneaking an AlertDialog in @oakkitten :eyes: - but that's fine ;-) (this is intended as a humorous reference to the MaterialDialog vs AlertDialog conversation earlier, please do not read anything more into it than is justified by a wink smile, for the avoidance of doubt)

I'm okay with all the strings as is I think they are honest and still easy to read. I might be missing something but that's my take.

I believe the 3rd commit is tied up with another PR? The backend utility to check when it was last postponed? Commit seems fine in this commit stream as well though.

2022-10-30 20:37 UTC, mikehardy commented
The learn more link addition to AlertDialog.Builder has been peeled to #12671 and appears close to merge there, at which point this will need another rebase to drop those commits and use the final version. Requested concrete change there from @BrayanDSO to finish it up (I think)

2022-10-30 22:37 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="migration_update_request_warning_lost">If you uninstall AnkiDroid, your data will be lost.</string>
I altered the string to be a bit more language like during my last rebase to drop commits from related PRs as they went through

2022-10-30 22:45 UTC, mikehardy commented
The amount of refinement that went on in here as parts were pulled out (then refined heavily outside + merged) while this was worked on is incredible. I think it looks good now, as a PR

I'm doing final testing now but unless local emulators show a problem -> pending merge / open for refactor later

2022-10-30 22:54 UTC, mikehardy commented
Had square corners.

![image](https://user-images.githubusercontent.com/782704/198905706-ff690052-2179-4f08-9859-2824aa894287.png)


Fixed

![image](https://user-images.githubusercontent.com/782704/198905719-6a3a7161-ec54-439c-9103-a7a822580710.png)

2022-10-30 23:23 UTC, merged