Adding a scoped storage migration channel
ankidroid/Anki-Android pull request #12653
Opened 2022-10-14 01:49 UTC by Arthur-Milchior

2022-10-14 03:52 UTC, lukstbit commented
Compilation errors for tests.

2022-10-14 17:29 UTC, lukstbit approved these changes
Combined with squash merge the changes LGTM.
The second commit(lint complains about API level) and the third commit(the importance property is not defined) fail.

2022-10-14 19:41 UTC, BrayanDSO commented
This has got some conflicts

2022-10-14 21:19 UTC, mikehardy requested changes
Apparently has some conflicts and *if the goal is to rebase merge) some issues with the commit stream on individual commits (https://github.com/ankidroid/Anki-Android/blob/main/tools/test-commits.sh is an easy way to test them, though it will melt your machine ;-) - I run it `/bin/nice -n 19 ./tools/test-commits.sh <hash>` personally)

My actual suggestions are just me continuing to act as police for the strings and push my personal vision of "Storage migration" as the phrase to use. I recognize what string to use is still up for discussion though

2022-10-14 21:19 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationChannels.kt
> +            Channel.SCOPED_STORAGE_MIGRATION -> res.getString(R.string.scoped_storage_channel_name)
```suggestion
            Channel.SCOPED_STORAGE_MIGRATION -> res.getString(R.string.scoped_storage_title)
```

2022-10-14 21:19 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="scoped_storage_channel_name">AnkiDroid upgrade</string>
```suggestion
```

2022-10-15 14:44 UTC, Arthur-Milchior commented
So, I changed the text, and rebased.

2022-10-15 21:05 UTC, mikehardy approved these changes
I fixed up the last 2 commits and pushed it out, pending CI, thanks!

2022-10-15 22:50 UTC, mikehardy requested changes
Grrr - an API availability lint check - must be fixed

2022-10-15 23:47 UTC, Arthur-Milchior commented
I failed to understand why it was compiling locally. Until I saw I used `RequiresApi` instead of `TargetApi`.

2022-10-17 02:13 UTC, mikehardy approved these changes
And now it's not even a strings change :-)
Thanks for the final fixup

2022-10-17 02:13 UTC, merged