Kotlin Cleanup: Changed to scope function in DeckPickerTest
ankidroid/Anki-Android pull request #12667
Opened 2022-10-15 20:41 UTC by alyoshenka

## Pull Request template

## Purpose / Description
Fix `@KotlinCleanup` tag for better code styling.

## Fixes
Partial fix for issue 10489
I am not linking to this issue directly so that it does not automatically resolve it when this PR goes through. This is my understanding of what happens when linked issues are attached to PRs.

## Approach
This code changes from using a variable representation to a scoped function. This helps to enhance readability. The variable is referenced within scope by `it`.

## How Has This Been Tested?
This has been tested both as an individual test file and as part of the entire gradle test suite:
- `./gradlew AnkiDroid:testPlayDebugUnitTest --tests com.ichi2.anki.DeckPickerTest.verifyCodeMessages`
- `./gradlew AnkiDroid:testPlayDebugUnitTest --tests com.ichi2.anki.DeckPickerTest`
- `./gradlew jacocoTestReport`

## Learning (optional, can help others)
[This](https://kotlinlang.org/docs/scope-functions.html) is Kotlin's Scope Function reference.

## Checklist

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- ~[ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)~
- ~[ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)~

2022-10-16 17:06 UTC, BrayanDSO commented
As I think that the cleanup purpose was to remove the repetitions of `codeResponsePairs`, I'd do (untested)
```kotlin
@Test
    fun verifyCodeMessages() {
        val context = targetContext
        val codeResponsePairs = hashMapOf(
            407 to context.getString(R.string.sync_error_407_proxy_required),
            409 to context.getString(R.string.sync_error_409),
            413 to context.getString(R.string.sync_error_413_collection_size),
            500 to context.getString(R.string.sync_error_500_unknown),
            501 to context.getString(R.string.sync_error_501_upgrade_required),
            502 to context.getString(R.string.sync_error_502_maintenance),
            503 to context.getString(R.string.sync_too_busy),
            504 to context.getString(R.string.sync_error_504_gateway_timeout)
        )
        ActivityScenario.launch(DeckPicker::class.java).use { scenario ->
            scenario.onActivity { deckPicker: DeckPicker ->
                for ((key, value) in codeResponsePairs) {
                    assertEquals(deckPicker.rewriteError(key), value)
                }
            }
        }
    }
```

Pinging @lukstbit, as you're the cleanup author and may have a stronger opinion on that

2022-10-17 03:13 UTC, mikehardy commented
Meta note: github will close an issue if you say `Fixes #<number>` (or "closes") but if you just say `Related #<number>` you get the link without the automation, so still some nice cross-reference links between the two but it won't close

2022-10-17 12:08 UTC, lukstbit commented
I was probably thinking about an `apply {}` to encapsulate the `HashMap` initialization code. But, as usually, we should also strive to make the code more kotlin like so @BrayanDSO 's suggestion to use the platform `hashMapOf` is much nicer.

@alyoshenka Thank you for the contribution, I would ask you to use @BrayanDSO 's  proposed code as it makes it slightly more readable.

2022-10-20 23:42 UTC, BrayanDSO requested changes

2022-10-20 23:50 UTC, alyoshenka commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
> +        // getResourceString() is the wrapper for targetContext.getString(resource)
Thanks for the suggestion, it takes a moment to get accustomed to new coding styles and I appreciate the help!

2022-10-20 23:51 UTC, BrayanDSO approved these changes
Looks good to me. Thanks for the contribution!

2022-10-20 23:54 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
> +        // getResourceString() is the wrapper for targetContext.getString(resource)
> it takes a moment to get accustomed to new coding styles and I appreciate the help!

I know this feeling. Especially here, with more than 300 contributors with very different past experience, code styles and personalities. But time solves all of the issues

2022-10-21 04:10 UTC, lukstbit approved these changes
Thanks!

2022-10-21 04:12 UTC, merged