Correcting Hyperlink Color In About Section
ankidroid/Anki-Android pull request #12662
Opened 2022-10-14 12:12 UTC by TomerPacific

## Pull Request template

## Purpose / Description
It can be observed that in the About section, the hyperlink colors are not consistent.

## Fixes
#12595 

## Approach
By adding a specific attribute for anchor link colors, we can access this attribute based on the theme (light/dark)

## How Has This Been Tested?
I have used an emulated device and saw the anchor link colors in light and dark theme (screenshots attached).

## Learning (optional, can help others)
Not relevant

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [X] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

## Screenshots
![qemu-system-x86_64_2PssWR9hIK](https://user-images.githubusercontent.com/23402988/195843882-ac69fa72-6c27-461a-8b20-bb584f7d6725.png)

![qemu-system-x86_64_g58hSbVzHM](https://user-images.githubusercontent.com/23402988/195843887-97f0a033-d0fc-49ca-be8b-1bee570e0503.png)

2022-10-14 21:50 UTC, mikehardy commented
Thanks for the first PR! I edited the description above (check it out) to explicitly say `Fixes #<number>` so github auto-connects the issue and PR and will close the issue when merged. We'll see what Brayan thinks of the PR

2022-10-16 19:21 UTC, BrayanDSO requested changes
Hello there. Thanks for the contribution! Left a comment

2022-10-16 19:21 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
> +        val anchorTextThemeColor: Int = ThemeUtils.getThemeAttrColor(this, R.attr.anchorTextColor)
Could you use `colorAccent` as the color attr? This is the default on the About section so the color is consistent

2022-10-17 10:37 UTC, TomerPacific commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
> +        val anchorTextThemeColor: Int = ThemeUtils.getThemeAttrColor(this, R.attr.anchorTextColor)
@BrayanDSO  - Got it. So I am going to delete the custom attribute I created.

2022-10-17 10:53 UTC, TomerPacific commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
> +        val anchorTextThemeColor: Int = ThemeUtils.getThemeAttrColor(this, R.attr.anchorTextColor)
@BrayanDSO  - I made several more commits per your comment.

2022-10-17 17:23 UTC, BrayanDSO approved these changes
*L*ooks
*G*ood
*T*o
*M*e

---

Note for the future (not related to your PR, but as a general comment for the repository): it would be nice to have an util method to convert colors to HEX. There are some other places on the app that do this same conversion

2022-10-17 18:06 UTC, n1snt requested changes

2022-10-17 18:06 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
> +        val anchorTextColor: String = String.format("#%06X", 0xFFFFFF and anchorTextThemeColor)
I think the data type declared here is redundant and can be removed as it will return Int & String by default.

2022-10-17 18:11 UTC, n1snt reviewed
Another suggestion would be to avoid having 6 commits just to have 1 change in a file.
You can delete/merge all the commits using `git rebase`

2022-10-17 18:22 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
> +        val anchorTextColor: String = String.format("#%06X", 0xFFFFFF and anchorTextThemeColor)
IMHO, this is a matter of personal taste and a overall low value discussion and efforts, so I'd go with implementer's choice.

2022-10-18 03:17 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
> +        val anchorTextColor: String = String.format("#%06X", 0xFFFFFF and anchorTextThemeColor)
Yeah. Not something it should be blocked upon.

2022-10-18 17:38 UTC, TomerPacific commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
> +        val anchorTextColor: String = String.format("#%06X", 0xFFFFFF and anchorTextThemeColor)
@n1snt  - Removed type declaration.

2022-10-18 18:25 UTC, n1snt approved these changes

2022-10-18 18:27 UTC, TomerPacific commented
@BrayanDSO  - Failed attempt at rebasing. Trying again.

2022-10-18 18:42 UTC, TomerPacific commented
@BrayanDSO - I think I did it (first time rebasing for me).

2022-10-18 22:50 UTC, BrayanDSO requested changes

2022-10-18 22:50 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
> +            return this.getString(key, defValue.toString())!!.toLong()
these changes aren't related to the PR. Perhaps you got it while rebasing the branch

2022-10-18 22:51 UTC, BrayanDSO commented
> [BrayanDSO](https://github.com/BrayanDSO) - I think I did it (first time rebasing for me).

Rebasing is a very handy skill to have. Thanks for the initiative.

2022-10-19 19:20 UTC, TomerPacific commented on AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
> +            return this.getString(key, defValue.toString())!!.toLong()
@BrayanDSO  - Yes, I think it is related to the rebase. Do I just revert these?

2022-10-19 19:40 UTC, TomerPacific commented on AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
> +            return this.getString(key, defValue.toString())!!.toLong()
@BrayanDSO - Yes, I think it is related to the rebase. Reverting those changes.

2022-10-21 08:55 UTC, TomerPacific commented
@BrayanDSO ?

2022-10-22 09:18 UTC, BrayanDSO approved these changes
LGTM. Thanks

2022-10-23 12:25 UTC, david-allison approved these changes

2022-10-23 12:26 UTC, merged