Add `migrate` in DeckPicker
ankidroid/Anki-Android pull request #12666
Opened 2022-10-15 20:33 UTC by Arthur-Milchior

It suspend during the important part of the migration and then call a function to start the service. This one is TODO for the moment.
We'll need this as a separate function since we'll need to start the service also if the service is not working and we still have work to do

2022-10-17 03:11 UTC, mikehardy reviewed
just silly language edits. I'm mostly reviewing at all to leave this question though: what's left to do here? Seems fine as far as it goes now

2022-10-17 03:11 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="start_migration_progress_message">Storage migration is starting. You can restart using AnkiDroid very shortly.</string>
Active voice instead of passive voice, removing "very shortly" in case it is making a promise in the user's mind that we cannot keep (imagine perhaps a 100MB collection and a really really slow phone?)
```suggestion
    <string name="start_migration_progress_message">Starting storage migration. You may resume using AnkiDroid shortly.</string>
```

2022-10-17 03:11 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="migration_part_1_done_resume">You can resume using AnkiDroid.
```suggestion
    <string name="migration_part_1_done_resume">You may resume using AnkiDroid.
```

2022-10-17 03:11 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +\nStorage migration ongoing.</string>
```suggestion
\nStorage migration will continue in the background.</string>
```

2022-10-17 12:56 UTC, lukstbit requested changes

2022-10-17 12:56 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                migrateEssentialFiles(baseContext)
Note that this will run on the main thread, you'll want to wrap this call with a `withContext(Dispatchers.IO) {}` block.

2022-10-18 17:02 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="start_migration_progress_message">Storage migration is starting. You can restart using AnkiDroid very shortly.</string>
You give me an idea. Media can be encoded as base64. So instead of having a media collection that is never backed-up, I could move everything to base64 encoding. Admittedly, I'd take even more space in the DB since I would not get saving from reusing the same image. But maybe I could ensure that I would never lose a media when I restore a back-up.

I would not do it for ankiweb's sake.

If I really cared about hugest collection, I'd ask DAE, assuming that ankiweb is a pretty good approximation. But I'll still agree about your remark related to the slow phone

2022-10-18 17:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                migrateEssentialFiles(baseContext)
Thanks for letting me know. Added.
I admit I don't understand then why we don't use it everywhere we used to use CollectionTask since it was also using IO usually

2022-10-19 05:32 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                migrateEssentialFiles(baseContext)
We do use it, it's used by the method `withCol`. Some parts of the code in those coroutines could be moved to the background as well but that's for later to go through the code to make sure it's correct.

2022-10-19 05:34 UTC, lukstbit approved these changes

2022-10-30 23:04 UTC, mikehardy approved these changes
These look good, I've rebased against main and will shepherd these through

2022-10-31 00:14 UTC, merged