Task non null
ankidroid/Anki-Android pull request #12660
Opened 2022-10-14 11:29 UTC by Arthur-Milchior

First part of #12659 and of another PR to come. Which needs to improve nullability for ease of creating notification from scoped storage migration

2022-10-14 21:46 UTC, mikehardy approved these changes
I was okay with these on the draft, still okay with them here.

I do want a stronger Kotlin-speaker to give them a look though :pray:

2022-10-16 00:11 UTC, Arthur-Milchior commented
I remove the high priority. This one helps, but it's not blocking until a decision is taken

2022-10-16 09:11 UTC, lukstbit requested changes

2022-10-16 09:11 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/async/TaskManager.kt
> +            listener: TaskListener<in Progress, in Result>?
Based on the current types the `Result` can't be made not nullable because:
- `LoadDeckCounts` returns null from it's task when it throws an exception
- the `CollectionTask` itself returns null from `doInBackground` if the Collection is not available

I guess we could merge this now if you really needed it and the issues above will be resolved soon once each of those tasks is migrated to coroutines.

2022-10-16 12:47 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/TaskManager.kt
> +            listener: TaskListener<in Progress, in Result>?
`LoadDeckCounts` return a nullable type, I entirely agree. But in this case, `Result` is `List<TreeNode<DeckDueTreeNode>>?`, so there is no problem.
What this change does is ensuring that we don't force the listener to accept nullable types. But if we instantiate a call to `launchCollectionTask` with a nullable result, then the taskListener will have a Nullable result. This change just ensure that when it's possible to let the TaskListener know that it won't receive a null result when it's impossible.

On the other hand, I missed the `doInBackground`, you're perfectly right. I had not realized that, going through AsyncTask which is in java, nullability is not as well checked than I believed. Nice catch, thanks a lot!

2022-10-16 12:51 UTC, Arthur-Milchior commented
@lukstbit I removed the first commit. Thanks for catching it!

2022-10-16 13:30 UTC, lukstbit approved these changes

2022-10-16 14:04 UTC, merged