NF: save last successful export
ankidroid/Anki-Android pull request #12670
Opened 2022-10-15 22:52 UTC by Arthur-Milchior

We save MOD and date. We intend to take it into account if sync is not activated.

MOD because if there was no change since last export, it's clear we don't risk loosing data.

Actual time because that will ensure we can know how much time of review/card creation can be lost.

2022-10-16 07:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +const val LAST_SUCCESSFUL_EXPORT_AT_SECOND_KEY = "last_successful_export_mod"
These are the same value, is this intentional?

2022-10-16 12:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +const val LAST_SUCCESSFUL_EXPORT_AT_SECOND_KEY = "last_successful_export_mod"
Corrected thanks

2022-10-16 14:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +const val LAST_SUCCESSFUL_EXPORT_AT_SECOND_KEY = "last_successful_export_mod"
Not. Corrected. Thanks

2022-10-16 16:34 UTC, lukstbit requested changes
Along with the issue below, I'm not sure how precise do you want this export time saving to be. At the moment you could miss a share collection action if:
- I first save the collection as apkg(so there's no prefs registration in saveSuccessfulCollectionExport)
- at this moment mExportFilename will have a path with apkg at the end
- I try to share a collection(which ends in colpkg), this will be ignored by your code as it looks at mExportFilename which has the previous save apkg path
- your code doesn't use the path in shareFile

This is kind of an edge scenario so if you don't mind this(as we will not know what happened in the share action done by the user then)then fixing the property access below is ok. If you want to also avoid the scenario above your could write your method like:

```
private fun saveSuccessfulCollectionExportIf(condition: Boolean) {
        if (condition) {
            val prefs = AnkiDroidApp.getSharedPrefs(activity)
            prefs.edit { putLong(LAST_SUCCESSFUL_EXPORT_AT_SECOND_KEY, TimeManager.time.intTime()) }
            val col = collectionSupplier.get()
            prefs.edit { putLong(LAST_SUCCESSFUL_EXPORT_AT_MOD_KEY, col.mod) }
        }
    }
```
Then in `shareFile` you could use the `path.endsWith(".colpkg")` as the condition and in `saveFileCallback` you could use `mExportFileName.endsWith(".colpkg")` as the condition.

2022-10-16 16:34 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +        if (! mExportFileName.endsWith(".colpkg")) return
This will fail if you export the collection and then you first try to share because your method will try to access the `mExportFilename property` which is only initialized in the save path. So at a minimum you would need a `::mExportFilename.isInitialized` condition as well in the if clause.

2022-10-16 16:52 UTC, Arthur-Milchior commented
Thanks a lot for your review. Really appreciated.

Whether a back-up actually occurred is hard to define. So I'll just state that I want that there is an easy way for the user to be sure that they did an export using the standard path. If it's not detected as an export, they can always override the warning and migrate anyway. What I don't want is to believe there is an export while actually there are none.
Admittedly, I even fail at this task because the user may start sending the file, then not sending it, and we wouldn't know it. E.g. if they start to send it as an email attachment and the email is not sent.

2022-10-17 11:59 UTC, lukstbit commented
@Arthur-Milchior I understand. I would ask you to add the fix above:

```
private fun saveSuccessfulCollectionExportIfRelevant() {
    if (::mExportFilename.isInitialized && !mExportFileName.endsWith(".colpkg")) return
```
this will prevent a regression here which would affect the users even outside scoped storage related code. Then we could merge this.

2022-10-30 21:04 UTC, mikehardy approved these changes
verified all comments resolved (or I resolved them via incorporating changes) while rebasing this to main to resolve conflict introduced by #12707

This should be good to go

2022-10-30 21:04 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +        if (! mExportFileName.endsWith(".colpkg")) return
great catch, I am rebase-editing and have incorporated your suggestion

2022-10-30 21:04 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +const val LAST_SUCCESSFUL_EXPORT_AT_SECOND_KEY = "last_successful_export_mod"
verified resolved

2022-10-30 21:31 UTC, mikehardy commented
CI flake, immaterial but re-running anyway. Not going to wait on it though, nearly out of window for the day

2022-10-30 21:31 UTC, merged

2022-11-02 22:47 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +        if (! mExportFileName.endsWith(".colpkg")) return
Thanks a lot @lukstbit !