NF: introduce makeLinksClickableAndShow
ankidroid/Anki-Android pull request #12671
Opened 2022-10-16 01:51 UTC by Arthur-Milchior

Code by Oakkitten. Tested in #12650

2022-10-16 02:08 UTC, oakkitten commented
I'd keep it as `makeLinksClickable()`. It *currently* requires the caller to do `create().makeLinksClickable().show()` but it's simpler this way and can be using in situations where you don't immediately show the dialog, e.g. when overriding `DialogFragment.onCreateDialog`

2022-10-16 06:27 UTC, david-allison requested changes
Nothing major, needs testing on an older emulator

2022-10-16 06:27 UTC, david-allison commented on .idea/dictionaries/milchior.xml
> +      <w>oakkitten</w>
Use `usernames.xml` here

2022-10-16 06:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    fun AlertDialog.Builder.addLearnMoreLinkAndShow(@Language("HTML")message: String): AlertDialog {
```suggestion
    fun AlertDialog.Builder.addLearnMoreLinkAndShow(@Language("HTML") message: String): AlertDialog {
```

2022-10-16 06:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    fun AlertDialog.Builder.addLearnMoreLinkAndShow(@Language("HTML")message: String): AlertDialog {
Logically, this method doesn't belong in the DeckPicker, it should be in a Scoped Storage specific class. 

Moving it would mean the name makes sense: `addLearnMoreLinkAndShow` only makes sense when we understand the context of these to be 'learn more' to be 'scoped storage'

2022-10-16 06:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        @Language("HTML") val messageWithLink = """$message
What happens on API < 24 when `Html.FROM_HTML_MODE_LEGACY` isn't available (does this still produce a correct `Spannable`)?

2022-10-16 13:12 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    fun AlertDialog.Builder.addLearnMoreLinkAndShow(@Language("HTML")message: String): AlertDialog {
Moved

2022-10-16 13:45 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        @Language("HTML") val messageWithLink = """$message
I just tested on API 22 and it work as well. 
![2022-10-16-154509_406x654_scrot](https://user-images.githubusercontent.com/357361/196038876-b86e5f06-4c32-47a6-867a-bb19e8af8b04.png)

2022-10-16 16:53 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    fun AlertDialog.Builder.addLearnMoreLinkAndShow(@Language("HTML")message: String): AlertDialog {
@Arthur-Milchior, have you pushed this change or do you plan to do something else before pushing it?

2022-10-16 17:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    fun AlertDialog.Builder.addLearnMoreLinkAndShow(@Language("HTML")message: String): AlertDialog {
@BrayanDSO pushed.

Thanks for the question. 
Seems magit sometime don't warn me when force push fails, that seems new. No idea what occurs. I'll pay attention

2022-10-16 19:00 UTC, BrayanDSO commented
> ![2022-10-16-154509_406x654_scrot](https://user-images.githubusercontent.com/357361/196038876-b86e5f06-4c32-47a6-867a-bb19e8af8b04.png)

Based on this screenshot, may I ask why the trouble of adding a clickable `Learn more` section inside the dialog instead of using it as a third Neutral button?

If the reason is "because Neutral buttons aren't encouraged by Material", I'd say that adding a `Learn more` link isn't encouraged either. The reason for `Learn more` buttons not being encouraged is because after tapping them the user will left dialog open, without completing/following its flow. A `Learn more` link would be no different.

2022-10-16 19:03 UTC, Arthur-Milchior commented
@mikehardy I think the question is for you, as you were the one against the neutral button.

I'd simply add that at least in one version, we were allowing user to answer:
* yes
* now
* later

And in this case, learn more could not be neutral. Obviously, it may not be something we want to add in the first place,

2022-10-17 02:43 UTC, mikehardy commented
Re 2 or 3 buttons I do not feel super strongly about it, though I do consider Material.io as a *usually reasonable* set of guidelines, mostly useful so that we don't discuss UI all the time and just get on with things.

That's not working here. We keep discussing this dialog. It's a waste of time in my opinion, or at least, not a good use of time.

I think this is already solved in code, in that the dialog works. However, if 3 buttons works for everyone this is a dialog that has a built-in sunset - it will go away no matter what over time - so even as a "violation" of material design, it's temporary.

So my "judgement" as far as it goes is, in this case I do not really care. It seems like there are a few people also heavily invested in AnkIDroid arguing for three buttons being fine, and it would be less code I think.

I can only guess that Arthur does not really care either other than going back to 3 buttons would be one more set of edits + commits. But it would also be a deletion of the clickable link helper etc. So, in the end I will say "3 buttons is fine if you want" and fall back to "Implementor's choice" that is: Arthur is *killing it* with scoped storage PRs, so I'd give his preference based on how his available time preference. And post-commit I would still say implementor's choice if someone wanted to PR an edit to 3 buttons, "no me importa" (Spanish: doesn't bother me but maybe closer to "I don't really care"). :-)

2022-10-17 02:45 UTC, mikehardy approved these changes
Approve, but I would also approve a 3-button style here. I strongly approve of a merge and move on either way

2022-10-17 17:26 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/Utils.kt
> +    create().apply {
@oakkitten, as you are the one that created the method, it isn't better to make this extend `AlertDialog` instead of `AlertDialog.Builder`, so it isn't mandatory to have this as the last call on the builder?

2022-10-17 19:12 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/Utils.kt
> +    create().apply {
Yeah, I think what I originally suggested was `AlertDialog.makeLinksClickable()`

2022-10-17 19:26 UTC, oakkitten commented
> Based on this screenshot, may I ask why the trouble of adding a clickable Learn more section inside the dialog instead of using it as a third Neutral button?

Just an opinion, and not a very strong one; I like the way with the link as it separates non-action from actions. Also, it won't close the dialog, and I guess you'd expect the neutral button to close it. I also saw other apps do it this way and I liked how it felt. (On the screenshot above, Learn more *button* would sit roughly where the Learn more link sits now so it would also be separated. But this only works for very big screens/small UI elements. I prefer my display stuff big, so I'd probably see the three buttons in a vertical arrangement—not very separated.)

Oh and by the way, that dialog has very sharp corners!

2022-10-17 23:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/Utils.kt
> +    create().apply {
I'd be fine using both. It just that I realized that in every dialog, I was doing `.create().makeLinksClickable().show()` and decided that I didn't want to repeat code

2022-10-17 23:49 UTC, Arthur-Milchior commented
I'm fine with everything. In this case, I'm just trying to implement what I've been told to, at least when I understand the request. 
I can even imagine that we decide to keep both a neutral button and a link, when it makes sense to have three actual choices for the user. 
I want it done, I don't care one way or another as long as I can push the code (and thanks a lot @oakkitten since in this case, I'm pushing your code).
In my ideal word, given that we want it done quickly, we'd merge this PR. If we want for some reason to be able to call it on an Alert Dialog that don't come from a builder, we'll split this function in two when requested. Or even we'd get anyone who cares do an extra PR, or just submit a commit on top of it, already provinding the feature.
And if for some reason we decided not to ever use it, when all is done and we are happy with the code to push to users, we can delete this function that seemed legitimately useful

2022-10-18 16:04 UTC, oakkitten commented
Just to explain my reasoning, I was thinking that we can introduce a thin API for creating dialogs, which could look something like this:

```kt
lifecycleScope.launch {
    val result = showOkCancelDialog {
        title(..)
        text(.., makeLinksClickable=true)
    }

    if (result == OkCancelDialog.Ok) ..
}
```
And this API could call through to `AlertDialog.makeLinksClickable()`. But all of this can be done later, of course.

Oh and by the way `Co-authored-by` needs an email to be properly recognized. You can use an email from other commits, or if you don't have that you can use the noreply email, both of which IIRC are recognized by GitHub. (You should be able to see the pfps of all users mentioned in this way on the left of the commit.) In my case that's the same e-mail:

    Co-authored-by: oakkitten <oakkitten@users.noreply.github.com>

2022-10-18 22:47 UTC, BrayanDSO commented
> Just an opinion, and not a very strong one; I like the way with the link as it separates non-action from actions. Also, it won't close the dialog, and I guess you'd expect the neutral button to close it. I also saw other apps do it this way and I liked how it felt. (On the screenshot above, Learn more button would sit roughly where the Learn more link sits now so it would also be separated. But this only works for very big screens/small UI elements. I prefer my display stuff big, so I'd probably see the three buttons in a vertical arrangement—not very separated.)

Very reasonable. Fine by me

2022-10-30 17:29 UTC, BrayanDSO requested changes

2022-10-30 17:29 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ScopedStorageMigrationDialog.kt
> +fun AlertDialog.Builder.addLearnMoreLinkAndShow(@Language("HTML") message: String): AlertDialog {
Can we not have this as an `AlertDialog.Builder` extension method? This is only useful for Scoped Storage

2022-10-30 20:34 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ScopedStorageMigrationDialog.kt
> +fun AlertDialog.Builder.addLearnMoreLinkAndShow(@Language("HTML") message: String): AlertDialog {
@BrayanDSO what is the concrete suggestion here? It appears it will be used in a couple locations - should it take an AlertDialog.Builder and return one? can you propose code for it ?

2022-10-30 20:35 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ScopedStorageMigrationDialog.kt
> +fun AlertDialog.Builder.addLearnMoreLinkAndShow(@Language("HTML") message: String): AlertDialog {
Here is one location it is used (it was peeled out from this PR I think - the PR just still has the commits in it)
https://github.com/ankidroid/Anki-Android/pull/12650/commits/2cf8d3f5693ee73c72286e940e98a965a5098774#diff-1c9f8440ee3813eda89e500bf5db95d90730eda462a22fb54b2d832e8fb06e2cR2771-R2783

2022-10-30 20:39 UTC, mikehardy commented
Marked #12650 as blocked by this (since it incorporates this work), so marked this as high priority
- needs conclusion on how to do the builder thing, feedback requested
- commits when rebased should get a proper coauthered commit message edit as mentioned by oakkitten

2022-10-30 21:09 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ScopedStorageMigrationDialog.kt
> +fun AlertDialog.Builder.addLearnMoreLinkAndShow(@Language("HTML") message: String): AlertDialog {
Just renaming it to `addScopedStorageLearnMoreLinkAndShow` should be fine I guess to keep speed here while not having a misleading generic name

2022-10-30 21:39 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ScopedStorageMigrationDialog.kt
> +fun AlertDialog.Builder.addLearnMoreLinkAndShow(@Language("HTML") message: String): AlertDialog {
I think this method is super weird and the "Learn more" belongs with the message, anyway.

But as long as methods with receivers are `private` I'm fine with them having non-generic code. (Kotlin is really nice but the decision to ditch package-private is just. Why)

2022-10-30 21:53 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ScopedStorageMigrationDialog.kt
> +fun AlertDialog.Builder.addLearnMoreLinkAndShow(@Language("HTML") message: String): AlertDialog {
thanks - going to go with `addScopedStorageLearnMoreLinkAndShow` and keep moving, can bikeshed later

2022-10-30 22:10 UTC, mikehardy approved these changes
I have made sure all comments are resolved, I checked it on API21 emu (by wiring it up to the trigger test crash button temporarily) and it works + has round corners now

![image](https://user-images.githubusercontent.com/782704/198903924-171fd4c8-ebf1-495f-8e22-0fca64ac9236.png)


I patched up the co-authored-by commit message as well.

Everything should be good to go

2022-10-30 22:20 UTC, oakkitten commented
😕

2022-10-30 22:21 UTC, mikehardy commented
@oakkitten don't post cryptic emoji please - make concrete suggestions, I will incorporate as rapidly as possible

2022-10-30 22:26 UTC, mikehardy commented
Related #12650 rebased over this one, the final commit is the only one that contains a real bit of new functionality, based on all these building blocks - it will be unblocked when this is done and I drop commits: https://github.com/ankidroid/Anki-Android/pull/12650/commits/70ce856b93d5025d5806cbb730236c196a0d8a83

2022-10-30 22:35 UTC, merged

2022-10-30 22:36 UTC, mikehardy commented
Any functionality here may be considered open for refactor at any time of course, please post follow-ons if motivated, but I want to get this chain of building blocks committed during the time I have available. Velocity is important here

2022-10-30 23:05 UTC, oakkitten commented
I mean,

* As I said above, "Learn more" belongs with the message
* `$message` should be on a new line, else why `trimIndent()`?
* This is not very readable, should've extracted to variables
  ```
               <br><a href='${context.getString(R.string.link_scoped_storage_faq)}'>${context.getString(R.string.scoped_storage_learn_more)}</a>
    ```
* The above line is 141 characters long
* I asked not to be mentioned in the file header (and my handle starts with a lowercase letter)
* Commit that adds `addScopedStorageLearnMoreLinkAndShow` belongs in #12650 not here. 
* `addScopedStorageLearnMoreLinkAndShow` is used once and should be inlined anyway. Here's the thing, it might seem to be a good idea but it's only good if you plan to do no refactoring at all. I'd be very surprised if this method stays after a sensible refactor. Inline now. Still think you need it? Add a commit that uses it (to #12650), extract the method, rebase. Now we can argue
* `AlertDialog.Builder.makeLinksClickable()` is a function with a lying name and should not exist anyway
* `AlertDialog.makeLinksClickable()` doesn't deserve its own PR in the first place

2022-10-30 23:18 UTC, mikehardy commented
Numbered points are easier so I can reference - edited

1- post PR refining please
2- I'm unsure what this means and don't have time to dig, please feel free to refine with PR
3- also perfect for refining PR
4- line length is farthest from a blocker, this PR was a blocker tho, refine in a PR if you like
5- I deeply apologize, I didn't realize I missed that, I was focused on your commit message comment and must have missed it, if you want to edit that out, obviously post a PR
6- 12650 had these extracted and all the work happened here, so I preferred to put this in here and drop commits there
7- refactor away, but after 12650 goes through - it should shortly
8- post concrete PR now that we have code to mash around. Code >>> PR Comments
9- with as many comments as this got, I disagree

Arthur's going to have connectivity again shortly and I don't want this stack still extent when that happens. I have this block of time and no more for days and days, so now this happened and we're moving forward. Sorry of it's rough

2022-10-30 23:42 UTC, oakkitten commented
I didn't review this because I just didn't think this was ready.

> with as many comments as this got, I disagree

That's the issue with PRs that shouldn't exist, they can generate a lot of comments. I mean, all of this is about one method. If it was in a well-refactored PR with things that actually use it, a large part of this conversation just wouldn't happen.

I understand the rush, but a merged piece of code doesn't bring us much closer to the goal than an unmerged one. At least in this case it isn't a block many a developer can start building upon. We still need more code. (Or should I say *less* code?)

2022-10-31 01:08 UTC, mikehardy commented
We may need slightly less or slightly different code but I needed to get the strings through also: #12759 - it's a pretty big "machine" this app, and the translators need to work as well. Code is actually fairly easy to mash around, and I assume it will be