Delete shared deck after import as asked for in #10663
ankidroid/Anki-Android pull request #12681
Opened 2022-10-16 19:10 UTC by humaneBicycle

## Pull Request template

## Purpose / Description
Completed a feature request as asked in 
Fixes #10663

## Fixes
Files now get deleted from `Android/data/com.ichi2.anki/files/Download`

## Approach
used the file URI to delete using the method in contentResolver after successful import.

## How Has This Been Tested?

Tested on Pixel 4 API 30 and Redmi 6 Pro API 27
The tested video is attached below.
[anki demo delete.webm](https://user-images.githubusercontent.com/41517932/196053405-b8b8b583-e577-4879-bc60-505c6f32e040.webm)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have performed a self-review of your own code
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-10-17 04:41 UTC, mikehardy requested changes
Hey! Thanks for posting this.
I left a couple suggestions, I don't think either of them really changes the nature of things - just a request for defensive programming and a trivial log level suggestion.
What do you think?

2022-10-17 04:41 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
> +                Timber.d("onCreate() import successful and cannot delete file $e")
:thinking: I am struggling here - I think it is more than a `Timber.d` since this is an unexpected situation and breaks the functionality. However, we recover from it - the app can keep on working, so it's not a `Timber.e`. It's either an `.i` or a `.w`. I think `.i` fits better for things that are expected and just good to know, this is unexpected and breaks the feature in this PR, so I suggest `.w`

```suggestion
                Timber.w("onCreate() import successful and cannot delete file $e")
```

2022-10-17 04:41 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
> +            val file = File(intent.data!!.path!!)
I always get nervous when I see `!!` - can you assert that in all cases every time the intent will have data that has a path? And it is never possible that it goes away asynchronously or anything?

You may be able to do that, but...it wouldn't hurt to just handle the nullability safely just in case would it? App crashes are terrible things, requiring a whole new release of the app to fix

2022-10-17 14:36 UTC, mikehardy requested changes
everything looks safe + functional now, just one more thought (apologies) on the file location being shared across a couple objects but with repeated logic vs central logic

2022-10-25 21:03 UTC, david-allison requested changes
LGTM. One nitpick

2022-10-25 21:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
> +                Timber.w("onCreate() import successful and cannot delete file $e")
```suggestion
                Timber.w(e, "onCreate() import successful and cannot delete file")
```

2022-10-26 15:55 UTC, david-allison approved these changes
LGTM, thanks!

2022-10-27 13:36 UTC, lukstbit commented on lint.gradle
> +android {
Please revert this change.

2022-10-27 13:51 UTC, lukstbit approved these changes

2022-10-27 13:57 UTC, merged