Replaces all usages of `MaterialDialog` with `AlertDialog` on preferences classes
ankidroid/Anki-Android pull request #12682
Opened 2022-10-16 19:17 UTC by BrayanDSO

## Pull Request template

## Purpose / Description

Pending knowing how not dismiss a dialog after tapping `OK` to keep the `ControlPreference` dialog flow in case someone cancels the replacement of an existing binding

## Fixes
Fixes #12669

## Approach
Replaces all usages of `MaterialDialog` with `AlertDialog` on preferences classes

And simplify `ControlPreference` utils a bit + use a snackbar with an undo button instead of a toast on the about screen (unrelated and I probably should remove that)

## How Has This Been Tested?

Untested

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-10-17 03:48 UTC, oakkitten commented
I think we could investigate rolling out our own tiny API for dialogs, similar to snackbar APIs, if only to guarantee that `show()` is called at the end.

Also, I mentioned it elsewhere, since we have quite a few places where dialogs open other dialogs, we could use coroutines to flatten the callbacks. Here's [one article](https://federicokt.medium.com/smarter-dialogs-with-coroutines-b83e1d0e06a0)

2022-10-17 03:51 UTC, mikehardy approved these changes
Just as a pre-emptive vote of confidence since I've been on record on the Material vs Alert dialog thing. I'll happily see the MaterialDialog dependency drop and the transformations in these commits look trivial. If all of the tech issues are solved, I think this is mostly a step sideways but also a bit of a step forwards and is worth it

2023-02-20 06:44 UTC, lukstbit commented
@BrayanDSO Fix one conflict, get an approve for free!

2023-02-20 10:50 UTC, BrayanDSO commented
I really like getting things for free 😁

2023-02-20 13:19 UTC, lukstbit requested changes
One small issue below.
Squash on merging?

2023-02-20 13:19 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
> +        AlertDialog.Builder(requireContext())
This dialog also needs a `show()` call.

2023-02-21 20:56 UTC, BrayanDSO commented
Squash, please

2023-02-21 21:42 UTC, david-allison approved these changes
Approve with one optional request. Implementer's choice

2023-02-21 21:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
> +                        setTitle(R.string.dialog_collection_path_not_dir)
Implementer's choice:
Consider using the Facade in this PR to avoid line noise `setTitle()` -> `title()` means an unchanged line on the diff

2023-02-21 21:51 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
> +                        setTitle(R.string.dialog_collection_path_not_dir)
Good point. Will do it if I need to upgrade other dialogs. For now, changing this PR would take me some minutes and wouldn't create any reward, so I'd rather spare me the work

2023-02-22 08:37 UTC, lukstbit approved these changes
Great!

2023-02-22 08:39 UTC, merged