Add an alert that there is not enough space for a full backup.
ankidroid/Anki-Android pull request #12684
Opened 2022-10-16 22:40 UTC by Arthur-Milchior

![2022-10-17-002808_262x471_scrot](https://user-images.githubusercontent.com/357361/196061855-10ffbe93-7e91-4c4d-8822-b953b2097a9b.png)

Also tested on my own device and got a result that seems correct, at a rounding error approximation

2022-10-17 04:55 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/export/Utils.kt
> +val nonMediaFile = listOf(
seems sort-of duplicate of this logic here

https://github.com/ankidroid/Anki-Android/blob/b0492e137448fe7fab4916e69e85580416429557/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFiles.kt#L410-L424

But that's kind of complex, perhaps just having a list is easier? Or perhaps this should be factored to build the list using the methods linked

2022-10-17 04:58 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/export/Utils.kt
> + * We are ignoring the space for meta data. Hoping that compression plus the [MIN_FREE_SPACE] is enough to count for it.
Combined with your test result I'm inclined to go with it for now. It's a little worrisome to use the word "hope", but removing it implies a desire for some thought on what a pathological case looks like for this estimator, then some testing to see if it breaks. That could be deferred to a follow-on issue/PR

2022-10-17 05:00 UTC, mikehardy commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="insufficient_space_dialog">A fall backup requires %1$d MB.\n\n You have %2$d MB free space. Please free space or use another way to backup.</string>
```suggestion
    <string name="insufficient_space_dialog">A full backup requires %1$d MB free space.\n\n You only have %2$d MB available. Please free up more space, or use another way to backup.</string>
```

2022-10-29 12:20 UTC, ShridharGoel commented
@Arthur-Milchior The screenshot shows that 10 MB is required and 6337 MB is available. So the error should not be shown, right?

2022-11-01 21:25 UTC, oakkitten requested changes

2022-11-01 21:25 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        val requiredSpaceInMB = spaceRequiredForFullExport(col) / 1024 / 1024
A megabyte is 1000 bytes

2022-11-01 21:25 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
> +        internal const val MIN_FREE_SPACE = 10
10 what? I suggest converting to bytes while we are at it. Also it is *extra* space, as in it's added to the size of a backup, the name should reflect that.

2022-11-01 21:25 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    fun insufficientSpaceDialog() {
`insufficientSpaceDialog` → `showInsufficientSpaceDialog()`

Also I suggest removing “Assumes that there is indeed not enough space. This is not checked.”

2022-11-01 21:25 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/export/Utils.kt
> +val nonMediaFile = listOf(
![image](https://user-images.githubusercontent.com/1710718/199341399-37f5b9c7-dc1d-44f1-b5c6-4575c02084b2.png)

2022-11-01 21:25 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/export/Utils.kt
> +fun spaceRequiredForFullExport(col: Collection): Long {
This is a slow operation and should be performed in a thread. Also it should be cancelable. And it should be `calculateSpaceRequiredForFullExport`

2022-11-01 21:25 UTC, oakkitten commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="insufficient_space_dialog">A fall backup requires %1$d MB.\n\n You have %2$d MB free space. Please free space or use another way to backup.</string>
`insufficient_space` → `dialogs__insufficient_space__title`
`insufficient_space_dialog` → `dialogs__insufficient_space__text`
Or something like that

2022-11-01 21:25 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/export/Utils.kt
> +val nonMediaFile = listOf(
Also rename `nonMediaFile` to something else, like `essentialFileNames`. Please use “file”/“directory” for `File` objects, “name” for what `File.name` gives, and “path” for full paths as `String`s

2022-11-01 21:25 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
> +    fun mediaInformation() =
I would inline this method, this doesn't need a name

2022-11-01 21:27 UTC, oakkitten commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="insufficient_space_dialog">A fall backup requires %1$d MB.\n\n You have %2$d MB free space. Please free space or use another way to backup.</string>
Also remove the space after `\n\n`

2022-11-02 23:33 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        val requiredSpaceInMB = spaceRequiredForFullExport(col) / 1024 / 1024
If we are getting technical, it is actually 1,000,000 bytes.

2022-11-02 23:33 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        val requiredSpaceInMB = spaceRequiredForFullExport(col) / 1024 / 1024
But yeah, the megabyte vs mebibyte concern is valid IMO.

2022-12-03 13:52 UTC, mikehardy commented
This one has a bunch of conflicts and unresolved feedback but seems important for scoped storage? So I tagged it as review high priority so it stays on my high priority queue scans
I don't think Arthur cares about anyone taking a PR and adding commits + fixing it up if anyone has time to get this thing across the finish line...

2023-01-15 21:15 UTC, Arthur-Milchior reviewed
What @oakkitten made me realize, is that we already know the space if we are able to warn that there is not enough. So this function should not compute free space in the first place. Hence, I remove all computation part and will put in other PR

2023-01-15 21:16 UTC, Arthur-Milchior commented
> @Arthur-Milchior The screenshot shows that 10 MB is required and 6337 MB is available. So the error should not be shown, right?

I beg your pardon, @ShridharGoel, I was unclear. The test was done by forcing this function to be run. There was no condition that the space is missing. Actually, this is not even in the code of this function.

2023-02-25 22:20 UTC, mikehardy commented
conflicts 😩

2023-02-25 22:21 UTC, mikehardy commented
@david-allison the related method on main appears to have gone away entirely, is this still functionality ?

2023-02-25 23:07 UTC, david-allison commented
Could be integrated into https://github.com/ankidroid/Anki-Android/pull/13316 (backup prompt). Up to @Arthur-Milchior.

2023-03-19 00:53 UTC, closed without merging