NF: remote toLong and toInt from equal assertions
ankidroid/Anki-Android pull request #12703
Opened 2022-10-19 16:18 UTC by Arthur-Milchior

Mostly fixes bug: #11965, except for examples such as https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt#L160 where, if you remove the toLong you get the error message:
> java.lang.AssertionError: expected: java.lang.Integer<20800301> but was: java.lang.Long<20800301>

2022-10-19 22:04 UTC, BrayanDSO requested changes
I believe that you mixed your branches by mistake

2022-10-19 22:04 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/attrs.xml
> +
unrelated

2022-10-19 22:04 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/anki/preferences/SettingsSearchBarTest.kt
> +//        val preferencesToIndexField = getJavaFieldAsAccessible(SearchConfiguration::class.java, "preferencesToIndex")
all changes on this file are unrelated

2022-11-04 04:47 UTC, Arthur-Milchior commented
strange. But you're totally right. I got something wrong here

2023-01-10 05:37 UTC, closed without merging