UI fixes and enhancements
ankidroid/Anki-Android pull request #12726
Opened 2022-10-24 19:08 UTC by Subhadiptech

UI fixes:
- The third text was not responsive as it had some horizontal bias of 0.0. I fixed it by removing the bias and adding horizontal constraints.

UI enhancements:I
- The line between Study Less and remember more has been added with a gradient to make it look better.

2022-10-25 05:33 UTC, lukstbit commented
Thank you for the contribution. 
I haven't checked the changes but does your code take in consideration the different themes we offer to the user(asking this because you added a hard coded color in the layouts)? Also we ask for PRs with changes to the UI that they provide some images showing the UI changes.

2022-10-25 06:13 UTC, Subhadiptech commented
I got it now, I will apply theme styles instead of hard code. Thanks for pointing it out.

2022-10-25 06:22 UTC, Subhadiptech commented
I am sharing the image of the changes made

2022-10-25 06:27 UTC, Subhadiptech commented
Before :

<img width="590" alt="Screenshot 2022-10-25 at 11 54 17 AM" src="https://user-images.githubusercontent.com/89024718/197698251-fdec89a5-25af-4c31-b188-d72d72f813f5.png">

After:

<img width="683" alt="Screenshot 2022-10-25 at 11 53 11 AM" src="https://user-images.githubusercontent.com/89024718/197698345-42677076-c017-4803-ba68-04f82f784186.png">

2022-10-25 12:43 UTC, lukstbit commented on AnkiDroid/src/main/res/drawable/gradient_line_horizontal.xml
> +        android:centerColor="#dddddd"
Extract this color to the end of colors.xml and name it as `intro_center_separator`

2022-10-25 12:43 UTC, lukstbit commented on AnkiDroid/src/main/res/drawable/gradient_line_horizontal.xml
> +        android:startColor="@color/white" />
In order to handle the different themes you could replace this hardcodded color with the attribute from the theme responsible for the background color: 

`?android:colorBackground`

2022-10-25 12:43 UTC, lukstbit commented on AnkiDroid/src/main/res/layout/introduction_layout.xml
> +        android:layout_width="160dp"
There is no need to make this wider, leave it as it is.

2022-10-25 12:43 UTC, lukstbit commented on AnkiDroid/src/main/res/layout/introduction_layout.xml
> +        android:background="@drawable/gradient_line_horizontal"
Rename the drawable file to `horizontal_gradient_separator`.

2022-10-25 14:19 UTC, Subhadiptech commented on AnkiDroid/src/main/res/layout/introduction_layout.xml
> +        android:layout_width="160dp"
As the line was previously a normal line, it was looking fine with 100dp, but as I added gradient and the start and end color are white, it required some more length for better look. Please Correct me if I was wrong. Thank you

2022-10-25 14:35 UTC, Subhadiptech commented
I am making the required changes. Thanks for the feedbacks @lukstbit

2022-10-25 20:05 UTC, Subhadiptech commented
I have made the required changed @lukstbit

2022-10-25 23:18 UTC, david-allison requested changes
LGTM. One nitpick

2022-10-25 23:18 UTC, david-allison commented on AnkiDroid/src/main/res/layout/homescreen.xml
> +
This seems like a no-op, could it be reverted?

2022-10-26 04:47 UTC, lukstbit approved these changes
Thanks!

2022-10-26 09:51 UTC, Subhadiptech commented on AnkiDroid/src/main/res/layout/homescreen.xml
> +
It was not changed by me @david-allison

2022-10-26 09:51 UTC, Subhadiptech commented on AnkiDroid/src/main/res/layout/homescreen.xml
> +
> The formatting right? @david-allison

2022-10-26 14:52 UTC, lukstbit commented on AnkiDroid/src/main/res/layout/homescreen.xml
> +
@Subhadiptech  Yes, the change is unrelated to the other changes.

2022-10-26 17:42 UTC, Subhadiptech commented on AnkiDroid/src/main/res/layout/homescreen.xml
> +
Sure, I will revert

2022-10-27 17:43 UTC, Subhadiptech commented
I have reverted the un wanted changes. @david-allison  @lukstbit

2022-10-29 09:39 UTC, Subhadiptech commented
> LGTM. One nitpick

It's updated

2022-10-30 23:09 UTC, mikehardy approved these changes
All comments appear to be handled

2022-10-30 23:10 UTC, merged

2022-10-30 23:10 UTC, mikehardy commented
First PR merged! Congratulations :smile:

2022-10-31 11:10 UTC, Subhadiptech commented
Thanks 🙏