toast replaced with snackbar
ankidroid/Anki-Android pull request #12732
Opened 2022-10-26 19:13 UTC by criticalAY

## Purpose / Description
toast replacement

## Checklist
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-10-26 19:15 UTC, criticalAY commented
` @KotlinCleanup("check RTL with concat")` is this needed there now because the toast is gone ?

2022-10-26 20:47 UTC, BrayanDSO requested changes
Tests fail

2022-10-26 20:47 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> -            @KotlinCleanup("check RTL with concat")
keep the cleanup. It is about if the string is concatened correctly on RTL languages.

2022-10-26 20:47 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +            showSnackbar(resources.getString(R.string.no_browser_notification) + url, Snackbar.LENGTH_LONG)
I'd extract `resources.getString(R.string.no_browser_notification) + url` into a variable to make this more readable. `noBrowserMessage` seems good to me

2022-10-27 02:52 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> -            @KotlinCleanup("check RTL with concat")
cool

2022-10-27 04:16 UTC, criticalAY commented
`java.lang.IllegalArgumentException: While trying to show a snackbar, could not find a view with id root_layout in com.ichi2.anki.dialogs.utils.FragmentTestActivity@292bfa01` the test error is caused by this but what to pass there ? It is working fine

2022-11-21 15:11 UTC, criticalAY commented
@BrayanDSO I am reverting the code and removing the annotation for the cleanup as there is no root layout to attach the snackbar. So its better to keep the toast instead

2022-11-21 16:18 UTC, BrayanDSO commented
Have you tested this piece of code on a real device? 

I believe that the only issue with this is the unit tests, which should be fixed instead of just removing the TODO. Perhaps by using a CoordinatorLayout somewhere

2022-11-21 16:20 UTC, BrayanDSO commented
> I have tested it and it worked fine but the test failed because of the layout issue

It may be tough, but the path here is to fix the test

2022-11-21 16:21 UTC, criticalAY commented
For that we need to locate the test file could you help me with that I would like to give it a try

2022-12-03 15:07 UTC, criticalAY commented
I forced push back then and ended up here will try to get it fixed because this PR is of less relevance because there needs to be some edits in test case for this snackbar to pass the tests. But surely try fixing it and I will keep rebasing in mind in the future for sure

2022-12-11 13:12 UTC, criticalAY commented
I have corrected this PR but would like to know how to fix the tests @BrayanDSO because it is working fine at my end doesn't seems to be an issue

2022-12-11 13:16 UTC, criticalAY commented
![Screenshot_13](https://user-images.githubusercontent.com/48384865/206905894-e4aa1a3e-e945-41cc-91cf-0dde4e2e13d0.png)

2022-12-11 16:46 UTC, mikehardy commented
@criticalAY please learn how to rebase and rebase. The commit history here is not good

2022-12-11 17:41 UTC, criticalAY commented
> @criticalAY please learn how to rebase and rebase. The commit history here is not good

done Mike

2022-12-11 17:43 UTC, criticalAY commented
Mike is there a way to drop multiple commits in one go I had to place a d before I guess 50 commits to clean this branch

2022-12-11 18:42 UTC, mikehardy commented
Once you've done a "merge" it's difficult. I suggest pulling the actual commits that do things you are interested in doing, in this PR, off to the side (git reset --soft HEAD~'some number' can probably do that followed by git stash)

Once you are *sure* you have the changes you actually want, that you intend for this PR, stashed, then git reset --hard upstream/main to just purge your local branch state. Then git stash pop, git commit your changes as a single nice commit, and push --force-with-lease

But, there are lots of ways to do it. End goal is to just have the actual textual changes that implement whatever you implementing as a nice single commit, as opposed to a trail of like 20 with 3 of them being merges - those are impossible to follow along with, as a reviewer

2022-12-11 19:58 UTC, criticalAY commented
```
    fun testNormalStartupSelectingItem() {
        val linkedItem = getItemLinkingTo(R.string.link_manual)
        val v = getRecyclerViewFor(linkedItem)
        clickChildAtIndex(v, 0)
        MatcherAssert.assertThat(activity!!.lastUrlOpened, Matchers.equalTo(getResourceString(R.string.link_manual)))
    }
```

There is this test function I would like to know if we really need the `!!` here can be prefer `?`

2022-12-11 21:00 UTC, BrayanDSO commented
I'd try setting a layout with a `CoordinatorLayout` on `FragmentTestActivity.kt`

2022-12-11 21:37 UTC, criticalAY commented
> I'd try setting a layout with a `CoordinatorLayout` on `FragmentTestActivity.kt`

```
val coordinatorLayout = findViewById<CoordinatorLayout>(R.id.coordinator_layout)
 assertNotNull(coordinatorLayout)
```

something like this?

2022-12-11 22:34 UTC, criticalAY commented
@BrayanDSO The tests passed when added the layout I have added the DeckPicker layout right now but can we consider creating a new layout because I am not sure if the current commit is a best practice

2023-02-16 23:36 UTC, closed without merging