kotlin code cleanup
ankidroid/Anki-Android pull request #12735
Opened 2022-10-27 09:56 UTC by criticalAY

Code cleanup

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-10-29 12:38 UTC, ShridharGoel requested changes

2022-10-29 12:38 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        val newFragment: AsyncDialogFragment = SimpleMessageDialog.newInstance(title, message!!, reload)
This isn't the correct way. The type of function parameter `method` should be changed to `String`.

2022-10-29 14:40 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        val newFragment: AsyncDialogFragment = SimpleMessageDialog.newInstance(title, message!!, reload)
that is already `String` ?

2022-10-29 14:43 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        val newFragment: AsyncDialogFragment = SimpleMessageDialog.newInstance(title, message!!, reload)
you mean `String?` should be converted to `String` in the parameters? If so then my misunderstanding I though it should be passed as non null

2022-10-29 16:38 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        val newFragment: AsyncDialogFragment = SimpleMessageDialog.newInstance(title, message!!, reload)
Correct, parameter should be changed to non-nullable type.

2022-10-29 16:40 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        val newFragment: AsyncDialogFragment = SimpleMessageDialog.newInstance(title, message!!, reload)
that gives an error while compiling

2022-10-31 11:14 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        val newFragment: AsyncDialogFragment = SimpleMessageDialog.newInstance(title, message!!, reload)
Yeah, obviously it will require consideration at the places from where the method is being called.

2022-10-31 14:46 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        val newFragment: AsyncDialogFragment = SimpleMessageDialog.newInstance(title, message!!, reload)
There are a lot of places we need to remove the `?` assertion if we remove just one and there are places where we require the `?` assertion

2022-10-31 14:56 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        val newFragment: AsyncDialogFragment = SimpleMessageDialog.newInstance(title, message!!, reload)
It will only need changes at 2 places out of the places where it is being called. Apart from that, you need to update the overridden method as well.

2022-10-31 14:57 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        val newFragment: AsyncDialogFragment = SimpleMessageDialog.newInstance(title, message!!, reload)
Most of the calls to the method are already passing non-nullable string for message.

2022-10-31 16:03 UTC, ShridharGoel commented
Yes, but not all places need the change.

सोम, 31 अक्तू॰ 2022, 21:10 को Ashish Yadav ***@***.***> ने
लिखा:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> <https://github.com/ankidroid/Anki-Android/pull/12735#discussion_r1009568963>
> :
>
> >      open fun showSimpleMessageDialog(message: String?, title: String = "", reload: Boolean = false) {
> -        val newFragment: AsyncDialogFragment = SimpleMessageDialog.newInstance(title, message, reload)
> +        val newFragment: AsyncDialogFragment = SimpleMessageDialog.newInstance(title, message!!, reload)
>
> it is being called are many places more than 10 I guess
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ankidroid/Anki-Android/pull/12735#discussion_r1009568963>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIPLJHCYWWGJR6UZQXJH6HTWF7SAVANCNFSM6AAAAAARP36ZYY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-10-31 18:57 UTC, ShridharGoel requested changes

2022-10-31 18:57 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
> -                            message = getHumanReadableLoginErrorMessage(result[0] as Exception),
I'll suggest using `getHumanReadableLoginErrorMessage(result[0] as Exception) ?: ""`

2022-10-31 18:57 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        val newFragment: AsyncDialogFragment = SimpleMessageDialog.newInstance(title, message!!, reload)
Yes, but not all places need the change.

2022-10-31 19:18 UTC, criticalAY commented
So we basically replaced it with empty string just in case

2022-10-31 19:41 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +                .setContentText(message ?: "")
Could you explain this change please?

2022-10-31 19:41 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            if (isEmpty(getCurrentFieldText(0))) {
This should be `getCurrentFieldText(0).isEmpty()` no?

2022-10-31 19:41 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.kt
> +                response.body?.close()
Why not follow annotation advice?

2022-10-31 19:41 UTC, oakkitten commented on api/src/test/java/com/ichi2/anki/api/ApiUtilsTest.kt
> +        val set = mutableSetOf<String?>()
Use `setOf(...)`, rename method, its name is wrong

2022-10-31 19:47 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            if (isEmpty(getCurrentFieldText(0))) {
`TextUtils` is a redundant qualifier here so can be removed and `isEmpty `can be used directly

2022-10-31 19:50 UTC, criticalAY commented on api/src/test/java/com/ichi2/anki/api/ApiUtilsTest.kt
> +        val set = mutableSetOf<String?>()
I did get this one sorry

2022-10-31 19:51 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +                .setContentText(message ?: "")
Ahmm true isn't really necessary I did that change when I did a wrong change earlier

2022-10-31 19:55 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.kt
> +                response.body?.close()
`response?` in here `?` isn't really necessary because that would be a add on which can be replaced with dot call

2022-10-31 19:58 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            if (isEmpty(getCurrentFieldText(0))) {
I suggest not using `TextUtils.isEmpty` at all.

2022-10-31 19:59 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.kt
> +                response.body?.close()
The advice was to replace the entire `if (response?.body != null) { response.body!!.close() }` with `response?.body?.close()`

2022-10-31 20:00 UTC, oakkitten commented on api/src/test/java/com/ichi2/anki/api/ApiUtilsTest.kt
> +        val set = mutableSetOf<String?>()
Just say `val tags = setOf("A", "B", "C")`. And the method says "empty string" and there are no empty strings here

2022-10-31 20:03 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.kt
> +                response.body?.close()
further simplification sure

2022-11-01 05:09 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +                ticker = message!!
This hasn't been resolved, what I meant was - The argument should be non-null (String instead of String?).

2022-11-01 05:40 UTC, criticalAY commented
Have done all the changes now

2022-11-01 14:00 UTC, oakkitten requested changes

2022-11-01 14:22 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        message: String,
sure waiting for the response

2022-11-01 14:38 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
>              val undoIcon = undoName(resources).let {
renaming `undoName` ? you mean

2022-11-01 14:41 UTC, criticalAY commented on api/src/test/java/com/ichi2/anki/api/ApiUtilsTest.kt
> +import kotlin.collections.HashSet
val `fieldName` is useless then ?

2022-11-01 14:42 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    open val backupManager: BackupManager
I thought here we are talking about the assertion

2022-11-01 20:11 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
>              val undoIcon = undoName(resources).let {
Never mind, this is better left for another PR

2022-11-01 20:14 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    open val backupManager: BackupManager
I mean, you can probably remove the whole variable

2022-11-01 20:16 UTC, oakkitten commented on api/src/test/java/com/ichi2/anki/api/ApiUtilsTest.kt
> +import kotlin.collections.HashSet
Uh, I meant to do this where `HashSet` is used

2022-11-03 02:20 UTC, criticalAY commented on api/src/test/java/com/ichi2/anki/api/ApiUtilsTest.kt
> +import kotlin.collections.HashSet
ok

2022-11-03 02:23 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        message: String,
Now only this edit is left to resolve

2022-11-03 16:34 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    open val backupManager: BackupManager
So.. is this used anywhere?

2022-11-03 16:46 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    open val backupManager: BackupManager
nope we  can remove the two lines

2022-11-03 17:09 UTC, criticalAY commented
Done!

2022-11-04 01:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        message: String,
At the time, I believed (and still believe) that all of the 'sync' code was using a non-null message, but I didn't have the time to work through the logic to 100% confirm it. The pervasive nullable annotation was unnecessary and it would be better to make this and the rest of the sync code return a non-null message.

I don't feel `?: ""`. is the correct solution. 

I don't believe a nullable parameter is a use case we need to support with our current codebase and I'd prefer to move to a state where our sync code returns a non-null value. But for the ease of the review & moving the code forward, I'd be happy to allow the value to be null as long as it's properly handled. 

----

Additional context: At the time, the usage of `null` around this class was also a risk (we were in the early days of the Kotlin version of `MaterialDialog`):

`AsyncDialogFragment` was written before my time. It is either a `MaterialDialog` or a notification.

A `MaterialDialog` accepts a `String?` for `content`/`title`, but throws an exception if this `String?` is null:

```
    java.lang.IllegalArgumentException: title: You must specify a resource ID or literal value
        at com.afollestad.materialdialogs.utils.MDUtil.assertOneSet(MDUtil.kt:351)
        at com.afollestad.materialdialogs.MaterialDialog.title(MaterialDialog.kt:151)
        at com.afollestad.materialdialogs.MaterialDialog.title$default(MaterialDialog.kt:149)
        at com.ichi2.anki.dialogs.IntegerDialog.onCreateDialog(IntegerDialog.kt:51)
        at com.ichi2.anki.dialogs.IntegerDialog.onCreateDialog(IntegerDialog.kt:31)
```

2022-11-06 09:32 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        message: String,
so the commit was fine? and do we need to revert `?: ""`

2022-11-06 12:09 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        message: String,
This method, `showSimpleNotification`, is about notifications and I believe notifications API allow `null`s.

A method above, `showSimpleMessageDialog`, is about dialogs, and while `MaterialDialog.message` will indeed crash if a `null` value is passed to it (ugh), `showSimpleMessageDialog` seems to be properly handling `null` message values by not calling `MaterialDialog.message` with `null`s.

I would suggest keeping the nullability for now.

2022-11-06 14:45 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        message: String,
Ok so I am reverting it back to the way it was

2022-11-06 14:56 UTC, criticalAY commented
I guess someone else already fixed one part as there is a conflict

2022-11-06 15:20 UTC, criticalAY commented
I didn't touch `DeckPickerCheckDatabaseListenerTest` file but it is coming in the conflicts and also the test are failing due to it

2022-11-06 16:11 UTC, criticalAY commented
Have done the changes now

2022-11-07 06:21 UTC, david-allison approved these changes
Wonderful, thanks!

2022-11-07 06:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        )
so much nicer

2022-11-07 17:29 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +    open fun showSimpleMessageDialog(message: String, title: String = "", reload: Boolean = false) {
I still think that this method should accept nullable `message`. `SimpleMessageDialog` is explicitly handling `null` `message`s.

2022-11-07 17:30 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
>      @KotlinCleanup("make non-null")
If we decided to keep nullable `message` here, I guess we can remove the annotation. (And probably keep the empty line above)

2022-11-07 17:51 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +    open fun showSimpleMessageDialog(message: String, title: String = "", reload: Boolean = false) {
I also think that because it is safer to use but is the message ever going to be null ?

2022-11-07 18:08 UTC, criticalAY commented
now we are good to go, ready to merge

2022-11-07 19:34 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
>      @KotlinCleanup("make non-null")
I'm sorry but the annotation is still here

2022-11-07 19:45 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
>      @KotlinCleanup("make non-null")
ops Sorry

2022-11-07 19:46 UTC, criticalAY commented
DONE! finally

2022-11-07 20:15 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        showSimpleMessageDialog(title = title, message = message ?: "", reload = true)
Uhh.. Just noticed, since `message` argument is nullable we better avoid `?: ""`

2022-11-07 20:15 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
> +                            message = getHumanReadableLoginErrorMessage(result[0] as Exception) ?: "",
And here as well I guess

2022-11-07 20:17 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        showSimpleMessageDialog(title = title, message = message ?: "", reload = true)
yeah true true I forgot that

2022-11-07 21:01 UTC, oakkitten approved these changes
This was a long journey. I think we are there at last!

2022-11-07 21:13 UTC, criticalAY commented
> This was a long journey. I think we are there at last!

Yes I learned to force push and resolve conflicts hehehe but Thanks!

2022-11-09 21:02 UTC, mikehardy approved these changes
Nice!

2022-11-09 21:03 UTC, merged