[GSoC] Global notification
ankidroid/Anki-Android pull request #12766
Opened 2022-10-31 18:15 UTC by prateek-singh-3212

## Pull Request template

## Purpose / Description
Implements the Global notification.

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-10-31 18:18 UTC, prateek-singh-3212 commented
The UI is under construction. I will share it in a while

2022-10-31 19:28 UTC, oakkitten commented
Why handle time zone manually? `AlarmManager` should handle that for you.

Also, my concerns from #12635 are still not addressed

2022-10-31 19:32 UTC, prateek-singh-3212 commented
> Why handle time zone manually? AlarmManager should handle that for you.

We are not using the alarm manager to schedule notifications. We are using work manager that's why I handled it manually.
Regarding changes: I will make all the required changes but this PR is slightly different from that one as it focus only on all deck notification (Global notification)

2022-10-31 19:43 UTC, oakkitten commented
Yes, I understand that you are using work manager, my question is why. It seems to me that alarm manager is a better tool for the job.

2022-11-01 04:38 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +    constructor() : this(
Have you created this for setting default values? It can be done directly like this `val enabled: Boolean = true`.

2022-11-01 04:38 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +    constructor() : this(
Same.

2022-11-01 04:44 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        CoroutineScope(Dispatchers.Default).launch {
Would be good to inject dispatcher, since currently we don't have dependency injection set-up - you can add dispatcher as an argument in the class and set default values. 

Add in constructor like this: `private val defaultDispatcher: CoroutineDispatcher  = Dispatchers.Default`
Then, you can use `defaultDispatcher` instead of `Dispatchers.Default` here.

https://developer.android.com/kotlin/coroutines/coroutines-best-practices#inject-dispatchers

2022-11-01 04:45 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        CoroutineScope(Dispatchers.Default).launch {
Would be good to inject dispatcher. Since currently we don't have a dependency injection setup, you can add dispatcher as an argument in the class and set default values.

Add in constructor like this: private val defaultDispatcher: CoroutineDispatcher = Dispatchers.Default
Then, you can use defaultDispatcher instead of Dispatchers.Default here.

https://developer.android.com/kotlin/coroutines/coroutines-best-practices#inject-dispatchers

2022-11-01 04:48 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +            totalDueCount.addLrn(it.lrnCount)
`apply` can be used.

2022-11-01 04:50 UTC, ShridharGoel commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="all_deck_notification_new_title">You have card due</string>
Consider changing this text to be based on singular/plural values as well.

It can be either "You have a card due" or "You have some cards due".

2022-11-01 06:37 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +    constructor() : this(
No, Actually It is required by Jackson to serialize the data.

2022-11-01 06:38 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +    constructor() : this(
Discussed above.

2022-11-01 14:03 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +            totalDueCount.addLrn(it.lrnCount)
Or just use the constructor?..

2022-11-01 17:13 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +            totalDueCount.addLrn(it.lrnCount)
Used apply here.

2022-11-01 17:25 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="all_deck_notification_new_title">You have card due</string>
Done, Thanks

2022-11-01 20:52 UTC, prateek-singh-3212 commented
> Yes, I understand that you are using work manager, my question is why. It seems to me that alarm manager is a better tool for the job.

We tried to use the alarm manager to trigger the notification. but the thing is when we schedule the single deck notofication then we are not able to manage it efficiently. (this pr does not contains the single deck notification implementation it will come in future) 

we had a good discussion and concluded that we are going to use work manager.
for discussion you can check PR

2022-11-01 20:52 UTC, prateek-singh-3212 commented
> Yes, I understand that you are using work manager, my question is why. It seems to me that alarm manager is a better tool for the job.

We tried to use the alarm manager to trigger the notification. but the thing is when we schedule the single deck notofication then we are not able to manage it efficiently. (this pr does not contains the single deck notification implementation it will come in future) 

we had a good discussion and concluded that we are going to use work manager.
for discussion you can check PR

2022-11-01 21:56 UTC, oakkitten commented
It took my computer 15 minutes to load that page, and I still couldn't find the discussion about `AlarmManager`. Could you link to specific comments please?

2022-11-02 13:50 UTC, prateek-singh-3212 commented
Sure, See: Discussion after this comment https://github.com/ankidroid/Anki-Android/pull/11487#issuecomment-1166347895

There is discussion on discord also.

2022-11-02 15:15 UTC, oakkitten commented
I looked there and clicked through some links and I still can't find the discussion about `AlarmManager` on GitHub. On discord, there's like 3 mentions of it but no arguments for or against it.

I also see the discussion about [storing configuration](https://github.com/ankidroid/Anki-Android/pull/11487#discussion_r889411954). I can't see the code (I think?) but correct me if I'm wrong here. You only need to store deck ID and time of the notification. If you don't do stuff like serializing classes, you can get away with as little as 10 bytes per deck. Also, there is no way that anyone is going to be configuring individual notifications for every deck, so even if there are 1000's of decks you will only have to store the times for a few of them. So in a realistic scenario you will only have to store some 30-90 bytes. So I have to ask what exactly was the issue with using shared preferences?

2022-11-02 15:39 UTC, mikehardy commented
> Also, there is no way that anyone is going to be configuring individual notifications for every deck

I have learned to never make assumptions about the behavior of people using Anki, with regard to rational expectations of potentially unbounded data sizes

2022-11-02 16:23 UTC, oakkitten commented
The OOM crash happened when [committing to memory](https://github.com/ankidroid/Anki-Android/pull/11487#discussion_r889667710) and while I can't see the code it might be that you would have to do this (commit to memory) anyway, manually, to fix the current issue with the race condition in the data store. Or always use the data store asynchronously, the way I think it is meant to be used. Or try to optimize the way you store it...

2022-11-02 22:03 UTC, Arthur-Milchior commented
@prateek-singh-3212 I'll start reviewing now.
Can you please fill the PR template. At the very least, if you do not fill it, then delete every parts that are not relevant. Because right now, we have to read the basic template to check whether there is anything relevant.
Given the complexity of the new behavior, knowing how we can test it seems extremely relevant. As you mention yourself, some parts are missing to be able to use the current notification system, so we would really need to have a list of what is present and what is still TODO. Otherwise I feel like we can't honestly review it. We can look at the code you wrote, but we can't know if we agree with you that this is good code, as we don't even know exactly what this code is supposed to do.

I'd really love to see the UI added to it, so that I can actually test it easily on my device

2022-11-02 23:59 UTC, Arthur-Milchior reviewed
Thank you very much for a PR that does just the one thing we asked to start with, global notification.

I feel like I'm repeating myself, but I still would love that you write more text. Your code is generally good, but it's hard to review because your PR has no details, your commit messages are extremely short, sometime a single line, even in commits doing a lot of work. Which means that it's very hard for me to review what you are doing, as I don't know what you intend to do, and I can't check whether the code you wrote is actually the code you intended to wrote.

Right now, unless somebody object, I really would want to keep the legacy notification. I don't want people that tests our alphas to not be able to still use it if they want it. Even if your new notification works, it's clearly not entirely done yet, and it's not a proper replacement.

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        val initialDiff = triggerTime - TimeManager.time.intTimeMS()
Would be nice to call it `initialDelay`. Would be consistent with Timber and with the parameter of the function where it's use. Diff is more vague than delay

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    private fun hourMinuteTimestampToday(hourOfDay: Int, minutesOfHour: Int) =
I'd call it `timestampOfTodayAtGivenHourAndMinute`. It's long, but it would be far clearer I believe.

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * While scheduling the notification we saves the data in datastore So, Data in datastore will be always fresh.
A point before `So` if it's a new sentence. And maybe "the data in the datastore"

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * Recreates the deck time map.
Unless I misundestand something, there is no map anymore. There is a single time for the unique global notification. If so, please change the comment

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * true: @see [ExistingWorkPolicy.REPLACE], false: @see [ExistingWorkPolicy.KEEP]
I'd love a comment explaining in which case you expect this function to be called with true or false for force. 
If we really need this parameter, I wonder we should not just take a `ExistingWorkPolicy` parameter instead. At least, it'll be directly clear while reading the function call what the argument means

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * Triggers the notification immediately.
> Triggers the notification immediately if notification is enabled.

otherwise the first sentence is just false, if the notification is sometime not actually triggered.

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        // Check notification is enabled or not.
> Check whether the notification is enabled

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * Builds the notification that is going to trigger.
I don't understand "that is going to trigger". I don't believe the notification will trigger anything.
I guess, maybe, we want 

> A notification, according to the given parameters

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +
In the commit "Implemented Timezone Change broadcast receiver & Calibrated notificat" please avoid adding this line. It add noises and does not seems relevant here

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> + * Broadcast receiver to listen timezone change of user.
> Broadcast receiver to listen to when a user changes their timezone.

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +         * Key to access user's Time Zone from datastore.
> Datastore key for the Timezone id. See [TimeZone.getTimeZone]

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +         * Get current time according the timezone of user.
It seems to me you are getting the current time according to the time zone with id [zoneID]. Nothing here guarantees that it's the time zone of the user. So the first line is not correct

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +            // Trigger time will come in future...
> Too soon to trigger.

That comment would explain why you return immediately. Current comment is true but don't explain the code nearby

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> -        // TODO: Build & Fire all deck notification.
"global notification". Otherwise, it's ambiguous whether you mean the notification for "all decks" or "all the deck notifications"

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +        // Creates an explicit intent for an DeckPiker Activity.
No need to state it "creates" or that it "build" (below). It does not seem to add information. Just commenting the content of the values is enough.
Also "A DeckPicker" with a c.

> An intent to open the deck picker, to use when the user tap on the notification

would probably helps more explaining what is going around

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +                totalDueCount.count()
I'd be in favor of putting this count in a value. Because you use it thrice. It's not expensive to compute, still, seems cleaner

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +        }
I feel like this part of the code is long enough to be worth being its own function. You can still call it from here. 
`onCreate` is still far far tool long, should really be refactored. But at least, let's not make the problem worse

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/10-preferences.xml
> -    <string name="never_notify">Never notify</string>
I'd prefer that we keep the old notification system, and so all old strings, until we really are ready to launch the new system. People may want to keep using current notification while still testing alphas.

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +                    true
Since I want you to keep old notification system, you should move current code from `initSubscreen` in a function `initLegacyNotificationSubscreen`. And put all of your new code in `initNewNotificationSubscreen`. Then `initSubscreen` could call both functions..

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +        val notificationDatastore = NotificationDatastore.getInstance(requireContext())
Please, create real commit message. Not just a title. "Implemented Global Notification preference screen." is a big commit doing really non trivial changes. Explain to the reader what is going to occur in the commit you created. 

Right now, this commit is asking me to read everything to understand exactly what you are doing. Which means that I may be able to say that it "looks good to me". But I'm not able to state whether this commit is actually doing what you want it to do, and that's the really important question.
I can't even know whether we all agree that's the proper settings, because you did not provide screenshot in the PR, and did not explain in the PR or in the commit message what is the new behavior.

2022-11-02 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/xml/preferences_notifications.xml
> -    <ListPreference
I think actually we should not remove the legacy preferences because right now, the user has no way to deactivate them. So if a user has the legacy notification systems activated, they could not deactivate it anymore.

2022-11-03 00:09 UTC, Arthur-Milchior commented
> I also see the discussion about [storing configuration](https://github.com/ankidroid/Anki-Android/pull/11487#discussion_r889411954). I can't see the code (I think?) .....

Right now, @david-allison and myself, as mentor for GSoC, asked @prateek-singh-3212 to do a single thing: a global notification, that just show a notification if there is any card to review. So we can concentrate on a single behavior. So I believe that this remark, @oakkitten, even if relevant in absolute, are to be kept for another PR when we work on more fine grained notification.


@prateek-singh-3212, since the remarks related to AlarmManager seems to be hard to find, be it on Discord or various other discussion, it would be nice if you could recap everything that you know that explains why it does not work. A quick look seems to indicate that @oakkitten is right and AlarmManager would seems appropriate.

2022-11-03 00:31 UTC, david-allison requested changes
Thanks! Primarily UX tweaks. 

I'll check with Arthur if we want this to replace the old mechanism over Discord

Personally, I feel that the functionality is already better than what previously existed, and we can replace it.

2022-11-03 00:31 UTC, david-allison commented on AnkiDroid/src/main/res/values/10-preferences.xml
> -    <string name="never_notify">Never notify</string>
IMO, this PR should replace the old notification system with the new notification system

2022-11-03 00:31 UTC, david-allison commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="notification_preference_global_notification" maxLength="41">Global Notification</string>
```suggestion
    <string name="notification_preference_global_notification" maxLength="41">Daily reminder notification</string>
```

2022-11-03 00:31 UTC, david-allison commented on AnkiDroid/src/main/res/xml/preferences_notifications.xml
> +        android:defaultValue="true"
Notifications should default to 'off'

2022-11-03 00:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +                "${data.notificationTime.hour}:${data.notificationTime.minutes}"
This formats '0' minutes as '7:0' rather than '7:00'

2022-11-03 00:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +                "${data.notificationTime.hour}:${data.notificationTime.minutes}"
This doesn't correctly handle internationalisation as it uses string concatenation

2022-11-03 00:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        setAutoCancel(true)
What should tapping on a notification do? Right now it opens the deck picker, even if I only have one deck with one card pending

2022-11-03 00:31 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    </plurals>
The message that we provide is going to be seen by the user every day. We should spend some time proposing alternatives.

<img width="397" alt="Screenshot 2022-11-03 at 00 19 42" src="https://user-images.githubusercontent.com/62114487/199626546-e670a033-e3bd-4c10-bf6a-378eb254da79.png">

2022-11-03 00:31 UTC, david-allison commented on AnkiDroid/src/main/res/xml/preferences_notifications.xml
> +        android:title="@string/notification_preference_global_notification" />
This could do with a 'summary' attribute which briefly explains the feature in a little more detail

2022-11-03 00:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +import com.fasterxml.jackson.databind.ObjectMapper
@oakkitten noted in #12635 

> I think this is way too simple to serialize.
> 
> Serialization is fine for possibly complex objects such as encryption keys, or for objects that aren't supposed to be long-lived. Serialization is nice until you need to change how you store your data, or until some weird thing changes and you can't deserialize. For preferences, especially in such simple cases like this, I'd strongly prefer something more manual. E.g. just encode all of enabled decks and their times in a string.
> 
> Also, why jackson istead of kotlinx.serialization?

And that seems even more relevant now, when we are just keeping a very simple information about a single notification.
Since we probably will always use hours, and potentially minutes, I love storing hour/minute of global notification directly. While serializing will indeed be an issue if we eventially want to store more or less data

2022-11-03 00:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +            remindAtPreference.summary =
@oakkitten noted that we should not even hard code text for hours and minutes. I clearly agree. Please use string ressource.

2022-11-03 00:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +                remindAtPreference.summary = "$hour:$minutes"
@oakkitten noted that we should not even hard code text for hours and minutes. I clearly agree. Please use string ressource.

2022-11-03 00:52 UTC, Arthur-Milchior commented
After discord discussion with @david-allison and @mikehardy , I reverse my remarks regarding the legacy notification system. Remove it entirely.
My only request would be that you remove it in a separate commit. Or even a separate PR. The commit that adds the new preference is already complex enough that I'd love to be able to not mix removing old code and seeing new one

2022-11-03 05:05 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    </plurals>
By alternative, do you mean that we should devise multiple messages and alternate between day from one day to the next? Or that we should brainstorm alternative messages in this PR to select one in the end?

2022-11-03 05:20 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/xml/preference_headers.xml
> -        android:key="@string/pref_notifications_screen_key"
@BrayanDSO, could you please let us know why this key is here. Searching online, I fail to understand the point of this key, but I'll [Chesterton's Fence](https://fs.blog/chestertons-fence/#:~:text=Do%20not%20remove%20a%20fence,during%20a%20fit%20of%20madness.) it and wait until I know if there is a reason for us to use it before I accept to remove it. 

In particular, given your work, I can imagine that it's actually used to search for preferences. And I can also imagine that it's just used out of habits, because it does not break anything and nobody objected during review

2022-11-03 05:24 UTC, Arthur-Milchior commented
![2022-11-03-062217_281x48_scrot](https://user-images.githubusercontent.com/357361/199652679-1f85486d-2ce6-41b2-b873-a516ef41ae3c.png)

In the preferences, I see the subtitle of "notification" is "Notify when". We should probably also correct this. Probably creating a new string, different than "notification_pref_title", because it may already be translated.
At least, I assume we don't want this actual subtitle, because it seems like a start of sentence that is cut too short. There is not even some ... that would at least indicates a missing suffix

2022-11-03 05:27 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/10-preferences.xml
> -    <string name="notification_minimum_cards_due_vibrate" maxLength="41">Vibrate</string>
As far as I'm concerned, one other trouble with removing current notification system is that we are removing strings such as this one. And I can imagine we still want to let user decide whether their device vibrate or blink light (I can also imagine we don't). And intuitively, it seems like removing the string to add it is a bad idea. At least we have not tested it, and I honestly don't know whether crowdin won't loose all already existing translation

2022-11-03 08:01 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/values/10-preferences.xml
> -    <string name="notification_minimum_cards_due_vibrate" maxLength="41">Vibrate</string>
If I will add these then Compile error will be there because I am not using these strings.

2022-11-03 10:47 UTC, BrayanDSO commented on AnkiDroid/src/main/res/xml/preference_headers.xml
> -        android:key="@string/pref_notifications_screen_key"
It was mandatory to have it before, but it may not be now. But it's best to have a key associated with each preference so you can retrieve the preference on code with `requirePreference`, configure it, test it, etc.

And the main point is that removing this isn't useful at all to what the PR intends to do, so my suggestion is to keep it

2022-11-03 10:49 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +data class GlobalNotificationPreference(
I suggest renaming this. Having `Preference` on the name implies that this is a implementation of `Preference`, like `ListPreference`, `HeaderPreference` and many other classes, while this isn't one

2022-11-03 10:51 UTC, BrayanDSO commented on AnkiDroid/src/main/res/xml/preferences_notifications.xml
> +        app:summary="7:00"/>
hardcoded

2022-11-03 10:53 UTC, BrayanDSO commented
As a note, if the legacy notification system is going away, the notifcations options on Deck options should be removed as well

2022-11-03 11:09 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    </plurals>
`You have a card due - 1 card due` is redundant IMO and everything could be simplified to just `You have a card due` and `You have X cards due` as title, leaving the description empty or to be used for something more useful like which decks have cards due (to be implemented later, I suppose)

2022-11-03 11:10 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    </plurals>
And if multiple different messages are going to be shown, I suggest leaving this for later/another PR

2022-11-03 16:03 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +    constructor() : this(
![image](https://user-images.githubusercontent.com/1710718/199772203-5472c174-202d-44ca-b670-ad71954e2595.png)

2022-11-04 02:28 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +                addLrn(it.lrnCount)
There is an issue here. 
If there is a deck A::B, then the card you must review today is counted both in A and A::B, so you are counting them twice.
You should only make the sum for top level decks.

In the deck picker, there is a message "4669 cards due (1d 12h)" (that's actually what my ankidroid tells me, aoutch....)
I believe you can reuse the same string (after all, showing guessed time is probably a good idea) and the same counting code.

2022-11-04 07:32 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +data class GlobalNotificationPreference(
@Arthur-Milchior @david-allison what are your thoughts on this?

2022-11-04 07:36 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +import com.fasterxml.jackson.databind.ObjectMapper
I have created the new data class for notification time because I will reuse this in future in sigle deck, backlog notification.
Their are more information that we have to store when we implement exclude deck feature.

2022-11-04 07:41 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +     * Send single and all deck notifications.
Done

2022-11-04 07:45 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +                Timber.d(topLevelDecks.toString())
I added this for testing on my own but forget to remove this. Thanks, I will remove this.

> More importantly, I'd prefer Timber.d("%s", topLevelDecks)

Sure I will take care of this next time. I didn't know that printing logs are costly.

2022-11-04 07:49 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +                addLrn(it.lrnCount)
@Arthur-Milchior this means that I calculate all due cards from top-level decks only.

Although I will be requiring all Deck data in triggering the Backlog notification. So should I remove this in this PR and add it back in the backlog PR..?

2022-11-04 07:56 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +                addLrn(it.lrnCount)
I will add the functionality as the deck picker does.

2022-11-04 08:08 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        setAutoCancel(true)
Yes, I will open the deck picker activity regardless of the due card count.

2022-11-04 09:32 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * Builds the notification that is going to trigger.
Sure, I will do these changes.

2022-11-04 09:39 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        // Check notification is enabled or not.
Done

2022-11-04 09:42 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * Triggers the notification immediately.
> It will check internally whether notification is enabled or not.

I wrote this in the next line. But still should I add this.

2022-11-04 09:46 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * true: @see [ExistingWorkPolicy.REPLACE], false: @see [ExistingWorkPolicy.KEEP]
> If we really need this parameter, I wonder we should not just take a ExistingWorkPolicy parameter instead. At least, it'll be directly clear while reading the function call what the argument means

I am avoiding this because their are several work policies. So I don't want other contributers to pass any work policy.
Starting a work manager is a strategic move I want it to be in binary.

> I'd love a comment explaining in which case you expect this function to be called with true or false for force.

Sure, I will add this.

2022-11-04 10:04 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +    constructor() : this(
@prateek-singh-3212 Have you tried using `@JsonProperty` annotation?

2022-11-04 10:17 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +    constructor() : this(
No, Could you give me any documentation. I would be a great help

2022-11-05 04:34 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +                Timber.d(topLevelDecks.toString())
To be more specific, what can be costly is to compute the string. 
If we were in C++ or any other language with macro, we could just change a compilation flag that would remove this function call and all of its argument.
In Kotlin, as far as I know, even if you change this function for a function that do nothing, in order to avoid the cost of writing log, you'll still need to compute all arguments, even the ones that are actually never used. So, I want to avoid `toString`. Especially if the string can be long.

2022-11-05 04:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * true: @see [ExistingWorkPolicy.REPLACE], false: @see [ExistingWorkPolicy.KEEP]
I can understand that. 
Maybe you can rename the parameter to ensure it's more clear what is being forced or not.
Otherwise, I suspect that it may be a case where you may want to consider using an enum with two values, potentially also KEEP and REPLACE, whose documentation also links to ExistingWorkPolicy's Keep and Replace. This way, you are sure only one of those two values is used here, but it's also simple to understand what is the behavior each values give.

Or maybe we can make it clear with just a boolean, once the documentation explains in which case one is more relevant than the other. Because, I'll admit that right now, I don't understand in which case REPLACE would not be acceptable. After all, REPLACE still works

2022-11-05 04:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * Triggers the notification immediately.
Yeah, I did saw the next line. That's actually why I was able to see that the sentence was not accurate.

2022-11-05 04:57 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/10-preferences.xml
> -    <string name="never_notify">Never notify</string>
As @prateek-singh-3212 asked elsewhere, should this PR also remove the deck notification system?

2022-11-05 04:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +import com.fasterxml.jackson.databind.ObjectMapper
I feel like it only partially answers the question.
For example, not answering the choice of library.

Also, and most importantly, I believe we can, and probably should, use multiple keys. We may want to actually serialize complex data. But we are not forced to save the deck-by-deck data and the global system with the same key

2022-11-06 05:03 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            var triggerTime = hourMinuteTimestampToday(hourOfDay, minutesOfHour)
Done. But it does not give timestamp instead it gives the time in milli seconds

2022-11-06 05:04 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            if (!enabled) {
Done

2022-11-06 05:05 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        val triggerTime = notificationDatastore.getLong(GLOBAL_NOTIFICATION_TIME, -1)
Okay

2022-11-06 05:05 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        val triggerTime = notificationDatastore.getLong(GLOBAL_NOTIFICATION_TIME, -1)
Done, Thanks

2022-11-06 05:06 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        val initialDiff = triggerTime - TimeManager.time.intTimeMS()
Done

2022-11-06 05:07 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    private fun hourMinuteTimestampToday(hourOfDay: Int, minutesOfHour: Int) =
Done, Thanks

2022-11-06 05:12 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * Recreates the deck time map.
Done

2022-11-06 05:13 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * While scheduling the notification we saves the data in datastore So, Data in datastore will be always fresh.
Done Thanks

2022-11-06 05:26 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * true: @see [ExistingWorkPolicy.REPLACE], false: @see [ExistingWorkPolicy.KEEP]
Added more info
```
     * @param force if true then it will use [ExistingWorkPolicy.REPLACE] which destroys the existing work manager and recreates the new one.
     * if false then it will use [ExistingWorkPolicy.KEEP] which doesn't destroys the existing work manager if present.
     ```

2022-11-06 05:27 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * Triggers the notification immediately.
Okay

2022-11-06 05:32 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +         * Get current time according the timezone of user.
Done. Corrected

2022-11-06 05:33 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +         * Key to access user's Time Zone from datastore.
Added

2022-11-06 05:34 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> + * Broadcast receiver to listen timezone change of user.
Added, Thanks

2022-11-06 07:34 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +            // Trigger time will come in future...
Done, Thanks

2022-11-06 07:38 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +        // Creates an explicit intent for an DeckPiker Activity.
Done, Thanks

2022-11-06 07:40 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +                totalDueCount.count()
Done.

2022-11-06 07:43 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    </plurals>
What about 
Title: You have some cards due.
Message: X cards due it will take X mins to review.

2022-11-06 07:46 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +        }
Done, Thanks

2022-11-06 07:50 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/xml/preferences_notifications.xml
> +        android:defaultValue="true"
Why any specific reason? We have to set the default value to true because it is general for all users.

2022-11-06 09:39 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +                    true
Done. Thanks

2022-11-06 10:44 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="notification_preference_global_notification" maxLength="41">Global Notification</string>
Done, Thanks

2022-11-06 10:52 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/xml/preferences_notifications.xml
> +        app:summary="7:00"/>
Done add string HH:MM

2022-11-06 10:59 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/xml/preferences_notifications.xml
> +        android:title="@string/notification_preference_global_notification" />
Added.
> Notifies the due cards from all deck at the given time.

2022-11-06 11:00 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/xml/preferences_notifications.xml
> +        android:defaultValue="true"
Done

2022-11-06 11:03 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/xml/preference_headers.xml
> -        android:key="@string/pref_notifications_screen_key"
Added back

2022-11-06 11:13 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/xml/preferences_notifications.xml
> -    <ListPreference
They don't require to be deactivated. But I think we discussed this on discord.

2022-11-06 11:21 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +                remindAtPreference.summary = "$hour:$minutes"
Added String Resources

2022-11-06 11:27 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +                "${data.notificationTime.hour}:${data.notificationTime.minutes}"
Fixed this. Thanks

2022-11-06 11:27 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +            remindAtPreference.summary =
Used Thanks

2022-11-06 11:38 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +        val notificationDatastore = NotificationDatastore.getInstance(requireContext())
Done.

2022-11-06 12:29 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +                addLrn(it.lrnCount)
Done

2022-11-06 13:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +data class GlobalNotificationPreference(
Agreed

2022-11-06 14:28 UTC, oakkitten reviewed
I mentioned it before and I want to mention it again. There are race conditions in the way the data store is accessed. You may not think that they will ever happen, but they absolutely will happen, race conditions are sneaky like that 😛

2022-11-06 14:28 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            val notificationTimestampForToday = timestampOfTodayAtGivenHourAndMinute(hourOfDay, minutesOfHour)
Timestamp usually refers to a text representation of time. I suggest using the suffix `At`, or `epochMillis`, or something else, but consistently.

2022-11-06 14:28 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +                }
I suggest refactoring the above method to accept adding days, and reuse it. Or make a new method for this

2022-11-06 14:28 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +                true,
I'd like `enabled = ...`, etc

2022-11-06 14:28 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +                notificationHelper.startNotificationWorker(0, false)
I'm not sure what's going on here?

2022-11-06 14:28 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun startNotificationWorker(initialDelay: Long, force: Boolean) {
I'd prefer this method to take absolute time, not a delay

2022-11-06 14:28 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        val notificationManager =
I suggest putting this statement after the guard clause

2022-11-06 14:28 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        }
I suggest checking if notifications are disabled in the calling code, not here

2022-11-06 14:28 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun buildNotification(
This is reminders-specific and the name should probably reflect that

2022-11-06 14:28 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        const val GLOBAL_NOTIFICATION_TIME = "GLOBAL_NOTIFICATION_TIME"
Suffix keys with `_KEY`. I'd also prefix with `PREF_` maybe. Also consider storing these at file level for simplicity.

2022-11-06 14:28 UTC, oakkitten commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    </plurals>
Perhaps only have title, and skip the body? How does that look?

2022-11-06 14:28 UTC, oakkitten commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    </plurals>
Also, I suggest naming keys in a format of `notification__study_reminder__all_decks__title`, etc

2022-11-06 14:28 UTC, oakkitten commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="notification_global_notification_summary" maxLength="41">Notifies the due cards from all deck at the given time.</string>
Maybe “Notify if there are any decks with due cards”?

2022-11-07 00:06 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    </plurals>
`You have %d cards due`. No need for a title

2022-11-07 01:35 UTC, david-allison requested changes

2022-11-07 01:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun manageGlobalNotification(
Proposal (@oakkitten, you have really good 'taste', so please advise if you don't like the style)

```kotlin
    fun updateGlobalNotificationData(data: GlobalNotification[Preference]) {
        if (!data.enabled) {
            Timber.i("Canceling scheduled notification")
            cancelGlobalNotification()
            return
        }

        if (!dataHasChanged(data)) {
            Timber.d("No change in notification data")
            return
        }

        saveNotificationData(data)
        rescheduleGlobalNotificationWorker(data)
    }
```

2022-11-07 01:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        WorkManager.getInstance(context).cancelAllWorkByTag(TAG)
This method is used incorrectly to cancel the global notification (both in name and in execution) - in fact it cancels all under the tag

2022-11-07 01:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +            Channel.GENERAL,
+1 enough to write a comment. This should not be in GENERAL

2022-11-07 01:35 UTC, david-allison commented on AnkiDroid/src/main/res/xml/preferences_notifications.xml
> +
(nit: unnecessary)

2022-11-07 01:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +                data.notificationTime.hour = hour
+1 Avoid mutable state. Just re-fetch the data and ensure you're using the up to date copy

```kotlin
val newData = notificationHelper.setGlobalNotificationTime(hour, minutes)
updateSummaries(newData)
```

2022-11-07 01:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +            }
Add a TODO:

This should be a `TimePickerPreferenceCompat` to save complexity, rather than a generic `Preference` with additional handlers for Time

2022-11-07 01:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            notificationDatastore.putLongAsync(GLOBAL_NOTIFICATION_TIME, timestampOfNextTrigger)
Do we need to store this: it's derived from globalNotification

2022-11-07 02:39 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun manageGlobalNotification(
Good taste? Me? Aw thanks 😳

Well I think that the method is not too bad in the first place. I mean it's easy to understand what's going on and that's what matters.

The reason for the suggestion to split into two methods is because if you pass `enabled = false` you are ignoring the time, and if you create `GlobalNotification` with `enabled = false` you are setting the time to values that are not going to be used. Not terrible, but I would prefer to avoid that.

One way would be to not pass `data` at all, and use preferences/data store in a regular way to fetch the values inside the method. For instance, if I was designing this from grounds up, using my proposal in #12161, this could look approximately like this:

```kt
class Settings {
    var studyReminderForAllDecksEnabled by booleanSetting(..., default = false)
        .whenChanged { enabled ->
            if (enabled) {
                rescheduleStudyReminderNotificationForAllDecks()
            } else {
                unscheduleStudyReminderNotificationForAllDecks()
            }
        }

    var showStudyReminderForAllDecksAt by timeSetting(..., default = TimeOfDay(19, 0))
        .whenChanged {
            if (studyReminderForAllDecksEnabled) {
                rescheduleStudyReminderNotificationForAllDecks()
            }
        }
}

fun unscheduleStudyReminderNotificationForAllDecks() {
    // Cancel alarm
}

fun rescheduleStudyReminderNotificationForAllDecks() {
    val showAt: TimeOfDay = settings.showStudyReminderForAllDecksAt
    // Set alarm at `showAt`, possibly replacing the old one
}
```

But again, the original approach is not too bad. This is just to give an example of an alternative approach. I refactor so much that I usually end up with a result that's completely unlike what I started with.

2022-11-07 02:41 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun manageGlobalNotification(
Oh and by the way I'd also consider putting all decks under a (fake) deck “All decks”, and make the UI for it exactly the same as for the other decks. This could simplify the code considerably as well, if we didn't have to handle the reminder for all deck separately.

2022-11-07 04:30 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    </plurals>
Are you sure? I will not be going to look good.

2022-11-07 04:31 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        setAutoCancel(true)
Cool, Let me write the logic for it.

2022-11-07 04:34 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +            7,
Okay, you were saying for 7:00 PM. I thought you told me to to put 7:00 AM as default

2022-11-07 04:34 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +            7,
I will do it.

2022-11-07 04:38 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +    var enabled: Boolean,
I can't because I am using its feature while setting the notification preference. I will do the suggested correction then their is code repetition. See NotificationSettingPreference

2022-11-07 04:43 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * existing work manager if present.
If there is a notification that needs to be triggered first before the currently scheduled one then we will use force. It will be used when I will work on backlog notifications.

2022-11-07 04:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +    var enabled: Boolean,
Fixing this is explained in my comments on `NotificationSettingPreference`

2022-11-07 04:45 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +    var enabled: Boolean,
Okay. I will do this. Thanks.

2022-11-07 04:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * existing work manager if present.
Add this to the documentation

2022-11-07 06:21 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +            7,
Done

2022-11-07 06:22 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +        true,
Done, Thanks

2022-11-07 06:24 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +    var enabled: Boolean,
Done, Thanks

2022-11-07 06:24 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +data class GlobalNotificationPreference(
Done

2022-11-07 06:26 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationDatastore.kt
> +import com.fasterxml.jackson.databind.ObjectMapper
I am in favor of using this because we have to add the additional complexity to the global notification like list of decks that we have to exclude.

2022-11-07 16:19 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +    }
No, Because notifies the data first. Then we can schedule the notification

2022-11-07 16:20 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +    suspend fun notifies(): Result {
As it says, I it used to notify the user.

2022-11-07 16:20 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +        val topLevelDecks = try {
No, Because we are using top-level deck in deck picker activity as query raised by @david-allison

2022-11-07 17:05 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +    suspend fun notifies(): Result {
It's not clear what it means “to notify the user”. Notify how? About what? I suggest being more precise.

2022-11-07 17:09 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +        val topLevelDecks = try {
Yes, we are _using_ only top-level decks, but this variable contains information about all decks, I believe. You are passing it to `fireGlobalNotification` which takes `allDecks`. It doesn't make much sense to only pass *top-level* decks to a method that wants `allDecks`, does it?

2022-11-07 17:15 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +    }
Ah, I see the issue. `notifies()` calls `fireGlobalNotification(...)`, and `fireGlobalNotification()` does `// Save next notification time`, and then `rescheduleNextWorker()` uses this saved time.

This is a problem with methods that do not do exactly what their name says they do. I suggest refactoring in such a way that `fireGlobalNotification()` does _not_ save next notification time.

2022-11-07 17:18 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * existing work manager if present.
I have a better question, why should a developer *not* set force?

2022-11-07 17:23 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        minutesOfHour: Int,
Used, Thanks

2022-11-07 19:05 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * existing work manager if present.
Done. Thanks

2022-11-07 19:08 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        WorkManager.getInstance(context).cancelAllWorkByTag(TAG)
I am using this method for this PR only. I will modify this method when I will add the backlog notification feature.

2022-11-07 19:16 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    </plurals>
Done This, Thanks

2022-11-07 19:20 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    </plurals>
Done, Thanks

2022-11-07 19:21 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +            context.resources.getQuantityString(
Done

2022-11-07 19:23 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +            Channel.GENERAL,
Changed to Global Notification Channel

2022-11-07 19:24 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +        val resultIntent = Intent(context, DeckPicker::class.java).apply {
Done

2022-11-07 19:24 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +    private suspend fun fireGlobalNotification(allDecks: List<TreeNode<DeckDueTreeNode>>) {
@Arthur-Milchior suggested me to use global to make more generalize.

2022-11-08 12:15 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +    constructor() : this(
@prateek-singh-3212 https://www.baeldung.com/jackson-annotations#1-jsonproperty

2022-11-08 12:18 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/model/NotificationData.kt
> +    constructor() : this(
I'm not sure if the above is relevant to the current use-case. I've not worked with Jackson.

2022-11-13 17:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/xml/preferences_notifications.xml
>          android:key="@string/pref_notifications_blink_key"
It may be nice to remove this preference when a phone don't have light. As then it can't blink.

2022-11-14 11:07 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/xml/preferences_notifications.xml
>          android:key="@string/pref_notifications_blink_key"
Sure, but shall I change the current PR? just asking because it is feature-specific PR. I will create a separate PR for this.

2022-11-14 21:54 UTC, david-allison requested changes
Seems good - retry behaviour needs to be documented and fixed

2022-11-14 21:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +            setOnPreferenceChangeListener { _, _ ->
I believe if there's a single value, then it's the preference value as an `Any`

2022-11-14 21:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +            return Result.retry()
⚠️ This needs to be fixed

2022-11-15 04:51 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/xml/preferences_notifications.xml
>          android:key="@string/pref_notifications_blink_key"
I'm fine waiting for an extra PR. Just add a todo somewhere

2022-11-15 09:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * existing work manager if present.
I'm sorry, but I'm still as confused.
I suggested adding an enum on https://github.com/ankidroid/Anki-Android/pull/12766#discussion_r1012373975 , please comment explicitly you won't follow an advice if you don't intend to follow it. It's perfectly acceptable, but be explicit about it.
More importantly, you explain what will occur depending on whether you set force or not. I'm pretty sure @david-allison and @oakkitten where able to follow KEEP/REPLACE and read their documentation, as your previous documentation suggested. So, I suspect that they may still have the same question than me.
Why would someone want to keep the currently existing notification. You provide the option to keep it, but I feel like we never actually want to have two simultaneous global notification scheduled. So, why do you provide it? In which case would it be a problem to always use REPLACE and ensure we only use a single notification

2022-11-15 09:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun startNotificationWorker(initialDelay: Long, force: Boolean) {
@david-allison you may want to indicate who you are agreeing with.
Especially since you are considering two cases where you have the word "delay" and none when you mention timestamp

2022-11-15 09:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        val notificationManager =
Agreed

2022-11-15 09:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        val notificationManager =
Agreed

2022-11-15 09:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        }
agreed. Especially since it's only caller, `fireGlobalNotification` is bing and count the numbers of cards, it seems interesting to ensure that we only count it if we are sure we want to display it

2022-11-15 09:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun buildNotification(
Also, should probably be private. This helper method is great for notification, it simplifies code, I love it. However, we may want to make it clear it is not a general builder

2022-11-15 09:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +
not done yet

2022-11-15 13:14 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +            return Result.retry()
changing this to failure

2022-11-15 13:17 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +    suspend fun notifies(): Result {
Done. Thanks

2022-11-15 13:18 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +    private fun fireGlobalNotification(allDecks: List<TreeNode<DeckDueTreeNode>>) {
Done. 
Added.
` Fire global notification. It requires only top level decks.`

2022-11-15 13:20 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +            allDecks.forEach {
Done thanks

2022-11-15 13:23 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            Timber.d("Time gone for today, Scheduling next day.")
Thanks 
Added 
`Scheduling notification for next day.` instead of `Time gone for today, Scheduling next day.`

2022-11-15 13:32 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        Timber.d("Next trigger time $timestampOfNextTrigger, Initial delay $initialDelay")
Done, Thanks

2022-11-15 13:32 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * While scheduling the notification we saves the data in SharedPreference.
Done thanks

2022-11-15 13:33 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        // Storing Global Notification. Their timestamp may be wrong
Sorry, That comment is of the previous code. I changed this now.

2022-11-15 13:34 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        if (!globalNotificationEnabled) {
Did this

2022-11-15 13:47 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +     * existing work manager if present.
@Arthur-Milchior We are using the unique worker this means that there should be one and only one worker notification worker scheduled. 
The aim of this is that. If the notification worker is not scheduled for some xyz reason and there is pending notification then we will rerun the worker and do the pending task (if any) and then reschedule the notification again. See its implementation in `AnkiDroidApp`

2022-11-15 13:56 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun buildNotification(
@oakkitten @Arthur-Milchior any idea?? I am bad at naming 😅
I think we should not make this private method.

2022-11-15 14:02 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +
Changed

2022-11-15 14:04 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +                Timber.d("No Timezone changed found...")
yes, I timezone changes triggers 2 time when device timezone changes and network operator timezone changes saw this on stackoverflow

2022-11-15 14:15 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +        fun getZonedCurrTimeMS(zoneId: String): Long {
I returns the time in ms according to the given timezone.

2022-11-15 14:18 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +            PendingIntent.FLAG_UPDATE_CURRENT
It requires an android version greater than `M`. I have to use this in if else block.

2022-11-15 14:20 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +        const val GLOBAL_NOTIFICATION_ID = 11
Sure I will add the notification ids in this companion object only

2022-11-15 14:23 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +            )
I dont want to because it is used only one time

2022-11-15 14:27 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/xml/preferences_notifications.xml
> +
Removed

2022-11-15 14:29 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="notification_global_notification_summary" maxLength="41">Notifies the due cards from all deck at the given time.</string>
Suggeted by @Arthur-Milchior (correct me If I am wrong). But it really depends on person

2022-11-15 14:34 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +            setOnPreferenceChangeListener { _, _ ->
Sorry, I didn't understood this

2022-11-15 15:05 UTC, Arthur-Milchior commented
Juste rebased on top of main because we recently removed a bug that made ankidroid slow on my phone

2022-11-16 07:22 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            return
Also, I guess I'd exchange the `if` and `else`, so that you can remove the negation. Not very important, but still, it simplifies the read a little bit

2022-11-16 07:41 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +                Timber.d("No Timezone changed found...")
Agreed with @oakkitten , a comment would be nice too. That is, a comment in code.
And you only answered about the equality. It is not clear to me why, when the old time zone is null, we have nothing to do. After all, it seems that if we finally have a timezone and we didn't, we should use it

2022-11-16 07:52 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +        fun registerTimeZoneChangeReceiver(context: Context, receiver: BroadcastReceiver) {
Do you know what should be done instead ? I don't see an obvious things to do instead

2022-11-16 07:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +    private fun fireGlobalNotification(topLevelDecks: List<TreeNode<DeckDueTreeNode>>) {
/**
     * @param topLevelDecks: top level decks.
     * */

The first sentence repeat the name of the function so is not useful.

2022-11-16 14:53 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +        fun getZonedCurrTimeMS(zoneId: String): Long {
The number of milliseconds since epoch does not depend on a time zone, it's the same number around the globe

2022-11-16 15:01 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun buildNotification(
Strongly suggest using verbs for actions, `buildReminderNotification` not `reminderNotification`. Or, rename the class to `ReminderNotificationHelper` if it makes sense, then you can keep `buildNotification`

2022-11-16 15:03 UTC, oakkitten commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="notification_global_notification_summary" maxLength="41">Notifies the due cards from all deck at the given time.</string>
I don't think “Notify the due cards” is good English, but I'm not a native speaker, suggest checking with one

2022-11-16 17:45 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +            setOnPreferenceChangeListener { _, _ ->
if you provide a single parameter, it contains the value which has been changed (typed as an `Any`).

2022-11-16 17:56 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +            setOnPreferenceChangeListener { _, _ ->
I don't think you can do `{ newValue ->`, but `{ _, newValue ->` should work

2022-11-16 20:27 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +    private fun fireGlobalNotification(topLevelDecks: List<TreeNode<DeckDueTreeNode>>) {
I'm going to disagree with you @oakkitten. 
@prateek-singh-3212 , don't worry if you don't know who to listen to, we won't block merging the PR for a variable name.

Anki set of deck is a forest. This list contains the root of each tree. Those tree are not guaranteed to be childless at all. However, we do not need to consider the children in this function, because the member's value of a node consider both the number of cards actually in this very node, the number of cards in children of this node, and the limit if this node deck option. 

However, those are all details that are entirely irrelevant to this function. So I believe that `fireGlobalNotification` should just take a single value `numberOfCardsToReview: Int`. And use it in its message. 

Since the same number of cards also appear in the top of the deck picker, we can even reuse the same function. And potentially eventually reuse the same string, that also contains the expected time the review will take (or at least, we can put this in a todo if it's too complex)

2022-11-16 22:08 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +    private fun fireGlobalNotification(topLevelDecks: List<TreeNode<DeckDueTreeNode>>) {
> However, those are all details that are entirely irrelevant to this function. So I believe that `fireGlobalNotification` should just take a single value `numberOfCardsToReview: Int`. And use it in its message.

Ah, this would be ideal. I still think that “global notification” is a very confusing name, but otherwise taking an `Int` is what this method is supposed to do.

But if you do not pass an `Int`, but the list of all decks, it's best to avoid creating new names. As I said above, if you are using `topLevelDecks` you are essentially lying to the reader. And, it exposes the implementation details. The caller should not care how exactly the method is producing whatever it wants from the tree.

2022-11-17 06:15 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        val hourAndMinutes = sharedPreferences.getString(GLOBAL_NOTIFICATION_TIME, null)
This will be a bit complex for the new contributor while reading the code. Keeping my code for now. btw Thanks for your suggesting.

2022-11-17 06:27 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +            return
Done

2022-11-17 07:34 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun buildNotification(
My plan is to use this helper class for all the notification instead of reminder notification. I want to use this while sending the sync notification also

2022-11-19 03:28 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun startNotificationWorker(initialDelay: Long, force: Boolean) {
Consider this as backup. If the notification worker is somehow not scheduled or enqued and
`force=false` then it will execute the notification worker at that time with giving initial delay.

2022-11-19 03:31 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun buildNotification(
done

2022-11-19 03:31 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        }
Done

2022-11-19 03:44 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +                Timber.d("No Timezone changed found...")
I am not saving the currentTimeZone on starting of app. That's why when timezone reviciver will run first time then It will have `oldTimeZone` null.

2022-11-19 09:23 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +        } else if (notificationEnabled) {
You can consider this case as a backup. If the worker is not scheduled and notification is enabled then this case will occur. 
The functionality of `force` which you mentioned earlier can be easily understood from here.

2022-11-19 10:36 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/receiver/TimeZoneChangeReceiver.kt
> +                Timber.d("No Timezone changed found...")
Remved this

2022-11-19 11:41 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +                val enabled = !globalNotification.isChecked
Done

2022-11-19 14:50 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun startNotificationWorker(initialDelay: Long, force: Boolean) {
I agree with OK

It's easier to reason about the log line if it only needs one piece of information (the time a notification is scheduled) rather than two: the current time and the delay

Sorry I missed this.

2022-11-19 17:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +            // TODO: Remove this preference when a phone don't have light.
Still open

2022-11-19 17:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +                if (newValue as Boolean) {
Nit: I'd consider using `val enabled = newValue as Boolean`, for ease of reading

2022-11-19 17:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +    private fun fireGlobalNotification(topLevelDecks: List<TreeNode<DeckDueTreeNode>>) {
Please, @prateek-singh-3212 , don't resolve unless you applied the suggestion. If you didn't, explain why, or add a todo

2022-11-19 17:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +        // An intent to open the deck picker, to use when the user tap on the notification.
It seems that you are going to open deck picker or reviewer depending on the number of top level deck. Can your comment please reflect your code?

2022-11-19 17:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +        // Build the notification
I don't see the added value by this comment. `buildNotification` is literally the name of the function

2022-11-20 18:27 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +    private fun fireGlobalNotification(topLevelDecks: List<TreeNode<DeckDueTreeNode>>) {
> fireGlobalNotification should just take a single value numberOfCardsToReview: Int. And use it in its message.

I don't want to do this as of now. because there is no point to calculate the deck count before calling the function as we are not using this further (not required by any other function). 
My approach is that there are different functions for different notifications and I am letting those functions calculate the data which they want to calculate.

2022-11-20 18:29 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        val hourAndMinutes = sharedPreferences.getString(GLOBAL_NOTIFICATION_TIME, null)
definitely I will consider this in deck-based notification.

2022-11-20 18:30 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun startNotificationWorker(initialDelay: Long, force: Boolean) {
Thanks @david-allison. using intalDelay

2022-11-20 18:47 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        Timber.d("Next trigger time %s, Initial delay %d", Timestamp(timestampOfNextTrigger), initialDelay)
Had to look it up. I'd avoid using SQL-specific methods for this. Besides, `Timestamp` produces a string without time zone information, which you would not expect from the text. I suggest using usual `Instant.ofEpochMilli`, which includes the time zone if you `toString()` it, and can be converted to any time zone.

2022-11-20 19:29 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +        } else if (notificationEnabled) {
Okay I will remove the force parameter

2022-11-21 11:11 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun startNotificationWorker(initialDelay: Long, force: Boolean) {
Removed this as of now. I will add this in the future if required.

2022-11-21 11:19 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        WorkManager.getInstance(context).cancelAllWorkByTag(TAG)
@Arthur-Milchior Changed this to `cancelUniqueWork(TAG)` this will cancel the notification worker only. Because we are using the unique worker.
Please note that there is **one and only notification worker is scheduled** whether we have to trigger the global notification or backlog notification (Which I am going to add in the future).
And unique worker means that there is only one worker that can exist with `uniqueWorkerName` in our case uniqueWorkerName is `TAG`

2022-11-21 11:21 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        Timber.d("Next trigger time %s, Initial delay %d", Timestamp(timestampOfNextTrigger), initialDelay)
Done thanks

2022-11-21 11:23 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun buildNotification(
Changed class name to `ReminderNotificationHelper` Thanks @Arthur-Milchior @oakkitten

2022-11-21 11:32 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +        // An intent to open the deck picker, to use when the user tap on the notification.
Added Thanks,
```
// An intent to open the deck picker or reviewer depending on due count, to use when the user tap on the notification.
```

2022-11-21 11:32 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +        // Build the notification
Removing...

2022-11-21 11:37 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +        var hourOfNotification = notificationTime.split(":")[0].toInt()
I am confused here. What should I do?

2022-11-21 11:39 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +                if (newValue as Boolean) {
Done thanks

2022-11-21 11:39 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +            // TODO: Remove this preference when a phone don't have light.
Done now sorry missed last time

2022-11-21 21:32 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        Timber.d("Next trigger time %s, Initial delay %d", Timestamp(timestampOfNextTrigger), initialDelay)
In what way is it weird? In `2022-11-22T09:45:03.661Z`, [`Z` means UTC](https://en.wikipedia.org/wiki/Coordinated_Universal_Time#:~:text=The%20time%20zone%20using,zones%20other%20than%20Greenwich.).

2022-11-21 21:42 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +        val hourAndMinutes = sharedPreferences.getString(GLOBAL_NOTIFICATION_TIME, null)
Encoding/decoding is a different level of abstraction and should not appear in this code. If you do something like this, it won't be hard to read, and you can use arbitrary packing logic

```kt
data class TimeOfDay(val hour: Int, val minutes: Int) {
    fun toMinutesSinceMidnight() = hour * 60 + minutes

    companion object {
        fun fromMinutesSinceMidnight(input: Int) = TimeOfDay(input / 60, input % 60)
    }
}
```

2022-11-21 22:09 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +            )
Sorry, I think I meant to place my comment elsewhere, not sure where, never mind this

2022-11-21 22:17 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +        const val GLOBAL_NOTIFICATION_ID = 11
(I meant all notification ids from all places in the app. Like maybe someone else adds another notification and decides to use id 11 as well. But this may be another PR)

2022-11-22 08:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
> +        var hourOfNotification = notificationTime.split(":")[0].toInt()
I'm sorry, but I don't know what more to explain here. I don't know which part is confusing.
You may decide not to create such a dataclass. You may decide to create it, and so ensure the encoding/decoding is done by the dataclass and not by the notification code.

2022-11-22 08:18 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun startNotificationWorker(initialDelay: Long, force: Boolean) {
Thanks.
Given how long we spent discussing this question, I'm curious to know whether you understand why Oakkitten and myself questioned the "force" parameter. Or whether it's just so that we get done with it

2022-11-22 13:37 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NotificationHelper.kt
> +    fun startNotificationWorker(initialDelay: Long, force: Boolean) {
@Arthur-Milchior Yes, I understood that. But I didn't want to remove this because I am going to use it in Backlog notification. But I think it works for me fir now.
btw when are we going to merge this??

2022-11-23 07:33 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/NotificationWorker.kt
> +    private fun fireGlobalNotification(topLevelDecks: List<TreeNode<DeckDueTreeNode>>) {
The usual rule of thumb is that a function takes exactly the parameter it needs, no more. In this case, that's:
* the number of card to review (to display it)
* the id of the only deck (if there is a single top level deck, in order to open the reviewer directly); which can be a `Long?`

This ensure that, if we eventually write unit tests, or integration test, the function is as simple as possible to test. It also allows other function to call it even if they don't have a lot of information. 

If it's needed, it's fine to add an extra function that takes the list of nodes, compute the sum, and then call  `fireGlobalNotification`. For example, if we actually try to generalize this function and ensure it implements a method from an interface. Or if we realize that we use this function multiple time.

I admit that there `notifiesUser` should not actually compute the number of cards, that's not really part of the business logic of this function. But that can be done by a function that just take the list and return the sum. A nice easy to test small function. Or better, that can be done by the same code than the one showing the list at the top of the deck picker as I mentioned previously

2023-08-31 11:10 UTC, closed without merging

2023-08-31 11:10 UTC, BrayanDSO commented
Codebase changed a lot since this PR was opened, and looks abandoned. It's best to create another one if work is restarted

2023-08-31 11:10 UTC, BrayanDSO commented
Codebase changed a lot since this PR was opened, and looks abandoned. It's best to create another one if work is restarted

2024-07-02 02:04 UTC, bqv commented
I rebased this onto current main. It works, best I can tell. If I resurrect it, is it mergeable in current state?