Create & use manage space activity
ankidroid/Anki-Android pull request #12765
Opened 2022-10-31 17:21 UTC by oakkitten

Closes #12366, #12538, #12539, #12540. Includes everything from #12371. I'd push there but have no access.

This is a draft, and while it is ready for reviewing, it is not yet for merging: the strings need to be extracted. It's easier to review them when they are not.

<img src="https://user-images.githubusercontent.com/1710718/199066689-905d0bb3-79d0-4cc5-8b57-e2c061e47070.png" width=250> <img src="https://user-images.githubusercontent.com/1710718/199066697-644fc7cb-2b80-4b53-831a-203934441f09.png" width=250> <img src="https://user-images.githubusercontent.com/1710718/199066710-86ced905-67fb-4d9f-b9d2-b7d034b8ced9.png" width=250> <img src="https://user-images.githubusercontent.com/1710718/199066721-f71812b9-88ad-4ddd-9a21-d06d280b66f6.png" width=250> <img src="https://user-images.githubusercontent.com/1710718/199066734-ec485bc9-3486-4feb-8003-3832936258b4.png" width=250> <img src="https://user-images.githubusercontent.com/1710718/199066746-152bffa2-4aff-4a4a-9d03-602e3517ffca.png" width=250> 

It works as you'd expect from the screenshots. You can select unused media files before deleting (all are selected by default), and you can select backups before deleting (none are selected by default). File names are shown for unused media files, and dates in current locale for backups. A few issues:

* Activity transition animations are weird. It slides from the bottom, and on finishing just disappears. Any idea how to set transitions to the default ones?
* Deleting the collection should `finish()` or refresh all activities that depend on the collection. Note that these activities might be visibile to user at the time of deletion! I am not sure how to do this. Perhaps keeping weak references to all activities would work.
* This probably needs tests but I'm not good at those, so I hope someone else makes them.
* Just something to keep in mind; on Android <= N, file sizes will be shown using powers of 1024. This means that the numbers shown will be inconsistent on different Android versions, which is less than ideal. On the other hand, they will be consistent with other the numbers on the same device.

### How Has This Been Tested?

At the moment, physically on my Android 11 device.

### Checklist

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-10-31 18:37 UTC, oakkitten commented on build.gradle
> +                freeCompilerArgs = ['-Xjvm-default=all', "-Xcontext-receivers"]
I've been using many an experimental syntax in Kotlin and haven't had an issue so far. Context receivers greatly improve readability in my opinion.

2022-11-02 20:46 UTC, BrayanDSO requested changes
I'm not on my PC and don't have Android Studio here + I'm not familiar with some things like context receivers, so I'm just giving a quick review on what called my attention

- The first screenshot is outdated, as it has `Delete app data` instead of `Delete everything`

> Deleting the collection should finish() or refresh all activities that depend on the collection. Note that these activities might be visibile to user at the time of deletion! I am not sure how to do this. Perhaps keeping weak references to all activities would work.

If the goal is just finishing all of them, I'd take a look on https://developer.android.com/reference/android/content/Intent#FLAG_ACTIVITY_CLEAR_TASK and https://developer.android.com/guide/components/activities/tasks-and-back-stack.

2022-11-02 20:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
> +    enum class ThemeChanged { Yes, No }
Using a enum as just a binary true/false isn't helpful IMO. It's just more one thing for a dev to keep in mind/deal with + a bit more time to compile + make the app [heavier](https://medium.com/android-news/android-performance-avoid-using-enum-on-android-326be0794dc3) while a simple Boolean would work perfectly

2022-11-02 20:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        if (Themes.updateCurrentThemeByUiMode(newConfig.uiMode) == Themes.ThemeChanged.Yes) {
The same this needs to be updated on `DeckOptions.kt` and `FilteredDeckOptions.kt` as well (they are not `AnkiActivity`s and at the time I just duplicated the code as I expected to deal with it soon, but life took over my time). 

For reusability purposes, maybe extracting everything to a `recreateIfThemeHasChanged` as an Activity's extension method could work

2022-11-02 20:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceActivity.kt
> +        Themes.setThemeLegacy(this)
For anyone else that wants to take this TODO, just set `textColorSecondary` on the default themes to the same color used by the legacy themes.

2022-11-02 20:46 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="dialog_positive_delete_selected">Delete selected</string>
Redundant

2022-11-02 20:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +}
Could you join this with the logic of the `Select backup to restore` naming pattern (https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt#L208)?

2022-11-02 20:46 UTC, BrayanDSO commented on AnkiDroid/src/main/res/xml/manage_space.xml
> +        android:summary="AnkiDroid will recreate collection backups later, up to the number specified below"
The summary isn't about the item's action. Having no summary here is fine IMO, as `Delete backups` is quite straightforward

2022-11-02 20:46 UTC, BrayanDSO commented on AnkiDroid/src/main/res/xml/manage_space.xml
> +        android:summary="Delete collection, media, and backups. Settings are not deleted"
2. `Settings are not deleted` isn't accurate because some settings are saved/retrieved from the collection. I consider this a niche option, so I wouldn't be opposed to removing it

2022-11-02 20:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +            deleteEverythingDialogTitle = "Delete everything 🤯"
I think that it's best to avoid using emojis on messages/titles

2022-11-02 20:55 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +}
And as a second thought, I believe that only the files that matches the backup file name pattern should be shown, so the `N/A` option wouldn't be necessary

2022-11-02 21:14 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
>              args.putInt("dialogType", dialogType)
Will do

2022-11-02 21:16 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceActivity.kt
> +package com.ichi2.anki.ui.windows.managespace
`com.ichi2.anki` is our package name, so I think everything should be inside it. This way, you can say `.ui.windows.managespace.ManageSpaceActivity` in the manifest, else you have to specify the full name.

2022-11-02 21:17 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +            deleteEverythingDialogTitle = "Delete everything 🤯"
I like emoji 🤪

2022-11-02 21:25 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +}
As I understand `getBestDateTimePattern` is useful when you want to have a special date format. In this case the default one should work, so I'm assuming this should do an adequate job?

`"N/A"` will never be shown to users, it's just here because I don't like `!!`s. But having `this.name` would probably be even better.

2022-11-02 21:31 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        if (Themes.updateCurrentThemeByUiMode(newConfig.uiMode) == Themes.ThemeChanged.Yes) {
I hear you but perhaps it's best to leave this to another PR

2022-11-02 21:33 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +}
> As I understand getBestDateTimePattern is useful when you want to have a special date format. In this case the default one should work, so I'm assuming this should do an adequate job?

It does, but mygoal here is to be consistent by using the same date pattern for backups along the app.

> "N/A" will never be shown to users, it's just here because I don't like !!s.

`!!` is for those cases that things should won't ever be null. The `N/A` here is completely useless and misleading if that is the case

2022-11-02 21:37 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        if (Themes.updateCurrentThemeByUiMode(newConfig.uiMode) == Themes.ThemeChanged.Yes) {
Fine by me. Keeping this unresolved to create an issue later

2022-11-02 21:38 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
> +    enum class ThemeChanged { Yes, No }
The call site is pretty readable though, `if (updateTheme() == ThemeChanged.Yes)`. If not using an enum, you have to say something like `if (updateThemeAndReturnWhetherChanged())` or `updateThemeAndIfChanged { }`. I didn't sleep well so I can't come up with a name that I'd like better than the enum right now.

As for impact on the code, this is what R8 will deal with once enabled

2022-11-02 21:39 UTC, oakkitten commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="dialog_positive_delete_selected">Delete selected</string>
I think it's worth to be a little more explicit. This is easy to translate anyway

2022-11-02 21:43 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="dialog_positive_delete_selected">Delete selected</string>
Just `Delete` is fine and shorter + one less string to translate. It is redundant telling that the selected items are the ones being deleted if you have checkboxes to select them.

2022-11-02 21:44 UTC, oakkitten commented on AnkiDroid/src/main/res/xml/manage_space.xml
> +        android:summary="AnkiDroid will recreate collection backups later, up to the number specified below"
I agree, but the widget on the right displays the number of files & data size in two rows. I couldn't figure out how to make it stay big; if only using preference title, the widget shows only one line of text. Besides, even if it was enlarging the preference, I don't think it would look well.

2022-11-02 21:48 UTC, oakkitten commented on AnkiDroid/src/main/res/xml/manage_space.xml
> +        android:summary="Delete collection, media, and backups. Settings are not deleted"
Perhaps “App settings are not deleted”?

I have no strong opinion about whether this option should go or stay.

2022-11-02 21:49 UTC, BrayanDSO commented
I'm not sure about the unused media dialog. I expect people to have dozens/hundreds of files to delete and not care about them because they are unused, especially after a massive notes deletion. 

Selecting them manually one by one would be painful.

And I find the scenario of "having the files named carefully so you can distinguish them (instead of a timestamp or random name)" + "wanting to keep a unused file" + "knowing how to get that file out of media folder to use the file" quite rare.

2022-11-02 22:27 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +}
I'll change the other method.

Someone could call this method later on a file that's not a backup. I really don't like `!!`. If you use it, the reader of the code has to wonder if there's a possibility that this may crash. Better avoid it even if this means stuff like `?:` or `== null` IMO.

2022-11-02 22:37 UTC, oakkitten commented
> The first screenshot is outdated, as it has Delete app data instead of Delete everything

I had my collection in the legacy folder for the first screenshot and in the app-specific folder for the second one.

> If the goal is just finishing all of them, I'd take a look on

As I understand this requires launching a new activity, and we don't want to launch a new activity here.

> I'm not sure about the unused media dialog. I expect people to have dozens/hundreds of files to delete and not care about them because they are unused, especially after a massive notes deletion.

This is why all are selected by default. Tbh the main reason I went with selection was because it was easier to implement.

2022-11-02 23:28 UTC, BrayanDSO requested changes

2022-11-02 23:28 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> -                    val localDf = SimpleDateFormat(getBestDateTimePattern(Locale.getDefault(), "dd MMM yyyy HH:mm"))
huh. The custom pattern had a reason to be used.

Originally, this custom pattern was intended to avoid ambiguation of date patterns on languages that are used on multiple countries.

As an example, American english uses month/day/year, while British english uses day/month/year. 

So if you use AnkiDroid with `English` set, `DateFormat.getInstance()` will deliver something like 11/2/22. For a American resident this is November 2nd, while for a British resident this is February 11th. That's why the month name is written like `Nov 02, 2022.` so nobody gets confused

2022-11-02 23:38 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +        is Size.Calculating -> "Calcu-\nlating…"
Does Android have a line wrap method somewhere? I expect this to not wrap correctly for people with super big or super small fonts

2022-11-02 23:42 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +}
A comment explaining that it won't crash is sufficient IMO

2022-11-02 23:47 UTC, BrayanDSO commented on AnkiDroid/src/main/res/xml/manage_space.xml
> +        android:summary="Delete collection, media, and backups. Settings are not deleted"
My vote would be to remove it

2022-11-03 15:40 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +}
There's a saying in my country, once a year even an unloaded gun shoots. It is possible to call this in a way that it crashes. How about a compromise? I changed the code to have a guard clause.
```kt
val backupDate = BackupManager.getBackupDate(file.name) ?: return file.name
return formatter.format(backupDate)
```

2022-11-03 15:41 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> -                    val localDf = SimpleDateFormat(getBestDateTimePattern(Locale.getDefault(), "dd MMM yyyy HH:mm"))
Oh I see now. Fixed in 70ffee0

2022-11-03 15:47 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +        is Size.Calculating -> "Calcu-\nlating…"
Wrapping would mean setting fixed width and I'd prefer the box to grow if it can't accommodate the text

2022-11-04 01:00 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
> +}
Wouldn't a function be way simpler here? The only goal of the class is to call `getTimeOfBackupAsTest`, we only use this on two places, and I don't expect it to be used anywhere else, and on both you write
```kotlin
val formatter = LocalizedUnambiguousBackupTimeFormatter()
...
formatter.getTimeOfBackupAsText()
```
instead of simply
```kotlin
beautifulFunctionOfBackupNames()
```

2022-11-04 01:08 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +        is Size.Calculating -> "Calcu-\nlating…"
I think that with super small fonts this won't look good split

2022-11-04 01:09 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +}
LGTM

2022-11-04 01:36 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
> +}
This is simply to reuse the actual formatter instead of creating one for each backup

2022-11-04 09:56 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +        is Size.Calculating -> "Calcu-\nlating…"
Here's the smallest text my device can show on various display sizes

<img width=250 src=https://user-images.githubusercontent.com/1710718/199944525-ae9b5700-bb9b-43cd-8d8c-6bcf3587e0f2.png> <img width=250 src=https://user-images.githubusercontent.com/1710718/199944536-95ef8550-e77d-428a-9602-7d7077921302.png> <img width=250 src=https://user-images.githubusercontent.com/1710718/199944540-c33a3f7d-a8fc-41d5-8f30-af5b4db6bb4b.png>

2022-11-04 15:02 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
> +}
C'est vrai

2022-11-04 17:57 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
> +}
Oh and a new instance is created because the locale can change. And also because `SimpleDateFormat` is for some reason not thread safe, I remember that I once ran into an issue with that 🤦

2022-11-04 20:26 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
> +}
> I remember that I once ran into an issue with that 🤦

This kind of thing is annoying when having to deal with, but fun to tell the story later

2022-11-04 20:36 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +        is Size.Calculating -> "Calcu-\nlating…"
Maybe a loading icon, like this emoji 🔄, progress bar, or something that is not a word to be wrapped, would look ok? This would ease translations a lot, especially since this normally only is shown for a very brief time and the user may not see it at all

2022-11-04 21:13 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +        is Size.Calculating -> "Calcu-\nlating…"
I thought about that (because it would look much better anyway) but

* This is much simpler to implement
* Other apps also use “Calculating...” or “Computing...”
* Having a loading icon might be slightly confusing. It might be not clear to the user what is going on. In most cases at least one of the icons will load fast, so the user can deduce what should go in the boxes, but as this screen will be used so rarely, I'm still not a fan. OTOH, one can argue that from “Calculating...” it's not clear what exactly is loading either

I'm not entirely against a loading icon but that was my thinking

2022-11-04 22:50 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +        is Size.Calculating -> "Calcu-\nlating…"
I like `Calculating...` and agree on the point of a loading icon possibly being confusing. My main concern is that translators don't have a way to know if the manual wrap they are doing is going to look nice on super small and super big fonts. 

A slightly more complex implementation can spare a lot of the translators' time here, with text wrapping, an icon, or any other idea than manually writing strings with a line break inside a word

2022-11-05 11:11 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +        is Size.Calculating -> "Calcu-\nlating…"
"Calculating..." is a pretty long word and I expect that in most languages the word would be of the same length or even shorter, or maybe _slightly_ longer. As long as it is cut in the middle, or not cut at all if it's very short, I think any issues are unlikely, we just have to make sure there are screenshots and a comment, and maybe put a reminder somewhere to go through translations before releasing and check for weird words just in case.

An icon is a doable alternative but I'm not sure how wrapping etc could work.

2022-11-06 02:08 UTC, oakkitten commented
There's a bit of a problem with the last item, Max number of backups. It seems it's not respected with the V3 scheme. It seems that the backend is using a different logic to create backups, and we don't have UI for those settings.

2022-11-08 01:14 UTC, oakkitten commented
Thanks to David I now can access these settings. There's two small issues with it:

* `TR.preferencesDailyBackups()` & related methods have `:` at the end, so I'm not sure if we want to use these. (I strongly prefer not to have stray `:`s.)
* These settings are synchronized between devices. I don't think we want this?.. User may want to have more backups on their PC and fewer on their phone. @dae thoughts?

2022-11-08 03:51 UTC, dae commented
I have no objections to a PR that allows selecting a different config per platform. Passing in an optional custom prefix/suffix on backend initialization might be the cleanest. It could be stored in CollectionState, and get/set_backup_limits could apply it to the key.

(FWIW, AnkiMobile currently shares config with the desktop, and no users have requested differently so far)

2022-11-09 20:42 UTC, mikehardy commented
FWIW on my part: if per-device backup count does not seem to be a high-demand feature and would delay this PR with some tangential work, I think we leave it synchronized at collection level across all devices and just note it as such in the manual or in the text associated with the control. That is "document it for the user, move on with existing functionality..."

2022-11-10 18:24 UTC, oakkitten commented
Updated to also have the v16 backup options. See updated screenshots in the first comment. Also:

* Added [this silly line](https://github.com/ankidroid/Anki-Android/compare/70ffee0a4df29054df6204848010b440f6f3c05f..0fbb545b78fc4ebbba28ac0ae1913aeb372b0682#diff-e56093ad07754ec925a017bc0b7676f4b30871df922fe55c6773baacdb54658cR394-R397). I wish Kotlin had [a file-private, or package-private, access modifier](https://youtrack.jetbrains.com/issue/KT-29227), then this nonsense wouldn't be necessary. Anyone's got a better idea?
* Simplified `findUnusedMediaFiles()`. It throws an exception if media check is required now.
* Fixed a small mistake in `findUnusedMediaFiles()` that prevented it from being cancelled fast.
* Made the box on the end of `TextWidgetPreference` grow along with text size rather than display size.

Please review the strings so I can turn this into a ready PR.

2022-11-10 18:27 UTC, oakkitten commented on AnkiDroid/src/main/res/xml/manage_space.xml
> +        android:summary="AnkiDroid will recreate collection backups later, up to the number specified below"
> I couldn't figure out how to make it stay big

Eventually I did figure out how to make it stay big.

2022-11-10 19:29 UTC, lukstbit commented
> Added [this silly line](https://github.com/ankidroid/Anki-Android/compare/70ffee0a4df29054df6204848010b440f6f3c05f..0fbb545b78fc4ebbba28ac0ae1913aeb372b0682#diff-e56093ad07754ec925a017bc0b7676f4b30871df922fe55c6773baacdb54658cR394-R397). I wish Kotlin had [a file-private, or package-private, access modifier](https://youtrack.jetbrains.com/issue/KT-29227), then this nonsense wouldn't be necessary. Anyone's got a better idea?

Maybe its the few hours of sleep from last night, but why do we need the new Queue type restriction/new withQueue method? I've seen that its used only once and that usage could be simplified(at least from what I saw):

`withQueue { CollectionManager.deleteCollectionDirectory() }`

vs 

`CollectionManager.deleteCollectionDirectory()`

where CollectionManager.deleteCollectionDirectory() is:

```
class CollectionManager {
    suspend fun deleteCollectionDirectory() {
        withContext(queue) { // queue being the old CoroutineDispatcher
            ensureClosedInner(save = false)
            getCollectionDirectory().deleteRecursively()
        }
    }
}
```

2022-11-10 20:56 UTC, oakkitten commented
You can do this, and it was done before. I don't like this design. I think stuff that changes threads is generally a high-level operation and belongs in the call site. The code that wants to delete the collection is one that must decide on the thread and atomicity and things like that. I also think it makes it easier to comprehend what's going on. Relevant: https://github.com/ankidroid/Anki-Android/pull/12371#discussion_r990797635

2022-11-11 13:07 UTC, lukstbit commented
> I don't like this design. 

This doesn't make your code more correct. The same with your answer to my remark above about using experimental language features.

> The code that wants to delete the collection is one that must decide on the thread and atomicity and things like that.

Your code does nothing of what you mention, it's just more convoluted.

> I also think it makes it easier to comprehend what's going on.

I don't think you could honestly say that (experimental language feature + over abstracting + language gimmick) is more readable and easier to maintain than a simple method on the CollectionManager. Yourself acknowledge this in the comment I quoted above. 

There's no need to answer, I don't think you're looking for a review and the functionality is important going further.

2022-11-11 15:02 UTC, oakkitten commented
Not sure what I said that warranted an answer like that. But since there's no need to answer, I guess I won't 🤷‍♀️

2022-11-11 18:00 UTC, mikehardy commented
> Not sure what I said that warranted an answer like that. But since there's no need to answer, I guess I won't

I think that's a shallow read @oakkitten - you two are having an interpersonal disagreement here and given you are both excellent contributors I think it bears examination, of which I am sincerely certain you are capable. I'm going to go out on a limb here and say that @lukstbit feels like you are *listening* (that is: you are generating comments in reply that clearly maintain a coherent thread) but you are not *hearing* (that is: you are not actually modifying anything in response.

You have made comment replies that are effectively saying "I like it this way and I'm doing it this way".

That's not collaborative. It will generate responses that sound shut-down in the same way @lukstbit's comment sounded shut down (that is: "I don't think you're looking for a review"). Because if you fail to alter anything in response to valid comments, it does not appear you are looking for a review. You are receiving review comments from other people also working hard on this project and your actions say to me "okay, I read your comment, but I'm not changing anything".

Specifically:

1- context receivers - you state that you prefer them and that in your anecdotal experience using kotlin experimental features has not had problems. I think each feature should be examined on it's own. For context receivers, I say don't: https://youtrack.jetbrains.com/issues?q=context%20receiver%20project:%20Kotlin%20Type:%20Bug / https://discuss.kotlinlang.org/t/why-are-context-receivers-still-experimental/25230

We are not a bleeding edge language-study project here. I prefer a boring no-surprises language use style, personally. We don't need to have our code all the sudden break with kotlin 1.8 because we are using an experimental feature based on preference vs necessity. Especially not when my first hits researching feature stability turn up a discussion warning and a pile of subtle language interaction bugs. That makes me nervous, and if context receiver usage is just a preference, I want to avoid it.

If there is a secondary concern that the use of the feature results in a design that another reviewer does not like, perhaps we avoid two things at once here: a possible code break as an experimental API changes shape / behavior *and* a resulting design that another reviewer doesn't like. Those things would have value, in a project where the other reviewer does a *lot* of review/merge work on top of individual PR contribution

2- emoji: we have no emoji in our UI other than when I throw it in our *changelog*. User interface elements should not have emoji. It doesn't matter if you like them more. That was a valid comment from Brayan. I hesitate to think what a screen reader would say on that dialog. Or a braille terminal? I don't actually know, but I don't want to find out the results are poor.

Similar to case 1 of context receiver, ignoring that feedback is non-collaborative.

You are doing fantastic work here. Your work on scoped storage in particular is personally appreciated. But we must collaborate to get things done here and that involves compromise. The goal here is to finish scoped migration, as fast as possible, but also together as a team as much as possible. Some parts will just barely work. Some parts will be cool. Some parts will look the way you like, some parts won't. Some parts I will push through quickly for strings, and hope for refactors after. But we need to work together, hear each other and actually compromise when code is really under review, *please* :pray:

2022-11-11 20:15 UTC, mikehardy commented
Sorry if this makes you uncomfortable but in general I try to only communicate open or closed in a way I wouldn't mind having written up on the front page top half of the newspaper, and your discourse in general appears (to me?) to follow the same pattern. So in an open source project I'll go for transparency first, with phrasing as benefit-of-the-doubtish as I can so that it all hopefully works. I appreciate your bearing with me.

That said, I'm not going to go around a bunch of times - I'll answer direct questions directly:

1- please remove the use of the experimental use of the context receiver

I may be overly conservative here but I'd rather not get a language surprise later

2- please remove the usage of emoji

We currently have zero emoji in our UI. I'm not 100% against having emoji in the UI. I have legitimate Accessibility concerns so I worry about their inclusion but they may be fun to have in certain places. Here's an article I read that had reasonable guidelines: https://uxcontent.com/accessible-content-design-for-emojis/ - which this PR would appear to follow, **but** I don't want to go from 0 to 1 on "using emoji" in the app and bikeshed on it as some tangent thing when what we really need is scoped storage to be done.

I think it matters what everyone thinks, and a debate is a good thing. But I am going to place a higher value on pragmatism then personal preference if review seems to be stuck / deadlocked - if sacrificing a preference unlocks an approval, and then the work is done....the work is done! The user does not care the preference and the user does care about new releases finally hitting the Play Store so I'm focused on that - unlocking review approvals and moving. That's my goal here.

it appears to me that with items 1 and 2 in this comment, you'll have 2 (maybe 3 - I was deferring string review *because* they weren't actually in resources yet...) approvals and we move forward. That's a win I think

2022-11-11 20:29 UTC, oakkitten commented
> 1- please remove the use of the experimental use of the context receiver
> I may be overly conservative here but I'd rather not get a language surprise later

I can do that, but this will be a considerable rewrite since some things are just not possible without them. I invite you to take a look at how much more readable they make the code.

> 2- please remove the usage of emoji
> but I don't want to go from 0 to 1 on "using emoji" in the app and bikeshed on it as some tangent thing

😔

2022-11-11 20:37 UTC, mikehardy commented
:bow:

2022-11-11 22:19 UTC, mikehardy reviewed
mostly just notes to extract, but a few string questions

2022-11-11 22:19 UTC, mikehardy commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="dialog_positive_delete_selected">Delete selected</string>
Material design doesn't offer much guidance on word count (https://m3.material.io/components/buttons/guidelines) but I have a preference for fewer words and fewer translations

Let's save the translation work - reduce the word count and remove this one

2022-11-11 22:19 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="check_media_summary">Delete unused medias from your collection.</string>
I think media is also plural? If you want an explicit plural you need "media files" I think.

```suggestion
    <string name="check_media_summary">Delete unused media from your collection.</string>
```

2022-11-11 22:19 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="delete_collection_confirmation">Are you sure you want to delete your whole collection and media?\n\nThis can\'t be undone.</string>
I've learned to avoid contractions where ever possible in multi-lingual apps. Many people won't have translations in their languages for some time, and may speak rudimentary English but contractions trip people, and do not provide much value IMHO

```suggestion
    <string name="delete_collection_confirmation">Are you sure you want to delete your whole collection and all media?\n\nThis cannot be undone.</string>
```

2022-11-11 22:19 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                    Size.Error(Exception("Not implemented"), widgetText = "🤷️")
:thinking: 

```suggestion
                    Size.Error(Exception("Not implemented"), widgetText = "Size is only calculated for Android 8 and higher")
```

...and, needs extraction? Not sure where this will show up or if it will

2022-11-11 22:19 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                setMessage("Media check required to find unused media files")
```suggestion
                setMessage("A media check is required to find unused media files")
```

and needs extraction?

2022-11-11 22:19 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                setTitle("Delete unused media files")
looks good, pending extraction?

2022-11-11 22:19 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                setTitle("Delete backups")
looks good, pending extraction?

2022-11-11 22:19 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                withProgress("Deleting backups…") {
looks good, pending extraction?

2022-11-11 22:19 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                setMessage("Are you sure you want to delete your collection, media, and backups?")
This one confuses me a little - message is deleting everything (col, media, backups) but title is just delete collection

if this truly deletes everything shouldn't it be more like "delete all app data" ? :thinking: 

```suggestion
                setTitle("Delete collection")
                setMessage("Are you sure you want to delete your collection, media, and backups?")
```

2022-11-11 22:19 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                withProgress("Deleting collection…") {
pending result of thought above, maybe "Deleting all app data..."

2022-11-11 22:19 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +            deleteEverythingDialogTitle = "Delete everything 🤯"
```suggestion
            deleteEverythingDialogTitle = "Delete everything"
```

2022-11-11 22:19 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                "Note that this will shut down this window."
I don't understand this part. Do you mean the whole application will shut down and restart? If so I think stating it like that is better than just mentioning the window

Something like "Note: the application will restart when the deletion is complete" or similar? Or I could be misunderstanding

2022-11-11 22:19 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                "Note that this will shut down this window."
Same reservation here - is it just the window or is it the app?

2022-11-11 22:19 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +        is Size.Calculating -> "Calcu-\nlating…"
I'm going to go with "good enough for now" on the split. When extracted it needs a good comment for translators explaining it is a very very narrow UI widget, and they should split their word 50/50 even if it is uncomfortable.

2022-11-11 22:19 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +        is Size.Calculating -> showSnackbar("Calculating…")
extract

2022-11-11 22:50 UTC, oakkitten commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="dialog_positive_delete_selected">Delete selected</string>
That's two opinions versus one, oh well Delete it is.

2022-11-11 22:51 UTC, oakkitten commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="check_media_summary">Delete unused medias from your collection.</string>
Oh I think this one is a bit stale and unused, also below

2022-11-11 22:53 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                    Size.Error(Exception("Not implemented"), widgetText = "🤷️")
Widget is that little box on the right-hand side of the preference, the text should be reeeal short, hence emoji. Not sure what to put here. Or maybe we should bother to calculate, it *is* possible

2022-11-11 22:55 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                setMessage("Are you sure you want to delete your collection, media, and backups?")
Settings, app cache, etc is not deleted.

2022-11-11 22:57 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                "Note that this will shut down this window."
The application is shut down. That's just like you clear all data from an app that has no manage space activity. Maybe “Note that this will shut down the app.”? Deleting is nearly instantaneous here

2022-11-11 23:00 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/preferences/screens/BackupLimitsPresenter.kt
> +                    is State.Error.NoCollection -> showSnackbar("Collection does not exist")
Yep these are user visible and to be extracted.

2022-11-11 23:01 UTC, oakkitten commented on AnkiDroid/src/main/res/xml/manage_space.xml
> +        android:summary="Delete collection, media, and backups. Settings are not deleted"
The higher powers spoke. No emojis 😭

2022-11-11 23:01 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +            deleteEverythingDialogTitle = "Delete everything 🤯"
The higher powers spoke. No emojis 😭

2022-11-11 23:03 UTC, oakkitten commented on build.gradle
> +                freeCompilerArgs = ['-Xjvm-default=all', "-Xcontext-receivers"]
It was decided that anything experimental is a no-no.

2022-11-11 23:13 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                    Size.Error(Exception("Not implemented"), widgetText = "🤷️")
:thinking:  Could simply go with `?` for now + defer task to follow-on, it won't affect strings nor will it affect structure of everything so seems like deferrable work

2022-11-11 23:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                setMessage("Are you sure you want to delete your collection, media, and backups?")
Hmm is there some word that captures "more than collection" but "less than everything". "App Data" maybe? I don't like that. Delete collection seems fine fine though, go with it - resolving except extraction needed of course

2022-11-11 23:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                withProgress("Deleting collection…") {
no great phrase I can think of, seems fine knowing what I know now

2022-11-11 23:15 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                "Note that this will shut down this window."
"Note: AnkiDroid will close when all data is deleted." ?

2022-11-11 23:18 UTC, mikehardy commented on AnkiDroid/src/main/res/xml/manage_space.xml
> +        android:summary="Delete images and other media that are not prefixed with _ and are not references by any notes"
It is hard for me to examine the strings when they are mixed in here vs extracted - I rip up and down the PR pretty quickly and these are all highlighted blue but only some are translatable.

Strings seem fine - maybe some hesitancy between terminating summaries with periods or not. What do we do normally?

2022-11-11 23:19 UTC, mikehardy commented on AnkiDroid/src/main/res/xml/preferences_backup_limits.xml
> +                You can restore from a backup and export your collection in the deck list menu."
Seems fine, anything I say would just be mushing words around for no real purpose - this seems to cover all the bases

But it terminates the summary with a period, other areas in this PR do not

2022-11-13 18:51 UTC, oakkitten commented on AnkiDroid/src/main/res/xml/manage_space.xml
> +        android:summary="Delete images and other media that are not prefixed with _ and are not references by any notes"
> It is hard for me to examine the strings when they are mixed in here vs extracted - I rip up and down the PR pretty quickly and these are all highlighted blue but only some are translatable.

Not sure I understood that

I think summaries must be without the period at the end. But a help preference is several paragraphs. It is *made* using a summary but it's semantically different, it's a piece of text, and I like it to follow the rules of text. Besides it's just weird to write several paragraphs and no period at the end kind of?

2022-11-13 19:02 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                    Size.Error(Exception("Not implemented"), widgetText = "🤷️")
Maybe “N/A” for now? And let me see how exactly problematic the calculation will be

2022-11-13 19:15 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                setMessage("Are you sure you want to delete your collection, media, and backups?")
Regarding the “Clear storage” action on Android, which appears to be deleting “User data” and “cache”. Depending on where the collection is located, we call that either:

* Delete everything (Delete collection, media, backups, and settings)
* Delete app data (Delete settings and other app data), or

The former minus the latter is

* Delete collection (Delete collection, media, and backups. App settings are not deleted)

Media files are collection, I guess? Maybe backups aren't, but I can't imagine a scenario where I'd want to delete the collection but not its backups.

2022-11-13 19:27 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                "Note that this will shut down this window."
I think the “when” clause is just not necessary. And I'm not a fan of “AnkiDroid” as from user perspective they are in “system settings for AnkiDroid” and not “in AnkiDroid”. That's why I went with “window” originally.

This warning is only needed so that the user is not confused when the activity suddenly disappears from under their finger. The user presses “Ok” in the dialog and what they are looking at just vanishes without animation. They could think this is a crash or something. (Ideally, you'd launch a separate process, but accessing collection from multiple processes is a bad idea)

2022-11-13 19:45 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                setMessage("Media check required to find unused media files")
Btw I got curious and I asked around on various English language channels and a third of people prefer the variant without “a”, another third with it, and the rest think that either variant is good heh.

2022-11-13 20:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                "Note that this will shut down this window."
"This action will close the application"? Avoids AnkiDroid, no when clause, ?

2022-11-13 20:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                    Size.Error(Exception("Not implemented"), widgetText = "🤷️")
N/A works for me

2022-11-13 20:15 UTC, mikehardy commented on AnkiDroid/src/main/res/xml/manage_space.xml
> +        android:summary="Delete images and other media that are not prefixed with _ and are not references by any notes"
I don't feel strongly about it, no change needed

2022-11-13 21:03 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                "Note that this will shut down this window."
While this closes both AnkiDroid and the settings app, I'm not sure if users regard the settings app as an “app” as well, so maybe it's best to avoid “app”/“application”?  Perhaps “This action will close settings” but then maybe on some devices the settings app stays?

2022-11-14 00:27 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                "Note that this will shut down this window."
We've been talking about this for two days and I've lost interest. Use the original string. Let's go.

2022-11-15 22:53 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                "Note that this will shut down this window."
I went “Note: this action will close the window” for now, your suggestion + my concern about app/AnkiDroid

2022-11-15 23:11 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +                "Note that this will shut down this window."
That looks good - comment is thorough for translators - thank you!

2022-11-15 23:14 UTC, oakkitten commented
Rebased onto v2.16alpha89 to resolve conflicts. Also,

* Strings extracted & deemojified. 😥 I didn't if having multiline entries in the XML is acceptable by AnkiDroid or not, so I went with a safer option. (I personally prefer this variant:
  ```xml
  <string>
      Text</string>
  ```
  But some tools (in)correctly display (and count) the whitespace.)

* Bye bye context receivers. 😭

* In async dialogs with multiple choice items, the button is disabled if no items are chosen.

* Added calculation of app data size for Android < Q. May require running gradle clean? The AIDL processor produces a warning since `IPackageStatsObserver` is using `PackageStats` that is deprecated. I am not sure if there's a proper way to suppress it. It doesn't pop up on every compile so maybe not an issue.

* There's a failing emulator test for this [resource file](https://github.com/oakkitten/Anki-Android/blob/15b9cc554d707c8b637188a747065be27a4562e1/AnkiDroid/src/main/res/layout/activity_manage_space.xml), the error is self-explanatory. (Why doesn't CI print the full traceback? Can we fix it?) I would prefer fixing the test here but I am not experienced with testing so I hope someone helps me out here.

  ```
  com.ichi2.anki.tests.LayoutValidationTest > ensureLayout[activity_manage_space][test(AVD) - 10] FAILED 
      android.view.InflateException: Binary XML file line #17 in com.ichi2.anki:layout/activity_manage_space: Binary XML file line #17 in com.ichi2.anki:layout/activity_manage_space: Error inflating class androidx.fragment.app.FragmentContainerView
      ...
      Caused by: java.lang.UnsupportedOperationException: FragmentContainerView must be within a FragmentActivity to use android:name="com.ichi2.anki.ui.windows.managespace.ManageSpaceFragment"
      ...
  ```

2022-11-15 23:14 UTC, mikehardy commented
Fresh code I am excited! So excited I just hit the little button asking for re-reviews, so we can hopefully get this in. Thank you @oakkitten

2022-11-17 13:35 UTC, lukstbit approved these changes
Changes LGTM, interesting use of aidl.
With the request to add @BrayanDSO 's comment to your TODO in the ManageSpaceActivity.

> Bye bye context receivers. sob

Thank you!

> There's a failing emulator test for this [resource file](https://github.com/oakkitten/Anki-Android/blob/15b9cc554d707c8b637188a747065be27a4562e1/AnkiDroid/src/main/res/layout/activity_manage_space.xml), the error is self-explanatory. (Why doesn't CI print the full traceback? Can we fix it?) I would prefer fixing the test here but I am not experienced with testing so I hope someone helps me out here.

My option here would be to ignore this layout. In LayoutValidationTest.initParameters():

```
// layouts that should be ignored by the layout inflation test
 // currently ignores layouts that use FragmentContainerView with a specified fragment
// name, these would normally fail the test as they require an activity to be inflated
// successfully
val ignoredLayouts = listOf(
    com.ichi2.anki.R.layout::class.java.getField("activity_manage_space").name
)
 ....
for (f in layout::class.java.fields) {
    if (nonAnkiFieldNames.contains(f.name) || ignoredLayouts.contains(f.name)) {
        continue
}
```
Fixing the test would require to provide an activity, which isn't needed for all other layouts(121) and if we start the activity with all the code inside it we might as well write tests specifically for that activity.

2022-11-18 00:18 UTC, oakkitten commented
Done and done. I went with a slightly different wording [and this](https://github.com/ankidroid/Anki-Android/compare/34b3c004928b801ff3591e59b23714c764594df1..5635e997c685374c3aff81a4780046eb1a5ce360#diff-8c5c9fecb5373470dce2fcc01a4959fe88eacdd26d255654c71b48291ac30bd7R103-R107), hopefully it's as correct.

(I don't suppose there's a ready way to skip (disable, ignore) a parametrized test the way you do it with regular tests?)

2022-11-18 00:39 UTC, mikehardy commented
> (I don't suppose there's a ready way to skip (disable, ignore) a parametrized test the way you do it with regular tests?)

I think in parameterized tests, in the actual test implementation you have the concrete value of the parameter at runtime, and there is a method that we call in some tests (I forget? just assert(conditional) maybe?)  so if you have some known value of the parameter you want to skip, you can make a conditional looking for that value of the parameter and skip execution if it matches

...or similar

2022-11-18 01:51 UTC, oakkitten commented
Ah yes, found it, if I say this, the run gets skipped (“121 passed, 1 skipped”)

```kt
@Test fun ensureLayout() {
    assumeFalse(resourceId in ignoredLayoutIds)
    ...
}
```

I'm not sure about changing to this since skipping inside a test feels wrong and makes the entire logic even more convoluted than it is. Ugh, so ugly. Where's the cute testing frameworks.

2022-11-18 15:43 UTC, mikehardy requested changes
Seems really well composed by my read. I had a large pile of very small things...

2022-11-18 15:43 UTC, mikehardy commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="card_info_ease_not_applicable" comment="TODO: Write comment">N/A</string>
Is this really a todo? Is this something that needs to change?

2022-11-18 15:43 UTC, mikehardy commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +        >@string/pref__delete_unused_media_files__title</string>
if there is a "no translation needed" marker, this one needs it

2022-11-18 15:43 UTC, mikehardy commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +        >@string/pref__delete_backups__title</string>
if there is a "no translation needed" marker, this one needs it

2022-11-18 15:43 UTC, mikehardy commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +        >@string/pref__delete_everything__title</string>
if there is a "no translation needed" marker, this one needs it

2022-11-18 15:43 UTC, mikehardy commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +        >@string/pref__delete_app_data__title</string>
if there is a "no translation needed" marker, this one needs it

2022-11-18 15:43 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +            withCol { BackupManager.deleteBackups(this, backupsToDelete) }
So, `BackupManager.deleteBackups` can throw an unchecked exception, which *I think* means that finally will execute here, but the exception itself will bubble up. This is called below without a catch for the specific (IllegalArgumentException), what happens if this is called and one of the backups isn't a valid backup, causing it to throw? Is that handled or would backup deletion always be an unrecoverable uncaught crash? I might be missing something

2022-11-18 15:43 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
> +    enum class ThemeChanged { Yes, No }
It appears the only place this is called does not consult the return value anyway, meaning it could be void and not matter?

2022-11-18 17:29 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
> +    enum class ThemeChanged { Yes, No }
It's used here https://github.com/ankidroid/Anki-Android/blob/24d1acb00ccb2aa41305ffa38ff0249df560358a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt#L126

2022-11-18 17:40 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
> +    enum class ThemeChanged { Yes, No }
Ah got it - I must have had the file collapsed. I'm fine with it anyway - works for me

2022-11-18 17:54 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
> +     *   Then, only functions that are also marked can be run inside the block:
Well I did create #12812, didn't put too many details in there because I was still thinking about how it should work. I'm still not sure. For now I'm thinking that probably:

* We need a `ReadWriteMutex` (can deadlock itself) or possibly a `ReentrantReadWriteMutex` (can't deadlock itself, but [some people really dislike reentrant things](https://groups.google.com/g/comp.programming.threads/c/tcrTKnfP8HI/m/me2K7_byNdgJ?hl=en&pli=1#:~:text=And%20so%20DCE,of%20a%20dare.));
* We need to designate things that can be run inside only the read or only the write part of the above mutex;
* We probably want to have an official way to do collection related I/O in a thread pool.

But I'm still not sure.

P.S. About reentrant mutexes (...mutices?) https://elizarov.medium.com/phantom-of-the-coroutine-afc63b03a131

2022-11-18 17:57 UTC, oakkitten commented on AnkiDroid/src/main/res/drawable/bg_preference_widget_text.xml
> +    <stroke android:width="1.5dp" android:color="#44888888" />
It's only used in this one place so why have it have a name? If someone ever wants to override it in another theme, extracting it should be easy.

I ran accessibility scanner, and it didn't complain. This is just background so it shouldn't matter for accessibility

2022-11-18 17:57 UTC, oakkitten commented on AnkiDroid/src/main/res/layout/preference_widget_text.xml
> +    android:minWidth="70sp"
Checked on min & max font sizes, no complaints.

2022-11-18 18:01 UTC, oakkitten commented on AnkiDroid/src/main/res/values/01-core.xml
> +        >@string/webview_crash_unknown</string>
I suppose that depending on the language some translators might want to translate these?

2022-11-18 18:05 UTC, oakkitten commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="card_info_ease_not_applicable" comment="TODO: Write comment">N/A</string>
In one commit I added this because you can't have two strings that say the same text without comments on both. When I later removed the other `N/A`, I forgot to revert this change. I'll revert it. (But it would be nice to have a comment here, still not sure what this means)

2022-11-18 18:14 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +            withCol { BackupManager.deleteBackups(this, backupsToDelete) }
The coroutine is launched using `launchCatchingTask`, so in a case of a crash you'll see an error dialog as usual.

https://github.com/ankidroid/Anki-Android/blob/5635e997c685374c3aff81a4780046eb1a5ce360/AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt#L376-L381

I suppose this try/finally approach might not be ideal from the architectural design viewpoint. At first, I tried to have it way up the call chain, in the above method, but I thought it made the code harder to read so I went with this.

2022-11-18 18:16 UTC, mikehardy commented on AnkiDroid/src/main/res/drawable/bg_preference_widget_text.xml
> +    <stroke android:width="1.5dp" android:color="#44888888" />
background can reduce contrast and fail accessibility, but if the scanner says it's good, it's good. If it is only used in one place I'm fine with YAGNI principle

2022-11-18 18:37 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +            withCol { BackupManager.deleteBackups(this, backupsToDelete) }
I'd say try-with-resources is mostly a cleanup thing, that would be Kotlin's `use {}`. *This* try/finally is mostly...
* Run _this_ code
* Regardless of the outcome, do _this_

I suppose *maybe* using `runCatching` would express the intent cleaner? As in

```kt
suspend fun deleteMedia(filesNamesToDelete: List<String>): Result<Unit> {
    val result: Result<Unit> = kotlin.runCatching {
        withCol { deleteMedia(this, filesNamesToDelete) }
    }

    launchCalculationOfSizeOfEverything()
    launchCalculationOfCollectionSize()
    launchSearchForUnusedMedia()

    return result
}
```

But who even uses `runCatching`.

2022-11-18 18:50 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
> +     *   Then, only functions that are also marked can be run inside the block:
That works for me - that one is pretty specific then. Need to handle other todos that definitely need extraction or agree / get consensus just leaving them in code as TODO is sufficient. That's case-by-case, I trust your judgement

2022-11-18 18:54 UTC, oakkitten commented on AnkiDroid/src/main/res/values/01-core.xml
> +        >@string/webview_crash_unknown</string>
In _this_ particular case I would rather rename `webview_crash_unknown` to `error__etc__unknown_error` since I hate having `webview_crash_unknown` in code that has absolutely nothing to do with web views. But as I understand renaming strings is a no-no, so I went with this. Now it's explicitly generic!

In other cases, where identifier names are not an issue, when the same English string refers to text used differently, “leaving open the possibility” might be worthwhile?

How about I add ` translatable="false"` to this string, and not to others?

2022-11-18 19:03 UTC, mikehardy commented on AnkiDroid/src/main/res/values/01-core.xml
> +        >@string/webview_crash_unknown</string>
Okay add translatable=false to this one
I don't like the might be worthwhile waffling - I think it will confuse translators then we'll have crowdin issues raised to provide context or ask what's going on. Be decisive, it needs translation or not...

2022-11-18 19:11 UTC, oakkitten commented on AnkiDroid/src/main/res/values/01-core.xml
> +        >@string/webview_crash_unknown</string>
I suppose Crowdin is smart enough to handle string references? I don't suppose it literally shows “@string/webview_crash_unknown”? If it does, maybe we can indeed be more decisive

2022-11-18 19:22 UTC, mikehardy commented on AnkiDroid/src/main/res/values/01-core.xml
> +        >@string/webview_crash_unknown</string>
I believe it is going to literally show that string, yes. I don't see anything that says it will decode indirections https://store.crowdin.com/android-xml

2022-11-18 19:32 UTC, oakkitten commented on AnkiDroid/src/main/res/values/01-core.xml
> +        >@string/webview_crash_unknown</string>
I checked and apparently Crowdin doesn't handle string references in any way. ¯\_(ツ)_/¯

I'll remove them and add comments

2022-11-18 20:26 UTC, oakkitten commented
Updated to:
* “references” → “referenced”
* `translatable="false"` for `error__etc__unknown_error`
* Remove references to other strings & add comments
* Remove ` comment="TODO: Write comment"`

And I'd like to ask the reviewers & testers to actually build & run the code and go through some deletions to make sure everything works. Things to look for:
* Test legacy & new backend (different backup preferences shown);
* Test with collection in legacy location and in scoped storage (depending on location you should see Delete app data or Delete everything);
* Would love to confirm that Delete app data/Delete everything size is the same number that is shown by the system (= size of User data + Cache) before Oreo & after;
*  Also pay notice to #12827.

2022-11-18 20:34 UTC, mikehardy commented
Yep - I'll review one more time then it's time to build + play with it, that's actually why I went ahead with alpha90 instead of cramming this in - a few days to try it over next week. But as soon as it's good merge+alpha91!

2022-11-19 04:23 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
> +    fun CoroutineScope.findUnusedMediaFiles(): List<File> {
checkMedia() in the backend performs the same task, but @oakkitten felt that the fact that it renames invalidly-named files at the same time was worth writing his own implementation.

2022-11-29 18:43 UTC, mikehardy commented
built this locally and installed it on API33 emulator, took this exception immediately when I did this:

1. `gh pr checkout 12765`
2. `./gradlew uninstallPlayDebug installPlayDebug` on API33 android emulator (so I am using legacy backend)
3. started the app, logged in to a "typical" account, and did a sync
4. hit task switcher, long-pressed app icon, chose app info
5. chose storage & cache from app info
6. chose "manage space" (which should open this new activity but instead...)

```
11-29 13:39:12.536 18801 18801 E ACRA    : ACRA caught a IllegalArgumentException for com.ichi2.anki
11-29 13:39:12.536 18801 18801 E ACRA    : java.lang.IllegalArgumentException: Invalid UUID string: 151F-3B1A
11-29 13:39:12.536 18801 18801 E ACRA    : 	at java.util.UUID.fromString(UUID.java:194)
11-29 13:39:12.536 18801 18801 E ACRA    : 	at com.ichi2.anki.ui.windows.managespace.FileUtilsKt.getUserDataAndCacheSizeUsingStorageStatsManager(FileUtils.kt:59)
11-29 13:39:12.536 18801 18801 E ACRA    : 	at com.ichi2.anki.ui.windows.managespace.FileUtilsKt.getUserDataAndCacheSize(FileUtils.kt:37)
11-29 13:39:12.536 18801 18801 E ACRA    : 	at com.ichi2.anki.ui.windows.managespace.ManageSpaceViewModel$launchCalculationOfSizeOfEverything$1$1.invokeSuspend(ManageSpaceFragment.kt:154)
11-29 13:39:12.536 18801 18801 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-29 13:39:12.536 18801 18801 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
11-29 13:39:12.536 18801 18801 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
11-29 13:39:12.536 18801 18801 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
11-29 13:39:12.536 18801 18801 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
11-29 13:39:12.536 18801 18801 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
11-29 13:39:12.536 18801 18801 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
11-29 13:39:12.536 18801 18801 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
11-29 13:39:12.536 18801 18801 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@fb1b799, Dispatchers.Main.immediate]

```

2022-11-29 19:33 UTC, oakkitten commented
I cannot run an emulator, so I won't be able to resolve this issue. Some relevant info:

`151F-3B1A` is indeed not a valid UUID. This appears to be [a platform bug](https://issuetracker.google.com/issues/62982912), perhaps an emulator-only bug.

There's [this question on SO](https://stackoverflow.com/questions/48589109/invalid-uuid-of-storage-gained-from-android-storagemanager). One answer recommends using `UUID.nameUUIDFromBytes(sv.getUuid().getBytes())`, well this won't crash but I don't see how it can work. But it has 5 upvotes so maybe it does? Another mentions `ApplicationInfo#storageUuid`, which is also mentioned in my comment above the crashing method:

https://github.com/ankidroid/Anki-Android/blob/c96d480f0cc988f5f98aa35e425870cf525a201f/AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/FileUtils.kt#L46-L50

This method gives us only one UUID. But in the documentation of `getExternalFilesDirs()`, for instance, we see, 

> Returns absolute paths to application-specific directories on all shared/external storage devices where the application can place persistent files it owns. These files are internal to the application, and not typically visible to the user as media.

So if “storage device” and “storage volume” have 1:1 correspondence, it appears that on some devices you can have app data on several UUIDs, and using only the primary UUID would yield incorrect results.

2022-11-30 00:42 UTC, mikehardy commented
Appears to be platform issue on any device with external storage of a specific flavor.

The stackoverlow answer with 5 upvotes has promise, I'll try it and report since I'm reproducing trivially

2022-11-30 01:25 UTC, mikehardy commented
It worked - I pushed a commit just to make sure that the known-working version (at least on my setup, I guess it needs a cross check on yours!) is the one we're debating. I don't feel proprietary about it all though - only goal is that the code I tested is under discussion - feel free to rebase it in however you like, and no need to get git-fussy with preserving attribution or anything. Let's just make it work

2022-11-30 01:49 UTC, mikehardy commented
- delete collection took a really long time for me - fairly sizable collection with regard to count of media files, on legacy or new backend / not scoped storage so it's just really slow IO. Maybe a follow-on PR to expand the modal to have number remaining vs number total to delete?

- after deleting app data, I immediately re-opened the manage space activity, now the top 3 (delete unused media / delete backups / delete collection) all say "Error" now in the calculation box? When I re-open AnkiDroid it re-prompts me for permissions (notification - I'm on API33 where that's required, and storage) so perhaps that's it? Yep, it repopulates after granting storage permission.

Those are minor things. Everything appears to *work* (I mean, "error" when there is no storage permission is not fantastic but it's not technically wrong either, just maybe not the most awesome label - it's not crashing or anything)

Maybe we defer those both to follow-on PRs? If so, and after you've mashed the UUID-workaround in how you like I'll do a final scan then merge this in ?

2022-11-30 01:49 UTC, oakkitten commented
A bit surprised that it works. I mean, that function expects a namespace
and a name but clearly the namespace isn't given so I wonder how the UUID
it provides is usable at all. Well I will check if it works for me...

P.S. Using stuff from SO requires attribution, including a link to the
question, question and answer author names and links to their profiles

On Wed, 30 Nov 2022, 01:25 Mike Hardy, ***@***.***> wrote:

> It worked - I pushed a commit just to make sure that the known-working
> version (at least on my setup, I guess it needs a cross check on yours!) is
> the one we're debating. I don't feel proprietary about it all though - only
> goal is that the code I tested is under discussion - feel free to rebase it
> in however you like, and no need to get git-fussy with preserving
> attribution or anything. Let's just make it work
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ankidroid/Anki-Android/pull/12765#issuecomment-1331528319>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AANBU7SPD7RARKSUBS2LQ3LWK2UKNANCNFSM6AAAAAARTJL7MA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-30 16:56 UTC, oakkitten commented
So I tested this on my device and it didn't crash and produced correct result. However this was only due to the fact that `volume.uuid` was `null` on my device and hence `StorageManager.UUID_DEFAULT` was used.

The question is, why did it not crash for you. `UUID.fromString()` produces a different result than `UUID.nameUUIDFromBytes()`, and according to the docstring of `queryStatsForPackage()`, it “throws `IOException` when the storage device isn't present.” Apparently, this is somewhat false. When given a bad UUID, `queryStatsForPackage()` simply returns 0. So I figure out this is what happened; you have two drives in an emulator, one has the default UUID, and the emulated SD card has the wrong UUID, and you get the correct stats from the former, and 0 from the latter, but it's actually 0 anyway.

I think it's very unlikely that `151F-3B1A` will actually work with `nameUUIDFromBytes` to produce a valid volume UUID. To test, you could try running `getExternalFilesDirs()` to see if it gives you an option of placing files on the SD card, 

**Edit** : looking at source code for `StorageManager.convert` I see this comment:

    if (isFatVolumeIdentifier(uuid)) {
        // FAT volume identifiers are not UUIDs but we need to coerce them into
        // UUIDs in order to satisfy apis that take java.util.UUID arguments.
        //
        // We coerce a 32 bit fat volume identifier of the form XXXX-YYYY into
        // a UUID of form "fafafafa-fafa-5afa-8afa-fafaXXXXYYYY". This is an
        // RFC-422 UUID with Version 5, which is a namespaced UUID. The UUIDs we
        // coerce into are not true namespace UUIDs; although FAT storage volume
        // identifiers are unique names within a fixed namespace, this UUID is not
        // based on an SHA-1 hash of the name. We avoid the SHA-1 hash because
        // (a) we need this transform to be reversible (b) it's pointless to generate
        // a 128 bit hash from a 32 bit value.
        return UUID.fromString(FAT_UUID_PREFIX + uuid.replace("-", ""));

And the first called method saying:

    /**
     * Returns true if {@code uuid} is a FAT volume identifier. FAT Volume identifiers
     * are 32 randomly generated bits that are represented in string form as AAAA-AAAA.
     */
    private static boolean isFatVolumeIdentifier(String uuid) {
        return uuid.length() == 9 && uuid.charAt(4) == '-';
    }

I think this is it!

2022-11-30 17:04 UTC, oakkitten commented
> delete collection took a really long time for me - fairly sizable collection with regard to count of media files, on legacy or new backend / not scoped storage so it's just really slow IO. Maybe a follow-on PR to expand the modal to have number remaining vs number total to delete?

It's pretty fast for me, I have around 3-5k media files so perhaps not too much. But even if it is slow, I suppose it will be too slow only on legacy backend. So I guess not many people will run into this, only those that have the new version but haven't yet upgraded.

> after deleting app data, I immediately re-opened the manage space activity, now the top 3 (delete unused media / delete backups / delete collection) all say "Error" now in the calculation box? When I re-open AnkiDroid it re-prompts me for permissions (notification - I'm on API33 where that's required, and storage) so perhaps that's it? Yep, it repopulates after granting storage permission.

That's it and if you tap on preferences that say error you should see a snackbar with details. Not much we can do here apart from asking for a permission, which feels awkward to do in a screen like this. And then again this situation is rare; you should be both using legacy storage, and having just deleted app data, or revoked storage permissions, to run into it.

2022-11-30 17:58 UTC, oakkitten commented
Pushed a commit that adds handling of FAT volume identifiers. **NOT TESTED**!

2022-11-30 19:29 UTC, mikehardy commented
I re-tested this with your latest commit adding the FAT-handling extensions and it works great on the same device that was reproducing the problem before. Read the commit - looks good to me. I think this is ready for a final review sweep then merge. oh my goodness !

2022-11-30 19:36 UTC, oakkitten commented
Does it work as in produces correct numbers from FAT partitions, or just doesn't crash?

2022-11-30 19:37 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
> +    fun CoroutineScope.findUnusedMediaFiles(): List<File> {
#12905

2022-11-30 19:38 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        if (Themes.updateCurrentThemeByUiMode(newConfig.uiMode) == Themes.ThemeChanged.Yes) {
#12906

2022-11-30 19:45 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
> +     *   Then, only functions that are also marked can be run inside the block:
leaving as TODO

2022-11-30 19:53 UTC, mikehardy commented
> Does it work as in produces correct numbers from FAT partitions, or just doesn't crash?

Not sure exactly how to test this :thinking: - it definitely does not crash.

I have `/storage/151F-3B1A` as a filesystem and I assume (dangerous) this is the location.
I go to there and `mkdir AnkiDroid` then `dd if=/dev/random of=foo.dat bs=1M count=100` to generate a file in i

I go to manage space and I don't see an extra 100M taken up, so I'm not sure exactly whether it is measuring correctly or not.

Any thoughts? I'm fine to pull this to a separate tracking issue as well, we need to land this one and move on, I think having AnkiDroid data on a FAT sdcard is going to be rare and is discouraged anyway (since FAT has limits on number of files per directory and is a classic source of errors for people that try to put data on external cards...)

2022-11-30 19:58 UTC, mikehardy commented
Current status:
- :heavy_check_mark: implementation seems to work, to me. No other testing reports from anyone else so I'll go with my direct experience
- :heavy_check_mark: I have peeled all the pending items from lots of people to various issues where necessary
- :grey_question: pending exploration on testing FAT external card storage space usage
- :hourglass:  need to do a final sweep of strings and resolve all my pending comments there - re-check strings in general
- :hourglass: do an i18n sync to clear real translations out, then land these

2022-11-30 20:07 UTC, oakkitten commented
For the purpose of the method we'd need to have some data in a folder that's deleted with the app. I don't know if the system creates such folders on FAT partitions at all. But you can check that maybe `getExternalFilesDirs()` gives you several results? If so, then maybe you can test by placing stuff inside both of the folders, and verifying that that the FAT codepath gives you correct numbers. If not, mhm, perhaps call `android.app.usage.StorageStatsManager#getTotalBytes(java.util.UUID)` on the resulting UUID to see if it's valid.

Also, I guess this needs to be tested on a device with storage volumes that produce non-FAT volume identifiers...

2022-12-02 17:42 UTC, mikehardy approved these changes
I don't think I have anything else blocking merge. I will peel a request to test FAT storage (low priority, may just stale close...)

How do you want to merge this? (yes I know you really want to fast-forrward it but...) rebase or squash? The commits do tell a story but with the leading commits being not-really-useful as independent items and at least one refactor, could be a squash. I lean towards squash but I will let you call it @oakkitten - let me know. I haven't checked it for commit-wise test passing and won't unless I hear you do not want squash. That may delay further as it will take a while to do and may require changes

Let me know please

2022-12-02 17:50 UTC, oakkitten commented
I'd prefer a merge/rebase, although I don't feel in any particular way about the commits that are not mine so I don't mind _them_ squashed

2022-12-03 12:57 UTC, mikehardy commented
21 commits so it took forever but I started the `./tools/test-commits.sh` run yesterday evening to make sure none of them would break git bisect and they all passed so it is good to go for rebase merge first time!

2022-12-03 12:57 UTC, merged

2022-12-05 15:22 UTC, oakkitten commented
> 21 commits so it took forever but I started the `./tools/test-commits.sh` run yesterday evening to make sure none of them would break git bisect and they all passed so it is good to go for rebase merge first time!

Hm, should be possible to create an action triggerable by a comment that runs tests for all commits in a matrix. I looked up "github actions dynamic matrix" and there are a few suggestions that seem to be quite useful.

2022-12-05 16:12 UTC, mikehardy commented
It is not something that needs to happen more often then once every few months, and it's not something I would want to wait on CI for in general (it would be so very slow) - so I'd let this one go - works well as a shell script locally, for me, for now

2022-12-05 16:53 UTC, oakkitten commented
> it would be so very slow

I mean if you run it in a matrix it'll take as long as checking one commit so 30 minutes-ish? But if it's needed so rarely then I guess it doesn't matter. Just had an idea