open collective link opening fix
ankidroid/Anki-Android pull request #12772
Opened 2022-11-02 17:08 UTC by criticalAY

## Pull Request template

## Purpose / Description
#12720 changes 

## Checklist

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-11-15 19:19 UTC, criticalAY commented
> 

I thought of it but I am not a html expert so didn't wanted to experiment but l will give it a try

2022-11-15 19:26 UTC, criticalAY commented
Don't we have to use css for that ?

2022-11-15 19:28 UTC, BrayanDSO commented
> Don't we have to use css for that ?

Yes. You can use CSS (and javascript) inside a HTML document

2022-11-15 19:29 UTC, criticalAY commented
lemme try

2022-11-15 21:13 UTC, criticalAY commented
I tried using js but doing so doesn't get the work done, href links doesn't work in that case 
`  /* The order of below javascript code must not change (this order works both in debug and release mode)
//                                 *  or else it will break in any one mode.
//                                 */`

there was this comment

2022-11-15 21:18 UTC, criticalAY commented
though I referred https://developer.android.com/develop/ui/views/layout/webapps/webview#EnablingJavaScript:~:text=All%20links%20the,of%20Activity. for the usage of this methods and found it relevant

2023-01-15 06:20 UTC, criticalAY commented
David could you please take a glimpse whenever you are free @david-allison

2023-01-15 22:11 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
> +                        }
Thoughts on using `openUrl` here instead?

2023-01-15 22:11 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
> +                        if (request?.url.toString() == "https://docs.ankidroid.org/changelog.html" || request?.url.toString() == "https://github.com/ankidroid/Anki-Android/commits/main") {
This could do with a comment explaining why we're special-casing two URLs.

We may want to extract these to constants to ensure the logic here is consistent if the values change

2023-01-16 08:08 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
> +                        }
I did but the official doc suggest not using that while returning true as this unnecessarily cancels the current load and starts a new load with the same URL

2023-01-16 08:52 UTC, criticalAY commented
the test:

https://user-images.githubusercontent.com/48384865/212636323-8e78e9ad-6574-41c7-9204-110810c36b82.mp4

2023-02-15 19:18 UTC, criticalAY commented
@david-allison could you review this PR as it has been pending for months now

2023-02-15 19:48 UTC, david-allison requested changes
Needs to check if the user has a web browser:

https://github.com/ankidroid/Anki-Android/blob/ffa4c3be55ea869ef5fc4368ee5c7e54f32906d4/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt#L422

2023-02-16 19:22 UTC, david-allison approved these changes

2023-02-17 19:13 UTC, mikehardy approved these changes
Nice

2023-02-17 19:31 UTC, merged