Search View was added to Card Editor Page for Fields.
ankidroid/Anki-Android pull request #12773
Opened 2022-11-02 17:57 UTC by raehat

(Search View was implemented in NoteEditor.kt)

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_
As mentioned by a regular user, searching for fields in editor was a difficult task sometimes, so I have implemented search view in Card Editor which can search for fields using both, search by field label and search by field content.

## Fixes
Fixes _Link to the issues._
Implemented Search View in Card Editor for Fields, can be used to search for both, field labels and field content

## Approach
_How does this change address the problem?_
Users don't have to scroll and find the desired field manually, they can simply search for the same.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)
Physically tested each and every test case

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [✓] You have a descriptive commit message with a short title (first line, max 50 chars).
- [✓] You have commented your code, particularly in hard-to-understand areas
- [✓] You have performed a self-review of your own code
- [✓] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [✓] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-11-02 18:00 UTC, raehat commented
https://user-images.githubusercontent.com/77321971/199565943-00522bc7-46ea-4bb9-bb9e-f4ef193cd453.mp4

Demonstration
please maintainers check the PR and suggest me any possible changes

2022-11-02 18:05 UTC, raehat commented
Also, I have added some strings, and I have no idea how to translate them to other languages for the project. It will be helpful if someone guides me for the same

2022-11-02 19:12 UTC, oakkitten requested changes
This is pretty neat! I have a few requests for overall changes before I do a full review.

Also, in the video I see that the input is underlined, would be nice to remove that underline.

Also, there is a lot of blinking when the fields change. Fields will blink even though they stay at the same place. Would be nice to investigate why they are blinking, and whether this can be prevented.

When searching for field contents, it would be nice to highlight the words inside text. We could also highlight words when the editor is open from the browser and there was a search for words.

Does interacting with the fields cancel the search? I imagine that when I have finally found the field, and tap on it, all fields are shown, but the one that was found is focused.

2022-11-02 19:12 UTC, oakkitten commented on AnkiDroid/src/main/res/values/strings.xml
> +    <string name="search_for_field_label">Search for Field label</string>
Use sentence capitalization. Also I suggest “Search in field labels” & “Search in field contents”

2022-11-03 00:07 UTC, raehat commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                if (sharedPreferences.getString("search_options", "fieldlabel") == "fieldlabel") {
enum uses extra space so I prefer not to use it if the task is small, also I forgot to look for any default shared preferences if used. However I will adhere to the coding practice mentioned and make the required changes.

2022-11-03 00:08 UTC, raehat commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        menu.findItem(R.id.search_options).setOnMenuItemClickListener {
will make the required changes.

2022-11-03 00:12 UTC, raehat commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        val searchViewFieldSearch: SearchView = actionViewFieldSearch.actionView as SearchView
"searchviewFieldSearch" as in SearchView of menuitem "FieldSearch" (short for field_search_view_note_editor). I'll change it and make it more understandable for other contributors.

2022-11-03 00:13 UTC, raehat commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +    private fun populateEditFields(type: FieldChangeType, editModelMode: Boolean, filterQueryByFieldName: String?, filterQueryByFieldContent: String?) {
I'll change it

2022-11-03 00:13 UTC, raehat commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            if (editLineView.name!!.lowercase().contains(filterQueryByFieldName!!.lowercase()) &&
will do the same

2022-11-03 00:13 UTC, raehat commented on AnkiDroid/src/main/res/values/strings.xml
> +    <string name="search_for_field_label">Search for Field label</string>
will do the same

2022-11-03 00:18 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                if (sharedPreferences.getString("search_options", "fieldlabel") == "fieldlabel") {
Enums are cheap and when R8 is fully enabled they should be practically free.

By the way I am only a contributor just yourself, so please take what I say as a suggestion and not a hard requirement.

2022-11-03 00:24 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        val searchViewFieldSearch: SearchView = actionViewFieldSearch.actionView as SearchView
I'd say something along

```kt
val searchMenuItem = menu.findItem(R.id.menu_search)
val searchView = searchMenuItem.actionView as SearchView
```
because

* I generally like to prefix all menus with `menu_`
* `searchMenuItem` because `findItem` returns a `MenuItem`, and it's okay to *suffix* with a type I think
* `searchView` for simplicity as there's only one

2022-11-03 17:41 UTC, raehat commented
@oakkitten most of the changes mentioned I was able to implement, however
1) I noticed that in Card Editor, a linear layout is used in which views are added. Now, to perform search, this linear layout is refreshed every time which causes the blinking effect. If a recycler view was used, this problem could have been avoided.
I am working on this problem, and I'll appreciate some suggestions from your side
2) 

> I imagine that when I have finally found the field, and tap on it, all fields are shown, but the one that was found is focused.

If searchview is collapsed, the linear layout reloads, and focus from the selected field is lost

2022-11-03 17:42 UTC, raehat commented
Rest of the changes were pushed

2022-11-03 22:48 UTC, oakkitten requested changes
> Now, to perform search, this linear layout is refreshed every time which causes the blinking effect. If a recycler view was used, this problem could have been avoided.

I see. Blinking is annoying but as far as I am concerned this is still an improvement, and move to recycler view can be done in another PR

> If searchview is collapsed, the linear layout reloads, and focus from the selected field is lost

Yeah but I think that when you tap on a field to edit, the search should close as well. This will solve one of the issues below too. The focus should be set after layout reload or something... Or if moving to recycler view is easy enough, do that first

I ran the code and there are some crashes. Also,
* Highlighted text (very cool!) has too bright a background in dark mode (yellow bg + white text)
* Only the first match is highlighted, e.g. if you search for `o` in `moloko`, you'll get `m[o]loko`
* Since the highlighting stays when you tap on field, you can type *in* the highlighted text
* When searching, ← should cancel search I think? Not offer to close the editor.
* When searching, × deletes text BUT stays, and second tap on it closes the search. I dunno if this is how it is supposed to work but it sounds weird to me

2022-11-03 22:48 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            if (editLineView.name!!.removeNonSpacingMarks().contains(queryByFieldName!!.removeNonSpacingMarks(), ignoreCase = true) &&
This throws NPE for me

                 Caused by: java.lang.NullPointerException
                 	at com.ichi2.anki.NoteEditor.populateEditFields(NoteEditor.kt:1408)
                 	at com.ichi2.anki.NoteEditor.setNote(NoteEditor.kt:1756)
                 	at com.ichi2.anki.NoteEditor.onCollectionLoaded(NoteEditor.kt:397)
                 	at com.ichi2.anki.AnkiActivity.startLoadingCollection(AnkiActivity.kt:373)
                 	at com.ichi2.anki.NoteEditor.onCreate(NoteEditor.kt:291)

2022-11-03 22:48 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +    private lateinit var searchMenuItem: MenuItem
If a variable is used ONLY in one method, it's best to keep it local

2022-11-03 22:48 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        }
I say this is good enough for now, to be refactored later along with other preferences

2022-11-03 22:48 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            }
I think that instead of manually checking/unchecking checkboxes we can go for radio buttons. See here https://stackoverflow.com/questions/10768419/how-to-create-a-submenu-with-radio-buttons-in-android

2022-11-03 22:48 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                spannableString.setSpan(BackgroundColorSpan(Color.YELLOW), start, end, 0)
This crashes when I use e.g. a letter `G` when the text has only `g`'s

                 java.lang.IndexOutOfBoundsException: setSpan (-1 ... 0) starts before 0
                 	at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:497)
                 	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:197)
                 	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:184)
                 	at android.text.SpannableString.setSpan(SpannableString.java:60)
                 	at com.ichi2.anki.NoteEditor.populateEditFields(NoteEditor.kt:1419)
                 	at com.ichi2.anki.NoteEditor.access$populateEditFields(NoteEditor.kt:114)
                 	at com.ichi2.anki.NoteEditor$onCreateOptionsMenu$1.onQueryTextChange(NoteEditor.kt:922)

2022-11-03 22:48 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            .replace("\\p{Mn}+".toRegex(), "")
This comment https://stackoverflow.com/questions/3322152 suggests `"\\p{M}"`. I also wonder if this will scale well, that is what if you have a lot of fields with a lot of text, how fast would this work? Maybe cache normalized strings or something

2022-11-03 22:48 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                val end = start + queryByFieldContent.length
There will be a problem here; you are looking in a normalized string without diactrics, but setting the span in a string that might have them... Maybe normalizing isn't the best way here. Perhaps use `Collator`? I don't know

2022-11-06 06:10 UTC, raehat commented
I will push changes in a week or so, sorry for delay I am a bit overwhelmed with uni work.

2022-11-14 11:08 UTC, raehat commented
I will push changes in 2 weeks now, my semester finals have started, sorry for delay

2022-12-09 15:46 UTC, raehat commented
> Yeah but I think that when you tap on a field to edit, the search should close as well. 

@oakkitten well, I don't understand the flow for this one. What exactly should happen when I click on a field? If search closes, then the selected field is also lost. If you can tell me the desired flow here, I will implement it right away. I think other issues I have managed.
I think this can be done quickly.

2022-12-09 19:07 UTC, raehat commented
@oakkitten also if I simply scroll down programmatically when searching, what about the second item in search? It can be a few fields below the first item.

2022-12-10 19:08 UTC, oakkitten commented
> What exactly should happen when I click on a field?

*I* think that when you tap on a field from the search, you should see the same effect as though you tapped on a field not from the search. Basically, all the fields that were filtered out should reappear. The field that was tapped should not change position.

This is just an opinion; perhaps someone will say that they think that search must be always dismissed manually. I just think that dismiss on field tap is a more like what the users are going to expect.

> also if I simply scroll down programmatically when searching, what about the second item in search? It can be a few fields below the first item.

I suppose you can have up and down arrows such as you can see in your browser app when searching for text in a page. And you can highlight the matching fields with `ItemDecoration`. 

I am not entirely sure which of the two approaches, filtering fields or scrolling, I would prefer.

2022-12-10 22:02 UTC, raehat commented
@oakkitten I'll keep these points in mind, and push changes.

2023-01-09 16:57 UTC, raehat commented
@oakkitten I have tried to implement some of the features you told, but I have come to a realization that we can't implement something like what you have suggested completely without shifting to recycler view. I think we can shift to recycler view and then work on something like this, because then we will be able to implement the Search feature without blinking too, and also it's just a good idea to shift to recycler view I think.
Please give me your suggestion and I'll work on the same.

2023-01-09 16:58 UTC, raehat commented
@oakkitten for now, what I have pushed is just a proof of concept for how search view may without shifting to recycler view. It is not completely implemented though. I'll share screen recording too.

2023-01-09 17:19 UTC, raehat commented
Uploading video0901.mp4…

2023-01-09 17:28 UTC, raehat commented
https://user-images.githubusercontent.com/77321971/211369427-30d42c1e-37c9-45a9-8fb0-79d1dfee5d53.mp4

2023-02-28 14:37 UTC, closed without merging