Fix #12777
ankidroid/Anki-Android pull request #12786
Opened 2022-11-05 23:06 UTC by Subhadiptech

As intended, I have followed the first preference as suggested by @mikehardy  and @Arthur-Milchior  and made the following changes.

2022-11-06 00:13 UTC, Arthur-Milchior commented
Thanks @Subhadiptech 

A few requests. 
As you may see above, the "Code quality checks /lint debug" fails
```
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/03-dialogs.xml:101: Error: The resource R.string.storage_full_title appears to be unused [UnusedResources]
    <string name="storage_full_title">Storage full</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/03-dialogs.xml:104: Error: The resource R.string.storage_almost_full_title appears to be unused [UnusedResources]
    <string name="storage_almost_full_title">Storage almost full</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/04-network.xml:69: Error: The resource R.string.sync_write_access_error_on_storage appears to be unused [UnusedResources]
    <string name="sync_write_access_error_on_storage">The downloaded file couldn’t be saved to your storage. Either the storage is mounted read-only or there isn’t enough space.</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/09-backup.xml:24: Error: The resource R.string.backup_deck_no_storage_left appears to be unused [UnusedResources]
    <string name="backup_deck_no_storage_left">Backup not saved. Not enough space left on Storage. Lower the backup depth or remove some other files.</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/09-backup.xml:27: Error: The resource R.string.storage_warning appears to be unused [UnusedResources]
    <string name="storage_warning">Less than %d MB space on your storage left.\nFree some space to avoid data loss.</string>
```

Could you please correct that. 
https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#lint explains how to run it on your device.
Essentially, it means that since a string is not used anymore, you should delete it from `values` directory.

(That also means you don't need to add comments to explain the difference)

As discussed on Discord, you should use those new strings in the code. The goal being for the user to see them.

One last remark. I'd appreciate if the commit message and the PR message could explains in plain English what is being done.
The goal is that devs can look at the history of the file, see when a line was introduced, and what was the reason. Devs won't know what bug number 12777 is. However, if they read 
> Remove "SD cards" from strings

they'll probably get a guess, at least understand that it's just changing a string value; so if they are looking for a bug, know that it was probably not related to this change.

2022-11-06 00:17 UTC, Subhadiptech commented
Ya, I have used the strings now. Just changing JDK version and pushing

2022-11-06 01:48 UTC, Arthur-Milchior approved these changes
Thanks

2022-11-06 01:49 UTC, Arthur-Milchior commented
It would be nice if you could put all of this in a single commit, and put a descriptive commit message, as I explained above. Don't hesitate to force push on your own branch

2022-11-06 01:59 UTC, Subhadiptech commented
@Arthur-Milchior I will create new branch from next time. Just wanted to ask how to merge all the commits into a single commit?

2022-11-06 22:16 UTC, Arthur-Milchior commented
You answered "sure", so I guess I'll wait for this last change to be done.

2022-11-06 23:40 UTC, david-allison requested changes
Thanks! Couple of nitpicks

2022-11-06 23:40 UTC, david-allison commented on AnkiDroid/src/main/res/values/09-backup.xml
> +    <string name="backup_deck_no_storage_left">Backup not saved. Not enough space left on Storage. Lower the backup depth or remove some other files.</string>
```suggestion
    <string name="backup_deck_no_storage_left">Backup not saved. Not enough space left on your storage. Lower the backup depth or remove some other files.</string>
```

2022-11-06 23:40 UTC, david-allison commented on AnkiDroid/src/main/res/values/04-network.xml
> +    <string name="sync_write_access_error_on_storage">The downloaded file couldn’t be saved to your storage. Either the storage is mounted read-only or there isn’t enough space.</string>
```suggestion
    <string name="sync_write_access_error_on_storage">The downloaded file couldn’t be saved to your storage. Either the storage is read-only or there isn’t enough space.</string>
```

2022-11-08 13:55 UTC, david-allison commented
Pending squash merge and sync from https://github.com/ankidroid/Anki-Android/actions/runs/3420021758

2022-11-09 20:39 UTC, mikehardy approved these changes
Looks good to me - and I've just cleared strings out via crowdin sync + merged translations PR

2022-11-09 20:39 UTC, merged