CropException fix
ankidroid/Anki-Android pull request #12816
Opened 2022-11-11 14:12 UTC by criticalAY

## Pull Request template
Fixes #12768

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-11-11 15:41 UTC, mikehardy requested changes
This could be correct but you've deleted the entire PR template.
I want to know what the motivation is for this PR (a brief synopsis of the issue perhaps)
I want to know *why* this is the correct fix
I want to know *how* you test this to know that this is the correct fix

Something like "Crop exceptions were generating lots of exception reports in ACRA and it seemed most of them were not actionable"

Along with "It turns out that if you do XYZ then you get a CropException because of ABC, but there is nothing we can do about it. However if you do JKL it is a real exception of type FOO so we still want to pay attention to those"

Along with "So based on that, this PR just logs exceptions of type CropException but for the rest we still send a report via ACRA"

2022-11-11 15:50 UTC, criticalAY commented
> This could be correct but you've deleted the entire PR template. I want to know what the motivation is for this PR (a brief synopsis of the issue perhaps) I want to know _why_ this is the correct fix I want to know _how_ you test this to know that this is the correct fix
> 
> Something like "Crop exceptions were generating lots of exception reports in ACRA and it seemed most of them were not actionable"
> 
> Along with "It turns out that if you do XYZ then you get a CropException because of ABC, but there is nothing we can do about it. However if you do JKL it is a real exception of type FOO so we still want to pay attention to those"
> 
> Along with "So based on that, this PR just logs exceptions of type CropException but for the rest we still send a report via ACRA"

Will do that

2022-11-11 21:00 UTC, mikehardy requested changes
Huh - that's a very terse exchange on the upstream repo: https://github.com/CanHub/Android-Image-Cropper/issues/527 - but ... it does not seem like it is useful for us to do anything with the exception at the moment.

I proposed a tiny change where we just also log the exception in the Timber call, just in case

What do you think?

2022-11-11 21:00 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
> +                    Timber.i("CropException caught")
I think we could at least log the exception with the Timber message, that way since it is 'i' level it will show up even in release mode builds, and if someone is affected by this they can generate a manual exception report that *should* still have the exception in it from logcat, allowing us to still investigate in depth with an affected user in case we are incorrect in the analysis that these do not matter

```suggestion
                    Timber.i("CropException caught, seemingly nothing to do", error)
```

2022-11-11 21:07 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
> +                    Timber.i("CropException caught")
ok will amend it

2022-11-11 21:11 UTC, criticalAY commented
> Huh - that's a very terse exchange on the upstream repo: [CanHub/Android-Image-Cropper#527](https://github.com/CanHub/Android-Image-Cropper/issues/527) - but ... it does not seem like it is useful for us to do anything with the exception at the moment.
> 
> I proposed a tiny change where we just also log the exception in the Timber call, just in case
> 
> What do you think?

I am also putting a comment there so when in future Canhub gets rid of this issue or finds a way to handle it correctly then we can remove this particular condition

2022-11-11 21:28 UTC, mikehardy commented
This is a small enough change it can work as a test bed for git commands.
Let's get this thing rebased and squashed down to a single clean commit so we can start having clean commit histories on your PRs.

There are GUIs that do this, but I use git from the command line. Here are the commands I would run:

```bash
git rebase -i HEAD~3   # "hey git, let's interactively rebase the last three commits"
# this will open your configured text editor, probably vi(?) with "pick" in front of each commit
# delete pick from the second and third commits and put "s" instead, for "squash"
# save and exit the editor, now git will try to follow your instructions
# you should get a commit message edit window where you are prompted to combine all the messages into one, do that, save+exit
git push --force-with-lease
```

In this case since it's just a squash of 3 commits into 1 it's really easy, mostly just asking git to do it then editing the message, then pushing the result back out

Try it out and let's see how it looks.

2022-11-11 21:29 UTC, mikehardy approved these changes
This looks great to me, and I've looked into the upstream repo and everything.
Only pausing now (but with approval on the code) to see if we can get a rebased version of the commits for practice

2022-11-11 22:33 UTC, criticalAY commented
I think I messed up the rebasing :(

2022-11-11 22:43 UTC, criticalAY commented
@mikehardy finally did it, Thanks!

2022-11-11 22:57 UTC, mikehardy reviewed
My only quibble now is that the commit message itself contains no useful information, it says

"squash merge commits" when it should say something like:

"stop logging exception reports for CropExceptions" as a title with a message internally like "They were logged previously for analysis to see if they were useful. They do not appear useful now that we have seen them. Logging them to ACRA just seems like clutter"

This can be done with a `git rebase -i HEAD~1` and the "reword" interactive rebase command. It will bring up an editor where you can rewrite the commit title + message to whatever you want.

Then you have to force push again of course. But you'll be good at it after this! It's a really useful skill

2022-11-11 23:05 UTC, criticalAY commented
Thanks! and done

2022-11-11 23:21 UTC, mikehardy approved these changes
A thing of beauty :-)

2022-11-12 18:23 UTC, lukstbit requested changes
To answer your question from Discord, this is a bug I introduced when I migrated the library to use the new activity result APIs :(. Your code works, but it will swallow all exceptions related to cropping not just the one thrown when user hits back. So I'm proposing these changes:

```
// condition can be removed if #12768 get fixed by Canhub
if (cropResult.error is CropException.Cancellation) {
     Timber.i("Crop cancelled by user, seemingly nothing to do")
} else {
      CrashReportService.sendExceptionReport(error, "cropImage threw an error")
}
```

This way we only ignore the Cancellation exception(user hits back), but we send a report for the other exceptions(like FailedToDecodeImage or FailedToLoadBitmap).

2022-11-12 18:36 UTC, mikehardy commented
> CropException.Cancellation

This is even better, I did not realize there were sub-exceptions / finer ways to differentiate. I like it

2022-11-12 18:40 UTC, criticalAY commented
> (cropResult.error is CropException.Cancellation)

Thanks for responding, I caught all the cropping exceptions true and this can further be simplified thankyou for pointing that out

2022-11-12 18:54 UTC, criticalAY commented
> > CropException.Cancellation
> 
> This is even better, I did not realize there were sub-exceptions / finer ways to differentiate. I like it

I didn't know that I can use the crop result itself to refine it, I tried though but wasn't able to do that and Luksbit suggested the exact thing. Kudos to him :)

2022-11-13 06:13 UTC, lukstbit approved these changes
Nice!

2022-11-13 06:14 UTC, merged