scope function
ankidroid/Anki-Android pull request #12811
Opened 2022-11-10 18:10 UTC by criticalAY

## Pull Request template
kotlin cleanup scope function

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-11-10 19:38 UTC, lukstbit requested changes

2022-11-10 19:38 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +        fieldController.let {
While `let {}` works, I think it's better to use `apply {}` as this will bring `fieldController` in scope(no need to use the `it` parameter, simply call the setters) and also reads better as we are applying some changes to the property.

2022-11-10 19:42 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +        fieldController.let {
I thought of both methods but decided to go with `let {}`

2022-11-10 19:43 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +        fieldController.let {
but sure we can avoid the `it`

2022-11-10 19:49 UTC, criticalAY commented
`let { }` worked fine though for this function but true that is puts `extra` it and which can be avoided by using apply so I have changed `let { }` with `apply { }`

2022-11-10 19:53 UTC, lukstbit approved these changes
Thanks!

2022-11-11 00:23 UTC, david-allison approved these changes

2022-11-11 00:23 UTC, merged

2022-11-11 00:23 UTC, david-allison commented
Another one bites the dust, thanks!