kotlin cleanup
ankidroid/Anki-Android pull request #12836
Opened 2022-11-16 21:04 UTC by criticalAY

## Pull Request template
Kotlin Cleanup 

## Purpose / Description
Renaming variable and using scope function as kotlin cleanup

## Fixes

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-11-17 16:46 UTC, lukstbit requested changes

2022-11-17 16:46 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckOptionsActivity.kt
> +                    "name" to deck.getString("name")
This code is not equivalent with the original. `"name" to deck.getString("name")` simply creates a Pair<String, String> and it doesn't update the mValues map. You can see this as you can do : 

`val unusedByMap = "name" to deck.getString("name")`

Use the set() method as that is the one that enables the previous bracket notation:

2022-11-17 16:46 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckOptionsActivity.kt
> +                    "newSteps" to StepsPreference.convertFromJSON(newOptions.getJSONArray("delays"))
Same as above with set(), this time on a JSONObject.

2022-11-17 16:46 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckOptionsActivity.kt
> +                    "lapSteps" to StepsPreference.convertFromJSON(lapOptions.getJSONArray("delays"))
Same as above

2022-11-17 16:46 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckOptionsActivity.kt
> +                        "reminderEnabled" to reminder.getBoolean("enabled").toString()
I would revert this change and the one immediate bellow this.
While apply {} looks nice I think it's overkill when you have only two calls on the same object. You're basically doubling the previous number of lines of code with questionable increase in readability.

2022-11-17 16:46 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +        resultData.apply {
`val resultData = Intent(). apply {}`

2022-11-17 16:46 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
> +                type = newOrLearningList.shuffled().first()
See above comment on using apply with only two calls on the same variable.

2022-11-17 16:46 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
> +            card.apply {
See above comment on using apply with only two calls on the same variable.

2022-11-17 16:46 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
> +        field.apply {
`val field = ImageField.apply {}`

2022-11-17 16:46 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
> +        field.apply {
`val field = MediaClipField().apply {}`

2022-11-17 16:46 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
> +        val fileImage = directory.newFile("test_image.png")
Revert this change and keep the original name.

2022-11-17 16:46 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
> +        basicNote.apply {
`val basicNote = Note(testCol!!, testModel).apply {}`

2022-11-17 17:27 UTC, criticalAY commented on AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
> +        val fileImage = directory.newFile("test_image.png")
There was a annotation to rename it?

2022-11-17 17:43 UTC, criticalAY commented on AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
> +        val fileImage = directory.newFile("test_image.png")
and I think it is correct as per naming convention no?

2022-11-19 07:04 UTC, lukstbit requested changes

2022-11-19 07:04 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckOptionsActivity.kt
> +                    set("name", "name")
Why "name" for the second parameter when originally it was deck.getString("desc")?
The same for the following two calls.

2022-11-19 07:04 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
> +        val fileImage = directory.newFile("test_image.png")
Leave it as it is. With "annotation to rename it" I think you're referring to the type raised by the IDE, but that can be ignored.

2022-11-19 07:11 UTC, criticalAY commented on AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
> +        val fileImage = directory.newFile("test_image.png")
There was a kotlin cleanup annotation mentioning the renaming

2022-11-19 07:14 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckOptionsActivity.kt
> +                    set("name", "name")
mistakenly did that

2022-11-19 07:16 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
> +        val fileImage = directory.newFile("test_image.png")
@criticalAY You're right, I completely missed the class annotation. The file should be renamed.

2022-11-19 11:09 UTC, lukstbit approved these changes
Thanks!

2022-11-20 12:15 UTC, BrayanDSO requested changes

2022-11-20 12:15 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
> +                }
```kotlin
val model = srcModel.deepClone().apply {
...
}
```

2022-11-20 12:15 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
> +                }
ditto

2022-11-20 12:15 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
> +        }
Personally, I find the previous code easier to read. No need for the change

2022-11-20 16:15 UTC, BrayanDSO approved these changes
LGTM. Thanks!

2022-11-20 16:15 UTC, merged