Used val instead of var
ankidroid/Anki-Android pull request #12831
Opened 2022-11-15 11:10 UTC by SanjaySargam

## Pull Request template
Used `val` instead of `var`

## Fixes
Bug #11450 

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-11-15 12:39 UTC, divyanshdxn commented
@SanjaySargam unit tests are failing with `java.lang.StackOverflowError`

2022-11-15 13:47 UTC, SanjaySargam commented
> @SanjaySargam unit tests are failing with `java.lang.StackOverflowError`

Ok I will resolve

2022-11-15 13:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
>              val m = ANONYMOUS_CLASS.matcher(tag)
In this line, your local `val tag` is not defined, so it uses the `val tag: String` defined below. Which itself uses `createStackElementTag`, so you created an infinite recursion.

2022-11-15 13:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
>              val m = ANONYMOUS_CLASS.matcher(tag)
You can still remove the var. I believe it would still be an improvement. But you either need to use another variable, or to directry apply `.substring` to the result of the if/else

2022-11-15 13:57 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
>              val m = ANONYMOUS_CLASS.matcher(tag)
Ok got it

2022-11-19 18:28 UTC, lukstbit requested changes

2022-11-19 18:28 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            val tag = if (m.find()) {
You code doesn't replicate the original code when `m.find()` returns true(you're calling substring on m.replaceAll but your code looks for the point index on el). To remove the var you could do:

```
val m = ANONYMOUS_CLASS.matcher(element.className)
val tag = if (m.find()) m.replaceAll("") else element.className
return tag.substring(tag.lastIndexOf('.') + 1)
```

2022-11-19 18:32 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            val tag = if (m.find()) {
Alright

2022-11-20 07:15 UTC, lukstbit approved these changes
Thanks!

2022-11-20 11:56 UTC, BrayanDSO approved these changes

2022-11-20 11:57 UTC, merged