kotlin code cleanup
ankidroid/Anki-Android pull request #12838
Opened 2022-11-17 07:13 UTC by pratyaksh1610

## Purpose / Description
Kotlin cleanup

## Fixes

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-11-17 13:54 UTC, lukstbit requested changes

2022-11-17 13:54 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt
> +                Calendar.HOUR_OF_DAY to getRolloverHourOfDay(context)
The code is not equivalent. Your code:

`Calendar.HOUR_OF_DAY to getRolloverHourOfDay(context)`

simply creates a Pair<Int, Int> inside the apply block not changing the calendar instance. You can see this as you can assign the pair above to a variable:

```
calendar.apply {
     val unused: Pair<Int, Int> = Calendar.HOUR_OF_DAY to getRolloverHourOfDay(context)
```

So please use the set() method inside the apply block as that is the method used when using the bracket style from the initial code.

2022-11-17 13:54 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
> +        return fIllegalCharReg.matcher(str).replaceAll("")
You can further improve this function(and the other one) with:

`fun stripIllegal(str: String): String = fIllegalCharReg.matcher(str).replaceAll("")`

2022-11-19 18:12 UTC, lukstbit requested changes

2022-11-19 18:12 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
> +        fun getCollectionMediaPath(collectionPath: String): String = collectionPath.replaceFirst("\\.anki2$".toRegex(), ".media")
Please revert this change. While we can turn this into a one line function, it becomes a bit too long to read inside an IDE.

2022-11-19 18:12 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
> +        fun indexOfFname(p: Pattern): Int = if (p == fSoundRegexps) 2 else if (p == fImgAudioRegExpU) 2 else 3
Please revert this change. It becomes a bit too long and it's also more difficult to read with the nested if-else.

2022-11-20 17:37 UTC, pratyaksh1610 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
> +        fun getCollectionMediaPath(collectionPath: String): String = collectionPath.replaceFirst("\\.anki2$".toRegex(), ".media")
Done

2022-11-20 17:37 UTC, pratyaksh1610 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
> +        fun indexOfFname(p: Pattern): Int = if (p == fSoundRegexps) 2 else if (p == fImgAudioRegExpU) 2 else 3
Done

2022-11-20 17:40 UTC, pratyaksh1610 commented on AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt
> +                Calendar.HOUR_OF_DAY to getRolloverHourOfDay(context)
I have made the change. Thanks.

2022-11-20 17:40 UTC, pratyaksh1610 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
> +        return fIllegalCharReg.matcher(str).replaceAll("")
I have made the change. Thanks.

2022-11-21 05:49 UTC, lukstbit approved these changes

2022-11-21 16:30 UTC, BrayanDSO approved these changes
Approving, but 80% of it wasn't really necessary

2022-11-21 16:30 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
> +    fun dir(): String = mDir!!
To be honest, this kind of change (removing `return` to use `=` on existing code) only generates noise and doesn't serve an useful purpose, IMO

2022-11-21 16:30 UTC, merged