Use ”Undo” instead of "Undo %s" for the item of "Undo" if there is no string of undone target
ankidroid/Anki-Android pull request #12854
Opened 2022-11-20 04:33 UTC by snowtimeglass

## Pull Request template

## Purpose / Description
Use just "Undo" instead of "Undo %s" for the item of "Undo" if there is no string of undone target.
![image](https://user-images.githubusercontent.com/10436072/202884903-3234acd0-de6d-411f-9895-9989499c056f.png)
![image](https://user-images.githubusercontent.com/10436072/202880860-3784d168-8e09-43ae-a02a-b96ce8cd4f2f.png)

https://github.com/ankidroid/Anki-Android/blob/9ac9e6e3047184d79a4044129254f2ee96a4f8bc/AnkiDroid/src/main/res/values/01-core.xml#L76
https://github.com/ankidroid/Anki-Android/blob/9ac9e6e3047184d79a4044129254f2ee96a4f8bc/AnkiDroid/src/main/res/values-ja/01-core.xml#L92
https://github.com/ankidroid/Anki-Android/blob/9ac9e6e3047184d79a4044129254f2ee96a4f8bc/AnkiDroid/src/main/res/values/01-core.xml#L74
https://github.com/ankidroid/Anki-Android/blob/9ac9e6e3047184d79a4044129254f2ee96a4f8bc/AnkiDroid/src/main/res/values-ja/01-core.xml#L90
## Fixes
Fixes #12853

## Approach
Separate cases by presence/absence of string of undone target on Reviewer.kt

## How Has This Been Tested?
Checked on a physical device
![image](https://user-images.githubusercontent.com/10436072/202884961-7580870a-adae-4bac-a7a3-99363c23be81.png)

![image](https://user-images.githubusercontent.com/10436072/202884257-0054e6ff-2add-4c1a-964c-e340e0f4cb65.png)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-11-20 09:44 UTC, BrayanDSO requested changes
The japanese I learned on Anki now is helping me solve bugs on Anki. There are some odd circles on life indeed

2022-11-20 09:44 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +            if (col.undoName(resources) !="") {
There are some lint errors. 

And I believe that `if (col.undoAvailable())` can be used

And a comment on code to why this is necessary would be nice

2022-11-20 14:23 UTC, snowtimeglass commented
Glad to hear you have learned Japanese :+1: 
What a nice circle. It probably circulates neither by chance nor by destiny but by your good will. It makes AnkiDroid and the world better, thanks.

2022-11-20 14:27 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +            if (col.undoName(resources) !="") {
Thanks for your advice! I've rewritten them.

2022-11-20 16:12 UTC, BrayanDSO approved these changes
LGTM

2022-11-20 16:13 UTC, BrayanDSO requested changes
Oops. There are still some lint errors. ktlintFormat should have solved these

2022-11-23 02:58 UTC, snowtimeglass commented
Thanks for pointing it out. Sorry, I'm still unfamiliar with the procedure. I fixed some lint errors just now.

2022-11-28 12:52 UTC, BrayanDSO approved these changes

2022-11-29 09:42 UTC, lukstbit approved these changes
There's no complete circle for me as I don't learn japanese with Anki, but changes LGTM. Thanks!

2022-11-29 09:52 UTC, merged