Next/Previous card gestures in Previewer
ankidroid/Anki-Android pull request #12882
Opened 2022-11-24 22:31 UTC by alyoshenka

## Purpose / Description
This fix introduces gesture support for viewing the next and previous card in `Previewer`.

## Fixes
Fixes #12390 

## Approach
This adds the relevant viewer commands and checks for them in `Previewer` when a gesture is detected.

From what I could see, there are no other commands that have confusingly similar meanings. To the best of my knowledge, these new commands are set up like the others, however I may have missed something.

As per the conversation in the original issue, there are more commands that could be added to the `Previewer`, such as flipping the card. This pr just fixes the main issue, but I am looking into others to add as well. 

## How Has This Been Tested?
1. Go to Settings > Controls > Set 'Preview Next/Previous Card' to the desired gesture
2. Go to Previewer
  1. Card Browser > Options Menu > Preview
- [ ] The selected gestures move to next/previous card 
  - [ ] 'Previous' gesture does nothing when at the beginning of the deck
  - [ ] 'Next' gesture does nothing when at the end of the deck

## Learning (optional, can help others)
I couldn't find documentation detailing how to add new gestures. It seemed pretty straightforward, but it would be worthwhile to add a documentation page for it. 

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] ~UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)~
- [ ] ~UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)~

2022-11-26 09:34 UTC, BrayanDSO commented
Hi. I think that the user wants to re-use the gestures they use on the reviewer instead of creating duplicates exclusive to the previewer.

So I believe that the goal here is to make some gestures like `Show answer` and `Answer button X` to work on the previewer as well. 

As you are the issue creator, do you have any ideas @voidplayer ?

And oh, tests are failing

2022-11-26 20:36 UTC, alyoshenka commented
What actions would showing the next and previous card map to? I couldn't find any that seemed appropriate.

2022-11-28 12:47 UTC, BrayanDSO reviewed
In order to avoid people getting confused, it would be best to create a `PreferenceCategory` called `Previews` so the user know that these are specific to the previewer.

If this is created, maybe the strings could be simplified to `Next card` and `Previous card`.

---
For other issues:
1. Reuse the existing gestures as well (Answer button 1/2/3/4 and show answer)
2. Make the previewer answer bar be resizable as well

2022-11-28 12:47 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt
> +    private fun tryChangePreviewedCard(nextCard: Boolean): Boolean {
This method name and parameter are a bit confusing, although I know that the logic is similar to the existing `changePreviewedCard` method

Perhaps having separate methods named `showNextCard` and `showPreviousCard` (or similar names) without a parameter would be better

2022-11-28 12:47 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/11-arrays.xml
> +    <string name="gesture_preview_previous_card">Preview Previous Card</string>
I know that the other gestures have all words capitalized, but they shouldn't be, so I'd rather if these were `Preview next card` and `Preview previous card`

2022-11-29 22:58 UTC, alyoshenka commented on AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt
> +    private fun tryChangePreviewedCard(nextCard: Boolean): Boolean {
Updated in most recent commit.

2022-11-29 22:58 UTC, alyoshenka commented on AnkiDroid/src/main/res/values/11-arrays.xml
> +    <string name="gesture_preview_previous_card">Preview Previous Card</string>
Updated in most recent commit.

2022-11-29 23:00 UTC, alyoshenka commented
> Yes, ideally same gestures work without having to define them
> 
> but `go to next/previous card without showing answer` is an action exclusive of the preview window and have no gestures

For this issue specifically, I'm working on showing next/prev card. If I get around to supporting other gestures, I'll make a separate PR.

2022-12-01 22:27 UTC, alyoshenka commented
After looking more at `ViewerCommand`, it does seem like this class is intended to be used only with `Reviewer`: all of the MapableBindings are connected to it. I feel like this means a larger redesign is necessary, but I'm not sure what that entails.

2022-12-04 18:50 UTC, alyoshenka commented
My solution that seems to work is as follows:
- keep all gesture actions in `ViewerCommand.values()`
- add specific gestures for each `AbstractFlashcardViewer` (just `Reviewer` and `Previewer` in this case) to the companion object
  - so you would access previewer gestures with `ViewerCommand.previewCommands`
  - This has the downside of needing to repeat most commands into `ViewerCommand.reviewerCommands`, but the upside of making an easy place to define which commands go to which viewer
- add a new `PreferenceCategory` to `ControlsSettingsFragment` and populate it with the Previewer commands
This comes with the downside that there would need to be a new translated string resource: "Previewer commands" (and potentially also changing "Command mapping" to "Reviewer commands'). However, this would be necessary anyway with the necessity of making the Previewer command category.

I'm working on getting this change ready to push, but it will take some time to get the string resources figured out. That's my solution, at least.

2022-12-04 20:24 UTC, alyoshenka commented
There is also an issue where pressing a key in `Previewer` causes the screen to darken. This is an issue in `main` as well.

2022-12-04 20:26 UTC, alyoshenka commented
This PR still needs translations. It is my understanding that now that I've added a string resource, it will go out for translation, and I don't have to do anything further.

2022-12-04 21:15 UTC, BrayanDSO requested changes
Overall looks pretty good. Great job!

Of my remarks, probably only the search bar breadcrumbs one is important, rest of them are nits.

And I agree with you that `Command mapping` should be renamed to `Reviewer commands` (remember to change the key too when you do it)

2022-12-04 21:15 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt
> +    fun addAllControlPreferencesToCategory(category: PreferenceCategory, commands: List<ViewerCommand>) {
Renaming the method to `addCommandsToCategory` (or something similar) would make more sense now.

And rewriting the javadoc would be appropriate too.
```kotlin
    /** 
       * Creates dinamically [ControlPreference] objects for each of the [commands] given,
       * and add them to [category]
       */
```

2022-12-04 21:15 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +                .addBreadcrumb(getString(R.string.controls_previewer))
The preferences search bar indexes preferences from the XMLs. As we build controlPreferences dinamically, they aren't on the XMLs and therefore aren't indexed with the others, so we have to index them manually like on this block. 

Note that the breadcrumbs should be different between reviewer and previewer methods, as they are on different categories, so basically you need to have a different loop for each of them. So I suggest something like

```kotlin
for (command in ViewerCommand.reviewerCommands) {
            searchConfig.indexItem()
                .withTitle(getString(command.resourceId))
                .withKey(command.preferenceKey)
                .withResId(R.xml.preferences_controls)
                .addBreadcrumb(getString(R.string.pref_cat_controls))
                .addBreadcrumb(getString(R.string.controls_main_category))

for (command in ViewerCommand.previewerCommands) {
            searchConfig.indexItem()
                .withTitle(getString(command.resourceId))
                .withKey(command.preferenceKey)
                .withResId(R.xml.preferences_controls)
                .addBreadcrumb(getString(R.string.pref_cat_controls))
                .addBreadcrumb(getString(R.string.controls_previewer))
```

2022-12-04 21:15 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/preferences.xml
> +    <string name="controls_command_mapping_cat_key_previewer">key_map_category_previewer</string>
Have `_key` at the end of the key

2022-12-04 21:15 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="controls_previewer" maxLength="41">Previewer commands</string>
`controls_previewer_cat` or `controls_previewer_category`

2022-12-04 22:27 UTC, alyoshenka commented
Sweet! Didn't expect everything to be 100% the first time, glad to hear this approach is acceptable. I'll get those changes in as soon as I can.

2022-12-07 00:31 UTC, alyoshenka commented
Not sure what's going on with ubuntu-latest tests, I ran them locally with no errors.

2022-12-07 00:50 UTC, dae commented
Network flake; restarted.

2022-12-07 16:17 UTC, alyoshenka commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
> +        val reviewerCommands: List<ViewerCommand>
Covered in most recent commit

2022-12-07 16:17 UTC, alyoshenka commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
> +                SHOW_PREV_CARD -> from(keyCode(KeyEvent.KEYCODE_O, CardSide.BOTH))
Covered in most recent commit

2022-12-07 16:18 UTC, alyoshenka commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +                .addBreadcrumb(getString(R.string.controls_previewer))
Covered in most recent commit

2022-12-07 16:18 UTC, alyoshenka commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="controls_previewer" maxLength="41">Previewer commands</string>
Covered in most recent commit

2022-12-07 20:05 UTC, BrayanDSO requested changes

2023-02-22 17:49 UTC, david-allison requested changes
This should be using the `MappableBinding.Screen` class to serialise properties designed for a new screen

2023-03-08 18:43 UTC, david-allison commented
I'll take this one to completion in 2.17 if there's no reply. Good feature to have.

2024-03-16 10:46 UTC, closed without merging