Changed API for Bundle.getSerializable
ankidroid/Anki-Android pull request #12881
Opened 2022-11-24 14:57 UTC by SanjaySargam

## Pull Request template
Changed API for Bundle.getSerializable

## Fixes
Bug #12364 

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-11-25 15:58 UTC, criticalAY commented
This still leaves us with the same issue @mikehardy. We are not using the new method as call but the old one. This PR is similar to what I had closed last time. We need a discussion here. Probably David needs to interfere here as I mentioned earlier also. I am also interested in the outcome

2022-11-25 17:23 UTC, SanjaySargam commented
> This still leaves us with the same issue @mikehardy. We are not using the new method as call but the old one. This PR is similar to what I had closed last time. We need a discussion here. Probably David needs to interfere here as I mentioned earlier also. I am also interested in the outcome

Ok So Will I close this issue?

2022-11-25 17:26 UTC, criticalAY commented
No let it be, I was the first one to work on it and if you went through the conversation on my PR that I referred you there is something we need to discuss that's all

2022-11-25 17:29 UTC, SanjaySargam commented
> No let it be, I was the first one to work on it and if you went through the conversation on my PR that I referred you there is something we need to discuss that's all

Ok

2022-12-01 07:23 UTC, lukstbit commented
I don't think the current code is how we should go forward, instead we should use the newer method signature with our current code. This can be done by creating an extension method on `Bundle` inside `CompatHelper` which replicates the newer `getSerializable`(the one that also takes the Class parameter) and using it where we currently have a deprecation warning. This new method can then call the compat method that you created.

This would allow us, when API 33 will be the minimum supported, to switch to the new implementation by simply deleting the compat related code and changing some imports where the method is used.

2022-12-02 12:29 UTC, SanjaySargam commented
> I don't think the current code is how we should go forward, instead we should use the newer method signature with our current code. This can be done by creating an extension method on `Bundle` inside `CompatHelper` which replicates the newer `getSerializable`(the one that also takes the Class parameter) and using it where we currently have a deprecation warning. This new method can then call the compat method that you created.
> 
> This would allow us, when API 33 will be the minimum supported, to switch to the new implementation by simply deleting the compat related code and changing some imports where the method is used.

I think I have done the same thing that what u said
Correct me if I am wrong

2022-12-02 13:29 UTC, lukstbit commented
@SanjaySargam No, the method you defined in CompatHelper doesn't match the signature of the new version of the method from API 33.

2022-12-02 13:49 UTC, criticalAY commented
> @SanjaySargam No, the method you defined in CompatHelper doesn't match the signature of the new version of the method from API 33.

Indeed correct, Mike and luksbit are correct I was not getting the issue right now  but it's going to be an issue in future if we don't use the new method to call it. So +1 to go with the new method. There isn't much to change though I think it will be an easy one

2022-12-03 14:11 UTC, mikehardy requested changes

2022-12-03 14:11 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/utils/BundleUtils.kt
>      @Suppress("deprecation") // getSerializable
can remove the suppression now?

2022-12-03 14:11 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
> +                (bundle.getSerializableCompat<ArrayList<Array<Any>>>("mTemplateChanges"))!!
I don't understand how we have defined it in Compat / CompatHelper to use the new API but we are *still* not using an API compatible with the new API here. **there is not type argument but that is part of the new Serializable API**

Why is there no type argument here?

Instead of defining these companion methods that deviate from the future API, meaning we will have to make changes in the future to use the non-compat style, can we just 

- use the Compat infrastructure to make a method taking the future argument signature
- use that method, e.g. CompatHelper.getCompat().getSerializable(bundle, name, type)

This companion method style encourages the use of a not-future-compatible API and is the same thing you got hung up on as well @criticalAY 

Stated differently: the goal is that for now we call a Compat API that takes the object we are working on *followed by the new API parameters* so that in the future *we easily convert to just calling the method directly on the object we are working on, without needing to change the type parameters*

I don't consider the companion methods helpful then, really.

2022-12-03 15:49 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
> +                (bundle.getSerializableCompat<ArrayList<Array<Any>>>("mTemplateChanges"))!!
Yes, its the same one we need to alter the param in the compat helper file as Compat is already having the new method the issue is with the helper where we are passing `T::Class.java`, adding a parameter there and then replacing the T::Class.java can help fix it. That is my POV

2022-12-07 11:54 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/utils/BundleUtils.kt
>      @Suppress("deprecation") // getSerializable
removed

2023-02-12 12:44 UTC, closed without merging