Show more stats while downloading a shared deck
ankidroid/Anki-Android pull request #12900
Opened 2022-11-29 15:01 UTC by abhi-kr-2100

## Purpose / Description
Instead of just showing the progress in percentage, the download screen now shows an estimate of the time remaining along with average download speed in the appropriate units.

## Fixes
Fixes https://github.com/ankidroid/Anki-Android/issues/12899

## Approach
This solves issue #12899 directly by adding the asked for stats on the download screen.

## How Has This Been Tested?
This has been tested on a physical as well as several virtual android devices. Just launch Anki and try to download a shared deck via the "Get shared deck" button. On the download screen one can see an estimate of the remaining time as well as the average download speed.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-11-29 17:21 UTC, mikehardy commented
This looks interesting - thanks for posting it up!

This is a UI change and you haven't attested to the two UI related items, can you please include a video of it in action and make sure it passes the accessibility scanner?

UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
 UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-11-29 17:26 UTC, mikehardy requested changes
Code-wise I had a couple questions, plus the lack of translation is a full blocker, all strings must be translate-able before a PR may be merged https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#adding-translations

2022-11-29 17:26 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                "$estimatedTimeRemainingInSeconds second${if (estimatedTimeRemainingInSeconds != 1L) "s" else ""}"
It is not valid to do string interpolation like this. It appears that R.string.percentage needs to be removed and replaced with whatever string you need, including format string variables, then you interpolate that in. Otherwise you do not handle RTL languages or other plurals well in the wide variety of languages we support.

2022-11-29 17:26 UTC, mikehardy commented on AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml
> +        tools:text="66 %, 42 seconds left (7 MBs/second)" />
the previous version starts at 100% while this one starts at 66%. Why the change in percent?

2022-11-29 17:26 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            ++timeQuantumPassed
Can you explain why this is needed now, here, where it was not needed prior?

2022-11-30 03:49 UTC, abhi-kr-2100 commented
@mikehardy Thanks for the quick response. I'll post a video and do an accessibility scan today when I reach my room.

2022-11-30 03:51 UTC, abhi-kr-2100 commented on AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml
> +        tools:text="66 %, 42 seconds left (7 MBs/second)" />
This is to show what the new UI looks like when the download is midway. 0% and 100% are edge-cases where the time remaining and the speed may not be displayed.

2022-11-30 03:56 UTC, abhi-kr-2100 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            ++timeQuantumPassed
Sure. The function is run every `DOWNLOAD_PROGRESS_CHECK_DELAY` milliseconds. `timeQuantumPassed` counts how many times the function is run. This can be used to calculate the time duration since the download started: `timeQuantumPassed * DOWNLOAD_PROGRESS_CHECK_DELAY` milliseconds.

I think I should rename it to `iterations`. I originally named it `timeQuantumPassed` since at that time I was thinking in terms of time duration. I consider `DOWNLOAD_PROGRESS_CHECK_DELAY` to be 1 time quanta. `timeQuantumPassed` counts how many time quantum have passed.

2022-11-30 03:57 UTC, abhi-kr-2100 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                "$estimatedTimeRemainingInSeconds second${if (estimatedTimeRemainingInSeconds != 1L) "s" else ""}"
Thanks for pointing this out. I'll be correcting this as soon as possible.

2022-11-30 14:07 UTC, abhi-kr-2100 commented on AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml
> +        tools:text="66 %" />
Changed to 66 % to show how the layout would look like when the download is midway.

2022-11-30 15:13 UTC, abhi-kr-2100 commented
@mikehardy I've attached a video, but I couldn't successfully scan the download screen using Google Accessibility Scanner. It looks like the scan failed because the screen constantly changes (as the download progress). But since I've based my additions on already existing TextViews, their accessibility is no different from the other already existing elements.


https://user-images.githubusercontent.com/66527624/204835234-08b7a88c-f6ba-4351-9f92-cf5471529952.mp4

2022-11-30 15:14 UTC, abhi-kr-2100 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                "$estimatedTimeRemainingInSeconds second${if (estimatedTimeRemainingInSeconds != 1L) "s" else ""}"
I've now added the used text to the appropriate resources file and used `getQuantityString` to format them and pluralize them.

2022-12-26 22:06 UTC, BrayanDSO reviewed
Overall the code is good, and precise enough to me to deliver a reasonably good enough display of the download speed.

My main question is if we could hide or zero the download speed / time left when the download is finished, because by looking at it on the video I thought that the import hadn't ended even when it reached 100%

2022-12-26 22:06 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            ++timeQuantumPassed
> I think I should rename it to iterations

I think that this is a good idea

2022-12-27 09:26 UTC, abhi-kr-2100 commented
@BrayanDSO I've made the requested changes:

* `timeQuantumPassed` has been renamed to `mNumIterations`
* An estimate of the remaining time is not displayed when download has just started or has finished.

2022-12-27 09:27 UTC, abhi-kr-2100 commented
https://user-images.githubusercontent.com/66527624/209644769-0495c62b-a796-41a4-9433-47311cc531b8.mp4

2023-01-05 00:43 UTC, abhi-kr-2100 commented
@BrayanDSO @mikehardy Any update on the progress of this PR?

2023-01-06 16:15 UTC, abhi-kr-2100 commented
@BrayanDSO I considered hiding the download speed as well, however the final download speed that is displayed is the overall average download speed: total bytes downloaded / total time taken. This information can be useful/interesting. Hence, I decided to leave it there.

2023-01-06 16:30 UTC, BrayanDSO approved these changes
LGTM. Left just a nit

2023-01-06 16:30 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +    private var mNumIterations = 0
just a note that we are trying to avoid using hungarian notation for new variables in Kotlin. 

A lot of files still have them because we've converted hundreds of files not so long ago and removing the notation wasn't a priority. But for now on, it is best to avoid adding more variables with hungarian notation

2023-01-06 17:25 UTC, abhi-kr-2100 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +    private var mNumIterations = 0
@BrayanDSO Fixed this just now.

2023-01-07 09:54 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +    private lateinit var mDownloadSpeedText: TextView
If you want to remove the hungarian notation from the properties you added, there are these two as well

2023-01-07 10:37 UTC, abhi-kr-2100 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +    private lateinit var mDownloadSpeedText: TextView
My bad. Corrected this now.

2023-01-07 11:02 UTC, BrayanDSO approved these changes

2023-01-31 11:57 UTC, david-allison requested changes
Thanks! minor string issue and good to go

2023-01-31 11:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            val averageSpeedInBytesPerMillis = downloadedBytes / totalTimePassedInMillis
Guaranteed to be nonzero

2023-01-31 11:57 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +        <item quantity="other">%d KBs/second</item>
`2 KB/second` (I'd prefer `2KB/s`), not `2KBs/second`

2023-01-31 11:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            val averageSpeedInBytesPerSecond = ceil(downloadedBytes / (totalTimePassedInMillis / 1000.0)).toInt()
This logic could be extracted for readability (implementer's choice)

2023-03-14 06:38 UTC, closed without merging