Enable CI check using  the new backend for the Ubuntu runner
ankidroid/Anki-Android pull request #12927
Opened 2022-12-05 13:33 UTC by lukstbit

## Purpose / Description

Introduces a new matrix variable for jobs so we get to test the old code as well as run tests for the new backend. At the moment I enabled the new backend just for Ubuntu. Also because this PR introduces two different configurations for Ubuntu CI runner, I changed the name of the job to mention both the os and the legacy schema value so reviewers/contributors can see more easily  in which situations the PR fails.

## Fixes

Fixes #12920 

## How Has This Been Tested?

Ran on my fork.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-12-05 14:01 UTC, mikehardy requested changes

2022-12-05 14:01 UTC, mikehardy commented on .github/workflows/tests_unit.yml
> +            legacy_schema: false
I love the change in general (nice touch with the naming!)  but can we not exclude windows?
My reasoning: it is a subtle side effect - windows runner is slower / lower performance and it has turned up a few real problems with timing / race conditions in the new schema if I recall correctly, so I think it is useful to have it checking things too

Feel free to disagree if you disagree (just say why of course...) and I'll be inclined to go with your reasoning if so, then we can merge this.

I really appreciate your doing this, having more people playing with the workflows here is a big deal for project continuity versus the last few years where the main test workflows have been mostly just me. :raised_hands: 

```suggestion
```

2022-12-05 14:08 UTC, lukstbit commented on .github/workflows/tests_unit.yml
> +            legacy_schema: false
@mikehardy The only reason I enabled it only for ubuntu was because this came up in one of my PRs for the new backend where I mentioned that I didn't add any tests and there was a discussion about enabling it for Ubuntu to start.

2022-12-05 14:11 UTC, mikehardy commented on .github/workflows/tests_unit.yml
> +            legacy_schema: false
makes sense - I guess it just seems like this is basically the complete solution now (with "all but macOS") and at this point with this nice matrix solution the only reason not to enable macOS is to manage our concurrency of free macOS runners (those limit our global throughput sometimes)

2022-12-05 14:14 UTC, lukstbit commented
@mikehardy Just a heads up, got a warning when I ran the action:

_macOS-latest pipelines will use macOS-12 soon. For more details, see https://github.com/actions/runner-images/issues/6384_

2022-12-05 14:17 UTC, mikehardy commented
Yep - this may cause us issues so I'll do a check. It actually broke CI in a couple other repos (notably: react-native-firebase which I maintain on contract so it's really important to me!) but only because `python` was no longer available in macos-12 :laughing:. 

We use python in some of our CI here on macOS (notably the i18n stuff) so it might affect us

2022-12-05 15:19 UTC, mikehardy commented
As I suspected! 

https://github.com/ankidroid/Anki-Android/actions/runs/3620776691/jobs/6103410583#step:10:159

:monocle_face:

2022-12-05 15:21 UTC, mikehardy commented
Note: you may or may not have a windows environment set up for this. You probably don't! I would not if I did not have to, but maybe windows is your main development platform? Just let me know if you have an environment to test this, otherwise I do have a windows VM set up to work on Anki-Android-Backend etc so I can look through it

If it is an easy fix we can fix it in a commit here, if it is not then we can have this one not fail the CI run (but remain there as an advisory) and peel it to another issue)

2022-12-05 17:40 UTC, lukstbit commented
> but maybe windows is your main development platform?

Not by a mile, I only use Ubuntu, sorry.

2022-12-05 17:45 UTC, mikehardy commented
> Not by a mile, I only use Ubuntu, sorry

I'm with you on the bare metal, but it's a great platform for VMs :-). I'll fire up my win11 VM and give it a whirl to see if it's a flake or a consistent failure or what

2022-12-06 00:26 UTC, dae commented
That test is useless on the new schema, so you should be able to just add an assumption that the legacy schema is enabled at the top of the test.

2022-12-06 21:55 UTC, mikehardy approved these changes
LGTM - thanks @lukstbit !

2022-12-06 21:55 UTC, merged