Renamed name to fullDeckName
ankidroid/Anki-Android pull request #12938
Opened 2022-12-08 15:51 UTC by n1snt

## How Has This Been Tested?

- Tests

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-12-08 15:52 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.kt
>  @KotlinCleanup("maybe possible to remove gettres for revCount/lrnCount")
I think we can remove this kotlin cleanup as well because there are no getters for both of them.

2022-12-12 08:56 UTC, lukstbit requested changes

2022-12-12 08:56 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.kt
>  @KotlinCleanup("maybe possible to remove gettres for revCount/lrnCount")
That cleanup can be deleted as well. Will you add it to this PR?

2022-12-14 16:02 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.kt
>  @KotlinCleanup("maybe possible to remove gettres for revCount/lrnCount")
Yeah sure will add that too. 👍

2022-12-27 18:58 UTC, n1snt commented
Hey, @lukstbit just made the requested changes.

2022-12-27 20:27 UTC, david-allison approved these changes

2022-12-28 06:17 UTC, lukstbit approved these changes
Great!

2022-12-28 06:17 UTC, merged