Add option to sync media only on wifi
ankidroid/Anki-Android pull request #12933
Opened 2022-12-07 20:40 UTC by RobozinhoD

## Pull Request template

## Purpose / Description
This converts the Fetch media on sync SwitchPreference to a ListPreference with the options "Always, "Only on Wi-Fi" and "Never"

## Fixes
Fixes#12932

## Approach
This converts the Fetch media on sync SwitchPreference to a ListPreference with the options "Always, "Only on Wi-Fi" and "Never"

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

Mostly I tried to understand the code by reading other PRs after using git blame on `preferences_sync.xml`. 

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-12-08 21:40 UTC, BrayanDSO requested changes
Pretty good job here. 

The only things remaining IMO is filling the "Testing" section of the PR description and making a unit test for the preference upgrade

2022-12-08 21:40 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +
I think that we should extract some of those strings into constants. But having all of the preference values centralized somewhere with testing was an idea that I haven't got the time to do yet, so I'm fine with this now as this seems correct

2022-12-08 21:40 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
> +        }
Preference upgrades must be solid, so I'd like to have a unit test here

2022-12-14 00:02 UTC, RobozinhoD commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
> +        }
done

2022-12-14 00:03 UTC, RobozinhoD commented
done

2022-12-15 11:34 UTC, BrayanDSO approved these changes
LGTM. Thanks!

2022-12-20 13:25 UTC, lukstbit requested changes
The code LGTM with the small issues below related to the strings used.

2022-12-20 13:25 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            val syncMediaPrefValue = preferences.getString("syncFetchMedia", "always")
We really should be using the string values from resources like:

`val syncMediaPrefValue = preferences.getString("syncFetchMedia", getString(R.string.sync_media_always_value))`

2022-12-20 13:25 UTC, lukstbit commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="only_wifi">Only on Wi-Fi</string>
This two strings should be prefixed with `sync_media_`:

```
<string name="sync_media_only_wifi">Only on Wi-Fi</string>
<string name="sync_media_never">Never</string>

```
to make it more clear where they are used and to avoid cross use as I mention below.

2022-12-20 13:25 UTC, lukstbit commented on AnkiDroid/src/main/res/values/constants.xml
> +        <item>@string/override_font_always</item>
There's no reason to reuse this string which belongs to another scope. If that string is changed for whatever reason(like "always" -> "always overide font") we will have to change this code as well not to mention the need for another translation for the new string. So please create a standalone string for this.

2022-12-29 21:37 UTC, RobozinhoD commented
fixed the errors

2022-12-30 14:03 UTC, lukstbit requested changes
Thanks for working on this. The lint rule requires that a comment be added to both duplicated strings, so we also need a comment on the `override_font_always` string(something similar to the comment your added but referring to fonts).

2023-01-01 21:54 UTC, oakkitten commented
By the way I would love to see “Only on unmetered connections”. Wi-Fi is often metered when using cellular tethering. “Only on unmetered connections” could be the default

2023-01-02 00:03 UTC, BrayanDSO commented
Rereviewing this makes me question if it wouldn't be good to have generic strings like `Always` and `Never` that could be reused more easily instead of creating duplicates. 

Gonna ping @RobozinhoD (the implementer) and @lukstbit (the one who has suggested to add the `sync_media_` prefix to the strings keys) to see what they think

2023-01-11 18:04 UTC, BrayanDSO commented
Pushing to another person's fork can be messier than I expected. But something can always be learned from a new experience.

Anyway, pushed the "Wi-fi" -> "Unmetered connection" string change because it is a feature I personally want to have

2023-01-12 07:52 UTC, lukstbit approved these changes
LGTM, sorry for taking so long to respond on this.

> wouldn't be good to have generic strings like Always and Never that could be reused more easily instead of creating duplicates.

This duplication will allow us to avoid situations in the future were the original string is changed and the change also affects other places of the app(this was the target of my complaint). I'm perfectly fine either ways, I'm leaning towards using two different strings to not drag this PR anymore.

I'm going to put this as "Pending merge" and leave it for a bit to see if I can tackle your translation sync related issue. Let me know if you want any changes.

2023-01-13 19:20 UTC, oakkitten commented
> Anyway, pushed the "Wi-fi" -> "Unmetered connection" string change because it is a feature I personally want to have

Um I don't understand. You seem to only have changed the string, but not the code. The API allows to separately query for Wi-Fi and for metered connections.

2023-01-13 21:13 UTC, BrayanDSO commented
> Um I don't understand. You seem to only have changed the string, but not the code. The API allows to separately query for Wi-Fi and for metered connections.

Currently, the code check if the connection is metered with `isActiveNetworkMetered()`. Could we add another option called `Only on Wi-Fi`? Yes, but as I'm the author of the issue that this PR is trying to fix, I'm fine with the unmetered connections option, which is actually what I originally wanted to have.

Another PR/issue can be made if anyone wants an `Only Wi-Fi` option

2023-01-13 22:31 UTC, oakkitten reviewed
> Currently, the code check if the connection is metered with `isActiveNetworkMetered()`. Could we add another option called Only on Wi-Fi? Yes, but as I'm the author of the issue that this PR is trying to fix, I'm fine with the unmetered connections option, which is actually what I originally wanted to have.

Ah, from the title I though that the code was indeed checking for Wi-Fi. Nevermind, then

2023-01-13 22:31 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                (syncMediaPrefValue == onlyUnmeteredValue && !isActiveNetworkMetered())
I understand what's going on but this is just so hard to read. I wonder if we can forgo storing preference values in strings for simple constants? Especially since the code below uses hardcoded values. Constants seem to be middle ground...

2023-01-13 22:31 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
>                  handleNewSync(conflict, syncMedia)
Should we notify the user that media wasn't synced because they are on a metered connection?

2023-01-13 22:31 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
> +    const val SYNC_FETCH_MEDIA = "syncFetchesMedia"
Maybe `SYNC_FETCHES_MEDIA`?

2023-01-13 22:31 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
> +                    putString("syncFetchMedia", status)
It seems that `syncFetchesMedia` is changed to `syncFetchMedia`. I suggest a more different key, just so it can't be confused with the old one.

2023-01-13 22:31 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
> +                    putString("syncFetchMedia", status)
Also, extract into a constant?

2023-01-13 23:59 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
>                  handleNewSync(conflict, syncMedia)
If people deliberately set not to sync media on metered connections, remembering them of their choice would be annoying

2023-01-14 11:09 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
>                  handleNewSync(conflict, syncMedia)
I was thinking, we've got a "Collection synced" snackbar and it might be mentioning whether or not media sync was skipped. But probably this isn't needed

2023-01-14 19:52 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                (syncMediaPrefValue == onlyUnmeteredValue && !isActiveNetworkMetered())
...you marked this as resolved but did not address the bit about the constants, if you could explain why that would be helfpul

2023-01-14 19:53 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
> +                    putString("syncFetchMedia", status)
...same here

2023-01-14 20:00 UTC, RobozinhoD commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                (syncMediaPrefValue == onlyUnmeteredValue && !isActiveNetworkMetered())
I thought I’ve resolved the readability issue. Didn’t thought to use constants

2023-01-14 20:01 UTC, RobozinhoD commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
> +                    putString("syncFetchMedia", status)
I don’t think this is necessary

2023-01-20 17:29 UTC, merged