Fix manage space activity on parallel builds
ankidroid/Anki-Android pull request #12954
Opened 2022-12-10 20:35 UTC by BrayanDSO

Co-authored-by: oakkitten <oakkitten@users.noreply.github.com>

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes #12953

## Approach
Use absolute names on the manifest for manage space acitivty

## How Has This Been Tested?

1. Install one of the parallel builds (can be found at the releases page or by running ./tools/parallel-package-name.sh com.ichi2.anki.a AnkiDroid.A then installing the app)
2. Go to the app settings > Storage

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-12-21 15:14 UTC, mikehardy commented on AnkiDroid/src/main/AndroidManifest.xml
> +        android:manageSpaceActivity="com.ichi2.anki.ui.windows.managespace.ManageSpaceActivity"
But, for the parallel build, doesn't this mean that parallel build "manage space" accesses in app settings will always go to the main install? That seems like it functions in that it opens something if you have a main install that contains the manage space activity, but it is incorrect in that wires all parallel builds to the main builds manage space activity?

2022-12-24 22:09 UTC, BrayanDSO commented on AnkiDroid/src/main/AndroidManifest.xml
> +        android:manageSpaceActivity="com.ichi2.anki.ui.windows.managespace.ManageSpaceActivity"
Well thought. The best should be to go to #12955 all the way then

2022-12-24 22:30 UTC, oakkitten commented on AnkiDroid/src/main/AndroidManifest.xml
> +        android:manageSpaceActivity="com.ichi2.anki.ui.windows.managespace.ManageSpaceActivity"
I don't think it will. I think this is a bug in the framework. In gradle, there's `applicationId`, and there's `namespace`, aka `package` in the `<manifest>` tag. The latter is always `com.ichi2.anki` for us. I think `android:manageSpaceActivity` for some reason erroneously picks `applicationId` instead of `namespace`, if it isn't explicitly specified, and fails to work. Should be easy to check if this is right.

2022-12-24 22:34 UTC, oakkitten commented on AnkiDroid/src/main/AndroidManifest.xml
> +        android:manageSpaceActivity="com.ichi2.anki.ui.windows.managespace.ManageSpaceActivity"
In other words, this PR is probably good, and it's very likely that #12955 will not resolve the issue all by itself, although there is a chance that it will.

2023-01-11 22:37 UTC, BrayanDSO commented on AnkiDroid/src/main/AndroidManifest.xml
> +        android:manageSpaceActivity="com.ichi2.anki.ui.windows.managespace.ManageSpaceActivity"
Tested it and we don't need a main install, so this is good

2023-01-12 09:13 UTC, BrayanDSO commented on AnkiDroid/src/main/AndroidManifest.xml
> +        android:manageSpaceActivity="com.ichi2.anki.ui.windows.managespace.ManageSpaceActivity"
And did some other tests as well that lead me to think that oakkitten's thought that the issue is in the framework is right

2023-02-06 14:04 UTC, david-allison commented on AnkiDroid/src/main/AndroidManifest.xml
> +        android:manageSpaceActivity="com.ichi2.anki.ui.windows.managespace.ManageSpaceActivity"
Sorry to be a pain. 
Since this is a bug in the framework, could a comment be added so it's not refactored later?

2023-02-06 14:04 UTC, david-allison requested changes
Requesting a comment. Hard approve once this has been added

2023-02-06 16:18 UTC, david-allison approved these changes

2023-02-06 16:18 UTC, merged