Make "Undo" item's title for whiteboard mode
ankidroid/Anki-Android pull request #12961
Opened 2022-12-11 13:04 UTC by snowtimeglass

## Pull Request template

## Purpose / Description
"Undo" item's title isn't switched to one for whiteboard mode though Its action itself and its icon are done.
![image](https://user-images.githubusercontent.com/10436072/206902935-6c5de6ac-e98d-4f19-ae46-7bdea974fc90.png)

## Fixes
Fixes #12960

## Approach
Make a new string for "Undo" item's title for whiteboard mode

## How Has This Been Tested?
Checked on a physical device
![image](https://user-images.githubusercontent.com/10436072/206904550-362a0b51-6944-412f-a2d6-4fd37792e7c9.png)

https://user-images.githubusercontent.com/10436072/206904451-9fa0ca93-1b34-43e3-bbe7-a089d3039cbc.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-12-15 12:58 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                // We arrive here if whiteboard is shown and one or more strokes are retained
I only noticed after seeing the video that someone can only undo whiteboard actions if the whiteboard is active. Could you please add a comment explaining it here?

2022-12-16 13:51 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                // We arrive here if whiteboard is shown and one or more strokes are retained
Thanks. Would these comments be okay?

2022-12-16 15:51 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +            if (mShowWhiteboard && whiteboard != null && whiteboard!!.isUndoModeActive) {
I believe `whiteboard?.isUndoModeActive == true` would be a tad more idiomatic

2022-12-16 15:51 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                //  or is reset ("Clear whiteboard")
This comment reads as though it should make sense for someone who has some sort of a technical knowledge which I don't. I read this five times and I still have no idea what's going on here...

2022-12-16 15:51 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                undoIcon.title = resources.getString(R.string.studyoptions_congrats_undo, lastStroke)
* Why not have one string saying, "Undo [last] stroke"? 
* This makes the title "Undo Stroke", probably better to have "Undo stroke"?

2022-12-18 05:29 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +            if (mShowWhiteboard && whiteboard != null && whiteboard!!.isUndoModeActive) {
Thanks! I've rewritten the part.

2022-12-18 05:34 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                //  or is reset ("Clear whiteboard")
Sorry for the complicated explanation. I've rewritten it. Thanks!

2022-12-18 05:49 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                undoIcon.title = resources.getString(R.string.studyoptions_congrats_undo, lastStroke)
I thought that reusing the existing string "Undo %" might be desirable, but I've switched to the more readable way. Thank you for the advise!

2022-12-24 14:13 UTC, oakkitten reviewed
Sorry about a late review, life came up. I think that this _ideally_ needs simplification of behavior and logic, however this does fix the issue so I'm not against merging this pending some consensus on the capitalization of “Undo stroke”

2022-12-24 14:13 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +            if (undoIconId == R.drawable.eraser) {
`undoIconId == R.drawable.eraser` feels hacky, if you have a variable such as `whiteboardHasStrokesToUndo` you could use that.

2022-12-24 14:13 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +            } else if (col.undoAvailable()) {
**OR better yet**, join the two if blocks. Notice how they are very similar, and you are doing the same checks and calling `col.undoAvailable()` twice.

Don't be afraid to make a bigger refactor in places that do warrant bigger refactors :p

2022-12-24 14:13 UTC, oakkitten commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="undo_action_whiteboard_last_stroke">Undo Stroke</string>
Still think this should be “Undo stroke”

2022-12-24 14:17 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                undoIcon.title = resources.getString(R.string.studyoptions_congrats_undo, lastStroke)
I thought about this this way; if you are a translator than translating a menu item “Undo stroke” is a no-brainer, but if it's simply “stroke” then you have to think about the context in which it is used, like maybe you need to pick the correct tense and capitalization and whatever. Longer text doesn't necessary == harder to translate

2022-12-25 11:41 UTC, snowtimeglass commented
Thank you so much for taking your precious time to give me the thoughtful reviews. I've learned a great deal from them. I'll try some more fixes following your advice.

2022-12-25 11:42 UTC, snowtimeglass commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="undo_action_whiteboard_last_stroke">Undo Stroke</string>
Currently, all initial letters of words are capitalized on the titles of undoing collection actions (e.g., `Undo Add Note`, `Undo Bury`) because Anki Desktop strings are used on the titles (and Anki Desktop applies the all-initial-letters-of words-capitalized style). 

https://github.com/ankidroid/Anki-Android/blob/d095bbf354ba86feb28a74f6c96681873e342df2/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt#L762-L766
![image](https://user-images.githubusercontent.com/10436072/209466059-76affa1c-6d6f-409e-8a8a-57dd040a1aaf.png)
![image](https://user-images.githubusercontent.com/10436072/209466033-c45e5e65-73ca-497a-aa6e-c78a572315c2.png)



>Using Anki translations is something I prefer as it represents a more "shared work" future (between Anki Desktop and AnkiDroid), which may also be read as "less work per contributor" and is thus more sustainable long-term, even if there is punctuation inconsistency.

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/12446#issuecomment-1257214544_

Following the case of punctuation, I have applied the same style to the title of undoing whiteboard strokes though it makes capitalization inconsistency in action menu.

2022-12-25 11:51 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                undoIcon.title = resources.getString(R.string.studyoptions_congrats_undo, lastStroke)
Thanks, I understand and agree with the thought.

2022-12-30 11:06 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        if (mShowWhiteboard && whiteboard != null && whiteboard?.isUndoModeActive == true) {
Thanks. I got it.

2022-12-31 04:14 UTC, snowtimeglass commented
Behavior after the above commits

https://user-images.githubusercontent.com/10436072/210124495-b9ecd5c9-b826-41e5-b21f-c81fa0a1561d.mp4

2022-12-31 04:20 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +            //  or is reset (by "Clear whiteboard")
Thank you for the guidance. Following your suggestion, I've removed the `isUndoModeActive` logic.

2022-12-31 04:23 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +            if (undoIconId == R.drawable.eraser) {
I see. I've used a variable for this part in the new commit. Thanks!

2023-01-01 18:49 UTC, oakkitten commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="undo_action_whiteboard_last_stroke">Undo Stroke</string>
Right, I understand but this might be the case to consider being inconsistent for the sake of the future. Basically, we can go two ways:

* Reuse as much Anki strings as possible and introduce as few homegrown translations as possible. “Undo Add Note” is not super horrible even though it's going to be inconsistent with other menu items. In this case, “Undo Stroke” would be consistent with other “Undo” items but inconsistent with other menu items, and “Undo stroke” would be inconsistent with other “Undo” items but consistent with other menu items. 

  I'd say both of the choices are about as bad, and whatever the implementer choses works.
* Have proper capitalization, with the hope that in the future other strings will be corrected to also have proper capitalization. This will probably require some effort in the Anki repository, creating new strings for all undo actions. But then if you already have “Add note”, it's _very easy_ to translate “Undo add note”. This would be especially cool for languages that have tenses, as in English you can simply prepend “Undo” and you have a phrase that *kind of* works, but in other languages it can be much more awkward.

   In this case, it makes sense to have “Undo stroke” now.

I would personally prefer going the second route; it's quite a bit of gain and the extra translators' burden doesn't seem high. But perhaps there are pitfalls I'm not aware of, and in either case this is something that must be decided by the big guys. So I want to tag @mikehardy and @dae and ask if perhaps it would be a good idea to create proper strings for undo actions in Anki?

2023-01-01 18:49 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        val whiteboardShowsStrokesToUndo = mShowWhiteboard && whiteboard?.undoEmpty() == false
Nit: I'd _slightly_ prefer my original `whiteboardHasStrokesToUndo` as you can interpret your variant as “whiteboard shows [the button/menu] ‘strokes to undo’”

By the way, can we do away with `whiteboardHasStrokes`? Is it possible to have stokes and at the same time NOT being able to undo them?

2023-01-01 18:49 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +            // We can arrive here even if whiteboard is enabled if no stroke has ever been made
Just a thought. What I personally prefer to do is in case of complex behavior describe it in a _single_ comment in simple, non-technical words and put it before the method. This way you can see the big picture without reading the code

2023-01-01 19:23 UTC, dae commented
"Undo Add Note" and the like use "Title Case" for two reasons: it's what seems to be the standard in menubars, and we had a bunch of already translated actions in that case. I'm not really sure it's worth making translations translate all these actions twice. If there are inconsistency issues, couldn't you just dynamically convert particular strings to "Sentence case", perhaps for a whitelisted set of languages?

2023-01-01 20:09 UTC, oakkitten commented
Title Case menu bars might have been standard on Windows, but it seems that this trope might be disappearing, as some modern Windows applications such as Edge, or Photos, or Clock, seem to prefer Sentence casing. Others don't, however, such as Calculator. It's definitely not standard on Android, though, and I don't know about Apple.

I would personally love Anki to switch to Sentence casing, because:

* It would be more consistent with Anki itself; other languages such as Spanish, French or Russian do no use Title Casing within Anki
* Easily reuse strings in Android
* I see no point in Title Casing in the first place

Regarding undo strings, I would still love to have new strings, because:
* It allows for easier to understand, more natural language in translations
* Not a lot of _additional_ work for the translators

> couldn't you just dynamically convert particular strings to "Sentence case", perhaps for a whitelisted set of languages

That would work for English, I guess, but not for other languages I know. A lot of languages use tenses/conjugations/whatever, so this is going to work well for a very few select cases. Can we even come up with a list with such languages? How sure can we be that this would work for those languages? Sounds dangerous to me

2023-01-01 20:33 UTC, dae commented
From a quick look at some Apple iOS apps, Title Case appears to be the norm. But I think internal consistency is more important - if different menu items in the same menu use different cases, that looks somewhat unprofessional.

> other languages such as Spanish, French or Russian do no use Title Casing within Anki

Is that the standard for those languages, or just their Anki translations? What does the calculator app or similar look like in those languages?

> A lot of languages use tenses/conjugations/whatever, so this is going to work well for a very few select cases.

Translators have control of the template, so they can do the equivalent of `Undo '{Action Name}'` or `Undo: {Action Name}`. Is such an an approach really that awkward in other languages? (I'm not arguing here, I'm just trying to understand)

> Sounds dangerous to me

With an add-language-as-required whitelist and the ability to apply it to select strings, I suspect it'd work fairly well in practice.

2023-01-01 22:20 UTC, oakkitten commented
> Is that the standard for those languages, or just their Anki translations? What does the calculator app or similar look like in those languages?

Good question, it seems that on Windows Sentence casing is used in those languages ... which means that there's probably not only a tense inconsistency, but also a capitalization inconsistency in the Undo menu item in Anki itself — for most languages?

> Is such an an approach really that awkward in other languages?

You can sort of see it in English, while “Undo Add Note” as a phrase sounds Ok in a menu  (at least to me — I'm not a native speaker), it should ideally be “Undo adding a note” or something. In Russian “Undo Add Note” becomes «Отменить - Добавить запись», which is bad in my opinion. Russian is just not so... flexible? in this regard. I'd surely go with «Отменить добавление записи» here. Of course, some people may have other opinions about this.

2023-01-01 22:51 UTC, dae commented
"Add Note" -> "Undo Note Addition" might be more natural prose, but "Undo 'Add Note'" doesn't seem particularly strange to me in English. No experience with Russian, so I'll have to take your word for it there :-)

There are also "Redo: ..." and "... undone", "... redone" strings, so splitting these up into separate strings means we're making 4x the work for translators. I guess the question is, is the awkwardness of the existing strings in languages like Russian enough to justify the extra work, given that the average completion rate across the translations is only about 50% as it is?

2023-01-02 00:00 UTC, BrayanDSO commented
About title casing, I don't see the point either.

And about using individual strings instead of a generic format string, in portuguese at least (I'm brazilian), it would be quite more natural to have individualized strings because the verbs, articles, etc should have a gender and number agreement.

Are the generic translations too odd to justify multiplying the translations' work by 5 times? Idk. In portuguese at least, they are mostly acceptable I think, but if Anki strives to be a more user friendly app on different languages, individualized strings make sense, despite the increased work load on the job of volunteer translators

2023-01-02 13:06 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        val whiteboardShowsStrokesToUndo = mShowWhiteboard && whiteboard?.undoEmpty() == false
>you can interpret your variant as “whiteboard shows [the button/menu] ‘strokes to undo’”

I beg your pardon, I don't understand the interpretation enough yet.
Does it mean “whiteboard shows the button (or the item) named `strokes to undo`”?



>Is it possible to have stokes and at the same time NOT being able to undo them?

Currently, it is possible after the action of "Hide whiteboard". The action disables undoing strokes, and enables undoing collection actions again.

https://user-images.githubusercontent.com/10436072/210235131-cd533dbd-b237-4152-a2e8-890255c486b6.mp4

2023-01-02 20:10 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        val whiteboardShowsStrokesToUndo = mShowWhiteboard && whiteboard?.undoEmpty() == false
> I beg your pardon, I don't understand the interpretation enough yet.
Does it mean “whiteboard shows the button (or the item) named strokes to undo”?

That was my idea but on the second thought, uh, just ignore it, it's a bit far-fetched :p

> Currently, it is possible after the action of "Hide whiteboard". The action disables undoing strokes, and enables undoing collection actions again.

Hum. But if you hide the whiteboard, then CMIIW `mShowWhiteboard` will be `false` and so our variable will be false. How about naming it `whiteboardIsShownAndHasStrokes`?

2023-01-02 20:21 UTC, oakkitten commented
> There are also "Redo: ..." and "... undone", "... redone" strings, so splitting these up into separate strings means we're making 4x (5x since the original action names are required as well) the work for translators. I guess the question is, is the awkwardness of the existing strings in languages like Russian enough to justify the extra work, given that the average completion rate across the translations is only about 50% as it is?

As a translator (and I try to be very diligent about my translations) I would say than what takes time is understanding the context of the phrase, and trying to fit it withing constraints such as character count. Actually typing the text takes the fraction of the time for me; when there are many related phrases like in this case, I enjoy doing a lot of translations in no time.

BUT I'm only speaking for myself here, it's hard for me to judge whether this kind of a change will result in a lot of these strings untranslated for a long time or not.

2023-01-03 14:08 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        val whiteboardShowsStrokesToUndo = mShowWhiteboard && whiteboard?.undoEmpty() == false
>Hum. But if you hide the whiteboard, then CMIIW `mShowWhiteboard` will be false and so our variable will be false.

Yes, I think you're right on this point, but sorry, I'm not sure yet what you are concerned about from the fact. However, I understand that the current name of the variable, `whiteboardShowsStrokesToUndo`, is apparently ambiguous and misleading for some reason. 

>How about naming it whiteboardIsShownAndHasStrokes? Or whiteboardStrokesVisible maybe

I agree with the idea. The suggested name, `whiteboardIsShownAndHasStrokes`, is clearer for me, too. I'm going to rename it. Thank you for the suggestion :-D

2023-01-04 13:07 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        val whiteboardShowsStrokesToUndo = mShowWhiteboard && whiteboard?.undoEmpty() == false
Done :-)

2023-01-08 03:40 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +            // We can arrive here even if whiteboard is enabled if no stroke has ever been made
Thank you for the advice. Certainly, this comment isn't simple.

Thanks to the new simple variable, `whiteboardIsShownAndHasStrokes`, suggested by you, there will be less need for the comment, I think. So, I'm going to remove it.

        if (whiteboardIsShownAndHasStrokes) {
            undoIconId = R.drawable.eraser
            undoEnabled = true
        } else {
            // We can arrive here even if whiteboard is enabled if no stroke has ever been made
            undoIconId = R.drawable.ic_undo_white
            undoEnabled = colIsOpen() && col.undoAvailable()

2023-01-22 10:53 UTC, snowtimeglass commented
I am sorry for the late reply.

> Right, I understand but this might be the case to consider being inconsistent for the sake of the future. Basically, we can go two ways:
> 
> * Reuse as much Anki strings as possible and introduce as few homegrown translations as possible. “Undo Add Note” is not super horrible even though it's going to be inconsistent with other menu items. In this case, “Undo Stroke” would be consistent with other “Undo” items but inconsistent with other menu items, and “Undo stroke” would be inconsistent with other “Undo” items but consistent with other menu items. 
> 
>   I'd say both of the choices are about as bad, and whatever the implementer choses works.
> * Have proper capitalization, with the hope that in the future other strings will be corrected to also have proper capitalization. This will probably require some effort in the Anki repository, creating new strings for all undo actions. But then if you already have “Add note”, it's _very easy_ to translate “Undo add note”. This would be especially cool for languages that have tenses, as in English you can simply prepend “Undo” and you have a phrase that *kind of* works, but in other languages it can be much more awkward.
> 
>    In this case, it makes sense to have “Undo stroke” now.
> 
> I would personally prefer going the second route; it's quite a bit of gain and the extra translators' burden doesn't seem high. But perhaps there are pitfalls I'm not aware of, and in either case this is something that must be decided by the big guys. So I want to tag @mikehardy and @dae and ask if perhaps it would be a good idea to create proper strings for undo actions in Anki?
> 

 _Originally posted by @oakkitten in https://github.com/ankidroid/Anki-Android/pull/12961#discussion_r1059783644_

There seems to be no consensus yet on conforming capitalization to Anki Desktop ("Title Case" style), so I've rewrited the string, "Undo Stroke" to "Undo stroke" ("Sentence case" style) :-)

>“Undo stroke” would be inconsistent with other “Undo” items but consistent with other menu items.

I would like to leave the consistency problem unresolved for now and carry it over to another issue.

2023-02-21 15:15 UTC, david-allison requested changes
One nitpick and good to go.

2023-02-21 15:15 UTC, david-allison commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="undo_action_whiteboard_last_stroke">Undo stroke</string>
Could you add a `comment=""` explaining the relation to the whiteboard

2023-02-25 22:22 UTC, mikehardy commented
This one just needs a comment in the strings file it seems?

2023-02-26 00:11 UTC, snowtimeglass commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="undo_action_whiteboard_last_stroke">Undo stroke</string>
My apologies for the late response. I overlooked your comment. I will work on it now.

2023-02-26 00:13 UTC, snowtimeglass commented
I overlooked it. Thank you for letting me notice.

2023-02-26 02:28 UTC, david-allison approved these changes

2023-02-26 02:30 UTC, david-allison reviewed
`"` needs to be escaped, or just use `'`

2023-02-26 02:30 UTC, david-allison commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="undo_action_whiteboard_last_stroke" comment="One of the display patterns of "Undo" item on the action menu in Reviewer. It is shown as the title of the item when the whiteboard (han
```suggestion
    <string name="undo_action_whiteboard_last_stroke" comment="One of the display patterns of 'Undo' item on the action menu in Reviewer. It is shown as the title of the item when the whiteboard (handwriting) feature is enabled and visible and has any strokes (handwritten lines)">Undo stroke</string>
```

2023-02-26 02:31 UTC, snowtimeglass commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="undo_action_whiteboard_last_stroke" comment="One of the display patterns of "Undo" item on the action menu in Reviewer. It is shown as the title of the item when the whiteboard (han
I see. Thank you so much!

2023-02-26 03:31 UTC, david-allison approved these changes

2023-02-26 12:54 UTC, mikehardy approved these changes
LGTM - strings activity is only trusted users on crowdin (frequent translators) and their translations look good based on activity stream, so I'll merge

2023-02-26 12:55 UTC, merged