bug fix for deck export
ankidroid/Anki-Android pull request #12967
Opened 2022-12-12 10:49 UTC by criticalAY

## Pull Request template
This PR fixes the export deck bug

## Purpose / Description

## Fixes
Fixes #12966

## Approach
Select the exact deck before calling the export method

## How Has This Been Tested?
1. Long press a deck other than the default deck you were studying 
2. Press export deck
3. This particular deck will be exported

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-12-13 11:53 UTC, lukstbit requested changes
Nice catch. This isn't a logic bug as the proper collection is exported but it's definitely a UI bug as an incorrect name is used for the deck being saved.

Your code does work but I think it's better to fix the part of the code which is incorrect and which  can be found in `ActivityExportingDelegate.exportDeckAsApkg()`. Current code:

```
override fun exportDeckAsApkg(path: String?, did: DeckId, includeSched: Boolean, includeMedia: Boolean) {
   val deckName = collectionSupplier.get().decks.current().getString("name")
    ...
```
and the solution is to use the deck id to fetch the proper name:
```

override fun exportDeckAsApkg(path: String?, did: DeckId, includeSched: Boolean, includeMedia: Boolean) {
     val deckName = collectionSupplier.get().decks.name(did)
     ...
```

2022-12-13 17:04 UTC, mikehardy commented
> @[criticalAY](https://github.com/criticalAY) criticalAY [force-pushed](https://github.com/ankidroid/Anki-Android/compare/a33a34f391f63003136adcdace17d4a4b28bcf7d..2fac88328ab51a7789a1998e919e9840ac9c312f) the correctDeck branch from [a33a34f ](https://github.com/ankidroid/Anki-Android/commit/a33a34f391f63003136adcdace17d4a4b28bcf7d)to [2fac883 ](https://github.com/ankidroid/Anki-Android/commit/2fac88328ab51a7789a1998e919e9840ac9c312f)[5 minutes ago](https://github.com/ankidroid/Anki-Android/pull/12967#event-8028055633)

Git mastery level +1

2022-12-13 17:06 UTC, criticalAY commented
@mikehardy all thanks to you hehehe

2022-12-13 17:08 UTC, mikehardy commented
Thank you! But my job's easy, I just write comments here ;-), you took the advice and then did all the reading and practice and that's worth recognizing. Regardless of AnkiDroid experience I hope it serves you well (I think it will!) in general software development career

2022-12-14 06:43 UTC, lukstbit approved these changes
Nice!

2022-12-15 11:37 UTC, BrayanDSO approved these changes
LGTM. Thanks!

2022-12-15 11:37 UTC, merged