string intent fix
ankidroid/Anki-Android pull request #12970
Opened 2022-12-12 18:36 UTC by criticalAY

## Pull Request template
String false space fixed

## Purpose / Description
This PR fixes the unwanted white space that was occurring before the param (string) inside the main string

## Fixes
Fixes _Link to the issues._

## Approach
used `.trimMargin()` 

## How Has This Been Tested?
Tested on google emulator
BEFORE : 
![before](https://user-images.githubusercontent.com/48384865/207126617-b3c22720-e45e-4bc9-a91b-d4610ff371a6.jpeg)

AFTER
![Screenshot_16](https://user-images.githubusercontent.com/48384865/207126345-6a343596-7932-420a-8d3d-e1764e8b1fe0.png)

## Learning (optional, can help others)
 Add a pipe character and use trim margin. The pipe means there aren't any leading spaces before the input text

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-12-13 06:02 UTC, lukstbit commented
On what API levels did you see this behavior? I verified 21, 31 and 33 on the emulator and didn't see this once.

2022-12-13 07:01 UTC, criticalAY commented
> On what API levels did you see this behavior? I verified 21, 31 and 33 on the emulator and didn't see this once. 

I tested it on two APIs 28 and 33 and I was able to reproduce it

2022-12-13 11:45 UTC, lukstbit approved these changes
I wasn't able to reproduce this but the changes look ok so I'm leaving this to a second reviewer.

2022-12-13 11:53 UTC, criticalAY commented
> I wasn't able to reproduce this but the changes look ok so I'm leaving this to a second reviewer.

Yes if you want I can link the stack over flow thread I went through

2022-12-13 16:51 UTC, criticalAY commented
> > Yes if you want I can link the stack over flow thread I went through
> 
> That's the stated purpose of the area of the description for context information, please link things like that as a general rule

https://stackoverflow.com/questions/53229432/string-with-triple-quote-inside-of-string-with-triple-quote

2022-12-13 16:54 UTC, mikehardy commented
Edit description as indicated:

```
Learning (optional, can help others)
Add a pipe character and use trim margin. The pipe means there aren't any leading spaces before the input text

Links to blog posts, patterns, libraries or addons used to solve this problem
```

2022-12-13 16:57 UTC, criticalAY commented
> Edit description as indicated:
> 
> ```
> Learning (optional, can help others)
> Add a pipe character and use trim margin. The pipe means there aren't any leading spaces before the input text
> 
> Links to blog posts, patterns, libraries or addons used to solve this problem
> ```

Done

2022-12-15 11:39 UTC, BrayanDSO commented
This is why I tend to prefer plain old string concatenation for multi-line strings.

The change looks good. Thanks for the screenshot and the SA thread

2022-12-15 12:39 UTC, BrayanDSO commented
I could change it myself, but as a feedback point the commit message doesn't suit well the change, and we have a checkbox that says `You have a descriptive commit message with a short title (first line, max 50 chars).`, which you marked.

So, try thinking on a better commit title and description (if necessary) then push it back here

2022-12-15 12:39 UTC, BrayanDSO requested changes
I could change it myself, but as a feedback point the commit message doesn't suit well the change, and we have a checkbox that says `You have a descriptive commit message with a short title (first line, max 50 chars).`, which you marked.

So, try thinking on a better commit title and description (if necessary) then push it back here

2022-12-15 15:52 UTC, criticalAY commented
oki done!

2022-12-15 16:46 UTC, BrayanDSO approved these changes

2022-12-15 16:47 UTC, merged