[KotlinCleanUp] OnRenderProcessGoneDelegateTest,SchedTest.kt,FragmentTestActivity.kt
ankidroid/Anki-Android pull request #12988
Opened 2022-12-15 15:09 UTC by Prince-kushwaha

## Purpose / Description
 Koltin CleanUp of OnRenderProcessGoneDelegateTest,SchedTest.kt,FragmentTestActivity.kt

2022-12-15 21:36 UTC, criticalAY approved these changes

2022-12-15 21:38 UTC, criticalAY commented
LGTM

2022-12-17 07:57 UTC, lukstbit requested changes

2022-12-17 07:57 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
> -@RustCleanup("Remove, or add KotlinCleanup")
This is a `RustCleanup` and should be left alone.

2022-12-17 07:57 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/OnRenderProcessGoneDelegateTest.kt
> -    @KotlinCleanup("webview nullability")
The changes in this class should be reverted and this KotlinCleanup annotation should be deleted instead.
The target WebView can be null and I don't think it's a good idea to hide this fact in tests with `delegate.target.webView?.let {}`.

2022-12-18 06:00 UTC, Prince-kushwaha commented on AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/OnRenderProcessGoneDelegateTest.kt
> -    @KotlinCleanup("webview nullability")
ok

2022-12-18 16:20 UTC, lukstbit requested changes

2022-12-18 16:20 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
> -        val t = Math.round((c.due - TimeManager.time.intTime()).toFloat()).toLong()
While your code does fix the issue it can also be improved. `c.due` and `TimeManager.time.intTime()` both return long so there's no need to cast it to float to round it. So the code should simply be:

`val t = c.due - TimeManager.time.intTime()`

2022-12-18 16:20 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
> -        assertEquals(Math.round((c.due - TimeManager.time.intTime()).toFloat()).toFloat(), 179f, 1f)
The same issues as above with the extra casts and unnecessary rounding:

`assertEquals((c.due - TimeManager.time.intTime()).toFloat(), 179f, 1f)`

2022-12-19 04:53 UTC, Prince-kushwaha commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
> -        val t = Math.round((c.due - TimeManager.time.intTime()).toFloat()).toLong()
ok

2022-12-19 04:53 UTC, Prince-kushwaha commented on AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
> -        assertEquals(Math.round((c.due - TimeManager.time.intTime()).toFloat()).toFloat(), 179f, 1f)
ok

2022-12-19 06:47 UTC, lukstbit approved these changes

2022-12-19 06:47 UTC, merged