made MediaCheckResult parcelable
ankidroid/Anki-Android pull request #12996
Opened 2022-12-17 15:59 UTC by criticalAY

## Pull Request template
 made MediaCheckResult parcelable with @Parcelize and used it instead of Array...

## Purpose / Description
TODO

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?
Tested on google emulator SDK 31

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-12-17 17:21 UTC, criticalAY commented
I have recently observed that JunitTest for windows with legacy Schema=true are failing due to some reason.

2022-12-17 17:27 UTC, lukstbit requested changes

2022-12-17 17:27 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> +            args.putParcelable(CHECK_LIST, checkList)
Did you also refactored the retrieval of the _checkList_ from the arguments?

2022-12-17 17:37 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> +            args.putParcelable(CHECK_LIST, checkList)
I used refactor to extract the constant so should it do it everywhere?

2022-12-17 17:41 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> +            args.putParcelable(CHECK_LIST, checkList)
I also searched for this string but could not find a place(which I did to make sure I am not missing out something) where it was used as it is after I refactored it

2022-12-17 17:53 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> +private const val CHECK_LIST = "checkList"
I personally prefer suffixing keys with `_KEY`, otherwise it's not clear what the purpose of `CHECK_LIST` is

2022-12-17 17:53 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
>          fun newInstance(dialogType: Int, checkList: MediaCheckResult): MediaCheckDialog {
I suggest renaming `checkList` to `mediaCheckResult` here to reduce the number of names. Also the key constant

2022-12-17 17:53 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> +            args.putParcelable(CHECK_LIST, checkList)
This deletes the argument with key `"unused"` among others. Other code is still using it though. Search for `"unused"` in the code files

2022-12-17 18:05 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> +private const val CHECK_LIST = "checkList"
Done

2022-12-17 18:06 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> +            args.putParcelable(CHECK_LIST, checkList)
The whole codebase like all the files or the file I changed? and delete it?

2022-12-17 18:16 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> +            args.putParcelable(CHECK_LIST, checkList)
```
val nohave = requireArguments().getStringArrayList("nohave")
val unused = requireArguments().getStringArrayList("unused")
val invalid = requireArguments().getStringArrayList("invalid")
```

2022-12-17 18:26 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> +            args.putParcelable(CHECK_LIST, checkList)
to 
```
val mediaCheckResult = arguments?.getParcelable<MediaCheckResult>(CHECK_LIST_KEY)                
val nohave = requireArguments().getStringArrayList("nohave")
 val unused = mediaCheckResult?.unusedFileNames
 val invalid = mediaCheckResult?.missingFileNames
```

2022-12-17 18:36 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> +            args.putParcelable(CHECK_LIST, checkList)
The main thing here is to make sure you understand what's going on. With Kotlin cleanups you don't have to look deep, as the changes are often more trivial. Here it might be a bit more nuanced. `"unused"` is a key, and searching the whole codebase for a thing like this is quick and dirty way to find all relevant places, so you can get a picture of what's going on.

2022-12-17 18:45 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> +            args.putParcelable(CHECK_LIST, checkList)
This key is used in two files "DialogHandler" and "MediaCheckDialog"

2022-12-17 18:48 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> +            args.putParcelable(CHECK_LIST, checkList)
And we are getting the arguments using the key

2022-12-17 19:05 UTC, criticalAY commented
I understand that I didn't refactor the retrieval code but there are two arguments that are used in the data class the one with "nohave" what to do with it?

2022-12-17 19:59 UTC, criticalAY commented
Have made the changes

2022-12-18 20:35 UTC, mikehardy commented
@criticalAY 

>  due to some reason.

Please be specific, copy/paste the actual reason if possible otherwise it takes time to read but has no real content

2022-12-18 20:53 UTC, criticalAY commented
@mikehardy  here it is but I don't know what is causing this import issue as I am not that good with tests
```
 What went wrong:
Could not compile build file 'D:\a\Anki-Android\Anki-Android\build.gradle'.
> startup failed:
  build file 'D:\a\Anki-Android\Anki-Android\build.gradle': 2: unable to resolve class org.jetbrains.kotlin.gradle.tasks.KotlinCompile
   @ line 2, column 1.
     import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
     ^
```

2022-12-18 22:58 UTC, mikehardy commented
It does seem to have been some sort of caching related failure. I deleted the related caches on main and reran windows unit legacy on main (to regenerate the caches, while checking it...) and it seems to have already progressed past the point of failure that you noticed @criticalAY - thanks for pointing it out. These windows junit legacy failures should all pass (and be quick) once the cache is fully regenerated in a few minutes, I hope. In the meantime consider them non-blocking since they don't appear to be related to the PRs at all

2023-01-01 19:08 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> +            args.putParcelable(CHECK_LIST, checkList)
Sorry, forgot to reply and noticing this only now.

So anyway, the big idea here is **to reduce the number of names**. `MediaCheckResult` is a single thing that has all the properties required to show a dialog. It uses field names such as `missingFileNames` which are easier to understand than `nohave`. We want to use `missingFileNames` for all missing file names throughout the code. We do not want to have different names that mean the same thing.

So if we are doing this, we also want to remove stuff like `b.putStringArrayList("nohave", ArrayList(mediaCheckResult?.missingFileNames!!))`, and even stuff like `val nohave = mediaCheckResult?.missingFileNames`. If it's easy to read, we want to simply use `mediaCheckResult.missingFileNames`, or ***IF*** it gets repeated a lot, you could say `val (missingFileNames, unusedFileNames, invalidFileNames) = mediaCheckResult` and use `missingFileNames`. One name for one concept.

2023-03-14 06:38 UTC, closed without merging