Kotlin cleanup of NoteEditorTest.kt
ankidroid/Anki-Android pull request #13001
Opened 2022-12-18 07:19 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
Kotlin cleanup of NoteEditorTest.kt

2022-12-18 08:24 UTC, david-allison approved these changes

2022-12-18 16:26 UTC, lukstbit requested changes

2022-12-18 16:26 UTC, lukstbit commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
> +            return Intent(targetContext, NoteEditor::class.java).also {
`apply {}`(as requested by the cleanup) is a better solution here as it avoids the need of using `it`.

2022-12-19 05:01 UTC, Prince-kushwaha commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
> +            return Intent(targetContext, NoteEditor::class.java).also {
i not understand what i have to do ?

2022-12-19 09:59 UTC, lukstbit commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
> +            return Intent(targetContext, NoteEditor::class.java).also {
The cleanup that you deleted said:

> @KotlinCleanup("simplify property getter with **_apply_** and direct return")

For some reason you decided to use `also` which is more verbose.

2022-12-19 10:03 UTC, TimSta82 commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
> +            return Intent(targetContext, NoteEditor::class.java).also {
replace `also {}` with `apply {}`

within 
apply {
   component = ...
   putExtra(...)
}

2022-12-19 11:34 UTC, TimSta82 commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
> +    private val invalidSdksImpl: List<Int>
have you simplified the getter? 
I think something like this is meant:
`
val invalid: Int = Build.VERSION_CODES.N_MR1
val integers: ArrayList<Int> = arrayListOf(invalid)
integers.addAll(invalidSdks!!)
return integers
`

2022-12-20 17:02 UTC, Prince-kushwaha commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
> +            return Intent(targetContext, NoteEditor::class.java).also {
ok

2022-12-20 17:06 UTC, Prince-kushwaha commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
> +    private val invalidSdksImpl: List<Int>
No getter is fine there is no need to simplify getter

2022-12-24 18:22 UTC, lukstbit approved these changes

2022-12-24 18:23 UTC, merged