KotlinCleanup - ContentProviderTest
ankidroid/Anki-Android pull request #13007
Opened 2022-12-18 23:23 UTC by TimSta82

## Pull Request template

## Purpose / Description
Solve some Kotlin Cleanup tasks within ContentProviderTest.kt

## Fixes
- rename variable
- apply equalTo
- add explicit return types for better readability

## Approach
_How does this change address the problem?_

## How Has This Been Tested?
Successful running unit test

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-12-19 10:09 UTC, lukstbit requested changes
Thanks for contributing!
Besides the issues below, your PR also contain some changes that shouldn't be done:

- adding the type to variables, this is only needed if the IDE raises an issue(you'll see a brown dotted line) otherwise this is verbose(kotlin can infer the type based on the right side value) and also makes things harder to review by introducing unrelated changes
- changing imports. The imports should be changed only as a direct change introduced by a cleanup, there's no need to re arrange or change from * to individual imports etc.

2022-12-19 10:09 UTC, lukstbit commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
> +            put(FlashCardsContract.ReviewInfo.SUSPEND, CONTENT_VALUE_SUSPEND)
Although the cleanup said to rename, the variable _suspend_ should be deleted and `1` used directly. It doesn't make sense to use a constant here as it's only one usage.

2022-12-19 10:09 UTC, lukstbit commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
> -@KotlinCleanup("is -> equalTo")
The annotation should be deleted only if all targeted cleanups were solved. There are more usages of `is` inside this class. So either keep the annotation or delete it and solve all related issues.

2022-12-19 14:20 UTC, TimSta82 commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
> +            put(FlashCardsContract.ReviewInfo.SUSPEND, CONTENT_VALUE_SUSPEND)
done

2022-12-19 14:25 UTC, TimSta82 commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
> -@KotlinCleanup("is -> equalTo")
Added annotation back again.

I've reverted the explicit return types as well, but they don't harm and increase the readability, especially in PRs, imo.

2022-12-20 18:26 UTC, mikehardy commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
> -@KotlinCleanup("is -> equalTo")
Any line changed in a PR increases PR review load and the chance there is some error

General rule - the best code is no code, second best code is code you delete, third best code is code you don't touch

Of course refactoring is good, of course adding features and creating software is good, but this is a big app already with lots of complication and a really high PR flow. PR review time and QA time is at a premium, so touch things ("change a line of code") only if you really must, and then make sure they are in a clean / well-thought-out commit that does one thing and does it will if at all possible

2023-02-25 18:37 UTC, closed without merging