Added undo and clear button on drawing panel
ankidroid/Anki-Android pull request #13004
Opened 2022-12-18 11:51 UTC by Aayush2111

## Pull Request template

## Purpose / Description
Added undo and clear button on drawing panel

## Fixes
Fixes #12979 

## Approach
By adding undo button we can undo our last stroke and clear button will clear all the screen

## How Has This Been Tested?

Tested on physical device- android version 11

![WhatsApp Image 2022-12-18 at 17 20 57](https://user-images.githubusercontent.com/85586404/208296793-0b0cb56f-a04e-4070-9203-e2820ab93d0c.jpg)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-12-18 12:54 UTC, pratyaksh1610 requested changes
🚀 Congratulations on your first PR ! . Some changes before the initial pass. I think you should remove the portion which you have commented for smooth review process and run `./gradlew ktlintFormat` to format the code as per the standards.

2022-12-18 13:24 UTC, Aayush2111 commented
> 

done, thanks! :)

2022-12-23 18:00 UTC, pratyaksh1610 requested changes

2022-12-23 18:00 UTC, pratyaksh1610 commented on AnkiDroid/src/main/res/layout/reviewer_whiteboard_editor.xml
> +
Please remove these unnecessary lines of code.

2022-12-23 18:02 UTC, pratyaksh1610 commented
@Aayush2111 I think a sidebar would be a better option in my opinion . Thanks !

2022-12-26 19:49 UTC, Aayush2111 commented
> @Aayush2111 I think a sidebar would be a better option in my opinion . Thanks !

like permanent sidebar on the left side of the screen or at bottom?

2022-12-26 21:57 UTC, BrayanDSO requested changes
Tested on SDK 33 emulator, Pixel 2

Functionality-wise, the main issues I see are:
1. the undo and clear canvas buttons don't appear on light themes,
    - ![image](https://user-images.githubusercontent.com/69634269/209584815-e1a5edc3-4931-42c5-92b6-82b25303e652.png)
2. The user can't scroll to the green and black colors you added
2. The color buttons close the whiteboard editor while the new buttons don't. I believe that it would be better to be consistent and not close the editor after tapping a color button.
3. *optional*: if you want to, making the undo button faded if there isn't anything to undo would be nice
4. *optional*: it would be good to be able to undo a `Clear canvas` action

About the PR organization itself:
1. There are some merge commits, which normally isn't a problem, but on AnkiDroid we strive to keep a linear git history, so we only do squash and rebase merges. This means that if you want your git history to be merged, you'd better rebase the PR. Otherwise, you can leave the merge commits as is, and the PR will be squashed when it is merged.
2. The commits could be more helpful
    - They should describe what the changes intend to do
    - They shouldn't have temporary changes as commenting a whole block of code just to test things
3.

2022-12-26 21:57 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
> +        // Draw the current state of the canvas
unnecessary

2022-12-26 21:57 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
> +
unnecessary blank line

2022-12-26 21:57 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
> +
unnecessary blank line

2022-12-26 21:57 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
> +import java.util.*
do we need this import?

2022-12-26 21:57 UTC, BrayanDSO commented on AnkiDroid/src/main/res/layout/reviewer_whiteboard_editor.xml
>          style="@style/reviewer_whiteboard_editor_button_style"/>
Why are you adding a new color and changing the colors order?

As you haven't described your approach on the commits or the PR description, I can't tell

2022-12-26 21:57 UTC, BrayanDSO commented on AnkiDroid/src/main/res/layout/reviewer_whiteboard_editor.xml
> +        android:background="@color/flag_red"
Same here. Why are you changing this to `flag_red`?

2022-12-27 13:54 UTC, Aayush2111 commented
Working on the requested changes!

2022-12-28 19:00 UTC, Aayush2111 commented
> 1. the undo and clear canvas buttons don't appear on light themes,
-Resolved

> 2. The user can't scroll to the green and black colors you added
-Resolved

> 3. The color buttons close the whiteboard editor while the new buttons don't. I believe that it would be better to be consistent and not close the editor after tapping a color button.
- I guess it'd be better if clicking on colors close the editor as it will provide more space for us to draw while other buttons can stay as it is since it will be frustrating if we have to undo more than one stroke and manually opening editor again and again. I didn't change this as of now, but do let me know if you think editor shouldn't get close after tapping a color button, I will fix it.

> 4. _optional_: if you want to, making the undo button faded if there isn't anything to undo would be nice
-I have tried adding new drawable _ic_undo_selector.xml_ which will link to _ic_undo_disabled.xml_ (if android:state_enabled="false") and _ic_undo_white.xml_, but this doesn't work for some reason only _ic_undo_white.xml_ is working. I am not quite sure what I am missing extra?

2023-01-06 17:19 UTC, BrayanDSO commented
> The user can't scroll to the green and black colors you added
Resolved

Here I still cannot do that

2023-01-06 17:43 UTC, Aayush2111 commented
> > The user can't scroll to the green and black colors you added
> > Resolved
> 
> Here I still cannot do that

I have removed the green color on platelet by default, working fine for me

screenshot: 
![WhatsApp Image 2023-01-06 at 23 13 13](https://user-images.githubusercontent.com/85586404/211068502-59ddc703-961a-4eb4-b0fd-9b33151616df.jpg)
![WhatsApp Image 2023-01-06 at 23 13 13](https://user-images.githubusercontent.com/85586404/211068524-71e99c05-16f3-435c-8d80-0d4abfcf36dd.jpg)

2023-01-06 18:39 UTC, BrayanDSO commented
> I have removed the green color on platelet by default, working fine for me

Getting rid of things without need isn't a good way of solving problems IMO.

2023-01-06 18:49 UTC, Aayush2111 commented
> IMO.

I see, but other way would be to change the platelet structure completely as keeping all default colors with current platelet structure with extra two buttons now doesn't seem ideal to me.

Should I restructure the platelet then?

2023-01-06 18:51 UTC, BrayanDSO commented
> Should I restructure the platelet then?

I think that this is a good idea

2023-01-06 19:13 UTC, Aayush2111 commented
> > Should I restructure the platelet then?
> 
> I think that this is a good idea



> > Should I restructure the platelet then?
> 
> I think that this is a good idea

![WhatsApp Image 2023-01-07 at 00 42 33](https://user-images.githubusercontent.com/85586404/211082938-9f6d83bb-c700-4a13-b095-2bac60ec1f02.jpg)

Is something like this ideal? 
PS: sorry for bad drawing :P

2023-02-22 01:09 UTC, david-allison commented
@Aayush2111 If you're around, I'm back and happy to work to get this to completion

2023-03-15 02:45 UTC, closed without merging

2023-03-21 22:20 UTC, SanjaySargam commented
Hey @Aayush2111 If you are not working on it then let me know. I would love to continue this implementation

2023-03-21 22:54 UTC, Aayush2111 commented
> Hey @Aayush2111 If you are not working on it then let me know. I would love to continue this implementation

Sure, go for it.

2023-03-21 23:13 UTC, SanjaySargam commented
@Aayush2111 Thanks for informing