[Kotlin cleanup] AnkiAssert.kt,CollectionAssert.kt,ExportingTest.kt
ankidroid/Anki-Android pull request #13024
Opened 2022-12-22 04:29 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
Kotlin Cleanup of  AnkiAssert.kt,CollectionAssert.kt,ExportingTest.kt

2022-12-24 17:56 UTC, lukstbit requested changes

2022-12-24 17:56 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssert.kt
> +        SchedV2._fuzzIvlRange(targetIvl).apply {
I don't think this reads better and should be changed to only use in the `in` operator:

```
val minMax = SchedV2._fuzzIvlRange(targetIvl)
return  c.ivl in minMax.first..minMax.second
```

2022-12-24 17:56 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/testutils/libanki/CollectionAssert.kt
>  import org.hamcrest.core.Is.*
Isn't this import unused now?

2022-12-25 06:16 UTC, Prince-kushwaha commented on AnkiDroid/src/test/java/com/ichi2/testutils/libanki/CollectionAssert.kt
>  import org.hamcrest.core.Is.*
org.hamcrest.core.Is.*
it is unused I remove this import

2022-12-26 17:44 UTC, lukstbit approved these changes

2022-12-26 17:44 UTC, merged