TextUtils.join and .isEmpty changed to kotlin methods
ankidroid/Anki-Android pull request #13039
Opened 2022-12-27 06:01 UTC by soCallmeAdityaKumar

## Pull Request template

## Purpose / Description
cleanup:Changed TextUtils.join to .jointostring and TextUtils.isEmpty to .isNullOrEmpty/isEmpty

## Fixes
https://github.com/ankidroid/Anki-Android/issues/13036

## Checklist
_Please, go through these checks before submitting the PR._

- [✓] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [✓] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2022-12-28 09:41 UTC, criticalAY reviewed
I reviewed most of the files but not all waiting for a response

2022-12-28 09:41 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                Timber.d("Changed the SnackBar", "Snackbar")
Could you explain these changes?

2022-12-28 09:41 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerCustomFonts.kt
> +            if (mDominantFontStyle!!.isEmpty()) {
Why `!!` ?

2022-12-28 09:41 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerCustomFonts.kt
> +                if (mDominantFontStyle!!.isEmpty()) {
Same

2022-12-28 09:41 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/libanki/Finder.kt
> +            if (txt.isNullOrEmpty()) {
`isEmpty` is more suited here

2022-12-28 09:41 UTC, criticalAY commented on annotations/README.md
> +```xml
Why this?

2022-12-28 09:41 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        val locale: Locale = if (tempLocaleCode.contains("_") || tempLocaleCode.contains("-")) {
I am not in the favour of removing this condition from here

2022-12-28 10:28 UTC, criticalAY commented
You marked resolved but are they?

2022-12-28 16:13 UTC, criticalAY commented
You still haven't took care of few things that I mentioned.

2022-12-31 12:20 UTC, BrayanDSO requested changes
Tests fail and it's better to use `.isNullOrEmpty()` instead of `?.isEmpty() == true`

2022-12-31 12:31 UTC, soCallmeAdityaKumar commented
> Tests fail and it's better to use `.isNullOrEmpty()` instead of `?.isEmpty() == true`

ok i will do it right now

2023-01-01 19:51 UTC, soCallmeAdityaKumar commented
@BrayanDSO @criticalAY  I think my checks are failing because of the ankiAndroidBackend file that I have not install( placed correctly)  ( I have windows OS). Can you please assist me in doing that.

2023-01-02 00:18 UTC, BrayanDSO commented
You can see the failed tests log by clicking on `Details` by the tests side here on GitHub.

There, it shows the following failed test:
```
FinderTest > test_findCards FAILED
    java.lang.AssertionError: expected:<5> but was:<0>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at com.ichi2.libanki.FinderTest.test_findCards(FinderTest.kt:276)
```
As this is an error on `FinderTest.kt`, which tests `Finder.kt`, and you've modified `Finder.kt`, probably the error is somewhere there, so you should try fixing it.

---
About your problem with the backend installation, I can't tell exactly what you mean, so I suggest reading [this article](https://stackoverflow.com/help/how-to-ask) about how to ask better a question on the internet and going to AnkiDroid Discord so someone can answer you better

2023-01-02 00:34 UTC, dae commented
https://github.com/ankidroid/Anki-Android/issues/8482#issuecomment-1100924517

2023-01-02 03:16 UTC, soCallmeAdityaKumar commented
> You can see the failed tests log by clicking on `Details` by the tests side here on GitHub.
> 
> There, it shows the following failed test:
> 
> ```
> FinderTest > test_findCards FAILED
>     java.lang.AssertionError: expected:<5> but was:<0>
>         at org.junit.Assert.fail(Assert.java:89)
>         at org.junit.Assert.failNotEquals(Assert.java:835)
>         at org.junit.Assert.assertEquals(Assert.java:120)
>         at org.junit.Assert.assertEquals(Assert.java:146)
>         at com.ichi2.libanki.FinderTest.test_findCards(FinderTest.kt:276)
> ```
> 
> As this is an error on `FinderTest.kt`, which tests `Finder.kt`, and you've modified `Finder.kt`, probably the error is somewhere there, so you should try fixing it.
> 
> About your problem with the backend installation, I can't tell exactly what you mean, so I suggest reading [this article](https://stackoverflow.com/help/how-to-ask) about how to ask better a question on the internet and going to AnkiDroid Discord so someone can answer you better

Ok I am looking over it.

2023-01-02 03:17 UTC, soCallmeAdityaKumar commented
> [#8482 (comment)](https://github.com/ankidroid/Anki-Android/issues/8482#issuecomment-1100924517)

Thanks

2023-01-02 23:46 UTC, BrayanDSO requested changes
Overall, the PR seems pretty good. Thanks for the job!

The requested changes are more about avoiding leaving IDE lints.

Another request that I do is to remove the last two usages of `TextUtils.isEmpty()` on `DeckOptionsActivity.kt`, so we can close the issue

2023-01-02 23:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
> +            if (!tmpname.isEmpty()) {
The IDE actually suggests this
```suggestion
            if (tmpname.isNotEmpty()) {
```

2023-01-02 23:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Finder.kt
> +            sql += if (!preds.isEmpty()) {
remove the `!` and use `isNotEmpty()`, as the IDE suggests

2023-01-02 23:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Finder.kt
> +            if (!order.isEmpty()) {
ditto

2023-01-02 23:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        if (tempLocaleCode == null || tempLocaleCode.isEmpty()) {
```suggestion
        if (tempLocaleCode.isNullOrEmpty()) {
```

2023-01-02 23:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
> +                        if (!csum.isEmpty()) {
remove the `!` and use `isNotEmpty()`, as the IDE suggests

2023-01-02 23:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Model.kt
> +            if (!sfld[i].trim { it <= ' ' }.isEmpty()) {
remove the `!` and use `isNotEmpty()`, as the IDE suggests

2023-01-02 23:46 UTC, BrayanDSO commented on annotations/README.md
>  ```
Unnecessary/Unrelated changes. Please revert

2023-01-02 23:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.kt
> +        if (!resp.optString("err").isEmpty()) {
remove the `!` and use `isNotEmpty()`, as the IDE suggests

2023-01-02 23:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerCustomFonts.kt
> +            if (mDominantFontStyle?.isEmpty() == true) {
```suggestion
            if (mDominantFontStyle.isNullOrEmpty()) {
```

2023-01-02 23:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerCustomFonts.kt
> +                if (mDominantFontStyle?.isEmpty() == true) {
```suggestion
                if (mDominantFontStyle.isNullOrEmpty()) {
```

2023-01-02 23:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +        if (!search.trim { it <= ' ' }.isEmpty()) {
remove the `!` and use `isNotEmpty()`, as the IDE suggests

2023-01-02 23:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt
> +            if (!search.trim { it <= ' ' }.isEmpty()) {
remove the `!` and use `isNotEmpty()`, as the IDE suggests

2023-01-02 23:46 UTC, BrayanDSO commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/Shared.kt
> +        val suffix = if (!name.isEmpty()) {
remove the `!` and use `isNotEmpty()`, as the IDE suggests

2023-01-02 23:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.kt
> +        if (!lim.isEmpty()) {
remove the `!` and use `isNotEmpty()`, as the IDE suggests

2023-01-02 23:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.kt
> +        if (!dayFilter.isEmpty()) {
remove the `!` and use `isNotEmpty()`, as the IDE suggests

2023-01-02 23:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
> +            if (mToolbarSearchItem!!.isActionViewExpanded && !query.isEmpty()) {
remove the `!` and use `isNotEmpty()`, as the IDE suggests

2023-01-02 23:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateFilters.kt
> +            if (!txt.isEmpty()) {
remove the `!` and use `isNotEmpty()`, as the IDE suggests

2023-01-02 23:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateFilters.kt
> +            if (!txt.isEmpty() && !extra.isEmpty()) {
remove the `!` and use `isNotEmpty()`, as the IDE suggests

2023-01-02 23:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateFilters.kt
> +                if (!m.group(4).isNullOrEmpty()) {
remove the `!` and use `isNotEmpty()`, as the IDE suggests

2023-01-02 23:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Utils.kt
> +            if (!value.isEmpty()) {
remove the `!` and use `isNotEmpty()`, as the IDE suggests

2023-01-04 23:12 UTC, BrayanDSO commented
I'm not sure if you want another review, @soCallmeAdityaKumar, buf if you do, there are some unresolved requests to do first

2023-01-05 05:07 UTC, soCallmeAdityaKumar commented
> Overall, the PR seems pretty good. Thanks for the job!
> 
> The requested changes are more about avoiding leaving IDE lints.
> 
> Another request that I do is to remove the last two usages of `TextUtils.isEmpty()` on `DeckOptionsActivity.kt`, so we can close the issue

I have done this in DeckOptionsActivity

2023-01-05 12:18 UTC, soCallmeAdityaKumar commented
@BrayanDSO  i have addressed all your requested changes

2023-01-06 16:09 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Model.kt
> +            if (!sfld[i].trim { it <= ' ' }.isEmpty()) {
Hasn't been resolved

2023-01-06 16:09 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.kt
> +        if (!resp.optString("err").isEmpty()) {
Hasn't been resolved

2023-01-06 16:09 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerCustomFonts.kt
> +            if (mDominantFontStyle?.isEmpty() == true) {
Hasn't been resolved

2023-01-06 16:09 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerCustomFonts.kt
> +                if (mDominantFontStyle?.isEmpty() == true) {
Hasn't been resolved

2023-01-06 16:09 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt
> +        if (!search.trim { it <= ' ' }.isEmpty()) {
Hasn't been resolved

2023-01-06 16:09 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt
> +            if (!search.trim { it <= ' ' }.isEmpty()) {
Hasn't been resolved

2023-01-06 16:09 UTC, BrayanDSO commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/Shared.kt
> +        val suffix = if (!name.isEmpty()) {
Hasn't been resolved

2023-01-06 16:10 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.kt
> +        if (!lim.isEmpty()) {
Hasn't been resolved

2023-01-06 16:10 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.kt
> +        if (!dayFilter.isEmpty()) {
Hasn't been resolved

2023-01-06 16:11 UTC, BrayanDSO commented
@soCallmeAdityaKumar, I commented with `Hasn't been resolved` the changes that haven't been resolved. Github hides some requests when there are many, so make sure to unhide them

2023-01-06 18:36 UTC, BrayanDSO approved these changes
LGTM. Thanks!

2023-01-06 20:38 UTC, criticalAY approved these changes

2023-01-06 23:02 UTC, BrayanDSO commented
We have the second approval of @criticalAY, so we are good to go

2023-01-06 23:05 UTC, merged