update: unit test in DuplicateTextInPreferencesXmlTest.kt
ankidroid/Anki-Android pull request #13049
Opened 2023-01-01 15:39 UTC by oyeraghib

## Purpose / Description
Update unit test inside DuplicateTextInPreferencesXmlTest.kt

## Approach
Removed Java Strings and added Kotlin Multi-line strings. 
Updated the expected result with actual result in case of invalid .xml file because of Duplicate Text In Prefereneces.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-01-03 00:02 UTC, BrayanDSO requested changes

2023-01-03 00:02 UTC, BrayanDSO commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/DuplicateTextInPreferencesXmlTest.kt
> +                             android:summary="@string/force_full_sync_summary" />
Isn't this too much indented? (one level more than it should)

2023-01-03 05:29 UTC, oyeraghib commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/DuplicateTextInPreferencesXmlTest.kt
> +                             android:summary="@string/force_full_sync_summary" />
Fixed

2023-01-03 13:00 UTC, BrayanDSO approved these changes
LGTM. Thanks!

2023-01-05 16:04 UTC, lukstbit requested changes
There are a lot of leftover `\` in the new strings which should be deleted as well.

2023-01-05 16:04 UTC, lukstbit commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/DuplicateTextInPreferencesXmlTest.kt
> -        "    android:summary=\"@string/pref_cat_advanced_summ\"                         " +
Why was this deleted in the multiline string?

2023-01-06 19:20 UTC, oyeraghib commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/DuplicateTextInPreferencesXmlTest.kt
> -        "    android:summary=\"@string/pref_cat_advanced_summ\"                         " +
It was deleted by mistake. I have added it back.

2023-01-06 19:21 UTC, oyeraghib commented
> There are a lot of leftover `\` in the new strings which should be deleted as well.

Fixed.

2023-01-10 17:54 UTC, merged