Apply AGP 7.2 update recommendations
ankidroid/Anki-Android pull request #13067
Opened 2023-01-05 16:24 UTC by RSBat

## Pull Request template

## Purpose / Description
Remove usages of deprecated dsl. Declaring package is manifest also seems to be incompatible with AGP 8.0 

## Fixes
Fixes #11288

## Approach
Follows the update recommendations. The only surprising change is `textOutput`, it outputs to `stdout` by default ([docs](https://developer.android.com/reference/tools/gradle-api/7.3/com/android/build/api/dsl/Lint#textOutput()))

## How Has This Been Tested?

Ran build, lint and tests

## Learning (optional, can help others)
AGP DSL reference - very useful when Android Studio doesn't want to help you https://developer.android.com/reference/tools/gradle-api

Application id vs namespace: https://developer.android.com/studio/build/configure-app-module#set-namespace

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-01-06 16:24 UTC, BrayanDSO approved these changes
Really really good. It is always nice to polish the gradle scripts. The docs links helped a lot too. Thanks!

2023-02-06 02:01 UTC, mikehardy approved these changes
These look great - thank you!
I don't think anything will go wrong but I'm working on dependency updates right now and I'm going to mark this as blocked by dependency on #13198 but I'll handle the rebase+repush as I shepherd that through

2023-02-06 19:11 UTC, mikehardy commented
rebased, anyone that can merge should merge if/when CI goes green :heavy_check_mark:

2023-02-06 19:13 UTC, mikehardy commented
Ooo - glad I was cautious here. This is new!

```

* What went wrong:
Execution failed for task ':api:processDebugAndroidTestManifest'.
> Error while evaluating property 'namespace' of task ':api:processDebugAndroidTestManifest'.
   > Failed to calculate the value of task ':api:processDebugAndroidTestManifest' property 'namespace'.
      > Failed to calculate the value of property 'namespace'.
         > namespace and testNamespace have the same value ("com.ichi2.anki.api"), which is not allowed.


```

2023-02-06 19:14 UTC, mikehardy requested changes

2023-02-06 19:14 UTC, mikehardy commented on api/build.gradle
> +    testNamespace "com.ichi2.anki.api"
Apparently this is no longer allowed !? Passed before though, I saw it...

2023-02-08 04:23 UTC, RSBat commented on api/build.gradle
> +    testNamespace "com.ichi2.anki.api"
Interesting. [Corresponding ticket is closed in Aug 2022](https://issuetracker.google.com/issues/233369034), but I guess it didn't make it into AGP 7.3 ([Sep 2022](https://developer.android.com/studio/past-releases/past-agp-releases/agp-7-3-0-release-notes)). [The docs also now have a warning](https://developer.android.com/studio/build/configure-app-module#change-namespace-for-testing) which I don't remember seeing.

I can check later if changing the test namespace breaks anything

2023-02-16 15:37 UTC, closed without merging