Removed Snackbar
ankidroid/Anki-Android pull request #13073
Opened 2023-01-06 17:37 UTC by SanjaySargam

## Pull Request template

## Purpose / Description
Showing snackbar isn't useful because we can even review card using controller/external keyboard

## Fixes
Fixes #13002 

## How Has This Been Tested?

Virtual Emulator ( Pixel 6 Pro API 29 )

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-01-06 18:42 UTC, BrayanDSO requested changes

2023-01-06 18:42 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
> +            true
Should be removed

2023-01-07 02:36 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
> +            true
Okk

2023-01-07 09:48 UTC, BrayanDSO approved these changes
LGTM. Something I suggest doing in the future is using `git amend` and `git rebase` to keep the commits organized and easier to review

2023-01-07 09:49 UTC, SanjaySargam commented
> LGTM. Something I suggest doing in the future is using `git amend` and `git rebase` to keep the commits organized and easier to review

Ok 
Will take care next time

2023-01-08 21:14 UTC, criticalAY commented
This closes #12986 and fixes #12940

2023-01-08 21:14 UTC, criticalAY approved these changes
LGTM

2023-01-08 21:22 UTC, criticalAY commented
@BrayanDSO please remember to take care of the issue and the PR I mentioned above

2023-01-09 10:14 UTC, BrayanDSO commented
> please remember to take care of the issue and the PR I mentioned above

Thanks. Edited the PR's text

2023-01-10 03:41 UTC, SanjaySargam commented
@BrayanDSO 
This also fixes #12995

2023-02-17 13:56 UTC, mikehardy approved these changes
LGTM - confirmed (via direct inspection of crowdin activity timeline) strings activity quiet enough to just merge + resync after

2023-02-17 13:56 UTC, merged