Display
ankidroid/Anki-Android pull request #13082
Opened 2023-01-08 06:20 UTC by soCallmeAdityaKumar

## Fixes
9333

2023-01-08 12:14 UTC, criticalAY commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.kt
> +        @RequiresApi(Build.VERSION_CODES.R)
This is not a good idea to place the API call here as this would cause an issue with API <R

2023-01-08 13:45 UTC, soCallmeAdityaKumar commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.kt
> +        @RequiresApi(Build.VERSION_CODES.R)
Okk now i have made changed in it .

2023-01-08 18:21 UTC, pratyaksh1610 commented
Please fill the PR template for smooth review process.

2023-01-09 10:06 UTC, BrayanDSO requested changes

2023-01-09 10:06 UTC, BrayanDSO commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.kt
> +            } else false
This now returns false to everyone that uses an Android version lower than R, which wasn't the way this method worked before

2023-01-09 10:07 UTC, BrayanDSO commented
And I strongly suggest to edit the PR title as "Display" isn't a descriptive one

2023-01-09 14:09 UTC, soCallmeAdityaKumar commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.kt
> +            } else false
@BrayanDSO so can i use the previous method for API not equal to 30 and for API 30 this can be suitable?

2023-01-10 19:03 UTC, criticalAY requested changes

2023-01-10 19:03 UTC, criticalAY commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.kt
>      @Suppress("deprecation") // #9333: getDefaultDisplay & getMetrics
The suppress annotation is still here and if you remove it, the code will show an error please go through the compact files as I suggested to handle it properly

2023-01-11 13:59 UTC, soCallmeAdityaKumar commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.kt
>      @Suppress("deprecation") // #9333: getDefaultDisplay & getMetrics
can you please share me some resources to work with it .

2023-01-11 18:07 UTC, soCallmeAdityaKumar commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.kt
>              val screenSw = Math.min(widthDp, heightDp)
ok i will do it

2023-01-11 19:39 UTC, criticalAY commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.kt
>      @Suppress("deprecation") // #9333: getDefaultDisplay & getMetrics
Go through the compat file and there is an open issue regarding deprecation go through that you will get and idea

2023-01-24 10:23 UTC, closed without merging