fixed the crash that occured due to `getResources()` error
ankidroid/Anki-Android pull request #13086
Opened 2023-01-09 08:29 UTC by criticalAY

## Pull Request template
crash fix

## Purpose / Description
this error was caused due to the `resource` method which requires a fragment attached to some activity but when we closed the application the dialog had no activity to attach hence the crash.

## Fixes
Fixes #13085

## Approach
used the application context itself to avoid the crash and access the resources(string in this case)

## How Has This Been Tested?
Tested on oneplus nord ce

https://user-images.githubusercontent.com/48384865/211266804-8ece0aa7-9931-49e3-89a7-415dc66fbcc4.mp4

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-01-09 08:31 UTC, criticalAY commented
I will make one more commit to directly use the `appResources` from the import itself I mean will simplify it

2023-01-09 14:27 UTC, criticalAY commented
It is creating the language issue but Brayan  the ` notificationMessage` and `notificationTitle` properties are part of the `AsyncDialogFragment` class, which means that they are not specific to a particular instance of the` ImportDialog` class. As a result, they will not retain their data when the fragment is detached and reattached.

2023-01-10 05:25 UTC, criticalAY commented
@BrayanDSO 
![test2](https://user-images.githubusercontent.com/48384865/211468768-3f37d58d-61ec-491a-bc67-713afb0bfb40.jpg)
, I have taken care of it in the latest commit

2023-01-13 18:57 UTC, BrayanDSO requested changes

2023-01-13 18:57 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +            val message = resources.getString(R.string.import_interrupted)
`showAsyncDialogFragment` is a generic method used to show a variety of dialogs. This currently hardcodes it to always show the import dialog title and message

2023-01-13 20:31 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +            val message = resources.getString(R.string.import_interrupted)
then I think it would be the best to use ViewModel or services, I'll go with that approach

2023-01-13 22:38 UTC, criticalAY commented
@BrayanDSO as far as I have researched through the documentation to access the resources we need some context and here in our case there is no context for the fragment to attach to even if we use the ViewModel it is of no use because viewmodels also require some context for initiation say we can store the resource value using ViewModel  inside `onDestory` but we won't we able to retrieve it as there would we no context(as the activity/fragment is not opening), So either we use an if-else condition (here we will have a restriction for the language but the crash would be avoided) or leave it as it is(which is no good either).

Waiting for your response

2023-01-14 14:23 UTC, BrayanDSO commented
Can we check if context is null and return on the method or kill the fragment if necesary?

This probably isn't the proper Android way to do things, but I don't have the time to investigate it myself right now.

2023-01-18 20:39 UTC, criticalAY commented
![Screenshot_2](https://user-images.githubusercontent.com/48384865/213289624-c023f0a8-3b08-4fab-8163-476babd0b9ac.png)
Test

2023-01-18 20:40 UTC, criticalAY commented
@BrayanDSO I think this one should work

2023-02-06 23:48 UTC, criticalAY commented
@BrayanDSO could you please look into it whenever you are free

2023-02-19 07:03 UTC, criticalAY commented
@david-allison Could you review this PR whenever you are free

2023-02-19 14:51 UTC, david-allison requested changes
Not too familiar here, but I feel we have a solution in the base class which will resolve this

2023-02-19 14:51 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt
> +            return asyncMessageContent
I'd wager replacing this with `res().getString` is a better approach

2023-02-19 19:44 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt
> +            return asyncMessageContent
`res()` was removed in one of the previous PR

2023-02-19 19:52 UTC, criticalAY commented
I have already tried this `val res = AnkiDroidApp.appResources` approach it restricts the language from the strings

2023-03-06 01:33 UTC, david-allison commented
Sorry this sat, missed the reply

2023-03-06 08:01 UTC, criticalAY commented
No issue thanks!

2023-03-06 16:40 UTC, mikehardy approved these changes
LGTM - thanks!

2023-03-06 16:40 UTC, merged