Fix getParcelableArrayList deprecation
ankidroid/Anki-Android pull request #13113
Opened 2023-01-12 19:01 UTC by RobozinhoD

## Purpose / Description
Fix getParcelableArrayList deprecation

## Fixes
Fixes part of #12364

## Approach
Added it to compat

## How Has This Been Tested?

Opened the browser and selected a deck

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-01-13 18:54 UTC, BrayanDSO approved these changes
LGTM. Thanks!

2023-01-14 07:52 UTC, lukstbit requested changes
This took some conflicts from the previous PR being merged...

2023-01-14 07:52 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
> +        inline fun <reified T : Parcelable> Bundle.getParcelableArrayListCompat(key: String, clazz: Class<T>): ArrayList<T>? {
The name of the method should be `getParcelableArrayList` to fully replicate the newer platform version. This way, when api 33 will be the minimum supported level, we will be able to simply delete the compatibility code and then change some imports where the method is used(without changing the actual code, like having to rename).

2023-01-14 14:09 UTC, RobozinhoD commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
> +        inline fun <reified T : Parcelable> Bundle.getParcelableArrayListCompat(key: String, clazz: Class<T>): ArrayList<T>? {
This leads to this error 

Extension is shadowed by a member: public open fun <T : Any!> getParcelableArrayList(key: String?, clazz: Class<out T!>): ArrayList<T!>?

2023-01-15 09:15 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
> +        inline fun <reified T : Parcelable> Bundle.getParcelableArrayListCompat(key: String, clazz: Class<T>): ArrayList<T>? {
Yes, I didn't realize it's going to conflict with the platform version :(

2023-01-15 09:18 UTC, lukstbit approved these changes
Thanks!

2023-01-15 09:21 UTC, merged