Fix resolveService deprecation
ankidroid/Anki-Android pull request #13110
Opened 2023-01-12 16:59 UTC by RobozinhoD

## Purpose / Description
Fix resolveService deprecation

## Fixes
Fixes part of #12364 

## Approach
Bases myself on #12422 and added a method to compat

## How Has This Been Tested?

I didn't know how to test it

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-01-14 08:05 UTC, lukstbit requested changes
The newer version of `resolveService` uses the api level 33 class [ResolveInfoFlags](https://developer.android.com/reference/android/content/pm/PackageManager.ResolveInfoFlags). I think we should duplicate this functionality to easier migrate later to the platform code. This was almost done in #12550 (which also needs it) and I'm inclined to put this PR on hold until that PR is merged(so we can use the class introduced there).

Of course if you want to work on it now I can review it.

2023-01-14 08:05 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
> +        fun PackageManager.resolveServiceCompat(intent: Intent, flags: Int): ResolveInfo? {
The name should be `resolveService` to follow the platform naming for easier migration. See #12550 for a similar case(for `resolveActivity`) where I explained how to tackle this.

2023-01-14 14:19 UTC, RobozinhoD commented
> I think we should duplicate this functionality to easier migrate later to the platform code

I find this harder

2023-01-14 14:20 UTC, RobozinhoD commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
> +        fun PackageManager.resolveServiceCompat(intent: Intent, flags: Int): ResolveInfo? {
warning "Extension is shadowed by a member: public abstract fun resolveService(intent: Intent, flags: Int): ResolveInfo?"

2023-02-15 22:32 UTC, david-allison commented
Agreed with the above. See: https://github.com/ankidroid/Anki-Android/pull/13250 for an example

2023-02-15 22:32 UTC, david-allison requested changes

2023-02-15 22:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
> +        fun PackageManager.resolveServiceCompat(intent: Intent, flags: Int): ResolveInfo? {
Resolving - valid reasoning

2023-02-19 13:06 UTC, RobozinhoD commented
the example helped a lot, thx

2023-02-19 13:51 UTC, david-allison approved these changes
Awesome

2023-02-19 13:57 UTC, mikehardy approved these changes
David established the pattern prior and likes it - looks good to me as well, thank you!

2023-02-19 13:57 UTC, merged