added sync disabled icon to be shown during migration
ankidroid/Anki-Android pull request #13130
Opened 2023-01-17 09:11 UTC by criticalAY

## Pull Request template

## Purpose / Description
Fixes #13129

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?
tested on oneplus nord ce
![testsync](https://user-images.githubusercontent.com/48384865/212856563-d32ed629-d20f-4022-9a43-55fd7aa3cc21.jpg)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-01-17 21:49 UTC, BrayanDSO commented
This icon's arrows look different from the default sync icon.

I'd rather if we made our own new icon similar to this, with a line crossing the sync icon we use.

2023-01-17 22:17 UTC, criticalAY commented
The sync error icon is also in the same fashion as above and I took this one from the vector asset from where we are using the current sync icon and the sync error icon.

2023-01-18 17:09 UTC, lukstbit commented
I think the added icon is ok although it isn't like the current one, the change is most likely due to the strike line which would be in an awkward position with our current icon.

My question is if the sync locked icon isn't better as the migration (b)locks the ability to sync:

<img src="https://user-images.githubusercontent.com/52494258/213247840-255eccc4-e4a9-4dbf-92c5-75560e3a7714.png" width="200px" height="200px" />

2023-01-18 18:05 UTC, criticalAY commented
I like this locked sync icon as well so I am in favor of using it as it looks better in my opinion. @david-allison  @BrayanDSO

2023-01-18 18:47 UTC, david-allison commented
"Locked" looks good to me

2023-01-18 19:41 UTC, criticalAY commented
Done! updated it with locked sync icon

2023-01-18 21:34 UTC, david-allison commented
Do you have a sample before/after screenshot?

2023-01-18 21:51 UTC, criticalAY commented
![Screenshot_4](https://user-images.githubusercontent.com/48384865/213302947-0d8570d9-743a-46b9-b151-53cf352c8794.png)
![Screenshot_3](https://user-images.githubusercontent.com/48384865/213302959-2efacda5-07f3-4804-aa68-6b51d0e89ebf.png)

2023-01-19 06:01 UTC, lukstbit requested changes

2023-01-19 06:01 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        if (syncIcon == SyncIconState.Disabled) {
This should be in the when clause above where there is already and entry for SyncIconState.Disabled.

2023-01-21 15:34 UTC, lukstbit approved these changes

2023-02-12 01:09 UTC, oakkitten commented
Personal opinion: I wonder if we can rethink the icon a bit. I think wireframe icons look best when the stroke thickness is consistent. Currently the u-shaped part of the lock is too thin for my taste. Also, the arrows have a different shape and position.

Said that, I think that it's easier to understand than the crossed-out sync icon, even if that one looks better.

2023-02-14 00:49 UTC, david-allison commented
@criticalAY Are you likely to have time to produce/find a better icon, given other work that's in progress currently?

2023-02-14 04:03 UTC, criticalAY commented
Sure, I will provide with few options and then we can discuss and pick one

2023-02-23 14:05 UTC, mikehardy commented
Perfect is the enemy of good enough. We need scoped storage done and this has been stalled on nitpicks for more than a month

2023-02-23 14:07 UTC, mikehardy approved these changes

2023-02-23 14:07 UTC, merged