[KotlinCleanup] - TemporaryModel.kt
ankidroid/Anki-Android pull request #13138
Opened 2023-01-20 14:45 UTC by Ash-2k3

## Fixes
-Added Constructor Property
-Handled Nullability checks
-Replaced getSerializable() with getSerializableWithCast()
-Replaced toBundle() with bundleOf() 

## Checklist

- [] You have a descriptive commit message with a short title (first line, max 50 chars).
- [] You have commented your code, particularly in hard-to-understand areas
- [] You have performed a self-review of your own code
- [] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-01-22 07:51 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
>          get() {
Is the `get()` method still needed?

2023-01-22 20:14 UTC, Ash-2k3 commented on AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
>          get() {
hey @ShridharGoel ..I didn't get it properly..
Can you please tell me more about this problem .

2023-01-23 08:30 UTC, Ash-2k3 commented on AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
>          get() {
> Is the `get()` method still needed?
I went through the code for this....I think we need the `get()` method
The value of `mTemplateChanges` might change  so I think we should be using getter .

I am just a beginner I would love to hear your suggestion !

2023-01-25 15:32 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
>          get() {
You can just write `val templateChanges: ArrayList<Array<Any>> = mTemplateChanges`.

2023-01-25 15:36 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
>          get() {
You can just write `val templateChanges: ArrayList<Array<Any>> = mTemplateChanges`.

2023-01-25 16:19 UTC, Ash-2k3 commented on AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
>          get() {
I have done the suggested changes. Can you review it and let me know if there are any more changes that can be made or is it ready to be merged ?

2023-01-25 17:16 UTC, ShridharGoel approved these changes

2023-01-25 17:18 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
> +            for (c in AnkiDroidApp.instance.cacheDir.listFiles()!!) {
This can be handled in a better way.

2023-01-25 17:19 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
>          get() {
This change is fine now, I have added another comment.

2023-01-25 17:20 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
> +            for (c in AnkiDroidApp.instance.cacheDir.listFiles()!!) {
You can use `?: arrayOf()`.

2023-01-25 17:54 UTC, Ash-2k3 commented on AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
> +            for (c in AnkiDroidApp.instance.cacheDir.listFiles()!!) {
@ShridharGoel Done !!

2023-01-26 13:52 UTC, ShridharGoel approved these changes

2023-01-30 13:31 UTC, lukstbit requested changes

2023-01-30 13:31 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
> +    val templateChanges: ArrayList<Array<Any>> = mTemplateChanges
This doesn't replicate the original code. 
After mTemplateChanges is reinitialized with another list(like in the method above loadTemplateChanges) callers of templateChanges will not see the new list. get() should still be used.

2023-01-30 13:51 UTC, Ash-2k3 commented on AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
> +    val templateChanges: ArrayList<Array<Any>> = mTemplateChanges
@lukstbit Done...Are there any other bugs to fix or is it ready to be merged ?

2023-01-30 23:29 UTC, david-allison requested changes
one nitpick (needs testing), then looks good to me, thanks!

2023-01-30 23:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
> +        val fileName = saveTempModel(AnkiDroidApp.instance.applicationContext, model)
can be inlined:

```kotlin
    fun toBundle(): Bundle = bundleOf(
        INTENT_MODEL_FILENAME to saveTempModel(AnkiDroidApp.instance.applicationContext, model),
        "mTemplateChanges" to mTemplateChanges
    )
```

2023-01-31 01:41 UTC, Ash-2k3 commented on AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
> +        val fileName = saveTempModel(AnkiDroidApp.instance.applicationContext, model)
Yess this makes the same function more concise .....

2023-01-31 02:30 UTC, david-allison approved these changes

2023-01-31 16:07 UTC, lukstbit approved these changes

2023-02-16 00:25 UTC, merged