Fixed Snackbar disappearing after changing the deck path
ankidroid/Anki-Android pull request #13160
Opened 2023-01-27 07:21 UTC by Aditya-gupta99

## Fixes
the snackbar disappear after moving the deck.

## Approach
Change snackbar duration from length_undefined to length_short

## How Has This Been Tested?
- Tests

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-01-27 16:33 UTC, lukstbit approved these changes
Thanks for contributing!

2023-01-27 17:31 UTC, criticalAY requested changes

2023-01-27 17:31 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        showSnackbar(message, Snackbar.LENGTH_SHORT) {
IMO this snack bar should have LENGTH_LONG as it has an action attached to it and the user needs more time to move their fingers across the screen so I suggest changing it to long

2023-02-01 18:32 UTC, criticalAY approved these changes
Thankyou!

2023-02-06 12:11 UTC, merged