Fixed the whiteboard-editor-bug
ankidroid/Anki-Android pull request #13177
Opened 2023-02-01 10:59 UTC by Marius1501

## Pull Request template

## Purpose / Description
The whiteboard-editor overlapped the toolbar when the answerButtonPosition was set to "top" or "none"

## Fixes
Fixes #12388 

## Approach
The position changes to the bottom when the answerButtonPosition is set to "top" or "none".

##Screenshots
| Top  | None |
| ------------- | ------------- |
| ![grafik](https://user-images.githubusercontent.com/109673982/216024395-e932e007-b83b-49ec-98e1-f09ba95ce36e.png)|![grafik](https://user-images.githubusercontent.com/109673982/216024635-bb8587c1-5e36-4d9e-bd76-3f2c27f5f902.png)|

## How Has This Been Tested?

OS: Android 13.0
Device: Pixel 6 Pro

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-02-05 09:19 UTC, lukstbit requested changes
Thanks, looks ok with the two small issues below.

2023-02-05 09:19 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +    private fun updateAnswerButtonPosition() {
The method name should be `updateWhiteboardEditorPosition`, we indeed reference the `answerButtonPosition` preference but it's not the answer buttons that get their position changed.

2023-02-05 09:19 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        mPrefAnswerButtonPosition = super.restorePreferences()
There's no need to go through `restorePreferences()` just to read that preference, accessing the SharedPreferences directly is faster:

`AnkiDroidApp.getSharedPrefs(this).getString...`

2023-02-07 21:22 UTC, BrayanDSO requested changes

2023-02-07 21:22 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +    private var mPrefAnswerButtonPosition: String? = "bottom"
Making `mAnswerButtonsPosition` protected at `AbstractFlashcardViewer` and reusing it would be better to avoid the code duplication

2023-02-10 17:03 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +    private var mPrefAnswerButtonPosition: String? = "bottom"
Your last change has moved mPrefAnswerButtonPosition to AbstractFlashcardViewer, which isn't what I asked. Three steps:

1. Make mAnswerButtonPosition protected at AbstractFlashcardviewer
2. Replace mPrefAnswerButtonPosition usages with mAnswerButtonPosition
3. Remove mPrefAnswerButtonPosition

2023-02-11 07:01 UTC, Marius1501 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +    private var mPrefAnswerButtonPosition: String? = "bottom"
Sry, now it should be ok. 😄

2023-02-11 16:47 UTC, BrayanDSO approved these changes

2023-02-12 07:41 UTC, merged