Update CardBrowser.kt
ankidroid/Anki-Android pull request #13182
Opened 2023-02-01 23:34 UTC by zaidazaize

## Fixes
- converted nullable to  lateinit var type
- Removed notnull (!!) assertions
- simplified comparison logic

## How Has This Been Tested?
- Tests

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-02-03 17:44 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            (
Unnecessary indentation here

2023-02-05 01:30 UTC, zaidazaize commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            (
done

2023-02-05 01:38 UTC, zaidazaize commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            (
removed.

2023-02-09 16:21 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +
Revert this unwanted line

2023-02-09 16:22 UTC, criticalAY approved these changes
Thankyou!
Approving, left a nit though

2023-02-13 14:12 UTC, david-allison requested changes
`onCollectionLoaded` is not guaranteed to be called.

The `lateinit` variables should be initialised in `onCreate` instead.

2023-02-18 09:12 UTC, zaidazaize commented
cardsListView is now  initialised in onCreate

2023-02-18 17:35 UTC, david-allison requested changes

2023-02-18 17:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    lateinit var cardsAdapter: MultiColumnListAdapter
Same issue with `cardsAdapter`. Confirm that each variable is in `onCreate`

2023-02-20 21:55 UTC, zaidazaize commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    lateinit var cardsAdapter: MultiColumnListAdapter
moved initialization of `cardsAdapter` and `mActionBarTitle` to `onCreate`. Also have moved adapter linking from `onCollectionLoaded` to `onCreate`.

2023-02-20 22:52 UTC, david-allison commented
Conflicts

2023-02-20 23:54 UTC, closed without merging