Alert dialog when reset is clicked in app bar buttons
ankidroid/Anki-Android pull request #13189
Opened 2023-02-04 08:00 UTC by LCB2021029-Badri

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-02-04 08:27 UTC, pratyaksh1610 commented
Tests are failing.

2023-02-04 08:28 UTC, pratyaksh1610 commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="alert_positive">Yes</string>
I think `Yes` and `No` strings are already there and need not be re-declared.

2023-02-04 17:24 UTC, LCB2021029-Badri commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="alert_positive">Yes</string>
ok, i will try using them

2023-02-04 23:00 UTC, LCB2021029-Badri commented
The code has passed all the checks. @pratyaksh1610

2023-02-06 09:33 UTC, LCB2021029-Badri commented
can anyone approve this, if there is no error :)

2023-02-06 12:07 UTC, BrayanDSO requested changes

2023-02-06 12:07 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomButtonsSettingsFragment.kt
> +
unnecessary blank line

2023-02-06 12:07 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomButtonsSettingsFragment.kt
> +                    }
nit: could you extract this into a method to improve the readability?

2023-02-06 12:07 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="alert_title">Confirm Reset</string>
unnecessary

2023-02-06 12:07 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomButtonsSettingsFragment.kt
> +                .setPositiveButton(R.string.dialog_yes) { _, _ ->
Yes or No dialogs usually aren't good. I suggest something like `Reset custom buttons` → `OK` / `Cancel`

2023-02-06 12:07 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="alert_message">Are you sure you want to reset all custom toolbar buttons?</string>
`alert_title` and `alert_message` are generic keys. As those strings are actually specific to custom buttons, the keys should be more specific as well

2023-03-07 13:38 UTC, closed without merging