Allow to restore default value in AnkiDroid directory settings
ankidroid/Anki-Android pull request #13193
Opened 2023-02-05 07:15 UTC by Arthur-Milchior

As suggested by @BrayanDSO in #13153, it's better to have the button in the dialog than to have an extra one.

Manually tested, it indeed put back the folder to its default value.

Fix: #13150
![2023-02-05-081512_425x767_scrot](https://user-images.githubusercontent.com/357361/216806652-a77f1e62-b278-4157-b34d-152e45a20d6d.png)

2023-02-05 09:14 UTC, lukstbit approved these changes
Look ok, with the small issue below to fix..

2023-02-05 09:14 UTC, lukstbit commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="reset_default">Reset to default</string>
Lint complains about duplication for this string's value and ask for a comment to be set on both strings.

2023-02-05 13:59 UTC, Arthur-Milchior commented
Corrected by reusing the string. Thanks

2023-02-06 11:45 UTC, BrayanDSO requested changes

2023-02-06 11:45 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/preferences/EditTextPreferenceWithDefault.kt
> +    class EditTextPreferenceWithDefaultCompat(val preference: EditTextPreferenceWithDefault) : EditTextPreferenceDialogFragmentCompat() {
Don't forget the `DialogFragment` before `Compat`
```suggestion
    class EditTextPreferenceWithResetButtonDialogFragmentCompat(val preference: EditTextPreferenceWithDefault) : EditTextPreferenceDialogFragmentCompat() {
```

2023-02-06 11:45 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/preferences/EditTextPreferenceWithDefault.kt
> +            dialog.setButton(DialogInterface.BUTTON_NEUTRAL, getString(R.string.reset_custom_buttons)) {
I find `Reset to default` redundant and long for a button. `Reset` would be better IMO.

2023-02-06 11:45 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/preferences/EditTextPreferenceWithDefault.kt
> +                preference.callChangeListener(preference.defaultValue)
As wrote in `callChangeListener` javadoc

> Call this method after the user changes the preference, but before the internal state is
     set. This allows the client to ignore the user value.

So, the preference `.text` should only be changed AFTER `callChangeListener` and only if it returns true. Another problem here is that it runs `callChangeListener` even if the value hasn't changed

```suggestion
                if (preference.text != preference.defaultValue && preference.callChangeListener(preference.defaultValue)) {
                    preference.text = preference.defaultValue
                }
```

2023-02-06 11:45 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
> +            defaultValue = CollectionHelper.getDefaultAnkiDroidDirectory(requireContext())
Someone may get confused by the difference of the new `defaultValue` and the platform `defaultValue` (e.g. by using `setDefaultValue` instead).

I particularly don't like telling people to "do it this way" on reviews, but I believe that the last commits on https://github.com/BrayanDSO/Anki-Android/commits/default would be less confusing

2023-02-06 12:39 UTC, BrayanDSO commented
Sorry for the force-push. Did it by mistake. I've already reverted any changes I'd done

2023-03-04 01:11 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
> +            defaultValue = CollectionHelper.getDefaultAnkiDroidDirectory(requireContext())
* A user is preserving legacy storage. DeckPath is `/storage/emulated/0/AnkiDroid`
* `getDefaultAnkiDroidDirectory` returns `/storage/emulated/0/Android/data/com.ichi2.anki.debug/files/AnkiDroid`
* A user presses 'reset to default'
* The directory is now `/storage/emulated/0/Android/data/com.ichi2.anki.debug/files/AnkiDroid`

2023-03-04 01:12 UTC, david-allison requested changes
Resets to a new default if [preserveLegacyExternalStorage](https://developer.android.com/training/data-storage/use-cases) is active

2023-03-26 19:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
> +            defaultValue = CollectionHelper.getDefaultAnkiDroidDirectory(requireContext())
Force pushed with this version

2023-03-26 20:01 UTC, Arthur-Milchior commented
> Resets to a new default if `preserveLegacyStorage` is active

Why a "new default"? If we preserve legacy storage, then I guess we just want to reset to the legacy storage.

Also, I don't know which function exactly you refer to. The closer name I find is `userIsPreservingLegacyStorage` but it seems to be just for backup. And all other methods with legacyStorage does not consider whether the user want to preserve it, only whether it is currently the legacy one

2023-03-26 20:31 UTC, david-allison commented
> > Resets to a new default if `preserveLegacyStorage` is active
> 
> Why a "new default"? If we preserve legacy storage, then I guess we just want to reset to the legacy storage.
> 
> Also, I don't know which function exactly you refer to. The closer name I find is `userIsPreservingLegacyStorage` but it seems to be just for backup. And all other methods with legacyStorage does not consider whether the user want to preserve it, only whether it is currently the legacy one

If a user has a folder as `~/AnkiDroid` and updates to 2.16.X, 'reset', resets their folder to `~/Android/....

Apologies about the typo. [preserveLegacyExternalStorage](https://developer.android.com/training/data-storage/use-cases)

2023-03-26 21:29 UTC, Arthur-Milchior commented
I'm sorry, but I still don't get it.
`preserveLegacyExternalStorage` only indicates whether, in case of upgrade, the legacy storage is preserved.
Even if I can access it (and `R.attr.preserveLegacyExternalStorage` is not even defined), that does not allow us to know whether it is an upgrade or not.

The only thing that seems to matter is whether we have access to legacy storage. And as far as I can tell, `selectAnkiDroidFolder` already deals with it properly.

2023-03-27 19:34 UTC, BrayanDSO commented
lint is failing

2023-03-27 21:11 UTC, david-allison commented
> I'm sorry, but I still don't get it. 

* A user is on the Play Store. Their directory is `~/AnkiDroid`
* A user upgrades to 2.16
* A user presses 'restore default'
* The directory is changed to `~/Android/data/com.ichi2.anki/...` and the user no longer has a means to access their (valid) collection at the old location.

2023-04-15 15:10 UTC, Arthur-Milchior commented
Thanks. Now I get it.
I admit I don't see exactly how to solve it. 
At least, it's not urgent.

Because usually, we use the current path to decide whether it's scoped or not. But in this case, since this button is useful only if the path changed, it seems we have no easy way to know which directory should be used.

Main trouble is that, if the user updated on play store to 2.16, we currently have no way to know if we are before or after a migration once the directory is changed.
I could check which of the two potential directory is accessible and has a AnkiDroid folder; but that does not state what to do if there are folders at the two places. E.g. during  a migration.

The only solution i see would be to add an extra preference to track that a migration ended.

2023-05-06 15:36 UTC, closed without merging