changed some String.format into String template
ankidroid/Anki-Android pull request #13191
Opened 2023-02-04 10:50 UTC by abhi835

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-02-05 07:46 UTC, criticalAY commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:7.4.0'
This gradle update isn't required in PR

2023-02-05 07:47 UTC, criticalAY requested changes

2023-02-05 07:47 UTC, criticalAY commented on README.md
> +
Unnecessary blank lines. Please revert the changes

2023-02-05 22:45 UTC, mikehardy commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:7.4.0'
Stated more strongly: never include unrelated items in a PR, *especially* changes to build files, those changes are always unwanted. Have a focused goal for the PR, then with the changes include only the minimal things required to implement the goal of the PR

2023-02-06 12:11 UTC, abhi835 reviewed
Changed to previous version

2023-02-06 12:27 UTC, criticalAY requested changes
Looks good just need to revert one last change and we are good to go.

2023-02-06 12:27 UTC, criticalAY commented on README.md
> +-
Revert this one too

2023-02-07 06:05 UTC, n1snt commented on api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
> +
This line also needs to be removed.

2023-02-07 06:06 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
> +
This too

2023-02-07 06:07 UTC, n1snt commented
There are some merge conflicts too that need to be resolved.

2023-02-12 11:05 UTC, closed without merging