added migration progess bar
ankidroid/Anki-Android pull request #13219
Opened 2023-02-07 19:06 UTC by criticalAY

## Pull Request template
Added migration progress bar that is to be shown during migration process 
The progress bar is updated using CoroutineScope.

## Purpose / Description
Updated static percentage with dynamic UI

## Fixes
Fixes #13080

## Approach
_How does this change address the problem?_

## How Has This Been Tested?
Tested on OnePlus Nord CE 
https://user-images.githubusercontent.com/48384865/217341347-de6091fc-2d1b-47d4-bbcb-5c14b7b92cdf.mp4

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, 

go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-02-07 19:09 UTC, criticalAY commented
things that need to be taken care of or need suggestion
1. UI of the material box. i.e the widht of progress bar, size padding of mbox
2. Percentage number in the dialog box, like we need it or not.

2023-02-07 19:33 UTC, criticalAY commented
Closes  #13212

2023-02-11 06:30 UTC, criticalAY commented
![Screenshot_38](https://user-images.githubusercontent.com/48384865/218244252-ad480478-5f0d-44d4-bf32-8c7cb87a47db.png)
I have updated the string and here is the latest test

2023-02-11 06:46 UTC, criticalAY commented
The code quality is failing due to the string values in resource directory.

2023-02-12 00:59 UTC, oakkitten requested changes
A very solid PR with a few issues!

I have to admit I did not run the code for reaons. Also, I'm skipping the XML files with the idea that these will get changed when moving to `AlertDialog`. I see some hardcoded colors but I trust that this dialog looks consistent with the usual AD progress dialog that we've got—in all themes.

Anyway, two things:
* I'd like to have a dialog fragment here. Dialog fragments do require a little more boilerplate, but they are more mainstream and they survive device rotation, which is cool.
* I would still love to have UI updates to go via more modern approaches such as `StateFlow`. You would do something like:
   ```kt
    dialogFragment.lifecycleScope.launch {
        flowOfMigrationProgress.collect { migrationProgress ->
            progressBarView.progress = migrationProgress.ratio
            progressTextView.text = getString(..., migrationProgress.transferredMb, migrationProgress.totalMb)
        }
    }
    ```

2023-02-12 00:59 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
>          MaterialDialog(this).show {
I suggest not using `MaterialDialog` as we are trying to move back to `AlertDialog`

2023-02-12 00:59 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            cornerRadius(14f)
Regardless of which dialog implementation we use, it's best to set stuff like that via theming. If this is not viable for some reason, add a comment explaining the reasoning

2023-02-12 00:59 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            cornerRadius(14f)
We are currently using `8dp` for all popups, see `dialog_corner_radius`. This is a rather conservative value, but if increasing it, I'd suggest increasing it for *all* dialogs and popups, and perhaps doing so as a part of a more comprehensive UI overhaul.

2023-02-12 00:59 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            onDismiss { progressScope.cancel() }
While this is a fine approach, I suggest using a dialog fragment. Dialog fragments are, well, fragments, which provide their own scope, which removes the necessity of canceling scopes explicitly.

2023-02-12 00:59 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                val percentProgress = migrationService.instance?.let { service ->
You have `migrationService.instance?` two times in a row. It would be easier to read if it is extracted into a variable, or perhaps it might be suitable to use a guard clause here.

2023-02-12 00:59 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                        Pair(service.currentProgress.toMB(), totalToTransfer.toMB())
Nit: consider using `to` here. (Or perhaps try refactoring this method more vigorously.)

2023-02-12 00:59 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                val progressedMB = percentProgress!!.first
`!!` is a big red flag here! 🚩 It should either be present earlier, or better yet, not present at all.

2023-02-12 00:59 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                val progressedMB = percentProgress!!.first
Also, instead of doing `val a = foo.first; val b = foo.second` consider doing `val (a, b) = foo`.

2023-02-12 00:59 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    String.format("%.2f", (progressedMB.toFloat() / totalMB.toFloat()) * 100)
I think division by zero can happen here.

2023-02-12 00:59 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    String.format("%.2f", (progressedMB.toFloat() / totalMB.toFloat()) * 100)
As a user, I would prefer something like “2 MB of 10 MB” instead of “20%”.

2023-02-14 11:37 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            cornerRadius(14f)
removed the radius itself

2023-02-14 11:40 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    String.format("%.2f", (progressedMB.toFloat() / totalMB.toFloat()) * 100)
The user won't be opening and won't be able to open this dialog in case it's zero as the success is already shown in that case

2023-02-14 11:41 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    String.format("%.2f", (progressedMB.toFloat() / totalMB.toFloat()) * 100)
we had a discuss for % and MB but we preferred % than MB

2023-02-14 11:42 UTC, criticalAY commented
I have made the changes and tested it on my end though there might be some nits or changes so I am open to them

2023-02-14 15:40 UTC, oakkitten commented
Before reviewing, I tried tried running [9709917](https://github.com/ankidroid/Anki-Android/pull/13219/commits/9709917b2591bb7c37357c8548de5f7396a32b7a) and this is what I see. Tagging also @david-allison 

While  minimizing app while syncing media I see this crash:

```
D  onPause()
I  AnkiActivity::onPause - DeckPicker
D  onStop()
I  AnkiActivity::onStop - DeckPicker
D  WidgetStatus.update(): already running or not enabled
D  saveCollectionInBackground: start
D  doInBackgroundSaveCollection
I  flush - Saving information to DB...
W  Accessing hidden field Landroid/app/ActivityThread;->mServices:Landroid/util/ArrayMap; (greylist, reflection, allowed)
D  onDestroy
V  Terminated Repeater com.ichi2.utils.Repeater@38c9dbd
D  Watching instance of com.ichi2.anki.services.MigrationService (com.ichi2.anki.services.MigrationService received Service#onDestroy() callback) with key d9c57c64-ab9c-4046-8267-227a3632c453
D  fast move successful from '/storage/emulated/0/AnkiDroid/collection.media/AUDIO-Priory.mp3' to '/storage/emulated/0/Android/data/com.ichi2.anki.debug/files/AnkiDroid1/collection.media/AUDIO-Priory.mp3'
E  FATAL EXCEPTION: Storage Migration
  Process: com.ichi2.anki.debug, PID: 26549
  java.lang.IllegalStateException: no exceptions provided 
    at com.ichi2.exceptions.AggregateException$Companion.raise(AggregateException.kt:40)
    at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData.migrateFiles(MigrateUserData.kt:514)
    at com.ichi2.anki.services.MigrationService$onStartCommand$1.invoke(MigrationService.kt:204)
    at com.ichi2.anki.services.MigrationService$onStartCommand$1.invoke(MigrationService.kt:199)
    at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

Also this:

```
E  ANR in com.ichi2.anki.debug
   PID: 27982
   Reason: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{fb78010 u0 com.ichi2.anki.debug/com.ichi2.anki.services.MigrationService}
   Load: 0.0 / 0.11 / 0.1
   CPU usage from 0ms to 8911ms later (2023-02-14 15:06:53.881 to 2023-02-14 15:07:02.793):
     55% 3339/com.android.providers.media.module: 29% user + 25% kernel / faults: 5440 minor 66 major
     32% 27982/com.ichi2.anki.debug: 18% user + 14% kernel / faults: 17257 minor 84 major
     25% 152/kswapd0: 0% user + 25% kernel
     20% 1440/system_server: 10% user + 9.5% kernel / faults: 16411 minor 340 major
     15% 10379/com.google.android.gms.persistent: 11% user + 3.7% kernel / faults: 10950 minor 412 major
     11% 453/mmc-cmdqd/0: 0% user + 11% kernel
     6.9% 2081/com.android.systemui: 4.3% user + 2.5% kernel / faults: 16381 minor 131 major
     4.7% 27955/com.google.android.gms: 3.1% user + 1.5% kernel / faults: 12594 minor 259 major
     3.9% 9229/com.google.android.googlequicksearchbox:search: 2.1% user + 1.7% kernel / faults: 9218 minor 624 major
     3.9% 27013/com.google.android.inputmethod.latin: 2% user + 1.9% kernel / faults: 9756 minor 964 major
     3.4% 824/surfaceflinger: 1.5% user + 1.9% kernel / faults: 2744 minor 24 major
     0.1% 1108/media.codec: 0% user + 0% kernel / faults: 10162 minor 12 major
     2.5% 5853/com.laurencedawson.reddit_sync: 2.4% user + 0.1% kernel / faults: 245 minor
     2.3% 944/adbd: 0.7% user + 1.5% kernel / faults: 797 minor 6 major
     1.7% 2568/com.android.phone: 1.1% user + 0.6% kernel / faults: 4769 minor 105 major
     0% 1133/media.swcodec: 0% user + 0% kernel / faults: 6833 minor 15 major
     1.4% 2431/com.android.networkstack.process: 1% user + 0.4% kernel / faults: 4892 minor 114 major
     0% 2467/.dataservices: 0% user + 0% kernel / faults: 4251 minor 194 major
     0% 1076/media.extractor: 0% user + 0% kernel / faults: 4815 minor 11 major
     1.3% 2550/.qtidataservices: 1.2% user + 0.1% kernel / faults: 3682 minor 23 major
     1.2% 598/logd: 0.6% user + 0.5% kernel / faults: 762 minor 4 major
     1.2% 21901/kworker/u16:7: 0% user + 1.2% kernel
     1% 89/kcompactd0: 0% user + 1% kernel
     0% 2497/com.qualcomm.qti.telephonyservice: 0% user + 0% kernel / faults: 5386 minor 65 major
     1% 6711/com.microsoft.emmx: 0.4% user + 0.5% kernel / faults: 4001 minor 370 major
     1% 26806/kworker/u16:15: 0% user + 1% kernel
     0% 2508/com.android.se: 0% user + 0% kernel / faults: 3640 minor 104 major
     0.7% 3389/org.lineageos.settings.doze: 0.5% user + 0.2% kernel / faults: 3435 minor 35 major
     0.7% 27605/kworker/u17:2: 0% user + 0.7% kernel
     0.6% 563/kworker/0:1H: 0% user + 0.6% kernel
     0% 3424/com.tencent.soter.soterserver: 0% user + 0% kernel / faults: 5156 minor 84 major
     0% 3453/org.lineageos.audiofx: 0% user + 0% kernel / faults: 3634 minor 36 major
     0.6% 12830/kworker/u16:3: 0% user + 0.6% kernel
     0.6% 17441/kworker/u17:0: 0% user + 0.6% kernel
     0.5% 709/zygote64: 0.1% user + 0.4% kernel / faults: 1638 minor 2 major
     0.5% 2036/com.android.bluetooth: 0% user + 0.5% kernel / faults: 740 minor 28 major
     0.5% 28128/com.ichi2.anki.debug:acra: 0.3% user + 0.2% kernel / faults: 3170 minor 18 major
     0.4% 3/ksoftirqd/0: 0% user + 0.4% kernel
     0.4% 7/rcu_preempt: 0% user + 0.4% kernel
     0.4% 25/rcuop/2: 0% user + 0.4% kernel
     0.4% 620/jbd2/mmcblk0p69: 0% user + 0.4% kernel
     0.4% 707/statsd: 0.3% user + 0.1% kernel / faults: 1049 minor 18 major
     0.4% 1855/cds_mc_thread: 0% user + 0.4% kernel
     0.4% 3168/irq/61-1008000.: 0% user + 0.4% kernel
     0.4% 26737/kworker/0:0: 0% user + 0.4% kernel / faults: 7 minor
     0.3% 10/rcuop/0: 0% user + 0.3% kernel
     0.3% 18/rcuop/1: 0% user + 0.3% kernel
     0.3% 445/cfinteractive: 0% user + 0.3% kernel
     0% 689/tombstoned: 0% user + 0% kernel / faults: 228 minor 32 major
     0.3% 15943/kworker/u16:5: 0% user + 0.3% kernel
     0.3% 24577/kworker/u16:12: 0% user + 0.3% kernel
     0.3% 26265/logcat: 0.2% user + 0.1% kernel / faults: 64 minor
E    46% 1440/system_server: 16% user + 30% kernel / faults: 648 minor
       43% 28246/AnrConsumer: 16% user + 27% kernel
     31% 27982/com.ichi2.anki.debug: 7.7% user + 23% kernel / faults: 98 minor
       27% 28182/Storage Migrati: 7.7% user + 19% kernel
     14% 152/kswapd0: 0% user + 14% kernel
     5% 824/surfaceflinger: 2.5% user + 2.5% kernel / faults: 7 minor
       2.5% 1015/TimerDispatch: 2.5% user + 0% kernel
       2.5% 1017/app: 2.5% user + 0% kernel
     5.1% 944/adbd: 0% user + 5.1% kernel / faults: 8 minor
       2.5% 944/adbd: 0% user + 2.5% kernel
       2.5% 26250/UsbFfs-worker: 0% user + 2.5% kernel
     2% 7/rcu_preempt: 0% user + 2% kernel
     2% 39/rcuop/4: 0% user + 2% kernel
     2.4% 599/lmkd: 0% user + 2.4% kernel
     2.6% 1172/ipacm: 2.6% user + 0% kernel / faults: 7 minor 1 major
       2.6% 4950/ipacm: 2.6% user + 0% kernel
     3% 5853/com.laurencedawson.reddit_sync: 3% user + 0% kernel
       3% 5853/son.reddit_sync: 3% user + 0% kernel
   29% TOTAL: 12% user + 14% kernel + 0.2% iowait + 0.7% irq + 1% softirq
```

Also, the notification briefly shows nonsensical "Migrated 0 MB of 261140 MB" before showing the correct "of 255 MB"

Also, the migration is not resumed using the old numbers. That is, if it starts, if I re-start migration (by killing and reopening the app) with "Migrated 50 of 200 MB", I get a new notification with "Migrated 0 of 150 MB", which should be confusing to the user.

Also, when restarting the app that has migration in progress, there's no indication that migration is being resumed. I suppose we want to show a snackbar or something?

Also, I do suggest showing "20.2 MB" instead of "20 MB", copying 1 MB takes some 30+ seconds here.

2023-02-14 19:28 UTC, oakkitten requested changes
Now I am thinking whether my advice to go use dialog fragments was actually good. This *is* a proper way, but perhaps it would be currently best to forgo it for simplicity.

The big idea behind fragments is like this: a fragment is not tied to a specific activity. It should be easy to take a fragment and put it into another activity. Also, a fragment, like an activity, has its own view model. When you rotate a device, fragment's views are destroyed, but its `viewModel` remains. The `viewModel` is destroyed when the fragment is no longer needed, such as when you destroy the dialog. Here's an illustration:

![fragment](https://user-images.githubusercontent.com/1710718/218837418-b76ecba5-c27d-4764-b0ac-ad8f09c7a775.png)

To explain what's going on here:
* An activity shows a dialog fragment, and in our case it probably doesn't pass any arguments to it. Our dialog fragment knows exactly what to do.
* Fragment's `viewModel` will remain until dialog is dismissed. It connects to the service directly, not via the activity. It obtains a flow of migration progress updates from the service.†
* Fragment, when it is started, and until it's paused, collects from the flow and updates the views. This ensures that we don't waste CPU when the screen is off. The easiest way to do this is to use `fragmentLifecycle.repeatOnLifecycle(Lifecycle.State.STARTED) {}`.

You can ask, but if the fragment doesn't know about the activity, where does the flow come from? Well, I think it should come from the service itself. In fact, other parts of the app could be simplified if using flow there.

†One thing to note here, it might be possible to skip using `viewModel` here. A service is normally more long-lived than the dialog, and if it produces a flow that we can use directly, we don't exactly need the `viewModel`. But this means that we will have to bind to the service each time Fragment is created. By default this is an asynchronous operation, so it's possible that e.g. after device roatation very briefly we will have a wrong value to show.

†Another thing to note here, AnkiDroid activities are long-lived objects in an unrecommended way, handling configuration changes themselves. This may mask issues with fragments. Best to test with “Don't keep activities” for future proofing.

2023-02-15 09:42 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MigrationProgressDialogFragment.kt
> +        layout.addView(progressView)
I already tried that before but adding the custom layout the padding/margin get ignored so I am creating them in kotlin file

2023-02-15 15:56 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MigrationProgressDialogFragment.kt
> +        }
it is same as `launchWhenStarted` as it's also aware of the state so it good to go here

2023-02-15 17:45 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MigrationProgressDialogFragment.kt
> +        layout.addView(progressView)
This is weird, I suggest investigating, or at least adding a comment with some information about what you tried and a TODO

2023-02-15 17:46 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MigrationProgressDialogFragment.kt
> +        }
As I understand, `launchWhenStarted` will will launch a coroutine that will work till the end of the activity/fragment, and with `lifecycle.repeatOnLifecycle(Lifecycle.State.STARTED)` the block will be canceled on `onStop` and resumed on `onStart`, so these are different

2023-02-15 18:42 UTC, criticalAY commented
@oakkitten I have removed the parameter and created a viewmodel

2023-02-16 05:44 UTC, criticalAY commented
@oakkitten I have fixed the padding seems like was my mistake, Thanks!

2023-02-16 05:44 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MigrationProgressDialogFragment.kt
> +        layout.addView(progressView)
done!

2023-02-16 15:23 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MigrationProgressDialogFragment.kt
> +        return builder.create()
Builders in Kotlin/Java typically use method cascading (fluent interfaces):

```kotlin
    return AlertDialog.Builder(activity)
        .setView(progressView)
        .setPositiveButton(R.string.dialog_ok) { _, _ ->
            dismiss()
        }
        .setNegativeButton(R.string.scoped_storage_learn_more) { _, _ ->
            (requireActivity() as AnkiActivity).openUrl(R.string.link_scoped_storage_faq)
        }
        .create()
```

2023-02-16 18:28 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MigrationProgressDialogFragment.kt
> +        return builder.create()
yes can do this now as was using a custom layout earlier

2023-02-16 18:54 UTC, david-allison commented
lint failure

2023-02-16 18:57 UTC, david-allison commented
Looks good besides the lint check. Could you post a screenshot?

2023-02-16 18:58 UTC, criticalAY commented
> lint failure

It wont pass as the strings need to be updated as I have changed the argument and edited it but not all the strings

2023-02-16 18:59 UTC, criticalAY commented
> Looks good besides the lint check. Could you post a screenshot?

Sure!

2023-02-16 19:07 UTC, david-allison commented
Use a new key if you're changing a string

2023-02-16 19:38 UTC, criticalAY commented
@david-allison The lint-test still failed due to the unused string :)

2023-02-16 20:48 UTC, david-allison commented
Remove the old string in `values`

2023-02-16 20:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                        delay(500)
500 seems too long from the video. What about 100?

2023-02-16 21:26 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                        delay(500)
https://user-images.githubusercontent.com/48384865/219490448-bc80f7a8-a317-4c46-ba95-216de5062610.mp4

2023-02-16 21:30 UTC, criticalAY commented
> Remove the old string in `values`

All the strings or just one that's there?

2023-02-16 22:07 UTC, david-allison approved these changes

2023-02-17 13:59 UTC, mikehardy commented
I'd like to get this one in prior to the next alpha because I think we're getting a lot of issue traffic related to this one

I have a strong desire to get the next alpha out quickly, as we've got an AnkiDroid-Backend + Anki subsystem critical fix pending release (working through them now)

I've merged all the strings related stuff I could so the strings sync pathway is clear

So, yes, it's open source, but if there is any ability to complete review on this thing so it's merge-able in a short time frame, that would be 🔥 😄

2023-02-17 14:13 UTC, criticalAY commented
@mikehardy I agree as there have been manual reports too for the migration issue. There is also one more PR related to the sync lock so please don't push the alpha before these atleast and I'm working on both of these plus the notification that needs to be shown after the successful migration but this one is not a blocker. I will most probably get the sync lock PR updated  in a day or two

2023-02-18 20:36 UTC, oakkitten commented
Sorry, I promised to review but didn't realize this is high prio. Promise to review tomorrow, but from a tipsy, cursory glance, [this comment](https://github.com/ankidroid/Anki-Android/pull/13219#discussion_r1106241223) wasn't addressed, also subsequent comments; also `progressFlowJob` seems to be not doing anything

2023-02-18 22:34 UTC, mikehardy commented
No worries @oakkitten I'm admittedly putting pressure on in an open source context and it's bad form. I'll always accept "can't / don't have time" of course. But if you do have time 😄 - I *think* this is close to critical path, so yes, higher priority

2023-02-19 06:07 UTC, criticalAY commented
@oakkitten `progressFlowJob` was meant to cancel the jobs that were initiatied `onStart`.
I tried to put the method in `onCreateDialog` earlier but the UI doesn't update properly so that was the reason I created the method inside `onStart` and later cancel the job `onStop` and I certainly missed to place that variable.

2023-02-19 22:20 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MigrationProgressDialogFragment.kt
> +    private fun updateProgress(state: MigrationProgress) {
Nit: this could be a local method, and `messageTextView` and `progressBar` could be local fields. Better encapsulation doesn't _really_ matter for such a simple class, but I think it would simplify things a little bit

2023-02-19 22:20 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MigrationProgressDialogFragment.kt
> +                (state.transferredMb.toFloat() / state.totalMb.toFloat()) * 100
I won't be insisting on this further, but even if this doesn't crash, I would still explicitly handle division by zero. For the current `MigrationProgress` implementation it just makes sense to have a 0 `totalMb` while calculating `totalMb`. Better safe than sorry!

2023-02-20 17:28 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MigrationProgressDialogFragment.kt
> +                (state.transferredMb.toFloat() / state.totalMb.toFloat()) * 100
ok!

2023-02-20 18:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MigrationProgressDialogFragment.kt
> +                (state.transferredMb.toFloat() / state.totalMb.toFloat()) * 100
The divide by zero needs to be handled

2023-02-20 18:23 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    }
Loop: Tag this one for a follow-up. It's not worthwhile rewriting the PR over.

Test to see the rotation behaviour and fix if it's an issue.

2023-02-20 18:24 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    }
Already tested not causing any issue

2023-02-21 22:06 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    }
There's a high chance there will be no follow-up because no-one will bother. If so, we will be left with this loop that survives rotation in manual testing on one device. This seems good but I know I have to think hard about whether or not this will work in all cases. And I am not confident it will. I'd sure love to have code that I have no doubts about...

2023-02-23 14:09 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            service.totalToTransfer?.let { totalToTransfer ->
@criticalAY thoughts on this one?

2023-02-23 14:11 UTC, mikehardy commented
Took another conflict :weary: - and appears to have one unresolved comment needing author reply
Really need to get this done, it's blocking an alpha release.

2023-02-23 14:16 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            service.totalToTransfer?.let { totalToTransfer ->
@david-allison you may have thoughts here? and/or if there is some easy fix could just implement then we could be done with this one

2023-02-23 14:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            service.totalToTransfer?.let { totalToTransfer ->
Edge case: add a `Loading...` string here and let's get this out

2023-02-23 14:32 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            service.totalToTransfer?.let { totalToTransfer ->
I made a check for that in the code if totalMB is null then that means the progress would be rapid and I am certain that no user can reach the button in the short period of time but I have still placed a check

2023-02-23 14:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            service.totalToTransfer?.let { totalToTransfer ->
We have a number of users with 10+GB of data, calculating the total size is an expensive operation in this case, and I feel it's worthwhile (quickly) tackling.

2023-02-23 17:08 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            service.totalToTransfer?.let { totalToTransfer ->
So what is the ideal solution you suggest

2023-02-24 00:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            service.totalToTransfer?.let { totalToTransfer ->
> Add a `Loading...` string here and let's get this out

2023-02-24 07:39 UTC, criticalAY commented
updated the String values

2023-02-24 14:53 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            service.totalToTransfer?.let { totalToTransfer ->
Can we be more specific here? Something like “Calculating the size of files to migrate”

2023-02-24 18:26 UTC, oakkitten commented
Currently the dialog is just always stuck on “Loading...”. [This](https://github.com/ankidroid/Anki-Android/pull/13219#discussion_r1106251552) is still a problem. Can't say if there are further problems with this, as migration crashes when the app is minimized.

2023-02-24 18:34 UTC, criticalAY commented
It doesn't crash in my case when it is minimised

2023-02-24 18:45 UTC, oakkitten commented
https://user-images.githubusercontent.com/1710718/221264444-b3edad89-08c0-4ef1-8c7c-adbd80e86106.mp4

2023-02-24 19:36 UTC, oakkitten commented
Okay so the above issue is not exactly a crash but the service stopping. It stops due to the fact that a) the activity unbinds from the service on stop, and b) the service doesn't get properly set up as a foreground service in the first place, which makes it stop when the last client unbinds. This, in turns, seems to be happening because the first notification is not posted until the size of transfer is calculated, which can take more than 5 seconds:

https://github.com/ankidroid/Anki-Android/blob/092f4f9f473dbd98ec68996ba305815ba1f91f99/AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt#L222-L224

Now, after “fixing” this by removing the unbind call, I can also attest that [this](https://github.com/ankidroid/Anki-Android/pull/13219#discussion_r1111328111) is also still a problem, namely, this part:

> Also, doing `lifecycleScope.launch` here feels wrong-ish. IF doing this, the proper way would be to launch this on the view model's scope to survive rotation, etc

“Etc” is the key part here. The activity is not destroyed on rotation due to the old hacks, but it does get destroyed on theme change. This will also stop the dialog from updating.

2023-02-24 19:42 UTC, criticalAY commented
We should tag @david-allison  for this one then

2023-02-25 02:24 UTC, david-allison commented
If the problem isn't within this PR, extract the issue to a GitHub issue, stick it on the project board and get this PR in.

2023-02-25 06:55 UTC, criticalAY commented
#13348 here

2023-02-25 16:00 UTC, oakkitten commented
Here's some working [mockup code](https://github.com/oakkitten/Anki-Android/tree/progress_dialog) ([diff](https://github.com/oakkitten/Anki-Android/compare/e57be852a6db4cabcb4e6048a49508e4c88d542b..progress_dialog)) (with a few TODOs) on top of this PR that (hopefully) resolve the remaining issues in this PR and fixes #13348 to boot

https://user-images.githubusercontent.com/1710718/221366838-da80b137-c15c-4478-812a-9b8ac9b7f4f9.mp4

2023-02-25 21:41 UTC, mikehardy commented
Okay, back to @criticalAY then I s'pose

2023-02-25 21:51 UTC, criticalAY commented
> Okay, back to @criticalAY then I s'pose

@mikehardy oakkitten said he wanna make changes over this PR @oakkitten ?

2023-02-25 22:53 UTC, mikehardy commented
@criticalAY I think they did propose changes - you can see the link to their fork / branch in his comment, and check the diff, and pull it in to your branch by making a PR to your fork from their branch on their fork

2023-02-25 22:56 UTC, criticalAY commented
> @criticalAY I think they did propose changes - you can see the link to their fork / branch in his comment, and check the diff, and pull it in to your branch by making a PR to your fork from their branch on their fork

Ok will do when I wake up as I just turned of my laptop and going to sleep

2023-02-26 17:33 UTC, david-allison commented
They're on the project board: https://github.com/orgs/ankidroid/projects/1/views/1

I intend to come back to them before release (if you'd prefer to do them yourself, strongly supported). 

Reviews are where this project's getting blocked (this PR & next alpha have been waiting 3 weeks!). I suspect there's going to be a month after the final functional PRs are in place before they get merged, and it's better to tackle the follow-up tasks in this time.

2023-02-26 18:01 UTC, criticalAY commented
I agree with @david-allison we can get this one in and start working on the fixation part soon after it following the merge that way we won't block the alpha and will be able to provide a proper fix without rushing. He have made a whole communication channel on this PR though xD

2023-02-26 18:21 UTC, oakkitten commented
I can't disagree more. I mean, one of the reasons that this PR has been stuck for so long is because of the issues in the code it talks to. We should should try fixing the existing problems which create issues for other developers before going forward to create even more issues...

2023-02-26 21:44 UTC, BrayanDSO commented
Agreed with @oakkitten 

IMHO, getting the migration right takes way way way more priority over a progress bar or releasing a new alpha (which I still don’t see the blocker).

2023-02-26 23:21 UTC, doozan commented
> one of the reasons that this PR has been stuck for so long is because of the issues in the code it talks to. We should should try fixing the existing problems which create issues for other developers before going forward to create even more issues...

Just commenting here as an uninvolved observer (ie, feel free to ignore me or tell me to stfu): Would it be possible to peel these concerns into separate issues, flag them as blocking this PR, and just leave this as a simple GUI patch to expose the migration progress? That would let someone comfortable with the the backend/service concerns step up to resolve the service concerns and, when that's finished, everyone can circle back to this PR and make sure the progress bar still works.

2023-02-27 00:57 UTC, mikehardy commented
🤔  so as far as I understand

- these *are* serious issues that @oakkitten is poking at (thank you!) and
- the issues uncovered *are* tracked via peeling to the project board as separate issues (if not, please do so but I think they are)
- there is no progress bar currently and I was blocking alpha because I thought it would be fast but hey, it's definitely not. Stated differently, I was hoping for progression but if I release a new alpha it is not at least a *regression*

So I propose:

- @oakkitten do you have any bandwidth to propose the concrete changes required for the issues pointed out? Specifically, can you and @david-allison work on the comments here https://github.com/ankidroid/Anki-Android/pull/13152#pullrequestreview-1287957166 and stall this PR (apologies, @criticalAY) until that's settled?
- @david-allison I think is able to continue moving in parallel in general (this is huge + driving it to completion)
- I will release an alpha now regardless of state of this PR / basically removing the soft block I had placed on alpha release hoping to get this in


Thumbs up if you're good with that, otherwise please propose something concrete + actionable

2023-03-12 11:23 UTC, Arthur-Milchior reviewed
Those reviews are copy of the reviews from #13368, regarding the part that was still in @oakkitten 's commit

2023-04-02 12:42 UTC, closed without merging

2023-04-02 16:19 UTC, criticalAY commented
oakkitten is working on it so I think it doesn't matter thanks bot :)