Improve accessibility and styling of note editor toolbar
ankidroid/Anki-Android pull request #13249
Opened 2023-02-13 17:17 UTC by yamanq

## Purpose / Description
The toolbar buttons have some styling and accessibility inconsistencies:
- They have no tooltips for new users to understand their purpose
- Custom buttons added by insertItem have no click animation and have a smaller clickable area
- As briefly mentioned in #13244, the "Add toolbar item" button does not have a contentDescription set

## Fixes
I could not find any open issue for these problems.

## Approach
- Add tooltips to all buttons with the exception of custom toolbar buttons since they already have a long click action
- Add contentDescription to all buttons for accessibility. For custom toolbar buttons, the button text is used.
- Resize the layout of insertItem buttons to match the other buttons (see Before screenshot)
- Add background animation on insertItem buttons

## How Has This Been Tested?
Tested on physical Pixel 2 SDK 30 (Android 11).

- Long clicking buttons results in tooltip
- Adding multiple custom buttons does not break the style
- Accessibility text to speech reads button descriptions, including custom buttons
- Clicking buttons created by insertItem results in a background animation, just like the other buttons.

## Screenshots
### Before (Google Accessibility Scanner)
Note the size of the clickable area
![Screenshot_20230213-115840](https://user-images.githubusercontent.com/8166212/218522550-6fd0acbf-a392-4e5c-b187-8b01a34691b7.png)

### After (Showing click animation and tooltip)
![Screenshot_20230213-114707](https://user-images.githubusercontent.com/8166212/218522651-59b17146-e537-42a6-8285-28e4abce7a9d.png)

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [X] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-02-13 20:18 UTC, david-allison requested changes
Thank you!!

There's one issue on API 21.

Since this is a pure improvement over the original, I'll accept either:

* Adding a GitHub issue as a follow-up to investigate and fix this + adding a comment in the layout code referencing the issue.
* Fixing it

Thanks so much for this!!!

2023-02-13 20:18 UTC, david-allison commented on AnkiDroid/src/main/res/layout/note_editor_toolbar.xml
> +            android:tooltipText="@string/format_insert_bold"
These don't appear on API 21 (the ones added by `TooltipCompat.setTooltipText`) do.

2023-02-13 21:24 UTC, david-allison approved these changes

2023-02-13 21:24 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
> +    private fun addTooltipText() {
We typically handle compat + TODOs via `com.ichi2.compat.Compat`

The call would be: `CompatHelper.compat.addTooltipText(parentLayout.children)`

* In `CompatV21` we define the operation as below
* In `CompatV26` we define the operation as a no-op.

When we bump the minimum SDK, this shows a maintainer that any functions which are no longer necessary should be removed

2023-02-13 22:04 UTC, david-allison approved these changes

2023-02-13 23:59 UTC, david-allison commented
All good, thanks!

2023-02-14 00:58 UTC, oakkitten reviewed
This works very well and you even get the haptic feedback!

2023-02-14 00:58 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
> +        CompatHelper.compat.addTooltipText(parentLayout.children)
The name `addTooltipText` is confusing, it's not clear why it takes a list of views and where it gets tooltip text. Perhaps you could do:

```kt
parentLayout.children.forEach { child ->
    CompatHelper.compat.setTooltipTextByContentDescription(child)
}
```

But I would suggest simplifying it further:

```kt
// We set tooltips via `android:tooltipText`, but it is ignored on API < 26,
// so for those API set it via `android:contentDescription`.
if (Build.VERSION.SDK_INT < 26) {
    parentLayout.children.forEach { child ->
        TooltipCompat.setTooltipText(child, child.contentDescription)
    }
}
```

It's more code here, but this code can be read without looking up what the compat method does, and you add less code elsewhere.

2023-02-14 00:58 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
> +        val params = LinearLayout.LayoutParams(layoutSize, layoutSize)
Not that this have to be a part of this PR, but it would be nice to refactor this entire method to make it readable. It's such a wall of statements. Oh and I'd say `buttonWidth` instead of `layoutSize`, the latter term is a little confusing

2023-02-14 04:05 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
> +        CompatHelper.compat.addTooltipText(parentLayout.children)
That was a personal opinion. Ain't nothing wrong with the compat approach (although I'd do it without subclassing), but it creates a new API that must be learned by the reader. It's useful when it's used more than once, but in this case it's only used once, so _for now_ I'd go with the way that's easier to read. If need be, the logic can always be extracted into a compat method, but chances are [we aren't gonna need it](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it).

2023-02-18 01:19 UTC, oakkitten approved these changes
Well, I still wouldn't use `compat`, but it's a minor thing and this is good either way.

2023-02-18 01:19 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
> +    override fun addTooltipTextsFromContentDescription(views: Sequence<View>) {
I just want to explain my reasoning for suggesting what I did:
```kt
parentLayout.children.forEach { child ->
    CompatHelper.compat.setTooltipTextByContentDescription(child)
}
```
First, `set` vs `add`. “Set”, or “assign”, signifies the assignment `:=` operation, usually overwriting the previous value. `Add` usually signifies mutation of a collection. Executing addition twice, you get more than if you do it twice. Therefore I think `set by` is more readable here.

Second, I prefer methods that operate internally on single elements to not take collections, unless doing so is a significant optimization. It is unconventional, and the reader is going to ask, why does it take a collection? Having `forEach` outside is a little more code but is more like what you'd expect here. I think

2023-02-19 10:31 UTC, lukstbit approved these changes
LGTM, thanks for contributing this improvement!
I think all issues were addressed, I'm going to merge(or anyone else) a bit later if @oakkitten has anything else to add.

2023-02-19 13:08 UTC, mikehardy commented
maintainer note: the lint failure is known issue #13296 already with work around on main, not a merge blocker here.

2023-02-20 06:30 UTC, merged