Added function for database error
ankidroid/Anki-Android pull request #13248
Opened 2023-02-13 16:04 UTC by lonewolf2208

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixed #13168 
## Approach
There was already method for database error but was not implemented so added functionality for it .

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-02-13 16:20 UTC, mikehardy requested changes
testing failure

2023-02-13 20:18 UTC, lonewolf2208 commented
Good day @mikehardy , I think the problem is with the testcases as in line 453 it is requesting for DIALOG_TEST_FAILED but according to the changes it is DIALOG_DB_ERROR so should I move ahead and make the change in test case .Please correct me if I'm mistaken . 
![image](https://user-images.githubusercontent.com/72886809/218541241-44affb7e-48b4-408c-ad7e-b0895650f6c8.png)

2023-02-13 20:47 UTC, david-allison commented
The case when the database is corrupt is different from when the disk is full. 

One is a temporary issue, one is permanent.

I feel we should handle `DISK_FULL` as a separate case.

2023-02-13 20:54 UTC, lonewolf2208 commented
> The case when the database is corrupt is different from when the disk is full.
> 
> One is a temporary issue, one is permanent.
> 
> I feel we should handle `DISK_FULL` as a separate case.

Yes, I do agree with you, however because the text for the database error message handles both, I chose that  . Here is the content for dialog 
 <string name="answering_error_message">Writing to the collection failed. The database could be corrupt or there may not to be enough empty space on disk.\n\nIf this happens more often, try checking the database, repairing the collection or restoring it from a backup. Touch “options” for that.\n\Or it could be an AnkiDroid bug as well; please report the error so that we can check this.</string>

2023-02-13 21:29 UTC, david-allison commented
We can know that the database has no space in this circumstance (the failure occurs on startup, and we get an error specifying insufficient space when we open the collection).

In this case, we want to show a specific 'no space' dialog. As offering the user the option to repair/delete is not correct.

2023-02-14 17:43 UTC, lonewolf2208 commented
Good day @david-allison  Could you kindly evaluate the changes? I also need to add string translations for other languages, which I'll do when you do.

2023-02-14 17:49 UTC, david-allison requested changes
Much nicer! Could you add a screenshot of the dialog (after the string update is added) + buttons are changed

Few nitpicks + one request regarding the dialog functionality

2023-02-14 17:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +                    contentNullable(message)
What does this dialog do? Both the negative and positive button?

I think the ideal is 'retry/exit', but I'd support 'exit' as a single item initially to get this through

2023-02-14 17:49 UTC, david-allison commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +   <string name="storage_full_message">The disk/database is at full capacity and cannot store any more data. Please free up some space or remove unnecessary collection . </string>
```suggestion
   <string name="storage_full_message">There is not enough free storage space to open AnkiDroid. Free up some space to continue</string>
```

2023-02-14 18:02 UTC, lonewolf2208 commented on AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
> +        FILE_TOO_NEW, CORRUPT, LOCKED, NO_STORAGE
I selected this since I had used DISK FULL for StartupFailure and wanted to keep things distinct. Should i change this with different one ?

2023-02-14 18:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
> +        FILE_TOO_NEW, CORRUPT, LOCKED, NO_STORAGE
I feel there's benefits from consistency here

2023-02-14 19:42 UTC, david-allison commented on AnkiDroid/src/main/res/values-af/strings.xml
> +    <string name="storage_full_message">Daar is nie genoeg gratis stoorplek om AnkiDroid oop te maak nie. Maak spasie vry om voort te gaan.</string>
Revert the strings (except the one in `/values/`

2023-02-14 20:00 UTC, david-allison approved these changes

2023-02-14 20:02 UTC, lonewolf2208 commented
Thanks great learning

2023-02-15 17:58 UTC, mikehardy approved these changes
LGTM now thank you!

2023-02-15 18:09 UTC, mikehardy commented
Merge after merging #13262 so strings are clear. Then redo strings sync to get this in there clean.

2023-02-15 20:34 UTC, merged