Bump `targetSdkVersion` to 30, enable `MANAGE_EXERNAL_STORAGE` for Non-Play Store builds
ankidroid/Anki-Android pull request #13261
Opened 2023-02-15 05:27 UTC by david-allison

## Purpose / Description
Next stage of a storage migration: giving users an 'out'.

If they uninstall on Google Play, they can re-obtain access to their data via either F-Droid or downloading an APK.

We can guide users to this method on the app intro screen, and 'restore from backups' screen

## PR Draft

A small number of items are not completed. Initial thoughts & feedback would be appreciated before the design is ossified.

I would happily split out the early commits if requested so we can reduce the weight of this beastie

* For discussion: do we provide parallel alphas with `MANAGE_EXERNAL_STORAGE` disabled in the manifest (different startup flow)

## Fixes
Related: #5304

## Approach
This one is complex and if it can be made simpler/easier to understand, it should:

* An initial refactoring step to move permission management outside `DeckPicker`: the class is already too big, and this would complicate things further.
   * `PermissionManager`
   *  `StartupStoragePermissionManager`
     * APIs to simplify the calling code for permissions from the `DeckPicker` 
* Fix tests & update to API 30
* Add `MANAGE_EXERNAL_STORAGE` and add a workflow around this
   * Sets `deckPath` based on whether this permission is available in the Manifest and `TARGET_SDK`
   * See the commit message on this commit for our strategy of whether to force a user to accept storage before using the app
   * Optional request for an F-Droid or APK user to use `MANAGE_EXERNAL_STORAGE`

⛔️ This is the point of no return. Once this is merged, we're on API 30 and uninstalling will delete data.
   * Unless alpha users request `MANAGE_EXERNAL_STORAGE`. This will not be possible on the Play Store
⚠️ Still pending: handling a collection which was uninstalled, but with data intact

## How Has This Been Tested?

⚠️ Insufficient: manual testing - test cases requested

<img width="403" alt="Screenshot 2023-02-15 at 05 15 52" src="https://user-images.githubusercontent.com/62114487/218938782-b8cfc54d-e7f4-4a0f-aed9-eeaac7817afc.png">
<img width="423" alt="Screenshot 2023-02-15 at 05 16 04" src="https://user-images.githubusercontent.com/62114487/218938817-40f1347a-eeff-4c1b-a8ec-c5545ab257f4.png">

## Learning 
* `MANAGE_EXTERNAL_STORAGE` is denied permanently by default
* https://stackoverflow.com/questions/30719047/android-m-check-runtime-permission-how-to-determine-if-the-user-checked-nev
   * How to detect 'DENIED_PERMANENTLY' 

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [⚠️] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [⚠️] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-02-15 05:32 UTC, david-allison commented on AnkiDroid/build.gradle
> -                    buildConfigField "Boolean", "LEGACY_STORAGE", localProperties["legacy_storage"]
consider replacement

2023-02-15 05:32 UTC, david-allison commented on AnkiDroid/src/main/AndroidManifest.xml
> +        android:maxSdkVersion="29" />
verify

2023-02-15 05:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                        Timber.i("postponing startup code - dialog shown")
duplicated logic - extract

2023-02-15 05:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +    fun hasAllFilesAccess(context: Context): Boolean {
naming is inconsistent

2023-02-15 05:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +    fun canManageExternalStorage(context: Context): Boolean =
maybe `may`

2023-02-15 05:32 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityTest.kt
> +        assertThat(
inconsistent test style compared to below

2023-02-15 05:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +                title(text = "")
hardcoded strings

2023-02-15 05:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
> +            UIUtils.showThemedToast(mActivity, mActivity.resources.getString(R.string.multimedia_editor_something_wrong), false)
wants a root cause analysis - started failing on a specific test on API 30

2023-02-15 05:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +                    else -> throw IllegalStateException("not reachable")
This isn't the case. `ERROR` is a possibility

2023-02-15 10:47 UTC, david-allison commented
> A suggestion is to have analytics to know how much people wanted to use this new approach so we know if the effort to maintain this is worth it or not.

I 100% want to maintain this and will handle the maintenance burden. 

Analytics: They're opt-in and users won't have opted in before they see this dialog. I don't think our analytics handles 'user properties' yet, and I'm not sure it can do this well if users are anonymous - it's 1 but of deanonymizing information.

> What do you mean by "ensures compatibility with other apps" in the screenshot of a dialog on the PR description? Which apps are these? Why do they need that AnkiDroid to have this permission? ...

The copy in the screenshot was the first thing that came to mind. I'll update and give it some proper thought. We only added the Add `media` API recently, and older third party apps will integrate directly with the `collection.media` folder

> Actually, do we need to prompt this dialog? I think it's safer to always use the not in-app folder for alpha users, as we've done until now. If they want to migrate to the play store version, they can migrate their data before replacing their installation (but has the problem of having to keep the scoped storage code forever or restricting them to GitHub versions)

Do you mean we should force the user to provide us with 'all files' access before continuing? This doesn't feel like good UX

2023-02-15 10:58 UTC, BrayanDSO commented
> Do you mean we should force the user to provide us with 'all files' access before continuing? This doesn't feel like good UX

Isn't it just tapping a checkbox then tapping to go back to the app? I find it an almost equivalent process to the old way of giving the storage permission.

Not doing this is fine as well, although I find it simpler for the user

2023-02-15 11:15 UTC, david-allison commented
> > Do you mean we should force the user to provide us with 'all files' access before continuing? This doesn't feel like good UX
> 
> Isn't it just tapping a checkbox then tapping to go back to the app? I find it an almost equivalent process to the old way of giving the storage permission.
> 
> Not doing this is fine as well, although I find it simpler for the user

Done

2023-02-15 11:41 UTC, david-allison commented
Tests are failing due to bug in Robolectric: https://github.com/robolectric/robolectric/issues/7300

2023-02-15 17:34 UTC, oakkitten requested changes
This is not a full review, I just poked around. Some parts are quite hard to grasp, I hope parts of the code can be simplified. I think there's a possibility of a crash around `callback`, fixing which might require a considerable rewrite. I hope to review again at some time.

2023-02-15 17:34 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +    }
Maybe change `DIALOG_WITH_CALLBACK_SHOWN` when the potential callback crash is fixed?

2023-02-15 17:34 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +    this.finishWithoutAnimation()
I suggest adding a comment why we finish the activity here. Also maybe `finishActivityAndShowAppPermissionManagementScreen`?

2023-02-15 17:34 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +    ).also(this::startActivityWithoutAnimation)
I think simply `startActivityWithoutAnimation(Intent(...))` reads better

2023-02-15 17:34 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
> +    }
I don't understand the meaning and purpose of `setCollectionPath`

2023-02-15 17:34 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +    fun Context.permissionDefinedInManifest(packageName: String, vararg permissions: String): Boolean {
What's the purpose of `packageName`? Can we still request package info for other packages? https://stackoverflow.com/questions/62345805/namenotfoundexception-when-calling-getpackageinfo-on-android-11

2023-02-15 17:34 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +    fun Context.permissionDefinedInManifest(packageName: String, vararg permissions: String): Boolean {
I suggest refactoring so you could say instead:
```kt
if (permission in getPermissionsDefinedInManifest()) {
    ...
}
```

2023-02-15 17:34 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +    fun canManageExternalStorage(context: Context): Boolean =
Nit: I would refactor this and similar methods to be top-level functions like this:
```kt
fun Context.appCanManageExternalStorage(): Boolean = ...
```
This way, instead of
```kt
canManageExternalStorage = Permissions.canManageExternalStorage(context)
```
you could say
```kt
canManageExternalStorage = appCanManageExternalStorage()
```
I think this phrasing is better than “permissions can manage external storage”, and `Context` is probably like the most acceptable receiver ever

2023-02-15 17:34 UTC, oakkitten commented on AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityTest.kt
> +        const val AFTER_Q = Build.VERSION_CODES.Q + 1
Nit: this uses `AFTER_Q` but most of the checks in the code say `Build.VERSION.SDK_INT >= Build.VERSION_CODES.R`, I suggest using the same idea throughout

2023-02-15 20:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +}
What wording would you use for:

* The decision to request a a 'safe' (`/AnkiDroid`) or a 'non-safe' (`/Android/data`) folder for the AnkiDroid collection
* Requesting a permission from Android (formerly: `onRequestPermissionsResult`)
* The decision to enforce that a user has a given storage permission on startup (as opposed to it being optional)

2023-02-15 20:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +    // If we don't have a collection directory - assume it's non-legacy
`deckPath` is null

2023-02-15 20:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +    if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.Q) {
Compiler's not smart enough to realise that `Build.VERSION.SDK_INT < Build.VERSION_CODES.Q` and `Build.VERSION.SDK_INT == Build.VERSION_CODES.Q` are a valid condition to allow R-based APIs

2023-02-15 20:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        UIUtils.showThemedToast(deckPicker, R.string.startup_no_storage_permission, false)
This flow is already used in 2.15

2023-02-15 20:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +            }
Any decent way of making the compiler see this as exhaustive?

2023-02-15 20:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +        callback.invoke(PermissionResult.fromResults(activityRef, results))
Learning experience here: I'm new to this API. What's the best pattern to handle this?

If I'm understanding your comment correctly: a new instance of `PermissionManager` is registered to the activity, but without `callback`, as the previous instance was killed by the system?

In this case, I presume `callback` needs to be required at construction time?

2023-02-15 20:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +    }
Any suggestions?

2023-02-15 21:11 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +        val activity = activityRef.get() ?: throw Exception("activity disposed")
I don't think it can occur at this point: the activity executes the method on the class

2023-02-15 21:15 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +    fun Context.permissionDefinedInManifest(packageName: String, vararg permissions: String): Boolean {
Used in:

https://github.com/ankidroid/Anki-Android/blob/105134d957f5016a0a8e6a636050edfd241de31d/AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt#L1269-L1283

2023-02-15 21:18 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +    fun Context.permissionDefinedInManifest(packageName: String, vararg permissions: String): Boolean {
> I suggest refactoring so you could say instead:

Comparing two lists, I don't see how this would be more readable

2023-02-15 21:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +    fun canManageExternalStorage(context: Context): Boolean =
appropriate for a follow-on, not worthwhile to refactor the class in this PR

2023-02-16 18:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +                    PermissionResult.DENIED_TEMPORARILY -> requestPermissionViaDialog(permissionRequest)
Wasn't done with previous code - probably more appropriate for a follow-on

2023-02-16 18:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +            UIUtils.showThemedToast(activity, R.string.startup_no_storage_permission, false)
For another issue

2023-02-16 23:21 UTC, mikehardy commented
conflicts fyi :-)

2023-02-17 19:42 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +}
The word "safe" here is really a synonym for Scoped Storage or not isn't it?
I can understand the idea of mixing what most people think of data retention (like, our auto-backups have a retention policy that is tunable even...) vs total deletion or not on uninstall.
Could maybe be either CollectionDeletionOnUninstallPolicy to capture the efffect or CollectionScopedStorageStatus to capture the proximate cause or something

If naming is a blocker

2023-02-17 19:46 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +                    else -> throw IllegalStateException("not reachable")
just want to drop a recommendation to maybe check out react-native-permissions in case you want another look at flowchart of android request/interaction flow and related code. It's a pretty battle-tested implementation. You may feel comfortable with your mental model / this code already though, which is fine, but it's a nice implementation in case you are still in compare-and-contrast mode

2023-02-17 19:51 UTC, mikehardy commented on AnkiDroid/build.gradle
> +        targetSdkVersion 30 // change .travis.yml platform download at same time
I suppose the comment is pretty vestigial at this point. Travis! Those were the days.

Robolectric may need a switch though? Do you remember where the default API used by robolectric is or is it just off targetSdkVersion here? May need a download uncomment to pre-cache it and maintain de-flaking on CI:
https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/robolectricDownloader.gradle#L16

May need to change test matrix here? https://github.com/ankidroid/Anki-Android/blob/main/.github/workflows/tests_emulator.yml#L50

2023-02-17 19:53 UTC, mikehardy commented on AnkiDroid/src/main/AndroidManifest.xml
> +        android:maxSdkVersion="29" />
I believe I have done something like this before with bluetooth perms and others and it appeared to work fine, but surely we'll notice quickly when attempt to publish first beta to play store, they'll reject otherwise I think?

2023-02-17 19:55 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
> +    }
I'm making comments per-comment so perhaps this is out of turn, but @david-allison this appears to be an unanswered question? I'd like to avoid having more David/Oakkitten/David/Oakkitten cycles then necessary so answering this before the next Oakkitten scan seems like it would have value...

2023-02-17 19:57 UTC, mikehardy commented on AnkiDroid/build.gradle
> -                    buildConfigField "Boolean", "LEGACY_STORAGE", localProperties["legacy_storage"]
YAGNI? I get that scoped storage is (as you name it) "unsafe") but the path of least resistance is a powerful temptation. I think most people are going to be on phones with non-serviceable storage hardware and running scoped storage because that's 99.9999% of the user base. The rest will work out a procedure and document it and it'll work for them

2023-02-17 20:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
> +    }
This is fair - still on me to improve this area.

There was an issue with a circular dependency which could be fixed in a better manner now we've Brayan suggested we removed the concept of 'a user may deny permissions and access the app' from F-Droid/GitHub builds:

* We want to get the initial collection path:
* To do this, we want to know whether we should try `/AnkiDroid` (wait for permissions), or `/Android` (`AnkiDroidApp` will create the folder)
* To know whether we should try `/AnkiDroid`, we need to know:
  * SDK
  * Manifest Permissions
  * If the user denied permissions
    * This was stored by knowing what `deckPath` was
      * The method for this called into getting the collection path
        *  if `deckPath` wasn't null, back to the start

Due to Brayan's suggestion, this is much less of a mess, and we can remove this

2023-02-17 20:33 UTC, david-allison commented on AnkiDroid/build.gradle
> +        targetSdkVersion 30 // change .travis.yml platform download at same time
We removed our Robolectric config a long while back:

4bdb52ce110d3bf174a6775b06ed85e3cc3072f7

2023-02-17 20:41 UTC, david-allison commented on AnkiDroid/build.gradle
> -                    buildConfigField "Boolean", "LEGACY_STORAGE", localProperties["legacy_storage"]
Will be needed for testing. Once we move to `targetSdkVersion 30`, we have more difficulty testing with `/AnkiDroid` as it won't be available by default

After? Absolutely not necessary

2023-02-17 20:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +}
Done

2023-02-17 20:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +            .requestDialog(permissionRequest.permissions) { permissionDialogResult ->
Somewhat improved - awaiting a more concrete suggestion

2023-02-17 22:37 UTC, david-allison commented on AnkiDroid/build.gradle
> -                    buildConfigField "Boolean", "LEGACY_STORAGE", localProperties["legacy_storage"]
done, but blocked on https://github.com/ankidroid/Anki-Android/pull/13261

2023-02-17 23:21 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +}
I do not exactly understand what it means to “request a folder”, how “requesting a permission” can result in “no permission needed” and what “forcing that user has given storage permission” implies. I mean, it's mostly the language that is confusing, but if you have a lot of confusing words it makes it very hard to understand the whole of text. Maybe it could be rewritten in a more simple way? Like if you have `forceUserHasGivenStoragePermissionsIfRequiredByPolicy()` that can be rewritten as
```kt
if (needManageAllFilesPermissionToAccessCollectionLocation() && !hasPermission(MANAGE_ALL_FILES) {
    if (requestPermissions(MANAGE_ALL_FILES) == PermissionRequestResult.Granted) {
        finishActivity()
    }
}
```

2023-02-17 23:25 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +    // If we don't have a collection directory - assume it's non-legacy
What's `deckPath`?

2023-02-17 23:33 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +            }
It's not the `when` per se, it's the fact that there's two return statements and a `when` that can only yield from one branch. On second reading, I think this could be rewritten as

```kt
fun requestStoragePermissions(deckPicker: DeckPicker): PermissionManager.PermissionDialogState {
    return when (val policy = queryCollectionDataRetentionPolicy(deckPicker)) {
        is CollectionDataRetentionPolicy.Unsafe -> PermissionManager.PermissionDialogState.NO_DIALOG_REQUIRED
        is CollectionDataRetentionPolicy.ForceSafeStartup -> requestPermissionViaDialog(policy)
    }
}
```

2023-02-17 23:39 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +    private val checkPermission = activity.registerForActivityResult(ActivityResultContracts.RequestMultiplePermissions()) { results ->
...`launchPermissionDialog` is a verb phrase you usually associate with functions... Incidentally, you also have a function with the same name there.

This has a type `ActivityResultLauncher` (not the best name IMO but at least it is a library name), and since this is a private field in a “permission manager” I'd just go with `activityResultLauncher` maybe?

2023-02-17 23:57 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +        callback.invoke(PermissionResult.fromResults(activityRef, results))
I also see this API for the first time so take anything what I say with a grain of salt, but it's my understanding that when you request something from another activity, after navigating to that other activity, your activity can be killed. Now there's a super low chance of this happening, since the action of giving permissions is probably not resource-heavy, BUT I encountered users who insisted on having “Don't keep activities” on in their daily use of the device... Anyway, now the system has a reply to your activity but the activity is dead, it restarts it and calls it `onActivityResult()`. As I understand, `registerForActivityResult` works similarly by hooking into this machinery, it just hides the request codes and stuff like that from you. But when the system restarts the activity for you, all your in-memory objects that you had prior to launch are lost. So you have to restore what you *might* need to handle replies on every activity launch. And I guess that the `callback` is part of that, so yes.

2023-02-18 00:01 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +        val activity = activityRef.get() ?: throw Exception("activity disposed")
Hmh, say, why do we use a weak reference here in the first place?

2023-02-18 00:41 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +    fun Context.permissionDefinedInManifest(packageName: String, vararg permissions: String): Boolean {
>Used in:

Ah, I see here that the system [gives access to package info of any apps that access a content provide in your app](https://developer.android.com/training/package-visibility/automatic#app-types-visible-automatically), so that should work fine.

> I don't see how this would be more readable

Well, first of all it almost reads like plain language, “if permission [is] in ~~get~~ permissions defined in manifest [of a] package”. Also, not that you are likely to need it, but `getPermissionsDefinedInManifest()` is just more versatile, since you get the entire list. And it's a bit less of passing arguments around

2023-02-18 00:43 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +    fun canManageExternalStorage(context: Context): Boolean =
I thought this was new code?

2023-02-18 04:57 UTC, Arthur-Milchior reviewed
Agreed with @oakkitten, some parts are hard to grasp.

My main question is: do you have any suggestion for manual testing? Given the topic, it's far harder to test than most code, so I'd love to know what you'd suggest if anything.

Codes look good to me, what I read makes sense, but clearly, I have no idea how to check whether it has the expected result on every platform.


Relatedly, if we can still use legacy storage on fdroid and other, can't we upload the app there? This would lead to more testers of non-migration related features. Even if it's not a priority, it would be nice to know if it crashes in places we missed.

2023-02-18 04:57 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> + * Reduces the complexity of handling permission requests via:
Not fan of this comment.
It would be great in the commit message, since this commit reduces the complexity.
But as a code comment, it seems strange, as it does not indicates "Reduces the complexity compared to ..."

So just "Handle permission requests via:"

2023-02-18 04:57 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +        callback: () -> Job,
I'd consider adding the callback to the last position. This way, we can both do:
`executeIfPermissionGranted(permissions) {callbackCode}`
and
```
executeIfPermissionGranted(permissions, {failureCode}) {callbackCode}
```

2023-02-18 04:57 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +                if (!results.any()) return ERROR
Can you also comment in which case it occurs?
Why is it an error if there is no result, in particular no negative result

2023-02-18 04:57 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
> +        /** This should typically not be called: the value of `legacyStorage` should be system-defined */
I don't understand this comment.
Why do you create this function if it should not be called, appart by `getDefaultAnkiDroidDirectory`.
If it's for test purpose, can't we just use VisibleForTest on a private method.  This seems more standard

2023-02-18 04:57 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            val offerToUpgrade = (isLegacyStorage(context) && !userMigrationIsInProgress(context)) && !Permissions.hasAllFilesAccess(context)
The extra parentheseses does not seems useful. Even if not hurtful either

2023-02-18 04:57 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> -    // match previous AnkiDroid behaviour - force the use of /AnkiDroid, since it's fast & safe.
Maybe replace "previous" by "behavior before scoped storage", for long term clarity

2023-02-18 04:57 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +            // we can continue, and it's a waste to add another enum value and complicate the code
Then, maybe, let's rename it to `PERMISSION_REQUESTED`. 
After all, the important information is that the user see some changes, not how the change is displayed. And this will avoid us this comment.

2023-02-18 04:57 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> + * In this a user has to go to permissions -> storage -> 'allow management of all files' -> dialog warning
You use "in this" twice, and it's not clear, reading the documentation, which one is MANAGE_ALL_FILES and which one is displayAppPermissionManagementScreen

Also, I guess that everything but the first line should be a comment and not documentation

2023-02-18 19:32 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +    fun Context.permissionDefinedInManifest(packageName: String, vararg permissions: String): Boolean {
Um no?

2023-02-18 19:37 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +        if (field is ImageField && this.permissionsDefinedInAnkiDroidManifest(Manifest.permission.CAMERA) &&
`permissionsDefinedInAnkiDroidManifest`? I think this function only tells whether the the according `<uses-permission />` exists in the manifest and is applicable.

2023-02-18 19:50 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +                // been shown. This may nto happen here as we call getPermissionResult after we have dialog results
I'd appreciate a comment with a high-level, simple-language overview of how permissions API on this method, too. (Or somewhere else.) `shouldShowRequestPermissionRationale` is a (probably necessary) hack, but its docstring is lacking detail.

2023-02-18 22:29 UTC, mikehardy commented on AnkiDroid/build.gradle
> -                    buildConfigField "Boolean", "LEGACY_STORAGE", localProperties["legacy_storage"]
Just to note that the issue link you put in your comment is self-referential to this same PR, guessing you meant a different one blocking this?

2023-02-19 03:23 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +                if (!results.any()) return ERROR
https://developer.android.com/reference/androidx/core/app/ActivityCompat.OnRequestPermissionsResultCallback

Note: It is possible that the permissions request interaction with the user is interrupted. In this case you will receive empty permissions and results arrays which should be treated as a cancellation.

2023-02-19 03:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +    private val permissionManager = PermissionManager.register(deckPickerRef.get()!!)
It's a private constructor - cleaner this way if it can only be done via a `.register` method

2023-02-19 03:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +    // match previous AnkiDroid behaviour - force the use of /AnkiDroid, since it's fast & safe.
It's fast after `MANAGE_EXTERNAL_STORAGE`, or before Google decided to kill the filesystem speed

2023-02-19 03:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +        if (field is ImageField && this.permissionsDefinedInAnkiDroidManifest(Manifest.permission.CAMERA) &&
I feel the method name is clear

2023-02-19 03:44 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +    fun Context.permissionDefinedInManifest(packageName: String, vararg permissions: String): Boolean {
Awaiting a suggestion here, or I'll close the comment - I've extracted `getPermissionsDefinedInManifest ` and it feels reasonable

2023-02-19 03:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +    // If we don't have a collection directory - assume it's non-legacy
https://github.com/ankidroid/Anki-Android/blob/e5bf3052b82af572539daa24609aa5ee3d2ecda6/AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt#L306-L317

2023-02-19 03:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +        val activity = activityRef.get() ?: throw Exception("activity disposed")
Can be null inside `fromResults`

2023-02-19 05:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +    /** Do not allow AnkiDroid to startup until we have permission to use a safe folder */
This one seems like complexity for complexity's sake. Pushback unless there's a good reason.

In particular, the permissions provided in the array are incorrect for `API >= R`

2023-02-19 05:48 UTC, david-allison commented
Awaiting next round of feedback.

Emulator tests blocked by https://github.com/ankidroid/Anki-Android/pull/13291

2023-02-19 14:29 UTC, david-allison commented on AnkiDroid/build.gradle
> -                    buildConfigField "Boolean", "LEGACY_STORAGE", localProperties["legacy_storage"]
Fixed, thanks

2023-02-19 14:31 UTC, david-allison commented on AnkiDroid/src/main/AndroidManifest.xml
> +        android:maxSdkVersion="29" />
Note: This was incorrect and broke `preserveLegacyStorage` (which almost gave me a heart attack last night). We should not have a `maxSdkVersion`.

2023-02-19 14:35 UTC, david-allison commented on AnkiDroid/build.gradle
> +        targetSdkVersion 30 // change .travis.yml platform download at same time
Was blocked on https://github.com/ankidroid/Anki-Android/pull/13291. Now completed

2023-02-19 14:37 UTC, david-allison commented
@mikehardy This brings in an API split for emulator tests `>= R`. https://github.com/ankidroid/Anki-Android/pull/13291 was required for `amazon`. `play` works with no changes.

Proposal: move this to a separate issue

2023-02-19 16:41 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +    // match previous AnkiDroid behaviour - force the use of /AnkiDroid, since it's fast & safe.
Oh, I didn't know it gets back its previous speed once we request to manage external storage. Good news :)

And yeah, it used to be fast, I agree. But since it's not the case anymore, the comment was strange.

2023-02-19 20:27 UTC, Arthur-Milchior reviewed
still LGTM for the code I read. Same remark as before, it's pretty hard to really get a proper idea as I don't know how we can manually test it.

2023-02-19 20:27 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +    fun hasAllFilesAccess(context: Context): Boolean {
Inconsistent with what ? The behavior or some other naming schemes?

I don't understand why, if the API is too old, you return false. It seems like we could have access to all files on previous versions, assuming the correct preferences were requested.
At the very least, I suspect documentation must be provided to explain what it means exactly

2023-02-19 20:28 UTC, Arthur-Milchior commented
Merge conflict.
Also, we may potentially remove the "blocked by dependency", as #13291 is merged. Or is there another blocker?

2023-02-20 02:15 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +    fun hasAllFilesAccess(context: Context): Boolean {
In code, we call it `MANAGE_EXTERNAL_STORAGE`.

Android UI calls it `All Files Access

2023-02-20 02:23 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +        if (field is ImageField && this.permissionsDefinedInAnkiDroidManifest(Manifest.permission.CAMERA) &&
This is about code unrelated to the PR. If we want to fix my bad naming from 2020, let's move it to another issue.

2023-02-20 10:44 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +    fun Context.permissionDefinedInManifest(packageName: String, vararg permissions: String): Boolean {
`areContextPermissionsDefinedInManifest` sounds like a better name.

2023-02-21 00:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +    fun Context.permissionDefinedInManifest(packageName: String, vararg permissions: String): Boolean {
I don't know what context permissions are.

2023-02-21 04:11 UTC, david-allison commented
> Merge conflict. Also, we may potentially remove the "blocked by dependency", as #13291 is merged. Or is there another blocker?

The blocker was that I believed it would be difficult to test this. I was mistaken

----

Storage can be re-enabled after this change via:

```
adb shell am compat disable DEFAULT_SCOPED_STORAGE com.ichi2.anki.debug
adb shell am compat disable FORCE_ENABLE_SCOPED_STORAGE com.ichi2.anki.debug
adb shell pm grant com.ichi2.anki.debug android.permission.READ_EXTERNAL_STORAGE
adb shell pm grant com.ichi2.anki.debug android.permission.WRITE_EXTERNAL_STORAGE
```

on an API 30 emulator (or a non-AOSP emulator)

2023-02-22 14:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +}
1) Whether the app should take the decision to use a 'safe' or non-safe' folder and attempt to gain permission to use it.
2) If the permission is defined in the Manifest and is already granted, the call to request the permission inside AnkiDroid returns immediately, there's no need to call out to Android to determine this
3) Why would you want to finish the activity if permission is granted? I don't understand the code

2023-02-24 17:04 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +}
> Whether the app should take the decision to use a 'safe' or non-safe' folder and attempt to gain permission to use it.
* I find the terms “safe” and “unsafe” folders too judgemental and confusing, I'd prefer the terms “app-private” and “public”
* I am not sure why we have to have a name for the app deciding whether or not it should decide which of the two folders to use. Are you sure we have to “decide to decide”?
* I am not sure why we have to have a name for the app deciding which of the two folders to use, either.

> If the permission is defined in the Manifest and is already granted, the call to request the permission inside AnkiDroid returns immediately, there's no need to call out to Android to determine this

Why “call to request the permission” instead of “check whether the permission has been granted”?

> Why would you want to finish the activity if the permission is granted? I don't understand the code

Sorry, `==` should've been `!=`. Anyway, it's not a real piece of code, just an illustration

2023-02-24 17:09 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +    // If we don't have a collection directory - assume it's non-legacy
So, mayhaps it could be this?
> If the user has not set a custom collection path, default to the app-private path

2023-02-25 12:55 UTC, mikehardy commented
Conflict again 😩 - what's the status on this one, is it ready for a review do you think? That is, all existing comments addressed? There are 127 comments on here (!?!) it is hard to keep track

2023-02-25 13:06 UTC, david-allison commented
I feel I'm blocked on reviews

2023-02-25 17:42 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +    fun Context.permissionDefinedInManifest(packageName: String, vararg permissions: String): Boolean {
Seems like I had written context permissions by mistake. What I meant was `arePermissionsDefinedInManifest` only.

2023-02-25 19:25 UTC, oakkitten reviewed
I can understand some parts of code but others are a little too blurry for me to see a coherent overall picture. I really wish we had simple-language, not-too-technical descriptions of what's going on, where applicable...

2023-02-25 19:25 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        if (requestStoragePermissionsForDialog()) return
“Request storage permissions for dialog”? Do we have a dialog that requires storage permissions? It's not clear from the method what it returns.

2023-02-25 19:25 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        permissions = requiredPermissions,
`requiredPermissions` can be an empty array, does this make sense to call this with empty permissions?

2023-03-01 21:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +        if (!activityRecreated || useCallbackIfRecreatedSuccessfully) {
An ActivityResultLauncher handles intents in a type-safe manner. It is launched via a `launch` method. In this case it accepts one or more permissions and displays an Android permissions dialog. The callback is executed once the permissions dialog is closed and focus returns to the app

2023-03-01 22:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +    fun launchPermissionDialog(): PermissionDialogState {
Split into check + request. I feel this complicates the calling code.

2023-03-01 22:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +        showAppPermissionManagementScreen()
It allows for the same permission to be granted (albeit with a worse UI)

2023-03-01 22:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    ) // used for check media
🤷‍♂️ Been reported by @Arthur-Milchior and I believe @mikehardy  has also run into this one.

2023-03-01 23:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        permissions = requiredPermissions,
We don't have a 'non-empty array' class. I'm fine with leaving this as a later refactoring

2023-03-02 00:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +    this.finishWithoutAnimation()
This one doesn't seem worthwhile

2023-03-02 00:08 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +        if (!activityRecreated || useCallbackIfRecreatedSuccessfully) {
I was referring to `if (!activityRecreated || useCallbackIfRecreatedSuccessfully)` specifically

2023-03-02 00:08 UTC, david-allison commented
Split out permissions into a `check` + `showDialog` model.

Added `RequestPermissionsResult` + `CheckPermissionsResult`

2023-03-06 03:04 UTC, david-allison commented
What's needed to get this merged?

2023-03-06 16:42 UTC, mikehardy commented
If you feel all the items brought up have been addressed and you rebase, I'll look through (again), and if it looks good I can hit the button

2023-03-06 16:57 UTC, david-allison commented
Rebased. Awaiting review

2023-03-07 07:31 UTC, Arthur-Milchior approved these changes
I noted two potential issues with the WeakPointer. Otherwise, it's only nit and documentation request/suggestion.

I personally would accept to merge as-is, given that the bug are not important, and that everything can be corrected/answered later. This way, we'd unblock more work on the migration code.

2023-03-07 07:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
> +    }
Then please, at least, add a todo to remove it. And if you still have it, a link to @BrayanDSO suggestion.

2023-03-07 07:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +    fun hasAllFilesAccess(context: Context): Boolean {
Please rename to `allFileAccessPermissionGranted`.
Or at the very least, add a javadoc to mention you are referring to the permission.

Because the way this function read while browsing the code, it seems like you check whether you really have access to all files. Which means that, up to Android 9, we should return "true" (since there was no limit to file access)

2023-03-07 07:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
>              return Status.COMPLETED
I'd prefer if you could add a new status, "UNREQUIRED" or "NOT_NEEDED" or something similar. 
So that if you have `allFileAccess`, the result indicate that the status of the migration is that the migration won't occur.
"COMPLETED" for a migration that did not occur seems wrong to me

2023-03-07 07:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> -        return hasPermission(context, Manifest.permission.WRITE_EXTERNAL_STORAGE)
Nit: I'd suggest keeping `hasPermission` in all commit. This way, you don't have to change those lines of tests.

2023-03-07 07:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
>       *
I believe the documentation is slightly wrong.
It should be "(as long as AnkiDroid targeted API<30, requested legacy storage, and has been continously installed since)"
Because we may still have permission, while targeting API 30

2023-03-07 09:59 UTC, Arthur-Milchior commented
Also, you got a merge conflict

2023-03-07 10:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +        if (field is ImageField && this.arePermissionsDefinedInAnkiDroidManifest(Manifest.permission.CAMERA) &&
There was a lot of commits in this originally which were split out. Will do this

2023-03-07 10:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
> +    }
This was removed

2023-03-07 10:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +    /** Do not allow AnkiDroid to startup until we have permission to use a safe folder */
> I'd have a slight preference to introduce the documentation in the commit that introduce this class. But that's a nitpick and I'm fine with the end result

done

2023-03-07 11:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> -    private fun requestStoragePermission() {
I fear this will take too much time at this point

2023-03-07 12:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> -        return hasPermission(context, Manifest.permission.WRITE_EXTERNAL_STORAGE)
Much nicer - turns out I'd refactored out the vararg call in previous reviews

2023-03-07 12:41 UTC, david-allison commented
rebased with partial fixes, still on me

2023-03-07 16:01 UTC, BrayanDSO commented on .github/workflows/tests_emulator.yml
> +        api-level: [30]
As the comment above explains, 29 was chosen because it were the fastest emulator, based on tests. 

If the 29->30 change is necessary, the comment should be updated as well

2023-03-07 21:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                showMediaCheckDialog(MediaCheckDialog.DIALOG_MEDIA_CHECK_RESULTS, mediaCheckResult)
I'll leave this as a TODO

2023-03-08 00:18 UTC, david-allison commented
As a follow-up to: 

> Verify behaviour on Android Q, <Q. I didn't confirm in the docs, and it seems unusual that there's one Android where we have neither WRITE_EXTERNAL_STORAGE nor MANAGE_EXTERNAL_STORAGE

Done some manual testing. Android Q allows `WRITE_EXTERNAL_STORAGE` & access to `/AnkiDroid`, the issue is 10 -> 11

2023-03-12 00:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> + * Closes the activity and opens the Android settings page for AnkiDroid
You resolved it, but didn't update the documentation accordingly (nor replied to my remark if you disagree)

2023-03-12 00:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +    object DeleteOnUninstall : AnkiDroidFolder
I'm confused.
It seems you followed my advice for `PublicFolder`. So why didn't you rename `DeleteOnUninstall` to something such as `ScopedFolder` that indicates the selected folder

2023-03-12 00:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        // and a user should use one of the below options to provide aster speeds
Nit: faster

2023-03-12 00:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +    uninstallPolicy: AnkiDroidFolder,
Given the change in type, I guess the variable name should also be changed. Probably something such as `ankidroidFolder`

2023-03-12 00:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +        val activity = activityRef.get() ?: throw Exception("activity disposed")
So, as explained elsewhere, I was clearly wrong here. The callback is not kept in memory during permission request. This is why it's important to immediately register the callback, because the newly registered callback will be call.
Anyway, since this callback capture the activity, the activity lives as long as the callback. So the activity can't become null. So this weakRef is useless here

2023-03-12 00:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
> +        if ((!isLegacyStorage(context) && !userMigrationIsInProgress(context))) {
You can now remove the extra parenthesis

2023-03-12 00:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +            // checkSelfPermission doesn't return PERMISSION_GRANTED, even if it's granted.
```
`checkSelfPermission` can't be used on `MANAGE_EXTERNA_STORAGE`; even if the permission is granted, it  returns  PERMISSION_DENIED
```
Also, it would be nice in the comment that you gives a link explaining this (I can't easily find one), or just that you state you discovered it through experiment. If it's too long, just put it in the commit message instead.
That seems interesting to know in particular because, for what I know, it may be an issue specific to some manufacturer for example.

2023-03-12 01:48 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +}
Sorry, I guess the better grammar would be “a name for the **app's** deciding whether or not it should decide which of the two folders to use”, that is, a name for
> Whether the app should take the decision to use a 'safe' or non-safe' folder and attempt to gain permission to use it.

I'm not exactly sure what's going on here, but the bottom line is that overly complicated concepts might be useful to split into several simpler concepts. Even if the complicated concept is used several times. Sometimes more code reads easier than less code!

2023-03-12 18:36 UTC, oakkitten requested changes

2023-03-12 18:36 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
> +    }
The most recent commit is 2e8e3c9 and I think this method is still there? It doesn't seem to be used by anything

2023-03-12 18:36 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +        }
I'm still not a fan of this method—`getPermissionsDefinedInManifest` could be used directly—but I don't think you need the `try` here since `getPermissionsDefinedInManifest` won't throw anything. Or, have it throw.

2023-03-12 18:36 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> +    fun allFileAccessPermissionGranted(context: Context): Boolean {
I would put “manage external storage” into the name of the method for the sake of having the same concept have the same name throughout the code

2023-03-12 18:36 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        is AnkiDroidFolder.DeleteOnUninstall -> noPermissionDialogRequired
I also wonder if we can skip registering for activity results if we aren't planning on requesting permissions. I know that you are supposed to that unconditionally, but I don't suppose the system will blow up if we get a response for a code that we did not request?

2023-03-12 19:01 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    ) // used for check media
Not much else to say. Arthur had it happen where his storage was in this state, and I also saw it. It makes no sense. Yet it was observed. Sometimes reality doesn't make sense when you don't know all the underlying stuff so I'm going to just worship the Scoped Storage God and say, this happens sometimes.

2023-03-12 19:03 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    // used for check media
I followed your link @oakkitten and closed the related conversation because "observed phenomena".
Please propose a more detailed explanation here so we can close this one

2023-03-12 19:05 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionsCheckResult.kt
> +open class PermissionsCheckResult(val permissions: Map<String, Boolean>) {
@oakkitten  If we're going that descriptive why not `permissionToGrantedStatus` (the thought seems truncated to me without the idea it's the granted state, but yes in my other projects typically permissions is just an array of string constants, so rename fine)

Please yay/nay that quickly so it can be done

2023-03-12 19:13 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +            }
Going to lean on implementor's choice on this one. "too complicated" is qualitative, and David has a long-term history of supporting his implementations so I assert it is not enough to disqualify the implementation.

Suggest for velocity that we then go with your your suggestion of adding a comment. In absence of David and with Arthur's plan this would become a code change by us here with a `// TODO - add comment explaining <the stuff you want explained>`. Yes/no?

2023-03-12 19:15 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionsCheckResult.kt
> +    val requiresPermissionDialog: Boolean = permissions.any { !it.value }
@oakkitten Seems reasonable. Are you prepared to pull this PR and make a final commit (or series of commits) that includes this change in concert with whatever is consuming the value?

2023-03-12 19:18 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +sealed interface AnkiDroidFolder {
I understand names are important but I must admit I grow weary of seeing naming suggestions.
Are you prepared to pull this PR and propose a commit that alters this to your liking?

2023-03-12 19:21 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +    class PublicFolder(val requiredPermissions: Array<String>) : AnkiDroidFolder
Seems more testable like this. And this code itself is tested, perturbing it has a cost, esp w/David out now. I'm not feeling particularly moved. Are you prepared to pull this PR, make a commit that alters it to your liking, test it all out in the various scenarios and support it? You might be if so awesome, but that's the standard here for going with your comment - it needs to turn from words to concrete + tested + supported code ASAP

2023-03-12 19:22 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                val permissionResult = PermissionsRequestResults.from(deckPicker, permissionResultRaw)
Gonna need commitment on your part to make a commit or it resolves

2023-03-12 19:23 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        }
Are you willing to make a commit + test + support it with this refactor? If so, okay

2023-03-12 19:25 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +}
strange, I don't see the code this is referencing. This doesn't seem like it clears the "important enough to care about" bar to me though

2023-03-12 19:25 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +@NeedsTest("Existing User: Changes Deck")
use code suggestion tool on github UI to add `// TODO <thing I want here>` ?

2023-03-12 19:26 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        deckPicker.finishActivityAndShowAppPermissionManagementScreen()
same, can use a TODO suggestion. Or you can pull + make commit + retest everything + commit to support

2023-03-12 19:26 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +    private fun onRegularStartup() {
suggestion or commit

2023-03-12 19:28 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +    private fun retryPermissionRequest(displayError: Boolean) {
The deadline haiku:

new name suggestion
but is not a code suggestion
another cycle

2023-03-12 19:30 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        if (timesRequested < 3) {
seems arbitrary, but asking infinitely is bad UX. Some limit must be chosen. 3 seems reasonable.
Not saving across app restart doesn't seem right, `// TODO save in user prefs to survive app restarts` as code suggestion?

2023-03-19 13:21 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    // used for check media
I do not see how this is possible. I don't know what exactly was observed, so I can't judge, but might it be that in this case whatever was observed was caused by an unrelated problem?

Since I don't see how this is possible, I would remove this logic. Instead, maybe we could try catching the “impossible” state and send details about it to that ACRA thing?

2023-03-19 13:23 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionsCheckResult.kt
> +open class PermissionsCheckResult(val permissions: Map<String, Boolean>) {
I wouldn't mind “granted state” but I personally don't find it much better than just “granted”

2023-03-19 13:49 UTC, oakkitten commented
I'm replying here to most of the comments by @mikehardy since the replies would be largely the same.

I think adding a TODO is a viable strategy only if either:

* There's a guarantee that the TODO will be resolved soon, or
* The TODO is about an isolated implementation detail, and not the API.

If we add TODOs here, there's a high chance that they will not be resolved ever. This code for the most part will run only once for all users, and if it does work, I'd advocate against touching it.

More importantly, the proposed TODOs would be about names and overall design, something that is *not* isolated implementation details. As they are about the API, they should be resolved as soon as possible, hopefully before the PR is merged. The reason is that the API is used by other code, read by other developers, and other API is built upon this API. If the API is not ideal, this makes it hard to understand the behavior, hard to verify code correctness, and wastes time of the developers who are using these API. The technical debt has a tendency to snowball, and if we should care about it at all, we should care *now*, as we are not going to be looking to improve this code in the long run.

So I don't think that adding TODOs would be suitable here. If the suggested change is important, we should follow up now, and if it's not, let's mark it as won't fix and move on.

To answer the questions about whether or not I am willing to personally retouch the code, I can't say now. I don't yet have a full understanding of the behavior, so it may take considerable time to dig into it. If I do find the time, I'll be sure to ask David if I can try to put some commits on top of this PR, but I can't make any promises at the moment.

2023-03-19 13:51 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +}
Sorry, should've marked the entire method. Not sure if this link is going to work [ankidroid/Anki-Android/pull/13261/files/2e8e3c946dd5401976b274c028c9bf4170a9e5d4#diff-b79dae2d4822b030b95a66fc05fa9d611a8299ea1b0fd8812e80b67a5c2cd4eeR155-R175](https://github.com/ankidroid/Anki-Android/pull/13261/files/2e8e3c946dd5401976b274c028c9bf4170a9e5d4#diff-b79dae2d4822b030b95a66fc05fa9d611a8299ea1b0fd8812e80b67a5c2cd4eeR155-R175)

2023-03-20 16:22 UTC, mikehardy commented
>  I don't think that adding TODOs would be suitable here. If the suggested change is important, we should follow up now, and if it's not, let's mark it as won't fix and move on.

Ok. I will pay special attention to anything that appears to be particularly important, and extract to an issue as needed.

> To answer the questions about whether or not I am willing to personally retouch the code, I can't say now. I don't yet have a full understanding of the behavior, so it may take considerable time to dig into it. If I do find the time, I'll be sure to ask David if I can try to put some commits on top of this PR, but I can't make any promises at the moment.

Ok, with phrase "considerable time" noted - that's critical.

So, to me that is fine and I understand not wanting to commit. However, without a firm immediate commitment, a declared stance of wanting to wait to understand more and the phrase "considerable time" is functionally equivalent to a call for delay.

Call for delay considered. Not going to delay. Going to generally mark as won't fix and move on.

2023-03-20 16:38 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +        val activity = activityRef.get() ?: throw Exception("activity disposed")
Peeled off as #13460 though I don't think it will affect functionality

2023-03-20 16:39 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +            PermissionManager(activity, permissions, useCallbackIfActivityRecreated, callback)
Can be done as a follow-on PR if desired

2023-03-20 16:43 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +    uninstallPolicy: AnkiDroidFolder,
Feel free to change variable names later in follow-on PR as desired, seems unimportant vs merge at the moment.

2023-03-20 16:43 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +    object DeleteOnUninstall : AnkiDroidFolder
not important enough for delay - happy to entertain a follow-on PR if desired

2023-03-20 17:39 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
> +    private lateinit var callback: ((PermissionsRequestResults) -> Unit)
I believe based on a bunch of reading just now that it is a constructor parameter and initialized then, as it is supplied in the only constructor call I see. If I am wrong, this can be corrected follow-on

2023-03-20 17:43 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        if (timesRequested < 3) {
I believe based on my read of control flow that this is only requested if we really need permission, or the app simply won't work. So retrying again across app restarts is I think a feature not a bug

2023-03-20 17:43 UTC, mikehardy approved these changes
LGTM

2023-03-20 17:45 UTC, merged

2023-03-20 19:15 UTC, timrae commented
Looks like this was a very complex beast, good work all involved!

2023-03-20 22:30 UTC, Arthur-Milchior commented
Thanks @timrae. Nice seeing you here :)