Make collection calls async on Preferences
ankidroid/Anki-Android pull request #13295
Opened 2023-02-18 17:00 UTC by BrayanDSO

note: getDayOffset() was copied and pasted into Stats.kt because Stats.kt will be removed once the new backend is the default, which means that refactoring it to use suspend functions isn't worth the time

## Pull Request template

## Purpose / Description
Collection calls shouldn't be on the UI thread to avoid freezing

## Fixes
Supersedes #12943 (TIL: Force-pushing before reopening a PR makes impossible to open it again)

## Approach
Use coroutines and withCol() to replace the previous collection calls

note: getDayOffset() was copied and pasted into Stats.kt because Stats.kt will be removed once the new backend is the default, which means that refactoring it to use suspend functions isn't worth the time

## How Has This Been Tested?

SDK 25 emulator
Tried to change in-app all the settings I've edited

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-02-18 17:06 UTC, david-allison approved these changes

2023-02-18 22:10 UTC, mikehardy commented
Safe to merge - prettier action is having some problem, temporarily removed, will re-enable here per #13296

2023-02-19 08:39 UTC, lukstbit requested changes

2023-02-19 08:39 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
> +                        lifecycle.coroutineScope.launch {
The outer `try-catch` block needs to be inside the coroutine otherwise it's not going to catch the possible exception thrown inside. So it should be inside the `withCol {}` lambda.

Also, we should use launchCatchingTask or launchWithCol instead of `lifecycle.coroutineScope.launch`.

2023-02-19 10:32 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
> +                        lifecycle.coroutineScope.launch {
I've removed the `try-catch` because that specific exception is not thrown anywhere in the app

2023-02-19 11:20 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
> +                        lifecycle.coroutineScope.launch {
Even better!

2023-02-19 11:21 UTC, lukstbit approved these changes

2023-02-19 12:21 UTC, merged