Storage Migration: Notification to handle failure
ankidroid/Anki-Android pull request #13300
Opened 2023-02-19 02:21 UTC by david-allison

## Pull Request template

## Purpose / Description
Handles a few TODOs. Previously a crash would have occurred

## Fixes
Issue #5304

## Approach
* Show a notification with a 'copy debug info'
  * Copies Exception + Stack trace to clipboard
* Submits a Crash Report

## How Has This Been Tested?

<details>
<summary>Manually by having `MoveFile` throw - debug info included</summary>

```
Migration failed
 java.lang.IllegalStateException: Testing
	at com.ichi2.anki.servicelayer.scopedstorage.MoveFile.execute(MoveFile.kt:42)
	at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$Executor.executeOperationInternal$AnkiDroid_playDebug(MigrateUserData.kt:344)
	at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$Executor$execute$1.invoke(MigrateUserData.kt:334)
	at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$Executor$execute$1.invoke(MigrateUserData.kt:333)
	at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$MigrationContext.execSafe(MigrateUserData.kt:187)
	at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$Executor.execute(MigrateUserData.kt:333)
	at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData.migrateFiles$moveRemainingFiles(MigrateUserData.kt:500)
	at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData.migrateFiles(MigrateUserData.kt:509)
	at com.ichi2.anki.services.MigrationService$onStartCommand$1.invoke(MigrationService.kt:225)
	at com.ichi2.anki.services.MigrationService$onStartCommand$1.invoke(MigrationService.kt:220)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$DirectoryNotEmptyException: directory was not empty: /storage/emulated/0/AnkiDroid/backup
	at com.ichi2.anki.servicelayer.scopedstorage.DeleteEmptyDirectory.execute(DeleteEmptyDirectory.kt:36)
	at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$SingleRetryDecorator.execute(MigrateUserData.kt:296)
	at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$Executor.executeOperationInternal$AnkiDroid_playDebug(MigrateUserData.kt:344)
	at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$Executor$execute$1.invoke(MigrateUserData.kt:334)
	at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$Executor$execute$1.invoke(MigrateUserData.kt:333)
	at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$MigrationContext.execSafe(MigrateUserData.kt:187)
	at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$Executor.execute(MigrateUserData.kt:333)
	at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData.migrateFiles$moveRemainingFiles(MigrateUserData.kt:500)
	at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData.migrateFiles(MigrateUserData.kt:509)
	at com.ichi2.anki.services.MigrationService$onStartCommand$1.invoke(MigrationService.kt:225)
	at com.ichi2.anki.services.MigrationService$onStartCommand$1.invoke(MigrationService.kt:220)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

```

</details>

![Screenshot 2023-02-19 at 02 08 37](https://user-images.githubusercontent.com/62114487/219908584-c5e21832-60ea-4814-b8c3-95c5d79d5164.png)
![Screenshot 2023-02-19 at 02 08 43](https://user-images.githubusercontent.com/62114487/219908586-c01b7aff-70b7-4ae5-a137-80043e6eaea9.png)

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-02-19 13:59 UTC, mikehardy approved these changes
Nice way to handle it, to my way of thinking

2023-02-19 19:24 UTC, BrayanDSO requested changes

2023-02-19 19:24 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
> +    private fun copyToClipboard(intent: Intent) {
I'd try extracting part of the logic of `copyDebugInfo()` from AboutFragment.kt to avoid repetitions in the code.

If you think this shouldn't be the case, I suggest renaming the method to `copyDebugInfoIntoClipboard`, as the current name can be a bit vague

2023-02-19 19:24 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
> +        }
Is there a place where the "migration is ongoing" sharedPref is reset to false, so the user can restart the migration?

2023-02-19 19:24 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/migrateuserdata/MigrateUserData.kt
> +            val migrationFailed = AnkiDroidApp.instance.getString(R.string.migration_failed_message)
`val migrationFailedMessage`

2023-02-19 20:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
> +    private fun copyToClipboard(intent: Intent) {
One uses a snackbar, this uses a toast

2023-02-19 20:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
> +        }
No, other than in this class when it's completed. Migration is attempted each time the app is launched

2023-02-20 01:32 UTC, Arthur-Milchior approved these changes
One nit. Agree with Brayan, might be worse to avoid duplication if possible. But not blocking, so LGTM

2023-02-20 01:32 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
> +        DEFAULT_START_APP_IF_NEW, FILE_IMPORT, SYNC, REVIEW, COPY
I fear COPY is not clear. COPY_DEBUG_INFO is nice, and there will be no doubt what it means when someone read it in 5 years

2023-02-20 02:02 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
> +    private fun copyToClipboard(intent: Intent) {
I (mildly) don't feel this is worthwhile as they're different + agree with Arthur.

Reviewer's choice as to continue

2023-02-21 22:18 UTC, BrayanDSO approved these changes

2023-02-21 22:26 UTC, david-allison commented
Let me rebase this one to ensure the lint change didn't eat it

2023-02-22 10:19 UTC, BrayanDSO commented
Conflicts

2023-02-23 14:05 UTC, merged