fix getParcelable deprecation
ankidroid/Anki-Android pull request #13310
Opened 2023-02-19 15:04 UTC by RobozinhoD

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
part of https://github.com/ankidroid/Anki-Android/issues/12364

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

I don't know how to test this

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-02-19 15:38 UTC, david-allison requested changes
nitpick, then let's go!

2023-02-19 15:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
> +        inline fun <reified T> Bundle.getParcelableCompat(key: String): T? {
Would be great to have comments here

2023-02-19 16:35 UTC, RobozinhoD commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
> +        inline fun <reified T> Bundle.getParcelableCompat(key: String): T? {
done

2023-02-19 17:24 UTC, mikehardy commented
Conflicts with a previous change that you also made, in parallel I think ? (no good deed unpunished! hopefully easy to resolve)

While de-conflicting, please rebase against main just to make sure ktlint changes from #13265 are handled just in case

Thank you!

2023-02-22 19:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
> +        return bundle.getParcelable(key)
Can this be tested? I'm surprised it works without a cast

2023-02-22 19:27 UTC, david-allison commented
Lint is failing

2023-02-22 19:36 UTC, RobozinhoD commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
> +        return bundle.getParcelable(key)
how can I test this?

2023-02-22 19:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
> +        return bundle.getParcelable(key)
On an emulator using an API before the method in `CompatV33` overrides it

2023-02-22 20:06 UTC, RobozinhoD commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
> +        return bundle.getParcelable(key)
I added a getParcelableCompat line among DeckPicker and it didn't crash after running the line

2023-02-22 20:53 UTC, david-allison approved these changes
Ah, underlying method is `<T>`, that works

LGTM

2023-02-22 21:08 UTC, BrayanDSO approved these changes
Seems like you really don't like deprecations. LGTM

2023-02-22 21:08 UTC, merged

2023-02-23 15:50 UTC, mikehardy commented
I hate deprecations as they *do* eventually result in "cannot release anymore" blockers, so I love these PRs. Thank you!