Disable some settings if migrating storage
ankidroid/Anki-Android pull request #13329
Opened 2023-02-23 01:37 UTC by david-allison

## Pull Request template

## Purpose / Description
Migrating storage is a high-risk operation as it involves copying the user's media

Disable:
* AnkiDroid Directory
  * Corruption: Media from the one collection is moved to the other
* V3 Migration
  * High Risk: Disabling defensively

## Related
- #5304
- #13904

## Approach
We add a snackbar, but don't grey the preferences as it's significant effort for a low-traffic screen

## How Has This Been Tested?
Manually: API 33 emulator

## Learning
* If a preference is not disabled, the `click` handler won't stop the change/dialog event
* If disabled, the `click` handler doesn't fire

But we can handle the dialog event separately to catch this

On switch/checkbox preferences, all we need to do is override `setOnPreferenceChangeListener` AFTER it's been set conditionally

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-02-23 13:55 UTC, mikehardy approved these changes
LGTM - strings are clear right now, easy merge

2023-02-23 17:10 UTC, criticalAY approved these changes

2023-02-24 20:02 UTC, david-allison commented
replaced implementation with a summary change. Thanks to @BrayanDSO for the idea

2023-02-24 20:48 UTC, BrayanDSO requested changes

2023-02-24 20:48 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
> +        val isStorageMigrationOccurring = try {
only used inside `disableIfStorageMigrationInProgress`, so it should be there

2023-02-24 20:48 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
> +            // The only expected crash is due to preference corruption, not database corruption
Is there a scenario where you think that a preference could be corrupted? I don't know if this is even possible

2023-02-24 20:48 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
> +            ScopedStorageService.userMigrationIsInProgress(this.requireContext())
remove `this.`

2023-02-24 20:48 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
> +            if (!isStorageMigrationOccurring) return
the method reads better without this being a guard clause, i.e. writing it as 
```kotlin
if (isStorageMigrationOccurring) {
...
}
```

2023-02-24 21:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
> +            // The only expected crash is due to preference corruption, not database corruption
More likely to be a logic error, but we do NOT want to lose access to this screen right now as it's one of our recovery options.

2023-02-24 22:26 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
> +            // The only expected crash is due to preference corruption, not database corruption
So, change the comment to reflect that this is just for extra precaution instead of saying that someone can expect a crash due to a preference corruption

2023-02-24 23:26 UTC, BrayanDSO approved these changes

2023-02-25 00:36 UTC, david-allison commented
This one good to go (with strings)

2023-02-25 12:58 UTC, mikehardy commented
There's a fair chunk of strings activity (https://crowdin.com/project/ankidroid/activity-stream) since last build.
It is only an optimization but it is a useful one IMHO, better to clear them out.
I'll run strings now then hopefully (with a concerted push from everyone) we can merge all the strings PRs in a batch for optimal optimalness

2023-02-25 17:44 UTC, ShridharGoel approved these changes

2023-02-25 22:19 UTC, mikehardy approved these changes
clean!
I just checked crowdin activity and there has been more from 2 people in between me cleaning strings and right now, but their translations all check out, so the strings PR will be easy

2023-02-25 22:19 UTC, merged