update CardBrowser.kt
ankidroid/Anki-Android pull request #13321
Opened 2023-02-21 13:39 UTC by zaidazaize

#13182

## Fixes
- converted nullable to  lateinit var type
- Removed notnull (!!) assertions
- simplified comparison logic
- Edited UnitTests in CardBrowserTest file (removed not null (!!) assertions)

## How Has This Been Tested?
- Tests

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-02-21 13:42 UTC, zaidazaize commented
@david-allison I have updated the code in new pull request.

2023-02-21 17:56 UTC, david-allison requested changes

2023-02-21 17:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        val columnsContent = arrayOf(COLUMN1_KEYS[mColumn1Index], COLUMN2_KEYS[mColumn2Index])
You've extracted something which depends on `mColumn1Index`, but the value is now uninitialised

2023-02-21 17:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    private lateinit var mRestrictOnDeck: String
default this to `""`

2023-02-21 17:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    private lateinit var mSearchItem: MenuItem
I worry that a few of these are only valid if in multiselect:

```kotlin
if (!isInMultiSelectMode) {
```

Could you test to see if the setters can be extracted from the conditional (`.findItem` shouldn't require that the item be visible, but do confirm).

2023-02-21 23:53 UTC, david-allison commented
Note: merge contained no changes, still waiting for reply

2023-02-22 12:54 UTC, zaidazaize commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    private lateinit var mSearchItem: MenuItem
The setters cannot be extracted as `mSearchItem` which reffrences `R.id.action_search` is present in `R.menu.card_browser`  which is inflated when `!isInMultiSelectMode.`  
On second situation when `isInMultiSelectMode` `R.menu.card_browser_multiselect` menu is inflated which does not contain  `R.id.action_search` menu item . 
I think all the menu items will be initialised before they are used and during the test those variables which were called before initialisation I have put the conditions to check for for initialisation status .

2023-02-22 14:01 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        val columnsContent = arrayOf(COLUMN1_KEYS[mColumn1Index], COLUMN2_KEYS[mColumn2Index])
Yes, it still needs a test

2023-02-22 14:10 UTC, zaidazaize commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        val columnsContent = arrayOf(COLUMN1_KEYS[mColumn1Index], COLUMN2_KEYS[mColumn2Index])
done

2023-02-22 14:25 UTC, zaidazaize commented
If we use layout binding then many variables could be removed and also we do not have to worry about the variable initilization . Besides `findViewById` takes more time . I am thinking to use layout binding

2023-02-22 14:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    private lateinit var mSearchItem: MenuItem
It would be best to remove `lateInit` from these then, and handle the menu using another mechanism in further cleanuos

2023-02-22 14:39 UTC, david-allison commented
> If we use layout binding then many variables could be removed and also we do not have to worry about the variable initilization . Besides `findViewById` takes more time . I am thinking to use layout binding

See: https://github.com/ankidroid/Anki-Android/issues/11116

I don't want to take on a project which will only be done halfway (as one of the maintainers will be left picking up the pieces)

2023-02-22 15:39 UTC, zaidazaize commented
See I read the thread . No doubt the project is big shifting every file to `dataBinding` on single go is disastrous. See no doubt using databinding is better choice but since many things are going on same time so what i propose is that we should start dataBinding in the project and convert one activity at a time or one layout at a time (which suits best based on the load). It will be a long process because we have to make sure that other people who are working on different sections of the project are not facing much problem.
See I can give 6-10 hrs/week and in next 8-10 weeks I can shift the whole project to use databinding.
I can work on it.

2023-02-22 16:50 UTC, zaidazaize commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    private lateinit var mSearchItem: MenuItem
done

2023-02-22 17:42 UTC, david-allison requested changes

2023-02-22 17:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    @NeedsTest("mColumn1Index is uninitilized")
the point of the test is to ensure that `mColumn1Index`/`mColumn2Index` are used.

2023-02-22 17:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        val columnsContent = arrayOf(COLUMN1_KEYS[mColumn1Index], COLUMN2_KEYS[mColumn2Index])
`mColumn2Index` has the same problem that `mColumn1Index` did

2023-02-22 19:37 UTC, david-allison requested changes

2023-02-22 19:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    @NeedsTest("mColumn1Index/mColumn2Index")
Explain what needs testing: `ensure mColumn[1/2]Index are used as default columns`

2023-02-22 19:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -        cardsListView!!.setOnScrollListener(RenderOnScroll())
Where has this line gone?

2023-02-23 01:42 UTC, david-allison reviewed
One last one I think

2023-02-23 01:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        if (!this::mSearchView.isInitialized || mSearchView.isIconified) {
If were doing this, it probably shouldn't be lateinit and it'll cause bugs

2023-02-23 01:43 UTC, david-allison commented
> See I read the thread . No doubt the project is big shifting every file to `dataBinding` on single go is disastrous. See no doubt using databinding is better choice but since many things are going on same time so what i propose is that we should start dataBinding in the project and convert one activity at a time or one layout at a time (which suits best based on the load). It will be a long process because we have to make sure that other people who are working on different sections of the project are not facing much problem. See I can give 6-10 hrs/week and in next 8-10 weeks I can shift the whole project to use databinding. I can work on it.

Let's bring it to Discord `ankidroid-dev` to discuss

2023-02-23 08:02 UTC, zaidazaize commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        if (!this::mSearchView.isInitialized || mSearchView.isIconified) {
Actually it is similar to checking for nullable but making it lateint exempts us from `!!` Assertions of non nullable . This is only accessed at this place before initialisation.

2023-02-23 08:03 UTC, zaidazaize commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        if (!this::mSearchView.isInitialized || mSearchView.isIconified) {
Do want me to revert it .?

2023-02-23 15:23 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        if (!this::mSearchView.isInitialized || mSearchView.isIconified) {
Aim for the principle of least surprise. If a developer sees a `lateinit var`, they have no reason to check it for being null. Checking `isInitialized ` should be a special case (`finish()` being called early) but in normal execution of the app. 

Revert

2023-02-23 15:42 UTC, zaidazaize commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        if (!this::mSearchView.isInitialized || mSearchView.isIconified) {
done

2023-02-23 19:35 UTC, david-allison requested changes

2023-02-23 19:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    private lateinit var mActionBarTitle: TextView
This one also wasn't moved to `onCreate`

2023-02-23 19:43 UTC, zaidazaize commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    private lateinit var mActionBarTitle: TextView
it's there

2023-02-23 19:43 UTC, zaidazaize commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        mActionBarTitle = findViewById(R.id.toolbar_title)
here it is

2023-02-24 00:33 UTC, david-allison approved these changes

2023-02-25 17:22 UTC, lukstbit approved these changes
Thanks!

2023-02-25 17:31 UTC, merged