updated sync icon and migration progress
ankidroid/Anki-Android pull request #13335
Opened 2023-02-23 17:05 UTC by criticalAY

## Pull Request template
Added migration progress icon in the menu

## Purpose / Description
Puts the migration icon while we migrate and hides the sync icon

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-02-23 17:28 UTC, david-allison commented
```
> Task :AnkiDroid:ktlintMainSourceSetCheck FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:700:11 Missing spacing after "if"
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:720:1 Needless blank line(s)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:820:77 Missing spacing after ","
```

lint failure - aware you're working through issues now

2023-02-23 19:54 UTC, criticalAY commented
@david-allison Have fixed the code

2023-02-23 20:32 UTC, david-allison requested changes
The arrow seems slightly smaller, confirm I'm correct (didn't screw up the layered screenshots), then fix, then LGTM

![Screenshot 2023-02-23 at 20 31 19](https://user-images.githubusercontent.com/62114487/221023263-2f887f39-26b6-4e93-ac6a-8c4fe3636c3f.png)

2023-02-23 21:29 UTC, criticalAY commented
I have increased the icon size by little

2023-02-23 23:12 UTC, david-allison requested changes
Nitpicks to make this pixel perfect. One request to find out why this is necessary (timeboxed) then happy to squash + go.

Thanks!

2023-02-23 23:12 UTC, david-allison commented on AnkiDroid/src/main/res/layout/migration_progress_menu_layout.xml
> +    android:layout_height="wrap_content"
Timebox an investigation to see why this is needed (both start and end are 12dp too short)

```suggestion
    android:layout_height="wrap_content"
    android:paddingHorizontal="12dp"
```

2023-02-23 23:12 UTC, david-allison commented on AnkiDroid/src/main/res/layout/migration_progress_menu_layout.xml
> +        android:layout_height="28dp"
```suggestion
        android:layout_width="30dp"
        android:layout_height="30dp"
```

2023-02-23 23:14 UTC, david-allison requested changes
marking as needing feedback - albeit minor.

2023-02-23 23:42 UTC, criticalAY commented
I get it what was missing here, Thanks David!
[ The icon itself has a width of 12dp. Whole button’s width is 36dp: (12dp + (2 * 12dp) = 36dp).](https://medium.com/@lucasurbas/making-android-toolbar-responsive-2627d4e07129#)

2023-02-23 23:48 UTC, criticalAY commented
I haved added the title in this menu item do we need that here or are we okay without it?

2023-02-24 00:31 UTC, david-allison approved these changes

2023-02-24 00:31 UTC, david-allison commented
> I haven't added the title in this menu item do we need that here or are we okay without it?

Useful, if you have time

2023-02-24 05:48 UTC, criticalAY commented
I added the title and tested but it look like it doesn't work that way with action layouts so we are good to go now

2023-02-24 14:26 UTC, david-allison commented
> I added the title and tested but it look like it doesn't work that way with action layouts so we are good to go now

Drop a TODO for later

2023-02-25 12:52 UTC, mikehardy approved these changes
Nice!

2023-02-25 12:53 UTC, merged