Changed Material Dialog with Alert Dialog for DeckPicker.kt
ankidroid/Anki-Android pull request #13338
Opened 2023-02-23 19:05 UTC by PalashKohli007

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-02-23 19:17 UTC, david-allison requested changes
LGTM, one nitpick

2023-02-23 19:17 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                                .setCancelable(false)
`.cancelable(false)` is available in `main`

2023-02-23 19:19 UTC, david-allison commented
BTW, could you `rebase` rather than opening new PRs for review changes, this causes comments/review history to be lost

2023-02-24 05:52 UTC, criticalAY requested changes

2023-02-24 05:52 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        AlertDialog.Builder(this).show {
This change is not actually worth it as the pending PR will replace this Dialog as we will be having a DialogFragment so I suggest reverting these lines inside `warnNoSyncDuringMigration`

2023-02-24 05:54 UTC, criticalAY commented
@PalashKohli007 for future reference please fill out the PR template properly and make sure you fill out the test section and if possible attach screenshot it making any UI change

2023-02-24 14:28 UTC, david-allison requested changes

2023-02-24 14:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            positiveButton(R.string.dialog_ok)
refactor the library to use `res` instead of `stringRes so there's no changes here

2023-02-24 18:10 UTC, criticalAY approved these changes
Looks good to me, Thanks!

2023-02-24 19:38 UTC, david-allison requested changes
Looks good, only nitpicks

2023-02-24 19:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    .setCancelable(false)
change

2023-02-24 19:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                        .setCancelable(false)
fix indentation

2023-02-24 19:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                                .cancelable(false)
fix indentation

2023-02-27 17:48 UTC, PalashKohli007 commented
@david-allison , resolved comments , please review

2023-02-27 18:06 UTC, david-allison approved these changes
Awesome, thanks!

2023-02-27 18:41 UTC, PalashKohli007 commented
> Awesome, thanks!

welcome David

2023-02-28 13:56 UTC, mikehardy approved these changes
Nice!

2023-02-28 13:56 UTC, merged