add tool: enable/disable scoped storage
ankidroid/Anki-Android pull request #13397
Opened 2023-03-04 03:17 UTC by david-allison

A script to enable/disable scoped storage without the need to uninstall/upgrade from `targetSdkVersion 29`

Makes testing of the disable/enable routine quicker

Issue #5304
Cherry-picked from https://github.com/ankidroid/Anki-Android/pull/13396

2023-03-04 15:52 UTC, Prachi-Jamdade approved these changes

2023-03-04 20:48 UTC, BrayanDSO requested changes

2023-03-04 20:48 UTC, BrayanDSO commented on tools/storage/set_scoped_storage.sh
> +    adb shell pm grant com.ichi2.anki.debug android.permission.READ_EXTERNAL_STORAGE
If you want to, it would be nice to give a proper error message if the developer doesn't have `adb` installed/on their PATH, to avoid the ` adb: command not found` message

2023-03-04 20:48 UTC, BrayanDSO commented on tools/storage/set_scoped_storage.sh
> +    echo "unknown argument: '$1'. Valid values: 'limited', 'full'"
I believe this error message could be improved. When I first ran `tools/storage/set_scoped_storage.sh`, the shown up message was `unknown argument: ''. Valid values: 'limited', 'full'` and I didn't know what to do. 

So it would be nice to explain what `limited` and `full` means and handle the no arguments case too

2023-03-04 22:46 UTC, david-allison commented on tools/storage/set_scoped_storage.sh
> +    adb shell pm grant com.ichi2.anki.debug android.permission.READ_EXTERNAL_STORAGE
I don't think this script is worth gold-plating

2023-03-05 00:03 UTC, BrayanDSO commented on tools/storage/set_scoped_storage.sh
> +    echo "First argument missing. Valid values: 'limited', 'full'"
Could you describe here what "limited" and "full" are supposed to do, respectively?

2023-03-05 00:47 UTC, BrayanDSO approved these changes

2023-03-05 20:16 UTC, merged