stor 05 for migration completion notification and dialog
ankidroid/Anki-Android pull request #13417
Opened 2023-03-07 17:09 UTC by criticalAY

## Purpose / Description
Added notification and alert dialog which will be shown as soon as migration is completed

## Fixes
Fixes #13131

## How Has This Been Tested?
Tested on OnePlus Nord CE
![Screenshot_64](https://user-images.githubusercontent.com/48384865/223496446-1c3ded03-53c2-4b74-bfbc-2114098c8efa.png)

https://user-images.githubusercontent.com/48384865/223496458-aa1776d0-ceb5-44fc-bc52-a90447bd7748.mp4

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-03-09 01:52 UTC, david-allison requested changes
Concept is great, some code cleanup and good to go!

2023-03-09 01:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        dialog.show()
Optional nitpick, but I prefer this syntax - feels cleaner.

Uses `show` and `positiveButton` to reduce complexity

```suggestion
AlertDialog.Builder(this).show {
            setTitle(resources.getString(R.string.migration_successful_message))
            setMessage(resources.getString(R.string.migration_completed))
            positiveButton(R.string.dialog_ok) {
                it.dismiss()
            }
        }
```

2023-03-09 01:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        }
Look into `DialogHandler/showAsyncDialogFragment(fragment, channel)` for how we've handled this in the past and use this mechanism - I've recently done a little cleanup.

There's more to go (probably needs a rewrite), but we should stay consistent with how the Java app used to handle this use case rather than adding multiple ways which will eventually be refactored.

2023-03-09 01:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    private var isMigrated: Boolean = false
This should be removed by `DialogHandler/AsyncDialogFragment`, but if it's not, you need to handle `saveInstanceState`

2023-03-09 01:55 UTC, david-allison requested changes
On re-review, this likely wants to occur in the service. You can't guarantee `onStorageMigrationCompleted` will be called (if `DeckPicker` is not bound to the service)

2023-03-09 11:22 UTC, criticalAY commented
I have made the nits but this will show the notification is the application is closed and a dialog if the app is running, unlike the previous commit where the dialog was shown even if the app was closed and the user returned to the app. But I don't have an issue with this one too so I am good to go but the notification needs to be taken care of as there was a crash that I fixed previously related to the resource file so I think we need to handle it for proper & safer future use I will look into it after this PR

2023-03-09 12:00 UTC, criticalAY commented
I will rebase the branch afterwards

2023-03-09 19:13 UTC, david-allison requested changes
One issue, one slight improvement to the string and a couple of optional nitpicks

2023-03-09 19:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MigrationSuccessDialog.kt
> +class MigrationSuccessDialog : AsyncDialogFragment() {
pass `resources` into the constructor, don't use static strings

2023-03-09 19:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        showAsyncDialogFragment(MigrationSuccessDialog(), Channel.SCOPED_STORAGE_MIGRATION)
I still think this should be performed in the service, `onStorageMigrationCompleted` is for when the migration completes and the DeckPicker is active and may not be called when the migration process completes

2023-03-09 19:13 UTC, david-allison commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="migration_completed">The migration process has been completed successfully.</string>
```suggestion
    <string name="migration_completed">The migration process has completed successfully</string>
```

2023-03-09 19:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MigrationSuccessDialog.kt
> +            }.create()
optional: I'd support adding `.create { }` or extension here

2023-03-09 22:26 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        showAsyncDialogFragment(MigrationSuccessDialog(), Channel.SCOPED_STORAGE_MIGRATION)
How can we do so as the AnkiActivity is a activity and other one is a service class and there would be `  java.lang.ClassCastException` exception

2023-03-09 22:58 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        showAsyncDialogFragment(MigrationSuccessDialog(), Channel.SCOPED_STORAGE_MIGRATION)
And even so can a service show a fragment?

2023-03-13 22:17 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        showAsyncDialogFragment(MigrationSuccessDialog(), Channel.SCOPED_STORAGE_MIGRATION)
The service has already posted a notification hasn't it? It has to post a sticky notification for the migration to work, doesn't it?
So it *seems* based on simple thinking on my part that the service can post a notification (since it did so). So it could - as it clears the migration sticky notification - post a new migration complete notification I think?

2023-03-13 22:25 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        showAsyncDialogFragment(MigrationSuccessDialog(), Channel.SCOPED_STORAGE_MIGRATION)
Notification works differently I guess and Service is a background component that does not have access to the UI thread, so I don't think we can show a DialogFragment from here

2023-03-13 22:25 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        showAsyncDialogFragment(MigrationSuccessDialog(), Channel.SCOPED_STORAGE_MIGRATION)
I already tried that and got the expected `ClassCastException`

2023-03-24 14:23 UTC, mikehardy commented
@criticalAY you just re-requested a review but I don't see any changes pushed despite some comments to address?

2023-03-24 15:25 UTC, criticalAY commented
> @criticalAY you just re-requested a review but I don't see any changes pushed despite some comments to address?

Apologies I thought I pushed it, have pushed the changes now

2023-03-24 16:43 UTC, mikehardy commented
What bad luck - took a conflict from the other PR I just merged, my condolences 😩

2023-03-24 16:49 UTC, criticalAY commented
Not an issue will resolve it

2023-04-01 10:14 UTC, criticalAY commented
@david-allison would like to have your review here

2023-04-01 14:18 UTC, david-allison reviewed
Can you break down the use cases and what happens after this PR:

* App is open (not on Deck Picker)
* App is open (on Deck Picker)
* App is closed, service is running

`DeckPicker.onStorageMigrationCompleted` handles the migration completion in the context of the DeckPicker UI, not in the context of the service/migration.

2023-04-01 15:25 UTC, criticalAY commented
It works fine when we are in DeckPicker activity but in the other two cases, it's a missing case and skips the dialog and the notification. And we can not call the Fragments from a service class not possible as of now. So, any other viable solution you can think of I even tried to use a Broadcast receiver but to no avail

2023-04-01 15:48 UTC, criticalAY commented
Can we consider the first commit as we are sure that the dialog will be shown and if the user is not using the app then the notification is shown for sure

2023-04-01 22:53 UTC, oakkitten requested changes
This has a number of issues.

* The dialog is shown only if the user is in some way looking at the deck picker. Users probably don't do that, the deck picker is pretty boring.
* The user won't see the dialog if the app isn't focused, due to how `showAsyncDialogFragment` works, it shows a notification instead. Even if it showed the dialog unconditionally, the app may get killed at any time in background.

I think the success message is best to not leave to notification only, but show as a dialog unconditionally. If not possible to show the dialog right away, defer it to whenever the user reopens the app, including after it being killed. For instance, like this:

* The progress listener in the service (the one that updates the notification) on successful completion (**also on an error**—are we handling errors?) tries to show the dialog in the current foreground activity. Not sure what's the best way to fetch the current activity but here's [what looks like a way](https://stackoverflow.com/a/40833623) (might be better to register the callback in the service itself on start command). Then, 
  * if there's a foreground activity (started), show the dialog in it, or
  * if not, store flag in shared preferences that the dialog must be shown. On starting any activity, or perhaps only when starting reviewer or deck picker, the flag is checked, and if set, the dialog is shown and the flag is reset.

I also suggest duplicating in the dialog the information about the fact that the collection is now removed along with the app by default, and the the user should take care to backup/sync/whatever.

2023-04-01 22:53 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MigrationSuccessDialog.kt
> +) : AsyncDialogFragment() {
This will crash. Fragments must have a zero-argument constructor.

Also it kind of doesn't make much sense passing arguments into a very much concrete dialog class. Perhaps use `SimpleMessageDialog`, or don't implement `AsyncDialogFragment`?

2023-04-01 22:53 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        showAsyncDialogFragment(MigrationSuccessDialog(resources.getString(R.string.migration_completed), resources.getString(R.string.migration_successful_message)), Channel.SCOPED_STORAGE_MIGRATION
Note that the method `onStorageMigrationCompleted()` was removed in #13368.

Also note that the service in #13368 is keeping the notification after it's done and that notification includes a success message already.

2023-04-01 22:53 UTC, oakkitten commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="migration_completed">The migration process has completed successfully</string>
This is about the same as `migration_successful_message` so it needs a comment I guess.

2023-04-01 22:56 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MigrationSuccessDialog.kt
> +) : AsyncDialogFragment() {
Also, I suggest suffixing all fragments with `Fragment` and all dialog fragments with `DialogFragment`

2023-04-02 16:14 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        showAsyncDialogFragment(MigrationSuccessDialog(resources.getString(R.string.migration_completed), resources.getString(R.string.migration_successful_message)), Channel.SCOPED_STORAGE_MIGRATION
So the notification is not needed nice

2023-04-02 16:17 UTC, criticalAY commented
@oakkitten Thankyou! for pointing out `activityLifecycleCallbacks`  I completely forgot about this one I remember I came across this stack over flow post when I was working on the migration progress Dialog PR but here I was too focused on the Service class so Thankyou!!!!

2023-04-02 16:18 UTC, criticalAY commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="migration_completed">The migration process has completed successfully</string>
If there exist a string I will remove it afterwards like whenever your PR would get merged

2023-04-06 16:51 UTC, criticalAY commented
I have used shared pref to save the flag

2023-04-11 02:17 UTC, david-allison approved these changes
This works. Thanks! 

Given the complexity, I'd have preferred a toast, no changes required.

2023-04-11 11:45 UTC, oakkitten commented
Can this be postponed until #13368 is merged? I'd like to make a few changes here

2023-04-11 18:01 UTC, criticalAY commented
you want the changes in this PR or #13368 ?

2023-04-11 19:13 UTC, oakkitten commented
In this PR. When/if #13368 is merged, this will need to have some changes in order to work with that—doing it the other way around is more work. I also want to try one other thing here, and maybe refactor a bit. If you don't mind, I can make another PR on top of this one ❤

2023-04-19 17:16 UTC, david-allison reviewed
one nit, my approval from last week still stands

2023-04-19 17:16 UTC, david-allison commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="migration_successful">The migration process has been completed successfully.</string>
```suggestion
    <string name="migration_successful">The storage migration process has been completed successfully.</string>
```

2023-04-19 17:18 UTC, criticalAY commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="migration_successful">The migration process has been completed successfully.</string>
ok

2023-04-19 19:54 UTC, oakkitten commented
I would still like to make a few changes if this can wait until the weekend. Also I suggest that the warning about the dangers of the new collection location is reiterated in the final dialog as well

2023-04-19 20:01 UTC, criticalAY commented
> I would still like to make a few changes if this can wait until the weekend. Also I suggest that the warning about the dangers of the new collection location is reiterated in the final dialog as well

I won't mind but could you state the changes you wish to make?

2023-04-19 20:19 UTC, oakkitten commented
Mostly the ones I already mentioned plus a few naming changes (you know how I am about names) *and* this seems to be the right PR to also throw in at least some error handling

2023-04-21 20:14 UTC, mikehardy commented
Strings were just cleared out, I think this is the only one that's wanted for storage migration that has strings, I hate to ask for ETAs but time is very short now - @oakkitten do you have an idea when you'll have time to do whatever it is that is causing  you to ask for a hold here?

2023-04-23 14:41 UTC, closed without merging