fix: Rename performPermissionRequest
ankidroid/Anki-Android pull request #13423
Opened 2023-03-08 18:35 UTC by pratyaksh1610

## Pull Request template

## Purpose / Description
Rename `performPermissionRequest` .

## Fixes
Fixes #13413 

## Approach
Rename the method name.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-03-13 23:17 UTC, mikehardy approved these changes
Seems almost....too easy

2023-03-15 05:29 UTC, lukstbit requested changes

2023-03-15 05:29 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +    private fun onRequestMultimediaPermissionsResult(field: IField): Boolean {
I don't think this is the name to use as `onWordWord...` type of method names are usually associated with callbacks, which this method isn't. I think a better name would be `hasPerformedPermissionRequestForField`.

2023-03-15 07:58 UTC, pratyaksh1610 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +    private fun onRequestMultimediaPermissionsResult(field: IField): Boolean {
Done

2023-03-15 09:56 UTC, lukstbit approved these changes
Great, thanks!

2023-03-15 09:57 UTC, merged