Toolbar is showing during review using FullScreen Mode/Hide the system bars
ankidroid/Anki-Android pull request #13448
Opened 2023-03-17 18:22 UTC by SanjaySargam

## Pull Request template

## Purpose / Description
Toolbar is not showing during review using FullScreen Mode/Hide the system bars when  System UI visibility changes

## Fixes
Fixes #13375

## Approach
Added condition for FullScreenMode.BUTTONS_ONLY

## How Has This Been Tested?

Tested on Emulator

https://user-images.githubusercontent.com/65113071/225987013-349d0632-5cdd-4be6-98a5-c5161ad22b9a.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-03-20 21:33 UTC, BrayanDSO requested changes
The top and answer bars are misplaced

2023-03-21 05:54 UTC, SanjaySargam commented
> The top and answer bars are misplaced
> 
> SDK 33 emulator
> ![image](https://user-images.githubusercontent.com/69634269/226470800-78626162-5465-4ac3-83fc-8b184e951f4b.png)
> 

@BrayanDSO I will look into this

2023-03-21 14:45 UTC, SanjaySargam commented
@BrayanDSO I think the answer bar is in the right place as there is a space for nav bar below answer bar
And top bar needs to be in the place of status bar

2023-03-22 09:56 UTC, BrayanDSO commented
Those blank spaces aren't necessary in order to make the nav/status bar reappear

2023-03-22 09:59 UTC, SanjaySargam commented
> Those blank spaces aren't necessary in order to make the nav/status bar reappear

Ok

2023-03-23 10:33 UTC, SanjaySargam commented
> Those blank spaces aren't necessary in order to make the nav/status bar reappear

I agree for answer bar buttons as there is blank space
But the top bar is in the right place, just below the status bar

2023-03-24 21:56 UTC, BrayanDSO commented
The current result isn't better than what we currently have and doesn't solve the issue

2023-03-25 04:25 UTC, SanjaySargam commented
@BrayanDSO 
What are the things that I have to modify
Please let me know

2023-03-25 08:03 UTC, BrayanDSO commented
In terms of code, I'm not sure on what exactly needs to be done, which means that this needs investigation. In terms of functionality, it should fix the issue that this PR is linked to

2023-03-26 14:00 UTC, doozan commented
>  What are the things that I have to modify Please let me know

Since this bug was introduced sometime between alpha92 and alpha93, you might be able to use ```git bisect``` to find the commit that introduced the problem and use that as a starting point for fixing it.

2023-03-26 21:20 UTC, BrayanDSO commented
To me this start happening after I upgraded to Android 13

2023-04-16 21:36 UTC, closed without merging