Replaced materialDialogue with AlertDialogue
ankidroid/Anki-Android pull request #13449
Opened 2023-03-17 19:41 UTC by SumitSingh2003

## Pull Request template

## Purpose / Description
Replaced materialDialogue with AlertDialogue

## Fixes
Fixes #13315

## How Has This Been Tested?
Tested on Realme 6

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-03-17 19:51 UTC, criticalAY commented
Thanks for the contribution and your efforts but the test fails

2023-03-17 19:53 UTC, SanjaySargam commented
@SumitSingh2003 Thanks for Contribution
It's Dialog not Dialogue. Kindly rename it.

2023-03-17 19:58 UTC, criticalAY commented
@SanjaySargam Its `dialog` only in Android Studio

2023-03-17 20:56 UTC, criticalAY reviewed
Please attach a screenshot of the UI changes

2023-03-17 23:01 UTC, criticalAY approved these changes
seems fine to me otherwise thanks!

2023-03-19 07:21 UTC, lukstbit requested changes

2023-03-19 07:21 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +        AlertDialog.Builder(context).setTitle(R.string.vague_error).setMessage(msg)
Thank you for contributing. The code is close but we need some changes:
- in the AlertDialogFacade file you'll find some extension methods that should be used instead of the setters methods that you used, the changes should consist mostly of adding some imports
- the code should replicate the original code as much as possible, so use the setOnDismissListener() method instead of moving code to the positive button listener

2023-03-20 07:33 UTC, lukstbit commented
You're moving further from what we want. The code should be something like:

```
AlertDialog.Builder(someContext).show{
      title() => this would come from AlertDialogFacade
      positiveButton()
      .setOnDismissListener()
}
```

2023-03-24 15:28 UTC, lukstbit commented
This PR was superseded by #13481 
Thank you for trying to contribute.

2023-03-24 15:28 UTC, closed without merging