Keyboard is showing in onResume state of Reviewer.kt
ankidroid/Anki-Android pull request #13451
Opened 2023-03-18 07:22 UTC by SanjaySargam

## Pull Request template

## Purpose / Description

## Fixes
Fixes #13450

## Approach

This can be achieved by adding answerField!!.focusWithKeyboard() in onResume()

## How Has This Been Tested?

Tested on Emulator

https://user-images.githubusercontent.com/65113071/226091366-19107112-12fa-419c-9760-8833937aba62.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-03-18 08:10 UTC, pratyaksh1610 reviewed
Tests fails.

2023-03-18 09:31 UTC, SanjaySargam commented
> Tests are failing .

Now all tests passed.

2023-03-19 07:28 UTC, pratyaksh1610 approved these changes

2023-03-19 08:39 UTC, ShridharGoel requested changes

2023-03-19 08:39 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +import android.os.*
Unnecessary change

2023-05-23 04:05 UTC, SanjaySargam commented
Hey @ShridharGoel Can you review it

2023-06-07 06:17 UTC, SanjaySargam commented
Can any of the maintainers will look into this ? It's been a long time

2023-06-07 09:25 UTC, ShridharGoel approved these changes

2023-06-22 15:16 UTC, merged