Changed Material Dialog with Alert Dialog for Toolbar.kt
ankidroid/Anki-Android pull request #13467
Opened 2023-03-21 08:29 UTC by Prince-kushwaha

## Purpose / Description
Replaces usages of MaterialDialog with AlertDialog in Toolbar.kt
## Fixes
Related to #13315 

## How Has This Been Tested?
Open each one of the changed dialogs on their respective preferences

2023-03-23 13:52 UTC, mikehardy approved these changes
LGTM - thanks!

2023-03-23 16:44 UTC, lukstbit requested changes
Please provide screenshots for PRs which contain UI changes(this includes dialogs changes).

2023-03-23 16:44 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
> +        var headingList = arrayOf("h1", "h2", "h3", "h4", "h5")
`val` instead of `var`, this is also a warning in the IDE.

2023-03-23 16:44 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
> +            title(R.string.menu_font_size)
Why was this changed?

2023-03-23 16:44 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
> +                var charSequence = headingList[index]
val instead of var, this is also a warning in the IDE.

2023-03-23 17:05 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
> +            title(R.string.menu_font_size)
taken by mistake

2023-03-23 17:39 UTC, Prince-kushwaha commented
Insert Heading Dialog Image 
![heading](https://user-images.githubusercontent.com/65972015/227293149-17122ff3-a4d2-4e03-8b4d-52017986249e.jpeg)

2023-03-23 17:40 UTC, Prince-kushwaha commented
display FontSize Dialog
![forntsize](https://user-images.githubusercontent.com/65972015/227293639-fca9f367-dcac-405a-8bba-783b78cdb14c.jpeg)

2023-03-24 09:56 UTC, lukstbit approved these changes
Looks great, thanks!

2023-03-24 09:57 UTC, merged