Showing Warning on Reset to Default button in App bar buttons
ankidroid/Anki-Android pull request #13476
Opened 2023-03-22 09:34 UTC by SanjaySargam

## Pull Request template

## Purpose / Description

## Fixes
Fixes #13174 

## Screen Recording

https://user-images.githubusercontent.com/65113071/226860911-d9c6ea3e-648f-48a5-9725-297a102e5d65.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-03-22 09:57 UTC, BrayanDSO commented
lint

2023-03-22 11:33 UTC, SanjaySargam commented
> lint

Now all tests passed

2023-03-22 23:28 UTC, BrayanDSO requested changes

2023-03-22 23:28 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomButtonsSettingsFragment.kt
> +                    .negativeButton(R.string.dialog_cancel, null)
```suggestion
                message(R.string.reset_confirmation_text)
                positiveButton(R.string.reset) {
                    // Reset the settings to default
                    AnkiDroidApp.getSharedPrefs(requireContext()).edit {
                        remove("customButtonUndo")
                        remove("customButtonScheduleCard")
                        remove("customButtonEditCard")
                        remove("customButtonTags")
                        remove("customButtonAddCard")
                        remove("customButtonReplay")
                        remove("customButtonCardInfo")
                        remove("customButtonSelectTts")
                        remove("customButtonDeckOptions")
                        remove("customButtonMarkCard")
                        remove("customButtonToggleMicToolBar")
                        remove("customButtonBury")
                        remove("customButtonSuspend")
                        remove("customButtonFlag")
                        remove("customButtonDelete")
                        remove("customButtonEnableWhiteboard")
                        remove("customButtonSaveWhiteboard")
                        remove("customButtonWhiteboardPenColor")
                        remove("customButtonClearWhiteboard")
                        remove("customButtonShowHideWhiteboard")
                    }
                    // #9263: refresh the screen to display the changes
                    refreshScreen()
                }
                negativeButton(R.string.dialog_cancel, null)
```

2023-03-22 23:28 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="reset_settings_to_default">Reset Settings to Default</string>
Phrase casing
```suggestion
    <string name="reset_settings_to_default">Reset settings to default</string>
```

2023-03-22 23:28 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="reset_confirmation_text" maxLength="41">Are you sure you want to reset your settings to default?</string>
*Particularly*, I'd prefer to remove this message, as the dialog title is pretty clear already

2023-03-23 06:33 UTC, SanjaySargam commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="reset_confirmation_text" maxLength="41">Are you sure you want to reset your settings to default?</string>
Ok

2023-03-24 09:10 UTC, BrayanDSO approved these changes

2023-03-24 14:04 UTC, mikehardy commented
I'm okay with the status of strings right now based on crowdin activity stream. 1 Japanese change + 11 German changes which I can review in crowdin API, so, merging this one

2023-03-24 14:05 UTC, merged