Used AlertDialog instead of MaterialDialog in NoteEditor.kt
ankidroid/Anki-Android pull request #13473
Opened 2023-03-21 20:19 UTC by SanjaySargam

## Pull Request template

## Purpose / Description

## Fixes
Related #13315 

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-03-22 10:00 UTC, BrayanDSO commented
Do you have a screenshot?

and as a note, please don't delete the `How Has This Been Tested?` section and try filling it.

2023-03-22 10:03 UTC, SanjaySargam commented
> and please don't delete the `How Has This Been Tested?` section and try filling it.

Ok Will take care next time

2023-03-22 10:25 UTC, SanjaySargam commented
> Do you have a screenshot?


@BrayanDSO 

![WhatsApp Image 2023-03-22 at 3 54 18](https://user-images.githubusercontent.com/65113071/226874733-cb781990-55f9-475b-a53f-48b26a5e3a51.jpeg)
![WhatsApp Image 2023-03-22 at 3 54 18 PM](https://user-images.githubusercontent.com/65113071/226874746-f39415d6-364f-42c9-bb7b-1686fdd6dbae.jpeg)

2023-03-23 14:47 UTC, mikehardy approved these changes
LGTM

2023-03-23 14:47 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> -import android.text.TextUtils.isEmpty
interesting - this is unrelated, but at the same time it appears to be unused if this is still compiling correctly, so it is a valid change.

Should be in a separate lint-labeled commit for 💯 % credit tho ;-)

2023-03-24 09:17 UTC, lukstbit requested changes
The changes introduces in this PR completely break the functionality of the changed dialogs. I would recommend to start with the change I mention below and from there make the proper changes so the intent of the original code is maintained.

Note that there should also be some padding added in the layout used as a custom view because the original UI isn't reproduced without it.

2023-03-24 09:17 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        editToolbarItemDialog: AlertDialog.Builder
The type of `editToolbarItemDialog` should be `AlertDialog` so below you can call `dismiss()` on it. The change between `dismiss()` and `cancelable(true)` doesn't make any sense and it doesn't reproduce the original code's  intent.

2023-03-24 13:51 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        editToolbarItemDialog: AlertDialog.Builder
If I initialised `editToolbarItemDialog` as a `AlertDialog` then its affecting the other dialog and give error

2023-03-24 14:08 UTC, mikehardy requested changes
Does not match behavior of previous code

2023-03-24 15:17 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        editToolbarItemDialog: AlertDialog.Builder
> If I initialised `editToolbarItemDialog` as a `AlertDialog` then its affecting the other dialog and giving error

Yes, there will be errors, as this isn't going to be a simple change method names/ imports and be done. The type there needs to be AlertDialog so you can dismiss it. It shouldn't be very difficult to do.

2023-03-30 12:35 UTC, SanjaySargam commented
> There are still conflicts...

Can you plz elaborate  the conflicts which are there

2023-03-30 13:13 UTC, lukstbit commented
There's a conflict in the imports of NoteEditor. If you look at the bottom of this discussion the Github UI tells you that there's a conflict.

2023-03-31 00:26 UTC, SanjaySargam commented
> There's a conflict in the imports of NoteEditor. If you look at the bottom of this discussion the Github UI tells you that there's a conflict.

How these conflicts can be resolved

2023-03-31 04:50 UTC, lukstbit commented
I fixed the conflict, you can see the commit for more information. To avoid these conflicts in the future you could follow these steps before pushing:
- update the main branch with the latest changes from this repository(this is particularly important when the PR is older then a few days(the longer a PR stays open the greater chances of a conflict due to code that was merged))
- rebase your PR on top of main, these would allow you to see and fix any possible conflicts
- as an extra step, if the amount of changes is small(like in this PR) you could squash them into a single commit
- push the code to the PR branch.

2023-03-31 04:51 UTC, SanjaySargam commented
> I fixed the conflict, you can see the commit for more information. To avoid these conflicts in the future you could follow these steps before pushing:
> - update the main branch with the latest changes from this repository(this is particularly important when the PR is older then a few days(the longer a PR stays open the greater chances of a conflict due to code that was merged))
> - rebase your PR on top of main, these would allow you to see and fix any possible conflicts
> - as an extra step, if the amount of changes is small(like in this PR) you could squash them into a single commit
> - push the code to the PR branch.
> 

Ok Got it. Thanks ♥️

2023-04-01 11:31 UTC, lukstbit requested changes
Almost there...

2023-04-01 11:31 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        val view = ScrollView(this)
This ScrollView needs to be added in the layout R.layout.note_editor_toolbar_add_custom_item wrapping the top LinearLayout. Add a standard padding to it of 16dp in all directions.

2023-04-01 11:31 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        val v = ScrollView(this)
As above this ScrollView needs to be added in the layout R.layout.note_editor_toolbar_edit_custom_item wrapping the top LinearLayout. Add a standard padding to it of 16dp in all directions.

2023-04-02 06:53 UTC, lukstbit approved these changes
Great!

2023-04-06 20:15 UTC, mikehardy approved these changes
Now it is looking good, thank you! Thanks also for sure to @lukstbit - big kudos for helping work this PR through

2023-04-06 20:15 UTC, merged