NF: Whiteboard - Stylus Only Mode
ankidroid/Anki-Android pull request #13475
Opened 2023-03-22 08:20 UTC by naong

## Pull Request template

## Purpose / Description
Related to #13090. Adds new feature for stylus mode to whiteboard.

This function allows you to write with only the stylus pen when using a stylus pen such as the S-Pen. Finger gestures use scroll and button controls only.

This function have a toggle action button and a menu.

![action button](https://user-images.githubusercontent.com/7389524/226837204-6aeaaaae-5d4c-48ed-9f7a-7653f56eb681.png)
![stylus menu](https://user-images.githubusercontent.com/7389524/226837222-aa33b5f7-330b-4397-ab85-e3f6a13792b1.png)

## Fixes
none

## Approach
In the MotionEvent, check the tool type.

## How Has This Been Tested?
Tested in emulator and Samsung Galaxy Tab S7+(SM-T970).

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-03-22 10:44 UTC, naong commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +    private var mToggleStylus = false
> I've tested this on my S-Pen and it works pretty well. Had this on my TODO list for a while, so it's nice to have someone else implementing it, so thanks!
> 
> As you've probably read the API, do you know if there is a way to toggle this mode automatically if a stylus is connected? (for another issue)

I didn't think about automatically recognizing the connection of the stylus. Because I didn't think everyone would want this feature.



> I know that the adjacent code uses hungarian notation, but this is because this file were on Java previously. Although we haven't migrated removed the notation from all of the code, we are trying to keep the new code without it.

I understand.

2023-03-22 10:45 UTC, naong commented on AnkiDroid/src/main/res/values-ja/02-strings.xml
> +    <string name="disable_stylus">スタイラスモードオフ</string>
ok

2023-03-22 10:45 UTC, naong commented on AnkiDroid/src/main/res/values-ko/02-strings.xml
> +    <string name="disable_stylus">스타일러스 비활성화</string>
yup

2023-03-22 10:47 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +    private var mToggleStylus = false
> I didn't think about automatically recognizing the connection of the stylus. Because I didn't think everyone would want this feature.

At least on Samsung notes and Xodo (a PDF editor), this is the default behavior when I take off the S-pen from my phone

2023-03-22 10:52 UTC, naong commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="disable_stylus">Disable Stylus Mode</string>
It's something I've been thinking about too, but I think 'Block finger writing' or 'Stylus writing only' would be more correct.

Other apps that support a stylus usually don't differentiate between both inputs, like current Anki, or don't draw with finger input.

2023-03-22 11:38 UTC, naong commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +    private var mToggleStylus = false
> At least on Samsung notes and Xodo (a PDF editor), this is the default behavior when I take off the S-pen from my phone

As you may know, I think you need the S-pen SDK to check the connection status of the S-pen.

https://developer.samsung.com/codelab/s-pen-remote/s-pen-remote-sdk.html#Initialize-SPenRemote-in-onResume()-of-activity

2023-03-22 20:42 UTC, naong commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +    private var mToggleStylus = false
It is possible to make 'Stylus Mode' enable automatically by detecting use of stylus. But the reverse is difficult because we never know when the stylus has been disabled.

2023-03-22 23:17 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="disable_stylus">Disable Stylus Mode</string>
I won't block the PR on this because I'm not strong about anything, so I'll go with the implementer's choice. Although I'd prefer if it were on phrase casing (i.e. `Enable stylus mode`)

2023-03-22 23:18 UTC, BrayanDSO approved these changes

2023-03-23 05:52 UTC, naong commented
I noticed the missing state memory feature. I will request a review again after adding this feature.

2023-03-23 11:25 UTC, naong commented
I implemented it to remember the stylus mode state. This implementation includes modifying the database and changing `DATABASE_VERSION` from 6 to 7.

2023-03-23 14:59 UTC, mikehardy approved these changes
Cool feature! Code looks good - I re-requested @BrayanDSO per your comments below where you modify metadb

2023-03-24 22:12 UTC, BrayanDSO requested changes
only trivial things to solve. Worked well on my tests

2023-03-24 22:12 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
> +    private var toogleStylus = false
misspelled
```suggestion
    private var toggleStylus = false
```

2023-03-24 22:12 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.kt
> +     * @param whiteboardStylusState 1 if the whiteboard stylus mode should be enabled, 0 otherwise
>      * @param whiteboardStylusState 1 if the whiteboard stylus mode should be enabled, 0 otherwise

the dev gives a boolean here, not 0 and 1, so the text should be changed a little to reflect that 0 and 1 are the way to store the status on the database, depending if whiteboardStylusState is true or false

2023-03-25 01:21 UTC, naong commented on AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.kt
> +     * @param whiteboardStylusState 1 if the whiteboard stylus mode should be enabled, 0 otherwise
Thank you for your review. I have applied your request.

2023-03-25 01:58 UTC, naong reviewed
Thank you for your review. I have applied your request.

2023-03-26 21:19 UTC, BrayanDSO approved these changes
LGTM. Thanks a lot!

2023-03-27 22:47 UTC, david-allison approved these changes

2023-03-27 22:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
> +
optional: this could have been:

```kotlin
var toggleStylus = false
    private set
```

2023-03-27 22:49 UTC, merged

2023-08-08 21:05 UTC, david-allison commented
@naong 

You're getting a lot of love from reddit for this one: https://www.reddit.com/r/Anki/comments/15l9dxy/thank_you_ankidroid_devs_just_want_to_say_thank/

💜💜