Showing Snackbar instead of Toast in Reviewer.kt
ankidroid/Anki-Android pull request #13488
Opened 2023-03-23 18:16 UTC by SanjaySargam

## Pull Request template

## Purpose / Description
Used Snackbar instead of Toast

## Fixes
Related #13411

## How Has This Been Tested?
Tested on Emulator

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-03-24 22:14 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +            this.showSnackbar(
ditto

2023-03-24 22:14 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                        this.showSnackbar(getString(R.string.white_board_image_save_failed, e.localizedMessage))
ditto

2023-03-24 22:15 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                resources.getQuantityString(toastResourceId, cardCount, cardCount)
previously the toast time was short and the snackbar is long

2023-03-24 22:15 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                        this.showSnackbar(getString(R.string.white_board_image_save_failed, e.localizedMessage))
ditto 2 (snackbar time)

2023-03-25 08:00 UTC, BrayanDSO approved these changes

2023-03-26 06:48 UTC, lukstbit requested changes

2023-03-26 06:48 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +            showSnackbar(getString(R.string.multimedia_editor_something_wrong))
This also requires `Snackbar.LENGTH_SHORT`.

2023-03-30 04:01 UTC, lukstbit approved these changes

2023-03-30 04:29 UTC, merged