fix: Disable search preview when there are no cards
ankidroid/Anki-Android pull request #13492
Opened 2023-03-24 06:48 UTC by pratyaksh1610

## Purpose / Description
Disable search preview when there are no cards .

## Fixes
Fixes #13489 

## Approach
Modify visibility of `mSearchItem`

## How Has This Been Tested?

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-03-27 19:33 UTC, BrayanDSO requested changes
The user should still be able to search if there are cards on the collection. this hides the button if there isn't any cards on the current query

2023-03-30 07:12 UTC, pratyaksh1610 commented
@BrayanDSO Can you please share a mockup being referred to ? . I think the user is able to search if there is a card on the collection. Thanks.

2023-04-15 06:37 UTC, pratyaksh1610 commented
@BrayanDSO Waiting for the reply here.

2023-04-15 17:25 UTC, BrayanDSO commented
Sorry. Will take a look later

2023-06-22 15:17 UTC, mikehardy commented
@BrayanDSO no pressure but I believe this is pending your reply

2023-08-29 10:23 UTC, pratyaksh1610 commented
@BrayanDSO Needs review.

2023-09-02 16:58 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        mSearchItem?.isVisible = cardCount != 0
I believe that this shouldn't be in this method, given its name

2023-09-21 04:35 UTC, closed without merging