Fix some activityResult deprecations
ankidroid/Anki-Android pull request #13495
Opened 2023-03-24 21:49 UTC by RobozinhoD

## Fixes
part of #8602

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

used the debugger to see if the deck options launcher worked. I didn't test the previewer fix because I think that it isn't necessary

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-03-24 22:10 UTC, BrayanDSO requested changes

2023-03-24 22:10 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                deckOptionsLauncher.launch(i)
this removes the `FADE` animation, but as the app doesn't have consistent animations anyway (a problem that should be solved later), I think it's fine

2023-03-24 22:10 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +            performReload()
testing this a little, noticed that this isn't reached before or after the change, which means there was a bug. Should be easy to solve though.

2023-03-27 17:40 UTC, RobozinhoD commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +            performReload()
done

2023-03-27 19:14 UTC, BrayanDSO approved these changes

2023-03-27 22:23 UTC, merged