Use "full" flavor on parallel builds
ankidroid/Anki-Android pull request #13514
Opened 2023-03-27 18:48 UTC by BrayanDSO

## Fixes
#13431

## Approach
Change the assemble type on the script

## How Has This Been Tested?

Runned `./gradlew assembleFullRelease` to check if the command was okay. Didn't run the script because of the credentials.

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-03-27 20:54 UTC, david-allison commented
This means the regular APK and the arch specific APKs are using `play`, but the parallel alphas are using `full`.

We should have a quick discussion on whether this is the right move as we'll need to (slightly) change documentation

2023-03-27 21:55 UTC, mikehardy commented
I believe all APKs should use full *except* the ones we upload to play store. I do not want to throw a bunch of flavors up on github releases (they're pretty chunky, feels like abuse of storage service to me...) so that implies we pick one, and "full" is the one you'd want to pick. No reason to restrict a manually installed APK in any way, IMHO

2023-03-27 21:57 UTC, BrayanDSO commented
So, `release.sh` should be changed to make a "full" and a "play" non-parallel build and upload the "full" one to GitHub. Probably for another PR

2023-03-27 22:07 UTC, mikehardy commented
I was planning on digging in to this in a little bit but you're already in here and this change looks good :-), I think it should just go in here in another commit

Change `play` here to `full` https://github.com/ankidroid/Anki-Android/blob/7ab289a0ee3ed114570cf1554b89c2cb3ca2e903/tools/release.sh#L142

Change this:
https://github.com/ankidroid/Anki-Android/blob/7ab289a0ee3ed114570cf1554b89c2cb3ca2e903/tools/release.sh#L130-L133

to "now generate the full flavor builds for all the architectures and universal" as a comment, alter `play` to full in the gradle target and.....that should be it?

2023-03-27 22:07 UTC, mikehardy commented
(if it was more complicated I'd say yeah another PR but this should be that easy 🤞 )

2023-03-27 22:19 UTC, david-allison requested changes
One issue, rest LGTM

2023-03-27 22:19 UTC, david-allison commented on tools/parallel-package-release.sh
> +    if ! ./gradlew assembleFullRelease -PcustomSuffix="$LCBUILD" -PcustomName="AnkiDroid.$BUILD" -Duniversal-apk=true
Line 41 needs changing to `cp AnkiDroid/build/outputs/apk/full/release/AnkiDroid-full-universal-release.apk ./AnkiDroid-$TAG.parallel.$BUILD.apk
done`

2023-03-27 22:23 UTC, david-allison approved these changes

2023-03-27 22:39 UTC, mikehardy approved these changes
Looks right to me, will squash. Thanks @BrayanDSO ! Knocked a thing off my todo list so helps me personally not just project, not that anyone else should care but I do haha :-)

2023-03-27 22:40 UTC, merged

2023-03-29 00:52 UTC, Arthur-Milchior commented
Thanks @BrayanDSO.

> I believe all APKs should use full _except_ ...

I'm not entirely certain. In the sense that, if we want to ask users to alpha tests the migration, they should be able to download it from github (at least, if I understand correctly that we want to test with github alpha testers first, before testing with play store ones)

2023-03-29 11:37 UTC, mikehardy commented
May be that we want a specific "play" build on the releases page as well for testing?
I believe "full" should be the default for all non-play store locations (read as: github releases page) but you have a point @Arthur-Milchior about testing play release from the releases page. Could do a single universal play variant there. In fact, could do a universal version of each non-full variant on the releases page, for testing (read as: play + amazon universal builds)

If you like that idea, peel this to an issue and assign me, I can get it