Replace MaterialDialog with AlertDialog
ankidroid/Anki-Android pull request #13525
Opened 2023-03-30 19:43 UTC by gajwani

## Purpose / Description
Based on https://github.com/ankidroid/Anki-Android/issues/13315, we would like to replace all instances of `MaterialDialog` with `AlertDialog`.

I started with `CardTemplateEditor` and realize that that would mean changing `DiscardChangesDialog` which was also used in 2 other locations (`NoteEditor` and `CardTemplateBrowserAppearanceEditor`). I made the change in all 3 locations, along with some Robolectric tests (`CardTemplateEditorTest`) that required some changes in how we access underlying Robolectric `ShadowDialog`s.

Apologies that this PR became a bit involved, but hopefully should read fairly straightforwardly.

## Fixes
Fixes https://github.com/ankidroid/Anki-Android/issues/13315

## Approach
I started with a simple replace, and then modified and cleaned up things as I went along. There was a situation where a method that was marked as `@VisibleForTesting` was not actually being tested, so I removed that, and in the case of `DiscardChangesDialog` I removed the return value for `showDialog` which wasn't being used anywhere. I also made `context` a non-nullable parameter to the `showDialog` function, as it was always called with a valid `this` as a context.

## How Has This Been Tested?
So far, this has been tested in the simulator, with unit tests. I am currently working on getting it tested on my real device (I am new to Android development, I am mostly a backend Kotlin developer).

## Learning (optional, can help others)
We have a lot of code that can be written a more idiomatically in Kotlin, this presents a good way to start getting familiar with the codebase.

Note that I found this blogpost useful:
https://bterczynski.medium.com/testing-dialogs-in-robolectric-b7118f965ff3, as it described why the `performClick` call in the Robolectric tests was not having any impact.

Note: I will add screenshots as I finish up testing.  I wanted to get this PR up for review while I do that.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-03-30 19:45 UTC, gajwani commented
@BrayanDSO apologies that I didn't tag you as a reviewer before completing the PR description, I also cannot modify that field after the fact. Can you take a look at this when you get a chance?

2023-03-30 19:46 UTC, gajwani commented
Also, should I remove the `Fixes` part? I realize now that it might try to close that issue (#13315) if this merges.

2023-03-30 19:50 UTC, gajwani commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> -        discardDialog.show()
The `show` was not required here, as `showDialog` already calls it here https://github.com/ankidroid/Anki-Android/pull/13525/files#diff-37061358ffaa73b5b369f81a83e7936cf78114b3d0943b0e4f8c0d9fa5a1a68cR31. The return value was also not used anywhere.

2023-03-30 19:51 UTC, gajwani commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DiscardChangesDialog.kt
> +        ) = AlertDialog.Builder(context).show {
Although this is technically returning the `AlertDialog.Builder`, that is not consumed anywhere.

2023-04-01 11:02 UTC, lukstbit requested changes
Thank you for contributing!
Changes look good, left some minor issues to improve and then this could be merged.

2023-04-07 09:38 UTC, lukstbit approved these changes
LGTM, thanks!

2023-04-08 11:54 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +    private fun showDiscardChangesDialog() = DiscardChangesDialog.showDialog(this) {
To simplify things, I suggest removing `DiscardChangesDialog.kt` and putting whatever little code it has directly in this method

2023-04-08 11:54 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DiscardChangesDialog.kt
> +            negativeButton(R.string.dialog_cancel)
Suggest using safer and more standard `AlertDialog.Builder` methods such as `setMessage`, `setPositiveButton`, etc.

...can we deprecate `message()` & friends?

2023-04-11 03:33 UTC, david-allison approved these changes

2023-04-11 11:30 UTC, lukstbit commented
Looks good as it is now, further work can be done later if needed. Thank you!

2023-04-11 11:31 UTC, merged

2023-04-13 19:00 UTC, gajwani commented
@lukstbit and @david-allison and @oakkitten thanks for the reviews and apologies for being a bit MIA on this. I'll create follow up PRs for any additional work.

2023-04-14 04:06 UTC, lukstbit commented
@gajwani No problems and at the moment there's no need for any additional work related to this PR.