Added permission for API 33+
ankidroid/Anki-Android pull request #13535
Opened 2023-04-01 21:32 UTC by lonewolf2208

## Pull Request template

## Purpose / Description
At an unknown API level, "Allow management of all files" is no longer available in the app permissions screen.

## Fixes
Fixed #13520

## Approach
Added a dialog box signifying the need of storage permission

Note - I couldn't find a prior string that was relevant, so I had to build a new one for the dialogue box's message.

![image](https://user-images.githubusercontent.com/72886809/229314587-7cb78eb3-e3cd-41ad-8e64-e9a9dcfdc4d1.png)

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-04-06 20:32 UTC, mikehardy requested changes
Thanks for taking a crack at this, much appreciated! I spotted a few things and left comments next to them

2023-04-06 20:32 UTC, mikehardy commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="storage_access_permission">Ankidroid requires storage access permission to function properly. This permission allows the app to access and modify files on your device, which is nece
🤔 I thought we already had a string somewhere that explained we need storage access?

2023-04-06 20:32 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +//            // note: this may not be defined on some Phones. In which case we still have a toast
This indentation change is unwanted - it appears the previous indentation was fine and the new indentation has a newline unexpectedly, and is not indented properly

2023-04-06 20:32 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +            MaterialDialog(deckPicker).show {
We are trying to replace the MaterialDialog library and usages with standard AlertDialogs, can you alter this to use AlertDialog instead of MaterialDialog?

See #13315

2023-04-06 20:37 UTC, lonewolf2208 commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="storage_access_permission">Ankidroid requires storage access permission to function properly. This permission allows the app to access and modify files on your device, which is nece
I couldn't identify any strings related to the storage access explanation.

2023-04-09 00:45 UTC, david-allison requested changes
Did you confirm which API level this issue starts at?

2023-04-09 00:45 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +                )
seems unrelated

2023-04-09 00:45 UTC, david-allison commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name ="storage_access">Storage Access</string>
```suggestion
    <string name="storage_access">Storage Access</string>
```

2023-04-09 23:32 UTC, mikehardy commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="storage_access_permission">Ankidroid requires storage access permission to function properly. This permission allows the app to access and modify files on your device, which is nece
I could have sworn we used to have a string for this! Perhaps it was deleted during the scoped storage migration work. Anyway, I could not find one either!

```suggestion
    <string name="storage_access_permission">Ankidroid requires storage access permission to function properly. This permission allows the app to access and modify files in the general storage area of your device, which allows AnkiDroid to store and access your collection.</string>
```

Wording is always difficult and I am of course open to suggestion. I think this makes it more specific about what exactly we are doing with the general storage access permission, in the case of the full flavor where people might use it

What do you think?

2023-04-14 14:44 UTC, lonewolf2208 commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="storage_access_permission">Ankidroid requires storage access permission to function properly. This permission allows the app to access and modify files on your device, which is nece
Well, I think that this is sufficient information to inform users about the need for Ankidroid in order to access files.

2023-04-14 16:05 UTC, closed without merging

2023-04-15 01:00 UTC, Arthur-Milchior commented
This PR was started again on https://github.com/ankidroid/Anki-Android/pull/13604