fixes the horizontal logged in UI
ankidroid/Anki-Android pull request #13532
Opened 2023-04-01 11:58 UTC by criticalAY

## Pull Request template

## Purpose / Description
1. When the user was logged in and switched to the horizontal mode they could not access the Logout button 
2. The email and password section had a yellow tint that came when the user clicked autofill (autofill in our case is not necessary)

## Fixes
I have made the AnkiDroid logo for the logged-in screen consistent to that to login screen i.e. the AnkiDroid logo is not visible in horizontal mode
And the marked the edit text fields as not important for autofill 

## Approach
_How does this change address the problem?_

## How Has This Been Tested?
![loggedIN](https://user-images.githubusercontent.com/48384865/229287315-b3c8c0dd-96f2-45a0-a079-49b06a66e991.jpg)

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-04-06 06:14 UTC, criticalAY commented
@mikehardy requesting your review here

2023-04-08 07:39 UTC, lukstbit requested changes
LGTM in relation to the logout button issue, but also has unrelated changes that should be reverted.

2023-04-08 07:39 UTC, lukstbit commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                        android:importantForAutofill="no"
The changes in this file should be reverted. From my understanding, setting `importantForAutofill` to no disables the password saving feature and I don't see why we would to this.

2023-04-08 07:40 UTC, criticalAY commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                        android:importantForAutofill="no"
No this is not unwanted I have made that change on purpose see the PR template

2023-04-08 07:41 UTC, criticalAY commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                        android:importantForAutofill="no"
There is a yellow tint all over the edit text field if user clicks the autofill from the keyboard I have disabled that

2023-04-08 07:54 UTC, lukstbit commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                        android:importantForAutofill="no"
I saw it but I don't think that is a bug, just how the system handles the passwords(and it doesn't really matter as is only seen briefly). I see disabling the password saving by the system quite important and it shouldn't be disabled.

If you feel like this is a real issue then revert the changes here(as they are unrelated to the actual fix) and create a new issue(and add some images showing the behavior) so we can have more discussions.

2023-04-08 08:00 UTC, criticalAY commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                        android:importantForAutofill="no"
yes this tint was placed by google as a security measure to show to user that that password has been auto-filled anyway I will raise an issue and remove that part from this PR, Thankyou!

2023-04-08 08:21 UTC, lukstbit approved these changes
Great!

2023-04-08 14:00 UTC, mikehardy commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                        android:importantForAutofill="no"
Google will not change that. There will be a tint if the user autofills. Do not log an issue about it please

2023-04-08 14:09 UTC, criticalAY commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                        android:importantForAutofill="no"
I already raised ehhh but Thankyou Mike!

2023-04-08 14:10 UTC, criticalAY commented
I am rebasing the PR then cool

2023-04-11 03:35 UTC, david-allison approved these changes

2023-04-11 03:35 UTC, merged