Replaced toast with Snackbar in MultimediaEditFieldActivity
ankidroid/Anki-Android pull request #13542
Opened 2023-04-03 15:32 UTC by Giyutomioka-SS

## Pull Request template

## Purpose / Description
Replaced toast with Snackbar in MultimediaEditFieldActivity 

## Fixes
Related to #13541 13411

## How Has This Been Tested?
Tested on Realme 6
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-04-06 06:58 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +            showSnackbar(getString(R.string.multimedia_editor_failed), Snackbar.LENGTH_SHORT)
The required snackbar duration is Long
So you can remove this line `Snackbar.LENGTH_SHORT`

2023-04-06 06:58 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +        showSnackbar(getString(R.string.mutimedia_editor_assertion_failed), Snackbar.LENGTH_SHORT)
Same here also

2023-04-06 14:44 UTC, SanjaySargam approved these changes
LGTM!! 🎉

2023-04-14 09:45 UTC, lukstbit reviewed
One small issue.

2023-04-14 09:45 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +            showSnackbar((R.string.multimedia_editor_audio_permission_refused), Snackbar.LENGTH_SHORT)
Please remove the extra parentheses around the string id.

2023-04-14 10:15 UTC, Giyutomioka-SS commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +            showSnackbar((R.string.multimedia_editor_audio_permission_refused), Snackbar.LENGTH_SHORT)
Unit test are failing after removing those extra parentheses

2023-04-14 11:06 UTC, lukstbit approved these changes
Thank you!

2023-05-26 16:13 UTC, BrayanDSO requested changes
I'm afraid this wasn't tested. These toasts are shown when an activity is being closed, and since the snackbars are bound to an activity, they are finished together with the activity and don't show up

2023-06-16 17:36 UTC, closed without merging