Replace MaterialDialog with AlertDialog in SimpleMessageDialog.kt
ankidroid/Anki-Android pull request #13548
Opened 2023-04-04 15:13 UTC by jocoand

## Fixes
https://github.com/ankidroid/Anki-Android/issues/13315

## How Has This Been Tested?

Tested on Emulator API 33 

**Before** 
<img src="https://user-images.githubusercontent.com/106654580/229835796-b2942d56-57b6-4eef-9f12-6c6a7b1c5e46.png"  width="200"/>
<img src="https://user-images.githubusercontent.com/106654580/229836536-283a7fba-9377-416c-af86-46ab43086c91.png"  width="200"/>
<img src="https://user-images.githubusercontent.com/106654580/229836554-5d2fdb97-a9c6-4e57-8773-ea5c4ec7f6ce.png"  width="200"/>

**After**
<img src="https://user-images.githubusercontent.com/106654580/229836938-e56048ae-6ba8-484c-9678-baa3d44a37ea.png"  width="200"/>
<img src="https://user-images.githubusercontent.com/106654580/229836950-26c0c57d-7d58-4bd5-b8e4-b46e75f4a02e.png"  width="200"/>
<img src="https://user-images.githubusercontent.com/106654580/229836955-640feb12-da8b-496e-a55e-e56514d6dfff.png"  width="200"/>

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-04-04 20:23 UTC, oakkitten reviewed
Are you sure the screenshots are right? The “after” dialogs seem to have the margins of material dialogs, I don't suppose we've had those altered for alert dialogs?

2023-04-04 20:23 UTC, oakkitten commented on AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
> +    protected fun getAlertDialogText(@Suppress("SameParameterValue") checkDismissed: Boolean): String? {
I suggest either:

* renaming `getDialogText` to `getMaterialDialogText`, or
* unifying both method and keeping the name `getDialogText`

2023-04-04 20:23 UTC, oakkitten commented on AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
> +        dialog.getButton(button!!).performClick()
If you are going to `!!` the `button`, there's probably no need to have it nullable. Same applies to `clickDialogButton` which could also be renamed to `clickMaterialDialogButton` or merged with this one (might be harder to do).

2023-04-04 20:23 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
> +}
I would consider not creating this method. I suppose the ultimate goal is to use `AlertDialog` methods directly, or use a kind of **very* thin API around it. This method is used only once; I'd just inline it

2023-04-05 03:31 UTC, jocoand commented on AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
> +        dialog.getButton(button!!).performClick()
thanks, I missed this one

2023-04-05 03:31 UTC, jocoand commented on AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
> +    protected fun getAlertDialogText(@Suppress("SameParameterValue") checkDismissed: Boolean): String? {
Done, I ended up renaming the dialog

2023-04-05 03:37 UTC, jocoand commented
>> Are you sure the screenshots are right? The “after” dialogs seem to have the margins of material dialogs

I have updated the screenshots.

Thanks for the feedback 👍

2023-04-05 20:21 UTC, oakkitten commented
In the last commit you renamed `getAlertDialogText` to `getDialogText`. While this probably will be quite proper a name for the method once the migration to alert dialog is complete, consider keeping the name `getAlertDialogText`, so that we have `getAlertDialogText` for alert dialogs and `getMaterialDialogText` for material dialogs—that would be just neat.

Also, while you are at it, if simply to prevent the slight possible confusion by future readers, I'd make `button` in `clickMaterialDialogButton` non-nullable as well.

2023-04-06 16:47 UTC, lukstbit requested changes

2023-04-06 16:47 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SimpleMessageDialog.kt
> +            message(text = notificationMessage)
This is not correct, if `notificationMessage` is null then calling `message()` this way will throw an exception as that method expects that a valid string _or_ the id of a string resource will be provided. I think the original extension method you wrote is ok to use(there are more usages of contentNullable to replace for other MaterialDialogs usages), but I would change its name to `messageNullable()` to be aligned with the `message()` method.

2023-04-06 20:01 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SimpleMessageDialog.kt
> +            message(text = notificationMessage)
Uhh can we please simply use `setMessage`?

2023-04-07 02:13 UTC, jocoand commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SimpleMessageDialog.kt
> +            message(text = notificationMessage)
It looks like there is already a discussion about using a facade here https://github.com/ankidroid/Anki-Android/issues/13315#issuecomment-1439115880

2023-04-07 09:02 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SimpleMessageDialog.kt
> +            message(text = notificationMessage)
Whether we decide to use a facade or not, `message(text = ...)` is an awful API as it can lead to crashes as it's so easy to forget that it must take at least one non-null argument. The linked discussion is about having a different `message()` that acts exactly like `setMessage()` but has a different name. Before we decide on the API I think it's best to go the most simple way and use `setMessage()`.

2023-04-07 10:23 UTC, oakkitten approved these changes
I'd personally also replace stuff like `title(text = ...)` with alert dialog methods as a part of this PR, but this is quite optional

2023-04-07 13:02 UTC, jocoand commented
Done, thanks for the feedback 👍

2023-04-08 07:08 UTC, lukstbit approved these changes
Ok, thanks you!
For the other reviewer, #13525 should probably be merged before this as that pr also introduces the changes to tests(it was first and I would rather not introduce conflicts there).
@jocoand If the PR I linked to gets merged this is going to probably have some conflicts, just to let you know.

2023-04-08 07:10 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SimpleMessageDialog.kt
> +            message(text = notificationMessage)
@oakkitten I'm also for using directly `.setX()` methods from the builder class but my understanding is that we settle on using the facade methods. This should be addressed and settled to not have several ways of writing the dialogs when replacing them.

2023-04-14 11:09 UTC, lukstbit commented
@jocoand This PR took come conflicts that should be easy to fix. Let us know if you can work on them so we can get this merged.

2023-04-15 04:33 UTC, jocoand commented
any idea about the failed unit test, seems dependency problem 🤔 
Its fine when I run the test locally
```
* What went wrong:
Execution failed for task ':AnkiDroid:jacocoUnitTestReport'.
> Could not resolve all files for configuration ':AnkiDroid:jacocoAnt'.
   > Could not find org.jacoco.core-0.8.9.jar (org.jacoco:org.jacoco.core:0.8.9).
```

2023-04-15 06:11 UTC, lukstbit approved these changes
> any idea about the failed unit test, seems dependency problem thinking

Lately there are some issues with that dependency, I ran the tests again and everything is ok now.
Thanks again.

2023-04-15 06:12 UTC, merged