Replaced Toast with Snackbar in AudioView.kt & CustomStudyDialog.kt
ankidroid/Anki-Android pull request #13562
Opened 2023-04-06 12:45 UTC by Giyutomioka-SS

## Pull Request template

## Purpose / Description
Replaced toast with Snackbar in AudioView.kt & CustomStudyDialog.kt

## Fixes
Related to #13411 

## How Has This Been Tested?
Tested on Realme 6

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-04-07 05:15 UTC, SanjaySargam approved these changes
LGTM!!!

2023-04-07 10:37 UTC, oakkitten reviewed
Would be nice to have at least one screenshot to make sure things are positioned correctly

2023-04-07 10:37 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +                showSnackbar(getString(R.string.custom_study_deck_exists), Snackbar.LENGTH_SHORT)
You don't have to call `getString` for simple strings. Didn't run this change but I think it should work

```suggestion
                showSnackbar(R.string.custom_study_deck_exists, Snackbar.LENGTH_SHORT)
```

Same in other places

2023-04-07 19:04 UTC, Giyutomioka-SS commented
![photo_2023-04-08_00-32-09](https://user-images.githubusercontent.com/91668590/230663295-a2d014aa-4ccd-443d-8812-c93693669523.jpg)
![photo_2023-04-08_00-30-28](https://user-images.githubusercontent.com/91668590/230663345-a2097552-2579-47c5-8b89-1652928b8225.jpg)

2023-04-07 21:19 UTC, oakkitten requested changes
Thanks for the screenshots! Not using gesture navigation hint eh? Me too.

A few more simplifications to polish this off

2023-04-07 21:19 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +            showSnackbar((R.string.custom_study_rebuild_deck_corrupt))
Don't need double parentheses here

2023-04-07 21:19 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.kt
> +                    showSnackbar(resources.getString(R.string.multimedia_editor_audio_permission_denied), Snackbar.LENGTH_SHORT)
I think we can ditch the call to `resources.getString()` here as well

2023-04-07 21:19 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.kt
> +                            showSnackbar(gtxt(R.string.multimedia_editor_audio_view_recording_failed), Snackbar.LENGTH_SHORT)
Looking a bit deeper, we should actually be able to get rid of the call to `gtxt` here and elsewhere, and also of the [method itself](https://github.com/ankidroid/Anki-Android/blob/3b3a2eab89ed07fa4c2330c7fdcc3bb5f9728d1f/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.kt#L70-L72). A view has access to its resources, and we have a `View.showSnackbar()` method that takes an `Int` text resource.

2023-04-14 23:15 UTC, oakkitten approved these changes
LGTM 👍 (Disclaimer: didn't run the code)

2023-10-24 05:41 UTC, lukstbit commented
This took some conflicts...

2023-10-24 13:25 UTC, closed without merging