Deprecate methods in AlertDialogFacade
ankidroid/Anki-Android pull request #13576
Opened 2023-04-08 19:19 UTC by oakkitten

## Purpose / Description

`AlertDialog.Builder` `methods are well-known. Using a home-brew API that adds little to none functionality to the original ones is not very helpful. Also, some of the APIs are not type-safe, throwing an exception if neither of the string resource id nor text is provided.

## Approach

Methods are deprecated in favor of regular `AlertDialog.Builder` methods. Additionally,
* function AlertDialog.Builder.show is deprecated in favor of `showAlertDialog`. This function, placed in 
  `com.ichi2.anki.ui.dialogs.tools`, parallels the existing `showSnackbar`.
* function `checkBoxPrompt`, being used in one place only, is refactored into a more type-safe `setCheckBoxPrompt` in the same package.

**NOTE**: I didn't find a way to make proper `ReplaceWith` for many cases. E.g. I opted for `"setMessage(stringRes ?: text)"` for `message()`; the former only accepts a single argument but the latter accepts two. The resulting code needs some adjustments, e.g.

    positiveButton(R.string.dialog_cancel) { onCancel() }

is converted to

    setPositiveButton(R.string.dialog_cancel ?: null) { onCancel() }

which has to be manually changed into

    setPositiveButton(R.string.dialog_cancel) { _, _ -> onCancel() }

I don't know if there's a better way.

The tests fail because warnings are reported as errors, not sure what's the procedure to deal with this.

## How Has This Been Tested?

Tested in AS (deprecation warning) and on device (behavior of `setCheckBoxPrompt`).

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-04-09 08:44 UTC, lukstbit requested changes

2023-04-09 08:44 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/tools/Dialogs.kt
> +package com.ichi2.anki.ui.dialogs.tools
Add the new functionality from this file to the `com.ichi2.anki.dialogs/Utils.kt` file(which should also be renamed to `AlertDialogUtils` in another PR to keep those one as simple as possible), we already have a lot of functionality spread across multiple files all over the application. 

I know there's a discussion about refactoring the package structure but until that becomes an active issue settled and being worked on we should use the current structure.

2023-04-09 08:44 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/tools/Dialogs.kt
> +fun Context.showAlertDialog(block: AlertDialog.Builder.() -> Unit) {
Use the `AppCompatActivity` as the receiver, a `Service` is also a `Context` and the current code would allow developers to call this method inside it which is an error.

2023-04-09 08:44 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/tools/Dialogs.kt
> +        .show()
This method(and the one on Fragment) should return the created `AlertDialog`, further calls on the returned `AlertDialog` may be desired(for example we currently use a keyboard related extension on MaterialDialog which would require the AlertDialog instance to be available to replicate it).

2023-04-09 08:44 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
> +@Deprecated("This method is deprecated as it is not type-safe. Use setTitle() instead.", ReplaceWith("setTitle(stringRes ?: text)"))
Because any of the options for `@Deprecated(level = DeprecationLevel.*)` will trigger a build error, you have two options:
- remove the @ Deprecated annotation and add deprecation notices in the javadoc and have the current usages gradually fixed over time
- replace all current usages of this methods with the new code(I could help with this as well, just that this would not get merged until it builds)

I'm not sure how to handle the issue related to ReplaceWith.

2023-04-09 10:25 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/tools/Dialogs.kt
> +package com.ichi2.anki.ui.dialogs.tools
I thought that we decided that it would be fine to use Artur's proposed package structure for new files at least. So I would like to keep this file; but having functionality spread over files is indeed not helpful. How about I move/refactor the contents of `com.ichi2.anki.dialogs/Utils.kt` instead?

2023-04-09 10:29 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/tools/Dialogs.kt
> +fun Context.showAlertDialog(block: AlertDialog.Builder.() -> Unit) {
It's interesting that `AlertDialog.Builder` doesn't itself require an activity. It seems that it indeed can work without one in some esoteric cases, but perhaps for our own API the restriction would make sense. I'll change the receiver to `Activity` unless there's a specific reason to use `AppCompatActivity`

2023-04-09 10:34 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/tools/Dialogs.kt
> +        .show()
I'd prefer this method not to “leak” the dialog unless it is necessary. I suggest that we add this functionality if and when we do find it necessary

2023-04-09 10:39 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
> +@Deprecated("This method is deprecated as it is not type-safe. Use setTitle() instead.", ReplaceWith("setTitle(stringRes ?: text)"))
Hm, using comments instead of `@Deprecated` seems rather silly, that's what the annotation was made for. Can we not treat warnings as errors, at least for deprecations?

Replacing actual usages sounds better, but since @mikehardy greenlit the idea of deprecating these methods let's ask if he had anything else in mind?

2023-04-09 13:05 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
> +@Deprecated("This method is deprecated as it is not type-safe. Use setTitle() instead.", ReplaceWith("setTitle(stringRes ?: text)"))
IMO, replace usages. 

This was going to be done later when the dialogs' migration was complete, as the motive for having these methods is just to reduce the diff when reviewing. Since these temporary methods are apparently causing some problems, it would be good to replace them now.

2023-04-10 10:41 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/tools/Dialogs.kt
> +package com.ichi2.anki.ui.dialogs.tools
It wasn't decided, Arthur wrote: _this issue is up for discussion, we are not expecting anyone to do anything until there is a consensus._ without any input from David and Mike(it's a really low priority issue IMO right now). By using the file I pointed we are combining the extensions for AlertDialog and in the future the change to a new package will result into a simple rename operation instead of a consistent diff.

> How about I move/refactor the contents of com.ichi2.anki.dialogs/Utils.kt instead?

It would be out of scope of this PR.

2023-04-10 10:46 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/tools/Dialogs.kt
> +fun Context.showAlertDialog(block: AlertDialog.Builder.() -> Unit) {
I misspoke about this and `Context` is the proper receiver. I've looked through some of the future usages of `showAlertDialog` and it would be also used on a view/dialog Context or on simple Context defined properties. So it needs to be a Context.

Maybe we could introduce a check in this method to see if the Context receiver is an `Application` or `Service` and throw an exception if it is. This is up to you, I have no preference on this.

2023-04-10 10:47 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/tools/Dialogs.kt
> +        .show()
As I mentioned in the example above, we are going to need it, but it can be added later.

2023-04-10 11:22 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/tools/Dialogs.kt
> +fun Context.showAlertDialog(block: AlertDialog.Builder.() -> Unit) {
I suppose I'd rather not in this case. `showAlertDialog` is a very simple and straightforward bit of sugar that wraps around `AlertDialog` APIs. Besides, if we do try to create a dialog with an improper context it will crash anyway, albeit with a more cryptic—but easily googleable—message.

2023-04-10 13:40 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/tools/Dialogs.kt
> +package com.ichi2.anki.ui.dialogs.tools
Why odd?

2023-04-10 13:44 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/tools/Dialogs.kt
> +package com.ichi2.anki.ui.dialogs.tools
Why on `anki`? Why a `tools` subdirectory inside of dialogs if we barely have anything else on `dialogs`?

2023-04-10 15:23 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/tools/Dialogs.kt
> +package com.ichi2.anki.ui.dialogs.tools
* `com.ichi2.anki` because that's our app ID. It makes sense to have everything directly app/Android-related be under this. It also allows shortening the names in XML, e.g. `com.ichi2.anki.Foo` can be shortened to `.Foo`.

* `com.ichi2.anki.ui.dialogs` will contain the dialogs themselves after refactor, and `com.ichi2.anki.ui.dialogs.tools` contain helper things, so that you have `com.ichi2.anki.ui.dialogs.tools.showAlertDialog`. (To be renamed to `showDialog`, paralleling the existing `awaitDialog` in the same package.)

*  A file called `Dialogs.kt` parallels another one, called `AsyncDialogs.kt`, in the same directory, and is similar to `Snackbars.kt`.

I'm not bent on these names, just explaining my reasoning. If there's a better idea I'll change the structure

2023-04-10 22:43 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/tools/Dialogs.kt
> +package com.ichi2.anki.ui.dialogs.tools
> com.ichi2.anki because that's our app ID. It makes sense to have everything directly app/Android-related be under this. It also allows shortening the names in XML, e.g. com.ichi2.anki.Foo can be shortened to .Foo.

So everything is going to be migrated into com.ichi2.anki? If so, fine by me. Asked because there is a com.ichi2.ui package, so I wasn't sure where it should be exactly on this new structure. 

> A file called Dialogs.kt parallels another one, called AsyncDialogs.kt, in the same directory, and is similar to Snackbars.kt.

I don't care much here, although this still isn't a descriptive name IMO.

2023-04-11 02:54 UTC, david-allison requested changes
Proposing to close

https://github.com/ankidroid/Anki-Android/blob/aaedfb53dac4dbbf70458231bbf928800e28c39d/AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt#L37-L41

The point of this file and methods are to reduce the noise in the diff when converting from `com.afollestad.materialdialogs` (https://github.com/ankidroid/Anki-Android/issues/13315). They're not expected to be a permanent part of the codebase

Deprecating the methods before the migration is completed only adds additional work to the migration (by causing more code churn for reviewers, and more risk that contributors will make errors).

The dangerous methods were dangerous on `com.afollestad.materialdialogs`, I don't see what danger we're adding (unless I'm missing something).

Once the migration is completed, the methods should be inlined. This can be done trivially for the majority, and is much less work than expecting contributors to do the work manually during the migration process.

As a sample of what this class enables: https://github.com/ankidroid/Anki-Android/pull/13326/

2023-04-11 19:21 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/tools/Dialogs.kt
> +package com.ichi2.anki.ui.dialogs.tools
> Asked because there is a com.ichi2.ui package

What *is* `com.ichi2` though? `com.ichi2.anki` is the our app ID, but that other one doesn't carry any significant meaning. 

> So everything is going to be migrated into com.ichi2.anki? 

I would do that. Everything in one folder, under package named after our app ID. Perhaps the advantage is not big but this is simple and I see no reason to do otherwise.

> I don't care much here, although this still isn't a descriptive name IMO.

Well no-one objected `Snackbars.kt` 😛 Also, there already is `DialogUtils.kt` and I'm not a fan of having two same name files. And anyway, the file name doesn't matter much since you know it's Kotlin.

2023-04-18 15:22 UTC, david-allison commented
Calling deprecated methods is currently an error, it confuses the matter when new contributors want to pick up the issue. We have a lot of work to do and want to optimize for an easy + bug-free conversion here.

>  a) have to import the according methods

Fair point, I personally don't see this as an issue when reviewing.

>  b) you have to study these methods if you are using them the first time

The contract of the methods in the Facade is 'works as it did previously'. It's more time to think "what does `.positiveButton()`" map to in `AlertDialog`, compared to calling the same method with the same signature on the class.

> you will have two PRs for a dialog, which will double the effort to make the PR, and to review it. This IMO is quite wasteful.

It leads to 1 simple PR for the dialog, then one simple 'inline the facade' for all dialogs once the conversion work has been completed. It's wasteful to have large diffs to review, when they can be one or two lines of functional change and a few imports.

2023-04-19 20:13 UTC, oakkitten commented
I think a reasonable developer is not going to assume that the method of the same name belonging to a different class is going to behave the same way for a different class, so they'll have to study it anyway. With regarding to how methods map to each other, thankfully in most cases you just prepend `set` so this should be a non-issue and shouldn't take much more time compared to importing the facade methods. And if that “one simple 'inline the facade' PR” is indeed that simple why not just do it right away for every dialog PR?

Look, how many material dialogs do we have? When I suggested the API for snackbars I just went ahead and changed every snackbar and it wasn't too hard. I am willing to do the same for the dialogs once we deal with migration and when I have time.

2023-05-10 20:37 UTC, closed without merging