fix: Changed title and action names of cancel share deck download dialog
ankidroid/Anki-Android pull request #13587
Opened 2023-04-10 05:27 UTC by pratyaksh1610

## Pull Request template

## Purpose / Description
Changed title and action names of cancel share deck download dialog

## Fixes
Fixes #13386

## Approach
Changed title and action names of cancel share deck download dialog

## How Has This Been Tested?

![ss](https://user-images.githubusercontent.com/76740999/230832378-b51b48d8-6f37-47bb-902c-50656cd2d63c.png)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-04-11 11:37 UTC, lukstbit requested changes

2023-04-11 11:37 UTC, lukstbit commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="cancel_download_question_title">Do you want to cancel download?</string>
This change should be reverted, the original text is perfectly fine.

2023-04-15 06:39 UTC, pratyaksh1610 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="cancel_download_question_title">Do you want to cancel download?</string>
Done

2023-04-15 08:28 UTC, lukstbit approved these changes
Thanks!

2023-04-15 08:29 UTC, merged