only show text in edittext pref in custom study deck settings
ankidroid/Anki-Android pull request #13582
Opened 2023-04-09 05:41 UTC by criticalAY

## Pull Request template

## Purpose / Description
I am allowing the user to only see the search text for the deck and properties they selected which I think is the right thing to do as the text if altered and not matched with the required one causes an issue as I said on Discord 
There is another but that would require to creation of two new fields one for the deck and one for the property, deck field would be fine but the property field would be a mess as there are lists and limits or even text which are accepted as properties.

## Fixes
Fixes #13581

## How Has This Been Tested?

Tested on oneplus nord ce
![Screenshot_25](https://user-images.githubusercontent.com/48384865/230756463-0da24446-5faf-4491-8970-37108a45fe93.jpg)

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-04-09 09:38 UTC, BrayanDSO commented
This setting shouldn’t be disabled. The user is supposed to be able to change their filtered decks queries as they please.

2023-04-09 09:41 UTC, criticalAY commented
A slight mistake while changing the query causes a crash

2023-04-09 09:42 UTC, BrayanDSO commented
Why not fix the crash instead of disabling functionality?

2023-04-09 09:44 UTC, criticalAY commented
Umm I know from where the crash is occurring so ok can try to handle the crash itself

2023-04-09 10:52 UTC, BrayanDSO requested changes

2023-04-09 10:52 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/BaseSched.kt
> +        }
this ignores the issue instead of fixing it

2023-04-09 12:33 UTC, criticalAY commented
we can not make this behave like other edit text preferences and display an error in the dialog itself but the best thing I can come up with is that comparing the string with regex and allowing and not allowing the user to depending on the syntax it works fine

2023-04-09 13:03 UTC, criticalAY commented
I need little help here as the deck name can be anything so I want to update the regex but I am not able to fix it

2023-04-09 13:08 UTC, BrayanDSO commented
If you see how it works on Anki Desktop, custom study decks are just filtered decks. The user should be able to use ANY query, not only queries with "deck:"

2023-04-09 13:11 UTC, criticalAY commented
> If you see how it works on Anki Desktop, custom study decks are just filtered decks. The user should be able to use ANY query, not only queries with "deck:"

So this deck also needs to be removed then there only needs a check for some `foo1:"abc" foo2:xyz` basically the quotes and the colon

2023-04-09 13:42 UTC, criticalAY commented
ok so now this would allow taking any string but would make sure that there is `" "` and two `:` in their respective places

2023-04-09 16:13 UTC, BrayanDSO commented
As I said, Anki desktop accepts any queries, which include empty queries. I don't think that a RegEx should be used here

2023-04-09 16:17 UTC, criticalAY commented
The logcat says it is related to the backend but we need to handle ti in some way either try-catch or modify the regex, do you have another solution that would suit better here?

2023-04-09 16:25 UTC, BrayanDSO commented
Do you have the stacktrace?

2023-04-09 16:43 UTC, criticalAY commented
yes wait

2023-04-09 16:48 UTC, criticalAY commented
@BrayanDSO logcat stackstrace
```
net.ankiweb.rsdroid.BackendException$BackendSearchException: Invalid search: ⁨an opening double quote `"` was found, but there was no second one to close it. If you want to search for a literal `"`, prepend a backslash: `\"`.⁩
                                                                                                    	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:118)
                                                                                                    	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:323)
                                                                                                    	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
                                                                                                    	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:130)
                                                                                                    	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:129)
                                                                                                    	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:157)
                                                                                                    	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:129)
                                                                                                    	at anki.backend.GeneratedBackend.rebuildFilteredDeckRaw(GeneratedBackend.kt:1375)
                                                                                                    	at anki.backend.GeneratedBackend.rebuildFilteredDeck(GeneratedBackend.kt:1385)
                                                                                                    	at com.ichi2.libanki.sched.BaseSched.rebuildDyn(BaseSched.kt:265)
                                                                                                    	at com.ichi2.libanki.sched.SchedV2.rebuildDyn(SchedV2.kt:1796)
                                                                                                    	at com.ichi2.anki.FilteredDeckOptions.closeWithResult(FilteredDeckOptions.kt:261)
                                                                                                    	at com.ichi2.ui.AppCompatPreferenceActivity.onOptionsItemSelected(AppCompatPreferenceActivity.kt:298)
```

2023-04-09 18:24 UTC, BrayanDSO commented
Desktop behavior:
![image](https://user-images.githubusercontent.com/69634269/230789893-5ac00406-9b54-4267-ae77-d18217a590d2.png)

I suggest try-catching the error and showing a dialog, as the desktop app does

2023-04-09 21:16 UTC, criticalAY commented
I am updating the PR template with the new tested screenshot

2023-04-09 21:19 UTC, BrayanDSO requested changes

2023-04-09 21:19 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="wrong_search_query">An opening double quote \" was found, but there was no second one to close it. If you want to search for a literal \", prepend a backslash: \\ \".</string>
This text is the same found on the BackendException message, so get it from there

2023-04-09 21:19 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="search_filter_error">Search filter error</string>
unnecessary

2023-04-09 21:25 UTC, criticalAY commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="wrong_search_query">An opening double quote \" was found, but there was no second one to close it. If you want to search for a literal \", prepend a backslash: \\ \".</string>
The error message contains the backend error..... Then the actual string

2023-04-09 21:26 UTC, criticalAY commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="search_filter_error">Search filter error</string>
Completely remove the title you mean?

2023-04-09 22:11 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="search_filter_error">Search filter error</string>
or use a generic "Error" title, your choice

2023-04-09 22:13 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="wrong_search_query">An opening double quote \" was found, but there was no second one to close it. If you want to search for a literal \", prepend a backslash: \\ \".</string>
When rebuilding a filtered deck with the new backend enabled, the shown message looks fine to me though

![image](https://user-images.githubusercontent.com/69634269/230798935-c0d47c00-fa0d-45e2-90c4-e4b03ed76fad.png)

If are speaking about the "Invalid search:" string, I believe that it's a lot better to keep it instead of "duplicating" a string and add more work to the translators

2023-04-13 19:36 UTC, BrayanDSO requested changes

2023-04-13 19:36 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
> +            }
You repeat this twice, maybe this could be extracted into a function?

Soft-approve after it. 

No major refactors are worth it because this class should be gone when we get rid of DeckOptions.kt (after the new backend is the default) and the filtered deck options screen either is migrated to the new androidx preferences library or someone implements a Svelte filtered deck screens that can be reused here (on my TODO list, actually because I can't find a filtered deck option on my iPad and would get rid of this task on AnkiDroid).

2023-04-13 19:36 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
> +        dialog.show()
```suggestion
            AlertDialog.Builder(this).show {
                setTitle(getString(R.string.pref__widget_text__error))
                setMessage(error.message)
                setPositiveButton(getString(R.string.dialog_ok)) { dialog, _ ->
                    dialog.dismiss()
                }
            }
```

2023-04-14 06:10 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
> +            }
Umm yes its being used twice so we can but it is going to be removed soon so sure

2023-04-14 09:08 UTC, lukstbit commented
@criticalAY In one of the review comments Brayan requested that you use the `show {}` extension method. Please use that, there's no reason to have:

```
AlertDialog.Builder().apply { 
      ...
     show()
}
```

when you can write 

```
AlertDialog.Builder().show { 
   ...
}
```

2023-04-14 09:54 UTC, criticalAY commented
> @criticalAY In one of the review comments Brayan requested that you use the `show {}` extension method. Please use that, there's no reason to have:
> 
> ```
> AlertDialog.Builder().apply { 
>       ...
>      show()
> }
> ```
> 
> when you can write 
> 
> ```
> AlertDialog.Builder().show { 
>    ...
> }
> ```

I'm aware of that but we can't directly use `show` here I already tried that before making this PR and after Brayan suggested just to be sure.

2023-04-14 11:07 UTC, lukstbit commented
> we can't directly use show here I already tried that before making this PR

Why we can't use the `show {}` extension method here?

2023-04-14 14:56 UTC, criticalAY commented
> > we can't directly use show here I already tried that before making this PR
> 
> Why we can't use the `show {}` extension method here?

It was a import error, sorry, fixed it

2023-04-15 17:21 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
> +    private fun closedWithResult() {
I think it's confusing having very similar names such as closeWithResult() and closedWithResult()

2023-04-15 17:24 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
> +    private fun closedWithResult() {
what else do you want me to rename it to?

2023-04-15 17:25 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
> +    private fun closedWithResult() {
tryResult

2023-04-15 17:26 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
> +    private fun closedWithResult() {
Yeah, tryCloseWithResult is fine enough

2023-04-15 17:40 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
> +    private fun closedWithResult() {
Ok

2023-04-16 14:10 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
> +            Timber.e("Backend search exception")
```suggestion
            Timber.e(e, "Backend exception while trying to finish a AppCompatPreferenceActivity")
```

2023-04-16 14:49 UTC, BrayanDSO approved these changes
Lgtm, thanks!

2023-04-19 04:55 UTC, lukstbit approved these changes

2023-04-19 04:56 UTC, merged