Display dialog for API>=33
ankidroid/Anki-Android pull request #13604
Opened 2023-04-14 20:41 UTC by lonewolf2208

## Pull Request template

## Purpose / Description
At an unknown API level, "Allow management of all files" is no longer available in the app permissions screen.

## Fixes
Fixed #13520

## Approach
Added a dialog box signifying the need of storage permission

Note - I couldn't find a prior string that was relevant, so I had to build a new one for the dialogue box's message.

![image](https://user-images.githubusercontent.com/72886809/229314587-7cb78eb3-e3cd-41ad-8e64-e9a9dcfdc4d1.png)

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-04-14 20:43 UTC, lonewolf2208 commented
Good day @david-allison , i have created a new PR previous one got some issues , Can you please review it . Inconvienence regretted

2023-04-15 01:23 UTC, Arthur-Milchior requested changes
Hi @lonewolf2208, 

Enchanted to meet you, thanks a lot for your first contribution

Please, in general, do not close PR and open new one. Just push new commits on top of the initial one. Or better, force push a commit on top of the existing PR. . Because when looking at the current PR, we don't see the messages of #13535. At the very least, please mention #13535 in your PR message.

I'd love your help to figure out to review this PR.

How did you determine that the limit is API level 33?  David asked you that in the previous PR and I had not seen an answer. Could you please provide a link to the relevant documentation in your commit message. Or if you didn't find any documentation, at least, the way you figured out this level.

More importantly, concerning the commit message, please add a more descriptive title. "Display dialog for API >=33" is pretty vague without explaining which dialog. Maybe "Require management of all ifles on API >=33"

Can you also explain how you tested it yourself, so that reviewers can reproduce your test and ensure they can obtain the expected behavior? Ideally, this should also be in your commit message, if not in the PR text.

@mikehardy ; I expect the file you wanted was deleted in eb49979e9b52f75f7020e02b4d749c0fa638797d , it was named `collection_load_welcome_request_permissions_details` and stated:
> AnkiDroid requires storage permission, which we use exclusively to store your AnkiDroid collection, flashcard media and backups. Our code is open-source, written by volunteers, and trusted by millions.
>
> If you have any questions, please access our in-app manual or visit our support forums.
>
> Thank you for trying AnkiDroid!
> —AnkiDroid Development Team

I believe we can use it still, except that I don't know any simple way to upload the translations back (the API would allow it, but that would mean creating a new script for it)

In the meantime, I guess I'd prefer, @lonewolf2208 , if you could reuse the string that we have had for years.

2023-04-15 01:23 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="storage_access_permission">>Ankidroid requires storage access permission to function properly. This permission allows the app to access and modify files in the general storage area
`>>` should be a single `>`

2023-04-15 01:23 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +                    deckPicker.finishActivityAndShowAppPermissionManagementScreen()
I thought the very point of this issue is that we want the generic ankidroid settings screen instead of the permission management screen.
If so, please find out how to open the right screen

2023-04-15 17:47 UTC, BrayanDSO commented
I believe that this should change the code specified on the issue's text. The "onPermanentlyDismissDialog()" issue is another problem

2023-04-15 18:00 UTC, lonewolf2208 commented
Thanks , @Arthur-Milchior . Will definitely consider your recommendations after receiving the input.

2023-04-15 18:03 UTC, lonewolf2208 commented
> How did you determine that the limit is API level 33? David asked you that in the previous PR and I had not seen an answer. Could you please provide a link to the relevant documentation in your commit message. Or if you didn't find any documentation, at least, the way you figured out this level.
I basically read over the Mike's ideas https://github.com/ankidroid/Anki-Android/issues/13520#issuecomment-1488409306
and implemented the idea .

2023-04-15 18:34 UTC, lonewolf2208 commented
> I believe that this should change the code specified on the issue's text. The "onPermissionPermanentlyDenie()" issue is another problem

Yes, I think the PR should be updated.

2023-04-15 23:27 UTC, david-allison requested changes

2023-04-15 23:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +                    deckPicker.finishActivityAndShowAppPermissionManagementScreen()
The issue is that Android does not enforce the presence of the "Allow All Files Access" screen according to the docs

https://github.com/ankidroid/Anki-Android/blob/905d456890f696cff0add7bb176ab8ae25d6572f/AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt#L187-L188

- at a given Android version, this screen no longer lets the user change `MANAGE_EXTERNAL_STORAGE` from the permission screen. At this point, show the dialog

2023-04-17 21:25 UTC, lonewolf2208 commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +                    deckPicker.finishActivityAndShowAppPermissionManagementScreen()
Greetings to everybody. I'm a little bit confused, so could you tell me if I'm heading in the correct direction or not? 
```kt
 if (intent.resolveActivity(packageManager) != null) {
        accessAllFilesLauncher.launch(intent)
    } else if(/* TODO */){
        // Since, on some API level this action has been removed,
        // So we need to do something else!
        // This also allows management of the all files permission (worse UI)
        finishActivityAndShowAppPermissionManagementScreen()
    }
    else
    {
        // Display dialog and open general settings
    }
```

2023-05-16 17:36 UTC, closed without merging