Move file consider destinations which are prefix of the source
ankidroid/Anki-Android pull request #13619
Opened 2023-04-16 09:55 UTC by Arthur-Milchior

I added a method to detect prefix of files.

As I found the code quite confusing to read, I rewrote it to split in three cases:
* source does not exists
* destination exists
* move can occur as expected

Fixed: #13170

2023-04-16 13:29 UTC, david-allison commented
Tests are failing

2023-04-16 13:34 UTC, david-allison requested changes

2023-04-16 13:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.kt
> +                if (prefixFileEnded && fullFileEnded) {
Maybe I'm missing something (reviewing on my phone), but this doesn't seem to handle file contents.

If one file contains "a" and the other contains "bb", then it should not be considered to be a prefix

2023-04-20 00:49 UTC, Arthur-Milchior reviewed
I'll look at the failures

2023-04-20 01:45 UTC, Arthur-Milchior commented
Corrected.
Only difference, I believe it makes more sense to have a progress of 0 reported all of the time a move's source is a non existing field. 
I also would be all right with always having no progress reported.

Just, having a progress reported if and only if the destination does not exists didn't make much sense to me, so I changed an implementation. And so changed one test at the same time

2023-04-20 22:20 UTC, david-allison approved these changes
This is great, thank you!

2023-04-20 22:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.kt
> +                if (prefixFileEnded && fullFileEnded) {
Ah! Definitely an issue reviewing on my phone. Thanks

2023-04-21 01:25 UTC, david-allison commented
nit: https://github.com/ankidroid/Anki-Android/blob/3f251cf6dc61e52ea9fb91116ab09fc17d84596b/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/migrateuserdata/MigrateUserData.kt#L535-L537 can be removed

2023-04-21 21:32 UTC, mikehardy approved these changes
All seems fine, I had a nit with a concrete suggestion, it is just changing wording a log message (which I attach very very low importance to)

Going to mark it approved, I'm fine with anyone merging this for speed without the nit fixed, or if the nit is fixed then *please* merge

2023-04-21 21:32 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFile.kt
> +                Timber.w("(conflict) Deleted empty file in destination. Deletion result: %b", deletionSucceeded)
```suggestion
                Timber.w("(conflict) Deleted partial file in destination. Deletion result: %b", deletionSucceeded)
```

technically an empty file is a partial file isn't it? anyway now that you are checking for prefixes empty is definitely not correct, partial seems more correct. This is a nit though

2023-04-21 21:53 UTC, mikehardy commented
On reflection, if I'm going to hang this on a nit, I'm going to pull it locally, fix the nit then push and merge. No more delay

2023-04-21 22:29 UTC, merged