Fix: storage migration shown on API 27 [Amazon]
ankidroid/Anki-Android pull request #13614
Opened 2023-04-15 23:59 UTC by david-allison

## Pull Request template

## Fixes
- Fixes #13612

## Approach
We were using the condition `allFileAccessPermissionGranted` 

But this returns false before API 30  Instead define and use `collectionWillBeMadeInaccessibleAfterUninstall` which takes this condition into account  

## How Has This Been Tested?
* Unit Tests
* ⚠️ Downloading the API 27 emulator as we speak

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-04-16 00:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
> +    fun collectionWillBeMadeInaccessibleAfterUninstall(context: Context): Boolean {
This is somewhat duplicated, but not enough to extract it (IMO). Review comments welcome

2023-04-16 14:07 UTC, BrayanDSO requested changes

2023-04-16 14:07 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
> +     * except for using another build of `com.ichi2.anki` pr manually copying files
"pr" at `pr manually...`

2023-04-16 14:07 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
> +    fun collectionWillBeMadeInaccessibleAfterUninstall(context: Context): Boolean {
fine by me

2023-04-17 20:45 UTC, david-allison reviewed
forgot to comment

2023-04-18 17:44 UTC, BrayanDSO approved these changes
LGTM

2023-04-21 21:15 UTC, mikehardy approved these changes
what a tangled web we weave

2023-04-21 21:16 UTC, merged