#12451 Issue: Replace string with plurals
ankidroid/Anki-Android pull request #13616
Opened 2023-04-16 02:58 UTC by Aayush-Goel-04

## Checklist

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-04-16 03:25 UTC, Aayush-Goel-04 commented on AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.kt
In the corrected syntax, the first argument to getString() is the plural resource ID, the second argument is the quantity (the number of media files downloaded), and the third argument is the value that should be used when the quantity is zero.
This will return the string for the plural resource sync_media_downloaded_count, with the %d placeholder replaced with the value of mDownloadCount.

2023-04-16 13:00 UTC, david-allison requested changes
CI needs fixing

2023-04-17 08:51 UTC, Aayush-Goel-04 commented
Of the 8 PluralCandidates, first and last one don't need to be changed to plurals. 
For first one , both the params are constants. So String will be always be same. 
For last one, It is used to create "notify" dialog in notification preferences where strings always in plural form.The string entry values are always more than 1. 
For remaining, we need to add plurals.
Plurals 2,3,4,5,6,7 have been changed. String key names have been changed as-
name = "string_key" to name =""

2023-04-18 11:41 UTC, Aayush-Goel-04 commented
> CI needs fixing
CI checks are passing now

2023-04-19 10:32 UTC, Aayush-Goel-04 commented
> CI needs fixing

@david-allison 
I have changed the string keys. 
All checks are now passing.
Can you review it?

2023-04-24 15:06 UTC, doozan commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +        <item quantity="other">Updated %1$d of %2$d existing notes.</item>
The singular string "1 of 2 existing note" is wrong. I don't think this string needs a singular, "Updated 1 of 1 existing notes" sounds fine to me.

2023-04-24 15:08 UTC, doozan commented on AnkiDroid/src/main/res/values/04-network.xml
> +    </plurals>
This seems wrong, there are actually two variables here that could lead to a plural/singular. This doesn't account for the cases "1 media file downloaded. 2 media files uploaded" and "2 media files downloaded. 1 media file uploaded"

2023-04-25 05:24 UTC, Aayush-Goel-04 commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +        <item quantity="other">Updated %1$d of %2$d existing notes.</item>
I Thank you for pointing that out. I understand your concern about the singular string "1 of 2 existing note" being wrong. After considering your feedback, I agree that the phrase "Updated 1 of 1 existing notes" would sound more appropriate in this context. 
I will make the necessary changes to the code accordingly. 
Thank you for your valuable input.

2023-04-25 05:27 UTC, Aayush-Goel-04 commented on AnkiDroid/src/main/res/values/04-network.xml
> +    </plurals>
Hey there! You pointed out something interesting about the plural/singular usage in that code snippet. I agree with you that it doesn't cover all possible cases like "1 media file downloaded. 2 media files uploaded" and "2 media files downloaded. 1 media file uploaded".
Thanks for bringing it up!

2023-05-05 16:52 UTC, Aayush-Goel-04 commented
> CI needs fixing

Hi @david-allison ,
I have made the changes. Please take a look at my updated code when you have a chance.
Thank you!

2023-05-19 04:37 UTC, Aayush-Goel-04 commented
Hi @david-allison ,
Can you review the changes made.
Thanks!

2023-06-02 09:56 UTC, Aayush-Goel-04 commented
Hi @david-allison 
Can you review the changes made.
Thanks!

2023-06-22 14:40 UTC, mikehardy commented on AnkiDroid/src/main/res/values/04-network.xml
> +        <item quantity="other">Your clock’s off by %1$d seconds%2$s. Make sure that the date, time, and timezone on your phone are set correctly, then sync again.</item>
the apostrophe here does not seem correct to me. I think it is a possessive apostrophe instead of a contraction, expanding it to disambiguate

```suggestion
        <item quantity="one">Your clock is off by %1$d second%2$s. Make sure that the date, time, and timezone on your phone are set correctly, then sync again.</item>
        <item quantity="other">Your clock is off by %1$d seconds%2$s. Make sure that the date, time, and timezone on your phone are set correctly, then sync again.</item>
```

2023-06-22 14:47 UTC, mikehardy approved these changes
These look good to me. I removed the merge commit, rebased to current main and re-pushed, plus committed one small text change, if CI passes I think this can go in

2023-06-22 15:18 UTC, merged