Replace MaterialDialog with AlertDialog in SharedDecksDownloadFragment class
ankidroid/Anki-Android pull request #13621
Opened 2023-04-18 13:14 UTC by ashutosh-kumar-kushwaha

## Purpose / Description
Deprecate MaterialDialog and use AlertDialog instead https://github.com/ankidroid/Anki-Android/issues/13315

## Fixes
Replaced MaterialDialog with AlertDialog in the function showCancelConfirmationDialog()

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-04-18 13:28 UTC, SanjaySargam commented
You quit **`How has been tested`** section in PR template

Btw Thanks for contributing 🚀🚀🚀

2023-04-18 14:34 UTC, david-allison reviewed
Looks good! Thanks. One question and good to go

2023-04-18 14:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            }.create()
is `create` necessary?

2023-04-18 19:01 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            AlertDialog.Builder(it).show {
Since we are using the Material Components library it would be better to use MaterialAlertDialogBuilder.
_Source: https://stackoverflow.com/a/57896538/10420283_

2023-04-19 04:57 UTC, ashutosh-kumar-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            }.create()
Got this error when I removed create()

> Type mismatch: inferred type is AlertDialog.Builder? but AlertDialog? was expected

2023-04-19 04:58 UTC, ashutosh-kumar-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
>      @Suppress("deprecation") // onBackPressed
Got this warning after removing @Suppress("deprecation")

> 'onBackPressed(): Unit' is deprecated. Overrides deprecated member in 'androidx.core.app.ComponentActivity'. Deprecated in Java

2023-04-19 08:40 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
>      @Suppress("deprecation") // onBackPressed
You can also fix the onBackPress deprecation while you are at this.
_Have a look at this link: https://stackoverflow.com/questions/72634225/onbackpressed-deprecated-what-is-the-alternative_

2023-04-19 11:34 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
>      @Suppress("deprecation") // onBackPressed
This deprecation isn't yet solved so the suppress annotation should remain.

2023-04-19 11:35 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            AlertDialog.Builder(it).show {
Could be a future improvement, but the standard AlertDialog is the one we currently use and the one which should be used.

2023-04-19 11:45 UTC, lukstbit requested changes

2023-04-19 11:45 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            MaterialAlertDialogBuilder(it).show {
Please use `AlertDialog.Builder`.

2023-04-19 11:45 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            }.create()
Using `create()` is an error because mDownloadCancelConfirmationDialog will be initialized with a different dialog and not the one which is being shown(the show{} extension method returns the AlertDialog.Builder used to create the dialog and not the dialog itself).

Strictly speaking the `show{}` extension should be modified to returned the dialog that is shown and not the builder. To keep this PR simple the change should be:

```
AlertDialog.Builder(it)
    .title(R.string.cancel_download_question_title)
    .// rest of the methods
    .show()
```

2023-04-19 19:18 UTC, n1snt commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            MaterialAlertDialogBuilder(it).show {
Hey, just wondering if there is any reason to go with AlertDialog over MaterialAlertDialogBuilder?
As much as I know MaterialAlertDialogBuilder extends AlertDialog & support for the latest Material Design specifications, So shouldn't it be the replacement?

2023-04-20 13:34 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            MaterialAlertDialogBuilder(it).show {
> So shouldn't it be the replacement?

Could be, we just decided for now to use AlertDialog as a first step to get rid of the library MaterialDialog. In the future it would be very easy to switch to MaterialAlertDialog if we settle on this(UI is very low on the list of priorities).

2023-04-20 13:36 UTC, lukstbit approved these changes
LGTM, thanks!

2023-04-22 13:29 UTC, ashutosh-kumar-kushwaha commented
Is there anything I still need to do to get this PR merged?

2023-04-22 14:13 UTC, david-allison approved these changes

2023-04-22 14:13 UTC, merged

2023-04-22 14:13 UTC, david-allison commented
Nope, thanks for the bump!

2023-04-24 03:56 UTC, david-allison commented
This will be reverted in https://github.com/ankidroid/Anki-Android/pull/13691