added a Help button in the notification if the migration fails
ankidroid/Anki-Android pull request #13636
Opened 2023-04-20 10:09 UTC by criticalAY

## Pull Request template

## Purpose / Description
shows a `Help` button in case migration fails and when clicked the user is taken to the application even if the application is closed using a pending intent and show a help dialog fragment

## Fixes
Completes a TODO

## How Has This Been Tested?
Tested on OnePlus nord ce, I tested it on the success notification as a dummy but the behaviour would be similar on the failing notification also here is the test screenshot
![Screenshot_49](https://user-images.githubusercontent.com/48384865/233335116-6bbcea9e-3c87-4235-88a5-ddb248be5188.jpg)

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-04-20 10:12 UTC, criticalAY commented
@david-allison I would like [this](https://github.com/orgs/ankidroid/projects/1?pane=issue&itemId=25747166) to be moved out as an issue

2023-04-20 21:34 UTC, david-allison commented
> @david-allison I would like [this](https://github.com/orgs/ankidroid/projects/1?pane=issue&itemId=25747166) to be moved out as an issue

#13641

2023-04-20 22:05 UTC, david-allison requested changes
Dialog looks good! Let's have this open a URL instead

I'll add a page shortly which we can link to

2023-04-21 14:24 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            val pendingHelpDialog = context.getSharedPreferences("migrationFailed", Context.MODE_PRIVATE)
I used this because of the HelpDialog if we plan to use the URL then we don't need all this for sure we can just use the broadcast receiver that would open the URL even if the application is closed/opening/paused

2023-04-21 15:03 UTC, criticalAY commented
I did go through the `openUrl`method but even if we want to use this we would need a service class/Broadcast Receiver/Activity  and an action to run this function which would make it a little messy so I think we should stick to the broadcast receiver
- Using an activity is complicated 
- making another service class makes no sense as we just want to launch the URL
- Best solution would be to use the Broadcast Receiver (which is the present commit) , I have tested it out when: The notification was shown and the app was running + when the notification was shown but the app was there in the background + finally when the app was killed and not running and the notification was shown. Works as expected in all three cases

2023-04-21 16:49 UTC, lukstbit commented
@criticalAY Is the extra BroadcastReceiver really needed? Couldn't the intent used in the PendingIntent be set with ACTION_VIEW and the data with an URI of the new url directly?

2023-04-21 17:16 UTC, criticalAY commented
> the intent used in the PendingIntent be set with ACTION_VIEW and the data with an URI of the new url directly?

Yes, we can do that also it would simplify the code further, Thanks!

2023-04-22 18:43 UTC, mikehardy commented
doc is live: https://ankidroid.org/storage-migration-error.html

2023-04-22 19:26 UTC, criticalAY commented
> doc is live: https://ankidroid.org/storage-migration-error.html

Already updated

2023-04-23 03:39 UTC, david-allison approved these changes
![](https://media.tenor.com/z0VTZtL2yQEAAAAM/awesome-reaction.gif)

2023-04-23 04:32 UTC, lukstbit approved these changes
Great, thanks!

2023-04-23 14:08 UTC, merged