Showing warning on FixedEditText instead of Toast
ankidroid/Anki-Android pull request #13632
Opened 2023-04-19 16:50 UTC by sanjaysargam

## Pull Request template

## Purpose / Description
It's better to show a warning on FixedEditText rather than Toast 

## Fixes
Fixes #13631

## Approach
Implementing a warning message on FixedEditText when user didn't enter anything in FixedEditText or the value is duplicate

## How Has This Been Tested?

Tested on Physical Device (Realme 9)

https://user-images.githubusercontent.com/65113071/233145117-79d5e4a0-1e05-429a-a026-87531f170ee9.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-04-19 17:20 UTC, david-allison reviewed
Thanks!

One potential issue, one further UX improvement to look into

2023-04-19 17:24 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +                .noAutoDismiss()
Ohh forgot to dismiss dialog in negative button
I'll do

2023-04-19 17:25 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +                        _fieldNameInput.error = getString(R.string.toast_duplicate_field)
Yeah!! That's better approach
will implement this

2023-05-02 18:38 UTC, david-allison requested changes

2023-05-02 18:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +                    }
We should disable the positive button if an error occurred.

2023-05-02 18:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +                    }
Previously: `uniqueName` performed two types of validation, now it only performs one

2023-05-02 18:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +            }
This seems to be duplicated code, see if it can be combined into a single class

2023-05-03 01:43 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +            }
In which file, this is need to be added

2023-05-03 01:49 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +                    }
uniqueName function checks two condition 
1. whether the input is empty or not
2. whether the input is already exists or not

These two validation, I already added

2023-05-17 17:22 UTC, david-allison requested changes

2023-05-17 17:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +        }
Could you explain this in a comment?

2023-05-17 17:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
>                      }
Add a TODO for this functionality to be extracted

2023-05-17 17:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +                .noAutoDismiss()
Why does this exist if the positive button is disabled when the input is invalid and both buttons dismiss the dialog?

2023-05-17 17:30 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +        }
Ok will add comment

2023-05-17 17:46 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
>                      }
Did you mean to add TODO in comment?

2023-06-08 18:36 UTC, closed without merging

2023-08-02 08:16 UTC, SanjaySargam commented
Hey @david-allison Please open this PR