added horizontalPadding and showing warning on FixedEditText
ankidroid/Anki-Android pull request #13662
Opened 2023-04-22 16:46 UTC by SanjaySargam

## Pull Request template

## Purpose / Description
It's better to have a horizontal padding and show a warning on FixedEditText rather than Toast

## Fixes
Related #13639

## Approach
Implementing a warning message on FixedEditText when user didn't enter anything in FixedEditText 
Adding horizontalPadding to FixedEditText

## How Has This Been Tested?

Tested on Emulator (Pixel 5 API 29)
[warn.webm](https://user-images.githubusercontent.com/65113071/233796478-a3b49af8-2808-432d-a4fd-ee73676037c5.webm)

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-06-28 16:01 UTC, mikehardy requested changes
with apologies, could you convert this to AlertDialog instead, using a padding style similar to here  https://github.com/ankidroid/Anki-Android/pull/13999/files ?

The other PR you made with horizontal padding conflicted directly with that one, and I think that #13999 style (Material -> Alert first) is the way to go if we are changing dialogs since it affects all the buttons / padding / dismissing logic

2023-06-28 16:46 UTC, SanjaySargam commented
> with apologies, could you convert this to AlertDialog instead, using a padding style similar to here https://github.com/ankidroid/Anki-Android/pull/13999/files ?

Ok I'll convert this first

2023-07-08 08:47 UTC, SanjaySargam commented
![image](https://github.com/ankidroid/Anki-Android/assets/65113071/8a48cd10-317d-453e-adbf-2297fe7de13a)

2023-08-01 05:03 UTC, lukstbit requested changes

2023-08-01 05:03 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
> +fun AlertDialog.Builder.customView(
These is already available so there's no need to include it again here.

2023-08-01 05:03 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
> +            val textWatcher = object : TextWatcher {
There's no need to create a TextWatcher manually, you should use one of the ktx extensions functions directly:

`modelNameEditText.doOnTextChanged { ... }`

2023-08-01 16:02 UTC, lukstbit requested changes

2023-08-01 16:02 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
> +                val name = text.toString().trim()
Please handle the nullability correctly, if text is null then calling toString() on it will return the string "null" on which you'll call trim(). Use `?.`:

`text?.toString()?.trim()`

and handle name being null in the if condition below.

2023-08-01 16:15 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
> +                if (name!!.isEmpty()) {
```suggestion
                if (name.isNullOrEmpty()) {
```

2023-08-01 16:50 UTC, lukstbit approved these changes

2023-09-04 05:07 UTC, lukstbit commented
With the new backend `ModelBrowser` was deleted so this PR became obsolete. 
Sorry.

2023-09-04 05:07 UTC, closed without merging