NF: clarify a constant name
ankidroid/Anki-Android pull request #13672
Opened 2023-04-23 05:19 UTC by Arthur-Milchior

Not very important, but I'm trying to debug my auto-sync error and saw this misleading constant name

2023-04-23 09:03 UTC, lukstbit approved these changes
Ok!

2023-04-23 09:03 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        private const val AUTOMATIC_SYNC_INTERVAL_IN_M: Long = 10
Not blocking, but is this really needed? Do you plan to use it in the future?

2023-04-24 02:00 UTC, david-allison requested changes

2023-04-24 02:00 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        private const val AUTOMATIC_SYNC_INTERVAL_IN_M: Long = 10
Agreed - inline. `M` is also ambiguous

2023-05-12 01:19 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        private const val AUTOMATIC_SYNC_INTERVAL_IN_M: Long = 10
So, I clearly was using it when auto sync was buggy, to locally sync more often and reproduce the bug without waiting 10 minutes.
But I agree that two constants is too much. 
I prefer to keep the one in minutes, because that's the one I actually care about. The MS one is an implementation details

2023-05-12 10:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        val automaticSyncIntervalInMS = AUTOMATIC_SYNC_INTERVAL_IN_MINUTES * 60 * 1000
`MIN` stood for minimum, not `minutes` previously. We lose this distinction.

2023-05-13 14:17 UTC, david-allison approved these changes

2023-05-13 17:53 UTC, mikehardy approved these changes
works for me

2023-05-13 17:53 UTC, merged