`sortedWith` extension function provided by Kotlin for collections tag
ankidroid/Anki-Android pull request #13730
Opened 2023-04-26 17:27 UTC by criticalAY

`sortedWith` extension function provided by Kotlin for collections that will allow us to sort a list with a custom comparator

## Pull Request template

## Purpose / Description
The implementation of the custom comparator function remains mostly the same,
The main change made in the sort() function is the use of the sortedWith function instead of mAllTags.sortWith

## Fixes
Fixes #12471

## Approach

## How Has This Been Tested?
Tested on API24/31/27

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-04-26 19:34 UTC, david-allison commented
To confirm: did this crash before the fix was in place?

2023-04-26 21:02 UTC, criticalAY commented
Yes

2023-04-26 21:21 UTC, david-allison requested changes
Quick question for cleanup, then let's go!

2023-04-26 21:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt
> +import org.slf4j.MDC.clear
These are unusual imports. Can I confirm that both are required?

2023-04-26 21:22 UTC, david-allison commented
> The main change made in the sort() function is the use of the sortedWith function instead of mAllTags.sortWith

Isn't the fix to use `.toList()` which uses a separate collection, and then replacing the collection rather than trying to mutate it in place?

2023-04-27 03:09 UTC, criticalAY commented
Sorry I forgot to update the template I made 2nd commit and this was from the earlier one

2023-04-27 03:17 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt
> +import org.slf4j.MDC.clear
They are not they were not removed automatically when I changed the code

2023-04-27 04:18 UTC, lukstbit approved these changes
I managed to reproduce this on lower versions(not newer versions however) and this seems to fix it. So thanks!

2023-04-27 04:19 UTC, criticalAY commented
> I managed to reproduce this on lower versions(not newer versions however) and this seems to fix it. So thanks!

Yes it was an API specific issue :)

2023-04-27 05:39 UTC, david-allison approved these changes
Clean! Thank you 🙏🙏🙏

2023-04-27 05:40 UTC, merged