Refactor `AggregateException`, making it translatable, & sligtly fix up the migration failed notification
ankidroid/Anki-Android pull request #13762
Opened 2023-04-29 23:35 UTC by oakkitten

## Purpose / Description
See #13671. Also, the migration failed notification was simply displaying `toString()` of the exception which wasn't adequate and wasn't what the migration failed dialog did.

## Fixes
Fixes #13667, supersedes and closes #13671

## Approach
* Move the code into app id-based package, also tests;
* Introduce the concepts of translatable strings and translatable exceptions;
* Make `AggregateException` translatable;
* Use big text style for the migration failed notification

https://user-images.githubusercontent.com/1710718/235327985-83594ee6-8393-4d03-84fb-ea1da1c1f508.mp4

Note: translatable strings/exceptions might be an overkill but this allows quickly making existing exceptions translatable. Just implement one method and make sure the UI calls through to `getUserFriendlyErrorText`. I'm not saying that is is the best idea ever, but certainly is *an* idea...

## How Has This Been Tested?

Tested on my device. Disclaimer: at the time I have not self-reviewed this as much as I'd like to.

## Checklist

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-05-01 14:53 UTC, BrayanDSO reviewed
The translation works fine. Only left a comment about an util

2023-05-01 14:53 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/KotlinUtils.kt
> +}
This method can be confusing, specially as a kotlin util, because by the name I expect that it does the same thing as `ifBlank` but with the condition inverted. But differently from `ifBlank` that returns the value included in the block if the CharSequence is blank, this doesn't return anything

And the code could be simplified on the places where you used this method if this returned a value

2023-05-01 18:47 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/KotlinUtils.kt
> +}
Fixed in a different way, hopefully

2023-05-01 18:54 UTC, oakkitten commented
Updated to address the review comment.

Low priority TODO self: when this is merged, deal with `com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData.DirectoryNotEmptyException`. We could remove it and catch `java.nio.file.DirectoryNotEmptyException` insted, re-raising a translatable `FailedToRemoveDirectoryThatIsNotEmpty` or something with that as a cause. (`java.nio.file.DirectoryNotEmptyException` *might* be note deletion-exclusive.) These *rare* errors may appear when files are modified during migration but also due to #13609.

2023-05-02 18:40 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/KotlinUtils.kt
> +}
Somewhat hard to read, but not worth blocking

2023-05-02 18:41 UTC, BrayanDSO approved these changes

2023-05-02 18:58 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/KotlinUtils.kt
> +}
Couldn't think of a better alternative (`ifNotBlank` was a very stupid idea). One would be something like `a.ifNullOrBlank { b.ifNullOrBlank { c.ifNullOrBlank { d } } }` but that's a bit too many braces for my liking and needs an extra extension method to boot (granted, a rather readable one)

2023-05-02 19:03 UTC, david-allison requested changes
This translation framework bypasses lint checks.

If this can be quickly fixed, then it should be. If it can't, then move it to a follow-up issue.

We've had numerous issues in the past when it comes to translated strings, and we need many guardrails in here as possible.

2023-05-02 19:14 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/Translations.kt
> +    }
I understand that you can e.g. pass a string with a wrong number of `%s`s here, but this should be an issue only for the commit author no? If you do and run the code, it will promptly crash

2023-05-02 22:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/Translations.kt
> +    }
I'd like to aim for the code not to crash.

* Previously:
    * An author would be warned in-IDE if making a mistake
    * A 'bad' PR would fail CI
    * Crashing code could not reasonably make it into the product
* Now:
   * Authors are no longer warned when working with strings
     * -> Longer feedback cycle
   * Reviewers need to take time to review string accesses
   * We risk a crash

2023-05-02 22:54 UTC, BrayanDSO requested changes

2023-05-02 22:54 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/Translations.kt
> +    }
Good point. Agreed with David here.

Automatic machine checks >>>>>>>>>>>>>>>>>>>>>>>>>>>>> human checks

2023-05-03 20:00 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/Translations.kt
> +    }
I mean the crash *is* a machine check, it'll happen every time the code is run. I just don't think this is a real world problem; to make the production crash,
* An author should submit the PR without running the code (merits rigorous spanking)
* The reviewer should approve the PR without running the code (merits regular spanking)
* The reviewer should approve the PR without noticing the mistake (forgivable but deserves a stern look)

This should not be in any way likely?

2023-05-03 22:18 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/Translations.kt
> +    }
I'll always prefer to remove cognitive burden from developers/reviewers and let machines deal with it automatically.

2023-05-05 13:43 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/Translations.kt
> +    }
Strongly disagree, and don't like the line of thought

People make PRs all the time without running the code in all scenarios for a variety of reasons.
Reviewers do not always run the code for a variety of reasons.
Reviewers approve things with mistakes regularly.

All of that is supported by objective evidence.

The failure mode is likely.

2023-05-05 14:58 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/Translations.kt
> +    }
I can't think of any valid non-exceptional reasons to not properly test-run new code.

P.S. There's also the requirement to provide screenshots with changed strings so that would also have to be ignored for a crash to occur.

2023-05-05 23:00 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/Translations.kt
> +    }
> If this can be quickly fixed, then it should be. If it can't, then move it to a follow-up issue.

What's the feasible resolution?

2023-05-06 13:44 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/Translations.kt
> +    }
I suppose one of these, in order of my preference:
* Improve PR submitting & reviewing standards, and write the lint check (I suppose taking `StringFormatDetector.java` as a hint)
* Improve PR submitting & reviewing standards, this will be good enough without the check
* Write the lint check
* `TranslatableString` is a very simple functional interface that takes a `context` argument, so we can just call `getString` on that, e.g. `TranslatableString { context -> context.getString(foo, bar) }`. While it is definitely usable, I'm not a fan as:
  * It's a bit wordier;
  * I can imagine someone using the wrong context.

  Actually, let me try an idea...

2023-05-06 16:23 UTC, oakkitten commented
Updated to allow saying

```kt
TranslatableString { getString(R.string.hello_s, "world") }
    .toTranslatedString(context)
```

2023-05-08 21:57 UTC, david-allison approved these changes

2023-05-09 16:13 UTC, BrayanDSO approved these changes

2023-05-13 17:45 UTC, mikehardy commented
This is a squash merge because of conflicts, I'll start string sync process now to get prepped for this

2023-05-13 18:28 UTC, merged