Fix UI being in bad state when storage migration fails
ankidroid/Anki-Android pull request #13774
Opened 2023-04-30 20:35 UTC by oakkitten

## Fixes
Fixes #13668

## Approach
See commit message. Ideally needs further and more extensive refactoring, but it just takes so much time.

## How Has This Been Tested?
NOT SUFFICIENTLY TESTED. A round of self-review is required and that will have to wait until tomorrow at least, hence a draft.

## Checklist
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-05-01 14:58 UTC, BrayanDSO commented
I'll wait until this is undrafted and split into more commits before reviewing.

2023-05-01 16:53 UTC, oakkitten commented
Updated with very minor changes; edited the first comment with a little more details.

2023-05-02 23:00 UTC, david-allison requested changes
Partial review. On me to continue.

This very likely need to be split out into separate commits. There's a lot going on here.

2023-05-02 23:03 UTC, david-allison requested changes

2023-05-02 23:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
> +                )
nit: this feels more complex

2023-05-02 23:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.kt
> +fun SharedPreferences.getOrSetLong(key: String, defaultValue: Long): Long {
This makes the signature inconsistent with the above

2023-05-03 13:54 UTC, mikehardy commented
Marking as needs review as comments indicate review is ongoing, but also marking as needs author reply because some things are already actionable

2023-05-03 19:53 UTC, oakkitten commented
To address the last review I'll just remove (hopefully tomorrow) the code related to refactoring `MigrationService`, that was a result of a mess in my git and I was too lazy to get rid of it (sorry). (But why shouldn't we be using spaces in preference keys?)

2023-05-05 10:36 UTC, oakkitten commented
Updated to remove changes unrelated to the PR. And to remove spaces in preference keys, although I still don't know what's the problem with that.

2023-05-08 23:03 UTC, david-allison requested changes
This view of the error significantly differs from the notification. We should provide users help here, in case "try again" fails.

2023-05-08 23:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    }
This functionality significantly differs from: https://github.com/ankidroid/Anki-Android/blob/d1f8672e2f43b38ac6dac8618378efa83fea0815/AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt#L265-L277

Especially as it does not provide the user an avenue to get help

2023-05-09 16:38 UTC, BrayanDSO reviewed
Overall looks good, but I ressonate with David about the help option

2023-05-09 18:59 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    }
I didn't include that functionality here as it's included in the Migration failed dialog, which is shown along with the notification

https://github.com/ankidroid/Anki-Android/blob/4120c6aa46720a6096bab8234c986b048391fec6/AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/ActivityAgnosticDialogs.kt#L70-L85

You think we need help here as well? And the traceback?

2023-05-10 12:38 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    }
At least a Help button yeah, so they can know what to do with the shown error in case it persists and/or they dismissed the failed dialog/notification

2023-05-12 04:13 UTC, Arthur-Milchior reviewed
thanks a lot for this change. Looks good to me. Main request is really: if you were able to record the usage of this new version, new dialog, that would help a lot understand in which context it occurs.

2023-05-12 04:13 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
> +            object CollectionIsInPublicFolderButWillRemainAccessible : NotNeeded
I believe this one would benefit from a comment.
I assume "remain accessible" means that we are not using play store, so it remains accessible even after uninstall/reinstall (assuming the same flavor).
Because as long as you just update, it should always remain accessible.

2023-05-12 04:13 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
> +    fun migrationIsOngoing() = ScopedStorageService.userMigrationIsInProgress(preferences)
I'm sorry, but I'm confused. What's the point of redefining those functions.
I could understand `val migrationIsOngoing = ScopedStorageService.userMigrationIsInProgress(preferences)`, to make the `if` more readable. But I admit I don't get the point of creating a new function with a single usage.

I may understand that you want to remove all use of `userMigrationIsInProgress` and only use `getMediaMigrationState`. But, for example, `isLegacyStorage` seems natural to use, and I don't see a point of removing it. You may want to care about this even outside of migration strictly speaking

2023-05-12 10:53 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            is MediaMigrationState.NotOngoing.Needed -> {
You do need `is` for classes, but you are right that it can be ditched as `Needed` is also an object. However I prefer using `is` instead of `==` with sealed classes/interfaces at all times—for consistency, and for a little easier refactoring, e.g. if you were to change `MediaMigrationState.NotOngoing.Needed` to `MediaMigrationState.NotOngoing` you'd need to add back the `is` if you weren't using it in the first place.

2023-05-12 10:56 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
> +     * DEPRECATED. Use either [com.ichi2.anki.services.getMediaMigrationState], or
It is okay to continue using deprecated things.

I think it's too late for a full refactor, but in case someone makes a smaller refactor they can take hints from this deprecation.

2023-05-12 11:20 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
> +            object CollectionIsInPublicFolderButWillRemainAccessible : NotNeeded
Not sure if this needs a comment. This is a rather high-level enum and the consumer of it should not care for what reasons the collection is going to remain accessible. This should read “Migration is not needed, as the collection will remain accessible even though it is in a public folder.” I didn't suffix this with `AfterReinstall` because

* the name is too long already
* the detail about updating without reinstalling retaining access is too low level for this enum
* there are perhaps ways of losing access such as user upgrading their OS so you just can't have a perfectly precise name

If the reader is interested in the implementation detail, the implementation does have a comment

2023-05-12 11:29 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
> +    fun migrationIsOngoing() = ScopedStorageService.userMigrationIsInProgress(preferences)
* To make the `if` more readable. Using `val` would compute everything even though it might be not needed, `val get()` is illegal in local functions, so `fun`
* `isLegacyStorage` is a bad name (we decided to use the terms “app-private folder“ & “public folder”) and should probably be replaced with `isInsideDirectoriesRemovedWithTheApp` (or the latter should be renamed into `isInsideAppPrivateFolders`).
* `collectionWillBeMadeInaccessibleAfterUninstall` is only used once here and can be inlined. Didn't do it right away as I wanted a smaller diff

2023-05-12 20:17 UTC, BrayanDSO approved these changes

2023-05-12 20:18 UTC, BrayanDSO commented
I'm interpreting David's comment as an approval. Didn't see nothing breaking or major on Arthur's comments. Pending merge

2023-05-12 23:13 UTC, david-allison approved these changes
Review was dismissed: my comment was handled, but I wasn't at a computer to re-review.

I've now had time to look through. Looks good to me. Needs a follow up to move the TODOs to the board.

2023-05-13 18:17 UTC, mikehardy commented
This was a one-commit change, and had a conflict - in those cases for speed, doing the github web UI "resolve conflicts" (which adds a merge commit to the branch) is functionally equivalent in my opinion to pulling branch / rebase-with-interactive-de-conflict / re-push, because a squash merge after the merge commit is still just one commit

So I just did the resolve conflicts / merge commit thing here and if CI goes green I will merge this once string sync is done (string sync in process....)

2023-05-13 18:32 UTC, mikehardy commented
Took another conflict when #13762 went in, apparently user friendly error text util moved in that PR and this PR used it.
Did another de-conflict merge commit, these are trivial fixups, if CI goes green it's good

2023-05-13 18:57 UTC, merged