Resolve NeedsTests annotations in LoginActivity.kt
ankidroid/Anki-Android pull request #13780
Opened 2023-05-01 18:01 UTC by tomaszgarbus

This is my first contribution, so I'm looking forward to getting some feedback before getting deeper into the codebase!

This is a clone of https://github.com/ankidroid/Anki-Android/pull/13759 (see also comment history there) because I wanted to move these changes off of my main branch.

Tests flow as follows:
* mock isLoggedIn() (we have mockk mockStatic I think) to return true
* start LoginActivity
* assert that the Lifecycle state of LoginActivity is finished/destroyed(as there's no reason to show this activity when the user is logged in). Also test the Activity result codes.

2023-05-02 23:30 UTC, david-allison reviewed
Looks great, thanks.

One 'hard' nitpick regarding calling `.close()` on scenarios once completed. 

One implementer's choice which cleans up the preference modification code

2023-05-02 23:30 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/LoginActivityTest.kt
> +        val scenario = launchActivityForResult(LoginActivity::class.java)
ActivityScenario is `AutoCloseable`. Use `launchActivityForResult(LoginActivity::class.java).use { scenario -> ... }`

From the docs: 

> `ActivityScenario` does't clean up device state automatically and may leave the activity keep
> running after the test finishes. Call `close()` in your test to clean up the state or use
> try-with-resources statement. This is optional but highly recommended to improve the stability of
> your tests. ~~Also, consider using `androidx.test.ext.junit.rules.ActivityScenarioRule`.~~

Note: don't use the suggested `Rule` due to the setup/teardown you're performing with the preferences

2023-05-02 23:30 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/LoginActivityTest.kt
> +            .apply()
* `RobolectricTest` exposes `getPreferences` as a helper method
* Kotlin provides a `.edit { }` extension method

This can be converted to:

```kotlin
        getPreferences().edit { putString(SyncPreferences.HKEY, "anything not null") }
```

2023-05-02 23:34 UTC, david-allison requested changes

2023-05-02 23:34 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/LoginActivityTest.kt
> +package com.ichi2.anki
Please add a GPL compatible copyright header.

```
/*
 *  Copyright (c) 2023 NAME <email>
 *
 *  This program is free software; you can redistribute it and/or modify it under
 *  the terms of the GNU General Public License as published by the Free Software
 *  Foundation; either version 3 of the License, or (at your option) any later
 *  version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT ANY
 *  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 *  PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with
 *  this program.  If not, see <http://www.gnu.org/licenses/>.
 */

```

@mikehardy - FYI: This one got past the lint check

2023-05-03 19:28 UTC, tomaszgarbus commented
No idea why the unit test run was cancelled after 40m. @david-allison would you mind retriggering the checks? I'm assuming I don't have permissions to do it.

2023-05-03 19:29 UTC, tomaszgarbus reviewed
Addressed the suggestions from the previous version.

2023-05-04 17:23 UTC, BrayanDSO approved these changes
LGTM. Left only a nit

2023-05-04 17:23 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/LoginActivity.kt
> +
nit: remove this line

2023-05-04 20:39 UTC, tomaszgarbus commented on AnkiDroid/src/main/java/com/ichi2/anki/LoginActivity.kt
> +
Done.

2023-05-07 05:15 UTC, lukstbit approved these changes
LGTM and all previous comments were addressed. Thank you for contributing!

2023-05-07 05:17 UTC, merged