Moved cursor to end in NumberRangePreferenceCompat
ankidroid/Anki-Android pull request #13800
Opened 2023-05-05 03:53 UTC by SanjaySargam

## Pull Request template

## Purpose / Description
It's become inconvenient for the user to relocate the cursor to end every time

## Fixes
Fixes #13799

## Approach
called `setFocusAndOpenKeyboard()` function which is already there in AndroidUiUtils

## How Has This Been Tested?

Tested on Emulator (Pixel 5 API 29)

https://user-images.githubusercontent.com/65113071/236374491-d1ae3dce-4821-4abd-952c-687f86d5c8b8.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-05-05 15:08 UTC, lukstbit reviewed
There's no need to create a method for one line of code. Inline the call.

2023-05-05 15:10 UTC, SanjaySargam commented
> There's no need to create a method for one line of code used once. Inline the call.

Ok

2023-05-05 23:46 UTC, BrayanDSO requested changes

2023-05-05 23:46 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt
> +            setFocusAndOpenKeyboard(editText) { editText.setSelection(editText.text.length) }
`super.onBindDialogView()` already does this (hence why default text preferences put the cursor at the ended), but the selection is changed after the inputType or the filters are changed (I haven't checked which or if both)

So I propose something like this:
```kotlin
        override fun onBindDialogView(view: View) {
            editText = view.findViewById(android.R.id.edit)!!

            // Only allow integer input
            editText.inputType = InputType.TYPE_CLASS_NUMBER

            // Clone the existing filters so we don't override them, then append our one at the end.
            editText.filters = arrayOf(*editText.filters, InputFilter.LengthFilter(numberRangePreference.maxDigits))

            super.onBindDialogView(view)
        }
```

2023-05-06 08:18 UTC, BrayanDSO approved these changes

2023-05-07 04:22 UTC, lukstbit approved these changes

2023-05-07 04:22 UTC, merged