NF: remove JvmStatic
ankidroid/Anki-Android pull request #13823
Opened 2023-05-09 02:58 UTC by Arthur-Milchior

Tests pass locally

2023-05-15 11:56 UTC, mikehardy requested changes
seems fine in general, one question if it is possible to convert one more temporary variable to inline to match style of other conversions

2023-05-15 11:56 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt
>          plotSheet.textColor = ColorWrap(textColor)
Why not change this one as well 🤔 ? Seems like the same construction that you've modified in the other spots

2023-05-15 14:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt
>          plotSheet.textColor = ColorWrap(textColor)
No idea. Probably missed it

2023-05-15 15:51 UTC, david-allison reviewed
Nit: Some of these read as more complicated

Defining `View.setBackgroundColorFromAttr(attr)` would help simplify matters.

Not going to enforce changes. Implementer's choice

2023-05-15 15:51 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.kt
> +        val textColor = String.format("#%06X", 0xFFFFFF and getColorFromAttr(webView.context, R.attr.textColor)) // Color to hex string
This reads worse - lots of complexity on one line

2023-05-15 15:51 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                    MenuItemCompat.setIconTintList(m, ColorStateList.valueOf(getColorFromAttr(this, R.attr.navDrawerItemColor)))
nit: somewhat harder to read

2023-05-15 15:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.kt
> +        val textColor = String.format("#%06X", 0xFFFFFF and getColorFromAttr(webView.context, R.attr.textColor)) // Color to hex string
I expected to do it in a different PR, but fine

2023-05-15 16:15 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.kt
> +        val textColor = String.format("#%06X", 0xFFFFFF and getColorFromAttr(webView.context, R.attr.textColor)) // Color to hex string
Done

2023-06-04 03:06 UTC, Arthur-Milchior commented
Rebased now that preliminary commit is merged

2023-06-25 04:37 UTC, closed without merging