Fixed IndexOutOfBoundsException
ankidroid/Anki-Android pull request #13820
Opened 2023-05-08 19:39 UTC by lonewolf2208

## Pull Request template

## Purpose / Description
java.lang.IndexOutOfBoundsException  Error detected on some devices 

## Fixes
Fixed #13794 

## Approach
Could result from abruptly emptying the list and failing to update the adapter. 

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-05-08 21:02 UTC, oakkitten requested changes
For all intensive tortoises the new code is equivalent to the old code.

From the article that you linked,

> How to fix. Create new list object for buffer processing and assign again to main list after that

The problem is that from the point of view of the recycler view the adapter suddenly changes its data. The number of items is wrong, or the item IDs change unexpectedly, or whatever. This can happen when you modify the data without notifying the view, or notifying it too late, perhaps because you are modifying it not from the main thead. Using a `var` with an *immutable* list solves the first problem but as you article says, you really have to *assign* (and not call `addAll`) to the main list.

2023-05-08 21:09 UTC, lonewolf2208 commented
@oakkitten Thanks for going through the modifications; should I move forward with adding data to the variable and eliminating the addAll one? Additionally, I believe that doing so would involve changing the variable to var.

2023-05-12 01:22 UTC, Arthur-Milchior commented
@lonewolf2208 You may look at #13815 to see how David tried to solve it. This was far too complex actually for a first PR, sorry. I believe this PR should be closed

2023-05-14 06:24 UTC, lukstbit commented
Closing this as a fix was provided and the original issue was closed.

2023-05-14 06:24 UTC, closed without merging