CardBrowser is not getting bold
ankidroid/Anki-Android pull request #13830
Opened 2023-05-10 05:57 UTC by SanjaySargam

## Pull Request template

## Purpose / Description
This issue was introduced due to #13198

## Fixes
Fixes #13818

## Approach
Changed `com.google.android.material:material` to 1.7.0

## How Has This Been Tested?

Physical Device

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-05-10 11:20 UTC, david-allison reviewed
I don't understand the video.

The bolding feature was added in 1.8: https://github.com/material-components/material-components-android/releases/tag/1.8.0

> Updated active text label to use a bold typeface. (https://github.com/material-components/material-components-android/commit/b1bd580d7e6a587f88da5c034107bed1e77cd26a)

So the video should show no bolding if we've reverted the library.

2023-05-10 11:23 UTC, david-allison commented
Maybe also fixes https://github.com/ankidroid/Anki-Android/issues/13831#issuecomment-1541906608

2023-05-10 11:23 UTC, david-allison requested changes

2023-05-10 11:23 UTC, david-allison commented on AnkiDroid/build.gradle
> +    implementation 'com.google.android.material:material:1.7.0'
If you are reverting, leave a comment to explain why

2023-05-10 13:24 UTC, SanjaySargam commented
> EDIT: Ignore this comment - problem with video resolution

Yes, the video is not clear because of low quality.
So, here is the video with better quality

https://github.com/ankidroid/Anki-Android/assets/65113071/887c7ad3-fa66-4661-9328-ee383abeee39

2023-05-10 15:50 UTC, SanjaySargam commented
This PR also fixes #13375 

Tested on Emulator

2023-05-10 22:45 UTC, BrayanDSO approved these changes

2023-05-10 22:46 UTC, merged

2023-05-11 01:17 UTC, snowtimeglass commented
Thank you for the fix!