Adding an advanced options to add media
ankidroid/Anki-Android pull request #13854
Opened 2023-05-15 04:25 UTC by Arthur-Milchior

This will add to manually test migration of media.

Fixes #13480 from @oakkitten

2023-05-15 08:00 UTC, david-allison submitted a review, later dismissed
Lint is failing

Primary issue:

Needs to be in "Developer Options" rather than "Advanced"

Aside: There's little signal if we're testing the same count/size of files every time. Might as well be an apkg

2023-05-15 12:31 UTC, oakkitten commented
I think this needs to be a more easily accessible action, e.g. a *main menu* option to “Create a fake deck” or something with the options to set:

* Collection location
* Number and sizes of media files to generate (e.g. 10-20 files of 1-10MB each)
* Whether or not some media files are referenced to by cards or not
* Maybe something else?

Also I'd love to have the option to crash during migration

Also I'd love to have the option to reset migration state

2023-05-15 18:00 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
> -                (activity as AnkiActivity).dismissAllDialogFragments()
Visibly something remaining from a different PR. Strange

2023-05-15 18:36 UTC, Arthur-Milchior commented
If that's okay with you, @oakkitten, this PR will deal with media creation. 

I am not sure what you mean by "main menu".
The trouble I had with putting this action in DeckPicker is that I really don't want that a user find it by accident. With developer or advanced, there is no risk here.
I could ensure it appears only if you are in DEBUG mode, but that's not great to test the version on the play store then

2023-05-15 19:54 UTC, oakkitten commented
The overflow menu in deck picker could have a menu item “Debug” opening a submenu with some options. It could be enabled either via `DEBUG` or via a setting in Developer options, e.g. “Show debug menu”

> If that's okay with you, @oakkitten, this PR will deal with media creation.

I mean, I don't always fill the media folder with random files when testing. The `MigrateUserData` task will migrate *some* files so you will see if it is broken at all. I would like to be able to quickly set the collection to a public storage though, that's more useful. And I would like to be able to reset the migration—if it fails, and keeps failing, you can't quite escape the loop (by the way, we do not have a way of dealing with this!) and the only way to resolve the situation is to ”Delete everything” in “Manage space activity”, which has an additional effect of voiding all of the permissions including the ones you must set via adb/some advanced preferences.

P.S. I imagine that the settings in the “Create a fake deck” dialog would be saved into shared preferences.

2023-05-15 23:08 UTC, Arthur-Milchior commented
So, right now, I put the action in the developer settings. If needed it can be moved later. 
In particular, I don't expect to need to use it that much that putting it in main instead of in settings will change that much.
I suggest we add more option to help manual test later, in other PR, so that at least this can be used.

2023-05-20 12:44 UTC, BrayanDSO requested changes

2023-05-20 12:44 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
> +         * Debugging section
the section isn't called "Debugging".

2023-05-20 12:44 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
> +                setMessage("You'll add $numberOfFilePreference files with no meaningful content, potentially overriding existing files. Do not do it on a collection you care about.")
$numberOfFilePreference will print the title of the preference

2023-05-20 12:44 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
> +                        showSnackbar("$i files added.")
can't see that snackbar showing up

2023-05-20 12:44 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
> +                    val f = File.createTempFile("00$i", suffix)
this gives me an IDE warning, either suppress (with a justification comment) it or handle with it

2023-05-20 12:44 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/preferences.xml
> +    <string name="pref_fill_collection_size_file">fillCollectionSizeFile</string>
nit: put these together with the other dev options keys, i.e. below `<!-- Developer options -->` in this same file

2023-05-20 12:44 UTC, BrayanDSO commented on AnkiDroid/src/main/res/xml/preferences_dev_options.xml
> +        android:title="Create medias"
I believe that media is a plural word.

2023-05-20 12:54 UTC, david-allison commented on AnkiDroid/src/main/res/values/preferences.xml
> +    <string name="pref_fill_collection_size_file">fillCollectionSizeFile</string>
We don't need any strings. Keep the debug settings in English

2023-05-20 12:55 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/preferences.xml
> +    <string name="pref_fill_collection_size_file">fillCollectionSizeFile</string>
these are the keys constants, not strings

2023-05-20 13:06 UTC, david-allison commented on AnkiDroid/src/main/res/values/preferences.xml
> +    <string name="pref_fill_collection_size_file">fillCollectionSizeFile</string>
That's what I get for reviewing on my phone, thanks!

2023-06-06 20:07 UTC, BrayanDSO approved these changes
Took the liberty to fix myself the issues I found to avoid getting stale, since this is pretty useful.

2023-06-08 13:27 UTC, lukstbit approved these changes
LGTM
Note that I added some minor changes to improve the names used and to fix an issue with the last toast shown.

2023-06-08 14:28 UTC, merged