Add option to trigger crash during migration
ankidroid/Anki-Android pull request #13861
Opened 2023-05-16 00:59 UTC by Arthur-Milchior

As requested in #13854

2023-06-04 10:57 UTC, Arthur-Milchior commented
@lukstbit I'm sorry but I don't understand your tag. There is no comment on question, how could I reply to anything.
@oakkitten, would you mind commenting, as I was trying to follow the idea you mentioned.

2023-06-04 12:04 UTC, oakkitten commented on AnkiDroid/src/main/res/values/preferences.xml
> +    <string name="crash_during_essential_migration">crashDuringMainMigration</string>
You've got “essential migration” and “main migration” in one line. I **strongly** suggest reusing terminology that we already have, throughout. Namely, “essential file migration”. So I'd go with “Simulate error during essential file migration”.

Change related names accordingly

2023-06-04 12:05 UTC, lukstbit commented
I add that label because something is preventing the review, either tests are failing or there is a merge conflict(I think this had a merge conflict when I initially looked at it). That label becomes a notice for me(and I hope others) that it isn't yet ready for review so I don't repeatedly check it out.

2023-06-04 15:02 UTC, Arthur-Milchior commented
@lukstbit May I advise checking the nature of the merge conflict?
You're right, I just had to rebase to resolve one. But, given the merge conflict was related to two imports appearing at the same place in the list of imports, I suspect that the code was ready for review. And even if you wanted to execute it to test locally, the resolution was a non-brainer

2023-06-04 15:05 UTC, Arthur-Milchior commented
@oakkitten reworded/renamed

2023-06-06 19:40 UTC, oakkitten requested changes
I suggest using the phrase “Simulate error during essential file migration” (without the `s` and the period), as well as renaming *all* related keys and string values and constants and variables to mirror this phrase. Using a single phrase for everything greatly reduces confusion **and** it's so easy to do (and easy to search and everything), besides, you don't have to think, just rename everything related.

2023-06-07 19:27 UTC, Arthur-Milchior commented
Done.

2023-06-09 21:23 UTC, BrayanDSO approved these changes
I don't effectively care about the names and the keys. This is a dev option and we are post the deadline, so it only matters if it works. So I'm approving.

Reviewers' note: avoid merging this before #13969 as it will generate conflicts and #13969 is way over higher priority than this, so I'm even adding the "Blocked by dependency" label

2023-06-09 21:23 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/preferences.xml
> +    <string name="simulate_error_during_essential_file_migration">crashDuringEssentialMigration</string>
```suggestion
    <string name="simulate_error_during_essential_file_migration_key">crashDuringEssentialMigration</string>
```

2023-06-09 21:23 UTC, BrayanDSO commented on AnkiDroid/src/main/res/xml/preferences_dev_options.xml
> +        android:title="Migration crashes">
```suggestion
        android:title="Crash migration">
```

2023-06-09 21:23 UTC, BrayanDSO commented on AnkiDroid/src/main/res/xml/preferences_dev_options.xml
> +            android:title="Simulate error during essential file migration"
```suggestion
            android:title="Simulate error during essential files migration"
```

2023-06-09 21:50 UTC, oakkitten commented on AnkiDroid/src/main/res/xml/preferences_dev_options.xml
> +        android:title="Migration crashes">
This doesn't crash the app

2023-06-09 21:51 UTC, oakkitten commented on AnkiDroid/src/main/res/xml/preferences_dev_options.xml
> +            android:title="Simulate error during essential file migration"
Not sure about this one, it's “bird migration” not “birds migration”, but you can always say “migration of essential files”

2023-08-16 17:36 UTC, closed without merging