fix: save note NullPointerException
ankidroid/Anki-Android pull request #13885
Opened 2023-05-17 17:36 UTC by SanjaySargam

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes #13874

## Approach
make `dupeOrEmpty()` suspend function

## How Has This Been Tested?

Tested on Emulator ( Pixel 5 API 33 )

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-05-17 18:06 UTC, david-allison requested changes

2023-05-17 18:06 UTC, david-allison commented
CI fail

2023-05-18 05:45 UTC, Arthur-Milchior commented
Did you try to build it locally? Still does not compile, and it should not.

2023-05-18 06:02 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
> +            val fields = col.db.queryStringList(
I fear I was not clear. You should not use `col`. Instead, `withCol` provides `col` as the receiver of methods. So `db` is implicitly interpreted as `col.db` for example.

It probably does not matter, as, most of the time, `col` and the collection provided by `withCol` are the same collection. But if the collection was closed for whatever reason, both objects can differ; in which case you're using a value that is not valid anymore

2023-05-18 06:19 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
> +            val fields = col.db.queryStringList(
```suggestion
            val fields = this.db.queryStringList(
```
Can I use like this? Here this belongs to `withCol`

2023-05-18 14:08 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
> +            val fields = col.db.queryStringList(
The receiver of `withCol` is a `Collection`.

@Arthur-Milchior defined `collection.col` in e90c2dd64066325c52fa13154a9c934927c49fd7, which means that `withCol { col.db }` works using the receiver's `col` rather than the Activity's.

(@Arthur-Milchior, I fear I don't understand the issue here, given the definition of `collection.col`): did we standardise on not using `col` when performing to coroutine migration?

https://github.com/ankidroid/Anki-Android/blob/82951b853bb04329ffac2e2416cd9ba53732aa69/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt#L2524-L2529

2023-05-19 00:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
> +            val fields = col.db.queryStringList(
My bad, I totally forgot it. So I guess `col` was right. Seems not intuitive in the first place; but I guess ideally, `Card` and `Note` should not keep `col` anyway, and once it's resolve, there won't be ambiguity

2023-06-09 08:15 UTC, Arthur-Milchior commented
@SanjaySargam Do you intend to rework this PR?

2023-06-09 08:23 UTC, SanjaySargam commented
Yes 
Could you plz tell me what changes I should make?

2023-06-30 09:36 UTC, closed without merging