Queue in sched
ankidroid/Anki-Android pull request #13896
Opened 2023-05-20 03:28 UTC by Arthur-Milchior

Some cleaning done during debugging a nullptrexception

2023-06-03 07:06 UTC, Arthur-Milchior commented
While it's indeed clean-up, @BrayanDSO, I did it because ensuring that the variable is non-null simplify some more complex code from #13936; which itself will, hopefully, help reduce the number of crash due to access to null collection.

So, I believe that it's still worth reviewing it, especially since it's a small PR

2023-06-03 08:02 UTC, lukstbit requested changes

2023-06-03 08:02 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/CardQueue.kt
> +        queue.removeIf { card -> card.id == cid }
The two calls are not equivalent, `LinkedList.remove()` removes the first occurrence of the passed element while `LinkedList.removeIf {}` will remove **all** elements from the list based on the condition.

2023-06-04 03:21 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/CardQueue.kt
> +        queue.removeIf { card -> card.id == cid }
I agree with you. However, the queue should never have the same card twice, so it should not be an issue. 
Indeed, there is a single cases in which elements are added, it works as follow
* the list is cleared
* we query the database for a list of cards
* we add in batch all of the result from the query


So if at any time we have a duplicate in the collection, it means that there was two cards with the same id in the database. Since it's a primary key in sqlite, I doubt it's actually possible

2023-06-04 06:05 UTC, lukstbit approved these changes
LGTM

2023-06-10 10:09 UTC, BrayanDSO approved these changes

2023-06-10 10:09 UTC, merged