Changed Material Dialog with Alert Dialog for ModelBrowserContextMenu.kt
ankidroid/Anki-Android pull request #13910
Opened 2023-05-24 16:06 UTC by Prince-kushwaha

## Purpose / Description
Replaces usages of MaterialDialog with AlertDialog in ModelBrowserContextMenu.kt
## Fixes
Related to #13315 

## How Has This Been Tested?
Open each one of the changed dialogs on their respective preferences

2023-06-02 03:06 UTC, Prince-kushwaha commented
@lukstbit  can you review this PR

2023-06-02 06:19 UTC, lukstbit requested changes

2023-06-02 06:19 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelBrowserContextMenu.kt
> +        return AlertDialog.Builder(requireActivity()).show {
You can't use `show {}`(which will create and display a new dialog) and `create()`(which will also create a new dialog) together as you'll end up with two dialogs and will cause crashes in certain scenarios. 

Use `apply {}` instead of `show {}` so there's only one dialog being created.

2023-06-07 12:29 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelBrowserContextMenu.kt
> +        return AlertDialog.Builder(requireActivity()).show {
ok i fixed that

2023-06-07 16:40 UTC, lukstbit approved these changes

2023-06-09 15:11 UTC, BrayanDSO approved these changes

2023-06-09 15:11 UTC, merged