immediate dialog after selecting note type
ankidroid/Anki-Android pull request #13916
Opened 2023-05-26 17:34 UTC by SanjaySargam

## Pull Request template

## Purpose / Description
While adding a note type from manage note types, I am supposed to choose the note type, and after choosing I again need to press the Ok button and then it opens a new dialog for naming the note type
Obviously, if I chose note type, I meant to add note type.

## Fixes
Fixes #13914

## Approach
1. Remove the positive button
2. set `waitForPositiveButton = false` in `listItemSingleChoice() `so that I do not wait for the OK button to be clicked

## How Has This Been Tested?

Tested on Physical Device ( Realme 9 )

https://github.com/ankidroid/Anki-Android/assets/65113071/967f444e-a74a-4a7f-838a-de246d9ea6f2

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-05-29 16:22 UTC, lukstbit approved these changes

2023-05-29 16:30 UTC, BrayanDSO requested changes

2023-05-29 16:30 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
> +                dialog.dismiss()
Do we need this line? I've seen other uses of `waitForPositiveButton` without it, hence why I'm asking. If it isn't necessary, a comment explaining why sould ne nice.

2023-05-30 13:28 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
> +                dialog.dismiss()
`dialog.dismiss()` 
This line is needed. Without these, the outer dialog is not closed as it is closing in previously after creating note type

2023-05-30 20:42 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
> +                dialog.dismiss()
Thanks for the explaining

2023-05-30 20:42 UTC, BrayanDSO approved these changes

2023-05-30 20:42 UTC, merged