Remove sched
ankidroid/Anki-Android pull request #13940
Opened 2023-06-03 15:43 UTC by Arthur-Milchior

I remove members of type Schedulers in classes outside of test (except Collection).
This will ensure that all access to a scheduler is through `col` and ultimately in `withCol`.

As discussed in #13936

2023-06-05 10:59 UTC, BrayanDSO approved these changes
LGTM

2023-06-13 04:38 UTC, lukstbit requested changes
This took come conflicts from other recently merged PRs, there's also the issue below...

2023-06-13 04:38 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +        launchCatchingTask {
This is not going to work as intended.
The `launchCatchingTask` builder uses the activity lifecycle coroutine scope which will get created with the activity and will be cancelled in onDestroy(). So this code launches a coroutine in the method where the scope is cancelled(I don't think it's going to get executed at all).
Here, we need a scope which is greater than the activity coroutine scope, like a scope defined at the application level(or maybe just leave it as it is now, in hope for a better architecture when we move to the new backend which will not require this type of cleanups in onDestroy()).

2023-07-04 05:37 UTC, closed without merging

2023-07-04 08:10 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +        launchCatchingTask {
Thanks. 

Actually, that seems like a big deal. Because, that's a problem that seems to occur even when we do thing such as editing a note, or reviewing the last note of a deck. 
I did a quick correction here, but now that you note it, I guess a lot of `launchCatchingTask` should run on GlobalScope