feat: Slider preferences
ankidroid/Anki-Android pull request #13960
Opened 2023-06-06 19:15 UTC by BrayanDSO

## Purpose / Description
I had this branch from back the time of my GSoC project, but didn't finish it. Looking at #13957 remembered me of that so I finished it before I forgot to do it again.

The main reason of this PR is to replace the `SeekBarPreferenceCompat` usages with something better. The main issue with it is that it has an unnecessary tap to show a dialog to configure it and it looks bad.

The initial alternative would be to replace it with some `androidx.preference.SeekBarPreference` but they look very simple and aren't very customizable, so I built a new preference class based on the material Slider to use instead

## Approach
See the description above

## How Has This Been Tested?

SDK 29 emulator

https://github.com/ankidroid/Anki-Android/assets/69634269/871d7af3-4404-4f65-b8fe-4430aac6555a

https://github.com/ankidroid/Anki-Android/assets/69634269/c3e47ee5-8ff7-49b5-aa3c-06179fdc916e

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-06-12 12:52 UTC, lukstbit requested changes
I like the new UI, left some minor issue to check out.

2023-06-12 12:52 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/preferences/SliderPreference.kt
> +                throw Exception("value $value should be between the min of $valueFrom and max of $valueTo")
I think IllegalArgumentException should be used here.

2023-06-12 12:52 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/preferences/SliderPreference.kt
> +    private lateinit var slider: Slider
There's no need for this property, it's only used in onBindViewHolder().

2023-06-12 12:52 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/preferences/SliderPreference.kt
> +    private var displayValueTextView: TextView? = null
The same as above, the `onBindViewHolder()` mentions that the views should not be referenced outside of the method.

Wouldn't be simpler and safer to inline the `updateValueDisplayText()` method inside `onBindViewHolder()` and then simply call `notifyChange()` in the value setter?

2023-06-12 12:52 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/preferences/SliderPreference.kt
> +            displayValueTextView?.text = if (displayFormat != null) {
Could be inline to avoid the !! : displayFormat?.let {..}

2023-06-12 12:52 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/preferences/SliderPreference.kt
> +        slider = holder.findViewById(R.id.slider) as Slider
Your choice, maybe an `apply{}` to avoid the local variable/property?

2023-06-12 19:53 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/preferences/SliderPreference.kt
> +    private var displayValueTextView: TextView? = null
Great idea. Thanks!

2023-06-12 19:54 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/preferences/SliderPreference.kt
> +        slider = holder.findViewById(R.id.slider) as Slider
gonna need to write `this.value = value`, and similars with `apply`, which isn't much better, so I'll leave it as is

2023-06-22 14:13 UTC, mikehardy approved these changes
Really nice!

Cross-pollination from the react-native world: the slider libraries there are kind of terrible too, they churn a lot and don't seem to have a solid foundation, I suppose it is because the underlying widgets just aren't great which is the same reason to implement one here. Stated differently: it appears you basically need to implement a slider yourself if you want a good one, so here we are :-)

2023-06-22 14:14 UTC, merged