fix: Cursor color being the same of he app bar on the light theme
ankidroid/Anki-Android pull request #13961
Opened 2023-06-07 01:18 UTC by BrayanDSO

## Pull Request template

## Purpose / Description
Changing colorControlActivated value originally had the purpose of tinting the preferences switches (49a880bca6bc422bcebbaf32555042f32e1e648c)

Since this caused the problem of the text selector being the same color of the app bar on the light theme (#12337), using a more specific color selector should be preferred

## Fixes
Fixes #12337 and closes #13503

## Approach
On the commits

## How Has This Been Tested?

API 25 emulator

https://github.com/ankidroid/Anki-Android/assets/69634269/cb4ac0ad-5dc9-4032-bfdc-c44da1ed2e7c

## Learning (optional, can help others)

Appcompat has a lot of attributes. Try searching deep if you haven't found an attribute to change something

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-06-22 13:32 UTC, BrayanDSO commented
Drafted in favor of #13960, since I'm going to make changes to this PR after the other one is merged

2023-06-22 14:14 UTC, mikehardy commented
ready to go if you want, antecedent PR merged

2023-06-24 20:01 UTC, oakkitten requested changes
Other apps seem to have the cursor color similar to text color, as in light if it's light and dark if it's dark. I'd prefer that as well, as well as changing the color of the hint.

2023-06-25 00:58 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/theme_dark.xml
> -        <item name="popupMenuStyle">@style/PopupMenuStyle</item>
Oops. Got the wrong branch. This were from a test

2023-06-25 01:01 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/theme_light.xml
> +        <item name="thumbTint">@color/switch_thumb_tint</item>
If I only want to change the color, the ideal would be to only change the exact thing I want to change, wouldn’t it?

2023-06-25 01:01 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/attrs.xml
> +    <attr name="widgetColor" format="color"/>
Suggestions, please

2023-06-25 01:03 UTC, BrayanDSO commented on AnkiDroid/src/main/res/color/switch_thumb_tint.xml
> +    <item android:color="#ececec"/>
Yes, why not? It is a shade grey that looked fine. Doesn’t need to be reused or changed between themes

2023-06-25 01:05 UTC, BrayanDSO commented
> Other apps seem to have the cursor color similar to text color, as in light if it's light and dark if it's dark. I'd prefer that as well, as well as changing the color of the hint.

I don’t care much. But I would leave this to popular opinion and deal with it later

2023-06-25 01:12 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/theme_light.xml
> +        <item name="thumbTint">@color/switch_thumb_tint</item>
I can’t recall any scenario where it would or where it wouldn’t. If there isn’t anything actionable and concrete here, I’ll leave it as is

2023-06-25 14:51 UTC, oakkitten commented on AnkiDroid/src/main/res/values/theme_light.xml
> +        <item name="thumbTint">@color/switch_thumb_tint</item>
Okay so my idea was to have a style that only applies to switches. Apparently you can't do that with non-material components. With material ones, you can use `materialThemeOverlay`. Not needed for now

Details for myself if I ever want to look at this again (hope not):

In theme,

    <item name="switchPreferenceCompatStyle">@style/PreferenceMaterialSwitch</item>
    <item name="switchStyle">@style/SwitchStyle</item>
    <item name="materialSwitchStyle">@style/SwitchStyle</item>

In layout/widget.xml,

```xml
<?xml version="1.0" encoding="utf-8"?>

<com.google.android.material.switchmaterial.SwitchMaterial
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@android:id/switch_widget"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:focusable="false"
    android:clickable="false"
    android:background="@null"
    />
```

In styles,

    <style name="SwitchPreferenceCompatStyle" parent="@style/Preference.SwitchPreferenceCompat.Material">
        <item name="widgetLayout">@layout/widget</item>
    </style>

    <!-- for the old (our current) style -->
    <style name="SwitchStyle" parent="Widget.AppCompat.CompoundButton.Switch">
        <item name="materialThemeOverlay">@style/SwitchThemeOverlay</item>
        <item name="useMaterialThemeColors">true</item>
    </style>

    <style name="SwitchThemeOverlay" parent="Theme_Light">
        <item name="colorAccent">#f0f</item>
        <item name="colorOnSurface">#ff0</item>
        <!-- Etc -->
    </style>

https://m2.material.io/develop/android/components/switches
https://stackoverflow.com/questions/74487358/how-to-use-material-3-switch-in-preferencefragmentcompat-programmatically/76270479#76270479

2023-06-25 15:01 UTC, oakkitten commented on AnkiDroid/src/main/res/values/attrs.xml
> +    <attr name="widgetColor" format="color"/>
Not sure what this is supposed to represent... “checked”/“active” color?

2023-06-25 15:02 UTC, oakkitten commented
By the way, while this colors switches bright blue, other similar elements (checkboxes, etc) remain the darker color. Why do we want this color at all?

2023-06-25 20:35 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/attrs.xml
> +    <attr name="widgetColor" format="color"/>
It mimics `colorControlActivated`, so maybe `widgetColorActivated`?

2023-06-25 20:43 UTC, BrayanDSO commented
> By the way, while this colors switches bright blue, other similar elements (checkboxes, etc) remain the darker color. Why do we want this color at all?

My goal is to fix #12337 which was created when I tried to change the switch color. So here I'm only trying to fix it by setting the switch color in another way. The checkboxes/etc color changes were unintentional, although I liked them and preferred that way.

I haven't tried to see if other elements have more specific selectors, such as `preferenceCategoryTitleTextColor` that I found out by chance recently, so I can't judge right now what would be the ideal approach. 

For 2.17+, I intend to migrate to material theming and a broader redesign plan. Since material and appcompat's attrs are different, I'd like to take a look at them when I start doing the job.

2023-06-25 20:46 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/theme_light.xml
> +        <item name="thumbTint">@color/switch_thumb_tint</item>
I actually cogitated migrating directly to material switches, and they actually looked okay. But that needed a material theme and I don't want to risk breaking a color scheme somewhere just before 2.16 release

2023-06-25 20:48 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/theme_light.xml
> +        <item name="thumbTint">@color/switch_thumb_tint</item>
Gonna close this as resolved. Comment again if necessary

2023-06-25 22:12 UTC, oakkitten commented on AnkiDroid/src/main/res/values/attrs.xml
> +    <attr name="widgetColor" format="color"/>
Sounds good for now

2023-06-25 22:20 UTC, oakkitten commented
Okay then let's not bother with the theming apart from fixing the immediate issues.

2023-06-26 00:31 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/attrs.xml
> +    <attr name="widgetColor" format="color"/>
Okay, done

2023-06-26 14:12 UTC, mikehardy approved these changes
This works for me, targeted + incremental progress. Limited scope is a positive IMHO Thanks!

2023-06-26 14:12 UTC, merged