Migrate the FindEmptyCards task to coroutines
ankidroid/Anki-Android pull request #13971
Opened 2023-06-09 22:57 UTC by RobozinhoD

## Fixes
#7108

## Approach
I tried to do something like @lukstbit did in #12787 and used backend methods to do this

## How Has This Been Tested?
[device-2023-06-09-195419.webm](https://github.com/ankidroid/Anki-Android/assets/65715921/ea859a65-3598-4f82-982a-ec59735b3a25)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-06-10 05:23 UTC, dae commented
Please test this with the new backend disabled - I suspect it will not work, as that backend method looks like it needs the new schema. Also, the backend should not usually be called directly by GUI code - it should be called by a method in Collection or CollectionV16.

2023-06-10 09:08 UTC, BrayanDSO commented
The string says “Cards deleted: X”, but the code deletes X notes, so it isn’t accurate. 

And the cards count isn’t updated in the video you sent, which led me to realize that it this issue existed before this PR. Therefore, it could be split into another issue, but it would be nice if you managed to solve it here.

2023-06-10 10:06 UTC, RobozinhoD commented
fixed PTAL

2023-06-10 10:40 UTC, BrayanDSO approved these changes
Okay, looks good now. An issue to make the new backend dialog looks more like the one of Anki desktop can be created. But as far as this Pr’s scope goes, it looks alright

2023-06-10 10:59 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                            val cardIds = report.notesList.flatMap { it.cardIdsList }
```suggestion
                        val cardIds = report.notesList.flatMap { it.cardIdsList }
                        val cardCount = cardIds.size
                        setTitle(TR.emptyCardsWindowTitle())
                        setMessage(getString(R.string.empty_cards_count, cardCount))
                        setPositiveButton(R.string.dialog_confirm) { _, _ ->
```

2023-06-10 16:44 UTC, BrayanDSO commented
You could've incorporated the change then rebased, but this is fine

2023-06-10 23:23 UTC, dae commented
A couple of nits:

- Col16.removeCards() and Col.remCards() do the same thing, but one uses the backend. It would be better if the Col16 method overrides remCards instead of using a different name. removeCards is a better name, but if you're changing one then you should change both (and probably not the best time to be changing it)
- The code could be deduplicated a bit. Instead of separate fetch+display paths for each schema, the code could be changed so that just the data-gathering step is different. Eg:

```diff
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
index 05bbd2c1b9..f52cd64f0b 100644
--- a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
@@ -2297,45 +2297,24 @@ open class DeckPicker :
     }
 
     private fun handleEmptyCards() {
-        if (!BackendFactory.defaultLegacySchema) {
-            launchCatchingTask {
-                val report: EmptyCardsReport = withProgress(R.string.emtpy_cards_finding) {
-                    withCol { (this as CollectionV16).getEmptyCards() }
-                }
-                if (report.notesCount == 0) {
-                    showSimpleMessageDialog(getString(R.string.empty_cards_none))
-                } else {
-                    AlertDialog.Builder(this@DeckPicker).show {
-                        val cardIds = report.notesList.flatMap { it.cardIdsList }
-                        val cardCount = cardIds.size
-                        setTitle(TR.emptyCardsWindowTitle())
-                        setMessage(getString(R.string.empty_cards_count, cardCount))
-                        setPositiveButton(R.string.dialog_confirm) { _, _ ->
-                            launchCatchingTask { withCol { (this as CollectionV16).removeCards(cardIds) } }
-                            showSnackbar(getString(R.string.empty_cards_deleted, cardCount))
-                        }
-                        setNegativeButton(R.string.dialog_cancel) { _, _ -> }
+        launchCatchingTask {
+            val emptyCids = withProgress(R.string.emtpy_cards_finding) {
+                withCol {
+                    if (!BackendFactory.defaultLegacySchema) {
+                        newBackend.getEmptyCards().notesList.flatMap { it.cardIdsList }
+                    } else {
+                        emptyCids()
                     }
                 }
             }
-        } else {
-            launchCatchingTask {
-                val emptyCids = withProgress {
-                    withCol { emptyCids() }
-                }
-                if (emptyCids.isEmpty()) {
-                    showSimpleMessageDialog(getString(R.string.empty_cards_none))
-                } else {
-                    AlertDialog.Builder(this@DeckPicker).show {
-                        setTitle(TR.emptyCardsWindowTitle())
-                        setMessage(getString(R.string.empty_cards_count, emptyCids.size))
-                        setPositiveButton(R.string.dialog_confirm) { _, _ ->
-                            launchCatchingTask { withCol { remCards(emptyCids) } }
-                            showSnackbar(getString(R.string.empty_cards_deleted, emptyCids.size))
-                        }
-                        setNegativeButton(R.string.dialog_cancel) { _, _ -> }
-                    }
+            AlertDialog.Builder(this@DeckPicker).show {
+                setTitle(TR.emptyCardsWindowTitle())
+                setMessage(getString(R.string.empty_cards_count, emptyCids.size))
+                setPositiveButton(R.string.dialog_confirm) { _, _ ->
+                    launchCatchingTask { withCol { remCards(emptyCids) } }
+                    showSnackbar(getString(R.string.empty_cards_deleted, emptyCids.size))
                 }
+                setNegativeButton(R.string.dialog_cancel) { _, _ -> }
             }
         }
     }
```

2023-06-11 00:42 UTC, RobozinhoD commented
done. PTAL

2023-06-11 00:58 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +    open fun removeCards(cardIds: Iterable<Long>) {
The rename didn't affect many files, so makes sense to do it. I checked the Python code and the desktop version calls this routine removeCardsAndOrphanedNotes (in snake case), so it may be better to match that name. Otherwise looks good, pending tests passing.

2023-06-11 01:11 UTC, RobozinhoD commented
I changed the positive button text to Delete and fixed the test problems

2023-06-11 07:46 UTC, lukstbit requested changes
Almost there.
@RobozinhoD For future PRs please limit the scope of changes to address a single issue(not like this PR which contains changes for two separate issues). This makes it easier to review and to get your code merged.

2023-06-11 07:46 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +    open fun removeCards(cardIds: Iterable<Long>) {
@RobozinhoD Please use the recommended name from above.

2023-06-11 07:46 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                        launchCatchingTask { withCol { removeCards(emptyCids) } }
The `withCol` call should be wrapped with a `withProgress {}`(it's fine to not add a message).

2023-06-11 08:18 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                        launchCatchingTask { withCol { removeCards(emptyCids) } }
Thanks lukstbit, I missed that.

2023-06-11 08:32 UTC, RobozinhoD commented
> @RobozinhoD For future PRs please limit the scope of changes to address a single issue(not like this PR which contains changes for two separate issues). This makes it easier to review and to get your code merged.

ok. will do. done the changes. PTAL

2023-06-11 10:54 UTC, lukstbit approved these changes
Great, thanks!

2023-06-11 11:06 UTC, merged