Replace MaterialDialog with Alertdialog for ModelFieldEditor.kt
ankidroid/Anki-Android pull request #13999
Opened 2023-06-13 15:22 UTC by zaghdaneh

## Fixes
Related to [#13315](https://github.com/ankidroid/Anki-Android/issues/13315)

## Approach
I tried following previous pull requests related to this issue as much as possible. When I noticed that no other previous pull request adapting a Material dialog that had an EditText inside, I added a new "customView" function to the Alert dialog facade to achieve a similar UI Design. 

## How Has This Been Tested?
Tested all the modified dialogs by inputting, canceling or making changes.

## Learning (optional, can help others)
While trying to work on this problem, I noticed that there was no alternative to the customView function from the materialDialog library in the AlertDialog library. While trying to inflate an EditText it was actually hard to find a solution to add a margin to the InputField to make it look like its materialDialog version (I wanted to avoid making an xml file). I found a solution thanks to this [Post](https://stackoverflow.com/questions/27774414/add-bigger-margin-to-edittext-in-android-alertdialog).

Here are screenshots of the before and after :
<img src="https://github.com/ankidroid/Anki-Android/assets/46049558/dcfafc7a-adac-476e-a486-935f52bfb42e"  width="250" height="500" /> --> <img src="https://github.com/ankidroid/Anki-Android/assets/46049558/08076959-1bc0-4249-b948-0248422c4b13"  width="250" height="500" />

2023-06-14 15:28 UTC, lukstbit requested changes
Thank you for contributing!
I left below some small issues to fix before this could be merged.

2023-06-14 15:28 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
> +                customView(_fieldNameInput)
Add the same margin values you added for the other dialogs, to make this dialog look better.

2023-06-14 15:28 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
> +    editText: View,
While here this is used to add EditTexts, it would be better to name this parameter as _view_ to be more generic.

2023-06-14 15:28 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
> +    val container = FrameLayout(context)
It's wasteful to add two FrameLayouts just to apply some space. You should use a single FrameLayout and set the margin parameters as its padding:

- create a FrameLayout
- set on it as padding the margin parameters(there's the setPadding() method to apply all values at once)
- add the view(use addView(view, LayoutParams) where the LayoutParams are the ones you created below(without the margin))
- set as the dialog's view the created FrameLayout

2023-06-17 06:34 UTC, lukstbit approved these changes
LGTM, thanks you!

2023-06-20 07:41 UTC, Arthur-Milchior reviewed
A single request. If you have a reason not to apply it, and believe code is better as is, I'm fine with merging as is.

Thanks a lot for providing before/after screenshot, it helps so much to review and know what to check exactly. Welcome with us

2023-06-20 07:41 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
> +    paddingLeft: Int = 0,
Do you expect to ever use it with default value? Otherwise, I suggest adding 64 and 32, and a comment explaining why you chose this numbers. This will avoid code repetition everywhere.

2023-06-26 13:06 UTC, lukstbit commented
I think the response for Arthur's raised issue is sufficient to merge this(and I do think 0 as default padding is the reasonable approach). I'm setting this as "Pending merge".

2023-06-28 15:49 UTC, mikehardy commented
I just re-pushed this after rebasing to main and fixing the conflict introduced by a recent multi-change here https://github.com/ankidroid/Anki-Android/pull/13640/files

Part of that PR #13640 was unrelated to this change and part of it was, I believe that PR and this are in harmony now, pending CI

2023-06-28 15:50 UTC, mikehardy approved these changes
the comments were addressed, and I think conflicts are fixed as well, should be good to go

2023-07-01 11:18 UTC, BrayanDSO commented
Rebased to main. Pending CI

2023-07-01 12:22 UTC, merged