NF: Correct typing of getBundleEditFields
ankidroid/Anki-Android pull request #13994
Opened 2023-06-12 21:30 UTC by Arthur-Milchior

IntelliJ keeps removing `import java.util.*`. Which changes `ArrayList` from java to kotlin and creates compilation error due to nullable string typing.

I'd wish this to be merged just so that I don't have to fight with IntelliJ.

2023-06-14 15:42 UTC, lukstbit requested changes

2023-06-14 15:42 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
> +        return mutableListOf(*ret)
As this was transformed into a `mutableListOf`, then the(now aliased) `ArrayList` returned 8 lines above from this method should also be changed to `mutableListOf`.

This way this file will not reference in any way the java/kotlin alias `ArrayList`.

2023-06-14 15:43 UTC, lukstbit commented
Also, I verified that the changes are ok.

2023-06-15 12:08 UTC, lukstbit approved these changes
The changes are ok so I'm approving this. But what I said above would be an extra improvement.

2023-06-19 16:16 UTC, Arthur-Milchior commented
You're right, thanks

2023-06-21 18:26 UTC, mikehardy approved these changes
works for me, thanks!

2023-06-21 18:26 UTC, merged