checking for bitmap size to avoid `illegalArgumentException`
ankidroid/Anki-Android pull request #14001
Opened 2023-06-14 21:28 UTC by criticalAY

## Pull Request template

## Purpose / Description
Bitmap size check to avoid the condition where bitmap size <0

## Fixes
Fixes #13972

## Approach
_How does this change address the problem?_

## How Has This Been Tested?
 condition is suffice to avoid the exception but I would like to have an opinion if we should have a default bitmap size i.e `500x500` in case this case arises. @BrayanDSO 

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-06-15 20:46 UTC, criticalAY commented
Can we consider passing some default size as I mentioned in the PR?

2023-06-15 20:50 UTC, criticalAY commented
this is the deprecated method
```fun getDisplayDimensions```
we can handle the deprecation along with the case if the dimension is zero?

2023-06-15 21:05 UTC, oakkitten commented
Wait, I double-checked the stack trace and the method you are altering, `com.ichi2.anki.Whiteboard#createBitmap()`, does not appear in the trace

2023-06-16 04:20 UTC, criticalAY commented
@oakkitten correct I found the correct place to handle the exception but I want to know if we should assign some default values in case it is less than zero i.e here is the changed method
```
    override fun onSizeChanged(w: Int, h: Int, oldw: Int, oldh: Int) {
        super.onSizeChanged(w, h, oldw, oldh)
        if (w > 0 && h > 0) {
            val scaledBitmap: Bitmap? = try {
                Bitmap.createScaledBitmap(mBitmap, w, h, true)
            } catch (e: IllegalArgumentException) {
                Timber.e("Bitmap size less than zero")
                null
            }
            if (scaledBitmap != null) {
                mBitmap.recycle() 
                mBitmap = scaledBitmap
                mCanvas = Canvas(mBitmap)
            } else {
                val validWidth = 500
                val validHeight = 500
                mBitmap.recycle()
                mBitmap = Bitmap.createBitmap(validWidth, validHeight, Bitmap.Config.ARGB_8888)
                mCanvas = Canvas(mBitmap)
            }
        }
    }
    ```

2023-06-16 12:25 UTC, oakkitten commented
It's hard to say in which cases the view can have one or more sizes as 0. Might be related to very small AnkiDroid window sizes or some unfortunate chains of events that lead to a temporary weird size. Without being able to reproduce the issue, we can't be sure that the application will behave correctly when we get a 0 here. Said that, I think a view should be able to handle having a zero height or width in any case.

I do not see any advantage to resizing the bitmap to anything when we have a 0 height or width. With a zero area we can't draw anything in a meaningful way. At this point we should already have a bitmap so creating one isn't required. Besides, scaling breaks the image since, well, it scales what is supposed not to be scaled. And undo will break this scaling again. And everything is lost on screen rotation anyway. Or theme change. So I wouldn't bother to do anything here beyond a simple 

```kt
if (w == 0 && h == 0) return
```

2023-06-17 18:19 UTC, oakkitten commented
Uhh sorry I meant to say `||` there 😅

2023-06-17 20:50 UTC, criticalAY commented
ok but there are chances that there would be an exception somewhere else after this but chances are minimal so I think it is ok

2023-06-20 17:58 UTC, BrayanDSO commented
Could you please add a `Timber.w` there?

2023-06-20 18:59 UTC, criticalAY commented
what do we want to pass there ?

2023-06-22 12:49 UTC, BrayanDSO requested changes

2023-06-22 12:49 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
> +        if (w == 0 || h == 0) return
```suggestion
        // createScaledBitmap requires a width and height > 0; #13972
        if (w <= 0 || h <= 0) {
            Timber.w("Width or height <= 0: width: $w; height: $h; Bitmap can't be created with the new size")
            return
        }
```

2023-06-22 12:58 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
> +        Timber.w("Whiteboard::onSizeChanged width:$w height:$h")
```suggestion
        Timber.i("Whiteboard::onSizeChanged width:$w height:$h")
```
Here it's just an info, so use `Timber.i`. Below it's a potential error situation where we could recover, so it's a warn `Timber.w`

2023-06-22 13:06 UTC, BrayanDSO approved these changes

2023-06-22 19:56 UTC, mikehardy approved these changes
works for me - thank you!

2023-06-22 19:56 UTC, merged