Rename the strings related to "Collection exported successfully" to the ones for "Export ready"
ankidroid/Anki-Android pull request #14059
Opened 2023-07-01 09:30 UTC by snowtimeglass

## Pull Request template

## Purpose / Description

1. The title of ”Collection exported successfully” in the middle of exporting process is misleading for users, so this commit will replace it with "Export ready". 
1. Incidentally, 
   - The labels of the button of this dialog will be changed. 
   - The dialog message will be removed.
   - The text of the in-progress message before the dialog will be changed.
   - The filenames and the class names related to this dialog will be changed. (`ExportCompleteDialog` -> `ExportReadyDialog`)
   - MaterialDialog for this dialog will be replaced with AlertDialog. 

## Fixes
Fixes #13920
Fixes one of  #13315

## How Has This Been Tested?
Checked on a physical device (Android 11)
|  Before  |  After  |
| ---- | ---- |
|**In current backend**![image](https://github.com/ankidroid/Anki-Android/assets/10436072/c32c8b95-3f10-496d-a3f0-fc1e91408f6b) |  ![image](https://github.com/ankidroid/Anki-Android/assets/10436072/d77e9797-b8df-4f6a-882c-9ad6fa5f69d0)
|**In new backend**![image](https://github.com/ankidroid/Anki-Android/assets/10436072/977b89cc-2943-4d6d-a0ac-c9844fb8f6f2)  | (the same as above) ![image](https://github.com/ankidroid/Anki-Android/assets/10436072/d77e9797-b8df-4f6a-882c-9ad6fa5f69d0)  |
| ![image](https://github.com/ankidroid/Anki-Android/assets/10436072/da4284ae-dbe8-4403-a0a8-8cb750270dd5) |  ![image](https://github.com/ankidroid/Anki-Android/assets/10436072/0dde986e-68f8-4d71-bebb-29f3fc71dcd1)  |

https://github.com/ankidroid/Anki-Android/assets/10436072/7fe0645e-7f89-4efa-a99a-f654dccc578f

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-07-01 16:38 UTC, BrayanDSO requested changes

2023-07-01 16:38 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
> +        builder.show {
Don't call `show {}` here since `onCreateDialog` should only create the dialog

2023-07-01 16:38 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
> +    override val notificationMessage: String? = null
If it isn't used anymore, remove it

2023-07-01 16:38 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="export_preparation_in_progress">Preparing Export…</string>
Why using title case instead of sentence case here? i.e. why `Preparing Export...` instead of `Preparing export...`

2023-07-01 16:38 UTC, BrayanDSO commented
squash there are some commits that don't compile

2023-07-02 01:51 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
> +        builder.show {
Thank you for the reviews. I've rewritten this part.

2023-07-02 01:53 UTC, snowtimeglass commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="export_preparation_in_progress">Preparing Export…</string>
Thank you for the catch. I've fixed it.

2023-07-02 02:02 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
> +    override val notificationMessage: String? = null
Simply removing it seems to cause an error.
![error androidstudio](https://github.com/ankidroid/Anki-Android/assets/10436072/f39ced2c-a0a9-4450-9bd0-a1a4657b9fdc)
![error androidstudio3](https://github.com/ankidroid/Anki-Android/assets/10436072/26adaf7f-d45e-42e5-95cf-6c7767b5b410)
Could you please advise what to do?

2023-07-02 12:37 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
> +    override val notificationMessage: String? = null
My bad. Nevermind

2023-07-02 12:37 UTC, BrayanDSO approved these changes

2023-07-02 12:40 UTC, mikehardy approved these changes
Nice - this seems like a cleaner flow of dialogs for users
I'm syncing strings now so this may be easily merged

2023-07-02 12:56 UTC, merged