set horizontalPadding to HelpDialog Items
ankidroid/Anki-Android pull request #14071
Opened 2023-07-02 09:41 UTC by SanjaySargam

## Pull Request template

## Purpose / Description
Add horizontalPadding to HelpDialog items

## Fixes
Fixes #14042 

## Approach
set paddingLeft to 32 pixels

## How Has This Been Tested?

Tested on Physical Device (Realme 9
![WhatsApp Image 2023-07-02 at 3 10 52 PM](https://github.com/ankidroid/Anki-Android/assets/65113071/333ec670-c779-4133-a219-292f05500637)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-07-03 13:14 UTC, lukstbit requested changes

2023-07-03 13:14 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.kt
> +                root.setPadding(32.dpToPx(), 0, 0, 0)
There's no need to set the padding manually as the layout file used above has padding set on it(of just 10dp) and it also sets is symmetrical.

So change the padding in the layout file to `32dp`.

2023-07-03 14:41 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.kt
> +                root.setPadding(32.dpToPx(), 0, 0, 0)
Will I change all paddings to 32dp or only paddingLeft?

2023-07-03 14:56 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.kt
> +                root.setPadding(32.dpToPx(), 0, 0, 0)
The horizontal padding on both sides, so right and left(I think the IDE will also complain if you don't do it).

2023-07-03 15:21 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.kt
> +                root.setPadding(32.dpToPx(), 0, 0, 0)
@SanjaySargam Also change the paddingStart and paddingLeft to 32dp.

2023-07-03 17:07 UTC, lukstbit approved these changes

2023-08-26 18:39 UTC, abhineshchandra1234 approved these changes

2023-09-12 13:46 UTC, mikehardy approved these changes
Nice! Thank you

2023-09-12 13:47 UTC, merged