Highlighted Correct Deck
ankidroid/Anki-Android pull request #14104
Opened 2023-07-06 11:23 UTC by SanjaySargam

## Pull Request template

## Purpose / Description
Highlighting wrong deck in tablet

## Fixes
Fixes #14057

## Approach
updated DeckList when it is in tablet mode.

## How Has This Been Tested?

Tested on Tablet Emulator ( Pixel C API 33 )
[highlight.webm](https://github.com/ankidroid/Anki-Android/assets/65113071/b59126be-d15f-45eb-aaa3-cd1d7e7f4f72)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-07-13 08:55 UTC, lukstbit requested changes
While this seems to fix the issue it also duplicates the work done when the two pane layout isn't being shown(which will be the majority of the devices).

So I would ask not to introduce another call to `updateDeckList` in `onDeckClicked` and instead change the `handleDeckSelection` method that's called there. Inside `handleDeckSelection` you'll see some if /else clauses that have  `if (fragmented) {} else { updateDeckList() }` which should be changed to `if (fragmented) {} updateDeckList() ` to always update the decks list.

2023-07-14 05:33 UTC, lukstbit commented
As I said above it should be: 
```

if (fragmented) {
    ...
}
updateDeckList()
```

There are also several `else` clauses which should be updated.

2023-07-23 15:00 UTC, lukstbit commented
@SanjaySargam I misspoke about this, the original fix you provided in `onDeckClicked()` adding a call to `updateDeckList()` is the way to go.

2023-07-24 12:50 UTC, lukstbit approved these changes

2023-08-18 15:17 UTC, mikehardy approved these changes
Thanks for this! Much appreciated + and much appreciated @lukstbit for the review, keeps everything moving 🚂

2023-08-18 15:18 UTC, merged