Changed Material Dialog with Alert Dialog for DeckPickerNoSpaceLeftDialog.kt
ankidroid/Anki-Android pull request #14105
Opened 2023-07-06 11:42 UTC by Prince-kushwaha

## Purpose / Description
Replaces usages of MaterialDialog with AlertDialog in DeckPickerNoSpaceLeftDialog.kt
## Fixes
Related to #13315 

## How Has This Been Tested?
Open each one of the changed dialogs on their respective preferences
## Screenshot
![WhatsApp Image 2023-07-06 at 5 10 33 PM](https://github.com/ankidroid/Anki-Android/assets/65972015/72688193-1f0b-4159-99a9-1097a1a07830)

2023-07-06 16:23 UTC, adityabarodiya commented
May I work on this issue?

2023-07-06 16:58 UTC, Prince-kushwaha commented
@adityabarodiya this is not an issue. It is pull Request

2023-07-06 18:36 UTC, BrayanDSO requested changes

2023-07-06 18:36 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerNoSpaceLeftDialog.kt
> +        }.show()
.create() instead of show

2023-07-06 18:36 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerNoSpaceLeftDialog.kt
>              cancelable(true)
Do we need this?

2023-07-06 18:36 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerNoSpaceLeftDialog.kt
>              setOnCancelListener { (activity as DeckPicker).startLoadingCollection() }
Have you checked if this is still working?

2023-07-07 03:17 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerNoSpaceLeftDialog.kt
> +        }.show()
ok

2023-07-07 03:21 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerNoSpaceLeftDialog.kt
>              setOnCancelListener { (activity as DeckPicker).startLoadingCollection() }
yes it  is working perfectly

2023-07-07 04:01 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerNoSpaceLeftDialog.kt
>              cancelable(true)
yes

2023-07-07 04:02 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerNoSpaceLeftDialog.kt
>              setOnCancelListener { (activity as DeckPicker).startLoadingCollection() }
i also tested it

2023-07-19 12:43 UTC, lukstbit approved these changes

2023-08-17 04:51 UTC, Prince-kushwaha commented
@david-allison   review this PR

2023-08-17 16:26 UTC, david-allison approved these changes
Tested. I'm happy

2023-08-17 16:27 UTC, merged