Search text is in normal instead hint text
ankidroid/Anki-Android pull request #14176
Opened 2023-07-30 11:18 UTC by SanjaySargam

## Pull Request template

## Purpose / Description
Search text is in hint text instead of normal text while filtering by tags

## Fixes
Fixes #14175 

## Approach
use searchWithFilterQuery function in filterByTags function

## How Has This Been Tested?
Tested on Emulator ( Pixel 5 API 33 )

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-10-25 08:29 UTC, lukstbit requested changes

2023-10-25 08:29 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
>          searchCards()
There's no need for the searchCards() call at the end as searchWithFilterQuery() already calls searchCards().

2023-10-25 08:31 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
>          searchCards()
Ok I will remove it

2023-11-02 18:13 UTC, lukstbit approved these changes

2023-11-11 13:48 UTC, mikehardy approved these changes
Thanks!

2023-11-11 13:48 UTC, merged