fix: Removed beolingus pronounce feature
ankidroid/Anki-Android pull request #14181
Opened 2023-08-01 09:26 UTC by pratyaksh1610

## Purpose / Description
fix: Removed beolingus pronounce feature

## Fixes
Fixes #14165

## Approach
Removed instances and activities.

## How Has This Been Tested?
![pro](https://github.com/ankidroid/Anki-Android/assets/76740999/c768eb40-226a-4bf0-841f-3e90f9ae2ef0)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-08-01 09:46 UTC, lukstbit commented
Please fix lint issues.

2023-08-02 00:17 UTC, BrayanDSO commented
I think that the `Advanced editor` can be removed as well. Or is there anything else in this screen besides the `Clear` button?

2023-08-02 06:41 UTC, pratyaksh1610 commented
@BrayanDSO The `Advanced editor` includes the `Clone from` button as well.

2023-08-02 09:40 UTC, lukstbit requested changes
There are classes which were left behind, See the packages `multimediacard/beolingus/*` and `multimediacard/language/*` plus the tests for `BeolingusParser`.

2023-08-02 09:40 UTC, lukstbit commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
> -	<string name="network_no_connection">No connection</string>
@BrayanDSO This string seems generic enough to be used in other places. Do you think we should suppress the unused warning instead of deleting it?

2023-08-02 09:40 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.kt
>          val layoutTools2 = LinearLayout(mActivity)
The `layoutTools2` LinearLayout is not needed anymore.

2023-08-02 09:51 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
> -	<string name="network_no_connection">No connection</string>
I thought a little and haven't found a place that we could use it right now. 

From what I've looked, it is translated in ~50% of the languages, so to spare the work of the rest of the untraslated languages since we aren't sure this will be useful, I'd vote to remove it

2023-08-02 10:19 UTC, lukstbit commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
> -	<string name="network_no_connection">No connection</string>
@BrayanDSO Removal it is then.

2023-08-03 09:56 UTC, lukstbit approved these changes

2023-08-03 10:49 UTC, BrayanDSO approved these changes
Glad to see this being gone. Thanks!

2023-08-18 12:30 UTC, merged