Added gesture for rescheduling
ankidroid/Anki-Android pull request #14182
Opened 2023-08-02 04:01 UTC by parthn2

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._
#14179 

## Approach
_How does this change address the problem?_

## How Has This Been Tested?
Tested on Android Studio Emulator

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-08-02 08:40 UTC, lukstbit commented
Your changes are making some of the tests to fail. You have to also fix those tests.

2023-08-02 21:09 UTC, BrayanDSO requested changes

2023-08-02 21:09 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
> +                Pair(44, ViewerCommand.RESCHEDULE_NOTE)
not necessary

2023-08-04 22:28 UTC, BrayanDSO requested changes

2023-08-04 22:28 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
> +    RESCHEDULE_NOTE(R.string.reschedule_card_dialog_message);
Just `Reschedule` reads better here
```suggestion
    RESCHEDULE_NOTE(R.string.card_editor_reschedule_card);
```

2023-08-05 10:26 UTC, BrayanDSO approved these changes
LGTM. Thanks for the contribution

2023-08-05 15:29 UTC, lukstbit approved these changes
Thanks you for contributing!

2023-08-05 15:30 UTC, merged