Fix importing a shared deck by providing a dedicated download path
ankidroid/Anki-Android pull request #14198
Opened 2023-08-06 10:08 UTC by lukstbit

## Purpose / Description

Attempts to fix some reported issues related to FileNotFoundExceptions when importing shared decks(for example https://ankidroid.org/acra/app/1/bug/63087/report/cca29061-dec2-416f-bbf1-a0e5bb864aa2 ). See commit message for extra info.

See documentation for [FileProvider](https://developer.android.com/reference/androidx/core/content/FileProvider), especially the section **Specifying Available Files**. Notice the mappings between the paths in filepaths.xml and the specific system directories the documentation specifies.

## How Has This Been Tested?

Manually imported a shared deck, however I don't know how relevant is this as I wasn't able to replicate the crashes from acra.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-08-11 20:06 UTC, david-allison requested changes
Could we also add documentation for how a user can safely clear space from this directory.

2023-08-11 20:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        val decksDownloadFolder = File(requireContext().getExternalFilesDir(null), "shared_decks")
`getExternalFilesDir` can return null. Can we handle this case?

2023-08-13 06:55 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        val decksDownloadFolder = File(requireContext().getExternalFilesDir(null), "shared_decks")
I handled this case by canceling the download and showing a toast to the user.

2023-08-13 06:57 UTC, lukstbit commented
I added the code needed to delete the downloaded shared deck.

Note that this was intended as a quick fix, this part about importing decks needs to be refactored to use something like WorkManager or a foreground service.

2023-08-18 14:43 UTC, mikehardy requested changes
This seems okay to me - I left two comments which are mostly trivial (+nullcheck, +constant&comment) but the code looks fine as an idea + general implementation

2023-08-18 14:43 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
> +                contentResolver.delete(intent.data!!, null, null)
Any time I see a `!!` I have a vision of a future crash report, regardless how slim the chance 😬

2023-08-18 14:43 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        val decksDownloadFolder = File(externalFilesFolder, "shared_decks")
`shared_decks` is a "magic string", and it is shared between this file and the `filepaths.xml` file

Could you make it a real Kotlin constant in this file, and document that it is also defined in filepaths.xml to make sure things are tied together mentally for future maintainers?

2023-08-18 20:52 UTC, david-allison approved these changes
Happy, awaiting changes for Mike

2023-08-24 16:19 UTC, lukstbit commented
I've made the requested changes.
Note that this isn't likely to solve the issues around importing decks that appear on acra but I still think this is a good change to be merged.
This code around importing decks/shared decks really needs to be refactored as it has a lot of issues.

2023-08-25 15:11 UTC, mikehardy approved these changes
fantastic! thanks

2023-08-25 15:12 UTC, mikehardy commented
crowdin activity stream indicates there has been no activity since building the project for the last string merges, so this is clean + ready to go

2023-08-25 15:13 UTC, merged