feature : minimal screen touch time to reveal answer
ankidroid/Anki-Android pull request #14237
Opened 2023-08-16 10:25 UTC by criticalAY

## Pull Request template

## Purpose / Description
The user can define the minimum touch time for the show answer button as to avoid accidental touches and revealing the answer, this would allow the button to be clickable only after the certain time
min time : 0
max time : 2 s

## Fixes
Fixes #14229 

## How Has This Been Tested?
Tested on google emualtor 
![Screenshot_119](https://github.com/ankidroid/Anki-Android/assets/48384865/25b4efe3-5ab8-455d-b2ce-f30c6f6efa45)
![Screenshot_118](https://github.com/ankidroid/Anki-Android/assets/48384865/8e3c6c03-a5a1-48d6-a580-90d9ee650d3a)

https://github.com/ankidroid/Anki-Android/assets/48384865/fa7e1eae-2769-49b5-bde9-5779040f3c24

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-08-16 16:39 UTC, lukstbit commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="pref_minimal_click_time_summary">Delay Show Answer button click time to prevent accidental clicks while commuting</string>
This aren't the strings that should be used, they are not very general. Another attempt:

_Show answer trigger delay
Amount of time in milliseconds to wait between clicking "Show answer" and actually registering the click_

2023-08-16 16:51 UTC, criticalAY commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="pref_minimal_click_time_summary">Delay Show Answer button click time to prevent accidental clicks while commuting</string>
>Amount of time in milliseconds to wait between clicking "Show answer" and actually registering the click

this is not about the wait time it about hold and press the show answer button the show the answer

2023-08-16 16:54 UTC, criticalAY commented
@david-allison I have implemented the press and hold accessibility there is one other way also i.e. we can disable the button for a certain period and the user would only be able to click the button after that time so, either we can implement this or the second one(wait time before the button is accessible )

2023-08-21 15:19 UTC, david-allison requested changes
@crackychans, can you confirm that this is what you require (hold for Xms before registering an answer) and that "Double tap time interval" is not sufficient for you.

----

⚠️ Blocker (after OP responds to ensure we don't waste time): This seems to only be for the 'flip' and not for the 'answer buttons' as was in the original issue

2023-08-21 15:19 UTC, david-allison commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="pref_minimal_click_time_summary">Delay Show Answer button click time to prevent accidental clicks while commuting</string>
Try a few iterations and see what ChatGPT comes up with:

* We want to reference a general issue, not commuting

My proposal would be "Require a touch for at least the provided duration before flipping or answering a card"

But I feel we can do better. Mike's fantastic with these

2023-08-21 15:43 UTC, criticalAY commented
I would ping Mike once we are clear what the OP actually suggested

2023-08-22 06:54 UTC, criticalAY commented
@david-allison I suggest keeping the minimal touch time on the `show answer` button only

2023-08-22 09:29 UTC, david-allison requested changes
If you're happy, I'm happy to merge. 

One requested comment/change about the "do nothing" line

I would personally like to come back to this to add the functionality to the answer buttons: if it's for accessibility, we should do as much as possible. I don't think this needs to happen in this PR

2023-08-22 09:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +            if (minimalClickSpeed != 0) {
Optional: flip the `if` to reduce nesting

2023-08-22 09:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +                                // do nothing
This condition seems to do nothing, which implies a bug. If it does nothing, does it need to exist?

2023-08-22 10:25 UTC, criticalAY commented
ok I will remove the excess code and do the nits pinging @mikehardy for the strings

2023-08-22 15:35 UTC, david-allison commented
I'm happy, pending string discussion

2023-08-23 08:17 UTC, snowtimeglass commented
>I did try Android's "Ignore repeated touches" feature for a day. It's a tier of hell, lmao. 

>0.1ms is the minimal, and I apparently type faster than that. 

>Also, it puts this obnoxious circle graphic around where you touch the screen which lights red whenever you tap faster.

@crackychans Which version of AnkiDroid are you using? You might want to try the latest version on the Play Store.

2023-08-23 11:57 UTC, criticalAY commented
I forgot to post the updated screen recording here :
[https://github.com/ankidroid/Anki-Android/assets/48384865/b81dc013-66ad-49f3-8350-8302ef78b3bd

2023-08-25 16:47 UTC, david-allison commented
> > I did try Android's "Ignore repeated touches" feature for a day. It's a tier of hell, lmao.
> > 0.1ms is the minimal, and I apparently type faster than that.
> 
> @crackychans Which version of AnkiDroid are you using?

Just to note: "Ignore Repeated Touches" is an Android OS feature

2023-08-25 16:50 UTC, mikehardy commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="pref_minimal_click_time_summary">Delay Show Answer button click time to prevent accidental clicks while commuting</string>
Interesting - looking at this now, it appears the chosen solution is to create a preference that turns on a long-touch requirement for show answer button 

So string title should be something like "Show answer long-press time (milliseconds)"
And description should be something like "Minimum long-press time before the show answer button will register a touch. May reduce the chance of accidental extra button presses. Default is 0ms"

My goals for the wording were to keep the title short but hopefully still meaningful, and for the description to have both the idea of "why would I want that / how could it help me?" as well as a sufficient description of the mechanism so it made sense. And then the default value

? I'm flattered anyone thinks I'm good at crafting these phrases, I struggle with it and generally am not happy with my results either 😆 . But hopefully it helps

2023-08-25 22:16 UTC, criticalAY commented
@david-allison Done! Replaced the strings

2023-09-05 06:41 UTC, criticalAY commented
@david-allison review request:)

2023-09-05 06:47 UTC, lukstbit commented
@criticalAY Lint is failing...

2023-09-05 06:49 UTC, criticalAY commented
String is too long I'll fix that I thought it's a flaky one so didn't see the log , I guess other than this other things are fine

2023-09-05 07:03 UTC, david-allison approved these changes

2023-09-05 14:41 UTC, criticalAY commented
```
CardBrowserTest > filterByFlagDisplaysProperly FAILED
    kotlinx.coroutines.test.UncaughtExceptionsBeforeTest: There were uncaught exceptions before the test started. Please avoid this, as such exceptions are also reported in a platform-dependent manner so that they are not lost.
        at kotlinx.coroutines.test.TestScopeImpl.enter(TestScope.kt:242)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:307)
        at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:166)
        at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
        at com.ichi2.anki.RobolectricTest.runTest(RobolectricTest.kt:581)
        at com.ichi2.anki.RobolectricTest.runTest$default(RobolectricTest.kt:575)
        at com.ichi2.anki.CardBrowserTest.filterByFlagDisplaysProperly(CardBrowserTest.kt:350)

```

2023-09-09 06:46 UTC, criticalAY commented
@mikehardy pending for review

2023-09-12 14:50 UTC, mikehardy approved these changes
Nice, this is an interesting - and I think useful - accessibility addition
I wonder if in the future other taps may also benefit from the functionality, they might
(not arguing for any in specific or to do anything else here - easy extraction + addition in follow-ons if so)

I rebased it on current so the flaky test should be gone, and I squashed the commits to a single

It will need the now-standard "sync strings before merging this", "merge this", "sync strings after" treatment 

Cheers

2023-09-12 15:13 UTC, criticalAY commented
🙏🏻 thanks!

2023-09-13 08:49 UTC, lukstbit approved these changes

2023-09-13 08:50 UTC, merged