Stop using finishWithoutAnimation() and launchForResultWIthoutAnimation()
ankidroid/Anki-Android pull request #14370
Opened 2023-09-01 18:52 UTC by BrayanDSO

Historically, finishWithoutAnimation() was mostly used as a replacement for finish(), since it was deprecated by previous AnkiDroid devs in favor of using finishWithoutAnimation() and finishWithAnimation().

The issue was that it was common to see contributors, especially new ones (including myself), using finishWithoutAnimation() because only because finish() wasn't available and finishWithAnimation() was harder to use

Since there is no reason for wanting for a screen to finish without animation, which is unnatural, and now that finish() is undeprecated, it should be the default way of closing a screen.

There is no concern about devices with animation, since the behavior will be the same with finish()

Same for `launchForResultWIthoutAnimation()`. `startActivityForResultWithoutAnimation` will be removed anyway later because it is a deprecated method

## Approach
- Replace `finishWithoutAnimation()` with `finish()`
- Remove launchForResultWIthoutAnimation()

## How Has This Been Tested?

33 emulator: opened the app and opened/closed some screens

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-09-06 15:42 UTC, lukstbit requested changes
Using `finish()` seems fine.

2023-09-06 20:44 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -        launchActivityForResultWithoutAnimation(previewIntent, onPreviewCardsActivityResult)
All of the calls of `ActivityResultContract.launch()` will have animation. A next step would be disabling animation conditionally on all of the calls, which I still have to think how to do it. Either way, `launchActivityForResultWithoutAnimation` removal is a necessary step to simplify the API and improve consistency.

So, for now, I'd like to keep this as is

2023-09-08 10:33 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> -        launchActivityForResultWithoutAnimation(previewIntent, onPreviewCardsActivityResult)
Fine, but if we get a report I'm assigning you :)
It would be interesting to see how many users with an e-ink device we have.

2023-09-08 10:34 UTC, lukstbit approved these changes

2023-09-12 13:41 UTC, mikehardy approved these changes
Steady incremental progress, +1

2023-09-12 13:41 UTC, merged