Successfully showing snackbar above FAB in the deck picker
ankidroid/Anki-Android pull request #14408
Opened 2023-09-07 10:29 UTC by DevP-ai

## Purpose / Description
In the deck picker component of our application, we want to enhance the user experience by displaying Snackbars with important notifications or messages directly above the Floating Action Button (FAB) instead of below it. This change is intended to ensure that the Snackbar will more noticeable and user-friendly.

## Fixes
Show snack bar above FAB in the deck picker instead of below #14403

## Approach
To address the issue, modify the behavior of the Floating Action Button (FAB) by removing its current implementation in the "floating_add_button.xml" file. This approach involves decoupling the FAB behavior from its XML representation and using an anchor view mechanism in the Snackbar logic. By doing so, we aim to provide more flexibility and control over how Snackbars are positioned relative to other UI elements, ensuring a more cohesive and adaptable user interface.
## How Has This Been Tested?
### Before:

![before](https://github.com/ankidroid/Anki-Android/assets/107491760/f5ea19ca-d6d3-454f-9e9d-ec3e84ee2517)

### After:

![after](https://github.com/ankidroid/Anki-Android/assets/107491760/0987cc1b-e437-48d4-a477-b137ca875e00)

## Learning (optional, can help others)
_Describe the research stage_
https://m3.material.io/components/snackbar/guidelines#84cd5bb6-354f-4fd0-bdd9-daf9684ba4bf
https://stackoverflow.com/questions/52302340/show-snack-bar-above-fab-in-androidx

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-09-10 14:59 UTC, BrayanDSO requested changes

2023-09-10 14:59 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt
> +var mFab: FloatingActionButton? = null
Instead of adding this global variable, You should add the `BaseSnackbarBuilderProvider` interface to `DeckPicker` and set the anchorView there

2023-09-10 16:17 UTC, DevP-ai commented on AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt
> +var mFab: FloatingActionButton? = null
Ok sir

2023-09-10 18:33 UTC, DevP-ai commented on AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt
> +var mFab: FloatingActionButton? = null
### Sir please check below images , i have set all the required code in `BaseSnackbarBuilderProvider` and remove from `Snackbar` but Snackbar and FloatingActionButton are overlapping

## BaseSnackbarBuilderProvider interface:

![image](https://github.com/ankidroid/Anki-Android/assets/107491760/c6f14a81-dfc0-45fb-87ee-dcffc892afbd)

## Initializing mFab: 
![image](https://github.com/ankidroid/Anki-Android/assets/107491760/898fcef4-0193-43cb-ba8a-6d0c6dc40342)

## Set anchorview:
![image](https://github.com/ankidroid/Anki-Android/assets/107491760/68400963-80ea-473d-ab8b-d9bb31781849)

2023-09-12 09:44 UTC, DevP-ai commented on AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt
> +var mFab: FloatingActionButton? = null
@BrayanDSO  Sir, could you please take a look at my code and inform me if there are any changes that need to be made?

2023-09-12 19:56 UTC, BrayanDSO requested changes

2023-09-12 19:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +typealias SnackbarBuilder = Snackbar.() -> Unit
Import it from `com.ichi2.anki.snackbar.Snackbar.kt` instead of redefining it here

2023-09-12 19:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            mFab = findViewById(R.id.fab_main)
You don't need a `mFab` class property if this is only used at this method and it is always redefined at it.

```
this.anchorView = mFab
````
this would suffice here

2023-09-12 20:04 UTC, DevP-ai commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            mFab = findViewById(R.id.fab_main)
`override val baseSnackbarBuilder: SnackbarBuilder`
    `get() = {`
        `val mFab = findViewById<View>(R.id.fab_main)`
        `this.anchorView = mFab // Set anchorView directly`
    `}`
    
    is this correct??

2023-09-12 20:06 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            mFab = findViewById(R.id.fab_main)
The `m` prefix is for class properties (search for hungarian notation for more details)

```kotlin
override val baseSnackbarBuilder: SnackbarBuilder
    get() = {
        this.anchorView =  findViewById<View>(R.id.fab_main)
    }
```

this should suffice (up to testing)

2023-09-12 20:10 UTC, DevP-ai commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            mFab = findViewById(R.id.fab_main)
Ok sir thank you

2023-09-15 12:26 UTC, BrayanDSO approved these changes

2023-09-15 12:26 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        }
```suggestion
    override val baseSnackbarBuilder: SnackbarBuilder = {
        anchorView = findViewById<FloatingActionButton>(R.id.fab_main)
    }
```

2023-09-16 08:33 UTC, lukstbit approved these changes
Thanks for contributing!
LGTM with the small issue below to fix and then we can merge this.

2023-09-16 08:33 UTC, lukstbit commented on AnkiDroid/src/main/res/layout/floating_add_button.xml
> -    app:layout_behavior="com.ichi2.anki.widgets.FabBehavior"
The `FabBehavior` class was used only here so ti should be deleted as well.

2023-09-16 08:50 UTC, DevP-ai commented on AnkiDroid/src/main/res/layout/floating_add_button.xml
> -    app:layout_behavior="com.ichi2.anki.widgets.FabBehavior"
Can you please explain what I should do more clearly? In my first  PR, I had removed `FabBehavior`

2023-09-16 08:58 UTC, lukstbit commented on AnkiDroid/src/main/res/layout/floating_add_button.xml
> -    app:layout_behavior="com.ichi2.anki.widgets.FabBehavior"
I mean you have to delete the class `FabBehavior` which can be found in the package `com.ichi2.anki.widgets`. With `    app:layout_behavior="com.ichi2.anki.widgets.FabBehavior"` you deleted its only usage so it's not needed anymore.

2023-09-16 09:06 UTC, DevP-ai commented on AnkiDroid/src/main/res/layout/floating_add_button.xml
> -    app:layout_behavior="com.ichi2.anki.widgets.FabBehavior"
should I remove this class from the package `com.ichi2.anki.widget`

![image](https://github.com/ankidroid/Anki-Android/assets/107491760/d0da3105-dd55-4ab8-a30c-6a26e0e6a33d)

2023-09-16 09:16 UTC, lukstbit commented on AnkiDroid/src/main/res/layout/floating_add_button.xml
> -    app:layout_behavior="com.ichi2.anki.widgets.FabBehavior"
Yes

2023-09-16 09:45 UTC, lukstbit approved these changes
Great!

2023-09-16 09:46 UTC, merged

2023-10-30 19:10 UTC, DevP-ai commented
@BrayanDSO  Sorry to interrupt you sir,  I want to ask about the above message https://github.com/ankidroid/Anki-Android/pull/14408#issuecomment-1783975754  . Can you please explain it briefly?