[Deprecation] Activity.onBackPressed (WIP)
ankidroid/Anki-Android pull request #14401
Opened 2023-09-06 09:57 UTC by n1snt

## Purpose / Description
Fixes Activity.onBackPressed deprecation.

## Fixes
https://github.com/ankidroid/Anki-Android/issues/12364

## Approach
Source: https://stackoverflow.com/questions/72634225/onbackpressed-is-deprecated-what-is-the-alternative

## How Has This Been Tested?
- Physical device.

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-09-08 06:05 UTC, n1snt commented
I'm almost done with testing I'll add some screen recordings & screenshots here.

2023-09-08 10:36 UTC, lukstbit commented on AnkiDroid/src/main/AndroidManifest.xml
> +        android:enableOnBackInvokedCallback="true"
This isn't needed yet, it's for the new predictive back gestures.

2023-09-08 10:39 UTC, lukstbit requested changes

2023-09-08 10:39 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
>      override fun onBackPressed() {
The goal of the new API is to avoid using onBackPressed().
The code also doesn't make any sense: you add a back callback in onBackPressed when  the user just clicked back and the activity is finishing.

2023-09-08 10:39 UTC, lukstbit commented on AnkiDroid/src/main/AndroidManifest.xml
> +        android:enableOnBackInvokedCallback="true"
This isn't needed yet, it's for the new predictive back gestures.

2023-09-08 10:39 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
>      override fun onBackPressed() {
The same as above related to overriding onBackPressed().

2023-09-24 14:28 UTC, n1snt commented
@lukstbit Just redone it can I please have a review?
@BrayanDSO Will do some more testing & add screen recordings/screenshots here.

2023-10-16 14:36 UTC, closed without merging