Update to Anki 23.10
ankidroid/Anki-Android pull request #14456
Opened 2023-09-20 04:01 UTC by dae

Depends on https://github.com/ankidroid/Anki-Android-Backend/pull/307

2023-10-16 10:34 UTC, dae commented
Thanks @lukstbit. Tests are passing; if this could be merged in and a new alpha put out, that would be appreciated.

2023-10-17 11:40 UTC, lukstbit requested changes

2023-10-17 11:40 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +            while (true) {
This will hang the main thread, there's even a warning for the mediaSynStatus() call:

`W  Op on UI thread:com.ichi2.anki.SyncKt$monitorMediaSync$2.invokeSuspend(Sync.kt:351)`

Maybe we could read the status inside another coroutine and expose it through a channel?
```
launchCatchingTask {
  val channel = Channel<MediaSyncResponse?>()
  val fetchResponseJob = launch(Dispatchers.IO) {
     // read the status CollectionManager.getBackend().mediaSyncStatus(), use null for exception?
  }
  for (resp in channel) {
      // code checking if it is active and update status
  }
}
```

2023-10-17 11:41 UTC, lukstbit commented
@dae Do you target a specific date for the 23.10 release?

2023-10-17 14:14 UTC, mikehardy commented
@lukstbit --> https://github.com/ankidroid/Anki-Android-Backend/pull/307#issuecomment-1763250092 has some info:

> While 23.10 likely won't be stabilized until the end of the month, it would be nice to get this into the hands of users now, as FSRS works best when all clients support it. If possible, it would be great if we could publish this now, merge https://github.com/ankidroid/Anki-Android/pull/14456 in, and then put out 2.17alpha2. When 23.10 is released as stable, I'll follow-up with another backend PR that pulls in any remaining fixes accumulated since now.

...which seems reasonable to me, as it is mainly releasing a new alpha which is low-risk as it's alpha channel only

2023-10-17 22:41 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +            while (true) {
Thanks, good catch!

2023-10-18 05:09 UTC, lukstbit approved these changes
Good to go from my point of view.

2023-10-18 07:09 UTC, dae commented
@lukstbit re your confused emoji: the plan is to get this code into an alpha build, and then when 23.10 is released as stable (hopefully this month), do another backend update with any accumulated fixes, as I imagine 2.17 will take some more time before it's ready for a stable release

2023-10-18 16:09 UTC, BrayanDSO requested changes

2023-10-18 16:09 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    var mediaUsnOnConflict: Int? = null
If the activity is recreated (i.e. theme is changed), this will be set to null again. 

Save this value at `onSaveInstanceState` and restore it at `onRestoreInstanceState`

2023-10-18 23:26 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    var mediaUsnOnConflict: Int? = null
Thanks, I don't think I'll ever get used to Android losing state in such cases.

2023-10-19 00:23 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    var mediaUsnOnConflict: Int? = null
Nowadays seems like the "preferred Android way" to handle things like this is using a `ViewModel`, which has a tendency of delivering better code overall, so bad things may happen for a good reason (or at least it is more confortable thinking that way).

2023-10-19 00:24 UTC, BrayanDSO approved these changes

2023-10-19 00:26 UTC, BrayanDSO approved these changes

2023-10-19 00:27 UTC, merged