ammened backer in readme.md
ankidroid/Anki-Android pull request #14508
Opened 2023-10-04 11:38 UTC by criticalAY

## Purpose / Description
Broken link for open collective backers

## Fixes
Fixes #14441

## How Has This Been Tested?

![image](https://github.com/ankidroid/Anki-Android/assets/48384865/8b88b0df-2a8d-414f-9e0e-18ae6054963e)

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-10-06 11:28 UTC, criticalAY commented
@Arthur-Milchior review request

2023-10-08 12:14 UTC, david-allison requested changes
We don't want to hardcode this if at all possible. How do other repos do this?

2023-10-08 12:52 UTC, criticalAY commented
> We don't want to hardcode this if at all possible. How do other repos do this?

Webpack [link](https://github.com/webpack/webpack) does it this way it is actually not hardcoded it shows the backers from the backers list that is available on OC and the user is not hardcoded here

2023-10-08 12:54 UTC, criticalAY commented
eslint has actually hardcoded their selective sponsors 
```
<!--sponsorsstart-->
<h3>Platinum Sponsors</h3>
<p><a href="#"><img src="https://images.opencollective.com/2021-frameworks-fund/logo.png" alt="Chrome Frameworks Fund" height="undefined"></a> <a href="https://automattic.com"><img src="https://images.opencollective.com/automattic/d0ef3e1/logo.png" alt="Automattic" height="undefined"></a></p><h3>Gold Sponsors</h3>
<p><a href="https://engineering.salesforce.com"><img src="https://images.opencollective.com/salesforce/ca8f997/logo.png" alt="Salesforce" height="96"></a> <a href="https://www.airbnb.com/"><img src="https://images.opencollective.com/airbnb/d327d66/logo.png" alt="Airbnb" height="96"></a></p><h3>Silver Sponsors</h3>
<p><a href="https://liftoff.io/"><img src="https://images.opencollective.com/liftoff/5c4fa84/logo.png" alt="Liftoff" height="64"></a> <a href="https://americanexpress.io"><img src="https://avatars.githubusercontent.com/u/3853301?v=4" alt="American Express" height="64"></a></p><h3>Bronze Sponsors</h3>
<p><a href="https://themeisle.com"><img src="https://images.opencollective.com/themeisle/d5592fe/logo.png" alt="ThemeIsle" height="32"></a> <a href="https://www.crosswordsolver.org/anagram-solver/"><img src="https://images.opencollective.com/anagram-solver/2666271/logo.png" alt="Anagram Solver" height="32"></a> <a href="https://icons8.com/"><img src="https://images.opencollective.com/icons8/7fa1641/logo.png" alt="Icons8" height="32"></a> <a href="https://discord.com"><img src="https://images.opencollective.com/discordapp/f9645d9/logo.png" alt="Discord" height="32"></a> <a href="https://transloadit.com/"><img src="https://avatars.githubusercontent.com/u/125754?v=4" alt="Transloadit" height="32"></a> <a href="https://www.ignitionapp.com"><img src="https://avatars.githubusercontent.com/u/5753491?v=4" alt="Ignition" height="32"></a> <a href="https://herocoders.com"><img src="https://avatars.githubusercontent.com/u/37549774?v=4" alt="HeroCoders" height="32"></a> <a href="https://quickbookstoolhub.com"><img src="https://avatars.githubusercontent.com/u/95090305?u=e5bc398ef775c9ed19f955c675cdc1fb6abf01df&v=4" alt="QuickBooks Tool hub" height="32"></a></p>
<!--sponsorsend-->
```

2023-10-09 06:19 UTC, lukstbit commented
I think we could also use their API and create a workflow to automatically update the readme file.

2023-10-09 06:23 UTC, criticalAY commented
> I think we could also use their API and create a workflow to automatically update the readme file.

But why to complicate things when we can simply use the URL in here and its updates the user from the backers list

2023-10-09 06:53 UTC, lukstbit commented
I just mentioned the API as an alternative, I haven't checked to see if this would actually work.

The problem with your approach is that it's manual, so any new backers would need to be added manually especially as we mention that backing the project would get their name on our readme. So someone would have to go pretty often and check if there are new backers(I see a big list) and then add them in the readme(with a long list of commits "Add new backers").

2023-10-09 06:57 UTC, criticalAY commented
Umm webpack has actually mentioned that if a backers name is not there they need to create an issue and they would be added just in case but I'll see if there is a API available(not sure there is )

2023-10-09 07:11 UTC, lukstbit commented
> Umm webpack has actually mentioned that if a backers name is not there they need to create an issue

The code in this PR + a text added that if you are a backer and you don't see your name in the list to create an issue sounds like a simple solution.

2023-10-09 07:25 UTC, criticalAY commented
Ok will do

2023-10-09 09:06 UTC, lukstbit commented
I think the text should be something like(also remove the empty row above this text):

_If you can't see yourself here, please let us know by creating an issue._

but wait for other reviewers' opinions as well. Note that when I looked at this from the files tab the backers images are not seen:

![Screenshot from 2023-10-09 12-02-28](https://github.com/ankidroid/Anki-Android/assets/52494258/a1682d64-ddcb-4f99-bead-5cad59560349)

2023-10-09 09:41 UTC, criticalAY commented
I can see the list i tested it before pushing it
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/695e0fa5-d44f-4844-90c2-c31616e11a85)

2023-10-09 10:13 UTC, eginhard commented
It already shows the top, not first, 100 backers, so I assume OpenCollective would update the linked images. There are currently 3584 total backers, so it surely is not feasible to list them all in this way.

2023-10-09 10:30 UTC, criticalAY commented
Can we add around 50 backers as I added top 100 and then give a link to more show them all

2023-10-09 10:47 UTC, criticalAY commented
@lukstbit @david-allison I figured it out we can display all the backers without hardcoding anything I'll update the PR once I'm home

2023-10-09 16:25 UTC, criticalAY commented
i open an issue for the same in OC repo [here](https://github.com/opencollective/opencollective/issues/7046)

2023-10-10 07:32 UTC, criticalAY commented
@lukstbit @david-allison 
We can't render all the 3k backers due to the SVG size,
we have two options here
1. Just show the number of backers badge(current commit)
2. Show 1k backers along with this badge

2023-10-10 08:30 UTC, david-allison commented
I prefer option 1. We could get in contact with Open Collective and add some backlog work for a more feasible option, but I  wouldn't want to see automated processes here unless there's a requirement. 

* We don't want to spend much time here
* We don't want ongoing maintenance here

Speaking for our backers: I'd much rather their money went to user-facing changes, rather than our readme.

----

This appears broken on your branch: 

https://github.com/criticalAY/Anki-Android/blob/backers-link/README.md

Screenshot:
<img width="548" alt="Screenshot 2023-10-10 at 16 28 10" src="https://github.com/ankidroid/Anki-Android/assets/62114487/ad5297d4-69f5-4fb9-bdec-3161cd9c55be">

2023-10-10 08:54 UTC, criticalAY commented
updated it
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/71c6f6da-4fc2-4fae-b32f-bd58ab7b53c2)

2023-10-10 09:07 UTC, criticalAY commented on README.md
> +A big thank you to each of our 🙏
i left that on purpose as the badge already has that text but will amend this

2023-10-10 09:08 UTC, criticalAY commented on README.md
> +A big thank you to each of our 🙏
Done!

2023-10-10 09:38 UTC, david-allison approved these changes

2023-10-10 11:44 UTC, lukstbit approved these changes
LGTM

2023-10-10 11:46 UTC, merged