fix- Can't disable "Show remaining" and "Show button time"
ankidroid/Anki-Android pull request #14512
Opened 2023-10-04 20:54 UTC by vyom198

## Purpose / Description
_Can't disable "Show remaining" and "Show button time" in the appearance section in settings_

## Fixes
Fixes _https://github.com/ankidroid/Anki-Android/issues/14502_

## Approach
_Casting the value of newDueCountsValue and newETA to Boolean and passed the values to config.set() method_

## How Has This Been Tested?
_in the emulator_

https://github.com/ankidroid/Anki-Android/assets/112750331/d5441547-64a2-41c2-b78a-880a709842b8

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-10-09 05:57 UTC, lukstbit approved these changes
LGTM, thank you for contributing!

2023-10-13 23:27 UTC, BrayanDSO requested changes

2023-10-13 23:27 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
> +                val newDueCountsValueBool = newDueCountsValue as? Boolean ?: false
I suggest returning false inside the listener here, so the preference value isn't changed if the value for some reason is null.

Same for the above change

2023-10-14 06:08 UTC, vyom198 commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
> +                val newDueCountsValueBool = newDueCountsValue as? Boolean ?: false
should i make new pull request with the requested changes?

2023-10-15 18:24 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
>              }
Here's what I mean with returning false at the listener
```suggestion
            setOnPreferenceChangeListener { _, newETA ->
                val newETABool = newETA as? Boolean ?: return@setOnPreferenceChangeListener false
                launchCatchingTask { withCol { config.set("estTimes", newETABool) } }
                true
            }
```

2023-10-15 18:25 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
> +                val newDueCountsValueBool = newDueCountsValue as? Boolean ?: false
See the comment below

2023-10-16 03:30 UTC, vyom198 commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
>              }
should i create new pull request with the requested changes?

2023-10-16 15:50 UTC, BrayanDSO approved these changes

2023-10-16 15:50 UTC, merged