Snackbar for Audio was added
ankidroid/Anki-Android pull request #14523
Opened 2023-10-07 17:34 UTC by ABHAYISm

## Purpose / Description
Show a snackbar instead of a toast II #13411

## Fixes
#13411

## Approach
Toast as changed to this.showSnackbar()

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-10-08 06:01 UTC, lukstbit requested changes

2023-10-08 06:01 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +            if (grantResults[0] != PackageManager.PERMISSION_GRANTED) {
The new code is not equivalent to the old code. You should replace **only** the `showThemedToast()` call with a call to `showSnackbar()`.

2023-10-09 17:04 UTC, ABHAYISm commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +            if (grantResults[0] != PackageManager.PERMISSION_GRANTED) {
Tried doing that way first time around, But it was creating some bug resulting in popup time of Snackbar decrease to less than 1 second. Hence i had to make some changes in old code.

2023-10-10 07:59 UTC, lukstbit commented
I'm going to close this as this specific Toast shouldn't be replaced with a SnackBar and I'm going to add a notice on the original issue about this.

Feel free to look at other Toasts that might be replaced.

2023-10-10 07:59 UTC, closed without merging