Robolectric 4.11 for API34 testing
ankidroid/Anki-Android pull request #14557
Opened 2023-10-18 20:55 UTC by mikehardy

## Purpose / Description

**The last commit here will be what lands if merged, ignore other commits**

To test API34 items we need robolectric 4.11 which is only available in snapshot form at the moment

This PR is not a high priority, and is based on #14556 so will need a rebase after that lands regardless,

## Fixes

## Approach
Adopt the snapshot version, handle behavior changes, switch up downloads

## How Has This Been Tested?

Local `jacocoUnitTestReport` and lint runs

## Learning (optional, can help others)
snapshots are in a fully separate repository and you have to explicitly add it to access it.

There is some unrelated information about updating dependencies if they are snapshots, involving setting "changing" to true in the dependency definition in the gradle files, and setting how long to cache them and such. I ignored that for now though as the current snapshot works fine and we won't need to update it as far as I can see, until we adopt 4.11 non-snapshot version

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-10-18 20:58 UTC, mikehardy commented
mostly posting this as I made a local attempt to actually bump `targetSdk` to 34 - not just `compileSdk` as proposed in #14556 and this was part of the effort that I wanted to preserve for that future effort.

I aborted doing that full effort for now as simply targetting API34 implies we must handle the dynamic context receiver export issue that I noted in https://github.com/ankidroid/Anki-Android/pull/14158#issuecomment-1767348440 or the app crashes when those dynamic receivers are registered, and I didn't have time to handle it fully here.

2023-10-27 22:02 UTC, david-allison requested changes
I'm concerned the test failure is an issue - I'm in Locale land right now and it's hairy

2023-10-27 22:02 UTC, david-allison commented on api/build.gradle.kts
> +        targetSdk = 33
This feels like it deserves its own commit - change is fine, but sdk bumps are big ones

2023-10-30 14:46 UTC, mikehardy commented on api/build.gradle.kts
> +        targetSdk = 33
yes in fact! I'm superceding this one by the one dependabot proposed, and as I moved these changes to that branch I chunked up the work as it should be - this did get its own commit there and rightly so !

2023-10-30 14:47 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt
> +            // assertThat(LanguageUtil.getCurrentLocaleTag(), equalTo(languageTag))
was bizarre, the language tag comes through from the context as empty string every time - unexpected, and somewhere in robolectric depths. works on real device

2023-10-30 14:48 UTC, closed without merging

2023-10-30 14:48 UTC, mikehardy commented
superceded by #14617 - pulled the necessary adjustments into that branch as clean / separate commits - this was more speculative / to store the work in case robolectric didn't release for a long time + to preserve the effort but I never really wanted to pull snapshot repo in, thankfully no need