Fix backgrounding freezing app until sync finishes
ankidroid/Anki-Android pull request #14577
Opened 2023-10-23 00:26 UTC by dae

- Don't block the main thread in onStop() and onResume()
- Suppress multiple progress windows, so that the deck refresh that happens on onResume() doesn't cover sync progress

Closes #14197

2023-10-23 07:27 UTC, david-allison requested changes
Requesting a comment on the logic (if it's not a bug)

2023-10-23 07:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        WidgetStatus.updateInBackground(this@DeckPicker)
✅

This uses `.withCol` and is therefore safe

https://github.com/ankidroid/Anki-Android/blob/7a65160e0e23e20080091a30abdd4c05fc610e06/AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt#L96-L106

2023-10-23 07:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
> +        mNavigationView!!.setNavigationItemSelectedListener(this)
nit: preference for `.apply` to remove the `!!`

2023-10-23 07:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +        AnkiDroidApp.instance.progressDialogShown = false
Could do with a comment, I don't understand this logic from a quick glance:

* A dialog is showing (`progressDialogShown == true` )
* `withProgressDialog` is called a second time
* What stops this line from being executed and `progressDialogShown` being `false` with a dialog showing?

2023-10-23 07:29 UTC, david-allison commented
Also: any opposition to squashing, given some intermediate commits fail tests

2023-10-23 21:28 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +        AnkiDroidApp.instance.progressDialogShown = false
Thanks, good catch.

2023-10-23 21:28 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
> +        mNavigationView!!.setNavigationItemSelectedListener(this)
Using .apply on findViewById() complains that it can't infer the type of the variable

2023-10-23 21:28 UTC, dae commented
Squash would be good

2023-10-24 18:44 UTC, BrayanDSO approved these changes
Valuable progress. But for the future we need to reorganize how dialogs and UI updates are handled to avoid piling up things and creating more bugs

2023-10-24 18:44 UTC, merged