replacing the existing audio recorder
ankidroid/Anki-Android pull request #14591
Opened 2023-10-26 21:30 UTC by criticalAY

## Purpose / Description
DRAFT PR!!

The existing Audio player has a poor UI and there is no timeline or a tracking that makes it clear that the recording has started.
This makes it difficult to track the recording, therefore this code would replace the existing audio recorder with a better UI, here
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/65c9bbaf-8494-45ce-a737-647167eaae70)

## Fixes
Fixes #13043 

## How Has This Been Tested?
yet to be tested

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-10-27 14:51 UTC, criticalAY commented
@david-allison could you please help me with this, I am not able to see the .3gp file in the edit field when Im clicking done ✅, could you point it out ?

2023-10-29 12:39 UTC, BrayanDSO reviewed
Functionality-wise seems pretty good. My remarks about it are:

1. The waveform goes right-to-left here and I believe that left-to-right is more natural for LTR reading people (idk about RTL reading people)
2. It seems like the waveform is too sensible, so any sound I make makes it produce a maximum wavesound, so there isn't a good distinction between what is louder and what is quieter


https://github.com/ankidroid/Anki-Android/assets/69634269/07b06aec-c763-4869-8e56-8d6127146cce

Here is an example of what Samsung voice recorder does (LTR recording and more sensibility to sound levels)

https://github.com/ankidroid/Anki-Android/assets/69634269/692e7cfd-60bd-4a5b-92d2-3bca78b1d4b4

2023-10-29 12:41 UTC, BrayanDSO commented
Now that I'm reviewing the videos, the quick time update (i.e. showing hundredths of seconds) in Samsung voice recorder makes it more fluid

2023-10-29 12:42 UTC, BrayanDSO commented
Also, a way to hear the recorded audio before saving, like the previous recorder did, would be good.

2023-10-29 12:48 UTC, BrayanDSO commented
Other thing: if the audio is already saved, i.e. the user pressed the ✔️ button and `Recording saved` appeared, it would be good to not dismiss it bby mistake if the user press the back button

2023-10-29 12:50 UTC, BrayanDSO commented
For trying to kill two birds with a stone of adding this to the edit field and reviewer, you could make a DialogFragment (or bottom sheet one) and completely dismiss using the MultimediaEditor activity for this

2023-10-29 21:58 UTC, criticalAY commented
Ok, would go for the bottom dialogsheet and add the functionality to listen to the audio recording

2023-10-30 17:50 UTC, criticalAY commented
Reason for not using the bottomsheet or dialog fragment : 
>Edit: check pronunciation option enables a toolbar having the audio recorder that would not be possible if we use bottom sheet though we can use it for the edit note but would not that be too much for this portion

![Screenshot 2023-10-30 231716](https://github.com/ankidroid/Anki-Android/assets/48384865/3debff23-d9db-4605-b791-d7db62f0205f)
![Screenshot 2023-10-30 231725](https://github.com/ankidroid/Anki-Android/assets/48384865/599adb2d-1cef-44d8-b731-f9a5a584cce6)
![Screenshot 2023-10-30 231733](https://github.com/ankidroid/Anki-Android/assets/48384865/a4b6753b-fe76-4b31-a849-026ff4b8d71e)

I will come up with a optimised layout for the reviewer using the existing code and finally eliminating the need for the redundant files (AudioPLayer, AudioView)

2023-10-30 23:14 UTC, BrayanDSO commented
> Edit: check pronunciation option enables a toolbar having the audio recorder that would not be possible if we use bottom sheet though we can use it for the edit note but would not that be too much for this portion

I don't see why it can't be reused in the reviewer as a bottom sheet dialog. The only pratical difference I see between the `Edit field` and the `Check pronunciation` is that the file isn't saved in `Check pronunciation`.

2023-10-31 06:16 UTC, criticalAY commented
We can use the bottom sheet fragment in the note editor section but not in the reviewer section as that option once enabled stays there until we turn it off again so I don't find a motivation to write excess code for just the note editor section to implement the bottom sheet

2023-10-31 22:44 UTC, criticalAY commented
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/8691c6e7-28c9-4501-90c9-f632eb1f871d)

2023-11-01 21:54 UTC, david-allison requested changes
I LOVE the screenshots

I feel like I'm going to be commenting on functionality which is copy/pasted from `AudioView/AudioRecorder`,

It'd be useful if the common functionality is refactored (either made public/companion/extracted) to ensure we don't only make fixes/changes in one place

2023-11-01 21:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +            }
We likely want haptics here: https://developer.android.com/develop/ui/views/haptics/haptics-principles#legacy

2023-11-01 21:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +        }
I'd move these methods to `.apply {}` on the variables they refer to

2023-11-01 21:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +    private fun generateTempAudioFile(context: Context): String? {
Instead of creating a new function, remove duplication

2023-11-01 21:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +        }
`onRecordingInitialized?.run()`

2023-11-01 21:54 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="audio_text">00:00:00</string>
If only this is localised, it'll be removed as soon as the timer starts

2023-11-01 22:10 UTC, criticalAY commented
> I feel like I'm going to be commenting on functionality which is copy/pasted from `AudioView/AudioRecorder`,
> 
> It'd be useful if the common functionality is refactored (either made public/companion/extracted) to ensure we don't only make fixes/changes in one place

Umm, I made some changes to AudioRecorder as recordings can be paused in case of new APIs and took some code from `AudioView` (I would remove it completely) so that my reason for not touching AudioView, for now, is that when I take care of reviewer in the next phase I would delete this file and then make some refactors in the new `AudioRecorderController` .

2023-11-01 22:57 UTC, david-allison reviewed
Only nitpicks: this is MUCH better and could be released as-is

* I feel the drawing could be a little more fluid
* It would be nicer if it were left to right
* I feel the update of the text could be more fluid (both more frequent, and it's unusual that the final digit doesn't change)
* I feel I 'lose my place' in the recording before it starts to scroll, having the vertical line as in Brayan's Samsung recording would help
* Vibration is great, could it be added to 'delete' and 'accept' as well?

2023-11-01 22:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.kt
> +    private lateinit var mediaRecorder: MediaRecorder
either:

1. Rebase to ensure the PR can be squashed, and add the rename as a refactoring commit
   * Right now due to failing commits, it needs to be squashed 
2. Don't do the refactor as it adds line noise to the commit
3. Split off the refactor into another PR
   * Likely not the best choice as it holds up this PR for no real reason, and you can't guarantee the order of merges

2023-11-01 22:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.kt
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
Doesn't check for this::mediaRecorder.isInitialized

2023-11-01 22:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.kt
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
Doesn't check for this::mediaRecorder.isInitialized

2023-11-01 22:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +    private fun generateTempAudioFile(context: Context): String? {
This still feels duplicated

2023-11-01 22:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +        tempAudioPath = generateTempAudioFile(context)
this seems unusual and can likely be merged into a line

2023-11-01 22:59 UTC, david-allison commented
Bug:

* Record
* Press the 'tick'
* Press 'Back'

Recording is not moved to the card

2023-11-01 23:10 UTC, david-allison commented
(For discussion)

Is there a lot of user desire to 'append' to their recording?

I feel the typical + optimal workflow is:

* Record Audio
* (optional playback)
* Save + Exit

and we should optimise for this:

* A user wants to save immediately (maybe using the app bar button, but I don't feel this touch target is large enough)

States:

* **Initial State**
   * `(x) (record) (x)`
* **Recording**
   * `(x) (pause) (x)`
* **Audio Recorded**
   * `(delete) (play) (save)`
   * I would probably place the 'record more' button at the end of the audio visualisation, 

(play)

2023-11-01 23:12 UTC, david-allison commented
Buttons could do with being a little larger (can we scale them to the screen size)?

<details>

<summary>Example from LINE on my phone</summary>

![image](https://github.com/ankidroid/Anki-Android/assets/62114487/0d724196-093e-4a15-a037-24ce87c7b186)
![image](https://github.com/ankidroid/Anki-Android/assets/62114487/9f3f226f-74a9-4529-8529-8dde6133449a)

</details>

2023-11-01 23:19 UTC, BrayanDSO commented
> Is there a lot of user desire to 'append' to their recording?

Probably not. My guess is that even the recording itself isn't a popular feature.

> (can we scale them to the screen size)

yes, but I suggest using dp either way to avoid having enormous buttons in tablets

> (maybe using the app bar button, but I don't feel this touch target is large enough)

The default back bar button seems good enough to me, but maybe it would be nice to replace it with a bigger one somewhere else (bottom left of the screen would be best I guess), but for now I'd leave it as is and focus on the rest.

2023-11-01 23:22 UTC, david-allison commented
I'm using a deck which was recorded entirely in AnkiDroid, it definitely sees use

2023-11-02 01:23 UTC, criticalAY commented
> Bug:
> 
> * Record
> * Press the 'tick'
> * Press the Android 'Back' button
> 
> Recording is not moved to the card

[x] - Fixed

2023-11-02 01:34 UTC, criticalAY commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="audio_text">00:00:00</string>
should I remove it and simply hard code it?

2023-11-02 16:11 UTC, david-allison commented
Even better. I'd say the UX of this is some of the best of the app

While the recording is starting, the 'progress line' doesn't match the start of the audio. In [Brayan's screenshot](https://github.com/ankidroid/Anki-Android/assets/62114487/b95d879c-7d4a-4c50-881f-b190c0f7aad1), it starts from the left

* make the middle button larger

* The current middle button icon screams 'recording has started' rather than 'recording has yet to begin' 
  * Make the 'start recording' symbol inside the middle button smaller

Following on: I found that the screen felt much more responsive when `delay` was set to `25` rather than `100`. Setting it too low meant that `maxAmplitude` returned 0.
* I would also scale the 'speed/width' of the bar based on the delay, as changing the delay means less is shown on the screen. Let's aim to see a minimum of 5 seconds on the screen on mobile

One `formatTimer` method is unused in `AudioTimer`

I'd consider re-tweaking the scaling

2023-11-02 16:19 UTC, david-allison reviewed
We should ensure that the screen doesn't turn off while audio is recording

2023-11-02 16:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.kt
> +            mRecorder.maxAmplitude
`maxAmplitude` documentation says:

> Returns the maximum absolute amplitude that was sampled since the last call to this method.


If we get a value of 0, we should return the previously recorded non-0 amplitude. This should smooth out some of the 'blips' I see when I move the delay to a lower value

2023-11-02 16:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.kt
>          }
No need for the null check. Just `mOnRecordingInitialized?.run()`

2023-11-02 20:08 UTC, criticalAY commented
> I'd consider re-tweaking the vertical scaling
as in?

2023-11-02 20:19 UTC, criticalAY commented
Tablet:
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/7a29b9cd-6976-4df9-9881-387da1232929)

Phone:
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/7bdd05d6-984d-489d-94cb-c5cc3d34aee6)

2023-11-02 21:27 UTC, criticalAY commented
>While the recording is starting, the 'progress line' doesn't match the start of the audio. In [Brayan's screenshot](https://github.com/ankidroid/Anki-Android/assets/62114487/b95d879c-7d4a-4c50-881f-b190c0f7aad1), it starts from the left

This would need a little work here in `onDraw` would leave a TODO for this and handle it in follow ups

2023-11-02 23:28 UTC, david-allison approved these changes
Pic of me testing this 👍👍👍

![](https://media.giphy.com/media/C4NfiF2x3DTGw/giphy.gif)

Nothing blocking

2023-11-02 23:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.kt
> +        if (this::mRecorder.isInitialized) {
nit: in general it's better to invert the condition and return early to reduce nesting

2023-11-02 23:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +            CompatHelper.compat.vibrate(context, 20)
Haptics would likely be better here

2023-11-02 23:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +// TODO: forwards & rewind have 1000 jump time and UI shows 5 fix the UI
This one might be a blocker. Implementer's choice

2023-11-03 02:16 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +// TODO: forwards & rewind have 1000 jump time and UI shows 5 fix the UI
> // TODO: forwards & rewind have 1000 jump time and UI shows 5 fix the UI

Fixed

2023-11-03 02:17 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +            CompatHelper.compat.vibrate(context, 20)
After this one for sure would take care of it

2023-11-03 02:17 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.kt
> +        if (this::mRecorder.isInitialized) {
done!

2023-11-03 02:38 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +// TODO: forwards & rewind have 1000 jump time and UI shows 5 fix the UI
OnePlus has this flicker but I want it to be smooth so leaving this TODO

2023-11-04 00:10 UTC, BrayanDSO reviewed
It is a HUGE advancement for audio recording and looks pretty good. 

---
Alhough, some issues I found:
1. Changing system dark mode with `Follow system` theme finishes the activity (should be handled later)
2. If I tap back while playing back an audio, the audio keeps playing
3. I can't cancel saving the audio after recorded if I didn't like the result

The rest of my comments is mostly nits

2023-11-04 00:12 UTC, BrayanDSO commented on AnkiDroid/src/main/res/layout/activity_audio_recording.xml
> +<LinearLayout android:id="@+id/audioView"
Or maybe don't if it is too much trouble, since `MultimediaEditFieldActivity` should be gone someday

2023-11-04 01:51 UTC, criticalAY commented on AnkiDroid/src/main/res/layout/activity_audio_recording.xml
> +<LinearLayout android:id="@+id/audioView"
When I started it was `CoordinatorLayout` but I later changed it to Linear as it a view that takes only half the screen so its always gonna be a child layout

2023-11-04 15:38 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +            prepare()
sure! honestly didn't notice until you commented

2023-11-04 16:08 UTC, criticalAY commented
Not wanting to stretch this PR so I would handle this in the follow up there are few things that need to be done along with this
> Changing system dark mode with Follow system theme finishes the activity (should be handled later)
> If I tap back while playing back an audio, the audio keeps playing
> I can't cancel saving the audio after recorded if I didn't like the result

The whole MultimediaAudioRecorder is destroyed and I am aware of the audio-playing issue (current audio player also have this issue),
I would add the functionality to reset the audio after this code is merged.

2023-11-04 22:49 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +    }
Not resolved

2023-11-04 22:49 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +    private lateinit var audioFileView: ShapeableImageView
Not resolved

2023-11-04 22:50 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +    private var jumpValue = 5000
Not resolved. here I mean `const val`, not `val`

2023-11-04 23:01 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
> +    }
done

2023-11-04 23:01 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +    private lateinit var audioFileView: ShapeableImageView
done for all now

2023-11-04 23:25 UTC, criticalAY commented
@BrayanDSO ✅ done

2023-11-05 23:57 UTC, BrayanDSO approved these changes

2023-11-05 23:57 UTC, merged