Improve preferences activity style and add a large screen layout
ankidroid/Anki-Android pull request #14603
Opened 2023-10-28 12:36 UTC by BrayanDSO

## Purpose / Description
Depends on/Blocked by #14596

## Fixes
Part of #13878 

## Approach
In the commits

## How Has This Been Tested?

33 resizable emulator:
I'll upload the videos ASAP

## Learning (optional, can help others)

You can't set a toolbar title directly if there is a CollpasingToolbarLayout https://stackoverflow.com/questions/26486730/in-android-app-toolbar-settitle-method-has-no-effect-application-name-is-shown

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-10-28 13:54 UTC, BrayanDSO commented
Pending things that you may note:
1. The statusBar color is still light blue, which is something I want to fix in the future together with other things
2. I haven't removed the `screenSize` configChange from the manifest because this doesn't deal with screen resizes at the moment. If I assessed the work correctly, I'd need to create a custom backstack and fragment managers so I can propertly restore/replace the fragments when the screen is resized (i.e. too much work for a too small reward)

2023-10-28 21:27 UTC, criticalAY commented
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/6dad6e7c-0600-4eff-af19-27474e9d30ba)
We should have this UI style (App showing along side the back icon) the current app bar is odd? The screen is scrolled leading to the actual way of doing it but initially the app bar and the title are not aligned

2023-10-28 22:40 UTC, BrayanDSO commented
New Material 3 thing: https://m3.material.io/components/top-app-bar/specs. Have seen this in other apps, specially in iOS ones (notes, photos, app store, google agenda, PDF expert) and that's what I think that Material is perhaps trying to copy

2023-10-29 00:59 UTC, criticalAY commented
Umm there are 4 options available depending upon the use case
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/626aab3b-de91-40a4-9d19-cc189c215eba)
wouldn't this cause an issue on the small screen, taking a little more space? 
I am fine with both 2 & 3 though

2023-10-29 09:02 UTC, BrayanDSO commented
> wouldn't this cause an issue on the small screen, taking a little more space?

I don't think so, since it is compressible. Also, phone screen size average only gets bigger

2023-11-01 01:36 UTC, BrayanDSO commented
For reference, I intend to make the title bold later, like other apps do (especially iOS ones), but I'd like to do this kind of change altogether (i.e. change font-weight in different places of the app)

e.g.
![Pasted image 20230725194714](https://github.com/ankidroid/Anki-Android/assets/69634269/6fd2229d-ca35-422e-b178-80d6542416b7)

e.g. 2
![image](https://github.com/ankidroid/Anki-Android/assets/69634269/22dd171a-e607-4c08-b180-a4c5e7167d4a)

2023-11-04 08:58 UTC, lukstbit commented
Looks pretty good from what I saw but I really don't like the toolbar and empty space, seems wasteful. The main issue is that we don't have toolbar menu options to kind of "break" the space so its pretty continuous, this becomes more obvious in phone landscape or with drawing based languages(japanese or chinese) which use even smaller spaces for the Settings title. Also there will be phones were that extra space will force the user to scroll and we should avoid this.


My option for the toolbar is number 2 in the image above, but feel free to wait for other opinions as well.

2023-11-04 22:46 UTC, BrayanDSO commented
> this becomes more obvious in phone landscape

I don't think that any of the app screens is good in phones landscape mode. Tablets/Chromebooks could benefit of it, but spending time adequating the app for phones landscape mode shouldn't be a goal.

> Also there will be phones were that extra space will force the user to scroll and we should avoid this.

We can, or better **should**, use low-dp layouts for those kind of cases. 

---
Also, I think that 3 is fine too. And would avoid 2 since it is too generic/bland IMHO

2023-11-05 20:34 UTC, criticalAY commented
I personally like 2 but am fine with 3 also as M3 allows us to use that in small screens also

2023-11-07 23:41 UTC, BrayanDSO commented
Seems pretty handy. I'll take a look at it. Thanks!

2023-11-08 17:30 UTC, BrayanDSO commented
> Seems pretty handy. I'll take a look at it. Thanks!

Won't do. Doesn't fit exactly the layout, since in the tablets' layout the app bar is only above the lateral fragment, not above the main one. If I find an easy solution, I'll fix it eventually, but for now I don't think that it is worth the trouble

2023-11-11 12:45 UTC, mikehardy approved these changes
I think it looks great - with respect, I have read the qualitative disagreements, and they have merit but the defenses from Brayan were also pretty solid. It seemed like a good discussion, with a productive experiment in response even, despite abandoning it.

Given that the ideas appear to have been explored, the existing implementation looks pretty good in my personal opinion, others seem to accept it as at least acceptable, and Brayan - who is actually doing the work - likes it, I'm going to say we should maintain velocity here and get this in

2023-11-11 20:58 UTC, david-allison requested changes
Consider this an 'approve' once license issues are discussed.

2023-11-11 20:58 UTC, david-allison commented on AnkiDroid/src/main/res/layout-sw600dp/preferences.xml
> +<?xml version="1.0" encoding="utf-8"?>
no license

2023-11-11 20:59 UTC, david-allison commented on AnkiDroid/src/main/res/layout/preferences.xml
> -  ~  Copyright (c) 2021 David Allison <davidallisongithub@gmail.com>
License was removed - I don't mind removing my name (IDE default)

But we should stick with the GPL guidance

2023-11-13 11:31 UTC, BrayanDSO commented
Licenses added

2023-11-13 14:06 UTC, mikehardy commented
From David:

> Consider this an 'approve' once license issues are discussed.

From Brayan: 

>  Licenses added

👆 verified

2023-11-13 14:06 UTC, merged