review count in deck picker
ankidroid/Anki-Android pull request #14607
Opened 2023-10-28 15:18 UTC by soCallmeAdityaKumar

## Purpose / Description
Day Reviewed cards count was not displayed at the bottom of the home screen

## Fixes
#14600 

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-10-28 15:57 UTC, BrayanDSO commented
Hi. In the PR layout there is a `How has this been tested section`. Please don't erase it and try filling it. Preferentially with a screenshot showing the results

2023-10-28 17:22 UTC, soCallmeAdityaKumar commented
> Hi. In the PR layout there is a `How has this been tested section`. Please don't erase it and try filling it. Preferentially with a screenshot showing the results

@BrayanDSO i have added the screenshot

2023-10-28 18:32 UTC, user1823 commented
This doesn't look nice. In 2.16, the text was in a single line.

2023-10-28 20:56 UTC, BrayanDSO commented
> This doesn't look nice. In 2.16, the text was in a single line.

Agreed. Please fix that @soCallmeAdityaKumar

2023-10-30 00:08 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                mReviewSummaryTextView.setSingleLine()
Can you set the textview to use a singleLine in the XML?

2023-10-30 05:50 UTC, lukstbit requested changes

2023-10-30 05:50 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                mReviewSummaryTextView.text = sched.studiedToday()
withCol runs its lambda on a background thread so the text shouldn't be updated there:

`mReviewSummaryTextView.text = withCol { sched.studiedToday() }`

2023-10-30 06:27 UTC, soCallmeAdityaKumar commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                mReviewSummaryTextView.setSingleLine()
If i use ```android:singleLine="true"``` or ```android:maxLines="1"``` then only "Studied 1 card...." is shown

2023-10-30 06:46 UTC, lukstbit approved these changes
LGTM, thanks!

2023-10-30 13:33 UTC, BrayanDSO approved these changes
LGTM. Thanks!

2023-10-30 13:33 UTC, merged