feat: TTS Support (button & {{tts-voices}}) [DRAFT]
ankidroid/Anki-Android pull request #14628
Opened 2023-10-31 20:35 UTC by david-allison

⚠️ Draft for architectural review - some cleanup and testing pending

* This is based off https://github.com/ankidroid/Anki-Android/pull/14597

## Purpose / Description
* Handles `{{tts-voices}}`
* Enables playing TTS when the "audio" button on the card is pressed

## Fixes
* Partially #14358

## Approach

## ~~How Has This Been Tested?~~

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## ~~Learning (optional, can help others)~~
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-10-31 20:44 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt
> +// a name looks like: com.google.android.tts-cmn-cn-x-ccc-local
Review: 

In Android, there are multiple potential engines, and a user may add their own

Currently, we only support one Engine at the same time, but in a future PR, we should investigate whether we can support voices from more than one at once.

For now, I can test two engines: Samsung and Google

Both have 'awful' names:

* `tts-cmn-cn-x-ccc-local`

Changing names is a breaking change.

Do we want to reformat these names to be more 'readable'?

I'm tempted to say 'no', although Anki Desktop does this: https://github.com/ankitects/anki/blob/9600f033f745bfae4e00dd9fa43e44d3b30c22d2/qt/aqt/tts.py

If we reformatted a name to say 'Chinese (Local)", then this becomes a locale dependent string.

I feel a better alternative would be to change the display name in `{{tts-voices}}`

Other engines will still have awful names

2023-10-31 20:44 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt
> +        return "$buf</div>"
We may want to do better here: maybe sorting on 'availability' when listing

Google provides a MASSIVE number of voices and this is hard to navigate (although it's only once, and it's for advanced users).

The output is too large for Google Keep to accept.

Here's an old copy
<details>

```
TTS voices available:
{{tts ar voices=com.google.android.tts-ar-language}} (unavailable)
{{tts ar voices=com.google.android.tts-ar-xa-x-ard-network}} (unavailable)
{{tts ar voices=com.google.android.tts-ar-xa-x-are-local}} (unavailable)
{{tts ar voices=com.google.android.tts-ar-xa-x-arc-local}} (unavailable)
{{tts ar voices=com.google.android.tts-ar-xa-x-ard-local}} (unavailable)
{{tts ar voices=com.google.android.tts-ar-xa-x-arz-local}} (unavailable)
{{tts ar voices=com.google.android.tts-ar-xa-x-are-network}} (unavailable)
{{tts ar voices=com.google.android.tts-ar-xa-x-arz-network}} (unavailable)
{{tts ar voices=com.google.android.tts-ar-xa-x-arc-network}} (unavailable)
{{tts bg_BG voices=com.google.android.tts-bg-bg-x-ifk-local}} (unavailable)
{{tts bg_BG voices=com.google.android.tts-bg-bg-x-ifk-network}} (unavailable)
{{tts bg_BG voices=com.google.android.tts-bg-bg-language}} (unavailable)
{{tts bn_BD voices=com.google.android.tts-bn-BD-language}} (unavailable)
{{tts bn_BD voices=com.google.android.tts-bn-bd-x-ban-network}} (unavailable)
{{tts bn_BD voices=com.google.android.tts-bn-bd-x-ban-local}} (unavailable)
{{tts bn_IN voices=com.google.android.tts-bn-in-x-bin-network}} (unavailable)
{{tts bn_IN voices=com.google.android.tts-bn-IN-language}} (unavailable)
{{tts bn_IN voices=com.google.android.tts-bn-in-x-bnx-network}} (unavailable)
{{tts bn_IN voices=com.google.android.tts-bn-in-x-bnm-network}} (unavailable)
{{tts bn_IN voices=com.google.android.tts-bn-in-x-bnf-network}} (unavailable)
{{tts bn_IN voices=com.google.android.tts-bn-in-x-bnf-local}} (unavailable)
{{tts bn_IN voices=com.google.android.tts-bn-in-x-bin-local}} (unavailable)
{{tts bn_IN voices=com.google.android.tts-bn-in-x-bnm-local}} (unavailable)
{{tts bn_IN voices=com.google.android.tts-bn-in-x-bnx-local}} (unavailable)
{{tts bs_BA voices=com.google.android.tts-bs-ba-x-bsm-local}} (unavailable)
{{tts bs_BA voices=com.google.android.tts-bs-ba-language}} (unavailable)
{{tts bs_BA voices=com.google.android.tts-bs-ba-x-bsm-network}} (unavailable)
{{tts ca_ES voices=com.google.android.tts-ca-ES-language}} (unavailable)
{{tts ca_ES voices=com.google.android.tts-ca-es-x-caf-network}} (unavailable)
{{tts ca_ES voices=com.google.android.tts-ca-es-x-caf-local}} (unavailable)
{{tts cs_CZ voices=com.google.android.tts-cs-cz-x-jfs-local}} (unavailable)
{{tts cs_CZ voices=com.google.android.tts-cs-cz-x-jfs-network}} (unavailable)
{{tts cs_CZ voices=com.google.android.tts-cs-CZ-language}} (unavailable)
{{tts cy_GB voices=com.google.android.tts-cy-gb-x-cyf-local}} (unavailable)
{{tts cy_GB voices=com.google.android.tts-cy-gb-x-cyf-network}} (unavailable)
{{tts cy_GB voices=com.google.android.tts-cy-GB-language}} (unavailable)
{{tts da_DK voices=com.google.android.tts-da-dk-x-sfp-network}} (unavailable)
{{tts da_DK voices=com.google.android.tts-da-DK-language}} (unavailable)
{{tts da_DK voices=com.google.android.tts-da-dk-x-nmm-network}} (unavailable)
{{tts da_DK voices=com.google.android.tts-da-dk-x-nmm-local}} (unavailable)
{{tts da_DK voices=com.google.android.tts-da-dk-x-vfb-network}} (unavailable)
{{tts da_DK voices=com.google.android.tts-da-dk-x-kfm-network}} (unavailable)
{{tts da_DK voices=com.google.android.tts-da-dk-x-kfm-local}} (unavailable)
{{tts da_DK voices=com.google.android.tts-da-dk-x-vfb-local}} (unavailable)
{{tts da_DK voices=com.google.android.tts-da-dk-x-sfp-local}} (unavailable)
{{tts de_DE voices=com.google.android.tts-de-de-x-deb-network}} (unavailable)
{{tts de_DE voices=com.google.android.tts-de-DE-language}} (unavailable)
{{tts de_DE voices=com.google.android.tts-de-de-x-dea-network}} (unavailable)
{{tts de_DE voices=com.google.android.tts-de-de-x-deg-network}} (unavailable)
{{tts de_DE voices=com.google.android.tts-de-de-x-deb-local}} (unavailable)
{{tts de_DE voices=com.google.android.tts-de-de-x-deg-local}} (unavailable)
{{tts de_DE voices=com.google.android.tts-de-de-x-nfh-local}} (unavailable)
{{tts de_DE voices=com.google.android.tts-de-de-x-nfh-network}} (unavailable)
{{tts de_DE voices=com.google.android.tts-de-de-x-dea-local}} (unavailable)
{{tts el_GR voices=com.google.android.tts-el-GR-language}} (unavailable)
{{tts el_GR voices=com.google.android.tts-el-gr-x-vfz-local}} (unavailable)
{{tts el_GR voices=com.google.android.tts-el-gr-x-vfz-network}} (unavailable)
{{tts en_AU voices=com.google.android.tts-en-AU-language}} (unavailable)
{{tts en_AU voices=com.google.android.tts-en-au-x-aua-network}} (unavailable)
{{tts en_AU voices=com.google.android.tts-en-au-x-aud-local}} (unavailable)
{{tts en_AU voices=com.google.android.tts-en-au-x-aua-local}} (unavailable)
{{tts en_AU voices=com.google.android.tts-en-au-x-auc-network}} (unavailable)
{{tts en_AU voices=com.google.android.tts-en-au-x-aub-local}} (unavailable)
{{tts en_AU voices=com.google.android.tts-en-au-x-aub-network}} (unavailable)
{{tts en_AU voices=com.google.android.tts-en-au-x-aud-network}} (unavailable)
{{tts en_AU voices=com.google.android.tts-en-au-x-auc-local}} (unavailable)
{{tts en_GB voices=com.google.android.tts-en-gb-x-gba-local}}
{{tts en_GB voices=com.google.android.tts-en-gb-x-gbb-network}}
{{tts en_GB voices=com.google.android.tts-en-gb-x-rjs-local}}
{{tts en_GB voices=com.google.android.tts-en-gb-x-gbg-local}}
{{tts en_GB voices=com.google.android.tts-en-gb-x-gbd-local}}
{{tts en_GB voices=com.google.android.tts-en-gb-x-gbd-network}}
{{tts en_GB voices=com.google.android.tts-en-gb-x-gbb-local}}
{{tts en_GB voices=com.google.android.tts-en-gb-x-gbc-local}}
{{tts en_GB voices=com.google.android.tts-en-GB-language}}
{{tts en_GB voices=com.google.android.tts-en-gb-x-gba-network}}
{{tts en_GB voices=com.google.android.tts-en-gb-x-gbc-network}}
{{tts en_GB voices=com.google.android.tts-en-gb-x-rjs-network}}
{{tts en_GB voices=com.google.android.tts-en-gb-x-gbg-network}}
{{tts en_IN voices=com.google.android.tts-en-in-x-end-network}} (unavailable)
{{tts en_IN voices=com.google.android.tts-en-in-x-ene-local}} (unavailable)
{{tts en_IN voices=com.google.android.tts-en-in-x-end-local}} (unavailable)
{{tts en_IN voices=com.google.android.tts-en-in-x-enc-local}} (unavailable)
{{tts en_IN voices=com.google.android.tts-en-in-x-enc-network}} (unavailable)
{{tts en_IN voices=com.google.android.tts-en-in-x-ene-network}} (unavailable)
{{tts en_IN voices=com.google.android.tts-en-in-x-ena-network}} (unavailable)
{{tts en_IN voices=com.google.android.tts-en-IN-language}} (unavailable)
{{tts en_IN voices=com.google.android.tts-en-in-x-ena-local}} (unavailable)
{{tts en_NG voices=com.google.android.tts-en-NG-language}} (unavailable)
{{tts en_NG voices=com.google.android.tts-en-ng-x-tfn-network}} (unavailable)
{{tts en_NG voices=com.google.android.tts-en-ng-x-tfn-local}} (unavailable)
{{tts en_US voices=com.google.android.tts-en-us-x-tpf-local}}
{{tts en_US voices=com.google.android.tts-en-us-x-sfg-network}}
{{tts en_US voices=com.google.android.tts-en-us-x-sfg-local}}
{{tts en_US voices=com.google.android.tts-en-us-x-iob-local}}
{{tts en_US voices=com.google.android.tts-en-us-x-tpd-network}}
{{tts en_US voices=com.google.android.tts-en-us-x-tpc-network}}
{{tts en_US voices=com.google.android.tts-en-us-x-iob-network}}
{{tts en_US voices=com.google.android.tts-en-us-x-iol-network}}
{{tts en_US voices=com.google.android.tts-en-us-x-iom-network}}
{{tts en_US voices=com.google.android.tts-en-us-x-iom-local}}
{{tts en_US voices=com.google.android.tts-en-US-language}}
{{tts en_US voices=com.google.android.tts-en-us-x-tpd-local}}
{{tts en_US voices=com.google.android.tts-en-us-x-iog-network}}
{{tts en_US voices=com.google.android.tts-en-us-x-tpf-network}}
{{tts en_US voices=com.google.android.tts-en-us-x-iog-local}}
{{tts en [...]

2023-10-31 20:44 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt
> +            it.setSpeechRate(tag.speed)
Errors are ignored here

2023-11-24 03:23 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt
> +// a name looks like: com.google.android.tts-cmn-cn-x-ccc-local
! for review

2023-11-24 03:23 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <!-- Chips should probably be in a separate file, due to the additional length req -->
! review, we could also set `maxLength` here?

2023-11-26 16:41 UTC, lukstbit requested changes
Took a quick look at this and left some comments.

2023-11-26 16:41 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt
> +    DefaultLifecycleObserver {
This class isn't added as a listener to a LifecycleOwner. Do you plant o add it later?

2023-11-26 16:41 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt
> +class AndroidTtsError(private val errorCode: TtsErrorCode, private val context: Context) : TtsPlayer.TtsError() {
I don't think we really need the Context here, we should format the exception error in the dialog where it's displayed to the user. This would allow us to remove the context reference from here and simplify the class.

2023-11-26 17:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt
> +    DefaultLifecycleObserver {
When used in `AbstractFlashcardViewer` to play TTS

2023-11-26 18:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsVoicesDialogFragment.kt
> +    private lateinit var mainAdapter: RecyclerView
Will fix, remnants of a past design with a second layout

2023-11-26 18:23 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsVoicesDialogFragment.kt
> +                textChanged { text -> viewModel.setSpokenText(text.toString()) }
Is there an extension with a single parameter, `text, _, _, _ -> ... }` isn't as clean

2023-11-26 19:07 UTC, david-allison commented
Pushed a number of changes, more remain (on me)

2023-11-26 19:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsVoicesDialogFragment.kt
> +            dialog?.window?.decorView?.showSnackbar(R.string.tts_voices_selected_voice_should_be_installed) {
What would be the suggested operation here?

Is it time to build a queue into our Snackbar mechanism?

2023-11-28 12:45 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsVoicesDialogFragment.kt
> +                textChanged { text -> viewModel.setSpokenText(text.toString()) }
No, I don't think so.

2023-11-30 13:07 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/viewmodel/TtsVoicesViewModel.kt
> +    fun copyToClipboard(voice: TtsVoice) = viewModelScope.launch(Dispatchers.IO) {
I don't think the coroutine launching is needed, all other usages of copyToClipboard are done on the main thread.

2023-11-30 13:16 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsVoicesDialogFragment.kt
> +            dialog?.window?.decorView?.showSnackbar(R.string.tts_voices_selected_voice_should_be_installed) {
> Is it time to build a queue into our Snackbar mechanism?

Maybe not.
After thinking again about this I'm not if it's a real issue(leaving aside the UI), as this snackbar is more of a informational notice as we allow the user to still use the voice code.
Could be fixed with a if check  _(NetworkUtils.isOnline) return_.

2023-12-02 20:16 UTC, david-allison commented
Comments handled, thanks

2023-12-05 16:43 UTC, lukstbit reviewed
I'm ok with the implementation. Left a question and one minor issue and then I guess we could move forward with this.

2023-12-05 16:43 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/viewmodel/TtsVoicesViewModel.kt
> +        viewModelScope.launch {
MutableStateFlow has an extension [update](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/update.html) that you could use to avoid the need for a  coroutine.

2023-12-05 16:43 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt
> +// a name looks like: com.google.android.tts-cmn-cn-x-ccc-local
Still a review issue? As we encode the engine name, we should be able to handle a different engine.

2023-12-05 16:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt
> +// a name looks like: com.google.android.tts-cmn-cn-x-ccc-local
I want to ensure that other reviewers are happy with this naming strategy as it'll be a breaking change to fix. Personally I'm happy

2023-12-05 17:09 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt
> +// a name looks like: com.google.android.tts-cmn-cn-x-ccc-local
Seems like a reasonable strategy

2023-12-05 19:29 UTC, lukstbit approved these changes
I think we  could merge this now.

2023-12-07 00:10 UTC, mikehardy approved these changes
Looks good, pulled it and it works well, this appears to be well into the "can do follow-ups as needed, let's go..." territory

Pending #14890 to clear strings out

2023-12-07 01:34 UTC, merged

2023-12-08 01:27 UTC, snowtimeglass commented on AnkiDroid/src/main/res/values/02-strings.xml
> +voice. The string is a technical error code such as 'ERROR_NOT_INSTALLED_YET' or ''">
This `or ''` is a typo?  Or the `''` means a blank?
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/976a22f8-9130-46b3-858a-a2b0deaabb19)

2023-12-08 01:33 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +voice. The string is a technical error code such as 'ERROR_NOT_INSTALLED_YET' or ''">
typo, thanks

2023-12-08 02:14 UTC, snowtimeglass commented on AnkiDroid/src/main/res/values/02-strings.xml
> +voice. The string is a technical error code such as 'ERROR_NOT_INSTALLED_YET' or ''">
By the way, organizing the look on the string files seems to have a bit influence (perhaps a bit consideration about the spaces) on the translation process, but is organizing the look on the string files is a priority in this cases?
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/aca0a8d5-24af-451e-888a-afbaade42341)
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/3455a866-15da-4a1a-a695-7b50af226db8)
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/471ba115-c54d-4d0c-ae2d-504539d2116c)
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/74dd34ea-5bff-424b-be6e-4b76f7462c6d)
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/fae972ac-2b3b-4a79-b4ce-e1c10e0e621a)
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/beb3088b-e8be-41a6-93d6-e4129b691098)
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/5f8183f4-f25c-4f46-a943-4a43e34baf6a)

2023-12-15 11:05 UTC, snowtimeglass commented
The "Copied to clipboard." doesn't seem to be shown on my environment.
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/559fd2db-8b14-41c1-a9f0-52b988d911c0" width="200px">


<details><summary>debug info</summary><div>

AnkiDroid Version = 2.17alpha10 (50fa39cd561d83662cd5ef1f708b14a9a15c74ac)

Backend Version = 0.1.31-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true
</div></details>