dismissed snackbar message
ankidroid/Anki-Android pull request #14648
Opened 2023-11-02 12:35 UTC by soCallmeAdityaKumar

## Purpose / Description
Snackbar shows in front of the FAB secondary options

## Fixes
#14470

## How Has This Been Tested?

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-11-02 15:34 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
> +        if (deckPicker.syncSnackbar != null && deckPicker.syncSnackbar!!.isShown)deckPicker.syncSnackbar!!.dismiss()
avoid using `!!`

2023-11-02 15:34 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
> +
not safe to use `!!`

2023-11-03 04:21 UTC, soCallmeAdityaKumar commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
> +
replaced with '?'

2023-11-03 04:21 UTC, soCallmeAdityaKumar commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
> +        if (deckPicker.syncSnackbar != null && deckPicker.syncSnackbar!!.isShown)deckPicker.syncSnackbar!!.dismiss()
replaced with '?'

2023-11-03 12:36 UTC, criticalAY commented
The naming convention used seems a little absurd maybe other reviewer would be able ti help with that

2023-11-03 17:13 UTC, BrayanDSO commented
I believe that you could use a `BaseSnackbarBuilderProvider` (or some similar name, I'm on my phone and can't check), store only a single reference like `shownSnackbar` then use it to dismiss the snackbar

2023-11-05 20:27 UTC, criticalAY approved these changes
Implementation looks fine to me

2023-11-05 23:49 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
>          anchorView = findViewById<FloatingActionButton>(R.id.fab_main)
I meant that you could add `baseSnackbar = this` below this line and avoid the repetition along all of the activity

2023-11-06 11:28 UTC, soCallmeAdityaKumar commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
>          anchorView = findViewById<FloatingActionButton>(R.id.fab_main)
yeah thanks!!

2023-11-20 08:19 UTC, soCallmeAdityaKumar commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
>          anchorView = findViewById<FloatingActionButton>(R.id.fab_main)
@BrayanDSO @criticalAY  i think its ready to be merge please review it

2023-11-20 08:36 UTC, criticalAY approved these changes
Thankyou!

2023-12-11 07:23 UTC, soCallmeAdityaKumar commented
@mikehardy @david-allison @BrayanDSO review required

2023-12-16 17:22 UTC, david-allison requested changes
Outcome is great

* Could you add a `@NeedsTest` somewhere, including the issue number

A few nitpicks with code style

2023-12-16 17:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
> +
* `deckPicker.baseSnackBar?.isShown == true` handles the case where `deckPicker.baseSnackBar == null`
* add a space after the `)` and the follow-on

```suggestion
        // ensure the snackbar doesn't obscure the menu
        if (deckPicker.baseSnackBar?.isShown == true) deckPicker.baseSnackBar?.dismiss()
        if (createDeckSnackBar?.isShown == true) createDeckSnackBar?.dismiss()
```

2023-12-16 17:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Undo.kt
> +//            snackbar = this
don't leave commented out code

2023-12-17 14:56 UTC, soCallmeAdityaKumar commented on AnkiDroid/src/main/java/com/ichi2/anki/Undo.kt
> +//            snackbar = this
removed

2023-12-17 14:56 UTC, soCallmeAdityaKumar commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
> +
done

2023-12-29 15:24 UTC, david-allison approved these changes
Looks great, thanks!

2024-01-26 13:57 UTC, david-allison commented
CI is failing

2024-01-31 06:30 UTC, david-allison reviewed
Brief review, I'll need to go through this on my laptop

2024-01-31 06:30 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> -                renderOutput()
This should be reverted

2024-01-31 06:30 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Undo.kt
> +//    var snackbar: Snackbar? = null
Revert this

2024-01-31 14:28 UTC, david-allison requested changes
This pattern means that any additional snackbars are not handled.

* move `baseSnackbar` into AnkiActivity. rename to `currentSnackbar`
* Inside the following, check if `Activity` is `AnkiActivity`, and if so, set `currentSnackbar`

https://github.com/ankidroid/Anki-Android/blob/56601041636f06e3e177749e73b75051fcb76568/AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt#L112-L116

* define `fun dismissSnackar()` inside `AnkiActivity` and call that from the FAB code

2024-01-31 14:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
> +    private var createDeckSnackBar: Snackbar? = null
This isn't used

2024-02-07 02:35 UTC, closed without merging