fix permission margin
ankidroid/Anki-Android pull request #14657
Opened 2023-11-03 23:33 UTC by RobozinhoD

## Fixes
Fixes #14653

## Approach
I used the same padding of preferences switches as asked

## How Has This Been Tested?

I could not reproduce the issue, but I trust what I did and looks okay in the preview see
![image](https://github.com/ankidroid/Anki-Android/assets/65715921/6dcedb43-2474-46a9-ba41-c290496e7ac9)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-11-03 23:55 UTC, david-allison requested changes
Sorry to be a pain: dimensions are inconsistent with preferences. The right edge of the switch should line up with the right edge of the button

<details>

<summary>Screenshots</summary>

![image](https://github.com/ankidroid/Anki-Android/assets/62114487/118e0fc5-6ab3-432a-8028-ba4dc90cc79b)

![image](https://github.com/ankidroid/Anki-Android/assets/62114487/bd5963c7-7804-4067-bd13-c0ad8b4b20f0)

</details>

2023-11-04 00:15 UTC, RobozinhoD commented
ok

![image](https://github.com/ankidroid/Anki-Android/assets/65715921/f817cdf7-1e5a-4e6c-9852-a577e3323dd9)

2023-11-04 16:39 UTC, criticalAY commented
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/68d9de74-2eb8-4353-8331-49d8e7ef0a8e)
The audio icon is on top of the title we should constraint it to the bottom like above -the gravity is in center

2023-11-04 16:57 UTC, criticalAY requested changes

2023-11-04 16:57 UTC, criticalAY commented on AnkiDroid/src/main/res/layout/permission_item.xml
>      android:paddingTop="16dp"
Instead of having padding here use margin so that it comes consistent

2023-11-04 22:55 UTC, RobozinhoD commented on AnkiDroid/src/main/res/layout/permission_item.xml
>      android:paddingTop="16dp"
consistent with what?

2023-11-04 22:56 UTC, RobozinhoD commented
> ![image](https://user-images.githubusercontent.com/48384865/280480349-68d9de74-2eb8-4353-8331-49d8e7ef0a8e.png) The audio icon is on top of the title we should constraint it to the bottom like above -the gravity is in center

the issue doesn't ask to do that

2023-11-04 23:05 UTC, criticalAY commented
But there is no harm in resolving it as it would be a add on and is related to the same layout

2023-11-04 23:05 UTC, criticalAY commented on AnkiDroid/src/main/res/layout/permission_item.xml
>      android:paddingTop="16dp"
That is when you put the icon in centre

2023-11-06 00:07 UTC, BrayanDSO commented
My reference for the permission screen is this one:

![image](https://github.com/ankidroid/Anki-Android/assets/69634269/55852f93-7eec-4501-889e-93749a56414a)

I definetely want to avoid copying 100% a preference because that feels both tight and generic. Putting the icon a little down, but not at the center would look good, but it's up to the implementer

2023-11-15 14:27 UTC, RobozinhoD commented
Done
![image](https://github.com/ankidroid/Anki-Android/assets/65715921/0ea89a42-ae75-4bc1-8d3e-43f69b41afaa)

2023-11-15 14:31 UTC, david-allison approved these changes
Looks great, thanks!

2023-11-15 14:34 UTC, BrayanDSO approved these changes

2023-11-15 15:00 UTC, merged