fix: handle plural strings in SliderPreference
ankidroid/Anki-Android pull request #14704
Opened 2023-11-11 18:33 UTC by BrayanDSO

## Purpose / Description
SliderPreference summaries didn't handle plurals

## Fixes
* Fixes #14572 
* Closes #14701

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Emulator 34

[Screen_recording_20231111_152907.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/d37470f1-dbcd-4bd1-a56d-8e1b756d8ad5)

## Learning (optional, can help others)

getResourceTypeName can be used to differentiate resource types. Source: ChatGPT

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-11-11 18:38 UTC, david-allison requested changes
I think `1` should be fixed to help translators

2023-11-11 18:38 UTC, david-allison commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +        <item quantity="one">1 hour past midnight</item>
Use %d for '1'. Some languages use `one` for variable strings:

2023-11-11 18:38 UTC, david-allison commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +        <item quantity="other">%1$d hours past midnight</item>
Nit: I don't think `%1$d` is necessary over `%d` as there's only one string

2023-11-11 18:39 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +        <item quantity="one">1 hour past midnight</item>
Also for the zero case?

2023-11-11 18:43 UTC, BrayanDSO commented
note: I added a comment to to string:

> comment="%d is going to be replaced with the number of hours past midnight. It can be replaced if something else suits better the translation"

2023-11-11 18:44 UTC, david-allison commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +        <item quantity="one">1 hour past midnight</item>
Good point! TIL: `zero` is ambiguous in Latvian: https://www.unicode.org/cldr/charts/44/supplemental/language_plural_rules.html#lv

But practically: English doesn't need a zero case, as it's handled by `other`.

2023-11-11 18:53 UTC, oyeraghib commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +        <item quantity="one">1 hour past midnight</item>
I don't think we might need `hour` for "zero". It should be called `zero hours` if I am not wrong. Just `one` and `other` attributes should do the required work.

Good to read: https://ell.stackexchange.com/questions/174489/is-it-correct-to-say-0-hours#:~:text=Tangentially%20related%2C%20zero%20hour%20(no,something%20is%20scheduled%20to%20occur.

https://github.com/ankidroid/Anki-Android/pull/14701#discussion_r1390258100

2023-11-11 18:53 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +        <item quantity="one">1 hour past midnight</item>
Done. Thanks!

2023-11-11 19:26 UTC, david-allison approved these changes

2023-11-12 10:23 UTC, lukstbit approved these changes
LGTM!

2023-11-12 10:23 UTC, merged