Add apk build date in About Fragment
ankidroid/Anki-Android pull request #14713
Opened 2023-11-13 16:10 UTC by oyeraghib

## Purpose / Description
Add apk build date in About Fragment near version number

## Fixes
* Fixes #14691 

## How Has This Been Tested?
Manually tested on emulator Pixel 3a

<img src="https://github.com/ankidroid/Anki-Android/assets/40427461/59688944-41fc-4cb8-aa6c-50931d120138" width="300">

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-11-13 16:49 UTC, BrayanDSO reviewed
Maybe put the date below the version?

2023-11-13 16:49 UTC, BrayanDSO commented on AnkiDroid/build.gradle
> +        buildConfigField "String", "BUILD_TIME", "\"" + System.currentTimeMillis().toString() + "\""
Are the `"\""` necessary?

2023-11-14 15:23 UTC, oyeraghib commented
Update with changes (date below version)
<img src="https://github.com/ankidroid/Anki-Android/assets/40427461/a49750f7-dd92-41c3-bd15-8bccf9447834" width="300" height="600">

2023-11-14 15:24 UTC, oyeraghib commented on AnkiDroid/build.gradle
> +        buildConfigField "String", "BUILD_TIME", "\"" + System.currentTimeMillis().toString() + "\""
removed.

2023-11-14 15:42 UTC, david-allison requested changes
LGTM, one quick cleanup. 

Consider this a soft approval

2023-11-14 15:42 UTC, david-allison commented on AnkiDroid/build.gradle
> +        buildConfigField "String", "BUILD_TIME", "\"${System.currentTimeMillis().toString()}\""
I believe this can be a `Long`. This would remove `BuildConfig.BUILD_TIME.toLong()`

2023-11-14 16:09 UTC, david-allison approved these changes
Cheers, I'm happy if tests pass

2023-11-14 16:35 UTC, lukstbit approved these changes
Thanks!

2023-11-14 16:36 UTC, merged

2023-11-14 17:48 UTC, Arthur-Milchior commented
Thanks a lot, that’ll be quite helpful!