add redo button and control
ankidroid/Anki-Android pull request #14738
Opened 2023-11-15 16:49 UTC by RobozinhoD

## Purpose / Description
Added option to redo card

## Fixes
* Fixes #14030 

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

In emulator 34, I undid a card answered then tapped the redo button. I did that with the control with ctrl+shift+z too

![image](https://github.com/ankidroid/Anki-Android/assets/65715921/ef4cf88e-5690-4363-b960-b9a3b984d9bf)

![image](https://github.com/ankidroid/Anki-Android/assets/65715921/6a43ff66-b90c-496e-a745-c884f1e0daad)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-11-15 18:16 UTC, BrayanDSO requested changes

2023-11-15 18:16 UTC, BrayanDSO commented on AnkiDroid/src/main/res/menu/reviewer.xml
> +        ankidroid:showAsAction="always"/>
The icon isn't mirrored in RTL languages, although you put a `android:autoMirrored="true"` at SVG. I guess that adding `        ankidroid:actionProviderClass="com.ichi2.ui.RtlCompliantActionProvider"` just like the undo button should fix it

2023-11-15 21:02 UTC, BrayanDSO approved these changes
LGTM. Thanks

For another issue, adding a redo button to the whiteboard would be useful

2023-11-16 13:49 UTC, david-allison approved these changes

2023-11-16 13:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomButtonsSettingsFragment.kt
> +                        }
nit: 
* helper method to removeAll
* `allKeys` is ambiguous. It's all keys on the screen, but it could also be all preference keys

2023-11-16 23:27 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomButtonsSettingsFragment.kt
> +                        }
> helper method to removeAll

I'd wait to see if it has an use somewhere else

> allKeys is ambiguous. It's all keys on the screen, but it could also be all preference keys

valid, but I am going merge this now to take advantage of the recent translations sync

2023-11-16 23:27 UTC, merged