new audio recorder and player
ankidroid/Anki-Android pull request #14740
Opened 2023-11-15 19:18 UTC by criticalAY

## Purpose / Description
New Audio Recorder UI for reviewer and handling the bugs and state management from previous PR

* The audio recorder + player + audio view were separate and cluttered removing the MediaPlayer class and handling the states in the custom Audio View itself, 
* adding a new preference to allow record audio >save it > then play it
* Resulting in 
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/174b61ed-3ed9-40b7-831d-d1eb1a995f80)

* Deleting the existing audio view class and completely replacing it with the new `AudioRecordingController` bitting down a lot of excess code
* Reviewer would go and something like : 
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/10fe94d4-0f1a-46cd-9721-d3311580c817)
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/600d0e3c-9ebb-4829-b8f8-2c66cc82cd5d)

* Allow the user to re-record the audio if they are not satisfied with the output 

## Fixes
* Fixes #14736
* Fixes #14730
* Related #14591

## Approach
Replacing the existing audio recorder with new one at all places in the application 

## How Has This Been Tested?
Tested in Google emulator and oneplus nord ce

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-11-16 16:15 UTC, criticalAY commented
@david-allison we can start reviewing this PR now

2023-11-19 15:31 UTC, david-allison requested changes
At 383ffcdd010c0761290498b0ab649420811d84de

* it takes two taps of 'record' to start recording
* The waveform stays at 0
* Neither 'delete', nor 'tick' work
* I would convert the 'tick' button to a 'save' icon

2023-11-19 15:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        isMicToolBarVisible = !isMicToolBarVisible
nit: consider moving this to the start of the method, then returning early in the `if` to reduce nesting

2023-11-19 15:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +            audioRecordingController?.toggleSave()
`saveRecording` contains `if (inEditField) saveRecording()`

It would be useful to have a comment explaining where the recording would be saved (presumably it's not added to the card inside the reviewer)

2023-11-20 07:51 UTC, criticalAY commented
* The double tap issue was there due to the audio recorder not being destroyed when the reviewer was closed (fixed it)
* changed the audio save icon
* other issues are fixed 
![Screenshot 2023-11-20 123058](https://github.com/ankidroid/Anki-Android/assets/48384865/1d322ad3-ad86-4a02-aef8-d2ac64f5c0ee)

2023-11-20 14:31 UTC, david-allison requested changes
I think we could do with a sentence or two explaining what a user wants when they check their pronunciation. I feel we can do better with the UX here

Initial thoughts:

* The audio isn't discarded once the next card is shown
* Recorded audio should be in 'playback mode' when the answer is shown
* I'm not sure if we want the 'continue recording' functionality to be so prominent here
* I was mistaken about the 'save' functionality
  * If a user wants to save the audio to disk, we want to provide this, but this would more likely be on the 'player' mode of the view

* app crashes if 'save' is pressed while recording is in progress.

----

I'd move to 'player mode' as soon as the recording is completed.

2023-11-20 15:06 UTC, criticalAY commented
* The audio isn't discarded once the next card is shown
The previous recorder had this so I didn't change it
* Recorded audio should be in 'playback mode' when the answer is shown
Can try do this
* app crashes if 'save' is pressed while recording is in progress.
Will test it

2023-11-21 17:32 UTC, mikehardy commented
Sorry about the merge conflict @criticalAY - I knew it would perturb this PR. You fixed it quickly!

2023-11-21 17:46 UTC, criticalAY commented
> Sorry about the merge conflict @criticalAY - I knew it would perturb this PR. You fixed it quickly!

No problem at all :)

2023-11-23 15:40 UTC, criticalAY commented
@david-allison I have fixed the crash, can the `The audio isn't discarded once the next card is shown` wait as it was there in the previous recorder too, we can test the other things the get it ready for the 2.17 release and I can continue to work on it after that?

2023-11-26 20:44 UTC, david-allison commented
* it feels like the playback bar doesn't start with 0 on the left side, it takes about 300ms to start moving
   * I believe that this is because the timer does not use the `currentPosition` variable
* `delay = 50L` leaves about 20FPS, can we bump this up to 60?
  * In particular, this value means the final digit of playback oscillates between 0 and 5
* play audio until the end, press the 'go back 5' icon:
  *  Timer contines forever
  * It's likely these icons shouldn't be usable
* I've had occurrences where the audio recording immediately stops
  *  this occurs after a 'delete' in the 'playback' mode, and trying a second recording
  * pressing "record, save, delete, record" quickly caused this

If feasible, can we have flipping the card move the state to 'playback'

I would have 'next card' discard the recording

2023-11-26 20:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +            audioPlayer!!.currentPosition
I think this is a no-op

2023-11-28 17:10 UTC, criticalAY commented
> * `delay = 50L` leaves about 20FPS, can we bump this up to 60?

Done!

>   * Timer contines forever

Fixed


> If feasible, can we have flipping the card move the state to 'playback'
> I would have 'next card' discard the recording

Yes, we can and this should better but I will do it in the next chunk not this PR, as this can still wait and the users wont be affected because the previous recorder also had this thing, I will do it in next PR.

2023-11-28 18:15 UTC, criticalAY commented
https://github.com/ankidroid/Anki-Android/assets/48384865/e128c1d4-a644-4249-bdae-e88ab704f4a8

2023-11-30 20:22 UTC, criticalAY commented
The failed test is flaky

2023-11-30 20:35 UTC, david-allison requested changes
I'm still getting a bug where I start recording, and it stops a few milliseconds later

2023-11-30 21:00 UTC, criticalAY commented
> I'm still getting a bug (CardViewer) where I start recording, and it stops a few milliseconds later.
> 
> Doesn't happen regularly, but often.
> 
> I'd be open to the addition of `Timber.v/d` logging if you can't reproduce this, so you can get a trace of what's going on

Got it, I guess it was due `stop` being after afterwards, I tested it out multiple times worked fine, I hope it is fixed otherwise Timber will be the only resort

2023-11-30 21:35 UTC, david-allison commented
Any chance this could be rebased on `main`, just updated to JDK21, and need to bump it up each time I want to test

2023-11-30 21:37 UTC, criticalAY commented
Sure! As soon as I wake up I will rebase the PR

2023-12-01 09:49 UTC, criticalAY commented
I will try to rebase the PR once we are done testing

2023-12-02 20:58 UTC, criticalAY commented
@david-allison updated branch with main, will work with JDK21 now

2023-12-03 00:04 UTC, david-allison requested changes
* on replaying, stopping + starting the recording shows the wrong 'elapsed' time
* it still feels like there's latency from 'pressing the button + counter starting' to
* still getting the immediate start + stop, but  much less common

2023-12-03 08:12 UTC, criticalAY commented
> * on replaying, stopping + starting the playback shows the wrong 'elapsed' time

Fixed this one
> * it still feels like there's latency from 'pressing the button + counter starting' to the 'duration bar' moving

any suggestion you have, I am happy to implement that
> * still getting the record -> immediate stop issue, but  much less common
I tested the audio recorder 30-35 times, was able to reproduce it only once, that too the audio is being recorded but the waveform didn't show up

2023-12-04 23:38 UTC, david-allison commented
Let's get some `Timber.d`s in there and I'll get a trace of the proble,

2023-12-05 19:03 UTC, criticalAY commented
it was some stupid val error, have fixed it and tested it and didn't appear on my side this time should be fixed now :)

2023-12-11 22:33 UTC, david-allison requested changes
I'm still getting an instant stop of recording when pressing 'record' after a few tries of record -> save -> delete -> record

2023-12-12 01:40 UTC, criticalAY commented
> I'm still getting an instant stop of recording when pressing 'record' after a few tries of record -> save -> delete -> record

umm I would like to confirm one thing are you testing it on emulator ?

2023-12-12 16:12 UTC, criticalAY commented
https://github.com/ankidroid/Anki-Android/assets/48384865/552ae9ee-b25b-437b-b75d-1a025af119a4

2023-12-12 19:20 UTC, david-allison commented
> > I'm still getting an instant stop of recording when pressing 'record' after a few tries of record -> save -> delete -> record
> 
> umm I would like to confirm one thing are you testing it on emulator ?

My S21

2023-12-20 08:01 UTC, david-allison commented
Still getting an instant stop

2023-12-20 13:02 UTC, mikehardy commented
😬  
<img width="1016" alt="image" src="https://github.com/ankidroid/Anki-Android/assets/782704/88fef466-e1b5-45d8-a817-28dd469eb903">

why not fetch upstream then rebase, fix the specific commits with an issue then repush? There are 27 commits in this PR now

2023-12-20 13:21 UTC, criticalAY commented
I'll get rid of all this once the PR is reviewed and working as expected

2023-12-20 13:40 UTC, mikehardy commented
It is an impediment to review at the moment. You've got hard stops reported so it's not working (thus not sure reviews will remain valid from existing reviewers) and as a possible new reviewer I see merge commits and 27 commits listed and I think "nope" with my limited time and go after other PRs. $0.02

2023-12-20 13:56 UTC, criticalAY commented
Ohh Ok 👍🏻👍🏻 will fix it in an hour or so

2023-12-20 23:34 UTC, david-allison commented
Still showing as 24 changes

2023-12-21 07:26 UTC, criticalAY commented
Files? It is correct as there are 24 changed files

2023-12-21 14:22 UTC, mikehardy commented
Something about CI isn't right and looks like a "github had an issue" thing so I'm closing reopening just to kick off CI again
@david-allison diff does appear to clean now + 1 commit / 24 files changed

2023-12-21 17:36 UTC, criticalAY commented
> Something about CI isn't right and looks like a "github had an issue" thing so I'm closing reopening just to kick off CI again @david-allison diff does appear to clean now + 1 commit / 24 files changed

it happened when re opened one of my previous PR but it should work fine when i  push one more commit

2023-12-21 18:51 UTC, criticalAY commented
conflicts :(

2023-12-21 21:33 UTC, mikehardy commented
wouldn't a rebase have easily incorporated those changes without the merge commit? they were just spacing and from to listOf 🤔

2023-12-21 21:36 UTC, criticalAY commented
> wouldn't a rebase have easily incorporated those changes without the merge commit? they were just spacing and from to listOf 🤔

could you mention the steps please ?

2023-12-21 22:13 UTC, mikehardy commented
well, assuming you don't have a merge commit in there, I do something like this on the command line:

1- git fetch upstream
2- git rebase upstream/main (conflicts! dang)
3- ...at this point I'm in the middle of the rebase, halted on the commit that had a conflict
4- git status (shows me the file(s) that's busted)
5- open that file (or those files if multiple) in an editor and search for `<<<<` to seek down to the conflict
6- think about things...how they are supposed to fit together...edit things until they fit together
7- `./gradlew jacocoTestReport` to make sure tests are passing etc - still mid-rebase but conflict fixed now!
8- once tests are passing, git diff one more time to make sure it looks correct
9- git add -A
10- git rebase --continue (if a future commit has a conflict too, go to step 3...)

Now you have a local branch that's got upstream/main in it cleanly

11 - git push --force-with-lease

2023-12-31 10:11 UTC, criticalAY commented
@david-allison could you please confirm you tested the latest commit, as  I tested it but I could not reproduce it even after quite a  attempts I also posted a screen recording

2023-12-31 10:37 UTC, david-allison commented
```
davidallison@Davids-MacBook-Pro Anki-Android % gh pr checkout --force 14740
From https://github.com/ankidroid/Anki-Android
 * branch                  refs/pull/14740/head -> FETCH_HEAD
HEAD is now at 04a7ddd33c resolving merge conflicts in AbstractFlashcardViewer and ViewerCommand
davidallison@Davids-MacBook-Pro Anki-Android % git rev-parse HEAD
04a7ddd33c28cef354f88e5bbd80979fedc0e0fb
```

Reproduced immediately

2023-12-31 10:37 UTC, david-allison commented
```
10:35:56.945 MediaRecorder                        D  Constructor MediaRecorder
10:35:56.945 MediaRecorderJNI                     I  setup
10:35:56.979                                      I  setAudioSource(1)
10:35:57.031                                      I  setAudioEncoder(3)
10:35:57.031                                      I  setParameter(), params: audio-param-number-of-channels=2
10:35:57.031                                      I  setParameter(), params: audio-param-sampling-rate=44100
10:35:57.031                                      I  setParameter(), params: audio-param-encoding-bitrate=192000
10:35:57.032                                      I  setOutputFile
10:35:57.032                                      I  prepare
10:35:57.037 MediaRecorder                        I  prepare elapsed time : 5 ms
10:35:57.039 MediaRecorderJNI                     I  start
10:35:57.457                                      I  pause
10:35:58.077                                      I  resume
10:36:01.466                                      I  stop
10:36:01.594 MediaPlayerNative                    W  info/warning (10973, 0)
10:36:04.222 MediaRecorder                        D  Constructor MediaRecorder
10:36:04.222 MediaRecorderJNI                     I  setup
10:36:04.225                                      I  setAudioSource(1)
10:36:04.235                                      I  setAudioEncoder(3)
10:36:04.235                                      I  setParameter(), params: audio-param-number-of-channels=2
10:36:04.235                                      I  setParameter(), params: audio-param-sampling-rate=44100
10:36:04.235                                      I  setParameter(), params: audio-param-encoding-bitrate=192000
10:36:04.236                                      I  setOutputFile
10:36:04.237                                      I  prepare
10:36:04.239 MediaRecorder                        I  prepare elapsed time : 4 ms
10:36:04.239 MediaRecorderJNI                     I  start
10:36:04.336 MediaPlayerNative                    E  error (-38, 0)
10:36:04.339 MediaPlayer                          E  Error (-38,0)
10:36:04.339 MediaPlayer-JNI                      E  enable device callback failed: -19
10:36:08.346 MediaRecorderJNI                     I  pause
10:36:57.591                                      I  resume
10:36:58.943                                      I  pause
10:36:59.981                                      I  stop
10:37:00.052 MediaPlayerNative                    W  info/warning (10973, 0)
```

2023-12-31 13:25 UTC, criticalAY commented
Seems like it is due to the media player being prepared but we still hit the recording button, would place a check and see if we can reproduce it

2023-12-31 14:15 UTC, criticalAY commented
Done! I really hope this time it gets fixed, the issue was with the audio player rather than the recorder so I have made some changes there.

2023-12-31 16:30 UTC, david-allison requested changes
Fixed!!!

`onTimerTick` should be using `currentPosition`: the audio player takes a few hundred ms to start.

```kotlin
        if (isPlaying && !isRecording) {
            val currentPosition = audioPlayer!!.currentPosition
            audioProgressBar.progress = currentPosition
            val ms = currentPosition % 1000
            val s = (currentPosition / 1000) % 60
            val m = (currentPosition / (1000 * 60)) % 60
            val h = (currentPosition / (1000 * 60 * 60)) % 60
            audioTimeView.text = if (h > 0) {
                "%02d:%02d:%02d.%02d".format(h, m, s, ms / 10)
            } else {
                "%02d:%02d.%02d".format(m, s, ms / 10)
            }

        } else {
            audioTimeView.text = duration
            audioProgressBar.progress = 0
        }
```

2023-12-31 22:01 UTC, criticalAY commented
It seems fine as  I was using it for the onTimeTick

2024-01-01 02:04 UTC, david-allison commented
Oh my phone, it takes maybe 300ms before the audio starts. This means that the timer is running when the bar isn't moving and audio isn't playing

2024-01-01 07:19 UTC, criticalAY commented
I updated the commits as you suggested so it should be fixed ?

2024-01-01 10:20 UTC, david-allison reviewed
I will apply these comments, posting for posterity

2024-01-01 10:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                    Timber.e("unable to add the audio recorder to toolbar: $e")
`Timer.w`, pass in `e` as the first parameter rather than formatting it

2024-01-01 10:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +                label.visibility = if (hasTextContents) View.VISIBLE else View.GONE
`label.isVisible = hasTextContents`

2024-01-01 10:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +                    val textView = FixedTextView(this)
use `.apply`

2024-01-01 10:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +                Timber.e(e)
`Timber.w`

2024-01-01 10:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +            rewindAudioButton
?

2024-01-01 10:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +                iconTint = ContextCompat.getColorStateList(context, R.color.flag_red)
These colors should /probably/ not use the flag definitions

2024-01-01 10:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +                iconTint = ContextCompat.getColorStateList(context, R.color.flag_green)
ditto

2024-01-01 10:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +            Timber.e(e, "Failed to start recording")
`Timber.w`

Good usage of `(e, "Failed to start recording")`

2024-01-01 10:45 UTC, david-allison approved these changes
Did some cleanup - I'm happy

Happy New Year! Let's get this in!

2024-01-01 10:55 UTC, criticalAY commented
*Closes #15075

2024-01-02 18:53 UTC, BrayanDSO commented
## Issues when I tested

### Audio goes back if pausing near the end

[go back.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/036cffef-e90b-4be0-b9da-fdae107c80a0)

### Recording circle button should always be red

[Screen_recording_20240102_154507.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/1258c50d-8ac5-4e4e-8e6c-b2dddb90c733)

### Go back 5 seconds isn't returning to start when the audio is short (neither Go after button goes to the end)

[Screen_recording_20240102_154416.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/04b79701-4a34-4c66-b2e9-3aa45cb02214)

### nit: play icon should be green and pause button should be red, not the contrary

I believe that is a more universally adepted scheme (as in traffic lights)

![image](https://github.com/ankidroid/Anki-Android/assets/69634269/b28396ae-bf4a-4a17-a7cf-297001c4f0c9)

![image](https://github.com/ankidroid/Anki-Android/assets/69634269/a422f8c4-c083-447c-9af9-851b666c3475)

2024-01-02 18:55 UTC, BrayanDSO commented
question: since the recording isn't actually saved to the device storage in the reviewer, do you think that a stop icon would be better than a disk icon in this specific case?

2024-01-02 20:20 UTC, criticalAY commented
> Go back 5 seconds isn't returning to start when the audio is short (neither Go after button goes to the end)

it's because the rewind or forward is possible only for (+-5) the button has that marking too, we can disable the buttons in case the recording is too short i.e less than 10sec ?

2024-01-02 20:24 UTC, criticalAY commented
> Audio goes back if pausing near the end 

should be a minor issue would fix it

2024-01-02 20:27 UTC, criticalAY commented
> question: since the recording isn't actually saved to the device storage in the reviewer, do you think that a stop icon would be better than a disk icon in this specific case?

We can discuss it but I would put it in the followup if not this one, and how about a tick in this case ?

2024-01-02 20:43 UTC, BrayanDSO commented
> it's because the rewind or forward is possible only for (+-5) the button has that marking too, we can disable the buttons in case the recording is too short i.e less than 10sec ?

if it is less than 5 seconds, go to the end or beginning. Disabling the buttons seems like complicating the UX

> thinking behind this logic is that when stopped its red otherwise green

the timer and the sounds wave running is the major thing that tells me that it is running or not. Reverting the colors is rather conterintuitive to me

> it was red but we discussed it on discord to change the color so that the user is aware that recording has started

repeating myself, the timer and sounds wave is the major thing that tells that is is running or not

> We can discuss it but I would put it in the followup if not this one, and how about a tick in this case ?

No reason to do a followup PR to something this simple. And a tick seems better

2024-01-02 20:51 UTC, criticalAY commented
> No reason to do a followup PR to something this simple. And a tick seems better

not for this but there are other known improvements that I want to make so I will do a followup not putting them here as it stretches the PR further more, so won't do it here but I would put the icon in the commit when I fix the pause bug you mentioned

2024-01-02 20:53 UTC, criticalAY commented
> the timer and the sounds wave running is the major thing that tells me that it is running or not. Reverting the colors is rather conterintuitive to me

originally it was constant (red) but I made these changes knowingly, I don't have an issue reverting to the constant red color

2024-01-03 20:28 UTC, criticalAY commented
This happens when there are few ms left not seconds I tested it on OnePlus nord seems like an issue with MediaPlayer, would like this and the tick option rather than disk option to be added to my TODO and will get rid of it, other than that I have resolved rewind and forward button bug in case recording is <5s and the audio recorder color.

2024-01-04 10:48 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/reviewer/KeyboardShortcutIntegrationTest.kt
> -class KeyboardShortcutIntegrationTest : RobolectricTest() {
got a conflict here, but why was it removed? The functionality doesn't seem to be affected

2024-01-04 16:27 UTC, criticalAY commented on AnkiDroid/src/test/java/com/ichi2/anki/reviewer/KeyboardShortcutIntegrationTest.kt
> -class KeyboardShortcutIntegrationTest : RobolectricTest() {
The AudioPlayer and AudioView were different so the test is using the old method the current code would need a new test file this would not work hence the removal

2024-01-05 04:23 UTC, mikehardy approved these changes
read through it - tested it locally, appears to work, nice!
just pending #15161

2024-01-05 04:43 UTC, merged