refactor: remove appIntro dependency
ankidroid/Anki-Android pull request #14741
Opened 2023-11-15 21:00 UTC by BrayanDSO

It didn't have any special use that we couldn't deal with ease without it

## How Has This Been Tested?

Emulator 24. Haven't tested CI because I'm leaving home right now

[intro.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/607ba15d-d609-4b22-9eec-1b0c0931e271)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-11-16 06:12 UTC, lukstbit requested changes
The changes LGTM and it's always nice to be able to remove a dependency. 

There's the instrumented failing test to fix + there are two IDE reported issues in IntroductionActivity(unused imports) that could be fixed as well.

Also, have you noticed the regression with the briefly showing dialog with the StorageException? Although the code still works this didn't happened with the old implementation. Is this something that we could address(or should address?)?

2023-11-16 08:45 UTC, BrayanDSO commented
> Also, have you noticed the regression with the briefly showing dialog with the StorageException?

Yep. Idk if that is a regression created by this PR or something that already have been happening with lower APIs. I believe that some operations in the deck picker keep running while the user haven't given the permissions in the permission screen. Since the deck picker is recreated after leaving the permission screen, the dialog is dismissed automatically.

I believe it should be addressed, although given the impact of it, I wouldn't spend time on it myself

2023-11-16 13:14 UTC, david-allison commented
The storage error dialog displaying briefly is not a regression, this occurs on `main`

2023-11-17 05:23 UTC, lukstbit approved these changes

2023-11-21 17:20 UTC, mikehardy approved these changes
okay then :-)

2023-11-21 17:20 UTC, merged