browser menu plural update
ankidroid/Anki-Android pull request #14755
Opened 2023-11-16 18:11 UTC by criticalAY

## Purpose / Description
Correct string according to the number of cards

## Fixes
* Fixes #14752

## How Has This Been Tested?
![Screenshot 2023-11-16 233948](https://github.com/ankidroid/Anki-Android/assets/48384865/53234d39-2e1e-41a0-890b-0961c3e26158)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-11-16 22:15 UTC, david-allison requested changes
Thanks!

2023-11-16 22:15 UTC, david-allison commented on AnkiDroid/src/main/res/menu/card_browser_multiselect.xml
> +        android:icon="@drawable/ic_delete_white" />
`tools:title` can be used to help designers (`Delete note(s)`)

2023-11-16 22:15 UTC, david-allison commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +<!--    <string name="card_browser_unsuspend_card">Unsuspend cards</string>-->
No point in commenting it out - can be removed

2023-11-16 22:15 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                title = if (hasUnmarked) {
(pending other reviewers): I'd much rather use Anki's "Toggle Suspend" and "Toggle Mark" here and remove this method

This code is complex and slow, and I don't feel it adds value to the end user

2023-11-16 22:15 UTC, david-allison commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <plurals name="card_browser_delete_card">
Let's fix the name here as well

2023-11-16 22:15 UTC, david-allison commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="card_browser_mark_card">Toggle Mark</string>
`CollectionManager.TR.browsingToggleMark()`

2023-11-16 22:15 UTC, david-allison commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="card_browser_suspend_card">Toggle suspend</string>
`CollectionManager.TR.browsingToggleSuspend()`

2023-11-16 22:15 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            }
This looks to be the same on both branches

2023-11-16 23:22 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                title = if (hasUnmarked) {
> "Toggle Suspend" and "Toggle Mark"

👍

2023-11-17 08:44 UTC, criticalAY commented
Question : should we delete the string ? as it was also used to set title in XML file in the menu in case we use `CollectionManager.TR.browsingToggleMark()`

2023-11-17 08:57 UTC, BrayanDSO commented
> should we delete the string ?

yes

> That would leave the title empty in the XML view

That's what `tools:title` serves for

> This looks to be the same on both branches
The code just above it is also doing so, should I simplify that too?

yes

2023-11-17 08:59 UTC, criticalAY commented
> That's what tools:title serves for

No I meant if we use string from `TR` we wont have a string locally

2023-11-17 09:02 UTC, BrayanDSO commented
> No I meant if we use string from TR we wont have a string locally

I still don't get what you mean. That we won't have XML previews for other languages if `tools:title` is being used?

2023-11-17 09:04 UTC, criticalAY commented
> I still don't get what you mean. That we won't have XML previews for other languages if `tools:title` is being used?

I mean if we delete the string "Toggle mark" then we will have to hardcode the string as `tools:title` is it ok? as we wont have the "Toggle mark" string in the `values/strings`

2023-11-17 09:05 UTC, BrayanDSO commented
I mean if we delete the string "Toggle mark" then we will have to hardcode the string as tools:title is it ok?

yes

2023-11-21 16:01 UTC, criticalAY commented
@david-allison review requested! : )

2023-11-21 23:26 UTC, david-allison requested changes

2023-11-21 23:26 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
>      private fun onSelectedCardsChecked(result: Pair<Boolean, Boolean>) {
My proposal was to remove this method and the job creating it entirely and just keep 'Toggle Suspend' as a single title: https://github.com/ankidroid/Anki-Android/pull/14755#discussion_r1396418008

2023-11-22 09:03 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
>      private fun onSelectedCardsChecked(result: Pair<Boolean, Boolean>) {
Removed!

2023-11-22 17:05 UTC, criticalAY commented
I messed up the rebase but cleaned in the end, jobs need to be re-run though

2023-11-22 21:25 UTC, david-allison approved these changes
Perfect!

2023-11-24 16:12 UTC, mikehardy approved these changes
Nice - going to merge this and use it as a test of new string upload to crowdin with #11557 in place

2023-11-24 16:13 UTC, merged