anchor the snackbar on fab when exporting col
ankidroid/Anki-Android pull request #14797
Opened 2023-11-22 19:05 UTC by criticalAY

## Purpose / Description
Anchor the snackbar on FAB when the collection is exported successfully or fails

## How Has This Been Tested?
google emulator
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/7253b7b6-bd61-4625-b4af-d6eea471783a)

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-11-22 19:08 UTC, criticalAY commented
I came across this when I was reproducing #14795, and regarding this issue we can use shared prefs to overcome it what say? 
I can update this PR only if the reviewer agrees to this updating the message and commits do let me know

2023-11-24 09:35 UTC, lukstbit commented
Is this really needed? I've tested the collection/apkg export and the SnackBar appears where it should, above the FAB.

2023-11-24 09:52 UTC, criticalAY commented
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/cc8a796f-c6c7-44a4-8cd2-1304ebd9bb50)
This was in case the "dont keep activity" was turned on by the user but after fixing the crash I noticed it still persist I am updating the PR to fix the crash first

2023-11-24 10:02 UTC, criticalAY commented
> Edit, forgot: I'm working on #14604 and I might be able to delete ActivityExportingDelegate, so you shouldn't spend time on #14795 .

ok, leaving it for now then 👍

2023-12-08 10:38 UTC, criticalAY commented
@lukstbit any updates on the issue?

2023-12-09 08:11 UTC, lukstbit requested changes
I've implemented the changes I wanted but it didn't touched the mExportFileName related issue. So this PR is needed, I left some reviews notes on this.

2023-12-09 08:11 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +    private var mExportFileName: String? = null
This can be deleted as we don't really this property, we could simply use the shared preferences.

2023-12-09 08:11 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +        activity.getSharedPreferences("file_prefs", Context.MODE_PRIVATE)
`activity.sharedPrefs.edt { putString() }`

2023-12-09 08:11 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +        mExportFileName = sharedPreferences.getString(EXPORT_FILE_NAME_KEY, null)
`val localFile = activity.sharedPrefs().getString(EXPORT_FILE_NAME_KEY, "") ?: ""`

then the other usages of mExportFileName can be update to take this value.

2023-12-09 08:11 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
>      private fun saveSuccessfulCollectionExportIfRelevant() {
Method should be changed to receive the path as a parameter.

2023-12-09 09:50 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +        activity.getSharedPreferences("file_prefs", Context.MODE_PRIVATE)
We should also exclude this from ACRA

2023-12-09 21:21 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +        mExportFileName = sharedPreferences.getString(EXPORT_FILE_NAME_KEY, null)
This still creates a need for a `val` so why not to use it as a lateint only

2023-12-11 00:35 UTC, david-allison commented
Minor: we should remove the name from ACRA reports in the method: `createAcraCoreConfigBuilder`

2023-12-11 14:03 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +    private var mExportFileName: String? = null
this comment has not been addressed @criticalAY - and it appears if it were addressed (by removing the var) there would be a compilation error below in `saveSuccessfulCollectionExportIfRelevant` which is assuming that mExportFileName is set and non-null (via a dangerous `!!`) but never sets it as far as I can see?

2023-12-11 14:04 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +        mExportFileName = activity.sharedPrefs().getString(EXPORT_FILE_NAME_KEY, "")
what happens if it is empty for whatever reason?

2023-12-11 14:04 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +                        CompatHelper.compat.copyFile(mExportFileName!!, fileOutputStream)
if the var was removed above and it was just a val local then you wouldn't need the dangerous !!

2023-12-11 14:05 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +            if (deleteAfterExport && !File(mExportFileName!!).delete()) {
likewise - if the var was removed above and it was just a val local then you wouldn't need the dangerous !!

2023-12-11 14:06 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +        if (!mExportFileName!!.endsWith(".colpkg")) return
we are in a new method here, and the activity may be recreated, but I don't see the filename fetched from prefs and initialized again?

If lukstbit had been handled instead of just resolved and closed without handling, then it would be a method parameter (non-null...) and you wouldn't need the dangerous !! on a var that I think is not initialized at this point

2023-12-11 14:06 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
>      private fun saveSuccessfulCollectionExportIfRelevant() {
this was not handled.

2023-12-11 15:10 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +        if (!mExportFileName!!.endsWith(".colpkg")) return
there is still a risk of it being null (it is 99.9% sure though it won't be null) as `getString(EXPORT_FILE_NAME_KEY, "")` automatically assigns null value to the pref in case it is null.

2023-12-11 15:12 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +        if (!mExportFileName!!.endsWith(".colpkg")) return
I thought it automatically assigned `""` to the pref in case it is null.
This doesn't seem to actually address the substance of my comment tho?

2023-12-11 15:14 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +        if (!mExportFileName!!.endsWith(".colpkg")) return
i am pushing the changes for that part I have used elvis operator though in case

2023-12-11 15:16 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +        if (!mExportFileName!!.endsWith(".colpkg")) return
we can't escape the evil "!!" here  ` if (!mExportFileName!!.endsWith(".colpkg")) return`

2023-12-11 17:08 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
>      private fun saveSuccessfulCollectionExportIfRelevant() {
This method is called from two other methods, in one the path is available and could be passed directly and in the other method, saveFileCallback you could retrieve the filename from preferences and pass it to saveSuccessfillColl... and also to exportToProvider() which would allow us to avoid exportfilename?:"".

2023-12-11 17:09 UTC, david-allison commented
Is it feasible to use `savedInstanceState` here instead of preferences?

2023-12-11 18:04 UTC, criticalAY commented
> Is it feasible to use `savedInstanceState` here instead of preferences?

I guess that creates the need for extra calls from the activity where we are using this class, we can avoid that by using the prefs here itself

2023-12-17 15:56 UTC, criticalAY commented
Using saved state now instead shared pref

2023-12-18 01:27 UTC, david-allison requested changes
one issue regarding invalid states, rest looks great, thanks!

2023-12-18 01:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +            if (deleteAfterExport && !File(fileExportPath?:"").delete()) {
We should likely close the dialog/fail if the path is null.

`File("").delete()` is almost certainly a no-op, but it's a scary line of code

2023-12-18 02:04 UTC, david-allison approved these changes
Looks great, thanks!

2023-12-18 18:52 UTC, mikehardy commented
At some point @criticalAY you're going to need to learn how to use git rebase and clean up your commits - this should be a one commit PR, I have no idea why there are 9 different commits most with same title

<img width="424" alt="image" src="https://github.com/ankidroid/Anki-Android/assets/782704/c9cd1f04-668a-416f-bbe2-14172ccefd53">

2023-12-18 18:53 UTC, criticalAY commented
> At some point @criticalAY you're going to need to learn how to use git rebase and clean up your commits - this should be a one commit PR, I have no idea why there are 9 different commits most with same title
> 
> <img alt="image" width="424" src="https://private-user-images.githubusercontent.com/782704/291380816-c9cd1f04-668a-416f-bbe2-14172ccefd53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MjU5MDMsIm5iZiI6MTcwMjkyNTYwMywicGF0aCI6Ii83ODI3MDQvMjkxMzgwODE2LWM5Y2QxZjA0LTY2OGEtNDE2Zi1iYmUyLTE0MTcyY2NlZmQ1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQxODUzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xN2IyNmUyODI3MjA5YTZjZWQ0OWNmNzg4NTliNjgzY2JhNWQ4ZmNhM2ZjNWM1ZWE1YWMwN2RhZTk5N2JlMjRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1kcEX5aZdLxw9PWFs2tMoDad4KO9J9sttd0Sx6upESk">

Give me a moment, will do it

2023-12-18 18:54 UTC, mikehardy requested changes

2023-12-18 18:54 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +            .withExcludeMatchingSharedPreferencesKeys("username", "hkey", "file_prefs")
Is this still a thing? Seems related to the previous design that was saved preferences based, but now you're using the bundle passed between previous-killed-activity and newly-resumed-activity ?

2023-12-18 19:39 UTC, mikehardy approved these changes
This looks clean + correct to me know and also "lighter" using the saved instance state style. It's changed a lot and with the rebase + push I'm going to ask for one more approval but I think it's smooth sailing. Thanks!

2023-12-19 05:16 UTC, david-allison requested changes
Sorry, another round due to the use of `""` as a path

2023-12-19 05:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +            fileExportPath = savedState.getString(EXPORT_FILE_NAME_KEY)
Nit: can be simplified to `?.`

2023-12-19 05:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +                        CompatHelper.compat.copyFile(fileExportPath ?: "", fileOutputStream)
Can we make the variable lateinit if it's not possible, or handle this correctly?

`""` being passed to a file operation is scary

2023-12-19 05:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +    private var fileExportPath: String? = null
as per other comments, we should keep this as lateinit, and continue to guard in the few paths where it may be uninitialised

2023-12-19 06:01 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
> +        fileExportPath = savedInstanceState?.getString(EXPORT_FILE_NAME_KEY).toString()
Sorry! this is incorrect now we've moved to `lateinit`, `null.toString() == "null"`

```kotlin
        val restoredValue = savedInstanceState?.getString(EXPORT_FILE_NAME_KEY) ?: return
        fileExportPath = restoredValue
```

2023-12-19 06:17 UTC, david-allison approved these changes

2023-12-19 06:17 UTC, david-allison commented
https://github.com/ankidroid/Anki-Android/labels/squash-merge

2023-12-19 06:23 UTC, criticalAY commented
there was a linting error causing the code quality failure so the latest commit fixes that nothing else

2023-12-20 08:39 UTC, merged