8602 - Finished fully migrating DeckPicker over to using registerForActivityResults API instead of the deprecated startActivityForResult
ankidroid/Anki-Android pull request #14818
Opened 2023-11-26 07:13 UTC by nfragiskatos

## Purpose / Description
`startActivityForResult` is deprecated. We want to replace these calls using the new Register For Activity Result APIs.
- removed the last remaining request code dependencies in DeckPicker (`PICK_APKG_FILE`, `PICK_CSV_FILE`), and replaced with their equivalent `ActivityResultLaunchers` 
- removed deprecated `onActivityResult` function from `DeckPicker` 
- `ImportFileSelectionFragment.openImportFilePicker` needed a way to grab the `ActivityResultLauncher` from the activity, so I created 2 interfaces fetch the launcher, one for APKG imports and one for CSV imports. 
- Created `ImportFileType` enum to signal to `ImportFileSelectionFragment.openImportFilePicker` which launcher it should look for

## Fixes
Related: #8602 

## How Has This Been Tested?

I ran unit tests and I manually tested the functionality on an emulator.

## Learning (optional, can help others)
Ideally, I would like to just pass some sort of interface/lambda, or even an actual `ActivityResultLauncher` into `ImportFileSelectionFragment.openImportFilePicker`, instead of relying on the `AnkiActivity` parameter, but this would also require passing it into the `ImportFileSelectionFragment.OpenFilePicker` class, and `OpenFilePicker` needs to be serializable, so that leads to serialization issues.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-11-26 09:16 UTC, lukstbit requested changes
The functionality looks good, I left some issues related to the code.

2023-11-26 09:16 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
> +        fun getResultLauncher(importFileType: ImportFileType): ActivityResultLauncher<Intent?> {
This method is unused and should be deleted.

2023-11-26 09:16 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +                                if (it is FileImportResultLauncherHolder) {
This extra check is not needed as openImportFilePicker checks that the activity implements the proper interface.

2023-11-26 09:16 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +                            (activity as AnkiActivity?)?.let {
The check should be _(activity as? AnkiActivity)?.let {}_.

2023-11-26 09:16 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
> +            }
As an improvement, add an else clause with some logging if the ifs fail:

```
else {
   Timber.w("Activity($activity) can't handle requested import: $filetype")
}
```

so we at least get a notice in logcat.

2023-11-26 09:16 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
> +    interface FileImportResultLauncherHolder : ApkgFileImportResultLauncherHolder, CsvFileImportResultLauncherHolder {
This interface seems to only exist to group the two above interfaces. While I understand the rationale behind this I think it's verbose and should be deleted(with the two interfaces being implemented individually by interested activities).

2023-11-26 12:27 UTC, nfragiskatos commented
@lukstbit, thank you for the review. I went ahead and pushed an update with the changes you requested.

2023-11-28 19:12 UTC, mikehardy approved these changes
Nice! Thank you

2023-11-28 19:13 UTC, merged