Fix changing the cards order to 'NoOrdering' after toggling to 'Notes'
ankidroid/Anki-Android pull request #14859
Opened 2023-12-01 19:06 UTC by peyman79

## Purpose / Description
When changing the display ordering for cards and then toggling to notes, the previous ordering will not persist; instead, it displays notes with no specific order (default ordering).

## Fixes
Related to #14825

## Approach
The  function doesn't include specific order
The function _findOneCardByNote_ did not affect the user-specified order on the list of cardIds; instead, it always passed the constant value 'NoOrdering' as input to the _findNotes_ function. Furthermore, the _findNotes_ function, as a result, did not take the order value into account when received from the backend.
I modified the functionality of _searchForCards_ to consistently pass the results of _findCards_, regardless of whether it is in card mode or not.

## How Has This Been Tested?
Tested on Galaxy A50 (API 29)

https://github.com/ankidroid/Anki-Android/assets/61017890/29189f00-307e-440f-9a89-5fd34a2694f8

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-12-01 19:39 UTC, david-allison requested changes
Thanks for the contribution!

This removes the 'notes' functionality, and there are unit test failures

----

Just to note: we're going to be reworking this area fairly soon after https://github.com/ankidroid/Anki-Android/pull/14843 is merged (https://github.com/ankidroid/Anki-Android/issues/11889), could you also add a unit test for the issue you're fixing, to ensure that we don't add a regression here.

2023-12-01 20:18 UTC, david-allison requested changes
review was already provided, code hasn't changed

2023-12-01 23:01 UTC, peyman79 commented
> Thanks for the contribution!
> 
> This removes the 'notes' functionality, and there are unit test failures
> 
> Just to note: we're going to be reworking this area fairly soon after #14843 is merged (#11889), could you also add a unit test for the issue you're fixing, to ensure that we don't add a regression here.

I fixed #14825 using a different approach. I included 'order by' in the query, ensuring no alteration to note functionality. Also the "notes-only mode returns one card from each note" test is passed now.

2023-12-02 00:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        val cardIds = findCards(query, order)
I know we're getting rid of this soon, but this change could be faster: return `[(cid, nid)]` from the SQL, order the list by the index of `nid` in the search results (probably converted to a `Map<>` for speed), then return `cid`

That removes what I suspect to be an expensive `ORDER BY` in the SQL, and an unnecessary call to `findCards`

2023-12-04 13:07 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        val sortedResultList = resultList.sortedBy { noteIds.indexOf(it.second) }
This feels O(n^2 log n) (`n log n` sort * `n` for the IndexOf)

Kotlin might be doing something smart here, but I'd prefer something along the lines of (untested):

```kotlin
        val noteIdMap = noteIds.mapIndexed { index, id -> id to index }.toMap()
        val sortedResultList = resultList.sortedBy { noteIdMap[it.second] }
```

2023-12-04 13:08 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        val resultList = mutableListOf<Pair<Long, Long>>()
Optional: slightly nicer with a data class

```kotlin
        data class CardIdToNoteId(val id: Long, val nid: Long)
```

2023-12-04 13:09 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
> +        saveControllerForCleanup(cardBrowserController)
This would be much cleaner using more modern Kotlin:

```
browserWithNoNewCards.apply {
```

2023-12-04 19:24 UTC, peyman79 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +        val sortedResultList = resultList.sortedBy { noteIds.indexOf(it.second) }
You're right. I tested it out, and it worked fine.

2023-12-04 19:26 UTC, peyman79 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            getColUnsafe.config.set("browserNoteSortBackwards", mOrderAsc)
I can't understand what you mean. Could you please explain it more?

2023-12-06 11:51 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            getColUnsafe.config.set("browserNoteSortBackwards", mOrderAsc)
You've introduced a new config variable to the code (which is valid)

It's useful to provide a source to where the variable came from (whether it's AnkiDroid specific or used in Anki Desktop)

If this is added to the commit message, it saves time when people are looking through the git log

2023-12-07 11:36 UTC, mikehardy approved these changes
Nice! Thanks for fixing this

2023-12-07 11:37 UTC, merged