Fix app bar color in tags dialog
ankidroid/Anki-Android pull request #14879
Opened 2023-12-05 17:07 UTC by user1823

## Purpose / Description
The tags dialog has a blue bar in Black theme, which looks ugly.

Similar to https://github.com/ankidroid/Anki-Android/issues/14642

## Fixes
* Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

Similar to https://github.com/ankidroid/Anki-Android/pull/14644

## How Has This Been Tested?

Untested

Well, I am not a dev. But, I still made this PR because it took almost the same effort as creating an issue.

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-12-05 17:19 UTC, mikehardy commented
before 
![image](https://github.com/ankidroid/Anki-Android/assets/782704/eab207f0-52c9-4d4b-85f5-ce7308d9d145)


after
![image](https://github.com/ankidroid/Anki-Android/assets/782704/f87a0046-71d3-4a6a-b02a-2eca494d0a8b)


Uh oh! Look who is a developer now @user1823 👀 - this is how it starts, you've been warned - next thing you know you'll think "oh what the hell, might as well download Android Studio, this bug is trivial" and you do, and it is, and you fix a Kotlin bug, and it just goes downhill from there 😆

2023-12-05 17:22 UTC, mikehardy requested changes
Okay - well there is some error with it that looks both trivial and subtle at the same time

```

                Caused by:
                java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f040045 a=-1}, theme={InheritanceMap=[id=0x7f120001com.ichi2.anki.debug:style/ActionBarStyle], Themes=[com.ichi2.anki.debug:style/ActionBarStyle, forced, com.ichi2.anki.debug:style/Theme.AppCompat, forced, com.ichi2.anki.debug:style/FragmentScenarioEmptyFragmentActivityTheme, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
                    at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1007)
                    at android.content.res.TypedArray.getDrawable(TypedArray.java:991)
                    at android.view.View.__constructor__(View.java:5579)
                    at android.view.View.<init>(View.java)
                    at android.view.ViewGroup.<init>(ViewGroup.java)
                    at androidx.appcompat.widget.Toolbar.<init>(Toolbar.java:266)
                    at androidx.appcompat.widget.Toolbar.<init>(Toolbar.java:262)
                    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
                    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                    at android.view.LayoutInflater.createView(LayoutInflater.java:858)
                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
                    at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1237)
                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
                    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                    at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
                    at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                    ... 18 more

TagsDialogTest > test_SearchTag_willInheritExpandState FAILED
    android.view.InflateException: Binary XML file line #7 in com.ichi2.anki.debug:layout/tags_dialog: Binary XML file line #2 in com.ichi2.anki.debug:layout/tags_dialog_title: Error inflating class <unknown>
```

I don't have a lot of experience here but I have the sneaking suspicion that @BrayanDSO can just read the lines I pasted in there (along with seeing the attr change in the diff here) and know the reason without further information or effort

2023-12-05 19:25 UTC, lukstbit reviewed
Looks good, thank you for contributing.
Regarding the failing tests in TagsDialogTest.kt, this is happening because we create the fragment under test using the theme `androidx.appcompat.R.style.Theme_AppCompat`  while the app uses `R.style.Theme_Light/Black/Dark/Plain`(where the appBarColor is actually defined). So you need to replace occurrences of `androidx.appcompat.R.style.Theme_AppCompat` with `R.style.Theme_Light` in TagsDialogTest.

2023-12-05 23:30 UTC, mikehardy commented
Thanks @lukstbit ! I gave that a go with a web edit on the file on the fork-branch, it's running now

the previous emulator test failure was unrelated, there is a *might* battle going on right now to stabilize a new androidTest test related to custom-data saving, and I believe the war on flakiness will be won there. In the meantime emulator test runs on main-based code will flake a bit

2023-12-05 23:56 UTC, mikehardy approved these changes
emulator test is a flake, it is unrelated as mentioned, and work is in progress on that
Looks like lukstbit nailed this one, 🖖

2023-12-06 06:57 UTC, lukstbit approved these changes

2023-12-06 06:58 UTC, merged