Dismissed the BackupDialog on never show again selected
ankidroid/Anki-Android pull request #14872
Opened 2023-12-04 13:02 UTC by soCallmeAdityaKumar

## Purpose / Description
Dismissed  the backup prompt on "never show again"

## Fixes
Fixes https://github.com/ankidroid/Anki-Android/issues/14732

## How Has This Been Tested?

https://github.com/ankidroid/Anki-Android/assets/101629190/9402ee60-9472-4970-af4d-48b5f65ed03a

set ONE_DAY_IN_MS=1 (for frequent popup to test)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-12-09 14:37 UTC, mikehardy requested changes
I had a hard time reasoning about this one and I have a hunch it is because the handlers were sent in opposite to intention (for some reason?) - changing that would make it correct and easier to think about assuming I've understood things correctly - @david-allison could use a second set of 👀 to see if I'm thinking correctly here

2023-12-09 14:37 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
> +            val isDisabledPermanently = deckPicker.sharedPrefs().getBoolean("backupPromptDisabled", false)
🤔  isn't the same as the var definition's getter above - the same code but without duplication?

```suggestion
```

https://github.com/ankidroid/Anki-Android/pull/14872/files#diff-1c0cb9742198b0b2914269cd8e8dd1caf5c5fc3ac5d4db42d842367f9601bba4R68-R69

2023-12-09 14:37 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
> +            if (isDisabledPermanently) {
```suggestion
            if (deckPicker.dialogPermanentlyDismissed) {
```

Using above var definition in place of local variable / duplicated code - I *think* this will work ? Completely untested

2023-12-09 14:37 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
>                  Timber.i("permanently disabling 'Backup Prompt' reminder - no confirmation")
These UI event handlers names are confusing to me, I think that might be the root cause of the issue.

I think the actual error is that in the call to this fun the handlers are swapped vs their intent based on their names. Switching to the other handler - as you have done here to fix the issue does seem like it is technically correct but it is still confusing

Shouldn't the handler blocks be swapped up above at the call site so that `onDisableReminder` is the code that actually disables the reminder, and onCancel is actually the "just dismiss the dialog" code?

https://github.com/ankidroid/Anki-Android/pull/14872/files#diff-1c0cb9742198b0b2914269cd8e8dd1caf5c5fc3ac5d4db42d842367f9601bba4R92-R96

Likely requires swapping up above at the call site then switching which handler is mapped to which button below as well https://github.com/ankidroid/Anki-Android/pull/14872/files#diff-1c0cb9742198b0b2914269cd8e8dd1caf5c5fc3ac5d4db42d842367f9601bba4R219-R220 ?

What do you think?

2023-12-09 14:57 UTC, david-allison requested changes
Please ping me if I don't re-review within 24 hours

2023-12-09 14:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
>              if (!backupPrompt.shouldShowDialog()) {
Shouldn't this logic be inside here?

2023-12-09 21:28 UTC, david-allison requested changes
This is all that should be required

```patch
Subject: [PATCH] extract: selectRowAtPosition
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt	(revision 2b10f91a825abfcbba1b83a12dd898336de8cb70)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt	(date 1702157217946)
@@ -255,7 +255,7 @@
     }
 
     private fun timeToShowDialogAgain(): Boolean =
-        nextTimeToShowDialog <= TimeManager.time.intTimeMS()
+       !dialogPermanentlyDismissed && nextTimeToShowDialog <= TimeManager.time.intTimeMS()
 
     private suspend fun userIsNewToAnkiDroid(): Boolean {
         // A user is new if the app was installed > 7 days ago  OR if they have no cards
```

2023-12-10 10:06 UTC, soCallmeAdityaKumar commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
>              if (!backupPrompt.shouldShowDialog()) {
I had removed it

2023-12-10 10:15 UTC, soCallmeAdityaKumar commented
> This is all that should be required
> 
> ```diff
> Subject: [PATCH] extract: selectRowAtPosition
> ---
> Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
> --- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt	(revision 2b10f91a825abfcbba1b83a12dd898336de8cb70)
> +++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt	(date 1702157217946)
> @@ -255,7 +255,7 @@
>      }
>  
>      private fun timeToShowDialogAgain(): Boolean =
> -        nextTimeToShowDialog <= TimeManager.time.intTimeMS()
> +       !dialogPermanentlyDismissed && nextTimeToShowDialog <= TimeManager.time.intTimeMS()
>  
>      private suspend fun userIsNewToAnkiDroid(): Boolean {
>          // A user is new if the app was installed > 7 days ago  OR if they have no cards
> ```

what if if only check time inside ```private fun timeToShowDialogAgain(): Boolean =
        nextTimeToShowDialog <= TimeManager.time.intTimeMS()``` and check ```if (!backupPrompt.shouldShowDialog()&&backupPrompt.dialogPermanentlyDismissed) {
                return false
            }```  will also run and make sense?

2023-12-10 10:16 UTC, soCallmeAdityaKumar commented
> > This is all that should be required
> > ```diff
> > Subject: [PATCH] extract: selectRowAtPosition
> > ---
> > Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
> > IDEA additional info:
> > Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> > <+>UTF-8
> > ===================================================================
> > diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
> > --- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt	(revision 2b10f91a825abfcbba1b83a12dd898336de8cb70)
> > +++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt	(date 1702157217946)
> > @@ -255,7 +255,7 @@
> >      }
> >  
> >      private fun timeToShowDialogAgain(): Boolean =
> > -        nextTimeToShowDialog <= TimeManager.time.intTimeMS()
> > +       !dialogPermanentlyDismissed && nextTimeToShowDialog <= TimeManager.time.intTimeMS()
> >  
> >      private suspend fun userIsNewToAnkiDroid(): Boolean {
> >          // A user is new if the app was installed > 7 days ago  OR if they have no cards
> > ```
> 
> what if if only check time inside `private fun timeToShowDialogAgain(): Boolean = nextTimeToShowDialog <= TimeManager.time.intTimeMS()` and check `if (!backupPrompt.shouldShowDialog()&&backupPrompt.dialogPermanentlyDismissed) { return false }` will also run and make sense?

NeedAuthorReply

2023-12-10 10:18 UTC, soCallmeAdityaKumar commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
>                  Timber.i("permanently disabling 'Backup Prompt' reminder - no confirmation")
yeah ideally onDismissReminder should dismiss the further call of the dialog , but its not working , instead onCancel() is cancelling the reminder

2023-12-10 13:38 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
>                  Timber.i("permanently disabling 'Backup Prompt' reminder - no confirmation")
Your answer does not seem to advance the thinking behind my comment.
Your answer is correct as I mention, but what do you think about **swapping the handlers** since they seem like they swapped right now. Then which handler does what would make more sense...

2023-12-10 19:13 UTC, david-allison requested changes
I feel that `shouldShowDialog` should return false if `dialogPermanentlyDismissed` is true

2023-12-10 19:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
> +            if (!backupPrompt.shouldShowDialog() && backupPrompt.dialogPermanentlyDismissed) {
This condition seems incorrect

2023-12-11 03:35 UTC, soCallmeAdityaKumar commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
>                  Timber.i("permanently disabling 'Backup Prompt' reminder - no confirmation")
ya , we can swap the handler for onCancel() and onDisableReminder() , it works fine

2023-12-11 03:39 UTC, soCallmeAdityaKumar commented
I would like to propose one issue , that whenever the user download the app for first or second time , after login the backup dialog doesn't appear just after user returns after login(the dialog should appear after successful login) , when user close the app and again opens it it shows up .

2023-12-11 05:15 UTC, david-allison approved these changes
Thanks!

2023-12-11 13:36 UTC, mikehardy approved these changes
with the handlers swapped their functions actually seem to match their names now, and the initial bug should be fixed, thanks!

2023-12-11 13:37 UTC, merged