remove reviewer ETA
ankidroid/Anki-Android pull request #14930
Opened 2023-12-10 18:18 UTC by RobozinhoD

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
* Fixes #14917 

## Approach
I removed the eta code

## How Has This Been Tested?

I opened the reviewer

![image](https://github.com/ankidroid/Anki-Android/assets/65715921/01cf5692-77f2-41cb-be6d-0341cb10e46d)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-12-10 19:05 UTC, david-allison requested changes
Minor request, rest LGTM

2023-12-10 19:05 UTC, david-allison commented on AnkiDroid/src/main/res/values/preferences.xml
> -    <string name="show_eta_preference">showETA</string>
can `PreferenceUpgradeService` be updated to remove this from current collections

2023-12-10 20:07 UTC, BrayanDSO approved these changes

2023-12-11 00:30 UTC, david-allison approved these changes
Looks great, thanks. Will get in faster if you rebase onto main where CI is less flaky

2023-12-11 02:18 UTC, mikehardy commented
I'm running strings through now

2023-12-11 02:52 UTC, merged