refactor: extract 'CardBrowserLaunchOptions'
ankidroid/Anki-Android pull request #14945
Opened 2023-12-11 18:36 UTC by david-allison

Handling will be moved into the ViewModel at a later time in which case the class is useful

* extract the concept from https://github.com/ankidroid/Anki-Android/pull/14843 

## How Has This Been Tested?
Tests, then opened the card browser and it still launched

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-12-15 10:45 UTC, lukstbit requested changes

2023-12-15 10:45 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserLaunchOptions.kt
> +        fun Intent.toCardBrowserLaunchOptions(): CardBrowserLaunchOptions? {
Small nitpick: I think this method should be a top level function in this file.

2023-12-15 10:45 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    private var launchOptions: CardBrowserLaunchOptions? = intent?.toCardBrowserLaunchOptions()
This will always be null here, the intent will not be available when this property is initialized(activity was just instantiated).

2023-12-15 11:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    private var launchOptions: CardBrowserLaunchOptions? = intent?.toCardBrowserLaunchOptions()
Great catch! Thanks

2023-12-19 08:42 UTC, lukstbit approved these changes
Good to go!

2023-12-21 19:44 UTC, mikehardy requested changes
was going to merge this one, but it took a conflict from #15010
was going to just fix the conflict but it is a little bit subtle

so instead of just YOLO'ing it (not the way to go) 🤠 proposing what I think is the conflict resolution since I already had some time in it

What do you think?

2023-12-21 19:44 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            launchOptions = null
collided with https://github.com/ankidroid/Anki-Android/commit/02ec4291922ab29632853760d762635398a637fb - I think this is the proper way to mash them together?

```suggestion
        launchOptions?.let { options ->
            if (options !is CardBrowserLaunchOptions.SystemContextMenu) return@let
            // Fill in the search.
            Timber.i("CardBrowser :: Called with search intent: %s", launchOptions.toString())
            searchWithFilterQuery(options.search.toString())
            launchOptions = null
        }```

2023-12-21 19:44 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserLaunchOptions.kt
> +    }
collided with https://github.com/ankidroid/Anki-Android/commit/02ec4291922ab29632853760d762635398a637fb - I think this is the proper way to mash them together?

```suggestion
    if (Intent.ACTION_PROCESS_TEXT == action) {
        action = Intent.ACTION_DEFAULT
        val search = getCharSequenceExtra(Intent.EXTRA_PROCESS_TEXT)
        if (search.isNullOrEmpty()) {
            return null
        }
        return CardBrowserLaunchOptions.SystemContextMenu(search)
    }```

2023-12-21 20:07 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            launchOptions = null
It is - pushed

2023-12-21 20:44 UTC, mikehardy approved these changes
let's go, CI

2023-12-21 20:44 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserLaunchOptions.kt
> +    }
You are the other of both the conflicting PRs, so I'll trust you on the startup issue remaining fixed, just noting for posterity that the one change I no longer see in the final de-conflicted conflict is where the action is bent from `Intent.ACTION_PROCESS_TEXT` to `Intent.ACTION_DEFAULT`

>         action = Intent.ACTION_DEFAULT

...just in case the note is useful for a follow-on

2023-12-21 21:02 UTC, merged