Port Anki Desktop previewer
ankidroid/Anki-Android pull request #14949
Opened 2023-12-12 01:05 UTC by BrayanDSO

## Notice
Currently under a developer option

the pending issue to solve before releasing to the public is handling audio

since right now there are a bunch of TTS work in progress, I'll defer audio handling to later

Depends on https://github.com/ankidroid/Anki-Android-Backend/pull/335

## Approach
In the commits.

## How Has This Been Tested?

[prev2.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/f826590e-934d-4484-a252-c516e3a9e189)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-12-12 01:08 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerServer.kt
> +class PreviewerServer(private val mediaDir: String) : NanoHTTPD(LOCALHOST, PORT) {
I intend to make AnkiServer/PreviewerServer/ReviewerServer to not have a reference to an Activity and join them, but given that there are some current work with AnkiServer (i.e. Image Occlusion), and the reviewer work will take more time, I preferred to create a new server class for now

2023-12-12 01:11 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +    // TODO maybe move the server to a Service and move it out of here?
or to a singleton

or to some kind of shared view model that can be used by more than one activity/fragment

or nowhere

2023-12-12 11:04 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +                    <script>bridgeCommand = function(){};</script>
Deliberately made `bridgeCommand` blank because I didn't notice a use for it in AnkiDroid

2023-12-12 14:04 UTC, david-allison reviewed
Brief review, mostly nitpicks. I'll want to run it to see how things feel

Regardless, if this is behind an experimental flag, I'm happy

* I much prefer our existing UI elements for flag/mark, are these feasible to add back in at a later date, either in Android or HTML?

2023-12-12 14:40 UTC, BrayanDSO commented on AnkiDroid/src/main/AndroidManifest.xml
> +        <activity
It can very easily be a fragment. Didn't do it because I hadn't a use for it yet. 

Maybe creating a `SimpleFragmentActivity` to host it (or any other fragment) can work well

2023-12-12 14:41 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerActivity.kt
> +        lifecycleScope.launch {
`.collect` returns `Unit`, not `Flow`, so I can't chain `launchIn` here

2023-12-12 14:43 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +            if (backsideOnly.value) {
Do what? Backside only option? If so, yes

![image](https://github.com/ankidroid/Anki-Android/assets/69634269/31b0c4ec-807a-418b-82b3-424dc032a305)

2023-12-12 14:52 UTC, BrayanDSO commented
> I much prefer our existing UI elements for flag/mark, are these feasible to add back in at a later date, either in Android or HTML?

I actually had implemented marking/changing flags in the previewer, but reverted the change to make it "only a previewer", not a card editor. 

And just to say, the current previewer doesn't show either flags or mark

2023-12-12 14:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                if (caller == CALLER_PREVIEWER_EDIT) {
I expect this whole `CALLER` logic to be refactored in the future, so I don't think that it is worth it now

2023-12-12 15:01 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +                backendException.localizedMessage?.let { onError.emit(it) }
this is basically a copy of launchCatchingTask. But, good question. I'll look into it

2023-12-12 15:27 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerActivity.kt
> +        val selectedCardIds = intent.getLongArrayExtra(CARD_IDS_EXTRA)
`!!`? `require` doesn't exist in the default API and creating a method may not be worth it when `!!` can be used

2023-12-12 15:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerActivity.kt
> +        lifecycleScope.launch {
Should be able to chain `onEach`

2023-12-12 15:49 UTC, david-allison commented on AnkiDroid/src/main/AndroidManifest.xml
> +        <activity
I'd like to, only as long as it's easy

Also to set precedent to move away from the 'one screen == one activity' concept

2023-12-12 15:52 UTC, david-allison commented
>  And just to say, the current previewer doesn't show either flags or mark

I'm aware - definitely non-blocking, but would be nice to fix (and fix with a nice UI) in the new screen

---

In terms of functionality: I'd support adding all functionality in the Previewer which is available in the Card Browser

But, we can do this later: no regressions is the most important first step. I'd rather use this as a proving ground so we can start tackling the Reviewer

2023-12-12 15:53 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerActivity.kt
> +        lifecycleScope.launch {
Done. Left only the ones that used `collectLatest`

2023-12-12 15:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +            if (backsideOnly.value) {
```kotlin
showQuestion(); 
showAnswer()
```

It would make sense to me to only `showAnswer()`

2023-12-12 15:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerActivity.kt
> +        val selectedCardIds = intent.getLongArrayExtra(CARD_IDS_EXTRA)
Apologies, what I get for reviewing on my phone

nitpick, totally optional

`        val selectedCardIds = requireNotNull(intent.getLongArrayExtra(CARD_IDS_EXTRA)) { "'$CARD_IDS_EXTRA' extra must be present" }`

2023-12-12 16:03 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +            if (backsideOnly.value) {
Yes, Anki Desktop does the same. The eval code for showing the answer needs the question to be shown before.

I agree that it is odd. Not sure if it is easier to just follow Anki to keep a reference to how things are done there in order to keep an equivalent result, or to refactor this a bit, so I went to the easiest way of just copying things.

I'll add the comment

2023-12-12 23:54 UTC, BrayanDSO commented on AnkiDroid/src/main/AndroidManifest.xml
> +        <activity
done

2023-12-13 00:03 UTC, BrayanDSO commented
> In terms of functionality: I'd support adding all functionality in the Previewer which is available in the Card Browser

I'll add both mark and flag to this PR in the next 48h. The other commits can still be reviewed

2023-12-13 23:42 UTC, BrayanDSO commented
As asked, added "marking" and "flagging" features:

[news.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/41a99945-9d2b-487a-95e4-eb3b6cec0e80)

2023-12-14 21:54 UTC, BrayanDSO commented
Split what I could to simplify the reviewing process

2023-12-15 09:06 UTC, david-allison requested changes
One potential security vulnerability, rest are just stylistic

2023-12-15 09:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerServer.kt
> +            val file = File(mediaDir, uri.substring(1))
I feel this is a path traversal vulnerability, passing in `../` into the URL

2023-12-15 09:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +            backsideOnly.emit(!backsideOnly.value)
I think `.update { }` can be used here to move it out of the task

2023-12-15 09:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +        launchCatching {
nit: I prefer `() = launchCatching { ... }`

2023-12-15 09:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +        launchCatching {
These feel copy/pasted. consider marking as duplicated, and extracting if possible

2023-12-15 09:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +            showQuestion()
I believe there was a comment here about why `showQuestion` was needed

2023-12-15 09:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +        flagCode.emit(currentCard.userFlag())
`.update { }` and this doesn't need to be `suspend`

2023-12-15 09:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +    fun launchCatching(block: suspend PreviewerViewModel.() -> Unit) {
Useful globally, should extract this

2023-12-15 09:17 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                    // only close the activity when the note is actually updated
I don't feel this comment reflects reality

2023-12-15 22:33 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +            backsideOnly.emit(!backsideOnly.value)
the method still needs `launchCatching` because it calls `showAnswer` that calls `prepareCardTextForDisplay`, which have a `withCol`.

If you mean moving only `backsideOnly.update(!backsideOnly.value)` to outside the task, I don't see the advantage

2023-12-15 22:39 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +        launchCatching {
As a personal preference, I normally avoid using `=` as method notation. I really prefer having explicit return types and even `return` than having to mentally infer all of it. Also, it is more similar to the notation of methods in other programming languages, so the mental friction is smaller. Another reason is that sometimes `=` makes the method return something when it should not do it.

I tend to only use `=` with methods when it is something super simple and that can be written in just one short line.

2023-12-15 22:45 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +        flagCode.emit(currentCard.userFlag())
Doesn't seem like an advantage to me, since this is only called at another suspend method. 

Also, if I were to use it in a non-suspend context, I believe that `tryEmit` is more appropriate, since it fits more the goal of simply updating the flow value.

2023-12-15 23:50 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +        launchCatching {
It was 
![WinkEyeWinkGIF](https://github.com/ankidroid/Anki-Android/assets/69634269/6411ecb8-8f07-4a3a-beef-6af2bf7ac9e8)

Just forgot to reuse it after my manual tests

2023-12-15 23:54 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerServer.kt
> +            val file = File(mediaDir, uri.substring(1))
I just copied what `ReviewerServer.kt` does, but that's a really really good concern. I'll give this some thought

2023-12-15 23:57 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +            showQuestion()
Added it as the doc of `showAnswer()`

2023-12-15 23:57 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                    // only close the activity when the note is actually updated
removed it

2023-12-16 00:18 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerServer.kt
> +            val file = File(mediaDir, uri.substring(1))
If you're concerned about files outside of AnkiDroid's sandbox being read, the other exposed endpoints need to be considered too. For example, getImageForOcclusion reads an arbitrary file from the filesystem, and as AnkiDroid is currently exposing all endpoints to all screens, there's the risk that JS in a shared deck could exfiltrate information. This was recently fixed in the computer version by analyzing the origin header, and only allowing certain endpoints when requests are initiated from the review screen.

2023-12-16 00:20 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerServer.kt
> +            val file = File(mediaDir, uri.substring(1))
Actually, `getUri()` in NanoHTTPD returns only `the path part of the URL.`, so this is safe

2023-12-17 07:47 UTC, david-allison approved these changes
Looks great, thanks!

2023-12-21 23:43 UTC, mikehardy approved these changes
Works for me - fantastic chunk of forward progress and behind a developer toggle I can't see how it could hurt

2023-12-22 00:02 UTC, merged