refactor: Browser lastDeckId/restrictOnDeck
ankidroid/Anki-Android pull request #14946
Opened 2023-12-11 20:03 UTC by david-allison

## Purpose / Description
* Split from https://github.com/ankidroid/Anki-Android/pull/14843, partially, partially rewritten

## Approach
⚠️ One of the more risky refactors
* We want to start moving `searchCards` into an output of the flows
* Once these are all outputs of the flows, we can move it to a combined flow inside the ViewModel

----

* Extract repository
* Extract lastDeckId to viewmodel
* Extract to flow
* Continue to extract
* Extract `mRestrictOnDeck`

## How Has This Been Tested?
Unit tests + manual testing on API 33 emulator

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-12-16 18:37 UTC, lukstbit approved these changes
Seems fine, LGTM.

2023-12-21 20:10 UTC, mikehardy requested changes
Took a conflict similar to other refactor but the conflict was YOLO-able and passing local testing so was on path to push+merge, but then I noticed something confusing on shared prefs access off AnkiDroidApp - left a note

2023-12-21 20:10 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/LastDeckIdRepository.kt
> +            context.getSharedPreferences(PERSISTENT_STATE_FILE, 0).edit {
I'm curious about this set of 3 different access to shared preferences

1- sometimes it is `AnkiDroidApp.instance.getSharedPreferences`, sometimes it is `AnkiDroidApp.instance.context.getSharedPreferences`, why different?
2- in no case it is `AnkiDroidApp.sharedPreferencesProvider`, why not?

2023-12-21 20:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/LastDeckIdRepository.kt
> +            context.getSharedPreferences(PERSISTENT_STATE_FILE, 0).edit {
`clearLastDeckId` is static, but all can and should be changed

2023-12-21 20:15 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/LastDeckIdRepository.kt
> +            context.getSharedPreferences(PERSISTENT_STATE_FILE, 0).edit {
These were using `PERSISTENT_STATE_FILE `, which I don't believe is `sharedPrefs()`

2023-12-21 20:17 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/LastDeckIdRepository.kt
> +            context.getSharedPreferences(PERSISTENT_STATE_FILE, 0).edit {
* `AnkiDroidApp.instance.sharedPrefs` -> relies on Android
* `AnkiDroidApp.sharedPrefs()` -> no reliance on Android with miminal code churn
* `SharedPreferencesProvider` -> no dependency on AnkiDroidApp's static init block

2023-12-21 20:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/LastDeckIdRepository.kt
> +            context.getSharedPreferences(PERSISTENT_STATE_FILE, 0).edit {
Added docs

2023-12-21 20:46 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/LastDeckIdRepository.kt
> +            context.getSharedPreferences(PERSISTENT_STATE_FILE, 0).edit {
Ah ha - I see the last commit with docs

>  * This exists as the old code used [PERSISTENT_STATE_FILE], rather than [AnkiDroidApp.sharedPrefs]

🤦 of course - glossed over that shared prefs can specify non-default file and didn't notice this was doing so

2023-12-21 20:47 UTC, mikehardy approved these changes
let's go - similar to the previous squash, will wait for merge queue to drain so I don't thrash it

2023-12-21 21:31 UTC, merged