refactor: move flag related stuff to Flags.kt
ankidroid/Anki-Android pull request #14979
Opened 2023-12-14 21:48 UTC by BrayanDSO

Part of #14949

2023-12-14 21:48 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Flags.kt
> +fun getFlagDrawable(@Flag flag: Int): Int {
This is a new method

2023-12-14 21:48 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Flags.kt
> +annotation class Flag
Renamed FlagDef to Flag

2023-12-14 22:26 UTC, david-allison approved these changes
Change is good

I'd personally prefer to move to an enum. The use of `IntDef` feels like a micro-optimisation which is no longer necessary

2023-12-14 23:42 UTC, BrayanDSO commented
Stopped being lazy and did the Enum. PTAL

2023-12-14 23:46 UTC, david-allison approved these changes
Beautiful

2023-12-14 23:55 UTC, david-allison requested changes
Test failures: can't `%d` the enum in a Timber.

2023-12-15 00:02 UTC, david-allison approved these changes

2023-12-15 04:18 UTC, mikehardy approved these changes
somehow ended up being net-negative code even with that gigantic copyright notice
nice!

2023-12-15 05:19 UTC, merged