feat: add device shake gesture detection
ankidroid/Anki-Android pull request #14972
Opened 2023-12-14 10:16 UTC by aalhendi

## Purpose / Description

Add shake detection. This paves the way to use the shake gesture to skip a card.
The issue description and comments were very informative.

## Fixes

* Begins to address #14270 

## Approach

As suggested, this adds the [Seismic](https://github.com/square/seismic/) dependency and implements ``ShakeDetector`` on ``LinkDetectingGestureDetector``. The approach philosophy is "minimal change" where extending current functionality is chosen over big refactors.

## How Has This Been Tested?

Unit/Integration Tests: N/A. This is a proof of concept. I hope someone else can take it from here.

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

- Android 14 Emulator. Android 13 Physical Device. (Works on my machine™️)

## Learning (optional, can help others)

This is my first time writing Kotlin and developing for Android natively.  Made a hello world and toyed with it to convert the Java example from Seismic to Kotlin.
From there I went down to where the gesture listening was being done and climbed up a few levels till it was reasonable to extend the shake detector listener class. 

## Pictures

![image](https://github.com/ankidroid/Anki-Android/assets/20049338/094ebad4-3df7-4a98-98cf-9a6fe8608ed4)
![image](https://github.com/ankidroid/Anki-Android/assets/20049338/f36ad291-5007-47ec-8c0f-24d0ebe993e0)

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-12-14 14:27 UTC, mikehardy commented
Only talking about SVG - A couple SVG options
https://github.com/ant-design/ant-design-icons/blob/master/packages/icons-svg/svg/outlined/shake.svg
https://fonts.google.com/icons?selected=Material+Symbols+Outlined:vibration:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=vibrate&icon.platform=android

I have a slight preference for the ant-design one as the google material design one is actually "vibrate" and as a user cue it may be ambiguous since it is used in other areas for vibration

But both could work

2023-12-14 14:36 UTC, mikehardy requested changes
I think this is really cool, and looks correct on a first pass

I left a non-review comment where people can debate a proper icon and everyone has graphic opinions (see: "bikeshedding") but I've attempted to be efficient by making two concrete proposals and favoring one for a real reason :-). No idea how to implement a specific icon for a gesture in the menu system though - does anyone know? Definitely need a real icon before integration tho

Other than that I had a couple of code style comments that aren't functionality related

2023-12-14 14:36 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +        val sensorManager = getSystemService(Context.SENSOR_SERVICE) as SensorManager
it appears the sensorManager is only used inside the LinkDetectingGestureDetector initialization?
Could just be moved in there to be inner-class-local?

2023-12-14 14:36 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +            sd.start(sensorManager, SensorManager.SENSOR_DELAY_UI)
and here is where my Kotlin is terrible, but I *think* it is more kotlin idiomatic to not have a val here (since it is never used again ?) and instead do something kotlin-y like `ShakeDetector(this).apply { start(<params>) }`

https://kotlinlang.org/docs/scope-functions.html#apply

this is a code style comment not a functionality comment, so opinions could defer and either way current code looks like it *works* which is of course job number 1

2023-12-14 14:36 UTC, mikehardy commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="gestures_shake" maxLength="41">Shake</string>
mild preference for a complete verb/noun pair

```suggestion
    <string name="gestures_shake" maxLength="41">Shake device</string>
```

Otherwise when I read it there was a vague doubt of, "shake what?"

2023-12-14 17:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +        val sensorManager = getSystemService(Context.SENSOR_SERVICE) as SensorManager
In addition to this: only initialize the manager if the user has defined a shake gesture

2023-12-14 17:41 UTC, david-allison commented
This looks great! Mike's handled everything I would have said, barring one comment

2023-12-14 19:58 UTC, david-allison commented
@mikehardy the display string is defined in

`Binding::GestureInput::toDiplayString -> Gesture.toDisplayString`

https://github.com/ankidroid/Anki-Android/blob/7a65160e0e23e20080091a30abdd4c05fc610e06/AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/Gesture.kt#L53-L54

2023-12-20 06:11 UTC, aalhendi commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +        val sensorManager = getSystemService(Context.SENSOR_SERVICE) as SensorManager
> In addition to this: only initialize the manager if the user has defined a shake gesture

How can I identify this?

2023-12-20 06:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +        val sensorManager = getSystemService(Context.SENSOR_SERVICE) as SensorManager
I believe: `mGestureProcessor.isBound(Gesture.SHAKE)`

2023-12-20 07:16 UTC, david-allison approved these changes
Looks great, only nitpicks

2023-12-20 07:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +            }
don't need the `isBound` here, should be handled by the GestureProcessor

2023-12-20 07:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +                val sensorManager = getSystemService(Context.SENSOR_SERVICE) as SensorManager
could do with a `Timber.d` log here

2023-12-21 15:12 UTC, mikehardy approved these changes
This looks great, thank you!
I'm clearing out our i18n pending translation queue now in order to get this in

2023-12-21 15:12 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/Gesture.kt
> +const val SHAKE_GESTURE_PREFIX = "\uD83E\uDE87"
I like the maracas! Good choice, should make sense to everyone and leans a little towards "fun" vs "boring"

2023-12-21 15:13 UTC, mikehardy commented
#15043 goes in first then this follows

2023-12-21 20:20 UTC, merged