libanki: add `addPlayButtons()` and rename `addPlayIcons()`
ankidroid/Anki-Android pull request #14978
Opened 2023-12-14 21:47 UTC by BrayanDSO

Part of #14949

2023-12-14 22:25 UTC, david-allison requested changes
Functionality is incorrect with `HtmlGenerator` - could do with a unit test to determine intent

2023-12-14 22:25 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
>          }
This is already in `HtmlGenerator.expandSounds`

2023-12-15 00:02 UTC, BrayanDSO commented
> Functionality is incorrect with HtmlGenerator

How so? I believe they do the same thing

https://github.com/ankidroid/Anki-Android/blob/12d008b2ccf558419fa439145b98e35960e5569c/AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/HtmlGenerator.kt#L55-L61

2023-12-15 00:03 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
>          }
Since I expect to delete the whole `HtmlGenerator` when the reviewer is ported as well, I preferred to "duplicate" the method and put it in the same place as the desktop version

2023-12-15 00:09 UTC, david-allison requested changes
If I understand correctly: we're checking the config twice for the same thing: once in `HtmlGenerator`, and once in `Sound.expandSounds`

Since the only call to `Sound.expandSounds` is from `HtmlGenerator`, this duplicates work

since `HtmlGenerator` needs to go (agreed), we might as well remove the functionality from there, so we're only checking once

2023-12-15 00:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
>          }
Sure, that makes sense, it needs to go

2023-12-15 00:34 UTC, BrayanDSO commented
> we're checking the config twice for the same thing: once in HtmlGenerator, and once in Sound.expandSounds

the new method `addPlayButtons`, which is the one here that checks the config, isn't used anywhere else right now, so it doesn't do any functional changes.

The `addPlayIcons` -> `avRefsToPlayIcons` rename is also a non-functional change.

Both the new previewer and reviewer won't use HtmlGenerator at all (also CardAppearance and CardHtml), so the work won't be duplicated.

2023-12-15 00:44 UTC, david-allison approved these changes
Sorry for being slow today, that works

2023-12-15 04:23 UTC, mikehardy approved these changes
🚂

2023-12-15 06:59 UTC, merged