enhancement: allow camera access when using image occlusion
ankidroid/Anki-Android pull request #15029
Opened 2023-12-19 10:34 UTC by criticalAY

## Purpose / Description
When adding a image (image occlusion) allow the user to access camera and add image using it along with gallery option

## Fixes
* Fixes #15017

## Approach
- Adding the option for the camera in note editor, with the help of bottom dialog sheet fragment the user can either choose camera or the gallery as desired.
- Used Bottom dialog sheet or the modal sheet guidelines from Google Android MDC(here)[https://github.com/material-components/material-components-android/blob/master/docs/components/BottomSheet.md]
- The bottom sheet fix class allow the horizontal height issue when using the bottom sheet in horizontal mode

## How Has This Been Tested?
Tested on google emulator and one plus nord ce (different themes)

[Screen_recording_20231219_155655.webm](https://github.com/ankidroid/Anki-Android/assets/48384865/bf9aa821-2e77-4ebf-8316-8002344d8b68)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-12-19 10:45 UTC, david-allison reviewed
This is really nice.

One nitpick for logging

One thought: I'd prefer if the design looked more like Google Keep (it feels a lot more 'Androud/clean', as the current nav feels like it belongs on iOS)

![image](https://github.com/ankidroid/Anki-Android/assets/62114487/6fa685de-bf91-4ff4-86c4-4b63a4a0cc63)


What do you think?

2023-12-19 10:45 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            Timber.e("Error creating the file: $e")
`w`, not `e`

2023-12-19 10:47 UTC, criticalAY commented
> One thought: I'd prefer if the design looked more like Google Keep (it feels a lot more 'Android & clean', as the current nav feels like it belongs on iOS)

This is implemented using menu can do that I holded back as it would have required one more menu file, implementing it and pushing it seems fine to me

2023-12-19 10:49 UTC, david-allison commented
Do it if it's not too much work

2023-12-19 11:14 UTC, criticalAY commented
Simply used the icons and switched to `wrap_content`

2023-12-19 11:15 UTC, criticalAY commented
![Screenshot_2023-12-19-16-45-10-06_7b5228b5a93c00ecba98ecb0735c59e2.jpg](https://github.com/ankidroid/Anki-Android/assets/48384865/79037b94-205a-42ab-92e9-8d1bb50f13fb)

2023-12-19 11:32 UTC, david-allison approved these changes
Looks great 👍

2023-12-19 11:50 UTC, snowtimeglass commented
Looks great. Thank you.

"Select Image" may associate with selecting an existing image from gallery, but now that the camera option has been added, how about replacing it with "Add image" like AnkiMobile?
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/163dc297-ee0f-4327-ab25-e90b7ed3028b)

2023-12-19 12:09 UTC, criticalAY commented
I am fine with either one and whatever the other like

2023-12-19 12:16 UTC, BrayanDSO requested changes
The design looks great!

Left some comments about t he code

2023-12-19 12:16 UTC, BrayanDSO commented on AnkiDroid/src/main/res/layout/image_occlusion_options_layout.xml
> +    <ImageView
Use [BottomSheetDragHandleView](https://developer.android.com/reference/com/google/android/material/bottomsheet/BottomSheetDragHandleView), so adding a handle drawable isn't necessary

2023-12-19 12:16 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/bottomsheet/BottomSheetDialogFragmentFix.kt
> +    override fun onConfigurationChanged(newConfig: Configuration) {
Does this depends on the activity having `android:configChanges="orientation"`? If so, this isn't something that we should rely on the long term (see #12832)

2023-12-19 12:16 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/bottomsheet/BottomSheetDialogFragmentFix.kt
> +open class BottomSheetDialogFragmentFix : BottomSheetDialogFragment() {
Text is too long and not clear. I'm not sure even if we can call this a `fix`, since this having the dialog collapsed in landscape mode is a design decision of the material library maintainers, not a bug per se.

Since this may not be the desirable behavior on every bottom dialog that we use, I believe that this would fit more as an extension function than a class.

2023-12-19 12:16 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/bottomsheet/BottomSheetDialogFragmentFix.kt
> +                UIUtils.convertDpToPixel(512f, requireContext()).toInt()
Why specifically using `512` instead of setting the state to expanded with `BottomSheetBehavior.STATE_EXPANDED`?

2023-12-19 12:25 UTC, david-allison commented
>> Not sure here, but is a cancel button necessary?

Tapping the scrim (obscured view) is acceptable, and feels like standard functionality. I don't think we need an explicit 'cancel'

> They can be dismissed by:
> 
> * Tapping the scrim

https://m3.material.io/components/bottom-sheets/guidelines#22deb8a2-3513-4a2e-aa47-c64875e15e12

2023-12-19 12:27 UTC, BrayanDSO commented
Also, please add screenshots of this in the other themes (plain, dark and black)

2023-12-19 12:33 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/bottomsheet/BottomSheetDialogFragmentFix.kt
> +    override fun onConfigurationChanged(newConfig: Configuration) {
Yes google did introduced that as a functionality

2023-12-19 12:38 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/bottomsheet/BottomSheetDialogFragmentFix.kt
> +    override fun onConfigurationChanged(newConfig: Configuration) {
Google apps mostly use expanded state i have seen Gpay using the collapsed state when making payments (processing them) otherwise it is mostly expanded

2023-12-19 12:41 UTC, criticalAY commented
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/dbec00a5-9df6-4b6c-a67c-22e3c43c8564)
Dark:
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/56a0eb97-2533-46fe-855b-01a584ba56b9)
Black:
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/470fbe9b-ab50-4dd3-910b-7d197f66146e)

2023-12-19 12:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/bottomsheet/BottomSheetDialogFragmentFix.kt
> +    override fun onConfigurationChanged(newConfig: Configuration) {
I'm not sure if you understood my question. AFAIK, Fragments and therefore `BottomSheetDialogFragment` only have `onConfigurationChanged` called if `android:configChanges` is set on the manifest of their host activities, so this theoretically depends on `android:configChanges` and we should avoid that.

I believe that you even can remove this block and `orientation` from `android:configChanges` on the NoteEditor declaration in the manifest, since you always call `fixBottomSheetPeekHeight` in onResume

2023-12-19 12:57 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/bottomsheet/BottomSheetDialogFragmentFix.kt
> +            }
Why not always expanded? In both portrait and landscape modes

2023-12-19 12:59 UTC, BrayanDSO commented
If it is just `Camera` and gallery, isn't there a default Android solution for that? As an example, I saw the dialog below in Notion:

![image](https://github.com/ankidroid/Anki-Android/assets/69634269/4a069518-f1d8-43a7-aff4-45d6fff069e8)

2023-12-19 15:01 UTC, snowtimeglass commented
How about the following structure:

- Add image
  - Camera
  - Files (or Gallery)
  - Clipboard

My focus here is on structure (especially about Clipboard), not naming or order.

---
**Current structure:**

- Select image
  - Camera
  - Gallery
- Paste Image from Clipboard

---
The desktop version does not have camera option, so the buttons eventually mean the two options: "Files" and "Clipboard". They are lined up on the same hierarchy.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/006f58a9-9501-44e9-9ab2-bb577319df52)



Since AnkiDroid will have camera option as AnkiMobile, it will have (at least) the three options: "Camera", "Files", "Clipboard". So perhaps the three options should be lined up on a same hierarchy, as the four options in AnkiMobile, and the two options above in the desktop version.  
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/d45005a0-3fa5-4726-b280-d684bc7a2cb6)
Based on this viewpoint on second thought, the current structure above might be a bit unnatural.

2023-12-19 15:43 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/bottomsheet/BottomSheetDialogFragmentFix.kt
> +                UIUtils.convertDpToPixel(512f, requireContext()).toInt()
no that wont work, its a intented behavior 16:9 by google doesn't work

2023-12-19 16:18 UTC, criticalAY commented
Using the flow suggested by @snowtimeglass it is much better and made some string changes i.e `Add image` instead of `Select image` and putting the option to paste image inside the bottom sheet only making more sense, 
Coming to the other question 
@BrayanDSO using `512` is one of the workaround you can't use the `EXPANDED_STATE` due the the 16:9 google factor if you go through the stack overflow link I dropped above in the workaround you would make out why that class and 512, yes we could have used the extension function rather than a class both would have done the same work no difference so doesn't matter if we used a class/function the end goal is to allow the state to be expanded, google have imposed it in M3 not a good idea though it is stupid in some cases they themselves don't follow that in some cases, and this doesn't follow is here our case we can't impose the 16:9 stupid factor as we allow the user to use our app in landscape mode.

> If it is just Camera and gallery, isn't there a default Android solution for that? As an example, I saw the dialog below in Notion:

This also requires the intents that we use currently so doesn't matter what we use and different phones have different option like my OnePlus has a share option too in case of Notion which is not there in your case(Samsung).

2023-12-19 17:22 UTC, snowtimeglass commented
> Using the flow suggested by @snowtimeglass it is much better and made some string changes i.e `Add image` instead of `Select image` and putting the option to paste image inside the bottom sheet only making more sense,

Thank you so much for your consideration and work. However, with apologies, I have updated the suggestion above. Now I'm more interested in the following structure (as the first suggestion in the updated comment above), which no longer uses the `Add image` string:
- Camera (←New button on "Add" screen)
- Files
- Clipboard

I think that it would enable users to choose one of the options more instantly and easily, just as on the following structure on the desktop version and on the current AnkiDroid 2.17alpha12:
- Files
- Clipboard

![image](https://github.com/ankidroid/Anki-Android/assets/10436072/53ec7421-d5de-45b3-8383-4d23cb97da17)
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/a812ac13-7d05-474f-adf6-9b7802ec6da4)

2023-12-19 17:26 UTC, criticalAY commented
I am making it consistent with Anki desktop

2024-01-03 19:27 UTC, mikehardy commented
@BrayanDSO no pressure - just wanted to mention I think this is pending a re-look from you  based on the comment history ?

2024-01-17 21:35 UTC, BrayanDSO commented
Busy. Don't block this because of me

2024-01-20 19:13 UTC, mikehardy commented
commit history is not reviewable commit / it's not useful

![image](https://github.com/ankidroid/Anki-Android/assets/782704/cd4780cf-c357-4ea5-a4d9-11b1a6033fb7)

2024-01-20 19:15 UTC, criticalAY commented
Will rebase

2024-01-22 00:48 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            CrashReportService.sendExceptionReport(e, "NoteEditor", "Error creating the file", true)
Logging one thing with 'w' and one with 'e' levels does not make sense to me, it is either a warning or it is an error, it is not both.

This is recoverable, so it is a warning

I don't think we should send this to the crash report service, I don't know what we would do with it? File based crash service logs are usually very low signal and lots of noise as devices have all sorts of file system issues which are non-actionable. So if we do end up needing logging here I'd prefer to add it after it's obvious and just do regular "user sends us steps to reproduce / we reproduce" triage if there are problems

```suggestion
            Timber.w("Error creating the file", e)
```

2024-01-22 04:49 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        registerForActivityResult(ActivityResultContracts.TakePicture()) { isPictureTaken ->
You mean multimedia activity where we have code to allow cropping using the library ? That code is specific to 'BasicImageFieldController'

2024-01-22 04:56 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        registerForActivityResult(ActivityResultContracts.TakePicture()) { isPictureTaken ->
We can include the library to allow image cropping, rotation, etc

2024-01-23 20:55 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        registerForActivityResult(ActivityResultContracts.TakePicture()) { isPictureTaken ->
That code shouldn't be specific to BasicImageFieldController, that code is "use this library that has some basic image editing to get the file URL for an image" - it should be possible to make that generic?

Taking photos is tricky across Android versions and hardware with regard to both file io and file permissions as well as dealing with hardware quirks - definitely do not want to reinvent the wheel - definitely want to reuse that code, making it generic if necessary

2024-01-23 23:17 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        registerForActivityResult(ActivityResultContracts.TakePicture()) { isPictureTaken ->
Will look into it

2024-02-06 03:18 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        registerForActivityResult(ActivityResultContracts.TakePicture()) { isPictureTaken ->
Done!

2024-02-11 22:35 UTC, oakkitten commented
Just a note, I would *personally* prefer all the photos I take from apps to be saved permanently in a public folder. I think since Q you can use media store API for that, IIRC without needing permission.

Also, I'm seeing that `File.createTempFile` is used, that probably won't survive process death, if that is of any concern.

2024-02-15 16:33 UTC, criticalAY commented
> that probably won't survive process death, if that is of any concern.

Why do we want to do that? I don't think we need it here

2024-02-15 20:16 UTC, oakkitten commented
Opening an external camera app means AnkiDroid can be killed while the camera is running. This used to be a common occurrence back in the day, not sure about how exactly this problem is user-visible on more modern Android versions and modern devices...

2024-02-29 20:48 UTC, criticalAY commented
@david-allison could you please remove the `stale` tag, I will get back to this in few days

2024-04-15 11:46 UTC, lukstbit requested changes

2024-04-15 11:46 UTC, lukstbit commented on AnkiDroid/src/main/res/layout/image_occlusion_options_layout.xml
> +<LinearLayout style="@style/Animation.Design.BottomSheetDialog"
Using material buttons for the options looks weird due to their color. Another issue is that the buttons are cramped on the left and this leaves a lot of wasted space which doesn't look too good. I would say it's better to replicate the material design example that you linked to. Here's a patch:

```patch
diff --git a/AnkiDroid/src/main/res/layout/image_occlusion_options_layout.xml b/AnkiDroid/src/main/res/layout/image_occlusion_options_layout.xml
index dc05512a8f..c3b58d1282 100644
--- a/AnkiDroid/src/main/res/layout/image_occlusion_options_layout.xml
+++ b/AnkiDroid/src/main/res/layout/image_occlusion_options_layout.xml
@@ -16,28 +16,55 @@
 <LinearLayout style="@style/Animation.Design.BottomSheetDialog"
     xmlns:android="http://schemas.android.com/apk/res/android"
     xmlns:app="http://schemas.android.com/apk/res-auto"
-    xmlns:tools="http://schemas.android.com/tools"
     android:layout_width="match_parent"
     android:layout_height="match_parent"
     android:orientation="vertical"
-    android:padding="10dp">
+    android:padding="16dp">
 
-    <com.google.android.material.bottomsheet.BottomSheetDragHandleView
+    <LinearLayout
+        android:id="@+id/occlusion_action_camera"
         android:layout_width="match_parent"
-        android:layout_height="wrap_content" />
+        android:minHeight="?attr/listPreferredItemHeight"
+        android:background="?attr/selectableItemBackground"
+        android:layout_height="wrap_content" >
 
-    <com.google.android.material.button.MaterialButton
-        android:id="@+id/occlusion_action_camera"
-        android:layout_width="wrap_content"
-        android:layout_height="wrap_content"
-        android:text="@string/multimedia_editor_image_field_editing_photo"
-        app:icon="@drawable/ic_camera" />
+        <ImageView
+            android:layout_width="wrap_content"
+            app:srcCompat="@drawable/ic_camera"
+            android:layout_marginEnd="24dp"
+            android:layout_marginStart="8dp"
+            android:layout_height="match_parent" />
+
+        <TextView
+            android:id="@+id/occlusion_action_camera"
+            android:layout_width="match_parent"
+            android:layout_height="match_parent"
+            android:gravity="center_vertical"
+            android:text="@string/multimedia_editor_image_field_editing_photo"
+            app:iconPadding="12dp"
+            app:icon="@drawable/ic_camera" />
+    </LinearLayout>
 
-    <com.google.android.material.button.MaterialButton
+    <LinearLayout
         android:id="@+id/occlusion_action_gallery"
-        android:layout_width="wrap_content"
-        android:layout_height="wrap_content"
-        android:text="@string/pick_image_gallery"
-        app:icon="@drawable/ic_gallery" />
+        android:layout_width="match_parent"
+        android:minHeight="?attr/listPreferredItemHeight"
+        android:background="?attr/selectableItemBackground"
+        android:layout_height="wrap_content" >
+
+        <ImageView
+            android:layout_width="wrap_content"
+            app:srcCompat="@drawable/ic_gallery"
+            android:layout_marginEnd="24dp"
+            android:layout_marginStart="8dp"
+            android:layout_height="match_parent" />
+
+        <TextView
+            android:id="@+id/occlusion_action_camera"
+            android:layout_width="match_parent"
+            android:layout_height="match_parent"
+            android:gravity="center_vertical"
+            android:text="@string/pick_image_gallery" />
+    </LinearLayout>
 
 </LinearLayout>
``` 

Don't forget to add `android:tint="?attr/coolorControlNormal"` to the two icons used in this layout so they appear correctly in light/dark themes.

2024-04-21 15:25 UTC, criticalAY commented on AnkiDroid/src/main/res/layout/image_occlusion_options_layout.xml
> +<LinearLayout style="@style/Animation.Design.BottomSheetDialog"
I made some changes here, applied the padding to child as parent padding added a weird tint when the option was pressed i.e the blank space. And added top padding to parent

2024-04-21 15:26 UTC, criticalAY commented
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/c42919b5-8683-4c16-b8ea-896dcf025a7b)

2024-04-22 16:58 UTC, lukstbit approved these changes
Great!

2024-04-25 18:56 UTC, mikehardy commented
I'd like to merge this after we cut for 2.18 - I think we've got enough to work on just at the moment for 2.18 and we need to get that out very quickly to meet a Play Store requirement

2024-05-14 09:36 UTC, david-allison commented
@mikehardy still blocked on the 2.19 cut I believe

2024-05-14 11:02 UTC, mikehardy commented
Just merge, will retrocut on tag

2024-05-14 14:00 UTC, merged