disable the save button in case of image occlusion
ankidroid/Anki-Android pull request #15030
Opened 2023-12-19 12:08 UTC by criticalAY

## Purpose / Description
When in image occlusion mode hide the save button as the note is already saved when adding the image and the user is notified 

## Fixes
* Fixes #15025

## How Has This Been Tested?
tested on google emulator 
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/f349458a-76f9-4ef4-92c5-5c12ae938e80)

![image](https://github.com/ankidroid/Anki-Android/assets/48384865/e8e12354-95f7-4719-8c2e-8acd1db62f71)

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-12-19 12:16 UTC, david-allison commented
'Preview' should be fixed rather than removed - a card should be able to be generated

More importantly, I'd like the 'back' button to warn the user about losing changes when in Image Occlusion

And to see if we can do anything to make the 'add' button more prominent. It's not intuitive in its current position

2023-12-19 12:18 UTC, david-allison requested changes

2023-12-19 12:18 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        menu.findItem(R.id.action_save).isVisible = !currentNotetypeIsImageOcclusion()
nit: extract this to a method: `canSaveNoteType()` or `canSave()`

2023-12-19 12:29 UTC, david-allison requested changes
```
NoteEditorTest > verifyStartupAndCloseWithNoCollectionDoesNotCrash FAILED
    net.ankiweb.rsdroid.BackendException$BackendDbException$BackendDbLockedException: 
        at com.ichi2.anki.CollectionManager.ensureOpenInner(CollectionManager.kt:229)
        at com.ichi2.anki.CollectionManager.access$ensureOpenInner(CollectionManager.kt:39)
        at com.ichi2.anki.CollectionManager$getColUnsafe$1$1.invoke(CollectionManager.kt:287)
        at com.ichi2.anki.CollectionManager$getColUnsafe$1$1.invoke(CollectionManager.kt:286)
        at com.ichi2.anki.CollectionManager.blockForQueue(CollectionManager.kt:266)
        at com.ichi2.anki.CollectionManager.access$blockForQueue(CollectionManager.kt:39)
        at com.ichi2.anki.CollectionManager$getColUnsafe$1.invoke(CollectionManager.kt:286)
        at com.ichi2.anki.CollectionManager$getColUnsafe$1.invoke(CollectionManager.kt:285)
        at com.ichi2.anki.CollectionManager.logUIHangs(CollectionManager.kt:302)
        at com.ichi2.anki.CollectionManager.getColUnsafe(CollectionManager.kt:285)
        at com.ichi2.anki.AnkiActivity.getGetColUnsafe(AnkiActivity.kt:[138](https://github.com/ankidroid/Anki-Android/actions/runs/7261580314/job/19783061508?pr=15030#step:9:139))
        at com.ichi2.anki.NoteEditor.getCurrentlySelectedNotetype(NoteEditor.kt:1973)
        at com.ichi2.anki.NoteEditor.currentNotetypeIsImageOcclusion(NoteEditor.kt:1998)
        at com.ichi2.anki.NoteEditor.onCreateOptionsMenu(NoteEditor.kt:999)
        at android.app.Activity.onCreatePanelMenu(Activity.java:4343)
        at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:520)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3442)
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at org.robolectric.shadows.ShadowPausedLooper$IdlingRunnable.doRun(ShadowPausedLooper.java:573)
        at org.robolectric.shadows.ShadowPausedLooper$ControlRunnable.run(ShadowPausedLooper.java:536)
        at org.robolectric.shadows.ShadowPausedLooper.executeOnLooper(ShadowPausedLooper.java:629)
        at org.robolectric.shadows.ShadowPausedLooper.idle(ShadowPausedLooper.java:104)
        at org.robolectric.shadows.ShadowPausedLooper.idleIfPaused(ShadowPausedLooper.java:177)
        at org.robolectric.android.controller.ActivityController.visible(ActivityController.java:232)
        at org.robolectric.android.internal.RoboMonitoringInstrumentation.lambda$startActivitySyncInternal$0(RoboMonitoringInstrumentation.java:134)
        at org.robolectric.shadows.ShadowInstrumentation.runOnMainSyncNoIdle(ShadowInstrumentation.java:1201)
        at org.robolectric.android.internal.RoboMonitoringInstrumentation.startActivitySyncInternal(RoboMonitoringInstrumentation.java:120)
        at org.robolectric.android.internal.LocalActivityInvoker.startActivityForResult(LocalActivityInvoker.java:47)
        at org.robolectric.android.internal.LocalActivityInvoker.startActivityForResult(LocalActivityInvoker.java:53)
        at androidx.test.core.app.ActivityScenario.launchInternal(ActivityScenario.java:360)
        at androidx.test.core.app.ActivityScenario.launchActivityForResult(ActivityScenario.java:273)
        at com.ichi2.anki.NoteEditorTest.verifyStartupAndCloseWithNoCollectionDoesNotCrash(NoteEditorTest.kt:184)
```

2023-12-19 12:55 UTC, david-allison commented
Oh, you're absolutely correct. Preview makes no sense if no image has been added

2023-12-19 12:55 UTC, criticalAY commented
Will make changes to it even the test failed going to the gym right now

2023-12-19 17:29 UTC, david-allison requested changes
Issue with the logic:

```
if (anything) {
  doIt()
} else {
   doIt()
}
```

can be simplified to `doIt()`, as the `else` is exhaustive

2023-12-19 17:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                }
This is equivalent to `launchCatchingTask { saveNote() }`

2023-12-19 17:39 UTC, criticalAY commented
> can be simplified to doIt(), as the else is exhaustive

Right! sorry about that

2023-12-20 02:42 UTC, david-allison requested changes

2023-12-20 02:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        return currentNotetypeIsImageOcclusion()
move `addNote` into here

2023-12-20 02:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +    fun canSave(): Boolean {
This is inverted. `currentNotetypeIsImageOcclusion()` means that we can't save, not that we can save

2023-12-20 02:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        // we can further extend it if required refer :https://github.com/ankidroid/Anki-Android/pull/15030#discussion_r1431330266
no need for the comment

2023-12-20 02:45 UTC, david-allison commented
Overall:

```kotlin
    private fun canSave(): Boolean = when {
        addNote && currentNotetypeIsImageOcclusion() -> false
        else -> true
    }
```

2023-12-20 07:17 UTC, david-allison approved these changes
Looks good

2023-12-21 14:44 UTC, BrayanDSO requested changes

2023-12-21 14:44 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                    }
`canSave()` returns false if in edit mode, so this means that the card can't be previewed in edit mode, which is a regression.

Also, this is really odd to read. Why something can only be previewed if it can be saved? So, I suggest to rename the method

2023-12-21 14:44 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                }
ditto

2023-12-21 14:44 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                    launchCatchingTask { saveNote() }
by the way this is repeated here and above, shouldn't `saveNote()` check if it `canSave` instead of the caller doing it?

2023-12-21 14:44 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +    }
nit: IMO if/else would be clearer than `when` if there is only a single conditional branch like this

2023-12-21 14:44 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            invalidateMenu()
add a comment explaining why `invalidateMenu()` is necessary here

2023-12-21 14:44 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +    }
add a doc to the method explaining why image occlusion notetypes "can't be saved"

2023-12-21 14:44 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        addNote && currentNotetypeIsImageOcclusion() -> false
why added notes can't be saved?

2023-12-21 18:34 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                    launchCatchingTask { saveNote() }
this option is not visible but just the test were failing and other other reason is the keyboard shortcut

2023-12-21 18:43 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                    launchCatchingTask { saveNote() }
Hence it is never called through the menu

2023-12-21 18:44 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +    }
both work the same and in case we need to extent it in future we will already have the structure so this works fine I guess

2024-01-02 19:37 UTC, BrayanDSO requested changes

2024-01-02 19:37 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            menu.findItem(R.id.action_preview).isVisible = allowSaveAndPreview()
allowSaveAndPreview() value should be stored into a variable or use a scoped function to avoid running the method twice

2024-01-02 19:37 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +     * **/
```suggestion
     */
```

2024-01-02 19:53 UTC, BrayanDSO approved these changes

2024-01-02 21:27 UTC, merged