Updated MaterialDialog to AlertDialog in SharedDecksDownloadFragment.kt
ankidroid/Anki-Android pull request #15065
Opened 2023-12-23 14:55 UTC by ritikrawat2447

## Purpose / Description
Deprecate MaterialDialog and use AlertDialog instead https://github.com/ankidroid/Anki-Android/issues/13315

## Fixes
Replaced MaterialDialog with AlertDialog.Builder under one function showCancelConfirmationDialog() of SharedDecksDownloadFragment.kt.

## Approach
Used AlertDialog 

## How Has This Been Tested?

I tested on my physical device by going inside "get shared decks" choosing any shared decks downloading it and clicking cancel to see the alert dialog which I changed. Changes are done as mentioned there is no difference in the dialog but changed the code to MaterialDilog to AlertDialog.

## Learning (optional, can help others)
Googled the official documentary for the AlertDialog.
https://developer.android.com/reference/android/app/AlertDialog.Builder

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-12-23 15:02 UTC, david-allison requested changes

2023-12-23 15:02 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            setPositiveButton("Yes") { _, _: Int ->
move back to `R.string` rather than a hardcoded string

2023-12-23 16:52 UTC, ritikrawat2447 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            setPositiveButton("Yes") { _, _: Int ->
Resolved it new commit .

2023-12-23 17:13 UTC, BrayanDSO reviewed
From the code, it should work but I can't test it right now

2023-12-23 17:13 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +import android.app.AlertDialog
```suggestion
import androidx.appcompat.app.AlertDialog
```

2023-12-23 17:32 UTC, ritikrawat2447 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +import android.app.AlertDialog
Ok, I can change it to appcompat.app.AlertDialog . I will resolve it in next commit .

2023-12-23 17:40 UTC, ritikrawat2447 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +import android.app.AlertDialog
Changed it.

2023-12-23 23:10 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +    private var mDownloadCancelConfirmationDialog: AlertDialog? = null
Can we consider using the normal naming convention and remove this `m`

2023-12-23 23:10 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                // Perform action on negative button click
You can remove this comment

2023-12-24 06:03 UTC, ritikrawat2447 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +    private var mDownloadCancelConfirmationDialog: AlertDialog? = null
ok , I can do that but there are other variables also named with 'm' so do I also need to remove 'm' from all names or just this one ?

2023-12-24 07:28 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +    private var mDownloadCancelConfirmationDialog: AlertDialog? = null
You are not refactoring so just this one for now

2023-12-24 07:38 UTC, ritikrawat2447 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +    private var mDownloadCancelConfirmationDialog: AlertDialog? = null
Ok, resolved this one and also removed the comment line. You can review the latest commit.

2023-12-24 07:39 UTC, ritikrawat2447 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                // Perform action on negative button click
Removed.

2023-12-24 07:46 UTC, criticalAY requested changes

2023-12-24 07:46 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +    private var DownloadCancelConfirmationDialog: AlertDialog? = null
The first letter should not be capital make it 
` private var downloadCancelConfirmationDialog: AlertDialog? = null`

2023-12-24 08:00 UTC, criticalAY requested changes

2023-12-24 08:00 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        DownloadCancelConfirmationDialog?.show()
Also instead on creating this `val` you can simplify the code by doing : 
```
  AlertDialog.Builder(requireContext()).show {
            title(R.string.cancel_download_question_title)
            positiveButton(R.string.dialog_yes) {
                mDownloadManager.remove(mDownloadId)
                unregisterReceiver()
                isDownloadInProgress = false
                activity?.onBackPressed()
            }
            negativeButton(R.string.dialog_no) {
                DownloadCancelConfirmationDialog?.dismiss()
            }
        }

```

2023-12-24 08:16 UTC, ritikrawat2447 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +    private var DownloadCancelConfirmationDialog: AlertDialog? = null
Sorry, I will change it.

2023-12-24 08:23 UTC, ritikrawat2447 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        DownloadCancelConfirmationDialog?.show()
Ok, I have made the changes. Please review it again.

2023-12-24 08:36 UTC, criticalAY requested changes

2023-12-24 08:36 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        }.create().show()
You removed the download variable also where this dialog is to be stored, it would give a NPE where this dialog is called in case we want to dismiss it, use the function below  
```
 @Suppress("deprecation") // onBackPressed
    fun showCancelConfirmationDialog() {
        downloadCancelConfirmationDialog = AlertDialog.Builder(requireContext()).apply {
            setTitle(R.string.cancel_download_question_title)
            setPositiveButton(R.string.dialog_yes) { _, _ ->
                mDownloadManager.remove(mDownloadId)
                unregisterReceiver()
                isDownloadInProgress = false
                activity?.onBackPressed()
            }
            setNegativeButton(R.string.dialog_no) { _, _ ->
                downloadCancelConfirmationDialog?.dismiss()
            }
        }.create()
        downloadCancelConfirmationDialog?.show()
    }
```

2023-12-24 09:22 UTC, ritikrawat2447 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        }.create().show()
Ok, I have changed the code.

2023-12-24 09:22 UTC, ritikrawat2447 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +    private var DownloadCancelConfirmationDialog: AlertDialog? = null
ok

2023-12-24 09:26 UTC, criticalAY approved these changes
Looks good, thanks!

2024-01-02 19:41 UTC, BrayanDSO approved these changes

2024-01-03 13:30 UTC, david-allison approved these changes

2024-01-03 13:30 UTC, merged