Use the new M3 adding errors end mode icon to clear text field
ankidroid/Anki-Android pull request #15067
Opened 2023-12-23 20:34 UTC by criticalAY

## Purpose / Description
AnkiWeb allows login/signup through email only and M3 provides us a method to add error- [Adding errors to a text field](https://github.com/material-components/material-components-android/blob/master/docs/components/TextField.md#adding-errors-to-a-text-field) to a text field and an end icon - [Adding errors to a text field](https://github.com/material-components/material-components-android/blob/master/docs/components/TextField.md#adding-a-trailing-icon-to-a-text-field) to clear the text or toggle password, so updating that and removing the current method to set the error. Also updating the login logic so that the login button is only enabled if the email and password are filled by the user. (Other option is to keep the login button enabled and set the errors to password field too in case it is missing) . 

Google way : 
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/cb3d6358-e698-43d4-8758-ad6409e1d761)

Twitter doesn't allow the button to be enabled if the fields are empty : 
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/7b0929b4-5136-4490-a880-d0c7a26ba26e)
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/eecca4c4-9b2c-4627-8a10-43c95de0d912)

## How Has This Been Tested?
Google Emulator 

Fresh activity : (Clear icon not there)
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/8fb1fa7e-aa50-406e-9f63-16de73ccb4af)

In case the email field is left empty :
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/d1654419-15b4-4893-ae48-8f776b0ec379)

In case wrong email : (clear icon for email text is visible)
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/3f0e75f0-ac58-44a8-83c1-3215873aa357)

In case the email is filled but pwd is empty  : 
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/691deb77-9294-44f5-af83-7a517c48b19b)

when all fields are satisfied  : 
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/867f70fd-0f9d-4665-9d5c-073f429da79f)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-12-23 23:13 UTC, criticalAY commented
[Screen_recording_20231224_044328.webm](https://github.com/ankidroid/Anki-Android/assets/48384865/029575b6-d91c-4e66-b434-ff1187d59ffa)

2024-01-02 17:58 UTC, david-allison requested changes
* If I press the 'tab' key, I can't type into the 'email' field
* I can use 'enter' to submit, even though 'sign in' is disabled

2024-01-02 20:16 UTC, criticalAY commented
> if I press the 'tab' key, I can't type into the 'email' field

I tried but I was able to do so

> I can use 'enter' to submit, even though 'sign in' is disabled

fixed! was due to the pwd field allowing login attempt when enter key was hit from the pwd field

2024-01-03 13:29 UTC, david-allison commented
[15067.webm](https://github.com/ankidroid/Anki-Android/assets/62114487/0cf059ef-451e-4565-860d-d554dfd4737a)

2024-01-03 17:10 UTC, criticalAY commented
Reproduced and fixed

2024-01-08 14:47 UTC, david-allison requested changes
One quick issue with tests

One question for research: validating emails

We may want to remove the validation is a custom sync server is used

2024-01-08 14:47 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/MyAccountTest.kt
> +        assertTrue(loginButton.performClick())
don't perform network activity in the tests - this would send automated requests to AnkiWeb (and potentially be flaky - if we get rate limited).

2024-01-08 14:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
> +        return Patterns.EMAIL_ADDRESS.matcher(email).matches()
Haven't looked hard, but from the spec, I don't believe this is fully RFC5321 compliant.

I don't think it matters here.

What does matter: 
* With a custom sync server, does the ID need to be an email

2024-01-08 15:53 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
> +        return Patterns.EMAIL_ADDRESS.matcher(email).matches()
seems reasonable though so but my assumption was only emails are allowed so no issue would amend it to check if its empty or not

2024-01-08 16:52 UTC, david-allison approved these changes

2024-01-08 16:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
> +            }
I suspect that this can be more idiomatic by using: https://developer.android.com/reference/android/view/View#attr_android:nextFocusForward + backwards

2024-01-08 19:23 UTC, david-allison approved these changes
Still an approve :)

2024-01-20 19:19 UTC, mikehardy commented
Commit history on the PR useless, please rebase / squash commits in the future such that commits are meaningful

<img width="460" alt="image" src="https://github.com/ankidroid/Anki-Android/assets/782704/d2c57ae5-76b9-43d1-b1d2-020d52d630cb">

2024-01-20 19:22 UTC, mikehardy approved these changes
There should have been one commit first which changed names from the mName to name style, as a refactor commit all by itself

Having that non-functional change mixed in with the functional change makes for a big mixed diff which is hard for a PR reviewer to understand which means it takes more time for your PRs to go through

If you want your PRs to go through quickly, do the extra work to have a clean commit trail where non-functional things are in separate commits, and functional things are in specific commits for each functional thing you can separate.

Does look like an improvement though, and strings are currently clear

2024-01-20 19:22 UTC, merged