Implemented the logic to hide the toolbar on scroll
ankidroid/Anki-Android pull request #15068
Opened 2023-12-24 02:55 UTC by neeldoshii

## Fixes
#14991 

## Approach
When the user scrolls down the toolbar will get hide and if he scrolls up the toolbar will get visible again. 
So, I have implemented a `setOnScrollChangeListener` which will keep a track on scroll behavior on the WebView performed by the user. So here if the user will scroll upwards so the toolbar will get hidden but if he scrolls downwards the toolbar will get visible again.

## Testing Instructions
1. Open the Hamburger Menu
2. Open the Statistic tab
3. Perform Vertical Scroll and check the toolbar visiblity.

## How Has This Been Tested?

This has been tested on physical device(Realme 3i) and on emulator (Google Pixel 3)

Here is the working video.

https://github.com/ankidroid/Anki-Android/assets/60827173/201c6d90-3750-41c1-8470-20587462f11b

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-12-24 08:08 UTC, criticalAY requested changes

2023-12-24 08:08 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
> +        // Scroll Change listener is used to check whether the scroll is done up or down
you can remove these comments

2023-12-24 08:08 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
> +        // to hide or show the toolbar
same

2023-12-24 08:08 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
> +                // Show the toolbar if scrolled down or at the top
same

2023-12-24 08:08 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
> +                // Hide the toolbar if scrolling up
same

2023-12-24 08:12 UTC, criticalAY commented
If you noticed the toolbar flickers when we are scrolling up or down

2023-12-24 11:28 UTC, neeldoshii commented
> If you noticed the toolbar flickers when we are scrolling up or down.

Yes, its flickering a lot, I am making one more commit as a fix of flickering.  

> you can remove these comments.

If you don't mind what's the point in removing comments from the code? I have the habit of commenting for increased readability for new contributors/beginners to understands the codebase.

2023-12-24 11:42 UTC, neeldoshii commented
@criticalAY 
I have fixed the issue of flickering on toolbar. 

I have also removed the comments which was said earlier.

2023-12-25 16:03 UTC, criticalAY commented
Code Quality 
```

> Task :AnkiDroid:ktlintMainSourceSetCheck FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt:65:1 Needless blank line(s)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt:68:1 Needless blank line(s)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt:77:61 Missing spacing before "{"
```

2023-12-25 16:03 UTC, criticalAY requested changes
Fix the lint error

2023-12-25 16:07 UTC, neeldoshii commented
> Fix the lint error

Sure.

2023-12-25 17:16 UTC, neeldoshii commented
@criticalAY lint error fixed

2023-12-27 03:05 UTC, Mukuljangir372 requested changes

2023-12-27 03:05 UTC, Mukuljangir372 commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
> +                handler.postDelayed({
`Handler` used for `delay` should not be used here because it doesn't auto-binds with lifecycle of fragment/activity.  Instead of using `Handler`, `lifecycleScope` is recommended.

2023-12-27 03:05 UTC, Mukuljangir372 commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
> +                handler.postDelayed({
Same as above:)

2023-12-29 14:58 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
> +                handler.postDelayed({
The `WebView` object itself, as any other `View`, is able to use `postDelayed`, which should be enough

2023-12-29 15:00 UTC, BrayanDSO requested changes

2023-12-29 15:00 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
> +        var isScrolling = false
The changes are being done in `PageFragment`, which means that all of its inheritors will get this behavior, but this was asked only for the Statistics screen

2024-01-01 03:55 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
> +        var isScrolling = false
> The changes are being done in PageFragment, which means that all of its inheritors will get this behavior, but this was asked only for the Statistics screen

Makes sense, I will be make the changes and release the fix in next commit.

2024-01-01 05:11 UTC, neeldoshii commented
> The WebView object itself, as any other View, is able to use postDelayed, which should be enough

@Mukuljangir372 @BrayanDSO 

I have changed the handler and used WebView object.

2024-01-01 05:11 UTC, neeldoshii commented
> The changes are being done in PageFragment, which means that all of its inheritors will get this behavior, but this was asked only for the Statistics screen

Can we have a toolbar hidden on scroll for every page? I guess it will be good from UX perspective?
What do  you think of it?

2024-01-02 03:27 UTC, Mukuljangir372 commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +                toolbar?.visibility = View.GONE
can we use `toolbar.isVisible = false` instead of using `View.GONE`?

2024-01-02 03:27 UTC, Mukuljangir372 commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +                }, 300)
Can we extract `300` in a constant. Because it being used twice.

2024-01-02 12:04 UTC, neeldoshii commented
@Mukuljangir372 
I have added the 300 seconds in the const. and instead of `toolbar?.visibility = View.GONE`, I have used `toolbar?.isVisible = false` as requested. 

Also, all the testcases have now been passed.

2024-01-03 22:07 UTC, BrayanDSO commented
The hiding process is a bit rough IMO. Could you add some kind of animation? Like the one at the Settings screen when the toolbar is collapsed

2024-01-22 16:18 UTC, neeldoshii commented
> The hiding process is a bit rough IMO. Could you add some kind of animation?

Makes sense. Can we add fade in transition or something like that?

2024-01-22 18:27 UTC, BrayanDSO commented
> > The hiding process is a bit rough IMO. Could you add some kind of animation?

> Makes sense. Can we add fade in transition or something like that?

Sounds nice

2024-01-26 08:51 UTC, Mukuljangir372 commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +        var lastScrollY = 0
We should keep it in parent (above onViewCreated()). Wdyt?

2024-01-26 08:51 UTC, Mukuljangir372 commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +            if (isAnimating) return@setOnScrollChangeListener // Ignore scroll events while animating
Do we need this comment?

2024-01-26 08:51 UTC, Mukuljangir372 commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +    private fun showToolbar(toolbar: MaterialToolbar?) {
Seems unformatted code. A line space is missing here?

2024-01-26 08:51 UTC, Mukuljangir372 commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +    private fun hideToolbar(toolbar: MaterialToolbar?) {
Same here:)

2024-01-26 08:51 UTC, Mukuljangir372 commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +            toolbar.visibility = View.VISIBLE
We should use `isVisible = true` instead of using `View.VISIBLE`

2024-01-26 08:51 UTC, Mukuljangir372 commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +            toolbar.visibility = View.GONE
Same as here:)

2024-01-26 09:02 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +            if (isAnimating) return@setOnScrollChangeListener // Ignore scroll events while animating
Yes, I added this for readability as by seeing it very hard to understand why have we even used that condition.

2024-01-26 09:03 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +    private fun showToolbar(toolbar: MaterialToolbar?) {
done.

2024-01-26 09:03 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +    private fun hideToolbar(toolbar: MaterialToolbar?) {
done.

2024-01-26 09:05 UTC, Mukuljangir372 commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +            if (isAnimating) return@setOnScrollChangeListener // Ignore scroll events while animating
Here, I think code itself is self explanatory. We can remove the comment.

2024-01-26 09:06 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +            if (isAnimating) return@setOnScrollChangeListener // Ignore scroll events while animating
ok, I will remove the comment.

2024-02-04 14:31 UTC, BrayanDSO commented
It looks quite buggy here

[Screen_recording_20240204_113037.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/7c1f0bbb-95e2-447a-a4d0-de9e26557464)

2024-02-04 18:42 UTC, user1823 commented
This comment is probably not helpful at all; I just wanted to share my thoughts.

Hiding the top region during scroll is very common in Android apps. I am quite surprised that implementing it is so difficult that the PR is pending since more than a month.

Though I am not a dev, for something this common, I would expect an easy solution (like Android allowing an app to say that this is the element that I want to hide on scroll — this would be a single-line code in the app and Android would handle the rest).

2024-02-05 17:38 UTC, mikehardy commented
@user1823 just with regard to duration of PR working through progress - was also holidays and the team has been focused on higher priority 2.17 items, everything else is starved for attention

2024-02-06 10:33 UTC, neeldoshii commented
@user1823 

> Hiding the top region during scroll is very common in Android apps. I am quite surprised that implementing it is so difficult that the PR is pending since more than a month.

Well, I don't mean to say anything but realistically I was quite busy as I was at the end of my internship so had heavy workload due to which I had no free time to contribute. Every contributor here & maintainer here are doing voluntary work each having different goal in mind to learn, upskill, get new feature of their favourite app, passion etc. We are currently focusing on releasing 2.17 so all other issues are done on lesser priority compared to higher priority issues tackled for 2.17 to roll up the update.

**Coming towards technical part.** 
The fix could have been done using a simple fix using coordinator layout but the issue arrived during that time was we had web view and web view scroll was not detected by coordinator layout due to which toolbar hide was not correctly. I added a programmatic manual approach in which handling animation and toggling scroll is hectic. I don't want to create excuses. I am sorry I could have tackled it using the hack of `nested scroll` and did it easily. 

> By the way, with a quick Google search, I encountered the following page. It seems to be similar to what I envisioned and might be helpful.
https://guides.codepath.com/android/handling-scrolls-with-coordinatorlayout

Thank you though. I have fixed it, releasing a commit.

Thank you for your time.

2024-02-06 11:08 UTC, neeldoshii commented
> It looks quite buggy here
> 
>  Screen_recording_20240204_113037.webm


https://github.com/ankidroid/Anki-Android/assets/60827173/0aef5d00-000a-45b8-8e37-1e842a9cc6d3

Did a slow, fast scroll, normal scroll. Works fine now.

2024-02-12 10:23 UTC, BrayanDSO commented
> Adding coordinator layout in this will gonna make all the inherited class of pageFragment use this. Should we have separate xml for statistics?

yes, that's the open/closed principle. We don't want to create any bugs because of it (I could find one in the Image Occlusion page).

Also, here's a patch on top of the current changes that fixes the status bar color (you still need to migrate this into a statistics xml):

```patch
Index: AnkiDroid/src/main/res/layout/page_fragment.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/res/layout/page_fragment.xml b/AnkiDroid/src/main/res/layout/page_fragment.xml
--- a/AnkiDroid/src/main/res/layout/page_fragment.xml	(revision 592b61462f4208198b11a8150082b75f7ec12659)
+++ b/AnkiDroid/src/main/res/layout/page_fragment.xml	(date 1707732870687)
@@ -3,12 +3,14 @@
     xmlns:android="http://schemas.android.com/apk/res/android"
     xmlns:app="http://schemas.android.com/apk/res-auto"
     android:layout_width="match_parent"
-    android:layout_height="match_parent">
+    android:layout_height="match_parent"
+    android:fitsSystemWindows="true">
 
     <com.google.android.material.appbar.AppBarLayout
         android:id="@+id/app_bar"
         android:layout_width="match_parent"
-        android:layout_height="wrap_content">
+        android:layout_height="wrap_content"
+        android:fitsSystemWindows="true">
 
     <com.google.android.material.appbar.MaterialToolbar
         android:id="@+id/toolbar"
@@ -23,14 +25,14 @@
     <androidx.core.widget.NestedScrollView
         android:layout_width="match_parent"
         android:layout_height="match_parent"
-        android:fillViewport="false"
-        android:fitsSystemWindows="true"
         app:layout_behavior="@string/appbar_scrolling_view_behavior">
-    <WebView
-        android:id="@+id/webview"
-        android:layout_width="match_parent"
-        android:layout_height="match_parent"
-        android:visibility="invisible"/>
+
+        <WebView
+            android:id="@+id/webview"
+            android:layout_width="match_parent"
+            android:layout_height="match_parent"
+            android:visibility="invisible"/>
+
     </androidx.core.widget.NestedScrollView>
 
 </androidx.coordinatorlayout.widget.CoordinatorLayout>
\ No newline at end of file
```

2024-02-29 18:16 UTC, neeldoshii commented
Keep Open. Working!!!

2024-03-21 19:36 UTC, closed without merging

2024-03-31 00:27 UTC, neeldoshii commented
Will take it once I get free, but for next 1-2 week I am on break so if someone wants to work on this issue feel free to work on this. Refer the above patch provided by Brayan, just need a refactor to get this working for just this implemented only in statistics screen.