fix : Placeholders in delete note type dialog
ankidroid/Anki-Android pull request #15073
Opened 2023-12-24 14:05 UTC by pratyaksh1610

## Purpose / Description
fix : Placeholders in delete note type dialog.

## Approach
Replace strings.

## How Has This Been Tested?

![image](https://github.com/ankidroid/Anki-Android/assets/76740999/ac73ff2b-28e7-4ddd-be5b-310c34e45776)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-12-24 16:58 UTC, david-allison requested changes

2023-12-24 16:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +                positiveButton(R.string.dialog_yes) {
As per material guidelines, I believe this should be `delete/cancel` 

(I could only find this for V2)

> Don’t use action text that fails to indicate what the selection will do. “Cancel” and “Delete” better indicate what will occur in this dialog.

https://m2.material.io/components/dialogs

> The confirmation action is disabled until all mandatory fields are filled. Use descriptive verbs such as “Save,” “Send,” “Share,” “Update,” or “Create.” Don’t use vague terms such as “Done,” “OK” or “Close.”

https://m3.material.io/components/dialogs/guidelines

2023-12-25 07:09 UTC, pratyaksh1610 commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +                positiveButton(R.string.dialog_yes) {
`Delete` would be a better option imo.

2023-12-25 08:02 UTC, david-allison approved these changes

2023-12-26 15:16 UTC, lukstbit approved these changes
Thanks, but before we can merge this you need to squash the 3 commits in this PR into a single one.

As a side note, using multiple commits it's only valid if each commit introduces a specific change(this doesn't apply here as the change is very small). Here's [one article](https://www.freecodecamp.org/news/git-squash-commits/) about squashing, there are  more if you search for "_git squashing_".

2023-12-26 19:50 UTC, lukstbit approved these changes
Thanks!

2023-12-26 20:04 UTC, merged