Namespace declaration is never used
ankidroid/Anki-Android pull request #15088
Opened 2023-12-26 10:28 UTC by neeldoshii

Removed the namespace which are declared but not used from string and xml files.

## Purpose / Description
Fixed the Unused Namespace Declaration Android Studio warnings.

## Fixes
Related to #13282 

## Approach
_How does this change address the problem?_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-12-26 13:37 UTC, BrayanDSO commented
I believe that the locales XML files are automatically generated, so there is no value in changing them directly.

Also, this issue can go on forever since someone will always forget to remove it. Unless we start using the headless IDE linter proposed at #13282, I don't think this is worth reviewing

2023-12-29 12:35 UTC, ShridharGoel approved these changes

2024-01-01 03:51 UTC, neeldoshii commented
Thank you @ShridharGoel for approving the PR.

2024-01-11 14:30 UTC, mikehardy commented on AnkiDroid/src/main/res/layout/locale_dialog_fragment_textview.xml
> +    android:padding="@dimen/content_vertical_padding" />
it is difficult to review the 101 files changed when more than removing the namespace is happening

here spacing is changed which makes me think "oh now was `android:padding` also removed?"

only on close examination (read as: after demanding time from a busy reviewer) is it possible to see that this line did not have a semantic difference

2024-01-11 14:30 UTC, mikehardy commented on AnkiDroid/src/main/res/layout/locale_dialog_fragment_textview.xml
> +<androidx.appcompat.widget.AppCompatTextView xmlns:android="http://schemas.android.com/apk/res/android"
spacing change, muddies the diff, harder to review

2024-01-11 14:31 UTC, mikehardy commented on AnkiDroid/src/main/res/layout/navigation_drawer_layout.xml
> +    android:fitsSystemWindows="true">
etc - -5 +4 diff, but it should just be -1

2024-01-11 14:33 UTC, mikehardy commented on AnkiDroid/src/main/res/layout-land/introduction_layout.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
this spacing change should be reverted - there is no reason to have a stack of things formatted nicely but with one-and-only-one snuggled up on the tag opening line

2024-01-11 14:33 UTC, mikehardy commented on AnkiDroid/src/main/res/layout/card_browser.xml
> +<androidx.coordinatorlayout.widget.CoordinatorLayout android:id="@+id/root_layout"
same, please revert this

2024-01-11 14:33 UTC, mikehardy commented on AnkiDroid/src/main/res/layout/locale_dialog_fragment_textview.xml
> +    android:padding="@dimen/content_vertical_padding" />
unnecessary spacing change

2024-01-11 14:34 UTC, mikehardy commented on AnkiDroid/src/main/res/layout/reviewer_fullscreen_noanswers.xml
> +<androidx.coordinatorlayout.widget.CoordinatorLayout android:id="@+id/root_layout"
prefer to just get rid of the xmlns:tools line snuggled up on tag open vs moving the android:id up there, one is a clean 1-line diff, other is -2 +1

2024-01-11 14:36 UTC, mikehardy requested changes
this seems okay, and I believe a compilation test is enough to prove it works, but by including irrelevant spacing changes in the diff, it's more difficult to review.

I left a few specific comments on things to revert and I recognize it is being really picky, but the way you do one thing is the way you do all things, and we want to be in the habit in this repo of never proposing diffs with unnecessary spacing changes unless they are in a clean+separate commit. We value reviewer time more than that

2024-01-12 16:27 UTC, david-allison commented
Optional: My understanding is that if we make the change in the "main" file, then the translation sync process will remove it when it next occurs

This would massively cut down on the changes in this PR

2024-02-06 18:42 UTC, closed without merging