refactor: CardBrowser - searchTerms
ankidroid/Anki-Android pull request #15095
Opened 2023-12-27 14:13 UTC by david-allison

Split from #14843

This completes the move of a sufficient subset of state to the ViewModel. This also starts restructuring search such that it is driven by the ViewModel, rather than driven by the UI

* Blocked on #15077
* Blocked on #15094

2024-01-04 12:09 UTC, lukstbit approved these changes
I don't see any issue with this, so LGTM!
Is #14843 the next one to review?

2024-01-04 12:41 UTC, david-allison commented
> I don't see any issue with this, so LGTM! Is #14843 the next one to review?

That's it for now. We've removed ~600 LOC from that PR, but I don't feel it's 'reviewable' yet

Once this is in, I believe I can start on the larger refactorings (`searchCards`)

2024-01-05 05:07 UTC, mikehardy requested changes
🤔  general searching use cases seem to work, however:

1- if you have some cards with "test" in them and search for "test", you will see correct results and "test" in the search box
2- if you save that search then
3- if you clear the search and go back to the card browser not searching
4- and then use 3-dot menu to select "My searches" and choose that saved search
5- you will get the correct search results *but you will not see the search terms in the search box*

Note that if you skip step 3, so you are in a search mode when you load a saved search, the search term *will* be in the search box, even if it has to replace an existing search term

2024-02-03 22:14 UTC, david-allison commented
deferred until 2.18

2024-03-20 21:46 UTC, BrayanDSO requested changes
The searchView query isn't updated in the first time I run a `Saved search`

slightly off-topic: first time I discovered the feature, and I find it odd. Why not show the last queries in a dropdown list like `SearchPreference`, Anki, Google, or any search bar? (I know this is a refactor and I'm just proposing other ideas)

[Screen_recording_20240320_183858.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/30c88bfe-918c-4c6b-85e3-c2c29906d8f4)

2024-04-05 23:09 UTC, david-allison commented
@BrayanDSO Fixed in final commit

2024-04-06 10:26 UTC, BrayanDSO approved these changes

2024-04-06 12:44 UTC, merged