Improve export compatibility with desktop code
ankidroid/Anki-Android pull request #15102
Opened 2023-12-28 14:11 UTC by lukstbit

## Purpose / Description

Replicates(almost) the desktop dialog when exporting a collection/apkg/notes/cards either directly or from the browser. See the images below on how it looks. The new dialog is inserted replacing the previous(first) ExportDialog, there's no other change in the export flow.

Some notes for reviewers:
- The factory methods newInstance() could be combined into one with default arguments, I made them independent to clearly state the goal of the export(and to avoid adding logic to verify options passed in)
- I didn't add the export option "Support older Anki versions"(do we need it?), see the images below
- A related test is now ignored as the new code uses AlertDialog while the test looks for a MaterialDialog and in order to make the test pass it would require a lot of refactoring. As a side note,  we could look into deleting the tests in DeckPickerContextMenuTest. We could shave some seconds from running the tests(aprox. 33 seconds on my PC) plus I don't think they provide that much value(testing that a dialog with a specific title is shown after clicking a menu option). 

Collection export(desktop vs phone):
<img src="https://github.com/ankidroid/Anki-Android/assets/52494258/e4f98666-07c7-4652-bbf0-e5bb427eeab1" width="380px" height="220px" /><img src="https://github.com/ankidroid/Anki-Android/assets/52494258/f9f2f309-e149-41ae-8e59-647b55195c24" width="380px" height="720px" />

Apkg export:

<img src="https://github.com/ankidroid/Anki-Android/assets/52494258/a713b5e7-6020-4178-b825-d2516d027dc6" width="380px" height="220px" /><img src="https://github.com/ankidroid/Anki-Android/assets/52494258/fcdddadf-2394-46cd-9724-a11fa777dc6f" width="380px" height="720px" />

Notes text export:

<img src="https://github.com/ankidroid/Anki-Android/assets/52494258/fbd17762-7940-4fcb-bc20-4fca8c670ef7" width="380px" height="220px" /><img src="https://github.com/ankidroid/Anki-Android/assets/52494258/26012860-4d47-4740-9977-9a97199b0ce5" width="380px" height="720px" />

Card text export:

<img src="https://github.com/ankidroid/Anki-Android/assets/52494258/2630b432-01a3-4c62-a0cd-2d37d20b3fd8" width="380px" height="220px" /><img src="https://github.com/ankidroid/Anki-Android/assets/52494258/8bc01dbc-1acf-4741-bab1-73563bf0f60b" width="380px" height="720px" />

Exporting a selection of cards/notes from the browser:

<img src="https://github.com/ankidroid/Anki-Android/assets/52494258/7aa939e0-ec95-4420-a8d0-61aad3a4d78c" width="380px" height="220px" /><img src="https://github.com/ankidroid/Anki-Android/assets/52494258/f2172064-49ce-43b4-a7a4-cd7f1d8ec121" width="380px" height="720px" />

## Fixes
* Fixes #14604

## How Has This Been Tested?

Ran the tests and manually verified the export scenarios in the app.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-12-28 16:35 UTC, BrayanDSO reviewed
Super good

My only real concern is about the translation of the export prefix when selecting cards/notes from the browser.

The other comments are optional

---
About your comments:

> - I didn't use AnkiActivity.showDialogFragment() as this left the
dialog still showing after the export was done due to how the helper method
does the fragment transaction.

I don't like AnkiActivity.showDialogFragment() anyway, so I don't care

> I didn't add the export option "Support older Anki versions"(do we need it?), see the images below

I don't think we need it

> A related test is now ignored as the new code uses AlertDialog while the test looks for a MaterialDialog and in order to make the test pass it would require a lot of refactoring. As a side note, we could look into deleting the tests in DeckPickerContextMenuTest. We could shave some seconds from running the tests(aprox. 33 seconds on my PC) plus I don't think they provide that much value(testing that a dialog with a specific title is shown after clicking a menu option).

Agreed

2023-12-28 16:35 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +                    3 -> handleCardsInPlainTextExport()
Maybe using an enum or a comment with a quick link (`/** Indexes from [exportExtraViewIds] */`) would help understanding those indexes

2023-12-28 16:35 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +            null -> (deckSelector.adapter as DeckDisplayAdapter).getItem(deckSelector.selectedItemPosition).name
The file name is translated in Anki Desktop (same string of exportingSelectedNotes() I believe)

2023-12-28 16:35 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +            HtmlCompat.fromHtml(exportingInclude(), HtmlCompat.FROM_HTML_MODE_LEGACY)
Could you add a comment saying that the html parsing is because the titles from desktop have bold tags? (To avoiding other people like me checking why)

2023-12-29 13:09 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +        dialogView.initializeCardsExportUi(CollectionManager.TR)
I used _apply {}_ as I could inline the method calls with the view inflation code.

2023-12-29 13:10 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +        dialogView.initializeCardsExportUi(CollectionManager.TR)
Thanks, should have done this from the beginning.

2023-12-29 14:24 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +            null -> (deckSelector.adapter as DeckDisplayAdapter).getItem(deckSelector.selectedItemPosition).name
Nice catch, didn't noticed this.

2023-12-29 14:54 UTC, BrayanDSO approved these changes
LGTM. Really great

2023-12-29 15:09 UTC, david-allison requested changes
Looks great! One request for UI stability. Treat this as an "approve" when done

2023-12-29 15:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +            // add "All decks" option on first position to replicate desktop
We should add this to the long list of legit Kotlin cleanups, the deck selector isn't great

2023-12-29 15:09 UTC, david-allison commented on AnkiDroid/src/main/res/layout/dialog_export_options.xml
> +    <TextView
I'm not sure if it's as much of a problem in newer versions of Android, but we have `FixedTextView` which used to handle a number of crashes across manufacturers

2023-12-30 18:24 UTC, david-allison approved these changes

2023-12-30 18:25 UTC, david-allison commented
https://github.com/ankidroid/Anki-Android/labels/Strings

* https://github.com/ankidroid/Anki-Android/pull/15111

2023-12-30 20:31 UTC, merged