github action to check conflict in pr and add label
ankidroid/Anki-Android pull request #15101
Opened 2023-12-28 11:01 UTC by krmanik

## Purpose / Description

Scan PR in current repo and add label to conflicting PR after other PR merged to main branch.

## Fixes
* Fixes #13264

## Approach
_How does this change address the problem?_

Using https://github.com/actions/github-script

Get all opened pr in current repo, get pr from list then get mergeable state of the pr, also added delay 1 second becuase on merge of other pr to main branch the mergeable state are unknown so after delay, the state may be dirty or clean, if dirty add `Has Conflicts`

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

Tested on temp repo

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

https://octokit.github.io/rest.js/v20
https://github.com/actions/github-script

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2023-12-28 11:46 UTC, david-allison requested changes
One question, one bug, one nitpick.

Intention looks great, thanks! Will really help with the maintenance burden

2023-12-28 11:46 UTC, david-allison commented on .github/workflows/conflict.yaml
> +  - cron: "* 12 * * *"
What's the intention here? This reads as 'once per minute between 12:00 and 13:00'

Ideally once per hour, open to other reviewers' thoughts (depending on how slo the job is)

2023-12-28 11:46 UTC, david-allison commented on .github/workflows/conflict.yaml
> +                            await wait(1);
the parameter is `ms`, not `s`

2023-12-28 11:46 UTC, david-allison commented on .github/workflows/conflict.yaml
> +                        } while (pullRequestData.data.mergeable_state === 'unknown');
Add a terminal condition or timeout somewhere - we don't want to spam GitHub

2023-12-28 12:16 UTC, krmanik commented on .github/workflows/conflict.yaml
> +  - cron: "* 12 * * *"
No intention, just visited this and copied https://crontab.guru/
Open for discussion, currently added 2 hour.

2023-12-28 12:16 UTC, krmanik commented on .github/workflows/conflict.yaml
> +                        } while (pullRequestData.data.mergeable_state === 'unknown');
Added iteration count 10 or if state is not unknown

2023-12-28 12:33 UTC, david-allison approved these changes
Thanks!

2023-12-28 12:33 UTC, david-allison commented on .github/workflows/conflict.yaml
> +  - cron: "59 * * * *"
would be better at '0' IMO

2023-12-28 13:07 UTC, krmanik commented on .github/workflows/conflict.yaml
> +      - uses: actions/checkout@v2
Not required, updated it.

2023-12-28 13:08 UTC, krmanik commented on .github/workflows/conflict.yaml
> +  - cron: "59 * * * *"
done

2023-12-30 14:43 UTC, lukstbit approved these changes
LGTM. 
Please squash so we can merge this.

2023-12-30 19:00 UTC, merged