feat: implement  Congrats screen links and deck options button
ankidroid/Anki-Android pull request #15219
Opened 2024-01-13 00:42 UTC by BrayanDSO

## Fixes
* Fixes most of #14955. 

Only pending thing is the button leading to the deck description. I haven't added the `Unbury` and `Custom study` buttons because I think that the links are sufficient

## Approach
In the commits. On top of #15218. Only the last 5 commits are new

## How Has This Been Tested?

Emulator 31:
[Screen_recording_20240112_213816.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/25fa0a7d-a068-4f85-bd09-4b099f2444b8)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-01-13 00:44 UTC, BrayanDSO commented
Some issues I found that during the video that are probably unrelated to these changes (and I don't have time to try to reproduce):

The webview background not being colored:
```
2024-01-12 21:38:48.486 10625-10625 chromium                com.ichi2.anki.debug                 I  [INFO:CONSOLE(1)] "Uncaught (in promise) Error: 500: Fragment CongratsPage{5c018aa} (488469fe-243a-4c2f-b471-48f761aee1aa) not attached to an activity.", source: http://127.0.0.1:34433/backend/web/congrats.js (1)
```

---
The ReviewState error messages:
```text
net.ankiweb.rsdroid.exceptions.BackendInvalidInputException: card was modified: Normal(
                                                                                                        Review(
                                                                                                            ReviewState {
                                                                                                                scheduled_days: 3,
                                                                                                                elapsed_days: 3,
                                                                                                                ease_factor: 2.65,
                                                                                                                lapses: 0,
                                                                                                                leeched: false,
                                                                                                                memory_state: None,
                                                                                                            },
                                                                                                        ),
                                                                                                    ) Filtered(
                                                                                                        Rescheduling(
                                                                                                            ReschedulingFilterState {
                                                                                                                original_state: Review(
                                                                                                                    ReviewState {
                                                                                                                        scheduled_days: 3,
                                                                                                                        elapsed_days: 0,
                                                                                                                        ease_factor: 2.5,
                                                                                                                        lapses: 0,
                                                                                                                        leeched: false,
                                                                                                                        memory_state: None,
                                                                                                                    },
                                                                                                                ),
                                                                                                            },
                                                                                                        ),
                                                                                                    )
                                                                                                    	at net.ankiweb.rsdroid.exceptions.BackendInvalidInputException$Companion.fromInvalidInputError(BackendInvalidInputException.kt:37)
                                                                                                    	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:114)
                                                                                                    	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:271)
                                                                                                    	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
                                                                                                    	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:118)
                                                                                                    	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:117)
                                                                                                    	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:131)
                                                                                                    	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:117)
                                                                                                    	at anki.backend.GeneratedBackend.answerCardRaw(GeneratedBackend.kt:676)
                                                                                                    	at anki.backend.GeneratedBackend.answerCard(GeneratedBackend.kt:681)
                                                                                                    	at com.ichi2.libanki.sched.Scheduler.answerCard(Scheduler.kt:100)
                                                                                                    	at com.ichi2.anki.Reviewer$answerCardInner$2.invoke(Reviewer.kt:1037)
                                                                                                    	at com.ichi2.anki.Reviewer$answerCardInner$2.invoke(Reviewer.kt:1036)
                                                                                                    	at com.ichi2.libanki.ChangeManagerKt$undoableOp$2.invoke(ChangeManager.kt:96)
                                                                                                    	at com.ichi2.libanki.ChangeManagerKt$undoableOp$2.invoke(ChangeManager.kt:95)
                                                                                                    	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:106)
                                                                                                    	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:104)
                                                                                                    	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:90)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                        [...]

2024-01-14 11:46 UTC, Mukuljangir372 approved these changes

2024-01-14 16:21 UTC, BrayanDSO commented
> The webview background not being colored:
> 
> ```
> 2024-01-12 21:38:48.486 10625-10625 chromium                com.ichi2.anki.debug                 I  [INFO:CONSOLE(1)] "Uncaught (in promise) Error: 500: Fragment CongratsPage{5c018aa} (488469fe-243a-4c2f-b471-48f761aee1aa) not attached to an activity.", source: http://127.0.0.1:34433/backend/web/congrats.js (1)
> ```

Not new. Got one when I was studying

2024-01-14 16:33 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
> +        }
I'm open to any ideas that can be written more beautifully than this. What I wanted to do was keeping the deck options destination restrict to the viewModelScope and the activity methods to the activity's scope

2024-01-15 09:49 UTC, Mukuljangir372 commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
> +        }
As far as I can see, It doesn't make sense to using `viewModelScope.async` here. We can simply move the `getDeckOptionsDestination()`  inside `lifecycleScope.launch` to avoid using `await` as well. What do you think?

2024-01-15 12:49 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
> +        }
The task would be cancelled if the activity gets recreated (e.g. rotation changes) when the computation is being done, which would be a bug

2024-01-15 23:05 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
> +        }
Okay, I think I got a better idea, so I updated it.

2024-01-15 23:09 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
> +    }
Maybe move this into a Flow like onDeckOptions()? I don't know what is the standard/best practice here

2024-01-17 01:17 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
> +    }
did it to make things consistent

2024-01-18 01:32 UTC, david-allison requested changes
One change request for the back button behaviour

Code looks good

2024-01-18 01:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
> +                requireActivity().finish()
The back behaviour feels jarring due to this call.

I would expect:
* Reviewer -> Complete
* Congrats
* Deck Options
* Back should take a user to 'Congrats', not 'DeckPicker'

2024-01-18 01:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
> +    fun getCurrentId(): DeckId = col.backend.getCurrentDeck().id
In libAnki: https://github.com/ankitects/anki/blob/main/pylib/anki/decks.py#L412-L414

2024-01-18 01:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
> +    fun unburyDeck(
We probably want a `@RustCleanup` here to ensure we're correctly handling/specifying 'user/scheduler buried'

Some of the calls looks potentially incorrect and I'd like them to be explicit if questionable

2024-01-18 22:24 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
> +                requireActivity().finish()
Removed `requireActivity().finish()`

2024-01-18 22:33 UTC, david-allison approved these changes
Perfect, thanks!

2024-01-20 23:08 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
> +        super.onViewCreated(view, savedInstanceState)
haha - noted!

2024-01-20 23:16 UTC, mikehardy approved these changes
steady forward progress, thanks @BrayanDSO !

2024-01-20 23:48 UTC, merged