refactor: Anki pages WebViewClient creation and asset loading
ankidroid/Anki-Android pull request #15218
Opened 2024-01-13 00:16 UTC by BrayanDSO

## Purpose / Description
In the commits.

## Approach
In the commits. 
## How Has This Been Tested?

Emulator 31: Open the statistics and card info pages to see if things are still loading

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-01-14 11:45 UTC, Mukuljangir372 approved these changes

2024-01-14 15:45 UTC, david-allison requested changes
Much cleaner! One request to not log the file name

2024-01-14 15:45 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt
> +                Timber.w("%s not found", path)
This leaks user file names to ACRA

2024-01-14 16:25 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt
> +                Timber.w("%s not found", path)
this only applies to files under `/backend/web/` that are used in Anki backend pages, so there shouldn't be any user files there

2024-01-14 20:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt
> +                Timber.w("%s not found", path)
We're almost certainly fine here then

2024-01-14 20:56 UTC, david-allison approved these changes

2024-01-15 00:24 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt
> +                Timber.w("%s not found", path)
(logging the backend names is helpful for debugging issues with missing files, like the recent missing anki-package-import.html problem)

2024-01-16 12:09 UTC, lukstbit approved these changes
LGTM!

Left two small issues(one from this refactoring + one from my code) if you want to fix them here. Either way feel free to merge this.

2024-01-16 23:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiPackageImporterFragment.kt
>      private lateinit var backCallback: OnBackPressedCallback
done

2024-01-16 23:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
> +        return inflater.inflate(R.layout.page_fragment, container, false)
TIL. Really nice. Thanks!

2024-01-17 01:40 UTC, merged