Answer Button Arrow keys fixed
ankidroid/Anki-Android pull request #15229
Opened 2024-01-15 19:47 UTC by soCallmeAdityaKumar

## Purpose / Description
Unnecessary dummy card was shown on next card if reverse was empty

## Fixes
* Fixes #15093

## How Has This Been Tested?

https://github.com/ankidroid/Anki-Android/assets/101629190/1f21b198-389b-4378-8ea7-bb58720b6d0b

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-01-15 21:52 UTC, BrayanDSO requested changes

2024-01-15 21:52 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
> +                    if (fields.size > 2 && fields[2].isEmpty()) {
What if I have 10 fields, and the 4th is empty? Or any other combination that is not the second field being empty

2024-01-18 10:14 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
> +                    if (fields.size > 2 && fields[2].isEmpty()) {
Yep. This should match the desktop behavior as much as possible

2024-01-19 18:08 UTC, david-allison commented
CI is failing

2024-01-27 20:42 UTC, BrayanDSO commented
CI still fails

2024-02-17 21:07 UTC, BrayanDSO commented
After discussion in the original issue, it was agreed that this may not be necessary.

Sorry for the time spent, but thanks for the work

2024-02-17 21:07 UTC, closed without merging