audio recorder functionality improvement
ankidroid/Anki-Android pull request #15239
Opened 2024-01-16 23:32 UTC by criticalAY

## Purpose / Description
There were few TODOs I left for myself when I created the previous PRs, so this PR further improves the audio recorder logic and functionality (UX)

- Stop the audio recorder or player in case the user presses back while in multimedia activity or exits the activity. As of now the audio recorder keeps going on and same for the player the audio is played even if the user leaves the screen 
- Same for the reviewer 
- When the user goes to next card the audio recorder UI gets reset to its initial state (was suggested by David)
- When in reviewer the save icon(disk) does not makes sense so replacing it with done icon in case of reviewer 

## How Has This Been Tested?

Tested on Google emulator 
- Pressed back while playing audio
- Pressed back while recording 
- Pressed back while the recorder was paused 
- changed multiple cards 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-01-22 05:56 UTC, criticalAY commented
* Fixes #15300

2024-01-23 00:17 UTC, david-allison requested changes
Main frustration

* I record
* I press the 'tick'
* I expect the recording to be saved

2024-01-23 00:17 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        try {
nit: aim to not leak implementation details in a calling class

move this inside the `audioRecorder` with a reasonable name

2024-01-23 00:17 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +        (context as? Activity)?.let { activity ->
It would likely be better to have something implement `DefaultLifecycleObserver` and handle registration of callbacks

2024-01-23 00:17 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +                    if (activity == context) {
Do you want this to vibate?

2024-01-23 03:39 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +                    if (activity == context) {
It does when stopping the audio recorder otherwise don't want it

2024-01-23 21:33 UTC, david-allison approved these changes
Much nicer UX, thanks so much!

2024-01-26 01:16 UTC, mikehardy approved these changes
the separate commits with refactors all by themselves really help, thank you

2024-01-26 01:38 UTC, merged