Update the Twitter logo
ankidroid/Anki-Android pull request #15255
Opened 2024-01-17 22:54 UTC by criticalAY

## Purpose / Description
Twitter logo updation

## How Has This Been Tested?

Google emualtor 
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/6aeabf53-4080-48d2-92f1-7610a673623d)
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/6c2c91e0-29a3-4a5b-bbb1-f2ef95020fdc)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-01-17 23:11 UTC, david-allison commented on AnkiDroid/src/main/res/drawable/twitter.xml
>  <vector xmlns:android="http://schemas.android.com/apk/res/android"
What's the license?

2024-01-17 23:32 UTC, criticalAY commented on AnkiDroid/src/main/res/drawable/twitter.xml
>  <vector xmlns:android="http://schemas.android.com/apk/res/android"
The OP put it here i.e the source they downloaded it from would have it there, this icon that I updated doesn't need it, it's free and attribution is optional so I skipped it and I made some changes to the logo color and dimensions so it technically belongs to me now 😁, and I don't wish to put attribution here

2024-01-18 00:58 UTC, david-allison commented on AnkiDroid/src/main/res/drawable/twitter.xml
>  <vector xmlns:android="http://schemas.android.com/apk/res/android"
Sorry, I don't understand?

Where did the file come from and what license was it under before you made modifications?

2024-01-18 09:05 UTC, criticalAY commented on AnkiDroid/src/main/res/drawable/twitter.xml
>  <vector xmlns:android="http://schemas.android.com/apk/res/android"
The previous file was downloaded from http://pictogrammers.com where they would have put these licenses, wait I will update it

2024-01-18 09:09 UTC, criticalAY commented
I have made some changes, now it has nothing to do with the previous icon file

2024-01-18 17:21 UTC, david-allison commented on AnkiDroid/src/main/res/drawable/twitter.xml
>  <vector xmlns:android="http://schemas.android.com/apk/res/android"
It's fine (& encouraged) to keep the file in the same location

But the commit says nothing about the source of the current icon, and the copyright header doesn't appear accurate

* The commit message should ideally list where the icon came from
* If you made changes (especially if the file is Apache)
  * You need to list the changes which are made
  * It's likely OK to post a link to the original file, and have your commit contain the changed icon
  * It's less ambiguous to commit the original file, and then commit your changes as a separate commit on top of this

2024-01-19 16:41 UTC, david-allison commented
The icons were added in 

https://github.com/ankidroid/Anki-Android/pull/8519

These were using a "GPL Friendly" license from Pictogrammers

It turns out that the license wasn't GPL-Friendly, specifically regarding brand icons: https://github.com/Templarian/MaterialDesign/issues/5777

and brand icons were removed in V6: https://github.com/Templarian/MaterialDesign/issues/6602

The logical conclusion to me would be to remove the brand icons if they're nonfree

----

Pending a further discussion on Discord

2024-01-20 09:27 UTC, lukstbit commented
> The logical conclusion to me would be to remove the brand icons if they're nonfree

I think this is the way to go, icons would be nice but definitely not worth the hassle.

2024-01-20 19:16 UTC, mikehardy commented
Agreed

Remove the brand icons

2024-01-20 19:22 UTC, david-allison commented
@lukstbit would you like to include removal in https://github.com/ankidroid/Anki-Android/pull/15190, or have someone split it out into a separate PR?

2024-01-20 23:27 UTC, david-allison approved these changes

2024-01-21 07:37 UTC, lukstbit requested changes
Looks good, however I think it could be better by:
- swapping the _Reddit_ and _Mailing List_ so all social networks links are together 
- using the link icon for _Reddit_ as well like it was used for the other social networks

2024-01-21 12:13 UTC, lukstbit approved these changes
Fantastic, thanks!

2024-01-21 12:16 UTC, merged