refactor: convert IntegerDialog to AlertDialog
ankidroid/Anki-Android pull request #15294
Opened 2024-01-21 17:58 UTC by david-allison

## Fixes
* Part of #13315

## How Has This Been Tested?
API 33 emulator: Reposition Dialog dialog

<img width="356" alt="Screenshot 2024-01-21 at 17 56 14" src="https://github.com/ankidroid/Anki-Android/assets/62114487/243b0fd9-f12e-4391-9b86-62b0e86df73f">

<img width="336" alt="Screenshot 2024-01-21 at 17 55 56" src="https://github.com/ankidroid/Anki-Android/assets/62114487/d67a85c9-9e30-4fec-99dd-a422546133fb">

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-01-26 14:22 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
> + * if `true` [callback] is called when [positiveButton] is pressed
method param docs mis-interleaved just a bit

```suggestion
 * @param callback if [waitForPositiveButton], called when [positiveButton] is pressed, otherwise
 * called whenever the text is changed
 * @param maxLength if set, the user may not enter more than the supplied number of digits
 * @param inputType see [EditText.setInputType]
 * @param waitForPositiveButton MaterialDialog compat: if `false` [callback] is called on input
 * if `true` [callback] is called when [positiveButton] is pressed
```

2024-01-26 14:22 UTC, mikehardy approved these changes
Seems fine - one method param doc line needs a tiny fix but assuming that is fixed, lgtm

2024-01-26 14:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
> + * if `true` [callback] is called when [positiveButton] is pressed
> `@param callback if [waitForPositiveButton], called when [positiveButton] is pressed, otherwise` is now a fragment

2024-01-27 09:49 UTC, lukstbit requested changes
Code seems fine, left a couple of notes.

Also, the dialog looks bad right now(along with some of the dialogs in the app), (maybe a regression from #15333 and not from the changes in this PR). 

<details>
  <summary>image1</summary>
  
   
![light](https://github.com/ankidroid/Anki-Android/assets/52494258/c2624a4d-3539-4fc0-a316-f91d0db7b2c7)
  
</details>

<details>
  <summary>image2</summary>

![black_settings](https://github.com/ankidroid/Anki-Android/assets/52494258/a76d0531-5218-46a9-b6fb-f14983997897)
</details>

2024-01-27 09:49 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt
> +            requireArguments().getString("content")?.let { message(text = it) }
We could use use the platform `setMessage()` which can take a null text. I think it would read better.

2024-01-27 09:49 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt
> -                displayKeyboard(getInputField())
This method became unused.

2024-01-27 09:49 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
> +            doOnTextChanged { text, _, _, _ ->
The logic in this callback seems complicated. Wouldn't something like below be better:

```
if (!allowEmpty) {
   // set the initial button status
   positiveButton.isEnabled = !getInputField().text.isNullOrEmpty()

    doOnTextChanged { text, _, _, _ ->
        this@input.positiveButton.isEnabled = !text.isNullOrEmpty()                
    }
}
```

2024-01-27 10:30 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt
> -                displayKeyboard(getInputField())
replaced with `displayKeyboard = true` in the `input()`

2024-01-27 10:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
> +            doOnTextChanged { text, _, _, _ ->
The above suggestion overrides the value if set by `callback`

2024-01-27 10:36 UTC, david-allison commented
Blocked until dialogs look good

2024-01-28 10:06 UTC, lukstbit approved these changes

2024-01-31 15:43 UTC, merged