refactor: remove lifecycle dependency from SoundPlayer
ankidroid/Anki-Android pull request #15296
Opened 2024-01-21 20:09 UTC by BrayanDSO

## Purpose / Description

Different activities may have different lifecycle behaviors depending on how well they deal with configuration changes or if they have a ViewModel or not

So now the SoundPlayer will get its own scope, which means that callers need to remember to close() it, and it can be enabled/disabled with a property

this also makes removes the Robolectric dependency from SoundPlayerTest, which should make things faster

Additionally, it prepares for handling audios in the new previewer

## Approach
In the commits

## How Has This Been Tested?

Unit tests (should be non functional) + opened some cards with audio in 31 emulator

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-01-21 20:35 UTC, david-allison commented
Non-blocking, but one should be rebased once the other is in
* https://github.com/ankidroid/Anki-Android/pull/15254

2024-01-21 20:38 UTC, david-allison requested changes
One change

Looks good: only notes are:

* I'd consider moving this `enable/disable/remove` into a `LifecycleObserver` which references the `SoundPlayer`
* `withCol { xxx(this) } ` is subject to change in the next couple of days, low priority to fixup these calls

2024-01-21 20:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +        soundPlayer.close()
I believe this also needs `isInitialized`

2024-01-21 21:18 UTC, david-allison approved these changes

2024-01-22 01:21 UTC, mikehardy approved these changes
lgtm - will see about a rebase+push to get it in

2024-01-22 01:36 UTC, mikehardy requested changes
ok - with apologies, strings are clear but I'm not 100% sure how to do the alteration to take advantage of context receivers to remove the `this` from inside the withCol's, and am prioritizing merging+releasing things that can go quickly with the time I've got

so this will need a closer look

2024-01-22 01:50 UTC, david-allison approved these changes
This is good to go if there's no conflicts, context receivers are optional cleanup

2024-01-23 07:40 UTC, Mukuljangir372 commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundPlayer.kt
> -        this.playSoundsJob = scope.launch(Dispatchers.IO) {
We've removed Dispatchers.IO. Is there any specific reason for that?

2024-01-23 16:06 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundPlayer.kt
> -        this.playSoundsJob = scope.launch(Dispatchers.IO) {
scope = SupervisorJob() + Dispatchers.IO

2024-01-26 01:27 UTC, mikehardy approved these changes
ok - works for me - code looked okay before just halted on conflicts (resolved now)

2024-01-26 02:16 UTC, merged