enhancement: show copied to clipboard toast for API12 or lower
ankidroid/Anki-Android pull request #15293
Opened 2024-01-21 16:12 UTC by criticalAY

## Purpose / Description
In Android 12L (API level 32) and lower, users might be unsure whether they successfully copied content or what they copied. 

## Fixes
* Fixes  #14992

## How Has This Been Tested?
Tested on Google emulator for API 12 and lower and API 33

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-01-21 16:21 UTC, david-allison requested changes
Needs to go through the call chains of `copyToClipboard` and ensure only one toast is displayed

2024-01-21 16:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
> +    // In Android 12L (API level 32) and lower, users might be unsure whether they successfully copied
This causes a number of places to show multiple toasts

2024-01-21 17:54 UTC, david-allison approved these changes

2024-01-21 18:15 UTC, BrayanDSO commented
There is `copyToClipboardAndShowConfirmation()` already

2024-01-21 18:17 UTC, david-allison commented
Our confirmation is not necessary in later APIs, we don't want to show it twice.

2024-01-21 18:32 UTC, BrayanDSO commented
My suggestion is to join both methods and remove the `showTextCopiedMessage: Boolean = false` conditional, so the message is always shown in older APIs and not duplicated in newer APIs

2024-02-02 04:18 UTC, david-allison requested changes
Copied from a series of Discord messages:

 want to walk through things just to be sure. Tell me where I'm going wrong

There's 2 conditions:

1. Did the copy succeed?
2. Do we need to show a notification (or the negation: did Android show a notification due to a succesful copy)

`1 && 2` -> do nothing, the notification was shown by the system
`1 && !2` -> the system didn't show a notification, show one
`!1 && (2 || !2)` -> if the copy didn't succeed, we need to show a notification

Then the final step is 'how': using a toast or a snackbar

----

Code dump, then let me explain:

```kotlin
/**
 * Copies the provided [text] to the clipboard (truncated if necessary),
 * and show either a snackbar, if possible, or a toast in case of API>32,
 * with the success or failure message.
 */
fun Context.copyToClipboard(
    text: String,
    @StringRes successMessageId: Int,
    @StringRes failureMessageId: Int
) {
    val copied = copyTextToClipboard(text)
    // in Android T and above, the system is guaranteed to show a message on a successful copy
    // so we don't need to do anything
    val doesNotNeedToShowMessage = copied && Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU

    if (doesNotNeedToShowMessage) {
        Timber.v("successful clipboard copy & system informed user of copy")
        return
    }

    val confirmationMessage = if (copied) successMessageId else failureMessageId

    // prefer a snackbar over a toast
    if (this is Activity && canProperlyShowSnackbars()) {
        showSnackbar(confirmationMessage)
    } else {
        showThemedToast(this, confirmationMessage,  shortLength = true)
    }
}

private fun Context.copyTextToClipboard(text: String): Boolean {
    val clipboardManager = this.getSystemService(Activity.CLIPBOARD_SERVICE) as? ClipboardManager
    if (clipboardManager == null) {
        Timber.w("Failed to obtain ClipboardManager")
        return false
    }

    return try {
        clipboardManager.setPrimaryClip(
            ClipData.newPlainText(
                "${VersionUtils.appName} v${VersionUtils.pkgVersionName}",
                text
            )
        )
        true
    } catch (e: Exception) {
        Timber.e("Failed to copy text to clipboard", e)
        false
    }
}
```

Firstly, there was a lot of code which effectively boiled down to setting `copied` to either `true` or `false`
It made the code much more simple to use `Refactor ... Function` to extract the method
That allows for early returns inside the `if` for example, and `return try`


![image](https://github.com/ankidroid/Anki-Android/assets/62114487/1fd9e053-5f9e-49c1-8eda-88fc7fdc2bda)

After this, my boolean table above takes in 4 inputs, but returns two outputs:
do we want to show a message, or not

Because we only have two outputs, and 1 is 'do nothing', return early on the 'do nothing' case

Now... we want to show a message. Figure out what the message is, then figure out how to show it, preferring a Snackbar
and we're done with the refactor

2024-02-02 04:24 UTC, david-allison requested changes
Additional review comments which weren't covered from my large message

Finally: the commit message and maybe a comment should make it clear that `>= T` (or `> S_V2`) is where the system clipboard notification is added

Ideally with a link to reference the Android changelog

2024-02-02 04:24 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
> +            Timber.e("Failed to copy text to clipboard", e)
The `e` parameter comes first in Timber

Use `Timber.w` for non-fatal errors, not `Timber.e`


```suggestion
            Timber.w(e, "Failed to copy text to clipboard")
```

2024-02-02 04:24 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
> + * with the success or failure message.
rephrase this based on what the method does:

* copies the text to the clipboard
* shows a message to the user if the system does not already show a 'copied to clipboard' message
  * This happens for failure or success
* `@param`s are a nice to have here

2024-02-02 20:06 UTC, david-allison approved these changes
Looks great, thanks!

2024-02-02 23:59 UTC, BrayanDSO requested changes

2024-02-02 23:59 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
> + * @param successMessageId message that needs to be shown after successfully coping the text
typo: coping

2024-02-02 23:59 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
> +private fun Context.copyTextToClipboard(text: String): Boolean {
why keep two methods for copying stuff to the clipboard?

2024-02-02 23:59 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
> + * @param text the text that needs to be copied
Add a blank like between the parameters and the text

2024-02-02 23:59 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
> + * Copies the provided [text] to the clipboard (truncated if necessary),
What are the exact situations that the text is going to be truncated? How many chars?

2024-02-02 23:59 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/viewmodel/TtsVoicesViewModel.kt
> +            failureMessageId = R.string.about_ankidroid_error_copy_debug_info
Can't these be default values for the function parameters? This seems repetitive and verbose

2024-02-03 00:00 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
> +            text = (intent.getStringExtra(CLIPBOARD_INTENT_EXTRA_DATA)!!),
Is it possible for `!!` to crash?  If not, add a comment so nobody has to think about it. If yes, handle it.

2024-02-03 07:38 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
> +private fun Context.copyTextToClipboard(text: String): Boolean {
Read David's comment above

2024-02-03 07:44 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
> + * Copies the provided [text] to the clipboard (truncated if necessary),
When the text we are copying has more than 5 lines, no exact chars are there

2024-02-03 07:55 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/viewmodel/TtsVoicesViewModel.kt
> +            failureMessageId = R.string.about_ankidroid_error_copy_debug_info
Success message is fine but not the failure message, just noticed one more mistake I used the debug failure string in TTS

2024-02-04 01:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
> +private fun Context.copyTextToClipboard(text: String): Boolean {
To elaborate, the code beforehand was:

https://github.com/ankidroid/Anki-Android/blob/c63210597cd6dbd281ed017aa5a46a6f45fc7f60/AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt#L76-L100

Too much of the method was obtaining the value of `copied`, and this obscured the additional logic of displaying feedback to the user

2024-02-04 10:24 UTC, BrayanDSO requested changes

2024-02-04 10:24 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
> + * Copies the provided [text] to the clipboard (truncated if necessary, >5 lines),
Where does the source stating the >5 lines restriction come from? I believe that the debug info is way bigger than that

2024-02-04 10:24 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
> +private fun Context.copyTextToClipboard(text: String): Boolean {
So please add a javadoc to the method explaining the difference between the two

2024-02-04 10:24 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="failed_to_copy_voice">Failed to copy voice</string>
I suggest creating a generic string of failing to copy to the clipboard so we don't increase translators' job for strings that are rarely going to be reached

2024-02-04 10:30 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
> + * Copies the provided [text] to the clipboard (truncated if necessary, >5 lines),
It is not officially on Android doc, the link is provided in the commit message but they have a preview of the copy paste and if you try copying the text in valid APIs the number of lines is 5 after that it's.
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/38121758-5f95-4fce-823d-a2272a54a18f)

2024-02-15 16:23 UTC, mikehardy approved these changes
LGTM - I believe you addressed Brayan's comments with exception of strings key remaining a little non-generic

2024-02-15 16:23 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="failed_to_copy_voice">Failed to copy</string>
This is no longer voice-related, altering key slightly

```suggestion
    <string name="failed_to_copy">Failed to copy</string>
```

2024-02-15 16:36 UTC, mikehardy commented
Sorry @criticalAY I just obliterated your change there with a force-push, didn't see you were also working in there but I was operating on the principle of "you break it you buy it" since I waded in and changed the key name then (ridiculously...) forgot to change the key name ref in the code

cleaned up the conflict locally at the same time - I imagine you did both of those as well :-)

Anyway, I expect this will go green now and be ready

2024-02-15 17:38 UTC, merged