fix some bugs in the new previewer + some refactors
ankidroid/Anki-Android pull request #15297
Opened 2024-01-21 20:42 UTC by BrayanDSO

## Purpose / Description

I'm sorry if there were too much churn of changes in the new previewer instead of reviewing just one final piece, but I was trying to do things in a incremental way and sometimes I get new ideas on how to organize stuff (and I likely will refactor more stuff when I generify the code to be reused in the CardTemplatePreviewer rewrite)

The last task is handling audios, which I already finished locally, so it shouldn't take long before it can be made the default one

## Approach
In the commits

## How Has This Been Tested?

Android 31:

[teste.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/91d89718-6acf-4c62-a237-637734bd116a)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-01-23 07:39 UTC, Mukuljangir372 commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
> +        /* ************************************* Menu items ************************************* */
Do we need this comment?

2024-01-23 16:07 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
> +        /* ************************************* Menu items ************************************* */
As I said in a commit, `debatable, but I think this may help organize stuff`. I'm fine with keeping or removing it, just need a consensus

2024-01-23 21:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
> +        /* ************************************* Menu items ************************************* */
keep

2024-01-24 00:47 UTC, dae commented
Re the change to Dispatchers.IO: I'd argue for a different approach. Currently, the code is inconsistent. We use .Default for launchCatching, but EmptyCoroutineContext for launchCatchingTask (which I gather means the coroutine remains on the thread it starts on). It's surprising to have the Task variant behave differently to the non-task variant.

And for .IO vs Empty: personally, I think the latter makes more sense. A not-uncommon idiom is to launch a background task that performs some I/O with the collection and then does some follow-up UI work, i.e. `launchCatchingTask { withCol { ... }; uiStuff() }`. With an I/O context, withCol still needs to be called, and then you need to wrap uiStuff in a separate context so it runs on main, which creates more work.

2024-01-24 19:00 UTC, BrayanDSO commented
> A not-uncommon idiom is to launch a background task that performs some I/O with the collection and then does some follow-up UI work

ViewModel instances aren't supposed to do any UI work, so that doesn't apply here. 

`Empty` would lead to run things in the Main thread by default, so someone would need to add a `(Dispatchers.IO)` most (probably all) of the times, which creates more work.

2024-01-25 01:38 UTC, dae commented
Re view models, fair enough, but I'd suggest you make the difference from launch/launchCatchingTask obvious in the name, e.g. calling it launchCatchingIo instead of launchCatching. It might be also worth renaming launchCatchingTask -> launchCatching at the same time, since 'task' is not really adding anything.

2024-01-26 08:43 UTC, Mukuljangir372 commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
> +        /* ************************************* Menu items ************************************* */
It invokes bad practises as comments should not be used in such cases. In terms of organise the code, We can extract it in a function with meaningful name. It would be enough and clean way for such cases.

2024-01-26 14:24 UTC, mikehardy commented
I like the idea of the name refactors dae proposes - might be a reasonable time to do it right now as things aren't crazy in-tree at the moment with regard to volume of in-flight PRs

2024-02-01 20:07 UTC, BrayanDSO commented
the launchCatching rename will generate some conflicts, so I'll only solve them after this is reviewed

2024-02-02 20:17 UTC, david-allison requested changes
Primarily the user privacy change

2024-02-02 20:17 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +import android.content.Intent
(non-blocking); an aim at some point in the future would be to remove all `android` references from the ViewModel

2024-02-02 20:17 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
> +                    Timber.w("Could not open url: %s", request.url)
concern: user privacy + logging tokens etc..

2024-02-02 20:17 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
> +                    setBacksideOnlyButtonIcon(menu, isBacksideOnly)
nit: rename to `BackSide` `Backside` is more commonly used for "buttocks"

2024-02-02 20:17 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +                currentIndex.update { it + 1 }
How is Out of Bounds handled here?

2024-02-02 20:17 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +    context: CoroutineContext = EmptyCoroutineContext,
This commit is named 'refactor', but has a functional change

2024-02-02 23:27 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +import android.content.Intent
Used for NoteEditorDestination only. Extracting it to another file should make it clearer

2024-02-02 23:29 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
> +                currentIndex.update { it + 1 }
The next button is disabled if it reaches the last index.

```kotlin
val isNextButtonEnabled = combine(currentIndex, showingAnswer) { index, showingAnswer ->
        index != selectedCardIds.lastIndex || !showingAnswer
    }
```

2024-02-03 00:11 UTC, BrayanDSO commented
removed the launchCatchingTask rename commit. That can be pushed in any other day or PR

2024-02-03 01:16 UTC, david-allison approved these changes

2024-02-07 02:26 UTC, mikehardy approved these changes
All look good to me - sorry the attempt to rename things caused conflict trauma, hopefully that's easy as a single commit done in a separate PR we can just push through

This should be good to go but is marked squash so needs the merge queue to clear out, has 2 items at the moment

2024-02-07 03:01 UTC, merged

2024-02-07 03:02 UTC, mikehardy commented
pulled it locally rebased it to current main and made sure it was good 👍