Enhancement: added cancel sync button in sync progress dialog
ankidroid/Anki-Android pull request #15310
Opened 2024-01-22 18:38 UTC by criticalAY

## Purpose / Description
Add cancel button in sync progress dialog 

## Fixes
* Fixes #12613

## How Has This Been Tested?
Oneplus nord ce

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-01-22 18:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +            setButton(DialogInterface.BUTTON_NEGATIVE, context.getString(R.string.cancel_sync)) { _, _ ->
This isn't generic enough

`@StringRes manualCancelButton: Int = null` would probably be what we're looking for

The act of passing in the resource as non-null would act as `showCancellable` here

2024-01-22 18:43 UTC, david-allison requested changes
One issue with the  field not being generic enough

I would love for the back button to be handled, but we could leave this as a TODO

2024-01-22 19:20 UTC, david-allison approved these changes
One nitpick, requested updated video

2024-01-22 19:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +    manualCancelButton: Int? = null,
`@StringRes`?

2024-01-22 19:20 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +    manualCancelButton: Int? = null,
oops sorry!

2024-01-22 19:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +    manualCancelButton: Int? = null,
Never a worry!

2024-01-22 19:26 UTC, criticalAY commented
Updated test video :
https://github.com/ankidroid/Anki-Android/assets/48384865/896dcef3-78df-4040-967c-09392630a76f

2024-01-22 19:40 UTC, david-allison approved these changes
Only question is whether 'cancel' should be blue as that feels inconsistent

That's a nitpick of a nitpick, let's get this in, one step closer to 2.17!

2024-01-22 19:41 UTC, criticalAY commented
> Only question is whether 'cancel' should be blue as that feels inconsistent

Can make it blue won't be an issue just need to change one word

2024-01-22 20:00 UTC, criticalAY commented
Updated the color 
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/3b769ab2-b8a5-4fc4-b0cf-fbbc8aa5f34e)

2024-01-22 21:34 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/styles.xml
> +        <item name="android:textColor">@color/material_light_blue_500</item>
Plain theme doesn't use blue. Dialogs use `?attr/colorPrimary` IIRC

2024-01-24 13:32 UTC, mikehardy commented
Hoping to merge this one today - two notes with regards to strings:
- strings are currently clear after merge of #15326 
- strings workflow just switched from node v18 to v20 in #15327 and this will be first run with that, so carefully watch the strings workflow

2024-01-24 15:14 UTC, merged