Removed the Material Dialog Box and Added Alert Box to Backup Prompt Dialog
ankidroid/Anki-Android pull request #15334
Opened 2024-01-26 04:10 UTC by neeldoshii

## Fixes
* Fixes #13315  

## Approach
Replaces usages of MaterialDialog with AlertDialog For Backup Prompt Dialog.

## Testing Instructions
1. The backup prompt usually pops once in a 2 week of span. 
2. You can programatically change it and test to check the alert box from code

Change this code 
* Original Code
```
 private fun timeToShowDialogAgain(): Boolean = 
        !dialogPermanentlyDismissed && nextTimeToShowDialog <= TimeManager.time.intTimeMS()
```
* Change this to return  this function true so it will pop up every time so you can test the dialog box (Note only for testing)
```
    private fun timeToShowDialogAgain(): Boolean = true
```
3. You will get the alert box dialog.
## How Has This Been Tested?

This has been tested on physical device(Realme 3i) and on emulator (Google Pixel 7)

Screenshots 

| Before | After |
|--------|-------|
| ![before](https://github.com/ankidroid/Anki-Android/assets/60827173/d48940d6-f184-410c-b102-b71eb0352b05) | ![After image](https://github.com/ankidroid/Anki-Android/assets/60827173/ab969382-970b-41d3-b71a-0cab259b0dde) |

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-01-26 14:19 UTC, david-allison requested changes
* The screenshot shows that both options are disabled, could you either use another theme if this is a global theme change, or fix the issue

2024-01-26 14:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
> +            .setTitle(R.string.backup_your_collection)
Could you look through https://github.com/ankidroid/Anki-Android/pull/15148/files to use things such as `message()`. This reduces code churn and makes it easier to review and ensure that things are correct.

2024-01-26 15:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
> +            .setTitle(R.string.backup_your_collection)
Extension functions have been added, such as `message()`:

https://github.com/ankidroid/Anki-Android/blob/da41ac1cb1db39847fe2dc3b870143192873af65/AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt#L61-L70

These make it easier to review the changes so we can be sure they're correct

From my testing, the code almost compiles after the following change to `AlertDialog.Builder`. This is much easier to review

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt	(revision 7d284e1c3de83cb723eea618736d14cd77dc708b)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt	(date 1706284685226)
@@ -21,10 +21,8 @@
 import androidx.annotation.StringRes
 import androidx.appcompat.app.AlertDialog
 import androidx.core.content.edit
-import com.afollestad.materialdialogs.MaterialDialog
 import com.afollestad.materialdialogs.WhichButton
 import com.afollestad.materialdialogs.actions.setActionButtonEnabled
-import com.afollestad.materialdialogs.checkbox.checkBoxPrompt
 import com.ichi2.anki.*
 import com.ichi2.anki.CollectionManager.withCol
 import com.ichi2.anki.preferences.sharedPrefs
@@ -48,7 +46,7 @@
  */
 class BackupPromptDialog private constructor(private val windowContext: Context) {
 
-    private lateinit var materialDialog: MaterialDialog
+    private lateinit var materialDialog: AlertDialog
 
     /**
      * After 2 dismissals, allow ignoring
@@ -113,8 +111,8 @@
     }
 
     private fun build(isLoggedIn: Boolean, performBackup: () -> Unit) {
-        this.materialDialog = MaterialDialog(windowContext).apply {
-            icon(if (isLoggedIn) R.drawable.ic_baseline_backup_24 else R.drawable.ic_backup_restore)
+        this.materialDialog = AlertDialog.Builder(windowContext).apply {
+            setIcon(if (isLoggedIn) R.drawable.ic_baseline_backup_24 else R.drawable.ic_backup_restore)
             title(R.string.backup_your_collection)
             message(R.string.backup_collection_message)
             positiveButton(if (isLoggedIn) R.string.button_sync else R.string.button_backup) {
@@ -131,7 +129,7 @@
             }
             negativeButton(R.string.button_backup_later) { onDismiss() }
             cancelable(false)
-        }
+        }.create()
     }
 
     companion object {

```

2024-01-27 09:53 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
> +            .setTitle(R.string.backup_your_collection)
Gotcha! In my current commit I have made the usage of AlertDialog Utils from AlertDialogFacade. 

* Removed the Layout which I was attaching to the alertDialog for checkbox and now making usage of AlertDialogFacade to show checkbox.

2024-01-27 09:54 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
> +            .setTitle(R.string.backup_your_collection)
> The screenshot shows that both options are disabled, could you either use another theme if this is a global theme change, or fix the issue

Working on this on my next commit.

2024-01-27 14:18 UTC, neeldoshii commented
> The screenshot shows that both options are disabled, could you either use another theme if this is a global theme change, or fix the issue

While I was working on this, I found out that on most of the dialog boxes we are having same button text color for (positive and negative). On plain theme its just looks as the text is disabled. 

Well, I come from a pre UI/UX background I feel for color's we should be having a primary color and secondary color for dialogs.

### Reason:-
<img src="https://github.com/ankidroid/Anki-Android/assets/60827173/78874117-f8c9-413b-b98e-3fadbae01f6c" width="50%" height="50%">

Here using two different colors for buttons in a dialog box helps users make quick, intuitive decisions: a distinct, bold color for the "Delete" button draws attention to the primary action, like confirming the deletion of a note, while a more subdued color for the "Cancel" button indicates a less prominent, secondary action, preventing accidental deletions and improving overall user experience.

### Currently What we have
![Desktop - 2 (1)](https://github.com/ankidroid/Anki-Android/assets/60827173/d5a0a2b0-76a1-47d3-8362-277e5a6fa347)

### Proposed Change 
![Desktop - 1](https://github.com/ankidroid/Anki-Android/assets/60827173/b66a65a1-7cee-4cb1-8aab-daed2ad39c83)


The issue here is that I am not sure at how many dialog we have this type and changing one by one to all will be a heavy workaround. I am not sure we should be having this all over our app or not. As we might lose consistency in our app if we have it on some section and not on some sections. 

Open for suggestions.

Thanks

2024-01-27 16:31 UTC, BrayanDSO commented
keep using the same color for dialog options

2024-01-27 19:31 UTC, david-allison requested changes
When you're refactoring, the aim is to perform as little work as possible to make the change. This makes it obvious to reviewers that the behaviour remains

* Functional aspects should not be changed
* A minimal subset of the code should be changed
* If functional aspects are changed, they should be done in a separate commit

This change is both unnecessarily hard to understand (given that I provided a patch which was 90% there as an example). It also introduces a bug: the line `setActionButtonEnabled(WhichButton.POSITIVE, !checked)` was removed. The intention of this is to ensure a user knows they're permanently dismissing the dialog if they click "Don't show again"

In addition, this adds `isCheckedDefault = false`. False is the default of this parameter, and removes log statements

<img width="363" alt="Screenshot 2024-01-27 at 19 17 52" src="https://github.com/ankidroid/Anki-Android/assets/62114487/3ed732da-1d92-4c82-9fc2-b21f3059bcac">

Please:

* Start again on this branch, using `git reset`
* Go back to my patch: https://github.com/ankidroid/Anki-Android/pull/15334#discussion_r1467832428
* Copy it to clipboard, and apply it from the clipboard using Android Studio
* Fix the line: `setActionButtonEnabled`
* Force push

I've worked through this, and it should result in ~10 lines of code changed

2024-01-27 19:33 UTC, david-allison commented
RE: Dialog button colors (primary/secondary)

That goes against material dialog guidelines: https://m3.material.io/components/dialogs/overview

2024-01-29 21:07 UTC, david-allison reviewed
Few questions, change looks good

2024-01-29 21:07 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
> +            iconAttr(if (isLoggedIn) R.drawable.ic_baseline_backup_24 else R.drawable.ic_backup_restore)
I thought it would be `setIcon` here. Did that not work?

2024-01-29 21:07 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
> +                    Timber.tag("Checking").d("Checkbox")
Aim to split out any non-refactoring changes from the commit

We don't use `.tag` in this repo (besides AnkiDroidApp)

2024-01-29 21:07 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
> +        alertDialog = builder.create()
Did you apply the patch I provided using Android Studio?

I used something along the lines of `this.alertDialog = AlertDialog.Builder().apply { ... }.create()`, which feels cleaner than this

2024-01-30 10:16 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
> +                    Timber.tag("Checking").d("Checkbox")
The whole log `Timber.tag("Checking").d("Checkbox")` is redundant I created for debugging bymistakely committed so I am removing.

`Timber.d("Don't show again checked: %b", checked)` This does the work for logs.

2024-01-30 10:17 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
> +            iconAttr(if (isLoggedIn) R.drawable.ic_baseline_backup_24 else R.drawable.ic_backup_restore)
Both of them works changing it to setIcon since its used everywhere to maintain consistency.

2024-01-30 13:44 UTC, david-allison approved these changes
Perfect, thanks!

2024-01-31 12:24 UTC, mikehardy approved these changes
LGTM - thank you - since the commit chain isn't rebase-clean needs a squash commit, will need to wait for maintainer merge after merge queue drains so as not to invalidate queue - check queue here https://github.com/ankidroid/Anki-Android/queue/main

2024-01-31 12:44 UTC, mikehardy commented
Unrelated flaky CI. emulator test failed on fetching standard actions, looks like github-internal network error.

Unit tests were some current flakes that aren't marked Flaky yet

```
ReviewerTest > testLrnQueueAfterUndo FAILED
    java.lang.AssertionError: 
    Expected: "2"
         but: was "1"
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.test.TestDispatcher.processEvent$kotlinx_coroutines_test(TestDispatcher.kt:28)
        at kotlinx.coroutines.test.TestCoroutineScheduler.tryRunNextTaskUnless$kotlinx_coroutines_test(TestCoroutineScheduler.kt:103)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$workRunner$1.invokeSuspend(TestBuilders.kt:320)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at kotlinx.coroutines.test.TestBuildersJvmKt.createTestResult(TestBuildersJvm.kt:13)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:308)
        at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:166)
        at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
        at com.ichi2.testutils.TestClass.runTest(TestClass.kt:218)
        at com.ichi2.testutils.TestClass.runTest$default(TestClass.kt:[209](https://github.com/ankidroid/Anki-Android/actions/runs/7725964998/job/21061296143?pr=15334#step:8:210))
        at com.ichi2.anki.ReviewerTest.testMultipleCards(ReviewerTest.kt:121)
```

2024-01-31 14:05 UTC, merged