Fix: API30 tts `availableVoices` to return empty set to avoid crash
ankidroid/Anki-Android pull request #15366
Opened 2024-01-30 19:29 UTC by criticalAY

## Purpose / Description
As I mentioned this in the issue it happens only for API30 and no other API, I have tested it for other API i.e. 24 and 33 and its works fine. It might be related to emulator only as it was reported under emulator category but still fixing it so that it doesn't break in API30 emualtor.

## Fixes
* #15364

## How Has This Been Tested?
Tested on API30 (emulator) / API24 / API 33(physical and emulator both)

## Learning (optional, can help others)
https://issuetracker.google.com/issues/199606758

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-01-30 21:12 UTC, david-allison requested changes
The issue is that `availableVoices` isn't set, as I listed in the issue.

It should be fixed so `availableVoices` is set before `availableLocaleData` in the two listed error cases

* https://github.com/ankidroid/Anki-Android/issues/15364#issuecomment-1917451837

2024-01-30 21:35 UTC, criticalAY commented
It is initialized in a physical device this issue is only with the emulator so, there are no tts in the emulator itself
I tested it on a physical device with API30 and it works fine as I suspect that issue is under emulator category so that explains it, in case of emulator we can keep it empty?

2024-01-30 21:48 UTC, criticalAY commented
API 30
Emulator : 
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/c4b1aa24-01b9-43a8-a775-90486650b1c6)

Device:
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/1aa995bf-4869-4776-abb0-5864b61101cb)

```
AnkiDroid Version = 2.17alpha17-debug (c833bbe960fe9ba9efd4dc8269ba03e3a867124c)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = amazon

Manufacturer = Xiaomi

Model = M2006C3LI

Hardware = mt6762

Webview User Agent = Mozilla/5.0 (Linux; Android 11; M2006C3LI Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.230 Mobile Safari/537.36

ACRA UUID = 22c78714-8f76-4833-b0e2-353f467174d8

Crash Reports Enabled = false
```

2024-01-31 01:36 UTC, david-allison requested changes
1. This doesn't handle other places in the file with the condition
2. This looks like it breaks TTS for all providers. The condition should be false on first run, and `launchBuildLocalesJob` will never be called
3. This should be fixed when `availableVoices` is set

As stated in the issue, we should be doing:

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt b/AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt	(revision c833bbe960fe9ba9efd4dc8269ba03e3a867124c)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt	(date 1706664810965)
@@ -109,10 +109,6 @@
      * Returns the list of available voices for use in TTS
      */
     suspend fun allTtsVoices(): Set<AndroidTtsVoice> {
-        // Happens only in API30: https://issuetracker.google.com/issues/199606758
-        if (!this::availableVoices.isInitialized) {
-            return emptySet()
-        }
         if (this::availableLocaleData.isInitialized) {
             return this.availableVoices
         }
@@ -153,6 +149,7 @@
         val tts = createTts()
         if (tts == null) {
             Timber.e("Unable to build list of TTS Voices")
+            availableVoices = emptySet()
             availableLocaleData = emptyList()
             return
         }
@@ -166,6 +163,7 @@
             availableVoices = tts.voices.map { it.toTtsVoice(ttsEngine) }.toSet()
             availableLocaleData = tts.availableLanguages.map { CompatHelper.compat.normalize(it) }
         } catch (e: Exception) {
+            availableVoices = emptySet()
             availableLocaleData = emptyList()
         } finally {
             tts.shutdown()
```

2024-01-31 01:58 UTC, criticalAY commented
Ohhh, I already tried the above solution must have a patch for it, but thankyou so much

2024-01-31 02:44 UTC, david-allison approved these changes

2024-01-31 11:46 UTC, mikehardy approved these changes
🚂

2024-01-31 11:47 UTC, merged