Removed the Material Dialog Box and Added Alert Box from CardBrowserMySearchesDialog
ankidroid/Anki-Android pull request #15397
Opened 2024-02-03 22:31 UTC by neeldoshii

## Fixes
* Related #13315  

## Approach
Replaces usages of Deprecated MaterialDialog and adds the Native AlertDialog For Deck Picker Analytics.

## Images
![Alert Dialog](https://github.com/ankidroid/Anki-Android/assets/60827173/af86195b-a41c-42e7-b15a-d9b5ac31acb7)
![Material Dialog](https://github.com/ankidroid/Anki-Android/assets/60827173/593d51e0-098d-4cff-a983-ee42ebdc5130)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [X] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-02-07 01:51 UTC, david-allison submitted a review, later dismissed
Split out the 'easy' dialog into another PR

Fixing the second dialog will take longer. Padding definitely needs to be fixed

2024-02-07 09:45 UTC, neeldoshii commented
> Split out the 'easy' dialog into another PR
> 
> Fixing the second dialog will take longer. Padding definitely needs to be fixed

Also what about the divider decoration?

2024-02-07 11:51 UTC, neeldoshii commented
@david-allison I have not tested it yet but I am thinking what if I create an extension function and apply it so we would be having same ui as before (will also have decoration divider, padding).
This would make the code follow DRY approach for later.

This is what I came up with it for extnesion method.

```
/**
 * Adds a RecyclerView with a custom adapter and decoration to the AlertDialog.
 * @param adapter The adapter for the RecyclerView.
 * @param context The context used to access resources and LayoutInflater.
 * @param paddingTop The top padding in dp.
 * @param paddingBottom The bottom padding in dp.
 * @param paddingLeft The left padding in dp.
 * @param paddingRight The right padding in dp.
 */
fun AlertDialog.Builder.customListAdapterWithDecoration(adapter: RecyclerView.Adapter<*>, context: Context, paddingTop: Int = 0, paddingBottom: Int = 0, paddingLeft: Int = 0, paddingRight: Int = 0) {
    val recyclerView = LayoutInflater.from(context).inflate(R.layout.dialog_generic_recycler_view, null, false) as RecyclerView
    recyclerView.adapter = adapter
    recyclerView.layoutManager = LinearLayoutManager(context)
    val dividerItemDecoration = DividerItemDecoration(recyclerView.context, LinearLayoutManager.VERTICAL)
    recyclerView.addItemDecoration(dividerItemDecoration)
    recyclerView.setPadding(paddingLeft,paddingTop,paddingRight,paddingBottom)
    this.setView(recyclerView)
}
```

2024-02-07 15:01 UTC, david-allison commented
The vertical padding on that screenshot looks off

Try adding 8-12dp top & bottom and see if it looks good

2024-02-07 16:02 UTC, neeldoshii commented
> The vertical padding on that screenshot looks off, and the touch targets look too small
> 
> Try adding 8-12dp top & bottom and see if it looks good

<img src="https://github.com/ankidroid/Anki-Android/assets/60827173/66dd20d6-bea3-47cd-b57d-f1d4698e7278" alt="image" width="40%" height="40%">

I simplified the layout instead of nested layout(relative and linear, increasing size of imageview was not making the textview vertical center aligned properly) I made it simplified and clean.

few things can be again added as per accessibility suggestion by Android Studio 

> This item may not have a label readable by screen readers.

Adding a content description would fix this. I am not sure which string to add for it and not sure from localization. I am not adding it also its of low priority. Just adding it for reference of issue.

2024-02-09 01:36 UTC, david-allison approved these changes
It still feels like the padding is too large on the right hand side

Implementer's choice, it looks better than the previous screen at this point

Thanks!!!

2024-02-09 01:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +            AlertDialog.Builder(requireActivity()).show {
in future, aim to keep the style consistent when you're doing a refactoring.

The aim is to reduce the number of changed lines so we can focus on the difference

2024-02-10 08:12 UTC, lukstbit requested changes

2024-02-10 08:12 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +        return alertDialog.show()
This is not ok and it introduces a bug which you can see when trying to save a search(there's an overlay(empty dialog) over the dialog). You call show() here to return a dialog for the DialogFragment but above you create a **new** dialog and call show() on it ending up with two dialogs.

You need to use the _alertDialog_(please rename it back to the original name dialog) property and return directly from the if/else clause.

2024-02-26 05:41 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +        return alertDialog.show()
I addressed this issue in description. The dialog is being called twice. 
I am unable to return dialog with show I tried a lot. 

Can any of the maintainers/contributors help me to resolve this. Thank You

2024-02-26 06:51 UTC, lukstbit commented
@neeldoshii Check the patch below for specific changes. Note that I didn't visually verified it.

```patch
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
index b068b3d804..78bd03204c 100644
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
@@ -5,20 +5,17 @@ import android.annotation.SuppressLint
 import android.app.Dialog
 import android.os.Bundle
 import androidx.appcompat.app.AlertDialog
-import androidx.recyclerview.widget.DividerItemDecoration
-import androidx.recyclerview.widget.LinearLayoutManager
-import com.afollestad.materialdialogs.MaterialDialog
-import com.afollestad.materialdialogs.input.input
-import com.afollestad.materialdialogs.list.customListAdapter
-import com.afollestad.materialdialogs.list.getRecyclerView
 import com.ichi2.anki.R
 import com.ichi2.anki.analytics.AnalyticsDialogFragment
 import com.ichi2.compat.CompatHelper.Companion.getSerializableCompat
 import com.ichi2.ui.ButtonItemAdapter
+import com.ichi2.utils.createAndApply
+import com.ichi2.utils.input
 import com.ichi2.utils.message
 import com.ichi2.utils.negativeButton
 import com.ichi2.utils.positiveButton
 import com.ichi2.utils.show
+import com.ichi2.utils.title
 import timber.log.Timber
 
 // TODO: Add different classes for the two different dialogs
@@ -37,7 +34,7 @@ class CardBrowserMySearchesDialog : AnalyticsDialogFragment() {
     @SuppressLint("CheckResult")
     override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
         super.onCreate(savedInstanceState)
-        val dialog = MaterialDialog(requireActivity())
+        val dialog = AlertDialog.Builder(requireActivity())
         val type = requireArguments().getInt("type")
         if (type == CARD_BROWSER_MY_SEARCHES_TYPE_LIST) {
             savedFilters = requireArguments().getSerializableCompat("savedFilters")
@@ -51,7 +48,7 @@ class CardBrowserMySearchesDialog : AnalyticsDialogFragment() {
                 itemCallback = { searchName ->
                     Timber.d("item clicked: %s", searchName)
                     mySearchesDialogListener!!.onSelection(searchName)
-                    dialog.dismiss()
+                    dismiss()
                 },
                 buttonCallback = { searchName ->
                     Timber.d("button clicked: %s", searchName)
@@ -60,27 +57,24 @@ class CardBrowserMySearchesDialog : AnalyticsDialogFragment() {
             ).apply {
                 notifyAdapterDataSetChanged() // so the values are sorted.
                 dialog.title(text = resources.getString(R.string.card_browser_list_my_searches_title))
-                    .customListAdapter(this, null)
+                    .customListAdapterWithDecoration(this, requireActivity())
             }
         } else if (type == CARD_BROWSER_MY_SEARCHES_TYPE_SAVE) {
             val currentSearchTerms = requireArguments().getString("currentSearchTerms")
-            dialog.title(text = getString(R.string.card_browser_list_my_searches_save))
-                .positiveButton(android.R.string.ok)
-                .negativeButton(R.string.dialog_cancel)
-                .input(hintRes = R.string.card_browser_list_my_searches_new_name) { _: MaterialDialog?, text: CharSequence ->
-                    Timber.d("Saving search with title/terms: %s/%s", text, currentSearchTerms)
-                    mySearchesDialogListener!!.onSaveSearch(text.toString(), currentSearchTerms)
+            return dialog.show {
+                    title(text = getString(R.string.card_browser_list_my_searches_save))
+                    positiveButton(android.R.string.ok)
+                    negativeButton(R.string.dialog_cancel)
+                    setView(R.layout.dialog_generic_text_input)
+                }.apply {
+                    input(hint = getString(R.string.card_browser_list_my_searches_new_name)) { dialog, text ->
+                            Timber.d("Saving search with title/terms: %s/%s", text, currentSearchTerms)
+                            mySearchesDialogListener!!.onSaveSearch(text.toString(), currentSearchTerms)
+                            dialog.dismiss()
+                    }
                 }
         }
-        runCatching { dialog.getRecyclerView() }.onSuccess { recyclerView ->
-            val layoutManager = recyclerView.layoutManager as LinearLayoutManager
-            val dividerItemDecoration = DividerItemDecoration(recyclerView.context, layoutManager.orientation)
-            val scale = resources.displayMetrics.density
-            val dpAsPixels = (5 * scale + 0.5f).toInt()
-            dialog.view.setPadding(dpAsPixels, 0, dpAsPixels, dpAsPixels)
-            recyclerView.addItemDecoration(dividerItemDecoration)
-        }
-        return dialog
+        return dialog.create()
     }
 
     private fun removeSearch(searchName: String) {

```

2024-02-26 11:06 UTC, neeldoshii commented
> @neeldoshii Check the patch below for specific changes. Note that I didn't verify the dialog on the emulator.
> 
> ```diff
> diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> index b068b3d804..78bd03204c 100644
> --- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> +++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
> @@ -5,20 +5,17 @@ import android.annotation.SuppressLint
>  import android.app.Dialog
>  import android.os.Bundle
>  import androidx.appcompat.app.AlertDialog
> -import androidx.recyclerview.widget.DividerItemDecoration
> -import androidx.recyclerview.widget.LinearLayoutManager
> -import com.afollestad.materialdialogs.MaterialDialog
> -import com.afollestad.materialdialogs.input.input
> -import com.afollestad.materialdialogs.list.customListAdapter
> -import com.afollestad.materialdialogs.list.getRecyclerView
>  import com.ichi2.anki.R
>  import com.ichi2.anki.analytics.AnalyticsDialogFragment
>  import com.ichi2.compat.CompatHelper.Companion.getSerializableCompat
>  import com.ichi2.ui.ButtonItemAdapter
> +import com.ichi2.utils.createAndApply
> +import com.ichi2.utils.input
>  import com.ichi2.utils.message
>  import com.ichi2.utils.negativeButton
>  import com.ichi2.utils.positiveButton
>  import com.ichi2.utils.show
> +import com.ichi2.utils.title
>  import timber.log.Timber
>  
>  // TODO: Add different classes for the two different dialogs
> @@ -37,7 +34,7 @@ class CardBrowserMySearchesDialog : AnalyticsDialogFragment() {
>      @SuppressLint("CheckResult")
>      override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
>          super.onCreate(savedInstanceState)
> -        val dialog = MaterialDialog(requireActivity())
> +        val dialog = AlertDialog.Builder(requireActivity())
>          val type = requireArguments().getInt("type")
>          if (type == CARD_BROWSER_MY_SEARCHES_TYPE_LIST) {
>              savedFilters = requireArguments().getSerializableCompat("savedFilters")
> @@ -51,7 +48,7 @@ class CardBrowserMySearchesDialog : AnalyticsDialogFragment() {
>                  itemCallback = { searchName ->
>                      Timber.d("item clicked: %s", searchName)
>                      mySearchesDialogListener!!.onSelection(searchName)
> -                    dialog.dismiss()
> +                    dismiss()
>                  },
>                  buttonCallback = { searchName ->
>                      Timber.d("button clicked: %s", searchName)
> @@ -60,27 +57,24 @@ class CardBrowserMySearchesDialog : AnalyticsDialogFragment() {
>              ).apply {
>                  notifyAdapterDataSetChanged() // so the values are sorted.
>                  dialog.title(text = resources.getString(R.string.card_browser_list_my_searches_title))
> -                    .customListAdapter(this, null)
> +                    .customListAdapterWithDecoration(this, requireActivity())
>              }
>          } else if (type == CARD_BROWSER_MY_SEARCHES_TYPE_SAVE) {
>              val currentSearchTerms = requireArguments().getString("currentSearchTerms")
> -            dialog.title(text = getString(R.string.card_browser_list_my_searches_save))
> -                .positiveButton(android.R.string.ok)
> -                .negativeButton(R.string.dialog_cancel)
> -                .input(hintRes = R.string.card_browser_list_my_searches_new_name) { _: MaterialDialog?, text: CharSequence ->
> -                    Timber.d("Saving search with title/terms: %s/%s", text, currentSearchTerms)
> -                    mySearchesDialogListener!!.onSaveSearch(text.toString(), currentSearchTerms)
> +            return dialog.show {
> +                    title(text = getString(R.string.card_browser_list_my_searches_save))
> +                    positiveButton(android.R.string.ok)
> +                    negativeButton(R.string.dialog_cancel)
> +                    setView(R.layout.dialog_generic_text_input)
> +                }.apply {
> +                    input(hint = getString(R.string.card_browser_list_my_searches_new_name)) { dialog, text ->
> +                            Timber.d("Saving search with title/terms: %s/%s", text, currentSearchTerms)
> +                            mySearchesDialogListener!!.onSaveSearch(text.toString(), currentSearchTerms)
> +                            dialog.dismiss()
> +                    }
>                  }
>          }
> -        runCatching { dialog.getRecyclerView() }.onSuccess { recyclerView ->
> -            val layoutManager = recyclerView.layoutManager as LinearLayoutManager
> -            val dividerItemDecoration = DividerItemDecoration(recyclerView.context, layoutManager.orientation)
> -            val scale = resources.displayMetrics.density
> -            val dpAsPixels = (5 * scale + 0.5f).toInt()
> -            dialog.view.setPadding(dpAsPixels, 0, dpAsPixels, dpAsPixels)
> -            recyclerView.addItemDecoration(dividerItemDecoration)
> -        }
> -        return dialog
> +        return dialog.create()
>      }
>  
>      private fun removeSearch(searchName: String) {
> ```

tested and fixed the issue in the current commit. Thank you @lukstbit

2024-02-26 11:15 UTC, neeldoshii commented
> It still feels like the padding is too large on the right hand side
> 
> Implementer's choice, it looks better than the previous screen at this point
> 
> Thanks!!!

Should I update the code to match the padding like this for reducing padding right? 

<img src="https://github.com/ankidroid/Anki-Android/assets/60827173/f9365419-3653-4510-9fa4-1fecdbe3e1fa" width="50%" height="50%">

> 2. Can we add prefill for save search? As the user who search a particular thing is probably gonna save that new thing. Correct me if I am wrong. I didn't added it yet as it was not there previously.
> ```
> input(hint = getString(R.string.card_browser_list_my_searches_new_name), **prefill = currentSearchTerms**, allowEmpty = false, displayKeyboard = true, waitForPositiveButton = true)
> ```
> 

I have one more question from the PR description which could be helpful. Should we add this?

2024-02-29 05:30 UTC, lukstbit approved these changes

2024-02-29 05:30 UTC, lukstbit commented
Thanks for making the changes!

2024-02-29 06:51 UTC, david-allison commented
squashed + force pushed

2024-02-29 07:21 UTC, merged