Enhancement: allow SingleFragmentActivity to survive config changes
ankidroid/Anki-Android pull request #15393
Opened 2024-02-02 22:59 UTC by criticalAY

## Purpose / Description
Allow `SingleFragmentActivity` to survive config changes

## Fixes
* Fixes #15392

## How Has This Been Tested?
Google Pixel 8 emualtor 
Posting emulator ss itself
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/17eae43c-113a-44a6-b7fc-efe7b9a12d27)
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/20237182-6ff1-48fa-a732-9fdbbc17139f)

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-02-02 23:25 UTC, BrayanDSO requested changes
This breaks landscape layouts, big/small screen layouts and follow system night mode.

Reading #12832 may help you understand `configChanges` actually works.

Following the `Open–closed principle`, create another activity for that and add only `orientation|screenSize` to it

2024-02-04 11:06 UTC, BrayanDSO requested changes

2024-02-04 11:06 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> + * adjust to the new aspect ratio.
I can't undestand what you mean here.

2024-02-04 11:08 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> + * adjust to the new aspect ratio.
Doc or the file in general ?

2024-02-04 11:51 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> + * adjust to the new aspect ratio.
doc

2024-02-04 13:21 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> + * adjust to the new aspect ratio.
It means that this activity is for Image occlusion so that it handles the orientation changes when the editor (IO) has moved or resized (mask)

2024-02-04 13:45 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> + * adjust to the new aspect ratio.
1. adding `configChanges=""` without a `onConfigurationChanged` method means that the configuration changes are being **_ignored_**, not handled.
2. the actual issue is that the activity is recreated, which loses the webview state and happens with any activity with a webview. Not something specific to IO masks
3. You don't need to repeat the name of a class in its doc

```suggestion
* Handles adding and editing Image Occlusion cards.
* 
* Based in [SingleFragmentActivity], but with `configChanges="orientation|screenSize"`
* to avoid unwanted activity recreations
```

2024-02-04 13:48 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> + * adjust to the new aspect ratio.
`onConfigurationChanged` overrides nothing? I removed that due to this

2024-02-04 13:54 UTC, criticalAY commented
> onConfigurationChanged method means that the configuration changes are being ignored, not handled.

Just want to clear my device handles them without this being override? just adding `configChanges` why?

2024-02-04 14:01 UTC, BrayanDSO commented
`configChanges=` means that we want to handle the configuration changes ourselves and don't want the system to recreate the activity automatically when the specified configuration are changes.

How to handle configuration changes ourselves? with `onConfigurationChanged`

If we don't use `onConfigurationChanged`, what happens? the configuration change is ignored

2024-02-04 16:05 UTC, criticalAY commented
I read a lot of comments and post for some people it works just by putting the configChanges in manifest file ?
https://stackoverflow.com/questions/12131025/android-preventing-webview-reload-on-rotate

2024-02-04 21:31 UTC, BrayanDSO commented
> I read a lot of comments and post for some people it works just by putting the configChanges in manifest file ?
https://stackoverflow.com/questions/12131025/android-preventing-webview-reload-on-rotate

It does and I never said it doesn't. I'm trying to explain why it works

2024-02-04 21:31 UTC, BrayanDSO approved these changes

2024-02-05 17:44 UTC, mikehardy reviewed
Seems like it should work, but obviously seems like the override-that-only-calls-super is redundant?

2024-02-05 17:44 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> +    }
If a subclass declares an override method that does nothing but calls the super for the method, do you have to actually override the method?

Isn't this the same behavior as not overriding it at all - meaning this shouldn't be here?

2024-02-05 17:45 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> +    }
This is what I was saying here, 
> I read a lot of comments and post for some people it works just by putting the configChanges in manifest file ?
https://stackoverflow.com/questions/12131025/android-preventing-webview-reload-on-rotate

2024-02-05 18:12 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> +    }
What I want to hear is "I tested it without the seemingly redundant override-that-only-calls-super and I discovered...." (then some description of your results)

2024-02-05 18:13 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> +    }
I tested it out without it too and with it ,and it works fine without it

2024-02-05 18:13 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> +    }
(because unless I'm misunderstanding how overrides and super calls work, if you override but only call super, you're not doing anything and your override is redundant and unneeded - I need to see experimental results that contradict my understanding, not some stackoverflow faffery :-) )

2024-02-05 18:15 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> +    }
ok thanks!

2024-02-05 18:16 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> +    }
Done!!

2024-02-05 18:27 UTC, mikehardy approved these changes
nice, LGTM

2024-02-05 18:42 UTC, david-allison approved these changes

2024-02-05 18:45 UTC, merged