Removed the Material Dialog Box and Added Alert Box from DatabaseErrorDialog
ankidroid/Anki-Android pull request #15396
Opened 2024-02-03 14:57 UTC by neeldoshii

## Fixes
* Related #13315  

## Approach
Replaces usages of Deprecated MaterialDialog and adds the Native AlertDialog For DatabaseErrorDialog

## Images

**Restore Backup**

| Material Dialog | Alert Dialog |
|-----------------|--------------|
| ![Material Dialog](https://github.com/ankidroid/Anki-Android/assets/60827173/4182ed26-32f8-4d0c-9a67-393898d7d4ee) | ![Alert Dialog](https://github.com/ankidroid/Anki-Android/assets/60827173/d553ee91-fa43-4795-aa60-22293b6a55b5) |

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [X] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-02-28 14:37 UTC, neeldoshii commented
This PR doesn't cover full conversion of DatabaseErrorDialog but covers massive dialog conversion. Only 4 dialogs are left for conversion. 

Few Extension needs to be made in order to convert some dialog to alertDialog. I will be creating separate PR for extension of this which will help in this dialog conversion

1. We don't have extension for handling negative button enable/disable based on boolean.
https://github.com/ankidroid/Anki-Android/blob/cc3a765708796b0a44f5f0a0a047997ada7fd7f7/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt#L111

2. We don't have extension for `listItemsSingleChoice` .
https://github.com/ankidroid/Anki-Android/blob/cc3a765708796b0a44f5f0a0a047997ada7fd7f7/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt#L224

2024-02-28 17:57 UTC, david-allison requested changes
Are you planning to squash merge or rebase merge this?

2024-02-28 18:54 UTC, neeldoshii commented
> Are you planning to squash merge or rebase merge this?

Squash Merge.

2024-02-28 19:01 UTC, david-allison requested changes
Could you send a screenshot of the comparison of the `listItems` one in dark mode?

And check the others

Other than that, looks fine, thanks!

2024-02-28 19:26 UTC, neeldoshii commented
> Could you send a screenshot of the comparison of the `listItems` one in dark mode?
> 
> And check the others
> 
> Other than that, looks fine, thanks!
<img src = "https://github.com/ankidroid/Anki-Android/assets/60827173/676f88e1-c827-4c71-a8f3-1132c50043ad" width = "50%" height ="50%">

2024-02-28 19:35 UTC, david-allison approved these changes
Thanks @neeldoshii

2024-03-01 10:55 UTC, BrayanDSO approved these changes

2024-03-01 16:43 UTC, merged