Removed the Material Dialog Box and Added Alert Box from TagsDialog
ankidroid/Anki-Android pull request #15398
Opened 2024-02-03 23:30 UTC by neeldoshii

## Fixes
* Related #13315  

## Approach
Replaces usages of Deprecated MaterialDialog and adds the Native AlertDialog For TagsDialog.

## Working Video (Alert Dialog)

https://github.com/ankidroid/Anki-Android/assets/60827173/a4c14e6e-5cd2-4740-a6fa-ef25207eb4d9

https://github.com/ankidroid/Anki-Android/assets/60827173/e17afcf3-0f1e-427c-9587-7be35fbd6810

## Previously (Material Dialog)

https://github.com/ankidroid/Anki-Android/assets/60827173/4539bf8b-7739-420f-9435-ea5277561a0f

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [X] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-02-03 23:37 UTC, david-allison requested changes

2024-02-03 23:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
> -        resizeWhenSoftInputShown(dialog?.window!!)
Why was this removed?

See d7778e80adf9f1f89fc156679deaa28cafc26616 for how to implement

2024-02-03 23:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
> -            inputET.setText("$prefixTag ")
Why was this removed? I would expect the trailing space to be kept

2024-02-04 11:04 UTC, BrayanDSO commented
Currently you have 4 open PRs that can't be reviewed. Try to slow down and get each one to completion before creating new ones.

2024-02-04 12:10 UTC, neeldoshii commented
> Currently you have 4 open PRs that can't be reviewed. Try to slow down and get each one to completion before creating new ones.

Cool!!

2024-02-04 12:12 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
> -        resizeWhenSoftInputShown(dialog?.window!!)
I thought we add it inside our util extension method. 
I will add it in my next commit as fix.

2024-02-28 18:41 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
> -        resizeWhenSoftInputShown(dialog?.window!!)
Fixed.

2024-02-28 18:41 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
> -            inputET.setText("$prefixTag ")
Fixed.

2024-02-28 18:42 UTC, neeldoshii commented
Tests are failing because of `TagDialogTest` uses Material Dialog.

```
TagsDialogTest > test_SearchTag_willInheritExpandState FAILED
    java.lang.ClassCastException: class androidx.appcompat.app.AlertDialog cannot be cast to class com.afollestad.materialdialogs.MaterialDialog (androidx.appcompat.app.AlertDialog and com.afollestad.materialdialogs.MaterialDialog are in unnamed module of loader org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader @68f776ee)
        at com.ichi2.anki.dialogs.tags.TagsDialogTest.test_SearchTag_willInheritExpandState$lambda$11(TagsDialogTest.kt:441)
        at androidx.fragment.app.testing.FragmentScenario.onFragment$lambda$6(FragmentScenario.kt:323)
        at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$androidx-test-core-app-ActivityScenario(ActivityScenario.java:789)
        at androidx.test.core.app.ActivityScenario$$ExternalSyntheticLambda2.run(D8$$SyntheticClass)
        at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:799)
        at androidx.fragment.app.testing.FragmentScenario.onFragment(FragmentScenario.kt:316)
        at com.ichi2.anki.dialogs.tags.TagsDialogTest.test_SearchTag_willInheritExpandState(TagsDialogTest.kt:440)

```

2024-02-28 19:35 UTC, david-allison commented
They need to be fixed

2024-03-23 15:37 UTC, neeldoshii commented
"Keep Open"

2024-03-24 02:05 UTC, david-allison commented
Tests still need to be fixed

2024-05-20 11:38 UTC, lukstbit approved these changes
Approved as I'm the person that made the changes.

@neeldoshii I wanted to incorporate your previous work to credit you, but blindly I did a forced reset seeing as the PR was so old. This eliminated you from the git authors, sorry.

2024-05-20 14:09 UTC, neeldoshii commented
> @neeldoshii I wanted to incorporate your previous work to credit you, but blindly I did a forced reset seeing as the PR was so old. This eliminated you from the git authors, sorry.

Sure, no problem. Thanks though for taking this PR to the completion stage.

2024-05-20 14:35 UTC, david-allison approved these changes
LGTM, thanks both!

2024-05-20 14:35 UTC, david-allison commented
@lukstbit I've force pushed to reapply credit to @neeldoshii in the first commit.

2024-05-20 15:10 UTC, merged