feat: day rollover handling
ankidroid/Anki-Android pull request #15412
Opened 2024-02-04 23:53 UTC by david-allison

## Reviewer Note

Review harshly, shouldn't have done this whilst tired

## Purpose / Description
AnkiDroid needs to perform certain operations after a day rollover,
otherwise the backend throws InvalidInputException when reviewing

## Fixes
* Fixes _Link to the issues._

## Approach
* ⚠️ This is a hack

Due to complexities of Android scheduling a timer at a given time,
we use a hack:

* Every minute, run a function
* If we have less than a minute to go, run this check every second

In the future, this ideally will be removed, as it's inexact

We care about:

* Reviewer - a new card may be seen
* DeckPicker - counts will be updated
* CongratsScreen - bury status will change

----

`DayRolloverHandler` is a singleton, we maintain a weak collection of LifecycleOwners to ensure the `Runnable` is not executed twice

## How Has This Been Tested?
I changed code to perform a 'day rollover' every second, and ensured that the 

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-02-05 02:39 UTC, david-allison commented
The test failures are indicative of a larger problem:

* We execute tests on an `Unconfined` Dispatcher:

https://github.com/ankidroid/Anki-Android/blob/abb6a36681a0fe0e0dca04d02468c6c40c81e9fe/AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt#L215


This leads to the following, even if inside a `withContext(Dispatchers.Main)`

```
    java.lang.RuntimeException: Can't create handler inside thread Thread[#34,DefaultDispatcher-worker-1 @coroutine#912,5,SDK 33] that has not called Looper.prepare()
        at android.os.Handler.__constructor__(Handler.java:227)
```

2024-02-05 06:42 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DayRolloverHandler.kt
> + * Checks every minute for a 'day rollover' event.
I'll look at this more closely later this day, but have you looked into using [the time changed broadcast intent](https://developer.android.com/reference/android/content/Intent#ACTION_TIME_CHANGED)?

2024-02-05 09:54 UTC, BrayanDSO commented
Does it need to run every minute if the rollover is like 20h from now?

2024-02-05 15:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DayRolloverHandler.kt
> + * Checks every minute for a 'day rollover' event.
Thanks, I'll investigate. Drafting for now

2024-02-08 15:18 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DayRolloverHandler.kt
> +            ContextCompat.registerReceiver(context, DayRolloverHandler, filter, RECEIVER_EXPORTED)
saw the register lines below without any export sauce and thought "oh no, was this tested on current android?" then saw you'd abstracted it here so it was always exported. 👍

2024-02-08 15:22 UTC, mikehardy requested changes
I think this is a nice final solution, my comments are trivial

2024-02-08 15:22 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DayRolloverHandler.kt
> +        Timber.v("received ${intent!!.action}")
if it's declared in the method as possibly null why-oh-why !! it here when there's a null-ish operator? 
Imagine crashing because of a Timber.v statement

```suggestion
        Timber.v("received ${intent?.action}")
```

2024-02-08 15:22 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DayRolloverHandler.kt
> +        register(IntentFilter(ACTION_TIMEZONE_CHANGED))
I don't believe the commit message is accurate anymore now that you are receiving system broadcasts vs running handlers ?

2024-02-08 15:25 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DayRolloverHandler.kt
> +        register(IntentFilter(ACTION_TIMEZONE_CHANGED))
also the PR description may be out of date with the intent-based broadcast receipt style vs handlers?

2024-02-08 20:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DayRolloverHandler.kt
> +        Timber.v("received ${intent!!.action}")
Great catch!

2024-02-08 20:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DayRolloverHandler.kt
> +        register(IntentFilter(ACTION_TIMEZONE_CHANGED))
This seems fine, could you suggest an improvement?

```
feat: day rollover handling

AnkiDroid needs to perform certain operations after a day rollover,
otherwise the backend throws InvalidInputException when reviewing

Due to complexities of Android scheduling a timer at a given time,
we use a hack:

* Every minute, run a function
* If we have less than a minute to go, run this check every second

In the future, this ideally will be removed, as it's inexact

We care about:

* Reviewer - a new card may be seen
* DeckPicker - counts will be updated
* CongratsScreen - bury status will change

Fixes 14090
```

2024-02-08 20:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DayRolloverHandler.kt
> +        register(IntentFilter(ACTION_TIMEZONE_CHANGED))
Already did the PR, the commit slipped through the cracks, thanks!

2024-02-09 02:11 UTC, mikehardy approved these changes
works for me as a solid first cut at solving this

2024-02-09 17:54 UTC, lukstbit approved these changes
Fine, but we should look into this later(maybe create a issue?) to try to optimize the check.

2024-02-09 17:54 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/utils/TimeUtil.kt
> +suspend fun <T> coMeasureTime(functionName: String? = "", function: suspend () -> T): T {
This is unused.

2024-02-09 19:07 UTC, merged

2024-02-09 20:24 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/TimeUtil.kt
> +suspend fun <T> coMeasureTime(functionName: String? = "", function: suspend () -> T): T {
It's helpful for debugging and I felt it was worthwhile to keep it in

2024-03-14 08:58 UTC, andreas1974 commented
> ⚠️ This is a hack, please suggest a better method, happy to rewrite

Hi David!

And thanks for trying to deal with this issue.
I do however have another suggestion: Could you add an error handler that just suppresses / ignores this exact error instead, on this place in the code? I guess it would mean one question,  at the most, not rated every 24 hours, right? Personally I'd prefer that to code running every second. 

> "> withCol { sched.dayCutoff } takes 0-5ms on a background thread, I'm not worried about a hit to battery life from this"

Yes, I read you are not worried about the hit to battery life, but if many app programmers argue the same way, running 5 ms code every second, there will eventually be a hit on performance and battery life.
That is why I would prefer losing one rated card every day, or getting the same card again (if that is what will happen). I don't mind much getting a question just one extra time a day.

Thanks, 
Andreas Jansson

2024-03-14 09:59 UTC, david-allison commented
@andreas1974 could you move the comment to a new issue so we can track a more permanent fix

2024-03-14 11:02 UTC, david-allison commented
No worries! It's typically best to pick the open issue (or the most recent non-duplicate). The following which you chose is perfect

* https://github.com/ankidroid/Anki-Android/issues/15889