CustomStudyDialog uses Alert Dialog
ankidroid/Anki-Android pull request #15459
Opened 2024-02-08 18:38 UTC by neeldoshii

## Fixes
* Related #13315  

## Approach
Replaces usages of Deprecated MaterialDialog and adds the Native AlertDialog For CustomStudyDialog.

## Images

| Material Dialog | Alert Dialog |
| --------------- | ------------ |
| ![Material Dialog Image](https://github.com/ankidroid/Anki-Android/assets/60827173/c8039065-b97f-4f27-9b33-9f03ec13809e) | ![Alert Dialog Image](https://github.com/ankidroid/Anki-Android/assets/60827173/2a433b3c-f5f5-4d0b-adb3-32b8eafdfb80) |

| Material Dialog | Alert Dialog |
| --------------- | ------------ |
| ![Material Dialog Image](https://github.com/ankidroid/Anki-Android/assets/60827173/e7a3ce46-60a8-47e1-8485-babe395221bb) | ![Alert Dialog Image](https://github.com/ankidroid/Anki-Android/assets/60827173/c8221b76-8584-42f3-9e7c-c54fa887b861) |

Addition Consideration :

```
.listItems(items = getValuesFromKeys(keyValueMap, listIds).toList().map { it as CharSequence }) { _: MaterialDialog, _: Int, charSequence: CharSequence ->
```
For this we didn't had extension method I have used manual method for now using
```.setItems()```

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [X] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-02-08 20:25 UTC, david-allison commented
tests failing

2024-02-08 20:25 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +                    dialog.getButton(AlertDialog.BUTTON_POSITIVE).isEnabled = true
`positiveButton` I belive

2024-02-08 20:35 UTC, neeldoshii commented
> tests failing

I am making this PR as draft for now. As I have many PR in queue once its ready for review I will open it again.

2024-02-28 16:51 UTC, neeldoshii commented
> I am making this PR as draft for now. As I have many PR in queue once its ready for review I will open it again.

The PR is now ready for review.

2024-02-28 17:43 UTC, david-allison requested changes
Tests are failing

2024-02-28 17:52 UTC, neeldoshii commented
> Tests are failing
Hi @david-allison. 
The test is getting failed because in CustomStudyDialogTest we have used MaterialDialog so when testing it with AlertDialog its getting failed i guess. 
[CustomStudyDialogTest](https://github.com/ankidroid/Anki-Android/blob/0ab90ba8c1def105b512b507800c823d85bc9af4/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt#L21)
```
CustomStudyDialogTest > increaseNewCardLimitRegressionTest FAILED
java.lang.ClassCastException: class androidx.appcompat.app.AlertDialog cannot be cast to class com.afollestad.materialdialogs.MaterialDialog (androidx.appcompat.app.AlertDialog and com.afollestad.materialdialogs.MaterialDialog are in unnamed module of loader org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader @376498da)
 ```

2024-03-13 19:51 UTC, neeldoshii commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt
> -            MatcherAssert.assertThat(dialog!!.items, Matchers.not(Matchers.hasItem(getResourceString(R.string.custom_study_increase_new_limit))))
Maintainers Note:
Not sure is removing this relevant or not. If not then let me know how this can be handled.

2024-03-13 22:24 UTC, david-allison commented
```patch
Subject: [PATCH] fix: videos with only audio stream

A number of video extension may only contain audio

In these cases, we should show a play button

Sources:
* anki-15872-valid-1.mp4 -> https://github.com/chromium/chromium/blob/main/third_party/blink/web_tests/external/wpt/media/movie_5.mp4
* anki-15872-audio-only.webm -> https://github.com/chromium/chromium/blob/main/third_party/blink/web_tests/external/wpt/media/test-a-128k-44100Hz-1ch.webm
* anki-15872-audio-only.mp4 -> https://github.com/chromium/chromium/blob/main/third_party/blink/web_tests/external/wpt/media-source/mp4/test-a-128k-44100Hz-1ch.mp4

I attempted to use MediaMetadataRetriever:

```
MediaMetadataRetriever().let {
    it.setDataSource(file.path)
    it.extractMetadata(MediaMetadataRetriever.METADATA_KEY_HAS_VIDEO)
}
```

but it fails on API 23 with:

```
java.lang.RuntimeException: setDataSource failed: status = 0x80000000
at android.media.MediaMetadataRetriever.setDataSource(Native Method)
```

Fixes 15872

Co-authored-by: Brayan Oliveira <69634269+brayandso@users.noreply.github.com>
---
Index: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt	(revision a6573e61bbaed9a836f46611564488a27631fc6f)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt	(date 1710368439209)
@@ -15,8 +15,7 @@
  */
 package com.ichi2.anki.dialogs
 
-import android.app.AlertDialog
-import android.content.DialogInterface
+import androidx.appcompat.app.AlertDialog
 import androidx.fragment.app.testing.FragmentScenario
 import androidx.lifecycle.Lifecycle
 import androidx.test.ext.junit.runners.AndroidJUnit4
@@ -24,6 +23,7 @@
 import com.ichi2.anki.dialogs.customstudy.CustomStudyDialog
 import com.ichi2.anki.dialogs.customstudy.CustomStudyDialog.CustomStudyListener
 import com.ichi2.anki.dialogs.customstudy.CustomStudyDialogFactory
+import com.ichi2.anki.dialogs.utils.performPositiveClick
 import com.ichi2.libanki.Collection
 import com.ichi2.libanki.sched.Scheduler
 import com.ichi2.testutils.ParametersUtils
@@ -40,6 +40,8 @@
 import org.mockito.kotlin.mock
 import org.mockito.kotlin.whenever
 import org.robolectric.annotation.Config
+import kotlin.test.assertNotNull
+
 
 @RunWith(AndroidJUnit4::class)
 class CustomStudyDialogTest : RobolectricTest() {
@@ -62,12 +64,11 @@
             .withArguments(CustomStudyDialog.ContextMenuOption.STUDY_AHEAD, 1)
             .arguments
         val factory = CustomStudyDialogFactory({ this.col }, mockListener)
-        val scenario = FragmentScenario.launch(CustomStudyDialog::class.java, args, factory)
-        scenario.moveToState(Lifecycle.State.STARTED)
+        val scenario = FragmentScenario.launch(CustomStudyDialog::class.java, args, androidx.appcompat.R.style.Theme_AppCompat, factory)
+        scenario.moveToState(Lifecycle.State.RESUMED)
         scenario.onFragment { f: CustomStudyDialog ->
-            val dialog = f.dialog as AlertDialog?
-            MatcherAssert.assertThat(dialog, IsNull.notNullValue())
-            dialog?.getButton(DialogInterface.BUTTON_POSITIVE)?.callOnClick()
+            val dialog = assertNotNull(f.dialog as AlertDialog?)
+            dialog.performPositiveClick()
         }
         val customStudy = col.decks.current()
         MatcherAssert.assertThat("Custom Study should be dynamic", customStudy.isFiltered)
Index: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/AlertDialogUtils.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/AlertDialogUtils.kt b/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/AlertDialogUtils.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/AlertDialogUtils.kt	(revision a6573e61bbaed9a836f46611564488a27631fc6f)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/AlertDialogUtils.kt	(date 1710368645170)
@@ -16,9 +16,15 @@
 
 package com.ichi2.anki.dialogs.utils
 
+import android.content.DialogInterface
 import android.widget.TextView
 import androidx.appcompat.app.AlertDialog
+import androidx.core.view.isVisible
+import org.hamcrest.MatcherAssert.*
+import androidx.test.platform.app.InstrumentationRegistry
+import com.ichi2.utils.HandlerUtils.executeFunctionUsingHandler
 import com.ichi2.utils.getInputField
+import kotlin.test.assertNotNull
 
 var AlertDialog.input
     get() = getInputField().text.toString()
@@ -28,3 +34,12 @@
     get() = requireNotNull(this.findViewById<TextView>(androidx.appcompat.R.id.alertTitle)) {
         "androidx.appcompat.R.id.alertTitle not found"
     }.text.toString()
+
+fun AlertDialog.performPositiveClick() {
+    // This exists as callOnClick did not call the listener
+    val positiveButton = assertNotNull(getButton(DialogInterface.BUTTON_POSITIVE), message =  "positive button")
+    assertThat("button is visible", positiveButton.isVisible)
+    assertThat("button is enalbed", positiveButton.isEnabled)
+    executeFunctionUsingHandler { positiveButton.callOnClick() }
+    InstrumentationRegistry.getInstrumentation().waitForIdleSync()
+}
\ No newline at end of file
```

2024-03-13 22:47 UTC, neeldoshii commented
Test case passed!!! Special thanks to David for the patch that fixed the testcase.

2024-03-13 22:56 UTC, david-allison submitted a review, later dismissed
Note: not tested manually, the code looks good

2024-03-13 22:58 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt
> -            MatcherAssert.assertThat(dialog!!.items, Matchers.not(Matchers.hasItem(getResourceString(R.string.custom_study_increase_new_limit))))
Yes, this should be fixed

2024-03-14 11:49 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +                .positiveButton(R.string.dialog_ok) {
do you mean  indentation of positive button?

2024-03-14 11:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +                .positiveButton(R.string.dialog_ok) {
Look at the "files changed" tab and there's a lot of whitespace differences.

2024-03-14 13:50 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +                .positiveButton(R.string.dialog_ok) {
But you added `.apply {`, that doesn't need to happen when you're doing a migration

```patch
Subject: [PATCH] aa
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt	(revision 13b21868c837d820413eaf59933157184ee3380f)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt	(revision 8ecde43413d40ea4d85b8d5fd20fb36cf7efc0bd)
@@ -107,55 +107,54 @@
         val jumpToReviewer = requireArguments().getBoolean("jumpToReviewer")
         val items = getValuesFromKeys(keyValueMap, listIds).toList().map { it as CharSequence }
 
-        return AlertDialog.Builder(requireActivity()).apply {
-            title(R.string.custom_study)
-                .cancelable(true)
-                .listItems(items = items) { _, index ->
-                    when (ContextMenuOption.fromString(resources, items[index].toString())) {
-                        DECK_OPTIONS -> {
-                            // User asked to permanently change the deck options
-                            val deckId = requireArguments().getLong("did")
-                            val i = com.ichi2.anki.pages.DeckOptions.getIntent(requireContext(), deckId)
-                            requireActivity().startActivity(i)
-                        }
-                        MORE_OPTIONS -> {
-                            // User asked to see all custom study options
-                            val d = CustomStudyDialog(collection, customStudyListener)
-                                .withArguments(
-                                    STANDARD,
-                                    requireArguments().getLong("did"),
-                                    jumpToReviewer
-                                )
-                            customStudyListener?.showDialogFragment(d)
-                        }
-                        STUDY_TAGS -> {
+        return AlertDialog.Builder(requireActivity())
+            .title(R.string.custom_study)
+            .cancelable(true)
+            .listItems(items = items) { _, index ->
+                when (ContextMenuOption.fromString(resources, items[index].toString())) {
+                    DECK_OPTIONS -> {
+                        // User asked to permanently change the deck options
+                        val deckId = requireArguments().getLong("did")
+                        val i = com.ichi2.anki.pages.DeckOptions.getIntent(requireContext(), deckId)
+                        requireActivity().startActivity(i)
+                    }
+                    MORE_OPTIONS -> {
+                        // User asked to see all custom study options
+                        val d = CustomStudyDialog(collection, customStudyListener)
+                            .withArguments(
+                                STANDARD,
+                                requireArguments().getLong("did"),
+                                jumpToReviewer
+                            )
+                        customStudyListener?.showDialogFragment(d)
+                    }
+                    STUDY_TAGS -> {
                         /*
                          * This is a special Dialog for CUSTOM STUDY, where instead of only collecting a
                          * number, it is necessary to collect a list of tags. This case handles the creation
                          * of that Dialog.
                          */
-                            val currentDeck = requireArguments().getLong("did")
+                        val currentDeck = requireArguments().getLong("did")
 
-                            val dialogFragment = TagsDialog().withArguments(
-                                TagsDialog.DialogType.CUSTOM_STUDY_TAGS,
-                                ArrayList(),
-                                ArrayList(collection.tags.byDeck(currentDeck))
-                            )
-                            customStudyListener?.showDialogFragment(dialogFragment)
-                        }
-                        else -> {
-                            // User asked for a standard custom study option
-                            val d = CustomStudyDialog(collection, customStudyListener)
-                                .withArguments(
-                                    ContextMenuOption.fromString(resources, items[index].toString()),
-                                    requireArguments().getLong("did"),
-                                    jumpToReviewer
-                                )
-                            customStudyListener?.showDialogFragment(d)
-                        }
+                        val dialogFragment = TagsDialog().withArguments(
+                            TagsDialog.DialogType.CUSTOM_STUDY_TAGS,
+                            ArrayList(),
+                            ArrayList(collection.tags.byDeck(currentDeck))
+                        )
+                        customStudyListener?.showDialogFragment(dialogFragment)
+                    }
+                    else -> {
+                        // User asked for a standard custom study option
+                        val d = CustomStudyDialog(collection, customStudyListener)
+                            .withArguments(
+                                ContextMenuOption.fromString(resources, items[index].toString()),
+                                requireArguments().getLong("did"),
+                                jumpToReviewer
+                            )
+                        customStudyListener?.showDialogFragment(d)
                     }
                 }
-        }.show()
+            }.show()
     }
 
     @KotlinCleanup("make this use enum instead of Int")
@@ -198,90 +197,90 @@
         // Whether or not to jump straight to the reviewer
         val jumpToReviewer = requireArguments().getBoolean("jumpToReviewer")
         // Set material dialog parameters
-        val dialog = AlertDialog.Builder(requireActivity()).apply {
-            customView(view = v, paddingLeft = 64, paddingRight = 64, paddingTop = 32, paddingBottom = 32)
-                .positiveButton(R.string.dialog_ok) {
-                    // Get the value selected by user
-                    val n: Int = try {
-                        editText.text.toString().toInt()
-                    } catch (e: Exception) {
-                        Timber.w(e)
-                        // This should never happen because we disable positive button for non-parsable inputs
-                        return@positiveButton
-                    }
-                    when (contextMenuOption) {
-                        STUDY_NEW -> {
-                            requireActivity().sharedPrefs().edit { putInt("extendNew", n) }
-                            val deck = collection.decks.get(did)!!
-                            deck.put("extendNew", n)
-                            collection.decks.save(deck)
-                            collection.sched.extendLimits(n, 0)
-                            onLimitsExtended(jumpToReviewer)
-                        }
-                        STUDY_REV -> {
-                            requireActivity().sharedPrefs().edit { putInt("extendRev", n) }
-                            val deck = collection.decks.get(did)!!
-                            deck.put("extendRev", n)
-                            collection.decks.save(deck)
-                            collection.sched.extendLimits(0, n)
-                            onLimitsExtended(jumpToReviewer)
-                        }
-                        STUDY_FORGOT -> {
-                   [...]

2024-03-14 13:51 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +                .positiveButton(R.string.dialog_ok) {
The patch makes this much easier to review, and implies a number of bugs with the addition of `.create()` and `.show()`

The point is to make the patch 'obviously correct', changing the structure of the code (`apply` vs method chaining) obscures this

2024-03-14 13:55 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +                .positiveButton(R.string.dialog_ok) {
done added.

2024-03-14 13:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +            }.show()
is this needed?

2024-03-14 13:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +            .create()
is this needed?

2024-03-14 14:00 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +                .positiveButton(R.string.dialog_ok) {
Thanks @neeldoshii !!

2024-03-15 13:46 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +            .create()
without `.create()` it gives me error in accessing `dialog.positiveButton.isEnabled = true`

2024-03-15 13:54 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +            }.show()
Not sure about other approach, but removing `.show()` or `.create()` gives 
Type mismatch: inferred type is AlertDialog.Builder but AlertDialog was expected

What do you think would be good?

2024-03-15 20:35 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +            }.show()
David mean that do not show dialog only create it

2024-03-15 20:40 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +            }.show()
I would suggest you to create dialog instead of show

2024-03-15 20:57 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +            }.show()
Thank You. Will make the changes.

2024-03-20 15:22 UTC, david-allison requested changes

2024-03-20 15:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +            .create()
Leave a comment and let's keep the call

2024-03-20 15:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +            }.show()
Sounds good!

2024-03-21 02:19 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +            }.show()
Made the changes

2024-03-21 02:20 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +            .create()
Added the comment.

2024-03-24 21:01 UTC, david-allison approved these changes
Thanks!

2024-03-25 00:10 UTC, Arthur-Milchior approved these changes

2024-03-25 00:10 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +            .listItems(items = items) { _, index ->
I admit I'm confused.
It seems you introduced `listItems`, use it in a single place, and ignore the first argument of `onClick`
if so, why not simply have `onClick` takes a single argument, the index ?

2024-03-27 11:26 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +            .listItems(items = items) { _, index ->
I am not sure I understood the question exactly, Its better to handle the onClick taking the index of the list.

2024-03-31 01:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +            .listItems(items = items) { _, index ->
I'm totally fine with you using the index of the list.
My question is, why does this function requires a first argument ? 
In `listItems` it seems you could delete the first argument of the block, and have smaller code that would still work.
But I'm not blocking on that

2024-04-03 19:53 UTC, neeldoshii commented
Hi, should I squash down to two commits now
- Refactor to Alert Dialog
- Listitem code refactor

or should I squash down to one commit?

2024-04-03 19:53 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +            .listItems(items = items) { _, index ->
did the changes.

2024-04-04 02:21 UTC, david-allison commented
Two commits, both of which should compile if you `git checkout <hash>`

* Each commit in `main` should compile
* We don't want to squash a refactor and an 'extract', as that's complex for someone to review, requires reverting too much if a bug is introduced, and makes it harder to understand the code if a bug needs to be diagnosed

2024-04-04 05:31 UTC, neeldoshii commented
Squashed the commits.

Did a git checkout for https://github.com/ankidroid/Anki-Android/pull/15459/commits/b48180b3a861e6e7988654d03d844f0b7ad064a6 and it compiles.

2024-04-04 18:26 UTC, david-allison requested changes
First commit is good, the second seems like it'll add a burden in future, especially as `setItems` uses `dialog`

2024-04-04 18:26 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
> +fun AlertDialog.Builder.listItems(items: List<CharSequence>, onClick: (index: Int) -> Unit): AlertDialog.Builder {
Having a reference to the `dialog` is useful, I'd drop this commit

2024-04-04 19:22 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
> +fun AlertDialog.Builder.listItems(items: List<CharSequence>, onClick: (index: Int) -> Unit): AlertDialog.Builder {
Done.

2024-04-05 02:25 UTC, david-allison approved these changes
Looks great, thanks!

2024-04-05 02:25 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +            .listItems(items = items) { _, index ->
The underlying API accepts a dialog parameter. I requested that this is reverted

2024-04-05 02:25 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
> +fun AlertDialog.Builder.listItems(items: List<CharSequence>, onClick: (index: Int) -> Unit): AlertDialog.Builder {
We've all gone through a learning stage, and we're all still learning. Very welcome!

2024-04-11 08:09 UTC, lukstbit requested changes

2024-04-23 13:01 UTC, neeldoshii commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt
> -            MatcherAssert.assertThat(dialog!!.items, Matchers.not(Matchers.hasItem(getResourceString(R.string.custom_study_increase_new_limit))))
HI @lukstbit, I have made the changes.

2024-04-24 16:42 UTC, lukstbit approved these changes
LGTM!
Also thanks for squashing!

2024-04-26 11:38 UTC, neeldoshii commented
@lukstbit should I remove this redundant package as this is no longer used in our test after `CustomStudyDialog` migration?
https://github.com/ankidroid/Anki-Android/blob/6354574aee656b96f732928007618286e9e6c239/AnkiDroid/src/test/java/com/ichi2/testutils/DialogUtils.kt#L17-L37

2024-04-26 21:27 UTC, mikehardy commented
can do any further refactors as an easy followup PR (e.g., removing a no-longer-needed package if that's the case)

2024-04-26 21:42 UTC, merged