Fix: IllegalArgumentException on with progress dialog dimiss
ankidroid/Anki-Android pull request #15461
Opened 2024-02-08 21:54 UTC by criticalAY

## Purpose / Description
`withProgress` dialog might throw IllegalArgumentException if the dialog is not shown and dismiss is called 

## Fixes
* Fixes #15445

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-02-08 22:11 UTC, david-allison requested changes
Thanks!

2024-02-08 22:11 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +        }
This should be wrapped in. try...catch as well, there's a rare race condition here

2024-02-08 22:21 UTC, david-allison approved these changes

2024-02-08 22:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +        Timber.v(e)
use `.w`

2024-02-08 22:32 UTC, david-allison approved these changes
It was good, now it's even better, thanks!

2024-02-09 06:37 UTC, lukstbit approved these changes
Thanks!

2024-02-09 06:51 UTC, merged