update some libanki stuff related to notes and notetypes
ankidroid/Anki-Android pull request #15476
Opened 2024-02-10 22:37 UTC by BrayanDSO

## Purpose / Description
prep for porting the template previewer

## Approach
In the commits

## How Has This Been Tested?

Unit tests + Did the same steps of #14692 to be sure it wasn't created again.

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-02-10 23:27 UTC, david-allison commented
Unit tests failure

2024-02-11 12:53 UTC, david-allison requested changes
needs testing

2024-02-11 12:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
> +            return n.ephemeralCard(getColUnsafe, ord = ord, customNoteType = notetype)
Have you tested this with

* https://github.com/ankidroid/Anki-Android/issues/14692#issuecomment-1808380554

2024-02-11 12:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
> -private class EphemeralCard(col: Collection, id: Long?) : Card(col, id) {
This feels like it needs a separate commit

2024-02-11 18:58 UTC, david-allison approved these changes

2024-02-12 04:51 UTC, lukstbit approved these changes

2024-02-12 05:05 UTC, merged