fix(card-browser): retain state in 'onStart'
ankidroid/Anki-Android pull request #15488
Opened 2024-02-12 20:45 UTC by david-allison

## Purpose / Description
The flows were refreshed, causing a search if a user backgrounded the app and restored it

Also with editing notes in different activities

## Fixes
* Fixes 14220

## Approach
_How does this change address the problem?_

## How Has This Been Tested?
On my S21: editing notes and backgrounding the app:

* editing removes selection (as previously)
* backgrounding now maintains scroll position

## Learning (optional, can help others)
I did not know this issue that a `StateFlow` would refresh when backgrounded. This won't be a problem when we move searching into the `ViewModel`, but is for now

## Checklist
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-02-12 22:23 UTC, oakkitten requested changes
Only did a cusory look through the code.

If I may suggest, 

* I am not sure if `flowWithLifecycle` is useful here. You use `flowWithLifecycle` when you wan to start/stop collecting a flow when the lifecycle moves in and out of some state. Usually you do this when you have a long-running action that updates state, but you don't want to waste resources updating UI when the activity is stopped.

        |------------------state updates------------------|
               |--UI active--|   |----UI active----|

    An example of such an action would a file upload that happens in background, and UI with progress.

    For stuff like updating the “Truncate content” state, using this is probably redundant because:

   * Truncate content is a momentary change, and
   * It can only happen when UI is active, anyway.

    Instead, simply do something along

    ```kt
    fun onCreate(...) {
    	lifecycleScope.launch {
    		flowOfisContentTruncated.collect { ... }
    	}
    }
    ```

* Something with the name `isTruncatedFlow` should probably be a `Boolean`. I suggest the syntax `flowOfThing` (disclaimer: my own invention, as used in `ManageSpaceFragment`).

* `flowWhenActive` does not reflect what is happening. Whan is “active”?

2024-02-12 22:23 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        viewModel.cardsOrNotesFlow.flowWhenActive { runOnUiThread { searchCards() } }
Why `runOnUiThread`?

2024-02-14 15:13 UTC, BrayanDSO approved these changes

2024-02-14 19:05 UTC, oakkitten approved these changes
5d467ac77fb33adc7f62def0bca1c48e924fea35 removes a single `runOnUiThread` out of a few. Suggest either removing all of the redundant calls or dropping the commit.

P.S. Something like `dataFlow` is readable enough, but as, in in the example above, `isTruncatedFlow`, you may run into problems when you combine the suffix `Flow` with the more conventional boolean prefix `is`. This just might be confusing for some as “Is the flow truncated?” sounds like a perfectly fine question. `flowOf`, on the other hand, is very un-problematic in my experience. You can slap it onto anything, and it will not lead to confusion. You can't read in other ways besides “Flow of ‘is truncated?’”

2024-02-15 16:29 UTC, mikehardy approved these changes

2024-02-15 17:19 UTC, merged