Test: instrumental test for NoteEditor when text is sent
ankidroid/Anki-Android pull request #15575
Opened 2024-02-18 16:25 UTC by criticalAY

…pplication

## Purpose / Description
              @criticalAY this feels like a blocker for 2.17, so I'll take it on

it would be greatly appreciated if you could follow up with a regression test in `androidTest`

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/15566#issuecomment-1950966979_

## How Has This Been Tested?
Google emualtor and ran test locally 

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-02-18 16:28 UTC, david-allison requested changes
LGTM, a few nitpicks

Could you change the commit message to:

```
test(note-editor): text shared via ACTION_SEND

Issue 15566
```

2024-02-18 16:28 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
> +class NoteEditorIntentTest {
Is there a reason you're not inheriting from `InstrumentedTest`?

2024-02-18 17:09 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        }
This method is used in the test hence I moved it to companion object

2024-02-18 17:09 UTC, criticalAY commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
> +class NoteEditorIntentTest {
Switched to `InstrumentedTest`

2024-02-18 17:12 UTC, david-allison approved these changes

2024-02-19 03:25 UTC, mikehardy approved these changes
LGTM - thank you!

2024-02-19 03:41 UTC, merged