fix: copyFileToCache NetworkOnMainThreadException
ankidroid/Anki-Android pull request #15570
Opened 2024-02-18 07:41 UTC by AnisBak

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
* Fixes [Bug] copyFileToCache: NetworkOnMainThreadException [#15446](https://github.com/ankidroid/Anki-Android/issues/15446)

## Approach
Move the execution from the main thread

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-02-18 07:48 UTC, david-allison approved these changes
Beautiful, thank you!!

2024-02-18 10:37 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                }
we have a helper for catching errors (which would be nice if it accepted a `CoroutineContext` param like `launchCatching` does)

```suggestion
                launchCatchingTask {
                    withContext(Dispatchers.IO) {
                        onSelectedPackageToImport(it.data!!)   
                    }
                }
```

2024-02-18 10:39 UTC, lukstbit requested changes

2024-02-18 10:39 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    onSelectedPackageToImport(it.data!!)
If there's an issue when handling the imported package the app shows a dialog. With this change that dialog will be shown on a background thread and it will crash the app.

https://github.com/ankidroid/Anki-Android/blob/a06d445bfcea3139accc30faa1b24c0fe214d2b0/AnkiDroid/src/main/java/com/ichi2/anki/Import.kt#L49-L54

The call to _ImportUtils.showImportUnsuccessfulDialog()_ in the method above needs to be done on the main thread which can be done by wrapping the call in _runOnUiThread {}_.

2024-02-19 03:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    onSelectedPackageToImport(it.data!!)
Great catch @lukstbit

2024-02-19 05:16 UTC, lukstbit approved these changes
Thank you!

2024-02-19 05:17 UTC, merged