fix: NPE when adding note via inten
ankidroid/Anki-Android pull request #15587
Opened 2024-02-19 07:25 UTC by criticalAY

## Purpose / Description
Can't share to AnkiDroid if an image occlusion note type is selected 

## Fixes
* Fixes #15584

## Approach
Change the note type to basic when adding an image or text via share intent  

## How Has This Been Tested?
Google emulator - API 34

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-02-19 07:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        val model = getColUnsafe.notetypes.byName("Basic")
not guaranteed to exist, especially if the user is non-English

2024-02-19 07:54 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        val model = getColUnsafe.notetypes.byName("Basic")
Is there any method to bypass it? or get the basic type?

2024-02-19 11:03 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +    @OptIn(DelicateCoroutinesApi::class)
Not sure if we want to use it, need an alternative

2024-02-19 14:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        val model = getColUnsafe.notetypes.byName("Basic")
Maybe we can make a good guess using the date of creation and filtering on `originalStockKind`

2024-02-19 15:00 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        val model = getColUnsafe.notetypes.byName("Basic")
But the current updated code seems more reliable as we get the `stockNotetype.Kind.entries`  here?

2024-02-19 20:18 UTC, david-allison requested changes
This feels too complicated (in the selection of the next note type). How about this:

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(revision 6dc9907814909457bb17f6841864d281bae5097c)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(date 1708373812607)
@@ -518,7 +518,6 @@
                     finish()
                     return
                 }
-                changeNoteTypeForAddIntent()
                 addNote = true
             }
             // image occlusion is handled at the end of this method, grep: CALLER_IMG_OCCLUSION
@@ -527,7 +526,6 @@
                 addNote = true
             }
             CALLER_ADD_IMAGE -> {
-                changeNoteTypeForAddIntent()
                 addNote = true
             }
             else -> {}
@@ -600,6 +598,15 @@
             // set information transferred by intent
             var contents: String? = null
             val tags = intent.getStringArrayExtra(EXTRA_TAGS)
+
+            // If content has been shared, we can't share to an image occlusion note type
+            if (currentNotetypeIsImageOcclusion() && (sourceText != null || caller == CALLER_ADD_IMAGE)) {
+                val model = col.notetypes.all().first {
+                    it.getInt("originalStockKind") != StockNotetype.OriginalStockKind.ORIGINAL_STOCK_KIND_IMAGE_OCCLUSION_VALUE
+                }
+                changeNoteType(model.id)
+            }
+
             if (sourceText != null) {
                 if (aedictIntent && mEditFields!!.size == 3 && sourceText!![1]!!.contains("[")) {
                     contents = sourceText!![1]!!
@@ -2063,55 +2070,6 @@
             }
         }
 
-    private fun changeNoteTypeForAddIntent() = runBlocking {
-        coroutineScope {
-            val cardType = async {
-                getValidCardType()
-            }
-            val type = cardType.await()
-            if (type != null) {
-                val model = getColUnsafe.notetypes.byName(type)
-                val newId = model?.id
-                if (model != null) {
-                    getColUnsafe.notetypes.setCurrent(model)
-                    val currentDeck = getColUnsafe.decks.current()
-                    currentDeck.put("mid", newId)
-                    getColUnsafe.decks.save(currentDeck)
-                    if (!getColUnsafe.config.getBool(ConfigKey.Bool.ADDING_DEFAULTS_TO_CURRENT_DECK)) {
-                        deckId = model.optLong("did", Consts.DEFAULT_DECK_ID)
-                    }
-                }
-            }
-        }
-    }
-
-    private suspend fun getValidCardType(): String? {
-        var cardType: String? = null
-        withCol {
-            StockNotetype.Kind.entries
-                .filter { it != StockNotetype.Kind.UNRECOGNIZED && it != StockNotetype.Kind.KIND_IMAGE_OCCLUSION }
-                .find { kind ->
-                    var containsFrontOrBack = false
-                    val stockNotetype = BackendUtils.from_json_bytes(getStockNotetypeLegacy(kind))
-                    val tmplsArray = stockNotetype.optJSONArray("tmpls")
-                    if (tmplsArray != null) {
-                        for (i in 0 until tmplsArray.length()) {
-                            val templateObj = tmplsArray.getJSONObject(i)
-                            val qfmt = templateObj.optString("qfmt", "")
-                            val afmt = templateObj.optString("afmt", "")
-                            if (qfmt.contains("{{Front}}") || afmt.contains("{{Back}}")) {
-                                cardType = stockNotetype.optString("name", "")
-                                containsFrontOrBack = true
-                                break
-                            }
-                        }
-                    }
-                    !containsFrontOrBack
-                }
-        }
-        return cardType
-    }
-
     /**
      * Update all the field EditText views based on the currently selected note type and the mModelChangeFieldMap
      */
@@ -2161,38 +2119,42 @@
         requestIOEditorCloser.launch(intent)
     }
 
-    // ----------------------------------------------------------------------------
-    // INNER CLASSES
-    // ----------------------------------------------------------------------------
-    private inner class SetNoteTypeListener : OnItemSelectedListener {
-        override fun onItemSelected(parent: AdapterView<*>?, view: View?, pos: Int, id: Long) {
-            // If a new column was selected then change the key used to map from mCards to the column TextView
-            // Timber.i("NoteEditor:: onItemSelected() fired on mNoteTypeSpinner");
-            // In case the type is changed while adding the card, the menu options need to be invalidated
-            invalidateMenu()
-            val oldModelId = getColUnsafe.notetypes.current().getLong("id")
-            val newId = mAllModelIds!![pos]
-            Timber.i("Changing note type to '%d", newId)
-            if (oldModelId != newId) {
-                val model = getColUnsafe.notetypes.get(newId)
-                if (model == null) {
-                    Timber.w("New model %s not found, not changing note type", newId)
-                    return
-                }
-                getColUnsafe.notetypes.setCurrent(model)
-                val currentDeck = getColUnsafe.decks.current()
-                currentDeck.put("mid", newId)
-                getColUnsafe.decks.save(currentDeck)
-                // Update deck
-                if (!getColUnsafe.config.getBool(ConfigKey.Bool.ADDING_DEFAULTS_TO_CURRENT_DECK)) {
-                    deckId = model.optLong("did", Consts.DEFAULT_DECK_ID)
-                }
-                refreshNoteData(FieldChangeType.changeFieldCount(shouldReplaceNewlines()))
-                setDuplicateFieldStyles()
-                mDeckSpinnerSelection!!.updateDeckPosition(deckId)
-            }
-        }
+
+    private fun changeNoteType(newId: NoteTypeId) {
+        val oldModelId = getColUnsafe.notetypes.current().getLong("id")
+        Timber.i("Changing note type to '%d", newId)
+        if (oldModelId != newId) {
+            val model = getColUnsafe.notetypes.get(newId)
+            if (model == null) {
+                Timber.w("New model %s not found, not changing note type", newId)
+                return
+            }
+            getColUnsafe.notetypes.setCurrent(model)
+            val currentDeck = getColUnsafe.decks.current()
+            currentDeck.put("mid", newId)
+            getColUnsafe.decks.save(currentDeck)
+            // Update deck
+            if (!getColUnsafe.config.getBool(ConfigKey.Bool.ADDING_DEFAULTS_TO_CURRENT_DECK)) {
+                deckId = model.optLong("did", Consts.DEFAULT_DECK_ID)
+            }
+            refreshNoteData(FieldChangeType.changeFieldCount(shouldReplaceNewlines()))
+            setDuplicateFieldStyles()
+            mDeckSpinnerSelection!!.updateDeckPosition(deckId)
+        }
+    }
 
+    // ----------------------------------------------------------------------------
+    // INNER CLASSES
+    // ----------------------------------------------------------------------------
+    private inner class SetNoteTypeListener : OnItemSelectedListener {
+        override fun onItemSelected(parent: AdapterView<*>?, view: View?, pos: Int, id: Long) {
+            // If a new column was selected then change the key used to map from mCards to the column TextView
+            // Timber.i("NoteEditor:: onItemSelected() fired on mNoteTypeSpinner");
+            // In case the type is changed while adding the card, the menu options need to be invalidated
+     [...]

2024-02-20 02:02 UTC, criticalAY commented
@david-allison I made one more change: If there is no note type having an edit field then the application still crashes (unlikely to happen but I added a check)

2024-02-20 02:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        if (oldModelId != newId) {
invert & return early

2024-02-20 02:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                sourceText = null
This also needs to handle the line: `if (caller == CALLER_ADD_IMAGE) handleImageIntent(intent)`

2024-02-20 02:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                        it.getInt("originalStockKind") != StockNotetype.OriginalStockKind.ORIGINAL_STOCK_KIND_IMAGE_OCCLUSION_VALUE
Note: I have a PR which defines `isImageOcclusion`. No action needed, but may want a follow-up after it's merged

https://github.com/ankidroid/Anki-Android/pull/15583/files#diff-11356b3bcc63f8b8148cba7b24bf22a55daa6b4aa99f6e7e581253f424682fa9

2024-02-20 02:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        if (getColUnsafe.config.getBool(ConfigKey.Bool.ADDING_DEFAULTS_TO_CURRENT_DECK).not()) {
```
        if (!getColUnsafe.config.getBool(ConfigKey.Bool.ADDING_DEFAULTS_TO_CURRENT_DECK)) {
```

2024-02-20 02:32 UTC, david-allison approved these changes

2024-02-20 02:32 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="missing_note_type">No note type found to add text/image</string>
```suggestion
    <string name="missing_note_type">No note type found</string>
```

2024-02-20 11:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                        it.getInt("originalStockKind") != StockNotetype.OriginalStockKind.ORIGINAL_STOCK_KIND_IMAGE_OCCLUSION_VALUE
Optional: merged now

2024-02-20 12:07 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                        it.getInt("originalStockKind") != StockNotetype.OriginalStockKind.ORIGINAL_STOCK_KIND_IMAGE_OCCLUSION_VALUE
Will change the method

2024-02-20 13:05 UTC, mikehardy approved these changes
LGTM - thank you - just did a string sync to push string changes through but will follow with another one to get this change in, strings are clear between github / crowdin right now

2024-02-20 14:35 UTC, lukstbit commented
@criticalAY 
Small conflict from merging other PRs:

 > Task :AnkiDroid:compilePlayDebugKotlin FAILED
> e: file:///home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:601:59 Unresolved reference: StockNotetype

2024-02-20 15:22 UTC, mikehardy commented
@criticalAY yeah - this one needs a fixup anyway, so you have a chance to switch to David's method and that likely fixes the thing anyway

2024-02-20 15:38 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                        it.getInt("originalStockKind") != StockNotetype.OriginalStockKind.ORIGINAL_STOCK_KIND_IMAGE_OCCLUSION_VALUE
I've integrated this change locally as it fixes the compile conflict from in-flight PRs and I'm going to force push it now (apologies in advance @criticalAY please forgive me...) so it unblocks this PR which unblocks strings which unblocks beta6...

2024-02-20 15:38 UTC, mikehardy commented
fixed up + pushed + set for auto-merge via queue when CI passes

2024-02-20 16:08 UTC, merged