[Clean Up] : unexpected end of file
ankidroid/Anki-Android pull request #15633
Opened 2024-02-24 00:09 UTC by ro4i7

## Purpose / Description
fix warning of property naming conversion

## Fixes
* Fixes #13282 

## Approach
emulator

## How Has This Been Tested?
emulator

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-02-24 15:46 UTC, david-allison requested changes
The commit does not match the commit message

2024-02-25 01:17 UTC, david-allison approved these changes
Looks good, thanks!

2024-02-25 08:14 UTC, lukstbit requested changes
Thank you for contributing, I've left two requests and then we could merge this.

2024-02-25 08:14 UTC, lukstbit commented on annotations/README.md
>  ## Modificiation Instructions
Could you please also fix the typo for this word?

2024-02-25 08:14 UTC, lukstbit commented on annotations/README.md
> +These annotations are not yet supported by our automated tooling.
Why was this line changed?

2024-02-25 08:58 UTC, ro4i7 commented on annotations/README.md
> +These annotations are not yet supported by our automated tooling.
No, it's same as original one.

2024-02-25 09:06 UTC, lukstbit commented on annotations/README.md
> +These annotations are not yet supported by our automated tooling.
Yes, you added a new line at the end and Github showed it as changed.

2024-02-25 09:24 UTC, lukstbit approved these changes
All good, thanks for making the change!

2024-02-29 18:01 UTC, merged