return opChanges in setUserFlagForCards
ankidroid/Anki-Android pull request #15632
Opened 2024-02-23 22:45 UTC by BrayanDSO

## Purpose / Description

~~Gonna need it to fix a bug~~ Actually, it already fixes the bug of the card browser not being updated after card changes in the new previewer

## Approach

match the desktop code and return opChanges in setUserFlagForCards

## How Has This Been Tested?

[el fuego.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/83f105e5-322f-4d18-8e9b-0b36ddccdd27)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-02-23 23:12 UTC, david-allison requested changes
Small request to reduce the opChangee being forgotten about

2024-02-23 23:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +    fun setUserFlagForCards(cids: Iterable<Long>, flag: Int): OpChangesWithCount {
Could you `@CheckResult` here?

2024-02-23 23:53 UTC, david-allison approved these changes
Perfect, cheers!

2024-02-24 15:47 UTC, mikehardy approved these changes
LGTM - this looks pickable as well for 2.17

2024-02-24 16:03 UTC, merged