Feature: Allow changing deck name in statistics screen
ankidroid/Anki-Android pull request #15648
Opened 2024-02-24 21:15 UTC by criticalAY

## Purpose / Description
Reintroduce Deck Selector to the Statistics Page

## Fixes
* Fixes #15197

## Approach
Use M3 button to allow user to change deck, not using the spinner here as the deck name is already displayed in the text field 

## How Has This Been Tested?
Google emulator  API 34
Tested the orientation change too

![image](https://github.com/ankidroid/Anki-Android/assets/48384865/d8d5ba55-e6d6-41c5-8899-22a177dc8448)
[test-stats.webm](https://github.com/ankidroid/Anki-Android/assets/48384865/886da4fc-b279-4ac0-9ac7-3e1ea18b8cea)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-02-25 03:28 UTC, david-allison reviewed
Is there a reason you didn't go with the spinner in the `ActionBar`?

2024-02-25 04:48 UTC, criticalAY commented
Ohh that's because the deck name is already shown in the page why to have it at top would that be a good ui ? I did mention that in my pr template

2024-02-25 05:37 UTC, david-allison commented
I feel this significantly reduces scrolling space at the bottom. 

1. Could we move it into the menu (as the main action)?
2. Could you send a screenshot of the spinner to see if we can make it work? The inconsistency is unusual

2024-02-26 23:38 UTC, criticalAY commented
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/9e6ed00c-054a-4003-b551-6352ba982020)

2024-02-26 23:50 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.kt
> +            // Spinner has white text color in light theme, we change it only for StatisticsActivity
One issue here, we want this condition to execute only if theme is light

2024-02-26 23:55 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.kt
> +            // Spinner has white text color in light theme, we change it only for StatisticsActivity
Ok found it in `Themes.kt`

2024-02-27 00:36 UTC, criticalAY commented
![image-1.png](https://github.com/ankidroid/Anki-Android/assets/48384865/1f142e9a-bb4f-47dc-ac7e-39fcdb2b43b0)

Updated screenshot

2024-02-27 06:49 UTC, david-allison requested changes
Visually, this looks awesome, thank you!

2024-02-27 06:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.kt
> +            if (context is StatisticsActivity && (Themes.currentTheme.id == Theme.LIGHT.id)) {
can this be a style instead?

2024-02-27 06:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +        toolbar.apply {
optional: `val supportActionBar = enableToolbar()` as that saves a line later on and removes `supportActionBar == null`

2024-02-27 06:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +            toolbarSpinner.visibility = View.VISIBLE
`isVisible = true` reads better to me

2024-02-27 06:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/StatisticsActivity.kt
> +    var deckNameLive = MutableLiveData<String>()
is it possible to do this in a `ViewModel`?

2024-02-27 06:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/StatisticsActivity.kt
> +        collection = col
Don't save the collection, use `withCol { }`

2024-02-27 06:49 UTC, david-allison commented on AnkiDroid/src/main/res/layout/page_fragment.xml
> +
revert line change

2024-02-27 06:49 UTC, david-allison commented on AnkiDroid/src/main/res/layout/page_fragment.xml
> +            app:popupTheme="@style/ActionBar.Popup" />
Flagging for re-review & Reviewer 2, I can't immediately think of a clean way to manage this

2024-02-27 07:43 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.kt
> +            if (context is StatisticsActivity && (Themes.currentTheme.id == Theme.LIGHT.id)) {
Considering it is used only in stats page, not a feasible  option.

2024-02-27 07:46 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +        toolbar.apply {
This is an fragment plus ` initializeActionBarDeckSpinner(it, supportActionBar)` would need a null check anyway or the risky `!!`

2024-02-27 07:52 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/StatisticsActivity.kt
> +        collection = col
```
withCol {
                    initializeActionBarDeckSpinner(this, supportActionBar)
                    launchCatchingTask { selectDeckById(deckId, true) }
                }
```
we can't do this here as `initializeActionBarDeckSpinner` runs on MainThread

2024-02-27 07:53 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/StatisticsActivity.kt
> +        collection = col
or are you talking about just this portion here
```
override fun onCollectionLoaded(col: Collection) {
        super.onCollectionLoaded(col)
        launchCatchingTask {
            withCol{
                collection = this
            }
        }

    }
```

2024-02-27 09:08 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.kt
> +            if (context is StatisticsActivity && (Themes.currentTheme.id == Theme.LIGHT.id)) {
I'll leave this one open for reviewer 2

2024-02-27 09:12 UTC, david-allison requested changes

2024-02-27 09:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/StatisticsActivity.kt
> +                }
this no longer needs a `withCol`, I believe it can just be:

```kotlin
            launchCatchingTask {
                initializeStatsBarDeckSpinner(supportActionBar)
                selectDeckById(deckId, true)
            }
```

2024-02-27 09:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/StatisticsActivity.kt
> +    }
setDeckName?

2024-02-27 09:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +        (activity as? StatisticsActivity)?.viewModel?.deckName?.observe(
can't you directly access the `ViewModel` here?

2024-02-27 12:28 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.kt
> +            if (context is StatisticsActivity && (Themes.currentTheme.id == Theme.LIGHT.id)) {
That's what attributes/styles are for. Changing View properties dinamically is almost always unnecessary and break XML previews

2024-02-27 14:24 UTC, criticalAY commented on AnkiDroid/src/main/res/layout/page_fragment.xml
> +            app:popupTheme="@style/ActionBar.Popup" />
Resolved will push it

2024-02-27 14:27 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.kt
> +            if (context is StatisticsActivity && (Themes.currentTheme.id == Theme.LIGHT.id)) {
If we apply it from Themes then it is also used in CardBrowser where it will be affected, we want the text black only in the Stats fragment as there the Toolbar background is white, we can create style but that would also need to be applied from the kotlin file

2024-02-27 14:27 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.kt
> +            if (context is StatisticsActivity && (Themes.currentTheme.id == Theme.LIGHT.id)) {
If there is any other solution or workaround then I am ready to apply it

2024-02-27 21:14 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.kt
> +            if (context is StatisticsActivity && (Themes.currentTheme.id == Theme.LIGHT.id)) {
> we can create style but that would also need to be applied from the kotlin file

Are you really sure of that?

2024-02-27 21:16 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.kt
> +            if (context is StatisticsActivity && (Themes.currentTheme.id == Theme.LIGHT.id)) {
There is a condition for Stats screen so yes I am sure

2024-02-27 21:35 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.kt
> +            if (context is StatisticsActivity && (Themes.currentTheme.id == Theme.LIGHT.id)) {
And the only possibility of implementing this is by adding a check inside an adapter?

2024-02-27 21:39 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +        webView.evaluateJavascript(javascriptCode, null)
if possible, add an AndroidTest to get any backend breakages

2024-02-27 21:53 UTC, BrayanDSO commented
This likely will need more feedback rounds than I have availability for. Leaving to the other reviewers

2024-02-28 06:29 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.kt
> +            if (context is StatisticsActivity && (Themes.currentTheme.id == Theme.LIGHT.id)) {
I am trying something with toolbar and if that work we can escape it

2024-02-28 11:31 UTC, criticalAY commented
@BrayanDSO Is this ok? I made some changes

2024-04-21 15:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
>  class Statistics : PageFragment(R.layout.statistics) {
Add a comment linking to the activity

2024-04-21 15:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +                val supportActionBar = (activity as? StatisticsActivity)?.supportActionBar
We've recently introduced `requireAnkiActivity()`

2024-04-21 15:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.kt
> +            }
Don't do this here, do it inside `StatisticsActivity`

2024-04-21 15:56 UTC, david-allison commented on AnkiDroid/src/main/res/layout/page_fragment.xml
> +        app:navigationIcon="?attr/homeAsUpIndicator"/>
nit: line noise

2024-04-21 15:56 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
> +            get(StatisticsActivity::class.java)
nit: add a trailing comma

2024-04-21 15:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/StatisticsActivity.kt
> +    val deckName: LiveData<String> = _deckName
Any advantage of `LiveData` over `Flow`?

I've been aiming to have 0 `android` dependencies from the `ViewModels`

2024-04-21 15:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/StatisticsActivity.kt
> +    var deckId: DeckId = 0
What does 0 mean? `ALL_DECKS`

2024-04-21 15:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +            R.layout.statistics_fragment_layout,
Can this not be passed into the constructor?

2024-04-21 15:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
>  class Statistics : PageFragment(R.layout.statistics) {
Does `R.layout.statistics` still need to exist?

2024-04-21 16:16 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/StatisticsActivity.kt
> +    var deckId: DeckId = 0
Not all decks it would select the default deck if no deck is there

2024-04-21 16:16 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
>  class Statistics : PageFragment(R.layout.statistics) {
Ahh there are two layouts now, we will need only one

2024-04-21 16:53 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.kt
> +            }
Stats activity doesn't directly use it, and the text is part of the Adapter layout it would be way more complex, what I have done now is that passed the styles as constructor

2024-05-21 18:33 UTC, david-allison requested changes
The control in the action bar needs a "down caret" so it appears selectable

2024-05-21 20:11 UTC, criticalAY commented
It is there but I suspect not visible due to the toolbar color will override it

2024-06-19 14:04 UTC, lukstbit commented
I've fixed the conflicts and made some changes to implement the feature(basically, just change the current selected deck and reload the embedded WebView). The new behavior follows the desktop behavior where selecting a deck in the statistics screen doesn't change the html input at the top.

Some images(note that I added a background for the decks spinner area to differentiate it a bit from the rest of the content, I think it looks better):

<img src="https://github.com/ankidroid/Anki-Android/assets/52494258/810fb2d1-1c5b-46fb-ad0f-bfca49870638" width="350px" height="720px" /><img src="https://github.com/ankidroid/Anki-Android/assets/52494258/0090f721-9670-4923-b6e8-57bc1dcf073e" width="350px" height="720px" />

2024-06-19 14:12 UTC, david-allison commented
I feel I'm missing something

Where do you select a deck in the screenshots? I'd have expected it in the app bar

2024-06-19 14:17 UTC, lukstbit commented
> Where do you select a deck in the screenshots? I'd have expected it in the app bar

It's the Spinner at the bottom(in the picture there was a deck B selected).

Besides the desktop UI that places the deck selector at the bottom it was much easier to implement this way(I would prefer to keep the title as it is).

2024-06-19 14:22 UTC, david-allison approved these changes
I don't like it design wise, but it's better than it was. Let's do it

2024-06-19 15:24 UTC, user1823 commented
> The new behavior follows the desktop behavior where selecting a deck in the statistics screen doesn't change the html input at the top.

But, does it mean that changing the deck in the Stats page changes the current deck? If so, it will affect the reviewer if the user goes to the Stats page and changes the deck there in the middle of doing reviews.

In https://github.com/ankidroid/Anki-Android/issues/15197#issuecomment-1936853509, David wrote:
> Personally: if I switch decks in the reviewer or the Card Browser, I don't want the current review session's deck to change

(Here, "decks in the reviewer" should be read as "decks in the Stats page" IMO.)

Also, design-wise, I liked the design by criticalAY.

2024-06-19 15:42 UTC, lukstbit commented
> But, does it mean that changing the deck in the Stats page changes the current deck? If so, it will affect the reviewer if the user goes to the Stats page and changes the deck there in the middle of doing reviews.

My quick test just now showed the same behavior on desktop.  Do you see a different behavior?
If it is the same I don't think we should go another way(although the behavior is not nice).

2024-06-19 15:49 UTC, user1823 commented
Well, what you are suggesting here is exactly what I suggested in https://github.com/ankidroid/Anki-Android/issues/15197#issuecomment-1925761823. Though, we will also need to add code for refreshing the reviewer when the user returns to the reviewer (see the linked comment).

However, I later got convinced by David's comment that users won't want their reviews to be affected by changing the deck in Stats page. Also, see that Damien also supports changing the search query and is welcoming a PR to do that in Anki.

2024-06-20 11:13 UTC, lukstbit commented
I made some changes:

- reverted to the popular design
- the deck is changed/statistics are shown without changing the selected deck for the rest of the app

<img src="https://github.com/ankidroid/Anki-Android/assets/52494258/fe0833e7-418c-4137-ba37-7d8d52142d64" width="320px" height="720px" /><img src="https://github.com/ankidroid/Anki-Android/assets/52494258/438668bc-7fae-42ec-b338-b8081de65413" width="320px" height="720px" />

2024-08-19 03:15 UTC, mikehardy approved these changes
Seems fine to me - left one comment where I'd like anki upstream to mark the form we are using in the webview as an external API otherwise good to go for me - going to ping David one final time in case he disagrees with the final couple pushes, otherwise let's get this in

2024-08-19 03:15 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +        var textBox = [].slice.call(document.getElementsByTagName('input'), 0).filter(x => x.type == "text")[0];
this may be overkill, but if it is not already noted in anki source code via a comment in the related file that generates this form that we are programmatically manipulating here - can you link an issue or PR that adds a comment to that line that says "this form is an external API and should not be changed - other clients e.g. AnkiDroid programmatically update this form"

2024-08-19 09:08 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +            }
I would prefer `requireNotNull` or `finish` instead, I don't believe the screen will work if this is unset, but it won't close either

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt b/AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt	(revision 1b40e43b5eddfceb477bce379056334a6c2fffb9)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt	(date 1724058383532)
@@ -37,6 +37,7 @@
 import com.ichi2.libanki.DeckId
 import com.ichi2.libanki.DeckNameId
 import com.ichi2.libanki.utils.TimeManager
+import com.ichi2.utils.BundleUtils.getNullableLong
 
 class Statistics :
     PageFragment(R.layout.statistics),
@@ -78,11 +79,7 @@
                 changeDeck(selectedDeck.name)
             }
         } else {
-            val savedDeckId = savedInstanceState.getLong(KEY_DECK_ID, -1)
-            // check only for tests
-            if (savedDeckId == -1L) {
-                return
-            }
+            val savedDeckId = savedInstanceState.getNullableLong(KEY_DECK_ID) ?: return
             requireActivity().launchCatchingTask {
                 deckSpinnerSelection.initializeStatsBarDeckSpinner()
                 select(savedDeckId)
```

2024-08-19 09:16 UTC, david-allison approved these changes
Approve after Mike's comment is taken care of

2024-08-19 09:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +        if (foundPosition >= 0) spinner.setSelection(foundPosition)
Untested

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt b/AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt	(revision 1b40e43b5eddfceb477bce379056334a6c2fffb9)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt	(date 1724058537675)
@@ -126,16 +126,15 @@
      * Given the [deckId] look in the decks adapter for its position and select it if found.
      */
     private fun select(deckId: DeckId) {
-        var foundPosition = INVALID_POSITION
         // find the selected position in the adapter and manually select it
+        val itemToSelect = items.withIndex().firstOrNull { it.value.id == deckId } ?: return
+        spinner.setSelection(itemToSelect.index)
+    }
+    
+    private val items get() = sequence {
         for (i in 0 until spinner.adapter.count) {
-            val item = spinner.adapter.getItem(i) as DeckNameId
-            if (item.id == deckId) {
-                foundPosition = i
-                break
-            }
+            yield(spinner.adapter.getItem(i) as DeckNameId)
         }
-        if (foundPosition >= 0) spinner.setSelection(foundPosition)
     }
 
     /**
```

2024-08-20 17:42 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +        if (foundPosition >= 0) spinner.setSelection(foundPosition)
Looks cleaner so I modified the code.

2024-08-20 17:42 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +            }
Forgot about that method, thanks!

2024-08-22 16:57 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +        var textBox = [].slice.call(document.getElementsByTagName('input'), 0).filter(x => x.type == "text")[0];
Agreed it may be stepping out of bounds, however if you don't ask you don't get. We're all reasonable people and this seems like a reasonable ask - to just mark it in comments that AnkiDroid uses this programmatically. We're not asking them to never change it or anything, we're just asking for a polite heads up if they do, in my mind

2024-08-22 16:58 UTC, mikehardy commented
Note for me mainly as I look to merge all things merge-able and I scan this, only outstanding thread is this, hoping for a PR or issue to mark the code generating the form we twiddle here upstream so we get a note if they modify it: https://github.com/ankidroid/Anki-Android/pull/15648#discussion_r1727502723

2024-09-10 19:04 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +        var textBox = [].slice.call(document.getElementsByTagName('input'), 0).filter(x => x.type == "text")[0];
I don't mind such comments when required, but I think AD could probably also make an effort to make this less fragile. You're currently just looking for the first input box on the page, which will prevent us from adding any others before it should we wish to in the future. Instead of just adding a comment, if you also add an id to the input element, then you can identify it even if it moves around on the page relative to other input elements.

2024-09-16 16:05 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +        var textBox = [].slice.call(document.getElementsByTagName('input'), 0).filter(x => x.type == "text")[0];
Attempted to move the linked PR forward here --> https://github.com/ankitects/anki/pull/3398/files#r1761436611

With some luck I did that correctly (or close enough to fixup quickly and merge there) - then the PR here should go by element ID not by "first text box", once Anki-Android-Backend has the change ingested

2024-09-16 16:06 UTC, mikehardy commented
Current status: I think we're really close here. Only sticking point is cross-repo programmatic usage of the web form and that *will* resolve but it may take an iteration or so

2024-09-16 16:26 UTC, user1823 commented
I think that this PR can be merged now as it is and the change from "first text box" to ID can be made in a subsequent PR.

Reasoning:
Even if dae merges the linked PR today, we likely won't get the change in AnkiDroid until the next stable release of Anki, which seems to be at least a month away. In my opinion, it isn't wise to block this PR just for that small change, which we can easily make once the backend update is available.

2024-09-16 16:55 UTC, merged

2024-10-14 23:33 UTC, Vermeille commented
Why is it a text field instead of a drop-down selector? Any particular reason?

2024-10-15 00:24 UTC, david-allison commented
@Vermeille Did you try our 2.19 beta? 

It's a full-screen list/selection. This allows more functionality and tree-style decks, rather than a dropdown list.

The text field which is seen comes from the Anki backend, and is mostly superseded by the dialog introduced in this PR.

2024-10-15 00:34 UTC, Vermeille commented
I did not :) Glad to see things improving!