fix: allow seeking in `<audio>`, `<video>` and `<object>` sources
ankidroid/Anki-Android pull request #15644
Opened 2024-02-24 16:55 UTC by BrayanDSO

## Purpose / Description

To be able to use a server to intercept POST requests in the reviewer, the base url of the reviewer isn't the media directory anymore, so files aren't automatically using the `file:///` protocol

## Fixes
* Fixes #15631

## Approach

It uses the `file:///` scheme in the tag sources, which allow seeking and has a better performance than using HTTP partial content (I tried https://github.com/BrayanDSO/Anki-Android/tree/fix_audio_seeking)

## How Has This Been Tested?

### Please note that I removed the video audio because it was copyrighted

Emulator 31:

[yeah-boy_3drhy0gn.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/7cb784c8-a3a8-402b-b431-e998d7e182e4)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-02-24 17:09 UTC, BrayanDSO commented
for the future, this can be made in JavaScript in the reviewer port, since most of its render is in JavaScript.

2024-02-25 01:07 UTC, david-allison requested changes
Test request

2024-02-25 01:07 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
> +    val hasMadeChanges =
Could you test case-sensitivity?

2024-02-25 18:33 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
> +    val hasMadeChanges =
added it, and a bunch of other tests

2024-02-25 21:31 UTC, mikehardy approved these changes
All seems reasonable as I think through it, test support looks pretty solid.
Does this work for you David ?

2024-02-26 04:21 UTC, david-allison approved these changes
Checked this, added a test and I'm happy

2024-02-26 20:33 UTC, david-allison commented
force pushed to fix CI

2024-02-26 21:11 UTC, merged