feat(libanki): setDueDate
ankidroid/Anki-Android pull request #15699
Opened 2024-02-28 02:02 UTC by david-allison

https://github.com/ankitects/anki/blob/7784321b90be4ed0b9a7cc157cd88295722cb826/pylib/anki/scheduler/base.py#L205-L224

Prep for #14729

2024-02-28 02:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
> +        }
I'm keeping strictly to the libAnki structure, rather than using Kotlin-based idioms

2024-02-28 17:15 UTC, david-allison commented
@snowtimeglass will be providing a better 'date range' icon, but I wanted to start code reviews while this was pending

2024-02-28 17:53 UTC, david-allison commented
My main requests:

* suggestion for tablet mode (maybe a different layout for date range)
* help with colors in dark mode (or allowing this to go through with an expected follow-up)

2024-02-29 08:17 UTC, snowtimeglass commented
Though the dots on the (updated) left icon has the same stroke thickness (2dp) as the line on the right icon, it may look somewhat smaller, perhaps because of its short width, contrast with the calendar, and the large whitespace.

How about trying out the following 3dp dot version.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/81478fd3-dc19-4038-96f8-5d35252c4642)

![calendar with single dot  3dp dot ver](https://github.com/ankidroid/Anki-Android/assets/10436072/3a934426-145b-4ad0-9aa7-85b65d6b40b1)
(SVG file)

2024-02-29 08:27 UTC, david-allison commented
For visual consistency, the dot and the bar should be the same height, is that feasible?
I did prefer my original 'dot' at 3px

2024-02-29 08:40 UTC, snowtimeglass commented
Though it may be acceptable to enlarge the dot as "one point emphasis", but if they (dot and line) work well with the same thickness, that is of course fine too.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/149430f2-b335-4e38-bef3-a9aec2b07170)
![calendar with range  3dp plain](https://github.com/ankidroid/Anki-Android/assets/10436072/e479bcfe-d3cb-4378-890d-a4b1febd557f)

2024-02-29 08:46 UTC, david-allison commented
LGTM, do you have the SVGs available?

2024-02-29 08:54 UTC, snowtimeglass commented
Ah, I misunderstood the above images can be saved as SVG. I'll prepare the zip file now.

2024-02-29 09:05 UTC, snowtimeglass commented
Here it is.
[calendar icons [3dp ver].zip](https://github.com/ankidroid/Anki-Android/files/14445470/calendar.icons.3dp.ver.zip)

2024-02-29 16:00 UTC, FubayashiKazue commented
Looks good! The checkbox outline in dark mode for "change interval to match" is dark in the previews. Could maybe be changed to a white/grey outline like the rest of the checkboxes in the app.

2024-03-01 07:23 UTC, user1823 commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +        >Change interval to match</string>
```suggestion
        >Set the interval to the same value</string>
```
The previous wording was confusing. I think that the suggested wording is clearer.

2024-03-02 07:02 UTC, snowtimeglass commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +        >Set the interval to the same value</string>
How about the following changes?

- Omit "the":
`Set interval to same value`

- Replace "value" with "days"(or "day(s)"):
`Set interval to same days`

2024-03-02 08:09 UTC, user1823 commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +        >Set the interval to the same value</string>
We can drop "the" but "same days" doesn't look grammatically correct.

2024-03-03 00:41 UTC, snowtimeglass commented
In this screen, the two control boxes appear to be a bit too far apart.  It could affect usability of input, too. 
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/7df2e79c-53fc-4d83-8282-3bf12c4d35ba)
How about setting a maximum width of the distance between the two boxes (and maybe a maximum width of the box in the one dot calendar tab).

2024-03-03 05:14 UTC, david-allison commented
@snowtimeglass Thanks! 

Did some tablet-based work yesterday for the screenshot you're referring to, but it's obviously not sufficient

I'm not sure I understand what you're proposing, could you send over a quick sketch?

2024-03-03 05:35 UTC, david-allison commented
Thinking about it, I suspect we might be better off if we fixed the maximum width of the dialog to something reasonable

I'm not sure if that goes against material design

2024-03-03 05:42 UTC, snowtimeglass commented
It may be better.

For now, quick sketches are as follows:
1. current
2. what I was trying to say, pattern A
3. what I was trying to say, pattern B
4. a different pattern (that I was leaning toward until I heard your new idea)

![image](https://github.com/ankidroid/Anki-Android/assets/10436072/bcb8ca62-9dd2-4343-8bad-2ae53a08d566)

2024-03-03 17:52 UTC, david-allison commented
Improved: 
<img width="471" alt="Screenshot 2024-03-03 at 17 52 05" src="https://github.com/ankidroid/Anki-Android/assets/62114487/f1b5e325-4ebe-427d-bf1f-9fa2358fd457">

Constrained to 450dp on tablets, or 90% of the width of the screen if smaller

2024-03-08 14:21 UTC, BrayanDSO requested changes

2024-03-08 14:21 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
> +                (requireActivity() as AnkiActivity).openUrl(R.string.link_set_due_date_help)
Rebase this PR into main to use AndroidUtils::Fragment.openUrl to avoid the `AnkiActivity` dependency

2024-03-08 14:21 UTC, BrayanDSO commented on AnkiDroid/src/main/res/layout/set_due_date_range.xml
> +        android:textSize="24dp"
always sp for text
```suggestion
        android:textSize="24sp"
```

2024-03-08 14:21 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
> +        }
Not sure if you had tried this:

```suggestion
    class SelectSingleDateFragment : Fragment(R.layout.set_due_date_single) {

        private val viewModel: SetDueDateViewModel by activityViewModels<SetDueDateViewModel>()
```

2024-03-08 14:21 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateViewModel.kt
> +    }
why not actually doing this in `init {}`?

2024-03-08 14:22 UTC, BrayanDSO commented
those can expand without limits:

[Screen_recording_20240308_110846.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/4efef98e-9baa-40e1-b5d0-2b630dab0b24)

2024-03-08 14:23 UTC, BrayanDSO commented
The second tab input boxes are cut while the tab is slided.

Using `Show card in` in a separate title, like the second tab does, should match both tabs height and fix that, while increasing consistency

[Screen_recording_20240308_110526.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/2bb19d7c-3433-4582-8812-04de4c88fcef)

2024-03-08 14:25 UTC, BrayanDSO commented
![image](https://github.com/ankidroid/Anki-Android/assets/69634269/061f3ada-3f49-4a13-a94a-4eebdee1c3cb)

1. Is `---` universally understandable between languages to indicate `to`?
2. Does `days` need to be repeated twice?

2024-03-08 15:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
> +        }
I hadn't, thanks

2024-03-08 16:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateViewModel.kt
> +    }
* viewModel is shared between fragments
* Some sub-fragments do not have knowledge of the `cardIds`, only the dialog does

2024-03-08 16:28 UTC, david-allison commented
Doesn't fit inside the box, so it'd be better as a TextView

<img width="328" alt="Screenshot 2024-03-08 at 16 28 27" src="https://github.com/ankidroid/Anki-Android/assets/62114487/024797ba-f7ce-4682-a288-109098ea6d66">

2024-03-08 23:16 UTC, david-allison commented
Specifically; I'd (mildly) rather keep `days` in both boxes, I feel the remainder of comments are addressed

2024-03-09 01:05 UTC, snowtimeglass commented
> 1. Is `---` universally understandable between languages to indicate `to`?

In Japanese, for example, it is a bit difficult to understand naturally, I guess. It would be natural to use "～" character instead. So, it may be better to make it translatable.

(Perhaps it might also be desirable to reconsider replacing it with "From" and "To" in the box for more universal understandability and translatability.)

> 2. Does `days` need to be repeated twice?

It may not be necessary, but it's more easier to understand, I think.

2024-03-09 03:48 UTC, david-allison commented
1. I've made the en-dash translatable

2024-03-14 03:23 UTC, snowtimeglass requested changes

2024-03-14 03:23 UTC, snowtimeglass commented on AnkiDroid/src/main/res/drawable/calendar_single_day.xml
> +        android:strokeWidth="0.52891105"
```suggestion
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path
        android:pathData="M6,1L6,3L4,3C3,32.005,42,5L2,20C2,213,21.9994,21.999L4,204,7L20,7L20,20L4,204,22L20,22C21,2222,2122,20L22,1122,5C22,420.999,320,3L18,3L18,1L16,1L16,3L8,3L8,1ZM6,9L6,11.5L8.5,11.5L8.5,9Z"
```

My bad (the red range). I have revised the part for the following points.

- Standardize the sizes (24dp × 24dp, 24×24 viewport) and the coordinates
- Remove the unnecessary `strokeWidth` information

[[Revised] calendar_single_day.xml.zip](https://github.com/ankidroid/Anki-Android/files/14596212/Revised.calendar_single_day.xml.zip)
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/bdd0cbaa-ccc7-40b0-84a9-5fbf3e06549e" width="500px">

2024-03-14 07:33 UTC, david-allison commented
Something went wrong with the patch, I'll investigate

2024-03-14 13:28 UTC, david-allison commented
@snowtimeglass can you send the SVGs rather than the XML files?

2024-03-14 13:31 UTC, david-allison commented
The attached files were good, the patch was bad

2024-03-14 15:57 UTC, BrayanDSO approved these changes
Some issues with configuration changes, but not worth blocking:

Here, the inputbox in the first tab doesn't retain the value after configuration changes, while the second one does

[config changes.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/dde648b0-a23f-4d52-a970-ed90d7831ca7)

2024-03-14 15:57 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
> +            viewModel.updateDueDate()
If the activity is recreated for some reason (configuration change, app freeing resources, etc) during this, the task will be cancelled, since it''s running under `activity.lifecycleScope`.

Not drastic, so a TODO is enough for now

2024-03-14 16:01 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
> +            viewModel.updateDueDate()
With apologies, what's the best way of fixing this? 

Have `updateDueDate()` perform `launch` and `.join()` on the returned job?

2024-03-14 16:06 UTC, BrayanDSO requested changes
actually, the snackbar feedback doesn't show up if a large number of cards is updated (sorry for the video in the wrong orientation), although the due dates are updated

[huh.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/f634982d-8698-45e0-9e73-411a841e1188)

2024-03-14 16:44 UTC, david-allison commented
Since I'm rebasing this one in:

```patch
Subject: [PATCH] AA
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt	(revision 6fdda6d98033ea27a75cc3cfc48e44c63a0456cf)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt	(revision 41eed68436b16530086dc514f17969afd40dc131)
@@ -32,6 +32,7 @@
 import androidx.core.app.NotificationCompat
 import androidx.core.app.PendingIntentCompat
 import androidx.fragment.app.DialogFragment
+import androidx.fragment.app.Fragment
 import androidx.fragment.app.FragmentManager
 import com.google.android.material.color.MaterialColors
 import com.ichi2.anim.ActivityTransitionAnimation
@@ -589,3 +590,8 @@
         private const val SIMPLE_NOTIFICATION_ID = 0
     }
 }
+
+fun Fragment.requireAnkiActivity(): AnkiActivity {
+    return requireActivity() as? AnkiActivity?
+        ?: throw java.lang.IllegalStateException("Fragment $this not attached to an AnkiActivity.")
+}
Index: AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt b/AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt	(revision 6fdda6d98033ea27a75cc3cfc48e44c63a0456cf)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt	(revision 41eed68436b16530086dc514f17969afd40dc131)
@@ -2,6 +2,7 @@
 
 package com.ichi2.anki
 
+import android.app.Activity
 import android.content.Context
 import android.util.DisplayMetrics
 import android.widget.Toast
@@ -28,6 +29,11 @@
         Toast.makeText(requireContext(), textResource, if (shortLength) Toast.LENGTH_SHORT else Toast.LENGTH_LONG).show()
     }
 
+    context (Activity)
+    fun showThemedToast(@StringRes textResource: Int, shortLength: Boolean) {
+        Toast.makeText(this@Activity, textResource, if (shortLength) Toast.LENGTH_SHORT else Toast.LENGTH_LONG).show()
+    }
+
     fun getDensityAdjustedValue(context: Context, value: Float): Float {
         return context.resources.displayMetrics.density * value
     }
Index: AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt	(revision 6fdda6d98033ea27a75cc3cfc48e44c63a0456cf)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt	(revision 41eed68436b16530086dc514f17969afd40dc131)
@@ -36,10 +36,12 @@
 import com.google.android.material.tabs.TabLayout
 import com.google.android.material.tabs.TabLayoutMediator
 import com.google.android.material.textfield.TextInputLayout
+import com.ichi2.anki.AnkiActivity
 import com.ichi2.anki.CollectionManager
 import com.ichi2.anki.R
 import com.ichi2.anki.UIUtils.showThemedToast
 import com.ichi2.anki.launchCatchingTask
+import com.ichi2.anki.requireAnkiActivity
 import com.ichi2.anki.scheduling.SetDueDateViewModel.Tab
 import com.ichi2.anki.snackbar.showSnackbar
 import com.ichi2.anki.ui.internationalization.toSentenceCase
@@ -96,13 +98,13 @@
     override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
         return MaterialAlertDialogBuilder(requireContext()).create {
             title(text = CollectionManager.TR.actionsSetDueDate().toSentenceCase(R.string.sentence_set_due_date))
-            positiveButton(R.string.dialog_ok) { updateDueDate() }
+            positiveButton(R.string.dialog_ok) { launchUpdateDueDate() }
             negativeButton(R.string.dialog_cancel)
             neutralButton(R.string.help) {
                 openUrl(R.string.link_set_due_date_help)
             }
-
-            setView(R.layout.dialog_set_due_date)
+            this
+                .setView(R.layout.dialog_set_due_date)
         }.apply {
             show()
 
@@ -137,26 +139,7 @@
         }
     }
 
-    private fun updateDueDate() = launchCatchingTask {
-        val cardsUpdated = withProgress(resources.getString(R.string.dialog_processing)) {
-            viewModel.updateDueDate()
-        }
-
-        if (cardsUpdated == null) {
-            Timber.w("unable to update due date")
-            showThemedToast(R.string.something_wrong, true)
-            return@launchCatchingTask
-        }
-
-        showSnackbar(
-            resources.getQuantityString(
-                R.plurals.reschedule_cards_dialog_acknowledge,
-                cardsUpdated,
-                cardsUpdated
-            ),
-            Snackbar.LENGTH_SHORT
-        )
-    }
+    private fun launchUpdateDueDate() = requireAnkiActivity().updateDueDate(viewModel)
 
     companion object {
         const val ARG_CARD_IDS = "ARGS_CARD_IDS"
@@ -250,3 +233,25 @@
 context (DialogFragment)
 val Int.dpToPx: Int
     get() = (this * requireContext().resources.displayMetrics.density + 0.5f).toInt()
+
+// this can outlive the lifetime of the fragment
+private fun AnkiActivity.updateDueDate(viewModel: SetDueDateViewModel) = this@AnkiActivity.launchCatchingTask {
+    val cardsUpdated = withProgress(resources.getString(R.string.dialog_processing)) {
+        viewModel.updateDueDate()
+    }
+
+    if (cardsUpdated == null) {
+        Timber.w("unable to update due date")
+        showThemedToast(R.string.something_wrong, true)
+        return@launchCatchingTask
+    }
+
+    showSnackbar(
+        resources.getQuantityString(
+            R.plurals.reschedule_cards_dialog_acknowledge,
+            cardsUpdated,
+            cardsUpdated
+        ),
+        Snackbar.LENGTH_SHORT
+    )
+}
```

2024-03-15 01:07 UTC, snowtimeglass commented
> The attached files were good, the patch was bad

Sorry for the trouble.

![image](https://github.com/ankidroid/Anki-Android/assets/10436072/8284fc93-5c9e-474a-ab56-1463ee490e76)
(left: text in the attached file, right: text pasted by me in the patch)

It appears that each space was removed unexpectedly for me, when I pasted the text (copied from 
Android Studio) to OneNote.

![image](https://github.com/ankidroid/Anki-Android/assets/10436072/b9a0cf65-30e3-42d1-9e77-23dc98c63e3b)

I'll be more careful.

2024-03-21 12:47 UTC, BrayanDSO approved these changes

2024-03-21 12:47 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
> +        )
Idk if this could be resolved with a `sw600dp` layout with a different width. since Android dialogs may be complicated. May be worth investigating in the future

2024-03-24 07:49 UTC, lukstbit requested changes
The dialog doesn't work in landscape: start in portrait => rotate to landscape => dialog is unusable
![Screenshot from 2024-03-24 09-48-10](https://github.com/ankidroid/Anki-Android/assets/52494258/e6f7e9e6-b35d-4b46-83bb-661a6719999f)

Also the keyboard doesn't appear when I'm trying to enter a value.

2024-03-24 07:49 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateViewModel.kt
> +    suspend fun updateDueDateAsync() = viewModelScope.async {
Why make this function suspended?

2024-04-09 13:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt
> +    fun showThemedToast(@StringRes textResource: Int, shortLength: Boolean) {
#16146

2024-04-10 09:25 UTC, lukstbit reviewed
The issues with dialog portrait-landscape and the keyboard not appearing are not fixed.

2024-04-13 11:37 UTC, lukstbit approved these changes
Great, looks good!

2024-04-13 12:28 UTC, merged