fix: flaky NoteEditorIntentTest
ankidroid/Anki-Android pull request #15712
Opened 2024-02-28 18:41 UTC by criticalAY

## Purpose / Description
Flaky test if trying to access edit field before it has loaded

## Fixes
* Fixes  #15707

## Approach
Place a check

## How Has This Been Tested?
Locally tested on PC need CI testing passing though

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-02-28 18:42 UTC, criticalAY commented
I have drafted the PR, if the CI passes and the changes are ok we can proceed otherwise would need more investigation

2024-02-28 18:43 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
> +            if (editor.collectionHasLoaded()) {
This would be better as an `assumeThat`

Better if we wait until the test can run

2024-02-28 18:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +    var collectionLoaded = false
I don't think this is used

2024-02-28 18:47 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +    var collectionLoaded = false
oops sorry

2024-02-28 19:09 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +    var collectionLoaded = false
I will rebase the PR, waiting for CI (want to be sure, twice)

2024-02-29 14:58 UTC, criticalAY commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
> +            Assume.assumeTrue(editor.collectionHasLoaded())
We can define a while loop and number of retires lets say 5 and time to retry 1 second?

2024-02-29 15:01 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
> +            Assume.assumeTrue(editor.collectionHasLoaded())
Whatever's easiest

2024-02-29 19:59 UTC, mikehardy commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
> +            Assume.assumeTrue(editor.collectionHasLoaded())
I'm not sure about the whatever's easiest, this solution does not look good to me as it's polling based and could still just flake.

Is there no way to make this *actually* event based and have it wait until it has the things it needs, then do what it needs to for testing?

2024-02-29 20:01 UTC, criticalAY commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
> +            Assume.assumeTrue(editor.collectionHasLoaded())
There is maybe `IdlingResource` can do that, I will have to look into it

2024-02-29 20:02 UTC, criticalAY commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
> +            Assume.assumeTrue(editor.collectionHasLoaded())
This won't give flaky just in case collection is still not loaded ` Assume.assumeTrue(editor.collectionHasLoaded())` will take care of it

2024-03-02 18:51 UTC, criticalAY commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
> +            Assume.assumeTrue(editor.collectionHasLoaded())
@mikehardy We can use a latch and `observeForever` but that would also need a time-out, it requires a mutable live variable in Activity and that's how we observe it as as soon as collection is loaded we get out and proceed but if time is elapshed and collection is not loaded then we escape the test, fundamentally same approach, what do you suggest keep this code or use other one? we can't observe it for infinite time though. The current commit would not give flaky test though as it also has a check. Would like to know your opinion

2024-03-02 18:53 UTC, criticalAY commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
> +            Assume.assumeTrue(editor.collectionHasLoaded())
If we place this condition we can escape the test in case the collection is loaded within the specified time?
```
if (!collectionLoaded && retryCount == maxRetryCount) {
    Assert.fail("Collection was not loaded within the specified time frame")
}
```

2024-03-18 15:55 UTC, david-allison commented
@criticalAY is this on us to re-review?

2024-03-18 15:58 UTC, criticalAY commented
Yes, I did comment after Mike replied so I was waiting for a response to act

2024-03-18 17:14 UTC, david-allison requested changes

2024-03-18 17:14 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
> +        Assert.assertTrue(collectionLoaded)
Going back on myself, we need to do better here.

We need to figure out whether:

* `scenario.moveToState(Lifecycle.State.RESUMED)` didn't work
* The activity depends on a background task, which may not be completed after `onResume`

Either this is a bug in the test, or a bug in the implementation, we need to understand what's happened and fix it

In addition, the commit message should contain much more of an explanation of why the bug was occurring if it's not clear from the test

2024-03-18 18:30 UTC, criticalAY commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
> +        Assert.assertTrue(collectionLoaded)
Ok will look to it and get back

2024-03-19 16:40 UTC, criticalAY commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
> +        Assert.assertTrue(collectionLoaded)
Moving the state to Created to see if it works with the CI fine as the test pass on my local system without any issue

2024-03-19 17:07 UTC, criticalAY commented
I will push one more change to test ci then rebase

2024-04-02 20:33 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
> +        scenario.moveToState(Lifecycle.State.CREATED)
What's the state of this? It would be extremely useful to know /why/ this fixes the problem, as it feels like `RESUMED` is the correct state

2024-05-01 20:05 UTC, criticalAY commented
keep open please

2024-06-18 10:00 UTC, david-allison commented
Closing this to keep the PR queue clean - work is required here

2024-06-18 10:00 UTC, closed without merging