Added FSRS info to getDebugInfo
ankidroid/Anki-Android pull request #15749
Opened 2024-03-02 20:52 UTC by Haz3-jolt

Added FSRS status to getDebugInfo as a coroutine and converted getDebugInfo into a suspend function and converted it's callers to applicationScopeLaunch.

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
* Fixes _[Link to the issues](https://github.com/ankidroid/Anki-Android/issues/15447)._

## Approach
_How does this change address the problem?_
- Adds info to the debug about weather the user is using FSRS or not, by creating a suspend fun getFSRSStatus(), which uses config.get() to get the FSRS status. 
- Converted getDebugInfo() to a suspend function.
- Wrapped all the relevant getDebugInfo() with a coroutine. 
## How Has This Been Tested?

When through compilation, tested by using a fresh install and running cases the following cases: 
- With no decks (Fresh Install). (FSRS = null)
- One deck with no cards. (FSRS = null)
- One deck with Cards but FSRS has never been enabled. (FSRS = null)
- One deck with Cards and FSRS has been enabled. (FSRS = True)
- One deck with Card and FSRS has been disabled but was enabled some time in the past. (FSRS = False)
- With no decks but FSRS has been enabled before. (FSRS = null)
- New empty deck created with FSRS never enabled. (FSRS = False)

## Checklist
_Please, go through these checks before submitting the PR._

- [-] You have a descriptive commit message with a short title (first line, max 50 chars).
- [-] You have commented your code, particularly in hard-to-understand areas
- [-] You have performed a self-review of your own code
- [-] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [-] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

Here is a video with some TestCases
https://github.com/ankidroid/Anki-Android/assets/79502699/8184ce57-9c9a-4580-bd45-510690537073

2024-03-02 21:04 UTC, BrayanDSO requested changes

2024-03-02 21:04 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +        // Use applicationScope as a coroutine scope to use getDebugInfo() since it is a suspend fun
the comment isn't useful

2024-03-02 21:04 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +                Timber.e(e, "Error getting debug info")
```suggestion
                Timber.w(e, "Error getting debug info")
```

2024-03-02 21:04 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
> +        viewLifecycleOwner.lifecycleScope.launch {
Use `launchCatchingTask` and drop the `catch` block

2024-03-02 21:04 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
> +        val isFSRSEnabled = deferred.await()
Why async/await and why Dispatchers.Main?

2024-03-02 21:05 UTC, BrayanDSO commented
Also, the commit messages are identical. If they are meant to do the same thing, please squash them

2024-03-02 21:10 UTC, Haz3-jolt commented
> Also, the commit messages are identical. If they are meant to do the same thing, please squash them

Ye that was a mistake, will change now.

2024-03-02 21:10 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
> +        val isFSRSEnabled = deferred.await()
Was a test case thing, sorry bruv.

2024-03-02 21:50 UTC, BrayanDSO requested changes

2024-03-02 21:50 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
> +            }
not necessary inside a `launchCatchingTask

2024-03-02 21:50 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
> +    // Uses config.get() to get the FSRS status from the collection using withOpenColOrNull
`//` comments can only be read in the file of the method itself. Since this is just stating what the method calls, it is easier to read the method directly.

If it was a `/**` comment, it still wouldn't be necessary to state those kind of implementation details.

TLDR: please remove the comment

2024-03-02 21:50 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
> +               FSRS  = $isFSRSEnabled
```suggestion
               FSRS Enabled = $isFSRSEnabled
```

2024-03-02 21:50 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
> +    // This is run on the startup path, we need to protect against a null/corrupt collection
A method shouldn't be responsible for its calling sites. The call could be removed from the startup at any time and this wouldn't make sense. Also why someone needs to protect against a null/corrupt collection here?

What I suggest is
```kotlin
    /**
    * Retrieves the debug info based in different parameters of the app.
    * 
    * Note that the `FSRS` parameter can be null if the collection isn't open
    */
```

2024-03-02 22:00 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
> +    // This is run on the startup path, we need to protect against a null/corrupt collection
Done, made changes, and the null/corrupt thing was from testing because before I ran the FSRS in a async coroutine since i wanted the go ahead from David on if i can make the entire debugInfo fun into a suspend.

2024-03-02 22:12 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
> +    // Uses config.get() to get the FSRS status from the collection using withOpenColOrNull
> TLDR: please remove the comment

you resolved the comment, but didn't do what was asked nor stated why you didn't

2024-03-02 22:18 UTC, david-allison requested changes
Thanks!! almost there

2024-03-02 22:18 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            }
getDebugInfo should not throw

```suggestion
            Timber.i(DebugInfoService.getDebugInfo(this))
```

2024-03-02 22:18 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
> +        CollectionManager.withOpenColOrNull { config.get<Boolean>("fsrs") }
If this does not exist, it throws a `BackendNotFoundException`, and therefore returns `null`.

This should be changed s.t.

* `BackendNotFoundException` is caught
* the default value of `false` is returned if the value is not found

2024-03-02 22:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
> +        CollectionManager.withOpenColOrNull { config.get<Boolean>("fsrs") }
This could also be implemented as an extension method on `config`, up to you

2024-03-02 22:25 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
> +        CollectionManager.withOpenColOrNull { config.get<Boolean>("fsrs") }
It returns Null, if there are no decks or if a deck has been created and FSRS has never been enabled, but if FSRS is enabled and then disabled, it would return False. I left it because it might be useful to know if FSRS was used at some point but later disabled, but if you think its better to just have true or false then I am okay with that as well.

2024-03-02 22:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
> +        CollectionManager.withOpenColOrNull { config.get<Boolean>("fsrs") }
I feel the most intuitive is:

`null` -> no collection
`false` -> enabled, then disabled (or no preference)
`true` -> enabled

2024-03-02 22:31 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
> +        CollectionManager.withOpenColOrNull { config.get<Boolean>("fsrs") }
so do i go ahead with the change? btw ignore the checks for a moment, accidentally hit commit suggested changed, have to reverse it rn.

2024-03-02 22:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
> +        CollectionManager.withOpenColOrNull { config.get<Boolean>("fsrs") }
```patch
Subject: [PATCH] feat: copy card template to clipboard

---
Index: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt	(revision 7a052a9e0c73dc8f0fd8dc8e7e24af637cf52c19)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt	(date 1709419061597)
@@ -136,7 +136,7 @@
         }
 
         applicationScope.launch {
-            Timber.i(DebugInfoService.getDebugInfo(this))
+            Timber.i(DebugInfoService.getDebugInfo(this@AnkiDroidApp))
         }
 
         // Stop after analytics and logging are initialised.
Index: AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt b/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt	(revision 7a052a9e0c73dc8f0fd8dc8e7e24af637cf52c19)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt	(date 1709419363652)
@@ -36,6 +36,7 @@
      */
     suspend fun getDebugInfo(info: Context): String {
         val webviewUserAgent = getWebviewUserAgent(info)
+        // isFSRSEnabled is null on startup
         val isFSRSEnabled = getFSRSStatus()
         return """
                AnkiDroid Version = $pkgVersionName (${BuildConfig.GIT_COMMIT_HASH})
@@ -77,7 +78,7 @@
 
     // Uses config.get() to get the FSRS status from the collection using withOpenColOrNull
     private suspend fun getFSRSStatus(): Boolean? = try {
-        CollectionManager.withOpenColOrNull { config.get<Boolean>("fsrs") }
+        CollectionManager.withOpenColOrNull { config.get<Boolean>("fsrs", false) }
     } catch (e: Error) {
         Timber.w(e)
         null
Index: AnkiDroid/src/main/java/com/ichi2/libanki/Config.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/libanki/Config.kt b/AnkiDroid/src/main/java/com/ichi2/libanki/Config.kt
--- a/AnkiDroid/src/main/java/com/ichi2/libanki/Config.kt	(revision 7a052a9e0c73dc8f0fd8dc8e7e24af637cf52c19)
+++ b/AnkiDroid/src/main/java/com/ichi2/libanki/Config.kt	(date 1709419016527)
@@ -18,6 +18,7 @@
 
 import anki.config.ConfigKey
 import com.google.protobuf.kotlin.toByteStringUtf8
+import com.ichi2.libanki.utils.NotInLibAnki
 import kotlinx.serialization.SerializationException
 import kotlinx.serialization.encodeToString
 import kotlinx.serialization.json.Json
@@ -57,4 +58,15 @@
     fun setBool(key: ConfigKey.Bool, value: Boolean) {
         backend.setConfigBool(key, value, false)
     }
+
+    @NotInLibAnki
+    inline fun<reified T> get(key: String, default: T): T? {
+        return try {
+            Json.decodeFromString<T>(backend.getConfigJson(key).toStringUtf8())
+        } catch (ex: BackendNotFoundException) {
+            default
+        } catch (ex: SerializationException) {
+            null
+        }
+    }
 }
```

2024-03-02 23:02 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
> +        CollectionManager.withOpenColOrNull { config.get<Boolean>("fsrs") }
Done.

2024-03-03 05:18 UTC, david-allison requested changes
one comment-based change, then good to go

2024-03-03 05:18 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
> +    // Uses config.get() to get the FSRS status from the collection using withOpenColOrNull
This

2024-03-03 06:12 UTC, Haz3-jolt commented
> one comment-based change, then good to go

what should the new comment be?

2024-03-03 06:22 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
> +    // Uses config.get() to get the FSRS status from the collection using withOpenColOrNull
ahh ok man

2024-03-03 11:44 UTC, david-allison approved these changes
Looks great, thanks so much @Haz3-jolt!!

2024-03-03 12:57 UTC, BrayanDSO approved these changes
Nice. Thanks!

2024-03-03 13:13 UTC, merged