Fix: Missing storage permission causing NPE and crashing app
ankidroid/Anki-Android pull request #15765
Opened 2024-03-04 09:50 UTC by criticalAY

## Purpose / Description
* #15698 PR tried to fix the widget issue but it introduced a bug in lower API (Android<=10) which I revert in * #15747
Here in this PR instead of disabling the widgets from manifest file, I updated the flow which is
* The shortcuts are not enabled until the storage access is granted using a return statement in the same function
* Widgets are enabled by default but if user tries to access the widget i.e. open it without storage permission then they are taken to storage permission screen. For existing user having the widgets(we can't update the existing widget that are already added) placing a check in the respective activities to handle the cases and showing a relevant toast that storage permission is missing 
* No existing widget is deleted 
* Not bound to any API level 

## Fixes
* Fixes #13518
* Fixes #15686

## How Has This Been Tested?
[widget_new_device.webm](https://github.com/ankidroid/Anki-Android/assets/48384865/a1c20b3d-33ff-42fd-a38f-0ba044c93e29)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-03-04 16:25 UTC, david-allison requested changes

2024-03-04 16:25 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        if (!IntentHandler.grantedStoragePermissions(this)) {
This feels like it should be functionally equivalent to the check below, could you see if `hasCollectionStoragePermissions` can be updated?

2024-03-04 16:25 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
> +        if (grantedStoragePermissions(this)) {
ditto with the above comment

2024-03-04 16:25 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
> +                Timber.i("Opening AnkiDroid Small widget without storage access")
This feels like a `Timber.w`

Inform the developer that the function stopped

2024-03-04 16:25 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
> +                Timber.i("Opening AnkiDroid Small widget without storage access")
I believe this needs to be handled on more than `onStart`

2024-03-04 16:25 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                if (!IntentHandler.grantedStoragePermissions(this)) {
Why is this needed if `finish() + return` is called inside `onCreate`

2024-03-04 19:13 UTC, mikehardy commented
May not make it into 2.17.4 but if not, 2.17.5 would be nice - will rework milestone names after the 2.17.2 release pipeline failure unexpectedly burnt a number

2024-03-04 19:15 UTC, criticalAY commented
@david-allison I made some changes (nitpicks in the recent push) I hope you are through them?

2024-03-04 19:17 UTC, david-allison commented
Re-reviewed after the push, still good to go

2024-03-04 19:23 UTC, mikehardy commented
🤔 ominous sign

```

com.ichi2.anki.FieldEditLineTest > testSaveRestore[emulator-5554 - 11] FAILED 
	java.lang.NullPointerException: Cannot run onActivity since Activity has been destroyed already
	at androidx.test.internal.util.Checks.checkNotNull(Checks.java:45)

com.ichi2.anki.FieldEditLineTest > testSetters[emulator-5554 - 11] FAILED 
	java.lang.NullPointerException: Cannot run onActivity since Activity has been destroyed already
	at androidx.test.internal.util.Checks.checkNotNull(Checks.java:45)
```

re-running.

2024-03-04 19:24 UTC, criticalAY commented
Looking into it

2024-03-04 19:28 UTC, criticalAY commented
Let's wait for the CI to run this time, here is to hoping noting is wrong this time

2024-03-04 19:37 UTC, criticalAY commented
I think we will have to update the test as we return early, so no merge today

2024-03-04 21:22 UTC, criticalAY commented
@david-allison @mikehardy Removed one test as in CardBrowser replaced certain outdated code, apart from that we skip the method i.e. instrumented test or unit test

2024-03-04 21:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +        checkAndHandleStoragePermissions(savedInstanceState)
This no longer returns early, as the return is extracted to the method

2024-03-04 21:26 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +        checkAndHandleStoragePermissions(savedInstanceState)
If we call `restorePreferences()` after this we can return early

2024-03-04 22:15 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +        checkAndHandleStoragePermissions(savedInstanceState)
One more mistake I found, I made changes to Abstract flashcard class idk why but it was supposed to be Reviewer

2024-03-04 22:17 UTC, criticalAY commented
Updated test
![Screen_recording_20240305_034627.webm](https://github.com/ankidroid/Anki-Android/assets/48384865/24f08b7d-2bd6-450f-bc20-eaca5339346b)

2024-03-05 01:30 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        if (!grantedStoragePermissions(this) && !AdaptionUtil.isRunningAsUnitTest) {
Flip the if and return early

2024-03-05 01:30 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
> -    fun startupFromCardBrowserActionItemShouldEndActivityIfNoPermissions() {
Can you fix this test rather then remove it (mock the new method to fail)

2024-03-05 02:28 UTC, mikehardy commented
Question: why didn't `./gradlew jacocoTestReport` see this on your machine prior to posting the PR?

2024-03-05 08:44 UTC, criticalAY commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
> -    fun startupFromCardBrowserActionItemShouldEndActivityIfNoPermissions() {
Done!

2024-03-05 09:02 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        if (!grantedStoragePermissions(this) && !AdaptionUtil.isRunningAsUnitTest) {
I messed up the commit message and will update it and apply this suggestion once I'm home

2024-03-05 09:19 UTC, criticalAY commented
> Question: why didn't ./gradlew jacocoTestReport see this on your machine prior to posting the PR?

Will do in future commits

2024-03-05 12:16 UTC, criticalAY commented
Reason for not returning early: the super call gets executed which prevents the actual onCreate body from being executed hence reverting it,
`./gradlew jacocoTestReport` passed all tests except Tablet as the emulator it ran a test on was a Pixel 8 device

2024-03-05 13:39 UTC, david-allison approved these changes
I'll leave it to reviewer 2 to suggest changes to calling `super.onCreate()` from inside those methods, it's unusual and will lead to bugs

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt	(revision 33fda02ce126762fd1fe4ac5512634fd6a5accd5)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt	(date 1709645946821)
@@ -349,17 +349,17 @@
      * This method should be called before calling super.onCreate(savedInstanceState).
      */
     private fun checkAndHandleStoragePermissions(savedInstanceState: Bundle?): Boolean {
-        if (!grantedStoragePermissions(this) && !AdaptionUtil.isRunningAsUnitTest) {
-            super.onCreate(savedInstanceState)
-            Timber.w("'Card Browser' Action item pressed before storage permissions granted.")
-            if (wasLoadedFromExternalTextActionItem()) {
-                // we need to do this as DeckPicker still contains app init logic/upgrade logic
-                displayDeckPickerForPermissionsDialog()
-            }
-            finish()
-            return false
-        }
-        return true
+        if (grantedStoragePermissions(this) || AdaptionUtil.isRunningAsUnitTest) {
+            return true
+        }
+        super.onCreate(savedInstanceState)
+        Timber.w("'Card Browser' Action item pressed before storage permissions granted.")
+        if (wasLoadedFromExternalTextActionItem()) {
+            // we need to do this as DeckPicker still contains app init logic/upgrade logic
+            displayDeckPickerForPermissionsDialog()
+        }
+        finish()
+        return false
     }
 
     override fun onCreate(savedInstanceState: Bundle?) {
```

2024-03-05 13:44 UTC, criticalAY commented
The only reason to have super call here is because tag factory class is init before super call in `onCreate` that's why we need to check storage access before that other there isn't any need

2024-03-05 17:00 UTC, criticalAY commented
Returning early at both classes now

2024-03-07 12:43 UTC, mikehardy commented
This is problematic for me as a comment:

> I'll leave it to reviewer 2 to suggest changes to calling super.onCreate() from inside those methods, it's unusual and will lead to bugs

In combination with the frequent need for followups and fixups and reverts and such on previous work

I haven't reviewed deeply enough to say one way or the other but I'm concerned about general level of quality in the past and I'm looking to merge + cherry-pick fixes for the release branch - given history and this comment I pass on spending time on this one until maybe some future date I have time

Though any other reviewer that has time to look, obviously please do

2024-03-07 13:52 UTC, david-allison requested changes
* don't log in a getter
* Each of the 3 scenarios: CardBrowswr, Reviewer & NoteEditor had the same general concept: storage permissions has not been granted, so don't start the activity. This was extracted to `AnkiActivity`
  *  It seemed easier to log a generic 'activity finishing' message than providing a specific message per activity 
* CardBrowser needed the `ViewModel` to be conditionally initalized if storage permissions were granted

```patch
Subject: [PATCH] chore(log): CardBrowserViewModel

The logs helps with diagnostics when the collection is inaccessible
---
Index: AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt b/AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
--- a/AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt	(revision b1f87895395df8436e442eebd1bb87737acfc969)
+++ b/AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt	(date 1709819584379)
@@ -147,23 +147,6 @@
             Timber.d("isRunningAsUnitTest: %b", true)
             return true
         }
-
-    /**
-     * Checks if the code is running as part of an Android instrumentation test.
-     * This property detects if the Espresso testing library is available on the classpath,
-     * which indicates that the code is being executed within an Android instrumentation test.
-     */
-    val isRunningAsAndroidTest: Boolean
-        get() {
-            try {
-                Class.forName("androidx.test.espresso.Espresso")
-            } catch (ignored: ClassNotFoundException) {
-                Timber.d("isRunningAsAndroidTest: %b", false)
-                return false
-            }
-            Timber.d("isRunningAsAndroidTest: %b", true)
-            return true
-        }
 }
 
 val isRobolectric get() = Build.FINGERPRINT?.startsWith("robolectric") ?: false
Index: AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt	(revision b1f87895395df8436e442eebd1bb87737acfc969)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt	(date 1709818646800)
@@ -388,7 +388,7 @@
             mockkObject(AdaptionUtil)
             mockkObject(IntentHandler)
 
-            every { grantedStoragePermissions(any()) } returns false
+            every { grantedStoragePermissions(any(), any()) } returns false
             every { AdaptionUtil.isRunningAsUnitTest } returns false
 
             val browserController = Robolectric.buildActivity(CardBrowser::class.java).create()
Index: AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt b/AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
--- a/AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt	(revision b1f87895395df8436e442eebd1bb87737acfc969)
+++ b/AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt	(date 1709818717712)
@@ -39,7 +39,7 @@
 class AnkiDroidWidgetSmall : AppWidgetProvider() {
     override fun onUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray) {
         Timber.d("SmallWidget: onUpdate")
-        if (!grantedStoragePermissions(context)) {
+        if (!grantedStoragePermissions(context, showToast = false)) {
             Timber.w("Opening AnkiDroid Small widget without storage access")
             return
         }
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(revision b1f87895395df8436e442eebd1bb87737acfc969)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(date 1709819452184)
@@ -353,14 +353,12 @@
         tagsDialogFactory = TagsDialogFactory(this).attachToActivity<TagsDialogFactory>(this)
         mediaRegistration = MediaRegistration(this)
         super.onCreate(savedInstanceState)
+        if (!ensureStoragePermissions()) {
+            return
+        }
         fieldState.setInstanceState(savedInstanceState)
         setContentView(R.layout.note_editor)
         val intent = intent
-        if (!IntentHandler.grantedStoragePermissions(this) && !AdaptionUtil.isRunningAsAndroidTest) {
-            Timber.w("No storage access")
-            finish()
-            return
-        }
         if (savedInstanceState != null) {
             caller = savedInstanceState.getInt("caller")
             addNote = savedInstanceState.getBoolean("addNote")
Index: AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt b/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt	(revision b1f87895395df8436e442eebd1bb87737acfc969)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt	(date 1709818646778)
@@ -126,7 +126,7 @@
      */
     @NeedsTest("clicking a file in 'Files' to import")
     private fun performActionIfStorageAccessible(reloadIntent: Intent, action: String?, block: () -> Unit) {
-        if (grantedStoragePermissions(this)) {
+        if (grantedStoragePermissions(this, showToast = true)) {
             Timber.i("User has storage permissions. Running intent: %s", action)
             block()
         } else {
@@ -267,7 +267,7 @@
             return !isInvalidViewIntent(intent)
         }
 
-        fun grantedStoragePermissions(context: Context, showToast: Boolean = true): Boolean {
+        fun grantedStoragePermissions(context: Context, showToast: Boolean): Boolean {
             val granted = !ScopedStorageService.isLegacyStorage(context) || hasStorageAccessPermission(context) || Permissions.isExternalStorageManagerCompat()
 
             if (!granted && showToast) {
Index: AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt	(revision b1f87895395df8436e442eebd1bb87737acfc969)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt	(date 1709818646796)
@@ -420,7 +420,7 @@
         const val EXTRA_STARTED_WITH_SHORTCUT = "com.ichi2.anki.StartedWithShortcut"
 
         fun enablePostShortcut(context: Context) {
-            if (!IntentHandler.grantedStoragePermissions(context, false)) {
+            if (!IntentHandler.grantedStoragePermissions(context, showToast = false)) {
                 Timber.w("No storage access, not enabling shortcuts")
                 return
             }
Index: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
=================================== [...]

2024-03-07 14:42 UTC, david-allison approved these changes
Round 2, let's try this one again

2024-03-07 19:38 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
> +        if (!IntentHandler.grantedStoragePermissions(context, showToast = false)) {
This change makes this instance of the AddNoteWidget to not start the NoteEditor:

- install app(no permission yet)
- add the AddNoteWidget to the screen(at this point the actual initialization in onUpdate is ignored(including starting NoteEditor on click)), the app does not crash so it's a plus
- go through the app and offer the permission
- click on the AddNoteWidget and see that it starts DeckPicker(standard intent?) not the NoteEditor(because of the permission not being available, its action wasn't set and the widget doesn't update itself so onUpdate is not called again)
- if you add another AddNoteWidget that works correctly as it picks the new permissions

To be honest I'm not sure how to fix this.

2024-03-07 19:43 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
> +        if (!IntentHandler.grantedStoragePermissions(context, showToast = false)) {
I placed this code in the service first, where it worked fine but now here its buggy again, let me see to it, this issue is taking forever now lmao but okay...

2024-03-07 19:56 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
> +        if (!IntentHandler.grantedStoragePermissions(context, showToast = false)) {
The intent is never placed hence the issue, can resolve it using a broadcast receiver

2024-03-07 20:22 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
> +        if (!IntentHandler.grantedStoragePermissions(context, showToast = false)) {
Fixed it

2024-03-07 20:23 UTC, criticalAY commented
https://github.com/ankidroid/Anki-Android/assets/48384865/894952d9-6917-4577-b634-86c3ad676d72

2024-03-07 20:24 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
> +        if (!IntentHandler.grantedStoragePermissions(context, showToast = false)) {
I have provided the updated test below

2024-03-09 04:25 UTC, david-allison commented on AnkiDroid/src/main/AndroidManifest.xml
> +        <receiver android:name="com.ichi2.widget.WidgetPermissionReceiver"
I'd propose splitting out the widget-related changes into a separate PR, there's more complexity being added here, and the activity- related changes can be merged immediately

2024-03-09 06:42 UTC, criticalAY commented on AnkiDroid/src/main/AndroidManifest.xml
> +        <receiver android:name="com.ichi2.widget.WidgetPermissionReceiver"
Ok 🆗

2024-03-09 08:46 UTC, lukstbit approved these changes
Ok, with the expectation of a follow up PR for the widget update.

2024-03-09 09:03 UTC, merged

2024-03-09 09:08 UTC, criticalAY commented
There is some electricity issue here today, so as soon as it's fixed I'll drop a PR