Feature/add search bar to manage note types
ankidroid/Anki-Android pull request #15789
Opened 2024-03-06 05:10 UTC by AffanShaikhsurab

# Branch Name: feature/add-search-bar-to-manage-note-types

This commit introduces a search bar to the ManageNotetypes section, enabling users to search for specific note types. The search bar enhances usability and improves the overall user experience.

## Purpose / Description
The purpose of this change is to improve the ManageNotetypes section by adding a search bar functionality. This allows users to easily find specific note types within the application, thereby enhancing user experience and usability.

## Fixes
* Fixes #15763

## Approach
The approach taken to address this issue was to integrate a search bar component into the ManageNotetypes section. This involved modifying the layout XML file to include the search bar widget and implementing the necessary logic to handle search queries.

## How Has This Been Tested?
The changes have been tested thoroughly to ensure functionality and compatibility across different devices and screen sizes. The following steps were taken to verify the changes:
1. Opened the ManageNotetypes section.
2. Entered various search queries to test the search functionality.
3. Verified that the search results were accurate and relevant.
4. Tested the responsiveness of the search bar on different screen sizes and orientations.
5. Reviewed the code changes for any potential issues or regressions.

Test Configuration:
- Device: Google Pixel 4 XL
- OS: Android 12
- SDK Version: 31

## Learning (optional, can help others)
During the implementation of this feature, I learned about integrating search functionality into Android applications using the SearchView widget. I also explored best practices for handling search queries efficiently and optimizing search performance.

No additional external resources were used in the implementation of this feature.

## Checklist
Please, go through these checks before submitting the PR.

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

![ManageNotesTypes](https://github.com/ankidroid/Anki-Android/assets/51104750/1f311b18-61a0-4322-9b9e-04a403ed15db)
![ManageNotesTypes_Accessibility](https://github.com/ankidroid/Anki-Android/assets/51104750/c3c4f3dc-0a79-4b27-ada3-955a3f9cbc34)

2024-03-06 08:31 UTC, david-allison requested changes
Thanks! Is it feasible to move this into the app bar + menu to save space as we do with other screens

2024-03-06 08:36 UTC, AffanShaikhsurab commented
Can we relocate the search icon to the top right of the app bar? Does that sound good?

2024-03-06 08:38 UTC, david-allison commented
That sounds perfect! We do the same in the DeckPicker

2024-03-06 10:36 UTC, AffanShaikhsurab commented
I've humbly relocated the search icon to the top right corner of the app bar. Would you mind taking a look?
![manage_notes_tupe1](https://github.com/ankidroid/Anki-Android/assets/51104750/cd9eb519-d02e-4279-b594-83d3fd89a3fd)
![Manage_notes_type](https://github.com/ankidroid/Anki-Android/assets/51104750/bf0d2972-298f-40ef-857b-9d5f893e95a4)

2024-03-07 02:46 UTC, AffanShaikhsurab commented
Can you please tell if any changes needs to be done , thank you

2024-03-07 14:24 UTC, david-allison requested changes
Very clean!

In addition: the 'x' on the searchView seems to be in the wrong place, I would expect that it would be to the right hand side

<img width="380" alt="Screenshot 2024-03-07 at 14 21 28" src="https://github.com/ankidroid/Anki-Android/assets/62114487/d40215dd-900b-45d8-b42d-cfdbbadf595f">

2024-03-07 14:24 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +                    notetypesAdapter.currentList.filter {
This performs a filter on the current list

Let's say we have decks: `[a, aa]`

If a user enters `aa`, then only `aa` is displayed

If a user backspaces, the filter is performed over `[aa]`, therefore a search for `a` only returns `[aa]`

2024-03-07 14:24 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +                    currentNotetypes // returns the initial list if search query is  empty
```suggestion
                    currentNotetypes // returns the initial list if search query is empty
```

2024-03-07 14:24 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +
please revert non-functional spacing changes, they make it harder to review & use `git blame`

2024-03-07 14:24 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +        }
I don't understand this, I would expect that we want the search to handle a newly added note type (and to remove a deleted note type from the collection)

2024-03-07 14:24 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeAdapter.kt
> +
nit: revert spacing changes

2024-03-07 14:24 UTC, david-allison commented on AnkiDroid/src/main/res/layout/toolbar.xml
> +
nit: spacing changes

2024-03-07 14:24 UTC, david-allison commented on AnkiDroid/src/main/res/values/strings.xml
> +    <string name="search">Search\n</string>
We already have this string

In addition, for AnkiDroid, we should use `02-strings` or similar, as these files are automatically sent to our translators

2024-03-07 14:24 UTC, david-allison commented on AnkiDroid/src/main/res/menu/manage_notes_type_menu.xml
> +        android:title="@string/deck_picker_dialog_filter_decks"
This is incorrect: `Filter decks`

2024-03-07 14:24 UTC, david-allison commented on AnkiDroid/src/main/res/menu/manage_notes_type_menu.xml
> +        android:contentDescription="@string/search_content_description"
I feel `Filter note types` (as seen above) will be sufficient.

2024-03-07 14:24 UTC, david-allison commented on AnkiDroid/src/main/res/menu/manage_notes_type_menu.xml
> +  Copyright (c) 2020 David Allison <davidallisongithub@gmail.com>
Add your copyright

2024-03-07 14:24 UTC, david-allison commented on AnkiDroid/src/main/res/layout/activity_manage_note_types.xml
> +<include layout="@layout/manage_notes_type_toolbar" />
aim to keep the spacing consistent (needs a couple of tabs to align with other elements)

2024-03-07 14:36 UTC, AffanShaikhsurab commented
Thanks a lot for the feedback I will surely implement all of it

2024-03-07 15:07 UTC, AffanShaikhsurab commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +                    notetypesAdapter.currentList.filter {
There was an issue, so I preserved the original list by storing it in the variable "currentList." Now, when the user filters the list with the term "aa" and then presses the backspace key, the filter reverts to the original list [a, aa] instead of just [aa]. Is this method fine ?

2024-03-07 15:09 UTC, AffanShaikhsurab commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +        }
Here, I'm saving the original list for the first time.

2024-03-07 23:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +                    notetypesAdapter.currentList.filter {
If a user has `a` in the search, it should show `[a, aa]`

2024-03-08 13:17 UTC, AffanShaikhsurab commented
I have implemented the requested changed just one quick question : The "x" in searchView is used in the right hand side in the other screens of the app . So i have kept it on the right hand it self . Should i need move it anyways ? 
![test1](https://github.com/ankidroid/Anki-Android/assets/51104750/d5a23f71-5a63-4ba9-8c72-1b2597deb7f4)

2024-03-08 22:52 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="search_notes">Search Notes</string>
```
  /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/02-strings.xml:343: Error: The resource R.string.search_notes appears to be unused [UnusedResources]
      <string name="search_notes">Search Notes</string>
              ~~~~~~~~~~~~~~~~~~~
```

2024-03-09 06:18 UTC, AffanShaikhsurab commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="search_notes">Search Notes</string>
Thank you for pointing it out

2024-03-09 12:35 UTC, AffanShaikhsurab commented
I have made the necessary changes i was using a very noob approach but after understanding the codebase better i have implemented all the changes requested

2024-03-11 09:14 UTC, criticalAY requested changes

2024-03-11 09:14 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +    // Initialize the list of current note types to an empty list
Please remove the extra comments

2024-03-11 09:14 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +                val filteredList = if (newText.isNullOrEmpty()) {
Same here

2024-03-11 09:21 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeAdapter.kt
> -
Revert this change

2024-03-11 09:32 UTC, criticalAY requested changes

2024-03-11 09:32 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +        val searchView = searchItem.actionView as SearchView?
`val searchView = searchItem?.actionView as? SearchView`
Adding null safety checks (?.) when accessing the searchView variable to prevent potential NullPointerExceptions is better

2024-03-11 09:32 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +                return false
why return false here? Should it be true to indicate that the search action has been handled.

2024-03-11 12:07 UTC, Mukuljangir372 commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +                    currentNotetypes.filter {
We should move this to background thread using Dispatcher.IO.

2024-03-11 16:09 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeAdapter.kt
> -
Still not addressed

2024-03-11 16:10 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +        // Get the SearchView MenuItem
comments here are not removed

2024-03-11 17:33 UTC, AffanShaikhsurab commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeAdapter.kt
> -
i am sorry but i don't understand , do you want me to revert it to original form ( as in main repo )

2024-03-11 17:59 UTC, criticalAY requested changes

2024-03-11 17:59 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeAdapter.kt
> -
Yes, you removed a line here which is unwanted

2024-03-12 04:08 UTC, AffanShaikhsurab commented
Any other changes that need's to be made.

2024-03-12 15:42 UTC, david-allison requested changes
Thanks! Looks good and works well

I still feel the x is in the wrong place

<img width="410" alt="Screenshot 2024-03-12 at 15 41 00" src="https://github.com/ankidroid/Anki-Android/assets/62114487/be944117-49ae-4155-ad79-1506000e7f6a">

In future, could you rebase rather than adding `merge` commits into the history, and `squash` merge any intermediary commits.

Squashing commits before pushing makes it easier to review, and easier to merge. There's no need for fixup commits in the history.

It also makes it much easier to fix line ending issues

2024-03-12 15:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +                lifecycleScope.launch {
This doesn't need to be a coroutine, it's a filter on ~100 items. 

The overhead takes it from 0-1ms to 1-2ms, and that's without any optimization

Both of these durations are much less than a frame at 120Hz

2024-03-12 15:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> -            // start with the button disabled as dialog shows the initial name
don't remove comments

2024-03-12 15:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +
nit: try not to make unnecessary line change

2024-03-12 15:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeAdapter.kt
>      }
ditto: aim to not make unnecessary line changes.

This will be much easier in the next PR where you've squashed commits

2024-03-12 15:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeAdapter.kt
> +    private val useCount: TextView = rowView.findViewById(R.id.note_use_count)
nit: revert this - try not to combine refactorings and functional changes in the same change.

We're going to need to squash merge this, and this adds unnecessary context for someone looking through this file

2024-03-12 15:42 UTC, david-allison commented on AnkiDroid/src/main/res/layout/activity_manage_note_types.xml
> +    android:id="@+id/root_layout"
nit: revert the spacing change

2024-03-12 15:42 UTC, david-allison commented on AnkiDroid/src/main/res/layout/activity_manage_note_types.xml
> +    <!-- Floating Action Button for adding new note types -->
comments are great!

2024-03-12 15:42 UTC, david-allison commented on AnkiDroid/src/main/res/layout/toolbar.xml
>              android:visibility="gone" />
nit: spacing change

2024-03-12 15:42 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +<resources>
revert this: it should be done in a separate PR as it will have a large impact on our translated files

2024-03-12 16:38 UTC, AffanShaikhsurab commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +                lifecycleScope.launch {
ohh thanks for the feedback , should i remove the it coroutine ?

2024-03-12 16:39 UTC, AffanShaikhsurab commented on AnkiDroid/src/main/res/values/02-strings.xml
> +<resources>
Ohh sorry i didn't knew it !

2024-03-12 16:46 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +<resources>
No worries!

2024-03-12 16:46 UTC, AffanShaikhsurab commented on AnkiDroid/src/main/res/layout/activity_manage_note_types.xml
> +    <!-- Floating Action Button for adding new note types -->
Thanks so much! It means a lot to hear that you appreciate the comments. If there's anything specific you'd like to see more of or any suggestions you have for improvement

2024-03-12 16:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +                lifecycleScope.launch {
yep

2024-03-12 16:47 UTC, AffanShaikhsurab commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeAdapter.kt
> +    private val useCount: TextView = rowView.findViewById(R.id.note_use_count)
yeah sure , i will make sure of that from next time !!

2024-03-12 16:49 UTC, AffanShaikhsurab commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +                lifecycleScope.launch {
I have removed it as you mentioned!

2024-03-12 16:50 UTC, AffanShaikhsurab commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeAdapter.kt
>      }
i am sorry i am causing inconvenience ,i am new to this ,  is there some resource i like this stuff so i don't make much mistakes from next time !?

2024-03-12 17:03 UTC, AffanShaikhsurab commented
Are they any changes that needs to be made ?

2024-03-12 17:22 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> -        launchCatchingTask { runAndRefreshAfter() } // shows the initial note types list
Unwanted changes here

2024-03-12 17:22 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeAdapter.kt
> -
Not reverted

2024-03-12 17:22 UTC, criticalAY commented on AnkiDroid/src/main/res/layout/toolbar.xml
> -
same here

2024-03-12 17:22 UTC, criticalAY commented on AnkiDroid/src/main/res/layout/toolbar.xml
> -
same

2024-03-12 17:22 UTC, criticalAY commented on AnkiDroid/src/main/res/layout/toolbar.xml
> -
same

2024-03-12 17:22 UTC, criticalAY commented on AnkiDroid/src/main/res/values/02-strings.xml
> +
can remove this extra blank line

2024-03-12 17:22 UTC, david-allison requested changes
A few minor spacing changes, then good to go

For reverting a file, see:

![Screenshot 2024-03-12 at 17 21 54](https://github.com/ankidroid/Anki-Android/assets/62114487/fcafd299-1be7-47bd-b72c-faa9b13e3140)

2024-03-12 17:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +        launchCatchingTask { runAndRefreshAfter() }
please don't remove comments

2024-03-12 17:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +                    currentNotetypes.filter {
discussed in another comment thread - there's no need for the complexity

2024-03-12 17:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeAdapter.kt
>      }
The term you're looking for is 'reverting hunks'

Before you 'git push', take a look through the preview and check to see if any line changes are made that aren't relevant

This still needs fixing

2024-03-12 17:22 UTC, david-allison commented on AnkiDroid/src/main/res/layout/toolbar.xml
> -
actually... none of the changes you made to this file are relevant, revert them all
![Screenshot 2024-03-12 at 17 21 54](https://github.com/ankidroid/Anki-Android/assets/62114487/fcafd299-1be7-47bd-b72c-faa9b13e3140)

2024-03-13 14:15 UTC, AffanShaikhsurab commented on AnkiDroid/src/main/res/layout/toolbar.xml
> -
I reverted all the changes

2024-03-13 14:16 UTC, AffanShaikhsurab commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> -        launchCatchingTask { runAndRefreshAfter() } // shows the initial note types list
Thanks for pointing out , I reverted it

2024-03-13 14:17 UTC, AffanShaikhsurab commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +        launchCatchingTask { runAndRefreshAfter() }
i will make sure it doesn't happens again !

2024-03-13 14:21 UTC, david-allison approved these changes
Looks great, thanks so much!

2024-03-13 14:23 UTC, AffanShaikhsurab commented
Thank you for guiding me throughout!

2024-03-23 16:55 UTC, lukstbit approved these changes
Thanks for contributing. I left below some small issues to address then we can merge this.

2024-03-23 16:55 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +    override fun onCreateOptionsMenu(menu: Menu): Boolean {
Please add an empty line between these methods.

2024-03-23 16:55 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +        val searchView = searchItem?.actionView as? SearchView
You can add:

`searchview?.maxWidth = Integer.MAX_VALUE`

to make the SearchView clear button stay the end of the toolbar.

2024-03-23 16:55 UTC, lukstbit commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="fab_content_description">Add a new note type</string>
This string name is too general. Use something like _"cd_manage_notetypes_add"_.

2024-03-26 13:51 UTC, AffanShaikhsurab commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="fab_content_description">Add a new note type</string>
yeah sure

2024-03-26 13:57 UTC, AffanShaikhsurab commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +        val searchView = searchItem?.actionView as? SearchView
added

2024-03-26 13:57 UTC, AffanShaikhsurab commented on AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
> +    override fun onCreateOptionsMenu(menu: Menu): Boolean {
added

2024-03-28 12:56 UTC, merged