chore: 'DialogFragmentProvider' - make optional
ankidroid/Anki-Android pull request #15784
Opened 2024-03-05 19:13 UTC by david-allison

If a call to super is requested, `null` may be returned In this case, `super` would be called

This is useful if you would optionally want to inherit from a class (say `EditTextPreference`), but also allow conditionally return a different fragment

* Prep for #3114 : 
   * We'll want a `ListPreference` if the user is on `play`
   * A `EditTextPreference` if the user is on `full`
   * Preferences screens don't expect two preferences for the same key
     * So we need one preference which will change implementations

2024-06-30 06:27 UTC, lukstbit requested changes

2024-06-30 06:27 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/preferences/ListPreferenceTrait.kt
> +    fun newInstance(key: String?): ListPreferenceDialogFragment =
You probably want to have this in the companion object.

2024-06-30 06:27 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/preferences/ListPreferenceTrait.kt
> +            dialog.dismiss()
Is this call to dismiss() needed?

2024-06-30 06:27 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/preferences/ListPreferenceTrait.kt
> +    var listEntries: MutableList<Entry>
Do you need to have this as a MutableList seeing as you declared it as a var?

2024-06-30 06:27 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/preferences/ListPreferenceTrait.kt
> +    fun findIndexOfValue(value: String) = listEntries.indexOfFirst { it.value == value }
Small nitpick: The name seems a bit verbose, indexOf(value) reads quite well and is shorter. Or maybe we don't need this method at all.

2024-08-16 01:54 UTC, mikehardy approved these changes
sorry this sat so long!

2024-08-16 02:34 UTC, merged