Exit confirmation in IO Editor
ankidroid/Anki-Android pull request #15806
Opened 2024-03-07 18:56 UTC by Aditya13s

## Purpose / Description
The purpose of this change is to implement an exit confirmation dialog that appears when the back button is pressed accidentally. This feature aims to prevent users from losing their work accidentally.

## Fixes
* Fixes #15753

## Approach
The approach taken to address this issue was to add an on `onBackPressedDispatcher` in `ImageOcclusionActivity.kt` and call the method named `showExitConfirmationDialog()` when back button was pressed

## How Has This Been Tested?
Tested the app on Realme Narzo 50 Pro Device

## Screenshots
<img height=700 src=https://github.com/ankidroid/Anki-Android/assets/77337791/413c5aa4-8bfd-43d6-824e-15f2636ad428.jpeg>

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-03-07 19:38 UTC, criticalAY requested changes
This PR's issue was assigned to someone else, @Aditya13s please ask in the issue first before submitting a PR or ping the members.  And if you were working on it already you should update that on this issue that you are working on it

2024-03-07 19:38 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> +        alertDialogBuilder.setNegativeButton("Keep Editing") { dialog, _ ->
Don't hardcode the strings here, use from backend `TR`

2024-03-07 19:38 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> +        val alertDialogBuilder = android.app.AlertDialog.Builder(this)
We have `androidx` why use `android` plus we have our own extension methods so change it here

2024-03-07 19:38 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> +        alertDialogBuilder.setPositiveButton("Discard") { dialog, _ ->
Same no hardcoding of strings

2024-03-07 20:04 UTC, criticalAY requested changes

2024-03-07 20:04 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> +        alertDialogBuilder.setMessage(CollectionManager.TR.addingDiscardCurrentInput())
Still not using the extension methods here, see how other AlertDialog exist in the project

2024-03-07 20:28 UTC, criticalAY approved these changes

2024-03-07 20:28 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> +    }
I don't think its relevant to have it as method, but leaving it for reviewers, rest looks good

2024-03-07 20:29 UTC, Aditya13s commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> +    }
okay

2024-03-07 23:00 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> +        onBackPressedDispatcher.addCallback(this) {
why is this onStart and not onCreate?

2024-03-08 00:16 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
> +    }
Please do remove it

2024-03-08 15:38 UTC, david-allison approved these changes

2024-03-08 16:53 UTC, krmanik approved these changes
Looks good to me. Thanks

2024-03-08 17:11 UTC, merged