fix: dont reset scroll state
ankidroid/Anki-Android pull request #15803
Opened 2024-03-07 11:40 UTC by CyberButton

## Purpose / Description
Dont reset scroll state after deletion

## Fixes
* Fixes #15442 

## Approach
When user deletes a deck, state of the currently selected deck is reset to 1, while `focusedDeck` variable still holds
deck id of deleted deck, consequently when `renderPage()` is called it executes 
`if (focusedDeck != current) {
            scrollDecklistToDeck(current)
            focusedDeck = current
        }`
resetting the scroll state.
If we change `focusedDeck` to 1, then above if statement is skipped
## How Has This Been Tested?
manually

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-03-19 18:16 UTC, CyberButton commented
> Can you add a video?

Yes, here https://github.com/ankidroid/Anki-Android/assets/67738637/25049efe-62df-4870-830b-ce31707b2ac7

2024-03-28 14:42 UTC, CyberButton commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            focusedDeck = 1
I initially tried to set it to 0, but value of current deck was being set to 1, not 0. So setting it to 0 had no effect.

2024-03-28 14:56 UTC, CyberButton commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            focusedDeck = 1
Okay

2024-03-28 19:46 UTC, CyberButton commented
from what I observed after selecting and deleting a deck, value of current deck in `decks.current()` will be set to defualt - 1(which is  deck id of default deck), here I have a video demonstartion, I have specifically added 1 card into "Default" deck(so that it will be visibile in the decks list) to show that after deleting any deck, `decks.current()` will be rest to it.

https://github.com/ankidroid/Anki-Android/assets/67738637/95f212a2-2efc-47b7-a5c8-20fe9135b549

2024-03-28 19:49 UTC, CyberButton commented
If we just add `focusedDeck = 1` into the `deleteDeck()` function, scroll state will not update. Since both `focusedDeck` and `decks.current()` will be equal.

2024-03-28 19:51 UTC, CyberButton commented
Following the implementation of the requested changes and the clarification on the aforementioned condition, I kindly request a re-review.

2024-03-29 19:59 UTC, CyberButton commented
> > If we just add `focusedDeck = 1` into the `deleteDeck()` function, scroll state will not update. Since both `focusedDeck` and `decks.current()` will be equal.
> 
> Wouldn't this lead to another deck getting focused?

Yes, it would focus on another deck, specifically the "Default" deck with an ID of 1. This deck is always there; it can't be deleted and it's not visible if it's empty. When a deck is deleted, the system automatically sets the "Default" deck as the current one. I'm suggesting that we also update the value of the focused deck to match this, so we avoid any inconsistencies and prevent unnecessary auto-scrolling. However, I'm open to your suggestions, critiques, or any feedback you might have.

2024-03-29 19:59 UTC, CyberButton commented
> [#15803 (comment)](https://github.com/ankidroid/Anki-Android/pull/15803#issuecomment-2007844352)
> 
> In this video, aren't you already at the bottom while deleting? Just to confirm, try once while being at the top so that there's space for the scroll to happen.

Sure, here:

https://github.com/ankidroid/Anki-Android/assets/67738637/56572e71-cc14-4167-a602-2b844fafbba3

2024-04-09 22:30 UTC, david-allison requested changes
minor request, then good to go, thanks for the explanation

2024-04-09 23:49 UTC, david-allison approved these changes

2024-04-09 23:50 UTC, david-allison commented
Cheers! Sorry for the delay

2024-04-09 23:51 UTC, merged