test: close activity by continue button
ankidroid/Anki-Android pull request #15868
Opened 2024-03-12 17:31 UTC by SanjaySargam

## Purpose / Description

```kotlin
 @NeedsTest("activity can only be closed by tapping the continue button")
``` 

## Fixes

## Approach
Unit Test

## How Has This Been Tested?

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-03-12 17:38 UTC, SanjaySargam commented on AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt
> +            // Check if activity is finished
Ok

2024-03-12 18:19 UTC, david-allison requested changes
one nit, then good to go

2024-03-12 18:19 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt
> +            assert(activity.isFinishing)
```suggestion
            assertThat("activity is finishing", activity.isFinishing)
```

2024-03-12 18:19 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt
> +            assert(activity.isFinishing)
Use Hamcrest, not kotlin's `assert` for better error messages

2024-03-13 13:22 UTC, david-allison approved these changes
Perfect, thanks!

2024-03-13 18:30 UTC, BrayanDSO requested changes
The NeedsTest annotation says "**can only be** closed by the continue", while this test only check if the continue button finishes the activity, but not if other conditions, such as pressing back, can do that as well

2024-03-14 12:51 UTC, david-allison requested changes
per comment above

2024-03-14 13:11 UTC, SanjaySargam commented on AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt
> +            assertThat("activity is finishing", activity.isFinishing)
```kotlin
assertThat("activity is finishing", !activity.isFinishing)
``` 

When I do this, then test fails

2024-03-14 13:45 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt
> +            assertThat("activity is finishing", activity.isFinishing)
Either it's a problem in the screen, or a problem with the test

2024-03-21 12:39 UTC, BrayanDSO requested changes

2024-03-21 12:39 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt
>          onBackPressedDispatcher.addCallback {}
If I remove this line, which is what should prohibit closing the activity with the `back` button, the test also passes. So the test probably isn't testing this scenario

2024-03-21 23:06 UTC, david-allison commented
Sorry! Forgot to send the review!

I suspect that if you check the logs, the activity is closing BEFORE the test is executed, that's why `isFinishing` isn't set correctly

2024-03-23 09:35 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt
>          onBackPressedDispatcher.addCallback {}
Will you guide me how to achieve this

2024-03-23 09:42 UTC, SanjaySargam commented
> I suspect that if you check the logs, the activity is closing BEFORE the test is executed, that's why `isFinishing` isn't set correctly

How to check this unit test logs

2024-03-23 10:19 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt
>          onBackPressedDispatcher.addCallback {}
I'm also not sure how to do that

2024-03-24 01:43 UTC, david-allison commented
Either logcat, or in the `console` tab for test output

2024-03-31 02:03 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt
> +            assertThat("activity is not destroyed", !activity.isDestroyed)
If you step through the code, you'll find that the routine exits early due to this call

https://github.com/ankidroid/Anki-Android/blob/a872b53275b207f7d9bee195e3e09ae03efe53b3/AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt#L58-L59

2024-03-31 02:09 UTC, david-allison reviewed
I'd also consider:

```kotlin
        val permissionSet = IntentCompat.getParcelableExtra(intent, PERMISSIONS_SET_EXTRA, PermissionSet::class.java) 
            ?: return Unit.also { Timber.w("PERMISSIONS_SET_EXTRA not set") }
        val permissionsFragment = permissionSet.permissionsFragment?.getDeclaredConstructor()?.newInstance() ?: 
            return Unit.also { Timber.w("permissionsFragment not defined") }
```

since the lack of logging caused issues with unit tests

@BrayanDSO Would these be better as `require`, or could you see a valid reason why the invariant wouldn't be met

2024-03-31 02:27 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt
>          onBackPressedDispatcher.addCallback {}
First question, @SanjaySargam: did you try to reproduce what Brayan did ?
That is, deleting the line and checking the test succeed ?

2024-03-31 09:34 UTC, BrayanDSO commented
Can be done

2024-04-01 05:14 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt
>          onBackPressedDispatcher.addCallback {}
Yes, test succeed

2024-04-01 05:47 UTC, SanjaySargam commented on AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt
> +            assertThat("activity is not destroyed", !activity.isDestroyed)
where I have to setup back dispatcher

2024-04-02 04:31 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt
> +            assertThat("activity is not destroyed", !activity.isDestroyed)
It's already setup here, the lines just aren't reached

This can be seen if you step through the code in a debugger:

https://github.com/ankidroid/Anki-Android/blob/11d1c414cec871f02645c9ebb5dba3b9c6a84468/AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt#L59-L66

2024-04-02 04:34 UTC, david-allison requested changes
Also use `requireNotNull`:

```kotlin
        val permissionSet = requireNotNull(IntentCompat.getParcelableExtra(intent, PERMISSIONS_SET_EXTRA, PermissionSet::class.java)) {
            "PERMISSIONS_SET_EXTRA not set"
        }
        val permissionsFragment = requireNotNull(permissionSet.permissionsFragment?.getDeclaredConstructor()?.newInstance()) {
            "invalid permissionsFragment"
        }
```

See (resolved) conversation with Brayan

2024-04-03 16:19 UTC, SanjaySargam commented
> Also use `requireNotNull`:
> 
> ```kotlin
>         val permissionSet = requireNotNull(IntentCompat.getParcelableExtra(intent, PERMISSIONS_SET_EXTRA, PermissionSet::class.java)) {
>             "PERMISSIONS_SET_EXTRA not set"
>         }
>         val permissionsFragment = requireNotNull(permissionSet.permissionsFragment?.getDeclaredConstructor()?.newInstance()) {
>             "invalid permissionsFragment"
>         }
> ```
> 
> See (resolved) conversation with Brayan

used this but test fails

2024-04-04 14:09 UTC, SanjaySargam commented
> the lines just aren't reached (onBackPressedDispatcher.addCallback {} )


I made it reachable by removing return statement

2024-04-04 14:54 UTC, david-allison commented
> > Also use `requireNotNull`:
> > 
> > ```kotlin
> >         val permissionSet = requireNotNull(IntentCompat.getParcelableExtra(intent, PERMISSIONS_SET_EXTRA, PermissionSet::class.java)) {
> >             "PERMISSIONS_SET_EXTRA not set"
> >         }
> >         val permissionsFragment = requireNotNull(permissionSet.permissionsFragment?.getDeclaredConstructor()?.newInstance()) {
> >             "invalid permissionsFragment"
> >         }
> > ```
> > 
> > See (resolved) conversation with Brayan
> 
> used this but test fails

That's the point!

2024-04-05 03:49 UTC, SanjaySargam commented
Now `Each screen starts normally and has the same permissions of a PermissionSet` test fails. 

```
PermissionsActivityTest > Each screen starts normally and has the same permissions of a PermissionSet FAILED
    java.lang.IllegalArgumentException: PERMISSIONS_SET_EXTRA not set
```

2024-04-05 13:45 UTC, david-allison commented
```patch
Index: AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt	(revision 8df9eb5a2bef34a9f8868f70968f9fc1c0acdb94)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt	(date 1712324694435)
@@ -18,8 +18,10 @@
 import androidx.appcompat.widget.AppCompatButton
 import androidx.fragment.app.commitNow
 import androidx.test.core.app.ActivityScenario
+import androidx.test.core.app.ActivityScenario.ActivityAction
 import androidx.test.core.app.ApplicationProvider
 import androidx.test.ext.junit.runners.AndroidJUnit4
+import com.ichi2.anki.AnkiDroidFolder.AppPrivateFolder.permissionSet
 import com.ichi2.anki.PermissionSet
 import com.ichi2.anki.R
 import com.ichi2.anki.RobolectricTest
@@ -30,11 +32,9 @@
 
 @RunWith(AndroidJUnit4::class)
 class PermissionsActivityTest : RobolectricTest() {
-    private val permissionSet = PermissionSet.LEGACY_ACCESS // Example: Choose the appropriate enum constant based on your test scenario
     @Test
     fun testActivityCantBeClosedByBackButton() {
-        val intent = PermissionsActivity.getIntent(ApplicationProvider.getApplicationContext(), permissionSet)
-        ActivityScenario.launch<PermissionsActivity>(intent).onActivity { activity ->
+        testActivity(ARBITRARY_PERMISSION_SET) { activity ->
             activity.onBackPressedDispatcher.onBackPressed()
             assertThat("activity is not destroyed", !activity.isDestroyed)
         }
@@ -42,8 +42,7 @@
 
     @Test
     fun testActivityCanBeClosedByContinueButton() {
-        val intent = PermissionsActivity.getIntent(ApplicationProvider.getApplicationContext(), permissionSet)
-        ActivityScenario.launch<PermissionsActivity>(intent).onActivity { activity ->
+        testActivity(ARBITRARY_PERMISSION_SET) { activity ->
             activity.findViewById<AppCompatButton>(R.id.continue_button).performClick()
             assertThat("activity is finishing", activity.isFinishing)
         }
@@ -51,7 +50,7 @@
 
     @Test
     fun `Each screen starts normally and has the same permissions of a PermissionSet`() {
-        ActivityScenario.launch(PermissionsActivity::class.java).onActivity { activity ->
+        testActivity(ARBITRARY_PERMISSION_SET) { activity ->
             for (permissionSet in PermissionSet.entries) {
                 val fragment = permissionSet.permissionsFragment?.getDeclaredConstructor()?.newInstance() ?: continue
                 activity.supportFragmentManager.commitNow {
@@ -63,4 +62,15 @@
             }
         }
     }
+
+    private fun testActivity(permissionSet: PermissionSet, action: ActivityAction<PermissionsActivity>) {
+        val intent = PermissionsActivity.getIntent(ApplicationProvider.getApplicationContext(), permissionSet)
+        ActivityScenario.launch<PermissionsActivity>(intent).onActivity { activity ->
+            action.perform(activity)
+        }
+    }
+
+    companion object {
+        val ARBITRARY_PERMISSION_SET = PermissionSet.entries.first()
+    }
 }
```

2024-04-05 18:53 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt
> +            assertThat("activity is not destroyed", !activity.isDestroyed)
```suggestion
            assertThat("activity is finishing", activity.isFinishing)
```

2024-04-06 04:26 UTC, SanjaySargam commented on AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt
> +            assertThat("activity is not destroyed", !activity.isDestroyed)
I think it should
```kotlin
assertThat("activity is not finishing", !activity.isFinishing)
```  
because activity should not be closed when backpressed

2024-04-06 04:37 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt
> +            assertThat("activity is not destroyed", !activity.isDestroyed)
You're completely correct! Great catch

2024-04-08 23:26 UTC, david-allison approved these changes
Forgot to approve. Great job!

2024-04-13 10:45 UTC, lukstbit requested changes
The _testActivityCanBeClosedByContinueButton_ test passes by mistake because the button is disabled at that moment. You can see this by adding to the test the check below :

`assertTrue(activity.findViewById<AppCompatButton>(R.id.continue_button).isEnabled)`

which fails. I think the second test should be renamed to _testOnClickingContinueActivityFinishes_ to just test that clicking _continue_ calls _finish()_.

I don't think the annotation is resolved and it should be kept in the code. A real(and more useful) test would check the _continue_ button in relation to the permission switch being set/unset but that would be a more complicated scenario to test with the current code.

2024-04-17 15:53 UTC, lukstbit approved these changes

2024-04-17 16:09 UTC, merged