ui: use another shade in previewers' background
ankidroid/Anki-Android pull request #15893
Opened 2024-03-14 12:26 UTC by BrayanDSO

## Purpose / Description

Make things prettier

## How Has This Been Tested?

Emulator 34:

[light black.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/a5dea0bc-b620-4575-9e4d-8415ef4365f0)

[p light black.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/ad0ded13-a598-42f6-af19-229062cc9b3a)

[plain dark.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/daf1ef32-4753-4533-8d3f-e432697cc569)

## Learning (optional, can help others)
_Describe the research stage_

sometimes with a transparent navigationBarColor, a scrim will be applied to better visualize the buttons

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-03-14 12:29 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
> +        }
didn't do it in `CardViewerFragment` because I'm not sure if the new reviewer will look similar

2024-03-14 13:38 UTC, david-allison commented
As discussed on Discord: I strongly support adding a small amount of depth + a border to the card

2024-03-14 13:59 UTC, BrayanDSO commented
note: `Black` will look the same because I kept its 1990's `no contrast` style

2024-03-14 14:04 UTC, david-allison commented
I don't feel there's enough contrast on the light theme, and the background should be a tad darker

2024-03-14 14:35 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/Resources.kt
> +fun Context.getSystemBoolean(resName: String, fallback: Boolean): Boolean {
added a `@NeedsTest`. This is just to setup a color, so didn't seem urgent

2024-03-14 14:36 UTC, BrayanDSO commented
> I don't feel there's enough contrast on the light theme, so the background should be a tad darker

made it a little bit darker

![Screenshot_20240314_113642](https://github.com/ankidroid/Anki-Android/assets/69634269/42d650b0-9753-49e3-be6f-e2ebf7dc51d6)

2024-03-14 14:47 UTC, david-allison requested changes
That's beautiful! I don't understand the scrim logic

2024-03-14 14:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/Resources.kt
> +val FragmentActivity.navBarNeedsScrim: Boolean
I don't get this logic, could it be rewritten, or made more clear by extracting `Build.VERSION.SDK_INT < Build.VERSION_CODES.O_MR1` into a variable such as: `transparentNavBarIsAvailable`

* `Build.VERSION.SDK_INT < Build.VERSION_CODES.O_MR1` then this returns true

but the comment reads `and they can only be transparent in API ≥ 27`

2024-03-14 14:50 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/Resources.kt
> +val FragmentActivity.navBarNeedsScrim: Boolean
actually the API check isn't necessary. Thanks

2024-03-14 14:58 UTC, david-allison approved these changes
Beautiful, thanks!

2024-03-14 18:28 UTC, user1823 commented
This looks much better than the current UI. Thanks!

I suggest doing this for the Black theme too. If I am not misunderstanding it, you just need to replace `#000` in https://github.com/ankidroid/Anki-Android/pull/15893/files#diff-d0b2f770500ef1342008d6144c8d1003292e1f118e4124a60e622891b4bb68f5R50 with another color. What about `#101010`?

2024-03-15 12:02 UTC, lukstbit approved these changes
Looks nice, thanks!

2024-03-15 13:07 UTC, merged

2024-03-15 13:07 UTC, david-allison commented
Thank you so much for this!