fix: image name with unescaped chars
ankidroid/Anki-Android pull request #15890
Opened 2024-03-14 09:54 UTC by BrayanDSO

## Fixes
* Fixes #15844

## How Has This Been Tested?

Import an image with `%20` in its name

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-03-14 10:01 UTC, david-allison commented
Thanks! Could you drop a needstest for an integration test here

2024-03-14 10:01 UTC, david-allison approved these changes

2024-03-15 10:16 UTC, krmanik requested changes
For me it is not working during review, but when I edit note the image opened in IO editor.

> Failed to load resource: net::ERR_FILE_NOT_FOUND
> file:///storage/emulated/0/AnkiDroid/collection.media/Screenshot_20240315-180553_One%20UI%20Home.jpg

![image](https://github.com/ankidroid/Anki-Android/assets/12841290/dc545872-728c-4720-91f5-b60b6571dff1)

2024-03-15 11:46 UTC, krmanik commented
I found that in case of Anki Desktop the files are saved with space but in case of AnkiDroid the files are saved with `%20` instead of space.

2024-03-15 11:55 UTC, krmanik approved these changes
The issue lies somewhere else, approving.

2024-03-15 19:14 UTC, merged

2025-03-09 20:04 UTC, Sahil06012002 commented
@BrayanDSO , I tried to import the card provided in the issue here : https://github.com/ankidroid/Anki-Android/issues/15844#issuecomment-1987352338
and we are still not able to render this card in the current version. Is that the case for everyone or am I missing something?