Migrate version catalog for stable dependencies version between modules
ankidroid/Anki-Android pull request #15915
Opened 2024-03-16 14:24 UTC by AbdelrahmanEsam

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
* Fixes #

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-03-16 15:31 UTC, neeldoshii requested changes

2024-03-16 15:31 UTC, neeldoshii commented on settings.gradle.kts
> +
this file seems unnecessary change I guess this should be reverted.

2024-03-16 17:27 UTC, lukstbit requested changes
Thanks for contributing. I've left some requests for changes to implement, mostly related to naming and structure.

2024-03-16 17:27 UTC, lukstbit commented on gradle/libs.versions.toml
> +appcompatVersion = "1.7.0-alpha03"
Don't append the _Version_ suffix, these variables will only be used here and their placement under the _versions_ tab clearly states their purpose.

Also, please append the _androidx_ prefix to all versions of libraries that come from the androidx package(ex: _androidxAppcompat_) so it's easier to find them when scanning this file.

2024-03-16 17:27 UTC, lukstbit commented on gradle/libs.versions.toml
> +junit = "1.1.5"
We should split the versions(with a comment above about their target) in categories like normal, test and build(versions for plugins) dependencies. Mixing them like they are now makes it harder to find a version.

2024-03-16 17:27 UTC, lukstbit commented on gradle/libs.versions.toml
> +ankidroid_backend_version = '0.1.34-anki23.12.1'
We should stick with camel case for the versions names(ex. _ankidroidBackend_ and not _ankidroid_backend_version_)

2024-03-16 17:27 UTC, lukstbit commented on gradle/libs.versions.toml
> +amazonappstorepublisher = "3.9.0"
This is not the version that this plugin uses.

2024-03-16 17:27 UTC, lukstbit commented on gradle/libs.versions.toml
> +android-image-cropper = { module = "com.vanniktech:android-image-cropper", version.ref = "androidImageCropper" }
This name and others are too verbose. Better examples:

```
androidImageCropper = { module = "com.vanniktech:android-image-cropper", version.ref = "androidImageCropper" }
lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
tripletPlay = { id = "com.github.triplet.play", version.ref = "tripletPlay" }
etc.
```

There's no need to use as name the full package for example, just a name sufficient to identify the library.

2024-03-16 17:27 UTC, lukstbit commented on gradle/libs.versions.toml
> +androidx-fragment-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "fragmentKtxVersion" }
This library definition is duplicated below. It would be really helpful for reviewing if you could split the PR in multiple commits where in each commit you move the dependencies from one build file to the versions catalog.

2024-03-16 20:05 UTC, AbdelrahmanEsam commented on gradle/libs.versions.toml
> +android-image-cropper = { module = "com.vanniktech:android-image-cropper", version.ref = "androidImageCropper" }
I think this is the recommended way from google  we shouldn't use camelCase in dependencies names should we ?

2024-03-16 20:06 UTC, AbdelrahmanEsam commented on gradle/libs.versions.toml
> +amazonappstorepublisher = "3.9.0"
explain more please ... can you tell me which plugin please ?

2024-03-16 20:07 UTC, AbdelrahmanEsam commented on gradle/libs.versions.toml
> +junit = "1.1.5"
explain more please

2024-03-16 23:56 UTC, Arthur-Milchior commented
I'd very much appreciate if your commit message could contain more explanation.
Why are you doing that?
I admit I don't understand this PR at all.

Are you doing it to solve a bug ? If so, which bug ? What are going to be the difference for the user ?
It is a best practice for coding ? Will it change anything from the developer point of view ? Speed up compilation speed ? Ensure we don't get blocked by deprecated code later ?

2024-03-17 11:25 UTC, AbdelrahmanEsam commented
@Arthur-Milchior 
hi arthur ....what my pr is doing is that making all versions / dependencies /plugins  at one file so the mangement of them now is so much easier and with no confilcts between modules ... if we have more modules in the future this will be so much helpful

2024-03-18 07:09 UTC, david-allison commented on gradle/libs.versions.toml
> +junit = "1.1.5"
Instead of ordering the dependencies by name, first order them by category `[core, test, androidTest, build, etc..]` and then by name

This makes it easier for a developer to find a dependency in the list

I haven't researched whether version catalogs allow named categories, defer to @lukstbit for whether this is just adding comments, or whether there is also a syntax change

2024-03-18 15:33 UTC, david-allison commented on gradle/libs.versions.toml
> +junit = "1.1.5"
Not my area of expertise, I'll leave @lukstbit to opine

2024-03-20 17:04 UTC, lukstbit commented on gradle/libs.versions.toml
> +junit = "1.1.5"
@AbdelrahmanEsam I was referring to better arrange the versions and dependencies so they are easier and more logical to find when needed. One way we can do this is by splitting the versions between dependencies that are normally used with implementation(), dependencies that are used for testing and versions that are used for plugins. Mixing these versions in one list makes it harder to easily read them.
Also, we should keep the current setup(single dependencies) and not introduce bundles, this can be done at a later time.

Example:
```toml
[versions]
# standard dependencies versions
androidxSomething = "aaa"(ideally the versions would also be sorted alphabetically in each category)
...

# test dependencies versions
junit = "0.0"
...

# plugins versions
androidPlugin = "10.0.0"
....
```

2024-03-20 17:12 UTC, lukstbit commented on gradle/libs.versions.toml
> +android-image-cropper = { module = "com.vanniktech:android-image-cropper", version.ref = "androidImageCropper" }
> I think this is the recommended way from google we shouldn't use camelCase in dependencies names should we ?

It is recommended to use - so we get a nice package like behavior but adding the full package is very verbose. Example:

```toml
io-github-david-allison-one-anki-android-backend = { module = "io.github.david-allison-1:anki-android-backend", version.ref = "ankidroidBackend" }
io-github-david-allison-one-anki-android-backend-testing = { module = "io.github.david-allison-1:anki-android-backend-testing", version.ref = "ankidroidBackend" }
```

this would result in needing to add a lot of dashes to insert this dependencies which is verbose. Much better would be using the common namespace + the two dependencies with -:

```toml
ankiBackend-backend = { module = "io.github.david-allison-1:anki-android-backend", version.ref = "ankidroidBackend" }
ankiBackend-testing = { module = "io.github.david-allison-1:anki-android-backend-testing", version.ref = "ankidroidBackend" }
```

2024-03-20 18:14 UTC, lukstbit requested changes

2024-03-20 18:14 UTC, lukstbit commented on gradle/libs.versions.toml
> +org-jlleitschuh-gradle-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
Use just ktlint as name.

2024-03-20 18:14 UTC, lukstbit commented on gradle/libs.versions.toml
> +org-jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
Use just dokka as name.

2024-03-20 18:14 UTC, lukstbit commented on gradle/libs.versions.toml
> +com-github-triplet-play = { id = "com.github.triplet.play", version.ref = "triplet" }
Use just tripletPlay as name.

2024-03-20 18:14 UTC, lukstbit commented on gradle/libs.versions.toml
> +app-brant-amazonappstorepublisher = { id = "app.brant.amazonappstorepublisher", version.ref = "amazonappstorepublisher" }
Use just amazonappstorepublisher as name

2024-03-20 18:14 UTC, lukstbit commented on gradle/libs.versions.toml
> +io-github-david-allison-one-anki-android-backend = { module = "io.github.david-allison-1:anki-android-backend", version.ref = "ankidroidBackend" }
Use ankiBackend as namespace for the two related dependencies:
```toml
ankiBackend-backend = { module = "io.github.david-allison-1:anki-android-backend", version.ref = "ankidroidBackend" }
ankiBackend-testing = { module = "io.github.david-allison-1:anki-android-backend-testing", version.ref = "ankidroidBackend" }
```

2024-03-20 18:14 UTC, lukstbit commented on gradle/libs.versions.toml
> +org-hamcrest-hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
Just hamcrest(and for the other hamcrest related dependency)

2024-03-20 18:14 UTC, lukstbit commented on gradle/libs.versions.toml
> +com-android-tools-lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
Use just lint not the full package.

2024-03-20 18:14 UTC, lukstbit commented on gradle/libs.versions.toml
> +material-tap-target-prompt = { module = "uk.co.samuelwall:material-tap-target-prompt", version.ref = "materialTapTargetPrompt" }
One word.

2024-03-20 18:14 UTC, lukstbit commented on gradle/libs.versions.toml
> +hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
This is duplicated.

2024-03-20 18:14 UTC, lukstbit commented on gradle/libs.versions.toml
> +acra= ["acra-dialog","acra-http","acra-limiter","acra-toast"]
Can be deleted, we can add bundles at a later point.

2024-03-20 18:14 UTC, lukstbit commented on gradle/libs.versions.toml
> +kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
kotlinx not kotlin.

2024-03-20 18:54 UTC, lukstbit commented on gradle/libs.versions.toml
> +android-image-cropper = { module = "com.vanniktech:android-image-cropper", version.ref = "androidImageCropper" }
I don't think it's a fixed rule. At least remove the package parts from the dependencies names, those are verbose and not needed.

2024-03-20 19:00 UTC, lukstbit commented on gradle/libs.versions.toml
> +junit = "1.1.5"
Let's use individual dependencies for now(we can implement bundles at a later point), this PR is already difficult to review and doesn't need any extra changes. 

One second thought I think it would be better for the initial migration to simply have the versions and dependencies alphabetically.

2024-03-21 06:11 UTC, lukstbit requested changes
There's a conflict in _AnkiDroid/build.gradle_ that needs to be fixed.

Also, it would be nice if you could squash the commits from this(yours) branch into a single commit. This can be done from the command line [or the IDE directly](https://www.jetbrains.com/help/idea/edit-project-history.html#squash-commits).

2024-03-21 06:11 UTC, lukstbit commented on gradle/libs.versions.toml
> +#A
There's no need for this types of comments. Please remove them.

2024-03-21 08:22 UTC, david-allison requested changes
Looks great! A few nitpicks and we're good to go

2024-03-21 08:22 UTC, david-allison commented on AnkiDroid/build.gradle
> +    testImplementation libs.shared.preferences.mock
Make it more obvious that this is a nonstandard library

2024-03-21 08:22 UTC, david-allison commented on AnkiDroid/build.gradle
> +    compileOnly libs.annotations
List JetBrains

2024-03-21 08:22 UTC, david-allison commented on AnkiDroid/build.gradle
> +    implementation libs.drawer
List the vendor as it's nonstandard

2024-03-21 08:22 UTC, david-allison commented on AnkiDroid/build.gradle
> +    implementation libs.colorpicker
Ditto

2024-03-21 08:22 UTC, david-allison commented on gradle/libs.versions.toml
> +#A
No need for the letters as comments

2024-03-21 08:22 UTC, david-allison commented on lint-rules/build.gradle.kts
> +    compileOnly(libs.lint)
I'd expect libs.android.lint.api

2024-03-21 08:22 UTC, david-allison commented on settings.gradle.kts
> +include(":lint-rules", ":api", ":AnkiDroid", ":testlib")
Revert this file, no change made

2024-03-21 12:07 UTC, lukstbit commented
@AbdelrahmanEsam You didn't fixed the conflict that your branch has with the most recent code on the main branch(there was a new dependency added).

See below the message:
```
This branch has conflicts that must be resolved

Conflicting files
AnkiDroid/build.gradle 
```

2024-03-21 12:29 UTC, david-allison commented on AnkiDroid/build.gradle
> +    implementation libs.drawer.drakeet
drakeet.drawer?

2024-03-21 12:30 UTC, david-allison commented on AnkiDroid/build.gradle
> +    implementation libs.java.semver // For AnkiDroid JS API Versioning
I'd add in the author

2024-03-21 12:30 UTC, david-allison commented on AnkiDroid/build.gradle
> +    implementation libs.colorpicker
This was unchanged

2024-03-21 12:31 UTC, david-allison commented on AnkiDroid/build.gradle
> +    implementation libs.search.preference
Review 2: borderline add author

2024-03-21 12:32 UTC, david-allison commented on gradle/libs.versions.toml
> +[versions]
There's no need for newlines between each letter of the alphabet

2024-03-21 15:57 UTC, david-allison commented on AnkiDroid/build.gradle
> +    implementation libs.android.image.cropper
Maybe add author (for reviewer 2)

2024-03-21 21:42 UTC, AbdelrahmanEsam commented on AnkiDroid/build.gradle
> +    implementation libs.colorpicker
please explain more what changes you think please .... really few comments I have understood .

2024-03-21 21:58 UTC, AbdelrahmanEsam commented on AnkiDroid/build.gradle
> +    implementation libs.android.image.cropper
please explain

2024-03-21 21:59 UTC, AbdelrahmanEsam commented on AnkiDroid/build.gradle
> +    implementation libs.search.preference
please explain

2024-03-21 21:59 UTC, AbdelrahmanEsam commented on AnkiDroid/build.gradle
> +    implementation libs.java.semver // For AnkiDroid JS API Versioning
please explain

2024-03-21 21:59 UTC, closed without merging

2024-03-21 22:04 UTC, AbdelrahmanEsam commented
> @AbdelrahmanEsam You didn't fixed the conflict that your branch has with the most recent code on the main branch(there was a new dependency added).
> 
> See below the message:
> 
> ```
> This branch has conflicts that must be resolved
> 
> Conflicting files
> AnkiDroid/build.gradle 
> ```

sorry ? If you are talking about the work manager dependency I added it to the version catalog and resolved my conflict ?

2024-03-21 22:49 UTC, AbdelrahmanEsam commented on AnkiDroid/build.gradle
> +    implementation libs.timber.jakewharton
we have more than one timber so I have made theme slf4j.timber and jakewharton-timber

2024-03-21 23:00 UTC, david-allison commented on AnkiDroid/build.gradle
> +    implementation libs.android.image.cropper
`vanniktech` is excluded and we may want to include it (but I'm not sure)

This is a comment for Reviewer 2 to address or ignore