Rename Deck not show error initially.
ankidroid/Anki-Android pull request #15946
Opened 2024-03-20 14:58 UTC by Aditya13s

## Purpose / Description
The purpose of this change is to not show Deck already exits error message initially.

## Fixes
* Fixes #15944
* Closes #16030

## Approach
Added a check in which current test sequence of dialog box is matched with initial deck name
`text.toString() != initialDeckName`

## How Has This Been Tested?
Tested on multiple decks and working fine.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-03-20 15:12 UTC, david-allison requested changes
Thanks! Could you add a test:

> A unit test should be added to verify this functionality

2024-03-20 16:06 UTC, Aditya13s commented
@david-allison Please guide me in adding unit tests.

2024-03-20 16:43 UTC, david-allison commented
@Aditya13s Specifically what are you struggling with?

There are samples here: https://github.com/ankidroid/Anki-Android/blob/fa77cb5d79c999d48f1d85c69bd99f4efdb4f8cf/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt#L47

2024-03-21 15:08 UTC, Haz3-jolt commented
> I added a check in if statement that if currentText != initialDeckName then show error message. I want to test if the error message is shown initially or not.

You don't need to a add a unit test for it, usually small changes don't require a test case.

2024-03-21 15:12 UTC, Haz3-jolt commented
> I added a check in if statement that if currentText != initialDeckName then show error message. I want to test if the error message is shown initially or not.

IIRC fun testRenameDeckFunction should be what your searching for! Try modifying it and check if it works.

2024-03-21 15:14 UTC, prathvihan1008 commented
Should i still consider to pull a request my addressing the necessary changes?. This question may be silly since i  never contributed till now.  And one more doubt : what does it mean that the last 2 rows in the checklist are not marked as correct,does it mean that the pull request must satisfy those 2 checks too.

2024-03-21 16:03 UTC, prathvihan1008 commented
> > Should i still consider to pull a request my addressing the necessary changes?. This question may be silly since i  never contributed till now.  And one more doubt : what does it mean that the last 2 rows in the checklist are not marked as correct,does it mean that the pull request must satisfy those 2 checks too.
> 
> Last two rows are not much necessary for this pr

What about unit test, is it already added in the PR

2024-03-23 09:58 UTC, Aditya13s commented
@david-allison I have added a unit test case to check whether the "OK" button is enabled or disabled when the deck name matches.

2024-03-24 02:04 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt
> +            assertThat("Ok is enabled when deck names match", positiveButton.isEnabled, equalTo(true))
Other than the suggestion: the more important thing to test is that there's no error

```suggestion
            assertThat("Ok is enabled when deck names match", positiveButton.isEnabled)
```

2024-03-24 20:48 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt
> +            assertThat("Ok is enabled when deck names match", positiveButton.isEnabled, equalTo(true))
>  the more important thing to test is that there's no error

2024-03-26 08:16 UTC, Aditya13s commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt
> +            assertThat("Ok is enabled when deck names match", positiveButton.isEnabled, equalTo(true))
@david-allison I don't know what to do next.

2024-03-27 05:48 UTC, Aditya13s commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt
> +            assertThat("Ok is enabled when deck names match", positiveButton.isEnabled, equalTo(true))
@ro4i7 when the text box is empty then ok button disables and cannot rename the deck so we don't need to handle that situation it's already handled.

2024-03-30 21:25 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt
> +            assertThat("Ok is enabled when deck names match", positiveButton.isEnabled, equalTo(true))
```patch
Index: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt	(revision 0dce9a7c134234adacb91f8a5b71339d3501d935)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt	(date 1711833785094)
@@ -29,9 +29,11 @@
 import com.ichi2.anki.dialogs.CreateDeckDialog.DeckDialogType
 import com.ichi2.anki.dialogs.utils.input
 import com.ichi2.libanki.DeckId
+import com.ichi2.utils.getInputTextLayout
 import com.ichi2.utils.positiveButton
 import okhttp3.internal.closeQuietly
 import org.hamcrest.CoreMatchers.equalTo
+import org.hamcrest.CoreMatchers.nullValue
 import org.hamcrest.MatcherAssert.*
 import org.junit.Test
 import org.junit.runner.RunWith
@@ -200,6 +202,7 @@
         testDialog(DeckDialogType.RENAME_DECK) {
             input = previousDeckName
             assertThat("Ok is enabled when deck names match", positiveButton.isEnabled)
+            assertThat("no error is displayed", getInputTextLayout().error, nullValue())
         }
     }
```

2024-03-31 05:52 UTC, Aditya13s commented
@david-allison Please check the final changes.

2024-03-31 14:07 UTC, david-allison approved these changes
Perfect, thanks!

2024-04-01 09:39 UTC, lukstbit approved these changes

2024-04-01 09:40 UTC, lukstbit commented
Thanks, LGTM!

2024-04-02 18:38 UTC, david-allison approved these changes
Re-approving as PR was closed. Thanks!!

2024-04-02 18:39 UTC, david-allison commented
@Aditya13s In future, you'll get from 'pending merge' to 'merge' much faster if you squash and force-push your changes

2024-04-02 18:39 UTC, merged

2024-04-02 18:42 UTC, Aditya13s commented
> @Aditya13s In future, you'll get from 'pending merge' to 'merge' much faster if you squash and force-push your changes

I will remember that