Crop tool for image occlusion
ankidroid/Anki-Android pull request #15951
Opened 2024-03-20 21:16 UTC by awanishyadav967

##  Description
Here I  Implement a crop tool for the image occlusion feature. When a user selects an image from the gallery, the crop tool option will open before proceeding to the image occlusion editor.

## Fixes
* Fixes #15864

## Video Demo

https://github.com/ankidroid/Anki-Android/assets/91160609/d1d89997-e4ec-446e-b199-6ed849c6a557

## How Has This Been Tested?
  - Emulator: Pixel 5 (API 27)
   - Real Device: Realme 6 (Android Level 30)

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-03-20 21:28 UTC, david-allison commented
Emulator Tests failed, likely legit, I'm rerunning

2024-03-20 21:48 UTC, awanishyadav967 commented
> Emulator Tests failed, likely legit, I'm rerunning

Accidently I created feature/crop-function-demo instead of just crop-function-demo, going to correct this .

2024-03-20 23:24 UTC, david-allison commented
> > Emulator Tests failed, likely legit, I'm rerunning
> 
> Accidently I created feature/crop-function-demo instead of just crop-function-demo, going to correct this .

Branch name shouldn't cause a problem

2024-03-21 06:54 UTC, lukstbit requested changes
Please rebase your branch on top of main(and then push to update it here), as you have unrelated commits which makes it harder to review the actual changes:

```
git pull upstream main (I don't know if you have set a remote or you're updating main through the github UI here)
git checkout yourBranch
git rebase main
git push yourBranch
```

2024-03-21 06:54 UTC, lukstbit commented on .idea/dictionaries/Avanish.xml
> +      <w>avanish</w>
We have an _.idea/dictionaries/username.xml_ dictionary file, you should put your username there instead of creating a new file

2024-03-21 20:11 UTC, closed without merging

2024-03-22 14:50 UTC, david-allison commented
@awanishyadav967 please don't close and recreate pull requests in future.

Instead, rebase and force push

2024-03-22 15:16 UTC, awanishyadav967 commented
> @awanishyadav967 please don't close and recreate pull requests in future.
> 
> Instead, rebase and force push

I got it ,this is last time  I did this ,in future I will do rebase only.