Migrate version catalog
ankidroid/Anki-Android pull request #15966
Opened 2024-03-22 10:01 UTC by AbdelrahmanEsam

migrate to version catalog for stable dependency injection between modules

https://github.com/ankidroid/Anki-Android/pull/15915

2024-03-22 16:34 UTC, david-allison requested changes

2024-03-22 16:34 UTC, david-allison commented on AnkiDroid/build.gradle
> +   implementation libs.acra.http
These are each misaligned with the rest of the file - add a space before each line

2024-03-22 16:34 UTC, david-allison commented on AnkiDroid/build.gradle
> +    androidTestImplementation(libs.espresso.contrib) {
Why are these `espresso`, but the ones below `androidx.test.xxx`

2024-03-22 16:34 UTC, david-allison commented on AnkiDroid/build.gradle
> +    androidTestImplementation libs.test.rules
why is this not `androidx`

2024-03-22 16:34 UTC, david-allison commented on AnkiDroid/build.gradle
> +    androidTestImplementation libs.androidx.junit
Why is this not `androidx.test.junit`

2024-03-22 16:34 UTC, david-allison commented on gradle/libs.versions.toml
> +acra = '5.11.3'
I don't feel the comments on the previous PR were addressed

The goal is to sort by use (core, test, androidTest), then alphabetically

This is just alphabetical

2024-03-22 17:10 UTC, AbdelrahmanEsam commented on gradle/libs.versions.toml
> +acra = '5.11.3'
sorry explain more please ?

2024-03-22 17:10 UTC, AbdelrahmanEsam commented on gradle/libs.versions.toml
> +acra = '5.11.3'
what do you mean by core ? dependencies needed in the application itself ? not test or android test ?

2024-03-22 17:11 UTC, AbdelrahmanEsam commented on AnkiDroid/build.gradle
> +    androidTestImplementation libs.androidx.junit
it was like this before but one of the reviewers said to me that names like these is too long .... what should I do ? stick with the standards or make it as short as possible ?

2024-03-22 17:12 UTC, AbdelrahmanEsam commented on AnkiDroid/build.gradle
> +    androidTestImplementation libs.test.rules
++

2024-03-22 17:12 UTC, AbdelrahmanEsam commented on AnkiDroid/build.gradle
> +    androidTestImplementation(libs.espresso.contrib) {
++

2024-03-23 17:39 UTC, lukstbit requested changes

2024-03-23 17:39 UTC, lukstbit commented on gradle/libs.versions.toml
> +lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
Should be _android-lint-api_.

2024-03-23 17:39 UTC, lukstbit commented on gradle/libs.versions.toml
> +hamcrest-library = { module = "org.hamcrest:hamcrest-library", version.ref = "hamcrest" }
Should be in the _testing libs_, near the standard _hamcrest_ defined library.

2024-03-23 17:39 UTC, lukstbit commented on gradle/libs.versions.toml
> +junit = "1.1.5"
This name is confusing, it's used with _androidx-test-junit_ so it should use that name _androidTestJunit_.

2024-03-23 17:39 UTC, lukstbit commented on gradle/libs.versions.toml
> +core = { module = "com.afollestad.material-dialogs:core", version.ref = "androidxTextCore" }
_core_ is too general, it should be _materialDialogs-core_.

2024-03-23 17:39 UTC, lukstbit commented on gradle/libs.versions.toml
> +input = { module = "com.afollestad.material-dialogs:input", version.ref = "input" }
_input_ is too general, it should be _materialDialogs-input_(and placed near the other _materialDialogs*_ dependency).

2024-03-23 17:39 UTC, lukstbit commented on gradle/libs.versions.toml
> +androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTextCore" }
Should be in the testing libs group of dependencies.

2024-03-23 17:39 UTC, lukstbit commented on gradle/libs.versions.toml
> +androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
Be consistent and use _module + version_ like all the other declared dependencies.

2024-03-23 17:39 UTC, lukstbit commented on gradle/libs.versions.toml
> +androidx-runner = { module = "androidx.test:runner", version.ref = "androidxRunner" }
androidx-test-runner

2024-03-23 17:39 UTC, lukstbit commented on gradle/libs.versions.toml
> +androidx-rules = { module = "androidx.test:rules", version.ref = "androidxTextCore" }
androidx-test-rules

2024-03-24 01:42 UTC, david-allison requested changes
I think this is it. One name change requested

2024-03-24 01:42 UTC, david-allison commented on AnkiDroid/build.gradle
> +    implementation libs.google.analytics.java7
This is not a google dependency. This is a dependency for Google Analytics

2024-03-24 01:42 UTC, david-allison commented on AnkiDroid/build.gradle
> +    testImplementation(libs.androidx.fragment.testing)
I don't think we need the `()` now

2024-03-24 01:42 UTC, david-allison commented on AnkiDroid/build.gradle
> +    testImplementation(libs.androidx.espresso.contrib) {
is it possible to remove the `()`, or is this needed for the `{ }`

2024-03-24 01:42 UTC, david-allison commented on gradle/libs.versions.toml
> +acra = '5.11.3'
Resolving as-per https://github.com/ankidroid/Anki-Android/pull/15915#discussion_r1532644052

2024-03-24 09:42 UTC, AbdelrahmanEsam commented on AnkiDroid/build.gradle
> +    testImplementation(libs.androidx.espresso.contrib) {
this is needed for the { }

2024-03-24 20:36 UTC, david-allison approved these changes
Only nitpicks, cheers!

2024-03-24 20:36 UTC, david-allison commented on AnkiDroid/build.gradle
> +    debugImplementation(libs.androidx.fragment.testing.manifest)
`()` probably isn't needed

2024-03-24 20:36 UTC, david-allison commented on AnkiDroid/build.gradle
> +    testImplementation(libs.androidx.fragment.testing)
Why was this resolved?

2024-03-24 20:36 UTC, david-allison commented on settings.gradle.kts
> +include(":lint-rules", ":api", ":AnkiDroid", ":testlib")
could you revert this file

2024-03-26 17:46 UTC, lukstbit approved these changes
LGTM, thank you for contributing!

2024-03-27 00:53 UTC, merged