Crop tool for image occlusion
ankidroid/Anki-Android pull request #15961
Opened 2024-03-21 21:40 UTC by awanishyadav967

##  Description
Here I Implement a crop tool for the image occlusion feature. When a user select an image from the gallery, the crop tool option will open before proceeding to the image occlusion editor.

## Fixes
* Fixes #15864 

## Video Demo

https://github.com/ankidroid/Anki-Android/assets/91160609/fcec0e90-dbf9-4333-b918-d890642d6fe9

## How Has This Been Tested?
 Realme 6 (Android Level 30)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-03-21 22:02 UTC, SanjaySargam commented
Test fails
```
BasicImageFieldControllerTest > constructionWithDataSucceeds FAILED
    kotlin.UninitializedPropertyAccessException: lateinit property registryToUse has not been initialized
```

2024-03-21 22:09 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
> -        val registryToUse = if (this::registryToUse.isInitialized) registryToUse else this._activity.activityResultRegistry
Why you removed this

2024-03-22 04:05 UTC, krmanik commented
Before adding image, it asks for crop, functionality wise it is good but what if some users just want to add image without intermediate crop action. The feature should be included in IO editor which avoid implementation for each client.

2024-03-22 09:50 UTC, criticalAY commented
It would be better to add the crop option where we have IO fragment

2024-03-22 18:20 UTC, Sagar0-0 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
> +            ImageUtils.cropImage(_activity.activityResultRegistry, it) { cropResult ->
This code is duplicate, we can use a function and add success callbacks

2024-03-22 18:31 UTC, Sagar0-0 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            ImageUtils.cropImage(activityResultRegistry, imageUri) { result ->
This code can be added to a function and we can have success callback as it is also duplicate in BasicImageFieldController .

2024-03-24 02:00 UTC, david-allison requested changes
`cropImage` seems to be incorrectly implemented

2024-03-31 01:36 UTC, neeldoshii commented on .idea/dictionaries/usernames.xml
> +      <w>Avanish</w>
What is the need of this change? (haven't tested locally)

2024-03-31 17:43 UTC, josephShokry commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                }
for more nit code you can write it like that 
```
if (result?.isSuccessful == true) {
    val uriFilePath = result.getUriFilePath(this)
    uriFilePath?.let { setupImageOcclusionEditor(it) } ?: run {
        Timber.v("Failed to get the file path from the cropped image URI")
    }
} else {
    Timber.v("Failed to crop the image")
}
```

2024-03-31 17:43 UTC, josephShokry commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
> +                        imageFileSizeWarning.visibility = View.GONE
`isVisible` is typically better instead of visibility 
try `imageFileSizeWarning.isVisible = false`

2024-05-02 12:43 UTC, closed without merging