Enhancement: notification permission in SDK>=33
ankidroid/Anki-Android pull request #15977
Opened 2024-03-23 11:13 UTC by criticalAY

## Purpose / Description
No notification is shown in SDK>=33 if user doesn't grant notification permission, we here handle the issue and ask the user for notification permission and in case they deny first time we show a rationale (dialog) explaining why we need it, leaving it up to the user if they still want ti deny or grant the permission 

## Fixes
* Fixes #15952

## Approach
As explained on discord 

The general flow is System notification dialog 
* Granted -> Continue
* Not granted  -> Show rationale explaining the need for it -> if user agrees show the system notification dialog again -> user grants permission
* Not granted  -> Show rationale explaining the need for it -> if user agrees show the system notification dialog again -> user doesn't grant it -> continue without it and disable that feature
* Not granted -> Show rationale -> user skips it -> continue without it
## How Has This Been Tested?
![Screenshot 2024-03-23 163329](https://github.com/ankidroid/Anki-Android/assets/48384865/b47a2464-e815-4b99-87a6-c822db64d2ca)
![Screenshot 2024-03-23 163341](https://github.com/ankidroid/Anki-Android/assets/48384865/7424354c-fa80-43dc-ada9-82d071bbf05b)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-03-23 11:21 UTC, criticalAY commented
Not blocking the sync process here, if they are new user the dialog is shown on top of the login/signup dialog same for the rational, and if existing user if they press the sync button then it would pop up, by default the permission is not granted and if not granted a rational would be shown or permission would be requested

2024-03-24 21:06 UTC, david-allison commented
Can we move the UX discussion back to the issue [or at very least summarise the discussion outside Discord - it's not searchable]? 

I feel we can do better here

2024-03-24 23:45 UTC, Arthur-Milchior commented
I'd expect that we also need notification if the user wanted to have remainders. Isn't it the case ?

2024-03-27 10:50 UTC, BrayanDSO commented
This will likely take some time to discuss.

For now, could you just ask the permission? No dialogs explaining anything, nor a `NotificationPermission` class. Just ask the permission and don't care if it has been granted

2024-03-27 14:34 UTC, criticalAY commented
Ok will do 👍🏼

2024-03-28 19:12 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        // let works fine here as we return early in method
* This needs to be removed
* I will wait for the discussion over the notification rationale and how we want to proceed with it and then start fresh with new PR

2024-03-28 19:46 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        if (IntentHandler.grantedStoragePermissions(this, false)) {
If we don't check then the permission dialog would be shown as soon as the app is opened, sometimes on the permission screen, but since we are moving to login screen we might not need it

2024-03-28 20:01 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        // let works fine here as we return early in method
It was left from the previous commit, and needed to be removed

2024-03-28 20:02 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        // do nothing for now see #15977
if it doesn't do nothing, don't add it

2024-03-28 20:02 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        // do nothing for now see #15977
Quoting myself

>  Just ask the permission and don't care if it has been granted

2024-03-28 20:39 UTC, criticalAY commented
We can just ask for permission as soon as user goes on the login screen, to avoid calling code form 2 places, the outcome is same

2024-04-01 20:12 UTC, BrayanDSO commented
It is asking me the permission when I open the Log-in screen. Could you change it to ask the permission after the user logged in?

2024-04-01 23:12 UTC, BrayanDSO approved these changes
LGTM. Thanks!

2024-04-02 19:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
> +            if (permission != null && ContextCompat.checkSelfPermission(
Can a user continue if they deny permission?

2024-04-02 19:12 UTC, david-allison requested changes
Question only

2024-04-02 19:13 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
> +            if (permission != null && ContextCompat.checkSelfPermission(
Yes, it doesn't affect the app functioning

2024-04-02 22:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
> +            if (permission != null && ContextCompat.checkSelfPermission(
Could you deny the permission twice and add a comment explaining what happens to this method on "permanent rejection of permission"

I was evaluating an app this morning which failed to start if it didn't have notification permission, so I'm a little paranoid here

2024-04-03 02:12 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
> +            if (permission != null && ContextCompat.checkSelfPermission(
Ok so I tested it thoroughly and gist is that sync is not affected
* I dismiss the dialog when I first login without allowing or denying the permission -> synced 
* I deny the permission -> collection is synced
* I grant the permission -> synced

2024-04-03 02:44 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
> +            if (permission != null && ContextCompat.checkSelfPermission(
In addition to this patch, also log in `MyAccount`

```patch
Subject: 
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt b/AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt	(revision 8c228b03e402811ab928ebf8c21e1152787aa0d5)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt	(date 1712112043985)
@@ -258,6 +258,16 @@
         internal const val STATE_LOG_IN = 1
         internal const val STATE_LOGGED_IN = 2
 
+        /**
+         * Displays a system prompt: "Allow AnkiDroid to send you notifications"
+         *
+         * [launcher] receives a callback result (`boolean`) unless:
+         *  * Permissions were already granted
+         *  * We are < API 33
+         *
+         * Permissions may permanently be denied, in which case [launcher] immediately
+         * receives a failure result
+         */
         fun checkNotificationPermission(
             context: Context,
             launcher: ActivityResultLauncher<String>
Index: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt	(revision 8c228b03e402811ab928ebf8c21e1152787aa0d5)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt	(date 1712112043975)
@@ -390,7 +390,9 @@
         true
     }
 
-    private val notificationPermissionLauncher = registerForActivityResult(ActivityResultContracts.RequestPermission()) {}
+    private val notificationPermissionLauncher = registerForActivityResult(ActivityResultContracts.RequestPermission()) {
+        Timber.i("notification permission: %b", it)
+    }
 
     // ----------------------------------------------------------------------------
     // ANDROID ACTIVITY METHODS
```

2024-04-03 02:46 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
> +            if (permission != null && ContextCompat.checkSelfPermission(
Will do in a few hours

2024-04-03 02:46 UTC, david-allison reviewed
I like this (and will approve, as this is an improvement), but I'm not happy with the UX of the background sync (which feels external to this PR)

Currently there is no way to cancel the media sync (including force closing the app!), that's not a good UX

2024-04-03 15:39 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
> +            if (permission != null && ContextCompat.checkSelfPermission(
Done

2024-04-05 02:36 UTC, david-allison approved these changes

2024-04-05 16:34 UTC, lukstbit commented
@criticalAY https://github.com/ankidroid/Anki-Android/labels/squash-merge

2024-04-05 19:45 UTC, merged

2024-04-05 19:57 UTC, david-allison commented
Strings changes were removed - Sync Translations failed