Heirarchical deck selection
ankidroid/Anki-Android pull request #15988
Opened 2024-03-24 15:45 UTC by josephShokry

## Purpose / Description
This PR introduces a hierarchical menu in the browser for selecting decks, improving user experience by enabling easier navigation through decks.

the deck search
Before
![image](https://github.com/ankidroid/Anki-Android/assets/96320048/47b8b745-8a0b-4e5f-8ba2-9032b18a707b)

After
![image](https://github.com/ankidroid/Anki-Android/assets/96320048/e061259d-226e-47ad-ac55-8c4b7285a072)

## Fixes
* Fixes #15646

## Approach
open Card browser> Deck Search you will the new hierarchical deck selection

## How Has This Been Tested?

The feature has been tested both on emulator (Pixel 5 API 30) and physical device (Realme 7).

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-03-24 15:57 UTC, david-allison commented
Thanks! Tests are failing and will likely need to be updated

2024-03-25 08:31 UTC, SanjaySargam commented
```
DeckSelectionDialogTest > verifyDeckDisplayName FAILED
    java.lang.AssertionError: 
    Expected: "\t\t\t\t\t\tsub-deck3"
         but: was "sub-deck3"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at com.ichi2.anki.dialogs.DeckSelectionDialogTest.verifyDeckDisplayName(DeckSelectionDialogTest.kt:34)

```

2024-03-25 11:35 UTC, neeldoshii requested changes

2024-03-25 11:35 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +                    notifyDataSetChanged() // Update UI
comments can be removed here.

2024-03-25 11:35 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +                notifyDataSetChanged() // Update UI
same.

2024-03-25 14:25 UTC, josephShokry commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +                notifyDataSetChanged() // Update UI
done!

2024-03-25 18:25 UTC, Sagar0-0 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +        val ta = context?.obtainStyledAttributes(attrs)
What is "ta" here? It will be better if we are using more readable names for variables

2024-03-25 21:16 UTC, david-allison requested changes
The margin on the left hand side is a little too large

The expansion status of the decks doesn't match the home screen

* I have `English::Vocab`, searching for `Vocab` produces nothing if `Vocab` is searched for and `English` is not expanded

<img width="363" alt="Screenshot 2024-03-25 at 21 02 14" src="https://github.com/ankidroid/Anki-Android/assets/62114487/49cd75d2-8ac4-4f23-ad06-6be9a2745b3b">

2024-03-25 21:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +                holder.itemView.visibility = View.VISIBLE
`isVisible` is typically better

2024-03-25 21:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            runBlocking { setDeckExpander(holder.expander, holder.indentView, deck) }
why is this `runBlocking`?

2024-03-25 21:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +        private fun findNodeLevel(node: SelectableDeck): Int {
I'd rename this to `findNodeDepth`

2024-03-25 21:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            return allDecksList.any { it.name.startsWith("${node.name}::") }
can this be `contains("::")`

2024-03-26 10:17 UTC, josephShokry commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +                holder.itemView.visibility = View.VISIBLE
I can't use `isVisible` as I have to implement my logic of deck visibility.
do you suggest just changing the name of my method?

2024-03-26 10:23 UTC, josephShokry commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            runBlocking { setDeckExpander(holder.expander, holder.indentView, deck) }
you are right there is no need for `runBlocking` coroutine

2024-03-26 10:31 UTC, josephShokry commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            return allDecksList.any { it.name.startsWith("${node.name}::") }
The node that this method checks if it has subDecks its "::" in its name doesn't indicate that it has subdecks.
so to check if node `X` has subDecks we should 
iterate for all decks and check if there is any node `Y` where `Y.name` starts with `X.name`
why just check `Y.name.contains(X.name)`?  because this case
X name is `deck1`
Y name is `anotherDeck::deck1::subDeck`
in this case deck `Y` is not a subDeck of deck `X` instead it it a subDeck of the Deck which name is `anotherDeck::deck1`

2024-03-28 12:27 UTC, david-allison requested changes
Comments: One request on `SelectableDeck`, the rest are nitpicks and can be ignored

Implementation: the `expanded` status doesn't match the Deck Picker. This makes it harder to select decks than it previously was

2024-03-28 12:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +        collapseImage.isAutoMirrored = true
nit: Kotlin Scope function

2024-03-28 12:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +                holder.itemView.visibility = View.VISIBLE
This seems to work:

```kotlin
holder.itemView.isVisible = true
```

2024-03-28 12:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +        var parentDeck: SelectableDeck? = null
It would be nicer to wrap this class in a representation which is only used in `DeckSelectionDialog`. 

`SelectableDeck` is exposed by `DeckSelectionDialog`, and we don't want to make class-based implementation details public

Especially when these implementation details will not be correct when used outside the class

2024-03-28 12:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +                expander.apply {
nit: this feels like it should also be inside the `.apply {`

2024-03-28 12:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +                    isExpanded = !isExpanded
It would be useful to `Timber.d` the deck Id + expansion state change

2024-03-28 12:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +    class SelectableDeck(val deckId: DeckId, val name: String, var isExpanded: Boolean = false) : Comparable<SelectableDeck>, Parcelable {
It likely shouldn't be in the class scope, and instead should be in a class which wraps `SelectedDeck`

2024-03-31 17:40 UTC, david-allison commented
Was this handled?

> Implementation: the expanded status doesn't match the Deck Picker. This makes it harder to select decks than it previously was

2024-03-31 17:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            val deck = allDecksList.map { it.selectableDeck }.firstOrNull { it.name == deckName }
might as well delegate `name` to `selectableDeck.name` in the class

2024-03-31 17:52 UTC, josephShokry commented
> not handled yet. can you give me more information about the problem
>> Was this handled?
>> 
>> > Implementation: the expanded status doesn't match the Deck Picker. This makes it harder to select decks than it previously was

2024-03-31 18:02 UTC, david-allison commented
Let's say I have a deck structure like so:

![Screenshot 2024-03-31 at 19 00 59](https://github.com/ankidroid/Anki-Android/assets/62114487/e1024dd3-7775-4d7c-a91e-ea91af4d1afc)

With the previous screen, it took 1  tap to select the child deck

With the new screen, it takes 5 taps to select the child deck

2024-04-16 15:30 UTC, david-allison requested changes
This is really good, thanks!

The main issue is that 'All Decks' should be a leaf node at the top of the tree, rather than being the root node of all decks

In addition, the image below implies that there may also be an issue with an alphabetical ordering

![Screenshot 2024-04-16 at 16 28 08](https://github.com/ankidroid/Anki-Android/assets/62114487/782c8ccb-16b1-4e08-8aff-ec49bc7ff2e9)

----

* Could you add a couple of `@NeedsTest` annotations for the issues found - we'll fix these outside this PR

2024-04-16 15:30 UTC, david-allison commented on AnkiDroid/src/main/res/layout/deck_picker_dialog_list_item.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Here's a quick patch which fixes:

* Layout Preview
* the long-press ripple effect was only on the TextView, rather than on the entire row

```patch
Subject: [PATCH] aa
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt	(revision c47d07f9b47649917bd3077179fe1c9d2f642866)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt	(date 1713280914225)
@@ -245,13 +245,13 @@
             }
 
             init {
-                deckTextView.setOnClickListener {
+                deckHolder.setOnClickListener {
                     selectDeckByIdAndClose(deckID)
                 }
                 expander.setOnClickListener {
                     toggleExpansion(deckID)
                 }
-                deckTextView.setOnLongClickListener { // creating sub deck with parent deck path
+                deckHolder.setOnLongClickListener { // creating sub deck with parent deck path
                     if (deckID == DeckSpinnerSelection.ALL_DECKS_ID) {
                         context?.let { showThemedToast(it, R.string.cannot_create_subdeck_for_all_decks, true) }
                     } else {
Index: AnkiDroid/src/main/res/layout/deck_picker_dialog_list_item.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/res/layout/deck_picker_dialog_list_item.xml b/AnkiDroid/src/main/res/layout/deck_picker_dialog_list_item.xml
--- a/AnkiDroid/src/main/res/layout/deck_picker_dialog_list_item.xml	(revision c47d07f9b47649917bd3077179fe1c9d2f642866)
+++ b/AnkiDroid/src/main/res/layout/deck_picker_dialog_list_item.xml	(date 1713281052993)
@@ -15,6 +15,7 @@
   this program.  If not, see <http://www.gnu.org/licenses/>.
   -->
 <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
+    xmlns:tools="http://schemas.android.com/tools"
     android:id="@+id/DeckPickerHoriz"
     android:background="?attr/selectableItemBackground"
     android:layout_width="match_parent"
@@ -22,7 +23,8 @@
     android:gravity="center_vertical"
     android:orientation="horizontal"
     android:paddingStart="1dp"
-    android:paddingEnd="@dimen/deck_picker_right_padding">
+    android:paddingEnd="@dimen/deck_picker_right_padding"
+    tools:showIn="@layout/deck_picker_dialog">
     <ImageButton
         android:id="@+id/deckpicker_indent"
         android:minWidth="0dp"
@@ -32,7 +34,7 @@
         />
     <LinearLayout
         android:id="@+id/deck_name_linear_layout"
-        android:layout_width="wrap_content"
+        android:layout_width="match_parent"
         android:layout_height="wrap_content"
         android:orientation="horizontal"
         android:gravity="center_vertical">
@@ -43,24 +45,20 @@
             android:minWidth="48dp"
             android:padding="12dp"
             android:background="?attr/selectableItemBackgroundBorderless"
+            tools:src="@drawable/ic_expand_more_black"
             />
 
-        <!-- An item in a deck selection screen. Partially based off deck_item -->
         <com.ichi2.ui.FixedTextView
-            xmlns:tools="http://schemas.android.com/tools"
-            tools:showIn="@layout/deck_picker_dialog"
             android:id="@+id/deckpicker_name"
             android:layout_width="match_parent"
             android:layout_height="wrap_content"
             android:minHeight="?android:attr/listPreferredItemHeight"
             android:paddingEnd="8dp"
             android:gravity="start|center_vertical"
-            android:background="?attr/selectableItemBackground"
             android:textStyle="bold"
             android:textSize="20sp"
             android:textIsSelectable="false"
-            android:focusable="true"
-            android:clickable="true"
+            tools:text="Deck Name"
         />
     </LinearLayout>
 </LinearLayout>
```

2024-04-17 09:46 UTC, josephShokry commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            return !parentNode.get()?.collapsed!! && isViewable(parentNode.get()!!)
yes because there may be a subdeck that is expanded and should be viewable but one of its parents is not expanded so the subdeck also shouldn't be viewable, and this also saves the state of subdecks so when you toggle the parent the subdeck will be viewed depending on the previous state of it before collabsing the parent.

2024-04-17 11:15 UTC, josephShokry commented
I have resolved it, you can check it now

2024-04-17 13:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            return !parentNode.get()?.collapsed!! && isViewable(parentNode.get()!!)
Does the collapsed property not handle this?

2024-04-17 15:15 UTC, josephShokry commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            return !parentNode.get()?.collapsed!! && isViewable(parentNode.get()!!)
no, I have tried it too, to make sure.
the collapsed property tells us whether this node is collapsed or not but for a node to be viewed all its parents in the tree should be expanded (!collapsed) that is what I do by recursion.

2024-04-17 17:05 UTC, david-allison requested changes
"All Decks" appears in the note editor

2024-04-18 23:02 UTC, david-allison commented
I don't believe my comment was taken into account as there was no pushes afterwards

2024-04-19 07:08 UTC, josephShokry commented
> I don't believe my comment was taken into account as there was no pushes afterwards

Actually my updates for the bug is pushed but I don't know why it doesn't appear here.
here one of my last changes to handel "All decks appears in the note editor"
```
   private fun updateCurrentlyDisplayedDecks() {
            currentlyDisplayedDecks.clear()
            currentlyDisplayedDecks.addAll(allDecksList.filter(::isViewable))
            currentlyDisplayedDecks.sortWith(compareBy({ it.fullDeckName != getString(R.string.card_browser_all_decks) }, { it.fullDeckName }))
            notifyDataSetChanged()
        }
```
and here is the hash of my commit 
e277cbe48526a18474073cfc98d907e6478fb22b

2024-04-19 07:34 UTC, josephShokry commented
Actually it appears here
![image](https://github.com/ankidroid/Anki-Android/assets/96320048/6883d6da-e91b-4ca6-9a11-527a76adbd7c)

2024-04-20 20:50 UTC, david-allison requested changes
Order is incorrect. Please also add a `@NeedsTest` for this so we can add regression cover later

**Before**
![Screenshot 2024-04-20 at 21 47 49](https://github.com/ankidroid/Anki-Android/assets/62114487/00ed7a56-9acc-4707-bb3c-15a8395bcfbd)

**After**
![Screenshot 2024-04-20 at 21 50 25](https://github.com/ankidroid/Anki-Android/assets/62114487/260174ef-cd3a-4ef5-82df-2ae5d3175f90)

2024-04-20 23:34 UTC, david-allison requested changes

2024-04-20 23:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            currentlyDisplayedDecks.sortWith(
This seems complicated as it no longer user `SelectableDeck.compareTo`

Why not use the order returned from the backend?

Untested patch:

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt	(revision aa51fd1a6be6f5d833a62a19dd5c9fd76112e39d)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt	(date 1713655884440)
@@ -49,7 +49,6 @@
 import com.ichi2.libanki.DeckId
 import com.ichi2.libanki.DeckNameId
 import com.ichi2.libanki.sched.DeckNode
-import com.ichi2.utils.DeckNameComparator
 import com.ichi2.utils.KotlinCleanup
 import com.ichi2.utils.TypedFilter
 import kotlinx.parcelize.IgnoredOnParcel
@@ -277,15 +276,6 @@
         private fun updateCurrentlyDisplayedDecks() {
             currentlyDisplayedDecks.clear()
             currentlyDisplayedDecks.addAll(allDecksList.filter(::isViewable))
-            currentlyDisplayedDecks.sortWith(
-                compareBy({ it.fullDeckName != getString(R.string.card_browser_all_decks) }, {
-                    it.fullDeckName.lowercase(
-                        Locale.getDefault()
-                    )
-                })
-            )
-//            currentlyDisplayedDecks.sortWith(compareBy({ it.fullDeckName.toLowerCase() != getString(R.string.card_browser_all_decks).toLowerCase() }, { it.fullDeckName.toLowerCase() }))
-
             notifyDataSetChanged()
         }
 
@@ -373,13 +363,6 @@
                 currentlyDisplayedDecks.apply {
                     clear()
                     addAll(results)
-                    sortWith(
-                        compareBy({ it.fullDeckName != getString(R.string.card_browser_all_decks) }, {
-                            it.fullDeckName.lowercase(
-                                Locale.getDefault()
-                            )
-                        })
-                    )
                 }
                 notifyDataSetChanged()
             }
@@ -390,7 +373,6 @@
                 decksRoot = withCol { Pair(sched.deckDueTree(), this.isEmpty) }.first
 
                 val allDecksSet = deckNames.filter { it.deckId != 0L }.mapNotNull { decksRoot.find(it.deckId) }.toSet()
-                allDecksList.addAll(allDecksSet)
                 if (deckNames.any { it.deckId == 0L }) {
                     val newDeckNode = DeckTreeNode.newBuilder()
                         .setDeckId(0L)
@@ -398,6 +380,7 @@
                         .build()
                     allDecksList.add(DeckNode(newDeckNode, getString(R.string.card_browser_all_decks), null))
                 }
+                allDecksList.addAll(allDecksSet)
                 updateCurrentlyDisplayedDecks()
             }
         }
@@ -408,7 +391,7 @@
      * @param name Name of the deck, or localization of "all decks"
      */
     @Parcelize
-    class SelectableDeck(val deckId: DeckId, val name: String) : Comparable<SelectableDeck>, Parcelable {
+    class SelectableDeck(val deckId: DeckId, val name: String) : Parcelable {
         /**
          * The name to be displayed to the user. Contains only
          * the sub-deck name rather than the entire deck name.
@@ -422,21 +405,6 @@
         }
         constructor(d: DeckNameId) : this(d.id, d.name)
 
-        /** "All decks" comes first. Then usual deck name order.  */
-        override fun compareTo(other: SelectableDeck): Int {
-            if (deckId == ALL_DECKS_ID) {
-                return if (other.deckId == ALL_DECKS_ID) {
-                    0
-                } else {
-                    -1
-                }
-            }
-            return if (other.deckId == ALL_DECKS_ID) {
-                1
-            } else {
-                DeckNameComparator.INSTANCE.compare(name, other.name)
-            }
-        }
 
         companion object {
             /**
Index: AnkiDroid/src/main/java/com/ichi2/utils/DeckComparator.kt
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/utils/DeckComparator.kt b/AnkiDroid/src/main/java/com/ichi2/utils/DeckComparator.kt
deleted file mode 100644
--- a/AnkiDroid/src/main/java/com/ichi2/utils/DeckComparator.kt	(revision aa51fd1a6be6f5d833a62a19dd5c9fd76112e39d)
+++ /dev/null	(revision aa51fd1a6be6f5d833a62a19dd5c9fd76112e39d)
@@ -1,28 +0,0 @@
-/****************************************************************************************
- * Copyright (c) 2020 Arthur Milchior <arthur@milchior.fr>                              *
- *                                                                                      *
- * This program is free software; you can redistribute it and/or modify it under        *
- * the terms of the GNU General Public License as published by the Free Software        *
- * Foundation; either version 3 of the License, or (at your option) any later           *
- * version.                                                                             *
- *                                                                                      *
- * This program is distributed in the hope that it will be useful, but WITHOUT ANY      *
- * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A      *
- * PARTICULAR PURPOSE. See the GNU General Public License for more details.             *
- *                                                                                      *
- * You should have received a copy of the GNU General Public License along with         *
- * this program.  If not, see <http://www.gnu.org/licenses/>.                           *
- ****************************************************************************************/
-package com.ichi2.utils
-
-import org.json.JSONObject
-
-class DeckComparator : Comparator<JSONObject> {
-    override fun compare(lhs: JSONObject, rhs: JSONObject): Int {
-        return DeckNameComparator.INSTANCE.compare(lhs.getString("name"), rhs.getString("name"))
-    }
-
-    companion object {
-        val INSTANCE = DeckComparator()
-    }
-}
Index: AnkiDroid/src/main/java/com/ichi2/utils/DeckNameComparator.kt
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/utils/DeckNameComparator.kt b/AnkiDroid/src/main/java/com/ichi2/utils/DeckNameComparator.kt
deleted file mode 100644
--- a/AnkiDroid/src/main/java/com/ichi2/utils/DeckNameComparator.kt	(revision aa51fd1a6be6f5d833a62a19dd5c9fd76112e39d)
+++ /dev/null	(revision aa51fd1a6be6f5d833a62a19dd5c9fd76112e39d)
@@ -1,38 +0,0 @@
-/****************************************************************************************
- * Copyright (c) 2020 Arthur Milchior <arthur@milchior.fr>                              *
- *                                                                                      *
- * This program is free software; you can redistribute it and/or modify it under        *
- * the terms of the GNU General Public License as published by the Free Software        *
- * Foundation; either version 3 of the License, or (at your option) any later           *
- * version.                                                                             *
- *                                                                                      *
- * This program is distributed in the hope that it will be useful, but WITHOUT ANY      *
- * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A      *
- * PARTICULAR PURPOSE. See the GNU General Public License for more details.             *
- *                                                                                      *
- * You  [...]

2024-04-21 12:31 UTC, josephShokry commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            currentlyDisplayedDecks.sortWith(
I was not sure that I was allowed to refactor just was aming to add all the necessities for the feature without removing anything in order not to produce any bugs.
the code before the feature there was sorting so I applied sorting even if it is not necessary for me as it may be necessary for anything else that I don't know so the developer before me added it.

2024-04-21 14:48 UTC, david-allison approved these changes
Looks great, thanks!

2024-04-21 14:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +                results.forEach { it.collapsed = false }
questionable, as state doesn't seem to be reset

2024-04-22 07:23 UTC, josephShokry commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +                results.forEach { it.collapsed = false }
this is correct, the main behavior for the user is to click on search which will overwrite all the states, and then choose one deck and close, but if the user clicks on search and does not choose any deck instead gets back which is a valid behavior the all the decks will keep the overwritten state which is all the decks would be expanded.

2024-04-26 18:28 UTC, BrayanDSO approved these changes

2024-04-26 22:03 UTC, merged