[Cleanup]: Fix Android Studio Warnings #13282
ankidroid/Anki-Android pull request #15982
Opened 2024-03-23 18:40 UTC by isbvah

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
* Fixes #13282  [Cleanup]: Fix Android Studio Warnings 

## Approach
fixed by basic conventions first I scanned the warnings and then fixed some of the warnings under kotlin hood

2024-03-23 19:15 UTC, neeldoshii requested changes

2024-03-23 19:15 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +    @Deprecated("This function is deprecated due to ...", ReplaceWith("..."))
Not sure what this statement means `deprecated due to ..."` instead you can use `@Deprecated("Deprecated in Java")`

2024-03-23 19:16 UTC, neeldoshii commented
Thank you for contributing. LGTM, left one minor review.

2024-03-23 20:10 UTC, isbvah commented
Done Minor Fix

2024-03-24 01:29 UTC, david-allison commented
@isbvah, your git commit email means that the commits here are attributed to https://github.com/ishqDehlvi

Is this your intention?

2024-03-24 01:34 UTC, david-allison requested changes
Looks great! A couple of nitpicks, then let's get this in

2024-03-24 01:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    private fun Boolean.removeNotesView(cardsIds: List<Long>) {
Revert changes to this method, we want to keep it for now

2024-03-24 01:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
> +            this.cacheValues()
revert this file and just remove the `KotlinCleanup`

2024-03-24 11:00 UTC, david-allison approved these changes

2024-03-24 11:01 UTC, merged