Main key utils testing
ankidroid/Anki-Android pull request #15998
Opened 2024-03-26 00:02 UTC by AbdelrahmanEsam

add test cases for KeyUtils

2024-03-26 00:49 UTC, david-allison requested changes
Lint is failing

2024-03-26 09:53 UTC, BrayanDSO commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/utils/KeyUtilsTest.kt
> + *  Copyright (c) 2024 Brayan Oliveira <brayandso.dev@gmail.com>
I didnt make this file. Put your name and email here, or if you don't want to, remove this line

2024-03-28 12:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +        ChangeManager.subscribe(this)
?

2024-03-28 17:45 UTC, david-allison requested changes
Given testing, (and we're now in Kotlin), I'd make `isDigit` private and have `getDigit` return null if it's not a digit

Then, we're not returning invalid data

2024-03-28 17:45 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/utils/KeyUtilsTest.kt
> +        assertEquals(49, KeyUtils.getDigit(keyEvent))
This doesn't look expected

2024-03-28 17:45 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/utils/KeyUtilsTest.kt
> +        assertEquals(-48, KeyUtils.getDigit(keyEvent))
Ditto - we probably want to return `null`

2024-03-28 22:26 UTC, AbdelrahmanEsam commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/utils/KeyUtilsTest.kt
> +        assertEquals(-48, KeyUtils.getDigit(keyEvent))
explain more please

2024-03-28 22:26 UTC, AbdelrahmanEsam commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/utils/KeyUtilsTest.kt
> +        assertEquals(49, KeyUtils.getDigit(keyEvent))
explain more please

2024-03-29 00:59 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/utils/KeyUtilsTest.kt
> +        assertEquals(-48, KeyUtils.getDigit(keyEvent))
We've identified an issue in the code due to testing. 

This is partially as Java has much worse `null` handling than Kotlin

We should modify `KeyUtils.getDigit(keyEvent)` to return an `Int?`, and `null` when the values are out of range.

Make `isDigit()` private and have `getDigit` return `null` if `isDigit` returns `false`.

Then handle this in the caller

2024-04-02 20:37 UTC, david-allison requested changes
See comment thread: `getDigit`: This testing has found an issue, `getDigit()` should be modified to return an int

Reviewing to remove a notification

2024-04-03 03:43 UTC, david-allison commented
Let's give @AbdelrahmanEsam time to respond, it's a stressful time of year

If you don't hear anything within 48 hours, feel free to take this PR to completion

2024-04-03 10:50 UTC, AbdelrahmanEsam commented
I sorry I was really stressed  .... I will  continue working on this pr today or tomorrow .

2024-04-06 00:23 UTC, AbdelrahmanEsam commented
I am already did it and will upload my work today or tomoorrow

2024-04-06 19:04 UTC, david-allison requested changes
Could you revert the non-relevant changes in `Files Changed`, this is difficult to review currently

2024-04-06 19:04 UTC, david-allison commented on AnkiDroid/build.gradle
> +
Why isn't this in `lint-release.xml`?

What's it doing?

2024-04-06 23:12 UTC, AbdelrahmanEsam commented on AnkiDroid/build.gradle
> +
it's in lint-release.xml now .... it will give you compiler error when you are trying to access anything anotated with @VisibleForTests and not in testing sourceSet

2024-04-06 23:21 UTC, david-allison commented on AnkiDroid/build.gradle
> +
This would be better in a separate pull request

2024-04-08 12:06 UTC, david-allison requested changes
One revert requested, one nitpick

Looks much better, thanks!

2024-04-08 12:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            if (getTextFromSearchView != null && getTextFromSearchView.isNotEmpty()) {
This looks accidental

2024-04-08 12:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            digit?.let {
more concise: 
```kotlin
KeyUtils.getDigit(event)?.let { digit ->
```

2024-04-10 10:24 UTC, lukstbit approved these changes
Thanks!

2024-04-11 11:08 UTC, merged