Let users specify a custom root certificate
ankidroid/Anki-Android pull request #15996
Opened 2024-03-25 21:36 UTC by voczi

## Purpose / Description
Since the new backend is forced on the newer Ankidroid releases, Android users cannot connect to their self-hosted sync server if it uses a self-signed certificate. The problem should be fixed with this PR. More than willing to accept any changes made to the UI part of this feature, it ain't that pretty.
Requires https://github.com/ankidroid/Anki-Android-Backend/pull/357. 

## Fixes
* Fixes #14686 

## Approach
Allow users to specify a custom root certificate to trust (in PEM format) and feed this through the backend.

## How Has This Been Tested?
Took the PEM-formatted root certificate I use for my local servers, and then copied the contents of it into the text field in the custom sync server section. After doing this, I don't get a error message telling me that the sync server certificate has an unknown issuer.

## Learning
[PEM, DER, CRT, and CER: X.509 Encodings and Conversions](https://www.ssl.com/guide/pem-der-crt-and-cer-x-509-encodings-and-conversions/)

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

![Screenshot_20240325_223253](https://github.com/ankidroid/Anki-Android/assets/82241877/b9945e78-ac29-48dc-82c3-9c0d872fcf09)
(sorry for the flashbang)

2024-03-25 22:31 UTC, david-allison requested changes
Looks great! 

The main change required is to remove all but the translation in `/values`

Feel free to ignore the rest + mark as resolved. Logging is the only thing I'd mildly push for

2024-03-25 22:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +    checkCurrentCert(this.sharedPrefs())
It would be nice to find a centralised place for this, I don't think we do any more.  Looks good!

2024-03-25 22:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +    const val CUSTOM_CERTIFICATE_ENABLED: String = CUSTOM_CERTIFICATE + VersatileTextWithASwitchPreference.SWITCH_SUFFIX
non-blocking: Could this be simplified to a single preference (null: disabled)

2024-03-25 22:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +    val currentCert: String? = BackendFactory.getCustomCert()
Non-blocking: I don't have a sense for the valid values which this can be from this code.

It would be a nice to have to define an [inline value class](https://kotlinlang.org/docs/inline-classes.html#representation) with a little documentation as a doc-comment.

Barring that, a comment with a sample value will do

2024-03-25 22:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +        runBlocking { CollectionManager.discardBackend() }
move the call into `launchCatchingTask` and make this a `suspend fun`

2024-03-25 22:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +        runBlocking { CollectionManager.discardBackend() }
Non-blocking: I suspect we can extend this functionality to remove the requirement to call `discardBackend`

It may want to be documented that `discardBackend` is required on the `setCustomCert` doc-comment

2024-03-25 22:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +        BackendFactory.setCustomCert(customCert)
Could you add a `Timber.i` informing us that a custom cert is being used

Don't log the value, as this could potentially contain PII

2024-03-25 22:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +    val currentCert: String? = BackendFactory.getCustomCert()
Is this call potentially slow? 

If so, if `CUSTOM_CERTIFICATE_ENABLED` is unset, we could add logic to avoid checking the backend

2024-03-25 22:36 UTC, david-allison commented
This is an advanced feature, implementer's choice if we should add basic PEM validation [if there's anything in the Java stdlib OR a quick check via string comparison]

2024-03-25 22:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +        BackendFactory.setCustomCert(customCert)
What happens if a bad value is provided? 

I mostly want to ensure we avoid a crash, this may want to be extended to inform the user via a log (possibly in the backend)

2024-03-26 06:24 UTC, voczi commented on AnkiDroid/src/main/res/values-bn/10-preferences.xml
> +    <string name="custom_certificate_title" maxLength="41">Custom root certificate (PEM)</string>
Yep, will do! Wasn't sure how any of this worked.

2024-03-26 06:27 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +        BackendFactory.setCustomCert(customCert)
Nothing at all, actually. The certificate is validated in the Rust backend.
The one thing I thought about is validating it on this side regardless, purely for people to know that their certificate isn't in the right format? Just an idea, not sure if it's really needed.

2024-03-26 06:32 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +        BackendFactory.setCustomCert(customCert)
Already done here https://github.com/ankidroid/Anki-Android-Backend/pull/357/commits/c5d5c75ea285519e634b229b547ccacde5d83990
Although it's logged as a debug message instead of as information.

2024-03-26 06:34 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +        BackendFactory.setCustomCert(customCert)
Ah, saw you made a comment about this directly above.
Yeah, I'm unsure if any validation is really that necessary.. It's an advanced feature, as you said.

2024-03-26 15:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +        BackendFactory.setCustomCert(customCert)
I'm fine to resolve this as long as it's a no-op

2024-04-20 13:41 UTC, david-allison commented
@voczi as far as I understand it, this is waiting on draft PRs on the backend repo.

Is it likely you'll have time to get these ship-shape?

2024-04-21 14:03 UTC, voczi commented
@david-allison yeah i think i abandoned the PR on the backend repo some time ago lol. feeling i got was that there wasnt any need (from the backend maintainers' perspective) to have this problem resolved asap.

ive got a fixed version released on my fork (the code itself isnt up to date though). in any case, ill just close this PR for now.

2024-04-21 14:03 UTC, closed without merging

2024-04-21 14:40 UTC, david-allison commented
@voczi Would be nice to get it in rather than see the work go to waste. Your call