Fix: Display Correct Filtered Deck Name In Edit Note
ankidroid/Anki-Android pull request #16002
Opened 2024-03-26 21:52 UTC by advait-bhitkar

## Purpose / Description
To show the correct deck name on the Edit Note screen, when reviewing filtered deck. 

## Fixes
* Fixes #15919 

## Approach
The deck field always showed as the first deck among all decks, rather than displaying the actual deck of the note. This occurred because the dropDownDecks list did not contain the filteredDecks, thus it couldn't find the deck with that ID.

To fix this, I set showFilteredDecks to true, and in the initializeNoteEditorDeckSpinner function, I made includeFiltered equal to showFilteredDecks.

## How Has This Been Tested?
Tested on Android device

## Screenshots

<details>
  <summary>Deck List</summary>

![Screenshot_20240327-030600](https://github.com/ankidroid/Anki-Android/assets/25331865/8b04cc61-3712-448b-b8ef-9f9182dc2524)
</details>

<details>
  <summary>Before</summary>

![Screenshot_20240327-030838](https://github.com/ankidroid/Anki-Android/assets/25331865/20a4ce51-32c9-4571-b5ec-4d73a0a02c65)</details>

<details>
  <summary>After fix - </summary>

![Screenshot_20240327-030613](https://github.com/ankidroid/Anki-Android/assets/25331865/27f5b7cc-20b8-4d74-8539-762caa5cb639)
</details>

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-03-27 13:18 UTC, advait-bhitkar commented
https://github.com/ankidroid/Anki-Android/assets/25331865/eaa3e565-acfd-44e6-94b8-24487e810a46

Before it would show only the first deck name, now it is showing the correct filtered deck name.

2024-03-28 12:59 UTC, david-allison commented
We should be using something along the lines of `getDeckIdForCard` (using `oDid` if it exists). This will display the 'home deck' of the card.

Not displaying the filtered deck

2024-03-28 17:50 UTC, advait-bhitkar commented
Should we return `CardUtils.getDeckIdForCard(currentEditedCard!!)` instead of `currentEditedCard!!.did` in `calculateDeckId()`? 

This ensures that the card's original deck ID is used when displaying the deck name with `deckSpinnerSelection!!.selectDeckById(deckId, false)`, displaying the card's home deck.

2024-03-28 19:45 UTC, david-allison commented
Try it, test it, and see if it works.

Add a unit test if you're unusre

2024-03-29 13:09 UTC, advait-bhitkar commented
Used `CardUtils.getDeckIdForCard(currentEditedCard!!)` to retrieve the original deck ID of the card, which is then utilized to display the 'home deck' name in Note Editor.

Tried and tested, working correctly.

2024-03-29 13:42 UTC, advait-bhitkar commented
Previously, when editing a note and saving it without making any changes, the card remained in the filtered deck. However, now it is being removed.
Will try to fix it.

2024-04-16 01:05 UTC, david-allison requested changes
Sorry for the delay - had a HUGE backlog and almost through with it

2024-04-16 01:05 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                return CardUtils.getDeckIdForCard(currentEditedCard!!)
This should be a purely visual change (changing the displayed deck name to include both `did` and `odid`), changing the underlying IDs will result in problems

A valid output would be `Filtered Deck (Default)`

2024-05-07 01:53 UTC, closed without merging