refactor: trim CollectionHelper a bit
ankidroid/Anki-Android pull request #16014
Opened 2024-03-28 16:46 UTC by BrayanDSO

## Approach

In the commits

## How Has This Been Tested?

CI + With a corrupt collection by renaming any file to `collection.anki2` in an Android 34 emulator: 

[Screen_recording_20240328_134350.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/4900cd2b-feb6-407b-a98f-dd514a3dc319)

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-03-28 16:54 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
> +    ) {
Unintended changes because of #15143. Only saw this after I left my PC

2024-04-05 02:49 UTC, david-allison requested changes
This is good, only minor issues in the first commit

There's one (minor) request regarding a spacing change, code looks good

But it uncovers existing bugs which could do with a TODO

2024-04-05 02:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +                        FlashCardsContract.ReviewInfo.TIME_TAKEN ->
?

2024-04-05 02:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +        val col = CollectionManager.getColUnsafe()
This uncovers a bug: we've changed the API contract if `getCol` fails

Could you add a TODO for a `getColUnsafe` which throws `IllegalStateException` on failure?

2024-04-05 02:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
> +        this.col = CollectionManager.getColUnsafe()
technically uncovers a bug, but I'm fine with this

2024-04-05 13:33 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +                        FlashCardsContract.ReviewInfo.TIME_TAKEN ->
#15143. It will keep happening since it's easy to miss a space change among 50 others after inlining something

2024-04-05 13:44 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +        val col = CollectionManager.getColUnsafe()
this happens in more than one place there, so I think that an issue would be better

2024-04-05 13:48 UTC, david-allison approved these changes

2024-04-07 09:24 UTC, lukstbit approved these changes
LGTM, with the two minor issues below.

2024-04-07 14:29 UTC, merged