Requesting Review: [Cleanup]: Fix Android Studio Warnings #13282
ankidroid/Anki-Android pull request #16040
Opened 2024-03-31 17:44 UTC by eliseevavika

## Purpose / Description
The purpose of this pull request is to address task #13282, titled '[Cleanup]: Fix Android Studio Warnings,' which is designed to assist in onboarding new users to the codebase by resolving various warnings and errors in the code. 
Upon inspecting the codebase, I identified several errors, warnings, and weak warnings.
To familiarize myself with the codebase and practice my skills, I have fixed a subset of these issues. This effort aims to improve the overall code quality and maintainability of the project

## Fixes
* Fixed some the errors, warnings + weak warnings in the file after code Inspection (Code -> Inspect Code)

## How Has This Been Tested?

I have tested the changes by running the application on my device. The project launched successfully without any errors or issues, confirming the functionality of the implemented features

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-03-31 17:52 UTC, david-allison requested changes
Thanks! Small amount of feedback

Please revert all changes to `AddContentApi` so we can get this merged as soon as possible

2024-03-31 17:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        val builder = Builder(customTabActivityHelper.session)
Better as it was previously

If it's not possible to resolve this another way, could you alias `CustomTabsIntent.Builder` to `CustomTabsIntentBuilder`

2024-03-31 17:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
> +        toRelrn += kotlin.math.ceil((1 - revRate) * counts.rev).toInt()
is `ceil` usable?

2024-03-31 17:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
> +        relrnRate = kotlin.math.max(relrnRate, 0.05)
ditto: shouldn't need the `kotlin.math` qualifier

2024-03-31 17:52 UTC, david-allison commented on annotations/README.md
> +          </root>
This doesn't seem to add value to the example

2024-03-31 17:52 UTC, david-allison commented on api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
> +            val ordColumnIndex = cardsCursor.getColumnIndex(Card.CARD_ORD)
I didn't see an IDE warning for this one

2024-03-31 17:52 UTC, david-allison commented on api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
> +                val nameColumnIndex = cardsCursor.getColumnIndex(Card.CARD_NAME)
ditto, which warnings are fixed

2024-03-31 17:53 UTC, david-allison commented
```
* What went wrong:
Execution failed for task ':AnkiDroid:ktlintMainSourceSetCheck'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.ConsoleReportWorkAction
   > KtLint found code style violations. Please see the following reports:
     - /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/build/reports/ktlint/ktlintMainSourceSetCheck/ktlintMainSourceSetCheck.txt
```

2024-03-31 18:14 UTC, eliseevavika commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
> +        toRelrn += kotlin.math.ceil((1 - revRate) * counts.rev).toInt()
In Java, we use Math.ceil(), while in Kotlin, we use kotlin.math.ceil(), which is to round up the result to the nearest integer. Both functions perform the same operation, rounding up to the nearest integer.

2024-03-31 18:18 UTC, eliseevavika commented on annotations/README.md
> +          </root>
there was a warning or error at the end of the file. Should I undo these changes?

2024-03-31 18:20 UTC, Aditya13s commented
> Task :AnkiDroid:ktlintMainSourceSetCheck FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt:30:1 Unused import

@eliseevavika There is an unused import in AnkiActivity.kt in line 30. Remove it

2024-03-31 18:27 UTC, eliseevavika commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        val builder = Builder(customTabActivityHelper.session)
reverted changes to AddContentApi

2024-03-31 18:29 UTC, eliseevavika commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
> +        relrnRate = kotlin.math.max(relrnRate, 0.05)
made changes: used import statement for max function in Scheduler.kt and removed kotlin.math

2024-03-31 18:40 UTC, eliseevavika commented
> > Task :AnkiDroid:ktlintMainSourceSetCheck FAILED
> > /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt:30:1 Unused import
> 
> @eliseevavika There is an unused import in AnkiActivity.kt in line 30. Remove it

by a comment above I reverted the change for CustomTabsIntent, so now I need this import:
import androidx.browser.customtabs.CustomTabsIntent

2024-03-31 18:54 UTC, david-allison commented on annotations/README.md
> +          </root>
Yep - the closing tags don't seem to provide value for readers

2024-03-31 19:18 UTC, eliseevavika commented on api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
> +            val ordColumnIndex = cardsCursor.getColumnIndex(Card.CARD_ORD)
I do the next steps:
Code - > Inspect Code (Whole project)
Under the folder -Android Lint: Correctness:
there are 12 warnings in the file AddContentApi.kt:
"value must be >=0 but ‘getColumnIndex’ can be -1

<img width="516" alt="Screen Shot 2024-03-31 at 3 15 25 PM" src="https://github.com/ankidroid/Anki-Android/assets/22506240/ed00e82b-9768-4c7c-9ef2-19488dfa2bd0">
"

2024-03-31 19:33 UTC, eliseevavika commented on annotations/README.md
> +          </root>
undo my changes

2024-03-31 19:59 UTC, eliseevavika commented
> ```
> * What went wrong:
> Execution failed for task ':AnkiDroid:ktlintMainSourceSetCheck'.
> > A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.ConsoleReportWorkAction
>    > KtLint found code style violations. Please see the following reports:
>      - /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/build/reports/ktlint/ktlintMainSourceSetCheck/ktlintMainSourceSetCheck.txt
> ```

I see that all (7) checks have passed. How can I see this error?

2024-03-31 21:57 UTC, david-allison requested changes
One request for a revert on `AddContentApi`

Optional nitpick with `kotlin.math.ceil`

Then good to merge, thanks!

2024-03-31 21:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
> +        toRelrn += kotlin.math.ceil((1 - revRate) * counts.rev).toInt()
Yes, but the namespace shouldn't be necessary: `ceil` vs `kotlin.math.ceil`

2024-03-31 21:57 UTC, david-allison commented on api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
> +            val ordColumnIndex = cardsCursor.getColumnIndex(Card.CARD_ORD)
Revert the file for now, we can do better when cleaning this up

2024-04-01 00:06 UTC, david-allison approved these changes
Looks great, thanks!

2024-04-01 05:06 UTC, lukstbit approved these changes
LGTM, thank you for contributing!

2024-04-01 19:43 UTC, merged

2024-04-01 19:43 UTC, mikehardy commented
great! merge queue was drained, so squashed this in