feat: sync improvements
ankidroid/Anki-Android pull request #16056
Opened 2024-04-01 20:27 UTC by BrayanDSO

## Purpose / Description

Trying to make sync less sufferable.

#15624 is next

## Approach

In the commits

## How Has This Been Tested?

Emulator 34.

1. Try syncing with no changed media and fetch media enabled, and likely the notification won't appear
2. Enable autosync and open the app after 10 minutes with no changes to sync → you shouldn't blocked by the sync dialog

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-04-01 20:29 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt
> +        fun getWorkRequest(auth: SyncAuth): OneTimeWorkRequest {
I extracted this because I'll use it in another PR

2024-04-01 20:29 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                SyncStatusResponse.Required.UNRECOGNIZED,
tbh, not sure what unrecognized does

2024-04-13 18:28 UTC, david-allison requested changes
One question about a `!!`, looks great (and sorry for taking so long with the review)

Optional: It would be useful, but not required to go through a sync and print the `Timber`s generated, to be sure we're not missing anything

And a quick think through the `Timber.i` calls to ensure we're at a good level of granularity for ACRA

2024-04-13 18:52 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            }.required
What is your concern here?

2024-04-13 18:59 UTC, BrayanDSO commented
> And a quick think through the Timber.i calls to ensure we're at a good level of granularity for ACRA

I don't care much. Whatever someone wants is good to me.

2024-04-13 20:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            }.required
Just style, ignore it

2024-04-13 20:15 UTC, david-allison approved these changes
Thanks! Looks great

2024-04-15 16:17 UTC, lukstbit approved these changes
LGTM

2024-04-15 16:32 UTC, merged