feat: autosync collection in the background when leaving the app
ankidroid/Anki-Android pull request #16060
Opened 2024-04-01 23:00 UTC by BrayanDSO

## Purpose / Description

Autosync is quite annoying since forever. 

You open the app, with nothing to sync, but you have to wait a dialog the same way

You want to leave the app and do something else, but you have to wait a dialog while everything could be done in the background.

This PR tries to bring decency into that.

## Fixes
* Fixes #15624

## Approach
In the commits (please read their descriptions)

On top of #16056. Only the last two are new

## How Has This Been Tested?

I've been using this in my personal build in the last week, and work wonders. Quite a QOL improvement to me. 

Do I fully trust it? No, since some kind of bad internet, bad phone, huge collection may cause a problem. But maybe it won't. I need people using it to assess it.

Emulator 34:

[alice.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/b1143bbf-979b-4b1a-aa05-c452adfed593)

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-04-16 17:50 UTC, david-allison commented
* dependency merged: https://github.com/ankidroid/Anki-Android/pull/16056

2024-04-16 20:07 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
> +        }
Not sure if this would still hang in slower phones. In my S23 there is a <1s hang in the app launcher.

I think that the scenario of leaving the app and reopening it before sync was finished is rare (at least for me, sync normally takes less than 5s), but will happen given the number of users we have

2024-04-16 20:08 UTC, BrayanDSO commented
As a note, I've been using this personally for the last weeks and LOVE the quality of life that this provides. B

ut I don't trust 100% that this will flow without any issues to fix, so be aware of that before deciding if this is going to be in 2.18 or 2.19

2024-04-16 21:45 UTC, david-allison requested changes
Looks great!

One issue with `cancelSync`, the rest are optional nitpicks

2024-04-16 21:45 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
> +        if (launchType != LaunchType.COPY_DEBUG_INFO) {
nit: extract to a method defining the functional need: `requiresCollectionAccess(launchType)`

2024-04-17 06:25 UTC, david-allison commented
Why isn't the animated media progress icon appearing in the Deck Picker in the video?

2024-04-17 11:20 UTC, BrayanDSO commented
> Why isn't the animated media progress icon appearing in the Deck Picker in the video?

I made this PR before the other one

2024-04-17 14:09 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncWorker.kt
> +            cancelSync(CollectionManager.getBackend())
The Worker exits and that's it

2024-04-17 14:20 UTC, david-allison approved these changes

2024-04-17 17:01 UTC, lukstbit approved these changes
LGTM

2024-04-17 17:16 UTC, merged