[Cleanup] Fix Android Studio java warnings in anki/servicelayer #13282
ankidroid/Anki-Android pull request #16074
Opened 2024-04-02 18:53 UTC by henriqueccmac

## Purpose / Description
Get to know the project. Fixed some android studio warnings and weak warnings as per #13282.

## Fixes
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFiles.kt: fixed typos in references to functions and constants.
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectory.kt: fixed import paths and made a function private.
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileOrDirectory.kt: removed unused import.
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/migrateuserdata/MigrateUserData.kt: made relevant functions private.

## Checklist
_Please, go through these checks before submitting the PR._

- [X ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-04-02 18:57 UTC, david-allison approved these changes
Cheers!

2024-04-02 18:57 UTC, david-allison requested changes
Tests are failing

```
> Task :AnkiDroid:compilePlayDebugUnitTestKotlin FAILED
e: file:///home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt:22:66 Unresolved reference: MoveDirectory
e: file:///home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileOrDirectoryTest.kt:19:66 Unresolved reference: MoveDirectory
```

2024-04-02 18:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectory.kt
> +package com.ichi2.anki.servicelayer.scopedstorage
issue is likely here - I suspect we want to keep the package and move the file

2024-04-02 22:48 UTC, henriqueccmac commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectory.kt
> +package com.ichi2.anki.servicelayer.scopedstorage
I agree. I moved the file and changed the imports accordingly.

2024-04-03 01:05 UTC, david-allison approved these changes
Squash merge and force push on your first change. Impressive!

Thanks so much, welcome to AnkiDroid :)

2024-04-03 01:19 UTC, merged