Match the color of status bar with Statistic toolbar
ankidroid/Anki-Android pull request #16088
Opened 2024-04-03 19:17 UTC by Aditya13s

## Purpose / Description
The purpose of this is to match the color of status bar with the statistics toolbar.

## Fixes
* Fixes #16034 

## Approach
I added a scroll listener which changes the color of the status bar according to the Material toolbar which changes it's color when user scrolls.

## How Has This Been Tested?
I tested the app by scrolling the screen.

## Screenshot
<img src="https://github.com/ankidroid/Anki-Android/assets/77337791/a2b7467d-317d-43f1-91bb-aadf05ad43ba.jpg" height="600">

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-04-03 19:25 UTC, neeldoshii approved these changes

2024-04-03 19:25 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
> +                activity?.window!!.statusBarColor = backgroundColor
```suggestion
                activity?.window?.statusBarColor = backgroundColor
```

Can we use ? instead of !!

2024-04-03 19:27 UTC, neeldoshii commented
Thank you for contributing. Looks good, left one minor change.

2024-04-03 21:02 UTC, BrayanDSO requested changes
The toolbar is not always the same color, as it changes when collapsed/uncollapsed (see the Settings activity for an example).

I believe that setting it programatically won't be the way. More likely some kind of configuration in the XML

2024-04-03 21:09 UTC, BrayanDSO approved these changes

2024-04-04 01:41 UTC, david-allison approved these changes

2024-04-04 01:42 UTC, merged

2024-04-04 01:42 UTC, david-allison commented
Cheers!