Fix #15356: Fixed bug causing system bars to reappear in full screen after navigatin menu
ankidroid/Anki-Android pull request #16087
Opened 2024-04-03 16:29 UTC by Bobalogic

## Purpose / Description
This commit addresses the issue where the system bars were reappearing even when the application was in full screen mode, specifically after navigating to the menu and returning to the deck.

## Fixes
* Fixes #15356

## Approach
The onResume() method in Reviewer.kt was modified to preserve the full screen state by adding a Jvm static variable. Additionally, modifications were made to the following XML files:
- reviewer_fullscreen.xml
- reviewer_fullscreen_noanswers.xml

## How Has This Been Tested?
Tested in my personal device connected to the android studio.

## Learning (optional, can help others)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-04-03 19:03 UTC, neeldoshii requested changes

2024-04-03 19:03 UTC, neeldoshii commented on AnkiDroid/src/main/res/layout/reviewer_fullscreen.xml
> +    android:focusableInTouchMode="true">
seems like uneeded formating?

2024-04-05 02:40 UTC, david-allison requested changes
Thanks! Please aim to only have the diff include relevant lines.

If you go to 'files changed', you can see additional changes have been made

It would be much easier to review if these hunks of non-functional changes in the diff are reverted

2024-04-05 11:52 UTC, mikehardy commented on AnkiDroid/src/main/res/layout/reviewer_fullscreen.xml
> +    android:focusableInTouchMode="true">
as near as I can tell, and I had to spend valuable review time carefully checking, there was no actual change here
So the formatting was a negative for me, this change shouldn't be here or should be in a separate formatting-only commit

2024-04-05 11:54 UTC, mikehardy commented on AnkiDroid/src/main/res/layout/reviewer_fullscreen_noanswers.xml
> +            android:visibility="gone"/>
As near as I can tell - and it is very difficult to tell - the *only* functional changes are the addition of the visibility attribute here and below

But it is critical to note: it is very very difficult for me to tell this. The lesson here is do not ever include formatting changes with functional changes - it makes reviewing files nearly impossible

Reformatting files is strongly discouraged in general - it very rarely serves any useful purpose and has negative effects on review

2024-04-05 11:56 UTC, mikehardy requested changes
I can't review it confidently with the formatting diff mixed in.
I think I see what the real changes are and they seem okay if I understand them correctly, but we can and should do better, so echoing David - can't approve with the diff as is.
Revert *all* non-functional changes and re-push please

2024-04-05 13:25 UTC, neeldoshii commented
@Bobalogic this is the following patch I have just reverted the uneeded diff from reviewer.kt , reviewer full screen. You still need to revert reviewer_fullscreen_no screen.

```diff
Subject: [PATCH] Reverts the unintended files of Reviewer & reviewer full screen
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt b/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt	(revision 73022cca32f2edea79823f174631442615e7846c)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt	(date 1712322566584)
@@ -197,6 +197,29 @@
         super.onPause()
     }
 
+    override fun onResume() {
+        if (prefFullscreenReview) {
+            val toolbarTemp = findViewById<Toolbar>(R.id.toolbar)
+            val answerButtonsTemp = findViewById<View>(R.id.answer_options_layout)
+            val topbarTemp = findViewById<View>(R.id.top_bar)
+
+            hideViewWithAnimation(toolbarTemp)
+            if (fullscreenMode == FullScreenMode.FULLSCREEN_ALL_GONE) {
+                hideViewWithAnimation(topbarTemp)
+                hideViewWithAnimation(answerButtonsTemp)
+            }
+        }
+
+        when {
+            stopTimerOnAnswer && isDisplayingAnswer -> {}
+            else -> launchCatchingTask { answerTimer.resume() }
+        }
+        super.onResume()
+        if (typeAnswer?.autoFocusEditText() == true) {
+            answerField?.focusWithKeyboard()
+        }
+    }
+
     override fun onDestroy() {
         super.onDestroy()
         server.stop()
@@ -1332,32 +1355,6 @@
         }
     }
 
-    override fun onResume() {
-        if (prefFullscreenReview) {
-            val toolbarTemp = findViewById<Toolbar>(R.id.toolbar)
-            val answerButtonsTemp = findViewById<View>(R.id.answer_options_layout)
-            val topbarTemp = findViewById<View>(R.id.top_bar)
-
-            hideViewWithAnimation(toolbarTemp)
-            if (fullscreenMode == FullScreenMode.FULLSCREEN_ALL_GONE) {
-                hideViewWithAnimation(topbarTemp)
-                hideViewWithAnimation(answerButtonsTemp)
-            }
-        }
-
-        when {
-            stopTimerOnAnswer && isDisplayingAnswer -> {}
-            else -> launchCatchingTask { answerTimer.resume() }
-        }
-        super.onResume()
-        if (typeAnswer?.autoFocusEditText() == true) {
-            answerField?.focusWithKeyboard()
-        }
-
-        Timber.d("System UI visibility change.  on resume called")
-        Timber.d("System UI visibility change.  pref full screen : $prefFullscreenReview")
-    }
-
     @Suppress("deprecation") // #9332: UI Visibility -> Insets
     private fun setFullScreen(a: AbstractFlashcardViewer) {
         // Set appropriate flags to enable Sticky Immersive mode.
Index: AnkiDroid/src/main/res/layout/reviewer_fullscreen.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/res/layout/reviewer_fullscreen.xml b/AnkiDroid/src/main/res/layout/reviewer_fullscreen.xml
--- a/AnkiDroid/src/main/res/layout/reviewer_fullscreen.xml	(revision 73022cca32f2edea79823f174631442615e7846c)
+++ b/AnkiDroid/src/main/res/layout/reviewer_fullscreen.xml	(date 1712322266690)
@@ -1,16 +1,14 @@
-<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
-    android:id="@+id/root_layout"
-    android:layout_width="match_parent"
-    android:layout_height="match_parent"
-    android:focusableInTouchMode="true">
+<androidx.coordinatorlayout.widget.CoordinatorLayout android:id="@+id/root_layout"
+android:layout_width="match_parent"
+android:layout_height="match_parent"
+android:focusableInTouchMode="true"
+xmlns:android="http://schemas.android.com/apk/res/android">
     <!-- Main content that takes up the fullscreen -->
     <RelativeLayout
         android:id="@+id/fullscreen_frame"
         android:layout_width="match_parent"
         android:layout_height="match_parent">
-
-        <include
-            layout="@layout/reviewer_topbar"
+        <include layout="@layout/reviewer_topbar"
             android:layout_width="match_parent"
             android:layout_height="wrap_content"
             android:layout_alignParentTop="true"/>
@@ -18,32 +16,25 @@
             layout="@layout/reviewer_mic_tool_bar"
             android:layout_width="match_parent"
             android:layout_height="wrap_content"
-            android:layout_below="@id/top_bar"/>
-
-        <include
-            layout="@layout/reviewer_flashcard_fullscreen"
+            android:layout_below="@id/top_bar" />
+        <include layout="@layout/reviewer_flashcard_fullscreen"
             android:layout_width="match_parent"
             android:layout_height="match_parent"
             android:layout_below="@id/mic_tool_bar_layer"/>
-
         <include
             layout="@layout/reviewer_whiteboard_editor"
             android:layout_width="wrap_content"
             android:layout_height="wrap_content"
-            android:layout_above="@+id/bottom_area_layout"
-            android:layout_centerHorizontal="true"/>
-
-        <include
-            layout="@layout/reviewer_answer_buttons"/>
+            android:layout_centerHorizontal="true"
+            android:layout_above="@+id/bottom_area_layout"/>
+        <include layout="@layout/reviewer_answer_buttons"/>
     </RelativeLayout>
     <!-- Controls that are overlaid over the main content when the user interrupts immersive mode -->
     <FrameLayout
         android:layout_width="match_parent"
         android:layout_height="match_parent"
         android:fitsSystemWindows="true">
-
-        <include
-            layout="@layout/toolbar"
+        <include layout="@layout/toolbar"
             android:layout_width="match_parent"
             android:layout_height="wrap_content"
             android:gravity="top"/>
             
```

2024-04-05 13:28 UTC, neeldoshii commented
Thanks!!! I admit, I haven't understood main issue. As in main branch I am still able to see app bar and answer for few seconds. Is this fix for this? 

https://github.com/ankidroid/Anki-Android/assets/60827173/52b55a4d-38fa-4429-8f23-eef7749acc91

2024-04-26 13:36 UTC, closed without merging