Add: Remove button for deck picker background image
ankidroid/Anki-Android pull request #16091
Opened 2024-04-04 06:30 UTC by oyeraghib

## Purpose / Description
Add: Remove button for deck picker background image

## Fixes
* Fixes #16090 

## Approach
Created a custom preference for adding the option to remove the image along with selecting the image.

### Before

https://github.com/ankidroid/Anki-Android/assets/40427461/ec776769-51ce-4efd-b652-e10414f766fb

### After

https://github.com/ankidroid/Anki-Android/assets/40427461/1137b97e-c08d-4bc0-9e96-8234aa499f8d

## How Has This Been Tested?

Tested on:
Physical device - Pixel 6A (Android 13)
Emulator - Pixel 3a (Android 14)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-04-04 18:06 UTC, oyeraghib commented
@SanjaySargam I think the problem with this approach would be replacing the image. If there is already a bg image and user decides to change to new image, first they have to remove the prior image and then they would get the option to "Select image", which I think is an extra unnecessary step from user's pov.

2024-04-05 02:40 UTC, SanjaySargam commented on AnkiDroid/src/main/res/xml/preferences_appearance.xml
> +        app:allowDividerBelow="false">
Why did you set this to false? Is there any specific reason?

2024-04-06 00:37 UTC, oyeraghib commented on AnkiDroid/src/main/res/xml/preferences_appearance.xml
> +        app:allowDividerBelow="false">
After adding a custom layout for preferences, there was a divider below the title, and setting this to `false` removes that divider. So there is only one divider after that preference category.

2024-04-10 06:16 UTC, krmanik requested changes

2024-04-10 06:16 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/PreferenceSelectBackgroundImage.kt
> +class PreferenceSelectBackgroundImage @JvmOverloads constructor(
It looks good to me. Can you move this to `SettingsFragment`?

2024-04-13 16:19 UTC, oyeraghib commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/PreferenceSelectBackgroundImage.kt
> +class PreferenceSelectBackgroundImage @JvmOverloads constructor(
@krmanik I tried moving this to `SettingsFragment` and encountered some issues.
So basically I had to update the reference in xml as follows :

```
<PreferenceCategory android:title="@string/background_image_title"
        app:allowDividerBelow="false">
            <view class="com.ichi2.anki.preferences.SettingsFragment$PreferenceSelectBackgroundImage"
                android:defaultValue="0"
                android:key="@string/pref_deck_picker_background_key"
                android:shouldDisableView="true"/>
    </PreferenceCategory>
```

which gives an error:

```
ACRA caught a InflateException for com.ichi2.anki.debug
android.view.InflateException: Binary XML file line #62: Error inflating class (not found)view
```

and on further searching I found: 
https://stackoverflow.com/a/2100111/9062752

where it is mentioned in the comments - 
`" The only way round this I've found is to promote the static nested class to a full-blown class in its own file, which isn't ideal."`

2025-01-05 14:41 UTC, closed without merging