[Cleanup]: Fix Android Studio Warnings in various Kotlin files #13282
ankidroid/Anki-Android pull request #16095
Opened 2024-04-04 22:44 UTC by BAH-HA

## Purpose / Description
Cleaning Android Studio Warnings in various Kotlin files
## Fixes
* Fixes #13282 

## Approach
Removed unused imports, changed some java functions to kotlin ones and fixed some code style issues

## How Has This Been Tested?

Ran ./gradlew jacocoUnitTestReport and ./gradlew jacocoAndroidTestReport

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ X] You have commented your code, particularly in hard-to-understand areas
- [X ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-04-04 23:44 UTC, david-allison approved these changes
Perfect, cheers!

In future, look into `squash`, `rebase` + `force-push` so we have a linear git history when merging

2024-04-05 08:29 UTC, BAH-HA commented
> Perfect, cheers!
> 
> In future, look into `squash`, `rebase` + `force-push` so we have a linear git history when merging.
> 
> Ideally each pull request should be available for us to "Rebase Merge" into main.

Thank you for the Feedback David, I'll take that into consideration in my future PR.

2024-04-05 17:48 UTC, lukstbit requested changes
Thanks for contributing!
I left two issues to fix and then we could merge this PR.

2024-04-05 17:48 UTC, lukstbit commented on api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
> +import com.ichi2.anki.FlashCardsContract as FlashCardsContract
There isn't any issue highlighted by the IDE for this import and the change itself doesn't fix anything. Please revert this.

2024-04-05 17:48 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt
> +            get() = spy(moveDirectoryContent) { it ->
Using _it_ for the lambda parameter name is confusing as the same name is used below with two different values + the standard name for the parameter of a lambda being _it_.
Please rename it to _moveDirectoryContent_ and change its usage below in _whenever_ as well.

2024-04-06 12:28 UTC, BAH-HA commented on api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
> +import com.ichi2.anki.FlashCardsContract as FlashCardsContract
Thank you for your Feedback, already committed the new changes

2024-04-06 12:28 UTC, BAH-HA commented on AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt
> +            get() = spy(moveDirectoryContent) { it ->
Done 👍

2024-04-06 16:07 UTC, lukstbit approved these changes
All good, thank you for making the changes.

2024-04-06 19:05 UTC, merged