Duplicating iw and he values folder
ankidroid/Anki-Android pull request #16178
Opened 2024-04-14 14:26 UTC by Aditya13s

## Purpose / Description
The purpose of this Pull Request is to ensure that the values-iw folder is duplicated with the values-he folder.
## Fixes
* Fixes #9451

## Approach
I just added a case that if the language is `iw` then it use `androidLanguage = "heb"`

## How Has This Been Tested?
I lack the means to test this.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-04-14 20:21 UTC, david-allison requested changes
> I lack the means to test this.

This affects our automated translation sync. It's not okay, especially as this change wouldn't work

You need to get this to the point that it's testable outside of production, start by looking at CI, then by contacting the author if you haven't been able to run the script

2024-04-14 20:21 UTC, david-allison commented on tools/localization/src/update.ts
> +                break;
`iw` isn't in the list of languages

2024-04-15 07:48 UTC, Aditya13s commented
> > I lack the means to test this.
> 
> This affects our automated translation sync. It's not okay, especially as this change wouldn't work
> 
> You need to get this to the point that it's testable outside of production, start by looking at CI, then by contacting the author if you haven't been able to run the script

`iw` works on old devices and i don't have any old device to test and I have doubt that do i have to manually copy `he` files in `iw` files

2024-04-15 10:00 UTC, david-allison commented
The automated copying process needs to be tested

2024-04-15 18:45 UTC, david-allison requested changes
Don't bother with the XML, this is about fixing the translation sync script

We don't want a manual step in the build process

2024-04-16 12:11 UTC, Aditya13s commented
> Don't bother with the XML, this is about fixing the translation sync script
> 
> We don't want a manual step in the build process

I removed the xml. I have no idea about what to change in the script. Please help me with that.

2024-04-16 13:27 UTC, david-allison commented
I don't have the capacity for that currently, sorry

2024-04-16 19:22 UTC, BrayanDSO commented
This PR is far from what the task needs, and the author themselves said that they don't know how to fix it. 

So, there's nothing to review here.

2024-04-16 19:22 UTC, closed without merging