chore: improve SharedDeckDownloadFragment logging
ankidroid/Anki-Android pull request #16171
Opened 2024-04-13 19:01 UTC by criticalAY

## Purpose / Description
The log gives only the status code not the reason, I added the reason too in the log

## Approach

## How Has This Been Tested?

`Status code -> 16, reason 1008`

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-04-13 20:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                        Timber.d("Status code -> ${it.getInt(columnIndex)}, reason ${it.getInt(columnIndexReason)}")
(On my phone), is this nullable, or could it potentially throw

2024-04-13 20:16 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                        Timber.d("Status code -> ${it.getInt(columnIndex)}, reason ${it.getInt(columnIndexReason)}")
Its not nullable, value is garunteed

2024-04-13 23:50 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                        Timber.d("Status code -> ${it.getInt(columnIndex)}, reason ${it.getInt(columnIndexReason)}")
```java
     * If {@link #COLUMN_STATUS} is neither {@link #STATUS_FAILED} nor {@link #STATUS_PAUSED}, this
     * column's value is undefined.
```

getInt:

```kotlin
Returns the value of the requested column as an int.
The result and whether this method throws an exception when the column value is null, the column type is not an integral type, or the integer value is outside the range [Integer.MIN_VALUE, Integer.MAX_VALUE] is implementation-defined.
```

write a `getIntOrNull` extension method on `Cursor`

2024-04-14 07:16 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                        Timber.d("Status code -> ${it.getInt(columnIndex)}, reason ${it.getInt(columnIndexReason)}")
Sorry :)

2024-04-14 08:39 UTC, david-allison requested changes
Last one!

2024-04-14 08:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        return if (columnIndex != -1) this?.getInt(columnIndex) else null
The issue is more likely to be with bad data (null/out of range/non integer), also wrap in a try...catch

2024-04-14 13:11 UTC, lukstbit approved these changes

2024-04-14 13:11 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +    fun Cursor?.getIntOrNull(columnIndex: Int): Int? {
One small nitpick, but make this method private.

2024-04-14 20:33 UTC, david-allison approved these changes

2024-04-14 20:48 UTC, merged