Added URL whitelist for SharedDecks WebView
ankidroid/Anki-Android pull request #16173
Opened 2024-04-13 20:55 UTC by eckertl

## Purpose / Description
Since the WebView in the shared decks import previously offered a completely unrestricted browsing experience, this made it possible to bypass browser locks, for example. As this enables procrastination on devices that do not actually have a browser, it makes sense to only allow the websites actually required in the WebView and to display all others via the browser. This means that regular users still have the option of accessing linked YouTube posts, for example, but users who do not have a browser, for example, can no longer do so and will therefore only be able to access Anki websites.

## Fixes
* Fixes #16172 

## Approach
A URL whitelist is introduced, and if a website that is not on the whitelist is called up within the WebView, it is opened via the standard browser.
![Implementation_Example](https://github.com/ankidroid/Anki-Android/assets/50594304/78a88c09-4428-4053-995e-5dea73433cd3)

Currently whitelisted hosts:
- ankiweb.net
- apps.ankiweb.net"
- ankiuser.net
- ankisrs.net

## How Has This Been Tested?
Tested on physical (Xiaomi Redmi Note 8 Pro) and emulated (Pixel 6) device.
I tested the following steps by using the import shared decks feature to create the host whitelist:
- Login
- Search
- Download
- Import

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2024-04-13 21:51 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +    private var allowedHosts = listOf<String>("ankiweb.net", "ankiuser.net", "ankisrs.net", "apps.ankiweb.net")
I think that this should be a const, not a var

2024-04-13 23:37 UTC, david-allison requested changes
Thanks!

Could we include  any subdomains of the provided sites, rather than just `apps.ankiweb.net`

`forums.ankiweb.net` specifically needs to be handled

But a `*` match on subdomain makes the code less brittle

2024-04-13 23:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +            startActivity(browserIntent)
use `AnkiActivity::openUrl` [in case a user doesn't have a browser]

2024-04-14 13:44 UTC, eckertl commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +            startActivity(browserIntent)
I looked for this kind of function but couldnt find it. It is now in use:
![no_browser](https://github.com/ankidroid/Anki-Android/assets/50594304/9cec4ab3-ead6-4d61-b6a3-8cf39909101c)

2024-04-14 20:29 UTC, david-allison requested changes

2024-04-14 20:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +            // Check if the requested host is whitelisted
Explain why we have a whitelist in the comment, the 'what' is pretty obvious

2024-04-14 20:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +    private val allowedHosts = listOf<Regex>(Regex("(.*\\W)?ankiweb\\.net\$"), Regex("ankiuser.net"), Regex("ankisrs.net"))
Why is this `\\W`?

You should be able to use three quotes to remove some escaping here

2024-04-14 22:04 UTC, eckertl commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +            // Check if the requested host is whitelisted
> Explain why we have a whitelist in the comment, the 'what' is pretty obvious

I'm not quite sure what you mean by that. Why we have this is already written above the function.
Should I explain the whole thing in more detail and write that we use a whitelist for this to prevent loading URLs which aren't needed for the import of shared decks?

Should I remove the comments within the function? Normally I wouldn't have used them, but I added them because of the checklist. The passages are not really difficult to understand anyway

2024-04-14 23:15 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +            // Check if the requested host is whitelisted
It's an unusual use-case (and almost guaranteed to produce bugs in the next couple of decades as domains change)

A comment for anyone going through the code to state that it's to avoid procrastination via using the AnkiDroid WebView as a bypass on a block on the default Web Browser

The comment on the function doesn't explain that, it's also a 'what'. The first reason anyone would ask is "why are we doing this"

Method comments: implementer's choice, pretty obvious what they're doing, I don't oppose them

2024-04-15 19:49 UTC, eckertl commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +            // Check if the requested host is whitelisted
Ah, I see. Thank you for the clarification

2024-04-16 00:29 UTC, david-allison approved these changes
Thanks!

2024-04-16 15:40 UTC, lukstbit approved these changes
LGTM, thank you for contributing!

2024-04-16 16:35 UTC, merged