Created Unit Test for fun refreshIfRequired
ankidroid/Anki-Android pull request #16188
Opened 2024-04-16 21:49 UTC by Haz3-jolt

## Purpose / Description
Added Unit test to function with @NeedsTest.

## Fixes
* Adds test for fun refreshIfRequired, which was tagged with @NeedsTest("if opExecuted is called while activity is in the background, audio plays onResume").

## Approach
- Making refreshIfRequired public so it is available for testing.
- Create a companion object for testing.
- Unit test with multiple cases to test for edge cases.
## How Has This Been Tested?
Ran the Unit test multiple times, and ensured it is passing.

## Checklist
- [-] You have a descriptive commit message with a short title (first line, max 50 chars).
- [-] You have commented your code, particularly in hard-to-understand areas
- [-] You have performed a self-review of your own code
- [] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-04-16 22:00 UTC, david-allison requested changes
Quality is great! 

You don't need to make all the changes here, just comment and resolve the ones you don't like

2024-04-16 22:00 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +    var refreshRequired: ViewerRefresh? = null
`@VisibleForTesting`

2024-04-16 22:00 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +    fun refreshIfRequired(isResuming: Boolean = false) {
ditto

2024-04-16 22:00 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerRefresh.kt
> +        val UpdateCard: ViewerRefresh
```suggestion
        val updateCard: ViewerRefresh
```

2024-04-16 22:00 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerRefresh.kt
> +        val UpdateCard: ViewerRefresh
If this is only used for testing, move it into the test class

2024-04-16 22:00 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.kt
> +        val controller = Robolectric.buildActivity(AbstractFlashcardViewerTest.NonAbstractFlashcardViewer::class.java)
this needs `.use { }` to ensure it's cleaned up

2024-04-16 22:00 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.kt
> +        var viewer = controller.create().start().get()
I'd consider `with (controller.get()` rather than using a `var`

2024-04-16 22:23 UTC, david-allison commented
```
> Task :AnkiDroid:ktlintMainSourceSetCheck FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerRefresh.kt:25:1 Unexpected indentation (20) (should be 12)

```

2024-04-17 00:40 UTC, david-allison commented
> [-] You have a descriptive commit message with a short title (first line, max 50 chars).

Use `[x]` and `[ ]` and you get:

> [x] You have a descriptive commit message with a short title (first line, max 50 chars).
> [ ] You have a descriptive commit message with a short title (first line, max 50 chars).

2024-04-17 12:52 UTC, david-allison approved these changes
Looks great! All comments are optional

2024-04-17 12:56 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +    internal fun refreshIfRequired(isResuming: Boolean = false) {
I tried with private, but it's invisible to the test even with the tag, so I used internal. Is there another way? Or should I just make it public.

2024-04-17 14:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +    internal fun refreshIfRequired(isResuming: Boolean = false) {
internal has little meaning for us, and it's more characters. Public is fine

2024-04-18 17:46 UTC, lukstbit approved these changes
Thanks!

2024-04-18 18:03 UTC, merged