fix: Use flags from col, dynamically loading them into the menu
ankidroid/Anki-Android pull request #16218
Opened 2024-04-19 07:33 UTC by criticalAY

## Purpose / Description
* Display Renamed Flags #16204 
This PR removes the static menu item - flags, from the menu and dynamically load the flag data which allow the user to access the renamed flags if they did rename them in Anki desktop 

## Fixes
* Fixes #16204

## Approach
Loaded flag from col

## How Has This Been Tested?
Anki ->
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/70239262-a716-4efa-8a7f-017b64391ac6)

AnkiDroid -> 
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/79fd23f9-6017-4878-800d-3f02c2e0baa6)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-04-19 07:35 UTC, criticalAY reviewed
The strings also differ in AnkiDroid i.e. the `flag` after them but I am not focusing on that here, and if we wish to reuse `addFlags` then I am all ears

2024-04-19 08:20 UTC, david-allison reviewed
CI issue

2024-04-19 12:59 UTC, criticalAY commented
I just want to test id this test is really causing the issue, if not then I will revert the commit

2024-04-19 14:41 UTC, david-allison requested changes
Thanks!

2024-04-19 14:41 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
> +    @Ignore("flaky")
Remove this test, we do it better elsewhere

```
E/ACRA: ACRA caught a BackendDbLockedException for com.ichi2.anki.debug
net.ankiweb.rsdroid.BackendException$BackendDbException$BackendDbLockedException: 
	at com.ichi2.anki.CollectionManager.ensureOpenInner(CollectionManager.kt:225)
	at com.ichi2.anki.CollectionManager.access$ensureOpenInner(CollectionManager.kt:39)
	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:101)
	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:100)
	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:86)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineId(9), "coroutine#9":StandaloneCoroutine{Cancelling}@14b99530, Dispatchers.Main.immediate]
W/ACRA: 
org.acra.collector.CollectorException: Error while retrieving LOGCAT data:Cannot run program "logcat": error=2, No such file or directory
	at org.acra.collector.BaseReportFieldCollector.collect(BaseReportFieldCollector.kt:60)
	at org.acra.data.CrashReportDataFactory.collect$lambda$10$lambda$9(CrashReportDataFactory.kt:69)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: Cannot run program "logcat": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at org.acra.collector.LogCatCollector.collectLogCat(LogCatCollector.kt:74)
	at org.acra.collector.LogCatCollector.collect(LogCatCollector.kt:103)
	at org.acra.collector.BaseReportFieldCollector.collect(BaseReportFieldCollector.kt:56)
	... 6 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 10 more
W/ACRA: 
org.acra.collector.CollectorException: Error while retrieving BUILD data:Cannot invoke "Object.getClass()" because "obj" is null
	at org.acra.collector.BaseReportFieldCollector.collect(BaseReportFieldCollector.kt:60)
	at org.acra.data.CrashReportDataFactory.collect$lambda$10$lambda$9(CrashReportDataFactory.kt:69)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
	at java.base/java.lang.reflect.Field.checkAccess(Field.java:1103)
	at java.base/java.lang.reflect.Field.get(Field.java:423)
	at org.acra.collector.ReflectionCollector$Companion.collectConstants(ReflectionCollector.kt:104)
	at org.acra.collector.ReflectionCollector$Companion.access$collectConstants(ReflectionCollector.kt:92)
	at org.acra.collector.ReflectionCollector.collect(ReflectionCollector.kt:45)
	at org.acra.collector.BaseReportFieldCollector.collect(BaseReportFieldCollector.kt:56)
	... 6 more
```

2024-04-19 14:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        tintOverflowMenuIcons(menu)
This feels like a race condition - continue to skip the flags

2024-04-19 14:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        val flag = Flag.entries.find { it.ordinal == item.itemId }
Use different IDs for multiselect and normal select, otherwise this can get nasty

2024-04-19 19:49 UTC, david-allison requested changes
Thanks! Should be the last round

I'd also encourage adding a follow-up issue to change the strings from `Red flag` to `Red` as is used upstream

2024-04-19 19:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            when (item.groupId) {
Use the constant values in the when

2024-04-19 19:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                subMenu?.add(Menu.NONE, flag.ordinal, Menu.NONE, title)?.setIcon(drawableRes)
It might be useful to add arg names for the `NONE` values

2024-04-19 19:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        return flagTitles.contains(menuItem.title.toString())
Is there another way to handle this with an immutable value?

Minor concern about titles changing either due to a rename of the flag, or a language change

2024-04-19 21:08 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                subMenu?.add(Menu.NONE, flag.ordinal, Menu.NONE, title)?.setIcon(drawableRes)
The none is set for group id and order and we don't care about them here, so I don' think it is required here

2024-04-19 21:08 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        return flagTitles.contains(menuItem.title.toString())
Can try with item id

2024-04-19 21:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                subMenu?.add(Menu.NONE, flag.ordinal, Menu.NONE, title)?.setIcon(drawableRes)
It probably isn't needed, but it's useful to have the argument names listed for documentation (if possible)

2024-04-19 21:23 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                subMenu?.add(Menu.NONE, flag.ordinal, Menu.NONE, title)?.setIcon(drawableRes)
ok gotchu

2024-04-19 22:48 UTC, david-allison approved these changes
Thanks! One more to go

2024-04-19 22:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                else -> updateFlagForSelectedRows(it)
`Mode.MULTI_SELECT`, then another `else` branch returning

2024-04-19 22:54 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                else -> updateFlagForSelectedRows(it)
Done!

2024-04-20 15:56 UTC, BrayanDSO requested changes

2024-04-20 15:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        }
Unnecessary refactor + removes logs + doesn't make it more readable, just shorter + slight performance cost

2024-04-20 15:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
> +        }
ditto

2024-04-20 15:56 UTC, BrayanDSO commented on AnkiDroid/src/main/res/menu/card_browser_multiselect.xml
> +          <!--  flags are dynamically added -->
```suggestion
          <!-- flags are dynamically added -->
```

2024-04-20 15:56 UTC, BrayanDSO commented on AnkiDroid/src/main/res/menu/card_browser.xml
> +            <!--  flags are dynamically added -->
```suggestion
            <!-- flags are dynamically added -->
```

2024-04-20 15:56 UTC, BrayanDSO commented on AnkiDroid/src/main/res/menu/previewer.xml
> +            <!--  flags are dynamically added -->
```suggestion
            <!-- flags are dynamically added -->
```

2024-04-20 15:56 UTC, BrayanDSO commented on AnkiDroid/src/main/res/menu/reviewer.xml
> +            <!--  flags are dynamically added -->
```suggestion
            <!-- flags are dynamically added -->
```

2024-04-20 15:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
> +// this is not part of the enum as getFlagNames should be used to handle overrides
add a `defaultNameRes` property to the enum instead of using a hashmap

2024-04-20 15:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
> +}
This method would be better placed in a `JSONObject` file inside the `com.ichi2.anki.utils.ext` package

2024-04-20 15:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
> +}
This method complicate things more than it should. You already have the flag and the drawableRes. The only thing that you want to get is the flag name.

So you could use a getName method inside the `Flag` enum:
```kotlin
    suspend fun getName(resources: Resources): String {
        val overrides = withCol { config.getObject("flagLabels", JSONObject()) }
        return overrides.getStringOrNull(code.toString()) ?: resources.getString(flagToName[this]!!)
    }
```
and replace the `getFlagData` loops with:
```kotlin
for (flag in Flag.entries) {
    val title = flag.getName(resources)
    submenu?.add(Menu.NONE, flag.ordinal, Menu.NONE, title)?.setIcon(flag.drawableRes)
}
```

2024-04-20 15:56 UTC, BrayanDSO commented on AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
> -    }
This removal should be in another commit or at least in the commit description. Somebody reading your code shouldn't need to read David's comment to get why this is being removed

2024-04-20 17:20 UTC, BrayanDSO requested changes

2024-04-20 17:20 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        }
Not resolved or had an explanation from the author (this isn't the first time that this happens with you)

2024-04-20 17:20 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
> +        }
Not resolved or had an explanation from the author

2024-04-20 17:24 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        }
Apologies, missed it, how do we expect to handle the menu item click? and we can add a generic log here.

2024-04-20 17:29 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        }
The alternatives aren't going to be easier, so just re-add the log

2024-04-20 17:38 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +        }
Done! thankyou for pointing out my oversight will keep in mind  for future reviews

2024-04-20 17:39 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
> +            Timber.i("PreviewerFragment:: $it")
Specify that this is under onMenuItemClick. Same for the reviewer call

2024-04-20 17:49 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
> +            Timber.i("PreviewerFragment:: onOptionItemSelected Flag - $it clicked")
Wrong method name

2024-04-20 17:52 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
> +            Timber.i("PreviewerFragment:: onOptionItemSelected Flag - $it clicked")
Ahhhhhh I am soooo sorryyyy :(

2024-04-20 18:36 UTC, BrayanDSO requested changes

2024-04-20 18:36 UTC, BrayanDSO commented on AnkiDroid/src/main/res/menu/previewer.xml
> -            <item
Actually, can't just the titles be added dynamically? Removing them makes harder to preview in the XML layout previewer

2024-04-20 18:37 UTC, criticalAY commented on AnkiDroid/src/main/res/menu/previewer.xml
> -            <item
That makes things not dynamic but just some portion of it, and I suspect it will make thing messy

2024-04-20 18:43 UTC, BrayanDSO commented on AnkiDroid/src/main/res/menu/previewer.xml
> -            <item
So that's a yes that doesn't break XML previews. I trust that you can solve it without doing a mess

2024-04-20 19:03 UTC, criticalAY commented on AnkiDroid/src/main/res/menu/previewer.xml
> -            <item
We can do that, but the current code doesn't break the xml preview 
i.e. 
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/0d4b2e23-1bd7-4fe7-bc29-f67758daf1c6)

2024-04-20 20:42 UTC, BrayanDSO commented on AnkiDroid/src/main/res/menu/previewer.xml
> -            <item
Oh, my bad. Looks good then. Thanks!

2024-04-20 20:43 UTC, BrayanDSO approved these changes

2024-04-20 22:02 UTC, merged