Added hint text on "Set due date"
ankidroid/Anki-Android pull request #16224
Opened 2024-04-20 06:02 UTC by Giyutomioka-SS

## Purpose
It would be helpful to add hint text to the "Set due date" field, clarifying that "0 days" indicates today, as it does in the desktop version.

## Fixes
#16199

## How Has This Been Tested?
On Realme 6 & Emulator 

## Screenshot's
![image (2)](https://github.com/ankidroid/Anki-Android/assets/91668590/0466d284-ba12-4457-9557-a560da409a6c)

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-04-20 06:59 UTC, david-allison commented
Meta: In future, could you use the `Fixes` syntax of : `* Fixes #16199`

2024-04-20 07:00 UTC, david-allison requested changes
Check with @snowtimeglass for a suggested design if you're struggling for inspiration

2024-04-20 07:00 UTC, david-allison commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="set_due_date_hintText">\'0\' days means today</string>
Use mart quotes, not `'`

2024-04-20 07:00 UTC, david-allison commented on AnkiDroid/src/main/res/layout/set_due_date_single.xml
> +            android:hint="@string/set_due_date_hintText"
We don't want to use `android:hint` here, this does not look good

2024-04-20 07:00 UTC, david-allison commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +
nit: revert this

2024-04-20 10:42 UTC, snowtimeglass commented
What do you think of using helperText as in #16037?
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/52ff111b-25c3-4b1e-8b62-399050f0e6e2)

2024-04-20 11:57 UTC, Giyutomioka-SS commented
Is this looks good ?
![image](https://github.com/ankidroid/Anki-Android/assets/91668590/d7f36fbf-b707-4fc5-92b5-098af4dcd6fa)

2024-04-20 12:49 UTC, snowtimeglass commented
It looks good to me. Thank you :)


Regarding the content of the string, I'm wondering if you would change it as follows:
```diff
- "0" days means today
+ "0 days" means today
```

2024-04-20 17:34 UTC, david-allison requested changes

2024-04-20 17:34 UTC, david-allison commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="set_due_date_hintText">\"0 days\" means today</string>
Use smart single quotes

2024-04-20 17:34 UTC, david-allison commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="set_due_date_hintText">\"0 days\" means today</string>
Use smart single quotes

```suggestion
    <string name="set_due_date_hintText">‘0 days’ is today; ‘1 day’ is tomorrow etc…</string>
```

2024-04-20 17:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
> +                helperText = getString(R.string.set_due_date_hintText)
define this in the XML

2024-04-20 17:51 UTC, Giyutomioka-SS commented
is this looks good @david-allison 

![image](https://github.com/ankidroid/Anki-Android/assets/91668590/c092def7-a0c8-4527-97c1-dba1daf8a4d6)

2024-04-20 18:20 UTC, david-allison reviewed
It does! Apologies for the final feedback round, I feel this will look better

2024-04-20 18:20 UTC, david-allison commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="set_due_date_hintText">‘0 days’ is today; ‘1 day’ is tomorrow etc…</string>
```suggestion
    <string name="set_due_date_hintText">Today is ‘0 days’, tomorrow is ‘1 day’, etc…</string>
```

2024-04-20 18:22 UTC, david-allison approved these changes
That's it, thanks!

Screenshot of the final result would be great

2024-04-20 18:29 UTC, Giyutomioka-SS commented
Final result screenshot @Giyutomioka-SS 
![image](https://github.com/ankidroid/Anki-Android/assets/91668590/6939c238-87e2-47e4-8cb9-68399cac9ba8)

2024-04-20 20:47 UTC, BrayanDSO commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="set_due_date_hintText">Today is ‘0 days’, tomorrow is ‘1 day’, etc…</string>
I suggest using the strings themselves in the hint, i.e. `Today is ‘%1$s’, tomorrow is ‘%2$s’, etc…`, so there won't be a translations mismatch

2024-04-21 10:21 UTC, Giyutomioka-SS commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="set_due_date_hintText">Today is ‘0 days’, tomorrow is ‘1 day’, etc…</string>
@BrayanDSO When I follow your instructions in XML by passing the helper text argument like this: app:helperTextArguments="0 days, 1 day"
I encounter an error during the build process stating: Attribute helperTextArguments (aka com.ichi2.anki.debug:helperTextArguments) not found.

However, when I write code in the SetDueDateDailog.kt file, everything works fine:
helperText = getString(R.string.set_due_date_hintText, "0 days", "1 day")

But @david-allison prefers this to be done in XML.

2024-04-21 12:31 UTC, david-allison commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="set_due_date_hintText">Today is ‘0 days’, tomorrow is ‘1 day’, etc…</string>
If it's got parameters, then it should be in Kotlin 

Use a `tools:` attribute to set the XML preview

2024-04-21 12:31 UTC, david-allison commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="set_due_date_hintText">Today is ‘0 days’, tomorrow is ‘1 day’, etc…</string>
Also, the parameters should be the result of `getString` calls

2024-04-21 12:38 UTC, snowtimeglass commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="set_due_date_hintText">Today is ‘0 days’, tomorrow is ‘1 day’, etc…</string>
```suggestion
    <string name="set_due_date_hintText">Today is ‘0 days’, tomorrow is ‘1 day’, and so on</string>
```

I suppose "and so on" is more appropriate here since it works as abbreviation of examples that can be inferred.

2024-04-21 18:23 UTC, david-allison requested changes
I /think/ this is the best option.

We don't have '0 days', we only have the suffix: 'day/days' as it's implemented as `suffixText`

```patch
Subject: [PATCH] CSS: Match Anki Desktop

https://github.com/ankitects/anki/blob/00248665d70fad5bf3c1679db0871ae7418d399f/ts/reviewer/reviewer.scss#L13

Fixes 16236
Fixes 16227
---
Index: AnkiDroid/src/main/res/values/07-cardbrowser.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/res/values/07-cardbrowser.xml b/AnkiDroid/src/main/res/values/07-cardbrowser.xml
--- a/AnkiDroid/src/main/res/values/07-cardbrowser.xml	(revision 3f2230dce694224e6f1eea1cf5caa23bb58b2900)
+++ b/AnkiDroid/src/main/res/values/07-cardbrowser.xml	(date 1713723652500)
@@ -75,9 +75,7 @@
     <string name="card_browser_search_all_decks">Search all decks</string>
     <string name="card_browser_unknown_deck_name">Unknown</string>
     <string name="card_browser_truncate" comment="allows users to show less of a field value">Truncate content</string>
-    <string name="set_due_date_hintText">‘Today is ‘%1$s’, tomorrow is ‘%2$s’, and so on…</string>
-    <string name="zero_days">0 days</string>
-    <string name="one_day">1 day</string>
+    <string name="set_due_date_hintText">‘Today is ‘0 %1$s’, tomorrow is ‘1 %2$s’, and so on…</string>
     <plurals name="card_browser_export_cards">
         <item quantity="one">Export card</item>
         <item quantity="other">Export cards</item>
Index: AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt	(revision 3f2230dce694224e6f1eea1cf5caa23bb58b2900)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt	(date 1713723652497)
@@ -212,7 +212,10 @@
                         suffixText = resources.getQuantityString(R.plurals.set_due_date_label_suffix, currentValue ?: 0)
                     }
                     suffixText = resources.getQuantityString(R.plurals.set_due_date_label_suffix, 0)
-                    helperText = getString(R.string.set_due_date_hintText, getString(R.string.zero_days), getString(R.string.one_day))
+                    helperText = getString(R.string.set_due_date_hintText,
+                        resources.getQuantityString(R.plurals.set_due_date_label_suffix, 0), // 0 days
+                        resources.getQuantityString(R.plurals.set_due_date_label_suffix, 1), // 1 day
+                    )
                 }
             }
             view.findViewById<TextView>(R.id.date_single_label).text =
```

2024-04-21 18:26 UTC, david-allison commented
I prefer 'etc...' over 'and so on...', for brevity

@snowtimeglass your English grammar is likely better than mine (as you learned formally), do you have strong feelings here?

2024-04-21 18:31 UTC, Giyutomioka-SS commented
Here is the Updated Screenshot  @david-allison @BrayanDSO 
![image](https://github.com/ankidroid/Anki-Android/assets/91668590/51c13383-2646-4b41-812a-7d30a0bb30e6)

2024-04-21 18:47 UTC, david-allison commented
I updated my patch above, there should not be a `'` at the start of the string

2024-04-21 19:19 UTC, david-allison approved these changes
Thanks! 

As stated, I prefer "etc..." when written, but it's a non-blocker and one for discussion

2024-04-21 19:45 UTC, Giyutomioka-SS commented
> Thanks!
> 
> As stated, I prefer "etc..." when written, but it's a non-blocker and one for discussion

In my view, both 'etc.' and 'and so on' are acceptable. However, 'and so on' is generally more formal, while 'etc.' is more casual.

2024-04-22 01:15 UTC, snowtimeglass commented
@david-allison  Thank you for the kind words. 
>do you have strong feelings here?

No, I don't have strong feelings there. If "etc." is a natural expression in this case, I'm fine with it.

2024-04-22 04:54 UTC, david-allison commented
As always, thank you!

Go with `etc…` (checked with a couple of friends and they also feel it's more natural)

2024-04-22 11:24 UTC, Aditya13s approved these changes

2024-04-22 12:44 UTC, david-allison approved these changes
I'd approved, requesting for approval again removes that from the UI

Looks greater than before, and it was great then!

2024-04-22 17:10 UTC, lukstbit approved these changes
Thanks!

2024-04-22 17:56 UTC, david-allison commented
@Giyutomioka-SS this becomes easier to merge if you squash merge it

2024-04-23 08:39 UTC, Giyutomioka-SS commented
> @Giyutomioka-SS this becomes easier to merge if you squash merge + force push it

Done @david-allison

2024-04-23 09:09 UTC, david-allison commented
Thanks, I'll get strings synced when I'm back at my PC

2024-04-23 09:28 UTC, david-allison commented
* https://github.com/ankidroid/Anki-Android/pull/16247#pullrequestreview-2016559325

2024-04-23 11:17 UTC, lukstbit commented
@Giyutomioka-SS Thanks for squashing, this will make it easier to merge. Could you also change the name of the commit to something more relevant? "Squashed Commmit" doesn't tell anything about what work was done in the commit and makes it harder to understand the change history. Something like "_Add hint text on "Set due date" dialog_" would work just fine.

You can do this with _git commit --amend_(changes the last commit) and then again force push.

2024-04-23 11:32 UTC, Giyutomioka-SS commented
> the last commit) and then again force push.

Done @lukstbit

2024-04-23 12:22 UTC, merged