feat(check-pronunciation): Streamline UX
ankidroid/Anki-Android pull request #16248
Opened 2024-04-22 18:32 UTC by david-allison

## Purpose / Description
A few issues/suggestions were raised in #16185 about the audio recorder changes introduced for #13043

* takes up too much space on 
* increased number of touches required
* ❓ stops working after a while
* ❌ move the recorder to the bottom of the screen
* ✅ A long-press should start, releasing the long-press should stop

## Fixes
* Fixes #16185

## Approach

1) Major refactor to improve the state handling logic
2) Simplify the Reviewer state to the following, add a new layout and changes to the Waveform control:

```mermaid
stateDiagram-v2
    direction LR
    [*] --> Empty

    Empty --> Recording : ⏺️
    Recording --> Empty : ❎
    Recording --> Playback : ⏹️
    Playback --> Empty : ❎

    state Playback {
        [*]  --> p1
        p1: Paused
        p2: Playing

        p1 --> p2 : ▶️
        p2 --> p1 : ↩️
    }
```

3) Add 'on hold' logic for long presses

## How Has This Been Tested?

https://github.com/ankidroid/Anki-Android/assets/62114487/6fb5c329-152e-4c89-b231-f2ac2ac4395c

## Learning (optional, can help others)
* `onStop`
* Adding custom attributes to Views
* MaterialButton is hard when it comes to centering icons

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)
    - [ ] ⚠️ no issues with touch targets. Historical issues with 'item label' - proposing to extract to another issue

2024-04-22 21:06 UTC, criticalAY approved these changes
Nice!! Especially the AudioRecorderController, using enum 👍 , Looks good to me!!

2024-04-22 21:40 UTC, criticalAY requested changes
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/a449e8b5-09c8-4a8d-8b4c-43e72ce0f552)
 
The waveform is not visible

2024-04-23 02:43 UTC, mikehardy approved these changes
always daunting to see "large diffs hidden by default" type message in the commit viewer but ... all looks good, much more readable style with the enum state handling

2024-04-23 10:44 UTC, criticalAY reviewed
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/d7934fe4-2341-4451-b250-eb3b8943ae9b)

It works fine in reviewer but in multimedia it has this issue now, Potrait -> Landscape -> Potrait, result in wave form to be invisible

2024-04-23 11:52 UTC, david-allison commented
https://github.com/ankidroid/Anki-Android/assets/62114487/3452207d-72c3-415e-a1ae-3c223652626d

@criticalAY Could I get a logcat? Can't reproduce

2024-04-23 11:57 UTC, david-allison commented
@criticalAY Can't reproduce

Could you check 0a629925b427cc21a8c7877d19d31fe3522a8343 and 7879edfa469178e5d974cdadbd7a13846e44845e to find the bad commit


https://github.com/ankidroid/Anki-Android/assets/62114487/f7d82d2f-7610-4770-80f8-a460d658370b

2024-04-23 13:30 UTC, criticalAY commented
This PR too

2024-04-23 15:11 UTC, david-allison commented
For clarity: And also `main`?

2024-04-23 15:14 UTC, criticalAY commented
Yes, both main and this PR have issue on emulator

2024-04-26 18:03 UTC, BrayanDSO commented
My concerns:
- The `Replay` icon *stops* the audio instead of replaying it, which is unintuitive to me.
- There shouldn't be a delay between long pressing the record button and the recording start

2024-04-27 14:29 UTC, david-allison commented
> My concerns:
> 
> * The `Replay` icon _stops_ the audio instead of replaying it, which is unintuitive to me, so I suggest using another icon.

If I can find an icon similar to this, would it be acceptable?

<img width="172" alt="Screenshot 2024-04-27 at 15 26 59" src="https://github.com/ankidroid/Anki-Android/assets/62114487/f3d7efd5-ac01-44ee-93ba-379f16705926">


> * There shouldn't be a delay between long pressing the record button and the recording start.

So this would be moving 'record' to `ACTION_DOWN`?

2024-04-27 14:41 UTC, david-allison commented
Crash on closing the screen while recording is playing back

```
15:40:50.466 AndroidRuntime          com.ichi2.anki.debug                 E  FATAL EXCEPTION: main
                                                                             Process: com.ichi2.anki.debug, PID: 9262
                                                                             java.lang.IllegalStateException
                                                                             	at android.media.MediaPlayer._pause(Native Method)
                                                                             	at android.media.MediaPlayer.pause(MediaPlayer.java:1573)
                                                                             	at com.ichi2.audio.AudioRecordingController.controlAudioRecorder(AudioRecordingController.kt:483)
                                                                             	at com.ichi2.audio.AudioRecordingController.createUI$lambda$4(AudioRecordingController.kt:190)
                                                                             	at com.ichi2.audio.AudioRecordingController.$r8$lambda$Kt6IrF7armXMsCjnga1mPK4zvx0(Unknown Source:0)
                                                                             	at com.ichi2.audio.AudioRecordingController$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
                                                                             	at android.view.View.performClick(View.java:8043)
                                                                             	at android.widget.TextView.performClick(TextView.java:17816)
                                                                             	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)
                                                                             	at android.view.View.performClickInternal(View.java:8020)
                                                                             	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                             	at android.view.View$PerformClick.run(View.java:31850)
                                                                             	at android.os.Handler.handleCallback(Handler.java:958)
                                                                             	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                             	at android.os.Looper.loopOnce(Looper.java:230)
                                                                             	at android.os.Looper.loop(Looper.java:319)
                                                                             	at android.app.ActivityThread.main(ActivityThread.java:8893)
                                                                             	at java.lang.reflect.Method.invoke(Native Method)
                                                                             	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                                                                             	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

2024-04-27 15:11 UTC, BrayanDSO commented
> If I can find an icon similar to this, would it be acceptable?

I won't block because of the icon, so choose what you like more.

> So this would be moving 'record' to ACTION_DOWN?

Yes. Either record while pressing, or press once then stop when pressed again

2024-04-27 15:37 UTC, david-allison commented
![image](https://github.com/ankidroid/Anki-Android/assets/62114487/8d949d0c-c5cb-48b4-ae01-08aa3193cba3)

I'll propose to drop the final commit so this can go in, would that be acceptable?

2024-04-27 15:40 UTC, BrayanDSO commented
> I'll propose to drop the final commit so this can go in, would that be acceptable?

Yeah. Add an issue for the holding feature then

2024-04-27 15:40 UTC, BrayanDSO approved these changes

2024-04-27 15:47 UTC, david-allison commented
Blocked on https://github.com/ankidroid/Anki-Android/pull/16248#issuecomment-2080812264

2024-04-28 08:44 UTC, merged