Enhancement: allow renaming flag from CardBrowser menu
ankidroid/Anki-Android pull request #16244
Opened 2024-04-22 09:23 UTC by criticalAY

## Purpose / Description
* #16205, Anki allows flag to be renamed from card browser so replicating that this PR provides a menu option through which we can rename the flag and after sync the same is reflected in Anki desktop 

## Fixes
* Fixes #16205

## How Has This Been Tested?
AnkiDroid:
![Screenshot 2024-04-22 144750](https://github.com/ankidroid/Anki-Android/assets/48384865/a5774ebc-356c-400f-af90-ee9047e74ab0)

Anki after sync:
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/526f468a-33f2-4f92-928e-a3e8ab869bfe)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-04-22 09:31 UTC, criticalAY commented
I have placed the rename option in menu for now, reason too many steps would be required in that case 
Menu -> Options dialog -> Rename flag -> One more dialog consisting of the list of flag -> flag clicked -> another rename dialog

2024-04-22 11:29 UTC, lukstbit requested changes
> I have placed the rename option in menu for now, reason too many steps would be required in that case
> Menu -> Options dialog -> Rename flag -> One more dialog consisting of the list of flag -> flag clicked -> another rename dialog

Again, this is not an option that will be used by many users and even those that are going to use it are going to use it a few times. There's no justification to have this option cluttering the menu for everyone for such small/specific usage.

_Menu -> Options dialog -> Rename flag -> **One** dialog_

That dialog can both display the flags with their current name and an option to edit them _inline_. For example, for a flag entry, initially show a TextView + Button to rename(maybe also the flag icon so it's more clear). When the rename button is clicked replace the TextView + Button with an EditText + 2 Buttons(1 for accept and 1 for cancel the new name). This way the user both sees the current names + has the option to edit all of them in the same dialog.

2024-04-22 16:39 UTC, criticalAY commented
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/d34afb8d-620c-4fbb-8650-db8eb7291a2b)

![image](https://github.com/ankidroid/Anki-Android/assets/48384865/b04ec32e-9f87-4ff0-b57d-816761a38fac)

2024-04-22 18:11 UTC, lukstbit requested changes

2024-04-22 18:47 UTC, david-allison requested changes
Anki Desktop does not allow 'No Flag' to be renamed

2024-04-22 18:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/FlagRenameDialog.kt
> +        dialog?.window?.clearFlags(
`setupDialog` would be better

2024-04-22 18:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/FlagRenameDialog.kt
> +        val dialogView = inflater.inflate(R.layout.rename_flag_layout, null)
nit: combine to a single line

2024-04-22 20:36 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/FlagRenameDialog.kt
> +        dialog?.window?.clearFlags(
Doesnt work with it

2024-04-22 20:38 UTC, criticalAY commented
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/ec233467-f0ab-47ff-ab2c-249599fae8ba)
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/f6e39c67-929f-4b8c-a0f6-53e98c80022c)
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/f0a7de95-c517-41d6-a2bb-0331dd24431a)

2024-04-23 00:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/FlagRenameDialog.kt
> +                flag.getName(requireContext().resources) == getString(R.string.menu_flag_card_zero)
`.filter { it != Flag.NONE }` is likely more accurate

2024-06-03 21:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/FlagRenameDialog.kt
> +            // TODO: Extract pending changes from the adapter and save them
Specifically: I'm being lazy here

I didn't like the fact that pressing 'OK' closed the dialog

But don't have the capacity to extract the logic from the ViewHolder, or handle the `FlagItem` matching the state of the adapter's edit mode (`.copy()` is used, changing references)

2024-06-03 21:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/FlagRenameDialog.kt
> +                showThemedToast(R.string.confirm_before_saving, true)
I'm hoping this is temporary code, so not putting effort into getting the snackbar working inside the dialog

2024-06-12 17:00 UTC, lukstbit requested changes
I think the changes are good, left some minor improvements.

2024-06-12 17:00 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/FlagRenameDialog.kt
> +            // TODO: Extract pending changes from the adapter and save them
It's ok, this is not the feature to spend too much time on it,

2024-06-17 13:55 UTC, lukstbit approved these changes
LGTM.
If you don't get to this by then, I'll merge it in a few hours.

2024-06-17 17:18 UTC, merged

2024-06-20 11:59 UTC, snowtimeglass commented
First of all, thanks for the great work. I think that not a few users have been looking forward to this useful feature.

It seems that pressing "Cancel" button (at the bottom of the following dialog box) doesn't cancel flag names edited and "checked"(✓) on the spot. 

Even then, is it desirable to place the "Cancel" and "OK" button in the dialog box? For now, I'm a bit concerned whether the role of "Cancel" button might be confusing. Is no button (or single button, "Close") not good in this case? 

<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/1c9a3685-7e28-44c8-b97b-74ea38d8838b" width="320px">