AnkiDroid to use flag names like anki
ankidroid/Anki-Android pull request #16242
Opened 2024-04-21 20:00 UTC by Giyutomioka-SS

## Purpose / Description
AnkiDroid to use Flag names like Anki 

## Fixes
* Fixes #16222 

## How Has This Been Tested?
On Realme 6 & Emulator

## Screen Recording
https://github.com/ankidroid/Anki-Android/assets/91668590/67718564-a5d6-44c6-b6cb-7f6b2ae89f30

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-04-21 20:55 UTC, david-allison requested changes

2024-04-21 20:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
> +    PURPLE(7, R.drawable.ic_flag_purple, R.color.flag_purple, TR.actionsFlagPurple());
Store a reference to the function, not the result of the function. 

`defaultNameRes` should be `() -> String`

This means it works when a user has changed languages in the settings

2024-04-21 21:30 UTC, Giyutomioka-SS commented on AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
> +    PURPLE(7, R.drawable.ic_flag_purple, R.color.flag_purple, TR.actionsFlagPurple());
Shouldn't it be like this: TR::browsingNoFlag ?

2024-04-21 21:51 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
> +    PURPLE(7, R.drawable.ic_flag_purple, R.color.flag_purple, TR.actionsFlagPurple());
Yep, sounds corect

2024-04-21 21:53 UTC, david-allison requested changes
Looks great! Needs to handle errors, other than that, the other comment is a nitpick and this is good to go

2024-04-21 21:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
> +    private val defaultNameRes: () -> String
```
    private val defaultBackendName: () -> String
```

2024-04-21 21:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
> +        return overrides.getStringOrNull(code.toString()) ?: defaultNameRes()
handle `defaultNameRes` throwing (if the backend is not open for some reason)

2024-04-21 21:59 UTC, criticalAY commented
`'byte[][] net.ankiweb.rsdroid.NativeMethods.openBackend(byte[])'`
Unit test are likely to fail again

2024-04-21 22:39 UTC, Giyutomioka-SS commented
@david-allison, Unit tests are failing again. What should be done?

2024-04-22 05:18 UTC, Aditya13s commented
@Giyutomioka-SS Remove the code or resource which are not in use.

2024-04-22 20:45 UTC, david-allison commented
Ping me in 24h, feel free to pick up another issue in the meantime

2024-04-24 05:02 UTC, Giyutomioka-SS commented
@david-allison

2024-04-24 05:02 UTC, Giyutomioka-SS commented
> Ping me in 24h, feel free to pick up another issue in the meantime

@david-allison

2024-04-24 22:21 UTC, david-allison commented
@Giyutomioka-SS with apologies, my laptop died today. 

Try our Discord for now, I'll be a while to get back to normal

2024-04-25 11:04 UTC, Giyutomioka-SS commented
@david-allison please don’t apologize, machines can give up anytime, and i always keep a tab on anki discord just don’t talk much😂

2024-04-25 15:42 UTC, david-allison commented
Feel free to ping the channel for help/a review, it's what we're here for!

2024-04-25 17:51 UTC, mikehardy commented
Not sure why, but the backend is not being found?

```

        Caused by:
        java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: 'byte[][] net.ankiweb.rsdroid.NativeMethods.openBackend(byte[])' [in thread "ForkJoinPool-1-worker-1"]
            at net.ankiweb.rsdroid.NativeMethods.openBackend(Native Method)
            at net.ankiweb.rsdroid.Backend.<init>(Backend.kt:79)
            at net.ankiweb.rsdroid.BackendFactory.getBackend(BackendFactory.kt:39)
            at net.ankiweb.rsdroid.BackendFactory.getBackend$default(BackendFactory.kt:37)
            at com.ichi2.anki.CollectionManager.ensureBackendInner(CollectionManager.kt:183)
            at com.ichi2.anki.CollectionManager.access$ensureBackendInner(CollectionManager.kt:39)
            at com.ichi2.anki.CollectionManager$getBackend$1$1.invoke(CollectionManager.kt:132)
            at com.ichi2.anki.CollectionManager$getBackend$1$1.invoke(CollectionManager.kt:132)
            at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:86)
            at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:42)
            at com.ichi2.anki.CollectionManager$getBackend$1.invokeSuspend(CollectionManager.kt:132)
```

I looked at the commit history - it should be squashed - no reason for 5 commits - so I recommend learning how `git rebase` works and perhaps doing a `git rebase -i HEAD~5` then changing `pick` on commits 2 through 5 to `squash` and after getting your local branch cleaned up like that so it is a single commit doing a `git push --force-with-lease` to push your cleaned-up local branch back out to github for this PR - that will kick off CI again and perhaps the linker problem will be solved?

If it is not solved by that, then I would also do a `git add remote upstream git@github.com:ankidroid/Anki-Android`, then a `git fetch upstream`, then a `git rebase upstream/main` on your branch to pull in all upstream changes to make sure the backend dependency is correct and again `git push --force-with-lease` to push those changes back out to github so the PR is updated. That will run CI again and hopefully the problem will be solved?

2024-04-26 20:39 UTC, criticalAY commented
@david-allison @Giyutomioka-SS It is blocked until I come up with the right code to handle the flag names, as the previous commit I made related to flag names was reverted

2024-04-26 22:56 UTC, BrayanDSO commented
>  It is blocked until I come up with the right code to handle the flag names,

I don't see a reason for blocking this one. It doesn't matter which PR goes first, as long as is works and doesn't break CI

2024-04-26 23:03 UTC, criticalAY commented
This PR uses a method which was reverted to fix the CI failure and that is the reason for the conflicts, but if you intend to replace strings only then go ahead, @Giyutomioka-SS remember to find and replace the strings at all places now

2024-05-13 17:38 UTC, Giyutomioka-SS commented
@BrayanDSO @david-allison @criticalAY is this good now ??

2024-05-13 17:48 UTC, criticalAY commented
Looks good to me

2024-05-13 18:13 UTC, criticalAY approved these changes

2024-05-14 15:49 UTC, david-allison requested changes
Implementer's choice: One request to remove duplication, rest looks good

Thanks!

2024-05-14 15:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        menu.findItem(R.id.action_select_flag_zero).title = TR.browsingNoFlag()
Can these be moved to be properties of `Flag`: ``Flag.RED.displayName()`

2024-05-17 12:31 UTC, david-allison requested changes
This is no longer using the backend


displayName should be a method

2024-05-17 13:44 UTC, criticalAY commented
On my phone but there should be a better way than the current code to achieve the same result @Giyutomioka-SS instead of overriding it for all the strings

2024-05-17 14:09 UTC, Giyutomioka-SS commented
> On my phone but there should be a better way than the current code to achieve the same result @Giyutomioka-SS instead of overriding it for all the strings

In that case, I guess backend need to provides the display name along with other flag information.

2024-05-17 15:21 UTC, Giyutomioka-SS commented
> On my phone but there should be a better way than the current code to achieve the same result @Giyutomioka-SS instead of overriding it for all the strings

Unit tests are failing if I am using TR this way in Flag.kt should I revert this to the previous commit it works fine.

2024-05-17 16:45 UTC, criticalAY requested changes
Will approve after the blue flag name is corrected

2024-05-17 16:45 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
> +    BLUE(4, R.drawable.ic_flag_blue, R.color.flag_blue, TR.actionsFlagGreen()),
Green flag for Blue?

2024-05-17 16:45 UTC, criticalAY commented on AnkiDroid/src/main/res/menu/card_browser.xml
> +                tools:title="Red Flag"
Optional: Remove flag after the flag names so that it is consistent with Anki, though this is dev only

2024-05-17 21:32 UTC, david-allison approved these changes
Cheers

2024-05-17 21:33 UTC, david-allison requested changes
Tests are failing

2024-05-17 22:00 UTC, david-allison requested changes
I believe:

<details>


```patch
Subject: [PATCH] feat: Toggle Bury

Issue 14163
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt b/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt	(revision 9fb827d72dcbb33cfc10761fbed02216a09f0181)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt	(date 1715982065094)
@@ -851,14 +851,14 @@
     }
 
     private fun setFlagTitles(menu: Menu) {
-        menu.findItem(R.id.action_flag_zero).title = Flag.NONE.displayName
-        menu.findItem(R.id.action_flag_one).title = Flag.RED.displayName
-        menu.findItem(R.id.action_flag_two).title = Flag.ORANGE.displayName
-        menu.findItem(R.id.action_flag_three).title = Flag.GREEN.displayName
-        menu.findItem(R.id.action_flag_four).title = Flag.BLUE.displayName
-        menu.findItem(R.id.action_flag_five).title = Flag.PINK.displayName
-        menu.findItem(R.id.action_flag_six).title = Flag.TURQUOISE.displayName
-        menu.findItem(R.id.action_flag_seven).title = Flag.PURPLE.displayName
+        menu.findItem(R.id.action_flag_zero).title = Flag.NONE.displayName()
+        menu.findItem(R.id.action_flag_one).title = Flag.RED.displayName()
+        menu.findItem(R.id.action_flag_two).title = Flag.ORANGE.displayName()
+        menu.findItem(R.id.action_flag_three).title = Flag.GREEN.displayName()
+        menu.findItem(R.id.action_flag_four).title = Flag.BLUE.displayName()
+        menu.findItem(R.id.action_flag_five).title = Flag.PINK.displayName()
+        menu.findItem(R.id.action_flag_six).title = Flag.TURQUOISE.displayName()
+        menu.findItem(R.id.action_flag_seven).title = Flag.PURPLE.displayName()
     }
 
     @SuppressLint("RestrictedApi")
Index: AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt	(revision 9fb827d72dcbb33cfc10761fbed02216a09f0181)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt	(date 1715982065097)
@@ -206,14 +206,14 @@
     }
 
     private fun setFlagTitles(menu: Menu) {
-        menu.findItem(R.id.action_flag_zero).title = Flag.NONE.displayName
-        menu.findItem(R.id.action_flag_one).title = Flag.RED.displayName
-        menu.findItem(R.id.action_flag_two).title = Flag.ORANGE.displayName
-        menu.findItem(R.id.action_flag_three).title = Flag.GREEN.displayName
-        menu.findItem(R.id.action_flag_four).title = Flag.BLUE.displayName
-        menu.findItem(R.id.action_flag_five).title = Flag.PINK.displayName
-        menu.findItem(R.id.action_flag_six).title = Flag.TURQUOISE.displayName
-        menu.findItem(R.id.action_flag_seven).title = Flag.PURPLE.displayName
+        menu.findItem(R.id.action_flag_zero).title = Flag.NONE.displayName()
+        menu.findItem(R.id.action_flag_one).title = Flag.RED.displayName()
+        menu.findItem(R.id.action_flag_two).title = Flag.ORANGE.displayName()
+        menu.findItem(R.id.action_flag_three).title = Flag.GREEN.displayName()
+        menu.findItem(R.id.action_flag_four).title = Flag.BLUE.displayName()
+        menu.findItem(R.id.action_flag_five).title = Flag.PINK.displayName()
+        menu.findItem(R.id.action_flag_six).title = Flag.TURQUOISE.displayName()
+        menu.findItem(R.id.action_flag_seven).title = Flag.PURPLE.displayName()
     }
 
     private fun setBackSideOnlyButtonIcon(menu: Menu, isBackSideOnly: Boolean) {
Index: AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt b/AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt	(revision 9fb827d72dcbb33cfc10761fbed02216a09f0181)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt	(date 1715982602616)
@@ -18,19 +18,31 @@
 import androidx.annotation.ColorRes
 import androidx.annotation.DrawableRes
 import com.ichi2.anki.CollectionManager.TR
+import com.ichi2.anki.CollectionManager.withCol
 import com.ichi2.libanki.Card
 import com.ichi2.libanki.CardId
 import com.ichi2.libanki.Collection
 
-enum class Flag(val code: Int, @DrawableRes val drawableRes: Int, @ColorRes val browserColorRes: Int?, val displayName: String) {
-    NONE(0, R.drawable.ic_flag_transparent, null, TR.browsingNoFlag()),
-    RED(1, R.drawable.ic_flag_red, R.color.flag_red, TR.actionsFlagRed()),
-    ORANGE(2, R.drawable.ic_flag_orange, R.color.flag_orange, TR.actionsFlagOrange()),
-    GREEN(3, R.drawable.ic_flag_green, R.color.flag_green, TR.actionsFlagGreen()),
-    BLUE(4, R.drawable.ic_flag_blue, R.color.flag_blue, TR.actionsFlagBlue()),
-    PINK(5, R.drawable.ic_flag_pink, R.color.flag_pink, TR.actionsFlagPink()),
-    TURQUOISE(6, R.drawable.ic_flag_turquoise, R.color.flag_turquoise, TR.actionsFlagTurquoise()),
-    PURPLE(7, R.drawable.ic_flag_purple, R.color.flag_purple, TR.actionsFlagPurple());
+enum class Flag(val code: Int, @DrawableRes val drawableRes: Int, @ColorRes val browserColorRes: Int?) {
+    NONE(0, R.drawable.ic_flag_transparent, null),
+    RED(1, R.drawable.ic_flag_red, R.color.flag_red),
+    ORANGE(2, R.drawable.ic_flag_orange, R.color.flag_orange),
+    GREEN(3, R.drawable.ic_flag_green, R.color.flag_green),
+    BLUE(4, R.drawable.ic_flag_blue, R.color.flag_blue),
+    PINK(5, R.drawable.ic_flag_pink, R.color.flag_pink),
+    TURQUOISE(6, R.drawable.ic_flag_turquoise, R.color.flag_turquoise),
+    PURPLE(7, R.drawable.ic_flag_purple, R.color.flag_purple);
+
+    fun displayName() : String = when (this) {
+        NONE -> TR.browsingNoFlag()
+        RED -> TR.actionsFlagRed()
+        ORANGE -> TR.actionsFlagOrange()
+        GREEN -> TR.actionsFlagGreen()
+        BLUE -> TR.actionsFlagBlue()
+        PINK -> TR.actionsFlagPink()
+        TURQUOISE -> TR.actionsFlagTurquoise()
+        PURPLE -> TR.actionsFlagPurple()
+    }
 
     companion object {
         fun fromCode(code: Int): Flag {
Index: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt	(revision 9fb827d72dcbb33cfc10761fbed02216a09f0181)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt	(date 1715982065104)
@@ -822,25 +822,25 @@
     }
 
     private fun setFlagTitles(menu: Menu) {
-        menu.findItem(R.id.action_select_flag_zero).title = Flag.NONE.displayName
-        menu.findItem(R.id.action_select_flag_one).title = Flag.RED.displayName
-        menu.findItem(R.id.action_select_flag_two).title = Flag.ORANGE.displayName
-        menu.findItem(R.id.action_select_flag_three).title = Flag.GREEN.displayName
-        menu.findItem(R.id.action_select_flag_four).title = Flag.BLUE.displayName
-        menu.findItem(R.id.action_select_flag_five).title = Flag.PINK.displayName
-        menu.findItem(R.id.action_select_flag_six).title = Flag.TURQUOISE.displayName
-        menu.findItem(R.id.action_select_flag_seven).title = Flag.PURPLE.displayName
+        menu.findItem(R.id.action_select_flag_zero).title = Flag.NONE.displayName()
+   [...]

2024-05-17 23:05 UTC, criticalAY commented
CI is happy now

2024-05-17 23:05 UTC, criticalAY approved these changes

2024-05-17 23:18 UTC, david-allison approved these changes
Cheers!

2024-05-19 07:58 UTC, lukstbit approved these changes
Thanks!

2024-05-19 07:59 UTC, lukstbit commented
Going in after #16427(with which I'm almost done)

2024-05-19 11:10 UTC, merged