Refactored DatabaseErrorDialog to MaterialAlertDialog
ankidroid/Anki-Android pull request #16259
Opened 2024-04-23 16:20 UTC by neeldoshii

## Fixes
* Related https://github.com/ankidroid/Anki-Android/issues/13315

## Screenshots

<img src = "https://github.com/ankidroid/Anki-Android/assets/60827173/7f70ba80-671b-40c4-a32a-56a83173232a" width =50% height = 50%>

<br>

<img src = "https://github.com/ankidroid/Anki-Android/assets/60827173/766c0c56-4a67-4912-8dc0-290470eb0814" width =50% height = 50%>

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-04-23 16:21 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> -        dialog.cancelable(true)
is this okay to remove I felt this is redundant.

2024-04-23 16:22 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> -    @Suppress("Deprecation") // Material dialog neutral button deprecation
Successful Merge of this PR will close #11780

2024-04-23 16:24 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +                // AlertDialog does not allow message and listItems
Not sure in materialAlertDialog also over here `listItem` & `message` is not working.

2024-04-23 16:24 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> -    private val title: String
title is now unused.

2024-04-24 18:39 UTC, neeldoshii commented
@david-allison Should I create a new PR for this commit 057ea62f5ce3a93f78044000d12a98de9f653300 as this is functional change in refactor PR as well its blocking #16266

2024-04-28 00:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> -    @Suppress("Deprecation") // Material dialog neutral button deprecation
Added to description

2024-04-28 00:52 UTC, david-allison requested changes
Could you post before & after screenshots, `INCOMPATIBLE_DB_VERSION` looks wrong.

I feel the styling may be a little worse in the new version

2024-04-28 00:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> -        dialog.cancelable(true)
why? `DIALOG_ERROR_HANDLING`, `DIALOG_REPAIR_COLLECTION` etc... seems to need it

2024-04-28 00:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +                    title(R.string.incompatible_database_version_title)
This looks wrong

2024-04-28 00:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +                    title(R.string.directory_inaccessible_after_uninstall)
why is `message` no longer being set?

2024-04-28 00:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +                    alertDialog.title(R.string.backup_restore_select_title)
keep it as `dialog` to reduce lines in the diff

2024-04-28 00:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
> +fun AlertDialog.Builder.listItemsAndMessage(@StringRes messageResId: String?, items: List<CharSequence>, onClick: (dialog: DialogInterface, index: Int) -> Unit): AlertDialog.Builder {
A `string` isn't a `StringRes` or a `resId`, it's

`message: String?`

2024-04-28 00:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> -    private val title: String
I'd have preferred to keep a minimal diff

2024-04-28 00:52 UTC, david-allison commented on AnkiDroid/src/main/res/layout/dialog_listview_message.xml
> +    <TextView
`FixedTextView`

2024-04-29 03:10 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> -    private val title: String
Wont this cause lint test failing?  'variable unused'

2024-05-02 14:59 UTC, neeldoshii commented
I am on break due to university exams, drafting this PR till then. Will open it for review once the `requested changes` are refactored for review

2024-05-02 21:26 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> -        dialog.cancelable(true)
fixed.

2024-05-02 21:27 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +                    title(R.string.directory_inaccessible_after_uninstall)
Thanks for the catch. fixed it.

2024-05-02 21:27 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> -    private val title: String
done.

2024-05-02 21:27 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
> +fun AlertDialog.Builder.listItemsAndMessage(@StringRes messageResId: String?, items: List<CharSequence>, onClick: (dialog: DialogInterface, index: Int) -> Unit): AlertDialog.Builder {
fixed.

2024-05-02 22:34 UTC, neeldoshii commented
Screenshots of `INCOMPATIBLE_DB_VERSION`. Note : Ignore Before's background dim its emulator issue.

I feel the styling may be a little worse in the new version
| Before | After |
|--------|--------|
| ![screenshot](https://github.com/ankidroid/Anki-Android/assets/60827173/111472b7-9a08-4659-9414-8e328f0e5913) | ![screenshot](https://github.com/ankidroid/Anki-Android/assets/60827173/b5868055-9bf9-4cb9-a932-64ba5e218010) |

2024-05-02 22:37 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +                    alertDialog.title(R.string.backup_restore_select_title)
I don't think its possible we are already using `alertdialog` variable for alertdialogs. Introduced in #15396

2024-05-02 22:39 UTC, neeldoshii commented
@david-allison Is this because of my fast commits pushed?

```
  Received 1440578237 of 1440578237 (100.0%), 85.6 MBs/sec
  Cache restored successfully
  Restored groovy-dsl with key gradle-groovy-dsl-v1-b6176636e15c884e52aa481f4216903e to C:\Users\runneradmin\.gradle\caches\*\groovy-dsl\*/
  Error: The action 'Setup Gradle' has timed out after 5 minutes.
  ```

2024-05-02 22:41 UTC, david-allison commented
Don't worry about CI, we're having issues

2024-05-02 22:42 UTC, david-allison commented
My request would be to have side-by-side images for each screen.

A few of them look unusual, and I want to confirm visually there's no regressions.

Once we have a list of 'before' screenshots, they won't need to change

2024-05-03 01:43 UTC, david-allison reviewed
The "incompatible DB version" in "Before" looks incorrect

From the code on `main`, it looks like it should be using `incompatible_database_version_summary`, can you confirm why this isn't the case?

2024-05-03 12:22 UTC, neeldoshii commented
Updated all the screenshots in the PR description for review.


> The "incompatible DB version" in "Before" looks incorrect
> 
> From the code on main, it looks like it should be using incompatible_database_version_title & incompatible_database_version_summary, can you confirm why this isn't the case?

Its because I did  manual trigger for testing at `DIALOG_CONFIRM_DATABASE_CHECK` so its taking its corresponding title & message rather than `incompatible_database_version_title` & `incompatible_database_version_summary`.
```
            DIALOG_CONFIRM_DATABASE_CHECK -> {
                // Confirmation dialog for database check
                alertDialog.show {
                    title(R.string.check_db_title)
                    message(text = message)
                    positiveButton(R.string.dialog_ok) {
                        (activity as DeckPicker).integrityCheck()
                        dismissAllDialogFragments()
                    }
                    negativeButton(R.string.dialog_cancel)
                }
            }
```

2024-05-03 15:34 UTC, david-allison commented
Neither the before nor the 'after' screenshots seem correct, can we do better here?

2024-05-04 09:45 UTC, neeldoshii commented
updated the screenshots for review ;)

2024-05-16 00:02 UTC, david-allison approved these changes
Looks great, thanks!

2024-05-16 00:02 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +                        .setSingleChoiceItems(dates.toTypedArray(), -1) { _, index: Int ->
From the docs:
`If -1 no items are checked.`

2024-05-16 12:58 UTC, BrayanDSO approved these changes
LGTM. Thanks

2024-05-16 13:14 UTC, merged