fix: handle backend-col already open to fix CI failure
ankidroid/Anki-Android pull request #16264
Opened 2024-04-24 05:57 UTC by criticalAY

## Purpose / Description
CI fails giving col already open 

## How Has This Been Tested?
Needs testing on CI

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-04-25 08:13 UTC, lukstbit approved these changes
Seeing as this actually works, ok from me.

2024-04-25 09:27 UTC, criticalAY commented
All the force push are test that passed everytime, so I think it fixes the issue /hopefully/

2024-04-25 09:46 UTC, david-allison commented
I'll rerun a few times, then let's get this in tonight

2024-04-25 13:43 UTC, lukstbit commented
And it failed...

2024-04-25 13:55 UTC, david-allison commented
My suspicion: see if you can make https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid%2Fsrc%2Ftest%2Fjava%2Fcom%2Fichi2%2Fanki%2FWhiteboardDefaultForegroundColorTest.kt

Line 37 into a "runTest"

2024-04-25 14:59 UTC, david-allison commented
I'd rather not delete the test and use a `runTest` instead (or an ignore at worst)

2024-04-25 15:12 UTC, mikehardy commented
Not a fan of "hey a test isn't working let's just delete the test" style

2024-04-25 16:01 UTC, mikehardy requested changes
we can narrow the skip to just one OS such that the coverage is still maintained at least on others for basic functionality verification, I think

2024-04-25 16:01 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/WhiteboardDefaultForegroundColorTest.kt
> +    @Ignore("workflow failure on windows, see #16253")
```suggestion
    @Flaky(os = OS.WINDOWS, "workflow failure on windows, see #16253")
```

2024-04-25 16:01 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/WhiteboardDefaultForegroundColorTest.kt
> +import org.junit.Ignore
```suggestion
```

2024-04-25 16:01 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/WhiteboardDefaultForegroundColorTest.kt
>  import org.hamcrest.MatcherAssert.assertThat
```suggestion
import org.hamcrest.MatcherAssert.assertThat
import com.ichi2.testutils.Flaky
import com.ichi2.testutils.OS
```

2024-04-25 16:13 UTC, lukstbit reviewed
Forgot about @ Flaky , changes done.

2024-04-25 16:25 UTC, mikehardy approved these changes
These changes look magnificent, a thing of beauty
and my opinion has nothing to do with the fact I created them

more seriously, thanks for handling this with the quick force-pushes etc @lukstbit  :)

2024-04-25 17:44 UTC, mikehardy commented
Hmm - still failed on windows after marking that one flaky, but we don't have the build logs from the failure yet (#16255 is in queue not merged yet...) so I want to keep this open for a moment, rebase it on top of that PR post-merge then kick it again, we need a more general windows flaky fix

2024-04-25 19:15 UTC, mikehardy commented
I have committed a non-merge-able change to the unit test YAML that runs it on windows only, 10 iterations

Since the required ubuntu and macos checks won't run, this will never meet merge status checks, but we should see windows unit test failures (and associated logs to use to fix this problem...) every single time we try.

2024-04-25 20:11 UTC, criticalAY commented
I tried placing it in `launchCatching{}` block but it failed after few hits

2024-04-25 22:13 UTC, mikehardy commented
Current state of this one is that I've reverted all the minor changes attempting to work around this:

- marking one test Flaky on windows was not sufficient, anything touching the reviewer right now is potentially flaky
- wrapping all tests that touch the Reviewer in `= runTest` is not okay because the GestureDetector that is created during AbstractFlashcardReviewer (superclass of Reviewer...) for whiteboard stuff requires a non-null return from `Looper.myLooper` and that is not the case in our test dispatcher

All of these things, including getting the "backend already open" exception to throw as an Error if executing in a Robolectric context, and perhaps the *actual* root problem of non-serialized  backend-open behavior on Windows can be solved, but not quickly

So this is in prep to revert.

Expectations:
- the push I just made with no remediation at all and 20 iterations on windows should trigger at least one failure, giving me confidence that I can actually reproduce the problem
- the revert of #16218 that I will push after that should succeed, giving me confidence that it is going to work reasonably well

If those expectations are met then I will make a clean revert PR

2024-04-26 03:59 UTC, mikehardy commented
I just pushed the revert commit here before bed - prior to the revert we had 1-out-of-10 failures, then a 7-out-of-20 failure rate. So if it is 100% passing on windows unit tests I'd say that's pretty good. I would still prefer to see a couple batches-of-20 go through green if possible, by re-running if possible

But in general if anyone sees this in the next 12 hours or so and I'm not obviously active in here I won't mind a single bit if you just take charge and start noting results + re-running it and then ideally merging. Cheers

2024-04-26 05:48 UTC, criticalAY commented
The revert commit was just the log one

2024-04-26 09:34 UTC, lukstbit commented
With the full revert there were no workflow failure. I've started another run.

2024-04-26 09:37 UTC, criticalAY commented
From discord:
 Revert fixed the issue but would like to know if we can pass `col` as param to `getName`? This would solve the issue of multiple backend opening attempts but in this the question would be how to get col in the activity or the place from where we are going to call it

2024-04-26 12:48 UTC, merged