Implement 'Hold to Record' Functionality
ankidroid/Anki-Android pull request #16293
Opened 2024-04-29 04:35 UTC by Giyutomioka-SS

## Purpose / Description
This PR implements the "hold to record" functionality for the Pronunciation Check feature, as proposed in issue #16282. 
The following requirements are met:
Recording starts as soon as the button is pressed, rather than after a long press.
If ACTION_UP is received after the long-press time, it's considered a long-press, and the recording is completed.
If ACTION_UP is received before the long-press time, the recording is paused until the button is pressed again.

## Fixes
* Fixes #16282 

## How Has This Been Tested?

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-04-29 07:40 UTC, david-allison requested changes
I won't review the code as it's a draft

2024-04-29 07:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
> + *  Copyright (c) 2024 David Allison <sumitsinghkoranga7@gmail.com>
Either put both copyrights if you feel my contributions are nontrivial, or remove it and replace it with yours

2024-04-29 18:24 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
> +fun View.setOnHoldListener(listener: OnHoldListener) {
Does this start recording on `ACTION_DOWN`? It still appears to use onlongclick

2024-04-29 18:24 UTC, david-allison requested changes
Meant for this to be "request changes"

2024-05-14 10:07 UTC, david-allison requested changes

2024-05-14 10:07 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
> +    fun onHoldStart(): Boolean
I don't think `onHoldStart` is necessary:

We want:

* `onTouchStart` - the touch event is detected (`ACTION_DOWN`)
  * Start recording
* `onHoldEnd`  - the touch event ended and it was a long-press
  * Stop recording - this was the end of the long press 

I believe this would also significantly simplify the implementation of the class

* remove `isHolding` and ``isLongPress`
* remove `MotionEvent.ACTION_UP` 
* etc...

----

If there are reasons that this can't be done, then they should be code comments.

This is currently only used for `AudioRecordingController`, keep the complexity out of the class until it's required

2024-05-18 01:24 UTC, Giyutomioka-SS commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
> +    fun onHoldStart(): Boolean
```suggestion
    fun onHoldStart(): Booleaninterface OnHoldListener {
    fun onTouchStart(): Boolean
    fun onHoldEnd()
}

fun View.setOnHoldListener(listener: OnHoldListener) {
    val listenerWrapper = object : View.OnTouchListener, View.OnLongClickListener {

        override fun onTouch(v: View?, event: MotionEvent?): Boolean {
            if (event?.action == MotionEvent.ACTION_DOWN) {
                (listener.onTouchStart())
            }
            return false
        }

        override fun onLongClick(v: View?): Boolean {
            return true
        }
    }
    this.setOnLongClickListener(listenerWrapper)
    this.setOnTouchListener(listenerWrapper)
}
```

2024-05-18 01:25 UTC, Giyutomioka-SS commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
> +    fun onHoldStart(): Boolean
interface OnHoldListener {
    fun onTouchStart(): Boolean
    fun onHoldEnd()
}

fun View.setOnHoldListener(listener: OnHoldListener) {
    val listenerWrapper = object : View.OnTouchListener, View.OnLongClickListener {

        override fun onTouch(v: View?, event: MotionEvent?): Boolean {
            if (event?.action == MotionEvent.ACTION_DOWN) {
                (listener.onTouchStart())
            }
            return false
        }

        override fun onLongClick(v: View?): Boolean {
            return true
        }
    }
    this.setOnLongClickListener(listenerWrapper)
    this.setOnTouchListener(listenerWrapper)
}

2024-05-18 01:34 UTC, Giyutomioka-SS commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
> +    fun onHoldStart(): Boolean
```
interface OnHoldListener {
    fun onTouchStart(): Boolean
    fun onHoldEnd()
}

fun View.setOnHoldListener(listener: OnHoldListener) {
    val listenerWrapper = object : View.OnTouchListener, View.OnLongClickListener {

        override fun onTouch(v: View?, event: MotionEvent?): Boolean {
            if (event?.action == MotionEvent.ACTION_DOWN) {
                (listener.onTouchStart())
            }
            return false
        }

        override fun onLongClick(v: View?): Boolean {
            return true
        }
    }
    this.setOnLongClickListener(listenerWrapper)
    this.setOnTouchListener(listenerWrapper)
}
```

In this code, when I attempt to implement onHoldEnd to stop recording after a long press, it's not functioning as expected. I need some assistance  on what could be done 🥲

2024-05-18 23:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
> +    fun onHoldStart(): Boolean
Ping me when you see this message, I'll see if I can take a look in the morning

2024-05-19 02:51 UTC, Giyutomioka-SS commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
> +    fun onHoldStart(): Boolean
@david-allison

2024-05-19 13:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
> +    fun onHoldStart(): Boolean
```patch
Subject: [PATCH] feat: Toggle Bury

Issue 14163
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt b/AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt	(revision c29af600d8e72b9372ff4c39c9495876dea8d045)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt	(date 1716123721211)
@@ -20,41 +20,32 @@
 import android.view.View
 
 interface OnHoldListener {
-    fun onHoldStart(): Boolean
-    fun onHoldEnd(isLongPress: Boolean)
-    fun onHoldActionDown(): Boolean
+    fun onTouchStart()
+    fun onHoldEnd()
 }
 
 fun View.setOnHoldListener(listener: OnHoldListener) {
     val listenerWrapper = object : View.OnTouchListener, View.OnLongClickListener {
 
-        var isHolding = false
-        var isLongPress = false
-
+        var isHolding: Boolean = false
         override fun onTouch(v: View?, event: MotionEvent?): Boolean {
             when (event?.action) {
-                MotionEvent.ACTION_DOWN -> {
-                    isLongPress = false
-                    if (listener.onHoldActionDown()) {
-                        isHolding = true
-                    }
-                }
+                MotionEvent.ACTION_DOWN -> { listener.onTouchStart() }
                 MotionEvent.ACTION_UP -> {
                     if (isHolding) {
-                        isHolding = false
-                        listener.onHoldEnd(isLongPress)
-                        return true
-                    }
+                        listener.onHoldEnd()
+                    }
+                    isHolding = false
                 }
             }
+
             return false
         }
 
         override fun onLongClick(v: View?): Boolean {
-            isLongPress = true
-            if (listener.onHoldStart()) {
-                isHolding = true
-            }
+            // this method is called once the threshold for a long press is reached
+            // not when the long press is released
+            isHolding = true
             return true
         }
     }
Index: AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt b/AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
--- a/AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt	(revision c29af600d8e72b9372ff4c39c9495876dea8d045)
+++ b/AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt	(date 1716123453771)
@@ -197,34 +197,21 @@
         // holding the 'record' button should start a recording
         // releasing the 'record' button should complete the recording
         recordButton.setOnHoldListener(object : OnHoldListener {
-            override fun onHoldStart(): Boolean {
-                if (state != ImmediatePlayback.CLEARED && state != AppendToRecording.CLEARED) return false
+            override fun onTouchStart() {
+                if (state != ImmediatePlayback.CLEARED && state != AppendToRecording.CLEARED) return
                 Timber.d("holding 'record' button'")
                 controlAudioRecorder()
-                return true
             }
 
-            override fun onHoldEnd(isLongPress: Boolean) {
+            override fun onHoldEnd() {
                 Timber.d("finished holding 'record' button'")
-                if (isLongPress) {
-                    // Logic for handling the long press end
-                    if (state is ImmediatePlayback) {
-                        controlAudioRecorder()
-                    } else {
-                        saveButton?.performClick()
-                    }
-                } else {
-                    // Logic for handling the short press end (do nothing)
-                    Timber.d("short press ended, waiting for further action")
+                // Logic for handling the long press end
+                if (state is ImmediatePlayback) {
+                    controlAudioRecorder()
+                } else {
+                    saveButton?.performClick()
                 }
             }
-            override fun onHoldActionDown(): Boolean {
-                // Start recording immediately on ACTION_DOWN
-                if (state != ImmediatePlayback.CLEARED && state != AppendToRecording.CLEARED) return false
-                Timber.d("press 'record' button'")
-                controlAudioRecorder()
-                return true
-            }
         })
 
         playAudioButton.setOnClickListener {

```

2024-05-19 13:52 UTC, Giyutomioka-SS commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
> +    fun onHoldStart(): Boolean
Thanks for helping. I guess you suggested removing ‘is holding,’ which is why I tried to implement it that way. 🥲

2024-05-19 14:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
> +    fun onHoldStart(): Boolean
You're closest to the implementation, if a suggestion won't work, it won't work

2024-05-19 15:02 UTC, Giyutomioka-SS commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
> +    fun onHoldStart(): Boolean
Got it, thanks ♥️

2024-05-19 15:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
> +    fun onHoldStart(): Boolean
Ready to go after my patch is merged

2024-05-19 16:31 UTC, Giyutomioka-SS commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
> +    fun onHoldStart(): Boolean
@david-allison  The On-hold recording function is working correctly, but when the user merely taps the record button, it shows "Recording failed.

https://github.com/ankidroid/Anki-Android/assets/91668590/f5b3a1ce-b3fa-4512-8ab1-a80c39ae58a4

2024-05-19 16:33 UTC, david-allison approved these changes
~~if tested, LGTM~~

2024-05-19 16:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
> +    fun onHoldStart(): Boolean
That needs fixing

2024-05-19 16:36 UTC, david-allison requested changes
If the PR isn't ready to be reviewed, please mark it as a draft

2024-05-19 16:41 UTC, Giyutomioka-SS commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
> +    fun onHoldStart(): Boolean
On it

2024-05-23 15:07 UTC, david-allison requested changes
The interface isn't the code which was provided.

The issue with my previously provided code was that the following still existed:

```kotlin
        recordButton.setOnClickListener {
            Timber.i("primary 'record' button clicked")
            controlAudioRecorder()
        }
```

```patch

---
Subject: [PATCH] tests: fix for Kotlin 2.0
---
Index: AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt b/AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
--- a/AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt	(revision 4c54277b27bf1f4045a2f8481708c0856b35a2c3)
+++ b/AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt	(date 1716476623592)
@@ -188,29 +188,20 @@
         setUpMediaPlayer()
 
         audioTimer = AudioTimer(this, this)
-        recordButton.setOnClickListener {
-            Timber.i("primary 'record' button clicked")
-            controlAudioRecorder()
-        }
 
         // if the recorder is in the 'cleared' state
         // holding the 'record' button should start a recording
         // releasing the 'record' button should complete the recording
+        // TODO: remove haptics from the long press - the 'buzz' can be heard on the recording
         recordButton.setOnHoldListener(object : OnHoldListener {
-            override fun onTouchStart(isLongPress: Boolean): Boolean {
-                if (state !in listOf(ImmediatePlayback.CLEARED, AppendToRecording.CLEARED)) return false
-                Timber.d("holding 'record' button'")
+            override fun onTouchStart() {
+                Timber.d("pressed 'record' button'")
                 controlAudioRecorder()
-                return true
             }
 
-            override fun onHoldEnd(isLongPress: Boolean) {
+            override fun onHoldEnd() {
                 Timber.d("finished holding 'record' button'")
-                if (isLongPress && state is ImmediatePlayback) {
-                    controlAudioRecorder()
-                } else {
-                    saveButton?.performClick()
-                }
+                controlAudioRecorder()
             }
         })
 
Index: AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt b/AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt	(revision 4c54277b27bf1f4045a2f8481708c0856b35a2c3)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt	(date 1716476693346)
@@ -18,42 +18,40 @@
 
 import android.view.MotionEvent
 import android.view.View
+import timber.log.Timber
 
 interface OnHoldListener {
-    fun onTouchStart(isLongPress: Boolean): Boolean
-    fun onHoldEnd(isLongPress: Boolean)
+    fun onTouchStart()
+    fun onHoldEnd()
 }
 
 fun View.setOnHoldListener(listener: OnHoldListener) {
     val listenerWrapper = object : View.OnTouchListener, View.OnLongClickListener {
-
         var isHolding = false
-        var isLongPress = false
 
         override fun onTouch(v: View?, event: MotionEvent?): Boolean {
             when (event?.action) {
                 MotionEvent.ACTION_DOWN -> {
-                    isLongPress = false
-                    if (listener.onTouchStart(isLongPress)) {
-                        isHolding = true
-                    }
+                    Timber.v("ACTION_DOWN: onTouchStart()")
+                    listener.onTouchStart()
                 }
                 MotionEvent.ACTION_UP -> {
+                    Timber.v("ACTION_UP")
                     if (isHolding) {
-                        isHolding = false
-                        listener.onHoldEnd(isLongPress)
-                        return true
-                    }
+                        Timber.v("onHoldEnd()")
+                        listener.onHoldEnd()
+                    }
+                    isHolding = false
                 }
             }
             return false
         }
 
         override fun onLongClick(v: View?): Boolean {
-            isLongPress = true
-            if (listener.onTouchStart(isLongPress)) {
-                isHolding = true
-            }
+            Timber.v("onLongClick")
+            // this method is called once the threshold for a long press is reached
+            // not when the long press is released
+            isHolding = true
             return true
         }
     }

```

2024-05-23 15:22 UTC, david-allison reviewed
One last patch + test I feel, you got my patch before I edited it

2024-05-23 15:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> +            }
This one's on me - messed up in the proposed patch, could you test, then this is good to go

```suggestion
             override fun onHoldEnd() {
                 Timber.d("finished holding 'record' button'")
                 if (state is ImmediatePlayback) {
                     controlAudioRecorder()
                 } else {
                     // if we're recording audio to add permanently, 
                     // releasing the button after a long press should be 'save', not 'pause'
                     saveButton?.performClick()
                 }
             }
```

2024-05-23 15:37 UTC, david-allison approved these changes
Lots of my code, so needs a thorough second review 

Cheers!

2024-06-10 14:32 UTC, mikehardy requested changes
As a state machine scenario:

- If a user taps the record button does not reach the long-click threshold then;
- listener recognizes ACTION_DOWN and calls onTouchStart, isHolding = false
- controlAudioRecorder() is called so recording starts?
- listener does not recognize long-click, instead recognizes ACTION_UP
- isHolding = false so listener.onHoldEnd is not called
- audio record is left recording, never stops?

My analysis could be wrong, if so please explain and I'll happily approve but if my analysis is correct then I believe an ACTION_UP in isHolding = false state needs handling somehow, perhaps an onTouchStop on the listener that is only called if long-click didn't happen, and in AudioRecordingController that is handled with a controlAudioRecorder call ?

2024-06-10 14:42 UTC, david-allison commented
If the button is tapped, then the functionality is unchanged: 

* Start the recording on tap
* A user needs to tap the main button again to change state (now "stop/pause recording")

2024-06-10 14:50 UTC, david-allison commented
Proposal (if the above is insufficient): add an `onTapEnd()` function which we define as a no-op and explain

2024-06-10 17:14 UTC, mikehardy approved these changes
Ah - I see - the expected close-out on the state machine in the tap but not long-tap case is for a user tap to stop it. That makes sense and satisfies my curiosity about backwards-compatibility for this feature at the same time

Works for me then, nice!

2024-06-10 17:29 UTC, merged