chore: update a part of libanki
ankidroid/Anki-Android pull request #16317
Opened 2024-05-01 23:38 UTC by BrayanDSO

## Purpose / Description

I just looked into a method and started updating it like a robot. When the spell was gone, I stopped it.

## How Has This Been Tested?

I haven't

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-05-02 09:28 UTC, david-allison requested changes
Wanted to do this myself, thanks!

Could you add `@CheckResult` to relevant functions, especially ones returning `opChanges`

2024-05-02 09:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
> +    fun deckAndChildNameIds(deckId: DeckId): List<Pair<String, Long>> {
this matches upstream: `Iterable[tuple[str, DeckId]]:`

I'd prefer to use `DeckNameId` here. Implementer's choice

2024-05-02 09:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
> +    /** All existing parents of name */
`[name]`

2024-05-02 09:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
> +        }
Reviewer 2- compare to https://github.com/ankitects/anki/blob/4fc535ec8810c77838d49252ed83921ff99301a6/pylib/anki/decks.py#L503-L517 as the code differs

2024-05-02 09:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
> +    fun parentsByName(name: String): List<Deck> {
`@NeedsTest` as the code differs slightly

2024-05-02 22:32 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
> +    fun deckAndChildNameIds(deckId: DeckId): List<Pair<String, Long>> {
I read `DeckNameId` and get more confused, so I'll just rename Long to DeckId

2024-05-03 00:26 UTC, david-allison approved these changes
The commit comments were AWESOME, thank you for that

2024-05-11 17:49 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
> +        }
It's different but the logic is the same in my opinion.

2024-05-11 17:50 UTC, lukstbit approved these changes
Great!

2024-05-11 18:45 UTC, merged