Added ContentDescription for check pronunciation
ankidroid/Anki-Android pull request #16332
Opened 2024-05-02 18:12 UTC by Aditya13s

## Purpose / Description
The purpose of this pr is to add content descripton for record button which help partially sighted users.

## Fixes
* Fixes #16320

## Approach
Approach is to add `android:contentDescription`  in both the xmls

## How Has This Been Tested?
Tested the app using google talkback

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-05-02 18:19 UTC, david-allison requested changes
This button does different things depending on the state of the UI.

Use more concise strings

2024-05-02 20:54 UTC, david-allison requested changes

2024-05-02 20:54 UTC, david-allison commented on AnkiDroid/src/main/res/values/11-arrays.xml
> +    <string name="start_recording">Start Recording Voice</string>
Use more concise strings: "Record"

2024-05-02 21:19 UTC, Aditya13s commented on AnkiDroid/src/main/res/values/11-arrays.xml
> +    <string name="start_recording">Start Recording Voice</string>
Do i need to change only this or also the others?

2024-05-03 02:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> -                    setIconResource(R.drawable.ic_record)
Why was this removed?

2024-05-03 02:48 UTC, david-allison commented on AnkiDroid/src/main/res/values/11-arrays.xml
> +    <string name="start_recording">Start Recording Voice</string>
Don't make people listen to anything more then necessary. All the descriptions should be concise

2024-05-03 06:57 UTC, Aditya13s commented on AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
> -                    setIconResource(R.drawable.ic_record)
removed by mistake but now added it again

2024-05-04 12:33 UTC, Aditya13s commented
@david-allison please check the new changes

2024-05-06 16:41 UTC, david-allison approved these changes
Looks good, one small request!

2024-05-06 16:53 UTC, Aditya13s commented on AnkiDroid/src/main/res/values/11-arrays.xml
> +    <string name="next_recording">Next</string>
> These shouldn't be in `arrays`

so where should i have to add?

2024-05-06 16:57 UTC, david-allison commented on AnkiDroid/src/main/res/values/11-arrays.xml
> +    <string name="next_recording">Next</string>
`strings` for now

We may later want to have non-visible strings in a separate file, but that would implicitly reduce the priority of accessibility-related strings

2024-05-06 17:38 UTC, Aditya13s commented
@david-allison successfully squashed the commits

2024-05-11 18:47 UTC, lukstbit approved these changes
Thanks for the changes, thanks for squashing!

2024-05-11 22:33 UTC, david-allison commented
* https://github.com/ankidroid/Anki-Android/pull/16376

2024-05-11 22:48 UTC, merged