fix sync tooltip text
ankidroid/Anki-Android pull request #16344
Opened 2024-05-03 09:50 UTC by RobozinhoD

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
* Fixes #16343

## Approach
set the tooltip programatically

## How Has This Been Tested?

I long pressed the icon to see if the tooltip is shown

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-05-03 15:47 UTC, david-allison requested changes
LGTM. One request

2024-05-03 15:47 UTC, david-allison commented on AnkiDroid/src/main/res/layout/sync_progress_layout.xml
> +        android:tooltipText="@string/button_sync"
Probably best for no default and instead use `tools:`, the default is different between new users and logged in users

2024-05-03 22:04 UTC, RobozinhoD commented on AnkiDroid/src/main/res/layout/sync_progress_layout.xml
> +        android:tooltipText="@string/button_sync"
But that way people with Android < O won't have any tooltip

2024-05-04 16:23 UTC, BrayanDSO approved these changes
Works for me. Thanks

2024-05-05 02:14 UTC, david-allison approved these changes

2024-05-05 02:29 UTC, merged