Highlight selected preference setting
ankidroid/Anki-Android pull request #16368
Opened 2024-05-10 07:10 UTC by SanjaySargam

## Purpose / Description
In tablet mode, the selected settings preference category is not highlighted. It would be better if we highlight the preference to have better user experience.

## Approach
Highlight GeneralSettings preference as default
use onPreferenceTreeClick function and remove highlight from previously selected preference and highlight the current preference

## How Has This Been Tested?
Emulator

https://github.com/ankidroid/Anki-Android/assets/65113071/5a73461b-b068-4cd4-acae-bb3c4949a2bc

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-05-10 12:25 UTC, BrayanDSO reviewed
Haven't tested, but I think that this doesn't handle configuration changes (e.g. toggling night mode)

2024-05-10 12:53 UTC, SanjaySargam commented
@BrayanDSO handling

2024-05-10 17:16 UTC, SanjaySargam commented
It handles, I consider highlighting in night mode too

2024-05-10 20:34 UTC, BrayanDSO commented
Tested it myself, and it doesn't.

1. Use a tablet/large screen device
2. Open settings
3. Choose a section other than `General`
4. Toggle system's night mode

Result: `General is highlighted` instead of the active preference

2024-05-11 04:09 UTC, SanjaySargam commented
Now I understood what you said. Sorry I didn't test this. I'll make changes accordingly.

> Also, please avoid deleting your own comments. Editing is a more healthy choice for discussions


Ok will take care of this from next time

2024-05-13 17:23 UTC, lukstbit requested changes
The current code has two issues:

- on phones(where the majority of our users are) the highlight shouldn't appear as it looks weird. You could fix this by making the Preferences.hasLateralNavigation() method public and then checking its status in highlightHeaderPreference() and return immediately if false(on phones).
- second issue: tablet on any orientation -> highlight one preference -> rotate the tablet -> highlight is gone

2024-05-13 17:23 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
> +            highlightHeaderPreference(this)
Small nitpick but using _apply {}_ looks verbose as you could write this in one line:

`highlightHeaderPreference(requirePreference<HeaderPreference>(selectedHeaderPreferenceKey))`

2024-05-16 08:41 UTC, SanjaySargam commented
> on phones(where the majority of our users are) the highlight shouldn't appear as it looks weird. You could fix this by making the Preferences.hasLateralNavigation() method public and then checking its status in highlightHeaderPreference() and return immediately if false(on phones).

hasLateralNavigation function is not included in companion object so we can't access even if we make it public

2024-05-17 15:41 UTC, lukstbit approved these changes
LGTM if it includes the change below.

2024-05-17 15:41 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
> +    private fun hasLateralNavigation(): Boolean {
> hasLateralNavigation function is not included in companion object so we can't access even if we make it public

It's not in the companion but can be accessed from the activity object. HeaderFragment is a fragment so it has access to the activity to call the method:

`if (!(activity as Preferences).hasLateralNavigation()) `

This is better as we avoid duplication and a possible bug where the check is changed in the activity but not the fragment.

2024-05-19 06:25 UTC, SanjaySargam commented
Also tested on Chromebook

2024-05-22 17:57 UTC, david-allison requested changes
minor nitpicks, should be good to go next round

2024-05-22 17:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
> +    private var selectedHeaderPreferenceKey: String = KEY_SELECTED_HEADER_PREF
This is confusing: you're using the key as the value

Split the two out

2024-05-22 17:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
> +            selectedHeaderPreferenceKey = savedInstanceState.getString(KEY_SELECTED_HEADER_PREF).toString()
As above, this is confusing.

Use `getString(key, default)`, or `!!` rather than `.toString()` to handle the null case

2024-05-22 17:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
> +        selectedHeaderPreferenceKey = headerPreference.key
```suggestion
        selectedHeaderPreference?.setHighlighted(false)
        // highlight the newly selected header
        selectedHeaderPreference = headerPreference.apply {
            setHighlighted(true)
            selectedHeaderPreferenceKey = this.key
        }
```

I feel this is a little more readable

2024-05-23 15:00 UTC, merged