Fixed Record Audio Waveform not visible #16258
ankidroid/Anki-Android pull request #16372
Opened 2024-05-10 18:22 UTC by shalenMathew

## Purpose / Description
fixing  #16258 the issue where audio wave disappears when orientation changes to landscape

## Fixes
* Fixes #16258 

## Approach

-issue occurred due Audio Waveform being kept GONE when config changed ,
solved the issue 

-audio form is now visible even in landscape mode

- changed the height of audio wave a bit , to suit in both landscape and potrait mode

## How Has This Been Tested?
- tested in emulator 

## Screenshot

https://github.com/ankidroid/Anki-Android/assets/119736953/4de4ae18-0ad7-4873-a996-e3c5110b9e5b

![WhatsApp Image 2024-05-10 at 11 46 27 PM](https://github.com/ankidroid/Anki-Android/assets/119736953/3a28cee9-4507-49f0-8ed1-69bce0d21697)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-05-10 22:39 UTC, BrayanDSO requested changes

2024-05-10 22:39 UTC, BrayanDSO commented on AnkiDroid/src/main/res/layout/activity_audio_recording.xml
> +            android:layout_height="200px"
Could you test that with a height using `dp`? 200px may make sense for phones, but not on tablets

2024-05-11 01:50 UTC, david-allison commented
Thanks!!

There was a reason that the audio waveform was hidden in landscape (I believe due to limited vertical space on phones) 

This doesn't address the issue that the flip from landscape to portrait does not reveal the control

2024-05-11 01:51 UTC, david-allison commented
Forgot to ping, @criticalAY has context for the landscape change hiding the control

2024-05-11 06:59 UTC, criticalAY commented
The audio wave form was kept hidden in landscape as the mobile screen don't have that much of space to accommodate both the waveform and the card content, when a user want to record while seeing the content of their card it is difficult if it's visible in landscape

2024-05-11 08:09 UTC, criticalAY requested changes
Thanks! but this is not the solution instead try fixing the original issue

2024-05-11 11:28 UTC, shalenMathew commented
So whats the fix here ? Should i make any further changes ?

2024-05-11 11:30 UTC, shalenMathew commented
Shall i change px to dp ?

2024-05-11 13:23 UTC, shalenMathew commented
> You will need to fix the behavior mentioned in the issue which is emulator only 

Ok 👌

2024-05-21 14:55 UTC, david-allison commented
@shalenMathew could you mark this as draft if it's not ready for review?

2024-05-23 13:18 UTC, shalenMathew commented
> @shalenMathew could you mark this as draft if it's not ready for review?

I have changed the size of audio waveform to 100dp just notify me if i need to make any more changes

2024-05-23 13:54 UTC, criticalAY commented
This is not what I meant, I will repeat what I said, you need to figure out what is the issue that causes the emulator bug and fix that instead of changing the height

2024-05-24 11:09 UTC, shalenMathew commented
> This is not what I meant, I will repeat what I said, you need to figure out what is the issue that causes the emulator bug and fix that instead of changing the height

ok , i think it not a bug the waveform disappears coz the logic is set up that way , when the  orientation changes the waveform  visiblity is set to gone  , i think due to limited space of screen on landscape mode the logic is set up that way...

I think the logic works as intended ... Maybe its not an issue

2024-05-24 11:41 UTC, david-allison commented
@shalenMathew first, you need to understand the problem: 

* We want the view hidden in landscape mode
* We don't want the view hidden in portrait mode
* If the user switches from portrait to landscape, then from landscape to portrait, the view is invisible in portrait, this is a bug 

----

The first step is to reproduce the problem in an emulator

Then explain what the bug is

Then fix the bug in a pull request

2024-05-24 12:32 UTC, shalenMathew commented
> @shalenMathew first, you need to understand the problem:
> 
> * We want the view hidden in landscape mode
> * We don't want the view hidden in portrait mode
> * If the user switches from portrait to landscape, then from landscape to portrait, the view is invisible in portrait, this is a bug
> 
> The first step is to reproduce the problem in an emulator
> 
> Then explain what the bug is
> 
> Then fix the bug in a pull request

ok now i got it my bad, let me try to fix it

2024-06-19 22:20 UTC, criticalAY commented
I am closing this PR as there are no changes here and i dont see any development recently, so the OP can figure out the right solution and get back.

2024-06-19 22:20 UTC, closed without merging