Added Unit test for Reviewer.kt.
ankidroid/Anki-Android pull request #16391
Opened 2024-05-14 16:13 UTC by Haz3-jolt

## Purpose / Description
Added Unit test to function with @NeedsTest.

## Fixes
* Created test for AddNote() to address "Starting animation from swipe is inverse to the finishing one".

## Approach
- Unit test completed.
## How Has This Been Tested?
- Ran the Unit test multiple times, and ensured it is passing.

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-05-20 19:22 UTC, david-allison requested changes
Thanks! In future, please ping if you feel things are forgotten about

2024-05-20 19:22 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
> +        TestCase.assertEquals(
Remove the `TestCase` prefix:

When we're asserting, we want to focus on the functionality, not the source of the assertion methods

```
        assertEquals(
```

2024-05-20 19:22 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
> +        val shadowApplication = Shadows.shadowOf(ApplicationProvider.getApplicationContext() as Application)
```suggestion
        val shadowApplication = Shadows.shadowOf(ApplicationProvider.getApplicationContext<Application>())
```

2024-05-20 19:59 UTC, Haz3-jolt commented
> Thanks! In future, please ping if you feel things are forgotten about

Forgot about the feature myself lol! No worries at all

2024-05-20 20:01 UTC, david-allison approved these changes
Y'know, none of these are blocking, let's go!

2024-05-20 20:02 UTC, Haz3-jolt commented
> Y'know, none of these are blocking, let's go!

I did make the changes btw

2024-05-21 07:48 UTC, lukstbit approved these changes
Thanks!
A request for future tests: there's no need to add comments with _Arrange/Act/Assert_. These could be useful for someone just starting to read tests but later becomes verbose. Adding an empty line between the logical groups is perfectly fine.

2024-05-21 08:05 UTC, merged