Feature: Instant Note Editor to allow adding cloze card
ankidroid/Anki-Android pull request #16393
Opened 2024-05-14 17:29 UTC by criticalAY

## Purpose / Description
### GSOC
This PR aims to provide basic functionality for the instant note editor i.e. allowing the user to add cloze card without actually opening AnkiDroid application, to achieve this we utilize a transparent activity with custom theme.

* The activity has intent filter to register and receive text when user taps share button after selecting text
*  `Instant card` label used for the activity
* `EditTextGestureHelper` allows user to single tap and turn words to cloze
* User can also long press and select multiple words/text and turn it to cloze
* Deck spinner allows user to change deck
* User can tap in/out manual mode if wanted
* Cloze increment button allows user to increment cloze number

## How Has This Been Tested?
OnePlus Nord CE:

https://github.com/ankidroid/Anki-Android/assets/48384865/e9686c21-ac84-4007-97e8-fcfadde4aca5

## Learning (optional, can help others)
How we can use transparent activities [Google and Stackoverflow but didn't save links to them]

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-05-14 19:35 UTC, david-allison reviewed
Brief thoughts, not a thorough review

2024-05-14 19:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/TextSurroundHelper.kt
> +    data class Disabled(val isEnabled: Boolean = false) : EditTextGestureState()
I suspect you want `EditTextGestureState(val isEnabled: Boolean)` and then passing that value into the constructor

This feels a little over-designed. Unless there's going to be extension, a `value class` over a boolean would allow for documentation without the compelxity

2024-05-14 19:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/TextSurroundHelper.kt
> +                enableGesture()
from a simplicity perspective: instead of adding and removing the listener, you could check for `isEnabled` inside the listener

2024-05-14 19:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/TextSurroundHelper.kt
> +        ) + "{{c${ClozeNumberManager.currentClozeNumber}::$selectedWord}}" + text.substring(end)
from a readability perspective, use `buildString { }`

```kt
        val newText = buildString { 
            append(text.substring(0, start))
            append("{{c${ClozeNumberManager.currentClozeNumber}::$selectedWord}}")
            append(text.substring(end))
        }
```

2024-05-14 19:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +class InstantNoteEditorActivity : AnkiActivity(), DeckSelectionDialog.DeckSelectionListener {
Brief comment

2024-05-14 19:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        deckId = getColUnsafe.config.get(Decks.CURRENT_DECK) ?: 1L
Since this is a new dialog, see if you can move to a `suspend fun` for loading, and move to `withCol { }` instead of `getColUnsafe`

2024-05-14 19:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        deckId = getColUnsafe.config.get(Decks.CURRENT_DECK) ?: 1L
Note: This activity does need to handle the `col` not loading (for example if the user does not have storage permission, or is a brand new user)

2024-05-14 19:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +    private inner class ActionModeCallback(
Was this copied from `NoteEditor`? We can likely extract it to a class used in both implementations

2024-05-14 19:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        changeNoteType(model.id)
Do we want to modify AnkiDroid's selection if this screen is opened

2024-05-14 19:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        val model = getColUnsafe.notetypes.all().first { noteType ->
A user may have more than one 'cloze' note type

Probably needs an option to select the desired one

2024-05-14 19:39 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/EditFieldState.kt
> +class EditFieldState(val editor: InstantNoteEditorActivity) {
deleted this unused code already

2024-05-14 19:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/EditFieldState.kt
> +class EditFieldState(val editor: InstantNoteEditorActivity) {
Deleted my comment already 😅. You're too fast 🥷

2024-05-14 20:56 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +    private inner class ActionModeCallback(
Yes, it is used from NoteEditor, will extract

2024-05-14 20:57 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        changeNoteType(model.id)
Ohh correct had it in my mind but forgot to put it in code, we need to revert to the note type the user was using before

2024-05-14 20:59 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        val model = getColUnsafe.notetypes.all().first { noteType ->
First select the note type (cloze) then editor dialog or should we allow that from the dialog itself?

2024-05-14 22:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        val model = getColUnsafe.notetypes.all().first { noteType ->
Pick a reasonable default, and have an 'options' menu where power users can change it

2024-05-14 23:35 UTC, criticalAY commented
I have extracted the long press callback here: 
* #16401

2024-05-15 08:38 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/TextSurroundHelper.kt
> +}
This is used in two classes so isn't Object a good choice?

2024-05-15 14:50 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/TextSurroundHelper.kt
> +}
No, object is global. Ideally you want the instance to be destroyed once the screen is closed

2024-05-15 18:44 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        changeNoteType(model.id)
Done! Note reverts to AnkiDroid one on `onDestroy`

2024-05-16 20:09 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        runBlocking {
with lifecycle scope yes

2024-05-17 17:48 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        }
Might throw error, we does so in NoteEditor

2024-05-20 08:38 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        enableEdgeToEdge()
Makes the status bar transparent and content is loaded till edges

2024-05-20 08:39 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        if (Intent.ACTION_SEND == intent.action && intent.type != null && "text/plain" == intent.type) {
Can do that, but we should do that in a separate PR for the whole project as it is used in multiple places in AnkiDroid

2024-05-20 09:00 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        val oldModelId = getColUnsafe.notetypes.current().getLong("id")
Can do that, @david-allison leaving it open for discussion

2024-05-21 13:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        startLoadingCollection()
How long do you think it would take to remove this call and make the load asynchronous?

We want to move away from `onCollectionLoaded` long-term, and it would be good to set a reasonable pattern, as we do in the new `Previewer`

2024-05-27 11:15 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +    private val _editorNote = MutableLiveData<Note?>()
I updated it for some vals but not all since SharedFlow is best suited for one time events.

2024-05-27 12:40 UTC, david-allison reviewed
Few more rounds of comments, this is preliminary

Output: looks great!

2024-05-27 12:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +        }
Don't do things which don't need the collection inside `withCol`

Get the value from the collection, then unlock the collection

```suggestion
        val did = withCol { config.get(Decks.CURRENT_DECK) ?: 1L }
        _deckId.postValue(did)
```

2024-05-27 12:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +        }
ditto with too much logic inside the `withCol`. Multiple calls are better

2024-05-27 12:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +    }
Remove this

* one call in the Activity should use `getColUnsafe`
* one call passes this back into the ViewModel, and therefore should use `withCol`

2024-05-27 12:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +                        Timber.d("Cloze note type: ${it.isCloze}")
What is this meant to do? It feels like it'll spam the logs

Maybe `it.name`?

2024-05-27 12:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +    }
+ this doesn't need to be suspect if using `viewModelScope.launch`

```suggestion
   fun checkClozeNoteTypes() = viewModelScope.launch {
        val hasClozeNoteType = withCol { notetypes.all().any { it.isCloze } }
        clozeNoteType.emit(hasClozeNoteType)
    }
```

2024-05-27 12:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +    fun showDialog() {
Reduces the number of `!!`

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt b/AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt	(revision 45a3a1adcf5607b6caa1d28b2e64cdc40f6ad608)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt	(date 1716812733098)
@@ -160,14 +160,16 @@
 
     fun showDialog() {
         Timber.d("Showing Instant Note Editor dialog")
-        dialogView = layoutInflater.inflate(R.layout.instant_editor_dialog, null)
-        editFieldsLayout = dialogView?.findViewById(R.id.editor_fields_layout)
-        singleTapSwitch = dialogView!!.findViewById(R.id.switch_single_tap_cloze)
-        dialogView?.findViewById<MaterialButton>(R.id.open_note_editor)?.setOnClickListener {
+        val dialogView = layoutInflater.inflate(R.layout.instant_editor_dialog, null).also { dv ->
+            dialogView = dv
+        }
+        editFieldsLayout = dialogView.findViewById(R.id.editor_fields_layout)
+        singleTapSwitch = dialogView.findViewById(R.id.switch_single_tap_cloze)
+        dialogView.findViewById<MaterialButton>(R.id.open_note_editor)?.setOnClickListener {
             openNoteEditor()
         }
-        warningTextField = dialogView!!.findViewById(R.id.warning_text)
-        dialogView?.findViewById<MaterialButton>(R.id.increment_cloze_button)?.setOnClickListener {
+        warningTextField = dialogView.findViewById(R.id.warning_text)
+        dialogView.findViewById<MaterialButton>(R.id.increment_cloze_button)?.setOnClickListener {
             currentClozeNumber++
             Timber.d("Incrementing cloze number: $currentClozeNumber")
         }
@@ -182,11 +184,11 @@
 
         instantAlertDialog = AlertDialog.Builder(this).show {
             setView(dialogView)
-            val spinner = dialogView!!.findViewById<LinearLayout>(R.id.spinner_layout)
+            val spinner = dialogView.findViewById<LinearLayout>(R.id.spinner_layout)
             spinner.setOnClickListener {
                 launchCatchingTask { deckSpinnerSelection!!.displayDeckSelectionDialog() }
             }
-            dialogView?.findViewById<MaterialButton>(R.id.action_save_note)?.setOnClickListener {
+            dialogView.findViewById<MaterialButton>(R.id.action_save_note)?.setOnClickListener {
                 Timber.d("Save note button pressed")
                 checkAndSave()
             }
```

2024-05-27 12:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        for (i in 0 until jsonArray.length()) {
Prefer `jsonObjectIterable`

2024-05-27 12:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +                }
extract to a method for setting up cloze fields

2024-05-27 12:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +            if (clozeFields?.firstOrNull() == name) {
is `firstOrNull` accurate? I believe a template can have two cloze fields

2024-05-27 12:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +    private fun resetErrors() {
rename this, the name implies it can be called multiple times

2024-05-27 12:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +    private fun noClozeDialog(errorMessage: String) {
brief comment explaining the method

2024-05-27 12:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +    private fun noClozeDetectedDialog() {
rename: `noClozeNoteTypesFoundDialog()`

2024-05-27 12:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        }
nit: This could be a little easier to read

2024-05-28 21:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +    private val oldNoteId = MutableSharedFlow<Long?>()
Why do we need to select a note type in the first place?

2024-05-28 21:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +    private val _savingNote = MutableLiveData(false)
Consider using a toast here - we want to be in the way as little as possible, and a toast can be displayed after the activity is closed

2024-05-28 21:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +    }
This feels unusual architecturally, why does it happen, why is it public and not in an `init` method, and can we do anything to change it?

2024-05-28 21:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +            setModel(this, model.id)
Why do we need to do this?

2024-05-28 21:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +            setModel(this, model.id)
nit: add an overload with `context(Collection)` to remove the `this` parameter

2024-05-28 21:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +    ) {
Instead of passing in lambdas, I'd return an enum with the result, and execute the continuation based off this

This also makes it a little easier to test

2024-05-28 21:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +            val noteFieldsCheck = editorNote.value?.let { checkNoteFieldsResponse(it) }
if `editorNote` is null, this seems to succeed

2024-05-28 21:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +        viewModelScope.launch {
implementer's choice:

```kotlin
fun checkAndSaveNote(activity: Activity) {
    viewModelScope.launch {
    }
}
```

I prefer the following, as it's more concise, I know others in the project have other optinions:

```kotlin
fun checkAndSaveNote(activity: Activity) = viewModelScope.launch {
}
```

2024-05-28 21:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +        val nid = oldNoteId.first()
`.first()` throws `NoSuchElementException` if the flow was empty. 

Check that this can't occur as a race condition

2024-05-28 21:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +        }
If you can move a check outside the `withCol`, do so, as this saves locking the collection

Combined with the above comment

```suggestion
        val nid = oldNoteId.firstOrNull() ?: return
        withCol { setModel(this, nid) }
```

2024-05-28 21:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +        )
Split the data out of the `.postValue` into a variable

2024-05-28 21:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +                Note.fromNotetypeId(notetype.id)
Don't we have this ID from earlier in the method?

2024-05-29 10:54 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +                Note.fromNotetypeId(notetype.id)
Don't think so

2024-05-29 10:56 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +    private val oldNoteId = MutableSharedFlow<Long?>()
I tried with not setting the note but the fields did not work as expected

2024-05-29 15:14 UTC, david-allison reviewed
Next goal is to remove `oldNoteId` for simplicity

2024-05-29 15:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +    private val oldNoteId = MutableSharedFlow<Long?>()
Can we go over this? It should work, and would hugely reduce the complexity

In addition, this appears to be a NoteTypeId (ModelID), not a NoteId

In init, the procedure should be:

* Find the current `DeckId`
  * this may impact how we find the `NoteTypeId`
* Find a valid `NoteTypeId` (or null if no clozes exist)
* Call `Note.fromNoteTypeId`

From there, you have the note (defining the fields + names in `fieldMap`)

2024-05-29 15:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +    private val _editorNote = MutableLiveData<Note?>()
Why is this a `LiveData` if it's private, wouldn't a variable do the same?

2024-05-30 21:20 UTC, criticalAY commented
> Can we go over this? It shouldn't be necessary, and would hugely reduce the complexity

Not needed for the current note, but when we open the instant editor the cloze type note is selected whereas in AnkiDroid user might not have it selected and might have different note type, I when finished saving this card, we would want that that be reverted back to the original note the user had selected

2024-05-31 11:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +            Timber.d(e, "Error saving note")
`w`

2024-05-31 11:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +            val deckId = deckId.value ?: return SaveNoteResult.Failure(null)
I'd make these both `lateinit`

2024-05-31 11:56 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt
> +        viewModel.setUpNoteType(hasClozeNoteType)
use `col` to delete the note types - make sure things are realistic

2024-05-31 11:56 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt
> +        val result = viewModel.checkAndSaveNote(targetContext)
See if you can drive the VIewModel externally:

* Setup the collection
* Create an instance of the ViewModel
* Call methods on the ViewModel which the UI would call
* Verify the response

2024-05-31 11:56 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt
> +        MockitoAnnotations.openMocks(this)
I don't think this is needed any more

2024-06-01 00:01 UTC, david-allison reviewed
Looking really good!

2024-06-01 00:01 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +                if (result.message == null) {
only if null?

2024-06-01 00:01 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        var currentClozeNumber: Int = 0
Shouldn't this exist in the ViewModel?

This shouldn't be global

2024-06-01 08:58 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        var currentClozeNumber: Int = 0
No, this is also used in the custom text helper to track and put clozes hence not in viewModel

2024-06-01 09:08 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        viewModel = ViewModelProvider(this)[InstantEditorViewModel::class.java]
`viewModels()`

2024-06-01 09:12 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +                if (result.message == null) {
It means that it was not a known error or warning, i.e. when saving note with no cloze there is a warning its not a failure

2024-06-01 10:26 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +                if (result.message == null) {
Would it be better to return a triple: warning | success | failure

Or have failure with a Boolean showing whether it should be reported

2024-06-01 23:13 UTC, david-allison requested changes
I'm /REALLY/ happy, either last, or penultimate review

2024-06-01 23:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        var currentClozeNumber: Int = 0
This shouldn't be global

2024-06-01 23:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        }
Add a TODO to refactor this, [or do so - TODO preferred so this is a non-blocking comment]

* you should subscribe to the flow of `deckId` to change the control value

----
I feel the method should be:

* reinit spinner
* set the viewModel value

2024-06-01 23:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +                lifecycleScope.launch { viewModel.instantEditorError.emit(result.message) }
This shouldn't call `emit` on the ViewModel, do this inside the ViewModel (ideally in the ViewModel scope)

2024-06-01 23:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +                        viewModel.checkAndSaveNote(this@InstantNoteEditorActivity, true)
You need to name this boolean

2024-06-01 23:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        getFieldValues()
This needs a better name - a `get` should return something

2024-06-01 23:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +            }
This common code should be extracted into a method with an `ignoreErrors` boolean

2024-06-01 23:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        }
TODO: define your own iterator here

2024-06-01 23:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +                }
again: move to the `ViewModel` and use its lifecycle scope?

2024-06-02 07:47 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +//        }
Yes, because the send action will never be executed to disabled till the filter is enabled back

2024-06-02 09:36 UTC, david-allison approved these changes
LGTM, some TODOs to be handled later

Congrats! It's happening 🎊

2024-06-02 09:36 UTC, david-allison commented
* Blocked on: https://github.com/ankidroid/Anki-Android/pull/16526

2024-06-03 17:42 UTC, merged