fix:no warning on empty front template
ankidroid/Anki-Android pull request #16423
Opened 2024-05-18 08:43 UTC by shrutigitte

## Purpose / Description
Anki and Ankidroid both have same warning dialog when trying to save front card template

## Fixes 
* Fixes #16220 

## How Has This Been Tested?
Google Emulator
![image](https://github.com/ankidroid/Anki-Android/assets/115779647/35cdcecb-8068-4bd1-a51f-4c4cc993b14c)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-05-19 16:03 UTC, david-allison requested changes
Thanks!!!

Could you also add a `@NeedsTest` annotation for each testable issue raised in this review

2024-05-19 16:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +                    val templateCount = tempModel.templateCount
If I have two templates, and the problem is on the first template, this should be 1, not 2

2024-05-19 16:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +
Please revert - PRs shouldn't contain unnecessary spacing changes

2024-05-20 08:48 UTC, shrutigitte commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +            if (currentTemplate?.front.isNullOrEmpty()) {
anki uses update_notetype_legacy and to show errors anki uses AnkiErrors but I couldn't find something as such so I need help as I am a new contributor .

2024-05-20 21:23 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +            if (currentTemplate?.front.isNullOrEmpty()) {
Best to check in Discord to see if anyone has capacity to bring this to completion

2024-05-21 14:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +            if (currentTemplate?.front.isNullOrEmpty()) {
Could you also mark this as a draft if it's not ready for review

2024-06-24 18:37 UTC, closed without merging