[GSoC'24] Chore: extension method to get cloze field name
ankidroid/Anki-Android pull request #16424
Opened 2024-05-18 10:14 UTC by criticalAY

## Purpose / Description
Anki allows cloze in only the cloze field which is in `qfmt` under `tmpls` here in below screenshot
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/1bb06ae9-cb51-405a-a147-51718bf4f119)

I am creating this extension method so that I can use it in instant note editor to put text and also the bug in NoteEditor i.e. * #16419 can be fixed to check for cloze text in this field along with cloze number >1

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-05-18 13:27 UTC, david-allison requested changes
These all relate to the first field, the second method doesn't return all cloze fields. The names should be changed, or the implementation should be fixed

A little documentation would be useful

Secondly, if the user has multiple filters on the field, I don't believe the second Regex would match this

You should add unit tests for this

2024-05-20 18:01 UTC, david-allison requested changes
Extensions should be generic and work on all instances of the type, this doesn't meet that bar as a standard note type can have more than one template

`NoteTypeJson.templates` would be a good extension (returning something like a `List<CardTemplateJson>`)

`CardTemplateJson.qfmt` is a good extension: a card template should have a `qfmt`

This could also be named `.questionFormat`, because `qfmt` is hard to immediately understand

`NotetypeJson.qfmtField` is not a good extension, it only returns one element, but there are potentially many associated templates


(not sure if you want this):
`val ClozeNoteTypeJson.qfmt get() = this.template.qfmt` is a good extension - a cloze note type only has one template, and in this case we have a good meaning

2024-05-20 20:27 UTC, criticalAY commented
> NoteTypeJson.templates would be a good extension (returning something like a List<CardTemplateJson>)

How about now?

2024-05-20 20:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/CardTemplateJson.kt
> +)
This should be an accessor over the JSON, it shouldn't load it.

Loading the JSON means that a number of properties are unnecessarily loaded, slowing down the code

Placing a wrapper over a JSONObject is effectively free

See how `NotetypeJson` is defined

2024-05-20 21:44 UTC, david-allison requested changes
* The typo fix should go in a separate commit
* The constructor accepts a `string`, this also adds JSON highlighting
  * You may wish to auto-format the JSON, I did a bad manual job

```patch
Subject: [PATCH] test(ci): fix windows runner hanging

Tracked down to all methods on TagsDialog

Adding `: RobolectricTest()` did not resolves this

So add `@Flaky`

Fixes 16404
---
Index: AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt b/AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
--- a/AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt	(revision 69fa6ecef388741b561e1420f8b72f46e17b2954)
+++ b/AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt	(date 1716240981320)
@@ -51,7 +51,7 @@
     }
 
     /**
-     * Creates a model object form json string
+     * Creates a model object from json string
      */
     constructor(@Language("json") json: String) : super(json)
 
Index: AnkiDroid/src/test/java/com/ichi2/utils/NoteTypeTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/utils/NoteTypeTest.kt b/AnkiDroid/src/test/java/com/ichi2/utils/NoteTypeTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/utils/NoteTypeTest.kt	(revision 69fa6ecef388741b561e1420f8b72f46e17b2954)
+++ b/AnkiDroid/src/test/java/com/ichi2/utils/NoteTypeTest.kt	(date 1716241292682)
@@ -21,33 +21,34 @@
 import com.ichi2.anki.utils.ext.templates
 import com.ichi2.libanki.NotetypeJson
 import junit.framework.TestCase.assertEquals
-import org.json.JSONObject
 import kotlin.test.Test
 
+// link to a method in `NoteType.kt` for navigation as it contains no classes
+/** Test of [NoteType][templates] */
 class NoteTypeTest {
 
     private val noteType = """
         {
            "tmpls":[
-       {
-         "name":"Cloze",
-         "ord":0,
-         "qfmt":"{{type:cloze:Text}} {{type:cloze:Text2}} {{cloze:Text3}} {{Added field}}",
-         "afmt":"{{cloze:Text}}<br>\n{{Back Extra}}",
-         "bqfmt":"",
-         "bafmt":"",
-         "did":null,
-         "bfont":"",
-         "bsize":0,
-         "id":-556071557671997833
-      }
+               {
+                 "name":"Cloze",
+                 "ord":0,
+                 "qfmt":"{{type:cloze:Text}} {{type:cloze:Text2}} {{cloze:Text3}} {{Added field}}",
+                 "afmt":"{{cloze:Text}}<br>\n{{Back Extra}}",
+                 "bqfmt":"",
+                 "bafmt":"",
+                 "did":null,
+                 "bfont":"",
+                 "bsize":0,
+                 "id":-556071557671997833
+              }
            ]
         }
     """
 
     @Test
     fun testQfmtField() {
-        val notetypeJson = NotetypeJson(JSONObject(noteType))
+        val notetypeJson = NotetypeJson(noteType)
 
         val expectedQfmt = "{{type:cloze:Text}} {{type:cloze:Text2}} {{cloze:Text3}} {{Added field}}"
         assertEquals(expectedQfmt, notetypeJson.templates[0].qfmt)
@@ -55,7 +56,7 @@
 
     @Test
     fun testGetAllClozeTexts() {
-        val notetypeJson = NotetypeJson(JSONObject(noteType))
+        val notetypeJson = NotetypeJson(noteType)
 
         val expectedClozeTexts = listOf("Text", "Text2", "Text3")
         assertEquals(expectedClozeTexts, notetypeJson.getAllClozeTextFields())
@@ -63,21 +64,21 @@
 
     @Test
     fun testNameField() {
-        val notetypeJson = NotetypeJson(JSONObject(noteType))
+        val notetypeJson = NotetypeJson(noteType)
         val expectedName = "Cloze"
         assertEquals(expectedName, notetypeJson.templates[0].name)
     }
 
     @Test
     fun testOrdField() {
-        val notetypeJson = NotetypeJson(JSONObject(noteType))
+        val notetypeJson = NotetypeJson(noteType)
         val expectedOrd = 0
         assertEquals(expectedOrd, notetypeJson.templates[0].ord)
     }
 
     @Test
     fun testAfmtField() {
-        val notetypeJson = NotetypeJson(JSONObject(noteType))
+        val notetypeJson = NotetypeJson(noteType)
         val expectedAfmt = "{{cloze:Text}}<br>\n{{Back Extra}}"
         assertEquals(expectedAfmt, notetypeJson.templates[0].afmt)
     }
```

2024-05-20 21:44 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/NoteType.kt
> +    }
untested

```suggestion
val NotetypeJson.templates: List<CardTemplateJson>
    get() = getJSONArray("tmpls").jsonObjectIterable().map { CardTemplateJson(it) }
```

2024-05-20 21:44 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/NoteType.kt
> +    val regex = "\\{\\{(?:.*?:)?cloze:([^}]*)\\}\\}".toRegex()
Extract this outside the `fun`, it's a constant value.

Optional extra: look into compiled regexes and compile it (if not done already) for a speedup

2024-05-20 21:44 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/NoteType.kt
> +    val questionFormat = this.templates[0].qfmt
I'd throw if (`this.isCloze` is false)

Your call

2024-05-20 21:44 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/NoteType.kt
> +    val questionFormat = this.templates[0].qfmt
I'd use `.single()` rather than `[0]`

(to be honest, I'd implement this on `ClozeNotetypeJson`, but that's somewhat controversial, and I'd want to check with a second reviewer before this suggestion is implemented).

2024-05-21 19:59 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/NoteType.kt
> +    val questionFormat = this.templates[0].qfmt
This is an extension on NotetypeJson, so it should be in here only ig

2024-05-21 22:25 UTC, david-allison requested changes

2024-05-21 22:25 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/NoteType.kt
> +    val template = this.templates.singleOrNull { it.name == "Cloze" }
I don't believe this is guaranteed to be 'Cloze' in all languages

`this.isCloze` feels more correct

2024-05-21 22:25 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/NoteType.kt
> +    return regex.findAll(questionFormat).map { it.groups[1]?.value.orEmpty() }.toList()
Needs testing, but what I'd expect

```suggestion
fun NotetypeJson.getAllClozeTextFields(): List<String> {
    if (!this.isCloze) {
        throw IllegalStateException("getAllClozeTextFields called on non-cloze template")
    }
    val questionFormat = templates.single().qfmt
    return clozeRegex.findAll(questionFormat).map { it.groups[1]!!.value }.toList()
}
```

2024-05-22 17:14 UTC, david-allison approved these changes
Looks great!

2024-05-26 10:52 UTC, david-allison commented
@criticalAY could you squash this into two commits: one for the typo change, and one for the change 

Ping me if this isn't done in 24hours and I'll get to it. Don't want to block this

2024-05-26 11:02 UTC, criticalAY commented
Done!

2024-05-26 11:43 UTC, merged