[GSoC'24] Refactor DeckPicker to Single Menu Layout
ankidroid/Anki-Android pull request #16425
Opened 2024-05-18 14:52 UTC by SanjaySargam

## Purpose / Description
This PR aims to convert deckpicker to have single menu and also remove StudyOptionsFragment when collection is empty

## Approach
Moved menu items from DeckPicker screen to StudyOptionsFragment

## How Has This Been Tested?
Emulator

https://github.com/ankidroid/Anki-Android/assets/65113071/78a26dbf-eb91-4bef-ac08-9b01eb3b6bc9

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-05-24 12:54 UTC, david-allison requested changes
* Could you split out the functional commits (hiding the fragment on onboarding) to make this easier to review and understand

I would have expected that the combination of menus would mean:

* Remove the menu from the fragment
* Have the activity control the menu, and select different menus depending on the fragment state

Is there a reason you didn't pick this implementation?

2024-05-24 13:55 UTC, SanjaySargam commented
> Is there a reason you didn't pick this implementation?

If I do so, then the context menu ( three dots ) will show in the middle of the screen. I just thought having the menu at the top-right of the screen would be better so that's why I combined menus in fragment

2024-05-24 13:56 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +    context: Context
Not able to access from fragment ( StudyOptionsFragment )

2024-05-26 11:48 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +    context: Context
I'm sorry @SanjaySargam but I don't understand your answer. What can't access from, and how is StudyOptionsFragment related to this code change?

2024-05-26 11:52 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +    context: Context
Ohhh sorry my bad. I'll revert this change

2024-05-26 12:04 UTC, Arthur-Milchior commented
If I understand correctly David request, that means you'd split your PR into multiple commit.
The first commit would just take care of empty collection and remove the second fragment
the second commit would remove the back button when fragmented.
The third would move the menu from one fragment to the other

This way, it becomes far easier for us to review each commit, and consider whether it actually does what it is supposed to do

2024-05-26 12:06 UTC, SanjaySargam commented
Now understood very well

2024-05-26 13:21 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/menu/study_options_fragment.xml
> +        android:id="@+id/action_undo1"
Please, use names that are more meaningful.
In this case `action_undo_study_options` and you can rename the other one `action_undo_deck_picker`

Why do you need to have a different ID, while the items belows seems to be fine sharing the id of deck_picker ?

2024-05-26 13:21 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/menu/study_options_fragment.xml
> +    <group android:id="@+id/allItems" android:visible="false">
My understanding is that this is a copy/paste of deck_picker content, right ?

I don't like to have duplicated code. Because, if one day we update one of the menu, we may forget to update the other one. 

Instead, in `StudyOptionsFragment.kt`, after `toolbar!!.inflateMenu(R.menu.study_options_fragment)` you can add `toolbar!!.inflateMenu(R.menu.deck_picker)`, and you'll have the content of deck_picker.xml at the end of study_option_fragment

2024-05-27 12:46 UTC, SanjaySargam commented on AnkiDroid/src/main/res/menu/study_options_fragment.xml
> +    <group android:id="@+id/allItems" android:visible="false">
> My understanding is that this is a copy/paste of deck_picker content, right ?

Yes

But the issue which I'm facing rn is search icon is showing in two screens ( DeckPicker & StudyOptionsFragment ) even when I explicitly hide the search icon in the fragment. Also the export menu is already there in fragment so I'm trying to hide export menu which is there in deck_picker.xml but still visible

2024-05-28 20:42 UTC, Arthur-Milchior commented
I've a small problem right now with your code when I execute it. 
If you start on a fresh install, just after AnkiDroid asks you to grant access to storage, you start with a split view, and then a second later, you get a single view.
On the one paw, that's not that bad, because it'll occur only the first time you open ankidroid. On the other paw, that's exactly the time where we want to have a single view because the collection is empty. And that would even be worse because that will be the first thing the user see when they open the app on tablet.

I think the issue is that you only know whether you need to display one or two views once the collection is loaded. And obviously, it can't be loaded until permissions are given.
This does not seems to be an issue with the play variant. Probably because there is need for permission.

So, we need to decide what to do when we don't have access to the collection. That is, what to put in the screen before the collection is loaded. Whether there is one or two view by default.
The simplest solution, in my mind, would be to use a preference, as they will be imediately accessible, to recall whether we used to have content last time the collection was opened. It's default value would be "empty". And it would be set to non-empty when any behavior occurs to add a deck.
I'd love opinions of other maintainers, because that seems to be a lot of code complexity for something that will be a rare problem

2024-05-28 21:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/menu/study_options_fragment.xml
> +    <group android:id="@+id/allItems" android:visible="false">
I think, Sanjay, that you'll have to learn to give far more context in your text.
"Right now" seems strange to me. I don't know what "right now" refers to the code in your PR? Whether it refers to origin/main.
In all cases, I don't really understand what you mean here. I can't find any way to get two search icons. And I don't see it in your video.

Similarly, "the export menu is already there in fragment". There are two fragments so it was not clear to me which one you referred to, and I had to take a look to see it's in both fragments. It would be easier for me if you stated "both" directly

2024-05-28 22:56 UTC, Arthur-Milchior reviewed
There are still quite some improvements to do. I admit I really need more information and more context in order to really understand what you tried, what failed, and most importantly, why you did the change you did.

Please don't hesitate to message me on discord if you have questions about my remark. 

I still believe we can avoid that much code duplication.

2024-05-28 22:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
>          when (item.itemId) {
We can probably start the function with
```kotlin
if ((activity as DeckPicker).onOptionsItemSelected(item)) {
  return true;
}
```
So that we reuse all the cases considered in DeckPicker without duplicating code.
As a bonus, that would allow to avoid making some methods public

2024-05-28 22:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +                (activity as DeckPicker).setupMediaSyncMenuItem(menu)
If we use `(activity as DeckPicker)` that much, I suggest we introduce `private val deckPicker = activity as DeckPicker` and we use it everywhere. That'll be more readable I expect

2024-05-28 22:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +    context: Context
Actually, you can access the DeckPicker from StudyOptionsFragment.kt. You already do it many time. It's just `activity as DeckPicker`

So you may not even need to change this function.

I agree with David however. We can just request it to be an Activity. We never actually need it to specifically be a DeckPicker.

2024-05-28 22:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/menu/study_options_fragment.xml
> +    <group android:id="@+id/allItems" android:visible="false">
I don't like that "allItems" does not contains all items from the menu. Is there a better way of describing what it contains ?

2024-05-28 22:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/menu/deck_picker.xml
>      <group android:id="@+id/allItems">
If we were to move the first element, I'd like the group to be renamed, as it's not "all item" anymore.
Also, I'd appreciate if you could explain in the commit message why you moved this item.
Generally, it'd be nice if you could explain the reason of any non-straightforward change in your commit message. And this is really not a change for which I can guess the meaning.

In particular, it seems that https://github.com/ankidroid/Anki-Android/blob/c2bb60dacabbbc7ea0ffab7b913b9d98b8e5d7b2/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt#L975 won't do any anymore to the filter, which seems quite a strange change to me

2024-05-29 10:55 UTC, SanjaySargam commented on AnkiDroid/src/main/res/menu/study_options_fragment.xml
> +    <group android:id="@+id/allItems" android:visible="false">
Can we name it as "commonActions" ?

2024-05-29 10:59 UTC, SanjaySargam commented on AnkiDroid/src/main/res/menu/study_options_fragment.xml
> +    <group android:id="@+id/allItems" android:visible="false">
Can we rename it as "secondaryActions"?

2024-05-29 18:07 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        if (fragmented && collectionIsEmpty) {
```kotlin
if (fragmented) {
      invalidateOptionsMenu()
      studyoptionsFrame?.visibility = if (collectionIsEmpty) View.GONE else View.VISIBLE
  }
``` 

I've done this way, by the considering the case where you have only one deck and you deleted that deck, then the fragment will remove. And when we perform "undo delete deck" , the fragment will show but the optionsMenu is not updating

2024-06-09 02:53 UTC, Arthur-Milchior reviewed
Did you test your code also on small screen?
Because, we should not change anything on phone. And it seems your commit is doing some change. And actually, the orange icon and the empty line of code cause ankidroid to crash. 

Please don't hesitate to ask if you don't know how to debug it. Otherwise, I'd love if you could also have something that still works on android.

Appart from that, I mostly have small remarks concerning the style. It's still hard to review because last commit does a lot of things that are vaguely related. I really want to have some simple commits that do the renaming/introducing a value, that help read the code without any functional change.
And separately THE commit that do the actual functional change, that contains nothing but the functional change.

![2024-06-09-044817_338x600_scrot](https://github.com/ankidroid/Anki-Android/assets/357361/2e83f50e-cb27-47bd-a6aa-6d22d3dd4dd9)
![2024-06-09-044812_343x604_scrot](https://github.com/ankidroid/Anki-Android/assets/357361/b5cde44c-85f0-48ec-b8b8-8a7a076fae5f)

2024-06-09 02:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            studyoptionsFrame?.visibility = if (collectionIsEmpty) View.GONE else View.VISIBLE
I'm not a fan of this change from `!!` to `?.`. I'd be interested in knowing the reason you did it.
If for some reason the frame was null, I'd be happy to have ankidroid crashing and let us know. 
Instead, this would be ignored, even while it should not occur.

If I'm missing something, I'd be interested to see it explained in the commit message.


I'll admit this !! is ugly. If you want to avoid it, I'd suggest creating a first commit where you state that the frame is lateinit. You'll then be able to just assume the variable is non-null everywhere

2024-06-09 02:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +            } else {
I'd appreciate if your commit message could contains slightly more details, so that I can understand what it does without having to read the code.

In this case, it would indicates that the button had no effect, and should not have been here in the first place.

Unless I'm wrong, this was a mistake in AnkiDroid, that was not related to the current PR.
I'd be fine putting it as a separate PR that could be merged very quickly.

2024-06-09 02:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    private fun updateSearchFromState(menu: Menu) {
Maybe, rename to `updateSearchVisibilityFromState` to be more specific.
Because, when I read the part of the code where the method is used, I was wondering whether it was updating the search result, the search field or anything else.

2024-06-09 02:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
>          when (item.itemId) {
Sorry, when re-reading my code snippet, I guess I should have added a comment too. Because, just reading it, it's not as clear as I first thought.

Something such as:
> // `item` was handled by the Deck Picker, no need to handle it here.

2024-06-09 02:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +    private lateinit var deckPicker: DeckPicker
My bad, I gave you a wrong snippet in the previous remark.

What I was suggesting was 

```
   /** Current activity.*/
    private val deckPicker: DeckPicker
        get() = activity as DeckPicker
```

I'd consider putting it in its own commit.
The last commit is long enough, removing from the diff all lines where you use this value would simplify reviewing it

2024-06-09 02:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/menu/study_options_fragment.xml
> +        android:id="@+id/action_undo_study_options"
Similarly, to simplify reviewing the commit, I'd considering renaming the id in its own commit. So that I can concentrate on the important part of the review without having to see all those changes. 

You can do multiple renaming in a single commit.

2024-06-09 02:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/menu/deck_picker.xml
>      <group android:id="@+id/allItems">
Why was this comment ignored? I admit I'm still confused by the name `allItems` that don't contain all items.

2024-06-09 04:58 UTC, SanjaySargam commented on AnkiDroid/src/main/res/menu/deck_picker.xml
>      <group android:id="@+id/allItems">
Can we rename it as "secondaryActions"?

2024-06-10 20:04 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +            } else {
This was a mistake in AnkiDroid. I'll make separate PR

2024-06-11 06:42 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            studyoptionsFrame?.visibility = if (collectionIsEmpty) View.GONE else View.VISIBLE
> I'll admit this !! is ugly. If you want to avoid it, I'd suggest creating a first commit where you state that the frame is lateinit. You'll then be able to just assume the variable is non-null everywhere

we can't do that because on small screen `studyOptionsFrame` will be null

2024-06-11 07:07 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +    private lateinit var deckPicker: DeckPicker
`java.lang.ClassCastException: com.ichi2.anki.StudyOptionsActivity cannot be cast to com.ichi2.anki.DeckPicker`

getting this error only on small screen

2024-06-11 08:02 UTC, SanjaySargam commented on AnkiDroid/src/main/res/menu/study_options_fragment.xml
> +        android:id="@+id/action_undo_study_options"
It is not possibble to rename in separate commit . If I do so,  we will get an error because `action_undo` id contains in deck_picker menu and studyoptions menu

2024-06-18 01:46 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            studyoptionsFrame?.visibility = if (collectionIsEmpty) View.GONE else View.VISIBLE
Then thanks for reverting this chanhge

2024-06-18 05:10 UTC, Arthur-Milchior approved these changes
All of my remarks are related to documentation/comment and can be handled later.
 I tested on smartphone and tablet simulator, and it seems to work as expected. So I'm fine approving it

2024-06-18 06:23 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +    var createMenuJob: Job? = null
> How you intend to use it in test.
Really don't know, I just copied it from deckpicker . And I see `createMenuJob` is not used in any of the test.
Should I remove `@VisibleForTesting`?

2024-06-18 09:18 UTC, david-allison commented
I think it's unusual that the menus for the fragmented view are the responsibility of the fragment on the right, as it adds complexity to the logic

I would expect the menu to be extracted out of the fragments, and extended to the full width of the activity (with the activity being responsible)

You would then have two menu files for the DeckPicker (fragmented/non), and one for the Options (non-fragmented), and but need to worry about conditionally applying text, or moving some of the processing to the fragment

Is there a technical reason why my hunch won't work out?

2024-06-20 17:02 UTC, SanjaySargam commented
@david-allison Would it be acceptable to handle this as a TODO and merge as it is? I will work on this during GSOC period only

2024-06-20 17:13 UTC, david-allison commented
It would, add a to-do and let's get this in

2024-07-01 21:08 UTC, Arthur-Milchior approved these changes
Fine by me. Only a very small nit. I'd be fine merging it as-is

2024-07-05 15:01 UTC, david-allison requested changes
Only a couple of string-related changes. The implementation looks good

Think about the ordering of this menu, and see if you can improve it

<img width="195" alt="Screenshot 2024-07-05 at 16 00 06" src="https://github.com/ankidroid/Anki-Android/assets/62114487/4116e6b6-38c5-4043-9612-97d2b060a580">

2024-07-08 12:49 UTC, david-allison approved these changes
Cheers

2024-07-08 12:52 UTC, david-allison commented
* https://github.com/ankidroid/Anki-Android/pull/16705

2024-07-08 14:09 UTC, merged