Fix: use field check from backend and display error accordingly
ankidroid/Anki-Android pull request #16432
Opened 2024-05-20 10:40 UTC by criticalAY

## Purpose / Description
AnkiDroid used custom made check on field but since Anki already has a method to do so, this PR updates that issue of manual check and check the field content via the Anki method.

## Fixes
* Fixes #16419

## Approach
Use method from backend

## How Has This Been Tested?
When first field is empty:
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/86744831-7add-4614-93f1-5f09cfa0f0e5)

When content has no cloze:
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/1e03f092-a929-4e16-a15f-b339573d7a71)

Wrong cloze field:
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/3bbada4f-e961-4219-bd98-ca59dc12cef5)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-05-20 17:54 UTC, david-allison requested changes
```patch
Subject: [PATCH] test(ci): fix windows runner hanging

Tracked down to all methods on TagsDialog

Adding `: RobolectricTest()` did not resolves this

So add `@Flaky`

Fixes 16404
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt	(revision 91beab6983f9cf148f13f4c8d7678d4c96d0a62d)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt	(date 1716226885766)
@@ -19,62 +19,55 @@
 
 import anki.notes.NoteFieldsCheckResponse
 import com.ichi2.anki.CollectionManager.TR
+import com.ichi2.anki.NoteFieldsCheckResult.*
 import com.ichi2.anki.utils.ext.isImageOcclusion
 import com.ichi2.libanki.Collection
 import com.ichi2.libanki.Note
 import timber.log.Timber
 
 /**
- * Representing the result of checking note fields.
+ * The result of [checking note fields][Note.fieldsCheck], either a [Success], or [Failure] with
+ * user-readable message
  *
- * @property result Boolean indicating if there was some issue or not.
- * @property problem A nullable string that provides details about the problem if the check failed.
+ * @see NoteFieldsCheckResponse.State
+ * @see checkNoteFieldsResponse
  */
-data class NoteFieldsCheckResult(val result: Boolean, val problem: String?)
+sealed interface NoteFieldsCheckResult {
+    data object Success : NoteFieldsCheckResult
 
-/** This method checks the state of the note fields and logs the state. Depending on the state, it may
- *  return false if the note has issues that prevent it from being valid.
+    /** @property localizedMessage user-readable error message */
+    data class Failure(val localizedMessage: String?) : NoteFieldsCheckResult
+}
+
+/** 
+ * Validates fields of a note; produces a human-readable error on failure 
  *
- *  Passes any problem if any to [NoteFieldsCheckResult].
+ * @see NoteFieldsCheckResult
+ * @see Note.fieldsCheck
  **/
 fun checkNoteFieldsResponse(col: Collection, note: Note?): NoteFieldsCheckResult {
     Timber.i("Checking for NoteField State")
-    val result = note?.fieldsCheck(col)
-    result?.let { state ->
-        when (state) {
-            NoteFieldsCheckResponse.State.NORMAL -> {
-                // Intentionally left blank
-            }
-
-            NoteFieldsCheckResponse.State.EMPTY -> {
-                val problem = if (note.notetype.isImageOcclusion) {
-                    TR.notetypesNoOcclusionCreated2()
-                } else {
-                    TR.addingTheFirstFieldIsEmpty()
-                }
-                return NoteFieldsCheckResult(false, problem)
-            }
-
-            NoteFieldsCheckResponse.State.DUPLICATE -> {
-                // Intentionally left blank
-            }
+    val fieldsCheckState = note?.fieldsCheck(col) ?: return Success
+    return when (fieldsCheckState) {
+        NoteFieldsCheckResponse.State.NORMAL, NoteFieldsCheckResponse.State.DUPLICATE 
+            -> Success
+    
+        NoteFieldsCheckResponse.State.EMPTY -> if (note.notetype.isImageOcclusion) {
+            Failure(TR.notetypesNoOcclusionCreated2())
+        } else {
+            Failure(TR.addingTheFirstFieldIsEmpty())
+        }
 
-            NoteFieldsCheckResponse.State.MISSING_CLOZE -> {
-                return NoteFieldsCheckResult(false, TR.addingYouHaveAClozeDeletionNote())
-            }
+        NoteFieldsCheckResponse.State.MISSING_CLOZE ->
+            Failure(TR.addingYouHaveAClozeDeletionNote())
 
-            NoteFieldsCheckResponse.State.NOTETYPE_NOT_CLOZE -> {
-                return NoteFieldsCheckResult(false, TR.addingClozeOutsideClozeNotetype())
-            }
+        NoteFieldsCheckResponse.State.NOTETYPE_NOT_CLOZE -> 
+            Failure(TR.addingClozeOutsideClozeNotetype())
 
-            NoteFieldsCheckResponse.State.FIELD_NOT_CLOZE -> {
-                return NoteFieldsCheckResult(false, TR.addingClozeOutsideClozeField())
-            }
+        NoteFieldsCheckResponse.State.FIELD_NOT_CLOZE -> 
+            Failure(TR.addingClozeOutsideClozeField())
 
-            NoteFieldsCheckResponse.State.UNRECOGNIZED -> {
-                return NoteFieldsCheckResult(false, null)
-            }
-        }
+        NoteFieldsCheckResponse.State.UNRECOGNIZED -> 
+            Failure(localizedMessage = null)
     }
-    return NoteFieldsCheckResult(true, null)
 }
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(revision 91beab6983f9cf148f13f4c8d7678d4c96d0a62d)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(date 1716226590723)
@@ -1021,8 +1021,8 @@
             reloadRequired = true
 
             val noteFieldsCheckResult = withCol { checkNoteFieldsResponse(col = this, editorNote) }
-            if (!noteFieldsCheckResult.result) {
-                addNoteErrorMessage = noteFieldsCheckResult.problem
+            if (noteFieldsCheckResult is NoteFieldsCheckResult.Failure) {
+                addNoteErrorMessage = noteFieldsCheckResult.localizedMessage
                 displayErrorSavingNote()
                 return
             }
```

2024-05-20 17:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
> +fun checkNoteFieldsResponse(col: Collection, note: Note?): NoteFieldsCheckResult {
make this `suspend` and use `withCol` internally

2024-05-20 17:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
> +fun checkNoteFieldsResponse(col: Collection, note: Note?): NoteFieldsCheckResult {
why is note nullable?

2024-05-20 17:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
> +    Timber.i("Checking for NoteField State")
```suggestion
    Timber.d("validating note fields")
```

2024-05-20 17:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +    val getErrorMessage: String
This needs a better name, at the very least, remove the `get` prefix

2024-05-20 17:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                addNoteErrorMessage = noteFieldsCheckResult.problem
This is a no-op if `UNRECOGNIZED` is returned, meaning an incorrect error message is displayed

2024-05-20 18:02 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
> +fun checkNoteFieldsResponse(col: Collection, note: Note?): NoteFieldsCheckResult {
because it is nullable in NoteEditor

2024-05-20 18:21 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                addNoteErrorMessage = noteFieldsCheckResult.problem
It will be null in that case and depending on the field content error message will be displayed, ig it is still better than earlier

2024-05-20 18:24 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
> +fun checkNoteFieldsResponse(col: Collection, note: Note?): NoteFieldsCheckResult {
I changed it now not not null

2024-05-20 18:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                addNoteErrorMessage = noteFieldsCheckResult.problem
It is, can we do better?

2024-05-20 18:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
> +    val fieldsCheckState = withCol { note.fieldsCheck(this) }
optional: look into context to remove the `(this)` parameter:

https://github.com/ankidroid/Anki-Android/blob/85abd410bb517e527dbf4d4e8dd49d109ab007ab/AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt#L305-L315

2024-05-20 18:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                val noteFieldsCheckResult = checkNoteFieldsResponse(editorNote!!)
nit: consider a shorter name

2024-05-20 18:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            showSnackbar(errorMessage, Snackbar.LENGTH_INDEFINITE) {
add a comment explaining this

2024-05-20 18:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +    private var addNoteErrorMessage: String? = null
This isn't reset to null on success

2024-05-20 18:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +    val snackbarErrorText: String
This should probably be a method, up to reviewer 2

2024-05-20 18:38 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +    val snackbarErrorText: String
I made it a method but earlier we had a val so I sticked to that, open to change though

2024-05-20 18:39 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                addNoteErrorMessage = noteFieldsCheckResult.problem
So, we should come come with a case where we can handle `UNRECOGNIZED` state differently

2024-05-20 20:03 UTC, david-allison approved these changes
One minor request, no more comments, LGTM

2024-05-20 20:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            addNoteErrorMessage == UNRECOGNIZED_STATE -> resources.getString(R.string.something_wrong)
remove this and move it closer to the setter

2024-05-20 20:21 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
> +const val UNRECOGNIZED_STATE = "unrecognized_state"
If we use null then `   private var addNoteErrorMessage: String? = null` will create problem

2024-05-20 20:22 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
> +            Failure(UNRECOGNIZED_STATE)
it was removed ig, was unused

2024-05-20 20:30 UTC, david-allison requested changes
Seems like a review comment of mine wasn't sent, apologies for the confusion

```patch
Subject: [PATCH] test(ci): fix windows runner hanging

Tracked down to all methods on TagsDialog

Adding `: RobolectricTest()` did not resolves this

So add `@Flaky`

Fixes 16404
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt	(revision 934e633029e728ba5756ebcc09ba67a93e4b9d23)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt	(date 1716237006525)
@@ -17,6 +17,7 @@
 
 package com.ichi2.anki
 
+import android.content.Context
 import anki.notes.NoteFieldsCheckResponse
 import com.ichi2.anki.CollectionManager.TR
 import com.ichi2.anki.CollectionManager.withCol
@@ -26,9 +27,6 @@
 import com.ichi2.libanki.fieldsCheck
 import timber.log.Timber
 
-/** Unrecognized state string, to handle cases [NoteFieldsCheckResponse.State] is not recognized **/
-const val UNRECOGNIZED_STATE = "unrecognized_state"
-
 /**
  * The result of [checking note fields][Note.fieldsCheck], either a [Success], or [Failure] with
  * user-readable message
@@ -40,7 +38,9 @@
     data object Success : NoteFieldsCheckResult
 
     /** @property localizedMessage user-readable error message */
-    data class Failure(val localizedMessage: String?) : NoteFieldsCheckResult
+    data class Failure(private val localizedMessage: String?) : NoteFieldsCheckResult {
+        fun getLocalizedMessage(context: Context) = localizedMessage ?: context.getString(R.string.something_wrong)
+    }
 }
 
 /**
@@ -73,6 +73,6 @@
             Failure(TR.addingClozeOutsideClozeField())
 
         NoteFieldsCheckResponse.State.UNRECOGNIZED ->
-            Failure(UNRECOGNIZED_STATE)
+            Failure(localizedMessage = null)
     }
 }
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(revision 934e633029e728ba5756ebcc09ba67a93e4b9d23)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(date 1716237006522)
@@ -340,7 +340,6 @@
     @VisibleForTesting
     val snackbarErrorText: String
         get() = when {
-            addNoteErrorMessage == UNRECOGNIZED_STATE -> resources.getString(R.string.something_wrong)
             addNoteErrorMessage != null -> addNoteErrorMessage!!
             allFieldsHaveContent() -> resources.getString(R.string.note_editor_no_cards_created_all_fields)
             else -> resources.getString(R.string.note_editor_no_cards_created)
@@ -1027,7 +1026,7 @@
             lifecycleScope.launch {
                 val noteFieldsCheck = checkNoteFieldsResponse(editorNote!!)
                 if (noteFieldsCheck is NoteFieldsCheckResult.Failure) {
-                    addNoteErrorMessage = noteFieldsCheck.localizedMessage
+                    addNoteErrorMessage = noteFieldsCheck.getLocalizedMessage(this@NoteEditor)
                     displayErrorSavingNote()
                     return@launch
                 }

```

2024-05-20 20:51 UTC, criticalAY commented
Thankyou!

2024-05-20 20:57 UTC, david-allison approved these changes
Looks great, cheers!

2024-05-20 22:45 UTC, BrayanDSO commented
> ![image](https://github.com/ankidroid/Anki-Android/assets/69634269/8d5ff201-033d-446b-86b3-2323288673e3)

Please don't use a snackbar to ask for confirmation. That's what dialogs are for

2024-05-22 17:19 UTC, david-allison reviewed
Last changes, both implementer's choice

Add a `NeedsTest` or a test to be sure the error message is cleared

Cheers!

2024-05-22 17:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            positiveButton(R.string.dialog_yes) {
I believe the material dialog spec prefers save/cancel over yes/no

2024-05-22 17:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                    return@launch
I'd move `addNoteErrorText = null` here (if possible)

2024-05-22 17:39 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            positiveButton(R.string.dialog_yes) {
Anki had it this way, so that's why but yes android usually have save/cancel, want me to change?

2024-05-22 17:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            positiveButton(R.string.dialog_yes) {
Yeah, follow the Android guidelines

2024-05-22 18:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            positiveButton(R.string.dialog_ok) {
I believe prefer 'add/save' rather than OK

2024-05-22 18:07 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            positiveButton(R.string.dialog_ok) {
Resolved!

2024-05-22 19:57 UTC, david-allison approved these changes
Thanks!

2024-05-23 13:52 UTC, criticalAY commented
Put a gsoc label here since will be using the code in instant note editor too before saving the note

2024-05-26 11:07 UTC, merged

2024-05-26 23:49 UTC, david-allison commented
Forgot to sync translations on this one. Running now