Migrate root build file to kotlin dsl
ankidroid/Anki-Android pull request #16451
Opened 2024-05-22 08:43 UTC by lukstbit

## Purpose / Description

Migrates the root build gradle file to kotlin dsl. 
Note: I've done this in a single commit as I don't think it's worth keeping the git history, it's almost only dependencies updates + some tweaks from Mike for CI. This avoids having a commit that doesn't compile in the git history.

## How Has This Been Tested?

Synchronized/built the project.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-05-22 17:29 UTC, david-allison requested changes
Code looks good, treat this as an 'approve' once the macOS CI error is fixed

2024-05-22 17:29 UTC, david-allison commented on build.gradle.kts
> +        outputStream.toString().toInt()
Genuine CI failure:

```
Build file '/Users/runner/work/Anki-Android/Anki-Android/build.gradle.kts' line: 129
* What went wrong:
For input string: "3
"
```


```suggestion
        outputStream.toString().trim().toInt()
```

2024-05-23 19:34 UTC, david-allison approved these changes
Thanks!

2024-05-24 08:42 UTC, BrayanDSO approved these changes

2024-05-24 09:00 UTC, merged