[GSoC'24]  Implementation of Deck Picker Widget .
ankidroid/Anki-Android pull request #16450
Opened 2024-05-22 08:38 UTC by xenonnn4w

## Purpose / Description
Initial Implementation of Deck Picker Widget . 

## Approach
Created the Basic layout, initial constraints, Deck layouts .

## How Has This Been Tested?
![image](https://github.com/ankidroid/Anki-Android/assets/139516059/9bfde2b1-beb7-45fc-a5bc-945960e3b434)

https://github.com/ankidroid/Anki-Android/assets/139516059/2c8580ab-61c4-47d4-a073-864c0b738abc

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-05-22 14:04 UTC, david-allison reviewed
This looks great! 

For the analytics in the base class, check in that you're still logging the correct class name

This could do with a unit test

Main focuses other than the review comments:

* See if you can convert the images into drawables, or reuse the ones we have to reduce APK size

2024-05-22 14:04 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        UsageAnalytics.sendAnalyticsEvent(this.javaClass.simpleName, "disabled")
As we do with fragments, make an `AnalyticsWidgetProvider` and see if you can remove this from the widget code into the base class

2024-05-22 14:04 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        if (!IntentHandler.grantedStoragePermissions(context, showToast = false)) {
Move the implementation of this check into the base class

2024-05-23 13:10 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        UsageAnalytics.sendAnalyticsEvent(this.javaClass.simpleName, "disabled")
Done

2024-05-23 13:11 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        if (!IntentHandler.grantedStoragePermissions(context, showToast = false)) {
Done!

2024-05-26 11:52 UTC, david-allison requested changes
Looks great! I think the main question is getting to a conclusion on including the title or not

2024-05-26 11:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> + * This program is free software; you can redistribute it and/or modify it under        *
Feel free to add your own name + email

2024-05-26 11:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +    private val usageAnalytics: UsageAnalytics = UsageAnalytics
I don't think this is necessary

2024-05-26 11:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +open class AnalyticsWidgetProvider : AppWidgetProvider() {
Optional: split this out into a second PR so it can be merged more quickly

2024-05-26 11:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +    open fun performUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray, usageAnalytics: UsageAnalytics) {
Should this be abstract, or is there a reason it won't need to be overridden

2024-05-26 11:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +    override fun onEnabled(context: Context) {
Add `@CallSuper` annotations to make it an error to not call super.onEnabled

2024-05-26 12:12 UTC, xenonnn4w commented on AnkiDroid/src/main/res/values/widgets_strings.xml
> +    <string name="app_widget_description">Deck Picker</string>
Inlined ✅ , did'nt get how i can move them to `08-widget` ( do i've to move whole widgets_string.xml there or specific strings ?)

2024-05-26 12:17 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> + * This program is free software; you can redistribute it and/or modify it under        *
alright !

2024-05-26 12:18 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +open class AnalyticsWidgetProvider : AppWidgetProvider() {
okie !

2024-05-26 12:22 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +    private val usageAnalytics: UsageAnalytics = UsageAnalytics
Removed , just wrote it while writing the unit test , to assist that :smiling_face_with_tear:

2024-05-26 12:25 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +    override fun onEnabled(context: Context) {
Got it ! Done

2024-05-26 12:28 UTC, david-allison commented on AnkiDroid/src/main/res/values/widgets_strings.xml
> +    <string name="app_widget_description">Deck Picker</string>
Just the strings which we'll want to translate

2024-05-26 12:49 UTC, xenonnn4w commented on AnkiDroid/src/main/res/values/widgets_strings.xml
> +    <string name="app_widget_description">Deck Picker</string>
Index: AnkiDroid/src/main/res/values/08-widget.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/res/values/08-widget.xml b/AnkiDroid/src/main/res/values/08-widget.xml
--- a/AnkiDroid/src/main/res/values/08-widget.xml	(revision 2c7d0ca9b9a8e50d1cf8d56cb52c4b36c697b82a)
+++ b/AnkiDroid/src/main/res/values/08-widget.xml	(date 1716727231969)
@@ -38,4 +38,6 @@
     </plurals>
 
     <string name="widget_add_note_button">Add new AnkiDroid note</string>
+    <string name="DeckPickerWidgetLabel">Deck</string>
+    <string name="app_widget_description">Deck Picker</string>
 </resources>

2024-05-26 12:51 UTC, xenonnn4w commented on AnkiDroid/src/main/res/values/widgets_strings.xml
> +    <string name="app_widget_description">Deck Picker</string>
```
Index: AnkiDroid/src/main/res/values/08-widget.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/res/values/08-widget.xml b/AnkiDroid/src/main/res/values/08-widget.xml
--- a/AnkiDroid/src/main/res/values/08-widget.xml    (revision 2c7d0ca9b9a8e50d1cf8d56cb52c4b36c697b82a)
+++ b/AnkiDroid/src/main/res/values/08-widget.xml    (date 1716727231969)
@@ -38,4 +38,6 @@
     </plurals>
 
     <string name="widget_add_note_button">Add new AnkiDroid note</string>
+    <string name="DeckPickerWidgetLabel">Deck</string>
+    <string name="app_widget_description">Deck Picker</string>
 </resources>
```

2024-05-26 12:56 UTC, xenonnn4w commented on AnkiDroid/src/main/res/values/widgets_strings.xml
> +    <string name="app_widget_description">Deck Picker</string>
```
Index: AnkiDroid/src/main/res/values/widgets_strings.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/res/values/widgets_strings.xml b/AnkiDroid/src/main/res/values/widgets_strings.xml
--- a/AnkiDroid/src/main/res/values/widgets_strings.xml	(revision 2c7d0ca9b9a8e50d1cf8d56cb52c4b36c697b82a)
+++ b/AnkiDroid/src/main/res/values/widgets_strings.xml	(date 1716727460003)
@@ -1,26 +1,23 @@
 <?xml version="1.0" encoding="utf-8"?>
 <resources>
-    <string name="app_widget_description">Deck Picker</string>
     <string name="deck1">Deck1</string>
-    <string name="DeckPickerWidgetLabel">Deck</string>
     <string name="deck2">Deck2</string>
     <string name="deck3">Deck3</string>
     <string name="deck4">Deck4</string>
     <string name="deck5">Deck5</string>
-    <string name="deck1NewCardsValue">50</string>
-    <string name="deck1DueCardsValue">51</string>
-    <string name="deck1LearnCardsValue">52</string>
-    <string name="deck2NewCardsValue">53</string>
-    <string name="deck2DueCardsValue">54</string>
-    <string name="deck2LearnCardsValue">55</string>
-    <string name="deck3NewCardsValue">56</string>
-    <string name="deck3DueCardsValue">57</string>
-    <string name="deck3LearnCardsValue">58</string>
-    <string name="deck4NewCardsValue">59</string>
-    <string name="deck4DueCardsValue">60</string>
-    <string name="deck4LearnCardsValue">61</string>
-    <string name="deck5NewCardsValue">62</string>
-    <string name="deck5DueCardsValue">63</string>
-    <string name="deck5LearnCardsValue">64</string>
-
+    <string name="deck1NewCardsValue"/>  
+    <string name="deck1DueCardsValue"/>
+    <string name="deck1LearnCardsValue"/>
+    <string name="deck2NewCardsValue"/>
+    <string name="deck2DueCardsValue"/>
+    <string name="deck2LearnCardsValue"/>
+    <string name="deck3NewCardsValue"/>
+    <string name="deck3DueCardsValue"/>
+    <string name="deck3LearnCardsValue"/>
+    <string name="deck4NewCardsValue"/>
+    <string name="deck4DueCardsValue"/>
+    <string name="deck4LearnCardsValue"/>
+    <string name="deck5NewCardsValue"/>
+    <string name="deck5DueCardsValue"/>
+    <string name="deck5LearnCardsValue"/>
 </resources>
\ No newline at end of file

```

2024-05-26 13:58 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +    open fun performUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray, usageAnalytics: UsageAnalytics) {
yep it should be abstract , at time when i was writing code for flexible layout idk i just write some of that under this so i put it open !

2024-05-26 14:09 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +    open fun performUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray, usageAnalytics: UsageAnalytics) {
getting error as `Class 'TestWidgetProvider' is not abstract and does not implement abstract base class member public abstract fun performUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray, usageAnalytics: UsageAnalytics): Unit defined in com.ichi2.widget.AnalyticsWidgetProvide` in DeckPickerTest.kt if i make it abstract

2024-05-26 21:08 UTC, david-allison commented on AnkiDroid/src/main/res/values/widgets_strings.xml
> +    <string name="app_widget_description">Deck Picker</string>
No need to diff if you're on GitHub, patch away :)

2024-05-26 21:11 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +    override fun onEnabled(context: Context) {
You want these on other relevant methods, not just this one

2024-05-26 21:11 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +    open fun performUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray, usageAnalytics: UsageAnalytics) {
Implement the method in the test class (doing nothing)

2024-05-26 21:11 UTC, david-allison commented on AnkiDroid/src/main/res/drawable/widget_deck_picker_draw.png
I'd leave this for now, until we've decided on the final output of the widget

In addition: the star feels a little squashed

2024-05-26 21:11 UTC, david-allison commented on AnkiDroid/src/main/res/values/widgets_strings.xml
> +    <string name="deck5LearnCardsValue"/>
```suggestion
```

2024-05-26 21:11 UTC, david-allison commented on AnkiDroid/src/main/res/layout/widget_deck_picker_large.xml
> +                android:text="@string/deck5NewCardsValue"
`tools:text="50"`

2024-05-26 22:42 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/widget/DeckPickerWidgetTest.kt
> +        mockkObject(UsageAnalytics)
should be `unmockkObject`

2024-05-27 08:32 UTC, xenonnn4w commented on AnkiDroid/src/main/res/drawable/widget_deck_picker_draw.png
same thoughts :> 
<details>
  <summary>For star squashed </summary>
- ![image](https://github.com/ankidroid/Anki-Android/assets/139516059/2dbef7c1-4126-4aa4-b011-4302e269fa93)
</details>

2024-06-05 06:00 UTC, david-allison requested changes

2024-06-05 06:00 UTC, david-allison commented on AnkiDroid/src/main/res/layout/widget_deck_picker_large.xml
> +                android:text="@string/deck1"
use `tools:text` and hardcode the string

2024-06-05 19:01 UTC, xenonnn4w commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +<appwidget-provider xmlns:android="http://schemas.android.com/apk/res/android"
As per our discussion , at last time we reached at these sizes ;
sizes -  3 W* 2H Default 
           -4 W* 5H Size we maximum width 
           -3 W* 1H Size with minimum height
so according to these , the values were selected !

2024-06-05 19:07 UTC, xenonnn4w commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:previewImage="@drawable/deck_picker_widget"
oouch , elaborate please  :3 , dynamic color part handles that ?

2024-06-05 19:46 UTC, david-allison commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +<appwidget-provider xmlns:android="http://schemas.android.com/apk/res/android"
Add this to a comment, so someone knows in the future

2024-06-05 19:47 UTC, david-allison commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:previewImage="@drawable/deck_picker_widget"
I believe the image is currently a png, and therefore static, regardless of the phone's theme

What do other apps look like here?

2024-06-05 20:12 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +}
getting `Unresolved reference: getDeckNameAndStats` even after making ` @VisibleForTesting` in the test class

2024-06-05 20:14 UTC, xenonnn4w commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +<appwidget-provider xmlns:android="http://schemas.android.com/apk/res/android"
alr

2024-06-05 20:18 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +}
patch?

2024-06-06 08:10 UTC, xenonnn4w commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:previewImage="@drawable/deck_picker_widget"
some are using same image for both themes while some having one for light theme and one for dark theme.

2024-06-06 08:22 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +}
```Subject: [PATCH] refactoring
---
Index: AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt b/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
--- a/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt	(revision 5c05bc6691d126b7c6228d4fc82cbee28095754c)
+++ b/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt	(date 1717618313577)
@@ -23,6 +23,7 @@
 import com.ichi2.anki.CollectionManager.withCol
 import com.ichi2.anki.R
 import timber.log.Timber
+import androidx.annotation.VisibleForTesting
 
 data class DeckPickerWidgetData(
     val deckId: Long,
@@ -32,28 +33,6 @@
     val newCount: Int
 )
 
-suspend fun getDeckNameAndStats(deckIds: List<Long>): List<DeckPickerWidgetData> {
-    val result = mutableListOf<DeckPickerWidgetData>()
-
-    val deckTree = withCol { sched.deckDueTree() }
-
-    deckTree.forEach { node ->
-        if (node.did !in deckIds) return@forEach
-        result.add(
-            DeckPickerWidgetData(
-                deckId = node.did,
-                name = node.lastDeckNameComponent,
-                reviewCount = node.revCount,
-                learnCount = node.lrnCount,
-                newCount = node.newCount
-            )
-        )
-    }
-
-    val deckIdToData = result.associateBy { it.deckId }
-    return deckIds.mapNotNull { deckIdToData[it] }
-}
-
 class DeckPickerWidget : AppWidgetProvider() {
 
     override fun onUpdate(
@@ -77,4 +56,26 @@
             appWidgetManager.updateAppWidget(widgetId, remoteViews)
         }
     }
+    @VisibleForTesting
+    suspend fun getDeckNameAndStats(deckIds: List<Long>): List<DeckPickerWidgetData> {
+        val result = mutableListOf<DeckPickerWidgetData>()
+
+        val deckTree = withCol { sched.deckDueTree() }
+
+        deckTree.forEach { node ->
+            if (node.did !in deckIds) return@forEach
+            result.add(
+                DeckPickerWidgetData(
+                    deckId = node.did,
+                    name = node.lastDeckNameComponent,
+                    reviewCount = node.revCount,
+                    learnCount = node.lrnCount,
+                    newCount = node.newCount
+                )
+            )
+        }
+
+        val deckIdToData = result.associateBy { it.deckId }
+        return deckIds.mapNotNull { deckIdToData[it] }
+    }
 }
Index: AnkiDroid/src/test/java/com/ichi2/anki/widget/DeckNameAndStatsTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/widget/DeckNameAndStatsTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/widget/DeckNameAndStatsTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/widget/DeckNameAndStatsTest.kt	(revision 5c05bc6691d126b7c6228d4fc82cbee28095754c)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/widget/DeckNameAndStatsTest.kt	(date 1717618313586)
@@ -18,7 +18,7 @@
 
 import androidx.test.ext.junit.runners.AndroidJUnit4
 import com.ichi2.anki.RobolectricTest
-import com.ichi2.widget.getDeckNameAndStats
+import com.ichi2.widget.DeckPickerWidget
 import org.junit.Test
 import org.junit.runner.RunWith
 import kotlin.test.assertEquals
@@ -74,18 +74,4 @@
         assertEquals(child1Id, result[1].deckId)
     }
 
-    @Test
-    fun testGetDeckNameAndStats_truncatedNames() = runTest {
-        val deck1Id = addDeck("Deck 1")
-        val child1Id = addDeck("Deck 1::Child 1")
-        val deckIds = listOf(deck1Id, child1Id)
-
-        val result = getDeckNameAndStats(deckIds)
-
-        assertEquals(2, result.size)
-        assertEquals("Deck 1", result[0].name)
-        assertEquals(deck1Id, result[0].deckId)
-        assertEquals("Child 1", result[1].name)
-        assertEquals(child1Id, result[1].deckId)
-    }
-}
+}
```

2024-06-06 12:16 UTC, david-allison commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:previewImage="@drawable/deck_picker_widget"
Anything regarding Material You and using the user's theme, or are all pre-defined images?

2024-06-06 14:34 UTC, xenonnn4w commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:previewImage="@drawable/deck_picker_widget"
The `android:previewImage` attribute is not intended to support dynamic theming and will always display a static image , so ig we have to develop logic in companion object of DeckPickerWidget.kt

2024-06-06 14:35 UTC, xenonnn4w commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:previewImage="@drawable/deck_picker_widget"
![widget_deck_picker_light_mode](https://github.com/ankidroid/Anki-Android/assets/139516059/fdf73a48-e614-43fb-b41b-5aa4c57b5141)
![deck_picker_widget](https://github.com/ankidroid/Anki-Android/assets/139516059/68af9e40-3306-4ad4-84fd-2337dbf1f6d9)
ig these 2 will work out for respective modes!

2024-06-06 15:39 UTC, david-allison commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:previewImage="@drawable/deck_picker_widget"
Sure!

2024-06-07 08:38 UTC, xenonnn4w commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:previewImage="@drawable/deck_picker_widget"
I worked over it , from what i got as of now is like smtg that we have create two providers files and fed them manifest as 
```
<receiver
            android:name="com.ichi2.widget.DeckPickerWidget"
            android:exported="false"
            >
            <intent-filter>
                <action android:name="android.appwidget.action.APPWIDGET_UPDATE" />
            </intent-filter>

            <meta-data
                android:name="android.appwidget.provider"
                android:resource="@xml/widget_provider_deck_picker_dark" />
            <meta-data
                android:name="android.appwidget.provider"
                android:resource="@xml/widget_provider_deck_picker_light"
        </receiver>
```
and make a function around it to set which meta data is to fed up

2024-06-10 13:22 UTC, david-allison commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:previewImage="@drawable/deck_picker_widget"
I don't believe this is correct - I have a number of app widgets which are using my Material You colors in the preview

2024-06-14 17:35 UTC, xenonnn4w commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:previewImage="@drawable/deck_picker_widget"
oh will look into it after completing the Deck Picker Config Screen work .

2024-07-18 14:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +}
```patch
Index: AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt b/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
--- a/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt	(revision 8c4387964d827397053d9cbb48745ae53fd800c0)
+++ b/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt	(date 1721313356778)
@@ -40,28 +40,6 @@
     val newCount: Int
 )
 
-suspend fun getDeckNameAndStats(deckIds: List<Long>): List<DeckPickerWidgetData> {
-    val result = mutableListOf<DeckPickerWidgetData>()
-
-    val deckTree = withCol { sched.deckDueTree() }
-
-    deckTree.forEach { node ->
-        if (node.did !in deckIds) return@forEach
-        result.add(
-            DeckPickerWidgetData(
-                deckId = node.did,
-                name = node.lastDeckNameComponent,
-                reviewCount = node.revCount,
-                learnCount = node.lrnCount,
-                newCount = node.newCount
-            )
-        )
-    }
-
-    val deckIdToData = result.associateBy { it.deckId }
-    return deckIds.mapNotNull { deckIdToData[it] }
-}
-
 class DeckPickerWidget : AppWidgetProvider() {
 
     override fun onUpdate(
@@ -181,3 +159,26 @@
         }
     }
 }
+
+suspend fun getDeckNameAndStats(deckIds: List<Long>): List<DeckPickerWidgetData> {
+    val result = mutableListOf<DeckPickerWidgetData>()
+
+    val deckTree = withCol { sched.deckDueTree() }
+
+    deckTree.forEach { node ->
+        if (node.did !in deckIds) return@forEach
+        result.add(
+            DeckPickerWidgetData(
+                deckId = node.did,
+                name = node.lastDeckNameComponent,
+                reviewCount = node.revCount,
+                learnCount = node.lrnCount,
+                newCount = node.newCount
+            )
+        )
+    }
+
+    val deckIdToData = result.associateBy { it.deckId }
+    return deckIds.mapNotNull { deckIdToData[it] }
+}
+
```

2024-07-18 14:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +            GlobalScope.launch(Dispatchers.Main) {
Better to use the AnkiDroidApp scope

2024-07-18 14:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +    private fun saveSelectedDecksToPreferences() {
needs documentation

2024-07-18 14:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +        editor.apply()
non-functional refactor. You'll need to import `edit {`

```suggestion
        val sharedPreferences = getSharedPreferences("DeckPickerWidgetPrefs", Context.MODE_PRIVATE)
        val selectedDecks = deckAdapter.decks.map { it.deckId.toString() }
        getSharedPreferences("DeckPickerWidgetPrefs", Context.MODE_PRIVATE).edit {
            putString("selected_decks_$appWidgetId", selectedDecks.joinToString(","))
        }
```

2024-07-18 14:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +        val selectedDecksString = sharedPreferences.getString("selected_decks_$appWidgetId", "")
How do you delete data once `appWidgetId` is no longer valid?

For example if the widget is removed

2024-07-18 14:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +        val sharedPreferences = getSharedPreferences("DeckPickerWidgetPrefs", Context.MODE_PRIVATE)
I would extract the preference access/deserialization into a separate class, for readability:

* The widget doesn't need to know the implementation details
* Having a smaller class allows us to focus more on the config

2024-07-18 14:42 UTC, david-allison commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="no_favourite_deck_placeholder_title">"No decks are marked favourite "</string>
Why is this quoted?

2024-07-18 14:43 UTC, david-allison commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck3Learn_deck_picker_widget">5</string>
These should be hardcoded, in constants.xml, as they don't need to be translated

2024-07-18 14:43 UTC, david-allison commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck3Name_deck_picker_widget">math</string>
These should have a `comment=` explaining to translators that these are sample deck names

2024-07-18 14:44 UTC, david-allison commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="widget_config_screen_done_button" comment="This will redirect the user to widget deck picker and will mark the end of configuration screen of widget deck picker">Done</string>
Is this needed? Can we use a string in Android, or an existing string in the constants? `Save` for example?

2024-07-18 14:44 UTC, david-allison commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck_limit_reached">Only 5 decks can be marked favourite.</string>
This limit feels a little low. Could you document why you selected it?

2024-07-18 14:44 UTC, david-allison commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="no_favourite_deck_placeholder_description">Start marking decks favourite using the + icon.</string>
Grammar

2024-07-19 15:38 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +            GlobalScope.launch(Dispatchers.Main) {
```   AnkiDroidApp.coroutineScope.launch(Dispatchers.Main) {
                val deckData = getDeckNameAndStats(deckIds.toList()) ```
like this ?

2024-07-19 16:45 UTC, xenonnn4w commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck3Name_deck_picker_widget">math</string>
just shifted to `constants.xml` and added a overall comment

2024-07-19 17:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +            GlobalScope.launch(Dispatchers.Main) {
I think so, yes

2024-07-19 18:16 UTC, xenonnn4w commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="widget_config_screen_done_button" comment="This will redirect the user to widget deck picker and will mark the end of configuration screen of widget deck picker">Done</string>
yep we can do that

2024-07-19 19:36 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +            GlobalScope.launch(Dispatchers.Main) {
Unresolved reference: coroutineScope , getting this if i try to implement above

2024-07-20 11:26 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        Timber.d("onUpdate")
This should be based off `AnalyticsWidgetProvider`, and therefore shouldn't need logs in `onUpdate`

2024-07-20 11:26 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        } else if (intent?.action == "com.ichi2.widget.ACTION_UPDATE_WIDGET") {
extract to a constant

2024-07-20 11:26 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +    override fun onReceive(context: Context?, intent: Intent?) {
as with the above, `context` should not be null

2024-07-20 11:26 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +            GlobalScope.launch(Dispatchers.Main) {
The variable is named `applicationScope`

2024-07-20 11:26 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        private fun setRecurringAlarm(context: Context, appWidgetId: Int) {
What's the logic here? It feels that this is recurring, but a new scheduled alarm is created each time `onUpdate` is called

2024-07-20 11:26 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +                60000,
change to `60_000` and extract to a constant

2024-07-20 11:26 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
> +            .filter { it != "com.ichi2.widget.DeckPickerWidgetConfig" }
Why is this ignored rather than handled?

2024-07-20 11:26 UTC, david-allison commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:updatePeriodMillis="60000"
Why does this both have a recurring alarm and have `updatePeriodMillis` set?

2024-07-20 12:21 UTC, xenonnn4w commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:updatePeriodMillis="60000"
oh , i was testing something , forget there ; i can remove it safely now.

2024-07-20 12:22 UTC, xenonnn4w commented on AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
> +            .filter { it != "com.ichi2.widget.DeckPickerWidgetConfig" }
thought of finishing the priority tasks first , and to work on that later.

2024-07-20 12:30 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        private fun setRecurringAlarm(context: Context, appWidgetId: Int) {
Fixed

2024-07-21 15:07 UTC, david-allison requested changes
Conflicts need resolving

2024-07-21 15:08 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
> +            .filter { it != "com.ichi2.widget.DeckPickerWidgetConfig" }
At the very least, leave a TODO

But this should be a couple of lines to fix

2024-07-21 15:23 UTC, david-allison requested changes

2024-07-21 15:23 UTC, david-allison commented on AnkiDroid/src/main/res/values/constants.xml
> +    <string name="deck3Name_deck_picker_widget">math</string>
These should be translatable

2024-07-21 19:20 UTC, xenonnn4w commented on AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
> +            .filter { it != "com.ichi2.widget.DeckPickerWidgetConfig" }
yep leaving a TODO for a while, will work on it after the project progress becomes more on track

2024-07-28 16:05 UTC, david-allison commented
Move the card analysis widget into a separate PR

2024-07-28 23:51 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +This program is free software; you can redistribute it and/or modify it under
Nit: please juste copy paste from other file. In particular, this would ensure that all lines of the licence begins with a *, and it gets properly aligned

2024-07-28 23:51 UTC, Arthur-Milchior commented on AnkiDroid/src/main/AndroidManifest.xml
> +            android:enabled="false">
Please add in the commit message and the PR description the fact that the reviewer need to switch `enabled` to `true` in order to test your PR.

I admit I lost too much time on it, trying to understand whether I failed to understand something about widget.

2024-07-28 23:51 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +class DeckPickerWidget : AppWidgetProvider() {
As I mentioned in a previous PR, I'd like more documentation. Both in the commit message and the code.
One line of commit message is far too short, given that you introduce from scratch a whole new feature. 
I can review what you did, but I don't know what you intended to do, and so I can't check whether your code actually implements correctly what you want.
Instead, I'd appreciate if you could state, explicitly, something that descirbes in plain English what the user will see.
Probably something such as
> A widget that shows a list of deck, and the number of cards to see today that are new/in learning/in review.
> The widget takes horizontally the space of 3 icons and vertically can be resized. No user action can be done from this widget, it is only used for display purposes

(The last sentence seems useful too, because intuitively, I'd expect the user to be able to click on a deck to start reviewing it)
And more importantly, if there are more options, more things user can do, and you wrote them here, it would ensure that I can test them, that I am not missing any feature in my manual testing.


Please don't copy paste my text. I don't actually know what are the constraint that you want to follow, and what constraints are related to my particular simulator. So ensure that your text is exact.


Please do the same thing for any other widget and the configuration  clasess

2024-07-29 15:55 UTC, david-allison requested changes

2024-07-29 15:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        private fun getSelectedDeckIdsFromPreferencesDeckPickerWidget(context: Context, appWidgetId: Int): LongArray {
the method names don't need `DeckPickerWidget` suffixes if they are in a `DeckPickerWidget` class

2024-07-29 15:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +            applicationScope.launch(Dispatchers.Main) {
Is there a reason this isn't using the AnkiDroidApp scope?

2024-07-29 15:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +                val ONE_MINUTE_MILLIS = 60_000L
Maybe `60.seconds.inWholeMilliseconds`

2024-07-29 15:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +            if (pendingIntent == null) {
Explain what happens if `onUpdate` is called and an alarm already exists

2024-07-29 15:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +                val newPendingIntent = PendingIntent.getBroadcast(context, appWidgetId, intent, PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE)
Add a `Timber.d` here for the two cases: `== null` and `!= null`

2024-07-29 15:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +            val alarmManager = context.getSystemService(Context.ALARM_SERVICE) as AlarmManager
Add a timber log

2024-07-29 15:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +class DeckPickerWidget : AppWidgetProvider() {
This should use the base class you created

2024-07-29 15:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +        setResult(RESULT_CANCELED)
Why?

2024-07-29 15:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +        }
```suggestion
        appWidgetId = intent.extras?.getInt(
            AppWidgetManager.EXTRA_APPWIDGET_ID,
            AppWidgetManager.INVALID_APPWIDGET_ID
        ) ?: AppWidgetManager.INVALID_APPWIDGET_ID
```

2024-07-29 15:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +            Timber.tag("DeckPickerWidgetConfig").e("Invalid App Widget ID")
Use the standard `Timber.w`

And see: https://github.com/ankidroid/Anki-Android/wiki/Code-style#log-levels

2024-07-29 15:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +        itemTouchHelper.attachToRecyclerView(recyclerView)
Minor preference

```suggestion
        this.deckAdapter = WidgetConfigScreenAdapter(mutableListOf())
        findViewById<RecyclerView>(R.id.recyclerViewSelectedDecks).apply {
            layoutManager = LinearLayoutManager(context)
            adapter = this@DeckPickerWidgetConfig.deckAdapter

            val itemTouchHelper = ItemTouchHelper(itemTouchHelperCallback)
            itemTouchHelper.attachToRecyclerView(this)
        }
```

2024-07-29 15:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +
Don't expose a mutable collection from an adapter if possible

```patch
Index: AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt b/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
--- a/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt	(revision 6bf188ae9310a346d87ebfe727cee4c3acd5260b)
+++ b/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt	(date 1722268224875)
@@ -77,7 +77,7 @@
 
         val recyclerView = findViewById<RecyclerView>(R.id.recyclerViewSelectedDecks)
         recyclerView.layoutManager = LinearLayoutManager(this)
-        deckAdapter = WidgetConfigScreenAdapter(mutableListOf())
+        deckAdapter = WidgetConfigScreenAdapter()
         recyclerView.adapter = deckAdapter
 
         val itemTouchHelper = ItemTouchHelper(itemTouchHelperCallback)
@@ -201,7 +201,7 @@
         getSharedPreferences("DeckPickerWidgetPrefs", Context.MODE_PRIVATE)
 
         // Get the list of selected deck IDs as strings
-        val selectedDecks = deckAdapter.decks.map { it.deckId.toString() }
+        val selectedDecks = deckAdapter.deckIds.map { it.toString() }
 
         // Store the selected deck IDs in SharedPreferences using an editor with a lambda
         getSharedPreferences("DeckPickerWidgetPrefs", Context.MODE_PRIVATE).edit {
@@ -236,7 +236,7 @@
 
     /** Returns a list of selected deck IDs. */
     private fun getSelectedDeckIdsDeckPickerWidget(): List<Long> {
-        return deckAdapter.decks.map { it.deckId }
+        return deckAdapter.deckIds
     }
 
     /** Deletes the widget data associated with the given app widget ID. */
Index: AnkiDroid/src/main/java/com/ichi2/widget/WidgetConfigScreenAdapter.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/widget/WidgetConfigScreenAdapter.kt b/AnkiDroid/src/main/java/com/ichi2/widget/WidgetConfigScreenAdapter.kt
--- a/AnkiDroid/src/main/java/com/ichi2/widget/WidgetConfigScreenAdapter.kt	(revision 6bf188ae9310a346d87ebfe727cee4c3acd5260b)
+++ b/AnkiDroid/src/main/java/com/ichi2/widget/WidgetConfigScreenAdapter.kt	(date 1722268224881)
@@ -30,9 +30,11 @@
  *
  * @property decks the list of selectable decks to display
  */
-class WidgetConfigScreenAdapter(
-    val decks: MutableList<SelectableDeck>
-) : RecyclerView.Adapter<WidgetConfigScreenAdapter.DeckViewHolder>() {
+class WidgetConfigScreenAdapter : RecyclerView.Adapter<WidgetConfigScreenAdapter.DeckViewHolder>() {
+
+    private val decks: MutableList<SelectableDeck> = mutableListOf()
+    
+    val deckIds get() = decks.map { it.deckId }
 
     class DeckViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
         val deckNameTextView: TextView = itemView.findViewById(R.id.deck_name)
```

2024-07-29 15:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +            val selectedDecksString = sharedPreferences.getString("deck_picker_widget_selected_decks_$appWidgetId", "")
Shouldn't this be in `DeckPickerWidgetPreferences`

2024-07-29 15:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +        getSharedPreferences("DeckPickerWidgetPrefs", Context.MODE_PRIVATE).edit {
Shouldn't this be in `DeckPickerWidgetPreferences`

2024-07-29 15:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +        getSharedPreferences("DeckPickerWidgetPrefs", Context.MODE_PRIVATE)
This does nothing

2024-07-29 15:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +            if (intent?.action == AppWidgetManager.ACTION_APPWIDGET_DELETED) {
invert the `if` to reduce nesting

2024-07-29 16:25 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +class DeckPickerWidget : AppWidgetProvider() {
how do i sync those merged classes in this branch ?

2024-07-29 16:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +class DeckPickerWidget : AppWidgetProvider() {
rebase this branch onto `upstream main` (or sync `origin main` and use it)

2024-07-29 17:24 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +
why so ? curious

2024-07-29 17:26 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +            val selectedDecksString = sharedPreferences.getString("deck_picker_widget_selected_decks_$appWidgetId", "")
you mean `WidgetPreferences`  ?

2024-07-29 18:07 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +            val selectedDecksString = sharedPreferences.getString("deck_picker_widget_selected_decks_$appWidgetId", "")
I'm not at my PC, but I believe the class was named as above

2024-07-30 12:10 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +            applicationScope.launch(Dispatchers.Main) {
`AnkiDroidApp.applicationScope.launch(Dispatchers.Main)` like this ?

2024-07-30 12:19 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +            if (pendingIntent == null) {
When` onUpdate` is called, the code checks if an existing alarm` PendingIntent` is already set for the widget .If an Alarm Already Exists:` PendingIntent.getBroadcast` returns the existing `PendingIntent`, and `pendingIntent `is not `null`. The if block is skipped, and no new alarm is set.

2024-07-30 22:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +            if (pendingIntent == null) {
Sounds good, move the explanation to a comment for others

2024-07-30 22:23 UTC, david-allison requested changes

2024-07-30 22:23 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +    override fun onUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray) {
? why is this being overridden and not `performUpdate`

2024-07-30 22:23 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +            val selectedDecksString = sharedPreferences.getString("deck_picker_widget_selected_decks_$appWidgetId", "")
Yes, `WidgetPreferences`. Why was this marked as resolved?

2024-07-30 22:23 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +                Timber.d("PendingIntent is null, creating a new one for widget ID: $appWidgetId")
This doesn't give context that it's a recurring alarm

2024-07-30 22:23 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +            Timber.tag("DeckPickerWidgetConfig").w("Invalid App Widget ID")
? This is unusual

2024-07-30 22:23 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +        setResult(RESULT_CANCELED)
But isn't `RESULT_CANCELED` the default value

2024-07-30 22:23 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +            if (pendingIntent == null) {
invert the if and return early to reduce nesting

2024-07-30 22:23 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +                Timber.d("PendingIntent already exists for widget ID: $appWidgetId")
```suggestion
                Timber.v("PendingIntent already exists for widget ID: $appWidgetId")
```

2024-07-30 22:23 UTC, david-allison commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck1Name_deck_picker_widget" >Chemistry</string>
```suggestion
    <string name="deck1Name_deck_picker_widget">Chemistry</string>
```

2024-07-30 22:23 UTC, david-allison commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <!--  sample deck names and properties for Deck Picker Widget layout in widget picker screen -->
These need to be in `comment=` attributes for the relevant strings

2024-07-30 22:23 UTC, david-allison commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck_picker_widget_description">Deck Picker</string>
Do we want to overload the name? Are there alternatives?

2024-07-31 17:46 UTC, xenonnn4w commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck_picker_widget_description">Deck Picker</string>
sorry , what overload means here ?

2024-07-31 19:33 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +    override fun onUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray) {
The `onUpdate` method is overridden in the `AnalyticsWidgetProvider` to handle common tasks like checking storage permissions and logging analytics events, before delegating to the abstract `performUpdate` method

2024-07-31 21:54 UTC, david-allison commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck_picker_widget_description">Deck Picker</string>
We already have `DeckPicker.kt`, we don't want to use the name for multiple concepts within the app

2024-07-31 21:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +    override fun onUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray) {
Why aren't we using `performUpdate `?

2024-08-01 14:05 UTC, xenonnn4w commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck_picker_widget_description">Deck Picker</string>
Does the `Deck Widget` work?

2024-08-01 14:29 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +    override fun onUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray) {
oh my bad , updated

2024-08-01 18:54 UTC, david-allison commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck_picker_widget_description">Deck Picker</string>
Sure

2024-08-03 13:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +            applicationScope.launch(Dispatchers.Main) {
I would expect the following, unless `.IO` is necessary

```
Index: AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt b/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
--- a/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt	(revision 420e636102e9be5805c447bb6fb0f896c4f9d140)
+++ b/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt	(date 1722691853062)
@@ -23,11 +23,10 @@
 import android.content.Intent
 import android.os.SystemClock
 import android.widget.RemoteViews
-import com.ichi2.anki.AnkiDroidApp.Companion.applicationScope
+import com.ichi2.anki.AnkiDroidApp
 import com.ichi2.anki.CollectionManager.withCol
 import com.ichi2.anki.R
 import com.ichi2.anki.analytics.UsageAnalytics
-import kotlinx.coroutines.Dispatchers
 import kotlinx.coroutines.launch
 import timber.log.Timber
 import kotlin.time.Duration.Companion.seconds
@@ -80,7 +79,7 @@
         ) {
             val remoteViews = RemoteViews(context.packageName, R.layout.widget_deck_picker_large)
 
-            applicationScope.launch(Dispatchers.IO) {
+            AnkiDroidApp.applicationScope.launch {
                 val deckData = getDeckNameAndStats(deckIds.toList())
 
                 remoteViews.removeAllViews(R.id.deckCollection)


```

2024-08-03 13:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        const val ACTION_APPWIDGET_UPDATE = AppWidgetManager.ACTION_APPWIDGET_UPDATE
comment these two

2024-08-03 13:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +            widgetId: IntArray,
logic: we're being passed in an array and treating it as a single widget

Either:
* update the parameter to be an Int
* update the logic to handle multiple values

2024-08-03 13:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        private fun setRecurringAlarm(context: Context, appWidgetId: Int) {
nit: consider converting `appWidgetId` into a value class/typealias

2024-08-03 13:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +                val appWidgetIds = intent.getIntArrayExtra(AppWidgetManager.EXTRA_APPWIDGET_IDS)
Can this be multiple IDs?

2024-08-03 13:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        appWidgetIds?.forEach { widgetId ->
What about deleting the preferences?

2024-08-03 13:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +        if (deck != null) {
invert the if to reduce nesting

2024-08-03 13:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +            if (deckAdapter.itemCount >= 5) {
extract to a variable and explain why this is 5

2024-08-03 13:38 UTC, david-allison commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck_limit_reached" comment="Message when the deck limit is reached">Only 5 decks can be marked favorite.</string>
Extract `5` to a parameter. Consider making this a `plurals`

2024-08-03 13:38 UTC, david-allison commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="no_favourite_deck_placeholder_description" comment="Description for starting to mark decks as favorites">Start marking decks as favorites using the + icon.</string>
needs some work

2024-08-03 13:38 UTC, david-allison commented on AnkiDroid/src/main/res/values/constants.xml
> +    <string name="deck3Learn_deck_picker_widget">5</string>
Inline these

2024-08-03 13:38 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
> +// TODO : To handle the DeckPickerWidgetConfig
This should be fixed

2024-08-03 19:52 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +                val appWidgetIds = intent.getIntArrayExtra(AppWidgetManager.EXTRA_APPWIDGET_IDS)
yes

2024-08-03 20:20 UTC, xenonnn4w commented on AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
> +// TODO : To handle the DeckPickerWidgetConfig
alr, will work on it!

2024-08-03 20:27 UTC, xenonnn4w commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="no_favourite_deck_placeholder_description" comment="Description for starting to mark decks as favorites">Start marking decks as favorites using the + icon.</string>
sorry , work like ?

2024-08-04 06:55 UTC, xenonnn4w commented on AnkiDroid/src/main/res/values/constants.xml
> +    <string name="deck3Learn_deck_picker_widget">5</string>
if i hardcode them then the `./gradlew lint` fails ! What am I doing wrong?

2024-08-04 15:33 UTC, david-allison commented on AnkiDroid/src/main/res/values/constants.xml
> +    <string name="deck3Learn_deck_picker_widget">5</string>
Ignore lint, since there's no need to translate/mutate these

2024-08-04 15:33 UTC, david-allison commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="no_favourite_deck_placeholder_description" comment="Description for starting to mark decks as favorites">Start marking decks as favorites using the + icon.</string>
Grammar/intention improvements

2024-08-04 22:56 UTC, Arthur-Milchior reviewed
My main concern is the word "favorite". I'm really not sure it's clear in this context. Appart from that, only nits. 
I still had a hard time following everything that was going on, but it's still nicer than you first PR I reviewed.

2024-08-04 22:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +        val MAX_DECKS_ALLOWED = 5 // Maximum number of decks allowed in the widget
I think this would be better at the top of the file, as a constant. So it's very easy to find where to modify it if we realize we want.
Or maybe if we want to cause it to be a function depending on the size of the screen

2024-08-04 22:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <!-- Strings to explain usage in Deck Picker and Card Analysis Extra Widget Configuration screen -->
I don't think there is any "card analysis here" so it should be removed from this comment

2024-08-04 22:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/08-widget.xml
> +        <item quantity="other">Only %d decks can be marked favorite.</item>
I'd expect in English that it should be "marked as favorite".

2024-08-04 22:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck_picker_widget_description">Deck Picker Widget</string>
I doubt that "favorite" is a good word here. At least to me, it's not clear why those decks would be "favorite" in any way. The widget does not even repeat the word "favorite" so there is no way for the user to be sure this is what you'll mean with "favorite"

Given that those strings seems to appear only in the context of the widget, I think it may be enough to call them "selected decks"

2024-08-04 22:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="select_deck_title" comment="Title for Deck Selection Dialog">Mark as Favorite.</string>
I doubt that "favorite" is a good word here. At least to me, it's not clear why those decks would be "favorite" in any way. The widget does not even repeat the word "favorite" so there is no way for the user to be sure this is what you'll mean with "favorite"

Given that those strings seems to appear only in the context of the widget, I think it may be enough to call them "selected decks". 

So 
* Select decks
* Select decks to display in the widgets (this would make it clear what will occurs with the selected decks)
* Select decks with the + icon.
* You can select up to %d decks

2024-08-04 22:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/constants.xml
> +
Please revert

2024-08-04 22:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetPreferences.kt
> + * A class to manage the shared preferences for widget configuration, specifically for the Deck Picker Widget and Card Analysis Widget.
I would prefer if you could not mention card analysis here, and add it when you'll merge the card analysis pr

2024-08-05 07:54 UTC, xenonnn4w commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:previewImage="@drawable/widget_deck_picker_drawable"
I've tried it, but it doesn't load in the widget picker screen for API levels below 31.

2024-08-05 08:09 UTC, xenonnn4w commented on AnkiDroid/src/main/res/drawable/widget_deck_picker_drawable.jpg
I'm not entirely sure what needs improvement in this part. Are you suggesting that I replace the subject names with the names of languages? Specifically, should I select three language names based on the regions where the app has the most users? This way, we can determine which three names to use. Is that correct?

2024-08-05 08:19 UTC, xenonnn4w commented on AnkiDroid/src/main/AndroidManifest.xml
> +        <activity
No, as of now there is only one way to open the configuration screen, which is while adding up the widget to home screen.

2024-08-05 08:31 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> + * No user actions can be performed from this widget as of now; it is for display purposes only.
i understand you completely , but i was unable to find a single widget where we can reconfigure it (to have an ideas how i can implement it here). Apart David proposed a approach on which i worked you can see the result of that [here](<https://discord.com/channels/368267295601983490/1218310931629735966/1255461667807035392>), here the main drawback was it is hampering the simplicity of the widget .

2024-08-05 08:34 UTC, xenonnn4w commented on AnkiDroid/src/main/AndroidManifest.xml
> +        <receiver
Updated the PR description .

2024-08-05 13:50 UTC, xenonnn4w commented on AnkiDroid/src/test/java/com/ichi2/anki/widget/DeckNameAndStatsTest.kt
> +        assertEquals("Child 1", result[1].name) // Changed to truncated name
`Changed to truncated name` refers that the name of the child deck "Deck 1::Child 1" is being truncated to just "Child 1" in the test assertion i.e indicates that the` getDeckNameAndStats` function processes the full deck name by removing the parent deck name part before the "::" delimiter.

2024-08-05 17:25 UTC, david-allison commented on AnkiDroid/src/main/res/drawable/widget_deck_picker_drawable.jpg
I like @Arthur-Milchior's suggestion. Pick 3 dissimilar languages: English and 2 of which which use a non-English script.

Proposal:

* English
* Español
* 日本語

2024-08-05 17:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        when (intent.action) {
Agreed

2024-08-05 18:33 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        when (intent.action) {
how i can send a silent crash report ?

2024-08-05 20:56 UTC, Arthur-Milchior commented
I renamed the PR so that it gets the most important fact first. It's a "deck picker widget". Still left the tag, even if I'm not sure it was needed given we have actual github tag

2024-08-07 13:23 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
> +// TODO : To handle the DeckPickerWidgetConfig
Is any help needed?

2024-08-09 00:10 UTC, david-allison commented
```
ActivityStartupUnderBackupTest > [DeckPickerWidgetConfig] > activityHandlesRestoreBackup[DeckPickerWidgetConfig] FAILED
    java.lang.IllegalArgumentException: Receiver not registered: com.ichi2.widget.DeckPickerWidgetConfig$widgetRemovedReceiver$1@7d8fa84f
        at org.robolectric.shadows.ShadowInstrumentation.unregisterReceiver(ShadowInstrumentation.java:958)
        at org.robolectric.shadows.ShadowContextImpl.unregisterReceiver(ShadowContextImpl.java:332)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:820)
        at com.ichi2.widget.DeckPickerWidgetConfig.onDestroy(DeckPickerWidgetConfig.kt:113)
        at android.app.Activity.performDestroy(Activity.java:8876)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1491)
        at org.robolectric.android.internal.RoboMonitoringInstrumentation.callActivityOnDestroy(RoboMonitoringInstrumentation.java:369)
        at org.robolectric.android.controller.ActivityController.lambda$destroy$13(ActivityController.java:310)
        at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:243)
        at org.robolectric.android.controller.ActivityController.destroy(ActivityController.java:308)
        at com.ichi2.anki.ActivityStartupUnderBackupTest.activityHandlesRestoreBackup(ActivityStartupUnderBackupTest.kt:97)
```

2024-08-09 00:28 UTC, david-allison requested changes
* The default deck isn't handled correctly when a second deck is added
* The widget doesn't refresh if a card is added, showing incorrect values
* There's no 'error' state/visualization if a deck is removed
* The 'remove' icon should probably be a trashcan
* Clicking the decks in the widget does nothing
* There's no "would you like to discard changes" dialog if the user presses 'back'
* (optional) You probably don't want to use the 'empty AnkiDroid box' in the empty state
* The save button feels unusual. At very least make it a Material TextButton + change color to blue
* Deck names should have a little end-padding
  *  And probably show ellipses if truncated

2024-08-10 11:07 UTC, xenonnn4w commented
- The default deck isn't handled correctly when a second deck is added [----]
- The widget doesn't refresh if a card is added, showing incorrect values [----]
- There's no 'error' state/visualization if a deck is removed [DONE]
- The 'remove' icon should probably be a trashcan [DONE]
- Clicking the decks in the widget does nothing [----]
- There's no "would you like to discard changes" dialog if the user presses 'back' [DONE]
- (optional) You probably don't want to use the 'empty AnkiDroid box' in the empty state [DONE]
- The save button feels unusual. At very least make it a Material TextButton + change color to blue [DONE]
- Deck names should have a little end-padding + Bottom-padding [DONE]
- And probably show ellipses if truncated [DONE]

2024-08-13 22:54 UTC, Arthur-Milchior commented
If all decks are already displayed, you remove the + symbol. There is no sense in offering to add a deck when all decks are displayed.


You should not be able to add the same deck multiple time.
Ideally, I'd want you to ensure that in the list to select the deck, decks that are already selected appears as disabled. Taping on them do nothing, and they are gray-ish. However, as it's probably not entirely trivial and we are late, maybe, instead at least ensure that a deck is not added a second time to the list

2024-08-13 22:57 UTC, Arthur-Milchior commented
Let's say you have a deck with a lot of subdecks. Let's say 1::2::3::4::5::6::7::8::9::10. 
In the widget, I believe it's great to see it as 10. It's a small screen, that's totally consistent with the use of widget.
However, in the setting view, I want to see the full name. Use multiple lines if needed. Because there maybe multiple subdeck called 10 and the user must be sure of what is selected

2024-08-13 23:53 UTC, Arthur-Milchior commented
When a deck has no card to review, you should not open the reviewer. It closes itself, that's a bad user experience.

In my opinion, you should behave similarly than the way you behave on the phone's deck picker. That is, you could open the study options, so that the user can decide to do custom study.
Except if the deck is empty, in which case you could display a snackbar/toast "The deck is empty".

If it's too hard, you can postpone those feature request to another PR. But at the very least, don't open

2024-08-14 00:00 UTC, Arthur-Milchior commented
In the configuration view, if I delete two deck one after the other, I got 
```
                                                                                                    java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
                                                                                                    	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
                                                                                                    	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
                                                                                                    	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
                                                                                                    	at java.util.Objects.checkIndex(Objects.java:359)
                                                                                                    	at java.util.ArrayList.remove(ArrayList.java:511)
                                                                                                    	at com.ichi2.widget.WidgetConfigScreenAdapter.removeDeck(WidgetConfigScreenAdapter.kt:73)
                                                                                                    	at com.ichi2.widget.DeckPickerWidgetConfig.onCreate$lambda$0(DeckPickerWidgetConfig.kt:82)
                                                                                                    	at com.ichi2.widget.DeckPickerWidgetConfig.$r8$lambda$pxCTVI6ApIiZ-pYMbnoYNYj8Jqc(Unknown Source:0)
                                                                                                    	at com.ichi2.widget.DeckPickerWidgetConfig$$ExternalSyntheticLambda1.invoke(D8$$SyntheticClass:0)
                                                                                                    	at com.ichi2.widget.WidgetConfigScreenAdapter.onBindViewHolder$lambda$1(WidgetConfigScreenAdapter.kt:60)
                                                                                                    	at com.ichi2.widget.WidgetConfigScreenAdapter.$r8$lambda$vIXDNBTNELT_TUub1kxoZ8M8qZI(Unknown Source:0)
                                                                                                    	at com.ichi2.widget.WidgetConfigScreenAdapter$$ExternalSyntheticLambda1.onClick(D8$$SyntheticClass:0)
                                                                                                    	at android.view.View.performClick(View.java:7659)
                                                                                                    	at android.view.View.performClickInternal(View.java:7636)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:30156)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

I think you should use the deck id instead of the position to decide what to delete. Once you ensure the list contain each deck only one, this will be non ambiguous

2024-08-14 00:05 UTC, Arthur-Milchior commented
Let's say you have four decks and want to show all of them.
You need to click four time on the "+" button, and then select them independently

I think really we should be able to do a multi select. Which would require to have a "confirm" button.
Probably, we would want a "select all" when the number of decks is at most 5 (not counting the potentially empty "Default" deck with id 1)


This should probably remain as a TODO, given that it would require reworking the deck selector

2024-08-14 00:08 UTC, Arthur-Milchior commented
![image](https://github.com/user-attachments/assets/747f28a8-0304-4424-b389-1b63473d825d)
On simulator pixel 2 api 34, the last line is not fully readable. Any idea why?

2024-08-14 00:17 UTC, Arthur-Milchior commented
Your widget has serious problem when permission to access the collection is not granted. 
You get a widget once every minute stating that the collection could not be accessed. if you try to reconfigure the widget, the screen crashes.

I think you should instead replace the widget content by a simple message stating that the data is not available, and clicking on it would open the "AnkiDroid needs some permissions to work" screen. Same if you try to open the configuration view

2024-08-14 00:55 UTC, Arthur-Milchior reviewed
I've only reviewed the deck picker. Already took a lot of time. Going to sleep, but at least you've the start of my review

2024-08-14 00:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +    val newCount: Int
We'll probably want to add a boolean "isEmpty". At least if we consider my remarks to imitate the actual DeckPicker behaviour when you click on an empty deck.

2024-08-14 00:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +         * provided in the `deckIds` array. If any decks are deleted or unavailable,
What do you mean by "unavailable"? 
I could imagine that you lose permission to read the collection; however, in this case, any way, you get no data at all.

2024-08-14 00:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +         * Sets a recurring alarm to update the widget every minute, if necessary.
"if necessary" confused me. I thought you meant that it would do the update if the update is necessary.

Now, I understand you mean that you set the alarm if necessary. I.e. if it's not already set.
Instead, please rephrase it as:
> Ensure a recurring alarm is set to update the widget every minutes.

2024-08-14 00:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +            val alarmManager = context.getSystemService(Context.ALARM_SERVICE) as AlarmManager
Move this below. It's possible we won't even need this value. Let's not get a service unless we're sure we need it

2024-08-14 00:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +            val pendingIntent = PendingIntent.getBroadcast(context, appWidgetId, intent, PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE)
Nit:
Not fan of the code duplication. 
I'd consider having a function that returns the pendingIntent. Probably this function should take a `create: bool` argument to decide whether it uses the UPDATE_CURRENT or the NO_CREATE flag.

I'd also use
` fun alarmManager() = context.GetSystemService(Context.ALARM_SERVICE) as AlarmManager` to avoid duplicating the alarm manager code.

2024-08-14 00:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +                val selectedDeckIds = intent.getLongArrayExtra("deck_picker_widget_selected_deck_ids")
Please extract `deck_picker_widget_selected_deck_ids` to a constant and use it instead. So we're sure there is no typo, and the same value is used in both places

2024-08-14 00:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +                if (appWidgetIds != null && selectedDeckIds != null) {
Please, instead, if any of them are null, do an early return. That's equivalent but avoid code imbrication

2024-08-14 00:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +                val appWidgetIds = intent.getIntArrayExtra(AppWidgetManager.EXTRA_APPWIDGET_IDS)
Can you please add a comment explaining why there is an array of widget ids. I would have expected, given your description, that you'd get a single widget at a time

Do you know how to get multiple widget for the ACTION_APPWIDGET_UPDATE ?

2024-08-14 00:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +                        updateWidget(context, appWidgetManager, appWidgetId, selectedDeckIds)
If we had multiple widget, it mean that you set the same set of selected deck ids for all of them. That does not seems what we would ever want. Or am I missing something?

2024-08-14 00:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        // Ensure context is not null
I don't think this comment is useful. It does not provide any information a kotlin reader wouldn't guess by reading the code

2024-08-14 04:40 UTC, xenonnn4w commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck1Name_deck_picker_widget" comment="Sample deck name for Deck 1 in Deck Picker Widget layout in widget picker">English</string>
@david-allison  what you views over it ?

2024-08-14 04:41 UTC, xenonnn4w commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck1Name_deck_picker_widget" comment="Sample deck name for Deck 1 in Deck Picker Widget layout in widget picker">English</string>
Reason of resolve- duplicated review.

2024-08-14 05:04 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> + * No user actions can be performed from this widget as of now; it is for display purposes only.
my bad, sure thing.

2024-08-14 05:19 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +         * provided in the `deckIds` array. If any decks are deleted or unavailable,
The `updateWidget ` method updates the widget's view with the latest data for the specified decks. It replaces the previous view with entries for each deck ID provided in the `deckIds` array. If any decks are deleted or unavailable, they are simply omitted from the updated view, ensuring only available decks are displayed.

2024-08-14 06:13 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +                val appWidgetIds = intent.getIntArrayExtra(AppWidgetManager.EXTRA_APPWIDGET_IDS)
Yes, the ACTION_APPWIDGET_UPDATE can involve multiple widget instances . When this action is broadcast by the system, it includes an array of widget IDs in the EXTRA_APPWIDGET_IDS extra. This array contains the IDs of all the widget instances that need to be updated.

2024-08-14 06:41 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +                        updateWidget(context, appWidgetManager, appWidgetId, selectedDeckIds)
You're correct that each widget instance can have its own set of independent selected decks. However, in the context of the `ACTION_APPWIDGET_UPDATE ` intent, the assumption is that when multiple widgets are being updated simultaneously, it's typically due to a global change that affects all widgets.

This approach ensures that all widgets are updated with the latest deck information. If each widget had a different set of selected decks, the `ACTION_APPWIDGET_UPDATE` intent would still update all widgets with the most recent data, and each widget would then reflect its own configuration.

If the intention is to maintain unique deck selections for each widget, then the code would need to ensure that each widget's individual settings are preserved and applied . In this case, the current implementation assumes a global update context for consistency across all widgets.

2024-08-14 08:34 UTC, xenonnn4w commented
> If all decks are already displayed, you remove the + symbol. There is no sense in offering to add a deck when all decks are displayed.
> 
> You should not be able to add the same deck multiple time. Ideally, I'd want you to ensure that in the list to select the deck, decks that are already selected appears as disabled. Taping on them do nothing, and they are gray-ish. However, as it's probably not entirely trivial and we are late, maybe, instead at least ensure that a deck is not added a second time to the list

Updated!

2024-08-14 12:32 UTC, xenonnn4w commented
> Let's say you have a deck with a lot of subdecks. Let's say 1::2::3::4::5::6::7::8::9::10. In the widget, I believe it's great to see it as 10. It's a small screen, that's totally consistent with the use of widget. However, in the setting view, I want to see the full name. Use multiple lines if needed. Because there maybe multiple subde

Updated!

2024-08-14 12:33 UTC, xenonnn4w commented
> When a deck has no card to review, you should not open the reviewer. It closes itself, that's a bad user experience.
> 
> In my opinion, you should behave similarly than the way you behave on the phone's deck picker. That is, you could open the study options, so that the user can decide to do custom study. Except if the deck is empty, in which case you could display a snackbar/toast "The deck is empty".
> 
> If it's too hard, you can postpone those feature request to another PR. But at the very least, don't open

Updated!

2024-08-14 14:48 UTC, xenonnn4w commented
> In the configuration view, if I delete two deck one after the other, I got
>....
> I think you should use the deck id instead of the position to decide what to delete. Once you ensure the list contain each deck only one, this will be non ambiguous
Updated!

2024-08-14 14:53 UTC, xenonnn4w commented
> ![image](https://private-user-images.githubusercontent.com/357361/357621384-747f28a8-0304-4424-b389-1b63473d825d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NDIxMTMsIm5iZiI6MTcyMzY0MTgxMywicGF0aCI6Ii8zNTczNjEvMzU3NjIxMzg0LTc0N2YyOGE4LTAzMDQtNDQyNC1iMzg5LTFiNjM0NzNkODI1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxMzIzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjM0YTE4ZDk1MGEyNTUxOWM5ZTE3ZDUzMmJjNjdiMDlmOTY3YzEwZTFhYWQ4NGQxZTMzNDc4ZTA0NjY5MWYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XVi3ANGQ8r_4gQ2Q4ZCdUT7axpt19649xsBqFAAOiCk) On simulator pixel 2 api 34, the last line is not fully readable. Any idea why?

Sorry, it was due to the bad padding.
Resolved now ,
![Screenshot_20240814_202219](https://github.com/user-attachments/assets/f48cc95a-4eee-4aef-9b60-5ab862f35a3d)

2024-08-14 15:08 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +    val newCount: Int
for now, nothing will happen on clicking on the empty deck and due to time constraints `open the study options` is a TODO.

2024-08-14 21:17 UTC, david-allison commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck1Name_deck_picker_widget" comment="Sample deck name for Deck 1 in Deck Picker Widget layout in widget picker">English</string>
1. Don't put `translatable="false"` in a file sent to CrowdIn
2. Do move the listed strings to a non-translatable file
3. Do add `translatable="false"`, either to the strings, or the file (if the XML supports it) - We're using the language names in the language itself. `en -> "English"` is correct in all locales

2024-08-14 21:23 UTC, Arthur-Milchior commented
But, I'd appreciate that instead of "updated", you noted exactly what you did when I offered multiple suggestion.

for example, I suggested removing the "+" symbol when all decks are added.
I tested with only a single deck "a", added it in the config, and the + sign is still here. 
I understand you updated by following other part of the recommendation, still, I'd have appreciatedthat you note explicitly that you only applied part of the suggestion

2024-08-14 21:25 UTC, Arthur-Milchior commented
When my only deck is "default", I can't add it. I see that there are no deck. Even if default is non empty

2024-08-14 21:31 UTC, Arthur-Milchior commented
When there are no decks, appart maybe from the default empty deck, I think the behavior should be different.

Ideally, I'd want the user to be unable to create the widget, given that it's pointless until ankidroid is used. But it does not seems easy to conditionally allow widget creation.
So instead, I think we should have a simple message stating something such as
> This widget require AnkiDroid to be initialized.
> [open ankidroid] 

with a button to open the main app

2024-08-14 21:37 UTC, Arthur-Milchior commented
I think that "save" makes no sense when no deck are selected.
Instead, I think it should be "cancel". 
Actually, I guess it'd be nice to always have a button cancel available. Hopefully that should not be hard to implement something that close the configurator without saving anything.

If you're editing the widget instead of

2024-08-14 21:41 UTC, Arthur-Milchior commented
If you can't ensure that the widget get up to dates data, then I'd appreciate a little "sync" button, to ensure that it gets up to date number.
When I'm "reviewing" on the simulator, and I'm done with a deck, it's kind of frustrating that it apperas to still have cards to be seen right now.

Admittedly, ideally, you should be able to do what you're currently learning to do with other widget, that is, listen to change to the collection, and learn that if the widget is displayed, and it heard that there was change, it should update its values

2024-08-15 07:45 UTC, xenonnn4w commented
> If you're editing the widget instead of creating it, and the list of deck was not empty at start, then it seems really nice to be able to cancel.

Fixed!

2024-08-15 16:09 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck1Name_deck_picker_widget" comment="Sample deck name for Deck 1 in Deck Picker Widget layout in widget picker">English</string>
Then use 12-dont-translate. It already contains the only string we don't want to send to crowdin

2024-08-15 18:21 UTC, xenonnn4w commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:previewImage="@drawable/widget_deck_picker_drawable"
To reduce the size of the jpg, as it is almost convey the same thing. 
I did that, it looks fine in widget picker screen but as soon we hold it and it expands, we can clearly notice the blur effect.

2024-08-15 19:09 UTC, xenonnn4w commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +        3 W * 2H Default
Removed the extra space. 
https://developer.android.com/develop/ui/views/appwidgets/layouts#anatomy_determining_size
i.e. for width `(73n - 16)` where n=3 which leads to 203.
while same for width but i just adjusted it more by testing so that we get the desired widget layout in most of cases.

2024-08-15 20:19 UTC, david-allison commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +        3 W * 2H Default
Move the explanation to a code comment

2024-08-15 20:25 UTC, david-allison commented on AnkiDroid/src/main/AndroidManifest.xml
> +            android:enabled="false">
Remove this, it makes testing harder and we'll merge into production

2024-08-15 20:47 UTC, david-allison requested changes
Give the widget a title

<img width="306" alt="Screenshot 2024-08-15 at 21 27 02" src="https://github.com/user-attachments/assets/901fe5cd-7c4c-4588-abd0-940144e552eb">

----

The drag + drop to replace has no affordances (icomn on the left to indicate it can be moved), and the long-press duration is too long

Drag + Drop should not be enabled if there's one deck

----

Bug:
* I have a deck called "E" in the settings
  * It was blank, but even then it should be displayed
* I added a card

It's not appearing in the widget

<img width="306" alt="Screenshot 2024-08-15 at 21 43 40" src="https://github.com/user-attachments/assets/2bd0be12-df0d-43bf-92c5-8a387112a616">

----

I'm getting logs:

`Unexpected action received: android.appwidget.action.APPWIDGET_UPDATE_OPTIONS`

2024-08-15 20:47 UTC, david-allison commented on AnkiDroid/src/main/res/layout/widget_deck_picker_config.xml
> +                android:id="@+id/done_button"
the text is 'save/cancel', not 'done'

2024-08-15 20:47 UTC, david-allison commented on AnkiDroid/src/main/res/layout/widget_deck_picker_config.xml
> +                android:textSize="20sp" />
I mentioned making it look like the "reset password" button on the sync screen. This has none of the flair which a button needs

```suggestion
            <!-- Save / Cancel -->
            <Button
                android:id="@+id/submit_button"
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:textSize="@dimen/abc_text_size_button_material"
                style="@style/Widget.Material3.Button.TextButton"
                android:singleLine="true"
                android:padding="3dp"
                android:layout_gravity="center"
                android:text="@string/save" />
```

2024-08-15 20:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        ChangeManager.subscribe(this)
Does this subscribe each time `performUpdate` is called? Don't you only want to subscribe once?

2024-08-15 20:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        ChangeManager.clearSubscribers()
This is a method for testing which clears all subscribers. This breaks the app

2024-08-15 21:01 UTC, xenonnn4w commented on AnkiDroid/src/main/res/layout/widget_deck_picker_config.xml
> +                android:textSize="20sp" />
oh, Thanks.

2024-08-16 06:42 UTC, xenonnn4w commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:description="@string/deck_picker_widget_description"
>Give the widget a title

If i replace above by ` android:title="@string/deck_picker_widget_description"` why it still shows the `AnkiDroid` as title.

2024-08-16 09:42 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        ChangeManager.subscribe(this)
Reverted.

2024-08-16 09:42 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        ChangeManager.clearSubscribers()
Reverted.

2024-08-16 09:48 UTC, david-allison requested changes
<img width="400" alt="Screenshot 2024-08-16 at 10 47 53" src="https://github.com/user-attachments/assets/7a833d7f-7d33-4372-8bf9-f03d6fc31d4b">

The snackbar obscures the primary UI elements of the screen

2024-08-16 09:51 UTC, david-allison commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="discard_changes_message">Discard current input?</string>
This should use `DiscardChangesDialog`, where we get the string from the backend

2024-08-16 14:01 UTC, xenonnn4w commented
> The snackbar obscures the primary UI elements of the screen
how i set the snackbar just above the the floating action button ?

2024-08-16 14:35 UTC, david-allison commented
https://github.com/ankidroid/Anki-Android/blob/06e8ac2ef3e0d35fb3efc59aabb38c796b276b04/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt#L297-L300

2024-08-17 23:32 UTC, Arthur-Milchior reviewed
Going to sleep. I've still not reviewed everything.

2024-08-17 23:32 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +    @SuppressLint("DirectSnackbarMakeUsage")
I'd prefer that you add the anchor view as potential parameter of ShowSnackbar

```
Subject: [PATCH] refactor(card-browser): remove unused methods
---
Index: AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt b/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
--- a/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt	(revision 2fafc3d3c1b0acecfb8ce76986898c443eba3d9f)
+++ b/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt	(date 1723936673221)
@@ -109,14 +109,12 @@
 
     @SuppressLint("DirectSnackbarMakeUsage")
     fun showSnackbar(messageResId: Int) {
-        val snackbar = Snackbar.make(
-            findViewById(R.id.widgetConfigContainer),
+        val v : View = findViewById(R.id.widgetConfigContainer)
+       v.showSnackbar(
             getString(messageResId),
-            Snackbar.LENGTH_LONG
-        ).apply {
-            anchorView = findViewById<FloatingActionButton>(R.id.fabWidgetDeckPicker)
-        }
-        snackbar.show()
+            Snackbar.LENGTH_LONG,
+            findViewById<FloatingActionButton>(R.id.fabWidgetDeckPicker)
+        )
     }
 
     // Method to initialize UI components
Index: AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt b/AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt	(revision 2fafc3d3c1b0acecfb8ce76986898c443eba3d9f)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt	(date 1723936673221)
@@ -70,10 +70,11 @@
 fun Activity.showSnackbar(
     @StringRes textResource: Int,
     duration: Int = Snackbar.LENGTH_LONG,
-    snackbarBuilder: SnackbarBuilder? = null
+    anchorView: View? = null,
+    snackbarBuilder: SnackbarBuilder? = null,
 ) {
     val text = getText(textResource)
-    showSnackbar(text, duration, snackbarBuilder)
+    showSnackbar(text, duration, anchorView, snackbarBuilder )
 }
 
 /**
@@ -104,13 +105,14 @@
 fun Activity.showSnackbar(
     text: CharSequence,
     duration: Int = Snackbar.LENGTH_LONG,
-    snackbarBuilder: SnackbarBuilder? = null
+    anchorView: View? = null,
+    snackbarBuilder: SnackbarBuilder? = null,
 ) {
     val view: View? = findViewById(R.id.root_layout) as? CoordinatorLayout
 
     if (view != null) {
         val baseSnackbarBuilder = (this as? BaseSnackbarBuilderProvider)?.baseSnackbarBuilder
-        view.showSnackbar(text, duration) {
+        view.showSnackbar(text, duration, anchorView=anchorView) {
             baseSnackbarBuilder?.invoke(this)
             snackbarBuilder?.invoke(this)
             Timber.d("displayed snackbar: '%s'", text)
@@ -157,10 +159,11 @@
 fun View.showSnackbar(
     @StringRes textResource: Int,
     duration: Int = Snackbar.LENGTH_LONG,
-    snackbarBuilder: SnackbarBuilder? = null
+    anchorView: View? = null,
+    snackbarBuilder: SnackbarBuilder? = null,
 ) {
     val text = resources.getText(textResource)
-    showSnackbar(text, duration, snackbarBuilder)
+    showSnackbar(text, duration, anchorView, snackbarBuilder )
 }
 
 /**
@@ -192,19 +195,24 @@
 fun View.showSnackbar(
     text: CharSequence,
     duration: Int = Snackbar.LENGTH_LONG,
-    snackbarBuilder: SnackbarBuilder? = null
+    anchorView: View? = null,
+    snackbarBuilder: SnackbarBuilder? = null,
 ) {
-    val snackbar = Snackbar.make(this, text, duration)
-    snackbar.setMaxLines(4)
-    snackbar.behavior = SwipeDismissBehaviorFix()
+    Snackbar.make(this, text, duration).apply {
+        this.anchorView = anchorView
+        setMaxLines(4)
+        behavior = SwipeDismissBehaviorFix()
 
-    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
-        snackbar.fixMarginsWhenInsetsChange()
-    }
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
+            fixMarginsWhenInsetsChange()
+        }
 
-    if (snackbarBuilder != null) { snackbar.snackbarBuilder() }
+        if (snackbarBuilder != null) {
+            snackbarBuilder()
+        }
 
-    snackbar.show()
+        show()
+    }
 }
 
 /**
@@ -236,10 +244,11 @@
 fun Fragment.showSnackbar(
     text: CharSequence,
     duration: Int = Snackbar.LENGTH_LONG,
-    snackbarBuilder: SnackbarBuilder? = null
+    anchorView: View? = null,
+    snackbarBuilder: SnackbarBuilder? = null,
 ) {
     val baseSnackbarBuilder = (this as? BaseSnackbarBuilderProvider)?.baseSnackbarBuilder
-    requireActivity().showSnackbar(text, duration) {
+    requireActivity().showSnackbar(text, duration, anchorView=anchorView) {
         baseSnackbarBuilder?.invoke(this)
         snackbarBuilder?.invoke(this)
         Timber.d("displayed snackbar: '%s'", text)
@@ -275,10 +284,11 @@
 fun Fragment.showSnackbar(
     @StringRes textResource: Int,
     duration: Int = Snackbar.LENGTH_LONG,
-    snackbarBuilder: SnackbarBuilder? = null
+    anchorView: View? = null,
+    snackbarBuilder: SnackbarBuilder? = null,
 ) {
     val text = resources.getText(textResource)
-    showSnackbar(text, duration, snackbarBuilder)
+    showSnackbar(text, duration, anchorView, snackbarBuilder )
 }
 
 /* ********************************************************************************************** */
```

2024-08-17 23:32 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +            showSnackbar(message)
You should directly give the string id to `showSnackbar`, otherwise it does not use your function. Same remark below

2024-08-17 23:32 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +    fun showSnackbar(messageResId: Int) {
You're using `showSnackbar` with string. So please create a similar function that text a CharSequence. Otherwise, the anchor view is not used

2024-08-17 23:32 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +        loadDueTree()
But why ? 
Please, ensure your comment explain WHY you do things. I can see that it loads the due tree, that what you wrote. What matters to me is why you need to do that. And honestly, I can't guess it. As far as I can tell, in the configuration, you only need the list of deck.
The variable `dueTree` is used only to check whether the default deck is empty, as far as I can tell. But that can be checked directly using the Decks library.

The "due tree" is only usefel if you need whether cards are due. Otherwise, it contains far too much information, and is costly to compute.
Instead, `col.decks.allNamesAndIds` allow you to directly "skipEmptyDefault". If you set it to True, you'll ensure that you get the list without Default when Default is empty, and you don't need to recode the entire logic here yourself

2024-08-17 23:32 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +        val defaultDeckHasCards = defaultDeck.hasCardsReadyToStudy()
Why do you use "hasCardsReadyToStudy"? We normally don't care whether the cards are ready to study. Maybe the user is done reviewing the default deck for today, we should still be able to add it to the widget

2024-08-18 08:07 UTC, xenonnn4w commented
>What do you mean by "unavailable"
My thought process behind jotting that up as; a deck might be considered unavailable if, for some reason, it can't be accessed at the moment of the widget update. This could happen due to various reasons, such as synchronization issues or temporary loading problems. If you feel this reasoning is not correct, i can reframe that sentence as  ~or unavailable~

2024-08-18 08:13 UTC, xenonnn4w commented
> Please answer my question instead of resolving

I already shifted these string to `constants` with the updated comment message.

2024-08-18 08:48 UTC, xenonnn4w commented
>  I can't figure how to get a ACTION_APPWIDGET_UPDATE with multiple appWidgetIds.
```diff
Index: AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt b/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
--- a/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt	(revision 98a3e7e623ab1775884b8f23e8d7e4d1ba01d5cd)
+++ b/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt	(date 1723970124589)
@@ -285,6 +285,7 @@
             // This action is received when the AppWidgetManager broadcasts an update request.
             // It typically happens when the widget is added, resized, or updated from an external trigger.
             ACTION_APPWIDGET_UPDATE -> {
+                Timber.d("ACTION_APPWIDGET_UPDATE received")
                 val appWidgetManager = AppWidgetManager.getInstance(context)
 
                 /**
@@ -302,33 +303,44 @@
                 val selectedDeckIds = intent.getLongArrayExtra(EXTRA_SELECTED_DECK_IDS)
 
                 if (appWidgetIds == null || selectedDeckIds == null) {
+                    Timber.e("appWidgetIds or selectedDeckIds is null")
                     return
                 }
 
                 for (appWidgetId in appWidgetIds) {
+                    Timber.d("Updating widget with ID: $appWidgetId")
                     updateWidget(context, appWidgetManager, appWidgetId, selectedDeckIds)
                 }
             }
             // This custom action is received to update a specific widget.
             // It is triggered by the setRecurringAlarm method to refresh the widget's data periodically.
             ACTION_UPDATE_WIDGET -> {
+                Timber.d("ACTION_UPDATE_WIDGET received")
                 val appWidgetManager = AppWidgetManager.getInstance(context)
                 val appWidgetId = intent.getIntExtra(AppWidgetManager.EXTRA_APPWIDGET_ID, AppWidgetManager.INVALID_APPWIDGET_ID)
+
                 if (appWidgetId != AppWidgetManager.INVALID_APPWIDGET_ID) {
                     val selectedDeckIds = widgetPreferences.getSelectedDeckIdsFromPreferencesDeckPickerWidget(appWidgetId)
                     if (selectedDeckIds.isNotEmpty()) {
+                        Timber.d("Updating specific widget with ID: $appWidgetId")
                         updateWidget(context, appWidgetManager, appWidgetId, selectedDeckIds)
+                    } else {
+                        Timber.d("No selected decks found for widget ID: $appWidgetId")
                     }
+                } else {
+                    Timber.e("Invalid widget ID received in ACTION_UPDATE_WIDGET")
                 }
             }
             AppWidgetManager.ACTION_APPWIDGET_DELETED -> {
-                val appWidgetId = intent.getIntExtra(
-                    AppWidgetManager.EXTRA_APPWIDGET_ID,
-                    AppWidgetManager.INVALID_APPWIDGET_ID
-                )
+                Timber.d("ACTION_APPWIDGET_DELETED received")
+                val appWidgetId = intent.getIntExtra(AppWidgetManager.EXTRA_APPWIDGET_ID, AppWidgetManager.INVALID_APPWIDGET_ID)
+
                 if (appWidgetId != AppWidgetManager.INVALID_APPWIDGET_ID) {
+                    Timber.d("Deleting widget with ID: $appWidgetId")
                     cancelRecurringAlarm(context, appWidgetId)
                     widgetPreferences.deleteDeckPickerWidgetData(appWidgetId)
+                } else {
+                    Timber.e("Invalid widget ID received in ACTION_APPWIDGET_DELETED")
                 }
             }
             AppWidgetManager.ACTION_APPWIDGET_ENABLED -> {

```
regarding this my logcat was as follows :
https://gist.github.com/xenonnn4w/e87d7e52bdbb22ef24255145743fd27c

2024-08-18 09:55 UTC, Arthur-Milchior commented
Thank you for the patch and the logcat.
I feel like this still does not answer my question. I see a single "Updating widget with ID", which means that the action ACTION_APPWIDGET_UPDATE received a request to update a single widget. Unless I seriously misunderstand what you're doing.

So that still does not let me know how to have ACTION_APPWIDGET_UPDATE with multiple widget id. It does not even tell me that you were succesful in having it.

I see you have multiple ACTION_UPDATE_WIDGET, which is great, and that's what I was expecting

2024-08-18 10:02 UTC, Arthur-Milchior commented
I admit I had not considered syncing. That may lead to some interesting problem.
Because, if you update your widget each time an action occur in the collection, you'll have to update it hundreds of time during the sync process. Which is really not acceptable.
So I guess that you should only do the update after the end of the sync.
The easiest way I see to do that is that, when you hear there is an update to the collection, you don't update immediately. Instead you schedule an update for 0.1 second later. If you hear there are more updates, you cancel the first scheduled update and schedule a new one. This ensure that as long as updated are synced into your local collection, you don't update the widget, and you only update it once the sync is done. 
This is the same process, for example, that @SanjaySargam used in the card template editor to ensure that, while the user type, there are no change in the template previewer, and once the user is done typing the new text is displayed all at once.

2024-08-18 10:08 UTC, Arthur-Milchior commented
> a deck might be considered unavailable if, for some reason, it can't be accessed at the moment of the widget update. This could happen due to various reasons, such as synchronization issues or temporary loading problems. If you feel this reasoning is not correct, i can reframe that sentence as or unavailable

Can you find a way to achieve such a state? Personally, I can't. Even during synchronization, I expect the whole deck collection to be available. Unless the deck was deleted, but in this case, it's not "unavailable" but "deleted". There is no case where during a synchronization it gets deleted and come back later.
If you update the widget mid-sync, in the worst case, some cards will be updated and some will be not updated, which may lead to wrong numbers displayed to the user. Maybe in this case, the deck should be considered "unavailable", so that we don't change the numbers displayed twice. I still have two objections:
* you have not implemented such a feature. It may make sense to implement it, but you have to create it, to ensure that there is a new "unavailable" state
* this would be a pretty bad user experience, to see a deck disappearing and reappearing

2024-08-18 10:12 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck2Name_deck_picker_widget" comment="Similar to the first deck, but in Spanish">Español</string>
@xenonnn4w wrote: 

> I already shifted these string to constants with the updated comment message.

I'd prefer you answer as a reply to my message, so I can keep track of the context of the discussion.

And, yeah, that's great, I'm happy that you followed my recommendation and updated the comment message.
Still, that does not tell me whether you took a look at how crowdin work, which was my initial question. I expect it can be done in less than 20 minute and be quite instructive to understand what the translators will see.
Or you can tell me you already did. For what I know, you may have already participated to some translations. I just don't want the questions to be ignored

2024-08-18 12:08 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +    @SuppressLint("DirectSnackbarMakeUsage")
Thanks.

2024-08-18 14:33 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +    }
Nope, will debug and solve it in my next slot of time, oh sorry i didn't use the word broken but ya i acknowledge that is not working in my list of pending tasks.

2024-08-19 11:53 UTC, david-allison commented
Could you rebase this onto `main` (no conflicts expected), this is using an older version of AGP which adds friction to testing

2024-08-19 11:56 UTC, david-allison commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:description="@string/deck_picker_widget_description"
Other widgets use https://github.com/ankidroid/Anki-Android/blob/1269201d11066c8caf4024491ed0f14974977a43/AnkiDroid/src/main/AndroidManifest.xml#L514, have you tried this?

2024-08-19 11:59 UTC, david-allison requested changes
<img width="425" alt="Screenshot 2024-08-19 at 12 57 30" src="https://github.com/user-attachments/assets/34f44314-d595-4346-81bb-643f62b7e1c3">

I clicked on a deck and I got this:

<details>

```
--------- beginning of kernel
--------- beginning of main
--------- beginning of system
--------- beginning of crash
12:57:01.006 chi2.anki.debu          com.ichi2.anki.debug                 I  Late-enabling -Xcheck:jni
12:57:01.015 chi2.anki.debu          com.ichi2.anki.debug                 I  Unquickening 12 vdex files!
12:57:01.040 chi2.anki.debu          com.ichi2.anki.debug                 I  The ClassLoaderContext is a special shared library.
12:57:01.549 NetworkSecurityConfig   com.ichi2.anki.debug                 D  Using Network Security Config from resource network_security_config debugBuild: true
12:57:01.551 NetworkSecurityConfig   com.ichi2.anki.debug                 D  Using Network Security Config from resource network_security_config debugBuild: true
12:57:01.626 ACRA                    com.ichi2.anki.debug                 I  ACRA is enabled for com.ichi2.anki.debug, initializing...
12:57:01.654 AnkiDroid               com.ichi2.anki.debug                 D  Startup - Application Start
12:57:01.655 AnkiDroidApp            com.ichi2.anki.debug                 I  Timber config: DEBUG
12:57:01.656 UsageAnalytics          com.ichi2.anki.debug                 I  initialize()
12:57:01.656 UsageAnalytics          com.ichi2.anki.debug                 D  App tracking id 'tid' = UA-125800786-1
12:57:01.663 WebViewFactory          com.ichi2.anki.debug                 I  Loading com.google.android.webview version 91.0.4472.114 (code 447211484)
12:57:01.681 chi2.anki.debu          com.ichi2.anki.debug                 I  The ClassLoaderContext is a special shared library.
12:57:01.682 nativeloader            com.ichi2.anki.debug                 D  classloader namespace configured for unbundled product apk. library_path=/product/app/WebViewGoogle64/lib/arm64:/product/app/WebViewGoogle64/WebViewGoogle64.apk!/lib/arm64-v8a:/product/app/TrichromeLibrary64/TrichromeLibrary64.apk!/lib/arm64-v8a:/product/lib64:/system/product/lib64
12:57:01.691 chi2.anki.debu          com.ichi2.anki.debug                 I  The ClassLoaderContext is a special shared library.
12:57:01.692 nativeloader            com.ichi2.anki.debug                 D  classloader namespace configured for unbundled product apk. library_path=/product/app/WebViewGoogle64/lib/arm64:/product/app/WebViewGoogle64/WebViewGoogle64.apk!/lib/arm64-v8a:/product/app/TrichromeLibrary64/TrichromeLibrary64.apk!/lib/arm64-v8a:/product/lib64:/system/product/lib64
12:57:01.701 chi2.anki.debu          com.ichi2.anki.debug                 W  Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)
12:57:01.701 chi2.anki.debu          com.ichi2.anki.debug                 W  Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (greylist, reflection, allowed)
12:57:01.701 chi2.anki.debu          com.ichi2.anki.debug                 W  Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (greylist, reflection, allowed)
12:57:01.701 chi2.anki.debu          com.ichi2.anki.debug                 W  Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)
12:57:01.701 chi2.anki.debu          com.ichi2.anki.debug                 W  Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)
12:57:01.707 cr_LibraryLoader        com.ichi2.anki.debug                 I  Loaded native library version number "91.0.4472.114"
12:57:01.707 cr_CachingUmaRecorder   com.ichi2.anki.debug                 I  Flushed 5 samples from 5 histograms.
12:57:01.709 TetheringManager        com.ichi2.anki.debug                 I  registerTetheringEventCallback:com.ichi2.anki.debug
12:57:01.712 cr_VariationsUtils      com.ichi2.anki.debug                 I  Failed reading seed file "/data/user/0/com.ichi2.anki.debug/app_webview/variations_seed_new"
12:57:01.712 cr_VariationsUtils      com.ichi2.anki.debug                 I  Failed reading seed file "/data/user/0/com.ichi2.anki.debug/app_webview/variations_seed"
12:57:01.712 cr_VariationsUtils      com.ichi2.anki.debug                 I  Requesting new seed from IVariationsSeedServer
12:57:01.732 libc                    com.ichi2.anki.debug                 E  SetHeapTaggingLevel: re-enabling tagging after it was disabled is not supported
12:57:01.751 NetworkSecurityConfig   com.ichi2.anki.debug                 D  No Network Security Config specified, using platform default
12:57:01.751 NetworkSecurityConfig   com.ichi2.anki.debug                 D  No Network Security Config specified, using platform default
12:57:01.752 cr_ChildProcessService  com.ichi2.anki.debug                 I  Creating new ChildProcessService pid=3241
12:57:01.830 GoogleAnalyticsImpl     com.ichi2.anki.debug                 I  Not participating in analytics sample (sample percentage vs random: 10 42)
12:57:01.831 UsageAnalytics          com.ichi2.anki.debug                 I  setOptIn(): from false to false
12:57:01.831 GoogleAnalyticsImpl     com.ichi2.anki.debug                 I  Participating in analytics sample (sample percentage vs random: 10 1)
12:57:01.831 UsageAnalytics          com.ichi2.anki.debug                 D  setOptIn() optIn / sAnalytics.config().enabled(): false/false
12:57:01.831 UsageAnalytics          com.ichi2.anki.debug                 I  setDryRun(): true, warning dryRun is experimental
12:57:01.862 TestUtilsKt             com.ichi2.anki.debug                 D  isRunningAsUnitTest: false
12:57:01.882 NotificationChannels    com.ichi2.anki.debug                 I  Creating notification channel with id/name: General Notifications/AnkiDroid
12:57:01.882 NotificationChannels    com.ichi2.anki.debug                 I  Creating notification channel with id/name: Synchronization/Synchronization
12:57:01.882 NotificationChannels    com.ichi2.anki.debug                 I  Creating notification channel with id/name: Global Reminders/Cards due
12:57:01.882 NotificationChannels    com.ichi2.anki.debug                 I  Creating notification channel with id/name: Deck Reminders/Reminders
12:57:01.883 NotificationChannels    com.ichi2.anki.debug                 I  Creating notification channel with id/name: Scoped Storage/Storage migration
12:57:01.898 AnkiDroidApp            com.ichi2.anki.debug                 I  AnkiDroidApp: Starting Services
12:57:01.898 BootService             com.ichi2.anki.debug                 W  Boot Service did not execute - no permissions
12:57:01.901 TtsVoices               com.ichi2.anki.debug                 D  launching job
12:57:01.901 TtsVoices$...LocalesJob com.ichi2.anki.debug                 D  executing job
12:57:01.902 TtsVoices               com.ichi2.anki.debug                 V  begin TTS creation
12:57:01.907 TextToSpeech            com.ichi2.anki.debug                 I  Sucessfully bound to com.google.android.tts
12:57:01.913 libEGL                  com.ichi2.anki.debug                 D  loaded /vendor/lib64/egl/libEGL_emulation.so
12:57:01.914 libEGL                  com.ichi2.anki.debug                 D  loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
12:57:01.915 libEGL                  com.ichi2.anki.debug                 D  loaded /vendor/lib64/egl/libGLESv2_emulation.so
12:57:01.923 AnkiDroidApp$onCreate   com.ichi2.anki.debug                 I  IntentHandler::onCreate
12:57:01.924 Themes                  com.ichi2.anki.debug                 I  Setting theme to LIGHT
12:57:01.929 IntentHandler           com.ichi2.anki.debug                 V  Intent { act=android.intent.action.MAIN cat=[android.intent.category.MULTIWINDOW_LAUNCHER] flg=0x10000000 cmp=com.ichi2.anki.debug/com.ichi2.anki.IntentHandler }
12:57:01.945 WM-PackageManagerHelper com.ichi2.anki.debug                 D  Skipping [...]

2024-08-19 14:11 UTC, xenonnn4w commented
> Other widgets use...

Oh, Thanks; it worked.

2024-08-19 16:37 UTC, xenonnn4w commented
>I clicked on a deck and I got this:

May be an issue related to a different things. I also had instance where i got there the same error; at that time i'ad 3 emulator launched and in one i deleted a deck, and it hanged got that same.

2024-08-19 19:17 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        updateWidgetFromChanges()
updated.

2024-08-20 14:33 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +        val defaultDeckHasCards = defaultDeck.hasCardsReadyToStudy()
here how i can form a condition that tell me that deck has card (whether reviewed or not)?

2024-08-22 15:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +                val appWidgetIds = intent.getIntArrayExtra(AppWidgetManager.EXTRA_APPWIDGET_IDS)
This still seems unresolved

2024-08-22 15:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +                    if (hasUnsavedChanges) {
The callback should be enabled/disabled based on state, rather than having 'finish' logic inside the callback

For example, calling `finish()` inside the callback means that any other callbacks would not be able to stop the action

See: 

https://github.com/ankidroid/Anki-Android/blob/854f0f6efe54d9225c424181e33836e514a2ffc3/AnkiDroid/src/main/java/com/ichi2/anki/Info.kt#L155

2024-08-22 15:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +        deckAdapter.registerAdapterDataObserver(object : RecyclerView.AdapterDataObserver() {
This method appears to be called multiple times, does this mean we register multiple callbacks?

2024-08-22 15:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +        }
doneButton.isVisible = deckAdapter.itemCount != 0

2024-08-22 15:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +            fab.visibility = if (selectedDeckCount >= MAX_DECKS_ALLOWED || selectedDeckCount >= adjustedTotalSelectableDecks) {
`isVisible`

2024-08-22 17:20 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +        val defaultDeckHasCards = defaultDeck.hasCardsReadyToStudy()
will update the PR with the required code once https://github.com/ankidroid/Anki-Android/pull/16929 this got merged.

2024-08-22 17:23 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt
> +    anchorView: View? = null,
I previously did the way you proposed, but Arthur suggested this way here so i did implemented it https://github.com/ankidroid/Anki-Android/pull/16450#discussion_r1720848814

2024-08-23 12:33 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +         * provided in the `deckIds` array. If any decks are deleted or unavailable,
refactored the documentation.

2024-08-23 23:06 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt
> +    anchorView: View? = null,
If you're referring to what you did when I left the comment, in https://github.com/ankidroid/Anki-Android/pull/16450/files#diff-64bb057fd0487785ccd71390b701838c120c5ddaadbcffc95b23649eb36f0dbdR115 , then no, you didn't do what David proposed.
You even had to use ` @SuppressLint("DirectSnackbarMakeUsage")` because the linter was failing. While, as David shows in his example, the DeckPicker does not need it.

I admit I didn't know about the `baseSnackbarBuilder`. Clearly, copying the DeckPicker is far better.

Given that give the first patch, let me give the correct one
```
Subject: [PATCH] refactor(card-browser): remove unused methods
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt b/AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt	(revision ae8d00a44be9ede2fc0c904f6759785e3ec71f94)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt	(date 1724452597510)
@@ -70,11 +70,10 @@
 fun Activity.showSnackbar(
     @StringRes textResource: Int,
     duration: Int = Snackbar.LENGTH_LONG,
-    anchorView: View? = null,
     snackbarBuilder: SnackbarBuilder? = null
 ) {
     val text = getText(textResource)
-    showSnackbar(text, duration, anchorView, snackbarBuilder)
+    showSnackbar(text, duration, snackbarBuilder)
 }
 
 /**
@@ -105,14 +104,13 @@
 fun Activity.showSnackbar(
     text: CharSequence,
     duration: Int = Snackbar.LENGTH_LONG,
-    anchorView: View? = null,
     snackbarBuilder: SnackbarBuilder? = null
 ) {
     val view: View? = findViewById(R.id.root_layout) as? CoordinatorLayout
 
     if (view != null) {
         val baseSnackbarBuilder = (this as? BaseSnackbarBuilderProvider)?.baseSnackbarBuilder
-        view.showSnackbar(text, duration, anchorView = anchorView) {
+        view.showSnackbar(text, duration) {
             baseSnackbarBuilder?.invoke(this)
             snackbarBuilder?.invoke(this)
             Timber.d("displayed snackbar: '%s'", text)
@@ -159,11 +157,10 @@
 fun View.showSnackbar(
     @StringRes textResource: Int,
     duration: Int = Snackbar.LENGTH_LONG,
-    anchorView: View? = null,
     snackbarBuilder: SnackbarBuilder? = null
 ) {
     val text = resources.getText(textResource)
-    showSnackbar(text, duration, anchorView, snackbarBuilder)
+    showSnackbar(text, duration, snackbarBuilder)
 }
 
 /**
@@ -195,11 +192,9 @@
 fun View.showSnackbar(
     text: CharSequence,
     duration: Int = Snackbar.LENGTH_LONG,
-    anchorView: View? = null,
     snackbarBuilder: SnackbarBuilder? = null
 ) {
     Snackbar.make(this, text, duration).apply {
-        this.anchorView = anchorView
         setMaxLines(4)
         behavior = SwipeDismissBehaviorFix()
 
@@ -244,11 +239,10 @@
 fun Fragment.showSnackbar(
     text: CharSequence,
     duration: Int = Snackbar.LENGTH_LONG,
-    anchorView: View? = null,
     snackbarBuilder: SnackbarBuilder? = null
 ) {
     val baseSnackbarBuilder = (this as? BaseSnackbarBuilderProvider)?.baseSnackbarBuilder
-    requireActivity().showSnackbar(text, duration, anchorView = anchorView) {
+    requireActivity().showSnackbar(text, duration) {
         baseSnackbarBuilder?.invoke(this)
         snackbarBuilder?.invoke(this)
         Timber.d("displayed snackbar: '%s'", text)
@@ -284,11 +278,10 @@
 fun Fragment.showSnackbar(
     @StringRes textResource: Int,
     duration: Int = Snackbar.LENGTH_LONG,
-    anchorView: View? = null,
     snackbarBuilder: SnackbarBuilder? = null
 ) {
     val text = resources.getText(textResource)
-    showSnackbar(text, duration, anchorView, snackbarBuilder)
+    showSnackbar(text, duration, snackbarBuilder)
 }
 
 /* ********************************************************************************************** */
Index: AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt b/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
--- a/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt	(revision ae8d00a44be9ede2fc0c904f6759785e3ec71f94)
+++ b/AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt	(date 1724453954049)
@@ -33,6 +33,7 @@
 import androidx.recyclerview.widget.LinearLayoutManager
 import androidx.recyclerview.widget.RecyclerView
 import com.google.android.material.floatingactionbutton.FloatingActionButton
+import com.google.android.material.snackbar.BaseTransientBottomBar
 import com.google.android.material.snackbar.Snackbar
 import com.ichi2.anki.AnkiActivity
 import com.ichi2.anki.CollectionManager.withCol
@@ -42,6 +43,8 @@
 import com.ichi2.anki.dialogs.DeckSelectionDialog.SelectableDeck
 import com.ichi2.anki.dialogs.DiscardChangesDialog
 import com.ichi2.anki.showThemedToast
+import com.ichi2.anki.snackbar.BaseSnackbarBuilderProvider
+import com.ichi2.anki.snackbar.SnackbarBuilder
 import com.ichi2.anki.snackbar.showSnackbar
 import kotlinx.coroutines.Dispatchers
 import kotlinx.coroutines.launch
@@ -54,7 +57,7 @@
  * User can Select up to 5 decks.
  * User Can remove, reorder decks and reconfigure by holding the widget.
  */
-class DeckPickerWidgetConfig : AnkiActivity(), DeckSelectionListener {
+class DeckPickerWidgetConfig : AnkiActivity(), DeckSelectionListener, BaseSnackbarBuilderProvider {
 
     private var appWidgetId = AppWidgetManager.INVALID_APPWIDGET_ID
     lateinit var deckAdapter: WidgetConfigScreenAdapter
@@ -114,11 +117,9 @@
 
     @SuppressLint("DirectSnackbarMakeUsage")
     fun showSnackbar(message: CharSequence) {
-        val v: View = findViewById(R.id.widgetConfigContainer)
-        v.showSnackbar(
+        showSnackbar(
             message,
-            Snackbar.LENGTH_LONG,
-            findViewById<FloatingActionButton>(R.id.fabWidgetDeckPicker)
+            Snackbar.LENGTH_LONG
         )
     }
 
@@ -208,6 +209,21 @@
         unregisterReceiverSilently(widgetRemovedReceiver)
     }
 
+    override val baseSnackbarBuilder: SnackbarBuilder = {
+        anchorView = findViewById<FloatingActionButton>(R.id.fabWidgetDeckPicker)
+        addCallback(object : BaseTransientBottomBar.BaseCallback<Snackbar>() {
+            var activeSnackBar: Snackbar? = null
+
+            override fun onShown(transientBottomBar: Snackbar?) {
+                activeSnackBar = transientBottomBar
+            }
+
+            override fun onDismissed(transientBottomBar: Snackbar?, event: Int) {
+                activeSnackBar = null
+            }
+        })
+    }
+
     /**
      * Configures the "Done" button based on the number of selected decks.
      *
```

2024-08-23 23:06 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +                val appWidgetIds = intent.getIntArrayExtra(AppWidgetManager.EXTRA_APPWIDGET_IDS)
This is not an answer. It's part of a log. No idea what I'm supposed to do with it. Please don't make me guess, explain and save me time.
`Performing widget update for appWidgetIds` is part of `performUpdate` and my question is about `onReceive` so I fail to see how your log is even relevant.

2024-08-24 01:31 UTC, Arthur-Milchior reviewed
As mentioned on discord:
* This is far far better. I'm happy to see the progress with the update.
* when you sync your collection, the widget is not updated until you make a manual change.

2024-08-24 01:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetAlarm.kt
> +object WidgetAlarm {
Why do you put all of those methods in an object?

2024-08-24 01:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetAlarm.kt
> +        val intent = Intent(context, DeckPickerWidget::class.java).apply {
If this is DeckPickerWidget specific, please ensure it's clear. Because WidgetAlarm seems to be general to all widget.
One way to do it would be to have a subfolder in widget, named "deckpicker", and put all files related to deck picker widget inside of it.

If you plan to reuse it, because this seems useful for the card widget too, it'd be nice if you could try to make it general. You'll probably need to use `private inline fun <reified W:AnalyticsWidgetProvider>`, and ensure that `ACTION_UPDATE_WIDGET` is not DeckPicker specific

2024-08-24 01:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetPreferences.kt
> + * A class to manage the shared preferences for widget configuration, specifically for the Deck Picker Widget.
Same reamk. If it's deck picker specific, it should be clear. Maybe by being in a deckpicker subfolder, or by changing the name

2024-08-24 15:38 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetAlarm.kt
> +        val intent = Intent(context, DeckPickerWidget::class.java).apply {
got this suggestion `Cannot use 'W' as reified type parameter. Use a class instead.`
so the below patch will work to resolve this review 
```diff
Index: AnkiDroid/src/main/java/com/ichi2/widget/WidgetAlarm.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/widget/WidgetAlarm.kt b/AnkiDroid/src/main/java/com/ichi2/widget/WidgetAlarm.kt
--- a/AnkiDroid/src/main/java/com/ichi2/widget/WidgetAlarm.kt	(revision ae8d00a44be9ede2fc0c904f6759785e3ec71f94)
+++ b/AnkiDroid/src/main/java/com/ichi2/widget/WidgetAlarm.kt	(date 1724512605533)
@@ -42,16 +42,18 @@
      *
      * @param context the context of the application
      * @param appWidgetId the ID of the widget
+     * @param widgetClass the class of the widget provider
      * @param create whether to create a new PendingIntent or just retrieve it
      * @return the PendingIntent for the widget
      */
     private fun getPendingIntent(
         context: Context,
         appWidgetId: AppWidgetId,
+        widgetClass: Class<out AnalyticsWidgetProvider>,
         create: Boolean
     ): PendingIntent? {
-        val intent = Intent(context, DeckPickerWidget::class.java).apply {
-            action = DeckPickerWidget.ACTION_UPDATE_WIDGET
+        val intent = Intent(context, widgetClass).apply {
+            action = "${widgetClass.name}.ACTION_UPDATE_WIDGET"
             putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID, appWidgetId)
         }
         return PendingIntent.getBroadcast(
@@ -75,9 +77,14 @@
      *
      * @param context the context of the application
      * @param appWidgetId the ID of the widget
+     * @param widgetClass the class of the widget provider
      */
-    fun setRecurringAlarm(context: Context, appWidgetId: AppWidgetId) {
-        val pendingIntent = getPendingIntent(context, appWidgetId, create = false)
+    fun setRecurringAlarm(
+        context: Context,
+        appWidgetId: AppWidgetId,
+        widgetClass: Class<out AnalyticsWidgetProvider>
+    ) {
+        val pendingIntent = getPendingIntent(context, appWidgetId, widgetClass, create = false)
 
         if (pendingIntent != null) {
             Timber.v("Recurring alarm PendingIntent already exists for widget ID: $appWidgetId")
@@ -87,7 +94,7 @@
         Timber.v("Creating a new recurring alarm PendingIntent for widget ID: $appWidgetId")
 
         val alarmManager = alarmManager(context)
-        val newPendingIntent = getPendingIntent(context, appWidgetId, create = true)
+        val newPendingIntent = getPendingIntent(context, appWidgetId, widgetClass, create = true)
 
         // Set alarm to trigger every 10 minutes
         val TEN_MINUTES_MILLIS = 10.minutes.inWholeMilliseconds
@@ -106,9 +113,14 @@
      *
      * @param context the context of the application
      * @param appWidgetId the ID of the widget
+     * @param widgetClass the class of the widget provider
      */
-    fun cancelRecurringAlarm(context: Context, appWidgetId: AppWidgetId) {
-        val pendingIntent = getPendingIntent(context, appWidgetId, create = true)
+    fun cancelRecurringAlarm(
+        context: Context,
+        appWidgetId: AppWidgetId,
+        widgetClass: Class<out AnalyticsWidgetProvider>
+    ) {
+        val pendingIntent = getPendingIntent(context, appWidgetId, widgetClass, create = true)
         val alarmManager = alarmManager(context)
         Timber.d("Canceling recurring alarm for widget ID: $appWidgetId")
         if (pendingIntent != null) {

```

2024-08-24 16:03 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetPreferences.kt
> + * A class to manage the shared preferences for widget configuration, specifically for the Deck Picker Widget.
No, as it will used for save the preferences of card analysis extra widget.

2024-08-24 16:36 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetAlarm.kt
> +object WidgetAlarm {
Ensure a single instance manages alarms, simplifies the management of alarms.

2024-08-24 20:38 UTC, xenonnn4w commented on AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
> +            get(DeckPickerWidgetConfig::class.java)
This is not possible.

2024-08-24 23:28 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetAlarm.kt
> +object WidgetAlarm {
Sorry but I still don't get it. You never actually use the object as far as I can tell. You only use the methods as if they were static methods. So you could just remove the `object WidgetAlarm{` line and the code would still behave the same way (and remove the pairing `}`)

2024-08-24 23:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +        const val ACTION_UPDATE_WIDGET = "com.ichi2.widget.ACTION_UPDATE_WIDGET"
Is this action specific to deck picker or not?
If Yes, the name should indicate it's related to deck picker.
If no then it should not be defined in the DeckPickerWidget file

2024-08-24 23:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetAlarm.kt
> +        val intent = Intent(context, DeckPickerWidget::class.java).apply {
I'm not a fan of `widgetClass.name` in the string template. Because we need to use it multiple time and it's easy to make a typo. I'd like at least that we have a function that takes the class and generate the string.

But the real question is: do we really need each widget to have an action with a different name? I'd expect that we can use the same name for all widget, which would simplify the code.

In this case, yeah, having the `widgetClass` parameter to create the intent seems to be the right path forward

2024-08-24 23:46 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetPreferences.kt
> + * A class to manage the shared preferences for widget configuration, specifically for the Deck Picker Widget.
Then I don't understand the comment "specifically for the DeckPickerWidget"

If you mean that it's currently used only by the Deck Picker Widget, that's very fine. Don't hesitate to note that this is supposed to evolve. It's okay to write down that something is a work in progress

2024-08-25 12:01 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
> +            get(DeckPickerWidgetConfig::class.java)
Never mind then

2024-08-25 14:03 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +    object ChangeSubscriber : ChangeManager.Subscriber {
Thanks, Done!

2024-08-25 14:26 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +                val appWidgetIds = intent.getIntArrayExtra(AppWidgetManager.EXTRA_APPWIDGET_IDS)
Apologies for the confusion. I just realized my implementation was incorrect, so I've refactored the code.

2024-08-25 14:29 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidget.kt
> +                val appWidgetIds = intent.getIntArrayExtra(AppWidgetManager.EXTRA_APPWIDGET_IDS)
Apologies for the confusion. I just realized my implementation was incorrect, so I've refactored the code.

2024-08-25 14:46 UTC, xenonnn4w commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck2Name_deck_picker_widget" comment="Similar to the first deck, but in Spanish">Español</string>
I apologize for not addressing this sooner; it seems it got lost in the reviews. Yes, I did read the wiki.

2024-08-25 14:47 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +    @SuppressLint("DirectSnackbarMakeUsage")
Done.

2024-08-25 17:28 UTC, Arthur-Milchior reviewed
I still would appreciate the deckpicker specific files to be in a deckpicker subfolder. There are enough of them that it's reasonnable to put them in their own package. It will make code easier to navigate.

Mostly a few nit.
There are a few changes I'd consider doing. But I won't block on them. I'll be fine approving the code once the nits are addressed. I just want you to add TODO for those change I request (unless of course you feel like you can address them without being late on the second widget)

I wonder whether we really need one alarm by widget id. That could simplify the code a little bit. Except that no, we must remove the alarm only when the last widget is deleted.

We are computing the deck tree too often. You compute it once by widget and by notification. It sometime can be slightly expensive, so it'd be nice to ensure that we compute it less often. So that when you observe a change in the collection, if you have 5 widgets, you could ensure to compute the duetree only once, then compute the `DeckPickerWidgetData` for all widgets to update, and finally send those data to each widgets individually.
Note that if you have a single alarm for all widgets, this will also save time there.


I would have loved to ensure that we only update during notification if the widget is actually visible, but it seems there is actually no way to know whether the widget is visible. That's frustrating. But that's a good reason for you not to implement this feature.

2024-08-25 17:28 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/DeckPickerWidgetConfig.kt
> +        return withContext(Dispatchers.IO) {
could you add a comment explaining why the withContext to the Dispatchers.IO?
I admit that is not extremely clear to me.

2024-08-25 17:28 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:minHeight="50dp"
Why don't we use `updatePeriodMillis` instead of having an alarm on 10 minutes ? Seems like it'd do what we want in a simpler way

(I just found it by looking at other widgets)

2024-08-25 17:52 UTC, Arthur-Milchior commented
I just found another bug. But it's a bug we also have with the shortcuts, so I don't think it's blocking this PR.

* open ankidroid
* open a deck A
* go back to android home
* from the widget open a deck b 
* press back

Expected:
* closing the reviewer. Either going back to the deck picker or to android home

Actual result:
* you go back to deck A. But if you try to review, you get "Not at top of the queue" error message



Another bug:

How to reproduce:
* from the widget, open deck B
* press home
* open deck B

Expected:
* you see deck B
Actual:
* you still see deck A

2024-08-25 18:31 UTC, xenonnn4w commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:minHeight="50dp"
I understand. Initially, I had considered this approach, but I wasn't fully confident about handling the widget update, which is why I leaned towards the widget alarm concept. Since the file has already been thoroughly reviewed, I would prefer to stick with that approach. However, if you disagree, I'm open to implementing this too.

2024-08-25 20:45 UTC, xenonnn4w commented
Created an issue for the bug 1 https://github.com/ankidroid/Anki-Android/issues/16956 , while not able to produce the bug 2.

2024-08-26 13:47 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/deckpickerwidget/DeckPickerWidget.kt
> +/*
I personally advised to just name the subfolder `deckpicker`. It’s already clear that it’s a widget given that it’s in the widget subfolder.

2024-08-26 13:47 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:minHeight="50dp"
I’d like you to at least add a TODO. As this would allow to simplify our codebase slightly.
However, I won’t require it during this PR, I don’t want to make you late

2024-08-26 14:15 UTC, david-allison reviewed
Looking great!

Two string changes requested, the rest are non-blocking and should be either quickly fixed, or added as a TODO:

* move the 'remove' icon to the right to make it feel consistent with a material theme
  * Compare with the 'menu' icon on other screens and have the positions match
* The deck picker should hide already selected deck

2024-08-26 14:15 UTC, david-allison commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck_picker_widget_description">Deck Picker Widget</string>
```suggestion
    <string name="deck_picker_widget_description">Deck Picker</string>
```

2024-08-26 14:15 UTC, david-allison commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck_picker_widget_description">Deck Picker Widget</string>
Or "Decks", implementer's choice

2024-08-26 14:15 UTC, david-allison commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="deck_removed_from_widget" comment="Snackbar when deck is removed from widget">Deck Removed</string>
```suggestion
    <string name="deck_removed_from_widget" comment="Snackbar when deck is removed from widget">Deck removed</string>
```

2024-08-26 14:15 UTC, david-allison commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:minHeight="50dp"
I asked about this back in July: https://github.com/ankidroid/Anki-Android/pull/16450#discussion_r1685388020

2024-08-26 14:15 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/widget/deckpicker/DeckPickerWidgetConfigTest.kt
> +        assert(selectedDeckIds.contains(deck1.deckId))
Don't use `assert`, look into how we use `assertThat`

2024-08-26 14:25 UTC, xenonnn4w commented on AnkiDroid/src/main/res/xml/widget_provider_deck_picker.xml
> +    android:minHeight="50dp"
Hmm, I remember; however, as mentioned earlier, I was more confident using the Widget Alarm. For now, I've added a TODO.

2024-08-26 17:13 UTC, david-allison approved these changes
I'm happy, great turn around with this over the past week!

2024-08-26 17:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidget.kt
> +         *       saying "The deck is empty" instead of opening any activity.
Seems to be resolved

2024-08-26 17:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidget.kt
> +            Timber.e("Context is null in onDeleted")
```suggestion
            Timber.w("Context is null in onDeleted")
```

2024-08-26 17:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetAlarm.kt
> +    val TEN_MINUTES_MILLIS = 10.minutes.inWholeMilliseconds
Might want to make this smaller if we know a few operations don't update

2024-08-26 17:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetAlarm.kt
> +    val newPendingIntent = getPendingIntent(context, appWidgetId, widgetClass, create = true)
nit: `?: return` may read better here

2024-08-26 19:57 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetAlarm.kt
> +    val TEN_MINUTES_MILLIS = 10.minutes.inWholeMilliseconds
how small?

2024-08-27 14:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetAlarm.kt
> +    val TEN_MINUTES_MILLIS = 10.minutes.inWholeMilliseconds
1/2 minutes, up to you

2024-08-27 18:02 UTC, Arthur-Milchior approved these changes

2024-08-27 22:26 UTC, merged