20s Timeout in JvmTest and RobolectricTest
ankidroid/Anki-Android pull request #16466
Opened 2024-05-23 20:55 UTC by Aditya13s

## Purpose / Description
The purpose of the PR is to add a 20s timeout in `JvmTest` and `RobolectricTest`

## Fixes
* Fixes #16435

## Approach
Added TimeoutRule from this linked commit. [https://github.com/robolectric/robolectric/commit/5554acdd9c35f15381b0289e0c94f1a08aa39826](url)

## How Has This Been Tested?
Tested this by running it on my local device.

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-05-23 21:53 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
> +    var chain: RuleChain = RuleChain.outerRule(rule)
Is this necessary?

2024-05-24 16:22 UTC, Aditya13s commented on AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
> +    var chain: RuleChain = RuleChain.outerRule(rule)
> Is this necessary?

Yes it is necessary. Without this timeout will not work.

2024-05-24 16:30 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
> +    var chain: RuleChain = RuleChain.outerRule(rule)
This seems to work

```patch
Subject: [PATCH] tests: fix for Kotlin 2.0

The generic needs to apply to both `EmptyApplication` and `AnkiDroidApp`

```
    java.lang.ClassCastException: class com.ichi2.anki.AnkiDroidApp cannot be cast to class java.lang.Void (com.ichi2.anki.AnkiDroidApp is in unnamed module of loader org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader @29f72685; java.lang.Void is in module java.base of loader 'bootstrap')
        at com.ichi2.anki.RobolectricTest.validateRunWithAnnotationPresent(RobolectricTest.kt:439)
        at com.ichi2.anki.RobolectricTest.setUp(RobolectricTest.kt:105)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.ichi2.testutils.FailOnUnhandledExceptionRule$apply$1.evaluate(FailOnUnhandledExceptionRule.kt:57)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:489)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:291)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:104)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```
---
Index: AnkiDroid/src/test/java/com/ichi2/testutils/JvmTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/testutils/JvmTest.kt b/AnkiDroid/src/test/java/com/ichi2/testutils/JvmTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/testutils/JvmTest.kt	(revision ff55b0734a9476912e3285243914974139cb9b99)
+++ b/AnkiDroid/src/test/java/com/ichi2/testutils/JvmTest.kt	(date 1716568138306)
@@ -33,7 +33,6 @@
 import org.junit.Assume
 import org.junit.Before
 import org.junit.Rule
-import org.junit.rules.RuleChain
 import org.junit.rules.TestName
 import org.robolectric.junit.rules.TimeoutRule
 import timber.log.Timber
@@ -41,12 +40,12 @@
 
 open class JvmTest : TestClass {
     @get:Rule
-    val testName = TestName()
-
-    private val rule: TimeoutRule = TimeoutRule.seconds(20)
+    val timeoutRule: TimeoutRule = TimeoutRule.seconds(20)
 
-    @get : Rule
-    var chain: RuleChain = RuleChain.outerRule(rule)
+    @get:Rule
+    val testName = TestName()
+
+
 
     private fun maybeSetupBackend() {
         RustBackendLoader.ensureSetup()
Index: AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt	(revision ff55b0734a9476912e3285243914974139cb9b99)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt	(date 1716568138309)
@@ -95,10 +95,8 @@
     @get:Rule
     val failOnUnhandledExceptions = FailOnUnhandledExceptionRule()
 
-    private val rule: TimeoutRule = TimeoutRule.seconds(20)
-
-    @get : Rule
-    var chain: RuleChain = RuleChain.outerRule(rule)
+    @get:Rule
+    val timeoutRule: TimeoutRule = TimeoutRule.seconds(20)
 
     @Before
     @CallSuper
```

2024-05-24 16:31 UTC, david-allison requested changes
In addition: 20s was too short, change it to a minute

2024-05-24 17:56 UTC, david-allison approved these changes
Looks good, cheers!

2024-05-24 18:35 UTC, Aditya13s commented
> What do you mean testing these classes? These are the base classes for most tests

I initially thought we could directly test this RobolectricTest class, but I now understand, as you mentioned, that this is a base class for tests.

2024-05-25 16:38 UTC, merged