Add support for custom certificate
ankidroid/Anki-Android pull request #16481
Opened 2024-05-26 13:51 UTC by voczi

Copied from https://github.com/ankidroid/Anki-Android/pull/15996
## Purpose / Description
Since the new backend is forced on the newer Ankidroid releases, Android users cannot connect to their self-hosted sync server if it uses a self-signed certificate. The problem should be fixed with this PR. More than willing to accept any changes made to the UI part of this feature, it ain't that pretty.

* https://github.com/ankidroid/Anki-Android/labels/Blocked%20by%20dependency https://github.com/ankidroid/Anki-Android-Backend/pull/357. 

## Fixes
* Fixes #14686 

## Approach
Allow users to specify a custom root certificate to trust (in PEM format) and feed this through the backend.

## How Has This Been Tested?
Took the PEM-formatted root certificate I use for my local servers, and then copied the contents of it into the text field in the custom sync server section. After doing this, I don't get a error message telling me that the sync server certificate has an unknown issuer.

## Learning
[PEM, DER, CRT, and CER: X.509 Encodings and Conversions](https://www.ssl.com/guide/pem-der-crt-and-cer-x-509-encodings-and-conversions/)

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

![Screenshot_20240325_223253](https://github.com/ankidroid/Anki-Android/assets/82241877/b9945e78-ac29-48dc-82c3-9c0d872fcf09)
(sorry for the flashbang)

2024-06-02 12:06 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +var currentCertificate = ""
Is this global variable necessary?

2024-06-02 12:06 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +var currentCertificate = ""
Can this not be a _global_ variable?

2024-06-02 13:09 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +var currentCertificate = ""
Thought so, too, didn't quite understand what purpose it would serve..
Would that change strictly be a matter of cleaner code, or?

2024-06-04 22:02 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +    val customSyncCertificate = preferences.get("customSyncCertificate")
Why not `preferences.getString()`?

2024-06-04 22:02 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +    var CUSTOM_SYNC_CERTIFICATE = ""
In Kotlin, SCREAMING_SNAKE_CASE is used for constants, not `var`s

2024-06-19 17:31 UTC, david-allison requested changes
I trust that the change works, as mentioned in Discord, I won't have the capacity to verify

**Required**

* Documentation + testing of how to remove the certificate
  * If this does work, a comment on the method (un)setting the preference is sufficient
* Docs on whether un-setting the preference uses the empty string, or uses `null` 
* https://github.com/ankitects/anki/commit/9e3a34f17fb18e89853d2b995df2a049294495d4 and/or the Anki Desktop PR in the commit message

**Implementer's choice**
* I don't know what the 'scope' of the variable is within the backend: is it reset when the user changes collection, or would this setting persist until the backend is explicitly closed and opened (for example, if a user changes profile, is this reset?)
  * I would prefer if `var currentSyncCertificate` were moved further down the stack, possibly `CollectionManager` even if it's not **exactly** the right place. Possibly with logic inside `CollectionManager.setCustomCertificate` (if current cert == null, then no-op), which would reduce the code inside `Sync.kt` to 

**Strongly encouraged to disagree here**

```patch
Subject: [PATCH] 
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt	(revision 4537497645db0522d6ee31901e0e5b74851ba8b2)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt	(date 1718818143347)
@@ -66,6 +66,8 @@
 
     private val testMutex = ReentrantLock()
 
+    private var currentSyncCertificate: String? = null
+
     /**
      * Execute the provided block on a serial background queue, to ensure
      * concurrent access does not happen.
@@ -400,4 +402,13 @@
         // as it does not seem to be compatible with the test scheduler
         queue = dispatcher
     }
+    /** TODO: Docs */
+    fun updateCustomCertificate(cert: String?): Boolean {
+        if (cert.isNullOrEmpty() && currentSyncCertificate.isNullOrEmpty()) return true
+
+        // TODO: explain ""
+        return getBackend().setCustomCertificate(cert ?: "").also {
+            currentSyncCertificate = cert
+        }
+    }
 }
Index: AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt b/AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt	(revision 4537497645db0522d6ee31901e0e5b74851ba8b2)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt	(date 1718818143350)
@@ -32,7 +32,6 @@
 import com.ichi2.anki.CollectionManager.withCol
 import com.ichi2.anki.dialogs.DialogHandlerMessage
 import com.ichi2.anki.dialogs.SyncErrorDialog
-import com.ichi2.anki.preferences.get
 import com.ichi2.anki.preferences.sharedPrefs
 import com.ichi2.anki.servicelayer.ScopedStorageService
 import com.ichi2.anki.snackbar.showSnackbar
@@ -64,7 +63,6 @@
     const val CUSTOM_SYNC_URI = "syncBaseUrl"
     const val CUSTOM_SYNC_ENABLED = CUSTOM_SYNC_URI + VersatileTextWithASwitchPreference.SWITCH_SUFFIX
     const val CUSTOM_SYNC_CERTIFICATE = "customSyncCertificate"
-    var currentSyncCertificate = ""
 
     // Used in the legacy schema path
     const val HOSTNUM = "hostNum"
@@ -84,10 +82,7 @@
     val preferences = this.sharedPrefs()
 
     val currentSyncCertificate = preferences.getString(SyncPreferences.CUSTOM_SYNC_CERTIFICATE, null)
-    if (currentSyncCertificate != null && SyncPreferences.currentSyncCertificate != currentSyncCertificate) {
-        CollectionManager.getBackend().setCustomCertificate(currentSyncCertificate)
-        SyncPreferences.currentSyncCertificate = currentSyncCertificate
-    }
+    CollectionManager.updateCustomCertificate(currentSyncCertificate)
 
     val hkey = preferences.getString(SyncPreferences.HKEY, null)
     val resolvedEndpoint = getEndpoint(this)

```

2024-06-20 10:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
> +    fun updateCustomCertificate(cert: String): Boolean {
What does passing in an empty string do? From reading the backend code, it unsets the certificate

2024-06-20 10:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomSyncServerSettingsFragment.kt
> +            if (!CollectionManager.updateCustomCertificate(newCert)) {
Could do with a line explaining what happens when the preference is unset

2024-06-20 11:19 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomSyncServerSettingsFragment.kt
> +            if (!CollectionManager.updateCustomCertificate(newCert)) {
unset is an empty string "", no extra cert is used for TLS validation.
so would you rather want me just explain this above in CollectionManager?

2024-06-20 11:22 UTC, voczi commented
side note: i did think of keeping track of the current cert in the backend code. although, this would mean that we would have to make calls to the backend every single time we have a cert stored. (even if it isn't changed)
not sure how fast calls to the backend are, so i chose to keep track of this in the app itself instead.

2024-06-24 17:30 UTC, david-allison requested changes
Looking good (tested only the dialog, not a custom server accepting the cert)

* The error message for an invalid PEM is truncated due to it being set as the `title` of the `AlertDialog`
* Show some form of confirmation when the certificate is set correctly
* In the comments to this issue, provide a valid PEM which can be used for testing

2024-06-24 17:30 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +    CollectionManager.updateCustomCertificate(currentSyncCertificate!!)
```suggestion
    val currentSyncCertificate = preferences.getString(SyncPreferences.CUSTOM_SYNC_CERTIFICATE, "") ?: ""
    CollectionManager.updateCustomCertificate(currentSyncCertificate)
```

2024-06-24 19:34 UTC, voczi commented
Example of a valid cert: https://cacerts.digicert.com/DigiCertTLSECCP384RootG5.crt.pem (https://www.digicert.com/kb/digicert-root-certificates.htm)

2024-06-24 20:15 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomSyncServerSettingsFragment.kt
> +                }
consider `showSnackbar` (`showThemedToast` if you can't get it working) - we want to inform the user without requiring an action to dismiss it

2024-06-24 20:15 UTC, david-allison requested changes
One more round, sorry for being unclear

2024-06-24 20:15 UTC, david-allison commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="dialog_valid_custom_certificate">Certificate successfully parsed and applied</string>
Just use this in the snackbar/toast

```suggestion
    <string name="dialog_valid_custom_certificate">Certificate successfully applied</string>
```

2024-06-24 20:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomSyncServerSettingsFragment.kt
> +                }
This is an unusual message if the user blanks the dialog

2024-06-25 10:33 UTC, voczi commented
> One more round, sorry for being unclear

No worries, thank you for the suggestions! Should look better now.

2024-06-25 19:43 UTC, david-allison approved these changes
Looks great, cheers!

2024-06-27 17:47 UTC, mikehardy approved these changes
All LGTM - after all the previous rounds I don't see anything to polish
Strings just syncing now, putting this in the merge queue so it goes after strings, then re-sync

2024-06-27 17:49 UTC, mikehardy commented
Another epic yak-shave (next to the release mode instrumented test) BTW, here going all the way upstream in anki then back through ankidroid to expose it, nice

2024-06-27 18:15 UTC, merged