Changed color of the checkbox in alertdialog
ankidroid/Anki-Android pull request #16485
Opened 2024-05-26 23:42 UTC by Thejas775

## Purpose / Description
To change the color of the checkbox in the delete alertbox.

## Fixes
* Fixes #15174

## Approach
I have created a new custom dialog for it.

## How Has This Been Tested?
This has been tested in both the physical device as well as emulator. Please see the attached screenshots below.
![image](https://github.com/ankidroid/Anki-Android/assets/58774753/fb1ae959-eba3-43ac-b99a-10022cc0c223)
![image](https://github.com/ankidroid/Anki-Android/assets/58774753/59040daa-023e-459f-8a8d-4a4f198ad229)

## Learning (optional, can help others)
The await-dialog on default doesn't provide us with changes we need to create a custom dialog for it.

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-05-27 04:44 UTC, neeldoshii commented
I was also trying the same issue, my thought process was to implement  #13878 which will fix two things at once. Implementor Choice

2024-05-27 04:47 UTC, neeldoshii requested changes
Thanks for contributing. 
Left some reviews also code quality test is failing.

2024-05-27 04:47 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomDialogFragment.kt
> +        val builder = AlertDialog.Builder(requireContext(), theme)
We have extension methods `AlertDialogFacade` use that instead of manually adding here.

2024-05-27 04:47 UTC, neeldoshii commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +
Seems unecessary changes over here.

2024-05-27 18:24 UTC, criticalAY commented
thanks! but this is not how we handle AlertDialog changes, see how AlertDialog is used in other places and most likely you will have to check with the styles to handle the issue

2024-05-27 18:30 UTC, Thejas775 commented
> thanks! but this is not how we handle AlertDialog changes, see how AlertDialog is used in other places and most likely you will have to check with the styles to handle the issue

Yes but for changing the color of the checkboxes, we cannot use the default one so that's why I did this.

2024-05-27 18:31 UTC, Thejas775 commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
> +
Yes will do the changes soon.

2024-05-29 16:04 UTC, david-allison reviewed
Is there a reason you can't change the [default] style?

2024-06-05 15:35 UTC, neeldoshii commented
* Let's close this PR as the issue is fixed on #16552

2024-06-05 17:34 UTC, Thejas775 commented
> Is there a reason you can't change the [default] style?

Sorry I was little busy couldn't reply. I guess migrating to material 3 will also work.

2024-06-27 00:52 UTC, closed without merging