UnitTest : String null test for note editor
ankidroid/Anki-Android pull request #16480
Opened 2024-05-26 11:58 UTC by shrutigitte

## Purpose / Description
 Unit Test for note editor

## How Has This Been Tested?
Tested locally all tests passed

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-05-26 14:45 UTC, criticalAY requested changes
Hey, thanks for the contribution, there are some changes that need to be addressed

2024-05-26 14:45 UTC, criticalAY commented on AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
> +            .withFirstField("Test")
The error is always null in this case, hence this test it wrong. You need a value to be assigned first then test it

2024-05-26 19:44 UTC, david-allison approved these changes
Looks great, cheers!

2024-05-26 20:31 UTC, criticalAY approved these changes
LGTM!

2024-05-30 16:58 UTC, mikehardy approved these changes
Nice

2024-05-30 16:58 UTC, merged