Init: Instant note editor activity
ankidroid/Anki-Android pull request #16497
Opened 2024-05-29 12:35 UTC by criticalAY

## Purpose / Description
Setting up the instant note editor activity

## Approach
Using single instance attribute in manifest to clear it from recent task
No task affinity to separate from other tasks
creating custom style for this activity

## How Has This Been Tested?
Activity unit test pass

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-05-29 12:53 UTC, david-allison requested changes
Let's get this in quickly. Few comments

2024-05-29 12:53 UTC, david-allison commented on AnkiDroid/src/main/AndroidManifest.xml
> +            android:exported="true"
False for now, make sure it's not externally usable

2024-05-29 12:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        setContentView(R.layout.activity_instant_note_editor)
Call onDestroy, no point in having this openable and not usable

2024-05-29 13:02 UTC, criticalAY commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="instant_card">Instant card</string>
Used When sharing text via "Share" from context menu/long press from other app to AnkiDroid to create a instant cloze card.

2024-05-29 13:03 UTC, criticalAY commented
`<string name="instant_card">Instant card</string>`
Used When sharing text via "Share" from context menu/long press from other app to AnkiDroid to create a instant cloze card.

2024-05-29 13:10 UTC, david-allison reviewed
@criticalAY Confirm that this isn't user-visible in the relevant menus, and we can get it in

Optional: A developer option to display it would be useful

2024-05-29 13:10 UTC, david-allison commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="instant_card">Instant card</string>
The comment needs to be here.

Explain what it does, and that it doesn't need to be translated literally

2024-05-29 14:49 UTC, david-allison commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="instant_card" comment="Used when sharing text via Share from context menu or long press from other app to AnkiDroid to create a Instant Cloze card.">Instant card</string>
Tell the translator that they do not need to translate literally.

2024-05-29 17:26 UTC, david-allison approved these changes
Cheers!

2024-06-01 11:35 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        if (!ensureStoragePermissions()) {
This needs a Toast to tell the user that the app doesn't have the expected permission. Otherwise it would be very confusing.

2024-06-01 12:10 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        if (!ensureStoragePermissions()) {
It is already doing that. I remember refactoring this code myself

2024-06-01 12:30 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        if (!ensureStoragePermissions()) {
it works as expected 
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/5ed06611-a1cf-4872-ab77-aec1c1bed3b4)

2024-06-01 12:40 UTC, lukstbit approved these changes

2024-06-01 13:45 UTC, merged