feat(new reviewer): implement some of the actions
ankidroid/Anki-Android pull request #16493
Opened 2024-05-27 23:01 UTC by BrayanDSO

## Purpose / Description

On top of #16455

Implement in the new reviewer:
1. Card info
2. Deck Options
3. Add note
4. Edit note
5. Bury
6. Suspend
7. Delete

## Fixes
Part of #14302 

## Approach

In the commits

Note: the `Mark note` menu item is misaligned for some reason and will be fixed later

## How Has This Been Tested?

Emulator 34

[rev2.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/352d9b2f-5728-4fa9-83fe-57144ed16c1f)

[rev21.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/a8801f3c-b402-499c-8cd6-188e2b714f35)

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)
[rev21.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/d681ed1d-10ea-4325-9055-cdd38a2d287a)

2024-05-28 02:26 UTC, snowtimeglass commented
Thank you always for your hard work.

The items of "Flag card" and "Mark note" seems a bit shifted to the left.
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/777812b2-e42f-4d2a-81d7-2488a3a7ed90" width="320px">

2024-05-28 09:12 UTC, BrayanDSO commented
Read the PR description.

2024-05-28 09:49 UTC, snowtimeglass commented
Sorry, my bad. I see.

2024-06-06 22:58 UTC, mikehardy commented
I think it's fine to defer work but I'm afraid of losing track of the state of the work if there are things that look really really close to complete (as much of this does) but has tiny things like two menu items slightly off center

Perhaps a comment on the main port PR (or a checkbox-list in the description?) where tiny things are tracked?

2024-06-07 11:31 UTC, BrayanDSO commented
The important TODOs are documented in the code.

Keeping a separate list would be mostly busywork to me at the moment, since most of the things aren't implemented yet. Maybe when this comes closer to be under a public-available experimental setting.

2024-06-07 11:35 UTC, david-allison approved these changes
Dev-only change. I'm happy

2024-06-12 16:31 UTC, lukstbit requested changes
This is great!
Left some minor nitpicks plus there were changes in the flag area recently and this doesn't build at the moment.

2024-06-12 16:31 UTC, lukstbit commented on AnkiDroid/src/main/res/menu/reviewer2.xml
> +        app:showAsAction="collapseActionView"/>
I would use _never_, I don't think this item needs to be prominent.

2024-06-12 16:31 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
> +    fun handleNoteEditorResult(result: ActivityResult) {
I would pass the booleans values directly to better separate the viewmodel and the android ui classes.

2024-06-12 16:31 UTC, lukstbit commented on AnkiDroid/src/main/res/menu/reviewer2.xml
> +        android:id="@+id/action_add_note"
The add and edit note items are separated, we should probably have them near each other.

2024-06-12 21:47 UTC, BrayanDSO commented on AnkiDroid/src/main/res/menu/reviewer2.xml
> +        app:showAsAction="collapseActionView"/>
The default viewing mode and the order doesn't matter right now because I'm going to implement https://github.com/ankidroid/Anki-Android/issues/16016#issuecomment-2026895574 later

2024-06-12 21:47 UTC, BrayanDSO commented on AnkiDroid/src/main/res/menu/reviewer2.xml
> +        android:id="@+id/action_add_note"
The default viewing mode and the order doesn't matter right now because I'm going to implement https://github.com/ankidroid/Anki-Android/issues/16016#issuecomment-2026895574 later

2024-06-12 22:22 UTC, BrayanDSO commented
This needs me to update the flags to use the custom names.

2024-06-21 17:34 UTC, lukstbit approved these changes
Ok, LGTM!

2024-06-21 17:52 UTC, merged