refactor: extract text/plain as constant
ankidroid/Anki-Android pull request #16518
Opened 2024-05-31 18:30 UTC by shrutigitte

## Purpose / Description
Extracting 'text/plain' as constant and replacing it in the 

## Fixes
* Fixes #16508 

## How Has This Been Tested?
Tested locally and project build successfully

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-05-31 18:46 UTC, david-allison reviewed
@ShridharGoel Was this what you were expecting from your comment?

I would expect this to be outside the `constants.xml`, and just as a bare string (to remove the `Context` dependency)

2024-06-01 21:31 UTC, david-allison requested changes
In addition to Shridhar's comment

2024-06-01 21:31 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/utils/AssetHelperTest.kt
> +        assertThat(AssetHelper.guessMimeType("test.txt"), equalTo(TEXT_PLAIN))
keep this hardcoded as it's a test

2024-06-02 20:03 UTC, david-allison requested changes

2024-06-02 20:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +const val TEXT_PLAIN = "text/plain"
As mentioned in Discord: `AssetHelper.kt`

2024-06-02 20:39 UTC, david-allison approved these changes
if CI passes, I'm happy

2024-06-02 23:28 UTC, criticalAY approved these changes
LGTM!

2024-06-03 07:35 UTC, merged