Fix #15553: Start of Next Day Not Working
ankidroid/Anki-Android pull request #16528
Opened 2024-06-02 11:56 UTC by powy-e

## Purpose / Description
After finishing all cards for a day, changing Start of Next Day to the past and trying to access that same deck would result in a message saying that all cards were finished for the day.
This was due to the fact that the scheduler did not update after the rollover change
Previously, this issue would require restarting anki.

## Fixes
* Fixes #15553

## Approach
_How does this change address the problem?_
`config.set("rollover", hours)` only updates the database, this change will eventually propagate, however the scheduler will not update what cards to show. This is caused by the transaction of config.set not requiring a queue rebuild (as it's only DeckConfig)
By calling `setPreferences(newPrefs)` this will reset scheduler_info as well as a transaction that will require a study queue rebuild.

## How Has This Been Tested?
By following @briankrznarich steps to reproduce the bug, on a physical device (Samsung A33 5G, Android 14)
> * With a rollover of 8pm, finish all cards for the day.
> * On the Deck Summary screen, at 2pm, with all cards finished, set the rollover to noon. (i.e. "the past")
> * On the Deck Screen, newly due cards appear (~500 for me)
> * Tap the deck to start reviewing

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-06-02 12:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +                setPreferences(newPrefs)
Is this necessary?

2024-06-02 12:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +            ChangeManager.notifySubscribers(opChanges { studyQueues = true }, initiator = null)
This looks like the issue, great catch!

2024-06-02 12:13 UTC, david-allison requested changes
Excellent job, thank you!

2024-06-02 12:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +                setPreferences(newPrefs)
Could you add a comment, explaining this issue, as you did in the issue description

2024-06-02 12:17 UTC, BrayanDSO commented
please check if `Undo` works correctly after that

2024-06-02 13:34 UTC, powy-e commented
> please check if `Undo` works correctly after that

It is working like the Anki desktop version does. But it does exhibit a weird behavior.

1 - If my limit of cards is 3 per day
2 - I review all 3 cards for the day
3 - Change the rollover hour to the past
4 - Review 1 card
5 - Undo everything i just did  (1 card review + rollover + 3 cards review)
6 -I can now review 6 cards. (instead of 3)

At first glance this seems to be a bug with the scheduler again, because when I restart AnkiDroid it only lets me review 3

2024-06-02 19:05 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +                // Before we used config.set("rollover", hours) which caused a bug where the study queue was not updated,
Stating how things worked before doesn't help the person who is reading the code now. So the comment isnt necessary

2024-06-02 19:05 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +            ChangeManager.notifySubscribers(opChanges { studyQueues = true }, initiator = null)
Can you use undoableOp {} instead of withCol {} and avoid notifying it manually?

2024-06-02 19:48 UTC, powy-e commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +                // Before we used config.set("rollover", hours) which caused a bug where the study queue was not updated,
I added the comment because I thought that was what David suggested doing. I might have misunderstood, what would you suggest to comment?

2024-06-02 19:49 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +                // Before we used config.set("rollover", hours) which caused a bug where the study queue was not updated,
Nothing, I guess. Commenting it in GitHub probably would answer what David wanted

2024-06-02 19:54 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
>                  scheduleNotification(TimeManager.time, context)
Remove this from inside the `undoableOp` block

2024-06-02 20:05 UTC, powy-e commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +                // Before we used config.set("rollover", hours) which caused a bug where the study queue was not updated,
I decided to leave a shorter comment explaining the reason I used setPreferences, if you think it doesn't make sense to leave it there, I will remove it

2024-06-02 20:19 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +                // Before we used config.set("rollover", hours) which caused a bug where the study queue was not updated,
Every `OpChange`, and therefore every returned value in a `undoableOp` block, notifies all the ChangeManager subscribers so they can handle the change inside `opExecuted`. So here, the DeckPicker is being notified to restart because there was an OpChange.

Since we use `undoableOp` in a lot of places, re-explaining that everywhere isn't necessary, so IMO, the comment should be revmoved.

2024-06-02 20:37 UTC, powy-e commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +            ChangeManager.notifySubscribers(opChanges { studyQueues = true }, initiator = null)
undoableOp didn't work, it was causing the pipeline to fail I've reverted back to withCol

2024-06-03 16:16 UTC, powy-e commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +            ChangeManager.notifySubscribers(opChanges { studyQueues = true }, initiator = null)
I've tried to investigate it further and I did not reach any conclusion, but if undoableOp is used the code just seems to hang forever and never finish

2024-06-03 16:21 UTC, david-allison approved these changes

2024-06-06 13:14 UTC, mikehardy commented
@BrayanDSO looks like this one might be good to go but you had some insightful comments so might good to take another look?

2024-06-07 11:53 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +            ChangeManager.notifySubscribers(opChanges { studyQueues = true }, initiator = null)
This worked for me. Could you test it there?

```kotlin
suspend fun setDayOffset(context: Context, hours: Int) {
            val prefs = withCol { getPreferences() }
            val newPrefs = prefs.copy { scheduling = prefs.scheduling.copy { rollover = hours } }

            undoableOp {
                setPreferences(newPrefs)
            }
            scheduleNotification(TimeManager.time, context)
            Timber.i("set day offset: '%d'", hours)
        }

        suspend fun getDayOffset(): Int {
            return withCol { getPreferences().scheduling.rollover }
        }
```

2024-06-07 12:39 UTC, powy-e commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +            ChangeManager.notifySubscribers(opChanges { studyQueues = true }, initiator = null)
Just retested it with the code you provided, and it still fails the following two tests:
```
PreferencesTest > setDayOffsetSetsConfig FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:94)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at com.ichi2.anki.preferences.PreferencesTest.setDayOffsetSetsConfig(PreferencesTest.kt:100)
```
```
PreferencesTest > testDayOffsetExhaustive FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:94)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at com.ichi2.anki.preferences.PreferencesTest.testDayOffsetExhaustive(PreferencesTest.kt:56)
```

Using breakpoints it seems as tough the function hangs inside undoableOp and never resumes the `setDayOffset` function

2024-06-07 12:50 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +            ChangeManager.notifySubscribers(opChanges { studyQueues = true }, initiator = null)
```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt b/AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt	(revision 80938ec8d474965d572e44e9f7db2f91cc75896a)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt	(date 1717764333149)
@@ -47,6 +47,7 @@
 import com.ichi2.anki.services.BootService.Companion.scheduleNotification
 import com.ichi2.annotations.NeedsTest
 import com.ichi2.libanki.ChangeManager
+import com.ichi2.libanki.undoableOp
 import com.ichi2.libanki.utils.TimeManager
 import com.ichi2.themes.setTransparentStatusBar
 import com.ichi2.utils.getInstanceFromClassName
@@ -238,16 +239,15 @@
             val prefs = withCol { getPreferences() }
             val newPrefs = prefs.copy { scheduling = prefs.scheduling.copy { rollover = hours } }
 
-            withCol {
+            undoableOp {
                 setPreferences(newPrefs)
             }
-
             scheduleNotification(TimeManager.time, context)
-            ChangeManager.notifySubscribers(opChanges { studyQueues = true }, initiator = null)
             Timber.i("set day offset: '%d'", hours)
         }
+
         suspend fun getDayOffset(): Int {
-            return withCol { config.get("rollover") ?: 4 }
+            return withCol { getPreferences().scheduling.rollover }
         }
     }
 }
Index: AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesTest.kt	(revision 80938ec8d474965d572e44e9f7db2f91cc75896a)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesTest.kt	(date 1717764579925)
@@ -53,7 +53,7 @@
 
     @Test
     fun testDayOffsetExhaustive() {
-        runBlocking {
+        runTest {
             for (i in 0..23) {
                 setDayOffset(preferences, i)
                 assertThat(getDayOffset(), equalTo(i))
@@ -64,7 +64,7 @@
     @Test
     @Throws(ConfirmModSchemaException::class)
     fun testDayOffsetExhaustiveV2() {
-        runBlocking {
+        runTest {
             for (i in 0..23) {
                 setDayOffset(preferences, i)
                 assertThat(getDayOffset(), equalTo(i))
@@ -95,9 +95,9 @@
     @Test
     @Throws(ConfirmModSchemaException::class)
     fun setDayOffsetSetsConfig() {
-        val offset = runBlocking { getDayOffset() }
-        assertThat("Default offset should be 4", offset, equalTo(4))
-        runBlocking { setDayOffset(preferences, 2) }
-        assertThat("rollover config should be set to new value", col.config.get("rollover") ?: 4, equalTo(2))
+        runTest {
+            setDayOffset(preferences, 2)
+            assertThat("rollover config should be set to new value", col.config.get("rollover") ?: 4, equalTo(2))
+        }
     }
 }
```

2024-06-07 13:17 UTC, powy-e commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +            ChangeManager.notifySubscribers(opChanges { studyQueues = true }, initiator = null)
I think the problem were the tests. I just pushed, the pipeline should pass now.

2024-06-17 12:11 UTC, mikehardy approved these changes
did my best Brayan impersonation and scanned through all comments and final status of the PR, I believe they are all addressed and yes CI does pass now

2024-06-17 12:26 UTC, merged