[GSoC'24] Add TemplatePreviewerFragment to CardTemplateEditor
ankidroid/Anki-Android pull request #16529
Opened 2024-06-02 15:22 UTC by SanjaySargam

## Purpose / Description
This feature aims to enhance the CardTemplateEditor by adding a TemplatePreviewerFragment. This will allow users to preview card templates in real-time, improving the usability and efficiency of template editing.

## Approach
Steps
1. Attach fragment to activity
2. Load fragment on preview button, performing actions and tab change
3. Remove back button when fragmented
4. Move menu contents to fragment
5. Customize UI

## How Has This Been Tested?
Emulator

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-06-02 20:28 UTC, david-allison commented
```
CardTemplateEditorTest > testDeletePendingAddExistingCardCount FAILED
    java.lang.NullPointerException: null cannot be cast to non-null type androidx.appcompat.app.AlertDialog
        at com.ichi2.anki.RobolectricTest.getAlertDialogText(RobolectricTest.kt:219)
        at com.ichi2.anki.CardTemplateEditorTest.testDeletePendingAddExistingCardCount(CardTemplateEditorTest.kt:467)
```

2024-06-03 03:38 UTC, SanjaySargam commented
![image](https://github.com/ankidroid/Anki-Android/assets/65113071/db747008-6ed6-4d45-8224-0cde788f5526)
@david-allison, AlertDialog is showing as expected. Am I missing something to reproduce it?

2024-06-03 09:51 UTC, david-allison commented
@SanjaySargam run and debug the listed test

2024-06-03 12:42 UTC, SanjaySargam commented
@david-allison I ran this test in main branch, still it fails. There might the issue with test case I think

2024-06-03 13:06 UTC, david-allison commented
CI in main passes. It's likely an issue with this PR

I'm not going to have time to dig deeper today

2024-06-04 11:29 UTC, SanjaySargam commented
@david-allison test fails due to `move menu to fragment` commit. Will you please review it once? I'm not able to figure out

2024-06-04 11:32 UTC, david-allison commented
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/davidallison/.gradle/caches/transforms-4/7abe0f11969f889e91071cf394c241db/transformed/slf4j-timber-3.1-runtime.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/davidallison/.gradle/caches/transforms-4/2942083a1c2f97a1213598d3cb7713d2/transformed/slf4j-timber-3.1/jars/classes.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [com.arcao.slf4j.timber.TimberLoggerFactory]
-- executing test "testDeletePendingAddExistingCardCount"
D/Backend: Opening rust backend with lang=[en-US]
I/Collection: (Re)opening Database: /var/folders/ym/nqynp93d4j74dpzw20sq4wq00000gn/T/robolectric-CardTemplateEditorTest_testDeletePendingAddExistingCardCount12987290836504835394/external-files/Android/data/com.ichi2.anki.debug/AnkiDroid/collection.anki2
I/Themes: Setting theme to LIGHT
I/AnkiDroidApp$onCreate: CardTemplateEditor::onCreate
D/AnkiActivity: AnkiActivity.startLoadingCollection()
D/AnkiActivity: Synchronously calling onCollectionLoaded
I/CardTemplateEditor: CardTemplateEditor:: Card template editor successfully started for model id 1717500700290
D/CardTemplateEditor: Setting starting tab to -1
I/AnkiDroidApp$onCreate: CardTemplateEditor::onStart
I/AnkiDroidApp$onCreate: CardTemplateEditor::onResume
D/UsageAnalytics: sendAnalyticsScreenView(): CardTemplateEditor
D/UsageAnalytics: getOptIn() status: false
I/FragmentLifecycleLogger: CardTemplateEditor::CardTemplateFragment::onAttach
I/FragmentLifecycleLogger: CardTemplateEditor::CardTemplateFragment::onCreate
Invalid ID 0x00000000.
D/CardTemplateNotetype: getTemplate() on ordinal 0
D/CardTemplateNotetype: getTemplate() on ordinal 0
D/CardTemplateNotetype: getTemplate() on ordinal 1
I/FragmentLifecycleLogger: CardTemplateEditor::CardTemplateFragment::onViewCreated
I/FragmentLifecycleLogger: CardTemplateEditor::CardTemplateFragment::onStart
I/FragmentLifecycleLogger: CardTemplateEditor::CardTemplateFragment::onResume
W/View: requestLayout() improperly called by com.google.android.material.tabs.TabLayout$SlidingTabIndicator{4689143b V.ED..... ......ID 0,0-320,48} during layout: running second layout pass
D/CardTemplateNotetype$Companion: isOrdinalPendingAdd() ord 0 is not a pending add
D/CardTemplateNotetype$Companion: isOrdinalPendingAdd() ord 1 is not a pending add
I/CardTemplateEditor: CardTemplateEditor:: Delete template button pressed
D/CardTemplateNotetype: getTemplate() on ordinal 1
D/CardTemplateNotetype$Companion: isOrdinalPendingAdd() ord 1 is not a pending add
D/CardTemplateEditor: Ordinal is not a pending add, so we'll get the current card count for confirmation
I/FragmentLifecycleLogger: CardTemplateEditor::CardTemplateFragment::onAttach
I/FragmentLifecycleLogger: CardTemplateEditor::CardTemplateFragment::onCreate
Invalid ID 0x00000000.
D/CardTemplateNotetype: getTemplate() on ordinal 1
D/CardTemplateNotetype: getTemplate() on ordinal 0
D/CardTemplateNotetype: getTemplate() on ordinal 1
I/FragmentLifecycleLogger: CardTemplateEditor::CardTemplateFragment::onViewCreated
I/FragmentLifecycleLogger: CardTemplateEditor::CardTemplateFragment::onStart
I/FragmentLifecycleLogger: CardTemplateEditor::CardTemplateFragment::onPause
I/FragmentLifecycleLogger: CardTemplateEditor::CardTemplateFragment::onResume
D/RobolectricTest: Calling destroy on controller com.ichi2.anki.CardTemplateEditor@4f81cc8f
I/AnkiDroidApp$onCreate: CardTemplateEditor::onDestroy
I/FragmentLifecycleLogger: CardTemplateEditor::CardTemplateFragment::onStop
I/FragmentLifecycleLogger: CardTemplateEditor::CardTemplateFragment::onViewDestroyed
I/FragmentLifecycleLogger: CardTemplateEditor::CardTemplateFragment::onDestroy
I/FragmentLifecycleLogger: CardTemplateEditor::CardTemplateFragment::onDetach
I/FragmentLifecycleLogger: CardTemplateEditor::CardTemplateFragment::onPause
I/FragmentLifecycleLogger: CardTemplateEditor::CardTemplateFragment::onStop
I/FragmentLifecycleLogger: CardTemplateEditor::CardTemplateFragment::onViewDestroyed
I/FragmentLifecycleLogger: CardTemplateEditor::CardTemplateFragment::onDestroy
I/FragmentLifecycleLogger: CardTemplateEditor::CardTemplateFragment::onDetach
I/RobolectricTest: closeCollection: RobolectricTest: End
I/Collection: Collection closed
-- completed test "testDeletePendingAddExistingCardCount"

java.lang.NullPointerException: null cannot be cast to non-null type androidx.appcompat.app.AlertDialog
	at com.ichi2.anki.RobolectricTest.getAlertDialogText(RobolectricTest.kt:215)
	at com.ichi2.anki.CardTemplateEditorTest.testDeletePendingAddExistingCardCount(CardTemplateEditorTest.kt:467)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at com.ichi2.testutils.FailOnUnhandledExceptionRule$apply$1.evaluate(FailOnUnhandledExceptionRule.kt:57)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:489)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:290)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:104)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

2024-06-04 11:34 UTC, david-allison commented
https://github.com/ankidroid/Anki-Android/blob/9c5ce7cc1e6a6cf5a6beb00a8bbe777ae080251d/AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt#L215 

`getLatestDialog` returns `null` causing the crash

2024-06-04 11:42 UTC, david-allison commented
`!CardTemplateNotetype.isOrdinalPendingAdd(tempModel, ordinal)` is `true` in a 'good' commit

and `false` in a 'bad' commit

@SanjaySargam Next step is for you to figure out why

2024-06-05 16:36 UTC, SanjaySargam commented
@david-allison Finally figured it out

2024-06-08 18:36 UTC, Arthur-Milchior reviewed
Really great PR, thank you very much. I'm happy to see your work going so well, and already having results that'll be visible for the users :D

I tried it on simulator, not chromebook. Still a few issues, that may be resolved in future PR if it's not trivial to solve them here.

On big vertical screen, I think we can keep the buttons for front/back/css even when the keyboard appear on th escreen.
Moreso if you type with the plugged in keyboard, and there is no keyborad on screen. (Actually, the case of using an external keyboard might be true even on small screen)

I am not a fan of refreshing using the eye icon. I think we should follow anki lead and refresh when you are done editing the text for one second. Don't update for each character, but let the user directly see the result of their work.
Admittedly, when you have javascript in your card, that don't always work great. Especially if you have some `alert('foo')` in it. But I assume most people don't do it. And if we get complaint, we may want to consider adding a way to disable the automated refresh. But I suspect for most user, being as WISIWYG as possible will be a nicer experience.

For a reason I've not yet understood, on pixel tablet simulator at least, if you split the screen in two (using android split, to show a second app) and then put ankidroid back in full view mode, you'll get the CSS content that is copied to the front of the currently displayed card.

Plenty of smaller style remarks inside the code. Nothing that should require a lot of works to correct.

My main remark, really, is that I'd want to know in each commit what I'll see. And really, I'm loosing time because most often, I need to read the code in details to understand what the commit title meant. Please, unless your change is really trivial, add a paragraph. Explain what change is visible from the user point of view and how you achieve that change.

2024-06-08 18:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerFragment.kt
> +        fragmented = requireActivity().javaClass == CardTemplateEditor::class.java
I think actually Fragmented should be added to `TemplatePreviewerArguments`.
This is some information that we should now as soon when we open the previewer and is not expceted to change, so it should be set when it's opened.
Also, this seems cleaner. This way, if we ever decide to change the implementation, and use another activity to contain this fragment, the app won't break

2024-06-08 18:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerFragment.kt
> +        if (!fragmented) {
For the sake of readability, I'd generally prefer the `if` not to contains negation.
> If it's fragmented, we want no navigation icon, otherwise ensure that the arrow request the transmit the "back" action to its parent

seems slightly easier to read than 
> If it's not fragmented the arrow request the transmit the "back" action to its parent otherwise , we want no navigation icon

2024-06-08 18:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +        fun setupCommonMenu(menu: Menu) {
Please document your functions.
What is "common" here.

2024-06-08 18:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/layout/template_previewer.xml
> -            <com.google.android.material.appbar.MaterialToolbar
I'd appreciate if your  commit could explain why you replace a Material toolbar by our toolbar. It's not clear to me what change this part of the commit is doing

2024-06-08 18:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +                }
It seems each time you call `loadTemplatePreviewerFragment` you first check whether it's fragmented.
I believe you should change `loadTemplatePreviewerFragment` to `loadTemplatePreviewerFragmentIfFragmented`, and let this method do an early return if the view is not fragmented. It'll reduce the size of the code and the logic to consider in your PR

2024-06-08 18:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/layout/card_template_editor_item.xml
> +        android:background="?attr/alternativeBackgroundColor"
For the last commit, I admit I can't give very much feedback. It's really hard to read xml and state directly whether it's an improvement or not.
I'd appreciate a lot if you could add to your PR screenshot of everything that changed. Since those changes seems to be applied on phone too, it'll be easy to take screenshot of before/after and we can easily see the difference and whether most maintainers agree its an improvement

2024-06-09 13:45 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
>          if (keyCode == KeyEvent.KEYCODE_P) {
Ctrl + P. I tried in Chromebook and it's working as expected

2024-06-09 14:12 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerFragment.kt
> +    private var fragmented = false
> the meaning of fragmented is not exactly the same, as this fragment belongs to a container instead of taking the full screen with a subview

No

It is the flag which indicates whether the screen is x-large or small

2024-06-10 04:45 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerFragment.kt
> +        fragmented = requireActivity().javaClass == CardTemplateEditor::class.java
Really I don't know, I referred it from `StudyOptionsFragment`. 

Which variable type should I use instead of member variable.

2024-06-10 04:54 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerFragment.kt
> +        fragmented = requireActivity().javaClass == CardTemplateEditor::class.java
`???`

Should I put this in comment as it is ?

2024-06-10 04:57 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerFragment.kt
> +        fragmented = requireActivity().javaClass == CardTemplateEditor::class.java
Ok, Should I do this in separate commit or this commit itself?

2024-06-10 06:58 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +        fun setupCommonMenu(menu: Menu) {
Here "common" means this menu will be used in TemplateEditor or in Previewer fragment

2024-06-10 07:19 UTC, SanjaySargam commented on AnkiDroid/src/main/res/layout/template_previewer.xml
> -            <com.google.android.material.appbar.MaterialToolbar
The reason is, in template editor, we have "our toolbar" and I thought, using same toolbar in both screens would be better.
If we don't do that, it will require some more changes like changing background

2024-06-10 07:54 UTC, SanjaySargam commented on AnkiDroid/src/main/res/layout/card_template_editor_item.xml
> +        android:background="?attr/alternativeBackgroundColor"
Ok

2024-06-10 12:44 UTC, SanjaySargam commented
### Light Theme
| Before | After |
|--------|--------|
| ![WhatsApp Image 2024-06-10 at 5 14 55 PM (1)](https://github.com/ankidroid/Anki-Android/assets/65113071/f894cdbb-78dd-497f-b986-d3725b914834) | ![WhatsApp Image 2024-06-10 at 5 14 52 PM (1)](https://github.com/ankidroid/Anki-Android/assets/65113071/dbc22538-4a90-4be6-9d7a-bba55f449b42) |
| ![WhatsApp Image 2024-06-10 at 5 14 55 PM](https://github.com/ankidroid/Anki-Android/assets/65113071/65ac68bc-0241-4b5c-9218-2746795d9626) | ![WhatsApp Image 2024-06-10 at 5 14 52 PM](https://github.com/ankidroid/Anki-Android/assets/65113071/868b30f3-904b-4e7b-a781-8d80358b2328) |

### Plain Theme
| Before | After |
|--------|--------|
| ![WhatsApp Image 2024-06-10 at 5 14 54 PM](https://github.com/ankidroid/Anki-Android/assets/65113071/868b6e2d-a65f-4d1e-9f87-7ff7eab8c03f) | ![WhatsApp Image 2024-06-10 at 5 14 51 PM (1)](https://github.com/ankidroid/Anki-Android/assets/65113071/66a1290c-27f7-44a0-acbf-6bd2f577e341) |
| ![WhatsApp Image 2024-06-10 at 5 14 53 PM (1)](https://github.com/ankidroid/Anki-Android/assets/65113071/09d44c8f-39f6-4f97-b8c6-7d7d6d2c08ac) | ![WhatsApp Image 2024-06-10 at 5 14 51 PM](https://github.com/ankidroid/Anki-Android/assets/65113071/1b01127a-f8dd-47d9-8f43-6677bc7c23ee) | 

### Black Theme
| Before | After |
|--------|--------|
| ![WhatsApp Image 2024-06-10 at 5 14 54 PM (2)](https://github.com/ankidroid/Anki-Android/assets/65113071/4f3f1457-919d-4072-9bc2-46409b376b12) | ![WhatsApp Image 2024-06-10 at 5 14 50 PM (2)](https://github.com/ankidroid/Anki-Android/assets/65113071/fe207720-50c6-4521-860f-aa5d8d2da038) |
| ![WhatsApp Image 2024-06-10 at 5 14 54 PM (1)](https://github.com/ankidroid/Anki-Android/assets/65113071/f4d06e8f-b082-4b76-b02f-23ea37b3c500) | ![WhatsApp Image 2024-06-10 at 5 14 50 PM (1)](https://github.com/ankidroid/Anki-Android/assets/65113071/25b51903-140b-4f6b-a17f-cba44e36a6e3) |

### Dark Theme
| Before | After |
|--------|--------|
| ![WhatsApp Image 2024-06-10 at 5 14 53 PM](https://github.com/ankidroid/Anki-Android/assets/65113071/f18d776d-6d11-4ec0-b576-de69bfc804dc) | ![WhatsApp Image 2024-06-10 at 5 14 50 PM](https://github.com/ankidroid/Anki-Android/assets/65113071/5ca0af6d-4d2a-4d53-8b47-abc5e9cc4600) |
| ![WhatsApp Image 2024-06-10 at 5 14 52 PM (2)](https://github.com/ankidroid/Anki-Android/assets/65113071/fc955b48-45d6-4a31-9b4f-f08e22dca73c) | ![WhatsApp Image 2024-06-10 at 5 14 49 PM](https://github.com/ankidroid/Anki-Android/assets/65113071/fffefa9c-125f-4211-a454-3124ca2080a2) |

2024-06-10 13:04 UTC, SanjaySargam commented
### Tablet

![Screenshot 2024-06-10 6 28 11 PM](https://github.com/ankidroid/Anki-Android/assets/65113071/b0603b74-69ad-4a8f-84e6-4aa858da4612)

![Screenshot 2024-06-10 6 28 34 PM](https://github.com/ankidroid/Anki-Android/assets/65113071/42cb29e6-585f-421d-aa4b-f152ec461690)

![Screenshot 2024-06-10 6 30 42 PM](https://github.com/ankidroid/Anki-Android/assets/65113071/ce01f848-5184-484e-baa4-19e1464cec41)

![Screenshot 2024-06-10 6 27 02 PM](https://github.com/ankidroid/Anki-Android/assets/65113071/40ef484d-d6f3-4be9-b3af-915583ab5969)

2024-06-10 13:15 UTC, david-allison requested changes
While the fragment is loading, there is a flicker where the right side of the screen is white. This is subtle in the video, but much more noticeable in real life

Could this be fixed (either have the screen show a loading bar, or load the fragment immediately, with the card showing a loading screen)

[16529-white.webm](https://github.com/ankidroid/Anki-Android/assets/62114487/8e91bb98-ca3d-4073-9f90-03a6d1666420)

2024-06-10 18:38 UTC, SanjaySargam commented
> For a reason I've not yet understood, on pixel tablet simulator at least, if you split the screen in two (using android split, to show a second app) and then put ankidroid back in full view mode, you'll get the CSS content that is copied to the front of the currently displayed card.

@Arthur-Milchior
Not able to reproduce on physical tablet
[Screen recording 2024-06-11 12.05.26 AM.webm](https://github.com/ankidroid/Anki-Android/assets/65113071/45596d2b-a51c-47c0-80de-c43f3147c1ca)

2024-06-20 07:19 UTC, Arthur-Milchior reviewed
I'm done reviewing for now, I must leave. I'll do the last commits later.
Please re-read all commit messages and documentation. Think about the "it" and whether anything is ambiguous. Whether there is missing context. 

Don't hesitate to write too much. It's not that bad if you write too much, at least, I'll be sure to get all information I need in order to review.

2024-06-20 07:19 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +            if (!templateEditor.fragmented) {
Regarding the message of the fourth commit, please don't use "it" as often.  Clarifies what you refer to

> This commit ensures that the menu will be visible in previewer fragment if it is fragmented

It seems you mean that "it" is the preview fragment. But the previewer can't be fragmented. Instead, you can either state "if it belongs to a fragmented activity". 
By the way, I think that "when" would be more grammatically correct than "if".


> So it will be compatible to use same toolbar on both screens

I've no idea what "it" refers to. I'd expect "it" refers to "Toolbar". But then the end of the sentence makes no sense.

 I think you should do shorter sentences. For example, here, one sentence to explain that you want the same kind of toolbar on both previewer and card template editor. And  in another sentence, state that  you switch from material toolbar to toolbar in the previewer.

2024-06-20 12:22 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +                if (fragmented) {
@Arthur-Milchior 
Oh Sorry, I forget to delete this commit.
Reason: [Commit](https://github.com/ankidroid/Anki-Android/pull/16529/commits/b628699730b7f257af3490a57b5c20fabee0020c)
The above commit will refresh the previewer fragment after one second of text change, so there is no point of loading it manually

2024-06-23 00:35 UTC, Arthur-Milchior reviewed
It really gets better and better, and it gets easier to review, thank you very much.

I'll almost be ready to tap "approve", if not for the fact that, on phone, for some reason, I get the card editor text area to disappear, which render it unusable.
Everything else can be solved later. But this does not seems an acceptable condition for the app.

2024-06-23 00:35 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +                val isTablet = isTablet(requireContext())
![2024-06-23-020159_339x565_scrot](https://github.com/ankidroid/Anki-Android/assets/357361/e21ee4a8-84e5-45fd-9258-c9d603488ec9)
Actually, it seems there is an even worse problem on phone.
Can you please take a look at this ?

2024-06-23 00:35 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/AndroidUiUtils.kt
> +                >= Configuration.SCREENLAYOUT_SIZE_LARGE
Your documentation consider "xlarge" but you use the "large" constant. There seems to be an issue here. 
Also, it'll probably return true on chromebook, which are not tablet.

I think that, if we need this method, you should just name it `isAtLeastXLarge`
Also, you may want to add a comment that state that you have the assumption that, anything whose mask is at least `SCREENLAYOUT_SIZE_XLARGE` will be bigger than x-large.

This seesm to make sense, but I don't see any guarantee in the documentation

2024-06-23 00:35 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +                val isTablet = isTablet(requireContext())
I don't understand why you care about whether it's a "tablet", instead of caring about whether the view is fragmented. 
Can you add a comment explaining why you can't just use `templateEditor.fragmented` here?

2024-06-23 00:35 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +            // Hide preview option if it is fragmented
Still an issue with a "it" that is not very clear

2024-06-23 00:35 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +                private var refreshFragmentRunnable: Runnable? = null
Please document this variable.

2024-06-23 00:35 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +                    refreshFragmentHandler.postDelayed(updateRunnable, 1000)
I'd appreciate if you could move this 1000 into a top level constant. And document that this is the time to wait before we refresh the previewer. 
This way, if we realize that half a second gives a better user experience, it's clear where to change it.

2024-06-23 00:35 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +            if (templateEditor.fragmented) {
It took me some time to understand why this was in the same commit than the auto-refresh. Until I realize that auto-refresh render this pointless.

I'd suggest either splitting it in two commits. Or explaining in the commit message why you put those together

2024-06-23 00:35 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialog.kt
> +        (activity as CardTemplateEditor).loadTemplatePreviewerFragmentIfFragmented()
It seems that inserting a field already cause the text watcher to call `afterTextChanged`. And so this is redundant with the current line. This cause two reloads, which is not pleasant to see.

I'd suggest either:
* removing this line, 
* or, better, ensuring that, in this case, `refreshFragmentRunnable` is set to null

2024-06-23 06:39 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +                    templateEditor.loadTemplatePreviewerFragmentIfFragmented()
`load fragment on tab change` I mean if we change card on leading side then fragment will load and shows the same card

2024-06-23 06:51 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +                val isTablet = isTablet(requireContext())
Sorry, my bad

2024-06-23 08:40 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +                val isTablet = isTablet(requireContext())
> ![2024-06-23-014720_358x561_scrot](https://private-user-images.githubusercontent.com/357361/342004069-815fc832-f912-461b-a30d-62955d277870.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMzAyNTIsIm5iZiI6MTcxOTEyOTk1MiwicGF0aCI6Ii8zNTczNjEvMzQyMDA0MDY5LTgxNWZjODMyLWY5MTItNDYxYi1hMzBkLTYyOTU1ZDI3Nzg3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QwODA1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTExZGExOTk4ODQ5OWUxOTQxOGRjOGQ0MDRkZWY3N2NhMWI2NGY5YTQzYzhhNjQ4OTJhNGIzMWYzZTEyYjI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DmYIWNtixq3GdeoIYnHk-hQE2HnQpmD8w8bzu6NEMHc) There is still a problem with the length of the navigation bar when it's on top of the keyboard.

@Arthur-Milchior I tried a lot to figure out but I didn't able to find why this was happening.

2024-06-26 04:21 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +                val isTablet = isTablet(requireContext())
@Arthur-Milchior This problem is solved by setting `fitsSystemWindows` to false

2024-07-08 13:09 UTC, david-allison commented
This doesn't look good visually

<img width="1282" alt="Screenshot 2024-07-08 at 14 08 35" src="https://github.com/ankidroid/Anki-Android/assets/62114487/2ba7db6b-525c-43a5-9e1c-4406019aa33a">

<img width="1281" alt="Screenshot 2024-07-08 at 14 09 03" src="https://github.com/ankidroid/Anki-Android/assets/62114487/f00e6322-eb4c-46d9-a691-45acea668278">

2024-07-08 18:49 UTC, SanjaySargam commented
@david-allison UI shows fine in my case. I really don't know why this happens in your case. Will you provide debug info?

![WhatsApp Image 2024-07-09 at 12 10 40 AM](https://github.com/ankidroid/Anki-Android/assets/65113071/456d094c-7c35-4f2e-9db0-e014253b53b8)

2024-07-08 20:49 UTC, david-allison commented
```
AnkiDroid Version = 2.19alpha0-debug (bdb2237a77e9617ad6c399c40a82ba65b7d2508e)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = sdk_gphone64_arm64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 14; sdk_gphone64_arm64 Build/UE1A.230829.036.A2; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.133 Safari/537.36

ACRA UUID = 99515b09-738e-4144-9222-9bb532b626f6

FSRS Enabled = false

Crash Reports Enabled = false
```

Should be a standard Google Emulator. Let me know what other diagnostics you want me to run

2024-07-09 14:14 UTC, SanjaySargam commented
@david-allison I figured it out. This happens due to this commit https://github.com/ankidroid/Anki-Android/pull/16529/commits/fd7609ff918c74ccba03056ea3b1ed00327fb992
```kotlin
android:fitsSystemWindows="false"
``` 

if it is set to true :
![image](https://github.com/ankidroid/Anki-Android/assets/65113071/5db698fe-0914-401e-963b-3c845e180adf)

if it is set to false: 
![image](https://github.com/ankidroid/Anki-Android/assets/65113071/7611b7f8-4d81-403d-87f0-2970a24bc277)


Need help. Is there any alternative way to handle both cases? I tried searching google but couldn't find alternative way

2024-07-21 00:14 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +            // Enable menu
I don't think this comment adds a lot. Unless there is a difference between "enable" and "setup" in which case this comment is not clear enough

2024-07-21 00:14 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +                    templateEditor.loadTemplatePreviewerFragmentIfFragmented()
Thank you.
Then, I guess I'd try to do something more succinct, such as:
> Change in card type gets reflected in the previewer

2024-07-25 00:21 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +                if (imeIsVisible && !(templateEditor.fragmented && resources.configuration.orientation == Configuration.ORIENTATION_PORTRAIT)) {
I think you should revert this line.

I spent some time looking at the bottom navigation view.
My understanding is that it was created to be hidden when the keyboard appear. Because the user probably is not considering navigating to another part of the app while entering input. By default, it's expected this get hidden by the keyboard, so there is not even a need to hide it. But we set `android:windowSoftInputMode="stateAlwaysHidden|adjustResize"` which caused it not to be hidden.

It's not ideal, but acceptable to always behave in the same way, even when we have space to do better. I don't think we should block your PR just because of that.

2024-07-25 14:52 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +                if (imeIsVisible && !(templateEditor.fragmented && resources.configuration.orientation == Configuration.ORIENTATION_PORTRAIT)) {
> I think you should revert this line.

@Arthur-Milchior I should delete this commit

2024-07-28 01:00 UTC, Arthur-Milchior approved these changes
Given that all changes I request are documentation, comment and commit message, I'm happy to finally approve this

2024-07-28 10:02 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +                templateEditor.loadTemplatePreviewerFragmentIfFragmented()
To rename/update the tab name

2024-07-29 04:56 UTC, david-allison reviewed
LGTM, let me know:

* Is this to be squash merged, or rebase merged
* When this is ready to merge, my comments are all non-blocking I believe

Thanks!!

2024-07-29 04:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerFragment.kt
> +    private var inFragmentedActivity = false
nitpick, but request:

could you look into turning this into a get-based property. This would significantly reduce the amount of code/complexity in this commit

I suspect it's possible, but don't spend a long time on this

2024-07-29 04:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +                R.id.action_insert_field -> showInsertFieldDialog()
Not part of this PR: would be nice for these to have 'Timber's

2024-07-29 04:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +    var fragmented = false
I don't believe this needs to be public, revert

2024-07-29 04:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +        setNavigationBarColor(R.attr.alternativeBackgroundColor)
This commit message needs work if we're not squashing this

2024-07-29 04:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +        private const val REFRESH_PREVIEW_DELAY = 1000L
What does Anki Desktop use? This feels slow

2024-07-29 04:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +        private const val REFRESH_PREVIEW_DELAY = 1000L
But as above, I'd reduce this to `xxx.milliseconds`

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt	(revision 82bef8d240ba8ec1315c146975e9dbeb3c6a0838)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt	(date 1722228861063)
@@ -67,6 +67,7 @@
 import com.ichi2.anki.previewer.TemplatePreviewerFragment
 import com.ichi2.anki.snackbar.showSnackbar
 import com.ichi2.anki.utils.ext.isImageOcclusion
+import com.ichi2.anki.utils.postDelayed
 import com.ichi2.annotations.NeedsTest
 import com.ichi2.compat.CompatHelper.Companion.getSerializableCompat
 import com.ichi2.libanki.Collection
@@ -89,6 +90,7 @@
 import java.util.regex.Pattern
 import kotlin.math.max
 import kotlin.math.min
+import kotlin.time.Duration.Companion.seconds
 
 /**
  * Allows the user to view the template for the current note type
@@ -1134,8 +1136,8 @@
         private const val EDITOR_START_ORD_ID = "ordId"
         private const val CARD_INDEX = "card_ord"
 
-        // Time to wait before refreshing the previewer, in milliseconds.
-        private const val REFRESH_PREVIEW_DELAY = 1000L
+        /** Time to wait before refreshing the previewer */
+        private val REFRESH_PREVIEW_DELAY = 1.seconds
 
         @Suppress("unused")
         private const val REQUEST_PREVIEWER = 0
```

2024-07-29 11:44 UTC, SanjaySargam commented
> * Is this to be squash merged, or rebase merged

Rebased one

2024-07-29 12:06 UTC, david-allison commented
Needs de-conflicting as well

2024-07-29 12:07 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerFragment.kt
> +    private var inFragmentedActivity = false
Not possible 
coz the value is getting from arguments

2024-08-01 19:08 UTC, david-allison commented
@SanjaySargam If this is being rebased, please fixup the commit messages

After this, I think it will be good to go. I'll do a final review

2024-08-07 13:46 UTC, david-allison commented
@SanjaySargam still pending, should be a quick one

2024-08-07 14:17 UTC, SanjaySargam commented
> @SanjaySargam If this is being rebased, please fixup the commit messages
> 
> After this, I think it will be good to go. I'll do a final review


@david-allison As I know, it didn't harm commit messages. Will you please be specific which commit message?

2024-08-11 19:52 UTC, Arthur-Milchior commented
@david-allison the commit "UI improvements" has more details.
If it's the only change you requested, you should be able to merge it

2024-08-11 19:55 UTC, david-allison approved these changes
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNG9sZTVvbmlteHpvNmpuMnRvOXo1eWhyZnVpMXNmbmtsZmF0eW1qYSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/igR5863TALcSk/giphy.gif)

2024-08-11 20:11 UTC, merged