[GSoC'24] Enhancements: Instant Note Editor Improvements
ankidroid/Anki-Android pull request #16534
Opened 2024-06-03 02:11 UTC by criticalAY

## Purpose / Description
On top of:
* #16393

-> This PR focus on the UI improvements in the instant note editor 
* Use chip drawable to display text in single tap and turn to cloze mode
* Use text normal layout in advanced mode
* Text touch improvements for the input text
* Removing global cloze `var`
* Use view model for shared text retention

## Approach
_How does this change address the problem?_

## How Has This Been Tested?
OnePlus Nord CE

## Learning (optional, can help others)
How to use Image span class and chips inside edit text: 
[Link](https://stackoverflow.com/questions/50574943/how-to-add-chips-from-material-components-library-to-input-field-in-android)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-06-03 19:33 UTC, david-allison reviewed
Looking great!

2024-06-03 19:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/EditTextGestureHelper.kt
> +        return this == ',' || this == '.' || this == ';' || this == '!' || this == '?'
Check unicode groups here, this is English-only

2024-06-03 19:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/EditTextGestureHelper.kt
> +        val actualString = buildString {
unit test if possible

2024-06-03 19:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/EditTextGestureHelper.kt
> +        val suffix = if (end < text.length && text[end].isPunctuation()) text[end].toString() else ""
TODO: I'd love to see more of this in the ViewModel

2024-06-03 19:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/ChipTextWatcher.kt
> +            this@AppCompatEditText.requestLayout()
Maybe:

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/ChipTextWatcher.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/ChipTextWatcher.kt b/AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/ChipTextWatcher.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/ChipTextWatcher.kt	(revision 231e7b227767d065f2cae925a102c77a7343c830)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/ChipTextWatcher.kt	(date 1717441911551)
@@ -62,26 +62,21 @@
         }
 
         override fun afterTextChanged(editable: Editable) {
-            val words = editable.toString().split("\\s+".toRegex())
-            var startIndex = 0
-
+            val wordAndIndexList = editable.toWordAndIndex()
             editable.clearSpans()
-
-            for (word in words) {
-                if (word.isNotEmpty()) {
-                    val chip = ChipDrawable.createFromResource(context, chipResourceId)
-                    chip.text = word
-
-                    chip.setBounds(0, 0, chip.intrinsicWidth, chip.intrinsicHeight)
-                    val span = ChipImageSpan(chip)
-                    editable.setSpan(
-                        span,
-                        startIndex,
-                        startIndex + word.length,
-                        Spanned.SPAN_EXCLUSIVE_EXCLUSIVE
-                    )
-                }
-                startIndex += word.length + 1
+            for ((word, startIndex) in wordAndIndexList) {
+                val chip = ChipDrawable.createFromResource(context, chipResourceId).apply {
+                    text = word
+                    setBounds(0, 0, intrinsicWidth, intrinsicHeight)    
+                }
+                
+                val span = ChipImageSpan(chip)
+                editable.setSpan(
+                    span,
+                    startIndex,
+                    startIndex + word.length,
+                    Spanned.SPAN_EXCLUSIVE_EXCLUSIVE
+                )
             }
             // refresh the layout here
             this@AppCompatEditText.requestLayout()
@@ -91,3 +86,18 @@
 
     return chipTextWatcher
 }
+
+private data class WordAndIndex(val word: String, val index: Int)
+
+private fun Editable.toWordAndIndex(): List<WordAndIndex> {
+    val ret = mutableListOf<WordAndIndex>()
+    val words = this.toString().split("\\s+".toRegex())
+    var startIndex = 0
+    for (word in words) {
+        if (word.isNotEmpty()) {
+            ret.add(WordAndIndex(word, startIndex))
+        }
+        startIndex += word.length + 1
+    }
+    return ret
+}
```

2024-06-03 19:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +                        viewModel.currentClozeNumber.value
optional: you can define `currentClozeNumber` as a get-only property in the ViewModel and use `flowOfCurrentClozeNumber` for the flow

2024-06-03 19:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/ChipImageSpan.kt
> +        if (fm != null) {
invert for clarity

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/ChipImageSpan.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/ChipImageSpan.kt b/AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/ChipImageSpan.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/ChipImageSpan.kt	(revision 231e7b227767d065f2cae925a102c77a7343c830)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/ChipImageSpan.kt	(date 1717443189040)
@@ -33,19 +33,19 @@
         end: Int,
         fm: Paint.FontMetricsInt?
     ): Int {
+        if (fm == null) return drawable.bounds.right
         val drawable = drawable
         val rect = drawable.bounds
-        if (fm != null) {
-            val fmPaint = paint.fontMetricsInt
-            val fontHeight = fmPaint.descent - fmPaint.ascent
-            val drHeight = rect.bottom - rect.top
-            val centerY = fmPaint.ascent + fontHeight / 2
+
+        val fmPaint = paint.fontMetricsInt
+        val fontHeight = fmPaint.descent - fmPaint.ascent
+        val drHeight = rect.bottom - rect.top
+        val centerY = fmPaint.ascent + fontHeight / 2
 
-            fm.ascent = centerY - drHeight / 2
-            fm.top = fm.ascent
-            fm.bottom = centerY + drHeight / 2
-            fm.descent = fm.bottom
-        }
+        fm.ascent = centerY - drHeight / 2
+        fm.top = fm.ascent
+        fm.bottom = centerY + drHeight / 2
+        fm.descent = fm.bottom
         return rect.right
     }
 
```

2024-06-04 21:28 UTC, david-allison requested changes
* tapping a second time on a cloze should remove it and fix numbering
* Incrementing the number should be done by default on every tap
  * If the mode is changed to 'NO_INCREMENT', the number should not be incremented on a tap
  * If the mode is changed

----

* The default mode should be increment per tap

```
This is a note with two deletions -> This is a {{c2::note}} with {{c1::two}} {{c1::deletions}}
```

And the process would be:

* tap change mode
* tap 'two'
* tap 'deletions'
* tap 'change mode'
* tap 'note'
* save

----

Having the chips on an edit text isn't pleasant currently - I don't get feedback on my taps

I don't like the TextView changing as I tap

Some elements are too small: "a" needs a minimum width

The delay from tapping to completing the cloze is too long (noticeable)

2024-06-06 19:50 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +        val pattern = Pattern.compile("\\{\\{c(\\d+)::(.+?)\\}\\}(\\p{Punct})?")
I have made changes here, it will handle them now

2024-06-06 20:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +    fun getWordClozeNumber(word: String): Int? {
I don't believe this will work on duplicated words.

You'll probably find it easier to work by `Word index -> status`, rather than `word -> status`

2024-06-06 20:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +    private fun splitTextPreservingPunctuation(text: String): List<String> {
Are the unit tests thorough for this? Feels complex

2024-06-06 20:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +        val pattern = Pattern.compile("(?<!\\p{Punct})\\s+|(?<=\\p{Punct})(?=\\s)|(?<=\\s)(?=\\p{Punct})")
Extract this outside the method - only compile once

2024-06-06 20:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +        val pattern = Pattern.compile("\\{\\{c(\\d+)::([^}]+?)\\}\\}(\\p{Punct})?")
ditto

2024-06-06 20:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +        _currentClozeNumber.value = 0
`c0` is not valid (and I don't think this is needed)

2024-06-06 22:26 UTC, david-allison requested changes
Needs regression test:

* tap `You`
* tap Edit
* tap Edit again

A blank space chip is shown

2024-06-07 23:41 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +    fun getWordClozeNumber(word: String): Int? {
Meaning?

2024-06-08 17:15 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +    fun getWordClozeNumber(word: String): Int? {
I have made changes to the code this one too

2024-06-09 19:40 UTC, david-allison requested changes
Only small changes, this looks AWESOME

2024-06-09 19:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/EditorChips.kt
> +    val chipsData = words.mapIndexed { _, word ->
why are you using `mapIndexed` and then discarding the index?

2024-06-09 19:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/EditorChips.kt
> +    var clozeNumber: Int?
document what `null` means

2024-06-09 19:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +    fun getWordClozeNumber(word: String): Int? {
add a doc-comment with an example

I presume this is: `{{c1::text}}` -> `1`

2024-06-09 19:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +    fun getCleanClozeWords(word: String): String {
docs: what is clean?

2024-06-09 19:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
> +    private fun checkClozeAndUndo(text: String): String? {
document this and see if you can remove the 'and' from the name by refactoring the method

2024-06-09 19:40 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt
> +        assertEquals(expectedCloze, result)
(optional/nitpick) - For brevity, I prefer inlining `expectedCloze` into the `assert`

2024-06-09 19:40 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt
> +        )
Mentoring, general learning, not for this PR: have a quick look at parameterized tests. 

Especially how this test would look in C# using `NUnit`: https://stackoverflow.com/a/4818524/13121290

2024-06-10 17:18 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/EditorChips.kt
> +    val chipsData = words.mapIndexed { _, word ->
Was experimenting earlier forgot to update here

2024-06-10 17:44 UTC, criticalAY commented on AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt
> +        )
will do in future

2024-06-10 21:26 UTC, david-allison approved these changes
Everything I expected from the project and more! 

Works incredibly. Well done!!!

2024-06-14 22:26 UTC, merged

2024-06-14 22:30 UTC, david-allison commented
🎉🎉🎉