Make permission item fully touchable
ankidroid/Anki-Android pull request #16535
Opened 2024-06-03 07:49 UTC by gayatriii0803

## Purpose / Description
In PermissionActivity, the permission item is not fully touchable, unlike in the settings.

## Approach
setOnClickListener on root layout.

## How Has This Been Tested?
Emulator.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-06-03 08:52 UTC, criticalAY commented
If you are setting the onClick listener to the root layout, then it would be best to remove the redundant code from the switch listener ?

2024-06-06 10:23 UTC, gayatriii0803 commented
> did you test if the switch is unchecked when declined?

Yes

2024-06-07 11:50 UTC, BrayanDSO requested changes
If the whole element is going to be a touch area, it needs some kind of visual feedback, like a Setting does.

2024-06-07 17:06 UTC, criticalAY requested changes
As I said earlier the views need to be merged, right now the switch if tapped does nothing, the linear layout takes to the permission screen but the switch 
Here the view are independent:
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/4d16b1b0-6767-49af-9716-e02f39a118cd)

2024-06-11 06:45 UTC, gayatriii0803 commented
@criticalAY  I don't understand will you please explain what actually i have to do.

2024-06-11 08:41 UTC, criticalAY commented
Tap the switch, nothing happens. It will work only if you tap the layout i.e. the switch/layout should both be tappable and lead to same action

2024-07-06 10:41 UTC, gayatriii0803 commented
I request maintainers to open this PR and review

2024-07-10 11:31 UTC, criticalAY commented
Comments need to be resolved

2024-07-23 09:31 UTC, gayatriii0803 commented
@criticalAY Comment already resolve kindly check once again.

2024-08-03 17:56 UTC, david-allison commented
@criticalAY

2024-08-03 20:05 UTC, criticalAY approved these changes
Works as expected!

2024-08-26 23:44 UTC, BrayanDSO commented
Repeating myself:

> If the whole element is going to be a touch area, it needs some kind of visual feedback, like a Setting does.

2024-09-26 18:54 UTC, gayatriii0803 commented
Please reopen this PR

2024-09-27 11:34 UTC, gayatriii0803 commented
it needs some kind of visual feedback, like a Setting does
@BrayanDSO What do you mean by visual feedback? I don't understand. Will you please explain again?

2024-09-29 22:03 UTC, BrayanDSO commented
When you press a setting, there's a gray animation that flows like a wave that acts as feedback. So, something like that.

2024-09-30 03:25 UTC, david-allison commented
The wave is called a 'ripple' in Material Design

2024-09-30 05:59 UTC, gayatriii0803 commented
@BrayanDSO @david-allison Already there

2024-09-30 18:33 UTC, david-allison requested changes
The ripple on the setting has inconsistent padding.

There is empty space at the top. This does not exist on the bottom and should do

Approximation:

<img width="390" alt="Screenshot 2024-09-30 at 19 33 51" src="https://github.com/user-attachments/assets/9366b6fb-3c0b-4e6d-95ea-928ca031b37e">

2024-09-30 21:25 UTC, david-allison approved these changes

2024-10-05 08:36 UTC, merged