[GSoC'24] Analytical widget provider class for Deck Picker Widget .
ankidroid/Anki-Android pull request #16545
Opened 2024-06-04 14:23 UTC by xenonnn4w

update

## Purpose / Description
Adding Up Analytical widget provider class for Deck Picker Widget .

## How Has This Been Tested?
https://github.com/ankidroid/Anki-Android/pull/16450

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-06-04 14:40 UTC, david-allison commented
Are you not going to use this with our current classes?

2024-06-04 17:03 UTC, xenonnn4w commented
> You should use this with our current classes

Sorry, didn't understand what you meant by that

2024-06-04 18:10 UTC, david-allison commented
<img width="1176" alt="Screenshot 2024-06-04 at 19 08 30" src="https://github.com/ankidroid/Anki-Android/assets/62114487/5be8b9ec-04d0-4b89-96d2-54f948d2dc8f">

Two widget classes appear to be using this functionality and have duplicated code.
You're planning on adding a third which also uses this functionality, so the concern was extracted to a class

You should add the class which you've created into the inheritance hierarchy for the two other classes to reduce complexity

2024-06-05 05:57 UTC, david-allison requested changes

2024-06-05 05:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
>          if (!grantedStoragePermissions(context, showToast = false)) {
I don't beleive `performUpdate` is called if this condition is false

2024-06-05 05:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
>          if (!IntentHandler.grantedStoragePermissions(context, showToast = false)) {
ditto

2024-06-05 10:15 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
>          if (!grantedStoragePermissions(context, showToast = false)) {
sorry , not able to figure out what exactly i've do here

2024-06-05 10:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
>          if (!grantedStoragePermissions(context, showToast = false)) {
If `onUpdate` in the base class doesn't call `performUpdate` if a condition is met, you don't need to check for it again in the subclass

2024-06-05 17:33 UTC, david-allison approved these changes
LGTM, cheers

2024-06-10 23:36 UTC, Arthur-Milchior commented
I don't understand you "how has this been tested" section. Can you please explain how the link refers to tests ?

2024-06-11 00:07 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +    override fun onUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray) {
I'm sorry, but I'd love to understand when the class that inherits from AnalyticsWidgetProvider must implements onUpdate and when it must implements `performUpdate`.
Since you added `@CallSuper` and it's not final, I assume you expect the children class to also override this method. But then, having `performUpdate` that actually perform the update seems useless. The performance could be done in the children `onUpdate`.

Also, what's the point of `performUpdate`? `usageAnalytics` is always the same object as far as I understand it, and it seems any class can free access it. So I don't see the point of this extra parameter.

If somehow it was useful for tests, for examples, please add a comment explaining it. And explain the reason of this implementation in the commit message if you can't put it in documentation, so that the next reader can understand why things are implemented the way they are

2024-06-11 00:07 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
Honestly, I don't know enough about widget to be sure of what is a small widget exactly.
A line or two of documentation, potentially with a link to the official documentation of small widget, would help me review, and probably the next reviewer that is not expert in widgets.

2024-07-13 17:21 UTC, Arthur-Milchior reviewed
There are some changes I don't understand. I am not 100% certain they are wrong, I may misunderstood things. But I'd really like your commit message to explain changes that don't seem to be directly related to refactoring common code.

My suspicion is that you did `git pull origin main` and didn't resolve properly the merge conflicts

2024-07-13 17:21 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
> -            val appWidgetManager = getAppWidgetManager(context) ?: return
I'm sorry, but I don't understand why we don't use `getAppWidgetManager` anymore. If really it became useless, I'd really like you to explain why in the commit message. So, if we got a crash report with this line of code, we understand your choice.

According to the comment near `getAppWidgetManager`, it's actually possible that the returned value is null, on some devices. If so, we should really do an early return, otherwise we'll reintroduce the crash this function was solving.

(I guess also, a TODO in WidgetUtils.kt to state that we need a linter to forbid direct usage of `AppWidgetManager.getInstance` would be nice

2024-07-13 17:21 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
> +                    AnkiDroidApp.instance.registerReceiver(mMountReceiver, iFilter)
Why did you remove the Compat and the flag?
It feels like this is going to lead to crash.

Did you test the small widget with your changes ? I don't see the numbers anymore, while I see them with origin/main

2024-07-13 17:59 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> + * TODO: Add a lint rule to forbid the direct use of AppWidgetProvider.
marking resolved as per discussion in discord regarding dropping idea of it as of now.

2024-07-13 18:07 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> + * TODO: Add a lint rule to forbid the direct use of AppWidgetProvider.
Should be able to mark it as a `final override` in Kotlin, if this is a worry

2024-07-13 18:42 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
> +                    AnkiDroidApp.instance.registerReceiver(mMountReceiver, iFilter)
my bad , yep its crashing ; i did tested the code before pushing all the way to here, it was working (but in another commit ig i messed up the code ) .  thanks

2024-07-13 19:17 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> + * TODO: Add a lint rule to forbid the direct use of AppWidgetProvider.
No need for final, override is sufficient ? as it says Redundant modality modifier

2024-07-18 18:45 UTC, david-allison commented
Still has conflicts

+ please squash merge

2024-07-18 18:53 UTC, david-allison requested changes

2024-07-18 18:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +    override fun onUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray) {
```suggestion
    final override fun onUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray) {
```

2024-07-18 18:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +    override fun onUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray) {
I don't think we need `@CallSuper` if we do this.

This handles Arthur's comment above

2024-07-18 18:58 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +    override fun onUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray) {
was not sure about it , thanks

2024-07-18 18:59 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> + * TODO: Add a lint rule to forbid the direct use of AppWidgetProvider.
resolved (here)[https://github.com/ankidroid/Anki-Android/pull/16545#discussion_r1683338359]

2024-07-18 19:05 UTC, david-allison approved these changes

2024-07-18 19:06 UTC, david-allison commented
@Arthur-Milchior

2024-07-20 11:19 UTC, david-allison reviewed
Has conflicts

2024-07-20 11:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +        Timber.d("${this.javaClass.name}: performUpdate")
I feel the log should come first

2024-07-21 14:55 UTC, david-allison requested changes
Why is this no longer applied to `AnkiDroidWidgetSmall`?

2024-07-21 14:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
> +        Timber.d("AddNoteWidget: performUpdate")
Isn't this logged already in the base class?

```suggestion
```

2024-07-21 20:30 UTC, xenonnn4w commented
> Why is this no longer applied to `AnkiDroidWidgetSmall`?

for some reason `widget_eta `and `widget_due` are not rendering after these changes , was investigating that onl;y

2024-07-21 20:38 UTC, david-allison commented
You should be communicating that this is the case

2024-07-22 01:27 UTC, Arthur-Milchior requested changes
Honestly, I'm unhappy with the recent changes. 
Maybe they are correct change, maybe they are wrong change, I honestly don't know, because you don't explain what you're doing.

I spent more than an hour on it, trying to explain in details what's wrong. This should not be the case on a commit that is a month an a half old. Especially given that I already asked you the previous time to add comment and documentation, to explain to us what you're doing.

David did approve a previous version of the PR. Personally, I had some requests, but it seems globally okay. Now you made many you changes, you MUST explain why you did them.  When I came back to review your PR, I was expecting to see essentially the same PR than last time, with the changes I requested and maybe change requested by David. If David approved your PR, you are not supposed to change it, or if you must, you should ask for a new review, or explain that it's really a trivial change (for example you rebased onto `main`, or you found a typo in a comment you wanted to fix). 
You made really non trivial change. If they are really things you wanted to do, that you believed should be merged with the current PR, then you should have written it down explicitly, you should have explained what was changed so that we don't need to re-read everything, and check from scratch whether every part of the PR is okay in this new environment.

And, even if it were a fresh PR and not an update on a PR that was already reviewed, you need to save us time. I don't know Widgets very well, I don't know the details of AppWidgetManager. I should not have to know them. Android is huge, and maintainers do not have to know the entire system. The contributor that does a change, especially in the case of GSoC where it's your responsability to do this change, must assume that we know Kotlin correctly, that we have an idea of how Android generally works. But it's your role to explain what you do so that we don't have to read the whole documentation to understand the reason behind your proposed changes. And similarly, every such non trivial changes must be explained in the commit message, to help future reader of the code understand why the code is written the way it is, and maybe revert the change, or debug it, if it's not what you expected.

As far as I'm concerned, I will not accept to review another PR of yours unless every non trivial change you did are documented in the commit message, or comes with a comment or documentation near it.
If you have a doubt whether a change is trivial or not, consider it to be non-trivial. Once you document too much, we'll discuss or to ensure you comment just enough. But first, you must take the habit to comment a lot.


Finally, regarding 
> for some reason widget_eta and widget_due are not rendering after these changes , was investigating that onl;y

Here are my requests:
* either you repaired it, and that's great. Please let us know
* or it's still broken. In this case, please provide screenshot, so we understand exactly what you mean here. What is broken. Maybe we can help you. And, more importantly, either you believe the PR can still be merged, in which case explain why it's okay to merge this new class, even if it have issues. Or it can't be merged, and change the PR so that it moves to Draft, so that it's clear that there are still things wrong here. And please communicate with us, don't hesitate to ask for help. We didn't even knew there was an issue before you mentioned it as a reply to David. And if there is an issue with code we approved, it means we missed some errors, that's something that is interesting for us to know

2024-07-22 01:27 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
> +        private fun getAppWidgetManager(context: Context): AppWidgetManager? {
Why did you introduce this function?
Please add a comment to explain why we need it.
Is it really possible that `getInstance` throws an exception? If so, how did you learn it ? It's not in the documentation of the method. Were you able to experience this exception yoursef ? If so, how ? Did you read it somewhere, please provide a link to the place you learned about it. Also, can you catch only the type of exception that can really be raised ? This seems too vague.

In any case, this seems to be very similar to `com.pichi2.widget.WidgetUtils.getAppWidgetManager`. It sounds really really strange to me that you can't reuse the same implementation. If really you can have an exception, then you probably want to correct the other method too, as the problem can occur for any place that use the other method.

If the only difference is that you really want to Timber an error. Here are a few remarks:
* I don't think this should use `Timber.e`. Usually we use it to show an error in AnkiDroid. Something that we expect the developer of AnkiDroid to be able to fix. If it raises an exception, that's an issue with the phone itself. I would accept a `Timber.w`, but `e` seems useless. It would show as an error in the log each time it's used.
* You should add a comment stating that the only reason we use this method is to timber.
* If `getInstance` return `null` without throwing an exception, that's probably a case where you want to Timber. And it seems it's possible, according to the current content of WidgetUtils.

2024-07-22 13:49 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
> +        private fun getAppWidgetManager(context: Context): AppWidgetManager? {
Very sorry, i understand now my implementation is completely wrong.

2024-07-22 16:55 UTC, david-allison requested changes

2024-07-22 16:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
> -        preferences.edit(commit = true) { putBoolean("widgetSmallEnabled", false) }
This line is not moved to the base class and should not be removed. Same in `onEnabled`

2024-07-22 16:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
> +     * Note: When this method is executed, it is assumed that the storage access is granted.
`<p>` doesn't work in Kotlin I believe

```
* Override this method to implement Widget functionality
* 
* Called when the [AnalyticsWidgetProvider] is asked to provide [RemoteViews] for a set of Widgets AND the Anki collection is accessible.
* 
* @see AppWidgetProvider.onUpdate
```

2024-07-22 17:39 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
> -        preferences.edit(commit = true) { putBoolean("widgetSmallEnabled", false) }
oh that's where i got confused , i was thinking same as Arthur point this in above review, sorry for trouble

2024-07-22 21:37 UTC, david-allison requested changes

2024-07-22 21:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
>      }
There's duplicated code in the base class `onEnabled/Disabled` and here

2024-07-23 20:59 UTC, david-allison approved these changes
Looks good, cheers

2024-07-24 21:13 UTC, Arthur-Milchior reviewed
Regarding the commit message, the way it usually work in github and most git tool is that the first line is considered to be the title, and the remaining is the body of the message.

So I'd appreciate if you could have a first line with something that looks like a title. The title will be the only thing that someone will see when they look at the history of `AnkiDroidWidgetSmall.kt` 's `git blame` for example.

It can be something as simple as:
> Introducing `AnalyticsWidgetProvider` as ancestor of all widget classes

And then you can add a small message that explain why it's done, so that anyone looking at the commit understand more of the context.

> This will ensure any widgets Timber and send analytics on enabling, disabling and updating.

2024-07-24 21:13 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/widget/DeckPickerWidgetTest.kt
> +class DeckPickerWidgetTest : RobolectricTest() {
Why is this called `DeckPickerWidgetTest` ? this seems not related to deck picker at all.
By the way, same question regarding the PR title "Analytical widget provider class for Deck Picker Widget ."  Seems like you should rename it.

2024-07-26 05:48 UTC, Arthur-Milchior approved these changes

2024-07-26 06:03 UTC, merged