Small cleaning of codes
ankidroid/Anki-Android pull request #16572
Opened 2024-06-09 02:06 UTC by Arthur-Milchior

First, I wanted to replace
`isEmpty` by `containsNoCard`. It seems interesting to note that this may still contains non-default note-type and decks, and still consider the collection empty.

This makes me look at Pairs, and found that, often, destructing the Pair seems more readable to me than using `.first` and `.second`. Especially when it eiher allows to have a single non-null assertion, or allows to have name value instead.

2024-06-09 05:36 UTC, david-allison requested changes
Tuple destructing is great, naming needs a couple of tweaks, then good to go

2024-06-09 05:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +    fun areEmptyDecks(vararg dids: Long): Boolean {
Please revert and add `@NotInLibAnki`

This isn't correct grammatically when handing a single deck and this is only ever provided with a single deck

If you are wanting to rename this, move it to `Decks`: `col.decks.areEmpty(dids)`

2024-06-09 05:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +    val containsNoCard: Boolean
Please revert and add `@LibAnkiAlias("is_empty")`

This should match Anki Desktop, and the new name is not correct grammatically

https://github.com/ankitects/anki/blob/33a923797afc9655c3b4f79847e1705a1f998d03/pylib/anki/collection.py#L600

2024-06-10 10:47 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +    fun areEmptyDecks(vararg dids: Long): Boolean {
Oh. My bad. I didn't check its usage.
The function accept multiple arguments, so I assume it was used with multiple arguments.

Then I change the signature for a single did.
This even allow to use the same sql query all the time. Even if that won't be a significant improvement for sure

2024-06-10 10:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +    val containsNoCard: Boolean
Done

2024-06-10 11:28 UTC, david-allison reviewed
One suggestion for discussion, rest LGTM

2024-06-10 11:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
>      fun findOneCardByNote(query: String, order: SortOrder): List<CardId> {
(aside): I have a dev-only change which removes this method

2024-06-10 11:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
> +}
this feels cleaner to me:

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt	(revision 8687a54fd6d1d690715ae8bc9941a5c34396dc2d)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt	(date 1718018806479)
@@ -2660,7 +2660,7 @@
             withCol { sched.hasCardsTodayAfterStudyAheadLimit() } -> CompletedDeckStatus.LEARN_AHEAD_LIMIT_REACHED
             withCol { sched.newDue() || sched.revDue() } -> CompletedDeckStatus.LEARN_AHEAD_LIMIT_REACHED
             withCol { decks.isFiltered(did) } -> CompletedDeckStatus.DYNAMIC_DECK_NO_LIMITS_REACHED
-            deckListAdapter.getNodeByDid(did).children.isEmpty() && isEmptyDeck(did) -> CompletedDeckStatus.EMPTY_REGULAR_DECK
+            deckListAdapter.getNodeByDid(did).children.isEmpty() && withCol { decks.isEmpty(did) } -> CompletedDeckStatus.EMPTY_REGULAR_DECK
             else -> CompletedDeckStatus.REGULAR_DECK_NO_MORE_CARDS_TODAY
         }
 
Index: AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt b/AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
--- a/AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt	(revision 8687a54fd6d1d690715ae8bc9941a5c34396dc2d)
+++ b/AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt	(date 1718018806485)
@@ -578,6 +578,14 @@
         return deck.getString("name") + DECK_SEPARATOR + subdeckName
     }
 
+    @NotInLibAnki
+    fun cardCount(did: DeckId): Int =
+        col.db.queryScalar("SELECT count() FROM cards WHERE did = ? ", did)
+
+    @NotInLibAnki
+    fun isEmpty(did: DeckId): Boolean = cardCount(did) == 0
+
+
     companion object {
         /* Parents/children */
 
@@ -631,14 +639,4 @@
  */
 fun Collection.getOrCreateFilteredDeck(did: DeckId): FilteredDeckForUpdate {
     return backend.getOrCreateFilteredDeck(did = did)
-}
-
-@NotInLibAnki
-suspend fun cardCount(did: DeckId): Int {
-    return withCol { db.queryScalar("SELECT count() FROM cards WHERE did = ? ", did) }
-}
-
-@NotInLibAnki
-suspend fun isEmptyDeck(did: DeckId): Boolean {
-    return cardCount(did) == 0
-}
+}
\ No newline at end of file
```

2024-07-07 15:08 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
> +}
Done, thanks

2024-07-07 16:58 UTC, david-allison approved these changes
Looks great, cheers

2024-07-16 06:31 UTC, lukstbit approved these changes
I'm fine with the changes.
Left a note, you can merge as you see fit.

2024-07-16 06:31 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
> +    fun cardCount(did: DeckId): Int =
Decks class already has a method cardCount() which follows anki(card_count). That method is not yet implemented but the implementation is simple https://github.com/ankitects/anki/blob/486cc8a2abba7858e0e8b69e9768d3be0a47a4dd/pylib/anki/decks.py#L224-L237
I also think the other method has a cleaner API.

If you want to keep this as a simple cleanup PR I'm fine with it and we can merge this, I was going to provide an implementation for that method anyway for another PR and I can cleanup this at that moment.

2024-07-18 15:02 UTC, mikehardy approved these changes

2024-07-18 15:02 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
> +    fun cardCount(did: DeckId): Int =
@lukstbit I'm scanning the queue for things to merge and I think your suggestion is best as a small cleanup PR or part of your PR after, to keep this small and to get it through while it has agreement on all other parts

2024-07-18 20:54 UTC, david-allison commented
Taking this on to completion, CI failed due to conflicts with the wildcard import

2024-07-18 20:58 UTC, david-allison approved these changes

2024-07-18 21:29 UTC, merged

2024-07-19 03:16 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
> +    fun cardCount(did: DeckId): Int =
@mikehardy Sure, I was going to merge this in a couple of days myself anyway.