[GSoC'24] Enhacement: Instant Editor UX improvements
ankidroid/Anki-Android pull request #16587
Opened 2024-06-11 14:05 UTC by criticalAY

On top of:
*  #16534
## Purpose / Description
- Cloze number to increment only in Increment mode
- Show discard change dialog if there are any changes 
- Share latest text to the note editor 

## How Has This Been Tested?
Tested on Oneplus nord ce

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-06-14 23:10 UTC, david-allison requested changes
Couple of required comments, rest are implementer's choice, but I'd encourage them

2024-06-14 23:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +                if (keyCode == KeyEvent.KEYCODE_BACK && event.action == KeyEvent.ACTION_UP) {
⚠️ use `onDismissListener`

2024-06-14 23:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +            if (event.action == MotionEvent.ACTION_DOWN) {
invert this condition to make code easier to read

2024-06-14 23:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +                dialogView.getGlobalVisibleRect(rect)
Consider making a method here to abstract what's happening into a simple concept

```kotlin
if (!dialogView.userClickedOutsideDialog(event)) { return false }
// user clicked inside the dialog - we want to exit
if (intentTextChanged()) {
    showDiscardChangesDialog()
    return@setOnTouchListener true
} else {
    finish()
}
```

2024-06-14 23:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        dialogView.rootView.setOnTouchListener { _, event ->
⚠️ Why is this not handled by default?

2024-06-14 23:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        return intent.getStringExtra("extra_text_key") != viewModel.actualClozeFieldText.value
extract `extra_text_key` to a constant so a developer can more easily run _Find Usages_ to understand the code

2024-06-14 23:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        val sharedText = viewModel.actualClozeFieldText.value
See if you can make a property which exposes `.value`, to reduce overhead reading the code

2024-06-15 09:48 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +                if (keyCode == KeyEvent.KEYCODE_BACK && event.action == KeyEvent.ACTION_UP) {
The editor dialog would already be dismissed, this is called after the dialog is dismissed so cant use it

2024-06-15 10:05 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        dialogView.rootView.setOnTouchListener { _, event ->
The touch outside the dialog would dismiss it and if we `setCancellable` to false then the Dialog cant be dismissed by accidental clicks, we will need to handle it on our end

2024-06-15 10:10 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        val sharedText = viewModel.actualClozeFieldText.value
get property in activity

2024-06-19 20:39 UTC, david-allison approved these changes
Looks good!

2024-06-19 22:15 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DiscardChangesDialog.kt
> +        Timber.i("showing 'discard changes' dialog")
Not temp, this dialog is used in a lot of places so it intentional was put here by David.

2024-07-05 13:59 UTC, merged