extract magic numbers to version catalog
ankidroid/Anki-Android pull request #16594
Opened 2024-06-14 14:26 UTC by AbdelrahmanEsam

extract magic numbers from gradle and share them between modules

2024-06-14 15:29 UTC, lukstbit requested changes
Thanks, left one minor issue.
Also please link the issue that this PR will be closing.

2024-06-14 15:29 UTC, lukstbit commented on AnkiDroid/build.gradle
> +        versionName=libs.versions.versionName.get().toString()
versionCode and versionName shouldn't be extracted.

2024-06-15 07:28 UTC, lukstbit commented on AnkiDroid/build.gradle
> +        versionName=libs.versions.versionName.get().toString()
Those are used just in the main module to build the app and they will not be used in other modules. Also, having the actual values for the app versions there, is better for understanding the documentation that is just above the changed lines(that describes how the versions numbers are constructed).

The other values that you extracted are used in multiple modules(and will be used in modules that we plan to add).

2024-06-15 11:49 UTC, AbdelrahmanEsam commented on AnkiDroid/build.gradle
> +        versionName=libs.versions.versionName.get().toString()
I see that they are only in the main module and they will never be at another ... but I see that it's good for centerlizing versions over all .... you want to alter version ? just go for version catalog.

2024-06-15 11:54 UTC, AbdelrahmanEsam commented on AnkiDroid/build.gradle
> +        versionName=libs.versions.versionName.get().toString()
@david-allison  what do you think ?

2024-06-15 11:59 UTC, david-allison commented on AnkiDroid/build.gradle
> +        versionName=libs.versions.versionName.get().toString()
Keep the version codes where they are

2024-06-15 13:59 UTC, david-allison requested changes

2024-06-15 13:59 UTC, david-allison commented on AnkiDroid/build.gradle
> +    compileSdk libs.versions.compileSdk.get().toInteger() // change api compileSdk at the same time
```suggestion
    compileSdk libs.versions.compileSdk.get().toInteger()
```

2024-06-15 13:59 UTC, david-allison commented on AnkiDroid/build.gradle
> +        minSdk libs.versions.minSdk.get().toInteger() // also in testlib/build.gradle.kts
```suggestion
        minSdk libs.versions.minSdk.get().toInteger()
```

2024-06-15 13:59 UTC, david-allison commented on AnkiDroid/build.gradle
> +        targetSdk libs.versions.targetSdk.get().toInteger() // also in [api|testlib]/build.gradle.kts and ../robolectricDownloader.gradle
Can the toml value also be used in `robolectricDownloader`?

2024-06-15 14:14 UTC, AbdelrahmanEsam commented on AnkiDroid/build.gradle
> +        targetSdk libs.versions.targetSdk.get().toInteger() // also in [api|testlib]/build.gradle.kts and ../robolectricDownloader.gradle
yes but for what ?

2024-06-15 14:36 UTC, david-allison commented on AnkiDroid/build.gradle
> +        targetSdk libs.versions.targetSdk.get().toInteger() // also in [api|testlib]/build.gradle.kts and ../robolectricDownloader.gradle
You're right - forgot the implementation of the script

2024-06-15 14:37 UTC, david-allison requested changes
one chage, as the result of a discussion - rest looks good, thanks!

Treat as an approve after the comment is added

2024-06-15 14:37 UTC, david-allison commented on AnkiDroid/build.gradle
> -        targetSdk 33 // also in [api|testlib]/build.gradle.kts and ../robolectricDownloader.gradle
move the `robolectricDownloader.gradle` comment to the TOML

2024-06-15 14:52 UTC, david-allison approved these changes

2024-06-15 14:52 UTC, david-allison commented on AnkiDroid/build.gradle
>          // After #13695: change .tests_emulator.yml
maybe also move this to `minSdk`

2024-06-15 16:30 UTC, david-allison commented on gradle/libs.versions.toml
> +targetSdk = "33"  # also in [api|testlib]/build.gradle.kts and ../robolectricDownloader.gradle
```suggestion
targetSdk = "33"  # also in ../robolectricDownloader.gradle
```

2024-06-15 16:42 UTC, david-allison approved these changes
CHeers

2024-06-16 08:02 UTC, lukstbit approved these changes
Thank you for making the changes!

2024-06-16 08:37 UTC, merged