fix: use android import for crash report dialog
ankidroid/Anki-Android pull request #16605
Opened 2024-06-16 20:17 UTC by shrutigitte

## Purpose / Description
use android import for crash report dialog instead of androidx as crash report acitivity is a external dependecy activity and using androidx requires theme.appCompat

## Fixes
* Fixes #16604 

## How Has This Been Tested?
Locally tested on emulator

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-06-16 20:55 UTC, criticalAY requested changes
CI failed, you need to update the lint file and add this file as exception there

2024-06-16 21:09 UTC, david-allison approved these changes
Needs a follow-up issue for a test

and the lint needs to be ignored with a reason

```
  /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt:20: Error: Use androidx.appcompat.app.AlertDialog instead of android.app.AlertDialog [AvoidAlertDialogUsage from com.ichi2.anki:lint-rules]
  import android.app.AlertDialog
```

2024-06-17 01:15 UTC, mikehardy reviewed
Hasn't shipped in the release-2.18 branch so this does not need a pick

Can't approve with lint failing tho

2024-06-17 17:41 UTC, criticalAY approved these changes
Looks good now!

2024-06-17 17:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt
> +//noinspection AvoidAlertDialogUsage see #16605
Is it possible to move this next to the import?

2024-06-17 18:13 UTC, shrutigitte commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt
> +//noinspection AvoidAlertDialogUsage see #16605
no it cannot be because it would not be in lexical order

'''
Imports must be ordered in lexicographic order without any empty lines in-between with "java", "javax", "kotlin" and aliases in the end -- no autocorrection due to comments in the import list [90m(import-ordering)[0m
'''

2024-06-17 18:17 UTC, david-allison commented
LGTM, @shrutigitte Could you squash the commits so we can add this to the merge queue?

2024-06-17 18:18 UTC, david-allison approved these changes

2024-06-17 18:22 UTC, shrutigitte commented
done

2024-06-18 05:03 UTC, lukstbit approved these changes
Thanks for the fix!
While the _noinspection_ comment worked on suppressing the lint violation, I think it is better to use the lint rules system that we built so I added the required lint code.

2024-06-18 05:20 UTC, merged