chore: refactors in prep for using backend to render browser
ankidroid/Anki-Android pull request #16617
Opened 2024-06-19 15:37 UTC by david-allison

## Approach
* Implement various non-functional refactors and add new functionality to the `common` module

## How Has This Been Tested?

Unit tests

⚠️ Common unit tests do not run in CI - needs an issue

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-06-19 16:57 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
> +    Timber.i("Flagging %d card(s) as %s", cids.size, flag)
is that really `.i` ? or `.d` ?

2024-06-19 16:57 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +            Timber.i("removeNotes: %d changes", it.count)
also seems kind of `.d` to me personally

2024-06-19 16:58 UTC, mikehardy approved these changes
LGTM - two tiniest quibbles on .d vs .i but I don't really mind tbh
if we have tests and they're just not running that's a "sad miss" because the tests are already there, should log the issue before merge

2024-06-19 17:02 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
> +    Timber.i("Flagging %d card(s) as %s", cids.size, flag)
It feels like an `.i`, but I'm open to feedback:

* it's not PII, so it can be `.i`
* It's a bulk operation, so won't be called in a list
* Knowing that a user has flagged cards is useful for debugging

2024-06-19 17:05 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
> +    Timber.i("Flagging %d card(s) as %s", cids.size, flag)
I'll uee `d`

2024-06-20 11:28 UTC, lukstbit requested changes

2024-06-20 11:28 UTC, lukstbit commented on common/src/main/java/com/ichi2/anki/common/utils/ext/Float.kt
> +fun Float.clamp(min: Float, max: Float) = max(min, min(this, max))
[coerceIn](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.ranges/coerce-in.html)?

2024-06-20 11:28 UTC, lukstbit commented on common/src/main/java/com/ichi2/anki/utils/android/ColorUtils.kt
> +object ColorUtils {
Do we really need this object?
My guess is no as we'll would probably import the specific function directly, _ColorUtils.darkenColor()_ seems a bit verbose vs using _darkenColor()_ directly anyway.

2024-06-20 11:28 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/BrowserColumnCollection.kt
> +        ): BrowserColumnCollection? {
Maybe it would be worth adding an explanation for the return type in the method's javadoc?

2024-06-20 12:00 UTC, lukstbit approved these changes
Works for me.

2024-06-20 12:16 UTC, merged