Implementation of Keyboard Shortcuts
ankidroid/Anki-Android pull request #16679
Opened 2024-07-01 11:50 UTC by SanjaySargam

## Purpose / Description
Implement keyboard shortcuts to enhance the user experience by providing quick access to commonly used functionalities within the application. This will improve the overall usability, especially for power users who prefer using the keyboard over the mouse.

## Approach
The shortcuts are implemented by adding event listeners for keypress events and mapping them to the respective functions. The approach ensures that the shortcuts are intuitive and do not conflict with existing shortcuts.

## How Has This Been Tested?
Hp Chromebook

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-07-04 13:42 UTC, Arthur-Milchior reviewed
In my opinion, the first commit could be a PR by itself.
If you want to ensure the reviewer spend very little time on it, you could do very simple changes.
First commit, you create openManageNoteType and use it in the shortcut. Second commit, same thing with another method, etc..
So each commit can be reviewed in a second, checking that you just copy pasted code, called the right function, and used the right letter. (We can always squash this to have a single commit in our codebase)

2024-07-04 13:42 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                // Ensure it's not Ctrl + D
Why is this important for ctrl+d and not other letters?
If a user press ctrl+a for example, we probably don't want to open add-note. This seems like a bug that would be nice to fix for all letters. 
I assume you tested manually, using ctrl+d and ctrl+a other letters and realized that you entered the switch.
Can you please write this in the commit message.

2024-07-04 13:42 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    override fun onKeyDown(keyCode: Int, event: KeyEvent): Boolean {
Please explain why some actions are on key up and other on key down. That is far from intuitive to me

2024-07-05 08:41 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                // Ensure it's not Ctrl + D
> Why is this important for ctrl+d and not other letters?

Because `Ctrl+D` is a shortcut to check database

2024-07-05 09:09 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    override fun onKeyDown(keyCode: Int, event: KeyEvent): Boolean {
onKeyDown() trigger multiple times if the key is held down. So I plan to move remove onKeyDown() and combine in onKeyUp()

2024-07-07 05:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    renameDeckDialog(focusedDeck)
When we are on a phone and you have almost no indication of which deck is currently selected, I don't think this shortcut is a good idea.
When you are on a split screen, with the deck taking all of the trailiing side of the screen, then it makes sense.

I should add that, at least on simulator, you can navigate in the list of decks with the keyboard's arrows. But the deck selected by the keyboard is only used if you press "enter" (because it simulates a tap), and is not used otherwise. So I'd even state that this is a very misleading behavior.

I think that, before having any action that occurs on the selected deck on phone, we should ensure that it's very clear which deck is currently selected, and that the user can use the keyboard to navigate to it.

I think right now this feature should belong to deckoptions instead of deckpicker

2024-07-07 05:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                deleteDeck(focusedDeck)
Same remark as with "Rename" below. But furthermore, I think we should use DeckPickerConfirmDeleteDeckDialog. I opened #16691 to discuss it. 
Unless there is a consensus that this implementation is okay, I really prefer that we only do the deletion if we first ask for the user to confirm the deletion

2024-07-07 06:11 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +     * Displays a dialog for creating a new deck.
Ok. I'm happy that you liked my documentation. From now onwards, I'll document each and everything in upcoming PRs

2024-07-07 10:28 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    renameDeckDialog(focusedDeck)
> I think right now this feature should belong to deckoptions instead of deckpicker

You mean `DeckPickerContextMenu` ?

2024-07-12 16:35 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                deleteDeck(focusedDeck)
This is still relevant. Without answer  in my bug, let's be safe and ask for confirmation

2024-07-12 17:35 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    renameDeckDialog(focusedDeck)
should I make this shortcut available only if fragmented?

2024-07-12 17:38 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                deleteDeck(focusedDeck)
then here should I DeckPickerConfirmDeleteDeckDialog?

2024-07-13 19:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    renameDeckDialog(focusedDeck)
I'd prefer yes, please. We'll change it if somebody has an objection

2024-07-13 19:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                deleteDeck(focusedDeck)
Yes please

2024-07-13 20:16 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    renameDeckDialog(focusedDeck)
also delete shortcut right?

2024-07-13 20:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    renameDeckDialog(focusedDeck)
Same with the delete shortcut yes.

Please, do longer sentences. Right now, I thought "delete" was the verb and you asked whether I also want you to delete the shortcut.

2024-07-15 23:39 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerConfirmDeleteDeckDialog.kt
> +                    "Are you sure you want to delete <b>$deckName</b>?",
Please don't add strings shown to the user in the codebase.
Instead, it should go in `AnkiDrois/src/main/res/values/03-dialogs.xml` with all other strings shown to the user, so that our translators can translate it.

Don't put the `<b>` in the xml file. The translator should not have to know anything about html bold tag. Instead, you'll do `res.getString(R.string.delete_deck_message,  "<b>$deckName</b>")`

Actually, if @david-allison agree, I think we could reuse the sentences that were deleted in 7a65160e0e23e20080091a30abdd4c05fc610e06

```
    <plurals name="delete_deck_message">
        <item quantity="one">Delete all cards in %1$s? It contains %2$d card.</item>
        <item quantity="other">Delete all cards in %1$s? It contains %2$d cards.</item>
    </plurals>
   <string name="delete_cram_deck_message">Send all cards in %s back to their original decks?</string>
```

So that the user know whether they delete a filtered deck or a regular deck, and in the second case, how many card they'll delete (if you see "It contains 1049 cards" you may start to worry!)

In the case of filtered decks (that used to be called "cram deck") I suggest maybe the sentence
> Delete filtered deck <b>%s</b> and send all cards back to their original decks.

So that it's clear it's also a deletion.

2024-07-16 09:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                // This shortcut should be helpful on large screens only
`DEL` should show a dialog

The dialog should note that `SHIFT` + `DEL` would auto-confirm the deletion

2024-07-16 09:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                        getColUnsafe.decks.name(focusedDeck),
I'd do:

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt	(revision 08b24ec1aff35e10b765077a2626d16753de8cf2)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt	(date 1721122589951)
@@ -1391,10 +1391,7 @@
                 // This shortcut should be helpful on large screens only
                 if (fragmented) {
                     Timber.i("Delete Deck from keypress")
-                    DeckPickerConfirmDeleteDeckDialog.newInstance(
-                        getColUnsafe.decks.name(focusedDeck),
-                        focusedDeck
-                    ).show(supportFragmentManager, "deckDeckDialog")
+                    showDeleteDeckConfirmationDialog()
                 }
             }
             KeyEvent.KEYCODE_R -> {
@@ -1449,6 +1446,15 @@
         return super.onKeyUp(keyCode, event)
     }
 
+    private fun showDeleteDeckConfirmationDialog() = launchCatchingTask {
+        val deckName = withCol { decks.name(focusedDeck) }
+        val confirmDeleteDeckDialog = DeckPickerConfirmDeleteDeckDialog.newInstance(
+            deckName = deckName,
+            deckId = focusedDeck
+        )
+        showDialogFragment(confirmDeleteDeckDialog)
+    }
+
     /**
      * Perform the following tasks:
      * Automatic backup
```

2024-07-16 09:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerConfirmDeleteDeckDialog.kt
> +                    "Are you sure you want to delete <b>$deckName</b>?",
I agree

2024-07-17 10:28 UTC, david-allison requested changes
I would find it useful to have a table of keyboard shortcuts, and the equivalent shortcut in Anki Desktop

Some things. such as "Empty Cards" feel out of place

I'd (mildly) recommend that this doesn't have a shortcut, as it's an uncommon action

This could do with a few more `@see` annotations to help with navigation

Code is really high quality, thank you!

2024-07-17 10:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    showTheCreateDeckDialog()
`displayCreateDeckDialog()`

2024-07-17 10:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                createFilteredDialog()
This feels a bit wordy - maybe see if an LLM has better suggestions

```
                displayCreateFilteredDeckDialog()
```

2024-07-17 10:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                        // Shortcut: Shift + DEL - Delete deck without confirmation dialog
Awesome stuff

2024-07-17 10:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    handleEmptyCards()
It feels too common for a very uncommon use-case

Anki doesn't use this shortcut

2024-07-17 10:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        val (deckName, totalCards, isFilteredDeck) = withCol {
really clean

2024-07-17 10:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +     * Finally, the dialog is displayed by calling `showDialog()` on the `CreateDeckDialog` instance.
This feels over-documented - explain what the method does and let the developer read the implementation details if they're unambiguous

@Arthur-Milchior did you request this level of detail? You may want to improve on my suggestion, as it's a little bare

```suggestion
     * Displays a dialog for creating a new deck.
     *
     * @see CreateDeckDialog
```

2024-07-17 10:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
> +     * Opens the Settings Screen.
I felt it was a little ambiguous as we have a few settings screens

```suggestion
     * Opens AnkiDroid's Settings Screen.
     * @see Preferences
```

2024-07-17 10:28 UTC, david-allison commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +        <item quantity="other">Delete all cards in %1$s? It contains %2$d cards.</item>
This feels unusual, normally we don't have full stops at the end of strings

Implementer's choice

2024-07-17 10:54 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    handleEmptyCards()
> Anki doesn't use this shortcut

Yes, it does not have a shortcut for this. It would be better if we had a shortcut. In the future, we can have a shortcut in Anki too.

2024-07-17 15:54 UTC, SanjaySargam commented
> I would find it useful to have a table of keyboard shortcuts, and the equivalent shortcut in Anki Desktop

 @david-allison Created table in PR description

2024-07-17 23:10 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                        getColUnsafe.decks.name(focusedDeck),
Oh. I asked your opinion because you appear as author of those functions. Except that I realize now that you probably simply did the kotlin transition. My bad.

Regarding the toast:
* `confirmDeleteDeckDialog` should not be a toast. It's asking the user to confirm the deletion. There is no reason to show it in the notification if the user close the app.
* if the user select the deletion, then we want to keep the already existing snackbar. In particular, because it offers a way to undo. The good news being that this don't require more work from you.


In particular, it seems to me that the documentation of `showDialogFragment` is outdated. I'll correct it.

2024-07-17 23:13 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    handleEmptyCards()
I'd be curious to know why you thing it would be better. IT is not obvious to me.
Personally, I suspect that there will be more users that type "e" by accident than user that really want to handle empty cards.
I especially don't like this because sometime the issue is that the card template is wrong, and you don't even want to delete the cards.

2024-07-17 23:17 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +     * Finally, the dialog is displayed by calling `showDialog()` on the `CreateDeckDialog` instance.
@david-allison I asked to reduce the quantity of documentation in https://github.com/ankidroid/Anki-Android/pull/16679#discussion_r1667599963.

However, I should note that, in a way, I did ask for too much documentation. This is because, during the first few weeks, Sanjay wrote very little documentation. Even for complex classes such as AnkiFragment. And since Sanjay was still not writing enough documentation, I told him I want to see too much documentation. That he doesn't hesitate to write a lot, we can always cut later. So, yeah, in a sense, I did ask to write that much documentation, as a first step. And later, I tried to explain why I wanted to keep part of the documentation and why we could remove other parts

2024-07-18 05:56 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    handleEmptyCards()
I understand your concern about accidentally triggering the deletion of empty cards. I want to clarify that pressing 'E' does not immediately delete the empty cards. Instead, it initiates a process that shows a confirmation dialog to the user. This dialog provides details about the empty cards found and allows the user to decide whether to proceed with deletion or not

2024-07-19 08:52 UTC, david-allison commented
@SanjaySargam Please feel free to mark my comments as 'resolved' once you've resolved them

2024-07-19 08:55 UTC, david-allison requested changes
I would request that we use Anki Desktop's shortcuts where possible, for compatibility:

| Action | Shortcut in AnkiDroid | Shortcut in Anki |
|--------|--------|--------|
| Check Database | Ctrl + D | C |
| Restore backup | Ctrl+R | B |

I would like to remove 'empty cards' (up to you & @Arthur-Milchior, non-blocking)

In terms of code quality, this is great, thank you!

2024-07-19 08:55 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    handleEmptyCards()
I'd vote to remove this

2024-07-19 09:13 UTC, SanjaySargam commented
> Restore backup	Ctrl+R	B

@david-allison Browser cards and Create backup both have shortcut as 'B' in Anki

2024-07-19 09:30 UTC, david-allison commented
Ah, it wasn't on the list

* Agreed. Browse is better as 'B'
* I don't see "Restore backup" as `B` in Anki
  * But in AnkiDroid, if we are doing it, put it under a `Ctrl` option, it's a dangerous and potentially irreversible action

2024-07-19 09:34 UTC, SanjaySargam commented
> Ah, it wasn't on the list

Shortcut B is already implemented in AnkiDroid and is bound to `Open CardBrowser`

> I don't see "Restore backup" as B in Anki

I mean
![image](https://github.com/user-attachments/assets/89190acb-f84c-4e7c-9171-4002ac2efea5)

2024-07-21 15:16 UTC, david-allison approved these changes
Cheers! 

PR description should be updated

2024-07-26 06:41 UTC, Arthur-Milchior commented
> I mean ![image](https://private-user-images.githubusercontent.com/65113071/350343901-89190acb-f84c-4e7c-9171-4002ac2efea5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NzI3MjksIm5iZiI6MTcyMTk3MjQyOSwicGF0aCI6Ii82NTExMzA3MS8zNTAzNDM5MDEtODkxOTBhY2ItZjg0Yy00ZTdjLTkxNzEtNDAwMmFjMmVmZWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA1NDAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwOTc4NGQ1ZDg3NmFiZGMxYTQzYjZmYzY5NGJiODVjODUzMGMwMjUyNDc3ODY5Mjc3ZjY0YmYwNmUzYTJjM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LVN2keDItDyS3rSuxfDavpLFcIQKf9XMQ5PREolyZe8)

This only mean that, once the menu is open "b" will select "create backup". It's not generally a shortcut in the deckpicker.
We can ignored those underlined lines

2024-08-01 23:09 UTC, merged