Fix: Autoplay audio on card previews only when setting is enabled
ankidroid/Anki-Android pull request #16684
Opened 2024-07-04 18:48 UTC by leobugeja

## Purpose / Description

Video demonstration of the card preview only auto playing the audio when the setting is on:
[preview_audio_autoplay_fix.webm](https://github.com/ankidroid/Anki-Android/assets/28263886/c31d166a-06a7-4a93-a4c8-e7197e904d5b)

## Fixes
* Fixes #16519

2024-07-05 09:04 UTC, lukstbit requested changes
Lint is failing. See the details of the Code Quality Checks  below.

2024-07-05 09:04 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardMediaPlayer.kt
> +    suspend fun autoplayAllSoundsForSide(cardSide: CardSide): Job? {
Why the extra method and not adding the check directly to _playAllSoundsForSide_ ?

2024-07-05 19:51 UTC, leobugeja commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardMediaPlayer.kt
> +    suspend fun autoplayAllSoundsForSide(cardSide: CardSide): Job? {
There are other places which call `playAllSoundsForSide` and should trigger the audio playback even when `config.autoplay` is `false`. For example within `playSounds` in `AbstractFlashcardViewer.kt`, `doAudioReplay` can be `true` while `config.autoplay` is `false` and `playAllSoundsForSide` will still get called (indirectly).

2024-07-08 05:37 UTC, lukstbit approved these changes
LGTM, thank you!

One last nitpick: Please provide a better commit message.

2024-07-08 12:01 UTC, david-allison approved these changes
Ditto: needs a better commit message

2024-07-08 22:12 UTC, leobugeja commented
Renamed commit to `fix: card preview autoplay audio`
(my bad I had took the wrong commit message when I squashed)

2024-07-11 11:40 UTC, merged