Update top bar setting description
ankidroid/Anki-Android pull request #16700
Opened 2024-07-07 21:26 UTC by Giyutomioka-SS

## Purpose / Description
Update the description of the "Show top bar" setting to include a mention of the answer timer. This change clarifies that the answer timer will be displayed when the top bar is enabled, addressing user confusion about the functionality.

## Fixes
* Fixes #16698

## Approach
Modified the string resource for the "Show top bar" setting to mention the answer timer explicitly.

## How Has This Been Tested?
Realme 6 and Emulator

## Screenshot
![photo_2024-07-08_02-55-40](https://github.com/ankidroid/Anki-Android/assets/91668590/3134b936-2d5a-4054-9f29-5ef85c745539)

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-08-17 20:42 UTC, Giyutomioka-SS commented
@david-allison should i close this?

2024-08-19 13:52 UTC, david-allison requested changes
Just slipped my radar. Good to go with one minor change

2024-08-19 13:52 UTC, david-allison commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="show_top_bar_summ">Show card counts, answer timer, flag and mark in top bar</string>
update the `name` key as well

2024-08-19 14:08 UTC, david-allison approved these changes
Cheers!

2024-08-22 16:38 UTC, mikehardy approved these changes
LGTM also, needs a string sync prior to merge

2024-08-22 17:49 UTC, merged