Fixed keyboard done button during creation or renaming of deck
ankidroid/Anki-Android pull request #16704
Opened 2024-07-08 12:42 UTC by MinusMallard

## Purpose / Description
Pressing ImeAction button on keyboard during Deck Creation resulted in new line in TextField

## Fixes
Defining a Done button click listener from the keyboard inside the input callback of the AlertDialog fixed this issue

## How Has This Been Tested?
on android 14 samsung f23 physical device

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

https://github.com/ankidroid/Anki-Android/assets/116078997/5d330151-1756-425f-8c0e-e08883762df9

2024-07-08 12:59 UTC, david-allison requested changes
Looks great! One minor improvement, then good to go

2024-07-08 13:07 UTC, MinusMallard commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
> +        shownDialog?.dismiss()
closing dialog behaviour is not specifically because of 'done' I think it should happen even when ok button is pressed also it's just 'shownDialog?.dismiss()' was present under createDeck function but not under renameDeck function so renaming had this issue that dialog was not closing doesn't matter what is pressed 'ok' button or 'done' button however I can add a comment mentioning both of the factor. whatever you prefer!!!

2024-07-08 13:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
> +        shownDialog?.dismiss()
Sounds good to me

2024-07-08 13:34 UTC, david-allison approved these changes

2024-07-12 18:41 UTC, david-allison commented
Ideally use 

`* Fixes #16690` so it also provides a summary of the issue:

* Fixes #16690

2024-07-12 19:05 UTC, BrayanDSO approved these changes

2024-07-12 19:06 UTC, merged

2024-07-12 20:33 UTC, Arthur-Milchior commented
Congrats on your first merged PR @MinusMallard.
Are you on our discord?

2024-09-08 20:55 UTC, Arthur-Milchior commented
Actually, it's still buggy. Because you do "ok" unconditionally, while sometime "ok" is disabled. So you end up creating deck that should not exists