Add Right-Click Support to Long Click Listeners
ankidroid/Anki-Android pull request #16712
Opened 2024-07-09 19:09 UTC by SanjaySargam

## Purpose / Description
This PR introduces functionality to support right-click actions wherever long click listeners are implemented in the application. This enhancement aims to improve user experience by providing additional interaction capabilities on devices that support right-click actions.

## Approach
```kotlin
yourView.setOnContextClickListener {
    showContextMenu()
    true
}
``` 

## How Has This Been Tested?
HP Chromebook

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-07-11 22:56 UTC, Arthur-Milchior requested changes

2024-07-11 22:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    private val deckLongClickListener = OnLongClickListener { v ->
I'd have a slight preference for having it directly on top of `showDeckPickerContextMenu`. Just to reduce the size of the diff.
And then `deckContextClickListener` even on top of it

2024-07-11 22:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +    private fun showSubDeckDialog(parentDeckPath: String, deckID: DeckId) {
Please add some javadoc. 
It used to be very clear what this method was doing. Now that it may not open the subdeck dialog, it's important to note this special case

2024-07-11 22:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +                deckHolder.setOnContextClickListener { // creating sub deck with parent deck path
It seems that each time you introduce `setOnContextClickListener` in the codebase, it does the same thing as `setOnLongClickListener`

I'd suggest we do something such as
```kotlin


    /**
     * A listener that has the same action for both "context click"  (i.e. mostly right click) and "long click" (i.e. holding the finger on the view).
     */
    interface OnContextAndLongClickListener: OnContextClickListener, OnLongClickListener {
        fun onAction(v: View): Boolean
        override fun onContextClick(v: View): Boolean {
            Timber.i("${this.javaClass}: user context clicked")
            return onAction(v)
        }
        override fun onLongClick(v: View): Boolean {
            Timber.i("${this.javaClass}: user long clicked")
            return onAction(v)
        }

        companion object {
            /**
             * Ensures [this] gets both a long click and a context click listener.
             * @see View.setOnLongClickListener
             * @see View.setOnContextClickListener
             */
            fun View.setContextAndLongClickListener(listener: OnContextAndLongClickListener) {
                setOnLongClickListener(listener)
                setOnContextClickListener(listener)
            }
        }
    }
```

Maybe not exactly as-is, if we can improve the usage.
Still, it would ensure we don't need to duplicate code everywhere, given that we'll probably never want to have one listener and not the other

2024-07-11 22:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
> +    fun setDeckContextClickListener(listener: OnContextClickListener?) {
Why is the parameter nullable ?

2024-07-11 22:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
> +        deckContextClickListener = listener
If the setter is public, I think the whole var can be public.

2024-07-12 08:18 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
> +    fun setDeckContextClickListener(listener: OnContextClickListener?) {
reason:
```kotlin
    var deckContextClickListener: OnContextClickListener? = null

```

2024-07-12 08:40 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
> +    fun setDeckContextClickListener(listener: OnContextClickListener?) {
reason: 
```kotlin
    var deckContextClickListener: OnContextClickListener? = null

```

2024-07-12 18:03 UTC, david-allison requested changes
Improved using `fun interface` (SAM Interfaces: https://kotlinlang.org/docs/fun-interfaces.html)

```patch
Subject: [PATCH] refactor(card-browser): remove unused methods
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt	(revision cada620c80d29b9b04c87e2691313822eb6da07d)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt	(date 1720807369193)
@@ -280,13 +280,11 @@
                 expander.setOnClickListener {
                     toggleExpansion(deckID)
                 }
-                deckHolder.setOnContextAndLongClickListener(object : OnContextAndLongClickListener {
-                    override fun onAction(v: View): Boolean {
-                        // creating sub deck with parent deck path
-                        showSubDeckDialog(deckName, deckID)
-                        return true
-                    }
-                })
+                deckHolder.setOnContextAndLongClickListener {
+                    // creating sub deck with parent deck path
+                    showSubDeckDialog(deckName, deckID)
+                    true
+                }
             }
 
             private fun toggleExpansion(deckId: Long) {
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(revision cada620c80d29b9b04c87e2691313822eb6da07d)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(date 1720807369200)
@@ -2007,11 +2007,9 @@
 
             // Allow Ctrl + 1...Ctrl + 0 for item 10.
             v.tag = (visualIndex % 10).toString()
-            v.setOnContextAndLongClickListener(object : OnContextAndLongClickListener {
-                override fun onAction(v: View): Boolean {
-                    displayEditToolbarDialog(b)
-                    return true
-                }
+            v.setOnContextAndLongClickListener(OnContextAndLongClickListener {
+                displayEditToolbarDialog(b)
+                true
             })
         }
 
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt	(revision cada620c80d29b9b04c87e2691313822eb6da07d)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt	(date 1720807369202)
@@ -190,20 +190,15 @@
             dialogTitle = resources.getString(R.string.card_details_tags)
             optionsGroup.visibility = View.GONE
             positiveText = getString(R.string.dialog_ok)
-            tagsArrayAdapter!!.tagContextAndLongClickListener = object : OnContextAndLongClickListener {
-                override fun onAction(v: View): Boolean {
+            tagsArrayAdapter!!.tagContextAndLongClickListener =
+                OnContextAndLongClickListener { v ->
                     createAddTagDialog(v.tag as String)
-                    return true
+                    true
                 }
-            }
         } else {
             dialogTitle = resources.getString(R.string.studyoptions_limit_select_tags)
             positiveText = getString(R.string.select)
-            tagsArrayAdapter!!.tagContextAndLongClickListener = object : OnContextAndLongClickListener {
-                override fun onAction(v: View): Boolean {
-                    return false
-                }
-            }
+            tagsArrayAdapter!!.tagContextAndLongClickListener = OnContextAndLongClickListener { false }
         }
         adjustToolbar(tagsDialogView)
         dialog = AlertDialog.Builder(requireActivity())
Index: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt	(revision cada620c80d29b9b04c87e2691313822eb6da07d)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt	(date 1720807369191)
@@ -376,12 +376,10 @@
         }
     }
 
-    private val deckContextAndLongClickListener = object : OnContextAndLongClickListener {
-        override fun onAction(v: View): Boolean {
-            val deckId = v.tag as DeckId
-            showDeckPickerContextMenu(deckId)
-            return true
-        }
+    private val deckContextAndLongClickListener = OnContextAndLongClickListener { v ->
+        val deckId = v.tag as DeckId
+        showDeckPickerContextMenu(deckId)
+        true
     }
 
     private fun showDeckPickerContextMenu(deckId: DeckId) {
Index: AnkiDroid/src/main/java/com/ichi2/anki/OnContextAndLongClickListener.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/OnContextAndLongClickListener.kt b/AnkiDroid/src/main/java/com/ichi2/anki/OnContextAndLongClickListener.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/OnContextAndLongClickListener.kt	(revision cada620c80d29b9b04c87e2691313822eb6da07d)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/OnContextAndLongClickListener.kt	(date 1720807369184)
@@ -23,7 +23,7 @@
 /**
  * A listener that has the same action for both "context click" (i.e., mostly right-click) and "long click" (i.e., holding the finger on the view).
  */
-interface OnContextAndLongClickListener : View.OnContextClickListener, View.OnLongClickListener {
+fun interface OnContextAndLongClickListener : View.OnContextClickListener, View.OnLongClickListener {
     fun onAction(v: View): Boolean
     override fun onContextClick(v: View): Boolean {
         Timber.i("${this.javaClass}: user context clicked")
```

2024-07-21 15:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/OnContextAndLongClickListener.kt
> + * A listener that has the same action for both "context click" (i.e., mostly right-click) and "long click" (i.e., holding the finger on the view).
I don't feel this was addressed

2024-07-21 15:21 UTC, david-allison requested changes
Missed a comment - feels like a GitHub bug

2024-07-21 15:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/OnContextAndLongClickListener.kt
> + * A listener that has the same action for both "context click" (i.e., mostly right-click) and "long click" (i.e., holding the finger on the view).
I left this in as https://github.com/ankidroid/Anki-Android/pull/16712/files#r1676294753, but it seems the comment chain doesn't appear on the PR

2024-07-21 17:16 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/OnContextAndLongClickListener.kt
> + * A listener that has the same action for both "context click" (i.e., mostly right-click) and "long click" (i.e., holding the finger on the view).
@david-allison Addressed. Kindly check once

2024-07-21 17:30 UTC, david-allison approved these changes

2024-07-21 17:30 UTC, david-allison commented
Really clean, thanks!

2024-07-28 03:11 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +                deckHolder.setOnContextClickListener { // creating sub deck with parent deck path
To be clear, when I state "something such as", or similar requirement, you don't have to copy-paste it as-is. I don't guarantee that it's working properly. 
In particular, if you tested the Timber, you'd see it gives
> class com.ichi2.anki.DeckPicker$$ExternalSyntheticLambda6: user long clicked

Which to be honest I only realized because I could not guess what would be the class of `this` with your implementation.


I admit that I have no great idea about how to solve that. I would have loved to have an extra parameter which is a string value, but that would make the code far less readable, since we could not use only the declaration as a single function.
Worse, the TagsArrayAdapter is not easy to correct

As I've no better idea, I guess we can leave it as is. Unless someone wiser find a good solution that don't require too much work.
I doubt it'll really impede debugging, given the small number of place it's used in each file.

2024-07-28 03:16 UTC, Arthur-Milchior approved these changes

2024-07-28 03:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/OnContextAndLongClickListener.kt
> +        Timber.i("${this.javaClass}: user context clicked")
To be clear, when I state "something such as", or similar requirement, you don't have to copy-paste it as-is. I don't guarantee that it's working properly. 
In particular, if you tested the Timber, you'd see it gives
> class com.ichi2.anki.DeckPicker$$ExternalSyntheticLambda6: user long clicked

Which to be honest I only realized because I could not guess what would be the class of `this` with your implementation.


I admit that I have no great idea about how to solve that. I would have loved to have an extra parameter which is a string value, but that would make the code far less readable, since we could not use only the declaration as a single function.
Worse, the TagsArrayAdapter is not easy to correct

As I've no better idea, I guess we can leave it as is. Unless someone wiser find a good solution that don't require too much work.
I doubt it'll really impede debugging, given the small number of place it's used in each file.

2024-07-28 03:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    private fun showDeckPickerContextMenu(deckId: DeckId) {
I'm fine with having a function that is just a function. But in this case, I think you should not have the value deckContextAndLongClickListener and directly move its content at the only place where it's used

2024-07-28 03:17 UTC, Arthur-Milchior commented
I'll want a little bit of changes, but essentially, I approve the commit as it is. If you find a way to improve timber let us know, otherwise I just want you to add the documentation/comment please

2024-07-28 14:30 UTC, merged