[GSoC'24] CardTemplateEditor: Implementation of Keyboard Shortcuts
ankidroid/Anki-Android pull request #16722
Opened 2024-07-11 17:34 UTC by SanjaySargam

## Purpose / Description
Implement keyboard shortcuts to enhance the user experience by providing quick access to commonly used functionalities within the application. This will improve the overall usability, especially for power users who prefer using the keyboard over the mouse.

## Approach
The shortcuts are implemented by adding event listeners for keypress events and mapping them to the respective functions. The approach ensures that the shortcuts are intuitive and do not conflict with existing shortcuts.

## How Has This Been Tested?
HP Chromebook

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-07-11 18:19 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> -                            R.id.action_add -> {
Menu options don't need to be removed just extract the logic

2024-07-11 18:36 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> -                            R.id.action_add -> {
DIdn't removed

2024-07-11 19:48 UTC, criticalAY reviewed
```patch
Subject: [PATCH] Template
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt	(revision 49cae72ffb7fe08a5a9a77a0c87b8bf1dac5b2b2)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt	(date 1720726825334)
@@ -564,25 +564,50 @@
                     }
 
                     override fun onMenuItemSelected(menuItem: MenuItem): Boolean {
-                        when (menuItem.itemId) {
+                        return when (menuItem.itemId) {
                             R.id.action_add -> addCard()
-                            R.id.action_reposition -> showRepositionDialog()
-                            R.id.action_rename -> showRenameDialog()
-                            R.id.action_copy_as_markdown -> copyMarkdownTemplateToClipboard()
-                            R.id.action_insert_field -> showInsertFieldDialog()
-                            R.id.action_delete -> deleteCard()
+                            R.id.action_reposition -> {
+                                showRepositionDialog()
+                                return true
+                            }
+
+                            R.id.action_rename -> {
+                                showRenameDialog()
+                                return true
+                            }
+
+                            R.id.action_copy_as_markdown -> {
+                                copyMarkdownTemplateToClipboard()
+                                return true
+
+                            }
+
+                            R.id.action_insert_field -> {
+                                showInsertFieldDialog()
+                                return true
+
+                            }
+
+                            R.id.action_delete -> {
+                                return deleteCard()
+                            }
+
                             R.id.action_add_deck_override -> {
                                 displayDeckOverrideDialog(tempModel)
                                 return true
                             }
+
                             R.id.action_preview -> {
                                 performPreview()
                                 return true
                             }
+
                             R.id.action_confirm -> saveNote()
                             R.id.action_card_browser_appearance -> openBrowserAppearance()
+                            else -> {
+                               false
+                            }
                         }
-                        return false
                     }
                 },
                 viewLifecycleOwner,
```

should resolve the test issue

2024-07-11 20:16 UTC, SanjaySargam commented
@criticalAY Thank You ❤️

2024-07-11 22:11 UTC, Arthur-Milchior requested changes

2024-07-11 22:11 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +                                deleteCard()
Please call it `deleteNote`, because you'll delete the whole note

2024-07-11 22:11 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +        fun addCard(): Boolean {
Please call it `addCardTemplate`. You're adding card templates. As a side effect it add cards, but that's not the main effect.

2024-07-11 22:11 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +        fun deleteCard(): Boolean {
Please call it `deleteCardTemplate`. Same reason as "addCard" above

2024-07-11 22:11 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +                return true
As for `addCard`, I'd prefer you don't return a boolean, given it's always the same value.
But keep the early return

2024-07-11 22:11 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +        fun saveNote(): Boolean {
`saveNoteType`

2024-07-12 11:58 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +        fun deleteCard(): Boolean {
@Arthur-Milchior in previous review you said 

> Please call it deleteNote, because you'll delete the whole note

2024-07-18 18:51 UTC, david-allison approved these changes
LGTM, cheers!

2024-07-18 18:51 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +        if (event.isCtrlPressed) {
I don't understand this comment given the provided code. Maybe it was fixed already

2024-07-28 14:13 UTC, Arthur-Milchior approved these changes

2024-07-28 14:28 UTC, merged