Fix: update set due date card snackbar
ankidroid/Anki-Android pull request #16738
Opened 2024-07-15 06:04 UTC by Giyutomioka-SS

## Purpose / Description
This pull request fixes the snackbar message in AnkiDroid when setting a card's due date. The current message says "1 card rescheduled," which is incorrect. The update changes it to "Set due date of 1 card" to accurately reflect the action taken by the user.

## Fixes
* Fixes #16732 

## How Has This Been Tested?
Realme 6 (API-30) and Emulator

## Screenshot
![image (8)](https://github.com/user-attachments/assets/7da5feba-1ce2-48a1-8841-9391fd925da9)

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-07-15 07:15 UTC, lukstbit requested changes
Please fix the lint issues.

2024-07-15 08:05 UTC, criticalAY requested changes
String should be declared in base folder/file, you have not declared the string at correct place

2024-07-15 10:11 UTC, Giyutomioka-SS reviewed
I guess we can remove this
`<!-- Reschedule Card Dialog -->
    <plurals name="reschedule_cards_dialog_acknowledge" tools:ignore="UnusedResources">
    <item quantity="one">%d card rescheduled</item>
    <item quantity="other">%d cards rescheduled</item>
    </plurals>`

2024-07-15 11:03 UTC, user1823 requested changes
Instead of creating a new string, reuse the string from the backend.

2024-07-16 10:50 UTC, user1823 approved these changes
LGTM. My approval doesn't count, though.

2024-07-16 15:53 UTC, criticalAY approved these changes
Looks good! 
Note for 2nd reviewer the unused string need to be removed and deleting the base file string produces lint error in one of the translated file

2024-07-19 09:24 UTC, david-allison requested changes
Looks good! One blocking request

Only change `03-dialogs`, our translation sync handles the other languages

2024-07-19 09:24 UTC, david-allison commented on AnkiDroid/src/main/res/values/03-dialogs.xml
>      </plurals>
If it's unused, remove it

2024-07-19 11:22 UTC, Giyutomioka-SS commented
@david-allison  Checks are failing.

2024-07-19 11:26 UTC, david-allison approved these changes
4 lines added, 23 removed... today is a great day, thanks!

2024-07-19 11:27 UTC, david-allison commented
Checks should be fixed with: https://github.com/ankidroid/Anki-Android/commit/8c352ec3de068ef8c42dfd343408afae234b9812

2024-07-19 11:33 UTC, Giyutomioka-SS commented
> 4 lines added, 23 removed... today is a great day, thanks!

Indeed! 😂

2024-07-19 17:10 UTC, mikehardy commented
rebased to current main, pushed, CI re-running, hopefully goes green ...

2024-07-19 17:52 UTC, david-allison commented
```
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-iw/03-dialogs.xml:71: Error: The plurals "reschedule_cards_dialog_acknowledge" in values-iw has no declaration in the base values folder; this can lead to crashes when the resource is queried in a configuration that does not match this qualifier [MissingDefaultResource]
    <plurals name="reschedule_cards_dialog_acknowledge">
```

Interesting, this one is on us

2024-07-19 18:28 UTC, david-allison commented
* https://github.com/ankidroid/Anki-Android/labels/Blocked%20by%20dependency https://github.com/ankidroid/Anki-Android/pull/16763

Please revert your changes and remove the string from `values` again

2024-07-19 19:06 UTC, david-allison commented
Merged. Needs a rebase and revert to removing the string

2024-07-19 20:24 UTC, Giyutomioka-SS commented
> Merged. Needs a rebase and revert to removing the string

Done.

2024-07-19 20:55 UTC, david-allison approved these changes
Thanks so much!

2024-07-20 07:36 UTC, lukstbit approved these changes
Thanks!

2024-07-20 07:52 UTC, merged