enhancement: add long press listener on cloze button
ankidroid/Anki-Android pull request #16735
Opened 2024-07-14 12:37 UTC by criticalAY

## Purpose / Description
This PR further improvise the instant editor by allowing user to manually edit the cloze number by long pressing the cloze number button in the dialog 

## How Has This Been Tested?

Tested on OnePlus Nord CE:
https://github.com/user-attachments/assets/62f532cf-8fd6-42ba-a665-26b0201c128d

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-07-16 16:39 UTC, david-allison requested changes
I was expecting "long press on a clozed word to change the cloze number"

I don't think allowing the user to change the current global cloze number has many use cases

2024-07-16 16:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +        shownDialog = AlertDialog.Builder(this).show {
Could you comment as to why you're not using `IntegerDialog` here

2024-07-17 10:40 UTC, david-allison reviewed
Looks great! minor requests

A test here would be great

2024-07-17 10:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/EditorChips.kt
> +            viewModel.getWordClozeNumber(data.word)
nit: this would be more readable as a `val` + early return

2024-07-17 10:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/EditorChips.kt
> +                    (this as AnkiActivity).updateClozeNumber(oldClozeNumber) { clozeNumber ->
Make the receiver an `AnkiActivity` rather than performing a cast

2024-07-17 10:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/EditorChips.kt
> +                    (this as AnkiActivity).updateClozeNumber(oldClozeNumber) { clozeNumber ->
`displayUpdateClozeNumberDialog`

2024-07-17 10:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> +
revert

2024-07-17 10:40 UTC, david-allison commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="cloze_number">Cloze number:</string>
Does this match other dialogs? A colon seems out of place

2024-07-17 10:46 UTC, criticalAY commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="cloze_number">Cloze number:</string>
yes it does i.e. `<string name="reposition_card_dialog_message">Start position:</string>`

2024-07-17 15:29 UTC, criticalAY commented
@ShridharGoel I resolved them locally but something important came up so forgot to push

2024-07-18 12:59 UTC, david-allison approved these changes
Looks great, cheers!

2024-07-18 12:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/EditorChips.kt
> +            }
much nicer!

2024-07-18 12:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/EditorChips.kt
> + *
nit: could do with an example here

2024-07-19 09:03 UTC, david-allison commented
* https://github.com/ankidroid/Anki-Android/pull/16758

2024-07-19 10:30 UTC, merged

2024-07-19 11:29 UTC, david-allison commented
* https://github.com/ankidroid/Anki-Android/pull/16761