[GSoC'24] Enhancement of Media Drop Feature in NoteEditor
ankidroid/Anki-Android pull request #16749
Opened 2024-07-17 17:02 UTC by SanjaySargam

## Purpose / Description
This PR enhances the existing functionality of dropping media files in the NoteEditor (FixedEditText). Previously, only photos could be dropped. With this enhancement, users can now also drop video and audio files into the FixedEditText.

## Approach
To implement this feature, I utilized the `DropHelper` class instead of the traditional drag-and-drop mechanisms.

**Why DropHelper?**
Simplified Implementation: DropHelper provides a straightforward and high-level API for managing drop actions, reducing the complexity of handling multiple types of media.

## How Has This Been Tested?
HP Chromebook
[Screen recording 2024-07-17 10.30.17 PM.webm](https://github.com/user-attachments/assets/1695385d-1f65-427f-8c4c-7cc531ec0ec4)

## Learning (optional, can help others)
https://medium.com/androiddevelopers/simplifying-drag-and-drop-3713d6ef526e
https://developer.android.com/reference/androidx/draganddrop/DropHelper

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-07-18 21:04 UTC, david-allison commented on gradle/libs.versions.toml
> +minSdk = "24"  # also in testlib/build.gradle.kts
As discussed, put this behind `compat` so we don't need to bump the `minSdk`

2024-07-21 15:55 UTC, david-allison commented
Provided a patch for API 23 compat in Discord. Please include that, along with the error message

```patch
Subject: [PATCH]
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(revision 26727088028dca0bbaa605bdb2600a13308d9b77)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(date 1721576715628)
@@ -69,7 +69,6 @@
 import androidx.core.text.HtmlCompat
 import androidx.core.view.OnReceiveContentListener
 import androidx.core.view.isVisible
-import androidx.draganddrop.DropHelper
 import androidx.lifecycle.lifecycleScope
 import anki.config.ConfigKey
 import anki.notes.NoteFieldsCheckResponse
@@ -121,6 +120,8 @@
 import com.ichi2.annotations.NeedsTest
 import com.ichi2.compat.CompatHelper.Companion.getSerializableCompat
 import com.ichi2.compat.CompatHelper.Companion.registerReceiverCompat
+import com.ichi2.compat.DropHelperCompat
+import com.ichi2.compat.DropHelperOptionsBuilder
 import com.ichi2.libanki.Card
 import com.ichi2.libanki.Collection
 import com.ichi2.libanki.Consts
@@ -139,7 +140,6 @@
 import com.ichi2.libanki.utils.TimeManager
 import com.ichi2.utils.AdaptionUtil
 import com.ichi2.utils.ClipboardUtil
-import com.ichi2.utils.ClipboardUtil.MEDIA_MIME_TYPES
 import com.ichi2.utils.ClipboardUtil.hasMedia
 import com.ichi2.utils.HashUtil
 import com.ichi2.utils.ImageUtils
@@ -1630,11 +1630,9 @@
                     description!!
                 )
             }
-            DropHelper.configureView(
-                this,
+            DropHelperCompat.configureView(
                 editLineView,
-                MEDIA_MIME_TYPES,
-                DropHelper.Options.Builder()
+                DropHelperOptionsBuilder()
                     .setHighlightColor(R.color.material_lime_green_A700)
                     .setHighlightCornerRadiusPx(0)
                     .addInnerEditTexts(newEditText)
Index: AnkiDroid/src/main/AndroidManifest.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/AndroidManifest.xml b/AnkiDroid/src/main/AndroidManifest.xml
--- a/AnkiDroid/src/main/AndroidManifest.xml	(revision 26727088028dca0bbaa605bdb2600a13308d9b77)
+++ b/AnkiDroid/src/main/AndroidManifest.xml	(date 1721576525705)
@@ -21,6 +21,10 @@
 <manifest xmlns:android="http://schemas.android.com/apk/res/android"
     xmlns:tools="http://schemas.android.com/tools"
     android:installLocation="auto">
+
+    <!-- Requires minSdk 24, but we wrap this in compat -->
+    <uses-sdk tools:overrideLibrary="androidx.draganddrop"/>
+
     <uses-feature android:name="android.hardware.camera" android:required="false" />
     <uses-feature android:name="android.hardware.camera.any" android:required="false" />
     <uses-feature android:name="android.hardware.audio.output" android:required="false" />
Index: gradle/libs.versions.toml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/gradle/libs.versions.toml b/gradle/libs.versions.toml
--- a/gradle/libs.versions.toml	(revision 26727088028dca0bbaa605bdb2600a13308d9b77)
+++ b/gradle/libs.versions.toml	(date 1721576015076)
@@ -1,6 +1,6 @@
 [versions]
 compileSdk = "34"
-minSdk = "24"  # also in testlib/build.gradle.kts
+minSdk = "23"  # also in testlib/build.gradle.kts
 targetSdk = "34"  # also in  ../robolectricDownloader.gradle
 acra = '5.11.3'
 amazonappstorepublisher = "0.1.0"
Index: AnkiDroid/src/main/java/com/ichi2/compat/DropHelperCompat.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/compat/DropHelperCompat.kt b/AnkiDroid/src/main/java/com/ichi2/compat/DropHelperCompat.kt
new file mode 100644
--- /dev/null	(date 1721576755570)
+++ b/AnkiDroid/src/main/java/com/ichi2/compat/DropHelperCompat.kt	(date 1721576755570)
@@ -0,0 +1,59 @@
+/*
+ *  Copyright (c) 2024 David Allison <davidallisongithub@gmail.com>
+ *
+ *  This program is free software; you can redistribute it and/or modify it under
+ *  the terms of the GNU General Public License as published by the Free Software
+ *  Foundation; either version 3 of the License, or (at your option) any later
+ *  version.
+ *
+ *  This program is distributed in the hope that it will be useful, but WITHOUT ANY
+ *  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
+ *  PARTICULAR PURPOSE. See the GNU General Public License for more details.
+ *
+ *  You should have received a copy of the GNU General Public License along with
+ *  this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+package com.ichi2.compat
+
+import android.app.Activity
+import android.os.Build
+import android.view.View
+import androidx.core.view.OnReceiveContentListener
+import androidx.draganddrop.DropHelper
+import com.ichi2.utils.ClipboardUtil.MEDIA_MIME_TYPES
+
+typealias DropHelperOptionsCompat = DropHelper.Options
+typealias DropHelperOptionsBuilder = DropHelper.Options.Builder
+
+/**
+ * We have applied `tools:overrideLibrary="androidx.draganddrop"` so we manually need to handle
+ * compat of [DropHelper]
+ */
+object DropHelperCompat {
+
+    /**
+     * Configures a [View] for drag and drop operations, including the highlighting that
+     * indicates the view is a drop target. Sets a listener that enables the view to handle dropped
+     * data.
+     *
+     * @see DropHelper.configureView
+     */
+    context (Activity)
+    fun configureView(
+        view: View,
+        options: DropHelperOptionsCompat,
+        onReceiveContentListener: OnReceiveContentListener
+    ) {
+        // library will fail < API 24
+        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.N) return
+
+        DropHelper.configureView(
+            this@Activity,
+            view,
+            MEDIA_MIME_TYPES,
+            options,
+            onReceiveContentListener
+        )
+    }
+}
\ No newline at end of file
```

2024-07-21 18:15 UTC, david-allison requested changes

2024-07-21 18:15 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
> +        }
I don't think this `isImage` is correct for SVG.

Consider another strategy

2024-07-21 18:15 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        val remaining = pair.second
```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(revision 0ba534fc0510823a0c62158eb5f9620f43501224)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(date 1721585234412)
@@ -69,6 +69,8 @@
 import androidx.core.content.res.ResourcesCompat
 import androidx.core.os.BundleCompat
 import androidx.core.text.HtmlCompat
+import androidx.core.util.component1
+import androidx.core.util.component2
 import androidx.core.view.OnReceiveContentListener
 import androidx.core.view.isVisible
 import androidx.fragment.app.activityViewModels
@@ -380,9 +382,7 @@
      * This listener processes URIs contained in the payload and attempts to paste the content into the target EditText view.
      */
     private val onReceiveContentListener = OnReceiveContentListener { view, payload ->
-        val pair = payload.partition { item -> item.uri != null }
-        val uriContent = pair.first
-        val remaining = pair.second
+        val (uriContent, remaining) = payload.partition { item -> item.uri != null }
 
         if (uriContent == null) {
             return@OnReceiveContentListener remaining
```

2024-07-21 18:15 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                CrashReportService.sendExceptionReport(e, "NoteEditor::onMedia")
change the string

2024-07-21 18:15 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        for (j in 0 until clip.itemCount) {
nitpick for readability

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(revision 0ba534fc0510823a0c62158eb5f9620f43501224)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(date 1721585528787)
@@ -160,6 +160,7 @@
 import com.ichi2.utils.NoteFieldDecorator
 import com.ichi2.utils.TextViewUtil
 import com.ichi2.utils.increaseHorizontalPaddingOfOverflowMenuIcons
+import com.ichi2.utils.items
 import com.ichi2.utils.message
 import com.ichi2.utils.negativeButton
 import com.ichi2.utils.neutralButton
@@ -395,8 +396,7 @@
             return@OnReceiveContentListener remaining
         }
 
-        for (j in 0 until clip.itemCount) {
-            val uri = clip.getItemAt(j).uri
+        for (uri in clip.items().map { it.uri }) {
             try {
                 onPaste(view as EditText, uri, description)
             } catch (e: Exception) {
Index: AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt b/AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
--- a/AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt	(revision 0ba534fc0510823a0c62158eb5f9620f43501224)
+++ b/AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt	(date 1721585528778)
@@ -93,6 +93,12 @@
     }
 }
 
+fun ClipData.items() = sequence {
+    for (j in 0 until itemCount) {
+        yield(getItemAt(j))
+    }
+}
+
 /**
  * Copies the provided [text] to the clipboard (truncated if necessary, >5 lines),
  * and show either a snackbar, if possible, or a toast with a success/failure

```

2024-07-21 18:15 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
> +    private val IMAGE_MIME_TYPES = arrayOf("image/gif", "image/png", "image/jpg", "image/jpeg")
for this use case: `isImage` should probably use `image/*`?

I wouldn't change it for other use cases

2024-07-21 18:15 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="note_editor_paste_too_large">The media is too large, please insert the media manually</string>
also change the key

2024-07-21 19:13 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
> +        }
This will be removed once #16750 it is merged

2024-07-21 20:50 UTC, david-allison commented
Thanks! I'll say this is blocked on https://github.com/ankidroid/Anki-Android/pull/16750

2024-07-21 23:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
> +        }
Unblocked

2024-07-22 18:34 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
> +        }
> I don't think this isImage is correct for SVG.

Considered this case

2024-07-23 20:52 UTC, david-allison reviewed
Looks great! 

Asking for testing [unit/integration] as we'll certainly want to support extensions here, and want to guard against regressions

----

This would be easier to read if you performed the rename from `image` to `media` in a preceding commit

PS: I really appreciate you retaining my copyright header

2024-07-23 20:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
> +            ?.primaryClip
You use this pattern a lot, but it's a remnant of the Java -> Kotlin conversion

This can be simplified to `clipboard?.primaryClip`

2024-07-23 20:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
> +    private val VIDEO_MIME_TYPES = arrayOf("video/*")
I'd want to see a couple of unit tests around this code

2024-07-24 10:52 UTC, david-allison commented
Regarding the initial commit, I would also add the following.

This makes the intention of the second commit message more clear

I (unusually) provided a suggested commit message in the patch

```patch
Subject: [PATCH] note-editor: rename 'image' to 'media'

In preparation for 'Drag & Drop' work,
which will allow importing of media

---
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(revision 4cf695ee0450a04bfb7dafee8482e1eaf59736fe)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(date 1721818142497)
@@ -109,6 +109,7 @@
 import com.ichi2.anki.noteeditor.FieldState
 import com.ichi2.anki.noteeditor.FieldState.FieldChangeType
 import com.ichi2.anki.noteeditor.NoteEditorLauncher
+import com.ichi2.anki.noteeditor.Toolbar
 import com.ichi2.anki.noteeditor.Toolbar.TextFormatListener
 import com.ichi2.anki.noteeditor.Toolbar.TextWrapper
 import com.ichi2.anki.pages.ImageOcclusion
@@ -154,13 +155,11 @@
 import com.ichi2.utils.MapUtil
 import com.ichi2.utils.NoteFieldDecorator
 import com.ichi2.utils.TextViewUtil
-import com.ichi2.utils.increaseHorizontalPaddingOfOverflowMenuIcons
 import com.ichi2.utils.message
 import com.ichi2.utils.negativeButton
 import com.ichi2.utils.neutralButton
 import com.ichi2.utils.positiveButton
 import com.ichi2.utils.show
-import com.ichi2.utils.tintOverflowMenuIcons
 import com.ichi2.utils.title
 import com.ichi2.widget.WidgetStatus
 import kotlinx.coroutines.flow.first
@@ -172,12 +171,10 @@
 import java.util.LinkedList
 import java.util.Locale
 import java.util.function.Consumer
-import kotlin.collections.ArrayList
 import kotlin.math.max
 import kotlin.math.min
 import kotlin.math.roundToInt
 import androidx.appcompat.widget.Toolbar as MainToolbar
-import com.ichi2.anki.noteeditor.Toolbar as Toolbar
 
 /**
  * Allows the user to edit a note, for instance if there is a typo. A card is a presentation of a note, and has two
@@ -659,7 +656,7 @@
                 // TODO: Support all extensions
                 //  See https://github.com/ankitects/anki/blob/6f3550464d37aee1b8b784e431cbfce8382d3ce7/rslib/src/image_occlusion/imagedata.rs#L154
                 if (ClipboardUtil.hasImage(clipboard)) {
-                    val uri = ClipboardUtil.getImageUri(clipboard)
+                    val uri = ClipboardUtil.getUri(clipboard)
                     val i = Intent().apply {
                         addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                         clipData = ClipData.newUri(requireActivity().contentResolver, uri.toString(), uri)
@@ -1625,8 +1622,8 @@
             val editLineView = editLines[i]
             customViewIds.add(editLineView.id)
             val newEditText = editLineView.editText
-            newEditText.setImagePasteListener { editText: EditText?, uri: Uri? ->
-                onImagePaste(
+            newEditText.setPasteListener { editText: EditText?, uri: Uri? ->
+                onPaste(
                     editText!!,
                     uri!!
                 )
@@ -1825,8 +1822,8 @@
         }
     }
 
-    private fun onImagePaste(editText: EditText, uri: Uri): Boolean {
-        val imageTag = mediaRegistration!!.onImagePaste(uri) ?: return false
+    private fun onPaste(editText: EditText, uri: Uri): Boolean {
+        val imageTag = mediaRegistration!!.onPaste(uri) ?: return false
         insertStringInField(editText, imageTag)
         return true
     }
Index: AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt b/AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt	(revision 4cf695ee0450a04bfb7dafee8482e1eaf59736fe)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt	(date 1721818142484)
@@ -41,7 +41,7 @@
 import com.ichi2.anki.servicelayer.NoteService
 import com.ichi2.ui.FixedEditText
 import com.ichi2.utils.ClipboardUtil.IMAGE_MIME_TYPES
-import com.ichi2.utils.ClipboardUtil.getImageUri
+import com.ichi2.utils.ClipboardUtil.getUri
 import com.ichi2.utils.ClipboardUtil.getPlainText
 import com.ichi2.utils.ClipboardUtil.hasImage
 import com.ichi2.utils.KotlinCleanup
@@ -55,7 +55,7 @@
     override var ord = 0
     private var origBackground: Drawable? = null
     private var selectionChangeListener: TextSelectionListener? = null
-    private var imageListener: ImagePasteListener? = null
+    private var pasteListener: PasteListener? = null
 
     @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
     var clipboard: ClipboardManager? = null
@@ -96,8 +96,8 @@
         setDefaultStyle()
     }
 
-    fun setImagePasteListener(imageListener: ImagePasteListener?) {
-        this.imageListener = imageListener
+    fun setPasteListener(imageListener: PasteListener?) {
+        this.pasteListener = imageListener
     }
 
     @KotlinCleanup("add extension method to iterate clip items")
@@ -113,7 +113,7 @@
                     val uriContent = pair.first
                     val remaining = pair.second
 
-                    if (imageListener == null || uriContent == null) {
+                    if (pasteListener == null || uriContent == null) {
                         return remaining
                     }
 
@@ -127,7 +127,7 @@
                     for (i in 0 until clip.itemCount) {
                         val uri = clip.getItemAt(i).uri
                         try {
-                            onImagePaste(uri)
+                            onPaste(uri)
                         } catch (e: Exception) {
                             Timber.w(e)
                             CrashReportService.sendExceptionReport(e, "NoteEditor::onImage")
@@ -194,7 +194,7 @@
         // This handles both CTRL+V and "Paste"
         if (id == android.R.id.paste) {
             if (hasImage(clipboard)) {
-                return onImagePaste(getImageUri(clipboard))
+                return onPaste(getUri(clipboard))
             }
             return pastePlainText()
         }
@@ -215,11 +215,11 @@
         return false
     }
 
-    private fun onImagePaste(imageUri: Uri?): Boolean {
-        return if (imageUri == null) {
+    private fun onPaste(uri: Uri?): Boolean {
+        return if (uri == null) {
             false
         } else {
-            imageListener!!.onImagePaste(this, imageUri)
+            pasteListener!!.onPaste(this, uri)
         }
     }
 
@@ -251,8 +251,8 @@
         fun onSelectionChanged(selStart: Int, selEnd: Int)
     }
 
-    fun interface ImagePasteListener {
-        fun onImagePaste(editText: EditText, uri: Uri?): Boolean
+    fun interface PasteListener {
+        fun onPaste(editText: EditText, uri: Uri?): Boolean
     }
 
     companion object {
Index: AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt b/AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
--- a/AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt	(revision 4cf695ee0450a04bfb7dafee8482e1eaf59736fe)
+++ b/AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt	(date 1721818142487)
@@ -54,7 +54,7 @@
         ?.takeIf { it.itemCount > 0 }
         ?.getItemAt(0)
 
-    fun getImageUri(clipboard: ClipboardManager?): Uri? {
+    fun getUri(clipboard: ClipboardManager?): Uri? {
         return getFirstItem [...]

2024-07-24 10:58 UTC, david-allison requested changes
I get the following error when building locally

```
> Task :testlib:processAmazonDebugUnitTestManifest FAILED
/Users/davidallison/StudioProjects/Anki-Android/testlib/build/intermediates/tmp/manifest/test/amazon/debug/tempFile1ProcessTestManifest3204105172373074631.xml:5:5-74 Error:
	uses-sdk:minSdkVersion 23 cannot be smaller than version 24 declared in library [androidx.draganddrop:draganddrop:1.0.0] /Users/davidallison/.gradle/caches/8.9/transforms/20ebe1ae2c541e0d36502b025cdb232b/transformed/draganddrop-1.0.0/AndroidManifest.xml as the library might be using APIs not available in 23
	Suggestion: use a compatible library with a minSdk of at most 23,
		or increase this project's minSdk version to at least 24,
		or use tools:overrideLibrary="androidx.draganddrop" to force usage (may lead to runtime failures)

See https://developer.android.com/r/studio-ui/build/manifest-merger for more information about the manifest merger.
```

2024-07-24 11:57 UTC, david-allison commented
```
> Task :AnkiDroid:ktlintMainSourceSetCheck FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt:19:1 Imports must be ordered in lexicographic order without any empty lines in-between with "java", "javax", "kotlin" and aliases in the end
```

2024-07-24 14:36 UTC, david-allison requested changes
I don't get it, but this fixes it

```patch
Index: testlib/src/main/AndroidManifest.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/testlib/src/main/AndroidManifest.xml b/testlib/src/main/AndroidManifest.xml
--- a/testlib/src/main/AndroidManifest.xml	(revision ef425b96e655e7a5a32969ec8529ba9f2c8a06b8)
+++ b/testlib/src/main/AndroidManifest.xml	(date 1721831731559)
@@ -1,2 +1,14 @@
 <?xml version="1.0" encoding="utf-8"?>
-<manifest />
\ No newline at end of file
+<manifest xmlns:tools="http://schemas.android.com/tools">
+    <!--
+    overrideLibrary shouldn't be necessary as it should be handled in the AnkiDroid manifest
+    But an error occurred on build:
+    
+/Users/davidallison/StudioProjects/Anki-Android/testlib/build/intermediates/tmp/manifest/test/amazon/debug/tempFile1ProcessTestManifest12107165475509574808.xml:5:5-74 Error:
+	uses-sdk:minSdkVersion 23 cannot be smaller than version 24 declared in library [androidx.draganddrop:draganddrop:1.0.0] /Users/davidallison/.gradle/caches/8.9/transforms/20ebe1ae2c541e0d36502b025cdb232b/transformed/draganddrop-1.0.0/AndroidManifest.xml as the library might be using APIs not available in 23
+	Suggestion: use a compatible library with a minSdk of at most 23,
+		or increase this project's minSdk version to at least 24,
+		or use tools:overrideLibrary="androidx.draganddrop" to force usage (may lead to runtime failures)
+		-->
+    <uses-sdk tools:overrideLibrary="androidx.draganddrop"/>
+</manifest>
\ No newline at end of file
```

2024-07-24 17:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> -    }
This code is no longer executed on API 23

2024-07-24 17:34 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> -    }
Should I create a new file for this test or write in NoteEditorTest?

2024-07-24 19:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> -    }
NoteEditorTest if at all possible

2024-07-24 20:02 UTC, david-allison requested changes

2024-07-24 20:02 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/FieldEditLineTest.kt
> +    }
This looks incorrect, maybe I'm misunderstanding:

* Did the code to paste an image into a field work on API 23 previously?
* Does it work now?

2024-07-25 16:27 UTC, SanjaySargam commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/FieldEditLineTest.kt
> +    }
> Did the code to paste an image into a field work on API 23 previously?

Yes

> Does it work now?

Yes

2024-07-26 09:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> -    override fun onCreateInputConnection(editorInfo: EditorInfo): InputConnection? {
With apologies, I'm struggling to understand how this still works on API 23

Could you explain how it worked previously, and how it does now (in terms of called methods)

No need for a code comment, just GItHub comments

2024-07-26 09:38 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> -    override fun onCreateInputConnection(editorInfo: EditorInfo): InputConnection? {
Because of this

```kotlin
    override fun onTextContextMenuItem(id: Int): Boolean {
        // This handles both CTRL+V and "Paste"
        if (id == android.R.id.paste) {
            if (hasMedia(clipboard)) {
                return onPaste(getUri(clipboard), getDescription(clipboard))
            }
            return pastePlainText()
        }
        return super.onTextContextMenuItem(id)
    }
```

2024-07-26 09:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> -    override fun onCreateInputConnection(editorInfo: EditorInfo): InputConnection? {
That handles the context menu.

What about the IME features, such as the following in the 'bar' of the keyboard: 

![image](https://github.com/user-attachments/assets/c58ac8a7-ed99-446b-8d9d-bb9d22983cd4)

2024-07-26 10:47 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> -    override fun onCreateInputConnection(editorInfo: EditorInfo): InputConnection? {
I'm really sorry. I'm misunderstood. It does not work in API 23 previously and now. Only plain text paste working

2024-07-29 04:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> -    override fun onCreateInputConnection(editorInfo: EditorInfo): InputConnection? {
I believe this still needs to be fixed

2024-07-29 12:17 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> -    override fun onCreateInputConnection(editorInfo: EditorInfo): InputConnection? {
Yes but this issue is not related to this PR.

2024-07-29 14:02 UTC, david-allison approved these changes
LGTM, cheers!

2024-07-29 14:02 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/FieldEditLineTest.kt
> +    @SdkSuppress(maxSdkVersion = Build.VERSION_CODES.M)
I'd remove this, it doesn't test anything useful

2024-08-03 17:27 UTC, Arthur-Milchior approved these changes
Only nits. Please feel free to let me know you disagree, or you want to leave change for another PR.  Also, one question for @david-allison : Are you okay with your homepath bieng in the codebase?

I admit there were parts which were still hard for me to understand, but it's still clearly easier than the first PR you gave me, thanks

2024-08-03 17:27 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
>      fun hasImage(clipboard: ClipboardManager?): Boolean {
Please, on all methods considering "image", add some documentation stating that it may return false on svg.
If you're certain it always return "false", then state "it returns false on svg". But given that, according to [mdn](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types), the mime type of svg should be `image/svg+xml` , I assume it may returns `true` on some device.

Anyway, it seems important that any caller think about svg explicitly

2024-08-03 17:27 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
> +    private fun getFirstItem(clipboard: ClipboardManager?) = clipboard?.primaryClip
While touching this method/object, I'd consider rewriting it as `ClipboardManager?.getFirstItem() = ...` 
And similarly everywhere. I would find it nicer.
And similarly everywhere in the file

Note that you can do an automated rewrite with "ctrl+f6" and move a parameter as receive of the method, so it does the change for you.


Not mandatory, I won't block on it

2024-08-03 17:27 UTC, Arthur-Milchior commented on testlib/src/main/AndroidManifest.xml
> +    /Users/davidallison/StudioProjects/Anki-Android/testlib/build/intermediates/tmp/manifest/test/amazon/debug/tempFile1ProcessTestManifest12107165475509574808.xml:5:5-74 Error:
@david-allison do you want your path to appear in our codebase?
I'd have considered censoring the path, `/Users/davidallison/StudioProjects/` as it does not provide useful information. But that's not a requirement either to merge it

2024-08-03 17:27 UTC, Arthur-Milchior commented on testlib/src/main/AndroidManifest.xml
> +    overrideLibrary shouldn't be necessary as it should be handled in the AnkiDroid manifest
What should be handled in AnkiDroid manifest? I don't know what "it" refers to here.
In particular, what is not required?  On first read, I'd expect that you mean that you don't need to override, and could just use the standard `uses-feature android:name=`.
By looking more at the code, I understand you probably meant that we should not have to add anything, given that the current manifest otherwise implicitly use everything from AnkiDroid/src/main/AndroidManifest.xml

If I understand correctly, it would be rephrase as:

> Testlib's manifest should implicitly imports everything from `AnkiDroid/src/main/AndroidManifest.xml`, except the imports done with `overrideLibrary` it seems. So we repeat the overriden imports below. Otherwise, here is the error message we receive:

2024-08-03 17:35 UTC, david-allison commented on testlib/src/main/AndroidManifest.xml
> +    /Users/davidallison/StudioProjects/Anki-Android/testlib/build/intermediates/tmp/manifest/test/amazon/debug/tempFile1ProcessTestManifest12107165475509574808.xml:5:5-74 Error:
This is neither a security nor privacy issue to me. 

If it makes understanding the issue harder, remove it.

2024-08-04 08:59 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
>          // This handles both CTRL+V and "Paste"
> Also, note if it also deal with drag and drop

No

2024-08-04 09:01 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
> +            showThemedToast(context, context.getString(R.string.note_editor_media_too_large), false)
To reproduce try pasting video or audio

2024-08-13 15:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
>          // This handles both CTRL+V and "Paste"
Sorry, I was not clear.
I didn't mean "If it deals with drag and drop, please write it down.
I meant "Indicates whether or not it deals with drag and drop"
My understanding is that drag/drop and copy/paste use similar mechanism, so I thought it migh be a natural question, and so it would be nice to state that this is not used for drag/drop.

Honestly, given the name, I would not even have guessed it was dealing with pasting

2024-08-13 17:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
>      // JPEG is sent via pasted content
I think we can remove this comment. It may have been useful, but it seems strange here when we use so many media type

2024-08-13 17:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
> +                context.getString(
I'd consider having one sentence for video and one for audio if you can

2024-08-13 17:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
> +            if (!isSVG && isImage && shouldConvertToJPG(fileNameAndExtension.value, copyFd)) {
I feel like `shouldConvertToJPG` should handle the case of svg and checking that the media is an image.
Maybe it means giving it more arguments, such as the description. But that would allow us to simplify this part of the code.

2024-08-13 18:15 UTC, SanjaySargam commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="note_editor_media_too_large">The %1$s is too large, please insert the %2$s manually</string>
> it'd be clearer if we state that "the audio file is too large"

Similarly for video as "the audio file is too large"?

2024-08-13 18:31 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
>      fun hasImage(clipboard: ClipboardManager?): Boolean {
> where you able to make this function return false on SVG?

It returns true on SVG too

2024-08-13 18:48 UTC, SanjaySargam commented
> I think you need a space after > for it to work in markdown


@Arthur-Milchior still not

2024-08-14 00:14 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="note_editor_media_too_large">The %1$s is too large, please insert the %2$s manually</string>
Do we need the parameter?

> The file is too large to paste. Please insert it manually

2024-08-15 14:00 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="note_editor_media_too_large">The %1$s is too large, please insert the %2$s manually</string>
@david-allison whcih string parameter are you referring to ?

2024-08-15 18:49 UTC, Arthur-Milchior approved these changes

2024-08-15 18:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
> +            if (shouldConvertToJPG(fileNameAndExtension.value, copyFd, isImage)) {
I'd have considered to send the `description` directly to the function. So that you could use the mime type to check for SVG.

2024-08-15 18:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
> +        if (!isImage) {
While you are touching this file, would you mind:
* setting fileNameExtension to lowercase
* add jpeg, which is also a valid for jpg
* maybe simplify to:
```
        return when (fileNameExtension.lowercase()) {
            ".svg", ".jpg", ".jpeg", ".gif" -> false
            ".png" -> !doesInputStreamContainTransparency(fileStream)
            else -> true
        }
```

2024-08-15 18:49 UTC, Arthur-Milchior commented
Very small nit. If you're willing to address them in a different PR it's great, otherwise, no worries.
Let's merge it

2024-08-15 19:07 UTC, merged

2024-08-15 21:12 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="note_editor_media_too_large">The %1$s is too large, please insert the %2$s manually</string>
* In the original we had 1 string with a parameter (bad)
* In the update, we have 3 strings

I don't see why we need 3 strings if the context is obvious to the user. It's a file which is too large to paste.