[GSoC'24] Feature: enable instant editor for public use
ankidroid/Anki-Android pull request #16760
Opened 2024-07-19 11:01 UTC by criticalAY

## Purpose / Description
This PR lift off instant editor from dev settings and set it for public use

## Approach
Remove Instant editor from dev setting and enable the intent filters and set exported to true

## How Has This Been Tested?
Tested locally/ Oneplus Nord ce:
![image](https://github.com/user-attachments/assets/8f90af5f-14de-4805-9cdd-db6529e19ed5)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-07-19 18:00 UTC, david-allison approved these changes
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExeGZ6dWJlNzN3eGZ2czh6cmxlOXpxYWZoYm92d24zdnQ1N2tkajI5eCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/t3sZxY5zS5B0z5zMIz/giphy-downsized.gif)

2024-07-20 08:24 UTC, lukstbit commented
@criticalAY This took some conflicts from the new multimedia UI PR being merged.

2024-07-20 12:48 UTC, criticalAY commented
Have resolved the conflicts

2024-07-21 04:43 UTC, lukstbit requested changes
I'm not seeing this working properly.
If I apply the changes: _select text -> share -> see the AnkiDroid Card option(not the instant card) -> selecting this takes me to NoteEditor_

If I delete from the manifest:

```
<intent-filter>-->
    <action android:name="android.intent.action.SEND" />-->
    <category android:name="android.intent.category.DEFAULT" />-->
    <data android:mimeType="text/plain" />-->
</intent-filter>
```

From the IntentHandler2 activity entry, then when sharing text I can see the Instant Card option(but no AnkiDroid Card option) and the InstantCardActivity.

2024-07-21 04:43 UTC, lukstbit commented on AnkiDroid/src/main/AndroidManifest.xml
>          <!-- TODO: enable the filter once we are done and set export as true -->
This TODO should be deleted as well.

2024-07-21 05:41 UTC, criticalAY commented
@lukstbit sometimes Android changes the order of preference so you will find the other option not on the main share screen but after you scroll the bottom sheet a little, both options are accessible.

2024-07-21 05:49 UTC, lukstbit approved these changes
:)) Too early in the morning it seems. There's that leftover TODO in the manifest then we could merge this.

2024-07-21 06:31 UTC, merged