[GSoC'24] Enhacement: add Audio and Video multimedia options
ankidroid/Anki-Android pull request #16769
Opened 2024-07-21 08:22 UTC by criticalAY

## Purpose / Description
This PR enables the Audio/Video media option in multimedia selection and refactor some of the previous code
- ViewModel: using media instead of image, hence generalizing the string 
- Extracting menu provider so that it can be used in other classes of multimedia fragments

## How Has This Been Tested?
Tested on Oneplus Nord ce

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-07-21 08:49 UTC, criticalAY commented
Need better suggestion for the string in case no media file is selected

2024-07-21 16:49 UTC, david-allison requested changes
Only done a brief first-look through the code, really well designed!

2024-07-21 16:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt
> +class AudioVideoFragment : MultimediaFragment(R.layout.fragment_audio_video) {
comment would be useful

2024-07-21 16:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt
> +        registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
Does this work correctly if a user picks media, then the second pick fails?

Only some of the `View.GONE` changes are reverted

2024-07-21 16:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt
> +        get() = if (selectedMediaOptions == MediaOption.AUDIO_CLIP) {
nit: I would move this to `selectedMediaOptions.toTitle(context)`

2024-07-21 16:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt
> +        private var selectedMediaOptions: MediaOption = MediaOption.UNKNOWN
Don't put variables in `companion object` (global variables are bad), pass them to the instance

2024-07-21 16:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt
> +        UNKNOWN
Don't have `UNKNOWN`, make it null

2024-07-21 16:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt
> +    /** Enum class representing various media file options */
Don't mention `enum class`, just what it represents

Probably:

`The supported media types which [AudioVideoFragment]` supports

2024-07-21 16:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt
> +        (requireActivity() as MenuHost).addMenuProvider(menuProvider)
nit (probably for another cleanup PR): I'd see if we can move this to `requireAnkiActivity().addMenuProvider()`

2024-07-21 16:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt
> +    }
This isn't a good method, it combines two separate concerns

2024-07-21 16:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt
> +    }
Also note that `Formatter.formatFileSize` has different implementations (K = 1024 -> 1000) before Android O

2024-07-21 16:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt
> +                displayMediaFileSize(clipCopy.absoluteFile, R.id.media_size_textview)
Is `absoluteFile` necessary? If so, comment

2024-07-21 16:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt
> +    }
But better document the method I added 

```patch
Subject: [PATCH]
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt	(revision 76d7ca232cd6aa3b937cad5e559a79acfe1f7d0f)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt	(date 1721580205063)
@@ -103,6 +103,7 @@
 
     private lateinit var mediaPlayer: ExoPlayer
     private lateinit var playerView: PlayerView
+    private lateinit var mediaFileSize: TextView
 
     override fun onCreate(savedInstanceState: Bundle?) {
         super.onCreate(savedInstanceState)
@@ -160,7 +161,7 @@
         playerView = requireView().findViewById(R.id.player_view)
         mediaPlayer = ExoPlayer.Builder(requireContext()).build()
         playerView.player = mediaPlayer
-
+        mediaFileSize = requireView().findViewById(R.id.media_size_textview)
         playerView.setControllerAnimationEnabled(true)
 
         if (selectedMediaOptions == MediaOption.AUDIO_CLIP) {
@@ -354,7 +355,7 @@
 
                 viewModel.currentMultimediaPath = clipCopy.absolutePath
                 viewModel.selectedMultimediaLength = File(clipCopy.absolutePath).length()
-                displayMediaFileSize(clipCopy.absoluteFile, R.id.media_size_textview)
+                mediaFileSize.text = clipCopy.toHumanReadableSize()
             }
         } catch (e: Exception) {
             Timber.e(e, "Unable to copy media file from ContentProvider")
Index: AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt	(revision 76d7ca232cd6aa3b937cad5e559a79acfe1f7d0f)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt	(date 1721580205066)
@@ -20,8 +20,6 @@
 import android.os.Bundle
 import android.text.format.Formatter
 import android.view.View
-import android.widget.TextView
-import androidx.annotation.IdRes
 import androidx.annotation.LayoutRes
 import androidx.appcompat.app.AlertDialog
 import androidx.core.view.MenuHost
@@ -81,18 +79,7 @@
         (requireActivity() as MenuHost).addMenuProvider(menuProvider)
     }
 
-    /**
-     * Displays the human-readable file size of a media file in the specified TextView.
-     * This method first uses `Formatter.formatFileSize(context, length)` to get the formatted file
-     * size string based on the provided `file` and the current context retrieved using `requireContext()`.
-     *
-     * @param file The `File` object representing the media file for which to get the size.
-     * @param textView The resource ID of the TextView widget where the file size will be displayed. This parameter should be annotated with `@IdRes`.
-     */
-    fun displayMediaFileSize(file: File, @IdRes textView: Int) {
-        val size = Formatter.formatFileSize(requireContext(), file.length())
-        view?.findViewById<TextView>(textView)?.text = size
-    }
+    fun File.toHumanReadableSize(): String = Formatter.formatFileSize(requireContext(), this.absoluteFile.length())
 
     /**
      * Shows a Snackbar at the bottom of the screen with a predefined
Index: AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt	(revision 76d7ca232cd6aa3b937cad5e559a79acfe1f7d0f)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt	(date 1721579338959)
@@ -59,6 +59,7 @@
         get() = resources.getString(R.string.multimedia_editor_popup_image)
 
     private lateinit var imagePreview: ImageView
+    private lateinit var imageFileSize: TextView
 
     private val viewModel: MultimediaViewModel by viewModels()
 
@@ -147,6 +148,7 @@
         super.onViewCreated(view, savedInstanceState)
         setupMenu(multimediaMenu)
         imagePreview = view.findViewById(R.id.image_preview)
+        imageFileSize = view.findViewById(R.id.image_size_textview)
         handleSelectedImageOptions()
         setupDoneButton()
     }
@@ -240,7 +242,7 @@
     private fun updateAndDisplayImageSize(imagePath: String) {
         val file = File(imagePath)
         viewModel.selectedMultimediaLength = file.length()
-        displayMediaFileSize(file, R.id.image_size_textview)
+        imageFileSize.text = file.toHumanReadableSize()
     }
 
     private fun showLargeFileCropDialog(length: Float) {
```

2024-07-21 16:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +                        ImageOptions.UNKNOWN -> {
Again, probably best to remove `UNKNOWN`

2024-07-21 16:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +            if (viewModel.getMultimediaLength() == 0L) {
What does `length` mean?

`duration` or `fileSize`

2024-07-21 16:49 UTC, david-allison commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
> +    <string name="no_media_preview">Audio or Video not selected, select an audio or video to proceed.</string>
Where is this shown? It'll want to be updated before release

2024-07-22 00:45 UTC, snowtimeglass commented
Is it undesirable to eliminate the chances themselves that these "(media) not selected" strings and screens are shown?

(Is the elimination not feasible by showing the potentially-second bottom sheet  (app picker) in the initial screen ("Add" screen or "Edit note" screen) directly?)

<img src="https://github.com/user-attachments/assets/58882b5d-75ca-4448-af74-c4aa9944dbff" width="220px">
<img src="https://github.com/user-attachments/assets/da9b9443-b9ab-4668-8a2f-be00a0933ca0" width="220px">

Regarding the case of not selecting a media file in the picker, I guess it might be enough to just go back to the initial screen ("Add" screen or "Edit note" screen) or the initial bottom sheet, because the case is irregular.

2024-07-22 08:32 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt
> +        registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
I uodated the code to retain the previous media files in that case

2024-07-22 08:45 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt
> +    }
Thanks!

2024-07-22 08:46 UTC, criticalAY commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
> +    <string name="no_media_preview">Audio or Video not selected, select an audio or video to proceed.</string>
I am taking the suggestion from @snowtimeglass and removing the string

2024-07-22 09:21 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt
> +        (requireActivity() as MenuHost).addMenuProvider(menuProvider)
Leaving a TODO

2024-07-22 09:27 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt
> +                displayMediaFileSize(clipCopy.absoluteFile, R.id.media_size_textview)
Not required replaced

2024-07-22 10:35 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt
> +            showSomethingWentWrong()
Resolved

2024-07-22 11:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt
> +    fun File.toHumanReadableSize(): String = Formatter.formatFileSize(requireContext(), this.absoluteFile.length())
`absoluteFile` may not be necessary, I copied it from your code

(I didn't make it explicit in my patch, my mistake)

2024-07-22 11:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt
> +                displayMediaFileSize(clipCopy.absoluteFile, R.id.media_size_textview)
Should be removed in `toHumanReadableSize` as well

2024-07-23 08:45 UTC, snowtimeglass commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
>      <string name="restart">Restart</string>
<img src="https://github.com/user-attachments/assets/1d48a950-42f8-4fd9-be44-54fb00894af2" width="320px">

"Restart" might be somewhat confusing for users and misleading for translators. How about "Reselect".


```suggestion
    <string name="reselect">Reselect</string>
```

2024-07-23 08:47 UTC, criticalAY commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
>      <string name="restart">Restart</string>
Reasonable change thanks 👍🏼

2024-07-23 09:29 UTC, snowtimeglass commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
>      <string name="restart">Restart</string>
Thank you, too.

By the way, could you please guide me as to what has been done for the "Crop" icon (and its feature) in the "Add image" screen?
![image](https://github.com/user-attachments/assets/70bc89cf-98b0-4547-ae86-8a6043accdf9)
(Image from https://github.com/ankidroid/Anki-Android/pull/16673#issue-2381557104)

2024-07-23 09:56 UTC, criticalAY commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
>      <string name="restart">Restart</string>
We use canhub for cropping images, so it requires the current image URI and I extracted the code for cropping images to `ImageUtils` so we use that to handle the crop result

2024-07-23 10:53 UTC, david-allison commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
>      <string name="restart">Restart</string>
You should use the `replace image` material icon:

<img width="75" alt="Screenshot 2024-07-23 at 11 53 42" src="https://github.com/user-attachments/assets/b76ee4ca-3aea-43b8-ad52-9b9032454bd5">

https://fonts.google.com/icons?selected=Material+Symbols+Outlined:replace_image:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=replace&icon.size=24&icon.color=%23e8eaed

2024-07-23 11:06 UTC, snowtimeglass commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
>      <string name="restart">Restart</string>
@criticalAY so, after the coding, an icon for cropping is going to be revived?

2024-07-23 11:45 UTC, snowtimeglass commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
>      <string name="restart">Restart</string>
I'm trying to say...
I saw "Crop" icon in a screenshot of #16673;
![image](https://github.com/user-attachments/assets/70fcd528-fd7b-461b-8082-24a882c3c352)

while I still don't see the icon in the same screen in a debug build from [73dde8a](https://github.com/ankidroid/Anki-Android/tree/73dde8aef587460c059e0de622e90eb6742fc1af)

![image](https://github.com/user-attachments/assets/6a754c25-4a22-4a9c-928e-39041278b704)
So I'm currently supposing the "Crop" icon has temporarily been removed for some reason, and I would like to know whether the icon (and its function) in the screen can be used again in near future.

2024-07-23 11:47 UTC, criticalAY commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
>      <string name="restart">Restart</string>
Ahh it's working fine in the latest commit, I have fixed that

2024-07-23 11:51 UTC, snowtimeglass commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
>      <string name="restart">Restart</string>
Oh, that's nice. Thank you for letting me know.

2024-07-23 17:31 UTC, criticalAY commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
>      <string name="restart">Restart</string>
@david-allison applied the suggestion for all current media types i.e. audio, video, image

2024-07-25 15:32 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt
> +    // TODO: move this to requireAnkiActivity().addMenuProvider()
Will create a separate PR for this

2024-07-25 15:42 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaViewModel.kt
> +    fun getMultimediaFileSize(): Long {
Simplified

2024-07-28 16:11 UTC, david-allison requested changes
* Add Image From Camera
* Don't Crop
* Reselect
* Press "Back"
* Save Note

=> Image is not displayed

<img width="144" alt="Screenshot 2024-07-28 at 17 11 34" src="https://github.com/user-attachments/assets/25dbdfde-ccbb-4dc8-8475-4a068b2fb702">

2024-07-28 17:14 UTC, criticalAY commented
@david-allison Fixed it, cause was if the camera was dispatched again it caused an issue due to viewModel updating the URI
` viewModel.updateCurrentMultimediaPath(it.absolutePath)`

2024-07-28 17:17 UTC, david-allison requested changes
* "Done" does nothing on 'Add audio clip'

API 30 emulator

2024-07-29 04:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaActivity.kt
> + * Representing a data structure used to hold extra information for multimedia activities.
```suggestion
 * Required information for multimedia activities.
```

2024-07-29 04:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaActivity.kt
> +                EXTRA_MEDIA_OPTIONS to intent.getSerializableExtraCompat<Serializable>(EXTRA_MEDIA_OPTIONS)
style: consider an extension property on `Intent`, these lines are long and hard to quickly parse

2024-07-29 04:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaActivity.kt
> +        // used in case a fragment supports more than media operations
Use `/* */` for IDE documentation

2024-07-29 04:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaActivity.kt
> +        const val EXTRA_MEDIA_OPTIONS = "extra_media_options"
nitpick: architecture

Does this work from an implementation perspective? 

Typically you want to model options as a tuple\*: `(Class, Options)`, so you can't assign the wrong options to a fragment

Here, it feels like the options should be added/handled in the subclasses

`*` or similar to a tuple: `Fragment<TOptions>`

2024-07-29 04:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt
> +    }
nit: In this case, make it a method

2024-07-29 04:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +    /** Represents image options that a user choose from the bottom sheet which [MultimediaImageFragment] uses **/
```suggestion
    /** Image options that a user choose from the bottom sheet which [MultimediaImageFragment] uses **/
```

2024-07-29 04:39 UTC, david-allison commented
I consider this a "merge when you feel it's ready" @criticalAY. 

All my comments [besides the message in Discord about fixing the commit message] were nitpicks, and we can get this in now if you'd like

2024-07-29 15:57 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaActivity.kt
> +        const val EXTRA_MEDIA_OPTIONS = "extra_media_options"
Not clearly getting it but the getItntent in the fragment will accept only the option that are in enum it's serializable here but in fragment we have restricted the option

2024-07-29 16:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaActivity.kt
> +        const val EXTRA_MEDIA_OPTIONS = "extra_media_options"
More of a teaching experience than anything, we can skip this

2024-07-29 16:20 UTC, criticalAY commented
CI is happy we can get it in

2024-07-29 16:23 UTC, david-allison commented
* https://github.com/ankidroid/Anki-Android/labels/Strings : https://github.com/ankidroid/Anki-Android/pull/16793

2024-07-29 16:44 UTC, david-allison approved these changes

2024-07-31 14:54 UTC, david-allison commented
Looks like GitHub threw a wobbly. Let's get this in

2024-07-31 15:11 UTC, merged