[GSoC'24] Add NoteEditor to CardBrowser
ankidroid/Anki-Android pull request #16764
Opened 2024-07-19 19:05 UTC by SanjaySargam

## Purpose / Description
This feature aims to enhance the CardBrowser by adding a NoteEditor. This will allow users to edit card side by side on large screens

## Approach
1. Attach NoteEditor to CardBrowser
2. Move NoteEditor menu to CardBrowser menu
3. Hide fragment when deck is empty

## How Has This Been Tested?
Medium Tablet API 34

https://github.com/user-attachments/assets/78ada4c3-906a-402b-9432-a9e8691de71b

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-07-24 21:09 UTC, david-allison reviewed
All looks good, cheers!

2024-07-24 21:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        setContentView(R.layout.cardbrowser)
why was this renamed?

2024-07-24 21:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        fragmented = noteEditorFrame != null && noteEditorFrame!!.visibility == View.VISIBLE
can `fragmented` be a `get()`

2024-07-24 21:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            }
```suggestion
            fragment?.configureMainToolbar(menu)
```

2024-07-24 21:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        get() = NoteEditorLauncher.EditCard(viewModel.currentCardId, Direction.DEFAULT)
These should be at the top of the class

2024-07-24 21:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        inFragmentedActivity = requireActivity().javaClass == CardBrowser::class.java
This should be inverted to check the 'regular' activity

2024-07-24 21:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        fun newInstance(arguments: Bundle): NoteEditor {
Would be great to better type this instead of `Bundle`

2024-07-25 14:56 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        setContentView(R.layout.cardbrowser)
`R.layout.cardbrowser` have two layouts
1. normal
2. x-large

2024-07-25 15:02 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        fragmented = noteEditorFrame != null && noteEditorFrame!!.visibility == View.VISIBLE
No, because `fragmented` is initialised in `NavigationDrawerActivity`

2024-08-01 19:09 UTC, david-allison submitted a review, later dismissed

2024-08-11 14:44 UTC, Arthur-Milchior commented
I'm reviewing. Commenting because there is one main issue I've got that I'd want to be fixed before the feature is shipped to user.

If you are making any change, in the trailing side, and select a new card, any change you made is lost.
I'm sorry, I should have realized this sooner. But yeah, that does not really seems acceptable behavior, as it means that the user change are lost. And this could occur by simply tapping on the screen by accident.

The note editor is already able to stop the user from leaving the view if they are unsaved changes. 
In my opinion, we should not do exactly the same change. After all, it's not clear how to save the changes (the tick icon may be clear to developer; I'm not sure it is to everyone when the screen is fragmented)
Instead, I'd suggest asking the user whether they want to save the change or discard them. In particular because, if they want to resume editing, they can still "save" and then come back to the card.

2024-08-11 16:10 UTC, Arthur-Milchior reviewed
Another issue I found. Move to a deck with no card. You can still select the meny entry "copy note". And it'll copy the last selected note. This should become grayed. Same with, for "show toolbar" given that it lead to a crash if there is no note editor.

My main question is: how did you test it.
I understand this is Google Summer of Code, and you're not a quality assurance expert. Still, I'd have expected that you'd test your code with various configuration, such as phone, tablet with fragmented screen, tablet with the fragment hidden, and check all buttons. Or at least, all "note editor" related menu features.

Right now I'll keep reviewing other PR, and wait for you to answer to the remarks I made, I'll come back to it after you replied to them, or, ideally, fixed bugs and applied correction I wanted

2024-08-11 16:38 UTC, Arthur-Milchior commented
One fundamental principle of UI design is that the user must have feedback on their action.
In the stand-alone note editor, the "save" action also close the UI, which is clear feedback something occurred.
Given that we are not closing the view anymore, I believe we should have a snackbar/toast, saying "change saved"

Also, I'd be interested maybe in having a change of color in the tick. Or maybe a red dot, the same way that the "sync" button let you know you must sync, so it's clear where to click to save changes.

2024-08-11 16:57 UTC, Arthur-Milchior commented
I'd appreciate if the selected card could always be highlighted. It does not seems to be the case, for example, if you move the current card to another deck, and get a new selected card instead

2024-08-11 17:02 UTC, Arthur-Milchior commented
![2024-08-11-185915_1032x703_scrot](https://github.com/user-attachments/assets/1f585c5e-2d30-4eeb-b8ce-3c0341212d4e)
This menu is far too long. That's not usable.

I'm really not sure what the right behavior is during multi select.
I think that, on the short term, we should hide the note editor.
On the long term, it'd be nice to see the content of the note, but not being able to edit it. Just to provide informations to the user.
I understand that adding a "read only" feature to the note editor is outside the scope of GSoC. If you feel you can do it, great (still, check with David or any other reviewer whether they agree with me first). 
Otherwise, just hiding the note editor will lead to a more consistent user experience that would be simple for you to implement, hopefully

2024-08-14 14:18 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        // Hide mainToolbar if this fragment is a part of fragmented activity
I don't understand what's wrong with my comment here

2024-08-14 14:24 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        currentCardId = viewModel.cards[0].id
![image](https://github.com/user-attachments/assets/e3b5ee5d-009f-407b-9f97-3d158edfd684)

> If the card selected belongs to the new search result, I'd expect it to still appear on the right side.

It's already there as you were expecting. Will you please reproduce once?

2024-08-16 01:58 UTC, mikehardy commented
(just closing/reopening as I changed the set of github actions that run / are required, this re-triggers CI with the new set)

2024-08-17 18:23 UTC, SanjaySargam commented
> In my opinion, we should not do exactly the same change


@Arthur-Milchior I don't understand this line. Will you please explain again

2024-08-22 08:15 UTC, SanjaySargam commented
> Another issue I found. Move to a deck with no card. You can still select the meny entry "copy note". And it'll copy the last selected note. This should become grayed. Same with, for "show toolbar" given that it lead to a crash if there is no note editor.

I plan to hide note_editor menu if deck is empty

2024-09-01 02:18 UTC, Arthur-Milchior reviewed
I feel like some problem I mentioned above were not resolved:
* save provide little feedback
* Change can be lost

actually, "save" moves to the first card, but the selection still appear to be on the card that was selected, which is a very strange behavior.
I don't feel like we can merge this until those are resolved.


I appreciate that, in case of multi select, we don't have the problem of the huge menu anymore. Thats nice

@david-allison You still have your approval there, do you want to remove it or do you think it's mergeable?
 Since the feature is disabled by default, I can hear that it's mergeable. Still, I prefer if we could fix those issues first.

2024-09-01 02:18 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        currentCardId = viewModel.cards[0].id
Seems to work the way I expected right now. I won't double check with the past version of the PR

2024-09-01 02:18 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        // Sets the first card as the current card by default after searching for cards
Fine with no comment

2024-09-01 02:18 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        // Hide mainToolbar if this fragment is a part of fragmented activity
Simply that it repeat what the code states. The code already state "If this then that is gone". Usually we try to add comment if either the code is really long/complex and we can summarize, or the reason of the code is not clear to the reader

2024-09-03 11:08 UTC, SanjaySargam commented
> I feel like some problem I mentioned above were not resolved:
> 
> save provide little feedback
> Change can be lost
> actually, "save" moves to the first card, but the selection still appear to be on the card that was selected, which is a very strange behavior.
> 

@Arthur-Milchior Resolved

2025-01-10 01:34 UTC, david-allison commented
@SanjaySargam I'm going to want to get this in, probably for 2.21.

I've been the cause of a number of conflicts and should be taking responsibility to get this over the finish line

What was the resolution logic which you defined for "user has made a change, and wants to change selected card"

2025-01-11 13:08 UTC, david-allison commented
Let me know if you want me to de-conflict. My responsibility, as I caused a bunch of breakages

2025-01-11 13:51 UTC, SanjaySargam commented
Yeah. I'd be great

2025-01-11 16:01 UTC, david-allison commented
@SanjaySargam please ping on Monday, I'll probably forget. Got a lot on right now

2025-01-11 16:13 UTC, SanjaySargam commented
Ok

2025-01-13 21:29 UTC, david-allison commented
De-conflicted.

* I would move most of the logic into the VIewModel
* Instead of `selectedCardId`, this should handle `CardsOrNotes` and either pass in a NoteID, or a CardId to the Note Editor

2025-01-15 07:52 UTC, SanjaySargam commented
@david-allison ktlint fails when I try to `git merge --continue`

2025-01-15 11:44 UTC, SanjaySargam commented
> What was the resolution logic which you defined for "user has made a change, and wants to change selected card"

@david-allison The logic is that when a user makes any unsaved note editor changes while changing the card, the dialog will prompt to save or discard changes.

2025-01-16 01:49 UTC, david-allison commented
@SanjaySargam To confirm: is this ready for review?

2025-01-16 03:03 UTC, SanjaySargam commented
> @SanjaySargam To confirm: is this ready for review?

Yes

2025-01-16 04:49 UTC, david-allison commented
You probably want to squash my 'DA' commit into something which is rebaeable

2025-01-16 04:59 UTC, david-allison requested changes
Partial review due to the number of spacing changes which need to be reverted

2025-01-16 04:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
>      override var currentCardId
This is a non-null value in the ViewModel, so the comment is incorrect

And we should inline this variable so it lives in the ViewModel

2025-01-16 04:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
>                  openNoteEditorForCard(cardId)
We should move this logic to the ViewModel and test it

2025-01-16 04:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            loadNoteEditorFragmentIfFragmented(editNoteLauncher)
We should move this logic to the VIewModel and test it

2025-01-16 04:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            intent?.toCardBrowserLaunchOptions() // must be called after super.onCreate()
spacing change (probably my fault)

2025-01-16 04:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        setContentView(R.layout.cardbrowser)
I still don't understand why you didn't add two layouts named `card_browser`

2025-01-16 04:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        cardsAdapter.stateRestorationPolicy =
spacing

2025-01-16 04:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                    fragment?.saveNote()
Maybe ViewModel?

One edit can affect multiple rows [add/delete/change], are these all updated?

2025-01-16 04:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        DiscardChangesDialog.showDialog(
There should be a 'cancel' here

2025-01-16 04:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            }
can this be simplified to `as? NoteEditor`

2025-01-16 04:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        }
set it to true unconditionally

2025-01-16 04:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                SearchState.Initializing -> {}
spacing

2025-01-16 04:59 UTC, david-allison commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="save_changes_message">Do you want to save changes?</string>
Anki has 'please save your changes first'

`deckConfigPleaseSaveYourChangesFirst`

2025-01-16 10:31 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        DiscardChangesDialog.showDialog(
You mean 3 buttons ?
1. Save
2. Discard
3. Cancel

2025-01-16 13:04 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                    fragment?.saveNote()
> One edit can affect multiple rows [add/delete/change], are these all updated?

Yes

2025-01-16 16:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        DiscardChangesDialog.showDialog(
Yep. I know it's against material spec, but some users won't know about the functionality, and I don't want to give the user a choice of two destructive actions

2025-01-16 18:30 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        setContentView(R.layout.cardbrowser)
I implemented in similar way like how DeckPicker is implemented

2025-01-16 19:31 UTC, david-allison requested changes
Still got a number of spacing changes in `CardBrowser`

2025-01-16 19:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DiscardChangesDialog.kt
> +        }
If a user supplies a method without text, it is unused.

I'd make the neutral method nullable

2025-01-16 19:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        setContentView(R.layout.cardbrowser)
I understand, but can we keep the original name of the file?

2025-01-16 19:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            viewModel.currentCardId = id.toCardId(viewModel.cardsOrNotes)
Move to ViewModel & test

2025-01-16 19:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            cardsAdapter.focusedRow = id
move to ViewModel & test

2025-01-16 19:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        if (!sharedPrefs().getBoolean("split_cardbrowser", false)) {
I'd remove the preference. We're making a lot of CardBrowser changes in 2.21, let's go live with it

2025-01-16 19:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            (noteEditorFrame?.visibility == View.VISIBLE).apply {
on second thought, just `Timber.i`  using `fragmented`:

Timber.i("Using split Browser: %b", fragmented)

2025-01-16 19:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +
spacing changes need reverting

2025-01-16 19:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        if (fragmented) {
Probably ViewModel & react to a flow

2025-01-17 14:22 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        if (fragmented) {
Would you guide me here?

2025-01-22 17:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        if (fragmented) {
Sorry, message me on the 27th

The basic idea is that the Activity/Fragment should call a method on the ViewModel
The ViewModel decides the actions to take and performs them, typically inside `viewModelScope`
The ViewModel uses `Flow` to signal to the Activity/Fragment that a change is made

This allows us to separate the business logic from the View logic, add fast tests to the ViewModel (as it's non-Android), and reduce the complexity of the Browser

2025-01-26 04:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        if (fragmented) {
@SanjaySargam Very close! 

If you can, aim to move most of the business logic to the ViewModel, as seen in this patch.

We're still working through this refactoring on the whole ViewModel, if it's simple then do it, if it's not then leave it.

This should also make it VERY easy to add tests in `CardBrowserViewModelTest`

```patch
Subject: [PATCH] improvement(release): clarify files are under 'Assets'

When I looked at the page, `Assets` was collapsed
and had the same section styles as the other h2s
so it was hard to distinguish what "Install `arm64-v8a`" meant
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt b/AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt	(revision 62210ec3d5150d804434802f5e2e57f402765c90)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt	(date 1737865033451)
@@ -186,14 +186,7 @@
     val flowOfSelectedRows: Flow<Set<CardOrNoteId>> =
         flowOf(selectedRows).combine(refreshSelectedRowsFlow) { row, _ -> row }
 
-    suspend fun handleLongPress(id: CardOrNoteId) {
-        currentCardId = id.toCardId(cardsOrNotes)
-        if (isInMultiSelectMode && lastSelectedId != null) {
-            selectRowsBetween(lastSelectedId!!, id)
-        } else {
-            toggleRowSelection(id)
-        }
-    }
+    val flowOfFocusedRow = MutableStateFlow<CardOrNoteId?>(null)
 
     suspend fun queryAllSelectedCardIds() = selectedRows.queryCardIds(this.cardsOrNotes)
 
@@ -399,6 +392,17 @@
         Timber.d("manualInit")
     }
 
+
+    fun handleRowLongPress(id: CardOrNoteId) = viewModelScope.launch {
+        currentCardId = id.toCardId(cardsOrNotes)
+        if (isInMultiSelectMode && lastSelectedId != null) {
+            selectRowsBetween(lastSelectedId!!, id)
+        } else {
+            toggleRowSelection(id)
+        }
+        flowOfFocusedRow.emit(id)
+    }
+    
     /** Whether any rows are selected */
     fun hasSelectedAnyRows(): Boolean = selectedRows.isNotEmpty()
 
Index: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt	(revision 62210ec3d5150d804434802f5e2e57f402765c90)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt	(date 1737865033447)
@@ -366,15 +366,6 @@
             }
         }
 
-    @VisibleForTesting
-    fun onLongPress(id: CardOrNoteId) {
-        launchCatchingTask {
-            viewModel.handleLongPress(id)
-            cardsAdapter.focusedRow = id
-            loadNoteEditorFragmentIfFragmented(editNoteLauncher)
-        }
-    }
-
     override fun onCreate(savedInstanceState: Bundle?) {
         if (showedActivityFailedScreen(savedInstanceState)) {
             return
@@ -418,7 +409,7 @@
                 this,
                 viewModel,
                 onTap = ::onTap,
-                onLongPress = ::onLongPress,
+                onLongPress = viewModel::handleRowLongPress,
             )
         cardsListView.adapter = cardsAdapter
         cardsAdapter.stateRestorationPolicy = RecyclerView.Adapter.StateRestorationPolicy.PREVENT_WHEN_EMPTY
@@ -626,6 +617,11 @@
                 }
             }
         }
+        
+        fun onSelectedRowUpdated(id: CardOrNoteId?) {
+            cardsAdapter.focusedRow = id
+            loadNoteEditorFragmentIfFragmented(editNoteLauncher)
+        }
 
         viewModel.flowOfIsTruncated.launchCollectionInLifecycleScope(::onIsTruncatedChanged)
         viewModel.flowOfSearchQueryExpanded.launchCollectionInLifecycleScope(::onSearchQueryExpanded)
@@ -638,6 +634,7 @@
         viewModel.flowOfCardsUpdated.launchCollectionInLifecycleScope(::cardsUpdatedChanged)
         viewModel.flowOfSearchState.launchCollectionInLifecycleScope(::searchStateChanged)
         viewModel.flowOfColumnHeadings.launchCollectionInLifecycleScope(::onColumnNamesChanged)
+        viewModel.flowOfFocusedRow.launchCollectionInLifecycleScope(::onSelectedRowUpdated)
     }
 
     // Finish initializing the activity after the collection has been correctly loaded
```

2025-03-22 23:05 UTC, Arthur-Milchior commented
y'ouve a merge conflict @SanjaySargam 
Can you also tell whether you did what David requested? I see some open comments without answer

2025-03-24 21:04 UTC, SanjaySargam commented
@Arthur-Milchior merge conflict resolved.

> Can you also tell whether you did what David requested? I see some open comments without answer

Yes, all changes are done. Forgot to resolve conversations

2025-04-13 08:36 UTC, david-allison requested changes
Few minor changes. Haven't tested this on device

2025-04-13 08:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            cardsAdapter.focusedRow = id
This wasn't resolved, at least put in a TODO to do this

2025-04-13 08:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DiscardChangesDialog.kt
> +        neutralMethod: (() -> Unit)? = null,
Add a TODO to clean this up, it's much more messy than it needs to be

2025-04-13 08:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            neutralMethod = {},
explain this

2025-04-13 08:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        if (!fragmented) {
hard/optional: I'd consider storing `noteEditorFrame` and similar in a `sealed class`, this would remove the `!!`:

Something like

```kotlin
when (this.fragmentAccessor) {
   is Fragmented -> { this.fragmentAccessor.secondaryFrame.isVisible = true }
}
```

2025-04-13 08:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
> +    val flowOfFocusedCard = MutableSharedFlow<Unit>()
Having both doesn't feel necessary. If they are, comment it, if not, remove one

2025-04-13 08:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
> +        fragmented: Boolean,
I'd be tempted to move this to an accessor provided to the factory.

The state of the screen should affect a number of options later on

2025-04-15 10:02 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        if (!fragmented) {
Will make this as `TODO`

2025-04-15 10:08 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
> +    val flowOfFocusedCard = MutableSharedFlow<Unit>()
both are different. 

`flowOfFocusedRow `for `handleRowLongPress`
`flowOfFocusedCard `for `handleCardSelection`

2025-04-15 10:26 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            neutralMethod = {},
![image](https://github.com/user-attachments/assets/0889905f-eab7-4b95-9912-e2198bac5a33)

The neutral button (Cancel) is provided to handle cases where the user unintentionally initiated an action, such as accidentally selecting a different card

2025-04-21 11:17 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
> +    val flowOfFocusedCard = MutableSharedFlow<Unit>()
See if you can fix the naming

2025-04-21 11:18 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            neutralMethod = {},
Move this to a comment so the next person isn't confused

2025-06-03 05:06 UTC, david-allison approved these changes
Looks good!

@SanjaySargam I'm hoping to start pushing towards a stable release, do you feel this is stable enough to go into the next beta, or would you rather defer it to the start of the merge window for 2.22?

2025-06-03 05:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/BrowserMultiColumnAdapter.kt
> +                    ThemeUtils.getThemeAttrColor(context, R.attr.currentDeckBackgroundColor)
make a new attribute

2025-06-03 05:37 UTC, sanjaysargam commented
> Looks good!
> 
> @SanjaySargam I'm hoping to start pushing towards a stable release, do you feel this is stable enough to go into the next beta, or would you rather defer it to the start of the merge window for 2.22?

I’ve tested it thoroughly and haven’t encountered any regressions. From my side, it looks stable enough to include in the next beta.
Happy to revisit or make adjustments if any issues come up during broader testing.

2025-06-04 00:12 UTC, mikehardy approved these changes
Ok - note - needs string sync

2025-06-04 00:25 UTC, merged

2025-11-06 04:24 UTC, david-allison commented
Hi there @sanjaysargam! This is the OpenCollective Notice for PRs merged from [2025-06-01 through 2025-06-30](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2025-06-01..2025-06-30+author%3Asanjaysargam)
                      
If you are interested in compensation for this work, the process with details is here: https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

We only post one comment per person per month to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month

Please understand that our monthly budget is never guaranteed to cover all claims - the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!