fix: deckpicker to use transparent status bar
ankidroid/Anki-Android pull request #16775
Opened 2024-07-22 20:24 UTC by shrutigitte

## Purpose / Description
This PR fixes the status bar for ground color issue

## Fixes
* Fixes #16770 

## Approach
Status Bar transparent API is called just like note editor does

## How Has This Been Tested?
Google Emulator
![image](https://github.com/user-attachments/assets/884c5395-fdbe-4936-912f-88065b21ca5e)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-07-22 20:40 UTC, criticalAY requested changes
I suggest setting it for the AnkiActivity so that it will be consistent with whole application

2024-07-22 21:09 UTC, criticalAY approved these changes
Looks good now! /Not official approval/

2024-08-03 17:32 UTC, david-allison commented
@snowtimeglass Was this what you intended? I would have expected the icons to stay white

2024-08-04 11:09 UTC, BrayanDSO approved these changes
If the Android framework is saying that black is more readable than white, I'm going to trust it.

2024-08-04 12:10 UTC, snowtimeglass commented
@david-allison No, this is what I have expected. I also have expected the icons to stay white.

I suppose it is better that the color is consistent with the text color in the app bar. If the text color will remain white, then it is desirable to keep the foreground color in the status bar white, in my opinion.

2024-08-04 12:54 UTC, criticalAY commented
I saw many apps keep it transparent like Twitter, Google Auth, Keep Notes
So I support Brayan's arg here

2024-08-04 13:16 UTC, david-allison commented
I personally don't like this change

2024-08-04 13:36 UTC, criticalAY commented
So we are sticking to keeping it white?

2024-08-04 13:54 UTC, david-allison commented
I'd like to, as that's what the issue requested.

2024-08-05 00:09 UTC, snowtimeglass commented
@criticalAY 
> I saw many apps keep it transparent like Twitter, Google Auth, Keep Notes

You mean you saw displays like the followings?
![image](https://github.com/user-attachments/assets/8d5e6a39-a4d0-4c7b-a2e5-7e63e27e9062)

2024-08-05 04:11 UTC, criticalAY commented
Yep I meant this only

2024-08-05 04:57 UTC, snowtimeglass commented
Then, I think it also means you saw the foreground color is consistent between the status bar and the app bar, as well as about the consistency of the background color. The foreground color is consistently black in the first screen, and consistently white in the second screen. 

In that aspect, I suppose that the user experience of this PR's suggested screen is not the same kind as one of what you saw in the other apps. The foreground color is black on one side bar, white on the other side bar. 
![image](https://github.com/user-attachments/assets/5ca56dde-b1b8-441f-a3a2-ad334a4e3778)
So, I think it is not desirable.

2024-08-06 10:25 UTC, criticalAY approved these changes
Look good!

2024-08-06 11:22 UTC, david-allison approved these changes
Thanks

2024-08-11 00:18 UTC, BrayanDSO approved these changes

2024-08-11 00:34 UTC, merged