[GSoC'24] CardBrowser: Implementation of Keyboard Shortcuts
ankidroid/Anki-Android pull request #16795
Opened 2024-07-30 09:47 UTC by SanjaySargam

## Purpose / Description
Implement keyboard shortcuts to enhance the user experience by providing quick access to commonly used functionalities within the application. This will improve the overall usability, especially for power users who prefer using the keyboard over the mouse.

## Approach
The shortcuts are implemented by adding event listeners for keypress events and mapping them to the respective functions. The approach ensures that the shortcuts are intuitive and do not conflict with existing shortcuts.

## How Has This Been Tested?
HP Chromebook

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-07-31 15:07 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            openNoteEditorForCard(cardId)
This should be extracted into another method -  it does two separate things, and the method name is no longer correct

2024-07-31 15:07 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    }
Personal preference 

```suggestion
    private fun searchForSuspendedCards() = launchCatchingTask {
        viewModel.searchForSuspendedCards()
    }
```

2024-08-01 06:17 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                    showSavedSearches()
It shows resposition dialog

2024-08-01 06:19 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            openNoteEditorForCard(cardId)
I will make a seperate PR. It is not related to this PR

2024-08-01 07:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                    showSavedSearches()
My question was to confirm that this was intended

2024-08-01 08:52 UTC, david-allison requested changes
I don't feel `E` is well-defined:

I think there's two choices:

* Split it out into a separate PR and get this merged quickly
* Spend some more time, and keep this blocked for a bit

2024-08-01 08:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    }
Flagging this for reviewer 2

2024-08-01 08:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                    openNoteEditorForCurrentlySelectedNote()
I'd like a couple of unit tests here defining behaviour:

* Cards mode/notes mode
* What if there's multiple selections
* What if there's no selection, but rows
* What if there's no rows and no selections

2024-08-01 16:23 UTC, SanjaySargam commented
> * Split it out into a separate PR and get this merged quickly

I'd prefer this

2024-08-01 16:24 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    }
didn't understand

2024-08-01 17:07 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                    showSavedSearches()
It's not intentional

2024-08-01 17:12 UTC, david-allison commented
Sounds great

2024-08-03 10:08 UTC, david-allison approved these changes
LGTM, cheers!

2024-08-04 00:55 UTC, Arthur-Milchior approved these changes
I'd be fine merging as is. Even if honestly I'd prefer better name and documentation. And since I expect it's not blocking anything, I won't press "merge"

2024-08-04 00:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    private fun getCardInfo() {
As far as I can tell, what it does is displaying to the user the informations of the card. If so, I'd go with `displayCardInfo`

2024-08-04 00:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    private fun saveSearch() {
Please be specific. Call it `openSaveSearchView` or something similar. Because, reading the code, I thought it was directly saving the search, and I was surprised. By testing; I realize it's not the case.

In particular, the fact that there is not even documentation clarifying is an issue

2024-08-04 00:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                    searchForSuspendedCards()
If you look at the code in the view model, you'll see it's only expected to be used if the user has no selection.
Indeed, in this case, the action item is not even displayed to the user.

So, there are two problems.
First, you return "true" even if nothing occurred. Ideally, we should return false, so that any system that check whether the shortcut was dealt with does not inform the user that this was a success.

More generally, for each shortcut, it would be nice to document if it's expected to occur when there is a selection, when there is no selection, or whether it does not matter

This is a case where I expect that having `searchForSuspendedCards` return a bool would make sense to me, and then we could directly return the bool

2024-08-04 00:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    private fun searchForSuspendedCards() = launchCatchingTask {
I'd appreciate if you could document that this is only "replacing the current search by a search for all suspended cards". Intuitively, I would have thought it'd restrict the current search by adding is:suspended, as you can do in anki browser. It's nice to know that it's far more limited than that.

Actually, you could add the documentation in the implementation in viewModel, and just put a `@seeCardBrowserViewModel.searchForSuspendedCards`

2024-08-04 10:41 UTC, david-allison commented
@Arthur-Milchior @SanjaySargam As far as I'm aware, this is waiting for Sanjay's blessing to merge [review comments are optional].

Should this be merged now, or wait for another round of reviews?

2024-08-04 11:21 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
>          // NOTE: These are all active when typing in the search - doesn't matter as all need CTRL
I admit I had a hard time understanding this comment. In particular, I couldn't imagine that if it states that they are "all" active, it implies that it would be possible to have only some of them to be active.

I'd rephrase it as:
> This method is call even when the user is typing a the search text field. So we must ensure that all shortcuts uses a modifier. A shortcut without modifier would be triggered while the user types, which is not what we want.

2024-08-07 13:47 UTC, david-allison commented
@Arthur-Milchior Still fine to merge?

2024-08-10 21:17 UTC, Arthur-Milchior reviewed
@david-allison I admit I'm surprised one comment remained neither answered nor followed.
I'd be fine merging and correcting later if needed. However, as it's not blocking anything, I won't press "merge" until either @SanjaySargam tells us to merge with open comment or follow them.

Also, there are typos that were my mistake, that ended up in the PR

2024-08-10 21:17 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                    searchForSuspendedCards()
I don't understand why this seems to have been mostly ignored.
I appreciate you didn't resolve it. Still, seems strange that you ignored most of it.

For example, for `searcForSuspendedCards`, you added documentation, which I really like. But you omitted what I was asking for in the first place. Documenting that this method does nothing if the selection is not empty, and, in this case, returning `false`

2024-08-10 21:17 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        // This method is call even when the user is typing a the search text field.
I'm very sorry for my broken English. I realize I wrote the typos and you just copy-pasted them.
Out of curiosity, did you copy paste without reading. Or had you not realized that what I wrote was wrong.

"is called" "in the search text field"

2024-08-10 21:40 UTC, david-allison commented
@Arthur-Milchior with apologies, I'm not following, could you link the discussion which requires my input. 

I'm still happy to see this merged

2024-08-11 14:45 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        // This method is call even when the user is typing a the search text field.
Sorry, I just copy-pasted. I'll make sure to pay more attention next time

2024-08-11 19:55 UTC, Arthur-Milchior commented
@david-allison My excuses for being unclear.
You asked whether we could merge. I was trying to answer to you. I was not willing to merge immediately due to one comment which was not resolved.
I was not expecting any answer from you, it was not a question but an answer

2024-08-11 20:20 UTC, Arthur-Milchior requested changes

2024-08-11 20:20 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +     * @see CardBrowserViewModel.searchForSuspendedCards
I'm sorry for being so unclear.
ViewModel's `searchForSuspendedCards` already check whether there is any selected rows. So it was not very useful to do the check here.
Instead, I thought that this function would just be
`private fun searchForSuspendedCards = viewModel.searchForSuspendedCards()` (or actually, you could just remove this method and directly call `viewModel.searchForSuspendedCards()` everywhere, it'll make the code slightly shorter.

The ViewModel's function would do `return false` instead of an early return. And it would return `true` if there are selected rows.

2024-08-11 20:20 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +     * Returns false if selected rows is not empty else true
I think you missed the most important point in this comment. First, that the search is only updated if there is currently no selection.
Secondly, I'd prefer that you explain why this return true or false. That is, you return whether there was any update.

Here is the comment you'd put in the ViewModel.
```
/**
* If there any any selected card, do nothing. 
* Otherwise, searches for all suspended cards and replaces the current search results with these suspended cards.
* @returns whether the search was updated.
*/
```

2024-08-11 20:20 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
>          setFilterQuery("tag:marked")
When I wrote "for each shortcut", I meant that you were supposed to look at the implementation of each shortcut.
`searchForMarkedNoted` also do an early return if there is a selection. And this seems to be the same case in a lot of function above and below. So it'd be nice to:
* document that all those methods do nothing if there is a selection (which will probably be the case often when you use the shortcut
* ensure they return a boolean that indicates whether anything was done
* that all method that call them return this boolean, so that the information is propagated to the shortcut function

2024-08-15 05:28 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +     * @see CardBrowserViewModel.searchForSuspendedCards
> viewModel.searchForSuspendedCards()

This is suspend function. We can't directly `return viewModel.searchForSuspendedCards()`

2024-08-15 05:59 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +     * @see CardBrowserViewModel.searchForSuspendedCards
Instead should I do like this:
```kotlin
    /**
     * If there any any selected card, do nothing.
     * Otherwise, searches for all suspended cards and replaces the current search results with these suspended cards.
     * @returns whether the search was updated.
     */
    suspend fun searchForSuspendedCards() {
        setFilterQuery("is:suspended")
    }
```

2024-08-15 12:42 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +     * @see CardBrowserViewModel.searchForSuspendedCards
I'd like @david-allison opinion on it.
He created the ViewModel, and maybe there are constraints I don't understand.

I admit that, personally, what I would do is:
In the view model
```kotlin
fun searchForSuspendedCards() = setFilterQuery("is:suspended")

/**
Asynchronously edit the search query and list of cards if nothing is selected
@return whether the search update is queued for launch
*/
fun setFilterQuery(filterQuery: String) : False {
  // Do not change the search while some cards are selected
  if (hasSelectedAnyRows()) return False
  launchCatchingTask { 
    // Abort the update if the user selected cards in the meantime
    if (hasSelectedAnyRows()) return
    this.flowOfFilterQuery.emit(filterQuery)
    launchSearchForCards(filterQuery)
  }
  return True
}
```
And then you directly use `viewModel.searchForSuspendedCards()` to deal with both the menu entry and the shortcut.

Of course, that means you must do similar changes to the three methods that use `setFilterQuery()`. Some of them do not have an early return. I believe that adding an early return to them will be a good thing; after all, there is no reason to lose the current search selection when you change the search for tag or flag.



If @david-allison disagrees with my suggestion, then I guess we'll use your suggestion. This sounds like code duplication, but it may be fine

2024-08-15 13:58 UTC, Arthur-Milchior reviewed
One last question regarding tests.

For the Boolean question, I let you decide whether you want to undo it, or not.

2024-08-15 13:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +     * @see CardBrowserViewModel.searchForSuspendedCards
David Mentionned I'm overcomplicating things and anyway this code will be changed.
So, fine, let's return true. I'm not huge huge fan of it, but probably reasonable, especially if nobody complain

2024-08-15 13:58 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt
> +            if (!hasSelectedAnyRows()) {
I'm sorry, but I don't understand why you add the line in the test.
Normally, while running the test, you know whether you expect cards to be selected. And act accordingly.
If you're not 100% , you can also add a test/expectation that the card is selected/not selected.

2024-08-15 14:02 UTC, SanjaySargam commented on AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt
> +            if (!hasSelectedAnyRows()) {
Because I removed this check from `searchForMarkedNotes()`
I'll revert this

2024-08-15 20:05 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +     * @see CardBrowserViewModel.searchForSuspendedCards
For posterity:

> 1. You're overcomplicating things. Return `true`
>     * You handled the keypress and don't want it to bubble. The fact that handling it had no effect is irrelevant
> 2. I have a pull request which removes this functionality, so it's not worth putting in significant effort
>     * Discussed with Sanjay: https://discord.com/channels/368267295601983490/882228005504696350/1268216267601612912
>    * Implemented: [#16859: feat(card-browser): Chip Based Filtering [Tags, Flags & State]](<https://github.com/ankidroid/Anki-Android/issues/16859>)

2024-08-16 01:58 UTC, mikehardy commented
(just closing/reopening as I changed the set of github actions that run / are required, this re-triggers CI with the new set)

2024-08-16 01:59 UTC, mikehardy commented
@Arthur-Milchior you had this set to auto-merge but...that sat there for 12 hours and did not merge? I perturbed it with my close/reopen for CI required check changes just now. If you intended to merge this I believe you will have to try again?

2024-08-17 17:26 UTC, david-allison commented
@Arthur-Milchior you need to approve this

2024-08-17 17:27 UTC, Arthur-Milchior approved these changes

2024-08-17 17:44 UTC, merged