[GSoC'24] CardBrowser: Shortcut E
ankidroid/Anki-Android pull request #16814
Opened 2024-08-03 08:27 UTC by SanjaySargam

## Purpose / Description
This PR is a part of #16795 

## How Has This Been Tested?
HP Chromebook

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-08-03 13:42 UTC, david-allison commented
@SanjaySargam What's pending before this becomes ready to review?

2024-08-03 18:54 UTC, Arthur-Milchior approved these changes
only nit. If you only change comment/documentation we can merge immediately

2024-08-03 18:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    private suspend fun getCardIdForNoteEditor(): CardId {
Please add documentation.
> In case of selection, the first card that was selected, otherwise the first card of the list.

2024-08-03 18:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        // Just select the first one. It doesn't particularly matter if there's a multiselect occurring.
I admit I don't understand the "doesn't particularly matter". That does not seems obvious to me.
And in particular, it seems it should be `if` part of the if/else.
Because that's the only place where we consider the case where there is indeed multiple selections.

2024-08-03 19:06 UTC, david-allison commented
What if there's no cards?

2024-08-04 00:39 UTC, Arthur-Milchior commented
@david-allison If there is no card, it edit the first card of the search result.
Which is what I was asking him to document

2024-08-04 00:40 UTC, david-allison commented
What if there are no cards in the deck?

2024-08-04 10:02 UTC, SanjaySargam commented
> What if there are no cards in the deck/collection?

It show toast as `Something went wrong`

```kotlin
    private fun openNoteEditorForCurrentlySelectedNote() = launchCatchingTask {
        try {
            val cardId = getCardIdForNoteEditor()
            openNoteEditorForCard(cardId)
        } catch (e: Exception) {
            Timber.w(e, "Error Opening Note Editor")
            showSnackbar(
                R.string.multimedia_editor_something_wrong,
                Snackbar.LENGTH_LONG
            )
        }
    }
```

2024-08-04 10:40 UTC, david-allison commented
It should do something more user-friendly. It's an expected 'error' case

2024-08-04 13:19 UTC, SanjaySargam commented
@david-allison Should I change toast as `No note to open NoteEditor`?

2024-08-04 13:20 UTC, david-allison commented
I'd go with `No note to edit`

2024-08-04 13:54 UTC, david-allison reviewed
Unit tests would be great here

2024-08-04 13:55 UTC, david-allison approved these changes
Awaiting Sanjay's approval: either waiting for tests, or merging as-is

2024-08-04 13:56 UTC, SanjaySargam commented
> Unit tests would be great here

I'll add in separate PR

2024-08-04 13:58 UTC, david-allison requested changes
This should only show `no note to edit` if there's no note to edit. Not on any failure.

2024-08-04 13:59 UTC, SanjaySargam reviewed
Self high-five! Approved!

2024-08-04 14:43 UTC, Arthur-Milchior commented
Sorry @SanjaySargam you won't get the 2nd approval right now. David make a useful remark. You should show the new message if no notes are selected. If there is any other error, then there should be no changes

2024-08-05 17:15 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +            val message = if (viewModel.rowCount == 0) {
Why are we doing this in an exception block, instead of either:

* returning a result from the ViewModel
* checking the precondition beforehand

2024-08-07 17:29 UTC, david-allison approved these changes
Beautiful, thanks for taking the time with this one

2024-08-07 17:30 UTC, david-allison commented
Blocked on translation sync

2024-08-08 18:28 UTC, merged