Enhancement: [Image Cropping] Use new API from `canhub`
ankidroid/Anki-Android pull request #16826
Opened 2024-08-05 20:59 UTC by criticalAY

## Purpose / Description
Use the new API to handle and remove the deprecated API from canhub i.e. create our own activity 

Blocking on: 
* https://github.com/ankidroid/Anki-Android/pull/16798

## Fixes
* https://github.com/ankidroid/Anki-Android/pull/16824

## How Has This Been Tested?
Emulator API 35

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-08-05 21:16 UTC, criticalAY commented
> w: file:///Users/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.kt:20:8 '@Deprecated(...) @SourceDebugExtension(...) class CropImageActivity : AppCompatActivity, CropImageView.OnSetImageUriCompleteListener, CropImageView.OnCropImageCompleteListener' is deprecated. Create your own Activity and use the CropImageView directly.
Will remove it when the blocker gets merged

2024-08-07 13:09 UTC, david-allison commented
Note: you don't want a failing commit in the history, so thids should either be reordered or squashed

2024-08-10 16:04 UTC, david-allison reviewed
1. If we're copying their code in, I would expect a couple of lines change in our calling code
2. Copyright seems like we don't acknowledge our source.

See:

https://github.com/ankidroid/Anki-Android/blob/864b7c75b4725dfd7710d62a38e0d62d13b8dab9/AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt#L17-L24

2024-08-10 16:04 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        cropImageLauncher.launch(intent)
Is there a reason there's so much code churn here?

2024-08-10 16:04 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +    private val imageCropperLauncher =
ditto

2024-08-10 16:04 UTC, david-allison commented on AnkiDroid/src/main/res/layout/fragment_image_cropper.xml
> +  ~ Copyright (c) 2024 Ashish Yadav <mailtoashish693@gmail.com>
is this correct?

2024-08-10 16:04 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/imagecropper/ImageCropper.kt
> + * Copyright (c) 2024 Ashish Yadav <mailtoashish693@gmail.com>
Is this correct?

2024-08-10 16:16 UTC, criticalAY commented on AnkiDroid/src/main/res/layout/fragment_image_cropper.xml
> +  ~ Copyright (c) 2024 Ashish Yadav <mailtoashish693@gmail.com>
Yes, we have our own implementation, that is different from canhub. didn't copy this

2024-08-10 16:17 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/imagecropper/ImageCropper.kt
> + * Copyright (c) 2024 Ashish Yadav <mailtoashish693@gmail.com>
Majority of the code is customized according to our usage, we own it ?

2024-08-10 16:27 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/imagecropper/ImageCropper.kt
> + * Copyright (c) 2024 Ashish Yadav <mailtoashish693@gmail.com>
Give attribution to where you got it from

2024-08-10 17:41 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        cropImageLauncher.launch(intent)
Earlier we did not had the specific activity for it

2024-08-16 02:10 UTC, mikehardy commented
I conflicted this with all my dependency updates, so I took the penalty and de-conflicted it then re-pushed.
Also I needed it to re-run CI with new set of checks

2024-08-16 07:42 UTC, david-allison commented
@criticalAY I'm self-assigning with the expectation that I'll get through this today. Please ping if this doesn't happen

I still feel there's too much code churn here, and I'm a little concerned about the copyright notices, so I want to work through this

Please ping if I'm not done within 24 hours

2024-08-16 09:07 UTC, david-allison commented
I'm posting PR feedback which I would provide here. I'm going to edit this post so it won't spam notifications

This is non-actionable and informative only, as I'll resolve these:

* The commit message needs much more information about where the code came from and why it occurred

2024-08-16 09:18 UTC, david-allison commented
@criticalAY After a quick look, I'm asking for busywork

Please improve the commit message significantly, explaining the choices you made. Here's a start:

> refactor(crop-image): fix `CropImageContract` deprecation
> 
> `CropImageContract` will be deprecated in `android-image-cropper:4.6.0`
as the library would like to focus on only providing cropping functionality
>
> Their defaults also included other unrelated functionality: loading
images etc..., and this is being moved into consumers of the library
> 
> The recommended upgrade path is to use `CropImageView`
> 
> * https://redirect.github.com/CanHub/Android-Image-Cropper/pull/637

2024-08-19 13:38 UTC, david-allison requested changes
> "feat: use CropImageView to **crop crop** images"

2024-08-22 16:34 UTC, mikehardy commented
I would like to see this go in, so I fixed the conflict (simple import statement thing) which simultaneously allowed me to reduce the `crop crop` in the comment to `crop`, so hopefully this is ready for serious review now

2024-08-22 16:50 UTC, david-allison approved these changes
I was previously an 'approve', and am still

With the note that the build now fails and that will need to be resolved, code structure is fine

2024-08-30 23:57 UTC, mikehardy approved these changes
Alright then, let's go! Thanks @criticalAY

2024-08-31 00:12 UTC, merged