fix: unnecessary camera permission check
ankidroid/Anki-Android pull request #16844
Opened 2024-08-07 20:33 UTC by criticalAY

## Purpose / Description
We use camera as feature in the manifest file and not as `<uses-permission android:name="android.permission.CAMERA" />` so the current check always returns false and the user is unable to open the camera options, the PR fixes that

## How Has This Been Tested?
Google emualtor API 24 & API35

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-08-07 22:15 UTC, Arthur-Milchior commented
I have to admit that, not knowing how camera works exactly in android code, it was hard to review.
I don't know whether other reviewers know without looking the way that manifest and code interacts, and the difference between andorid.hardware and android.permission in code.
Still, a few links or longer explanation could have helped. 
Or a video recording of before/after, given that, honestly, I don't really know what features uses the camera

Something such as:
> We remove `canUseCamera` that was not used. 
> Given that the manifest does not contain `<uses-permission android:name="android.permission.CAMERA" />`, `equestPermissionLauncher.launch(Manifest.permission.CAMERA)` always executed the callback with a denial, without even asking permission to the user. 
> We should note that we don't actually need the camera at all, given that we request the camera app to provide the image, and we don't directly interact avec the camera hardware.
> This means that, while we don't have the permission to use the camera, we don't have to do an early return when permission is missing; instead we can proceed as expected.

Please let me know if I got it wrong.


Also, can't we remove
```
  <uses-feature android:name="android.hardware.camera" android:required="false" />
    <uses-feature android:name="android.hardware.camera.any" android:required="false" />
```

As far as I understand, they are useless without camera permission.
At least, it builds without those lines.

2024-08-07 22:41 UTC, david-allison requested changes
Needs better documentation. Discussed privately on Discord

2024-08-08 10:55 UTC, criticalAY commented
I have updated the details in template, let me know if need to put them somewhere else?

2024-08-08 11:15 UTC, david-allison commented
I'd like a summary + link to the breaking commit in the commit message 

This allows someone to look back when adding the test and understand the problem

2024-08-08 11:46 UTC, david-allison approved these changes

2024-08-08 11:47 UTC, david-allison commented
Thanks for the blazing fast turnaround!

2024-08-08 22:33 UTC, Arthur-Milchior approved these changes
That seems to work. Not exactly sure about the whole context, but don't want to block either.
If you'd agree to put even more detailled explanation, please do so. Otherwise, tell me or any reviewer to click on "merge"

2024-08-08 22:33 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> -import android.Manifest
I'm sorry, but I'm still confused by the commit message.
You're linking to a commit that, according to github, is not part of our branch or repo, so I suspect you've got the wrong hash.
I don't understand why some information are present in the PR message and not the commit message, such as the fac that the permission was not there initially (I assumed you meant "there" and not "their"). This seems useful to record it in git history.

And most importantly, I wrote a relatively detailled example of commit message in my first review. I still don't know what was right or wrong. If it was wrong, can you tell me which part is wrong. If I got it right, I'd appreciate that you put the same information in the commit message, so that this commit is clear for someone that does not know how permission works.
For example,
> but we declare the camera as feature  `<uses-feature android:name="android.hardware.camera" />` later.

is very confusing to me.
What means "later". Later than what ? do you mean that it occurs below in the build process, or the execution process ? That it was introduced in a commit that arrived after the commit introducing the permission ?
And why did you use "but" ? It seems to indicate that those are incompatible things to do. But, as far as I understand the documentation, if you wanted to use the camera, you actually need to require the permission AND the feature. That's actually in one of the example on the documentation website if I recall correctly.
So the "but" seems just wrong.

One thing which I appreciate however is that, by linking to a past commit, you're starting to explain why the error was made. I'd really appreciate to know what we tried to do, so that I can be sure that's what you're doing now.

2024-08-08 22:33 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> -import android.Manifest
After checking, I think you want 6a8ede0916ca5a88c908c9d7301f4523bde436d7

Or maybe a PR link as it would also allow to see the discussion.

2024-08-08 23:05 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> -import android.Manifest
How about now?

2024-08-16 02:36 UTC, mikehardy requested changes
I believe this is correct, as Brayan stated when removing the permission from the manifest, the app *itself* is not using/accessing the camera, rather we are deferring to system camera services to grab images, so we do not need to declare nor check for camera permission

I was pretty sure we could remove the feature entry as well and on review of docs (https://developer.android.com/guide/topics/manifest/uses-feature-element#required) - we *should* also remove that feature declaration as well as Arthur states. It was never required in the first place (so it wasn't going to be used by Play Services or Play Store for app filtering related to a device, and now we are not even using the permission so it doesn't make sense to have it

I will happily approve+merge or invite anyone else to merge with the single change of also removing the feature entry for camera from AndroidManifest

2024-08-16 05:00 UTC, criticalAY commented
@mikehardy Require means /if set true/ that our app wont function without camera, but we use camera as a feature but it is not required so its set to false, we already don't have permission

2024-08-19 03:19 UTC, mikehardy commented
@criticalAY I believe we both have the same understanding of required or not. What I am understanding further though is that since we are not *directly* accessing the hardware, that is, using camera hardware APIs - but rather we are delegating to camera app for image capture (this is correct, yes?) - then having the feature mentioned at all is not really useful

Which led to this in order to just keep things minimal:

> will happily approve+merge or invite anyone else to merge with the single change of also removing the feature entry for camera from AndroidManifest

If my understanding is incorrect, or you just feel really deeply strongly that having the camera usage mentioned as a feature even though it is optional is important, then okay, and we should merge and move on

2024-08-19 11:12 UTC, criticalAY commented
I did go through the [doc](https://developer.android.com/media/camera/camera-deprecated/camera-api#:~:text=Camera%20Permission%20%2D%20Your%20application%20must,to%20use%20a%20device%20camera.&text=Note%3A%20If%20you%20are%20using,need%20to%20request%20this%20permission.&text=For%20a%20list%20of%20camera%20features%2C%20see%20the%20manifest%20Features%20Reference.) but I am not sure what are they meaning here, weather we can use device camera without feature declaration or not. @david-allison @mikehardy You might want to go through it once.

2024-08-19 12:11 UTC, david-allison commented
I don't have time to delve into this currently.

If we can't confirm quickly, leave it as a TODO & Good First Issue (and get this PR merged) - this is primarily research-based and we can make a decision quickly once the requirements are fully understood

2024-08-19 13:46 UTC, mikehardy commented
No. I went through it. It's informational.
It's not needed. If you don't feel strongly please stop conversationally reverting and remove the line

2024-08-19 19:57 UTC, criticalAY commented
@mikehardy Removed it

2024-08-21 02:03 UTC, mikehardy approved these changes
💥  boom 💥

2024-08-21 02:24 UTC, mikehardy commented
strings merge in queue, queueing this now

2024-08-21 02:39 UTC, merged