Fix: Tell the users why card type deletion fails when this would orphan note.
ankidroid/Anki-Android pull request #16840
Opened 2024-08-07 04:03 UTC by Sahil-Mandal15

## Purpose / Description
To show a dialog when the user tries to delete a card type that would orphan note.

## Fixes
* Fixes #16789 

## Approach
The issue fix involves creating a AlertDialog that is shown when the user tries to delete a card type that would  orphan note.

## How Has This Been Tested?

Device: Realme 10 pro+
Model: RMX3686
API Level: 34-ext12

## Screenshot of the Screen with the fix
![orphanotefix](https://github.com/user-attachments/assets/646df57a-c28d-4936-9146-ce1ad9d27495)

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-08-07 11:16 UTC, david-allison requested changes

2024-08-07 11:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +                    //   templateEditor.showSimpleMessageDialog(resources.getString(R.string.card_template_editor_would_delete_note)) // Implemented in the deleteCardTemplate
Don't comment out lines, we have `git` history and can remove them without worry.

2024-08-07 11:16 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="orphan_note_message">Deleting this card type would leave notes without a card type. Please delete the notes first.</string>
This doesn't strike me as correctly worded, @Arthur-Milchior?

My understanding is that the issue is that deleting the card type would cause:

* A user has a note with 2 card templates, 1 of which produced a card, and one of which does not
* If a user deletes the card template which produced a card, they have a note with no cards

I'd go with

> Deleting this card type produces notes which have no cards

----

I don't think we want to inform the user of the next course of action here. Telling them to delete their notes is drastic. The expected action is "don't do this"

2024-08-07 11:17 UTC, david-allison commented
Thanks! In addition to my request, there's a couple of test/lint checks to fix

2024-08-07 12:39 UTC, brishtibheja commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="orphan_note_message">Deleting this card type would leave notes without a card type. Please delete the notes first.</string>
The word "produce" is confusing. How about "Deleting this card type will leave your notes without any cards"?

2024-08-07 12:41 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="orphan_note_message">Deleting this card type would leave notes without a card type. Please delete the notes first.</string>
Much better, cheers!

2024-08-07 14:57 UTC, david-allison approved these changes
Nitpicks, looks good to me!

2024-08-07 14:57 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="orphan_note_message">Deleting this card type will leave some notes without any cards.</string>
```suggestion
    <string name="orphan_note_message">Deleting this card type will leave some notes without any cards</string>
```

2024-08-07 14:57 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="orphan_note_title">Cannot Delete Card Type</string>
```suggestion
    <string name="orphan_note_title">Cannot delete card type</string>
```

2024-08-07 16:28 UTC, david-allison requested changes
```
CardTemplateEditorTest > testDeleteTemplateWithSelectivelyGeneratedCards FAILED
    org.opentest4j.AssertionFailedError: Did not show dialog about deleting only card? ==> expected: <Removing this card type would cause one or more notes to be deleted. Please create and save a new card type first.> but was: <Deleting this card type will leave some notes without any cards>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1156)
        at app//kotlin.test.junit5.JUnit5Asserter.assertEquals(JUnitSupport.kt:32)
        at com.ichi2.anki.CardTemplateEditorTest.testDeleteTemplateWithSelectivelyGeneratedCards(CardTemplateEditorTest.kt:267)
```

and needs a lint fix

2024-08-07 16:37 UTC, Sahil-Mandal15 commented
can you help me with the fix as this is my first PR.

2024-08-07 17:35 UTC, david-allison commented
Sure!

Tap 'details' on the failing check:

<img width="1031" alt="Screenshot 2024-08-07 at 18 25 17" src="https://github.com/user-attachments/assets/ff01905a-eba3-40c4-a7e2-0c5fec4e8045">


https://github.com/ankidroid/Anki-Android/actions/runs/10288505701/job/28474098641?pr=16840

```
  /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/01-core.xml:149: Error: The resource R.string.card_template_editor_would_delete_note appears to be unused [UnusedResources]
      <string name="card_template_editor_would_delete_note">Removing this card type would cause one or more notes to be deleted. Please create and save a new card type first.</string>
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

----

Apply this patch by copying it, double-tapping shift in Android Studio and selecting 'apply patch from clipboard'

```patch
Index: AnkiDroid/src/main/res/values/01-core.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/res/values/01-core.xml b/AnkiDroid/src/main/res/values/01-core.xml
--- a/AnkiDroid/src/main/res/values/01-core.xml	(revision da8bd8e03e75d6b356bc20949d3869e35ffb9a8d)
+++ b/AnkiDroid/src/main/res/values/01-core.xml	(date 1723052089534)
@@ -146,7 +146,6 @@
         <item quantity="one">Delete the “%2$s” card type, and its %1$d card?</item>
         <item quantity="other">Delete the “%2$s” card type, and its %1$d cards?</item>
     </plurals>
-    <string name="card_template_editor_would_delete_note">Removing this card type would cause one or more notes to be deleted. Please create and save a new card type first.</string>
     <string name="card_template_editor_save_error">Unable to save card template changes: %s</string>
     <string name="template_for_current_card_deleted">The card type for the current card was deleted.</string>

```

2024-08-07 17:35 UTC, david-allison approved these changes

2024-08-07 17:40 UTC, Sahil-Mandal15 commented
Thanks for the help. I did the same and i guess i fixed it.

2024-08-07 18:02 UTC, david-allison commented
Great stuff, thanks so much!

2024-08-07 18:34 UTC, Sahil-Mandal15 commented
Thanks to you for showing patience.

2024-08-19 03:36 UTC, mikehardy approved these changes
LGTM - sorry this sat so long

2024-08-19 04:21 UTC, merged