update: Updated the snackbar developer string message to dialog box t…
ankidroid/Anki-Android pull request #16847
Opened 2024-08-08 11:11 UTC by Rohanraj123

## Purpose / Description
Implementation of user guide to troubleshoot the error of TTS engine voice incomapatibility when card synced from web.

## Fixes
Fixes #16825 

## Approach
Implementation of : 
Current TTS Engine + 'change' button which opens Android Settings
A link to the {{tts-voices:}} dialog fragment, so a user can see what's available
Link to 'Help'

Yet to implement : 
Current TTS

## How Has This Been Tested?
Tested on Samsung A15(Physical device).
Android version : 14  

## Learning
Lot of places in the app where It can be improved. This developer string was one failure when voice incompatibility occurs
`Improve TTS Error resolution for: APP_MISSING_VOICE` But there are lot of different errors are also mentioned their which still uses the snackbars with developer string. We can also perform simillar process to guide user in different format. Mostly will be done just replacing the developer string with a proper string message in the snackbar. 

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner]

https://github.com/user-attachments/assets/f07f6d08-4522-4bb5-bce0-9492cf0f3d9b

2024-08-08 20:08 UTC, david-allison reviewed
Thanks!!! First round of feedback - I've only looked briefly, but the main issue seems to be that this no longer handles other types of TTS error

To open settings:

https://github.com/ankidroid/Anki-Android/blob/8e1c71a54c06816887b3213d66c8e424d32cfc4f/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsVoicesDialogFragment.kt#L142-L153

2024-08-08 20:08 UTC, david-allison commented on AnkiDroid/src/main/res/layout/dialog_tts_error.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Is it feasible to have a more standard Material Dialog design?

2024-08-08 20:08 UTC, david-allison commented on AnkiDroid/src/main/res/layout/dialog_tts_error.xml
> +    ~  Copyright (c) 2024 David Allison <davidallisongithub@gmail.com>
Your copyright, not mine!

2024-08-08 20:08 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsPlaybackErrorDialog.kt
> +        const val TAG = "TTS PLAYBACK ERROR DIALOG"
Shouldn't be necessary

2024-08-08 20:08 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsPlaybackErrorDialog.kt
> +        }
A number of lines can be simplified

```suggestion
       view.findViewById<Button>(R.id.first_button).setOnClickListener {
            openSettings()
        }
```

2024-08-08 20:08 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsPlaybackErrorDialog.kt
> +        reasonTextView.text = reasonText
```suggestion
        view.findViewById<TextView>(R.id.reason_text).apply {
            text = getString(R.string.tts_error_dialog_reason_text, engine, language)
        }
```

2024-08-08 20:08 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsPlaybackErrorDialog.kt
> +class TtsPlaybackErrorDialog(private val language: String, private val engine: String) : DialogFragment() {
I believe you can pass the layout ID into the constructor for simplification

2024-08-08 20:08 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="tts_error_dialog_reason_text" translatable="false"><b>%1$s</b> engine does not support language : <b>%2$s</b></string>
Isn't this error potentially a failed match on lang + voice?

https://github.com/ankidroid/Anki-Android/blob/9f491242261a05919777cd64cade610a09de4ae7/AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt#L86-L90

2024-08-08 20:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardMediaPlayer.kt
> +                        soundErrorListener?.onTtsError(it, isAutomaticPlayback, tag.lang)
it would be more expected for the relevant error to contain the context, rather than passing it around as an additional arg

2024-08-08 20:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardMediaPlayer.kt
> +            val ttsEngine = TextToSpeech(baseContext, null)
What's the latency on this call? 

I proposed moving this into `TtsVoices` as there's potentially a fairly large performance hit when initializing `TextToSpeech`

2024-08-08 20:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardMediaPlayer.kt
> +                activity.showDialogFragment(TtsPlaybackErrorDialog(lang, ttsEngine.defaultEngine))
I believe that `ttsEngine.defaultEngine` is a "platform type" (`!`)

A platform type will trust a developer's cast to EITHER the nullable, or non-null type (`String!` = `String|String?`)

In this case, `defaultEngine` is nullable, and the cast to `String` is incorrect.

https://www.baeldung.com/kotlin/platform-types

2024-08-08 20:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsPlaybackErrorDialog.kt
> + *  Copyright (c) 2023 David Allison <davidallisongithub@gmail.com>
Not my copyright

2024-08-08 20:48 UTC, david-allison commented on AnkiDroid/src/main/res/layout/dialog_tts_error.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Coming back to this: I don't think we need the complexity of a `DialogFragment` here, and can get away with a standard 3-button`AlertDialog`

2024-08-09 07:03 UTC, Rohanraj123 commented
All the questions have been answered. And updated the code as well. 
--> There are some issues I wanna point out here : 

1. First time when i open card it doesnt show the language name, but when i dismiss the card and reopen it again, it shows the language correctly. looks like it takes time to update the state. 
2. Also there is one more observation. It seems like when ever we open card, it tries to either resync automatically or re-update the langauge name etc. because it destroys the state once we close the card. And fetch again the info. We can definately improve on that part. (Your suggestions )?
3. I have just provided a if else logic where we can handle the dialog when missing voice message appears other wise standard snackbars. Please check once whether it works or not.

2024-08-09 09:36 UTC, Rohanraj123 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
> +                .build()
https://github.com/ankidroid/Anki-Android/actions/runs/10315052630/job/28554515881?pr=16847#step:6:602:~:text=601-,/home/runner/work/Anki%2DAndroid/Anki%2DAndroid/AnkiDroid/src/main/java,ShortcutManagerCompat.addDynamicShortcuts(,-603

This is the error that is being produced when i do not add this code for shortcuts.

2024-08-09 14:48 UTC, Rohanraj123 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsVoicesDialogFragment.kt
> +        // asdlfkj
removed!

2024-08-10 06:35 UTC, Rohanraj123 commented
@david-allison Sorry It took little late to go through the code and actually find a good approach as per my understanding of codebase yet. But I feel things are working as expected now. I have tested it manually. Also if its about latency, I am not restablishing the connection to the engine, I just reused it.

2024-08-10 14:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
> +                .build()
That's a warning I believe. Revert this code and lint should still pass

2024-08-10 15:39 UTC, david-allison requested changes
Thanks!!

My patches need testing, written without running the app

I think this review moves it to a mergeable state, possibility for one very small "cleanup" review regarding translatable strings

2024-08-10 15:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardMediaPlayer.kt
> +                        TtsErrorCode.APP_MISSING_VOICE -> {
Architecture: `APP_MISSING_VOICE` should contain `tag`, it shouldn't be a parameter since `tag` is irrelevant/not included in other errors, and required in the `MissingVoice` case

Bit of a hairy patch due to moving from an enum to a union: 

The refactor needs to be extracted out into an initial 'refactor' commit so we can focus on the code changes

```patch
Subject: [PATCH] aa
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt b/AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt	(revision 2053989da052f03ca9efdc9c43ae049217ae8d59)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt	(date 1723303359803)
@@ -19,14 +19,13 @@
 import android.content.Context
 import android.os.Bundle
 import android.speech.tts.TextToSpeech
-import android.speech.tts.TextToSpeech.ERROR
 import androidx.annotation.CheckResult
-import com.ichi2.anki.AndroidTtsError.TtsErrorCode
 import com.ichi2.compat.UtteranceProgressListenerCompat
 import com.ichi2.libanki.TTSTag
 import com.ichi2.libanki.TtsPlayer
 import com.ichi2.libanki.TtsPlayer.TtsCompletionStatus
 import com.ichi2.libanki.TtsVoice
+import kotlinx.coroutines.CancellableContinuation
 import kotlinx.coroutines.CoroutineScope
 import kotlinx.coroutines.Dispatchers
 import kotlinx.coroutines.channels.Channel
@@ -72,7 +71,10 @@
                 }
 
                 override fun onError(utteranceId: String?, errorCode: Int) {
-                    scope.launch(Dispatchers.IO) { ttsCompletedChannel.send(AndroidTtsError.failure(errorCode)) }
+                    scope.launch(Dispatchers.IO) {
+                        val error = AndroidTtsError.fromErrorCode(errorCode)
+                        ttsCompletedChannel.send(TtsCompletionStatus.failure(error))
+                    }
                 }
             })
         }
@@ -86,13 +88,13 @@
         val match = voiceForTag(tag)
         if (match == null) {
             Timber.w("could not find voice for %s", tag)
-            return AndroidTtsError.failure(TtsErrorCode.APP_MISSING_VOICE)
+            return TtsCompletionStatus.failure(AndroidTtsError.MissingVoiceError(tag))
         }
 
         val voice = match.voice
         if (voice !is AndroidTtsVoice) {
             Timber.w("Invalid voice for %s", tag)
-            return AndroidTtsError.failure(TtsErrorCode.APP_INVALID_VOICE)
+            return TtsCompletionStatus.failure(AndroidTtsError.InvalidVoiceError)
         }
 
         return play(tag, voice).also { result ->
@@ -105,13 +107,13 @@
             val tts = tts?.also {
                 it.voice = voice.voice
                 tag.speed?.let { speed ->
-                    if (it.setSpeechRate(speed) == ERROR) {
-                        return@suspendCancellableCoroutine continuation.resume(AndroidTtsError.failure(TtsErrorCode.APP_SPEECH_RATE_FAILED))
+                    if (it.setSpeechRate(speed) == TextToSpeech.ERROR) {
+                        return@suspendCancellableCoroutine continuation.resume(AndroidTtsError.SpeechRateFailed)
                     }
                 }
                 // if it's already playing: stop it
                 it.stopPlaying()
-            } ?: return@suspendCancellableCoroutine continuation.resume(AndroidTtsError.failure(TtsErrorCode.APP_TTS_INIT_FAILED))
+            } ?: return@suspendCancellableCoroutine continuation.resume(AndroidTtsError.InitFailed)
 
             Timber.d("tts text '%s' to be played for locale (%s)", tag.fieldText, tag.lang)
             continuation.ensureActive()
@@ -163,57 +165,74 @@
     }
 }
 
-class AndroidTtsError(@Suppress("unused") val errorCode: TtsErrorCode) : TtsPlayer.TtsError() {
-    enum class TtsErrorCode(var code: Int) {
-        ERROR(TextToSpeech.ERROR),
-        ERROR_SYNTHESIS(TextToSpeech.ERROR_SYNTHESIS),
-        ERROR_INVALID_REQUEST(TextToSpeech.ERROR_INVALID_REQUEST),
-        ERROR_NETWORK(TextToSpeech.ERROR_NETWORK),
-        ERROR_NETWORK_TIMEOUT(TextToSpeech.ERROR_NETWORK_TIMEOUT),
-        ERROR_NOT_INSTALLED_YET(TextToSpeech.ERROR_NOT_INSTALLED_YET),
-        ERROR_OUTPUT(TextToSpeech.ERROR_OUTPUT),
-        ERROR_SERVICE(TextToSpeech.ERROR_SERVICE),
-        APP_UNKNOWN(0),
-        APP_MISSING_VOICE(2),
-        APP_INVALID_VOICE(3),
-        APP_SPEECH_RATE_FAILED(4),
-        APP_TTS_INIT_FAILED(5),
-        APP_TTS_INIT_TIMEOUT(6)
-        ;
+sealed class AndroidTtsError : TtsPlayer.TtsError() {
+    // AnkiDroid specific errors
+    data object UnknownError : AndroidTtsError()
+    data class MissingVoiceError(val tag: TTSTag) : AndroidTtsError()
+    data object InvalidVoiceError : AndroidTtsError()
+    data object SpeechRateFailed : AndroidTtsError()
+    data object InitFailed : AndroidTtsError()
+    data object InitTimeout : AndroidTtsError()
+
+    // Android Errors
+    /** @see TextToSpeech.ERROR */
+    private data object AndroidGenericError : AndroidTtsError()
+
+    /** @see TextToSpeech.ERROR_SYNTHESIS */
+    private data object AndroidSynthesisError : AndroidTtsError()
+
+    /** @see TextToSpeech.ERROR_INVALID_REQUEST */
+    private data object AndroidInvalidRequest : AndroidTtsError()
+
+    /** @see TextToSpeech.ERROR_NETWORK */
+    private data object AndroidNetworkError : AndroidTtsError()
+
+    /** @see TextToSpeech.ERROR_NETWORK_TIMEOUT */
+    private data object AndroidNetworkTimeout : AndroidTtsError()
+
+    /** @see TextToSpeech.ERROR_NOT_INSTALLED_YET */
+    private data object AndroidNotInstalledYet : AndroidTtsError()
+
+    /** @see TextToSpeech.ERROR_OUTPUT */
+    private data object AndroidOutputError : AndroidTtsError()
+
+    /** @see TextToSpeech.ERROR_SERVICE */
+    private data object AndroidServiceError : AndroidTtsError()
 
-        /** A string which google will relate to the TTS Engine in most cases */
-        val developerString: String
-            get() =
-                when (this) {
-                    ERROR -> "ERROR"
-                    ERROR_SYNTHESIS -> "ERROR_SYNTHESIS"
-                    ERROR_INVALID_REQUEST -> "ERROR_INVALID_REQUEST"
-                    ERROR_NETWORK -> "ERROR_NETWORK"
-                    ERROR_NETWORK_TIMEOUT -> "ERROR_NETWORK_TIMEOUT"
-                    ERROR_NOT_INSTALLED_YET -> "ERROR_NOT_INSTALLED_YET"
-                    ERROR_OUTPUT -> "ERROR_OUTPUT"
-                    ERROR_SERVICE -> "ERROR_SERVICE"
-                    APP_MISSING_VOICE -> "APP_MISSING_VOICE"
-                    APP_INVALID_VOICE -> "APP_INVALID_VOICE"
-                    APP_SPEECH_RATE_FAILED -> "APP_SPEECH_RATE_FAILED"
-                    APP_TTS_INIT_FAILED -> "APP_TTS_INIT_FAILED"
-                    APP_TTS_INIT_TIMEOUT -> "APP_TTS_INIT_TIMEOUT"
-                    APP_UNKNOWN -> "APP_UNKNOWN"
-                }
+    /** A string which google will relate to the TTS Engine in most cases */
+    val developerString: String
+        get() =
+            when (this) {
+                is AndroidGenericError -> "ERROR"
+                is AndroidSynthesisError -> "ERROR_SYNTHESIS"
+                is AndroidInvalidRequest -> "ERROR_INVALID_REQUEST"
+                is AndroidNetworkError -> "ERROR_NETWORK"
+                is AndroidNetworkTimeout -> "ERROR_NETWORK_TIMEOUT"
+                is AndroidNotInstalledYet -> "ERROR_NOT_INSTALLED_YET"
+                is AndroidOutputError -> "ERROR_OUTPUT"
+                is AndroidServiceError -> "ERROR_SERVICE"
+                is MissingVoiceError -> "APP_MISSING_VOICE"
+                is InvalidVoiceError -> "APP_INVALID_VOICE"
+                is SpeechRateFailed -> "APP_SPEECH_RATE_FAILED"
+                is InitFailed -> "APP_TTS_INIT_FAILED"
+                is InitTimeout -> "APP_TTS_INIT_TIMEOUT"
+      [...]

2024-08-10 15:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsPlaybackErrorDialog.kt
> +            .create()
I'd replace the `DialogFragment` entirely and use a method with `AlertDialog.Builder().show { }`

2024-08-10 15:39 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="tts_error_toast_message" translatable="false">Unable to open settings</string>
Remove `translatable=false`

2024-08-10 15:39 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="tts_error_toast_message" translatable="false">Unable to open settings</string>
Use the generic `something went wrong` here, no need for additional work for our translators

2024-08-10 15:39 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="tts_error_dialog_supported_voices_button_text" translatable="false">Voices Options</string>
```suggestion
    <string name="tts_error_dialog_supported_voices_button_text" translatable="false">Voice options</string>
```

2024-08-10 15:39 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="tts_error_dialog_reason_text" translatable="false"><b>%1$s</b> engine does not support language : <b>%2$s</b></string>
```suggestion
    <string name="tts_error_dialog_reason_text" translatable="false">Text to speech engine: <b>%1$s</b> does not support language: <b>%2$s</b></string>
```

2024-08-10 15:39 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="tts_error_dialog_title" translatable="false">TTS Error: Missing Language Support</string>
Needs a little reworking: 

We should come here from a `help` button in a "`Text to speech error (%s)`" snackbar:

* Here, we used "Text to speech", not TTS
* A user has context for what the dialog is
* So remove 'TTS Error' prefix
* Material designs prefers sentence case titles

 ```suggestion
    <string name="tts_error_dialog_title" translatable="false">Language not supported</string>
```

2024-08-10 15:39 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="tts_error_dialog_reason_text" translatable="false"><b>%1$s</b> engine does not support language : <b>%2$s</b></string>
I'd typically prefer quotes, rather than `<b>` for the tag lang, but this one's up to you: use what works

2024-08-10 15:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsPlaybackErrorDialog.kt
> +            showThemedToast(requireContext(), getString(R.string.tts_error_toast_message), true)
Also add a `Timber.w` here to add the error to logcat

2024-08-10 15:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsPlaybackErrorDialog.kt
> +            .create()
Add a `Timber.i` that the dialog is shown

2024-08-10 15:43 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="tts_error_toast_message" translatable="false">Unable to open settings</string>
Wait.. why not: `tts_voices_failed_opening_tts_system_settings `

2024-08-10 15:47 UTC, david-allison commented
> Also if its about latency, I am not restablishing the connection to the engine, I just reused it.

The constructor of the `TextToSpeech` class is (roughly) implemented as the following, which contains a lot of potentially expensive and slow calls on different platforms:

```java
// Step 1: Try connecting to the engine that was requested.
        if (mRequestedEngine != null) {
            if (mEnginesHelper.isEngineInstalled(mRequestedEngine)) {
                if (connectToEngine(mRequestedEngine)) {
                    mCurrentEngine = mRequestedEngine;
                    return SUCCESS;
                } else if (!mUseFallback) {
                    mCurrentEngine = null;
                    dispatchOnInit(ERROR);
                    return ERROR;
                }
            } else if (!mUseFallback) {
                Log.i(TAG, "Requested engine not installed: " + mRequestedEngine);
                mCurrentEngine = null;
                dispatchOnInit(ERROR);
                return ERROR;
            }
        }

        // Step 2: Try connecting to the user's default engine.
        final String defaultEngine = getDefaultEngine();
        if (defaultEngine != null && !defaultEngine.equals(mRequestedEngine)) {
            if (connectToEngine(defaultEngine)) {
                mCurrentEngine = defaultEngine;
                return SUCCESS;
            }
        }

        // Step 3: Try connecting to the highest ranked engine in the
        // system.
        final String highestRanked = mEnginesHelper.getHighestRankedEngineName();
        if (highestRanked != null && !highestRanked.equals(mRequestedEngine) &&
                !highestRanked.equals(defaultEngine)) {
            if (connectToEngine(highestRanked)) {
                mCurrentEngine = highestRanked;
                return SUCCESS;
            }
        }

        // NOTE: The API currently does not allow the caller to query whether
        // they are actually connected to any engine. This might fail for various
        // reasons like if the user disables all their TTS engines.

        mCurrentEngine = null;
        dispatchOnInit(ERROR);
        return ERROR;
```

2024-08-15 06:12 UTC, Rohanraj123 commented
@david-allison Can you please review the code  ?

2024-08-15 21:17 UTC, david-allison commented
With apologies, out of time for today, I've posted this on Discord, and please ping me again when you see this

2024-08-15 21:18 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="tts_error_dialog_reason_text"><b>%1$s</b> engine does not support language : <b>%2$s</b></string>
I don't know about this one

```suggestion
    <string name="tts_error_dialog_reason_text">The text to speech engine <b>%1$s</b> does not support the following language: <b>%2$s</b></string>
```

2024-08-15 21:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsPlaybackErrorDialog.kt
> +        Timber.i("Dialog is shown ")
Give context for what the dialog is

2024-08-15 21:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsPlaybackErrorDialog.kt
> +            activity.startActivity(
Consider a `Timber`

2024-08-15 21:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsPlaybackErrorDialog.kt
> +        voicesDialog.show(fragmentManager, "TTS_VOICES_DIALOG_FRAGMENT")
Is this how it was shown elsewhere in the code?

2024-08-15 21:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardMediaPlayer.kt
> +                        TtsErrorCode.APP_MISSING_VOICE -> {
The refactor needs to be extracted out into an initial 'refactor' commit so we can focus on the functionality changes in a second commit

2024-08-15 21:23 UTC, david-allison commented
I /did/ have time, looks great!

If you can't figure out the rebase/two commits, get all other changes done and get it to 'pending merge' and I can take the time to rebase it into shape

2024-08-16 05:22 UTC, Rohanraj123 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsPlaybackErrorDialog.kt
> +        voicesDialog.show(fragmentManager, "TTS_VOICES_DIALOG_FRAGMENT")
Yes, this text is working as a tag to open this fragment everywhere and thats why in starting I kept it in companion object inside that fragment file only so that it can be reusable.

2024-08-16 05:23 UTC, Rohanraj123 commented
![SS](https://github.com/user-attachments/assets/0c5853e4-b014-4ff7-943e-e61e54eee4fc)

Current dialog box!!

2024-08-17 17:26 UTC, Arthur-Milchior reviewed
LGTM. One single request. Appart from that, i don't use TTS so will let someone that actually know what was the issue from a user perspective check the result

2024-08-17 17:26 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsPlaybackErrorDialog.kt
> +        } catch (e: Exception) {
Don't we know anything more specific than exception that we can catch? Just un case we have an actual exception not related to what you care about here, ensuring that we get a crash report

2024-08-18 05:30 UTC, Rohanraj123 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsPlaybackErrorDialog.kt
> +        } catch (e: Exception) {
```
 private fun openSettings(activity: Activity) {
        try {
            Timber.i("Opening TextToSpeech engine settings to change the engine")
            activity.startActivity(
                Intent("com.android.settings.TTS_SETTINGS").apply { flags = Intent.FLAG_ACTIVITY_NEW_TASK }
            )
        } catch (e: Exception) {
            showThemedToast(activity, activity.getString(R.string.tts_voices_failed_opening_tts_system_settings), true)
            Timber.i("Error opening TTS settings: ${e.message}")
        } catch (activityNotFoundException: ActivityNotFoundException) {
            Timber.i("ActivityNotFoundException occurred: ${activityNotFoundException.message}")
        } catch (securityException: SecurityException) {
            Timber.i("SecurityException occurred: ${securityException.message}")
        } catch (illegalArgumentException: IllegalArgumentException) {
            Timber.i("IllegalArgumentException occurred: ${illegalArgumentException.message}")
        }
    }
```
@Arthur-Milchior These are some common exceptions that can occur that can be useful to know.

2024-08-21 05:24 UTC, Rohanraj123 commented
@Arthur-Milchior Ping

2024-08-22 09:29 UTC, david-allison requested changes
Code looks good, one minor improvement to error logging

Requested change to the commit structure, so we can rebase this in

2024-08-22 09:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsPlaybackErrorDialog.kt
> +            Timber.i("Error opening TTS settings: ${e.message}")
Typically: pass in `e` as the first parameter and use `Timber.w`

2024-08-22 09:29 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +<<<<<<< HEAD
We're going to rebase these changes in:

* The code should compile
* The refactor commit message should have `refactor:` as a prefix, and a more concise/'scannable' title
  * message is as long as you want it to be 
* I would /expect/ the refactor to come before the functional change, and only be a refactor
  * The 'refactor' commit which you have isn't a refactor, it's a functional change as it refactors AND enables the dialog. If I were looking for a bug, I'd skip this commit, and that would be the wrong move

2024-08-25 05:31 UTC, Rohanraj123 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +<<<<<<< HEAD
Now I think, It should look fine

2024-08-26 09:01 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsPlaybackErrorDialog.kt
> +        }
This was better previously

2024-08-26 09:08 UTC, david-allison requested changes
The first commit doesn't compile

```
> Task :AnkiDroid:compileAmazonDebugKotlin FAILED
e: file:///C:/Work/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt:111:80 Argument type mismatch: actual type is 'com.ichi2.anki.AndroidTtsError.SpeechRateFailed', but 'com.ichi2.libanki.TtsPlayer.TtsCompletionStatus' was expected.
e: file:///C:/Work/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt:116:73 Argument type mismatch: actual type is 'com.ichi2.anki.AndroidTtsError.InitFailed', but 'com.ichi2.libanki.TtsPlayer.TtsCompletionStatus' was expected.
```

----

I don't think we handle the following user report well:

The problem is that the user has selected a specific AwesomeTTS voice which Android does not provide, the language code should be supported

* https://github.com/ankidroid/Anki-Android/issues/14358#issuecomment-2308545862

----

Other than this, I'm happy to merge and want to push myself to approve this

2024-08-26 09:17 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +<<<<<<< HEAD
The commit title is still too long, but it's MUCH better

Aim for the title to be concise, and the message to add detail


```
refactor(tts-voices): add context to errors

When handling `MissingVoiceError`, knowing the voice 
we searched for enables better error resolution

Adding context required moving from an `enum` to 
`interface` & `data class`, which caused code churn
```

2024-08-28 01:16 UTC, Rohanraj123 commented
> The first commit doesn't compile
> 
> ```
> > Task :AnkiDroid:compileAmazonDebugKotlin FAILED
> e: file:///C:/Work/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt:111:80 Argument type mismatch: actual type is 'com.ichi2.anki.AndroidTtsError.SpeechRateFailed', but 'com.ichi2.libanki.TtsPlayer.TtsCompletionStatus' was expected.
> e: file:///C:/Work/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt:116:73 Argument type mismatch: actual type is 'com.ichi2.anki.AndroidTtsError.InitFailed', but 'com.ichi2.libanki.TtsPlayer.TtsCompletionStatus' was expected.
> ```
> 
> I don't think we handle the following user report well:
> 
> The problem is that the user has selected a specific AwesomeTTS voice which Android does not provide, the language code should be supported
> 
> * [Add support for TTS tags #14358 (comment)](https://github.com/ankidroid/Anki-Android/issues/14358#issuecomment-2308545862)
> 
> Other than this, I'm happy to merge and want to push myself to approve this

Showing a new message when InvalidVoiceError occurs to let them understand that error is because of incompatible voice type. So they need to change the tag would be a good idea. Suggestion ?

2024-08-28 12:52 UTC, david-allison approved these changes
Looks great, thanks so much for sticking with it!

2024-08-28 12:53 UTC, david-allison commented
> So they need to change the tag would be a good idea. Suggestion ?

* You have the language of the tag
* You have the languages supported by the app

Check if the languages of the app contains the language of the tag, if it doesn't, then the user needs to use a new engine/install a voice

If it contains the language, the user needs to add another voice to the tag [or, not ideally: be less specific with the provided voice]

2024-08-31 04:19 UTC, Rohanraj123 commented
@david-allison My understanding behind the change is that InvalidVoiceError addresses the particular issue mentioned above.

2024-08-31 08:57 UTC, david-allison commented
I'm happy to merge this as-is and add a follow-up issue

2024-09-10 06:30 UTC, lukstbit approved these changes
LGTM, thank you for contributing!

2024-09-10 06:43 UTC, merged