feat(card-browser): Chip Based Filtering [Tags, Flags & State]
ankidroid/Anki-Android pull request #16859
Opened 2024-08-11 19:05 UTC by david-allison

> [!IMPORTANT]
> * Commit messages need work, as well as more attribution and thanks to OK
> * State needs a 'clear filter'
> * The textual descriptions on 'State' need a lot of bikeshedding
> * Some copyright headers are duplicated
> * Some of the PR description should be duplicated in comments
>
> I feel the rest is ready for review
## Purpose / Description

This is an Android-based implementation of the sidebar in Anki Desktop which handles `[Tags; Flags; State]`

The implementation begins to productionize @oakkitten's [proposal](https://github.com/ankidroid/Anki-Android/issues/12554) for using [Material 3 Chips](https://m3.material.io/components/chips/overview) to filter categories in the Card Browser. 

* https://github.com/ankidroid/Anki-Android/issues/12554

A large amount of this Pull Request text is copied from the above. THANK YOU

<details>

<summary>Anki Desktop: Browser Sidebar</summary>
<img width="261" alt="Screenshot 2024-08-11 at 17 41 13" src="https://github.com/user-attachments/assets/ff9570d9-4ada-49e4-ae23-bc02fe2cf298">

</details>

### Images

<img width="250" alt="Screenshot 2024-08-11 at 19 28 25" src="https://github.com/user-attachments/assets/6bc47700-ddd8-4147-8cb1-08c9391beb54">

<img width="250" alt="Screenshot 2024-08-11 at 19 27 21" src="https://github.com/user-attachments/assets/39b6c830-7fc8-4aa5-970a-3b50eb51097c">
<img width="250" alt="Screenshot 2024-08-11 at 19 28 46" src="https://github.com/user-attachments/assets/88b26483-819f-408f-a219-0d94b36fbf61">
<img width="250" alt="Screenshot 2024-08-11 at 19 54 32" src="https://github.com/user-attachments/assets/1ed6f20d-f760-4ac7-9cd6-bfdc6ce171b4">

### Behavior

#### Chip Group

<img width="391" alt="Screenshot 2024-08-11 at 18 02 41" src="https://github.com/user-attachments/assets/3474cbbb-9f2a-469e-b454-7f06e2b21dfe">

A single-line chip bar, horizontally scrollable, is placed below the toolbar. Tapping on a chip opens the according bottom sheet, where you can select one or multiple items. When you select items, search is instantly re-applied, and the chip change color, label and optionally, icon to reflect the selection. 

For example, `Flags` changes to `Red` if the red flag is selected or `Red +1` if two are selected. In the latter case, `Red` would be the flag which the user selected first.

In the case of Flags and State, the icon is updated to match the icon of the first selected flag/state

#### Scrolling

The toolbar, along with the chip bar and the spinners bellow, is collapsed when the user scrolls down the list of cards.

#### Bottom Sheets

<img width="392" alt="Screenshot 2024-08-11 at 18 56 26" src="https://github.com/user-attachments/assets/151f4875-9cc7-4e9f-b3a1-f82fc6bcb260">

The bottom sheets show lists of items with icons, text, checkboxes and an optional description. To select items, you can:
  * **Tap on the item icon/label:** 
    * A quick way to select only one thing. The dialog will be closed, a  This will select the tapped item and close the dialog. If any other items were selected, those are de-selected. 
  * **Tap on the checkbox:** 
    * This does not dismiss the dialog and allows the user select multiple items. The dialog may be dismissed by swiping the sheet downwards, or tapping in the scrim area.

All the bottom sheets have a `Clear filter` icon without a checkbox. Tapping on it clears the selection and closes the dialog, stopping filtering by this category.

#### Chevrons / Indenting

**Context**: Hierarchical decks/tags

The bottom sheets can display directory tree-like items. Items that have subitems can be collapsed to hide those and show a clickable chevron to indicate collapsed state (`›`/`⌄`). If there are any chevrons, all items are shifted to the right to make place for the leftmost chevrons.

#### Searching

**Context**: User-defined categories: [Decks; Tags; Note Types]

If there are more than 10 items, a search input is visible with a hint: `Search tags`. Tapping on it expands the sheet to full screen (if enough items). A "clear search" button is shown when text is entered. When typing, items that do not contain the input are hidden, with the exception of any parent items, e.g., searching for `foo` would change

    * abc         
    * def                     * def
      * hello        -->         * hello
         * foo                     * foo
         * bar                * foo fighters
    * foo fighters

The bottom sheet survives rotation, preserving selection & scroll position.

#### Descriptions

<img width="392" alt="Screenshot 2024-08-11 at 18 58 46" src="https://github.com/user-attachments/assets/3af11b52-0272-44ed-8695-79404115c17b">

> [!NOTE] 
> The above screenshot is to demonstrate the UI only, please view the Pull Request for the current strings

The `State` control provides us with an opportunity to explain a number of Anki's concepts to users. I would strongly encourage us all to discuss these descriptions, as these will resolve a number of onboarding issues.

⚠️ My initial descriptions are not sufficient to be merged, and therefore are hardcoded in `CardSheetFragment::State`

### Feature Removals

This pull request removes the following menu items from the Card Browser. These were available from the Card Browser's menu when not in multi-select mode

* Filter marked: 
  * `marked` is implemented as a tag, which is displayed as a tag in the tag selection fragment. This tag is displayed with a distinct 'star' icon
* Filter suspended
  * `suspended` is an option in the **State** chip 
* Filter by tag
  * The **Tags** chip handles all functionality
  * ⚠️ The **All cards/New/Due** selector is not yet fully implemented
    * **New** is handled under **State**
    * ⚠️ Anki Desktop handled `is:due` under **Today**, which will be implemented in a later Pull Request 
* Filter by flag 
  * Handled, with more functionality in the **Flags

### Future Extensions

The following chips are planned, mirroring Anki Desktop's functionality. These were not implemented as this Pull Request is already extremely unwieldy, and will likely result in a long review cycle.

* Decks
  * Introducing this would produce two UI elements which modify the same category in different ways: our current `ActionView`-based UI does not handle multiple decks in an `OR`
  * We should move to a material `SearchView/Bar` in the same commit, and this involved a fair amount of design improvements
* Today
  * Handling parameters: in `Again` -> `rated:1:1` needs a little work
* Note Type
  * Should be an easy implementation, low-yield and I initially chose categories which replaced menu items in the Browser

----

Anki Desktop's Backend contains [3 states](https://github.com/ankitects/anki/blob/5f80ddf27d1bac4966699a767d9277fda56dff18/rslib/src/search/parser.rs#L597-L615) which are not displayed in Anki Desktop:

* `is:due`
  * Exposed somewhat in "Today - Overdue":
  * `Overdue` -> `is:due -prop:due=0`

⚠️ I would support handling the following two states in this Pull Request, 
* `is:buried-manually`
* `is:buried-sibling`

----

* Long-press menus should be available
  * A user may rename a flag
  * A user may delete a tag 
  * A 'Learn More' menu item for states

----

* Each category is searched with `AND`, and items within categories with `OR`. 
   * An advanced search mode will be made available to expose additional filters (`nc:, `re:`), as well as logical options. This will be focused on changing the search text, to expose all of Anki Desktop's search functionality
   * Using the Ctrl/Alt modifiers in Anki Desktop will likely open up this advanced editor. Displaying logical search combinations using a checkbox-based UI is untenable

* Following [this lively questionnaire](https://forums.ankiweb.net/t/do-you-use-these-filters-in-browser-and-why/23518), I think it would be nice to rename `Today` to `Time`, make `Due` find *all* due cards, and remove `Reschedule` & `Overdue`.

----

Selected tags may want to be moved to the top of the list [...]

2024-08-11 19:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/BottomSheetFragment.kt
> +        // TODO: This isn't good
Help wanted here

2024-08-11 20:50 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/BottomSheetFragment.kt
> +        runBlocking { onPrepareAdapter() }
Help wanted here

2024-08-11 22:33 UTC, david-allison commented
* Double-tapping a chip may open the filter sheet twice

2024-08-13 06:17 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/BottomSheetDialogFragmentFix.kt
> +open class BottomSheetDialogFragmentFix : BottomSheetDialogFragment() {
Did you take this class from oakkitten's code?

2024-08-13 06:51 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/BottomSheetDialogFragmentFix.kt
> +open class BottomSheetDialogFragmentFix : BottomSheetDialogFragment() {
Yep

2024-08-13 06:59 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/BottomSheetDialogFragmentFix.kt
> +open class BottomSheetDialogFragmentFix : BottomSheetDialogFragment() {
This behavior of the bottomsheet that this class tries to fix is already fixed in the API, we can remove this class

2024-08-13 07:01 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/BottomSheetDialogFragmentFix.kt
> +open class BottomSheetDialogFragmentFix : BottomSheetDialogFragment() {
```
val behavior = BottomSheetBehavior.from(requireView().parent as View)
behavior.state = BottomSheetBehavior.STATE_EXPANDED
```

2024-08-16 12:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/BottomSheetDialogFragmentFix.kt
> +open class BottomSheetDialogFragmentFix : BottomSheetDialogFragment() {
@criticalAY Could you provide a patch? Didn't work for me

Before 
<img width="754" alt="Screenshot 2024-08-16 at 13 45 14" src="https://github.com/user-attachments/assets/f2d325b7-bca6-4f66-82fa-adc6f4ce86ad">

After

<img width="762" alt="Screenshot 2024-08-16 at 13 44 35" src="https://github.com/user-attachments/assets/1168eb53-eb9e-4c1a-a591-928624ce0a11">

<details>

<summary>Patch I used</summary>

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/browser/BottomSheetFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/browser/BottomSheetFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/browser/BottomSheetFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/browser/BottomSheetFragment.kt	(revision 7d6733c34f0602fb9c13ad409794507c56e7ccfd)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/browser/BottomSheetFragment.kt	(date 1723812441647)
@@ -22,12 +22,14 @@
 import android.widget.ImageButton
 import androidx.core.widget.addTextChangedListener
 import androidx.recyclerview.widget.RecyclerView
+import com.google.android.material.bottomsheet.BottomSheetBehavior
 import com.google.android.material.bottomsheet.BottomSheetBehavior.STATE_EXPANDED
 import com.google.android.material.bottomsheet.BottomSheetDialog
+import com.google.android.material.bottomsheet.BottomSheetDialogFragment
 import com.ichi2.anki.R
 import kotlinx.coroutines.runBlocking
 
-open class BottomSheetFragment : BottomSheetDialogFragmentFix() {
+open class BottomSheetFragment : BottomSheetDialogFragment() {
     open val layoutResource = R.layout.bottom_sheet_list_without_filter
     open val filterHintResource: Int? = null
 
@@ -87,6 +89,11 @@
         return layout
     }
 
+    override fun onStart() {
+        super.onStart()
+        BottomSheetBehavior.from(requireView().parent as View).state = STATE_EXPANDED
+    }
+
     open suspend fun onPrepareAdapter() {}
 
     open fun onFilterInputChanged(filterInput: String) {}
```

</details>

2024-08-18 04:24 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardStateSheetFragment.kt
> +            Buried -> TR.statisticsCountsBuriedCards()
Thank you for the great work.

What do you think about using desktop's "Card State" order and color here?
(I mean, "Suspended, then Buried" order, and some yellow type color for Suspended, some orange type color for Buried.)
![image](https://github.com/user-attachments/assets/ee6c429d-dba8-46de-890d-a2eeab7cf732)

2024-08-18 19:04 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardStateSheetFragment.kt
> +            Buried -> TR.statisticsCountsBuriedCards()
Order: absolutely

Color: I prefer our own, as these match the colors which AnkiDroid uses

2024-08-18 19:25 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardStateSheetFragment.kt
> +            Buried -> TR.statisticsCountsBuriedCards()
To note: I specifically changed our 'order' as it made more sense to me in terms of progression.

Buried is 'Suspend lite' and felt like to deserved to be above Suspend

2024-08-19 01:32 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardStateSheetFragment.kt
> +            Buried -> TR.statisticsCountsBuriedCards()
> I specifically changed our 'order' as it made more sense to me in terms of progression

> Buried is 'Suspend lite' and felt like to deserved to be above Suspend

They sound totally reasonable to me. The order makes more sense to me, too.

How about prioritizing the rationality over consistency with desktop in this case? 

(I might suggest the "Buried, then Suspended" order, to the desktop in the future.)

2024-08-19 01:34 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardStateSheetFragment.kt
> +            Buried -> TR.statisticsCountsBuriedCards()
> Color: I prefer our own, as these match the colors which AnkiDroid uses

I'm still not sure what "the colors which AnkiDroid uses" refer to. In AnkiDroid card/note browser list, "Suspended" row color is pale yellow, and "Buried" row color is not changed from transparent.
![image](https://github.com/user-attachments/assets/19f43b59-3976-454e-a51a-ff60265bdfad)
(2.19alpah10)

2024-08-19 11:51 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardStateSheetFragment.kt
> +            Buried -> TR.statisticsCountsBuriedCards()
OK

* I'll revert the ordering

----
**Colors**

* `ic_card_state_new.xml` uses `attr/newCountColor`, which is the same color as is used in the DeckPicker

* Suspend and bury do not have colors, as I prefer the icons (but am willing to change if anyone feels strongly)
  * We will add a 'bury' color to the row in https://github.com/ankidroid/Anki-Android/pull/16620

* https://github.com/ankidroid/Anki-Android/pull/16620

2024-08-20 00:49 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardStateSheetFragment.kt
> +            Buried -> TR.statisticsCountsBuriedCards()
> Suspend and bury do not have colors, as I prefer the icons

I agree. I too like these icons. 

(I imagined that these icons with a bit of color nuance. But on second thought, the colored symbols might cause a rather inconsistent impression with the above three colored circle icon.)

2024-08-20 00:49 UTC, snowtimeglass commented
> **Bottom Sheets**
> <img src="https://github.com/user-attachments/assets/591a8ba6-4c6d-4100-b984-79cd8ae5b6bd" width="320px">

> - **Tap on the item icon/label:**
> A quick way to select only one thing. The dialog will be closed, a This will select the tapped item and close the dialog. If any other items were selected, those are de-selected.

Regarding the part above, the automatically closing seems useful as the quick way, but I'm still not sure that de-selecting other items would be useful.
> if any other items were selected, those are de-selected.

Is it not possible that the behavior is unexpected for users and this instant de-selecting (accompanied auto-closing the bottom sheet) is somewhat hard to visually confirm on the spot?

2024-08-20 01:57 UTC, snowtimeglass commented on AnkiDroid/src/main/res/drawable/ic_tag.xml
>  </vector>
To begin with, the _label_ icons may be less intuitive for _tag_.

[label icons]
![image](https://github.com/user-attachments/assets/43d67283-0bc4-49be-87fd-ab4618c0a227)

[tag icons]
![image](https://github.com/user-attachments/assets/827273a1-f2ce-46f1-9be6-8b45132b1d8c)

The icon's impression seems to become even more ambiguous when many of them are lined up.
<img src="https://github.com/user-attachments/assets/184c42f1-e81f-4c21-843e-8348d66ec45d" width="320px">

How about using an _hanging-tag_ icon instead, as in Anki Desktop.


![image](https://github.com/user-attachments/assets/a0032453-aea4-48f1-b583-4fd65c48c771)
https://pictogrammers.com/library/mdi/icon/tag-outline/

![image](https://github.com/user-attachments/assets/e5576038-ddc5-4cc3-be97-60b7b3753138)
(Anki Desktop)

(The existing icon for "Edit tags" in Reviewer screen menu could also subject to change in that case.)

2024-08-20 11:12 UTC, david-allison commented
> Is it not possible that the behavior is unexpected for users and that this instant de-selecting (accompanied auto-closing the bottom sheet) is somewhat hard to visually confirm on the spot?

Long-term: 
* One click to select is the most efficient behavior possible, I like it

Short-term:
* There's enough post-action visual feedback for a user to know that everything is deselected
* The only thing I don't like is that there's a bug in the visual 'ripple' effect when an item is selected, it's not as prominent as it should be.
* I feel a "everything was deselected" modal would be annoying (maybe a snackbar with an undo)

----

I don't feel the comment is prescriptive in a sense of "we should do this instead", and would like a path to resolution

2024-08-20 11:19 UTC, david-allison commented on AnkiDroid/src/main/res/drawable/ic_tag.xml
>  </vector>
This looks much nicer, thanks!

<img width="391" alt="Screenshot 2024-08-20 at 12 19 29" src="https://github.com/user-attachments/assets/032aa290-4478-4961-bdb0-1d708eaaede9">

2024-08-20 11:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardStateSheetFragment.kt
> +            Buried -> TR.statisticsCountsBuriedCards()
If we can do it with the design, it'd be great to combine the two

I suspect we can't make it look good, but this is a pain point: I saw a user with a card browser full of yellow cards, asking why they couldn't see any of them

2024-08-20 11:44 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardStateSheetFragment.kt
> +            Buried -> TR.statisticsCountsBuriedCards()
@AnKingMed - I suspect you've done a lot of thinking about card suspension given your workflow. Any and all thoughts would be appreciated

We're adding a 'state selector' to enable users to filter cards in the Card Browser based on state [wording pending], but I feel:

* If a user imports a deck of suspended cards, the first time they come into the browser, it's not 'obvious' that cards are suspended, and we need some way of better explaining what a suspended card is (likely when entering the screen, tapping the card, or immediately opening the browser with `-is:suspended`, so a user can visually see that we're excluding suspended cards, and makes the yellow -> suspended association by removing the filter)
* The yellow background of a suspended card isn't obviously suspended, and doesn't map well to the current icon we're using [as we don't include the yellow color here]


![image](https://github.com/user-attachments/assets/98a5dd6f-03f9-49f8-86f6-2e002fb48938)

2024-08-20 22:28 UTC, AnKingMed commented
> If a user imports a deck of suspended cards, the first time they come into the browser, it's not 'obvious' that cards are suspended, and we need some way of better explaining what a suspended card is. None of these options seem great:
when entering the screen,
tapping the card,
immediately opening the browser with -is:suspended,
so a user can visually see that we're excluding suspended cards, and makes the yellow -> suspended association by removing the filter
The yellow background of a suspended card doesn't obviously imply that the card is suspended, and doesn't map well to the current icon we're using [as we don't include the yellow color here]

Can you just have a popup when importing that says "some or all of the cards you've imported are suspended. To start studying them, visit the browser and unsuspend these cards"

2024-08-21 09:25 UTC, snowtimeglass commented
> I don't feel the comment is prescriptive in a sense of "we should do this instead", and would like a path to resolution

(In conclusion, I don't disagree with the current way.)

I still don't have a thought of "this way should be done" about this. I still don't even have a thought of "I prefer this way more", either.

I just feel that deselecting the other items might be uncommon as a behavior in such bottom sheets of Android.

If I suggest an alternative, it may be the common (in my assumption. It may be wrong) behavior as in Gmail, that is, not-deselecting the other items:

https://github.com/user-attachments/assets/da296b75-47c6-4582-b5e0-2721c86e0675

(Gmail)

However, on second thought, one click to select one item exclusively is consistent with the behavior in the desktop browser. It seems that there is enough post-action visual feedback. Also, user can select multiple items by clicking check boxes. So, I agree these distinguished selection ways are useful.

2024-08-21 09:52 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardStateSheetFragment.kt
> +            Buried -> TR.statisticsCountsBuriedCards()
> If we can do it with the design, it'd be great to combine the two
> 
> I suspect we can't make it look good, but this is a pain point: I saw a user with a card browser full of yellow cards, asking why they couldn't see any of them

How about this kind of approach.
- Put distinguished symbols inside the top three circle icons (New, Learning, Review)
- Color the bottom two symbol icons (Buried, Suspended)
  - The shape style of the bottom two icons are kept as it is. I mean, the symbols (for Buried and Suspended) won't get placed inside colored circle, unlike the top three icons. So, visual emphasis for the top three icons (New, Learning, Review) will be maintained as it is.
  
[mockup]
![image](https://github.com/user-attachments/assets/deea60c6-72b0-416c-8efc-4d40b4f18a42)

2024-08-21 10:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardStateSheetFragment.kt
> +            Buried -> TR.statisticsCountsBuriedCards()
I'd prefer the top 3 without icons (unless we get something incredibly good - maybe a plant analogy)

Suspend fails accessibility guidelines for graphical elements: https://webaim.org/resources/contrastchecker/?fcolor=CDCD00&bcolor=E5ECF0, we'd maybe need a black border?

Bury is a borderline fail, but we can fix this:

https://webaim.org/resources/contrastchecker/?fcolor=D48701&bcolor=E5ECF0

2024-08-22 09:56 UTC, snowtimeglass commented on AnkiDroid/src/main/res/drawable/ic_marked.xml
> +</vector>
The star icon looks pretty good to me. @oakkitten Thank you.

---

<img src="https://github.com/user-attachments/assets/3dcbf6f3-8ddc-4888-b87d-4570610ef789" width="320px">

How about treating the "Marked" tag specially even in other points? I mean,

- Put it at the top of the list constantly (when the "Marked" tag is used in one or more notes)
- Make the label translatable

---

What do you think about giving "Leech" tag an unique icon as well as "Marked" tag? 

[images]
![image](https://github.com/user-attachments/assets/0468101a-594c-499b-8304-8f608b04a489)

2024-08-22 10:30 UTC, david-allison commented on AnkiDroid/src/main/res/drawable/ic_marked.xml
> +</vector>
Agreed on both counts

2024-08-22 14:56 UTC, david-allison commented on AnkiDroid/src/main/res/drawable/ic_marked.xml
> +</vector>
One for consideration:

* Running with errors

<img width="82" alt="Screenshot 2024-08-22 at 15 55 22" src="https://github.com/user-attachments/assets/6d92ef6e-1313-4aa8-8331-ae74b9cb11de">

2024-08-23 01:03 UTC, snowtimeglass commented on AnkiDroid/src/main/res/drawable/ic_marked.xml
> +</vector>
> ![image](https://github.com/user-attachments/assets/a237ab48-2ef3-4502-a331-80acef3be7e5)

It is somewhat hard for me to associate it with "leech", as it conjures up an early error in the middle of a relatively short (seconds or hours) incessant process. 

I suppose some other icon is desirable.

[some alternatives]
![image](https://github.com/user-attachments/assets/a6d61af5-b9e5-4f4e-a3b1-682ad5c48f7f)
![image](https://github.com/user-attachments/assets/d1afd844-e2e5-49a9-b900-5c52cb4acd67)
https://pictogrammers.com/library/mdi/

Simple, abstract unique symbols that suggest some kind of warning or negative status. 
An answer to those who seek its meaning is "bloodsucking" (or "euphemism for biological leech").

2024-08-23 06:05 UTC, brishtibheja commented on AnkiDroid/src/main/res/drawable/ic_marked.xml
> +</vector>
A similar discussion happened here: [forums.ankiweb.net](<https://forums.ankiweb.net/t/anki-2-1-45-beta/10664/7?u=sorata>)

2024-08-23 07:58 UTC, david-allison commented on AnkiDroid/src/main/res/drawable/ic_marked.xml
> +</vector>
I don't want this to block the PR going in

I'm going to use "tag" for now, and we should split this into a future issue/extension

Personally, I want the icon to convey "this card has taken up too much time", and this is a problem

* We want a line of text and probably a link

I'd personally want a line similar to the following

> Eliminating 10% of the most difficult items in a generic material may produce an increase in the speed of learning of up to 300% 
> [Learn more]

2024-08-23 09:38 UTC, david-allison commented on AnkiDroid/src/main/res/drawable/ic_marked.xml
> +</vector>
https://github.com/ankidroid/Anki-Android/issues/16933

2024-08-26 11:37 UTC, snowtimeglass commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardStateSheetFragment.kt
> +    Suspended(4, R.drawable.ic_suspend, "Cards which aren't shown unless unsuspended", "is:suspended")
<img src="https://github.com/user-attachments/assets/3c578b2f-9f48-485d-a023-4f720bebe4da" width="200px">

---

For brainstorming:

**New**
Cards that have never been 
answered

**Learning**
Cards being learned to put 
contents into long-term memory

**Review**
Cards to keep and consolidate 
contents in long-term memory

**Buried**
Cards that aren't shown today 
regardless of schedule

**Suspended**
Cards that aren't shown until 
manually undone

2024-08-26 12:08 UTC, lukstbit requested changes
This isn't blocking, I'm leaving some personal notes on the design:

For card states I would choose using colors instead of the icons:
- it's consistent with desktop, much easier transition for users coming from desktop
- having both looks a bit weird IMO
- it reinforces the filtering action by creating a link between the color circle and the color of the rows that are shown after the selection(even if this isn't showing now it will be available at some point)

Love the tags icon.

2024-08-26 13:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/BottomSheetFragment.kt
> +        runBlocking { onPrepareAdapter() }
> I'm going to be completely honest and say that this entire class and the class hierarchy seems over abstracted and this over abstraction introduces issues like the one above which wouldn't happen if the filtering panels were independent. The three filtering panel only have in common using a RecyclerView and having a very similar row. However the tree structure is really only needed in the tags panel while the other two could simple build their UI manually, they don't even really need a RecyclerView/Adapter combination.

This is the feedback which I needed. I discarded the `Wizard` style abstraction from the linked PR, but this is a better approach

2024-08-27 20:43 UTC, BrayanDSO reviewed
Some remarks:

Just the tip of the dialog shows up if there are no tags to show. Some kind of message would be good:
- You haven't created any tags
- There are no tags in your cards
- There isn't any tag. Create one in this magic link/button

---

The flags and state dialogs use checkboxes, and checkboxes infer a multiple items choice, not a single item choice. So, radio buttons would be better there.

---
If I rename a flag while that flag is set in the chip, the name isn't updated in the chip until I reselect the flag

2024-08-30 22:00 UTC, oakkitten requested changes
Collapsing tags doesn't work btw.

Didn't have the time to properly look at the PR but here's a few thoughts anyway.

* Gmail, for one, shows `Whatever+1` not `Whatever +1` (no space) when multiple things are selected for a chip

* I opted for not changing the icon of the chip if a corresponding flag, etc, is changed. This is because while we can show `Red flag+1` for more than two flags, keeping only the red flag in this instance would be misleading. While it is probably rare that the user selects multiple things in any of the cases, I'd still go this way unless we have a special icon for `Red flag+1`. Can't imagine there's an icon that is good enough for this.

* Not sure why the hit target for the chevrons was reduced? They are very hard to tap now.

* Not sure why the margins of items have changed? Checkboxes are now too close to the edges, as is the search field, but then the distance between it and the top of the sheet hasn't changed?

* Tapping on tag without a chevron triggers the background of the chevron now

* When I wrote the code, I considered “Clear filter” and the like but instead went for “All decks” and “Any tags” for the following reasons:

  * We don't use the word “filter” anywhere, and while it should be evident that this is essentially a filter I could avoid a new word.

  * Having “All decks” *in the list* of decks feels more natural than “Clear filter”. If there's a “Clear filter”, it should be a separately displayed button and not an element of the list.

  * “Clear filter” is common enough thing, however i'm not sure if it has a commonly accepted icon. In any case, `×` is *not* a suitable icon. For popups, and a bottom sheet is a popup, `×` means to close without action.

  I didn't want a separate button, so I went with a different phrase and an unique icon that I think is a good representation of “many things”.

* Also, “Clear filter” is improperly aligned with the other items.

* The empty flag icon is too thin, the title should not be capitalized in song style.

* I am strongly against sub-lables in “State”. These labels are vastly inadequate for the purpose of explaining of the underlying concepts, and the current ones are mostly tautology anyway. “Cards that are still being learnt” adds zero infomation to “Learning”. Add a “Help” button if you must, but for something that is used commonly (unlike stuff in Settings) these subtitles just introduce clutter.

* No idea what the icons for “Buried” and “leech” are supposed to convey to me. I mean, I kind of do, but these icons are just not helpful. Suggest going with default stuff until there's a solid suggestion.

* Regarding the state icons, I would still go with my original idea [because of the same reasons as before](https://github.com/ankidroid/Anki-Android/issues/12554#issuecomment-1272575662). I understand the counterargument but I'm just not convinced enough. In any case, can we do better than simply colored circles? That's plain ugly and undescriptive.

* Non-colored icons appear to have different color in different sheets. I prefer same color as text, but whichever we choose we should stick with one, hopefully.

* Chevrons are wrong color if the device is in dark mode.

2024-09-29 12:14 UTC, david-allison commented
I'll close this for now. I'm not going to have the time to get to it for a while, and when I do, I'll split it further into smaller PRs

2024-09-29 12:14 UTC, closed without merging