[GSoC'24]: Implement Keyboard Shortcuts Helper
ankidroid/Anki-Android pull request #16880
Opened 2024-08-16 06:37 UTC by SanjaySargam

## Purpose / Description
Keyboard shortcuts for Chromebook users are important because they make it easier and faster to use AnkiDroid.  `Alt + K` shortcut will show keyboard shortcuts dialog

## How Has This Been Tested?
HP CHROMEBOOK
[Screen recording 2024-08-16 11.38.57 AM.webm](https://github.com/user-attachments/assets/ba741764-6d64-4842-b6fc-1e8419a5b128)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem
https://developer.android.com/develop/ui/compose/touch-input/keyboard-input/keyboard-shortcuts-helper

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-08-16 10:07 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="show_keyboard_shortcuts_dialog">Show keyboard shortcuts dialog</string>
I'm sorry, because, this is going to be very boring. But can you check that all of those strings are new. If they are not, then please simply consider reusing it.
I would expect that for most case, you'd have an entry in the menus. For example, instead of "Save Note", I think we could reuse "Save" that is already used as a label of the tick in the note editor.

Ideally, I 'd like the strings to be grouped with other strings related to the same feature. E.g. the Open Statistics could be in 10-preferences. After all, I expect that, from a translator point of view (which is what matters here), they should see this string when they want to consider the Preferences.

Finally, I'm going to ask you to add a comment for all of them, because it's probably not clear for translators that this string appear in the context of a shortcut description, or of the category of shortcuts.

It could be simply something such as 
`comment="Description of the shortcut that open the statistics page"`

FYI, "Open statistics" is good, I'm happy that the descriptions are small as much as possible. However, the comment should be very very explicit. Because the translator can't just test the shortcut (as they are not currently using the app, and even if they have a smartphone with ankidroid, they may not even have a keyboard)
And they should be very sure what the shortcut does so that they can find an appropriate short description

2024-08-16 10:07 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
> +            KeyboardShortcutGroup(
As discussed on discord, I'd prefer this to be in a companion object in the CardTemplateEditor. It will be simpler to  find where to edit the shortcut content when you edit the code for shortcut.

Also, I'd appreciate if, near the function dealing with shortcut, you can add a comment that state "When you edit this field, reflect the change in `cardTemplateEditorShortcutGroup`

2024-08-17 17:28 UTC, SanjaySargam commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="show_keyboard_shortcuts_dialog">Show keyboard shortcuts dialog</string>
Ok I'll do

2024-08-19 13:46 UTC, david-allison reviewed
Fundamentally: great change!

2024-08-19 13:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV23.kt
> +    override fun getAllShortcuts(activity: Activity): MutableList<KeyboardShortcutGroup> {
This should return a `List<>`, not a mutable list

2024-08-19 13:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        val shortcutGroups = CompatHelper.compat.getAllShortcuts(this)
Why are we showing shortcuts irrelevant to the current screen?

The reply also be a code comment

2024-08-19 13:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        if (keyCode == KeyEvent.KEYCODE_K && event.isAltPressed) {
This is a good start, but realistically nobody is going to know about this keyboard shortcut

There's a number of things we can do here, for example:

* If a user presses an unmapped shortcut, show a message that "Alt+K" shows all shortcuts?

2024-08-19 13:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV23.kt
> +    override fun showKeyboardShortcutsDialog(activity: Activity) {
This feels like it should be an extension method on `Activity`

2024-08-19 13:46 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="show_keyboard_shortcuts_dialog">Show keyboard shortcuts dialog</string>
Also: do other apps use Title Case, or Sentence case for these strings?

2024-08-19 13:46 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
> +    data class Shortcut(val shortcut: String, @StringRes val labelRes: Int) {
I suspect we want to allow `TR` accessors here as well

2024-08-20 18:26 UTC, SanjaySargam commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="show_keyboard_shortcuts_dialog">Show keyboard shortcuts dialog</string>
Yes 
Ex: Discord
![image](https://github.com/user-attachments/assets/37d645b6-ec48-4d95-a038-2feea318edaf)

2024-08-20 18:35 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        val shortcutGroups = CompatHelper.compat.getAllShortcuts(this)
We include all shortcuts here so that the keyboard shortcut dialog can be opened from anywhere in the app using the Alt+K shortcut, ensuring users have quick access to all available shortcuts regardless of the current screen.

2024-08-20 19:29 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
> +    data class Shortcut(val shortcut: String, @StringRes val labelRes: Int) {
Translating `shortcut`? I don't think so, ig keyboard is universally same irrespective of language

2024-08-20 19:52 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        if (keyCode == KeyEvent.KEYCODE_K && event.isAltPressed) {
How can I get unmapped shortcut? Do you know any easy way to achieve it

2024-08-21 18:20 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
> +            KeyboardShortcutGroup(
> As discussed on discord, I'd prefer this to be in a companion object in the CardTemplateEditor. It will be simpler to find where to edit the shortcut content when you edit the code for shortcut.

Is this goes similar to other screens (DeckPicker, NoteEditor, CardBrowser) ??

2024-08-22 15:30 UTC, david-allison requested changes

2024-08-22 15:30 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
> +    data class Shortcut(val shortcut: String, @StringRes val labelRes: Int) {
For the `labelRes`

2024-08-22 15:30 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="study_deck" comment="Description of the shortcut that starts studying the selected deck">Study deck</string>
`TR.decksStudyDeck()`

2024-08-22 15:30 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="note_editor_group" comment="Label for the group of shortcuts related to the note editor">Note Editor</string>
This should exist as a title?

2024-08-22 15:30 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="deck_picker_group" comment="Label for the group of shortcuts related to the deck picker">Deck Picker</string>
This should exist as a title?

2024-08-22 15:30 UTC, david-allison commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="export_cards" comment="Description of the shortcut that exports cards">Export cards</string>
Maybe `exportingExport`: `Export...`

2024-08-22 15:30 UTC, david-allison commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="toggle_mark" comment="Description of the shortcut that toggles the mark on selected cards">Toggle mark</string>
`TR.browsingToggleMark()`

2024-08-22 15:30 UTC, david-allison commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="reschedule_cards" comment="Description of the shortcut that reschedules the selected cards">Reschedule cards</string>
Maybe `TR.browsingReschedule()`

2024-08-22 15:30 UTC, david-allison commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="reposition_cards" comment="Description of the shortcut that repositions the selected cards">Reposition cards</string>
Maybe `TR.actionsReposition()`

2024-08-22 15:30 UTC, david-allison commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="toggle_suspended_cards" comment="Description of the shortcut that toggles the suspended state of selected cards">Toggle suspended cards</string>
Maybe `TR.browsingToggleSuspend`

2024-08-22 15:30 UTC, david-allison commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="display_card_info" comment="Description of the shortcut that displays information about the selected card">Display card info</string>
Maybe `actionsCardInfo()`

2024-08-22 15:30 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        val shortcutGroups = CompatHelper.compat.getAllShortcuts(this)
I'll leave this one to @Arthur-Milchior

Personally:

* If a screen has no specific actions, I'd want everything
* f a screen has specific actions, I'd only want to see relevant actions + global actions

2024-08-22 17:23 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
> +    data class Shortcut(val shortcut: String, @StringRes val labelRes: Int) {
Rough code 

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt	(revision 278d9e9a91d7e53f325485bb09f6fd1d986d3677)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt	(date 1724347336601)
@@ -1253,11 +1253,11 @@
             Shortcut("Ctrl+NUMPAD_3", R.string.edit_styling),
             Shortcut("Ctrl+S", R.string.save),
             Shortcut("Ctrl+I", R.string.card_template_editor_insert_field),
-            Shortcut("Ctrl+A", R.string.add_card),
-            Shortcut("Ctrl+R", R.string.rename_card),
+            Shortcut("Ctrl+A") { cardTemplatesAddCardType() },
+            Shortcut("Ctrl+R") { cardTemplatesRenameCardType() },
             Shortcut("Ctrl+B", R.string.card_template_browser_appearance_title),
-            Shortcut("Ctrl+D", R.string.delete_card),
-            Shortcut("Ctrl+O", R.string.card_template_editor_deck_override),
+            Shortcut("Ctrl+D") { cardTemplatesRemoveCardType() },
+            Shortcut("Ctrl+O") { cardTemplatesDeckOverride() },
             Shortcut("Ctrl+M", R.string.copy_markdown)
         )
     }
Index: AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt b/AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
--- a/AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt	(revision 278d9e9a91d7e53f325485bb09f6fd1d986d3677)
+++ b/AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt	(date 1724347336584)
@@ -30,11 +30,13 @@
 import androidx.draganddrop.DropHelper
 import com.ichi2.anki.CardBrowser
 import com.ichi2.anki.CardTemplateEditor
+import com.ichi2.anki.CollectionManager.TR
 import com.ichi2.anki.DeckPicker
 import com.ichi2.anki.NoteEditor
 import com.ichi2.anki.R
 import com.ichi2.anki.common.utils.android.isRobolectric
 import com.ichi2.utils.ClipboardUtil.MEDIA_MIME_TYPES
+import net.ankiweb.rsdroid.Translations
 import timber.log.Timber
 import java.util.Locale
 
@@ -109,13 +111,38 @@
         return shortcutGroups
     }
 
+    sealed interface StringResource {
+        /**
+         * @param labelRes The string resource ID for the shortcut label.
+         */
+        data class AndroidTranslation(@StringRes val labelRes: Int): StringResource {
+            override fun toDisplayString(context: Context): String = context.getString(labelRes)
+        }
+
+        /**
+         * Represents a function returning a translated string from the Anki Backend
+         *
+         * **Usage**
+         * ```kotlin
+         * AnkiBackendTranslation { editingTags() }
+         * ```
+         */
+        data class AnkiBackendTranslation(val getTranslation: Translations.() -> String): StringResource {
+            override fun toDisplayString(context: Context): String = getTranslation(TR)
+        }
+
+        // TODO: Parameters are not supported
+        fun toDisplayString(context: Context) : String
+    }
+
     /**
      * Data class representing a keyboard shortcut.
      *
      * @param shortcut The string representation of the keyboard shortcut (e.g., "Ctrl+Alt+S").
-     * @param labelRes The string resource ID for the shortcut label.
      */
-    data class Shortcut(val shortcut: String, @StringRes val labelRes: Int) {
+    data class Shortcut(val shortcut: String, val label: StringResource) {
+        constructor(shortcut: String, @StringRes labelRes: Int) : this(shortcut, StringResource.AndroidTranslation(labelRes))
+        constructor(shortcut: String, getTranslation: Translations.() -> String) : this(shortcut, StringResource.AnkiBackendTranslation(getTranslation))
 
         /**
          * Converts the shortcut string into a KeyboardShortcutInfo object.
@@ -124,7 +151,7 @@
          * @return A KeyboardShortcutInfo object representing the keyboard shortcut.
          */
         fun toShortcutInfo(context: Context): KeyboardShortcutInfo {
-            val label: String = context.getString(labelRes)
+            val label: String = label.toDisplayString(context)
             val parts = shortcut.split("+")
             val key = parts.last()
             val keycode: Int = KeyEvent.keyCodeFromString(key)
```

2024-08-23 11:02 UTC, SanjaySargam commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="note_editor_group" comment="Label for the group of shortcuts related to the note editor">Note Editor</string>
Didn't exists

2024-08-23 11:03 UTC, SanjaySargam commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="deck_picker_group" comment="Label for the group of shortcuts related to the deck picker">Deck Picker</string>
didn;t exists

2024-08-24 11:26 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        val shortcutGroups = CompatHelper.compat.getAllShortcuts(this)
@Arthur-Milchior FYI

2024-08-24 15:21 UTC, brishtibheja commented
Is <kbd>Alt</kbd>+<kbd>K</kbd> used in other Android devices? I couldn't find that on my own. In my Android, the global shortcut is <kbd>Search</kbd>+<kbd>/</kbd> and it also works in Google keep notes. The app-specific shortcuts are shown along with the system shortcuts here.

2024-08-24 15:53 UTC, SanjaySargam commented
> Is <kbd>Alt</kbd>+<kbd>K</kbd> used in other Android devices?

Nope. Here `K` for keyboard shortcuts

2024-08-24 16:59 UTC, brishtibheja commented
It would be nice to have it match with other apps/system shortcuts, although I'm not sure if there's a standard or it just depends on app/device.

2024-08-25 03:35 UTC, Arthur-Milchior commented
My bad, I'm very sorry, my mistake.
When I saw 
![image](https://github.com/user-attachments/assets/14e7e50b-8b6b-49e4-84f5-aa0598caa892)
on https://developer.android.com/develop/ui/compose/touch-input/keyboard-input/keyboard-shortcuts-helper
I thought that "System" "Input" and "Open Apps" were three KeyboardShortcutGroup.

I would have been fine to have such a UI. Let's say you're in card browser, you'll see the CardBrowser group first. And if you wanted, you could open the other groups, to get an idea of what you can do in the deck picker let's say. But by default, you'd only get the currently relevent shortcuts.

Clearly, I was wrong, and the "groups" are all displayed at once in a single list. This indeed looks far too busy. I don't like it.

So, yeah, I'm sorry and I'll ask you to revert and only show the shortcuts from the current activities.

Please also only display the message about shortcut only if there are available shortcuts, so that we don't offer to the user a list of shortcut that only contains alt+k

2024-08-25 06:08 UTC, brishtibheja commented
Wouldn't it be prudent to use <kbd>Search</kbd>+<kbd>/</kbd> for the message or it's too much work to change now?

2024-08-26 05:13 UTC, brishtibheja commented
I was saying the shortcut in this PR could be Meta+/ as it's seemed to be used elsewhere too.

2024-08-26 13:18 UTC, SanjaySargam commented
But the problem is Chromebook does not have `Meta` button

2024-08-26 13:28 UTC, david-allison approved these changes

2024-08-26 13:28 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="tags_dialog" comment="Description of the shortcut that opens the tags dialog">Tags dialog</string>
Could be a better string

2024-08-26 13:28 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="deck_selection_dialog" comment="Description of the shortcut that opens the deck selection dialog">Deck selection dialog</string>
Could be a better string, list what it does (select deck), not what it is

2024-08-26 13:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
> +            Shortcut("Alt+K", R.string.show_keyboard_shortcuts_dialog),
I don't think this is a good shortcut, but the rest of the PR is good. Happy with this for now

2024-08-26 13:30 UTC, david-allison commented
@SanjaySargam I wouldn't oppose two shortcuts, especially if <kbd>META + /</kbd> is common

2024-08-26 23:52 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        if (keyCode == KeyEvent.KEYCODE_K && event.isAltPressed) {
The snackbar shows up every time any key is pressed, which includes the back and volume buttons.

And why `Alt+K`? Is that a standard somewhere? In iPadOS it is `Command` (https://support.apple.com/en-us/102393). Anything that can benefit from external consistency is good to me.

> If a user presses an unmapped shortcut, show a message that "Alt+K" shows all shortcuts?

It is useful only once and very annoying every time a miss a shortcut in the future. Alos, that will be a nightmare with controllers, special keys and special devices.

2024-08-27 07:56 UTC, SanjaySargam commented
I would have been fine to have such a UI
@Arthur-Milchior There is no such in-built UI exists in KeyboardShortcutHelper. Only way to achieve is to design from stratch

2024-08-27 07:58 UTC, SanjaySargam commented
> Please also only display the message about shortcut only if there are available shortcuts, so that we don't offer to the user a list of shortcut that only contains alt+k

@Arthur-Milchior I don't understand this statement. Will you please explain it again

2024-08-27 08:47 UTC, SanjaySargam commented
> @SanjaySargam I wouldn't oppose two shortcuts, especially if META + / is common

I tried adding `Meta+/` it does nothing, does not shows keyboard shortcut dialog

2024-08-27 22:41 UTC, Arthur-Milchior commented
> @Arthur-Milchior There is no such in-built UI exists in KeyboardShortcutHelper. Only way to achieve is to design from stratch

Yeah, I discovered that.
I am really not asking you to create a new UI from scratch. If it's not standard in Android apps, I don't think we should create it for ankidroid.
My point was only that it's what, as a user, I'd appreciate.

2024-08-28 03:31 UTC, Arthur-Milchior reviewed
Main problem is that when I create a card or type in any text field, I get the shortcut stating to use alt+k

Also other some nits

2024-08-28 03:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            Shortcut("Ctrl+B", R.string.backup_restore),
Do we actually want that as a shortcut? Restoring from backup should be quite rare, and potentially dangerous, so I'd prefer not to be able to do it by accident.

2024-08-28 03:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            Shortcut("DEL", R.string.delete_deck_title),
Please put "delete deck" before the one "without confirmation"

2024-08-28 03:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            Shortcut("DEL", R.string.delete_deck_title),
Please only add those elements if the view is fragmented, to be consistent with the shortcuts implementation

2024-08-29 20:13 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        val shortcutGroups = CompatHelper.compat.getAllShortcuts(this)
Oops sorry.
In my mind, if a screen has no specific action, I prefer to see only the ankidroid general actions, even if they are only two.
And, most importantly, let's not show the snackbar to tell users to use alt-k. After all, when there is no specific action, this snackbar is pointless

2024-08-29 21:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        if (keyCode == KeyEvent.KEYCODE_K && event.isAltPressed) {
I refined the statement in a follow-up comment to only include shortcuts with modifier keys pressed

2024-08-30 00:03 UTC, Arthur-Milchior commented
My excuses. I thought for some wrong reason that most fragments were AnkiFragment.

Let's get a better version

```patch
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
index d66e66ebc6..826a4ad88b 100644
--- a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
@@ -13,8 +13,6 @@ import android.media.AudioManager
 import android.net.Uri
 import android.os.Build
 import android.os.Bundle
-import android.view.KeyboardShortcutGroup
-import android.view.Menu
 import android.view.MenuItem
 import android.view.View
 import android.view.ViewGroup
@@ -56,9 +54,7 @@ import com.ichi2.anki.preferences.sharedPrefs
 import com.ichi2.anki.snackbar.showSnackbar
 import com.ichi2.anki.workarounds.AppLoadedFromBackupWorkaround.showedActivityFailedScreen
 import com.ichi2.async.CollectionLoader
-import com.ichi2.compat.CompatHelper
 import com.ichi2.compat.CompatV24
-import com.ichi2.compat.ShortcutGroupProvider
 import com.ichi2.compat.customtabs.CustomTabActivityHelper
 import com.ichi2.compat.customtabs.CustomTabsFallback
 import com.ichi2.compat.customtabs.CustomTabsHelper
@@ -71,7 +67,7 @@ import androidx.browser.customtabs.CustomTabsIntent.Builder as CustomTabsIntentB
 
 @UiThread
 @KotlinCleanup("set activityName")
-open class AnkiActivity : AppCompatActivity, SimpleMessageDialogListener, ShortcutGroupProvider {
+open class AnkiActivity : AppCompatActivity, SimpleMessageDialogListener {
 
     /** The name of the parent class (example: 'Reviewer')  */
     private val activityName: String
@@ -592,17 +588,10 @@ open class AnkiActivity : AppCompatActivity, SimpleMessageDialogListener, Shortc
         return false
     }
 
-    override fun onProvideKeyboardShortcuts(
-        data: MutableList<KeyboardShortcutGroup>,
-        menu: Menu?,
-        deviceId: Int
-    ) {
-        val shortcutGroups = CompatHelper.compat.getShortcuts(this)
-        data.addAll(shortcutGroups)
-        super.onProvideKeyboardShortcuts(data, menu, deviceId)
-    }
-
-    override val shortcuts: CompatV24.ShortcutGroup? = null
+    /**
+     * Lists of shortcuts for this fragment, and the IdRes of the name of this shortcut group.
+     */
+    open val shortcuts: CompatV24.ShortcutGroup? = null
 
     companion object {
         const val DIALOG_FRAGMENT_TAG = "dialog"
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiFragment.kt
index 1c34f059cd..b719fb378f 100644
--- a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiFragment.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiFragment.kt
@@ -29,6 +29,7 @@ import androidx.appcompat.widget.Toolbar
 import androidx.fragment.app.DialogFragment
 import androidx.fragment.app.Fragment
 import com.ichi2.async.CollectionLoader
+import com.ichi2.compat.CompatV24
 import com.ichi2.libanki.Collection
 import com.ichi2.utils.increaseHorizontalPaddingOfOverflowMenuIcons
 import com.ichi2.utils.tintOverflowMenuIcons
@@ -218,4 +219,9 @@ open class AnkiFragment(@LayoutRes layout: Int) : Fragment(layout) {
         requireActivity().finish()
         return false
     }
+
+    /**
+     * Lists of shortcuts for this fragment, and the IdRes of the name of this shortcut group.
+     */
+    open val shortcuts: CompatV24.ShortcutGroup? = null
 }
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
index 2f6c01063c..0cfe4e2734 100644
--- a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
@@ -29,6 +29,7 @@ import android.os.SystemClock
 import android.text.TextUtils
 import android.util.TypedValue
 import android.view.KeyEvent
+import android.view.KeyboardShortcutGroup
 import android.view.LayoutInflater
 import android.view.Menu
 import android.view.MenuItem
@@ -635,6 +636,16 @@ open class CardBrowser :
         viewModel.setDeckId(deckId)
     }
 
+    override fun onProvideKeyboardShortcuts(
+        data: MutableList<KeyboardShortcutGroup>,
+        menu: Menu?,
+        deviceId: Int
+    ) {
+        val shortcutGroups = CompatHelper.compat.getShortcuts(this)
+        data.addAll(shortcutGroups)
+        super.onProvideKeyboardShortcuts(data, menu, deviceId)
+    }
+
     override fun onKeyUp(keyCode: Int, event: KeyEvent): Boolean {
         // This method is called even when the user is typing in the search text field.
         // So we must ensure that all shortcuts uses a modifier.
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
index 9464bc7729..37c25daa9e 100644
--- a/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
@@ -27,6 +27,7 @@ import android.text.Editable
 import android.text.TextWatcher
 import android.view.ActionMode
 import android.view.KeyEvent
+import android.view.KeyboardShortcutGroup
 import android.view.LayoutInflater
 import android.view.Menu
 import android.view.MenuInflater
@@ -325,6 +326,16 @@ open class CardTemplateEditor : AnkiActivity(), DeckSelectionListener {
         invalidateOptionsMenu()
     }
 
+    override fun onProvideKeyboardShortcuts(
+        data: MutableList<KeyboardShortcutGroup>,
+        menu: Menu?,
+        deviceId: Int
+    ) {
+        val shortcutGroups = CompatHelper.compat.getShortcuts(this)
+        data.addAll(shortcutGroups)
+        super.onProvideKeyboardShortcuts(data, menu, deviceId)
+    }
+
     override fun onKeyUp(keyCode: Int, event: KeyEvent): Boolean {
         val currentFragment = currentFragment ?: return super.onKeyUp(keyCode, event)
         if (event.isCtrlPressed) {
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
index c25e4b5675..a2933bb1a1 100644
--- a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
@@ -40,6 +40,7 @@ import android.os.Bundle
 import android.os.Message
 import android.util.TypedValue
 import android.view.KeyEvent
+import android.view.KeyboardShortcutGroup
 import android.view.Menu
 import android.view.MenuItem
 import android.view.View
@@ -1267,6 +1268,16 @@ open class DeckPicker :
         }
     }
 
+    override fun onProvideKeyboardShortcuts(
+        data: MutableList<KeyboardShortcutGroup>,
+        menu: Menu?,
+        deviceId: Int
+    ) {
+        val shortcutGroups = CompatHelper.compat.getShortcuts(this)
+        data.addAll(shortcutGroups)
+        super.onProvideKeyboardShortcuts(data, menu, deviceId)
+    }
+
     override fun onKeyUp(keyCode: Int, event: KeyEvent): Boolean {
         if (toolbarSearchView?.hasFocus() == true) {
             Timber.d("Skipping keypress: search action bar is focused")
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
index 587fac98c1..70609d9a99 100644
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
@@ -36,6 +36,7 @@ import android.text.Editable
 import android.text.TextWatcher
 import android.view.ActionMode
 import android.view.KeyEvent
+import android.view.KeyboardShortcutGroup
 import android.view.Menu
 import android.view.MenuInflater
 import android.view.MenuItem
@@ -138,7 +139,6 @@ import com.ichi2.compat.CompatHelper.Companion.getSerializableCompat
 import com.ichi2.compat.CompatHelper.Companion.registerReceiverCompat
 import com.ichi2.compat.CompatV24
 import com.ichi2.compat.CompatV24.Shortcut
-import com.ichi2.compat.ShortcutGroupProvider
 import com.ichi2.libanki.Card
 import com.ichi2.libanki.Collection
 import com.ichi2.libanki.Consts
@@ -198,15 +198,7 @@ import androidx.appcompat.widget.Toolbar as MainToolbar
  */
 @KotlinClean [...]

2024-08-30 20:38 UTC, Arthur-Milchior commented
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt:486: Information: Calling this method indicates use of dynamic shortcuts, but there are no calls to methods that track shortcut usage, such as pushDynamicShortcut or reportShortcutUsed. Calling these methods is recommended, as they track shortcut usage and allow launchers to adjust which shortcuts appear based on activation history. Please see https://developer.android.com/develop/ui/views/launch/shortcuts/managing-shortcuts#track-usage [ReportShortcutUsage]
>             ShortcutManagerCompat.addDynamicShortcuts(
>             ^
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/02-strings.xml:407: Error: Duplicate string value "Deck Picker", used in deck_picker_group, deck_picker_widget_description [DuplicateCrowdInStrings from com.ichi2.anki:lint-rules]
>     <string name="deck_picker_group" comment="Label for the group of shortcuts related to the deck picker">Deck Picker</string>

The second one must be corrected. It's a strange interaction with @SanjaySargam 's widget which introduced the same string.

I think it's best practice to use two distinct string as it's not clear to me that we can reuse the same string in all language.

The first one, I'm not usre it need to be dealt with

2024-08-31 05:51 UTC, SanjaySargam commented
@Arthur-Milchior 
```kotlin
    <string name="deck_picker_widget_description">Deck Picker Widget</string>
``` 
OK?

2024-08-31 20:37 UTC, Arthur-Milchior commented
No. It's clear in the context that it's a widget. No need to state it.
My point was really that it would be useful to add a `comment="Title of the Deck Picker Widget. Displayed to the user in Android's Widget Selection menu"`

2024-09-16 12:37 UTC, mikehardy commented
@Arthur-Milchior this appears to have a high frequency of conflicts, and also requires strings
Is it ready to go now or not?

2024-09-21 19:35 UTC, Arthur-Milchior reviewed
@mikehardy It was not mergeable. If you tried to type an upper case in the note editor, you'd get a toast telling you to use alt+k to see the list of shortcut.

I added two commits on top of it, with my suggestion of change, I hope we save time.

This refactor some code to avoid duplication. And avoid add an extra interface that does not seems very useful to me.
Plus, I ensure that "shift" does not trigger the "show shortcut list" toast

2024-09-21 19:35 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/compat/StringResource.kt
> +sealed interface StringResource {
I'm not a huge fan of this interface. 
Either we expect to have similar need into the future, in which case I believe it should also accept strings with parameters and be fully general.
Or we expect it to be only for Shortcut, in which case
```
/**
 * Provides a [CompatV24.Shortcut], from the shortcut keys and the resource id of its description.
 */
fun AnkiActivityProvider.shortcut(shortcut: String, @StringRes labelRes: Int) =
    CompatV24.Shortcut(shortcut, ankiActivity.getString(labelRes))

/**
 * Provides a [CompatV24.Shortcut], from the shortcut keys and the function from anki strings.
 */
fun shortcut(shortcut: String, getTranslation: Translations.() -> String) =
    CompatV24.Shortcut(shortcut, getTranslation(TR))
```

is largely sufficient.

With 
```
interface AnkiActivityProvider {
    val ankiActivity: AnkiActivity
}
```

2024-09-21 21:24 UTC, Arthur-Milchior approved these changes
@david-allison there was quite some changes since you reviewed. Including one that corrected a real bug. So I'd appreciate if you could re-review before we merge

2024-10-03 17:55 UTC, Arthur-Milchior commented
I'm quite sorry @SanjaySargam it tooks more conflict. Can you solve them?

2024-10-04 05:19 UTC, david-allison requested changes

2024-10-04 05:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        if (!done && shortcuts != null && (event.isCtrlPressed || event.isAltPressed) && (keyCode in KeyEvent.KEYCODE_A..KeyEvent.KEYCODE_Z) || (keyCode in KeyEvent.KEYCODE_NUMPAD_0..KeyEvent.KEYCODE
What about meta?

2024-10-04 05:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                    CompatHelper.compat.showKeyboardShortcutsDialog(this)
Add a Log

2024-10-04 05:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
>          }
Revert

2024-10-04 05:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
> +        if (shortcutsGroup.size <= 1) return
Add a comment: why does this return if there's 1

2024-10-04 05:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
> +            return when (modifier) {
Meta?

2024-10-04 05:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
> +                else -> KeyEvent.keyCodeFromString(key)
What does this do if invalid? Document it

2024-10-04 05:19 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="edit_answer" comment="Description of the shortcut that shows the answer side of the card template">Edit the answer</string>
"Edit answer"?

2024-10-04 05:19 UTC, david-allison commented on AnkiDroid/src/main/res/values/02-strings.xml
> +
Remove "the"

2024-10-05 06:23 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
>          }
what should I revert?

2024-10-05 06:32 UTC, SanjaySargam commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
> +            return when (modifier) {
Meta key is not used anywhere in shortcuts

2024-10-05 10:58 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
>          }
There was an unnecessary spacing change

2024-10-05 16:31 UTC, david-allison approved these changes
Thanks so much!

Needs strings sync

2024-10-05 19:54 UTC, david-allison commented
Synced, but needs a squash (then probably another sync)

2024-10-06 03:41 UTC, david-allison commented
I've squashed the commit and fixed a couple of 'additional newline' nitpicks which weren't addressed

2024-10-06 04:05 UTC, merged