fix: limit parameter of schedule URI returns the same data
ankidroid/Anki-Android pull request #16915
Opened 2024-08-20 16:05 UTC by warleysr

## Purpose / Description
I had some trouble integrating the AnkiDroid API in my app, mainly because some confusion on my part with the `CONTENT_URI` of `ReviewInfo` which `deckID` and `limit` aren't query parameters, not following the pattern of the others availables URIs. 

So I created the another URI to use the deck id as an appended path and passing limit as an optional query parameter, e.g. `/schedule/123456789?limit=5` leaving the existing one to not break any app that already uses it.

Also I found out that the `limit` parameter doesn't work in the existing schedule URI, returning the same card data N times and fixed this in this PR.

## Fixes
* Fixes #16772

## Approach
Creation of new URI in `CardContentProvider` and creation of `getQueuedCards()` function to solve the limit parameter issue.

## How Has This Been Tested?

Querying the `FlashCardsContract.ReviewInfo.CONTENT_URI` with appended path (new URI) and using selection arguments as the example provided in this file. The minimum working example I provided in the issue might help.

Used an Android 12 device.
 
## Learning (optional, can help others)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-08-21 00:17 UTC, mikehardy requested changes
Hi there! 👋 

Always nice to see someone using the API - not too many consumers of it by count-of-apps but the apps that do can be quite popular. And PRs coming from API consumers are usually pretty great despite never seeing the authors before 😄  - like this one

I left a couple comments that in my mind are trivial. This works for me and I appreciate the care to be backwards compatible, that certainly helps with the decision to integrate or not

2024-08-21 00:17 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
> +    fun getQueuedCards(limit: Int): List<Card> {
Hmm 🤔  - historically `libanki` is really only for things that are (or were) in the anki python library, there is a high bar to locating code here

Since this appears to be the only consumer of the limit-based query, could this code be inlined at the call site?

2024-08-21 00:17 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +                val deckId = uri.lastPathSegment!!.toLong()
it appears that `rv` may be returned as a "short circuit" / "things didn't work" return value based on code below

Could we avoid the `!!` (which worries me every time I see it, no matter how improbable it is that it fail) and return rv if uri.lastPathSegment was for whatever reason null?

2024-08-21 00:17 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +    private fun fetchReviewInfo(col: Collection, limit: Int, rv: MatrixCursor, columns: Array<String>) {
Note to maintainers: I see `fetchReviewInfo` used in a previous commit, so this needs a squash-merge. Not a big deal, just noting it

2024-08-21 00:19 UTC, mikehardy commented
Curious if your git commit hook didn't run? Looks like the ktlint autoformatter would fix this, and should fix it when you attempt to commit? Just a trivial spacing issue is stopping lint from passing:

```

> Task :AnkiDroid:ktlintMainSourceSetCheck FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt:692:1 Unexpected blank line(s) before "}"
```

2024-08-21 00:23 UTC, mikehardy commented
I see you and David have interacted a fair bit on the linked issue so I'm flagging him for review as well. I'm happy to be overruled on any of my review comments if David has other ideas

2024-08-21 02:08 UTC, mikehardy approved these changes
simply incorporates all my suggestions so of course I'm +1 but as mentioned I remain open to override by anything David thinks since you two interacted already

Fantastic, IMHO though. Cheers

2024-08-21 10:26 UTC, david-allison requested changes
Code is really high quality! Thanks so much.

Please bear in mind that this code was written before my time and I've had limited interactions with it.

That being said: it's our public API, so I'm being much more nitpicky than normal

----

Could you add test(s) to `ContentProviderTest`:

https://github.com/ankidroid/Anki-Android/blob/06e8ac2ef3e0d35fb3efc59aabb38c796b276b04/AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt#L74

----

## API Design

TL;DR: I don't think we should include the new endpoint

We are already somewhat unusual in our `ContentProvider` design

* `limit` should be a selection parameter, not a query parameter, justification in a comment below

---

I'm a mild oppose to adding the new endpoint on grounds of consistency (I'm undecided here)

* Our current endpoints are 'list/detail':
    * `decks/` lists all decks
    * `decks/1` lists a deck
    * `notes/` lists all notes
    *  `notes/1` lists a note

The parameter changes the semantics of the request.

We don't have this list/detail distinction with `schedule`. 

`/schedule` lists the schedule for the currently selected deck
`/schedule/1` lists the schedule for deck `X`

`DeckId` doesn't change the semantics of the request here, so should be a selection argument.

2024-08-21 10:26 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +                val limit = uri.getQueryParameter("limit")?.toInt() ?: 1
(disclaimer: I haven't done much API work)

As far as I understand it, query parameters (after the `?`) are not expected within Content Provider URIs.

I suspect this was due to URL length limits, and has been de-facto standardized as such

https://developer.android.com/guide/topics/providers/content-provider-basics#ContentURIs

The documentation does not comment on, or use parameters. It feels that `selection` should be used for filtering, as we currently do in `NOTES` and `NOTES_V2`.

----

Inconsistency: our `bulkInsert` method does a query parameter, I believe this inconsistency is because Android's `bulkInsert` does not expose alternate arguments.

2024-08-21 15:34 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +                val limit = uri.getQueryParameter("limit")?.toInt() ?: 1
Okay, sot hat's the criticism, and that seems well-reasoned. So the concrete proposal is:

- maintain current endpoint of /schedule ?
- add selection criteria of deck
- add selection criteria of limit (this is subtle now, since Android 11 and changed ContentProvider limit behavior)

So the underlying code would move the new logic into the schedule endpoint, and see what selection criteria were given - if deckid was not given, execute the old code to get data, if deckid was given execute the new code here

And then (the fancier bit...) if android O+ see if limit was sent in the bundle, if < O see if limit was sent in selection query as well and if so get it from query args. Either way if a limit was sent in, restrict results to limit ? (https://stackoverflow.com/a/63551176/9910298)

2024-08-21 15:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +                val limit = uri.getQueryParameter("limit")?.toInt() ?: 1
I don't believe the linked SO post is necessary - we're in control of the provider (as the server, rather than the client) and can handle a limit provided from a client so we just serve that amount of data

----

Steps would be:

* Test `/schedule` with DeckId/limit (with bug fixed) 
* Merge

2024-08-21 17:48 UTC, warleysr commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +                val limit = uri.getQueryParameter("limit")?.toInt() ?: 1
> Inconsistency: our `bulkInsert` method does a query parameter, I believe this inconsistency is because Android's `bulkInsert` does not expose alternate arguments.

I agree with this, query parameters aren't really used in any other endpoint, but following the other endpoints that I mentioned, the correct standardization would be `/schedule/<deckID>/<limit>` ?

2024-08-22 09:18 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +                val limit = uri.getQueryParameter("limit")?.toInt() ?: 1
> Many providers let you access a single row in a table by appending an ID value to the end of the URI. For example, to retrieve a row whose _ID is 4 from the User Dictionary Provider, you can use this content URI:

https://developer.android.com/guide/topics/providers/content-provider-basics#ContentURIs

This is what we're doing with other endpoints

As above, this changes the meaning of the endpoint from "many" to "one", and therefore makes sense to be included in the URL

----

`ContentProvider` expects `selection` (/`sectionArgs`) to be used for selections, and we should follow this standardization to the best of our ability

`/schedule/<deckID>/<limit>` is:

* ambiguous (no expectation of what the second parameter could be. `deckId` is arguably the primary parameter for `schedule`, but it's not as obvious as `notes/1` referring to the note with ID 1)
* unmaintainable: the URL endpoint gets more complex for each parameter added
* unmaintainable: over time, we will reach the limit of a URL

It does not follow the standardization of the other endpoints: neither of the parameters change the shape/semantics of the call/results

2024-08-22 13:00 UTC, david-allison approved these changes
Great stuff, cheers!

If you write a quick comment detailing where our documentation is lacking regarding the parameters, I'll put it up as a documentation issue

2024-08-22 13:41 UTC, merged