Implement the desktop UI in StudyOptionsFragment
ankidroid/Anki-Android pull request #16947
Opened 2024-08-24 08:27 UTC by lukstbit

## Purpose / Description

While working towards fixing #14793 I got sidetracked and implemented this so StudyOptionsFragment follows the desktop ui + it shows the bury counts(which weren't being shown) if the related deck options are enabled.

Some notes on the changes:
- the previous code showed the total cards count in the deck. As the desktop screen didn't show this I removed it. Can be brought back with ease if requested using the cardCount() method which was just added to out codebase.
- the previous code showed the total new cards count in the deck. As the desktop screen didn't show this I removed it. This can also be brought back for normal decks, however the related backend method doesn't work for filtered decks so we would need to either don't show this count for filtered decks or use the old code(which I'm actively trying to purge).
- the description was kept at the bottom, as it could be quite long there's no need to have it at the top to push the important count numbers below.
- bury counts colors are taken from the anki codebase

Some images:

_Current screen_ vs. _Changed screen + bury count + bury notice label_
<img src="https://github.com/user-attachments/assets/332b0bd8-64fb-43a1-b8ac-bdd4719c9858" width="380px" height="720px"/><img src="https://github.com/user-attachments/assets/a8b897f3-4f1a-4dda-b392-299a36ac2f14" width="380px" height="720px"/>

Desktop ui:
![Screenshot from 2024-08-24 10-42-01](https://github.com/user-attachments/assets/6b2d1f2b-35c2-4429-b067-f0b58b2a7069)

## How Has This Been Tested?

Saw if the buried counts appear + ran the tests. Personally I don't use the option to bury so it would be great if someone actively using buried cards tests this.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-08-24 11:14 UTC, david-allison commented
Pre-review: 

Can we make the bury count tappable? One of the common complaints for Anki Desktop is that people don't know what this is

2024-08-24 14:22 UTC, BrayanDSO commented
> Can we make the bury count tappable and provide a quick explanation?

or write `+ 1 buried` so it's clear. 

Maybe put in a new line like `New` and `Learning`, so it's something like `Buried: 1`

If someone says "bUt tHis isn't cOnsistEnt with AnKi", we don't have to be as unintuitive as Anki in some cases.

2024-08-24 14:40 UTC, david-allison requested changes
One request for libAnki compatibility, the rest are nitpicks: take it or leave it

This is an 'approve' after: I'd push to for a quick solution on 'bury counts' since they're so unintuitive, but it's not a blocker to merging. Things are better now

Thank you!

2024-08-24 14:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +            newBuryText.visibility = if (result.buriedNew == 0) View.GONE else View.VISIBLE
`isVisibile` would be better

2024-08-24 14:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +            reviewBuryText.text = "+${result.buriedReview}"
I suspect Anki Desktop doesn't use a format string here, but flagging it for a quick check

2024-08-24 14:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
> +    }
LGTM:

https://github.com/ankitects/anki/blob/a179da382759b9c7f8265faf37efdcbb47d8ee08/pylib/anki/decks.py#L188-L198

```python
    @classmethod
    def find_deck_in_tree(
        cls, node: DeckTreeNode, deck_id: DeckId
    ) -> DeckTreeNode | None:
        if node.deck_id == deck_id:
            return node
        for child in node.children:
            match = cls.find_deck_in_tree(child, deck_id)
            if match:
                return match
        return None
```

2024-08-24 14:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
> +    fun deckDueTree(deckId: DeckId? = null): DeckTreeNode? {
Parameter should be `topDeckId`

2024-08-24 14:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
> +    fun deckDueTree(deckId: DeckId? = null): DeckTreeNode? {
https://github.com/ankitects/anki/blob/a179da382759b9c7f8265faf37efdcbb47d8ee08/pylib/anki/scheduler/base.py#L75-L81

```python
    def deck_due_tree(self, top_deck_id: DeckId | None = None) -> DeckTreeNode | None:
        """Returns a tree of decks with counts.
        If top_deck_id provided, only the according subtree is returned."""
        tree = self.col._backend.deck_tree(now=int_time())
        if top_deck_id:
            return self.col.decks.find_deck_in_tree(tree, top_deck_id)
        return tree
```

2024-08-24 14:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +            newBuryText.visibility = if (result.buriedNew == 0) View.GONE else View.VISIBLE
https://android.github.io/android-ktx/core-ktx/androidx.view/android.view.-view/is-visible.html

2024-08-24 15:28 UTC, doozan commented
I use this screen regularly as a fast way to see how many new cards remain in a desk to estimate when I will finally complete the deck. For me, it's motivational to watch the numbers go down and I would be sad to lose that unless there's another easy way to see new/total count without having to mess with the deck browser.

2024-08-25 06:20 UTC, brishtibheja commented
There is already a Card Count pie chart in the statistics screen. The counts here don't need to show total new cards in deck, it's confusing to have the same data cluttered in different parts of UI.

2024-08-25 08:13 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +            newBuryText.visibility = if (result.buriedNew == 0) View.GONE else View.VISIBLE
It is much better, thanks!

2024-08-25 08:14 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +            reviewBuryText.text = "+${result.buriedReview}"
I don't know rust but I don't think so from my reading of the code. Because I went with Brayan's recommendation I switched to using a format string.

2024-08-25 08:23 UTC, lukstbit commented
> Can we make the bury count tappable and provide a quick explanation?

The desktop app uses the text I show when there any buried count displayed(see the image under the deck's name) as a tooltip on hover over the buried counts. I tried adding it as a tooltip as well but android limits the text in a tooltip to a max of 3 short rows so it gets cut(and it wouldn't really work with some of the longer languages out there). I tried using a PopupWindow as well but it was difficult to make it work properly so I avoided this.

Instead I went with my additional text from the desktop app + adding the word _buried_(see the image with the changes). I think this is enough especially as these counts are shown when the user specifically changes some default settings. I also added a _TODO_ just as a remainder.

@doozan I think these counts can be seen in the statistics. Not in one tap like the old code but still available to be enjoyed.

2024-08-26 09:53 UTC, david-allison approved these changes
Looks great, cheers!

2024-08-26 21:22 UTC, BrayanDSO approved these changes

2024-08-27 14:52 UTC, merged