Notify the UI that a sync was done
ankidroid/Anki-Android pull request #16958
Opened 2024-08-26 02:12 UTC by Arthur-Milchior

In this case, I really don't think it's realistic to expect an OpChange from the backend. The backend already sends informations that are relevant for the sync process. Given that "sync" does not uses the processes uses for undoable change (indeed, it should not be undoable), no OpChange is generated.

It seems reasonable in this place at least to directly notify the observers.

Given that the observers expect an OpChanges, I create one, and simply assume everything may be changed. This seems reasonable in case of sync, and it's sufficiently rare that the cost won't be prohibitive anyway.

Fixed: #16943
Fixed: #16942

2024-08-26 08:56 UTC, david-allison requested changes
Use the Kotlin DSL, it's easier to read:

```kotlin
        val changes = opChanges {
            card = true
            note = true
            tag = true
            notetype = true
            config = true
            deckConfig = true
            mtime = true
            browserTable = true
            browserSidebar = true
            noteText = true
            studyQueues = true
        }
```

----

Extract this into `ChangeManager.notifyAllChanged(caller)` or similar

Since the built class is immutable, you could have `ChangeManager.allChanges` inside a `companion object`

----

Add a unit test so an upgrade of the backend to add another property would be caught

----

`this` is a `CoroutineScope`

1. Passing in a `CoroutineScope` should probably be a warning/error
2. `this` should be a `DeckPicker`

2024-08-26 14:38 UTC, Arthur-Milchior commented
I admit I have no idea right now how to do such a test. I'd love it. Checking whether the number of field changed, probably. Or if a field value is unset. 

I'd appreciate if yo ucould do that, as I don't see how to do it

2024-08-26 17:57 UTC, david-allison commented
Glad I asked:

```
deck_
Expected: <true>
     but: was <false>
java.lang.AssertionError: deck_
Expected: <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at com.ichi2.libanki.ChangeManagerTest.aa(ChangeManagerTest.kt:41)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.robolectric.internal.TimeLimitedStatement.evaluate(TimeLimitedStatement.java:38)
```

```patch
Subject: [PATCH] docs: dependencies - changelogs (Triple-T Publisher)
---
Index: AnkiDroid/src/main/java/com/ichi2/libanki/ChangeManager.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/libanki/ChangeManager.kt b/AnkiDroid/src/main/java/com/ichi2/libanki/ChangeManager.kt
--- a/AnkiDroid/src/main/java/com/ichi2/libanki/ChangeManager.kt	(revision 2aa20401738d695c3a805566a70cc43f8f9bef8c)
+++ b/AnkiDroid/src/main/java/com/ichi2/libanki/ChangeManager.kt	(date 1724694593526)
@@ -33,6 +33,7 @@
 import anki.collection.OpChangesOnly
 import anki.collection.OpChangesWithCount
 import anki.collection.OpChangesWithId
+import anki.collection.opChanges
 import anki.import_export.ImportResponse
 import com.ichi2.anki.CollectionManager.withCol
 import com.ichi2.anki.CrashReportService
@@ -103,6 +104,21 @@
         }
         notifySubscribers(opChanges, initiator)
     }
+
+    internal val ALL = opChanges {
+        card = true
+        note = true
+        deck = true
+        tag = true
+        notetype = true
+        config = true
+        deckConfig = true
+        mtime = true
+        browserTable = true
+        browserSidebar = true
+        noteText = true
+        studyQueues = true
+    }
 }
 
 /** Wrap a routine that returns OpChanges* or similar undo info with this
Index: AnkiDroid/src/test/java/com/ichi2/libanki/ChangeManagerTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/libanki/ChangeManagerTest.kt b/AnkiDroid/src/test/java/com/ichi2/libanki/ChangeManagerTest.kt
new file mode 100644
--- /dev/null	(date 1724695014350)
+++ b/AnkiDroid/src/test/java/com/ichi2/libanki/ChangeManagerTest.kt	(date 1724695014350)
@@ -0,0 +1,65 @@
+/*
+ Copyright (c) 2024 David Allison <davidallisongithub@gmail.com>
+
+ This program is free software; you can redistribute it and/or modify it under
+ the terms of the GNU General Public License as published by the Free Software
+ Foundation; either version 3 of the License, or (at your option) any later
+ version.
+
+ This program is distributed in the hope that it will be useful, but WITHOUT ANY
+ WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
+ PARTICULAR PURPOSE. See the GNU General Public License for more details.
+
+ You should have received a copy of the GNU General Public License along with
+ this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+package com.ichi2.libanki
+
+import anki.collection.OpChanges
+import com.ichi2.testutils.JvmTest
+import org.hamcrest.MatcherAssert.assertThat
+import org.hamcrest.Matchers.equalTo
+import org.hamcrest.Matchers.greaterThan
+import org.junit.Test
+import org.junit.runner.RunWith
+import org.junit.runners.Parameterized
+import kotlin.collections.Collection
+import kotlin.reflect.KProperty1
+import kotlin.reflect.full.memberProperties
+import kotlin.reflect.javaType
+import kotlin.reflect.jvm.isAccessible
+
+@RunWith(Parameterized::class)
+class ChangeManagerTest : JvmTest() {
+
+
+    @JvmField // required for Parameter
+    @Parameterized.Parameter
+    var property: KProperty1<OpChanges, *>? = null
+
+    @JvmField // required for Parameter
+    @Parameterized.Parameter(1)
+    var name: String? = null
+
+    @Test
+    fun `Property is set in ALL object`() {
+        assertThat(name, property!!.call(ChangeManager.ALL), equalTo(true))
+    }
+
+    companion object {
+        @Parameterized.Parameters(name = "{1}")
+        @OptIn(ExperimentalStdlibApi::class)
+        @JvmStatic // required for initParameters
+        fun initParameters(): Collection<Array<out Any>> {
+            val props =
+                OpChanges::class.memberProperties.filter { it.returnType.javaType == Boolean::class.java }
+            assertThat(props.size, greaterThan(0))
+
+            props.forEach { it.isAccessible = true }
+            return props.map {
+                arrayOf(it, it.name)
+            }
+
+        }
+    }
+}
\ No newline at end of file
```

2024-08-27 00:56 UTC, Arthur-Milchior commented
Thanks. i didn't know how to use the reflection this way. Interesting

2024-08-27 07:17 UTC, david-allison approved these changes
Looks great, thanks for the fast turnaround!

2024-08-28 23:59 UTC, Arthur-Milchior commented
Merge conflict of imports resolved

2024-09-03 04:59 UTC, lukstbit approved these changes
LGTM

2024-09-03 05:11 UTC, merged