[GSoC'24] Card Analysis Extra Widget .
ankidroid/Anki-Android pull request #16982
Opened 2024-08-27 22:45 UTC by xenonnn4w

## Purpose / Description
This commit introduces the Card Analysis Widget, which displays a deck name along with the number of cards that are new, in learning, and due for review. 

## Approach
On the same pattern as Deck Picker Widget.

## How Has This Been Tested?
![image](https://github.com/user-attachments/assets/159029c4-9740-4465-b2e4-d234d3a47589)

https://github.com/user-attachments/assets/38e138d2-6c34-42a2-a675-85f18e683be7

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-08-27 23:00 UTC, david-allison requested changes
Main point would be to remove most references to `deckIds`. This widget operates on one ID

2024-08-27 23:00 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisExtraWidgetConfig.kt
> +        if (deckAdapter.itemCount > 0) {
use `isVisible`

2024-08-27 23:07 UTC, xenonnn4w commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="card_analysis_extra_widget_description">Card Analysis Extra</string>
That's from the documentation of gsoc proposal i.e. https://docs.google.com/document/d/1VLYzRhUfZdcgRViFrj_w5ASLvzz448aISbgRCdpIafE/edit#bookmark=id.9xj349epoxcx

2024-08-28 09:24 UTC, david-allison commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="card_analysis_extra_widget_description">Card Analysis Extra</string>
I don't understand the relevance

2024-08-28 21:09 UTC, xenonnn4w commented on AnkiDroid/src/test/java/com/ichi2/anki/widget/cardanalysis/CardAnalysisExtraWidgetConfigTest.kt
> +        lifecycle.handleLifecycleEvent(Lifecycle.Event.ON_CREATE)
oh i see, manual management of LifecycleRegistry is unnecessary.

2024-08-30 02:07 UTC, Arthur-Milchior commented
I get a "You may only select one deck" after selecting the only deck.
I'd prefer if you could open the deck selector as soon as configuration is opened. There is really no reason to have the use press "+". Similarly, once the selection is done, you can directly save it. In the worst case, if the user want to change the deck they can reconfigure it

2024-08-30 02:14 UTC, Arthur-Milchior commented
If the deck is deleted, I'd prefer if you could either delete the widget alltogether if it's possible (@david-allison  do you agree?) or at least show a message stating something such as "Missing deck. Please reconfigure" and tapping on the widget would open the configuration view instead of opening ankidroid

2024-08-30 02:29 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/WidgetConstants.kt
> +    const val ACTION_APPWIDGET_UPDATE = AppWidgetManager.ACTION_APPWIDGET_UPDATE
Why don't you directly use `AppWidgetManager.ACTION_APPWIDGET_UPDATE` where you use the value you're defining ? This object does not seems to have any advantage over it as far as I can tell

2024-08-30 02:29 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidget.kt
> +        Timber.d("Performing widget update for appWidgetIds: ${appWidgetIds.joinToString(", ")}")
`Timber.d("Performing widget update for appWidgetIds: %s", appWidgetIds)`
I'm sorry, I should have noticed it sooner. Or ideally we should have a lint here.

It's bad practice to use string formatting in Timber. 
The reason is that this force the string to always be computed, even if we don't use it.
If you use the code I provided, if `Timber.d` is defined as doing nothing (because we are not running a debug version and disabled debug log), the string won't have to be computed, saving resources.

Admittedly, the cost of computing this string is very low. There is probably not a lot of widgets. Still, it's good practice so that we don't have to even consider when it's acceptable or not

2024-08-30 02:29 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/WidgetPreferences.kt
> +    fun saveSelectedDecksDeckPickerWidget(appWidgetId: Int, selectedDecks: List<String>) {
I don't understand the point of renaming this.
If this class is not deck picker specific, it should not be in `deckpicker` folder.
If it's deckpicker specific, maybe we can rename the class to `DeckPickerWidgetPreferences` and this way we don't have to repeat `deckPicker` in the function name

2024-08-30 02:29 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidgetConfig.kt
> +    private suspend fun isDefaultDeckEmpty(): Boolean {
Please don't copy paste code.
If we really need it, maybe put it in `DeckUtils`, and use it in both classes

2024-08-30 02:29 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/08-widget.xml
>      <string name="no_selected_deck_placeholder_title" comment="Placeholder title when no decks are selected">Select decks to display in the widget. Select decks with the + icon.</string>
We should not use this string in the new widget. As it mentions "decks" with plural. And right now we only allow a single deck.

Anyway, as I wrote in the PR, I think we should not even ask the user to click + and save, given that, the only action they can do is select a deck. So there is no need for text here

2024-08-30 06:29 UTC, david-allison commented
Deleting the widget: it doesn't seem wise. Renaming a deck would count as a deletion, whereas the user would expect a reconfiguration

2024-08-30 11:34 UTC, Arthur-Milchior commented
I'm fine with not deleting it. But at least, we should not leave it empty

2024-08-30 21:59 UTC, Arthur-Milchior commented
I'm happy, and to be frank, pleasantly surprised, you were able to update so quickly.

A few requests:
* you shouldn't be able to close the list of decks except by selecting a deck. Closing the list, e.g. with "esc" should close the whole configuration. 
* Remove the + symbol. It won't be used.
* If the collection is empty, there are no card at all, instead of "missing deck", reuse the "not initialized" string. And don't open the configuration, as it close automatically.

2024-08-30 22:27 UTC, Arthur-Milchior commented
To save you time, here are the typing change I created while reviewing and testing your code

```patch
Subject: [PATCH] Notify the UI that a sync was done

In this case, I really don't think it's realistic to expect an
OpChange from the backend. The backend already sends informations that
are relevant for the sync process. Given that "sync" does not uses the
processes uses for undoable change (indeed, it should not be
undoable), no OpChange is generated.

It seems reasonable in this place at least to directly notify the
observers.

Given that the observers expect an OpChanges, I create one, and simply
assume everything may be changed. This seems reasonable in case of
sync, and it's sufficiently rare that the cost won't be prohibitive
anyway.

Fixed: #16943
Fixed: #16942
---
Index: AnkiDroid/src/test/java/com/ichi2/anki/widget/deckpicker/DeckNameAndStatsTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/widget/deckpicker/DeckNameAndStatsTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/widget/deckpicker/DeckNameAndStatsTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/widget/deckpicker/DeckNameAndStatsTest.kt	(revision a4a4c1bba2a4efeb201212bc201724b9d7ac6c8d)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/widget/deckpicker/DeckNameAndStatsTest.kt	(date 1725056072761)
@@ -18,7 +18,7 @@
 
 import androidx.test.ext.junit.runners.AndroidJUnit4
 import com.ichi2.anki.RobolectricTest
-import com.ichi2.widget.deckpicker.getDeckNameAndStats
+import com.ichi2.widget.deckpicker.getDeckNamesAndStats
 import org.junit.Test
 import org.junit.runner.RunWith
 import kotlin.test.assertEquals
@@ -32,7 +32,7 @@
         val deck2Id = addDeck("Deck 2")
         val deckIds = listOf(deck1Id, deck2Id)
 
-        val result = getDeckNameAndStats(deckIds)
+        val result = getDeckNamesAndStats(deckIds)
 
         assertEquals(2, result.size)
         assertEquals("Deck 1", result[0].name)
@@ -48,7 +48,7 @@
         val deckCId = addDeck("Deck C")
         val deckIds = listOf(deckCId, deckAId, deckBId)
 
-        val result = getDeckNameAndStats(deckIds)
+        val result = getDeckNamesAndStats(deckIds)
 
         assertEquals(3, result.size)
         assertEquals("Deck C", result[0].name)
@@ -65,7 +65,7 @@
         val child1Id = addDeck("Deck 1::Child 1")
         val deckIds = listOf(deck1Id, child1Id)
 
-        val result = getDeckNameAndStats(deckIds)
+        val result = getDeckNamesAndStats(deckIds)
 
         assertEquals(2, result.size)
         assertEquals("Deck 1", result[0].name)
Index: AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidgetConfig.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidgetConfig.kt b/AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidgetConfig.kt
--- a/AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidgetConfig.kt	(revision a4a4c1bba2a4efeb201212bc201724b9d7ac6c8d)
+++ b/AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidgetConfig.kt	(date 1725056710433)
@@ -104,8 +104,8 @@
 
             initializeUIComponents()
             // Show the Deck selection dialog only when there are no decks selected while opening the configuration screen.
-            val selectedDeckIds = cardAnalysisWidgetPreferences.getSelectedDeckIdFromPreferences(appWidgetId)
-            if (selectedDeckIds.isEmpty()) {
+            val selectedDeckId = cardAnalysisWidgetPreferences.getSelectedDeckIdFromPreferences(appWidgetId)
+            if (selectedDeckId == null) {
                 showDeckSelectionDialog()
             }
         }
@@ -220,16 +220,14 @@
 
     /** Updates the view according to the saved preference for appWidgetId.*/
     fun updateViewWithSavedPreferences() {
-        val selectedDeckIds = cardAnalysisWidgetPreferences.getSelectedDeckIdFromPreferences(appWidgetId)
-        if (selectedDeckIds.isNotEmpty()) {
+        val selectedDeckId = cardAnalysisWidgetPreferences.getSelectedDeckIdFromPreferences(appWidgetId)?: return
             lifecycleScope.launch {
                 val decks = fetchDecks()
-                val selectedDecks = decks.filter { it.deckId in selectedDeckIds }
+                val selectedDecks = decks.filter { it.deckId == selectedDeckId }
                 selectedDecks.forEach { deckAdapter.addDeck(it) }
                 updateViewVisibility()
                 updateFabVisibility()
             }
-        }
     }
 
     /** Asynchronously displays the list of deck in the selection dialog. */
@@ -287,9 +285,9 @@
             hasUnsavedChanges = false
             setUnsavedChanges(false)
 
-            val selectedDeckIds = cardAnalysisWidgetPreferences.getSelectedDeckIdFromPreferences(appWidgetId)
+            val selectedDeckId = cardAnalysisWidgetPreferences.getSelectedDeckIdFromPreferences(appWidgetId)
             val appWidgetManager = AppWidgetManager.getInstance(this)
-            CardAnalysisWidget.updateWidget(this, appWidgetManager, appWidgetId, selectedDeckIds)
+            CardAnalysisWidget.updateWidget(this, appWidgetManager, appWidgetId, selectedDeckId)
 
             val resultValue = Intent().putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID, appWidgetId)
             setResult(RESULT_OK, resultValue)
@@ -310,14 +308,14 @@
     }
 
     fun saveSelectedDecksToPreferencesCardAnalysisWidget() {
-        val selectedDecks = deckAdapter.deckIds.map { it }
-        cardAnalysisWidgetPreferences.saveSelectedDeck(appWidgetId, selectedDecks.map { it.toString() })
+        val selectedDeck = deckAdapter.deckIds.getOrNull(0)
+        cardAnalysisWidgetPreferences.saveSelectedDeck(appWidgetId, selectedDeck)
 
         val updateIntent = Intent(this, CardAnalysisWidget::class.java).apply {
             action = AppWidgetManager.ACTION_APPWIDGET_UPDATE
             putExtra(AppWidgetManager.EXTRA_APPWIDGET_IDS, intArrayOf(appWidgetId))
 
-            putExtra("card_analysis_widget_selected_deck_ids", selectedDecks.toList().toLongArray())
+            putExtra("card_analysis_widget_selected_deck_ids", selectedDeck)
         }
 
         sendBroadcast(updateIntent)
Index: AnkiDroid/src/test/java/com/ichi2/anki/widget/cardanalysis/CardAnalysisWidgetConfigTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/widget/cardanalysis/CardAnalysisWidgetConfigTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/widget/cardanalysis/CardAnalysisWidgetConfigTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/widget/cardanalysis/CardAnalysisWidgetConfigTest.kt	(revision a4a4c1bba2a4efeb201212bc201724b9d7ac6c8d)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/widget/cardanalysis/CardAnalysisWidgetConfigTest.kt	(date 1725056072761)
@@ -82,7 +82,7 @@
         activity.saveSelectedDecksToPreferencesCardAnalysisWidget()
 
         // Verify saved decks
-        val selectedDeckIds = widgetPreferences.getSelectedDeckIdFromPreferences(1).toList()
+        val selectedDeckIds = widgetPreferences.getSelectedDeckIdsFromPreferences(1).toList()
         assertThat(selectedDeckIds.contains(deck1.deckId), equalTo(true))
     }
 
@@ -96,7 +96,7 @@
     fun testLoadSavedPreferences() {
         // Save decks to preferences
         val deckIds = listOf(1L)
-        widgetPreferences.saveSelectedDeck(1, deckIds.map { it.toString() })
+        widgetPreferences.saveSelectedDecks(1, deckIds.map { it.toString() })
 
         // Load preferences
         activity.updateViewWithSavedPreferences()
Index: AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWi [...]

2024-08-31 11:03 UTC, xenonnn4w commented
>To save you time, here are the typing change I created while reviewing and testing your code

Thanks a lot for this, really helped me as my exams are around the corner.

2024-08-31 12:17 UTC, xenonnn4w commented
>you shouldn't be able to close the list of decks except by selecting a deck. Closing the list, e.g. with "esc" should close the whole configuration.
>Remove the + symbol. It won't be used.

Is it possible to implement this change in future?. Need some time for my exam. I tried but wasn't able to implement that on back press the config screen should get closed not the deck selection dialog. I did implement the alternate mechanism for now.

2024-09-01 18:00 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/widget/cardanalysis/CardAnalysisWidgetConfigTest.kt
> +    private lateinit var activity: CardAnalysisWidgetConfig
I believe this should be disposed in `tearDown`

2024-09-01 18:00 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/widget/deckpicker/DeckPickerWidgetConfigTest.kt
> +        widgetPreferences = DeckPickerWidgetPreferences(ApplicationProvider.getApplicationContext())
`targetContext`

2024-09-01 20:27 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidgetPreferences.kt
> +            putLong(getCardAnalysisExtraWidgetKey(appWidgetId), selectedDeck ?: NOT_FOUND_DECK_ID)
ah sorry, Arthur gave this addition to me in a patch mentioned above. So there a mis-match.

2024-09-01 20:43 UTC, xenonnn4w commented on AnkiDroid/src/test/java/com/ichi2/anki/widget/deckpicker/DeckPickerWidgetConfigTest.kt
> +        widgetPreferences = DeckPickerWidgetPreferences(ApplicationProvider.getApplicationContext())
can i get more about this? not able to figure out how i use that

2024-09-01 21:13 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidgetConfig.kt
> +            context?.let { cardAnalysisWidgetPreferences.deleteDeckData(appWidgetId) }
ohh, BroadcastReceiver is registered within the Activity; its unnecessary.

2024-09-01 22:03 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidget.kt
> +                    CardAnalysisWidgetPreferences(context).saveSelectedDeck(appWidgetId, null)
fixed.

2024-09-01 22:03 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidget.kt
> +                showMissingDeck(context, appWidgetManager, appWidgetId, remoteViews)
Done.

2024-09-02 12:02 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidget.kt
> +                    CardAnalysisWidgetPreferences(context).saveSelectedDeck(appWidgetId, null)
I'm asking why, it seemed to be the correct implementation, but I wanted to confirm (and add a comment if I was correct)

2024-09-02 12:31 UTC, xenonnn4w commented on AnkiDroid/src/test/java/com/ichi2/anki/widget/deckpicker/DeckPickerWidgetConfigTest.kt
> +        widgetPreferences = DeckPickerWidgetPreferences(ApplicationProvider.getApplicationContext())
Thanks.

2024-09-02 12:32 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidget.kt
> +                    CardAnalysisWidgetPreferences(context).saveSelectedDeck(appWidgetId, null)
oh, i misunderstood that. Commented the code

2024-09-02 14:44 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidget.kt
> +            ACTION_APPWIDGET_UPDATE -> {
The actions in the CardAnalysisWidget class are being handled separately from super.onReceive()

2024-09-02 15:25 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidgetPreferences.kt
> +            putLong(getCardAnalysisExtraWidgetKey(appWidgetId), selectedDeck ?: NOT_FOUND_DECK_ID)
replaced null with `NOT_FOUND_DECK_ID` at required places in 'CardAnalysisWidget.kt'

2024-09-03 16:06 UTC, Arthur-Milchior commented
@xenonnn4w after checking with David, fine for doing the configuration change in the future

2024-09-08 04:23 UTC, Arthur-Milchior approved these changes

2024-09-08 04:23 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidget.kt
> +                    action = Intent.ACTION_VIEW
Please use FLAG_ACTIVITY_CLEAR_TOP as in #17036 to ensure these is a single reviewer

2024-09-08 04:23 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="select_deck_title" comment="Title for Deck Selection Dialog">Select deck</string>
I think in English it would be "Select a deck"

2024-09-08 04:23 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidgetConfig.kt
> +
This class needs at the very least a TODO that we must not let the list of deck close itself

2024-09-08 14:22 UTC, david-allison approved these changes
Looks great, thanks so much for all the hard work in getting this over the finish line

2024-09-08 14:23 UTC, david-allison commented
* https://github.com/ankidroid/Anki-Android/actions/runs/10760675211

2024-09-08 19:00 UTC, merged