Fix incorrect key handling in some screens
ankidroid/Anki-Android pull request #16999
Opened 2024-08-29 17:28 UTC by lukstbit

## Purpose / Description

This PR fixes the linked issues + one more(edit note screen is shown on every E event) by properly following the contract of the onKeyUp method of returning true only if the event is handled there and using a modifier to not trigger on simple key events/checking the state of the search box to see if it's regular input.

In CardBrowser I introduced two new shortcuts by using the modifier that was not used in that when selection clause:

old: _T -> Show filter by tags dialog_ vs. new: _Ctrl+T: Show filter by tags dialog_

Feel free to propose other shortcuts.

@SanjaySargam I've made this PR to help seeing that you still have work on the Gsoc front.

## Fixes
* Fixes  #16955
* Fixes #16984
* Fixes #16983

## How Has This Been Tested?

I don't see the previous behavior.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-08-29 20:01 UTC, david-allison approved these changes

2024-08-30 00:11 UTC, SanjaySargam commented
@lukstbit Thank You ❤️

2024-08-30 19:35 UTC, BrayanDSO requested changes

2024-08-30 19:35 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                    Timber.i("Shift+E: Edit note")
Shift+E can be used to write capital E in the search box and this impedes that.

2024-08-31 04:54 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                    Timber.i("Shift+E: Edit note")
Didn't realize that, I've changed the code to look at the state of the searchbox. Thanks!

2024-08-31 15:25 UTC, BrayanDSO approved these changes

2024-08-31 16:01 UTC, merged