Improve the dialog's features related to BackendSyncException
ankidroid/Anki-Android pull request #17017
Opened 2024-09-04 10:30 UTC by peyman79

## Purpose / Description
After clicking the sync button, if your current time is invalid, a dialog will appear notifying you that your time settings are incorrect. This dialog now includes a "Go to Settings" button, allowing you to easily adjust your date and time to the correct settings. Additionally, the dialog displays the current time for your reference.

## Fixes
* Fixes #16978

## How Has This Been Tested?
Here is a screenshot of the result:

![Screenshot 2024-09-04 132458](https://github.com/user-attachments/assets/78a5bfb5-93d7-46a5-9b44-576a5f9cb19f)

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [X] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-09-04 10:54 UTC, user1823 commented
> Additionally, the dialog displays the current time for your reference.

Is this the server time or the device time?

2024-09-04 11:54 UTC, peyman79 commented
> > Additionally, the dialog displays the current time for your reference.
> 
> Is this the server time or the device time?

It's device time.

2024-09-04 13:28 UTC, user1823 commented
So, what about using `Current Device Time: ...` to make it clearer?

Or what about using a sentence:
Your clock is currently set to ....

2024-09-05 08:37 UTC, peyman79 commented
> Your clock is currently set to ....

Yes you're right. I changed it, It's better now.

2024-09-06 10:58 UTC, criticalAY requested changes

2024-09-06 10:58 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +fun showInvalidClockError(context: Context, msg: String, exception: Throwable, crashReport: Boolean = true) {
Imo this method name can be improved i.e. dialog not an error

2024-09-06 10:58 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +fun showInvalidClockError(context: Context, msg: String, exception: Throwable, crashReport: Boolean = true) {
When exactly are you gonna send crash report? you are setting is true by default then passing false, and this is the only place it is being used at

2024-09-06 10:58 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +        val fullMessage = "$msg\n\nYour clock is currently set to:\n$formattedTime"
Should be extract to string, why hardcoded?

2024-09-16 13:41 UTC, mikehardy requested changes
I'm not certain all "other" sync exceptions are device time related
If there are other subtypes in there, this would be helpful in some cases but harmful in others, so it needs some thought as mentioned in comment

2024-09-16 13:41 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +        val fullMessage = "$msg\n\n$invalidClockMessage\n$formattedTime"
🤔  normally I would be wary of string concatenation as it may break RTL languages, but it is on a new line so it should be okay

2024-09-16 13:41 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +                showInvalidClockDialog(this, exc.localizedMessage!!, exc)
Are you certain that the only BackendSyncException is from invalid device time?
Even if you are certain of that now are we certain that will remain true forever?
Is there some way to constrain this new dialog to present *only* when we *are* certain that it was from an invalid device time?

Perhaps a string match on exception message "your clock is not set to correct time"? But I believe this message comes through localized and may be translated to whatever we set the backend language too (which is ideally the user's selected language) which means a string search is not valid

So, a specific question for @dae then: is BackendError.Kind.SYNC_OTHER_ERROR a set of errors of different sub-types - sort of a grab bag - or is it always device time related? If it is multiple different types is there any way to differentiate with certainty whether a specific SYNC_OTHER_ERROR is device time related ?

 I trolled through and I couldn't see anything specific about BackendError.Kind.SYNC_OTHER_ERROR being constrained *only* to device time issues:

https://github.com/ankitects/anki/blob/73c97de5d022abcec0ab1fb70921c6bf813cfa28/proto/anki/backend.proto#L33

For this PR, if this is always a device time error, great. If it is not always device time but we can differentiate with certainty, then we need to only show this specific dialog when we are certain, otherwise use old code path. If there is no way to differentiate then the Dialog needs to be made much more ambiguous and say something like "if the error is device time related, you may wish to open time settings and update your time, current device time is xxxx" or similar
...that's the only reference I have really, as the ankiweb sync server code does not seem to be searchable

2024-09-27 12:53 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +                showInvalidClockDialog(this, exc.localizedMessage!!, exc)
Sorry, lost track of this one. If AD wants to be able to identify the clock message separately, it should send through a PR that moves the error out of OTHER and into a separate specific error, like we currently use to detect sync auth failures. Other is basically a catch-all for errors that we don't (currently) need to special-case in the frontend.

2024-09-27 19:10 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +                showInvalidClockDialog(this, exc.localizedMessage!!, exc)
🤔 pretty far out of my wheelhouse but after some spelunking, is that roundabouts here?

https://github.com/ankitects/anki/blob/1b7390f22d56cb566ee3aba2faff3615275c5aa4/rslib/src/backend/error.rs#L65-L72

2024-10-02 09:57 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
> +                showInvalidClockDialog(this, exc.localizedMessage!!, exc)
Yep, that maps our internal error to the limited protobuf errors we export. With a new case in the .proto file, ClockIncorrect could be mapped to it.

I had AnkiDroid notifications turned off which is why I missed this (again). I should see future pings.

2025-01-31 02:49 UTC, closed without merging