fix:[BUG] Key Labels Not Displaying in Landscape Mode
ankidroid/Anki-Android pull request #17022
Opened 2024-09-05 03:32 UTC by Prince-kushwaha

## Purpose / Description
Key Labels Not Displaying in Landscape Mode

## Fixes
* Fixes #16935 

## Approach
create an layout for landscape mode

## How Has This Been Tested?
Tested on Android Device 

## UI Screenshots
![WhatsApp Image 2024-09-05 at 9 01 33 AM](https://github.com/user-attachments/assets/d1f93f56-be7e-4bd3-8035-dc3b92c9f5d3)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-09-05 16:33 UTC, BrayanDSO requested changes
The issue can be resolved without creating a new layout, which makes the code easier to mantain, so please do that.

Also, this breaks the layout in tablets and screens large enough to properly show the dialog

2024-09-06 15:59 UTC, Prince-kushwaha commented
@BrayanDSO  incorporated feedback

2024-09-08 17:03 UTC, Prince-kushwaha commented
@Arthur-Milchior  can u please review this pr

2024-09-08 19:04 UTC, BrayanDSO commented
Please don't ping maintainers in such a hurried manner to get this reviewed. This isn't a high priority issue and we will get it whenever we can. Respect the time and availability of other people, please.

2024-09-08 19:05 UTC, BrayanDSO requested changes
Dialog broken

2024-09-10 01:14 UTC, Arthur-Milchior commented
FYI, you'd make the review faster if you could also provide screenshot for vertical, and tablet. So that it's clear it works everywhere.
And, more importantly, if you could explain why the change was required. What was broken and now works

2024-09-10 01:20 UTC, Arthur-Milchior commented
> Dialog broken

Running on the current version of the PR, the dialog seems okay to me. I admit I don't see what's broken.

The dialog is smaller. But I must admit that I don't see any problem with not having it take a lot more space.

2024-09-10 01:20 UTC, Arthur-Milchior approved these changes

2024-09-10 23:22 UTC, BrayanDSO submitted a review, later dismissed
Just to clarify what's broken: the dialog looked a certain way before in portrait mode or in big screens like tablets, and this PR breaks that look while it can easily preserve it and fix the issue at the same time. Don't break something to fix another.

2024-09-11 04:26 UTC, Prince-kushwaha commented
@BrayanDSO I tried to preserve the look of the dialog box in portrait mode but it is not possible  using  signal layout.xml that preserve portrait mode dialog look and also have responsive in landscape mode.

2024-09-11 04:27 UTC, Prince-kushwaha commented
if have any solution for that .please share it with me

2024-09-13 18:06 UTC, Prince-kushwaha commented
Hi @BrayanDSO , i fixed the dialog broken issue
![WhatsApp Image 2024-09-13 at 11 26 13 PM (1)](https://github.com/user-attachments/assets/ba8e55ca-9514-4e68-8911-1644757e2e0f)

2024-09-16 15:51 UTC, mikehardy submitted a review, later dismissed
please do not include merge commits
please squash changes to a single commit with descriptive commit title + description

2024-09-22 10:17 UTC, BrayanDSO commented
I'll review this again by next week

2024-10-04 11:52 UTC, Prince-kushwaha commented
Hi @lukstbit ,can u please review this PR

2024-10-05 09:22 UTC, lukstbit requested changes
Please be patient, don't ping for reviews.

2024-10-05 09:22 UTC, lukstbit commented on AnkiDroid/src/main/res/layout/dialog_key_picker.xml
> +        android:layout_width="match_parent"
In tablets which have bigger screens the dialog is very big and looks silly. It should be restricted:

- make the width 0dp as well so it follow constraints
- add to the LinearLayout layout_constraintWidth_max to 320dp which looks like a reasonable value to not have the dialog filling the entire screen

2024-10-05 12:28 UTC, Prince-kushwaha commented on AnkiDroid/src/main/res/layout/dialog_key_picker.xml
> +        android:layout_width="match_parent"
done

2024-10-05 13:24 UTC, lukstbit approved these changes
LGTM

2024-10-05 13:41 UTC, merged