Feat[Multimedia]: render `svg` using webview
ankidroid/Anki-Android pull request #17035
Opened 2024-09-07 19:47 UTC by criticalAY

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
* Fixes #

## Approach
Use a webview to render an SVG in it

## How Has This Been Tested?
Tested on OnePlus Nord CE:
![image](https://github.com/user-attachments/assets/567753ef-e5e9-44b1-8b8b-6c6055c3e819)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-09-08 19:07 UTC, BrayanDSO approved these changes
Looks GREAT to me

2024-09-09 09:50 UTC, BrayanDSO commented
Question: does this work for other formats? 

Because animated PNGs are static in the ImageView, but animated when the card is opened

2024-09-10 16:38 UTC, criticalAY commented
> Question: does this work for other formats?

No this method would require workarounds for different images, we can directly use webview to preview images

2024-09-10 23:17 UTC, BrayanDSO commented
> we can directly use webview to preview images

So, is it possible to use the WebView instead of an ImageView to preview all the images?

That should handle all the images that can be rendered in a flashcard

2024-10-02 15:45 UTC, mikehardy requested changes
this does seem like a fantastic opportunity to have a single way to do things vs conditionals

what if *all* images went through the webview? can this PR be altered to do that?

also would be nice to move this along by removing the dependency blocker - I think that other PR is about ready to go so the first commit can drop here ?

2024-10-02 15:47 UTC, criticalAY commented
I will update it to use webview then /will rebase once the blocker goes in /

2024-10-02 16:33 UTC, mikehardy commented
this one is free / unblocked now 🥳

2024-10-12 18:07 UTC, mikehardy requested changes
This is looking really good. Love the "use webview for all the things" direction if we're going to be using a WebView at all

Was testing this and took a crash here - granted, unlikely perhaps in the wild but on an emulator, boom

- add note (basic forward/reversed)
- click paperclip
- select gallery

```
10-12 12:58:40.367  4867  4867 D MultimediaImageFragment: MultimediaImageFragment:: Opening gallery
10-12 12:58:40.391   661   963 D CompatibilityChangeReporter: Compat change id reported: 182734110; UID 10193; state: ENABLED
10-12 12:58:40.392   509   608 D audioserver: FGS Logger Transaction failed
10-12 12:58:40.392   509   608 D audioserver: -129
10-12 12:58:40.399   661   963 I ActivityTaskManager: START u0 {act=android.intent.action.PICK dat=content://media/...} with LAUNCH_MULTIPLE from uid 10193 result code=-91
10-12 12:58:40.399  4867  4867 D AndroidRuntime: Shutting down VM
--------- beginning of crash
10-12 12:58:40.404  4867  4867 E AndroidRuntime: FATAL EXCEPTION: main
10-12 12:58:40.404  4867  4867 E AndroidRuntime: Process: com.ichi2.anki.debug, PID: 4867
10-12 12:58:40.404  4867  4867 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.PICK dat=content://media/... }
10-12 12:58:40.404  4867  4867 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2239)
10-12 12:58:40.404  4867  4867 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1878)
10-12 12:58:40.404  4867  4867 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5589)
10-12 12:58:40.404  4867  4867 E AndroidRuntime: 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.kt:704)
10-12 12:58:40.404  4867  4867 E AndroidRuntime: 	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:244)
10-12 12:58:40.404  4867  4867 E AndroidRuntime: 	at androidx.activity.ComponentActivity$activityResultRegistry$1.onLaunch(ComponentActivity.kt:225)
10-12 12:58:40.404  4867  4867 E AndroidRuntime: 	at androidx.activity.result.ActivityResultRegistry$register$2.launch(ActivityResultRegistry.kt:137)
10-12 12:58:40.404  4867  4867 E AndroidRuntime: 	at androidx.fragment.app.Fragment$10.launch(Fragment.java:3637)
10-12 12:58:40.404  4867  4867 E AndroidRuntime: 	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.kt:37)
10-12 12:58:40.404  4867  4867 E AndroidRuntime: 	at com.ichi2.anki.multimedia.MultimediaImageFragment.openGallery(MultimediaImageFragment.kt:328)
10-12 12:58:40.404  4867  4867 E AndroidRuntime: 	at com.ichi2.anki.multimedia.MultimediaImageFragment.handleSelectedImageOptions(MultimediaImageFragment.kt:288)
10-12 12:58:40.404  4867  4867 E AndroidRuntime: 	at com.ichi2.anki.multimedia.MultimediaImageFragment.handleImageUri(MultimediaImageFragment.kt:280)
10-12 12:58:40.404  4867  4867 E AndroidRuntime: 	at com.ichi2.anki.multimedia.MultimediaImageFragment.onViewCreated(MultimediaImageFragment.kt:272)
10-12 12:58:40.404  4867  4867 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3152)
```

The "take photo, crop it, see it in the preview both times" case worked well though
I did not test the "unsupported image type" case or the actual SVG case (yet)

2024-10-12 18:08 UTC, criticalAY commented
I did test it with svg, gif and normal pictures

2024-10-15 20:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +            inputStream?.bufferedReader()?.use { it.readText() }
I'd rather also see the `inputStream` in a `use {`. I don't believe it's necessary, but don't want readers of the code to have to think

2024-10-15 20:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +            loadDataWithBaseURL(null, svgData, SVG_IMAGE, "UTF-8", null)
I believe this is fine from a security perspective, but would appreciate a second look

2024-10-16 05:37 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +            loadDataWithBaseURL(null, svgData, SVG_IMAGE, "UTF-8", null)
javascript is disabled so, it should be fine, I don't think it will create an issue

2024-10-16 06:02 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +            inputStream?.bufferedReader()?.use { it.readText() }
This still doesn't close the `inputStream`

2024-10-16 06:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +            inputStream?.bufferedReader()?.use { it.readText() }
This is unnecessary, but removes a question I'd have each time I review the code

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt	(revision 4bb6974116b35eea097c03bc1643d76582d8161b)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt	(date 1729058648238)
@@ -579,11 +579,13 @@
      */
     private fun loadSvgFromUri(uri: Uri): String? {
         return try {
-            context?.contentResolver?.openInputStream(uri)?.bufferedReader()?.use { inputStream ->
-                inputStream.readText()
+            context?.contentResolver?.openInputStream(uri)?.use { inputStream ->
+                inputStream.bufferedReader().use { inputStream ->
+                    inputStream.readText()
+                }   
             }
         } catch (e: Exception) {
-            Timber.e(e, "Error reading SVG from URI")
+            Timber.w(e, "Error reading SVG from URI")
             null
         }
     }
```

2024-10-16 06:07 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +            inputStream?.bufferedReader()?.use { it.readText() }
Ahh I thought you meant it should be readable and the extra code, now use is applied to the inputStream, ensuring it is closed properly after the BufferedReader has finished reading the text.

2024-10-16 06:13 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +            inputStream?.bufferedReader()?.use { it.readText() }
@david-allison I already made changes, if you think this is not readable still then I will apply your patch

2024-10-18 21:48 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +            inputStream?.bufferedReader()?.use { it.readText() }
Waiting for your review

2024-11-08 20:19 UTC, criticalAY commented
@david-allison pending review

2024-11-10 23:14 UTC, david-allison reviewed
Looks good! I think these are nitpicks, with the `.use` potentially being a blocker

2024-11-10 23:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +            // Load image based on its MIME type
Explain why the decision is made here

2024-11-10 23:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +    }
`base64Png`

2024-11-10 23:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +        val drawable = ContextCompat.getDrawable(context, drawableResId)
I suspect this method needs a few `.use { }` calls to dispose resources

2024-11-10 23:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +    private fun showErrorInWebView() {
brief javadoc stating this shows an 'error' image

2024-11-10 23:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +                <img src="data:image/png;base64,$base64Image" alt="Error Image"/>
translate the `alt`

2024-11-10 23:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +            Timber.e(e, "Error reading SVG from URI")
```suggestion
            Timber.w(e, "Error reading SVG from URI")
```

2024-11-16 15:43 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +            // Load image based on its MIME type
ok

2024-11-20 21:52 UTC, mikehardy requested changes
I cleaned up the conflict here and re-pushed.

I was curious how the WebView would behave relative to really large files since we have an open crash bug for that #17378 and you commented that this should fix it.

This does not actually fix it, the WebView displays a broken image if you try a really large image. Not sure what the best way to handle that is, onWebProcessGone or something maybe?, unsure, but it doesn't handle failures gracefully yet

Test file https://upload.wikimedia.org/wikipedia/commons/f/fb/%22Bundles_for_Berlin%22_More_production%21.jpg?download (download it, adb push it to /sdcard/Download then you can use it for testing)

2024-11-20 22:29 UTC, david-allison commented
`onRenderProcessGone` is for a 'hard' crash of the WebView process, you shouldn't get this from loading a single image

We should have a TODO about handling it, but it'll be extremely rare

2024-11-20 22:31 UTC, mikehardy commented
This'll take a conflict when #17467 merges regardless (I know because I had to rebase this on on that one in order to test some of the pathways, like even proceeding past the "do you want to compress?" dialog)

2024-11-23 16:01 UTC, criticalAY commented
I created a issue for the render process in case of large image

2024-11-27 19:33 UTC, criticalAY commented
@david-allison ping for re-review

2024-11-27 21:19 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +        }
possibly higher performance (using StringBuffer etc) to use existing util
https://github.com/ankidroid/Anki-Android/blob/c601271739a5abeb2faedf55c6d9a14a4393daf5/AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/InputStream.kt#L30

2024-11-27 21:20 UTC, mikehardy approved these changes
If we're going to handle the WebView choking on large (okay: extremely huge) files separately that's fine by me. It did not crash which was good

So I'm +1 on this with a mild preference to delegate stream handling to centralized methods, as suggested in comment

2024-11-30 05:57 UTC, david-allison reviewed
I'd like to see Mike's change included

Mine are optional

Treat this as an approve when:

* Mike's change is implemented
* The change is tested

2024-11-30 05:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +        val imagePath = imageUri.toString()
nit: 

```kotlin
        Timber.i("Loading non-SVG image using WebView")
```

2024-11-30 05:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +    private fun drawableToBase64png(context: Context, drawableResId: Int): String {
```kotlin
    private fun drawableToBase64png(context: Context, @DrawableRes resId: Int): String {
```

2024-11-30 05:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +    private fun drawableToBase64png(context: Context, drawableResId: Int): String {
implementer's choice: I'd factor it as such:

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt	(revision f4cc20798a7b855dd79735b97189b3a44c6d4214)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt	(date 1732946003234)
@@ -26,17 +26,18 @@
 import android.net.Uri
 import android.os.Bundle
 import android.provider.MediaStore
-import android.util.Base64
 import android.view.View
 import android.webkit.WebView
 import android.widget.TextView
 import androidx.activity.result.contract.ActivityResultContracts
+import androidx.annotation.DrawableRes
 import androidx.appcompat.app.AlertDialog
 import androidx.appcompat.app.AppCompatActivity
 import androidx.core.content.ContextCompat
 import androidx.core.content.FileProvider
 import androidx.core.content.IntentCompat
 import androidx.core.os.BundleCompat
+import androidx.fragment.app.Fragment
 import androidx.lifecycle.lifecycleScope
 import com.canhub.cropper.CropException
 import com.google.android.material.button.MaterialButton
@@ -53,6 +54,7 @@
 import com.ichi2.anki.multimedia.MultimediaUtils.createImageFile
 import com.ichi2.anki.multimedia.MultimediaUtils.createNewCacheImageFile
 import com.ichi2.anki.snackbar.showSnackbar
+import com.ichi2.anki.utils.ext.toBase64Png
 import com.ichi2.annotations.NeedsTest
 import com.ichi2.compat.CompatHelper.Companion.getSerializableCompat
 import com.ichi2.imagecropper.ImageCropper
@@ -67,7 +69,6 @@
 import kotlinx.coroutines.flow.collectLatest
 import kotlinx.coroutines.launch
 import timber.log.Timber
-import java.io.ByteArrayOutputStream
 import java.io.File
 import java.io.FileNotFoundException
 import java.io.FileOutputStream
@@ -555,6 +556,7 @@
      * @param imageUri The URI of the non-SVG image.
      */
     private fun WebView.loadImage(imageUri: Uri) {
+        Timber.i("Loading non-SVG image using WebView")
         val imagePath = imageUri.toString()
         val htmlData = """
         <html>
@@ -567,20 +569,9 @@
         loadDataWithBaseURL(null, htmlData, "text/html", "UTF-8", null)
     }
 
-    private fun drawableToBase64png(context: Context, drawableResId: Int): String {
-        val drawable = ContextCompat.getDrawable(context, drawableResId)
-        val bitmap = (drawable as BitmapDrawable).bitmap
-
-        return ByteArrayOutputStream().use { outputStream ->
-            bitmap.compress(Bitmap.CompressFormat.PNG, 100, outputStream)
-            val byteArray = outputStream.toByteArray()
-            Base64.encodeToString(byteArray, Base64.DEFAULT)
-        }
-    }
-
     /** Shows an error image along with an error text **/
     private fun showErrorInWebView() {
-        val base64Image = drawableToBase64png(requireContext(), R.drawable.ic_image_not_supported)
+        val base64Image = getBitmapDrawable(R.drawable.ic_image_not_supported).toBase64Png()
 
         val errorHtml = """
         <html>
@@ -754,3 +745,6 @@
         DRAWING
     }
 }
+
+private fun Fragment.getBitmapDrawable(@DrawableRes resId: Int) =
+    ContextCompat.getDrawable(requireContext(), resId) as BitmapDrawable
\ No newline at end of file
Index: AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/BitmapDrawable.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/BitmapDrawable.kt b/AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/BitmapDrawable.kt
new file mode 100644
--- /dev/null	(date 1732946028147)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/BitmapDrawable.kt	(date 1732946028147)
@@ -0,0 +1,34 @@
+/*
+ *  Copyright (c) 2024 Ashish Yadav <mailtoashish693@gmail.com>
+ *  Copyright (c) 2024 David Allison <davidallisongithub@gmail.com>
+ *
+ *  This program is free software; you can redistribute it and/or modify it under
+ *  the terms of the GNU General Public License as published by the Free Software
+ *  Foundation; either version 3 of the License, or (at your option) any later
+ *  version.
+ *
+ *  This program is distributed in the hope that it will be useful, but WITHOUT ANY
+ *  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
+ *  PARTICULAR PURPOSE. See the GNU General Public License for more details.
+ *
+ *  You should have received a copy of the GNU General Public License along with
+ *  this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+package com.ichi2.anki.utils.ext
+
+import android.graphics.Bitmap.CompressFormat
+import android.graphics.drawable.BitmapDrawable
+import android.util.Base64
+import android.webkit.WebView
+import java.io.ByteArrayOutputStream
+
+/**
+ * Converts a [BitmapDrawable] into a Base64 PNG, typically for displaying in a [WebView]
+ */
+fun BitmapDrawable.toBase64Png() = ByteArrayOutputStream().use { outputStream ->
+    // quality (100) is ignored as PNG is lossless
+    bitmap.compress(CompressFormat.PNG, 100, outputStream)
+    val byteArray = outputStream.toByteArray()
+    Base64.encodeToString(byteArray, Base64.DEFAULT)
+}
\ No newline at end of file
```

2024-12-05 14:19 UTC, criticalAY commented
@mikehardy @david-allison Done!

2024-12-05 23:06 UTC, david-allison approved these changes
REALLY clean, cheers!

2024-12-05 23:06 UTC, david-allison commented
* https://github.com/ankidroid/Anki-Android/pull/17565 https://github.com/ankidroid/Anki-Android/labels/Strings

2024-12-06 00:15 UTC, merged