Refactored `DeckPickerWidget` to handle empty state visibility.
ankidroid/Anki-Android pull request #17041
Opened 2024-09-08 20:28 UTC by xenonnn4w

## Purpose / Description
Handle empty state visibility, allowing users to reconfigure the widget by clicking the empty state message in the Deck Picker Widget.

## Approach
Handled similar to that Card Analysis Widget.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-09-08 20:34 UTC, david-allison commented
What does this look like?

2024-09-08 20:52 UTC, xenonnn4w commented
added in the PR description.

2024-09-09 06:51 UTC, xenonnn4w commented
I reviewed the code and noticed an issue with the visibility of empty_deck. I plan to investigate and resolve it when I have more time.

2024-09-14 21:20 UTC, xenonnn4w commented
Fixed!

2024-09-16 14:16 UTC, mikehardy requested changes
I think this looks good - after looking through our back stack management though, I'm curious if we are missing a CLEAR_TOP on the Intent for the reviewer though

Otherwise (that is: the bulk of the PR): looks good

2024-09-16 14:16 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidget.kt
>                          }
should this have an Intent flag to CLEAR_TOP ?

2024-09-16 17:19 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidget.kt
>                          }
Thanks, Done!

2024-09-16 17:51 UTC, mikehardy approved these changes
Fantastic, I think this looks pretty good and from the video it looks pretty good to me

If you are curious at all - and I mention it because I have seen you do related work so I think you might be interested? - you might look at #17073 to consolidate our usage of these flags...

2024-09-29 12:33 UTC, lukstbit requested changes

2024-09-29 12:33 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidget.kt
> +                showDeck(context, appWidgetManager, appWidgetId, remoteViews, deckIds)
At this point _deckIds_ can't be null because you already checked above to show the empty state. This allows you to avoid the null checking in _showDeck_ by declaring the parameter as non null.

2024-09-29 12:33 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidget.kt
> +            remoteViews.setViewVisibility(R.id.empty_widget, View.VISIBLE)
If we are using the empty TextView to show a message for when the collection is empty(by setting a specific text there) than we should also set the missing deck text here.

2024-09-29 12:33 UTC, lukstbit commented on AnkiDroid/src/main/res/layout/widget_deck_picker_large.xml
> +        android:layout_marginStart="7dp"
As material design uses multiples of 4 for dimensions we should also use this for marginstart(8dp).

2024-09-29 12:33 UTC, lukstbit commented on AnkiDroid/src/main/res/layout/widget_deck_picker_large.xml
> +        android:text="@string/empty_widget"
The current text is _"Missing deck. Please reconfigure"_. I think it may better to change the last part to add either _Touch_ or _Click_ to tell the user how he can act on the issue:

_"Missing deck. Touch to reconfigure"_
_"Missing deck. Click to reconfigure"_

2024-09-29 12:33 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidget.kt
> +            remoteViews.setTextViewText(R.id.empty_widget, context.getString(R.string.app_not_initialized_new))
I've tested the no collection scenario and the user experience is not great here. 

If I have a collection with one deck that I register in the widget and then go to the app and delete the deck, when I return to the widget I see the message: _AnkiDroid is not initialized yet. Please open AnkiDroid and try again_. The issues:

- text is misleading
- if I'm going to the app and come back I still see the message
- if I'm going to the app and add decks and come back I still see the message
- touching the widget does nothing

I have to long click the widget to bring the system configure button to do anything.

So I would recommend to create a special string for this case(example: _Collection is empty, use app to add decks_), when the collection is empty and also make that text clickable to show the configure screen.

2024-10-02 19:36 UTC, xenonnn4w commented on AnkiDroid/src/main/res/layout/widget_deck_picker_large.xml
> +        android:layout_marginStart="7dp"
Thanks, I didn't know that earlier!

2024-10-02 19:57 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidget.kt
> +            remoteViews.setViewVisibility(R.id.empty_widget, View.VISIBLE)
Sorry, I didn't understand the context regarding the missing deck text.

2024-10-02 20:59 UTC, Arthur-Milchior reviewed
Is this issue specific to deck picker widget?
I'd have expected it could be the same issue in your card analysis widget, given that it also requires a deck.

If so, I'd appreciate if you could have change both widgets at once, idially without copy pasting too much code

2024-10-02 20:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="empty_widget" comment="To denote the widget is empty">Missing deck. Click to reconfigure</string>
I'd appreciate a dot at the end of the sentence.

2024-10-02 20:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="empty_widget" comment="To denote the widget is empty">Missing deck. Click to reconfigure</string>
Also, please use "tap" instead of "click". We expect more users on touch screen than using mouse.

2024-10-02 20:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/08-widget.xml
> +    <string name="empty_collection" comment="To denote the collection is empty">Collection is empty, use app to add decks then reconfigure</string>"
Please use a longer name. `empty_collection` is relatively vague, and I'd expect if we ever want to use it we may want to use it for something that is generally shown on empty collection.
I expect this string to be so rare that there may be more translators than users seeing it.

2024-10-03 10:21 UTC, xenonnn4w commented on AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidget.kt
> +            remoteViews.setViewVisibility(R.id.empty_widget, View.VISIBLE)
Got it, Thanks!

2024-10-03 13:48 UTC, lukstbit approved these changes
LGTM, thanks!

2024-10-03 14:01 UTC, merged