Solves a few little issues with toolbar
ankidroid/Anki-Android pull request #17045
Opened 2024-09-08 21:52 UTC by Arthur-Milchior

Fixed: #15308

The first commit clean some code, using TooltipCompats when possible, instead of checking the API version in code

The second does some more cleaning.

The third split a string in two strings, because it should not be the same in French, and probably not in other languages too. In English, the noun and the verb "search" are the same. Not in French at least.

The fourth add a "Discard" tooltip on the "x" button near the search view that discard the content of the search field.

2024-09-09 09:21 UTC, lukstbit requested changes

2024-09-09 09:21 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/ui/SearchView.kt
> +open class SearchView : androidx.appcompat.widget.SearchView {
Please either rename the class(ex. SearchViewWithTooltip) or add documentation to mention what it does and also to tell developers to use this instead of the platform class. It's very annoying to have classes with the same name as platform classes and without documentation because you're forced to check what the custom class does.

2024-09-09 09:21 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/ui/SearchView.kt
> +        TooltipCompat.setTooltipText(
As we are accessing an internal view we should de very defensive about how we use it:

```
findViewById<View>(androidx.appcompat.R.id.search_close_btn)?.let {
    TooltipCompat.setTooltipText(it, context.getString(R.string.discard)
}
```

2024-09-09 20:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/ui/SearchView.kt
> +open class SearchView : androidx.appcompat.widget.SearchView {
You're totally right, I am surprised I forgot to document. It's done.

I wanted to keep the same name because there is no place where we have any reason anymore to use the androidx SearchView, so it seems okay to hide it.

2024-09-09 20:37 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/ui/SearchView.kt
> +        TooltipCompat.setTooltipText(
Done.
Not entirely sure it's the right move. I think I'd have preferred to have a crash that we detect very quickly while using the app if there was a change in behavior. With this, the tooltip could disappear without us noticing it.

2024-09-11 08:07 UTC, lukstbit approved these changes

2024-09-11 12:00 UTC, david-allison requested changes
`SearchView` rename is blocking

nit: I'd be a fan of a `setTooltipTextCompat` extension to reduce churn in calling code, but that's strongly implementer's choice

Subject: [PATCH]
---
Index: AnkiDroid/src/main/java/com/ichi2/ui/SearchView.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/ui/SearchView.kt b/AnkiDroid/src/main/java/com/ichi2/ui/SearchView.kt
--- a/AnkiDroid/src/main/java/com/ichi2/ui/SearchView.kt	(revision ec4cdf02cca8874832794768511acc9310e24f18)
+++ b/AnkiDroid/src/main/java/com/ichi2/ui/SearchView.kt	(date 1726055683190)
@@ -19,8 +19,8 @@
 import android.content.Context
 import android.util.AttributeSet
 import android.widget.ImageView
-import androidx.appcompat.widget.TooltipCompat
 import com.ichi2.anki.R
+import com.ichi2.compat.setTooltipTextCompat
 
 /**
  * Same as androidx's SearchView, with an extra tooltip.
@@ -31,15 +31,9 @@
     constructor(context: Context, attrs: AttributeSet) : super(context, attrs)
     constructor(context: Context, attrs: AttributeSet, defStyleAttr: Int) : super(context, attrs, defStyleAttr)
     init {
-        // Close_btn is the cross that delete the content of the search field. It does not actually close the search view.
-        findViewById<ImageView>(androidx.appcompat.R.id.search_close_btn)?.let {
-            TooltipCompat.setTooltipText(
-                it,
-                context.getString(
-                    R.string.discard
-                )
-            )
-        }
+        // close_btn is the cross that deletes the search field content. It does not close the search view.
+        findViewById<ImageView>(androidx.appcompat.R.id.search_close_btn)
+            ?.setTooltipTextCompat(context.getString(R.string.discard))
     }
     // SearchView contains four button. The three others seems never to appear in ankidroid.
     // there is also a arrow to the trailing side, that should get a tooltip. Alas, I fail to see the id of this button, so I can't add it.
Index: AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.kt b/AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.kt
--- a/AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.kt	(revision ec4cdf02cca8874832794768511acc9310e24f18)
+++ b/AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.kt	(date 1723381204478)
@@ -21,6 +21,7 @@
 import androidx.annotation.VisibleForTesting
 import androidx.appcompat.widget.TooltipCompat
 import com.ichi2.anki.ActionProviderCompat
+import com.ichi2.compat.setTooltipTextCompat
 
 /**
  * An Rtl version of a normal action view, where the drawable is mirrored
@@ -40,7 +41,7 @@
 
     override fun onCreateActionView(forItem: MenuItem): View {
         val actionView = ImageButton(context, null, android.R.attr.actionButtonStyle)
-        TooltipCompat.setTooltipText(actionView, forItem.title)
+        actionView.setTooltipTextCompat(forItem.title)
         forItem.icon?.let {
             it.isAutoMirrored = true
             actionView.setImageDrawable(it)
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(revision ec4cdf02cca8874832794768511acc9310e24f18)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(date 1725827864855)
@@ -62,7 +62,6 @@
 import androidx.appcompat.app.AppCompatActivity
 import androidx.appcompat.widget.AppCompatButton
 import androidx.appcompat.widget.PopupMenu
-import androidx.appcompat.widget.TooltipCompat
 import androidx.core.content.ContextCompat
 import androidx.core.content.FileProvider
 import androidx.core.content.IntentCompat
@@ -137,6 +136,7 @@
 import com.ichi2.compat.CompatHelper
 import com.ichi2.compat.CompatHelper.Companion.getSerializableCompat
 import com.ichi2.compat.CompatHelper.Companion.registerReceiverCompat
+import com.ichi2.compat.setTooltipTextCompat
 import com.ichi2.imagecropper.ImageCropper
 import com.ichi2.imagecropper.ImageCropper.Companion.CROP_IMAGE_RESULT
 import com.ichi2.imagecropper.ImageCropperLauncher
@@ -2191,7 +2191,7 @@
         val button = toolbar.insertItem(0, drawable) { insertCloze(type) }.apply {
             contentDescription = description
         }
-        TooltipCompat.setTooltipText(button, description)
+        button.setTooltipTextCompat(description)
     }
 
     private fun updateToolbar() {
@@ -2251,7 +2251,7 @@
         drawable!!.setTint(MaterialColors.getColor(requireContext(), R.attr.toolbarIconColor, 0))
         val addButton = toolbar.insertItem(0, drawable) { displayAddToolbarDialog() }
         addButton.contentDescription = resources.getString(R.string.add_toolbar_item)
-        TooltipCompat.setTooltipText(addButton, resources.getString(R.string.add_toolbar_item))
+        addButton.setTooltipTextCompat(resources.getString(R.string.add_toolbar_item))
     }
 
     private val toolbarButtons: ArrayList<CustomToolbarButton>
Index: AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt b/AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
--- a/AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt	(revision ec4cdf02cca8874832794768511acc9310e24f18)
+++ b/AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt	(date 1726055865366)
@@ -29,6 +29,8 @@
 import android.view.KeyCharacterMap.deviceHasKey
 import android.view.KeyEvent.KEYCODE_PAGE_DOWN
 import android.view.KeyEvent.KEYCODE_PAGE_UP
+import android.view.View
+import androidx.appcompat.widget.TooltipCompat
 import androidx.core.content.ContextCompat
 import com.ichi2.compat.CompatHelper.Companion.compat
 import java.io.Serializable
@@ -195,3 +197,20 @@
             ContextCompat.registerReceiver(this, receiver, filter, flags)
     }
 }
+
+
+
+/**
+ * Sets the tooltip text for the view.
+ *
+ * On API 26 and later, this method calls through to {@link View#setTooltipText(CharSequence)}.
+ *
+ * Prior to API 26, this method sets or clears (when tooltipText is {@code null}) the view's
+ * {@code OnLongClickListener} and {@code OnHoverListener}. A tooltip-like sub-panel will be
+ * created on long-click or mouse hover.
+ *
+ * @receiver the view on which to set the tooltip text
+ * @param tooltipText the tooltip text
+ */
+fun View.setTooltipTextCompat(tooltipText: CharSequence?)
+    = TooltipCompat.setTooltipText(this, tooltipText)
Index: AnkiDroid/src/main/java/com/ichi2/anki/SyncActionProvider.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/SyncActionProvider.kt b/AnkiDroid/src/main/java/com/ichi2/anki/SyncActionProvider.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/SyncActionProvider.kt	(revision ec4cdf02cca8874832794768511acc9310e24f18)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/SyncActionProvider.kt	(date 1726055865362)
@@ -22,9 +22,9 @@
 import android.view.MenuItem
 import android.view.View
 import androidx.appcompat.widget.AppCompatImageButton
-import androidx.appcompat.widget.TooltipCompat
 import androidx.core.view.isVisible
 import com.google.android.material.pro [...]

2024-09-11 12:03 UTC, david-allison requested changes
typos

2024-09-11 12:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/SearchView.kt
> +    // SearchView contains four button. The three others seems never to appear in ankidroid.
```suggestion
    // SearchView contains four buttons. The three others seems never to appear in ankidroid.
```

2024-09-11 12:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/SearchView.kt
> +    // there is also a arrow to the trailing side, that should get a tooltip. Alas, I fail to see the id of this button, so I can't add it.
```suggestion
    // there is also an arrow to the trailing side, that should get a tooltip. Alas, I fail to see the id of this button, so I can't add it.
```

2024-09-11 18:23 UTC, Arthur-Milchior reviewed
I replied to your message. But somehow this message appears as "pending". I thought that if I replied directly to an existing message, I didn't have to use the "review change" button. Sorry, indeed, without my answer asking for a name, that made no sense.

2024-09-11 18:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/ui/SearchView.kt
> +open class SearchView : androidx.appcompat.widget.SearchView {
@lukstbit

2024-09-16 15:22 UTC, david-allison commented
I believe this is awaiting a response from @lukstbit on https://github.com/ankidroid/Anki-Android/pull/17045#discussion_r1755370796

2024-09-16 15:22 UTC, david-allison approved these changes
I'm an approve, I feel the "rename" thread is still open

2024-09-20 16:03 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/ui/SearchView.kt
> +open class SearchView : androidx.appcompat.widget.SearchView {
I think it was settled on Discord on using _AccessibleSearchView_ as the name of the widget?!? I'm fine with this name, _SearchViewWithTooltip_ was just a quick suggestion, something to differentiate the two classes.

2024-09-21 00:53 UTC, Arthur-Milchior commented
Renamed

2024-09-21 08:57 UTC, lukstbit approved these changes
Thank you!

2024-09-21 09:38 UTC, merged