Handle Android 15+ audio focus changes / allow platform to handle focus in AV fragment
ankidroid/Anki-Android pull request #17054
Opened 2024-09-11 17:14 UTC by mikehardy

## Purpose / Description

Android 15+ apps have audio focus restrictions applied

See: https://developer.android.com/about/versions/15/behavior-changes-15#audio-focus

> Apps that target Android 15 (API level 35) must be the top app or running a
> foreground service in order to request audio focus. If an app attempts to request
> focus when it does not meet one of these requirements, the call returns AUDIOFOCUS_REQUEST_FAILED

It is recommended, if you are using ExoPlayer (which the new AV fragment in #16769 does), to allow the platform to handle audio focus, and this PR also includes a commit to enable that.

The SoundTagPlayer should be refactored to use ExoPlayer in my opinion, now that we have that as a dependency, then audio focus code should be removed from SoundTagPlayer. That is out of scope for this PR though as it requires a large refactor

## Approach

- in SoundTagPlayer simply check if the focus request failed before attempting to do anything
- in AudioVideoFragment, set the ExoPlayer up with correct ContentType and instruction to handle focus automatically

## How Has This Been Tested?

> [!WARNING]
> automated tests only, testing while not in foreground is not something I'm sure how to do

@david-allison If I recall correctly you just did a big refactor to handle auto-play / start / stop etc, so you will know if shortcutting out of the "play sounds" series of steps on request failure will result in a state issue that will cause problems later when "stop" is attempted. I believe it is always valid to attempt to stop playback or to attempt focus abandon even if you don't have it so it *should* be okay? The playback stop has state exceptions handled, and focus abandon failure is unimportant...

@criticalAY the ExoPlayer setup change might be interesting for you? And/or you may want to attempt the SoundTagPlayer port to ExoPlayer if that seems like a good idea

## Learning (optional, can help others)

Scan of https://developer.android.com/about/versions/15/behavior-changes-15 (and the 14 changes as well...)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-09-11 17:39 UTC, criticalAY commented
Sounds interesting to me, can do so

2024-09-11 17:39 UTC, criticalAY approved these changes
This looks good

2024-09-12 23:18 UTC, BrayanDSO commented
Sound tags are currently only played if the app is the top app, so theoretically there shouldn't be any problems with keep using MediaPlayer. IIRC, SoundTagPlayer handles errors well

2024-09-13 05:06 UTC, david-allison requested changes
I'm very limited on time, sorry for the unsubstantiated claim without testing

2024-09-13 05:06 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundTagPlayer.kt
> +            if (requestAudioFocus() == AudioManager.AUDIOFOCUS_REQUEST_GRANTED) {
It feels like the error case doesn't affect the continuation, meaning that we block the coroutine

2024-09-13 18:10 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundTagPlayer.kt
> +            if (requestAudioFocus() == AudioManager.AUDIOFOCUS_REQUEST_GRANTED) {
okay will look more closely - this is important but not urgent, just something I tossed up while skimming android 15 changelist. So there is time to investigate

@BrayanDSO agreed using base MediaPlayer is not a *bad* thing. I just think ExoPlayer may allow for less code in our repo as it offers more functionality out of the box and our requirements match it pretty well. Agreed SoundTagPlayer implementation here is pretty well done though, so it would be a low-priority task IMHO

2024-09-17 14:32 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundTagPlayer.kt
> +            if (requestAudioFocus() == AudioManager.AUDIOFOCUS_REQUEST_GRANTED) {
Exo player removes the headache of handling any error manually though, so less maintenance in future :)

2024-09-21 21:27 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundTagPlayer.kt
> +            if (requestAudioFocus() == AudioManager.AUDIOFOCUS_REQUEST_GRANTED) {
Took a minute to read up on CancellableContinuation and how it is supposed to work, or how I think it is supposed to work

And you are correct, the continuation was ignored but there is now seemingly a branch now where it may be left uncontinued indefinitely

I added an else to the conditional then, logged out that we couldn't get focus and cancelled the continuation

I *think* that's how this stuff is supposed to work but I have never played with these APIs before so definitely needs a look

2024-09-26 21:31 UTC, david-allison approved these changes
This looks great, sorry it sat for so long!

2024-09-26 21:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt
> +            true
I'd have recommended naming this argument, but it's not possible as it's a call to a Java function

2024-09-28 08:35 UTC, lukstbit approved these changes
LGTM

2024-09-28 08:53 UTC, merged