fix : [Bug] The layout of the Axis Picker screen is not displaying correctly in landscape mode
ankidroid/Anki-Android pull request #17064
Opened 2024-09-14 10:22 UTC by Prince-kushwaha

## Purpose / Description
The layout of the Axis Picker screen is not displaying correctly in landscape mode

## Fixes
* Fixes #17026 

## Approach

## How Has This Been Tested?
Physical android device

##Screenshot

![WhatsApp Image 2024-09-14 at 3 47 58 PM](https://github.com/user-attachments/assets/26086323-f6c3-40bb-92d7-1e2bc42e73eb)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-09-16 14:41 UTC, mikehardy requested changes
- never do merge commits
- never push commits that are useless like ones that just say "change"

Please rebase this to have only the change you want in a single nice commit with descriptive message

I can't review it otherwise

2024-09-17 15:27 UTC, Prince-kushwaha commented
@mikehardy review comments are done

2024-09-22 10:59 UTC, BrayanDSO commented
I'll look at it by next week

2024-10-04 11:50 UTC, Prince-kushwaha commented
Hi @lukstbit ,can u please review this PR

2024-10-05 12:09 UTC, lukstbit requested changes
Same comment as in [your other PR](https://github.com/ankidroid/Anki-Android/pull/17022#discussion_r1788546574).

2024-10-05 13:57 UTC, Prince-kushwaha commented
> Same comment as in [your other PR](https://github.com/ankidroid/Anki-Android/pull/17022#discussion_r1788546574).

done

2024-10-05 14:27 UTC, lukstbit approved these changes
LGTM

2024-10-05 14:40 UTC, merged