fix: export option dialog have text overlapping issue and last checkbox is not visible in landscope mode
ankidroid/Anki-Android pull request #17061
Opened 2024-09-12 15:06 UTC by Prince-kushwaha

## Purpose / Description
export option dialog have text overlapping issue and last checkbox is not visible in landscope mode

## Fixes
* Fixes #17060 

## Approach
make layout scrollview

## How Has This Been Tested?
physical android device

## Screenshot
![WhatsApp Image 2024-09-12 at 8 26 01 PM](https://github.com/user-attachments/assets/f959a0e9-7ab1-4e44-b8de-dcd224fa0d21)
![WhatsApp Image 2024-09-12 at 8 26 06 PM](https://github.com/user-attachments/assets/8f5277fb-dc29-4315-b99e-9aa85158c008)
![WhatsApp Image 2024-09-12 at 8 26 08 PM](https://github.com/user-attachments/assets/518ef18d-b411-4a21-ab73-5533a693cf77)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-09-16 03:23 UTC, criticalAY approved these changes
LGTM, but PR can be rebased

2024-09-16 14:40 UTC, mikehardy requested changes
Agreed with @criticalAY - @Prince-kushwaha we use the merge queue here set to rebase, and I can't rebase-merge a dirty commit history like this. If you'll be making a bunch of PRs (and there are two in the queue now for review) you need to make PRs with a clean commit history

In your local checkout of this branch you want to git rebase and squash these 4 commits to a single commit with descriptive title and description

There should never be commits that are meaningless. like "change"

For me that would be this in a terminal:

- `git rebase -i HEAD~4` (to get the last 4 commits up in a commit editor
- in editor delete `pick` from commits 2-4 and switch to `s` for squash
- now save the editor and it will make a single commit with all messages together in an editor
- in the editor, delete all the commit messages and make one clean descriptive commit message
- save that, then `git push --force-with-lease` to push that rebase to the branch on github
- re-request review

2024-09-17 14:30 UTC, criticalAY approved these changes
Much cleaner commit history

2024-09-17 15:24 UTC, Prince-kushwaha commented
@mikehardy  Thank you for sharing that with me! I’ve learned a lot from that.

2024-09-20 18:13 UTC, mikehardy approved these changes
commit history cleaner, and this seems like an okay fix
I know Brayan has strong opinions on UI so asking for a review there
May take a while though, these are not super high priority fixes, so please have patience

2024-09-22 09:09 UTC, lukstbit requested changes
I specifically added ScrollViews to longer forms in that dialog to handle this but it seems it doesn't work and the ScrollView function as a normal layout(full height). I think this is also related to using configChanges for the DeckPicker but that attribute isn't going to be removed any time soon.

If those ScrollViews aren't working as expected then they should be removed as well to not have scrollable containers inside other scrollable containers. So,also remove the two inner ScrollViews and move their properties to the LinearLayout that they wrap.

2024-09-22 15:02 UTC, Prince-kushwaha commented
Review comments done

2024-09-23 10:51 UTC, lukstbit commented on AnkiDroid/src/main/res/layout/dialog_export_options.xml
> +            android:fillViewport="true"
_fillViewport_ is an attribute specifically for ScrollView not for any ViewGroup. While it doesn't do anything it shouldn't be used.

So delete the _android:fillViewport_ here and for the other LinearLayout and then we could merge this.

2024-09-23 12:33 UTC, Prince-kushwaha commented on AnkiDroid/src/main/res/layout/dialog_export_options.xml
> +            android:fillViewport="true"
done

2024-09-23 12:55 UTC, lukstbit approved these changes
Thanks!

2024-09-23 13:09 UTC, merged