Rephrase "Abort learning"
ankidroid/Anki-Android pull request #17117
Opened 2024-09-23 21:45 UTC by Arthur-Milchior

Those two strings appears as actions to which you can associate a gesture or a shortcut.

I must admit that I've no idea what "Abort learning" mean, until I looked at the code.

I hesitated to use "Close the Deck", because, after all, from the user point of view, we were opening a deck. The name "reviewer" is rarely used. But that's already the name used in our documentation and in other settings string, so I decided to keep it.

Admittedly, I'm not a native English speaker, so it's hard for me to know whether a native would understand directly what it means.

2024-09-24 04:50 UTC, snowtimeglass requested changes

2024-09-24 04:50 UTC, snowtimeglass commented on AnkiDroid/src/main/res/values/11-arrays.xml
> +    <string name="gesture_abort_learning">Close the reviewer</string>
```suggestion
    <string name="gesture_abort_learning">Close reviewer</string>
```

I assume articles can be omitted here as in the other items.

2024-09-24 04:50 UTC, snowtimeglass commented on AnkiDroid/src/main/res/values/11-arrays.xml
> +    <string name="gesture_abort_sync">Close the reviewer and Sync</string>
```suggestion
    <string name="gesture_abort_sync">Close reviewer and Sync</string>
```

Omission of article.

2024-09-26 17:21 UTC, david-allison approved these changes
Agreed on the comment by snowtimeglass

No more to add. Looks good to me. Treat this as an approval once the comment is handled

2024-09-26 17:22 UTC, david-allison commented on AnkiDroid/src/main/res/values/11-arrays.xml
> +    <string name="gesture_abort_sync">Close the reviewer and Sync</string>
Agreed

2024-09-27 13:35 UTC, lukstbit approved these changes
Pending merge, waiting for the requested change.

2024-09-28 01:30 UTC, david-allison commented
Awaiting a strings sync

2024-09-28 09:58 UTC, merged