Language name starts with a upper case
ankidroid/Anki-Android pull request #17121
Opened 2024-09-23 23:54 UTC by Arthur-Milchior

Language name starts with a upper case

The menu provided to the users to select their languages is not yet
perfect. It's hard to know for certain what is the correct way to
display the languages to the users. The function provided by Android
was buggy, and so, a year and a half ago, the language names were
hard-coded in #13275. Except that nobody speaks the 93 languages in
which we have translations available.

On the long term, I hope that 92 translators will provide 92 language
string to use. #17120 should start the process to eventually fix this
error.

On the short term, there is one change that we can make that will
probably be, on average, an improvement. Using upper case for the
first letter of each name.

If I understand correctly Brayan's comment, this change would be
correct for Portugese. I can confirm it's correct for French. I can't
promise this won't make things worse for some language. But, if we got
some right previously, it was by accident, and I still hope this is,
on average, an improvement.

The upper cases were obtained by using the "set first later to upper
case" feature of emacs on each language name.

Fixed: #17118

2024-09-24 00:33 UTC, david-allison requested changes
Two are incorrect.

Do we have this data anywhere in CLDR?

2024-09-24 00:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        "IsiXhosa" to "xh", // Xhosa
⚠️ This is incorrect

2024-09-24 00:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        "Eesti" to "et", // Estonian
possibly `Eesti keel`

2024-09-24 00:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        "Magyar" to "hu", // Hungarian
Possibly `Magyar nyelv`

2024-09-24 00:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        "Hայերեն (Հայաստան)" to "hy-AM", // Armenian (Armenia)
Maybe

2024-09-24 00:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        "Қазақ тілі" to "kk", // Kazakh
to be confirmed

2024-09-24 00:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        "Latviešu" to "lv", // Latvian
`Latviski` on Wikipedia

2024-09-24 00:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        "Română" to "ro", // Romanian
`Românește` on Wikipedia

2024-09-24 00:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        "O‘zbek" to "uz", // Uzbek
`O‘zbek` is not on Wikipedia as an Endonym

2024-09-24 00:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        "IsiZulu" to "zu" // Zulu
⚠️ This is incorrect

2024-09-24 01:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        "IsiXhosa" to "xh", // Xhosa
https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry  which is referenced by your first wikipedia link only use "Xhosa" while the second link indeed uses isiXhosa.

2024-09-24 01:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        "Қазақ тілі" to "kk", // Kazakh
Reverted in the meantime

2024-09-24 01:56 UTC, Arthur-Milchior commented
I applied your comment.

Honestly, I'm not exactly sure where to get confirmation, appart from waiting for translators to provide feedback through crowdin. I don't expect to easily find native Uzbek` speaker for example

2024-09-24 03:05 UTC, david-allison commented
I flagged potential issues. Stick with the CLDR-proposed names unless you've confirmed either way

2024-09-24 03:14 UTC, david-allison requested changes
I aim to approve after this mix of reverts and changes

2024-09-24 03:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        "Islenska" to "is", // Icelandic
```suggestion
        "íslenska" to "is", // Icelandic
```

> Language names as a rule are written in lowercase letters, likewise adjectives which are derived from nationalities, ex. íslenzka (Icelandic-language), enska (English language), danska (Danish language); íslenzkur (Icelandic person, adj.), enskur (English person, adj.), þýzkur (German person, adj.)

https://learn-nordic.livejournal.com/63751.html

----

Or use a capital í, instead of I

2024-09-24 03:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        "Eesti keel" to "et", // Estonian
```suggestion
        "Eesti" to "et", // Estonian
```

2024-09-24 03:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        "Magyar nyelv" to "hu", // Hungarian
```suggestion
        "Magyar" to "hu", // Hungarian
```

2024-09-24 03:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
>          "қазақ тілі" to "kk", // Kazakh
```suggestion
        "Қазақ тілі" to "kk", // Kazakh
```

2024-09-24 03:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        "Latviski" to "lv", // Latvian
```suggestion
        "Latviešu" to "lv", // Latvian
```

2024-09-24 03:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        "Românește" to "ro", // Romanian
```suggestion
        "Română" to "ro", // Romanian
```

2024-09-24 03:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
>          "Santali" to "sat", // Santali
```suggestion
        "ᱥᱟᱱᱛᱟᱲᱤ" to "sat", // Santali
```

2024-09-24 03:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
>          "Sardinian" to "sc", // Sardinian
```suggestion
        "Sardu" to "sc", // Sardinian
```

2024-09-24 03:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
>          "Santali" to "sat", // Santali
Note: not capitalization

2024-09-24 03:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
>          "Sardinian" to "sc", // Sardinian
ditto

2024-09-25 00:18 UTC, david-allison commented
Note: only one comment was addressed

2024-09-26 15:59 UTC, david-allison approved these changes
LGTM, cheers!

2024-09-26 18:05 UTC, david-allison commented
@Arthur-Milchior I've squashed the commits and force pushed. 

I've added additional information to the first commit message, and written the second.

When feasible, could you review my changes and confirm you're happy with them, given I've set you as the author on both

2024-09-30 15:42 UTC, mikehardy requested changes
I'm fine with this except I exhaustively investigated whether Spanish was capitalized as an endonum or not, and it is not

2024-09-30 15:42 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        "Español (España)" to "es-ES", // Spanish (Spain)
As near as I can tell, Spanish does *not* capitalize the first letter of languages:

- https://www.spanishdict.com/guide/capitalization-in-spanish (find in page "Time Words and Adjectives")
- https://www.tellmeinspanish.com/grammar/spanish-capitalization-rules/#words_that_are_not_capitalized
- https://www.fluentu.com/blog/spanish/spanish-captialization/#toc_16

And of course the most important, the arbiters of the language, the RAE:

https://www.rae.es/buen-uso-espa%C3%B1ol/cu%C3%A1ndo-no-debe-utilizarse-la-may%C3%BAscula-inicial-i

```
• Se inician con minúscula los adjetivos y sustantivos que designan pueblos o etnias, así como los que denotan nacionalidad o procedencia geográfica:

- la cultura mochica, los aztecas, los maoríes, los filipinos.


• También los nombres de las lenguas o idiomas
- El español es la lengua más estudiada del mundo después del inglés.

```
```suggestion
        "español (Argentina)" to "es-AR", // Spanish (Argentina)
        "español (España)" to "es-ES", // Spanish (Spain)
```

2024-09-30 15:57 UTC, mikehardy commented
I like the idea and the general implementation, my only requested change is very very language specific for Spanish.
I'm fine to merge after that

2024-09-30 15:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
> +        "Español (España)" to "es-ES", // Spanish (Spain)
@mikehardy CLDR appears to disagree

https://github.com/unicode-org/cldr/blob/1eadcf9c1a8dc3c33b001d3d9e98e6c7d9c1e45b/common/main/es.xml#L1243-L1268

truncated:

```xml
	<contextTransforms>
		<contextTransformUsage type="languages">
			<contextTransform type="stand-alone">titlecase-firstword</contextTransform>
			<contextTransform type="uiListOrMenu">titlecase-firstword</contextTransform>
		</contextTransformUsage>
	</contextTransforms>
```

2024-09-30 16:23 UTC, mikehardy approved these changes
I believe I know more now

2024-09-30 16:30 UTC, david-allison commented
I believe I know how little I know

2024-09-30 16:36 UTC, merged