[BUG]:The Set Due Date dialog box is missing its title
ankidroid/Anki-Android pull request #17143
Opened 2024-09-26 11:03 UTC by gautamsingh2

## Purpose / Description

The Set Due Date dialog box is missing its title .
## Fixes
* Fixes #17124 

##Screenshot

![WhatsApp Image 2024-09-26 at 4 27 46 PM](https://github.com/user-attachments/assets/240e36e9-bd47-4ea3-9264-4de3999247b0)
![WhatsApp Image 2024-09-26 at 4 27 45 PM](https://github.com/user-attachments/assets/db53fb10-36ca-4ab8-9d00-825625295c36)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-09-26 13:17 UTC, criticalAY commented
This PR is irrelevant since these a tool string as are visible in dev build only, actual strings are coming from backend only

2024-09-26 16:06 UTC, david-allison requested changes
This should come from the backend.

* update the xml files to note that this is the reason the strings are hardcoded
* update the code to set the title using (I believe): `TR.actionsSetDueDate().toSentenceCase(this@SetDueDateDialog, R.string.sentence_set_due_date))`

2024-09-27 08:09 UTC, gautamsingh2 commented
review feedback done

2024-09-30 17:38 UTC, david-allison approved these changes

2024-10-01 05:33 UTC, lukstbit requested changes

2024-10-01 05:33 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt
> +            it.apply {
There's no need for this, just use it.title and it.dialogTitle.

2024-10-01 05:33 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomButtonsSettingsFragment.kt
> +            it.apply {
Same, just use it.*

2024-10-04 05:24 UTC, lukstbit approved these changes
Thanks!

2024-10-04 05:37 UTC, merged

2025-01-06 15:41 UTC, Aminadev2 commented
Hi @david-allison ,i also get deeply disappointed . other paid for their work .But not me.

2025-01-06 15:42 UTC, Aminadev2 commented
Good Bye