feat: show discard dialog in case multimedia changes
ankidroid/Anki-Android pull request #17141
Opened 2024-09-26 08:27 UTC by criticalAY

## Purpose / Description
This PR completes a `TODO` shows a discard dialog in case there are changes i.e. user selects a media file

## How Has This Been Tested?
Google emulator 
![image](https://github.com/user-attachments/assets/d7afdf7a-b129-4b52-87cd-65de6835b98f)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-09-26 09:26 UTC, david-allison requested changes
Also needs a test or a `NeedsTest`

2024-09-26 09:26 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt
> +                    if (viewModel.currentMultimediaPath.value != null) {
As far as I understand it, we should be changing the `.enabled` property, rather than having "close" logic in the callback

2024-09-26 13:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt
> +                    if (viewModel.currentMultimediaPath.value != null) {
See this YouTube video: [Android Developers: Basics For System Back (@7:57)](https://www.youtube.com/watch?v=Elpqr5xpLxQ#t=7m57)

<img width="578" alt="Screenshot 2024-09-26 at 14 45 50" src="https://github.com/user-attachments/assets/45f7ee56-11d7-49cc-93cf-98bee8dba310">

Screenshot from 8:57

You don't want conditional logic inside the `OnBackPressedCallback`. Instead you want a reference to the `OnBackPressedCallback` and use conditional logic outside it to set/unset `.enabled`

2024-09-28 06:47 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt
> +                    if (viewModel.currentMultimediaPath.value != null) {
Ahhhh ok ok

2024-09-28 08:22 UTC, lukstbit commented on gradle/libs.versions.toml
> +androidGradlePlugin = "8.5.2"
No

2024-09-28 08:24 UTC, criticalAY commented on gradle/libs.versions.toml
> +androidGradlePlugin = "8.5.2"
Sorry about this one :)

2024-09-28 09:16 UTC, david-allison requested changes

2024-09-28 09:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt
> +                requireActivity().finish()
(I may be incorrect here, strongly encourage research and disagreement) 

This code would feel better as: 

* Disable the callback (stopping the ability for it to be re-enabled)
* Re-call the back dispatcher 

The system should be responsible for handing the back button, whether that is disposing of the current fragment, or finishing the activity

If the back dispatcher takes an active action, it means no other dispatchers can execute

If the fragment closes the activity, it may not be the right decision. The fragment should close, and the parent should make a decision on what to do based on the fragment closing + status

2024-09-29 03:44 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt
> +                requireActivity().finish()
You are correct on the fact that the system should handle the back press i.e.
`requireActivity().onBackPressedDispatcher.onBackPressed()`

and 

the callback can be disabled when back is dispatched

2024-09-29 04:02 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt
> +                requireActivity().finish()
I have updated the flow, read the correct flow for the same, this follows the best practice

2024-09-30 13:08 UTC, david-allison approved these changes

2024-09-30 13:09 UTC, david-allison commented
Thanks so much!!!!

2024-09-30 15:27 UTC, mikehardy approved these changes
thank you!

2024-09-30 15:43 UTC, merged