Fix FixedPreferencesTitleLength
ankidroid/Anki-Android pull request #17221
Opened 2024-10-10 01:57 UTC by Arthur-Milchior

I tried to remove a `maxLength="41"` and lint was still succesful.

I finally took the time to learn how the linter works, after having years where it is a mystery.

Given that the code was not very clear to me, I added comments, and rewrote part of it.

I then realized that the issue was that, if the string was not found, no error was recorded. Strings may be missing either:
* because the string is hard coded in English (developer options), in which case I explicitly decided to ignore the strings, or
* because the string is defined outside of 10-preferences.xml

As far as I can tell, even if the string is not purely a preference, the max length constraint should still be present outside of preferences.

I also updated the string so that, with maxLength less than 41, the lint still works. This is important because some strings are being used in Menu, where the maxLength is even shorter. A future PR should reuse this same code for menus.

I also rewrote slightly the error message, hopefully improving them. Admittedly, given that only developers will see the errors, it was not that important a change.

Finally, of course, I added the maxLength to every strings that were found by the linter.

2024-10-10 03:57 UTC, david-allison requested changes
Thanks!!

Blockers:

* Add some unit tests to make the PR easier to review
* Remove the 'shouldn't happen' check: it's an exceptional case and a crash is better than adding to the runtime of all checks

2024-10-10 03:57 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
> +            if (!titleAttribute.startsWith("@string/")) {
Don't we want to ignore the dev options resource file? 

Likely with a `tools:ignore=` in the xml, rather than in this file.

2024-10-10 03:57 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
> +            val stringName = titleAttribute.substring(8)
I believe this would be more readable as: `.substringAfter("android:")`

2024-10-10 03:57 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
>              }
YAGNI, I'd remove this as it adds to the runtime of the lint check.

Lint is on the critical path in `Sync Translations`

2024-10-10 03:57 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
> +            "string" == element.tagName
Confirming: you've considered 'plurals' and this is handled as it was previously?

2024-10-10 03:57 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
> +            stringResources[element.getAttribute(ATTR_NAME)] = Pair(element, handle)
If you're adding comments, sample data here and on the variable would help

Since this check was originally written in Java, we can probably do much better in Kotlin

2024-10-10 03:57 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
> +     * String resources
Give an example

2024-10-10 03:57 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
> +     * Titles of the resources in the xml/ folder.
Give an example

2024-10-10 04:04 UTC, Arthur-Milchior commented
Added a second commit for the menu entries. I'll look at @david-allison 's feedback tomorrow.

2024-10-10 04:16 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedResourcesTitleLength.kt
> +class FixedResourcesTitleLength : ResourceXmlDetector(), XmlScanner {
This is no longer seen as a rename in GitHub, we'll likely lose the source history

2024-10-10 11:24 UTC, Arthur-Milchior commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
> +            if (!titleAttribute.startsWith("@string/")) {
It's not clear to me what you actually want to do here.
Because I still think that adding the string to the set is a bad idea. It's better to do an early return.
If the string is a constant instead outside of the dev options, I hope other lint test will find it.

2024-10-10 11:24 UTC, Arthur-Milchior commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
> +            val stringName = titleAttribute.substring(8)
Done

2024-10-10 11:26 UTC, Arthur-Milchior commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
> +            "string" == element.tagName
We are dealing with titles. As far as I can see, the title is a constant, it can't take a number parameter.
This is indeed a change. I don't expect it'll be an issue.

2024-10-10 11:28 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
> +            if (!titleAttribute.startsWith("@string/")) {
You can ignore specific lint rules in the XML, we should ignore it in the XML file, rather than inside the Kotlin code

2024-10-10 12:53 UTC, Arthur-Milchior reviewed
I decided to keep "Preferences" in the lint file name. Otherwise git does not recognize it as a renaming operation

2024-10-10 12:53 UTC, Arthur-Milchior commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
> +            stringResources[element.getAttribute(ATTR_NAME)] = Pair(element, handle)
I rewrote it to be slightly shorter. Not sure whether that's what you had in mind or what sample you meant

2024-10-12 03:14 UTC, david-allison requested changes
Commit number 2:

It would be better to use the same `Issue` for both checks. 

We have a lot of strings, and ideally want to keep these lint checks fast

----

I do not expect the following patch to be used, but take a look to see if there's anything you like in it:

```patch
Subject: [PATCH] fix: silent crash on startup due to fatal error

A fatal error was a `RuntimeException`, as `Error` only
catches `Error` and not `Exception`, this was not caught

Now, a 'collection not opened' dialog appears

This also fixes the same issue in `DebugInfoService`

Fixes 16963
---
Index: lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt b/lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt
--- a/lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt	(revision 3da98cc7ccb7ae6d14b6fc2a91c6b911d7759273)
+++ b/lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt	(date 1728701975078)
@@ -99,8 +99,8 @@
                 TestFiles.xml("res/values/01-core.xml", strings1XmlInvalid)
             )
             .issues(
-                FixedPreferencesTitleLength.PREFERENCES_ISSUE_TITLE_LENGTH,
-                FixedPreferencesTitleLength.PREFERENCES_ISSUE_MAX_LENGTH
+                FixedPreferencesTitleLength.TITLE_LENGTH_EXCEEDED,
+                FixedPreferencesTitleLength.INVALID_MAX_LENGTH
             )
             .run()
             .expectErrorCount(3)
@@ -128,8 +128,8 @@
                 TestFiles.xml("res/values/01-core.xml", strings1XmlValid)
             )
             .issues(
-                FixedPreferencesTitleLength.PREFERENCES_ISSUE_MAX_LENGTH,
-                FixedPreferencesTitleLength.PREFERENCES_ISSUE_TITLE_LENGTH
+                FixedPreferencesTitleLength.INVALID_MAX_LENGTH,
+                FixedPreferencesTitleLength.TITLE_LENGTH_EXCEEDED
             )
             .run()
             .expectClean()
Index: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt b/lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
--- a/lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt	(revision 3da98cc7ccb7ae6d14b6fc2a91c6b911d7759273)
+++ b/lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt	(date 1728702786307)
@@ -41,30 +41,25 @@
 class FixedPreferencesTitleLength : ResourceXmlDetector(), XmlScanner {
     companion object {
         private const val PREFERENCES_ID_TITLE_LENGTH = "FixedPreferencesTitleLength"
-        private const val MENU_ID_TITLE_LENGTH = "FixedMenuTitleLength"
 
         private const val PREFERENCES_ID_MAX_LENGTH = "PreferencesTitleMaxLengthAttr"
-        private const val MENU_ID_MAX_LENGTH = "MenuTitleMaxLengthAttr"
 
-        private const val PREFERENCES_TITLE_MAX_LENGTH = 41
-        private const val MENU_TITLE_MAX_LENGTH = 28
+        private const val PREFERENCES_DESCRIPTION_TITLE_LENGTH = "Strings used as titles should not be truncated"
 
-        private const val PREFERENCES_DESCRIPTION_TITLE_LENGTH = "Preference titles should be less than $PREFERENCES_TITLE_MAX_LENGTH characters"
-        private const val MENU_DESCRIPTION_TITLE_LENGTH = "Preference titles should be less than $MENU_TITLE_MAX_LENGTH characters"
-
-        private const val PREFERENCES_DESCRIPTION_MAX_LENGTH = """Preference titles should contain maxLength="$PREFERENCES_TITLE_MAX_LENGTH" attribute"""
-        private const val MENU_DESCRIPTION_MAX_LENGTH = """Preference titles should contain maxLength="$MENU_TITLE_MAX_LENGTH" attribute"""
+        private const val PREFERENCES_DESCRIPTION_MAX_LENGTH = """Preference titles should contain the maxLength attribute"""
 
         // Around 42 (resp. 29) characters is a hard max on emulators in preferences (resp. menu), likely smaller in reality, so use a buffer
-        private const val PREFERENCES_EXPLANATION_TITLE_LENGTH = "A preference title with more than $PREFERENCES_TITLE_MAX_LENGTH characters may fail to display on smaller screens"
-        private const val MENU_EXPLANATION_TITLE_LENGTH = "A menu title with more than $MENU_TITLE_MAX_LENGTH characters may fail to display on smaller screens"
+        private const val PREFERENCES_EXPLANATION_TITLE_LENGTH = "A long title may fail to display on smaller screens"
 
         // Read More: https://support.crowdin.com/file-formats/android-xml/
-        private const val PREFERENCES_EXPLANATION_MAX_LENGTH = "Preference Title should contain maxLength attribute because it fixes translated string length"
-        private const val MENU_EXPLANATION_MAX_LENGTH = "Preference Title should contain maxLength attribute because it fixes translated string length"
+        private const val PREFERENCES_EXPLANATION_MAX_LENGTH = "Titles should contain the maxLength attribute so our translators on Crowdin are aware of the limit"
 
         private val implementation = Implementation(FixedPreferencesTitleLength::class.java, Scope.RESOURCE_FILE_SCOPE)
-        val PREFERENCES_ISSUE_TITLE_LENGTH: Issue = Issue.create(
+
+        /**
+         * If `maxLength` is exceeded
+         */
+        val TITLE_LENGTH_EXCEEDED: Issue = Issue.create(
             PREFERENCES_ID_TITLE_LENGTH,
             PREFERENCES_DESCRIPTION_TITLE_LENGTH,
             PREFERENCES_EXPLANATION_TITLE_LENGTH,
@@ -73,17 +68,8 @@
             Constants.ANKI_XML_SEVERITY,
             implementation
         )
-        val MENU_ISSUE_TITLE_LENGTH: Issue = Issue.create(
-            MENU_ID_TITLE_LENGTH,
-            MENU_DESCRIPTION_TITLE_LENGTH,
-            MENU_EXPLANATION_TITLE_LENGTH,
-            Constants.ANKI_XML_CATEGORY,
-            Constants.ANKI_XML_PRIORITY,
-            Constants.ANKI_XML_SEVERITY,
-            implementation
-        )
 
-        val PREFERENCES_ISSUE_MAX_LENGTH: Issue = Issue.create(
+        val INVALID_MAX_LENGTH: Issue = Issue.create(
             PREFERENCES_ID_MAX_LENGTH,
             PREFERENCES_DESCRIPTION_MAX_LENGTH,
             PREFERENCES_EXPLANATION_MAX_LENGTH,
@@ -91,15 +77,6 @@
             Constants.ANKI_XML_PRIORITY,
             Constants.ANKI_XML_SEVERITY,
             implementation
-        )
-        val MENU_ISSUE_MAX_LENGTH: Issue = Issue.create(
-            MENU_ID_MAX_LENGTH,
-            MENU_DESCRIPTION_MAX_LENGTH,
-            MENU_EXPLANATION_MAX_LENGTH,
-            Constants.ANKI_XML_CATEGORY,
-            Constants.ANKI_XML_PRIORITY,
-            Constants.ANKI_XML_SEVERITY,
-            implementation
         )
         private const val ATTR_TITLE = "android:title"
         private const val ATTR_NAME = "name"
@@ -111,12 +88,7 @@
      * I.e. after the end of [visitElement], it contains
      * "pref__delete_unused_media_files__title" from src/main/res/xml/manage_space
      */
-    private val titlesOfPreferenceScreens: MutableSet<String> = HashSet()
-
-    /**
-     * Titles of the resources in the menu/ folder.
-     */
-    private val titlesOfMenuScreens: MutableSet<String> = HashSet()
+    private val resourceKeysUsedAsTitles: MutableSet<ResourceKey> = HashSet()
 
     /**
      * String resources.
@@ -133,58 +105,105 @@
     }
 
     override fun visitElement(context: XmlContext, element: Element) {
-        if (element.hasAttribute(ATTR_TITLE)) {
-            val folderName = context.file.parentFile.name
-            val titlesToHandle =
-                when (folderName) {
-             [...]

2024-10-12 03:14 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
> +            } else if (stringElement.getAttribute(ATTR_MAX_LENGTH) > maxLength.toString()) {
`stringElement.getAttribute(ATTR_MAX_LENGTH) > maxLength.toString()` 

Is doing arithmetic operations on strings

2024-10-12 03:14 UTC, david-allison commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt
>      fun showsErrorForInvalidFile() {
I would expect more tests, rather than significant editing of existing tests, unless the existing tests are incorrect

2024-10-13 02:28 UTC, Arthur-Milchior commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt
> +        val strings10XmlValid = """<resources>
This change is required because we want to have multiple files. So the name should be more specific

2024-10-13 02:28 UTC, Arthur-Milchior commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt
> +    <string name="button_sync" maxLength="28">button_sync</string>
This change is required because I want to test that smaller maxLength don't trigger the linter!

2024-10-13 02:28 UTC, Arthur-Milchior commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt
> +<!--This preference's title should have a maxLength attribute-->
This change is not required, but I thought the phrasing was not proper English, so this still seems like an improvement

2024-10-13 02:28 UTC, Arthur-Milchior commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt
> -    <string name="more_characters_than_limit"  maxLength="41">This String contains character more than limit £</string>
The comment state that it contains UTF-8 character.. This is not relevant to the linter. I preferred to split the UTF-8 to another string. I could also just remove it. 
Still, I really didn't want to keep a comment that seems to indicate that the issue is different from what it actually is

2024-10-13 02:28 UTC, Arthur-Milchior commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt
> +        val preferenceString =
Technically, I could keep a two preference strings. However, I believe it's cleaner to have a single one, as the lint we are actually testing are in the string files and not the preferences, there is no reason to have two distinct preferences here

2024-10-13 02:28 UTC, Arthur-Milchior commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt
> +                """res/values/01-core.xml:5: Error: Preference title 'checkbox_title' must be less than 41 characters (currently 46). [FixedPreferencesTitleLength]
This change is required because, to test multiple files, I actually have to change the file name sometime. Also the change in size of the string is caused by the removal of the unicode character as explained above

2024-10-13 02:28 UTC, Arthur-Milchior commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt
>      fun showsErrorForInvalidFile() {
I tried to explain everywhere why I think the changes improve the code clarity.
I think the code were badly done and this is worth improving the tests

2024-10-13 02:28 UTC, Arthur-Milchior commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt
> +<!--Its maxLength attribute is greater than 41-->
This seems like an improvement. It states the issue is being greater than 41. There is nothing specific with 55.

2024-10-13 02:28 UTC, Arthur-Milchior commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
> +            if (!titleAttribute.startsWith("@string/")) {
But where do you want the `tools:ignore=`?
The three remaining issues location are in the string files. So, logically, the only relevant `tools:ignore=` for this linter should be in the string files.

If the issue is that the preferences uses a hard coded string instead of a string resource, it means the issue's location can only be the preferences itself. So I would need an issue specifically for strings which are not associated to a resources. Which I created in the previous version of the commit, and you told me to remove.

Admittedly, I think this issue would be in practice useless, as I wrote, because:
* either the string is actually a constant, and the linter would already warn us about that, unless we explicitly ignored it
* or the string is a reference but there is no associated value in `values/`, in which case build would just fail.

If there is a way for a file to state that it should be ignored by a detector's visit element, I don't know it. But `tools:ignore` does not seems the appropriate feature for it.

2024-10-13 02:34 UTC, Arthur-Milchior commented
I'm sorry, but I don't understand your point regarding the number of issue and how it relates to the speed of the linter.

If you look at api/IssueRegistry, you'll see that `createDetectors` iterate over all issues, and create the set of detectors and the set of implementations. Given that, in this case, all issues use the same detector and implementation, there is no lost time there.

This, by the way, is consistent with the fact that issues are not reported multiple times. If the issue's implementation were executed once by issue, we should get the report for all issues three time.

I could hear that, if we ever had a third limit for a third kind of title, that would state to make a lot of code repetition.
In this case, I think it's worth it. Because the issue description must be a constant. If this constant considered multiple cases, and explained the difference in maxLength between title depending on the class, that would create a very long description , not easy to understand by most developers

2024-10-14 01:19 UTC, david-allison approved these changes

2024-10-14 01:27 UTC, david-allison requested changes
You're right. Thanks so much for the clarification, and sorry about the time lost

But this needs work. Even after the following patch, lint fails for me

```patch
Subject: [PATCH] a
---
Index: AnkiDroid/src/main/res/values/01-core.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/res/values/01-core.xml b/AnkiDroid/src/main/res/values/01-core.xml
--- a/AnkiDroid/src/main/res/values/01-core.xml	(revision f6d9bcbfe3db41320805f961952c729d195acf29)
+++ b/AnkiDroid/src/main/res/values/01-core.xml	(date 1728868844275)
@@ -21,7 +21,7 @@
 <resources xmlns:tools="http://schemas.android.com/tools">
     <!-- Navigation drawer items-->
     <string name="decks" maxLength="28">Decks</string>
-    <string name="card_browser" maxLength="28"comment="The usage of card browser inside the app (note the casing)">Card browser</string>
+    <string name="card_browser" maxLength="28" comment="The usage of card browser inside the app (note the casing)">Card browser</string>
     <string name="statistics" maxLength="28">Statistics</string>
     <string name="settings" maxLength="28">Settings</string>
     <string name="help" maxLength="28">Help</string>
@@ -60,7 +60,7 @@
     <string name="ease_button_good" maxLength="41">Good</string>
     <string name="ease_button_easy">Easy</string>
     <string name="menu_import" maxLength="28">Import</string>
-    <string name="undo" maxLength="28"comment="When tapping on this text, the last action is undone.">Undo</string>
+    <string name="undo" maxLength="28" comment="When tapping on this text, the last action is undone.">Undo</string>
     <string name="redo" maxLength="28">Redo</string>
     <string name="undo_action_whiteboard_last_stroke" comment="One of the display patterns of 'Undo' item on the action menu in Reviewer. It is shown as the title of the item when the whiteboard (handwriting) feature is enabled and visible and has any strokes (handwritten lines)" maxLength="28">Undo stroke</string>
     <string name="move_all_to_deck">Move all to deck</string>
Index: AnkiDroid/src/main/res/values/07-cardbrowser.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/res/values/07-cardbrowser.xml b/AnkiDroid/src/main/res/values/07-cardbrowser.xml
--- a/AnkiDroid/src/main/res/values/07-cardbrowser.xml	(revision f6d9bcbfe3db41320805f961952c729d195acf29)
+++ b/AnkiDroid/src/main/res/values/07-cardbrowser.xml	(date 1728868874806)
@@ -50,7 +50,7 @@
     <string name="card_browser_list_my_searches_remove_content">Delete “%1$s”?</string>
     <string name="card_browser_change_display_order" maxLength="28">Change display order</string>
     <string name="card_browser_search_hint" comment="Message displayed in the search text field in the card browser.">Search</string>
-    <string name="card_browser_cram_search" maxLength="28"comment = "Menu entry to start a search.">Search</string>
+    <string name="card_browser_cram_search" maxLength="28" comment="Menu entry to start a search.">Search</string>
     <string name="card_browser_change_display_order_title">Choose display order</string>
     <string name="card_details_tags">Tags</string>
     <string-array name="card_browser_order_labels">
```

```
Execution failed for task ':AnkiDroid:lintAnalyzeAmazonDebug'.
> A failure occurred while executing com.android.build.gradle.internal.lint.AndroidLintWorkAction
   > Unexpected failure during lint analysis (this is a bug in lint or one of the libraries it depends on)
     
     Message: Unexpected failure during lint analysis (this is a bug in lint or one of the libraries it depends on)
     
     
     The crash seems to involve the detector \`com.ichi2.anki.lint.rules.FixedPreferencesTitleLength\`.
     You can try disabling it with something like this:
         android {
             lint {
                 disable "PreferencesTitleMaxLengthAttr", "MenuTitleMaxLengthAttr", "FixedPreferencesTitleLength", "FixedMenuTitleLength"
             }
         }
     
     Stack: \`NullPointerException:FixedPreferencesTitleLength.checkFolder(FixedPreferencesTitleLength.kt:172)←FixedPreferencesTitleLength.afterCheckEachProject(FixedPreferencesTitleLength.kt:166)←LintDriver$checkProject$1.run(LintDriver.kt:1075)←LintClient.runReadAction(LintClient.kt:1781)←LintDriver$LintClientWrapper.runReadAction(LintDriver.kt:2747)←LintDriver.checkProject(LintDriver.kt:1074)←LintDriver.checkProjectRoot(LintDriver.kt:622)←LintDriver.access$checkProjectRoot(LintDriver.kt:174)←LintDriver$analyzeOnly$1.invoke(LintDriver.kt:445)←LintDriver$analyzeOnly$1.invoke(LintDriver.kt:442)←LintDriver.doAnalyze(LintDriver.kt:501)←LintDriver.analyzeOnly(LintDriver.kt:442)←LintCliClient$analyzeOnly$1.invoke(LintCliClient.kt:258)←LintCliClient$analyzeOnly$1.invoke(LintCliClient.kt:255)←LintCliClient.run(LintCliClient.kt:312)←LintCliClient.analyzeOnly(LintCliClient.kt:255)←Main.run(Main.java:1766)←Main.run(Main.java:282)←DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)←Method.invoke(Method.java:580)←AndroidLintWorkAction.invokeLintMainRunMethod(AndroidLintWorkAction.kt:103)←AndroidLintWorkAction.runLint(AndroidLintWorkAction.kt:90)←AndroidLintWorkAction.execute(AndroidLintWorkAction.kt:64)←DefaultWorkerServer.execute(DefaultWorkerServer.java:63)←NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)←NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)←ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)←NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)←AbstractWorker$1.call(AbstractWorker.java:44)←AbstractWorker$1.call(AbstractWorker.java:41)←DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)←DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)←DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)←DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)←DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)←DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)←DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)←AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)←NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)←DefaultWorkerExecutor.lambda$submitWork$0(DefaultWorkerExecutor.java:174)←FutureTask.run(FutureTask.java:317)←DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:194)←DefaultConditionalExecutionQueue$ExecutionRunner.access$700(DefaultConditionalExecutionQueue.java:127)←DefaultConditionalExecutionQueue$ExecutionRunner$1.run(DefaultConditionalExecutionQueue.java:169)←Factories$1.create(Factories.java:31)←DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:263)←DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:127)←DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:132)←DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)←DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:133)←Executors$RunnableAdapter.call(Executors.java:572)←FutureTask.run(FutureTask.java:317)←ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)←AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)←ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)←ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)←Thread.run(Thread.java:1583)\`
     
     You can run with --stacktrace or set environment variable \`LINT_PRINT_STACKTRACE=true\` to dump a full stacktrace to stdout.
     Stack: `Runt [...]

2024-10-14 01:28 UTC, david-allison commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
> +            if (!titleAttribute.startsWith("@string/")) {
You're right. Too much hassle here

2024-10-16 01:35 UTC, Arthur-Milchior commented
Corrected

2024-10-16 03:52 UTC, david-allison requested changes
```
     Stack: \`NullPointerException:FixedPreferencesTitleLength.checkFolder(FixedPreferencesTitleLength.kt:172)←FixedPreferencesTitleLength.afterCheckEachProject(FixedPreferencesTitleLength.kt:166)←LintDriver$checkProject$1.run(LintDriver.kt:1075)←LintClient.runReadAction(LintClient.kt:1781)←LintDriver$LintClientWrapper.runReadAction(LintDriver.kt:2747)←LintDriver.checkProject(LintDriver.kt:1074)←LintDriver.checkProjectRoot(LintDriver.kt:622)←LintDriver.access$checkProjectRoot(LintDriver.kt:174)←LintDriver$analyzeOnly$1.invoke(LintDriver.kt:445)←LintDriver$analyzeOnly$1.invoke(LintDriver.kt:442)←LintDriver.doAnalyze(LintDriver.kt:501)←LintDriver.analyzeOnly(LintDriver.kt:442)←LintCliClient$analyzeOnly$1.invoke(LintCliClient.kt:258)←LintCliClient$analyzeOnly$1.invoke(LintCliClient.kt:255)←LintCliClient.run(LintCliClient.kt:312)←LintCliClient.analyzeOnly(LintCliClient.kt:255)←Main.run(Main.java:1766)←Main.run(Main.java:282)←DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)←Method.invoke(Method.java:580)←AndroidLintWorkAction.invokeLintMainRunMethod(AndroidLintWorkAction.kt:103)←AndroidLintWorkAction.runLint(AndroidLintWorkAction.kt:90)←AndroidLintWorkAction.execute(AndroidLintWorkAction.kt:64)←DefaultWorkerServer.execute(DefaultWorkerServer.java:63)←NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)←NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)←ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)←NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)←AbstractWorker$1.call(AbstractWorker.java:44)←AbstractWorker$1.call(AbstractWorker.java:41)←DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)←DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)←DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)←DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)←DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)←DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)←DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)←AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)←NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)←DefaultWorkerExecutor.lambda$submitWork$0(DefaultWorkerExecutor.java:174)←FutureTask.run(FutureTask.java:317)←DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:194)←DefaultConditionalExecutionQueue$ExecutionRunner.access$700(DefaultConditionalExecutionQueue.java:127)←DefaultConditionalExecutionQueue$ExecutionRunner$1.run(DefaultConditionalExecutionQueue.java:169)←Factories$1.create(Factories.java:31)←DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:263)←DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:127)←DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:132)←DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)←DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:133)←Executors$RunnableAdapter.call(Executors.java:572)←FutureTask.run(FutureTask.java:317)←ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)←AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)←ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)←ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)←Thread.run(Thread.java:1583)\`
     
     You can run with --stacktrace or set environment variable \`LINT_PRINT_STACKTRACE=true\` to dump a full stacktrace to stdout.
     Stack: `RuntimeException:LintDriver$Companion.handleDetectorError(LintDriver.kt:3740)←LintDriver$Companion.handleDetectorError$default(LintDriver.kt:3607)←LintDriver$Companion.handleDetectorError(LintDriver.kt:3603)←LintDriver$analyzeOnly$1.invoke(LintDriver.kt:447)←LintDriver$analyzeOnly$1.invoke(LintDriver.kt:442)←LintDriver.doAnalyze(LintDriver.kt:501)←LintDriver.analyzeOnly(LintDriver.kt:442)←LintCliClient$analyzeOnly$1.invoke(LintCliClient.kt:258)←LintCliClient$analyzeOnly$1.invoke(LintCliClient.kt:255)←LintCliClient.run(LintCliClient.kt:312)←LintCliClient.analyzeOnly(LintCliClient.kt:255)←Main.run(Main.java:1766)←Main.run(Main.java:282)←DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)←Method.invoke(Method.java:580)←AndroidLintWorkAction.invokeLintMainRunMethod(AndroidLintWorkAction.kt:103)←AndroidLintWorkAction.runLint(AndroidLintWorkAction.kt:90)←AndroidLintWorkAction.execute(AndroidLintWorkAction.kt:64)←DefaultWorkerServer.execute(DefaultWorkerServer.java:63)←NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)←NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)←ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)←NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)←AbstractWorker$1.call(AbstractWorker.java:44)←AbstractWorker$1.call(AbstractWorker.java:41)←DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)←DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)←DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)←DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)←DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)←DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)←DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)←AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)←NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)←DefaultWorkerExecutor.lambda$submitWork$0(DefaultWorkerExecutor.java:174)←FutureTask.run(FutureTask.java:317)←DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:194)←DefaultConditionalExecutionQueue$ExecutionRunner.access$700(DefaultConditionalExecutionQueue.java:127)←DefaultConditionalExecutionQueue$ExecutionRunner$1.run(DefaultConditionalExecutionQueue.java:169)←Factories$1.create(Factories.java:31)←DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:263)←DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:127)←DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:132)←DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)←DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:133)←Executors$RunnableAdapter.call(Executors.java:572)←FutureTask.run(FutureTask.java:317)←ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)←AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)←ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)←ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)←Thread.run(Thread.java:1583)`
```

I'll timebox a little to look into this

2024-10-16 04:06 UTC, david-allison requested changes
@Arthur-Milchior 

```patch
Subject: [PATCH] 
---
Index: lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt b/lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt
--- a/lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt	(revision 02778a7318e1a9cd4a4d7539d3a20e9ae8c0ecf4)
+++ b/lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt	(date 1729051530391)
@@ -89,6 +89,17 @@
 </PreferenceScreen>"""
     }
 
+    @Language("XML")
+    val preferenceWithHardcodedTitle = """
+        <PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android"
+            android:title="Dev options"
+            android:key="@string/pref_dev_options_screen_key">
+            <SwitchPreferenceCompat
+                android:title="New congrats screen"
+                android:key="@string/new_congrats_screen_pref_key"
+                android:defaultValue="false"/>
+        </PreferenceScreen>"""
+
     @Test
     fun showsErrorForInvalidFile() {
         TestLintTask.lint().allowMissingSdk()
@@ -134,4 +145,20 @@
             .run()
             .expectClean()
     }
+
+    @Test
+    fun hardcodedTitleIsNotFlagged() {
+        TestLintTask.lint().allowMissingSdk()
+            .allowCompilationErrors()
+            .files(
+                TestFiles.xml("res/xml/preference_general_valid.xml", preferenceWithHardcodedTitle),
+                TestFiles.xml("res/values/01-core.xml", strings1XmlValid),
+            )
+            .issues(
+                FixedPreferencesTitleLength.PREFERENCES_ISSUE_MAX_LENGTH,
+                FixedPreferencesTitleLength.PREFERENCES_ISSUE_TITLE_LENGTH
+            )
+            .run()
+            .expectClean()
+    }
 }
Index: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt b/lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
--- a/lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt	(revision 02778a7318e1a9cd4a4d7539d3a20e9ae8c0ecf4)
+++ b/lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt	(date 1729051439168)
@@ -145,7 +145,7 @@
              */
             // Removing the "@string/" part.
             val titleAttribute = element.getAttribute(ATTR_TITLE)
-            val stringName = titleAttribute.substringAfter("@string/")
+            val stringName = titleAttribute.substringAfter("@string/", "").ifEmpty { return }
             // the entry `stringName` may already exists. Losing the first entry is not an issue, as it won't actually hide that there are issues.
             titlesToHandle.add(stringName)
             return
@@ -169,7 +169,7 @@
 
     fun checkFolder(context: Context, titles: Set<String>, missingMaxLengthIssueIssue: Issue, wrongMaxLengthIssue: Issue, stringTooLongIssue: Issue, folder: String, maxLength: Int) {
         for (title in titles) {
-            val stringHandle = stringResources[title]!!
+            val stringHandle = stringResources[title] ?: throw IllegalArgumentException(title)
             val stringElement: Element = stringHandle.clientData as Element
             if (!stringElement.hasAttribute(ATTR_MAX_LENGTH)) {
                 val message = String.format(Locale.ENGLISH, "$folder title '%s' is missing maxLength=\"%d\" attribute.", title, maxLength)

```

2024-10-19 17:29 UTC, david-allison commented
```
> Task :lint-rules:ktlintTestSourceSetCheck FAILED
/home/runner/work/Anki-Android/Anki-Android/lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt:1:1 File must end with a newline (\n)
/home/runner/work/Anki-Android/Anki-Android/lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt:155:74 Unnecessary trailing comma before ")"
```

2024-10-23 04:35 UTC, david-allison commented
I've fixed the lint error and force pushed so we can get this in

2024-10-23 13:52 UTC, lukstbit approved these changes
Tested the behavior of the updated checks, LGTM.
As David fixed the conflicts and provided the initial approval I'm merging this now.

2024-10-23 14:10 UTC, merged

2024-10-26 19:31 UTC, Arthur-Milchior commented
Thank you David