Help solving "All card options show (end)"
ankidroid/Anki-Android pull request #17234
Opened 2024-10-11 17:16 UTC by RobozinhoD

## Purpose / Description

I tried to solve #15611 by doing [what David asked](https://github.com/ankidroid/Anki-Android/issues/15611#issuecomment-1985742924):

> This issue will be closed when the following method is updated to use the backend:

https://github.com/ankidroid/Anki-Android/blob/3775853baabe202f9d2c975a10754f229b89bf9c/AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt#L96-L114

I updated the methods to match Anki and use the backend, but I still see the `(end)` message. Despite of the fact that I didn't manage to completely fix the issue, I'm posting this PR because it updates libanki and can help someone else

## Fixes
* Fixes part of #15611

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-10-11 17:25 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
> +            onNewDeckCreated(newDeckId!!)
I really don't like to see `!!` added in any new code, is there any possible thing we can do to avoid that?

Change the contracts of the method producing the val so it is known to be not-null? 
Change the method call so that we have accept it might be null and provide a default value if it is, *if that makes sense* (it may not make sense in this context)
Check for null and avoid work that makes no sense in a null val context ?

2024-10-11 17:25 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
> +                decks.rename(decks.get(deckId!!)!!, newName)
same - I see `!!` and I just think 😬  we're avoiding doing work now that will be some really really obscure crash bug 2 years from now that we have forgotten

2024-10-11 17:25 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +                    did = col.decks.id(deckName)!!
same

2024-10-11 17:27 UTC, mikehardy requested changes
main problem for me is that in new code, especially libanki area, seeing !! is really really worrisome for me. To be avoided if at all possible

2024-10-11 20:27 UTC, david-allison requested changes
```

> Task :AnkiDroid:compilePlayReleaseAndroidTestKotlin FAILED
e: file:///home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt:121:33 Argument type mismatch: actual type is 'kotlin.Long?', but 'kotlin.Long' was expected.
e: file:///home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt:122:61 Argument type mismatch: actual type is 'kotlin.Long?', but 'kotlin.Long' was expected.
```

2024-10-11 20:54 UTC, david-allison requested changes

2024-10-11 20:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
>      }
This should not return `DeckId?` if `create == true`. I'm willing to break 'hard' libAnki compat here

Best option: Can we use code contracts: either `contract { }`, or `@Contract("")`. I'm happy to take responsibility for introducing an experimental feature

If not: can we split the method into multiple overrides, most of which return the non-nullable?

2024-10-12 00:07 UTC, RobozinhoD commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
>      }
I haven't managed to use contracts so I split in an override. Please take a look

2024-10-12 01:48 UTC, david-allison approved these changes
To note: `newDeckLegacy` still needs work

But... this is better than it was, so +1 & approval

2024-10-12 09:27 UTC, BrayanDSO approved these changes
LGTM

2024-10-12 13:26 UTC, merged

2024-10-12 16:20 UTC, mikehardy commented
> Comments addressed

🤷  ehhh, this PR adds two `!!`s in libanki code. Crash reports in 3....2...

2024-10-12 18:54 UTC, BrayanDSO commented
> 🤷 ehhh, this PR adds two !!s in libanki code. Crash reports in 3....2...

Sorry, I only paid attention to your comments at `CreateDeckDialog` and `CardContentProvider`, which were addressed.

The `!!` at the new `id()` method is safe and the method has a `NotInLibanki` annotation. Maybe a comment there to warn people from the future would help if you are concerned.

The other `!!` in `newFiltered` is already marked by the IDE as unnecessary and was an oversight

2024-10-12 19:32 UTC, mikehardy commented
> The !! at the new id() method is safe

🧐 I am perhaps too suspicious but...I am *always* suspicious of null pointer exception... so I looked at this and I agree with you - it will create a deck of that name if it doesn't exist so it should never return null.

I suppose the only way to get a method with a non-`?` return type to avoid the `!!` would be to decompose the id() call further such that one was basically the "create = true" version and one was the "create = false so can return null" version. Not super important but does require inspection to satisfy the suspicious

> The other !! in newFiltered is already marked by the IDE as unnecessary and was an oversight

That's good at least

Okay, I'm good then, you were right "comments addressed" ✅  thanks man 🫡