Added the button to copy stack trace and debug info
ankidroid/Anki-Android pull request #17279
Opened 2024-10-18 18:46 UTC by Aditya13s

## Purpose / Description
The purpose of this pr is to add a button in Error Dialog to copy stack track and debug info.

## Fixes
* Fixes #17232

## Approach
The approach is to first pass the exception from `InitialActivity` to `DeckPicker` by converting the `StartupFailure` enum into a sealed class and adding an exception parameter to each class inside the `StartupFailure` sealed class. Then, in the `DeckPicker` class, a companion object is created to store the exception. Finally, in the `DatabaseErrorDialog`, the companion object is accessed and used in the `copyStackTraceAndDebugInfo` function.

## How Has This Been Tested?
This change has been tested for database errors.

## Screenshots
![ErrorDialog](https://github.com/user-attachments/assets/963ec842-929e-492f-aa27-0a3e80956fd3)

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-10-18 20:09 UTC, david-allison commented
Tests are falling

2024-10-19 14:48 UTC, Aditya13s commented
@david-allison all tests are passed

2024-10-19 20:47 UTC, david-allison requested changes
Main blocker is the complexity of the additional variable in the Deck Picker

2024-10-19 20:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +        var exception: Exception? = null
This shouldn't be necessary

2024-10-19 20:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +    sealed class StartupFailure {
Great!

2024-10-19 20:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +    private fun copyStackTraceAndDebugInfo() {
Pass on the exception here, don't use a global

2024-10-19 20:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +    private fun copyStackTraceAndDebugInfo() {
It would probably be better to make this `suspend`

2024-10-19 20:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +            val debugInfo = withContext(NonCancellable) {
Is this withContext necessary?

2024-10-19 20:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +    private fun copyStackTraceAndDebugInfo() {
I'd spend a bit more time simplifying this. It's about 2.5x longer than it needs to be

2024-10-20 07:04 UTC, Aditya13s commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +    private fun copyStackTraceAndDebugInfo() {
I tried to pass the exception with bundle using the newInstance() function in DatabaseErrorDialog but it showing null when i try to fetch the exception passed through the bundle

2024-10-20 07:11 UTC, Aditya13s commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +            val debugInfo = withContext(NonCancellable) {
withContext is not necessary it can also work without withContext but i found out that the AboutFragment.kt is calling the function like this so I used that.
```
private fun copyDebugInfo() {
        launchCatchingTask {
            val debugInfo = withContext(Dispatchers.IO) {
                DebugInfoService.getDebugInfo(requireContext())
            }
            requireContext().copyToClipboard(
                debugInfo,
                failureMessageId = R.string.about_ankidroid_error_copy_debug_info
            )
        }
    }
```

2024-10-20 12:12 UTC, Aditya13s commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +    private fun copyStackTraceAndDebugInfo() {
Is it necessary to also add suspend keyword here? `DebugInfoService.getDebugInfo()` is also a suspend function.

`suspend fun getDebugInfo(info: Context): String `

2024-10-23 16:54 UTC, Aditya13s commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +    private fun copyStackTraceAndDebugInfo() {
How can I measure the performance of this function?

2024-10-23 19:06 UTC, david-allison commented
Not 1. Don't use mutable globals

2024-10-24 19:11 UTC, Aditya13s commented
@david-allison please review the changes.

2024-10-28 02:02 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +    private fun requireException() = BundleCompat.getParcelable(
This seems wrong to me. `require` means that you promise the value exists, and are okay with crashing the app otherwise.
Here, you use a method that returns a nullable value. Which you could realize if you added typing indication ` : CustomException`.


So, either you must rename the function, maybe to just `exception()`, or you should add `!!` at the end.

In any case, you must add documentation to explain what is the expected result, when it returns null, so that I can easily reivew and check whether your implementation is consistent with your documentation please

2024-10-28 02:27 UTC, Arthur-Milchior reviewed
Many way to improve the code. And, given that we are dealing with exception handling, with the time when AnkiDroid had an issue, I really want to be certain of the code we merge here, so sorry if I got to ask many changes or explanations.

> This change has been tested for database errors.

I'm sorry but I don't understand what it means. In  particular, I can't reproduce it.

Can you put a video instead of a picture, so that we can see what was actually copied (please paste the result somewhere so we can see it) or at least explain how to reproduce your testing.

2024-10-28 02:27 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +        "exception",
Please use string constant instead of strings literal. This way:
* I can be sure that there are no typos without having to check in details each letters
* It's easy to find all usage of this key through android-studio tools

2024-10-28 02:27 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +        val debugInfo = withContext(NonCancellable) {
I'd love a comment explaining why this task should be non cancellable. I've no idea what's going on.

2024-10-28 02:27 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +            DebugInfoService.getDebugInfo(requireActivity().applicationContext)
`requireContext()` does not work? It seems cleaner code

2024-10-28 02:27 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +    private fun copyStackTraceAndDebugInfo() {
If you really want an answer, don't mark as resolved. Otherwise you risk not being seen.

"necessary" not. But still seems good practice. Your function become easier to test when it's not in charge of creating a scope for the suspension. If you create a unit test for it, you can use the standard tools we have to test suspend functions.
Also, if at some time it must be used with other suspend function, that ensures that all functions are called in the same `launch`, and could potentially be cancelled together. If your method is not suspend, it restricts what is caller can do. And there seems to be no reason for that here.

2024-10-28 02:27 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +    private fun copyStackTraceAndDebugInfo() {
"2.5x longer" probably means the number of lines/instruction. Not the time it takes.
Honestly, I can't imagine David caring about the performance here. If it is called so many time that the performance is important, we have a huge problem with our application. 

Here is something that I wrote that seems, I believe, better Kotlin.
```kotlin
    private suspend fun copyStackTraceAndDebugInfo() {
        val stackTrace = requireException()?.stackTrace
        val debugInfo = withContext(NonCancellable) {DebugInfoService.getDebugInfo(requireContext())}
        val combinedInfo = if (stackTrace == null) {debugInfo} else {"$stackTrace\n$debugInfo"}

        requireContext().copyToClipboard(
            combinedInfo,
            failureMessageId = R.string.about_ankidroid_error_copy_debug_info
        )
    }
```

It's generally cleaner not to use any `var` if possible. And since here there are exactly two formatted you can want, this way of using only `val` seems nice. This way, you don't have to think about how `combinedInfo` evolves through the execution of the script.
Plus, using the `?.`, you don't need to reuse a `?` inside the `if`

2024-10-28 02:27 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            is DB_ERROR -> displayDatabaseFailure(CustomException(failure.exception!!.message!!, Log.getStackTraceString(failure.exception)))
I really don't like the `!!` in the exception handler.
If for some reason the message is missing or the exception is missing, the exception handler will fail and we won't be able to copy the stacktrace or do any of the previous clean-up. 
If you are 100% certain that the message is always here, please add a comment explaining why you are so sure.

2024-10-28 02:27 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        class DB_ERROR(val exception: Exception? = null) : StartupFailure()
Why do you default to null, why is the type nullable? Looking at the code, it seems that `DB_ERROR` is always called with a non-null exception.

2024-10-29 16:25 UTC, Aditya13s commented
> Many way to improve the code. And, given that we are dealing with exception handling, with the time when AnkiDroid had an issue, I really want to be certain of the code we merge here, so sorry if I got to ask many changes or explanations.
> 
> > This change has been tested for database errors.
> 
> I'm sorry but I don't understand what it means. In  particular, I can't reproduce it.
> 
> Can you put a video instead of a picture, so that we can see what was actually copied (please paste the result somewhere so we can see it) or at least explain how to reproduce your testing.

https://github.com/user-attachments/assets/25a02817-eea0-433a-897f-f8152c0d2a86

2024-10-29 16:28 UTC, Aditya13s commented
Exception Stack Trace

```
InitialActivity com.ichi2.anki.debug net.ankiweb.rsdroid.BackendException$BackendFatalError:
at com.ichi2.anki.CollectionManager$CollectionOpenFailure.triggerFailure(CollectionManager.kt:420)
at com.ichi2.anki.CollectionManager.ensureOpenInner(CollectionManager.kt:241)
at com.ichi2.anki.CollectionManager.getColUnsafe$lambda$11$lambda$10(CollectionManager.kt:299)
at com.ichi2.anki.CollectionManager.$r8$lambda$1xvLXT2AdUAF2dT9vOLsddKVcWo(Unknown Source:0)
at com.ichi2.anki.CollectionManager$$ExternalSyntheticLambda2.invoke(D8$$SyntheticClass:0)
at com.ichi2.anki.CollectionManager$withQueue$3.invokeSuspend(CollectionManager.kt:103)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)

```

2024-10-30 17:16 UTC, Aditya13s commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +                                return@listItems
Thanks for your feedback! I missed the return in the first commit and added it in the second one. I'll be more careful in the future.

2024-10-31 00:57 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        class DB_ERROR(val exception: Exception? = null) : StartupFailure()
Why did you resolve this issue?
You have not answered (and in any case you should not answer if it's not answered)
And you have not updated the code.

Please, do not resolve issue, unless you just pushed new code following the advice given.

2024-10-31 00:58 UTC, Arthur-Milchior commented
I'm very sorry, but your video starts with "Collection not opened". This does not tell me how to reproduce it. Unless you want me to manually put a wrong file instead of the database file.

2024-10-31 02:59 UTC, Aditya13s commented
> I'm very sorry, but your video starts with "Collection not opened". This does not tell me how to reproduce it. Unless you want me to manually put a wrong file instead of the database file.

'''
Index: AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt IDEA additional info: Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP <+>UTF-8 =================================================================== diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt --- a/AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt	(revision dcf07cefcfff05fbe54615400a6e419b6f72c86d) +++ b/AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt	(date 1728647924463) @@ -64,7 +64,7 @@ * @see [CollectionOpenFailure] */ @VisibleForTesting - var emulatedOpenFailure: CollectionOpenFailure? = null + var emulatedOpenFailure: CollectionOpenFailure? = CollectionOpenFailure.FATAL_ERROR private val testMutex = ReentrantLock()
'''

2024-10-31 03:02 UTC, Aditya13s commented
> I'm very sorry, but your video starts with "Collection not opened". This does not tell me how to reproduce it. Unless you want me to manually put a wrong file instead of the database file.

* [fix: handle `BackendException$BackendFatalError` on startup #17231](https://github.com/ankidroid/Anki-Android/pull/17231)

2024-11-01 18:08 UTC, Aditya13s commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +            DebugInfoService.getDebugInfo(requireActivity().applicationContext)
`requireContext()` can also work

2024-11-01 19:00 UTC, Aditya13s commented
> I'm very sorry, but your video starts with "Collection not opened". This does not tell me how to reproduce it. Unless you want me to manually put a wrong file instead of the database file.

    @Arthur-Milchior please review the changes

2024-11-01 19:01 UTC, Aditya13s commented
@Arthur-Milchior please review the changes

2024-11-01 21:33 UTC, Arthur-Milchior commented
> > I'm very sorry, but your video starts with "Collection not opened". This does not tell me how to reproduce it. Unless you want me to manually put a wrong file instead of the database file.
> 
> * [fix: handle `BackendException$BackendFatalError` on startup #17231](https://github.com/ankidroid/Anki-Android/pull/17231)

I did look at the link, and see no reproduction step either. Please write sentences, explain what you mean here. This is not useful for me to reproduce

2024-11-01 21:43 UTC, Arthur-Milchior reviewed
Nice improvement, thank you.

2024-11-01 21:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +        val debugInfo = withContext(NonCancellable) {
What's the point? Even if you're done computing the whole debug info, it'll immediately be discarded.
As far as I can tell, when reading https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-non-cancellable/ , this only ensure that the code inside the `withContext` is not cancelled. If the coroutine is canceled, the return value of `getDebugInfo` will just get ignored.

I admit it seems to makes sense. Keep copying the data even if the user close the dialog. But in this case, I expect you'd need the `NonCancellable` to contains the whole `copyStackTraceAndDebugInfo`. 
For the sake of style, I'd state that you'd want to do `withContext(copyStackTraceAndDebugInfo) {copyStackTraceAndDebugInfo()}`.

Also, please add a comment around the `NonCancellable` to explain why we use it there. As far as I can tell, we use it nowhere else

2024-11-02 06:51 UTC, Aditya13s commented
> I did look at the link, and see no reproduction step either. Please write sentences, explain what you mean here. This is not useful for me to reproduce

In `CollectionManager.kt` line 67 

Replace this
`var emulatedOpenFailure: CollectionOpenFailure? = null`

with this
`var emulatedOpenFailure: CollectionOpenFailure? = CollectionOpenFailure.FATAL_ERROR`

2024-11-02 21:12 UTC, Arthur-Milchior commented
Thank you for the reproduction step. 
On a next occasion, I'd really appreciate if you could give them directly when you create the PR.


Thanks also for applying the change I requested.

2024-11-02 21:14 UTC, Arthur-Milchior approved these changes

2024-11-06 15:25 UTC, Aditya13s commented
@david-allison need second approval

2024-11-13 21:09 UTC, david-allison commented
Please remove the merge commits from this, and rebase so we can rebase merge it via the merge queue

2024-11-14 11:16 UTC, Aditya13s commented
@david-allison merge commit removed and rebased the changes.

2024-11-14 16:30 UTC, david-allison reviewed
Looks good. Please squash. The individual commits contain code which shouldn't make it to production (such as storing the exception in `DeckPicker` as a global)

2024-11-14 16:30 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                val message = failure.exception.message ?: "Database Error"
Add a comment that this isn't a user-facing string, so is fine to be a constant

Or extract to constants

2024-11-14 16:30 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +        // Key for passing a CustomException in the Bundle, containing error messages and stack trace
Use javadoc comments, not regular comments here

2024-11-14 16:30 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +    class CustomException(
Call it `CustomExceptionData`, by convention in Java, classes which end in `Exception` should be an instance of `Exception`, and this isn't (and shouldn't be)

2024-11-15 15:35 UTC, david-allison requested changes

2024-11-15 17:32 UTC, Aditya13s commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +    ) : Parcelable
What will be the max length of the message and stacktrace?

2024-11-16 13:57 UTC, Aditya13s commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +    ) : Parcelable
```
    @Parcelize
    class CustomExceptionData(
        val message: String,
        val stackTrace: String
    ) : Parcelable {

        companion object {
            private const val MAX_MESSAGE_LENGTH = 50
            private const val MAX_STACKTRACE_LENGTH = 2000
            
            fun fromException(exception: Exception): CustomExceptionData {
                val truncatedMessage = exception.message?.let {
                    if (it.length > MAX_MESSAGE_LENGTH) it.substring(0, MAX_MESSAGE_LENGTH) + "..." else it
                } ?: "No message"
    
                val stackTraceString = exception.stackTraceToString()
                val truncatedStackTrace = if (stackTraceString.length > MAX_STACKTRACE_LENGTH) {
                    stackTraceString.substring(0, MAX_STACKTRACE_LENGTH) + "..."
                } else {
                    stackTraceString
                }
    
                return CustomExceptionData(truncatedMessage, truncatedStackTrace)
            }
        }
    }
```
Is this correct?

2024-11-20 18:55 UTC, Aditya13s commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +    ) : Parcelable
Added the function fromException() that truncates the stack trace to a maximum of 2000 lines.

2024-12-04 01:10 UTC, david-allison reviewed
Only blocker is changing `exception()` to `val exceptionData`

The others are nice to haves. `exception()` isn't trivial to understand

2024-12-04 01:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +    open fun showDatabaseErrorDialog(errorDialogType: DatabaseErrorDialogType, exception: CustomExceptionData? = null) {
nit: `exceptionData`

2024-12-04 01:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            }
nit: the `{ }` shouldn't be necessary

2024-12-04 01:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +    private fun displayDatabaseFailure(exception: CustomExceptionData? = null) {
ditto: `exceptionData`

2024-12-04 01:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        object DISK_FULL : StartupFailure()
All of these show compiler weak warnings on the names

2024-12-04 01:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +    private fun exception(): CustomExceptionData? = BundleCompat.getParcelable(requireArguments(), EXCEPTION_KEY, CustomExceptionData::class.java)
`val exceptionData`

2024-12-04 01:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +        fun newInstance(dialogType: DatabaseErrorDialogType, exception: CustomExceptionData? = null): DatabaseErrorDialog {
`exceptionData`

2024-12-04 01:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +            }
```suggestion
            exception?.let { args.putParcelable(EXCEPTION_KEY, it) }
```

2024-12-04 01:10 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +
```suggestion
```

2024-12-04 01:10 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
> +        override fun showDatabaseErrorDialog(errorDialogType: DatabaseErrorDialogType, exception: DatabaseErrorDialog.CustomExceptionData?) {
`exceptionData`

2024-12-04 05:31 UTC, Aditya13s commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        object DISK_FULL : StartupFailure()
Should I change it to follow the Pascal naming convention? Like this: SDCardNotMounted.

2024-12-04 05:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        object DISK_FULL : StartupFailure()
Sure!

2024-12-04 06:19 UTC, david-allison requested changes
Looks great! Last one

2024-12-04 06:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +        val message: String,
`message` is unused. This feels like a bug

2024-12-04 06:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        object DISK_FULL : StartupFailure()
Looking great!

2024-12-04 07:07 UTC, david-allison requested changes
I would have expected you to use the `message` (and exception name). What's the reason it was removed?

Something along the lines of java.lang.OutOfMemoryError: Java heap space is often more useful for the end user, whereas the stack trace is more useful to developers

----

Could you add a quick unit test which transforms an exception into a `CustomExceptionData` with a few lenient assertions on the result? I'd want to make sure the exception message and class name is visible to the user

2024-12-04 08:29 UTC, Aditya13s commented
> Could you add a quick unit test which transforms an exception into a `CustomExceptionData` with a few lenient assertions on the result? I'd want to make sure the exception message and class name is visible to the user

@david-allison I don't have much experience with unit testing. Could you help me with that?

2024-12-06 01:12 UTC, david-allison commented
```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt	(revision 2923db6f276b1ec4cf9356d3efddf3b1012da477)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt	(date 1733447247127)
@@ -405,7 +405,7 @@
      * and copies the combines information to the Android clipboard.
      */
     private suspend fun copyStackTraceAndDebugInfo() {
-        val stackTrace = exceptionData?.stackTrace
+        val stackTrace = exceptionData?.toHumanReadableString()
         val debugInfo = DebugInfoService.getDebugInfo(requireContext())
         val combinedInfo = stackTrace?.let { "$it\n$debugInfo" } ?: debugInfo
 
@@ -683,10 +683,12 @@
     class CustomExceptionData(
         val stackTrace: String
     ) : Parcelable {
+        fun toHumanReadableString() = stackTrace
 
         companion object {
             private const val MAX_STACKTRACE_LINES = 2000
 
+            @CheckResult
             fun fromException(exception: Exception): CustomExceptionData {
                 val stackTraceLines = exception.stackTraceToString().lines()
                 val truncatedStackTrace = if (stackTraceLines.size > MAX_STACKTRACE_LINES) {
Index: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomExceptionDataTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomExceptionDataTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomExceptionDataTest.kt
new file mode 100644
--- /dev/null	(date 1733447538988)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomExceptionDataTest.kt	(date 1733447538988)
@@ -0,0 +1,40 @@
+/*
+ *  Copyright (c) 2024 David Allison <davidallisongithub@gmail.com>
+ *
+ *  This program is free software; you can redistribute it and/or modify it under
+ *  the terms of the GNU General Public License as published by the Free Software
+ *  Foundation; either version 3 of the License, or (at your option) any later
+ *  version.
+ *
+ *  This program is distributed in the hope that it will be useful, but WITHOUT ANY
+ *  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
+ *  PARTICULAR PURPOSE. See the GNU General Public License for more details.
+ *
+ *  You should have received a copy of the GNU General Public License along with
+ *  this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+package com.ichi2.anki.dialogs
+
+import com.ichi2.anki.dialogs.DatabaseErrorDialog.*
+import org.hamcrest.MatcherAssert.assertThat
+import org.hamcrest.Matchers.arrayWithSize
+import org.hamcrest.Matchers.containsString
+import org.hamcrest.Matchers.not
+import org.junit.Test
+
+/** Test of [DatabaseErrorDialog.CustomExceptionData] */
+class CustomExceptionDataTest {
+
+    @Test
+    fun `exception type and message is printed`() {
+        val exception = IllegalStateException("Java heap space")
+        assertThat("stack trace should exist", exception.stackTrace, not(arrayWithSize(0)))
+
+        val exceptionData = CustomExceptionData.fromException(exception)
+
+        val outputString = exceptionData.toHumanReadableString()
+
+        assertThat(outputString, containsString("IllegalStateException: Java heap space"))
+    }
+}
\ No newline at end of file
```

2024-12-06 16:30 UTC, david-allison commented
If I were adding `message` to the data,  the method call and tests wouldn't change, only the implementation would

`@CheckResult` - it's a pure function and we always want to use the result. Turn it into an IDE error if it's not used, and auto suggest creating a variable

2024-12-07 01:32 UTC, david-allison approved these changes
Great job! Tested with

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt	(revision dcf07cefcfff05fbe54615400a6e419b6f72c86d)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt	(date 1728647924463)
@@ -64,7 +64,7 @@
      * @see [CollectionOpenFailure]
      */
     @VisibleForTesting
-    var emulatedOpenFailure: CollectionOpenFailure? = null
+    var emulatedOpenFailure: CollectionOpenFailure? = CollectionOpenFailure.FATAL_ERROR
 
     private val testMutex = ReentrantLock()
 
```

2024-12-07 02:02 UTC, merged