Fixed some Android Studio warnings
ankidroid/Anki-Android pull request #17285
Opened 2024-10-20 09:19 UTC by delphvr

## Purpose / Description
Removing some android studio warnings

## Fixes
 Fixes  #13282

## Approach
used code inspection to find the warnings and used refactoring.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-10-20 19:13 UTC, david-allison requested changes
Sorry about requesting changes on your first PR, and thanks for submitting!

The issue is meant to be over a single file. 

This gives you: 

* A small task to accomplish
* A "quick win" and confidence boost, in that a PR can likely be accepted within the same day or with minor adjustments
* The ability to focus on issues with setup (such as being unable to run tests)

This gives us: 

* An easy and consistent way to onboard new people and ensure that they can build and test the project
* Slow and gradual progress towards a metric, which we can eventually automate
* An easy code review
* Confidence that people are ready to take on larger tasks and they won't self-assign and feel they've bitten off more than they can chew

Due to the PR size, this may take a number of rounds to get right, and it wasn't intended to be like this

We'll get this merged now the work's been done, but to set expectations: things may take a little longer

2024-10-20 19:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +    private val _buffer = 512
Revert all these

2024-10-20 20:11 UTC, delphvr commented on AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidgetConfig.kt
> +    private val _maxDecksAllowed = 5
I put it as a const, but not sure if I did it like it was attended

2024-10-20 20:11 UTC, delphvr commented on AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidgetConfig.kt
> +    private val _maxDecksAllowed = 1
I put it as a const, but not sure if I did it like it was attended (same as above)

2024-10-20 20:12 UTC, delphvr commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/Time.kt
> -fun roundedTimeSpan(context: Context, time_s: Long): String {
Done, sorry

2024-10-20 20:14 UTC, delphvr commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/Time.kt
> +fun roundedTimeSpanUnformatted(context: Context, timeS: Long): String {
Done as well

2024-10-20 20:16 UTC, delphvr commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
> +    private val _buffer = 512
I revert everything you asked! Sorry for the extra work

2024-10-20 20:41 UTC, david-allison approved these changes
Looks good, cheers!

2024-10-21 13:11 UTC, lukstbit requested changes
Thank you for contributing!
I've left some minor issues to fix and then we could merge this. It would also be helpful if you could [squash the commits](https://stackoverflow.com/questions/6934752/combining-multiple-commits-before-pushing-in-git) to make it easier for us to merge your changes.

2024-10-21 14:02 UTC, delphvr commented
Thank you! I squash them like you asked

2024-10-21 14:29 UTC, merged