test: android test for MultimediaFragment intents
ankidroid/Anki-Android pull request #17286
Opened 2024-10-20 10:27 UTC by criticalAY

## Purpose / Description
Test for multimedia activity intents i.e. camera, gallery & drawing 

## Approach
Use `libs.androidx.espresso.intents` to check if the intents are there or not, this will be useful to test other components too I.e cropper, audio recorder, etc

## How Has This Been Tested?
Tested locally using `./gradlew connectedplayDebugAndroidTest`

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-10-20 11:36 UTC, lukstbit requested changes
Check the android test failures they seem related to your changes.

2024-10-20 11:36 UTC, lukstbit commented on gradle/libs.versions.toml
> +androidx-espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espressoIntents" }
We already use some of the espresso related dependencies, look at the top of this block of dependencies.

2024-10-20 16:40 UTC, criticalAY commented on gradle/libs.versions.toml
> +androidx-espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espressoIntents" }
I want to test the intents, that won't be available without this depend, but the CI failing is weird since I tested it locally and it worked

2024-10-20 19:45 UTC, criticalAY commented on gradle/libs.versions.toml
> +androidx-espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espressoIntents" }
I wanted to test the intent launched but the depn is causing CI issue so I have updated the test to check for the titles, I will create more test for multimedia activity soon

2024-10-21 13:19 UTC, lukstbit commented on gradle/libs.versions.toml
> +androidx-espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espressoIntents" }
Sorry about not being clear, my initial comment was about grouping the new Espresso dependency with the others we already use, also to drop the custom espresso intents version and use the one we already have as Espresso dependencies have always had the same version.

2024-10-21 13:21 UTC, criticalAY commented on gradle/libs.versions.toml
> +androidx-espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espressoIntents" }
I have updated the tests now, will refactor them in next PR with more tests

2024-10-21 13:24 UTC, lukstbit commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/MultimediaTest.kt
> +    fun testFragmentTitle() {
I don't think this test is needed.

With the exception of one multimedia class, all other classes define the title as constants and the usage it's a simple call to setToolbarTitle(). These title properties are not dynamic and they aren't really going to be changed by someone when modifying those classes in the future.

AudioVideoFragment has a title that is different according to the values of an enum. I still don't think a test is needed here because adding more cases to that enum would be caught by the fact that the enum is used as an expression in the title returning method so there will be an compiler error to handle the new entry.

2024-10-21 13:56 UTC, criticalAY commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/MultimediaTest.kt
> +    fun testFragmentTitle() {
Since, the activity has default title as AnkiDroid for the toolbar, they change depending upon the fragment, I'll add more tests to the class to test some complex cases

2024-10-21 14:43 UTC, criticalAY commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/MultimediaTest.kt
> +    fun testFragmentTitle() {
I have added test for discard dialog too now, but still more test the better it is?

2024-12-08 06:34 UTC, criticalAY commented
Up for review

2024-12-08 11:54 UTC, david-allison approved these changes
Take it or leave it. I'm happy either way, and CI is happy

Let me know if you want an explanation on anything here

```patch
Index: AnkiDroid/src/androidTest/java/com/ichi2/anki/MultimediaTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/androidTest/java/com/ichi2/anki/MultimediaTest.kt b/AnkiDroid/src/androidTest/java/com/ichi2/anki/MultimediaTest.kt
--- a/AnkiDroid/src/androidTest/java/com/ichi2/anki/MultimediaTest.kt	(revision cf2ad33710b66061e3a276d57334cdaf3afeb135)
+++ b/AnkiDroid/src/androidTest/java/com/ichi2/anki/MultimediaTest.kt	(date 1733658217414)
@@ -19,6 +19,7 @@
 
 import android.content.Context
 import android.content.Intent
+import androidx.fragment.app.Fragment
 import androidx.test.core.app.ActivityScenario
 import androidx.test.espresso.Espresso.onView
 import androidx.test.espresso.assertion.ViewAssertions.matches
@@ -38,7 +39,6 @@
 import org.junit.Test
 import org.junit.runner.RunWith
 import org.junit.runners.Parameterized
-import kotlin.test.DefaultAsserter.assertEquals
 import kotlin.test.assertEquals
 
 @RunWith(Parameterized::class)
@@ -50,15 +50,22 @@
 
     @JvmField
     @Parameterized.Parameter(1)
-    var title: Int? = null
+    var expectedTitleRes: Int? = null
+
+    @Suppress("unused") // used by "{2}"
+    @JvmField
+    @Parameterized.Parameter(2)
+    var testName: String = ""
+
+    private val expectedTitle
+        get() = testContext.getString(expectedTitleRes!!)
 
     @Test
     fun testFragmentTitle() {
-        ActivityScenario.launch<MultimediaActivity>(intentBuilder(testContext)).use { scenario ->
+        withMultimediaActivityScenario { scenario ->
             scenario.onActivity { activity ->
-                val fragment = activity.supportFragmentManager.findFragmentById(R.id.fragment_container) as MultimediaFragment
-                val titleString = title?.let { testContext.getString(it) }
-                assertEquals(titleString, fragment.title)
+                val actualFragmentTitle = (activity.fragmentContainer as MultimediaFragment).title
+                assertEquals(expectedTitle, actualFragmentTitle, message = "title")
             }
         }
     }
@@ -66,7 +73,7 @@
     @Test
     fun testImageFragmentDiscardDialogShown() {
         val validIntentBuilders = setOf(
-            { context: Context -> getImageFragment(context) },
+            { context: Context -> getCameraFragment(context) },
             { context: Context -> getGalleryFragment(context) },
             { context: Context -> getDrawingFragment(context) }
         )
@@ -75,11 +82,12 @@
             return
         }
 
-        ActivityScenario.launch<MultimediaActivity>(intentBuilder(testContext)).use { scenario ->
+        withMultimediaActivityScenario { scenario ->
             scenario.onActivity { activity ->
-                val fragment = activity.supportFragmentManager.findFragmentById(R.id.fragment_container) as MultimediaImageFragment
-                fragment.viewModel.updateCurrentMultimediaPath("test/path")
-                fragment.requireActivity().onBackPressedDispatcher.onBackPressed()
+                (activity.fragmentContainer as MultimediaImageFragment).apply {
+                    viewModel.updateCurrentMultimediaPath("test/path")
+                    requireActivity().onBackPressedDispatcher.onBackPressed()
+                }
             }
 
             onView(withText(CollectionManager.TR.addingDiscardCurrentInput()))
@@ -94,23 +102,32 @@
         }
     }
 
+    /** Runs [ActivityScenario.launch] with the result of the [intentBuilder] */
+    private fun withMultimediaActivityScenario(block: (ActivityScenario<MultimediaActivity>) -> Unit) {
+        ActivityScenario.launch<MultimediaActivity>(intentBuilder(testContext)).use { block(it) }
+    }
+
+    val MultimediaActivity.fragmentContainer: Fragment
+        get() = this.supportFragmentManager.findFragmentById(R.id.fragment_container)!!
+
+
     companion object {
-        @Parameterized.Parameters(name = "{index}: {1}")
+        @Parameterized.Parameters(name = "{2}")
         @JvmStatic
         fun initParameters(): Collection<Array<out Any>> {
             return listOf(
-                arrayOf({ context: Context -> getImageFragment(context) }, R.string.multimedia_editor_popup_image),
-                arrayOf({ context: Context -> getGalleryFragment(context) }, R.string.multimedia_editor_popup_image),
-                arrayOf({ context: Context -> getDrawingFragment(context) }, R.string.multimedia_editor_popup_image),
-                arrayOf({ context: Context -> getAudioFragment(context) }, R.string.multimedia_editor_popup_audio_clip),
-                arrayOf({ context: Context -> getVideoFragment(context) }, R.string.multimedia_editor_popup_video_clip),
-                arrayOf({ context: Context -> getAudioRecordingFragment(context) }, R.string.multimedia_editor_field_editing_audio)
+                arrayOf({ context: Context -> getCameraFragment(context) }, R.string.multimedia_editor_popup_image, "Add image (Camera)"),
+                arrayOf({ context: Context -> getGalleryFragment(context) }, R.string.multimedia_editor_popup_image, "Add image (Gallery)"),
+                arrayOf({ context: Context -> getDrawingFragment(context) }, R.string.multimedia_editor_popup_image, "Add image (Drawing)"),
+                arrayOf({ context: Context -> getAudioFragment(context) }, R.string.multimedia_editor_popup_audio_clip, "Add audio clip"),
+                arrayOf({ context: Context -> getVideoFragment(context) }, R.string.multimedia_editor_popup_video_clip, "Add video clip"),
+                arrayOf({ context: Context -> getAudioRecordingFragment(context) }, R.string.multimedia_editor_field_editing_audio, "Record audio")
             )
         }
 
         private val multimediaActivityExtra = MultimediaActivityExtra(0, ImageField(), getTestMultimediaNote())
 
-        private fun getImageFragment(context: Context): Intent {
+        private fun getCameraFragment(context: Context): Intent {
             return MultimediaImageFragment.getIntent(
                 context,
                 multimediaActivityExtra,
```

2024-12-09 13:00 UTC, lukstbit approved these changes
Ok, I didn't had any issues with the code itself just with how useful I perceived it to be.

2024-12-09 13:39 UTC, criticalAY commented
@david-allison thanks! applied the patch

2024-12-09 15:52 UTC, mikehardy commented
```

com.ichi2.anki.MultimediaTest > testFragmentTitle[Add image (Camera)][emulator-5554 - 11] FAILED 
	java.lang.NullPointerException: Cannot run onActivity since Activity has been destroyed already
	at androidx.test.internal.util.Checks.checkNotNull(Checks.java:50)

```

That's not a good sign - adding a flaky test is worse than adding no test, this needs real investigation + real fix so it isn't flaky

2024-12-09 15:52 UTC, mikehardy requested changes
flaky

2024-12-09 16:56 UTC, criticalAY commented
I am reverting the patch and will run 20 iterations lets see then

2024-12-10 20:39 UTC, mikehardy commented
The Flake Hammer (tm) was implemented unit test only
https://github.com/mikehardy/Anki-Android/commit/e524c8f1020b48c9d6426e0afb99f9ab8a9cfb77

2024-12-10 20:41 UTC, criticalAY commented
I have run emulated tests 16 times by manually triggering the CI, all green there

2024-12-29 12:33 UTC, david-allison commented
@mikehardy I believe this one's good to go

2024-12-29 12:51 UTC, mikehardy commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/MultimediaTest.kt
> +        }
it feels like there is an expectation that 3 possible runs of this with some of the parameters will execute a real test vs just return

But I don't see any place that expectation is validated. If someone changes the Intent builder methods below a little bit, somehow for some reason, it seems like this test would just happily discard them and return and no runs of this test would actually test anything but no failure would be recorded

2024-12-29 13:03 UTC, mikehardy commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/MultimediaTest.kt
> +        }
I read the parameterized test documentation, and it appears an easily understable way to do this might be to have a static counter that is incremented for each intentBuilder that does not return, and then an AfterAll method that asserts the count of executed parameterized iterations is 3 ?

2025-01-25 17:36 UTC, closed without merging