refactor: remove context from `InstantEditorViewModel`
ankidroid/Anki-Android pull request #17296
Opened 2024-10-22 11:18 UTC by criticalAY

## Purpose / Description
Completes a TODO to keep ViewModel context free

## How Has This Been Tested?
Locally Google emulator API35

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-10-22 13:54 UTC, lukstbit requested changes

2024-10-22 13:54 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
> +        fun getLocalizedMessage(defaultError: String) = localizedMessage ?: defaultError
I think it would be easier to just remove this method and expose the _localizedMessage_ property directly.
Then in _InstantEditorViewModel.checkAndSaveNote()_ you could simply pass the _localizedMesage_ property to 
_SaveNoteResult.Warning_ class that already handles a null _message_. The only other thing to do would be to change the place where _SaveNoteResult.Warning_ is used to add the default string if _message_ is null:

```
is SaveNoteResult.Warning -> {
    Timber.d("Showing warning to the user")
    viewModel.setWarningMessage(result.message ?: getString(R.string.something_wrong))
 }
```

2024-10-22 16:20 UTC, lukstbit approved these changes
LGTM, left one minor issue.

2024-10-22 16:20 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
> -                savingErrorDialog(result.getErrorMessage(this))
I think the _SaveNoteResult.Failure.getErrorMessage()_ method became unused and can be deleted as well.

2024-10-23 00:41 UTC, david-allison approved these changes
Great job, cheers!

2024-10-23 00:54 UTC, merged