refactor: improvise logs related to deckPicker in StudyOptionsFragment
ankidroid/Anki-Android pull request #17291
Opened 2024-10-20 18:50 UTC by criticalAY

## Purpose / Description
Improvise the logs in StudyOptionsFragment to find the exact cause of NPE in study option fragment
## Fixes
* Related https://github.com/ankidroid/Anki-Android/issues/17284

## How Has This Been Tested?
Local build

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-10-20 20:49 UTC, david-allison requested changes
One blocker on the comment, rest are prefeences

2024-10-20 20:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
>                  }
This would feel better as either:
* `deckPicker?.run { } :? Timber.w()` 
* Extracted method

2024-10-20 20:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +            else -> return deckPicker?.onOptionsItemSelected(item) ?: false
don't you want to log here?

2024-10-20 21:45 UTC, mikehardy reviewed
this will convert a crash that is the reason we saw this problem into a bunch of log warnings that we will never see

2024-10-20 21:58 UTC, mikehardy commented
I think we should send an error report at least

I think it should still be non-null, but, the getter is just returning `activity`, perhaps it should return `requireActivity` then it will still crash, but it will have an obvious error

All of the activity results should have an `isAdded` check from Fragment, no need to do the work if the fragment has been detached and disposed?

and configureToolbar shouldn't be run in onCreateView, it should probably run onAttach ?

In those cases I don't think it's ever possible for Activity to be null (onAttach it will exist, and if !Added and you avoid, then you will avoid when it is not null)

And if we somehow still attempt to fetch the deckPicker / activity then it will still crash so we'll see it

2024-10-21 06:02 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
>                  }
extracted

2024-10-21 06:02 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
> +            else -> return deckPicker?.onOptionsItemSelected(item) ?: false
Ignoring knowingly :)

2024-10-21 06:21 UTC, criticalAY commented
config toolbar should not be in onAttach since,

- onAttach(): This is too early in the fragment lifecycle to configure UI elements like the toolbar since the view hasn't been created yet.
- onCreateView(): The view hierarchy is created here, but it's still not fully initialized. This method is mainly intended for inflating the layout.
- onViewCreated(): The view is fully initialized at this point, making it the ideal place to set up the toolbar.

2024-10-21 20:22 UTC, mikehardy commented
Based on that description of the lifecycle, is it possible then that we are in a race with construction of view / configure of toolbar, and a teardown cycle with destroy of view / detach of fragment?

If not, then I don't know how the activity could be null. Perhaps we need some logging on the teardown direction of the view/fragment lifecycle to see if we are still trying to configure a toolbar when the user has already moved on to something else and the fragment detached so there is no activity ?

2024-10-23 04:11 UTC, david-allison approved these changes

2024-10-23 16:04 UTC, david-allison commented
@mikehardy awaiting your review

2024-10-23 22:43 UTC, david-allison commented
>  this bug would probably be fixed by using the FragmentResult apis in the configureToolbarInternal() method to ping DeckPicker ... 

@lukstbit just to note: the following issue/PR starts to move in this direction, and it'd be useful to transfer the additional thoughts from your comment here so they can be worked into the solution

* https://github.com/ankidroid/Anki-Android/issues/17077
* https://github.com/ankidroid/Anki-Android/pull/17099

2024-10-24 03:59 UTC, mikehardy approved these changes
looks pretty thorough! There is a small chance acracrium will be bombed with this but somehow I don't think so - hopefully just enough to learn stuff
Thanks @criticalAY

2024-10-24 04:45 UTC, merged