Lint odyssey
ankidroid/Anki-Android pull request #17292
Opened 2024-10-20 21:39 UTC by mikehardy

## Purpose / Description

Would you believe I was just trying to reproduce #17284 ?

I noticed that in the logcat there was a message `deck filter: ` in the logcat for each of the crashes so I thought, what's that?

Then when I saw it in the code I saw there was a Timber lint error and the string format was incorrect

But our CI lint and command lint just doesn't see Timber things, what?

So I looked through our lint file to see if there were timber-related things, and there were, so I did my best to fix those up while also cleaning out some obvious easy lint things

That still did not help

I attempted to fork Timber and update it's dependencies to see if it is failing just because Kotlin is way newer than Timber expects and such, but that had no effect - timber still works in self-testing internally https://github.com/mikehardy/timber/tree/dependency-updates

So in the end I ran "analyze" in the IDE which *does* show Timber items, and fixed all the timber items

But they are not automated, they will regress unfortunately.

Should probably be squash-merged

## Fixes

No fixes, alas, just some cleaning

## Approach

Slow methodical testing and changing

## How Has This Been Tested?

using the gradle lint command line from our workflows

## Learning (optional, can help others)

Lint is a mystery

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-10-20 22:17 UTC, david-allison commented
Does this fix:

* https://github.com/ankidroid/Anki-Android/issues/17248

2024-10-20 22:26 UTC, david-allison requested changes
Cheers! Tons of great stuff here

2024-10-20 22:26 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        window.navigationBarColor = Themes.getColorFromAttr(this, intArrayOf(attr))[0]
Can we drop this commit, or modify it to use our own method here. 

New code is unpleasantly verbose

2024-10-20 22:26 UTC, david-allison commented on lint-release.xml
> -    <issue id="TypographyEllipsis" severity="ignore" />
Unsure on this one.

`TranslationTypo` is our own.

`TypographyEllipsis` is from the framework: https://googlesamples.github.io/android-custom-lint-rules/checks/TypographyEllipsis.md.html

2024-10-20 22:26 UTC, david-allison commented on gradle/libs.versions.toml
> +jetbrainsAnnotations = "26.0.1"
might want to reorder as well

2024-10-22 01:28 UTC, mikehardy commented on gradle/libs.versions.toml
> +jetbrainsAnnotations = "26.0.1"
I reordered it 👍

2024-10-22 01:31 UTC, mikehardy commented on lint-release.xml
> -    <issue id="TypographyEllipsis" severity="ignore" />
Interestingly, for me, was that this one did not ignore RTL language, while our check in TranslationTypo did IIRC
So lots of them slipped in there - I understand the rationale that "it's hard" part of reviewing the RTL languages I just want to push back on that a bit - it's not so hard and my advice is just to use the crowdin interface and it's not so bad

But, could back this out also. I don't *really* feel strongly. We're picking lint after all

2024-10-22 01:32 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
> +        window.navigationBarColor = Themes.getColorFromAttr(this, intArrayOf(attr))[0]
This one made me look more deeply and we already had a different method doing something more modern by getting the lookup from MaterialColors library. 

So what I did was use *that* style as the new fundamental operation, but I did make a convenience method that did the boxing/unboxing so the syntax wasn't quite as sickness inducing

What do you think?

2024-10-22 06:08 UTC, david-allison commented on lint-release.xml
> -    <issue id="TypographyEllipsis" severity="ignore" />
The lint failure from the check is obvious, but I personally struggle with the verification that my fixes for RTL languages on Crowdin are correct.

I would prefer to do the fixes, rather than revert on Crowdin: as a string with the wrong ellipsis is better than falling back to English

But: 

* I'm not going to be massively active for the next week, experiments won't affect any workflows (and it's a team effort anyway)
* I would have expected this PR to cause lint failures, so it looks like the lint check isn't being run anyway

So if we want to merge it as a test, I'm 100% OK with it

2024-10-22 06:10 UTC, david-allison commented on lint-release.xml
> -    <issue id="WorldWriteableFiles" severity="ignore" />
Why are these lint issues not being moved to 'fatal'?

Listing them as `ignore` means we know they're not yet handled. 

Having them missing leaves them less documented than before

2024-10-22 15:33 UTC, mikehardy commented on lint-release.xml
> -    <issue id="TypographyEllipsis" severity="ignore" />
> I would have expected this PR to cause lint failures, so it looks like the lint check isn't being run anyway

No failures **because I fixed them all** 🦸  😆 

It's easy to fix in crowdin IMHO. Copy the ellipse char into clipboard, search for `...` in the RTL languages multi-lingual mode in crowdin, paste over the `...`, done. There were maybe 15? 20?

I want to enable it as a test, I found it useful and it drove real fixes (not reverts!). If it sucks, we revert this commit :-)

2024-10-22 15:34 UTC, mikehardy commented on lint-release.xml
> -    <issue id="WorldWriteableFiles" severity="ignore" />
Oh! Simply hadn't considered that, really obvious now that you mention it. I was just deleting, oops
Will convert to fatal yes

2024-10-22 15:35 UTC, mikehardy commented
Dang if the custom scheduler test isn't blowing up again! Why!?

```

com.ichi2.anki.ReviewerTest > testCustomSchedulerWithCustomData[emulator-5554 - 11] FAILED 
	java.lang.AssertionError:
	Expected: <3000>

```

I had a look and it looks to me like in the emulator video, it's just sitting on the question side, the show answer button is not clicked correctly. Unsure why, maybe a race? Maybe element name is different (that has happened before...)

2024-10-23 01:14 UTC, david-allison commented
Failure seems persistent

2024-10-24 03:53 UTC, mikehardy commented on lint-release.xml
> -    <issue id="WorldWriteableFiles" severity="ignore" />
great catch - this is done now, they are all switched from ignore to fatal rather than switching from ignore to "not there anymore"

2024-10-24 04:50 UTC, david-allison approved these changes
Thanks!!

2024-10-24 04:50 UTC, david-allison commented on lint-release.xml
> +    <issue id="CustomX509TrustManager" severity="ignore" />
Note: These are still ignore

2024-10-25 02:17 UTC, mikehardy commented on lint-release.xml
> +    <issue id="CustomX509TrustManager" severity="ignore" />
Wow, I must have been way too tired to code yesterday. Surprising oversight sorry for the lost time
Gave it another go just now and re-pushed

2024-10-26 01:44 UTC, merged