Add fsrs version to debug info
ankidroid/Anki-Android pull request #17304
Opened 2024-10-24 09:50 UTC by lukstbit

## Purpose / Description

Adds the fsrs version to the debug info. In a separate commit I also added the version to the about settings screen so it can be removed if not wanted:
![s1](https://github.com/user-attachments/assets/09147ff0-c053-47e8-8f7b-b053783e2d2c)

## Fixes
Towards #17236

## How Has This Been Tested?

Looked at the debug info, looked at the settings screen

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-10-24 10:15 UTC, david-allison requested changes
The FSRS version is technically correct (in that it's the library version) but not what we should display to the user.

A user would expect this version to be "FSRS 4.5", and not displaying this will lead to confusion.

2024-10-24 10:25 UTC, david-allison requested changes
Requested change:

I feel hardcoding a mapping from 'internal' to 'user-facing' version is the most effective way to quickly solve this

* Hardcode a mapping from `0.6.4` to `4.5`
* Add a unit test which will break if the `BuildConfig` changes from `0.6.4`
* In a future version, we expect to move this to the backend

2024-10-24 10:26 UTC, david-allison reviewed
+ capitalization nits

2024-10-24 10:26 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
> +            "(fsrs ${net.ankiweb.rsdroid.BuildConfig.FSRS_VERSION})"
```suggestion
            "(FSRS ${net.ankiweb.rsdroid.BuildConfig.FSRS_VERSION})"
```

2024-10-24 10:26 UTC, david-allison commented on AnkiDroid/src/main/res/layout/about_layout.xml
> +        tools:text="(fsrs 0.6.4)" />
```suggestion
        tools:text="(FSRS X.Y)" />
```

2024-10-24 11:14 UTC, david-allison approved these changes
Cheers!

Once this is merged, we should add an issue to expose this version in the backend

That will remove the need to perform additional code changed in addition to a version bump for the backend

2024-10-24 14:18 UTC, david-allison requested changes
With apologies for the back & forth. After a discussion with Voczi, Jarrett Ye & Expertium, there's consensus for displaying the library version.

https://discord.com/channels/368267295601983490/701922522836369498/1298985695645270097

I personally disagree here (I believe displaying the user-facing version is better), but it's a quick change to make to improve things if necessary

The FSRS devs will feel the support burden from this change more than AnkiDroid, and it's only fair to them to help them with user support as much as possible

2024-10-24 15:23 UTC, lukstbit commented
I've reverted the changes to the initial state, this includes showing only the library version in the debug info.

> I personally disagree here (I believe displaying the user-facing version is better)

I also think the user facing version is better. Looking though discussions on ankiweb's forums the users refer to FSRS in terms of 4.5, 5 and not library version which is mostly a dev thing. Even if there are issues with FSRS, we ask for debug info which would include the precise library version anyway.

2024-10-24 16:23 UTC, david-allison approved these changes

2024-10-25 01:49 UTC, mikehardy approved these changes
I'm also going with it as the stated preference of the devs following my general "implementor's choice" rule, which is even stronger if it's "people doing support's choice". We can add a mapping later if we really need it

2024-10-25 02:03 UTC, merged