Fix study options related menus
ankidroid/Anki-Android pull request #17314
Opened 2024-10-27 14:40 UTC by lukstbit

## Purpose / Description
Introduces changes to improve the handling of menus around StudyOptionsFragment which is used both in single and multi pane layouts in multiple activities. More info in the commits details.

Other notes:
- the undo menu item was moved out of StudyOptionsFragment, I think this is a global action and shouldn't be handled manually at fragment level
- the previous code used an option on tablets to export the current selected deck. I don't feel this is a menu option that should be present as we already have a menu item that does this at the cost of an extra touch. Also doesn't seem this would have the use frequency to have its own menu item.
- as the second commit introduces breaking changes(fixed later) the last 4 commits should probably be squashed.
- the label _"StudyOptions"_ was deleted from the manifest for _StudyOptionsActivity_ to show a toolbar without title like the previous code did(the fragment's toolbar didn't set a title). Maybe we should add a title here?

Some images:
<img src="https://github.com/user-attachments/assets/74e64993-06b0-4805-91f8-714dc153a32e" width="240px" height="520px" /><img src="https://github.com/user-attachments/assets/2215a924-8a94-4976-81f1-46facce9ed73" width="240px" height="520px" /><img src="https://github.com/user-attachments/assets/947339ab-b90d-4a75-b0cf-41e532b4888e" width="240px" height="520px" />

![tablet_normal_deck](https://github.com/user-attachments/assets/8fe0cc77-e93b-4ea2-892f-41e2361f6b74)
![tablet_normal_expanded_menu](https://github.com/user-attachments/assets/a411dcb6-dd40-4c01-acb3-fbee12f14dc7)

## Fixes
* Fixes #17284
* Fixes #17077
* Supersedes and closes  #17099 

## How Has This Been Tested?

Ran the tests, looked at the menus in phone/tablet mode.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-10-27 14:45 UTC, lukstbit commented
@david-allison I'm not sure if this is what you were thinking with the comment in the linked issue. My intentions with StudyOptionsFragment are:
- make it expose only the menu items that it handles internally
- make it so it doesn't have to know if it's in a multi pane layouts
- should probably delegate to the activity calls to other screens

2024-10-27 15:01 UTC, david-allison requested changes
Looks great!

`refreshUndoState` is the main question I have, I'm struggling with the guard clause logic

2024-10-28 12:22 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
> +        closeStudyOptions()
It's funny because the first time I pushed the branch it had a commit just for this, but I decided to get rid of it to make it easier to review  :laughing: . I'll do it in a future PR.

2024-10-28 12:24 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
> +        if (lifecycle.currentState.isAtLeast(Lifecycle.State.RESUMED)) return
My intention was to be very defensive and refresh the undo state only when the activity is in the foreground. I removed the check, if the activity is able to receive the _opExecuted_ callback , then it can also handle the undo state refresh.

2024-10-28 12:27 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
> +                    // TODO why are we going to the Reviewer from here? Desktop doesn't do this
> when we undo a review, we bring the user back to the reviewer

Seems reasonable, it's just that the desktop code doesn't do this, it just refreshes the count. I've looked a bit at this and I think it may also be related to the fact that when the deck is empty desktop goes to congrats page, we however don't call congrats directly I think we go through the reviewer first.

2024-10-28 15:12 UTC, david-allison approved these changes
Thanks!!!

> as the second commit introduces breaking changes(fixed later) the last 4 commits should probably be squashed.

2024-11-14 19:19 UTC, BrayanDSO commented on AnkiDroid/src/main/AndroidManifest.xml
> +            android:label=""
remove this completely and programmatically set the toolbar title to "" so the title stays blank

2024-11-15 10:08 UTC, lukstbit commented on AnkiDroid/src/main/AndroidManifest.xml
> +            android:label=""
Done, thanks!

2024-11-15 10:09 UTC, BrayanDSO approved these changes

2024-11-15 10:33 UTC, merged