NF: Simplify the usage of bridgeCommand in PageFragment
ankidroid/Anki-Android pull request #17315
Opened 2024-10-27 22:45 UTC by Arthur-Milchior

NF: Simplify the usage of bridgeCommand in PageFragment
`bridgeCommand` is the general process by which Anki's webview send
command to the webview's owner. In Anki, it's interpreted by
Python. In AnkiDroid it must be interpreted by Kotlin.

Currently, the only `bridgeCommand` we listen to are in
CongratsPage. And I'm really thankful @BrayanDSO for creating this
first usage!

When anki 24.10 beta 2 is used in ankidroid, the DeckOptions will also
send `bridgeCommand`. And, I expect that when we'll use more webview,
more `bridgeCommand` will arrive.

So, I decided to generalize Brayan's code and ensure that there is a
simple map that any PageFragment can override that would allow to
declare its `bridgeCommand` without needing to add copy
`CongratsPage`'s code.

I tested this manually, and the CongratsPage's button still works.

2024-10-27 23:51 UTC, mikehardy approved these changes
love the idea, implementation seems good but will defer to anyone better at Kotlin for taste and to Brayan for idea-consistency with what he was thinking

2024-10-28 07:31 UTC, david-allison requested changes
Very clean

Patch of my proposals:

```patch
Subject: [PATCH] fix: hack for broken AGP 8.6.1

We're now on AGP 8.7.1 and this is fixed:
https://issuetracker.google.com/issues/367752734

* remove `open = true`
* fix error

Reverts part of 7db4ea983b127812fcb9c6a34f0cd325a0f9f91d

* androidGradlePlugin 8.6.1 broke lint if using 
`.toLong()` in a `@LongDef`

https://issuetracker.google.com/issues/367752734 was been raised
and `open = true` was temporarily added on broken `@LongDef`
instances

Related 17086
Related 17263
Fixes 17265
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt b/AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt	(revision efa539c25e49155d7bcb771713eb9fc09c46a233)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt	(date 1730100622337)
@@ -33,7 +33,6 @@
 import com.ichi2.annotations.NeedsTest
 import com.ichi2.libanki.undoableOp
 import com.ichi2.libanki.updateDeckConfigsRaw
-import com.ichi2.libanki.utils.append
 import kotlinx.coroutines.Dispatchers
 import kotlinx.coroutines.withContext
 import timber.log.Timber
@@ -137,7 +136,7 @@
                 }
             }
         }.apply {
-            onPageFinishedCallback.append { view ->
+            onPageFinishedCallbacks.add { view ->
                 Timber.v("canGoBack: %b", view.canGoBack())
                 onBackCallback.isEnabled = view.canGoBack()
                 // reset the modal state on page load
Index: AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt	(revision efa539c25e49155d7bcb771713eb9fc09c46a233)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt	(date 1730100648593)
@@ -30,7 +30,6 @@
 import com.google.android.material.appbar.MaterialToolbar
 import com.ichi2.anki.R
 import com.ichi2.anki.SingleFragmentActivity
-import com.ichi2.libanki.utils.append
 import com.ichi2.themes.Themes
 import com.ichi2.themes.setTransparentStatusBar
 import timber.log.Timber
@@ -77,7 +76,7 @@
 
         onWebViewCreated(webView)
         if (bridgeCommands != null) {
-            pageWebViewClient.onPageFinishedCallback.append { webView ->
+            pageWebViewClient.onPageFinishedCallbacks.add { webView ->
                 webView.evaluateJavascript(
                     "bridgeCommand = function(request){ ankidroid.bridgeCommand(request); };"
                 ) {}
Index: AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt b/AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt	(revision efa539c25e49155d7bcb771713eb9fc09c46a233)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt	(date 1730100622334)
@@ -23,6 +23,7 @@
 import android.webkit.WebViewClient
 import androidx.core.view.isVisible
 import com.google.android.material.color.MaterialColors
+import com.ichi2.anki.OnPageFinishedCallback
 import com.ichi2.utils.AssetHelper.guessMimeType
 import com.ichi2.utils.toRGBHex
 import timber.log.Timber
@@ -37,7 +38,7 @@
     /** Wait for the provided promise to complete before showing the WebView */
     open val promiseToWaitFor: String? = null
 
-    val onPageFinishedCallback: MutableList<(WebView) -> Unit> = mutableListOf()
+    val onPageFinishedCallbacks: MutableList<OnPageFinishedCallback> = mutableListOf()
 
     override fun shouldInterceptRequest(
         view: WebView,
@@ -85,7 +86,7 @@
     override fun onPageFinished(view: WebView?, url: String?) {
         super.onPageFinished(view, url)
         if (view == null) return
-        onPageFinishedCallback.map { callback -> callback(view) }
+        onPageFinishedCallbacks.map { callback -> callback.onPageFinished(view) }
         if (promiseToWaitFor == null) {
             /** [PageFragment.webView] is invisible by default to avoid flashes while
              * the page is loaded, and can be made visible again after it finishes loading */
```

2024-10-28 07:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt
> +    val onPageFinishedCallback: MutableList<(WebView) -> Unit> = mutableListOf()
`onPageFinishedCallbacks`, I was struggling to understand `<function>.append`

2024-10-28 07:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
> +            pageWebViewClient.onPageFinishedCallback.append { webView ->
`.append` is intended to exist so we can get 1:1 functional compatibility with Python, the standard Kotlin method is `.add`.

`add` also handles named lambdas better

2024-10-28 07:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt
> +    val onPageFinishedCallback: MutableList<(WebView) -> Unit> = mutableListOf()
This would feel better as a list of `OnPageFinishedCallback`

2024-10-28 07:32 UTC, david-allison commented
@voczi FYI

2024-10-28 13:32 UTC, BrayanDSO reviewed
It works for me, but I agree with David's comments.

> And, I expect that when we'll use more webview, more `bridgeCommand` will arrive.

About that, @dae [himself said](https://github.com/ankidroid/Anki-Android/issues/14361#issuecomment-1701946364) that he wants to avoid `bridgeCommand` in new code.

If this is new code and still uses `bridgeCommand`, I'm honestly disappointed.

2024-10-28 15:40 UTC, Arthur-Milchior commented
I was referring to https://github.com/ankitects/anki/pull/3410/files , which introduces changes in svelte I wanted to use (and then I realize that, even if it’s available in ankidroid-backend, it’s not in ankidroid yet).

It does not introduce new `bridgeCommand` (i recalled it did, I was wrong). It still uses the `deckOptionsReady` to state that the webview is available to let python knows that it can send request to the webview about whether the data was modified.
I would have appreciated to use it.

But I guess I can just ignore this bridge command, assume that when the page is loaded, it can accept request. And any result that is not a boolean means the page was not loaded so we can’t close it.


Still, given that bridgeCommand already exists and does not seems to be going to be deleted soon, I still suspect this PR is useful.

I’ll apply David’s change when I’m on my home computer

2024-11-08 14:50 UTC, Arthur-Milchior commented
oh, I finally figured out why I was confused. New bridge commands were added in https://github.com/ankitects/anki/pull/3495/files
And I need it to fix a bug in ankidroid

2024-11-08 15:49 UTC, Arthur-Milchior commented
So I applied @david-allison 's requested change, and then added an extra commit to solve the deck option issue.

If we eventually move away from the bridge, this will need to be updated.

2024-11-08 15:50 UTC, Arthur-Milchior commented
Given the extra commit, I removed @mikehardy 's approval.
The nice thing here being that this show why the first two commit is useful. It's not only for code cleanliness

2024-11-09 04:01 UTC, Arthur-Milchior commented
Does anyone know whether PageFragments actually load their webcontent in RobolectricTest ?
Trying to run the test with the debugger, it seems clear that the BridgeCommand is not executed. I don't know whether it is because we should wait more or because the js part is not executed.

I tried adding 
```

            runBlocking{
                delay(2000)
            }
```
after pressing back, and it does not solve anything. So I assume it's a problem with the JS part

2024-11-09 13:37 UTC, mikehardy commented
As discussed on Discord, the WebView is a "shadow" (that is: fake) implementation in robolectric.
The APIs are there but they largely do nothing. No content is loaded, javascript is definitely not executed.
For WebView-related tests where the WebView is expected to actually do things, it needs to be an androidTest on device

2024-11-11 01:37 UTC, Arthur-Milchior commented
I removed the unit test then. There is no relevant way to do them. Unless I I start to mock the webview behavior, and that does not seems interesting things to do. In particular because this would break as soon as the deck option's TS code change

For some reason I don't understand, when I am in the deck picker, with instrumented tests, long click fail to open the menu. I don't know whether it just entirely fail to be registered, or whether the instrumented test don't open the menu for some reason.
In any case, opening the menu of actions  from deck is too hard, so I would prefer not to block this useful feature, unless someone is competent enough with espresso/instrumented test to help me understand what's wrong with it

2024-11-11 08:16 UTC, Arthur-Milchior commented
Rebased on top of #17419 so that I can reuse some deck picker instrumented tests function

2024-11-11 19:36 UTC, BrayanDSO commented
Please add some ` ` around my GitHub nickname in the [NF: Simplify the usage of bridgeCommand in PageFragment](https://github.com/ankidroid/Anki-Android/pull/17315/commits/b48c6672835c08c6330b693f3e0a9905821ba7d0) 
 commit description, so I don't get a ping every time you force push. i.e. use `@BrayanDSO`, not @BrayanDSO

2024-11-11 20:45 UTC, Arthur-Milchior commented
Done, sorry

2024-11-11 21:51 UTC, david-allison requested changes
Main question is regarding functionality + manual testing

And potential issues two classes with the same `JavaScriptInterface`, I'd avoid this by renaming the `"ankidroid"` interface we add in `DeckOptions`

Really appreciate the effort which went into re-testing this, thanks!!

2024-11-11 21:51 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckOptionsTest.kt
> +    val activityRule = ActivityScenarioRule(DeckPicker::class.java)
Explain why `DeckPicker` is used

2024-11-11 21:51 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckOptionsTest.kt
> +        assumeFalse("Test flaky in CI - #9282, skipping", wasBuiltOnCI())
This issue is closed

2024-11-11 21:51 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckOptionsTest.kt
> +            )
I'd extract this to a method: `performArbitraryOptionsChange()`

2024-11-11 21:51 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckOptionsTest.kt
> +    fun testDeckOptionsWithChangeShowAlert() {
This test has no assertions, and is therefore difficult to understand the intention

2024-11-11 21:51 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckOptionsTest.kt
> +        assertWebViewDoesNotExists()
Don't you want to assert that either: the fragment/activity is no longer loaded, or the user has gone back to the previous screen.

The WebView not existing doesn't seem to be a good proxy for this

2024-11-11 21:51 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckOptionsTest.kt
> +        assertWebViewDoesNotExists()
It would be better to have a timeout inside `assertWebViewDoesNotExists`: poll for lack of existence for the view up to 1s, then fail if the condition fails to occur

2024-11-11 21:51 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckOptionsTest.kt
> +        assumeFalse("Test flaky in CI - #9282, skipping", wasBuiltOnCI())
Does this test run on tablets, due to the difference in views?

2024-11-11 21:51 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPicker.kt
> +package com.ichi2.anki
This feels like it should be in a utility package

2024-11-11 21:51 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
> +        } catch (e: Throwable) {
Q: is this a bug. I would expect a `ViewNotFound` to be retried, but an assertion failure should exit the loop

2024-11-11 21:51 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
> +            webView.evaluateJavascript("anki.deckOptionsPendingChanges()") {
No Timber?

2024-11-11 21:51 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckOptionsTest.kt
> +class DeckOptionsTest : InstrumentedTest() {
These tests don't seem to handle either of the following cases. Did you manually test these:

* User navigated to the Anki Manual via a link, and pressed 'back'
  * WebView should navigate back to options (changes are persisted), options should remain open
* User opened up a modal on the svelte page and pressed 'back' 
  * modal should close, options should remain open

2024-11-11 21:51 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
> +                "ankidroid"
This conflicts with the line 

`webView.addJavascriptInterface(ModalJavaScriptInterfaceListener(), "ankidroid")`

2024-11-11 23:45 UTC, Arthur-Milchior commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckOptionsTest.kt
> +        assumeFalse("Test flaky in CI - #9282, skipping", wasBuiltOnCI())
I reopened it. There are still multiple disabled tests referring to this issue

2024-11-11 23:47 UTC, Arthur-Milchior commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckOptionsTest.kt
> +    fun testDeckOptionsWithChangeShowAlert() {
Actually there are assertions in openDeckOptions.
But the most important one is that the click can occurs, which means the buttons indeed exists. I don't know exactly how to state this with assertion

2024-11-12 01:35 UTC, Arthur-Milchior commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPicker.kt
> +package com.ichi2.anki
Done. Actually it was done in the PR #17419 that I use in two PRs.

2024-12-04 05:53 UTC, david-allison requested changes
Really nice, thanks!

I feel I went overboard on the nitpicks here, feel free to resolve anything you disagree with.

2024-12-04 05:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
> +                ) {}
Rename these (names are up to you)

Using `bridgeCommand` for 3 different concepts in the same block is a recipe for confusion.

2024-12-04 05:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
> +        if (bridgeCommands != null) {
nit/optional: I'd find it slightly easier to read if this were extracted to a method: `setupBridgeCommands`

2024-12-04 05:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
> +    open val bridgeCommands: Map<String, () -> Unit>? = null
Could do with a small JavaDoc. My question would be whether this can be mutated after init

The answer: yes

2024-12-04 05:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
> +    open val bridgeCommands: Map<String, () -> Unit>? = null
in the code below, we only check for `null`, not `empty`.

Optional: It might be easier to understand to make this non-null with an empty map

2024-12-04 05:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
> +            pageWebViewClient = onCreateWebViewClient(savedInstanceState)
Document that `webView.webViewClient` is accessible in API 26, and this is a hack to work around the lack of access

2024-12-04 05:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
> +    /**
Fantastic job here!

2024-12-04 05:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
> +     * It consists in requesting the webview to go back.
It requests the WebView to go back (to the Deck Options)

2024-12-04 05:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
> +     * It requests javascript to check whether there is any change and transmit further actions through the bridge command.
> It requests javascript to check whether there is any change and transmit further actions through the bridge command.

I don't believe this is correct. The callback isn't responsible for the JS, the JS is responsible for the callback

2024-12-04 05:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
> +     * Callback used when a modal is opened. It requests the webview to close it.
clarify: this is not an AnkiDroid modal

2024-12-04 05:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
> +    override val bridgeCommands = mapOf(
It feels like a lot of these changes got squashed into a previous commit

2024-12-04 05:53 UTC, david-allison commented on gradle/libs.versions.toml
> +androidx-espresso-web = { module = "androidx.test.espresso:espresso-web", version.ref = "espressoWeb" }
This should be under `testing libs` (L170):

> `#testing libs`

2024-12-04 05:53 UTC, david-allison commented on gradle/libs.versions.toml
> +espressoWeb = "3.6.1"
* rename to `androidxTestEspressoWeb`, 
* move it with the other `androidX` libraries below (Line 16) 
*  add a link to the documentation
    *  (Dependabot doesn't support links to the changelog/releases for Google libraries, so we do it manually)

2024-12-04 23:07 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
> +    /**
Thanks.
I'm especially happy to read that that it was long enough ago that I don't recall what this commit contains :p.

2024-12-04 23:10 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
> +     * It requests javascript to check whether there is any change and transmit further actions through the bridge command.
In the second commit, you're right. I should have done the documentation change in the commit where we actually request JS to check whether there is any change

2024-12-04 23:15 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
> +    override val bridgeCommands = mapOf(
I'm sorry but I don't understand this comment

2024-12-05 03:00 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
> +    open val bridgeCommands: Map<String, () -> Unit>? = null
```kotlin
    override val bridgeCommands: Map<String, () -> Unit>
        get() {
            return mapOf(
                Math.random().toString() to { viewModel.onUnbury() },
                "customStudy" to { onStudyMore() }
            )  
    } 
```

2024-12-05 03:01 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
> +    /**
Docs, docs and more docs!

2024-12-05 03:03 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
> +    override val bridgeCommands = mapOf(
It feels like https://github.com/ankidroid/Anki-Android/pull/17315/commits/022f2fa09a082ff43bedea7645983b4a2635016f contains a lot of the implementation of this commit

2024-12-05 03:03 UTC, david-allison commented
CI failure

2024-12-27 23:16 UTC, david-allison requested changes
Change is good, refactorings need work

And the third commit message is mostly irrelevant and can be condensed

2024-12-27 23:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
> +        webView.addJavascriptInterface(
These two lines should be swapped, otherwise there's a race condition where `onPageFinished` executes before `addJavascriptInterface`

2024-12-27 23:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
> +                "bridgeCommand = function(request){ bridgeCommandInterface.bridgeCommandImpl(request); };"
I believe this breaks `CongratsPage`, which uses `ankidroid` as the interface name

2024-12-28 15:26 UTC, david-allison approved these changes
Looks great!

I'm unhappy with the amount of review comments I made here (I want to optimize for getting PRs through faster in the future). I see this as an issue with my reviews, so feedback strongly encouraged for how I can streamline things.

2024-12-28 15:39 UTC, merged

2024-12-28 16:11 UTC, Arthur-Milchior commented
> Looks great!
Thanks

> I'm unhappy with the number of rounds of review I caused here (I want to optimize for getting PRs through faster in the future). I see this as an issue with my reviews, so strongly encourage feedback for how I can streamline things.

I admit the number of review was quite high for what was supposed to be a very simple features.
However, I don't have the feeling you were the cause. Or really anyone was.

The first version of the PR contained only some code to add the `bridgeCommand` to every PageFragment.
Then, Anki merged my PR to add the same feature upstream, and I was able to add a commit to use this feature.
There was also some discussion due to the fact that BridgeCommand should not even have been used in the first place.
I hesitated to merge this PR, as I tried to remove the new BridgeCommand [upstream](https://github.com/ankitects/anki/pull/3571). Somehow, I missed that DAE answered me, I just discovered it now. Maybe I'll do it this week-end then.

Which means that not only did we actually had two different PR review in this PR. One for refactoring the code. One, that arrived later, to use the new code for the desired feature.

I am not sure what could be done better really, appart from not having so many layers of dependencies.