test: deck options on back press
ankidroid/Anki-Android pull request #17311
Opened 2024-10-26 12:13 UTC by cshcsh3

Hello, I'm mostly a TypeScript dev who is really rusty with Android and trying to get back into Android development. Forgive my Android newbie-ness.

## Purpose / Description
Implemented test case for `DeckOptions`, ensures that on pressing the system-level back button and back navigation icon finishes the activity. 

## Fixes
* Fixes #13283

## Approach
2 tests have been written: 1 that does a system-level back press and 1 that simulates the icon button back press. For both tests, it passes as long as the deck options fragment activity is finishing.

I understand that the test annotation description was to verify that it returned to the previous screen, does checking if the activity is finishing sufficient in determining that going back works as intended?
I assume it's related to this other test case: `@NeedsTest("15130: pressing back: icon + button should return to options if the manual is open")`, then doing this check would make sense.

## How Has This Been Tested?

Ran `./gradlew jacocoUnitTestReport`

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-10-26 12:57 UTC, david-allison requested changes
Looks great! One nitpick on the copyright

Just to note:

`* Fixes #13283` closes the issue, which isn't what we want

I've changed this to

`* Part of #13283`

2024-10-26 12:57 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/DeckOptionsTest.kt
> + *  Copyright (c) 2024 David Allison <davidallisongithub@gmail.com>
That's Not Me!

(edit this to add your name and an optional email)

2024-10-26 14:38 UTC, cshcsh3 commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/DeckOptionsTest.kt
> + *  Copyright (c) 2024 David Allison <davidallisongithub@gmail.com>
Oops, was a copy paste mistake - edited

2024-10-26 14:46 UTC, david-allison approved these changes
Looks great, thanks for the fast turnaround

2024-10-26 16:25 UTC, lukstbit requested changes

2024-10-26 16:25 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/DeckOptionsTest.kt
> +    fun `When pressing the back icon, the activity should finish`() {
While it technically goes back this is known as an "up" action so I would recommend changing the test name to :

_When pressing the toolbar up button, the activity should finish_

This test is a duplicate of the first test because doing _onBackPressedDispatcher.onBackPressed()_ is the same with pressing BACK. When pressing BACK the activity goes through the BACK callbacks set on the _onBackPressedDispatcher_ and chooses the first one that is enabled.

If you want to actual test the up button then you need to simulate clicking it. That button can be found by its english content description _"Navigate up"_. Because looking for views by their content description is problematic due to the using a different locale, we need to wrap the click call in a try-catch to abort test if the view is not found:

```
scenario.onActivity { // assert that the activity is not finishing here
try {
    onView(withContentDescription("Navigate up")).perform(click())
} catch (ex: NoMatchingViewException) {
    Timber.d("Toolbar UP button not found. Is english locale being used?")
    return // if we get here just abort
}
scenario.onActivity { // click button and check that the activity is finishing
```

2024-10-27 04:07 UTC, cshcsh3 commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/DeckOptionsTest.kt
> +    fun `When pressing the back icon, the activity should finish`() {
Appreciate the detailed explanation, I've modified it via the view but within the same onActivity inline function, does that work?

2024-10-27 07:39 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/DeckOptionsTest.kt
> +    fun `When pressing the back icon, the activity should finish`() {
Yes, it's fine.

2024-10-27 07:42 UTC, lukstbit requested changes

2024-10-27 07:42 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/DeckOptionsTest.kt
> +                return@onActivity // Abort
We need a simple _return_ here to exit the test function because the test it's destined to fail(nothing was clicked). If we use _return@onActivity_ then we are simply exiting the _onActivity_ lambda and the test will continue.

2024-10-27 14:30 UTC, cshcsh3 commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/DeckOptionsTest.kt
> +                return@onActivity // Abort
Ah okay got what you mean, pushed the change

2024-10-27 14:55 UTC, lukstbit approved these changes
LGTM, thank you for making the changes.

2024-10-27 15:08 UTC, merged