chore: forward-port to compileSdk 35
ankidroid/Anki-Android pull request #17333
Opened 2024-10-31 16:13 UTC by mikehardy

## Purpose / Description

Unblock new dependencies that rely on compileSdk 35

most of the changes performed at same time are nullability-related

there are two specific things deferred via suppression annotation:
- all the targetSdk 35 edge-to-edge behavior changes - this is a big one
- one compute bounds thing for graphics, minor but API change is confusing

## Fixes

No fixes but:
- Related: #17327 
- Related: #17329 

## Approach

Nullability stuff was easy to handle as the null case was already contemplated in the codepaths as either "okay" or already an error. So that was just syntactic chore

Suppression of two other things was different and related issues will be logged

## How Has This Been Tested?

Ran the lint gradle command line locally as well as `./gradlew jacocoTestReport` until everything compiled well and tested okay

## Learning (optional, can help others)

Same ol' same ol' - relentless march of progress imposes background carry-cost load

I will be curious to see what the flagged API thing is for the computeBounds Path API deprecation

The edge-to-edge stuff will be a legitimate effort in this repository, it is a non-trivial UI update

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-10-31 16:37 UTC, mikehardy commented
hit the flake on androidTest scheduler thing again - turns out the dependency-updates branch didn't have the fix commit for new reviewer yet, so I just rebased dependency-updates and pushed it, and did same here.

2024-10-31 19:14 UTC, david-allison requested changes
As requested, nitpicks abound!

Most of which are included here:

```patch
Subject: [PATCH] 
---
Index: AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt	(revision 900a64a543e42cded4baf1c684a789786c5e8648)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt	(date 1730401960147)
@@ -34,21 +34,21 @@
 
         // we can't access this in a static context
         val packageInfo = targetContext.getPackageInfoCompat(targetContext.packageName, PackageInfoFlagsCompat.of(PackageManager.GET_ACTIVITIES.toLong())) ?: throw IllegalStateException("getPackageInfo failed")
-        val manifestActivities = packageInfo.activities
+
+        val manifestActivities = packageInfo.activities ?: throw IllegalStateException("activity list")
         val testedActivityClassNames = ActivityList.allActivitiesAndIntents().map { it.className }.toSet()
         var manifestActivityNames: Array<String> = emptyStringArray(0)
-        if (manifestActivities != null) {
-            manifestActivityNames = manifestActivities
-                .map { it.name }
-                .filter { it != "com.ichi2.anki.TestCardTemplatePreviewer" }
-                .filter { it != "com.ichi2.anki.AnkiCardContextMenuAction" }
-                .filter { it != "com.ichi2.anki.analytics.AnkiDroidCrashReportDialog" }
-                .filter { !it.startsWith("androidx") }
-                .filter { !it.startsWith("org.acra") }
-                .filter { !it.startsWith("leakcanary.internal") }
-                .filter { it != "com.canhub.cropper.CropImageActivity" }
-                .toTypedArray()
-        }
+        manifestActivityNames = manifestActivities
+            .map { it.name }
+            .filter { it != "com.ichi2.anki.TestCardTemplatePreviewer" }
+            .filter { it != "com.ichi2.anki.AnkiCardContextMenuAction" }
+            .filter { it != "com.ichi2.anki.analytics.AnkiDroidCrashReportDialog" }
+            .filter { !it.startsWith("androidx") }
+            .filter { !it.startsWith("org.acra") }
+            .filter { !it.startsWith("leakcanary.internal") }
+            .filter { it != "com.canhub.cropper.CropImageActivity" }
+            .toTypedArray()
+
         MatcherAssert.assertThat(testedActivityClassNames, Matchers.containsInAnyOrder(*manifestActivityNames))
     }
 }
Index: AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt b/AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt	(revision 900a64a543e42cded4baf1c684a789786c5e8648)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt	(date 1730401043023)
@@ -144,7 +144,10 @@
      */
     fun checkWebviewVersion(packageManager: PackageManager, activity: AnkiActivity) {
         val webviewPackageInfo = getAndroidSystemWebViewPackageInfo(packageManager) ?: return
-        val webviewVersion = webviewPackageInfo.versionName ?: return
+        val webviewVersion = webviewPackageInfo.versionName ?: run {
+            Timber.w("Failed to obtain WebView version")
+            return
+        }
         val versionCode = webviewVersion.split(".")[0].toInt()
         if (versionCode >= OLDEST_WORKING_WEBVIEW_VERSION) {
             Timber.d("WebView is up to date. %s: %s", webviewPackageInfo.packageName, webviewPackageInfo.versionName)
Index: AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt	(revision 900a64a543e42cded4baf1c684a789786c5e8648)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt	(date 1730400832986)
@@ -248,8 +248,7 @@
                 Timber.w("Could not get WebView package information")
                 return webViewInfo
             }
-            val webviewVersionName = pi.versionName
-            if (webviewVersionName != null) webViewInfo[WEBVIEW_VER_NAME] = webviewVersionName
+            pi.versionName?.let { versionName -> webViewInfo[WEBVIEW_VER_NAME] = versionName }
             webViewInfo["WEBVIEW_VER_CODE"] = PackageInfoCompat.getLongVersionCode(pi).toString()
         } catch (e: Throwable) {
             Timber.w(e)
Index: AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt b/AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
--- a/AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt	(revision 900a64a543e42cded4baf1c684a789786c5e8648)
+++ b/AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt	(date 1730401293795)
@@ -103,9 +103,8 @@
         return if (packageName != null) {
             try {
                 val info = pm.getPackageInfoCompat(packageName, PackageInfoFlagsCompat.EMPTY) ?: return false
-                val appInfo = info.applicationInfo
-                appInfo != null &&
-                    appInfo.flags and ApplicationInfo.FLAG_SYSTEM != 0
+                val appInfo = info.applicationInfo ?: return false
+                appInfo.flags and ApplicationInfo.FLAG_SYSTEM != 0
             } catch (e: PackageManager.NameNotFoundException) {
                 Timber.w(e)
                 false
Index: AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.kt b/AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.kt
--- a/AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.kt	(revision 900a64a543e42cded4baf1c684a789786c5e8648)
+++ b/AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.kt	(date 1730401583436)
@@ -62,10 +62,9 @@
             val context: Context = applicationInstance ?: return pkgVersion
             try {
                 val pInfo = context.getPackageInfoCompat(context.packageName, PackageInfoFlagsCompat.EMPTY) ?: return pkgVersion
-                val versionName = pInfo.versionName
-                if (versionName != null) pkgVersion = versionName
+                return pInfo.versionName ?: pkgVersion
             } catch (e: PackageManager.NameNotFoundException) {
-                Timber.e(e, "Couldn't find package named %s", context.packageName)
+                Timber.w(e, "Couldn't find package named %s", context.packageName)
             }
             return pkgVersion
         }
```

2024-10-31 19:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
> +                    appInfo.flags and ApplicationInfo.FLAG_SYSTEM != 0
Nothingburger of a suggestion. 

Note: I don't particularly like this method - `false` doesn't mean "no", it means "don't know", but this works with the current usages

```suggestion
                val appInfo = info.applicationInfo ?: return false
                appInfo.flags and ApplicationInfo.FLAG_SYSTEM != 0
```

2024-10-31 19:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.kt
> +                }
ditto with `?.let`

2024-10-31 19:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.kt
>              }
Although this is a candidate for a later rewrite

```kotlin
    val pkgVersionName: String
        get() {
            var pkgVersion = "?"
            val context: Context = applicationInstance ?: return pkgVersion
            try {
                val pInfo = context.getPackageInfoCompat(context.packageName, PackageInfoFlagsCompat.EMPTY) ?: return pkgVersion
                return pInfo.versionName ?: pkgVersion
            } catch (e: PackageManager.NameNotFoundException) {
                Timber.w(e, "Couldn't find package named %s", context.packageName)
            }
            return pkgVersion
        }
```

2024-10-31 19:14 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
>          val manifestActivities = packageInfo.activities
Prefer 

```kotlin
        val manifestActivities = packageInfo.activities ?: throw IllegalStateException("packageInfo.activities failed")
```

2024-10-31 19:41 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +            if (webviewVersionName != null) webViewInfo[WEBVIEW_VER_NAME] = webviewVersionName
yeah, if there's a default function param (it) no reason to conjure a new one just for naming

2024-10-31 19:42 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        val webviewVersion = webviewPackageInfo.versionName ?: return
I like it, if there's a problem we'll see it in logcat on crash reports

2024-10-31 19:43 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.kt
> +                }
that's the idiomatic kotlin I new existed but couldn't conjure without seeing it. flows much more nicely to have those little nullish continuations

2024-10-31 19:43 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.kt
>              }
I thought same but was going non-functional as strictly as possible

2024-10-31 20:29 UTC, mikehardy commented
applied patch, then did the manual change to the slightly preferred initial activity and the second ?.let on version util - much cleaner I think

2024-11-01 01:48 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
> +        var manifestActivityNames: Array<String> = emptyStringArray(0)
Couple of lines which no longer need to be changed here. I'll force push these and merge when I'm back at my PC

2024-11-01 02:13 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
> +        var manifestActivityNames: Array<String> = emptyStringArray(0)
Before & after

```patch
Index: AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt	(revision c59627ab268c0745ef43e739198b7079f16fd57e)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt	(revision 0a865153d61e0e85c655c1f0c3f86e6d7a28bb1e)
@@ -20,6 +20,7 @@
 import com.ichi2.compat.CompatHelper.Companion.getPackageInfoCompat
 import com.ichi2.compat.PackageInfoFlagsCompat
 import com.ichi2.testutils.ActivityList
+import com.ichi2.utils.emptyStringArray
 import org.hamcrest.MatcherAssert
 import org.hamcrest.Matchers
 import org.junit.Test
@@ -33,9 +34,11 @@
 
         // we can't access this in a static context
         val packageInfo = targetContext.getPackageInfoCompat(targetContext.packageName, PackageInfoFlagsCompat.of(PackageManager.GET_ACTIVITIES.toLong())) ?: throw IllegalStateException("getPackageInfo failed")
-        val manifestActivities = packageInfo.activities
+
+        val manifestActivities = packageInfo.activities ?: throw IllegalStateException("activity list")
         val testedActivityClassNames = ActivityList.allActivitiesAndIntents().map { it.className }.toSet()
-        val manifestActivityNames = manifestActivities
+        var manifestActivityNames: Array<String> = emptyStringArray(0)
+        manifestActivityNames = manifestActivities
             .map { it.name }
             .filter { it != "com.ichi2.anki.TestCardTemplatePreviewer" }
             .filter { it != "com.ichi2.anki.AnkiCardContextMenuAction" }
@@ -45,6 +48,7 @@
             .filter { !it.startsWith("leakcanary.internal") }
             .filter { it != "com.canhub.cropper.CropImageActivity" }
             .toTypedArray()
+
         MatcherAssert.assertThat(testedActivityClassNames, Matchers.containsInAnyOrder(*manifestActivityNames))
     }
 }
```

```patch
Index: AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt	(revision c59627ab268c0745ef43e739198b7079f16fd57e)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt	(revision 48d62eae9aea1c83708880ff845e537bd266c904)
@@ -33,9 +33,9 @@
 
         // we can't access this in a static context
         val packageInfo = targetContext.getPackageInfoCompat(targetContext.packageName, PackageInfoFlagsCompat.of(PackageManager.GET_ACTIVITIES.toLong())) ?: throw IllegalStateException("getPackageInfo failed")
-        val manifestActivities = packageInfo.activities
+        val manifestActivities = packageInfo.activities ?: throw IllegalStateException("activity list")
         val testedActivityClassNames = ActivityList.allActivitiesAndIntents().map { it.className }.toSet()
-        val manifestActivityNames = manifestActivities
+        var manifestActivityNames: Array<String> = manifestActivities
             .map { it.name }
             .filter { it != "com.ichi2.anki.TestCardTemplatePreviewer" }
             .filter { it != "com.ichi2.anki.AnkiCardContextMenuAction" }
```

2024-11-01 02:21 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
> +        var manifestActivityNames: Array<String> = emptyStringArray(0)
cleaner - thank you

2024-11-01 02:22 UTC, mikehardy commented
should have seen the ability to minimize that change myself - but was rushing through this to get back to my gradle-de-deprecation fiesta  🧹 🧹

2024-11-01 03:01 UTC, david-allison approved these changes
cheers!

2024-11-01 03:01 UTC, merged