Fix: Enable multi-line support for the deck picker footer
ankidroid/Anki-Android pull request #17349
Opened 2024-11-02 12:47 UTC by Aditya13s

## Purpose / Description
The purpose of this change is to allow the footer of the deck picker to display multiple lines of text.

## Fixes
* Fixes #17100

## Approach
The `setSingleLine` method has been removed from the `DeckPicker.kt` file to allow the footer text to display across multiple lines. Additionally, a `.replace` function was implemented to ensure that newline characters in the text from `sched.studiedToday()` are replaced with spaces, preventing any text from being hidden.

## How Has This Been Tested?
This change has been tested using different font sizes and languages.

## Screenshot
![multiline_footer](https://github.com/user-attachments/assets/b5cd6296-c248-45e7-84a1-2d8a43bebb65)

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-11-02 21:40 UTC, Arthur-Milchior approved these changes
Thank you very much. I appreciate the improvement.

I'll admit that, having the text below the + symbol is not ideal. It's still readable, and I don't expect that this bug is worth doing more effort to find a better design to solve it!

2024-11-02 21:40 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> -                sched.studiedToday()
I'd really love a comment to explain the reason of the replace.
Probably something such as:
> the backend returns a string such as 
> "Studied 1 cards in 5 seconds today
> (5s/card)"
> Let's imitate anki, save estate, and put the text on a single line if possible

2024-11-02 22:16 UTC, BrayanDSO requested changes
Kind of similar to what was proposed in #16965, so the comments about the screen edges made by `@lukstbit` still stands.

Also, the screenshot in the PR description evidently shows that the text can be hidden by the `Add` button

2024-11-03 09:22 UTC, Aditya13s commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> -                sched.studiedToday()
![footer](https://github.com/user-attachments/assets/33f22492-3d20-4d8c-94dd-ee737f8992bd)
After removing the `reviewSummaryTextView.setSingleLine()` the footer looks like this. So simplest approach which hits my mind is to use `replace()` function.

2024-11-03 09:34 UTC, Aditya13s commented
> Kind of similar to what was proposed in #16965, so the comments about the screen edges made by `@lukstbit` still stands.
> 
> Also, the screenshot in the PR description evidently shows that the text can be hidden by the `Add` button

As @Arthur-Milchior mentioned, this bug isn’t worth further effort and can be addressed in #17334, which completes the migration to edge-to-edge.

2024-11-03 12:52 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> -                sched.studiedToday()
When I say I want a comment, especially if I put the request for change at a specific line of the code, it means that I want the comment to be in the code.
So that the next person that reads the code can figure out what was going on

2024-11-03 12:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> -                sched.studiedToday()
Also what matters in the comment is to note that the backend returns a value with a newline.
Upstream, the value is used in HTML page, so it does not matter. Here, we need to pay attention to it as the newline would be shown by Android's UI

2024-11-03 13:17 UTC, Arthur-Milchior commented
@Aditya13s I don't have more authority than @BrayanDSO. I have approved this, but we usually wants to reviewer, and so if the other reivewer does not appreciate, this is up to discussion. 
I'm pretty sure Brayan was able to read what I wrote, and simply disagree. He has good argument I didn't even know about (edge-to-edge).

@BrayanDSO Can I ask what would be your preferred solution regarding the button?
Moving it, by ensuring it's above the text? Having the text width be small enough that it does not overlap with the button? (I'd fear we end up needing 3 lines if we don't allow the text to cover the full width of the screen)
I guess we can use `Rect.intersects` on the rectangle of the text view and the FAB to check whether they intersect, and reduce the width only if it's the case. Not very elegant but it would work.

> can be addressed in https://github.com/ankidroid/Anki-Android/issues/17334, which completes the migration to edge-to-edge.

Yeah, but in this case, there is not even a point of landing your change if we suspect we may need to change the result soon after. We should try to fix #14641 simultaneously, given that it consider the same part of the UI.

To be clear, I still believe that your change is an improvement compared to the current state. After all, the total quantity of missing text is quite smaller. But I prefer to have a single merged change that deals with all the issues related to this text view simultaneously

2024-11-05 23:25 UTC, BrayanDSO commented
> Moving it, by ensuring it's above the text?

Yes. I believe that it can be easily done by editing only the layout files. There shouldn't be a need to do it programmatically

2024-11-08 16:57 UTC, lukstbit requested changes
> this bug isn’t worth further effort and can be addressed in https://github.com/ankidroid/Anki-Android/issues/17334, which completes the migration to edge-to-edge.

Edge to edge becoming the default affects the interaction between the info text and the screen borders. The bug in the picture isn't related to edge to edge, it's related to the changes you've made in this PR and the interaction between the info text and the fab. So the current "fix" only fixes the issue partially and would result in a new bug report in the near future.

2024-11-12 13:18 UTC, Aditya13s commented
![Screenshot From 2024-11-12 02-05-42](https://github.com/user-attachments/assets/af6f8586-fd41-44b3-aa75-958fa80e5aaf)

Setting the CoordinatorLayout elevation of the Floating Action Button (FAB) to -1dp gives the right look, but it makes the FAB unclickable because it ends up behind other views.

2024-11-12 13:28 UTC, lukstbit commented
There should be enough space made available for the info text between the screen margin and fab button. It shouldn't be visible below or above the fab button.

2024-11-12 16:52 UTC, Aditya13s commented
![footer](https://github.com/user-attachments/assets/333ce723-4905-4039-b503-94b335242474)
This is the final output

2024-11-12 23:39 UTC, Arthur-Milchior commented
Clearly this result looks nicer. I admit I regret that it moves the FAB even when the text is small. I'd have preferred if we had a way to ensure it remains at the same place if possible.

I admit I really don't know XML layout enough to know how to do that.
I guess we should have a RelativeLayout that contains the `today_stats_text_view` at the bottom, and a layout that contains both the deck list and the fab at the top.
But that needs a serious rewrite of deck_picker.xml

2024-11-14 13:56 UTC, BrayanDSO submitted a review, later dismissed

2024-11-14 13:56 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
>              }
this hardcoded approach may not fit well all the screen sizes. 

Putting the FAB above the footer should be simple with most Android layouts (LinearLayout, CoordinatorLayout, RelativeLayout, ConstraintLayout).

2024-11-14 16:41 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
>              }
Definitely not impossible, nor too difficult to justify doing a hack that will fall short soon

2024-11-18 10:52 UTC, Aditya13s commented
@BrayanDSO Please review the changes

2025-01-06 17:13 UTC, Aditya13s commented
@david-allison needs review

2025-01-06 18:31 UTC, david-allison commented
@Aditya13s is it feasible to find another reviewer, this is one I'm not confident about

2025-01-07 09:56 UTC, lukstbit requested changes
While this does seem to work, we could end up with a memory leak/crash.

The listener isn't removed so basically runs on every frame drawn(even if most of the time it will not do anything). Even worse, a NEW listener is added EVERY time the decks are changed so we could end up with hundreds of these listeners running.

2025-01-07 16:55 UTC, Aditya13s commented
> While this does seem to work, we could end up with a memory leak/crash.
> The listener isn't removed so basically runs on every frame drawn(even if most of the time it will not do anything). Even worse, a NEW listener is added EVERY time the decks are changed so we could end up with hundreds of these listeners running.

Fixed this problem by removing the listener after adjusting the bottom margin.

2025-01-09 06:46 UTC, lukstbit reviewed
It doesn't seem to work every time:


https://github.com/user-attachments/assets/1f5650be-6464-4825-a678-570784e83d6b

2025-01-11 08:45 UTC, Aditya13s commented
@lukstbit I think moving this to the onStart() function will fix the problem.

2025-01-12 09:58 UTC, lukstbit approved these changes
LGTM, thanks.

2025-01-12 10:14 UTC, merged