minSdk 24
ankidroid/Anki-Android pull request #17364
Opened 2024-11-06 04:11 UTC by mikehardy

## Purpose / Description

Bumps our minSdk to 24, the commits have a bit more info

## Approach

bump the SDK
inline the compat stuff I can inline
inline the resources that are now mainline vs v24
remove the version checks no longer needed

## How Has This Been Tested?

Just keep running gradle targets (`./gradlew lint`) is especially helpful as it checks unnecessary SDK checks

## Learning (optional, can help others)

coding is a good distraction

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-11-07 06:54 UTC, david-allison requested changes
All looks good.

Patch contains various minor nitpicks as I was reviewing

One request with the `Shortcut[Group]`, as that feels big enough for its own commit, and the code feels too heavy for `AnkiActivity`

```patch
Subject: [PATCH] 
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.kt b/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.kt	(revision a0c8689b193165f444da968a1031d37b9c92b144)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.kt	(date 1730961490260)
@@ -103,15 +103,12 @@
     }
 
     fun pause() {
-        if (!this::recorder.isInitialized) {
-            return
-        }
+        if (!this::recorder.isInitialized) return
         recorder.pause()
     }
 
     fun resume() {
-        if (this::recorder.isInitialized) {
-            recorder.resume()
-        }
+        if (!this::recorder.isInitialized) return
+        recorder.resume()
     }
 }
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelEditorContextMenu.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelEditorContextMenu.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelEditorContextMenu.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelEditorContextMenu.kt	(revision a0c8689b193165f444da968a1031d37b9c92b144)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelEditorContextMenu.kt	(date 1730961490255)
@@ -23,8 +23,7 @@
     @SuppressLint("CheckResult")
     override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
         super.onCreate(savedInstanceState)
-        var availableItems = ModelEditorContextMenuAction.entries.toList()
-        availableItems = availableItems.sortedBy { it.order }
+        val availableItems = ModelEditorContextMenuAction.entries.sortedBy { it.order }
 
         return AlertDialog.Builder(requireActivity()).create {
             setTitle(requireArguments().getString(KEY_LABEL))
Index: AnkiDroid/src/androidTest/java/com/ichi2/anki/TtsVoicesTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/androidTest/java/com/ichi2/anki/TtsVoicesTest.kt b/AnkiDroid/src/androidTest/java/com/ichi2/anki/TtsVoicesTest.kt
--- a/AnkiDroid/src/androidTest/java/com/ichi2/anki/TtsVoicesTest.kt	(revision a0c8689b193165f444da968a1031d37b9c92b144)
+++ b/AnkiDroid/src/androidTest/java/com/ichi2/anki/TtsVoicesTest.kt	(date 1730961490275)
@@ -17,7 +17,6 @@
 package com.ichi2.anki
 
 import androidx.test.ext.junit.runners.AndroidJUnit4
-import com.ichi2.anki.AndroidTtsVoice.Companion.normalize
 import com.ichi2.anki.tests.InstrumentedTest
 import org.hamcrest.CoreMatchers.equalTo
 import org.hamcrest.MatcherAssert.assertThat
@@ -30,7 +29,7 @@
     @Test
     fun normalize() {
         fun assertEqual(l: Locale, str: String) {
-            val normalized = normalize(l)
+            val normalized = AndroidTtsVoice.normalize(l)
             assertThat(normalized.toLanguageTag(), equalTo(str))
         }
 
Index: AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt	(revision a0c8689b193165f444da968a1031d37b9c92b144)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt	(date 1730962022591)
@@ -472,6 +472,7 @@
     }
 
     private fun localeHintDialog() {
+        Timber.i("displaying locale hint dialog")
         // We don't currently show the current value, but we may want to in the future
         val dialogFragment: DialogFragment = LocaleSelectionDialog.newInstance(this)
         showDialogFragment(dialogFragment)

```

2024-11-07 06:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt
> +        private val twoLetterSystemLocaleMapping: Map<String, Locale>
Add a TODO to move these into a separate object - obvious coupling between the methods, the `init {}` block and this field

2024-11-08 18:58 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
> +open class CompatV24 : Compat {
I like that idea, thank you!
That combined with not re-homing all the shortcut stuff into AnkiActivity will make it pretty reasonable

2024-11-11 01:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt
> +        private val twoLetterSystemLocaleMapping: Map<String, Locale>
Added a TODO

2024-11-11 01:20 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
> +open class CompatV24 : Compat {
This is great, thank you @Arthur-Milchior 

I've implemented it

2024-11-11 12:43 UTC, david-allison commented
Force pushed a change to `AndroidManifest.xml` regarding drag & drop untested

2024-11-11 12:46 UTC, mikehardy reviewed
LGTM, cleaner commit setup, as hoped for with suggestion for BaseCompat (thanks Arthur) and splitting the shortcut stuff (thanks David)

2024-11-11 12:46 UTC, mikehardy commented
It's still technically my PR so I can't +1 it but I'm +1

2024-11-11 12:57 UTC, david-allison commented
Lint failure, mayve from my Manifest change. I don't see how

```
  Lint found 272 errors, 0 warnings. First failure:
  
  /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-ca/01-core.xml:59: Error: For locale "ca" (Catalan) the following quantity should also be defined: many [MissingQuantity]
      <plurals name="reviewer_window_title">
      ^
```

2024-11-11 23:21 UTC, mikehardy commented
I think between the 3 of us we've all actually contributed to it and all ideas are ingested now, with CI green. I've re-read it, looks good to go

2024-11-11 23:21 UTC, merged