Test that all TS backend functions are handled
ankidroid/Anki-Android pull request #17371
Opened 2024-11-07 15:33 UTC by voczi

## Purpose / Description
Make sure that we do not update to newer Anki backend versions where the names of TS functions do not correlate to the mappings we have set in PostRequestHandler. Otherwise, we would have to manually go and check for any such change in the Anki repo. If we don't do this, then functionality in some of the Svelte pages might be straight up unsupported, and we wouldn't know about this until we actually test the affected component.

## Fixes
N/A.

## Approach
Refactor PostRequestHandler so the switch-statement takes the form of a hash map instead. Then, in PostRequestHandlerTest, use list of TS functions generated from the AnkiDroid backend (https://github.com/ankidroid/Anki-Android-Backend/pull/434) to find out what function mappings we are supposed to have.

## How Has This Been Tested?
Just made sure that the tests passed and made sure we have mappings for all the backend functions.
For the first few lists of backend functions, I found some inconsistencies with my parsing code in the AnkiDroid backend and subsequently fixed this (https://github.com/ankidroid/Anki-Android-Backend/pull/437).

## Learning (optional, can help others)
Tree-sitter is some interesting stuff.
https://github.com/tree-sitter/tree-sitter
https://tree-sitter.github.io/tree-sitter/playground

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2024-11-07 15:47 UTC, voczi commented
Two problems:

- Emulator tests fail because some extension functions are not deemed necessary to keep around by Proguard. Probably because I am mocking the Collection class only.
- For some reason, my local list of exported TS backend functions deviate from the one produced by the Ankidroid backend repository.

2024-11-07 18:23 UTC, voczi commented
Should be good now.

2024-11-07 20:49 UTC, lukstbit requested changes

2024-11-07 20:49 UTC, lukstbit commented on .idea/dictionaries/voczi.xml
> +      <w>funcs</w>
Add this word to one of the already existing dictionaries like _android.xml_.

2024-11-07 20:49 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +fun FragmentActivity.uiMethods() = hashMapOf(
This modifies production code just for testing and I think it does this at the cost of worse readability.

Do we really need these mappings? Wouldn't a simple test(not Robolectric) where we fetch the backend functions and then compare them with a know static list(kept in the test itself)be simpler and faster?
The backend updates are usually done by David or Mike and I don't see either seeing the test failing and just updating that list and ignoring the actual work to create a mapping.

2024-11-07 21:08 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +fun FragmentActivity.uiMethods() = hashMapOf(
We would then be testing functionality that would not necessarily represented in production code. I think your suggestion goes against the point of this work.

2024-11-07 22:08 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +fun FragmentActivity.uiMethods() = hashMapOf(
I prefer that it's automatic + derived live during backend build and from code vs a list

I would go slightly further and say one of the things I like about it being dynamic like that is that we could also check that the mapping is in fact 1-to-1, that is it could signal when a mapping should go away, whereas no static list maintenance would quickly see that. @voczi do you think you could also assert that the combined funcs list is the same size as exported funcs list from backend? That would be a pretty strong guarantee of correctness

The readability is definitely a regression as things are 3 times as long but it seems like that could be managed perhaps with a small helper utility or something such that the actual creation of entries was one line again? Surely with as fancy as kotlin is there could be some sort of syntactic sugar available to one-line it again?

2024-11-07 23:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +fun FragmentActivity.uiMethods() = hashMapOf(
**We have**:

* `ts_funcs.txt`: A list of functions we want to call
* `Collection.kt`: Exposes all available backend functions
* `PostRequestHandler`: Exposes a subset of 'safe' backend functions to the web UI

**We want**:

* `PostRequestHandler` should only call functions in `ts_funcs.txt`
* All functions in `ts_funcs.txt` should be exposed in `PostRequestHandler`

**Issue**:

* A unit test can't determine the function calls which `PostRequestHandler` makes, so we have to make code quality compromised
* The list of 'safe' functions 
  * is unavailable at runtime
  * is not a 1:1 match with the collection method names

**Proposal**:

* A lint rule **can** walk the AST
* Mark all 'UI-safe' methods in the collection with an `@Annotation`
  * A unit test ensures all these methods match `ts_funcs`
* Write a lint rule which ensures and enforces:
  * Each annotated method in the collection is called from `PostRequestHandler`  
  * Calling a non-annotated collection/backend method is an error

**Potential issues**:

A couple of extension methods (e.g. `searchInBrowser`) will need to either be rehomed, or special-cased

I don't think this would be too time-consuming to implement or costly in terms of performance, as we're only walking the AST of `PostRequestHandler`, and accessing `Collection.kt` via reflection

I can't think of a simpler acceptable solution, but feel this is on the edge of 'too complex'

Strongly encouraged to tear the idea apart

2024-11-07 23:22 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +fun FragmentActivity.uiMethods() = hashMapOf(
On second thought, I believe the lint check could be implemented using `@StringDef`, which significantly simplifies it

2024-11-08 08:15 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +fun FragmentActivity.uiMethods() = hashMapOf(
@mikehardy Just a quick comment re: readability. I totally agree. It looks horrible. The original code I wrote had the mappings as one-liners, but it used function references (i.e. reflection) so I wanted to find something else to avoid dealing with PG.
There has to be some synthatic sugar for this, as you mentioned. I'll spend some more time looking.

2024-11-08 08:37 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +fun FragmentActivity.uiMethods() = hashMapOf(
Well, wait, one-liners do work.
![image](https://github.com/user-attachments/assets/63d2f708-b627-4635-947c-bb53ac2798ee)
But I'd like to find a way to get rid of the whole "bytes" thing for each and every entry.. Reading something about functional interfaces (?) in Kotlin now.

2024-11-08 09:14 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +fun FragmentActivity.uiMethods() = hashMapOf(
Also re: checking for equal lengths, `containsInAnyOrder` should already deal with this unless I'm misunderstanding the comment for `IsIterableContainingInAnyOrder.containsInAnyOrder`.
![image](https://github.com/user-attachments/assets/82b73b19-f634-4151-8789-f61af8463d98)

2024-11-08 09:15 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +fun FragmentActivity.uiMethods() = hashMapOf(
@david-allison I like the idea of your suggestion and it's something that I felt would be good to include in this PR, but it's currently hard for me to fit the necessary work in my schedule right now.

2024-11-08 12:58 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +fun FragmentActivity.uiMethods() = hashMapOf(
> For a positive match, the examined iterable must be of the same length as the number of specified items

That does look like it handles my desire to make sure that we assert even more strongly than "all required bindings exist" - rather we assert "only all required bindings exist" / "there are no extra bindings"

I guess to truly prove the point an extra containsInAnyOrder assertion could be added immediately after the one we expect to pass, where you add some dummy item to the list of bindings we have then expect a failure? And similarly could add a dummy binding to list of expected bindings and expect a failure. That would probe the guardrails for the assertion pretty thoroughly with just 4 more lines I think (or maybe 8, with addition of two newlines and two comments explaining why you'd do it 😆

2024-11-08 19:19 UTC, mikehardy approved these changes
Adults may disagree (and good for that) but, I think this looks pretty good

fully auto front-end functions list generation on backend repo, fully auto verification of our bindings for those functions here

2024-11-08 19:43 UTC, lukstbit requested changes
Left some minor IDE reported issues.

There are also two methods that became unused in _BackendImporting.kt_. Did you verified that their replacements produce the same outcome as the old methods?

2024-11-08 19:43 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
> +        val collectionMethods = runBlocking { testCollection.collectionMethods() }
These are not suspended functions, you don't need _runBlocking_.

2024-11-08 19:43 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +    var data = uiMethods()[methodName]?.invoke(bytes)?.await()
```suggestion
    val data = uiMethods()[methodName]?.invoke(bytes)?.await()
```

2024-11-08 19:43 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +fun FragmentActivity.uiMethods() = hashMapOf<String, UIBackendInterface>(
You don't need the types here and UIBackendInterface can be deleted as well.

2024-11-08 19:43 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +    "getGraphPreferences" to { bytes -> getGraphPreferencesRaw() },
```suggestion
    "getGraphPreferences" to { _ -> getGraphPreferencesRaw() },
```

2024-11-08 20:01 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +fun FragmentActivity.uiMethods() = hashMapOf<String, UIBackendInterface>(
Forgot to remove type specifier for the bytes param in `uiMethods`. Typealiases can stay, I like the specificity.

2024-11-08 20:02 UTC, voczi commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
> +        val collectionMethods = runBlocking { testCollection.collectionMethods() }
Remnant from the old solution.

2024-11-08 20:08 UTC, voczi commented
Could be that I imported the wrong importCsvRaw? I'll have a look.

2024-11-08 20:25 UTC, voczi commented
Ok, restored functions for importCsv and importAnkiPackage. Then moved them to uiMethods.

2024-11-09 01:29 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +typealias CollectionBackendInterface = (bytes: ByteArray) -> ByteArray
I'd prefer the type to be `Collection.(bytes: ByteArray) ->ByteArray`.
This would ensure that you could have 
```
val collectionMethods = hashMapOf<String, CollectionBackendInterface>(
    "i18nResources" to { bytes -> i18nResourcesRaw(bytes) },
```
and so on.
That's not more verbose. However, that ensures you don't have to re-create a map and closures for each usage. (I actually don't know enough about Kotlin optimization to know whether it creates new map and closure each time. But just in case, it's not worth it in a function that seems to be used a lot)

That would be something such as
```patch
Subject: [PATCH] [PATCH]
---
Index: AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt	(revision 6ea0f3125a1feed59011a3d8f88af96e8efb832f)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt	(date 1731114756983)
@@ -37,10 +37,8 @@
         val tsFuncs = tsFuncsStream.readLines()
         assertThat("List of stored Typescript functions is not empty", tsFuncs.isNotEmpty())
 
-        val testCollection = mock(Collection::class.java)
-        val testActivity = mock(FragmentActivity::class.java)
-        val collectionMethods = testCollection.collectionMethods()
-        val uiMethods = testActivity.uiMethods()
+        val collectionMethods = collectionMethods
+        val uiMethods = uiMethods
         val combined = (collectionMethods + uiMethods).keys
         assertThat(
             "Mapping exists for every TS backend function call",
Index: AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt b/AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt	(revision 6ea0f3125a1feed59011a3d8f88af96e8efb832f)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt	(date 1731114682553)
@@ -24,6 +24,7 @@
 import com.ichi2.anki.importAnkiPackageUndoable
 import com.ichi2.anki.importCsvRaw
 import com.ichi2.anki.launchCatchingTask
+import com.ichi2.anki.pages.collectionMethods
 import com.ichi2.anki.searchInBrowser
 import com.ichi2.libanki.Collection
 import com.ichi2.libanki.completeTagRaw
@@ -51,10 +52,10 @@
     suspend fun handlePostRequest(uri: String, bytes: ByteArray): ByteArray
 }
 
-typealias CollectionBackendInterface = (bytes: ByteArray) -> ByteArray
+typealias CollectionBackendInterface = Collection.(bytes: ByteArray) -> ByteArray
 
 @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
-fun Collection.collectionMethods() = hashMapOf<String, CollectionBackendInterface>(
+val collectionMethods = hashMapOf<String, CollectionBackendInterface>(
     "i18nResources" to { bytes -> i18nResourcesRaw(bytes) },
     "getGraphPreferences" to { _ -> getGraphPreferencesRaw() },
     "setGraphPreferences" to { bytes -> setGraphPreferencesRaw(bytes) },
@@ -87,13 +88,16 @@
 )
 
 suspend fun handleCollectionPostRequest(methodName: String, bytes: ByteArray): ByteArray? {
-    return withCol { collectionMethods()[methodName]?.invoke(bytes) }
+    return withCol {
+        val m = collectionMethods[methodName]?: return@withCol null
+        m(bytes)
+    }
 }
 
-typealias UIBackendInterface = (bytes: ByteArray) -> Deferred<ByteArray>
+typealias UIBackendInterface = FragmentActivity.(bytes: ByteArray) -> Deferred<ByteArray>
 
 @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
-fun FragmentActivity.uiMethods() = hashMapOf<String, UIBackendInterface>(
+val uiMethods = hashMapOf<String, UIBackendInterface>(
     "searchInBrowser" to { bytes -> lifecycleScope.async { searchInBrowser(bytes) } },
     "updateDeckConfigs" to { bytes -> lifecycleScope.async { updateDeckConfigsRaw(bytes) } },
     "importCsv" to { bytes -> lifecycleScope.async { importCsvRaw(bytes) } },
@@ -119,7 +123,8 @@
         return null
     }
 
-    val data = uiMethods()[methodName]?.invoke(bytes)?.await()
+    val m = uiMethods[methodName] ?: return null
+    val data = m(bytes).await()
     when (methodName) {
         "addImageOcclusionNote", "updateImageOcclusionNote" -> {
             undoableOp { OpChanges.parseFrom(data) }
```

2024-11-09 01:29 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +typealias UIBackendInterface = (bytes: ByteArray) -> Deferred<ByteArray>
same here of course

2024-11-09 01:29 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/BackendImporting.kt
> +suspend fun FragmentActivity.importAnkiPackageUndoable(input: ByteArray): ByteArray {
I don't understand what's the point of ensuring it's a method of FragmentActivity. That does not seems to be used

2024-11-09 01:29 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                    closeNoteEditor(Activity.RESULT_OK, null)
I admit that I don't understand how this relate to the fact that TS backend functions are handled correctly.

I'd really appreciate maybe a little bit more comment in the commit message to explain the changes that are not directly related to introducing new backend call

2024-11-09 01:29 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
> +        val tsFuncsStream = InputStreamReader(assetManager.open("backend/ts_funcs.txt"))
I'd really love some help here. I can't find this file. So I assume it's generated automatically, which seems great.
Maybe a one-line comment with a link showing how or where this file is generated, or to the file content directly, would be nice.

2024-11-09 01:29 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
> +            "Mapping does not exist for an extra local dummy TS function",
It seems that you are actually testing that the set of local function and of TS function are equal.
Otherwise, it would not be an issue that "meow" was defined locally (and never used)

If it is the case, then you may want to change the name of the test. Because it seems that you are only checking that all TS functions can be used. The name does not state that you don't accept extra function.

Also, if you really want equality, may I suggest either:
* transforming them into set and checking for equality
* sorting the list alphabetically and checking for equality

That will be more clear

2024-11-09 04:59 UTC, voczi commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
> +        val tsFuncsStream = InputStreamReader(assetManager.open("backend/ts_funcs.txt"))
It should be in the assets folder of the APK. Just like any other web artifact that's bundled into the app.

2024-11-09 05:00 UTC, voczi commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
> +            "Mapping does not exist for an extra local dummy TS function",
I think the addition of the extra assertions were unnecessary and the original assert with `containsInAnyOrder` should already do the trick. Reverting.

2024-11-09 05:46 UTC, Arthur-Milchior approved these changes

2024-11-09 05:46 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
> +        val collectionMethods = collectionMethods
Those two values are not really needed anymore. 
I'd go with 
```
        val postRequestHandlers = tsFuncs
        assertThat(
            "Mapping exists for every TS backend function call",
            tsFuncs,
            containsInAnyOrder(postRequestHandlers)
        )
```

2024-11-09 05:46 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
> +    fun `All backend typescript functions should be handled`() {
I find the name `containsInAnyOrder` confusing. It tests for equality and not containment (which, for container, would probably mean inclusion)

So actually, you're testing for equality.
Which makes quite a lot of sense. That ensure that if a method ever disappear from upstream, we detect it and don't leave it in the map uselessly. And so we get a warning if the method was not used anywhere else.

My point being, the title of the test is not exact. You may want to rename it as
```
fun `backend typescript functions are exactly collection+ui methods`
```
or at least add a comment that state that you are testing for equality of those lists

2024-11-09 06:28 UTC, voczi commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
> +        val collectionMethods = collectionMethods
Sorry, what?

2024-11-09 06:29 UTC, voczi commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
> +    fun `All backend typescript functions should be handled`() {
Equality means that the collections are specified in the exact same order. So no, this is not what I am testing here (nor what we should be testing).

2024-11-09 12:44 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
> +            containsInAnyOrder(combined)
All of this faff about "make sure if you add one to either list and compare with original it fails" and Arthur's mention that the test name doesn't match the intention are the same problem, and I don't think you get to just resolve those. The person that made the comment gets to resolve, not you the responder, because they are not resolved.

The fundamental issue is that the assertion you are using is confusing, it confused me, it confused Arthur, and it is still confusing, it is not resolved.

This at the minimum needs a comment on top of the usage of containsInAnyOrder that says "this assertion makes sure not only that each element in one list is present in the other but also makes sure the size is the same.

Or something like that.

And the test could be renamed something like "Verify all backend functions have one mapping, with no extra mappings" or similar

Do not resolve this until everyone agrees they actually understand it please

2024-11-09 12:46 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
> +        val tsFuncsStream = InputStreamReader(assetManager.open("backend/ts_funcs.txt"))
Similar to the other one, you don't get to mark this resolved because you didn't resolve it - a comment here is not resolution it's just ephemeral stuff that no one will look at

Proper resolution - I assume on Arthur's behalf - would be something like a clarifying comment like

```kotlin
// read auto-generated list of all typescript funcs created+packaged during backend build
```

2024-11-09 13:10 UTC, voczi commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
> +            containsInAnyOrder(combined)
I will let people take their time to understand the documentation of the functions in question. Thank you!

2024-11-09 14:07 UTC, mikehardy requested changes

2024-11-09 14:07 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
> +            containsInAnyOrder(combined)
If multiple people are confused, a clarifying comment is an easy way to eliminate confusion

My approval was contingent on clarification of what this assertion is doing and since I didn't trust it I proposed a test that probed failure if there were extra elements or missing elements, and I approved that.

That was reverted - which is fine, but only if my original confusion on what the extent of this assertion does is clarified for a Future Me where I've forgotten why this incompletely named assertion was adequate to protect against a future state where the ts funcs list has shrunk and we have stale bindings laying around, incurring maintenance cost for no reason

Clarifying comment suggestion that would satisfy my concern:

```suggestion
            // this matcher asserts equality in everything but order, no extras, nothing missing
            containsInAnyOrder(combined)
```

2024-11-09 14:37 UTC, lukstbit requested changes

2024-11-09 14:37 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +    val data = m(bytes).await()
For _addImageOcclusionNote_ and _updateImageOcclusionNote_ you are executing them two times, once here and once below in their respective when clauses which introduces a serious bug. The second call needs to be removed.

2024-11-09 14:40 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +    val data = m(bytes).await()
You're completely right. Good stuff.

2024-11-09 14:46 UTC, voczi commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
> +        val collectionMethods = collectionMethods
@Arthur-Milchior Clarification would be good.

2024-11-09 14:57 UTC, voczi commented
In need of a clarification from @Arthur-Milchior regarding a change suggestion. Don't merge until it's answered. https://github.com/ankidroid/Anki-Android/pull/17371#discussion_r1835418119

2024-11-09 15:06 UTC, lukstbit approved these changes
Ok, from me with the note below.

2024-11-09 15:06 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
>              data
Here and in the other case below the line _data_ should be removed as it's unused code. Sorry for being pedantic about this but we have an open issue about fixing these IDE reported warnings and I would prefer if we solve them in the PRs that touch the code so the files become clean.

2024-11-09 15:08 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
>              data
No worries

2024-11-09 15:39 UTC, voczi commented
CI needs a re-run (flaky custom scheduler test)

2024-11-09 15:49 UTC, mikehardy commented
unrelated flake, this one keeps popping up despite original de-flake attempt then follow-on "hey new reviewer is toggled on?"

```

com.ichi2.anki.ReviewerFragmentTest > testCustomSchedulerWithCustomData[emulator-5554 - 11] FAILED 
	java.lang.AssertionError: View assertion was not true within 30000 milliseconds
	at org.junit.Assert.fail(Assert.java:89)

```

re-running

2024-11-09 17:50 UTC, mikehardy approved these changes
my initial confusion about the full guarantee that matcher provides is handled, thanks

Looks we're down to just a " 🤔  what exactly do you mean?" for Arthur

2024-11-09 21:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +        val m = collectionMethods[methodName] ?: return@withCol null
nit: I don't think this needs to be inside the `withCol` as it doesn't use the collection

nit: could you name it `method`, for clarity

2024-11-09 21:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +        val m = collectionMethods[methodName] ?: return@withCol null
Could you `Timber.w` stating that an unknown method was called

And include the method name in a `Timber.d` (`.d` isn't active production)

2024-11-09 21:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
> +    val m = uiMethods[methodName] ?: return null
ditto on the timber, typically done using 

```
?: run { 
    Timber.w
    return 
}
```

2024-11-09 21:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> +    fun <ByteArray> backendIdentity(bytes: ByteArray): ByteArray = bytes
architecture: I'd move this out of the collection, and into `PostRequestHandler` - it's not in the backend and won't be useful anywhere else

2024-11-09 21:43 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
> +            containsInAnyOrder(combined)
I'd write an alias to this method in `AnkiAssert`, calling it `containsExactlyInAnyOrder` (or similar).

Therefore we won't need a comment, and the intention and functionality is more clear. We're working around `Hamcrest`'s naming/conventions here no matter what we do.

2024-11-09 21:43 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
> +        assertThat("List of stored Typescript functions is not empty", tsFuncs.isNotEmpty())
Typically in Hamcrest, you typically don't want to pass in a boolean and instead want to pass in a matcher

```suggestion
        assertThat("Stored TypeScript functions", tsFuncs, not(empty()))
```

Which produces a better error:
```
Stored Typescript functions
Expected: not an empty collection
     but: was <[]>
java.lang.AssertionError: Stored Typescript functions
Expected: not an empty collection
     but: was <[]>
```

Note that `empty()` and `not()` are imports from `Hamcrest`

2024-11-09 21:43 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
> +        val collectionMethods = collectionMethods
possibly something like:

```patch
Index: AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt	(revision 275f66d9f228cf7cd712eb744533a50d98974b5f)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt	(date 1731188157051)
@@ -20,6 +20,8 @@
 import com.ichi2.anki.RobolectricTest
 import com.ichi2.testutils.HamcrestUtils.containsInAnyOrder
 import org.hamcrest.MatcherAssert.assertThat
+import org.hamcrest.Matchers.empty
+import org.hamcrest.Matchers.not
 import org.junit.Test
 import org.junit.runner.RunWith
 import java.io.InputStreamReader
@@ -28,20 +30,21 @@
 class PostRequestHandlerTest : RobolectricTest() {
     @Test
     fun `All backend typescript functions should be handled`() {
-        val assetManager = targetContext.assets
-        // read auto-generated list of all typescript funcs created+packaged during backend build
-        val tsFuncsStream = InputStreamReader(assetManager.open("backend/ts_funcs.txt"))
-        val tsFuncs = tsFuncsStream.readLines()
-        assertThat("List of stored Typescript functions is not empty", tsFuncs.isNotEmpty())
-
-        val collectionMethods = collectionMethods
-        val uiMethods = uiMethods
-        val combined = (collectionMethods + uiMethods).keys
         assertThat(
             "Mapping exists for every TS backend function call",
-            tsFuncs,
+            typescriptFunctionsUsedByBackend,
             // this matcher asserts equality in everything but order, no extras, nothing missing
-            containsInAnyOrder(combined)
+            containsInAnyOrder((collectionMethods + uiMethods).keys)
         )
     }
+
+    /**
+     * Auto-generated list of all typescript funcs created & packaged during backend build
+     */
+    private val typescriptFunctionsUsedByBackend : List<String> =
+        InputStreamReader( targetContext.assets.open("backend/ts_funcs.txt")).use {
+            it.readLines().also { lines ->
+                assertThat("Stored Typescript functions", lines, not(empty()))
+            }
+        }
 }
```

2024-11-09 21:43 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt
> +        val tsFuncsStream = InputStreamReader(assetManager.open("backend/ts_funcs.txt"))
nit: this is `Closeable`, but never closed

2024-11-10 13:48 UTC, david-allison approved these changes
Beautiful stuff!

2024-11-10 14:03 UTC, merged