Fix: Activity Not found exception
ankidroid/Anki-Android pull request #17396
Opened 2024-11-08 19:57 UTC by criticalAY

## Purpose / Description
- https://github.com/ankidroid/Anki-Android/issues/17376

## Fixes
* Fixes #17376

## Approach
Use try-catch and show snackbar to the user

## How Has This Been Tested?
Local build

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-11-08 20:08 UTC, david-allison approved these changes
Feels like a warning. Implementer's choice

2024-11-08 20:08 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +            Timber.d(e, "MultimediaImageFragment:: No app found to select image")
```suggestion
            Timber.w(e, "MultimediaImageFragment:: No app found to select image")
```

2024-11-09 07:10 UTC, lukstbit requested changes

2024-11-09 07:10 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +            pickImageLauncher.launch(intent)
Just to be safe, I think we should also add this try-catch to _cameraLauncher_ .

2024-11-09 07:10 UTC, lukstbit commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
> +    <string name="no_image_app">No app found to select image</string>
We don't need this new string, we can use the general _R.string.activity_start_failed_ string that the activity uses for this situation:

_The system does not have an app installed that can perform this action._

2024-11-09 08:52 UTC, criticalAY commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
> +    <string name="no_image_app">No app found to select image</string>
Wanted to keep the error specific

2024-11-09 13:40 UTC, mikehardy commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
> +    <string name="no_image_app">No app found to select image</string>
I think that string is a great match - it is the string I was looking for in fact. It is specific enough

2024-11-09 14:10 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +            pickImageLauncher.launch(intent)
nice catch - I see this was added to cameraLauncher in latest commit so concern is addressed and that one should be safe as well

2024-11-09 14:11 UTC, mikehardy approved these changes
LGTM - I think lukstbit items are all ticked off as well but re-pinging on that for agreement
Thanks for crushing a crash

2024-11-09 14:12 UTC, lukstbit approved these changes
LGTM, thanks!

2024-11-09 14:26 UTC, merged