fix: invalid file issue on pasting file
ankidroid/Anki-Android pull request #17398
Opened 2024-11-08 21:44 UTC by criticalAY

## Purpose / Description
- https://github.com/ankidroid/Anki-Android/issues/17388
When some invalid or corrupted file is being pasted in the field then it might cause the issue, though I tried to reproduce it with various types of  files such as pdf but can not get it, so putting a try catch and send report to ACRA

## Fixes
* Fixes #17388

## How Has This Been Tested?
Local build, try-catch should do the work

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-11-08 21:57 UTC, mikehardy requested changes

2024-11-08 21:57 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> +                CrashReportService.sendExceptionReport("File is invalid issue:8880", "FieldEditText:: onPaste URI of file:$mediaUri")
after the recent issue with email addresses I'm worried about including user content like the URI here

and similar to the other issue about dispatching touches, I'm just not sure what the action would be here for someone that sees this in acrarium and tries to work on the stack trace as an issue. Is it actionable? I don't think so really - if pasting files isn't working at all, we'll get issue reports and I think that's sufficient vs having exception reports in the crash database

I'd +1 this with a delete of the crash report line

2024-11-08 23:41 UTC, mikehardy requested changes

2024-11-08 23:41 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> +            }
these are functionally identical blocks now aren't they? propose collapse

```suggestion
            } catch (e: Exception) {
                Timber.w(e, "Failed to paste media")
                showSnackbar(context.getString(R.string.multimedia_editor_something_wrong))
                false
            }
```

2024-11-09 00:07 UTC, criticalAY commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
> +            }
Earlier this was sending report to ACRA, my bad will fix it

2024-11-09 14:08 UTC, mikehardy approved these changes
great, thanks for fixing a crash, users will appreciate it

2024-11-09 14:51 UTC, lukstbit approved these changes
Thanks!

2024-11-09 15:06 UTC, merged