Sync from reviewer when we didn't want through the deck picker
ankidroid/Anki-Android pull request #17399
Opened 2024-11-08 23:10 UTC by Arthur-Milchior

Sync enabled in the reviewer when the deck picker was not used

Widgets and shortcuts allows to directly review a deck.
This means that automated sync, or even manual sync, is never
available. Except if the user close the reviewer and then manually
open ankidroid. This create a lot of friction on a very important
feature.

This commit enable the sync feature in the reviewer, but hides it
unless the intent actually requested it.

In my opinion, it should be always available. It's available in anki
upstream from the reviewer, and anki allows automated save every 10
minutes. Which means even if your device suddenly dies during a
streak, you only lose up to 10 minutes of review.

Still, this feature at least improve the case that was the most
dangerous for users (and frustrating for me)

I don't know the code of Reviewer2/ReviewerFragment. So this is only
enabled in the legacy reviewer. I hope the code is simple enough for
the feature to be easily ported to the other reviewers now that the
entire sync part of the code was decoupled from the DeckPicker.

Manually tested with:
* signin in (when no account present)
* full sync (requested locally and requested by ankiweb)
* normal sync
* changing the selected deck on the other device

To test it you should use a widget or a shortcut.

One point amy need to be changed. The little icon that state that
there is a not-uploaded change. While it's okay in the deckpicker, it
may not be ideal to have it as soon as we have the first review done.

2024-11-10 23:02 UTC, david-allison requested changes
> I don't know the code of Reviewer2/ReviewerFragment. So this is only
enabled in the legacy reviewer. I hope the code is simple enough for
the feature to be easily ported to the other reviewers now that the
entire sync part of the code was decoupled from the DeckPicker.

From an architecture perspective, supporting the new reviewer is the most important thing to get right. We want to move to the new reviewer (which affects everyone; this change only affects a subset of users), and if this PR doesn't support the new reviewer, then we're adding more friction to switching to the reviewer

----

I've reviewed the first two commits and they both look great. I'd strongly support a new PR to split them out if the rework of this PR will take some time.

2024-11-11 01:28 UTC, Arthur-Milchior commented
Done in #17417

I admit I don't know the new reviewer at all. I didn't even know a new reviewer was considered. I'll take a look

2024-11-11 01:34 UTC, david-allison commented
> Done in #17417
> 
> I admit I don't know the new reviewer at all. I didn't even know a new reviewer was considered. I'll take a look

It's in the developer options, it looks great and I feel we all strongly want to make it the default

2024-11-11 08:49 UTC, Arthur-Milchior commented
so I tried.
And the issue is that the widget and the shortcut are hardcoded for the first reviewer,even when the settings state to open the second one.
So in order to test the feature, I should first update the widget and shortcut

2024-11-11 18:19 UTC, Arthur-Milchior commented
Rebased on top of #17422 so that the deck picker widget can use the new reviewer.

2024-11-11 18:20 UTC, Arthur-Milchior commented
Feature is now ported to the new reviewer.
I don't know how currently this reviewer decide what is displayed or not. I decide to let it displayed if the deck picker was skipped

2024-11-11 21:25 UTC, david-allison commented
Conflicts

2024-12-04 03:30 UTC, Arthur-Milchior commented
Conflict resolved

2024-12-07 03:10 UTC, Arthur-Milchior commented
I split it some of its commits in #17570 and #17569 so that they can be reviewed faster and hopefully don't get too much merge conflict.
This will ensure this PR only contains:
* the code move from DeckPicker to Sync
* the use of Sync from the reviewer

2024-12-07 18:12 UTC, mikehardy commented
```

> Task :AnkiDroid:ktlintMainSourceSetCheck FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt:25:1 Unused import
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt:283:1 Unexpected indentation (16) (should be 12)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt:648:5 Declarations and declarations with comments should have an empty space between.
```

minor lint issue

2024-12-07 18:15 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
> +class SyncHandler(
`Sync.kt` is already pretty big isn't it? Could this reasonably go in its own file?

2024-12-07 20:00 UTC, Arthur-Milchior commented
I tried `./gradlew lint` and got 

> milchior@Liamwayl:~/ankidroid$ ./gradlew  lint 
> Starting a Gradle Daemon (subsequent builds will be faster)
> 
> BUILD SUCCESSFUL in 1m 18s
> 153 actionable tasks: 25 executed, 5 from cache, 123 up-to-date

would you have any idea why it success locally and not on github?

2024-12-07 20:41 UTC, mikehardy commented
> would you have any idea why it success locally and not on github?

no idea but looks like it resolved :-)

2024-12-12 00:13 UTC, david-allison requested changes
Fundamentally: I don't feel we should have a UI to sync from the reviewer.

I wouldn't mind it via the JS API, or being performed automatically on open/close, but not as a UI option. It turns the Reviewer into a "do everything" screen

2024-12-12 00:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/SyncHandler.kt
> +package com.ichi2.anki
can we move this into a subpackage?

2024-12-12 00:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/SyncHandler.kt
> +class SyncHandler(
This is far too coupled to implementation details for it to be worthwhile. the UI code shouldn't be here

2024-12-12 00:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
> +        if (intent.extras?.getBoolean(ENABLE_SYNC) == true) {
Should this be handled by the reviewer at all if there's no UI updates? Can we do it when we receive an intent instead?

2024-12-12 00:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +    var activityPaused = false
This should be using [lifecycle aware components](https://developer.android.com/topic/libraries/architecture/lifecycle), or querying the lifecycle manually

2024-12-12 00:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +            R.id.action_sync -> {
I don't think this belongs here. If a user wants to sync from a widget, they can turn on auto-sync and have it handled by the code you're adding

2025-01-03 12:47 UTC, closed without merging