Filter/block reports sent to ACRA
ankidroid/Anki-Android pull request #17402
Opened 2024-11-09 11:01 UTC by voczi

See title. Related:
https://github.com/ankidroid/Anki-Android/issues/17392
https://github.com/ankidroid/Anki-Android-Backend/pull/439
https://github.com/ankitects/anki/commit/ba1f5f4

Preemptive "may lord have mercy".

2024-11-09 12:50 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +    ): Boolean {
this PR seems to contain lots of non-functional change mixed in with functional change

There's the switch from `{ }` to `: Boolean =` above, there is this spacing change, I don't know what's going on. Why are functional and non-functional changes mixed in the same commit? Unnecessarily difficult to review like this

2024-11-09 12:51 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +
strongly discourage formatting changes in same commit as functional change they just make the diff harder to read

2024-11-09 12:57 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +        return newE
Looks like this started with Exception but is all Throwable now so should be altered (plus callers) to reflect
Also the comment strongly binds the implementation with the idea of the rules so this comment will need an update as rules change, or (better) comment should be more generic

```suggestion
    // Strip PII from Throwable.message or return null if we should discard completely
    @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
    fun processThrowable(t: Throwable): Throwable? {
        var newT: Throwable? = t

        for (rule in throwableRules) {
            newT = rule.invoke(newT!!)

            if (newT == null) {
                return null
            }
        }

        return newT
```

2024-11-09 13:01 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +    ): Boolean {
Reviewing PRs can become as difficult as you choose to make it.

2024-11-09 13:12 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +        return newE
No clue what this patch is supposed to reflect, except "use the term Throwable more than Exception". I can do that.

2024-11-09 13:38 UTC, dyzur commented
i like it. picasso

2024-11-09 13:45 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +    ): Boolean {
The size of the diff is correlated with the difficulty of review. A goal of any PR submitter should be to minimize diff in general and specifically to minimize diff per commit to aid review. The philosophical idea underpinning is that in many open source projects - this one included - review bandwidth is the limiter, not PR creation. So care should be taken to optimize for review

2024-11-09 13:57 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +        return newE
The patch was intended to reflect what I stated:

> Looks like this started with Exception but is all Throwable now so should be altered (plus callers) to reflect
Also the comment strongly binds the implementation with the idea of the rules so this comment will need an update as rules change, or (better) comment should be more generic

That is:
- the comment of this function shouldn't be bound to the implementation of another function
- it's all about Throwable in implementation but uses "Exception" in words

I believe those important but also think they're close to bikeshedding and when I bikeshed something I try to post a concrete suggestion that can just be adopted since (in my world at least) if you're going to bikeshed the onus is on you (that is: me in this context) to reduce back-and-forth and PR submitter effort trying to satisfy some bikeshed. So I made a whole suggestion.

Appears the comment part was ignored and a lot of the 'e's are still in there when it's really a 't', so that's a missed opportunity as the suggestion just did it all in one swell foop

2024-11-09 13:59 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +    // decided to block this based on some arbitrary rule(s) enforced on the throwable' contents.
```suggestion
    // Either alters Throwable.message via rules so it is safe for ACRA or returns null if
    // the Throwable cannot be made safe for ACRA and should just be discarded
```

2024-11-09 17:41 UTC, david-allison requested changes
Architecture:

* This doesn't process logcat
* This changes the type of the exception to `Throwable`

2024-11-09 17:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +                Patterns.EMAIL_ADDRESS.toRegex().replace(e.message.orEmpty(), "-EMAIL-")
Performance: extract `Patterns.EMAIL_ADDRESS.toRegex()` to a constant

2024-11-09 17:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +    var mPreferences: SharedPreferences? = null
Don't use Hungarian Notation

2024-11-09 17:41 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/CrashReportServiceTest.kt
> +        CrashReportService.mPreferences = preferences
This line shouldn't be necessary:

Using a live `SharedPreferences` is fine, otherwise use a mock

2024-11-09 17:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +    }
Optional 

```suggestion
    fun processThrowable(e: Throwable): Throwable? =
        throwableRules.fold(e) { nextThrowable, rule -> rule.invoke(nextThrowable) ?: return null }
```

2024-11-09 17:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +    fun processThrowable(e: Throwable): Throwable? {
**Method naming**
`process` isn't descriptive enough

`Throwable.removePersonallyIdentifiableInformation()` is probably too descriptive, but there's a happy medium

2024-11-09 17:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +            if (e.cause is BackendSyncServerMessageException) null else e
Bug: This doesn't handle if the exception is a `BackendSyncServerMessageException`
Bug: This doesn't handle if `e.cause.cause` is a `BackendSyncServerMessageException`

2024-11-09 17:41 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/CrashReportServiceTest.kt
> +        val e = Throwable(message, mock(BackendDeckIsFilteredException::class.java))
I don't see why you're creating a Throwable in these tests, an `Exception` is an instance of `Throwable`

2024-11-09 17:41 UTC, david-allison commented on gradle/libs.versions.toml
> +ankiBackend = '0.1.47-anki24.11rc1'
Can we split this into a separate PR so we can ensure that it's not squashed

2024-11-09 17:41 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/CrashReportServiceTest.kt
> +        assertNotNull(processed, "Returned exception should not be null")
Optional

```suggestion
        val processed = assertNotNull(processThrowable(e), "Returned exception should not be null")
```

2024-11-09 17:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +    fun processThrowable(e: Throwable): Throwable? {
Annotate this to ensure the return value is used

2024-11-09 17:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +            if (processThrowable(e) == null) {
🪲

`processThrowable` does not mutate the message, and we don't send the new instance of the Throwable to the `errorReporter`

This would read better as:

```kotlin
val safeException = removePersonallyIdentifiableInformation(e) ?? return
```

2024-11-09 17:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +    fun initialize(application: Application, preferences: SharedPreferences) {
I wouldn't bother with a new parameter, we already use `mApplication.sharedPrefs()`

2024-11-09 17:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +    fun Throwable.replaceMessage(newMessage: String?): Throwable =
This obscures the actual type of exception in logcat as it's converted to a Throwable. I believe this also loses the original stack trace, but I haven't confirmed.


```suggestion
    private fun Throwable.replaceMessage(newMessage: String?): Throwable =
```

2024-11-09 17:45 UTC, mikehardy commented
with regard to "This doesn't process logcat" from David -> I noticed while verifying my acrarium purge that there were some instances where the stack prompting a current error did not contain an email but the included logcat did. So it is a valid concern. I altered my purge matcher to also match emails deeper into the report (logcat also, not just original stack) so I'm cleaning them now, but better if they never hit logcat. Whole thing is messy, for sure

2024-11-09 18:58 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +    var mPreferences: SharedPreferences? = null
Yep, was my original approach. I'll do so.

2024-11-09 19:23 UTC, voczi commented on AnkiDroid/src/test/java/com/ichi2/anki/CrashReportServiceTest.kt
> +        CrashReportService.mPreferences = preferences
Do you mean to just remove L61?

2024-11-09 19:24 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +    }
Good simplification.

2024-11-09 19:29 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +    fun processThrowable(e: Throwable): Throwable? {
`Throwable.removePII` sounds good (with a PII defined in the function comment).

2024-11-09 19:33 UTC, voczi commented on AnkiDroid/src/test/java/com/ichi2/anki/CrashReportServiceTest.kt
> +        val e = Throwable(message, mock(BackendDeckIsFilteredException::class.java))
Thinking of something like this instead:
```kotlin
val message = "This is a test message which should not be filtered nor blocked"
val processed = BackendDeckIsFilteredException(BackendError.newBuilder().setMessage(message).build()).removePII()```

2024-11-09 19:38 UTC, voczi commented on gradle/libs.versions.toml
> +ankiBackend = '0.1.47-anki24.11rc1'
Rebased ontop of main (with that commit already merged by you before), should be gone from this PR now.

2024-11-09 19:41 UTC, voczi commented on AnkiDroid/src/test/java/com/ichi2/anki/CrashReportServiceTest.kt
> +        assertNotNull(processed, "Returned exception should not be null")
Yeah maybe a bit too long of a line now with my line above.

2024-11-09 19:46 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +            if (e.cause is BackendSyncServerMessageException) null else e
Could set up something recursive for this.

2024-11-09 19:54 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +            if (processThrowable(e) == null) {
> processThrowable does not mutate the message, and we don't send the new instance of the Throwable to the errorReporter

Does it not? I can't see why it wouldn't. You get the instance back if it's not blocked and nothing changes if it's not filtered (well, not really, as you mentioned below).

2024-11-09 20:47 UTC, voczi commented
Work's left to be done. Still unsure about certain things.

2024-11-09 20:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +            if (processThrowable(e) == null) {
The below test fails. `progressThrowable` produced a new `Throwable` with a mutated message.

```kotlin
    @Test
    fun `Input is not mutated`() {
        val input = Throwable("Lorem ipsum 123 email@domain.tld Lorem ipsum.")
        val output = processThrowable(Throwable("Lorem ipsum 123 email@domain.tld Lorem ipsum."))!!

        assertThat("Exception message does not contain the email", input.message, equalTo(output.message))
    }
```

If your code is not using the output from `processThrowable`, then you're only handling the case where `null` is returned

2024-11-10 12:41 UTC, voczi commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +            if (e.cause is BackendSyncServerMessageException) null else e
Should be good now.

2024-11-10 13:43 UTC, david-allison approved these changes
Looks SO much better, thanks so much!!!

One suggestion, take it or leave it

2024-11-10 13:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
> +    }
Optional: the `list` didn't seem to be adding much value with one entry.

This also adds javadocs, which render in the IDE

```suggestion
    /**
     * Checks if the [Throwable] is safe from Personally Identifiable Information (PII)
     * @return `false` if the [Throwable] contains PII, otherwise `true`
     */
    fun Throwable.safeFromPII(): Boolean {
        if (this.containsPIINonRecursive()) return false
        return this.cause?.safeFromPII() != false
    }

    private fun Throwable.containsPIINonRecursive(): Boolean {
        // BackendSyncServerMessage may contain PII and we do not want this leaked to ACRA.
        // Related: https://github.com/ankidroid/Anki-Android/issues/17392
        // and also https://github.com/ankitects/anki/commit/ba1f5f4
        return this is BackendSyncServerMessageException
    }
```

2024-11-10 13:52 UTC, david-allison approved these changes
Approval still stands

2024-11-11 22:56 UTC, mikehardy commented
To be concrete about the idea of installing the filter as an uncaught exception handler also, here is exactly how to do it

https://github.com/ankidroid/Anki-Android/blob/15b748a60a59748b1b572ba4b209128991446e9d/AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt#L117-L131

As long as we already have the filter logic, it's just "store ref to original handler, install ourselves as handler, and after we handle an uncaught exception pass it on to the original handler" - idea being that this is yet another ask on the PR but this one is hopefully satisfyingly easy and then covers the last place these could slip through

2024-11-26 23:26 UTC, mikehardy commented
No idea what's taking so long, but anyway 24.11rc2 just released and I'm going to publish it soon on backend
I think the last thing to do here is to hook into the exception handling chain to swallow unhandled ones, an important-but-hard addition

2024-11-30 20:28 UTC, mikehardy approved these changes
I implemented the handling of uncaught exceptions as well, what do you guys think?
I thought the isPII filter and initial test were great, so I'm approving those
Happy to bend the last commit around to whatever seems best to get it in

2024-12-01 02:00 UTC, david-allison reviewed
Looks good! Two questions

I had a play with Default interface implementations. I didn't like this and **wouldn't recommend it**, but it is less code

<details>

<summary>Patch</summary>

```patch
Subject: [PATCH] refactor: extract dialog fragments from Anki[Activity/Fragment]

* dismissAllDialogFragments
* showDialogFragment

**AnkiFragment**
* showDialogFragment

This affects all callers, as we now use extension methods
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ThrowableFilterService.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ThrowableFilterService.kt b/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ThrowableFilterService.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ThrowableFilterService.kt	(revision e68c8fc839fbc5a07dbce6343bc982094a928d15)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ThrowableFilterService.kt	(date 1733018370799)
@@ -16,71 +16,38 @@
  ****************************************************************************************/
 package com.ichi2.anki.servicelayer
 
-import androidx.annotation.VisibleForTesting
+import com.ichi2.anki.exception.ChainedUncaughtExceptionHandler
+import com.ichi2.anki.exception.Handled
 import net.ankiweb.rsdroid.exceptions.BackendSyncException.BackendSyncServerMessageException
 import timber.log.Timber
 
-object ThrowableFilterService {
-
-    @FunctionalInterface
-    fun interface FilteringExceptionHandler : Thread.UncaughtExceptionHandler
+object ThrowableFilterService : ChainedUncaughtExceptionHandler {
+    override var originalUncaughtExceptionHandler: Thread.UncaughtExceptionHandler? = null
 
-    @VisibleForTesting
-    var originalUncaughtExceptionHandler: Thread.UncaughtExceptionHandler? = null
-
-    var uncaughtExceptionHandler = FilteringExceptionHandler {
-            thread: Thread?, throwable: Throwable ->
+    override fun handleUncaughtException(thread: Thread?, throwable: Throwable): Handled {
         if (thread == null) {
             Timber.w("unexpected: thread was null")
-            return@FilteringExceptionHandler
+            return Handled.NO_CHAIN
         }
         if (shouldDiscardThrowable(throwable)) {
             Timber.i("discarding throwable")
-            return@FilteringExceptionHandler
+            Handled.NO_CHAIN
         }
-        originalUncaughtExceptionHandler?.uncaughtException(thread, throwable)
+        return Handled.CHAIN
     }
 
     fun initialize() {
-        Timber.i("initialize()")
         installDefaultExceptionHandler()
     }
 
-    /**
-     * We want to filter any exceptions with PII, then chain to other handlers
-     */
-    @Synchronized
-    @VisibleForTesting
-    fun installDefaultExceptionHandler() {
-        originalUncaughtExceptionHandler = Thread.getDefaultUncaughtExceptionHandler()
-        Timber.d("Chaining to uncaughtExceptionHandler (%s)", originalUncaughtExceptionHandler)
-        Thread.setDefaultUncaughtExceptionHandler(uncaughtExceptionHandler)
-    }
-
-    /**
-     * Reset the default exception handler
-     */
-    @Synchronized
-    @VisibleForTesting
-    fun unInstallDefaultExceptionHandler() {
-        Thread.setDefaultUncaughtExceptionHandler(originalUncaughtExceptionHandler)
-        originalUncaughtExceptionHandler = null
-    }
-
     /**
      * Re-Initialize the throwable filter
      */
-    @Synchronized
     fun reInitialize() {
-        // send any pending async hits, re-chain default exception handlers and re-init
-        Timber.i("reInitialize()")
-        unInstallDefaultExceptionHandler()
-        initialize()
+        reInitializeDefaultExceptionHandler()
     }
 
-    fun shouldDiscardThrowable(t: Throwable): Boolean {
-        return !t.safeFromPII()
-    }
+    fun shouldDiscardThrowable(t: Throwable) = !t.safeFromPII()
 
     /**
      * Checks if the [Throwable] is safe from Personally Identifiable Information (PII)
Index: AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt b/AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt	(revision e68c8fc839fbc5a07dbce6343bc982094a928d15)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt	(date 1733018083962)
@@ -29,6 +29,8 @@
 import com.ichi2.anki.AnkiDroidApp
 import com.ichi2.anki.BuildConfig
 import com.ichi2.anki.R
+import com.ichi2.anki.exception.ChainedUncaughtExceptionHandler
+import com.ichi2.anki.exception.Handled
 import com.ichi2.anki.preferences.sharedPrefs
 import com.ichi2.utils.DisplayUtils
 import com.ichi2.utils.KotlinCleanup
@@ -38,12 +40,12 @@
 import timber.log.Timber
 
 @KotlinCleanup("see if we can make variables lazy, or properties without the `s` prefix")
-object UsageAnalytics {
+object UsageAnalytics : ChainedUncaughtExceptionHandler {
     const val ANALYTICS_OPTIN_KEY = "analytics_opt_in"
 
     @KotlinCleanup("lateinit")
     private var sAnalytics: GoogleAnalytics? = null
-    private var sOriginalUncaughtExceptionHandler: Thread.UncaughtExceptionHandler? = null
+    override var originalUncaughtExceptionHandler: Thread.UncaughtExceptionHandler? = null
     private var sOptIn = false
     private var sAnalyticsTrackingId: String? = null
     private var sAnalyticsSamplePercentage = -1
@@ -51,14 +53,13 @@
     @FunctionalInterface
     fun interface AnalyticsLoggingExceptionHandler : Thread.UncaughtExceptionHandler
 
-    var uncaughtExceptionHandler = AnalyticsLoggingExceptionHandler {
-            thread: Thread?, throwable: Throwable ->
+    override fun handleUncaughtException(thread: Thread?, throwable: Throwable): Handled {
         sendAnalyticsException(throwable, true)
         if (thread == null) {
             Timber.w("unexpected: thread was null")
-            return@AnalyticsLoggingExceptionHandler
+            return Handled.NO_CHAIN
         }
-        sOriginalUncaughtExceptionHandler!!.uncaughtException(thread, throwable)
+        return Handled.CHAIN
     }
 
     /**
@@ -127,27 +128,6 @@
         reInitialize()
     }
 
-    /**
-     * We want to send an analytics hit on any exception, then chain to other handlers (e.g., ACRA)
-     */
-    @Synchronized
-    @VisibleForTesting
-    fun installDefaultExceptionHandler() {
-        sOriginalUncaughtExceptionHandler = Thread.getDefaultUncaughtExceptionHandler()
-        Timber.d("Chaining to uncaughtExceptionHandler (%s)", sOriginalUncaughtExceptionHandler)
-        Thread.setDefaultUncaughtExceptionHandler(uncaughtExceptionHandler)
-    }
-
-    /**
-     * Reset the default exception handler
-     */
-    @Synchronized
-    @VisibleForTesting
-    fun unInstallDefaultExceptionHandler() {
-        Thread.setDefaultUncaughtExceptionHandler(sOriginalUncaughtExceptionHandler)
-        sOriginalUncaughtExceptionHandler = null
-    }
-
     /**
      * Allow users to enable or disable analytics
      */
Index: AnkiDroid/src/main/java/com/ichi2/anki/exception/ChainedUncaughtExceptionHandler.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/exception/ChainedUncaughtExceptionHandler.kt b/AnkiDroid/src/main/java/com/ichi2/anki/exception/ChainedUncaughtExceptionHandler.kt
new file mode 100644
--- /dev/null	(date 1733018290159)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/exception/ChainedUncaughtExceptionHandler.kt	(date 1733018290159)
@@ -0,0 +1,80 @@
+/*
+ *  Copyright (c) 2024 David Allison <davidallisongithub@g [...]

2024-12-01 14:39 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ThrowableFilterService.kt
> +    }
Sure, let me check them out.
I was deliberately trying to be a bit more generic with the idea of Filter / discard vs purely PII (despite PII being our motivator!) because I thought there might be others to filter

2024-12-01 21:52 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ThrowableFilterService.kt
> +    }
last commit does it, and boy if the unit test I TDD-built it with didn't save me from a stupid error as well.
Seems to work well as pushed

2024-12-01 22:16 UTC, mikehardy commented
If macOS unit test fails, and it seems like it might with a current unrelated heapspace problem, contemplating testing one of these things - 

1- changing these params on test forking behavior:

https://github.com/ankidroid/Anki-Android/blob/0c5ea9d25ab1ac8fc0d18319578c87a7423c72af/build.gradle.kts#L51-L54

2- bumping up heapspace 🤷

2024-12-01 22:19 UTC, david-allison approved these changes

2024-12-02 01:49 UTC, merged

2024-12-02 01:50 UTC, mikehardy commented
Fixed the macOS runner issue as well (test executors needed more heap)
And this has been reviewed to death, reanimated, then reviewed to death again 😆  merged