fix: unable to crop shared images
ankidroid/Anki-Android pull request #17406
Opened 2024-11-10 05:24 UTC by criticalAY

## Purpose / Description
- https://github.com/ankidroid/Anki-Android/issues/17361

## Fixes
* Fixes #17361

## How Has This Been Tested?
Tested on Google Emulator API 35

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-11-10 13:20 UTC, mikehardy requested changes
I strongly suspect the file internalization logic exists somewhere already and some effort was expended on de-duplicating it once or a few times already

2024-11-10 13:20 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaUtils.kt
> +    fun getLocalUriFromExternalUri(context: Context, externalUri: Uri): Uri? {
I feel like I've written this function before - doesn't this exist already? Both in image handling in general and re-used for deck/collection import ?

Also, you made a PR but did not include in the PR description any information about how you reproduced, what the root cause of the issue is, the approach etc - so as a reviewer I am left to reconstruct all that in my mind just via presentation of code vs knowing the context you have already had to work through

2024-11-10 20:02 UTC, mikehardy approved these changes
will assume the log level alteration is easy and completed

2024-11-10 20:02 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +            Timber.e("Failed to internalize URI: $uri")
nit: e to me is "catastrophic", like the app needs to restart
w is "this would have been an error but we handled it and current task may be broken but we're moving on

I think this is a w

These are documented by the way, so you can choose appropriately: https://github.com/ankidroid/Anki-Android/wiki/Code-style#log-levels

Provisional approve assuming you'll get that, so if next person is +1, that's good for me!

Thanks

2024-11-10 21:53 UTC, david-allison submitted a review, later dismissed
* use `?.let { } so a nullable parameter isn't required
* `internalizeUrl` already logs when returning `null`, so the additional log isn't required

I think the following patch goes 'too far' in conciseness, but food for thought

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt	(revision 2e692c794b5048c098884b1760be7e1ccb576aaa)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt	(date 1731275398964)
@@ -274,26 +274,18 @@
     }
 
     private fun handleImageUri() {
+        fun processExternalImage(uri: Uri): Uri? = internalizeUri(uri)?.let { Uri.fromFile(it) }
+        
         if (imageUri != null) {
             view?.findViewById<TextView>(R.id.no_image_textview)?.visibility = View.GONE
 
-            val internalUri = processExternalImage(imageUri)
+            val internalUri = imageUri?.let { processExternalImage(it) }
             handleSelectImageIntent(internalUri)
         } else {
             handleSelectedImageOptions()
         }
     }
 
-    private fun processExternalImage(uri: Uri?): Uri? {
-        val localFile = uri?.let { internalizeUri(it) }
-        if (localFile != null) {
-            return Uri.fromFile(localFile)
-        } else {
-            Timber.e("Failed to internalize URI: $uri")
-            return null
-        }
-    }
-
     private fun handleSelectedImageOptions() {
         when (selectedImageOptions) {
             ImageOptions.GALLERY -> {
```

2024-11-16 15:36 UTC, criticalAY commented
@david-allison Applied the changes, now good to go

2024-11-18 14:45 UTC, mikehardy approved these changes
applies suggested change from David completely

2024-11-18 14:58 UTC, merged