My feature branch
ankidroid/Anki-Android pull request #17405
Opened 2024-11-10 04:48 UTC by MritunjayTiwari14

## Purpose / Description
To Fix Android Studio Warnings and make the experience smoother and bug free.

## Fixes
* Fixes #13282

## Approach
Looking for the Warning each one by one and solving them

## How Has This Been Tested?
All the Warning were removed

## Learning (optional, can help others)

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [YES ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ NO, Because All the Coding is about Cleanup] You have commented your code, particularly in hard-to-understand areas
- [Yes] You have performed a self-review of your own code
- [NO UI Changes] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [NO UI Changes] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-11-10 09:21 UTC, lukstbit requested changes
Thank you for contributing, I've left some issues below to fix.

Also you may want to read our [git related wiki](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#git-workflow) on how to contribute.

2024-11-10 09:21 UTC, lukstbit commented on .codecov.yml
> +        threshold: "0.15"
This is a not an issue and should be reverted.

2024-11-10 09:21 UTC, lukstbit commented on README.md
> +    <img alt="Get it on Google Play" height="250"
Although the 80 value raises an issue, using other values makes those images too big. Instead of changing the value these issues should be suppressed: right click -> Show context actions -> Click the three dots beside "Set height value to 250" -> Suppress for tag

2024-11-10 09:21 UTC, lukstbit commented on README.md
> +<p style="text-align: center;">
Remove the obsolete _align_ attribute. Also revert the spacing change on the inner img tag.

2024-11-10 09:21 UTC, lukstbit commented on build.gradle.kts
> +// allows for -Dare-dex=false to be set
Revert this, it changes the meaning of the comment.

2024-11-10 14:03 UTC, MritunjayTiwari14 commented on build.gradle.kts
> +// allows for -Dare-dex=false to be set
Okay Sir

2024-11-10 14:08 UTC, MritunjayTiwari14 commented on .codecov.yml
> +        threshold: "0.15"
Okay Sir

2024-11-20 18:27 UTC, lukstbit requested changes

2024-11-20 18:27 UTC, lukstbit commented on .codecov.yml
> +        threshold: "0.15"
Please don't mark review requests as resolved if you didn't resolved them. So again, please revert this change.

2024-11-20 18:27 UTC, lukstbit commented on README.md
> +<p style="text-align: center;">
Request above still active.

2024-11-20 18:27 UTC, lukstbit commented on README.md
> +    <img alt="Get it on Google Play" height="250"
Still active, this also needs to be done for the other two values in this file.

2024-11-20 18:27 UTC, lukstbit commented on build.gradle.kts
> +// Top-level Build file where you can add configuration options common to all sub-projects/modules.
This change is not needed.

2024-11-26 16:23 UTC, lukstbit requested changes
There are still change requests active. Don't add changes that are not needed.

2024-11-26 16:23 UTC, lukstbit commented on README.md
> +<img alt="Get it on Google Play" height="80"
There's no reason to change code indentation. Here and the other three img tags below.

2024-11-27 13:02 UTC, MritunjayTiwari14 commented on README.md
> +<img alt="Get it on Google Play" height="80"
Okay Sir.

2024-11-30 03:29 UTC, david-allison requested changes

2024-11-30 03:29 UTC, david-allison commented on README.md
> +    <img src="docs/graphics/logos/banner_readme.png" alt="">
revert

2024-11-30 03:29 UTC, david-allison commented on README.md
> +    <img alt="Get it on F-Droid" height=80
Why the change?

2024-11-30 03:29 UTC, david-allison commented on build.gradle.kts
>      println("\n\n\n")
This would be better to change to a single `println`

2024-11-30 03:29 UTC, david-allison commented on build.gradle.kts
> +// allows for -Dare-dex=false to be set
This wasn't reverted

2024-12-03 09:27 UTC, MritunjayTiwari14 commented on README.md
> +    <img alt="Get it on F-Droid" height=80
To suppress the warning, because it was given to do so in the list

2024-12-03 10:04 UTC, lukstbit requested changes
This is not ready to be reviewed as there are still pending requests.

Please take a step back and read carefully the review requests, implement them and don't introduce other unrelated changes.

2024-12-04 05:09 UTC, MritunjayTiwari14 commented on README.md
> +    <img alt="Get it on F-Droid" height=80
Okay

2024-12-04 06:25 UTC, MritunjayTiwari14 commented
https://github.com/ankidroid/Anki-Android/pull/17405#discussion_r1864064643

The comment has been already reverted. Please Check it once again.

2024-12-04 06:37 UTC, david-allison requested changes
Double tap shift and 'apply patch from clipboard' in Android Studio

Still one missed issue. Please ensure **all** comments are handled

```patch
Index: build.gradle.kts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/build.gradle.kts b/build.gradle.kts
--- a/build.gradle.kts	(revision f62239aea01431ac12c7aadcd61146749cb2529f)
+++ b/build.gradle.kts	(date 1733294177109)
@@ -98,13 +98,27 @@
 val jvmVersion = Jvm.current().javaVersion?.majorVersion
 if (jvmVersion != "17" && jvmVersion != "21") {
     println(
-        "\n\n\n*****************************************************\n\n\n" +
-        "ERROR: AnkiDroid builds with JVM version 17 or 21.\n" +
-        "Incompatible major version detected: '$jvmVersion'\n\n\n" +
-        "If you receive this error because you want to use a newer JDK, we may accept PRs to support it.\n" +
-        "Edit the main build.gradle file, find this message in the file, and add support for the newer version.\n" +
-        "Please make sure the `jacocoTestReport` target works on an emulator with our minSdkVersion.\n\n\n" +
-        "*****************************************************\n\n\n"
+        """
+            
+            
+            
+            *****************************************************
+            
+            
+            ERROR: AnkiDroid builds with JVM version 17 or 21.
+            Incompatible major version detected: '$jvmVersion'
+            
+            
+            If you receive this error because you want to use a newer JDK, we may accept PRs to support it.
+            Edit the main build.gradle file, find this message in the file, and add support for the newer version.
+            Please make sure the `jacocoTestReport` target works on an emulator with our minSdkVersion.
+            
+            
+            *****************************************************
+            
+            
+            
+            """.trimIndent()
     )
     exitProcess(1)
 }
```

2024-12-04 06:37 UTC, david-allison commented on gradle/libs.versions.toml
> +androidGradlePlugin = "8.7.3"
Don't bump dependencies in unrelated changes

2024-12-04 06:37 UTC, david-allison commented on build.gradle.kts
> +// allows for -Dare-dex=false to be set
This wasn't reverted

2024-12-04 07:08 UTC, david-allison commented on README.md
> -</p>
What's the rationale here?

2024-12-04 10:20 UTC, david-allison commented on README.md
> +<img src="docs/graphics/logos/banner_readme.png" alt = "">
That's a really unusual alt tag. Did you check the diff before requesting a review?

2024-12-05 06:16 UTC, david-allison commented on README.md
> -</p>
... it was a question. The fix is also wrong

This is a decorative image, and does not need to be announced to screen readers.

Please revert

2024-12-05 11:35 UTC, mikehardy commented
With apologies, I'm not sure this is worth the effort required from the reviewers here to work through some lint
These are not issues that should require a lot of back and forth and some of the proposed changes should not have been proposed to start

2024-12-05 11:35 UTC, closed without merging

2024-12-08 11:47 UTC, MritunjayTiwari14 commented
Okay Sir, no worries.