fix:IndexOutOfBoundsException in NoteEditor.kt(addMediaFileToField)
ankidroid/Anki-Android pull request #17408
Opened 2024-11-10 11:53 UTC by Prince-kushwaha

## Purpose / Description
IndexOutOfBoundsException in addMediaFileToField(NoteEditor.kt)

## Fixes
* Fixes #17383 

## How Has This Been Tested?
tested  note editor on physical device
## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-11-10 13:16 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +            if (index >= 0 && index < editFields!!.size) {
So this now determines we have a problem, and avoids the problem, which does stop the crash

... but it doesn't seem to fix the problem

Were you able to reproduce this error? What is the *actual* problem leading us to have the incorrect index / field mapping here? 

Because if we go out of bounds we crash but what if we are frequently incorrect in the index/field mappings and we are frequently not going out of bounds but we are scribbling into the wrong field via incorrect mappings that are still in bounds?

2024-11-10 19:54 UTC, mikehardy requested changes
does not seem to address root cause

2024-11-14 11:09 UTC, Prince-kushwaha commented
Hi @mikehardy, i  tried  different way to reproduce this issue. But not able to reproduce the issue .

2024-11-14 11:10 UTC, Prince-kushwaha commented
it could be due to some underlying race condition

2024-11-14 16:54 UTC, mikehardy commented
Without a reproduction and a fix of the root cause this PR cannot be merged. Better to crash then continue silently corrupting data with mismatched field indices

2024-12-05 17:38 UTC, closed without merging