Fix: DeckPicker-NullPointerException in onQueryTextChange
ankidroid/Anki-Android pull request #17403
Opened 2024-11-09 17:22 UTC by Giyutomioka-SS

## Purpose / Description
Fixes NullPointerException in onQueryTextChange by safely casting the adapter to Filterable before calling the filter method, preventing crashes when the adapter is null or not of the correct type.

## Fixes
* Fixes #17391 

## How Has This Been Tested?
Realme 6 and Emulator

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-11-09 17:44 UTC, david-allison commented
Did you manage to reproduce the error?

This seems to convert the crash into a bug

2024-11-09 19:51 UTC, Giyutomioka-SS commented
I couldn’t reproduce the crash. Should I add a null check and logging to catch cases where the adapter or filter is unexpectedly null?

2024-11-10 01:32 UTC, david-allison commented
We shouldn't rush to a solution

The first step is to understand how the crash occurred, and ideally being able to reproduce it. Once we know this, we'll ideally be able to fix the cause rather than ignore user input

Did you check ACRA for a logcat?

2024-11-27 16:43 UTC, mikehardy requested changes

2024-11-27 16:43 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                    adapter?.filter?.filter(newText)
I think we should add something like `if (adapter == null || adapter.filter == null) { /* some logging */ }`

and some logging should be:
Timber.w of the adapter and adapter.filter null status and type if possible
then a sendExceptionReport saying something like "DeckPicker.onQueryTextChanged with unexpected null adapter. Carefully examine logcat"

I think that's the best we can do at the moment - I can't see how this would ever be null and I was able to exercise the logic myself just not trigger the crash

2024-11-27 19:27 UTC, mikehardy requested changes
getting closer to something that might move this one forward, but needs to go to our ACRA server for it to be seen

2024-11-27 19:27 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                        Timber.e(Exception("DeckPicker.onQueryTextChanged with unexpected null adapter or filter. Carefully examine logcat"))
not a Timber.e a sendExceptionReport, so we can see these in ACRA reports and hopefully learn something about them for a real fix

2024-11-27 21:21 UTC, mikehardy approved these changes
That's what I had in mind - doesn't fix the underlying issue but will hopefully get us closer. Thank you

2024-11-29 16:37 UTC, mikehardy commented
Going to put this one in as well for 2.19.3, it stops the crash but adds logging and doesn't hide it in acra

2024-11-29 16:50 UTC, merged