Introduce enums in Dialog
ankidroid/Anki-Android pull request #17432
Opened 2024-11-12 22:55 UTC by Arthur-Milchior

In order to improve typing

2024-11-13 19:56 UTC, david-allison requested changes
Doesn't feel like a major improvement, but OK

2024-11-13 19:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt
> +        }
as in other PRs, be explicit

2024-11-13 19:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> +const val NO_HAVE = "noHave"
note: casing was changed. This is OK

2024-11-13 19:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
> +            fun Int.toType() = Type.entries[this]
ditto

2024-11-14 01:21 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt
> +        }
I'm sorry, I'm not sure what you want here.
That the name is `ImportDialogType` instead of `ImportDialog.Type` ?
That the `toType` is documented?

2024-11-29 04:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt
> +        }
Use integers, rather than the implicit ordering of the enum values

2024-12-04 03:30 UTC, david-allison requested changes
Make the public constants private and I'll approve.

The `ARG_` prefix is a nice to have, but optional

```patch
Subject: [PATCH] refactor: extract dialog fragments from Anki[Activity/Fragment]

* dismissAllDialogFragments
* showDialogFragment

**AnkiFragment**
* showDialogFragment

This affects all callers, as we now use extension methods
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt	(revision 1cc704df7c44c59a8bb3f342fa5c8052982d687b)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt	(date 1733282778465)
@@ -20,15 +20,11 @@
 import androidx.annotation.CheckResult
 import androidx.appcompat.app.AlertDialog
 import com.ichi2.anki.R
-import com.ichi2.anki.dialogs.ImportDialog.Type.Companion.fromCode
 import com.ichi2.utils.negativeButton
 import com.ichi2.utils.positiveButton
 import timber.log.Timber
 import java.net.URLDecoder
 
-const val IMPORT_DIALOG_TYPE_KEY = "dialogType"
-const val IMPORT_DIALOG_PACKAGE_PATH_KEY = "packagePath"
-
 class ImportDialog : AsyncDialogFragment() {
     enum class Type(val code: Int) {
         DIALOG_IMPORT_ADD_CONFIRM(0), DIALOG_IMPORT_REPLACE_CONFIRM(1);
@@ -44,7 +40,7 @@
 
     override fun onCreateDialog(savedInstanceState: Bundle?): AlertDialog {
         super.onCreate(savedInstanceState)
-        val type = fromCode(requireArguments().getInt(IMPORT_DIALOG_TYPE_KEY))
+        val type = Type.fromCode(requireArguments().getInt(IMPORT_DIALOG_TYPE_KEY))
         val dialog = AlertDialog.Builder(requireActivity())
         dialog.setCancelable(true)
         val packagePath = requireArguments().getString(IMPORT_DIALOG_PACKAGE_PATH_KEY)!!
@@ -100,6 +96,8 @@
     }
 
     companion object {
+        private const val IMPORT_DIALOG_TYPE_KEY = "dialogType"
+        private const val IMPORT_DIALOG_PACKAGE_PATH_KEY = "packagePath"
 
         /**
          * A set of dialogs which deal with importing a file
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt	(revision 1cc704df7c44c59a8bb3f342fa5c8052982d687b)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt	(date 1733282523137)
@@ -15,29 +15,9 @@
 import com.ichi2.anki.AnkiActivity
 import com.ichi2.anki.DeckPicker
 import com.ichi2.anki.R
-import com.ichi2.anki.dialogs.MediaCheckDialog.Type.Companion.fromCode
 import com.ichi2.anki.showError
 import com.ichi2.libanki.MediaCheckResult
 
-/**
- * Key for an ordinal in the Type.entries.
- */
-const val MEDIA_CHECK_DIALOG_TYPE_KEY = "dialogType"
-
-/**
- * Key for an array of strings of name of missing media
- */
-const val NO_HAVE = "noHave"
-
-/**
- * Key for an array of strings of name of unused media
- */
-const val UNUSED = "unused"
-
-/**
- * Key for an array of strings of name of invalid media
- */
-const val INVALID = "invalid"
 class MediaCheckDialog : AsyncDialogFragment() {
     interface MediaCheckDialogListener {
         fun showMediaCheckDialog(dialogType: Type)
@@ -64,9 +44,9 @@
                     .create()
             }
             Type.DIALOG_MEDIA_CHECK_RESULTS -> {
-                val noHave = requireArguments().getStringArrayList(NO_HAVE)
-                val unused = requireArguments().getStringArrayList(UNUSED)
-                val invalid = requireArguments().getStringArrayList(INVALID)
+                val noHave = requireArguments().getStringArrayList(ARG_NO_HAVE)
+                val unused = requireArguments().getStringArrayList(ARG_UNUSED)
+                val invalid = requireArguments().getStringArrayList(ARG_INVALID)
                 // Generate report
                 val report = StringBuilder()
                 if (invalid!!.isNotEmpty()) {
@@ -146,14 +126,14 @@
             }
         }
 
-    private fun typeFromArguments() = fromCode(requireArguments().getInt(MEDIA_CHECK_DIALOG_TYPE_KEY))
+    private fun typeFromArguments() = Type.fromCode(requireArguments().getInt(ARG_MEDIA_CHECK_DIALOG_TYPE_KEY))
 
     override val dialogHandlerMessage: MediaCheckCompleteDialog
         get() {
             val dialogType = typeFromArguments()
-            val noHave = requireArguments().getStringArrayList(NO_HAVE)
-            val unused = requireArguments().getStringArrayList(UNUSED)
-            val invalid = requireArguments().getStringArrayList(INVALID)
+            val noHave = requireArguments().getStringArrayList(ARG_NO_HAVE)
+            val unused = requireArguments().getStringArrayList(ARG_UNUSED)
+            val invalid = requireArguments().getStringArrayList(ARG_INVALID)
 
             return MediaCheckCompleteDialog(dialogType, noHave, unused, invalid)
         }
@@ -168,11 +148,31 @@
     }
 
     companion object {
+        /**
+         * Key for an ordinal in the [Type.entries].
+         */
+        private const val ARG_MEDIA_CHECK_DIALOG_TYPE_KEY = "dialogType"
+
+        /**
+         * Key for an array of strings of name of missing media
+         */
+        private const val ARG_NO_HAVE = "noHave"
+
+        /**
+         * Key for an array of strings of name of unused media
+         */
+        private const val ARG_UNUSED = "unused"
+
+        /**
+         * Key for an array of strings of name of invalid media
+         */
+        private const val ARG_INVALID = "invalid"
+
         @CheckResult
         fun newInstance(dialogType: Type): MediaCheckDialog {
             val f = MediaCheckDialog()
             val args = Bundle()
-            args.putInt(MEDIA_CHECK_DIALOG_TYPE_KEY, dialogType.code)
+            args.putInt(ARG_MEDIA_CHECK_DIALOG_TYPE_KEY, dialogType.code)
             f.arguments = args
             return f
         }
@@ -183,10 +183,10 @@
         fun newInstance(dialogType: Type, checkList: MediaCheckResult): MediaCheckDialog {
             val f = MediaCheckDialog()
             val args = Bundle()
-            args.putStringArrayList(NO_HAVE, ArrayList(checkList.missingFileNames))
-            args.putStringArrayList(UNUSED, ArrayList(checkList.unusedFileNames))
-            args.putStringArrayList(INVALID, ArrayList(checkList.invalidFileNames))
-            args.putInt(MEDIA_CHECK_DIALOG_TYPE_KEY, dialogType.code)
+            args.putStringArrayList(ARG_NO_HAVE, ArrayList(checkList.missingFileNames))
+            args.putStringArrayList(ARG_UNUSED, ArrayList(checkList.unusedFileNames))
+            args.putStringArrayList(ARG_INVALID, ArrayList(checkList.invalidFileNames))
+            args.putInt(ARG_MEDIA_CHECK_DIALOG_TYPE_KEY, dialogType.code)
             f.arguments = args
             return f
         }
@@ -222,19 +222,19 @@
         override fun toMessage(): Message = Message.obtain().apply {
             what = this@MediaCheckCompleteDialog.what
             data = bundleOf(
-                NO_HAVE to noHave,
-                UNUSED to unused,
-                INVALID to invalid,
-                MEDIA_CHECK_DIALOG_TYPE_KEY to dialogType
+                ARG_NO_HAVE to noHave,
+                ARG_UNUSED to unused,
+                ARG_INVALID to invalid,
+                ARG_MEDIA_CHECK_DIALOG_TYPE_KEY to dialogType
             )
         }
 
         companion object {
             fun fromMessage(message: Message): MediaCheckCompleteDialog {
-                val dialogType = fromCode(message.data.getInt [...]

2024-12-04 03:30 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> +const val MEDIA_CHECK_DIALOG_TYPE_KEY = "dialogType"
These should be private

2024-12-04 03:30 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
> +    private fun type() = fromCode(requireArguments().getInt(SYNC_ERROR_DIALOG_TYPE_KEY))
preference, take it or leave it

```kotlin
    private val dialogType
        get() = Type.fromCode(requireArguments().getInt(ARG_SYNC_ERROR_DIALOG_TYPE_KEY))
```

2024-12-04 03:32 UTC, david-allison reviewed
```
> Task :AnkiDroid:ktlintMainSourceSetCheck FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt:264:75 Missing spacing before "}"
```

2024-12-07 16:27 UTC, mikehardy approved these changes
okay by me, if David agrees now

2024-12-07 18:39 UTC, david-allison reviewed
Blocker: one comment I don't understand

Everything else is nitpicks/implementer's choice 

There's a lot of code churn from adding `Type.` inside the class which defined it, which doesn't seem necessary and is more verbose than it was

2024-12-07 18:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt
> -            DIALOG_IMPORT_ADD_CONFIRM -> {
`Type.` prefix seems like noise

2024-12-07 18:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> + * Key for an array of strings of name of invalid media
I don't understand

2024-12-07 18:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> +const val INVALID = "invalid"
Should this be public?

2024-12-07 18:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> +            Type.DIALOG_CONFIRM_MEDIA_CHECK -> {
Again: `Type.` seems more verbose than what we had before

2024-12-07 18:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
> +    private fun typeFromArguments() = Type.fromCode(requireArguments().getInt(MEDIA_CHECK_DIALOG_TYPE_KEY))
nit: 

`val dialogType get()` would read much better

2024-12-07 18:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
> +            Type.DIALOG_USER_NOT_LOGGED_IN_SYNC -> res().getString(R.string.not_logged_in_title)
Shouldn't be a need for the `Type` prefix

2024-12-07 20:47 UTC, Arthur-Milchior commented
> There's a lot of code churn from adding Type. inside the class which defined it, which doesn't seem necessary and is more verbose than it was

I'm confused.
You wrote, above 

> I prefer `Type.fromCode` than `fromCode`, but this is optional

so I added the explicit `Type` prefix everywhere.

Visibly it's not what you were looking for. Can you clarify where I should have used the `Type` prefix then?

2024-12-08 00:54 UTC, david-allison commented
Here is a patch answering your question

<details>

```patch
Subject: [PATCH] 
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt	(revision 7016267ddede32c6d0f6ed7f1cf0b3bc5fb458ca)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt	(date 1733617931452)
@@ -20,6 +20,8 @@
 import androidx.annotation.CheckResult
 import androidx.appcompat.app.AlertDialog
 import com.ichi2.anki.R
+import com.ichi2.anki.dialogs.ImportDialog.Type.DIALOG_IMPORT_ADD_CONFIRM
+import com.ichi2.anki.dialogs.ImportDialog.Type.DIALOG_IMPORT_REPLACE_CONFIRM
 import com.ichi2.anki.utils.ext.dismissAllDialogFragments
 import com.ichi2.utils.negativeButton
 import com.ichi2.utils.positiveButton
@@ -47,7 +49,7 @@
         val displayFileName = filenameFromPath(convertToDisplayName(packagePath))
 
         return when (type) {
-            Type.DIALOG_IMPORT_ADD_CONFIRM -> {
+            DIALOG_IMPORT_ADD_CONFIRM -> {
                 dialog.setTitle(R.string.import_title)
                     .setMessage(res().getString(R.string.import_dialog_message_add, displayFileName))
                     .positiveButton(R.string.import_message_add) {
@@ -57,7 +59,7 @@
                     .negativeButton(R.string.dialog_cancel)
                     .create()
             }
-            Type.DIALOG_IMPORT_REPLACE_CONFIRM -> {
+            DIALOG_IMPORT_REPLACE_CONFIRM -> {
                 dialog.setTitle(R.string.import_title)
                     .setMessage(res().getString(R.string.import_message_replace_confirm, displayFileName))
                     .positiveButton(R.string.dialog_positive_replace) {
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt	(revision 7016267ddede32c6d0f6ed7f1cf0b3bc5fb458ca)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt	(date 1733618185655)
@@ -15,6 +15,8 @@
 import com.ichi2.anki.AnkiActivity
 import com.ichi2.anki.DeckPicker
 import com.ichi2.anki.R
+import com.ichi2.anki.dialogs.MediaCheckDialog.Type.DIALOG_CONFIRM_MEDIA_CHECK
+import com.ichi2.anki.dialogs.MediaCheckDialog.Type.DIALOG_MEDIA_CHECK_RESULTS
 import com.ichi2.anki.showError
 import com.ichi2.anki.utils.ext.dismissAllDialogFragments
 import com.ichi2.libanki.MediaCheckResult
@@ -36,7 +38,7 @@
         val dialog = AlertDialog.Builder(requireContext())
             .setTitle(notificationTitle)
         return when (typeFromArguments()) {
-            Type.DIALOG_CONFIRM_MEDIA_CHECK -> {
+            DIALOG_CONFIRM_MEDIA_CHECK -> {
                 dialog.setMessage(notificationMessage)
                     .setPositiveButton(R.string.dialog_ok) { _, _ ->
                         (activity as MediaCheckDialogListener?)?.mediaCheck()
@@ -47,7 +49,7 @@
                     }
                     .create()
             }
-            Type.DIALOG_MEDIA_CHECK_RESULTS -> {
+            DIALOG_MEDIA_CHECK_RESULTS -> {
                 val noHave = requireArguments().getStringArrayList(NO_HAVE)
                 val unused = requireArguments().getStringArrayList(UNUSED)
                 val invalid = requireArguments().getStringArrayList(INVALID)
@@ -111,19 +113,14 @@
 
     override val notificationMessage: String
         get() = when (typeFromArguments()) {
-            Type.DIALOG_CONFIRM_MEDIA_CHECK -> res().getString(R.string.check_media_warning)
-            Type.DIALOG_MEDIA_CHECK_RESULTS -> res().getString(R.string.check_media_acknowledge)
+            DIALOG_CONFIRM_MEDIA_CHECK -> res().getString(R.string.check_media_warning)
+            DIALOG_MEDIA_CHECK_RESULTS -> res().getString(R.string.check_media_acknowledge)
         }
 
     override val notificationTitle: String
         get() = when (typeFromArguments()) {
-            Type.DIALOG_CONFIRM_MEDIA_CHECK -> {
-                res().getString(R.string.check_media_title)
-            }
-
-            Type.DIALOG_MEDIA_CHECK_RESULTS -> {
-                res().getString(R.string.app_name)
-            }
+            DIALOG_CONFIRM_MEDIA_CHECK -> res().getString(R.string.check_media_title)
+            DIALOG_MEDIA_CHECK_RESULTS -> res().getString(R.string.app_name)
         }
 
     private fun typeFromArguments() = Type.fromCode(requireArguments().getInt(MEDIA_CHECK_DIALOG_TYPE_KEY))
@@ -197,7 +194,7 @@
         override fun handleAsyncMessage(activity: AnkiActivity) {
             // Media check results
             when (dialogType) {
-                Type.DIALOG_MEDIA_CHECK_RESULTS -> {
+                DIALOG_MEDIA_CHECK_RESULTS -> {
                     // we may be called via any AnkiActivity but media check is a DeckPicker thing
                     if (activity !is DeckPicker) {
                         showError(
@@ -211,7 +208,7 @@
                     val checkList = MediaCheckResult(noHave ?: arrayListOf(), unused ?: arrayListOf(), invalid ?: arrayListOf())
                     activity.showMediaCheckDialog(dialogType, checkList)
                 }
-                Type.DIALOG_CONFIRM_MEDIA_CHECK -> { }
+                DIALOG_CONFIRM_MEDIA_CHECK -> { }
             }
         }
 
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt	(revision 7016267ddede32c6d0f6ed7f1cf0b3bc5fb458ca)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt	(date 1733618150177)
@@ -27,6 +27,17 @@
 import com.ichi2.anki.ConflictResolution
 import com.ichi2.anki.DeckPicker
 import com.ichi2.anki.R
+import com.ichi2.anki.dialogs.SyncErrorDialog.Type.DIALOG_CONNECTION_ERROR
+import com.ichi2.anki.dialogs.SyncErrorDialog.Type.DIALOG_MEDIA_SYNC_ERROR
+import com.ichi2.anki.dialogs.SyncErrorDialog.Type.DIALOG_SYNC_BASIC_CHECK_ERROR
+import com.ichi2.anki.dialogs.SyncErrorDialog.Type.DIALOG_SYNC_CONFLICT_CONFIRM_KEEP_LOCAL
+import com.ichi2.anki.dialogs.SyncErrorDialog.Type.DIALOG_SYNC_CONFLICT_CONFIRM_KEEP_REMOTE
+import com.ichi2.anki.dialogs.SyncErrorDialog.Type.DIALOG_SYNC_CONFLICT_RESOLUTION
+import com.ichi2.anki.dialogs.SyncErrorDialog.Type.DIALOG_SYNC_CORRUPT_COLLECTION
+import com.ichi2.anki.dialogs.SyncErrorDialog.Type.DIALOG_SYNC_SANITY_ERROR
+import com.ichi2.anki.dialogs.SyncErrorDialog.Type.DIALOG_SYNC_SANITY_ERROR_CONFIRM_KEEP_LOCAL
+import com.ichi2.anki.dialogs.SyncErrorDialog.Type.DIALOG_SYNC_SANITY_ERROR_CONFIRM_KEEP_REMOTE
+import com.ichi2.anki.dialogs.SyncErrorDialog.Type.DIALOG_USER_NOT_LOGGED_IN_SYNC
 import com.ichi2.anki.joinSyncMessages
 import com.ichi2.anki.showError
 import com.ichi2.anki.utils.ext.dismissAllDialogFragments
@@ -52,7 +63,7 @@
             .setTitle(title)
             .setMessage(message)
         return when (type()) {
-            Type.DIALOG_USER_NOT_LOGGED_IN_SYNC -> {
+            DIALOG_USER_NOT_LOGGED_IN_SYNC -> {
                 // User not logged in; take them to login screen
                 dialog.setIcon(R.drawable.ic_sync_problem)
                     .setPositiveButton(R. [...]

2024-12-28 03:26 UTC, Arthur-Milchior commented
Thanks

2024-12-28 20:39 UTC, david-allison approved these changes
Cheers! Force pushed to fix a CI issue with the new ktLint not being applied

2024-12-28 20:51 UTC, merged