Some enum
ankidroid/Anki-Android pull request #17435
Opened 2024-11-12 23:03 UTC by Arthur-Milchior

Those commits add some enum for the sake of code clarity

2024-11-13 19:38 UTC, david-allison requested changes
Note: both of these classes are planned to be deleted.

Signal is fine. Good change

I don't like `Caller` from an architecture POV, but I don't feel strongly here. The code's going to go away anyway.

I do want to stop using implicit enum ordinals, and that's what I'll request changes on: that makes the order of the enums a source of bugs.

2024-11-13 19:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        enum class Caller {
call it `NoteEditorCaller`

2024-11-13 19:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +                fun Int.toCaller() = Caller.entries[this]
This is a recipe for disaster, keep the enum ints explicit

This now throws on an unexpected value

2024-11-29 03:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        }
why is `11` not in the enum?

2024-11-29 13:16 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        }
they are out of order, it's there, in line 2682 

https://github.com/ankidroid/Anki-Android/pull/17435/files#diff-6d9f7ea7bba9cc72513b5078633cee9bdbbd1ea7646114869679f302ad607459R2682

they were out of order to start so this is actually the most understandable diff and is likely why Arthur just left it in that order (but I'm just guessing there of course)

2024-11-29 15:14 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
> +        }
Thanks! That took me a while, as the constant on the next line was also 11

2024-11-29 15:14 UTC, david-allison approved these changes

2024-12-04 20:30 UTC, mikehardy approved these changes
fine by me, assuming conflict is cleaned up merge at will IMHO

2024-12-04 21:09 UTC, merged