NF: Use com.ichi2.anki.Ease as much as possible
ankidroid/Anki-Android pull request #17430
Opened 2024-11-12 22:40 UTC by Arthur-Milchior

This allows to remove else in `when` case, and generally improve typing. Also, allows to remove some constant that were duplicate of the enum entries.

2024-11-13 14:29 UTC, david-allison requested changes
Implementer's choice on most of these. Thanks so much for splitting them up!

2024-11-13 14:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Ease.kt
> +         *The Ease corresponding to the [value]. Buttons are numbered from 1 to 4.
This isn't a clear description. Could you provide an example that Again = 1 and Easy = 4

2024-11-13 14:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Ease.kt
> +    val value = ordinal + 1
Implementer's choice: I preferred the way things were before (explicit rather than implicit). 

I think we're fine in general, but I've seen too many bugs due to implicit enum ordering in my career

2024-11-13 14:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +                        buttonTexts.put(col.sched.nextIvlStr(currentCard, Ease.entries[i]))
`Ease.fromValue`?

2024-11-13 14:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/EaseButton.kt
> +    fun unblockBasedOnEase(currentEase: Ease?) {
should this be a `?`.

If not, can you add a `KotlinCleanup`. Don't put too much effort into this. Class is going away

2024-11-13 14:29 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt
> +        assertGamepadButtonAnswers(KEYCODE_BUTTON_X, Ease.HARD)
nit: Import `HARD` and `AGAIN` as well as `EASY` and `GOOD`

2024-11-13 14:29 UTC, david-allison commented on api/src/main/java/com/ichi2/anki/api/Ease.kt
>  }
I can't tell if this is a breaking API change.

But I'd rather have it explicit rather than implicit, same as above

2024-11-13 14:29 UTC, david-allison commented on api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
> +     *            |                   |            | com.ichi2.anki.api.Ease.Ease.THREE.value
revert: inconsistent

2024-11-13 14:29 UTC, david-allison commented on api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
> +     *      int ease = Ease.Ease.THREE.value; //<-- insert real ease here
ditto

2024-11-14 00:48 UTC, david-allison requested changes
Marking as 'second approval' with trust that the API documentation issues will be resolved

Minor concern we're moving away from upstream with the tests, but most of which will be in Rust by now.

2024-11-14 00:48 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> +                            Timber.i("AbstractFlashcardViewer:: Ease.ONE pressed")
This no longer matches the value

2024-11-14 00:48 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
> +        // answer good, 'Ease.THREE' should now be < 10m
unusual comment

2024-11-14 00:48 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
> +        col.getSched().answerCard(c, EaseNumber.ONE);
?

2024-11-14 00:48 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
> +        //     col.getSched().answerCard(c, EaseNumber.TWO)
?

2024-11-14 00:48 UTC, david-allison commented on api/src/main/java/com/ichi2/anki/api/Ease.kt
> + * the buttons are numbered from 1 to 4.
This class is publicly visible and exposed via our API. These comments are not useful to API consumers

Revert it, or convert it to source-only comments

2024-11-14 01:42 UTC, david-allison commented
```
/home/runner/work/Anki-Android/Anki-Android/api/src/main/java/com/ichi2/anki/api/Ease.kt:22: Error: This block comment looks like it was intended to be a KDoc comment [WrongCommentType]
 * @param value The so called value of the button. For the sake of consistency with upstream and our API
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2024-11-14 18:09 UTC, BrayanDSO requested changes

2024-11-14 18:09 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Ease.kt
> +        fun fromValue(value: Int) = Ease.entries[value - 1]
The implementation assumes that the values in the enum are ordered. This is the case now, and tbh it is unlikely to change, but I prefer to avoid future human errors when possible.

```suggestion
        fun fromValue(value: Int) = entries.first { it.value == value }
```

2024-11-14 18:09 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Ease.kt
> +         */
From the name of the enum property and the name of this method, I think that it's quite intuitive to know its purpose and anything different from that would be unexpected IMO, so I don't think that this comment is useful.

2024-11-15 01:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Ease.kt
> +        fun fromValue(value: Int) = Ease.entries[value - 1]
Currently, this is guaranteed by the documentation. https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.enums/-enum-entries.html But fine. I doubt this is in the loop where it would be an issue to iterate over four elements

2024-11-15 10:06 UTC, BrayanDSO approved these changes

2024-11-15 15:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Ease.kt
> +    }
`Ease.fromValue` (or similar).

Adding global extensions to `Int` gets messy quickly.

2024-11-15 15:47 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +                            // The value corresponds to
fragment

2024-12-04 03:06 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Ease.kt
> +    }
Oh no. I just saw this as the 4th PR I rewrite to remove `.ordinal` and now I must go back to them remove the `Int.toType` too

2024-12-04 03:45 UTC, david-allison approved these changes
Perfect, cheers!

2024-12-04 03:58 UTC, merged