Revert lint rule changes
ankidroid/Anki-Android pull request #17436
Opened 2024-11-13 09:32 UTC by jradchaima

## Purpose / Description
*   #17425
The lint build fails with the following error: "Error: For locale "ca" (Catalan) the following quantity should also be defined: many "[MissingQuantity] to solve this error I Revert lint rule changes [UnusedQuantity, MissingQuantity] from fatal to ignore 
## Fixes
*  Fixes #17425 

## Approach
I made modifications to two AndroidManifest.xml
*AnkiDroid/src/main/AndroidManifest.xml
*testlib/src/main/AndroidManifest.xml
in lint-release.xml I changed thes two line from
```xml
<issue id="UnusedQuantity" severity="fatal" />
<issue id="MissingQuantity" severity="fatal" />
```
to
```xml
<issue id="UnusedQuantity" severity="ignore" />
<issue id="MissingQuantity" severity="ignore" />

```
These changes fix the lint build failure, making the build successful
## How Has This Been Tested?

tested on emulator Google HPE device

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-11-13 16:55 UTC, mikehardy requested changes
oh wait - this is incomplete, it has two parts and the other is to implement the suggestion in this as well: https://github.com/ankidroid/Anki-Android/commit/292d662d0b676edf21939b15c88dcf38fb3d83ba

that is, to do uses-feature there, and ensure the build still passes

2024-11-15 10:27 UTC, jradchaima commented
@mikehardy I updated two AndroidManifest.xml files, and the lint build was successful when tested in Android Studio. However, the commit with the fix for the AndroidManifest.xml had some checks that were unsuccessful. I’m not sure what caused the issue, so I’m currently looking on it

2024-11-15 17:10 UTC, mikehardy requested changes
looks great - just one remaining item about a comment that no longer applies

2024-11-15 17:10 UTC, mikehardy commented on AnkiDroid/src/main/AndroidManifest.xml
> +    <!--    <uses-feature android:name. We must ensure this is never called when running on API 23.-->
this comment is no longer valid - can you remove it?

2024-11-16 07:29 UTC, jradchaima commented on AnkiDroid/src/main/AndroidManifest.xml
> +    <!--    <uses-feature android:name. We must ensure this is never called when running on API 23.-->
yes of course

2024-11-16 08:33 UTC, jradchaima commented
I made some errors while updating the branch with the latest changes. I've resolved them and ensured everything is now up-to-date. Please let me know if there's anything else you'd like me to check!

2024-11-16 14:16 UTC, mikehardy commented
The "proper" way to update the branch in AnkiDroid is never to do a merge commit - for future reference. We do a rebase-merge strategy here which is a bit unusual based on my experience interacting with other developers but results in a very very clean commit history, which is something we value

Happy to accept the merge commit this time and do a squash-merge of this PR - no problems - but if you plan to contribute to AnkiDroid in the future maybe do some test PR work on your personal Anki-Android repo fork where you locally rebase a PR pulling changes into your branch that way, then force-push back out to your branch. A bit difficult to get used to at first but then pretty easy after some practice

2024-11-16 14:17 UTC, mikehardy approved these changes
looks exactly correct now, thank you!

2024-11-16 14:18 UTC, merged

2024-11-16 18:30 UTC, jradchaima commented
Thank you so much for the advice!