NF: APIResult takes known type only
ankidroid/Anki-Android pull request #17433
Opened 2024-11-12 22:57 UTC by Arthur-Milchior

I had a bug because I sent it an enum, and it didn't know how to read it again. By ensuring it only takes known value, any dev can find really quickly where the bug comes from

2024-11-19 10:56 UTC, BrayanDSO requested changes
B, I, L and S as names aren't descriptive enough, IMO.

2024-12-04 02:57 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
> +                o.put(VALUE_KEY, value)
This uses `.put(String, Object)`

`.put(String, Double)` exists, but not `(String, Float)`

Since it's unused, I'd consider removing it

2024-12-04 03:07 UTC, david-allison requested changes
Potential issue with `Float`, would recommend changing it to `Double`, or removing

2024-12-04 03:07 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
> +        class Integer(status: kotlin.Boolean, val value: kotlin.Int) : ApiResult(status) {
Lint warning; recommends `kotlin.Int => Int`

2024-12-04 03:14 UTC, david-allison commented
Fully optional

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt	(revision ad586153de3dc1b01332d2a059ecb339899655d6)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt	(date 1733281910739)
@@ -55,6 +55,12 @@
 import org.json.JSONObject
 import timber.log.Timber
 
+typealias JvmBoolean = Boolean
+typealias JvmInt = Int
+typealias JvmFloat = Float
+typealias JvmLong = Long
+typealias JvmString = String
+
 /**
  * Key for a success value.
  */
@@ -355,14 +361,14 @@
                 val callback = object : JavaScriptSTT.SpeechRecognitionCallback {
                     override fun onResult(results: List<String>) {
                         activity.lifecycleScope.launch {
-                            val apiResult = ApiResult.String(true, Json.encodeToString(ListSerializer(String.serializer()), results))
+                            val apiResult = ApiResult.success(Json.encodeToString(ListSerializer(String.serializer()), results))
                             val jsonEncodedString = withContext(Dispatchers.Default) { JSONObject.quote(apiResult.toString()) }
                             activity.webView!!.evaluateJavascript("ankiSttResult($jsonEncodedString)", null)
                         }
                     }
                     override fun onError(errorMessage: String) {
                         activity.lifecycleScope.launch {
-                            val apiResult = ApiResult.String(false, errorMessage)
+                            val apiResult = ApiResult.failure(errorMessage)
                             val jsonEncodedString = withContext(Dispatchers.Default) { JSONObject.quote(apiResult.toString()) }
                             activity.webView!!.evaluateJavascript("ankiSttResult($jsonEncodedString)", null)
                         }
@@ -442,28 +448,28 @@
         var nextTime4 = ""
     }
 
-    sealed class ApiResult protected constructor(private val status: kotlin.Boolean) {
-        class Boolean(status: kotlin.Boolean, val value: kotlin.Boolean) : ApiResult(status) {
+    sealed class ApiResult protected constructor(private val status: JvmBoolean) {
+        class Boolean(status: JvmBoolean, val value: JvmBoolean) : ApiResult(status) {
             override fun putValue(o: JSONObject) {
                 o.put(VALUE_KEY, value)
             }
         }
-        class Integer(status: kotlin.Boolean, val value: kotlin.Int) : ApiResult(status) {
+        class Integer(status: JvmBoolean, val value: JvmInt) : ApiResult(status) {
             override fun putValue(o: JSONObject) {
                 o.put(VALUE_KEY, value)
             }
         }
-        class Float(status: kotlin.Boolean, val value: kotlin.Float) : ApiResult(status) {
+        class Float(status: JvmBoolean, val value: JvmFloat) : ApiResult(status) {
             override fun putValue(o: JSONObject) {
                 o.put(VALUE_KEY, value)
             }
         }
-        class Long(status: kotlin.Boolean, val value: kotlin.Long) : ApiResult(status) {
+        class Long(status: JvmBoolean, val value: JvmLong) : ApiResult(status) {
             override fun putValue(o: JSONObject) {
                 o.put(VALUE_KEY, value)
             }
         }
-        class String(status: kotlin.Boolean, val value: kotlin.String) : ApiResult(status) {
+        class String(status: JvmBoolean, val value: JvmString) : ApiResult(status) {
             override fun putValue(o: JSONObject) {
                 o.put(VALUE_KEY, value)
             }
@@ -475,6 +481,12 @@
             put(SUCCESS_KEY, status)
             putValue(this)
         }.toString()
+
+        @Suppress("RemoveRedundantQualifierName") // we don't want `String(true, value)`
+        companion object {
+            fun success(value: JvmString) = ApiResult.String(true, value)
+            fun failure(value: JvmString) = ApiResult.String(false, value)
+        }
     }
 
     class ApiContract(val isValid: Boolean, val cardSuppliedDeveloperContact: String, val cardSuppliedData: String)
```

2024-12-07 01:18 UTC, david-allison approved these changes
LGTM, cheers!

2024-12-07 01:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/BrowserColumnCollection.kt
> -import com.ichi2.libanki.BrowserConfig.ACTIVE_CARD_COLUMNS_KEY
Not related to the PR

2024-12-07 01:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MappableBinding.kt
> -import kotlin.collections.ArrayList
Not related

2024-12-07 01:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
> -import com.ichi2.anki.IntentHandler
Not related

2024-12-07 09:43 UTC, BrayanDSO approved these changes

2024-12-07 09:57 UTC, merged