Consts
ankidroid/Anki-Android pull request #17431
Opened 2024-11-12 22:51 UTC by Arthur-Milchior

This PR should be merged after #17430. It contains #17430 and removing #17430 would create a ton of merge conflict.

It transforms IntDef of Consts.kt into enum

2024-12-06 00:40 UTC, david-allison commented
@Arthur-Milchior Unblocked

2024-12-08 20:58 UTC, david-allison requested changes
Incomplete review, I'm not going to have time to finish it

2024-12-12 06:54 UTC, david-allison requested changes
Doesn't compile

Last round of feedback. Sorry for the back & forth. Let's get this in

2024-12-12 06:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    enum class CardType(
This should be moved outside `Consts`, there's no need to write `Consts.QueueType/CardType`

2024-12-12 06:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                    if (state.topCard.queue.reviewable()) {
Does this differ from upstream?

2024-12-12 06:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> -            if (m.getInt("type") != Consts.MODEL_STD) {
This is different. How does it differ

(On me: this was a past comment)

2024-12-12 06:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +                NEW, LRN, REV, DAY_LEARN_RELEARN, PREVIEW -> true
This doesn't make sense to me as a name. Preview is reviewable?

2024-12-12 06:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +            fun Int.toModelType() = ModelType.entries[this]
Don't add extensions to Int until Kotlin supports context parameters

2024-12-12 06:54 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
> +            put("type", value.ordinal)
Not code?

2024-12-12 06:54 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
> +        if (notetype!!.getInt("type").toModelType() == CLOZE) {
Add an extension: `notetype.type`, note that it differs from upstream

We don't use the term "model" any more I believe

2024-12-12 21:13 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
> +        if (notetype!!.getInt("type").toModelType() == CLOZE) {
Good idea. Actually, I even use `isCloze` or `isStd` when possible

2024-12-12 21:14 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> -            if (m.getInt("type") != Consts.MODEL_STD) {
I'm sorry but I don't understand how it differs from the first question

2024-12-13 01:29 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> -            if (m.getInt("type") != Consts.MODEL_STD) {
If it's only used in unit tests, it's dead code and should be removed

2024-12-14 02:12 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
> -            if (m.getInt("type") != Consts.MODEL_STD) {
Done

2024-12-14 03:12 UTC, david-allison requested changes
Each of these enums needs to handle an `unknown` value, as we previously did

In the previous code, we would be compatible with a future version of Anki Desktop. (using a new queue/type, for example).

Now we're not: `.first` throws a `NoSuchElementException`

2024-12-14 03:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                    if (state.topCard.queue.reviewable()) {
Upstream:

```python
    def onLeech(self, card: Card | None = None) -> None:
        # for now
        s = tr.studying_card_was_a_leech()
        # v3 scheduler doesn't report this
        if card and card.queue < 0:
            s += f" {tr.studying_it_has_been_suspended()}"
        tooltip(s)
```

https://github.com/ankitects/anki/blob/9c3f89466d38d72daf8f671d6f3c8b18351bc642/qt/aqt/reviewer.py#L944

Matching upstream is important because upstream will continue to shift, and having code which is nearly 1:1 comparable makes these shifts much easier to mimic. 

The Rust conversion was much harder than it needed to be **because** we deviated from upstream, and I don't want to encourage this, unless the change is obviously better.

`reviewable()` isn't obviously a better name, and this code is more brittle if Anki adds new statuses. 

Keep it at `queue.code < 0`

2024-12-14 03:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    enum class NoteTypeKind(
This doesn't need to be under `libanki.Consts.NoteTypeKind`, just `libanki.NoteTypeKind`

2024-12-14 03:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
>      // TODO: Not constrained
```suggestion
```

2024-12-29 15:40 UTC, david-allison approved these changes
Cheers!

2024-12-29 15:40 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> +                    if (state.topCard.queue.code < 0) {
nit: should use method

2025-01-01 18:20 UTC, Arthur-Milchior commented
I hope I understood correctly what you asked me to do with the unknown case.
Now if the database contains data that we don't know how to interpret we'll have a Unknown queue and card type.
I was effrayed it would break ankidroid in unexpected way. But actually, as we don't do anything except display value, I guess if anything break, it'll be backend job to handle it.

2025-01-02 10:22 UTC, david-allison commented
Needs `./gradlew --rerun-tasks ktLintFormat`, maybe over a few commits

Would also question why the pre-commit hook isn't firing. This may want to be rebased on `main` if it hasn't already

2025-01-03 19:19 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    object New : CardType(0)
prefer `data object`

2025-01-03 19:21 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
> +    object ManuallyBuried : QueueType(-3)
I would /love/ to add some documentation on these in the future. This is great stuff!

2025-01-04 11:25 UTC, lukstbit approved these changes

2025-01-04 11:25 UTC, lukstbit commented
Merging this now so it doesn't take any more conflicts.

2025-01-04 11:38 UTC, merged