NF: Use enum for flag everywhere possible
ankidroid/Anki-Android pull request #17434
Opened 2024-11-12 22:59 UTC by Arthur-Milchior

It should be added that there is some ambiguity for the value of the flag. A flag could be either between 0 and 7, or an arbitrary int whose first 3 digits are the displayed flags.

Actually, the only time a number greater than 7 is generated, it's stored into the card's `flags` field, and never leave this object. So it's okay to use `Flag` object everywhere else.

2024-11-14 18:32 UTC, BrayanDSO requested changes

2024-11-14 18:32 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
> +     */
```suggestion
    /**
     * Color for the background of cards with this flag in the card browser.
     */
```

2024-11-14 18:32 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
> +    @DrawableRes val drawableReviewerRes: Int,
This property genereates a lot of duplication just to handle a color difference in a single flag that will be gone whenever the new reviewer is the default, since it uses colorControlNormal.

I haven't checked, but it may be possible to use `colorControlNormal` everywhere even now

2024-11-14 18:32 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
> +        return (flags and 0b111).toFlag()
Please add a comment stating that this isn't equivalent to libanki. Same for the other methods you changed this file.

2024-11-14 18:32 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
> +     * Use setUserFlag instead.
```suggestion
     * Use [setUserFlag] instead.
```

2024-11-15 10:08 UTC, BrayanDSO approved these changes

2024-11-30 02:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
> +            "cardFlag" -> convertToByteArray(apiContract, currentCard.userFlag().ordinal)
This should be an explicit value on the flag, otherwise reordering the enum values is a breakage

2024-11-30 02:32 UTC, david-allison requested changes
As-per comment: `.ordinal` is dangerous: it's not a pit of success for the developer

2024-12-04 02:45 UTC, Arthur-Milchior commented
Ordinal is removed

2024-12-04 03:38 UTC, david-allison approved these changes
Really nice, thanks!

2024-12-04 03:38 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
> +        fun fromCode(code: Int) = Flag.entries.first { it.code == code }
This seems to be a no-op

2024-12-04 03:39 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
> +        fun fromCode(code: Int) = Flag.entries.first { it.code == code }
@Arthur-Milchior FYI: I'm resolving and force-pushing this to get this merged

2024-12-04 04:04 UTC, merged