fixes Settings highlight does not follow 'back button'
ankidroid/Anki-Android pull request #17447
Opened 2024-11-15 12:06 UTC by jainv4156

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
* Fixes #17414

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-11-17 16:37 UTC, Aditya13s commented
@jainv4156 , can you complete all the details in the PR template? Thanks!

2024-11-18 11:54 UTC, jainv4156 commented
> @jainv4156 , can you complete all the details in the PR template? Thanks!

just to be sure you mean testing with accessibility scanner

2024-11-18 12:02 UTC, Aditya13s commented
> just to be sure ,do you mean testing with accessibility scanner.

It's about the description and the approach you used, present in the template

2024-11-26 12:44 UTC, mikehardy requested changes
seems reasonable - tiny nitpicks just a typo

2024-11-26 12:44 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
> +            .title = TR.preferencesBackups()
this is a reasonable change but is a refactor (along with the removal of collection manager - and I was curious why it was in the same commit - we usually split refactor stuff into separate commits so that review stays focused on the functional changes. No big deal this time though - just something to keep in the mind when developing in the future - think of the person that will review your code and make sure you keep their attention focused on the important bits by not including unimportant bits at the same time

2024-11-26 12:44 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
> +    fun handelHighlightHeaderPreferenceOnBack(key: String) {
typo

```suggestion
    fun handleHighlightHeaderPreferenceOnBack(key: String) {
```

2024-11-26 12:44 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +            headerFragment?.handelHighlightHeaderPreferenceOnBack(key)
typo

```suggestion
            headerFragment?.handleHighlightHeaderPreferenceOnBack(key)
```

2024-11-26 15:36 UTC, david-allison requested changes

2024-11-26 15:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
> +        preferenceScreen?.key?.let {
> `(requireActivity() as Preferences)`

This is going to conflict with 

* https://github.com/ankidroid/Anki-Android/pull/17487

Please be sure that this method would work once the fragment is extracted from the activity

2024-11-26 15:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
> +        preferenceScreen?.key?.let {
This isn't necessary. `handleHighlightPreferenceOnBack` handles a nullable string

`        (requireActivity() as Preferences).handleHighlightPreferenceOnBack(preferenceScreen.key)` without the `let {` will work

2024-11-26 15:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +    }
Extract finding the header fragment into a property so the intent of the method is clear:

```kotlin
    fun handleHighlightPreferenceOnBack(key: String?) {
        if (key == null) return
        lateralNavigationFragment?.handleHighlightHeaderPreferenceOnBack(key)
    }
```

2024-11-27 12:24 UTC, BrayanDSO commented
That PR also fixes the issue, and closes this PR. So it won't be necessary to continue working on this PR after that. Sorry for the time spent here.

2024-11-27 17:18 UTC, jainv4156 commented
> That PR also fixes the issue, and closes this PR. So it won't be necessary to continue working on this PR after that. Sorry for the time spent here.

sure

2024-11-27 17:18 UTC, closed without merging