Handle failures to parse system WebView versions
ankidroid/Anki-Android pull request #17441
Opened 2024-11-14 12:29 UTC by lukstbit

## Purpose / Description

There are several reports in acra about crashes in _checkWebviewVersion()_ when parsing the system WebView version. It seems some of those versions appear as _"Developer Build"_ and not a simply number like we expect.

https://ankidroid.org/acra/app/1/bug/256775/report/e8bb99dc-2cb8-4a73-ab66-3491c1e2752f
https://ankidroid.org/acra/app/1/bug/253230/report/6d761065-e7d6-498a-9323-84a68f7fbfd4

Stacktrace:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.DeckPicker}: java.lang.NumberFormatException: For input string: "Developer Build"
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2683)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2744)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1495)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6181)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
Caused by: java.lang.NumberFormatException: For input string: "Developer Build"
	at java.lang.Integer.parseInt(Integer.java:521)
	at java.lang.Integer.parseInt(Integer.java:556)
	at com.ichi2.anki.InitialActivity.checkWebviewVersion(InitialActivity.java:147)
	at com.ichi2.anki.DeckPicker.onCreate(DeckPicker.kt:573)
	at android.app.Activity.performCreate(Activity.java:6785)
```

The fix consists in catching exception from the version parsing and displaying a dialog about the minimum WebView version. I also added a checkbox to this dialog to hide the dialog on future runs, if the users have a developer build it seems reasonable to expect it's above our minimum WebView version requirements.

The dialog:
![zz](https://github.com/user-attachments/assets/b7fdc98b-2867-47ff-bf69-7bfedc28a75e)

I added the _Review High Priority_ label because I think these users can't access the DeckPicker.

## How Has This Been Tested?

Not tested, just opened the dialog to see how it looks.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-11-14 14:04 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
>          val webviewVersion = webviewPackageInfo.versionName ?: run {
Instead of checking the version by the name, I think that's possible to get the version code with `.longVersionCode` (`.versionCode` in older API), then check if if is newer than that.

`Installed version: %1$d` can be removed from the warning string if necessary (or maybe only in webview developer builds).

2024-11-14 16:53 UTC, mikehardy commented
I was tempted to say "this was mostly for developers using really old emulators that can't update so just let it pass if we can't parse it" but then I saw that one of them was actually out of date - our minimum is 77 and this was M74:

> App_Chromium_M74_for_AFP_dvlp_20191128_1

Which is kind of crazy.

So I think experimentation with Brayan's suggestion is really worthwhile - we can likely not crash *and* only allow webviews that are actually new enough

There's a compat API that allows us to use longVersionCode for all APIs

https://developer.android.com/reference/kotlin/androidx/core/content/pm/PackageInfoCompat?hl=en#getLongVersionCode(android.content.pm.PackageInfo)

As an incremental improvement - that may be sufficient without any ability to suppress+continue so could be cherry-picked easily if it was in one nice commit

As a feature, the ability to suppress + continue seems nice but strings are hard to cherry-pick across branches so that would be better as a 2.20 commit and it would need to be separate

2024-11-15 06:37 UTC, lukstbit commented
I switched to using the compat _longVersionCode_ that Brayan suggested. Hope the version code I found is ok, see commit message.
I've also not made any changes to strings to not mess cherry-picking and left a TODO for that for now.

2024-11-15 10:17 UTC, BrayanDSO approved these changes
AFAICT, the webview version code is alright. It looks like it follows a pattern and starts with the third element in the version name.

e.g. 119.0.`6045.193` →  `6045193`26

2024-11-15 15:00 UTC, mikehardy requested changes

2024-11-15 15:00 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        val userVisibleCode = runCatching {
I like the implementation off getLongVersionCode a lot, I think this will fix the problem in current crash reports completely - I tested it locally and indeed an API24 / Google APIs device correctly failed the test (with good log messages) while an API34 device passed it. Additionally, even with API24 I was able to "learn more" and then continue to use the app if I liked. So that was nice

However, with the choice of `runCatching` here, a NumberFormatException will fall into the `showError` block with default param of true to call `sendExceptionReport`

So we've solved the actual problem but the crash database will continue to contain reports, potentially wasting time in the future

Perhaps a local try/catch here where we just eat errors? Or perhaps there's a version of `runCatching` that doesn't send a report (or runCatching could be extended to have a default true parameter for report sending, but we send false here?

Just looking to keep acrarium clean of reports that we've already handled, and your actual fix here seems to handle it well

https://github.com/ankidroid/Anki-Android/blob/dd4c35d8cfeb052da36ad3b149e32c954d43ba66/AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt#L270

2024-11-15 16:31 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        val userVisibleCode = runCatching {
I'm using the kotlin platform method runCatching(basically a try-catch) and not one of our catching* methods that do indeed send a report. The exception should be consumed at that point with no report in acra. Hope I'm not missing anything in your comment.

2024-11-15 17:18 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
> +        val userVisibleCode = runCatching {
Ahh didn't realize it was a platform method, all I saw was our extension off FragmentActivity that I linked
If nothing is sent to ACRA, I think this is perfect
Thanks!

2024-11-15 17:19 UTC, mikehardy approved these changes

2024-11-15 17:31 UTC, merged