Allow adding large images, fixup large image size formatting
ankidroid/Anki-Android pull request #17467
Opened 2024-11-20 20:10 UTC by mikehardy

## Purpose / Description

Attempting to test:
- #17035

Attempting to reproduce:
- #17378

Noticed that the number format on the "image too large, want to crop?" dialog was mathematically incorrect and formatted wrong.

Also noticed that if the image was too large you really just couldn't save it at all even if you were a grown adult and you knew what you were doing

## Fixes

Nothing logged, these were on the side of the thing I am focused on and I just fixed it while in there

## Approach

Read the docs for DecimalFormat, they suggest using NumberFormat so you get locale-specific formatters. Did that.

## How Has This Been Tested?

I manually verified that when I add a really large image it has the size correctly displayed now, and I can save it if I really want to.

[ankidroid_add_large_image.webm](https://github.com/user-attachments/assets/91d892a8-d37a-4bf3-ba10-792d8498e77a)

## Learning (optional, can help others)

Yak shaves always

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-11-20 22:05 UTC, mikehardy commented
Note that rendering images with WebView does not really fix the "users loading huge images" problem(s), it has different problems with huge images.

So I think this package of fixes is a good thing to have in 2.19.x if reviewers agree

2024-11-20 22:45 UTC, david-allison requested changes
One issue, rest LGTM

2024-11-20 22:45 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +        val size = numberFormat.format(length / 1000000)
Otherwise, you use integer division

```suggestion
        val size = numberFormat.format(length / 1000000.0)
```

2024-11-20 23:16 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
> +        val size = numberFormat.format(length / 1000000)
My javascript-majority tech skills are showing
Nice catch

2024-11-21 00:36 UTC, david-allison approved these changes

2024-11-21 00:55 UTC, merged

2024-11-21 00:59 UTC, criticalAY commented
Niceeee one! Just woke up but this is great

2025-01-21 21:36 UTC, Danika-Dakika commented
[This post on Reddit](https://www.reddit.com/r/Anki/comments/1i65463/recently_i_have_a_problem_with_anki_droid_not/) -- happening in 2.20.1 -- sounds a lot like this bug.

2025-01-21 21:45 UTC, criticalAY commented
We migrated to webview recently it should not happen there but I will inspect it just in case