fix: use default constructor / factory + Arguments init style
ankidroid/Anki-Android pull request #17488
Opened 2024-11-23 21:32 UTC by mikehardy

## Purpose / Description

this allows Fragment lifecycle save/restore to work seemlessly and that fixes crashes on Activity restarts

**NOTE THAT IF THIS STYLE IS OKAY - A FEW OTHER DIALOGS NEED FIXES IN SAME STYLE**

## Fixes

* Fixes #17381

## Approach

Used the approach mentioned here https://stackoverflow.com/a/51831137/9910298

- Stop providing params to constructor, so there is a default constructor as required by default Fragment factory
- Start providing params as a Bundle set in to Fragment.arguments via a static newInstance method
- Access all params via Fragment.arguments
- Handle optionally missing arguments with warnings+defaults

## How Has This Been Tested?

- Enable developer option Don't Keep Activities
- Go to Card Browser, open Actions Menu "Options"
- Background AnkiDroid, resume AnkiDroid --> crash without patch
- With patch check all toggles + background/foreground permutations

Everything seems to work

[browser-options-crashfix.webm](https://github.com/user-attachments/assets/d7d9441e-fd7a-41ee-af9f-79452ecf8a85)

## Learning (optional, can help others)

Now we don't just have Activity lifecycle problems, we have Fragment lifecycle problems. Great

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-11-23 21:33 UTC, mikehardy commented
Repeating my note here - this PR will grow with more commits fixing other dialogs if this style is okay

NOTE THAT IF THIS STYLE IS OKAY - A FEW OTHER DIALOGS NEED FIXES IN SAME STYLE

2024-11-23 21:44 UTC, BrayanDSO approved these changes
Fully agreed with empty constructors for Fragments and passing stuff with arguments. Following the Android way of things is normally the most sane alternative.

2024-11-23 21:49 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt
> +        }
More kotlinesque
```suggestion
        fun newInstance(cardsOrNotes: CardsOrNotes, isTruncated: Boolean): BrowserOptionsDialog {
            val args = bundleOf(
                "cardsOrNotes" to (cardsOrNotes == CardsOrNotes.CARDS),
                "isTruncated" to isTruncated
            )
            return BrowserOptionsDialog().apply {
                arguments = args
            }
        }
```

2024-11-23 21:51 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt
> +        }
I always appreciate the Kotlin taste pointers, thanks

2024-11-23 21:54 UTC, mikehardy commented
Okay, going to take that preliminary note of approval for the style, Kotlin-ify it, and try another Dialog Fragment or two

2024-11-23 21:59 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt
> +        val cardsOrNotesBoolean = arguments?.getBoolean("cardsOrNotes")
Oh, also please extract these key strings into constants

2024-11-24 00:04 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt
> +            val args = bundleOf(
I'd add in a `Timber.i` here

2024-11-24 10:52 UTC, lukstbit approved these changes
Yes, dialogs with constructor parameters that don't use a fragment factory should be refactored.

2024-11-24 10:52 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt
> +        fun newInstance(cardsOrNotes: CardsOrNotes, isTruncated: Boolean): BrowserOptionsDialog {
You can write this more concise like:
```
fun newInstance(cardsOrNotes: CardsOrNotes, isTruncated: Boolean) =
    BrowserOptionsDialog().apply {
        arguments = bundleOf(...
```

2024-11-24 10:52 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt
> +class BrowserOptionsDialog() : AppCompatDialogFragment() {
Also delete the (), they produce and IDE warning.

2024-11-25 23:16 UTC, mikehardy commented
Turns out there was only one other DialogFragment with a problem like this (no default constructor) and it has a Factory but it must just not get installed correctly every time. I'm not going to add that commit here, I'll work it in a separate PR

So this is ready to go

I've adopted all the feedback to make this more Kotlin-y (and extract string constants) - thank you!

Three people approved but there were enough little changes from the feedback I think at least one other person should take a final look before merge so I am repinging the reviewers but hopefully (since it is a simple change) it's easy and done

2024-11-26 00:16 UTC, david-allison requested changes
Minor improvement with constants I believe, code is good

Although I stated that the styles of `getter` was inconsistent, I prefer them the way they are now.

The following looks ugly to me

```kotlin
    private val isTruncated by lazy {
        when (arguments?.getBoolean("isTruncated")) {
            true -> true
            false -> false
            null -> {
                Timber.w("BrowserOptionsDialog instantiated without configuration.")
                false
            }
        }
   
```

2024-11-26 00:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt
> +            if (selectedButtonId == R.id.select_cards_mode) CardsOrNotes.CARDS else CardsOrNotes.NOTES
Note: this is now just a spacing change

2024-11-26 00:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt
> +        when (arguments?.getBoolean("cardsOrNotes")) {
Shouldn't this use the constant?

2024-11-26 00:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt
> +        arguments?.getBoolean("isTruncated") ?: run {
ditto

2024-11-26 00:29 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt
> +        when (arguments?.getBoolean("cardsOrNotes")) {
🤦  gah

2024-11-26 00:29 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt
> +        arguments?.getBoolean("isTruncated") ?: run {
🤦 🤦

2024-11-26 00:37 UTC, david-allison approved these changes

2024-11-26 00:54 UTC, merged