Prefs refactor
ankidroid/Anki-Android pull request #17487
Opened 2024-11-23 19:08 UTC by BrayanDSO

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
* Fixes #

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-11-26 00:49 UTC, david-allison approved these changes
Really solid, thank you!

I don't think any of the comments are blocking

2024-11-26 00:49 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferenceTestUtils.kt
> +        return keys
Very nice

2024-11-26 00:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +            supportActionBar?.title = title
If I understand this correctly, if a non-`TitleProvider` is in `R.id.settings_container`, then set the title to `""`

It feels like a `Timber.w` if this condition fails to hold, unless there are 'obvious' counterexamples

2024-11-26 00:49 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +            }
Can this be a job for a [`OnBackPressedCallback`](https://developer.android.com/reference/androidx/activity/OnBackPressedCallback)?

2024-11-26 09:26 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +            }
Done. Thanks!

2024-11-26 09:42 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +            supportActionBar?.title = title
Added a unit test to check if all the screens have a title. Hope it works

2024-11-26 11:30 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/Resources.kt
> +fun Resources.isSw600dp(): Boolean = getBoolean(R.bool.is_sw600dp)
Microsoft actually has good responsive design docs https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/layout/screen-sizes-and-breakpoints-for-responsive-design.md

The idea is that there are breakpoints and you can ask "is at least ..." or "is..."

And you want at least small / medium / large sizes based on the actual DP

so an isSmall/isMedium/isLarge and an isAtLeastMedium would do it ?

Kind of over-engineered but also has worked well for me in practice

2024-11-26 11:35 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/Resources.kt
> +fun Resources.isSw600dp(): Boolean = getBoolean(R.bool.is_sw600dp)
Material reference: https://m3.material.io/foundations/layout/applying-layout/window-size-classes

so that means a medium window

2024-11-26 12:09 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/Resources.kt
> +fun Resources.isSw600dp(): Boolean = getBoolean(R.bool.is_sw600dp)
Done the [changes](https://github.com/ankidroid/Anki-Android/pull/17487/commits/4fde8ba5310e43e2b6b67fc09e055c76602954ae#diff-3e30fe3c1460076e9e66ad9fd2f0f2df8613acdf5c9aca1e9de739dcbdc61d66R67-R70)

2024-11-26 15:09 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/utils/Resources.kt
> +fun Resources.isSw600dp(): Boolean = getBoolean(R.bool.is_sw600dp)
Shower thought: is it feasible to call it `isMultiPanelLayout`

2024-11-26 15:21 UTC, david-allison requested changes
lint failure

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt b/AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt	(revision d3c3e62c0499ce015bef539528ed5554103bb47f)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt	(date 1732633838151)
@@ -24,7 +24,6 @@
 import android.os.Bundle
 import android.view.View
 import androidx.activity.OnBackPressedCallback
-import androidx.activity.addCallback
 import androidx.annotation.XmlRes
 import androidx.core.os.bundleOf
 import androidx.fragment.app.Fragment
@@ -40,7 +39,6 @@
 import com.ichi2.anki.R
 import com.ichi2.anki.SingleFragmentActivity
 import com.ichi2.anki.utils.isWindowCompact
-import com.ichi2.themes.setTransparentStatusBar
 import com.ichi2.utils.getInstanceFromClassName
 import timber.log.Timber
 import kotlin.reflect.KClass
```

Since we're squashing, can be a separate commit

2024-11-26 16:33 UTC, BrayanDSO commented
That bug also happens when clicking a search result and that PR doesn't fix that. I could fix both issues without much hassle in a commit here.

2024-11-26 17:10 UTC, david-allison commented
@BrayanDSO Your call

@jainv4156 FYI

2024-11-26 22:58 UTC, BrayanDSO commented
Done

2024-11-27 00:35 UTC, david-allison approved these changes
A few nitpicks. Code looks great!

**Note to second reviewer: this now wants two commits, so should be squashed manually**

2024-11-27 00:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
> +    private fun highlightPreference(keyRes: Int) {
I believe this requires `@StringRes`

2024-11-27 00:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
> +            return when (fragment) {
nits: 

* javadoc with example
* `@StringRes` on the result (I believe this is possible)

----

I was going to ask for a test here... and there is one! Thank you so much!

2024-12-03 11:47 UTC, lukstbit approved these changes
LGTM, squash into two commits and merge at will.

Left a minor point about _Up_ if you want to consider it, but I don't consider it blocking.

2024-12-03 11:47 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +            .setNavigationOnClickListener { onBackPressedCallback.handleOnBackPressed() }
I haven't flagged this a review request because the previous code has the same behavior, but I think the navigation listener shouldn't behave as the BACK button and it should close the activity:

`.setNavigationOnClickListener { requireActivity().finish() }`

The _Up_ button should be used to [navigate the app screens](https://developer.android.com/develop/ui/views/components/appbar/up-action) and not got through all user actions like the BACK button does. It's not something really problematic but I would still go with the platform behavior which the average android user would expect.

2024-12-03 15:36 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
> +            .setNavigationOnClickListener { onBackPressedCallback.handleOnBackPressed() }
Done. Thanks!

2024-12-03 16:00 UTC, merged

2024-12-03 16:57 UTC, mikehardy commented
I will cut the release-2.20 branch just prior to this merge commit just in case, hopefully no offense @BrayanDSO 

But! I'm mostly commenting to say that I *think* we can also flip on the new reviewer by default in a PR as well? line it up for 2.21, get that thing out there

2024-12-03 18:22 UTC, BrayanDSO commented
> hopefully no offense

None taken.

> we can also flip on the new reviewer by default in a PR as well?

Still a bit far from done.