Fixed CardBrowser Heading Language Change
ankidroid/Anki-Android pull request #17497
Opened 2024-11-25 21:55 UTC by soCallmeAdityaKumar

## Purpose / Description
On Changing the language, heading doesn't changes immediately

## Fixes
* Fixes #17367 

## Approach

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-11-26 00:35 UTC, david-allison requested changes
* Is it feasible to add a unit test for this one? The ViewModel should be well tested.
* Is it feasible to move this inside the ViewModel, so the UI is reacting to a change in ViewModel
* Should this be in `onConfigurationChanged` or `onResume`?
  *  Is it worthwhile to add an `AnkiDroid Language Changed` event? 
  * ^ maybe not, given we shouldn't be handling configuration changes manually most of the time

2024-11-26 00:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
> +            setUpColumns()
Rename: two methods one after the other with the same name

2024-11-26 00:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        if (viewModel.flowOfInitCompleted.value) {
Add a comment explaining the intent of this

2024-11-26 00:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +    private fun setupColumnSpinners() {
as below, revert + react to the ViewModel change

2024-11-26 00:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                setupColumnSpinners()
This should react to the ViewModel change inside `setupFlows`

2024-11-26 00:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                viewModel.setUpColumns()
This should trigger a ViewModel change (or not, if the language didn't change)

2024-11-26 00:35 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
>      override fun onResume() {
Should this be in `onConfigurationChanged`?

2024-11-26 15:36 UTC, soCallmeAdityaKumar commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                viewModel.setUpColumns()
yeah  viewModel will fetch the columns again , if even when the card browser resume

2024-11-28 18:28 UTC, soCallmeAdityaKumar commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        if (viewModel.flowOfInitCompleted.value) {
Added

2024-11-28 18:28 UTC, soCallmeAdityaKumar commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
> +            setUpColumns()
Done

2024-11-28 18:29 UTC, soCallmeAdityaKumar commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                setupColumnSpinners()
done

2024-11-28 18:30 UTC, soCallmeAdityaKumar commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
>      override fun onResume() {
On language change this doesnot trigger the onConfiguration Change

2024-11-29 21:28 UTC, david-allison commented
I don't believe this is ready to review, if you've identified an issue

2024-12-07 08:51 UTC, soCallmeAdityaKumar commented
@david-allison i have noticed that certain text in cardBrowser are not translated properly if language is changed from other language to SystemLanguage.

https://github.com/user-attachments/assets/027dc105-c7b4-4046-9a7e-994458df4fe9

2024-12-07 18:11 UTC, david-allison commented
That's a known issue. Focus on the column headers, as those are defined in the ViewModel

2024-12-10 17:42 UTC, soCallmeAdityaKumar commented
@david-allison  i need to add tests for viewmodel for this case or is there something more I have to do?

2024-12-11 05:24 UTC, david-allison commented
That's it

2024-12-11 05:25 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
> +        if (flowOfLanguageChanged.value != LanguageUtil.getSystemLocale().language) {
Is this necessary? I thought a `MutableStateFlow` didn't emit duplicates

2024-12-13 08:40 UTC, soCallmeAdityaKumar commented on AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
> +        if (flowOfLanguageChanged.value != LanguageUtil.getSystemLocale().language) {
yeah , fixed

2024-12-13 08:42 UTC, soCallmeAdityaKumar commented
@david-allison  i have tried but i am not able add tests for  this, because i am not able to find a way to change the language in test so that the new column2candidates are fetched on automatically.

2024-12-13 09:11 UTC, david-allison commented
Look into how the preferences screen does it

2024-12-27 10:09 UTC, soCallmeAdityaKumar commented
not stale

2024-12-28 21:08 UTC, david-allison commented
@soCallmeAdityaKumar Still waiting for feedback though?

2024-12-29 07:14 UTC, soCallmeAdityaKumar commented
> @soCallmeAdityaKumar Still waiting for feedback though?

yeah still i am working on this, figuring out

2024-12-29 18:16 UTC, soCallmeAdityaKumar commented
@david-allison  opened a new pr for this  ->https://github.com/ankidroid/Anki-Android/pull/17687
git merge conflicts and then messed with the files, so opened a new one, hope it fixes the and close this issue , added the test in that

2024-12-29 18:38 UTC, mikehardy commented
> got merge conflicts and then messed with the files, so opened a new one

Inability to drive git well as a user isn't a great reason to break the conversation / review context on a PR by hopping over to another one. It seems that spending some quality time getting better at driving git would pay dividends

2024-12-30 03:48 UTC, soCallmeAdityaKumar commented
> > got merge conflicts and then messed with the files, so opened a new one
> 
> Inability to drive git well as a user isn't a great reason to break the conversation / review context on a PR by hopping over to another one. It seems that spending some quality time getting better at driving git would pay dividends

sorry, @mikehardy , i was not diverting the conversation, just got messed with local files and got lost the track so opened a new fresh branch , i am still learning git

2025-01-02 14:29 UTC, soCallmeAdityaKumar commented
@david-allison  i have added the test should i open this

2025-01-03 15:40 UTC, david-allison commented
Yes, but please fix the git history. It makes it difficult to review

2025-01-03 15:42 UTC, david-allison requested changes

2025-01-03 15:42 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt
> +    @Config(qualifiers = "da")
This test passes on `main`

2025-01-04 06:35 UTC, soCallmeAdityaKumar commented
> Yes, but please fix the git history. It makes it difficult to review

Ok will do this .

2025-01-21 07:39 UTC, closed without merging