Fixes #17520
ankidroid/Anki-Android pull request #17531
Opened 2024-12-01 21:13 UTC by tanishy7777

Added a dependency on the assemblePlayDebugAndroidTest task from AnkiDroid's androidTest in build.gradle.

## Purpose / Description
Fixes the issue #17520 by adding  a dependency on the assemblePlayDebugAndroidTest task from AnkiDroid's androidTest in build.gradle.

## Fixes
* Fixes #17520 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-12-01 22:04 UTC, mikehardy requested changes
Hey there 👋  welcome to AnkiDroid

One subtle suggestion here but otherwise, this seems like it should work!

You erased the testing section of the PR template though so I am not sure how you proved to yourself it worked? 

Please re-insert that section, then show the results of a `./gradlew androidTest -v` (I think `-v` prints out the executed tasks...) before and after the change to see if the new task dependency is definitely missing before and definitely there after in the list of executed tasks

2024-12-01 22:04 UTC, mikehardy commented on AnkiDroid/build.gradle
> +tasks.named("assemblePlayDebugAndroidTest") {
The other task dependencies use `.configure` for a reason: it is done that way in order to work well with Gradle's ability to defer configuration, which can speed compilation for jobs that don't use some tasks and thus don't need to configure them

This was suggested as something to change via gradle lint rules in one of the recent gradle updates

https://github.com/ankidroid/Anki-Android/pull/14855/commits/68b1f68a9dd3950bd2a633af89175daea915a6e3

```suggestion
tasks.named("assemblePlayDebugAndroidTest").configure {
```

2024-12-01 22:05 UTC, mikehardy commented
Actually, it looks like it didn't compile at all

> 
> * Where:
> Build file '/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/build.gradle' line: 285

Did you run this prior to submitting it?

2024-12-08 13:44 UTC, MritunjayTiwari14 commented
Shall i work on this issue?

2024-12-08 16:15 UTC, mikehardy commented
@tanishy7777 do you intend to get this working locally and respond to the comment?

@MritunjayTiwari14 I'm not sure what you are talking about. I'm not sure what hamcrest etc have to do with it, I don't see any errors related to that.

2024-12-09 06:31 UTC, MritunjayTiwari14 commented
Alright, just saw the other PR where David had already fixed the Dependency issue.

2024-12-09 07:37 UTC, david-allison commented
I presume my PR was: 

* https://github.com/ankidroid/Anki-Android/pull/17519

To note: this issue (#17520) is a follow-on from that PR

* #17520

2024-12-09 07:58 UTC, MritunjayTiwari14 commented
@david-allison just want to confirm that is Gradle still throwing those duplicate class errors while trying to compile?

2024-12-30 09:37 UTC, closed without merging