NF: Remove `else ->` when possible
ankidroid/Anki-Android pull request #17568
Opened 2024-12-06 23:53 UTC by Arthur-Milchior

#17352 duplicated. For some reason I can't re-open it

When `when` is used on an enum, the `else ->` can always be transformed into a complete enumeration of the enum's entries.

This ensure that each time a new entry is added, there is a warning and the developer must decide whether or not a change is needed. While the `else` may hide some required change.

So, for the sake of future developement, I removed `else ->` when it makes sense.

I should note that I kept some `else ->` when the `when` consider only a very small part of all possible enum value, in order to reduce the size of the code.

2024-12-07 09:54 UTC, BrayanDSO approved these changes
LGTM

2024-12-07 18:09 UTC, mikehardy requested changes
I like the else-to-specific-cases transform, but I counted 5 other changes in here in 2 categories of nullability changes and code deletion changes. Those may be okay on their own as well but they don't seem like they're intended to be included in the single commit given it only discuses the else transform?

2024-12-07 20:44 UTC, Arthur-Milchior commented
Visibly wrong conflict resolution. reverted. Thanks

2024-12-07 20:48 UTC, mikehardy requested changes
I'm ready to hit that merge button but still two tiny things

2024-12-07 20:48 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/MediaPlayer.kt
> +
what's this?

```suggestion
```

2024-12-07 20:48 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
> -val SOUND_RE = Pattern.compile("\\[sound:([^\\[\\]]*)]").toRegex()
not exactly an else removal :-)

2024-12-08 14:12 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/MediaPlayer.kt
> +
Don't know how I introduced this one

2024-12-08 14:15 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
> -val SOUND_RE = Pattern.compile("\\[sound:([^\\[\\]]*)]").toRegex()
It was not used anymore and I cleaned this part of the code.
I can add part and we can remove it later

2024-12-08 16:22 UTC, mikehardy approved these changes
fixed the trivial compile error introduced in response to my request to not have deletions unrelated to the else transform, the import for the re-added chunk was missing

in the hands of CI now...

2024-12-08 16:45 UTC, merged