NF: rename model to note type
ankidroid/Anki-Android pull request #17598
Opened 2024-12-14 06:39 UTC by Arthur-Milchior

As David mentioned recently, Anki don't use "model" anymore, it should not be in the codebase.

There are two places where `model` should not be replaced. When the variable refers to a model that is not a note type (e.g. a viewModel, the Card Browser's model..). And when the word "model" appears in the API. Indeed we should not break the existing code using the API.

While it may be considered to extend our API, duplicating the Model commands to introduce a NoteType command with the same meaning. And, maybe one day, deprecate the previous API. But I don't think there is even a need to deprecate the API, it does not really lead to confusion.

On top of replacing "model", "models", "Model", "Models", "MODEL", "MODELS", we also rename the variables "m", "m2" and "mm" as those variable where abbreviations for "Model". I renamed some layout, menu,

In one case, the documentation was wrong. It mentioned "model" instead of "template". I thus replaced "model" by "template" in order to correct the documentation.

Note that all the changes were done manually. I used Android-Studio to rename function, variables, values and constant. But I generally avoided the "search and replace" feature which may have led to erroneous update. (Example of exception: `m` and `mm` in `modelTest`

2024-12-14 09:56 UTC, david-allison requested changes
This is a huge change, could it be broken down to PRs in the ~300LOC level, so it's reasonable to review in a sitting?


* This contains breaking changes to our API
  * Note: Renaming parameters in Kotlin is a breaking change
* Renaming an activity is a breaking change to our public API
* `addNoteUsingBasicModel` might as well be `addBasicNote`
* `NoteTypeType` is not a good name

2024-12-14 09:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteTypeFieldEditor.kt
> +                        this@NoteTypeFieldEditor.showDialogFragment(c)
the `@` shouldn't be necessary at all

2024-12-14 09:56 UTC, david-allison commented on AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
> +    ): Note = addNoteUsingNoteTypeName("Basic (type in the answer)", front, back)
`addNoteOfType` would seem sensible

2024-12-29 13:14 UTC, Arthur-Milchior commented
> This is a huge change, could it be broken down to PRs in the ~300LOC level, so it's reasonable to review in a sitting?

Not very easily.  `git reset HEAD^` followed by interactively adding some small part of the code one by one would not work. Any function that is renamed may impact many files. Even changing a variable from `m` to `noteType` couldn't easily be added with `git add -i`, because the lines are changed from `val m = getModel()` to `val noteType = getNoteType()`.

> * This contains breaking changes to our API
>   
>   * Note: Renaming parameters in Kotlin is a breaking change

I first thought that you were referring to ContentProvider. But there I only changed parameters of private function, so I don't except this is breaking anything, given that all calls to those methods are changed simultaneously.
I also changed private constants and local varibles. 

Is there any other library we export to other code not contained in the ankidroid repo? 


> * Renaming an activity is a breaking change to our public API

I assume you are speaking of `ModelFieldFieldEditor`.  Or are you referring to any other activity I'm missing? 
I would not have thought that we were offering this activity to other app. I guess they technically may open it. I can't imagine why an external app would directly offer to open our activity to edit the list of fields of a note type.

> * `addNoteUsingBasicModel` might as well be `addBasicNote`

Right. I also did the same change to other functions nearby

> * `NoteTypeType` is not a good name

The name out of context is certainly bad. `TypeOfNoteType` would avoid the immediate repetition, but not be consistent with the name of other enums.  And the note type contains a field named type, so this is really the name that makes sense.

2025-01-15 18:46 UTC, david-allison commented
* Moving through, via https://github.com/ankidroid/Anki-Android/pull/17771

2025-03-16 14:38 UTC, closed without merging