fix onBackPressed  deprecation of CardTemplateEditor
ankidroid/Anki-Android pull request #17599
Opened 2024-12-14 08:05 UTC by Prince-kushwaha

## Purpose / Description
fix onBackPressed  deprecation of CardTemplateEditor

## Fixes
* Fixes #14558

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-12-14 13:23 UTC, lukstbit requested changes
This looks good. 

One extra thing left over is a call in CardTemplateEditor's _onOptionsItemSelected()_method to the deprecated _onBackPressed()_ that should be replaced with:

_onBackPressedDispatcher.onBackPressed()_

2024-12-14 17:12 UTC, lukstbit requested changes

2024-12-14 17:12 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
>      @Suppress("DEPRECATION")
Also remove the annotation, the deprecation was fixed.

2024-12-15 14:12 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +            templateEditor.onBackPressedCallback.isEnabled = false
Is this necessary?

2024-12-15 14:13 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
> +    val onBackPressedCallback =
I'd rename to describe what the callback does: `displayDiscardChangesCallback`

2024-12-15 14:41 UTC, david-allison approved these changes
Looks great, cheers!

2024-12-15 17:55 UTC, lukstbit approved these changes
LGTM, thanks for making the changes.

2024-12-15 18:08 UTC, merged