Fix onBackPressed() deprecation In Card Browser
ankidroid/Anki-Android pull request #17594
Opened 2024-12-12 17:46 UTC by Prince-kushwaha

## Purpose / Description
Fix onBackPressed() deprecation In Card Browser

## Fixes
* Fixes #14558

## How Has This Been Tested?

Physical Device

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-12-12 19:52 UTC, david-allison requested changes

2024-12-12 19:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                    }
Too much logic in here. Split it into multiple dispatchers

2024-12-13 06:10 UTC, lukstbit requested changes
The goal of the new predictive back navigation is to have distinct back callbacks for any actions you may want on BACK pressed and to enable/disable those callbacks  dynamically so the system knows ahead of time if you are managing the back action or the system should handle it(and show animations).

Using OnBackPressedCallback and permanently have it enabled is equivalent with the current onBackPressed() so the changes in this PR are not an improvement.  I would rather keep the deprecated onBackPressed callback present because it stands out as needing to be fixed, instead of the callback which is going to make it harder to see there's an issue.

2024-12-14 11:05 UTC, Prince-kushwaha commented
Hi David, I will address the review points

2024-12-24 16:32 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +        isInMultiSelectMode: Boolean,
This seems to be false on all 3 calls

2024-12-24 17:17 UTC, david-allison requested changes
I don't feel this code matches the logic which the previous 

* If the drawer is open, the drawer should take prioirty
* If multiselect is open, it should be closed

If neither happen, there shouldn't be an active back dispatcher, and the activity should close normally, with the provided result set somewhere before the back button was pressed (`fail` + reload required should be the default).

A test here would also be great, regarding the exit + exit intent.

2024-12-24 17:17 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                closeCardBrowser(RESULT_OK, data)
This seems... unusual. It feels like it shouldn't be in the callback and should be the default of pressing 'back', unless there's documentation to disagree.

2024-12-24 17:17 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                    )
I don't get why these are combined. It would make more sense for me that opening the drawer is responsible for the drawer callback, and that opening multiselect is responsible for the multiselect callback

Then the order in which the callbacks are applied affects the action which is reversed first.

2024-12-26 15:44 UTC, lukstbit requested changes
First of all the drawer back state is handled in the super class. I defined there a back callback that should be exposed to subclasses to add to the back dispatcher. Also note that the order of adding the callbacks is important.

Secondly, there shouldn't be a "default" back callback because this would defeat the entire purpose of the new system(to know ahead of time the status of any back actions).

2024-12-27 13:16 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                    )
defined the order of callback drawerBackCallback->multiSelectBackCallback->closeCardBrowserBackCallback

2024-12-27 13:18 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
> +                closeCardBrowser(RESULT_OK, data)
this back callback method responsible for close of CardBrowser.

2024-12-27 13:28 UTC, Prince-kushwaha commented
Hi @david-allison ,i defined the order of callback method ->drawerBackCallback->multiSelectBackCallback->closeCardBrowserBackCallback. and it is matching the logic of the previous implementation (onBackPressed). Below adding the testing video of it 

https://github.com/user-attachments/assets/aa274cec-fc69-473b-88b6-ee499b60abdc

2024-12-29 12:14 UTC, david-allison requested changes
Forgot to submit

2025-01-26 23:46 UTC, closed without merging