fix: Navigate Up versus Close
ankidroid/Anki-Android pull request #17623
Opened 2024-12-18 14:59 UTC by Prince-kushwaha

## Fixes
* Fixes #17609 

## How Has This Been Tested?

Physical Device

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-12-18 16:30 UTC, lukstbit requested changes
This breaks the home icon.
The changes required for fixing the issue:

- replace the current (x) with the platform UP arrow icon (<-) so we match the platform UI
- on clicking that icon we should leave the screen completely
- don't break the home toolbar icon

2024-12-21 09:43 UTC, lukstbit approved these changes
Thanks!

2024-12-21 15:27 UTC, mikehardy requested changes
request for comments explaining

2024-12-21 15:27 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +        } else if (item.itemId == android.R.id.home) {
I feel like this needs an explanation - as someone unfamiliar with this area of code, I'm unclear how-and-why `R.id.home` is different from `android.R.id.home`

But it appears that difference is critical to this PR

Could you add a comment on line `item.itemId == R.id.home` explaining what that item is, then a comment on the second one explaining what that is and why it's different from the first one?

I recognize this may be simple and well-understood to anyone else but for me at least, I need the comments to understand it

2024-12-21 16:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +        } else if (item.itemId == android.R.id.home) {
For reference: 

`home` is our icon with the "home page" which takes you back to the main deck search page

`android.home` is the standard 'arrow' button taking you to the previous screen

![Screenshot_20241221_163302_AnkiDroid.jpg](https://github.com/user-attachments/assets/e83736b8-b1b7-432b-9e74-a32c84bab924)

2024-12-21 18:10 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +        } else if (item.itemId == android.R.id.home) {
that sounds like it could be the reference I'm looking for in the comment so it is a lot less of a "hmm?" for anyone that sees it

2024-12-22 04:43 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +        } else if (item.itemId == android.R.id.home) {
// R.id.home refers to a custom 'home' menu item defined in your app resources (res/menu/...)
 // android.R.id.home refers to the system-provided "up" button in the app toolbar
.

2024-12-22 21:09 UTC, mikehardy approved these changes
Thanks for adding the comment - didn't mean to be picky it was just subtle and I thought a comment addition would be really easy + help in the future. I appreciate it anyway

Cheers

2024-12-22 21:21 UTC, merged

2024-12-23 14:42 UTC, mikehardy commented
Thought this was pickable for a 2.20.1 release and gave it a shot but it relies on other changes already being in place from #17579 and those don't pick cleanly at all, so no cherry-pick for this one