Added checkbox for colpkg and apkg exports to match Anki desktop
ankidroid/Anki-Android pull request #17626
Opened 2024-12-18 18:13 UTC by Haz3-jolt

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
* Fixes #17536 

## Approach
Adds a checkbox and uses the common string to interop with Ani Desktop

## How Has This Been Tested?
Did visual confirmation along with a screen recording of the changes and checked the sizes of the exports to confirm that legacy is being triggered properly.

[Screen_recording_20241218_215818.webm](https://github.com/user-attachments/assets/bed6730d-9a20-42c8-84bd-594bd0a3df9c)

## Learning (optional, can help others)
Had to play around with the XML for a bit to get it to align, and other than that nothing much

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-12-18 18:43 UTC, david-allison reviewed
Thanks! You mentioned adding a few needs test annotations, but they don't seem to be in this PR

2024-12-18 18:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +            collectionExportLegacyCheckbox.visibility = View.VISIBLE
Use `isVisible`to simplify

2024-12-18 18:43 UTC, david-allison commented on AnkiDroid/src/main/res/layout/dialog_export_options.xml
> +            android:layout_height="wrap_content"
Set `tools:text` to a hard coded string so we have a preview

2024-12-18 18:43 UTC, david-allison commented on AnkiDroid/src/main/res/layout/dialog_export_options.xml
> +                android:id="@+id/export_legacy_checkbox_apkg"
Ditto

2024-12-18 18:43 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +        if (targetConfig.layoutId == R.id.export_extras_collection || targetConfig.layoutId == R.id.export_extras_apkg) {
I'm extremely tired and find this logic confusing. A comment may help here

2024-12-18 18:48 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +        if (targetConfig.layoutId == R.id.export_extras_collection || targetConfig.layoutId == R.id.export_extras_apkg) {
Its just to find if user is using apkg export or colpkg export, will comment

2024-12-18 18:49 UTC, Haz3-jolt commented
> Thanks! You mentioned adding a few needs test annotations, but they don't seem to be in this PR

Whoops, missed a commit, will do in a sec

2024-12-18 18:56 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +            collectionExportLegacyCheckbox.visibility = View.VISIBLE
Done

2024-12-18 18:56 UTC, Haz3-jolt commented on AnkiDroid/src/main/res/layout/dialog_export_options.xml
> +            android:layout_height="wrap_content"
Sure!

2024-12-18 22:45 UTC, david-allison requested changes

2024-12-18 22:45 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +        if (targetConfig.layoutId == R.id.export_extras_collection || targetConfig.layoutId == R.id.export_extras_apkg) {
To confirm; I wasn't just tired, there's a bug here

<img width="372" alt="Screenshot 2024-12-18 at 22 44 22" src="https://github.com/user-attachments/assets/294e4c76-75d3-4ad8-a3ec-29bbdd2142e9" />

2024-12-18 22:52 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +        }
I don't believe this code should exist at all. The code below should handle visibility of the container which contains the checkbox

```suggestion
```


```kotlin
        ExportConfiguration.entries.forEach { config ->
            container.findViewById<View>(config.layoutId).isVisible =
                config.layoutId == targetConfig.layoutId
        }
```

2024-12-18 22:53 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +            decksSelectorContainer.isVisible = false
Since we're no longer modifying this method, I'd split this change into a separate commit

2024-12-19 04:50 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +        if (targetConfig.layoutId == R.id.export_extras_collection || targetConfig.layoutId == R.id.export_extras_apkg) {
Will change but wondering why this worked on my end.

2024-12-19 04:56 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +        if (targetConfig.layoutId == R.id.export_extras_collection || targetConfig.layoutId == R.id.export_extras_apkg) {
It was triggered after a few flips between the export format

2024-12-19 04:58 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +            decksSelectorContainer.isVisible = false
Done, Ill splinter into seprate commit for refactoring

2024-12-19 04:59 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +        if (targetConfig.layoutId == R.id.export_extras_collection || targetConfig.layoutId == R.id.export_extras_apkg) {
ahh ok ok got it, good to know!

2024-12-19 05:25 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +        }
Done!

2024-12-19 05:31 UTC, david-allison requested changes

2024-12-19 05:31 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +        ExportConfiguration.entries.forEach { config ->
This code already exists below

2024-12-19 05:33 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +        ExportConfiguration.entries.forEach { config ->
Yeah I Amended the commit to seprate out the Visible to isVisible refactoring.

Rebase works now, so just redid the commits for a cleaner history

2024-12-19 07:16 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +        }
This appears to duplicate line 311

2024-12-19 07:17 UTC, david-allison requested changes
+ please squash commits 1 & 2

2024-12-19 07:48 UTC, Haz3-jolt commented
> & please squash commits 1 & 2

Done!

2024-12-19 07:57 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +        }
Just noticed, will amen one sec.

2024-12-19 08:20 UTC, Haz3-jolt commented
Just had to do some final cleanup in commit history! Should be good now!

2024-12-19 09:32 UTC, david-allison approved these changes
Other than the below, LGTM, thanks!!

Apply this to the second commit, it shouldn't be necessary to move the code around.

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt	(revision 89ae09b77bdc85a96dbd768e8d72fc57de7400dd)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt	(date 1734600673197)
@@ -291,11 +291,7 @@
         container: View,
         targetConfig: ExportConfiguration,
     ) {
-        // show the legacy checkbox only for collection and apkg exports
-        ExportConfiguration.entries.forEach { config ->
-            container.findViewById<View>(config.layoutId).isVisible =
-                config.layoutId == targetConfig.layoutId
-        }
+        // if we export as collection there's no deck/selected items to choose from
         if (targetConfig.layoutId == R.id.export_extras_collection) {
             decksSelectorContainer.isVisible = false
             selectedLabel.isVisible = false
@@ -309,6 +305,10 @@
             }
         }
         exportTypeSelector.setSelection(targetConfig.index)
+        ExportConfiguration.entries.forEach { config ->
+            container.findViewById<View>(config.layoutId).visibility =
+                if (config.layoutId == targetConfig.layoutId) View.VISIBLE else View.GONE
+        }
     }
 
     private fun handleCollectionExport() {
```

2024-12-19 09:37 UTC, Haz3-jolt commented
> Other than the below, LGTM, thanks!!
> 
> Apply this revert to the second commit, it shouldn't be necessary to move the code around.
> 
> ```diff
> Index: AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> --- a/AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt	(revision 89ae09b77bdc85a96dbd768e8d72fc57de7400dd)
> +++ b/AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt	(date 1734600673197)
> @@ -291,11 +291,7 @@
>          container: View,
>          targetConfig: ExportConfiguration,
>      ) {
> -        // show the legacy checkbox only for collection and apkg exports
> -        ExportConfiguration.entries.forEach { config ->
> -            container.findViewById<View>(config.layoutId).isVisible =
> -                config.layoutId == targetConfig.layoutId
> -        }
> +        // if we export as collection there's no deck/selected items to choose from
>          if (targetConfig.layoutId == R.id.export_extras_collection) {
>              decksSelectorContainer.isVisible = false
>              selectedLabel.isVisible = false
> @@ -309,6 +305,10 @@
>              }
>          }
>          exportTypeSelector.setSelection(targetConfig.index)
> +        ExportConfiguration.entries.forEach { config ->
> +            container.findViewById<View>(config.layoutId).visibility =
> +                if (config.layoutId == targetConfig.layoutId) View.VISIBLE else View.GONE
> +        }
>      }
>  
>      private fun handleCollectionExport() {
> ```

Done!

2024-12-19 11:28 UTC, BrayanDSO approved these changes

2024-12-19 13:13 UTC, david-allison commented
I don't mind squashing this, or I can rebase when I'm at a PC

2024-12-19 13:20 UTC, Haz3-jolt commented
> I don't mind squashing this, or it can be rebased to two commits, but we need to do this before adding it to the merge queue

I don't mind either way. It's up to you

2024-12-19 15:31 UTC, david-allison commented
Blocked on https://github.com/ankidroid/Anki-Android/pull/17631

Then needs a fixup via rebase

2024-12-19 18:53 UTC, BrayanDSO commented
I preferred squash because of `ExportConfiguration.entries.forEach { config ->...` being moved up in a commit, then back at where it was in the next one.

If that block is never moved, rebase is fine to me. Otherwise, squash.

2024-12-19 20:29 UTC, merged