Implementing automatic "safe display mode" for e-ink devices.
ankidroid/Anki-Android pull request #17646
Opened 2024-12-21 08:15 UTC by Scapesfear

## Purpose / Description
I am solving issue #17618 by implementing the `initializeSafeDisplayMode()` 

## Approach
My `initializeSafeDisplayMode()` method checks if the display is e-ink and also if the intial setting of safe display mode is not changed by user previously it turn on the safe display mode , I will implement detection of e-ink display in `hasEInkDisplay()` method under this PR only , i will make a small lookup nside the project only which will contain the manufacturers and models of the E-ink devices and from which lookup my `hasEInkDisplay()` method will detect if it is E-ink display.

## How Has This Been Tested?
For now `hasEInkDisplay()` method return true but i have tested the functionality of `initializeSafeDisplayMode()` method when a new device installs the app the safe display mode is set true(as `hasEInkDisplay()` method returns true) and if user changes that its preferences are saved.

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-12-21 08:17 UTC, Scapesfear commented
now in future commit i will implement `hasEInkDisplay()` method's complete logic

2024-12-21 09:14 UTC, david-allison commented
Please don't submit a PR until it's ready for review. I've marked this as a draft for now, please un-draft when completed

2024-12-21 13:24 UTC, Scapesfear commented
sorry for that, will keep this thing in mind for future.

2024-12-21 17:41 UTC, Scapesfear commented
I’ve added the hasEInkDisplay() method to detect E-Ink devices and integrated it with initializeSafeDisplayMode() to set preferences. Could you review the implementation and suggest improvements?

Also, since Android Studio lacks E-Ink emulation, how would you recommend testing this functionality?

2024-12-21 18:13 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            val jsonFileName = "eink_devices.json"
is there a real benefit to having this in a JSON file and loading it vs just having a map of manufacturers with an array of their modules in the code? I'm not sure I see a benefit

2024-12-21 18:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +    @OptIn(UnstableApi::class)
curious, what are the unstable APIs used here and below and why are they necessary vs a stable API ?

2024-12-22 03:26 UTC, xenonnn4w commented
| since Android Studio lacks E-Ink emulation, how would you recommend testing this functionality? 

You may try adding something like this 
`{
    "manufacturer": "Google",
    "models": ["sdk_gphone64_x86_64"]
  }`
  to your json file or the array. Also in models change the attribute `$deviceModel` value, here it was for Pixel 5 .

2024-12-22 04:15 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            val jsonFileName = "eink_devices.json"
Improved Code Readability: Externalizing data keeps the code focused on functionality, making it cleaner and easier to understand.

Ease of Maintenance: Updates to device data require changes only to the JSON file, avoiding code recompilation and reducing the risk of bugs.

Scalability: Supporting new devices is as simple as modifying the JSON file—no changes to the app logic are needed.

Future-Proof Design: While currently static, this setup can be easily adapted for dynamic updates (e.g., fetching updated device configurations from a server).

Separation of Concerns: Keeping data separate from logic aligns with best practices, making the app modular, testable, and extensible.

That said, if you prefer a hardcoded map, I can implement that instead.

2024-12-22 06:43 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +    @OptIn(UnstableApi::class)
I initially used @OptIn(UnstableApi::class) due to reliance on experimental APIs like android.system.Os and android.media3.common.util.Log for advanced system operations and logging. However, I've since replaced these unstable APIs with Timber, a stable and widely-used logging tool, ensuring better stability and compatibility while maintaining the required functionality.

2024-12-22 09:09 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +    @OptIn(UnstableApi::class)
i have finnaly fixed all the timber issues that were present in my code , please review

2024-12-22 09:12 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            val jsonFileName = "eink_devices.json"
as you can see my current json file which contains almost 90-95% e-ink devices is huge , add these many code lines in the code itself just for populating the map seems inefficient , but i can implement map if you want . please review

2024-12-22 09:21 UTC, Scapesfear commented
https://github.com/user-attachments/assets/7bd74677-1594-4b46-8517-ce3ecfbebcd1

2024-12-22 19:59 UTC, david-allison requested changes

2024-12-22 19:59 UTC, david-allison commented on AnkiDroid/src/main/assets/eink_devices.json
> +    "manufacturer": "Onyx Boox",
Where did you source this data from?

2024-12-22 19:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +        initializeTimber("SafeDisplayMode")
Eh? Why not initialize this after logging is setup?

It doesn't need to be done so early

2024-12-22 19:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            val jsonFileName = "eink_devices.json"
No need for a file. Hardcode it so we're doing less I/O on startup

2024-12-22 19:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            Timber.tag("SafeDisplayMode").d("Checking device: manufacturer=$deviceManufacturer, model=$deviceModel")
This is a non-idiomatic use of Timber, please fix to match our code style.

2024-12-22 19:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            }
This method feels like it should be ~1 line of code:

```kotlin
return knownEInkDevices.contains(DeviceInfo(Build.MANUFACTURER, Build.MODEL))
```

2024-12-22 21:08 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            val jsonFileName = "eink_devices.json"
the file isn't that big

"locality" for a feature is a value of it's own in my opinion - by which I mean "everything related to a feature in one spot"

2024-12-23 05:54 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            val jsonFileName = "eink_devices.json"
Okay i will get it done , i will make an map of eink_devices, but i want to confirm should i make the map in the hasEInkDisplay method itself or another method wich return the map to be used , please clarify

2024-12-23 06:26 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            }
okay , i can get i done , but this requires creating an inner class DeviceInfo and an companion object ( knownEInkDevices map ) is it allowed ?

2024-12-23 06:31 UTC, Scapesfear commented on AnkiDroid/src/main/assets/eink_devices.json
> +    "manufacturer": "Onyx Boox",
i did some research used these websites,
https://www.androidauthority.com/best-e-ink-tablet-3230616
https://www.androidpolice.com/best-e-ink-tablets
https://cincodias.elpais.com/smartlife/gadgets/2024-10-23/nuevos-boox-note-air4-c-palma-2-note-max-caracteristicas.html
https://www.androidcentral.com/best-e-ink-tablet

and in the end used Ai tools for completing it

2024-12-23 07:07 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            val jsonFileName = "eink_devices.json"
Separate class, it doesn't belong in `AnkiDroidApp`

2024-12-23 07:07 UTC, david-allison commented on AnkiDroid/src/main/assets/eink_devices.json
> +    "manufacturer": "Onyx Boox",
Are you sure that this is what the devices are reporting as `manufacturer`/`model`?

2024-12-23 08:27 UTC, Scapesfear commented on AnkiDroid/src/main/assets/eink_devices.json
> +    "manufacturer": "Onyx Boox",
sorry i can't confirm 100% about that because nowhere it is directly written what does Build.MODEL print for the devices , although there were some issue in my data i am fixing that .

2024-12-23 08:28 UTC, Scapesfear commented on AnkiDroid/src/main/assets/eink_devices.json
> +    "manufacturer": "Onyx Boox",
any guidance on how to collect the accurate data will be extremely helpful

2024-12-23 09:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            }
It's pseudocode, but it feels like a reasonable solution, is there a reason you're asking in partiuclar?

2024-12-23 09:43 UTC, Scapesfear commented on AnkiDroid/src/main/assets/eink_devices.json
> +    "manufacturer": "Onyx Boox",
hi , i was asking about keeping a naming convention for models in the map can i keep names such that the names only contains numbers and alphabets they too lowercase , no symbols like "-" or spaces , and then after getting the Build.Manufacturer and Build.Model , i can process them to remove any symbols and sapcing for better mathcing , please suggest ?

2024-12-23 09:49 UTC, david-allison commented on AnkiDroid/src/main/assets/eink_devices.json
> +    "manufacturer": "Onyx Boox",
No, find a list which you know is accurate, even if it's incomplete, rather than AI-generated slop. If you're not certain, it's best not to include it (and therefore, I believe we're starting from scratch).

My first example found from a quick search in the repo doesn't match

```
Manufacturer = ONYX
Model = NovaAir
```

You'll want to use an authoritative source. None of those blogs are usable

2024-12-23 09:54 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            val jsonFileName = "eink_devices.json"
I think that could be overkill , to make a seperate DeviceInfo class , making private map of knowin eink devices of key - manufacturer string and value as list of strin of models , is it fine ?

2024-12-27 18:37 UTC, david-allison requested changes
Thanks!

2024-12-27 18:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +    data class DeviceInfo(
Move all this logic into a separate object/class, it doesn't belong here

2024-12-27 18:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            Timber.w("Potential E-ink device: $currentDevice")
This needs to be sent to ACRA

2024-12-27 18:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +                            .contains(currentDevice.manufacturer)
Why is the lowercasing being done here + is it being done in a locale-invariant fashion? [https://en.wikipedia.org/wiki/Dotless_I]

Should be done on construction, or at the very least using a case-insensitive comparator

2024-12-27 18:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            }
No need to iterate the list twice

2024-12-27 18:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +        Timber.d("Checking device: $currentDevice")
```suggestion
        Timber.v("Checking device: $currentDevice")
```

2024-12-27 18:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            )
nit: probably define this as a property on `DeviceInfo`

2024-12-27 18:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            Timber.d("Not an E-ink device: $currentDevice")
```suggestion
            Timber.v("Not an E-ink device: $currentDevice")
```

2024-12-27 18:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            showThemedToast(this, "E-ink device detected", false)
We shouldn't show this to the user

2024-12-27 18:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            Timber.d("E-Ink display detected and safeDisplay is not set. Setting it now.")
Make the message less verbose

2024-12-27 18:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +        Timber.d("isSafeDisplaySet: $isSafeDisplaySet")
```suggestion
```

2024-12-27 18:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            Timber.d("No changes made. Either safeDisplay is already set or no confirmed E-Ink display detected.")
Not worth logging

2024-12-27 18:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +     * Returns true if a match is found, false otherwise.
Use `@return` and wrap `true` in backticks

```suggestion
     * Returns true if a match is found, false otherwise.
```

2024-12-27 18:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +     * Checks if the device has an E-Ink display by matching its manufacturer and model.
No need to explain the implementation in the docstring, this should be a method comment

2024-12-27 18:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            DeviceInfo("xiaomi", "xiaomi_reader"),
This doesn't distinguish between "known good" and "maybe"

This doesn't include the sample "known good" device from the original issue (Viwoods)

This doesn't include sources for the list

This has `onyx` and `Onyx`, why?

2024-12-27 18:37 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +        initializeSafeDisplayMode()
This shouldn't be done before crash handling etc...

2024-12-29 05:09 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            DeviceInfo("xiaomi", "xiaomi_reader"),
onyx and Onyx didn't really made difference according to my code , as i was just comparing the invariants , but i will change that , can i store everything in lowercase ?

2024-12-29 12:42 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            DeviceInfo("xiaomi", "xiaomi_reader"),
Store the known good values as they are on the device. Perform a case-insensitive, locale invariant comparison in the code

2024-12-29 17:13 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            DeviceInfo("xiaomi", "xiaomi_reader"),
In the code files, the manufacturer was listed as `onyx`. However, the CSV file didn’t specify a manufacturer, only the models . Since I saw `NovaAir` in the CSV and you provided an example with `Onyx`  I assumed the manufacturer to be 'Onyx' for any unclear entries. Let me know if any adjustments are needed.

2024-12-29 17:34 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            DeviceInfo("xiaomi", "xiaomi_reader"),
To simplify things:

* We have a list of known good data.
* We have a few lists of 'probably good data'
* We have a few manufacturers who probably make e-ink devices

Our goal is to populate the list of known good data. 

We do this via a silent troubleshooting report from users who have opted in.

====

* If current data is a known good, it's an e-ink
* If current data matches a 'probably', assume it's an e-ink and report so we have accurate data
* If current data matches manufacturer, report and do nothing

2025-01-02 08:51 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            Timber.w("Potential E-ink device: $currentDevice")
will it be done like this ?

if (isPartialMatch) {
            Timber.w("Potential E-ink device: $currentDevice")
            ACRA.errorReporter.handleSilentException(Exception("Potential E-ink device: $currentDevice"))
        }
        
is it correct way of doing it

2025-01-02 08:54 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +    data class DeviceInfo(
Done , i have moved all the logic of detecting EInk Device in another new class EInkDeviceIdentifier class which detect if device is EInk or not , only the IntializeSafeDisplay method will remain in the AnkiDroidApp.kt

2025-01-02 08:55 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +        Timber.d("Checking device: $currentDevice")
Done

2025-01-03 23:41 UTC, david-allison requested changes

2025-01-03 23:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/EInkDeviceIdentifier.kt
> +    data class DeviceInfo(
Data class doesn't feel useful here: we're not using exact comparators

2025-01-03 23:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/EInkDeviceIdentifier.kt
> +        Timber.v("Checking device: $currentDevice")
Timber prefers `%s`

2025-01-03 23:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/EInkDeviceIdentifier.kt
> +        if (isPartialMatch || eInkManufacturersList.contains(currentDevice.manufacturer)) {
Split out obtaining the output, and performing actions based on the outputs

2025-01-03 23:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/EInkDeviceIdentifier.kt
>              get() = originalModel.lowercase(Locale.ROOT).trim()
These shouldn't recompute the value each time if the function is pure

2025-01-03 23:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/EInkDeviceIdentifier.kt
>              // Check if the device is a partial match. Partial matches are detected using substring matching.
? partial matches are defined as a match on either manufacturer [or casing issues]

2025-01-03 23:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/EInkDeviceIdentifier.kt
> +            ACRA.errorReporter.handleSilentException(Exception("Potential E-ink device: $currentDevice"))
use 

``` 
               CrashReportService.sendExceptionReport(
                    onlyIfSilent = true
                )
```

2025-01-03 23:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/EInkDeviceIdentifier.kt
> +        for (device in knownEInkDevices) {
The code + loop feels too complicated:

Split out getting the match type, and executing based on the match

Then simplify the code querying the match type

2025-01-03 23:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +        val deviceIdentifier = EInkDeviceIdentifier()
This likely doesn't need to be a class if you're calling a method on it and it has no state

2025-01-03 23:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +        initializeSafeDisplayMode()
performance: this should be done in the background if at all possible so it doesn't block startup

2025-01-03 23:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +            preferences.edit().putBoolean("safeDisplay", true).apply()
there is an `.edit { }` extension method which implicitly calls `apply`

2025-01-03 23:41 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/EInkDeviceIdentifier.kt
> +            ACRA.errorReporter.handleSilentException(Exception("Potential E-ink device: $currentDevice"))
I added better diagnostics in: https://github.com/ankidroid/Anki-Android/pull/17686

We should extract this and also use it here, so we get a useful fingerprint

2025-01-04 05:55 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/EInkDeviceIdentifier.kt
>              // Check if the device is a partial match. Partial matches are detected using substring matching.
I am reporting potential e-ink if there is a manufacturer match or partial match , the partial match algorithm is that it checks if the current device's manufaturer and model is substring of any of the pair of manufaturer and model in the knowEInkDevices set or vice-versa as in the below source 
you can see that there is not a great certainity of perfect match but they are checking a substring match  https://github.com/koreader/android-luajit-launcher/blob/6bba3f4bb4da8073d0f4ea4f270828c8603aa54d/app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt#L260

2025-01-04 06:01 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +        initializeSafeDisplayMode()
I'm unsure how to handle this perfectly, but the safe display mode must be initialized at app startup if the device is e-ink. This won't block startup since it only checks for e-ink and initializes safe mode if needed, without interfering with other processes.

2025-01-04 06:03 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
> +        val deviceIdentifier = EInkDeviceIdentifier()
I’m having difficulty understanding the point you’re trying to convey. Could you clarify or elaborate further?

2025-01-04 06:05 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/EInkDeviceIdentifier.kt
>              get() = originalModel.lowercase(Locale.ROOT).trim()
yeah you are right , i will fix that

2025-01-04 06:05 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/EInkDeviceIdentifier.kt
> +        Timber.v("Checking device: $currentDevice")
i will fix that

2025-01-04 06:13 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/EInkDeviceIdentifier.kt
> +        for (device in knownEInkDevices) {
I understand the suggestion of splitting out the match type, but this would require iterating through the list twice, which introduces a tradeoff between clarity and efficiency. The exact match can be checked using ==, while the partial match requires a substring comparison. These two comparisons are fundamentally different and cannot be handled in a single pass without mixing their logic. Initially, I separated the checks, but you mentioned not to iterate the list twice, which is why I combined the logic.

2025-01-04 06:33 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/EInkDeviceIdentifier.kt
> +    data class DeviceInfo(
I really think we should keep DeviceInfo as a data class. It’s all about storing data in a clean and simple way, which makes sense since it's just holding the device's information. Mixing it into EInkDeviceIdentifier feels like it’s overcomplicating things and doesn’t really follow the separation of concerns principle.

Also, looking ahead, I see EInkDeviceIdentifier evolving with more features as e-ink devices continue to grow in popularity. These devices are more energy-efficient, and as research progresses, we’ll likely see more of them in the future. Keeping things separate now will help us easily scale and add more functionality later on.

2025-01-04 06:34 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/EInkDeviceIdentifier.kt
> +        if (isPartialMatch || eInkManufacturersList.contains(currentDevice.manufacturer)) {
both the manufaturer match and partial match results in repoting the device only so why should i seperate them

2025-01-04 06:34 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/EInkDeviceIdentifier.kt
> +            ACRA.errorReporter.handleSilentException(Exception("Potential E-ink device: $currentDevice"))
thanks

2025-01-04 06:43 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/EInkDeviceIdentifier.kt
>              // Check if the device is a partial match. Partial matches are detected using substring matching.
few more sources doing the same 

https://github.com/plotn/coolreader/blob/e5baf0607e678468aa045053ba5f092164aa1dd7/android/src/org/coolreader/crengine/DeviceInfo.java#L201

https://github.com/plotn/coolreader/blob/e5baf0607e678468aa045053ba5f092164aa1dd7/android/src/org/coolreader/crengine/DeviceInfo.java#L216

2025-01-04 07:10 UTC, Scapesfear commented on AnkiDroid/src/main/java/com/ichi2/anki/EInkDeviceIdentifier.kt
> +            ACRA.errorReporter.handleSilentException(Exception("Potential E-ink device: $currentDevice"))
CrashReportService.sendExceptionReport(
                Exception("Potential E-ink device: ${Build.MANUFACTURER} | ${Build.BRAND} | ${Build.DEVICE} | ${Build.PRODUCT} | ${Build.MODEL} | ${Build.HARDWARE}"),
                origin = "EInkDeviceIdentifier",
                additionalInfo = null,
                onlyIfSilent = true
            )
            
            like this right ?

2025-01-04 13:59 UTC, david-allison commented
This feature is not expected to add much value to the app based on proportion of e-ink users as a percentage of the total userbase and we have to be very careful with our time which is always our biggest limitation. 

This PR doesn't provide enough value to justify the time spent already, much less any future time. 

With apologies, I'm closing this as I'm not considering spending any further time on it

2025-01-04 13:59 UTC, closed without merging

2025-01-04 15:37 UTC, Scapesfear commented
> This feature is not expected to add much value to the app based on proportion of e-ink users as a percentage of the total userbase and we have to be very careful with our time which is always our biggest limitation.
> 
> This PR doesn't provide enough value to justify the time spent already, much less any future time.
> 
> With apologies, I'm closing this as I'm not considering spending any further time on it

I’ve implemented nearly all the changes you asked for, but I got frustrated with the lint issues since I wasn’t familiar with them. I’ve invested a lot of time into this.

If possible, could you please reconsider reopening the PR?

2025-01-04 19:23 UTC, mikehardy commented
> I’ve implemented nearly all the changes you asked for,

There is no reasonable expectation that future costs to review + get this merged will be sufficient to justify further activity, based on past activity.

Thus this statement is accurate as a standalone:

> This feature is not expected to add much value to the app based on proportion of e-ink users as a percentage of the total userbase and we have to be very careful with our time which is always our biggest limitation

This statement is a logical fallacy when allocating time + resources, and though it feels naturally and is understandable after any investment, it should not be used as a justification:

>  I’ve invested a lot of time into this

https://en.wikipedia.org/wiki/Sunk_cost