[Cleanup]: Resolve Android Studio Warnings (#13282)
ankidroid/Anki-Android pull request #17648
Opened 2024-12-22 15:10 UTC by Siddheshjondhale

## Purpose / Description
Reducing Android Studio warnings by cleaning up unused code and fixing initialization.

## Fixes
* Contributes towards #13282 ``[Cleanup]: Fix Android Studio Warnings``

## Approach

- Made the unmountReceiver property private in `AppCompatPreferenceActivity.kt`.
- Removed the unused import **(import androidx.activity.addCallback)** in `CardTemplateBrowserAppearanceEditor.kt`.
- Removed the unused **property editedModelFileName** in `CardTemplateNotetype.kt`.
- Fixed the unresolved reference to **BuildConfig** in `CardTemplateNotetype.kt`.
- Made the **legacyAnkiDroidDirectory property** private in `CollectionHelper.kt`.
- Removed the unused **property fieldsAsBundleForPreview** in `NoteEditor.kt`.
- Fixed the initialization of `activity` in `RtlCompliantActionProvider.kt` **by assigning it immediately during declaration**, **rather than inside the init block**. This ensures proper initialization and avoids potential issues.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have performed a self-review of your own code

2024-12-24 13:50 UTC, lukstbit requested changes
Thanks, one issue to fix and then we can merge this.

2024-12-24 13:50 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt
> +import com.arcao.slf4j.timber.BuildConfig
Why was this added?

2024-12-24 14:58 UTC, Siddheshjondhale commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt
> +import com.arcao.slf4j.timber.BuildConfig
fixed and squash merged

2024-12-24 15:12 UTC, lukstbit approved these changes
Thanks!

2024-12-25 19:50 UTC, BrayanDSO approved these changes

2024-12-25 20:02 UTC, merged