refactor: extract Binding equality to original classes
ankidroid/Anki-Android pull request #17668
Opened 2024-12-26 10:08 UTC by BrayanDSO

so it's possible to compare bindings without a MappableBinding

## How Has This Been Tested?

I'm trusting the unit tests. Went around and tested some keybinds and gestures and they still work.

I couldn't test some keybinds like `*` (mark default) and `!` (suspend default) even before these changes. They are only recognized as `Shift+1` and `Shift+8` here

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-12-26 10:10 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MappableBinding.kt
> -        // don't include the modifierKeys or mSide
I haven't included the modifier keys because this should be a non functional change.

But why the modifier keys are checked in `equals` but aren't added in the hash code? @david-allison

2024-12-26 15:04 UTC, Arthur-Milchior reviewed
Nice improvement. But I suspect it could be even simpler

2024-12-26 15:04 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/Binding.kt
> +        override fun equals(other: Any?): Boolean = other is GestureInput && gesture == other.gesture
I’m sorry but I don’t understand why you implement them.
According to the [documentation](https://kotlinlang.org/docs/data-classes.html#properties-declared-in-the-class-body) the equals and hashCode are directly implemented using the values of the primary constructor for data class.
So you are recreating functions that are generated by default in a similar way.
Am I missing something?

2024-12-26 16:59 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MappableBinding.kt
> -        // don't include the modifierKeys or mSide
Fallout from combining 'unicode' and 'keycode' lookups into the same HashMap

----

If we have "@" mapped, we convert the user input to a class and look it up in a hashmap to see if there is a command attached.

From memory: We lookup both based on keycode, and the system-defined unicode symbol from the KeyEvent

If using unicode:

* We do NOT want to match: [Ctrl || Alt] + Shift + 2
* We want to match `Shift + 2`
* We want to match a keyboard which has a dedicated `@` key: `!Shift + @`

----

This is implemented by overriding `shiftMatches` to return `true`, meaning multiple input values would match.

This is easily handled by overriding `shiftMatches`. Harder to handle with `getHashCode`, so trade off a theoretical bucket collision with ease of implementation.

2024-12-26 21:10 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/Binding.kt
> +        override fun equals(other: Any?): Boolean = other is GestureInput && gesture == other.gesture
> equals and hashCode are directly implemented using the values of the primary constructor for data class.

Forgot about that. Thanks a lot!

2024-12-26 21:26 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MappableBinding.kt
> -        // don't include the modifierKeys or mSide
> We want to match Shift + 2

At least in my ABNT2 keyboards, this doesn't happen. `@`, `!` aren't recognized at all

2024-12-26 21:35 UTC, BrayanDSO commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/Binding.kt
> +        override fun equals(other: Any?): Boolean = other is GestureInput && gesture == other.gesture
Had to keep the `hashCode` method for the KeyBindings because of https://github.com/ankidroid/Anki-Android/pull/17668#discussion_r1898020433

2024-12-29 12:28 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MappableBinding.kt
> -        // don't include the modifierKeys or mSide
`KeyEvent.getUnicodeChar` may return `@`: https://developer.android.com/reference/android/view/KeyEvent#getUnicodeChar(int)

2025-01-04 10:26 UTC, david-allison requested changes

2025-01-04 10:26 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/Binding.kt
> +        override fun hashCode(): Int = Objects.hash(ctrl, alt, shift, shiftMatches(true), shiftMatches(false))
object 1:

* shiftMatches(true) => true
* shiftMatches(false) => true

object 2:

* shiftMatches(true) => true
* shiftMatches(false) => false

The hashcodes would not be equal, but `this.shiftMatches(true) == keys.shiftMatches(true)` would be true, implying equality

2025-02-08 17:37 UTC, david-allison approved these changes

2025-02-10 13:57 UTC, mikehardy approved these changes
LGTM, thanks

2025-02-10 14:12 UTC, merged