Unit Tests for initializeApkgExportUi and initializeNotesExportUi
ankidroid/Anki-Android pull request #17680
Opened 2024-12-28 20:22 UTC by Haz3-jolt

## Purpose / Description
Added unit test to check the visibility and default checked status for the Apkg and Collection exports

## Fixes
* Added tests for initializeApkgExportUi() and initializeCollectionExportUi() both tagged with @NeedsTest("Checkbox is only available on two selections "), and @NeedsTest("Checkbox defaults to false").

## Approach
* Making showExtrasOptionsFor and ExportConfiguration public with @VisibleForTesting Tag.
* Launching a fragment with the configs for each

## How Has This Been Tested?
Ran the unit tests multiple times to avoid flaky tests

## Learning (optional, can help others)
* How to create fragment tests with AnkiFragmentScenario which extends on AndroidX testing lib.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-12-28 20:29 UTC, Haz3-jolt commented
@david-allison I think for the @NeedsTest("Checkbox value is provided to the correct export functions (true/false)") it should be testing exportApkgPackage and exportCollectionPackage from BackendExporting.kt. Is it fine if i do it seperately in a different PR?

2024-12-28 20:35 UTC, Haz3-jolt commented
Also can I do a refactor commit for:

2024-12-28 20:38 UTC, Haz3-jolt commented
Possible flaky Lint, can someone retry?

2024-12-29 09:35 UTC, lukstbit requested changes
>  I think for the @NeedsTest("Checkbox value is provided to the correct export functions (true/false)") it should be testing exportApkgPackage and exportCollectionPackage from BackendExporting.kt. Is it fine if i do it seperately in a different PR?

The test is about checking if the ui makes the proper calls to the backend. That would require mocking and the current code isn't made for this. I would leave it aside for now.

The refactoring is out of scope for this PR and can be done when the class is actually worked on.

2024-12-29 09:35 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +    fun showExtrasOptionsFor(
These tests shouldn't require that you make specific implementation related methods public. Instead you should be using Espresso to test the proper ui states/values.

2024-12-29 09:39 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +    fun showExtrasOptionsFor(
Ok will make the changes

2024-12-29 10:30 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +    fun showExtrasOptionsFor(
@lukstbit when I try using Espresso, the views are not initialized properly. Mainly because the UI elements are not yet loaded.

2024-12-29 10:30 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +    fun showExtrasOptionsFor(
```
Index: AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt
new file mode 100644
--- /dev/null	(date 1735467816906)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt	(date 1735467816906)
@@ -0,0 +1,64 @@
+/*
+* This program is free software; you can redistribute it and/or modify it under
+* the terms of the GNU General Public License as published by the Free Software
+* Foundation; either version 3 of the License, or (at your option) any later
+* version.
+*
+* This program is distributed in the hope that it will be useful, but WITHOUT ANY
+* WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
+* PARTICULAR PURPOSE. See the GNU General Public License for more details.
+*
+* You should have received a copy of the GNU General Public License along with
+* this program. If not, see <http://www.gnu.org/licenses/>.
+*/
+package com.ichi2.anki.export
+
+import android.widget.Spinner
+import androidx.test.ext.junit.runners.AndroidJUnit4
+import androidx.test.espresso.Espresso.onView
+import androidx.test.espresso.action.ViewActions.click
+import androidx.test.espresso.assertion.ViewAssertions.matches
+import androidx.test.espresso.matcher.ViewMatchers.*
+import com.ichi2.anki.R
+import com.ichi2.testutils.AnkiFragmentScenario
+import org.junit.Test
+import org.junit.runner.RunWith
+
+@RunWith(AndroidJUnit4::class)
+class ExportDialogFragmentTest {
+
+    @Test
+    fun colkpgLegacyExportCheckbox() {
+        AnkiFragmentScenario.launchInContainer(ExportDialogFragment::class.java).onFragment { fragment ->
+            fragment.view?.findViewById<Spinner>(R.id.export_type_selector)?.setSelection(0)
+        }
+        onView(withId(R.id.export_type_selector)).perform(click())
+        onView(withText("Anki Collection Package (.colpkg)")).perform(click())
+        onView(withId(R.id.export_legacy_checkbox_collection))
+            .check(matches(isDisplayed()))
+            .check(matches(isNotChecked()))
+    }
+
+    @Test
+    fun apkgLegacyExportCheckbox() {
+        AnkiFragmentScenario.launchInContainer(ExportDialogFragment::class.java).onFragment { fragment ->
+            fragment.view?.findViewById<Spinner>(R.id.export_type_selector)?.setSelection(1)
+        }
+        onView(withId(R.id.export_type_selector)).perform(click())
+        onView(withText("Anki Deck Package (.apkg)")).perform(click())
+        onView(withId(R.id.export_legacy_checkbox_apkg))
+            .check(matches(isDisplayed()))
+            .check(matches(isNotChecked()))
+    }
+
+    @Test
+    fun defaultLegacyExportCheckbox() {
+        AnkiFragmentScenario.launchInContainer(ExportDialogFragment::class.java).onFragment { fragment ->
+            fragment.view?.findViewById<Spinner>(R.id.export_type_selector)?.setSelection(-1)
+        }
+        onView(withId(R.id.export_legacy_checkbox_apkg))
+            .check(matches(withEffectiveVisibility(Visibility.GONE)))
+        onView(withId(R.id.export_legacy_checkbox_collection))
+            .check(matches(withEffectiveVisibility(Visibility.GONE)))
+    }
+}
\ No newline at end of file
```

2024-12-29 10:31 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +    fun showExtrasOptionsFor(
This is a temporary patch, I'm not very familiar with Espresso, so learning along the way

2024-12-29 12:19 UTC, lukstbit commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +    fun showExtrasOptionsFor(
You are in a dialog so tell Espresso where to look for those views with .inRoot(isDialog())

2024-12-29 20:41 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +    fun showExtrasOptionsFor(
Got it, thanks for the help

2024-12-30 10:26 UTC, Haz3-jolt commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> +    fun showExtrasOptionsFor(
Made the changes, took a while but now the test uses Espresso, thanks for the help!

2024-12-30 18:18 UTC, lukstbit requested changes

2024-12-30 18:18 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt
> +            fragment.view?.let {
Why was _fragment.view?._ added, the test should work without this.

2024-12-30 18:27 UTC, Haz3-jolt commented on AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt
> +            fragment.view?.let {
Oops leftover from when i used a Espresso Test from HelpDialogTest.kt as a reference.
Will remove!

2024-12-30 18:36 UTC, Haz3-jolt commented on AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt
> +            fragment.view?.let {
```
Subject: [PATCH] Unit Tests for initializeApkgExportUi and initializeNotesExportUi
---
Index: AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt	(revision ff8e1e9327f860a28449e6557d840f690c26532f)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt	(date 1735583790601)
@@ -32,38 +32,29 @@
 class ExportDialogFragmentTest {
     @Test
     fun colLegacyExportCheckbox() {
-        AnkiFragmentScenario.launchInContainer(ExportDialogFragment::class.java).onFragment { fragment ->
-            fragment.view?.let {
-                onView(withId(R.id.export_type_selector)).perform(click())
-                onView(withText("Anki Collection Package (.colpkg)")).perform(click())
-                onView(withId(R.id.export_legacy_checkbox_collection))
-                    .inRoot(isDialog())
-                    .check(matches(isDisplayed()))
-            }
-        }
+        AnkiFragmentScenario.launchInContainer(ExportDialogFragment::class.java)
+        onView(withId(R.id.export_type_selector)).perform(click())
+        onView(withText("Anki Collection Package (.colpkg)")).perform(click())
+        onView(withId(R.id.export_legacy_checkbox_collection))
+            .inRoot(isDialog())
+            .check(matches(isDisplayed()))
     }
 
     @Test
     fun apkgLegacyExportCheckbox() {
-        AnkiFragmentScenario.launchInContainer(ExportDialogFragment::class.java).onFragment { fragment ->
-            fragment.view?.let {
-                onView(withId(R.id.export_type_selector)).perform(click())
-                onView(withText("Anki Deck Package (.apkg)")).perform(click())
-                onView(withId(R.id.export_legacy_checkbox_collection))
-                    .inRoot(isDialog())
-                    .check(matches(isDisplayed()))
-            }
-        }
+        AnkiFragmentScenario.launchInContainer(ExportDialogFragment::class.java)
+        onView(withId(R.id.export_type_selector)).perform(click())
+        onView(withText("Anki Deck Package (.apkg)")).perform(click())
+        onView(withId(R.id.export_legacy_checkbox_collection))
+            .inRoot(isDialog())
+            .check(matches(isDisplayed()))
     }
 
     @Test
     fun defaultLegacyExportCheckbox() {
-        AnkiFragmentScenario.launchInContainer(ExportDialogFragment::class.java).onFragment { fragment ->
-            fragment.view?.let {
-                onView(withId(R.id.export_legacy_checkbox_collection))
-                    .inRoot(isDialog())
-                    .check(matches(withEffectiveVisibility(Visibility.GONE)))
-            }
-        }
+        AnkiFragmentScenario.launchInContainer(ExportDialogFragment::class.java)
+        onView(withId(R.id.export_legacy_checkbox_collection))
+            .inRoot(isDialog())
+            .check(matches(withEffectiveVisibility(Visibility.GONE)))
     }
-}
+}
\ No newline at end of file

```

2024-12-30 18:37 UTC, Haz3-jolt commented on AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt
> +            fragment.view?.let {
With this as a patch the test keeps failing, perhaps the views aren't initialized?

2024-12-30 18:53 UTC, lukstbit commented on AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt
> +            fragment.view?.let {
Again, the test should pass without the query for the fragment's view. In fact we wouldn't really know if the test checks something, if the fragment's view is null the checks are silently ignored.

You need to figure out why is the test failing. Also, you are in a dialog so all espresso calls should be scoped to the dialog, you're doing this, for some reason, just for the last line?!?!.

2024-12-30 20:01 UTC, Haz3-jolt commented on AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt
> +            fragment.view?.let {
```
Subject: [PATCH] Unit Tests for initializeApkgExportUi and initializeNotesExportUi
---
Index: AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt	(revision ff8e1e9327f860a28449e6557d840f690c26532f)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt	(date 1735588795810)
@@ -13,18 +13,20 @@
  */
 package com.ichi2.anki.export
 
+import androidx.test.espresso.Espresso.onData
 import androidx.test.espresso.Espresso.onView
 import androidx.test.espresso.action.ViewActions.click
 import androidx.test.espresso.assertion.ViewAssertions.matches
 import androidx.test.espresso.matcher.RootMatchers.isDialog
+import androidx.test.espresso.matcher.RootMatchers.isPlatformPopup
 import androidx.test.espresso.matcher.ViewMatchers.Visibility
 import androidx.test.espresso.matcher.ViewMatchers.isDisplayed
 import androidx.test.espresso.matcher.ViewMatchers.withEffectiveVisibility
 import androidx.test.espresso.matcher.ViewMatchers.withId
-import androidx.test.espresso.matcher.ViewMatchers.withText
 import androidx.test.ext.junit.runners.AndroidJUnit4
 import com.ichi2.anki.R
 import com.ichi2.testutils.AnkiFragmentScenario
+import org.hamcrest.CoreMatchers.anything
 import org.junit.Test
 import org.junit.runner.RunWith
 
@@ -32,38 +34,35 @@
 class ExportDialogFragmentTest {
     @Test
     fun colLegacyExportCheckbox() {
-        AnkiFragmentScenario.launchInContainer(ExportDialogFragment::class.java).onFragment { fragment ->
-            fragment.view?.let {
-                onView(withId(R.id.export_type_selector)).perform(click())
-                onView(withText("Anki Collection Package (.colpkg)")).perform(click())
-                onView(withId(R.id.export_legacy_checkbox_collection))
-                    .inRoot(isDialog())
-                    .check(matches(isDisplayed()))
-            }
+        AnkiFragmentScenario.launchInContainer(ExportDialogFragment::class.java).onFragment {
+            onView(withId(R.id.export_type_selector)).inRoot(isPlatformPopup()).perform(click())
+            onData(anything()).atPosition(0).perform(click())
+            onView(withId(R.id.export_legacy_checkbox_collection))
+                .inRoot(isDialog())
+                .check(matches(isDisplayed()))
         }
     }
 
     @Test
     fun apkgLegacyExportCheckbox() {
-        AnkiFragmentScenario.launchInContainer(ExportDialogFragment::class.java).onFragment { fragment ->
-            fragment.view?.let {
-                onView(withId(R.id.export_type_selector)).perform(click())
-                onView(withText("Anki Deck Package (.apkg)")).perform(click())
-                onView(withId(R.id.export_legacy_checkbox_collection))
-                    .inRoot(isDialog())
-                    .check(matches(isDisplayed()))
-            }
+        AnkiFragmentScenario.launchInContainer(ExportDialogFragment::class.java).onFragment {
+            onView(withId(R.id.export_type_selector)).inRoot(isPlatformPopup()).perform(click())
+            onData(anything()).atPosition(1).perform(click())
+            onView(withId(R.id.export_legacy_checkbox_apkg))
+                .inRoot(isDialog())
+                .check(matches(isDisplayed()))
         }
     }
 
     @Test
     fun defaultLegacyExportCheckbox() {
-        AnkiFragmentScenario.launchInContainer(ExportDialogFragment::class.java).onFragment { fragment ->
-            fragment.view?.let {
-                onView(withId(R.id.export_legacy_checkbox_collection))
-                    .inRoot(isDialog())
-                    .check(matches(withEffectiveVisibility(Visibility.GONE)))
-            }
+        AnkiFragmentScenario.launchInContainer(ExportDialogFragment::class.java).onFragment {
+            onView(withId(R.id.export_legacy_checkbox_collection))
+                .inRoot(isDialog())
+                .check(matches(withEffectiveVisibility(Visibility.GONE)))
+            onView(withId(R.id.export_legacy_checkbox_apkg)).
+                inRoot(isDialog())
+                .check(matches(withEffectiveVisibility(Visibility.GONE)))
         }
     }
 }
```

2024-12-30 20:02 UTC, Haz3-jolt commented on AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt
> +            fragment.view?.let {
with this patch, scoped all to inRoot. since spinner is a platfrompopup, i used it instead of isDialog(). 

But i keep getting the errors:

<html>Matcher 'is dialog' did not match any of the following roots: [Root{application-window-token=android.view.ViewRootImpl$W@6073e236, window-token=android.view.ViewRootImpl$W@6073e236, has-window-focus=true, layout-params-type=1, layout-params-string={(0,0)(fillxfill) ty=BASE_APPLICATION wanim=0x10302fe<br/>fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH DRAWS_SYSTEM_BAR_BACKGROUNDS<br/>pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED<br/>bhv=DEFAULT<br/>fitSides=}, decor-view-string=DecorView{id=-1, visibility=VISIBLE, width=320, height=470, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) ty=BASE_APPLICATION wanim=0x10302fe<br/>fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH DRAWS_SYSTEM_BAR_BACKGROUNDS<br/>pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED<br/>bhv=DEFAULT<br/>fitSides=}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}}]

and

<html>Matcher 'with decor view of type PopupWindow$PopupDecorView' did not match any of the following roots: [Root{application-window-token=android.view.ViewRootImpl$W@11641cae, window-token=android.view.ViewRootImpl$W@11641cae, has-window-focus=true, layout-params-type=1, layout-params-string={(0,0)(fillxfill) ty=BASE_APPLICATION wanim=0x10302fe<br/>fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH DRAWS_SYSTEM_BAR_BACKGROUNDS<br/>pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED<br/>bhv=DEFAULT<br/>fitSides=}, decor-view-string=DecorView{id=-1, visibility=VISIBLE, width=320, height=470, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) ty=BASE_APPLICATION wanim=0x10302fe<br/>fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH DRAWS_SYSTEM_BAR_BACKGROUNDS<br/>pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED<br/>bhv=DEFAULT<br/>fitSides=}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}}]

2024-12-30 20:05 UTC, Haz3-jolt commented on AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt
> +            fragment.view?.let {
Have tried different things, but these issues are persistenet. Is it wrong to check with withEffectiveVisibility().
and for the spinner I have no idea where I am going wrong.

2025-01-01 14:17 UTC, Haz3-jolt commented on AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt
> +            fragment.view?.let {
@david-allison any idea why the roots are not matching? Are they not in scope or something?

2025-01-03 09:22 UTC, lukstbit commented
@Haz3-jolt I've added the required code as it also required an extra fix.

2025-01-03 09:22 UTC, lukstbit approved these changes

2025-01-03 09:24 UTC, Haz3-jolt commented
@lukstbit sorry I couldn't be of much help, pretty new to espresso. Just curious about a few things though, why use launch instead of launchFragment?

2025-01-03 09:26 UTC, Haz3-jolt commented
> @Haz3-jolt I've added the needed code as it also required an extra fix.

Yep, just saw. Didn't know about adapterview was still trying with a bunch of other stuff I saw from stackoverflow :| .
Thanks a lot for your help!

2025-01-03 09:55 UTC, lukstbit commented
> why use launch instead of launchFragment?

It was the first method that came in my mind. The two are basically the same, with _launchFragment_ being nicer to call. I've modified the code to use it.

2025-01-03 15:45 UTC, david-allison approved these changes
Awesome stuff, sorry I missed the ping

2025-01-03 15:57 UTC, merged