NF: Use type Id
ankidroid/Anki-Android pull request #17688
Opened 2024-12-29 19:33 UTC by Arthur-Milchior

A recent review made me realize plenty of `id: Long` should be more specific.

Exceptions are in the AddContentApi as it can't depends on the type definition of the code.

2024-12-29 20:45 UTC, david-allison reviewed
Great stuff here!

One request, LGTM in general, thanks!

2024-12-29 20:45 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
> +    ) = if (uri.pathSegments[1] == FlashCardsContract.Model.CURRENT_MODEL_ID) {
This should be listed explicitly as returning a `NoteTypeId`

2025-01-01 21:44 UTC, david-allison requested changes

2025-01-01 21:44 UTC, david-allison commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
> +            mid: NoteTypeId,
Ntid?

2025-01-01 21:44 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
> +    var id: NoteId
Is this not a note type id?

2025-01-01 22:25 UTC, Arthur-Milchior commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
> +            mid: NoteTypeId,
I assume you mean that I should have changed the variable name too.
Done.
Admittedly, I was only working on the type there, not replacing m/model

2025-01-01 22:25 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
> +    var id: NoteId
Oops

2025-01-01 22:39 UTC, david-allison approved these changes

2025-01-02 10:24 UTC, lukstbit approved these changes

2025-01-02 10:36 UTC, merged