Fixes #Issue-17520   Ensures testlib is built
ankidroid/Anki-Android pull request #17682
Opened 2024-12-29 07:29 UTC by KushagraPatni

## Purpose / Description
To ensure that GitHub Actions runs ./gradlew :testlib:assemblePlayDebugAndroidTest at some point to ensure that testlib compiles

## Fixes
* Fixes #17520 

## Approach
By adding a dependency on this task from AnkiDroid's androidTest in build.gradle

## How Has This Been Tested?

By building it locally on my PC.

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-12-29 12:02 UTC, david-allison requested changes

2024-12-29 12:02 UTC, david-allison commented on AnkiDroid/build.gradle
> +    dependsOn(":testlib:assemblePlayDebugAndroidTest")
This doesn't look correct. `PlayDebug` is a specific variant

2024-12-30 10:24 UTC, KushagraPatni commented on AnkiDroid/build.gradle
> +    dependsOn(":testlib:assemblePlayDebugAndroidTest")
Okay then how about I make it compatible to all the build variants?
If you have any other suggestions please suggest otherwise also.

2024-12-30 13:01 UTC, david-allison commented on AnkiDroid/build.gradle
> +    dependsOn(":testlib:assemblePlayDebugAndroidTest")
Gradle isn't my area of expertise, sadly. I'll leave recommendations to another maintainer

2024-12-30 20:47 UTC, mikehardy commented
This stuff is a bit more subtle than it seems. If you're not looking to become a gradle expert it's not terribly interesting either.

Worse, it's kind of hard to explain as I had to figure it out myself by testing it, and after getting it working (with multiple failures before I got it working...) then...it was done.

So I just pushed a commit that does it.

Here's my test showing it works:

- clean (using a gradle command)
- verify there are no built artifacts in testlib area (with an `ls -la` of the area)
- run the same task that our CI runs to warm gradle, specifically `packagePlayReleaseAndroidTest`, with the TEST_RELEASE_BUILD set to true as it is in CI (though it would work even if that was unset)
- verify that there *are* built artifacts in testlib

```

mike@isabela:~/work/ankidroid/Anki-Android (KushagraPatni/main *) % ./gradlew clean  --console plain --rerun-tasks
> Task :lint-rules:clean UP-TO-DATE
> Task :common:clean
> Task :api:clean
> Task :testlib:clean
> Task :AnkiDroid:clean

BUILD SUCCESSFUL in 3s
5 actionable tasks: 4 executed, 1 up-to-date
mike@isabela:~/work/ankidroid/Anki-Android (KushagraPatni/main *) % ls -alt testlib/build/outputs/a*
ls: testlib/build/outputs/a*: No such file or directory
mike@isabela:~/work/ankidroid/Anki-Android (KushagraPatni/main *) % TEST_RELEASE_BUILD=true ./gradlew packagePlayRelease packagePlayReleaseAndroidTest --console plain --rerun-tasks

> Configure project :AnkiDroid
WARNING: BuildType 'release' is both debuggable and has 'isMinifyEnabled' set to true.
All code optimizations and obfuscation are disabled for debuggable builds.
WARNING: BuildType 'release' is both debuggable and has 'isMinifyEnabled' set to true.
All code optimizations and obfuscation are disabled for debuggable builds.
WARNING: BuildType 'release' is both debuggable and has 'isMinifyEnabled' set to true.
All code optimizations and obfuscation are disabled for debuggable builds.
GPP cannot configure variant 'playRelease' because it is debuggable
GPP cannot configure variant 'amazonRelease' because it is debuggable
GPP cannot configure variant 'fullRelease' because it is debuggable

> Task :api:preBuild UP-TO-DATE
> Task :common:preBuild UP-TO-DATE
> Task :testlib:preBuild UP-TO-DATE
> Task :testlib:prePlayReleaseBuild UP-TO-DATE
> Task :api:preReleaseBuild UP-TO-DATE
> Task :common:preReleaseBuild UP-TO-DATE
> Task :api:writeReleaseAarMetadata
> Task :common:writeReleaseAarMetadata
> Task :testlib:mergePlayReleaseJniLibFolders
> Task :testlib:mergePlayReleaseNativeLibs NO-SOURCE
> Task :testlib:stripPlayReleaseDebugSymbols NO-SOURCE
> Task :AnkiDroid:copyTestLibIntoAndroidTest
> Task :testlib:copyPlayReleaseJniLibsProjectAndLocalJars
> Task :api:generateReleaseResValues
> Task :common:generateReleaseResValues
> Task :testlib:generatePlayReleaseResValues
> Task :AnkiDroid:installGitHook
> Task :AnkiDroid:preBuild
> Task :AnkiDroid:prePlayReleaseBuild
> Task :common:generateReleaseResources
> Task :testlib:extractDeepLinksForAarPlayRelease
> Task :testlib:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :api:generateReleaseResources
> Task :testlib:generatePlayReleaseResources
> Task :common:packageReleaseResources
> Task :testlib:packagePlayReleaseResources
> Task :common:extractDeepLinksRelease
> Task :api:packageReleaseResources
> Task :api:extractDeepLinksRelease
> Task :testlib:mergePlayReleaseShaders
> Task :testlib:javaPreCompilePlayRelease
> Task :testlib:parsePlayReleaseLocalResources
> Task :testlib:compilePlayReleaseShaders NO-SOURCE
> Task :common:processReleaseManifest
> Task :testlib:generatePlayReleaseAssets UP-TO-DATE
> Task :api:processReleaseManifest
> Task :testlib:packagePlayReleaseAssets
> Task :common:compileReleaseLibraryResources
> Task :api:compileReleaseLibraryResources
> Task :testlib:preparePlayReleaseArtProfile
> Task :testlib:prepareLintJarForPublish
> Task :api:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :common:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :common:parseReleaseLocalResources
> Task :testlib:generatePlayReleaseRFile
> Task :api:parseReleaseLocalResources
> Task :testlib:writePlayReleaseAarMetadata
> Task :api:generateReleaseBuildConfig
> Task :common:javaPreCompileRelease
> Task :testlib:processPlayReleaseManifest
> Task :common:mergeReleaseShaders
> Task :common:compileReleaseShaders NO-SOURCE
> Task :common:generateReleaseAssets UP-TO-DATE
> Task :common:packageReleaseAssets
> Task :common:prepareReleaseArtProfile
> Task :api:javaPreCompileRelease
> Task :api:generateReleaseRFile
> Task :api:mergeReleaseShaders
> Task :common:generateReleaseRFile
> Task :api:compileReleaseShaders NO-SOURCE
> Task :common:extractProguardFiles
> Task :api:generateReleaseAssets UP-TO-DATE
> Task :api:packageReleaseAssets
> Task :api:prepareReleaseArtProfile
> Task :api:mergeReleaseJniLibFolders
> Task :api:mergeReleaseNativeLibs NO-SOURCE
> Task :api:copyReleaseJniLibsProjectOnly
> Task :testlib:mapPlayReleaseSourceSetPaths
> Task :AnkiDroid:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :AnkiDroid:generatePlayReleaseBuildConfig
> Task :common:mergeReleaseJniLibFolders
> Task :common:generateReleaseLibraryProguardRules
> Task :common:mergeReleaseNativeLibs NO-SOURCE
> Task :AnkiDroid:generatePlayReleaseResValues
> Task :common:copyReleaseJniLibsProjectOnly
> Task :AnkiDroid:checkPlayReleaseAarMetadata
> Task :AnkiDroid:mapPlayReleaseSourceSetPaths
> Task :AnkiDroid:generatePlayReleaseResources
> Task :AnkiDroid:compilePlayReleaseAidl
> Task :common:compileReleaseKotlin
> Task :common:compileReleaseJavaWithJavac NO-SOURCE
> Task :common:mergeReleaseGeneratedProguardFiles
> Task :common:bundleLibCompileToJarRelease
> Task :common:exportReleaseConsumerProguardFiles
> Task :common:processReleaseJavaRes
> Task :common:mergeReleaseJavaResource
> Task :testlib:mergePlayReleaseResources
> Task :api:compileReleaseKotlin
> Task :api:compileReleaseJavaWithJavac
> Task :api:mergeReleaseGeneratedProguardFiles
> Task :api:bundleLibCompileToJarRelease
> Task :api:exportReleaseConsumerProguardFiles
> Task :testlib:verifyPlayReleaseResources
> Task :api:processReleaseJavaRes
> Task :api:bundleLibRuntimeToJarRelease
> Task :common:minifyReleaseWithR8
> Task :common:bundleLibRuntimeToJarRelease
> Task :AnkiDroid:mergePlayReleaseResources
> Task :AnkiDroid:packagePlayReleaseResources
> Task :AnkiDroid:createPlayReleaseCompatibleScreenManifests
> Task :AnkiDroid:extractDeepLinksPlayRelease
> Task :AnkiDroid:parsePlayReleaseLocalResources

> Task :AnkiDroid:processPlayReleaseMainManifest
/Users/mike/work/ankidroid/Anki-Android/AnkiDroid/src/play/AndroidManifest.xml Warning:
	meta-data#androidx.work.WorkManagerInitializer was tagged at AndroidManifest.xml:0 to remove other declarations but no other declaration present
/Users/mike/work/ankidroid/Anki-Android/AnkiDroid/src/play/AndroidManifest.xml Warning:
	provider#org.acra.attachment.AcraContentProvider@android:authorities was tagged at AndroidManifest.xml:0 to replace other declarations but no other declaration present

> Task :AnkiDroid:processPlayReleaseManifest
> Task :AnkiDroid:mergePlayReleaseShaders
> Task :AnkiDroid:compilePlayReleaseShaders NO-SOURCE
> Task :AnkiDroid:generatePlayReleaseAssets UP-TO-DATE
> Task :AnkiDroid:javaPreCompilePlayRelease
> Task :AnkiDroid:mergePlayReleaseAssets
> Task :AnkiDroid:prePlayReleaseAndroidTestBuild SKIPPED
> Task :AnkiDroid:expandPlayReleaseAndroidTestL8ArtProfileWildcards
> Task :AnkiDroid:mergePlayReleaseArtProfile
> Task :AnkiDroid:compilePlayReleaseAndroidTestAidl NO-SOURCE
> Task :AnkiDroid:checkPlayReleaseAndroidTestDuplicateClasses
> Task :AnkiDroid:processPlayReleaseAndroidTestManifest
> Task :AnkiDroid:generatePlayReleaseAndroidTestBuildConfig
> Task :AnkiDroid:checkPlayReleaseAndroidTestAarMetadata
> Task :AnkiDroid:generatePlayReleaseAndroidTestResValues
> Task :AnkiDroid:mapPlayReleaseAndroidTestSourceSetPaths
> Task :AnkiDroid:generatePlayReleaseAndroidTestResources
> T [...]

2024-12-30 20:48 UTC, mikehardy commented
With apologies for hijacking that one @KushagraPatni - you may want to try a different issue if you are still interested in contributing. That one turned out to be not such a good first issue...

2024-12-30 21:07 UTC, david-allison approved these changes
Seems like I'm not a gradle expert by choice... LGTM given testing steps

2024-12-30 21:20 UTC, mikehardy commented
> Seems like I'm not a gradle expert by choice

wise man

If it weren't for all the react-native module maintenance I have to do I'd ignore it, but with that there's no ignoring it, so...here I am.

2024-12-31 05:44 UTC, KushagraPatni commented
No issues @mikehardy, I think I would have a lot of trouble figuring this one out.

2024-12-31 13:59 UTC, mikehardy commented
My main concern with this was accidentally increasing compilation time a great deal, which is why I carefully configured the dependency only for release or debug (the test name variant) vs just "assemble" (since that caused all variants, all flavors of AnkiDroid to compile! I tested it). I believe the current version works well and the action run doesn't show a big time increase so I'm going to merge this - I don't expect a subtle-gradle-magic review from anyone else at the moment 😉 

https://github.com/ankidroid/Anki-Android/actions/workflows/tests_emulator.yml

2024-12-31 13:59 UTC, merged