Replaced CustomStudyListener with FragmentResultApi in CustomStudyDialog
ankidroid/Anki-Android pull request #17692
Opened 2024-12-30 17:08 UTC by Aditya13s

## Purpose / Description
Replace `CustomStudyListener` with the `FragmentResultApi` in `CustomStudyDialog` to improve fragment communication.

## Fixes
* Fixes #17665

## Approach
Replaces the `CustomStudyListener` functions with `setFragmentResult` to pass `CustomStudyAction` inside a bundle. The result is then listened inside `DeckPicker` using `supportFragmentManager.setFragmentResultListener`.

## How Has This Been Tested?
Tested on Android 12

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2024-12-30 17:16 UTC, Aditya13s commented
@david-allison Kindly review and advise if any additional changes are required

2024-12-30 17:36 UTC, david-allison requested changes
* define `CustomStudyAction.fromOrdinal`
* Extract the key to a constant
  * Consider extracting the bundle arg key to a constant 
* 🐞 This doesn't handle all callers
* Remove the `CustomStudyListener`

2024-12-30 17:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +    enum class CustomStudyAction {
define `fromInt` and use

2024-12-30 17:36 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
>          fun onExtendStudyLimits()
Does this interface still need to exist?

2024-12-31 12:31 UTC, Aditya13s commented
> Remove the `CustomStudyListener`

 @david-allison 
CustomStudyListener Interface or val ?

2025-01-04 00:21 UTC, david-allison commented
The interface, it should no longer be necessary if you're using the result API

2025-01-06 15:04 UTC, david-allison approved these changes
Great stuff!

Some requests, but I'm putting this PR as 'need second approval', as they're all mechanical refactorings

2025-01-06 15:04 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +            val action = CustomStudyAction.fromOrdinal(actionOrdinal)
optional: `CustomStudyAction.fromBundle`

2025-01-06 15:04 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
> +                CustomStudyAction.EXTEND_STUDY_LIMITS -> onExtendStudyLimits()
inline `onCreateCustomStudySession` and `onExtendStudyLimits`

2025-01-06 15:04 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt
> +                CustomStudyAction.EXTEND_STUDY_LIMITS -> onExtendStudyLimits()
inline `onCreateCustomStudySession` and `onExtendStudyLimits`

2025-01-06 15:04 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +    enum class CustomStudyAction {
Move this to the end of the class, along with the other enums

2025-01-06 15:04 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
> +                CustomStudyAction.EXTEND_STUDY_LIMITS -> onExtendStudyLimits()
again: inline

2025-01-06 15:41 UTC, mikehardy approved these changes
Thank you, and also LGTM assuming suggested refactors are completed
Leaving as needs second approval, after pushing refactors re-request approval from David for final merge check is best path I think
Cheers

2025-01-06 15:51 UTC, Aditya13s commented
@david-allison I've made the changes. Please review.

2025-01-06 16:33 UTC, david-allison requested changes

2025-01-06 16:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +                }
Yeah... good shout to inline this as well

2025-01-06 16:33 UTC, david-allison commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
> +            fun fromBundle(ordinal: Int): CustomStudyAction? = entries.find { it.ordinal == ordinal }
`fromBundle` should accept a `bundle`. 

I'll fix this. It's good, I want it in.

2025-01-06 16:44 UTC, david-allison approved these changes
`+93, -98`, less code AND better code 🥳

2025-01-06 17:07 UTC, merged