Add Missing Statistics Data to Overview
ankidroid/Anki-Android pull request #6421
Opened 2020-06-09 19:41 UTC by david-allison-1

## Goals 

* Compare the two images and ensure data is consistent

## Purpose / Description
This brings us in line with the data that is shown by vanilla Anki Desktop on the stats page.

The months don't completely line up, so my screenshots display years.

## Fixes
Fixes #5266 
Fixes #4326 

## Approach
* Bit 'o SQL, bit o' comparison. Then output to HTML

* The translation strings here are a nightmare

## How Has This Been Tested?

Comparison with Anki Desktop. See comment

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2020-06-09 19:53 UTC, david-allison-1 commented
![anki-stats-2020-06-09@20-37-17-2](https://user-images.githubusercontent.com/62114487/84193337-312a6d80-aa93-11ea-83da-19b0c4de25f8.png)
![anki-stats-2020-06-09@20-37-17-3](https://user-images.githubusercontent.com/62114487/84193346-35568b00-aa93-11ea-9dba-758287813b64.png)
![anki-stats-2020-06-09@20-37-17-4](https://user-images.githubusercontent.com/62114487/84193352-38517b80-aa93-11ea-8757-9afcffd5993d.png)
![anki-stats-2020-06-09@20-37-17-1](https://user-images.githubusercontent.com/62114487/84193356-3ab3d580-aa93-11ea-92e4-06cbf19b16a9.png)

![image](https://user-images.githubusercontent.com/62114487/84193377-43a4a700-aa93-11ea-8a46-232f50aeaae3.png)

2020-06-09 19:56 UTC, david-allison-1 commented
There's still discrepancies, but I don't think they're with stats that I've done... hopefully the issue is with the day cutoff.

2020-06-09 20:23 UTC, mikehardy requested changes
Looks great, all I could see where just a couple places where it appeared like magic numbers were used in place of references to Const

2020-06-09 20:23 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
> +            } else if (currentType == 2) {
magic number 2?

2020-06-09 20:23 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
> +            answerButtonsOverview.correct += elements[1] == 1 ? 0 : elements[2];
magic number 1? (I think that 1 should be a Const)

2020-06-09 20:23 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
> +            list.add(0, new double[]{0, 1, 0});
I think this default empty thing is also a 0, 1, 0 of magic instead of const?

2020-06-09 20:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
> +            } else if (currentType == 2) {
Extracted method - not my code

2020-06-09 20:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
> +            answerButtonsOverview.correct += elements[1] == 1 ? 0 : elements[2];
This is my code!

2020-06-09 20:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
> +            list.add(0, new double[]{0, 1, 0});
Not my code change, just extracted

2020-06-10 14:50 UTC, mikehardy approved these changes
Vámonos!

2020-06-10 14:50 UTC, merged