JS API: Add: ease, id, creation and modified time
ankidroid/Anki-Android pull request #6766
Opened 2020-07-28 20:47 UTC by david-allison-1

## Purpose / Description
Properties weren't available and were requested

## Fixes
Fixes #5587

## Approach
Provide the properties

## How Has This Been Tested?
Untested

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2020-07-28 20:47 UTC, david-allison-1 commented
@Anthropos888 @infinyte7 Does the format of these properties seem sensible to you guys?

2020-07-28 20:49 UTC, david-allison-1 commented
Potential discussion points:

* Naming of created: Created/CreationTime
* Is sending a unix timstamp the best way?
* Should the ease be a double (2.5), or the database value of 2500? Do we want to call it `factor` or `ease`

2020-07-29 00:01 UTC, Arthur-Milchior reviewed
I do like the idea. Is there any reason why you add access to those values, and not all values from the database simultaneously ?

2020-07-29 00:01 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            return ((double) mCurrentCard.getFactor()) / 1000.0;
I would expect that keeping up to database format would be better. So use name "factor" and not dividing by 1000. First because a computer can't divide by 1000 without loosing informations, and that may be a real problem if someone want to know the actual number used to computer values. Furthermore, I would expect anyone needing access to the JS to know the actual database format anyway.

2020-07-29 04:10 UTC, infinyte7 commented
The value stored in Ankidroid should be passed and details about changing it, should be provided in wiki. It will help in designing card with exact numbers.  For example. eta is passed, not eta*60. But if it needs to changed then also okay.

2020-07-29 15:38 UTC, mikehardy commented
javascript can consume unix epoch timestamps directly in `new Date(millisSince1970)` so that's good

javascript *only* has a [`number` numeric type, and it is a double](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number). Number should be sent to javascript as doubles if possible, or if not they should probably be strings so that they are not modified in anyway and javascript can figure out how to handle them, as @infinyte7 mentions (via `parseInt(number, radix)` or similar

2020-07-29 16:00 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            return mCurrentCard.getMod();
I'd prefer to just keep the (unfriendly) current names as well - as sort of an ecosystem compatibility thing. The names attached to the data are a bit like an API and better to pass that through then make what is essentially a translation layer. So this would be `ankiGetCardMod`, and other `getCardId` etc

Avoiding naming confusion+education-need+problems and referring upstream is the desired outcome for me with that stance - upstream docs will remain relevant for reference

2020-07-29 16:00 UTC, mikehardy requested changes
comments on naming and datatypes

2020-08-02 17:29 UTC, david-allison-1 commented
Other methods in the class are returning `long/int`. 

I'll return these until we decide to move to `String/double`, as these will all need to be tested at once.

2020-08-02 17:40 UTC, david-allison-1 commented
Noting: `ankiGetCardInterval` should be `ankiGetCardIvl`

2020-08-02 17:42 UTC, david-allison-1 commented
Pushed - added all properties as requested by Arthur. Names and data types now match the AnkiDroid codebase

2020-08-03 00:58 UTC, Arthur-Milchior approved these changes

2020-08-03 14:50 UTC, mikehardy approved these changes
fantastic

2020-08-03 14:50 UTC, merged