More non real time
ankidroid/Anki-Android pull request #6965
Opened 2020-08-25 10:28 UTC by Arthur-Milchior

I find some more place where I use real time. Seems it shows not everything was catched by lint.

I moved all functions dealing with time in Time.In particular because Calendar/Date object have real time when they are created, it seems it can't be helped even if we want to have a specific date instead. This way at least, the part of the process where we have real time is encapsulated

2020-08-25 10:33 UTC, david-allison-1 requested changes
Can we determine why these weren't caught by the lint?

Ideally after this PR, adding the code back in should fail the build/warn the user.

2020-08-25 10:41 UTC, Arthur-Milchior commented
@lukstbit your help would be welcomed in investigating this question if you please.

I did warn in https://github.com/ankidroid/Anki-Android/pull/6956#discussion_r476255034 that there was still this problem. 

In android studio, on master, I can add
`long s = System.currentTimeMillis();`
in a method and get no trouble at all compiling

2020-08-26 12:58 UTC, lukstbit commented
@Arthur-Milchior Sorry for taking so long to respond.
The rules don't apply in Android Studio because I didn't setup them. When I wrote them I used the command line to iterate faster and also because integrating Lint rules from local modules with Android Studio is quite problematic(many bugs reported about this on both the Lint and Android Studio issues trackers). To make the rules work inside Android Studio there are two options:

- Copy the jar file obtained from the lint-rules module (in build/libs/lintrules.jar) to the user's home folder in `.android/lint`. This works but it's kind of deprecated
- Make the rules available through a library so they get integrated with Android Studio. In order to do  this:

 From `AnkiDroid/build.gradle` remove the line: 
   
   `lintChecks project(":lint-rules")`

 In  `api/build.gradle` instead of the line:

  `lintChecks project(":lint-rules")`

use

  `lintPublish project(":lint-rules")`

After making this changes you **must** clean the project and then do a build(either through the Build Menu(Rebuild Project) or from the command line with `./gradlew build`). At this point the rules will apply in Android Studio but they seem a bit slow to be triggered.

2020-08-26 13:19 UTC, Arthur-Milchior commented
@lukstbit First, I want to emphasize that you have no reason at all to be sorry. You are doing us a great service, you're volunteer (as we are), so everything you do is a bonus that is appreciated.
And in any way, taking a day to answer is not long. As a matter of fact, I've PR opened for month which sometime are not deemed a priority at all. 

I fear that I badly ask my question. I thought that those new rules would ensure that the build fails if some time function/constructor were used in place where they should not be used. That is, that with current version of the code, build would fail on travis and so we would immediately see that there is a problem. Did I misunderstood ? Is there a way to ensure that the compilation fails if those rules are not satisfied ? Indeed, ensuring that travis reject an incorrect use of time would:
1. help us ensure all remaining usage are correct (at least for the function we know to be used in the codebase)
2. no future dev uses an incorrect method by accident. Because in one year, us or the next mainteneur will probably have forgotten about this whole time issue and risk to accept this change while they should not

2020-08-28 15:21 UTC, Arthur-Milchior commented
Rebased on top of https://github.com/ankidroid/Anki-Android/pull/6976 to ensure I forgot no time method

2020-08-28 20:32 UTC, mikehardy commented
@Arthur-Milchior this one took a conflict on an unrelated PR as a new check was added to the "breaks the build" list: https://github.com/ankidroid/Anki-Android/pull/6986/files#diff-5a1d61b89cdf0eeceb29054306d657d4

And it has 3 failures exposed now: 

```
  

  The first 3 errors (out of 5) were:

  /home/travis/build/ankidroid/Anki-Android/AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java:104: Error: Use the collection's getTime() method instead of directly instantiating Date [DirectDateInstantiation]

          return DateFormat.getDateInstance(DateFormat.SHORT, getLocale()).format(new Date(ms));

                                                                                  ~~~~~~~~~~~~

  /home/travis/build/ankidroid/Anki-Android/AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java:110: Error: Use the collection's getTime() method instead of directly instantiating Date [DirectDateInstantiation]

          return DateFormat.getDateInstance(DateFormat.SHORT, getLocale()).format(new Date(s * 1000L));

                                                                                  ~~~~~~~~~~~~~~~~~~~

  /home/travis/build/ankidroid/Anki-Android/AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java:794: Error: Use the collection's getTime() method instead of System.currentTimeMillis() [DirectSystemCurrentTimeMillisUsage]

              long startTimeMillis = System.currentTimeMillis();

                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~

  
```

2020-08-28 21:07 UTC, Arthur-Milchior commented
Oops, the two first are false errors. "new Date(long)" is an acceptable constructor. It does not refer to real time. It would be good if lint could allow this constructor while forbidding the default one. Do you think it could be done @lukstbit ?

I'll let @lukstbit resolve the conflict, since I don't know lint.gradle and would not now whether we need to keep both side or only one

The last case tries to measure the time of an operation to display it in Timber. Real time is actually needed. Is there a way to tells that in this case, lint should allow compilation ?

2020-08-28 21:16 UTC, mikehardy commented
I think you can suppress lint with an annotation when you know you know better
The line that David committed in the link I attached is the one to use, has three checks vs 2

2020-08-28 21:26 UTC, Arthur-Milchior commented
I suppressed the 3rd lint. The two first requires to change the lint rules if possible, because they really are things I don't want to forbid

2020-08-29 06:06 UTC, lukstbit commented
@Arthur-Milchior I've made the change to only allow dates created with long values and committed on my PR. 

@mikehardy There's a merge conflict on my branch because in one of the newly merged PRs there was a new lint check added for release(WrongViewcast). That should be resolved by accepting my changes and adding the new check in the `lint-release.xml` file. More info can be found in that file.

2020-08-29 14:31 UTC, mikehardy commented
@lukstbit thank you! @Arthur-Milchior could you rebase over the new commits from that PR (since we are sort of merging them both here)

Advice on conflict resolution:
> accepting my changes and adding the new check in the lint-release.xml file. More info can be found in that file.

But to be very very specific, the contents of that line should be this when done:

> android.lintOptions.check 'NewApi', 'InlinedApi', 'WrongViewCast'

...all 3 checks are the desired final state

2020-08-29 15:14 UTC, Arthur-Milchior commented on lint-release.xml
> +    <issue id="WrongViewCast" severity="ignore" />
I believe this message is for @lukstbit , so should go to https://github.com/ankidroid/Anki-Android/pull/6976

2020-08-29 15:14 UTC, Arthur-Milchior commented
Rebased on lukstbit:apply_lint_rules

2020-08-29 16:26 UTC, lukstbit commented
@david-allison-1 @Arthur-Milchior I enabled those rules and updated my PR. Note that those rules show 2 extra errors.

2020-08-29 18:15 UTC, Arthur-Milchior commented
Moved the use of current time to Time.
I'm not sure of this last commit, because it uses time of a collection while the collection should not exists... however time should still be correct since by default it's always SystemTime.

I don't know what means

>  /home/travis/build/ankidroid/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java:53: Error: Custom view Whiteboard is missing constructor used by tools: (Context) or (Context,AttributeSet) or (Context,AttributeSet,int) [ViewConstructor]
>  public class Whiteboard extends View {
>               ~~~~~~~~~~

However so don't know how to correct

2020-08-29 19:57 UTC, david-allison-1 commented
> I don't know what means

We're no longer ignoring the `ViewConstructor` lint error, and we should be.

2020-08-29 20:06 UTC, Arthur-Milchior commented
Rebased to remove the change in lint. This way, we can remove the use of time in real code and simply deal with lint in the other PR. 
This has conclusively shown there is no more lint problem related to time, that's great, but does not mean this PR should contains lint change

2020-08-29 20:20 UTC, mikehardy commented
@david-allison-1 I think this one is good to go now? With the lint PR now being considered standalone - and that lint PR should pass now after rebasing on top of this post-merge of this

2020-08-29 20:21 UTC, Arthur-Milchior commented
The time based lint rules should pass I believe. The Whiteboard problem will remains but it's unrelated

2020-08-29 21:00 UTC, david-allison-1 requested changes
One request - rest looks good to go

2020-08-29 21:00 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java
> +                            Time time = ch.getColSafe(getContext()).getTime();
Could we add a `getTimeSafe()` - get col time, or return a new instance this can potentially crash -

2020-08-29 21:13 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java
> +                            Time time = ch.getColSafe(getContext()).getTime();
Done. Hopefully what you wanted

2020-08-29 23:56 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java
> +                            Time time = ch.getColSafe(getContext()).getTime();
Looks to be addressed, implementation looks good. Lots of CI to chew through but marking pending merge

2020-08-30 03:34 UTC, merged