Regression 6898 2
ankidroid/Anki-Android pull request #6978
Opened 2020-08-27 19:49 UTC by Arthur-Milchior

When doing undo and then reviewing again, the lrn queue was emptied and elements were not added back until the queue was empty (i.e. all elements added in the queue after undo left the queue)

This means that if we add card 1 to learning queue and then undo later, card 1 won't be seen again until the end of the review. This test show it's corrected.

2020-08-27 20:50 UTC, mikehardy commented
```
com.ichi2.anki.ReviewerTest > testLrnQueueAfterUndo[SchedV2] FAILED

    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.

        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:470)

        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:548)

        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)

        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)

        at java.util.concurrent.FutureTask.run(FutureTask.java:266)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

        at java.lang.Thread.run(Thread.java:748)

        Caused by:

        java.lang.AssertionError: 

        Expected: is "3"

             but: was "2"

            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)

            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)

            at com.ichi2.anki.RobolectricTest.equalFirstField(RobolectricTest.java:383)

            at com.ichi2.anki.ReviewerTest.testLrnQueueAfterUndo(ReviewerTest.java:252)


```

2020-08-27 21:03 UTC, Arthur-Milchior commented
I just run them again, and it works perfectly on my computer, even with multiple test.  First time I see such a difference.

2020-08-27 21:07 UTC, Arthur-Milchior commented
My best guess right now would be that the rule "wait for background task to ends" is not executed the same way in travis and on my computer.

2020-08-27 21:09 UTC, Arthur-Milchior commented
@david-allison-1  or @mikehardy , would one of you accept to download this branch, run the test and report the result. Ensuring I'm not entirely wrong.

Even better would be if you'd accept to investigate the difference  assuming that you also see a difference

2020-08-27 21:10 UTC, Arthur-Milchior commented
I don't eve know how to test, since test works on my computer. I could well add some `wait(500)` in the code, which would make the code work if I'm right...

2020-08-27 21:22 UTC, mikehardy commented
I have you configured as a remote on my local machine already, so I pulled the branch easily - just ran `./gradlew jacocoUnitTestReport` from it and...it was fine. That's on an Ubuntu 20 system but otherwise very similar to the Travis unit test running running linux.

Definitely a timing issue. What? How? Dunno.

If you look carefully at the Travis run, each of the three unit test runners (one macOS, one Ubuntu, one Windows) failed in slightly different ways. Very similar but slightly different.

2020-08-27 21:50 UTC, Arthur-Milchior commented
When you write "timing" do you mean that it's an error related to time. I.e. use of real time instead of simulated time ? Or do you mean a concurrency issue because of background task ?

I wonder whether adding lock in this reviewer to ensure the order of actions would be a solution (a bad one, but a solution)

The other solution is not to use the reviewer at all and directly test the scheduler. I see the point in testing in the reviewer, since it's where data is really shown. But having to deal with background tasks  and listener in unit test make things more complex.

On the one hand, I'm happy to know I got my test right. On the other, I fail that this lead to far more complex testing that what I ever expected.

2020-08-30 17:56 UTC, david-allison-1 requested changes
I think we've hit the point that we want to implement `waitForAsyncTasksToComplete` properly. 

What would the ideal look like, and how close can we get with a reasonable amount of effort.

2020-08-30 17:56 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java
> +    public synchronized void testLrnQueueAfterUndo() throws ConfirmModSchemaException, InterruptedException {
```suggestion
    public void testLrnQueueAfterUndo() throws ConfirmModSchemaException, InterruptedException {
```

2020-08-30 17:56 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java
> +        reviewer.answerCard(Consts.BUTTON_ONE);
Extract these two lines to `answerCard` for readability

2020-08-30 21:45 UTC, Arthur-Milchior commented
I believe https://github.com/ankidroid/Anki-Android/pull/7005 is even better

2020-10-23 14:24 UTC, mikehardy commented
wouldn't it be easier to just add some sleeps in the right spot vs the task manager PRs that are big and apparently contentious or failing in CI? I get their point, but a couple sleeps here and we'd be done

2020-10-24 16:13 UTC, mikehardy commented
I gave this a dual review / pending merge mark, I'm inclined to merge this in if it passes unit tests in CI, I understand it's based on master from just before the batch of CI fixes that fix the android tests, but this is a unit test PR so I would ignore those and merge anyway after another quick scan just to make sure it's a valid test and asserts on the expected resutl

2020-10-24 16:40 UTC, mikehardy approved these changes

2020-10-24 16:42 UTC, merged