NF: Add more line return in xml html
ankidroid/Anki-Android pull request #6982
Opened 2020-08-28 13:45 UTC by Arthur-Milchior

While working on xml ressources, I realized that having all informations on a single line leads to huge conflict. So I just added new line so that git find more similarities and makes better merge.

2020-08-28 20:57 UTC, Arthur-Milchior commented
I added a line in the script that trim the whitespaces I added. I love whitespace to read and understand XML, however I discovered with my recent tests that start and end of line whitespaces are shown to user in a distinct color. Makes sens to warn them when the whitespaces are actually useful. In this case, it's only distracting and confusing

2020-09-08 19:43 UTC, Arthur-Milchior commented
This now contains a script which, if added to pre-commit hook, ensure that xml are correctly formatted. Thanks of course to @phu54321 /trgk

Probably not ready to merge, as there is nothing that ensure that the script is run and that the formatting is correct

2020-09-08 19:58 UTC, david-allison-1 requested changes
Many files have been deleted

2020-09-08 19:58 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/12-dont-translate.xml
> +
?

2020-09-08 19:58 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/17-model-manager.xml
> -<?xml version="1.0" encoding="utf-8"?>
Why was this deleted?

2020-09-08 19:58 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> -<!--
ditto

2020-09-08 20:19 UTC, Arthur-Milchior commented
I redid it from scratch. I assume there were remainings from the different test I made.
I limited the scope to files which I now to contains string

2020-09-08 21:12 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/01-core.xml
> +    Decks
I find this style hard to read - if it's automated then it's not as much of an issue, but maybe it could do with two more indents before "Decks".

I don't want to bikeshed on this. If you disagree then mark this as resolved.

I believe leading and trailing spaces are truncated so this shouldn't be a proble,.

2020-09-08 21:45 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/01-core.xml
> +    Decks
Since <string> already has a 2 space indent, I assume you want 6 spaces here (it already has 4 spaces)
Would you also want 4 spaces before "<string"  instead of two ?

2020-09-08 23:08 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/01-core.xml
> +    Decks
It just feels inconsistent, I didn't grok that the intial indent was two spaces

I'd go:

* 4: `<string` 
* 8: `name=`
* 12: `Decks`

But don't care if it's 2,4,6 instead.

2020-09-08 23:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/01-core.xml
> +    Decks
Thank you for those remarks. I'll look at them if @phu54321 does not do it before

2020-09-09 00:13 UTC, david-allison-1 reviewed
Can you provide steps to test this functionality.

My main question (that I need to answer) would be whether we need to use

`python ./tools/xml_autoformat.py $file > $file.back ;` on Windows, as executing a .py directly often doesn't accept arguments.

https://stackoverflow.com/q/41183165/

2020-09-09 05:04 UTC, phu54321 commented
Yes windows would need `python ./tools/xml_autoformat.py $file > $file.back`

On linux we should use `python3` instead, but it'd be better to make script both python 2/3 compatible.

2020-09-09 12:51 UTC, mikehardy commented
I'm perfectly fine with python3 only, don't waste a minute on python 2 compatibility. Just put a check in the script at the top of execution that checks the version and print an error if it's not 3+

2020-09-09 20:48 UTC, Arthur-Milchior commented
The input and output should be the same since we are just changing the syntax of a file. So if you this change can be made, it would be great.
I did it in bash, but that's not actually useful

2020-10-09 00:44 UTC, Arthur-Milchior commented
Changed so that there are 2 spaces everywhere. I tried with 4 and it seems harder to read according to me. (I may be biaised because I'm mosting spending time on codebase with two spaces currently)

2020-10-09 01:36 UTC, david-allison-1 commented
> Can you provide steps to test this functionality.

I've been asked to re-review this, and this is the most important part - how do I exercise the functionality (from Windows) to ensure that it's working as expected?

Since it's a large change, elaborating on why the decision was made, and the testing that's been done on CrowdIn to ensure we don't trash the existing translations would be useful.

2020-10-09 02:25 UTC, Arthur-Milchior commented
There is a python script. I assume you can run python on windows. I don't know exactly what is the command line, but it seems that if you do 
`python.exe script_path`
it will run. So that's probably what you should put in your `.git/hook/pre-commit` file. I can't experiment on python

I already tested the fact that changing a ressource does not require a new translation as long as it uses the same id. No id is changed, so no new translations are requested. That was the point of a commit a month and a half ago.

The script which runs before upload occurs can be tested manually. It removes start and end of line whitespaces, so that the translator does not see a lot of useless whitespace in the string to translate. This is especially relevant because android trim the string ressources, so all spaces and newline before and after strings are ignored. You can test it easily by Timbering any ressource with newline starting before it.

I believe I already tried to explain the goal here:
* Ultimate goal is to have good translations
* The path forward is helping translator know what they translate (and asking for people to do translations, and review them... but that's not something relevant immediately)
* One of the few way we have to indicate what they translate is proving a comment explaining the context of the string (an other great path would be to have screenshot. But I can't even see screen shot you upload, and it seems to be a quantity of work that is order of magnitude higher than annotating xml)
* According to crowdin documentation, explanation should be given in xml attribute
* Adding all attributes in a single line would lead to huge and hard to read line. It also means that all lines will be modified, leading to huge conflict. This conflict will occurs each time we want to modify the xml
* To avoid to have huge conflict in the future, and to ensure we only get small conflict now, the easy solution is to split line. One line by attribute, one line with the ressource. So anything that change ressource without changing attribute, and anything that change attributes without changing ressources will allow git to find small merge conflict if any.

Furthermore, this goes with the goal I have, in other PR, to have scripts that ensure that style is applied consistently.
Furthermore, if a contributor want to add a string ressource and look at existing code, they'll see the correct formatting. So hopefully, the script will not be very useful in the first place,

2020-11-06 11:32 UTC, Arthur-Milchior commented
I guess I'll just close it, since we don't go with comments but with screenshot

2020-11-06 11:32 UTC, closed without merging