#6424 - warning dialog for duplicates
ankidroid/Anki-Android pull request #6983
Opened 2020-08-28 15:00 UTC by JakubOkrasa

## Purpose / Description
I've created a warning dialog to prevent adding unwanted note with duplicated front card. The past way to warn a user was using red backlight of the first field in the NoteEditor (without any messages). It was unintuitive for users.

## Fixes
Fixes [#6424](https://github.com/ankidroid/Anki-Android/issues/6424)

## Approach
My solution uses the past code to check if a front card is duplicated and displays the warning dialog. I removed the code which backlighted duplicate front cards fields while typing.

## How Has This Been Tested?
on emulator with API 29:
- manually
- automatic tests from NoteEditorTest.java passed

2020-08-28 15:21 UTC, david-allison-1 requested changes
Thanks for the PR!!

I think the main change would be to keep the formatting, I'd still find it useful. 

This may be one of the features that gets annoying for some users (some workflows may involve a lot of duplicates), but it's best to cross that bridge if/when we get a complaint

2020-08-28 15:21 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="dialog_positive_add">Add</string>
I expect that "Add" can be translated differently depending on the context, it's best to have multiple strings even though they use the same English word.

```suggestion
    <string name="dialog_positive_add_note">Add</string>
```

2020-08-28 15:21 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> -
I don't think we should remove the red styling, it has utility for advanced users

2020-08-28 15:21 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="note_editor_dialog_duplicate">The front card with such content already exists. Do you want to add a duplicate?</string>
I think this could be more succinct

@mikehardy You're better at copy than me and I'd rather not request multiple changes. Any suggestions?

```suggestion
    <string name="note_editor_dialog_duplicate">The front card with such content already exists. Do you want to add a duplicate?</string>
```

2020-08-28 17:21 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="note_editor_dialog_duplicate">The front card with such content already exists. Do you want to add a duplicate?</string>
Ah, I think the second copy editor can always improve, my first cut usually needs help too...

```suggestion
    <string name="note_editor_dialog_duplicate">You already have a note with identical front contents. Do you want to add a duplicate?</string>
```

Comes from idiomatic Spanish which would always go "Ya tienes..." in these cases "You already have..." and seems like a quick clear way to state it

2020-08-28 17:21 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> -
I agree, it exists and works and more indicators to avoid duplicates isn't a bad thing

2020-08-28 17:22 UTC, mikehardy commented
Echoing the first statement from @david-allison-1 regardless of nit-picking though, thanks for the PR! Very appreciated

2020-09-01 00:15 UTC, Arthur-Milchior reviewed
First, @JakubOkrasa, thank you very much for creating a PR. It is really appreciated. I need to emphasize it because the review is not really encouraging and I'm not sure whether that's a change I'd want to see in the app. I really like to get new contributors and I am really sad to have to ask for so many changes and to question whether we actually want this feature at all.

2020-09-01 00:15 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> -
And furthermore it's similar to upstream

2020-09-01 00:15 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="dialog_positive_add">Add</string>
That seems mostly useless no. Without context, the translators would not know which add is which. At least add context if we create more strings with same content

2020-09-01 00:15 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="note_editor_dialog_duplicate">The front card with such content already exists. Do you want to add a duplicate?</string>
There is a huge problem here. The very notion of "Front card" only makes sens for basic with (optional) reverse card note type. The basic note type has a single card. Ultimate geography, for example, has no "front" card nor "front" field.
Assuming we want to ask the user to confirm, this is not a correct way to do it.

As a side note, it would make the program frustrating for me. That's not actually a problem since I use anki to create my cards and not ankidroid. However, I've got a ton of notes with duplicate first field and I would hate to have to confirm each time I want to do it. The reason behind it is that the first field is the "page" field. Where I enter the page number, the URL... of the information contained in the note. (Usually, the book/pdf is clear thanks to the deck name). This means that I could only add a single note by URL before I need to get confirmation asked.
If we accept it I'd really want a way to deactivate it. Maybe simply a button "don't ask again"

2020-11-07 01:01 UTC, closed without merging