Show useful error when col version is too high
ankidroid/Anki-Android pull request #7075
Opened 2020-09-13 02:58 UTC by david-allison-1

# Draft

This is a draft so we can discuss the text

## Purpose / Description
This means that the database has been upgraded, and there is currently no way of downgrading from an earlier version

## Fixes
Fixes #7072

## Approach
Check the database version and show a better dialog

## How Has This Been Tested?
Android 9
![image](https://user-images.githubusercontent.com/62114487/93009162-23462600-f575-11ea-8037-e17ddb3bb672.png)

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2020-09-13 02:58 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
> +
```suggestion

    @Nullable
```

2020-09-13 02:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java
> +                       // .itemsColor(ContextCompat.getColor(requireContext(), R.color.material_grey_500))
```suggestion
```

2020-09-13 02:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java
> +                CharSequence[] options = new CharSequence[] { UiUtil.makeBold(res.getString(R.string.backup_restore)), UiUtil.makeBold(res.getString(R.string.backup_full_sync_from_server)) };
This might want a nicer abstraction as it's a rough copy of the same code in another method

2020-09-13 03:00 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java
> +                    Timber.w(e, "Failed to get database version");
```suggestion
                    Timber.w(e, "Failed to get database version, using -1");
```

2020-09-13 03:00 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
> +    public Integer queryVer() {
```suggestion
    public int queryVer() {
```

2020-09-13 03:01 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="database_version_title">Downgrade Required</string>
```suggestion
    <string name="database_downgrade_required_title">Downgrade Required</string>
```

2020-09-13 03:01 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="database_version_summary">The AnkiDroid database must be downgraded, or AnkiDroid must be upgraded before it can be opened\n\nAnkiDroid version: %1$d\nDatabase Version: %2$d\n\nPlea
```suggestion
    <string name="database_downgrade_required_summary">The AnkiDroid database must be downgraded, or AnkiDroid must be upgraded before it can be opened\n\nAnkiDroid version: %1$d\nDatabase Version: %2$d\n\nPlease downgrade the database, or perform one of the following options</string>
```

2020-09-13 11:34 UTC, Arthur-Milchior commented
> currently no way of downgrading from an earlier version

You probably mean "from a latter version" or "to an earlier version". Moving away from earlier does not required downgrade but upgrade

2020-09-13 12:14 UTC, david-allison-1 commented
> > currently no way of downgrading from an earlier version
> 
> You probably mean "from a latter version" or "to an earlier version". Moving away from earlier does not required downgrade but upgrade

This is wording that I need to work on.

From an earlier version (AnkiDroid 2.13), you cannot downgrade the database from V15

2020-09-30 14:01 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java
> +                    Timber.w(e, "Failed to get database version");
I like the -1 addition

2020-09-30 14:02 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
> +    public Integer queryVer() {
I prefer types that can't go null personally

2020-09-30 14:04 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
> +    public static Integer getDatabaseVersion(String path) {
would prefer a constant -1 int unknown, and a real value here. It's a concrete thing the idea of a version, and seems like it should be strictly known as a real integer or a known constant (-1) that is unknown, with a real Exception if it's unrecoverably busted. I just don't like Nulls really, I'll admit it.

2020-09-30 14:07 UTC, mikehardy commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="database_version_title">Downgrade Required</string>
The idea of "database downgrade" is non-sensical to the user in the AnkiDroid context. The AnkiDroid version and database version are locked right? We don't support multiple db versions in multiple app versions. So to be actionable I think the idea that the *app* must be downgraded is the thing to place front and center for the user. How to express that?

```suggestion
    <string name="database_version_title">Incompatible Database Version</string>
```

2020-09-30 14:11 UTC, mikehardy commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="database_version_summary">The AnkiDroid database must be downgraded, or AnkiDroid must be upgraded before it can be opened\n\nAnkiDroid version: %1$d\nDatabase Version: %2$d\n\nPlea
```suggestion
    <string name="database_version_summary">The database is a more advanced version than this version of AnkiDroid can work with. Upgrade AnkiDroid or downgrade the database to open it\n\nAnkiDroid version: %1$d\nDatabase Version: %2$d. The following restore options will overwrite your current collection, possibly with a compatible database version:</string>
```

2020-09-30 14:12 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
> +
As mentioned elsewhere, I'd prefer if the thing wasn't a possible null boxed value and was either a real value or a constant for unknown (-1) with actual exceptions and handling in case things are unrecoverably busted

2020-09-30 14:13 UTC, mikehardy requested changes
I don't see anything fundamentally wrong with the approach but mentioned in my smattering of comments I'd like to rid the idea of Null from the implementation and then it's just a bunch of bike-shed-should-be-yellow wordsmithery which I will do my best on but could also just send out after we've both tried our best

2020-10-01 11:48 UTC, david-allison-1 commented
![image](https://user-images.githubusercontent.com/62114487/94805466-547f7c80-03e4-11eb-870f-fe493af4d471.png)

The dialog will no longer appear if the database is badly corrupted (no col table)

2020-10-01 13:02 UTC, Arthur-Milchior commented
Nit: "AnkiDroid version: 11" is confusing. Because you can see version number on play store, on github, and when we announce an update we usually tell "this is version 2.13". So it'll probably be confusing that we indicate 2.13.3 everywhere and 11 in this message.
As a side note, either both "Version" should have a upper cap, or none should have.

I guess "Collection version: 15. This version of ankidroid support only up to version 11".

2020-10-01 13:55 UTC, david-allison-1 commented
Done

2020-10-01 14:24 UTC, mikehardy approved these changes
LGTM - I was confused a bit why there are were two implementations of the actual SQL but I see it's because sometimes the collection is too munged to open, so this even works in that scenario. Also notied that queryVer returns an Integer but is only ever used unboxed as an int, but if that's what queryScalar returns that's fine. Those are just thoughts, not even nits. I don't believe there's any action to take

2020-10-01 14:24 UTC, mikehardy commented
Will try to pick this to 2.13.5, might as well get it in quickly if possible

2020-10-01 18:06 UTC, david-allison-1 commented
> Also notied that queryVer returns an Integer

That's an oversight, will fix it

2020-10-01 21:54 UTC, merged