Add WakeLock to Deck Import
ankidroid/Anki-Android pull request #7078
Opened 2020-09-13 12:41 UTC by david-allison-1

## Purpose / Description
User needs to keep tapping on their screen to keep the import going. This is annoying on large decks

## Fixes
Related #7077 

## Approach
Take a WakeLock

## How Has This Been Tested?

Untested, don't have enough space on my phone to test, and emulator doesn't sleep

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2020-09-13 12:42 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/WakeLockTaskListener.java
> +    private static final long TIMEOUT_MS = 30 * 60 * 1000L;
I don't think this is going to be long enough - Sync has no timeout, which is scary. 

This seemed like a reasonable middle-ground (with a silent exception if the timeout is exceeded), but I'm unsure

2020-09-13 19:08 UTC, mikehardy reviewed
Ooo - very interesting. I like the attempt / style you're going for here though, I see what you're saying with 30min maybe working but maybe not, with the exception report we'll see I guess.

Is there anything we can bubble up to the user to help them manage the process themselves? We can't know how long an import is during the network part (there was an unrelated issue where we learned AnkiWeb is not really able to indicate size) but during the import we do actually have an indication of progress, it even posts to the task listener.

Perhaps the task listener, as long as progress is being made, can extend the wake lock instead of it being a fixed value?

2020-09-13 21:56 UTC, david-allison-1 commented
> Ooo - very interesting. I like the attempt / style you're going for here though, I see what you're saying with 30min maybe working but maybe not, with the exception report we'll see I guess.
> 
> Is there anything we can bubble up to the user to help them manage the process themselves? We can't know how long an import is during the network part (there was an unrelated issue where we learned AnkiWeb is not really able to indicate size) but during the import we do actually have an indication of progress, it even posts to the task listener.
> 
> Perhaps the task listener, as long as progress is being made, can extend the wake lock instead of it being a fixed value?

I'm out of my depth here, can you extend a wakelock?

2020-09-13 22:06 UTC, mikehardy commented
As an actual API, no, but release and reacquire with a new timeout would be the same. Not sure on how expensive that is but could be done and if expensive could be done only every x% or after x minutes or something

2020-09-21 14:43 UTC, mikehardy requested changes
I still don't like this one unless it actually extends on progress

To offer a concrete suggestion: perhaps in order to keep it self-contained, you can base it all on time calculated internally. If onProgressUpdate half or more of the time has elapsed, acquire a new wake lock for the duration constant defined and drop the old one

In that way as long as the task is emitting progress (which in RFC language it 'MUST DO' really if it runs that long) then it will maintain the lock

2020-09-21 15:24 UTC, david-allison-1 commented
> I still don't like this one unless it actually extends on progress
> 
> To offer a concrete suggestion: perhaps in order to keep it self-contained, you can base it all on time calculated internally. If onProgressUpdate half or more of the time has elapsed, acquire a new wake lock for the duration constant defined and drop the old one
> 
> In that way as long as the task is emitting progress (which in RFC language it 'MUST DO' really if it runs that long) then it will maintain the lock

This needs more work and effort on my behalf:

* Users have 10+GB that they're trying to import, 30m will not be viable.
* I need to heavily test the releasing of locks - maybe we'll require a "double buffering" based approach (two locks, 5 minutes apart, where only one is released)

2020-09-21 16:50 UTC, mikehardy commented
>     * Users have 10+GB that they're trying to import, 30m will not be viable.

Yep - but it does post progress so we get a chance to extend

>     * I need to heavily test the releasing of locks - maybe we'll require a "double buffering" based approach (two locks, 5 minutes apart, where only one is released)

I'm prepared to be shocked, but I'll be shocked if grabbing a new lock before releasing the old doesn't work

2021-01-16 14:18 UTC, closed without merging