Correct #7076
ankidroid/Anki-Android pull request #7080
Opened 2020-09-13 16:35 UTC by Arthur-Milchior

When I split updateScreenCounts in two, in 08bb0597601de2995c81e16ee6b187b68a60a49a, I forgot to call super. So of
course the part of the method which is general to all reviewer was not called.

Tested by running an emulator, adding cards in a new deck A::B, reviewing A and seeing that the title shown is "B"

2020-09-13 16:36 UTC, david-allison-1 approved these changes
Requires a follow up unit test and potentially a follow-up `@CallSuper` run

2020-09-13 17:06 UTC, Arthur-Milchior commented
Regression test added

2020-09-13 17:14 UTC, david-allison-1 requested changes
Could you revert the formatting changes?

2020-09-13 17:18 UTC, Arthur-Milchior commented
Done. Don't know how they were added by android studio

2020-09-13 17:23 UTC, david-allison-1 approved these changes
lgtm

2020-09-13 17:56 UTC, Arthur-Milchior commented
I edited the main message. There is no need for `CallSuper` I believe, because now the method with a problem is split in two

2020-09-13 19:16 UTC, mikehardy approved these changes
LGTM - thanks @Arthur-Milchior - and your regression test additions are all the emojis :trophy: :100:  :1st_place_medal:  haha, but seriously!

2020-09-14 00:07 UTC, david-allison-1 approved these changes
LGTM

2020-09-14 00:16 UTC, merged