port to targetSdk 29
ankidroid/Anki-Android pull request #7112
Opened 2020-09-15 22:22 UTC by mikehardy

## Pull Request template

## Purpose / Description

This is a bit rough-and-ready, not polished and I had hoped to fix more of the deprecation as I went - but the priority is to know with 100% certainty that we have targetSdk 29 capability as soon as possible in the release-2.14 cycle, before we get too close to the Nov 1, 2020 targetSdk29 deadline

So this makes sure we can do it, even if it is not perfect.

Related deprecation issues may be picked off one by one as we have time, but as most of them are fresh deprecations in API30 it should not be too big a deal.

The biggest item of concern right now (which needs testing prior to merging this) is the full screen / immersive UI action in CompatV30. They *really* changed the way that works, and it may be best to peel that commit out to a separate deprecation issue / PR pair so this can go in regardless

## Fixes
Fixes #7107 

## Approach

Mark deprecation where it was unthinkable to make the change now (AsyncTask etc), add Compat interfaces where quickly possible

## How Has This Been Tested?

So far just API28/29/30 emulators to see the effect, with `./gradlew jacocoTestReport` as the test harness.

Needs a good look all around.

## Learning (optional, can help others)

The WindowInsets stuff is a huge change. The threading stuff (AsyncTask, Handler) is a huge change.
The Preferences API change is really big for us also.

The platform moves quickly

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2020-09-15 22:24 UTC, mikehardy commented
This is the commit I mentioned that I'm iffy on. It's simply not doing the job right now and I'm not 100% sure how to get it to do the job.

https://github.com/ankidroid/Anki-Android/pull/7112/commits/99aeeb931b06a1932d178dae7ce6dd0a18cc1263

May be best to leave the raw work in place but in comments for now and just mark the (current) CompatV19 version for deprecation with a new issue to complete the work.

2020-09-15 22:26 UTC, mikehardy commented
Related to this, @david-allison-1 if we want to do any back-porting of database upgrade warnings like #7072 we need to make sure they are installed in release-2.10 (for API15 people) and release-2.13 (for API16+ people) and released before Nov 1 2020 or the updates will *not* be releasable without this PR. And I do not want to backport this PR.

2020-09-15 23:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +    private void updateSummary(android.preference.Preference pref) {
Can we define our own abstract classes, ignore the deprecation there, then use them to get rid of the line noise?

2020-09-15 23:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java
> +            mCompat = new CompatV26();
```suggestion
            mCompat = new CompatV28();
```

2020-09-15 23:21 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV30.java
> +                // I think the forward-port here is to do a WindowsInsets.Builder with WindowInsets.getInsetsIgnoringVisibility
Commenting for a reference for later - could we go with a toast that we know it's broken for now?

2020-09-15 23:22 UTC, david-allison-1 commented on AnkiDroid/src/test/resources/robolectric.properties
> +sdk=28
Can a comment be added?

2020-09-15 23:23 UTC, david-allison-1 requested changes
One issue with compat - worrying, but the code looks good

2020-09-16 00:22 UTC, mikehardy commented
Oo - that compat object return one is huge! It obviously still needs clicking around. I don't want to put anything broken out so I won't toast on the fullscreen one, I think I'd just delegate to compatv19 and log an issue

the preferences idea might just work

I'll do a polish on this the next time I have some cycles and fix everything you saw - thanks for scanning it!

2020-10-04 18:22 UTC, mikehardy commented
superceded by #7343  and #7332

2020-10-04 18:22 UTC, closed without merging