NF: undo message is more specific
ankidroid/Anki-Android pull request #7164
Opened 2020-09-19 20:15 UTC by Arthur-Milchior

Currently the message state that it undoes "(un)mark card" and "(un)suspend cards"

It is now really easy to correct this and put a more specific message. 
I expect it to make https://github.com/ankidroid/Anki-Android/issues/7162 easier to debug

![2020-09-19-220932_622x1151_scrot](https://user-images.githubusercontent.com/357361/93688347-72d0a880-fac5-11ea-8669-a96771fba4d2.png)
![2020-09-19-220743_622x1151_scrot](https://user-images.githubusercontent.com/357361/93688349-73693f00-fac5-11ea-8430-f68e1e928c3e.png)
![2020-09-19-220739_622x1151_scrot](https://user-images.githubusercontent.com/357361/93688350-7401d580-fac5-11ea-8959-15b7d999de28.png)
![2020-09-19-220723_622x1151_scrot](https://user-images.githubusercontent.com/357361/93688351-7401d580-fac5-11ea-8fa0-48d09bd8ad39.png)

2020-09-19 20:41 UTC, david-allison-1 requested changes

2020-09-19 20:41 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="undo_action_unsuspend_note">suspend note</string>
```suggestion
    <string name="undo_action_unsuspend_note">unsuspend note</string>
```

2020-09-19 20:41 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="undo_action_unsuspend_card">suspend card</string>
```suggestion
    <string name="undo_action_unsuspend_card">unsuspend card</string>
```

2020-09-19 20:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +        public UndoMarkNoteMulti(List<Note> originalMarked, List<Note> originalUnmarked, boolean hasUnmarked) {
Could you document what `hasUnmarked` means?

2020-09-19 20:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +        public UndoSuspendCardMulti(Card[] cards, boolean[] originalSuspended,
ditto - quick comment on meaning of `hasUnsuspended`

2020-09-19 20:45 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="undo_action_unsuspend_note">suspend note</string>
Deleted. I reuse strings and thought I already deleted the strings I temporarily added

2020-09-19 20:45 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="undo_action_unsuspend_card">suspend card</string>
same

2020-09-19 20:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +        public UndoMarkNoteMulti(List<Note> originalMarked, List<Note> originalUnmarked, boolean hasUnmarked) {
Done

2020-09-19 20:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +        public UndoSuspendCardMulti(Card[] cards, boolean[] originalSuspended,
Done

I kept the same name for the argument and for the parameter

2020-09-19 21:01 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +        public UndoMarkNoteMulti(List<Note> originalMarked, List<Note> originalUnmarked, boolean hasUnmarked) {
Pushed? I don't see it

2020-09-19 21:02 UTC, david-allison-1 approved these changes
One request for documentation that doesn't seem to have gone in yet - looks good other than that.

2020-09-19 21:03 UTC, Arthur-Milchior commented
Oops. 
> failed to push some refs to 'git@github.com:Arthur-Milchior/Anki-Android.git'  [Type `$' for details]

I retried

2020-09-20 16:01 UTC, mikehardy approved these changes
LGTM thanks!

2020-09-20 16:01 UTC, merged