NF: represents counts as a class
ankidroid/Anki-Android pull request #7171
Opened 2020-09-20 08:04 UTC by Arthur-Milchior

I don't like int[] when we know exactly that they are three elements. Furthermore, counts appear in enough place that it
makes sens to create a class for it. This makes for more readable code

2020-09-20 16:12 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Counts.java
> +    public enum Column {
It's a Queue not a Column really, isn't it? This feels like a mental hold-over from the int[0,1,2] previous vs naming it what it really represents

2020-09-20 16:13 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
> +            counts.mLrn += card.getLeft() / 1000;
it seems like all the Counts usage is encapsulated except this - here you just reach and set something, but the Counts object has some math that it does also. I'd prefer the queue members of Count to be actually encapsulated and not accessed here in this manner for consistency

2020-09-20 16:14 UTC, mikehardy requested changes
I like the idea - seems like a good typing improvement, but is partially encapsulated and has one naming thing - both of which I mentioned in specific comments

2020-09-20 19:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Counts.java
> +    public enum Column {
In my head, I was thinking about the column of number in the deck picker. It counts the number of elements in the queue. But I honestly don't care about the name. I find `.getNew()` far more than `[0]`, then whether it's a queue or a column matter little

2020-09-20 19:32 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
> +            counts.mLrn += card.getLeft() / 1000;
Corrected.

2020-09-20 20:43 UTC, mikehardy approved these changes
LGTM - thanks!

2020-09-20 20:44 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Counts.java
> +    public enum Column {
I agree it is not the most important thing, but access to these can be completely unordered so do like queue better. Thanks

2020-09-21 14:07 UTC, mikehardy commented
Has legit unit test failures

https://travis-ci.org/github/ankidroid/Anki-Android/jobs/728813676

2020-09-21 17:19 UTC, mikehardy commented
Still not working for some reason and took a conflict now :sweat_smile:

2020-09-21 23:53 UTC, Arthur-Milchior commented
Corrected. I inversed elements 1 and 2 of an array... which is kind of funny because it was exactly the reason why I wanted this change, to ensure that this kind of error does not occur ever

2020-09-22 14:13 UTC, mikehardy approved these changes

2020-09-22 14:13 UTC, merged