NF: Sort imports
ankidroid/Anki-Android pull request #7212
Opened 2020-09-21 03:09 UTC by Arthur-Milchior

2020-09-21 15:14 UTC, mikehardy approved these changes

2020-09-21 16:14 UTC, mikehardy requested changes
Yeah - I was curious to see CI on this one - total fail there, there were import removals but no additions so it did not seem like a sort

2020-09-21 23:03 UTC, Arthur-Milchior commented
I think I figured out the root cause of the errror. I had a branch with all corrections, and then cherry picked each commits out of it. This allowed me to track what is corrected and what is not. The problem being that in this case, some other correction removed the uses of some classes, so the import was deleted...
But when I cherry picked, the automated removal of useless import was not correct anymore

2020-09-22 14:08 UTC, mikehardy commented
@Arthur-Milchior still needs correct (I'm only tagging you specifically on the ones that still need attention because the traffic was so incredibly high it might have been lost in the noise - only a few more to check this round)

2020-09-23 16:19 UTC, mikehardy approved these changes

2020-09-23 16:19 UTC, merged