NF: factorize duplicate switch branch
ankidroid/Anki-Android pull request #7217
Opened 2020-09-21 03:50 UTC by Arthur-Milchior

2020-09-21 12:58 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
> +            case Consts.QUEUE_TYPE_DAY_LEARN_RELEARN:
Fix indentation

2020-09-21 12:58 UTC, david-allison-1 requested changes
Quick fix, then good to go

2020-09-21 17:37 UTC, mikehardy commented
and a conflict now :-)

2020-09-21 22:41 UTC, Arthur-Milchior commented
done

2020-09-22 14:05 UTC, mikehardy approved these changes
yep

2020-09-22 14:05 UTC, merged