NF: use enum for direction
ankidroid/Anki-Android pull request #7221
Opened 2020-09-21 04:23 UTC by Arthur-Milchior

This was detected as a problem with switch and an empty case. But it seems this was more important as far as typing goes

2020-09-21 17:15 UTC, mikehardy commented
took 2 conflicts from previous merges

2020-09-21 22:54 UTC, Arthur-Milchior commented
Resolved

2020-09-21 22:56 UTC, david-allison-1 requested changes

2020-09-21 22:56 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.java
> +@SuppressWarnings("ALL")
Why?

2020-09-21 23:00 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.java
> +@SuppressWarnings("ALL")
Seems an accident with Linter suppression of warning.

2020-09-21 23:43 UTC, david-allison-1 approved these changes
👍

2020-09-22 14:10 UTC, mikehardy commented
@Arthur-Milchior took another conflict :-), but, we're almost through merging all these so maybe it will quiet down

2020-09-30 15:50 UTC, mikehardy approved these changes

2020-09-30 15:51 UTC, merged