NF: uses Equals() for string
ankidroid/Anki-Android pull request #7223
Opened 2020-09-21 04:32 UTC by Arthur-Milchior

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code

2020-09-21 12:12 UTC, david-allison-1 approved these changes

2020-09-21 12:14 UTC, david-allison-1 requested changes
On second thought, let's be safe

2020-09-21 12:14 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
> +            if (! ancestorDeckPath[i].equals(descendantDeckPath[i])) {
Would be better to use `Objects.equals(a, b)` here to ensure nulls are handled on both sides

2020-09-21 16:23 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
> +            if (! ancestorDeckPath[i].equals(descendantDeckPath[i])) {
I checked, that API appears to be JDK7 so should be valid, I like the suggestion @Arthur-Milchior

2020-09-21 22:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
> +            if (! ancestorDeckPath[i].equals(descendantDeckPath[i])) {
Done

2020-09-21 22:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
> +            if (! ancestorDeckPath[i].equals(descendantDeckPath[i])) {
Call requires API level 19 (current min is 16): java.util.Objects#equals

2020-09-21 22:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
> +            if (! ancestorDeckPath[i].equals(descendantDeckPath[i])) {
Is there a way to annotate that elements of an array are not null ? I'd like to indicates that the method `path`'s type is

`@NonNull (@NonNull String)[]`

Because currently, none of the strings can be null (I understand why we still want the extra security)

2020-09-21 23:08 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
> +            if (! ancestorDeckPath[i].equals(descendantDeckPath[i])) {
I don't think Android Studio supports it.

Worst case: create `StringUtil.equals()` and note it's deprecated after API 19

2020-09-21 23:42 UTC, david-allison-1 approved these changes

2020-09-21 23:42 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
> +import java.util.Objects;
Probably a missing import now

2020-09-21 23:52 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
> +import java.util.Objects;
Yep...

2020-09-22 14:12 UTC, mikehardy approved these changes

2020-09-22 14:12 UTC, merged