"{{|" was considered as "{{#"
ankidroid/Anki-Android pull request #7282
Opened 2020-09-26 09:43 UTC by Arthur-Milchior

I added a regression test

This has probably never been a problem, as there is no reason to expect anyone ever used "{{|" in a template.
However, that'll be useful to port new card generation rules

2020-09-26 09:52 UTC, david-allison-1 approved these changes

2020-09-26 09:52 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java
> +import static org.hamcrest.Matchers.contains;
Doesn't seem necessary

2020-09-26 09:53 UTC, david-allison-1 requested changes

2020-09-26 09:53 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java
> +    public void regression_test_pipe() {
Don't leave a broken regression test as a single commit without an `@Ignore`, it breaks anyone wanting to perform a full bisect and adds commits that don't compile to the history.

2020-09-26 12:27 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java
> +    public void regression_test_pipe() {
I've got an excessively bad news: this is what I thought I should do, so this is what I did in all previous regression tests that are now merged.
The main idea being that, in order to check that the regression test is actually fixing something, I need to show that something was broken. So that you can test the intermediate commit and check that it is actually broken. 
Otherwise, I could just inadvertently leave a regression test that succeed even before the correction, and so it does not actually test what I expect it to test

2020-09-26 12:31 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java
> +    public void regression_test_pipe() {
Corrected

2020-09-26 12:32 UTC, david-allison-1 approved these changes

2020-09-27 14:23 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java
> +    public void regression_test_pipe() {
Yeah - and I didn't realize the automated bisect impact so I've been letting them go thinking "okay, one commit is broken but the next fixes it, no big deal?" - I like this new style better though and I notice you already used it in a different PR already merged --> :+1:

2020-09-27 14:24 UTC, mikehardy approved these changes
LGTM

2020-09-27 14:24 UTC, merged