Show progress indication when deleting media files (issue #7036)
ankidroid/Anki-Android pull request #7284
Opened 2020-09-26 14:49 UTC by tda1009

## Purpose / Description
This PR is an attempt to implement #7036

## Approach

Issue #7036 reported the lack of progress indication when deleting media files. The first commit of this PR added that indication, in the form of a progress dialog:

![delete_progress_dialog](https://user-images.githubusercontent.com/56965537/94343268-29420980-0041-11eb-9b95-355bb51ab556.png)

Also, while I was analyzing AnkiDroid's code regarding this problem, I noticed that the original code had the intention to show a result dialog when the deletion process finishes (see method deleteUnused()). However, in reality when I use AnkiDroid, this dialog is not shown. That's why I added a second commit to show this result dialog:

![delete_result_dialog](https://user-images.githubusercontent.com/56965537/94343272-30691780-0041-11eb-874e-eee94f8f0c8d.png)

I think a result dialog like above would be helpful in cases where the amount of files to delete was small, only tens or hundreds files for example. In these cases the deletion process would be so fast that the progress dialog might not have a chance to show up, so a dialog showing the deletion result would be nice.

Please consider if this result dialog is neccessary, if not i will remove it.

## How Has This Been Tested?

I verified (on Emulator API 27, 28 and 30) that these commits work as expected. I also ran the automated tests and they all passed (except the purposely ignored tests).

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2020-09-26 15:17 UTC, david-allison-1 requested changes
Looks great! Thanks so much. 😁.

The dialog is a sensible choice, thanks!

Just one nitpck which will make our translations more effective.

2020-09-26 15:17 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="delete_media_result_message">Files deleted: %d</string>
Can you use a `<plurals` here with `one` and `other` defined so the word "files" can better be translated into languages (for example: Lithuanian plurals depends on the suffix of the number - 11 and 12 may use a different word for `files`)

You'll need to refer to it via 

```java
int deletedFiles = result.getInt();
deckPicker.getResources().getQuantityString(R.plurals.XXX, deletedFiles, deletedFiles)
```

Optional: `%d files deleted` reads better to me.

2020-09-27 09:48 UTC, tda1009 commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="delete_media_result_message">Files deleted: %d</string>
Hi @david-allison-1, thank you for your feedback.

I has updated the PR in accordance with your suggestions.

![delete_singular](https://user-images.githubusercontent.com/56965537/94361762-06673200-00e1-11eb-9107-c144959168bc.png)

![delete_plural](https://user-images.githubusercontent.com/56965537/94361767-0b2be600-00e1-11eb-86b9-ab12105fa705.png)

2020-09-27 13:26 UTC, mikehardy approved these changes
This looks great the me thanks @tda1009 ! And thanks @david-allison-1 for the review + plurals note

2020-09-27 13:27 UTC, david-allison-1 approved these changes

2020-09-27 13:33 UTC, merged

2020-09-30 00:35 UTC, mikehardy commented
Picking this to 2.13.4 because it involved a string delete. I accept any risk of breakage by doing so - I think it'll be fine for what it's worth but I'll let 2.13.4 marinate in beta for a couple days just in case