Empty card progress
ankidroid/Anki-Android pull request #7290
Opened 2020-09-27 14:30 UTC by Arthur-Milchior

On my collection, "empty cards" takes two minutes. No progress indicates where we are. I correct it by adding a number. This is not perfect, because the numerator counts cards that should exists and the denominator counts cards that already exists. So if there are missing cards in the collection, the numerator will become greater than 1. On the other hand, if cards should be deleted, we will never reach the denominator. This is still a good indication on how the process is evolving.

Furthermore, this task is now cancellable.

2020-09-27 14:37 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                // Ensure we update at most 100 times. Updating in real time freeze the screen
If this is an update frequency issue, then we could perhaps still overwhelm the display if the math was correct and each percent was roughly real time. Perhaps better to have this "update frequency reducer" be based on time vs percents, and update once a second? (or similar)

2020-09-27 14:38 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                        deckPicker.getResources().getString(R.string.emtpy_cards_finding) + cardSeen + " / " + numberCards);
```suggestion
                        deckPicker.getResources().getString(R.string.empty_cards_finding) + cardSeen + " / " + numberCards);
```

But more problematically this does not work with RTL languages, the numbers should be interpolated into the string with a string format I think?

And a minor note, but if the math is "fuzzy" (you mention that things might go up or down) then I think you could put a `~` sign or something before the numbers to indicate "not exact but close"

2020-09-27 14:39 UTC, mikehardy requested changes
I like the idea but the string is problematic, and if update frequency is an issue then I think it will still exist?

2020-09-27 14:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                // Ensure we update at most 100 times. Updating in real time freeze the screen
Actually, it was not a real time issue. I discovered later that it was an issue that I kept displaying new box instead of updating the current one. Make sens, I'll do it

2020-09-27 14:47 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                // Ensure we update at most 100 times. Updating in real time freeze the screen
would be better to just update then ? :-) - I think there are patterns to follow with the sync progress and the database check dialog

2020-09-27 14:48 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                        deckPicker.getResources().getString(R.string.emtpy_cards_finding) + cardSeen + " / " + numberCards);
I copied what we do for "check collection". You may be right, but in this case it means this is also incorrect.

The number shown are exact. The trouble is that both numbers counts different things.  
I.e. "39691 /233434" means "We have checked that 39691 cards should be generated from your notes according to your collection, and for information your collection has 233434 cards". 
This is a good indication, because assuming that there are only a small number of cards to create/delete, then the numerator will almost reach the denominator.
So "~" seems really strange here.
If instead I showed percent, that would makes sens. But I like the idea to showing to the user their actual number of cards

2020-09-27 14:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                // Ensure we update at most 100 times. Updating in real time freeze the screen
The second problem is going to be that if you want the numbers in the ressource, then we'll need to ask all translations to be done again. I'm not really fan of this idea.
At least, I'll wait until we have decided what numbers to show before creating a new string

2020-09-27 14:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                        deckPicker.getResources().getString(R.string.emtpy_cards_finding) + cardSeen + " / " + numberCards);
Why not use a progress bar capped at 100%? 

Intuition from reading the code a while back implies that our Progress Dialog supports it, and this removes the ambiguity from a user's point of view - a progress bar stuck at 100% isn't great, but it happens a lot in applications, and a user would expect it.

2020-09-27 14:53 UTC, Arthur-Milchior commented
Note also that the "Empty card" process actually is done in three parts.

The first part is relatively quick, it simply lists all cards in the database.
The second part is slow, it check all notes and generates its card and check what is missing/create what must be created.
The third part is usually quick, it consists in saving in the db the cards that are actually missing.

This is the part I count. I am not a fan of the fact that some actions occurs before and after the counts. But I don't see anything better to do

2020-09-27 14:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                // Ensure we update at most 100 times. Updating in real time freeze the screen
I removed this test. Now that I update the string, it works perfectly

2020-09-27 15:03 UTC, david-allison-1 requested changes

2020-09-27 15:03 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                if (emptyCardTask != null) {
Might want to move this code (safeCancel) into a utils class.

2020-09-27 15:03 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        private final int numberCards;
```suggestion
        private final int mNumberOfCards;
```

2020-09-27 15:03 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private CollectionTask emptyCardTask = null;
We never reset this to null after execution - do we want to?

2020-09-27 15:06 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                        deckPicker.getResources().getString(R.string.emtpy_cards_finding) + cardSeen + " / " + numberCards);
I tried to copy what I currently have. I like seeing the actual number of cards in the collection, I find it nice. But if you prefer any other UI, I'm fine with them too as long as it's not harder to code.

2020-09-27 15:06 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                        deckPicker.getResources().getString(R.string.emtpy_cards_finding) + cardSeen + " / " + numberCards);
Inexact progress bars drive me crazy personally (like, there is a numerator and a denominator but it is not really a fraction of work effort being represented...), and it seems that if we want to expose the actual counts we have all sorts of complexity with RTL and strings and stuff.

Let's just do a percent 0 to 100 capped at 100, life will be easy :-)

2020-09-27 15:08 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
> +       //TODO: more validation code
I had indeed a commit which correct the tabs to space before the commits making the actual change. It's easier to work on code well formatted.

2020-09-27 15:08 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            deckPicker.mProgressDialog.setCanceledOnTouchOutside(false);
Use a "are you sure you want to cancel" dialog for this interaction if you're going to do this

2020-09-27 15:09 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
> +    public ArrayList<Long> genCards(long[] nids, CollectionTask task) {
An interface which contains what ?
I want to send update and check whether it's cancelled, it seems to be exactly the point of collection task.

That's exactly what is already done in libanki to cancel the deck due tree computation for example.

2020-09-27 15:10 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            deckPicker.mProgressDialog.setContent(
Can you please let me know what I should do instead ?

2020-09-27 15:13 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private CollectionTask emptyCardTask = null;
Corrected

2020-09-27 15:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        private final int numberCards;
Done

2020-09-27 15:21 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                if (emptyCardTask != null) {
I don't see how to generalize it. If I was sure that I had access to the collection task inside of the task listener, it would be easy to do. But I may imagine that onPreExecute gets executed while `mEmptyCardTask` is still null. This is not a problem with this code, because we access `mEmptyCardTask` only when the task is cancelled. This would be a problem if I tried to access it is `onPreExecute` to send it to the util class

2020-09-27 15:57 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
> +   public String _flagNameFromCardFlags(int flags){
Removed. This'll wait for linting to automatically occurs

2020-09-27 15:58 UTC, Arthur-Milchior commented
I'm pretty sure I saw a post telling me to ask the user whether they want to cancel before cancelling te task. I don't see it anymore. Maybe it was deleted, or I dreamed it. Anyway, I added a message asking the user to confirm whether they want to cancel

2020-09-27 15:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                        deckPicker.getResources().getString(R.string.emtpy_cards_finding) + cardSeen + " / " + numberCards);
I added a number with percent symbol, and a new string... not ideal because this new string contains a part of the old string. But let's go for it if that's what you prefer. 
I have little interest in UI I fear, and will do whatever I have to in order to get the feature I care about in the codebase. But I'll leave the beautiful UI to other if that's what they want to spend their time on.

2020-09-27 16:05 UTC, mikehardy requested changes
I think just the percent and nothing else is best

2020-09-27 16:05 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                                                  deckPicker.getResources().getString(R.string.empty_cards_finding_percent, percent) + cardSeen + " / " + mNumberOfCards);
I am also usually trying to do the minimum UI too, I will admit, this one in particular I was thinking percent *only* with no other info, like so: 
```suggestion
                                                  deckPicker.getResources().getString(R.string.empty_cards_finding_percent, percent));
```

That's how we avoid all the RTL language business - we can't do string concatenation in general because you never know where the language puts numbers naturally when doing translations. This way we have a percent and that's it

2020-09-27 16:06 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                                                  deckPicker.getResources().getString(R.string.empty_cards_finding_percent, percent) + cardSeen + " / " + mNumberOfCards);
Done. That was only an accident the remaining remained. It was already removed while you wrote this

2020-09-27 16:08 UTC, Arthur-Milchior commented
Ideally, I'd split this PR in two. one to cancel the task, one to show percent. However, both needs to deal with tasks and task listener. They both need to get information from libanki, so most of their code should stick together in this PR even if it's not ideal

2020-09-27 16:09 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            deckPicker.mProgressDialog.setContent(
Going with a progress bar and no text seems like the consensus.

2020-09-27 16:11 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            deckPicker.mProgressDialog.setContent(
I don't think we actually have a progress bar dialog? Just percents.
The Material UI standards have moved and we shouldn't be using Dialogs anyway, we should use Progress bars in notifications and not block the UI but that's even farther from what we have now

If this does a dialog with percents I think that is our best practice in our app at the moment?

2020-09-27 16:14 UTC, david-allison-1 commented
Could you try this with the following as I think it will give a better UX impression

```java
new MaterialDialog.Builder(context)
                .progress(false, maxNumberOfElements)
                ...
```

Comment on adding a "are you sure" was mine - I misread the "cancelOnTouch" line of code - if we don't support implicit cancellation, it's not really necessary, thought I'd deleted the message during the review stage rather than after submission.

2020-09-27 16:36 UTC, Arthur-Milchior commented
![Screenshot_20200927-183507_AnkiDroid.jpg](https://user-images.githubusercontent.com/357361/94370445-55689380-00f0-11eb-9844-f1007739bcd5.jpg)

2020-09-27 16:58 UTC, mikehardy commented
Oh cool! The progress bar looks great - is there no title for the dialog though? :thinking:

2020-09-27 17:17 UTC, Arthur-Milchior commented
![Screenshot_20200927-191627_AnkiDroid.jpg](https://user-images.githubusercontent.com/357361/94371335-1e957c00-00f6-11eb-87dd-02f35d323200.jpg)

2020-09-27 17:27 UTC, mikehardy commented
Une chose de toute beauté !

2020-09-27 17:33 UTC, Arthur-Milchior commented
Appart from the number of cards to review in background

2020-09-29 06:06 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            deckPicker.mProgressDialog.setContent(
@mikehardy is the current version of the code okay for you, or do you want to change something else ? It's not clear to me whether I did something you objected to, or whether you are okay with this.

2020-09-29 13:09 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            deckPicker.mProgressDialog.setContent(
just hadn't had time to go review anything yesterday, I was in meetings most of the day. I liked the last screenshot you posted and just need to actually review now!

2020-09-29 18:27 UTC, david-allison-1 commented
Sorry! Had queued up review comments -  let me confirm these are still relevant

2020-09-29 18:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        private long cardSeen = 0;
```suggestion
        private long mCardsSeen = 0;
```

2020-09-29 18:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            deckPicker.mEmptyCardTask = null;
Does this need a 

```
if (deckPicker.mProgressDialog != null && deckPicker.mProgressDialog.isShowing()) {
 deckPicker.mProgressDialog.dismiss();
      }
```

2020-09-29 18:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            deckPicker.mProgressDialog.setCanceledOnTouchOutside(false);
I am sorry, but I have no idea what this comment means.

2020-09-29 18:37 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        private void confirmCancel(DeckPicker deckPicker, CollectionTask task) {
There is no "cancel" button. Cancel occurs with pressing the return button of the phone. 

I believe that asking for confirmation is better, does not take a lot of time and ensure that time is not lost if you pressed by accident

2020-09-29 18:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            deckPicker.mProgressDialog.setCanceledOnTouchOutside(false);
From a quick skim of the code, this seems identical to `cancelable(false)`, I'm possibly mistaken though.

2020-09-29 18:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            deckPicker.mEmptyCardTask = null;
It seems that pressing the back button of the phone dismiss the dialog directly. I don't know whether it is the case on all device or whether it depends on device, version, api... if you tell me it depends, then I'll add it. But on my phone at least, it's useless

2020-09-29 19:01 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            deckPicker.mProgressDialog.setCanceledOnTouchOutside(false);
Are you referring to the lines `setCanceledOnTouchOutside` ?

Because if so, I believe you're wrong. 
`setCanceledOnTouchOutside` ask whether touching anything that is not the dialog trigger cancelling.

`cancelable(bool)` ask whether the dialog is cancelable.

So `cancelable(true)` followed by `setCanceledOnTouchOutside(false)` means that you can cancel, but that it is cancelling only by pressing a "back" button and not by pressing any part of your screen by accident

2020-10-04 13:18 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        private long cardSeen = 0;
Removed

2020-10-07 00:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private CollectionTask mEmptyCardTask = null;
Nullable

2020-10-07 00:42 UTC, david-allison-1 requested changes
Looks good from the implementation POV:

* Architecture - circular dependency in CollectionTask
* Design - I feel we're breaching material design guidelines with the "cancel" prompt, but happy to accept if we can't quickly decide on something better.

2020-10-07 00:42 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                    .content(deckPicker.getResources().getString(R.string.confirm_cancel))
You should be able to pass the IDs into this method directly

2020-10-07 00:42 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            deckPicker.mProgressDialog = new MaterialDialog.Builder(deckPicker)
(nit: add a blank line after ` }};` for readability)

2020-10-07 00:42 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
> +    public ArrayList<Long> genCards(long[] nids, @Nullable CollectionTask task) {
Please abstract out `CollectionTask` into a progress/cancellable listener as mentioned in the previous reviews. We shouldn't have a circular dependency from `CollectionTask` to `Collection`

2020-10-07 00:42 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="confirm_cancel">Do you want to cancel ?</string>
This still applies

2020-10-07 00:42 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="confirm_cancel">Do you want to cancel ?</string>
@mikehardy - yes/no is advised against in material guidelines, but I can't think of any better wording. 

> Don’t use action text that fails to indicate what the selection will do. “Cancel” and “Delete” better indicate what will occur in this dialog.

https://material.io/components/dialogs#alert-dialog

2020-10-07 09:39 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="confirm_cancel">Do you want to cancel ?</string>
It would not be immediately clear whether "cancel" mean "cancel the cancelling action" or "I confirm I want to cancel", this is why I avoided it

2020-10-07 09:40 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private CollectionTask mEmptyCardTask = null;
Done

2020-10-07 09:41 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                    .content(deckPicker.getResources().getString(R.string.confirm_cancel))
Done

2020-10-07 09:42 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            deckPicker.mProgressDialog = new MaterialDialog.Builder(deckPicker)
Done

2020-10-07 10:09 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
> +    public ArrayList<Long> genCards(long[] nids, @Nullable CollectionTask task) {
I changed the uses of CancelTask in Scheduler at the same time

2020-10-07 12:38 UTC, david-allison-1 approved these changes
LGTM - two optional comments

2020-10-07 12:38 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/ProgressSender.java
> +public interface ProgressSender<T> {
`@FunctionalInterface`

2020-10-07 12:38 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CancelListener.java
> +public interface CancelListener {
`@FunctionalInterface`

2020-10-07 14:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/ProgressSender.java
> +public interface ProgressSender<T> {
Done

2020-10-14 15:55 UTC, mikehardy approved these changes
Just two nits on missing copyright headers, otherwise pending merge, thanks @Arthur-Milchior

2020-10-14 18:34 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CancelListener.java
> +package com.ichi2.async;
Done

2020-10-14 18:34 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/ProgressSender.java
> +package com.ichi2.async;
Done

2020-10-14 19:05 UTC, mikehardy commented
Thanks @Arthur-Milchior ! Sorry for the slower velocity last week or three, but I am devoting at least a little time to Ankidroid (apart from reviews in my collection 😅 ) each day, things will slowly move forward and this particular one will merge as soon as CI finishes

2020-10-14 21:14 UTC, merged