NF: Reviewer check whether a card is empty more quickly
ankidroid/Anki-Android pull request #7306
Opened 2020-09-29 07:52 UTC by Arthur-Milchior

Cards with a lot of siblings takes time to be displayed. I never noticed because those cards also have a lot of fields, so I assumed it was the cause of the problem. Indeed, it used to be, but card generation was improved enough that it is not the bottleneck anymore. The bottle neck is very silly: to know whether a card is empty, we compute the list of non-empty cards of the note, and then check whether the card belongs to this set... That is entirely useless, since it consider all siblings in a process where siblings data is immediately discarded.

This PR change that, by splitting the method availOrds in three. One part deal with clozed note (this part is already efficient), one part deal with with standard note, and from this part I exctracted the part which deals with each card individually. I added a method which, given a single card, state whether it is empty without considering its neighbors.

2020-09-29 13:18 UTC, mikehardy commented
No idea if they are related or not but there are some performance issues reported still  #7305 - not sure what the reporting user's collection looks like yet

2020-09-29 13:27 UTC, mikehardy requested changes

2020-09-29 13:27 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
> +        if ("all".equals(type)) {
could be a constant, also is there any chance of getting at least a basic test of the area altered to make sure it actually didn't break (and to give you something to build on when you learn why it broke in something completely unexpected way later...)

2020-09-29 15:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
> +        if ("all".equals(type)) {
It could be a constant, indeed. It can't be an enum since it's an element of JSON

We already have test covering whether card are empty or not. That's the test in ModelTest which check which cards are generated (i.e. we only generate the non-empty cards)

2020-09-29 15:51 UTC, Arthur-Milchior commented
That would be a really strange coincidence that we suddenly get a bug report about this very bug the day I try to correct it. This is not new, it was in the code base for a long time, so there is no reason that anki suddenly become slower and that this increase in slowness is related to this PR

2020-09-29 16:25 UTC, mikehardy commented
I agree it is too coincidental to have a chance of being the root cause, regarding the performance regression

2020-09-29 16:32 UTC, Arthur-Milchior commented
Especially since this is not a regression.
It became the slowest part of showing a card only because all of the slow parts became quick recently.

2020-09-29 20:52 UTC, mikehardy commented
I just merged the PR you made for my constants request (thanks again), so naturally there's a conflict here to ingest it

2020-09-29 22:02 UTC, Arthur-Milchior commented
Rebased

2020-10-23 11:27 UTC, Arthur-Milchior commented
Conflict removed

2020-10-23 18:40 UTC, mikehardy commented
This is a heavily-contended PR apparently, It took another conflict! I was all set to review it in my batch of AnkiDroid work today sigh :)

2020-10-23 19:44 UTC, Arthur-Milchior commented
That's not a coincidence at all. Checking whether a card is empty is clearly related to my current work on empty cards. Actually, I tooks some commits of this PR and made them into separate PR in order to get the simpler part merged

2020-10-24 16:08 UTC, mikehardy approved these changes
LGTM - let's get this in before it conflicts again!

2020-10-24 16:08 UTC, merged