Iterate json
ankidroid/Anki-Android pull request #7357
Opened 2020-10-06 11:15 UTC by Arthur-Milchior

https://github.com/ankidroid/Anki-Android/pull/7313 was closed by accident and I can't reopen it. This takes the correction request by @david-allison-1 into account and factorize the first commit

2020-10-06 12:18 UTC, david-allison-1 requested changes
It was better the way it was previously - casting is not the same as using `getXXX`

2020-10-06 12:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
> +        for (Long l: activeDecks.<Long>iterable()) {
This is causing a lot of test failures

2020-10-06 13:40 UTC, Arthur-Milchior commented
getJSONArray, for example, uses a cast from Object to JSONArray internally. So there is no efficiency difference here

2020-10-06 13:48 UTC, david-allison-1 commented
I'm personally happier with a little more code if it'll track the idiomatic usage of the library (such as was done in #7313). 

This change has introduced bugs, it's likely to introduce more when less experienced developers use the `iterable()` method.

I also find that `.<JSONObject>iterable()` just doesn't look good.

2020-10-06 18:09 UTC, Arthur-Milchior commented
The nice thing is that its two commits, so just need to remove the last one

2020-10-06 18:17 UTC, david-allison-1 approved these changes

2020-10-07 00:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
> +        for (JSONObject ta: tmpls.jsonObjectIterable()) {
This moves from `i = 1` to `i = 0`.

2020-10-07 00:59 UTC, david-allison-1 requested changes
Glad I re-checked, could you confirm the listed bug is an issue, and if so, could we get regression cover there.

2020-10-07 10:40 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
> +        for (JSONObject ta: tmpls.jsonObjectIterable()) {
This seems to be multiple issues together. 
I had to go back look at older code to see what is done upstream, and there is a mistake in the first place. Upstream uses "qfmt" while we use "afmt". This means that this whole method has been broken since 2012. 0326c3827f8343ebc643b48bd76519212182dc92
Since this method update the collection from version 3 to 4, I suspect it rarely runs anymore. I'd be okay with writting regression test, but I honestly don't know what is the expected outcome, because it seems that the outcome produced by this method is not even valid anymore according to today's data structure

2020-10-07 10:51 UTC, Arthur-Milchior commented
I can't create a real regression test. Because this method is only called when the first template of a model contains the string "{{cloze:" and this loop only have an effect on templates whose question does not contains the string "{{cloze:". So this wins some time by ensuring that template 0 is not considered since it is always known that it will not be added to the collection. But it does not introduce a bug, even if for some reason someone tried to import a collection in version 3 or lower

2020-10-07 12:03 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
> +        for (JSONObject ta: tmpls.jsonObjectIterable()) {
No point in testing - let's fix it/flag it and move on

2020-10-07 12:41 UTC, david-allison-1 approved these changes

2020-10-07 20:04 UTC, mikehardy approved these changes
OK

2020-10-07 20:04 UTC, mikehardy commented
took a conflict but otherwise good to go

2020-10-07 22:04 UTC, Arthur-Milchior commented
incredible.
I'm not conflicting with a PR I created. only with a PR I merged!

2020-10-08 01:20 UTC, merged