Help screen: Redesign Proposal
ankidroid/Anki-Android pull request #7358
Opened 2020-10-06 23:45 UTC by david-allison-1

## Purpose / Description
* "Help" links to: https://docs.ankidroid.org/manual.html
* "Send Feedback" links to: https://docs.ankidroid.org/help.html

IMO, Both of these pages are information overload for new users, and we could do better to guide them to somewhere where they can get help.

This serves a secondary purpose of allowing users to know that we have both translation, and development opportunities, which should hopefully improve CrowdIn, and maybe get new users to our GitHub

This also allows a good menu for #6565 to add a "Send Bug Report", which directly hits ACRA

## Review Goals

* Do we want to keep "Send Feedback" in the main menu?
* Are the links going to the correct places
* Naming of all the items - including the navigation drawer item
* Discussion on where we want to redirect users to.
* Do we want a "Copy Debug Info" on this screen? Anything else missing?

## Approach
Recursive picture menu

## How Has This Been Tested?

Unit tested and on my device: https://www.youtube.com/watch?v=Djim166Dzc4

Also works in night mode

## Learning (optional, can help others)

Fragment testing using `FragmentScenario` doesn't seem fir for purpose if there's any coupling back from the fragment to the activity.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2020-10-07 00:08 UTC, david-allison-1 commented
Failed on lint:

```
  Errors found:
  
  /home/travis/build/ankidroid/Anki-Android/AnkiDroid/src/main/res/values-zh/constants.xml:21: Error: Inconsistent number of arguments in formatting string link_manual_importing; found both 0 and 4 [StringFormatCount]
      <string name="link_manual_importing">https://docs.ankidroid.org/manual-zh-CN.html#%E5%AF%BC%E5%85%A5</string>
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /home/travis/build/ankidroid/Anki-Android/AnkiDroid/src/main/res/values-ja/constants.xml:21: Conflicting number of arguments here
```

Converted string to CDATA

2020-10-08 01:28 UTC, mikehardy commented
Looks great, what do you think about putting the opencollective on it as donate? If it's a 2 level menu should it have some notion of breadcrumbs at the top (for ability to go back, and knowing where you are now in case of sloppy tapping)? Sorry for just seeing this now, it's a great feature

2020-10-08 03:03 UTC, david-allison-1 commented
Sounds good to me (as long as we don't fall afoul of app store policies). 

This is definitely something that needs bikeshedding over the ordering (and content) of the items, as the ordering implicitly pushes people to and away from certain services. 

Do you have any links on how you'd want breadcrumbs to look visually? 

Would a title and a "back" button be sufficient, or do you have something more advanced in mind?

2020-10-08 03:23 UTC, mikehardy commented
title and back totally sufficient for me
I just did a dive on donation links in android apps and google's policy is (or was) if you are a non-profit and payment is processed securely via a separate website, it'll work. Our fiscal host is non-profit and it fits all the criteria, I think it will be fine for google play at least. Unsure on the others but likely fine?

2020-10-09 01:40 UTC, david-allison-1 commented
Proposed design for breadcrumbs: 
![image](https://user-images.githubusercontent.com/62114487/95532635-d40ade00-09d8-11eb-8161-629ba6c82d2c.png)

2020-10-09 14:51 UTC, mikehardy commented
Exactly what I was thinking, looks great to me

2020-10-09 20:31 UTC, david-allison-1 commented
Added breadcrumb and Facebook/Twitter

2020-10-14 15:28 UTC, mikehardy requested changes
I think this one is really close - the only thing that actually gives me pause is the help link change. I'm not sure how ugly it would be but if you want to get this PR in quickly and not have it spider out you could effectively revert that and maintain locale-specific links directly in main translation, otherwise we need a solution for fallback in case a link is effectively dangling from an inbound translation change we don't notice

2020-10-14 15:28 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
>                  case R.id.nav_help:
I blew you up with the switch -> if/else change here sorry

2020-10-14 15:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.java
> +                textView.setOnClickListener((l) -> val.execute((AnkiActivity) requireActivity()));
L, not, 1. 

But: Should be a discard (sadly unsupported by Java), or "view"

2020-10-14 15:31 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.java
> +        public void writeToParcel(Parcel dest, int flags) {
Definitely fine - arrayList of < 100 elements.

2020-10-14 15:34 UTC, david-allison-1 commented
> I think this one is really close - the only thing that actually gives me pause is the help link change. I'm not sure how ugly it would be but if you want to get this PR in quickly and not have it spider out you could effectively revert that and maintain locale-specific links directly in main translation, otherwise we need a solution for fallback in case a link is effectively dangling from an inbound translation change we don't notice

We still have the problem in our current version, but I'll drop the change.

https://docs.ankidroid.org/manual-zh.html#importing is dangling

Are there opinions on the points in the main post? Namely additional links, organisations, or removing "Send Feedback" on the Navigation view, and bringing everything into "Help"?

2020-10-16 16:27 UTC, mikehardy commented
>    Do we want to keep "Send Feedback" in the main menu?

It does seem duplicative now, could go away

>    Are the links going to the correct places

I will trust you 

>    Naming of all the items - including the navigation drawer item

All seem fine

>    Discussion on where we want to redirect users to.

The only thing I wasn't sure on was reddit two places? I'd prefer to direct people for help to only places we control or are official - mailing list, our issues tracker, Anki forums

>    Do we want a "Copy Debug Info" on this screen? Anything else missing?

Not a bad idea - people struggle to find that

>    Do we want a "we're opening an external link" for privacy if we don't own the site (discord/reddit etc..)


Mmm those typically annoy me but I get it. I'd prefer to just have '(external link)' on uncontrolled sites so it's there at the start and I click or not. But that might be constrained by screen real estate. Perhaps a little section with "External Community Links" or similar, then the list of them. I don't feel strongly though. Just painting the bike shed

This all looks great in general and I'm only answering because you asked specifically for feedback (which is great :-) ), just saying it looks good / tasteful / on target, I'm excited to see it go in

Just needs the conflict and the de-dangling on the manual - if it's already a problem with a link at least we are in control of that and should fix it, vs opening it up for it to be scalably dangling ;-)

2020-10-16 16:42 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/constants.xml
> +    <string name="link_manual_importing">https://docs.ankidroid.org/manual.html#importing</string>
I think I misunderstood, `constants.xml` should be translated only by developers - it shouldn't hit CrowdIn.

2020-10-16 16:44 UTC, david-allison-1 commented
RE: "de-dangling on the manual" What's the action that you'd like me to take here? Just drop the commit?

2020-10-16 17:08 UTC, mikehardy commented
🤔  I don't want to be too prescriptive as you may have added something else useful or actually need a change? I would say as criteria the final solution should result in no change outside of 'values/' though. Hopefully that is still prescriptive enough?

2020-10-16 17:19 UTC, david-allison-1 commented
> 🤔 I don't want to be too prescriptive as you may have added something else useful or actually need a change? I would say as criteria the final solution should result in no change outside of 'values/' though. Hopefully that is still prescriptive enough?

No, prescriptive is great, thanks!

2020-10-26 18:07 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                        new FunctionItem(R.string.send_feedback, R.drawable.ic_email_black_24dp, HelpDialog::openFeedback)
Sorry to seemingly waffle on this, I think we should a 'Donate' to https://opencollective.com/ankidroid - silly to have it and not promote at all. Could use a link to the same actually on the contributions/help documents in FAQ / manual, and as a preliminary look it appears finding an SVG should not be hard https://duckduckgo.com/?q=black+24dp+usd+icon+svg&t=ffab&atb=v201-1&iar=images&iax=images&ia=images

2020-10-26 18:09 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                        new FunctionItem(R.string.send_feedback, R.drawable.ic_email_black_24dp, HelpDialog::openFeedback)
I wasn't sure whether we'd confirmed or not - no problem at all

2020-10-26 18:15 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                        new FunctionItem(R.string.send_feedback, R.drawable.ic_email_black_24dp, HelpDialog::openFeedback)
![image](https://user-images.githubusercontent.com/62114487/97211661-42141b00-17b7-11eb-8706-846b8c12b20a.png)

2020-10-26 18:59 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                        new FunctionItem(R.string.send_feedback, R.drawable.ic_email_black_24dp, HelpDialog::openFeedback)
yeah I just prodded them for final confirmation since I haven't heard back yet but this is okay to tee up in the meanwhile and I'll mark pending merge

2020-10-26 19:00 UTC, mikehardy approved these changes
Looks good, pending response from prior maintainers on donate link

2020-10-27 04:00 UTC, david-allison-1 commented
Cache clear + Force Push to attempt a passing build - API 29 emulator continually failing with unzipping errors

2020-10-27 04:49 UTC, david-allison-1 commented
```
Could not unzip /home/travis/.gradle/wrapper/dists/gradle-6.7-bin/efvqh8uyq79v2n7rcncuhu9sv/gradle-6.7-bin.zip to /home/travis/.gradle/wrapper/dists/gradle-6.7-bin/efvqh8uyq79v2n7rcncuhu9sv.
Reason: error in opening zip file
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:239)
	at org.gradle.wrapper.Install.access$900(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:81)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
```

2020-10-27 15:21 UTC, mikehardy commented
I would hate to not cache gradle but that's annoying...I just re-cleared this PR cache and restarted the 3 busted jobs, we'll see. This has enough consensus to merge now though as is, so once CI is green...

2020-10-27 17:07 UTC, mikehardy commented
So weird. That build is just not going to happen successfully. Merging it anyway

2020-10-27 17:07 UTC, merged