Add "Card Info" screen
ankidroid/Anki-Android pull request #7400
Opened 2020-10-18 02:24 UTC by david-allison-1

## Pull Request template

## Purpose / Description
Anki Desktop contains a card info screen, now we have one

## Fixes
Fixes #7397

## How Has This Been Tested?

API 16 emulator and my phone, with night mode.

## Learning (optional, can help others)

ConstraintLayouts are useful

`android:supportsRtl="true"` is required for this screen to be RTL, but we have a long way to go

![image](https://user-images.githubusercontent.com/62114487/96356950-2e98ee00-10ed-11eb-8729-a4e31c0b0ea1.png)
![image](https://user-images.githubusercontent.com/62114487/96357244-5d18c800-10f1-11eb-8108-d6ecc0cd1b45.png)

![image](https://user-images.githubusercontent.com/62114487/96356989-94857580-10ed-11eb-8149-1a7f7d61fb9a.png)

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

2020-10-18 02:39 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="time_span_decimal_seconds">%s seconds</string>
This is a pain. We want to show total time, or average time in fractions of a second, but Android's plurals don't support floats.

I don't really know what to do here.

2020-10-18 02:41 UTC, dae commented
Why port this to Java when you can use the Rust implementation?

2020-10-18 16:17 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="time_span_decimal_seconds">%s seconds</string>
rounding and move on IMHO

2020-10-18 16:22 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.java
> +            return getIntent().getLongExtra("cardId", INVALID_CARD_ID);
How does this handle activity restarts? the intent won't be there, needs an mCardId + onSaveInstanceState + check for card id persisted in bundle and set in onCreate ?

2020-10-18 16:23 UTC, mikehardy requested changes
activity restart handling but otherwise looks ace to me

2020-10-18 16:24 UTC, mikehardy commented
> Why port this to Java when you can use the Rust implementation?

@dae I was under the impression "Rust" philosophically would replace the libanki directory here and provide the equivalent of a pre-built model/storage layer but it would still require Android-specific (i.e., Java/Kotlin) model bindings, view layers and controllers ?

2020-10-18 22:20 UTC, dae commented
While that's generally the case, even when it was in Python, libanki had a method to spit out HTML representing the card info, which the frontend just needs to shown in a webview.

If you do need to decouple the presentation from the data gathering phase, then a separate method to export just the data from Rust could be made, but I'm not sure that's necessary, as the existing HTML should work on smaller screens already.

2020-10-18 22:49 UTC, dae commented
(Please note I'm not pushing for this PR to be rejected, I was just curious. I gather AD's initial Rust integration won't support decks/note types in Rust, so maybe David decided this couldn't wait...)

2020-10-19 00:03 UTC, mikehardy commented
Or maybe we didn't know about this method :-)

2020-10-19 02:30 UTC, david-allison-1 commented
I hadn't taken a look at the Rust/Python for this screen (my bad), and I'll be more than happy to trash the code here once we've got `rsdroid` into production, but I don't see this screen as a priority for the conversion, so I expect it to stay in Java for a fair time and will still be worth getting into the codebase.

----

A user mentioned that they wanted this screen, and it felt like it'd be an easy win, as it'd be a couple hours of fun to do, we haven't yet [got a lot of new features for 2.14](https://github.com/ankidroid/Anki-Android/milestone/30?closed=1) and I felt it'd be a break from getting the Rust cross-compiled and packed for running under the major desktop targets for Robolectric (was frustrating - finished off today). 

For V1 of `rsdroid`, I'd like to keep 100% fallbacks in place in-case the library fails to load. We're targeting ~16k distinct devices currently, and I'm expecting to have library linking issues which will get past our beta testers. This feature wouldn't be a good cut for V1, despite being well-contained as there wouldn't be a fallback available if we can't access the rust backend.

V2/V3 will be when `rsdroid` settles, and we can systematically test & replace/decommission this, but it'll be a gradual process and I'd rather get something out to users in the meantime.

2020-10-23 14:04 UTC, mikehardy commented
Needs a fix for activity restart I think, then good to go?

2020-10-23 16:38 UTC, david-allison-1 commented
Done & tested

2020-10-23 17:06 UTC, mikehardy approved these changes
sweet

2020-10-23 18:33 UTC, merged