Remove duplicate remove
ankidroid/Anki-Android pull request #7417
Opened 2020-10-19 02:21 UTC by Arthur-Milchior

2020-10-19 02:37 UTC, david-allison-1 commented on AnkiDroid/src/main/res/xml/deck_options.xml
> +                android:dialogTitle="@string/deck_conf_remove"
Wasn't this removed?

2020-10-19 03:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/xml/deck_options.xml
> +                android:dialogTitle="@string/deck_conf_remove"
Not in master, and I can't find any deletion in git log

2020-10-19 15:30 UTC, mikehardy requested changes
```
* What went wrong:

Execution failed for task ':AnkiDroid:processReleaseResources'.

> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

   > Android resource linking failed

     C:\Users\travis\build\ankidroid\Anki-Android\AnkiDroid\src\main\res\xml\deck_options.xml:37: AAPT: error: resource string/deck_conf_remove (aka com.ichi2.anki:string/deck_conf_remove) not found.

         
```

2020-10-23 13:53 UTC, mikehardy approved these changes

2020-10-23 13:53 UTC, merged