Empty card: update at most once by second
ankidroid/Anki-Android pull request #7451
Opened 2020-10-23 14:17 UTC by Arthur-Milchior

Checking the profiler, I see that some significant amount of time is spent enqueuing various update. (To be more specific, this time become significant when all the remaining optimization are merged. Otherwise, it's not the main factor at all)

Maybe one second is too big a delay, there is a clear loss in fluidity. But on the other hand, I believe that one update by second gives a correct amount of information

2020-10-23 15:27 UTC, david-allison-1 approved these changes
IME, it's better to increment every N files (via modulo), rather than adding in a timing dependency.

Code is good either way

2020-10-23 15:41 UTC, Arthur-Milchior commented
How do you decide how many cards to wait until you increment (by the way, I don't know why you mention "files", there is no "file" here)

2020-10-23 17:00 UTC, david-allison-1 commented
> How do you decide how many cards to wait until you increment (by the way, I don't know why you mention "files", there is no "file" here)

A reasonable round number based on the performance of the operation on a normal device. 10/25/50. 

Just "if we've processed N items, then update the UI to the current in-memory value"

2020-10-23 18:01 UTC, Arthur-Milchior commented
I guess I'll go with 1% increase. Smaller increase are not noticeable. 100 update seems reasonable

2020-10-23 18:17 UTC, mikehardy commented
marking to wait pending update to modulo-based-percent increments vs timing

2020-10-23 20:31 UTC, Arthur-Milchior commented
Corrected so that it update once each time that more than a percent of card is seen

2020-10-23 20:46 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            // Time in second, so this ensure one update by second at most
```suggestion
            // Ensure updates only happen if more than a percent of progress happened
```

2020-10-23 20:47 UTC, mikehardy requested changes
The comment was still referencing seconds, suggested some wording to square it with the new implementation
I like the new implementation though :-)

2020-10-23 21:04 UTC, Arthur-Milchior commented
done

2020-10-23 21:05 UTC, david-allison-1 approved these changes
LGTM

2020-10-23 21:05 UTC, mikehardy approved these changes

2020-10-24 00:03 UTC, mikehardy commented
failure of all APIs in the emulator tests - API25 may fail now but not all of them?

2020-10-24 00:05 UTC, mikehardy commented
I don't think the CI failure is related to your work at all. I'm investigating, no action needed on your part

2020-10-24 16:44 UTC, merged