NF: duplicate add note
ankidroid/Anki-Android pull request #7485
Opened 2020-10-24 21:35 UTC by Arthur-Milchior

2020-10-25 22:15 UTC, david-allison-1 requested changes

2020-10-25 22:15 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/04-network.xml
> +## Pull Request template
!

2020-10-26 07:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/04-network.xml
> +## Pull Request template
This is a strange copy paste...

2020-10-26 12:14 UTC, david-allison-1 approved these changes

2020-10-26 12:14 UTC, merged