NF: Comment "reviews"
ankidroid/Anki-Android pull request #7496
Opened 2020-10-24 23:08 UTC by Arthur-Milchior

2020-10-25 22:41 UTC, david-allison-1 approved these changes

2020-10-25 22:42 UTC, david-allison-1 requested changes
Actually, minor wording fixes

2020-10-25 22:42 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/07-cardbrowser.xml
> +    <string name="card_info_reviews" comment="Number of time a card was reviewed">Reviews</string>
```suggestion
    <string name="card_info_reviews" comment="Number of times a card was reviewed">Reviews</string>
```

2020-10-25 22:42 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="deck_conf_rev_cards" comment="Name of the submenu of deck option allowing to configure reviews of due cards.">Reviews</string>
```suggestion
    <string name="deck_conf_rev_cards" comment="Name of the deck options submenu for configuring reviews of due cards.">Reviews</string>
```

2020-10-26 07:34 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="deck_conf_rev_cards" comment="Name of the submenu of deck option allowing to configure reviews of due cards.">Reviews</string>
done

2020-10-26 12:15 UTC, david-allison-1 approved these changes

2020-10-26 12:15 UTC, merged