NF: duplicate rename
ankidroid/Anki-Android pull request #7504
Opened 2020-10-25 01:33 UTC by Arthur-Milchior

2020-10-25 22:47 UTC, david-allison-1 approved these changes

2020-10-25 22:47 UTC, david-allison-1 requested changes
CI failed

2020-10-26 07:37 UTC, Arthur-Milchior commented
Removed conflict. I'll see CI if it fails again. It compiles on my machine

2020-10-26 16:07 UTC, mikehardy requested changes

2020-10-26 16:07 UTC, mikehardy commented on AnkiDroid/src/main/res/values/17-model-manager.xml
> +    <string name="model_browser_options">Options</string>
I understand the comment needed for duplicate rename, I don't understand the new string added here?

2020-10-26 17:52 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/17-model-manager.xml
> +    <string name="model_browser_options">Options</string>
Bad conflict resolution I assume

2020-10-26 17:57 UTC, mikehardy approved these changes

2020-10-26 18:04 UTC, david-allison-1 approved these changes

2020-10-26 18:50 UTC, merged