Show partial result in browser before showing all
ankidroid/Anki-Android pull request #7513
Opened 2020-10-25 14:52 UTC by Arthur-Milchior

## Pull Request template

## Purpose / Description
Currently, showing search result in the browser takes time. On my collection, showing a big deck with subdecks takes 20 seconds. I thought that it could be possible to first show the first cards, and then show the full result. The number of cards I chose is exactly the number of precomputed cards we were already calculating. This lead to showing a part of the result in 7 seconds, while the whole result still takes 20 seconds to show.

The progress bar is still displayed to indicate that the result is not yet fully present.  

Since the card we must show is not yet necessarily in the list, I wait until the full list is  computed to scroll to it.

## Approach
The collection task sends a progress update with the partial result.
We may also want to regularly send partial result, so that the list grow and the user actually see there is work in progress.

One of the program was that the finder deal with list of card id, and the collection task deals with list of card cache. I had to create a class which change the list of cids to the list of card caches, precompute the data of the first card to display, and ensure this caching is actually cached. I do believe that splitting the CollectionTask in smaller classes would have helped here and make code simpler, but I am not going to wait until this is fully discussed and merged/corrected to add this feature.

## How Has This Been Tested?

I run it on my phone, and check it works. I check that some partial result appears quite quicker and that there is no more delay for the full result.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

2020-10-26 16:20 UTC, mikehardy commented
@Arthur-Milchior took a conflict

2020-10-26 16:36 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +            // At the end of the loop, mPositino is the size of cids, we want it to be the last position in cids
typo mPositino -> mPosition but it won't let me make the suggestion

2020-10-26 16:39 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                Timber.d("doInBackgroundSearchCards was cancelled so return«");
formatting here, missing 4-space indent

2020-10-26 16:47 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +            for (; mPosition < cids.size(); ++mPosition) {
I think you could eliminate the mPosition state here - if I'm reading correctly, mPosition is "mCards.size() - 1" at all times? Then this loop can be a standard iterator `for (int i = (mCards - 1); i < cids.size(); i++)`, eliminating both the state and the more complicated for-loop construction?

2020-10-26 16:48 UTC, mikehardy requested changes
Seems like it should work but to me it appears a little harder to read than necessary?

And the typical nearly-useless comment typo stuff but with an uncharacteristic whitespace issue :-)

2020-10-26 18:02 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                Timber.d("doInBackgroundSearchCards was cancelled so return«");
Done

2020-10-26 18:02 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +            // At the end of the loop, mPositino is the size of cids, we want it to be the last position in cids
Done

2020-10-26 18:12 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +            for (; mPosition < cids.size(); ++mPosition) {
You're right in the fact that mCards.size() can be used instead of `mPosition` and this is corrected. The correction is not exact, so I did not follow your loop

2020-10-26 18:13 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +            add(values[0]);
No, the method `add` is also used in `doInBackgroundSearchCards`, where the end of the card list are also added

2020-10-26 18:54 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +            add(values[0]);
Ah - okay, thanks

2020-10-26 18:55 UTC, mikehardy approved these changes
That's much easier to read - this seems like it should work to me and you were the last person in this area as it is :-). Marking for second review just in case I missed something but otherwise LGTM

2020-10-26 18:55 UTC, mikehardy commented
Does appear to still have a conflict though?

2020-10-28 00:10 UTC, david-allison-1 approved these changes

2020-10-28 00:10 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +        PartialSearch partialSearch = new PartialSearch(searchResult, column1Index, column2Index, numCardsToRender);
Nit: encapsulate `searchResult`, and rename the other variable

2020-11-18 19:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +        PartialSearch partialSearch = new PartialSearch(searchResult, column1Index, column2Index, numCardsToRender);
Sorry, i missed your message.
Also sorry, I don't understand what you expect me to do. Where should I encapsulate it?

2020-11-19 03:09 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +        PartialSearch partialSearch = new PartialSearch(searchResult, column1Index, column2Index, numCardsToRender);
Using `searchResult` and `searchResult_` for different variables is confusing

You should be fine to inline `searchResult` as it doesn't appear to be used again, that lets you rename `searchResult_` to `searchResult`

2020-11-20 12:54 UTC, merged