NF: timber uses format
ankidroid/Anki-Android pull request #7542
Opened 2020-10-28 13:17 UTC by Arthur-Milchior

2020-10-28 13:57 UTC, david-allison-1 requested changes

2020-10-28 13:57 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java
> +            Timber.d("scheduler version is %s", schedVersion);
```suggestion
            Timber.d("scheduler version is %d", schedVersion);
```

2020-10-28 16:13 UTC, david-allison-1 requested changes
Was this done via automated refactoring suggestions? 

Some of these appear incorrect

2020-10-28 16:13 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java
> +            Timber.d("%st=%d p=%d * %s", tabs, tElapsed, prob, outcomeProb);
prob is a double

2020-10-28 16:19 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java
> +            Timber.d("%st=%d p=%d * %s", tabs, tElapsed, prob, outcomeProb);
I automated what I could, i.e. the one of the form `"string" + var`
I did the end myself and checked that it compiles, I thought that I would get warning if this was not properly done, as with usual formatting rules

2020-10-28 16:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java
> +            Timber.d("%st=%d p=%d * %s", tabs, tElapsed, prob, outcomeProb);
Somehow, I did not realize that double uses %f, and not %d

2020-10-28 23:33 UTC, david-allison-1 requested changes

2020-10-28 23:33 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            Timber.d("Clipboard has text = %s", clipboardHasText());
bool

2020-10-28 23:33 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
> +                        Timber.i("Change value for key ' %s': %s", key, value);
```suggestion
                        Timber.i("Change value for key '%s': %s", key, value);
```

2020-10-28 23:33 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java
> +            Timber.d("%st=%d p=%d * %s", tabs, tElapsed, prob, outcomeProb);
Still using a %d

2020-10-29 16:17 UTC, david-allison-1 approved these changes

2020-10-30 01:46 UTC, merged