NF: assert->Assert
ankidroid/Anki-Android pull request #7549
Opened 2020-10-28 20:21 UTC by Arthur-Milchior

As timber state, this is never activated. So if we want it, we must uses Assert.

Or we could delete it, the app worked fine up to now without them

2020-10-28 20:43 UTC, david-allison-1 requested changes
`Assert` throws an error. 

I don't feel that crashing is the correct move and we'd be better throwing a class deriving from `RuntimeException`

I especially don't think we should be using `AssertionError`, as it'd be perfectly valid for the test framework to perform some static work in the constructor which would cause test failures in the future.

2020-10-28 20:43 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
> +import com.ichi2.anki.BuildConfig;
BuildConfig?

2020-10-28 20:47 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
> +import com.ichi2.anki.BuildConfig;
Timber suggest to use BuildConfig to check whether it's debug mode and fail in this case.

I tried it, but felt like that was not what we were looking for either. Of course, this does not means that this import should be kept.

I don't understand what you want. either we throw a RuntimeException or we don't crash. But we can't do both simultaneously.
I'm quite fine with any other solution. Just seems that this is not what we are looking for

2020-10-31 09:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
> +import com.ichi2.anki.BuildConfig;
We can throw a class deriving from `RuntimeException` and there's a good chance that it's caught.

Throwing an `Error` means that it should be explicitly handled, and very few places in the code do this.

2020-11-14 15:47 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
> +import com.ichi2.anki.BuildConfig;
Actually, I don't understand why you'd want to catch it, unless we try to correct it. Those are things that are not supposed to be possible in the first place. If we catch it, either we send it again and I don't see the point, or it's ignored and that's worse.
We want to be warned if this ever occurs

2020-11-22 09:13 UTC, david-allison-1 commented
Probably blocked by: https://github.com/ankidroid/Anki-Android/issues/7747

2020-12-08 19:12 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
> +import com.ichi2.anki.BuildConfig;
I removed BuildConfig via an interactive rebase while checking this locally

2020-12-08 19:17 UTC, mikehardy reviewed
I do not like the idea of a previously silent 'assert' now turning into an "Assert" crash without recourse for the user, or any new RuntimeException doing similar.

The right way to solve this is either:

1- continue ignoring it, and if Timber complains, actually remove the assert calls
2- turn each one into a "sendExceptionReport/replace-value-reasonable-default" stanza
3- turn each one into a "your database is corrupt / run check database" stanza and add the appropriate checks / reasonable default repairs to check database

Of the 3, 1 is obviously easiest and I'm going to close this so it is also the default stance

3 is the most correct as these are database corruption issues, and indicate a database needs to be repaired.

2020-12-08 19:18 UTC, closed without merging