NF: direct icon to deck
ankidroid/Anki-Android pull request #7585
Opened 2020-10-31 03:27 UTC by Arthur-Milchior

## Pull Request template

## Purpose / Description
I like the idea to get a link opening directly the reviewer, as suggested in #6995. So you can long click on a deck, and add a shortcut opening the reviewer directly to here.

## Approach
Uses https://developer.android.com/guide/topics/ui/shortcuts/creating-shortcuts#java

## How Has This Been Tested?

Open deck picker, long click on a deck, click on "Create shortcut", add it on android, open another deck, close ankidroid, click on the new icon, see that the correct deck is directly opened.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] Strings resources: All strings added as resources are unique or contain a comment for seemingly duplicate strings to explain the difference between both resources

2020-10-31 03:33 UTC, david-allison-1 reviewed
How does a shortcut get removed?

2020-10-31 03:41 UTC, Arthur-Milchior commented
As any other app on Android main window, you long press it and click on delete/drop it on delete

2020-10-31 03:45 UTC, david-allison-1 approved these changes
Looks good, thanks!

2020-10-31 03:45 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
Could you use `@RequiresApi` instead?

2020-10-31 03:56 UTC, david-allison-1 requested changes
This isn't non-functional

2020-10-31 04:56 UTC, Arthur-Milchior commented
I’m not used too functional change. This became a reflex

2020-10-31 09:29 UTC, david-allison-1 commented
```
  
  Errors found:
  
  /home/travis/build/ankidroid/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.java:150: Error: Call requires API level 26 (current min is 16): createIcon [NewApi]
                  ((DeckPicker) getActivity()).createIcon(getContext());
                                               ~~~~~~~~~~
```

2020-10-31 11:17 UTC, Arthur-Milchior commented
Rhis is why I requested api O to execute this code. It seems tto work whenn it was in a if instead of in a @reUire

2020-10-31 11:19 UTC, david-allison-1 commented
Normally I'd say add the annotation to `CONTEXT_MENU_CREATE_SHORTCUT`, but that doesn't work well with switch statements. Let's leave it how it was

2020-11-05 18:13 UTC, david-allison-1 approved these changes

2020-11-05 18:13 UTC, merged