Import simplified
ankidroid/Anki-Android pull request #7592
Opened 2020-11-01 01:35 UTC by Arthur-Milchior

Importing my main deck takes 6'24''. This PR' reduces it to 6'01''. Not exactly game changing, but still some noticeable progress.
It saves time by:
* Avoiding to query from the database some values that are never used
* Avoiding to convert multiple time between int/long and Int/Long (One last conversion is needed, because sql always takes Object[] which is actually a huge loss of time)

As a benefits, it becomes more clear, since instead of an array of Object, each variable has a readable name. 

It was tested by importing back my deck in a fresk ankidroid collection and seeing that everythnig seems to be alright

2020-11-01 18:36 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +        try (Cursor cur = mSrc.getDb().getDatabase().query("select n.id, n.guid, n.mid, n.mod, n.tags, n.flds, n.sfld, n.csum, n.flags, n.data  from notes n", null)) {
You don't need `n.` here

2020-11-01 18:36 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +    private static class NoteTriple {
is `private static final int GUID = 1;` still used?

2020-11-01 18:36 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +                                        flds.replace("\u001f", ",")));
Use a char here - should be much faster (needs testing)
```suggestion
                                        flds.replace('\u001f', ',')));
```

2020-11-01 18:36 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +                long id = cur.getLong(0);
I'd prefer `nid` here, but implementer's choice

2020-11-01 18:36 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +                                flds = _mungeMedia(mid, flds);
Reviewer note: `note[4] = usn;` is missing, but this is OK as we use the correct value

2020-11-01 18:36 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +                    "select f.guid, c.id, c.did, c.ord, c.type, c.queue, c.due, c.ivl, c.factor, c.reps, c.lapses, c.left, c.odue, c.odid, c.flags, c.data from cards c, notes f " +
much nicer!

2020-11-01 18:36 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +                long scid = cur.getLong(1);
What's a scid?

2020-11-01 18:36 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +                if (queue == 2 || queue == 3 || type == 2) {
Use the constants

2020-11-01 18:36 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +                    if (type == 1) { // type
ditto

2020-11-01 18:36 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +                    if (type == 1) {
ditto

2020-11-01 18:36 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +                cards.add(new Object[]{scid, nid, did, ord, mod, usn, type, queue, due, ivl, factor, reps, lapses, left, odue, odid, flags, data});
Needs second review - looks correct, but there's a lot going on here.

2020-11-01 21:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +                long id = cur.getLong(0);
I prefered to use the database column’s name out of consistency

2020-11-01 21:33 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +                if (queue == 2 || queue == 3 || type == 2) {
Done in another PR that can be merged first

2020-11-01 21:34 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +                cards.add(new Object[]{scid, nid, did, ord, mod, usn, type, queue, due, ivl, factor, reps, lapses, left, odue, odid, flags, data});
You may prefer to look commit by commit, where it should be easier to see why it’s correct

2020-11-01 21:43 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +                if (queue == 2 || queue == 3 || type == 2) {
https://github.com/ankidroid/Anki-Android/pull/7590

2020-11-01 21:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +                long scid = cur.getLong(1);
The variable was named scid before and upstream, so I kept this name even if I don't understand it. I can change it

2020-11-02 00:39 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +        try (Cursor cur = mSrc.getDb().getDatabase().query("select n.id, n.guid, n.mid, n.mod, n.tags, n.flds, n.sfld, n.csum, n.flags, n.data  from notes n", null)) {
Removed

2020-11-02 00:39 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +    private static class NoteTriple {
Not

2020-11-02 00:39 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +                                        flds.replace("\u001f", ",")));
https://github.com/ankidroid/Anki-Android/pull/7598

2020-11-02 00:40 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +                long id = cur.getLong(0);
changed to nid actually.

2020-11-02 00:40 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +                    "select f.guid, c.id, c.did, c.ord, c.type, c.queue, c.due, c.ivl, c.factor, c.reps, c.lapses, c.left, c.odue, c.odid, c.flags, c.data from cards c, notes f " +
I do agree

2020-11-02 00:40 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +                long scid = cur.getLong(1);
My bad. `scid` was Source Card id, and as the name state, it should not have changed. So I separate it in scid and cid

2020-11-02 00:41 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +                cards.add(new Object[]{scid, nid, did, ord, mod, usn, type, queue, due, ivl, factor, reps, lapses, left, odue, odid, flags, data});
@mikehardy , I guess it'll be for you.
You may be happy, I provided stats to explain time gain here

2020-11-02 02:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +g                    mNotes.put(guid, new NoteTriple(nid, mod, mid));
```suggestion
                     mNotes.put(guid, new NoteTriple(nid, mod, mid));
```

2020-11-02 09:45 UTC, david-allison-1 approved these changes

2020-11-02 09:45 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
>      private static final int MID = 2;
Are these two used?

2020-11-02 11:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
>      private static final int MID = 2;
Removed

2020-11-02 11:38 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
> +                    Timber.e(e, "MIids2str :: JSONException");
?

2020-11-02 11:39 UTC, david-allison-1 requested changes
Minor unintentional change added

2020-11-02 11:39 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
> +                long scid = cur.getLong(1);
a comment might be useful

2020-11-02 11:52 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
> +                    Timber.e(e, "MIids2str :: JSONException");
No idea how I added those lines

2020-11-02 11:54 UTC, Arthur-Milchior commented
Comment added for scid

2020-11-03 17:49 UTC, david-allison-1 commented
Conflict, but looks goo otherwise

2020-11-03 17:49 UTC, david-allison-1 approved these changes

2020-11-07 05:02 UTC, david-allison-1 requested changes

2020-11-07 05:02 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
> +                    name = zipEntryToFilenameMap.getOrDefault(name, name);
This is limited to API 24

2020-11-07 05:12 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
> +                    name = zipEntryToFilenameMap.getOrDefault(name, name);
Removed

2020-11-09 17:18 UTC, david-allison-1 approved these changes

2020-11-09 19:37 UTC, mikehardy approved these changes

2020-11-09 19:37 UTC, merged