NF: uses empty when possible
ankidroid/Anki-Android pull request #7599
Opened 2020-11-02 03:22 UTC by Arthur-Milchior

For the sake of readability

2020-11-05 03:52 UTC, david-allison-1 requested changes
I don't think these mass readability improvements are worth the effort unless they're automated (ideally also linted so they don't happen again):

* It took time to write
* It took time to review (and will take time for re-review)
* It introduced bugs in code that was both working, and will hopefully have no reason to be read/changed (I've never touched the wildplot code).
* The benefit from the change is both for a small audience, and low impact

As a cost-benefit, it didn't seem worth it. 

But, let's get this in now it's been submitted.

2020-11-05 03:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +            if (!mEditorNote.items()[index][1].isEmpty()) {
This variable should be extracted, IMO it's harder to read after the change.

2020-11-05 03:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +        if (!preferences.getString("hkey", "").isEmpty()) {
!TextUtils.isEmpty - null should also be handled here

2020-11-05 03:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
> +                if (constraint.length() > 0) {
⚠️

2020-11-05 03:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
> +                if (constraint.length() > 0) {
Reminder to self: Add a test here

2020-11-05 03:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TagsDialog.java
> +                if (constraint.length() > 0) {
Please stop mixing functional changes with `NF:` commits (presumably this was an intentional change as it's happened twice in the same code area in the same PR). 

This introduces a bug

2020-11-05 03:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/JSONArray.java
> +    public boolean isEmpty() {
`isNotEmpty()/any()` would also improve understanding

2020-11-05 03:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/wildplot/android/parsing/AtomTypes/FunctionXAtom.java
> +            if (!hasSpecialChar && (funcName.isEmpty())) {
```suggestion
            if (!hasSpecialChar && (!funcName.isEmpty())) {
```

2020-11-08 19:34 UTC, mikehardy commented
No, let's please stop doing these for all the reasons stated. I have no time for this, sorry

2020-11-08 19:34 UTC, closed without merging