NF: calls ids2String without useless conversions
ankidroid/Anki-Android pull request #7600
Opened 2020-11-02 11:15 UTC by Arthur-Milchior

Those values without conversion are already usable as-is

2020-11-02 11:38 UTC, david-allison-1 requested changes

2020-11-02 11:38 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        String ids = Utils.ids2str(children)+ ",";
What's the extra comma for?

2020-11-02 11:38 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
> +        mDb.execute("update cards set flags = (flags & ~?) | ?, usn=?, mod=? where id in " + cids,
You can't use `array.toString()`

2020-11-02 11:38 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
> +        return getDb().queryLongList("select id from cards where id in " + cards);
Ditto - and this needs regression coverage, as the breakage wasn't caught.

2020-11-02 11:43 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        String ids = Utils.ids2str(children)+ ",";
THe inital goal was to add the element directly. I then realized it would really not work and so changed and added it in the set of values

2020-11-02 11:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
> +        mDb.execute("update cards set flags = (flags & ~?) | ?, usn=?, mod=? where id in " + cids,
This is clearly a mistake. I just wanted to remove conversion. thanks

2020-11-02 11:51 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
> +        return getDb().queryLongList("select id from cards where id in " + cards);
Added

2020-11-02 20:00 UTC, david-allison-1 approved these changes
Great!

2020-11-02 21:12 UTC, Arthur-Milchior commented
I'd like help, I don't get 

> Execution failed for task ':AnkiDroid:compileDebugUnitTestJavaWithJavac'.
> > Could not resolve all files for configuration ':AnkiDroid:debugUnitTestCompileClasspath'.
>    > Failed to transform icu4j-53.1.jar (com.ibm.icu:icu4j:53.1) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
>       > Execution failed for JetifyTransform: /home/travis/.gradle/caches/modules-2/files-2.1/com.ibm.icu/icu4j/53.1/786d9055d4ca8c1aab4a7d4ac8283f973fd7e41f/icu4j-53.1.jar.
>          > Failed to transform '/home/travis/.gradle/caches/modules-2/files-2.1/com.ibm.icu/icu4j/53.1/786d9055d4ca8c1aab4a7d4ac8283f973fd7e41f/icu4j-53.1.jar' using Jetifier. Reason: EOFException, message: Unexpected end of ZLIB input stream. (Run with --stacktrace for more details.)
>            Suggestions:
>             - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
>             - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).

2020-11-03 17:44 UTC, david-allison-1 commented
> I'd like help, I don't understand
> 
> > Execution failed for task ':AnkiDroid:compileDebugUnitTestJavaWithJavac'.
> > > Could not resolve all files for configuration ':AnkiDroid:debugUnitTestCompileClasspath'.
> > > Failed to transform icu4j-53.1.jar (com.ibm.icu:icu4j:53.1) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
> > > > Execution failed for JetifyTransform: /home/travis/.gradle/caches/modules-2/files-2.1/com.ibm.icu/icu4j/53.1/786d9055d4ca8c1aab4a7d4ac8283f973fd7e41f/icu4j-53.1.jar.
> > > > Failed to transform '/home/travis/.gradle/caches/modules-2/files-2.1/com.ibm.icu/icu4j/53.1/786d9055d4ca8c1aab4a7d4ac8283f973fd7e41f/icu4j-53.1.jar' using Jetifier. Reason: EOFException, message: Unexpected end of ZLIB input stream. (Run with --stacktrace for more details.)
> > > Suggestions:
> > > - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
> > > - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).

Typically: Clear travis cache and try again

2020-11-08 19:48 UTC, mikehardy commented
That is a very persistent CI error, I was unable to clear it but the other platforms passed unit test and I checked the emulator runs, everything seems fine

2020-11-08 19:48 UTC, merged