NF: uses parametrized query where possible
ankidroid/Anki-Android pull request #7615
Opened 2020-11-04 10:36 UTC by Arthur-Milchior

They were found using
```sql
= ?" ?\+
```

2020-11-05 03:07 UTC, david-allison-1 requested changes

2020-11-05 03:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
> +            mCol.log(mCol.getDb().queryLongList("select id from cards where did = ?", did));
Add a comment - the code was easier to understand before

2020-11-05 03:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
> +        Object[] bindArgs = new Object[] {};
Consider reverting this - it makes the code harder to reason about.

2020-11-05 04:29 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
> +        mCol.getDb().update("cards", values, "id = ?", new String[] {Long.toString(mId)});
According to doc, this last argument represents values for the `?`
There seems to be no reason to prefer update to execute, or reciprocally. It seems they both do similar thing. It's hard to actually state whether one is better since those are name of interface functions.

2020-11-05 04:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
> +                        Utils.ids2str(dynIdsAndZero), new Object[] {nextDeckId, getTime().intTime(), usn()});
Oh right,

2020-11-05 04:45 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
> +            mCol.log(mCol.getDb().queryLongList("select id from cards where did = ?", did));
Done differently, in a hopefully simpler way

2020-11-05 04:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
> +        Object[] bindArgs = new Object[] {};
Ok

2020-11-05 05:25 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
> +        mCol.log(mCol.getDb().queryLongList("select id from cards where " + lim));
IMO, This is adding too much complexity - I'd be tempted to move it back, unless `emptyDyn()` is on a critical path.

2020-11-05 05:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
> +        try (Cursor cur = mCol.getDb().query(sql, (Object[]) args)) {
Better as the original

2020-11-05 05:29 UTC, david-allison-1 reviewed
Much nicer with the `.query`!

2020-11-05 05:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
> +        try (Cursor cur = mCol.getDb().query(sql, (Object[]) args)) {
ditto

2020-11-05 05:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
> +                        " and flds like ? escape '\\'", new Object[] {"%" + sqlVal + "%"})) {
Is new Object[] needed here?

2020-11-05 05:39 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
> +        mCol.log(mCol.getDb().queryLongList("select id from cards where " + lim));
No. Deleting an empty filtered deck is clearly not a critical path. I'll remove

2020-11-05 05:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
> +        mCol.log(mCol.getDb().queryLongList("select id from cards where " + lim));
On second though, i'm surprised. I'd find this one quite easier to understand, since both functions have a single parameter tehy use, instead of checking whether a value is null, if only in this case uses the other one

2020-11-05 05:46 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
> +        try (Cursor cur = mCol.getDb().query(sql, (Object[]) args)) {
ok

2020-11-05 05:46 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
> +        try (Cursor cur = mCol.getDb().query(sql, (Object[]) args)) {
Ok

2020-11-05 05:48 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
> +                        " and flds like ? escape '\\'", new Object[] {"%" + sqlVal + "%"})) {
Oh actually, the array can be removed here

2020-11-06 11:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
> +        mCol.log(mCol.getDb().queryLongList("select id from cards where " + lim));
Done, even if I I'd still prefer the other version

2020-11-06 16:28 UTC, david-allison-1 approved these changes

2020-11-06 16:29 UTC, merged