NF: addAll
ankidroid/Anki-Android pull request #7632
Opened 2020-11-09 09:01 UTC by Arthur-Milchior

I tried to go through with https://github.com/ankidroid/Anki-Android/pull/7616#issuecomment-723705392 comment and added more addAll.
I actually added some more, using essentially filter and/or map, but I'll keep it for when this simpler PR is merged

2020-11-09 16:39 UTC, david-allison-1 requested changes
Nice! 

One suggestion to make it even better.

2020-11-09 16:39 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
> +    	        addAll(cms, note.model().getJSONArray("tmpls").jsonObjectIterable());
Doesn't `ArrayList.addAll` already exist?

Could be simplified even further (and with an efficiency gain):

`cms = note.model().getJSONArray("tmpls").toJsonObjectList()`

2020-11-09 16:39 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
> +        addAll(ar, jsonArray.longIterable());
ditto

2020-11-09 16:39 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
> +        addAll(list, tags.stringIterable());
ditto

2020-11-09 17:10 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
> +    	        addAll(cms, note.model().getJSONArray("tmpls").jsonObjectIterable());
To be clear, the same way that I created `jsonObjectIterable` you want to add a method
```java
List<JSONObject> toJSONObjectList()
```
and similarly for other type, right ?
It would totally work, not totally ideal when we want to add elements to an existing list, since it requires to create list to delete it immediately after, but as long as we create new elmeents, it's great.

2020-11-09 17:12 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
> +    	        addAll(cms, note.model().getJSONArray("tmpls").jsonObjectIterable());
> To be clear, the same way that I created `jsonObjectIterable` you want to add a method
> 
> ```java
> List<JSONObject> toJSONObjectList()
> ```
> 
> and similarly for other type, right ?
> It would totally work, not totally ideal when we want to add elements to an existing list, since it requires to create list to delete it immediately after, but as long as we create new elmeents, it's great.

That's right! For this use case (and a few more) it's perfect as it allows the optimisation of setting the list size before initialisation.

> not totally ideal when we want to add elements to an existing list

True, but we have `CllectionUtils.addAll` for that.

2020-11-09 17:40 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
> +    	        addAll(cms, note.model().getJSONArray("tmpls").jsonObjectIterable());
As I tried to explain above, `addAll` can not take an iterable, it takes a collection. So I could not give anything directly from Array

2020-11-09 17:55 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
> -                    "SELECT id FROM cards WHERE ord NOT IN " + Utils.ids2str(ords) + " AND nid IN ( " +
ditto from the other PR - I don't see how this is the same

2020-11-09 18:01 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
> -                    "SELECT id FROM cards WHERE ord NOT IN " + Utils.ids2str(ords) + " AND nid IN ( " +
You're entirely right.

2020-11-09 18:22 UTC, david-allison-1 commented
I'll hold off on the re-review until #7637 goes in - this contains changes from it and will need to be rebased. Looks good though, thanks!

2020-11-10 07:27 UTC, Arthur-Milchior commented
Rebased

2020-11-10 18:20 UTC, david-allison-1 approved these changes

2020-11-10 18:20 UTC, merged