Fix #7466: Round Doubles when displaying Deck Options
ankidroid/Anki-Android pull request #7640
Opened 2020-11-09 18:57 UTC by Volfee

## Pull Request template

## Purpose / Description
When you modify some of the deck options like Reviews/Easy Bonus or Reviews/Interval wrong value is displayed.

For example if you modify Easy Bonus to 130 the actual value that is shown in the UI is 129%. This only happens for some values and must be related to some rounding issue.

## Fixes
Fixes #7466 

## Approach
* Changing  Integer.toString() method to String.format("%.0f", ...) that rounds Double values into nearest number without decimals.

## How Has This Been Tested?
* Emulated device Pixel 3a SDK 29.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2020-11-09 19:02 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
> +        @SuppressLint("DefaultLocale")
I just learned about this a few days ago, but I think you can use `Locale.ROOT` for locale-sensitive operations where you do not actually care about the locale? https://developer.android.com/reference/java/util/Locale#ROOT

2020-11-09 19:03 UTC, mikehardy requested changes
added one quick note that I think will get rid of the deprecation warning, but otherwise this looks good. Could you post a screenshot of a before/after since this affects the UI? (helps us make sure, without pulling the branch to test)

2020-11-10 10:29 UTC, Volfee commented
Thanks Mike nice finding! I have changed the code to use Local.ROOT

Re screenshots: I think, in this case it is a bit difficult to demonstrate change with SS as there is no change to the UI itself, but rather a value in form is populated correctly now ie. 130 instead of 129 when user types 130. 

If you think SS would be useful anyways I can add them to the thread.

2020-11-10 11:33 UTC, mikehardy approved these changes
ok - LGTM - thanks for fixing this!

2020-11-10 11:43 UTC, merged

2020-11-10 11:44 UTC, mikehardy commented
merged, will be out in the next alpha - @Volfee -> 🏆  😄

2020-11-25 18:08 UTC, mikehardy commented
Hello! with the 2.14 release we started accepting donations with the stated goal of accepting money from users to support maintenance and development of AnkiDroid

This PR was included in 2.14, and if you'd like to submit an expense to share in a portion of our hopefully-sustainable monthly disbursement, please read here and do so in the next couple of days:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process

This is our first time handling donations and attempting to compensate anyone with these processes, so please be flexible and patient with us

Thank you for your contribution to AnkiDroid!