Remove MIUI Keyboard Hack Preference
ankidroid/Anki-Android pull request #7669
Opened 2020-11-13 06:30 UTC by david-allison-1

No longer necessary now we have the note editor toolbar.

Related: 43151b618758c80b2bd4b7134f498a56f5b27170
Fixed By: #7124

2020-11-13 14:13 UTC, mikehardy requested changes
a note about orphaning the pref key / cleanup

2020-11-13 14:13 UTC, mikehardy commented on AnkiDroid/src/main/res/xml/preferences_advanced.xml
> -                android:key="enableMIUIClipboardHack"
I think also needs an update to remove the key?

https://github.com/ankidroid/Anki-Android/blob/d1c0906cd3dcda33880752b0fd16e6cb3cd3b5a9/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L1223-L1224

Something like this:

https://github.com/ankidroid/Anki-Android/blob/d1c0906cd3dcda33880752b0fd16e6cb3cd3b5a9/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L1343-L1356

Note that it is hard to pin down exactly when this will go (and thus to get the version code correct) but if you have time to do this now you will know that the next beta version number will have it and that will clear it out for almost everyone, orphaning almost no one and with no real importance if it does

2020-11-13 14:28 UTC, mikehardy commented
I like this change, and it affects strings. There is no rush, never a rush, but I will hold the next (last?) 2.14.0beta for it in order to do a good strings sync and not start developing a strings divergence across the branches yet

2020-11-13 20:16 UTC, david-allison-1 commented on AnkiDroid/src/main/res/xml/preferences_advanced.xml
> -                android:key="enableMIUIClipboardHack"
We haven't done this for any past keys - all of the updates in this routine relate to modifications, rather than removals.

Maintainer's choice - I don't feel it's worth the complexity.

2020-11-14 13:07 UTC, mikehardy commented on AnkiDroid/src/main/res/xml/preferences_advanced.xml
> -                android:key="enableMIUIClipboardHack"
Mmm - cost is slowly growing preferences on people that used the non-default setting for the feature, scaled by rate of addition of features that need preferences and are orphaned over time, vs cost of code in a nasty startup sequence.

Our rate of preference-requiring additions is low, so I tend to agree

2020-11-14 13:07 UTC, mikehardy approved these changes

2020-11-14 13:07 UTC, merged