Deck Picker: Convert the dialog to a Toast
ankidroid/Anki-Android pull request #7687
Opened 2020-11-14 19:45 UTC by bguneys

## Pull Request template

## Purpose / Description
After creating a new deck and opening a dialog menu by long tapping on the recently created deck, then tapping "Custom Study" option on the menu and tapping "Review ahead" option on the newly opened menu and then typing a number greater than 1 as days and tapping "OK" button, an alert dialog with text message "Rename the existing custom study deck first" appears but immediately gets obscured at the back of an another dialog menu.

## Fixes
Fixes #7680 

## Approach
Show a Toast message converting Dialog to Toast.

## How Has This Been Tested?
Android 9

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] Strings resources: All strings added as resources are unique or contain a comment for seemingly duplicate strings to explain the difference between both resources

2020-11-14 19:50 UTC, bguneys commented
![Screenshot_20201114-224047_AnkiDroid2](https://user-images.githubusercontent.com/42909556/99155740-b01f7400-26cb-11eb-96d5-eb4ae51adddb.jpg)

2020-11-14 19:51 UTC, david-allison-1 requested changes
Looks good from an implementation POV, thanks!!!!

One quick code quality improvement and we're good to go

2020-11-14 19:51 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
> +                Toast toast = Toast.makeText(getActivity(), R.string.custom_study_deck_exists, Toast.LENGTH_SHORT);
We have `UIUtils.showThemedToast` which should cut down on the code here.

2020-11-14 20:30 UTC, david-allison-1 approved these changes
Looks good to me, thanks!!

2020-11-14 20:32 UTC, bguneys commented
Thanks for the reply. I added `UIUtils.showThemedToast` but then Toast message is showing at the center of the Activity. Would this be ok for UI design? If not, is there any implementation could you advise to have Toast message showing at the bottom of the screen?

![Screenshot3](https://user-images.githubusercontent.com/42909556/99156401-997c1b80-26d1-11eb-94af-7778416baaf6.jpg)

2020-11-14 20:37 UTC, david-allison-1 commented
> r the reply. I added `UIUtils.showThemedToast` but then Toast message is showing at the center of the Activity. Would this be ok for UI design? If not, is there any implementation could you advise to have Toast message showing at the bottom of the screen?

That's strange... I haven't seen that happen before with `showThemedToast`. 

I'll take a quick look, give me 5 minutes

It'd be better at the bottom (in which case: revert and leave a comment).

2020-11-14 20:45 UTC, david-allison-1 commented
I've checked out the code and the toast appears on the bottom on my API 25 emulator.

It'd be best to include your fix (setting gravity) in `UIUtils.showThemedToast`, so we get consistent behaviour - as far as I'm aware, it  was intended to always be at the bottom of the screen.

@mikehardy Tagging to confirm this seems sensible with you.

2020-11-15 10:51 UTC, Arthur-Milchior reviewed
Thanks for fixing a problem. One small question.

2020-11-15 10:51 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
> +import android.view.Gravity;
Why this import?

2020-11-15 12:32 UTC, bguneys commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
> +import android.view.Gravity;
When I first added `Toast` to show the message, Toast message showed up at the center of the screen in my Samsung Galaxy S8 phone (Android 9). I thought maybe it was because I was creating `Toast` inside DialogFragment, so I wanted to set Toast message position at the bottom of the screen by using `setGravity()` method as a quick fix. This is why `Gravity` import was added. But @david-allison-1 reminded me to use `UIUtils.showThemedToast`. So I replaced my first `Toast` implementation and deleted `setGravity()` method. But I forgot to remove unused imports. In the latest commit ([7e3453b](https://github.com/ankidroid/Anki-Android/pull/7687/commits/7e3453ba76ac39f42d75e04e3d5b2823c1def18b)) I removed both `Gravity` and `Toast` imports  which are unused.

2020-11-17 16:23 UTC, mikehardy approved these changes
Thanks @bguneys! this LGTM and I think if toast display is not gravity bottom then that's a separate issue, a follow up is fine so we can get this in now since we haven't had other reports of unexpected toast gravity

2020-11-17 17:17 UTC, merged

2020-11-25 18:08 UTC, mikehardy commented
Hello! with the 2.14 release we started accepting donations with the stated goal of accepting money from users to support maintenance and development of AnkiDroid

This PR was included in 2.14, and if you'd like to submit an expense to share in a portion of our hopefully-sustainable monthly disbursement, please read here and do so in the next couple of days:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process

This is our first time handling donations and attempting to compensate anyone with these processes, so please be flexible and patient with us

Thank you for your contribution to AnkiDroid!