Replace menu string “Options” with either “Deck options” or “Study options”
ankidroid/Anki-Android pull request #7726
Opened 2020-11-19 15:37 UTC by oakkitten

***WARNING**: although i tested this to the best of my understanding of the app, it has many menus and functionality that i personally don't use so i might have missed something. particularly, i don't have a tablet*

the new strings "Deck options" and "Study options" replace the string "Options" that is ambiguous andd can be confused with "Settings".

## Purpose / Description
the word "options" ("preferences", "settings") when used by itself usually means global settings. i think it helps to clarify the intent behind it otherwise

## Approach
created new strings for "Deck options" and "Study options". the string "Options" (`study_options`) remains as a preference category. as per the wiki i did not rename its key, but i changed the comment. (i think it'd be nice to rename the key also.) in StudyOptionsFragment, the string for menu item `action_deck_or_study_options` is set dynamically.

## How Has This Been Tested?

visually on my device, also ran `gradlew jacocoUnitTestReport`

i did **NOT** test this on a tablet as i don't have one

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings): hopefully didn't miss any https://x0.at/ckl.zip
- [x] Strings resources: All strings added as resources are unique or contain a comment for seemingly duplicate strings to explain the difference between both resources

2020-12-08 17:33 UTC, mikehardy requested changes
Thanks for your patience on this @oakkitten - sorry it took so long to review

I have a comment on the first commit that needs to be addressed, then in general the second commit should be dropped entirely I think, we should never touch `values-NNN/*.xml`, only ever touch `values/**.xml` because the `values-NNN/*.xml` are clobbered automatically by crowdin export/import process

2020-12-08 17:33 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
> +        configureToolbar();
This looks suspect - I can only imagine that we added the null check in there in order to stop a crash or similar. To remove a null check with no associated change to protect against the possibility of null in the same commit can't be right. Even if it is in a following commit it might make later git bisect's while hunting for bugs crash as it is not altered in the same commit

2020-12-08 18:11 UTC, oakkitten commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
> +        configureToolbar();
i removed the null check because if `mToolbar` is `null` the app has already crashed at that point

https://github.com/oakkitten/Anki-Android/blob/1056243bfd742e620b70cfd6adcbe1eec2ccf204/AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java#L193-L197

still this change probably shouldn't be a part of this PR so i removed it

2020-12-08 18:15 UTC, oakkitten commented
as requested, removed the removal of the null check and the commit altering internationalized strings files

2020-12-08 18:23 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
> +        configureToolbar();
oh my - nice link there, haha. Yep indeed, just a littttle silly to null check now that I look at that but thank you for separating concerns regardless :sweat_smile:

2020-12-08 18:27 UTC, mikehardy approved these changes
LGTM - merge!

2020-12-08 18:27 UTC, merged

2021-01-10 21:32 UTC, mikehardy commented
Just a friendly notice (one per person, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for Dec 2020 submissions

Process note:

    At the end of the month, go to our OpenCollective expense form and follow their process to file an expense.
    As this process is new, we have little information on how many people will submit expenses, so we don't know what the total will be. As mentioned in "sustainable" above, we are trying to distribute about 10% of the total balance each month but we are just guessing right now. Please limit your expense to a maximum of 30 hours claimed working on AnkiDroid, and I believe we can support 10USD/hour for those hours, making a maximum expense claim of 300USD. Please include your GitHub or Discord name in the notes so we may verify your contribution.
    We will look at all the expenses and approve all the reasonable ones or work with you to adjust them, at which point OpenCollective (the company) indicates they do transfers twice a week.
    We may - if the total looks much above or below 10% of our total balance goal - reject all of the expenses with specific instructions to raise or lower the amount of hours you may claim to better match our goal.