Add experimental support for dynamic import in Reviewer JS
ankidroid/Anki-Android pull request #7764
Opened 2020-11-23 17:38 UTC by hgiesel

## Purpose / Description
This PR should be seen with a grain of salt: I never worked with Android before, and my last Java experience is ten years back. So see this as a starting point :)

This PR addresses the issue, where the WebView in the reviewer can not load dynamic JavaScript modules via `import("<nameofmodule>")`. This is a really useful pattern in modern JavaScript, because it allows for asynchronous execution.

This is currently not possible on AnkiDroid, because you cannot request modules via the `file` scheme. 

With this PR, the user can use `import('https://appassets.androidplatform.net/<nameofmodule>.js')` to import modules from collection.media; and in fact even use `fetch('https://appassets.androidplatform.net/<nameoffile>')` to dynamically get files from the collection.media directory.

The prefix "https://appassets.androidplatform.net" comes from the custom implementation of WebViewAssetLoader. It seems like android reserves this URL particularly for this purpose. Having to use it is not really beautiful, but it's an OK compromise as I see it.

## Fixes
#7760

## Approach
This uses the [WebViewAssetLoader](https://developer.android.com/reference/androidx/webkit/WebViewAssetLoader) class to enable special handling of the url "https://appassets.androidplatform.net"

## How Has This Been Tested?
No test yet.

## Learning (optional, can help others)
[Docs for WebViewAssetLoader](https://developer.android.com/reference/androidx/webkit/WebViewAssetLoader)
[This is how I came up with overriding PathLoader](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/483)

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [~] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

2020-11-23 18:05 UTC, mikehardy commented
Fascinating - they (google / jetpack library developer) have obviously seen this need, and this looks like exactly the ticket to make things work. I think this style could be merged in here.

I would want to make sure it survives activity restarts in the Android activity lifecycle (member variables may need to be reinitialized, for instance) but first things first: exactly what javascript are you using to import things now in AnkiMobile and Anki Desktop?

I don't find the reserved domain name to be the worst thing in the world but it is a little distasteful. If there was a way we could make the exact same import code work (maybe via some re-writes or something) that would be ideal but I would to see a javascript snippet to think about it

Thanks for proposing this either way - it seems like the path forward @hgiesel

2020-11-23 19:55 UTC, hgiesel commented
> exactly what javascript are you using to import things now in AnkiMobile and Anki Desktop?

This is an example code, which reflects how I load it in my JavaScript library:
```js
var libraryPromise = import(globalThis.ankiPlatform === 'desktop' ? '/__library.js' : './__library.js')
    .then(library => library.initialize())
    .catch(error => console.log('An error occured while executing library:', error))
```

As you can see, even the Anki platforms are not completely uniform.

On AnkiDesktop, you would use `import('/library.js'), because `import('./library.js') would resolve to `http://127.0.0.1:57193/_anki/_library.js` (port is random), which is where anki puts its own files.

On AnkiWeb (the website), it must `./_library.js`, because the reviewer runs on `https://ankiuser.net/study/`, so `/library.js` would resolve to `https://ankiuser.net/_library.js`, which is wrong.

On AnkiMobile both work. It works on a custom website with the url `ankifile://reviewer/`, where `ankifile` is the protocol, `reviewer` is the host, and the path is `/`, which means `./_library.js` and `/_library.js` will point to the same file.

2020-11-23 20:08 UTC, mikehardy commented
Mmm - that's a lot to think about, hey @dae - do you think there's an opportunity to unify this stuff? We can for sure publish a sort of "universal importing" conditional chunk that developers can crib so it will work, but it would be cooler if there was a single way, and it's new enough there probably isn't a lot of installed base that would be perturbed by a change yet

2020-11-23 23:23 UTC, dae commented
`<script src="something.js"></script>` should work across platforms, as it's relative to baseURL which points to the media folder. You should be able to add script tags to the document dynamically if required?

2020-11-24 10:59 UTC, hgiesel commented
There's some major issues with dynamically adding script tags:

Let's say you're in `_script.js` and want to add `_library.js`. First of all, it's quite similar to simply adding the script tag via the template, so you would not even need to do it dynamically (unless of course there are scenarios, where you explicitly wouldn't want the library loaded.

But now, if you do it via dynamically adding the script tag, or adding `<script src="_library.js"></script>` to the template, the result is the same: you do not really now when the library is loaded. Dynamically added script tags are always loaded **async**, which goes for both scenarios, because the way AnkiDesktop adds them to the reviewer WebView already counts as dynamic.

Assuming `_library.js`, adds an object `myLib` to the global object, the only way to check whether if finished loading would be to do the following:

```javascript
// _script.js
if (window.myLib) {
    // execute script
}
```

On a website, you could use the script's `onload` event listener. However, this event listener does not work in data URIs. So you have to rely on continuously checking for `myLib` with `setInterval`.

```js
const timerId = setInterval(() => {
  if (window.myLib) {
    console.log('Loaded!')
    clearInterval(timeId)
  }

  console.log('Not loaded')
}, 100)
```

That can work fine, if the library defines very few symbols. However once you have a bigger library, defining hundreds of symbols, you come across the issue, that rather than defining all symbols at once, the library gradually defines symbols one after another.

So even if the above condition is true, `myLib.utils.func` may still be undefined, and when that symbol is defined, `myLib.anki.tools` may still be undefined. What you get after the timeout is over, is entirely unpredictable. It might also be that an _inner function_, one that is not exported is still undefined. So you happily execute `myLib.anki.tools`, but then it throws an error that `helperFunc` is undefined, because that function is defined a few milliseconds later.

The only thing you can do is increase the timeout, to make it _less likely_ to encounter that issue. But then again, you want your library to load as fast as possible. So that's a dilemma.

---

I experimented a lot, and I think that dynamic importing using `import()` is the only way to reliably load a library and
1. Exactly know when it's done (by using the promise it returns)
2. Do so _fast_
3. Do it in the constraints of data URIs, or file URIs, in AnkiDroids case.

2020-11-28 01:41 UTC, dae commented
Presumably the symbols are defined in order, so you could have a sentinel at the end to know when everything has been loaded. But the root issue seems to be calling import() from Anki library code. Have you tried using a bootstrap js file in the media folder, and doing the imports from there, to make the imports relative to the media folder?

Are you really gaining a lot over using a bundler however? Dynamic imports are still relatively new, and one of the 2.1.35 alternate builds is still on Chromium 56 IIRC. https://caniuse.com/es6-module-dynamic-import

2020-11-28 15:34 UTC, hgiesel commented
> Have you tried using a bootstrap js file in the media folder

That's a good point, but I need "{{Tags}}", and "{{Card}}" as input to my logic, which is why I need to put this bootstrapping into the card template. Anki will replace it with the actual tags / card type, and those are passed to the JS library.

I am also aware of the lack of support on the alternate version, but the market share of pre El Capitan macOS users is now < 3-4%, so it seems reasonable to me.

**However**, I think all of this is kind of missing the point: I am really happy, with how my code currently works in AnkiDesktop (especially with the coming v2.1.36), so I don't really see any need for change there, neither on my side, nor on Ankis. Which is why this issue / PR is in the AnkiDroid repo.

The idea of unifying the import / fetch URL will probably fail with Ankidroid itself: The only way AnkiDroid could use a syntax like `import('./_library.js')`, if you would intercept **all** requests going out with the `file:` protocol, and rewrite them to go to `https://appassets.androidplatform.net` instead. You basically would have to change the default protocol from `file:` to `https:`, which I don't think is feasible.

> "universal importing" conditional chunk

I think this is what developers could use:

```js
const getAnkiPrefix = () => globalThis.ankiPlatform === 'desktop'
    ? ''
    : globalThis.AnkiDroidJS
    ? 'https://appassets.androidplatform.net'
    : '.'

import(`${getAnkiPrefix()}/_library.js`)
fetch(`${getAnkiPrefix()}/_resource.xml`)
```

2020-11-28 17:00 UTC, mikehardy commented
🤔  even though this would sort of codify a hack, perhaps we could put that conditional import chunk into the template itself such that we expose - as new supported symbol in the card - the prefix for imports?

Seems ugly but we (developers/maintainers) would be in control of the symbol's resolution so would not hurt us, would take load off javascript API developers ? Seems like it would be okay as a developer experience both for the apps and the JS API users

2020-11-28 17:51 UTC, hgiesel commented
It sounds like a nice idea, but it would feel more like a drop in the ocean.

For example, [this is the boilerplate](https://github.com/SimonLammer/anki-persistence/blob/master/script.js) for _persisting_ data within JavaScript from the front side of the card, to the back side of the card. And [this is my rewrite in TypeScript](https://github.com/hgiesel/closet/blob/master/src/anki/persistence.ts).

Another common issue is that on some platforms, the WebView is reused (e.g. on AnkiDesktop), whereas on others, a new WebView is used for each card (e.g. AnkiDroid).

If we can ***enter dream world*** for one second, than the optimal solution would be a common spec between the Anki platforms, to define an object, let's say `AnkiAPI`, which would offer functions, to execute common actions, like `AnkiAPI.persistData(myData)`, or `AnkiAPI.importLibrary(myLibSpecifier)`.

I noticed that AnkiDroid has `AnkiDroidJS`, which is really cool, but as you soon as you want to target all platforms, you're out of luck.

2020-11-28 18:18 UTC, mikehardy commented
Philosophically:

- I just checked and AnkiDroid appears to have 35,482 lines of code as measured by our coverage tool, each one a drop in a mighty ocean
- lack of persistence across card flip is indeed fairly absurd, great that you appear to have solved it in a general way!
- AnkidroidJS is indeed cool - important to know that as a design goal I would like it to be cross-platform but the primary developer here is AnkiDroid-specific. Having it be AnkiDrod-specific is an anti-goal though, my dream world has something like your library functions integrated here and upstream and exposed as "AnkiJS API" indeed, perhaps with some AnkiDroid-specific extensions, but with compatibility as a core value

There was a fair bit of effort put into AnkidroidJS API focused on the developer experience with regards to what the API supports (or does not) and registering JS API users along with what they are using, so we could support API development without having end-user issues rain on us because a JS API consumer wasn't forward-compatible and our API progress caused plugin failures for users

As long as that general idea is respected, I don't see why we can't distribute a platform library of foundational components, or at least support a one-tap install of a 3rd party project (like yours) that does the same. Stated differently: I like the idea of "JS Addons" as a cross platform thing with support for them in form of discovery, install, enable/disable, delete. Possibly even with Addon dependency specification so that users who want to install a plugin that depends on - for example - your project of foundational components is easy

No reason not to enter a dream world - for AnkiDroid we're completely blocked on native add-ons but they are our biggest request. We also can't easily change the reviewer experience without angering install base. A JS API can solve both, and I want to support the general direction of cross-platform, full-featured JS development in the ecosystem

2020-12-01 13:12 UTC, hgiesel commented
So I see two ideas here: a cross-platform `AnkiJS` API for developers, and a platform for distributing JS add-ons.

Concerning `AnkiJS`, it will ultimately be up to Dae. I can send PRs to AnkiDesktop, but I can't send PRs to AnkiMobile or AnkiWeb, which means it will also be more work for him.

Concerning a distribution platform: I already developed an Anki add-on with that idea in mind, called [Asset Manager](https://ankiweb.net/shared/info/656021484). The idea being, that users can develop the JavaScript components, without reinventing the method to insert the JavaScript into the template (or register it on hooks) for each add-on.

2020-12-01 13:31 UTC, mikehardy commented
Agreed they are 2 things (consistent DX w.r.t. symbols / functions defined, easy DX w.r.t. versioning, distribution, update checks, user mgmt of JS plugins) and somewhat orthogonal. I'd like both

AssetManager looks really nice - solves problems I wouldn't have even thought about until I'd seen the first version of what I had in mind! Appears 2-3 steps ahead. I'd love to see this as a core feature with the idea that developing JS for the Anki ecosystem is a supported thing and thus that managing the JS scripts is a 1st class action

Getting this right so it's a wow feature as opposed to confined to only serious adventurers will require some thought, agreement in general (@dae :-) ) and then harmony. Damien I haven't heard you speak much about your view of JS development in templates - maybe I missed it as I haven't searched - but what do you think? JS development for templates could be promoted, and mgmt of scripts as a 1st class thing? It's the only way the mobile platforms get "add-ons" (or that AnkiDroid can ever get a modern UI I think...) so we're pretty keen over here.

2020-12-03 09:12 UTC, dae commented
I think JS in the Anki ecosystem has a lot of potential, but I'm keen to tread carefully:

- Python add-ons are tightly bound to Anki's codebase, making it very difficult to make changes/refactor Anki without some of them breaking. And as users grow to depend on particular add-ons, if the add-on authors don't keep the add-ons up to date, they act as anchors keeping people stuck on older Anki versions, fragmenting the ecosystem. I am concerned that embracing JS add-ons will introduce similar problems if we're not careful.
- JS (and even fancy CSS) in shared decks also causes a fair few problems, such as when the deck author has not tested on all platforms, not tested on night mode, or they've done something that breaks in an update.

Breakages due to incompatible approaches by the different clients could be improved by having them share more code - the Rust and TS work has been a step in that direction, and it probably makes sense to move things like the reviewing screen (or at least parts of it) into a shared TS library in the future too. 

Moving JS/CSS out of shared decks and into a separate distribution mechanism may improve things somewhat, as you could have multiple decks sharing the same layout, and update one independently of the other.

2020-12-03 11:30 UTC, mikehardy commented
I agree on the risks, there is no way to support an API without having upgrade problems, or client maintainership issues etc. We spent a great deal of time on semantic versioning, hook usage registration, and facility to warn users when there were incompatibilities (e.g., you can't use a hook unless register w/an email the hook usage and if we break semver on the hook we'll toast to the user that the code needs help and here's the email...). 

All towards the ability to move right along with regards to API management without worrying too much about fragmentation (assuming we manage symbols well). It's all use-at-your-own-risk but does allow for the possibility at least

We already have complete a replacement reviewer proof of concept if you enable fully immersive mode and install the script: https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API#sample-decks (plus you can see the related PRs to see the journey to get there

So, while not disagreeing, since mobile has no other avenue for add-ons at all and catering to vocal minorities causes what should be add-ons (IMHO) to get into our main codebase, we are already going there. The only questions are on symbol harmony and UX/DX

2020-12-03 12:14 UTC, infinyte7 commented
Please correct me if wrong.
JS addon can be used for UI related stuff. But when it comes to modify decks data or create new data then separate app for AnkiDroid and AnkiMobile should be using using API provided by the apps. But in case of desktop addons can be used on the system. 

[Progress bar addon](https://github.com/infinyte7/Anki-Custom-Card-Layout/tree/master/JS%20addon) for AnkiDroid. It can be implemented into one deck but for other decks it has to copy to deck that share same note types. What information need for implementing it? I have implemented using (New, Learn, Review) card counts provided by AnkiDroid JS API. So to make available to Anki ecosystem then Anki desktop should have API to access those numbers.
(New, Learn, Review).

I have tried to access the data using jQuery. But it is only accessible when bottom tootbar focused and using [web inspector addon](https://ankiweb.net/shared/info/31746032).
```
$(".new-count").text()
$(".learn-count").text()
$(".review-count").text()
``` 

Other commands that I have compiled that may push one step closer to Anki ecosystem.
It can be used when user reviewing on Desktop where AnkiDroid JS API implemented.
```
pycmd('ans')
pycmd("ease1")
pycmd("ease2")
pycmd("ease3")
pycmd("ease4")
pycmd("defease")

pycmd("edit")
pycmd("more")

pycmd('decks')
pycmd('add')
pycmd('browse')
pycmd('stats')
pycmd('sync')
```

2020-12-03 23:56 UTC, dae commented
@infinyte7 Those are implementation details, not a published API, so they may break when various screens are updated in the future. At the moment you will need to rely on Python add-ons to do most extending of the computer version.

@mikehardy Happy for you guys to forge ahead with an AnkiDroid-specific implementation for now; we can return to the topic of a unified API at a later date, hopefully after the clients are sharing more code.

2020-12-08 18:20 UTC, mikehardy commented
Hey @hgiesel - spinning through PRs this morning and I see this one - to re-focus the discussion then:

If you had permission to design the "ideal future world", with the idea that it *would* be cross-platform if it was a successful (used + maintainable) API, what would that do to this PR? Would you go farther (modifying some things in card.js to install default / anyone-can-use them objects that did useful things)? Or would this PR still look the same and "going farther" would be something different?

Stated slightly differently, specifically for this PR: is it valuable to review it for potential merge now, after the discussion here?

Thanks!

2020-12-08 21:59 UTC, hgiesel commented
I would say, that at this point it doesn't make sense to go for a better user API. As it says in the [Anki Manual](https://docs.ankiweb.net/#/templates/styling?id=javascript):

> Javascript functionality is provided without any support or warranty

From all my research, I'm pretty confident, that this approach is the only one to implement this functionality. So what this PR represents for me is the "barebone" implementation, or as the title actually says "experimental support".

If at some point Damien considers to make an official Anki JavaScript API™, we can build some syntactical sugar on top of this implementation (or even revise it, if by then the Android world has something new).

However, right now, having:

```javascript
const getAnkiPrefix = () => globalThis.ankiPlatform === 'desktop'
    ? ''
    : globalThis.AnkiDroidJS
    ? ankiDroidGetAnkiPrefix()
    : '.'
```

VS.

```javascript
const getAnkiPrefix = () => globalThis.ankiPlatform === 'desktop'
    ? ''
    : globalThis.AnkiDroidJS
    ? 'https://appassets.androidplatform.net'
    : '.'
```

Would be no better, but only mean "one more symbol".

2020-12-08 22:25 UTC, mikehardy commented
Okay - thanks for replying, I'll review it from that perspective then and hopefully merge

It does seem though that while the Anki Manual does say that (and should...) we are approaching that moment where if we design an API that handles API-management concerns and is useful + adopted, the manual statement could be revised to something more like "This specific Javascript API is supported if you follow the rules set out here...". We are going that way in AnkiDroid anyway

2020-12-08 23:59 UTC, dae commented
The problem Mike is it's not just about an explicit API Anki(Droid) exposes - users effectively have access to the entire Javascript/DOM/CSS API surface, which as you know are huge and vary across platforms and platform versions (eg arrow functions, flexgrid, computed margins, etc). Even without any Anki-specific functionality exposed, it's easy to write code that breaks when moving between platforms, and end users assume that's Anki's fault.

2020-12-09 02:22 UTC, mikehardy commented
This is not intractable though. Part of the platform support could be a check for minimum acceptable support. For instance I just clipped off android api20 and below and now ankidroid can say if you use our Javascript API you need to set chrome or Firefox as your webview and we can check their versions and set a minimum then allow es6+ or whatever. Different or less than that and we can throw an unsupported toast first access every time.

The majority case is easy I think and the corner case gets a warning and a caveat emptor.

Why not?

2020-12-09 07:42 UTC, dae commented
Unless we reach a point where all clients have an identical environment, I think cross-platform issues are going to be difficult to avoid completely. And even putting them aside, there will still be breakages when webviews get updated, or the way those webviews are presented is changed in future Anki(Droid) updates. Things like https://forums.ankiweb.net/t/failed-to-get-computed-style-with-japanese-kanji/5630 crop up fairly frequently, and are a pain to support - even if you tell the user that it's the deck author that needs to fix it, it's not uncommon for them to argue the point "but it worked before" or "it works on my other device".

I totally get the appeal - if you make it easier to extend the program, it's easier to say no to niche requests that come in, reducing maintenance burden. But over the years I've come to feel it's much less of an easy win than I thought it was, as it also introduces a whole new spectrum of issues, and as the code is outside of the core codebase, it's harder to enforce standards or update when things change. There are some people who do some amazing things with add-ons/JS, and support their creations well. But there are also a lot who hack something together, share it, and disappear. They're totally within their rights to do so, but it makes support a headache, and makes it harder to update things without the risk of something breaking.

2020-12-09 15:19 UTC, mikehardy commented
I hear you, I really do. 

I have no problem telling these people:

>  "it's not uncommon for them to argue the point "but it worked before" or "it works on my other device"." 

'Sorry that's the way it is'. I assert they are <1% and I want to cater to the 99

I repeat we have done a great deal of work with the JS API we cooked up here such that you must register usage of the hooks before they do anything, and registration involves specifying what version of the hook you expect and providing contact information.

That means us telling them 'I'm sorry that's the way it is' becomes fully automated and brings with it a helpful pointer to the author. Whether they actually support it not isn't my concern but users will have their expectations set appropriately and their irritation (if it comes to pass...) directed at the right person.

Most of this is a direct reaction to the Python add-on experience, I think it addresses the concerns as the whole point is to address the concerns.

You might like https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API#initialize

2020-12-12 04:04 UTC, dae commented
It's a bad experience for the user when things break on upgrade or platform switch, and for every user that reports an issue or argues the point, there are multiple users who suffer the same issues in silence. And the users are not to blame here - they're just downloading shared decks, and not aware of the choices the deck authors have made. My fear is that by encouraging JS usage, it will turn this into an even bigger problem than it already is. 

It's great that AnkiDroid has tried to address some of these issues in the design of its API, but I'm afraid I don't think it's going to solve the problem on its own. There's nothing stopping JS authors from being lazy and accessing functions without checking if they're available first. And as mentioned earlier, this only protects against explicit AnkiDroid APIs, and not against all the other things that can go wrong in JS/CSS.

2020-12-12 13:50 UTC, mikehardy commented
The methods do not return results until registration happens, compliance with registration is mandatory

2020-12-15 10:55 UTC, infinyte7 commented
Using discussion at 
https://forums.ankiweb.net/t/how-can-i-get-implement-this-to-addon-to-get-card-counts/5787

I have implemented basic Anki JavaScript API. But I don't know how much fragile is it?
https://github.com/infinyte7/AnkiJS-API

Also finding solution for registering the api so when developer provide api then api get available to be called? (Passing string from reviewer to addon)

2020-12-15 16:57 UTC, hgiesel commented
@mikehardy Is there anything else I can help to get this merged? I think an API on top of it can be considered at any point in the future, but for now, the bare functionality suffices. It would nice if I could tell my users that they can use my add-on with the upcoming AnkiDroid 2.15 :)

2020-12-15 17:57 UTC, mikehardy commented
Sorry @hgiesel - I don't think this has pending items for you - I'm trying to respond to user help requests and merge things but I'm on vacation through tomorrow so I haven't gotten everything :-). I'll scan the queue when I get back though and certainly consider this

2020-12-20 02:00 UTC, mikehardy requested changes
I just re-read this and it looks okay with exception of a question on version of webkit specified

2020-12-20 02:36 UTC, hgiesel commented on AnkiDroid/build.gradle
> +    implementation 'androidx.webkit:webkit:1.2.0'
I think I copied this from the docs on `WebAssetLoader` I were reading, which were the docs for 1.2.0. I'll update to 1.4.0.

2020-12-20 02:56 UTC, mikehardy approved these changes
Great - thanks - marked pending merge as we lost Travis CI support and I haven't migrated over to GitHub Actions yet, I have to pull it and run it through locally 😞

2020-12-20 18:49 UTC, mikehardy commented
Checks out in local testing - good to go!

2020-12-20 18:49 UTC, merged

2021-01-30 06:07 UTC, david-allison-1 commented
Has this been tested with inputting a path of `../` allowing a user to access files outside the media directory?

2021-02-03 23:01 UTC, hgiesel commented
*Technically*, this [should not be possible](https://tools.ietf.org/html/rfc3986#section-5.2.4). A url can not start with `../`, but only with `/../`, which should be resolved to `/` (similiar like entering `cd /../` in shell, will make you end up in `/`).
However,  I can't say I tested it, or at least I don't remember.