NF: using isDynamic when possible for readability
ankidroid/Anki-Android pull request #7827
Opened 2020-12-05 10:48 UTC by Arthur-Milchior

isDynamic is literally defined as checking whether ODid is non null. So this makes no change, appart from the fact that it gets easier to read

2020-12-05 11:16 UTC, david-allison-1 approved these changes
LGTM

2020-12-05 13:27 UTC, mikehardy requested changes
The only thing I don't like about this is that "card.isDynamic" semantically says to me "this card is dynamic" but what it really means is "this card is in a dynamic deck". Seems like the whole method should be named "inDynamicDeck"

It's a non-libanki method, so we can change it, may I ask for this to a little farther and rename like that?

Also, what is the comment on isDynamic saying? "I have cards in my deck...." how is that relevant to a developer? :thinking:

2020-12-05 14:28 UTC, david-allison-1 commented
> Also, what is the comment on isDynamic saying? "I have cards in my deck...." how is that relevant to a developer? 🤔

God, I have no clue on that one - kill it with fire

2020-12-05 14:29 UTC, david-allison-1 commented
> > Also, what is the comment on isDynamic saying? "I have cards in my deck...." how is that relevant to a developer? 🤔
> 
> God, I have no clue on that one - kill it with fire

EDIT: Actually... this needs to be better stated, rather than removed. I'll put in a PR

2020-12-08 14:29 UTC, mikehardy requested changes
please change 'isDynamic' to 'inDynamicDeck' so it's meaningful when encountered in code, then I can merge

2020-12-08 14:30 UTC, mikehardy commented
also will likely take a conflict in that area when I merge #7829 unless rebased after, merging that in just a minute..

2020-12-09 11:15 UTC, Arthur-Milchior commented
Done

2020-12-09 13:10 UTC, david-allison-1 requested changes

2020-12-09 13:10 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
> +    public boolean isInDynamic() {
I don't think `isInDynamic` works well, either `isInDynamicDeck` or `inDynamicDeck` as suggested by Mike would be more readable.

2020-12-09 15:01 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
> +    public boolean isInDynamic() {
there is something to be said for java method naming conventions, and I like the 'isNNN' naming Arthur went for. 'isInDynamicDeck' is the most semantically precise. Now that I'm pulling these things locally and running them anyway (since travis isn't working for us) I just did this and repushed so there won't be any more back and forth -> merging

2020-12-09 15:02 UTC, mikehardy approved these changes

2020-12-09 15:12 UTC, merged