Delete a method never used
ankidroid/Anki-Android pull request #7842
Opened 2020-12-08 05:35 UTC by Arthur-Milchior

A quick search in git history shows that the method `previewCards` was introduced in 2012 in 2f3ea8868ce37534b1d3b7fee1c7f0c9fb1edbfa and has never been used since. I can't find a single time where `previewCards(` appears in the code base, appart when I did some changes such as replacing ints by constant.

As far as I understand, this is unrelated to previewing as we consider it today (it would be hard, in 2012). It returns instead the card that should be shown to the user if they asked to preview cards. If the user was creating a card, then it would show all cards generated. If the user was asking to edit the cards it would show already existing cards. If the user was trying to edit a note type, it would show all card types.

David called my attention on the fact that it's not used in https://github.com/ankidroid/Anki-Android/pull/7271#pullrequestreview-546721128 and I suggest to delete it instead of trying to figure out the correct way to edit a function which is never called

2020-12-08 12:46 UTC, david-allison-1 requested changes
Can you mention the names of the methods/types which were deleted in the commit message, this will allow a user to more easily grep the git log and find where they were removed.

2020-12-08 15:47 UTC, Arthur-Milchior commented
Done

2020-12-08 16:44 UTC, mikehardy requested changes
The commit message has a typo in the method name and first commit doesn't have the name haha :sweat_smile:

2020-12-09 06:50 UTC, Arthur-Milchior commented
oops

2020-12-09 13:25 UTC, david-allison-1 approved these changes

2020-12-09 13:42 UTC, mikehardy approved these changes
LGTM :-)

2020-12-09 17:44 UTC, mikehardy commented
de-conflicted while checking PRs locally, passes local testing

2020-12-09 17:44 UTC, merged