Counts picker
ankidroid/Anki-Android pull request #7922
Opened 2020-12-20 07:25 UTC by Arthur-Milchior

There is an accessibility problem, which I believe to be a problem related to unexpected behaviour, so this is a bad fix.

Clicking on the counts in the deck picker has an action, which I find surprising. There is no way to know what clicking will do, and it should be described for accessibility. I believe to be honest that it should actually be removed and if options are actually that useful, a more natural way to get to them should be used.

Is there a way to know the number of deck option page opened in ankidroid on small screen ? I.e. the number of cases where it's opened in it's own page, and not only because it's a mandatory step up to the reviewer?

2020-12-20 13:59 UTC, mikehardy commented
In the analytics (which I believe you have access to), you can filter on screen size, and then search for specific activities, it should be possible to say what percentage of sessions use this. It does make more sense on large screens yes. I know some people use this.

2020-12-20 14:01 UTC, mikehardy requested changes

2020-12-20 14:01 UTC, mikehardy commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="deck_picker_counts">Open the deck options. Show the number of card to see today.</string>
It is not the deck options page that opens though is it? It is more like a deck information page

2021-01-11 16:25 UTC, mikehardy requested changes
easy string fix here then we may merge

2021-01-11 16:25 UTC, mikehardy commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="deck_picker_counts">Open the deck options. Show the number of card to see today.</string>
```suggestion
    <string name="deck_picker_counts">Open the deck overview page containing the number of cards to see today.</string>
```

2021-01-13 14:49 UTC, mikehardy commented
@Arthur-Milchior I think this one just needs a conflict resolution and addressing the comment above (should be quick?) and it's good to go

2021-01-13 19:10 UTC, Arthur-Milchior commented
done

2021-04-24 03:28 UTC, david-allison-1 requested changes
I don't feel these belong in `core`. Otherwise LGTM

2021-04-24 03:28 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="deck_picker_counts">Open the deck overview page containing the number of cards to see today.</string>
I don't feel we need to block a translation release on these strings

2021-04-24 03:28 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="deck_picker_lrn">Number of cards in learning in this deck.</string> <!-- This is as simplification. It depends on sched v1 1 or 2, may count repetition but only cards due now are co
We're getting rid of SchedV1, so this doesn't worry me

2021-04-24 03:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="deck_picker_counts">Open the deck overview page containing the number of cards to see today.</string>
Oh, I didn't know core meant it would block. In this case, you're perfectly right

2021-04-24 03:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="deck_picker_lrn">Number of cards in learning in this deck.</string> <!-- This is as simplification. It depends on sched v1 1 or 2, may count repetition but only cards due now are co
Do you want any action from me here?
I changed the comment. It can get deleted later. I still prefer to keep note of approximation, even if it's acceptable here

2021-04-24 04:27 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="deck_picker_lrn">Number of cards in learning in this deck.</string> <!-- This is as simplification. It depends on sched v1 1 or 2, may count repetition but only cards due now are co
Nope, just a comment

2021-04-24 04:28 UTC, david-allison-1 approved these changes
LGTM

2021-04-24 14:41 UTC, mikehardy approved these changes

2021-04-24 14:41 UTC, merged