Field name
ankidroid/Anki-Android pull request #7964
Opened 2020-12-27 10:35 UTC by Arthur-Milchior

Anki trim field name when they are added/renamed (but not when they already exists). 

Assuming https://github.com/ankitects/anki/pull/869 gets merged, this PR will get more commits, unless it gets merged quickly.

2020-12-27 15:22 UTC, mikehardy requested changes
I need to modify how codecov integration adds comments, they are informative in that these lines are not covered and it would be nice to have a test that covered them and checked the new trim case, but they are distracting in review

at any rate, seems fine just the trivial annotation import thing

2020-12-27 15:22 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
> +import org.jetbrains.annotations.Nullable;
No jetbrains Nullable :-), this is an AndroidStudio trick where it pulls in jetbrains annotation before android annotation, might be a preference somewhere so it never does it

2020-12-27 15:22 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
> +import org.jetbrains.annotations.Nullable;
On the plus side the lint check did fail it so it was noted automatically :-)

```

  /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java:48: Error: Use androidx.annotation.NonNull and androidx.annotation.Nullable. See explanation for IDE-level fix [InconsistentAnnotationUsage]
  import org.jetbrains.annotations.Nullable;
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  
```

2020-12-27 15:47 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
> +import org.jetbrains.annotations.Nullable;
Automation is awesome - The Android Studio explanation shows:

https://github.com/ankidroid/Anki-Android/blob/1f785c1b8c324266fdf652e84c9d9309d7278392/lint-rules/src/main/java/com/ichi2/anki/lint/rules/InconsistentAnnotationUsage.java#L37-L38

2020-12-27 15:48 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
> +import org.jetbrains.annotations.Nullable;
I do love externalizing memory, that is a fantastic error message haha

2020-12-28 01:39 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
> +import org.jetbrains.annotations.Nullable;
Corrected

2020-12-28 01:59 UTC, mikehardy approved these changes

2020-12-28 01:59 UTC, merged