Factorize mod schema
ankidroid/Anki-Android pull request #7965
Opened 2020-12-27 12:30 UTC by Arthur-Milchior

There is a lot of code duplication for each changes that need a full sync. I factorize it.

Furthermore, I discovered that the app did not ask the user to confirm whether they want to confirm something when they need to confirm they want a full sync. I changed it so that it asks to confirm both.

Actually, asking for confirmation before asking the user to enter a name for a field would make sens too.

2020-12-28 03:36 UTC, david-allison-1 reviewed
At a cursory glance, looks good, I'll need to go through it with a fine toothcomb later

Unit tests would be nice, since they're flagged by our coverage tooling

2020-12-28 03:36 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +                            throw new RuntimeException(cmse);
It is very occasionally - more logging in this area would be appreciated as I don't see how it's possible

2020-12-28 03:36 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +    protected void executeSchemaModified(@NonNull SchemaModifier fn) {
Implementer's choice: This might be more readable as a builder

2020-12-28 08:13 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +                            throw new RuntimeException(cmse);
Timber log, or send exception to server ?

2020-12-28 08:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +    protected void executeSchemaModified(@NonNull SchemaModifier fn) {
I don't see the interest of the builder when there are so few members and one is mandatory. I'm not convinced here

2020-12-28 08:17 UTC, Arthur-Milchior commented
I'll take a look to figure out how to test activities when I'm done with templates

2020-12-31 01:45 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +                            throw new RuntimeException(cmse);
Timber logs - this currently crashes, posting logcat and the logs will be usable in debugging

2020-12-31 02:03 UTC, david-allison-1 requested changes
I haven't had the time to look through all of these, I'm not confident that this will be bug-free (or ever was in the first place), and testing, or more analysis may be appropriate for some of the harder cases.

2020-12-31 02:03 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
> -                            dismissContextMenu();
dismissContextMenu is no longer called

2020-12-31 02:03 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
> +                                TaskManager.launchCollectionTask(new CollectionTask.RepositionField(mMod,
unsure about this one

2021-03-24 19:15 UTC, Arthur-Milchior commented
This was clearly not meant to be closed. I understand it need more tests, and I need to understand how to test activities. But avoiding code duplication is still very relevant

2021-03-24 19:16 UTC, Arthur-Milchior commented
@david-allison-1 If I removed the cases where you have doubt and did a PR containing only the cases that are easy to check for NF, would you accept it?

2021-03-24 19:43 UTC, david-allison-1 commented
Definitely

2021-03-30 02:06 UTC, Arthur-Milchior commented
I removed the elements where you added comment. We should first commit #8390 and #8391

2022-08-23 21:28 UTC, david-allison commented
@Arthur-Milchior Would you be happy to close this? 

Now we're in Kotlin this can be done in a much nicer manner.

2023-03-07 20:37 UTC, closed without merging