"Unknown field" message gets translated
ankidroid/Anki-Android pull request #7976
Opened 2020-12-28 10:09 UTC by Arthur-Milchior

No idea why this text was not localized.

2020-12-28 10:26 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java
> +        assertThat(c.q(), containsString(getTargetContext().getString(R.string.unknown_field, "|Front")));
Consider keeping this as a hardcoded string

2020-12-28 10:36 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java
> +        assertThat(c.q(), containsString(getTargetContext().getString(R.string.unknown_field, "|Front")));
I thought that, in travis and in @mikehardy's test system, there were localized test. If so, this would fail when the translation are added in crowdin

2020-12-28 11:21 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java
> +        assertThat(c.q(), containsString(getTargetContext().getString(R.string.unknown_field, "|Front")));
`@Config(qualifiers = "en")` can be used to avoid issues.

The main question is the layer that we want to test. I feel having this as a slightly more brittle end-to-end test is worth the risk of breakages due to string changes.

2020-12-28 13:35 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java
> +        assertThat(c.q(), containsString(getTargetContext().getString(R.string.unknown_field, "|Front")));
we already have a couple english hard codes on purpose for the unit tests to lock them to a specific language, keeping unit test language expectationt hard coded and adding a qualifier works for me

2020-12-28 13:37 UTC, mikehardy requested changes
add the config qualifiers to keep the tests simpler and this can go in
good catch!

example https://github.com/ankidroid/Anki-Android/blob/3c562a8a8a5996e6831d6498ad00d29aac5e511f/AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java#L86-L92

2020-12-28 16:45 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="invalid_template_short">{{Invalid template}}</string>
Is `{}` code, or configuration? (If a user changes this character, will things break?)

2020-12-28 16:46 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java
>                      return "Error in filter " + mod;
Isn't this also translatable?

2020-12-28 16:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="invalid_template_short">{{Invalid template}}</string>
This is neither code nor configuration. Those curly brackes are hard coded, and if a field is missing, it is added to the question/answer

I can keep them in code instead of translation file, we can also decide to remove them. I don't assume they have any specific meaning in English, and so there is no strong reason to translate them.

2020-12-28 16:55 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java
>                      return "Error in filter " + mod;
You're totally right. I missed it. I didn't do a thorough search and only corrected what I found

2020-12-28 17:21 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="invalid_template_short">{{Invalid template}}</string>
If they won't cause a functional change if a translator changes them, lets leave it as it is.

2020-12-31 16:29 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java
>                      return "Error in filter " + mod;
@Arthur-Milchior I think this is just waiting on your correction - no pressure though it's holidays everywhere obviously :-)

2021-01-11 16:09 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java
>                      return "Error in filter " + mod;
@Arthur-Milchior another ping on this one - I think we are missing one extra translation here then we may merge

2021-01-12 04:22 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java
>                      return "Error in filter " + mod;
Done

2021-01-12 04:24 UTC, Arthur-Milchior commented
Please note that https://github.com/ankidroid/Anki-Android/pull/7980 will delete the code using the two first strings. In this other PR, while I ported card generation rules I also ported the error message from upstream, since they are more descriptive. This means that both PR will conflict and if 7980 is merged, the only remaining change from this PR is actually "Filter error"; which is an error I can't even reproduce on my phone as I don't know how to make our current filter fails, and I don't expect to be able to do so until we allow for more filters with javascript

2021-01-12 12:16 UTC, mikehardy commented
@Arthur-Milchior This one is ready for patch-up after the big template generation change just went in

2021-01-13 00:07 UTC, Arthur-Milchior commented
Done

2021-01-13 14:48 UTC, mikehardy approved these changes

2021-01-13 14:48 UTC, merged