Fix some deprecations
ankidroid/Anki-Android pull request #8026
Opened 2021-01-18 23:22 UTC by TacoTheDank

### 1st commit
- Update the NDK

### 2nd commit
- Some miscellaneous code cleanup

### 3rd commit
- Fix a bunch of deprecations
- Use some Compat stuff

### 4th commit
- Remove other redundant Compat stuff

2021-01-19 13:48 UTC, mikehardy approved these changes
These LGTM thanks @TacoTheDank  - they touch a few areas that I know @david-allison-1 put in for compat stuff, so as that is mopped up I'm going to ask him for a quick scan, but if it were just me I'm +1 and would merge FWIW

2021-01-19 14:29 UTC, david-allison-1 requested changes
At a skim, looks good, thanks!

I'll aim to get through the rest by the end of today. Solely nitpicks here.

There are a few cases of `if (API >= 21)` which we can remove

One item has been flagged for re-testing as it may be a functional change. I haven't had the time to look into the impact

2021-01-19 14:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +    public GestureDetector getGestureDetector() {
✔️ designed for Jellybean MR1

2021-01-19 14:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP && animationEnabled()) {
We can remove this constant condition - should always be >= 21

2021-01-19 14:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                return cm.isActiveNetworkMetered();
✔️ Only required for API 16

2021-01-19 14:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.java
> -    private Locale getLocale() {
LGTM - same as ConfigurationCompat.getLocales / LanguageUtil.getLocaleCompat

2021-01-19 14:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.java
> +        return getString(R.string.time_span_decimal_seconds, String.format(LanguageUtil.getLocaleCompat(getResources()), "%.2f", timeInMs / 1000d));
ℹ️ nit: can you keep `getLocale()` here and change the implementation of `getLocale()` to: `LanguageUtil.getLocaleCompat(getResources())`.

It cuts down on line noise

2021-01-19 14:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
> +        ActivityCompat.recreate(this);
⚠️ This is a functionality change on older platforms to emulate Android Pie. Unknown what it entails. May warrant investigation

2021-01-19 14:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java
> +        return InputConnectionCompat.createWrapper(inputConnection, editorInfo, (contentInfo, flags, opts) -> {
LGTM - import change

2021-01-19 16:11 UTC, TacoTheDank commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
> +        ActivityCompat.recreate(this);
I'll revert it for now if you wish, just to be safe. Then this can be investigated separate from this PR :)

2021-01-19 16:28 UTC, TacoTheDank commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP && animationEnabled()) {
👍

2021-01-19 16:34 UTC, TacoTheDank commented on AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.java
> +        return getString(R.string.time_span_decimal_seconds, String.format(LanguageUtil.getLocaleCompat(getResources()), "%.2f", timeInMs / 1000d));
@david-allison-1 Wouldn't that be unnecessary extra code, though? The `getLocale()` method exists in both CardInfo and Collection. I think we should have the Compat method defined in one util class for usage throughout the project to cut down on duplicate code.

2021-01-20 05:15 UTC, david-allison-1 requested changes
Nothing worrying, one API 21 change. Rest looks good! Thanks

BTW, were you using a tool to find these, or do you have a great knowledge of the Compat APIs?

2021-01-20 05:15 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.java
> +        return getString(R.string.time_span_decimal_seconds, String.format(LanguageUtil.getLocaleCompat(getResources()), "%.2f", timeInMs / 1000d));
The `LanguageUtil` method makes sense, but keeping the local method `getLocale()` is useful in reducing line noise.

The knowledge that the locale requires a `Resources` isn't necessary/relevant knowledge for the linked line and obscures the intention of the line (string formatting).

2021-01-20 05:15 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        mCardsButton.setText(HtmlCompat.fromHtml(
✔️ LGTM

2021-01-20 05:15 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP && animationEnabled()) {
ℹ️ Ditto, no longer necessary

2021-01-20 05:15 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
> +        return HtmlCompat.fromHtml(withFixedNewlines, HtmlCompat.FROM_HTML_MODE_LEGACY);
✔️ LGTM

2021-01-20 05:15 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/FieldState.java
> +            l.setId(View.generateViewId());
✔️ Fixed in API 17

2021-01-20 19:11 UTC, TacoTheDank commented on AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.java
> +        return getString(R.string.time_span_decimal_seconds, String.format(LanguageUtil.getLocaleCompat(getResources()), "%.2f", timeInMs / 1000d));
🤔 I see...

2021-01-20 19:29 UTC, TacoTheDank commented
> BTW, were you using a tool to find these, or do you have a great knowledge of the Compat APIs?

Just general knowledge :)

2021-01-20 19:32 UTC, david-allison-1 approved these changes
LGTM, thanks!

2021-01-23 19:59 UTC, merged

2021-01-25 14:45 UTC, TacoTheDank commented
Thank you!

2021-02-01 21:00 UTC, mikehardy commented
Just a friendly notice (one per person, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for Jan 2021 submissions

Process note:

At the end of the month, go to our OpenCollective expense form and follow their process to file an expense.

As this process is new, we have little information on how many people will submit expenses, so we don't know what the total will be. As mentioned in "sustainable" above, we are trying to distribute about 10% of the total balance each month but we are just guessing how many hours and what hourly rate will actually add up to that now. 

We will almost certainly adjust the amount of hours or the hourly rate this month in order to distribute the target amount, so if you submit an expense please submit for all the hours you spent, at the arbitrary rate of $10/hr. Once all the hours from everyone are in so I have real numbers to do real math on, I'll comment on the expenses to offer guidance on how to adjust them, then we'll process them

Thanks!