Timber all exceptions catched not re-thrown
ankidroid/Anki-Android pull request #8090
Opened 2021-02-06 17:01 UTC by Arthur-Milchior

I currently have an exception which is not printed. Instead, it shows an error message in ankidroid, but that does not help me to debug.
I realize that even if it's great for the user, it seems always nice to timber exceptions for people actually reading at logs.

Exception: I didn't add timbers to com.ichi2.anki.api since it's another package

2021-02-06 17:07 UTC, david-allison-1 requested changes
Could we use `.w`

https://github.com/ankidroid/Anki-Android/wiki/Code-style#the-error-level-should-only-be-used-when-something-fatal-has-happened

2021-02-06 17:09 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                Timber.e(e);
`ConfirmModSchemaException` does not need an error/warn log as it's not an error

Ideally just an info or debug log, (maybe under a `e.log()` call).

2021-02-06 17:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                Timber.e(e);
What is "e.log"? The ConfirmModSchemaException  does not have a `log` function

2021-02-06 17:47 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                Timber.e(e);
Might be best to add one, as the implementation will be the same, and potentially subject to change once we know how much log spam it produces.

2021-02-06 18:35 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                Timber.e(e);
I am sorry, but I do not know what you are asking for. What would it mean to add a log function to an exception?

I get your point that we might want to remove it, or at least not to leave it as anything more than verbose, and that has been done. But that does not tell me what the log function would do

2021-02-06 18:44 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                Timber.e(e);
Literally just a call-through to `Timber.log` -  we're repeating code for a specific aspect of the codebase, and the rationale behind logging for that aspect is subject to change. It'll mean less changes, and reduces the chance that we'll miss fixing a log statement overall.

That being said, it's such a minor nitpick. I'll go through then approve - implementer's choice.

2021-02-06 18:46 UTC, david-allison-1 requested changes

2021-02-06 18:46 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
> +            Timber.w(e);
Okay - I'll push back on the log statement and ask for it (but happy to discuss), this should have been a `Timber.v`. 
```suggestion
            Timber.v(e);
```

2021-02-06 19:22 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
> +            Timber.w(e);
Timbers are changed to v.
Note that this does not seems to be consistent with existing code, which deals with exceptions in various ways. Sometime using printStackTrace, sometime timbering with various degree of severity.

I probably won't try to uniformize them, I don't see the point and looking at all catch took a lot of time and can't really be automatized unless I know how to look at java's AST

2021-02-06 21:05 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                Timber.e(e);
`Timber.log` does take a priority. It's a generalization of `Timber.w`, `.v`, etc... so I can't just call it without knowing which priority to use.

I can also move all call to Timber to printStackTrace, that's fine by me, will allow the same potential debugging, and will avoid to send log if we don't want them.

2021-02-07 02:10 UTC, david-allison-1 requested changes
I've been unclear, and I apologize for the wasted time on this bikeshedding

* Keep everything except `ConfirmModSchemaException` as `Timber.w`
* `ConfirmModSchemaException` should consistently be a `Timber.v` - ideally encapsulated by a method inside `ConfirmModSchemaException` in-case we obtain the exception and need to deal with it

2021-02-07 11:04 UTC, Arthur-Milchior commented
I went over all catched ModSchemaExceptions and used log if the exception is expected, and kept Timber/throw if the exception should not have ocured.
I should not that, if the PR which factorize ModSchemaExceptions catching/asking were merged, this would lead to a simpler, smaller commit here. But I guess I still need to understand how to make unit test for graphical interface, since it's not merged because there are part of the code which changes and are not covered

2021-02-07 11:53 UTC, david-allison-1 approved these changes
Few comments, but nothing blocking

2021-02-07 11:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
> +                throw new IllegalArgumentException("Model ID must be either numeric or the String CURRENT_MODEL_ID", e);
Adds questionable value - just for discussion

2021-02-07 11:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/TextImporter.java
> +                Timber.w(e);
I don't know here - this was ported code, might need to see if the Unit tests cause this to be logged

2021-02-07 13:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
> +                throw new IllegalArgumentException("Model ID must be either numeric or the String CURRENT_MODEL_ID", e);
Currently, the exception does not state what was the value, which makes debugging less easy. I thought that using the value might improve debugging if this ever occurs. The string value is in the NumberFormatException and I kind of hoped that IllegalArgumentException would print NumberFormatException which would print the broken string.

I admit I didn't test it and at least, using the actual String might be a better idea. Given that it was not a problem I ever encountered and that my goal was mostly to go quickly over each catch and ensure that exceptions content are not ignored, I'm fine recreating this and changing the message so that it contains the srting or anything else you'd prefer

2021-02-07 13:35 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/importer/TextImporter.java
> +                Timber.w(e);
Can you please help me understand why it matters. I feel like I am missing something.
Even if this exception is expected and not actually sign of any bug, because we are testing sniffer and they just raise exceptions, I fail to see why the Timber are a problem. Either there is an actual bug we try to debug and this will help figuring out what was going on, as log does, or there is no bug and it's not going to impact the user. Timber may be slow, but that's only executed once by import so it won't be noticeable compared to most import code

2021-03-24 17:51 UTC, mikehardy requested changes
I scanned through them all and read the issue - should have checked + merged this much sooner, thanks for your patience @Arthur-Milchior - I found exactly one case of a ConfirmModSchemaException that did not do the slightly-different `.log()` call vs a direct Timber - change that one and this is good to merge

2021-03-24 17:51 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
> +                                Timber.w(e1);
```suggestion
                                e1.log();
```

2021-03-24 18:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
> +                                Timber.w(e1);
done

2021-03-24 19:02 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                Timber.w(e);
```suggestion
                e.log();
```

2021-03-24 19:03 UTC, mikehardy requested changes
I strangely see two more of the special cases missed, I'm sorry to bat this back and forth. It's an obviously good change, I'm itching to merge it....

2021-03-24 19:03 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                Timber.w(e);
```suggestion
                e.log();
```

Did these two get added in the delay between you doing this and me reviewing it or did something else happen? Either way it seems like there are 2 more, but this is SO CLOSE :-)

2021-03-24 19:09 UTC, Arthur-Milchior reviewed
done normally. I must admit I still don't understand why you want some with .log and some with Timber, but I tried to find the one you wanted and put them with .log

2021-03-24 19:09 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                Timber.w(e);
Normally, I added nothing. Just made the change you asked. Not even a merge conflict

2021-03-24 19:13 UTC, mikehardy approved these changes
I'm just following David's desires on the ConfirmModSchemaException so I can feel free to merge without feeling like I've done so in contradiction to his request, and since it is easy enough doesn't seem a like a huge deal?

Logically I could see that since that one specific exception is used more as a control flow signal vs an actual exception case, that it can be handled differently. In practice will it be important? Only the future versions of ourselves know

2021-03-24 19:16 UTC, Arthur-Milchior commented
It's a controlFlowSignal the first time only. The second time it should never occur and is a really.

2021-03-24 19:32 UTC, merged