Release TextToSpeech with a Context
ankidroid/Anki-Android pull request #8155
Opened 2021-03-10 01:33 UTC by JG916

## Pull Request template

## Purpose / Description
TextToSpeech was being released (shutdown) incorrectly due to a race condition.
When AbstractFlashcardViewer is recreated (Ex: through changing themes), the newly created activity initialized a new TextToSpeech. 
The old activity then releases that same TextToSpeech instance from onDestroy()
TextToSpeech will not work until it is re-initialized.

## Fixes
Fixes #8084

https://user-images.githubusercontent.com/16379504/110561114-1fa2ee80-8115-11eb-9a4b-db9f48ae2677.mp4

## Approach
When TextToSpeech is initialized, a Context is passed in and stored.
That Context is always 'paired' with a single instance of TextToSpeech.
Because the caller that initialized the instance wants to make sure it cleans up when it's done, it attempts to release it.
The instance is stored in a static private field in a different class, so the caller cannot tell what the state of that instance is.
To prevent a caller from releasing an instance of TextToSpeech that was initialized by another caller, the same Context must be passed it to verify if the instance belongs to it or not.

This has some caveats though. For instance, right now the only context used is AbstractFlashcardViewer, but if you were to start passing in a shared context like the application context, this problem would re-occur.

Because of the overall structure of ReadText and its connections, it was hard to find a solution that didn't involve a massive amount of time and code changes.

## How Has This Been Tested?

1. Enable TTS
2. Go to Study
3. Change theme from hamburger menu (switch on/off night mode)
4. Choose 'Replay audio' from dots menu

The audio should play after both step 3 (when the card is first shown) and step 4.

Tested on an emulator with API 29.

## Learning (optional, can help others)
https://developer.android.com/reference/android/speech/tts/TextToSpeech
http://robolectric.org/javadoc/4.0/org/robolectric/shadows/ShadowTextToSpeech.html

Text to speech is shared through all applications. Maybe it's possible that the current usage here could be changed from a (pseudo) per-activity usage to something more like a singleton? The initialization takes quite a long time to run, and it's likely that when used once, it will be used quite often throughout the session, so a different setup and destroy system could run perform better.

When re-initializing TextToSpeech inside ReadText, it's directly overriding the old reference without calling `shutdown()` on it beforehand. I'm wondering how much of an effect this has...

## Checklist
- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

2021-03-10 13:30 UTC, mikehardy requested changes
Just one comment on freeing the context in the one case we know enough to do so?

Also, the information in the PR about a possible refactor (or total restructure, really) where TextToSpeech is changed to match it's reality (that it is per-device really, so definitely should be true singleton in the Application and just stay initialized) is valuable - could you peel that into a separate issue for "the real fix"? We can mark it as an enhancement and perhaps someone will want to take it on for polishing

2021-03-10 13:30 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java
> +        if (mTts != null && mReviewer.get() == context) {
I think here we should clear the context too to prevent the only version of leak we can reasonably prevent with this ugly-but-quite-practical fix?

```suggestion
        if (mTts != null && mReviewer.get() == context) {
            context = null;
```

...I think?

2021-03-10 23:31 UTC, JG916 commented on AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java
> +        if (mTts != null && mReviewer.get() == context) {
Sorry, I'm not quite sure where the leak is happening here. 
`context` is not being stored anywhere from this function, so it shouldn't be leaking here.
Or if you meant `mReviewer`, that has a type of `WeakReference<Context>`, so it shouldn't retain it here either.

Correct me if I'm wrong about this, I haven't used Java in a few months now 😅

2021-03-10 23:33 UTC, JG916 commented on AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java
> +        if (mTts != null && mReviewer.get() == context) {
I can definitely put up an issue for the 'possible' fix soon. 

Take my solution suggestion with a mountain sized grain of salt though, there's a whole lot more about the architecture here and TextToSpeech I'd need to learn about before I'd be confident about it.

2021-03-11 01:59 UTC, Arthur-Milchior reviewed
First and most importantly, thanks a lot for your first contribution. I clearly would have had a hard time guessing the cause. You even have added test, which is more than what I did when I started, really love that!

May I ask you something. Since you found the cause three days ago in https://github.com/ankidroid/Anki-Android/issues/8084 , I assume it's a coincidence that your first PR arrive exactly when we announced that we are doing a Google Summer of Code internship, right ? If so, fun coincidence. 

May I please ask you to change a little bit your commit message. Maybe the title could be something such as:

> Allow to change setting without breaking TTS

and the message would contain a copy of the PR information. This way, someone reading the code in a few years would understand why this was done if needed. This is especially important since this code is far from intuitive when you don't know why it must be done this way

2021-03-11 01:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java
> +        if (mTts != null && mReviewer.get() == context) {
If `stop` or `shutdown` takes time to return, then `context` is kept in scope and so maybe can not be garbage collected. I do not know about java internal enough to know whether the garbage collector know that `contex` won't be used anymore, and I really really wish that we don't have to deal with this level of details.
Is there any reason to expect that one of those methods take time to return Mike? In particular that it takes so much time that it's a real concern?

2021-03-11 04:20 UTC, JG916 commented
Thanks for the kind words! It's great to find a repo that is this friendly 🙂

I haven't heard about your participation of summer of code until just now. Funny timing. I'm a little bit too old to be an intern, anyway.

I just pushed up a new commit message and description, too. LMK if this looks okay or not.

2021-03-11 19:18 UTC, mikehardy commented
The context leak is the most minor of concerns IMHO - was more of a thought "if it's easy" - I'll re-review :-)

2021-03-20 18:38 UTC, mikehardy approved these changes
Sorry for the delay! This looks good to go, thank you!

2021-03-20 18:47 UTC, merged

2021-04-05 18:37 UTC, mikehardy commented
Hi there!

Just a friendly notice (one per person for PRs merged in March, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for March 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

Thanks!