Warn using http
ankidroid/Anki-Android pull request #8167
Opened 2021-03-11 10:22 UTC by TarekkMA

## Pull Request template

## Purpose / Description
When the user tries to load an external file/image using the unsecure HTTP protocol will result in ``net::err_CLEARTEXT_NOT_PERMITTED`` and the file/image will not load for the user without any explanation.
see: #7231

<img src="https://user-images.githubusercontent.com/6633545/110771582-54bd5700-8263-11eb-83b1-34ec581e255a.png" width="25%">

## Fixes
Fixes #7741

## Approach
Since we are using a custom ``WebViewClient`` we have the ability to intercept requests that the web view is making. So checking whither the URL scheme is HTTP or not becomes easy.

2 new string were added, one for the snackbar message, and another constant link for the [FQA#external-content](https://github.com/ankidroid/Anki-Android/wiki/FAQ#external-content).

## How Has This Been Tested?

Tested manually by trying to load a card with an HTTP image

## Learning (optional, can help others)
Reading the docs of ``WebViewClient.shouldOverrideUrlLoading``. And realizing it won't be running on the Main/UI thread.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

2021-03-11 10:45 UTC, TarekkMA commented
BTW all test is passing on my machine, so I don't know why the CI is complaining

2021-03-13 03:30 UTC, david-allison-1 requested changes
Looks good, thanks! Comments are all nitpicks - could just be done in a single commit.

My main question: What happens when multiple images are included in a card? Does this means that multiple snackbars are displayed? 

What happens if they have 5 cards with this issue? Would they get this snackbar each time they load a card?

If I'm correct, then this functionality is likely to frustrate some users. I'd suggest using functionality such as in the following code to only ensure that the specific message is shown a couple of times to users:

https://github.com/ankidroid/Anki-Android/blob/7459828a32d0713bea0fd427b78856ba701bf9db/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L3348

Please note: If you disagree with anything said in a review, or think things can be done better, please do let us know. This is a discussion, and your perspective is important as you're the one who's closest to the code, please never see it as a "you must do X".

2021-03-13 03:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        protected boolean isLoadedFromHttpUrl(Uri uri){
```suggestion
        protected boolean isLoadedFromHttpUrl(Uri uri) {
```

2021-03-13 03:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        protected boolean isLoadedFromHttpUrl(String url){
```suggestion
        protected boolean isLoadedFromHttpUrl(String url) {
```

2021-03-13 03:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            if(isLoadedFromHttpUrl(url)){
```suggestion
            if (isLoadedFromHttpUrl(url)) {
```

2021-03-13 03:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            if(isLoadedFromHttpUrl(url)){
```suggestion
            if (isLoadedFromHttpUrl(url)) {
```

2021-03-13 03:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                AbstractFlashcardViewer.this.runOnUiThread(() -> {
Consider extracting this duplicate code into a method. Android Studio has this functionality under the "Refactor" context menu icon.

2021-03-13 04:44 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                AbstractFlashcardViewer.this.runOnUiThread(() -> {
Yeah you're right, but will leave the `runOnUiThread` part as it's specific to these methods

2021-03-13 05:22 UTC, TarekkMA commented
Thanks a lot David for your feedback.

Yes that would definitely be annoying to the user if she/he has multiple media content with HTTP content.

``MissingImageHandler`` Looks like a good idea, but I think the name should be changed (another PR) to something like ``MulimediaFaulthandler`` as the original name is kinda misleading.

If we go with ``MissingImageHandler``, I think adding a new counter for that error would be best, since having missing media is different from inaccessible media.

I also propose another solution for this, and maybe other code that need this functionally could use it.
A decorator like class. The name of the class could be more meaningful.
```java
final mShowSnakbar = new FunctionWithMaxExec(3, ()-> {
        OnClickListener onClickListener = (v) -> openUrl(Uri.parse(getString(R.string.link_fqa_external_http_content)));
        showSnackbar(getString(R.string.cannot_load_http_resource), R.string.help,onClickListener);
});
......
......

mShowSnakbar.exec();
```

Interested in hearing your thoughts about this, thanks again.

2021-03-13 05:24 UTC, TarekkMA commented
I will squashe the commits when I get to my PC.

2021-03-13 05:29 UTC, david-allison-1 commented
> Thanks a lot David for your feedback.
> 
> Yes that would definitely be annoying to the user if she/he has multiple media content with HTTP content.
> 
> `MissingImageHandler` Looks like a good idea, but I think the name should be changed (another PR) to something like `MulimediaFaulthandler` as the original name is kinda misleading.
> 
> If we go with `MissingImageHandler`, I think adding a new counter for that error would be best, since having missing media is different from inaccessible media.
> 
> I also propose another solution for this, and maybe other code that need this functionally could use it.
> A decorator like class. The name of the class could be more meaningful.
> 
> ```java
> final mShowSnakbar = new FunctionWithMaxExec(3, ()-> {
>         OnClickListener onClickListener = (v) -> openUrl(Uri.parse(getString(R.string.link_fqa_external_http_content)));
>         showSnackbar(getString(R.string.cannot_load_http_resource), R.string.help,onClickListener);
> });
> ......
> ......
> 
> mShowSnakbar.exec();
> ```
> 
> Interested in hearing your thoughts about this, thanks again.

Sounds good to me. Let's do it!

2021-03-13 14:01 UTC, TarekkMA commented
@david-allison-1 
I have added ``MaxExecFunction`` class as described in my proposal, I'm using `MaxExecFunction.execOnceForReference(card)` so if the card the user is looking at have multiple issues regarding the http content, it will only execute once and increasing the number of executions by only 1

2021-03-14 06:35 UTC, david-allison-1 approved these changes
Looks great to me, thanks!!!

2021-03-14 20:41 UTC, mikehardy requested changes
My comments are important to fix but are also all just nits, this looks great and should help users help themselves, which will lower our support load (and lower user frustration) a lot. Thank you!

2021-03-14 20:41 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/utils/MaxExecFunction.java
> +package com.ichi2.utils;
Missing a copyright header in here - just copy from any other file with the header but put your name in it please

2021-03-14 20:41 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/utils/MaxExecFunctionTest.java
> +package com.ichi2.utils;
missing copyright header here as well - but you've added a test! Thank you :heart:

2021-03-14 20:41 UTC, mikehardy commented on AnkiDroid/src/main/res/values/constants.xml
> +    <string name="link_fqa_external_http_content">https://github.com/ankidroid/Anki-Android/wiki/FAQ#external-content</string>
```suggestion
    <string name="link_faq_external_http_content">https://github.com/ankidroid/Anki-Android/wiki/FAQ#external-content</string>
```

2021-03-14 20:41 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        OnClickListener onClickListener = (v) -> openUrl(Uri.parse(getString(R.string.link_fqa_external_http_content)));
```suggestion
        OnClickListener onClickListener = (v) -> openUrl(Uri.parse(getString(R.string.link_faq_external_http_content)));
```

2021-03-14 20:46 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/utils/MaxExecFunction.java
> +package com.ichi2.utils;
Copy this exact copy right comment? and btw not all files have that in.
```
/*
 *  Copyright (c) 2020 David Allison <davidallisongithub@gmail.com>
 *
 *  This program is free software; you can redistribute it and/or modify it under
 *  the terms of the GNU General Public License as published by the Free Software
 *  Foundation; either version 3 of the License, or (at your option) any later
 *  version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT ANY
 *  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 *  PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with
 *  this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 ```

2021-03-14 20:47 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        OnClickListener onClickListener = (v) -> openUrl(Uri.parse(getString(R.string.link_fqa_external_http_content)));
oops 😅

2021-03-14 20:59 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/utils/MaxExecFunction.java
> +package com.ichi2.utils;
Changed the author and the date

2021-03-14 22:10 UTC, TarekkMA commented
@mikehardy Done

2021-03-14 22:19 UTC, mikehardy approved these changes
Glorious :-)

2021-03-14 22:20 UTC, merged

2021-03-14 22:20 UTC, mikehardy commented
merged :rocket: - will be in the next alpha, should be shortly I have almost finished sweeping through all the activity from the week

2021-03-14 22:23 UTC, TarekkMA commented
Nice. this is so exciting. My first merged contribution to AnkiDroid. Definitely will not be the last ❤️