Fixes #8164 Changed custom tabs theme with respect to app theme
ankidroid/Anki-Android pull request #8175
Opened 2021-03-12 08:03 UTC by mrudultora

## Purpose / Description
The app was not changing the theme of custom tabs with respect to the theme of the app (it was always blue colored theme). In this PR, that issue is fixed. The change is somewhat broader than mentioned in issue as all the themes (light, plain, dark, black) are considered.
The output of all 4 themes is in below image.

![img](https://user-images.githubusercontent.com/65870389/110910463-61ab7a80-8337-11eb-95b4-17f98ccbc6f6.png)

## Fixes
Fixes #8164 

## Approach
Firstly, I used reflection to get the current theme value in `int` format (if the reflection throws exception then we will switch to the light mode irrespective of app theme). Then, I had made some changes `CustomTabsIntent`.

## How Has This Been Tested?
Tested this on real device (Redmi Note 7S and Android SDK 29).

## Learning (optional, can help others)
Anyone interested in how custom tabs work can look here at the official [link.](https://developer.android.com/reference/androidx/browser/customtabs/CustomTabsIntent.Builder)

## Checklist

- [ x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x ] You have commented your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code
- [ x ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

2021-03-12 08:34 UTC, mrudultora commented
@david-allison-1 Sir, would you please review this? Also, I don't know why unit tests are failing. Please explain me that point.

2021-03-12 19:39 UTC, david-allison-1 requested changes
Really appreciate the effort. Thanks so much!

Unit test looks like a flaky test.

It seems that it would be much simpler to define the colour in the theme resources, rather than hardcoding the values per-theme in the method. I'm admittedly not too familiar with the theming side of the codebase, so this might be something really obvious that I'm missing.

Is there a reason that you chose to hardcode the constants for the colours in the code?

2021-03-12 19:39 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +            Method m = Class.forName(Context.class.getName()).getMethod("getThemeResId");
We should be able to read the setting from the preferences and return the ID rather than use reflection

2021-03-12 19:39 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +    private void fetchThemeColors() {
It's best not to use a class-scoped variable if a locally scoped variable will do, and the result from this method is only used by one function.

Can we return a tuple/class rather than setting member variables here?

2021-03-12 19:39 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +            System.out.println("currentTheme exception "+currentTheme+ e.getCause()+e.getMessage());
`Timber.w()`  if we want to log the error, but don't report it.

Also add `AnkiDroidApp.sendExceptionReport(` if it's unlikely to occur.

2021-03-12 19:39 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +        if (AppCompatDelegate.getDefaultNightMode() == AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM) {
We don't implement this yet, likely best to add a comment and leave following system night mode to another PR

2021-03-12 19:47 UTC, mrudultora commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +            System.out.println("currentTheme exception "+currentTheme+ e.getCause()+e.getMessage());
@david-allison-1  I forgot to replace that line (it was only meant to be for debug purposes). Okay I will do those changes!

2021-03-12 19:50 UTC, mrudultora commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +            Method m = Class.forName(Context.class.getName()).getMethod("getThemeResId");
No, actually I tried getting that from preferences but I was not able to do so. Infact, was unable to find on Stackoverflow also. So, at the end I moved towards reflection. This method is private but I tested on API 21 based emulator and API 29 based real device. Could you suggest another workaround ? (I tried my best to avoid using reflection).

2021-03-12 19:51 UTC, mrudultora commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +            Method m = Class.forName(Context.class.getName()).getMethod("getThemeResId");
After debugging, I found out that to compare the themes (the one from reflection and the current one) I have to hardcode them.

2021-03-12 19:54 UTC, mrudultora commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +        if (AppCompatDelegate.getDefaultNightMode() == AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM) {
Okay! I will do that.

2021-03-12 19:57 UTC, mrudultora commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +    private void fetchThemeColors() {
Would you please elaborate this point? Are we talking about the variables `toolbarColor` and `navBarColor`. So, should I make them member variables and pass it as argument ?

2021-03-12 20:07 UTC, mrudultora commented
> Really appreciate the effort. Thanks so much!
> 
> Unit test looks like a flaky test.
> 
> It seems that it would be much simpler to define the colour in the theme resources, rather than hardcoding the values per-theme in the method. I'm admittedly not too familiar with the theming side of the codebase, so this might be something really obvious that I'm missing.
> 
> Is there a reason that you chose to hardcode the constants for the colours in the code?

The way theming is done is a bit new to me. And truly speaking, it was really surprising that getting the current theme would become a big issue for me, so hardcoding them was the only solution I thought at the end.
If there's a simpler way of doing this, I would be happy to make those changes.

2021-03-12 20:14 UTC, david-allison-1 commented
> > Really appreciate the effort. Thanks so much!
> > Unit test looks like a flaky test.
> > It seems that it would be much simpler to define the colour in the theme resources, rather than hardcoding the values per-theme in the method. I'm admittedly not too familiar with the theming side of the codebase, so this might be something really obvious that I'm missing.
> > Is there a reason that you chose to hardcode the constants for the colours in the code?
> 
> The way theming is done is a bit new to me. And truly speaking, it was really surprising that getting the current theme would become a big issue for me, so hardcoding them was the only solution I thought at the end.
> If there's a simpler way of doing this, I would be happy to make those changes.

Should be able to:

Define an attribute: https://github.com/ankidroid/Anki-Android/blob/88db890eccb95aef81bb8c7327c362b3af93bd52/AnkiDroid/src/main/res/values/attrs.xml#L101

Define the attribute for each theme:

https://github.com/ankidroid/Anki-Android/blob/88db890eccb95aef81bb8c7327c362b3af93bd52/AnkiDroid/src/main/res/values/theme_black.xml#L90

Use it in code:

https://github.com/ankidroid/Anki-Android/blob/5f446439dbc5ff5b5abc11c2c50b3c907268af93/AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java#L183

2021-03-13 00:47 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +    private void fetchThemeColors() {
Yep - define a private class containing those two member variables (`mToolbarColor ` and `mNavBarColor`) and return it.

2021-03-14 06:53 UTC, mrudultora commented
@david-allison-1 Thanks for suggesting that way. Now, there is no need for using reflection. I have added the colors and there attributes. Also, I have checked it's working fine System Dark Mode. So, I have not changed that part. Would you please take a look at the changes?

2021-03-14 07:28 UTC, david-allison-1 reviewed
Nittiest of nitpicks. This is so much cleaner. Thank you!

I'll squash and merge if you're happy with my suggestions.

Obviously just want to confirm: this still works as expected after the change?

2021-03-14 07:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +        int toolbarColor=Themes.getColorFromAttr(this,R.attr.customTabToolbarColor);
```suggestion
        int toolbarColor = Themes.getColorFromAttr(this, R.attr.customTabToolbarColor);
```

2021-03-14 07:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +        int navBarColor=Themes.getColorFromAttr(this,R.attr.customTabNavBarColor);
```suggestion
        int navBarColor = Themes.getColorFromAttr(this, R.attr.customTabNavBarColor);
```

2021-03-14 07:35 UTC, mrudultora commented
> Nittiest of nitpicks. This is so much cleaner. Thank you!
> 
> I'll squash and merge if you're happy with my suggestions.
> 
> Obviously just want to confirm: this still works as expected after the change?

@david-allison-1 Yes, it is working completely fine. I tested it again for every theme. It was same so I didn't update the screenshot.

2021-03-14 07:35 UTC, mrudultora commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +        int toolbarColor=Themes.getColorFromAttr(this,R.attr.customTabToolbarColor);
So, should I make the commit for these changes?

2021-03-14 07:37 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +        int toolbarColor=Themes.getColorFromAttr(this,R.attr.customTabToolbarColor);
Yeah, just click "commit suggestion" if you're happy - I don't like making changes to other people's code directly.

2021-03-14 07:42 UTC, david-allison-1 approved these changes
Let's do this. Thanks!

I'll squash and merge this assuming CI passes.

2021-03-14 21:08 UTC, mikehardy approved these changes
This looks great! Eliminates one of the last really jarring places I think, where we don't respect the chosen theme

CI has passed, I'll squash-merge

2021-03-14 21:09 UTC, merged