Fixes #6535 Change log theme with respect to app theme
ankidroid/Anki-Android pull request #8181
Opened 2021-03-13 11:47 UTC by mrudultora

## Purpose / Description
Change log was always in light mode even when the app is in night mode both in release and debug build.
Also, just reformatted 2-3 lines `(ctrl+alt+L)` .
**Point to note is to test whether this will work in release mode I copied the changelog from the app ( live on playstore). This is to make sure that changelogs does not break in release builds.**

Attaching Screenshot for better refrence.
![img](https://user-images.githubusercontent.com/65870389/111028923-dfe34c00-841f-11eb-9b00-cd66c30b5d33.png)

## Fixes
Fixes #6535 

## Approach
Used **javascript** to make changes in the colors of `webView` (textColor, backgroundColor and link colors).

## How Has This Been Tested?
Tested on real device (Redmi Note 7S and API 29).

## Learning (optional, can help others)
This PR can help you to learn the usage and implementation of javascript in webView for changing themes (day/night mode).

## Checklist
_Please, go through these checks before submitting the PR._

- [ x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x] You have commented your code, particularly in hard-to-understand areas
- [ x] You have performed a self-review of your own code
- [ x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

2021-03-13 12:11 UTC, david-allison-1 requested changes
Fantastic!

One very small nitpick (I'd be tempted to say let's get this in if it turns out to be a significant amount of work/explanation), let me know if you'll need guiding through it.

----

Looks like it's been tested on the real thing and looks great. Thanks again!

2021-03-13 12:11 UTC, david-allison-1 commented on AnkiDroid/src/main/assets/changelog.html
> +</html>
nitpick: Could you `rebase/amend` this change out of the commit? No point in bumping a file if there's no content change relevant to the PR

This also applies to the lines at the end of `Info.java`

2021-03-13 12:51 UTC, mrudultora commented
@david-allison-1 I will do the changes. Actually, I unknowingly remove whitespaces lines. That happened before also. I will remember such things in future.

2021-03-13 12:52 UTC, mrudultora commented
The lines at the end of `Info.java` is changed. Was it a whitespace? I will check it once.

2021-03-13 12:56 UTC, david-allison-1 reviewed
Flagged the two changes I was referring to

2021-03-13 12:56 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.java
> +     *
line changed

2021-03-13 12:56 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.java
> +        android.content.ClipboardManager clipboardManager = (android.content.ClipboardManager) getSystemService(Context.CLIPBOARD_SERVICE);
line changed

2021-03-13 13:01 UTC, mrudultora commented
> Flagged the two changes I was referring to
> 
> 

Might be I am unable to explain you my point. Those changes actually arosed because of the below reason.

> Also, just reformatted 2-3 lines (ctrl+alt+L) .

2021-03-13 16:09 UTC, mrudultora commented
@david-allison-1 I have done the changes suggested by you. Squashed my previous 2 commits into the single one ;-)

2021-03-14 07:44 UTC, david-allison-1 approved these changes
Looks good to me! Kicked off CI again

2021-03-14 22:05 UTC, mikehardy approved these changes
Fascinating that best way to set the webview color is to dynamically javascript it after, but if it is tested and working, works for me

2021-03-14 22:05 UTC, merged