Improved UI Design Of Login Page.
ankidroid/Anki-Android pull request #8182
Opened 2021-03-13 11:54 UTC by Akshay0701

## Improved UI Design Of Login Page.

## Purpose / Description
Previous login ui was good and responsive ,but size of login button was small and button color was not matching with app bar color, and also it was not matching current UI design trend which user like the most, so i changed ui design of login page to make user experience great :)

## Added
1 Added designed button 
2 Added Anki-Android Logo

## Test
Tested this UI with different sizes of devices.

## Output
![Capture](https://user-images.githubusercontent.com/52353967/111028979-3a7ca800-8420-11eb-89c3-9f0cdb4b3234.PNG)

- [✓ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [✓] You have a descriptive commit message with a short title (first line, max 50 chars).
- [✓ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [✓] You have commented your code, particularly in hard-to-understand areas
- [✓] You have performed a self-review of your own code
- [✓] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

2021-03-13 12:05 UTC, david-allison-1 reviewed
I really like this!

* What's the rationale behind `nodpi` here, (I haven't used it previously), this seems to mean the app won't scale the image: https://developer.android.com/training/multiscreen/screendensities
   *   > Tip: If you have some drawable resources that the system should never scale (perhaps because you perform some adjustments to the image yourself at runtime), you should place them in a directory with the nodpi configuration qualifier. Resources with this qualifier are considered density-agnostic and the system will not scale them.

Not something I've had to deal with previously (so I'm taking a best guess), but we're adding 50KB to the APK size with `ankidroid_logo.png` and I'd like to see if we can reduce this.

* Have you tried to compress the file with PNGCrush or similar?
* Do we need the image at the current size for very high density displays?

2021-03-13 12:20 UTC, Akshay0701 commented
I added logo which you provided me in discord, and no i didn't tried to compress the file with PNGCrush ,
but i will learn about it .

2021-03-13 14:03 UTC, Akshay0701 commented
Yes @david-allison-1 I added new logo to support for high resolution phones, so that logo will not get blur , let me know if there's any issue in this PR ?

2021-03-14 04:37 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +                mProgressDialog = StyledProgressDialog.show(MyAccount.this, null,
It's be best to fix different bugs in separate PRs. That means we can focus more directly on the change. 

This change could instantly be merged in a separate PR.

2021-03-14 04:38 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +                mProgressDialog = StyledProgressDialog.show(MyAccount.this, null,
okay i will make separate pr for this issue

2021-03-14 04:41 UTC, Arthur-Milchior commented
That's quite nice, thanks.

Can I please ask you:
* screenshot of the device in horizontal and not only vertical
* screenshot on at least one big screen size, such as tablet. 
* Please check the Android Accessibility Auditor remark on your change https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor and ensure that it is accessible. (Note that ankidroid is far from being accessible right now. It just means that the change improve this too)

2021-03-14 07:09 UTC, Akshay0701 commented
@Arthur-Milchior here are some screenshoot that you ask for : )
## UI With Dark Mode
<img src="https://user-images.githubusercontent.com/52353967/111060223-3a80b480-84c1-11eb-9dba-0bc226e583c0.jpg" alt="alt text" width="250" height="550">

## UI In Horizontal Mode
<img src="https://user-images.githubusercontent.com/52353967/111060214-2fc61f80-84c1-11eb-9416-44e66cebb82f.gif" alt="alt text" width="550" height="250">


## UI In Horizontal Mode In Tablet  
![Capture2](https://user-images.githubusercontent.com/52353967/111060244-66039f00-84c1-11eb-9dbd-3fc46787afc1.PNG)

## UI In Vertical Mode In Tablet  
![Capture - Copy](https://user-images.githubusercontent.com/52353967/111060258-87648b00-84c1-11eb-8fa7-8a77f792be65.PNG)

2021-03-14 19:54 UTC, mikehardy requested changes
I like this!

However, don't we have an SVG for this already? It should be SVG really and I swear we have that icon available, it's our logo isn't it? Shouldn't be any need to add a PNG or worry about scaling or anything

In general I don't expect to see any PNGs added to the app again ever unless there is some special circumstance. It used to be PNG support was difficult but that is not the case anymore

2021-03-14 20:00 UTC, david-allison-1 commented
Apologies - I wasn't aware that we had an SVG icon (our current icon is in the `legacy` folder?): https://github.com/ankidroid/Anki-Android/blob/master/docs/graphics/legacy/anki.svg

I think we'll need to consider how we want the "horizontal" landscape to appear. All other look good, but this moves the login box off-screen.

2021-03-14 23:21 UTC, Arthur-Milchior commented
Agreed with David, having the login fields outside of the initial screen is a problem. We can have different screen depending on the size. I believe the best solution would be to find the correct height at which we start adding the image

2021-03-15 03:36 UTC, Akshay0701 commented
@mikehardy Yes we do have Svg image but problem with old icon is it get blur on big screens ,like tablet or iphones ,
so that is reason why i used high resolution png image ,if you want me to convert this png to svg , i will do that : )

2021-03-15 03:38 UTC, david-allison-1 commented
> @mikehardy Yes we do have Svg image but problem with old icon is it get blur on big screens ,like tablet or iphones ,
> so that is reason why i used high resolution png image ,if you want me to convert this png to svg , i will do that : )

SVGs shouldn't blur. It'd be better to use it: https://github.com/ankidroid/Anki-Android/blob/master/docs/graphics/legacy/anki.svg

Do screenshot if there are problems

2021-03-15 03:41 UTC, Akshay0701 commented
yes using icon takes login form outside screen in horizontal mode or small screen devices, I can write code to invisible icon in case user have small screen or using login form in horizontal mode and I will take icon little bit up so that below form gets much space ,
i think this will resolve issue of spaces and horizontal mode , let me know should i follow this approach ?

2021-03-15 03:48 UTC, david-allison-1 commented
> yes using icon takes login form outside screen in horizontal mode or small screen devices, I can write code to invisible icon in case user have small screen or using login form in horizontal mode and I will take icon little bit up so that below form gets much space ,
> i think this will resolve issue of spaces and horizontal mode , let me know should i follow this approach ?

You're closest to the issue - I think both will work, and I trust you to do what you think will work best

2021-03-15 04:44 UTC, Akshay0701 commented
Okay , let me explain what i did in this commit ,
1 removed ankidroid png icon and used svg icon 
2 placed ankidroid icon at top so that screen get enough spaces 
3 in case if any user using app in horizontal mode or small screen device , app automatically invisible icon to get extra spaces for small devices  

## Final Output
![Capture](https://user-images.githubusercontent.com/52353967/111104438-bab52180-8576-11eb-9a70-948a7cc0fc3e.PNG)

with horizontal mode // in horizontal mode or small screen device logo will not show ,to get some extra space on screen 
![ezgif-7-6284f0635543](https://user-images.githubusercontent.com/52353967/111104591-09fb5200-8577-11eb-9abb-f04d42eb0452.gif)

2021-03-15 06:39 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                        android:src="@drawable/anki"
This isn't referencing an SVG, causing blurriness

2021-03-15 06:40 UTC, david-allison-1 commented
Other than the comment, the screenshots look nice, thanks 😄

2021-03-15 07:01 UTC, Akshay0701 commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                        android:src="@drawable/anki"
can you please  provide me full name of svg icon ?

2021-03-15 07:17 UTC, Akshay0701 commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                        android:src="@drawable/anki"
yes now i included svg image

2021-03-15 10:21 UTC, david-allison-1 reviewed
I think these are all just nitpicks/style hints. Should be good to go once they're fixed up

2021-03-15 10:21 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                        tools:ignore="VectorDrawableCompat"></ImageView>
Is `tools:ignore="VectorDrawableCompat"` still required? Can it be fixed?

2021-03-15 10:21 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +    private ImageView mAnkidroid_logo;
nit: Typically we use camelCase variable names, rather than snake_case:

`mAnkidroidLogo`

2021-03-15 10:21 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +    private static boolean PORTRAIT_MODE = true;
I don't think this should be static. 

It should likely be a local variable in the method.

2021-03-15 10:21 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +    private OrientationEventListener myOrientationEventListener ;
```suggestion
    private OrientationEventListener myOrientationEventListener;
```

2021-03-15 10:21 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +                PORTRAIT_MODE = ((orientation < 100) || (orientation > 280));
(unsure): Is this the expected check for a horizontal orientation? Is there not an Android method?

2021-03-15 10:21 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +                if(PORTRAIT_MODE)
Style: [one space before an if](https://github.com/ankidroid/Anki-Android/wiki/Code-style#white-space-should-be-used-in-the-following-cases)

```suggestion
                if (PORTRAIT_MODE)
```

2021-03-15 10:21 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +                //if device is in horizontal mode then screen might not have enough space for ankidroid logo
code style: [one space before a comment](https://github.com/ankidroid/Anki-Android/wiki/Code-style#white-space-should-be-used-in-the-following-cases)

```suggestion
                // if device is in horizontal mode then screen might not have enough space for ankidroid logo
```

2021-03-15 10:21 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +                else
Code style: [else should have braces](https://github.com/ankidroid/Anki-Android/wiki/Code-style#the-if-else-class-of-statements-should-have-the-following-form)

2021-03-15 10:38 UTC, Akshay0701 commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                        tools:ignore="VectorDrawableCompat"></ImageView>
to be honest with you , i don't really know much about  "VectorDrawableCompat" ,android studio recommended it ,i am googling to know more about it , do you want me to remove `tools:ignore="VectorDrawableCompat`

2021-03-15 10:41 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +                PORTRAIT_MODE = ((orientation < 100) || (orientation > 280));
yes there is method `getResources().getConfiguration().orientation` which return orientation of device.
but in this case i wanted to listen when user rotate phone to "PORTRAIT_MODE" ,that is the main reason i created listener for this task .

2021-03-15 10:46 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +    private static boolean PORTRAIT_MODE = true;
actually i declared this variable to global , because i thought we will require this variable in future,
i will make changes accordingly : )

2021-03-15 10:53 UTC, Akshay0701 commented
i changed code accordingly your suggestion , take a look :)

2021-03-15 20:18 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                        tools:ignore="VectorDrawableCompat"></ImageView>
Understanding why the warning occurs is the main thing. Once you understand why a warning is provided, then you can give a rationale for ignoring an issue, or fixing it. The warning explanation is typically shown in the IDE

In this case:

> To use VectorDrawableCompat, you need to make two modifications to your project. "First, set `android.defaultConfig.vectorDrawables.useSupportLibrary = true` in your `build.gradle` file, and second, use `app:srcCompat` instead of `android:src` to refer to vectordrawables."

https://android.googlesource.com/platform/tools/base/+/studio-master-dev/lint/libs/lint-checks/src/main/java/com/android/tools/lint/checks/VectorDrawableCompatDetector.java

So it's asking you to change `android:src` to `app:srcCompat`

2021-03-15 20:22 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +                PORTRAIT_MODE = ((orientation < 100) || (orientation > 280));
This solution: https://stackoverflow.com/a/14929272/13121290 seems like it would be a better choice as it's using the system definitions. 

What do you think?

2021-03-15 20:28 UTC, david-allison-1 requested changes
Nearly there! Thanks for this. Looks awesome

* fix the warning
* fix whitespace
* private variables

2021-03-15 20:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +    private OrientationEventListener myOrientationEventListener ;
I think both of these can be moved inside the method. They're only used in `initAllContentViews`

2021-03-15 20:28 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                    android:id="@+id/MyAccountLayout"
nit: Could you revert the indentation changes of this file - a lot of lines here don't need to have changed. 

Comparison:

[Required changes](https://github.com/ankidroid/Anki-Android/pull/8182/files?w=1#diff-4e7a79289d760324b43dd89cee615ba3e3e9e179535532cc3b6b2c6b6a29cd5f)  
[Actual Changes](https://github.com/ankidroid/Anki-Android/pull/8182/files#diff-4e7a79289d760324b43dd89cee615ba3e3e9e179535532cc3b6b2c6b6a29cd5f)

2021-03-16 03:10 UTC, Akshay0701 commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                    android:id="@+id/MyAccountLayout"
actually entire code is same, i just added image to it , but just because one image is been added to middle of code, all other code sift to down by one line , and it shows it changed .

2021-03-16 03:50 UTC, Akshay0701 commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                    android:id="@+id/MyAccountLayout"
to be honest with you,
### whenever i tried to revert ,it add this few line automatically in account xml 
![Capture](https://user-images.githubusercontent.com/52353967/111252865-11366480-8638-11eb-9174-f71cea21d3b6.PNG)

### and then shows this message 
![Capture](https://user-images.githubusercontent.com/52353967/111252977-5195e280-8638-11eb-87d9-ec1144a2510c.PNG)

it is only showup for old commits ,for new commit this is not occuring. 
each time i tried to revert , it automatically add those lines , shows message to commit them :(

2021-03-16 05:46 UTC, Akshay0701 commented
i am so sorry @daniel-svard , i am really sorry , i created so many mess here , but i finally figured out and 
reverted ` 2906d1eb18a32ba37e36dd72504e1ee8fafc2` commit and i resolved unnecessary changes in lines of account.xml ,you can take a look now.

2021-03-16 22:40 UTC, david-allison-1 requested changes
Tiniest of changes, then good to go, thanks so much for the effort! ❤

PS: Just saw your messages - you might want to investigate what a merge conflict in git is, and how to resolve it for the future. 

Git takes a very long time to get used to, with quite a steep learning curve. Each time you learn, you find another situation where you no longer say "I'm not sure what's going on here", but keep pushing, it's one of the most useful tools that you can have, and the effort is worth it.

2021-03-16 22:40 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +                if(PORTRAIT_MODE){
https://github.com/ankidroid/Anki-Android/wiki/Code-style#white-spaces

```suggestion
                if (PORTRAIT_MODE) {
```

2021-03-16 22:40 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +                }else {
```suggestion
                } else {
```

2021-03-17 02:56 UTC, Akshay0701 commented
Thank You @david-allison-1 for guiding and your patiences, i never thought version controlling will this hard to manage, but i am now going to learn in depth of git :)

2021-03-17 04:24 UTC, david-allison-1 requested changes
Could you replace `ankidroid_logo.png` with a `svg`?

2021-03-17 08:28 UTC, david-allison-1 reviewed
Please check the corrections in Android Studio rather than committing directly on GitHub - they should fix the warning

Other than that, looks good!

2021-03-17 08:28 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                    android:src="@drawable/ankidroid_logo"
```suggestion
                    app:srcCompat="@drawable/ankidroid_logo"
```

2021-03-17 08:28 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                    tools:ignore="VectorDrawableCompat"></ImageView>
```suggestion
                    />
```

2021-03-17 09:21 UTC, david-allison-1 reviewed
@Akshay0701 Confirming that the new `srcCompat` was tested on an emulator? Will approve if so. Thanks for the patience :D

2021-03-17 09:34 UTC, Akshay0701 commented
i tried this changes on my devices and tablet emulator as well , its good .

2021-03-17 11:03 UTC, david-allison-1 approved these changes
Perfect, thanks! Note to maintainers: Squash/Merge.

2021-03-17 15:56 UTC, Arthur-Milchior commented
Would you accept to copy images to the PR message. Keeping the initial message updated with current description and screenshot. This help doing a review by allowing me not to read all discussion again and check which images are correct now and which one comes from a previous version

2021-03-17 17:45 UTC, Akshay0701 commented
@Arthur-Milchior yes, i added all details of work done till now in initial message.

2021-03-18 16:16 UTC, mikehardy requested changes
I still like this but on review it is not good to go

I have concerns as detailed about lifecycle handling and the handling of specific orientations

2021-03-18 16:16 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +                }
```suggestion
                // if device is in horizontal mode then screen might not have enough space for ankidroid logo
                // so we will invisible logo for horizontal mode only
                if ((orientation < 100) || (orientation > 280)) {
                    mAnkidroidLogo.setVisibility(View.GONE);
                } else {
                    mAnkidroidLogo.setVisibility(View.VISIBLE);
                }
```

If the variable is only used in one spot, the temp variable is not needed

2021-03-18 16:16 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +                boolean PORTRAIT_MODE = ((orientation < 100) || (orientation > 280));
this does not handle ORIENTATION_UNKNOWN, which is -1, except by accident
https://developer.android.com/reference/android/view/OrientationEventListener#ORIENTATION_UNKNOWN
Maybe better to be explicit and add that case explicitly?

`((orientation == OrientationEventListener.ORIENTATION_UNKNOWN) || (rest of cases here)` ?

2021-03-18 16:16 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +        myOrientationEventListener.enable();
Where is .disable called? https://developer.android.com/reference/android/view/OrientationEventListener#disable()

If you register a listener, you must always unregister it at the appropriate time using the correct android application/activity/view/fragment lifecycle hooks

currently this is executed in onCreate
I submit it should be in onResume, and `.disable` should be called in onPause

Additionally, how does this handle initial state? We are listening for changes now but there is no check for state prior to listening.

I think:
- extract the actual implementation of "taking an orientation int and toggling view GONE/VISIBLE" to a separate method
- have the listener simply call that method
- make the listener a member variable that you create in onCreate
- override onResume to `.enable` listening for future changes
- [check current state](https://developer.android.com/reference/android/content/res/Configuration.html#orientation) for [ORIENTATION_PORTRAIT](https://developer.android.com/reference/android/content/res/Configuration#ORIENTATION_PORTRAIT) in onResume and call the new extracted method to handle current state
- override onPause to `.disable` listening

Then it should handle all the cases.

2021-03-18 16:31 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +        myOrientationEventListener.enable();
thanks for covering all corner case mike sir , i will make changes according to your suggestion : )

2021-03-18 18:06 UTC, Akshay0701 commented
okay this thing i implemented in last commit ,
->extracted main implementation to `checkOrientation` and `initializeOrientationListner` methods,
->called checkOrientation method in side initializeOrientationListner methods,
->created listener and imageview as member variable to get access in `onResume` and `onPause` methods,
->overridden onResume to .enable listener for future changes,
->called initializeOrientationListner in onResume method,
->overridden onPause to .disable listener.

2021-03-18 18:27 UTC, mikehardy requested changes
still not handling check of current state I think?

2021-03-18 18:27 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +        initializeOrientationListner();
This should be in onCreate - you only need to initialize it once
onResume/onPause will just handle the enable/disable

```suggestion
        initializeOrientationListener();
```

2021-03-18 18:27 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +    public void initializeOrientationListner() {
```suggestion
    public void initializeOrientationListener() {
```

2021-03-18 18:27 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +        initializeOrientationListner();
I don't see handling of current state. We are listening for *future* states but what about the current state, if the user opens the activity *for the first time* already in horizontal mode? Does the listener call back immediately with current state? Or do we need to check it manually + then listen?

I think we need to check it manually + then listen. You are already setting up the listener, so you just need to add the manual check as explicitly specified in prior comment:

> - [check current state](https://developer.android.com/reference/android/content/res/Configuration.html#orientation) for [ORIENTATION_PORTRAIT](https://developer.android.com/reference/android/content/res/Configuration#ORIENTATION_PORTRAIT) in onResume and call the new extracted method to handle current state

2021-03-19 04:36 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +        initializeOrientationListner();
okay your right ,i will initialize listener for one time in onCreate function and before initialization  i will handle current state by calling `handleCurrentOrientationState` method.

2021-03-19 05:26 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +        initializeOrientationListner();
Mike, should i handle current state in initializeOrientationListner method before intializiation of listener ? or do i have to handle current state in onCreate method ?

2021-03-19 17:33 UTC, mikehardy requested changes

2021-03-19 17:33 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +        checkOrientation(getResources().getConfiguration().orientation);
This is not correct, I was very specific in my comments.
Current orientation must be handled in onResume, that's when the Activity is actually presented and interactive *after* all Configuration changes. Configuration can change between onCreate and onResume.

You do not appear to be aware of the Activity lifecycle in Android and what it means, please study it so we may avoid more back and forth: https://developer.android.com/guide/components/activities/activity-lifecycle#save-simple,-lightweight-ui-state-using-onsaveinstancestate

Additionally I actually linked the constants in use, did you notice that the getConfiguration().orientation API returns different number values in the constants than the orientation listener? They are not compatible, so you may not simply re-use the same orientation test with the two different sets of orientation constants.

2021-03-19 17:56 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +        checkOrientation(getResources().getConfiguration().orientation);
yes i am learning about activity life cycle and sorry for my misunderstanding , 
so now i have to handle current state in onResume only ,
i will create `handleCurrentOrientationState` method for handling current state in onResume,
and will use constants `ORIENTATION_LANDSCAPE` in method to support  getConfiguration().orientation API

2021-03-19 19:01 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +        checkOrientation(getResources().getConfiguration().orientation);
I might do some mistake , but I will keep improving those untill it perfectly fixed : )

2021-03-19 21:40 UTC, mikehardy approved these changes
Looks like a thing of beauty to me now! And knowing the activity lifecycle / how to register/unregister things at the right time is a fundamental Android thing - knowing that will help you forever, when developing Android stuff

Thanks!

2021-03-19 21:40 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +        checkOrientation(getResources().getConfiguration().orientation);
you got it now: perfectly fixed I think

2021-03-19 21:43 UTC, merged

2021-03-26 21:01 UTC, david-allison-1 commented
Screnshots:

<details><summary>While Screen loading</summary>

![image](https://user-images.githubusercontent.com/62114487/112692143-6105fe80-8e76-11eb-88fc-0be6e68739e4.png)


</details>


<details><summary>After screen loaded</summary>

![image](https://user-images.githubusercontent.com/62114487/112692162-6e22ed80-8e76-11eb-8058-cbead457c9ae.png)

</details>

2021-04-05 18:36 UTC, mikehardy commented
Hi there!

Just a friendly notice (one per person for PRs merged in March, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for March 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

Thanks!