Add accessibility mention to PR template
ankidroid/Anki-Android pull request #8189
Opened 2021-03-14 01:15 UTC by Arthur-Milchior

2021-03-14 04:33 UTC, david-allison-1 commented on .github/pull_request_template.md
> +- [ ] UI Changes: they satisfy Android accessibility test https://developer.android.com/guide/topics/ui/accessibility
```suggestion
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)
```

2021-03-14 04:34 UTC, david-allison-1 requested changes
Discussed on Discord - I didn't feel the landing page was useful (information overload), a concrete action is better and much less intimidating.

EDIT: But! I'm for the change, just feel we can improve the wording

2021-03-14 04:52 UTC, Arthur-Milchior commented
Accepting David's version

2021-03-14 04:52 UTC, merged

2021-03-14 04:52 UTC, david-allison-1 approved these changes

2021-03-14 18:26 UTC, mikehardy commented
Love this!

2021-04-05 18:35 UTC, mikehardy commented
Hi there!

Just a friendly notice (one per person for PRs merged in March, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for March 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

Thanks!