Remove codecov
ankidroid/Anki-Android pull request #8190
Opened 2021-03-14 02:21 UTC by Arthur-Milchior

Currently, it seems only negative to me.
It adds far too much comment, making the code read really hard. Indeed, when there is an empty line, it is not shown as an erroneous line, so it put a new comment after each empty line

Furthermore, it shows as broken commit while we are actually accepting it. Making it hard to check when there is really worry, as with unit test, and when it's only a covering problem, which currently is not something we work on.

2021-03-14 02:34 UTC, david-allison-1 reviewed
Nit:

Is there a way that we can continue to receive metrics, but ensure the check always goes green (setting up codecov to not penalise a coverage reduction for example?)

At some point in the future we'll want a greater focus on coverage (we're probably a year and a half away from it IMO), having the codecov message is a good push in the right direction.

But agreed: Right now it's providing little value due to the flakiness and differing priorities

2021-03-14 03:28 UTC, Arthur-Milchior commented
![2021-03-14-042754_1087x1146_scrot](https://user-images.githubusercontent.com/357361/111056225-b0fbc300-847d-11eb-9179-58985ea35a5d.png)
is really hard to read according to me mostly

2021-03-14 04:53 UTC, david-allison-1 approved these changes
Yeah, you're right

2021-03-14 20:26 UTC, mikehardy requested changes
codecov is not going away, this is the wrong approach

You want to change settings: https://github.com/ankidroid/Anki-Android/blob/master/.codecov.yml

The thing that I agree with you on is that reviewing the code is a nightmare with the coverage comments in the files themselves.

I like the coverage submission  and I like the comment on the PR itself so people know coverage is checked, and we may see diffs

Change this to a codecov config change that tunes PR comments out and I can merge 

To be specific you want this I believe https://github.com/stellargraph/stellargraph/pull/1036/files

2021-03-19 19:04 UTC, mikehardy commented
I pushed a change to the codecov config that disables diff comments (I think! we will see) and also allows a little bit of variability in coverage since our unit tests have time dependencies that can force different conditional branches in different runs and thus vary our coverage. That should have things all tuned up.

2021-03-19 19:04 UTC, closed without merging

2021-03-20 05:20 UTC, Arthur-Milchior commented
Thanks a lot

2021-03-20 14:02 UTC, mikehardy commented
No problem - I still haven't seen the effect I am looking for but I think that may be because people branched for their PRs prior to my change, in other words it may take a moment for the tuning to actually filter in to people's PRs. We can take further action if it is not working well within a few days though on new PRs. I want my clean diffs back in the web UI as well :-)