Added increment/decrement buttons for "New cards/day" preference
ankidroid/Anki-Android pull request #8191
Opened 2021-03-14 03:03 UTC by bhatushar

## Added increment/decrement buttons for "New cards/day" preference

## Purpose / Description
Feature request was made to add + and - buttons to "New cards/day" preference in Deck options. This PR implements that feature.

## Fixes
Fixes issue #8024 

## Approach
Created a new class `com.ichi2.preferences.IncrementerNumberRangePreference` which extends `com.ichi2.preferences.NumberRangePreference` and adds two buttons to the preference, one for increment and one for decrement. This class can be used for other numerical preferences as well.

## How Has This Been Tested?

Emulated on API 29, Android 10.0. Worked as expected.

## Output

![output](https://user-images.githubusercontent.com/21220253/111055787-612df380-849f-11eb-8f57-d5cdb3d948d0.png)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

2021-03-14 04:05 UTC, david-allison-1 requested changes
Looks good to me, thanks!

Could you try moving both buttons to the right hand side, and slightly decreasing their width.

I feel that having to "do" and "undo" close to each other allows users to more easily fix any time they click the button too much.

Could I also confirm that this has been tested with the max/min, it looks like it'll work from the code, but I'd like to confirm.

PS: Please see these comments as a discussion. Please feel free to disagree or ask for clarification. This is a collaborative approach :)

2021-03-14 04:55 UTC, bhatushar commented on AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.java
> +        // Remove mEditText, mIncrementButton, mDecrementButton before removing mLinearLayout
Yes, that's needed. If we don't explicitly remove the views on closing the dialog, it crashes the next time we open those settings.

2021-03-14 04:56 UTC, bhatushar commented on AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.java
> +        mIncrementButton.setText("+");
Sure, I can do that. I just need to know where in 02-strings.xml should I place them. Is there a section for this in the file or should I just append them at the end?

2021-03-14 05:00 UTC, bhatushar commented
> Could you try moving both buttons to the right hand side, and slightly decreasing their width.

I have a feeling that keeping those buttons on the same side might result in accidental clicks. But I'm no UI designer so if you think it'll be okay to have them on the same side, let me and I'll do that. It's quite straightforward.

I'll fix up the width too.

> Could I also confirm that this has been tested with the max/min, it looks like it'll work from the code, but I'd like to confirm.

Yes, it's tested on that. The new class inherits from NumberRangePreference and uses the same validations methods as the parent.

2021-03-14 07:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.java
> +        mIncrementButton.setText("+");
The end's fine. Cheers :)

2021-03-14 07:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.java
> +        // Remove mEditText, mIncrementButton, mDecrementButton before removing mLinearLayout
Interesting... thanks! Could you include a comment explaining this.

2021-03-14 07:22 UTC, david-allison-1 commented
> > Could you try moving both buttons to the right hand side, and slightly decreasing their width.
> 
> I have a feeling that keeping those buttons on the same side might result in accidental clicks. But I'm no UI designer so if you think it'll be okay to have them on the same side, let me know and I'll do that. It's quite straightforward.
> 
> I'll fix up the width too.

You're closer to the issue - very happy for you to make the decision which you feel is best (which sounds like "leave it as it is").

Thanks :)

2021-03-14 07:23 UTC, bhatushar commented on AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.java
> +        // Remove mEditText, mIncrementButton, mDecrementButton before removing mLinearLayout
Will do!

Also, I've made a comment about your request to move the buttons to the right. Can you take a look at that?

2021-03-14 07:32 UTC, bhatushar commented
I've made all the changes that were requested.

2021-03-14 07:39 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="minus_sign" comment="Label for increment button in IncrementerNumberRangePreference">-</string>
```suggestion
    <string name="minus_sign" comment="Label for decrement button in IncrementerNumberRangePreference">-</string>
```

2021-03-14 07:40 UTC, david-allison-1 commented
Tiiny change, then good to go

2021-03-14 07:52 UTC, david-allison-1 commented
Note to maintainers: squash & merge

2021-03-14 07:53 UTC, david-allison-1 approved these changes
Thanks!! 🚀🚀🚀

2021-03-14 18:48 UTC, mikehardy approved these changes
This looks great, thanks @bhatushar and @david-allison-1 !

2021-03-14 18:49 UTC, merged

2021-03-16 15:38 UTC, eginhard commented
Thanks for this contribution, it looks great and is very convenient!

I only feel that it would be more intuitive to flip the positions of plus and minus and usually see it that way in other apps/websites. See also how on a number line higher numbers are on the right. This might be different in right-to-left languages like Arabic, but I'm not familiar with those. What do you and others think?

2021-03-16 16:00 UTC, bhatushar commented
@eginhard I guess it boils down to personal preference. + being on the right side seems more natural to me. 

Swapping their position is as easy as swapping two adjacent lines in the code, literally. But for a more dynamic solution, we might have to implement some mechanism to save user preference for button order. That *might* make things a bit bloated for a relatively small feature.

2021-03-17 14:49 UTC, eginhard commented
I don't mean to add a preference for this, but to automatically position the buttons based on the user's language. I'm not a UI expert, but found the following guidelines for these input steppers (just learned that term): https://www.nngroup.com/articles/input-steppers/

Google's Material Design guidelines also have details on sliders, which work similarly: https://material.io/components/sliders#anatomy

Both indeed recommend to flip the orientation for RTL languages, i.e. in this case `[-] 20 [+]` for LTR and `[+] 20 [-]` for RTL languages. I think the UI doesn't actually have proper RTL support at the moment (#4371), so for now it might be enough to use `[-] 20 [+]` as a default and add a TODO for RTL support.

2021-03-17 17:38 UTC, bhatushar commented
I was looking at them in the same way as upvote/downvote buttons, that's why I went for this order.

Your suggestion seems helpful, you can create a new issue for this. Or get this one re-opened?

One way to solve it would be to check for the directionality of the current language and accordingly determine the button order inside `IncrementerNumberRangePreference.onCreateDialogView()`.

2021-03-17 17:54 UTC, eginhard commented
I opened #8259 for now, some other steps might be necessary first to add RTL support at all.