Added "Send Exception Report" to Help menu.
ankidroid/Anki-Android pull request #8193
Opened 2021-03-14 04:25 UTC by ritvij14

## Pull Request template

## Purpose / Description
Added a `Send Exception Report` option to Help menu, to send the Exception report from ACRA manually by user.

## Fixes
Fixes #6565 

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)
Redmi Note 8 Pro

![WhatsApp Image 2021-03-14 at 9 52 46 AM](https://user-images.githubusercontent.com/51456744/111057161-23cf6300-84ab-11eb-9009-2b186c822378.jpeg)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

2021-03-14 04:26 UTC, ritvij14 commented
@david-allison-1 created a draft for this. Please have a look. And how should I start with the captcha service?

2021-03-14 04:47 UTC, david-allison-1 reviewed
Thanks! Initial feedback on the change is below - I'll mark this as "Pending Review" so other maintainers can discuss how we'd want to handle anti-spam.

2021-03-14 04:47 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/strings.xml
> +    <string name="send_exception_now" translatable="false">Send Exception report</string>
Move this to `02-strings.xml` to allow our users to translate it.

2021-03-14 04:47 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +        private static final Map<String, Long> lastClickMap = new HashMap<>();
No need for a map here - we only have a single key, it's equivalent to a variable but harder to reason about

2021-03-14 04:47 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                Toast.makeText(activity, "Report Submitted.", Toast.LENGTH_SHORT).show();
`UIUtils.showThemedToast` would be slightly less code

2021-03-14 04:47 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                Toast.makeText(activity, "Submitted already.", Toast.LENGTH_SHORT).show();
Could you extract the resources to an XML resources file to allow them to be translated.

2021-03-14 04:47 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +        final int minInterval = 60000;
Could you suffix the variable to specify what unit it's in (milliseconds: ms, seconds etc...)

2021-03-14 04:47 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                AnkiDroidApp.sendExceptionReport(
Have you tested this? Debug reports can be accessed: https://918f7f55-f238-436c-b34f-c8b5f1331fe5-bluemix.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/ankidroid

I don't see how this would stop the stack trace deduplication logic from firing - I'd expect each stack trace to be the same

2021-03-14 04:47 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                        new Throwable("Exception report sent by user manually"),
A custom exception type would be better than Throwable: possibly named `UserSubmittedException` - we already have `ManuallySubmittedException`, and may want to rename this to reduce confusion

2021-03-14 04:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                Toast.makeText(activity, "Report Submitted.", Toast.LENGTH_SHORT).show();
Toasts shouldn't end in a full stop

```suggestion
                Toast.makeText(activity, "Report submitted", Toast.LENGTH_SHORT).show();
```

2021-03-14 04:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                Toast.makeText(activity, "Submitted already.", Toast.LENGTH_SHORT).show();
```suggestion
                Toast.makeText(activity, "Report already submitted", Toast.LENGTH_SHORT).show();
```

2021-03-14 08:32 UTC, ritvij14 commented on AnkiDroid/src/main/res/values/strings.xml
> +    <string name="send_exception_now" translatable="false">Send Exception report</string>
@david-allison-1 just wanted to confirm, I myself checked for the other options and just found out that they are being stored in `03-dialogs.xml`. Should I put it there instead of strings?

2021-03-14 09:09 UTC, ritvij14 commented
@david-allison-1 completed all the required changes above.

2021-03-14 18:40 UTC, mikehardy requested changes
I am not concerned with spam until proven it is a problem, that's an easy way to keep a feature simple in my opinion. I do not think spam will be a problem personally, even from the automated testing in the firebase test lab on releases to play store.

I don't believe the UUID adds anything if the ACRA limiter data is cleared (as it should be), I would remove all that and just clear limiter data then verify the reports are going through.

I'm excited to have this one in there, I do a lot of issue triage for users and it would be useful to ask them to manually submit a report to see their information (especially after #8142 is added so I can maybe diagnose problems like Android 8 hardware render failures more easily...

2021-03-14 18:40 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                AnkiDroidApp.sendExceptionReport(
Indeed, you will need to clear ACRA "limiter" data prior to sending or we cannot meet the goal of the API which is to definitely send an exception report right now

Example of API I mean https://github.com/ankidroid/Anki-Android/pull/6859/files

Here is ACRA source for the area in case it is useful https://github.com/ACRA/acra/blob/master/acra-limiter/src/main/java/org/acra/

The test ACRAlyzer instance should definitely be consulted to make sure that even though you are submitting the same stack each time, it goes through each time

2021-03-14 20:48 UTC, ritvij14 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                AnkiDroidApp.sendExceptionReport(
@mikehardy how should I be using the ACRAlyzer instance? I added the `deleteACRAlimiter()` function call, but I still cannot see the exception report from my device on the Acralyzer link.

2021-03-14 21:03 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                AnkiDroidApp.sendExceptionReport(
That suggests to me that you are likely not set up correctly for testing crash reports yet

The "test crash" button on the bottom of advanced preferences should be used as the known-good test until you successfully see reports

*every* time you want to successfully send a crash report you must allow the app to do so, for debug builds we assume crash reports are worthless so you have to manually toggle it on in settings first from "never" to one of the report send options that will actually send

That actually reminds me of a separate problem: If the user is set to "never" for crash reports, we will need to detect that and have a simple dialog that says anything like "You have requested to send an exception report right now, but your error report setting is "Never" so sending reports is prohibited, please choose another error report setting and try again" or similar

2021-03-14 21:32 UTC, david-allison-1 commented
> I'm excited to have this one in there, I do a lot of issue triage for users and it would be useful to ask them to manually submit a report to see their information (especially after #8142 is added so I can maybe diagnose problems like Android 8 hardware render failures more easily...

Question regarding the limiter: won't clearing this mean that all error reports will be sent again if they occur, rather than just ensuring that this single type of exception will always be sent?

2021-03-14 21:52 UTC, ritvij14 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                AnkiDroidApp.sendExceptionReport(
@mikehardy yes I checked the settings and the report doesn't go even after choosing the option as Always. Comparing the code of the test crash option. The only difference is that the app is forcibly doing a RunTime Exception there, while here I am doing only a `sendExceptionReport()` function call. I think instead of sending a report, I should cause a RunTime Exception forcibly and that will take care of sending the complete report of any errors that happened before that time. 
Right?

2021-03-14 21:54 UTC, mikehardy commented
> > I'm excited to have this one in there, I do a lot of issue triage for users and it would be useful to ask them to manually submit a report to see their information (especially after #8142 is added so I can maybe diagnose problems like Android 8 hardware render failures more easily...
> 
> Question regarding the limiter: won't clearing this mean that all error reports will be sent again if they occur, rather than just ensuring that this single type of exception will always be sent?

Yes, one more time. But we hardly ever crash now so this is not a serious concern to me vs definitely getting this manually requested report every single time (that is the essence of the feature) and not being fancy about it. In fact, I could argue that if a user is sending a manual report it might be good to re-catch any of their related crashes... - a crash limiter reset is a very tiny deal in other words. We reset them every version upgrade as well

2021-03-14 21:56 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                AnkiDroidApp.sendExceptionReport(
Throwing an exception will actually crash the app, I don't think that is a great user experience when it should not be necessary? It will affect Google Play stats as well, appearing as a real crash (when it is not), so I do not like that

Assuming the test crash button is sending the report, then the next task is to determine why sendExceptoinReport is not working while a real crash is. They should be roughly equivalent?

2021-03-14 22:07 UTC, ritvij14 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                AnkiDroidApp.sendExceptionReport(
Yes, I agree with your point. And to be honest I am also confused as to why the sendExceptionReport function is not working. They seem to be equivalent, but I am not completely sure how ACRA is handling the reports on this line-
https://github.com/ankidroid/Anki-Android/blob/14af04df24633a25ad32a52ccd526944f893909c/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java#L412

2021-03-14 22:34 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                AnkiDroidApp.sendExceptionReport(
It is odd - not sure what to say except to trace through it, perhaps with a debugger and breakpoints or similar, or if there is a way to set ACRA to a verbose logging mode in it's configuration on top of AnkiDroidApp and watch logcat

2021-03-15 05:21 UTC, ritvij14 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                AnkiDroidApp.sendExceptionReport(
@mikehardy can I also ask this doubt on ACRA google group, with reference to Ankidroid?

2021-03-15 10:37 UTC, ritvij14 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                AnkiDroidApp.sendExceptionReport(
@mikehardy I think I finally found what's happening.
While doing a Test Crash from Advanced settings, during the crash it shows a dialog which is the ACRAdialog in this case. It asks for sending report/cancel and also shows a checkbox which says `Send error reports automatically`
I noticed that after pressing Report (which the checkbox checked) all the exception reports from my new option in Help Dialog went to Acralyzer automatically. So we need to show that dialog, or maybe implement a part of its functionality for this option to work by itself.
What should I do in this case?

2021-03-15 12:10 UTC, ritvij14 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                AnkiDroidApp.sendExceptionReport(
I also found that for some reason, on choosing Always Report, it doesn't sent the report, but when we allow to send automatically from the AnkiCrashDialog, it starts sending reports properly.

2021-03-15 13:21 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                AnkiDroidApp.sendExceptionReport(
Those settings are based on the user's preference for sending reports and affect them. It is tied to user preferences

I do not want to alter the user's setting in general but they are explicitly asking to send the report this time so that implies consent.

Perhaps sendExceptionReport needs a new API that allows to send in an explicit preference value as an override to existing, and that value should be `@Nullable`. If it is null, it does the existing logic where it looks at preference values etc. If it is not null you use the value sent.

For this feature then you send in the value for Always ?

That could work?

https://github.com/ankidroid/Anki-Android/blob/b34276374a6259e64b790966a10e23a881865d86/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java#L152-L156

You can see how they are chained together already

https://github.com/ankidroid/Anki-Android/blob/b34276374a6259e64b790966a10e23a881865d86/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java#L384-L413

So there would be a new method at the bottom of that stack with one more parameter, and the existing method would just grab the report mode

https://github.com/ankidroid/Anki-Android/blob/b34276374a6259e64b790966a10e23a881865d86/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java#L403

and then delegate to your new method that has the rest of the implementation from that last method but using the new parameter

Then in your new feature, you send the "always" report mode explicitly

2021-03-15 15:28 UTC, ritvij14 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                AnkiDroidApp.sendExceptionReport(
@mikehardy I have 2 doubts:

1) If I choose Always in settings then why is it not sending the report directly? I see it's definitely setting it in shred preferences in this part

https://github.com/ankidroid/Anki-Android/blob/b34276374a6259e64b790966a10e23a881865d86/AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java#L699-L707

2) If I make another function for `sendExceptionReport()`, how will the new parameter function exactly? Does this function set the reporting mode to Always, send the report and then reset it?

2021-03-15 17:55 UTC, ritvij14 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                AnkiDroidApp.sendExceptionReport(
@mikehardy I have done it in the 2nd method, for now, except that I set the reporting mode to always and then switched it back to ask in the `execute()` function of the option that I created itself. I did that because we already have a `sendExceptionReport(Throwable e, String origin, @Nullable String additionalInfo)` and I thought the strings types of the 3rd parameter might conflict)

2021-03-16 02:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                exceptionReportItem
I feel this would be better under `Get Help`

2021-03-16 02:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                    getInstance().setAcraReportingMode(AnkiDroidApp.FEEDBACK_REPORT_ASK);
Ideally we should show the screen without changing the settings. if the setting is `always`. We want the user to be able to add a comment

2021-03-16 02:41 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/strings.xml
> +    <string name="send_exception_now" translatable="false">Send Exception report</string>
Dialogs would make more sense then, consistency is king.

2021-03-16 02:47 UTC, ritvij14 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                    getInstance().setAcraReportingMode(AnkiDroidApp.FEEDBACK_REPORT_ASK);
@david-allison-1 the settings don't change permanently. From what I saw on my device, if it was set to Never report, on doing this, it would show the Acra dialog. The acra dialog has a check box that corresponds to the Always option. But in this case, even selecting that wouldn't change the settings. If the user wants to change the setting, they have to do it from the settings menu.

What comment should the user be able to add for `always`? I will have to make a new dialog when the user taps on this option then right?

2021-03-16 02:50 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="help_dialog_exception_report_debounce">Report already submitted</string>
Sorry! Could we use `dialogs` here as well

2021-03-16 02:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                if (!reportMode.equals(AnkiDroidApp.FEEDBACK_REPORT_ALWAYS)) {
⚠️  When it comes to privacy, we don't want to change user settings without explicit permission. Ideally tell the user to change the setting in the settings, or add in an additional confirmation dialog, rather than change the setting permanently for them. We'll also need a "always send exception report as a dialog box" option.

2021-03-16 02:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +
If we're running under a test client, we don't want this

```java
        if (AdaptionUtil.isUserATestClient()) {
            UIUtils.showThemedToast(activity, activity.getString(R.string.user_is_a_robot), false);
            return;
        }
```

2021-03-16 02:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                    getInstance().setAcraReportingMode(AnkiDroidApp.FEEDBACK_REPORT_ASK);
In Debug mode the setting isn't persisted. In Release it is.

2021-03-16 02:51 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                    getInstance().setAcraReportingMode(AnkiDroidApp.FEEDBACK_REPORT_ASK);
We should ideally use the same dialog box as for 'ask', just accessing it via an API rather than setting the preference to `FEEDBACK_REPORT_ASK`

2021-03-16 02:54 UTC, ritvij14 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                if (!reportMode.equals(AnkiDroidApp.FEEDBACK_REPORT_ALWAYS)) {
@david-allison-1 yes I was also a bit confused about this part. Please have a look at this comment https://github.com/ankidroid/Anki-Android/pull/8193#discussion_r594327917

I have given 2 methods below it as well. If we don't change the settings ourselves we can't send the report. That's why I made sure it will ask everytime if not set to `ALWAYS`, so the user can decide whether they want to send or not.

2021-03-16 02:56 UTC, ritvij14 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +
Sorry sir, I didn't get this part :sweat_smile: could you please explain it once?

2021-03-16 04:09 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +
Add the code at the start of a method - if the user is running under an automated device such as the Firebase Test Lab, which is randomly pressing buttons, then we don't want to report the exception

2021-03-16 13:51 UTC, ritvij14 commented
@david-allison-1 I have done the changes I mentioned, and I have also disabled Acra after reporting. Should I put conditions to hiding the checkbox in Acra dialog as well?

2021-03-16 22:46 UTC, david-allison-1 requested changes
Very minor changes, implementation looks good, thanks!

2021-03-16 22:46 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                getInstance().getAcraCoreConfigBuilder().getPluginConfigurationBuilder(DialogConfigurationBuilder.class)
Do we need to disable this as well (I don't know)?

2021-03-16 22:46 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +            } else { sendReport(activity); }
```suggestion
            } else { 
                sendReport(activity); 
            }
```

2021-03-16 22:46 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +import static com.ichi2.anki.AnkiDroidApp.getInstance;
Remove these two and use `AnkiDroidApp.getInstance()`.

Having context for which class `getInstance()` refers to is important.

2021-03-16 22:46 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +        String reportMode = getSharedPrefs(getInstance().getApplicationContext()).getString(AnkiDroidApp.FEEDBACK_REPORT_KEY, "");
Move this inside `execute`, use `AnkiDroidApp.getSharedPrefs(activity)`

* It ensures that we get the current value every time
* It means that we can instantiate the class before `Application` is instantiated (useful for testing).

2021-03-17 03:46 UTC, ritvij14 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                getInstance().getAcraCoreConfigBuilder().getPluginConfigurationBuilder(DialogConfigurationBuilder.class)
@david-allison-1 before trying this method out, I also tried enabling just the dialog. But it didn't seem to work, so I think it won't matter much. As long as Acra is disabled, parts of Acra are also disabled.

2021-03-17 03:53 UTC, ritvij14 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +        String reportMode = getSharedPrefs(getInstance().getApplicationContext()).getString(AnkiDroidApp.FEEDBACK_REPORT_KEY, "");
`sendReport()` is using them so it will cause errors :sweat_smile:

2021-03-17 04:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                getInstance().getAcraCoreConfigBuilder().getPluginConfigurationBuilder(DialogConfigurationBuilder.class)
Definitely - we shouldn't be changing ACRA state

2021-03-17 04:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                sendReport(activity);
Does this send the report? Presumably the `preferences.edit().putBoolean(ACRA.PREF_DISABLE_ACRA, true).apply();` will be executed before the dialog has submitted the dialog.

Could you confirm in a comment that this will be OK

2021-03-17 06:39 UTC, ritvij14 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                sendReport(activity);
@david-allison-1 yes it works fine:

![20210317_120155](https://user-images.githubusercontent.com/51456744/111425544-51214880-8719-11eb-91ec-7cb0c57f4c34.gif)

![Screenshot from 2021-03-17 11-58-29](https://user-images.githubusercontent.com/51456744/111425556-554d6600-8719-11eb-9d47-b076a5987619.png)

2021-03-17 08:30 UTC, david-allison-1 approved these changes
Looks good to me. Thanks for your patience and fast replies!

2021-03-20 14:41 UTC, mikehardy commented
I was just reviewing this and I think it is about ready for merge, but a separate task that added a new parameter (for analytics) to the HelpDialog was merged #8257 so now there is a conflict

With apologies, can you rebase this to current and alter your code to have a new analytics action (SEND_EXCEPTION_REPORT constant or similar) and to do the right thing based on #8257?

This is a fortunate *and* unfortunate reality of working on a large project with lots of contributors, things move quickly and sometimes we have to alter our PRs in response to fresh changes

2021-03-20 14:41 UTC, mikehardy requested changes
Good to go I think, just needs reshaping to handle analytics feature added in help area

2021-03-20 15:56 UTC, ritvij14 commented
@mikehardy I have merged with the latest code and have also added an analytics event for when the user would press the Send Exception report option

2021-03-20 16:02 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java
> +        public static final String EXCEPTION_REPORT = "Exception report";
Maintains consistent capitalization with other events

```suggestion
        public static final String EXCEPTION_REPORT = "Exception Report";
```

2021-03-20 16:05 UTC, mikehardy commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="help_title_send_exception">Send Exception report</string>
I don't think a user will know what an "exception" is, but "troubleshooting" is widely understood. I would use "feedback" but I think we just send the report and don't ask for feedback, so that word does not quite fit

```suggestion
    <string name="help_title_send_exception">Send troubleshooting report</string>
```

2021-03-20 16:06 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +    private static class ExceptionReportItem extends Item implements Parcelable{
spacing, please consult our style guide https://github.com/ankidroid/Anki-Android/wiki/Code-style#white-spaces

```suggestion
    private static class ExceptionReportItem extends Item implements Parcelable {
```

2021-03-20 16:08 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +            if (reportMode.equals(AnkiDroidApp.FEEDBACK_REPORT_NEVER)) {
```suggestion
            if (AnkiDroidApp.FEEDBACK_REPORT_NEVER.equals(reportMode)) {
```

2021-03-20 16:11 UTC, mikehardy approved these changes
I made a couple of tiny changes to move this forward
This looks good to me, asking for a second scan from @david-allison-1 in case I missed something

2021-03-20 16:12 UTC, mikehardy commented
Oh wait - I see @david-allison-1 already scanned it in it's effectively final form. Good to go pending CI

2021-03-20 16:58 UTC, merged