Fixes Bug ankidroid#8192.
ankidroid/Anki-Android pull request #8195
Opened 2021-03-14 05:13 UTC by imaryandokania

## Pull Request template

## Purpose / Description 
The problem was with progressDialog title which was having space 

## Fixes
Fixes _Link to the issues._
 https://github.com/ankidroid/Anki-Android/issues/8192
## Approach
_How does this change address the problem?_
by changing "" to null 

## How Has This Been Tested?

Before fix

<img width="292" alt="Screenshot 2021-03-14 at 9 09 53 AM" src="https://user-images.githubusercontent.com/61244704/111058052-f20eca00-84b3-11eb-8e24-fa6497af5b82.png">

Solved by testing in emulator(After Fix)

<img width="292" alt="Screenshot 2021-03-14 at 9 08 33 AM" src="https://user-images.githubusercontent.com/61244704/111058022-b70c9680-84b3-11eb-8ea5-e34e67ae6012.png">

Tested on emulator: Pixel 3a API R

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-14 05:22 UTC, david-allison-1 requested changes
nitpick of the century... other than that, good to go!

2021-03-14 05:22 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +                mProgressDialog = StyledProgressDialog.show(MyAccount.this,null,
```suggestion
                mProgressDialog = StyledProgressDialog.show(MyAccount.this, null,
```

2021-03-14 05:33 UTC, david-allison-1 approved these changes
Thanks for the patience. Let's do this. 🚀🚀🚀🚀🚀

Awaiting CI to pass

2021-03-14 07:56 UTC, merged

2021-03-14 07:56 UTC, david-allison-1 commented
Thanks so much!

2021-03-14 17:08 UTC, Arthur-Milchior commented
I personally would have asked for more descriptive commit title, to help future browsing of commit list aand git blame. Thanks for noticing and fixing

2021-03-15 00:03 UTC, imaryandokania commented
> I personally would have asked for more descriptive commit title, to help future browsing of commit list aand git blame. Thanks for noticing and fixing

Definitely i will take care of these things in my future contributions !