Code cleaning and refactoring
ankidroid/Anki-Android pull request #8196
Opened 2021-03-14 05:53 UTC by TarekkMA

## Purpose / Description
Code cleaning and refactorings to Export classes and the ExportDialog class

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-14 05:54 UTC, TarekkMA commented
@Arthur-Milchior

2021-03-14 06:12 UTC, david-allison-1 requested changes
Tests are failing - not using the new API

```
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.java:130: error: no suitable constructor found for AnkiPackageExporter(Collection)
        AnkiPackageExporter exporter = new AnkiPackageExporter(getCol());
```

2021-03-14 06:12 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +     * @param did An long which specifies the deck to be exported
```suggestion
     * @param did A long which specifies the deck to be exported
```

2021-03-14 06:38 UTC, Arthur-Milchior reviewed
Thanks a lot for those cleaning. Really appreciate and I believe it'll improve the other PR.
Here are a few nits

2021-03-14 06:38 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +    private static ExportDialog newInstanceImpl(@NonNull String dialogMessage, @Nullable Long did) {
Adding "Impl" seems useless to me.

2021-03-14 06:38 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +        return newInstanceImpl(dialogMessage, null);
You could have just put
``` java
    public static ExportDialog newInstance(@NonNull String dialogMessage) {
        return newInstance(dialogMessage, null);
    }
```
and avoid adding an extra function name I think.

2021-03-14 06:38 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +                    ((ExportDialogListener) getActivity()).exportApkg(null, did, mIncludeSched, mIncludeMedia);
Why is it equivalent?
`exportApkg` takes a Lon which may be null, however it do not check for NOT_FOUND_DECK_ID currently. So this seems to potentially break things

2021-03-14 06:38 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
> +    public Exporter(Collection col, @NonNull Long did) {
/** 
* An exporter for content of deck `did`
*/

2021-03-14 06:38 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
> +    protected final boolean mIncludeSched;
Great. Thanks for adding those final. Clearly an improvement!

2021-03-14 06:38 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +     * @param did A long which specifies the deck to be exported
Could you please rebase and correct  it directly in the commit where it was introduced, rewritting it.

2021-03-14 06:41 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +        return newInstanceImpl(dialogMessage, null);
You are right I was thinking of the cids part of the other PR

2021-03-14 07:10 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +                    ((ExportDialogListener) getActivity()).exportApkg(null, did, mIncludeSched, mIncludeMedia);
Yeah, that's true. sorry about that I overlooked it.

2021-03-14 07:33 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +    private static ExportDialog newInstanceImpl(@NonNull String dialogMessage, @Nullable Long did) {
I'll take the rep for this one. I suggested it so there wasn't going to be a name conflict when an additional planned method would be added

2021-03-14 07:56 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +    private static ExportDialog newInstanceImpl(@NonNull String dialogMessage, @Nullable Long did) {
We won't have a name clash if the next PR (#8159) ,which will be based on this one, is merged. They all can have `newInstance`

2021-03-14 08:00 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +        return newInstanceImpl(dialogMessage, null);
I found an issue with this. The public method have `@NotNull did`. So passing null to it will cause a warning, but it is a warning we can ignore it.

Since this is a private static method, I can leave it as Impl for now and rename it in the next PR and won't be a big deal I think.

What's your opinion on this

2021-03-14 22:06 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +        return newInstanceImpl(dialogMessage, null);
I'd change @NonNull to @Nullable, and add a javadoc explaining that if did is null, then we export the whole collection

2021-03-14 22:07 UTC, Arthur-Milchior commented
Please let us know when you feel like this is ready for a new review

2021-03-14 22:09 UTC, TarekkMA commented
Oh sorry fory to add a comment. It is ready

2021-03-14 22:12 UTC, TarekkMA commented
Sorry I just saw you comment about the null annotations. Will do it innthe morning as I'm on my phone

2021-03-15 07:22 UTC, TarekkMA commented
Done. 

We will add the private `newInstance` on the other PR. and `newInstance(dialogMessage,did)` can be both `NonNull`

2021-03-17 17:01 UTC, david-allison-1 reviewed
One comment - rest looks good

2021-03-17 17:01 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +        args.putLong("did", did == null ? NOT_FOUND_DECK_ID : did);
@Arthur-Milchior (pinging as you were last here and may have context):

I feel that we should refactor here and just propagate `null` through here and stop switching from `null -> NOT_FOUND_DECK_ID -> null`

Is there a reason that we're not doing this?

Ref: https://github.com/ankidroid/Anki-Android/blob/41630a4a007c3961abbf9d35c74f6344d2f7ee1f/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java#L54-L102

2021-03-17 17:10 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +        args.putLong("did", did == null ? NOT_FOUND_DECK_ID : did);
Okay so you suggest removing `NOT_FOUND_DECK_ID`, and checking if `did == null` instead, right?

2021-03-17 17:20 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +        args.putLong("did", did == null ? NOT_FOUND_DECK_ID : did);
Oh I found the issue `Bundle.putLong()/getLong()` would only accept/return primitives. 

We can do it this
```java
    public static ExportDialog newInstance(@NonNull String dialogMessage, @Nullable Long did) {
        ExportDialog f = new ExportDialog();
        Bundle args = new Bundle();
        if (did != null) {
            args.putLong("did", did);
        }
        args.putString("dialogMessage", dialogMessage);
        f.setArguments(args);
        return f;
    }
```
and use this method for getting the value back
```java

    @Nullable
    private Long getDeckIdArgOrNull() {
        final long did = getArguments().getLong("did", NOT_FOUND_DECK_ID);
        return did == NOT_FOUND_DECK_ID ? null : did;
    }
```

But I find it to be much more verbose.

2021-03-17 17:22 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +        args.putLong("did", did == null ? NOT_FOUND_DECK_ID : did);
Yes, I think the reason is `getLong(key,def)`  require the def value to be primitive.

2021-03-18 01:42 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +        args.putLong("did", did == null ? NOT_FOUND_DECK_ID : did);
Okay, would be best to either:

* Add a comment explaining the strangeness
* Add a commit with a static `getNullableLong(Bundle , Long default)` method

Either choice and I'd be happy to accept this, looks good!

2021-03-18 04:00 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +        args.putLong("did", did == null ? NOT_FOUND_DECK_ID : did);
I can go with the second one, it will clean up the code.
Should we make BundleUtil class with this static method?

2021-03-18 04:45 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +        args.putLong("did", did == null ? NOT_FOUND_DECK_ID : did);
"NOT_FOUND_DECK_ID" is also used in DeckPicker. It is potentially set as preference for browserDeckIdFromDeckPicker . However this value is never read. Which lead me to suspect that REQUEST_BROWSE_CARDS request is entirely useless. Should be investigated. 

I guess that with this getNullableLong, there is no reason for this constant anymore

2021-03-18 05:04 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +        args.putLong("did", did == null ? NOT_FOUND_DECK_ID : did);
Did add a new `BundleUtils` class along with tests, and refactored out NOT_FOUND_DECK_ID from `ExportDialog`

2021-03-18 06:03 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/BundleUtils.java
> +    public static Long getNullableLong(@Nullable Bundle bundle, @NonNull String key) {
I thought that it would be implemented differently.
That if the key is in the bundle, you'd return the key value, otherwise null. This would allow to avoid using a magic constant DEFAULT_LONG_VALUE. I assume you can check whether a bundle has some key

2021-03-18 06:03 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/utils/BundleUtilsTest.java
> +public class BundleUtilsTest {
Thanks a lot for the tests

2021-03-18 06:19 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/utils/BundleUtils.java
> +    public static Long getNullableLong(@Nullable Bundle bundle, @NonNull String key) {
Oh, you are absolutely right. Forgot about that API. Will rebase and push shortly.

2021-03-18 06:27 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/utils/BundleUtils.java
> +    public static Long getNullableLong(@Nullable Bundle bundle, @NonNull String key) {
Done.

2021-03-18 10:10 UTC, Arthur-Milchior approved these changes

2021-03-18 12:55 UTC, david-allison-1 approved these changes
Very clean, thanks!!

2021-03-18 13:17 UTC, merged

2021-04-05 18:35 UTC, mikehardy commented
Hi there!

Just a friendly notice (one per person for PRs merged in March, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for March 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

Thanks!