Added 'browse cards' to deck context menu
ankidroid/Anki-Android pull request #8216
Opened 2021-03-15 00:25 UTC by ChaxuGarg

## Added View Cards List option in deck's context menu

## Purpose / Description
A feature request was made to add a view cards list option to the selected deck's context menu. This PR implements the feature.

## Fixes
Fixes #8187

## Approach
Created a new function `openCardBrowser` in DeckPicker.java which calls back the card browser for the selected deck by creating an Intent. Added a new Variable `CONTEXT_MENU_BROWSE_CARDS` that adds View Cards List option to Material Dialog and calls the function `openCardBrowser`.

## How Has This Been Tested?

Emulated on API 30, Android 10.0 and tested on Xiaomi Redmi Note 7 Pro Physical Device. Worked as expected.

## Checklist
_Please, go through these checks before submitting the PR._

* [x]  You have not changed whitespace unnecessarily (it makes diffs hard to read)
* [x]  You have a descriptive commit message with a short title (first line, max 50 chars).
* [x]  Your code follows the style of the project (e.g. never omit braces in `if` statements)
* [x]  You have commented your code, particularly in hard-to-understand areas
* [x]  You have performed a self-review of your own code
* [x]  UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
* [x]  UI Changes: You have tested your change using the [Google Accessibility Scanner]

2021-03-15 00:32 UTC, david-allison-1 approved these changes
Looks great and thanks for fixing the username - your GitHub contributions graph will fill up much more nicely now 👍 

Screenshots are listed in: https://github.com/ankidroid/Anki-Android/pull/8209#issuecomment-798989009

Awaiting CI, so blocked on https://github.com/ankidroid/Anki-Android/issues/8215

2021-03-15 01:37 UTC, david-allison-1 commented
@ChaxuGarg Could you pull `master` and rebase this against it. The checks should then pass.

2021-03-15 04:32 UTC, mikehardy commented
Sorry I broke the build and hung up progress on PR. In my previous office doing so would have earned me possession of a little rubber ducky we saved for the occasion, and you had to keep on your monitor until the next unfortunate person messed it up

This is the best I can do online: :duck: :desktop_computer:

2021-03-15 11:55 UTC, ChaxuGarg commented
Don't merge the branch yet @david-allison-1, found a bug, fixing it!

2021-03-15 12:05 UTC, ChaxuGarg commented
Before : When card browser was opened from browse cards of deck's context menu, card browser showed cards of Last Deck rather than of the selected deck.
Now: Fixed the issue!

2021-03-15 18:17 UTC, mikehardy approved these changes
LGTM as well - note the linked screen shots are just a little out of date, I was going to ask for a change to the wording + capitalization but it is already done :fireworks: - it is 'Browse cards' now, which works for me

I restarted the unit tests in CI as I think they failed for an unrelated reason. If they pass this is good to squash+merge

2021-03-15 18:19 UTC, mikehardy requested changes
Oh wait - actually I see the changes from the last commit - @david-allison-1 needs re-review, the unit test failure I think might be legit based on the alterations to CardBrowser

2021-03-15 20:40 UTC, david-allison-1 commented
Unit test failures are issues. @ChaxuGarg, could you check.

Presumably `getExtras()/getIntent()` returns null.

2021-03-15 20:44 UTC, david-allison-1 requested changes
A few questions aside from the test

2021-03-15 20:44 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        if (getIntent().getExtras().containsKey("did")){
Does this mean that a user can't change decks if viewed from this screen? 

How does this work if a user does try to change decks, and what is the intention?

Could you explain this in a comment

2021-03-15 20:44 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        } else  if(getDeckId() != null && getCol().getDecks().get(getDeckId(), false) != null) {
```suggestion
        } else if (getDeckId() != null && getCol().getDecks().get(getDeckId(), false) != null) {
```

2021-03-15 22:02 UTC, ChaxuGarg commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        if (getIntent().getExtras().containsKey("did")){
The user can change deck, the intention is to open the card browser for the particular deck when opened from that deck's context menu, or open the browser for last opened deck if card browser is opened from the navigation menu (the good old fashioned way).

2021-03-16 13:54 UTC, ChaxuGarg commented
@david-allison-1 @mikehardy Please check the new changes and close the issue if it can be merged now. Thanks for helping!!

2021-03-16 21:00 UTC, david-allison-1 reviewed
Mostly nitpicks - one question regarding a possible change in functionality

2021-03-16 21:00 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        Long did = getDeckId();
If I'm correct and this was an unintentional change, could you add in a unit test to ensure we don't have future regressions

2021-03-20 14:35 UTC, mikehardy commented
@ChaxuGarg no time pressure or expectations, just a note to say I think this was reviewed and is waiting on changes, but is close to merge

2021-06-01 13:00 UTC, ShridharGoel commented
@ChaxuGarg Are you planning to update this PR?

2021-06-02 12:51 UTC, david-allison-1 commented
Superseded by #9047

2021-06-02 12:51 UTC, closed without merging