Fix:8142 Adding Webview information to crash report
ankidroid/Anki-Android pull request #8225
Opened 2021-03-15 06:56 UTC by kartikeysaran

## Purpose / Description
Adding webview information to crash report

## Fixes
Fixes #8142 

## Approach
Retrieving the webview version name and code with the help of PackageManager and Package Info

## How Has This Been Tested?
This has been tested locally 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have performed a self-review of your own code

(https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-15 07:14 UTC, david-allison-1 reviewed
Thanks!!

To confirm with the reporter (@mikehardy)

* I presume that we want this to occur if the user is using the silent reporter
* We may want to add this is a separate field in the report, rather than appending it to the comment
* We may want to perform this at a different stage of reporting, so any additional reporters that we add will append this data

Could you provide a sample string that is submitted if this succeeds?

2021-03-15 07:14 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.java
> +                Log.e("Webview", "Android System WebView is not found");
```suggestion
                Timber.w(e, "Android System WebView is not found");
```

2021-03-15 07:14 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.java
> +            try {
Could you extract this to a method and ensure that it doesn't crash (probably catch `Throwable` here - we need these exception reports).

2021-03-15 07:17 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.java
> +            try {
@david-allison-1 I will update the code and push

2021-03-15 07:19 UTC, kartikeysaran commented
> Could you provide a sample string that is submitted if this succeeds?
The Webview information will be added to User's Comment so the comment would look like - "Users Comment  Webview Version Name :  , Version Code: "

2021-03-15 07:23 UTC, kartikeysaran commented
> * I presume that we want this to occur if the user is using the silent reporter
> * We may want to add this is a separate field in the report, rather than appending it to the comment
> * We may want to perform this at a different stage of reporting, so any additional reporters that we add will append this data

We can use DataStore Preferences under which the information of the webView can be saved and can be accessed from anywhere inside the application or we can have a static method for extracting this

2021-03-15 09:44 UTC, kartikeysaran commented
the webview information can be fetched from anywhere in the application by passing a webview to this method which will return the webview information
Ex output :
```
User-agent string: Mozilla/5.0 (Linux; Android 5.0; Nexus 4 Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/37.0.0.0 Mobile Safari/537.36
```
Reference :- [UserAgentString](https://developer.chrome.com/docs/multidevice/user-agent/)

2021-03-15 19:14 UTC, mikehardy requested changes
Thank you for taking this on @kartikeysaran ! I left a few requests in line while reviewing

2021-03-15 19:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.java
> +
You appear to have changed these lines unnecessarily - that makes it hard to read diffs. Please only change lines necessary to implement the required change - can you revert the change to these lines?

2021-03-15 19:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.java
> +    public static String fetchWebViewInformation( WebView webView ){
This does not follow our coding conventions - all projects have slightly varying conventions but they can typically be seen in the files you are working on, and should be followed. Frequently a project will have an actual document as well, as we do: https://github.com/ankidroid/Anki-Android/wiki/Code-style#white-spaces

Please correct the spacing here so it will match the rest of the project

2021-03-15 19:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.java
> +    public static String fetchWebViewInformation( WebView webView ){
The WebView parameter will have to be annotated `@Nonnull` if you are not checking it before de-referencing it

2021-03-15 19:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.java
> +        return webView.getSettings().getUserAgentString();
This should be wrapped in a try/catch where we catch `Throwable` - that is not a normal practice in Java (catching Throwable - it is generally not recommended) but in this context where the app is already potentially crashed and is sending an exception report, we never ever want to crash, so the crash reporting code itself should run no matter what happens and catching Throwable makes sure that happens

2021-03-15 19:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.java
> +                mHelper.sendCrash(mUserComment.getText().toString(),"");
The WebView information should be in it's own data field so it is always sent, it should not be in the comment - only the actual user comments (if the user types any) should be in the comments field.

I'm not 100% sure how to make a new data field in an ACRA report but the test ACRA instance should have lots of examples and I think we do it elsewhere (like, the media codecs in the report) so there may already be an example to copy?

2021-03-18 15:40 UTC, mikehardy requested changes
This does not appear to be addressed from a previous look at this:

> The WebView information should be in it's own data field so it is always sent, it should not be in the comment - only the actual user comments (if the user types any) should be in the comments field.

I'm not 100% sure how to make a new data field in an ACRA report but the test ACRA instance should have lots of examples and I think we do it elsewhere (like, the media codecs in the report) so there may already be an example to copy?


And I left some other comments in the code

2021-03-18 15:40 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.java
> +    public static String fetchWebViewInformation ( @NonNull WebView webView ) {
we have a style guide for code formatting, and the rest of the code is obviously different then your proposed method, that's not a good practice when working with existing codebases - https://github.com/ankidroid/Anki-Android/wiki/Code-style#white-spaces

Please read that and format well vs our project: blank line before your method, consistent spaces etc

2021-03-18 15:40 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.java
> +        } catch ( Exception e ) {
I believe we mentioned we should catch Throwable here vs Exception? Normally you would never do that but *we are already crashing* the whole system might be going down due to out of memory (an Error, not an Exception) and trying to use the web view could throw OutOfMemoryError, meaning we don't capture the report.

Please catch Throwable

2021-03-18 15:40 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.java
> +    public static String fetchWebViewInformation ( @NonNull WebView webView ) {
You are returning a String no matter what so you may mark the return value `@NonNull` as well, that can help linters / code static analysis tools

2021-03-18 15:40 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.java
> +    public static String fetchWebViewInformation ( @NonNull WebView webView ) {
I don't see where this information is ever actually used in the report?

2021-03-19 07:20 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.java
> +    public static String fetchWebViewInformation ( @NonNull WebView webView ) {
Will push the code a/c

2021-03-21 10:18 UTC, closed without merging