Add check on back button to exit DeckPicker
ankidroid/Anki-Android pull request #8228
Opened 2021-03-15 10:29 UTC by SujyotRaut

## Back button check to exit DeckPicker

## Description
_This PR is in response to the #8226 feature requested is that when back button is pressed it does not check twice and closes the DeckPicker so added the feature to exit DeckPicker we have to press back twice_

2021-03-15 12:37 UTC, kartikeysaran requested changes
I don't think there is any need of this instead in the OnBack function in the DeckPickerActivity we can simply show a dialog stating Do you want to exit

2021-03-15 12:40 UTC, kartikeysaran requested changes

2021-03-15 12:40 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                if (mBackPressedTime + 2000 > System.currentTimeMillis()) {
I don't think there is any need of this instead in the OnBack function in the DeckPickerActivity we can simply show a dialog stating Do you want to exit

2021-03-15 14:30 UTC, SujyotRaut commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                if (mBackPressedTime + 2000 > System.currentTimeMillis()) {
Sure we can i will start working on it tomorrow

2021-03-15 18:32 UTC, mikehardy commented
Please do not delete the pull request template, it helps us a lot, we want to see all the information filled in.
Please pay special attention to annotating the original issue in a way that GitHub will cross link it, that is `Fixes #issuenumber`

Please edit the PR description and put the pull request template back in it (you can find in the .github directory), then fill it in

2021-03-16 04:35 UTC, SujyotRaut commented
sorry about the PR template since i am new to open source i didn't know about that but i updated the PR description

2021-03-16 05:15 UTC, SujyotRaut commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                if (mBackPressedTime + 2000 > System.currentTimeMillis()) {
Since the back press doesn't kill the app process it just closes the app. Exit dialog might not be suitable, a simple toast might be enough.
What are your thoughts on this ?

2021-03-20 16:01 UTC, mikehardy commented
@david-allison-1 you accepted the linked issue, but it is ill-defined, so it is producing an ill-defined PR here with feedback based on opinions of various people.

As mentioned in the related issue, I don't know if this is even wanted, it seems like a solution in search of a problem to me, but maybe that's just opinion?

Could you please lay out exactly how this should behave, so the PR may achieve focus and - if wanted - acceptance + merge?

2021-03-21 06:12 UTC, david-allison-1 commented
Apologies. Spec listed: https://github.com/ankidroid/Anki-Android/issues/8226#issuecomment-803519439

2021-03-21 06:15 UTC, david-allison-1 requested changes
Let's make this simpler - just use a boolean, rather than a timer.

2021-03-21 06:15 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                    Toast.makeText(this, "Press back again to close the app", Toast.LENGTH_SHORT).show();
`UIUtils.showThemedToast`

2021-03-21 06:15 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                    Toast.makeText(this, "Press back again to close the app", Toast.LENGTH_SHORT).show();
Extract the string to a resource file (likely `02-strings`: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#adding-translations)

2021-04-03 08:43 UTC, david-allison-1 commented
@SujyotRaut I've had a request from someone else to work on this. Are you still working on the review comments

2021-04-03 08:56 UTC, SujyotRaut commented
Currently i am not working on it, i am not getting time work on it due to online classes you can give it him

2021-06-02 10:06 UTC, closed without merging