Notification can now take to reviewer Activity if review was in progress before.
ankidroid/Anki-Android pull request #8238
Opened 2021-03-16 04:08 UTC by IAmJaishree

## Pull Request template 

## Purpose / Description 
Currently, tapping the notification opens Deck List instead of Review page when pending reviews are present. 
This PR contains the code which will allow user to go to Review page instead of deck list page by tapping the notification when a review is already in progress. 
If no review is in progress the deck list page will open. 

## Fixes Fixes #3593 

## Approach 

1. Added a check in NotificationService.java => onReceive function which checks if there are pending card to review and decides the intent of Notification click based on this. 

2. Step 1 happens while the Notification onReceive method gets triggered and this can contain the lagging data as well. 

For example when this onReceive is triggered there may be pending cards to review and based on the logic it decides to open Review page on tapping the notification but there are cases where the user taps the notification after completing the deck also in this case the Review page will open and there will be no card to review. 

For this case added a check in Review activity where it checks if the Review Activity is open through Notification and verifies if there are pending cards or not, if there are no pending cards then it opens Deck List page instead. 

## How Has This Been Tested? 
This has been tested by me manually going through each of the following scenario: 

1. When user is reviewing a deck => Goes out of the app and there are pending cards to review. Notification appears and on tapping the notification the user is resumed to the Review page to continue the review process. 

2. When user is reviewing a deck => Completes the Deck Review => app closes automatically as the review is complete. Notification appears and on tapping the notification the deck list is opened. 

3. There are no review in progress but there are decks to review. Notification appears and on tapping the notification the deck list is opened. 

## Checklist _Please, go through these checks before submitting the PR._ 
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read) 
- [x] You have a descriptive commit message with a short title (first line, max 50 chars). - 
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) - 
- [x] You have commented your code, particularly in hard-to-understand areas 
- [x] You have performed a self-review of your own code 
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings) 
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner] (https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-16 05:40 UTC, haran2248 commented
@IAmJaishree Can you please a screenshot/video of the change if possible?

2021-03-16 06:49 UTC, IAmJaishree commented
@haran2248 initially I thought there is no UI change so it doesn't require screenshots, but yes as there is a change in behavior I'll add a video in a while. thanks for the suggestion :)

2021-03-16 07:02 UTC, IAmJaishree commented
When the user has an in progress review the notification tap takes to that deck instead of deck list page.

https://user-images.githubusercontent.com/58835654/111268587-78addd80-8653-11eb-8854-883994fd605c.mp4

2021-03-16 07:15 UTC, IAmJaishree commented
When user has completed the Review of a deck but still there are pending cards to review from other decks, the user will be notified by the notification and on tapping the notification the Deck List Page will open.

https://user-images.githubusercontent.com/58835654/111269905-31c0e780-8655-11eb-8bf0-49160a15834c.mp4

2021-03-16 07:29 UTC, haran2248 approved these changes

2021-03-16 07:39 UTC, mrudultora requested changes
Some small changes. You can format your code using `ctrl+alt+L`.

2021-03-16 07:39 UTC, mrudultora commented on AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java
> +            }else{
```suggestion
            } else {
```

2021-03-16 07:42 UTC, mrudultora requested changes

2021-03-16 07:42 UTC, mrudultora commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +        if(getIntent().getExtras()!=null){
```suggestion
        if (getIntent().getExtras() != null) {
```

2021-03-16 08:09 UTC, IAmJaishree commented
@mrudultora the thing is doing ctrl + alt + l in Reviewer.java added many extra lines as un necessary white spaces, so I didn't do it.
manually I can make these changes in that file. let's have some more reviews and then I'll make all these changes in one go. Thanks for the review :).

2021-03-16 08:11 UTC, mrudultora commented
> @mrudultora the thing is doing ctrl + alt + l in Reviewer.java added many extra lines as un necessary white spaces, so I didn't do it.
> manually I can make these changes in that file. let's have some more reviews and then I'll make all these changes in one go. Thanks for the review :).

No, don't select the whole file. Assume, you added 5 lines of code. So, select those 5 lines only and then do ctrl+alt+L. I hope the point in clear now?

2021-03-17 03:47 UTC, Arthur-Milchior reviewed
Hi,

Thanks a lot for your first PR.
I have never heard about this bug, as I personally don't use notification. It's really nice to see it solved, seems that'll indeed help quite some people.

A few remarks you can see in code comment.

I would like, if possible, that you edit your PR description in order to give a high level explanation of what you are doing. I have used notification in the past and improved them a little bit, but I don't remember exactly what Notificationservice, OnReceive and Notification are.

It would help me, I think, to simply read, for example:
> If the notification is triggered during a review, clicking on the notification let the user in the reviewer, unless there is no card to see in which case it goes back to deck picker

and also, for example:
> This is done as follow:
> * If the notification is triggered during review, then the intent will contains the field "throughNotification" to indicate that the notification was sent through review
> * If the activity is opened and the reviewer has no card, then we go to the deck picker

Currently, I am not sure what you are trying to do exactly, so it's hard to review and ensure that's correctly what you wanted to do.

In particular, I've got a question. What occurs if the user click on the notification later. For example later in the day, when some cards that were hard are due to review a second time. Or a day later, when cards are back in the deck to be reviewed. It is not clear to 


@mrudultora and @haran2248 Thank you a lot for your help reviewing. Given the increase in amount of time AnkiDroid suddenly require, this is very welcome. However, I'd like to ask for a change. As a general rule, I'd really appreciate if you can start by a positive message before starting with remarks of problem. Of course, the politeness rules depends of plenty of things, and that may not be needed for everybody, but that's still something that would ensure that even people with doubt will know that there were no mistake, that the whole process is good even if there are details to change. I believe that this help being a welcoming community to every people who wants to contribute. It also ensures simply that it is worth working on the PR; because after all, there is nothing that confirmed that it is a good approach globally.
To be clear, this is a general rule, for all PR, and not about this one in particular.

2021-03-17 03:47 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            Boolean throughNotification = (Boolean) getIntent().getExtras().get("throughNotification");
I'd replace `Boolean` with `boolean`. Otherwise, I'd think that the value can be null when reading the variable type

2021-03-17 03:47 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +                Card card = getCol().getSched().getCard();
Please use `count()` instead of `getCard()`. `getCard` has side effect, it removes a card from the queue, which change the order in which cards are reviewed. `count` will just let you know whether there is a card to review or not

2021-03-17 03:47 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java
> +            Card card = CollectionHelper.getInstance().getCol(context).getSched().getCard();
same remark about "count"

2021-03-17 03:47 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java
> +                resultIntent.putExtra("throughNotification", true);
Can you please put ti in `public static String", so that it is 100% sure that the very same string is used everywhere, even if we decide to use it later

2021-03-17 03:47 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            Boolean throughNotification = (Boolean) getIntent().getExtras().get("throughNotification");
Instead of get, you could use `containsKey`. Since the value is always true if it is set, testing the value is useless here.

2021-03-17 03:50 UTC, IAmJaishree commented on AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java
> +                resultIntent.putExtra("throughNotification", true);
Is there a class in the code to hold these constants string values? if yes I can store this string there itself, if not can I create another class to store constant values.

2021-03-17 03:51 UTC, IAmJaishree commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            Boolean throughNotification = (Boolean) getIntent().getExtras().get("throughNotification");
yes, that does make a lot of sense. thanks I will make this change

2021-03-17 03:52 UTC, IAmJaishree commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +                Card card = getCol().getSched().getCard();
thanks didn't know about this before that it will remove a card from the queue, will make this change.

2021-03-17 03:52 UTC, IAmJaishree commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            Boolean throughNotification = (Boolean) getIntent().getExtras().get("throughNotification");
sure

2021-03-17 04:04 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java
> +                resultIntent.putExtra("throughNotification", true);
There is no such class and I don't believe that creating such a class is a good idea. Usually, we put the constants where it make sens.
I believe that NotificationService is a good place. Indeed, we may want to use it in other activity one day, maybe, however we certainly want to emit the notification from this class

2021-03-17 04:51 UTC, IAmJaishree commented on AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java
> +                resultIntent.putExtra("throughNotification", true);
sure

2021-03-17 05:37 UTC, IAmJaishree commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            Boolean throughNotification = (Boolean) getIntent().getExtras().get("throughNotification");
I have made the changes, thanks

2021-03-17 05:37 UTC, IAmJaishree commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +                Card card = getCol().getSched().getCard();
I have made the changes, thanks

2021-03-17 05:37 UTC, IAmJaishree commented on AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java
> +                resultIntent.putExtra("throughNotification", true);
I have made the changes, thanks

2021-03-17 05:37 UTC, IAmJaishree commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            Boolean throughNotification = (Boolean) getIntent().getExtras().get("throughNotification");
I have made the changes, thanks

2021-03-17 21:15 UTC, lily1604 commented
@IAmJaishree  I am assigned for issue in this repository . But I am stuck ,would you like to work with me on that issue

2021-03-18 02:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java
> +     * This constant is used by Activities to check if the control came from Notification tap.
```suggestion
     * Used by Activities to check if the control came from Notification tap.
```

2021-03-18 02:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            if (getCol().getSched().count() == 0) {
I expect that this will fail if the collection is not loaded before `onCreate` is called. We're accessing the collection before `startLoadingCollection();`

2021-03-18 02:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java
> +            if (CollectionHelper.getInstance().getCol(context).getSched().count() > 0) {
`CollectionHelper.getInstance().getCol(context)` can crash if the database is broken - this may hard crash the app on startup

2021-03-18 02:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java
> +            if (CollectionHelper.getInstance().getCol(context).getSched().count() > 0) {
Could you extract this to `currentlySelectedDeckHasDueCards()` - the implication to a newbie in the code would be that there are no scheduled cards, whereas this only checks the selected deck.

2021-03-18 02:18 UTC, david-allison-1 reviewed
Code's really clean, thanks :)

2021-03-18 05:25 UTC, IAmJaishree commented
> @IAmJaishree I am assigned for issue in this repository . But I am stuck ,would you like to work with me on that issue

sure :)

2021-03-18 05:25 UTC, IAmJaishree commented on AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java
> +            if (CollectionHelper.getInstance().getCol(context).getSched().count() > 0) {
sure :)

2021-03-18 05:26 UTC, IAmJaishree commented on AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java
> +            if (CollectionHelper.getInstance().getCol(context).getSched().count() > 0) {
@david-allison-1  So should I add a try catch in it and not send the notification when the exception occurs?

2021-03-18 05:29 UTC, IAmJaishree commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            if (getCol().getSched().count() == 0) {
@david-allison-1 I was thinking that it must be loaded, because we are coming here from notification tap, so it must have been loaded earlier but not exactly sure and will have to find a way to create such scenario.

2021-03-18 05:29 UTC, IAmJaishree commented on AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java
> +     * This constant is used by Activities to check if the control came from Notification tap.
thanks, will make this change

2021-03-18 16:40 UTC, mikehardy commented
What's the status on this one? I don't see any status labels or clear approvals / request changes on review status from maintainers, though there is lots of interaction ?

2021-03-20 07:00 UTC, IAmJaishree commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            if (getCol().getSched().count() == 0) {
@david-allison-1 need your review on this one :).

2021-03-20 07:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            if (getCol().getSched().count() == 0) {
Assume that the collection load can fail, for example syncing currently locks the database

2021-03-20 07:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java
> +            if (CollectionHelper.getInstance().getCol(context).getSched().count() > 0) {
That makes sense, yeah

2021-03-20 08:20 UTC, IAmJaishree commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            if (getCol().getSched().count() == 0) {
@david-allison-1 then I can think of two ways.
1. Add a try catch in this code.
2. If there is any way(using preference or collection properties) to check if the collection is already loaded or not then add a check for that before executing this code.

2021-03-20 09:38 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            if (getCol().getSched().count() == 0) {
The problem is that the collection could be openable at this point (and not yet initialised). 

I feel we should move this check into `Reviewer.onCollectionLoaded` (and return early from that method)

To answer your question: `CollectionHelper.colIsOpen`

2021-03-22 09:26 UTC, IAmJaishree commented on AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java
> +            if (CollectionHelper.getInstance().getCol(context).getSched().count() > 0) {
Made the changes, thanks

2021-03-22 09:26 UTC, IAmJaishree commented on AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java
> +            if (CollectionHelper.getInstance().getCol(context).getSched().count() > 0) {
Made the changes, thanks

2021-03-22 09:26 UTC, IAmJaishree commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            if (getCol().getSched().count() == 0) {
Made the changes, thanks

2021-03-22 09:27 UTC, IAmJaishree commented on AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java
> +     * This constant is used by Activities to check if the control came from Notification tap.
Made the changes, thanks

2021-03-24 13:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +                    finishWithoutAnimation();
Might as well return early here as well

2021-03-24 13:20 UTC, david-allison-1 reviewed
Tiny change then good to go, thanks!!

2021-03-27 16:46 UTC, Arthur-Milchior commented
@IAmJaishree Do you still intend to work on it? Normally, it's almost done

2021-03-30 05:59 UTC, IAmJaishree commented
@Arthur-Milchior sorry for the delay I was involved in my college exams, will complete this in a while

2021-03-30 18:04 UTC, Arthur-Milchior commented
No emergency,  we are all volunteers.  We wondered whether we drove a contributor away somehow, and whether we should reassign this task

2021-04-03 16:08 UTC, IAmJaishree commented
@david-allison-1 @Arthur-Milchior could you please review this PR :)

2021-04-03 16:13 UTC, david-allison-1 approved these changes
Thanks! Looks good to me

2021-04-03 16:13 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +
nit: remove spacing here

2021-04-09 16:13 UTC, mikehardy requested changes
This looks good in general, but I left a comment about Intent handling - could you check it @IAmJaishree ?

Thanks for your patience on the review I did not see this until just now!

2021-04-09 16:13 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +                    startActivityWithoutAnimation(new Intent(this, DeckPicker.class));
This is something really subtle, but I have experienced bugs before where Intents were passed around, and the extras were erased https://github.com/crazycodeboy/react-native-splash-screen/issues/289#issuecomment-502406454

Philosophically, if we cannot handle an Intent, we should do our best to pass the original Intent to some Activity that can handle it, in the same way that if you cannot handle an Exception it is best to log something about why but then re-throw the original exception. Wrapping the exception or throwing a new one actually destroys information (the stack trace), and in the same way, making a new Intent here destroys information (any other possible Extras on the Intent)

I don't believe we can just re-launch the Intent, but we can at least make sure we pass everything possible, which is the Extras Bundle (if it exists) and any flags (if they exist?)

I think the correct way to do that is either:

1- call setComponent (or maybe setClassName?) https://developer.android.com/reference/android/content/Intent#setComponent(android.content.ComponentName) to simply take this intent but re-direct it to DeckPicker.class or

2- call fillIn on the new Intent (directed at DeckPicker) but with the contents of the one we could not handle here in Reviewer https://developer.android.com/reference/android/content/Intent#fillIn(android.content.Intent,%20int)


I strongly prefer solution 1 because we know we are passing everything without having to think more, but if it does not work then solution 2 could work, as long as extras were manually copied as well

2021-06-20 19:37 UTC, closed without merging