Fixes #8234 Additional debug info added
ankidroid/Anki-Android pull request #8250
Opened 2021-03-16 22:05 UTC by 2tanayk

## Pull Request template

## Purpose / Description
Added additional and useful debug info -device manufacturer, model, hardware and webview user agent.

## Fixes
#8234 

## Approach
Used the android os class `Build.` to extract manufacturer, model and hardware information
Used an anonymous instance of the `Webview` class which is `new WebView(this).getSettings().getUserAgentString()` to extract the webview user agent

## How Has This Been Tested?
Tested on an actual android device which runs on Android 10(API 29)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-16 22:25 UTC, david-allison-1 requested changes
Thanks! 2 minor changes, then good to go

2021-03-16 22:25 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.java
> +                "Webview User Agent = "+new WebView(this).getSettings().getUserAgentString()+ "\n\n"+
```suggestion
                "WebView User Agent = "+ new WebView(this).getSettings().getUserAgentString()+ "\n\n"+
```

2021-03-16 22:25 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.java
> +                "Webview User Agent = "+new WebView(this).getSettings().getUserAgentString()+ "\n\n"+
Could you extract this to a method, and surround it with a `try... catch(Throwable) { AnkiDroidApp.sendExceptionReport()... return null}`. This is somewhere that we don't want a crash for any purpose

2021-03-16 22:42 UTC, 2tanayk commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.java
> +                "Webview User Agent = "+new WebView(this).getSettings().getUserAgentString()+ "\n\n"+
sure

2021-03-16 22:44 UTC, 2tanayk commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.java
> +                "Webview User Agent = "+new WebView(this).getSettings().getUserAgentString()+ "\n\n"+
The whole debug info string right??

2021-03-16 22:47 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.java
> +                "Webview User Agent = "+new WebView(this).getSettings().getUserAgentString()+ "\n\n"+
Just `new WebView(this).getSettings().getUserAgentString()`, the others can't fail

2021-03-16 22:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.java
> +                "Hardware = " + Build.HARDWARE+"\n\n"+
```suggestion
                "Hardware = " + Build.HARDWARE + "\n\n"+
```

2021-03-16 22:50 UTC, 2tanayk commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.java
> +                "Webview User Agent = "+new WebView(this).getSettings().getUserAgentString()+ "\n\n"+
ok got it!

2021-03-16 23:11 UTC, david-allison-1 approved these changes
Looks good to me, thanks!

2021-03-17 06:47 UTC, 2tanayk commented
> Looks good to me, thanks!

some JUnit test is failing,why is that?

2021-03-17 08:32 UTC, david-allison-1 commented
Likely flakiness/nondeterminism in our unit tests - I haven't been through to fix them, and I think the migration from TravisCI to GitHub actions brought out a few issues

Arthur has a PR waiting which should fix the issue once and for all, and I haven't had the time to truly think through the design

2021-03-18 14:49 UTC, 2tanayk commented
Any updates regarding this ?Is everything fine?

2021-03-18 15:47 UTC, mikehardy commented
I have updated the PR description to include `Fixes #issuenumber` vs just `#issuenumber`, adding the `Fixes` as we request in the PR template is important because that is how GitHub knows to related the PR and issue in a way that closes the issue and cross-links them more strongly.

2021-03-18 15:52 UTC, mikehardy requested changes
one control flow issue, two spacing nits, excited to get this expanded info from users though!

2021-03-18 15:52 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.java
> +            return null;
why would we return in this case, without returning the rest of the information ?
None of the other try/catch blocks return and so in no other case will this method return null, meaning that now consumers have to null check it whereas before it was safe.

This catch block should not return, and definitely should not return null

2021-03-18 15:52 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.java
> +                "Webview User Agent = "+ webviewUserAgent +
```suggestion
                "Webview User Agent = " + webviewUserAgent +
```

spacing nit: https://github.com/ankidroid/Anki-Android/wiki/Code-style#white-space-should-be-used-in-the-following-cases -> "after and before operators"

2021-03-18 15:52 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.java
> +        return new WebView(this).getSettings().getUserAgentString()+ "\n\n";
```suggestion
        return new WebView(this).getSettings().getUserAgentString() + "\n\n";
```
https://github.com/ankidroid/Anki-Android/wiki/Code-style#white-space-should-be-used-in-the-following-cases

2021-03-18 21:28 UTC, 2tanayk commented
Will get it done as soon as possible sir✌️

2021-03-19 08:41 UTC, 2tanayk commented
done @mikehardy sir!

2021-03-19 08:58 UTC, david-allison-1 reviewed
As discussed on Discord - needs rebasing onto master and removing the merge commit

2021-03-19 16:47 UTC, mikehardy commented
Yeah, sorry - the commit history is non-reviewable at the moment. Once cleaned up I can re-check

2021-03-19 18:43 UTC, 2tanayk commented
> Yeah, sorry - the commit history is non-reviewable at the moment. Once cleaned up I can re-check

you mean I need to squash all the commits into one ?

2021-03-20 13:54 UTC, mikehardy commented
When I open the "Commits" tab on the PR I should see nothing but clean commits that implement your changes only, no unrelated commits

When I open the "Files Changed" tab on the PR I should see nothing but an easily readable diff containing nothing but the actual changes you needed to make to implement the improvement

There are many ways to do this with git, I don't have the time to lead you through them, but choose one that meets my expectations of a clean diff as described here, and I can review it

2021-03-20 16:22 UTC, 2tanayk commented
@mikehardy  sir how about a fresh/new PR?

2021-03-20 16:28 UTC, mikehardy commented
That is sometimes the best option, although I think there is value for you - as a person learning git - in figuring out how to actually fix this using `git rebase`. It won't be ...fun, but you will have much stronger control over git afterwards. Your choice

2021-03-20 19:12 UTC, 2tanayk commented
> That is sometimes the best option, although I think there is value for you - as a person learning git - in figuring out how to actually fix this using `git rebase`. It won't be ...fun, but you will have much stronger control over git afterwards. Your choice

Yes I get that!

2021-03-22 06:35 UTC, 2tanayk commented
> Yeah, sorry - the commit history is non-reviewable at the moment. Once cleaned up I can re-check

> When I open the "Commits" tab on the PR I should see nothing but clean commits that implement your changes only, no unrelated commits
> 
> When I open the "Files Changed" tab on the PR I should see nothing but an easily readable diff containing nothing but the actual changes you needed to make to implement the improvement
> 
> There are many ways to do this with git, I don't have the time to lead you through them, but choose one that meets my expectations of a clean diff as described here, and I can review it

sir if you want the file changed/diff then you can view it on github using a two-dot diff comparison like this:

https://github.com/2tanayk/Anki-Android/compare/e8141a2..38d670a

2021-03-22 08:32 UTC, 2tanayk commented
Now let me know if I've got it right this time :)

2021-03-22 08:35 UTC, david-allison-1 requested changes
Thanks! Tiny nitpick.

Almost there.

* Could you squash the 3 commits into one

I feel the commit message would be better as:

```
Added additional debug info (WebView/Hardware)

Fixes #8234
```

This provides more context for the commit, the issue number isn't too relevant when looking for context in a long list of issues.

2021-03-22 08:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.java
> +                "Hardware = " + Build.HARDWARE+"\n\n" +
```suggestion
                "Hardware = " + Build.HARDWARE+ "\n\n" +
```

2021-03-22 08:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.java
> +        return new WebView(this).getSettings().getUserAgentString() + "\n\n";
Nitpick/Implementer's choice: code style

I feel that the try/catch would be better inside this method, this allows us to reduce code in the `copyDebugInfo` method, and move the method call inline to where it's used

2021-03-22 09:03 UTC, 2tanayk commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.java
> +        return new WebView(this).getSettings().getUserAgentString() + "\n\n";
Yeah thats what I really wanted to do but it gives a compile time error (Java doesn't risk return in non-void functions) and hence I will have to return something else if the try block throws an exception(probably null) which makes the code unsafe again.

2021-03-22 09:06 UTC, 2tanayk commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.java
> +        return new WebView(this).getSettings().getUserAgentString() + "\n\n";
I will squash the commits for now

2021-03-22 09:12 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.java
> +        return new WebView(this).getSettings().getUserAgentString() + "\n\n";
You can return null, that's what we're doing implicitly here anyway

2021-03-22 09:33 UTC, 2tanayk commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.java
> +        return new WebView(this).getSettings().getUserAgentString() + "\n\n";
ok did that

2021-03-22 09:40 UTC, david-allison-1 reviewed
Last one!

One last thing!

Note that the PR title isn't the commit message title

You can change the commit message title via a `reword` operation in a rebase.

Alternately, Android Studio lets you do this with a UI:

![image](https://user-images.githubusercontent.com/62114487/111969869-974c2280-8af2-11eb-9638-bf244a3113a5.png)

2021-03-22 09:40 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.java
> +            return new WebView(this).getSettings().getUserAgentString() + "\n\n";
Move the `+ "\n\n";` to the `"Webview User Agent =` line, so it's applied to both null and the valid value

2021-03-22 09:40 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Info.java
> +                "Hardware = " + Build.HARDWARE+ "\n\n" +
And we're done after this, thanks for the patience

```suggestion
                "Hardware = " + Build.HARDWARE + "\n\n" +
```

2021-03-22 10:01 UTC, 2tanayk commented
I think all is taken care of ,check

2021-03-24 13:12 UTC, david-allison-1 approved these changes
Looks good to me, thanks!

2021-03-24 17:23 UTC, mikehardy approved these changes
good to go! Thanks

2021-03-24 17:24 UTC, merged

2021-04-05 18:33 UTC, mikehardy commented
Hi there!

Just a friendly notice (one per person for PRs merged in March, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for March 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

Thanks!

2021-06-04 21:35 UTC, mikehardy commented
@2tanayk I was able to just immediately diagnose a user problem as an out-of-date webview based on this extra debugging information, and it fixed the user immediately when they updated. I love seeing things like this pay off! Thanks again

2021-06-05 14:30 UTC, 2tanayk commented
Thanks @mikehardy means a lot to me and my semester almost over,look to start contributing again!