Progress Dialog of NoteEditor Extra Space Remove
ankidroid/Anki-Android pull request #8255
Opened 2021-03-17 06:35 UTC by imaryandokania

## Pull Request template

## Purpose / Description
Solves the bug of extra space

Before:
![Screenshot_1615822428](https://user-images.githubusercontent.com/61244704/111403765-acd9da80-86f5-11eb-9baa-3b32fdb1c85b.png)

After:
![Screenshot_1615946584](https://user-images.githubusercontent.com/61244704/111403787-b6634280-86f5-11eb-8dae-994cdfe13ec8.png)

## Fixes
"" in progress dialog changed to null
fixes bug ankidroid#8252

## How Has This Been Tested?

Tested on Emulator: Pixel 3a API R

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-17 06:46 UTC, david-allison-1 requested changes
Nice rebase! PS: You shouldn't need to create a new PR, a force push will update the existing PR to the state of the code on your machine.

Could you `rebase` this again, to change the commit title & message to something that will help future developers.

You can either use `rebase - reword`, or "Edit Commit Message" in Android Studio

Something along the lines of:

```
fix[NoteEditor]: Progress Dialog - remove spacing

fixes bug #8252
```

2021-03-17 06:59 UTC, imaryandokania commented
> Nice rebase! PS: You shouldn't need to create a new PR, a force push will update the existing PR to the state of the code on your machine.
> 
> Could you `rebase` this again, to change the commit title & message to something that will help future developers.
> 
> You can either use `rebase - reword`, or "Edit Commit Message" in Android Studio
> 
> Something along the lines of:
> 
> ```
> fix[NoteEditor]: Progress Dialog - remove space
> 
> fixes bug #8252
> ```

I have edited the commit message ,Is it fine now? Or did I do a mistake

2021-03-17 07:02 UTC, david-allison-1 approved these changes
All good! 

Rebasing is hard - definitely over halfway to git pro 😁

2021-03-17 07:03 UTC, david-allison-1 commented
Oh, just to note: if you type `Fixes #8252` in the PR template, then it links the issue and the PR. When it's merged, the issue automatically gets closed

2021-03-19 04:20 UTC, merged

2021-03-20 14:31 UTC, mikehardy commented
This bug did not use the correct `Fixes #bugnumber` notation so it orphaned the corresponding issue and did not close it on PR merge. I fixed it.