Add test to ensure Utils.stripHTML behave the same as the upstream
ankidroid/Anki-Android pull request #8256
Opened 2021-03-17 10:10 UTC by TarekkMA

## Pull Request template

## Purpose / Description
While working on #8248 I found an inconsistency between the pylib code and ankilib code. When dealing with tags. Also pylib code removes comments and ankilib currently lacks this.

## Approach
I have also added a test to the pylib util code
https://github.com/TarekkMA/anki/blob/698f7745f3/pylib/tests/test_utils.py#L3-L14

## How Has This Been Tested?
Using tests :)

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-17 10:36 UTC, david-allison-1 reviewed
Thanks!!

Tests fail (as expected?)

We should avoid having a commit in the repository where tests fail (as this means `git bisect` would fail).

Could you ignore the tests, and remove the ignore annotation in the next commit

2021-03-17 10:45 UTC, TarekkMA commented
Yes it does fail, you mean add `@Ignore` to tests and when I implement the fix remove them?

2021-03-17 10:51 UTC, david-allison-1 commented
> Yes it does fail, you mean add `@Ignore` to tests and when I implement the fix remove them?

Yeah, or perform the change in one commit. 

Leaving broken commits in a PR runs the risk that someone will rebase them onto master (as CI won't pick up on them). 

Once a bad commit is in `master`, they mean that an automatic `git bisect` may fail, and a developer would have to do it manually.

2021-03-17 10:52 UTC, TarekkMA commented
Oh, didn't know that, will rebase the fix here then. 

Will fix the tag pattern and add the comment pattern to be also stripped.

2021-03-17 11:19 UTC, TarekkMA commented
Fixed and this time, the changes to ankilib is to the minimum.

2021-03-17 11:20 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
>          s = stripHTMLScriptAndStyleTags(s);
``stripHTMLScriptAndStyleTags`` Not found in pylib, but I left it here for the sake of keeping changes to the minimum

2021-03-17 13:25 UTC, david-allison-1 commented
Looks reasonable. 

Could do with a link to the relevant Anki Desktop commit that the changes were pulled from in the commit message to help with anyone looking through the history.

This one might require a little more digging to understand the impact - for example: would checksums be using this? Does that mean we may have corrupt data?

2021-03-17 13:38 UTC, dae commented
Not a huge issue, they're rebuilt by the desktop DB check, and only affect duplicate checking IIRC.

2021-03-17 16:45 UTC, amritanshu-kk approved these changes

2021-03-17 16:47 UTC, amritanshu-kk approved these changes

2021-03-19 17:09 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/libanki/UtilsTest.java
> +import org.junit.Ignore;
This appears to be unused now
```suggestion
```

2021-03-19 17:11 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/libanki/UtilsTest.java
> +import org.junit.Ignore;
to be clear, if it's two commits, the first Ignores the test and needs it, sure, but the second commit should remove the import as well

Alternatively could just squash them to one commit, either is fine by me

2021-03-19 17:12 UTC, mikehardy requested changes
This looks great - just pending a clean up of import in the final diff

2021-03-19 17:15 UTC, TarekkMA commented on AnkiDroid/src/test/java/com/ichi2/libanki/UtilsTest.java
> +import org.junit.Ignore;
Oh sorry forgot the import there 😅 
Okay no issue will squash the 2 commits, since they are related.

2021-03-19 17:21 UTC, TarekkMA commented
Okay, that's done.

2021-03-19 17:36 UTC, mikehardy approved these changes
Fantastic, as soon as CI passes I will add this.
Yes to bugfixes! Thank you
Extra yes to bugfixes that come with a test proving they work, forever! Thank you

2021-03-20 03:19 UTC, david-allison-1 approved these changes
Cheers!

2021-03-20 03:19 UTC, merged