Fixes #8210 Added analytics/metrics to help section
ankidroid/Anki-Android pull request #8257
Opened 2021-03-17 15:00 UTC by mrudultora

## Purpose / Description
This PR adds analytics in Help section (Dialog box) on clicking any item.

## Fixes
Fixes #8210 

## Approach
As I was bit confused, I followed the approach suggested by David.
https://github.com/ankidroid/Anki-Android/issues/8210#issuecomment-800594220
**Also, there are some whitespaces but they are not intentional. I have properly formatted the classes and that has caused some extra line additions.**

## How Has This Been Tested?
Tested on real device (Redmi Note 7S and API 29). Analytics are logged in logcat and thus showing it's working fine.

## Learning (optional, can help others)
This PR changes used abstraction and some more changes.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-17 15:14 UTC, david-allison-1 requested changes
```
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/RecursivePictureMenuTest.java:127: error: no suitable constructor found for LinkItem(int,int,int)
> Task :AnkiDroid:compileDebugUnitTestJavaWithJavac
        return new LinkItem(R.string.help_item_ankidroid_manual, R.drawable.ic_manual_black_24dp, linkLocation);
               ^
    constructor LinkItem.LinkItem(int,int,int,int) is not applicable
      (actual and formal argument lists differ in length)
    constructor LinkItem.LinkItem(Parcel) is not applicable
      (actual and formal argument lists differ in length)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/RecursivePictureMenuTest.java:138: error: incompatible types: Item[] cannot be converted to int
        return new ItemHeader(R.string.help_item_ankidroid_manual, R.drawable.ic_manual_black_24dp, items);
```

2021-03-17 15:48 UTC, david-allison-1 requested changes
First pass through for review comments - looks good!

2021-03-17 15:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java
> +        public static final String LINK_CLICKED = "HelpDialog";
I'll defer the review mostly to Mike, he's much more clued up on the analytics side than I am.

But we presumably want a more general `LinkClicked` category if we only have a limited number

2021-03-17 15:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +        private @StringRes
nit: try and keep the typical Java definition on on line - I think you can move`@StringRes` to the line above for a more sensible line break.

2021-03-17 15:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.java
> +        public void execute(AnkiActivity activity) {
Yo should be able to move this to the base class if it's unchanged between different classes

2021-03-17 15:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +
Could you fix the spacing changes

2021-03-17 15:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +            return context.getString(mAnalyticsRes);
You can probably pass this + variable down to the base class to save code repetition.

2021-03-17 15:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +            UsageAnalytics.sendAnalyticsEvent(UsageAnalytics.Category.LINK_CLICKED, getAnalyticsId(activity));
Optional - implementer's choice: I'd move all calls to analytics before calling `onClicked`

2021-03-17 15:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.java
> +        public abstract String getAnalyticsId(Context context);
I don't think this needs to be abstract if you're using an ID for all implementations

2021-03-17 15:48 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/constants.xml
> +    <!-- Strings used for sending analytics for HelpDialogBox -->
Make a note not to change these strings, as the comparison between versions of AnkiDroid will be useful

2021-03-17 15:48 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/constants.xml
> +    <string name="opened_using_ankidroid">Opened Using AnkiDroid</string>
@mikehardy - unsure if these should be identifiers (`HelpUsingAnkiDroid`) to reduce the likelihood of people changing the strings. What's typical convention with analytics? 

We should add this to the dev guide/code style - would be useful

2021-03-17 15:50 UTC, mrudultora commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java
> +        public static final String LINK_CLICKED = "HelpDialog";
I thought that, but was unsure that, **what should be the name?** So I used this one.

2021-03-17 15:51 UTC, mrudultora commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +        private @StringRes
Yup, sure ! That would be a nicer way..

2021-03-17 15:52 UTC, mrudultora commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +
I will manually remove them. Just don't know on what basis Android Studio formats files. I thought of that...

> Also, there are some whitespaces but they are not intentional. I have properly formatted the classes and that has caused some extra line additions.

2021-03-17 15:54 UTC, mrudultora commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.java
> +        public abstract String getAnalyticsId(Context context);
But, all child classes must have this method. So I think, we must keep it abstract.

2021-03-17 16:08 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.java
> +        public abstract String getAnalyticsId(Context context);
I don't think they do - if we pass the ID to the base class (possibly a bad design, but I don't think the class is complex enough for it to matter), then they would all be the same implementation of returning `Context.getString`?

2021-03-17 18:52 UTC, mrudultora commented
@david-allison-1 Changes done as suggested by you. Now, only thing remaining is the Category tag.

2021-03-18 00:20 UTC, david-allison-1 reviewed
The amount of red in that last diff is fantastic -  60+ lines removed. We can do a little more, but this seems much better.

2021-03-18 00:20 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/constants.xml
> +    <!-- Note: These Strings must note be changed -->
```suggestion
    <!-- Note: These Strings must not be changed as they are used for analytic comparisons between AnkiDroid versions -->
```

2021-03-18 00:20 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/constants.xml
> +    <!-- Note: These Strings must note be changed -->
If this goes in, we should add an issue to enforce this via a lint check

2021-03-18 00:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.java
> +            System.out.println("getAnalyticsId : " + context.getString(analyticsId));
* Use `Timber.d` and format strings rather than string concatenation
    * If you concatenate strings, then the code must execute before the method is called
    * If you use format strings, the method can say "Debug logging is disabled", exit early, and avoid any concatenation
* Extract `context.getString(analyticsId)` into a variable - use it twice, Android Studio has a really good refactoring shortcut for this, memorize the keybind.

2021-03-18 00:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +            UsageAnalytics.sendAnalyticsEvent(UsageAnalytics.Category.LINK_CLICKED, getAnalyticsId(activity));
I believe this method can be moved to `Item` and made `public final void` as it should be the same for all subclasses

2021-03-18 02:57 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java
> +        public static final String LINK_CLICKED = "HelpDialog";
I think literally "LinkClicked" - we're just trying to log that they clicked a link as a category, there is still the chance to put what the link was (up to a certain number of characters) so that's where the detail should go. Eventually this could also be used for outbound links on the changelog etc or anywhere we have them. It's just the idea they clicked an outbound link

2021-03-18 03:00 UTC, mikehardy commented on AnkiDroid/src/main/res/values/constants.xml
> +    <string name="opened_using_ankidroid">Opened Using AnkiDroid</string>
I think they should be constants in the code. They must be alphabetically equal every time they are sent to the analytics provider, or they won't tally up - so there can be no variance. That's the reason for defining the category as a string constant as well by the way. Once you pick one - even though what you picked is arbitrary to begin with - that's how the data starts accumulating, and if you want it to be comparable over time and add up right, you must not change the values sent

2021-03-18 06:56 UTC, mrudultora commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java
> +        public static final String LINK_CLICKED = "HelpDialog";
@david-allison-1 I can assign **"LinkClicked"** in LINK_CLICKED Category and append **HelpDialogBox** before each of these strings. Is that a good idea ? For example, _HelpDialog opened Using AnkiDroid_.

2021-03-18 11:58 UTC, mrudultora commented
@david-allison-1 Changes done ;-)

2021-03-18 13:04 UTC, david-allison-1 requested changes
One pending change I feel could be done

Other than that, pending us coming up with a way to store the new analytics constants.

2021-03-18 13:04 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/constants.xml
> +    <string name="opened_using_ankidroid">Opened Using AnkiDroid</string>
These are in `constants.xml`, so non-translatable.

But, I'm unsure here, do you have a proposal for a structure/class to store these in?

I'd be tempted to say a constants class somewhere close to `UsageAnalytics` to imply to developers that the values shouldn't change for any reason.

It'd be ideal for these to be somewhere that we can either lint or unit test in future, to ensure that nobody accidentally changes the value - don't have a concrete idea yet, but both a class or XML file would work

2021-03-18 13:21 UTC, mrudultora commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.java
> +
@david-allison-1 No, I have removed the comment from all the classes and just added that in parent class **Item**. And yes, I will remove these blank lines.

2021-03-18 14:14 UTC, mrudultora commented
@david-allison-1 On moving this constant strings to class would require changes. Because currently I am using string resources (int) and now they are strings. So, should I change the parameter in constructor to String?

2021-03-18 14:16 UTC, david-allison-1 commented
> @david-allison-1 On moving this constant strings to class would require changes. Because currently I was using string resources (int) and now they are strings. So, should I change the parameter in constructor to String?

Best to hold off on this change until we know what we're after

2021-03-18 15:44 UTC, mikehardy commented
Why is it not okay to just define the constants *in* UsageAnalytics? I would just define available categories in there and be done. They will only ever be used while calling a UsageAnalytics API, so they belong there IMHO

2021-03-19 09:29 UTC, mrudultora commented
@david-allison-1 As Mike suggested, I think we should put those strings in Category class in UsageAnalytics. Adding a small note, not to change these strings would be good. What are your views on it?

2021-03-19 11:20 UTC, david-allison-1 commented
Sure - sounds good to me

2021-03-19 15:17 UTC, mrudultora commented
@david-allison-1 I have done the changes. Following points are there :

• Moved the strings in **Category** class in UsageAnalytics and added a note there.
• Introduced string parameter rather than the int String Resource.
• Changes done accordingly in Unit Tests.
• Removed all the unnecessary whitespaces and comments (avoided repetition)

2021-03-19 16:55 UTC, mikehardy approved these changes
I gave this a read and it looks good to me *assuming* the one pending item from David is satisfied, so once David agrees, I'm +1 on it

2021-03-19 17:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java
> +        public static final String OPENED_HELPDIALOG = "Opened HelpDialogBox";
Could we consider moving these to `public static class Action {`? These aren't category labels.

@mikehardy

2021-03-20 08:11 UTC, mrudultora commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java
> +        public static final String OPENED_HELPDIALOG = "Opened HelpDialogBox";
It makes sense, but, making separate class for this ? If we are going to make separate class for **Actions** than we must remove all the hardcoded strings parameters passed as actions and put them here, and not just for help dialog.

2021-03-20 08:38 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java
> +        public static final String LINK_CLICKED = "HelpDialog";
That's a good idea, yes

2021-03-20 08:43 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/constants.xml
> +    <!-- Note: These Strings must note be changed -->
#8287

2021-03-20 08:49 UTC, david-allison-1 reviewed
We can still remove duplication of `execute` 

Implementer's choice WRT class structure of constants.

2021-03-20 08:49 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java
> +        public static final String OPENED_HELPDIALOG = "Opened HelpDialogBox";
I feel I'm bikeshedding. 

Your call: 

* Leave it as it is, as it can quickly be refactored later
* `Actions` class with a TODO/follow-up PR
* `class LinkClicked`

2021-03-20 10:22 UTC, mrudultora commented
@david-allison-1 Changes done. List of changes....

• Removed duplication of `execute`.
• Added **Actions** class in UsageAnalytics and added a note there.

2021-03-20 11:10 UTC, david-allison-1 approved these changes
Beautiful! Awaiting CI - I'll re-run the emulator tests, and will check with Mike for a quick re-review

2021-03-20 13:49 UTC, mikehardy approved these changes
This looks good to me, thanks!
As a thought: any time we add analytics because we are curious about something, we should make sure we have a real question, a real hypothesis, and we will take action on the results. Otherwise we are just collecting data for no purpose right?

So I'd like to see an issue logged for follow-up that is about like so:
- review help section analytics
- "...about 2 months after 2.15 releases to stable channel, examine help section analytics"
- "...we were curious about ..."
- "...we expect the analytics to show ... because ..."
- "...if what they show is different we will ...."

Does that make sense? I think it will be a gift to developers in the future because it will document your purpose to guard against forgetting why we did this, and it should serve as a general criteria for adding things like this in the future - if we don't have a clear reason to collect data that we can articulate like this, then we shouldn't spend any time on it IMHO

2021-03-20 13:50 UTC, merged

2021-03-20 13:52 UTC, mikehardy commented
One note is that I used squash-merge on this, A chain of 9 commits with messages like "fixed some things" are effectively worthless in a git history - they communicate nothing to future explorers of the tree. When authoring git commits consider that you are effectively writing a story that future people *will* read. Commit messages should be useful and descriptive, and small commits editing changes in response to feedback should be merged (in your local tree) into the commit they belong to if possible

2021-03-20 13:55 UTC, mrudultora commented
I will remember this. In some commits I just removed the whitespaces so I was not sure like _What to put in these commit message_ 😅.

2021-03-20 14:22 UTC, mikehardy commented
In that case I usually, mentally when I do this I am thinking "oh! that's good feedback, I'll make the change and test it then I'll edit the original commit to include the correction"

```
...make the change and test it...
git stash
git rebase -i HEAD~1  (<-- assuming the last commit is the one you are patching up, use the number of the correct commit to fix though if not the last one)
...set the commit from pick to edit for the one you want to fix in the commit selection window...
git stash pop
git add -A
git rebase --continue
...edit the commit message if needed but usually it is just a save and exit on the editor...
git push <your fork name> +<your branch name>
```