Issue #6829 resolved
ankidroid/Anki-Android pull request #8258
Opened 2021-03-17 16:07 UTC by pree-T

## The manual and help instructions can now be loaded offline 
Issue #6829 resolved
The support and manual webpages have been added in the offline mode

## Fixes
#6829 

_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-17 16:13 UTC, infinyte7 commented
Change this more descriptive text, so it will help in searching later.
>Issue #6829 resolved

2021-03-17 16:24 UTC, david-allison-1 requested changes
Thanks!

My understanding is that this change will contain a change to `release.sh` to include the current version of the Support/Manual into the app: https://github.com/ankidroid/Anki-Android/issues/6829#issuecomment-669992883

I don't see this happening, so I think there's still requirements to be met

2021-03-17 16:24 UTC, david-allison-1 commented on AnkiDroid/build.gradle
> +
Could you revert this change - no need to bump the file

2021-03-17 16:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +
Could you revert changes to this file - unnecessary

2021-03-17 16:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +        view.loadUrl("file:///assets/AnkiDroidSupport.html");
These don't seem to have been added to the project

2021-03-17 16:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +        view.loadUrl("file:///assets/AnkiDroidSupport.html");
This seems to be loading a URL, then loading it again later on, could you explain the rationale?

2021-03-17 16:24 UTC, david-allison-1 commented on tools/chromeos/release.sh
> +# shellcheck disable=SC2164
Could you explain this?

2021-03-20 05:43 UTC, pree-T commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +        view.loadUrl("file:///assets/AnkiDroidSupport.html");
Yes actually here the webpage is stored in the locally in the app,so that even if the app is offline that page will be loaded

2021-03-20 05:47 UTC, pree-T commented on AnkiDroid/build.gradle
> +
These changes were automatically generated as a result of storing the webpage locally

2021-03-20 15:50 UTC, mikehardy commented on AnkiDroid/build.gradle
> +
@pree-T your statement is not relevant to the request from David. Your change does not require any change to the build.gradle yet you have included a change in your proposed diff. Nothing in programming is truly automatic, you are in control of all of it.

You must not make unrelated changes in pull requests, and this specific one was noted and David requested removal.

Remove this change

2021-03-20 15:51 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +
@pree-T Do not change any spacing unrelated to your changes - there are several lines like this, none of them are related to your actual proposed enhancement

2021-03-20 15:52 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +        view.loadUrl("file:///assets/AnkiDroidSupport.html");
The web page is *not* stored locally in the app until you make the necessary + related changes to release.sh to render them via asciidoctor from a parallel `ankidroiddocs` directory, similar to the changelog.asc render

2021-03-20 15:55 UTC, mikehardy requested changes
- release.sh needs to render the new files
- webview should load the file, no other loading should be necessary
- unrelated spacing must be removed
- no shellcheck disables should be included without explanation

2021-03-20 15:55 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +            InputStream stream = assetManager.open("AnkiDroidSupport.html");
As David said, this makes no sense - you have already asked the WebView to load the file. What are lines 64 through 78 in your diff doing, if not just duplicating the load you have already done in line 62?

2021-03-20 15:56 UTC, mikehardy commented
I have edited the PR title so it is meaningful for future notifications

2021-03-20 15:57 UTC, mikehardy commented
One final note - the help dialog just had an analytics feature added, causing a conflict in this work while it is/was in process - you will need to rebase (not merge!) from current master branch and fix up your use of the HelpDialog APIs to match #8257

2021-05-31 23:34 UTC, david-allison-1 commented
@pree-T This is still waiting for feedback. Are you likely to have time to address the review comments?

2021-08-07 00:51 UTC, closed without merging