Add supportsRtl to AndroidManifest.xml
ankidroid/Anki-Android pull request #8261
Opened 2021-03-17 20:13 UTC by TarekkMA

## Pull Request template

## Purpose / Description
This line of code was causing a lot of visual issues for RTL users. As the direction of the layout was still LTR

## Fixes
#8259

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-17 20:22 UTC, TarekkMA commented
The UI is now respecting the direction of the locale set.
<img src="https://user-images.githubusercontent.com/6633545/111532344-37f6b700-876e-11eb-987f-5f123b4cf672.png" width="35%">

But as you can see the arrow in the top is not pointing in the right direction. 


Here you can see the toolbar is correctly laid. 
<img src="https://user-images.githubusercontent.com/6633545/111532559-742a1780-876e-11eb-8d23-b5f8239fb960.png" width="35%"> <img src="https://user-images.githubusercontent.com/6633545/111532698-9f146b80-876e-11eb-8986-311118314416.png" width="35%">

But the 3 numbers and padding is not behaving correctly, in the case of the 3 numbers the use of relative layout and `layout_alignParentRight` instead of `layout_alignParentEnd` will not respect the layout direction of the locale.


I would need to go through all the XML files and fix all the hard coded directions, we can add to the development guide to never use start, end in XML, and android studio by default shows warning when using them.

If it's okay to start going through the XML let me know.

2021-03-17 20:39 UTC, TarekkMA commented
BTW this change will flip everything around, I think it's for the best. The old way was unusable and not comfortable for me as an Arabic speaker.

If the user use the app in RTL language most properly his whole device language. So him seeing LTR layout with RTL text is very bizarre

2021-03-17 21:29 UTC, eginhard commented
Thanks, that looks great! Can you confirm (and @irshadmd if you can) that nothing in the UI is completely broken/unusable after this?

2021-03-17 21:38 UTC, TarekkMA commented
I push a fix for the issue in the home screen which will make it more usable.

![Screen Shot 2021-03-17 at 11 31 34 PM](https://user-images.githubusercontent.com/6633545/111541835-a2f9bb00-8779-11eb-91ea-50d616be61f1.png)

2021-03-17 21:39 UTC, TarekkMA commented
Oh didn't notice the FAB.

2021-03-17 21:56 UTC, TarekkMA commented
@irshadmd Can you take a look at the changed I made, and run this PR and see if you spot any issues that make the application unusable?

2021-03-17 22:53 UTC, irshadmd commented
![Screenshot_20210318-041409](https://user-images.githubusercontent.com/32608381/111548583-f2071680-87a0-11eb-8812-3308fe686e0e.png)

@TarekkMA  I have run your PR in my system and find out that some options are not translating.

2021-03-17 23:26 UTC, david-allison-1 commented
> @TarekkMA I have run your PR in my system and find out that some options are not translating.
> 
> ![Screenshot_20210318-041409](https://user-images.githubusercontent.com/32608381/111548583-f2071680-87a0-11eb-8812-3308fe686e0e.png)

This is likely because your language hasn't been translated by our translators: https://crowdin.com/project/ankidroid

Could you please check the app for any layout problems?

2021-03-18 05:37 UTC, TarekkMA commented
I have succeeded in figuring out how to make the navigation icon RTL compliant. I will go through the app screen again and search for any apparent inconsistencies. 

<img src="https://user-images.githubusercontent.com/6633545/111578233-67341500-87bc-11eb-971c-e5783a517793.png" width="35%">

@irshadmd, make sure if you find more layout issues to post it here

2021-03-18 06:09 UTC, TarekkMA commented
Found another one with `RecursivePictureMenu` navigation icon.

## Old Layout
<img src="https://user-images.githubusercontent.com/6633545/111580895-022eee00-87c1-11eb-8e9e-07db3efb3e25.png" width="35%">

## New Layout

<img src="https://user-images.githubusercontent.com/6633545/111580973-2094e980-87c1-11eb-823b-8ec8928b3907.png" width="35%">

2021-03-18 06:11 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.java
> +            Drawable iconValue = AppCompatResources.getDrawable(getContext(), R.drawable.ic_menu_back_black_24dp);
autoMirror don't work with `VectorDrawableCompat`, so I used `AppCompatResources` which should do the exact same thing as `VectorDrawableCompat` as it's supposed to handle all types of drawables.

It's working on API 21

2021-03-18 12:20 UTC, irshadmd commented
@TarekkMA  yes layout look's fine 🚀

2021-03-18 12:51 UTC, david-allison-1 requested changes
```
git fetch upstream pull/8261/head:8261
git checkout 8261
git rev-parse HEAD
>> f971531801cfffde0bb3ad30a5bd3399b829dc74
```

* Answer buttons have changed positions - do we match Anki Desktop with this?
* Deck Picker - Arrow is pointing in the wrong direction
* Card Browser - fields are left aligned
* Note editor - fields are left aligned (see original issue - another linked ticket is on this and it may be complex - Anki Desktop has a concept of RTL fields)
* Add Tag -  the text hint seems to be LTR
   * Create Filtered Deck as well: https://github.com/ankidroid/Anki-Android/blob/1476aa95bd5e5b69a9b8329747b999b200b815b4/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L818
* Help Menu - Text is left aligned
* Graphs are still left to right (do we do anything here?)
* Manage Note Type - Edit Field -  Field list is LTR
* Changelog is LTR

2021-03-18 13:57 UTC, TarekkMA commented
Thank you. 

* Anki Desktop do flip the buttons on RTL layouts
<img src="https://user-images.githubusercontent.com/6633545/111633188-e7c73580-87fd-11eb-84f5-b5ec3838ccf8.png" width="50%">

* Yes the deck picker expand arrow is flipped, will push a fix here
* Card Browser - fields follow the direction of text written in them (specifically the first character)
   * **Should we force it to be the direction of the layout?** 
<img src="https://user-images.githubusercontent.com/6633545/111633785-8b184a80-87fe-11eb-9d7b-05ec4f26ed3b.png" width="35%">

* !!!!!!! Note editor - fields are left aligned (see original issue - another linked ticket is on this and it may be complex - Anki Desktop has a concept of RTL fields)
    * Will check the issue and reply to you. But I suspect we would need to have it in another PR

* Add Tag - I will fix it
<img src="https://user-images.githubusercontent.com/6633545/111634577-548eff80-87ff-11eb-8c9c-93e74963e647.png" width="35%">

* Create Filtered Deck as well (**Can you attach an image to point out the issue?**)

* Help Menu - Text is left aligned, do you mean this? if so I will push a fix for it here
<img src="https://user-images.githubusercontent.com/6633545/111634286-0974ec80-87ff-11eb-8b31-fa606b577e94.png" width="35%">

* Graphs are still left to right (do we do anything here?)
     * **They are acting the same in LTR and in RTL, so maybe we can do it in another PR. Since nothing is changed in graphs**

* Manage Note Type - Edit Field - Field list is LTR (I suspect it's acting the same way, inheriting the direction of the text)
    * **This screen is having some strange bug, Arabic text is not showing at all. This behavior was there before this PR on the stable google play version*
    
<img src="https://user-images.githubusercontent.com/6633545/111636631-5659c280-8801-11eb-8067-43811ab78507.png" width="35%">

* Change log is LTR
    * I suspect this also to be inherited from the text, as English text should still be laid from LTR

Also found that Card info is having issues
<img src="https://user-images.githubusercontent.com/6633545/111635328-0f1f0200-8800-11eb-814f-21d1df4c76a9.png" width="35%">

2021-03-18 14:01 UTC, david-allison-1 commented
I'll get around to replies later on today - Card Info is due to be replaced in AnkiDroid 2.16, so I wouldn't spend any effort on it.

Stats: We're going to add a new stats page in 2.16, so treat it as low priority, personally would let this through with stats not being fixed

2021-03-18 19:26 UTC, TarekkMA commented
Finally, found the issue with the Manage Note Type - Edit Field - Field list.
The TextView was set to a fixed size, I don't know what is that.

![Screen Shot 2021-03-18 at 9 23 47 PM](https://user-images.githubusercontent.com/6633545/111685370-810f3f80-8830-11eb-9ca5-508047aeecd7.png)

2021-03-20 07:33 UTC, Arthur-Milchior reviewed
I'm not going to review the UI after RTL change myself, since I never use it. If someone other than the author could confirm that they tested this version and that nothing got worse, I'll approve it.
I don't require everything to be perfect, but if you see problems that are not listed above, please mention them.

In any case, this will need to stay in alpha and beta some time, since it may be a big change. Every commit currently seems to make perfect sens and I'd approve this if I got confirmation nothing obviously broke.

2021-03-20 07:33 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/layout/model_field_editor_list_item.xml
> +        android:layout_width="match_parent"
Is this change related to RTL?

2021-03-20 07:53 UTC, TarekkMA commented on AnkiDroid/src/main/res/layout/model_field_editor_list_item.xml
> +        android:layout_width="match_parent"
Yes see the image I have attached in the previous comment. When we have RTL text it will go outside the screen. I don't know why the width is fixed.

2021-03-20 07:57 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/layout/model_field_editor_list_item.xml
> +        android:layout_width="match_parent"
It used to be "fill_parent". 
It was changed in https://github.com/ankidroid/Anki-Android/commit/304afd1a690256ea1a212a29466992093f888a48
The commit do not explain why. I don't expect that Tim would recall 6 years later why he made this choice, so no need to ping him there. 

Honestly, when I see this kind of commit, that motivate me to do atomic commit and comment. Because it will remain a mystery here...

2021-03-20 08:11 UTC, TarekkMA commented on AnkiDroid/src/main/res/layout/model_field_editor_list_item.xml
> +        android:layout_width="match_parent"
In the same commit, I found this `@dimen/match_parent_or_600dp` set to some layouts, maybe he forgot this one?

2021-03-20 09:33 UTC, david-allison-1 reviewed
> * Card Browser - fields follow the direction of text written in them (specifically the first character)
>   
>   * **Should we force it to be the direction of the layout?**

No, you're correct

> 
> * Change log is LTR
>   
>   * I suspect this also to be inherited from the text, as English text should still be laid from LTR

Fair point

----

Please let me know if I missed replying to anything, I'm so glad this seems easier than expected.

I would really like to push for a "Force Left to Right" preference- this is going to cause a lot of angry users as we're flipping the buttons

2021-03-20 09:46 UTC, TarekkMA commented
@david-allison-1 what do you mean by preference? Do you mean tge ease button in the reviewer?

And do we have an estimation on how many of the user base use the app is RTL local. So we have an Idea of the impact

2021-03-20 15:38 UTC, mikehardy commented
Here's a link to the last year's worth of user sessions language setting https://docs.google.com/spreadsheets/d/1AMLjlUEbqJlmk4Jr9Z_En1EE9hJytOHQ0v939PbYIKA/edit?usp=sharing

Here is just the copy paste of all languages with more than 10 sessions for the year

I'm not sure which language codes are RTL, sorry

```

Language | Users
-- | --
en-us | 46,529
en-gb | 4,247
pt-br | 3,356
es | 1,761
es-es | 1,017
de-de | 1,011
fr | 740
fr-fr | 587
de | 549
hu-hu | 544
es-419 | 543
sv | 542
nl | 537
tr-tr | 503
ja | 501
en | 489
pl-pl | 393
cs-cz | 363
vi-vn | 349
ko-kr | 264
nl-nl | 254
nb | 233
zh-tw | 227
da | 219
sv-se | 213
es-us | 175
pl | 160
pt-pt | 147
zh-cn | 143
cs | 130
hu | 129
ru-ru | 127
ca | 125
vi | 124
en-ca | 123
tr | 103
ko | 95
sk-sk | 88
fi | 83
it-it | 83
ar | 76
fa-ir | 74
ja-jp | 74
en-au | 67
pt | 67
en-in | 65
ru | 61
es-mx | 60
it | 58
da-dk | 35
fa | 34
fi-fi | 30
fr-ca | 28
sk | 28
el-gr | 25
nb-no | 22
lt | 21
es-ar | 20
es-co | 18
nl-be | 18
ca-es | 15
bg-bg | 14
de-at | 14
de-ch | 14
id-id | 14
lt-lt | 14
es-pe | 13
el | 12
uk-ua | 12
zh-hk | 12
ar-eg | 11
he-il | 11
```

2021-03-20 15:42 UTC, mikehardy commented
This is tough... thinking about the buttons and changing them and a force preference

May I submit that:
- our RTL user community is not very large (stats above)
- RTL users are probably very familiar with UI issues handling their languages because we non-RTL developers basically suck at it (and I'm speaking of myself here: I suck at it, I think in general we do a terrible job here)
- It follows then that if you put a BIG NOTE IN THE CHANGELOG that we spent a lot of time fixing RTL issues, they are real improvements but it means some buttons have now swapped as they are laid out RTL instead of fixed, that the RTL user community would be forgiving?
- It then follows that we can just do the change, note the change, and avoid the preference and move on

2021-03-20 16:03 UTC, TarekkMA commented
Here is a list of locals (with direction info) https://meta.wikimedia.org/wiki/Template:List_of_language_names_ordered_by_code
But I think most famous is (still small user base):
* Arabic - ar
* Persian - fa
* Hebrew - he
* Urdu - ur

I don't actually use RTL as a locale in my phone, but making the app different from the whole OS makes it strange and inaccessible, and if the user does use Anki Desktop in RTL locale the layout is flipped as expected. 

We can roll out the RTL layout change, with a new option that will appear when RTL locale is selected, that option can toggle LTR direction without affecting the language.

Then we see how many of the user base actually toggle that on. (obviously we make it off by default). I suspect that very small percentage will enable it, then we move to the last step and remove the option entirely, or leave it.

2021-03-20 16:14 UTC, mikehardy commented
No, please don't speculatively add a toggle (and associated code). If it wasn't clear in my comment, I prefer fairly strongly to not add a toggle.

I think we should make RTL work as it should, note that we have done so, and move on.

2021-03-20 16:22 UTC, TarekkMA commented
Oh, thanks for the clarification. We do it right like all other apps and move on.

2021-03-21 03:43 UTC, Arthur-Milchior commented
> Here's a link to the last year's worth of user sessions language setting https://docs.google.com/spreadsheets/d/1AMLjlUEbqJlmk4Jr9Z_En1EE9hJytOHQ0v939PbYIKA/edit?usp=sharing
> 
> Language | Users
> -- | --
> en-us | 46,529

This document is private

How do you explain such a low number. Is that a very small fraction of users accepted to share data? It seems suspicious compared to the number of user we think we have with play store data

2021-03-21 04:39 UTC, mikehardy commented
> > Here's a link to the last year's worth of user sessions language setting https://docs.google.com/spreadsheets/d/1AMLjlUEbqJlmk4Jr9Z_En1EE9hJytOHQ0v939PbYIKA/edit?usp=sharing
> > 
> > 
> > 
> > Language
> > Users
> > 
> > 
> > 
> > 
> > en-us
> > 46,529
> 
> This document is private
> 
> How do you explain such a low number. Is that a very small fraction of users accepted to share data? It seems suspicious compared to the number of user we think we have with play store data

It's even smaller than that - this is only 10% of whatever % of our users agree to share. In order to stay within the hit count limits on free tier of google analytics I implemented it as a sampling strategy based on guesses of the % of users that would consent, and the total userbase projected a couple years into the future, and it seemed that 10% or so sample was about right.

When using our google analytics numbers then the only valid comparisons with regard to magnitude of a number are between other analytics numbers. In that sense then if I remember the 'ar' local at something like 100 sessions vs 69000 total sessions, we are looking at .14% of the total userbase, and realistically that should guide our investment

That's where my stance of doing our best to get it right but then moving along comes from

I granted you access to it - didn't realize it was private sorry - and will grant access to anyone else that requests it, just ask on the doc

2021-03-21 08:02 UTC, irshadmd commented on AnkiDroid/src/main/res/layout/model_field_editor_list_item.xml
> +        android:layout_width="match_parent"
> I'm not going to review the UI after RTL change myself, since I never use it. If someone other than the author could confirm that they tested this version and that nothing got worse, I'll approve it.
> I don't require everything to be perfect, but if you see problems that are not listed above, please mention them.
> 
> In any case, this will need to stay in alpha and beta some time, since it may be a big change. Every commit currently seems to make perfect sens and I'd approve this if I got confirmation nothing obviously broke.

@Arthur-Milchior  I have tested and the layout is working fine as expected.

2021-03-22 17:40 UTC, TarekkMA commented
@eginhard I did fix the undo button. Yes you are correct. The graphs didn't change from the "flip", it is still displayed the same.

2021-03-22 17:50 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.java
> +    }
I had to implement this because the original `MenuItem` API don't seem to flip when supplied with auto mirrored drawable. I think the issue is that `ActionMenuItemView` is not based on an ImageView but a TextView.

I think the does mimic the original `ActionMenuItemView` when showing as an icon, the on click listener seems like a hack, but all other APIs are hidden and not public.

2021-03-25 08:52 UTC, eginhard commented
Sorry for being slow to check this. `grep -r "ic_undo" AnkiDroid/src/*` shows a few more places where the icon is used, can you ensure they are handled as well?

2021-03-25 13:04 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.java
> +    }
> Sorry for being slow to check this. `grep -r "ic_undo" AnkiDroid/src/*` shows a few more places where the icon is used, can you ensure they are handled as well?

No worries.  I will try to spot all uses of to undo icon and change them as well

2021-03-25 13:04 UTC, TarekkMA commented
> Sorry for being slow to check this. `grep -r "ic_undo" AnkiDroid/src/*` shows a few more places where the icon is used, can you ensure they are handled as well?

No worries.  I will try to spot all uses of to undo icon and change them as well

2021-03-26 13:50 UTC, eginhard approved these changes
Seems all good now from a usability point of view. Maybe @david-allison-1 can have another look.

2021-03-26 14:06 UTC, Arthur-Milchior commented
> > Sorry for being slow to check this. `grep -r "ic_undo" AnkiDroid/src/*` shows a few more places where the icon is used, can you ensure they are handled as well?
> 
> No worries. I will try to spot all uses of to undo icon and change them as well

You know you can ask Android Studio to search for a string anywhere in the code. Ctrl+shift+F. Or if you already have one, you can find all other occurrence by clicking on it and then doing alt+f7.That should ensure that you find all of them

2021-03-26 14:53 UTC, TarekkMA commented
> You know you can ask Android Studio to search for a string anywhere in the code. Ctrl+shift+F. Or if you already have one, you can find all other occurrence by clicking on it and then doing alt+f7.That should ensure that you find all of them

Yes I did use the "Find Usage" feature, and I think I got them all.

2021-03-26 15:18 UTC, Arthur-Milchior reviewed
That seems fine by me, and I really like having other people confirming it work. I'd just love seeing some more context in commit message. I must admit that this is really not part of the code I know, I fear that few people here really know what's going on in this android xml, so really more detailled commit message would be wonderful

2021-03-26 15:18 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/menu-television/reviewer.xml
> +        ankidroid:actionProviderClass="com.ichi2.ui.RtlCompliantActionProvider"
Is there any reason to have one `ankidroid:actionProviderClass="com.ichi2.ui.RtlCompliantActionProvider"` in the same commit as the definition of this class and the other ones elsewhere? Both together would seem fine

2021-03-26 15:18 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.java
> +            Drawable iconValue = AppCompatResources.getDrawable(getContext(), R.drawable.ic_menu_back_black_24dp);
Could you please put such message in the commit message ? It's really not stuff we do here usually, so explaining the reason behind the commit will be really useful here. In particular indicating what are the VectorDrawableCompat you're mentioning. I don't see anything with this name nearby

2021-03-26 15:30 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.java
> +    }
Sorry I meant the icon.

If to undo menu item can/should be shown in the toolbar, its action view should be visible. The default  action view is `ActionMenuItemView` which is an internal class in the Android API visible only to the SDK itself. When the icon supplied to `ActionMenuItemView` does have `autoMirrored = true`, it does ignore it and lay the image without mirroring in the case of RTL locals.

When I looked into `ActionMenuItemView` I found there is no image view at all, the only view is a text view used to do everything. I'm not sure, but I think to `autoMirrored` to work it needs an image view.

2021-03-26 15:32 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +        undoIcon.getActionView().setEnabled(undoEnabled);
Opps, yes this is a typo

2021-03-26 15:37 UTC, TarekkMA commented on AnkiDroid/src/main/res/menu-television/reviewer.xml
> +        ankidroid:actionProviderClass="com.ichi2.ui.RtlCompliantActionProvider"
Okay, I will squash them.

2021-03-26 15:40 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +        undoIcon.getActionView().setEnabled(undoEnabled);
The issue about the menu item API is most of it is hidden and have `@RestrictTo(LIBRARY_GROUP_PREFIX)`. 

So setting enabled on the item itself don't really reflect on the custom action view I have created.

There maybe a better way but I have searched in the SDK source code and all the classes/interfaces they use is hidden. Also, couldn't find a way online.

2021-03-26 15:45 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.java
> +            Drawable iconValue = AppCompatResources.getDrawable(getContext(), R.drawable.ic_menu_back_black_24dp);
I will put this in the commit message.

I have replaced `VectorDrawableCompat` with `AppCompatResources`.

But as for why `autoMirror` don't work with `VectorDrawableCompat` I don't know. I replaced it with `AppCompatResources` and it just worked.

2021-03-26 15:48 UTC, TarekkMA commented on AnkiDroid/src/main/res/menu-television/reviewer.xml
> +        ankidroid:actionProviderClass="com.ichi2.ui.RtlCompliantActionProvider"
There is no reason I was just committing as issues appeared.

2021-03-26 16:14 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
> +        mExpandImage.setAutoMirrored(true);
I don't think this can be done on xml.

But from looking at the surrounding code, it all about style.

I couldn't put  `android:autoMirrored` in xml directly because the view is `ImageButton`, and `android:autoMirrored` only be applied in xml on `ImageView`.

And a strange thing is in code I cannot do `ImageView#setAutoMirrored(boolean)` because this setter doesn't exist. The only way to do it in code is to set this property on the `Drawable` object itself

2021-03-26 16:21 UTC, TarekkMA commented
@Arthur-Milchior 
> That seems fine by me, and I really like having other people confirming it work. I'd just love seeing some more context in commit message. I must admit that this is really not part of the code I know, I fear that few people here really know what's going on in this android xml, so really more detailled commit message would be wonderful

Yeah, I will add more info on the commit messages. And also the resources @eginhard pointed should be put in the developer documentation.

The only thing that I made custom is the `RtlCompliantActionProvider`, because AFAIK the android SDK handling of menues is lacking in this regard (RTL).

2021-03-26 16:47 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/menu-television/reviewer.xml
> +        ankidroid:actionProviderClass="com.ichi2.ui.RtlCompliantActionProvider"
Thanks, let me know when review should be done again

2021-03-26 16:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +        undoIcon.getActionView().setEnabled(undoEnabled);
That'll be fine by me. I clearly won't duplicate your research and trust you here. Just, if you could put this information in a commit message, it would be great

2021-03-26 19:09 UTC, TarekkMA commented
@Arthur-Milchior Done, it's ready for another reaview.

2021-03-26 19:29 UTC, Arthur-Milchior commented
> And also the resources @eginhard pointed should be put in the developer documentation.

Most doc is a wiki. Feel free to edit it. Just create a google doc and share the link if you want someone to review it first

2021-03-26 19:44 UTC, Arthur-Milchior approved these changes
Thanks a lot for this big change.
Dealing with GSoC had been exhausting, however, it's really rewarding to see that it also led to changes that nobody in the team a month ago could have done properly (as we could not even have tested whether the result looks as expected).

I hope that @mikehardy or @david-allison-1 can review it soon, and that'll be a very cool thing to put in the next changelog

2021-03-26 19:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
> +        mExpandImage.setAutoMirrored(true);
I agree that the code nearby is about style. Hopefully, it should be corrected too. No idea how to do it, I really don't know the xml sadly

2021-03-26 19:53 UTC, TarekkMA commented
Thanks a lot for your kind words ❤️

2021-03-27 00:06 UTC, david-allison-1 commented
This is high priority on my TODO list. I'll aim to have this tested tomorrow. Running on my phone now:

```
git fetch upstream pull/8261/head:8261-02
git checkout 8261-02
git rev-parse HEAD
2ae45160d78572276edf1adaa9283cc6da135b5e
```

2021-03-27 00:25 UTC, david-allison-1 requested changes
Just one visual thing. I think this is really close, thanks so much for the hard work!

![image](https://user-images.githubusercontent.com/62114487/112704335-290cb480-8e92-11eb-8b66-416b4fa58529.png)

2021-03-27 00:25 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.java
> +        return (Activity) context;
We may want a better error message (for example: how will his fail if someone passes in `AnkiDroidApp.getInstance()`)

2021-03-27 00:25 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.java
> +            if (!forItem.isEnabled()) {
Note to self: test this manually on the final run

2021-03-27 06:54 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.java
> +        return (Activity) context;
Oh okay, I don't think this class should be instantiated manually, the android SDK should handle it. But will make sure to throw an exception in case of context being of other type than activity

2021-03-27 06:58 UTC, TarekkMA commented
@david-allison-1  yes I saw this issue on the android issue tracker https://issuetracker.google.com/issues/146100178 it's marked as fixed, will see how to apply this fix here

2021-03-27 08:03 UTC, TarekkMA commented
@david-allison-1 
Did add some tests on `RtlCompliantActionProvider#unwrapContext` and now it should throw with a message if the base context wasn't an activity after unwrapping it.

And as we discussed on Discord the issue with menu icons should be fixed when appcompat 1.3.0 is released
https://developer.android.com/jetpack/androidx/releases/appcompat#1.3.0-rc01

2021-03-27 09:47 UTC, david-allison-1 commented
@mikehardy Are we OK to move to `appcompat:1.3.0-rc01` in a separate PR to get this in.

Possible options (in priority order for me)

1. Attempt to move to `appcompat:1.3.0-rc01`
2. Revert the icons until appcompat is stable & working
3. Force the menu to LTR
4. Temporarily fork and apply the 2 lines that we need
5. Leave the icons broken

2021-03-28 18:19 UTC, david-allison-1 approved these changes
LGTM - need to check over the commits to see if this is a rebase or a squash - likely a rebase

2021-03-28 18:38 UTC, Arthur-Milchior commented
Rebase if I have to decide. I always prefer to keep commit small and easy to read

2021-03-28 18:38 UTC, merged