Possible fix for amazon App Store issue
ankidroid/Anki-Android pull request #8269
Opened 2021-03-18 16:53 UTC by imaryandokania

## Pull Request template

## Purpose / Description
The issue was related with CAMERA request in Manifest.xml,this is not tested yet.

## Fixes
fixes bug ankidroid#8151

## Approach
Tried for a runtime permission from user.
## How Has This Been Tested?
Not tested since I have no permission of amazon App Store 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-18 22:34 UTC, david-allison-1 requested changes
Hi, thanks for the PR!

I don't think this is the correct approach. 

We definitely don't want to be asking for Camera permission as soon as the app starts up, this will frustrate our users. 

We already request camera access as a runtime permission when required, and handle refusal of this permission

https://github.com/ankidroid/Anki-Android/blob/9c8182dde2ed45a0c0de69214097ac10c85bd14a/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java#L145-L151

2021-03-19 02:19 UTC, imaryandokania commented
Oh okay,I thought a runtime camera permission at start would have solved this, I have gone through stack overflow for reasons behind issue of amazon app store, I find everywhere about Runtime permission. So now I am out of options😅. Only I can think now is not listed fire devices as available devices for the app.

2021-03-19 08:28 UTC, mrudultora commented
@david-allison-1 I think we need to contact Amazon app store. Because I found a similar issue on amazon's [developer forum].(https://forums.developer.amazon.com/questions/135455/app-available-on-web-and-amazon-app-store-but-not.html)

2021-03-19 08:40 UTC, david-allison-1 commented
> @david-allison-1 I think we need to contact Amazon app store. Because I found a similar issue on amazon's [developer forum](https://forums.developer.amazon.com/questions/135455/app-available-on-web-and-amazon-app-store-but-not.html).

I don't have credentials for that, let's move this discussion to the main issue.

2021-03-19 08:41 UTC, david-allison-1 commented
I don't think this is going to be the strategy to fix the issue. Let's consolidate discussion on the issue.

2021-03-19 08:41 UTC, closed without merging