fix:#8267:Correction made in PreferenceReview.
ankidroid/Anki-Android pull request #8280
Opened 2021-03-19 19:40 UTC by haran2248

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_
The UX is causing users to get confused with setting time above 24 hours

## Fixes
Fixes _Link to the issues._
#8267

## Approach
_How does this change address the problem?_
Label has been added to specify the range of the hours
![WhatsApp Image 2021-03-20 at 01 09 50](https://user-images.githubusercontent.com/56928954/111834036-08d07900-8919-11eb-970b-6b5cd8a8594e.jpeg)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-20 04:06 UTC, Arthur-Milchior commented
Thanks for the contribution.
Three remarks, I'm sorry for having nits bigger than the contribution.

I would really prefer commit message to start by indicating in English what they correct.
The goal of a commit message is that you can look at history and see what was done. Maybe take a look at https://github.com/ankidroid/Anki-Android/blame/3141375007a3aac3c2531c3f1cbdb1ba228b37ae/AnkiDroid/src/main/res/values/10-preferences.xml if you never did, this is a way to quickly see why a line was added/changed. The bug number is not descriptive. It is nice to have it in the description, but certainly not as start of first line.

I'd also like your message to literally contains

" fixes #8267 " because this is what Github looks for when trying to understand what the PR does. If you put "fix:#8167" github won't close the bug.

Finally, I'd like you to create a new String id. We keep current string id when we only correct a typo, a space omitted after a comma. If we keep the same id, we'll use the same translation. Changing the ID means that translators will see they need to update the translation

2021-03-20 04:09 UTC, Arthur-Milchior commented
I forgot. I would appreciate if you could remove sentences such as "How does this change address the problem?". Indeed, when I and other maintainers read the description, it's really nice to see quickly the actual content, and  here it's slightly complex to see the difference with the section description

2021-03-20 04:26 UTC, haran2248 commented
> Thanks for the contribution.
> Three remarks, I'm sorry for having nits bigger than the contribution.
> 
> I would really prefer commit message to start by indicating in English what they correct.
> The goal of a commit message is that you can look at history and see what was done. Maybe take a look at https://github.com/ankidroid/Anki-Android/blame/3141375007a3aac3c2531c3f1cbdb1ba228b37ae/AnkiDroid/src/main/res/values/10-preferences.xml if you never did, this is a way to quickly see why a line was added/changed. The bug number is not descriptive. It is nice to have it in the description, but certainly not as start of first line.
> 
> I'd also like your message to literally contains
> 
> " fixes #8267 " because this is what Github looks for when trying to understand what the PR does. If you put "fix:#8167" github won't close the bug.
> 
> Finally, I'd like you to create a new String id. We keep current string id when we only correct a typo, a space omitted after a comma. If we keep the same id, we'll use the same translation. Changing the ID means that translators will see they need to update the translation

Yes I will correct this

2021-03-20 04:27 UTC, Arthur-Milchior commented
I missed a last note (Added it in my last message, repeating it here for the sake of completion since you answered):

Also, indicating in the commit title which correction you made would be great. Indeed, in the page linked about, stating that it's related to preference is not really useful since it's already indicated in the name of the file.

2021-03-20 04:31 UTC, haran2248 commented
> I missed a last note (Added it in my last message, repeating it here for the sake of completion since you answered):
> 
> Also, indicating in the commit title which correction you made would be great. Indeed, in the page linked about, stating that it's related to preference is not really useful since it's already indicated in the name of the file.

Yes sure

2021-03-21 06:01 UTC, haran2248 commented
> Finally, I'd like you to create a new String id. We keep current string id when we only correct a typo, a space omitted after a comma. If we keep the same id, we'll use the same translation. Changing the ID means that translators will see they need to update the translation.

The new string label is not translated in any other language,Is there any fix for this?

2021-03-21 06:05 UTC, david-allison-1 commented
> Ignore any errors stating that these are missing translations after adding the string. If it compiles, it's fine. Maintainers will handle generating the strings after the pull request is completed.

https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#adding-translations

2021-03-21 06:34 UTC, haran2248 commented
> > Ignore any errors stating that these are missing translations after adding the string. If it compiles, it's fine. Maintainers will handle generating the strings after the pull request is completed.
> 
> https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#adding-translations

I have added screenshot of the new string,It is said that maintainers will take care of translating it,Is there anything else to be done

2021-03-21 06:45 UTC, david-allison-1 reviewed
Minor request RE: string value

It'd be nice to squash your changes into atomic commits without "fixups" so we can review & merge a stream of commits

Other than that, looks good

2021-03-21 06:45 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="day_offset_with_description">Start of next day (0 is Midnight , 23 is 11PM)</string>
```suggestion
    <string name="day_offset_with_description">Start of next day (0 is midnight, 23 is 11PM)</string>
```

2021-03-21 07:26 UTC, haran2248 commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="day_offset_with_description">Start of next day (0 is Midnight , 23 is 11PM)</string>
done

2021-03-21 07:47 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="day_offset_with_description">Start of next day (0 is midnight , 23 is 11PM)</string>
```suggestion
    <string name="day_offset_with_description">Start of next day (0 is midnight, 23 is 11PM)</string>
```

2021-03-21 07:52 UTC, haran2248 commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="day_offset_with_description">Start of next day (0 is midnight , 23 is 11PM)</string>
anything else Ill do everything together

2021-03-22 07:46 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="day_offset_with_description">Start of next day (0 is midnight,23 is 11PM)</string>
```suggestion
    <string name="day_offset_with_description">Start of next day (0 is midnight, 23 is 11PM)</string>
```

2021-03-22 08:48 UTC, david-allison-1 approved these changes
Looks good to me, thanks!

2021-03-22 08:49 UTC, david-allison-1 requested changes
CI failure: 

```
  /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/10-preferences.xml:158: Error: The resource R.string.day_offset appears to be unused [UnusedResources]
      <string name="day_offset">Start of next day</string>
```

We'll need to discuss how we deal with this - likely best to delete the string and have our translators re-translate with the additional information.

2021-03-22 10:28 UTC, haran2248 commented
> CI failure:
> 
> ```
>   /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/10-preferences.xml:158: Error: The resource R.string.day_offset appears to be unused [UnusedResources]
>       <string name="day_offset">Start of next day</string>
> ```
> 
> We'll need to discuss how we deal with this - likely best to delete the string and have our translators re-translate with the additional information.

Are you sure I can delete this,I believe @Arthur-Milchior said something about replacing/deleting strings

2021-03-22 11:14 UTC, Arthur-Milchior commented
> Are you sure I can delete this,I believe @Arthur-Milchior said something about replacing/deleting strings

I said the same thing. You should delete previous string and create a new one. 
The previous string is not used anymore, it's dead code, no reason to keep it.

2021-03-22 11:17 UTC, Arthur-Milchior approved these changes

2021-03-22 19:27 UTC, haran2248 commented
@david-allison-1 Can you see if everything is fine?

2021-03-23 07:43 UTC, david-allison-1 approved these changes
Looks good to me, thanks!

2021-03-24 17:24 UTC, mikehardy approved these changes
Nice!

2021-03-24 17:26 UTC, merged