Fixes #8272: Removed white space for no title in a StyledProgressDialog dialouge popup
ankidroid/Anki-Android pull request #8289
Opened 2021-03-20 13:26 UTC by Ekagra

## Purpose / Description
Removing white space for no title in a StyledProgressDialog dialouge popup

## Fixes
https://github.com/ankidroid/Anki-Android/issues/8272

## Approach
I looked over every method using `StyledProgressDialog`  with title being "" and replaced with null

## How Has This Been Tested?
<p float="left">
  <img src="https://i.imgur.com/K0X1tuW.jpeg" width="400" />
</p>

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-20 13:40 UTC, david-allison-1 reviewed
Thanks!!

Can we fix this in `StyledProgressDialog.show` as well - translate `""` to null, and possibly put out a Debug warning that this occurs?

2021-03-21 04:50 UTC, Ekagra commented
@david-allison-1 I can't clearly understand you, could you kindly explain it again?

2021-03-21 04:54 UTC, david-allison-1 commented
https://github.com/ankidroid/Anki-Android/blob/05c58c2f02d10ba2a8a338af427e12c3c7d6926d/AnkiDroid/src/main/java/com/ichi2/themes/StyledProgressDialog.java#L61-L70

If we never want a `""` to go through, we can add.

```java
if ("".equals(title)) {
    title = null;
    Timber.w("Invalid title was provided. Using null");
}
```

This fixes the issue permanently for users, and notifies developers that code changes are required.

2021-03-21 05:27 UTC, Ekagra commented
got it should I implement this instead?

2021-03-21 05:48 UTC, david-allison-1 commented
> got it should I implement this instead?

I feel we might as well do both

2021-03-21 05:52 UTC, Ekagra commented
alright should make a commit changing `StyledProgressDialog` now ?

2021-03-21 05:55 UTC, david-allison-1 commented
yep

2021-03-21 12:19 UTC, Ekagra commented
added a  commit kindly review it @david-allison-1

2021-03-21 12:24 UTC, david-allison-1 approved these changes
Thanks! Looks good to me!

2021-03-21 12:26 UTC, david-allison-1 commented
Just to note:

Could you try and keep the commit messages to 50 characters in the future?

Commit messages can have an arbitrarily sized body: https://chris.beams.io/posts/git-commit/

We can squash/merge and change it for now, but it helps keep our commit log readable

2021-03-21 12:29 UTC, Ekagra commented
yeah sure noted!

2021-03-21 12:36 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/themes/StyledProgressDialog.java
> +        if (title.equals("")) {
If title is null, then this fails

```suggestion
        if ("".equals(title)) {
```

2021-03-21 12:41 UTC, Ekagra commented on AnkiDroid/src/main/java/com/ichi2/themes/StyledProgressDialog.java
> +        if (title.equals("")) {
fixed

2021-03-21 13:04 UTC, david-allison-1 approved these changes

2021-03-21 15:54 UTC, mikehardy requested changes
I think it should be Timber.d not Timber.w as mentioned

2021-03-21 15:54 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/themes/StyledProgressDialog.java
> +            Timber.w("Invalid title was provided. Using null");
A `Timber.w` is a warning, in our convention that means "something is definitely wrong, but we may recover and continue".

So, if "something is definitely wrong", how can the same commit be *adding* uses of the style that triggers a warning?

It seems to me that there is nothing wrong with using null and we don't even need an informative message, we are *expecting* to send null and handling it now. At most this should be `Timber.d` now, just so developers aren't surprised but that's it I think
```suggestion
            Timber.d("Invalid title was provided. Using null");
```

2021-03-21 16:01 UTC, Ekagra commented on AnkiDroid/src/main/java/com/ichi2/themes/StyledProgressDialog.java
> +            Timber.w("Invalid title was provided. Using null");
done

2021-03-21 16:04 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/themes/StyledProgressDialog.java
> +            Timber.w("Invalid title was provided. Using null");
The commit is removing `""`, the source of the warning, not adding it.

But `.d` works - we'll pick it up in logcat on a debug machine regardless

2021-03-21 16:10 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/themes/StyledProgressDialog.java
> +            Timber.w("Invalid title was provided. Using null");
Ah, sorry was thinking opposite @david-allison-1 - I still don't think it warrants a .w though, .d will note it for devs as mentioned

2021-03-21 16:10 UTC, mikehardy approved these changes

2021-03-21 16:11 UTC, mikehardy commented
Just pending CI (and labeled as such) anyone can squash-merge when/if they see CI pass

2021-03-21 16:39 UTC, Ekagra commented
how to get this PR merged now ?

2021-03-21 16:48 UTC, merged

2021-03-21 16:48 UTC, mikehardy commented
Yep - merged, just needed CI to pass and it just did :rocket:

2021-03-21 16:57 UTC, Ekagra commented
glad to have my first PR merge 🥳

2021-04-05 18:32 UTC, mikehardy commented
Hi there!

Just a friendly notice (one per person for PRs merged in March, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for March 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

Thanks!