Implemented FloatingActionMenu Without External Dependency
ankidroid/Anki-Android pull request #8290
Opened 2021-03-20 16:01 UTC by Akshay0701

## Reference 
#4936 

## Feature implemented of FloatingActionMenu without external dependency :
->Open add new note activity
->Open get Shared Decks WebView
->Open create new deck dialog
-> handled FABs layout on snackbar appear

## Output 
<img src="https://user-images.githubusercontent.com/52353967/111866119-3822cc80-8991-11eb-87b6-136595f039da.gif" width="250" height="500" />

2021-03-20 16:48 UTC, mikehardy requested changes
I'm excited by this!

The spacing problems must be corrected, and we should use SVGs going forward plus handle activity restarts, but the problems I see are not that big in my mind, now that you have it proven working. The stuff I noted is all small I think and we should be able to get this in shape for merge quickly

Thank you!

2021-03-20 16:48 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +	 private FloatingActionButton addDeckButton,addNoteButton,addSharedButton,fabMain;
The spacing here is strange? It appears you may be using tabs vs spaces

```suggestion
    private FloatingActionButton addDeckButton,addNoteButton,addSharedButton,fabMain;
```

Please go through the entire diff and make sure you are using spaces as specified https://github.com/ankidroid/Anki-Android/wiki/Code-style#white-spaces

2021-03-20 16:48 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +	 private FloatingActionButton addDeckButton,addNoteButton,addSharedButton,fabMain;
Also we do not declare multiple items on one line, each declaration gets its own line

2021-03-20 16:48 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private boolean isFABOpen = false;
I think this is new internal state yes? It should be `mIsFABOpen` and I think it should be included in the Bundle that is saved and restored onSaveInstanceState and onCreate so it survives activity restart

2021-03-20 16:48 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    // private FloatingActionsMenu mActionsMenu;
git is our history, we do not leave commented out code, please remove this and any other lines that you have commented out

2021-03-20 16:48 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    }
the spacing here does not seem to follow our style guide

2021-03-20 16:48 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        fabMain.animate().rotationBy(140);
I believe users may set a preference that indicates if they want animation or not, this is important for us to function correctly on e-ink devices. Could you scan the code in other animated areas to see how we access that preference, and then determine if animations should be used or not, only animating if they should be used?

2021-03-20 16:48 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        fabMain.animate().rotation(0);
Same here with animation, I personally like it and users on phones expect it, but it makes the app unusable on e-ink devices so we need to respect the user preference and only animate if they prefer it

2021-03-20 16:48 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +		 addNoteLayout = (LinearLayout) findViewById(R.id.add_note_layout);
spacing

2021-03-20 16:48 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +}
interesting, you changed the line ending on the file, which is not a big deal but indicates that your editor may not be configured for file endings following the style guide

2021-03-20 16:48 UTC, mikehardy commented on AnkiDroid/src/main/res/layout/floating_add_button.xml
> +            android:src="@drawable/ic_add_white_24dp"
I think we can move to SVGs for this now? I note these are still PNG files https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/res/drawable-hdpi/ic_add_white_24dp.png 

Can you swap in the SVG for these from here https://github.com/ankidroid/Anki-Android/pull/5134/files#diff-0c2d14511e351e6957faa40dbc083de47ec364b52dfe67d62bd9073e18f7fb58 (this is a link to ic_add_white but the others should be available as well) and delete the PNGs?

2021-03-20 16:49 UTC, mikehardy commented
I have edited the PR title to explicitly say `Fixes #issuenumber` so that github cross links things correctly

2021-03-21 04:56 UTC, david-allison-1 reviewed
Note: animation method is `AnkiActivity.animation[Enabled/Disabled]`

2021-03-21 06:09 UTC, Akshay0701 commented
Thanks @david-allison-1 , 
Things changed in last commit :
->used `animationEnabled` method from AnkiActivity class to get preference of user animation,
->Converted png's to svg and deleted png's,
->removed spaces,
->included `mIsFABOpen` in  Bundle onSaveInstanceState method and restored on onRestoreInstanceState method

2021-03-21 06:22 UTC, david-allison-1 reviewed
There still seem to be animations for the vertical translation

Needs a re-review and a finer look, but the code seems sensible from first glance

2021-03-21 06:22 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +		mIsFABOpen = savedInstanceState.getBoolean("mIsFABOpen");
spacing changed

2021-03-21 06:22 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/dimens.xml
> +    <dimen name="standard_100">110dp</dimen>
standard_100 is 110? Might need a comment.

I don't understand why we'd have resource values with a number in the name

2021-03-21 06:41 UTC, Akshay0701 commented on AnkiDroid/src/main/res/values/dimens.xml
> +    <dimen name="standard_100">110dp</dimen>
It is mistake to put 100 , I will change that

2021-03-21 06:43 UTC, Akshay0701 commented on AnkiDroid/src/main/res/values/dimens.xml
> +    <dimen name="standard_100">110dp</dimen>
I can directly put this value to Deckpicker activity animation function but I thought to declare it in diems ,should remove this value from diems?

2021-03-21 06:46 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/dimens.xml
> +    <dimen name="standard_100">110dp</dimen>
If we're not going to vary the values, and we've named them after the value, there doesn't seem to be a need

2021-03-21 06:47 UTC, david-allison-1 commented
Sorry, thought I'd mentioned.

A lot of the spacing of the code doesn't match the above/below code, there's also quite a lot of spacing that doesn't conform to our code style guide: https://github.com/ankidroid/Anki-Android/wiki/Code-style

2021-03-21 07:52 UTC, Akshay0701 commented
@david-allison-1 
![Capture](https://user-images.githubusercontent.com/52353967/111897779-d6716980-8a47-11eb-8100-69d2f4538f56.PNG)
you said "There still seem to be animations for the vertical translation"
If user animation preference is disabled then code should not run any animation right ? so my doubt is how Fabs button will move up in layout ?

2021-03-21 14:51 UTC, 4shutosh commented
Hey @Akshay0701 , for the wrong spacing here's a quick suggestion,
`ctrl + alt + l` : android studio shortcut for fomatting the code.

Most of time this formats the code well but some files does not follow the android studio formatting rules, while using this make sure you don't make unwanted changes defying the code style.

2021-03-22 03:52 UTC, Akshay0701 commented
<img src="https://user-images.githubusercontent.com/52353967/111938212-7b934d00-8aef-11eb-842a-841d10459267.gif" width="250" height="500" />---<img src="https://user-images.githubusercontent.com/52353967/111938216-7d5d1080-8aef-11eb-80b0-f6edaab29086.gif" width="250" height="500" />
1 Image Animation preference enabled 
2 Image Animation preference disabled

2021-03-24 16:45 UTC, david-allison-1 requested changes
* Needs a color change to match the original
* Needs background for text
* Ordering of items has changes
* Position has changed
* Shadow is worse

<details><summary>Before (expanded)</summary>

![image](https://user-images.githubusercontent.com/62114487/112348629-e7c4ab00-8cbf-11eb-92ea-aad7784159bb.png)

</details>


<details><summary>After (expanded)</summary>

![image](https://user-images.githubusercontent.com/62114487/112348785-0f1b7800-8cc0-11eb-80f7-0edb700f034b.png)

</details>

<details><summary>Shadow - Before</summary>

![image](https://user-images.githubusercontent.com/62114487/112349052-4ee25f80-8cc0-11eb-9749-1b9b77be6bef.png)

</details>


<details><summary>Shadow - After</summary>

![image](https://user-images.githubusercontent.com/62114487/112348933-32debe00-8cc0-11eb-8632-f76df479324f.png)


</details>

2021-03-24 17:07 UTC, mikehardy commented
I'm still excited it's functioning - David I think most of your comments are easy layout fixes (hopefully I'm right!). I really want to get rid of that old FAB library

2021-03-24 17:08 UTC, david-allison-1 commented
Nothing worrying in there, really happy to get animation removal sorted for it

2021-03-24 17:34 UTC, Akshay0701 commented
yes @mikehardy ,its minor changes, but i will not able to complete this changes till end of this week because final semester exams is going on :)

2021-03-24 17:53 UTC, mikehardy commented
@Akshay0701 never a rush, that's fine of course. Good luck on your exams!

2021-03-24 17:58 UTC, david-allison-1 commented
> yes @mikehardy ,its minor changes, but i may not able to complete this changes till end of this week because final semester exams is going on :)

Good luck with the exams! Life takes priority, we really appreciate your time

2021-03-24 18:52 UTC, mikehardy commented
@tanmayChakrawarty brought up an interesting point on the related issue, I'm consolidating discussion here - when consulting the material design website they show that FABs that do not cover the whole screen, when expanded, usually involve a dimming transition in the layer underneath - you can see it in the third example animation here https://material.io/design/motion/the-motion-system.html#container-transform (that's the one that matches our FAB use case)

if it is possible to add it to this PR, that would be great (specifically - Tanmay - if you have an example snippet you could contribute that would help, but opening a second PR I think would be counter-productive until this lands). If animation is off I would just immediately alter the underlying view to be dimmer, if it was on I would animate it between undimmed/dimmed at the same speed the FAB opens/closes

2021-03-25 06:49 UTC, tanmayChakrawarty commented
@mikehardy I implemented that feature the code is the same as done earlier by @Akshay0701 in this PR, small changes that I did is in the `floating_add_button.xml` file i.e. I only removed the parent linear layout under which all the linear layout are present 
( but I think if we include the view under that parent linear layout then it will also work ).
Result:- ( Tested on a physical device Android 5.0.2)
![S](https://user-images.githubusercontent.com/75254780/112430420-21e78880-8d64-11eb-935f-2b7f8b5ae9ac.gif)

2021-03-27 11:22 UTC, david-allison-1 requested changes
Much better!!

Can we keep the color consistent with how it was before. Previously this was `@color/material_light_blue_700` on the default theme, but will need to confirm what it was for the other color schemes.
  
I run my Android animations on 2x speed, and the animation is still a little too slow for my liking. Could you check this with other maintainers, but I feel it should be sped up a lot

2021-03-27 11:22 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/dimens.xml
> +    <dimen name="standard_60">60dp</dimen>
I don't really see the point in these

2021-03-27 11:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private FloatingActionButton addDeckButton;
Note: these need to match our naming guidelines https://github.com/ankidroid/Anki-Android/wiki/Code-style#non-public-non-static-field-names-should-start-with-m

2021-03-27 11:25 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private FloatingActionButton addDeckButton;
Design: I'd be tempted to move these into a new class - there's a lot of new variables and code here

2021-03-27 13:23 UTC, Akshay0701 commented
@david-allison-1 Actually i don't know why fab color is showing gray in light mode and blue in dark mode , i just used 

> app:fab_colorNormal="?attr/fab_normal"
> app:fab_colorPressed="?attr/fab_pressed"

2021-03-27 13:56 UTC, david-allison-1 requested changes
Looks so much cleaner!!! Thanks a bunch

Just a few naming things, one question about creating decks

2021-03-27 13:56 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/FloatingActionMenu.java
> +        this.ankiActivity = new AnkiActivity();
`DeckPicker` is an AnkiActivity, just use that

2021-03-27 13:56 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/FloatingActionMenu.java
> +    public FloatingActionMenu(Context mContext, View mView, DeckPicker deckPicker) {
```java
    public FloatingActionMenu(Context context, View view, DeckPicker deckPicker) {
```

2021-03-27 13:56 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/FloatingActionMenu.java
> +    private DeckPicker deckPicker;
```java
    private DeckPicker mDeckPicker;
```

2021-03-27 13:56 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/FloatingActionMenu.java
> +    private boolean createNewDeck(String deckName) {
This doesn't seem correct - shouldn't it call through to `DeckPicker.createNewDeck`

2021-03-27 13:56 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private FloatingActionMenu mFloatingActionMenu;
```java
    private DeckPickerFloatingActionMenu mFloatingActionMenu;
```

2021-03-27 14:05 UTC, david-allison-1 commented
> @david-allison-1 Actually i don't know why fab color is showing gray in light mode and blue in dark mode , i just used
> 
> > app:fab_colorNormal="?attr/fab_normal"
> > app:fab_colorPressed="?attr/fab_pressed"

Unsure - could you have another shot at this, and add to my spreadsheet if you hit a dead end and this will need a deep dive

2021-03-27 17:32 UTC, Akshay0701 commented
yes `app:fab_colorNormal` is used from google.material.floatingActionButton library  , actually i am too beginner and this is first time i heard of "attr/color" , so i have no idea why color is showing different ,to be honest with you @david-allison-1 .

2021-03-27 18:03 UTC, Akshay0701 commented
hey @david-allison-1 ,i found out cause of color issue after reading documentation, we should use 
`app:backgroundTint="?attr/fab_normal"`

<img src="https://user-images.githubusercontent.com/52353967/112729939-a8fb5300-8f54-11eb-8537-edc5580f56d6.jpg" width="250" height="500" />-----<img src="https://user-images.githubusercontent.com/52353967/112729935-a7318f80-8f54-11eb-8b3e-b2a7ba17430b.jpg" width="250" height="500" />

2021-03-27 19:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private FloatingActionButton fabMain;
nit: naming guidelines: https://github.com/ankidroid/Anki-Android/wiki/Code-style#non-public-non-static-field-names-should-start-with-m

2021-03-27 19:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private FloatingActionButton fabMain;
I think most of these variables are now unused

2021-03-27 19:26 UTC, david-allison-1 reviewed
Functionally, this works perfectly, thank you!!

A few nitpicks and we're good to go

2021-03-27 19:26 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        savedInstanceState.putBoolean("mIsFABOpen", mIsFABOpen);
I don't think this works any more - you have two variables: one in the class, and one here

2021-03-27 19:26 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.java
> +    private FloatingActionButton addDeckButton,addNoteButton,addSharedButton,fabMain;
Switch these to one line per variable. 

Use an `m` prefix for all fields: https://github.com/ankidroid/Anki-Android/wiki/Code-style#non-public-non-static-field-names-should-start-with-m

2021-03-27 19:26 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/dimens.xml
> +
can undo this

2021-03-28 05:34 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        savedInstanceState.putBoolean("mIsFABOpen", mIsFABOpen);
i think we have to replace this to `mFloatingActionMenu.mIsFABOpen` ,am i right ?

2021-03-28 05:34 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        savedInstanceState.putBoolean("mIsFABOpen", mIsFABOpen);
and i will remove all unused variables from DeckPicker as well

2021-03-28 11:07 UTC, david-allison-1 requested changes
Would be happy to see this go now, very slight amount more refinement. It's really clean now!

2021-03-28 11:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        if (mFloatingActionMenu.mIsFABOpen) {
Typically you want to go through a "getter" method: `mFloatingActionMenu.isFABOpen()`

2021-03-28 11:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        mFloatingActionMenu = new DeckPickerFloatingActionMenu(view,this);
```suggestion
        mFloatingActionMenu = new DeckPickerFloatingActionMenu(view, this);
```

2021-03-28 11:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        mFloatingActionMenu.mIsFABOpen = savedInstanceState.getBoolean("mIsFABOpen");
```suggestion
        mFloatingActionMenu.setIsFABOpen(savedInstanceState.getBoolean("mIsFABOpen"));
```

2021-03-28 11:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        mFloatingActionMenu.mIsFABOpen = savedInstanceState.getBoolean("mIsFABOpen");
Or have `mFloatingActionMenu` implement onRestoreInstanceState - for simplicity, go with the above change

2021-03-28 11:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.java
> +    private FloatingActionButton mAddDeckButton;
You can make a lot of these variables `private final`

2021-03-28 14:33 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.java
> +    private FloatingActionButton mAddDeckButton;
i will make all variables final except `isFabOpen`

2021-03-28 14:37 UTC, Akshay0701 commented
i have made getter and setter for `isFabOpen` and did added final to variables ,let me know if there ant other changes required ...

2021-03-28 15:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            if (mFloatingActionMenu.mIsFABOpen) {
Make the variable private so all of these become compile errors

```suggestion
            if (mFloatingActionMenu.isFABOpen()) {
```

2021-03-28 15:22 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            if (mFloatingActionMenu.mIsFABOpen) {
o sorry i didn't notice that one , okay i will makes changes accordingly :)

2021-03-28 18:24 UTC, david-allison-1 submitted a review, later dismissed
Looks good to me! Thanks

Looking into some automation so there's less code style related comments in these reviews - I'm aware that it's frustrating/slow and I apologise, we're working on it

2021-03-30 02:36 UTC, david-allison-1 commented
Note: A conflict will need to be resolved before this is merged

2021-03-30 03:31 UTC, Akshay0701 commented
I think I able to resolve conflict finally, Thank god 🙏

2021-03-30 12:26 UTC, Akshay0701 commented
Okay ,I will take care of that from next time

2021-03-30 12:59 UTC, david-allison-1 approved these changes
Looks good to me, thanks! Note to maintainers: needs a squash merge due to merge commit in the history, or more revisions

2021-03-30 17:00 UTC, Akshay0701 commented
First of all I am beginner in android development and I never thought I would be creating feature for any organisation , really thank you to you @mikehardy and @david-allison-1 for correcting my each small and keeping patience .

2021-03-31 07:57 UTC, Akshay0701 commented
Hii I just found one thing missing in `FabBehavior` class is whenever the snack bar appears on screen FABs view changes its Y-axis but after the snack bar disappear FABs didn't come to their origin place:--

<img src="https://user-images.githubusercontent.com/52353967/113110029-3a541900-9224-11eb-80be-62e0ee30ad3a.gif" width="250" height="500" />

I fixed this issue.
I wanted to ask that should I commit changes to this PR or should I create another pr for this issue?

2021-03-31 14:25 UTC, mikehardy commented
If you have already fixed it @Akshay0701 go ahead and add the commit here - it's still pending merge and the fix you mention if added as a separate commit should be easy to review + approve - thanks!

2021-03-31 14:42 UTC, Akshay0701 commented
Done
<img src="https://user-images.githubusercontent.com/52353967/113162914-50320000-925d-11eb-90bd-1c058039c53f.gif" width="250" height="500" />

2021-03-31 19:49 UTC, mikehardy approved these changes
Still looks good to me :-), thanks @Akshay0701 - merging now!

2021-03-31 19:50 UTC, merged