Highlight default selection in pickers
ankidroid/Anki-Android pull request #8292
Opened 2021-03-20 18:11 UTC by Abanoub-Asaad

## Purpose / Description
Highlight default selection in the pickers of note editor.
Related PRs: https://github.com/ankidroid/Anki-Android/pull/8171 and https://github.com/ankidroid/Anki-Android/pull/8174

## Fixes
Issue #7931

## Approach
`Before change` When the user was in note editor, there is a selector to change the type of note or card's deck, It was not highlighted.
`After change` Now, when the user selects something in this section, the background of the selected one will be highlighted by default to "light gray" color and the text color itself will be "black".

## How Has This Been Tested?
Tested by [Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&utm_source=www.apk4fun.com).

**Screenshots**
<div align="center">
<pre>
   <img alt="" width="30%" src="https://user-images.githubusercontent.com/48657780/111163716-0501c700-85a6-11eb-9bb5-7e86cffa7fff.jpeg">   <img alt="" width="30%" src="https://user-images.githubusercontent.com/48657780/111163722-0632f400-85a6-11eb-8327-8d4dd1a08489.jpeg">   <img alt="" width="30%" src="https://user-images.githubusercontent.com/48657780/111166210-8fe3c100-85a8-11eb-8be1-5558bf1858a0.jpeg"> 
     
</pre>
</div>

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

2021-03-20 19:12 UTC, mikehardy requested changes
Please follow the style guide for spacing https://github.com/ankidroid/Anki-Android/wiki/Code-style#white-spaces
Please edit PR to use specific format `Fixes #issuenumber` so that GitHub will crosslink them correctly

These are small things but I'll review for real after those are corrected

2021-03-21 07:46 UTC, david-allison-1 requested changes
Could you use `Fixes #7931`, not `Fixes Issue #7931`, as that links the PR and the issue together

2021-03-21 07:46 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> -            public void onItemSelected(AdapterView<?> parent, View view, int pos, long id) {
`setOnItemSelectedListener` no longer seems to be called

2021-03-21 07:46 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +                    tv.setBackgroundColor(Color.LTGRAY);
Could you extract the colors to a resource? Both here and for `noteDeckAdapter`?

This will allow future developers to change the styles in one place, without potential editing conflicts for the file, and allows us to define a consistent "selected" theme throughout the app.

2021-03-21 10:12 UTC, Abanoub-Asaad commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> -            public void onItemSelected(AdapterView<?> parent, View view, int pos, long id) {
Yes, this part isn't useful, so I've deleted it to make code cleaner. 
And also I've discussed this with another maintainer.

2021-03-21 10:14 UTC, Abanoub-Asaad commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +                    tv.setBackgroundColor(Color.LTGRAY);
I've extracted the colors.
Could you check the new commits? @david-allison-1

2021-03-21 11:16 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> -            public void onItemSelected(AdapterView<?> parent, View view, int pos, long id) {
Could you explain why it's not useful in the git commit message. I've had a quick scan and don't see any discussion.

2021-03-21 11:34 UTC, Abanoub-Asaad commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> -            public void onItemSelected(AdapterView<?> parent, View view, int pos, long id) {
The discussion was [here](https://github.com/ankidroid/Anki-Android/pull/8171#discussion_r592737772) in another related PR.

This method `onItemSelected(AdapterView<?> parent, View view, int position, long id)` is invoked when an item in this view has been selected. And I've already implemented that, but in a different way.  because when I've tried to use the exist method before, It doesn't work well.

2021-03-21 11:46 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> -            public void onItemSelected(AdapterView<?> parent, View view, int pos, long id) {
That discussion doesn't seem directly relevant to the code change.

I don't see why the previous method wouldn't work any more, could you explain?

This new method feels very unintuitive to me, I would presume that `getDropDownView` would be called for each view, and therefore `mCurrentDid` would be set to an incorrect value.

Are you certain that there aren't any other ways that `getDropDownView` could be called, aside from selecting a new item?

2021-03-21 13:28 UTC, Abanoub-Asaad commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> -            public void onItemSelected(AdapterView<?> parent, View view, int pos, long id) {
**Firstly**, I was facing  some problems with `getDropDownView` when I was trying to implement it in `onItemSelected` method in this part 
```java
mNoteDeckSpinner.setOnItemSelectedListener(new OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int pos, long id) {
                // Timber.i("NoteEditor:: onItemSelected() fired on mNoteDeckSpinner with pos = %d", pos);
                mCurrentDid = mAllDeckIds.get(pos);
            }

            @Override
            public void onNothingSelected(AdapterView<?> parent) {
                // Do Nothing
            }
        });
```
BTW I've searched a lot about how to implementing `getDropDownView` by another way, but I haven't reached a solution, so my solution was to remove this part and add a  new method to be able to make the highlight selection work by implementing `getDropDownView` as in the current commit.

**Secondly**, Could you tell me what's the importance of `mCurrentDid`, because I'm a little confused about this?

2021-03-21 19:53 UTC, Abanoub-Asaad commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> -            public void onItemSelected(AdapterView<?> parent, View view, int pos, long id) {
@david-allison-1 Sorry, I was confused about `mCurrentDid`, but I got your point.

2021-03-24 13:32 UTC, Ekagra requested changes
Use white places as: https://github.com/ankidroid/Anki-Android/wiki/Code-style#white-spaces

2021-03-24 14:02 UTC, Abanoub-Asaad commented
> Use white places as: https://github.com/ankidroid/Anki-Android/wiki/Code-style#white-spaces

In which part? because I'm using it.

2021-03-24 14:07 UTC, david-allison-1 reviewed
Looks good now! One nitpick and good to go

2021-03-24 14:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> -            public void onItemSelected(AdapterView<?> parent, View view, int pos, long id) {
`mCurrentDid` is the ID of the current deck.

This doesn't work. 

Could you re-instate the functionality? All you should need to do is un-delete these lines and remove setting `mCurrentDid` in the code that you added

2021-03-24 14:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +            public View getDropDownView(int position, View convertView, ViewGroup parent){
```suggestion
            public View getDropDownView(int position, View convertView, ViewGroup parent) {
```

2021-03-24 14:13 UTC, Abanoub-Asaad commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +            public View getDropDownView(int position, View convertView, ViewGroup parent){
Could you tell what's the problem here?

2021-03-24 14:17 UTC, david-allison-1 approved these changes
LGTM, thanks 👍

2021-03-24 17:18 UTC, mikehardy approved these changes
LGTM too thanks!

2021-03-24 17:18 UTC, merged

2021-04-05 18:32 UTC, mikehardy commented
Hi there!

Just a friendly notice (one per person for PRs merged in March, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for March 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

Thanks!