fixed:#8266:Unwanted else-if in DeckPicker removed.
ankidroid/Anki-Android pull request #8297
Opened 2021-03-20 20:13 UTC by haran2248

## Pull Request template

## Purpose / Description
fixed #8266.Remove unwanted code with browserDeckidFromDeckPicker

## Fixes
Fixes _Link to the issues._

fixed #8266

## Approach
_How does this change address the problem?_

The additional else-if has been removed

## How Has This Been Tested?

Runs on my device,Samsung SM-013F
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-20 20:14 UTC, haran2248 commented
@Arthur-Milchior 
![Arthur comments](https://user-images.githubusercontent.com/56928954/111884325-063c5500-89e7-11eb-9901-be7a1e021a8d.PNG)

2021-03-21 02:09 UTC, Arthur-Milchior commented
Thanks a lot fot looking for the two commits you screenshooted.

Generally speaking, I'd argue you should copy paste text instead of doing screenshot. Indeed:
* I can't do search in screenshot
* github would have transformed commit id to links. This would allow me to see the commit you mention. Currently, I can read comments but I have no idea what those comments are about. They are mostly useless if I can't see what change they relate to. 

Really, with just those messages, I get almost no information about what was going on, why and how it was used, why it is not anymore

Sadly, it also means that if someone come and read this commit, it'll also be hard to know why it was okay and not actually making a problem worse. After all, there probably was a reason why this code was here.


I investigated and my current understanding, that would be nice to have in the commit message is:

===============

NF: remove unused "browserDeckIdFromDeckPicker" parameter

As the name "browserDeckIdFromDeckPicker" indicates, this preference is supposed to be set in the deck picker, and put a global indication indicating which deck should be displayed in the card browser if it is opened by the deck picker.

More precisely, this preference was set if and only if the deck picker was opened with the request code `REQUEST_BROWSE_CARDS`. For some unknown reason, this request code is accepted by deck picker, and the deck picker do not even automatically open the card browser if it receives it. I suspect that this is a feature which was started to be implemented and never ended. Indeed, in the whole git history, DeckPicker was never opened with the request code `REQUEST_BROWSE_CARDS`. This seems to indicate also that:
* this code was never executed. Which is probably why it was never deleted since we never decided to stop using it.
* the code REQUEST_BROWSE_CARDS can be deleted from the code base.

=============

Note that we usually start by "NF:" to indicate that some commit is expected to be non functional. I.e. users should see no change at all in behavior.


I'm not entirely sure of what I wrote, but this is what I understand when I look at code history, and why I'm now confident that it is safe to delete this code. I'd love to know whether @mikehardy or @david-allison-1 have any thought here. (Ideally, we'd ask Tim, but it seems hard to imagine he'd remember what he expected to do in 2016 anyway. )

If I'm right, a second commit removing all uses of `REQUEST_BROWSE_CARDS` since it's not actually used.

2021-03-21 02:46 UTC, david-allison-1 commented
> * github would have transformed commit id to links.

`browserDeckIdFromDeckPicker` was introduced in 

https://github.com/ankidroid/Anki-Android/commit/f9883e71ae4e#diff-bc9854cf8afc1ab02dad530aa214fdd7d2d9b3e35352bc63d2eb822861912f6dR678-R1711 

and removed in 

https://github.com/ankidroid/Anki-Android/commit/74b3dd493227516420862f2abf793b47ddf8c571#diff-bc9854cf8afc1ab02dad530aa214fdd7d2d9b3e35352bc63d2eb822861912f6dL1883-L1892

> More precisely, this preference was set if and only if the deck picker was opened with the request code `REQUEST_BROWSE_CARDS`. etc...

This is processed in `onActivityResult`, this means this was the result when `DeckPicker` launched `CardBrowser` via `REQUEST_BROWSE_CARDS`. The code worked previously, this may change your view.

> If I'm right, a second commit removing all uses of REQUEST_BROWSE_CARDS since it's not actually used.

Optional - it's useful to distinguish how a activity was opened, I feel it still has (minor) value, but this isn't a strong opinion.

2021-03-21 02:55 UTC, david-allison-1 requested changes
I'm happy with the code

* We need to explain this thought process about removing the code (including commit refs) in the commit message
* The commit title is too long: `You have a descriptive commit message with a short title (first line, max 50 chars).` - currently 52. 

Suggestion: 

```
refactor[DeckPicker]: unused CardBrowser result

Fixes #8266

TODO - explain thought process in detail here, ensure you use the strings REQUEST_BROWSE_CARDS and browserDeckIdFromDeckPicker so future users can grep for this.
```

2021-03-21 03:35 UTC, Arthur-Milchior commented
> > More precisely, this preference was set if and only if the deck picker was opened with the request code `REQUEST_BROWSE_CARDS`. etc...
> 
> This is processed in `onActivityResult`, this means this was the result when `DeckPicker` launched `CardBrowser` via `REQUEST_BROWSE_CARDS`. The code worked previously, this may change your view.

Thank you a lot . I missed the "result" part. Makes far more sens now.
The message should be rewritten. It's still valid to remove "browserDeckIdFromDeckPicker" but not for the reason I thought.

> 
> > If I'm right, a second commit removing all uses of REQUEST_BROWSE_CARDS since it's not actually used.
> 
> Optional - it's useful to distinguish how a activity was opened, I feel it still has (minor) value, but this isn't a strong opinion.

The trouble is that it uses a deprecated function. 
Most troubling is that the function was deprecated in 1c4455c21265ee17e0795c62f5d88e2003e964f9 where it was added. And I don't see any reason for it to be deprecated and the text do not explain why. I'll create an issue to track this

2021-03-21 04:16 UTC, david-allison-1 commented
> The trouble is that it uses a deprecated function.
> Most troubling is that the function was deprecated in [1c4455c](https://github.com/ankidroid/Anki-Android/commit/1c4455c21265ee17e0795c62f5d88e2003e964f9) where it was added. And I don't see any reason for it to be deprecated and the text do not explain why. I'll create an issue to track this

Replied: https://github.com/ankidroid/Anki-Android/issues/8293#issuecomment-803509395 - likely just animations - I'm fine with this going in as-is and dealing with the deprecation later.

2021-03-21 05:31 UTC, haran2248 commented
> I'm happy with the code
> 
> * We need to explain this thought process about removing the code (including commit refs) in the commit message
> * The commit title is too long: `You have a descriptive commit message with a short title (first line, max 50 chars).` - currently 52.
> 
> Suggestion:
> 
> ```
> refactor[DeckPicker]: unused CardBrowser result
> 
> Fixes #8266
> 
> TODO - explain thought process in detail here, 80 chars per line
> ensure you use the strings REQUEST_BROWSE_CARDS and browserDeckIdFromDeckPicker
> so future users can grep for this.
> ```

Thank you.Ill work on this

2021-03-21 05:58 UTC, haran2248 commented
Is it ok now?

2021-03-21 06:06 UTC, david-allison-1 commented
> Is it ok now?

The title is. Could you also add a description explaining the change underneath the title

2021-03-21 06:29 UTC, haran2248 commented
Is that fine?

2021-03-21 06:43 UTC, david-allison-1 commented
I still don't see anything in the commit message: https://github.com/ankidroid/Anki-Android/pull/8297/commits/a9ce2269cf468eab119669f90eb944eaf8010b3d

2021-03-21 07:09 UTC, haran2248 commented
> I still don't see anything in the commit message: [a9ce226](https://github.com/ankidroid/Anki-Android/commit/a9ce2269cf468eab119669f90eb944eaf8010b3d)

Did you want me to comment on my commit message?

2021-03-21 07:13 UTC, david-allison-1 commented
> > I still don't see anything in the commit message: [a9ce226](https://github.com/ankidroid/Anki-Android/commit/a9ce2269cf468eab119669f90eb944eaf8010b3d)
> 
> Did you want me to comment on my commit message?I dont clearly get what you want me to do.I have commented about the changes in the commit message.Is that ok?

This post should help 

https://chris.beams.io/posts/git-commit/

A git commit message typically has 

* a title (50 chars)
* an optional body (we use 80 chars per line)

The body should explain the change in more detail, so a developer can see why a change was made

2021-03-21 07:20 UTC, haran2248 commented
> > > I still don't see anything in the commit message: [a9ce226](https://github.com/ankidroid/Anki-Android/commit/a9ce2269cf468eab119669f90eb944eaf8010b3d)
> > 
> > 
> > Did you want me to comment on my commit message?I dont clearly get what you want me to do.I have commented about the changes in the commit message.Is that ok?
> 
> This post should help
> 
> https://chris.beams.io/posts/git-commit/
> 
> A git commit message typically has
> 
> * a title (50 chars)
> * an optional body (we use 80 chars per line)
> 
> The body should explain the change in more detail, so a developer can see why a change was made

Ill work on this

2021-03-21 10:15 UTC, haran2248 commented
Can you see if it is ok?

2021-03-21 11:36 UTC, david-allison-1 commented
One of the 3 commits is nearly there.

* Could you squash the 3 commits together

Your current message is:
```
NF:remove unused browserDeckIdFromDeckPicker

refactor:[Unused card browser result]
fixes:8266
TODO:REQUEST_BROWSE_CARDS and browserDeckIDFromDeckPicker are no longer used as it is deprecated
```

You want something along the lines of:

```
refactor[DeckPicker]: unused CardBrowser result

Fixes #8266

browserDeckIdFromDeckPicker was added in f9883e7 and had usages removed 
in 74b3dd4, but the variable was still set in onActivityResult

We keep variable: REQUEST_BROWSE_CARDS for now to distinguish between 
methods of opening the card browser.
```

This would give a developer enough context to quickly understand why a change occurred, and the surrounding context.

2021-03-21 21:41 UTC, haran2248 commented
Is this fine?

2021-03-22 12:19 UTC, Arthur-Milchior approved these changes

2021-03-22 12:20 UTC, Arthur-Milchior commented
Fine

Flaky test, I restarted them and should be able to merge soon. Thanks a lot for making so many changes

2021-03-22 17:55 UTC, david-allison-1 approved these changes
Looks good to me, thanks!

2021-03-22 18:18 UTC, merged

2021-04-05 18:31 UTC, mikehardy commented
Hi there!

Just a friendly notice (one per person for PRs merged in March, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for March 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

Thanks!