Fix:8142 Adding Webview information to crash report
ankidroid/Anki-Android pull request #8301
Opened 2021-03-21 10:22 UTC by kartikeysaran

## Purpose / Description
Added webview information to ACRA crash reports with the help of package manager

## Fixes
Fixes #8142 

## Approach
Adding a custom field to ACRA report which send the Webview version name and code with the help of Package Manager

## How Has This Been Tested?

This has been tested locally

## Learning (optional, can help others)
Adding custom field to ACRA reports

https://stackoverflow.com/questions/34338262/acra-sending-a-custom-data-reportfield

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2021-03-21 10:25 UTC, kartikeysaran commented
@mikehardy I have closed the previour pr linked to the issue #8225 due to some wrong commits previously , I was using UserAgent String to fetch Webview Information but that was not handy as we need to pass a Webview parameter to that to fetch the data and we need to include the Webview information to ACRA crash report so for that i have used Package manager .

2021-03-21 14:35 UTC, 4shutosh commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +                return webViewInfo;
Common statements can be extracted from the if-else.

2021-03-21 14:38 UTC, 4shutosh commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +                webViewInfo = "Webview version name - "+pi.versionName+" , version Code - "+pi.versionCode;
Fix code formatting. 
Add proper spaces before and after symbols.

2021-03-24 18:05 UTC, mikehardy requested changes
@4shutosh is correct in this case @kartikeysaran - I made a suggestion based on that and I think it's a lot cleaner? What do you think?

2021-03-24 18:05 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +            }
```suggestion
            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
                pi = WebView.getCurrentWebViewPackage();
            } else {
                pi = packageManager.getPackageInfo("com.google.android.webview", 0);
            }
            return "Webview version name - " + pi.versionName + " , version Code - " + pi.versionCode ;
```

2021-03-24 18:08 UTC, david-allison-1 requested changes
Also got a test failure:

```
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:724: warning: [deprecation] versionCode in PackageInfo has been deprecated

                webViewInfo = "Webview version name - " + pi.versionName + " , version Code - " + pi.versionCode ;
> Task :AnkiDroid:compileDebugJavaWithJavac
                                                                                                    ^
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:728: warning: [deprecation] versionCode in PackageInfo has been deprecated
                webViewInfo = "Webview version name - " + pi.versionName + " , version Code - " + pi.versionCode ;
                                                                                                    ^
```

2021-03-25 01:58 UTC, kartikeysaran commented
> Also got a CI failure:
> 
> ```
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:724: warning: [deprecation] versionCode in PackageInfo has been deprecated
> 
>                 webViewInfo = "Webview version name - " + pi.versionName + " , version Code - " + pi.versionCode ;
> > Task :AnkiDroid:compileDebugJavaWithJavac
>                                                                                                     ^
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:728: warning: [deprecation] versionCode in PackageInfo has been deprecated
>                 webViewInfo = "Webview version name - " + pi.versionName + " , version Code - " + pi.versionCode ;
>                                                                                                     ^
> ```
> 
> Use [PackageInfoCompat.getLongVersionCode](https://developer.android.com/reference/androidx/core/content/pm/PackageInfoCompat)

Will update the code

2021-03-25 03:41 UTC, kartikeysaran commented
> @4shutosh is correct in this case @kartikeysaran - I made a suggestion based on that and I think it's a lot cleaner? What do you think?

Yeah it is more clean now , have pushed the code

2021-03-25 07:27 UTC, david-allison-1 requested changes
Thanks!! Almost there

2021-03-25 07:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        ACRA.getErrorReporter().putCustomData("WEBVIEW_INFORMATION",fetchWebViewInformation());
We'd make this data machine-readable if we had two fields: `WEBVIEW_VER_NAME` and `WEBVIEW_VER_CODE`.

2021-03-25 07:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +    private String fetchWebViewInformation () {
```suggestion
    private String fetchWebViewInformation() {
```

2021-03-25 07:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        ACRA.getErrorReporter().putCustomData("WEBVIEW_INFORMATION",fetchWebViewInformation());
```suggestion
        ACRA.getErrorReporter().putCustomData("WEBVIEW_INFORMATION", fetchWebViewInformation());
```

2021-03-25 07:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +            return e.getMessage();
I don't think we want the full stack trace here.

We definitely want a `Timber.w`

We likely can't send a crash report here, as we're in the ACRA setup

2021-03-25 07:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +            return "Webview version name - " + pi.versionName + " , version Code - " + PackageInfoCompat.getLongVersionCode(pi) ;
```suggestion
            return "Webview version name - " + pi.versionName + " , version Code - " + PackageInfoCompat.getLongVersionCode(pi);
```

2021-03-25 07:29 UTC, david-allison-1 requested changes
Lint error:

```
  /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:724: Error: Consider using WebViewCompat.getCurrentWebViewPackage instead which will support more devices. [WebViewApiAvailability]
                  pi = WebView.getCurrentWebViewPackage();
```

2021-03-25 08:31 UTC, david-allison-1 requested changes

2021-03-25 08:31 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +            webViewInfo.add(0,pi.versionName);
```suggestion
            webViewInfo.add(0, pi.versionName);
```

2021-03-25 08:31 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +            webViewInfo.add(1,String.valueOf(PackageInfoCompat.getLongVersionCode(pi)));
```suggestion
            webViewInfo.add(1, String.valueOf(PackageInfoCompat.getLongVersionCode(pi)));
```

2021-03-25 08:31 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +            Timber.w( e );
```suggestion
            Timber.w(e);
```

2021-03-25 08:31 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        ACRA.getErrorReporter().putCustomData("WEBVIEW_VER_CODE", fetchWebViewInformation().get(1));
You'd be better with two functions, returning a class or setting default values. 

This will crash if an exception is thrown

2021-03-25 08:34 UTC, kartikeysaran commented
@david-allison-1 @mikehardy Sorry for not following the code format will take care of it in future

2021-03-25 08:46 UTC, david-allison-1 commented
> @david-allison-1 @mikehardy Sorry for not following the code format will take care of it in future

No worries! We'll later want to move to a point where this is automated

2021-03-25 08:48 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +        ACRA.getErrorReporter().putCustomData("WEBVIEW_VER_CODE", fetchWebViewInformation().get(1));
rather than creating two separate functions i have used hashmaps that would work even when if there is an exception

2021-03-25 09:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +            webViewInfo.put("WEBVIEW_VER_NAME", "");
Set these before the catch while creating the `HashMap`. If `PackageInfoCompat.getLongVersionCode(pi)` fails, then this would remove the value of `pi.versionName`

2021-03-25 09:22 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
> +            webViewInfo.put("WEBVIEW_VER_NAME", "");
Okay

2021-03-25 09:38 UTC, david-allison-1 approved these changes
Looks good to me, thanks

Note to maintainers: squash & merge

2021-03-25 09:40 UTC, david-allison-1 commented
Actually... could you confirm that this works on our test ACRA instance: 

https://918f7f55-f238-436c-b34f-c8b5f1331fe5-bluemix.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/

2021-03-27 08:45 UTC, kartikeysaran commented
> Actually... could you confirm that this works on our test ACRA instance:
> 
> https://918f7f55-f238-436c-b34f-c8b5f1331fe5-bluemix.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/

Yes it does ! :) , send a crash report recently with webview information

2021-03-27 08:50 UTC, david-allison-1 approved these changes
Looks good to me then!

2021-03-27 14:38 UTC, mikehardy approved these changes
nice!

2021-03-27 14:39 UTC, merged