Implemented Search Deck Feature In Add Note Activity
ankidroid/Anki-Android pull request #8317
Opened 2021-03-22 13:37 UTC by Akshay0701

Fixes #8276

## Problem
With Current Spinner in add note activity user can select any deck , but
->If number of decks is very big it will be hard for user to search particular deck in spinner .
->Anki-desktop do have this feature.

## Work done till now:
1 Used `DeckSelectionDialog` class to implement search dialog.

## Output
<img src="https://user-images.githubusercontent.com/52353967/111996504-174ca980-8b40-11eb-9e30-81b9548f7960.gif" width="250" height="500" />

2021-03-23 01:16 UTC, david-allison-1 requested changes
Code looks great, tests pass and I've tested on my phone. Thanks!

* Handles long deck names well (both the dialog, and the "deck" shows all the value
* "Ctrl+D" still works

There are some visual issues that we'll need to discuss.

* It would be ideal to keep the same visual style as the above listbox, there is inconsistency visually
* "Restore Default" doesn't make sense here - might as well remove it
* The text content for the dialog takes up room vertically and is am empty string - should be removed

![image](https://user-images.githubusercontent.com/62114487/112077746-05d1c480-8b75-11eb-8393-bc1b0cec33f2.png)

Further extension (new issue, if agreed): if a keyboard is attached, it'd be great to filter the text via typing without needing to go to the filter option

2021-03-23 01:16 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +                    displayDeckOverrideDialog(getCol());
This still works 👍

2021-03-23 01:16 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/note_editor.xml
> +                            android:id="@+id/DeckEditorCardsButton"
Code Style: [XML elements identifiers must be all lowercase using underscore to separate words](https://github.com/ankidroid/Anki-Android/wiki/Code-style#xml-elements-identifiers-must-be-all-lowercase-using-underscore-to-separate-words)

2021-03-23 01:16 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/note_editor.xml
> +                                android:layout_marginLeft="5dip"
ideally use `layout_marginStart` and `layout_marginEnd`

2021-03-23 03:10 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> -        noteDeckAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
so should revert all deleted spinner code ?

2021-03-23 03:42 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> -        noteDeckAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
I'm unsure about the correct approach to take here, but we need a consistent UI or we'll get complaints

It might be best to extend the control, it might be best to recreate it. 

I don't know which, would trust either as a solution.

2021-03-23 03:48 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> -        noteDeckAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
can i change type-spinner into same deckdialog box ?, then it would look consistent UI .

2021-03-23 06:28 UTC, Akshay0701 commented
### Things changed in last commit :
1 handled nullable summary object in `DeckSelectionDialog`
2 changed type list-box style
3 changed xml ids and fixes spaces

## Output
<img src="https://user-images.githubusercontent.com/52353967/112102541-6f31f180-8bce-11eb-9930-68750eeae8a7.jpg" width="250" height="500" />

2021-03-23 06:40 UTC, Akshay0701 commented
and sorry for spaces issue ,I always make spaces issue in my each pr :( , i will try to code with anki code style.

2021-03-23 09:46 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> -        noteDeckAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
sorry to ask you again david ,but i don't understand where we used above code, and why we require this code ,if we removed whole spinner ?

2021-03-26 11:27 UTC, david-allison-1 commented
Could we keep the UI as it was before (selected item + drop down indicator) without the grey background

2021-03-26 11:32 UTC, Akshay0701 commented
yes we can , for that we have to keep spinner as it is , and we only have to change onClick function, i got you david , i will make chances soon

2021-03-26 16:11 UTC, Akshay0701 commented
<img src="https://user-images.githubusercontent.com/52353967/112660724-c14b6f00-8e7b-11eb-991d-28b1d27257d6.jpg" width="250" height="500" />----<img src="https://user-images.githubusercontent.com/52353967/112660726-c27c9c00-8e7b-11eb-855f-c767854e3af5.jpg" width="250" height="500" />

2021-03-26 22:17 UTC, david-allison-1 commented
This doesn't compile on my machine, so I couldn't test it

```
C:\GitHub\Anki-Android-Git\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\NoteEditor.java:609: error: cannot find symbol
        mNoteDeckLayout = findViewById(R.id.note_deck_layout);
                                           ^
  symbol:   variable note_deck_layout
  location: class id
```

Could you also rebase onto master to fix the conflict

2021-03-27 10:15 UTC, Akshay0701 commented
![Capture](https://user-images.githubusercontent.com/52353967/112717511-4b92e200-8f13-11eb-99bc-bb7bf6f4bf26.PNG)
when i rebase with master branch this error i get , what should i do ?

2021-03-27 11:01 UTC, david-allison-1 commented
> ![Capture](https://user-images.githubusercontent.com/52353967/112717511-4b92e200-8f13-11eb-99bc-bb7bf6f4bf26.PNG)
> when i rebase with master branch this error i get , what should i do ?

There was a conflict with https://github.com/ankidroid/Anki-Android/pull/8341

Look at the diff, and you'll see the changes that you'll need to make to resolve it.

2021-03-27 11:04 UTC, david-allison-1 commented
There was a conflicting change, if a merge conflict didn't occur:

* Android Studio - Right click the sidebar - annotate
* Find the commit: 3de33abda7a436ef8c71bcf03c78fda497d78ce2
* Find the PR: https://github.com/ankidroid/Anki-Android/pull/8335
* Find the diff: https://github.com/ankidroid/Anki-Android/pull/8335/files
* From the diff, work out the changes that you'll need to make

2021-03-31 12:02 UTC, closed without merging