Implement Create New Deck Function In Add Note Activity
ankidroid/Anki-Android pull request #8330
Opened 2021-03-24 13:45 UTC by Akshay0701

## Problem
With Current Spinner in add note activity user can select any deck , but
1 if user don't found particular deck in list then user have to go back to main activity to create that deck and then user have to create note and select that particular deck , it is lengthy process.

## Solution
We can implement add new create deck function at top left corner of `DeckSelectionDialog` box,so that if any user don't found deck , then user can directly create new deck from there without aborting whole process to create new deck.

## Fixes
Fixes #8275 

## Output 
<img src="https://user-images.githubusercontent.com/52353967/112320127-bb675980-8cd4-11eb-8eec-cfc9e42fb61c.gif" width="250" height="500" />------<img src="https://user-images.githubusercontent.com/52353967/112320120-ba362c80-8cd4-11eb-8714-bcd9666f5c24.gif" width="250" height="500" />
1 Add Deck Video
2 Add Sub Deck Video

2021-03-24 13:57 UTC, david-allison-1 requested changes
Looks good!

Blocked on a dependency before merging

* Can we have the "Add Deck" be an optional function - I think it would be useful with all the current use cases, but it may not be in the future

2021-03-24 13:57 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
> +        MenuItem add_Decks = mToolbar.getMenu().findItem(R.id.deck_picker_dialog_action_add_deck);
naming: `addDecks` (see Code Style)

2021-03-24 13:57 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
> +        EditText mDialogEditText = new FixedEditText(requireActivity());
`dialogEditText` or `editText`

2021-03-24 13:57 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
> +                        if (!creation_succeed) {
I think you'll want to show a Toast here - currently returning is the same as the "success" path

2021-03-24 13:57 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
> +                        boolean creation_succeed = createNewDeck(deckName);
`creationSucceeded`

2021-03-24 13:57 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
> +    private boolean createNewDeck(String deckName) {
What happens if a duplicate deck is added?

2021-03-24 13:57 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
> +                        addDeckDialog(ctv.getText().toString()+"::");
spacing around the "+"

2021-03-24 13:57 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
> +                        //creating sub deck with parent deck path
nit: add a space before the comment text

2021-03-24 13:57 UTC, david-allison-1 commented on AnkiDroid/src/main/res/menu/deck_picker_dialog_menu.xml
> +        android:title="Add deck"
Extract to resouce

2021-03-27 11:00 UTC, david-allison-1 reviewed
Just a warning: try to avoid merge commits in the history - we don't use them and they add complexity to rebasing the change.

This will now be hard for people to review if they're not reviewing commits

2021-03-27 11:00 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
> +                            UIUtils.showThemedToast(requireActivity(), "Failed to create deck", false);
Needs to be extracted to resources: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#adding-translations

2021-03-27 11:00 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
>              Long id = new AnkiActivity().getCol().getDecks().id(deckName);
nit: Can move this inside the if as well

2021-03-27 11:00 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
>          Timber.i("DeckPicker:: Creating new deck...");
Can you add to the documentation what "succeeded" means - and check the callers are handling this correctly, if nothing happens, did the operation succeed?

2021-03-27 11:00 UTC, david-allison-1 commented on AnkiDroid/src/main/res/menu/deck_picker_dialog_menu.xml
> +        android:title="@string/deck_conf_add"
Or add a new string if "add deck" makes more sense
```suggestion
        android:title="@string/menu_add"
```

2021-03-27 11:07 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
>          Timber.i("DeckPicker:: Creating new deck...");
> Succeeded means deck has been created without issue
> Deck will not create if deckName is already present in list
is this documentation right ?

2021-03-27 11:15 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
>          Timber.i("DeckPicker:: Creating new deck...");
As a developer, if I call the method, I want to know what will happen in the doccomment. 

You can define "Succeeded" to mean anything: 

* "there wasn't an error, and the deck will exist" (seems like a good choice)
* The deck was created, otherwise, false

But it needs to be consistent with the code. Callers need this detail to understand how to use the method

2021-03-27 11:16 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
> +                            UIUtils.showThemedToast(requireActivity(), "Failed to create deck", false);
do i need to add this string to all translation resources file ?

2021-04-01 22:07 UTC, david-allison-1 commented
@Akshay0701 this should be good to be looked at now, ping me when it's rebased and ready for a re-review

2021-04-02 18:09 UTC, closed without merging