Fixes #7013 Fixed deprecated NetworkInfo
ankidroid/Anki-Android pull request #8331
Opened 2021-03-24 14:06 UTC by mrudultora

## Purpose / Description
Fixed the deprecated NetworkInfo as it was deprecated.

## Fixes
Fixes #7013

## Approach
By using different methods in APIs greater than or equal to 23.

## How Has This Been Tested?
Tested on real device (Redmi Note 7S and API 29).

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-24 18:13 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.java
> +    @SuppressWarnings("deprecation")
Can we remove this now?

2021-03-24 18:16 UTC, mikehardy requested changes
I think these needs some more detail work per my comments but I *definitely* appreciate the effort - cleaning up deprecation is something users never really think about but they do appreciate that the app keeps running over decade(s)...

2021-03-24 18:16 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.java
> -        if (cm != null) {
Now that we have multiple conditionals requiring a non-null ConnectionManager, I'd prefer the first check to be a quick-return to simplify the future conditionals and make the code easier to reason about

```java
if (cm == null) {
    // we can't do anything with out a ConnectionManager
    return false;
}

2021-03-24 18:16 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.java
> +                    || networkCapabilities.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR));
I don't understand this part. Why do we care if it is WIFI or CELLULAR specifically? Why isn't BLUETOOTH okay?

I think what we really care about is INTERNET https://developer.android.com/reference/android/net/NetworkCapabilities#NET_CAPABILITY_INTERNET ?

2021-03-24 18:16 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.java
> +                    || networkCapabilities.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR));
Here is how the most popular react-native network information package handles it, some neat tricks in here:

https://github.com/react-native-netinfo/react-native-netinfo/blob/371acf957cb25275395a268fd61a285e60a01acf/android/src/main/java/com/reactnativecommunity/netinfo/NetworkCallbackConnectivityReceiver.java#L83-L105

2021-03-24 18:16 UTC, mrudultora commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.java
> +    @SuppressWarnings("deprecation")
No. Because I tried to remove this and then the build failed. It was not letting me to import `android.net.NetworkInfo`. I was getting a **-Werror**.

2021-03-24 18:17 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/async/Connection.java
> +    @SuppressWarnings("deprecation")
No unfortunately, there is no way to avoid touching deprecated APIs until minSdkVersion moves up past the point where they're needed

2021-03-26 07:57 UTC, mrudultora commented
Changes done !

2021-03-29 13:05 UTC, mikehardy approved these changes
Looks good to me thanks!

2021-03-29 13:06 UTC, merged