TalkBack Accessibility Improvement Umbrella Tracker #7913
ankidroid/Anki-Android pull request #8332
Opened 2021-03-24 15:53 UTC by jindalshiva

## Pull Request template

## Purpose / Description
_When the user enable TalkBack, then there were some issues with the UI of the app._

## Fixes
Fixes _https://github.com/ankidroid/Anki-Android/issues/7913_

## Approach
_I had to make changes in the XML files of the app, make some graphics and buttons of the app focusable_

## How Has This Been Tested?

Test this app by running this updated code, on your physical devices or emulator and also enable TalkBack on the device.

## Learning (optional, can help others)
_Started by learning about TalkBack. After this, I started making some changes to it._

_https://support.google.com/accessibility/android/answer/6283677?hl=en_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-26 23:57 UTC, david-allison-1 submitted a review, later dismissed
I can't tap cards in the card browser after checking out this change

2021-03-27 11:05 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                        android:paddingRight="40dp"/>
Typically we want `paddingEnd` to ensure that right-to-left layouts handle the padding correctly.

2021-03-27 11:07 UTC, jindalshiva commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                        android:paddingRight="40dp"/>
You want paddingEnd instead of paddingRight.

2021-03-27 11:34 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                        android:paddingRight="40dp"/>
If it makes sense in this context, then yes

2021-03-31 07:50 UTC, jindalshiva commented on AnkiDroid/src/main/res/layout/my_account.xml
> +                        android:paddingRight="40dp"/>
Hi @david-allison-1, just check, I have updated the code.

2021-03-31 07:51 UTC, jindalshiva commented
> I can't tap cards in the card browser after checking out this change

Hi @david-allison-1, now you can tap on cards in the card browser.

2021-04-01 16:36 UTC, david-allison-1 requested changes
This doesn't compile, CI is failing:

```
* What went wrong:
Execution failed for task ':AnkiDroid:mergeDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource compilation failed
     /Users/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/layout/deck_item.xml:36: AAPT: error: not well-formed (invalid token).
         
     /Users/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/layout/deck_item.xml: AAPT: error: file failed to compile.
```

2021-04-06 18:59 UTC, mikehardy commented
This PR is in a strange state from a GitHub perspective, I have no idea why the automated CI checks did not run 😅  - and it does not appear that I can cause them to run right now! Really strange. I would bet that adding some trivial change (like maybe a commit that added a comment, and then a second one that removed it - *just to force github to see it updated*) would cause the CI actions to run, otherwise I'm not sure what the best path forward is (open a new PR with the same commits perhaps? reviewer pull the branch locally and run `./gradlew clean jacocoTestReport lintRelease` ?). 

I don't see a recent incident https://www.githubstatus.com/history so I'm not sure what happened...

2021-04-08 14:56 UTC, vinishhub commented on AnkiDroid/src/main/res/layout/card_item_browser.xml
> +</LinearLayout>
here it shows changes due to line ending differences.

2021-04-08 14:58 UTC, vinishhub commented on AnkiDroid/src/main/res/layout/night_mode_switch.xml
>  </LinearLayout>
here also the  line ending differences. you've must added a new line after this

2021-08-13 23:37 UTC, closed without merging