Custom study
ankidroid/Anki-Android pull request #8338
Opened 2021-03-25 11:16 UTC by 4D17Y4

## Purpose / Description
Removed increase new card limit when no new cards

## Fixes
Fixes #4759

## Approach
Added a condition check to check if there are no new cards.

## How Has This Been Tested?

Tested on Nokia 6.1+ (physical) , android 10 stock version.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-25 12:07 UTC, david-allison-1 requested changes
Thanks!!! 

(optional): A unit test here would be great

Could you change the pull request title to something that makes sense without context of the change

2021-03-25 12:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
> +                if (col.getSched().newCount()==0) {
This would be more maintainable if you generate the list, and then remove the element based on a condition, this means both lists don't need to be kept in sync by a developer

2021-03-25 12:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
> +                if (col.getSched().newCount()==0) {
```suggestion
                if (col.getSched().newCount() == 0) {
```

2021-03-25 12:12 UTC, 4D17Y4 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
> +                if (col.getSched().newCount()==0) {
Sure I'll switch.
I am planning on making a new temporary array and copying the content after checking for the condition.
Any changes ?

2021-03-25 12:12 UTC, 4D17Y4 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
> +                if (col.getSched().newCount()==0) {
I'll fix it,
thanks for review.

2021-03-25 12:13 UTC, 4D17Y4 commented
@david-allison-1  should I be worried about the failing checks, though I've looked into it and they doesn't seem relevant here.

2021-03-25 12:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
> +                if (col.getSched().newCount()==0) {
Use an `ArrayList` rather than an array, as it makes removal easier. Convert to an array when you return it.

2021-03-25 12:33 UTC, david-allison-1 commented
> @david-allison-1 should I be worried about the failing checks, though I've looked into it and they doesn't seem relevant here.

Yeah, you're fine, we moved our CI from Travis to GitHub which has made the tests much more flaky. We're snowed under with all the new contributors right now, but we will be getting CI back up to 100% soon.

2021-03-25 13:06 UTC, 4D17Y4 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
> +                if (col.getSched().newCount()==0) {
Done, Thanks

2021-03-29 19:41 UTC, 4D17Y4 commented
Hey @david-allison-1 ,
In the Regression test, 
Should I be comparing the list in dialog or just validating the count is sufficient ?

2021-03-29 19:47 UTC, david-allison-1 reviewed
RE: Your question -  ideally verifying that the item isn't present

For a mock, whatever is easiest to read and will return a count of 0.

Aim for less coupling, but it doesn't need to be perfect

2021-03-29 19:47 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
> +                dialogOptions.remove(Integer.valueOf(DECK_OPTIONS));
Sorry to be annoying, I meant an `ArrayList` in this case statement, I think we lose maintainability by having a list for the entire function

2021-03-29 19:47 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
> +        int [] list = new int[dialogOptions.size()];
We have a function: `integerListToArray`

2021-03-29 19:51 UTC, 4D17Y4 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
> +                dialogOptions.remove(Integer.valueOf(DECK_OPTIONS));
This solves it, I was thinking as I changed list for whole function I should check for all cases.
I'll make the requested changes.
Thanks.

2021-03-29 21:00 UTC, 4D17Y4 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
> +        int [] list = new int[dialogOptions.size()];
done.

2021-03-29 21:02 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java
> +            assertThat(dialog.getItems(), Matchers.not(Matchers.hasItem("Modify today’s new card limit")));
Use the string for `R.string.custom_study_increase_new_limit`, and ensure that the test is running under English - therefore translation updates won't cause problems with the test

```java
    @Config(qualifiers = "en")
```

2021-03-29 21:02 UTC, david-allison-1 reviewed
Really clean, one note in the test and good to go. Thanks so much!!

2021-03-29 21:12 UTC, 4D17Y4 commented
Done ;)

2021-03-29 21:28 UTC, david-allison-1 approved these changes
Great! Thanks for the quick fixes, code's really clean, thank you!

2021-03-29 21:28 UTC, david-allison-1 commented
```

com.ichi2.anki.dialogs.CustomStudyDialogTest > increaseNewCardLimitRegressionTest FAILED
    java.lang.NullPointerException
        at com.ichi2.libanki.Decks.select(Decks.java:1081)
        at com.ichi2.anki.dialogs.CustomStudyDialog.onCreateDialog(CustomStudyDialog.java:114)
        at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:648)
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:562)
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1654)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
        at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:305)
        at androidx.fragment.app.testing.FragmentScenario$Companion$internalLaunch$2.perform(FragmentScenario.kt:618)
        at androidx.fragment.app.testing.FragmentScenario$Companion$internalLaunch$2.perform(FragmentScenario.kt:401)
        at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$ActivityScenario(ActivityScenario.java:660)
        at androidx.test.core.app.ActivityScenario$$Lambda$4.run(Unknown Source)
        at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:670)
        at androidx.fragment.app.testing.FragmentScenario$Companion.internalLaunch$fragment_testing_release(FragmentScenario.kt:592)
        at androidx.fragment.app.testing.FragmentScenario$Companion.launch(FragmentScenario.kt:477)
        at androidx.fragment.app.testing.FragmentScenario$Companion.launch$default(FragmentScenario.kt:476)
        at androidx.fragment.app.testing.FragmentScenario.launch(FragmentScenario.kt)
        at com.ichi2.anki.dialogs.CustomStudyDialogTest.getDialogScenario(CustomStudyDialogTest.java:96)
        at com.ichi2.anki.dialogs.CustomStudyDialogTest.increaseNewCardLimitRegressionTest(CustomStudyDialogTest.java:8
```

2021-03-29 22:34 UTC, 4D17Y4 commented
I'll fix it in some time.

2021-03-29 22:40 UTC, david-allison-1 commented
> I'll fix it in some time.

No rush, you should also be able to check the tests on your local machine, or enable GitHub actions on your fork

2021-03-30 17:08 UTC, 4D17Y4 commented
Hey @david-allison-1 ,
I might need your help here im getting the same error on running regression test as in #8064 on my local machine, tried so hard to figure out why im getting this error but no success. Due to the same reason I'm unable to debug this regression test ;(

2021-03-30 20:06 UTC, david-allison-1 commented
A flaky test is something that we need to rerun, Apologies, we moved to GitHub actions recently, and the test runners are much more problematic than our old ones. We do have a PR in which should fix these, but it'll take time to get over the finish line

2021-03-30 20:32 UTC, david-allison-1 commented
Okay, this is a failure. The first stage is to run the test under the debugger and set breakpoints to see where the problem lies.

2021-03-30 22:52 UTC, david-allison-1 commented
I've had a look into this.

Getting this test to work will require rearchitecting the class to use `FragmentFactory`, after this, we can use `FragmentScenario` without needing to override `getAnkiActivity()`

Could you add `@Ignore("#8406")` to the test, and let's get this in

2021-03-30 22:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
> +    @VisibleForTesting
And revert these `@VisibleForTesting` changes - shouldn't be necessary.

2021-03-31 09:56 UTC, 4D17Y4 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
> +    @VisibleForTesting
Done

2021-03-31 09:57 UTC, 4D17Y4 commented
Thanks @david-allison-1 ; )

2021-04-01 15:23 UTC, david-allison-1 approved these changes
Looks good to me, thanks! Maintainers: squash & merge

2021-04-01 22:26 UTC, mikehardy requested changes
LGTM - I read the note about the fragment testing difficulties, it's tracked nicely

My comments are all nitpicks then - just spacing. I'll commit them in a batch then squash+merge

2021-04-01 22:26 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java
> +        CustomStudyDialog standard = CustomStudyDialog.newInstance(CustomStudyDialog.CONTEXT_MENU_STANDARD,1);
```suggestion
        CustomStudyDialog standard = CustomStudyDialog.newInstance(CustomStudyDialog.CONTEXT_MENU_STANDARD, 1);
```

2021-04-01 22:26 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java
> +        scenarioStandard.onFragment(f ->{
```suggestion
        scenarioStandard.onFragment(f -> {
```

2021-04-01 22:26 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java
> +
```suggestion
```

2021-04-01 22:27 UTC, mikehardy approved these changes

2021-04-01 22:27 UTC, merged

2021-04-05 18:31 UTC, mikehardy commented
Hi there!

Just a friendly notice (one per person for PRs merged in March, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for March 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

Thanks!