NF: uses hash set/map which take size as init instead of capacity
ankidroid/Anki-Android pull request #8339
Opened 2021-03-25 11:16 UTC by Arthur-Milchior

Fixes #8337

2021-03-25 12:03 UTC, david-allison-1 requested changes
```
  symbol:   class HashUtil
  location: package com.ichi2.utils
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/themes/HtmlColors.java:3: error: cannot find symbol
import com.ichi2.utils.HashUtil;
```

Added a few places where the `HashUtil` is unused - this could indicate a problem, if it's fine, mark as resolved.

2021-03-25 13:09 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
> +     * given a card type, we don't need to recompute the HashUtil.
I used script to do some replacement. But this one, I fail to see how it was catched. Make no sens

2021-03-25 13:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/template/ParsedNode.java
> -import android.text.TextUtils;
No need for this change

2021-04-04 13:49 UTC, mikehardy requested changes
Seems fine to me - there is one unused import (doesn't codacy still send you email with new issues when it finds them? I got email on my last PR that had a codacy report showing I'd created issues and it pointed out 2 unused imports I forgot...)

Also needs a rebase / de-conflict

2021-04-04 13:49 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
> +import com.ichi2.utils.HashUtil;
remove unused header
```suggestion
```

2021-04-05 00:41 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
> +import com.ichi2.utils.HashUtil;
no, I never saw a codacy email

2021-04-05 13:23 UTC, mikehardy commented
@Arthur-Milchior Something went terribly wrong in the rebase and now HashUtil, which is pretty important to this PR, is not in the change, causing predictable havoc...

2021-04-08 15:08 UTC, mikehardy commented
Hey @Arthur-Milchior - can you patch this one up? Then we can get it in before moving on to the other PRs you are posting :)

2021-04-11 11:29 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/HashUtil.java
> +        return new HashMap<T, U>(capacity(size));
I spent some time to read about reflection but I don't understand how I could check that a function is not called. I don't see a way to change a method's code

2021-04-11 11:30 UTC, Arthur-Milchior commented
Sorry, I missed the first message. Too many things right now

2021-04-11 14:36 UTC, david-allison-1 approved these changes
LGTM, had a play in the debugger and it seems good. A unit test would be very nice

2021-04-11 14:36 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        Set<String> set = AnkiDroidApp.getSharedPrefs(this).getStringSet("note_editor_custom_buttons", HashUtil.HashSetInit(0));
If we're getting into microoptimisations, we shouldn't be allocating the HashSet at all

Fine though

2021-04-11 14:36 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/HashUtil.java
> +        return new HashMap<T, U>(capacity(size));
You can't (easily) - but you can read the internal state of the object to see if threshold is changed

2021-04-12 10:06 UTC, Arthur-Milchior commented
I rebased and added what I thought would be correct test. But it tells that some field I see in the source code do not exists. So I assume it uses a different implementation. Don't see how to test here. Help wanted

2021-04-12 10:23 UTC, david-allison-1 commented
> I rebased and added what I thought would be correct test. But it tells that some field I see in the source code do not exists. So I assume it uses a different implementation. Don't see how to test here. Help wanted

(On my phone). It's probably JaCoCo. Try filtering on `!field.isSynthetic`

2021-04-12 11:35 UTC, david-allison-1 reviewed
Try this

2021-04-12 11:35 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/utils/HashUtilTest.java
> +    public void NoReThreshold() throws NoSuchFieldException, IllegalAccessException {
```suggestion
    public void thresholdIsNotModifiedAfterCreationWithFixedSizeCollection() throws NoSuchFieldException, IllegalAccessException {
```

2021-04-12 11:35 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/utils/HashUtilTest.java
> +        return mapThreshold((HashMap) HashMap.class.getField("map").get(set));
```suggestion
        Field map = HashMap.class.getDeclaredField("map");
        map.setAccessible(true);
        return mapThreshold((HashMap) map.get(set));
```

2021-04-12 11:35 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/utils/HashUtilTest.java
> +        return  thresholdField.getInt(map);
```suggestion
        Field thresholdField = HashMap.class.getDeclaredField("threshold");
        thresholdField.setAccessible(true);
        return thresholdField.getInt(map);
    }
```

2021-04-12 12:23 UTC, david-allison-1 commented
Bad suggestion - apologies - split my code into 3 for ease of understanding

2021-04-12 12:24 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/utils/HashUtilTest.java
> +    }
Reminder to self: don't use suggestions for nontrivial fixes
```suggestion
```

2021-04-12 12:43 UTC, Arthur-Milchior commented
May I just let it to you, will probably get easier.

2021-06-02 03:24 UTC, david-allison-1 commented
Sorry this took so long

Given the CI output, let's get this in without tests:

```
> Task :AnkiDroid:testDebugUnitTest
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.ichi2.utils.HashUtilTest (file:/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/build/intermediates/javac/debugUnitTest/classes/) to field java.util.HashMap.threshold
WARNING: Please consider reporting this to the maintainers of com.ichi2.utils.HashUtilTest
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

com.ichi2.utils.HashUtilTest > thresholdIsNotModifiedAfterCreationWithFixedSizeCollection FAILED
    java.lang.AssertionError: expected:<16> but was:<12>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at com.ichi2.utils.HashUtilTest.thresholdIsNotModifiedAfterCreationWithFixedSizeCollection(HashUtilTest.java:37)
```

I'm happy it's working from experimentation

2021-06-02 03:25 UTC, david-allison-1 requested changes
adding this review flag: 

requested change: remove the tests given my comment above

2021-08-29 19:20 UTC, Arthur-Milchior commented
Done

2021-08-29 20:27 UTC, mikehardy requested changes
I was all ready to hit the tempting + fun-to-hit merge button but we need a copyright header, then I think it's merge-able

2021-08-29 20:27 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/utils/HashUtil.java
> +package com.ichi2.utils;
Missing copyright header check got you! :-)

```

/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/utils/HashUtil.java:1: Error: All files in AnkiDroid must contain a GPLv3-compatible copyright header [MissingCopyrightHeader from com.ichi2.anki.lint]
...
``

2021-09-04 08:43 UTC, Arthur-Milchior commented
done

2021-09-04 13:33 UTC, david-allison-1 approved these changes
LGTM, could do with a "Convert to Kotlin" for the new file, but that's not standardised yet

2021-09-04 14:25 UTC, mikehardy approved these changes
No need to keep messing around with this one - it took a conflict from a merge I just did but the code looks great on review now, I just went ahead and fixed the conflict if it passes CI I will squash-merge - thanks Arthur!

2021-09-04 14:47 UTC, merged