greying out disabled editText
ankidroid/Anki-Android pull request #8340
Opened 2021-03-25 13:30 UTC by prateek-singh-3212

## Pull Request template

## Purpose / Description
Changing note type in note editor make fields non-clickable

## Fixes
Fixes #8247 

## Approach
Greyed out the edit text fields when edit text fields are disabled

## How Has This Been Tested?

Tested on Samsung Galaxy M51, android 11 (Samsung One UI 3.1)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-25 13:50 UTC, david-allison-1 requested changes
Looks good! A few tiny changes, then good to go, thanks!

PS: Could you also test this in night mode and make sure it looks reasonable

2021-03-25 13:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        if(!enabled){
```suggestion
        if (!enabled){
```

2021-03-25 13:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +            editText.setBackgroundColor(Color.parseColor("#CFCFCF"));
Could you extract this to a resource (for example: https://github.com/ankidroid/Anki-Android/blob/8fa3e45e2d3cf4d9898caf990825429f472faad9/AnkiDroid/src/main/res/values/theme_light.xml#L14)

2021-03-25 14:28 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +            editText.setBackgroundColor(Color.parseColor("#CFCFCF"));
Yes,
here is the screenshot of both light and dark mode and I have linked this with color.xml. Should I use different colors for both light and dark modes?
![WhatsApp Image 2021-03-25 at 19 47 43(1)](https://user-images.githubusercontent.com/76490368/112488095-457df380-8da3-11eb-8a46-572b408c4676.jpeg)
![WhatsApp Image 2021-03-25 at 19 47 43](https://user-images.githubusercontent.com/76490368/112488103-4747b700-8da3-11eb-8778-f476586c185a.jpeg)

2021-03-25 14:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +            editText.setBackgroundColor(Color.parseColor("#CFCFCF"));
I trust your judgment - it should be easy to do if extracted to `resources`, see the `theme-` xml files.

2021-03-25 14:31 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        if (!enabled){
Really sorry 😅

```suggestion
        if (!enabled) {
```

2021-03-26 05:15 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +            editText.setBackgroundColor(Color.parseColor("#CFCFCF"));
Apology for the late work. I have added different colors for different themes and liked their code with theme files. 
Here is the screenshot of both light and dark theme
![WhatsApp Image 2021-03-26 at 09 58 28(1)](https://user-images.githubusercontent.com/76490368/112585639-35f0c000-8e20-11eb-8514-fbfd08d8a70d.jpeg)
![WhatsApp Image 2021-03-26 at 09 58 28](https://user-images.githubusercontent.com/76490368/112585642-3721ed00-8e20-11eb-995d-57e0769d3917.jpeg)

2021-03-26 07:00 UTC, david-allison-1 approved these changes
Looks good to me, thanks!

2021-03-26 07:01 UTC, david-allison-1 commented
In future, please don't perform a `merge` commit into your branch, instead, rebase it onto `master`

2021-03-26 07:29 UTC, prateek-singh-3212 commented
> In future, please don't perform a `merge` commit into your branch, instead, `rebase` it onto `master`

okay, I will take care of this thing further.

2021-03-26 14:44 UTC, mikehardy approved these changes
LGTM thanks!

2021-03-26 14:45 UTC, merged