revert changes by pr #6175
ankidroid/Anki-Android pull request #8341
Opened 2021-03-25 14:16 UTC by almas33

## Pull Request template

## Purpose / Description
pull request made for this issue were to be reverted and to make a interface based solution

## Fixes
#6174 

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-25 14:23 UTC, david-allison-1 requested changes
Thanks for the PR!!

Could you change the PR title and the commit message. 6175 was already reverted: https://github.com/ankidroid/Anki-Android/pull/6350

* Could you change `onPositive` to something more descriptive
* Could you remove `setTagsDialogListener` and the member variable
* Could you cast `[require|get]Activity` to `TagsDialogListener` instead of using the member variable

2021-03-25 21:41 UTC, almas33 commented
as 4 activities were using `onPositive` so I wasn't able to think of any better name than this

2021-03-26 06:58 UTC, david-allison-1 requested changes
Looks good!

Could you also convert the `ArrayList` in `onPositive` to a `List`

2021-03-26 06:58 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +    public void onPositive(ArrayList<String> selectedTags, int option) {
Could we rename `TagsDialogListener.onPositive`, it has no semantic meaning in the context of the CardViewer?

2021-03-26 06:58 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        DeckDropDownAdapter.SubtitleListener, TagsDialog.TagsDialogListener{
```suggestion
        DeckDropDownAdapter.SubtitleListener, TagsDialog.TagsDialogListener {
```

2021-03-26 06:58 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        TagsDialog.TagsDialogListener{
```suggestion
        TagsDialog.TagsDialogListener {
```

2021-03-26 10:47 UTC, almas33 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +    public void onPositive(ArrayList<String> selectedTags, int option) {
should I make another function in interface which can also have a different name for `CardBrowser` as coverting to `List` would make code less readable in `NoteEditor` because we have to make adjustments.

2021-03-26 11:01 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +    public void onPositive(ArrayList<String> selectedTags, int option) {
No, just rename `onPositive` to something relevant for the activities

`onTagsSelected` for example

2021-03-26 12:22 UTC, david-allison-1 reviewed
Pretty much there, should be the final one - should be able to convert to `list` for a nicer interface

2021-03-26 12:22 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
> +         * Here's the method that gathers the final selection of tags, type of cards and
Convert the comment to a doccomment above the method name

2021-03-26 12:22 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
> +         * Here's the method that gathers the final selection of tags, type of cards and
```suggestion
         * Gathers the final selection of tags, type of cards and
```

2021-03-26 14:06 UTC, david-allison-1 approved these changes
Looks great to me, thanks for the quick turnaround!

2021-03-26 14:41 UTC, mikehardy approved these changes
This looks nice!

2021-03-26 14:42 UTC, merged

2021-04-05 18:30 UTC, mikehardy commented
Hi there!

Just a friendly notice (one per person for PRs merged in March, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for March 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

Thanks!