Fixes #7983 Remaining time wrongly displayed as "0s" when falling und…
ankidroid/Anki-Android pull request #8343
Opened 2021-03-26 11:47 UTC by AyaanJaved

Added an if check which clamps the remaining time to 1 minute in case it goes under it.

## Purpose / Description
Intends to fix the wrong time (0 minute) displayed when the remaining time is under a minute.

![Screenshot_20210326-170251](https://user-images.githubusercontent.com/80831951/112626449-399f3980-8e56-11eb-9551-80e013594be5.png)

## Fixes
Fixes #7983 

After Fix
![Screenshot_20210326-170731](https://user-images.githubusercontent.com/80831951/112626625-779c5d80-8e56-11eb-9955-d1198b0a4e6d.png)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-26 12:23 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
> +            if(time_x == 0) {
nitpick: matches coding style
```suggestion
            if (time_x == 0) {
```

2021-03-26 13:01 UTC, david-allison-1 approved these changes
Thanks!!!

2021-03-26 14:38 UTC, mikehardy requested changes

2021-03-26 14:38 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
> +            }
This is going to seem like a nitpick but I think it's important

1- if the idea is to "clamp" something, you want to wipe out the whole range below the value you want to clamp, just in case, not just one specific value (0), so Math.max(ETA, 1) is better (changing it to `< 1` as a comparison could also work but we're already using Math methods, just throw one more in...)
2- there should be a comment so future code readers know why we are doing this

```suggestion
            // get time remaining, but never less than 1
            time_x = Math.max((int) Math.round(time_s / TIME_MINUTE), 1);
```

2021-03-26 14:50 UTC, AyaanJaved commented on AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
> +            }
Thanks for the suggestions
Definitely gonna keep them in mind the next time I contribute

2021-03-26 14:56 UTC, mikehardy approved these changes
of course my own code suggestion looks good to me :laughing: - but seriously, this looks good to go now, thank you!

2021-03-26 15:28 UTC, merged

2021-04-05 18:30 UTC, mikehardy commented
Hi there!

Just a friendly notice (one per person for PRs merged in March, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for March 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

Thanks!