Use text from browser search bar as first field when adding new note added
ankidroid/Anki-Android pull request #8345
Opened 2021-03-26 14:07 UTC by Arnold2381

## Purpose / Description
The purpose to not rewrite the text typed in SearchView of Card Browser activity and directly use it when clicking on Add note (overflow menu) if there is no such card present.

## Fixes
Use text from browser search bar as the first field when adding a new note #4925

## Approach
The approach was to first send the text from the CardBrowser activity on Add Note item click that was done using intent.putExtra and then setting it in first edit field when the focus was being set to it.

## How Has This Been Tested?
Tested on a physical device (Android -9)

## Screenshots

https://user-images.githubusercontent.com/46752548/112643128-08c8ff80-8e6a-11eb-8ec9-46eec1e7c7aa.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [x]  You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x]  You have a descriptive commit message with a short title (first line, max 50 chars).
- [x]  Your code follows the style of the project (e.g. never omit braces in if statements)
- [ ]  You have commented on your code, particularly in hard-to-understand areas
- [x]  You have performed a self-review of your own code

2021-03-26 14:12 UTC, david-allison-1 requested changes
Change looks good, just some nitpicks on naming/code style!

Thanks

2021-03-26 14:12 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        intent.putExtra("SEARCH",mSearchTerms);
```suggestion
        intent.putExtra("SEARCH", mSearchTerms);
```

2021-03-26 14:12 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        intent.putExtra("SEARCH",mSearchTerms);
We should extract `SEARCH` to a constant

2021-03-26 14:12 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +    private String search_item_query;
See code style: https://github.com/ankidroid/Anki-Android/wiki/Code-style#non-public-non-static-field-names-should-start-with-m

`private String mSearchItemQuery;`

2021-03-26 14:12 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        intent.putExtra("SEARCH",mSearchTerms);
We should also use a more descriptive name

2021-03-26 14:20 UTC, david-allison-1 commented
Unit test failure:

```
com.ichi2.anki.NoteEditorTest > processTextIntentShouldCopyFirstField FAILED
    java.lang.AssertionError: 
    Expected: iterable containing ["hello\nworld", ""]
         but: item 0: was ""
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at com.ichi2.anki.NoteEditorTest.processTextIntentShouldCopyFirstField(NoteEditorTest.java:272)
```

It'd also help to have unit tests for this functionality

2021-03-26 15:07 UTC, Arnold2381 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        intent.putExtra("SEARCH",mSearchTerms);
When I am extracting search to a constant I am not getting the text in add note.

2021-03-26 19:08 UTC, Arnold2381 commented
> Unit test failure:
> 
> ```
> com.ichi2.anki.NoteEditorTest > processTextIntentShouldCopyFirstField FAILED
>     java.lang.AssertionError: 
>     Expected: iterable containing ["hello\nworld", ""]
>          but: item 0: was ""
>         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
>         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
>         at com.ichi2.anki.NoteEditorTest.processTextIntentShouldCopyFirstField(NoteEditorTest.java:272)
> ```
> 
> It'd also help to have unit tests for this functionality

Can you give me some insights on how to work on the testing part, I have fixed the formatting and constant variable part?

2021-03-26 19:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +    public static final String TEXT_FROM_SEARCH_VIEW= "";
Do you really want to put an empty string ? I'd have assumed you would have wanted "SEARCH"  as the value. And in this case, the commit should be marked as "NF:"

2021-03-26 19:52 UTC, Arthur-Milchior commented
> Can you give me some insights on how to work on the testing part? I have fixed the formatting and constant variable part.

In Android Studio, you can find the test "processTextIntentShouldCopyFirstField" and click on the green right arrow near to it to run it locally. It'll tell you whether it is successful or not. 

I don't really know other general rules to figure out why some code bug, appart from reading the change you made and figuring out what caused this behavior

2021-03-26 21:29 UTC, david-allison-1 commented
> Can you give me some insights on how to work on the testing part? I have fixed the formatting and constant variable part.

First, find the test: `Ctrl+T, processTextIntentShouldCopyFirstField`

This will open up:

https://github.com/ankidroid/Anki-Android/blob/a4d290a87db4fee64f597aade5af6240dd72b028/AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java#L265-L273

![image](https://user-images.githubusercontent.com/62114487/112694390-2f8f3200-8e7a-11eb-8499-19dff4c2ada6.png)

Click the "play" button and select "debug", this will open up the test in a debugger. 

There will be tutorials on using a debugger, but in general, you set breakpoints, check variables, and see what's going on. Once you understand why the test isn't working, you can fix it.

This is also where you'd write your next test.

2021-03-27 07:27 UTC, Arnold2381 commented
I am getting a different error when I am running Test processTextIntentShouldCopyFirstField() whereas the details of the unit test show some other error.

The error I am getting 
![image](https://user-images.githubusercontent.com/46752548/112713503-7bce8680-8efb-11eb-943f-3bbed39c8b48.png)

I searched for my error and came to know its some problem with Roboelectric and using the shadowOf(getMainLooper()).idle() will solve it but unfortunately, it didn't work

the error in details of the junit test 
![image](https://user-images.githubusercontent.com/46752548/112713510-8426c180-8efb-11eb-8bd4-5a357f5bf02f.png)

I searched for this error and this can be solved using 
assertThat(actual, Matchers.hasItems("hello\nworld", ""));

2021-03-27 08:59 UTC, david-allison-1 commented
Oh dear... "Can't find dependent libraries" is caused by some backend changes, not a problem with the test. 

I'll need to look into it: https://github.com/david-allison-1/Anki-Android-Backend/issues/46

Could you comment on the referenced issue: 

* Does the referenced DLL in your temp directory exists.

----

No, `hasItems` won't help. The problem is that it's expecting `hello\nworld` in the first field, and that is no longer the case. This is because your feature is likely overriding the value with `null`, or an empty string

2021-03-27 09:05 UTC, Arnold2381 commented
> Oh dear... "Can't find dependent libraries" is caused by some backend changes, not a problem with the test.
> 
> I'll need to look into it: [david-allison-1/Anki-Android-Backend#46](https://github.com/david-allison-1/Anki-Android-Backend/issues/46)
> 
> Could you comment on the referenced issue:
> 
> * Does the referenced DLL in your temp directory exists.
> 
> No, `hasItems` won't help. The problem is that it's expecting `hello\nworld` in the first field, and that is no longer the case. This is because your feature is likely overriding the value with `null`, or an empty string

2021-03-27 09:06 UTC, Arnold2381 commented
> Oh dear... "Can't find dependent libraries" is caused by some backend changes, not a problem with the test.
> 
> I'll need to look into it: [david-allison-1/Anki-Android-Backend#46](https://github.com/david-allison-1/Anki-Android-Backend/issues/46)
> 
> Could you comment on the referenced issue:
> 
> * Does the referenced DLL in your temp directory exists.
> 
> No, `hasItems` won't help. The problem is that it's expecting `hello\nworld` in the first field, and that is no longer the case. This is because your feature is likely overriding the value with `null`, or an empty string

2021-03-27 09:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +    public static final String TEXT_FROM_SEARCH_VIEW= "SEARCH";
Also: rename to prefix with the word `EXTRA`:

`EXTRA_FIRST_FIELD` for example

```suggestion
    public static final String TEXT_FROM_SEARCH_VIEW = "SEARCH";
```

2021-03-27 10:41 UTC, david-allison-1 requested changes
Tiny changes, then good to go, thanks!!

2021-03-27 10:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +            if(mGetTextFromSearchView!=null && !mGetTextFromSearchView.isEmpty()) {
```suggestion
            if (mGetTextFromSearchView != null && !mGetTextFromSearchView.isEmpty()) {
```

2021-03-27 10:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +            //won't set Text in the first field if the value is empty or null
```suggestion
            // EXTRA_TEXT_FROM_SEARCH_VIEW takes priority over other input methods
```

2021-03-27 11:33 UTC, david-allison-1 reviewed
All good to go. One tiny change to make the code cleaner. Thanks so much!

BTW: Feel free to mark my comments as 'resolved' if you've completed them

2021-03-27 11:33 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        mGetTextFromSearchView = intent.getStringExtra(EXTRA_TEXT_FROM_SEARCH_VIEW);
This can be defined as a local variable without the private variable

2021-03-27 12:05 UTC, Arnold2381 commented
> All good to go. One tiny change to make the code cleaner. Thanks so much!
> 
> BTW: Feel free to mark my comments as 'resolved' if you've completed them

Sorry, I didn't know that, and also sorry for taking so long with some silly mistakes in formatting will take extra care next time and try solving the issue in minimum time.
And thank you so much for your patience and help :)

2021-03-27 12:14 UTC, Arnold2381 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        mGetTextFromSearchView = intent.getStringExtra(EXTRA_TEXT_FROM_SEARCH_VIEW);
It failed the emulator test, will have to check it.

2021-03-27 12:27 UTC, david-allison-1 approved these changes
Looks good to me, thanks!!!!

2021-03-27 12:29 UTC, Arnold2381 commented
> Looks good to me, thanks!!!!

Awesome!! Thank you so much for all the help!!

2021-03-27 12:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        mGetTextFromSearchView = intent.getStringExtra(EXTRA_TEXT_FROM_SEARCH_VIEW);
I'll restart those, we've had some test flakiness since moving from Travis, and haven't had the time to solve it

2021-03-27 14:31 UTC, mikehardy approved these changes
cool - LGTM

2021-03-27 14:32 UTC, merged

2021-03-27 14:33 UTC, mikehardy commented
In the future use the *exact* text `Fixes #issuenumber` in the PR and github auto-connects a PR and an issue and auto-closes the issue at the same time things are more easily clickable etc

2021-03-27 15:23 UTC, Arnold2381 commented
> In the future use the _exact_ text `Fixes #issuenumber` in the PR and github auto-connects a PR and an issue and auto-closes the issue at the same time things are more easily clickable etc

OK sure!! will keep in mind!!