Fixes #8169 'Card Browser becomes empty on toggling night mode"
ankidroid/Anki-Android pull request #8353
Opened 2021-03-26 20:21 UTC by 4D17Y4

## Fixes
#8169

## Approach
On a very exhaustive investigation, I found out that onDestroy is calling the search task to end, so when the search task is going on and the query is long enough the end search is called before it can finish and return the ouput , which results in empty card browser (The reason why we can see this clearly on all deck as the query is long ).
Moved the search cancelling statement to the start of next search to handle the error. 

## How Has This Been Tested?

Tested on Nokia 6.1 + , android 10 , sotck.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-26 20:51 UTC, david-allison-1 requested changes
Thanks for the investigation and the PR! Knowing the cause makes this much more easy to reason about

* Could you add your investigation into the commit message, so others can understand the reasoning behind the change
* Could we add a regression test for this issue

**Implementation**
Modifying `invalidate` affects quite a few areas of this screen, whereas we only want to affect the case where night mode is changed. 

I think it'd be best if we discussed if there were better ways to implement this. @Arthur-Milchior You were here last and guidance would be appreciated

Could we avoid calling `invalidate()` if `onDestroy()` is called due to a night mode change?

----

EDIT: Needs review as it may be useful to discuss implementations - if you find something that works and hits all use cases, then by all means, let's get this in.

2021-03-26 21:01 UTC, 4D17Y4 commented
Yes @david-allison-1 , 
Even I was worried about the other use cases where this might cause errors, 
I'll look into it to tackle the issue efficiently. 

Would love inputs frm @Arthur-Milchior .
 
I'll see to the requested changes on commit message and try adding the test. 
Thanks for the review.

2021-03-27 16:22 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        if(isDarkModeAtStart == AnkiDroidApp.getSharedPrefs(getApplicationContext())
Do we get this information on `onConfigurationChanged`?

2021-03-27 16:22 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        if(isDarkModeAtStart == AnkiDroidApp.getSharedPrefs(getApplicationContext())
```suggestion
        if (isDarkModeAtStart == AnkiDroidApp.getSharedPrefs(getApplicationContext())
```

2021-03-27 16:22 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        isDarkModeAtStart=AnkiDroidApp.getSharedPrefs(getApplicationContext())
Unsure if we can call it this early. We should move the code below `super.onCreate(savedInstanceState);`
```suggestion
        isDarkModeAtStart = AnkiDroidApp.getSharedPrefs(this)
```

2021-03-27 16:39 UTC, 4D17Y4 commented
Hey, @david-allison-1  
I've changed the onDestroy method to not call invalidate on just the theme change , and it works well.
The commit message is somewhat detailed this time.
I'll add the test if this is approved.
Thanks

2021-03-27 17:18 UTC, david-allison-1 commented
I'd prefer to see if there are better ways of implementing this (`onConfigurationChanged`, or some check/signal in `AnkiActivity` that `onDestroy` is called due to a theme change, rather than specifically encoding the logic that we care about a night mode change).

2021-03-28 20:51 UTC, 4D17Y4 commented
Digging a little deeper I found out that we're explicitly destroying the activity and creating a new one ( maybe because of that splash screen ) so onConfigurationChange cannot do much on this as the activity isnt being recreated. I checked this by logging isFinishing() in the destroy and it was true all the time.

2021-04-24 13:56 UTC, DuguMingyue commented
I 've tried to reproduce this issue and find that only the cards are small and short may cause this issue. If I add some cards with many contents in it then the bug cannot be triggered. I guess the issue is just affected by the speed of the thread that holds the onCreate() method so I make onDestroy() sleep 200ms before invalidate() and the bug never appear again. (Before editing the code on Anki 2.14.6, the bug is not 100% appears each time we change the theme).

2021-04-25 02:35 UTC, Arthur-Milchior reviewed
Thanks a lot for investigating this. 
Sorry, it was hard to review all PR quickly and this one is non trivial :s 

Thanks for searching and expalining task stack builder issue. 
Did you create a bug report? It might be best to discuss the options in an issue than in a PR.

I am totally fine with finding a different approach. I have no idea why moving to night/day mode need such a big rewritting of everything, so anything that can ease the loading time is great.

I wonder whether a solution could be, in AnkiActivity, to have a method to override that execute code that need to be executed iff there is a change in mode and code that is executed iff it's unrelated change. This way, instead of having the logic in the card browser, where it has nothing to do, we could have a general rules that may be applied elsewhere to simplify reloading.

2021-04-25 02:35 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> -        TaskManager.cancelAllTasks(CollectionTask.SearchCards.class);
As david stated, an explanation in the commit message would be nice.

In this case, I'd like to know in which case it was a mistake to cancel the SearchCards actions that justify removing this call

2021-04-25 02:35 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> -        TaskManager.cancelAllTasks(CollectionTask.SearchCards.class);
It seems that you are undoing in the second commit what you did in the first. Can you maybe squash those two commits for the ease of review, and history?

2021-04-25 02:35 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +                        .getBoolean(NIGHT_MODE_PREFERENCE,false)) {
space after the comma

2021-07-01 02:41 UTC, closed without merging