Fix part of : 8293 Forward porting Fragment startActivityForResult/onActvityResult to new Activity APIs
ankidroid/Anki-Android pull request #8356
Opened 2021-03-27 10:09 UTC by kartikeysaran

## Purpose / Description
inter-fragment/inter-activity communication is now done using AndroidX libraries as the libraries used before are now deprecated

## Fixes
Fixes part of #8293 

## Learning (optional, can help others)
Using Android X activity result apis

_Links to blog posts, patterns, libraries or addons used to solve this problem_
https://medium.com/@miloszlewandowski/a-first-look-at-androidx-activity-result-apis-3dc0f887de09
https://medium.com/@okonjiemmanuel/send-and-receive-data-from-activities-using-the-activity-result-apis-b698884d0061

2021-03-27 10:09 UTC, kartikeysaran commented
This pr has been kept short in order for the designers to have a look as requested by @mikehardy

2021-03-27 11:41 UTC, david-allison-1 requested changes

2021-03-27 11:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            //startActivityForResult(browserAppearanceIntent, REQUEST_CARD_BROWSER_APPEARANCE);
Don't comment out the old code, just get rid of it, we can use git if we need it.

2021-03-27 11:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            //Now we have to use activityResultLauncher.launch
We don't need the comment

And as a note: from the code style, start each comment with a space

2021-03-27 11:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                        if (result.getResultCode() == REQUEST_CARD_BROWSER_APPEARANCE) {
We shouldn't move from `requestCode` to `resultCode`, my impression is that this library is designed to split out the requests so we don't need the large `if` chain.

I don't know this for certain.

Could you re-check the documentation, or show me an example where my above statement is wrong. I'm not certain.

2021-03-27 14:18 UTC, kartikeysaran commented on AnkiDroid/build.gradle
> +    implementation "androidx.fragment:fragment:1.3.0"
Okay

2021-03-27 14:18 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            //startActivityForResult(browserAppearanceIntent, REQUEST_CARD_BROWSER_APPEARANCE);
Okay would delete all the commented parts

2021-03-27 14:19 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            //Now we have to use activityResultLauncher.launch
Okay ! Sorry again, i literally forgot about the code style

2021-03-27 14:31 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            //Now we have to use activityResultLauncher.launch
No worries! It's on my TODO list to automate it away - not sure if I'll have time for this GSoC, but definitely in time for next year

2021-04-01 23:09 UTC, mikehardy requested changes
the design comments are still by far the most important since it is our first time using these new APIs, but I left a comment on the dependencies as well

2021-04-01 23:09 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                        if (result.getResultCode() == REQUEST_CARD_BROWSER_APPEARANCE) {
The docs indicate it is more about making this inter-Activity communication typesafe where possible, with this `ActivityResultContracts.StartActivityForResult()` default contract as a fallback for either a slow-migration or when the receiving Activity doesn't have a typesafe contract

https://developer.android.com/training/basics/intents/result

In this case I think we the activities we are launching (browser appearance or previewer) need data in their Intent, so the input contract could be specified concretely, and they return nothing so the output can be null but since we perform actions when they return each should be launched by a separate launcher with separate contracts depending on the input they need?

Assuming I understand it correctly

2021-04-04 08:09 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> -
Okay

2021-04-04 08:10 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +
Okay

2021-04-04 08:19 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                        if (result.getResultCode() == REQUEST_CARD_BROWSER_APPEARANCE) {
Yeah @mikehardy , I will create specified contracts wherever needed

2021-04-07 13:24 UTC, david-allison-1 requested changes
I have to say, I find this more complicated to read than the former code, but I think that's a combination of us not being in Kotlin, and not using some provided functionality

* Can we use [StartActivityForResult](https://developer.android.com/reference/androidx/activity/result/contract/ActivityResultContracts.StartActivityForResult) rather than writing our own
* Can we use lambdas, rather than the verbose `new ActivityResultCallback<Intent>() {`
* Should we be returning `null` for the intent if the result was cancelled?

2021-04-07 13:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                if(resultCode != Activity.RESULT_OK || intent == null) {
If intent is null, then `return intent` is equivalent to `return null;`

```suggestion
                if (resultCode != Activity.RESULT_OK) {
```

2021-04-07 13:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +             onCardBrowserAppearanceResult(data);
```suggestion
                onCardBrowserAppearanceResult(data);
```

2021-04-07 13:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                if(resultCode != Activity.RESULT_OK || intent == null) {
ditto

2021-04-07 13:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +        ActivityResultLauncher<Intent> onCardBrowserAppearanceResult = registerForActivityResult(new onCardBrowserAppearanceContract(), new ActivityResultCallback<Intent>() {
Can we use a lambda here?

2021-04-07 13:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                    return null;
This makes the data passed into `onCardBrowserAppearanceResult` null, is this what we want?

2021-04-08 06:44 UTC, kartikeysaran commented
> * Can we use [StartActivityForResult]

We can just rename the ``` onCardBrowserAppearanceResults  ``` to 
``` startActivityforResult ```

2021-04-08 06:51 UTC, kartikeysaran commented
> * Can we use lambdas, rather than the verbose `new ActivityResultCallback<Intent>() {`

I think we can, would update the code

2021-04-08 12:19 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                    return null;
Will review the old code once

2021-04-08 12:25 UTC, david-allison-1 commented
> > * Can we use lambdas, rather than the verbose `new ActivityResultCallback<Intent>() {`
> 
> No , please correct me if i am wrong

Let me confirm, added to my spreadsheet: at the worst case I think we'll be able to define a `[Intent/ActivityResult]Callback` for common cases which will massively reduce code

2021-04-08 12:26 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                    return null;
> This makes the data passed into `onCardBrowserAppearanceResult` null, is this what we want? It seems to differ from how it used to be

Before we used to check the result code inside the method ``` onCardBrowserAppearanceResult()``` as ``` private void onCardBrowserAppearanceResult(int resultCode, @Nullable Intent data) {
            if (resultCode != RESULT_OK) {
                Timber.i("Activity Cancelled: Card Template Browser Appearance");
                return;
            } ```

2021-04-10 23:52 UTC, david-allison-1 reviewed
I asked about the StartActivityForResult class in my previous comment, that's my main question in reducing the code size. Lambdas look good, but I think we can do better

2021-04-11 07:27 UTC, kartikeysaran commented
> I asked about the StartActivityForResult class 

yes, we can

2021-04-12 06:00 UTC, kartikeysaran commented
> I asked about the StartActivityForResult class in my previous comment, that's my main question in reducing the code size. Lambdas look good, I think we can do even better

I had a look at [StartActivityForResult](https://developer.android.com/reference/androidx/activity/result/contract/ActivityResultContracts.StartActivityForResult), they can not be used here

2021-04-12 11:47 UTC, david-allison-1 reviewed
Sorry, the github-produced diff is terrible, but this should massively cut down on code

2021-04-12 11:47 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +        });
```suggestion
        ActivityResultLauncher<Intent> onRequestPreviewResult = registerForActivityResult(new ActivityResultContracts.StartActivityForResult(), result ->  {
                if (result.getResultCode() != RESULT_OK) {
                    return;
                }
                TemporaryModel.clearTempModelFiles();
                // Make sure the fragments reinitialize, otherwise there is staleness on return
                ((TemplatePagerAdapter)mTemplateEditor.mViewPager.getAdapter()).ordinalShift();
                mTemplateEditor.mViewPager.getAdapter().notifyDataSetChanged();
        });
```

2021-04-12 11:56 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +        ActivityResultLauncher<Intent> onRequestPreviewResult = registerForActivityResult(new ActivityResultContracts.StartActivityForResult(), result ->  {
I think the same refactoring can be applied to the other call

2021-04-13 04:33 UTC, david-allison-1 approved these changes
Really clean! Looks like a great proof of concept!

Thanks!!

2021-04-13 04:41 UTC, kartikeysaran commented
> Really clean! Looks like a great proof of concept!
> 
> Thanks!!

I have to make changes in ``` StudyOptionsFragment ``` as well then this pr would be completed

2021-04-14 02:56 UTC, mikehardy requested changes
I left a bunch of comments that are all trivial details, nothing to do with the structure - all important to do but super easy.

This is a great proof of concept of the new style, I'm excited to get this in and then (hopefully quickly, though everything takes time) refresh the whole codebase with the new style now that it's proven.

This one even has some automated test coverage because the CardTemplateEditor test probes the preview pathway https://app.codecov.io/gh/ankidroid/Anki-Android/compare/8356/diff#D1L549

Nice!

2021-04-14 02:56 UTC, mikehardy commented on AnkiDroid/build.gradle
> +    implementation "androidx.fragment:fragment:1.3.0"
Fragment dependency is already declared above (mostly alphabetically up there) https://github.com/ankidroid/Anki-Android/pull/8356/files#diff-5a90cabaa566821feb87e2e3cf9f9045ac174ceabbf2d10d8a86244f74b1bc49R229

```suggestion
```

2021-04-14 02:56 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            if(result.getResultCode() != RESULT_OK) {
minor spacing issue

```suggestion
            if (result.getResultCode() != RESULT_OK) {
```

2021-04-14 02:56 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
>      private void openFilteredDeckOptions(boolean defaultConfig) {
There is a deprecation marker on line 160 - I think the reward for this work is that we can remove that now ? :sunglasses:

2021-04-14 02:56 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
>          Intent reviewer = new Intent(getActivity(), Reviewer.class);
same here - there is a deprecation suppression on line 244 here that I think may be deleted?

2021-04-14 02:56 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
>                  openFilteredDeckOptions();
deprecation on this method is higher up but line 316 (which I guess will move as you remove them - but you get the idea - we can remove the issue 8293 deprecations for the methods you have worked on

2021-04-14 02:56 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
> +        if (result.getResultCode() == DeckPicker.RESULT_DB_ERROR || result.getResultCode() == DeckPicker.RESULT_MEDIA_EJECTED) {
I believe our coding standard go for "explicit parantheses" - by which I mean, even though they are not strictly necessary we put parentheses around all boolean logic clauses just to help tired brains read the if statements without thinking more than necessary during code reviews ;-)

```suggestion
        if ((result.getResultCode() == DeckPicker.RESULT_DB_ERROR) || (result.getResultCode() == DeckPicker.RESULT_MEDIA_EJECTED)) {
```

2021-04-14 02:56 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
> +            if (getCol().getSched().count() > 0 && mStudyOptionsView != null) {
explicit parentheses - these are just nitpicks of course

```suggestion
            if ((getCol().getSched().count() > 0) && (mStudyOptionsView != null)) {
```

2021-04-14 02:56 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
> +        if (result.getResultCode() == DeckPicker.RESULT_DB_ERROR || result.getResultCode() == DeckPicker.RESULT_MEDIA_EJECTED) {
```suggestion
        if ((result.getResultCode() == DeckPicker.RESULT_DB_ERROR) || (result.getResultCode() == DeckPicker.RESULT_MEDIA_EJECTED)) {
```

2021-04-14 02:56 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
> +        if (result.getResultCode() == DeckPicker.RESULT_DB_ERROR || result.getResultCode() == DeckPicker.RESULT_MEDIA_EJECTED) {
```suggestion
        if ((result.getResultCode() == DeckPicker.RESULT_DB_ERROR) || (result.getResultCode() == DeckPicker.RESULT_MEDIA_EJECTED)) {
```

2021-04-14 02:56 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
> +        if(mCurrentContentView == CONTENT_CONGRATS) {
trivial spacing change

```suggestion
        if (mCurrentContentView == CONTENT_CONGRATS) {
```

2021-04-14 02:57 UTC, mikehardy commented
maintainer note: I'm happy for anyone to merge this after my batch of nitpick requests is cleared up

2021-04-14 05:47 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
>          Intent reviewer = new Intent(getActivity(), Reviewer.class);
Yes

2021-04-14 05:47 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
>      private void openFilteredDeckOptions(boolean defaultConfig) {
Yes

2021-04-14 11:43 UTC, mikehardy approved these changes
Nice! Thank you

2021-04-14 11:44 UTC, merged

2021-04-14 13:01 UTC, david-allison-1 commented
@kartikeysaran Just to note for future: could you dismiss a review if you make substantial changes after an approved review?

2021-04-14 13:37 UTC, kartikeysaran commented
> @kartikeysaran Just to note for future: could you dismiss a review if you make substantial changes after an approved review?

No, I can just request for another review