added lint rules to check for copyright header in .java files
ankidroid/Anki-Android pull request #8359
Opened 2021-03-27 12:58 UTC by almas33

## Pull Request template

## Fixes
#8211 

## Approach
_How does this change address the problem?_
Feed `Copyright Header` in `Pattern`
`Matcher` will tell if that pattern is found
Reference use : https://github.com/vanniktech/lint-rules/blob/master/lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/InvalidSingleLineCommentDetector.kt
## How Has This Been Tested?

CI should tell

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_
https://github.com/vanniktech/lint-rules
## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-27 13:03 UTC, almas33 commented
Sorry, but Not sure if this will work as expected waiting for checks...

2021-03-27 13:47 UTC, david-allison-1 requested changes
Seeing this made my day, thank you! 

Things like these mean that code reviews will take less time to do, and we have more time to make AnkiDroid better

2021-03-27 13:47 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/CopyrightHeaderChecker.java
> +                " *  Copyright (c) $today.year David Allison <davidallisongithub@gmail.com>\n" +
This needs to be less restrictive, there are many comment styles within the codebase. 

Especially don't hardcode my name or the year, I don't want to have to make every file 😅

2021-03-27 13:47 UTC, david-allison-1 commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/CopyrightHeaderCheckerTest.java
> +        lint()
Surely this file should succeed, and a file without the copyright header should fail?

2021-03-27 13:47 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/CopyrightHeaderChecker.java
> +    private static final String EXPLANATION = "All files in AnkiDroid must contain  Copyright Header. " +
You might want to add newlines here as well.

```suggestion
    private static final String EXPLANATION = "All files in AnkiDroid must contain a GPLv3-compatible copyright header" +
```

You should also provide a link to a "default" copyright header that someone can copy/paste (maybe a wiki page?).

2021-03-27 13:47 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/CopyrightHeaderChecker.java
> +            Constants.ANKI_TIME_CATEGORY,
Might want to change these - they're fairly unimportant for now

2021-03-27 13:47 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/CopyrightHeaderChecker.java
> +        String source = context.getContents().toString();
Unsure here: we may be able to get a speedup if we don't use `.toString()`

2021-03-27 13:48 UTC, david-allison-1 commented
You can use `gradlew lintRelease` to test your code on the codebase locally.

I expect that it'll fail - but not crash, we'll likely have a few files which are missing copyright, which we'll deal with

2021-04-09 15:56 UTC, david-allison-1 commented
@almas33 Do you expect you'll have time to work on feedback?

2021-04-09 18:41 UTC, almas33 commented
Yes definitely, Sorry I got busy due to college projects

2021-04-09 19:01 UTC, david-allison-1 commented
> Yes definitely, Sorry I got busy due to college projects

No worries!

2021-04-13 07:30 UTC, almas33 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/CopyrightHeaderChecker.java
> +            Constants.ANKI_TIME_CATEGORY,
But if I remove them arguements will be less

2021-04-13 07:31 UTC, almas33 commented
> You can use `gradlew lintRelease` to test your code on the codebase locally.
> 
> I expect that it'll fail - but not crash, we'll likely have a few files which are missing copyright, which we'll deal with. Once you get to this stage, let's make it public so we can discuss what to do with the files

It is getting successful that means something is wrong

2021-04-13 16:59 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/CopyrightHeaderChecker.java
> +            Constants.ANKI_TIME_CATEGORY,
rebase onto `master`, then use `Constants.ANKI_CODE_STYLE_CATEGORY`

2021-04-14 16:37 UTC, david-allison-1 requested changes

2021-04-14 16:37 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/CopyrightHeaderChecker.java
> + *  Copyright (c) 2021 David Allison <davidallisongithub@gmail.com>
Not my file

2021-04-14 16:37 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/CopyrightHeaderChecker.java
> +                " *  Foundation; either version 3 of the License, or (at your option) any later\n" +
Just checking for this fragment should be enough
```
                " * either version 3 of the License, or (at your option) any later\n" +
```

2021-04-14 16:37 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/CopyrightHeaderChecker.java
> +        if (!found) {
```suggestion
        if (!pattern.matcher(source).find()) {
```

2021-04-14 16:37 UTC, david-allison-1 commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/CopyrightHeaderCheckerTest.java
> + *  Copyright (c) 2021 David Allison <davidallisongithub@gmail.com>
Not me

2021-04-14 16:37 UTC, david-allison-1 commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/CopyrightHeaderCheckerTest.java
> +
Also test for a failure

2021-04-14 16:37 UTC, david-allison-1 commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/CopyrightHeaderCheckerTest.java
> +                .expectErrorCount(1)
This should be fine?

2021-04-14 16:38 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/CopyrightHeaderChecker.java
> +        Pattern pattern = Pattern.compile("/*\n" +
Compile the pattern in a static for performancee

2021-04-15 07:36 UTC, almas33 commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/CopyrightHeaderCheckerTest.java
> +                .expectErrorCount(1)
Got little confused from this and comment from previous commit , please clarify
we have to create 2 tests :-
1. filewithCopyrightHeaderfails
    expectErrorCount(0)
2. showsNoErrorOnMissingCopyrightHeader
   expectErrorCount(0)

2021-04-15 12:51 UTC, david-allison-1 commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/CopyrightHeaderCheckerTest.java
> +                .expectErrorCount(1)
A file with a copyright header does not fail the lint check

A file with no copyright header fails the lint check (1 error)

2021-04-15 14:56 UTC, almas33 commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/CopyrightHeaderCheckerTest.java
> +                .expectErrorCount(1)
Yes , So in first commit name of test was `showsErrorForNoCopyrightHeader() `  (1 error)
but you said 

> Surely this file should succeed, and a file without the copyright header should fail?

So, I think it was doing the same thing before
Sorry, If I'm not understanding properly

In the last point, I was asking about the use of  `String mCopyrightHeader`  used in line `51` and does it have to be same as `Pattern`

2021-04-15 15:02 UTC, david-allison-1 commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/CopyrightHeaderCheckerTest.java
> +                .expectErrorCount(1)
As far as I recall, a file with a copyright header was passed into `showsErrorForNoCopyrightHeader` in that instance, sorry for being unclear (or incorrect)

----

We should have an example of a full, correct copyright header, no use in checking for the search snippet

If our code misses an example which exists in the codebase, we should add these as test cases, and fix the issue to protect against regressions (for example: the regex may need better newline handling)

2021-06-24 16:31 UTC, david-allison-1 commented
Fixed in #8662

2021-06-24 16:31 UTC, closed without merging