Fixes #7757 Lint check for onPrepareOptionsMenu
ankidroid/Anki-Android pull request #8374
Opened 2021-03-28 19:20 UTC by mrudultora

## Purpose / Description
Lint check to ensure that `onPrepareOptionsMenu` is not used.

## Fixes
Fixes #7757 

## Approach
If sub class of `Activity` class overrides `onPrepareOptionsMenu` (forbidden method) then an error will be generated.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-28 19:26 UTC, david-allison-1 approved these changes
LGTM

2021-03-28 19:27 UTC, mrudultora commented
I was unable to add test as `onPrepareOptionsMenu` requires object of `Menu` as argument. So, I am confused on the way to write a stub class.

2021-03-29 14:52 UTC, TarekkMA commented
> I was unable to add test as `onPrepareOptionsMenu` requires object of `Menu` as argument. So, I am confused on the way to write a stub class.

Use mockito, `Mockito.mock(Menu.class)` will return a concrete stub class for use.

```java
final Menu menu = Mockito.mock(Menu.class);

//to check if a method is called on the mocked object
verify(menu, times(1)).someMethod();
```

2021-04-01 22:41 UTC, david-allison-1 requested changes
Sorry... had a more thorough test. 

Could you add a unit test, this doesn't block `onPrepareOptionsMenu` from being added

2021-04-02 02:02 UTC, mrudultora commented
If its not blocking, is there something wrong in code, from your POV ? Should I change something?

2021-04-02 02:05 UTC, david-allison-1 commented
> If its not blocking, is there something wrong in code, from your POV ? Should I change something? I will add a unit test, but if it's not blocking at the first place then I must correct that firstly.

I should get a failure if I add `onPrepareOptionsMenu` to CardBrowser and run `gradlew lintRelease` it doesn't, so a PR wouldn't be blocked.

2021-04-12 08:48 UTC, closed without merging