Fixes #4312: Undo Bury Card opens Reviewer and Updates card number
ankidroid/Anki-Android pull request #8384
Opened 2021-03-29 19:18 UTC by farjadilyas

## Purpose / Description
Undoing Bury Card on the last card of the deck does not navigate to the Reviewer and update the left, blue number

## Fixes
Fixes #4312 

## Behavior
After clicking on 'Undo Bury Card', the study screen with the card is displayed again, just as it is done when the last card is answered and then you chose "Undo bury card" - the expected behavior described in #4312. In addition, the leftmost blue number is updated immediately for both the suspend and bury action.

## Approach
Similar approach to that used for 'Undo Last Review'. Calls ```deckPicker.updateDeckList()``` in DeckPicker.java to update the blue number. 

## How Has This Been Tested?
* Tested on SAMSUNG SM-A805F API 29 (Physical Device)
* Pixel 3a XL API 27 (Emulator)

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

No UI changes

2021-03-29 19:26 UTC, david-allison-1 requested changes
Looks good! Absolutely miniscule nitpick and a question

2021-03-29 19:26 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            else if (isBury) {
tiny nitpick: this should be on the same line as the `}`

2021-03-29 19:26 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            deckPicker.updateDeckList();
q: what does adding this line solve?

2021-03-29 19:31 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            else if (isBury) {
Got it!

2021-03-29 19:38 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            deckPicker.updateDeckList();
Without that line, if you undo suspend card, it does not update the left-most blue number. Now that you've pointed it out, I see that this line doesn't need to be executed if we click on 'Undo Bury Card' or 'Undo Last Review' since the number gets updated already once the Activity resumes. So I can improve this by only calling for Undo Suspend?

2021-03-29 19:42 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            deckPicker.updateDeckList();
Sounds reasonable to me - you're much more involved in the change, but I agree.

2021-03-29 20:16 UTC, david-allison-1 reviewed
More detailed feedback and thoughts

2021-03-29 20:16 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
>              if (isReview) {
Just noting: `isReview` and `isBury` are mutually exclusive, so this is fine

2021-03-29 20:16 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        String undoBuryString = getResources().getString(R.string.menu_bury_card).toLowerCase();
I've had a look through here, and the code style that you copied seems convoluted. 

`toLowerCase` would need a call to `getResources` to ensure that it's correct.

I feel the code would look better along the lines of:

```java
String undoReviewString = Collection.DismissType.REVIEW.getString(getResources());
String undoBuryString = Collection.DismissType.BURY_CARD.getString(getResources());
```

What do you think?

2021-03-29 20:16 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        final boolean isBury = undoBuryString.equals(getCol().undoName(getResources()));
Is it intentional that you're checking for bury card, and not for bury note?

2021-03-29 20:31 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        String undoBuryString = getResources().getString(R.string.menu_bury_card).toLowerCase();
Yes, that's much cleaner and safer! I'll take a deeper look at my changes and make some improvements

2021-03-29 22:45 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        String undoBuryString = getResources().getString(R.string.menu_bury_card).toLowerCase();
A question: It seems that the code can be made more understandable by simply using ```DismissType```'s enum types (such as BURY_CARD) for comparisons instead of fetching the resource strings associated with them. This will require the use of ```Collection.java```'s undoType() method and may require a null check for the object returned by that method. Is this a better approach?

2021-03-29 22:51 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        final boolean isBury = undoBuryString.equals(getCol().undoName(getResources()));
I didn't explore that part. I will check for bury note and I'll see if any other operations have similar problems.

2021-03-29 23:05 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        String undoBuryString = getResources().getString(R.string.menu_bury_card).toLowerCase();
If it works, then definitely better than my suggestion, I'd presumed there was a reason why this didn't happen in the first place.

2021-03-29 23:17 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        String undoBuryString = getResources().getString(R.string.menu_bury_card).toLowerCase();
Just one more thing: The only issue I can see with that approach is that the Collection.java's ```public DismissType undoType()``` method has a ```@VisibleForTesting``` annotation which gives a warning when I call it from DeckPicker.java. Can I just suppress "VisibleForTesting" in this case?

2021-03-29 23:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        String undoBuryString = getResources().getString(R.string.menu_bury_card).toLowerCase();
I'd say remove the `@VisibleForTesting` (but do check with the author)

@Arthur-Milchior, would you agree?

2021-03-30 00:44 UTC, Arthur-Milchior reviewed
Hi,

Thanks a lot for correcting problems that were here for quite some time. I honestly didn't even know we had this problem, for some reason it's only on phone, not on tablet (the reason being that tablets use the StudioOptionsFragment class to undo)

As David suggested, the problem is actually bigger than just burying. I have comment through the code to give more details. I'm really sorry as I fear I'm asking you to redo a big part of the work.

And now, for some more general comments.


Please, in your commit title, use a short sentence that explain alone what you're doing.
When someone looks at code history, they won't know what "#4312" is. "Undo Bury Card" is not clear either because you don't know what was the problem.

It would be nice if you could amend your commit instead of adding one commit on top of another. Because I usually read commit by commit, hoping to find atomic commits. Here, I see plenty of typos in first commit and don't yet know that actually they are corrected in later commits. If it's too complex right now, at least I'd like you to indicate in a comment that this PR must be squashed (that is, it will be a single commit) so that I know I don't have to look at each change one after the other

2021-03-30 00:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        return new UndoTaskListener(isReview, isBury,this);
`isBury, this` please add a space

2021-03-30 00:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        public UndoTaskListener(boolean isReview, boolean isBury, DeckPicker deckPicker) {
I'm surprised that burying need to be a special case and not suspend. Usually, both cases are very similar. Did you check with suspending whether you have a similar problem ? If so it would be nice to correct both problem simultaneously

2021-03-30 00:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        String undoBuryString = getResources().getString(R.string.menu_bury_card).toLowerCase();
Why do you want undoType instead of undoName ? If you want a string to display, it seems more relevant

2021-03-30 00:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        final boolean isBury = undoBuryString.equals(getCol().undoName(getResources()));
The real question is: is there anything you can undo in the deck picker that do not require to open the deck picker ?
If you look at `StudioOptionFragment.java`, the class used on tablets, you'll see that the deck picker is always reopened, and I believe it is the correct behavior. There is probably a way to use the same codes in both classes

2021-03-30 05:52 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        return new UndoTaskListener(isReview, isBury,this);
Got it! I'll squash the commits, and I'll amend any further commits

2021-03-30 06:04 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        String undoBuryString = getResources().getString(R.string.menu_bury_card).toLowerCase();
UndoName was only used for deciding how the UI behaves (opening Reviewer, updating the card count) when different DismissTypes are undone. So, undoName is compared with ```DismissType```s by getting the resource string associated with each DismissType, the res string for undoName, and comparing them. Since it's only being used for comparison, I figured comparing the enum types (such as BURY_CARD, SUSPEND_NOTE) would be cleaner.

2021-03-30 06:13 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        String undoBuryString = getResources().getString(R.string.menu_bury_card).toLowerCase();
Also, the only reason this comparison was necessary is because I set out to alter the behavior of Bury Card only and keep it the same for others since that is what Issue #4312 mentioned. Since this is a good opportunity to ensure the other Undo Options are working as expected, can you tell me what's the expected behavior for each one (Undo Last Review, Undo Bury Card/Note, Undo Suspend Card/Note)? I know they are the same for Undo Last Review and Undo Bury (both navigate to the study screen with the card). If I know what's the desired behavior for each, I can reduce the comparisons to only what's necessary.

2021-03-30 06:37 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        final boolean isBury = undoBuryString.equals(getCol().undoName(getResources()));
Do you mean 'is there anything you can undo in the deck picker that does not require to open the _reviewer_'? I think you're saying that if you undo anything in the deck picker, the reviewer (study screen where the card and 3 buttons for Easy Medium Hard) are shown. Am I right?

2021-03-31 02:29 UTC, Arthur-Milchior commented
Note that in #8408 I remove DismissType. It's not yet merged and clearly up to discussion, but I really believe it's not something that is still relevant in our codebase

2021-03-31 02:29 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        return new UndoTaskListener(isReview, isBury,this);
Thanks a lot. That'll really help

2021-03-31 02:34 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        String undoBuryString = getResources().getString(R.string.menu_bury_card).toLowerCase();
Actually, the method `Undoable::name` is not called anymore. That's really strange, I am pretty sure it was useful when I added it, it was used to decide what to display in the menu/alt text.
Thanks for noting it

2021-03-31 02:35 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        final boolean isBury = undoBuryString.equals(getCol().undoName(getResources()));
Almost.
When you open the reviewer back, you show the queston again, not the answer. I don't even think we currently have a way to tell the reviewer to start with the answer.

Appart from that, yes, that's what I meant. I believe that action you can undo will require opening the reviewer. If you use a tablet (or just an emulator with a large screen), you'll see that it is already current behaviour

2021-03-31 15:29 UTC, farjadilyas commented
Since the desired behavior is to open the Reviewer & ```DismissType``` may possibly be removed, I'm going to go ahead and remove the checks (```isBury```, ```isReview```) before opening the reviewer. This will ensure that all undo actions simply result in a call to ```deckPicker.openReviewer()```. Does this sound good?

2021-04-01 02:56 UTC, Arthur-Milchior commented
Sounds good.
If you can also check whether it would made sens to share the same undo function here and in the other class it would be great too

2021-04-02 01:42 UTC, farjadilyas commented
> Sounds good.
> If you can also check whether it would made sens to share the same undo function here and in the other class it would be great too

Yes, ```undo()``` in both DeckPicker and Reviewer (inherited from AbstractFlashcardView) will be the same except for the listeners being passed to ```TaskManager.launchCollectionTask()```. ```undoAvailable()``` calls ```getCol()``` which needs to be called from an AnkiActivity's context. Hence, I think the best way to use the same method for both is to have a static method that takes AnkiActivity as a parameter and uses it for the ```undoAvailable()``` check before launching ```CollectionTask.Undo```. I'm not too sure where this static method should be. I think it could be in AbstractFlashcardView since generally, this is responsible for undoing actions on cards. Does this sound like the right approach?

2021-04-04 13:36 UTC, mikehardy commented
No pressure - I'm just scanning the list and labeling this "waiting for feedback" which means the next activity is from the submitter, not the reviewers. This turned in to something much bigger than expected! That's software I guess :sweat_smile:

2021-04-08 19:02 UTC, farjadilyas commented
Please ignore these commits! I'll squash & work on this tomorrow

2021-04-08 21:22 UTC, farjadilyas commented
> > Please ignore these commits! I'll squash & work on this tomorrow
> 
> Just FYI: We avoid marge commits in the history

Yes, I understand. I accidentally merged instead of rebasing. I've reset it since no one else is using this branch.

2021-04-08 21:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        TaskManager.launchCollectionTask(new CollectionTask.Undo(), undoTaskListener());
@mikehardy @Arthur-Milchior Is this what we want here. The code looks good, but I'm not sure if I undo "mark note/change deck", I'd want to be back into the reviewer 

Maybe it should be a property on the class?

![image](https://user-images.githubusercontent.com/62114487/114099152-442beb00-98ba-11eb-99e5-277d39169ea5.png)

2021-04-29 07:48 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            deckPicker.hideProgressBar();
Any reason to hide after Timbering instead of before? I don't see the point here

2021-04-29 07:48 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        TaskManager.launchCollectionTask(new CollectionTask.Undo(), undoTaskListener());
You're so right that actually, `UndoMarkNoteMulti::undo` return `null` and `UndoChangeDeckMulti::undo` always return null, which means that no card has to be opened in the reviewer.

What should be done, and what is already done in the reviewer, is to get the card to display in `onProgressUpdate` and then open the reviewer with this card first. That's actually what's done upstream, reopening with the card related to the cancellation.

2021-04-29 07:48 UTC, Arthur-Milchior reviewed
Sorry for the delay in the answer. Can you please let us know whether you still intends to work on it?
If so, I'm sorry, you'll also have to rebase

2021-05-22 11:57 UTC, Arthur-Milchior commented
Any news ? Do you still intend to work on this issue?

2021-05-22 12:02 UTC, farjadilyas commented
@Arthur-Milchior Yes! Sorry I've been a bit busy lately. I'll continue this in a couple of days!

2021-05-22 14:27 UTC, mikehardy commented
I may be unaware - this is just a location / culture question - but is it holidays over there right now? Plus graduation and COVID stuff just from regional proximity to India plus maybe in Pakistan itself. Just curious if everyone in general has low time availability right now as the activity in the repo has slowed dramatically even for folks that seemed excited in general vs just excited for google summer of code (which is natural too, of course). Cheers Farjad

2021-05-22 14:45 UTC, farjadilyas commented
@mikehardy In Pakistan it's probably because of how close exam season is for all university students. Universities are about to reopen in a week or two now that COVID cases are dropping in Pakistan (they've been online for a couple of months now). So everyone here is gearing up for that. On top of that, this time stuff is heavier than usual since universities here had to delay this semester due to a COVID wave at the start of 2021. I expect everyone here should have more free time by the start of July though!

2021-05-22 14:59 UTC, mikehardy commented
That all makes a lot of sense, and of course school is and should always be the priority along with taking time for yourself and family. Thanks a bunch for sharing the situation and good luck in your exams!

2021-05-28 16:55 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            deckPicker.hideProgressBar();
Nope, I'll change this back

2021-05-28 16:56 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        TaskManager.launchCollectionTask(new CollectionTask.Undo(), undoTaskListener());
Got it! :)

2021-05-28 17:16 UTC, farjadilyas commented
We were going in a different direction in this PR before Arthur pointed out [here ](https://github.com/ankidroid/Anki-Android/pull/8384#discussion_r622811482) that we can use ```UndoAction```'s ```undo()``` which returns null if a card isn't supposed to be opened in the Reviewer, and returns the relevant card otherwise. This is then received in ```actualOnProgressUpdate()``` and can be used to open the Reviewer for the given card. 

I'll rebase and make this change.

2021-05-31 02:38 UTC, mikehardy commented
@farjadilyas I'm really looking forward to working with you and I apologize I haven't had a chance to review this PR yet. I have been so focused on user support and the release-2.15 stabilization that I just haven't had time yet. But! We will have a very nice + stable codebase that was released just prior to all the work for this summer so I will have time soon and we will have a good base to work on as we move forward. Cheers

2021-06-05 03:45 UTC, Arthur-Milchior requested changes
One little change about NotNull, and then it should be good.
However, I'd prefer you first tell us:
* whether you did the test again with this new version
* what tests you did exactly

If you could add unit tests, that would be wonderful. But honestly, I could not do them myself, I don't understand robolectric enough.

Thanks for working with me on it and accepting my suggestion in any case. I'm biased since you accepted to follow my suggestion, but I have a feeling that it leads to code simpler than the first version of it, and I like that very much as a reviewer

2021-06-05 03:45 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +import org.jetbrains.annotations.NotNull;
We use 
`import androidx.annotation.NonNull;`

Normally this should have been catch by linting, that's strange it did compile.

2021-06-06 20:04 UTC, farjadilyas commented
> One little change about NotNull, and then it should be good.
> However, I'd prefer you first tell us:
> 
> * whether you did the test again with this new version
> * what tests you did exactly
> 
> If you could add unit tests, that would be wonderful. But honestly, I could not do them myself, I don't understand robolectric enough.
> 
> Thanks for working with me on it and accepting my suggestion in any case. I'm biased since you accepted to follow my suggestion, but I have a feeling that it leads to code simpler than the first version of it, and I like that very much as a reviewer

@Arthur-Milchior 

### Testing done so far
I tested the functionality on my phone. I carried out the available actions from DeckPicker & Card Browser. I then attempted to undo them via the '3-dot' Menu at the top right of Deck Picker & it behaves as expected. The UndoActions which send a Card in ```doProgress()``` result in the Reviewer being opened. So as long as the classes extending UndoAction only return a card if the action being undone should lead to the Reviewer being opened, the DeckPicker works as expected!

I agree that we should have Unit Tests for this to ensure it works correctly under many permutations (like undoing an action done from Card Browser).

### One problem
I found a problem upon reviewing, after your comment. Undoing an action that doesn't open the Reviewer from DeckPicker, doesn't update the deck's counts. I didn't catch this before since the Undo Actions available in DeckPicker were opening the Reviewer & the counts are recalculated in onResume(). To reproduce, do any action that isn't supposed to open the Reviewer (only possible from Card Browser), return to Deck Picker, and undo it. 

According to the documentation, DeckPicker's ```updateDeckList()``` is the appropriate function to call in order to recalculate Deck counts after an Undo Action is completed.

### Next Steps

I'll fix the Deck Count update issue & write Unit Tests for Undo Actions!

One question: Card Browser doesn't check if it should open the Reviewer after undoing an action. Most Undo Actions available from Card Browser aren't supposed to open the Reviewer and they don't. However, the Reposition, Reschedule & Reset Actions send a Card in ```doProgress()```. This means that undoing the same action from Card Browser doesn't open the Reviewer, but it does when you go back to DeckPicker and Undo it from there. Is this the desired behavior or should we make it Card Browser consistent with how DeckPicker handles opening the Reviewer after an Undo Action?

2021-06-06 22:28 UTC, Arthur-Milchior commented
If you do an edit in the browser, and then cancelling it open the reviewer, it's a bug. 
Is it something that can be done with the current version of the application?

I think at some point we should rework undo from scratch and document exactly the details of what is expected. For example, the fact that undo become impossible if you change the selected deck may not be very intuitive. If you have the undo button, it is not clear what you'll undo. If you do a serie of undo, it is a real trouble.

2021-06-07 00:34 UTC, farjadilyas commented
Since this can only happen if you make an edit in the Browser, then go back to DeckPicker and then undo that edit, it cannot be done in the master & current release since both applications only open the reviewer after Undo Last Review. So for any other type of Undo, it won't open the Reviewer.

In the version of this PR, since we fixed the DeckPicker issue, now this can happen. It can be fixed by calling ```getCol().clearUndo()``` while navigating from the Card Browser to the Deck Picker.

I agree with you. Documenting the expected behavior & then reworking it would be ideal! I'll have plenty of time in a month's time so I'd be happy to take that up!

2021-06-07 22:36 UTC, Arthur-Milchior commented
I believe clearing makes more sens here. You can’t see what you undo, and offering undo without feedback seems frightening..
Maybe undo should always open a toast actually to confirm what was done

2021-06-27 13:31 UTC, mikehardy commented
I like this idea:

> Maybe undo should always open a toast actually to confirm what was done

In general I always prefer positive confirmation to the user of an action if possible

2021-06-27 14:45 UTC, mikehardy commented
This appears to need a conflict fix + re-push but it sounds like this must be done first before it is ready for review again:

>  It can be fixed by calling getCol().clearUndo() while navigating from the Card Browser to the Deck Picker.

I would argue for any sort of explicit toasts or re-work to be a separate PR so that the progress here may be ingested as an incremental improvement

2021-07-03 02:10 UTC, Arthur-Milchior commented
Please note you should use androidx's nonnull and not jetbrains NotNull. this is the reason the check failed

2021-09-12 15:38 UTC, closed without merging