Toolbar night mode support
ankidroid/Anki-Android pull request #8385
Opened 2021-03-29 19:20 UTC by prateek-singh-3212

## Pull Request template

## Purpose / Description
 Added toolbar support for night mode.

## Fixes
 Fixes issue #7832 

## Approach

-  I changed the toolbar background color to light grey or dark grey depending on the theme.

-  I have created a method that changes the icon color to white or black depending on the theme.

-  I have created a new drawable file to add a custom tag in the toolbar icon (White Color) which I am using in dark and black mode.

## How Has This Been Tested?
Tested on Samsung Galaxy M51, android 11 (Samsung One UI 3.1)
 
## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-03-29 19:31 UTC, david-allison-1 requested changes
Looks good! minor questions

* Could you rebase this to remove the merge commits from the commit history
* Could you include screenshots from the 4 themes in the main post

2021-03-29 19:31 UTC, david-allison-1 commented on .idea/codeStyles/Project.xml
> -          <package name="java.util" alias="false" withSubpackages="false" />
Could you revert this, not relevant to the PR

2021-03-29 19:31 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java
> +        for (int i=0; i < this.mToolbar.getChildCount(); i++) {
```suggestion
        for (int i = 0; i < this.mToolbar.getChildCount(); i++) {
```

2021-03-29 19:31 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +            editText.setBackgroundColor(Themes.getColorFromAttr(NoteEditor.this,R.attr.editTextBackgroundColor));
```suggestion
            editText.setBackgroundColor(Themes.getColorFromAttr(NoteEditor.this, R.attr.editTextBackgroundColor));
```

2021-03-29 19:31 UTC, david-allison-1 commented on AnkiDroid/src/main/res/drawable/ic_add_toolbar_white_icon.xml
> +    android:width="24dp"
Are you able to use a tint here, rather than cloning the icon?

2021-03-29 19:41 UTC, prateek-singh-3212 commented on .idea/codeStyles/Project.xml
> -          <package name="java.util" alias="false" withSubpackages="false" />
>     * in the

Yeah, Sure

2021-03-29 19:54 UTC, prateek-singh-3212 commented on .idea/codeStyles/Project.xml
> -          <package name="java.util" alias="false" withSubpackages="false" />
Yeah, Sure. Sorry for the inconvenience

2021-03-29 20:20 UTC, mrudultora commented
Hi, @prateek-singh-3212 There are merge conflicts. Your fork is 95 commits behind the main repo. Please resolve them. Also, make your fork even with upstream.

2021-03-30 12:01 UTC, closed without merging

2021-03-30 13:45 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/drawable/ic_add_toolbar_white_icon.xml
> +    android:width="24dp"
Yeah, it's working fine with the tint.