NF: Introduce List assertion
ankidroid/Anki-Android pull request #8410
Opened 2021-03-31 05:02 UTC by Arthur-Milchior

This way, it uses same tools as array equality and will show descriptive message about the difference

2021-04-01 15:33 UTC, david-allison-1 approved these changes
I'm fairly ambivalent about this, a Hamcrest matcher (or documentation on using an existing matcher) would likely be better from a readability standpoint. 

The syntax here seems verbose and copying the arrays is a negligible perf hit.

But, it's not incorrect, tests still pass.

2021-04-01 16:06 UTC, Arthur-Milchior commented
> I'm fairly ambivalent about this, a Hamcrest matcher (or documentation on using an existing matcher) would likely be better from a readability standpoint.

Readability of what ?

I find that current error messages are hard to read, because it shows the whole list and not where the equality break. I changed this so that the error message we get shows either the change in length or the first difference in the list. So debugging is easier.

What do you think in terme of documentation ? I don't understand what could be done. However, I'd be fine creating a better test rule as long as it gives detailed explanation of the difference

> The syntax here seems verbose and copying the arrays is a negligible perf hit.

`ListUtil.assertListEquals` can be replaced by `assertListEquals` with a static import. Done in new version

2021-04-01 16:13 UTC, david-allison-1 commented
> Readability of what ?

of the code: `assertThat(expectedList, is(actualList), "message");` strikes me as much more readable, but this is personal preference.

> I find that current error messages are hard to read, because it shows the whole list and not where the equality break. I changed this so that the error message we get shows either the change in length or the first difference in the list. So debugging is easier.

Agreed

> What do you think in terme of documentation ? I don't understand what could be done. However, I'd be fine creating a better test rule as long as it gives detailed explanation of the difference

In terms of better explaining the testing mechanisms that we have: If we have Hamcrest's `is` or `contains` and they do the job, then we'd want to document that, as it's a very common operation, and the Hamcrest documentation is a little too general for my taste.

> `ListUtil.assertListEquals` can be replaced by `assertListEquals` with a static import. Done in new version

Definitely a good change

2021-04-01 16:20 UTC, Arthur-Milchior commented
I rewrote it slightly so that it's even less verbose. It takes a sequence of expected values instead of a list

2021-04-01 16:25 UTC, david-allison-1 requested changes

2021-04-01 16:25 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/utils/ListUtil.java
> +    public static <T>  void assertListEquals(List<T> actuals,
I find this to be less readable. We're also going against the convention of `expected, actual`

2021-04-01 16:41 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/utils/ListUtil.java
> +    public static <T>  void assertListEquals(List<T> actuals,
Then we can remove the second commit and just keep the first

2021-04-01 16:50 UTC, david-allison-1 approved these changes
Comments still stand, no point in bikeshedding on this

2021-04-01 17:11 UTC, Arthur-Milchior commented
i'm fine with adding comments in the wiki page related to testing.

2021-04-01 22:09 UTC, mikehardy requested changes
I have found array error messages difficult in the past as well
This solution seems fine - I think the actual readability of the in-test code is fine in this version and if it produces better error messages, okay by me

I left nitpick comments though :)

2021-04-01 22:09 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/utils/ListUtil.java
> +package com.ichi2.utils;
missing copyright header

2021-04-01 22:09 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssert.java
> +import com.ichi2.utils.ListUtil;
if you import static you don't need the general import I think

2021-04-01 22:09 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java
> +import com.ichi2.utils.ListUtil;
if you import static you don't need the general import I think

2021-04-01 22:09 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
> +import org.junit.Test;
I think all 3 imports added here are unneded?

2021-04-01 22:53 UTC, Arthur-Milchior commented
Done

2021-04-01 23:11 UTC, mikehardy requested changes

2021-04-01 23:11 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
> +import org.junit.Test;
@Arthur-Milchior I think this one is still unused, but other than that it's all patched up

2021-04-02 18:43 UTC, Arthur-Milchior commented
done

2021-04-02 18:56 UTC, mikehardy approved these changes
good to go!

2021-04-02 19:20 UTC, merged