Preventing OR search query from bypassing RestrictOnDeck
ankidroid/Anki-Android pull request #8414
Opened 2021-03-31 15:11 UTC by ritvij14

## Pull Request template

## Purpose / Description
Till now if we opened the CardBrowser and tried searching cards using OR, we see that the results from the left-hand side of the OR are from the selected deck, but the right-hand side is searching all decks.

## Fixes
Fixes #8027 
## Approach
This adds `()` in the search string by default. This way the query is always enclosed in brackets and RestrictOnDeck is not bypassed.

## How Has This Been Tested?

Tested it on my Redmi Note 8 pro

![image](https://user-images.githubusercontent.com/51456744/113167444-5b872a80-9261-11eb-81c0-baa44eda9689.jpeg)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have performed a self-review of your own code

2021-03-31 15:20 UTC, ritvij14 commented
In the test case, I selected Deck 1, and the search, without brackets, would return 2 cards instead of 1.

Part of output on running the test-
```
V/Finder: Search query 'deck:"Deck 1" (world or hello)' is compiled as 'select c.id from cards c, notes n where c.nid=n.id and ((c.did in (1596783600460) or c.odid in (1596783600460)) and (((n.sfld like ? escape '\' or n.flds like ? escape '\')) or ((n.sfld like ? escape '\' or n.flds like ? escape '\'))))  ORDER BY n.sfld COLLATE NOCASE, c.ord'.
D/BackendV1Impl: Rust: fullQueryProto select c.id from cards c, notes n where c.nid=n.id and ((c.did in (1596783600460) or c.odid in (1596783600460)) and (((n.sfld like ? escape '\' or n.flds like ? escape '\')) or ((n.sfld like ? escape '\' or n.flds like ? escape '\'))))  ORDER BY n.sfld COLLATE NOCASE, c.ord
D/BackendV1Impl: cancelCurrentProtoQuery
D/CollectionTask$SearchCards: The search found 1 cards
```

2021-03-31 20:52 UTC, Arthur-Milchior reviewed
I believe you don't need such a complex logic. You can always add parenthesis, even if you don't add "deck:" in the search it will still works

2021-03-31 20:52 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +            if (mSearchTerms.charAt(5) == '\"') {
I doubt it work. If you search "FOO deck:Bar" then the first character is not at position 5.

the othe problem (which is not due), is that if you search for `"a card containing deck: literally"` then it'll detect this as a deck: query while it is actually a literal search. Probably worth making an issue of it

2021-03-31 20:52 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> -            searchText = mSearchTerms;
please copy the search term. If the `mSearchTerm` change while the function run, that would potentially create bug

2021-03-31 20:52 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +    public void checkSearchString() {
So this test was failing before? It would be nice to put a small comment with the bug report number

2021-04-01 05:04 UTC, ritvij14 commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +    public void checkSearchString() {
No, it wasn't failing before. I had to update the string because I have selected "Deck 1" before starting my search, so if I had kept hello before OR, it would pass anyway, as the query for a particular deck works fine for the left of the OR but not the right, so I changed the string.

2021-04-01 05:04 UTC, ritvij14 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> -            searchText = mSearchTerms;
Ok got it

2021-04-01 05:06 UTC, ritvij14 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +            if (mSearchTerms.charAt(5) == '\"') {
Ok understood. So for now I should just remove this part of logic and simply add parenthesis all around the string even if it has deck right?

2021-04-01 05:07 UTC, ritvij14 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +            if (mSearchTerms.charAt(5) == '\"') {
Ok understood. So for now I should just remove this part of logic and simply add parenthesis all around the string even if it has "deck:" right?

2021-04-01 18:23 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +            if (mSearchTerms.charAt(5) == '\"') {
I believe it would make sens.

2021-04-01 18:26 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +    public void checkSearchString() {
Sorry, I was not clear. 

I meant, if you write this test on top of master and nothing else, does the test succeed.

What we want and need is a test that fails without your changes and succeed with

2021-04-01 18:35 UTC, ritvij14 commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +    public void checkSearchString() {
Oh ok, I got it. Yes, the test is failing if we just use the master code. In that case, 2 cards are being returned.

And ok I will add the issue number on top of the test case in a comment.

2021-04-03 11:59 UTC, david-allison-1 requested changes
Looks good to me, a few slight nitpicks on tests

2021-04-03 11:59 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +        c1.flush();
I don't think you need this line

2021-04-03 11:59 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +        CardBrowser cardBrowser = getBrowserWithNoNewCards();
Could you assert that the card browser has a selected deck here

2021-04-03 11:59 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +        assertThat("tagged card should be returned", cardBrowser.getCardCount(), is(1));
```suggestion
        assertThat("Results should only be from the selected deck", cardBrowser.getCardCount(), is(1));
```
```suggestion
        assertThat("tagged card should be returned", cardBrowser.getCardCount(), is(1));
```

2021-04-03 12:20 UTC, ritvij14 commented
Changes done.

2021-04-03 12:23 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +        Card c1 = addNoteUsingBasicModel("Hello", "John").firstCard();
```suggestion
       addNoteUsingBasicModel("Hello", "John");
```

2021-04-03 12:23 UTC, david-allison-1 approved these changes
One nitpick, but looks good to me!

2021-04-03 12:53 UTC, david-allison-1 commented
Note to maintainers: squash merge

2021-04-03 13:05 UTC, mikehardy approved these changes
Nice! With added test support even +1

2021-04-03 13:29 UTC, merged

2021-05-09 15:13 UTC, mikehardy commented
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!