Fix#8379
ankidroid/Anki-Android pull request #8432
Opened 2021-04-02 13:56 UTC by Prashant830

## Pull Request template

## Purpose / Description
[Bug] Send Bug Report - Can't re-submit if cancelled

## Fixes
Fixes #8379 

## Approach
fix bug at exceptionReportItem method at HelpDialog.java class.

## How Has This Been Tested?
|               | |
|---------------|-|
|Device         |Infinix hot 7 |
|Android Version| Android 9 |

## Short Video

https://user-images.githubusercontent.com/72181295/113421678-260d4900-93e9-11eb-8a12-48a6c63bf080.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-02 14:38 UTC, david-allison-1 requested changes
Thanks for the PR! This solves the problem by removing the rate limiting, which isn't what we're after

After the problem is solved, could you confirm that the issue is fixed by following these steps:

* Send exception report with preference set to "ask"
* Press "cancel" on the report
* Send exception report
* The dialog should be shown again

2021-04-02 14:38 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                lastClickMap.put(lastClick, currentTimestamp);
You're not setting `lastClickTimeStamp` any more - this removes rate limiting on the dialog

2021-04-02 14:38 UTC, david-allison-1 commented on AnkiDroid/src/main/res/drawable/ic_baseline_lock_24.xml
> +    android:height="24dp"
These changes aren't relevant, could you remove them from the PR via a rebase

2021-04-15 23:16 UTC, mikehardy commented
Closing with preference for #8629 to get this done for 2.15

2021-04-15 23:16 UTC, closed without merging