fix :Deck ordering differs from Anki Desktop
ankidroid/Anki-Android pull request #8439
Opened 2021-04-02 18:36 UTC by Prince-kushwaha

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes :#8397

## Approach
Add an class -AbstractDeckTreeComparator which sort the mCurrentDeckList in DeckAdapter 
mCurrentDeckList is list of item for Recycler view 
## How Has This Been Tested?
Android Device:Redmiy3
API :29

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-02 18:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
> +        Collections.sort(mCurrentDeckList, new AbstractDeckTreeComparator());
Why are you sorting in `getItemCount()`? This will likely add a lot of overhead, as it's a method that's likely to be called a lot

2021-04-02 18:49 UTC, david-allison-1 requested changes
If this is the solution that you want to take, could you add some regression tests

2021-04-02 18:49 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractDeckTreeComparator.java
> +            String [] mNameComponentsO1 =o1.getmNameComponents();
```suggestion
            String[] mNameComponentsO1 = o1.getmNameComponents();
```

2021-04-02 18:49 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractDeckTreeComparator.java
> +                return result;
This doesn't seem to be correct

2021-04-03 14:25 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractDeckTreeComparator.java
> +                return result;
it is correct i test it

2021-04-03 14:31 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
> +        Collections.sort(mCurrentDeckList, new AbstractDeckTreeComparator());
Becouse getItemcount() method called everytime when recyclerview started or new Deck is added and Collections.sort method sort the mCurrentDeckList

2021-04-03 14:36 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractDeckTreeComparator.java
> +                return result;
What about decks which are nested more than 1 level?

2021-04-07 05:44 UTC, Prince-kushwaha commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractDeckTreeComparator.java
> +                return result;
it is solved

2021-04-07 11:11 UTC, david-allison-1 requested changes

2021-04-07 11:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
> +        Collections.sort(mCurrentDeckList, new AbstractDeckTreeComparator());
There should be a more appropriate method

2021-04-07 11:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractDeckTreeComparator.java
> +            return Integer.compare(mNameComponentsO1.length, mNameComponetsO2.length);
Can you comment here explaining the logic, and confirm the behaviour matches Anki Desktop

2021-04-11 08:33 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
> +        Collections.sort(mCurrentDeckList, new AbstractDeckTreeComparator());
It will be better to do this inside `onBindViewHolder()`.

2021-06-08 18:15 UTC, david-allison-1 commented
@Prince-kushwaha Hi, just following up, this is fine to be merged after feedback is addressed. Do you think you'll have time to work on this in the near future?

2021-06-16 04:08 UTC, Prince-kushwaha commented
@david-allison-1 yes i work

2021-09-05 15:38 UTC, closed without merging