[Feature] JavaScript Addons Support
ankidroid/Anki-Android pull request #8440
Opened 2021-04-02 21:55 UTC by infinyte7

## Pull Request template

## Purpose / Description
Using AnkiDroid JS API a deck can be extended to implement features like progress bar or custom card layouts. But it requires user to manually add the ```html/css/js``` to card templates. This is implementation for a way to inject code to all deck templates when addons get activated.

## Fixes
Fixes #7959 

## Approach
1. Download addons from https://www.npmjs.com/search?q=keywords:ankidroid-js-addon inside the app
2. In app there are implementation to check for valid addons for AnkiDroid
It will check following string in latest package.json
```
{
    "name": "ankidroid-js-addon-progress-bar",
    "version": "1.0.0",
    "author": "https://github.com/infinyte7",
    "homepage": "https://github.com/infinyte7/Anki-Custom-Card-Layout",
    "ankidroid_js_api": "0.0.1",
    "addon_type": "reviewer",
    "keywords": ["ankidroid-js-addon"]
}
```
There isValidPackageJson boolean function will check for above values if present then the addons is valid.

3. The ```enabled``` addons' ```index.js``` content wrapped in ```<script>``` tag will be added to ```fillFlashCard()``` in ```AbstractFlashcardViewer.java```

I have also documented it here https://github.com/infinyte7/ankidroid-js-addon

There are two types of addon ```reviewer``` and ```note_editor```. In this PR, reviewer addon is implemented.

<img src="https://user-images.githubusercontent.com/12841290/103460959-aaeab700-4d55-11eb-9226-2bec784b9871.gif" height=400/>

## How Has This Been Tested?
Tested on emulator 

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
https://developer.android.com/guide/topics/ui/layout/recyclerview

## Checklist
_Please, go through these checks before submitting the PR._

- [ x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x ] You have commented your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code
- [ x ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

2021-04-02 22:31 UTC, infinyte7 commented
How it will works?
1. Users will navigate to Addons Browser Activity
2. There are four button in options menu
     - Reviewer Addons
     - Note editor Addons  (Separate PR)
     - Import Addons
     - Get More Addons
3. When user click `Import Addons`
It will ask to paste `npm i ankidroid-js-addons...` that is available on npm package on npmjs.com
4. When user click `Download` it will download the addons to `AnkiDroid/addons` folder
5. There are implementation for checking valid npm package
```
{
    "name": "ankidroid-js-addon-progress-bar",
    "version": "1.0.0",
    "author": "https://github.com/infinyte7",
    "homepage": "https://github.com/infinyte7/Anki-Custom-Card-Layout",
    "ankidroid_js_api": "0.0.1",
    "addon_type": "reviewer",
    "keywords": ["ankidroid-js-addon"]
}
```
If above found in package.json on npmjs registry then then it will download the package.json and get tarball url.
6. Here package with `.tgz` extension will be downloaded to `Downloads` folder and extracted then copied to `AnkiDroid/addons`  folder
7. The addons will be listed on the Addons Browser screen
8. Users have option to enable, update and delete addons.
9. When users enable the addons, the `index.js` file of that addons will be added to card during review. The addons have full access to AnkiDroid JS API.

**Demo of progress bar**
<img src="https://user-images.githubusercontent.com/12841290/113458708-c1340c00-9445-11eb-85bb-985aba56cb2a.gif" height=500></img>

2021-04-02 22:34 UTC, david-allison-1 reviewed
This is a partial review, sorry, I'm tired and unable to go into depth right now. It's on me to re-review.

It looks good from a brief scan! And it'll be great to get this in. I think a few areas could do with refactoring for readability, which will make a future structural review easier.

My main thought from a design/maintenance perspective is that there should be more classes, in order to explain NPMs structure to a developer who is unfamiliar with how packages work, and what they contain, and insulating a developer from implementation details, showing at a high level what the algorithms aim to accomplish.

There's a lot of logic in a few of the methods, and it'd be better to break some of them up

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/build.gradle
> +    implementation 'org.rauschig:jarchivelib:1.1.0'
nit: move to where other `implementation` directives are

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/src/main/AndroidManifest.xml
> +                android:name="android.support.PARENT_ACTIVITY"
Is this still needed?

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            Timber.d("map values %s",entry.getKey() + ": " + entry.getValue().toString());
```suggestion
            Timber.d("map values %s: %s", entry.getKey(), entry.getValue());
```

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                    Timber.e(e, "AbstractFlashcardViewer::IOException");
```suggestion
                    Timber.w(e, "AbstractFlashcardViewer::IOException");
```

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        String mainJsFile = null;
I think this would be better in a separate class

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            if (entry.getKey().contains("reviewer_addon") && entry.getValue().toString().equals("enabled")) {
Invert this `if`, and `continue;` if it's false

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                    if (finalAddonPath.exists()) {
Again: invert the if to reduce nesting

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        String currentAnkiDroidDirectory = CollectionHelper.getCurrentAnkiDroidDirectory(this);
This method is too long, and too nested, I've added some small suggestions, but some things could be better encapsulated in a class.

I'll follow up from this in another review

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        final String cardContent = mCardContent + jsAddonContent;
efficiency: I think we'll be able to move this to improve the performance hit

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonModel.java
> +    private String name;
Naming conventions
```java
    private String sName;
```

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsAdapter.java
> +                UIUtils.showThemedToast(context, context.getString(R.string.disabled) + " " + addonModel.getName(), true);
Don't concatenate strings, this implies an order, ask for another translation

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsAdapter.java
> +        if (preferences.getString(addonModel.getType() + "_addon:" + addonModel.getName(), "disabled").equals("enabled")) {
extract: `"_addon:" + addonModel.getName()` into a variable - makes the code easier to read

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsAdapter.java
> +        if (preferences.getString(addonModel.getType() + "_addon:" + addonModel.getName(), "disabled").equals("enabled")) {
Is there a reason that you're using a string here instead of a boolean?

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsAdapter.java
> +                editor.apply();
```suggestion
                editor.putString(addonModel.getType() + "_addon:" + addonModel.getName(), "enabled").apply();
```

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsAdapter.java
> +            if (holder.addonActivate.isChecked()) {
This method can be simplified further

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsAdapter.java
> +        @SuppressLint("UseSwitchCompatOrMaterialCode")
What is this error? Why is it suppressed?

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/AddonsBrowserTest.java
> +public class AddonsBrowserTest extends RobolectricTest {
This shouldn't need to exist, or it should, but should have tests

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +        Themes.setThemeLegacy(this);
Is this needed?

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +            if (DownloadManager.ACTION_DOWNLOAD_COMPLETE.equals(action)) {
See if you can invert some of these if statements to reduce nesting

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +        if (dir.isDirectory()) {
invert the if

2021-04-02 22:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                }
```suggestion
                if (child.isDirectory()) {
                    deleteDirectory(child);
                }
                child.delete();
```

2021-04-02 22:42 UTC, infinyte7 commented
Thanks, I will update it with suggested changes.

2021-04-03 07:30 UTC, infinyte7 commented
>My main thought from a design/maintenance perspective is that there should be more classes, in order to explain NPMs structure to a developer who is unfamiliar with how packages work, and what they contain, and insulating a developer from implementation details, showing at a high level what the algorithms aim to accomplish.

I am implementing this so all npm related function should be in one class.

2021-04-03 13:04 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonModel.java
> +    private String sName;
m, not s: https://github.com/ankidroid/Anki-Android/wiki/Code-style
```java
    private String sName;
```

2021-04-03 13:32 UTC, david-allison-1 reviewed
Much nicer - second round, mostly structuring again

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +            Cursor cursor = downloadManager.query(query);
Wrap this in try with resources

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +            if (cursor.moveToFirst()) {
invert if to reduce nesting

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                }
is there another case here? what should happen? I feel there should be an `else`, not an `else if`

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                if (DownloadManager.STATUS_SUCCESSFUL == cursor.getInt(columnIndex)) {
Invert if and return

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                    String tarballPath = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
Deprecated in Android Q

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                    File addonsDir = new File(addonsHomeDir, addonName);
Security: if addon name contains `../`, can the user write to an arbitrary path?

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +        String[] children = dir.list();
Likely better as `.listFiles()`?

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                    BufferedReader br = new BufferedReader(new FileReader(addonsContentFile));
Use `try with resources`

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                    br.close();
Extract this to a method, check to see if we have a utility method which does this already

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                if (addonsContentFile.exists()) {
invert the if

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.java
> +                get(CardTemplateBrowserAppearanceEditor.class, ActivityList::intentForCardTemplateBrowserAppearanceEditor)
I believe this is still necessary and shouldn't have been reverted

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                            + "/" + Uri.parse(addonName).getPath() + ".tgz";
`Uri.parse(addonName).getPath()` can fail, what happens?

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +    private String AnkiDroidJsAPI = "0.0.1";
Shouldn't these refer to the same values as `AbstractFlashcardViewer`, maybe move to a constants class

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +    private String[] addonTypes = {"reviewer", "note_editor"};
We only handle the reviewer here

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +            openUrl(Uri.parse(getResources().getString(R.string.ankidroid_js_addon_npm_search_url)));
I think:

```java
            openUrl(Uri.parse(getString(R.string.ankidroid_js_addon_npm_search_url)));
```

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +        downloadDialog = new Dialog(this);
This seems like a nonstandard way to handle a dialog

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +        listAddonsFromDir(addonTypes[0]);
I think

```suggestion
        listAddonsFromDir(listAddonType);
```

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +    private MenuItem mInstallAddon;
These variables can be local to the function

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +    private long queueId;
This appears unused

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                if (isValidAddonPackage(jsonObject)) {
If it's invalid, do we want to let the user know?

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                Timber.d("Addons:%s", file.getName());
```suggestion
                Timber.d("Addons: %s", file.getName());
```

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                }
I would consider extracting to `AddonModel.tryParse(jsonObject)`

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +            }
I don't know what this does without context (what is `addonsMessageLayout`?)

Consider:
* Including a comment as to why this happens, 
* Extract to a named method where the method name gives context
* Renaming the variable to be more descriptive

```suggestion
            addonsMessageLayout.setVisibility(addonsNames.isEmpty() ? View.VISIBLE : View.GONE);
```

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                        editor.apply();
It'd also be useful to extract this string `addonModel.getType() + "_addon:" + addonModel.getName()` into the AddonModel class

```suggestion
                        preferences.edit().remove(addonModel.getType() + "_addon:" + addonModel.getName()).apply();
```

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                        addonsListRecyclerView.getAdapter().notifyDataSetChanged();
Do all 3 need to be called?

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +            AlertDialog deleteAlert = alertBuilder.create();
I think `alertBuilder` has a `.show()` method

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +        String addonHomepage = jsonObject.optString("homepage", "");
(I might have posted this elsewhere) - this, and a lot of this method's functionality would likely be better inside the class

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +            Timber.e(e.getLocalizedMessage());
```suggestion
            Timber.w(e, e.getLocalizedMessage());
```

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +                    fos.flush();
We should have util methods which do this already if you search the codebase:

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +                    is = response.body().byteStream();
Try with resources

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +                    Timber.e(e.getLocalizedMessage());
```suggestion
                    Timber.w(e, e.getLocalizedMessage());
```

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +
Use shared utils, and try with resources

2021-04-03 13:32 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.java
> +import com.ichi2.anki.AddonsBrowser;
Necessary?

2021-04-03 13:47 UTC, infinyte7 commented
Thanks again, I will update it.

2021-04-03 19:37 UTC, david-allison-1 commented
Just to note; the idea of inverting `if`s is to remove the horizontal nesting: this means that someone reading the code has less to think about, it's a mechanically simple change which makes the code a lot more readable I saw that one change was reverted, and I might have had a comment misunderstood.

As a general rule: prefer flatter functions

2021-04-03 19:42 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +            }
This is extension icon with message below on Addons Browser first screen when no addons available.

2021-04-03 19:42 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +        listAddonsFromDir(addonTypes[0]);
The list addon type is for 
* Reviewer 
* Note editor
So when user click reviewer it shows reviewer addons in recycler view else note editor addons

2021-04-03 19:42 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +    private String AnkiDroidJsAPI = "0.0.1";
I will create separate PR to add API constant from every .java files

2021-04-03 19:42 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                    br.close();
I tried it.
Utils.convertStreamToString(is) not used because in that method `content.append('\n')` not present so it make js code not to work
I used `Utils.convertStreamToString(is)` for reading json file and there are no problem to them.

2021-04-03 19:53 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                if (isValidAddonPackage(jsonObject)) {
I tried to showtoast but didn't work I got error.
`
Can't toast on a thread that has not called Looper.prepare()
`

2021-04-03 19:57 UTC, infinyte7 commented
I will again make more simple implementation.

2021-04-03 20:16 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +        listAddonsFromDir(addonTypes[0]);
I have removed the note editor options from menu. Now only `reviewer`.

2021-04-04 08:31 UTC, infinyte7 commented
Implementation:
I have tried to called toast and progress bar method but it crashes AnkiDroid, so I have implemented static method for progress bar and showing toast. It is working.
Also cleaned and restructured code a little  bit.

It become faster and simpler than my original implementation. 
Thanks

2021-04-04 09:27 UTC, david-allison-1 requested changes
We're performing a lot of `new File()` on user input. 

This is unsafe in Java: https://stackoverflow.com/a/44496536/13121290

I believe this is the same in Android. Could you test?

----

Code style: https://github.com/ankidroid/Anki-Android/wiki/Code-style#non-public-non-static-field-names-should-start-with-m

2021-04-04 09:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +        getSupportActionBar().setTitle(getString(R.string.reviewer_addons));
Might as well move this to where the other `getSupportActionBar()` methods are called

2021-04-04 09:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                    npmAddonName = npmAddonName.replace("npm i", "");
Use a substring with `"npm i".length()`; `replace` will replace all instances within the string

2021-04-04 09:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                npmAddonName = npmAddonName.replaceAll("\u00A0", "");
TODO: Check that this is what you want

```suggestion
                npmAddonName = StringUtil.strip(npmAddonName);
```

2021-04-04 09:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +    static Activity addonsBrowserActivity = null;
This leaks a context, let's remove it and try another design

2021-04-04 09:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +    private static RecyclerView addonsListRecyclerView;
I don't think any of these variables should be static. It will probably involve making methods non-static

2021-04-04 09:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +            File directory = new File(String.valueOf(addonsHomeDir));
TODO: I don't think you need this

```suggestion
            File directory = addonsHomeDir;
```

2021-04-04 09:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                File addonsPackageJson = new File(addonsPackageDir, "package.json");
I think this will work

```suggestion
                File addonsPackageJson = new File(file, "package/package.json");
```

2021-04-04 09:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                    if (addonModel.getType().equals(addonType)) {
Extract this logic in the `if` statement into `AddonModel`

2021-04-04 09:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +        hideProgressBarStatic();
Move this outside the method and into a `try...finally` on the one caller that doesn't have it already.

2021-04-04 09:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +        if (!dir.isDirectory()) {
This would be useful to extract to a `Util` class, it's almost the same as `BaclupManager.removeDir`

2021-04-04 09:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +            if (entry.getKey().contains("reviewer_addon") && entry.getValue().equals(true)) {
Instead of having multiple preferences, a `StringSet` might be the way to go.

We might also want to store this data in `MetaDB`, as it's per-device

2021-04-04 09:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +            if (entry.getKey().contains("reviewer_addon") && entry.getValue().equals(true)) {
Invert the if for readability

2021-04-04 09:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                        br.close();
Extract, or use a Util method

2021-04-04 09:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +                listAddonType = jsonObject.optString("addon_type", "");
Extract these accessors to the class as well

2021-04-04 09:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +            hideProgressBarStatic();
Do you want this in the `catch`, or in a `finally`?

2021-04-04 09:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +            Timber.e(e.getLocalizedMessage());
```suggestion
            Timber.w(e);
```

2021-04-04 09:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +            InputStream is = new FileInputStream(addonsFiles);
Does this ned a Try with resources?

2021-04-04 09:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +        String url = "https://registry.npmjs.org/" + npmAddonName + "/latest";
Extract to constant

2021-04-04 13:47 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                    npmAddonName = npmAddonName.replace("npm i", "");
I didn't understand. Please provide more info.

2021-04-04 13:47 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                npmAddonName = npmAddonName.replaceAll("\u00A0", "");
It didn't worked

2021-04-04 13:48 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +            InputStream is = new FileInputStream(addonsFiles);
Yes, It shows for file not found exception.

2021-04-04 13:51 UTC, infinyte7 commented
I have remove static implementation. It shows progressbar and toast. But when addons extracted to addons folder, I find difficult to refresh recyclerview with new addons or call `listAddonsFromDir`.

2021-04-04 14:35 UTC, david-allison-1 reviewed
Much nicer - this is a brief review due to time constraints, will get more structural points on the next round

My main worry is that `StringJoiner` doesn't seem to fix the underlying issue of someone passing in `../`

2021-04-04 14:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        if (AnkiDroidApp.getSharedPrefs(this).getBoolean("javascript_addons_support", false)) {
Move this into the `mCardTemplate` class - it's designed to speed up rendering the template, and the addons can be permanently inserted into the string at the correct position so the string needs less allocations

2021-04-04 14:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                        editor.putStringSet("enabledAddons", enabledAddonSet).apply();
Implementers choice - handling the `StringSet/Preferences` might be better off in a class to reduce the code here

2021-04-04 14:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +            if (!s.contains("reviewer_addon")) {
Do you need this? Could you have one set for reviewer addons, and one for note editor?

This would also allow you to simplify later code

2021-04-04 14:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +            BufferedReader br = new BufferedReader(new FileReader(addonsContentFile));
Use a try with resources, extract the file reading further out

2021-04-04 14:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +        if (addonsContentFile.exists()) {
invert the if

2021-04-04 14:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +    private String addonType = "reviewer";
`static final` since it's constant, you'll need a rename inside Android Studio

```java
    private static final String ADDON_TYPE = "reviewer";
```

2021-04-04 14:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +        showProgressBar();
Where has the `hideProgressBar()` gone?

2021-04-04 14:50 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +        showProgressBar();
I am implementing it.

2021-04-04 14:51 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +            if (!s.contains("reviewer_addon")) {
I am implementing for separate addons. It will be better to handle separately.

2021-04-04 14:51 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                        editor.putStringSet("enabledAddons", enabledAddonSet).apply();
To be implemented.

2021-04-04 14:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +            if (!s.contains("reviewer_addon")) {
OK. I was thinking one preference key per list of addons would make things much more simpler

2021-04-04 14:52 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        if (AnkiDroidApp.getSharedPrefs(this).getBoolean("javascript_addons_support", false)) {
I will implement this.

2021-04-04 14:57 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +            if (!s.contains("reviewer_addon")) {
Yes, I understood. I am implementing this.
`
Set<String> reviewerEnabledAddonSet = preferences.getStringSet("reviewerAddonKey", new HashSet<String>());
Set<String> noteEditorEnabledAddonSet = preferences.getStringSet("noteEditorEnabledAddonSet", new HashSet<String>());

`

2021-04-04 17:25 UTC, infinyte7 commented
For file path, i tried using `../` but it shows error. Here only user supplied value is `addonDir` but it also id for npm package and only possible to change if user want to edit it.
It is not possible to put `../` when downloaded from npmjs as it is unique id. 
```
                StringJoiner joinedPath = new StringJoiner("/")
                        .add(currentAnkiDroidDirectory)
                        .add("addons")
                        .add(addonDir)
                        .add("package")
                        .add("index.js");
```
![1](https://user-images.githubusercontent.com/12841290/113516543-69181980-95ad-11eb-9f53-feef7a531f0c.png)

2021-04-04 18:10 UTC, infinyte7 commented
It become more simpler than previous and I have noticed performance improved a lot after using `CardTemplate`
Thanks

2021-04-04 21:23 UTC, infinyte7 commented
Should I move just this one function to AddonsBrowser instead of AddonsNpmUtility ?
```
public void getLatestPackageJson(String npmAddonName) {
        showProgressBar();

        String url = getString(R.string.ankidroid_js_addon_npm_registry, npmAddonName);

        OkHttpClient client = new OkHttpClient();

        Request request = new Request.Builder()
                .url(url)
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                Timber.e("js addon %s", e.toString());
            }

            @Override
            public void onResponse(Call call, Response response) {
                try {
                    String strResponse = response.body().string();
                    runOnUiThread(() -> parseJsonData(strResponse, npmAddonName));
                } catch (IOException | NullPointerException e) {
                    Timber.e(e.getLocalizedMessage());
                }
            }
        });

    }
```

Because I need to call `listAddonsFromDir` to update recyclerview after addons download/extracted to addons folder. But that needs to change to static, which to change of many variables to static.
But changing `getLatestPackageJson` to AddonBrowser, it become very easy to call `listAddonsFromDir` also no static call.
I tried some other approach but didn't work.

2021-04-06 12:14 UTC, david-allison-1 commented
>         new Thread(() -> {
> 
>             runOnUiThread(() -> {
>                 String res = fetchThroughHttp(url);
>                 Timber.d("res:: %s", res);
>             });
> 
>         });

You need to call `thread.start()`

2021-04-06 12:15 UTC, david-allison-1 commented
> Should I move just this one function to AddonsBrowser instead of AddonsNpmUtility ?
> 
> ```java
> public void getLatestPackageJson(String npmAddonName) {
>         showProgressBar();
> 
>         String url = getString(R.string.ankidroid_js_addon_npm_registry, npmAddonName);
> 
>         OkHttpClient client = new OkHttpClient();
> 
>         Request request = new Request.Builder()
>                 .url(url)
>                 .build();
> 
>         client.newCall(request).enqueue(new Callback() {
>             @Override
>             public void onFailure(Call call, IOException e) {
>                 Timber.e("js addon %s", e.toString());
>             }
> 
>             @Override
>             public void onResponse(Call call, Response response) {
>                 try {
>                         String strResponse = response.body().string();
>                         npmUtility.parseJsonData(strResponse, npmAddonName);
> 
>                         //runOnUiThread(() -> {
>                             //listAddonsFromDir(addonType);
>                         //});
> 
>                 } catch (IOException | NullPointerException e) {
>                     Timber.e(e.getLocalizedMessage());
>                 }
>             }
>         });
> 
>     }
> ```
> 
> Because I need to call `listAddonsFromDir` to update recyclerview after addons download/extracted to addons folder. But that needs to change to static, which to change of many variables to static.
> But changing `getLatestPackageJson` to AddonBrowser, it become very easy to call `listAddonsFromDir` also no static call.
> I tried some other approach but didn't work.
> 
> I tried `fetchThroughHttp` from HttpFetcher but got following errors.

You can pass in a regular method as a callback, you shouldn't need a static method

2021-04-06 12:16 UTC, david-allison-1 commented
> For file path, i tried using `../` but it shows error on package because from there `../` can be input. Here only user supplied value is `addonDir` and also it is id for npm package and only possible to change if user manually want to edit it after install.
> It is not possible to put `../` when downloaded from npmjs as it is unique id.

Our code shouldn't be trusting external conventions of third parties for security - we should ensure explicitly that the path(s) are rooted where we expect them to be rooted.

2021-04-06 12:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        mCardContent = mCardTemplate.render(content, style, cardClass, addons);
We can do better - addons is effectively a constant, so we can load it/insert it into `mCardTemplate`

2021-04-06 12:34 UTC, david-allison-1 reviewed
@mikehardy @Arthur-Milchior 

Opinions/reviews would be great

Main current question: what happens if the user is offline or if the internet fails, are the errors understandable?

2021-04-06 12:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonModel.java
> +        if (!addonModel.getJsApiVersion().equals(AnkiDroidJsAPI) && jsAddonKeywordsPresent) {
Could you add a comment to explain why we have this check

2021-04-06 12:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonModel.java
> +        if (!addonModel.getName().isEmpty() && !addonModel.getVersion().isEmpty() && !addonModel.getDeveloper().isEmpty() && !addonModel.getHomepage().isEmpty()) {
`addonModel.isValid()` perhaps?

2021-04-06 12:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonModel.java
> +        editor.putStringSet(reviewerAddonKey, newStrSet).apply();
Can't you edit `reviewerEnabledAddonSet` without copying the set?

```suggestion
        Set<String> reviewerEnabledAddonSet = preferences.getStringSet(reviewerAddonKey, new HashSet<String>());

        if (remove) {
            reviewerEnabledAddonSet.remove(addonName);
        } else {
            reviewerEnabledAddonSet.add(addonName);
        }

        preferences.edit().putStringSet(reviewerAddonKey, newStrSet).apply();
```

2021-04-06 12:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +            Timber.d("json::%s", strResponse);
```suggestion
            Timber.v("json::%s", strResponse);
```

2021-04-06 12:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +                String tarballUrl = dist.get("tarball").toString();
Can this be done?
```suggestion
                String tarballUrl = dist.getString("tarball");
```

2021-04-06 12:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonModel.java
> +        if (addonModel == null) {
Move this check closer to where `addonModel` is created

2021-04-06 12:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                        response.close();
Do you need these if the call if not successful?

2021-04-06 12:57 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonModel.java
> +        editor.putStringSet(reviewerAddonKey, newStrSet).apply();
I tried but didn't worked so I found solution here https://stackoverflow.com/questions/19949182/android-sharedpreferences-string-set-some-items-are-removed-after-app-restart/19949833
It needs to copy. Also tried above but preferences not working.

2021-04-06 13:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonModel.java
> +        Set<String> reviewerEnabledAddonSet = preferences.getStringSet(reviewerAddonKey, new HashSet<String>());
Could you add a reference to SO, showing that you can't modify the set

2021-04-06 13:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonModel.java
> +        editor.putStringSet(reviewerAddonKey, newStrSet).apply();
Okay, little cleaner:

```suggestion
        Set<String> newStrSet = new HashSet<String>(reviewerEnabledAddonSet);
        
        if (remove) {
            newStrSet.remove(addonName);
        } else {
            newStrSet.add(addonName);
        }

        preferences.edit().putStringSet(reviewerAddonKey, newStrSet).apply();
```

2021-04-06 13:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                    npmAddonName = npmAddonName.replaceAll("npm i", "");
We only want a substring, not replacing all instances

```suggestion
                    npmAddonName = npmAddonName.substring("npm i".length());
```

2021-04-06 13:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                if (npmAddonName.startsWith("npm i")) {
This might be useful as `npmAddonName = StringUtil.trimPrefix("npm i")`

2021-04-06 13:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                npmAddonName = npmAddonName.replaceAll("\u00A0", "");
Best to get a unit test in to ensure we're fixing the "expected bad" input

2021-04-06 13:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                // TODO
flagging todo

2021-04-06 13:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +        br.close();
This needs a try with resources, or use an existing utility method if one exists

2021-04-06 13:11 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/addon_install_from_npm.xml
> +        android:text="@string/sync_conflict_remote"
I'd define another string with a `comment=` for "download"

2021-04-06 13:16 UTC, david-allison-1 commented
I'd like to step back and see what the others have to say: I think it's in a much much better place now and it'll be easier to discuss big picture things (if any need to be). @mikehardy @Arthur-Milchior

Main thoughts:
* Security - mostly on the `new File`
* Error handling - addon execution - this is a big one, as we'll be taking on a massive support hit if we get this wrong
* Logging - are we logging an appropriate amount to diagnose issues
* Error handling - addon download
* Documentation and simplification of the process - can we improve this? Do we need to show a download screen
* Privacy - I think we're OK here, but it's best to get explicit confirmation before opening NPM

2021-04-06 13:29 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        mCardContent = mCardTemplate.render(content, style, cardClass, addons);
Should I create `static final String addons` in class? or other method.

2021-04-06 13:31 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +        br.close();
There exist utility method but `content.append('\n');` not present and it makes js code to not work. So I created above.
I will add it to `try...catch`

2021-04-06 13:33 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        mCardContent = mCardTemplate.render(content, style, cardClass, addons);
There's no need for another variable - we can mutate the variables inside the class that we have already:

* One of the variables inside `CardTemplate` will have `::addons::`
* add a `setAddons()` method (or do it in the constructor if this is viable)
* Loop through each variable, and replace `::addons::` with the content provided

Now, we have the same number of concatenations per card, and we've included the addon content

2021-04-06 13:34 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +                        response.close();
I viewed that in logcat so I implemented above code.
```
WARNING: A connection to https://npmjs.com/ was leaked. Did you forget to close a response body?
```

2021-04-06 13:58 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        mCardContent = mCardTemplate.render(content, style, cardClass, addons);
Thanks, I am implementing it.

2021-04-06 13:59 UTC, infinyte7 commented
> > Because I need to call `listAddonsFromDir` to update recyclerview after addons download/extracted to addons folder. But that needs to change to static, which to change of many variables to static.
> > But changing `getLatestPackageJson` to AddonBrowser, it become very easy to call `listAddonsFromDir` also no static call.
> > I tried some other approach but didn't work.
> > I tried `fetchThroughHttp` from HttpFetcher but got following errors.
> 
> You can pass in a regular method as a callback, you shouldn't need a static method

I need help in creating the call back function. I tried but it seems not easy for me.

2021-04-06 14:14 UTC, david-allison-1 commented
> I need help in creating the call back function. I tried but it seems not easy for me.

What is the method signature that you need? Typically `Runnable` for 0 args, 0 return value

2021-04-06 15:01 UTC, infinyte7 commented
void with one args

2021-04-06 15:03 UTC, david-allison-1 commented
> void with one args

`Consumer<T>`, or write an interface with the given method signature.

2021-04-06 15:29 UTC, infinyte7 commented
Okay, I am implementing it.

2021-04-06 17:00 UTC, infinyte7 commented
I have implemented using `Runnable` and it give the expected result.
Thanks

2021-04-06 17:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +    public void getPackageJson(String npmAddonName, Runnable runnable) {
Explain when the runnable is run in the documentation

2021-04-13 11:56 UTC, david-allison-1 commented
I think the next stage would be to produce an addon that crashes for local testing - I want to reduce the blame for the app crashing/breaking as much as possible, and this will allow us to test mitigation strategies

2021-04-13 13:35 UTC, infinyte7 commented
Okay, I will implement tests for crashing app. 
Thanks

2021-04-15 03:45 UTC, david-allison-1 commented
@infinyte7 If you rebase this onto the latest master, then `gradlew lintRelease`/rebuild, the IDE will pick up variable naming issues

2021-04-15 07:08 UTC, infinyte7 commented
I have implemented the test in `CardTemplateTest.java` and `AddonModelTest.java`. I get the help from `AnalyticsTest.java` for prefs but still getting error. Also for json I viewed existing implemented code. But build failed to pass.

2021-04-16 11:58 UTC, TarekkMA commented
The issue with the tests is that there are 2 dependencies that are static. `AnkiDroidApp` and `AddonsNpmUtility`, thanks to mockito we can mock static methods with ease using one of the following syntaxes

##### Using Try Resources Syntax
```java
 try (MockedStatic<AnkiDroidApp> utilities = Mockito.mockStatic(AnkiDroidApp.class)) {
    utilities.when(() -> AnkiDroidApp.getSharedPrefs(mMockContext)).thenReturn(mMockSharedPreferences)
}
```
##### Manually closing them
```java
private MockedStatic<AnkiDroidApp> mMockAnkiDroidApp;
....
mMockAnkiDroidApp = Mockito.mockStatic(AnkiDroidApp.class);
....
mMockAnkiDroidApp.when(() -> AnkiDroidApp.getSharedPrefs(mMockContext)).thenReturn(mMockSharedPreferences);
....
mMockAnkiDroidApp.close();
```

And the two stub methods we need will look something like this:
```java
mMockAnkiDroidApp.when(() -> AnkiDroidApp.getSharedPrefs(mMockContext)).thenReturn(mMockSharedPreferences);
mMockAddonsNpmUtility.when(() -> AddonsNpmUtility.getEnabledAddonsContent(mMockContext)).thenReturn("addon");
```

2021-04-16 12:19 UTC, infinyte7 commented
Thanks @TarekkMA

2021-04-16 12:36 UTC, infinyte7 commented
@david-allison-1 Now There are two test implemented AddonModel and CardTemplate. What would be next step?

2021-04-16 12:39 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +    private final String mADDON_TYPE = "reviewer";
```suggestion
    private static final String ADDON_TYPE = "reviewer";
```

2021-04-16 12:48 UTC, david-allison-1 reviewed
Things that worry me that would be useful in tests

* CardViewer - what happens with an addon throwing JS errors
* What happens if a download fails, or the user is not connected to the internet
* How does a user uninstall an addon
* If an addon is placed on disk in a corrupt form, can the user delete it? 
* What if there's a mismatch between the preferences and what's in the directory?

2021-04-16 12:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +    private static final String ADDON_TYPE = "reviewer";
This seems duplicated - make one public

2021-04-16 12:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +            InputStream is = new FileInputStream(addonsFiles);
Use a try-with-resources block here, not just a try-catch

2021-04-16 12:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +            jsonObject = new JSONObject(stream);
You can return here

2021-04-16 12:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +        return jsonObject;
Return null if we return early

2021-04-16 12:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +    public static JSONObject packageJsonReader(File addonsFiles) {
Mark this as Nullable

2021-04-16 12:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +        for (String addonDir : reviewerEnabledAddonSet) {
Need to define what happens here (ideally with a test) if an addon is defined in preferences, but doesn't exist on the disk

2021-04-16 12:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +            FileReader fileReader = new FileReader(addonsContentFile);
Needs a few "Try with resources" blocks

2021-04-16 12:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +            while ((line = br.readLine()) != null) {
There's likely a better method for this

2021-04-16 12:48 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/AddonModelTest.java
> +    private static final String progrssBarAddonPackageJson = "{\n" +
Would make more sense to have this as a file and load it into a string - Java idioms would make diffing this string difficult

2021-04-16 16:44 UTC, infinyte7 commented
> CardViewer - what happens with an addon throwing JS errors

Added a test

> What happens if a download fails, or the user is not connected to the internet

Implemented method for checking if connected to internet

> How does a user uninstall an addon

There is options in info popup to update and delete addon, when clicked on addon

> If an addon is placed on disk in a corrupt form, can the user delete it?

I have tested manually by enabling three addons in dir enable and delete. It removes key from StringSet prefs if addon does not exist on disk.

> What if there's a mismatch between the preferences and what's in the directory?

Here the file downloaded from npmjs so every package have unique name. So, no duplicate in file name. 
`index.js` directly read from `AnkiDroid/addons/some-js-addon/package/index.js` if folder does not exists, then enabled prefs removed for that addon and read operation continue to next addon. 

The structures of addons will be
```
AnkiDroid
   ↳ addons
          ↳ progressbar-addon
                  ↳package
                        ↳ index.js
 
          ↳ card-info-addon
                  ↳ package
                        ↳ index.js
 
          ↳ button-addon
                  ↳ package
                        ↳ index.js
       .....
       .....
   collection.media
    ...
    ...
```

2021-06-15 18:00 UTC, david-allison-1 commented
Let's get this moving. I don't want to be the only one on this review.

@mikehardy @Arthur-Milchior When you guys have time, could you do an initial scan of the PR? 

@infinyte7 Do you have time now to work on additional feedback, or is it close to exam time for you?

2021-06-15 18:12 UTC, infinyte7 commented
There are three exams in this month. So, I will be able to contribute to this PR from first week in July.

Reviewing big PR takes time.
So, I have decided to re-submit PR in small size. So, that will be easier to review. I will use the same code in that PR.

PR 1
Implementation of downloaing addon from npm.org (.tgz file) with test 

PR 2
Install, update and delete the of addons files (Recyclerview showing list of addons) with test

PR 3
Adding contents of addon data to reviewer with test

The current PR needs some improvement and test case. But this PR is also complete. If this PR is reviewed then that will also be good.

2021-06-15 18:19 UTC, david-allison-1 reviewed
I've gone through about half again. So much better than it was. 

My main questions: 
* how do we handle JS errors and display to the user that it's an addon problem? Can we improve the UX (and possibly suggest disabling an addon)?
   * Can we attribute an error to a specific addon (or a clash between addons)?
* How are breaking changes handled, from both the AnkiDroid and Addon side?

2021-06-15 18:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonModel.java
> +        if (!addonModel.getJsApiVersion().equals(AnkiDroidJsAPI) || !jsAddonKeywordsPresent) {
How is compatibility handled (AnkiDroid too new, or addon too new)? Could this be documented.

Is it possible to set this to a range?

2021-06-15 18:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonModel.java
> +     * @param preferences SharedPreferences
The javadocs don't explain what this method does, especially `reviewerAddonKey`, which seems to be the most important aspect

2021-06-15 18:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsAdapter.java
> +        for (String s : reviewerEnabledAddonSet) {
Could this be simplified to `if (reviewerEnabledAddonSet.contains(addonModel.getName())`

2021-06-15 18:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsAdapter.java
> +        String reviewerAddonKey = AddonModel.getReviewerAddonKey();
I feel referring to the constant here would be more readable

2021-06-15 18:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +@SuppressWarnings("deprecation")
Typically it's best to mark the specific methods and add a reference to the GitHub issue if you suppress deprecation

2021-06-15 18:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsBrowser.java
> +        mNpmUtility = new AddonsNpmUtility(AddonsBrowser.this, this);
Typically you can inline this to the variable as long as you're not doing work in the `AddonsNpmUtility` constructor

2021-06-15 18:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +    public static final String ADDON_TYPE = "reviewer";
This will need a more descriptive name `ADDON_TYPE_REVIEWER`

2021-06-15 18:36 UTC, infinyte7 commented
> how do we handle JS errors and display to the user that it's an addon problem? Can we improve the UX (and possibly suggest disabling an addon)?

All content of js file read then added to reviewer (Same as adding js code to card template). So, any error in js, that will be in webview. It needs to track the error origin. Like in which file errors occur then notify user that the error occur in the js file of addons and needs to update/delete addons. It can be implemented.

> Can we attribute an error to a specific addon (or a clash between addons)?

The clash between can happened. But from AnkiDroid side it will/may not catch. Because lets say two addons have same variable name then AnkiDroid will not tell there is errors. (This will make AnkiDroid more like js interpreter. So, I think it will be left to addon developer to choose/decide/develop). But if this features needed then I may need to find solution for it.

> How are breaking changes handled, from both the AnkiDroid and Addon side?

The breaking changes handled using version of AnkiDroid JS API. If version greater than or matched to current api version then it will work with that version of AnkiDroid and JS API otherwise addons js content will not be added to reviewer.

2021-06-15 19:06 UTC, david-allison-1 commented
Thanks, if these are going to be massive changes, I'd much rather have a quick discussion with all the maintainers to make sure that this is going in the right direction. I don't want to be asking for busy work, and I want to see this in

2021-06-15 19:17 UTC, infinyte7 commented
I think catching error is easier because in webview if errors occur the Android webview's `onConsoleMessage` may tell file and line number of errors and that info will be used to notify users as well as addon developers.

2021-06-15 19:27 UTC, david-allison-1 commented
Is it possible to move each addon to a file, rather than concatenating the scripts into a `<script>` tag, this would allow rough identification of where a problem occurs?

2021-06-15 19:40 UTC, infinyte7 commented
yes, that will be better implementation. Instead of reading content of file appending in `<script>::addons::</script>`
This will be better `<script src="../addons/some-addons/package/index.js">`. It will help in identify error more easily.

2021-06-15 20:13 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonsNpmUtility.java
> +    public static String getEnabledAddonsContent(Context context) {
TODO:
Instead read and append to <script>::addons::</script>
Do this `<script src="../addons/some-addons/package/index.js"></script>`

It is easy to catch the bugs and also reduce complexity of this PR.

2021-09-17 05:04 UTC, infinyte7 commented
The same PR in kotlin already created.

2021-09-17 05:04 UTC, closed without merging