Fixes #7679 Lookup button enabled/disabled depending on Lookup Dictionary preference
ankidroid/Anki-Android pull request #8441
Opened 2021-04-02 22:10 UTC by Mohaned-Elfeky

## Pull Request template

## Purpose / Description
The Lookup button was not used so added it to the App bar buttons and made it visible/invisible depending on it's preference .

known issues: 
1-preferences doesn't load unless user opens the settings page.
2-the preferences argument in src\main\java\com\ichi2\anki\reviewer\ActionButtonStatus.java\setup doesn't return value(always returns default value).
 
## Fixes
Fixes #7679

## Approach
_How does this change address the problem?_
fixed the problem of the lookup button not being used and linked it to it's functionality and fixed it's visibility in the App bar menu.

## How Has This Been Tested?

Changed the lookup dictionary setting to different values and observed the visibility of the lookup button.

## Checklist
_Please, go through these checks before submitting the PR._

- [ x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x ] You have commented your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-02 23:10 UTC, david-allison-1 commented
Test failure: 

```
com.ichi2.anki.reviewer.ActionButtonStatusTest > allCustomButtonsCanBeDisabled FAILED
    java.lang.AssertionError: Each button in the Action Bar must be modifiable in Preferences - Reviewer - App Bar Buttons
    Expected: iterable over ["customButtonShowHideWhiteboard", "customButtonDelete", "customButtonSelectTts", "customButtonScheduleCard", "customButtonCardInfo", "customButtonFlag", "customButtonUndo", "customButtonClearWhiteboard", "customButtonToggleMicToolBar", "customButtonMarkCard", "customButtonTags", "customButtonSuspend", "customButtonEnableWhiteboard", "customButtonWhiteboardPenColor", "customButtonReplay", "customButtonDeckOptions", "customButtonSaveWhiteboard", "customButtonAddCard", "customButtonEditCard", "customButtonBury", "customButtonLookup"] in any order
         but: Not matched: "customButtonSearchDictionary"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at com.ichi2.anki.reviewer.ActionButtonStatusTest.allCustomButtonsCanBeDisabled(ActionButtonStatusTest.java:47)
```

It seems you're using `customButtonLookup` in the settings, and `customButtonSearchDictionary` in the code

2021-04-02 23:35 UTC, Mohaned-Elfeky commented
> Test failure:
> 
> ```
> com.ichi2.anki.reviewer.ActionButtonStatusTest > allCustomButtonsCanBeDisabled FAILED
>     java.lang.AssertionError: Each button in the Action Bar must be modifiable in Preferences - Reviewer - App Bar Buttons
>     Expected: iterable over ["customButtonShowHideWhiteboard", "customButtonDelete", "customButtonSelectTts", "customButtonScheduleCard", "customButtonCardInfo", "customButtonFlag", "customButtonUndo", "customButtonClearWhiteboard", "customButtonToggleMicToolBar", "customButtonMarkCard", "customButtonTags", "customButtonSuspend", "customButtonEnableWhiteboard", "customButtonWhiteboardPenColor", "customButtonReplay", "customButtonDeckOptions", "customButtonSaveWhiteboard", "customButtonAddCard", "customButtonEditCard", "customButtonBury", "customButtonLookup"] in any order
>          but: Not matched: "customButtonSearchDictionary"
>         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
>         at com.ichi2.anki.reviewer.ActionButtonStatusTest.allCustomButtonsCanBeDisabled(ActionButtonStatusTest.java:47)
> ```
> 
> It seems you're using `customButtonLookup` in the settings, and `customButtonSearchDictionary` in the code

fixed it

2021-04-02 23:35 UTC, david-allison-1 requested changes
Full review

2021-04-02 23:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java
> +        setupButton(preferences, R.id.action_search_dictionary, "customButtonSearchDictionary", Lookup.isAvailable() ? SHOW_AS_ACTION_IF_ROOM : MENU_DISABLED);
I mentioned in the previous review: this only sets the default, you want to disable the button if Lookup is disabled.

2021-04-02 23:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            UIUtils.showThemedToast(AbstractFlashcardViewer.this, getApplicationContext().getString(R.string.dialog_clipboard_empty) , false);
Why was this changed?

2021-04-02 23:37 UTC, Mohaned-Elfeky commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            UIUtils.showThemedToast(AbstractFlashcardViewer.this, getApplicationContext().getString(R.string.dialog_clipboard_empty) , false);
the selectAndCopyText method is not working and was marked with deprecation

2021-04-02 23:38 UTC, Mohaned-Elfeky commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java
> +        setupButton(preferences, R.id.action_search_dictionary, "customButtonSearchDictionary", Lookup.isAvailable() ? SHOW_AS_ACTION_IF_ROOM : MENU_DISABLED);
can you suggest in which file this change can be made?

2021-04-02 23:39 UTC, Mohaned-Elfeky commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java
> +        setupButton(preferences, R.id.action_search_dictionary, "customButtonSearchDictionary", Lookup.isAvailable() ? SHOW_AS_ACTION_IF_ROOM : MENU_DISABLED);
and I tested it this preference argument always returns the default value for all buttons

2021-04-02 23:40 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            UIUtils.showThemedToast(AbstractFlashcardViewer.this, getApplicationContext().getString(R.string.dialog_clipboard_empty) , false);
Could you raise it as a separate (linked) issue rather than remove the functionality?

2021-04-02 23:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java
> +        setupButton(preferences, R.id.action_search_dictionary, "customButtonSearchDictionary", Lookup.isAvailable() ? SHOW_AS_ACTION_IF_ROOM : MENU_DISABLED);
That's likely you were using the wrong variable, - the cause of the broken test, it should work now

2021-04-02 23:42 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java
> +        setupButton(preferences, R.id.action_search_dictionary, "customButtonSearchDictionary", Lookup.isAvailable() ? SHOW_AS_ACTION_IF_ROOM : MENU_DISABLED);
> can you suggest in which file this change can be made?

`ActionButtonStatus.java`

Inline `setupButton` for that call, and use a constant value if `Lookup.isAvailable()` is false

2021-04-02 23:42 UTC, Mohaned-Elfeky commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            UIUtils.showThemedToast(AbstractFlashcardViewer.this, getApplicationContext().getString(R.string.dialog_clipboard_empty) , false);
ok I will revert the change and raise another issue

2021-04-10 04:06 UTC, Mohaned-Elfeky commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java
> +        setupButton(preferences, R.id.action_search_dictionary, "customButtonSearchDictionary", Lookup.isAvailable() ? SHOW_AS_ACTION_IF_ROOM : MENU_DISABLED);
fixed it

2021-04-10 15:50 UTC, david-allison-1 reviewed
Thanks! Few queries, but looking much better

2021-04-10 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java
> +        }
move this to the caller, it's better to explicitly special-case logic
```suggestion
        if (resourceId == R.id.action_search_dictionary && !Lookup.isAvailable()) {
            mCustomButtons.put(resourceId, MENU_DISABLED);
        }
```

2021-04-10 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +               selectAndCopyText();
please revert the spacing change here

2021-04-10 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java
> +        setupButton(preferences, R.id.action_search_dictionary, "customButtonLookup", SHOW_AS_ACTION_NEVER);
Seems to be inconsistent between here and the preferences. `MENU_DISABLED` in prefs and `SHOW_AS_ACTION_NEVER` in the code

2021-04-10 23:15 UTC, david-allison-1 approved these changes
Beautiful, thanks!

2021-04-10 23:17 UTC, Mohaned-Elfeky commented
Thank you.

2021-04-10 23:32 UTC, david-allison-1 commented
Unit test failure - I'll take a look

2021-04-10 23:38 UTC, david-allison-1 commented
Change:

https://github.com/ankidroid/Anki-Android/blob/937d3027a35f3af8c478b2066c8f35d1627710ee/AnkiDroid/src/test/java/com/ichi2/anki/reviewer/ActionButtonStatusTest.java#L42-L51

to 

```java
    @Test
    public void allCustomButtonsCanBeDisabled() {
        Set<String> reviewerExpectedKeys = getCustomButtonsExpectedKeys();
        Set<String> actualPreferenceKeys = PreferenceUtils.getAllCustomButtonKeys(getTargetContext());
        reviewerExpectedKeys.add("customButtonLookup"); // preference isn't read if Lookup is disabled.

        assertThat("Each button in the Action Bar must be modifiable in Preferences - Reviewer - App Bar Buttons",
                reviewerExpectedKeys,
                containsInAnyOrder(Objects.requireNonNull(actualPreferenceKeys.toArray())));
    }
```

2021-04-10 23:46 UTC, david-allison-1 approved these changes
Take two... beautiful!

2021-04-10 23:47 UTC, Mohaned-Elfeky commented
Thank you for your feedback

2021-04-14 03:03 UTC, mikehardy requested changes
This will generate a few notifications - but I also approve, except one trivial spacing change, which I have to "request changes" on, then commit the suggestion, then I can approve then merge and release :-)

2021-04-14 03:03 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java
> +        else {
```suggestion
        } else {
```

2021-04-14 03:04 UTC, mikehardy approved these changes
good to go!

2021-04-14 13:44 UTC, merged

2021-05-09 15:17 UTC, mikehardy commented
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!