Implemented toast message when back is pressed
ankidroid/Anki-Android pull request #8457
Opened 2021-04-03 18:50 UTC by iamvs-2002

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_
Implemented toast message when back is pressed

## Fixes
Fixes _Link to the issues._
#8226 
#8453 

## Approach
_How does this change address the problem?_

## How Has This Been Tested?
I have tested the same on Google Pixel XL Api 30 android device.

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-03 18:53 UTC, david-allison-1 requested changes

2021-04-03 18:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    public boolean count = false;
See: https://github.com/ankidroid/Anki-Android/pull/8453#discussion_r606685865

2021-04-03 18:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +     * Keep a track of how many times back button was pressed
This comment isn't correct, and not really necessary, for something like this just having a well named variable will suffice

2021-04-03 18:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                if (count){
```suggestion
                if (count) {
```

2021-04-03 18:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                UIUtils.showThemedToast(this, getApplication().getString(R.string.back_pressed_once), true);
Don't show this if the FAB is open

2021-04-03 18:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                    UIUtils.showThemedToast(this, getApplication().getString(R.string.back_pressed_once), true);
```suggestion
                    UIUtils.showThemedToast(this, getString(R.string.back_pressed_once), true);
```

2021-04-03 19:06 UTC, david-allison-1 requested changes
See comment on variable naming

2021-04-03 19:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    public boolean count = false;
Move this variable to below the other non-static non-public variables

2021-04-03 19:07 UTC, iamvs-2002 commented
> See comment on variable naming

Alright let me make it back_pressed

2021-04-03 19:07 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="back_pressed_once" translatable="false">Press back again to exit</string>
```suggestion
    <string name="back_pressed_once">Press back again to exit</string>
```

2021-04-03 19:10 UTC, iamvs-2002 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="back_pressed_once" translatable="false">Press back again to exit</string>
It has been done because back_pressed_once is not translatable in other languages the app supports.

2021-04-03 19:11 UTC, david-allison-1 commented
The comment that I posted stated `mBackButtonPressedToExit`

2021-04-03 19:12 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="back_pressed_once" translatable="false">Press back again to exit</string>
I don't understand. It is translatable

2021-04-03 19:13 UTC, iamvs-2002 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="back_pressed_once" translatable="false">Press back again to exit</string>
Or shall I add it's translation in other languages as well?

2021-04-03 19:16 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="back_pressed_once" translatable="false">Press back again to exit</string>
All we need to do is define it as such: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#adding-translations

2021-04-03 19:38 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    public boolean mBackButtonPressedToExit = false;
Last one

```suggestion
    private boolean mBackButtonPressedToExit = false;
```

2021-04-03 19:38 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                else {
```suggestion
                } else {
```

2021-04-03 19:38 UTC, iamvs-2002 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    public boolean mBackButtonPressedToExit = false;
Alright.

2021-04-03 19:39 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            mBackButtonPressedToExit = true;
Only set this inside the `else` block
```suggestion
            mBackButtonPressedToExit = true;
```

2021-04-03 19:44 UTC, david-allison-1 approved these changes
Looks good to me

2021-04-03 19:44 UTC, david-allison-1 commented
Could you provide a screenshot: 

>  UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

2021-04-03 19:57 UTC, iamvs-2002 commented
> Could you provide a screenshot:
> 
> > UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

I am not sure if this is what you want:
![Screenshot (193)](https://user-images.githubusercontent.com/54304786/113489918-9c42a600-94e4-11eb-98a2-213c6898cfd0.png)
![Screenshot (195)](https://user-images.githubusercontent.com/54304786/113489921-a19ff080-94e4-11eb-8cef-0ef37c5e883a.png)
![Screenshot (197)](https://user-images.githubusercontent.com/54304786/113489924-a5337780-94e4-11eb-85b7-75d9d0d796db.png)

2021-04-03 20:00 UTC, iamvs-2002 commented
> Could you provide a screenshot:
> 
> > UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

Sir, I am not sure if these are the screenshots you want:
![Screenshot (193)](https://user-images.githubusercontent.com/54304786/113490020-4a4e5000-94e5-11eb-931b-6ed12a4539b4.png)
![Screenshot (195)](https://user-images.githubusercontent.com/54304786/113490023-4b7f7d00-94e5-11eb-811f-16baf4e35a47.png)
![Screenshot (197)](https://user-images.githubusercontent.com/54304786/113490025-4c181380-94e5-11eb-9ef1-62ed97972c43.png)

2021-04-03 20:02 UTC, mikehardy approved these changes
Screenshots look great, code looks great - LGTM

2021-04-03 20:02 UTC, merged

2021-05-09 15:17 UTC, mikehardy commented
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!

2021-05-10 13:44 UTC, iamvs-2002 commented
Hi sir,
Thanks a lot, but to be honest, I do open source because I really enjoy it.
If my contributions can bring some improvement in the product, that would
be my greatest earning.


*Regards,Vaibhav Singhal*
***@***.***
*LinkedIn <https://www.linkedin.com/in/iamvs2002/> . Github
<https://github.com/iamvs-2002>*

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/10/21,
07:13:15 PM

On Sun, May 9, 2021 at 8:47 PM Mike Hardy ***@***.***> wrote:

> Hi there!
>
> Just a friendly notice that we try to process OpenCollective payments
> monthly - it's time for April 2021 submissions
>
> If you are interested in compensation for this work, the process with
> details is here:
>
>
> https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid
>
> (I only post one comment per person to avoid spamming you, regardless of
> the number of PRs merged, but this note applies to all PRs merged in April)
>
> Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ankidroid/Anki-Android/pull/8457#issuecomment-835826941>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM6KAEXPULBSOVNHY3R4GITTM2RRVANCNFSM42KQS7NQ>
> .
>