Add utility function to handle focus on EditText and opening of keyboard
ankidroid/Anki-Android pull request #8465
Opened 2021-04-04 09:44 UTC by ShridharGoel

## Purpose / Description
Adding an utility function to handle focus on EditText and opening of keyboard

## Fixes
Fixes part of #8464

## Approach
Added a function which can be used with MaterialDialog having EditText.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-04 09:48 UTC, david-allison-1 requested changes
It'd be better to work off the code in `FixedEditText.focusWithKeyboard`

2021-04-04 09:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/AndroidUiUtils.java
> +        Objects.requireNonNull(materialDialog.getWindow()).setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_VISIBLE);
accept a `@NonNull` Window rather than a MaterialDialog

2021-04-04 10:06 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/AndroidUiUtils.java
> +        Objects.requireNonNull(materialDialog.getWindow()).setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_VISIBLE);
Updated.

2021-04-04 12:31 UTC, david-allison-1 requested changes

2021-04-04 12:31 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            AndroidUiUtils.setFocusAndOpenKeyboard(mAnswerField, getWindow());
It'd be better to keep the API the same, and leverage the same functionality (if possible).

2021-04-04 12:31 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/AndroidUiUtils.java
> +        view.requestFocus();
This has changed the implementation, so likely won't work on some phones

2021-04-04 12:34 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/AndroidUiUtils.java
> +        view.requestFocus();
Using `InputMethodManager` was not working with FixedEditText present inside MaterialDialog.

2021-04-04 16:58 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            AndroidUiUtils.setFocusAndOpenKeyboard(mAnswerField, getWindow());
Can you please explain this? If you mean that `InputMethodManager` should be used, then actually it isn't working in the `MaterialDialog` use-case. Should we considering restoring the `focusWithKeyboard()` method of `FixedEditText` and use it where it was being used earlier? And for the MaterialDialog use-case, we can use `setFocusAndOpenKeyboard()`.

2021-04-06 06:26 UTC, ShridharGoel commented
Any updates regarding what is expected here?

2021-04-06 06:28 UTC, ShridharGoel commented
@david-allison-1 Can you please tell what is expected here?

2021-04-06 14:57 UTC, david-allison-1 commented
> @david-allison-1 Can you please tell what is expected here?

If the two methods are incompatible, extract them both into a class with the same method name, so they're close to each other and improve discoverability.

2021-04-06 16:47 UTC, ShridharGoel commented
Updated.

2021-04-06 16:52 UTC, david-allison-1 reviewed
One minor change, and good to go

2021-04-06 16:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            AndroidUiUtils.setFocusAndOpenKeyboard(mAnswerField);
Keep the call the same, and call into AndroidUiUtils via the instance method.

This means that the method is still discoverable on the class

2021-04-06 16:57 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            AndroidUiUtils.setFocusAndOpenKeyboard(mAnswerField);
Updated.

2021-04-06 17:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/AndroidUiUtils.java
> +    public static void setFocusAndOpenKeyboard(@NotNull FixedEditText fixedEditText) {
`View view` should work... or at least `EditText`

2021-04-06 17:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/AndroidUiUtils.java
> +        window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_VISIBLE);
Is always visible what we want? Can the user dismiss the soft keyboard

2021-04-06 17:40 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/AndroidUiUtils.java
> +    public static void setFocusAndOpenKeyboard(@NotNull FixedEditText fixedEditText) {
Updated.

2021-04-06 17:42 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/AndroidUiUtils.java
> +        window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_VISIBLE);
Yes, the soft keyboard can be dismissed.

`SOFT_INPUT_STATE_VISIBLE` was not working, the keyboard was not showing using that. Hence I have used `SOFT_INPUT_STATE_ALWAYS_VISIBLE`.

2021-04-06 18:04 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/AndroidUiUtils.java
> +     * @param view The EditText which requires the focus to be set.
```suggestion
     * Focuses on View and opens the soft keyboard.
     * @param view The View which requires the focus to be set (typically an EditText).
```

2021-04-06 18:04 UTC, david-allison-1 approved these changes
Looks good to me!

2021-04-06 23:05 UTC, mikehardy requested changes
Looks good in general - appears to just need some import "hygiene" - I noted it where I think it's needed

2021-04-06 23:05 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +import com.ichi2.utils.AndroidUiUtils;
This import statement was added but in the final / complete change it does not appear to be used in the class?

```suggestion
```

2021-04-06 23:05 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/ui/FixedEditText.java
>  import android.view.inputmethod.InputMethodManager;
I do not believe this class still needs the InputMethodManager import and it may be removed

```suggestion
```

Definitely make sure it compiles after removing it of course - I could be wrong!

2021-04-07 09:49 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +import com.ichi2.utils.AndroidUiUtils;
This was an unused import. Updated.

2021-04-07 09:50 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/ui/FixedEditText.java
>  import android.view.inputmethod.InputMethodManager;
Yes, this was also an unused import. Removed it.

2021-04-08 03:53 UTC, mikehardy approved these changes
Looks really clean, thank you @ShridharGoel !

2021-04-08 03:54 UTC, merged