Fix #8467: Prevent crash on long pressing an already selected card
ankidroid/Anki-Android pull request #8468
Opened 2021-04-04 11:52 UTC by ShridharGoel

## Purpose / Description
App should not crash on long pressing an already selected card in the card browser.
 
## Fixes
Fixes #8467 

## Approach
Added a check to ensure that `childView` is not null before calling `findViewById()` on it.

## How Has This Been Tested?

Verified that the mentioned issue does not occur after this change.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-04 12:02 UTC, david-allison-1 requested changes
This implies a bug somewhere else in the app - likely with selecting an invalid position

2021-04-04 12:53 UTC, david-allison-1 commented
Could you diagnose and fix/test the cause of the bug, rather than patching the result of the bug

2021-04-04 12:57 UTC, ShridharGoel commented
Yes, I have found the issue. `getChildAt()` works with respect to the visible items in the ListView and not the actual positions in the list. Some alternative approach is needed here, which I'm trying to do.

2021-04-04 12:58 UTC, ShridharGoel commented
If you have any suggestions, then please let me know.

2021-04-04 13:03 UTC, david-allison-1 commented
> Yes, I have found the issue. `getChildAt()` works with respect to the visible items in the ListView and not the actual positions in the list. Some alternative approach is needed here, which I'm trying to do.

I would expect that the problem is that the input to that function is bad, is this not the case?

2021-04-04 13:06 UTC, ShridharGoel commented
Yes, the input to that function is wrong.

2021-04-04 13:13 UTC, david-allison-1 commented
Okay, so to fix this issue:

* work out why the input was bad, possibly use a debugger
* write a test which fails
* fix the code, and ensure the test passes

2021-04-04 13:47 UTC, ShridharGoel commented
For confirmation regarding the expected behaviour, suppose I select the card at position 8 by long pressing. Then, I scroll and long press on the card at position 15. This should lead to the selection of all cards from position 8 to 15, right?

2021-04-04 14:12 UTC, david-allison-1 commented
> For confirmation regarding the expected behaviour, suppose I select the card at position 8 by long pressing. Then, I scroll and long press on the card at position 15. This should lead to the selection of all cards from position 8 to 15, right?

yep

2021-04-04 16:04 UTC, ShridharGoel commented
Updated. Please have a look.

Regarding the tests, this requires an instrumentation test, right?

2021-04-04 16:06 UTC, madelesi commented
This is closely related to #8460. Adding your null check prevents crashing in #8460, but does not toggle the checkbox for all the cards which need scrolling (which is expected).

@david-allison-1 
> I would expect that the problem is that the input to that function is bad, is this not the case?
Do you mean the ```getChildAt()``` function? Because the input to it seems correct to me

2021-04-04 16:13 UTC, david-allison-1 commented
> Updated. Please have a look.
> 
> Regarding the tests, this requires an instrumentation test, right?

Likely better under robolectric.

I'm on my phone, but I haven't seen a diagnosis for why the bug occurred, only a fix and that's a little concerning

2021-04-04 16:14 UTC, mikehardy commented
I don't believe it will require an instrumentation test, RobolectricTest provides you with a collection where you may set up a data test fixture, and ability to start Activities and get View elements etc. You can see in CardTemplateEditorTest for instance doing some pretty heavy work with Activity lifecycles and checking view contents / altering them / asserting internal Activity state etc

2021-04-04 16:18 UTC, ShridharGoel commented
> I'm on my phone, but I haven't seen a diagnosis for why the bug occurred, only a fix and that's a little concerning

I have updated the details under the `Approach` section of the PR description.

2021-04-04 16:19 UTC, ShridharGoel commented
> I don't believe it will require an instrumentation test, RobolectricTest provides you with a collection where you may set up a data test fixture, and ability to start Activities and get View elements etc. You can see in CardTemplateEditorTest for instance doing some pretty heavy work with Activity lifecycles and checking view contents / altering them / asserting internal Activity state etc

Thank you.

2021-04-04 16:20 UTC, ShridharGoel commented
> I don't believe it will require an instrumentation test, RobolectricTest provides you with a collection where you may set up a data test fixture, and ability to start Activities and get View elements etc. You can see in CardTemplateEditorTest for instance doing some pretty heavy work with Activity lifecycles and checking view contents / altering them / asserting internal Activity state etc

Okay, I'll try this and update. Thanks.

2021-04-04 16:54 UTC, ShridharGoel commented
I have already tried creating this test in `CardBrowserTest`:

```
@Test
public void checkMultipleCardSelection() {
    CardBrowser browser = getBrowserWithNotes(10);
    selectOneOfManyCards(browser, 4);
    selectOneOfManyCards(browser, 8);
    assertThat(browser.checkedCardCount(), is(5));
}
```

Here, the card at position 4 is getting long clicked and then the one at position 8 (I have modified the `selectOneOfManyCards` method). But this test case is passing even when in actual the code leads to a crash. That's why I thought that an instrumentation test might be required. Any help on this? Does the above test look fine?

2021-04-05 22:44 UTC, david-allison-1 commented
You'll likely need to try emulating a long press in the test.

2021-04-06 15:46 UTC, madelesi commented
> suppose I select the card at position 8 by long pressing. Then, I scroll and long press on the card at position 15. This should lead to the selection of all cards from position 8 to 15, right?

As a heads-up, the current work would select all cards from 9 to 15 in your example. (It toggles all cards in the range, meaning the first card which was checked will become unchecked). Setting i to ```Math.Min(mLastSelectedPosition, position)+1``` in the for-loop seems a good fix.

2021-04-07 08:55 UTC, ShridharGoel commented
Detailed explanation:

Suppose the item with index 4 in the list is currently the first visible item on the screen. The method `getChildAt()` would require an input of 0 to refer to that item since it's at the 0th position (index) in the currently visible items, while in actual it's position (index) is 4 in the list. This was the reason of the bug, which this PR aims to solve. I have removed the dependency on `getChildAt()` method since it was not suitable for this use-case.

Also, because of this reason, it's not clear how to write a test which should fail for previous code and pass for this one.

2021-04-07 09:46 UTC, ShridharGoel commented
> As a heads-up, the current work would select all cards from 9 to 15 in your example. (It toggles all cards in the range, meaning the first card which was checked will become unchecked). Setting i to `Math.Min(mLastSelectedPosition, position)+1` in the for-loop seems a good fix.

Thanks, I have updated the functionality according to the behaviour which seemed expected from the previous code.

According to the current functionality, multiple items are not being unchecked at once. Suppose the items from index 1 to index 10 are checked. If we long press on item with index 5, then only that will get unchecked. Then, if we long press on item at index 8, then again only that item will get unchecked.

This is the current behaviour. If this is not as intended, then do let me know.

2021-04-07 14:12 UTC, david-allison-1 requested changes
I'll need to apologise here, I misunderstood the initial commit - the code didn't handle `mCheckedCards`, but the intuition was correct.

The fix will need commenting to explain why the code looks the way it does, and what is happening for both visible and invisible cards

----

I've taken a look at this issue in a debugger.

The issue is caused by: https://stackoverflow.com/a/6767006, and is triggered when there is more than one page of items in the CardBrowser

This means that to handle checking of unseen cards, we need to:

* Check the visible items on the screen, being aware that `getChildAt` returns the logical position, and not the physical position
* Modify our abstraction for checked cards: `mCheckedCards`
* Add a regression test

2021-04-07 16:45 UTC, ShridharGoel commented
> The fix will need commenting to explain why the code looks the way it does, and what is happening for both visible and invisible cards

I'll update it with comments.

> The issue is caused by: https://stackoverflow.com/a/6767006, and is triggered when there is more than one page of items in the CardBrowser

That's correct and I had also taken reference from this StackOverflow answer.
More specifically, the crash happens after scrolling from the first screen of visible items.

> Check the visible items on the screen, being aware that getChildAt returns the logical position, and not the physical position

Using `getChildAt()` is not required, the required functionality can be handled with `mCheckedCards` as done in this PR.

> Modify our abstraction for checked cards: mCheckedCards

Is there anything wrong with `mCheckedCards`? It seems to be fine.

> Add a regression test

I'll add a unit test to ensure that the functionality is working.

2021-04-07 16:45 UTC, ShridharGoel commented
> The fix will need commenting to explain why the code looks the way it does, and what is happening for both visible and invisible cards

I'll update it with comments.

> The issue is caused by: https://stackoverflow.com/a/6767006, and is triggered when there is more than one page of items in the CardBrowser

That's correct and I had also taken reference from this StackOverflow answer.
More specifically, the crash happens after scrolling from the first screen of visible items.

> Check the visible items on the screen, being aware that getChildAt returns the logical position, and not the physical position

Using `getChildAt()` is not required, the required functionality can be handled with `mCheckedCards` as done in this PR.

> Modify our abstraction for checked cards: mCheckedCards

Is there anything wrong with `mCheckedCards`? It seems to be fine.

> Add a regression test

I'll add a unit test to ensure that the functionality is working.

2021-04-07 16:47 UTC, ShridharGoel commented
> The fix will need commenting to explain why the code looks the way it does, and what is happening for both visible and invisible cards

I will update it with more comments.

> The issue is caused by: https://stackoverflow.com/a/6767006, and is triggered when there is more than one page of items in the CardBrowser

That's correct and I had also taken reference from this StackOverflow answer.
More specifically, the crash happens after scrolling from the first screen of visible items.

> Check the visible items on the screen, being aware that getChildAt returns the logical position, and not the physical position

Using `getChildAt()` is not required, the required functionality can be handled with `mCheckedCards` as done in this PR.

> Modify our abstraction for checked cards: mCheckedCards

Is there anything wrong with `mCheckedCards`? It seems to be fine.

> Add a regression test

I'll add a unit test to ensure that the functionality is working.

2021-04-07 16:47 UTC, ShridharGoel commented
> The fix will need commenting to explain why the code looks the way it does, and what is happening for both visible and invisible cards

I will update it with more comments.

> The issue is caused by: https://stackoverflow.com/a/6767006, and is triggered when there is more than one page of items in the CardBrowser

That's correct and I had also taken reference from this StackOverflow answer.
More specifically, the crash happens after scrolling from the first screen of visible items.

> Check the visible items on the screen, being aware that getChildAt returns the logical position, and not the physical position

Using `getChildAt()` is not required, the required functionality can be handled with `mCheckedCards` as done in this PR.

> Modify our abstraction for checked cards: mCheckedCards

Is there anything wrong with `mCheckedCards`? It seems to be fine.

> Add a regression test

I'll add a unit test.

2021-04-07 16:56 UTC, ShridharGoel commented
@david-allison-1 Please have a look at the unit test.

2021-04-07 17:10 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +    public void checkIfLongSelectChecksAllCardsInBetween() {
This test passes before the change was made

2021-04-07 17:12 UTC, david-allison-1 commented
> > Check the visible items on the screen, being aware that getChildAt returns the logical position, and not the physical position
> 
> Using `getChildAt()` is not required, the required functionality can be handled with `mCheckedCards` as done in this PR.

This PR doesn't seem correct - 

* select 0
* tap 3
* long tap 3

I'd expect (0,1,2,3) to be selected

> > Modify our abstraction for checked cards: mCheckedCards
> 
> Is there anything wrong with `mCheckedCards`? It seems to be fine.

I was unclear: how we check cards inside and outside the visible view range will need to be better abstracted.

2021-04-07 17:17 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +        selectOneOfManyCards(browser, 0);
Design: Could we add a method with a single parameter which defaults to 0

2021-04-07 17:17 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +    private void selectOneOfManyCards(CardBrowser browser, int position) {
Design: This method now performs more than selection. Could we add in another method for multiple selection, and cause `selectOneOfManyCards` to fail if it invokes the new multi-select code.

2021-04-07 17:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +                        if (!mCheckedCards.contains(card)) {
```suggestion
                        if (mCheckedCards.add(card)) {
```

2021-04-07 17:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +            onCheck(position, view);
Doesn't this call `onCheck` twice?

2021-04-07 18:53 UTC, ShridharGoel commented
> * select 0
> * tap 3
> * long tap 3
> 
> I'd expect (0,1,2,3) to be selected

The requirement was not perfectly clear to me earlier. I have updated the code now.

2021-04-07 18:54 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +            onCheck(position, view);
It was outside the if-else block and was being called just once I think. But now the implementation has changed in the updated code.

2021-04-07 19:15 UTC, ShridharGoel commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +    public void checkIfLongSelectChecksAllCardsInBetween() {
The issue with the previous code was that wrong index was being passed as input to `getChildAt()`. I think that cannot be replicated with Roboelectric unless we explicitly pass a wrong index.

2021-04-07 19:21 UTC, ShridharGoel commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +        selectOneOfManyCards(browser, 0);
Updated.

2021-04-07 19:57 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +    public void checkIfLongSelectChecksAllCardsInBetween() {
https://github.com/ankidroid/Anki-Android/blob/34c9f25038d24e3bf9f338fa307b1bcb3610b5ba/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java#L578-L579

`toSelect.getChildCount()` is 9 here.

We need to fix the test (a null view is passed through currently), but the bug is reproducible in a unit test.

2021-04-14 16:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +                        onSelectionChanged();
This is extremely inefficient if we select many cards, keep a variable, and perform the action at the end

2021-04-14 16:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +
Could you revert this spacing change

2021-04-14 16:53 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +    public void checkIfLongSelectChecksAllCardsInBetween() {
Could you ensure the test fails before you make the change to fix the bug

2021-04-24 14:25 UTC, mikehardy commented
Superceded by #8665

2021-04-24 14:25 UTC, closed without merging