[Modified]: Action buttons for cards changed to OnTouch.
ankidroid/Anki-Android pull request #8480
Opened 2021-04-05 04:59 UTC by shobhi1310

## Purpose / Description
If a card auto-advances right as you were answering you can get a weird skip effect, where the card you were trying to answer for is failed, the next card senses that you were holding one of the 4 buttons and since you were just lifting your finger as the next card comes in, it is marked with that answer, and moves to the next card.

## Fixes
Fixes #4631 

## Approach
If `OnTouch` listener with `ACTION_DOWN` is used in place of `OnClick`, it will ensure that the options which are chosen for a particular card, the changes will be reflected for that card itself. When holding down an answer from a previous card, existing input will be ignored.

## How Has This Been Tested?
The work has been tested on physical device (Xiaomi redmi note5 pro).
Steps to test:

1. Ensure your cards auto-advance
2. Hold down on an answer without lifting your finger
3. The card auto advances
4. The action/due date of the card chosen will be applicable for the card on which it was chosen for.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2021-04-05 05:10 UTC, david-allison-1 requested changes
Implementation looks neat, thanks!

But, as I mentioned in: https://github.com/ankidroid/Anki-Android/issues/4631#issuecomment-810358033

> If possible: save the card on press, and only perform the action if it's the same on release.

We ideally don't want to deviate from how the system handles buttons for the answer buttons

2021-04-05 11:25 UTC, shobhi1310 commented
If the user keeps button pressed for long or the auto advance time is too less, and what if the user intends to perform an action on the card, as per your comment, the user will not be able to get the intended action as the the point when he releases the button card is not same.

But if we keep `OnTouch` then all the requirements of user are satisfied.

2021-04-05 11:47 UTC, david-allison-1 commented
> If the user keeps button pressed for long or the auto advance time is too less, and what if the user intends to perform an action on the card, as per your comment, the user will not be able to get the intended action as the the point when he releases the button card is not same.
> 
> But if we keep `OnTouch` then all the requirements of user are satisfied.

That's why I said store a reference to the pressed card, and only perform the action if the card is the same

2021-04-05 12:58 UTC, david-allison-1 requested changes

2021-04-05 12:58 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        public boolean onTouch(View view, MotionEvent event) {
Just use an `onTouchListener`: combine it with the `OnClickListener` and store `mPrevCard` as a field inside it.

2021-04-05 12:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            if(mPrevCard==mCurrentCard) {
Spacing - and it's best to invert the if to reduce nesting.

```suggestion
            if (mPrevCard == mCurrentCard) {
```

2021-04-05 14:54 UTC, david-allison-1 requested changes

2021-04-05 14:54 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +    protected static final int DOUBLE_TAP_IGNORE_THRESHOLD = 50;
Why was this changed?

2021-04-05 14:54 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +//    protected Card mPrevCard;
git is our history, no need to leave code commented

```suggestion

```

2021-04-05 14:54 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            view.setOnClickListener(new OnClickListener() {
No need for a listener - emulate this on the "on release" event: `MotionEvent.ACTION_UP`

Do note: `MotionEvent.ACTION_CANCEL` will need to be considered

2021-04-05 18:05 UTC, shobhi1310 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +    protected static final int DOUBLE_TAP_IGNORE_THRESHOLD = 50;
ohh! I was actually experimenting locally with the response time, sorry will remove these.

2021-04-06 13:52 UTC, shobhi1310 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            view.setOnClickListener(new OnClickListener() {
I had earlier tried to emulate using `ACTION_UP`, but the double tap feature is getting captured first and auto-advancing of the card also freezes when new card shows up.

@david-allison-1

2021-04-06 14:39 UTC, david-allison-1 requested changes

2021-04-06 14:39 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +    protected static final int DOUBLE_TAP_IGNORE_THRESHOLD = 50;
Wasn't fixed

2021-04-06 14:39 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +//    protected Card mPrevCard;
Wasn't fixed

2021-04-06 14:39 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            view.setOnClickListener(new OnClickListener() {
What have you tried code-wise? Presumably you should only be setting the double-tap variable on release?

2021-04-07 03:19 UTC, shobhi1310 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                    clickCount = 0;
I have added 2 new variables `clickCount` and `duration` but still it is creating some issues still.

2021-04-07 03:25 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                if (clickCount == 2 && duration < DOUBLE_TAP_IGNORE_THRESHOLD) {
I feel this would be much more readable if we went back to using `mLastClickTime`.

Set `mLastClickTime` in this handler, as the original code was doing, and see if that improves things.

2021-04-07 05:15 UTC, shobhi1310 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                if (clickCount == 2 && duration < DOUBLE_TAP_IGNORE_THRESHOLD) {
@david-allison-1 
I was checking the `mTimeoutHandler.removeCallbacks(mShowQuestionTask);` . So, `mShowQuestionTask` is supposed to trigger an `onClick` on the again button which creates the auto-advance nature. If I apply `OnTouch` to `mEaseHandler` then even the runnable code needs to be changed.

https://github.com/ankidroid/Anki-Android/blob/5283cfa25155b2bf73cb234b22bfd874002c71ee/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L1931

2021-04-07 05:16 UTC, shobhi1310 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                if (clickCount == 2 && duration < DOUBLE_TAP_IGNORE_THRESHOLD) {
Best option would be to create a new `MotionEvent` and pass it into `dispatchTouch` for the runnable. Is it fine?

2021-04-07 16:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                if (clickCount == 2 && duration < DOUBLE_TAP_IGNORE_THRESHOLD) {
I still think that's far too complicated. All we should need is:

* A touch listener, replacing the click listener
* Handling `DOWN` and saving the card
* Handling `UP` with the same logic that we have now
  * Plus, do nothing if the card doesn't match

Could you try this design, and if it doesn't work, we'll iterate on it

2021-04-08 03:25 UTC, shobhi1310 commented
I have made the changes as you requested, do review it once @david-allison-1

2021-04-08 03:28 UTC, david-allison-1 reviewed
This looks much better! Just a quick refactoring to clean up the code

Main question is about what we want the return value to be, but I think we've got this

2021-04-08 03:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                if (mPrevCard == mCurrentCard) {
This looks much better! Could you invert this `if`

2021-04-08 03:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                    }
I think we want to return `true` here?

2021-04-08 03:36 UTC, shobhi1310 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                if (mPrevCard == mCurrentCard) {
ok, I will put up this condition as `&&` with the previous `if` condition.

2021-04-08 03:41 UTC, david-allison-1 approved these changes
Looks good to me, thanks!!!

2021-04-08 03:58 UTC, mikehardy approved these changes
clever fix, and a clean implementation - thanks @shobhi1310 !

2021-04-08 03:58 UTC, merged

2021-05-09 15:17 UTC, mikehardy commented
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!