Replace timebox notice with a popup
ankidroid/Anki-Android pull request #8484
Opened 2021-04-05 16:47 UTC by kuroni

## Purpose / Description
Replaces the timebox notice with a dialog popup.

## Fixes
Fixes #8081.

## Approach
Replace the themed toast with a material dialog.

## How Has This Been Tested?

I set the time box limit to 1 minute in preference, then opened up any deck, wait for 1 minute and answer. The dialog box shows up as expected.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-05 16:59 UTC, prateek-singh-3212 reviewed
Everything looks fine to me.

2021-04-05 17:03 UTC, david-allison-1 requested changes
Looks good! Minor changes

2021-04-05 17:03 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="dialog_finish">Finish</string>
`close` would be less ambiguous

2021-04-05 17:03 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                        .onPositive((materialDialog, dialogAction) -> finishWithAnimation(RIGHT))
Continue doesn't restart the timebox, and should

2021-04-05 17:06 UTC, kuroni commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                        .onPositive((materialDialog, dialogAction) -> finishWithAnimation(RIGHT))
I think the line below this addition (`getCol().startTimebox();`) does restart the timebox. Is this implying you want me to put this line into `.onNegative()`?

2021-04-05 17:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                        .onPositive((materialDialog, dialogAction) -> finishWithAnimation(RIGHT))
`onPositive` - I think we want to "pause" the timebox until the user presses continue

2021-04-05 17:23 UTC, kuroni commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                        .onPositive((materialDialog, dialogAction) -> finishWithAnimation(RIGHT))
Oh sorry, currently "Continue" is shown as `negativeText`  and not `positiveText`, I will fix that.

In addition to that, I believe that when the dialog is shown, the time box has already reached the limit, so we don't especially need to "pause" it; we only need to restart it when the user confirms "Continue", or cancels the dialog (by tapping out of the dialog for example).

2021-04-05 17:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                        .onPositive((materialDialog, dialogAction) -> finishWithAnimation(RIGHT))
Yep! Delaying calling `getCol().startTimebox();` de-facto pauses it, no action needed other than moving that to the `onPositive` (in my mind)

2021-04-05 18:00 UTC, david-allison-1 commented
(and onPositive change for the timebox) is remaining

```
  /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/02-strings.xml:106: Error: Duplicate string value "Close", used in close, dialog_close [DuplicateCrowdInStrings]
      <string name="close">Close</string>
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/03-dialogs.xml:110: Duplicates value in close. Add a comment attribute to explain this duplication
```

2021-04-05 18:08 UTC, kuroni commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                        .onPositive((materialDialog, dialogAction) -> finishWithAnimation(RIGHT))
I see what you mean. However I think one possibility that can happen is when the user decides to cancel the dialog box (by tapping outside for example).  When that happens, we would still want to restart the timer, so that's why I'm delaying to call `getCol().startTimebox();` later rather than moving it in `onPositive`.  Another approach would be to make the dialog box not cancellable  (which is not a good thing in my opinion).

2021-04-05 18:21 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                        .onPositive((materialDialog, dialogAction) -> finishWithAnimation(RIGHT))
The current code isn't calling it later. It starts the timer before the dialog is dismissed. `.show()` returns immediately, not when the dialog is closed.

You'll want to handle `onNeutral`

2021-04-05 19:00 UTC, kuroni commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                        .onPositive((materialDialog, dialogAction) -> finishWithAnimation(RIGHT))
Heya! I found out that `onNeutral` actually doesn't work with cancelling, so I did `cancelListener` instead. Other than that everything is addressed!

2021-04-05 19:05 UTC, david-allison-1 approved these changes
Looks good to me!

Could you post a screenshot?

2021-04-05 19:11 UTC, kuroni commented
![Screenshot_20210405-151022_AnkiDroid](https://user-images.githubusercontent.com/13513478/113614956-3b6cb800-9621-11eb-9768-e1ee6362e1dd.jpg)

2021-04-06 06:44 UTC, prateek-singh-3212 approved these changes

2021-04-08 04:05 UTC, mikehardy requested changes
As mentioned, I think this collides with another change, but the code here in general is excellent - I just want to make sure this change works with the one I referenced

2021-04-08 04:05 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                        .onNegative((materialDialog, dialogAction) -> finishWithAnimation(RIGHT))
With apologies I think this will collide with / and fail to compile now that #8396 has been fixed by #8470  - I think the solution is easy in that the 'RIGHT' needs to be 'END' now (I think the import will be updated already?

Can you rebase this PR to master, make sure it compiles, and push it again

For completeness / just in case, I think that's:

`git fetch upstream && git rebase upstream/master`

(which should get the fresh code (assuming `git remote add upstream git@github.com:ankidroid/Anki-Android.git` has already been executed, so the `upstream` name means something...)

Then after you make sure the code still compiles - probably with the change from `RIGHT` to `END` to push it back it's 

`git push origin +timebox-dialog` (where the `+` sign is normally dangerous - it is a force push and some repos forbid it, but we don't mind rewriting history on branches before merging them as it keeps the commit history clean pre-merge.

If you are a git pro already and that was unnecessary forgive me, but hopefully it helps :-)

2021-04-08 04:07 UTC, mikehardy commented
This PR is the second today to get the rare combo of "waiting for feedback" and "pending merge" - maintainer note, as soon as it is verified this passes CI after pulling upstream/master containing #8470 and working with the new RTL-capable transition animation names, this is good to go

2021-04-08 04:25 UTC, kuroni commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                        .onNegative((materialDialog, dialogAction) -> finishWithAnimation(RIGHT))
Thank you for the help! Although I've known about rebasing already, I never knew adding `+` before the branch force-pushed it (I've always used `--force` before)

2021-04-08 04:32 UTC, mikehardy approved these changes
That was fast! Thanks @kuroni

2021-04-08 04:42 UTC, merged