Fix #8466: Update card colour when a flag is selected
ankidroid/Anki-Android pull request #8485
Opened 2021-04-05 17:22 UTC by ShridharGoel

## Purpose / Description

Card colour needs to be updated when a flag is selected for that card.

## Fixes

Fixes #8466 

## Approach

Added functionality to iterate through the cards and set the selected flag for the selected cards.

## How Has This Been Tested?

Verified that the functionality is working.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-05 18:19 UTC, david-allison-1 requested changes
Thanks! Could you provide:

* a video of the "before" functionality - I'm really confused as to why I can't reproduce this
* A unit test, which failed before, and now passes

> I can't reproduce this, could you provide a failing unit test (which you made pass) along with your fix, if possible

https://github.com/ankidroid/Anki-Android/issues/8466#issuecomment-813025830

2021-04-05 18:44 UTC, ShridharGoel commented
> a video of the "before" functionality - I'm really confused as to why I can't reproduce this

I have added the video in the issue description here: https://github.com/ankidroid/Anki-Android/issues/8466

2021-04-06 06:11 UTC, ShridharGoel commented
> A unit test, which failed before, and now passes

Added the unit test.

2021-04-06 14:53 UTC, david-allison-1 reviewed
@Arthur-Milchior I'm going to relieve myself of reviewing this one until I understand it better, could you take a look. 

I still don't understand how the bug could be occurring, I haven't been able to reproduce it, and the code to fix it seems incorrect (but apparently works). 

Could you take a look?

2021-04-06 14:53 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +        assertThat(card.userFlag(), is(1));
This likely failed previously because we didn't wait for the async task to complete

2021-04-06 14:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        for (CardCache card: getCards()) {
This is likely to change the statuses of the card while the flagging task is still running

2021-04-06 17:02 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        for (CardCache card: getCards()) {
Is there any way to get a callback in this case when the AsyncTask is finished? Or some similar approach?

2021-04-07 00:33 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +    public void checkIfFlagSelectionUpdatesSelectedCard() {
I confirm this test fails. I'll take a look at it

2021-04-07 00:33 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +    public void flagTask (int flag) {
@VisibleForTesting

2021-04-07 09:54 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +    public void flagTask (int flag) {
Updated.

2021-04-30 19:54 UTC, mikehardy commented
I believe this is superceded by #8735

2021-04-30 20:06 UTC, Arthur-Milchior commented
It should be kept open until we have regression test

2021-04-30 20:29 UTC, david-allison-1 commented
> It should be kept open until we have regression test

Shouldn't that be the issue, and not the PR?

2021-05-01 14:26 UTC, closed without merging