Add unit test for TextCardExporter
ankidroid/Anki-Android pull request #8498
Opened 2021-04-07 05:12 UTC by kuroni

## Purpose / Description
Add unit test for TextCardExporter.
It is noteworthy that upstream does not have such a test.

## Approach
Comparing outputs of TextCardExporter with expected outputs.

## How Has This Been Tested?
Passed the unit test locally.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

## Additional
I saw there's an ExportingTest.java within the same folder, which looks like it's trying to copy upstream's exporting tests, but the current state has separate tests for different Exporters.

2021-04-07 14:46 UTC, david-allison-1 requested changes
Looks great, cheers!

One minor nitpick, then good to go

2021-04-07 14:46 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/libanki/TextCardExporterTest.java
> +        assertEquals(expectedWithHTML, contentWithHTML);
Could you split this into two tests: it's typically best to have one reason for a test to fail

(I'm aware that many tests ported from upstream don't follow this guideline)

2021-04-07 15:43 UTC, kuroni commented on AnkiDroid/src/test/java/com/ichi2/libanki/TextCardExporterTest.java
> +        assertEquals(expectedWithHTML, contentWithHTML);
Resolved :)

2021-04-07 15:54 UTC, david-allison-1 approved these changes
LGTM, thanks!

2021-04-07 18:03 UTC, TarekkMA commented on AnkiDroid/src/test/java/com/ichi2/libanki/TextCardExporterTest.java
> +        // with a different col
[nit] 
```suggestion
        // with a different note
```

2021-04-07 18:05 UTC, TarekkMA commented on AnkiDroid/src/test/java/com/ichi2/libanki/TextCardExporterTest.java
> +        expected += String.format(Locale.US, "<style>%s</style>", noteList.get(0).model().getString("css"));
Why do we need `String.format(Locale.US, ......)` instead of normal string concatenation ?

2021-04-07 18:08 UTC, TarekkMA commented
Thank you for testing `TextCardExporter` I thought I got it with `TextCardExporterTest` but I did forget about it 😅.

2021-04-07 18:13 UTC, kuroni commented on AnkiDroid/src/test/java/com/ichi2/libanki/TextCardExporterTest.java
> +        expected += String.format(Locale.US, "<style>%s</style>", noteList.get(0).model().getString("css"));
This was taken directly from https://github.com/ankidroid/Anki-Android/blob/7b6fcec9d7d49b2f15fc57b589d5e85e4c6ceaf5/AnkiDroid/src/main/java/com/ichi2/libanki/Card.java#L274.

2021-04-07 18:15 UTC, TarekkMA commented on AnkiDroid/src/test/java/com/ichi2/libanki/TextCardExporterTest.java
> +        expected += String.format(Locale.US, "<style>%s</style>", noteList.get(0).model().getString("css"));
Oh, okay thank you for the explanation.

2021-04-08 03:45 UTC, mikehardy requested changes
This looks good to me with the exception that it is missing the copyright header. Could you grab one from any of the files next to this one and put it in the top with your github email address? It's your chance to be (sort of / Anki-)famous! :-)

2021-04-08 03:46 UTC, mikehardy commented
the rare combo of "waiting for feedback" and "pending merge" - maintainers note as soon as it gets a copyright header it's ready to go...

2021-04-08 03:54 UTC, kuroni commented
All good! Thanks for the heads up!

2021-04-08 04:30 UTC, mikehardy approved these changes
ace!

2021-04-08 04:31 UTC, merged