Get deck name using JS API
ankidroid/Anki-Android pull request #8500
Opened 2021-04-07 11:16 UTC by infinyte7

## Pull Request template

## Purpose / Description
It helps in getting deck name when custom card layout used/designed. The `{{Deck}}` or `{{Subdeck}}` not working when added from js-addons `index.js`. So, it will easier to add deck name to reviewer using JS API.

## Fixes
Fixes _Link to the issues._

## Approach
It is implemented using existing JavascriptInterface

## How Has This Been Tested?
Tested on emulator

Add following to front/back side of card in `script` tag
```
console.log(AnkiDroidJS.ankiGetDeckName());
```

## Learning (optional, can help others)
https://developer.android.com/reference/android/webkit/JavascriptInterface

## Checklist
_Please, go through these checks before submitting the PR._

- [ x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x ] You have commented your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-07 11:24 UTC, david-allison-1 commented
Could you add a test to ensure that {{Deck}} and this method return the same string.

I'd typically be happy with using the same method for both calls, but we'll be removing template generation soon

2021-04-07 11:25 UTC, david-allison-1 requested changes
Could you add a test to ensure that {{Deck}} and this method return the same string.

I'd typically be happy with using the same method for both calls, but we'll be removing template generation soon

2021-04-07 11:48 UTC, infinyte7 commented
Okay, I am implementing it.

2021-04-07 13:23 UTC, infinyte7 commented
After viewing existing code for test, I have implemented for `ankiGetDeckName`. I am finding solution for testing `{{Deck}}`.

2021-04-07 13:26 UTC, david-allison-1 approved these changes
LGTM, thanks!

2021-04-08 03:55 UTC, mikehardy approved these changes
with a test too - thank you @infinyte7 !

2021-04-08 03:55 UTC, merged

2021-05-09 15:17 UTC, mikehardy commented
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!