Added tests to the utility functions of the Tags class
ankidroid/Anki-Android pull request #8511
Opened 2021-04-08 04:39 UTC by Vaibhavi1707

## Purpose 
Adds tests for utility functions in the Tags class.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2021-04-08 04:41 UTC, david-allison-1 approved these changes
Looks good to me

2021-04-09 13:04 UTC, mikehardy requested changes

2021-04-09 13:04 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/libanki/TagsTest.java
> +package com.ichi2.libanki;
Needs a copyright header - can you add one please?

2021-04-09 13:04 UTC, mikehardy commented
maintainer note: can be merged after addition of copyright header

2021-04-09 14:31 UTC, Vaibhavi1707 commented on AnkiDroid/src/test/java/com/ichi2/libanki/TagsTest.java
> +package com.ichi2.libanki;
Sure

2021-04-09 17:12 UTC, mikehardy approved these changes
LGTM thank you! Note for @TarekkMA I just reviewed a massive TagsDialog refactor PR from you, I'm not sure if this will collide or not, but I thought I'd mention you in case it collided

2021-04-09 17:13 UTC, merged

2021-04-09 18:14 UTC, TarekkMA commented
@mikehardy thank you for mentioning me, My PR did touch only the UI part. so I guess we are fine.

2021-05-09 15:17 UTC, mikehardy commented
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!