NF: Adding a reset to default button for setting default directory path
ankidroid/Anki-Android pull request #8514
Opened 2021-04-08 10:05 UTC by kartikeysaran

## Purpose / Description
If a user enters incorrect Directory path then a dialog appears with an option to reset the path to default

<img src="https://user-images.githubusercontent.com/55613721/114007723-32792200-987f-11eb-925b-2ab8681886de.png" width="400" height="800"/>

## Fixes
Fixes #8013 

## How Has This Been Tested?
This has been tested on a Real Device 

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2021-04-08 10:13 UTC, mrudultora commented
```
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/03-dialogs.xml:123: Error: Duplicate string value "Reset to default", used in dialog_reset_to_default, reset_custom_buttons [DuplicateCrowdInStrings]
      <string name="dialog_reset_to_default">Reset to default</string>
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/10-preferences.xml:178: Duplicates value in dialog_reset_to_default. Add a comment attribute to explain this duplication
```
Lint failure. Would you please check if there's already a string available for "Reset to default" ?

2021-04-08 11:07 UTC, mrudultora requested changes
Looks good to me. Small changes to be done.

2021-04-08 11:07 UTC, mrudultora commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                                            storageAccessException.printStackTrace();
Use `Timber` here.

2021-04-08 11:54 UTC, david-allison-1 requested changes
Looks good! Didn't think it'd be this easy

Could you check that you can minimise/restore the app and the functionality still works

2021-04-08 11:54 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                                    public void onClick(DialogInterface dialog, int id) {
nit: Can you use a lambda here

2021-04-08 11:54 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                                    public void onClick(DialogInterface dialog, int id) {
nit: Can you use a lambda here

2021-04-08 11:54 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                                            CollectionHelper.initializeAnkiDroidDirectory("/sdcard/AnkiDroid");
use `CollectionHelper.getDefaultAnkiDroidDirectory`

2021-04-08 11:54 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                        builder.create().show();
I /think/ you can just call `builder.show()`

2021-04-08 12:03 UTC, kartikeysaran commented
> Could you check that you can minimise/restore the app and the functionality still works

Yes it works !

2021-04-08 12:04 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                                    public void onClick(DialogInterface dialog, int id) {
Okay

2021-04-08 12:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                                        collectionPathPreference.setText("/sdcard/AnkiDroid");
```suggestion
                                        String defaultDirectory = CollectionHelper.getDefaultAnkiDroidDirectory();
                                        collectionPathPreference.setText(defaultDirectory);
```

2021-04-08 13:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                        AlertDialog.Builder builder = new AlertDialog.Builder(Preferences.this);
I think we'd be better with `MaterialDialog.Builder`

2021-04-09 06:42 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                        AlertDialog.Builder builder = new AlertDialog.Builder(Preferences.this);
We are using ``` setText() ``` that might not work with ``` MaterialDialog ```

2021-04-09 16:21 UTC, david-allison-1 approved these changes
Looks good to me!

2021-04-09 17:05 UTC, mikehardy approved these changes
Nice! even avoided a new string :sunglasses:

2021-04-09 17:06 UTC, merged

2021-05-09 15:17 UTC, mikehardy commented
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!