Improve dialog usage by setting default focus on EditText
ankidroid/Anki-Android pull request #8518
Opened 2021-04-08 13:44 UTC by ShridharGoel

## Purpose / Description
Improve dialog usage by setting default focus on EditText

## Fixes
Fixes #8464 

## Approach
Used utility function for focusing on EditText and opening keyboard when dialog is opened for 'Create deck', 'Rename deck' and 'Create subdeck'.

## How Has This Been Tested?

Verified that the functionality is working.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-08 16:28 UTC, david-allison-1 requested changes
All of these changes seem to handle a Dialog with a single EditText

I feel we could better abstract this concept (perhaps: `MaterialEditTextDialog.Builder(Context, EditText)`), this adds discoverability of the functionality by moving it inside the builder

2021-04-08 17:25 UTC, ShridharGoel commented
> I feel we could better abstract this concept (perhaps: `MaterialEditTextDialog.Builder(Context, EditText)`), this adds discoverability of the functionality by moving it inside the builder

Do you mean that a class called `MaterialEditTextDialog` should be created?

2021-04-08 17:39 UTC, david-allison-1 commented
> > I feel we could better abstract this concept (perhaps: `MaterialEditTextDialog.Builder(Context, EditText)`), this adds discoverability of the functionality by moving it inside the builder
> 
> Do you mean that a class called `MaterialEditTextDialog` should be created?

Yes, and a builder, if you feel it makes sense

2021-04-09 06:47 UTC, ShridharGoel commented
@david-allison-1 Updated. Please have a look.

2021-04-09 16:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.java
>                          .customView(mDialogEditText, true)
Looks nice! You can move the `.customView` call inside the class as well

2021-04-09 19:06 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.java
>                          .customView(mDialogEditText, true)
Updated.

2021-04-09 19:15 UTC, david-allison-1 approved these changes
I'm happy if CI passes, thanks!!!

2021-04-10 12:55 UTC, mikehardy requested changes
Nice - I like this - maintainer note as soon as it gets a copyright header it's good to merge I think

2021-04-10 12:55 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MaterialEditTextDialog.java
> +package com.ichi2.anki;
Need a copyright header - there should be one in all the files which I mention because you can grab one from any nearby file and paste it in here with your github email and we're set

2021-04-10 13:59 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/MaterialEditTextDialog.java
> +package com.ichi2.anki;
Added.

2021-04-13 17:26 UTC, ShridharGoel commented
@mikehardy Please have a look.

2021-04-14 13:42 UTC, mikehardy approved these changes
Just saw this was good to go as well - thank you @ShridharGoel !

2021-04-14 13:43 UTC, merged