Updated documentation with spelling and spaces
ankidroid/Anki-Android pull request #8522
Opened 2021-04-08 18:04 UTC by niki0712

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-08 18:06 UTC, david-allison-1 commented on .idea/codeStyles/Project.xml
> +          <package name="kotlinx.android.synthetic" withSubpackages="true" static="false" />
Hi, this is the only change that you've made, was it intentional?

2021-04-09 13:24 UTC, Vaibhavi1707 commented
Hi, can you complete the pull request template to explain what spellings or spaces are you fixing? This will make it simpler to understand.

2021-04-09 15:56 UTC, niki0712 commented on .idea/codeStyles/Project.xml
> +          <package name="kotlinx.android.synthetic" withSubpackages="true" static="false" />
Didn't get you, sorry!?

2021-04-09 15:59 UTC, david-allison-1 commented on .idea/codeStyles/Project.xml
> +          <package name="kotlinx.android.synthetic" withSubpackages="true" static="false" />
You've only made one change in this PR. Did you mean to change this? It doesn't seem to have anything to do with the title

2021-04-09 16:07 UTC, niki0712 commented on .idea/codeStyles/Project.xml
> +          <package name="kotlinx.android.synthetic" withSubpackages="true" static="false" />
Yes I meant to change it I'm sorry if I have chose a wrong title.

2021-04-09 16:09 UTC, niki0712 commented
@david-allison-1 Yes! I meant to change it. I may have chosen a wrong title. Sorry for the inconvenie

2021-04-09 16:10 UTC, niki0712 commented
@david-allison-1 Inconvenience*

2021-04-09 16:10 UTC, david-allison-1 requested changes
Could you explain what this PR is meant to do in the template

2021-04-09 16:32 UTC, closed without merging