Add files via upload
ankidroid/Anki-Android pull request #8524
Opened 2021-04-08 20:50 UTC by 3mmar7amed

## Pull Request template

## Purpose / Description
Add unit test for JSONArray class.
this class has not been tested yet.

## Approach
comparing the value stored in a specific index in a list with the actual value.
ensure that it isn't crashing in any way

## How Has This Been Tested?

Passed the unit test locally.

## Checklist

- [✔ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [✔  ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ✔ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ✔ ] You have commented your code, particularly in hard-to-understand areas
- [✔  ] You have performed a self-review of your own code

2021-04-09 13:02 UTC, mikehardy commented
This does not compile, I'm not sure how this ever worked locally?

```
> Task :AnkiDroid:packageDebugUnitTestForUnitTest
> Task :AnkiDroid:generateDebugUnitTestConfig
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.java:5: error: package org.junit.jupiter.api does not exist

import org.junit.jupiter.api.DisplayName;
> Task :AnkiDroid:compileDebugUnitTestJavaWithJavac
                            ^

```

2021-04-09 13:02 UTC, mikehardy requested changes
- does not compile
- does not follow style guide - see wiki - spacing is not consistent

2021-04-09 13:32 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.java
> +import org.junit.jupiter.api.DisplayName;
Remove this line. You don't use DisplayName anywhere and we clearly have no reason to depend of Jupiter

2021-04-09 13:34 UTC, Arthur-Milchior commented
You don't have to do
```md
> * [heavy_check_mark  ] UI Changes: You have tested your change using the Google Accessibility Scanner
```
Just using `[x]` will create a check mark
```md
> * [x] UI Changes: You have tested your change using the Google Accessibility Scanner
```

as in

[x] this example

2021-04-09 13:43 UTC, 3mmar7amed commented on AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.java
> +import org.junit.jupiter.api.DisplayName;
i forgot to remove it, i will now

2021-04-09 13:43 UTC, 3mmar7amed commented
> * does not compile
> * does not follow style guide - see wiki - spacing is not consistent

I will

2021-04-11 00:48 UTC, david-allison-1 requested changes

2021-04-11 00:48 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.java
> +        x.put(200 , 1150) ;
Could you auto-format this file in Android Studio? It's missing a lot of our code style: https://github.com/ankidroid/Anki-Android/wiki/Code-style

2021-04-11 00:48 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.java
> +package com.ichi2.utils;
Needs a copyright header

2021-04-12 21:22 UTC, m4r4c00ch0 commented
@3mmar7amed what do you think of removing the pretending "test" from your tests? In terms of readability, I think it can already be inferred. After all, you are in the `test` folder and are using the `@Test` JUnit decorators :)

2021-04-12 21:23 UTC, m4r4c00ch0 commented on AnkiDroid/src/test/java/com/ichi2/utils/MapUtilTest.java
> +    public void testGetKeyByValue_IsNotEqual() {
What about this?

```suggestion
    public void getKeyByValue_IsNotEqual() {
```

2021-04-12 21:42 UTC, 3mmar7amed commented on AnkiDroid/src/test/java/com/ichi2/utils/MapUtilTest.java
> +    public void testGetKeyByValue_IsNotEqual() {
I've just restyled it based on what I read in wiki

2021-04-17 03:11 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/utils/MapUtilTest.java
> +    public void testGetKeyByValue_IsNotEqual() {
Can you please link me to the part of the wiki you're making reference too? I can't figure out which rule would apply here.

2021-04-17 03:11 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.java
> +     * Actually the array will not expand as this value is set to the in the index in arraylist not add to .
I don't understand this sentenec

2021-04-17 03:11 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.java
> +    @Test(expected = AssertionError.class)
Why do you expect an error while last action is an equality assertion?

2021-04-17 03:11 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.java
> +    @Test(expected = AssertionError.class)
Same questions as above

2021-04-20 19:00 UTC, 3mmar7amed commented on AnkiDroid/src/test/java/com/ichi2/utils/MapUtilTest.java
> +    public void testGetKeyByValue_IsNotEqual() {
https://github.com/ankidroid/Anki-Android/wiki/Code-style#test-method-names-should-be-composed-by-a-name-representing-what-is-being-tested-and-a-name-stating-which-specific-case-is-being-tested-separated-with-underscore

2021-04-20 19:15 UTC, 3mmar7amed commented on AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.java
> +     * Actually the array will not expand as this value is set to the in the index in arraylist not add to .
JSONArray file called a function called "put" which is in json\JSONArray file ..  json\JSONArray class defines an ArrayList called (values) and "put" function which takes data  " put (index , value )" , and this is how it works :
while (values.size() <= index) {
            values.add(null);
        }
        values.set(index, value);
it uses the "set" function not "add" ... that means when I insert in the beginning or in the middle the array will not expand, but it will when I insert an index that is bigger than the array size

2021-04-20 19:22 UTC, 3mmar7amed commented on AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.java
> +    @Test(expected = AssertionError.class)
as I assert that the arrayLength will increase and that's not true and will through an error. the array doesn't expand when i insert at the beginning

2021-04-22 02:57 UTC, david-allison-1 requested changes

2021-04-22 02:57 UTC, david-allison-1 commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.8.3-all.zip
Can you revert this

2021-04-22 02:57 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/utils/MapUtilTest.java
> +}
This spacing change isn't necessary

2021-04-22 02:57 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/utils/MapUtilTest.java
> +    public void testGetKeyByValue_IsEqual() {
No need to restyle tests. Could you revert this, it's not relevant to the PR, and we'll fix each code style issue in a targeted fix

Aside: I think these code style rules for tests should be debated, I'm not a fan

2021-04-22 02:57 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.java
> +    public void initializeArray() {
This would be more grokkable if it returned a value, rather than mutated local state

Passing in the length as a parameter would make more sense to me

2021-04-24 03:04 UTC, 3mmar7amed commented on AnkiDroid/src/test/java/com/ichi2/utils/MapUtilTest.java
> +    public void testGetKeyByValue_IsEqual() {
in JSONArrayTest file , should i change my style of naming again?? i made it like the above.

2021-04-24 03:22 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/utils/MapUtilTest.java
> +    public void testGetKeyByValue_IsEqual() {
Personally: might as well stick with the code style. Now isn't the time to debate the merits of it.

But, it's not a good idea to change naming/functionality (this file) unless it's relevant to the PR

2021-04-24 03:22 UTC, david-allison-1 commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.8.3-all.zip
This hasn't been reverted

2021-04-24 05:00 UTC, 3mmar7amed commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.8.3-all.zip
I do it but it gives me "Failed to open zip file", so I change it to " 6.8.2-bin "  and it works.

2021-04-24 14:36 UTC, mikehardy commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.8.3-all.zip
@3mmar7amed then you have something corrupt in your local caches somewhere with regard to gradle. 6.8.3-bin and -all are valid gradle distribution names and both work. But we choose bin normally as it's smaller. We're on gradle 7.0 now anyway if you rebase over master branch current and try again.

2021-04-24 21:23 UTC, mikehardy commented
Unfortunately the way you've done this makes the diff very difficult to read.

I expect to see precisely zero commits related to gradle in this PR, I expect to see only lines changed that relate to the PR

On quite a few of the recent PRs there is guidance on how to "git rebase" if you search for them. What I expect is that your specific commits are the only commits here, rebased on to current master HEAD so all the gradle 7 stuff is already there but not in the PR, so that all the other commits dropped.

2021-04-26 03:42 UTC, 3mmar7amed commented
now I am stuck. how can I resolve this conflict?

2021-04-27 18:02 UTC, m4r4c00ch0 commented
@3mmar7amed perhaps do a rebase from the `master` branch of this repository (not your fork) :)

2021-04-28 16:46 UTC, mikehardy requested changes
There is no reason anything related to gradle should be in this test PR.
The gradle commit should not be present, and merge commits are also not ideal.
I strongly suggest getting more familiar with git commands, specifically git rebase - it's important to submit clean PRs to this repo so that we are able to review and merge them effectively

2021-04-28 19:23 UTC, prateek-singh-3212 commented
@3mmar7amed  Hi Ammar,
If you need any kind of help regarding GIT then I will be happy to help you

2021-04-28 19:23 UTC, prateek-singh-3212 commented
@3mmar7amed Hi Ammar,
If you need any kind of help regarding GIT, I will be happy to help you.

2021-04-28 22:36 UTC, mikehardy commented
Take that offer!! :-) :-) - git takes a while to get used to, and we can't merge changes until the PR has the right commits in it

2021-04-29 04:31 UTC, 3mmar7amed commented
> @3mmar7amed Hi Ammar,
> If you need any kind of help regarding GIT, I will be happy to help you.

thanks a lot, I would be very happy if you do. I removed every commits related to Gradle change and did a rebase. am I done now?

2021-04-29 05:58 UTC, prateek-singh-3212 commented
>  I done now?

No, Not now. We have to clean the commit history.  

The last good commit is [bf5a0eb ](https://github.com/ankidroid/Anki-Android/pull/8524/commits/83324fec409fe9e1abef2275f80906a698125c02). Am I right? After this commit do you changed anything in the JSONArrayTest file?

2021-04-29 08:03 UTC, 3mmar7amed commented
> > I done now?
> 
> No, Not now. We have to clean the commit history.
> 
> The last good commit is [bf5a0eb ](https://github.com/ankidroid/Anki-Android/pull/8524/commits/83324fec409fe9e1abef2275f80906a698125c02). Am I right? After this commit do you changed anything in the JSONArrayTest file?



> > I done now?
> 
> No, Not now. We have to clean the commit history.
> 
> The last good commit is [bf5a0eb ](https://github.com/ankidroid/Anki-Android/pull/8524/commits/83324fec409fe9e1abef2275f80906a698125c02). Am I right? After this commit do you changed anything in the JSONArrayTest file?

yes I changed . this is the last good commit (00142855e7d0a549ed669902a6a0d4ae6192259b)

2021-04-29 09:40 UTC, prateek-singh-3212 commented
Okay then let's join google meet.  Whenever you are free just ping me on discord.

meet.google.com/zpb-ncgs-hxe 
Or dial: (US) +1 402-662-1249 
PIN: 730 532 120#

2021-04-29 09:44 UTC, prateek-singh-3212 commented
Okay then let's join gsoc-talk channel on discord. Whenever you are free just ping me on discord.

2021-05-02 05:14 UTC, 3mmar7amed commented
the same file in another PR :
https://github.com/ankidroid/Anki-Android/pull/8752

2021-05-02 15:55 UTC, closed without merging