Fixes #5404: Prevent potential memory leaks due to AnkiStatsTaskHandler's AsyncTasks & amend its Singleton pattern
ankidroid/Anki-Android pull request #8531
Opened 2021-04-09 13:32 UTC by farjadilyas

## Purpose / Description
AsyncTasks in AnkiStatsTaskHandler are non-static & hold references to View objects. This can lead to potential memory leaks.

## Fixes
Fixes #5404 

## Approach

- It replaces the strong references to view objects in AsyncTasks with WeakReferences
- Turns the extended AsyncTasks into static inner classes
- Checks if a weakly referenced object isn't null before using. Attempts to update UI only if view objects exist.

## How Has This Been Tested?
-  Tested on SAMSUNG SM-A805F API 29 (Physical Device)
- Pixel 3a XL API 27 (Emulator)
- Pixel 2 API 24 (Emulator)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
No UI changes

2021-04-09 13:40 UTC, farjadilyas commented
I have only made changes to CreateChartTask for now. If this seems like the right approach, I can go ahead and make the changes for the other two AsyncTask inner classes in AnkiStatsTaskHandler.java & other non-static inner classes extending AsyncTask

2021-04-09 16:08 UTC, david-allison-1 requested changes
This looks good to me, aside from the comments:

* Could you change the commit message header to 50 chars
* Could you stick the additional information that you added to the PR template into the commit message body

2021-04-09 16:08 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java
> +                ChartBuilder chartBuilder = new ChartBuilder(mImageView.get(), collectionData,
Don't use `mImageView.get()`, just in case - extract the concrete reference and use that.

2021-04-09 16:08 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java
> +        mTaskHandler = AnkiStatsTaskHandler.getInstance(col);
Could you explain this change?

2021-04-09 16:09 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java
> +        mTaskHandler = AnkiStatsTaskHandler.getInstance(col);
Nevermind - I see: `new AnkiStatsTaskHandler()` was setting `sInstance`

2021-04-10 10:01 UTC, Arthur-Milchior commented
Do we know why it was using AsyncTask directly and not a CollectionTask ? Especially since both uses the same executor, the default one.

Seems good really. My question is really about current code, not about this PR

2021-04-10 15:32 UTC, farjadilyas commented
> Do we know why it was using AsyncTask directly and not a CollectionTask ? Especially since both uses the same executor, the default one.
> 
> Seems good really. My question is really about current code, not about this PR

That's a good point! I haven't been able to figure out why CollectionTask wasn't used since it can basically replace AsyncTask. I implemented one of the AsyncTasks: CreateChartTask using CollectionTask and it works just fine. Should we move to use CollectionTask instead of the 3 AsyncTasks in AnkiStatsTaskHandler since extending the Task class is more understandable than extending the AsyncTask class itself? 

Also, since ```mContext``` in CollectionTask is only used in doInBackground() & getContext() isn't used, we can make it a local variable and get rid of the Lint warning: 'This field leaks a Context object'.

2021-04-10 23:48 UTC, david-allison-1 approved these changes
Looks good to me, thanks!

2021-04-14 03:14 UTC, mikehardy requested changes
All of my comments are trivial - the PR itself is good, just spacing or explicit parentheses items, nothing important.

It seems like there was some unfinished conversation around using CollectionTask - that seems like it could make a good follow-on PR if you are interested, but since this has been reviewed by everyone already and all that's left is trivial formatting stuff, probably best to just polish this and get it in

Thank you!

2021-04-14 03:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java
> +            if (todayStatString != null && mIsRunning && textView != null) {
```suggestion
            if ((todayStatString != null) && mIsRunning && (textView != null)) {
```

2021-04-14 03:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java
> +            if (html != null && mIsRunning && webView != null && progressBar != null) {
```suggestion
            if ((html != null) && mIsRunning && (webView != null) && (progressBar != null)) {
```

2021-04-14 03:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java
> +            if (plotSheet != null && mIsRunning && imageView != null && progressBar != null) {
```suggestion
            if ((plotSheet != null) && mIsRunning && (imageView != null) && (progressBar != null)) {
```

2021-04-14 03:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java
> +                if (!mIsRunning || collectionData == null) {
```suggestion
                if (!mIsRunning || (collectionData == null)) {
```

2021-04-14 03:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java
> +                if (!mIsRunning || collectionData == null) {
```suggestion
                if (!mIsRunning || (collectionData == null)) {
```

2021-04-14 03:14 UTC, mikehardy commented
maintainer note: happy for anyone to merge after my batch of trivial nitpicks is handled

2021-04-14 12:44 UTC, mikehardy approved these changes
Nice! And the rebase / force-push for clean commit history +1

2021-04-14 12:45 UTC, merged