Fixes Code style for non-public, non-static fields #8387
ankidroid/Anki-Android pull request #8532
Opened 2021-04-09 18:35 UTC by Arnold2381

## Purpose / Description
Change the formatting issues according to #8370 

## Fixes
Fixes some of #8387 

## Approach
Followed #8370, added those changes ran gradlew lintRelease to generate a report of all the issues and solve errors accordingly. 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-09 18:38 UTC, Arnold2381 commented
@david-allison-1 I think you can merge #8370 with master and run the tests again after this will be merged. we are good to go.

In 5 files I added suppress warning just check those once too.

2021-04-09 18:59 UTC, david-allison-1 requested changes
Thanks!!

2021-04-09 18:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +@SuppressLint("FieldNamingPatternDetector")
This one should be fine to translate

2021-04-09 18:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java
> +        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
Please revert/rebase this out - we shouldn't bundle in changes into a refactoring PR

2021-04-09 18:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.java
> +@SuppressLint("FieldNamingPatternDetector")
Same - I think this should be fine to translate?

2021-04-09 18:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
> +@SuppressLint("FieldNamingPatternDetector")
Just do it for the individual field, not the class, you can do this with the Alt+Enter menu on the error

2021-04-09 18:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
> +@SuppressLint("FieldNamingPatternDetector")
I don't see why this is here

2021-04-09 18:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
> +    @SuppressLint("FieldNamingPatternDetector")
ditto

2021-04-09 18:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/sync/UnifiedTrustManager.java
> +@SuppressLint("FieldNamingPatternDetector")
ditto

2021-04-09 19:55 UTC, david-allison-1 requested changes
A few of these should have been constant

Other than that, good to go

2021-04-09 19:55 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
> +    private final int mINCLUDEMEDIA = 1;
```java
    private final static int INCLUDE_SCHED = 0;
    private final static int INCLUDE_MEDIA = 1;
```

2021-04-09 19:55 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
> +    private final int mBUFFERSIZE = 1024;
```java
    private static final int BUFFER_SIZE = 1024;
```

2021-04-09 20:35 UTC, david-allison-1 commented
I missed this! This is awesome, thank you so much!!!!!!!!

2021-04-09 20:50 UTC, Arnold2381 commented
> > @david-allison-1 I think you can merge #8370 with master and run the tests again after this will be merged. we are good to go.
> > In 5 files I added suppress warning just check those once too.
> > [image](https://user-images.githubusercontent.com/46752548/114226187-e61e0700-9990-11eb-932a-c7566a7dc191.png)
> > Got this finally haha.
> 
> I missed this! This is awesome, thank you so much!!!!!!!!

No worries btw i will take some more time to resolve all this, just trying to rebase since then hope I get it.

2021-04-09 21:25 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java
> +    @SuppressLint("MissingSuperCall")
Just leave it for another pull request

2021-04-09 21:25 UTC, Arnold2381 commented
@david-allison-1 I tried my best was successful the first time, and then for the second one too I did rebase and edited in that only but I don't know why it got pushed as a seperate commit.

But now I got most of it how is it done next time would be perfect.

2021-04-09 21:25 UTC, david-allison-1 requested changes
Just one nit, then we're good to go! Thanks so much for all the effort

2021-04-09 21:26 UTC, Arnold2381 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java
> +    @SuppressLint("MissingSuperCall")
So should i remove this ?

2021-04-09 21:34 UTC, Arnold2381 commented
@david-allison-1  is everything okay now?

2021-04-09 21:37 UTC, david-allison-1 approved these changes
Fantastic!!

2021-04-09 21:38 UTC, Arnold2381 commented
Thank you!!
Finally, I learnt git rebase!! 
Relief :)

2021-04-10 12:52 UTC, mikehardy approved these changes
These kinds of changes - cleaning codebase - are probably some of the more brutal changes to do as a developer because they seem to just go on forever like a bowl of soup that is more soup than you want ;-). But seriously they help make this project sustainable for the next decade - thank you very much for plowing through the whole codebase and getting this done, I appreciate it

2021-04-10 12:53 UTC, merged