Accessibility standards for Note Editor Toolbar
ankidroid/Anki-Android pull request #8539
Opened 2021-04-10 05:52 UTC by tanmayChakrawarty

## Purpose / Description
The toolbar is changed to meet accessibility standards

## Fixes
Fixes  #8523 

## Snapshot

https://user-images.githubusercontent.com/75254780/114259856-c4536d00-99ee-11eb-9842-135962561f6f.mp4

## How Has This Been Tested?
Tested on a physical device. (Android 5.0)

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

2021-04-10 06:24 UTC, kartikeysaran commented on AnkiDroid/src/main/res/layout/note_editor_toolbar.xml
> +            android:layout_height="48dp"
No need to add this as inside the style we already have defined the layout_height and width so if you want to make any changes then make it in ``` style/note_editor_toolbar_button

2021-04-10 06:24 UTC, kartikeysaran commented on AnkiDroid/src/main/res/layout/note_editor_toolbar.xml
> +            android:layout_height="48dp"
Same here

2021-04-10 06:27 UTC, kartikeysaran requested changes
I requested some changes in the code please have a look
-> Use ``` style/note_editor_toolbar ```

2021-04-10 06:30 UTC, kartikeysaran commented
And just a suggestion please don't make changes in the master branch of the repository you forked, rather you can create separate branches. :)

2021-04-10 23:43 UTC, david-allison-1 reviewed
Something needs to be done about the plus button. Other than that, very minor nitpick

2021-04-10 23:43 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java
> +        int expectedWidth = getVisibleItemCount() * dpToPixels(56);
Extra credit if you extract these to variables (at least the padding)
```suggestion
        int expectedWidth = getVisibleItemCount() * dpToPixels(48 + 8); // width + 4dp padding on both sides
```

2021-04-10 23:43 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/note_editor.xml
> +            android:layout_marginBottom="30dp"
Only 30?

2021-04-11 06:28 UTC, tanmayChakrawarty commented on AnkiDroid/src/main/res/layout/note_editor.xml
> +            android:layout_marginBottom="30dp"
Yes, otherwise the `Cards: Card1` button gets hidden by the toolbar.

2021-04-11 06:55 UTC, kartikeysaran commented on AnkiDroid/src/main/res/layout/note_editor.xml
> +            android:layout_marginBottom="30dp"
> Yes, otherwise the `Cards: Card1` button gets hidden by the toolbar.

I don't think so as we are using ContraintLayout, will check this once :)

2021-04-11 07:10 UTC, tanmayChakrawarty commented on AnkiDroid/src/main/res/layout/note_editor.xml
> +            android:layout_marginBottom="30dp"
If I remove this 30dp bottom margin from the scroll view and increase the bottom margin of the linear layout from 28dp to 40 or 50dp that will also work.

2021-04-11 16:01 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java
> +        int expectedWidth = getVisibleItemCount() * dpToPixels(widthDp+2*fourDp); //width + 4dp padding on both sides
```suggestion
        int expectedWidth = getVisibleItemCount() * dpToPixels(widthDp + 2 * fourDp); //width + 4dp padding on both sides
```

2021-04-11 16:02 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java
>          int fourDp = (int) Math.ceil(4 / context.getResources().getDisplayMetrics().density);
This is 4DP converted to another unit

2021-04-11 16:07 UTC, tanmayChakrawarty commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java
>          int fourDp = (int) Math.ceil(4 / context.getResources().getDisplayMetrics().density);
Should I change it to (48 + 2 * 4) like this?

2021-04-11 16:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java
>          int fourDp = (int) Math.ceil(4 / context.getResources().getDisplayMetrics().density);
yeah, that'll work

2021-04-11 17:13 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/dimens.xml
> +    <dimen name="note_editor_toolbar_height">50dp</dimen>
I think: 24+4 -> 28
48 + 4 -> 52

```suggestion
    <dimen name="note_editor_toolbar_height">52dp</dimen>
```

2021-04-11 17:13 UTC, david-allison-1 reviewed
Still a pending question about the plus button - I think there's more code that needs to be looked at

2021-04-12 07:59 UTC, tanmayChakrawarty commented
> Still a pending question about the plus button - I think there's more code that needs to be looked at

Yes, the spacing at the end is not there. Any idea or suggestion that can be done to make it appropriate?

2021-04-12 12:21 UTC, david-allison-1 commented
> > Still a pending question about the plus button - I think there's more code that needs to be looked at
> 
> Yes, the spacing at the end is not there. Any idea or suggestion that can be done to make it appropriate?

The relevant code is:

https://github.com/ankidroid/Anki-Android/blob/4ef14ff97d8d517ea500e9f5b4a0da11973ed90e/AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java#L176-L217

Or the caller to this code.

Use the Android Studio "Layout Inspector" to see the difference between the icons. On change I made was to enforce a 24dp size of the drawable (and scale the container), but I feel there's more to do, it still doesn't look perfect

![image](https://user-images.githubusercontent.com/62114487/114393328-cd307400-9b91-11eb-864f-45bf818ed269.png)

2021-04-15 15:16 UTC, tanmayChakrawarty commented
@david-allison-1 This is working but is this a good way?

![Screenshot (395)](https://user-images.githubusercontent.com/75254780/114893718-9d9c9880-9e2b-11eb-80da-044f62fcc363.png)

2021-04-28 06:08 UTC, tanmayChakrawarty commented
@david-allison-1  Sorry for the delay. Now it looks like this.


https://user-images.githubusercontent.com/75254780/116354407-fdc11080-a815-11eb-8f12-2d6e36345938.mp4

2021-04-28 08:47 UTC, david-allison-1 approved these changes
Looks good, thanks!

For second approver: only concern is that the cloze icon may not be immediately visible. I'm thinking that we can remove a few that are likely to be unused (horizontal line / title)?

2021-04-30 02:03 UTC, merged

2021-05-09 15:16 UTC, mikehardy commented
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!