NF: comment and simplify DismissNote
ankidroid/Anki-Android pull request #8540
Opened 2021-04-10 06:01 UTC by Arthur-Milchior

2021-04-10 16:16 UTC, david-allison-1 reviewed
Flagging this for a later review - assumed it would be a simple change to review

2021-04-10 16:16 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +     *
```suggestion
     * Represents an action that removes a card from the Reviewer without reviewing it.
```

2021-04-10 18:44 UTC, david-allison-1 requested changes
Doesn't compile

2021-04-10 18:44 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +            MCard suspendedCard = mCard.clone();
```suggestion
            Card suspendedCard = mCard.clone();
```

2021-04-10 18:44 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +            // suspend mCard
```suggestion
            // suspend card
```

2021-04-10 18:44 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +         * The art of the task that is specific to this object. E.g. suspending, deleting, burying...
```suggestion
         * The task that is specific to this object. E.g. suspending, deleting, burying...
```

2021-04-10 18:44 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +         *                       Cancelling only means that the next card don't have to be sent, however the action should still be peformed.
I struggle to understand this. Could you consider revising

2021-04-11 03:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +         * The art of the task that is specific to this object. E.g. suspending, deleting, burying...
the Part of the task

It was just missing a letter. Thanks

2021-04-11 03:49 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +         *                       Cancelling only means that the next card don't have to be sent, however the action should still be peformed.
Done

2021-04-11 13:17 UTC, david-allison-1 approved these changes
Thanks! LGTM

2021-04-14 03:16 UTC, mikehardy approved these changes
Works for me - thanks @Arthur-Milchior !

2021-04-14 03:16 UTC, merged