NF: rename `Undoable` to `UndoAction`
ankidroid/Anki-Android pull request #8541
Opened 2021-04-10 06:01 UTC by Arthur-Milchior

This name is more descriptive of the actual use of this class

2021-04-10 16:19 UTC, david-allison-1 requested changes
Two strange changes, rest looks good

2021-04-10 16:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
> +    UndoAction undoType() {
?

2021-04-10 16:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/UndoAction.java
> +    UndoAction revertToProvidedState (@StringRes int undoNameId, Card card){
?

2021-04-11 08:41 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
> +    UndoAction undoType() {
It seems to be a side effect of android studio automated renaming.
Related to a very discussion on discord about new line and annotation

2021-04-11 13:42 UTC, david-allison-1 approved these changes
LGTM

2021-04-11 13:43 UTC, merged