NF: `DismissNotes`'s `actualTask` return whether it succeeded
ankidroid/Anki-Android pull request #8544
Opened 2021-04-10 06:07 UTC by Arthur-Milchior

Indeed, it always returned one out of two values. Using false or true is nicer

2021-04-10 16:24 UTC, david-allison-1 requested changes
miniscule nit

2021-04-10 16:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                    if (! succeeded ) {
```suggestion
                    if (!succeeded ) {
```

2021-04-11 08:44 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                    if (! succeeded ) {
Done

2021-04-11 13:58 UTC, david-allison-1 approved these changes
LGTM

2021-04-14 03:18 UTC, mikehardy approved these changes
Yeah, a boolean is >> a null when possible, nice

2021-04-14 03:18 UTC, merged

2021-04-14 16:49 UTC, Arthur-Milchior commented
I just checked in Python. `True > None` raise an exception