fix for updating ui on suspend
ankidroid/Anki-Android pull request #8545
Opened 2021-04-10 06:59 UTC by sumadithya

## Purpose / Description
To fix UI update inconsistencies for suspend and flagging.

## Fixes
Fixes https://github.com/ankidroid/Anki-Android/issues/7992

## Approach
Updates the UI by notifying that db has been changed.

## How Has This Been Tested?
Tested on a Physical Device: Xiaomi Redmi 6 Pro

## Learning (optional, can help others)
There are still inconsistencies in card count and changing the available options. Most of them stem from using different IDs for different things inconsistently. Also, I'm not sure whether having duplicate cards in a deck is intentional or a bug. If it is a bug, that needs to be fixed and all issues related to the one this PR is fixing including itself will be obsoleted.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-10 07:28 UTC, prateek-singh-3212 commented
Hi @sumadithya,
Congratulations for your first PR. Could you upload the video of your fix?

2021-04-10 07:39 UTC, sumadithya commented
> Hi @sumadithya,
> Congratulations for your first PR. Could you upload the video of your fix?

https://imgur.com/TBoy7Z0

2021-04-10 10:38 UTC, Arthur-Milchior reviewed
Hi,

Thanks a lot for your first PR.
Solving an issue in three lines is rare and I love being able to review so quickly.

I've a few questions and remark. Maybe I missed something, please feel free to let me know if one remark seems wrong to you

2021-04-10 10:38 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +            browser.endMultiSelectMode();
We do not want to end multi select mode.

If a user spent a lot of time selecting a lot of specific card and want to do multiple things (suspend, changing deck) we will NOT remove the selection for them.

2021-04-10 10:38 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +            browser.searchCards();
This is a big functional change, and I don't want it.

If the user used "is:suspended" in their search query, and now unsuspends card, it means that the card will disappear from the search result, while the user may still expect to do other things to it.
It's a really important change in behavior. I:
* do not want it without serious discussion to know whether we want it
* if we do it, we do it on all actions, not just on suspend/bury. Otherwise we become inconsistent

2021-04-10 10:38 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +            browser.mCardsAdapter.notifyDataSetChanged();
This ones makes a lot of change. If you just keep this very specific line, I would expect the bug to be fixed. Can you please test and let me know?
If so, nice catch. Really great to find it, it's obvious now that I see it.

I'd like to note that I would assume that the same problem exists with marking and flagging. Can you test that also ? If you find the same problem, hopefully we can apply the same solution

2021-04-10 11:14 UTC, sumadithya commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +            browser.mCardsAdapter.notifyDataSetChanged();
* Flag card handler extends suspend card handler (I did not make this change) so it is expected to work (and I did test it as well and it works).
* Did not test for mark card handler (it doesn't extend suspend card handler), I would make changes accordingly.
* Without 'browser.searchCards()' it crashes randomly, although I was not able to test it consistently, I would try to work on it.

2021-04-10 11:25 UTC, sumadithya commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +            browser.mCardsAdapter.notifyDataSetChanged();
I tested it, It does not fix the issue with that one line.

2021-04-10 11:26 UTC, sumadithya commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +            browser.endMultiSelectMode();
Got it. I just assumed it was a bug.

2021-04-10 11:35 UTC, sumadithya commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +            browser.searchCards();
There were inconsistencies on how a card is referred to in the code, 'position', 'id' and the object  are used differently.
Normally it should not be a problem. But this issue is only reproducible when a deck has duplicate cards (I don't know if having duplicate cards is intended). Upon suspending cards, the UI does not update the color for duplicates. I could see what searchCards() does differently, but I took the lazy route and thought the use case you mentioned above should be an expected result.

2021-04-10 12:18 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +            browser.endMultiSelectMode();
I really appreciate that you want to fix bugs. 

We usually open an issue for bugs, but since it's such a small correction, it would have been acceptable to directly do the PR.

However, what really matters is that your commit explain what you are doing. If you fix a bug, the commit should state it. It should ideally contains a regression test if possible. I would like you to explicit this kind of things in future PR (if you still accept to contribute)

2021-04-10 12:20 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +            browser.searchCards();
What do you call a "duplicate card" ? 
Do you mean "two cards of the same note"? Like the Cards 1 and 2 of a "Basic and Reverse" note type ?

We almost always follow upstream, anki desktop. Anki desktop do not update the list until the user explicitly ask for it. We won't do it either.

There are very good reason to update, there are also very good reason not to update. We may decide one day to change the default behavior, but it must be discussed before and that we list it in our change log

2021-04-10 12:21 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +            browser.mCardsAdapter.notifyDataSetChanged();
Thank you very much for the report.

2021-04-10 13:53 UTC, sumadithya commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +            browser.searchCards();
No, I understand what Cards 1 and 2 of a 'basic and reverse' are. I'm talking about exact copies of same cards.
I mentioned this in one [issue](https://github.com/ankidroid/Anki-Android/issues/8547).
If you don't want to see that issue, please try this [deck](https://ankiweb.net/shared/info/1225334140) on Anki-droid to see duplicate cards.

2021-04-10 14:00 UTC, sumadithya commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +            browser.searchCards();
The duplicates affect a lot of things including card count, search (duplicates are not accounted for).

2021-04-10 14:50 UTC, sumadithya commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +            browser.searchCards();
> There are very good reason to update, there are also very good reason not to update. We may decide one day to change the default behavior, but it must be discussed before and that we list it in our change log.

I'm not challenging your statement but, I would really like to know if it is documented somewhere, I want to know more about it.

2021-04-10 23:57 UTC, david-allison-1 requested changes
I'll let Arthur handle the initial review. 

I'd like to see a Unit Test here. Card searching is currently far too complicated, and it's very easy to introduce regressions. Stronger testing will allow us to verify this fix, and will allow us to move towards a better structure for the Card Browser

2021-06-03 11:43 UTC, david-allison-1 commented
@sumadithya Can this be closed given your comment on the issue?

2021-06-05 14:57 UTC, sumadithya commented
@david-allison-1 
Please close this. But this pull isn't the fix for the issue.

2021-06-06 09:37 UTC, closed without merging