NF: Improve DeckPreviewStatistics type
ankidroid/Anki-Android pull request #8549
Opened 2021-04-10 10:00 UTC by Arthur-Milchior

2021-04-10 17:02 UTC, david-allison-1 requested changes

2021-04-10 17:02 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java
> +                mTextView = params[1].second;
This looks incorrect (params only has one element). Could you put in a regression test if this wasn't caught by our suite
 
```suggestion
                mTextView = params[1].second;
```

2021-04-11 13:57 UTC, david-allison-1 approved these changes
LGTM

2021-04-14 03:19 UTC, mikehardy approved these changes
Code gets a little bit better all the time, thanks Arthur!

2021-04-14 03:19 UTC, merged