Add unit tests for NamedJSONComparator class
ankidroid/Anki-Android pull request #8557
Opened 2021-04-10 16:33 UTC by ShridharGoel

## Purpose / Description
Add unit tests for `NamedJSONComparator` class.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-10 16:43 UTC, david-allison-1 requested changes
Looks good, one nit for readability

2021-04-10 16:43 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/utils/NamedJSONComparatorTest.java
> +        assertNotEquals(NamedJSONComparator.INSTANCE.compare(firstObject, secondObject), 0);
It would be best to assert the sign of the value, this can be done with `Hamcrest`'s `assertThat(n, [greater/less]Than[orEqualTo](0));`

2021-04-10 17:07 UTC, ShridharGoel commented on AnkiDroid/src/test/java/com/ichi2/utils/NamedJSONComparatorTest.java
> +        assertNotEquals(NamedJSONComparator.INSTANCE.compare(firstObject, secondObject), 0);
Updated.

2021-04-10 18:09 UTC, david-allison-1 approved these changes
LGTM

2021-04-13 17:26 UTC, ShridharGoel commented
@mikehardy Please have a look.

2021-04-14 03:35 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/utils/NamedJSONComparatorTest.java
> +@RunWith(RobolectricTestRunner.class)
I wonder - I think this one might be possible with just AndroidJUnit4Runner? I ask because Robolectric is an amazing framework, but it gives you a database and all sorts of other things which makes tests that use it a lot heavier. This one might be possible as a more pure / lightweight unit test via AndroidJUnit4 only?

2021-04-14 03:35 UTC, mikehardy reviewed
Indeed - that is one clean test - I am curious if Robolectric runner is needed as I commented in situ - but in general it's good to go pending answer to that question

2021-04-14 07:06 UTC, ShridharGoel commented on AnkiDroid/src/test/java/com/ichi2/utils/NamedJSONComparatorTest.java
> +@RunWith(RobolectricTestRunner.class)
Yes, it is possible with `AndroidJUnit4`. Updated.

2021-04-14 07:07 UTC, ShridharGoel commented
@mikehardy Updated.

2021-04-14 12:35 UTC, mikehardy approved these changes
Nice - should be just a bit quicker with pure JUnit vs Robolectric, not the *most* important thing - correctness is more important than speed, but if you can have both... glad that works! Thanks

2021-04-14 12:35 UTC, merged

2021-05-09 15:16 UTC, mikehardy commented
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!