NF: add some NonNull for notes
ankidroid/Anki-Android pull request #8570
Opened 2021-04-11 08:31 UTC by Arthur-Milchior

2021-04-11 13:52 UTC, david-allison-1 requested changes
I feel the inline annotations are for discussion, I don't feel they add value.

Would happily accept the method annotations in another PR (or in this one if you feel the same way about inline annotations) so we can get this moving

2021-04-11 13:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
> +        @NonNull Note n = getCol().newNote(model);
I don't think we need this now `newNote` is `@NonNull`

2021-04-11 13:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
> +                @NonNull com.ichi2.libanki.Note newNote = new com.ichi2.libanki.Note(col, model); // for some reason we cannot pass modelId in here
I don't see why we need this

2021-04-11 13:59 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
> +        @NonNull Note n = getCol().newNote(model);
When I read code below, I wanted to know whether `n` could be null or not. This kind of annotation ensure that I don't get to think about what `newNote` does, I see immediately that the variable is NonNull without having to care about how it was created

2021-04-11 14:05 UTC, Arthur-Milchior commented
Split into https://github.com/ankidroid/Anki-Android/pull/8574

2021-04-14 18:32 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
> +        @NonNull Note n = getCol().newNote(model);
I actually kind of like it even it is over-specifying, in the same way I like brain-dead explicit parentheses around every boolean clause in a compound conditional. Not necessary at all but I manage my cognitive load fiercely (to guard against cases where I'm distracted and don't even realize it! resulting in sub-standard reviews) so any tricks I/we can employ to make things more brain-dead are things I'm +1 on...within reason

This one seems "within reason" to me, so I like it.

2021-04-14 18:33 UTC, mikehardy commented
@Arthur-Milchior this took conflicts but if you fix and re-push we may re-examine?

2021-04-14 18:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
> +                @NonNull com.ichi2.libanki.Note newNote = new com.ichi2.libanki.Note(col, col.getModels().get(modelId));
I'll concede on `@NonNull` from createNote, but can we reconsider `NonNull` on a constructor call?

2021-04-14 18:59 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
> +                @NonNull com.ichi2.libanki.Note newNote = new com.ichi2.libanki.Note(col, col.getModels().get(modelId));
haha - that is true. I don't imagine a new can ever return a null? That violates "within reason" I think.

2021-04-15 20:08 UTC, Arthur-Milchior commented
Rebased

2021-04-16 00:17 UTC, david-allison-1 commented
comments on constructor annotations still stand

2021-05-01 00:56 UTC, david-allison-1 commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java
> +        newNote = new Note(col, col.getModels().get(mid));
What's going on with this diff? it seems incorrect, but the code compiles

2021-05-02 13:16 UTC, Arthur-Milchior commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java
> +        newNote = new Note(col, col.getModels().get(mid));
This is clearly an error on my part. I've double checked and I see nothing similar. I guess I removed too much when I edited to remove `@NonNull`.

It compiles because `AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java` does not compile and do not block test either. I have not read read about ContentProvider so I didn't pay attention to it until then, appart that it shows in Android Studio when I search for errors

2021-05-02 16:08 UTC, mikehardy commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java
> +        newNote = new Note(col, col.getModels().get(mid));
Just chiming in to say ContentProviderTest has no problem compiling, tests fine (on emulator! it's an emulator test / 'androidTest') and does block CI if it fails...

2021-05-02 19:47 UTC, david-allison-1 approved these changes
LGTM

2021-05-02 20:16 UTC, mikehardy approved these changes

2021-05-02 20:16 UTC, merged

2021-06-23 17:27 UTC, mikehardy commented
Hi there!

Apologies for the delay, and if you're already submitted something to OpenCollective for May 2021 PRs merged, you may feel free to ignore this.

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for May 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in May)

Thanks!