Added Color Picker
ankidroid/Anki-Android pull request #8575
Opened 2021-04-11 18:33 UTC by sakshi-1604

## Pull Request template

## Purpose / Description
Added Color Picker option in Note Editor Toolbar

## Fixes
Fixes #8466

## Approach
Just made some major changes in layout note_editor_toolbar.xml  and Toolbar.java to add option to change color .

## Screenshot

![Screenshot_1618164871](https://user-images.githubusercontent.com/65847879/114316720-4ee8b900-9b22-11eb-8a73-504f38c1b10c.png)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-11 22:11 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java
> +                        Toast.makeText(getContext(), "onColorSelected: 0x" + Integer.toHexString(selectedColor), Toast.LENGTH_SHORT).show();
Use UiUtils.showThemedToast instead of using Toast.makeText if you really want to use Toast message.
My preference is that we should not use toast messages.

2021-04-11 22:11 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/drawable-nodpi/ic_color_picker_red_24.xml
> +    android:viewportHeight="24" android:viewportWidth="24"
```suggestion
    android:viewportHeight="24"
    android:viewportWidth="24"
```
Put all the attributes in new line. In all xml files.

2021-04-12 03:44 UTC, ritvij14 reviewed
I think it would be great if you could add some screenshots of how this looks since this is a UI/UX fix.

2021-04-12 04:26 UTC, prateek-singh-3212 commented
> I think it would be great if you could add some screenshots of how this looks since this is a UI/UX fix.



> I think it would be great if you could add some screenshots of how this looks since this is a UI/UX fix.

yes, Please share the video of your fix so that it will be easier for us to review.

2021-04-12 04:39 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/layout/note_editor_toolbar.xml
> +                android:contentDescription="Red"
put hardcoded strings("Red") in the string resource file.

2021-04-12 04:41 UTC, mrudultora commented on AnkiDroid/src/main/res/layout/note_editor_toolbar.xml
> +                android:contentDescription="Red"
@prateek-singh-3212 The strings are for `contentDescription`. I don't think these strings require translations.

2021-04-12 04:45 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/res/layout/note_editor_toolbar.xml
> +                android:contentDescription="Red"
@mrudultora  It is throwing errors in Lint checks.

2021-04-12 05:08 UTC, mrudultora commented on AnkiDroid/src/main/res/layout/note_editor_toolbar.xml
> +                android:contentDescription="Red"
Hmm, I saw that, maybe `contentDescription` could be removed as it only gives warning.

2021-04-12 16:56 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java
> +        setClick(R.id.note_editor_toolbar_color_blue,"<span style=\"color:blue;\">","</span>");
```suggestion
        setClick(R.id.note_editor_toolbar_color_blue, "<span style=\"color:blue;\">", "</span>");
```

2021-04-12 16:56 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java
> +        setClick(R.id.note_editor_toolbar_color_green,"<span style=\"color:green;\">","</span>");
```suggestion
        setClick(R.id.note_editor_toolbar_color_green, "<span style=\"color:green;\">", "</span>");
```

2021-04-12 16:56 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java
> +        setClick(R.id.note_editor_toolbar_color_yellow,"<span style=\"color:yellow;\">","</span>");
```suggestion
        setClick(R.id.note_editor_toolbar_color_yellow, "<span style=\"color:yellow;\">", "</span>");
```

2021-04-12 16:56 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java
> +        setClick(R.id.note_editor_toolbar_color_white,"<span style=\"color:white;\">","</span>");
```suggestion
        setClick(R.id.note_editor_toolbar_color_white, "<span style=\"color:white;\">", "</span>");
```

2021-04-12 16:56 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java
> +        setClick(R.id.note_editor_toolbar_color_black,"<span style=\"color:black;\">","</span>");
```suggestion
        setClick(R.id.note_editor_toolbar_color_black, "<span style=\"color:black;\">", "</span>");
```

2021-04-12 16:56 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java
> +                        onFormat(new TextWrapper("<span style=\"color:"+"#"+Integer.toHexString(selectedColor)+";\">","</span>"));
```suggestion
                        onFormat(new TextWrapper("<span style=\"color:" + "#" + Integer.toHexString(selectedColor) + ";\">" , "</span>"));
```

2021-04-15 16:40 UTC, sakshi-1604 commented
Thanks @kartikeysaran for helping me in resolving this issue.

2021-04-25 00:50 UTC, mikehardy commented on AnkiDroid/build.gradle
> +    implementation 'com.github.QuadFlask:colorpicker:0.0.15'
QuadFlask:colorpicker is dead code. We need a maintained library, something that receives regular attention, has a lot of github stars and not a lot of github issues ideally.
https://android-arsenal.com/tag/18?sort=updated&category=1

2021-04-25 00:51 UTC, mikehardy requested changes
Can't take dead libraries on board - I left a comment with the link I would use to search up new libraries

2021-05-01 00:54 UTC, david-allison-1 requested changes
Looks good!

Could you update the screenshots in the OP?

Main question: could you rebase onto the latest master and run the accessibility scanner? I think that this will have taken a conflict with https://github.com/ankidroid/Anki-Android/pull/8539 and margins will want to be updated

2021-05-01 00:54 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java
> +        LinearLayout note_toolbar_internal_layout = (LinearLayout) this.mToolbar.getChildAt(1);
Can you get the view by Id

2021-05-01 00:54 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java
> +            AppCompatImageButton button = (AppCompatImageButton) note_toolbar_internal_layout.getChildAt(i);
Can we add a comment stating what we're doing here?

2021-05-01 00:54 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java
> -
nit: revert spacing change

2021-05-01 00:54 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/note_editor_toolbar.xml
> +                app:srcCompat="@drawable/ic_color_picker_24"
can you add a tag for a keyboard shortcut?

2021-06-26 12:39 UTC, prateek-singh-3212 commented
Hi @sakshi-1604  are you interested in changing  this PR. I think you can  use @mrudultora color picker now. I would like to see this color picker in Ankidroid. @mikehardy @david-allison-1  what are your thoughts on this PR.

Mrudul's Color Picker - https://github.com/mrudultora/Colorpicker

2021-06-26 12:48 UTC, mikehardy commented
I just asked @mrudultora the same thing on a related PR, just looking for current status and what he thinks at the moment. If I understand correctly everyone is either just finishing with exams for university or about to take them, so to be clear I understand if nothing is actually happening now :-), just want to know what people *want* to do in the future

2021-09-04 03:37 UTC, closed without merging