Fixing gestures with answer buttons not working
ankidroid/Anki-Android pull request #8579
Opened 2021-04-11 20:46 UTC by kuroni

## Purpose / Description
Fixing gestures with answer buttons not working on the latest alpha release.

## Fixes
Fixes #8527 and #8572.

## Approach
Completely removing the usage of `performClickWithAction`, opting to `answerCard`, since only touching actions on buttons are registered now.

## How Has This Been Tested?

Tested on my physical device.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2021-04-11 20:50 UTC, david-allison-1 approved these changes
LGTM, will add in a follow-up issue to add back the visual feedback

2021-04-11 20:50 UTC, david-allison-1 requested changes
Tests failing

2021-04-11 21:06 UTC, kuroni commented
Ooops, totally did not expect the method to come up there :sweat:

2021-04-11 21:17 UTC, david-allison-1 approved these changes
Ditto previous: will need a follow-up issue to fix the visual regression

2021-04-11 23:08 UTC, kuroni commented
> LGTM, will add in a follow-up issue to add back the visual feedback

Sorry, which visual feedback is this? I'm not totally clear.

2021-04-11 23:28 UTC, david-allison-1 commented
Hmm.... interesting. No regression here at all. I don't use gestures, but from the method name, I would have presumed that they would have animated the answer buttons

2021-04-12 00:32 UTC, david-allison-1 commented
@kuroni, apologies for the wasted effort, given [your comment](https://github.com/ankidroid/Anki-Android/issues/8583#issuecomment-817402056), I feel that a revert (#8584) is going to be the correct solution for now

2021-04-12 00:33 UTC, david-allison-1 commented
Will leave to the second reviewer to decide on the course of action

2021-04-12 23:57 UTC, kuroni commented
@david-allison-1 I've implemented the suggestions from https://github.com/ankidroid/Anki-Android/issues/8583#issuecomment-817801198, the change brought back the feedback on my device. However I got unit tests failed here.

2021-04-13 02:02 UTC, david-allison-1 requested changes
The button still doesn't "feel" right to me: I had an instance (non-reproducible) where the highlighting wasn't removed.

The other issue is that pressing, dragging your finger off, and letting go of the button no longer stops the execution (and there doesn't seem to be an `ACTION_CANCEL` fired all the time).

As a proposed solution:

* Use a class which encapsulates both the touch and click listener
* on Touch (down), set the variable from the current card and return false to not consume the action
* on click, check the variable and perform the action
* Apply both the click and the touch listener to the view

I think that would be the best of both worlds.

Don't feel the need to do this. Totally optional, and I'd be happy to take it on (let me know!). Don't want to be changing scope of a PR, and this feels like a rewrite at this stage

2021-04-13 03:22 UTC, kuroni commented
I think I'm up to the task; just give me a day or two.

2021-04-14 23:40 UTC, kuroni commented
So after implementing for a while, I came into this problem where you cannot use the gesture for answer buttons. The reason is simple: we only set `mPrevCard` at `onTouch`, and when you use gesture you don't touch the ease layout.

2021-04-15 02:34 UTC, kuroni commented
Please don't approve the current commit, there's a bug with the current logic.

Namely, suppose that you touch the button, but then moved your finger away from the button, that will trigger an `onTouch` event (which will set `mHasBeenTouched` to `true`), but will not trigger an `onClick` event. Now, if we let the card auto skip to the next card, and perform swipe, it will not register, because swiping only triggers the `onClick` event, which has both conditions on `mPrevCard` and `mHasBeenTouched` false.

I'm still trying to find a feasible action that can behave like `onTouch` with `ACTION_UP`, but is fired after `onClick` rather than before, but for now I cannot find anything like it ...

2021-04-17 18:07 UTC, kuroni commented
Sorry, I just came back to this. I think I've covered the logic issue. @david-allison-1 can you take a look at the changes please?

2021-04-17 18:18 UTC, david-allison-1 reviewed
Tested (& with keyboard) and all looks good.

Minor documentation nit and good to go

2021-04-17 18:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                float diffX = Math.abs(event.getRawX() - mTouchX);
We could do with more comments here, particularly: explain the order of operations (touch before onClick) so a future developer understands why this logic exists

2021-04-17 18:59 UTC, kuroni commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                float diffX = Math.abs(event.getRawX() - mTouchX);
Resolved

2021-04-17 19:08 UTC, david-allison-1 approved these changes
LGTM! Thanks

2021-04-18 14:43 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
> +        // Note: Couldn't get a spy working, so overriding the method
I have these same difficulties sometimes, but getting a test in (even if it requires some hackery) is fantastic

2021-04-18 15:00 UTC, david-allison-1 commented
@mikehardy Are we good to go with this?

2021-04-18 15:02 UTC, mikehardy requested changes
This is one of our biggest items for release-2.15, thank you for tackling this!
My comments are important to me (of course! :-) ) but really trivial in general, super easy to fix I think. Looking forward to merging this :rocket:

2021-04-18 15:07 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
> +        ShadowLooper.runUiThreadTasksIncludingDelayedTasks();
I added the test - we were performing a click action on a handler with a 20ms delay. This line should no longer be necessary.

2021-04-18 15:13 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
> +        ShadowLooper.runUiThreadTasksIncludingDelayedTasks();
it still may be that `IncludingDelayedTasks` is superior than our current style, which is to say, harvesting the idea might be a positive even if a bit unrelated to this now

2021-04-18 15:46 UTC, kuroni commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        private static final int CLICK_ACTION_THRESHOLD = 200;
That is indeed the case. Thank you very much!

2021-04-18 15:56 UTC, kuroni commented on AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
> +        ShadowLooper.runUiThreadTasksIncludingDelayedTasks();
I removed the line 419 from the file and the test passed. Should I go ahead and commit the removal, or do you have other suggestions (I'm not catching up with @mikehardy's latest comment so an explanation would be great)

2021-04-18 17:33 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
> +        ShadowLooper.runUiThreadTasksIncludingDelayedTasks();
if you remove the line and it works, I would commit the removal of the line yes.
Sorry I was unclear, what I was trying (badly) to communicate was that this specific wait method looks different than our current style:

https://github.com/ankidroid/Anki-Android/blob/143d7bbf7c9aa87f842d44c240c07b7cb2bd9285/AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java#L229-L245

...and as a not-really-related item maybe we should add `ShadowLooper.runUiThreadTasksIncludingDelayedTasks()` to the RobolectricTest advance method(s).

I will peel this comment off to a separate issue for investigation and consider this resolved once you commit the removal of the line in this PR

Thanks @kuroni

2021-04-18 17:35 UTC, mikehardy approved these changes
Really close now - maintainer note is that this is completely ready for merge (I think) as soon as the one shadow looper wait call is removed from a test. Approving pending that

2021-04-18 19:49 UTC, kuroni commented on AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
> +        ShadowLooper.runUiThreadTasksIncludingDelayedTasks();
Committed, thank you!

2021-04-18 20:20 UTC, merged

2021-05-09 15:16 UTC, mikehardy commented
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!