Lint fixed preferences title length
ankidroid/Anki-Android pull request #8586
Opened 2021-04-12 15:24 UTC by prateek-singh-3212

## Pull Request template

## Purpose / Description
A lint rule to ensure that preference text in English does not exceed a limit and Hints for CrowdIn to ensure that our translators do not hit the same issue
## Fixes
  Fixes #8534

## Approach
write the lint rule and parse the string XML file using XML DOM Parser.

## How Has This Been Tested?
not tested on a physical device. Done unit testing and run lint checks on terminal
## Learning (optional, can help others)
Android dev submit on Lint: https://www.youtube.com/watch?v=ffH-LD5uP4s&t=808s
Lint explanation in brief (Recommended for a developer who is new to lint ): https://youtu.be/wFe0WZm_xm8
Google GIT Lint Examples : https://android.googlesource.com/platform/tools/base/+/studio-master-dev/lint/libs/lint-checks

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-12 22:17 UTC, david-allison-1 requested changes
Great testing! This is currently inefficient O(n^2), with a big constant factor, and we can do better:  (O(n) with minimal constants)

We should also check for the `maxLength=""` attribute on the strings: https://support.crowdin.com/file-formats/android-xml/

----

Current algorithm

* For each `android:title` element:
   * Get the key
   * Load preferences.xml (slow)
   * Loop through `preferences.xml` to find the key
     * Flag if invalid  (O(n))

What we should be doing:

* Loop through each preference title and store each `key` in a `titles: Set<String>`
* Loop through the English preference string file and store the keys in a map: `key (String) -> StringLocation/Element` (I'm unsure, maybe both, maybe the StringLocation if you can get it from the element)
   * Only add to this list if it's known to be bad (> 32 chars || has no maxLength) - this will be most elements

When all files have been analysed:

* Loop through the titles
* Look up the key in the map from key -> title/location
   * If it doesn't exist, it's good
   * If it does exist, throw out an error:
      * If it's > 32 chars
      * If it doesn't have a maxLength=32 attribute

Let me know if you need more guidance on the above

https://github.com/ankidroid/Anki-Android/blob/1543f0f900be78cdf4f80a881e1f0f86e326f113/lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStrings.java#L152-L153

https://github.com/ankidroid/Anki-Android/blob/1543f0f900be78cdf4f80a881e1f0f86e326f113/lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStrings.java#L97

The two lines above should be useful in seeing the structure that we should be aiming for

2021-04-12 22:17 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +                }
We should do this another way, I'll explain in the top-level comment

2021-04-12 22:17 UTC, david-allison-1 commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.java
> +    @Test
tests are great!

2021-04-12 22:19 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesCrowdInTitleLength.java
> +public class FixedPreferencesCrowdInTitleLength extends ResourceXmlDetector {
I think this can be deleted?

2021-04-13 09:02 UTC, prateek-singh-3212 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +        if ("xml".equals(context.file.getParentFile().getName()) && element.hasAttribute(ATTR_TITLE)) {
It is checking 2 conditions:
1. If the current file is parent file of XML folder.(We can remove this because I have assigned that folderType == ResourceFolderType.XML in appliesTo method).
2. Scanning all the elements of XML file and checks that element contains android:title attribute If yes then go ahead.

2021-04-13 09:04 UTC, prateek-singh-3212 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +            Constants.ANKI_TIME_SEVERITY,
Okay

2021-04-14 06:26 UTC, prateek-singh-3212 commented
> Great testing! This is currently inefficient O(n^2), with a big constant factor, and we can do better: (O(n) with minimal constants)
> 
> We should also check for the `maxLength=""` attribute on the strings: https://support.crowdin.com/file-formats/android-xml/
> 
> Current algorithm
> 
>     * For each `android:title` element:
>       
>       * Get the key
>       * Load preferences.xml (slow)
>       * Loop through `preferences.xml` to find the key
>         
>         * Flag if invalid  (O(n))
> 
> 
> What we should be doing:
> 
>     * Loop through each preference title and store each `key` in a `titles: Set<String>`
> 
>     * Loop through the English preference string file and store the keys in a map: `key (String) -> StringLocation/Element` (I'm unsure, maybe both, maybe the StringLocation if you can get it from the element)
>       
>       * Only add to this list if it's known to be bad (> 32 chars || has no maxLength) - this will be most elements
> 
> 
> When all files have been analysed:
> 
>     * Loop through the titles
> 
>     * Look up the key in the map from key -> title/location
>       
>       * If it doesn't exist, it's good
>       * If it does exist, throw out an error:
>         
>         * If it's > 32 chars
>         * If it doesn't have a maxLength=32 attribute
> 
> 
> Let me know if you need more guidance on the above
> 
> https://github.com/ankidroid/Anki-Android/blob/1543f0f900be78cdf4f80a881e1f0f86e326f113/lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStrings.java#L152-L153
> 
> https://github.com/ankidroid/Anki-Android/blob/1543f0f900be78cdf4f80a881e1f0f86e326f113/lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStrings.java#L97
> 
> The two lines above should be useful in seeing the structure that we should be aiming for

Okay, I have noted down all the points you described above. For now, I am not having any doubt but in the future, if I have any doubt then I will let you know.

2021-04-14 06:28 UTC, prateek-singh-3212 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesCrowdInTitleLength.java
> +public class FixedPreferencesCrowdInTitleLength extends ResourceXmlDetector {
This file is part of the current issue and I am working on it.

2021-04-15 10:23 UTC, david-allison-1 commented
> Hi David,
> I am working on lint issue. I am unable to understand that why you to told to (>32 chars || has no maxLength).

Because those are all the badly named preferences.

We don't know which ones are titles at that point (there's a chance we analyze the `strings` file before the `preference` XML), so all we can do is collect the invalid strings, and later filter them to the list of invalid titles

2021-04-15 20:01 UTC, david-allison-1 requested changes
Much nicer!

Main point: since the lint check is working, let's extract the limit and increase it to 42

2021-04-17 11:38 UTC, prateek-singh-3212 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +            if ((valuesData.get(title).getFirst().hasAttribute(ATTR_MAX_LENGTH) &&
Sure

2021-04-17 12:22 UTC, prateek-singh-3212 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +                    !valuesData.get(title).getFirst().getAttribute(ATTR_MAX_LENGTH).equals("32") ||
Okay

2021-04-17 12:57 UTC, prateek-singh-3212 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +                context.report(ISSUE, valuesData.get(title).getSecond().resolve(), " "+title +" " +!valuesData.get(title).getFirst().getAttribute(ATTR_MAX_LENGTH).equals("32") + " " +( valuesData.get
@david-allison-1 are we expecting all the (Title )strings in preferences.xml file to have maxLength=32 attribute?

2021-04-17 13:45 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +                context.report(ISSUE, valuesData.get(title).getSecond().resolve(), " "+title +" " +!valuesData.get(title).getFirst().getAttribute(ATTR_MAX_LENGTH).equals("32") + " " +( valuesData.get
Yes, but let's increase the limit to 42

2021-04-17 14:00 UTC, prateek-singh-3212 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +                context.report(ISSUE, valuesData.get(title).getSecond().resolve(), " "+title +" " +!valuesData.get(title).getFirst().getAttribute(ATTR_MAX_LENGTH).equals("32") + " " +( valuesData.get
Okay, I'll change the limit to 42.

2021-04-17 17:50 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java
> -        issues.add(DirectSnackbarMakeUsage.ISSUE);
This shouldn't be removed

2021-04-17 17:50 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +    private static final String EXPLANATION = "A title with more than 32 characters may fail to display on smaller screens";
Concat this string 

```suggestion
    private static final String EXPLANATION = "A title with more than 32 characters may fail to display on smaller screens";
```

2021-04-17 17:50 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +        if ("values".equals(context.file.getParentFile().getName()) &&
Use one `if` for each of these three conditionals into an and return early if they're not hit

2021-04-17 17:50 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +            if (! valuesData.containsKey(title)) {
```suggestion
            if (!valuesData.containsKey(title)) {
```

2021-04-17 17:50 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +                context.report(ISSUE, stringData.getSecond().resolve(), message);
I think you likely want two issues with different IDs here

2021-04-17 17:50 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +    private static final int FIXED_LENGTH = 42;
rename (possibly `PREFERENCE_TITLE_MAX_LENGTH`)

I'd use 41 and perform a `>` (or a `<=`)

Let's change `maxLength=41`, as that should fix this

2021-04-17 17:50 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/utils/Constants.java
>  import com.android.tools.lint.detector.api.Severity;
try to avoid spacing changes

2021-04-17 17:50 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/utils/Constants.java
>  import com.android.tools.lint.detector.api.Severity;
try to avoid spacing changes

2021-04-17 17:53 UTC, david-allison-1 reviewed
Looking good!

You'll need a pull request, or a rebase + commit before the current set of commits fixing the lint errors. 

Would you like me to take this on?

2021-04-17 17:53 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +                    String message = String.format(Locale.ENGLISH, "Preference title '%s' is having maxLength=%s it should contain maxLength=%d", title, element.getAttribute(ATTR_MAX_LENGTH), FIXED_L
```suggestion
                    String message = String.format(Locale.ENGLISH, "Preference title '%s' has maxLength=%s instead of maxLength=%d", title, element.getAttribute(ATTR_MAX_LENGTH), FIXED_LENGTH);
```

2021-04-17 17:53 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +                context.report(ISSUE, stringData.getSecond().resolve(), message);
Optional: Adding a `LintFix` here would be useful if possible, as it will allow us to automate fixing the lint errors

2021-04-18 19:54 UTC, prateek-singh-3212 commented
> Would you like me to take this on?

Thanks for asking. I am not having any problem in doing work on this PR. I hope that I am not annoying you by requesting you to review the code. I will clean the commit history and then push the final changes.

Sorry I am bit busy today that's why I am unable to reply.

2021-04-18 20:40 UTC, david-allison-1 commented
> > Would you like me to take this on?
> 
> Thanks for asking. I am not having any problem in doing work on this PR. I hope that I am not annoying you by requesting you to review the code. I will clean the commit history and then push the final changes.
> 
> Sorry I am bit busy today that's why I am unable to reply.

Not at all - happy to do this :)

2021-04-19 12:09 UTC, david-allison-1 requested changes
There's quite a few irrelevant changes in the diff. Could you revert these (typically via `git rebase`) and rebase your branch onto master to get rid of these.

2021-04-19 17:15 UTC, david-allison-1 reviewed
Just to note: ping me and follow up via PM in Discord when it's ready for review. 

I still feel a few comments are pending. I really appreciate the effort and can't wait to see this in. It'll massively improve the app for our translators

2021-04-19 17:15 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java
> -        issues.add(DirectSnackbarMakeUsage.ISSUE);
This is still removed

2021-04-19 19:30 UTC, prateek-singh-3212 commented
> ping me and follow up via PM in Discord when it's ready for review.

Sure,

>I still feel a few comments are pending. I really appreciate the effort and can't wait to see this in. It'll massively improve the app for our translators

Sorry, I am working on this whenever I am getting free time. I will let you know whenever it is ready for review  😊

2021-04-20 06:53 UTC, prateek-singh-3212 commented
@david-allison-1 please suggest a new Title for the following:

 `    <string name="day_offset_with_description">Start of next day (0 is midnight, 23 is 11PM)</string>`[url](https://github.com/ankidroid/Anki-Android/blob/6d68424cd48ab0a702da949bd49a70eeb05f0dfd/AnkiDroid/src/main/res/values/10-preferences.xml#L160)

`    <string name="deck_conf_deck_description">Deck description (affects current deck only)</string>`[url](https://github.com/ankidroid/Anki-Android/blob/6d68424cd48ab0a702da949bd49a70eeb05f0dfd/AnkiDroid/src/main/res/values/10-preferences.xml#L205)

`    <string name="deck_conf_reminders_enabled">Enable reminder notifications for decks in this deck group</string>`[url](https://github.com/ankidroid/Anki-Android/blob/6d68424cd48ab0a702da949bd49a70eeb05f0dfd/AnkiDroid/src/main/res/values/10-preferences.xml#L269)

2021-04-20 08:10 UTC, david-allison-1 commented
@prateek-singh-3212 hold off until other maintainers have chimed in

* Enable notifications for this deck group
* Deck description (current deck only)
* Start of next day 

The final one is to be fixed properly in #8417

@mikehardy @Arthur-Milchior @infinyte7  - opinions on the above?

2021-04-20 08:49 UTC, prateek-singh-3212 commented
> @prateek-singh-3212, do these work for you?

Yes, it is absolutely fine.

2021-04-20 13:15 UTC, mikehardy commented
@david-allison-1 those all look great to me as shortenings

2021-04-20 19:22 UTC, Arthur-Milchior reviewed
I didn't know it was an issue, thanks a lot for solving it. A few extra thought.

I wonder whether it's a first time where the documents are videos instead of text. I must admit that it praticable guarantee that I will not go look at them. But that's a question of personal preferences.
If you have any documents about title's best practice, it would be appreciated too.

2021-04-20 19:22 UTC, Arthur-Milchior commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +                if (!element.getAttribute(ATTR_MAX_LENGTH).equals(Integer.toString(PREFERENCE_TITLE_MAX_LENGTH))) {
I find this kind of nested if hard to read.

I'd appreciate in this case if you could do:
* if no max_length
* elseif wrong max_length

2021-04-20 19:22 UTC, Arthur-Milchior commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +    private static final String EXPLANATION_TITLE_LENGTH = "A title with more than 41 characters may fail " +
So that the rule do not appear to be arbitrary, I'd like that the text message explain where this 41 come from. Whether it is only manual testing or whether there is a source. Probably good in the commit message too.

2021-04-20 19:22 UTC, Arthur-Milchior commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +    private static final String EXPLANATION_TITLE_LENGTH = "A title with more than 41 characters may fail " +
Other question, does this limit make sens in all languages? I am ignorant, and I can easily imagine things go wrong with non latin-based language. I don't expect RTL to be more of a problem in itself. However, I'm not sure that the notion of counting letters as a hint for space make as much sens in all locales. 
I'm not even sure that UTF-8 character that takes more than one byte, could you add test for that please?

2021-04-21 05:05 UTC, prateek-singh-3212 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +                if (!element.getAttribute(ATTR_MAX_LENGTH).equals(Integer.toString(PREFERENCE_TITLE_MAX_LENGTH))) {
sure, I will change this nesting.

2021-04-21 05:53 UTC, infinyte7 commented
Also look good to me.

2021-04-21 10:49 UTC, prateek-singh-3212 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +    private static final String EXPLANATION_TITLE_LENGTH = "A title with more than 41 characters may fail " +
>  where this 41 come from. Whether it is only manual testing or whether there is a source.

I came from manual testing. Tested on the 2.8-inch device by David.
Reference: https://github.com/ankidroid/Anki-Android/issues/8417#issuecomment-816308255

2021-04-21 11:11 UTC, prateek-singh-3212 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +    private static final String EXPLANATION_TITLE_LENGTH = "A title with more than 41 characters may fail " +
> Other question, does this limit make sens in all languages? I am ignorant, and I can easily imagine things go wrong with non latin-based language. I don't expect RTL to be more of a problem in itself. 


To be honest I didn't have that much idea about crowdin. How it deals with non-latin based Languages but I found some resources related to it hope it helps.
References: https://support.crowdin.com/file-formats/android-xml/#custom-attributes
https://support.crowdin.com/files-management/ (String Editing)

2021-04-21 11:13 UTC, prateek-singh-3212 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +    private static final String EXPLANATION_TITLE_LENGTH = "A title with more than 41 characters may fail " +
> I'm not even sure that UTF-8 character that takes more than one byte, could you add test for that please?

Sure, I will add a test of UTF-8 characters.

2021-04-23 05:28 UTC, david-allison-1 requested changes
This looks great!

Could you rebase and reorder the two commits (so we don't have a commit which fails the lint check in the history)

After that, more than happy to approve, looks great!

2021-04-23 05:28 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +    private static final String EXPLANATION_TITLE_LENGTH = "A title with more than 41 characters may fail " +
Please concat or format the 41 here

2021-04-23 06:10 UTC, prateek-singh-3212 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java
> +    private static final String EXPLANATION_TITLE_LENGTH = "A title with more than 41 characters may fail " +
Okay,  😅

2021-04-23 06:11 UTC, prateek-singh-3212 commented
@david-allison-1 Should I squash both commits?

2021-04-23 06:12 UTC, david-allison-1 commented
No, two commits are good, just reorder them

2021-04-23 15:04 UTC, david-allison-1 approved these changes
Beautiful! Maintainers: Rebase & merge

2021-04-23 15:20 UTC, oakkitten commented
why not simply allow multiline titles? i realize that it's against the guidelines, but it doesn't look bad at all and allows having titles that make sense. it's sometimes hard to make a sensible title in e.g. russian when the first line fits only two words. 

also you don't have to worry about devices with smaller screens/larger "display size" settings, languages with longer words that might not break well (e.g. german) or languages with wider letters (e.g. russian) etc

2021-04-24 00:38 UTC, Arthur-Milchior approved these changes
Same as David: beautiful work.
I'll merge it as it's clearly an improvement. However, I fear my test regarding UTF-8 was not understood properly. I'd appreciate if you can correct it and create a new PR with it. It's not blocking, so this clearly can be merged.

@oakkitten Thanks for your input. Do you have more context about it? A screenshot, or a text explaining the decision to go against the guideline? Or even the guideline itself, I don't know it actually, only that it seems to make sens to keep title short and on a single line

If there is a need to go against the guideline, justified somehow, for example by a translator, we can always reconsider or grant an exception. Still seems better to at least warn when this occur

2021-04-24 00:38 UTC, Arthur-Milchior commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.java
> +            "    <string name=\"more_characters_than_limit\"  maxLength=\"41\">This String contains character more than limit \u00A3</string>\n" +
I fear I was misunderstood here.
What I cared about is a string of, let's say, 30 characters with only wide characters. For example 30 copies of `\u00A3` takes 60 bytes in UTF-8 but is only 30 character long. So what I wanted to check is whether this was correctly counted and that the test still find this to be a valid string

2021-04-24 00:38 UTC, merged

2021-04-24 03:54 UTC, oakkitten commented
i'm not quite sure if read an actual guideline somewhere or just assumed it to be one as api-wise titles are single-line by default.

anyhow, here's a screenshot from Gmail where you can see that they do multiline titles, and also that another option not doing multiline titles fails to fit

<img src=https://user-images.githubusercontent.com/1710718/115946359-907d4a80-a4b8-11eb-8de8-48afe7e38be0.png width=300/>

as you can hopefully see the green part looks just fine. trying to cram everything into one line can lead to poor results and in some cases like this just fails to work

2021-04-24 04:01 UTC, Arthur-Milchior commented
Thanks a lot for the screenshot.

I guess we'll see whether we get to see if it raises any issues with translators or when creating new strings. We have mostly short title but it's hard to predict whether something will need a lot of space to translate

2021-04-24 04:32 UTC, oakkitten commented
btw there are some current AnkiDroid preference titles that don't fit my screen and are ellipsized, and i'm not even using the largest "display size" setting. E.g. "share usage statistics" doesn't fit, and in translation it's these same three words, just in russian. i guess you can make it just "usage statistics" and then clarify in the summary what it's about. but a good checkable preference title must be a verb phrase imo

2021-04-25 03:14 UTC, Arthur-Milchior commented
Thanks for this feedback @oakkitten. I didn't understand that it was already a problem in your language.

Ideally, you can go on crowdin and correct it, but we surely should find a way to automatize it to let translators in all languages know what should be done

2021-04-25 07:01 UTC, prateek-singh-3212 commented on lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.java
> +            "    <string name=\"more_characters_than_limit\"  maxLength=\"41\">This String contains character more than limit \u00A3</string>\n" +
Okay, I misunderstood your explanation but now it is clear I will make a new PR shortly.

2021-04-25 17:19 UTC, oakkitten commented
"share usage statistics" is a good setting name, i wouldn't want to change it. i would rather i can read the entire text.

you can tell that some translators are trying to fit text inside all single line UI elements. e.g.

> Notifications → Notify when → More than 10 cards due

becomes

> Notifications → Show which ones → When >10 cards

This does fit a single line but without the “due” it makes no sense.

(to be frank, a few settings are quite confusing in english as well. e.g.

* New card position. this implies there's some list of cards and when you create a new card this controls where it is placed. i'm guessing this is absolutely not what this setting is about
* Learn ahead limit. i have no idea what this is
* Timebox time limit. same.
* App bar buttons. i think AnkiDroid is the only app i've got that calls the toolbar "app bar"
* Day theme → Plain. what does a plain theme mean? the regular theme is pretty plain too. “grayscale” might be more descriptive
* "Center align. Center the content of cards vertically". the title here gives no useful information. the summary has the needed information and is a full sentence. Why not change summary to title, and remove summary altogether? It feels like every preference in AnkiDroid has to have a summary, even if it adds no value
* "Disable Single-Field Edit Mode. Allows 'Cloze Deletion' context menu when in landscape mode". i.. just don't understand any of this

and i can go on...)

2021-05-09 15:15 UTC, mikehardy commented
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!