Feature/lint/direct toast make text rule
ankidroid/Anki-Android pull request #8588
Opened 2021-04-12 17:27 UTC by nicdard

## Pull Request template

## Purpose / Description
Spare code review time and make the codebase cleaner by suggesting people to use `UIUtils.showThemedToast` instead of the `Toast.makeText`.

## Fixes
https://github.com/ankidroid/Anki-Android/issues/8576

## Approach
Implement a custom lint rule.

## How Has This Been Tested?
Unit tests are provided together with the implementation. Also,the lint report has been generated and the IDE provides visual feedback on the working rule.

## Learning (optional, can help others)
https://developer.android.com/studio/write/lint
https://proandroiddev.com/implementing-your-first-android-lint-rule-6e572383b292
https://proandroiddev.com/testing-your-first-android-lint-rule-bb78c1f2d2bd

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-12 18:07 UTC, prateek-singh-3212 reviewed
@nicdard Thanks for your first PR.
Everything looks good to me.

2021-04-12 18:12 UTC, prateek-singh-3212 commented
@nicdard please replace 

> #8576
with

> Fixes #8576
so that it will automatically link with issue.

2021-04-12 18:42 UTC, nicdard commented
> @nicdard please edit
> 
> > #8576
> 
> with
> 
> > Fixes #8576
> 
> so that it will automatically link with issue.

Thank you!
I hope now is ok :)

2021-04-13 00:36 UTC, david-allison-1 reviewed
This is really clean

* Could you `git rebase -i` (Or: `Git - Log - Interactively Rebase from Here` in Android Studio for a visual editor) and switch the ordering of the commits around.

If commits in the repository don't compile/pass lint, then it makes it harder for us to use `git bisect` to diagnose bugs

2021-04-13 00:36 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java
> +        issues.add(DirectSystemCurrentTimeMillisUsage.ISSUE);
Could you either revert this ordering change, or add it in a separate commit - it makes it harder to quickly see what's changed

2021-04-13 00:36 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectToastMakeTextUsage.java
> +    static final String DESCRIPTION = "Use the UIUtils.showThemedToast method instead of Toast.makeText";
Little more concise

```suggestion
    static final String DESCRIPTION = "Use UIUtils.showThemedToast instead of Toast.makeText";
```

2021-04-13 00:36 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java
> +    public static void showThemedToast(Context context, int textResource, boolean shortLength) {
This means that users get a warning if they don't pass in a `R.string`
```java
    public static void showThemedToast(Context context, @StringRes int textResource, boolean shortLength) {
```

2021-04-13 08:05 UTC, nicdard commented on AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java
> +    public static void showThemedToast(Context context, int textResource, boolean shortLength) {
Didn't know, thank you for pointing it out! :)

2021-04-13 08:05 UTC, nicdard commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectToastMakeTextUsage.java
> +    static final String DESCRIPTION = "Use the UIUtils.showThemedToast method instead of Toast.makeText";
Good

2021-04-13 08:05 UTC, nicdard commented on lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java
> +        issues.add(DirectSystemCurrentTimeMillisUsage.ISSUE);
Yes sorry!

2021-04-13 08:33 UTC, nicdard commented
For the future: are there some predefined types or scopes for commit messages?

2021-04-13 10:26 UTC, nicdard commented
I am wondering about the other helpers in `UIUtils`: do we want to implement similar lint rules as well (for example for showThemedSnackbar)? In case I can work on this in another PR :)

2021-04-13 16:10 UTC, david-allison-1 commented
> I am wondering about the other helpers in `UIUtils`: do we want to implement similar lint rules as well (for example for showSnackbar)? In case I can work on this in another PR :)

Yes, but they're less likely to be used. It's best to keep it to 1 PR per issue, but if you fancy tackling snackbars, then pull requests welcome :)

2021-04-13 16:11 UTC, david-allison-1 commented
> For the future: are there some predefined types or scopes for commit messages?

No: I'll typically use `fix`, `nf` (non-functional change) `lint` or `test`

2021-04-13 16:12 UTC, david-allison-1 approved these changes
Extremely clean, thank you!

2021-04-13 16:24 UTC, nicdard commented
> > For the future: are there some predefined types or scopes for commit messages?
> 
> No: I'll typically use `fix`, `nf` (non-functional change) `lint` or `test`

Good to know :)

2021-04-13 16:27 UTC, nicdard commented
> > I am wondering about the other helpers in `UIUtils`: do we want to implement similar lint rules as well (for example for showSnackbar)? In case I can work on this in another PR :)
> 
> Yes, but they're less likely to be used. It's best to keep it to 1 PR per issue, but if you fancy tackling snackbars, then pull requests welcome :)

Ok then, I'll figure it out if we can add a lint rule also for snackbars, since `UIUtils` contains more methods to display them and see if it is worth having it. Thank you for your advices, I'm really happy to help here :)

2021-04-13 16:53 UTC, david-allison-1 requested changes

2021-04-13 16:53 UTC, david-allison-1 commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectToastMakeTextUsage.java
> +package com.ichi2.anki.lint.rules;
Actually... just one nit: could you add a copyright header to new files?

You can set them up automatically, see the screenshot: https://github.com/ankidroid/Anki-Android/issues/8211#issue-831276255

2021-04-13 20:21 UTC, nicdard commented on lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectToastMakeTextUsage.java
> +package com.ichi2.anki.lint.rules;
Fixed!

2021-04-13 21:33 UTC, david-allison-1 approved these changes
LGTM! Thanks

2021-04-14 12:55 UTC, mikehardy commented
Specifically for the question about commit scopes, folks in the javascript ecosystem use "conventional commits", which themselves hook into "semantic versioning", and if done correctly allow you to run fully-automated releases on merge of any change, where the version number for the release is selected correctly based on the commit messages and released with the correct semantic versioning change (patch version / just a fix, minor version / new feature, major version / breaking change). Which is kind of amazing.

I use it in all the repos I can personally. react-native-device-info does fully auto releases on any merged change, react-native-firebase is a little conservative and only releases when I hit the "publish" button but the version selection is fully automated.

https://www.conventionalcommits.org/
https://semver.org/
https://semantic-release.gitbook.io/semantic-release/

2021-04-14 13:02 UTC, mikehardy requested changes
I think this looks 99% excellent and then has two tiny obvious things to fix :-)

Maintainer note: happy to see anyone merge this as soon as my comments are addressed + CI passes

2021-04-14 13:36 UTC, nicdard commented on AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java
> +    public static void showThemedToast(Context context, @StringRes  int textResource, boolean shortLength) {
Fixed!

2021-04-14 13:36 UTC, nicdard commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +        UIUtils.showThemedToast(this.getApplicationContext(), "ciao", false);
Sorry for this!

2021-04-14 13:49 UTC, nicdard commented
> Specifically for the question about commit scopes, folks in the javascript ecosystem use "conventional commits", which themselves hook into "semantic versioning", and if done correctly allow you to run fully-automated releases on merge of any change, where the version number for the release is selected correctly based on the commit messages and released with the correct semantic versioning change (patch version / just a fix, minor version / new feature, major version / breaking change). Which is kind of amazing.
> 
> I use it in all the repos I can personally. react-native-device-info does fully auto releases on any merged change, react-native-firebase is a little conservative and only releases when I hit the "publish" button but the version selection is fully automated.
> 
> https://www.conventionalcommits.org/
> https://semver.org/
> https://semantic-release.gitbook.io/semantic-release/

Thank you for those useful information! :+1:

2021-04-14 16:14 UTC, mikehardy approved these changes
Fantastic!

2021-04-14 16:15 UTC, merged

2021-04-15 08:18 UTC, mrudultora commented
@nicdard Are you implementing this one for **Snackbar** also. If not, can I take it up?

2021-04-15 09:55 UTC, nicdard commented
I did not because I realized that those are not so used as suggested by @david-allison-1 and in the meantime I have taken another issue to work on :)
You can take it up if you want :smile: :muscle:

2021-04-15 14:16 UTC, david-allison-1 commented
> If not, can I take it up?

Of course!