test: parsing hours as JUnit parameterized test
ankidroid/Anki-Android pull request #8590
Opened 2021-04-12 19:52 UTC by m4r4c00ch0

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-12 20:05 UTC, m4r4c00ch0 commented
Also, now that I see the local unit tests failing, I have to ask: are there flaky unit tests?

Sometimes when I run the `./gradlew jacocoUnitTestReport` command.

See screenshot below:

![Uploading Screen Shot 2021-04-12 at 22.05.55.png…]()

2021-04-12 20:11 UTC, Arthur-Milchior commented
Yeah, we have got flaky unit tests sometime. I did restart the test, since it seems the error was unrelated to your test.

2021-04-12 20:13 UTC, Arthur-Milchior commented
Your remark about 24:00 seems right. It would be nice if you could investigate whether that something that can be a problem for user. I don't actually remember what exactly is asked from them when the set reminder time. It may be an easy bug to fix, which would also give you a PR with code change.

In any case, it would be nice to add javadoc to `parseHours` so that it can get informations about what are the assumptions

2021-04-12 20:18 UTC, david-allison-1 requested changes
Very clean! Needs a copyright header, and a follow-up on the problematic value

2021-04-12 20:18 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/preferences/TimePreferenceTest.java
> +                {"24:00", 24}, // should this be "0"?
Yes, we should be doing this mod 24. 

Wanna comment it out and put in an issue (or fix it) so we can deal with it later and get this review in

2021-04-12 20:18 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/preferences/TimePreferenceTest.java
> +package com.ichi2.preferences;
Could you add in a copyright header?

2021-04-12 20:18 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/preferences/TimePreferenceTest.java
> +@RunWith(value = Parameterized.class)
```suggestion
@RunWith(Parameterized.class)
```

2021-04-12 21:31 UTC, m4r4c00ch0 reviewed
Added two suggestions.

- Note with the copyright notice
- Removing a comment related to undefined expected behavior

2021-04-12 21:31 UTC, m4r4c00ch0 commented on AnkiDroid/src/test/java/com/ichi2/preferences/TimePreferenceTest.java
> +package com.ichi2.preferences;
Would this be ok?

```suggestion
/****************************************************************************************
 * Copyright (c) 2021 Diego Rodriguez <diego.vincent.rodriguez@gmail.com>                              *
 *                                                                                      *
 * This program is free software; you can redistribute it and/or modify it under        *
 * the terms of the GNU General Public License as published by the Free Software        *
 * Foundation; either version 3 of the License, or (at your option) any later           *
 * version.                                                                             *
 *                                                                                      *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY      *
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A      *
 * PARTICULAR PURPOSE. See the GNU General Public License for more details.             *
 *                                                                                      *
 * You should have received a copy of the GNU General Public License along with         *
 * this program.  If not, see <http://www.gnu.org/licenses/>.                           *
 ****************************************************************************************/

package com.ichi2.preferences;
```

2021-04-12 21:31 UTC, m4r4c00ch0 commented on AnkiDroid/src/test/java/com/ichi2/preferences/TimePreferenceTest.java
> +                {"24:00", 24}, // should this be "0"?
I'll create an issue so the appropriate behavior is defined there.

```suggestion
                {"24:00", 24}
```

2021-04-12 21:48 UTC, m4r4c00ch0 commented
I added a new [issue](https://github.com/ankidroid/Anki-Android/issues/8593) referring to the problematic value.

2021-04-13 00:14 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/preferences/TimePreferenceTest.java
> +package com.ichi2.preferences;
Could you not use 

`/**************` as it plays with some of our lint checks

instead:

`/*
* content
* 
*/`

Content is good, thanks!

2021-04-13 10:16 UTC, m4r4c00ch0 commented on AnkiDroid/src/test/java/com/ichi2/preferences/TimePreferenceTest.java
> +package com.ichi2.preferences;
Fixed in https://github.com/ankidroid/Anki-Android/pull/8590/commits/ec45a3c9a01caba2077c6c44941ae896448be801

2021-04-13 11:23 UTC, david-allison-1 approved these changes
Thanks! Looks good to me!

Maintainers: squash & merge

2021-04-14 13:10 UTC, mikehardy approved these changes
Nice, thank you @m4r4c00ch0 !

2021-04-14 13:11 UTC, merged

2021-05-09 15:15 UTC, mikehardy commented
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!