Refactor: Open Previewer from CardBrowser using new Activity APIs
ankidroid/Anki-Android pull request #8620
Opened 2021-04-15 09:52 UTC by nicdard

## Pull Request template

## Purpose / Description
The old method of passing information to / starting / receiving results from one Activity to/from another Activity is deprecated in general, here we start refactoring the code to use the new androidx.activity APIs for such communication

## Fixes
Fixies https://github.com/ankidroid/Anki-Android/issues/8602
(only partially)

## Approach
Each `startActivityForResult` and corresponding case in `onActivityResult` is refactored to use the new API.
This first PR refactors only the communication between `Previewer` and `CardBrowser` in order to be sure that the style looks good before moving to the others.

## How Has This Been Tested?
On emulators: API 30 and API 25.

## Learning (optional, can help others)
https://developer.android.com/training/basics/intents/result

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-15 14:07 UTC, david-allison-1 reviewed
One quick change and good to go!

2021-04-15 14:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        if (result.getResultCode() == DeckPicker.RESULT_DB_ERROR) {
Logging here would be useful

2021-04-15 17:56 UTC, nicdard commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        if (result.getResultCode() == DeckPicker.RESULT_DB_ERROR) {
:+1:

2021-04-15 18:02 UTC, david-allison-1 approved these changes
LGTM

2021-04-16 04:02 UTC, mikehardy requested changes
This LGTM with one nitpick on the compound conditional, all the logic seems great

2021-04-16 04:02 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        if (hasChanges) {
I am really picky about compound conditionals, I like them to be as easy to read as possible - something more like this?

```suggestion
        if ((data != nul)l && 
            (data.getBooleanExtra("reloadRequired", false) || data.getBooleanExtra("noteChanged", false)) {
```

2021-04-16 06:26 UTC, nicdard commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        if (hasChanges) {
I liked to have it in a separate help variable to allow the reader not to read the condition to understand the meaning of the if statement, but I can change it :muscle: :)

2021-04-16 06:37 UTC, nicdard commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        if (hasChanges) {
Fixed!

2021-04-16 15:41 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        if (hasChanges) {
I just prefer to go the other direction - make the conditional so easy to mentally parse that it is not a problem (where possible)

2021-04-16 15:42 UTC, mikehardy approved these changes
LGTM - thanks!

2021-04-16 15:43 UTC, merged

2021-04-16 20:33 UTC, nicdard commented
@mikehardy One side note: I have seen that in `AnkiActivity` there are some help methods to start an activity with or without animation, this behavior is difficult to reproduce with the new API without replicating the same code for each call, do you have any tip about this issue?
For more clarity I can open a PR where I extract one of those calls, to let you have an example of the issue

2021-04-17 14:09 UTC, mikehardy commented
@nicdard 

> @mikehardy One side note: I have seen that in `AnkiActivity` there are some help methods to start an activity with or without animation, this behavior is difficult to reproduce with the new API without replicating the same code for each call, do you have any tip about this issue?
> For more clarity I can open a PR where I extract one of those calls, to let you have an example of the issue

Yeah I think I'd have to see it, but perhaps there is some way to use inheritance, I'm really vague on this but maybe the implementers of the activity result contract can extend some super object that handles the animation or not