Test: Check if Illegal Characters at the start of Fields get handled
ankidroid/Anki-Android pull request #8622
Opened 2021-04-15 13:18 UTC by dorrin-sot

## Purpose / Description
There didn't exist a test that checked if illegal characters would be omitted from the start of field names

## Fixes
Fixes #8612 

## Approach
Iterated through an array of illegal characters and for each of them opened a Dialog and EditText Virtually, set the text of the EditText to an invalid fieldName and clicked the confirm button of the Dialog. When the button of the Dialog is pressed, a refactored method `ModelFieldEditor::addField(EditText)` or `ModelFieldEditor::renameField(EditText)` gets called depending on which test method we are on.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-15 13:59 UTC, david-allison-1 requested changes
Really clean, thanks!

----

Are there other designs that we can use for the method extraction? I worry that the code inside `confim` is structurally far from the code in `try`, whereas in reality they're doing the same things.

Maybe we want the `modSchema` outside the method, or passed in as a runnable?

```
Runnable confirm = () -> {
                            mCol.modSchemaNoCheck();
                            TaskManager.launchCollectionTask(new CollectionTask.AddField(mMod, fieldName), listener);
                            dismissContextMenu();
                        };
```

----

Other than that, few nitpicks and we're good to go. Feel free to disagree with anything, a PR is a discussion.

2021-04-15 13:59 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java
> +        for (String forbidden : new String[] {"#", "^", "/", " ", "\t"}) {
These tests would be better as `@Parameterized`, therefore we can see individual failures, rather than one failure which would potentially hide others

2021-04-15 13:59 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java
> +package com.ichi2.anki;
Could you add a copyright header?

2021-04-15 13:59 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java
> +                .get(modelFields.size() - 1);
I think this was your intention
```suggestion
        String fieldName = modelFields.get(modelFields.size() - 1);
```

2021-04-15 13:59 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java
> +        assertThat("forbidden character detected!", !fieldName.equals(forbiddenFieldName));
Might need to check the syntax, but this gives a better error message
```java
        assertThat("forbidden character detected!", fieldName, not(equalTo(forbiddenFieldName));
```

2021-04-15 13:59 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java
> +                        exception.log();
throw the exception - test failures are good, they indicate problems

2021-04-15 13:59 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java
> +    }
Optional. Regardless, I'd question why you're using an iterator + `while` over a foreach loop

```java
        return getCol().getModels().getModels().entrySet()
                .stream()
                .filter(kvp -> kvp.getValue().getString("name").equals(modelName))
                .map(Map.Entry::getKey) // get the ID
                .findFirst()
                .orElse(0L);
```

2021-04-15 13:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
> +    void addField(EditText mFieldNameInput) throws ConfirmModSchemaException {
`fieldName`

2021-04-15 13:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
> +    @VisibleForTesting
```java
    @VisibleForTesting(otherwise = VisibleForTesting.NONE)
```

2021-04-15 13:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
> +    @VisibleForTesting
```java
    @VisibleForTesting(otherwise = VisibleForTesting.NONE)
```

2021-04-15 13:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
> +    void addField(EditText mFieldNameInput) throws ConfirmModSchemaException {
I find it useful to move the `VisibleForTesting` methods to the bottom of the class if they're unused - helps move them out of thought when reading the code, it took me a double-take to see what was happening in this change due

2021-04-15 13:59 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java
> +            String fieldName = setupInvalidFieldName(forbidden, true);
(optional): I'd be tempted to swap this boolean for an enum: `ADD_FIELD|RENAME_FIELD`

2021-04-15 14:35 UTC, dorrin-sot commented on AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java
> +    }
Oh, I did try to use Stream functions via `Stream.of(models)` but for some reason it wouldn't work. I'll fix it right now!

2021-04-15 14:41 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
> +    void addField(EditText mFieldNameInput) throws ConfirmModSchemaException {
oh ok sorry. Do I move other `VisibleForTesting` methods from other classes to bottom too or is `ModelFieldEditor` good enough?

2021-04-15 14:49 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
> +    void addField(EditText mFieldNameInput) throws ConfirmModSchemaException {
Just the ones you're working on is fine - it's an optional preference of mine, ignore if you disagree

2021-04-15 15:12 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
> +    void addField(EditText mFieldNameInput) throws ConfirmModSchemaException {
I don't understand. Do I move the `String fieldName` to the parameters instead of `EditText mFieldNameInput`?

2021-04-15 15:26 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
> +    void addField(EditText mFieldNameInput) throws ConfirmModSchemaException {
Sorry... this was a mistake, remove the `m` prefix from the variable and it's good to go

2021-04-15 15:52 UTC, dorrin-sot commented on AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java
> +                        exception.log();
Can I ask how do I replicate a `ConfirmModSchemaException` to make sure my assertion works properly?

2021-04-16 01:04 UTC, david-allison-1 approved these changes
Looks great! Minor optional changes

2021-04-16 01:04 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
nit: could you revert irrelevant spacing changes

2021-04-16 01:04 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java
> +    private String mForbiddenCharacter;
Could also define it with a `@Parameterized.Parameter()` annotation and remove the constructor

2021-04-16 01:04 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java
> +        });
That code was designed for an overzealous code analyzer that we no longer user

```suggestion
        String fieldName = setupInvalidFieldName(mForbiddenCharacter, RENAME_FIELD);

        testForIllegalCharacters(fieldName);
```

2021-04-16 03:40 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java
> +        });
I still use codacy ;-), that said, it could always be tweaked - we define(d) it's rule set

2021-04-16 09:06 UTC, dorrin-sot commented on AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java
> +    private String mForbiddenCharacter;
I'm not sure why but when I remove the constructor I get this error : `Caused by: java.lang.IllegalStateException: Provided 1 parameters, but only found fields for parameters: []`

2021-04-22 02:50 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java
> +    private String mForbiddenCharacter;
It definitely works (see other examples in the codebase), but it's not vital

2021-04-22 02:50 UTC, david-allison-1 approved these changes
Still LGTM

2021-04-22 15:14 UTC, Arthur-Milchior commented
Hi @dorrin-sot 

Please note you'll need to rebase your branch on top of master as there is conflict with current evrsion. Very sorry for this extra work

2021-04-22 19:06 UTC, mikehardy approved these changes
LGTM and a squash merge actually does appear to work...

2021-04-23 12:55 UTC, merged

2021-05-09 15:15 UTC, mikehardy commented
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!