Fix: 7173 Returning Locale.getDefault
ankidroid/Anki-Android pull request #8624
Opened 2021-04-15 15:54 UTC by kartikeysaran

## Purpose / Description
Returning Locale.getDefault()

## Fixes
Fixes #7173 

## How Has This Been Tested?

This has been tested on a Real device

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2021-04-15 16:00 UTC, david-allison-1 requested changes
I don't think this is correct

2021-04-15 16:00 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java
> +                locale = Locale.getDefault();
This returns the locale of the system, not the locale of the app

2021-04-15 16:00 UTC, david-allison-1 commented
Regardless, for something like this, a unit test displaying the problem would be fantastic

2021-04-15 16:38 UTC, kartikeysaran commented
> I don't think this is correct

I had cleared the App cache and then reopened the app the app was in Traditional Chinese would recheck this once

2021-06-15 15:42 UTC, mikehardy commented
going stale but it was a solid user complaint - would like to review + harvest the initial idea here if possible

2021-09-04 02:41 UTC, closed without merging