Enable lint for Rtl rules
ankidroid/Anki-Android pull request #8628
Opened 2021-04-15 22:54 UTC by TarekkMA

## Purpose / Description
Enable lint rules for RTL, except `RtlSymmetry` which is useless since we won't use any hardcoded directions because of `RtlHardcoded` rule

## Fixes
Fixes #8282

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-15 23:04 UTC, david-allison-1 requested changes
LGTM. One request then good to go

2021-04-15 23:04 UTC, david-allison-1 commented on lint-release.xml
> -    <issue id="RtlCompat" severity="ignore" />
Could you split this into a separate commit (so we could revert, without reverting the associated work), and move the rules to the top of the page along with the other "fatal" rules, rather than remove them?

2021-04-15 23:07 UTC, TarekkMA commented on lint-release.xml
> -    <issue id="RtlCompat" severity="ignore" />
would you suggest marking them as error or fatal?

2021-04-15 23:13 UTC, TarekkMA commented on lint-release.xml
> -    <issue id="RtlCompat" severity="ignore" />
I explicitly marked them as error and moved all RTL rules to the top of the file

2021-04-15 23:14 UTC, david-allison-1 commented on lint-release.xml
> -    <issue id="RtlCompat" severity="ignore" />
Android Studio took a long time to open, fatal, let's keep them consistent

2021-04-15 23:48 UTC, david-allison-1 commented on lint-release.xml
> +    <issue id="RtlSymmetry" severity="ignore" />
It'd be best to explain this one in a comment as well

2021-04-16 00:14 UTC, david-allison-1 approved these changes
LGTM

2021-04-16 03:46 UTC, mikehardy approved these changes
Wow, we still had so many RTL issues! Thank you

2021-04-16 03:47 UTC, merged