Extracted spinner code to DeckSpinnerSelection class
ankidroid/Anki-Android pull request #8644
Opened 2021-04-18 17:56 UTC by Akshay0701

## Need
With Current Spinner in card browser,note editor, statistics activity, user can select any deck, but
->If number of decks is very big it will be hard for the user to search a particular deck in the spinner.
->Anki-desktop does have search decks feature in browser activity.

## Work done till now:
1 Used `DeckSelectionDialog` class to implement search dialog.
2 extracted spinner code from 

# work done 

- [✔️ ] Used `DeckSelectionDialog` class to implement search dialog.

- [✔️] Extracted spinner code from Card Browser, NoteEditor, And Statistics 

## Output Pervious And Current
<img src="https://user-images.githubusercontent.com/52353967/115113787-a5824700-9fa9-11eb-8be0-55747e9f035b.gif" width="250" height="500" />----><img src="https://user-images.githubusercontent.com/52353967/115113860-fd20b280-9fa9-11eb-8272-831da5e818b4.gif" width="250" height="500" />

2021-04-18 18:00 UTC, Akshay0701 commented
I removed function from CardBrowser class and forget to make changes in test ,sorry
> Task :AnkiDroid:compileDebugUnitTestJavaWithJavac
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.java:355: error: cannot find symbol
        cb.selectDropDownItem(pos + 1);    //Adjusting for All Decks option at position 0
          ^
  symbol:   method selectDropDownItem(int)
  location: variable cb of type CardBrowser
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java:388: error: cannot find symbol
        b.selectDeckId(targetDid);

2021-04-19 10:30 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +    }
what could be alternate of this , If its only useful at method and not in whole class

2021-04-19 10:33 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
>      }
what should I do if I want to take this listener inside DeckSpinnerSelection?

2021-04-27 10:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        if (deck != null) {
invert the if to return early

2021-04-27 10:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +    }
It's best to note /why/, rather than what: having the note editor define the properties that it needs. Why does each need to be different?

2021-04-27 10:36 UTC, Akshay0701 commented
is my code causing test to fail ?

2021-04-27 10:41 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +    }
yes i understood each properties not require , so should I only create a simple boolean variable which hold value of whether parent class is noteEditor or not ?

2021-04-27 10:45 UTC, david-allison-1 commented
I expect so, those don't look like flaky tests

2021-04-27 14:27 UTC, Akshay0701 commented
![tumblr_m08nmihiRS1rqfhi2o1_500](https://user-images.githubusercontent.com/52353967/116258560-afb6f900-a792-11eb-81bd-39d4f8d58838.gif)
Done

2021-05-01 20:21 UTC, david-allison-1 requested changes
Looks good, may need to pull this and check it locally later on, it's a lot of code.

Does this add a "all decks" to the note editor? It shouldn't, but I don't see the code where this is avoided

2021-05-01 20:21 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +        mContext.getSharedPreferences(PERSISTENT_STATE_FILE, 0).edit().putLong(LAST_DECK_ID_KEY, id).apply();
Does this mean that the browser and the editor/stats share the same state? 

Do we want this? If so, make it explicit with a comment

2021-05-01 20:21 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +
nit: spacing

2021-05-01 20:21 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> -                if (!CheckCameraPermission.manifestContainsPermission(this)) {
?

2021-05-01 20:21 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        String newValue = convertToHtmlNewline(currentValue);
I think this reverts a change

2021-05-02 05:38 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +        mContext.getSharedPreferences(PERSISTENT_STATE_FILE, 0).edit().putLong(LAST_DECK_ID_KEY, id).apply();
now i applied a simple condition if its note editor then this method will not call and if it's not then "saveLastDeckId" method will call 

>   if (!mNoteEditorSpinner) {
>       saveLastDeckId(deckId);
>   }

2021-05-02 05:40 UTC, Akshay0701 commented
> Does this add "all decks" to the note editor? It shouldn't, but I don't see the code where this is avoided

No "All Decks" is not part of noteEditor deckList

2021-05-02 05:40 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        String newValue = convertToHtmlNewline(currentValue);
my rebasing fault

2021-05-02 21:52 UTC, david-allison-1 requested changes
Comments from using the feature:

* All Decks should be at the top, possibly

2021-05-02 21:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +        if (!mNoteEditorSpinner) {
Use a variable name which describes the feature, not the screen

2021-05-02 21:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +    public DeckSpinnerSelection(@NonNull AnkiActivity context, @NonNull int spinnerId, @NonNull boolean noteEditorSpinner) {
`noteEditorSpinner` would be better using a setter rather than the constructor

2021-05-02 21:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +        mContext.getSharedPreferences(PERSISTENT_STATE_FILE, 0).edit().putLong(LAST_DECK_ID_KEY, id).apply();
I don't think this addressed the question: it's useful to know if this saves it globally, or for a specific screen

2021-05-02 21:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        mDeckSpinnerSelection = new DeckSpinnerSelection(CardBrowser.this, R.id.toolbar_spinner, false);
We use `CardBrowser.this` if we're in a non-static class to refer to the outer class, not necessary here.

```suggestion
        mDeckSpinnerSelection = new DeckSpinnerSelection(this, R.id.toolbar_spinner, false);
```

2021-05-02 21:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +                lineContent = currentName ;
```suggestion
                lineContent = currentName;
```

2021-05-02 21:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +                if (!mNoteEditorSpinner) {
Use a different variable, again, with a setter

2021-05-02 21:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +        for (int dropDownDeckIdx = 0; dropDownDeckIdx < mAllDeckIds.size(); dropDownDeckIdx++) {
nit: consider extracting the "find" logic into a separate method for readability

2021-05-03 01:40 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +        mContext.getSharedPreferences(PERSISTENT_STATE_FILE, 0).edit().putLong(LAST_DECK_ID_KEY, id).apply();
Can I take this out of class and call this in onDecksSelection listener

2021-05-03 01:43 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +        mContext.getSharedPreferences(PERSISTENT_STATE_FILE, 0).edit().putLong(LAST_DECK_ID_KEY, id).apply();
Of course!

2021-05-03 07:21 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +        if (!mNoteEditorSpinner) {
can i use "mIsIncludedAllDeckOption" instead of "mNoteEditorSpinner" 
because we used this variable to add All Deck option In List

2021-05-03 07:46 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +        if (!mNoteEditorSpinner) {
Maybe `mShowAllDecks`?

2021-05-03 07:49 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +        if (!mNoteEditorSpinner) {
Yes, Thank you

2021-05-03 09:05 UTC, Akshay0701 commented
I hope now all error will get resolve

2021-05-03 18:18 UTC, david-allison-1 commented
@Akshay0701 No rush, is this ready to re-review?

2021-05-03 18:19 UTC, Akshay0701 commented
yes ,but i may not able to be active for some days

2021-05-03 18:41 UTC, david-allison-1 requested changes
Looks good, one more change needed

2021-05-03 18:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +            decks.add(0, new DeckSelectionDialog.SelectableDeck(ALL_DECKS_ID, "ALL DECKS"));
This should be translatable, I don't think it needs to be upper case

2021-05-03 18:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +            decks.add(0, new DeckSelectionDialog.SelectableDeck(ALL_DECKS_ID, "ALL DECKS"));
position 0 doesn't work: a deck named "A" comes before "ALL DECKS"

2021-05-03 18:43 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +            decks.add(0, new DeckSelectionDialog.SelectableDeck(ALL_DECKS_ID, "ALL DECKS"));
what should i do in this case ?

2021-05-03 18:44 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +            decks.add(0, new DeckSelectionDialog.SelectableDeck(ALL_DECKS_ID, "ALL DECKS"));
if i write "ALL DECKS" is small letters then it doesn't come to 0 position , I understand that if any Deck name is "AAA"
then it will appear at first position

2021-05-03 19:02 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +            decks.add(0, new DeckSelectionDialog.SelectableDeck(ALL_DECKS_ID, "ALL DECKS"));
is it okay, if I keep deckList unSorted?

2021-05-03 19:16 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +            decks.add(0, new DeckSelectionDialog.SelectableDeck(ALL_DECKS_ID, "ALL DECKS"));
You'll want to override .compareTo somewhere and special case the value if the deck ID is all decks

2021-05-04 03:50 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +            decks.add(0, new DeckSelectionDialog.SelectableDeck(ALL_DECKS_ID, "ALL DECKS"));
@Override
        public int compareTo(@NonNull SelectableDeck o) {
            if (o.mDeckId == Stats.ALL_DECKS_ID || this.mDeckId == Stats.ALL_DECKS_ID){
                return 0;
            }
            return this.mName.compareTo(o.mName);
        }

Done Master! , it works as expected, is there anything we can improve or is it good?

2021-05-04 04:15 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +            decks.add(0, new DeckSelectionDialog.SelectableDeck(ALL_DECKS_ID, "ALL DECKS"));
I don't think returning 0 is correct as that implies equality. I don't recall which, but I feel we want 1 or -1 to imply that it's always the first, and only 0 on the edge case that we have two "all decks" and are comparing them.

I think this works implicitly as you're using position 0, so it's always on the top and takes priority if the comparison returns 0.

2021-05-04 04:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +            decks.add(0, new DeckSelectionDialog.SelectableDeck(ALL_DECKS_ID, "ALL DECKS"));
Also as a note: ensure the case sensitivity of this list is the same as Anki desktop, that might be a bug

2021-05-04 04:27 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +            decks.add(0, new DeckSelectionDialog.SelectableDeck(ALL_DECKS_ID, "ALL DECKS"));
I checked -1 is correct and I removed that 0 position of AddDeck

2021-05-04 04:29 UTC, david-allison-1 commented
I think this is now just waiting for "all decks" to use the existing string constant

2021-05-04 04:32 UTC, Akshay0701 commented
> I think this is now just waiting for "all decks" to use the existing string constant

I added existing string constant for all decks

2021-05-04 04:49 UTC, david-allison-1 approved these changes
Looks good to me, thanks!

2021-05-04 17:49 UTC, mikehardy approved these changes
Nice! I continue to be jealous of your animated gif screen capture - what tool are you using??!?

2021-05-04 17:50 UTC, merged

2021-06-23 17:27 UTC, mikehardy commented
Hi there!

Apologies for the delay, and if you're already submitted something to OpenCollective for May 2021 PRs merged, you may feel free to ignore this.

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for May 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in May)

Thanks!