Add Statistics regression test to #8626
ankidroid/Anki-Android pull request #8655
Opened 2021-04-21 23:18 UTC by rodrigo-sp17

## Purpose / Description
Add regression testing to issue #8626.

## Fixes
Fixes #8631.

## Approach
An unit test was written with RobolectricRunner, calling AnkiStatsTaskHandler.createReviewSummaryStatistics() method.
The Collection parameter was mocked to return null on Collection.getDb().

## How Has This Been Tested?
Checked out commit 4809c77a4m, than wrote the test. When it started failing, checked out master on most recent commit and verified it is now passing.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-22 01:03 UTC, david-allison-1 requested changes
Looks great! Really high quality. Thank you!

A few tiny nitpicks based on AnkiDroid conventions

2021-04-22 01:03 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/stats/AnkiStatsTaskHandlerTest.java
> +@LooperMode(PAUSED)
Robolectric defaults to `PAUSED` as-of Robolectric 4.4: 

> The most noticeable item in the release is that the new PAUSED looper mode is now the default.

https://github.com/robolectric/robolectric/releases/tag/robolectric-4.4


```suggestion

```

2021-04-22 15:50 UTC, david-allison-1 approved these changes
Thanks so much!

![](https://media.giphy.com/media/tIeCLkB8geYtW/giphy.gif)

PS: Feel free to mark my review comments as 'resolved' in future

2021-04-22 16:24 UTC, rodrigo-sp17 commented
Will do!

2021-04-22 17:21 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/stats/AnkiStatsTaskHandlerTest.java
> +package com.ichi2.anki.stats;
Needs a copyright header - I think any of the files next to this one should have it (but use your ok-for-public-use email of course)

2021-04-22 17:23 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/stats/AnkiStatsTaskHandlerTest.java
> +        shadowMainLooper().idle();
Can we extend RobolectricTest and use `advanceRobolectricLooper` instead? I'm trying to keep all the Looper manipulation flowing through our own logic so that our next run of Looper de-flaking has a central point of control for async items

2021-04-22 17:23 UTC, mikehardy requested changes
always some nitpicks ;-) - looks good in general though

2021-04-23 00:29 UTC, rodrigo-sp17 commented on AnkiDroid/src/test/java/com/ichi2/anki/stats/AnkiStatsTaskHandlerTest.java
> +        shadowMainLooper().idle();
I replaced the shadowMainLooper().idle() for the advanceRobolectricLooper() method, hope it accomplished this.

2021-04-24 14:27 UTC, mikehardy approved these changes
Nice!

2021-04-24 17:34 UTC, merged

2021-05-09 15:14 UTC, mikehardy commented
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!