Fixes #8618: Add colIsOpen() checks in DeckPicker before executing dependent tasks
ankidroid/Anki-Android pull request #8666
Opened 2021-04-23 06:51 UTC by farjadilyas

## Purpose / Description
When the app would start without the Storage Permission, three predictable StorageAccessExceptions would occur in the following methods in DeckPicker:
- ```onResume()```
- ```onPrepareOptionsMenu()```
- ```onCreateOptionsMenu()``` -> ```displaySyncBadge()```

## Fixes
Fixes #8618 

## Approach
In DeckPicker, we can simply rely on ```colIsOpen()``` to check if Collection is initialized instead of using ```getColSafe()```. ```getColSafe()``` uses ```colIsOpen()``` to check if Collection is initialized, if not, it attempts to lazily initialize it. This step is not required in DeckPicker since DeckPicker's ```handleStartup()``` is responsible for initializing Collection.

More importantly, ```getColSafe()``` throws a ```StorageAccessException``` if the app doesn't have write access to the AnkiDroid directory. Hence, it follows that we should avoid calling ```getColSafe()``` when we're unsure about whether we have the Storage Permission.

The app's behavior is kept the same.

## How Has This Been Tested?
Unit tests for each collection-dependent call that had a ```colIsOpen()``` check added before it, with & without Storage Permissions to ensure the code path remains the same.

Tested on:
- Samsung Galaxy A80 API 30 (Physical Device)

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2021-04-24 21:20 UTC, mikehardy requested changes
This looks great! Rare I can only find a single thing, but I noted that you could mark the API as only visible because it's under test. Otherwise this looks good to me. Curious what @david-allison-1 thinks since he is the collection opening zen master at the moment

2021-04-24 21:20 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    protected void displaySyncBadge(Menu menu) {
I think if you are just opening access for testing you could flag it as such (and the default is private? there are examples of usage scattered all throughout the code)

```suggestion
    @VisibleForTesting
    protected void displaySyncBadge(Menu menu) {
```

2021-04-24 22:59 UTC, david-allison-1 approved these changes
Looks great, one potential follow-up

2021-04-24 22:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        }
@Arthur-Milchior This one might be better handled inside the Task architecture?

2021-04-24 23:33 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    protected void displaySyncBadge(Menu menu) {
Yes, okay! Totally forgot to add the annotation

2021-04-24 23:51 UTC, farjadilyas commented
Force pushed multiple times since I found an empty finally block in the tests which should've called ```disableNullCollection()```

2021-04-25 00:31 UTC, mikehardy approved these changes
sounds like David / Arthur may have an idea, but this LGTM
The emulator test was a flaky issue - not related to this change. I restarted it...

2021-04-25 02:22 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        }
I agree. If we expect the collection to be opened after the moment this code is reached and before the task is actually scheduled for executing, then this would prevent a valid execution

I don't know the lifecycle enough to know if it's something actually realistic

2021-04-25 02:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        }
Added: #8687 to further discuss

2021-04-25 03:16 UTC, Arthur-Milchior approved these changes

2021-04-25 03:20 UTC, merged

2021-05-09 15:14 UTC, mikehardy commented
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!