WhiteBoard : Improve UX
ankidroid/Anki-Android pull request #8715
Opened 2021-04-28 09:53 UTC by Akshay0701

## Approach
_How does this change address the problem?_

## Checklist
- [x] Implement Custom Color Picker option in whiteboard 
- [ ] Implement change stroke width feature
- [ ] Implement Zoom In And Zoom Out feature 
- [ ] Allow Users to save whiteboard image according to there choice (like PNG, JPG)
- [ ] Implement Eraser in WhiteBoard class 
## OutPut
<img src="https://user-images.githubusercontent.com/52353967/116383262-4e476680-a834-11eb-8ac1-af1627c631e7.gif" width="250" height="500" />

2021-04-28 09:57 UTC, Akshay0701 commented
if you think any feature I listed is not required then let me know, and if you have any suggestion on how more it could be useful and easily accessible to the user, then list out your idea down in comment, please : )

2021-04-28 12:11 UTC, mrudultora commented
There's already an option to save the image of whiteboard.

2021-04-28 12:25 UTC, Akshay0701 commented
Thanks! @mrudultora 

> There's already an option to save the image of the whiteboard

Yes I know, but I wanted to let the user save image according to their preference in png or jpg format 

> there's an option of undoing things in Whiteboard (not the same as an eraser but explicitly adding eraser is not needed according to me)

Your right to some extend but assume a situation where users wanted to erase a small part of the view and don't want to undo the whole view, still, your point makes sense to me

>  I don't know whether I am correct or not. But the library used by you, I think is dead (no recent commits).

Oh Thanks for informing me, I just refer this library from the previous implementation of WYSIWYG Editor, I would definitely see its alternative if required, thanks!

2021-04-28 12:43 UTC, mrudultora commented
Currently we are exporting a PNG. I particularly don't see a need for exporting a JPG. But, let's see other's views. By the way, stroke width feature would be nice and is really needed.

2021-04-30 00:56 UTC, mikehardy commented
- I think the recent "S Pen support" PR added ...sort of an erase ability? Might be able to generalize it? (should be easy to search for...was just a month or three ago)
- the custom color picker is a little problematic. There just aren't good color picker libraries out there that appear to be "alive" vs dead repos. I'd prefer to table fully custom color for now - can do it later unless you find one that is a live repo with recent commits?

2021-04-30 09:25 UTC, Akshay0701 commented
I understand and I will remove the Color Picker library, for now I think just implementing the stroke width change feature is enough.

2021-04-30 09:28 UTC, Akshay0701 commented
@mikehardy I also want to ask you,
is it worth creating Color Picker Class from scratch by our self?
because in the future implementation of Visual Editor, Color Picker is a very important feature and we may require color picker.

2021-04-30 14:06 UTC, mikehardy commented
No, worst case we will adopt one that exists. But can wait for now

2021-05-01 00:35 UTC, david-allison-1 requested changes
Looks nice, thanks!

Shouldn't be long to get this over the finish line

2021-05-01 00:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +
space change

2021-05-01 00:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +                .customView(layout,true)
```suggestion
                .customView(layout, true)
```

2021-05-01 00:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +        LinearLayout layout = new LinearLayout(mCardViewer.get());
Can we extract most of this method this to a layout file and/or class? It's rather complex to maintain as code, and is a separate concern from the whiteboard

2021-05-01 00:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +
On an empty method, please add a `// intentionally blank` comment

2021-05-01 00:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +        seekBar.setOnSeekBarChangeListener(this);
I feel this would be better as:

* An abstract class which explicitly does not implement `on[Start/Stop]TrackingTouch` (`class SeekBarProgressListener`). This would simplify the usage
* Initialising this as a lambda function, something along the lines of : `SeekBarProgressListener.setProgressListener(seekBar, x -> ??);`

2021-05-01 00:35 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/reviewer_whiteboard_pen_color.xml
>          android:layout_width="40dp"
I think it would be a good excuse to extract these `width|height|margin` into a `style` in a separate commit

2021-05-01 00:35 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/reviewer_whiteboard_pen_color.xml
> +        android:id="@+id/stroke_width"
I think we should rename the file in a separate commit if we're adding stroke width to the pen color

2021-05-01 00:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +                .negativeText(R.string.dialog_no)
This needs a title (`Stroke Width`)

2021-05-01 00:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +                .positiveText(R.string.dialog_ok)
Material guidelines: 

> Don’t use action text that fails to indicate what the selection will do. “Cancel” and “Delete” better indicate what will occur in this dialog.

https://material.io/components/dialogs#alert-dialog

In this cause, use `Save/Cancel`

2021-05-01 00:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> -
nit: spacing

2021-05-01 07:45 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +        LinearLayout layout = new LinearLayout(mCardViewer.get());
can you tell which methods and layout you expecting to extract in a separate class?

2021-05-01 07:49 UTC, Akshay0701 commented on AnkiDroid/src/main/res/layout/reviewer_whiteboard_pen_color.xml
> +        android:id="@+id/stroke_width"
`reviewer_whiteboard_edittor` is this a valid name for this layout? 

and we may need to change "Whitenoard pen color" string to "Whitenoard Editor"
<img src="https://user-images.githubusercontent.com/52353967/116775260-c190e880-aa7f-11eb-8e86-25b68f69f3d6.jpg" width="250" height="500" />

2021-05-01 08:16 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +        LinearLayout layout = new LinearLayout(mCardViewer.get());
do you want to extract all width changing code into the "WhiteBoardWidthDialog" class?

2021-05-01 08:17 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +        LinearLayout layout = new LinearLayout(mCardViewer.get());
so that we can use the same class in preference activity

2021-05-01 12:30 UTC, david-allison-1 requested changes
Much nicer!

2021-05-01 12:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +        whiteBoardWidthDialog.setWbStrokeWidth((width) ->{
Maybe `onStrokeWidthChanged`

It's unclear that Wb meant whiteboard, but I don't think it's required given the context

2021-05-01 12:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/WhiteBoardWidthDialog.java
> +        mOnStrokeWidthChanged.accept(mWbStrokeWidth);
Mark the variable as nullable and add a null check

2021-05-01 12:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/WhiteBoardWidthDialog.java
> +        SharedPreferences.Editor edit = AnkiDroidApp.getSharedPrefs(mContext).edit();
This preference is a partial responsibility of the class - saving is, loading isn't.

I feel we should move saving the preference back to `Whiteboard`

2021-05-01 15:26 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/WhiteBoardWidthDialog.java
> +                        mOnStrokeWidthChanged.accept(mWbStrokeWidth);
I was unclear - `mOnStrokeWidthChanged` can be null and we need to be concerned about that. Unsure about `mWbStrokeWidth` being null, I don't think this is valid

2021-05-01 15:51 UTC, david-allison-1 approved these changes
LGTM assuming CI passes

2021-05-01 21:32 UTC, mikehardy approved these changes
Nice - Your speed on UI changes is impressive!

2021-05-01 21:33 UTC, merged