NF: Split TagsDialog into multiple files
ankidroid/Anki-Android pull request #8717
Opened 2021-04-28 19:49 UTC by TarekkMA

## Pull Request template

## Purpose / Description
This is a continuation of #8322, moved to its own PR to reduce review complexity of the original PR

## Fixes
Fixes N/A

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-04-29 06:18 UTC, Arthur-Milchior approved these changes

2021-04-29 06:18 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.java
> +package com.ichi2.anki.dialogs.tags;
I checked this move with a diff tool, and it's okay

2021-04-29 06:18 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.java
> +package com.ichi2.anki.dialogs.tags;
I checked this move with a diff tool and it's okay

2021-04-29 22:56 UTC, mikehardy requested changes
2 missing copyright header notes but otherwise yes looks NF and should be fine?
Add the copyright headers and then anyone with merge power that sees this please merge so we may unblock #8577 :-)

2021-04-29 22:56 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.java
> +package com.ichi2.anki.dialogs.tags;
missing copyright header @TarekkMA

2021-04-29 22:56 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.java
> +package com.ichi2.anki.dialogs.tags;
missing copyright header

2021-04-30 00:41 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.java
> +package com.ichi2.anki.dialogs.tags;
alright I will add it

2021-04-30 00:44 UTC, TarekkMA commented
I did add the copyright headers.

2021-04-30 00:46 UTC, merged

2021-04-30 00:46 UTC, mikehardy commented
#8577 unblocked! Yesss! :-)

2021-05-09 15:13 UTC, mikehardy commented
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!