[ Enhancement ] Card Template Editor UI
ankidroid/Anki-Android pull request #8730
Opened 2021-04-29 14:51 UTC by Akshay0701

## Fixes
Fixes #7951

## Purpose
The problem is with the compact view of the current Card Template Editor,
So the solution I think would be changing current UI matching with AnkiDesktop, 

### So our UI may look like this: -
![Capture](https://user-images.githubusercontent.com/52353967/116512050-0c2a2d80-a8e5-11eb-9e3b-b74fd991f3c4.PNG)

## Output
<img src="https://user-images.githubusercontent.com/52353967/116570653-102b6f00-a928-11eb-806c-03ca8b8eabb3.jpg" width="250" height="500" />

2021-04-29 15:20 UTC, Akshay0701 commented
> com.ichi2.anki.tests.ContentProviderTest > testInsertAndRemoveNote[0][TestingAVD(AVD) - 11] FAILED 
> Test failed to run to completion. Reason: 'Instrumentation run failed due to 'Process crashed.''. Check device logcat for details
> Tests on TestingAVD(AVD) - 11 failed: Instrumentation run failed due to 'Process crashed.'

what should I do to fix this ?

2021-04-29 19:37 UTC, david-allison-1 requested changes
Looks good!

* Can you try having the centre text aligned it next to the button, not centred
* it feels we need a little more margin/padding between the buttons
* Could we try the text: "Front/Styling/Back" here, to provide the text more room to breathe. I don't know how this would look
* Have you tried the accessibility scanner

* What does it look like if the radiobutton labels contain too much text? New line or truncated? Is this acceptable?
* Is the content centre-aligned? I think top-aligned would be best
* What happens when the content contains more than a page? centre or top aligned?

2021-04-29 19:37 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                if (i == R.id.styling_edit) {
should work here outside the if: `mCurrentEdittextId = i;`

You'll need a better name for `i`

2021-04-29 20:04 UTC, david-allison-1 commented
Additional thoughts: 

* Can we turn off autocorrect for the text field
* Can we use a "code" font? Droid Sans Mono

2021-04-30 01:13 UTC, mikehardy commented
Oh this is exciting! The previous UI was just unusable, a real disaster (and I was partly responsible!!)

This is a big step forward

I'll review it too in my next batch

2021-04-30 04:56 UTC, Akshay0701 commented
> Could we try the text: "Front/Styling/Back" here, to provide the text more room to breathe. I don't know how this would look

- I think it requires to use "Front/Styling/Back" or otherwise layout may look like this -:


![Capture](https://user-images.githubusercontent.com/52353967/116648534-e95a5080-a99a-11eb-84f0-af72c9282913.PNG)

> Have you tried the accessibility scanner

- Oh Thanks!, I used it right now and its pretty useful, this app suggested me UI changes and i did that ,now UI look like this
- I changed content align to top ,so i think its much better now.

<img src="https://user-images.githubusercontent.com/52353967/116649890-b6fe2280-a99d-11eb-9c82-16aa7f6347c9.jpg" width="250" height="500" />

> Can we turn off autocorrect for the text field

Yes, we can do this, my idea is instead of saving all content after each textChanged ,we can save content of textView when user change the view ,like if user did some changes in front edit text and when user click to back radioButton at that time we will save our front changes ,what do you say ?

2021-04-30 12:20 UTC, david-allison-1 commented
This looks so much better! 

> > Can we turn off autocorrect for the text field
> 
> Yes, we can do this, my idea is instead of saving all content after each textChanged ,we can save content of textView when user change the view ,like if user did some changes in front edit text and when user click to back radioButton at that time we will save our front changes ,what do you say ?

I don't think this is relevant to autocorrect, it should be an attribute on the EditText

Putting the value in the model is fine, as long as it's not persisted to the database

I think the radio button area can be made a little less tall, but go with the accessibility scanner

I do think we should consider a different font choice here (droid sans mono), but other than that it looks great!

2021-04-30 12:27 UTC, Akshay0701 commented
Thanks !, And if there is any other UI-related work is pending, then let me know, I would love to do that.

2021-04-30 17:11 UTC, Akshay0701 commented
What a design now,Thanks to @infinyte7 ❤️

<img src="https://user-images.githubusercontent.com/52353967/116729706-1c392e80-aa05-11eb-8294-1f87fafded64.gif" width="250" height="500" />

2021-04-30 17:22 UTC, infinyte7 commented
Its looks good to me. Also view it in night mode, how it works.

2021-04-30 20:34 UTC, mikehardy commented
This is so much more usable, very cool. The only thing that worries me now is that people tend to get lost in UIs with two sets of tabs. I think AnkiMobile avoided that by having each card take you into the equivalent of it's own activity. That would be a really big change I think and not something I want to contemplate here even if maybe it is the "correct" thing to do for UX

What I do think might help is just altering the appearance of the top tab mar so that the whole tab bar had a line across it so it was clear that the entire bottom was a content pane, and the selected one then just stood out by being thicker or similar ?

2021-04-30 20:34 UTC, mikehardy commented
Or maybe that's worse :smile: - I'm bad at design

2021-05-01 05:54 UTC, Akshay0701 commented
![ln70bocwvxfztwt9321p](https://user-images.githubusercontent.com/52353967/116772862-68b95400-aa6f-11eb-9a02-4b45648eeae7.png)

I think Mike,we should keep our UI appearance like this, most of the Implementation done like this,it will separate the main content from tab layout and it will make little thicker

2021-05-01 10:42 UTC, Akshay0701 commented
<img src="https://user-images.githubusercontent.com/52353967/116780067-c1044c00-aa97-11eb-9334-eb1aa231db1e.gif" width="200" height="400" /> <img src="https://user-images.githubusercontent.com/52353967/116780073-cf526800-aa97-11eb-9533-6210a83486d5.gif" width="200" height="400" /> <img src="https://user-images.githubusercontent.com/52353967/116780082-de391a80-aa97-11eb-8d74-62759efe6ecd.gif" width="200" height="400" /> <img src="https://user-images.githubusercontent.com/52353967/116780093-ea24dc80-aa97-11eb-98aa-05dda81d4aef.gif" width="200" height="400" />

2021-05-01 14:18 UTC, david-allison-1 submitted a review, later dismissed
Looks great! Thanks

2021-05-01 14:23 UTC, Akshay0701 commented
but there is an error in Emulator Tests / Android Emulator Test (pull_request) ?

2021-05-02 05:04 UTC, Akshay0701 commented
Test passing in my local machine, what should I do?
![Capture](https://user-images.githubusercontent.com/52353967/116802638-f3fb1e00-ab31-11eb-9cf9-903154c74860.PNG)

2021-05-02 16:14 UTC, mikehardy commented
Hmm unsure about the test then - I just kicked off Emulator Tests again...

2021-05-02 18:54 UTC, david-allison-1 approved these changes
LGTM then

2021-05-02 20:12 UTC, mikehardy approved these changes
Just in time for release-2.15 - this is a huge UI improvement for this release, I think it may have been the most painful part of the app to use, even if most people used it rarely, it was awful when they had to. Thanks!

2021-05-02 20:13 UTC, merged