NF: introduce TaskWithoutCol to simplify code
ankidroid/Anki-Android pull request #8734
Opened 2021-04-30 13:18 UTC by Arthur-Milchior

Checking whether it's one specific class do not seems very elegant.
Ideally, having a method `boolean RequiresTheCollection()` would be ideal. However, I like the simplicity of having a
single method, as it will allow to use lambda in future commit. This keeps the code simple and still cleaner

2021-04-30 14:20 UTC, david-allison-1 reviewed
This raises a bug for a separate issue:

If `getCol()` returns null, this crashes

https://github.com/ankidroid/Anki-Android/blob/143d7bbf7c9aa87f842d44c240c07b7cb2bd9285/AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java#L1374-L1377

2021-04-30 14:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +    public static class RepairCollectionn extends TaskWithoutCol<Void, Boolean> {
nit (not for this PR): should be `RepairCollection`

2021-04-30 14:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +    public abstract static class TaskWithoutCol<ProgressBackground, ResultBackground> extends Task <ProgressBackground, ResultBackground>{}
It's unintuitive that `TaskWithoutCol` calls `getCol()`, we should have a method of `getCol()` which doesn't log if it fails.

We should have these accept an `Optional<Collection>` in the `task` method

2021-04-30 15:39 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +    public abstract static class TaskWithoutCol<ProgressBackground, ResultBackground> extends Task <ProgressBackground, ResultBackground>{}
Actually, one of the task begin by closing the collection if its opened. The other one use the collection to get context, and that's it. Probably not really necessary in the first place then.

I don't see the point of using Optional<Collection> since we always pass a collection

2021-04-30 15:40 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +    public abstract static class TaskWithoutCol<ProgressBackground, ResultBackground> extends Task <ProgressBackground, ResultBackground>{}
Actually, in one case, it needs the collection if it exists to close it. 

The difference is only that those task can proceed if the collection does not exists while all other tasks are aborted if they can't access the collection

2021-05-01 00:12 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +    public abstract static class TaskWithoutCol<ProgressBackground, ResultBackground> extends Task <ProgressBackground, ResultBackground>{}
Because it signals to the developer that the value is optional: either that or a `@Nullable`

2021-05-01 00:13 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +    public abstract static class TaskWithoutCol<ProgressBackground, ResultBackground> extends Task <ProgressBackground, ResultBackground>{}
`WithoutCol` doesn't make sense to me if the method can take a `col`, is there a better name that we can use?

2021-05-01 08:12 UTC, Arthur-Milchior commented
I changed it. I added a method. It's cleaner and do not rely on class at all anymore.

I still hope to transform some tasks into lambda, but with default method it won't actually be a trouble

2021-05-01 12:34 UTC, david-allison-1 requested changes

2021-05-01 12:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +        protected boolean requireAnOpenCollection() {
`requiresOpenCollection`

2021-05-01 17:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +        protected boolean requireAnOpenCollection() {
Done

2021-05-01 17:48 UTC, david-allison-1 approved these changes
LGTM

2021-05-01 21:13 UTC, mikehardy approved these changes

2021-05-01 21:13 UTC, merged