feat: Edit tags of a multiple notes / deck
ankidroid/Anki-Android pull request #8751
Opened 2021-05-02 00:45 UTC by TarekkMA

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes #4911

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-05-02 00:47 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.java
> -                    requireArguments().getStringArrayList(ALL_TAGS_KEY),
[note to self]

change signature of `TagsDialogListener#onSelectedTags`

revert formatting

2021-05-02 14:34 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.java
> -                    requireArguments().getStringArrayList(ALL_TAGS_KEY),
fixed

2021-05-02 23:37 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +    }
Am I doing this correctly? It does work, but I don't know if it can be done in a better way or not

2021-05-03 00:28 UTC, david-allison-1 requested changes
I really like this, thanks!

2021-05-03 00:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.java
> +         * Adding tag to a note/s
or "notes"

```suggestion
         * Adding tag to note(s)
```

2021-05-03 00:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogListener.java
> +    void onSelectedTags(List<String> selectedTags, List<String> indeterminateTags, int option);
Could you add a comment explaining what this is, or extract it to a class where the documentation can be centralised

2021-05-03 00:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                Timber.e(e, "doInBackgroundUpdateMultipleNotes - RuntimeException on updating multiple note");
```suggestion
                Timber.w(e, "doInBackgroundUpdateMultipleNotes - RuntimeException on updating multiple note");
```

2021-05-03 00:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                        }
Could you add a comment as to why you need this? I didn't think that notes would affect cards

2021-05-03 00:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +    }
We're going to get native functionality in Anki's backend later on in 2.16. 

I'd consider this to be fine for now: there's not much point putting effort into optimising, the value is going to be in all the architecture around it, rather than a method call that we can switch out

2021-05-03 00:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +    }
https://github.com/ankitects/anki/blob/abab4826bb57ade28d396acef060cc34245f0ea8/rslib/backend.proto#L239-L250 - what we'll be later be working with (probably AnkiDroid 2.17), in case this informs API design

2021-05-03 00:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.java
> + * Base on https://stackoverflow.com/a/40939367/3950497 answer.
```suggestion
 * Based on https://stackoverflow.com/a/40939367/3950497
```

2021-05-03 00:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.java
> +     * This is the listener set to the super class which is going to be evoke each
```suggestion
     * This is the listener set to the super class which is going to be invoked each
```

2021-05-03 00:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.java
> +        // checkbox status is changed from uncheck to checked.
```suggestion
        // checkbox status is changed from unchecked to checked.
```

2021-05-03 00:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.java
> +     * evoking our {@link #mPrivateListener} and therefore changing the real state.
```suggestion
     * invoking our {@link #mPrivateListener} and therefore changing the real state.
```

2021-05-03 00:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/TagsUtil.java
> +        updated.addAll(indeterminate.stream().filter(previous::contains).collect(Collectors.toList()));
Are these lists or sets? This is O(n^2) on a potentially large list and it's probably worth optimising

2021-05-03 00:28 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsListTest.java
> +        TagsList list = new TagsList(
I would find this more readable if you extracted the 3 sub-lists into named variables

2021-05-03 00:28 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsListTest.java
> +        assertFalse("Tag at index 6 should be unchecked (not indeterminate)", TAGS_LIST.isIndeterminate(6));
Are these correct? all are `assertFalse`

2021-05-03 00:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        List<Note> selectedNotes = getSelectedCardIds()
consider extracting to `CardUtils`

2021-05-03 12:12 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.java
> +public class CheckBoxTriStates extends AppCompatCheckBox {
This class is modified from https://gist.github.com/kevin-barrientos/d75a5baa13a686367d45d17aaec7f030,

I guess we should contact the author.

2021-05-03 12:12 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.java
> + * Base on https://stackoverflow.com/a/40939367/3950497 answer.
```java
 * Based on https://gist.github.com/kevin-barrientos/d75a5baa13a686367d45d17aaec7f030.
```

2021-05-03 12:19 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.java
> +         * Adding tag to a note/s
```java
         * Edit tags of note(s)
```

2021-05-03 12:20 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogListener.java
> +    void onSelectedTags(List<String> selectedTags, List<String> indeterminateTags, int option);
I will add a comment above this to explain what indeterminateTags is.

what do you mean by extracting to class ?

2021-05-03 12:28 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogListener.java
> +    void onSelectedTags(List<String> selectedTags, List<String> indeterminateTags, int option);
```java
    /**
     * Called when {@link TagsDialog} finished with editing tags.
     *
     * @param selectedTags the list of checked tags
     * @param indeterminateTags a list of indeterminate tags, their state maybe checked or unchecked, should be ignored if not expected
     * @param option selection radio option, should be ignored if not expected
     */
    void onSelectedTags(List<String> selectedTags, List<String> indeterminateTags, int option);
```

I edited it to be this

2021-05-03 12:31 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                        }
Yes in the case of tags cards wouldn't change. I can put a boolean to indicate if we want to update cards or not.

2021-05-03 12:34 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                Timber.e(e, "doInBackgroundUpdateMultipleNotes - RuntimeException on updating multiple note");
Why should it be `w`? Other tasks have it set as `e` not `w`.

2021-05-03 12:37 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +    }
when that happens we can make use `AddNoteTags` and `RemoveNoteTags` to update tags.

2021-05-03 12:40 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/utils/TagsUtil.java
> +        updated.addAll(indeterminate.stream().filter(previous::contains).collect(Collectors.toList()));
we can convert previous to a set before `previous::contains`

2021-05-03 12:41 UTC, TarekkMA commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsListTest.java
> +        assertFalse("Tag at index 6 should be unchecked (not indeterminate)", TAGS_LIST.isIndeterminate(6));
yes since these indices have tags with status (checked/unchecked).

2021-05-03 12:42 UTC, TarekkMA commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsListTest.java
> +        TagsList list = new TagsList(
you are right

2021-05-03 12:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogListener.java
> +    void onSelectedTags(List<String> selectedTags, List<String> indeterminateTags, int option);
Extracting the class would be encapsulating the set to allow consolidated documentation. I think documenting the parameter is better

I feel you can remove the word 'indeterminate' from the description, but it's good.

maybe -> may be.

Isn't this where the tags are both checked and unchecked, rather than "may be"

2021-05-03 12:53 UTC, TarekkMA commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsListTest.java
> +        TagsList list = new TagsList(
fixed

2021-05-03 12:55 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                Timber.e(e, "doInBackgroundUpdateMultipleNotes - RuntimeException on updating multiple note");
To my understand, we should be using w, as it's non-fatal but serious

https://github.com/ankidroid/Anki-Android/wiki/Code-style#the-warning-level-should-be-used-when-something-serious-and-unexpected-happened

2021-05-03 12:58 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogListener.java
> +    void onSelectedTags(List<String> selectedTags, List<String> indeterminateTags, int option);
The tag is not checked and unchecked, it's in an unknown state due to it being checked in some notes but not checked in others. so it can be checked or unchecked.

The caller must check the set of previous tags before update to determine the set of updated tags (This is what `TagsUtil#getUpdatedTags` do)

2021-05-03 13:01 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogListener.java
> +    void onSelectedTags(List<String> selectedTags, List<String> indeterminateTags, int option);
This notion of indeterminate tags is not in anki desktop, since it doesn't have a tag editor like the one in AnkiDroid. (Which is a plus for AnkiDroid)

2021-05-03 13:06 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogListener.java
> +    void onSelectedTags(List<String> selectedTags, List<String> indeterminateTags, int option);
I have included more details in the comment, please let me know if I can make it more clear.

2021-05-03 13:07 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                Timber.e(e, "doInBackgroundUpdateMultipleNotes - RuntimeException on updating multiple note");
Oh okay I understand now

2021-05-03 13:10 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        List<Note> selectedNotes = getSelectedCardIds()
`CardUtils#getNotes` already does what I need.

2021-05-03 13:16 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        List<Note> selectedNotes = getSelectedCardIds()
Should I pass the collection refrence to `CardUtils`?

2021-05-03 23:20 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.java
>                  // checked tags must appear first
Right now indeterminate tags have the same priority as checked when sorting, should we make checked then indeterminate then unchecked?

2021-05-04 20:50 UTC, TarekkMA commented
Added a test to test all tag variations are showing as expected.

2021-06-27 14:25 UTC, mikehardy commented
@TarekkMA looks like this needs re-basing as we're unwinding your stack of chained PRs - if you have a moment (and I understand it might be exam times for you! no pressure, it's not urgent) could you re-push this ?

2021-06-28 09:51 UTC, TarekkMA commented
I have just finished my exams, I will give this PR a look and repush.

2021-10-10 18:36 UTC, TarekkMA commented
Successfully deconflicted 😄

2021-10-10 21:04 UTC, mikehardy commented
Okay - I have to go through this again **BEFORE** entropy gets it again, thanks very much for working through the conflicts

2021-11-02 22:47 UTC, mikehardy commented
I pulled the PR and fixed the conflicts again - entropy is so fast

2021-11-05 02:12 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsListTest.java
> +        assertEquals("Checked tags list should not contain any duplicates  (case insensitive)\n" +
This test message should be Indeterminate not Checked tags list etc...

2021-11-05 02:18 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.java
> +         * Adding tag to a note/s
This was changed in a later commit, resolved

2021-11-05 02:20 UTC, mikehardy approved these changes
I think this one is ready for wider testing, I'd like to pull it and play with it but the code looks good at the moment at least.

2021-11-05 02:22 UTC, mikehardy commented
@david-allison-1 what do you think on this one? The test cover is really good, and it's a feature that is highly requested. I'd like to merge this to rescue it from entropy and deliver a great feature

2021-11-05 13:03 UTC, mikehardy commented
> > @david-allison-1 what do you think on this one? The test cover is really good, and it's a feature that is highly requested. I'd like to merge this to rescue it from entropy and deliver a great feature
> 
> Can this wait until Sunday? I don't have the free time to give this an appropriate amount of review or testing. Ping me if I don't look at this by Monday

Oh sure! Not a rush per se, just a statement of intention that I'd like it to not rot

2021-11-12 14:10 UTC, mikehardy commented
I just rescued it from conflict again and re-pushed

> Can this wait until Sunday? I don't have the free time to give this an appropriate amount of review or testing. Ping me if I don't look at this by Monday

Gentle nudge :-)

![](https://thumbs.gfycat.com/DigitalClassicAnchovy-max-1mb.gif)

2021-11-13 11:27 UTC, david-allison-1 approved these changes
Tested and this looks good

2021-11-13 11:27 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsListTest.java
> +        assertEquals("Checked tags list should not contain any duplicates  (case insensitive)\n" +
This seems logically correct, but it's handled by the above assert

2021-11-13 12:33 UTC, mikehardy commented
Okay, deep breath, here we go

2021-11-13 12:33 UTC, merged

2021-12-12 01:57 UTC, mikehardy commented
Hi there! November OpenCollective Notice

Apologies for the delay, and if you're already submitted something to OpenCollective for PRs merged in November 2021, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for November 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of August)

Thanks!

2021-12-12 01:57 UTC, mikehardy commented
@TarekkMA !!! We finally landed this one :heart:

2021-12-12 08:42 UTC, TarekkMA commented
This is awesome, thank you guys for your reviews and guidance.
Very proud to be a contributor to AnkiDroid ❤️.