Display study options properly on start on tablet
ankidroid/Anki-Android pull request #8756
Opened 2021-05-02 17:39 UTC by ShridharGoel

## Pull Request template

## Purpose / Description
Display study options properly on start on tablet.

## Fixes
Fixes #8755 

## Approach
`mFragmented` should be checked after it has been set in `onCreate()`.

## How Has This Been Tested?

Verified that the functionality is working.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-05-02 18:22 UTC, david-allison-1 requested changes
Could you add a test for this?

Could you also confirm that the app still opens on a corrupt/upgradeable collection?

2021-05-03 07:57 UTC, ShridharGoel commented
> Could you add a test for this?

Can it be done via Robolectric or an instrumentation test will be required (since this issue happens on tablets)?

> Could you also confirm that the app still opens on a corrupt/upgradeable collection?

How can this be checked?

2021-05-03 08:02 UTC, david-allison-1 commented
> > Could you add a test for this?
> 
> Can it be done via Robolectric or an instrumentation test will be required (since this issue happens on tablets)?
> 
> > Could you also confirm that the app still opens on a corrupt/upgradeable collection?
> 
> How can this be checked?

I've included a v16 apkg in the tests, change the DB path, close ankidroid and replace the folder's `collection.anki2`

Corruption? Copy the database file and blank one of the JSON fields in `col`

2021-05-03 08:02 UTC, david-allison-1 commented
Robolectric should be fine

2021-05-03 16:34 UTC, ShridharGoel commented
I have added the test.

2021-05-03 16:34 UTC, ShridharGoel commented
I have added a test.

2021-05-03 16:43 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
> +        assertThat("Study options should show on start on tablet", studyOptionsFragment != null, is(true));
```suggestion
        assertThat("Study options should show on start on tablet", studyOptionsFragment, notNullValue());
```

2021-05-03 16:44 UTC, david-allison-1 commented
@ShridharGoel Good to go after confirmation that you've tested this

2021-05-03 17:35 UTC, ShridharGoel commented
This exception is coming in case of corrupt collection:

```
android.database.sqlite.SQLiteDatabaseCorruptException: error while compiling: "openAnkiDroidCollection": DBError { info: "SqliteFailure(Error { code: DatabaseCorrupt, extended_code: 11 }, Some(\"database disk image is malformed\"))", kind: Other }
        at net.ankiweb.rsdroid.BackendV1Impl.openAnkiDroidCollection(BackendV1Impl.java:135)
        at net.ankiweb.rsdroid.BackendMutex.openAnkiDroidCollection(BackendMutex.java:977)
        at net.ankiweb.rsdroid.BackendUtils.openAnkiDroidCollection(BackendUtils.java:27)
        at net.ankiweb.rsdroid.database.RustSupportSQLiteOpenHelper.createRustSupportSQLiteDatabase(RustSupportSQLiteOpenHelper.java:91)
        at net.ankiweb.rsdroid.database.RustSupportSQLiteOpenHelper.getWritableDatabase(RustSupportSQLiteOpenHelper.java:72)
        at com.ichi2.libanki.DB.<init>(DB.java:80)
        at com.ichi2.libanki.backend.RustDroidBackend.openCollectionDatabase(RustDroidBackend.java:42)
        at com.ichi2.libanki.Storage.Collection(Storage.java:78)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:133)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:115)
        at com.ichi2.anki.StudyOptionsFragment.getCol(StudyOptionsFragment.java:730)
        at com.ichi2.anki.StudyOptionsFragment.configureToolbarInternal(StudyOptionsFragment.java:381)
        at com.ichi2.anki.StudyOptionsFragment.configureToolbar(StudyOptionsFragment.java:371)
        at com.ichi2.anki.StudyOptionsFragment.onCreateView(StudyOptionsFragment.java:207)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3136)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3070)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:501)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at com.ichi2.anki.AnkiActivity.onStart(AnkiActivity.java:101)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1425)
        at android.app.Activity.performStart(Activity.java:7825)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

2021-05-03 19:25 UTC, ShridharGoel commented
For corrupt collection case, it is working fine now.

> I've included a v16 apkg in the tests, change the DB path, close ankidroid and replace the folder's collection.anki2

I couldn't understand this properly. How to get the v16 apkg file?

2021-05-03 19:32 UTC, ShridharGoel commented
For the corrupt collection case, it is working fine now.

> I've included a v16 apkg in the tests, change the DB path, close ankidroid and replace the folder's collection.anki2

I couldn't understand this properly. How to get the v16 apkg file?

2021-05-05 19:29 UTC, ShridharGoel commented
@mikehardy This is almost complete. Can this also be included for release 2.15?

2021-06-02 02:42 UTC, david-allison-1 commented
> For the corrupt collection case, it is working fine now.
> 
> > I've included a v16 apkg in the tests, change the DB path, close ankidroid and replace the folder's collection.anki2
> 
> I couldn't understand this properly. How to get the v16 apkg file?

Sorry for the late reply: I'm trying a new method to manage my notifications

https://github.com/ankidroid/Anki-Android/blob/0cfc53fcbedbd3bf60bfa82ecc7aba94e3edcc3e/AnkiDroid/src/test/resources/schema16.anki2 should work

2021-06-02 14:10 UTC, david-allison-1 approved these changes
LGTM given testing worked

2021-06-02 18:32 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
> +    @Config(qualifiers = "xlarge-port")
nice trick here on the `@Config` to add a test for it! Hadn't considered that

2021-06-02 18:33 UTC, mikehardy approved these changes
LGTM thank you - esp for the testing + confirms there

2021-06-02 18:34 UTC, merged

2021-06-02 20:13 UTC, mikehardy commented
This is broken on tablets, it fails on release-2.15 branch immediately on startup when user has not granted permission.

I'm reverting the cherrypick to release-2.15 and 2.16alpha1 will not be released until fixed

Reproduction - use Pixel C emulator in landscape mode or portrait mode as first time user and open app. At least with commit hash 6a0b1d38e536c986c7531da4c45c467c49c59d66 it crashes immediately