Uses const for string key
ankidroid/Anki-Android pull request #8778
Opened 2021-05-04 22:09 UTC by Arthur-Milchior

As usual with constant, there are two goals:
* searching where the constant is used to get context
* ensuring that there is no typo

Some key used often, such as "name" was split into various constants to increase semantic

It's not all strings, just the one appearing as argument to `.get()`. That's already quite a lot

2021-05-05 00:42 UTC, david-allison-1 requested changes
I feel the risk is significantly higher than the value offered. 

Using a string constant over an embedded constant in a test is a conscious decision. We lose sight of breaking API changes if we use a constant.

This moves us further away from 1:1 compatibility with `libAnki`

This has broken a significant number of tests, and the build for Android Tests. I don't trust that my review would have caught those bugs, or ones which didn't cause test failures of compiler errors

2021-05-05 00:42 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +    private static final String MARK_CARD = "markCard";
Could you note that these are part of the JavaScript API and should not be modified?  Maybe move them to a separate class?

Moving them here encourages changing the values, which is a breaking change.

2021-05-05 00:42 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.java
> +    public static final String DID = "did";
Could you note the usage: arguments, possibly in the name or a comment

2021-06-27 14:12 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.java
> +    public static final String DID = "did";
This comment has not been addressed - @david-allison-1 what exactly do you mean here? It's been long enough that this PR has sat that perhaps being 100% prescriptive here could address it in one shot with no further back and forth?

2021-06-27 14:13 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +    private static final String MARK_CARD = "markCard";
Similar to the other comment - perhaps if more prescriptive this could be resolved in one shot and we could move on vs having it show up in the quite-expensive open-PR scans right now since the queue is so deep

2021-06-27 14:15 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.java
> +    public static final String DID = "did";
Could you state that this is specifically for the `did` passed into the fragment as an argument.

Either/or:

* rename to `ARGUMENT_DID` or similar
* Add a comment stating this is the intended usage

Have a `public static DID` encourages misuse of the variable for purposes outside the context of the fragment.

2021-06-27 14:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +    private static final String MARK_CARD = "markCard";
@mikehardy Could you elaborate on this one? I feel the intention is clear. I've re-elaborated below, but let me know if my meaning is unclear.

Extracting a string further from its usage encourages change of the string without thought about the context that a string is used in.

If a string must never be changed for API compatibility, then it should either have any of:

* an annotation stating this
* be inside a holder class for variables with an obvious purpose
* a unit test
* or be hardcoded (as it was)

2021-06-27 15:27 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +    private static final String MARK_CARD = "markCard";
Okay - that is pretty clear. I want to keep this simple then and whittle the choices down to two:

1- either these javascript API ones stay hardcoded / they are not touched here or
2- they get a holder class called something like "JavascriptAPIStrings" and the holder class has a comment that clearly mentions that any change to the strings is a Javascript API breaking change and should thus be done in a deprecation / add-new string release if possible followed by a major version bump of the API if/when the old string is removed

2021-09-02 16:46 UTC, closed without merging