Fixes #8761: Enabling second feature added in FilteredDeckOptions.java
ankidroid/Anki-Android pull request #8782
Opened 2021-05-06 18:01 UTC by Arnold2381

## Purpose / Description
Anki Desktop Filtered Deck Option had a feature of Second Filter which was missing in AnkiDroid.
## Fixes
Fixes #8761 

## Approach
After this, the enabled second feature is available and in sync with AnkiDesktop.

## How Has This Been Tested?
Physical Device and Anki Desktop
Before enabling
![image](https://user-images.githubusercontent.com/46752548/117344252-ce1fa180-aec2-11eb-9814-48541a7de653.png)

After enabling
![image](https://user-images.githubusercontent.com/46752548/117344364-ef808d80-aec2-11eb-8cf9-3a58bf622c02.png)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-05-06 18:02 UTC, Arnold2381 commented
@david-allison-1 please take a look.

2021-05-06 18:44 UTC, Akshay0701 reviewed
That's good!, I mentioned why your lint fail , take a look

2021-05-06 18:44 UTC, Akshay0701 commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="deck_conf_cram_search_2" maxLength="41">Search</string>
Duplicated values, causing lint to fail

2021-05-06 18:49 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
> +            if (mSecondFilter) {
There is two if statement used with same condition, can we write in one if statement ?

2021-05-06 22:00 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/11-arrays.xml
> +    <string-array name="cram_deck_conf_order_labels_2">
Define the array in `constants.xml` and the strings in `11-arrays`

2021-05-06 22:00 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/11-arrays.xml
> +    <string-array name="cram_deck_conf_order_labels_2">
Do we need this, or can we reuse the original array?

2021-05-06 22:00 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
> +        newOrderPrefSecond.setEntries(R.array.cram_deck_conf_order_labels_2);
I think we can get away with using the same values for both

2021-05-06 22:00 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
> +            if (newValue instanceof Boolean){
Could you extract this to a method?

2021-05-06 22:00 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
> +                    JSONArray narr = new JSONArray(Arrays.asList("\"deck:*\"",20,5));
```suggestion
                    JSONArray narr = new JSONArray(Arrays.asList("\"deck:*\"", 20, 5));
```

2021-05-06 22:00 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
>              mPref.registerOnSharedPreferenceChangeListener(this);
spacing changed

2021-05-06 22:00 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
> +            if (newValue instanceof Boolean){
This logic is no longer in `commit`, could we move it there?

2021-05-07 09:37 UTC, Arnold2381 commented on AnkiDroid/src/main/res/values/11-arrays.xml
> +    <string-array name="cram_deck_conf_order_labels_2">
Yes, I reused it.

2021-05-07 09:40 UTC, Arnold2381 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
> +            if (newValue instanceof Boolean){
I don't think we can do that. Because `commit` will be called twice after changes. And I tried calling the `second_filter_listener` function from `commit` it changes the value of the checkbox back to the same.

2021-06-01 00:35 UTC, david-allison-1 reviewed
Sorry this took me so long to get to. Got snowed under with notifications

* second filter should only be visible in SchedV2
* There's a lot of whitespace space between "Reschedule" and "Enable second filter"

A few tests to confirm that the search is as expected and matches Anki Desktop would be vital here.

2021-06-01 00:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
> +            if (newValue instanceof Boolean){
invert this if for readability

2021-06-01 00:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
> +                    JSONArray narr = new JSONArray(Arrays.asList("\"deck:*\"", 20, 5));
Could you add a comment confirming that this is what Anki Desktop does?

2021-06-01 00:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
> +    private void second_filter_listener()
This would be better named: `setupSecondFilterListener`

2021-06-01 00:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
> +        android.preference.CheckBoxPreference second_filter_sign = (android.preference.CheckBoxPreference) this.findPreference("filter_second");
nit: the naming of these variables should be camelCase

2021-06-01 00:36 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
> +            if (newValue instanceof Boolean){
I was referring to the code inside the lambda, I feel the remainder of the code could stay, but implementer's choice

2021-06-27 14:16 UTC, mikehardy commented
@Arnold2381 I'm excited to see this new feature land on AnkiDroid! It looks like there are a few comments that definitely need to be addressed before we merge

2021-06-28 12:07 UTC, Arnold2381 commented
> @Arnold2381 I'm excited to see this new feature land on AnkiDroid! It looks like there are a few comments that definitely need to be addressed before we merge

Sorry I was caught up with other things. I couldn't contribute much. I will try to make the changes asap and get it merged.

2021-06-28 13:59 UTC, Arnold2381 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
> +                    JSONArray narr = new JSONArray(Arrays.asList("\"deck:*\"", 20, 5));
Yea it is doing the same, just that its updated now and it no longer adds `"\"deck:*\""` but an empty string.

2021-06-28 14:52 UTC, Arnold2381 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
> +            if (newValue instanceof Boolean){
I didn't get this. What do I have to invert?

2021-06-29 22:30 UTC, david-allison-1 reviewed
Only nitpicks, looks great!

2021-06-29 22:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
> +                            JSONArray ar = mDeck.getJSONArray("terms");
extract the common code: `JSONArray ar = mDeck.getJSONArray("terms");` out of the if/else chain

2021-06-29 22:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
> +                    JSONArray narr = new JSONArray(Arrays.asList("", 20, 5));
Could you add a link to the defaults here: https://github.com/ankitects/anki/blob/1b15069b248a8f86f9bd4b3c66a9bfeab8dfb2b8/qt/aqt/filtered_deck.py#L148-L149

2021-06-29 22:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
> +            if (newValue instanceof Boolean){
Aim to reduce horizontal nesting in procedures like so:

```java
if (!(newValue instanceof Boolean)) {
    return true;
}
````

2021-06-30 10:07 UTC, Arnold2381 commented
@david-allison-1  PTAL.

2021-06-30 10:29 UTC, david-allison-1 commented
@Arnold2381 could you try rebasing this on master. The code looks good to me (happy to mark as ready for review), but there are (very likely) unrelated unit test failure

2021-06-30 11:18 UTC, Arnold2381 commented
@david-allison-1 it failed.

2021-06-30 11:20 UTC, david-allison-1 commented
Can you fetch master and try a rebase instead of a merge?

2021-06-30 11:46 UTC, Arnold2381 commented
I think i messed it up.

2021-06-30 12:22 UTC, david-allison-1 commented
I'm busy today, I'll aim to get to this tomorrow and see what we can do, sorry for the delay

2021-06-30 12:45 UTC, Arnold2381 commented
No problem.Sure!

2021-07-02 00:19 UTC, david-allison-1 commented
Could you rebase this on master and it should work

2021-07-02 06:03 UTC, Arnold2381 commented
```
git fetch origin   
git rebase origin/master 
```
@david-allison-1 this is how is it done right?

2021-07-02 13:39 UTC, david-allison-1 commented
Looks correct to me.

Can also do it in Android Studio

2021-07-02 14:24 UTC, Akshay0701 requested changes

2021-07-02 14:24 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
> +
revert this

2021-07-02 14:24 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
> +                android.preference.ListPreference newOrderPrefSecond = (android.preference.ListPreference) findPreference("order_2");
findPreferenceis deprecated, 

Is there a non-deprecated equivalent?

2021-07-02 14:43 UTC, Arnold2381 commented on AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
> +                android.preference.ListPreference newOrderPrefSecond = (android.preference.ListPreference) findPreference("order_2");
I don't find any non-deprecated equivalent.
Only if our app was targeted for API Level 11+ devices then we could have used it directly.

2021-07-02 14:53 UTC, david-allison-1 approved these changes
LGTM

2021-07-02 15:16 UTC, david-allison-1 commented
@Arnold2381 Want to mark this as "ready for review"?

2021-07-02 15:21 UTC, Arnold2381 commented
> @Arnold2381 Want to mark this as "ready for review"?

Yes this is ready for review.

2021-07-02 18:51 UTC, mikehardy commented
> ```
> git fetch origin   
> git rebase origin/master 
> ```
> 
> @david-allison-1 this is how is it done right?

Just commenting on this - I usually need to do "upstream" (because I have a fork, and "origin" refers to my fork, while I have added a a new git remote for "upstream": `git remote add upstream git@github.com:ankidroid/Anki-Android.git`)

2021-07-02 18:58 UTC, mikehardy approved these changes
LGTM too - thank you @Arnold2381 !

2021-07-02 18:59 UTC, merged

2021-08-05 15:42 UTC, mikehardy commented
Hi there!

If you're already submitted something to OpenCollective for PRs merged in July 2021, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for July 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month)

Thanks!