Card template editor save states
ankidroid/Anki-Android pull request #8786
Opened 2021-05-07 08:42 UTC by Akshay0701

## Pull Request template

## Purpose / Description
BottomNavigation view loses its states after the switch to preview screen.

## Fixes
Fixes #8780

## Approach
Maintained all pagers editorViewId and ediorViewPostion

2021-05-07 09:01 UTC, prateek-singh-3212 commented
Looks good to me!

2021-05-09 15:52 UTC, mikehardy requested changes
I would love to merge a fix for this issue but the logging statements need work, and I don't believe two separate state maps are necessary?

2021-05-09 15:52 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +import android.app.Activity;
This appears unused?

2021-05-09 15:52 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +import android.view.MotionEvent;
I believe this is unused?

2021-05-09 15:52 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            mEditorViewId.put(0, R.id.front_edit);
I don't understand why we need two hashmaps when all we need to know is the position? The set of all possible view ids is known and may be either repopulated fully on onCreate() or simply fetched dynamically when tabs switch?

Then all you need to persist onSaveInstanceState is the tab position

2021-05-09 15:52 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            }
I wish this were just safe by default - I don't like how the activity / fragment lifecycle handling has bled into createFragment. Perhaps something more like this though?

```java
int editorPosition = 0;
if (mEditorPosition.get(position) != null) {
  editorPosition = mEditorPosition.get(position);
}
```

2021-05-09 15:52 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +
I don't think this spacing change is necessary for the bugfix. It is not harmful but generally bug fixes should be the smallest possible change to reduce the diff to only the essentials

2021-05-09 15:52 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            args.putInt(EDITOR_VIEW_ID_KEY, viewId);
as mentioned above - aren't the view ids dependent on the editor position, and thus can be derived correctly at all times?

2021-05-09 15:52 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            Log.e("sample", mEditorPosition + "");
Log.e is reserved exclusively for issues that would maybe result in a crash report and definitely cannot be handled except by an application restart or user support, this seemingly does not quality

If you want debugging information, you should Log.d and prefix with the classname and method so it's easy to trace execution, e.g. `Log.d("CardTemplateFragment::onCreateView - mEditorPosition: %d", mEditorPosition);`

2021-05-09 15:52 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            bottomNavigation.setOnNavigationItemSelectedListener(item -> {
Doing the lambda-conversion as part of the functional change makes the bug fix part of the diff much harder to read, it is better to do it as a separate commit

2021-05-09 15:52 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            bottomNavigation.setOnNavigationItemSelectedListener(item -> {
I had to alter diff viewer settings to "ignore whitespace" and reload, but then the diff was less noisy for this change

2021-05-09 15:52 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                // Log.e("sample","current card :"+ position +" setted view : " + currentSelectedId);
I think `Log.d` statements are valuable and you would not even need to comment this out, but never Log.e unless it is really an error that you may not successfully recover from. Just use good message prefixes then in an `adb` session you can filter and trace quite easily

2021-05-09 15:52 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                    Log.e("sample", mTemplateEditor.mEditorPosition.toString());
Alter log statement as indicated in other comments

2021-05-09 16:20 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            args.putInt(EDITOR_VIEW_ID_KEY, viewId);
Okay let me explain,
We have to save states of 

1. selected bottom navigation button (front, back, style) 
2. position of currently selected editor edit text 

If I understood your point, you're saying there is no need to use editorViewId map. 

If I only save the editor position and not editorViewId then the program may not able to restore the previously selected bottom navigation button and it will only store the position of Edittext.

It would be great if could guide me on how I should process further.

2021-05-09 19:48 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            args.putInt(EDITOR_VIEW_ID_KEY, viewId);
Ah, perhaps a comment then explaining what each is as you declare the member variables...

something like 
`// the position of the cursor in the editor view` and 
`// the current editor view among front/style/back`

*assuming* I understand things correctly now, which I may not. If I am understanding correctly now then it does sound like they are necessary and I was just confused, which is something the comments I suggest above would avoid when I read again later and have forgotten this 😅

2021-05-10 04:25 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            Log.e("sample", mEditorPosition + "");
my fault! sorry, this log statement I used to check whether value restored or not, 

I am ready to remove this log statement if there no strong reason to keep it.

2021-05-10 04:37 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            Log.e("sample", mEditorPosition + "");
my fault, sorry, I used a log to check whether value restored or not  and I think in the previous commit I removed all logs

2021-05-19 16:29 UTC, mikehardy approved these changes
This looks good to me, just one unused import to get rid of
Thank you @Akshay0701 !

2021-05-19 16:29 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +import android.util.Log;
This is unused - we use Timber
```suggestion
```

2021-05-19 16:33 UTC, mikehardy commented
removed that import, waiting on CI now :rocket:

2021-05-19 16:37 UTC, Akshay0701 commented
Thanks!, I tried to test this as good as possible, hope this doesn't raise any new issues.

2021-05-19 21:45 UTC, merged