Enhanced card and tag buttons in Add Note
ankidroid/Anki-Android pull request #8790
Opened 2021-05-07 17:33 UTC by prateek-singh-3212

## Pull Request template

## Purpose / Description
Restyled the buttons to give it a feel of button.

Previous buttons:
![earliew](https://user-images.githubusercontent.com/76490368/117486957-00df9d80-af88-11eb-9418-390ca600eeec.png)

## Fixes
Fixes #8779

## Approach
I removed the previous implementation  and  added a AppCompatButton and layer-list in background.

## How Has This Been Tested?
Tested on Samsung Galaxy M51, android 11 (Samsung One UI 3.1)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-05-07 19:18 UTC, david-allison-1 requested changes
Light mode looks fantastic, thanks!

These don't look like buttons in night mode, could you perhaps try a different shadow color?

Could you change the font back to what it was (possibly just not using ALL CAPS for everything)

2021-05-08 07:01 UTC, prateek-singh-3212 commented
How it is looking now?
![Screenshot_20210508-122802_AnkiDroid](https://user-images.githubusercontent.com/76490368/117530153-3a042600-aff9-11eb-9026-044e2ac7e089.jpg)
![Screenshot_20210508-122725_AnkiDroid](https://user-images.githubusercontent.com/76490368/117530155-3b355300-aff9-11eb-86ba-22df09c7a1ce.jpg)

2021-05-17 01:36 UTC, david-allison-1 approved these changes
Much better, thanks!

2021-06-02 18:51 UTC, mikehardy approved these changes
Nice thank you!

2021-06-02 18:51 UTC, merged