Card Template Editor Appearance: Implemented "Insert Field" In Action Mode Callback
ankidroid/Anki-Android pull request #8797
Opened 2021-05-09 05:23 UTC by Akshay0701

## Fixes
Fixes #6964

## Checklist
- [x] Implemented insert field option in card editor template 
- [x] Implemented ActionModeCallback for inserting field in editText 

## Output
<img src="https://user-images.githubusercontent.com/52353967/117561450-9d9f5980-b0b4-11eb-9e8a-175aca71887a.gif" width="250" height="500" />

2021-06-01 01:33 UTC, david-allison-1 commented
Sorry I missed this! Was in the middle of another project when this came in. Will get to it later on today, feel free to rebase and we'll get it in.

2021-06-01 01:43 UTC, david-allison-1 reviewed
Preliminary review before I ran the code

2021-06-01 01:43 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +
no need

2021-06-01 01:43 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            builderSingle.setTitle("Select One Name:-");
Also needs to be in `xml`
```suggestion
            builderSingle.setTitle("Select field");
```

2021-06-01 01:43 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            AlertDialog.Builder builderSingle = new AlertDialog.Builder(getContext());
Typically we want a MaterialDialogBuilder

2021-06-01 01:43 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            builderSingle.setNegativeButton("cancel", (dialog, which) -> dialog.dismiss());
`xml`

2021-06-01 01:43 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                if (mCurrentEditorViewId == R.id.styling_edit) {
can we disable this on `styling` (possibly by returning false on the methods above) rather than special-casing here?

2021-06-01 01:43 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                }
These two branches appear to be the same

2021-06-01 01:43 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            fieldNames = requireActivity().getIntent().getStringArrayListExtra("fieldNames");
extract `requireActivity().getIntent().getStringArrayListExtra("fieldNames");` to a method

You likely want this in the constructor of the class, rather than with a dependency on the activity

2021-06-01 19:51 UTC, Akshay0701 commented
<img src="https://user-images.githubusercontent.com/52353967/120381970-b5c76900-c340-11eb-8288-99e9338c9ff2.jpg" width="250" height="500" />

what should i change to fix this ?

2021-06-01 19:51 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                }
your right

2021-06-01 19:52 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            AlertDialog.Builder builderSingle = new AlertDialog.Builder(getContext());
i used  MaterialAlertDialog

2021-06-02 02:20 UTC, david-allison-1 reviewed
> `image showing no fields`
> 
> what should i change to fix this ?

I'd recommend loading the fields in `onCollectionLoaded` of the screen, rather than from an intent.

The problem you don't pass in the field names when you open the screen from "Manage Note Types"

Also: https://github.com/ankidroid/Anki-Android/pull/8797#discussion_r642730337

2021-06-02 02:21 UTC, david-allison-1 reviewed
Android guidelines - we should follow them more

2021-06-02 02:21 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/01-core.xml
> +    <string name="card_template_editor_insert_field">Insert Field</string>
```suggestion
    <string name="card_template_editor_insert_field">Insert field</string>
```

2021-06-02 05:26 UTC, david-allison-1 reviewed
few more thoughts

2021-06-02 05:26 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +        private ArrayList<String> mFieldNames;
mark as nullable

2021-06-02 05:26 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/FieldState.java
> +    public static class FieldChangeType implements Serializable {
Is this necessary?

2021-06-02 05:26 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            MaterialAlertDialogBuilder builderSingle = new MaterialAlertDialogBuilder(context);
Can't you `requireContext()`?

2021-06-02 07:38 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/FieldState.java
> +    public static class FieldChangeType implements Serializable {
yes, to pass this from intent

2021-06-02 07:43 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/FieldState.java
> +    public static class FieldChangeType implements Serializable {
now i will load field from onCollectionLoaded

2021-06-27 14:08 UTC, mikehardy commented
Appears feedback was addressed in new commits post review, putting it back in review state removing feedback state

2021-06-27 14:10 UTC, david-allison-1 commented
Had a pending review that wasn't submitted (sorry), I'll go through this again now.

2021-06-27 14:16 UTC, Akshay0701 commented on AnkiDroid/src/main/res/values/styles.xml
> +    <style name="CardTemplateEditor_MaterialAlertDialogBuilder" parent="Theme.MaterialComponents.Light.DarkActionBar">
yes if i didn't use this theme for material dialog then application crash with message 

> You need to use a Theme.AppCompat theme (or descendant) with this activity

any suggestion what should I do ?

2021-06-27 14:19 UTC, Akshay0701 commented
> Had a pending review that wasn't submitted (sorry), I'll go through this again now.

no worry, please try to run this pr on the local device(in night mode).

2021-06-27 15:06 UTC, david-allison-1 commented
Sorry in advance, I don't like code dumping and it feels disrespectful.

```java
       private void showInsertFieldDialog() {
            if (mTemplateEditor.mFieldNames == null) {
                return;
            }
            List<String> items = mTemplateEditor.mFieldNames;
            RecyclerView.Adapter<?> adapter = new RecyclerView.Adapter<RecyclerView.ViewHolder>() {

                @NonNull
                @Override
                public RecyclerView.ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
                    View root = getLayoutInflater().inflate(R.layout.material_dialog_list_item, parent, false);
                    return new RecyclerView.ViewHolder(root) { };
                }


                @Override
                public void onBindViewHolder(@NonNull RecyclerView.ViewHolder holder, int position) {
                    TextView textView = (TextView) holder.itemView;
                    textView.setText(items.get(position));
                    textView.setOnClickListener((l) -> insertField(textView.getText().toString()));
                }


                @Override
                public int getItemCount() {
                    return items.size();
                }
            };

            new MaterialDialog.Builder(requireContext())
                .title(R.string.card_template_editor_select_field)
                .negativeText(R.string.dialog_cancel)
                .adapter(adapter, null)
                .show();
        }


        private void insertField(String fieldName) {
            int start = Math.max(mEditorEditText.getSelectionStart(), 0);
            int end = Math.max(mEditorEditText.getSelectionEnd(), 0);
            // add string to editText
            String updatedString = "{{" + fieldName + "}}";
            if (mCurrentEditorViewId == R.id.back_edit || mCurrentEditorViewId == R.id.front_edit) {
                mEditorEditText.getText().replace(Math.min(start, end), Math.max(start, end), updatedString, 0, updatedString.length());
            }
        }
```

We use a library for Material dialogs rather than the Android native one

This also allows you to revert some of the styling changes

I'm not /perfectly/ happy with the layout file that I used here (margins on the text field)

Continuations from here:

* Do we want to close the dialog after selecting a field
* Add screenshots

Then, let's get this into .16!

2021-06-27 15:15 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/styles.xml
> +    <style name="CardTemplateEditor_MaterialAlertDialogBuilder" parent="Theme.MaterialComponents.Light.DarkActionBar">
ANswered on main issue

2021-06-27 15:18 UTC, Akshay0701 commented
> Do we want to close the dialog after selecting a field

yes, after selecting field dialog should close and the selected field must be added in the editor, right?

> Revert some of the styling changes as they're no longer necessary

yes will do

2021-06-27 15:23 UTC, david-allison-1 reviewed
Implementer's choice on closing the dialog, seems sensible to me!

2021-06-27 19:26 UTC, Akshay0701 commented
and also I forgot to say, Thank you so much for all nit fixed and other changes from the above code, it's really helpful

2021-06-27 19:33 UTC, david-allison-1 reviewed
One fix, one question (let me know if you want to see if you can work on it, or whether we should accept it as-is, happy with both).

Thanks!

2021-06-27 19:33 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
optional: see if you can stop this from appearing on the "style" tab here

2021-06-27 19:33 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/card_template_editor_item.xml
> +            <com.ichi2.anki.FieldEditText
`FixedEditText` should be used here.

2021-06-27 19:35 UTC, Akshay0701 commented
Okay I will try to fix first 👍

2021-06-28 18:34 UTC, Akshay0701 commented on AnkiDroid/src/main/res/layout/card_template_editor_item.xml
> +            <com.ichi2.anki.FieldEditText
or may be `FixedTextView` ? because we just wanted to show text.

2021-06-28 21:29 UTC, david-allison-1 requested changes
Works well, just a bit more cleanup

2021-06-28 21:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            if (mCurrentEditorViewId == R.id.back_edit || mCurrentEditorViewId == R.id.front_edit) {
We don't need this any more

2021-06-28 21:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            } else if (itemId == R.id.action_insert_field) {
Hide the menu item as well, if styling is selected

2021-06-28 21:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +                    textView.setOnClickListener((l) -> insertField(textView.getText().toString()));
We also want to close the dialog if an item is clicked, get a reference to the dialog and close it

2021-06-29 05:16 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            } else if (itemId == R.id.action_insert_field) {
done!

2021-06-29 06:37 UTC, david-allison-1 reviewed
One nit.

One that requires testing.

I'm on my phone, and won't have the time for Ankidroid until Thursday, so sorry for the brevity. I'd really like to see a FragmentFactory (see our existing implementations in the code), as this is a common cause of bugs.

2021-06-29 06:37 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            if (mCurrentEditorViewId == R.id.styling_edit) {
Nit: define a Boolean, then "set visible" to remove the "if"

2021-06-29 06:37 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/InsertFieldDialog.java
> +    public void setOnSelectedField(Consumer<String> c) {
Could you test to see what happens if the dialog is dismissed (for example if the app is minimised).

I think we want a `FragmentFactory` here.

2021-06-29 06:42 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/InsertFieldDialog.java
> +    public void setOnSelectedField(Consumer<String> c) {
yes i just tested and working perfectly,

if `FragmentFactory` is required then will implement it.

2021-06-29 07:56 UTC, Akshay0701 commented
> won't have the time for Ankidroid until Thursday, so sorry for the brevity.

dont worry to much david, its fine.

I added initialization code to insertDialogFactory class.

2021-06-29 08:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            InsertFieldDialogFactory insertFieldDialogFactory = new InsertFieldDialogFactory().attachToActivity(mTemplateEditor);
I /think/ this should be done `onCreate` (both with a lambda, rather than with a concrete reference to the class) so the fragment can be restored, but I'm not certain on this one.

2021-06-29 09:15 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            InsertFieldDialogFactory insertFieldDialogFactory = new InsertFieldDialogFactory().attachToActivity(mTemplateEditor);
so do we want to store/restore `insertFieldDialogFactory` from savedInstanceState?

2021-06-29 09:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            InsertFieldDialogFactory insertFieldDialogFactory = new InsertFieldDialogFactory().attachToActivity(mTemplateEditor);
No, I don't think that's feasible. 

But: If the DialogFragment is recreated by Android, then we want to ensure that the lambda is set appropriately.

2021-07-01 12:10 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            InsertFieldDialogFactory insertFieldDialogFactory = new InsertFieldDialogFactory().attachToActivity(mTemplateEditor);
maybe I didn't understand properly, you see changes that I made, and let me know if that is right or wrong...

2021-07-01 12:25 UTC, david-allison-1 requested changes
Almost!

2021-07-01 12:25 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            mInsertFieldDialogFactory = savedInstanceState.getParcelable(INSERT_FIELD_FACTORY);
Don't use state here
```suggestion
```

2021-07-01 12:25 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            mInsertFieldDialogFactory = new InsertFieldDialogFactory().attachToActivity(this);
Bring this above, outside the `if`

2021-07-01 12:25 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +        outState.putSerializable(INSERT_FIELD_FACTORY, mInsertFieldDialogFactory);
```suggestion
```

2021-07-01 12:25 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialogFactory.java
> +
See `CustomStudyDialogFactory`.

accept `this::insertField` as a parameter, pass it to the constructor, and remove `setOnSelectedField`

2021-07-01 13:35 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialogFactory.java
> +
thanks done.

2021-07-01 13:45 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            mInsertFieldDialogFactory = new InsertFieldDialogFactory(this::insertField).attachToActivity(mTemplateEditor);
I don't believe this is correct (`onCreateView` rather than `onCreate`). On me to do some thinking and resolve  this. Sorry for the delay

2021-07-01 13:49 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            mInsertFieldDialogFactory = new InsertFieldDialogFactory(this::insertField).attachToActivity(mTemplateEditor);
insertField are present inside fragment, i.e i wrote it in onCreateView

if I wrote this in onCreate like this 
 ```java
mInsertFieldDialogFactory = new InsertFieldDialogFactory(getCurrentFragment()::insertField).attachToActivity(mTemplateEditor);
```
then it gives me nullpointer error on getFragment ... that is the reason I wrote this in onCreateView

2021-07-01 17:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            mInsertFieldDialogFactory = new InsertFieldDialogFactory(this::insertField).attachToActivity(mTemplateEditor);
See if you can defer the call: `() -> getCurrentFragment().insertField()`

2021-07-01 17:43 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +            mInsertFieldDialogFactory = new InsertFieldDialogFactory(this::insertField).attachToActivity(mTemplateEditor);
tussi great ho mahoday (in english "you are great sir")

2021-07-01 17:48 UTC, david-allison-1 approved these changes
Awesome!

2021-07-01 20:39 UTC, mikehardy approved these changes
Read through it all, I feel like I understand it, LGTM - can't see anything I'd change
I

2021-07-01 20:39 UTC, merged