Test for card browser changing color when card flag changes
ankidroid/Anki-Android pull request #8800
Opened 2021-05-10 18:26 UTC by dorrin-sot

## Purpose / Description
> This is follow on work for issue #8485
> 
> It was fixed in #8735 but without a test confirming the fix and making sure it doesn't happen again
> 
> This issue tracks creation of a test that verifies the issue before the fix from #8735 and makes sure it is actually fixed

## Fixes
Fixes #8744

## Approach
After testing different approaches to reproduce the bug, I found that using a deck of about 75 cards minimum would cause the error.
After that I added the method `flagsAreShownInBigDecksTest` in `CardBrowserTest` class in which I selected and flagged a random card, unflagged the card, and in the end selected and flagged all the cards, testing each time that the flags are correct.

## How Has This Been Tested?
Checked out commit 3e798367 and verified that the test failed, then went back to normal branch, verifying the test pass.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-06-02 05:36 UTC, david-allison-1 requested changes
minor change, looks great!

2021-06-02 05:36 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +        cardBrowser.checkCardsAtPositions((int) (random() * 74));
Either: 

* use a `Random` with a fixed seed
* Check 'em all
* record the seed

2021-06-02 05:36 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +        shadowOf(getMainLooper()).idle();
Use: `RobolectricTest.advanceRobolectricLooper()`

2021-06-02 05:38 UTC, david-allison-1 requested changes
Thanks so much for the PR - a few more changes

2021-06-02 05:38 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +        cardBrowser.checkCardsAtPositions((int) (random() * 74));
Actually... note 3: class `Random` should have a `nextInt` which reads better than a multiplication

2021-06-02 05:38 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +        CardBrowser cardBrowser = getBrowserWithNotes(75);
extract the int, and use `numberOfNotes - 1` in the code below

2021-06-02 06:59 UTC, dorrin-sot commented on AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
> +        cardBrowser.checkCardsAtPositions((int) (random() * 74));
I set the seed to 1 and used `assumeThat` to make sure that position gets checked

2021-06-02 07:01 UTC, david-allison-1 commented
Needs rebasing to remove irrelevant changes

2021-06-02 07:56 UTC, dorrin-sot commented
> Needs rebasing to remove irrelevant changes

Done

2021-06-02 08:06 UTC, dorrin-sot commented
Accidentally removed requested changes while rebasing now actually done

2021-06-02 10:12 UTC, david-allison-1 approved these changes
More testing! Lovely jubbly. Thanks!!!

2021-06-02 18:20 UTC, mikehardy approved these changes
Thank you!

2021-06-02 18:20 UTC, merged

2021-07-31 20:36 UTC, mikehardy commented
Hi there!

Apologies for the delay, and if you're already submitted something to OpenCollective for PRs merged in June 2021 PRs merged, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for June 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in May)

Thanks!