NF: Paste clipboard image as PNG
ankidroid/Anki-Android pull request #8804
Opened 2021-05-11 09:36 UTC by kartikeysaran

## Fixes
Fixes #8709 

## How Has This Been Tested?
This has been tested on a real device

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2021-05-11 12:26 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        }
Can you please tell me which line and exact changes as i have followed the code style ? Thanks !

2021-05-11 12:49 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        }
```suggestion
        if (getCol().getConf().optBoolean("pastePNG")) {
            clipCopy = File.createTempFile(fileNameAndExtension.getKey(), ".png");
        } else {
            clipCopy = File.createTempFile(fileNameAndExtension.getKey(), ".jpg");
        }
```

2021-05-12 07:40 UTC, Akshay0701 requested changes
Great! @kartikeysaran.

2021-05-12 07:40 UTC, Akshay0701 commented on AnkiDroid/src/main/res/xml/preferences_general.xml
> +</PreferenceScreen>
can you revert this change?

2021-06-27 14:07 UTC, mikehardy commented
superceded by #9080

2021-06-27 14:07 UTC, closed without merging