JSONObject names, some correction
ankidroid/Anki-Android pull request #8824
Opened 2021-05-14 04:39 UTC by Arthur-Milchior

Multiple functions did not check that `names()` could return null. So I add it. The behavior is the same than on empty jsonArray.

The second report of #8821 should never have occurred, as it's impossible to get no deck at all, but somehow it occured. I've no idea what was going on here. The best I can imagine is someone having fun with the database directly, and checking what would occur if the default deck is removed manually. It's something I could have imagined doing myself just to check.

At least, I hope it's the correct explanation, because the other one would be that someone was able to remove the default deck, which is theoretically impossible, and in this case it's a slightly bigger problem on our side. Sadly, until we find out how to reproduce it, there is nothing I can do.

2021-05-14 04:48 UTC, mikehardy commented
I think David added a way to store entire (corrupted) databases as assets in resources and load them, could do something like that for a test. How did it happen :thinking: maybe there was some sort of corruption during sync or import or similar?

2021-05-14 04:49 UTC, mikehardy approved these changes
I think was the 3rd commit from the other crash fix PR - still looks good but also I'm still exhausted so asking for a 2nd pair of :eyes:

2021-05-14 08:46 UTC, david-allison-1 requested changes
Again, we need to log this heavily if it's an assertion failure

From memory: Check the method at the bottom of CollectionHelper for mocking the collection

The issue that this fixes is listed incorrectly

If two PRs come in which are listed as fixing the same issue, it's an amber flag to me that the PRs may be split too much, or the issue is too general

2021-05-14 12:57 UTC, mikehardy commented
The issue was too general  - I was moving fast before sleep and posted a second stack on the same issue, I don't really think they were related other than I thought Arthur would already be watching that issue. A crappy optimization really, sorry :-)

2021-05-14 16:27 UTC, Arthur-Milchior commented
They are absolutely not related, and indeed I don't think mike should have posted both stacks on the same issues. I went with the current issue number only because it's faster than creating a separate issue. But since it's also fast to create a separate issue, here it's done. So we have two distinct PR fixing two distinct entirely unrelated issues.

2021-05-14 16:30 UTC, Arthur-Milchior commented
If I understand correctly David, you mean that testing what occurs when the collection have no deck at all is of low value.
If that's right, then I do agree. This is something that breaks anki so fundamentally that there is no reason for us to really consider this case. There is no right way to recover. If they are cards, then putting everything in a new default is a bad experience (and not conform to upstream), and if there are no card, then just restarting from scratch is better

2021-05-14 22:44 UTC, mikehardy commented
This is my last opportunity for a while to merge things and I'm doing a crashfix build right now, if we want a test we can pursue as a follow-on

2021-05-14 22:45 UTC, merged

2021-05-15 00:57 UTC, david-allison-1 commented
Can we add a follow-up to log this exception to ACRA rather than ignore it?

2021-05-15 01:07 UTC, Arthur-Milchior commented
I don't know how ACRA work. Should I just send an exception the same way I did for scrolling to 0 cards, or should I do more things?

2021-05-15 01:34 UTC, david-allison-1 commented
If you're referring to: https://github.com/ankidroid/Anki-Android/pull/8823/files#diff-f5fe2d7c59f0efdb3d639d6032040921173f1f57e7b3ae9be278d3d277218280R2182

Then that's all you need. ACRA handles understanding the user's preferences, and will show a dialog/silently report the exception based on these. 

It's typically best to understand ACRA as a black box: "pass in a string/exception, and it'll handle user preferences, and if the user consents, will optionally show a dialog, and send a crash report containing appropriate information".

Given enough time, people will see the "exception report" dialog (if preferences are set to 'ask') and will ask questions on the mailing list/reddit, from there we ca n collaborate and understand the underlying issue