Fixed crash on file selection
ankidroid/Anki-Android pull request #8887
Opened 2021-05-20 13:04 UTC by prateek-singh-3212

## Pull Request template

## Purpose / Description
App crashes when audio file is selected whose file name is invalid

## Fixes
Fixes #8881 

## Approach
I have created a method that checks the filename is valid or not

## How Has This Been Tested?

Not tested on a physical device but tested by providing invalid inputs in the filename string.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-05-21 02:25 UTC, mikehardy requested changes
Hmm - I would like to take a different approach, because I don't think this is easy at all for the user, and we are already mutating the filename so it is already not "sacred" - we can mutate it more. But for the user to have to go back and use a file management app to change the name then come back and...so painful.

I found this as a strategy to provably make a filename safe:

String name = s.replaceAll("\\W+", "");

https://stackoverflow.com/a/1184185/9910298

So I think instead of trying to filter it for safety (and probably missing some unsafe things) just *force* it and move on.

Could you try that strategy?

2021-05-21 15:34 UTC, prateek-singh-3212 commented
> Could you try that strategy?

Sure

2021-05-21 16:48 UTC, mikehardy approved these changes
Fantastic!

2021-05-21 17:03 UTC, prateek-singh-3212 commented
> Fantastic!

Thanks 😀.

I just want to know that where does log shows when the app crashes in the emulator test.

> Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Execution failed for task ':AnkiDroid:connectedPlayDebugAndroidTest'.
Use '--warning-mode all' to show the individual deprecation warnings.
> There were failing tests. See the report at: file:///Users/runner/work/Anki-Android/Anki-Android/AnkiDroid/build/reports/androidTests/connected/flavors/play/index.html

2021-05-21 17:14 UTC, mikehardy commented
Yeah, that's frustrating. We're not sure where that crash is but I looked at it just last night.

The first level of logging is in the action itself, of course. And it says "look at the emulator logs"

So we're capturing those:

https://github.com/ankidroid/Anki-Android/blob/3b163ac44bbb9e66fb4b001d75e59dd5deb9435a/.github/workflows/tests_emulator.yml#L139

...and saving them as github artifacts:

https://github.com/ankidroid/Anki-Android/blob/3b163ac44bbb9e66fb4b001d75e59dd5deb9435a/.github/workflows/tests_emulator.yml#L148-L153

And they are available then as "artifacts" on the check - like this one look for `adb_logs` at bottom:
https://github.com/ankidroid/Anki-Android/actions/runs/862574060

When you download that and double unzip it you get the raw logcat.

And here's the frustrating part: you see that there is a Rust call to open a collection and update it and then ... nothing AnkiDroid related...and then the Android OS kills the process with signal 9 (force kill unix signal).

No other information.

So that crash is going to need a lot more instrumentation added to it or a local reproduction (which we haven't seen yet) to find out where it's crashing, as there's no native stacks thrown in the log or anything :shrug:

2021-05-21 17:15 UTC, mikehardy commented
Logged all that as #8901

2021-05-21 18:00 UTC, merged

2021-06-23 17:28 UTC, mikehardy commented
Hi there!

Apologies for the delay, and if you're already submitted something to OpenCollective for May 2021 PRs merged, you may feel free to ignore this.

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for May 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in May)

Thanks!