modified the stop function in AudioPlayer
ankidroid/Anki-Android pull request #8918
Opened 2021-05-23 12:11 UTC by SilentCruzer

## Purpose / Description
There was a bug when trying to check the pronunciation where if we use the keyboard shortcuts multiple times, the app crashes.

## Fixes
Fixes [#8637](https://github.com/ankidroid/Anki-Android/issues/8637)

## Approach
The app crashed because we were trying to record new audio while the previously recorded audio was playing. So I modified the stop() function in the theAudioPlayer.java file to check the latest data source and also it resets the player after new audio is recorded.

Also added a onPrepared listener because the error - trying to use prepare() on a null object, kept crashing the app. 

## How Has This Been Tested?

Constantly press record Audio shortcut (shift + v) and play (v).
Tested this on a one plus 7t(physical device) and pixel 3A (emulator)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2021-05-23 17:31 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioPlayer.java
> -
Please can you revert back unnecessary changes

2021-05-23 17:31 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioPlayer.java
> +
Same here

2021-05-23 17:31 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioPlayer.java
> +
Same here

2021-05-23 17:32 UTC, kartikeysaran commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioPlayer.java
> +
Same here

2021-05-23 17:33 UTC, kartikeysaran requested changes
Just a few small changes

2021-05-23 17:34 UTC, kartikeysaran commented
Can you please add a test or share a video of this ?

2021-05-23 19:44 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioPlayer.java
> +        mPlayer.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
Set the listener before calling prepare - if `.prepare()` finishes before this call, then nothing happens

2021-05-23 22:04 UTC, SilentCruzer commented
https://user-images.githubusercontent.com/73246484/119278021-6c8c6080-bc40-11eb-9e7b-32f9c816e6c2.mp4


This is a recording of when I tested the app on the physical device.

And, I have made the mentioned changes in the latest commit.

2021-05-23 22:09 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioPlayer.java
> +            mPlayer.pause();
This doesn't seem correct - now we've moved `.start()` to `setOnPreparedListener`, we can potentially call `pause` before `.start()` is called

2021-05-24 06:34 UTC, SilentCruzer commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioPlayer.java
> +            mPlayer.pause();
I have added the pause() there because I needed to reset the player before a new recording starts. Looked through few forums and found that the media player in android already has a few sync issues, that's why the bug was happening. I found replacing the stop() function with the combination of pause() and seekto() functions to be effective.

2021-06-27 13:53 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioPlayer.java
> +        mPlayer.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
I believe this change has been made. The listener is set before prepare is called now

2021-06-27 13:55 UTC, mikehardy approved these changes
LGTM - @david-allison-1 you had comments before, if this is good for you we can merge

2021-06-27 13:56 UTC, mikehardy requested changes
Oh, actually I spoke too soon, it has a compile error:

```

> Task :AnkiDroid:compilePlayDebugUnitTestKotlin
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/reviewer/KeyboardShortcutIntegrationTest.java:137: error: method stop in class AudioPlayer cannot be applied to given types;

        verify(player, times(1)).stop();
                                ^
  required: String
  found: no arguments
  reason: actual and formal argument lists differ in length
> Task :AnkiDroid:compilePlayDebugUnitTestJavaWithJavac
```

2021-07-03 09:57 UTC, SilentCruzer commented
> Oh, actually I spoke too soon, it has a compile error:
> 
> ```
> 
> > Task :AnkiDroid:compilePlayDebugUnitTestKotlin
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/reviewer/KeyboardShortcutIntegrationTest.java:137: error: method stop in class AudioPlayer cannot be applied to given types;
> 
>         verify(player, times(1)).stop();
>                                 ^
>   required: String
>   found: no arguments
>   reason: actual and formal argument lists differ in length
> > Task :AnkiDroid:compilePlayDebugUnitTestJavaWithJavac
> ```

I have added the new arguments in the test since I had modified the stop function. Can you please try running the workflow again?

2021-07-03 16:49 UTC, mikehardy commented
Sure thing thanks @SilentCruzer - switched up the tags and pinged David to see if he had comments

2021-07-04 19:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioPlayer.java
> +            mPlayer.pause();
I don't think this is correct. 

`prepare()` calls `onPrepared` which calls `start()`, and the `pause` here seems to be working around this issue, and will fail if there's a race condition.

2021-08-22 22:37 UTC, mikehardy commented
These seems silly, but a close / re-open re-runs the workflows easily so I'm doing that. Both failures in CI appeared unrelated.

2021-12-14 14:37 UTC, closed without merging