Fix timing for Automatic Display Answer
ankidroid/Anki-Android pull request #8923
Opened 2021-05-25 06:34 UTC by AlexApps99

## Purpose / Description
Prevents Automatic Display Answer from occurring when the delay is set to 0, but there is audio present.

## Fixes
No issue existed before, I just came across it and since it irritated me I fixed it.
The default behavior for having the delay set to 0 is to wait indefinitely, so this just makes that more consistent.

## How Has This Been Tested?

I haven't compiled or tested it, because I don't have the SDK installed (sorry about that)
It seems like a pretty simple change though, if it compiles it should work as expected.

Please comment if you have tested it, thanks :)

BTW I'm loving AnkiDroid, it's great :+1:

2021-05-25 13:34 UTC, mikehardy commented
This does look like a simple fix! Thanks for taking the time to PR it - I've approved the CI runs so we should see about compile + test shortly and I tagged it up for review

2021-05-25 18:26 UTC, mikehardy requested changes
I think your fix is good but after examining, it could be even simpler. Since you just looked in here and thought about it - what do you think?

2021-05-25 18:26 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            if (mWaitAnswerSecond > 0 && delay > 0) {
Okay - this is interesting - so I checked and `mUseTimerDynamicMS` is "the duration of any sound", while `mWaitAnswerSecond` is definitely supposed to be how long to wait for auto-advance, with `0` confirmed (via examination of previous logic) to mean "no auto-advance".

So you are correctly that before this change if there is audio, we will auto-advance even if auto-advance is otherwise set to zero

After this change, the error is fixed, however I think the *most* correct fix is not to check delay at all, it is even simpler - I think if we just check whether we should auto-advance or not, that' sufficient, but then if we determine we should, obviously we want to postDelayed for the full delay

So I think this is most correct. What do you think?

```suggestion
            if (mWaitAnswerSecond > 0) {  // a wait of zero means auto-advance is disabled
```

2021-05-25 18:26 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            if (mWaitQuestionSecond > 0 && delay > 0) {
As described above - I think this is simplest + correct

```suggestion
            if (mWaitQuestionSecond > 0) {
```

2021-05-25 19:51 UTC, AlexApps99 commented
That's a good point, the audio time will never be negative so I will take that into account.

2021-05-25 19:54 UTC, mikehardy approved these changes
This LGTM - thanks!

2021-05-26 14:54 UTC, mikehardy commented
@david-allison-1 if you could check this quickly, it's a regression from 2.14 I believe, or at least an irritating mis-behavior and I think the patch snipes it - I could put it in 2.15.2

2021-05-26 15:12 UTC, david-allison-1 approved these changes
LGTM

2021-05-26 15:14 UTC, merged

2021-05-26 15:15 UTC, mikehardy commented
Oops, should have squashed :facepalm:

2021-06-23 17:28 UTC, mikehardy commented
Hi there!

Apologies for the delay, and if you're already submitted something to OpenCollective for May 2021 PRs merged, you may feel free to ignore this.

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for May 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in May)

Thanks!