Initial Kotlin migration - DeckPicker and some other files
ankidroid/Anki-Android pull request #8962
Opened 2021-05-26 14:01 UTC by ShridharGoel

2021-05-26 14:24 UTC, mikehardy requested changes
Hey @ShridharGoel this seems like a reasonable start and of course the Deck Picker would be the start of the onboarding journey. If there are no other PRs outstanding for DeckPicker that we need to get in quickly, this could go.

I left a few comments that I'm curious about

If this goes in I want to see the other 2 modules (API and lint) get the same treatment if possible so they have kotlin infrastructure set up in their gradle files all at once while we are thinking about it.

I would also like to settle on a single enforced coding standard for Kotlin if possible - typically just adopting whatever the most common one is works best (for example just https://developer.android.com/kotlin/style-guide) because then there is tooling for it that is easy to use (for example https://github.com/pinterest/ktlint) - adopting a new language in a collaborative project means these things (standards, automated checks in CI, coverage reporting etc) is maybe more important than the underlying code change!

2021-05-26 14:24 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +import org.jetbrains.annotations.NotNull;
nitpick: we do not use the jetbrains annotations, this should be the android annotation that does the same

2021-05-26 14:24 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +package com.ichi2.anki;
Missing copyright header

2021-05-26 14:24 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
> +    public void buildDeckList(List<AbstractDeckTreeNode<T>> nodes, Collection col, @Nullable CharSequence filter) {
All of the changes in this file seem unrelated to kotlin migration.
Are they necessary for Kotlin migration? If not, all changes here should be removed from the PR

2021-05-26 14:24 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
> +    public void refreshInterface(boolean resetSched) {
This does not seem related to kotlin migration. If it is not related it should not be in this PR

2021-05-26 14:24 UTC, mikehardy commented on AnkiDroid/build.gradle
> +        main.java.srcDirs += 'src/main/kotlin'
I'll be curious to see how this changes coverage metrics
When you run `./gradlew jacocoTestReport` from main branch vs from this branch, do you see coverage being correctly detected and reported on the kotlin files? Is codecov.io picking them up as well?

2021-05-26 14:24 UTC, mikehardy commented on AnkiDroid/build.gradle
> +apply plugin: 'kotlin-android'
Do we need to tweak any of the compile options for kotlin as we do for java?

https://kotlinlang.org/docs/gradle.html#compiler-options - `allWarningsAsErrors` is something we enable for instance, I believe it will need enable for kotlin

https://github.com/ankidroid/Anki-Android/blob/2bcfd2f199b1c52890fd9eb06f091f82ba42d0b7/AnkiDroid/build.gradle#L216-L224

2021-05-26 14:24 UTC, mikehardy commented on build.gradle
> +        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.10"
I tried to find documentation on this and could not. I found documentation for the `apply kotlin` change just not this one?

2021-05-26 14:36 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
> +    public void buildDeckList(List<AbstractDeckTreeNode<T>> nodes, Collection col, @Nullable CharSequence filter) {
Okay - definitely want @Arthur-Milchior to examine it then since this was all his work :-)

2021-05-26 14:37 UTC, ShridharGoel commented on AnkiDroid/build.gradle
> +        main.java.srcDirs += 'src/main/kotlin'
Actually, this can be removed currently since I haven't added the `kotlin` directory yet. I was trying

2021-05-26 14:38 UTC, ShridharGoel commented on AnkiDroid/build.gradle
> +        main.java.srcDirs += 'src/main/kotlin'
Actually, this can be removed currently since I haven't added the `kotlin` directory yet. It will actually be required if we have separate directories for Java and Kotlin files.

2021-05-26 14:56 UTC, ShridharGoel commented on build.gradle
> +        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.10"
This is the Kotlin Gradle Plugin.

https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-gradle-plugin
https://kotlinlang.org/docs/gradle.html

2021-05-26 14:58 UTC, mikehardy commented on AnkiDroid/build.gradle
> +        main.java.srcDirs += 'src/main/kotlin'
Hmm - that's a taste question. Personally, I really do *not* want separate directories, I'm always navigating around the directories and having a whole second top-level tree open to jump between files sounds awful. So removing this and keeping Kotlin next to Java sounds good to me

2021-05-26 14:59 UTC, mikehardy commented on build.gradle
> +        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.10"
Oh of course - sorry. And I have directly manipulated that line (to bump versions) in so many other repos. Should have remembered ;-)

2021-05-26 15:06 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +import org.jetbrains.annotations.NotNull;
Do the lint checks still work for Kotlin?

2021-05-26 15:11 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +import org.jetbrains.annotations.NotNull;
It was my understanding that they did, should it catch this? I did not see any checks run, possibly because there are conflicts?

2021-05-26 15:14 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +import org.jetbrains.annotations.NotNull;
Yes, we have a lint rule for this: https://github.com/ankidroid/Anki-Android/blob/dcbed8f5cf9ac21278c06b84b9b38cdb0350a96c/lint-rules/src/main/java/com/ichi2/anki/lint/rules/InconsistentAnnotationUsage.java

2021-05-26 15:15 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +import org.jetbrains.annotations.NotNull;
Let's wait to see what happens when checks are run

2021-05-26 16:18 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +import org.jetbrains.annotations.NotNull;
What can be done about that conflict? It is showing because that file has been removed.

2021-05-26 16:24 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +import org.jetbrains.annotations.NotNull;
> Do the lint checks still work for Kotlin?

This one is still a Java file.

2021-05-26 16:35 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +import org.jetbrains.annotations.NotNull;
and now that there is no conflict the checks run and it does fail lint (which is a good thing - the test should work). So this needs to be changed to the annotation we use, which is in the android package, not jetbrains package

2021-05-26 16:45 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +import org.jetbrains.annotations.NotNull;
Yes, I have updated it.

2021-05-30 14:14 UTC, ShridharGoel commented on AnkiDroid/build.gradle
> +apply plugin: 'kotlin-android'
`android.lintOptions.warningsAsErrors true`
This is already present in `lint.gradle`. It will work for Kotlin also. Is it required separately as well?

2021-05-30 14:50 UTC, mikehardy commented on AnkiDroid/build.gradle
> +apply plugin: 'kotlin-android'
If we know the same lintOptions are used for kotlin, then no - we do not need duplication, we just want to maintain our existing level of strictness. Thanks Shridhar

2021-05-30 15:31 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
> +package com.ichi2.anki;
Added.

2021-06-03 15:21 UTC, david-allison-1 commented
Can you split out the change which removes `sync_downloading_media` into a separate PR?

You only need to remove the English string. Our CrowdIn process will delete it from the other files

https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#handling-translations

2021-06-03 15:24 UTC, ShridharGoel commented
> Can you split out the change which removes `sync_downloading_media` into a separate PR?
> 
> You only need to remove the English string. Our CrowdIn process will delete it from the other files
> 
> https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#handling-translations

Okay, so can we ignore lint check failure in that case?

2021-06-03 15:24 UTC, david-allison-1 requested changes
This change needs to have a clean commit history with well-commented commits. Especially if multiple files are converted in a single commit.

I can't review this well while there are multiple conflict fixes and merge commits in the history

2021-06-03 16:05 UTC, ShridharGoel commented
> Can you split out the change which removes `sync_downloading_media` into a separate PR?
> 
> You only need to remove the English string. Our CrowdIn process will delete it from the other files
> 
> https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#handling-translations

#9060

2021-06-03 16:25 UTC, ShridharGoel commented on AnkiDroid/build.gradle
> +        disabledRules = ["no-wildcard-imports"]
Done.

2021-06-03 16:26 UTC, ShridharGoel commented on AnkiDroid/build.gradle
> +    id 'com.github.triplet.play' version '3.4.0-agp4.2'
Reverted.

2021-06-03 16:56 UTC, ShridharGoel commented
@david-allison-1 All changes have been done.

2021-06-14 16:56 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
> +        private boolean containsFilterString(String filterPattern, AbstractDeckTreeNode<T> root) {
@david-allison-1 Please have a look at this change.

2021-06-14 16:56 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
> +        for (AbstractDeckTreeNode<T> node : nodes) {
@david-allison-1 Please have a look at the changes in these two lines.

2021-06-14 16:57 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
> +    public void buildDeckList(List<AbstractDeckTreeNode<T>> nodes, Collection col, @Nullable CharSequence filter) {
@Arthur-Milchior Please have a look at the changes related to using `AbstractDeckTreeNode<T>` instead of `T`.

2021-06-18 03:13 UTC, Arthur-Milchior reviewed
How do you proof read such changes? Github don't seem to realize that the java and kotlin files are the same, so there is no easy way to get a meaningful diff. 
An obvious solution would be to rename the file in a different commit, but that would mean that the intermediate commit would not compile, which is not acceptable.

As David told earlier, it will be really important to split into smaller commits. And to avoid a commit just called "merge". So that reviewing can be done. It's impossible for me to do it here without spending an absurd amount of time on it

2021-06-18 03:13 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
> +        for (AbstractDeckTreeNode<T> node : nodes) {
Would `List<? extends T>` work? 
Because the way it is indicated, it seems to states it's a list of actual abstract deck tree nodes, which is of course impossible since it's an abstract class.

I'm not exactly surprised this led to a typing issue. This is a case where I felt limited by the typer and not by the actual algorithm itself.
Your code seems totally right. After all, `T` extends `AbstractDeckTreeNode<T>` so there is nothing absurd here. It's really a typing problem and not a code problem.

Maybe I should have created this by delegating more instead of inheriting. That was my mistake I fear. I may be able to improve it more today. Or not, not sure

2021-09-09 00:51 UTC, closed without merging