Migrate UiUtil to Kotlin
ankidroid/Anki-Android pull request #8968
Opened 2021-05-26 19:27 UTC by ShridharGoel

Added Kotlin related plugins and dependencies and migrated UiUtil to Kotlin.

2021-05-26 19:36 UTC, mikehardy commented
One at a time please - this duplicates a lot of the effort (and thus the concerns, and work) from the other Kotlin one

2021-05-26 19:39 UTC, ShridharGoel commented
@mikehardy Actually @david-allison-1 wanted to have the Kotlin migration done on a Utils file first, hence I have opened this PR.

2021-05-26 19:39 UTC, ShridharGoel commented
This one will be much easier to review and add the configuration required for Kotlin.

2021-05-26 19:41 UTC, mikehardy commented
I do agree with that :-), then can mark the other one as "draft" so I don't include it mentally when I'm running through the PR queue? Otherwise I know I'll keep looking at it.

So we should all focus on this one to get the tooling in, then we can move forward?

2021-05-26 19:42 UTC, ShridharGoel commented
Yes, marked that one as draft.

2021-05-26 19:43 UTC, ShridharGoel commented
Yes, marked the other one as draft.

2021-05-26 19:45 UTC, mikehardy requested changes
Looks good to me as a start, but with strong feelings about an auto-formatter (so that I can never worry about spacing issues again, huge win)

2021-05-26 19:45 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/utils/UiUtil.kt
> +}
Seeing "end of file has no newline" changes like this makes me think we *must* add a ktlint phase to our lint rules here. I personally don't care if there is a newline at end of file or not but I certainly do not want diffs cluttered up with meaningless changes like that - it makes it hard for us to review, right? So having a firm standard and enforcing it is key.

Can you integrate ktlint, make sure it has a valid gradle target, and add that target to our lint workflow after the existing two?

https://github.com/ankidroid/Anki-Android/blob/f4dd4958d905591746f7aadd2e4511433c77ab7e/.github/workflows/lint.yml#L72-L76

2021-05-27 14:26 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/utils/UiUtil.kt
> +}
Nice! Did ktlint flag this (and, hopefully, if run in some other mode auto-correct it?)
That makes me think in the developer guide for coding standards we need a new block for Kotlin - but this one will be easier than the Java one! Instead of talking about it all you can just say `"We use the <link>ktlint</link> auto-formatter to enforce the <link>Android Kotlin Standards</link>, to format the code run ./gradlew <what is the command?>`

2021-05-28 08:50 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/UiUtil.kt
> +}
> Did ktlint flag this (and, hopefully, if run in some other mode auto-correct it?)

Yes, it was flagged. Formatter was also working.


> That makes me think in the developer guide for coding standards we need a new block for Kotlin - but this one will be easier than the Java one! Instead of talking about it all you can just say `"We use the <link>ktlint</link> auto-formatter to enforce the <link>Android Kotlin Standards</link>, to format the code run ./gradlew <what is the command?>`

Yes, I had also thought that we should add the command to format the code using Ktlint in the documentation.
The command is `./gradlew ktlintFormat`.

2021-05-28 08:56 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/UiUtil.kt
> +}
Added the details in the `Development Guide`.

2021-05-28 16:55 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/utils/UiUtil.kt
> +}
that's fantastic - I looked, thanks!

2021-05-28 16:58 UTC, mikehardy approved these changes
The actual java->kotlin here is tiny, I have no problem with it
The infrastructure (formatting, format checks, documentation) was all worked through also and looks good to me

I definitely want to hear from @david-allison-1 and @Arthur-Milchior on this one just to make sure since we are going from "zero to one" here on kotlin

2021-05-28 16:58 UTC, david-allison-1 reviewed
Looks good.

What does this do the the APK size?

2021-05-28 17:03 UTC, mikehardy commented
I will be surprised if it affects things - if you do `./gradlew :AnkiDroid:dependencies | grep kotlin` on release-2.15 this is already a dependency all over the place since we have libraries that are in kotlin already

That said, changing the build.gradle debug block to also turn on minify for debug, then compiling the APK for release-2.15 and master will allow comparison

2021-05-28 18:12 UTC, Arthur-Milchior approved these changes

2021-05-28 18:12 UTC, merged