Invalid model crash branch
ankidroid/Anki-Android pull request #8996
Opened 2021-05-28 11:03 UTC by dorrin-sot

## Purpose / Description
App would crash if the database/model was corrupt

## Fixes
Fixes #8940

## Approach
Using the helper methods I added into the `AnkiActivity` class, a corruption check on the database is performed before activity creations and collection loadings. If it goes to deck picker page, shows the dialog and performs a database check and repair if the user selects the option to do so.

## How Has This Been Tested?

https://user-images.githubusercontent.com/59933477/119974166-6b9f5a00-bfc5-11eb-802d-37ee5515c8cf.mov

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-05-28 15:06 UTC, david-allison-1 requested changes
This doesn't seem like an acceptable check to perform on every screen load as it'll be extremely slow.

It'd be better to catch the bubbled exception in the Task, and show a "database corrupt" message, like most of our code does.

Then add a few unit tests for various screens to ensure that they open and work with a corrupt DB

See usages of: https://github.com/ankidroid/Anki-Android/blob/4c30d333d92033c9f48143bdf51074055410abae/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L168

2021-05-28 18:20 UTC, david-allison-1 commented
> @david-allison-1 TBH I did try throwing exceptions to direct the issue to activities to display the dialogs, But got stuck at places where it would lead to "CollectionTask". Is there a way I can display the dialogs from there without adding a weakreference of the activity to its constructor?

Check the references to the variable that I linked, it's typically handled from a listener to the task, possibly converting to a result-like structure or Boolean

2021-05-28 21:44 UTC, dorrin-sot commented
Sorry 'bout the atomic commit. New approach is:

1. Everything is as normal until a corruption in the model is noticed (eg. it being null). Then an Exception (`CorruptDatabaseException` that was added for just this purpose) will be thrown.
2. The exception will travel out via `throws` until we get to a method in an activity or task class.
3. if it's an activity class it would catch that exception and call `showDbCorruptDialog`
4. if not it would use a listener class (`ShowDbCorruptDialogListener`) that also calls `showDbCorruptDialog`

2021-05-29 00:41 UTC, david-allison-1 requested changes
This change adds a lot of noise to the surrounding code. I don't feel this is necessary, but I'm happy to be mistaken.

The way I see it:

* All significant `libAnki` access should ideally be in `CollectionTasks` (otherwise, we block the UI)
* All CollectionTasks should be able to return a `Pair<Boolean, X>` (a result type) if necessary.
* Most error handling can be done by handling the listeners to the `CollectionTask`
* The main aim would be determining where errors can be raised, returning a result-like structure, and handling this with a "database corrupt".
* If the database is corrupt (a bad model ref for example), then it would be ideal to check for it in the single place where it first crashes, and then assume that it's fine, rather than propagate the error handling throughout the codebase: this adds noise to the code, and logically can't occur if we catch the first occurrence

2021-05-29 05:13 UTC, dorrin-sot commented
> This change adds a lot of noise to the surrounding code. I don't feel this is necessary, but I'm happy to be mistaken.
> 
> The way I see it:
> 
> * All significant `libAnki` access should ideally be in `CollectionTasks` (otherwise, we block the UI)
> * All CollectionTasks should be able to return a `Pair<Boolean, X>` (a result type) if necessary.
> * Most error handling can be done by handling the listeners to the `CollectionTask`
> * The main aim would be determining where errors can be raised, returning a result-like structure, and handling this with a "database corrupt".
> * If the database is corrupt (a bad model ref for example), then it would be ideal to check for it in the single place where it first crashes, and then assume that it's fine, rather than propagate the error handling throughout the codebase: this adds noise to the code, and logically can't occur if we catch the first occurrence


I do agree it's really ugly this way. I also have to say another way I tried that would be cleaner (and maybe faster) was in the beginning where I'd call to `DialogHandler` to open the dialog from wherever the error occurred; only problem was It would only handle the message when `onResume` was called so for example only when the back button was pressed. so not only would it not open the dialog on the desired activity, the context in the handler was also too old and couldn't be used for the alert dialog's context. 
Is this way valid? if so, how do I fix this issue?

2021-05-29 08:06 UTC, david-allison-1 commented
In the code sample linked, we discard the current activity and open the Deck Picker with a code to specify corruption.

There is a rare bug here (cast to DeckPicker failed) that I've been meaning to deal with for some time, but since you're discarding the activity you shouldn't need to worry about additional lifecycle events (other than those on the path to onDestroy

2021-06-01 05:39 UTC, dorrin-sot commented
@david-allison-1 sorry, didn't think it would take this long and I've got a bunch of exams coming up :(. Is it ok if I continue working on this in a few weeks?

2021-06-01 06:23 UTC, david-allison-1 commented
> @david-allison-1 sorry, didn't think it would take this long and I've got a bunch of exams coming up :(. Is it ok if I continue working on this in a few weeks?

Absolutely! Life takes priority. Good luck

2021-09-29 19:33 UTC, david-allison-1 reviewed
Sorry for the delay - missed the notification. In future, please follow up aggressively. 

This is entirely on me, and by no means an attempt to pass any sort of blame.

2021-09-29 19:33 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +    public void showDbCorruptDialog() {
We should ideally keep this in the "Main Screen" (currently the deck picker). We already have a dialog for this

2021-09-29 19:33 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +                .setTitle("Corrupt Database")
If we are going to use this (I'd expect it to be removed), strings need to be translatable

2021-09-29 19:33 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            showDbCorruptDialog();
We already have a dialog for a DB error. Is there a reason we're not using this?

2021-09-29 19:33 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.java
> +                    builder.negativeText(res().getString(R.string.dialog_ok))
What's going on here? Shouldn't OK be positive?

2021-09-29 19:33 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                } catch (CorruptModelException e) {
I feel this should be a more general exception handler

2021-09-29 19:33 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                } catch (CorruptModelException e) {
likewise: probably better as a general exception handler

2021-09-29 19:33 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
> +                m = get(mCol.getDecks().current().optLong("mid", -1));
We shouldn't go about changing libAnki code. 

This code needs to be consistent with the Anki Desktop backend, as we're making a transition to this (see ModelsV16.kt)

2021-11-13 19:35 UTC, mikehardy commented
Can always reopen but based on comments and conflict state seems better to start fresh on this one

2021-11-13 19:35 UTC, closed without merging