Fix floating point numbers for steps in Deck Options
ankidroid/Anki-Android pull request #9009
Opened 2021-05-29 21:06 UTC by Peyman-hme

## Pull Request template

## Purpose / Description
`JsonArray` has a `put` method with double input. When we set its input with float variable, it was casted to double and then we may see a number with different value.

## Fixes
Fixes #8995

## Approach
Change `float` variable to `double`.

## How Has This Been Tested?

Emulated device Samsung A50 SDK 28.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-05-29 21:24 UTC, mikehardy requested changes
I had the tiniest formatting nitpick
Everything else appears fine, I'll approve the CI run, can you post a screenshot that shows the correct behavior? That would really help us verify it

Thanks!

2021-05-29 21:24 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.java
> +                int i =(int) d;
spacing nitpick, nothing more 
```suggestion
                int i = (int) d;
```

2021-05-29 21:55 UTC, Peyman-hme commented on AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.java
> +                int i =(int) d;
Sure.
Screenshots:
![Floating_1](https://user-images.githubusercontent.com/62210041/120085518-1f9c0480-c0ee-11eb-820f-dc4bb508e0c6.jpg)

And the result is:

![Floating_2](https://user-images.githubusercontent.com/62210041/120085522-23c82200-c0ee-11eb-8153-81ba54345c98.jpg)

2021-05-29 22:16 UTC, mikehardy approved these changes
A thing of beauty! Thank you!

2021-05-30 00:37 UTC, david-allison-1 commented
I'd like to take a quick look at this on my phone before a merge

Main concern would be regarding syncing to Anki (whether the rust can cope with higher precision)

And whether this fixes the issue: I don't see how adding more significant digits will help if the number isn't representable in binary

2021-05-30 01:17 UTC, david-allison-1 approved these changes
Surprised: all looks good, cheers!

2021-05-30 14:39 UTC, merged

2021-06-23 17:28 UTC, mikehardy commented
Hi there!

Apologies for the delay, and if you're already submitted something to OpenCollective for May 2021 PRs merged, you may feel free to ignore this.

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for May 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in May)

Thanks!