Add preference for full screen navigation drawer
ankidroid/Anki-Android pull request #9015
Opened 2021-05-30 11:10 UTC by ShridharGoel

## Purpose / Description
Add preference for full screen navigation drawer.

## Fixes
Fixes #8936 

## Approach
Added preference for selecting whether full screen navigation drawer should be enabled. By default, it will be off.
 
## How Has This Been Tested?
Verified that the functionality is working.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-05-30 14:52 UTC, Arthur-Milchior reviewed
I hope we can find better. This lead to a lot of code repetition. If we have to duplicate layout files for each potential option that can be on or off, it will lead to a lot of code duplication.

I really don't know a lot about views, so I don't know the path forward and would probably require a lot of time to find what should actually be done.

I hope there is a way to create our own layout/view, that takes as children other layouts. Then it behaves either as a standard drawable or as a full drawable depending on a parameter.

2021-05-30 15:54 UTC, ShridharGoel commented on AnkiDroid/src/main/res/layout-television/reviewer.xml
> -    <com.drakeet.drawer.FullDraggableContainer
There are two versions for `layout-television` as well: `reviewer.xml` and `reviewer_with_fullscreen_drawer.xml`.

Should I still revert it?

2021-05-30 15:55 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        if (preferences.getBoolean("gestureFullScreenNavigationDrawer", false)) {
Updated.

2021-05-30 17:29 UTC, Arthur-Milchior reviewed
If it's a high priority, I guess we can accept it as is. I'll open an issue to check whether it can be factorized after that

2021-05-30 17:29 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +import static com.ichi2.anki.CardBrowser.Column.EDITED;
There is quite a lot of things here. Can you deactivate the feature that make all of those change? They are unrelated and make hard to read what your commit actually do

2021-05-30 17:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/layout-television/reviewer.xml
> -    <com.drakeet.drawer.FullDraggableContainer
I don't think you have to revert. I guess it makes sens to use the same thing than everywhere.
But really, I've no idea what it means to have a drawer on TV in the first place

2021-05-30 18:00 UTC, ShridharGoel commented
Updated to implement this in a better way.

2021-05-30 18:04 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +import static com.ichi2.anki.CardBrowser.Column.EDITED;
I'll revert these changes.

2021-05-30 18:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        }
It seems those lines are copy-pasted 6 times. Can you factorize it into a method in `NavigationDrawerActivity`If I get it right, the main difference between each case is the layout ID you are using. If this is right, maybe you can put the code into `super.onCreate` and just make it call an abstract method that returns the Layer Resource

2021-05-30 22:49 UTC, david-allison-1 commented
Test failures are legit

2021-05-30 22:56 UTC, david-allison-1 requested changes
If I understand this correctly, it's a large change on the `.xml` side because it's reverting https://github.com/ankidroid/Anki-Android/pull/8071 and implementing it in a much nicer manner.

This is great! It would be much nicer if some work could be done to refactor the call in the code. I think we could handle it in: `NavigationDrawerActivity.setContentView` (if possible).

If not, let us know and we'll hopefully be able to come up with something better

2021-05-30 22:56 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +import static com.ichi2.anki.cardviewer.ViewerCommand.COMMAND_LOOKUP;
Could you revert these changes unless necessary, it makes it harder to read the diff

2021-05-31 04:49 UTC, ShridharGoel commented
@Arthur-Milchior @david-allison-1 Thanks for the suggestions. I have updated the code.

2021-05-31 04:53 UTC, david-allison-1 reviewed
Looks great! only a couple nitpicks, then good to go

2021-05-31 04:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        super.setContentView(getContentViewAttr(mPrefFullscreenReview));
nit: you can keep these as `setContentView(getContentViewAttr(mPrefFullscreenReview));`

2021-05-31 04:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +        ClosableDrawerLayout closableDrawerLayout = (ClosableDrawerLayout) LayoutInflater.from(this).inflate(R.layout.navigation_drawer_layout, null, false);
A comment here explaining why would be useful

2021-05-31 06:06 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        super.setContentView(getContentViewAttr(mPrefFullscreenReview));
Updated.

2021-05-31 06:06 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +        ClosableDrawerLayout closableDrawerLayout = (ClosableDrawerLayout) LayoutInflater.from(this).inflate(R.layout.navigation_drawer_layout, null, false);
Updated.

2021-05-31 06:06 UTC, david-allison-1 approved these changes
LGTM, thanks!

2021-06-02 03:59 UTC, mikehardy approved these changes
Nice! Thanks @ShridharGoel

2021-06-02 04:00 UTC, merged

2021-06-02 20:46 UTC, mikehardy commented
This is the root cause of #9052 - on a phone layout (not fragmented with study options already open on side of deck list) if you touch the 3 digits next to any deck in the deck list it *should* open the study options for that deck but instead it crashes. I'm reverting it on the stable branch.

2021-06-03 15:18 UTC, ShridharGoel commented
The crash caused by this has been fixed in #9057.