#8976: Add optional 2x2 grid for answer buttons
ankidroid/Anki-Android pull request #9020
Opened 2021-05-30 17:12 UTC by vbh

## Pull Request template

## Purpose / Description
Optional 2x2 grid for answer buttons.

## Fixes
Fixes #8976 

## Approach
Added preference for selecting large answer buttons. By default, it will be off.

## How Has This Been Tested?
Verified that the functionality is working.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-05-30 17:22 UTC, david-allison-1 reviewed
Hi, could you add screenshots to the OP please

2021-05-30 17:22 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                    getCol().getConf().put("largeAnswerButtons", !((android.preference.CheckBoxPreference) pref).isChecked());
Can we have this in shared preferences rather than conf

2021-05-30 17:23 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/strings.xml
> +    <string name="show_large_answer_buttons">Show Large Answer Buttons</string>
See: https://github.com/ankidroid/Anki-Android/wiki/Translating-AnkiDroid#logic-of-the-separation-in-different-files 

This should be in a different file

2021-05-30 17:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                    getCol().getConf().put("largeAnswerButtons", !((android.preference.CheckBoxPreference) pref).isChecked());
This line can be removed

2021-05-30 19:01 UTC, mikunimaru commented
What is the design when there are 3 buttons, such as in the early stages of learning?  I would like to see a screenshot comparing the four, three and two answer buttons.

2021-05-31 02:56 UTC, mikehardy commented
@mikunimaru great point on 4 vs 3 vs 2 buttons, I had not considered that! Would you be okay with 3 buttons going with 2 on top and one spanning completely across bottom, then 2 buttons layed out as one button on top spanning across whole row and one button on bottom spanning whole row? I *think* that would be not too bad to implement...

2021-05-31 06:14 UTC, mikunimaru commented
I thought it would be better to keep the position and size fixed even if the number of buttons changed. Here is a simple illustration.
![68747470733a2f2f696d61676573322e696d67626f782e636f6d2f36382f34352f494575494877304d5f6f2e706e67_1](https://user-images.githubusercontent.com/43168745/120147373-83731a00-c221-11eb-851e-83084e446510.jpg)

Stretching to the entire width is a big change and may induce false taps, especially for users who are not good at tapping, who are expected to use this option.

2021-05-31 06:18 UTC, mikehardy commented
Okay, so, if any button is not valid for a given card, just remove the button. We can do that at first, and see how it goes

2021-05-31 16:40 UTC, david-allison-1 requested changes
Review is on 07708612b2d59e4ed4241d3e708dcfc36241733b

* This doesn't play well with the animation on the "show answer" (minor visual flickering)
    * I feel we should double the size of the "show answer" button, so the user doesn't need to move their finger to select, this should also fix the above
* The "Good" button doesn't appear on SchedV1
* "Good/Again" only shows "Again" (SchedV1)
* The setting should be closer to the bottom as it's of limited usage

2021-05-31 16:40 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="show_large_answer_buttons" maxLength="41">Show Large Answer Buttons</string>
```suggestion
    <string name="show_large_answer_buttons" maxLength="41">Show large answer buttons</string>
```

2021-05-31 21:28 UTC, david-allison-1 approved these changes
Visually, looks great! Thank for the quick turnaround

We may want to extract the code into a separate class, but I'm fairly ambivalent

2021-06-02 19:11 UTC, mikehardy approved these changes
@vbh thanks for taking this on! This will be our first 2.16 feature out in the first 2.16alpha1 build for testing :smile:

2021-06-02 19:12 UTC, merged

2021-07-31 20:36 UTC, mikehardy commented
Hi there!

Apologies for the delay, and if you're already submitted something to OpenCollective for PRs merged in June 2021 PRs merged, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for June 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in May)

Thanks!