Add Browse Cards option in Deck Picker's context menu
ankidroid/Anki-Android pull request #9047
Opened 2021-06-02 12:36 UTC by ShridharGoel

## Purpose / Description
Add Browse Cards option in Deck Picker's context menu.

## Fixes
Fixes #8187 

## Approach
Added the option and its functionality to the menu.

## How Has This Been Tested?
Verified.

<details>
<summary>Screenshot</summary>

![DeckPickerContextMenu](https://user-images.githubusercontent.com/35566748/120480383-98d87780-c3cc-11eb-94f4-d72093569b46.jpeg)
</details>

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-06-02 12:51 UTC, david-allison-1 approved these changes
LGTM, thanks!

2021-06-02 19:14 UTC, mikehardy requested changes
A really minor comment, otherwise ready to go, thanks @ShridharGoel

2021-06-02 19:14 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.java
> +        ArrayList<Integer> itemIds = new ArrayList<>();
```suggestion
        ArrayList<Integer> itemIds = new ArrayList<>(10); // init with our fixed list size for performance
```

@Arthur-Milchior went to quite a bit of trouble to pre-size all of the arrays in the system to gain a bit of performance, keeping the initializer here and just increasing it one is optimal I believe

2021-06-03 15:25 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.java
> +        ArrayList<Integer> itemIds = new ArrayList<>();
This has been updated.

2021-06-20 03:44 UTC, mikehardy approved these changes
Really sorry for the delay! LGTM

2021-06-20 03:44 UTC, merged