Draft: WYSIWYG Editor
ankidroid/Anki-Android pull request #9048
Opened 2021-06-02 12:45 UTC by Akshay0701

## Purpose / Description
Follow-on from #7962 with commits cleaned and most review feedback handled.

Performed as trgk on Discord is interested and it'd be great to get this across the finish line.

Required:

- Remove reference to implementation 'com.github.jkennethcarino:RTextEditorView:0.1.1' and include summernote in a new commit (before Initial Commit) - document how summernote was included in the commit message

- Consider: whether this would be best in a separate library to reduce the load on git when summernote updates

- Reconsider color picker library as it is not maintained
- Consider: Move the "Add List" functions behind an "experimental" feature flag, as they're not perfect
- A few TODOs related to the WebView renderer crashing. See: onRenderProcessGone

## Fixes
Fixes #1377

## Approach
Features

Bold/Italic/Underline
Cloze
Text Align
Lists (bullet & numbered)
Remove Formatting
Insert & Delete Image & move via copy/paste (needs testing, and probably help)
Horizontal Line
Record Audio
MathJax
Sound and Video work via [sound:]
Text/Background Color
View HTML
<iframe> does not work in the viewer or the editor for me

2021-06-02 12:46 UTC, Akshay0701 commented
should we consider this https://github.com/mrudultora/Colorpicker color picker ?

2021-06-02 15:38 UTC, Akshay0701 commented
## Implemented save presets 
<img src="https://user-images.githubusercontent.com/52353967/120509771-6e93b380-c3e6-11eb-986a-919871ec193a.gif" width="250" height="500" />

2021-06-02 19:20 UTC, mikehardy commented
I'm okay with @mrudultora's color picker yes

2021-06-04 09:12 UTC, Akshay0701 commented
## Implemented whiteboard in visual editor
https://user-images.githubusercontent.com/52353967/120777503-f8f12a00-c542-11eb-98e8-6916b67b6f35.mp4

2021-06-06 09:53 UTC, Akshay0701 commented
## Implemented Undo / Redo
<img src="https://user-images.githubusercontent.com/52353967/120920135-fe817800-c6da-11eb-98b4-ac510412988a.gif" width="250" height="500" />

2021-06-10 04:31 UTC, Akshay0701 commented
@david-allison-1 you mentioned in https://github.com/ankidroid/Anki-Android/pull/9048#issue-660033774 that the iframe is not working, I did search whether its summer note problem or browser and found the cause  https://github.com/tneotia/html-editor-enhanced/issues/12

the solution is to append `https: in src then it's working fine

2021-06-10 04:37 UTC, Akshay0701 commented
one question: do we really need to give the option to embed links or videos in notes? because upstream anki doesn't have that functionality.

2021-06-10 15:59 UTC, david-allison-1 commented
> one question: do we really need to give the option to embed links or videos in notes? because upstream anki doesn't have that functionality.

If Anki didn't have it, then there's no need to handle it

2021-06-10 16:06 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +        if(mIsVisualEditorWhiteBoard) {
i think instead of `mIsVisualEditorWhiteBoard` variable name, we should give `mIsHandleMultiTouch`

2021-06-10 16:08 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +        if(mIsVisualEditorWhiteBoard) {
Sounds good to me

2021-06-10 16:10 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +        if(mIsVisualEditorWhiteBoard) {
and note: we didn't handle multi-touch in draw activity because it will be blank activity. 
In the case of Reviewer activity, we handle multi-touch because it's going to have a card inside it

2021-06-10 16:12 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/VisualEditorActivity.java
> +                break;
I registring media twice here, its my mistake but no worry, resolved it with recent 88c0d989ccaa44082e3bc968e5ae990e41c2717a

2021-06-10 16:15 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/visualeditor/FontSelectionDialog.java
> +public class FontSelectionDialog {
I think not required because the AnkiDesktop version doesn't give functionality to custom size font, going to remove.

2021-06-10 16:16 UTC, Akshay0701 commented on AnkiDroid/src/main/res/drawable/ic_visibility_black_24dp.xml
> -<vector xmlns:android="http://schemas.android.com/apk/res/android"
removed because duplicated

2021-06-10 16:17 UTC, Akshay0701 commented on AnkiDroid/src/main/res/drawable/ic_visibility_white_24dp.xml
> -<vector android:height="24dp" android:tint="#FFFFFF"
removed because duplicated

2021-06-10 16:17 UTC, Akshay0701 commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
> +    <string name="visual_editor_font_size">Text Size</string>
reason to change string: previous string was a duplicate of others string

2021-06-10 16:19 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/VisualEditorActivity.java
> -        webView.load();
extracted to  `WebViewUndoRedo`

2021-06-10 16:53 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/visualeditor/WebViewUndoRedo.java
> +public class WebViewUndoRedo {
### About WebViewUndoRedo implementation 
I used LinkedList data structure to store all changes of editor in a linear way and maintained pointer which will point to the current version of the editor, user can use undo/redo by simply incrementing pointer or decrementing.
for now, I set the max size of LinkedList 20 (not sure should I increase it or not)
I tried to implement and tested not found any bugs yet, but I request you to test it by yourself and let me know if there is an unexpected bug.

2021-06-10 17:00 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +public class RegisterMediaForWebView {
I required register media code in summer note class for paste image event (extracted code to avoid duplication of code)

2021-06-11 06:10 UTC, prateek-singh-3212 commented
Hi @Akshay0701 ,
I Just wanted to ask that have you updated the summernote version? because in the version which we are using their are several bugs in it (I have Not followed this PR for long time so I don't know if you have done so..).

@david-allison-1 I Just wanted to know that how to do I contribute in this PR ? I their is the way by which 2 people can contribute in 1 PR.

2021-06-11 09:37 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/visualeditor/FontSelectionDialog.java
> +public class FontSelectionDialog {
@david-allison-1... response needed and also should start writing tests for editor ?

2021-06-11 11:49 UTC, Akshay0701 commented
> I Just wanted to know that how to do I contribute in this PR ? I their is the way by which 2 people can contribute in 1 PR.

yes sure, 
pull this pr on your local machine,
then clone pr and you can change and add commits to it,
after you done publish your branch and share its link here, we will look that branch and I will cherry-pick your commits 
btw what you will like you to contribute?

2021-06-16 15:50 UTC, david-allison-1 requested changes
Thanks!!!!!!!!!!!!!!!!!!!!!

First round of changes, honestly nothing major.

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/build.gradle
> +    implementation 'com.github.jkennethcarino:RTextEditorView:0.1.1'
I think we should remove this dependency and include the summernote files ourselves. This allows us to document and handle the dependency update procedure

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/build.gradle
> +    implementation 'com.jaredrummler:colorpicker:1.1.0'
Question: do we want to use mrudultora's color picker?

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/AndroidManifest.xml
> +        <activity android:name=".DrawingActivity" />
This seems to be missing attributes

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/assets/visualeditor/visualeditor.css
> +/* //FIXED BUG: <hr/> is  less thick in the editor */
can remove the comment then

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +    }
I like this, we might want to separate this out into a separate commit/PR to get it into `master` more easily

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.java
> +public class DrawingActivity extends AnkiActivity {
Could you add a quick comment to explain what this does?

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.java
> +    public static final String EXTRA_RESULT_WHITE_BOARD = "drawing.editedImage";
nit: WHITEBOARD is one word

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.java
> +        }
seems identical to `AnkiActivity.enableToolbar`

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.java
> +    private void createWhiteboard() {
design nit: return mWhiteBoard here and set it in `onCreate`

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.java
> +        mWhiteboard = new Whiteboard(this, true, isInNightMode(sharedPrefs));
this code is likely duplicated between here and `Reviewer.java`, it'd be useful to move it to a static methods on `Whiteboard` if feasible to reduce code duplication

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.java
> +        mWhiteboard = new Whiteboard(this, true, isInNightMode(sharedPrefs));
(optional, likely add a TODO here as it's a fair bit of work for minimal gain)

You might also want to consider seeing if you can change `Whiteboard` so it can be included as a view, rather than creating it in code

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.java
> +            Timber.w(e);
If an exception occurs, do you want to exit?

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +                //TODO: Duplication
flagging TODO

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +                UIUtils.showThemedToast(this, "Unable to open Visual Editor", false);
hardcoded string

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +                Timber.e(e, "Unable to open Visual Editor");
```suggestion
                Timber.w(e, "Unable to open Visual Editor");
```

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +public class RegisterMediaForWebView {
Add this as a comment at the top of the class

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +        mPastedImageCache = new HashMap<>();
inline this

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +        mAnkiActivity = new AnkiActivity();
you shouldn't need this, and it's worrying

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +            mAnkiActivity.getCol().getMedia().addFile(f);
`CollectionHelper.getInstance()` if you really need it, don't make a new `AnkiActivity`

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +        mWhiteboard = new Whiteboard(this, false,isInNightMode());
```suggestion
        mWhiteboard = new Whiteboard(this, false, isInNightMode());
```

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +public class RegisterMediaForWebView {
I'd suggest extracting this logic in a separate PR so we can get it in more easily

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +        mAnkiActivity = cardViewer;
rename to `activity`

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +        return AnkiDroidApp.getSharedPrefs(mAnkiActivity.getApplicationContext()).getInt("whiteBoardStrokeWidth", 6);
You should just be able to pass in the activity here

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +        if(mIsVisualEditorWhiteBoard) {
```suggestion
        if (mIsVisualEditorWhiteBoard) {
```

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +        if(mIsVisualEditorWhiteBoard) {
Again: better as a comment then in the PR comments - easier for the next dev to discover

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/visualeditor/WebViewUndoRedo.java
> +public class WebViewUndoRedo {
add the comment to the top of the file, along with a link (not required, but they'd appreciate it)

```
/*
 * THIS CLASS IS PROVIDED TO THE PUBLIC DOMAIN FOR FREE WITHOUT ANY
 * RESTRICTIONS OR ANY WARRANTY.
 */
```

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
> +    <string name="visual_editor_custom_buttons">Custom Buttons</string>
A lot of these can likely be consolidated with the NoteEditor toolbar strings

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/main/vector_source/add_equation.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Again, I don't think we need this as it's included in the Note Editor toolbar, consider rebasing this commit so the file doesn't appear in the history

2021-06-16 15:50 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.java
> +        notYetHandled(DrawingActivity.class.getSimpleName(), "Not working (or implemented) - inherits from AnkiActivity");
Might want to handle this - shouldn't be difficult

2021-06-16 16:46 UTC, mikehardy commented on AnkiDroid/build.gradle
> +    implementation 'com.jaredrummler:colorpicker:1.1.0'
> Question: do we want to use mrudultora's color picker?

Definitely yes

2021-06-16 17:22 UTC, Akshay0701 commented on AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.java
> +        notYetHandled(DrawingActivity.class.getSimpleName(), "Not working (or implemented) - inherits from AnkiActivity");
okay, i am not aware how to handle this, can you please tell me....

2021-06-16 17:29 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
> +    <string name="visual_editor_font_size">Text Size</string>
We might as well use the duplicates if they're for the same purpose, it saves translator effort

2021-06-16 17:31 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.java
> +        notYetHandled(DrawingActivity.class.getSimpleName(), "Not working (or implemented) - inherits from AnkiActivity");
TODO: Improve the test documentation

add to `onCreate`
```
        if (showedActivityFailedScreen(savedInstanceState)) {
            return;
        }
```

2021-06-16 17:55 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.java
> +            Timber.w(e);
not sure, that might lose drew image.

2021-06-16 17:56 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.java
> +            Timber.w(e);
for now, i will include finally block here for finishing activity

2021-06-16 18:01 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.java
> +    private void createWhiteboard() {
``` java  
    private void createWhiteboard() {
        mWhiteboard = Whiteboard.instance(this, false);
        FrameLayout fl = findViewById(R.id.whiteboard);
        fl.addView(mWhiteboard);
        mWhiteboard.setOnTouchListener((v, event) -> mWhiteboard.handleTouchEvent(event));
    }
```


> design nit: return mWhiteBoard here and set it in onCreate

after extracting code looks more clean, i think it would be good to directly take `WhiteBoard.instance()` code in `onCreate `method.

2021-06-17 08:33 UTC, Akshay0701 commented
I know right now commits are not well managed, but don't worry once I am done with proper implementation at end I will make commits in proper order, 

Right not dropped `Rtexteditorview` library and include lastest summer note version, 
cheers.

2021-06-17 13:05 UTC, Akshay0701 commented on AnkiDroid/build.gradle
> +    implementation 'com.jaredrummler:colorpicker:1.1.0'
will do

2021-06-17 13:22 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +public class RegisterMediaForWebView {
okay I will create pr only contaning with `registerMediaForWebview `class

2021-06-17 16:37 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +        mPastedImageCache = new HashMap<>();
sorry, what is inline, what I suppose to do?

2021-06-17 16:43 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +        mPastedImageCache = new HashMap<>();
```  java  // Use the same HTML if the same image is pasted multiple times.
      private final HashMap<String, String> mPastedImageCache = new HashMap<>();
```
like this ?

2021-06-18 13:53 UTC, Akshay0701 commented on AnkiDroid/build.gradle
> +    implementation 'com.jaredrummler:colorpicker:1.1.0'
I will like to include mrudultora's libary,
I requested him few customizations in code, once there are done then we will include his library

2021-06-18 15:36 UTC, mikehardy commented on AnkiDroid/build.gradle
> +    implementation 'com.jaredrummler:colorpicker:1.1.0'
My "definitely yes" should be read as please use it now, even if you don't have everything you want yet
We looked at all the other colorpickers and I do not want to integrate them even temporarily
Post a PR to his library if you need to, but please do not incorporate any other color picker
Thanks

2021-06-18 15:40 UTC, Akshay0701 commented on AnkiDroid/build.gradle
> +    implementation 'com.jaredrummler:colorpicker:1.1.0'
not at all, I am not considering any other don't worry, a few errors and UI problems need to resolve and I raise issues for that, me and mrudultora's will going to solve that issues.

2021-06-18 15:52 UTC, Akshay0701 commented on AnkiDroid/build.gradle
> +    implementation 'com.jaredrummler:colorpicker:1.1.0'
Done ! @mikehardy.

2021-06-18 17:13 UTC, Akshay0701 commented
@david-allison-1 done with changes

2021-06-20 11:22 UTC, Akshay0701 commented
Wow, rebasing is to fun and confusing at same time, I hope I didn't mess this time 🤞

2021-08-09 19:20 UTC, david-allison-1 requested changes
What do we need the fonts for? Can we avoid them? As they're fairly large and we use our own

* Undo and redo aren't disabled if no action can take place
* You can't drag & drop images
  * mention that you should use cut & paste instead
* Cut & paste doesn't work for whiteboard images, which was the point

2021-08-09 19:20 UTC, david-allison-1 commented on AnkiDroid/src/main/assets/visualeditor/visual_editor_image.js
> +    //TODO
flagging TODO

2021-08-09 19:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +    public static Whiteboard instance(AnkiActivity context, Boolean handleMultiTouch) {
```
    public static Whiteboard createInstance(AnkiActivity context, Boolean handleMultiTouch) {
```

2021-08-09 19:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +     * note: we didn't handle multi-touch in draw activity because it will be blank activity.
Move the comment inside the method, it's not general documentation about the method

2021-08-09 19:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.java
> + */
This is awesome! Would be great to combine with the "gallery/camera" as well

2021-08-09 19:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +                requestEdit(REQUEST_VISUAL_EDIT, resultCode, data);
Consider moving to the new Activity handling here, no point in adding to `onActivityResult` if it's going to be  deprecated

2021-08-09 19:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +        if (mHandleMultiTouch) {
invert the if and return early if false

2021-08-09 19:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/VisualEditorActivity.java
> +            //Currently only used for
missing comment

2021-08-09 19:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/VisualEditorActivity.java
> +    public boolean isHasLoadedCol() {
```
    public boolean hasLoadedCol() {
```

2021-08-09 19:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/VisualEditorActivity.java
> +            Timber.e(e, "Failed to init web view");
Change all the `Timber.w` to `Timber.e`

```suggestion
            Timber.w(e, "Failed to init web view");
```

2021-08-09 19:22 UTC, david-allison-1 commented
We need a different icon for the whiteboard if possible

2021-08-10 07:45 UTC, Akshay0701 commented
created #9394 pr for drawing, I will resolve the conflict once that pr gets in master.

2021-08-10 14:35 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/VisualEditorActivity.java
> +            Timber.e(e, "Failed to init web view");
it confusing,

in comment, you said "change Timber.w to Timber.e"

and in suggested code you changed "Timber.e to Timber.w"

2021-08-17 05:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/VisualEditorActivity.java
> +            Timber.e(e, "Failed to init web view");
I profusely apologise. `Timber.w` for all but non-fatal errors

2021-08-17 05:08 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/VisualEditorActivity.java
> +            Timber.e(e, "Failed to init web view");
I profusely apologise, I'd made the correct suggestion, and the incorrect comment

2022-01-02 19:44 UTC, mikehardy commented
open for harvesting

2022-01-02 19:45 UTC, mikehardy commented
Or actually @Akshay0701 - as valuable as the kotlin is, getting this done would make millions of people worldwide do a little happy dance of joy ;-)

2022-01-03 16:15 UTC, Akshay0701 commented
@mikehardy this pr included almost all features that visual editor needs, 

but right now i am not able to rebase this branch properly, everything gets messing whenever i do rebase, i am still trying to resolve conflicts from this branch, it would be helpful if you or anyone else rebase this branch properly...

2022-01-03 16:16 UTC, mikehardy commented
Okay, I can give the rebase a try

2022-01-03 16:18 UTC, Akshay0701 commented
Thanks

2022-01-04 05:25 UTC, Akshay0701 commented
done with the rebase

2022-01-04 08:21 UTC, Akshay0701 commented
@david-allison-1 and @mikehardy test this feature on your phone, and let me know if there is any changes 

I tested this feature, and everything work good expect there is one audio bug, I am solving that right now

2022-01-04 16:39 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/VisualEditorActivity.java
> +        UIUtils.showThemedToast(this, "Unable to start visual editor", false);
Probably a few more strings that need to be extracted

2022-01-04 16:51 UTC, david-allison-1 requested changes
Seems good!

Initial feedback: Trying to close the editor asks if I want to save, even if no changes are made

There's an issue with newlines, a newline in the field is handled differently than a newline in the editor.

2022-01-04 18:48 UTC, Akshay0701 commented
how do fields handle newlines?

2022-01-04 18:53 UTC, Akshay0701 commented
do they also add extra HTML text like editor whenever a newline is created?

I also search this issue on the summer note github, seems like editor core code adds <p> something like codes and that makes show message "if want to save" ... 

i am looking into this, let me know if you have the solution or way to solve this issue...

2022-01-04 21:21 UTC, david-allison-1 commented
Code ref:

https://github.com/ankidroid/Anki-Android/blob/8a4ee594f8055857dcd6dbecb7cbfa71af1646f9/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L1071-L1074

2022-01-05 19:30 UTC, Akshay0701 commented
```
2022-01-06 00:58:41.120 29163-29163/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 29163
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3611)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
        at com.ichi2.anki.multimediacard.impl.MultimediaEditableNote.getInitialFieldCount(MultimediaEditableNote.java:131)
        at com.ichi2.anki.multimediacard.fields.BasicAudioRecordingFieldController.addFieldPreview(BasicAudioRecordingFieldController.java:92)
        at com.ichi2.anki.multimediacard.fields.BasicAudioRecordingFieldController.createUI(BasicAudioRecordingFieldController.java:74)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.recreateEditingUi(MultimediaEditFieldActivity.java:205)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.onCreate(MultimediaEditFieldActivity.java:121)
        at android.app.Activity.performCreate(Activity.java:8006)
        at android.app.Activity.performCreate(Activity.java:7990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)

```

this is the error I am getting after clicking audio button in visual editor, everything seems right in visual editor code, do you anyone know what is the cause of this error and how can I solve this?

2022-01-14 19:04 UTC, Akshay0701 commented
1. updated cleaned the code(more to be done),
2. comment redo/undo buttons for now(will solve this bug)
3. audio button error(i looked into it, new changes have been done, wherein audio recording activity needs fields, whereas in visual editor activity we don't have all fields, I still don't understand the error properly, trying...)
4. commits are full of mess(pardon me for this, don't review the code commit vise, i request reviewers to review the whole activity of visual editor, and let me know if there are more bugs or any changes you want)

2022-07-02 16:43 UTC, closed without merging