[Preference] Paste clipboard image as PNG
ankidroid/Anki-Android pull request #9080
Opened 2021-06-05 15:07 UTC by Akshay0701

## Pull Request template

## Purpose / Description
AnkiDesktop have feature of "Paste Clipboard Image As PNG " in the preference window ,
currently AnkiDroid do support to copy and paste image but not have this preference option in app.

## Fixes
Fixes #8709

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-06-27 14:05 UTC, mikehardy reviewed
This seems good - all the code seems good, I just have a question on whether this is really sufficient to paste in the PNG format or if it is just changing the name. Easily resolved by pasting a JPG then checking the resulting file via in the collection via  file examination tools (`file` on linux would do it...) to verify that the file really was PNG

2021-06-27 14:05 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +            clipCopy = File.createTempFile(fileName, ".png");
Interesting! Does simply forcing the extension to .png cause the system to actually paste the image as PNG or is the [file type / file magic](https://en.wikipedia.org/wiki/File_format#Magic_number) still the original source (not png) and it just has `.png` on the end of the name?

2021-06-27 14:12 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +            clipCopy = File.createTempFile(fileName, ".png");
your complete right, this was code by a contributor(thanks for noticing)
yes we can convert actually file like this 
``` java 
try {
   FileOutputStream out = new FileOutputStream(filename);
   bmp.compress(Bitmap.CompressFormat.PNG, 100, out); //100-best quality
   out.close();
} catch (Exception e) {
   e.printStackTrace();
}
```
let me know if we want to keep the quality percentage at 100

2021-06-27 15:20 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +            clipCopy = File.createTempFile(fileName, ".png");
- We should have the luxury of deferring quality percentage to upstream. Let's use whatever they use
- I realize this may have just been a sort of sketch but the error handling here will be inadequate if this is the implementation. Needs to be a Timber.w(e, "some message") along with probably our generic "something went wrong toast" ideally with the e.getMessage so the user can take care of it (probably a bitmap too big error or something if they paste a huge image), and we need to make sure that the file handle is closed no matter what, so it should be either a try with resources or in a finally  block do a close attempt

2021-06-28 14:35 UTC, mikehardy requested changes
I think just the error message handling and this is probably good to go - will be nice to achieve parity with desktop here!

2021-06-28 14:35 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +                UIUtils.showThemedToast(mContext, "something went wrong : " + e.getMessage(), true);
I think more like this:

```java
UIUtils.showThemedToast(mActivity, mActivity.getResources().getString(R.string.multimedia_editor_something_wrong), false);
```

(although maybe `true` for a long toast also fits)

It may be that is not *perfect* since we do have an error here. Perhaps a new string `multimedia_editor_something_wrong_details` that takes an `$1` in it so you may do string formatting, then you send in `e.getMessage`?

We must never send untranslated text through to the display though ever - that's a hard rule in internationalized projects (and in software development in general, all projects should have internationalization capabilities so in general I'd say never ever send a raw string through to the user as a general rule)

2021-06-28 21:49 UTC, mikehardy requested changes
almost trivial error handling item, rest looks great - I like the new UI message

2021-06-28 21:49 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +                outStream.close();
This is really really close now - all I can see now is that if `bm.compress()` throws an exception, we leak the open file handle from the FileOutputStream

the outStream needs to be handled either in try-with-resources so it closes automatically or in a finally declaration

Something like (warning! coding in a web text area! code probably crap)

```java
FileOutputStream outStream;
try {
  outStream = new FileOutputStream(clipCopy.getAbsolutePath());
  bm.compress(Bitmap.CompressFormat.PNG, 100, outStream);
  otuStream.flush();
} catch (IOException e) {
  Timber.w("MediaRegistration : Unable to convert file to png format");
  UIUtils.showThemedToast(mContext, mContext.getResources().getString(R.string.multimedia_editor_something_wrong_details, e.getMessage()), true);
} finally {
  try { outStream.close() } catch (Exception e) { /* do nothing */ }
}
```

2021-06-28 21:54 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +                outStream.close();
Should be able to use try-with-resources here
```java
try (FileOutputStream outStream = new FileOutputStream(clipCopy.getAbsolutePath()) {
  bm.compress(Bitmap.CompressFormat.PNG, 100, outStream);
  otuStream.flush();
} catch (IOException e) {
  Timber.w("MediaRegistration : Unable to convert file to png format");
  UIUtils.showThemedToast(mContext, mContext.getResources().getString(R.string.multimedia_editor_something_wrong_details, e.getMessage()), true);
}
```

2021-06-28 22:05 UTC, david-allison-1 reviewed
I'd like to check with @dae on this one, given that he has more context for why this was implemented in Anki.

In a desktop-based context, screenshots are the most often copy-pasted, which should compress well as `.png`s.

On Android, we'll likely end up increasing the file size on average for most use cases, as we don't move screenshots to the clipboard.

If there was a secondary reason for why this feature exists (avoiding compression artifacts), it'd be good to document it while we're implementing this.

----

@Akshay0701 As for review comments: could you add more links to the Anki source, and how it works there, so we can compare implementations

2021-06-28 22:53 UTC, dae commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                    getCol().getConf().put("pastePNG", ((android.preference.CheckBoxPreference) pref).isChecked());
Yeah, it's a trade-off. jpeg is smaller for photos, but it can't handle images with transparent backgrounds, and is larger for some screenshots. The desktop uses the above setting in the collection; AnkiMobile uses .jpg unless the image has an alpha channel in it and does not expose a separate option.

2021-06-29 05:42 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +                outStream.close();
try-with-resources vs finally..
which one should be in use?

2021-06-29 13:19 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +                outStream.close();
try-with-resources is the modern way of doing things, it is preferred where possible

2021-06-29 13:25 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +                outStream.close();
Okay done!, Added try with resources

2021-06-29 14:15 UTC, mikehardy requested changes
Last thing I can think of - noted in a comment

2021-06-29 14:15 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +            }
The error handling all looks good now except the very last final result: I think we need to `return null` here now, otherwise we'll attempt to use the invalid `clipCopy` File reference

2021-06-29 14:37 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +            }
Oo I missed that thanks!

2021-06-29 18:55 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +            }
That's why we have review. The things I've missed that others have caught.... 😅

2021-06-29 18:57 UTC, mikehardy approved these changes
I can't see anything to comment on, this looks like it's good to go.
Going to re-request @david-allison-1 since he had commentary but I'd merge pending his thoughts

2021-06-29 22:15 UTC, david-allison-1 requested changes
Nitpicks only, LGTM.

I think we should focus on the comment below and:

* explain this reasoning in the commit message, and/or a comment in the code, or to the user in the summary
* Add a follow-up issue to follow AnkiMobile and paste as PNG if there's an alpha channel. I feel it's a sensible design decision

> Yeah, it's a trade-off. jpeg is smaller for photos, but it can't handle images with transparent backgrounds, and is larger for some screenshots. The desktop uses the above setting in the collection; AnkiMobile uses .jpg unless the image has an alpha channel in it and does not expose a separate option.

https://github.com/ankidroid/Anki-Android/pull/9080/files#r660166058

2021-06-29 22:15 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +                UIUtils.showThemedToast(mContext, mContext.getResources().getString(R.string.multimedia_editor_something_wrong_details, e.getMessage()), true);
This is a fixable issue by the user (disable converting to PNG), so could we add a specific error string here

2021-06-29 22:15 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +                return null;
Can we log an exception to ACRA here?

2021-06-29 22:15 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="paste_as_png_summary" maxLength="41">By default Anki pastes images on the clipboard as JPG files, to save disk space. You can use this option to paste as PNG images instead.</string
```suggestion
    <string name="paste_as_png_summary" maxLength="41">By default Anki pastes images on the clipboard as JPG files to save disk space. You can use this option to paste as PNG images instead.</string>
```

2021-06-30 00:57 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +                UIUtils.showThemedToast(mContext, mContext.getResources().getString(R.string.multimedia_editor_something_wrong_details, e.getMessage()), true);
That is not necessarily true. They may have chosen on desktop or somewhere else or sometimes else to paste as PNG, and just this time for whatever reason pasted something enormous and run out of space, as an example. That's why I requested the contents of e.getMessage(), but I'm not sure we can be more prescriptive than that for the user

2021-06-30 00:58 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +                return null;
🤔 I thought it was doing that already, but yes I do want an acra log at least to start. It may be noisy, we can disable it if so. There are other recent examples of PRs that send manual exception reports if look for exception and manual in the codebase it should turn up an example usage pattern

2021-06-30 01:00 UTC, mikehardy commented
> Nitpicks only, LGTM.
> 
> I think we should focus on the comment below and:
> 
>     * explain this reasoning in the commit message, and/or a comment in the code, or to the user in the summary
> 
>     * Add a follow-up issue to follow AnkiMobile and paste as PNG if there's an alpha channel. I feel it's a sensible design decision
> 
> 
> > Yeah, it's a trade-off. jpeg is smaller for photos, but it can't handle images with transparent backgrounds, and is larger for some screenshots. The desktop uses the above setting in the collection; AnkiMobile uses .jpg unless the image has an alpha channel in it and does not expose a separate option.
> 
> https://github.com/ankidroid/Anki-Android/pull/9080/files#r660166058

I think that (auto-switch to PNG if there is an alpha channel) for a follow-up PR. I think this is an area where starting by deferring to users' choice  and implementing the upstream feature is a reasonable start

2021-06-30 01:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +                UIUtils.showThemedToast(mContext, mContext.getResources().getString(R.string.multimedia_editor_something_wrong_details, e.getMessage()), true);
I suspect `Error converting clipboard image to png: %s` should work. 

The user then has context on the operation which was occurring and can google/disable the setting.

2021-06-30 02:11 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +                UIUtils.showThemedToast(mContext, mContext.getResources().getString(R.string.multimedia_editor_something_wrong_details, e.getMessage()), true);
Ah, I see, currently the error message is fairly generic ("something went wrong"), then the exception getMessage is appended.  @Akshay0701 so just alter the string constant to be png-specific and use David's text and that works for me too

2021-06-30 03:08 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +            clipCopy = File.createTempFile(fileName, ".png");
Just to note: can we skip this if the extension is already `.png`

2021-06-30 04:53 UTC, Akshay0701 commented
will create follow-up PR for the alpha channel.

2021-06-30 05:35 UTC, Akshay0701 commented
https://stackoverflow.com/a/31311718/14148406 take look at this, I think this will work for checking whether it a transparent image or not.

2021-06-30 08:56 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +        if (!fileNameAndExtension.getValue().equals(".png") && CollectionHelper.getInstance().getCol(mContext).getConf().optBoolean("pastePNG")) {
`.png` is guaranteed to be non-null

```suggestion
        if (!".png".equals(fileNameAndExtension.getValue()) && CollectionHelper.getInstance().getCol(mContext).getConf().optBoolean("pastePNG")) {
```

2021-06-30 09:34 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
> +    <string name="multimedia_editor_something_wrong_details">Error converting clipboard image to png: %s</string>
Could you rename this string name, good to go!

2021-06-30 12:46 UTC, mikehardy commented
Second angry unit test run that looks real - I'm still catching up on notifications but, did something merge in GestureMapper @david-allison-1 - same stacks as previous comment on unrelated PR re: unit test fail

```

        Caused by:
        java.lang.NoClassDefFoundError: Could not initialize class com.ichi2.anki.reviewer.GestureMapper
            at com.ichi2.anki.cardviewer.GestureProcessor.<init>(GestureProcessor.java:42)
            at com.ichi2.anki.AbstractFlashcardViewer.<init>(AbstractFlashcardViewer.java:350)
            at com.ichi2.anki.AbstractFlashcardViewerTest$NonAbstractFlashcardViewer.<init>(AbstractFlashcardViewerTest.java:37)
            at com.ichi2.anki.AbstractFlashcardViewerTest.typeAnsAnswerFilter(AbstractFlashcardViewerTest.java:72)
            at com.ichi2.anki.AbstractFlashcardViewerTest.testTypeAnsAnswerFilterNormalCorrect(AbstractFlashcardViewerTest.java:106)
```

2021-06-30 12:48 UTC, david-allison-1 commented
I did a while back, but this is confusing. Could this be caching related? Master is currently green

I'll have time to look tomorrow

2021-06-30 13:14 UTC, mikehardy commented
Huh - could be some sort of corrupt gradle cache - I'm still set up to pull PRs and validate CI locally, so if that's the only thing keep them marked pending merge and I'll chew through. Odd that it would be caching on multiple PR branches but could be

2021-06-30 13:43 UTC, mikehardy commented
With apologies @Akshay0701 as linked from #9157 this did collide. But ingesting the change from that PR is just switching pastePNG to a constant, trivial fix, but yes it is yet-another-change here before landing sorry

2021-06-30 13:50 UTC, Akshay0701 commented
not a big issue, will catch this today

2021-06-30 14:58 UTC, mikehardy commented on AnkiDroid/src/main/res/values/16-multimedia-editor.xml
> +    <string name="multimedia_editor_something_wrong_details">Error converting clipboard image to png: %s</string>
@Akshay0701 this is the last item, now that the string itself is specific, the string name should be specific, e.g.

```suggestion
    <string name="multimedia_editor_png_paste_error">Error converting clipboard image to png: %s</string>
```

2021-06-30 15:10 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +                UIUtils.showThemedToast(mContext, mContext.getResources().getString(R.string.multimedia_editor_something_wrong_details, e.getMessage()), true);
sorry - you cannot just commit my suggestion because now this string won't coincide :-) 
```suggestion
                UIUtils.showThemedToast(mContext, mContext.getResources().getString(R.string.multimedia_editor_png_paste_error, e.getMessage()), true);
```

With this one it might? And I may squash merge it

2021-06-30 15:11 UTC, mikehardy commented
All feedback addressed I believe, pending CI

2021-06-30 15:26 UTC, david-allison-1 approved these changes
Looks great. Thanks!

On my phone. Will merge when next on a PC.

EDIT: CI is still a problem. Likely on us

2021-06-30 15:49 UTC, mikehardy commented
Yeah, really weird. Emulator test was the normal-abnormal "process crashed", not related to this PR, I restarted. Unit tests were the GestureMapper, not sure what is going on there 

Pulled locally and chewed through it on API29/API30 emulators with `./gradlew clean jacocoTestReport` to simulator CI. Appears fine

2021-06-30 15:49 UTC, merged

2021-06-30 15:54 UTC, mikehardy commented
GestureMapper NoClassDefFound was affecting master as well, so I just invalidated the gradle cache in GitHub CI @david-allison-1 FYI https://github.com/ankidroid/Anki-Android/commit/33473d9408e0fccc7ba6d6277ce691d0a53c4cc3

Will do a translations sync to exercise it.