Implement onboarding for new users
ankidroid/Anki-Android pull request #9092
Opened 2021-06-09 18:52 UTC by ShridharGoel

## Purpose / Description
Implement onboarding for new users.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-06-09 22:29 UTC, david-allison-1 requested changes
Had a quick scan:

We should be using `.xml` drawables, not `.png` images

* AnkiDroid closes after the tutorial opens

```
2021-06-09 23:25:37.261 21086-21086/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 21086
    java.lang.RuntimeException: Unable to resume activity {com.ichi2.anki/com.ichi2.anki.DeckPicker}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4438)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
        at com.ichi2.anki.DeckPicker.showTutorialForDeck(DeckPicker.java:1007)
        at com.ichi2.anki.DeckPicker.startDeckAndCountsTutorial(DeckPicker.java:998)
        at com.ichi2.anki.DeckPicker.onResume(DeckPicker.java:992)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
        at android.app.Activity.performResume(Activity.java:8135)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4428)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7660) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

* The animation for the note editor is distracting, the fields aren't highlighted (no transparency, a user can't see what's being highlighted), and there's no visible prompt to remove the suggestion

I think overall this PR needs more screenshots, and there'll be a lot of discussion on the content of the onboarding. I think our explanations need to be much more targeted at where our users are having problems, rather than explaining obvious (to me) concepts

2021-06-09 22:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +                title = "Welcome to AnkiDroid!",
needs extracting to resources: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#adding-translations

2021-06-09 22:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        mSharedPreferences = getSharedPreferences("PERSISTENT_STATE_FILE", 0);
is there a reason that you're not using `AnkiDroidApp.getSharedPreferences`?

2021-06-09 22:34 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        mSharedPreferences = getSharedPreferences("PERSISTENT_STATE_FILE", 0);
I thought that `AnkiDroidApp.getSharedPreferences()` is only being used for settings related preferences which can be changed by the user.

2021-06-10 18:15 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +        mSharedPreferences.edit().putBoolean(ONBOARDING_FLAG, false).apply();
Same builder with likely same functionality used many times, can we extract this to one class, to reduced duplication of code?

2021-06-10 18:20 UTC, Akshay0701 commented
reason your unit tests fails is 

    Caused by:
            java.lang.AssertionError: 
            Expected: iterable over ["com.ichi2.anki.IntentHandler", "com.ichi2.anki.DeckPicker", "com.ichi2.anki.StudyOptionsActivity", "com.ichi2.anki.CardBrowser", "com.ichi2.anki.ModelBrowser", "com.ichi2.anki.ModelFieldEditor", "com.ichi2.anki.Reviewer", "com.ichi2.anki.VideoPlayer", "com.ichi2.anki.MyAccount", "com.ichi2.anki.Preferences", "com.ichi2.anki.DeckOptions", "com.ichi2.anki.FilteredDeckOptions", "com.ichi2.anki.Info", "com.ichi2.anki.NoteEditor", "com.ichi2.anki.Statistics", "com.ichi2.anki.Previewer", "com.ichi2.anki.CardTemplatePreviewer", "com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity", "com.ichi2.anki.multimediacard.activity.TranslationActivity", "com.ichi2.anki.multimediacard.activity.LoadPronounciationActivity", "com.ichi2.anki.CardTemplateEditor", "com.ichi2.anki.CardTemplateBrowserAppearanceEditor", "com.ichi2.anki.CardInfo", "com.ichi2.anki.IntroductionActivity"] in any order
                 but: No item matches: "com.ichi2.anki.IntroductionActivity" in ["com.ichi2.anki.CardTemplatePreviewer", "com.ichi2.anki.DeckPicker", "com.ichi2.anki.ModelFieldEditor", "com.ichi2.anki.Info", "com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity", "com.ichi2.anki.VideoPlayer", "com.ichi2.anki.FilteredDeckOptions", "com.ichi2.anki.IntentHandler", "com.ichi2.anki.multimediacard.activity.LoadPronounciationActivity", "com.ichi2.anki.CardBrowser", "com.ichi2.anki.MyAccount", "com.ichi2.anki.CardTemplateEditor", "com.ichi2.anki.StudyOptionsActivity", "com.ichi2.anki.CardInfo", "com.ichi2.anki.Reviewer", "com.ichi2.anki.Statistics", "com.ichi2.anki.Previewer", "com.ichi2.anki.multimediacard.activity.TranslationActivity", "com.ichi2.anki.NoteEditor", "com.ichi2.anki.Preferences", "com.ichi2.anki.DeckOptions", "com.ichi2.anki.ModelBrowser", "com.ichi2.anki.CardTemplateBrowserAppearanceEditor"]
                at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
                at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
                at com.ichi2.anki.ActivityStartupMetaTest.ensureAllActivitiesAreTested(ActivityStartupMetaTest.java:60)

you need to add intro screen to `ActivityList.java`

2021-06-12 16:50 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +        mSharedPreferences.edit().putBoolean(ONBOARDING_FLAG, false).apply();
Each time this Builder is being used, the parameters being passed to various methods are different. Also, which methods of the Builder are being called also varies in various cases.

2021-06-12 16:50 UTC, ShridharGoel commented
> you need to add intro screen to `ActivityList.java`

Thanks, I'll update it.

2021-06-12 16:54 UTC, ShridharGoel commented
> you need to add intro screen to `ActivityList.java`

Thanks, I had not checked the reason of the unit tests failure yet. I will update this.
Also, other things require fixes. I'll check.

2021-06-12 19:28 UTC, ShridharGoel commented
> our explanations need to be much more targeted at where our users are having problems

@david-allison-1 Can you give some examples?

2021-06-12 19:42 UTC, infinyte7 commented
You should create an issues for discussion and ideas. 

You may take some ideas from here about onboarding.
https://dribbble.com/tags/onboarding

The target audiences are new users. So, When user install the app, then app should tell them exactly what AnkiDroid will do for them in 3-5 onboarding images.

There are some of my ideas.
- What exactly AnkiDroid space repetition software is?
- Like what is v1 and v2 shceduler?
- Creating cloze decks in AnkiDroid
- Are there data is backup and sync?
...
...

The walkthrough of the app is good. But attach screenshots because it is UI/UX related PR.

2021-06-13 11:52 UTC, Arthur-Milchior reviewed
I'm effraied of the idea of saving one preference entry by boolean. That will be very big quite quickly. I believe we should use a `long` to save up to 64 boolean flags to indicate which onboarding screen has already been seen or not.


Thanks a lot for this first PR.

I think we may also have to discuss editing a commit instead of pushing new one

2021-06-13 11:52 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +        mSharedPreferences.edit().putBoolean(ONBOARDING_FLAG, false).apply();
In this case, I'm going to agree with @ShridharGoel. It's rare I don't ask for more factorization. But in this case, using a function would decrease readabliity.
Indeed, I prefer to read that `R.id.action_flag` is the target than just seing that it is the first argument of a function taking 7 arguments.

Furthermore, since all of those methods are really small, and have a clear name, the code remains easy to read.


At most, I'd suggest creating a function that take a builder and a preference name, call show on the builder and the the preference to False.

2021-06-13 14:07 UTC, Arthur-Milchior reviewed
drawable-v24 should be moved to drawable, as it's not related to v24

2021-06-13 15:11 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        mSharedPreferences = getSharedPreferences("PERSISTENT_STATE_FILE", 0);
If it's fine to use `AnkiDroidApp.getSharedPreferences()` in these cases, then I'll update it.

2021-06-13 15:49 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        mSharedPreferences = getSharedPreferences("PERSISTENT_STATE_FILE", 0);
If there is nothing defined about this, then I'll change the implementation to use `AnkiDroidApp.getSharedPreferences()`.

2021-06-13 18:09 UTC, david-allison-1 commented
Copying from Discord:

To me, for onboarding, the most important thing to me is refinement of the current design, rather than expanding to other screens: right from the get-go, we're going to lose a lot of users (via "skip"), and we should spend more time focusing on the best way to provide information in the shortest amount of time

I think the onboarding process is going to get a lot of bike shedding. I normally shy away from this, but it needs to be done here, along with user testing.

I think our main screen should have a few goals:

* Gain trust
* Non-technical vocabulary (using the word "spaced repetition" in the first sentence is far too complex)
* Explain that we control scheduling of the cards, cards don't "go missing" and we're better than manual scheduling.
* Avoid information overload
* Permission requests (storage - TBC, as it'll be removed)
* Do we want to sync from Anki Desktop, or start from scratch
* Possibly showcase advanced card types - I don't know what I want here or if it should be here, I almost want to show something ridiculous in a card (3D model) to show the possibilities
* What to do if the user has a question/a problem (link to future onboarding efforts/reddit/discord/forums)

If we do the last point right, then we can cut down the list significantly.

I don't think we need to showcase features, it slows down getting users into the app, we want people downloading/adding as soon as possible.

----

My main ideal on moving this forward would be more screenshots/animations as mentioned in the initial review.

2021-06-14 17:00 UTC, ShridharGoel commented
> You should create an issues for discussion and ideas.
> 
> You may take some ideas from here about onboarding.
> https://dribbble.com/tags/onboarding
> 
> The target audiences are new users. So, When user install the app, then app should tell them exactly what AnkiDroid will do for them in 3-5 onboarding images.
> 
> There are some of my ideas.
> 
> * What exactly AnkiDroid space repetition software is?
> * Like what is v1 and v2 shceduler?
> * Creating cloze decks in AnkiDroid
> * Are there backup and sync of data?
>   ...
>   ...
> 
> The walkthrough of the app is good. But attach screenshots because it is UI/UX related PR.

@infinyte7 Thanks for the suggestions. Do you also have a suggestion about where should we show such things which might be a little advanced for the new user? For example, should we show the tip about `Close cards` when the user selects that option in the note editor for the first time or should we show it even when the user has not selected that option, just to inform the users that such an option exists?

2021-06-15 18:18 UTC, infinyte7 commented
There are two parts
- Onboarding
- Walkthrough

Onboarding can be used show the important features that does not needs demo to show. Like the feature `sync of note data across devices`. So, written text may explain and help new users to understand the feature.

Walkthrough of advanced features  like `creating cloze deletion notes` or any other examples.

2021-06-16 00:53 UTC, david-allison-1 requested changes
Aside from working on the content, main issue: the field highlighting on "add note" is a white block if you're in night mode

2021-06-16 00:55 UTC, david-allison-1 commented
I think the main concepts will be again/hard/good/easy/graduation/lapses/"deck completed: where are my cards"

2021-06-18 05:37 UTC, Arthur-Milchior reviewed
I think it would be nice to wait for commands to be available before showing them.
That is:
* wait until there is actually a card to review to let the user know they should click on a deck name
* Wait until there is an action to undo to present the arrow

Also:
"Enter the question part of card in front" (instead of saying "the front part")

The trouble of course being that "front" and "back" has only meaning on paper card. As we follow upstream, we can't really change it. Even if I'd argue that Anki should change it too in the basic note type.

I'd even argue that it would be nice to have similar description for "Basic and reverse" and for all basic note type (that's not trivial at all to detect, but can probably be done using just note type name as a heuristic)

2021-06-18 05:37 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +    const val ONBOARDING = "Onboarding"
I think it would be nice to have one entry by activity. One for reviewer, one for deck picker, etc...
If we store 10 longs instead of one, it's not a trouble, and we will then be able to have more than 64 onboarding information. While I know that 64 onboarding slides seems a lot, I actually think that it is not that much if we consider:
* the number of buttons
* we may want to deprecate some slide one day if a feature change too much
* we may add new features
* some slides won't be shown immediately but only after some time

2021-06-19 19:30 UTC, Arthur-Milchior reviewed
Thanks a lot. I sincerely appreciate how nicely the code evolves with each commits.
Were there any difficulties? Do you know what took you time? I understand it's not easy, but I was hoping to see more regular evolution of the PR, so that I can give feedback quickly and end faster the code review.
I've not yet concentrated on the actual content of the onboarding. You know it by know, I care a lot about having a nice library first

2021-06-19 19:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +class IntroductionActivity : AppIntro() {
Can you add some javadoc (KotlinDoc?) to indicate what it means. I find "IntroductionActivity" not clear by itself. If in two year someone read this page without knowing the context, they should be able to figure out that "introduction" here is "onboarding on first use of the app" and not "an activity that introduce a new card" or "introducing an activity in the activity queue"

2021-06-19 19:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedCirclePromptBackground.java
> + * Prompt background implementation that darkens behind the circle background.
English is not my mother tongue, so I beg your pardon for the followin remark, but I don't find it quite clear.

Maybe 

> Create a circle to emphasizes a part of the app.
> Darkens the entire screen, appart from this circle to ensure that the user focus on the circle itself

2021-06-19 19:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedCirclePromptBackground.java
> +        mDimPaint = new Paint();
There is no need to call super? Can you confirm you checked that the default constructor of CirclePromptBackground is what you want?

2021-06-19 19:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedCirclePromptBackground.java
> +package com.ichi2.utils;
I think com.ichi2.ui should be a better package. `utils` seems to have been mostly libraries and this is really ui related

2021-06-19 19:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedRectanglePromptBackground.java
> +package com.ichi2.utils;
Unless I'm missing something, everything seems to be duplicated with DimmedCirclePromptBackground. That's really a risk for error laters, if we think about correcting something in one class and not the other.

Unless you really need to extend the RectanglePromptBackground, you should avoid it. Instead, you should delegate to a `PromptBackground`.
That is, your constructor takes as parameter either a CirclePromptBackground or a RectanglePromptBackground, saves it as a member "mPromptBackground`,  and instead of using `super` you use `mPromptBackground` to apply a method to it.

You can also create two static functions that calls your constructor with a circle and a rectangle, so that you don't have to create them yourselves in the remaining of the code

2021-06-19 19:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            OnboardingUtils.INSTANCE.setAsVisited(DeckPickerOnboardingEnum.INTRODUCTION_SLIDES.ordinal(), this, DECK_PICKER_ONBOARDING);
You might want to wait until the end of the introduction to mark this as visited. So if the app is closed, introduction open again next time

2021-06-19 19:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            OnboardingUtils.INSTANCE.setAsVisited(DeckPickerOnboardingEnum.INTRODUCTION_SLIDES.ordinal(), this, DECK_PICKER_ONBOARDING);
is `INSTANCE` due to the interaction of Kotlin and JAVA. It sems that adding `OnboardingUtils.INSTANCE` has little meaning here, so it's nice if it can be avoided.

Also, that makes me wonder whether we should have a small structure that represents the pair `INTRODUCTION_SLIDES, DECK_PICKER_ONBOARDING`. This way, it avoid repeating it multiple time.

If the two methods took instance of an enum instead of an int, we could remove the `ordinal()` here and make the code smaller

2021-06-19 19:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            OnboardingUtils.INSTANCE.setAsVisited(DeckPickerOnboardingEnum.INTRODUCTION_SLIDES.ordinal(), this, DECK_PICKER_ONBOARDING);
I thought we would get an index by slide, and not one for the whole slide deck.
The reason is that, if one day, we decide to add a new feature worth mentionning to the users, we can open a deck with this feature only

2021-06-19 19:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        new MaterialTapTargetPrompt.Builder(this)
Any reason for not having a method that takes a builder, an ordinal and a set, and, if the pair is not already visited, then show the builder content and mark the pair as visited?
I have been making this kind of suggestion twice already, and I still not see it in the PR I review.
It's entirely fine if you disagree. I may lack some context. But I fear I've not seen answer explaining why you decided to disagree

2021-06-19 19:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +    fun checkIfNotAlreadyVisited(index: Int, context: Context, prefKey: String): Boolean {
Do you need to return the Boolean object? Or is there no difference difference between `Boolean` and `boolean` in Kotlin?

2021-06-19 19:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +
Actually, what could even be done is  (using Java syntax, I don't know Kotlin)

```java
boolean <Preference extends Union> checkIfNotAlreadyVisited(Preference index, Context context, Class<Preference> clazz) {
  return  (AnkiDroidApp.getSharedPrefs(context).getLong(clazz.toString(), 0) and (1L shl index.ordinal())) == 0L;
}
```
This would ensure the class name is used as entry. It would also ensure that the index comes from the very enum we are considering. This would decrease considerably the risk of error and simplify reviewing more commits

2021-06-19 19:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowserOnboardingEnum.kt
> +enum class CardBrowserOnboardingEnum {
Is it standard in Kotlin to move enum in their own class? I'd have considered that such an enum could be in CardBrowser. And similarly for other enum of onboarding

2021-06-19 19:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedCirclePromptBackground.java
> +
Please add a header. EIther with your copyright if you wrote it, or with the source if you were inspired by other (I'm surprised that you need to create this class yourself. I would have assumed that it is standard to focus this way. Can you please add in javadoc the difference between DimmedCirciclePromptBackground and what already exists. I.e. CirclePromptBackground and maybe other classes you found while exploring your options)

2021-06-19 20:04 UTC, ShridharGoel commented
> Were there any difficulties? Do you know what took you time? I understand it's not easy, but I was hoping to see more regular evolution of the PR, so that I can give feedback quickly and end faster the code review.

I was mainly waiting for feedback. I had done the required changes in the starting of the week and mentioned on Discord for reviews. Recieved feedback on Friday and then updated with things like there use of enum classes, having separate preferences for each screen, use of BitSet etc.
Apart from that I worked on the onboarding for Card Browser. Rest of the time was just waiting for feedback.

2021-06-19 20:06 UTC, ShridharGoel commented
> I still have a preference for you to use enums.

Enums are already being used. There was difficulty in passing an enum class directly as parameter so I used the `ordinal`. I'll check how enum classes can be passed directly.

2021-06-19 20:07 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        new MaterialTapTargetPrompt.Builder(this)
Sorry, missed this change. I will update it.

2021-06-19 20:08 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            OnboardingUtils.INSTANCE.setAsVisited(DeckPickerOnboardingEnum.INTRODUCTION_SLIDES.ordinal(), this, DECK_PICKER_ONBOARDING);
> is INSTANCE due to the interaction of Kotlin and JAVA

Yes.

2021-06-19 20:10 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedCirclePromptBackground.java
> +
DimmedCirclePromptBackground and DimmedRectanglePromptBackground have actually been taken from an example mentioned in the library documentation. So what should be done in this case?

2021-06-19 20:11 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +    private fun insertSlide(resources: Triple<Int, Int, Int>) {
This is possible by using a data class. I'll update it.

2021-06-20 04:10 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        mSharedPreferences = getSharedPreferences("PERSISTENT_STATE_FILE", 0);
Hmm - we've always just used a single preferences file (the default one) as far as I know. I believe there is one secondary one related to some module we include (dim memory - I don't think it's ACRA, I think even those keys are in the default one). Anyway, I don't see a reason to split them up, not even with what I know of performance in the preferences system on android, it will load them all up and have them cached anyway, but it's not high traffic or anything so no worries about file write contention on prefs.apply() etc. Just use the default I think

2021-06-20 04:31 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +        return (AnkiDroidApp.getSharedPrefs(context).getLong(prefKey, 0) and (1L shl index)) == 0L
@Arthur-Milchior are we really using a bitset to flag whether onboarding has shown something or not? Isn't that a fixed size thing? How would that map to an API where future features could implement a "walkthrough" hooking into this system and this system would know whether it was shown or not? That's a design I I mentioned recently in Discord, idea taken from VSCode https://code.visualstudio.com/updates/v1_57#_new-getting-started-experience 

Here's a great link to the VSCode team's experience with users when they *just* did the same thing we are doing: https://github.com/microsoft/vscode/issues/106717#issuecomment-790053982

Key findings:
- users skip because they're really focused on a specific task
- users then are maybe interested later but can't get back to the "getting started" content

Here's how they define a "walkthrough" contributed to the "getting started" content https://github.com/microsoft/vscode/issues/116414#issuecomment-783543863

2021-06-20 04:33 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedCirclePromptBackground.java
> +
I assume the library documentation has a license and/or copyright? If it's compatible we should include it, if not, I'm not sure what to do except re-implement ? That seems silly though, hopefully it's compatible

2021-06-20 15:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        mSharedPreferences = getSharedPreferences("PERSISTENT_STATE_FILE", 0);
> . I believe there is one secondary one related to some module we include

I think the other one was used by `CardBrowser`

2021-06-20 19:56 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +    fun checkIfNotAlreadyVisited(index: Int, context: Context, prefKey: String): Boolean {
There is no `boolean` in Kotlin.

2021-06-21 12:32 UTC, david-allison-1 reviewed
I'm focusing on the in-context hints with this one.

Design: To discuss with other mentors:

I feel we want to move away from having onboarding related code in the activity itself, and we should extract this to a separate concern

```java
private Onboarding.AbstractFlashcardViewer mOnboarding = new Onboarding.AbstractFlashcardViewer(this);

...

mOnboarding.onCreate()
mOnboarding.onQuestionShown()
mOnboarding.onAnswerShown()

```

Once we're inside the concern, it becomes more easy to:

* Exit early, if a method doesn't need to execute, as there's less unrelated context
* Define an order of transitions and move between them, possibly via data classes

2021-06-21 12:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                    .setPromptFocal(new RectanglePromptFocal());
Can you create a new builder which includes `.setPromptBackground(new DimmedPromptBackground(new RectanglePromptBackground()))` and `.setPromptFocal(new RectanglePromptFocal());`

This will reduce the amount of copy/pasted text

2021-06-21 12:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +                });
add a method: `setDismissedListener` which calls through

2021-06-21 12:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                .setFocalColour(ContextCompat.getColor(this, R.color.material_light_blue_500))
Likewise, extract to a new builder to reduce code duplication

2021-06-21 12:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +    private static final String NOTE_EDITOR_ONBOARDING = "NoteEditorOnboarding";
unused

2021-06-21 12:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +    private static final String CARD_BROWSER_ONBOARDING = "CardBrowserOnboarding";
unused

2021-06-21 12:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +        return (AnkiDroidApp.getSharedPrefs(context).getLong(enum.name, 0) and (1L shl enum.ordinal)) == 0L
Don't use enum ordinals, if someone removes an element (or reorders the elements into alphabetical order), then it corrupts the preference

2021-06-21 12:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +    public void showTutorialForFlag() {
agreed

2021-06-21 19:28 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +        return (AnkiDroidApp.getSharedPrefs(context).getLong(enum.name, 0) and (1L shl enum.ordinal)) == 0L
We can create a method inside the enum which would be giving specific values for specific entries in the enum. But, since we are just passing a generic enum as the parameter, how can we access methods from the enums without type casting the `enum` parameter?

2021-06-21 22:02 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        OnboardingUtils.INSTANCE.showTutorialAndMarkVisited(tutorialBuilder, NoteEditorOnboardingEnum.FRONT_BACK, this, true, true, null);
The params make this less readable, use a subclassed builder/factory method instead

2021-06-21 22:04 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +        return (AnkiDroidApp.getSharedPrefs(context).getLong(enum.name, 0) and (1L shl enum.ordinal)) == 0L
I don't know how you'd do it in Kotlin, In Java: Add in a constuctor to the enum accepting an integer, and use a fixed value.

2021-06-22 11:44 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +        return (AnkiDroidApp.getSharedPrefs(context).getLong(enum.name, 0) and (1L shl enum.ordinal)) == 0L
Yes, that's the way but as I mentioned in the previous comment, we are passing a generic enum instead of using the exact enum classes. So in that case, how can we fetch the integer value?

2021-06-22 19:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +        return (AnkiDroidApp.getSharedPrefs(context).getLong(enum.name, 0) and (1L shl enum.ordinal)) == 0L
Enums seem to be able to implement interfaces in Java

2021-06-22 20:04 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +        return (AnkiDroidApp.getSharedPrefs(context).getLong(enum.name, 0) and (1L shl enum.ordinal)) == 0L
Thanks for suggesting this approach. Updated.

2021-06-22 20:04 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +        OnboardingUtils.INSTANCE.showTutorialAndMarkVisited(tutorialBuilder, NoteEditorOnboardingEnum.FRONT_BACK, this, true, true, null);
Updated with better implementation.

2021-06-22 21:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            OnboardingUtils.INSTANCE.setOnboardingEnumValueListener(this);
I don't understand what this is doing. It feels incorrect

2021-06-22 21:33 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            OnboardingUtils.INSTANCE.setOnboardingEnumValueListener(this);
Okay, it feels that you want the constraint on `checkIfNotAlreadyVisited` to be both an enum, and inheriting from `OnboardingEnumValue` (or just inheriting from the interface)

2021-06-23 09:42 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            OnboardingUtils.INSTANCE.setOnboardingEnumValueListener(this);
Actually using an interface wasn't required. Updated the implementation to take fixed integer value as parameter in the functions in `OnboardingUtils`.

2021-06-23 13:35 UTC, mikehardy commented
Not sure what happened with unit tests - did not look like a normal flake - I restarted it to verify

2021-06-24 23:51 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CustomMaterialTapTargetPromptBuilder.kt
> +    fun <T : Enum<T>> showTutorialAndMarkVisited(enum: Enum<T>, enumValue: Int) {
can you add the generic constraint to include the interface as well

It's not ideal to pass in `object` and `object.property` to a method, when there's no chance that `object.property` won't belong to `object`

2021-06-24 23:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CustomMaterialTapTargetPromptBuilder.kt
> +            focalColour = ContextCompat.getColor(mActivity, focalColourRes)
Is this a noop if `null` is supplied?

2021-06-26 03:37 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +object OnboardingUtils {
Given that there's no state, this would be better as a class containing `static` methods, rather than as a singleton

2021-06-26 03:37 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +    fun <T : Enum<T>> checkIfNotAlreadyVisited(enum: Enum<T>, context: Context, enumValue: Int): Boolean {
You should be able to apply the same refactoring here to remove the `enumValue` parameter

2021-06-26 03:37 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +    fun <T : Enum<T>> setAsVisited(enum: Enum<T>, context: Context, enumValue: Int) {
ditto

2021-06-26 03:37 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +                .setDismissedListener(this::showTutorialForUndo)
Is there a way that you can accept a function returning void here? `Unit` makes for messy code

2021-06-26 03:37 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="cards_not_deleted">Your cards have not been deleted</string>
Copying from Discord

That's far too scary and there's too much text. 

I read that and my heart sank (and I know what AnkiDroid does)

Very few people will read that amount of text

-----

For UX on the dialog:

* Consider making it friendly with a positive image (unsure how this goes with Material Design)

----

As for copy: something along the lines of

"You're done for today"

You have a strong memory of all your cards.
OR
AnkiDroid cannot further strengthen your memory of cards today.

(something about "come back tomorrow, we'll show new/review cards")

buttons:
* [learn more cards -> burnout warning -> contextual tutorial on how to do so]
* [browse cards] 
* [close]


----

I do wonder if we need this now https://github.com/ankidroid/Anki-Android/pull/9143 has gone in

2021-06-26 03:37 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        if (mRecyclerViewLayoutManager.getChildAt(0) == null) return;
What does this do? Might need extracting to a method

2021-06-26 03:37 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        new Handler().postDelayed(() -> cardBrowserTutorial.setVisibility(View.GONE), 4000);
can you extract `new Handler().postDelayed(` into an onboarding related class, if we wanted to change the implementation, we'd need to do it everywhere

2021-06-26 03:37 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +    public void showTutorialForFlag() {
This is still pending, 

@Arthur-Milchior this might need elaboration on the design

2021-06-26 04:25 UTC, david-allison-1 commented
Just running this: the onboarding for flags doesn't explain "why" you'd want to flag a card, which I feel is where a lot of the confusion stems from

I don't think we want to promote flags as a "first feature" of the app. It encourages information overload

I feel something like "check pronunciation" when it's opened, to inform the user that this is just checking, and that media should be inserted by the note editor. (But that might be better fixed by adding the button to the check pronunciation window)

2021-06-26 13:59 UTC, david-allison-1 commented
The deck name isn't visible on the Onboarding if you're in Dark mode

2021-06-26 15:34 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +    public void showTutorialForFlag() {
@david-allison-1 We are already using a custom builder now, is anything else also required? I had created a method earlier, but during review you had mentioned that the method decreases the readability and hence we should shift that code to a custom builder class.

2021-06-26 15:34 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +                .setDismissedListener(this::showTutorialForUndo)
`Unit` is required until the code is migrated to Kotlin.

2021-06-26 15:34 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/CustomMaterialTapTargetPromptBuilder.kt
> +            focalColour = ContextCompat.getColor(mActivity, focalColourRes)
Yes, focal colour will not be set explicitly in case of null.

2021-06-26 15:34 UTC, ShridharGoel commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="cards_not_deleted">Your cards have not been deleted</string>
Since, this is not required now so I'll remove it.

2021-06-26 15:34 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        if (mRecyclerViewLayoutManager.getChildAt(0) == null) return;
This checks if the first RecyclerView item is null.

2021-06-26 15:46 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CustomMaterialTapTargetPromptBuilder.kt
> +            focalColour = ContextCompat.getColor(mActivity, focalColourRes)
Should we make it non-null then?

2021-06-26 15:46 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        if (mRecyclerViewLayoutManager.getChildAt(0) == null) return;
Could you extract it to a method `hasDecks()` maybe? 

We should explain the "why" to the next developer, typically just the method name can do this

2021-06-26 15:46 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +                .setDismissedListener(this::showTutorialForUndo)
Had a quick google, strangely this doesn't seem easily solvable

2021-06-26 16:28 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CustomMaterialTapTargetPromptBuilder.kt
> +class CustomMaterialTapTargetPromptBuilder(val mActivity: Activity) : MaterialTapTargetPrompt.Builder(mActivity) {
I assume the reason you inherited all methods and ensured they return `this` is to allow to have `CustomMaterialTapTargetPromptBuilder` as return type instead of a `MaterialTapTargetPrompt`. If I'm right, then there is an easier solution. If you use the new methods, i.e. `setFocalColourResource`, `setDismissedListener` etc... first, and if you override `show` to state that it also save the fact that the screen is visited then it's not a problem if all other setters return `MaterialTapTargetPrompt.Builder`.

2021-06-26 16:28 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CustomMaterialTapTargetPromptBuilder.kt
> +    fun setDismissedListener(tutorialFunction: () -> Unit): CustomMaterialTapTargetPromptBuilder {
You probably want `setDismissedListener` to accept a [`Runnable`](https://docs.oracle.com/javase/7/docs/api/java/lang/Runnable.html). This way, you can use void instead of having to deal with units in java

2021-06-26 16:28 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +                .setDismissedListener(this::showTutorialForUndo)
I also put a solution in the `CustomMaterialTapTargetPromptBuilder`'s comment

2021-06-26 16:28 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +    public void showTutorialForFlag() {
This is clearly not what I had in mind. I guess that using inheritance instead of delegation works. I fear it might not work anymore if we want to use another kind of builder in the future however

2021-06-26 16:28 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        if (OnboardingUtils.INSTANCE.checkIfNotAlreadyVisited(CardBrowserOnboardingEnum.DECK_CHANGER, this)) {
I would like other mentors opinion. I believe for clarity, it would be nicer if the test was done in the methods themselves.
E.g. `showTutorialForDeckChanger` would check if `DECK_CHANGER` is set, if so return immediately, otherwise actually show the tutorial. Maybe the name should be changed to `showTutorialForDeckChangerIfNew`

2021-06-26 16:28 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        AbstractFlashcardViewerOnboardingEnum(int value) {
What is the point of `mValue`. It seems redundant with `ordinal()`

2021-06-26 16:28 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +    fun <T : Enum<T>> checkIfNotAlreadyVisited(enum: Enum<T>, context: Context, enumValue: Int): Boolean {
Actually, it was done correctly before the commit "Use fixed integer value instead of enum ordinal". I don't understand the point of this commit, can you please at least explain it?

2021-06-26 16:34 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +    fun <T : Enum<T>> checkIfNotAlreadyVisited(enum: Enum<T>, context: Context, enumValue: Int): Boolean {
It was suggested by @david-allison-1 : https://github.com/ankidroid/Anki-Android/pull/9092#discussion_r655332947

2021-06-26 16:40 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +        return (AnkiDroidApp.getSharedPrefs(context).getLong(enum.name, 0) and (1L shl enum.ordinal)) == 0L
In this card, I was suggesting ordinals. I was also indicating that we should ensure that we never reorder or delete any element appart during alphas maybe. Ensuring that between each successive main version, elements are only added. This keep the code quite simpler, is not hard to enforce (should be indicated in a comment for safety). There is almost the same risk with current method of adding an explicit number and just add a lot of code duplication

2021-06-26 17:01 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        AbstractFlashcardViewerOnboardingEnum(int value) {
You don't want to use `.ordinal()` for an enum in persistence mechanisms unless the ordinal is explicitly defined.

Removing, or reordering an enum value while using `.ordinal()` causes all of the constants to map to the incorrect values. I've seen this have really nasty effects in systems before.

2021-06-26 17:09 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        if (OnboardingUtils.INSTANCE.checkIfNotAlreadyVisited(CardBrowserOnboardingEnum.DECK_CHANGER, this)) {
For clarity:

Have a `Onboarding.CardBrowser` class & pass in events/call methods on it, and have this class take the responsibility of the action to take

The code here would then become `mOnboarding.onCreate()` or `mOnboarding.displayFor(CardBrowser.ON_CREATE)`

2021-06-26 17:10 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CustomMaterialTapTargetPromptBuilder.kt
> +        promptBackground = DimmedPromptBackground(CirclePromptBackground())
https://github.com/sjwall/MaterialTapTargetPrompt/blob/099d7519c33be4b6d0dad2179b61fc1c6b97d602/library/src/main/java/uk/co/samuelwall/materialtaptargetprompt/extras/PromptOptions.java#L1439

Kotlin converts `obj.setX` and `obj.getX` into Properties, accessed as `obj.X = value` or `val v = Obj.x`

2021-06-27 19:19 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/CustomMaterialTapTargetPromptBuilder.kt
> +    fun <T> showTutorialAndMarkVisited(enum: T) where T : Enum<T>, T : OnboardingEnumInterface {
`enum` is too vague. `screenIdentifier` may be more clear. And clearly require a javadoc

2021-06-28 16:16 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +    public void showTutorialForFlag() {
@Arthur-Milchior In that case, can you tell what is expected here?

2021-06-28 16:17 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/CustomMaterialTapTargetPromptBuilder.kt
> +    fun setDismissedListener(tutorialFunction: () -> Unit): CustomMaterialTapTargetPromptBuilder {
Since onboarding related methods have now been moved to a Kotlin file, this issue of having to return `Unit.INSTANCE` is not longer present.

2021-06-28 16:18 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private Unit startDeckAndCountsTutorial() {
It was required to pass this as a function from a Java file to a Kotlin based function.
But now, since this is in a Kotlin file, returning `Unit` is no longer required.

2021-06-29 12:54 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CustomMaterialTapTargetPromptBuilder.kt
> +        promptBackground = DimmedPromptBackground(CirclePromptBackground())
I'll mark this as resolved. Nothing to do in my mind

2021-06-29 13:04 UTC, david-allison-1 reviewed
I love the changes, this is so clean now!

Only nits/design in the review

Once changes are made, I'd be happy to accept this if it has a feature flag to disable the onboarding while we discuss the content (maybe along with a debug preference to enable the onboarding so we can try it out).

2021-06-29 13:04 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +        fun <T> setVisited(featureIdentifier: T, context: Context) where T : Enum<T>, T : OnboardingFlag {
Loads of spacing changes here which make it harder to review

2021-06-29 13:04 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
nit: spacing change

2021-06-29 13:04 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +    class Reviewer(private val mActivityContext: Activity) {
Might want to extract `ReviewerOnboardingEnum` and similar here to keep `Reviewer` almost fully clean of onboarding work

2021-06-29 13:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +        return (AnkiDroidApp.getSharedPrefs(context).getLong(enum.name, 0) and (1L shl enum.ordinal)) == 0L
I strongly disagree. I've been stung by this in the past, the javadocs imply that we shouldn't be using `.ordinal()`. 

People refactor without thinking about the surrounding context. A bug which can be introduced by a mass refactoring, and causes subtle data corruption with no defined recovery procedure isn't anywhere near the problem of some code duplication.

2021-06-29 13:55 UTC, mikehardy commented
> feature flag to disable the onboarding while we discuss the content (maybe along with a debug preference to enable the onboarding so we can try it out).

That specifically means what? (we haven't really done a feature flag before, the scoped storage migration one is hard-coded in a constant!)

- shared preferences check for "showOnboarding" (or something) where the default return value is false?
- settings -> advanced button where you can toggle this to true? in Debug only? I think in all builds, just with a warning it's new and in progress
- settings -> advanced button where you can reset all the onboarding state so you can go through it again maybe? This will be a useful feature in general - lots of onboarding areas in apps have a reset button so people that were impatient but later wanted to see the information may do so

2021-06-30 16:13 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +        fun <T> setVisited(featureIdentifier: T, context: Context) where T : Enum<T>, T : OnboardingFlag {
These are not extra changes, they are required since the code has been put inside `companion object` as it was asked in a previous review to use a class here instead of creating a Singleton.

2021-07-01 18:51 UTC, david-allison-1 reviewed
Maybe 1 or 2 rounds to go

2021-07-01 18:51 UTC, david-allison-1 commented on .idea/codeStyles/Project.xml
> -          <package name="io.ktor" alias="false" withSubpackages="true" />
Can this be reverted?

2021-07-01 18:51 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    public static boolean hasDecks() {
Keep this as an instance method

2021-07-01 18:51 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +        fun <T> isVisited(featureIdentifier: T, context: Context, featureConstant: String): Boolean where T : Enum<T>, T : OnboardingFlag {
You can include `featureConstant` in the definition of `OnboardingFlag`

2021-07-01 18:51 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="show_onboarding_desc">Display feature tutorial to learn more about the app</string>
We don't need these as translatable strings if they're Debug only. Hardcode or use `constants/strings.xml` (see how other preferences did it).

2021-07-01 18:51 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/19-onboarding.xml
> +<?xml version="1.0" encoding="utf-8"?>
This needs to be added to the translation sync script(s) in /tools

2021-07-02 15:15 UTC, david-allison-1 commented
```
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/CustomMaterialTapTargetPromptBuilder.kt: (86, 67): Too many arguments for public final fun <T : Enum<T>> setVisited(featureIdentifier: T, context: Context): Unit where T : OnboardingFlag defined in com.ichi2.anki.OnboardingUtils.Companion
```

2021-07-02 16:09 UTC, david-allison-1 approved these changes
LGTM, one nit, thanks!!

2021-07-02 16:09 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +            CustomMaterialTapTargetPromptBuilder(mActivityContext, DeckPickerOnboardingEnum.DECK_NAME, DECK_PICKER_ONBOARDING)
Could add a custom builder which takes `DeckPickerOnboardingEnum` and uses `getFeatureConstant()` to reduce code here

2021-07-02 17:08 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +            CustomMaterialTapTargetPromptBuilder(mActivityContext, DeckPickerOnboardingEnum.DECK_NAME, DECK_PICKER_ONBOARDING)
@david-allison-1 Actually `featureConstant` wasn't required here. Removed it.

2021-07-02 19:08 UTC, mikehardy commented
@ShridharGoel looks like there is some mandatory lint to fix:

```

Execution failed for task ':AnkiDroid:lintPlayRelease'.
> Lint found errors in the project; aborting build.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  The first 3 errors (out of 4) were:
  
  /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/CustomMaterialTapTargetPromptBuilder.kt: Error: Field should be named: 'COMPANION' [ConstantFieldName]
  /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt: Error: Field should be named: 'COMPANION' [ConstantFieldName]
  /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt: Error: Field should be named: 'COMPANION' [ConstantFieldName]
```

I've got this queued for review

2021-07-02 19:13 UTC, ShridharGoel commented
@mikehardy Yes, I have fixed it.

2021-07-02 19:14 UTC, ShridharGoel commented
```
Error: Response status code does not indicate success: 500 (Internal Server Error).
```

Test needs to be restarted.

2021-07-03 00:54 UTC, Arthur-Milchior reviewed
Thanks for the change. I have far more time this week-end than last week-end. I'd suggest we do another pair programming so that, at least, we clean this PR.

I do like the result of  "Refactor onboarding related code" but honestly, it's quite hard to read, because you move a lot of code and it is not clear whether there is anything modified by accident.
Since the ultimate goal is to have the onboarding code in a separate file, I'd prefer if you can put the code you write directly in this separate file. It will make history and reviewing quite easier.

2021-07-03 00:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private Unit startDeckAndCountsTutorial() {
In another comment you mentionned that those functions are now in kotlin. Does it require to be in java first or can you put it in kotlin directly so that it avoid adding code to delete it soon after

2021-07-03 00:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/19-onboarding.xml
> +<?xml version="1.0" encoding="utf-8"?>
oh right. Ideally in the same commit than the one where the file is created

2021-07-03 00:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +    public void showTutorialForFlag() {
Oh, what I was trying to state is that this implementation is right. I believe that if needed, it can be reworked to be more general later, but right now it's quite good enough

2021-07-03 00:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingEnumInterface.kt
> +interface OnboardingEnumInterface {
Could you please make first a commit that add this interface, and then rewrite the intermediate commit so that the enumeration directly implements it? It will avoid to change the same code multiple time in a same PR and make reviewing the last commits quite easier

2021-07-03 00:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedPromptBackground.kt
> +// noinspection MissingCopyrightHeader
Please remove this line. We want inspection. It was only useful on legacy code

2021-07-03 00:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedPromptBackground.kt
> +/****************************************************************************************
Please add it in the same commit where you created the file.

2021-07-03 00:54 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedPromptBackground.kt
> +*   This has been taken from the documentation of the MaterialTapTargetPrompt library.   *
What is "this"? You may want to take "the content of this file" or "the documentation" or somethnig else.

It's even more strange that it seems you are reusing PrmoptBackground (and not Shapes as you linked here) and not copying the code of the linked file

2021-07-03 16:20 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedPromptBackground.kt
> +        mDimBounds[0f, 0f, metrics.widthPixels.toFloat()] = (metrics.heightPixels * 2).toFloat()
It was auto-converted from Java. Reference to read about how this operator works: https://kotlinlang.org/docs/operator-overloading.html#indexed-access-operator
Changed it to use `set()` method now, so that it becomes easy to understand.

Added the reason of using twice the height. Some area at the bottom of the screen was not being dimmed, so had to increase the width.

2021-07-03 16:48 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedPromptBackground.kt
> +class DimmedPromptBackground(val mPromptBackground: PromptBackground) : PromptBackground() {
Both are required since methods of the base class are abstract. So cannot use `super` to call them.

2021-07-03 16:56 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedPromptBackground.kt
> +class DimmedPromptBackground(val mPromptBackground: PromptBackground) : PromptBackground() {
Methods of the base class which are used here are abstract. Hence `super` cannot be used, so taking an instance of `PromptBackground` as argument would be required.

2021-07-03 16:56 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedPromptBackground.kt
> +*   This has been taken from the documentation of the MaterialTapTargetPrompt library.   *
The link is correct. It contains the relevant code after the 'Shapes' section.

2021-07-03 16:57 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedPromptBackground.kt
> +/****************************************************************************************
`MissingCopyrightHeader` works only with GPLv3 license currently.

2021-07-03 16:57 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedPromptBackground.kt
> +// noinspection MissingCopyrightHeader
`MissingCopyrightHeader` works only with GPLv3 license currently.

2021-07-04 22:33 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingFlag.kt
> +    fun getFeatureConstant(): String
Can you also add a javadoc explaining what is expected. I suppose that the string should have the same value as the enum value

2021-07-04 22:33 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        Onboarding.DeckPicker onboarding = new Onboarding.DeckPicker(this, mRecyclerViewLayoutManager);
Any reason to introduce a variable here?

2021-07-04 22:33 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +        fun handlerPost(function: () -> Unit) {
Please, by default, add javadoc everywhere. I've little idea why you introduce this method. and the commit message don't help. 
In general I'm strongly in favor of separating the commits which add a features, in this case handling "post" (whatever it is) to the actual content using it. In this case, I assume, reviewer and abstract flasch card viewer.

The default handler constructor is deprecated and risk loosing call, according to https://developer.android.com/reference/android/os/Handler#Handler() , so that's not a good implementation unless there is a really good reason.

I would like to read the reason you decided to handle runner like this, because we have not used it in ankidroid as far as I know. I don't know what is the goal here, but I doubt we can be certain we will always have the things in the order we want

2021-07-04 22:33 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +    class AbstractFlashcardViewer(private val mActivityContext: Activity) {
Is it a good idea to have the same class name than the java class it is related too? I fear it will make code harder to review later, if I see a variable of type `AbstractFlashcardViewer` and do not know which type the code uses

2021-07-04 22:33 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +            Handler().postDelayed(function, time)
Same remark about Handler than below. Also, seems strange to use a different handler each time

2021-07-04 22:42 UTC, Arthur-Milchior commented
Unless I'm wrong, the video is not up to date anymore. In particular it contains screen that are actually in #9130 
Would you mind creating two videos, so that I can't recall quickly which pr correspond to which feature

2021-07-08 11:43 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +        fun handlerPost(function: () -> Unit) {
I have updated the implementation. Used https://developer.android.com/reference/android/os/Handler#Handler(android.os.Looper) which is not deprecated.

Handler is required here to show feature prompt on menu items. Reference: https://github.com/sjwall/MaterialTapTargetPrompt/issues/73#issuecomment-320681655

2021-07-08 11:47 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +    class AbstractFlashcardViewer(private val mActivityContext: Activity) {
This is inside the `Onboarding` class which means that it will be represented as `Onboarding.AbstractFlashcardViewer`. Also, the constructor is different in these classes. So that should be sufficient to differentiate between these classes, right?

2021-07-08 11:49 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +            Handler().postDelayed(function, time)
> seems strange to use a different handler each time

Can you explain what does this mean? Do you mean using both `postDelayed()` and `post()`?

2021-07-08 11:49 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        Onboarding.DeckPicker onboarding = new Onboarding.DeckPicker(this, mRecyclerViewLayoutManager);
No, updated.

2021-07-08 11:49 UTC, ShridharGoel commented
@Arthur-Milchior The required changes have been done.

2021-07-08 16:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +        fun handlerPost(function: () -> Unit) {
Could you add a reference to the comment in the source code, it'll get lost here

2021-07-08 16:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +@SuppressLint("ConstantFieldName")
This line won't be needed after https://github.com/ankidroid/Anki-Android/issues/9223 is merged.

2021-07-08 17:11 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +        fun handlerPost(function: () -> Unit) {
@david-allison-1 I have already added it, please check the latest code.

2021-07-08 18:57 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +        fun handlerPost(function: () -> Unit) {
@david-allison-1 I have already added it, please check the latest code.

2021-07-08 18:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedPromptBackground.kt
> +// noinspection MissingCopyrightHeader
We still want this with a GPLv3. Stating that it includes content with a GPL compatible license

2021-07-11 09:26 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +                showTutorialForDeckIfNew()
Why do we want to call `showTutorialForDeckIfNew` only if FAB were not already shown. And in particular why would you want to show it when you call the method `showTutorialForFABIfNew`?

2021-07-11 09:26 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +class Onboarding {
There are a lot of classes that are relatively similar but not totally. That makes them hard to follow because even if I grasp the purpose of DeckPicker, I have to re-read the whole AbstractFlashcardViewer because it's not exactly the same logic.

I'd like you to write a small document (a google doc for example, so that we can comment more easily, and edit together) that explain the purpose of those classes. What they are expected to do. Ideally, I'd really like us to have an abstract class that can factorize most of those internal classes and method and ensure that we don't repeat that much code.

For example, I suspect that our goal is to have a list of tutorial we want to show. In this case, we can have a list of pair (flag, tutorial function), and iterate through them with the rule "if flag is not set, set the flag and execute the function". This would make the logic quite easier to follow.

Or, @david-allison-1 , you can say I stop trying to factorize, the code work, we can merge it and still improve it later. That would be acceptable.

2021-07-11 09:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +@SuppressLint("ConstantFieldName")
Yes, it's related to `companion object` and should be removable now the above PR is merged

2021-07-11 09:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +            return AnkiDroidApp.getSharedPrefs(context).edit().putLong(featureIdentifier.declaringClass.simpleName, visitedFeatures.toLongArray()[0]).apply()
Renaming a class is a somewhat common refactoring that you want to allow people to do without concern that they're going to break something.

Changing the constant that's returned from a method is comparatively a much more delicate operation, and people are more likely to ask questions about the impact in a review.

2021-07-11 10:05 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/HandlerUtils.kt
> +     * @param function The function which needs to be executed.
You should explicitly write that it'll execute on the main thread. It's not clear from javadoc and is very important as it mean that it could possibly block the main thread if there is any non-trivial computation here

2021-07-11 10:05 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                if (BuildConfig.DEBUG) {
As another example, this commit should really be more descriptive. It should indicate that it is adding a menu in preference. May be even indicate the path to access it, and the option.

Unless I get things wrong, this commit does not use any of the feature from the previous commits. So you can just create a PR with this commit alone, to get it merged quickly. 
This PR is long, reviewing it is long. I'm strongly in favor of doing plenty of smaller PR. I'll spend less time on each review

2021-07-16 14:49 UTC, Arthur-Milchior commented
Not really a surprise, now that I've merged  the smaller PR, you'll need to rebase this one.

2021-07-18 13:16 UTC, Arthur-Milchior reviewed
Thanks a lot. Only small change remaining I think and almost good to merge. Really really better than the first version as far as I'm concerned

2021-07-18 13:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +    class DeckPicker(
As far as I can tell, there is never any reason to get two objects, am I wrong?
If so, can you use the [singleton pattern|https://en.wikipedia.org/wiki/Singleton_pattern] in those classes?

2021-07-18 13:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +    private Onboarding.AbstractFlashcardViewer mOnboarding = new Onboarding.AbstractFlashcardViewer(this);
Is there any reason to have this as a member? It seems to add state to the object without having any meaning to it.
If we go with the singleton pattern, then there would be really no reason not to simply use the singleton in the two uses of this object. 

Another possibility would be to consider that Reviewer opening and ReviewerShowingAnswer would be two different classes, since they should show different content anyway

2021-07-18 13:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/HandlerUtils.kt
> +     * @param function The function which needs to be executed.
Any reason you did not do it?

2021-07-18 13:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/HandlerUtils.kt
> +     * @param function The function which needs to be executed.
Same request on the other method by the way

2021-07-18 13:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +            executeFunctionWithDelay({ cardBrowserTutorial.visibility = View.GONE }, 4000)
Why do you want to add the delay? For the style? Is there a bug otherwise? Can you please add a comment to it

2021-07-18 13:16 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +            executeFunctionUsingHandler {
Can you please explain why this one in particular need to go through the handler. What is the difference with other CustomMaterialTapTargetPromptBuilder ?

2021-07-18 13:35 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedPromptBackground.kt
> +// noinspection MissingCopyrightHeader
It has been already updated, I think you have reviewed older code. Please check the updated code.

2021-07-18 13:35 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/HandlerUtils.kt
> +     * @param function The function which needs to be executed.
It has been already updated, I think you have reviewed older code. Please check the updated code.

2021-07-18 13:36 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/HandlerUtils.kt
> +     * @param function The function which needs to be executed.
I'll do it on the other method as well.

2021-07-19 09:17 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +    private Onboarding.AbstractFlashcardViewer mOnboarding = new Onboarding.AbstractFlashcardViewer(this);
Singleton objects do not have constructors. In the current implementation, a constructor is required.

2021-07-19 09:17 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +    class DeckPicker(
Singleton objects do not have constructors. In the current implementation, a constructor is required.

2021-07-27 00:46 UTC, mikehardy commented
I've been holding off on checking this one - it appears to have outstanding comments that need response?

2021-07-27 20:01 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +            executeFunctionWithDelay({ cardBrowserTutorial.visibility = View.GONE }, 4000)
It is required to update the visibility after 4 seconds.

2021-07-27 20:02 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +            executeFunctionUsingHandler {
Handler is required here to show feature prompt on menu items. Reference: https://github.com/sjwall/MaterialTapTargetPrompt/issues/73#issuecomment-320681655

2021-07-27 20:04 UTC, ShridharGoel commented
@mikehardy I had already added comments in the code for those things after the checking the review comments. Now, explained those here on GitHub as well.

2021-07-27 20:05 UTC, ShridharGoel commented
This will be ready when #9291 will be merged. It will require a rebase over master after that PR is merged.

2021-08-05 18:59 UTC, ShridharGoel commented
Since #9291 is merged now, I have rebased this. It is ready for review.

2021-08-07 00:42 UTC, Arthur-Milchior reviewed
I've got a troulbe, I can't make it work on my tablet and I don't understand why. I rebased this on top of master, installed it on my tablet, but I never see any onboarding screen. I don't think I ever looked at an onboarding screen, so it's not even due to the fact that they are registered as already seen. Can you help me understanding what is going on (potentially on discord for quicker discussion)

By the way, do we have a way to reset all the flags, to review all onboarding messages again? I don't recall any such option and it may be useful, at the very least to test.

There are questions I asked weeks ago and still have no answer. I put a message on them, could you maybe answer them.
Since they can be found by just reading the code through github, and not on part of the code that disappeared, I suspect they were easy to find; contrary to questions regarding part of the code that disappeared.
I tried implementing some of the idea I suggested on https://github.com/Arthur-Milchior/Anki-Android/tree/onboarding to see whether there was any trouble I overlooked, but it seems not.

2021-08-07 00:42 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/HandlerUtils.kt
> +    fun executeFunctionWithDelay(function: () -> Unit, time: Long) {
I still would like to see a comment in the commit to explain the reason we introduce this.

Is there a way to test it?  I think we could do the same thing that what we did for Tasks executed in background. I think it's setting a boolean to false, then a function set it to true  in a task/handler (eventually with a 1 second delay). 
Then we test the value is put to true. (Potentially we also keep a timestamp, and check that it was executed 1 second after the request, with an acceptable delta)

2021-08-07 00:42 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/HandlerUtils.kt
> +    fun executeFunctionWithDelay(function: () -> Unit, time: Long) {
I still would like to see a comment in the commit to explain the reason we introduce this.

Is there a way to test it?  I think we could do the same thing that what we did for Tasks executed in background. I think it's setting a boolean to false, then a function set it to true  in a task/handler (eventually with a 1 second delay). 
Then we test the value is put to true. (Potentially we also keep a timestamp, and check that it was executed 1 second after the request, with an acceptable delta)

2021-08-07 00:42 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +    private Onboarding.AbstractFlashcardViewer mOnboarding = new Onboarding.AbstractFlashcardViewer(this);
The question still holds

2021-08-07 00:42 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +            executeFunctionUsingHandler {
Would you mind stating what occurs if you don't do it? 
I guess that the item is not yet loaded, so we need to wait until it's actually loaded to execute the function; and adding the function on the looper is a way to do so that just work. Does not seem ideal.

2021-08-07 00:42 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +            executeFunctionWithDelay({ cardBrowserTutorial.visibility = View.GONE }, 4000)
Okay, but why do we want to wait four seconds?

2021-08-07 07:56 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +    private Onboarding.AbstractFlashcardViewer mOnboarding = new Onboarding.AbstractFlashcardViewer(this);
If we don't have it as a member, then it will be required to initialise it two times, once inside `onCreate()` method and again inside `displayAnswerBottomBar()`.

2021-08-07 07:57 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    public boolean hasDecksBeingDisplayed() {
Added.

2021-08-07 07:57 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +class Onboarding {
Can you tell how an abstract class can be used here? Also, what would be the benefit of using it?

2021-08-07 07:57 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +    class DeckPicker(
Updated.

2021-08-07 07:57 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +            executeFunctionUsingHandler {
The tutorial would not load if it is not done.

What is the alternative way to do it then?

2021-08-07 07:57 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +            executeFunctionWithDelay({ cardBrowserTutorial.visibility = View.GONE }, 4000)
So that the tutorial remains visible for 4 seconds. 4 seconds seemed fine, if required then this time interval can be changed.

2021-08-07 07:57 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/HandlerUtils.kt
> +    fun executeFunctionWithDelay(function: () -> Unit, time: Long) {
Okay, I thought that you meant adding a comment in the code which I have already done.

2021-08-07 07:58 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/HandlerUtils.kt
> +    fun executeFunctionWithDelay(function: () -> Unit, time: Long) {
I'll try to add a test for this.

2021-08-07 08:00 UTC, ShridharGoel commented
> I've got a troulbe, I can't make it work on my tablet and I don't understand why. I rebased this on top of master, installed it on my tablet, but I never see any onboarding screen.

@Arthur-Milchior You need to enable onboarding preference in the Advanced settings.

2021-08-07 08:01 UTC, ShridharGoel commented
> I've got a troulbe, I can't make it work on my tablet and I don't understand why. I rebased this on top of master, installed it on my tablet, but I never see any onboarding screen.

@Arthur-Milchior You need to enable onboarding preference in the `Advanced` settings.

2021-08-07 08:02 UTC, ShridharGoel commented
@Arthur-Milchior You need to enable onboarding preference in the `Advanced` settings to view the onboarding related things.

2021-08-07 08:04 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    public boolean hasDecksBeingDisplayed() {
Added.

2021-08-07 08:04 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> + * 2. Create a new method to display the tutorial.
Fixed.

2021-08-07 11:25 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/HandlerUtils.kt
> +    fun executeFunctionWithDelay(function: () -> Unit, time: Long) {
Updated.

2021-08-07 11:26 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/HandlerUtils.kt
> +    fun executeFunctionWithDelay(function: () -> Unit, time: Long) {
Added commit description and unit tests.

2021-08-07 11:27 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/HandlerUtils.kt
> +    fun executeFunctionWithDelay(function: () -> Unit, time: Long) {
Added commit description and tests.

2021-08-07 13:32 UTC, Arthur-Milchior commented
![Screenshot_20210807-152652_AnkiDroid.jpg](https://user-images.githubusercontent.com/357361/128601860-f91ef8be-e694-4393-a38f-341f413119e4.jpg)![Screenshot_20210807-152704_AnkiDroid.jpg](https://user-images.githubusercontent.com/357361/128601861-1a6878e0-13bc-4287-880f-e11715b1c0e8.jpg)![Screenshot_20210807-152713_AnkiDroid.jpg](https://user-images.githubusercontent.com/357361/128601863-c0e02414-2778-486b-9956-aaa98c687c3e.jpg)

For wome reason flag and "answer" appear at the same time.
In full screen mode, the help makes no sens. Probably not an actual problem for most users

2021-08-07 14:02 UTC, Arthur-Milchior commented
I tested it. For some reason, on the deck picker I had only the onboarding for +, not the remaining.
Also, when I saw the onboarding, I clicked on the plus button. It opened the plus menu. Then there was no other help, intuitively I would have thought there should be indication of what to do next. Do you think we could add some indication once the fab menu is opened?

2021-08-07 14:22 UTC, Arthur-Milchior commented
Also, is there a way to restart the onboarding, reset everything to 0? So that I can test the next versions too

2021-08-07 15:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        mOnboarding.onCreate();
Is there anything that ensure that you are not executing the onCreate of both AbstractFlashcardViewer and Reviewer? I'd fear this may explain why I suddenly had two onboarding tips at the same time on my phone.

The easiest solution to it would be to move all of AbstractFlashcardViewer onboarding to Reviewer. We'll deal with actually taking care of AbstractFlashcardViewer if we really need to later. 
Another solution would be to have the Reviewer onboarding inheriting the AbstractFlashcardViewer; a `onboarding()` method in `AbstractFlashcardViewer` that gets overriden in Reviewer to call the Reviewer onboarding

2021-08-07 15:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +            executeFunctionUsingHandler {
I've got a few ideas I'd test, but nothing sure. We can keep it if it works.
I'd test if I knew how to reset the onboarding menus, to be able to see the onboarding again and again until I'm fine with the result. So maybe I'll do it later.

My assumption is that currently it requires the handler only because the flag is not already set, so `setTarget` fails. I hope some log would confirm it.
If it were to be the case, maybe it would be work by simply calling the function later in the lifecycle, not in `onCreate` but `onStart`. Or maybe it would fail anyway for other reason.

2021-08-07 15:31 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +            executeFunctionWithDelay({ cardBrowserTutorial.visibility = View.GONE }, 4000)
maybe I missed something, but I don't understand. I tested and don't think I saw any change after four seconds. What visibility is changed?

2021-08-07 19:11 UTC, ShridharGoel commented
Yes, it is expected that the tutorials for 'Answer' and 'Flag' appear at the same, since both are at different places and also don't need to come one after the other. Should this be changed?

There are no tutorials for options which show after clicking the '+' icon. If they are required, then I'll add them.

2021-08-07 19:11 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        mOnboarding.onCreate();
> Is there anything that ensure that you are not executing the onCreate of both AbstractFlashcardViewer and Reviewer?

No, currently it wasn't a problem since it seemed fine to show tutorials for 'Answer' and 'Flag' together. But I'll update it.

2021-08-07 19:13 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +            executeFunctionWithDelay({ cardBrowserTutorial.visibility = View.GONE }, 4000)
Visibility of the hand icon with text changes to `gone` state. You can refer the video attached in the PR description.

2021-08-07 20:26 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
>          val mOnboardingCondition: ((ActivityType) -> Boolean)? = null
Updated.

2021-08-07 20:29 UTC, ShridharGoel commented on AnkiDroid/src/test/java/com/ichi2/anki/HandlerUtilsTest.kt
> +            SystemClock.uptimeMillis() - initialTime == 1000L,
Updated.

2021-08-07 21:27 UTC, Arthur-Milchior commented
In https://github.com/ankidroid/Anki-Android/commit/50adac2d20d1f1cca67ea1b7956622c2dbef2791 I added a preference to require to show again all onboarding features. Given the remaining time, I preferred to do it myself. Will help me testing multiple time without erasing data.
Not sure its the right place to show it. Maybe the "help" menu will be more appropriate. And it lack test.

2021-08-07 21:46 UTC, Arthur-Milchior reviewed
As a user, my intuition if I  see a big block that hides the screen is to click anywhere outside of the block to make it disappear. I also expect the click not to have any impact. Is it possible to implement this or would it be complex?

2021-08-07 21:46 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +class Onboarding {
I see you pushed after this comment. Any trouble with using the commit I linked here? Even if you disagree, I'd still would prefer an acknoweldgement you saw the remark

2021-08-07 21:46 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/HandlerUtils.kt
> +    fun executeFunctionWithDelay(function: () -> Unit, time: Long) {
I understand. Thank you for the explanation

2021-08-07 21:46 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        mOnboarding.onCreate();
@david-allison-1 @mikehardy any preference here? I find it complex to have two helps at the same time, but I'm fine with keeping it if other people think it is not adding complexity

2021-08-07 21:46 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +            executeFunctionWithDelay({ cardBrowserTutorial.visibility = View.GONE }, 4000)
Okay, now I see it.
Now that I understand what it does, I still want to know why you do it. It's the only text the user have a limited time to read. It already seems a bad idea from an accessibility point of view, but furthermore when dealing with onboarding, where context may take time to remember, it seems even worse. 
Wouldn't just clicking anywhere on the screen work, as everywhere

2021-08-08 07:53 UTC, ShridharGoel commented
> I see you pushed after this comment. Any trouble with using the commit I linked here? Even if you disagree, I'd still would prefer an acknoweldgement you saw the remark

I had pushed other changes. This was not complete, so I had thought to push the changes related to this later. It was acknowledged and was in progress. Updated it now, please check. I have modified the previous commits to include those changes, should I instead pull your commit and add it here?

2021-08-08 09:11 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        mOnboarding.onCreate();
Updated.

2021-08-08 09:15 UTC, ShridharGoel commented
Updated the card browser tutorial. Now, the tutorial related to clicking on a list item will be dismissed after user clicks and not automatically.

2021-08-08 09:18 UTC, ShridharGoel commented
> Also, is there a way to restart the onboarding, reset everything to 0? So that I can test the next versions too

For this, you can clear the app data or edit the code to return `false` from the `isVisited()` method.

2021-08-08 09:20 UTC, ShridharGoel commented
> Do you think we could add some indication once the fab menu is opened?

Yes, but would it be good to do it in a separate PR once this is merged and the one related to introduction slides is also complete?

2021-08-08 09:21 UTC, ShridharGoel commented
> Do you think we could add some indication once the fab menu is opened?

Yes, would it be fine to do it in a separate PR once this is merged and the one related to introduction slides is also complete?

2021-08-08 15:37 UTC, Arthur-Milchior commented
I'm not asking you to pull my commit. Just work the way you prefer. If you prefer to ignore it because I missed an issue, that's fine. If you want to read it and use what you see to change some commit, that's fine. If you want to copy some part of it into a new commit, cool too. I care about the feature and the review, not the way the commit was done

2021-08-08 16:02 UTC, Arthur-Milchior approved these changes
Some small nit. Approval once corrected. @david-allison-1 or @mikehardy I think there are many changes since last approval and so require a new second approval

2021-08-08 16:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        new Onboarding.AbstractFlashcardViewer(this).onAnswerShown();
shouldn't this be a variable, or we lose state between the calls

2021-08-08 16:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            new Onboarding.Reviewer(this).onUndoButtonEnabled();
ditto - use a variable

2021-08-08 16:24 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/card_browser.xml
> +        <TextView
FixedTextView

2021-08-08 16:24 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/19-onboarding.xml
> +    <string name="fab_tutorial_title">Get started</string>
For discussion: 

While we're working on content, I feel that a few of these should be hardcoded (maybe in a companion object) so we're not adding work for our translators that won't be used in the final project

2021-08-08 16:24 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/HandlerUtilsTest.kt
> +        assertThat("Delay is 1 second", duration in 990L..1010L, `is`(true))
`duration in 990L..1010L` can likely be expressed via Hamcrest, rather than checking for a boolean

2021-08-08 16:24 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/HandlerUtilsTest.kt
> +        assertThat("Value has changed to true", value, `is`(true))
```suggestion
        assertThat("function was executed, `is`(true))
```

2021-08-08 16:24 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/HandlerUtilsTest.kt
> +        assertThat("Value has changed to true", value, `is`(true))
```suggestion
        assertThat("function was executed", value, `is`(true))
```

2021-08-08 16:49 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        new Onboarding.AbstractFlashcardViewer(this).onAnswerShown();
@Arthur-Milchior wanted this to not be a variable: https://github.com/ankidroid/Anki-Android/pull/9092#discussion_r684642367

So I had changed it from a variable to use it like this. What should be done here?

2021-08-08 16:49 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            new Onboarding.Reviewer(this).onUndoButtonEnabled();
@Arthur-Milchior wanted this to not be a variable: https://github.com/ankidroid/Anki-Android/pull/9092#discussion_r684642367

So I had changed it from a variable to use it like this. What should be done here?

2021-08-08 17:43 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        new Onboarding.AbstractFlashcardViewer(this).onAnswerShown();
Which state do we lose ? The only state AbstractFlashcardViewer is `this`, the activity.
The only state of its parent class, `Onboarding`, is `this` and also the list of onboarding tasks, which is never edited anyway.

2021-08-08 21:02 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        new Onboarding.AbstractFlashcardViewer(this).onAnswerShown();
Any state in the instance. I didn't check to see whether we have any. 

Regardless, the pattern of having a `private final` variable is much more common than having an allocation for a single method call. 

To me, the code would read better that way (especially as we define the class dependency at the top of the file in the variables), but this is just style and isn't worth blocking the review over. I'd push lightly to change, but implementer's choice.

2021-08-08 21:02 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            new Onboarding.Reviewer(this).onUndoButtonEnabled();
Your call. See: https://github.com/ankidroid/Anki-Android/pull/9092#discussion_r684828630

2021-08-08 21:03 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/HandlerUtilsTest.kt
> +        assertThat("Delay is around 1 second", duration.toDouble(), `is`(closeTo(1000.0, 10.0)))
nittiest of nitpicks

```suggestion
        assertThat("Delay is around 1 second", duration.toDouble(), closeTo(1000.0, 10.0))
```

2021-08-08 21:07 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        new Onboarding.AbstractFlashcardViewer(this).onAnswerShown();
I agree on this. Implementer choice.

2021-08-08 21:13 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        mOnboarding.onCreate();
It would make sense to me to move the onboarding to `Reviewer`. I don't think the onboarding is specific to all implementers of '`AbstractFlashcardViewer`'

https://www.youtube.com/watch?v=GGRF-B6DgeI - keep it as simple as possible, 'flags' are feature promotion, rather than instructional, and should come at a later stage in our onboarding flow.

----
for another time:

It raises the question of whether we want to have flags as the 'always show' for new users. Undo should definitely appear, but flags are a (relatively) more advanced functionality.

'Edit' would make sense, as would some tracking and suggesting a "customise app bar buttons" after a specific time period would be great.

2021-08-08 21:28 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +/**
Updated.

2021-08-08 21:28 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
> +            mTutorials.add(TutorialArguments(DeckPickerOnboardingEnum.DECK_NAME, this::showTutorialForDeckIfNew, { mActivityContext.hasAtLeastOneDeckBeingDisplayed() }))
Updated.

2021-08-08 21:29 UTC, ShridharGoel commented on AnkiDroid/src/main/res/layout/card_browser.xml
> +        <TextView
Updated.

2021-08-08 21:29 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +        new Onboarding.AbstractFlashcardViewer(this).onAnswerShown();
Updated.

2021-08-08 21:29 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +            new Onboarding.Reviewer(this).onUndoButtonEnabled();
Updated.

2021-08-08 21:29 UTC, ShridharGoel commented on AnkiDroid/src/test/java/com/ichi2/anki/HandlerUtilsTest.kt
> +        assertThat("Delay is 1 second", duration in 990L..1010L, `is`(true))
Updated with usage of `closeTo()`.

2021-08-08 21:29 UTC, ShridharGoel commented on AnkiDroid/src/test/java/com/ichi2/anki/HandlerUtilsTest.kt
> +        assertThat("Value has changed to true", value, `is`(true))
Updated.

2021-08-08 21:29 UTC, ShridharGoel commented on AnkiDroid/src/test/java/com/ichi2/anki/HandlerUtilsTest.kt
> +        assertThat("Value has changed to true", value, `is`(true))
Updated.

2021-08-08 21:29 UTC, ShridharGoel commented on AnkiDroid/src/test/java/com/ichi2/anki/HandlerUtilsTest.kt
> +        assertThat("Delay is around 1 second", duration.toDouble(), `is`(closeTo(1000.0, 10.0)))
Updated.

2021-08-08 22:41 UTC, Arthur-Milchior approved these changes
Seems fine by me. I'd be fine with merging.

2021-08-08 22:41 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/19-onboarding.xml
> +    <string name="fab_tutorial_title">Get started</string>
That's uselessly complex. Just remove this file from tools/update-localizations.py; and wait until the content is finally decided.
Do you have a plan to choose which will be the final content?

2021-08-10 21:19 UTC, david-allison-1 approved these changes
LGTM

2021-08-10 21:19 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/19-onboarding.xml
> +    <string name="fab_tutorial_title">Get started</string>
Discussed on Discord, only `fab_tutorial_title` for certain

2021-08-10 21:21 UTC, david-allison-1 commented
Pending CI, doesn't seem to have run.

@mikehardy, what was your mechanism for re-running checks? I'd typically close and open the PR, but the "official" mthod would be better for other peoples PRs

2021-08-10 22:39 UTC, mikehardy commented
If they did not run at all a close reopen might be only way, I wasn't aware of another way besides re-pushing

2021-08-11 21:06 UTC, merged

2021-08-12 00:31 UTC, david-allison-1 commented
Another one down! Thanks so much @ShridharGoel 

![](https://media.giphy.com/media/l3q2SH4Cmhh8F40jS/giphy.gif)