Increasing privacy policy compliance
ankidroid/Anki-Android pull request #9099
Opened 2021-06-11 13:13 UTC by tanmayChakrawarty

## Purpose / Description
Increasing privacy policy compliance for everyone.

## Fixes
Fixes  #9050

## How Has This Been Tested?

Tested on physical device moto g30 (Android 11).

## Output

https://user-images.githubusercontent.com/75254780/121690167-1f830800-cae3-11eb-9e2d-d470f0db0e20.mp4

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-06-11 13:22 UTC, david-allison-1 requested changes
Looks good! Few bits and we can get this in

2021-06-11 13:22 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +    <string name="help_item_terms_and_conditions">Terms and Conditions</string>
AnkiWeb

2021-06-11 13:22 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/constants.xml
> +    <string name="link_crash_reports">https://github.com/ankidroid/Anki-Android/wiki/Crash-Reports</string>
This isn't useful information for an end user, I feel it is explained by our privacy policy, but if not then we need a user facing page

Vote to remove this

2021-06-11 13:22 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
> +                new ItemHeader(R.string.help_title_privacy, R.drawable.ic_baseline_privacy_tip_24, UsageAnalytics.Actions.OPENED_PRIVACY,
Order: we want ankidroid things before AnkiWeb things. Ankidroid is mandatory, AnkiWeb is optional

2021-06-11 17:09 UTC, david-allison-1 commented
Just want to say thanks for the video, made this so much easier to look through!

2021-06-11 17:10 UTC, david-allison-1 requested changes
Also a few unit tests which need updating

2021-06-12 22:15 UTC, david-allison-1 commented
Unit tests still need updating

2021-06-13 04:27 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/constants.xml
> +    <string name="link_crash_reports">https://github.com/ankidroid/Anki-Android/wiki/Crash-Reports</string>
agreed

2021-06-15 14:21 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values-af/03-dialogs.xml
> +    <string name="help_title_privacy">Privacy</string>
Please revert this change.

> Add the string to the first file in the list (/values) and no other file.

See: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#adding-translations

2021-06-15 16:35 UTC, david-allison-1 approved these changes
LGTM

2021-06-20 04:48 UTC, mikehardy approved these changes
This is really fantastic, more comprehensive than I was thinking even (I guess I didn't realize how much data could really be flying around!) and looks great. Thanks

2021-06-20 04:48 UTC, merged

2021-07-31 20:35 UTC, mikehardy commented
Hi there!

Apologies for the delay, and if you're already submitted something to OpenCollective for PRs merged in June 2021 PRs merged, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for June 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in May)

Thanks!