Added Icons in Actionbar overflow menu
ankidroid/Anki-Android pull request #9110
Opened 2021-06-16 08:02 UTC by prateek-singh-3212

## Pull Request template

## Purpose / Description
  Added the icons in the overflow menu in Actionbar 

## Fixes
Fixes: #8912

## Approach
I implemented this by Override the menu methods in class. Such as onMenuOpened and onPanelClosed.

## How Has This Been Tested?
Tested on Samsung Galaxy M51, android 11 (Samsung One UI 3.1)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-06-16 08:08 UTC, prateek-singh-3212 commented
This is not completed yet. I made this PR because I want the code logic to be reviewed. I am attaching the video for better understanding.

https://user-images.githubusercontent.com/76490368/122182623-1067d580-cea8-11eb-93fe-11c052b23d06.mp4

2021-06-16 11:30 UTC, david-allison-1 requested changes
Looks good. Only nitpicks

One question for other reviewers regarding the RestrictedApi: we already use it if Android is running on a TV, and it seems to be the only way

Another question: this seems really similar to:

https://github.com/ankidroid/Anki-Android/blob/425701eb65d8f58267c2d289998fe33b5eeda3ba/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java#L694-L722

Is there a reason you're not using this code?

2021-06-16 11:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +        }
extract this to a method, catch `Throwable` and log/send an exception report if it fails

2021-06-16 11:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +                    if (drawable != null && !menu.getItem(i).hasSubMenu() && !isFlag(menu.getItem(i).getItemId())) {
extract `menu.getItem(i)` to a variable, 

extract `!menu.getItem(i).hasSubMenu() && !isFlag(menu.getItem(i).getItemId())` to a method: `shouldUseDefaultColor` and explain both cases

2021-06-16 11:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +                        drawable.setTint(Color.parseColor("#FF03A9F4"));
Extract to a resource

2021-06-16 11:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +        new Handler().post(new Runnable() {
Convert runnable to lambda

2021-06-16 11:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +        new Handler().postDelayed(new Runnable() {
convert runnable to lambda

2021-06-16 11:31 UTC, david-allison-1 commented
Yes, use if/else. Those won't be constants in a later version

2021-06-17 07:42 UTC, prateek-singh-3212 commented
> Is there a reason you're not using this code?

Yes their is. Previous code uses black color instead of white which we are using now. Secondly when user click on overflow button then icon colors changes to blue (in my code). Not a big issue but simple UI thing.


https://user-images.githubusercontent.com/76490368/122353408-a4e83b80-cf6d-11eb-9ef4-b4c1b3b40fd3.mp4

2021-06-25 04:17 UTC, mikehardy approved these changes
Seems like almost everything was resolved except the question of the RestrictedAPI and the possible code duplication. The code duplication appears to  be addressed (there's a UI reason) and if we already using the RestrictedAPI then this isn't taking it from 0 to 1, we would need a new strategy for the whole idea in future anyway. I did not find the linked stackoverflow info to be authoritative in explaining if this was an upstream bug that it was needed and there's something upstream to track - would be good to link that here in comments if possible. But I think this should go in and we should move on

2021-06-25 04:17 UTC, merged

2021-06-25 05:31 UTC, prateek-singh-3212 commented
@mikehardy I have to add new icons in the overflow menu as their is some duplication of icons [comment](https://github.com/ankidroid/Anki-Android/issues/8912#issuecomment-850806305). Should I add that in new PR?

2021-06-25 12:31 UTC, mikehardy commented
This is merged now, so yes 😁

2021-07-31 20:35 UTC, mikehardy commented
Hi there!

Apologies for the delay, and if you're already submitted something to OpenCollective for PRs merged in June 2021 PRs merged, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for June 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in May)

Thanks!