Created RegisterMediaForWebView class
ankidroid/Anki-Android pull request #9120
Opened 2021-06-18 06:14 UTC by Akshay0701

## Purpose / Description
this class is going to be in use for editor and David suggested including registerMediaWebView class in new pr 
[comment](https://github.com/ankidroid/Anki-Android/pull/9048/commits/fa7e219d0d896e3dd9fc32c07c95d4dc498aa9fd?file-filters%5B%5D=.java#r652818204)

2021-06-22 11:46 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +package com.ichi2.anki;
Needs a copyright header.

2021-06-22 11:47 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +package com.ichi2.anki;
Thanks!

2021-06-22 22:01 UTC, mikehardy reviewed
Mostly a question about the upload limit, and one nitpick on spacing

2021-06-22 22:01 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +        if (bytesWritten > oneMegabyte) {
how did we determine the 1MB limit? just curious. I believe it is smaller than the upload limit of anki desktop - currently 100MB for an individual file

https://faqs.ankiweb.net/are-there-limits-on-file-sizes-on-ankiweb.html

That's obviously ridiculously large but the point is that I'm not sure why we're imposing a limit, much less a 1MB one when the real limit appears to be 100MB/file. If there's a technical reason (crashes with too much data, for instance) maybe something more forgiving like 10MB or similar, or if it is going to be that low, perhaps a note to the user that they may wish to use an image editor to crop or shrink the image then retry (that's what the image attach does in note editor right now)

2021-06-23 05:21 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +        if (bytesWritten > oneMegabyte) {
yes there was technical issue with large file most time causing  `TransactionTooLargeException `with bundle but now its been resolved with [Convert Bundle to LargeObjectStorage ](https://github.com/ankidroid/Anki-Android/pull/9048/commits/e4d1b643f0a964d22884b57a0e2be9a293db6ccd), so we are able to handle large  amount of data now... will increase size limit to 10mb

2021-06-23 13:25 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +        if (bytesWritten > oneMegabyte) {
Great! Yes, Bundles in general should never be used for data passing that is more than a known + finite set of key/values

2021-06-23 13:28 UTC, mikehardy requested changes
really close to merge-able, in my opinion - just want the limit renamed and made class constant then it's good, to me

2021-06-23 13:28 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +        final int megabyte = 10 * 1000 * 1000;
okay - 10MB seems more reasonable, final thing is that since this is a final and it is a constant, it should be a static final class constant up above I think, and it's no long 'megabyte', constant should be something about its use I think like `MEDIA_MAX_SIZE` ?

2021-06-23 13:39 UTC, Akshay0701 commented
done!

2021-06-23 15:09 UTC, mikehardy approved these changes
I like it - @david-allison-1 I think this was at your request - does it meet your expectations?

2021-06-23 15:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +    private static final int MEDIA_MAX_SIZE = 10 * 1000 * 1000;
Can you split the commits into: 

* extract the class
* change functionality

The commit message doesn't mention that the max size has been changed, and this makes it awkward for future developers to understand what's happened here

2021-06-23 15:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +        final int megabyte = 10 * 1000 * 1000;
I should have explained this better at the time

* I didn't want a forced "crop" dialog when a user was pasting an image without UX work on it
* We don't have automated processing & compression of the image, if you paste an image, typically you want the exact image pasted
* I didn't want to encourage the users to thoughtlessly upload large files to AnkiWeb, both from a service perspective, and from a user bandwidth perspective

I feel at this time a 1MB limit is better, open to discussion.

2021-06-23 15:19 UTC, david-allison-1 reviewed
You're not using this class anywhere, shouldn't this be used in the Note Editor when pasting an image?

2021-06-23 15:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +public class RegisterMediaForWebView {
Maybe `MediaRegistration` for a name

2021-06-23 15:20 UTC, david-allison-1 commented
Oh, overall I like it!

2021-06-23 15:39 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +        final int megabyte = 10 * 1000 * 1000;
I still think 1MB is too small, as a computing dinosaur I find current file sizes to be kind of outrageously large but it seems the norm. 10MB may be too large for the reasons you cite, but I don't want users to constantly bump up against this for "normal" images. Just going with standard "positional bargaining" then, how bout 5MB ;-) ?

2021-06-23 17:01 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +    private static final int MEDIA_MAX_SIZE = 10 * 1000 * 1000;
okay, split it into two commits now.

2021-06-23 17:03 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +        final int megabyte = 10 * 1000 * 1000;
@david-allison-1 do you agree on the 5MB limit?

2021-06-23 17:05 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +        final int megabyte = 10 * 1000 * 1000;
[You drive a hard bargain, sir!](https://www.youtube.com/watch?v=51_Qs8tq5c8)

I'll be happy with 5, but I'll concede, and would like to include the "image compression" step in here that we use in the gallery. 

I really don't want to encourage large files on AnkiWeb (unless a user requires it). Most users will upload large files out of ignorance rather than necessity, and it's not fair to put unnecessary strain on a free service

2021-06-23 17:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +            //noinspection ResultOfMethodCallIgnored
Message was removed from here, we still want a toast on the Note Editor

2021-06-23 17:08 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +            //noinspection ResultOfMethodCallIgnored
yes i just noticed that and did chances

2021-06-23 17:10 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +        final int megabyte = 10 * 1000 * 1000;
definitely i will do that in next pr

2021-06-23 17:37 UTC, david-allison-1 approved these changes
Thanks!

2021-06-23 17:41 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/RegisterMediaForWebView.java
> +        final int megabyte = 10 * 1000 * 1000;
agreed it's typically just ignorance and agreed I don't want to stress a free service if at all possible, so looking forward to any sort of compression / crop flow in future but we can unstick here for now which is good

2021-06-23 17:42 UTC, merged