Implement app introduction system
ankidroid/Anki-Android pull request #9130
Opened 2021-06-21 15:05 UTC by ShridharGoel

2021-06-26 13:43 UTC, Arthur-Milchior reviewed
I think we should pair program the flags together, so that it gets done and merged and we can stop caring about them.

IntroductionActivity would seem nice except that all DeckPickerTest now fails. Do you have any idea why?
Did you run the test on your computer? I pulled your branch on my computer and tests also fails here, so I would expect you have the same problem. Do you want help investigating that?

2021-06-26 13:43 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +        return (AnkiDroidApp.getSharedPrefs(context).getLong(enum.name, 0) and (1L shl enum.ordinal)) == 0L
This part should also use the bitset I believe, just to be extra sure that the logic is right

2021-06-26 13:43 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +        return AnkiDroidApp.getSharedPrefs(context).edit().putLong(enum.name, bitset.toLongArray()[0]).apply()
`enum.name` contains the name of the element of the enumeration. What you actually want here is the name of the enumeration itself, the class inheriting enum. There are mulitple way to do it. The simplest being using `enum.getClass().getSimpleName()`. 
We should have regression test here, because I believe it would have entirely defeated the purpose of the tool.
Worse, if you had multiple enumerations with value of similar name, there would have been a clash

2021-06-26 15:03 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +    fun <T : Enum<T>> setAsVisited(enum: Enum<T>, context: Context) {
By the way, you probably could use `enum: T`; since you have the parameter, there is no reason to use `Enum<T>` instead of `T`

2021-06-26 15:21 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +        return AnkiDroidApp.getSharedPrefs(context).edit().putLong(enum.name, bitset.toLongArray()[0]).apply()
This is already updated in the other PR related to onboarding. I will update it here as well.

2021-07-04 22:41 UTC, Arthur-Milchior commented
Would you mind rebasing this on top of master? Maybe working on both PR in parallel. I think they don't use a lot in common anymore, and you have at least one html document to start to work with. So that you have something else to do while you wait for our review

2021-08-08 19:29 UTC, Arthur-Milchior reviewed
Thank you a lot for this work.
Is there a way for the user to choose the language when AnkiDroid start? I fear that some users may get English by default and then change the language later, when the onboarding is already seen.
Anyway, i'd guess it's nice to ask the user to confirm their language on first start. I think AnkiDroid is currently in English on my tablet which is otherwise in French, not ideal

I think the first two commits must be merged. (except for the js part which may be removed)

2021-08-08 19:29 UTC, Arthur-Milchior commented on AnkiDroid/src/main/assets/CardBrowser.html
> +            <tr>
There is a slight issue here, that we must discuss (ping @david-allison-1 and @mikehardy  )

I think that when we localize the app, the left language should be the user language. That is, we should ask the translators to translate "to know (about), be aware (of)". 

If the language is German or some Swiss German, I guess "wissen (von +dat, um +akk)" should be replaced by English. Given that it is a special case, we can hard code it instead of having to ask translators to do it manually

2021-08-08 19:29 UTC, Arthur-Milchior commented on AnkiDroid/src/main/assets/DeckList.html
> +            <div class="diveder"></div>
divider (here and in the comment)

2021-08-08 19:29 UTC, Arthur-Milchior commented on AnkiDroid/src/main/assets/DeckList.html
> +            <!-- Diveder to seprate -->
divider

2021-08-08 19:34 UTC, ShridharGoel commented on AnkiDroid/src/main/assets/AddNote.html
> +        <p class="regular" id="dialogue-text">Tags: </p>
String resources are already being used in IntroductionFragment.kt.

2021-08-08 19:39 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +        val mTitle: Int,
It's there in the lint rules, so needs to be done like this.

@david-allison-1 Has this changed with https://github.com/ankidroid/Anki-Android/pull/9378?

2021-08-08 19:43 UTC, ShridharGoel commented on AnkiDroid/src/main/assets/DeckList.html
> +            <div class="diveder"></div>
Yeah, I tried to fix the typos which were there in #9162 (since I directly took the commit from there). Might have missed this one.

2021-08-08 19:43 UTC, ShridharGoel commented on AnkiDroid/src/main/assets/DeckList.html
> +            <!-- Diveder to seprate -->
Yeah, I tried to fix the typos which were there in #9162 (since I directly took the commit from there). Might have missed this one.

2021-08-08 19:47 UTC, ShridharGoel commented on AnkiDroid/src/main/assets/DeckList.html
> +            <div class="diveder"></div>
Yeah, I tried to fix the typos which were there in #9162 (since the first commit of this PR has been taken from there). Might have missed this one.

2021-08-08 19:47 UTC, ShridharGoel commented on AnkiDroid/src/main/assets/DeckList.html
> +            <!-- Diveder to seprate -->
Yeah, I tried to fix the typos which were there in #9162 (since the first commit of this PR has been taken from there). Might have missed this one.

2021-08-08 19:57 UTC, ShridharGoel commented on AnkiDroid/src/main/res/values/19-onboarding.xml
> +    <string name="basic">Basic</string>
Updated.

2021-08-08 19:58 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +    ) : Serializable
Not required, removed it.

2021-08-08 20:04 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionFragment.kt
> +                                    loadUrl("javascript:replace('app-name', '" + getString(R.string.app_name) + "')")
> For safety, this function may also escape the quote.

Which quote? Currently, I don't think there is any quote being used in the text which is being accessed through string resources.

2021-08-08 23:25 UTC, david-allison-1 commented
> Is there a way for the user to choose the language when AnkiDroid start? I fear that some users may get English by default and then change the language later, when the onboarding is already seen.

We use the default system language (except for traditional Chinese, which is set to simplified Chinese due to a bug)

2021-08-08 23:27 UTC, david-allison-1 commented on AnkiDroid/src/main/assets/CardBrowser.html
> +            <tr>
What's the plan for handling translations with this file?

2021-08-11 02:03 UTC, infinyte7 commented
There are some points
1. Can we add simple gradients to html body page? (https://webgradients.com/)
2. Round corner to images
3. Title in bold and subtitle not in bold

2021-08-11 20:49 UTC, Arthur-Milchior commented
> We use the system language

That's not blocking, but I guess that I'd like for the user to choose their language, before showing them an introduction. Simply because not all users know how to configure their phone language.
It's virtually a selection menu, so I'd assume it requires nothing very fancy. But I also expect to be proven wrong in unexpected way

@infinyte7 Can you please explain your reasoning? I'm quite ignorant and I'd like to understand why it would be better.

2021-08-11 21:03 UTC, Arthur-Milchior reviewed
Thanks for your answers.
Some of the remark I gave are still valid; such as merging the first two commits to avoid introducing typos.

That's still keep @prateek-singh-3212 's autorship of the commit introducing file, if this were a reason why you did not want to edit his commit

2021-08-11 21:03 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionFragment.kt
> +                                    loadUrl("javascript:replace('app-name', '" + getString(R.string.app_name) + "')")
`getString(R.string.app_name)` may contain a quote symbol in one of the many translation.
You're injecting non-sanitized string into some code. Admittedly, it's some code from crowdin, and we do not have access to important data, so it's not that important, but still a bad idea in general.

In any case, the remaining request, to remove duplications of all of those loadUrl lines, still holds

2021-08-11 22:40 UTC, mikehardy commented on AnkiDroid/src/main/assets/CardBrowser.html
> +            <tr>
There is a comment above from @ShridharGoel 

> String resources are already being used in IntroductionFragment.kt.

But I have no idea how these will be translated, technically - like how exactly the translated strings will make their way into these HTML files?

That seems like the real hurdle to me. Having some strings be translatable and others not, or how exactly to direct the translators on crowdin seems like a minor point handled with string context?

2021-08-12 02:42 UTC, infinyte7 commented
> We use the system language

@Arthur-Milchior 
I think this answer will be given by @david-allison-1 .

2021-08-14 17:36 UTC, Arthur-Milchior reviewed
Thanks a lot. Still some request.
And thanks a lot for taking previous request into account

2021-08-14 17:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/assets/AddNote.html
> -
Can you please remove it in the first commit, in order not to add and remove the same code in successive commit?

2021-08-14 17:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +    data class IntroductionResources(
This request still hold

2021-08-14 17:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +        val mLocalization: List<Pair<String, Int>>? = null
Can you please add a javadoc on mLocalization to indicate that the int represents a string ressource id.

2021-08-14 17:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private static final String INTRODUCTION_SLIDES = "IntroductionSlides";
In OnboardingUtils.reset, would you mind putting back INTRODUCTION_SLIDES preference to false, please?

Also, can you rename it to "IntroductionSlidesShown" or something like that, so that it's clear that it represents whether it was shown and not whether it must be shown

2021-08-14 17:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionFragment.kt
> +            val resourcesBundle = bundleOf(
Is there any trouble with using the IntroductionResources in the constructor of IntroductionFragment instead of putting it in the bundle?
Since we only use introduction fragment explicitly from introductionActivity on create, I'd think it would work, and maybe make the code more readable, avoiding to go through this bundle, and checking for null for each value that may actually not be nullable such as the title

2021-08-14 17:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/StreamUtils.kt
> +    fun streamToString(inputStream: InputStream?): String {
Is there a reason to accept a nullable value? It seems you only use it with non nullable arg. I think I'd prefer it non nullable, and if ever someone want to use again, let them choose the string for null, if any

2021-08-14 17:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +            mLocalization = listOf(
Is this the only Introduction with localization? I was certain that there were localization in other slides too.

2021-08-14 17:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +                "app-name" to R.string.app_name, "due-time" to R.string.due_time,
Esthetically, I'd go with one pair by line for ease of readability. But no universal rule to follow here, just something I prefer when a list do not fit on a single line

2021-08-14 17:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionFragment.kt
> +        webView.evaluateJavascript("document.getElementById('" + id + "').innerHTML = '" + getString(stringResource) + "'") {}
I would still like you to escape the string. Because we still have no guarantee that either a translation, or a string won't contain ', ", or \.
In particular, in English and French, and I assume other language I don't know, the single quote is used often in every day sentence. Like the two previous sentence of this comment. So the risk seems realistic.

2021-08-14 19:23 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionFragment.kt
> +            val resourcesBundle = bundleOf(
It's a good practice to do it this way: https://stackoverflow.com/a/9245510

2021-08-14 19:34 UTC, ShridharGoel commented on AnkiDroid/src/main/assets/AddNote.html
> -
Updated.

2021-08-14 19:34 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +        val mLocalization: List<Pair<String, Int>>? = null
Updated.

2021-08-14 19:34 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +    data class IntroductionResources(
Updated.

2021-08-14 19:34 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private static final String INTRODUCTION_SLIDES = "IntroductionSlides";
Updated.

2021-08-14 19:35 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +            mLocalization = listOf(
Sorry, missed the required updates here. Done now.

2021-08-14 19:36 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/StreamUtils.kt
> +    fun streamToString(inputStream: InputStream?): String {
Thanks, it should have been non-nullable. Updated.

2021-08-14 19:36 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +                "app-name" to R.string.app_name, "due-time" to R.string.due_time,
Updated.

2021-08-14 19:36 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionFragment.kt
> +        webView.evaluateJavascript("document.getElementById('" + id + "').innerHTML = '" + getString(stringResource) + "'") {}
Updated.

2021-08-14 19:39 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionFragment.kt
> +        webView.evaluateJavascript("document.getElementById('" + id + "').innerHTML = '" + getString(stringResource) + "'") {}
How can this be done here?

2021-08-14 20:22 UTC, Arthur-Milchior reviewed
Once strings are escaped, I'm fine with merging

2021-08-14 20:22 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +            mLocalization = listOf(
thanks

2021-08-14 20:22 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionFragment.kt
> +            val resourcesBundle = bundleOf(
Thanks. I totally forgot the reason behind it. Nice to learn it again. Should really put activity documentation in anki

2021-08-14 20:22 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionFragment.kt
> +        webView.evaluateJavascript("document.getElementById('" + id + "').innerHTML = '" + getString(stringResource) + "'") {}
http://commons.apache.org/proper/commons-lang/javadocs/api-2.4/org/apache/commons/lang/StringEscapeUtils.html#escapeJavaScript(java.lang.String)

2021-08-14 20:22 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionFragment.kt
> +        webView.evaluateJavascript("document.getElementById('" + id + "').innerHTML = '" + getString(stringResource) + "'") {}
If you please, put this kind of question on discord; if I see them quickly, I can answer quicker, while reviewing a whole commit may take time

2021-08-14 20:22 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionFragment.kt
> +                // Optimisation to load local HTML faster
How much time do you save?
I would have imagined that, given that those are small files, and only shown once each, the time saved would be negligeable.

Still nice to have.

2021-08-15 01:25 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/StreamUtils.kt
> +    fun streamToString(inputStream: InputStream): String {
looks like it clones 

https://github.com/ankidroid/Anki-Android/blob/00abc059f60fd18ddc9e77d2425436a3cad044ed/AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java#L663-L684

2021-08-15 01:25 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionFragment.kt
> +                    val inputStream: InputStream = mgr.open(it, AssetManager.ACCESS_BUFFER)
This needs to be in a `.use`, likely also in a helper method

2021-08-15 01:25 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        if (!AnkiDroidApp.getSharedPrefs(this).getBoolean(INTRODUCTION_SLIDES_SHOWN, false)) {
can we either move this further into the startup flow, or return early? We risk having two startup flows at once here

Could you unit test this? The startup process is complex, and mistakes will be made in future

2021-08-15 14:41 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionFragment.kt
> +        webView.evaluateJavascript("document.getElementById('" + id + "').innerHTML = '" + getString(stringResource) + "'") {}
Thanks, updated.

2021-08-15 15:38 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionFragment.kt
> +                // Optimisation to load local HTML faster
Haven't checked the amount of difference.

2021-08-15 15:38 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/StreamUtils.kt
> +    fun streamToString(inputStream: InputStream): String {
Updated.

2021-08-15 15:38 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionFragment.kt
> +                    val inputStream: InputStream = mgr.open(it, AssetManager.ACCESS_BUFFER)
Updated.

2021-08-15 15:39 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        if (!AnkiDroidApp.getSharedPrefs(this).getBoolean(INTRODUCTION_SLIDES_SHOWN, false)) {
Updated.

2021-08-16 01:07 UTC, Arthur-Milchior reviewed
Only nit. Plus the fact that the test fail, so it must be corrected.

Note that the failing test give specific hint to correct it:
>     * Note: If you ran this test and it failed, please check to make sure that any new onCreate methods
     * have the following code snippet at the start:
     * <code>
     * if (showedActivityFailedScreen(savedInstanceState)) {
     *     return;
     * }
     * </code>
     *

2021-08-16 01:07 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionFragment.kt
> +    private fun replaceStrings(webView: WebView, id: String, stringResource: Int) {
I think the method name is too vague. There are a lot of thing that correspond to "replaceStrings".
I'm having trouble finding something short descriptive name. Maybe something such as "localizeSlide"
Can you have something such as `@StringRes` in Kotlin, so that the the variable name is more description while keeping the information.
E.g.  
```kotlin
private fun localizeSlide(webView: WebView, sentenceIdInHtml: String, sentenceResource: Int) {
```

Also, since it uses no local state, maybe it can be static

2021-08-16 01:07 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionFragment.kt
> +        webView.evaluateJavascript("document.getElementById('" + id + "').innerHTML = '" + StringEscapeUtils.escapeEcmaScript(getString(stringResource)) + "'") {}
I think the line is too long to be easy to read.
I'd state to be the output of escapeEcmaScript into a value

2021-08-16 01:07 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionFragment.kt
> +    private fun replaceStrings(webView: WebView, id: String, stringResource: Int) {
In any case, unless we find a very clear name, I'd go with a small javadoc

2021-08-23 17:34 UTC, Arthur-Milchior approved these changes
Still fine with it. But as last time, I didn't even notice the issue David noticed, so it's not very informative.

Can you please add a wiki page explaining to future developer how what they should do if:
* they want to add a new slide in deck picker
* they want to add a new slide deck (maybe it'd make sens to explain statistics, or add note, or something, with slides before showing onboarding)
* they want to add other oonboarding rectangle/circle

After all, not only did you add onboarding tools, but you added a framework which will allow any developer to easily add new onboarding indication; but for it to be used as easily as possible, it's important to document.

(I'll repeat myself. But compared to the first commits I reviewed, I'm honestly really happy how it evolve. You had something that worked very early. However, now, not only it works, but it's a system that is easy to make evolve as we want, meaning that you made maintenance and future evolution really easy)

2021-09-04 19:20 UTC, ShridharGoel commented
Wiki page for introduction slides: https://github.com/ankidroid/Anki-Android/wiki/Introduction-slides-for-new-user-onboarding
Wiki page for feature prompts: https://github.com/ankidroid/Anki-Android/wiki/Onboarding-feature-prompts-for-new-users

These are the initial versions of these pages, they might be updated later to include more information.

2021-09-18 12:14 UTC, Arthur-Milchior commented
@david-allison-1 any reason not to merge? @mikehardy can you review?

Thanks a lot @ShridharGoel for the wiki page. Can you please let me know whether you expect to update them to take my discord remarks into account? 
In particular, I think they really need:
* screenshot
* links to the github page with both the implementation of the methods you discuss, and an example of its usage

2021-10-03 22:49 UTC, david-allison-1 commented
Implementation: I'm happy, but I don't feel the content is providing an optimal onboarding benefit right now. 

I'd like to discuss the content and our goals with onboarding

As I've said a couple of times: We don't want to be advertising features. When a user installs an app, they want to get started as soon as possible, and we should only get in the way if the benefit is tangible. [UX advice](https://www.nngroup.com/people/alita-joyce/)`*` suggests onboarding to be as short as possible, and I feel we can cut this down.

I feel we want to provide:

* Information: Benefit of AnkiDroid. Something like: "We're different. We tell you what to study so you don't forget. Study less and get better results." but with more thought put into it.
* Onboarding: download from AnkiWeb if the user already has an account
   * Inform: Free recommended backups (optional)
* Onboarding: Permissions? Probably not, as that's going away this month.
* Optional: create your own deck, or download for free from AnkiWeb

`*` There are multiple really high quality articles & videos on Mobile Onboarding under the link

2022-03-22 19:37 UTC, Arthur-Milchior commented
It took conflict.
Maybe we can merge it, and improve on it later. Since it is not activated by default, and require a preference change, it's not like the users will get to see it. However, it will be easier for other contributors to provide suggestion or PR on top of this system when they have already existing examples.

It's not like one of us seems to know how to design an optimal slide system, and current options seems better than nothing

2022-03-23 11:34 UTC, mikehardy commented
@Arthur-Milchior I agree with you, I'm sad to see this unmerged still
Let me queue it for review and then hopefully we can iterate from there once it is in

2022-03-24 13:44 UTC, mikehardy commented
Oh for ______ 😠  it took another conflict 😆 because of #10577 doing Kotlin migration on IntentHandler.
We need to get this in ASAP, the entropy effect on it is *fierce*
I'll review it as is, I assume @ShridharGoel has the Kotlin mastery in more than sufficient quantity to rework that bit and it won't be significantly different

2022-03-24 14:00 UTC, mikehardy requested changes
The code in IntentHandler looks okay, hopefully the conversion to Kotlin is not too painful 😩 

I have some serious concerns about the duplicated code from AnkiActivity, that worries me a lot and I don't think we should merge this with that duplication in existence

I have a question about abstract to a .css file, hopefully a WebView that loads an HTML file can handle a reference to a .css file inside app assets from that HTML file, if so the CSS here would be really simplified.

It's great in general though - the idea, the pages, the implementation, I'm certain it all works, my comments would mostly just de-duplicate things if addressed

2022-03-26 21:36 UTC, Arthur-Milchior commented on AnkiDroid/src/main/assets/AddNote.html
> +    <style>
Maybe we should ping @prateek-singh-3212. Just in case you're willing to do this factorization, since it was your code

2022-03-26 21:57 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java
> +        setUpReloadIntentAndFinish(reloadIntent);
Implementor choice: I'd like an atomic commit which simply create `setUpReloadIntentAndFinish` and use it. This way, it'll be extremely easy to see that this atomic commit really do nothing, and separate this split from actual interesting behavior

2022-03-26 21:57 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +    private fun handleStartupFailure(startupFailure: StartupFailure) {
Can you please add a documentation indicating what occurs in this case.

2022-03-26 21:57 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +    // This method has been taken from AnkiActivity.
Agree with Mike
At the very least, it would be required to explain why duplication is required instead of factorization

2022-03-26 21:57 UTC, Arthur-Milchior commented on AnkiDroid/src/main/AndroidManifest.xml
> +            android:label="@string/introduction_activity"
Why do we need a label. 
Note that the same question holds in a lot of part of the code.
This is extra work for lot of translators. And it does not seems that it can ever be shown to the users since this activity can not answer to any outside intent nor be shown as an android icon

2022-03-27 12:03 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
> +    // This method has been taken from AnkiActivity.
It seemed difficult to prevent duplication here since `IntroductionActivity` needs to inherit from `AppIntro`. Any suggestions on how to use an interface here or some other way to avoid duplication? Also, the reason is mentioned in the next line.

2022-03-27 19:07 UTC, Arthur-Milchior reviewed
I can't compile right now. I assume some AppIntro dependency is missing in gradle. Would you mind adding it if I'm right

Without compiling, it's hard to investigate what can be done. Essentially, the obvious option is to use either AppIntro or `AnkiActivity` as a delegate. Ideally, I'd prefer the first one, because it may require to split AnkiActivity in the main activity and a delegate otherwise, and I don't like touching this base component of Anki

2022-03-27 19:07 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java
> +
On my computer, it seems there is whitespace. But I can't see it on github.

2022-03-27 19:07 UTC, Arthur-Milchior commented on AnkiDroid/build.gradle
> +    implementation 'org.apache.commons:commons-text:1.9'
Shouldn't gradle also contains a change to depends on AppIntro?
I'd expect it to be necessary to depends on AppIntro. 
At least I can't compile when downloading this branch, and I assume it may be the issue

2022-03-28 00:20 UTC, david-allison commented
> * Onboarding: download from AnkiWeb if the user already has an account

This is something that I'm 100% on and would like to push heavily in our onboarding, even if it's this one feature for now. This saves a lot of hassle

2022-03-28 00:25 UTC, Arthur-Milchior commented
> > * Onboarding: download from AnkiWeb if the user already has an account
> 
> This is something that I'm 100% on and would like to push heavily in our onboarding, even if it's this one feature for now. This saves a lot of hassle

I entirely agree with the feature. However, I'm not sure it's great to put it in this PR, given that it's already big, require already some changes, and I don't expect it to be quite harder to add it into an extra PR once this one is merged

2022-03-28 00:37 UTC, david-allison commented
If this PR is only the framework, then agreed. I'll move this to a separate issue.

2022-03-28 00:40 UTC, david-allison requested changes
Are the assets copied to the APK if they're unused?

If so, could we exclude them via gradle for now to reduce APK bloat.

2022-03-28 23:03 UTC, mikehardy commented
I'm not worried about the asset size as much as the duplication in the assets files (specifically the CSS which is copy-pasted all over. If we can de-duplicate so it's good code (HTML/CSS *is* code...) then there won't be that much text to begin with (after APK unpack), and the assets are compressed pretty hard in the APK so it should be a non-issue.

I just want there to be one canonical set of CSS mostly

2022-03-29 05:48 UTC, ShridharGoel commented on AnkiDroid/build.gradle
> +    implementation 'org.apache.commons:commons-text:1.9'
Seems like it got removed while resolving conflicts, I'll add it back.

2022-03-30 22:52 UTC, Arthur-Milchior commented
I saw @ShridharGoel you force pushed. However, it still has a conflict. I don't know if it was here when you pushed or if you really got unlucky.
Anyway, can you please let us know when you want the next review

2024-08-25 12:52 UTC, Arthur-Milchior commented
To be consistent with #16946, let's also close this PR.
It was nice work, I'm kind of sorry users never get to see it, but if nobody shares my opinion, it's not worth keeping it open. Sorry @ShridharGoel for your work.

Ping @david-allison, you may like to see it closed

2024-08-25 12:52 UTC, closed without merging