Show total card count in DeckPicker when no cards are due
ankidroid/Anki-Android pull request #9143
Opened 2021-06-24 18:07 UTC by ShridharGoel

## Purpose / Description
Show total card count in DeckPicker when no cards are due so that users can understand that there cards are still there, just the due count is zero.

## Approach
If number of due cards is zero, then change the subtitle in the toolbar of the DeckPicker.

## How Has This Been Tested?

Verified the functionality on device.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-06-24 18:45 UTC, mikehardy commented
This means we have divergent functionality from AnkiDesktop yes? Do you have a screenshot to show the different states?

2021-06-24 18:56 UTC, david-allison-1 requested changes
Just a nitpick

Could you add screenshots, and it looks good to go for me

2021-06-24 18:56 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                    String subTitle = res.getQuantityString(R.plurals.deckpicker_title, due, due, time);
Could you move this to the `else` - it's not ideal to reassign variables if possible

2021-06-24 18:57 UTC, david-allison-1 commented
> This means we have divergent functionality from AnkiDesktop yes? Do you have a screenshot to show the different states?

To my understanding, Anki Desktop doesn't show this information at all

2021-06-24 19:07 UTC, ShridharGoel commented
Added screenshots.

2021-06-24 19:07 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                    String subTitle = res.getQuantityString(R.plurals.deckpicker_title, due, due, time);
Updated.

2021-06-24 19:21 UTC, david-allison-1 approved these changes
LGTM. I feel this will massively reduce the "where have my cards gone" complaints from new users

2021-06-24 19:23 UTC, mikehardy commented
> To my understanding, Anki Desktop doesn't show this information at all

Oh fantastic! Then we can do whatever we like :-), In that case I agree with David :100: - this will really really help a common user frustration where they think they lost their cards. Thanks @ShridharGoel !

2021-06-24 19:24 UTC, mikehardy approved these changes
Nice

2021-06-24 19:26 UTC, mikehardy commented
Hey @david-allison-1 - you mentioned in some other area you have some git scripts that pull PRs locally, I'll do a big batch of github-actions-emulator-CI-execution locally to verify the current batch for merge, but I'd go faster if you could paste it in here :pray:  :-)

2021-06-24 19:28 UTC, david-allison-1 commented
> Hey @david-allison-1 - you mentioned in some other area you have some git scripts that pull PRs locally, I'll do a big batch of github-actions-emulator-CI-execution locally to verify the current batch for merge, but I'd go faster if you could paste it in here 🙏 :-)

Likely not going to be too much use, but sharing is caring

Script is for Windows (.cmd), and I've misplaced the incantation to register this as `git pr`

%1 is required, %2 is optional

```
git fetch upstream pull/%1/head:pr-%1-%2
git checkout pr-%1-%2
```

2021-06-24 22:23 UTC, mikehardy commented
@david-allison-1 https://github.com/NordicHPC/git-pr :-) - and you edit ~/.gitconfig to make aliases if you want, works a treat!

2021-06-24 22:45 UTC, david-allison-1 commented
> @david-allison-1 https://github.com/NordicHPC/git-pr :-) - and you edit ~/.gitconfig to make aliases if you want, works a treat!

Thanks! GitHub CLI looked interesting, but what I have works perfectly for my PR workflow right now

2021-06-24 23:14 UTC, mikehardy commented
Looks great locally when I pull it, 
Passes `./gradlew jacocoTestReport` on  the gamut of API21-API30 phone emulators plus a Pixel C API30 tablet emulator

2021-06-24 23:14 UTC, merged

2021-06-24 23:28 UTC, dae commented
This is something I'd like to solve on the desktop end as well, as it causes a lot of confusion. The Rust deck list code does a single table scan, so providing the total deck counts will be possible with minimal extra overhead. I'd been thinking of maybe showing them as the user hovers the mouse over a deck item, but hover is a no-go on mobile

2021-06-25 00:03 UTC, mikehardy commented
@dae really scarce real estate for us there with deck name already and 3 numbers, but yes - it's a real user issue. If it's all three zeros maybe it switches to a completely different mode that is like "0 ($total)". That's just spaghetti on the wall and normally I don't like multi-modal UIs but any idea here that worked and killed the confusion would be great. I paste our "lost my cards" FAQ link about 10x a week and that's just people with the gumption to speak up

2021-06-25 00:06 UTC, dae commented
Need to strike a balance here - people who know how things work appreciate having greyed out 0s so they can clearly see what still needs attention, and showing a big remaining count in the zero case will go against that. Maybe something like a grey "today done" instead?

2021-06-25 00:35 UTC, dae commented
One other thing to consider is that's in not just the completion case - users will import a large deck, see only 20 cards shown, and think the import failed. Ideally we communicate that the shown number is not a total, even when cards are remaining

2021-06-25 01:09 UTC, david-allison-1 commented
I feel making changes to the "deck overview" screen would be the way to go.

The screen has a lot of blank space, and we can add more information which will be helpful to all users without it becoming text-heavy. In particular for this issue:

* `current/total` cards learned
* horizontal progress bar (new/review/unseen etc...)
* (more controversial) Specific buttons for "learn more" + "review more" with appropriate caveats (done via time estimation of how long tomorrow's review session will be increased by)

<details>

![image](https://user-images.githubusercontent.com/62114487/123352927-423c0480-d558-11eb-947f-a9fd8a7b67c6.png)
![image](https://user-images.githubusercontent.com/62114487/123353090-a4950500-d558-11eb-9bdf-3131f5e0483c.png)
</details>

----

RE: Imports

We display "X notes/cards imported" after an import in a dialog (so a user has to acknowledge this). I presume Anki Desktop does the same.

2021-06-25 04:30 UTC, mikehardy commented
Interesting, I admit I like the series of zeros but then of course I understand how it works now. Maybe a grayed out "today done" as you mention (same dopamine hit / concretely done feel for me as the zero series...) and then full communication where we do have the space. If there was then a visual balance between making it obviously clickable (so people go in and see the extra info) without making the deck list look terrible, it might be a completely package

2021-06-25 06:37 UTC, Akshay0701 commented
I also agreed with dae, grayed out "today done" will be good in zero cases, it might give dopamine hit to users,
but I don't think so we currently have space in an android for "today done", I think instead of putting text in android we can put "✔️" (this will indicate the card is been completely reviewed, and it might fit into a small android device as well). 

just a thought: what if..... we give streak count(like Snapchat) to keep users motivated to increase and not break the daily streak count.