Fixed disappearing Actionbar icon after syncing
ankidroid/Anki-Android pull request #9155
Opened 2021-06-27 10:51 UTC by prateek-singh-3212

## Pull Request template

## Purpose / Description
 Actionbar icon is dissapearing after syncing

## Fixes
Fixes #9081

## Approach
This is a case when their is no change in collection or if their is a error while scyncing. I have done bit investigation and found out that this issue is occuring after this PR #8666 . !colIsOpen() is turned as true and their is no refreshing of action bar in this perticular case and we are seeing no icons in actionbar.

## How Has This Been Tested?

Samsung Galaxy M51 (API 30)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-06-27 13:29 UTC, mikehardy requested changes
This is one of those little UI things that bugs me too so I appreciate your taking it up
I'm not sure about the placement of the new state change or if we can avoid new state entirely though - I'd really prefer not to add new member variable state if possible

2021-06-27 13:29 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
>                  if (data.data[2] != null && !"".equals(data.data[2])) {
How strange - I don't understand how this can be in the right place, I just reproduced the issue on my personal device and the message after sync was "collection synchronized" but the icons were gone.

How can putting extra state in the failure case of the if/else fix the problem in the success case?

2021-06-27 13:29 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private boolean mMenuIsRefreshable = false;
If we add state to the object in the form of a member new member variable, then we have a higher mental load when thinking about the object (you have just increased the universe of possible state combinations by `^2`!) plus you need to add it to the Bundle onSaveInstanceState and re-hydrate it in onCreate

For those reasons I always try very very hard to think of some way to avoid adding new state, either by using existing state or by making it unnecessary.

In this case I think it would be best to make it unnecessary. Specifically, what if - in the sync code - if the sync was successful in the no change case it reopened the collection as it's last act? Then `!isColOpen` would return true :thinking:

2021-06-28 08:09 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    // Check to refresh menu actionbar (used in onPrepareOptionMenu)
Small fix for method name: Should have been `onPrepareOptionsMenu`.

2021-06-29 09:08 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private boolean mMenuIsRefreshable = false;
>  if the sync was successful in the no change case it reopened the collection as it's last act? Then !isColOpen would return true thinking

yes it's is the correct case

2021-06-29 09:48 UTC, david-allison-1 reviewed
Could you add a regression test here?

There's a lot of complex logic in the Deck Picker, and being able to pinpoint the issue will:

* Allow us to more safely refactor the syncing code
* Guard against regressions

2021-06-29 09:59 UTC, prateek-singh-3212 commented
I have just one question that . Shall I open the collection if case lies in `!data.success` is true. Would their will be any issue further?

2021-06-29 10:01 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private boolean mMenuIsRefreshable = false;
This is case :- When user is synced the data and message is 'No Changes Found'  then all the collections are closed. So after this whatever we do on deckpicker activity it will not refresh menu

2021-06-29 10:21 UTC, prateek-singh-3212 commented
`if (!colIsOpen()) {
            return false;
        }    }`
Is their is any strong reson for using this ? I don't found any error after removing this.

2021-06-29 13:14 UTC, mikehardy commented
> `if (!colIsOpen()) { return false; } }`
> Is their is any strong reson for using this ? I don't found any error after removing this.

That's what git blame is for:

https://github.com/ankidroid/Anki-Android/blame/a8f67d51fcc1eec5d67572416240ddb9b25bb878/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L691

leads to https://github.com/ankidroid/Anki-Android/pull/8666

So if you alter that line you need to make sure it is still consistent with the expectations there. It may be possible to do that more easily than any other change by doing a permission check in combination with the previous version of the code

Your testing experience of "it works for me" is a dangerous line of thought vs git blame inspection - most of the errors we are finding and fixing now are very rare corner cases - things that are not obvious - so I rarely trust my own local testing very far anymore other than to verify that I have not broken things completely

2021-06-29 13:17 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private boolean mMenuIsRefreshable = false;
I think this is behavior that may be changed - it seems correct to reopen the databases after sync if sync was successful (no change or otherwise). However David is right to request testing in the area as the sync code is very difficult to touch without breaking things. I think this gives us two possible avenues to a fix here, that does not involve adding state to the DeckPicker

- alter the test for colIsOpen back to getColSafe but coupled with a permission check to honor the previous PR in the area
- add a unit test for this DeckPicker expectation (after a sync, the menu items are refreshed) then alter the sync code to open the database after successful sync

2021-06-30 06:25 UTC, prateek-singh-3212 commented
Sorry, I am not blaming anyone.

2021-06-30 12:40 UTC, mikehardy commented
Oh no! It is literally a feature in git that they have named "blame" :laughing:  no worries / no offense, and please `git blame` people frequently :-)

With that in mind please re-read my comment - it was sincerely intended to help

2021-06-30 18:03 UTC, prateek-singh-3212 commented
Oh! My bad 🤣 .

2021-07-17 09:25 UTC, prateek-singh-3212 commented
@mikehardy Sorry taking time in this PR. I am planning to switch to `getColSafe `. I am not getting any storage exception anymore. To be safer side I will check the storage permission first and then execute the `getColSafe`.

What are your thoughts on this ?

2021-07-17 09:25 UTC, prateek-singh-3212 commented
@mikehardy Sorry taking time in this PR. I am planning to switch to `getColSafe `. I am not getting any storage exception anymore. To be safer side I will check the storage permission first and then execute the `getColSafe`.

What are your thoughts on this ?

2021-07-17 09:30 UTC, prateek-singh-3212 commented
@mikehardy Sorry taking time in this PR. I am planning to switch to `getColSafe `. I am not getting any storage exception anymore. To be safer side I will check the storage permission first and then execute the `getColSafe`.

What are your thoughts on this ?

2021-07-17 15:23 UTC, mikehardy commented
I'd prefer not to have more permissions checks scattered around, especially as permissions should go away shortly with the migration to scoped storage. I believe getColSafe with a null check is best here. It should work basically every time or be safe if not

2021-07-17 15:38 UTC, david-allison-1 commented
Would it be possible to get some logs here so we can understand the order of operations that lead to this issue?

My understanding is that `colIsOpen()` doesn't try to open the collection, and that's the issue: we can try to open the collection via `getCol`, but we need to know the best place to do this.

2021-07-17 16:01 UTC, mikehardy commented
I think getColSafe is fine here, I looked into this one thoroughly before when I spelunked for the git blame earlier. The sync closes the collection and leaves it closed, and there's no reason opening it here (or trying to: getColSafe) could harm system state or violate expectations I think. And in the case it doesn't work (probably just for disk corruption reasons, at that point, since they were able to sync already...) then the failure case is a null is there and we return, and...we have the same issue we have now which is just that the ActionBar doesn't re-initialize which is already released to users and thus not a regression.

Seems like an "easy and done" deal.

2021-07-19 12:09 UTC, david-allison-1 reviewed
Looks good! Quick comment and good to go

2021-07-19 12:09 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        // Don't use colIsOpen() instead getColSafe() because it cause #9081 issue
The comment should explain that there's a chance that the collection is not open at this point, so `colIsOpen()` is not sufficient

2021-07-19 12:48 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        // Don't use colIsOpen() instead getColSafe() because it cause #9081 issue
`using colIsOpen() is not right choice because in the case of sync failure collection is not open. ` works ?

2021-07-19 14:10 UTC, mikehardy reviewed
Enough bikeshedding on this one - I proposed what I think is a minimal / complete comment, I'll commit it, then squash merge the PR and we can all move on. Thanks @Akshay0701  :-)

2021-07-19 14:10 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        // using colIsOpen() is not right choice because in the case of sync failure collection is not open.
```suggestion
        // #9081: sync leaves the collection closed, thus colIsOpen() is insufficient, carefully open the collection if possible
```

2021-07-19 14:11 UTC, mikehardy approved these changes

2021-07-19 14:12 UTC, merged

2021-07-19 17:00 UTC, david-allison-1 commented
Thanks!

2021-08-05 15:42 UTC, mikehardy commented
Hi there!

If you're already submitted something to OpenCollective for PRs merged in July 2021, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for July 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month)

Thanks!