Preferences constant
ankidroid/Anki-Android pull request #9157
Opened 2021-06-27 16:28 UTC by Arthur-Milchior

The goal here is to ensure that each preference get a comment explaining their purpose. Using a string constant ensure that the javadoc can be found from any place where the constant is used

2021-06-27 19:08 UTC, david-allison-1 approved these changes
LGTM

2021-06-27 19:08 UTC, david-allison-1 requested changes
Should have checked the checks

2021-06-27 19:10 UTC, david-allison-1 commented
Can we also avoid having dependencies from `libAnki` -> `anki`

2021-06-27 19:38 UTC, david-allison-1 approved these changes
LGTM

2021-06-27 19:38 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +     * Note that "timeLim" is in second while TIME_LIMIT is in minute.
```suggestion
     * Note that "timeLim" is in second while TIME_LIMIT is in minutes.
```

2021-06-30 13:42 UTC, mikehardy approved these changes
Possible collision with #9080 - we'll see - either way @Akshay0701 should probably use a constant in your PR now (it's always something, I swear that PNG paste PR will land though - it is so close!)

2021-06-30 13:42 UTC, merged