Implemented ImageCropper library
ankidroid/Anki-Android pull request #9159
Opened 2021-06-28 08:10 UTC by Akshay0701

Fixes #8072

2021-06-28 09:10 UTC, Akshay0701 commented on gradle.properties
> -# Project-wide Gradle settings.
why this entire file changed i only removed 3 lines from this file 
![Capture](https://user-images.githubusercontent.com/52353967/123610953-b7d8f680-d81e-11eb-8584-27364748febe.PNG)

2021-06-28 12:59 UTC, ShridharGoel commented on gradle.properties
> -# Project-wide Gradle settings.
This screenshot is of `proguard-rules.pro` while this file is `gradle.properties`. You can revert the changes in this file.

2021-06-28 13:00 UTC, ShridharGoel commented on AnkiDroid/src/main/AndroidManifest.xml
> +            android:theme="@style/Base.Theme.AppCompat" />
Any reason for not using the theme which was used with the previous library?

2021-06-28 13:02 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
> +                Timber.w(error, "cropImage threw an error");
`Timber.e()` should be used here.

2021-06-28 13:59 UTC, Akshay0701 commented on AnkiDroid/src/main/AndroidManifest.xml
> +            android:theme="@style/Base.Theme.AppCompat" />
yes, in ucrop library all functionality was present on the bottom of activity i.e we used `NoActionBar` 
and in the case of [Image Cropper](https://github.com/CanHub/Android-Image-Cropper) same functionality are present in the ActionBar of activity.

2021-06-28 14:23 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
> +                String error = String.valueOf(Objects.requireNonNull(CropImage.getActivityResult(data)).getError());
I have to admit I've never understood the Object.requireNonNull programming pattern. It's just going to throw if the thing is null for whatever reason, so then there is a runtime exception and a crash. I can't see how that is ever a good thing?
Should do a real null test and handle it I think, to avoid any possibility of runtime crash

2021-06-28 14:24 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
> +                Timber.w(error, "cropImage threw an error");
I actually think a bit differently - Timber.e is for "app is in such a bad state that we need to basically restart in order to handle it", Timber.w is for "the user request failed but we can recover easily to a known state". This fits the `w` case for me - we should throw the general "something bad happened" error message (hopefully with contents of e.getMessage() as is being done here) but it's okay to move on from there.

2021-06-28 14:25 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
> +                AnkiDroidApp.sendExceptionReport(error, "cropImage threw an error");
hopefully these don't get too noisy but I am interested in seeing them in ACRA for at least a little while to see what kind of errors may happen

2021-06-28 14:27 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
> +        mViewModel.deleteImagePath();
what does `deleteImagePath` do here? Are we still able to revert if the user has canceled?

2021-06-28 14:28 UTC, mikehardy requested changes
thanks for taking this up! this has been on my medium-priority todo list for quite some time, I'm really happy you took the time to give it a go. I mostly had questions, but the null handling does concern me just a bit

2021-06-28 14:29 UTC, mikehardy commented on AnkiDroid/src/main/AndroidManifest.xml
> -            android:name="com.yalantis.ucrop.UCropActivity"
These activity changes create a real unit test failure. Did you run `./gradlew jacocoTestReport` with an emulator running locally prior to submitting? It will show the error

2021-06-28 14:34 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
> +                AnkiDroidApp.sendExceptionReport(error, "cropImage threw an error");
okay will do,

>  AnkiDroidApp.sendExceptionReport(e, "BasicImageFieldController::onActivityResult", info);

is this a right way to send report to ACRA ?

2021-06-28 14:48 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
> +        mViewModel.deleteImagePath();
here it will delete the previous "unCropped" file and will be initialized to new result file and 
incase if the user canceled then this function will not be called(so the original image will be there).

2021-06-28 16:48 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
> +                AnkiDroidApp.sendExceptionReport(error, "cropImage threw an error");
actually, I am not aware of which method is used to send a report to acra,
can you please tell me how I can do this...

2021-06-30 04:47 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
> +                    AnkiDroidApp.sendExceptionReport(error, "cropImage threw an error");;
```suggestion
                    AnkiDroidApp.sendExceptionReport(error, "cropImage threw an error");
```

2021-06-30 15:41 UTC, mikehardy requested changes
As mentioned: works well enough I want to use it exclusively now :sparkles:

2021-06-30 15:41 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
>          if (CompatHelper.getSdkVersion() > Build.VERSION_CODES.Q) { // We don't compile against 30 yet, so R symbol does not exist
I just tested this locally on API29 and API30 emulators

Congratulations @Akshay0701 ! This now appears to work better than the existing solution for Android <=10

Since we are still in the alpha cycle for 2.16 and it is less urgent / can receive more testing before release then my change to fix Android 11 before, let's go ahead and use CropImage for *all* versions.

Specifically: can you remove the version check now, and the else statement where we fallback, so that we now are using only CropImage for all versions?

2021-06-30 16:14 UTC, Akshay0701 commented
as now we moved can hub crop image implementation to all Android versions, so I think it's better to keep this in a separate commit.

2021-06-30 16:27 UTC, mikehardy approved these changes
I am happy to drop that incredibly nasty bit of code, thanks. It was always the touchiest thing and never fully supported by Android. Much better

2021-06-30 23:57 UTC, mikehardy commented
Tested locally on API21/29/30 emulators, works great on all of them - better than before (re-crop works now). This is tangible improvement for people 

@Canato congrats on a great library! We may stray over in to your area from time to time - have you had any requests for simple filters, specifically the ability to lighten / contrast (to touch up text images)? We got a request for that here, curious if you want to keep it very simple + working perfectly (a reasonable stance to take!) or if you have improvement ideas

Cheers

2021-06-30 23:57 UTC, merged

2021-07-01 05:07 UTC, Canato commented
> Tested locally on API21/29/30 emulators, works great on all of them - better than before (re-crop works now). This is tangible improvement for people 
> 
> @Canato congrats on a great library! We may stray over in to your area from time to time - have you had any requests for simple filters, specifically the ability to lighten / contrast (to touch up text images)? We got a request for that here, curious if you want to keep it very simple + working perfectly (a reasonable stance to take!) or if you have improvement ideas
> 
> Cheers

Thanks for the recognition, is a community effort cannot take the whole credit :D

Indeed, there is improvements I'm looking for. Most of my 2021 plans was related to tech debt(Kotlin, bugs, etc), my last two planned points for the year are:

- Stop using onAcitivityResult (PR is open by another member)
- Make 1 degree rotation available, not only 90/180....

After this I probably will create new goals! But if by any chance you guys feeling like dropping a PR, the community always win