Run Unit Tests in Foreground
ankidroid/Anki-Android pull request #9203
Opened 2021-07-04 22:12 UTC by david-allison-1

Requested by Arthur in https://github.com/ankidroid/Anki-Android/pull/8442#issuecomment-873667461

This implements running unit tests in the foreground using a custom scheduler. This should both reduce the flakiness of tests (as there are no race conditions for background tasks) and massively speed up the tests (as we no longer need to `sleep()`).

Original PR had the following comment:

> As requested by @mikehardy on https://github.com/ankidroid/Anki-Android/pull/7005#pullrequestreview-627234122

----

Implementation: Default to new scheduler for methods using `RobolectricTest`

Use a rule to detect `@RunInBackground`, and if it's found, default back to the old scheduler

See: https://github.com/junit-team/junit4/wiki/Rules#custom-rules, or commit messages

Supersedes #7005

----

I'd rather not support this change in the short term (above typical duties as a maintainer). I have other changes that are higher priority to me for 2.16.

This was an "alternate solution" to #7005.

2021-07-04 22:19 UTC, mikehardy requested changes
Looks great - my only comment is that `RunInBackground` exists in `src/main` - should be in `src/test` - it is only referenced from test?

2021-07-04 22:22 UTC, mikehardy commented
Just focusing on this:

> I'd rather not support this change in the short term (above typical duties as a maintainer). I have other changes that are higher priority to me for 2.16.

Understood - despite being prickly about it historically I am not actually anti-performance ;-). This is really clean though so I like it a lot, I'm happy to start driving it forward from, or collaborating with Arthur for same

2021-07-04 22:24 UTC, mikehardy approved these changes
Nice!

2021-07-04 22:27 UTC, Arthur-Milchior approved these changes
It seems quite easy to revert if required, so I'm not worried about supporting it.
Thanks for explaining how you did it with a link.

I regret the hours I spent on this feature now that I see how simple it can be. I'm really excited to accept it and can't wait to use it to run tests on my commits

2021-07-04 23:58 UTC, merged

2021-07-05 01:30 UTC, mikehardy commented
`./gradlew clean jacocoUnitTestReport --rerun-tasks`

Before: BUILD SUCCESSFUL in 3m 26s
After: BUILD SUCCESSFUL in 2m 56s

My machine is incredibly parallel so this is probably the "pathological" (i.e., less room to actually optimize) case, and thus represents a tangible speedup even for me.

How's it look to you all?

2021-07-05 15:18 UTC, david-allison-1 commented
Takes 5mins off my gym break ;)

I typically run via Android Studio rather than the commandline, convenience >> speed

```
Before: 14m8s
After: 9m34
```

2021-07-11 01:01 UTC, Arthur-Milchior commented
MappableBndingTest and BindingTest fail on my machine. Probably unrelated. java.lang.NoClassDefFoundError: org/mockito/kotlin/MockingKt

Appart from that, moved from 8 minutes to 3 minutes and a half. Really happy about it. Still sad it was not done earlier. That I did not explain quickly enough the blocking point to allow David to take over

2021-07-11 01:10 UTC, david-allison-1 commented
Try a gradle sync, we added this in 9f9925aa455ca526b51ca095956976753e99eadb