Paste as PNG, if alpha channel exists
ankidroid/Anki-Android pull request #9213
Opened 2021-07-06 09:38 UTC by Akshay0701

fixes #9171

code: https://stackoverflow.com/a/31311718/14148406

2021-07-06 18:33 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +                (isInputStreamContainTransparency(copyFd) || CollectionHelper.getInstance().getCol(mContext).getConf().optBoolean("pastePNG"))) {
`doesInputStreamContainTransparency`

2021-07-06 18:33 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +            inputStream.skip(12 + 4 + 4 + 4 + 1);
Could you add a StackOverflow link.

I don't understand how this works, isn't this for a specific image type (presumably all images have different headers).

2021-07-06 18:33 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +        InputStream copyFd = mContext.getContentResolver().openInputStream(uri);
you want this in a try with resources block

2021-07-08 06:57 UTC, Akshay0701 commented
okay so now we are following Anki mobile -> 
if the image is jpg we will not convert it and it will be pass as jpg format same applies for gif (for animation)
if it is png with alpha channel then we will keep that image as png otherwise we will convert that into jpg 
and all other format images will also convert in jpg.

2021-07-17 15:57 UTC, mikehardy requested changes
This seems okay but I have some structural wishes for it so that the logic and purpose were crystal clear, otherwise this code will become a real rats-nest of deep nesting and "things to remember" as a reader is reviewing it

2021-07-17 15:57 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +                }
Can you extract this method so that the conditionals and the work details have some separation - it will make the conditional / decision-making control-flow easier to follow

2021-07-17 15:57 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +                    (".png".equals(fileNameAndExtension.getValue()) && doesInputStreamContainTransparency(copyFd))) {
Can you abstract this to one method called something descriptive like `shouldConvertToJPG` ?

Then all the logic we are trying to implement will live in one well-described area

Implementation could even explain each case, e.g.:

```java
  private boolean shouldConvertToJPG(String filenameExtension, InputStream fileStream) {
    if (".jpg".equals(filenameExtension) {
      return false; // we are already a jpg, no conversion
    }
    if (".gif".equals(filenameExtension) {
      return false; // gifs may have animation, conversion would ruin them
    }
    if (...png and has transparency...) {
      return false; // pngs with transparency would be ruined by conversion
    }
    return true;
  }
```

2021-07-17 16:47 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +                    (".png".equals(fileNameAndExtension.getValue()) && doesInputStreamContainTransparency(copyFd))) {
Thank you so much for the details :)

2021-07-17 17:39 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +                }
I am sorry, but I didn't understand how can I extract this above code to the method because there are multiple variables to return,

please help...

2021-07-17 17:47 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +                }
Oh! Didn't realize it returned multiple variables, that makes it not so nice to extract. I suppose it's possible to return them as an array of Object but that is also not so nice. leave it inline for now I suppose

2021-07-17 17:48 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
> +                }
Okay, 

``` java
clipCopy = File.createTempFile(fileName, ".jpg");
bytesWritten = CompatHelper.getCompat().copyFile(fd, clipCopy.getAbsolutePath());
// return null if jpg conversion false.
if (!convertToJPG(clipCopy)) {
    return null;
}
```

i did something like this, not sure if this is right?

2021-07-17 17:50 UTC, mikehardy approved these changes
Ha, then you got the method extracted anyway - LGTM and now each method is pretty compact and makes sense on it's own, much easier to think about (for me at least)

2021-08-05 02:23 UTC, merged