Implement better download and import system for shared decks
ankidroid/Anki-Android pull request #9229
Opened 2021-07-09 06:50 UTC by ShridharGoel

## Purpose / Description
Implement better download and import system for shared decks.

## Approach
Added new Activity with WebView and used DownloadManager to download along with setting up BroadcastReceiver to check for download completion and import the downloaded deck.

## How Has This Been Tested?

Tested on API 28 and API 30 emulators.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-07-09 11:40 UTC, david-allison-1 reviewed
Looks great! Not much feedback, I think there's only nitpicks here.

Will need to try it out myself

I think we'll want to think about the "downloading" UX, maybe a progress bar rather than a `Toast`?

2021-07-09 11:40 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +            if (DownloadManager.ACTION_DOWNLOAD_COMPLETE == action) {
can you invert a few `if`s here for readability?

2021-07-09 11:40 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +                        fileIntent.setDataAndType(
Can this be simplified by delegating to `IntentHandler.class`?

2021-07-09 11:40 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +                            Timber.e(e)
```suggestion
                            Timber.w(e)
```

2021-07-09 11:40 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +                                context?.applicationContext?.packageName + ".apkgfileprovider",
Could you extract a bit of this into a named `openDownloadedDeck` method, it's difficult to grok the intention of this code from a quick skim.

2021-07-09 12:26 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +            unregisterReceiver()
This doesn't unregister the receiver if we return early, is this intended?

2021-07-09 12:26 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +    private var mOnComplete: BroadcastReceiver = object : BroadcastReceiver() {
Do we need to unregister this on any other events/situations?

2021-07-09 12:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +            downloadDeck(url, userAgent, contentDisposition, mimetype)
do we want to check to see if the deck is an `apkg` here?

2021-07-09 12:28 UTC, david-allison-1 reviewed
Sorry for the notifications, will try better next time

2021-07-09 12:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +        mDownloadId = downloadManager.enqueue(request)
What if two downloads occur? Can this be stored in the receiver?

2021-07-09 22:08 UTC, Arthur-Milchior reviewed
Note a lot to add to @david-allison-1 comment. Could you please make a short video illustrating the change.

I'd also like you to change the commit name.
> Implement better download and import system for shared decks

make sens today, But it won't make that much sens in a year, when the reader will not remember what changed occurred in 2021. That means in case of bug it will need work to reread the commit to understand it.

> Browse ankiweb shared decks in app
>
> This will allow to download decks and let ankidroid import them

2021-07-09 22:08 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
>      public void addSharedDeck() {
Could you add javadoc to give more details about what it is doing. I think it was opening a page in an external browser and now is opening another fragment, right? Then just
/**
Open the Shared Decks Activity window
*/
would suffice

I know that there was now javadoc. But as we go along, it's nice to correct code

2021-07-09 22:11 UTC, Arthur-Milchior reviewed
I've restarted the test in case it was just flaky. It failed on checkIfClickOnCountsLayoutOpensStudyOptionsOnMobile which is something I never saw before, but it does seem obviousl related to this PR either

2021-07-09 22:12 UTC, Arthur-Milchior commented
Restarted again but this time activityHandlesRestoreBackup was the failing one

2021-07-10 16:20 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +            unregisterReceiver()
It should unregister when returned early. Updated.

2021-07-10 16:20 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +        mDownloadId = downloadManager.enqueue(request)
Updated.

2021-07-10 16:20 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
>      public void addSharedDeck() {
Updated.

2021-07-11 18:54 UTC, david-allison-1 reviewed
I really like this. It's already much better.

* Would it be possible to remove the WebView after the first deck has been downloaded, and show a full-screen "download". The UX from importing multiple decks isn't good from an AnkiDroid perspective (as you need to explicitly agree to download each one).
  * this would mean that the "downloading" screen is full screen
* Could you change the "downloading" screen when the download is completed, I get an "open with app" dialog on my device (as I have multiple AnkiDroid clients installed), and it obscures the "downloading" message
  * This encourages people to close the "open with" dialog, which is what we want to avoid
* If people do close the "open with" dialog, could the post-download screen contain a button which will perform the same action to open the deck, if pressed.

2021-07-17 21:03 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +            .cancelable(true)
What does cancelling do? Is the listener disposed of?

2021-07-17 21:03 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +        val cursor = downloadManager.query(query)
can you move this into `try with resources`? I think Kotlin calls this a `use` block

2021-07-18 18:22 UTC, david-allison-1 requested changes
Code looks really nice

Could you consider making the "import deck" button fill screen, and maybe add some styling, it doesn't look very welcoming


We need to know how error handling works, and whether we can add a "try again"

Crash when cancelling a download
```
2021-07-18 19:20:23.255 5926-5926/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 5926
    java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.ichi2.anki (has extras) } in com.ichi2.anki.SharedDecksDownloadFragment$mOnComplete$1@94814c1
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1590)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: Fragment SharedDecksDownloadFragment{70a6a95} (c75e608b-1114-4e91-9c50-13ece4beb46c) not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
        at androidx.fragment.app.Fragment.getResources(Fragment.java:964)
        at androidx.fragment.app.Fragment.getString(Fragment.java:986)
        at com.ichi2.anki.SharedDecksDownloadFragment.continuePendingDownloadsOrUnregisterReceiver(SharedDecksDownloadFragment.kt:298)
        at com.ichi2.anki.SharedDecksDownloadFragment.continuePendingDownloadsOrUnregisterReceiver$default(SharedDecksDownloadFragment.kt:296)
        at com.ichi2.anki.SharedDecksDownloadFragment$mOnComplete$1.onReceive(SharedDecksDownloadFragment.kt:168)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1580)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7664) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

2021-07-18 18:24 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +            .cancelable(true)
Here is the link to the related documentation for this: https://github.com/afollestad/material-dialogs/blob/main/documentation/CORE.md#dismissing

This is not being used now, since download has been changed to full-screen as suggested.

2021-07-18 18:27 UTC, ShridharGoel commented
@david-allison-1 Fixed the crash. Can you check again?

2021-07-18 18:35 UTC, david-allison-1 commented
No crashes! Seems great

2021-07-18 19:16 UTC, ShridharGoel commented
@david-allison-1 Please have a look at the updated UI of the download screen.

2021-07-20 12:59 UTC, david-allison-1 requested changes
Looks good, probably another couple rounds of reviews

This wants a few more `Timber.i()` calls explaining the logic/state of the application, don't use it for debug information, and keep paths out of `Timber.i` or higher as these can be a privacy risk.

Can some testing/comments be added to see what happens if the app is minimised?

2021-07-20 12:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                view?.findViewById<TextView>(R.id.download_percentage)?.text = getString(R.string.percentage, downloadProgress.toInt())
Could you use 1 decimal place here?

2021-07-20 12:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        Timber.i("File URI -> $fileUri")
```suggestion
        Timber.d("File URI -> $fileUri")
```

2021-07-20 12:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            Timber.i("Download ID -> $mDownloadId")
again, this is debug info, so `Timber.d`, and only if you feel it will be useful to a developer debugging a problem

2021-07-20 12:59 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml
> +    <TextView
I think too much user choice is bad here, it adds a lot of complexity to the code, and I don't see the benefit.

I think keeping the "downloading" screen open while the file downloads is acceptable, and informing users that they can use other apps while the download occurs.

@mikehardy @Arthur-Milchior opinions?

2021-07-21 21:26 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml
> +        tools:text="This is how the title will look when a file with a long file name will be downloading" />
I think you want string ressources

2021-07-21 21:28 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml
> +        tools:text="This is how the title will look when a file with a long file name will be downloading" />
`tools:text` is only used in the designer as a sample of the content, it's fine outside a resource

2021-07-24 22:17 UTC, david-allison-1 requested changes
* Update the UI maybe once every 1/10 second. Progress updates are too slow
* When cancelling a download, don't use "yes/no", use "Cancel/Continue" as buttons: 
  *  https://material.io/components/dialogs#simple-dialog - Don’t use action text that fails to indicate what the selection will do. 
* Maybe 0% for 0%, not 0.0%

Other than that, implementation looks good, mostly nits

Main issue is ensuring that this is safe from exceptions

2021-07-24 22:17 UTC, david-allison-1 commented on AnkiDroid/src/main/AndroidManifest.xml
> +            android:exported="true" />
Do we want to export this?

2021-07-24 22:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +        when {
logging: `Timber.i` on each case. We want to get an idea about the user flow through the screen

2021-07-24 22:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        Timber.i("Registering broadcast receiver for download completion")
This feels like a `Timber.d` - it's an implementation detail rather than a user flow.

If we use `Timber.i`, go with `"starting file download"` or similar

2021-07-24 22:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        mCancelButton.setOnClickListener {
Useful to log the button presses here

2021-07-24 22:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                Timber.i("Download ID did not match with the ID of the completed download")
Very good, possibly a `Timber.w` (might need elaboration, if this is listening to all downloads then it's a regular occurrence) 

Also explain the outcome (presumably file won't be opened)

2021-07-24 22:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            if (action != DownloadManager.ACTION_DOWNLOAD_COMPLETE) {
We've stopped the download progress checker here, what does this mean if the download isn't complete?

Does "not complete" mean "pending", or that an error has definitely occurred? Needs better commenting

2021-07-24 22:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                Timber.i("Download is not complete")
This isn't enough information to go off

2021-07-24 22:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                    Timber.i("Empty cursor")
Can this be elaborated on?

2021-07-24 22:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                val columnIndex: Int = it.getColumnIndex(DownloadManager.COLUMN_STATUS)
What if this throws?

2021-07-24 22:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        Timber.i("Unregistering receiver")
```suggestion
        Timber.d("Unregistering receiver")
```

2021-07-24 22:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            Timber.i("Checking download status and unregistering receiver")
```suggestion
            Timber.d("Checking download status and unregistering receiver")
```

2021-07-24 22:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        const val DOWNLOAD_PROGRESS_CHECK_DELAY = 1000L
```suggestion
        const val DOWNLOAD_PROGRESS_CHECK_DELAY = 100L
```

2021-07-24 22:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        Timber.i("Starting download progress checker")
```suggestion
        Timber.d("Starting download progress checker")
```

2021-07-24 22:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        if (!mIsProgressCheckerRunning) {
invert the if for a reduction in nesting

2021-07-24 22:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        Timber.i("Stopping download progress checker")
```suggestion
        Timber.d("Stopping download progress checker")
```

2021-07-24 22:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                checkDownloadStatusAndUnregisterReceiver()
The method call doesn't imply that this is a failure case, possibly explicitly add args

2021-07-24 22:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            Timber.i("Broadcast receiver's onReceive() called")
Again, make this more understandable without the technical details - log the "what" not the implementation,

If there's a bug, having a good handle on the order of operations that a user took helps

2021-07-24 22:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            Timber.i("Broadcast receiver's onReceive() called")
Likely extract to an inner method and handle uncaught exceptions

2021-07-24 22:19 UTC, david-allison-1 requested changes
I'm impressed that this handles turning off Wifi, maybe consider a warning (or add a TODO for a future implementation)

2021-07-24 22:30 UTC, david-allison-1 commented
There should be a button in the UI which performs a "close this Webview", if I cancel a download, I need to press back 4/5 times to get back to the Deck Picker

2021-07-24 23:30 UTC, Arthur-Milchior reviewed
Only a few nit. Nothing to add to David. Thanks a lot for this work, it seems really great

2021-07-24 23:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/AndroidManifest.xml
> +            android:exported="true" />
I'd say no. Because if we export it, we should also test that it actually works, that if you open SharedDecksActivity from another app, import is done correctly. Seems a nightmare to actually test correctly. Since we don't expect anybody to use this export for quite some time, we won't even know if it gets broken until long after the break.

Seems a lot of potential problem and no discernable gain

2021-07-24 23:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +    override fun onBackPressed() {
I would appreciate a comment that indicate in plain English what you decided to do.
I think it's something as:

> If there is a download, ask whether it should be cancelled. If download ended, remove the fragment. Otherwise, go back in the view if possible, otherwise closet he webview.

By the way, is there a way for the user to quickly remove the webview entirely and go back to the deck picker, or must they reload in page in reverse order?

2021-07-24 23:30 UTC, Arthur-Milchior commented on AnkiDroid/src/main/res/values/strings.xml
> +    <bool name="ga_anonymizeIp">true</bool>
why did you move those two resources?

2021-07-25 12:11 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +     * When the deck download is completed successfully, open the .apkg file in AnkiDroid to import it.
In my opinion, this sentence mix two related topics. When it is supposed to be called and what it do. It seems that the method itself ensure that it get executed when the download is succesful, which is not the case.

So I'd go with

> If mFileName is apkg or colpkg, import it in AnkiDroid
> this should be called when the download completed succesfully

2021-07-25 12:11 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +    private var mFileName: String = ""
Could you please help me understand why you use a default value instead of lateInit.
My understanding is that you'll assign it only once, so I'd even assume a lateinit would be more correct semantically.

2021-07-25 12:11 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                if (mDownloadId != intent?.getLongExtra(DownloadManager.EXTRA_DOWNLOAD_ID, 0)) {
Do you know how it can happen? And if so, whether the other download is dealt with in any way by some broadcast receiver?

2021-07-25 12:11 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +     * When the deck download is completed successfully, open the .apkg file in AnkiDroid to import it.
In my opinion, this sentence mix two related topics. When it is supposed to be called and what it do. It seems that the method itself ensure that it get executed when the download is succesful, which is not the case.

So I'd go with

> If mFileName is apkg or colpkg, import it in AnkiDroid
> this should be called when the download completed succesfully

2021-07-25 12:28 UTC, david-allison-1 requested changes

2021-07-25 12:28 UTC, david-allison-1 commented on AnkiDroid/src/main/AndroidManifest.xml
> +            android:label="@string/menu_get_shared_decks"
This is now visible on the action bar. Change to "download deck" or similar

2021-07-25 12:28 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="cancel_download">Cancel Download</string>
Just use "cancel" and "continue" for the buttons. Use "Cancel download?" for the title

2021-07-25 12:28 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="deck_download_progress_message">You can use other apps while the download is running. Once the download completes, a dialog would open to let you import the deck.</string>
```suggestion
    <string name="deck_download_progress_message">You can use other apps while the download is running</string>
```

2021-07-25 12:28 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="previous_download_running_message">Download will start when the previous download completes.</string>
```suggestion
```

2021-07-25 12:28 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="cancel_confirmation">Are you sure you want to cancel the download?</string>
Just use the title. Less text is better

2021-07-25 12:28 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="cannot_import">Cannot import since file is not a deck</string>
We already have a similar string used in the import screen. Consider using this

2021-07-25 12:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        context?.let {
If the download completes, and the dialog is shown, remove it.

2021-07-25 12:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                    mDownloadManager.remove(mDownloadId)
Selecting "cancel" failed and crashed

```
2021-07-25 13:24:39.584 21179-21179/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 21179
    java.lang.IllegalArgumentException: Receiver not registered: com.ichi2.anki.SharedDecksDownloadFragment$mOnComplete$1@326f993
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1459)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1642)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:715)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:715)
        at com.ichi2.anki.SharedDecksDownloadFragment.unregisterReceiver(SharedDecksDownloadFragment.kt:229)
        at com.ichi2.anki.SharedDecksDownloadFragment.showCancelConfirmationDialog$lambda-7$lambda-5(SharedDecksDownloadFragment.kt:355)
        at com.ichi2.anki.SharedDecksDownloadFragment.lambda$t8e6bXd8yYwAAXryUECPrQDOBp8(Unknown Source:0)
        at com.ichi2.anki.-$$Lambda$SharedDecksDownloadFragment$t8e6bXd8yYwAAXryUECPrQDOBp8.onClick(Unknown Source:2)
        at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:410)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

2021-07-25 12:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                val downloadProgress: Float = downloadedBytes * 1f / totalBytes * 100
This can show `-0.0%`

2021-07-25 12:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            } while (it.moveToNext())
I don't see why this would loop, could it be turned into an `if`?

2021-07-25 12:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                UIUtils.showThemedToast(activity, R.string.cannot_import, false)
logging here would be useful

2021-07-25 14:50 UTC, david-allison-1 commented
Optional: could the progress bar be made taller? It feels like there should be more emphasis on it

2021-07-25 16:30 UTC, ShridharGoel commented on AnkiDroid/src/main/res/values/strings.xml
> +    <bool name="ga_anonymizeIp">true</bool>
Seems like it had happened automatically through Android Studio. Reverted.

2021-07-25 16:31 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            if (action != DownloadManager.ACTION_DOWNLOAD_COMPLETE) {
Removed this since it isn't required. `onReceive()` will be called when download is completed.

2021-07-25 16:31 UTC, ShridharGoel commented on AnkiDroid/src/main/res/values/strings.xml
> +    <bool name="ga_anonymizeIp">true</bool>
Seems like it had happened automatically through Android Studio. Reverted.

2021-07-25 16:32 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        if (mIsProgressCheckerRunning) {
It was there earlier for handling the case of multiple downloads. Removed.

2021-07-25 16:33 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +     * When the deck download is completed successfully, open the .apkg file in AnkiDroid to import it.
That is the case. This method gets executed when the download completes.

2021-07-25 16:33 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +    private var mFileName: String = ""
It's better to use a default value so that if in case `mFileName` gets used before it is initialised, then a crash can be prevented. It's required to ensure that `lateinit` variables are initialised before being used.

2021-07-25 16:44 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                if (mDownloadId != intent?.getLongExtra(DownloadManager.EXTRA_DOWNLOAD_ID, 0)) {
This might not happen since it has been decided to not allow the usage of the app while a download is going on. Should we still keep it as a check to be sure that the download ID matches?

2021-07-25 16:47 UTC, ShridharGoel commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="cancel_download">Cancel Download</string>
This can be confusing regarding what 'Cancel' means when asked for "Cancel download?". User might not know whether it means to cancel the download or cancel the confirmation dialog. Similar would be with 'Continue'. User might not know whether it means to continue the download or continue with the cancellation.

2021-07-25 16:48 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            } while (it.moveToNext())
I think even `if` is not required here. Updated.

2021-07-25 20:45 UTC, david-allison-1 reviewed
Only nitpicks, no complaints about the code, should be the last one

2021-07-25 20:45 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                if (!(mFileName.endsWith(APKG_EXTENSION) || mFileName.endsWith(COLPKG_EXTENSION))) {
What about `.apkg (1)` which Android will sometimes download

See: https://github.com/ankidroid/Anki-Android/blob/a3cd40ae81a09ae601506c1bdf94784ab3b5925a/AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java#L326-L335

2021-07-25 20:45 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                        Timber.i("Download could not be successful, update UI and unregister receiver")
Would be useful to log the value

2021-07-25 20:45 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            fun verifyIfDeckImportCanBeDone() {
maybe: `veifyDeckIsImportable()`

2021-07-25 20:45 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            if (it.getInt(columnIndexForStatus) == DownloadManager.STATUS_PAUSED &&
it.getInt(-1) wouldn't fail?

2021-07-25 20:45 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                activity?.onBackPressed()
Does this work if it's overridden?

2021-07-25 20:45 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="percentage">%s %%</string>
```suggestion
    <string name="percentage">%s%%</string>
```

2021-07-25 20:45 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="cancel_download">Cancel download</string>
Use "cancel/continue" without the "download"

```suggestion
```

2021-07-25 20:45 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="continue_download">Continue Download</string>
```suggestion
```

2021-07-25 20:45 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="download_deck">Download Deck</string>
```suggestion
    <string name="download_deck">Download deck</string>
```

2021-07-25 20:45 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +        super.onCreate(savedInstanceState)
It would be nice to add a "search" to the action bar, which resets to the default URL

2021-07-25 21:05 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                // Return if file doesn't have extension as .apkg or .colpkg
> Halt if file doesn't have extension as apkg or colpkg

The command is indeed called "return". However, we are not actually returning anything, what we actually do is halt the execution here

2021-07-25 21:05 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +     * Checks download progress and updates status, then re-schedules itself.
"Check download progress" 
(I suspect we don't want the third person here)

2021-07-25 21:05 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +     * Opens the downloaded deck using its file name.
> Open the downloaded deck saved in `mFileName`

"its file name" is not clear unless you already know the class architecture

2021-07-26 15:06 UTC, david-allison-1 requested changes
No more features I can suggest, this is so much more clean

**Feedback**

* Uses the light theme in Dark mode
   * Caused by the above ~~None of the text (progress/"you can use another app") is visible any more~~

2021-07-26 15:06 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +            override fun onQueryTextSubmit(query: String?): Boolean {
I love the search!!!!

![](https://media.giphy.com/media/xTQXENNW77nUsNVmV4/giphy.gif)

2021-07-26 15:06 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                -1
can't you return here instead of below?

2021-07-26 16:41 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +            override fun onQueryTextSubmit(query: String?): Boolean {
Thank you!

2021-07-26 16:42 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                Timber.w(exception)
Updated to call `checkDownloadStatusAndUnregisterReceiver()` and return.

2021-07-26 16:43 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                it.close()
Should not be required, removed.

2021-07-26 16:43 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                -1
It can be done, updated.

2021-07-26 17:33 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="cancel_download">Cancel Download</string>
@Arthur-Milchior @mikehardy 

Maybe "Cancel/Resume"?

2021-07-26 18:13 UTC, ShridharGoel commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="cancel_download">Cancel Download</string>
Using 'Resume' would seem like the download is in paused state till the dialog is open.

2021-07-26 20:37 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="cancel_download">Cancel Download</string>
Hmm...

"Cancel Download" -> "Stop Download? [CONTINUE] [STOP]"?

2021-07-26 20:51 UTC, david-allison-1 reviewed
Seems great!

This doesn't work on an API 21 emulator, but neither does the website

![image](https://user-images.githubusercontent.com/62114487/127057433-21f897ec-b89c-4c62-8c26-bcb0366fdfd4.png)
![image](https://user-images.githubusercontent.com/62114487/127057439-acbe86c4-4c68-4bbd-842d-bb1eb5a2d953.png)

2021-07-26 20:51 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +    private val mWebViewClient = object : WebViewClient() {
can't we clear the history immediately?

2021-07-26 20:51 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        val downloadFile = arguments?.getSerializable("DownloadFile") as DownloadFile
rename variable to `fileToDownload`, having a method the same as the class was confusing

2021-07-26 20:51 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        request.setDestinationInExternalFilesDir(context, Environment.DIRECTORY_DOWNLOADS, currentFileName)
thought: accepting a `DownloadFile` would allow you to move this code into a function which is `DownloadFile -> Request`

2021-07-26 20:51 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml
> +    <TextView
Use `FixedTextView` in all of your xml files

2021-07-27 15:37 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="cancel_download">Cancel Download</string>
I like the general idea of continue/stop, however "stop" is now inconsistent as a verb
If the call to action is "cancel download" (which is a good verb, I think), then the question should be "Cancel Download?" and the confirmation call to action should again be "cancel"

2021-07-27 19:26 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +    private val mWebViewClient = object : WebViewClient() {
No, history should not be cleared before the page finishes loading otherwise there would be an extra entry in the history since the previous page would not get cleared.

2021-07-27 21:24 UTC, david-allison-1 approved these changes
Beautiful, thanks so much!

2021-07-27 21:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +data class DownloadFile(
Could use a quick comment on what this is

2021-07-27 21:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        val fileToBeDownloaded = arguments?.getSerializable("DownloadFile") as DownloadFile
extract the constant as it's used between classes

2021-07-27 21:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            Timber.w(e)
move the comment here, and be a bit more explicit that the exception is ignored. Maybe with a `return`

2021-07-27 21:24 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            Timber.w(e)
Maybe a "something went wrong" toast as well

2021-07-31 01:40 UTC, Arthur-Milchior approved these changes
Really great.
I tried it. Really love the way it works. Except that now my collection got plenty of decks I'm not interested in.

There are a few unanswered questions by David. I think I found one error in error management. Also I'd love to know more about the catching of Exception. Usually it's bad practice. But I don't actually know whether you know more specifically what kind of exception you expect to get

I approve. I'd like you to answer David, and maybe correct the error I saw; should be trivial. I'm fine with merging after that

2021-07-31 01:40 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        } catch (e: Exception) {
Do you know what exceptions can be thrown? I checked by removing the try catch and got `IllegalArgumentException`. is there anything else? Generally, it's nice to catch just what you need.

2021-07-31 01:40 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            } catch (e: Exception) {
Can you please help me understand this try/catch.
My understanding of the javadoc is that it returns -1 if it is not found. 
You may have wanted `getColumnIndexOrThrow`; In which case you'd catch `IllegalArgumentException`

But I think you can just do 

```kotlin
val columnIndexForStatus= it.getColumnIndex(DownloadManager.COLUMN_STATUS)
val columnIndexForReason = it.getColumnIndex(DownloadManager.COLUMN_REASON)
if (columnIndexForReason == -1 || columnIndexForStatus == -1) {
  Timber.w("Missing a column")
  return
}

2021-07-31 01:40 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            } catch (exception: Exception) {
Same question. Do you have any idea what kind of exception you're expecting here? I'm not really happy with catching everything. Some thing maybe important actually.

2021-07-31 01:44 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +data class DownloadFile(
Just the class I feel

2021-07-31 16:40 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +     * The terminology
Yes.

2021-07-31 16:42 UTC, ShridharGoel commented
> There are a few unanswered questions by David.

Found only this one which seemed to require an answer: https://github.com/ankidroid/Anki-Android/pull/9229#discussion_r676199548
Rest are either already answered or already updated.

> I think I found one error in error management.

Can you tell which one is that?

2021-07-31 16:43 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +                                context?.applicationContext?.packageName + ".apkgfileprovider",
Not sure about what exceptions could be thrown here. It was suggested by @david-allison-1 to add a try-catch block for this code, so maybe he might have better idea.

2021-07-31 16:52 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +    private var mOnComplete: BroadcastReceiver = object : BroadcastReceiver() {
This was done earlier.

2021-07-31 16:54 UTC, ShridharGoel commented on AnkiDroid/src/main/res/values/strings.xml
> +</resources>
Updated.

2021-07-31 16:54 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +     * Method to set the request for downloading a deck.
Updated.

2021-07-31 16:54 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +     * When the deck download is completed successfully, open the .apkg file in AnkiDroid to import it.
Updated.

2021-07-31 16:55 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +     * When the deck download is completed successfully, open the .apkg file in AnkiDroid to import it.
Updated.

2021-07-31 16:56 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                // Return if file doesn't have extension as .apkg or .colpkg
Yes, updated it later.

2021-07-31 16:56 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +     * Checks download progress and updates status, then re-schedules itself.
Updated.

2021-07-31 16:56 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +     * Opens the downloaded deck using its file name.
Updated.

2021-07-31 16:56 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        val fileToBeDownloaded = arguments?.getSerializable("DownloadFile") as DownloadFile
Updated.

2021-07-31 16:56 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +        } catch (e: Exception) {
Updated.

2021-07-31 16:56 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            } catch (e: Exception) {
Updated.

2021-07-31 16:57 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            } catch (exception: Exception) {
Updated.

2021-07-31 16:57 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                -1
Updated.

2021-07-31 17:03 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            } catch (exception: Exception) {
Not sure what exceptions could be thrown from here. It was suggested by @david-allison-1 so he might be having better idea.

2021-07-31 17:09 UTC, ShridharGoel commented on AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml
> +    <TextView
This was implemented accordingly.

2021-07-31 17:10 UTC, ShridharGoel commented
> There are a few unanswered questions by David.

Found this one which seemed to require an answer: https://github.com/ankidroid/Anki-Android/pull/9229#discussion_r676199548
Rest are either already answered or already updated. I have replied to the review comments which were taken into consideration and code was updated but were not marked as resolved or which could have a reply even though they were marked as resolved.

> I think I found one error in error management.

Can you tell which one is that?

2021-08-01 21:09 UTC, Arthur-Milchior commented
> Can you tell which one is that?

I was referring to: https://github.com/ankidroid/Anki-Android/pull/9229#discussion_r680284712

2021-08-04 22:36 UTC, mikehardy requested changes
I think this looks great, and it will be loved by users in a big way, especially new users. Getting the first shared deck into your fresh + new AnkiDroid install is one of the biggest hurdles to a good first experience and this should solve it.

My only question is about how we post the Intent to do the import after downloading it, and whether that can be done differently

2021-08-04 22:36 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +            context?.startActivity(fileIntent)
I have a question - here it appears we are just sending the file URI and the type to the system to attempt an import via a generic `Intent.ACTION_VIEW`. There have been reports that for whatever reason the system does not always seem to register AnkiDroid as a handler for apkg/colpkg, and it's one of the common complaints from users on import failures

We know what activity does our import though, we control it. Why aren't we directly starting that activity with the intent? Or, am I misunderstanding things?

2021-08-05 00:36 UTC, Arthur-Milchior commented
I like it. Just tested it and really practical. I'm fine with merging it. 
When it downloads, I see the thankidroid logo again, as if the app was restarting. It looks like a bug, since this is the usual time when the logo reappear. Not ideal, but acceptable.  I suspect that following @mikehardy would solve it.

Personally, I'd be fine with merging, and then applying Mike's idea later if there remain time before the end of GSoC, and prioritizing onboarding. Unless @ShridharGoel you believe it's quick to solve, in which case i'd be happy for you to go fix it

2021-08-05 00:39 UTC, david-allison-1 commented
> When it downloads, I see the thankidroid logo again, as if the app was restarting. It looks like a bug, since this is the usual time when the logo reappear. Not ideal, but acceptable. I suspect that following @mikehardy would solve it.

Could you get a logcat, that's normally a crash

2021-08-05 02:00 UTC, mikehardy commented
Yeah - it's either a crash (logcat will show) or specifying the wrong activity transition animation.

Or! My specific question about how we are doing a system intent vs starting an activity might be that the system is then "starting Anki" so you get the startup logo as if it was a cold start. That question was in my review comments.

2021-08-05 17:15 UTC, ShridharGoel commented
> Why aren't we directly starting that activity with the intent?

The reason is that the task here is to import the deck. For that `Intent.ACTION_VIEW` is being used and then `setDataAndType()` method is being used to set the mime type. Is there a better way of doing this?

2021-08-05 17:17 UTC, ShridharGoel commented
> Why aren't we directly starting that activity with the intent?

The reason is that the task here is to import the deck. For that `Intent.ACTION_VIEW` is being used and then `setDataAndType()` method is being used to set the mime type. Can this be done when directly starting the DeckPicker?

2021-08-05 17:20 UTC, mikehardy commented
I think you want to make the same Intent, but you want to start the Activity directly, not send it to the system. I believe the activity to target internally is the one that handles ACTION_VIEW, i.e. `IntentHandler` - which has that Intent action set in it's filters https://github.com/ankidroid/Anki-Android/blob/2bee386507d22a2b72f60acb66fac7232f45dfe5/AnkiDroid/src/main/AndroidManifest.xml#L87

This way we maintain complete control - we are sending the intent directly to our known / controlled Activity, vs just flinging it out to the system and hoping it comes back (plus dealing with the Activity transitions that happen as the system puts it on the stack etc). if the transitions still happen then perhaps we find where our IntentHandler forwards to and then using that activity as the target... 

https://github.com/ankidroid/Anki-Android/blob/2bee386507d22a2b72f60acb66fac7232f45dfe5/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java#L62

...appears that would be more of a structural change as IntentHandler directly orchestrates it:

https://github.com/ankidroid/Anki-Android/blob/2bee386507d22a2b72f60acb66fac7232f45dfe5/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java#L139

So just using IntentHandler may be sufficient?

2021-08-05 17:28 UTC, ShridharGoel commented
@mikehardy Do you mean doing something like this?

https://github.com/ankidroid/Anki-Android/blob/2bee386507d22a2b72f60acb66fac7232f45dfe5/AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.java#L206-L209

2021-08-05 17:52 UTC, mikehardy commented
Yes! Exactly like that

2021-08-05 18:39 UTC, ShridharGoel commented
It doesn't work. Here is the code:

```
private fun openDownloadedDeck(context: Context?) {
    val mimeType = URLConnection.guessContentTypeFromName(mFileName)
    val fileIntent = Intent(context, IntentHandler::class.java)
    fileIntent.type = Intent.ACTION_VIEW
    fileIntent.addCategory(Intent.CATEGORY_LAUNCHER)

    val fileUri = context?.let {
        FileProvider.getUriForFile(
            it,
            it.applicationContext?.packageName + ".apkgfileprovider",
            File(it.getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS), mFileName.toString())
        )
    }
    Timber.d("File URI -> $fileUri")
    fileIntent.setDataAndType(fileUri, mimeType)
    fileIntent.flags = Intent.FLAG_ACTIVITY_NEW_TASK
    try {
        context?.startActivity(fileIntent)
    } catch (e: ActivityNotFoundException) {
        UIUtils.showThemedToast(context, R.string.something_wrong, false)
        Timber.w(e)
    }
}
```

Is something else required?

2021-08-05 18:43 UTC, ShridharGoel commented
@david-allison-1 had also mentioned about using `IntentHandler` earlier but the plan was dropped at that time.

2021-08-05 18:44 UTC, ShridharGoel commented
Updated it.

2021-08-05 19:45 UTC, mikehardy commented
"It doesn't work" makes no sense. If sending an Intent to the system, and then the system calls IntentHandler works, how on earth can skipping the system part and just sending it directly the Activity *not* work.

- "Doesn't work" - exactly what fails?
- What does unfiltered logcat say?
- What does IntentHandler do / what happens in there when it gets the Intent?

I'm really surprised on this one, and defies my understanding of how Android works

2021-08-05 20:00 UTC, mikehardy approved these changes
Really nice!

2021-08-05 20:01 UTC, merged

2021-08-05 20:30 UTC, david-allison-1 commented
I'm really excited to see this in. Thanks so much @ShridharGoel 

![](https://media.giphy.com/media/l3q2XhfQ8oCkm1Ts4/giphy.gif)

2021-08-06 05:26 UTC, ShridharGoel commented
@david-allison-1 @Arthur-Milchior @mikehardy Thanks!