[Feature] JavaScript Addons Support - npmjs addon package download (Part 1)
ankidroid/Anki-Android pull request #9232
Opened 2021-07-09 15:55 UTC by infinyte7

## Pull Request template

## Purpose / Description
Using AnkiDroid JS API a deck can be extended to implement features like progress bar or custom card layouts. But it requires user to manually add the ```html/css/js``` to card templates. This is implementation for a way to inject code to all deck templates when addons get activated.

This addon will be implemented in three part
1. package download/extract/copy from npmjs
2. List packages from directory
3. Add enabled addons content to reviewer

## Fixes
Fixes #7959 

## Approach

This implemented using [CompletableFuture](https://developer.android.com/reference/java/util/concurrent/CompletableFuture).

1. Download addons from https://www.npmjs.com/search?q=keywords:ankidroid-js-addon inside the app
2. In app there are implementation to check for valid addons for AnkiDroid
It will check following string in latest package.json
```
{
    "name": "ankidroid-js-addon-progress-bar",
    "version": "1.0.0",
    "author": "https://github.com/infinyte7",
    "homepage": "https://github.com/infinyte7/Anki-Custom-Card-Layout",
    "ankidroidJsApi": "0.0.1",
    "addonType": "reviewer",
    "keywords": ["ankidroid-js-addon"]
}
```
Note: `ankidroid_js_api` and `addon_type` changed to `ankidroidJsApi` and `addonType`

There `isValidAnkiDroidAddon` boolean function will check for above values if present then the addons is valid.

I have also documented it here https://github.com/infinyte7/ankidroid-js-addon

There are two types of addon ```reviewer``` and ```note_editor```. 
In this PR, first part of reviewer addon is implemented.

## How Has This Been Tested?
Tested on emulator and devices

<img src="https://user-images.githubusercontent.com/12841290/125104634-2f0c6580-e110-11eb-8035-f5991550db71.gif" height=450px></img>

 

## Learning (optional, can help others)
https://developer.android.com/reference/java/util/concurrent/CompletableFuture
https://www.callicoder.com/java-8-completablefuture-tutorial/

## Checklist
_Please, go through these checks before submitting the PR._

- [ x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x ] You have commented your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code
- [ x ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-07-09 18:01 UTC, david-allison-1 reviewed
First quick look over - tests are failing

To discuss with the others @mikehardy @Arthur-Milchior: I don't think we should be implementing a second type of concurrency primitive in this PR. As much as I dislike AsyncTask, until we actively pick the new direction, we shouldn't fragment how we implement concurrency

2021-07-09 22:13 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.java
> +    public CompletableFuture<String> getTarball(String addonName) {
I tried on API 21 emulator, it works.

2021-07-09 22:13 UTC, infinyte7 commented on AnkiDroid/build.gradle
> +    implementation 'org.rauschig:jarchivelib:1.1.0'
I tried to implement this using code from stackoverflow. I think this library far better than my implementations. 
Also it is easy to use.

2021-07-09 22:15 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.java
> +    public CompletableFuture<String> getTarball(String addonName) {
I have tested it on API 21 emulator and it is working.

2021-07-09 22:23 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.java
> +                ObjectMapper mapper = new ObjectMapper()
It will fail if any fields in json change by NPM org. 
The only field that depend this PR is getting tarball url to download .tgz file. 
That file only can be downloaded from https://registry.npmjs.org/

Other fields like `ankidroidJsApi` and `addonType` distinguish from other npm packages.

So, for backward compatible JSONObject will be used to parse only required fields when above fails.

2021-07-10 10:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonBrowser.java
> +    }
You shouldn't need this. Just return `this`

2021-07-10 10:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.java
> +                Timber.d(e.getLocalizedMessage());
Use `.w` typically

2021-07-10 10:27 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/NpmPackageDownloaderTest.java
> +public class NpmPackageDownloaderTest {
```java
public class NpmPackageDownloaderTest extends RobolectricTest {
```

2021-07-10 10:27 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/NpmPackageDownloaderTest.java
> +        context = mAddonBrowser.getContext();
```java
        context = getContext();
```

2021-07-10 10:27 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/NpmPackageDownloaderTest.java
> +        mAddonBrowser = new AddonBrowser();
You typically want to use RobolectricTest here

```
 super.startActivityNormallyOpenCollectionWithIntent(AddonBrowser.class, new Intent());
```

2021-07-10 10:27 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/NpmPackageDownloaderTest.java
> +        init();
If you call init on each call, move it to `@Before`

2021-07-10 10:27 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/NpmPackageDownloaderTest.java
> +        shadowOf(getMainLooper()).idle();
typically: `advanceRobolectricLooperWithSleep`

2021-07-10 10:27 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/NpmPackageDownloaderTest.java
> +        CompletableFuture<String> result1 = mNpmPackageDownloader.getTarball(validAddonName);
@Arthur-Milchior @mikehardy 

What's our opinion on having tests depend on internet resources? I'm against this as-is (as it exposes us to failures from systems that we can't control).

I'd be OK if these were informational, rather than failing the build (maybe a separate test category + warning on GitHub, rather than a straight test failure).

2021-07-10 10:27 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/NpmPackageDownloaderTest.java
> +        CompletableFuture<String> result1 = mNpmPackageDownloader.getTarball(validAddonName);
@Arthur-Milchior @mikehardy 

What's our opinion on having tests depend on internet resources? I'm against this as-is (as it exposes us to failures from systems that we can't control).

I'd be OK if these were informational, rather than failing the build (maybe a separate test category + warning on GitHub, rather than a straight test failure).

2021-07-10 12:04 UTC, infinyte7 commented on AnkiDroid/src/test/java/com/ichi2/anki/NpmPackageDownloaderTest.java
> +        CompletableFuture<String> result1 = mNpmPackageDownloader.getTarball(validAddonName);
I forget to remove this. Because CompletableFuture is removed from the class but not from test. I will remove it.

2021-07-10 15:43 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/DownloadAddonBackgroundTask.java
> +public abstract class DownloadAddonBackgroundTask {
This doesn't seem to use our async framework either

2021-07-10 16:02 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/DownloadAddonBackgroundTask.java
> +public abstract class DownloadAddonBackgroundTask {
Yes, I will implement using TaskDelegate.

2021-07-11 07:40 UTC, infinyte7 commented
This PR is finally implemented using TaskDelegate with test.

2021-07-12 22:10 UTC, infinyte7 commented
Added `Install addon` to custom tabs menu. 

It will works as follows
1. Get uri data from intent
2. Check if the url is starts with `https://www.npmjs.com/package/`
3. Then get addon's name from url
4. Check if the addon is valid for AnkiDroid
4. Download the addons

<img heigh=450px src="https://user-images.githubusercontent.com/12841290/125361820-73159980-e3a0-11eb-8eca-7d200bc98376.png"></img>

2021-07-13 03:08 UTC, Arthur-Milchior reviewed
You wrote 
> to all deck templates
I don't understand it. Do you mean "card type's template"? 

In your video, how is the user supposed to know what to enter and in which folder to go? 
In particular, it's confusing to call it the name of the add-on while it's a command line. 

Ideally, if there is a simpler way to deal with it, I'd prefer you take a real name. If it can't be done, then call it something else than "name".

Can you edit the first message, so that I know the current state of the code without having to check the latest comment.

I'd be great if you can rework the commit history. It seems that it's useless to read the sequence of commit one by one right now, and the whole change is so big it's hard to review. I probably forgot many comments,

2021-07-13 03:08 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.java
> +        private final String mAddonName;
Can you please indicate what you call addonName? Is it the command entered by the user (in this case, starting with "nmp", is it the uri, is it the part computed by the name function?

2021-07-13 03:08 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/NpmPackageDownloaderTest.java
> +        CompletableFuture<String> result1 = mNpmPackageDownloader.getTarball(validAddonName);
I thought that we already depended a lot on web, as we download things. I assume that the website we download from can afford it, even if its not efficient. Is github putting any limitation?
I'd clearly love to be as realistic as possible, so I find it cool to be tested actually.

I'm okay with informational failure, but I fear that it will be missed in the quantity of information, the ignored test, the long text printed.

2021-07-13 06:13 UTC, infinyte7 commented
> You wrote
> 
> > to all deck templates
> > I don't understand it. Do you mean "card type's template"?
> 
> In your video, how is the user supposed to know what to enter and in which folder to go?
> In particular, it's confusing to call it the name of the add-on while it's a command line.
> 

The contents of addon in this code javascript code added to reviewer to any decks. i.e. any card templates.

> Ideally, if there is a simpler way to deal with it, I'd prefer you take a real name. If it can't be done, then call it something else than "name".
> 

`name` is npm package name. This is in package.json of npm package.

> Can you edit the first message, so that I know the current state of the code without having to check the latest comment.
> 

I will edit the first commit. I have implemented this PR with `CompletableFuture` then implemented using `TaskDelegate` and removed `CompletableFuture`

> I'd be great if you can rework the commit history. It seems that it's useless to read the sequence of commit one by one right now, and the whole change is so big it's hard to review. I probably forgot many comments,

I will rewrite the commit history. The PR is started from `Re-implemented using TaskDelegate and added test` commit, all the previous commit can be ignored because that used `CompletableFuture`

2021-07-13 06:21 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/DownloadAddonAsyncTaskListener.java
> +    void addonShowProgressBar();
It is previous commit and it is updated.
From this commit `Re-implemented using TaskDelegate and added test`, I have implemented using TaskDelegate and TaskListener.

2021-07-13 06:22 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/DownloadAddonAsyncTaskListener.java
> +public interface DownloadAddonAsyncTaskListener {
I have implemented using extending TaskListener. It is old commit.

2021-07-13 06:22 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.java
> +    public CompletableFuture<String> downloadAddonPackageFile(String tarballUrl, String addonName) {
It is removed. Please review it from `Re-implemented using TaskDelegate and added test` commit.

2021-07-13 06:25 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.java
> +        // extracting using library https://github.com/thrau/jarchivelib
I will implement using `org.apache.commons.compress`. There is nothing wrong.

2021-07-13 10:48 UTC, infinyte7 commented
It seems hard to remove the older commit without removing reviewed message. 
Finally It has be done. This is clean PR with new commits. It only contains TaskDelegate and TaskListener.
All the previous implementation like (CompletableFuture, thread and other implementation removed from the commit history).

2021-07-13 10:49 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.java
> +        public boolean extractAndCopyAddonTgz(String tarballPath, String npmAddonName) {
I will add the test for this function.

2021-07-13 10:57 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.java
> +            // extracting using library https://github.com/thrau/jarchivelib
Using `org.apache.commons.compress` there is need to implement the same thing that `jarchivelib` does.

2021-07-13 10:58 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +            Intent intent = new Intent(this, DownloadAddonBroadcastReceiver.class);
I have javadoc explaining the openUrl function. It may need to add more details.

2021-07-13 10:59 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonInfo.java
> +@SuppressLint("NonPublicNonStaticFieldName")
javadoc added.

2021-07-13 10:59 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonInfo.java
> +     * if package.json of ankidroid-js-addon... contains valid ankidroid_js_api = 0.0.1 and keywords 'ankidroid-js-addon'
I have simplified the javadoc.

2021-07-13 11:04 UTC, infinyte7 commented on AnkiDroid/build.gradle
> +    implementation 'org.rauschig:jarchivelib:1.1.0'
Using `org.apache.commons.compress` there is need to implement the same thing that `jarchivelib` does.
Also `jarchivelib` uses `org.apache.commons.compress`.

2021-07-13 11:05 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonBrowser.java
> +    public boolean onCreateOptionsMenu(Menu menu) {
javadoc added to `onCreateOptionsMenu`

2021-07-13 11:07 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/DownloadAddonBroadcastReceiver.java
> +        if (addonName.contains("/")) {
I will the test for the funtion

2021-07-13 17:51 UTC, infinyte7 commented
>I thought that we already depended a lot on web, as we download things. I assume that the website we download from can afford it, even if its not efficient. Is github putting any limitation?
```
Use of npm Open Source
Subject to these Terms, npm grants you permission to use npm Open Source. That permission is not exclusive to you,
and you cannot transfer it to anyone else.

Your permission to use npm Open Source entitles you to do the following:

You may search for, download, publish, and manage packages of computer code (Packages) in the Public Registry,
and otherwise interact with the Public Registry, via the command-line tool published by npm at 
https://www.github.com/npm/npm (the CLI).

You may search for, download, publish, and manage Packages using software other than CLI via application 
programming interfaces that npm publicly documents or makes available for public use (Public APIs).

You may search for and manage Packages in the Public Registry, and otherwise interact with the Public Registry, 
via the Website.

You may update and manage your Account via the Website.

You may visit, create an account for, and participate in, discussions on npm.community.
```

2021-07-17 06:29 UTC, Arthur-Milchior commented
> > You wrote
> > > to all deck templates
> > > I don't understand it. Do you mean "card type's template"?
> > 
> > 
> > In your video, how is the user supposed to know what to enter and in which folder to go?
> > In particular, it's confusing to call it the name of the add-on while it's a command line.
> 
> The contents of addon in this code javascript code added to reviewer to any decks. i.e. any card templates.

I beg your pardon, you quote two questions I asked and give a single answer. It seems to ignore my second question, can you please answer it?

Also, what is the relation between deck and card template? Usually, there are none

> 
> > Ideally, if there is a simpler way to deal with it, I'd prefer you take a real name. If it can't be done, then call it something else than "name".
> 
> `name` is npm package name. This is in package.json of npm package.

In this case, why does the name in your screen capture example start by "name -i"?

> > Can you edit the first message, so that I know the current state of the code without having to check the latest comment.
> 
> I will edit the first commit. I have implemented this PR with `CompletableFuture` then implemented using `TaskDelegate` and removed `CompletableFuture`

Sorry, in this case, I was not speaking of commit message. I understand the ambiguity. I was mentionning the first PR message. That is, what we see at the top of https://github.com/ankidroid/Anki-Android/pull/9232  that starts by "Pull Request template"

By the way, it's not a problem if we loose some code comment in github. Either they are adressed and it's great. Or they are not, and we can redo them when we see the problem still exists.

> > I'd be great if you can rework the commit history. It seems that it's useless to read the sequence of commit one by one right now, and the whole change is so big it's hard to review. I probably forgot many comments,
> 
> I will rewrite the commit history. The PR is started from `Re-implemented using TaskDelegate and added test` commit, all the previous commit can be ignored because that used `CompletableFuture`

THanks

2021-07-17 07:30 UTC, infinyte7 commented
> > > You wrote
> > > > to all deck templates
> > > > I don't understand it. Do you mean "card type's template"?
> > > 
> > > 
> > > In your video, how is the user supposed to know what to enter and in which folder to go?
> > > In particular, it's confusing to call it the name of the add-on while it's a command line.
> > 
> > 
> > The contents of addon in this code javascript code added to reviewer to any decks. i.e. any card templates.
> 
> I beg your pardon, you quote two questions I asked and give a single answer. It seems to ignore my second question, can you please answer it?
> 

The same command copy from npmjs.org pasted inside edit text. But in later implementation, I added a menu to Custom tabs so, user do not need to copy it. They just have to visit the npmjs package then click 'Install Addon` from options menu. 


> Also, what is the relation between deck and card template? Usually, there are none
> 
> > > Ideally, if there is a simpler way to deal with it, I'd prefer you take a real name. If it can't be done, then call it something else than "name".
> > 
> > 
> > `name` is npm package name. This is in package.json of npm package.
> 
> In this case, why does the name in your screen capture example start by "name -i"?
> 

I have written so that user may find what should be entered from npmjs package. But it will be removed and replaced with Custom tabs menu. It is more simpler than copying command from npmjs.

> > > Can you edit the first message, so that I know the current state of the code without having to check the latest comment.
> > 
> > 
> > I will edit the first commit. I have implemented this PR with `CompletableFuture` then implemented using `TaskDelegate` and removed `CompletableFuture`
> 
> Sorry, in this case, I was not speaking of commit message. I understand the ambiguity. I was mentionning the first PR message. That is, what we see at the top of #9232 that starts by "Pull Request template"
> 
> By the way, it's not a problem if we loose some code comment in github. Either they are adressed and it's great. Or they are not, and we can redo them when we see the problem still exists.
> 
> > > I'd be great if you can rework the commit history. It seems that it's useless to read the sequence of commit one by one right now, and the whole change is so big it's hard to review. I probably forgot many comments,
> > 
> > 
> > I will rewrite the commit history. The PR is started from `Re-implemented using TaskDelegate and added test` commit, all the previous commit can be ignored because that used `CompletableFuture`
> 
> THanks

I have explained the commit message, also added test cases for almost all functions.

2021-07-17 07:56 UTC, Arthur-Milchior reviewed
I've just reviewed the firs commit, I may go onto other commits later, but it's already big and hard to review.

I would really really love smaller commits, which introduce a single feature, such as extracting tgz or getting the name of add-on. This way, if we merge those features quickly, it mean the remaining of the PR is quick to review, as I'll only review the parts that we could not merge quickly first

2021-07-17 07:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonBrowser.java
> +                mNpmAddonName = mNpmAddonName.replaceAll("\u00A0", "");
Can you please explain this line. 
I can't figure out:
* why you want to consider non-breakable space especially
* whether there is any realistic risk for the user to enter them
* why do you want to delete them. If by accident a user use a non-breakable space, you probably expect a space in the first place
* why it is done AFTER trimming. If you have a space, a non-breakable space, a space, then you'll still have the last space at the end of this code. Probably not what you expect

Can you write down exactly what is the definition of a name, what is the expectation?  Maybe it could help more

2021-07-17 07:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonBrowser.java
> +public class AddonBrowser extends NavigationDrawerActivity implements DeckDropDownAdapter.SubtitleListener {
Can you please add a javadoc explaining what it is. 
If this "only" contains a window taking a name, why do we need a new `NavigationDrawerActivity`? It seems that this kind of menu can be put on top of the deck picker or of any other place where it would be relevant

2021-07-17 07:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +     * Open url using custom tabs. It opens url in AnkiDroid if web browser supported devices. For some devices it is not
> I didn't know custom tabs. I'd appreciate a small explanation. 
> 
> Open provided url in a custom tab. That is, in a chrome tab controlled by ankidroid. If it is not possible, show a toast and do nothing else.
>
> For urls starting with https://www.npmjs.com, chrome menu will have an extra button "Install addon"

Also, can you please either state what "Install addon" will do, or link to a comment explaining it. E.g. using `see {@code DownloadAddonBroadcastReceiver}`

2021-07-17 07:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +        if (url.toString().startsWith("https://www.npmjs.com/")) {
Are you sure you want to capture only https and not http?

2021-07-17 07:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonInfo.java
> +    private String name;       // name of npm package, it unique for each package listed on npm
please start member name by m. So it should be `mName` for example

2021-07-17 07:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonInfo.java
> +    public String getName() {
I still don't understand the point here. You have `name` for example that you never set and that you can get. What is the point?
I'm not sure thit class should be in this commit isValidAnkiDroidAddon, as it seems that it is self contained

2021-07-17 07:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/DownloadAddonBroadcastReceiver.java
> +        if (addonName.contains("/")) {
I am really sorry, but I don't understand your answer.

In particular, it seems not to answer the fact that 
> // may be addon name ends with slash

mention the end of the name, while your code look for slash at any position

2021-07-17 07:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/DownloadAddonBroadcastReceiver.java
> +    private String getAddonName(@NonNull String url) {
Would you mind adding unit test for this method please?

2021-07-17 07:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/DownloadAddonBroadcastReceiver.java
> +    private String getAddonName(@NonNull String url) {
I think the method may be static. It does not seems to require any context. That's not really important, but usually good practice. In particular for unit test. Also if you want to add this method and related test in its own commit, before adding the actual receiver

2021-07-17 07:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/DownloadAddonListener.java
> +public class DownloadAddonListener extends TaskListener<Void, String> {
Up to now, all listeners where internal classes defined near the place where they are used. Maybe you can look at other part of the code to see how its done. It's not really important, but I'd appreciate consistency

2021-07-17 07:56 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/NpmPackageDownloaderTest.java
> +        CollectionTask<Void, String> ct = TaskManager.launchCollectionTask(new NpmPackageDownloader.DownloadAddon(context, validAddonPackageName));
I'm sorry, you'll need to add some casting, because now  launchCollectionTask returns a Cancellable.

Also, I think that you should test directly the DownloadAddon without going through the task itself. Both test might be useful, but in this case, I don't see the point of adding the Task Manager complexity since you want to  test the DownloadAddon logic

2021-07-17 07:56 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/NpmPackageDownloaderTest.java
> +        CollectionTask<Void, String> ct = TaskManager.launchCollectionTask(new NpmPackageDownloader.DownloadAddon(context, validAddonPackageName));
Same remark below

2021-07-17 07:56 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/NpmPackageDownloaderTest.java
> +    private final String inValidAddonName = "fs";
`private final static String INVALID_ADDON_NAME`

Since it's a constant and their name are all upper case
Same below please

2021-07-17 07:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.java
> +                ObjectMapper mapper = new ObjectMapper()
I don't get your discussion.
Since you set the configuration not to fail on unknown property, it should work even if the properties change in the future

2021-07-17 07:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.java
> +            } catch (JsonParseException | JsonMappingException | MalformedURLException e) {
Still relevant

2021-07-17 07:56 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/NpmPackageDownloaderTest.java
> +    public void inValidAddonTest() throws ExecutionException, InterruptedException {
`invalidAddonTest`

2021-07-17 07:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.java
> +         *                       extract downloaded .tgz files and copy to AnkiDroid/addons/ folder
This last javadoc line seems a copy of the first one. Should it be deleted maybe?

2021-07-17 07:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.java
> +        public boolean extractAndCopyAddonTgz(String tarballPath, String npmPackageName) {
Can you please test it? I suspect it would need to add an add-on tgz in the embedded test and run the method on them.

2021-07-17 07:56 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.java
> +        public boolean extractAndCopyAddonTgz(String tarballPath, String npmPackageName) {
This is also a method that, I believe, can be static, to simplify unit testing. And can be added in its own commit, with its own unit test. This would alow for smaller commits, it would allow to merge some of them quicker, and do future review more easily

2021-07-17 07:59 UTC, Arthur-Milchior commented
Oops, sorry, as I review commit by commit, I missed that you added test. I would appreciate if you could add tests in the same commit than the code they test.

If you want, we can take an hour at some point in time and pair code, so that at the very least I can discuss what I'd expect of commits. Because while they are split, they are not split in the way we usually do

2021-07-17 08:00 UTC, Arthur-Milchior commented
Also, I'd really love you to update the screen captured in the top of this page. Because I'd like to see the current version of the implementation. My questions were really related to the fact that your screen capture in the PR description contains "npm i"

2021-07-17 16:32 UTC, mikehardy commented
This is an important feature that I really want, but no feature with 99 comments and +1500 lines of code in a single commit is okay. That is just not okay. I actively fear even looking at this. I avoid it.

This must be separated into even smaller things to  be digestible - from my/our perspective there are more than 70 open PRs right now that all need attention, and 2 students working on Google Summer of Code that need lots of attention, along with regular release cycles and bugs and user feedback etc.

Reviewing a +1500 line commit that gets pushed multiple times per day is just not possible, I can't do it. I wish I could but I cannot.

When I see this text:

```
This implemented using TaskDelegate and jackson.
Jackson used to fetch latest package json then it parse to AddoInfo. There is isValidAnkiDroidAddon boolean function will check the addons is valid or not.

    Download addons from https://www.npmjs.com/search?q=keywords:ankidroid-js-addon inside the app
    In app there are implementation to check for valid addons for AnkiDroid
    It will check following string in latest package.json

{
    "name": "ankidroid-js-addon-progress-bar",
    "version": "1.0.0",
    "author": "https://github.com/infinyte7",
    "homepage": "https://github.com/infinyte7/Anki-Custom-Card-Layout",
    "ankidroidJsApi": "0.0.1",
    "addonType": "reviewer",
    "keywords": ["ankidroid-js-addon"]
}

Note: ankidroid_js_api and addon_type changed to ankidroidJsApi and addonType

I have also documented it here https://github.com/infinyte7/ankidroid-js-addon

There are two types of addon reviewer and note_editor.
In this PR, first part of reviewer addon is implemented.
```

I think of commits (maybe completely separate PRs) in chunks like:

- Add method to parse package.json to AddonInfo with tests
- Implement isValidAnkiDroidAddon boolean function will check the addons is valid or not with tests
- Implement remote package fetch from npmjs.org with tests
- Implement local package unpack with test (handle corrupt zip / pathological zip attack case)
- Implement display of locally unpacked reviewer add-on packages with enabled/disable/delete status / actions
- Implement npmjs.org remote query and result display with test (make sure network unavailable case is handled)
- Orchestrate remote query+display / remote select+download+unpack+validate / reviewer add on list display / integrate

Each of those is a reasonably separate feature, at the very least east to reason about as a separate commit

2021-07-17 16:59 UTC, infinyte7 commented
Yes, This PR is big. It needs split further. Currently I am doing that. I will mark it as draft for now. When PR split is done. I will mark it for Review. Thanks

2021-07-18 15:01 UTC, infinyte7 commented
I have added contents to `Pull Request Template` explaining all the PR. 
I have considered all the reviewed message in this PR and implemented and split the PR.

2021-07-19 10:52 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.java
> +                ObjectMapper mapper = new ObjectMapper()
Yes, it would work. Because in JSONObject implementation that can not be solved. If these fields in top of package.json then it will work. 
The PR is implemented according to this https://docs.npmjs.com/cli/v7/configuring-npm/package-json .

2021-07-19 10:57 UTC, infinyte7 commented on AnkiDroid/src/test/java/com/ichi2/anki/NpmPackageDownloaderTest.java
> +        CompletableFuture<String> result1 = mNpmPackageDownloader.getTarball(validAddonName);
The website will handle it, because this PR are not scrapping the website. In this PR user visit the npm package page as they visit in browser, then click 'Install Addon', here package.json downloaded for the package and tarball link extracted. 
The same thing happen in nodejs cli in PC.

2021-07-19 11:07 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/DownloadAddonBroadcastReceiver.java
> +        if (addonName.contains("/")) {
Packages URL have two variants. In this case  `valid-ankidroid-js-addon-test` string needs to extract. I have updated the functions.
```java
    // valid npm package url
    private val NPM_PACKAGE_URL = "https://www.npmjs.com/package/valid-ankidroid-js-addon-test"

    // valid npm package url with version
    private val NPM_PACKAGE_URL_WITH_VERSION = "https://www.npmjs.com/package/valid-ankidroid-js-addon-test/v/1.0.0"

    // valid npm package url with ?activeTab
    private val NPM_PACKAGE_URL_WITH_TAB = "https://www.npmjs.com/package/valid-ankidroid-js-addon-test?activeTab=versions"

```

2021-07-19 11:08 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/DownloadAddonBroadcastReceiver.java
> +            String[] s = addonName.split("/");
I tried it, it didn't work. I will try again.

2021-07-19 11:08 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.java
> +            } catch (JsonParseException | JsonMappingException | MalformedURLException e) {
I have updated Exception handling. Move to base exception class which extends those exceptions.

2021-07-19 11:09 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonBrowser.java
> +/****************************************************************************************
I have implemented the PR in kotlin also tests are in kotlin.

2021-07-19 11:10 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonBrowser.java
> +     * @param menu
I have removed edit text. Now package name will taken from npm package url.
Also updated screenshots.

2021-07-19 11:11 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonBrowser.java
> +                if (mNpmAddonName.startsWith("npm i")) {
This is used in edit text. I have removed it. Now, package name taken from url.

2021-07-19 11:15 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonBrowser.java
> +                mNpmAddonName = mNpmAddonName.replaceAll("\u00A0", "");
Now, package name taken from URL.

2021-07-19 11:15 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonBrowser.java
> +public class AddonBrowser extends NavigationDrawerActivity implements DeckDropDownAdapter.SubtitleListener {
Added doc to `AddonBrowser`

2021-07-19 11:15 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +     * Open url using custom tabs. It opens url in AnkiDroid if web browser supported devices. For some devices it is not
Added `see {@code DownloadAddonBroadcastReceiver}` to docs.

2021-07-19 11:16 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +        if (url.toString().startsWith("https://www.npmjs.com/")) {
Yes, because Android seems fetch resources on `https`

2021-07-19 11:18 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonInfo.java
> +    private String name;       // name of npm package, it unique for each package listed on npm
I have used `name` to make it consistent with `package.json`. Using mName also works. But package.json is mapped to this class So, I think the fields in the json should match with variable in the class.

2021-07-19 11:19 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonInfo.java
> +    public String getName() {
Now, getter function removed.

2021-07-19 11:19 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/DownloadAddonBroadcastReceiver.java
> +    private String getAddonName(@NonNull String url) {
I have added test for it. And implemented it in kotlin

2021-07-19 11:20 UTC, infinyte7 commented on AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/NpmPackageDownloaderTest.java
> +        CollectionTask<Void, String> ct = TaskManager.launchCollectionTask(new NpmPackageDownloader.DownloadAddon(context, validAddonPackageName));
Moved to Listener moved extended TaskDelegate class

2021-07-19 11:21 UTC, infinyte7 commented on AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/NpmPackageDownloaderTest.java
> +    private final String inValidAddonName = "fs";
All the constant in this PR are named in capital case.

2021-07-19 11:23 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.java
> +        public boolean extractAndCopyAddonTgz(String tarballPath, String npmPackageName) {
I moved each class with their test in single commit.

2021-07-19 11:24 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.java
> +        public boolean extractAndCopyAddonTgz(String tarballPath, String npmPackageName) {
Tests are added for almost functions.

2021-07-19 11:25 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.java
> +         *                       extract downloaded .tgz files and copy to AnkiDroid/addons/ folder
Updated.

2021-07-19 11:33 UTC, infinyte7 commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/jsaddons/NpmPackageTgzExtractTest.java
> +    public void unTarTest() throws IOException, ArchiveException {
I will update in next commits.

2021-08-24 02:53 UTC, david-allison-1 requested changes
Right now, the UX on the download could do with improving. It's very hard to find the "install addon" button.

Once we find the "install" button, most of the listed addons on NPM don't install, 

Is there a way to filter NPM to only addons which are available, then by star rating (/etc..) to avoid addons which don't work?

We might need to use the same technique that the "Shared Decks Download" uses here.

2021-08-24 02:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonBrowser.kt
> +        // TODO
flagging a TODO

2021-08-24 02:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageTgzExtract.java
> +            File outputFile = new File(outputDir, entry.getName());
This appears to be vulnerable to zipslip: https://snyk.io/research/zip-slip-vulnerability

2021-08-24 02:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageTgzExtract.java
> +        TarArchiveInputStream tarInputStream = (TarArchiveInputStream) new ArchiveStreamFactory()
Use a try with resources block here

2021-08-24 02:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageTgzExtract.java
> +                if (!outputFile.exists()) {
It would be useful to extract the exists...makedir...exception into a method for readability

2021-08-24 02:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageTgzExtract.java
> +                final OutputStream outputFileStream = new FileOutputStream(outputFile);
try with resources, you likely want to use AnkiDroid's compat for copying streams

2021-08-24 02:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmUtils.kt
> +    // TODO Extract to resources from other classes
flagging TODO

2021-08-24 02:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmUtils.kt
> +        if (addonModel.name == null || addonModel.addonTitle == null || addonModel.main == null ||
It feels like we should move this to `addonModel.isValid()`

2021-08-24 02:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmUtils.kt
> +        for (keyword in addonModel.keywords) {
can be simplified. pseudocode:

```kotlin
val jsAddonKeywordsPresent = addonModel.keywords.contains(ANKIDROID_JS_ADDON_KEYWORDS)
val jsAddonKeywordsPresent = addonModel.keywords.any { it == ANKIDROID_JS_ADDON_KEYWORDS }
```

2021-08-24 02:53 UTC, david-allison-1 commented on AnkiDroid/src/main/res/menu/navigation_drawer.xml
> +            android:id="@+id/nav_addons"
Let's hide this for now, until all functionality is complete.

Maybe make it visible only in debug mode?

2021-08-24 02:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +            }  else if (itemId == R.id.nav_addons) {
To discuss: I don't think we should enable this until all functionality (Flashcard Viewer)

2021-08-24 02:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +@SuppressLint("NonPublicNonStaticFieldName")
You should be able to remove this if you rebase onto master

2021-08-24 02:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.kt
> +                Timber.e(e.localizedMessage)
`Timber.w` here

2021-08-24 02:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.kt
> +                val addonModel = mapper.readValue(URL(mContext.getString(R.string.npmjs_registry, mNpmPackageName)), AddonModel::class.java)
Do we want to fail on unknown values?

2021-08-24 02:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/DownloadAddonBroadcastReceiver.kt
> +    override fun onReceive(context: Context, intent: Intent) {
Explain in documentation when this is triggered

2021-08-24 02:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/DownloadAddonBroadcastReceiver.kt
> +class DownloadAddonBroadcastReceiver : BroadcastReceiver() {
Explain the high-level intent

2021-08-24 02:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmUtils.kt
> +    fun isvalidAnkiDroidAddon(addonModel: AddonModel): Boolean {
`isValid`

2021-08-24 02:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.kt
> +                val mapper = ObjectMapper()
This needs to be extracted, it doesn't read as "download the URL into this JSON object"

you might want to extract `URL(mContext.getString(R.string.npmjs_registry, mNpmPackageName)` as a parameter to download.

Is concatenation safe here? When we're downloading executable files, we need to assume that a user will be malicious. Do we need to URLEscape or similar?

2021-08-24 02:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.kt
> +            } catch (e: JacksonException) {
Do we want to provide the exception message in a toast here?

2021-08-24 02:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.kt
> +            if (tarballPath == null) {
Can't you just make it a `String` rather than a `String?`

2021-08-24 03:04 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.java
> +                ObjectMapper mapper = new ObjectMapper()
It feels that the issue is that NPM are already at v7, they'll happily go to v8, and when they do, it forces all AnkiDroid clients to update, or thre'll be broken.

2021-08-24 11:36 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.kt
> +            } catch (e: JacksonException) {
The return in catch block returns message string to `onPostExecute` of TaskDelegate Listener class and from there error or success message toast shown.

2021-08-24 11:36 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.kt
> +                val mapper = ObjectMapper()
Implemented, now download take url as parameter
Url escape to be implemented

2021-08-24 11:36 UTC, infinyte7 commented on AnkiDroid/src/main/res/menu/navigation_drawer.xml
> +            android:id="@+id/nav_addons"
Implemented, for release the `Addon` menu will be hidden in side nav

2021-08-24 11:36 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmUtils.kt
> +        for (keyword in addonModel.keywords) {
Implemented, It is good to seed kotlin is so clean and easy

2021-08-24 11:36 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmUtils.kt
> +        if (addonModel.name == null || addonModel.addonTitle == null || addonModel.main == null ||
Moved to AddonModel class

2021-08-24 11:36 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageTgzExtract.java
> +                final OutputStream outputFileStream = new FileOutputStream(outputFile);
I have tried it but I think `TarArchiveInputStream` is not implemented. It needs to convert to input stream then copy. 
So, `IOUtils.copy` may be better here?

![屏幕截图(21)](https://user-images.githubusercontent.com/12841290/130608850-5d3bf4ed-a83f-455a-b37c-adbcef631656.png)

2021-08-24 11:36 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageTgzExtract.java
> +                if (!outputFile.exists()) {
Extracted to two function unTarDir and unTarFile

2021-08-24 11:36 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageTgzExtract.java
> +            File outputFile = new File(outputDir, entry.getName());
Implemented and added zip safety check code

2021-08-24 11:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +}
Kotlin has extension functions, and you may be able to define a real function on the data class, both work. 

The non-extension function would be better.

This code needs the `@param` fixing, and was done in GitHub, so may need a change to compile.

You can likely remove the `this.` references to make the code more readable, I don't recall (Kotlin is new to me)

```

/**
 * Check if npm package is valid or not by fields ankidroidJsApi, keywords (ankidroid-js-addon) and
 * addon_type (reviewer or note editor) in addonModel
 *
 * @param addonModel mapped readvalue of fecthed npm package.json
 * @return true for valid addon else false
 */
fun AddonModel.isValidAnkiDroidAddon(): Boolean {
	// either fields not present in package.json or failed to parse the fields
	if (this.name == null || this.addonTitle == null || this.main == null ||
		this.ankidroidJsApi == null || this.addonType == null || this.homepage == null ||
		this.keywords == null
	) {
		return false
	}

	// if fields are empty
	if (this.name.isEmpty() || this.addonTitle.isEmpty() || this.main.isEmpty() ||
		this.ankidroidJsApi.isEmpty() || this.addonType.isEmpty() || this.homepage.isEmpty()
	) {
		return false
	}

	// check if ankidroid-js-addon present or not in mapped addonModel
	val jsAddonKeywordsPresent = this.keywords.any { it == ANKIDROID_JS_ADDON_KEYWORDS }

	// addon package.json should have js_api_version, ankidroid-js-addon keywords and addon type
	return (
		this.ankidroidJsApi == NpmUtils.ANKIDROID_JS_API && jsAddonKeywordsPresent &&
			(this.addonType == NpmUtils.REVIEWER_ADDON || this.addonType == NpmUtils.NOTE_EDITOR_ADDON)
		)
}

```

2021-08-24 12:04 UTC, david-allison-1 commented
Something went wrong with the merge, needs a rebase to `master` before a full re-review

2021-08-24 12:05 UTC, infinyte7 commented
I am trying to resolve the conflict.

2021-08-24 12:19 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +}
So, what should be done? I didn't understand it. Should I move back to `NpmUtils`?

2021-08-24 17:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +        var url = resources.getString(R.string.shared_decks_url)
We should ideally be using a different activity or fragment here rather than enhancing the Shared Decks Activity with code which isn't relevant to shared decks.

2021-08-24 17:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                if (!ImportUtils.isFileAValidDeck(mFileName) || !ImportUtils.isFileAValidTgz(mFileName)) {
ditto - merging two different concerns isn't ideal from a maintainability perspective (you don't want screen Y to break if you change X).

See what you can abstract out from here

2021-08-24 17:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +    private fun extractDownloadFile(context: Context?) {
make `context` non-null (or figure out why it can be null, and fix it), there's no point in calling this with a null contex.

2021-08-24 17:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +fun AddonModel.isValidAnkiDroidAddon(): Boolean {
Awesome! Can this not be added as a method?

2021-08-24 17:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/DownloadAddonBroadcastReceiver.kt
> +        // TaskManager.launchCollectionTask(DownloadAddon(context, addonName), DownloadAddonListener(context))
?

2021-08-24 17:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.kt
> +                    "javascript:(function () { var html = document.body.innerHTML.toString(); " +
What's the purpose of this code?

2021-08-24 17:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.kt
> +            if (result != null) {
If result is null, return early.

Should result ever be null?

2021-08-24 17:14 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.kt
> +                    "javascript:(function () { var html = document.body.innerHTML.toString(); " +
This add a button to webview when there is keywords `ankidroid-js-addon` in html page.

2021-08-24 17:15 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/DownloadAddonBroadcastReceiver.kt
> +        // TaskManager.launchCollectionTask(DownloadAddon(context, addonName), DownloadAddonListener(context))
This code will be removed when I reused the code from shared deck PR.

2021-08-24 17:16 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
> +        var url = resources.getString(R.string.shared_decks_url)
Yes, It will be better I am implementing separate  activity or fragment for this.

2021-08-24 17:22 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
> +                if (!ImportUtils.isFileAValidDeck(mFileName) || !ImportUtils.isFileAValidTgz(mFileName)) {
Yes, It will be better I am implementing separate activity or fragment for this.

2021-08-25 06:04 UTC, david-allison-1 commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/AddonBrowserTest.kt
> +     * Addon Browser list addons to screen from addons directory in recycler view
Use `/*` for comments not associated with a variable

2021-08-25 06:04 UTC, david-allison-1 commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/AddonBrowserTest.kt
> +    var mRuntimePermissionRule = GrantPermissionRule.grant(Manifest.permission.WRITE_EXTERNAL_STORAGE)
We typically use `test` be default, rather than `AndroidTest`. Is there a reason for using AndroidTest here?

2021-08-25 06:16 UTC, infinyte7 commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/AddonBrowserTest.kt
> +    var mRuntimePermissionRule = GrantPermissionRule.grant(Manifest.permission.WRITE_EXTERNAL_STORAGE)
Yes, This class will be used for testing recyclerview and other things added to `AddonBrowser`. From earlier PR I found that AndroidTest will better here.

2021-08-25 06:17 UTC, infinyte7 commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/AddonBrowserTest.kt
> +    var mRuntimePermissionRule = GrantPermissionRule.grant(Manifest.permission.WRITE_EXTERNAL_STORAGE)
In next PR I will add more content to this class.

2021-09-03 01:33 UTC, infinyte7 commented
There are three tasks. 
1) Show Hide `Install Addon` button
2) Download when `Install Addon` clicked
3) Extract and copy to folder

<img src="https://user-images.githubusercontent.com/12841290/131936960-d2d7f02e-a9e1-4eb0-a452-e03461b89faf.gif" height=450px></img>

2021-09-04 16:41 UTC, david-allison-1 commented
There's a couple 'merge' commits in the mix, could you rebase these out, or we won't be able to rebase merge this

2021-09-04 16:44 UTC, david-allison-1 reviewed
First comment would be to combine the first and the third commit, and split out the second into constituent commits later on in the PR, so each commit is a valid atom

2021-09-04 16:44 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +                Intent intent = new Intent(NavigationDrawerActivity.this, AddonBrowser.class);
I don't think this commit would compile standalone as `AddonBrowser` doesn't exist yet

2021-09-04 16:44 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="npmjs_registry" translatable="false">https://registry.npmjs.org/%s/latest</string>
No need for a singular commit - it wouldn't pass CI due to unused strings

2021-09-04 20:45 UTC, infinyte7 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="npmjs_registry" translatable="false">https://registry.npmjs.org/%s/latest</string>
I am splitting it to their respective commit.

2021-09-04 22:36 UTC, infinyte7 commented
Reordered commit. 
Next commit depends upon previous commit.

2021-10-01 00:08 UTC, david-allison-1 reviewed
Coming together very nicely!

2021-10-01 00:08 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageTgzExtract.java
> +        GZIPInputStream inputStream = new GZIPInputStream(new FileInputStream(inputFile));
these need to be in a `.use {` block

2021-10-01 00:08 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageTgzExtract.java
> +        final OutputStream outputFileStream = new FileOutputStream(outputFile);
needs a `.use {` block

2021-10-01 00:08 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmUtils.kt
> +    fun getAddonNameFromUrl(url: String): String? {
This could do with testing with bad URLs

2021-10-01 00:08 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/NpmUtilsTest.kt
> +        // if url is search url then get null
This is great

2021-10-01 08:39 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonDownloadActivity.kt
> +    private val mWebViewClient = object : WebViewClient() {
I have copied the code from ShridharGoel 's deck import implementation. I removed history logic.

2021-10-01 08:39 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.kt
> +                    .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
It is similar to `@JsonIgnoreProperties(ignoreUnknown = true)`  I have that one but didn't work.
So, I used `FAIL_ON_UNKNOWN_PROPERTIES`
https://stackoverflow.com/questions/4486787/jackson-with-json-unrecognized-field-not-marked-as-ignorable

2021-10-01 08:39 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageTgzExtract.java
> +        GZIPInputStream inputStream = new GZIPInputStream(new FileInputStream(inputFile));
This java file so `.use {` may be not used. only this file I have not converted to kotlin because I directly copied code from google opensource.

2021-10-01 08:39 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageTgzExtract.java
> +        final OutputStream outputFileStream = new FileOutputStream(outputFile);
This java file so `.use {` may be not used.

2021-10-01 08:39 UTC, infinyte7 commented
> I'll still question this assertion, it's ideal to use the robolectric test unless there's a reason why it won't work. 

I will test recylcerview for listing addons in next PR. The listing of addons counting element added to recyclerview view list. So decided to use androidTest.

(There is no option to reply in same message above so replying here.)

2021-10-01 08:43 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.kt
> +        fun getTarBallUrl(url: URL): String? {
How it can be implemented?

2021-10-01 13:17 UTC, david-allison-1 reviewed
Partial reply - need to head out

2021-10-01 13:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.kt
> +         * For valid package it readValue url and gets tarball url from mapped AddonModel
This is great!

2021-10-01 13:17 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.kt
> +        fun getTarBallUrl(url: URL): String? {
https://stackoverflow.com/a/56900669/13121290 should work

2021-10-01 15:32 UTC, infinyte7 commented
Now it is more cleaner than previous implementation using `enum + data`.

2021-12-19 11:30 UTC, infinyte7 commented
I will update it later.

2022-01-15 10:49 UTC, infinyte7 commented
>we shouldn't need androidTest
>Security: we can't blindly use filenames from untrusted sources without testing
>fragility: we should not fail if additional properties are added to the JSON

- I moved all test for this PR from `androidTest` to `test` except `AddonBrowser`
- I will add function for checking filenames
- I have moved it to [anki-js-addon-export](https://github.com/infinyte7/anki-js-addon-export). The json file contains all the info about addons with `ankidroid-js-addon` keywords. So, it will help in handling issues like new fields added to json and removing  unsafe packages.

2022-01-15 10:51 UTC, infinyte7 commented
Also I have updated the UI. Now it is more intuitive. 

https://user-images.githubusercontent.com/12841290/149619061-dfe67cce-e72e-4a0f-bd5e-e6babd30e2f1.mp4

.

2022-03-03 19:20 UTC, TarekkMA commented
Hi @krmanik,

I noticed you are constructing `ObjectMapper` multiple times. When I was researching about Jackson I found that it's a heavy object. So I've created [`AnkiSerialization`](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/AnkiSerialization.kt) in the past to provide a single instance. Maybe it will be useful here.

2022-03-03 19:49 UTC, krmanik commented
Hi @TarekkMA 
I will update the implementation to (AnkiSerialization)[https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/AnkiSerialization.kt].

Thanks

2022-03-04 09:54 UTC, TarekkMA commented
I will try to have a look tonight or tomorow.

2022-03-06 21:39 UTC, TarekkMA requested changes
These are the things that I noticed right away, will try to give it another look sometime.

Thank you for the great work ❤️

2022-03-06 21:39 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.kt
> +                return mapper?.readValue(url, object : TypeReference<MutableList<AddonModel>>() {})
Rebase on master again, I have made a change to make mapper non-null

2022-03-06 21:39 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonBrowser.kt
> +                val mapper = ObjectMapper()
Use `AnkiSerialization` here

2022-03-06 21:39 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> + * ObjectMapper (jackson) readvalue map package.json to this class
I don't think we should mention the jackson library in the docs.

2022-03-06 21:39 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +class AddonModel {
Maybe data class is better suited for this class.

Also, I guess you will need to add jackson support for it. See: https://www.baeldung.com/kotlin/jackson-kotlin

2022-03-06 21:39 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonBrowser.kt
> +                val addonModel = mapper.readValue(File(file, "package/package.json"), AddonModel::class.java)
Using jackson kotlin module, you can omit the last parameter.

```suggestion
                val addonModel: AddonModel = mapper.readValue(File(file, "package/package.json"))
```

2022-03-06 21:39 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.kt
> +                return mapper?.readValue(url, object : TypeReference<MutableList<AddonModel>>() {})
Also here you can use kotlin module to be more elegant looking.
```suggestion
                return mapper?.readValue(url)
```

2022-03-06 22:05 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.kt
> +                return mapper?.readValue(url, object : TypeReference<MutableList<AddonModel>>() {})
![image](https://user-images.githubusercontent.com/12841290/156943604-51a45979-8109-47dd-993c-6498dccbe92e.png)

2022-03-06 22:05 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt
> +class AddonModel {
I have changed it to data class.

2022-03-06 22:09 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonBrowser.kt
> +                val addonModel = mapper.readValue(File(file, "package/package.json"), AddonModel::class.java)
It showing error.

2022-03-07 08:03 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonBrowser.kt
> +                val addonModel = mapper.readValue(File(file, "package/package.json"), AddonModel::class.java)
You need to use `jackson-module-kotlin` library,

https://github.com/FasterXML/jackson-module-kotlin

2022-03-07 08:04 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmPackageDownloader.kt
> +                return mapper?.readValue(url, object : TypeReference<MutableList<AddonModel>>() {})
https://github.com/FasterXML/jackson-module-kotlin

2022-03-07 08:05 UTC, TarekkMA commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonBrowser.kt
> +                val addonModel = mapper.readValue(File(file, "package/package.json"), AddonModel::class.java)
Don't forget to register it in AnkiSerilization class
```kotloin
val mapper = ObjectMapper().registerModule(KotlinModule())
```

2022-03-07 08:58 UTC, krmanik commented on AnkiDroid/src/main/java/com/ichi2/anki/AddonBrowser.kt
> +                val addonModel = mapper.readValue(File(file, "package/package.json"), AddonModel::class.java)
I understood it but now I think I should split this PR into multiple PR for faster review. Please review the other PR I will create.

2022-06-25 15:44 UTC, mikehardy commented
I know you are watching the stale bot and keeping things that are "alive" live @krmanik - your patience is always appreciated
GSoC causes a huge PR load which I know you feel as well, we'll get all these through though...

2022-06-25 15:44 UTC, krmanik commented
This PR is split and implemented in parts. So this PR should be closed. But the PR will be used as reference for suggestions and review other smaller PR.

2022-06-25 15:44 UTC, closed without merging

2022-06-25 16:00 UTC, krmanik commented
There are already merged some PR and more will be merged soon.

https://github.com/ankidroid/Anki-Android/commits/main/AnkiDroid/src/main/java/com/ichi2/anki/jsaddons