New JS API for bury & suspend card and bury & suspend note and tag card
ankidroid/Anki-Android pull request #9245
Opened 2021-07-11 10:21 UTC by infinyte7

## Pull Request template

## Purpose / Description
This continuation of JS API PR to add more functionality and new features to JS API.

## Fixes
Fixes #9231

## Approach
1. Added new api to `mApiList`
2. Then using signal and `buryCard()`, `buryNote()`, `suspendCard()`, `suspendNote()` and `showTagsDialog()` respective functions will be called for enabled api.

## How Has This Been Tested?
1. Add initialize api contract and get if enabled or not using api version and developer contact
```js
<script>
    var jsApi = { "version": "0.0.1", "developer": "dev@mail.com" };

    var apiStatus = AnkiDroidJS.init(JSON.stringify(jsApi));
    console.log(apiStatus);

    api = JSON.parse(apiStatus);
    if (api['buryCard']) {
        console.log("API bury card available");
    }
    if (api['buryNote']) {
        console.log("API bury note available");
    }

    if (api['suspendCard']) {
        console.log("API suspend card available");
    }

    if (api['suspendNote']) {
        console.log("API suspend note available");
    }

    if (api['tagCard']) {
        console.log("API tag card available");
    }
</script>
```

2. Then use following functions for the API
- To bury current card
```
<button onclick="ankiBuryCard();"></button>
```

- To bury current note
```
<button onclick="ankiBuryNote();"></button>
```

- To suspend current card
```
<button onclick="ankiSuspendCard();"></button>
```

- To suspend current note
```
<button onclick="ankiSuspendNote();"></button>
```

- To show Tags dialog for adding tag to current card
```
<button onclick="ankiAddTag();"></button>
```

Tested on devices and emulator

## Learning (optional, can help others)
https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x ] You have commented your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-07-17 16:10 UTC, mikehardy requested changes
I also like this idea a lot but we need to kill the boilerplate on it first thing, before a lot of these go in. I asked for advice there

2021-07-17 16:10 UTC, mikehardy commented on AnkiDroid/src/main/assets/scripts/card.js
> +// add to tag card current card
```suggestion
// add tag to current card
```

2021-07-17 16:10 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +    private static final String TAG_CARD = "tagCard";
I think the symbols here could be very specific as there may be lots of future tag work, so specifying the full verb/subject/object tuple is useful 

```suggestion
    private static final String ADD_TAG_TO_CARD = "addTagToCard";
```

2021-07-17 16:10 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                }
These blocks for the API not null and API contains signal are really repetitive

@david-allison-1 some advice here please, I notice in your APIs you boil these down even more than I do as you think more functionally than I do. If I had to guess "What would David do?" I would guess "David would make an interface that actually takes a function, then he could just write `return runAPICommand(BURY_CARD, () => buryCard())` or similar.

Does that sound about right? Do you have a sketch of what exactly that would look like or a pointer to code (I am certain this pattern exists in a couple places now...)

I picture 50 of these APIs in the future so this should be as efficient code-wise as possible and the boilerplate is crazy right now

2021-07-17 17:02 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                }
Also, the JS API should be moved another class. 
This is better idea `return runAPICommand(BURY_CARD, () => buryCard())` .

2021-07-18 03:40 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                }
@mikehardy  That looks good. 

Why are we using the signal-based API here, instead of the `JavascriptInterface` API where most of the API was placed?

2021-07-18 14:25 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                }
Ah! That's an even more important comment and would apply to the add tag to card PR as well @infinyte7 - I noticed the signal list was pretty short and thought "we have more APIs than that already don't we?" but could not put my finger on the oddness - of course it is because most of the API is elsewhere. Definitely better to have them all in one spot unless there is a reason to use the signals here specifically?

2021-07-18 15:03 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                }
Okay, I will changed it JavaScript function. That will also be done.

2021-07-18 15:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +                }
@mikehardy To my knowledge, the signals existed due to a security vulnerability in older versions of Android (~API 16) with `addJavascriptInterface` which allowed access to `.getClass()` by default, which gave JS full reflection-based access to the app.

I don't believe we need it any more

PoC:

```javascript
<script>
function execute(cmd){
  return window.jsinterface.getClass().forName('java.lang.Runtime').getMethod('getRuntime',null).invoke(null,null).exec(cmd);
}
execute(['/system/bin/sh','-c','echo \"mwr\" > /mnt/sdcard/mwr.txt']);
</script>
```

https://labs.f-secure.com/archive/webview-addjavascriptinterface-remote-code-execution/

2021-08-05 02:00 UTC, infinyte7 commented
`JavaScriptInterface` is much simpler than my previous implementation.

2021-08-05 16:38 UTC, mikehardy approved these changes
The combined change looks great (that is: implementing the feature, but with `@JavascriptInterface`

2021-08-05 16:38 UTC, merged

2021-08-06 06:09 UTC, BilderLoong commented
Thank you guys so much!