JS API to open card browser and search with query
ankidroid/Anki-Android pull request #9247
Opened 2021-07-11 14:30 UTC by infinyte7

## Pull Request template

## Purpose / Description
This is continuation of JS API features. From reviewer using js function/button in one click it will go to CardBrowser and search for cards using query.

## Fixes
Fixes #8109

## Approach
1. Override `openCardBrowser()` and call the function with query parameter using `signal`
3. Get string extra in CardBrowser and assign query to `mSearchTerms` then call `searchCards()`

## How Has This Been Tested?
Testesd on devices and emulator 

1. Add a button in card template to call `ankiSearchCard(query)`
2. Add query like, this query are same as entering in CardBrowser
```
'deck:"deck name" {{front}}'
'deck:"test" flag:2 tag:marked'
'deck:"test" flag:2 tag:marked is:suspended'
'deck:"test" flag:2 tag:marked search text here'
```
3. Click button to run the query
```js
<button onclick="ankiSearchCard('deck:\"test\" {{hanzi}}')">Search this in Card browser</button>
```

#### video
https://user-images.githubusercontent.com/12841290/125199042-0bbff280-e297-11eb-9670-07087c713b96.mp4

#### Another example, Added following to front side of card template
```js
<script>
   var jsApi = {"version" : "0.0.1", "developer" : "dev@mail.com"};

   var apiStatus = AnkiDroidJS.init(JSON.stringify(jsApi));
   console.log(apiStatus);
   
   api = JSON.parse(apiStatus);
   
   if (api['searchCard']) {
      console.log("API search card available");
   } 

  </script>

<button onclick="searchCard();">{{Simplified}}</button>     //  <-----  note this line

<script>
function searchCard() {
 ankiSearchCard('deck:"xiehanzi HSK 3.0" {{Simplified}}');  //  <-----  note this line
}
</script>

<div class="text-color1">{{Pinyin}}</div>
<div class="text-color3">{{Meaning}}</div>
```

#### image
<img src="https://user-images.githubusercontent.com/12841290/125198946-ac61e280-e296-11eb-912b-1adec540aa13.gif" height=450px></img>

## Learning (optional, can help others)
https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-07-17 15:46 UTC, mikehardy requested changes
I like this idea, but as mentioned in comments, split into 2 commits where one alters the API and all callers to always use Nullable query string to open card browser as a small simple change, then second commit layers the new Javascript API on top of it using the new capability

2021-07-17 15:46 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
> +        }
If you just checked for the search_query Intent extra, and used it if non-null, then all the "called_from_js_api" stuff can disappear, making this a much smaller / easier to understand change

```suggestion

        if (getIntent().getStringExtra("search_query") != null) {
            mSearchTerms = getIntent().getStringExtra("search_query");
            searchCards();
        }
```

2021-07-17 15:46 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +        intent.putExtra("search_query", query);
Change the official "openCardBrowser" API to add the query parameter as a `@Nullable` item and update all callers to the new API

Do this as a separate clean commit, then review of that change is trivial

As a second commit then add the Javascript API part that uses it - then this looks good to go?

```suggestion
    protected void openCardBrowser(String query) {
        Intent intent = new Intent(NavigationDrawerActivity.this, CardBrowser.class);
        Long currentCardId = getCurrentCardId();
        if (currentCardId != null) {
            intent.putExtra("currentCard", currentCardId);
        }
        intent.putExtra("search_query", query);
```

2021-07-17 17:00 UTC, infinyte7 commented
> I like this idea, but as mentioned in comments, split into 2 commits where one alters the API and all callers to always use Nullable query string to open card browser as a small simple change, then second commit layers the new Javascript API on top of it using the new capability

I will split into two PR. Thanks

2021-07-17 17:33 UTC, mikehardy commented
For this one could just be 2 commits I think - in this same PR, that would work for me, these ones will be small

2021-07-17 18:15 UTC, infinyte7 commented
> For this one could just be 2 commits I think - in this same PR, that would work for me, these ones will be small

Okay, I will do it.

2021-08-05 16:39 UTC, mikehardy requested changes
Can you use `@JavascriptInterface` in this one as well? Like in #9245 ?

2021-08-05 19:42 UTC, mikehardy approved these changes
Nice!

2021-08-05 19:42 UTC, mikehardy commented
Has a conflict with your other PR though :sweat_smile:

2021-08-05 19:50 UTC, infinyte7 commented
Yes, I think I need to rebase it.

I also thinking about implementing in signal. Because here are two types of function
- Functions that get parameter(s) - `ankiShowToast, ankiMarkCard etc.`
- Functions that do not get parameter(s) -  `All JSInterface functions`

So, should we make a rule that function that needs parameter(s) should go through signal and the function which do no require parameter(s) should go though `JSInterface`?

2021-08-05 19:55 UTC, mikehardy commented
- I am not aware of any security concerns for JavascriptInterface anymore (android 5+). Arguments, no arguments, no matter.
- I am under the impression *everything* should be JavascriptInterface, I expect this to be JavascriptInterface
- The commit history here is not good. There is no reason to have more than one commit here, containing nothing but the commit that adds the JavascriptInterface. Rebase is what you need to get there

2021-08-05 19:56 UTC, infinyte7 commented
Okay, I am on it.

2021-08-05 20:07 UTC, mikehardy approved these changes
Nice!

2021-08-05 20:27 UTC, merged