Migrate AnkiDroid Folder to External Scoped App-Specific Directory
ankidroid/Anki-Android pull request #9249
Opened 2021-07-11 18:59 UTC by farjadilyas

## Purpose / Description
Migrating user data stored in an AnkiDroid-specific folder to an App-Specific (external only for now) in order to preserve access to user data under scoped storage.

## Fixes
Takes a step towards fixing #5304. Fixes #9107.

## Approach
Uses storage permission (which AnkiDroid already asks for) to access legacy storage and migrates the data to the External App-Specific Directory (given by getExternalFilesDir())
Migration is done by launching a MigrateToScoped task

Any file within the AnkiDroid folder can be accessed under Scoped Storage post-migration.

## How Has This Been Tested?

- SAMSUNG Galaxy A80 (SM-A805F) API 30 (Physical Device)
- SAMSUNG Galaxy S7 (SM-G930F) API 26 (Physical Device)

Tested all different approaches used to move user data. Tested by repeatedly closing the app and confirming that it performs better the second time around once some data has been transferred.

## Important

- User Data is only being copied from the Legacy Directory, not deleted for now. That can be done once all use cases work under Scoped Storage
- To enable the Scoped Storage Functionality, set AnkiDroidApp's TESTING_SCOPED_STORAGE to true
- TESTING_SCOPED_STORAGE is set to false by default and will be set to true once the app can access external media (to be done in a later PR)

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

2021-07-12 05:53 UTC, Arthur-Milchior reviewed
Thank you. Mostly nits. Plus a request for test, or at least explaining in commit message how you tested it

2021-07-12 05:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
> +     * Uses {@link Files#walkFileTree(Path, FileVisitor)} to visit all levels of the file tree and copy
The reference to FileVisitor is seems to be an implementation detail. 
Is there any reason for the user of this method to care about it? If so, please write explicitly what is the difference in usage between V21 and V26. Otherwise, just put a comment that is not a javadoc

2021-07-12 05:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.java
> +    public static long getDirectorySize(File f) {
The name seems misleading as it can accept a directory or a file. Could you find better? Also, maybe state that the time is linear/proportional to the number of file. It is not straighforward that there is not just a android method knowing this that you could have answered in constant time, so it's nice to warn the user of the method

2021-07-12 05:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private boolean isLegacyStorage() {
As far as I understand, we can't add actual test for this method. Then, can you indicate in the commit message how you tested it. In case of bug, that's the best thing we could get to debug

2021-07-12 05:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
> +    public boolean moveDirectory(@NonNull File source, @NonNull File destination, ProgressSenderAndCancelListener<Integer> ioTask) {
Is there a way to test those methods? Creating a folder, testing its size is accurate, copying it, moving it, checking its content. With multiple small file and a bigger one (just a few mb).
I think that @mikehardy on device testing well, so please let me know if it makes no sens. But I assume that it would not be extremely hard to test (at least if you know how to create file and compare them)

2021-07-12 05:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +     * for the AnkiDroid folder. This new directory will be accessible without any permissions under Scoped Storage.
"without REQUESTING any permission" I assume. Because there seems to still be a notion of permission, simply, we automatically have it

2021-07-12 05:53 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        // To get the new path for the AnkiDroid folder, take the current name of the AnkiDroid folder and append it
I think you should indicate in which case the folder is not named "AnkiDroid" (I assume it's only variant A, B, ... we are not considering people forking their version of ankidroid here)

2021-07-15 07:12 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        // To get the new path for the AnkiDroid folder, take the current name of the AnkiDroid folder and append it
Okay, I'll mention that the user can change the directory used for storing AnkiDroid data via Settings -> Preferences -> Advanced. Hence, the name of the folder being used to store AnkiDroid's data can be anything the user wants it to be.

2021-07-15 07:42 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        // To get the new path for the AnkiDroid folder, take the current name of the AnkiDroid folder and append it
In fact, under Scoped Storage, Android already provides a directory to AnkiDroid for storing user data (Android/data/com.ichi2.anki/files), so we can just use that for storing data instead of creating an AnkiDroid folder below /files. Does that seem like the better option? If so, we can use a ```moveDirectoryContents()``` method instead of ```moveDirectory()```. This method will move a source directory's contents to the specified destination directory. It will also create the destination directory in case it doesn't exist. This can then also be used whenever a use case requires the migration of user data. What do you think?

2021-07-15 07:51 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        // To get the new path for the AnkiDroid folder, take the current name of the AnkiDroid folder and append it
In fact, Android provides a folder for AnkiDroid to store its data in under Scoped Storage: Android/data/com.ichi2.anki/files. We can simply use this files directory to store user data and move the contents of the old AnkiDroid directory to this instead of moving the AnkiDroid directory itself under the files directory. What do you think?

2021-07-16 08:21 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        // To get the new path for the AnkiDroid folder, take the current name of the AnkiDroid folder and append it
I beg your pardon. I don't understand what you mean.
Do you mean the user can change the directory today, that they will be able to change it once we have scoped storage, or both?
I'm really surprised if it's the second or third case; I thought that the point of internal scoped storage was that it led to a directory that is only under control of ankidroid and nothing else; so that the actual directory was of no importance to the user. 
To answer your question, I'd need to know what is the point of changing the directory when you use scoped storage. 

I'll stay consistent with my previous advice. In case of doubt, if there is a simple path, take it. Unless you believe it'll block you later. Right now I'm totally fine with Android/data/com.ichi2.anki/files, as long as it will allow the us to update the app in 2022. It's okay if we wait a later PR to change directory. 
Anyway, if you plan to allow the user to change directory under scoped storage (whatever that means), then you'll need to move the directory, so it's not like we can avoid this move by implementing it in this PR

2021-07-16 14:29 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        // To get the new path for the AnkiDroid folder, take the current name of the AnkiDroid folder and append it
No that's not what I meant. I meant that while migrating user data from the old legacy directory to a scoped directory, we can just use com.ichi2.anki/files and copy the contents of the current AnkiDroid directory instead of moving the directory itself. I believe this makes more sense, so I'll go for this. So we'll need methods to move the **contents** of a directory, not the directory itself. I'll make the changes and push.

2021-07-24 09:50 UTC, Arthur-Milchior reviewed
Thanks for the update.

There are speed improvement suggestion. Please do not work on them now, just put a todo in the code. As I wrote on discord, that's not the priority. 

There are a lot of comments request. Hopefully that should be quick to follow.
Similarly, refactorization/splitting a commit in two, I hope it'll be relatively easy to follow.

And as we discussed, mostly, I want to see tests for moving the folders, no change here

2021-07-24 09:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.java
> +     * and all of its sub-directories.
You can add in the various methods that we are assuming no symbolic links, as no code here deals with them (and it's not something we expect here anyway)

2021-07-24 09:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
> +     * latter case, a file isn't moved to the destination if the same file exists already.
It's implied by your text, but I tihnk it would be nice to note that while the source will often be empty after a succesful execution, there is no guarantee of it.
Also, I'd like you to describe failure modes. E.g. if the move is interrupted, what are the possible states? 
I suspect that it should be something such as:
* all files deleted from source are copied into destination
* all files moved into destination are deleted from source except potentially one

2021-07-24 09:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
> +     * source must be a directory. If the destination exists, it must be a directory. If it doesn't exist, then a
Can you please add that the running time is worst case linear, but it may sometime be constant if the source and destination are on the same device

2021-07-24 09:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +            return DeckPicker.migrateToScopedStorage(col.getContext(), collectionTask);
Please move the code of `migrateToScopedStorage` here. Unless you use a DeckPicker static private method (I didn't check), there is no reason to add this level of indirection.

2021-07-24 09:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private void handleStartupScenarios() {
I'd like you to create a commit that just extract `handleStartupScenarios` from `handleStartup` and call it in `handleStartup`. It'll make the diff easier to read in github

2021-07-24 09:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +     * This directory is stored under the key deckPath in SharedPreferences
the key "deckPath"

2021-07-24 09:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        String externalScopedDirPath =  CollectionHelper.getAppSpecificExternalAnkiDroidDirectory(this);
single space after "="

2021-07-24 09:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private long getAnkiDroidDirectorySize() {
I'd be more confortable if you could return a `Long` and then return `null` if there is an exception. Doing it this way semes dangerous

2021-07-24 09:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private long getAnkiDroidDirectorySize() {
Can it be static? 
I'd suggest trying to move what we can related to directories in a separate file, potentially a class of utils that are never instantiated, or a file that only contain a reference to current collection/preference.
Because getAnkiDroidDirectorySize is very very vaguely related to deck picking, the main purpose of this windows.

2021-07-24 09:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private void onMigrationComplete() {
I'd like if possible a name that indicate what it does and not when it should be called. 
If you can't find a name that is relevant and just want to let us know it's done at the end of the migration, then putting it in `actualOnPostExecute` would make reading the code easier, as `actualOnPostExecute` is always done at the end of the task executed

2021-07-24 09:50 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private boolean isLegacyStorage() {
It seems it can be static. Also one of the method I'd like to see outside of DeckPicker because it's not related to picking deck.

2021-07-24 11:32 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
> +    /**
I'll include the javaodc in the implementation in the interface. It should be kept in the interface since CompatVN is always accessed via ```CompatHelper.getCompat()```, so since the object returned is of the superclass type, it doesn't search for the javadoc of the overridden method. It shows no javadoc if I remove the interface javadoc and keep the javadoc of the overridden class.

2021-07-24 18:08 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +    private long getAnkiDroidDirectorySize() {
I agree. ```getAnkiDroidDirectorySize()``` & ```isLegacyStorage()``` are two methods which seem out of place in DeckPicker. Since CollectionHelper contains methods for getting Legacy & App-Specific directories, I'll move both of these methods to CollectionHelper.

2021-07-25 00:14 UTC, Arthur-Milchior reviewed
Hi,

Thanks a lot for those changes. 
Could you please introduce the test in the same commit as the method it tests?
To merge things quicker, you may want to create one PR with the copy method and with the copy test. Another PR with the move method and move test. (They can reuse the same utilities function)

I'd also like if possible tests for other methods such as the listFiles, ensureFileIsDirectory.
I think @david-allison-1 also asked for failures test. I don't know personally how to do so. How to simulate that the sd card becomes inaccessible during the run, that ankidroid gets closed during the run. But if there is way, it would be really great to do so.
Otherwise, it would be great if you can simulate a partially copied folder so that you can check that restarting a partially copied folder is done correctly. It seems you didn't test for that, or otherwise I missed it

2021-07-25 00:14 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/utils/FileUtilTest.java
> +    private ProgressSenderAndCancelListener<Integer> getDummyListener() {
I'd state you may simply do
`private static class DummyListener implements ProgressSenderAndCancelListener<Integer>() {`
No need for a function here

2021-07-25 00:14 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/utils/FileUtilTest.java
> +    @Config(sdk = { 21, 26 })
I see this config is used twice already.. Added once by @mikehardy and once by @david-allison-1 . Could one of you write in https://github.com/ankidroid/Anki-Android/wiki/Testing the reason we would want to use this config. I'd have thought it would be relevant for any SDK. And I don't get why we don't use the same restriction on all test if it's not always relevant

2021-08-04 15:41 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
> +    public static boolean isLegacyStorage(Context context) {
Ran 10 tests, and this method took 4-6 milliseconds to execute, even when I disabled migration and set the AnkiDroid folder to a folder which had 10 parent folders before it reached the root external storage directory (10 levels of nesting). So it doesn't seem like we need to use a preference. Moreover, for the vast majority of users, once their data is migrated, the while loop in this method will exit after the first iteraration since the current directory will be exactly the same as the external app-specific directory.

2021-08-07 14:13 UTC, Arthur-Milchior reviewed
One last small requested change, and good to go for me. 

I had to check the copy/move were already merged, for some reason I forgot about it

2021-08-07 14:13 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            CollectionHelper.getInstance().closeCollection(false, "refresh");
"refresh"? I think "migration to scoped storage" would be a far better reason to timber.

2021-08-07 15:58 UTC, david-allison-1 requested changes
We need to set `android:hasFragileUserData`: https://developer.android.com/guide/topics/manifest/application-element

What're the plans for automated testing? 

Can we allow a fallback for non-Play Store related installs which do not enforce scoped storage as the Play Store does?

We're at high risk for breaking this mechanism in the future with DeckPicker/startup related changes

2021-08-07 15:58 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            TaskManager.launchCollectionTask(new CollectionTask.MigrateToScoped(),
To my understanding (please correct me if I'm wrong): 

* This moves the Anki Collection and media into the scoped storage directory, which is now inaccessible to the user
* A user can't move their Anki collection via the preferences, they can only specify a new directory

Therefore, a user will have lost USB-based access to their collection. They will only be able to use the app to perform backups via our export mechanism.

If they uninstall the app, then the data in the scoped directory is at risk of deletion. 

I feel this use-case is sufficient to warrant the option of providing a full backup option to a user.

@mikehardy @Arthur-Milchior opinions? Or is this PR only for testing the mechanism, in which case I don't see an issue

2021-08-07 16:02 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                CompatHelper.getCompat().moveDirectory(sourceDir, destinationDir, listener);
The PR description states that this is a 'copy' operation, is this still the case?

2021-08-07 16:07 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            TaskManager.launchCollectionTask(new CollectionTask.MigrateToScoped(),
Since we're defaulting to an External App-Specific directory, the user will still have USB-based access to their collection & will be able to backup using their PC.

2021-08-07 16:16 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                CompatHelper.getCompat().moveDirectory(sourceDir, destinationDir, listener);
I mentioned that we'll be copying, not moving the directory in the PR since I thought it'd make for easier testing (testers wouldn't have to create a backup (for repeated testing) before opening the app which migrates their data). However, we'll need to test ```moveDirectory()``` anyway before we enable the migration feature (currently disabled by setting ```TESTING_SCOPED_STORAGE``` to false), so I think it makes sense to have ```moveDirectory()``` here instead. What do you think?

2021-08-07 16:16 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                CompatHelper.getCompat().moveDirectory(sourceDir, destinationDir, listener);
If you agree, I'll remove the TODO above this method & edit the PR comment

2021-08-07 16:33 UTC, farjadilyas commented
> We need to set `android:hasFragileUserData`: https://developer.android.com/guide/topics/manifest/application-element
> 
> What're the plans for automated testing? We're at high risk for breaking this mechanism in the future with DeckPicker/startup related changes
> 
> Can we allow a fallback for non-Play Store related installs which do not enforce scoped storage as the Play Store does, or is this out of scope for V1 of the migration

I thought it would make more sense to set```android:hasFragileUserData``` in a PR which finally enables the migration to Scoped Storage. Currently, the ```TESTING_SCOPED_STORAGE``` flag is set to false, so the app won't migrate user data to Scoped Storage. This flag was meant to be used by testers to test the migration functionality. What do you think?

As for the fallback for non-Play Store related installs, we can repurpose & rename the ```TESTING_SCOPED_STORAGE``` flag in the PR which enables the migration to scoped storage functionality only if the app detects if it has been installed via the Play Store, if that is possible?

I'll look into automated testing for the DeckPicker startup routine which now includes the migration functionality.

2021-08-07 16:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            TaskManager.launchCollectionTask(new CollectionTask.MigrateToScoped(),
If it's still accessible/modifiable via USB, my concern has no basis, thanks!

2021-08-07 18:23 UTC, david-allison-1 requested changes
After enabling the setting in `AnkiDroidApp`, this fails on my device (Android 11 Google Pixel 3a stock).

The dialog is stuck on the screen with no option for interaction

<details><summary>error</summary>

```
D/DeckPicker: onCreate()
I/AnkiActivity: AnkiActivity::onCreate - DeckPicker
I/CollectionHelper: isLegacyStorage(): current dir: /storage/emulated/0/AnkiDroid
    scoped external dir: /storage/emulated/0/Android/data/com.ichi2.anki/files
    scoped internal dir: /data/user/0/com.ichi2.anki/files
E/com.ichi2.anki: Invalid ID 0x00000000.
I/CollectionTask$MigrateToScoped: Starting Migration /storage/emulated/0/AnkiDroid to /storage/emulated/0/Android/data/com.ichi2.anki/files
V/ActivityThread: Recovering failed rename /storage/emulated/0/AnkiDroid/.nomedia to /storage/emulated/0/Android/data/com.ichi2.anki/files/.nomedia
V/ActivityThread: Recovering failed rename /storage/emulated/0/AnkiDroid/collection.anki2 to /storage/emulated/0/Android/data/com.ichi2.anki/files/collection.anki2
W/com.ichi2.anki: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
    Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
D/DeckPicker: No DeckPicker background preference
I/AnkiActivity: AnkiActivity::onStart - DeckPicker
D/DeckPicker: onResume()
I/AnkiActivity: AnkiActivity::onResume - DeckPicker
D/UsageAnalytics: sendAnalyticsScreenView(): DeckPicker
D/UsageAnalytics: getOptIn() status: false
D/DialogHandler: Reading persistent message
D/DeckPicker$UpdateDeckListListener: Refreshing deck list
    Refreshing deck list
D/DeckPicker: onPause()
I/SingleTaskManager: Cancelled 1 instances of task class com.ichi2.async.CollectionTask$LoadDeckCounts
I/AnkiActivity: AnkiActivity::onPause - DeckPicker
D/DeckPicker: onStop()
I/AnkiActivity: AnkiActivity::onStop - DeckPicker
D/WidgetStatus: WidgetStatus.update(): already running or not enabled
D/UIUtils: saveCollectionInBackground: start
I/AnkiActivity: AnkiActivity::onStart - DeckPicker
D/DeckPicker: onResume()
I/AnkiActivity: AnkiActivity::onResume - DeckPicker
D/UsageAnalytics: sendAnalyticsScreenView(): DeckPicker
    getOptIn() status: false
D/DialogHandler: Reading persistent message
D/DeckPicker$UpdateDeckListListener: Refreshing deck list
D/DeckPicker$UpdateDeckListListener: Refreshing deck list
V/ActivityThread: Recovering failed rename /storage/emulated/0/AnkiDroid/collection.anki2-journal to /storage/emulated/0/Android/data/com.ichi2.anki/files/collection.anki2-journal
I/AdrenoGLES-0: QUALCOMM build                   : 781e7d0, I46ff5fc46f
    Build Date                       : 12/01/20
    OpenGL ES Shader Compiler Version: EV031.31.04.01
    Local Branch                     : QPR1
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
    Build Config                     : C P 11.0.1 AArch64
    Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
I/AdrenoGLES-0: PFP: 0x016ee189, ME: 0x00000000
W/AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
    <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
I/Gralloc4: mapper 4.x is not supported
W/Gralloc3: mapper 3.x is not supported
V/ActivityThread: Recovering failed rename /storage/emulated/0/AnkiDroid/collection.log to /storage/emulated/0/Android/data/com.ichi2.anki/files/collection.log
I/OpenGLRenderer: Davey! duration=788ms; Flags=1, IntendedVsync=110693338566848, Vsync=110693788566830, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=110693805122003, AnimationStart=110693805127732, PerformTraversalsStart=110693805130597, DrawStart=110694111070211, SyncQueued=110694118761357, SyncStart=110694119136618, IssueDrawCommandsStart=110694119231097, SwapBuffers=110694126633442, FrameCompleted=110694127311931, DequeueBufferDuration=410000, QueueBufferDuration=321562, GpuCompleted=0, 
V/ActivityThread: Recovering failed rename /storage/emulated/0/AnkiDroid/collection.media to /storage/emulated/0/Android/data/com.ichi2.anki/files/collection.media
E/ActivityThread: Rename recovery failed 
    android.system.ErrnoException: rename failed: EXDEV (Cross-device link)
        at libcore.io.Linux.rename(Native Method)
        at libcore.io.ForwardingOs.rename(ForwardingOs.java:190)
        at libcore.io.BlockGuardOs.rename(BlockGuardOs.java:350)
        at libcore.io.ForwardingOs.rename(ForwardingOs.java:190)
        at android.app.ActivityThread$AndroidOs.rename(ActivityThread.java:7589)
        at java.io.UnixFileSystem.rename(UnixFileSystem.java:368)
        at java.io.File.renameTo(File.java:1412)
        at com.ichi2.compat.CompatV21.moveDirectory(CompatV21.java:168)
        at com.ichi2.async.CollectionTask$MigrateToScoped.task(CollectionTask.java:268)
        at com.ichi2.async.CollectionTask$MigrateToScoped.task(CollectionTask.java:256)
        at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:200)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:162)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:109)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
D/DeckPicker: onCreateOptionsMenu()
D/Collection: undoAvailable() undo size: 0
D/DeckPicker: onPause()
I/SingleTaskManager: Cancelled 1 instances of task class com.ichi2.async.CollectionTask$LoadDeckCounts
I/AnkiActivity: AnkiActivity::onPause - DeckPicker
D/DeckPicker: onStop()
I/AnkiActivity: AnkiActivity::onStop - DeckPicker
D/WidgetStatus: WidgetStatus.update(): already running or not enabled
D/UIUtils: saveCollectionInBackground: start
```

</details>

I've disabled the setting and my `collection.anki2` appears to have been wiped. The `AnkiDroid` folder is still in place.

I've backed up, but if there is recovery options available, it'd be useful for future developers

`/storage/emulated/0/Android/data/com.ichi2.anki/files/` appears to be completely inaccessible, both via the Device Browser and `adb shell & runas com.ichi2.anki`

2021-08-07 18:59 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                Timber.w("Migration failed");
This log is odd, especially since in ```CompatV21```'s ```moveDirectory()```, which is used by all other CompatVnns, if a rename fails, it breaks from the loop and attempts a copy and delete, but the logs show that it is attempting to recover multiple renames - this means that for multiple files within the AnkiDroid directory, ```srcFile.renameTo(destFile)``` is called. Something that shouldn't be possible. I attempted migrating on a Pixel 4 XL running Android 11 and it worked fine.

2021-08-07 19:49 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                Timber.w("Migration failed");
The exception is normal, it occurs when the source and destination directory are on different storage partitions, this doesn't result in an exception inside moveDirectory() through. If the rename fails like in this case, moveDirectory() should do a copy-then-delete. I tried it on a Pixel 3a & Pixel 4 XL Emulator, both running Android 11, and the migration was successful. Could you uninstall the app, and try again, perhaps with an empty collection. Also, I can't figure out why ```/storage/emulated/0/Android/data/com.ichi2.anki/files/``` wouldn't be accessible, I can access it via the Files app on the emulator.

2021-08-07 19:51 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                Timber.w("Migration failed");
It's empty in `Files`, and the provided directory was inaccessible via `adb`

2021-08-07 20:54 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                Timber.w("Migration failed");
Accessible on my PC and filling up from a sync, even though `AnkiDroidApp.TESTING_SCOPED_STORAGE` is false. 

Likely just my phone picking up the `deckPath` change

2021-08-07 21:01 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                Timber.w("Migration failed");
```deckPath``` should only change to ```Android/data/.../files``` once the migration is complete. I just realised I used ```apply()``` instead of ```commit()``` while saving the new path corresponding to the key ```deckPath```. Since ```apply()``` is asynchronous, perhaps the new path wasn't written to memory, and when the collection was reopened, it attempted to initialize the AnkiDroid directory from the empty folder.. I'll make the changes, let's see if this make a difference

2021-08-07 21:05 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                Timber.w("Migration failed");
I've never seen `apply()` fail, it could be possible, but it doesn't feel likely.

2021-08-07 21:20 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                Timber.w("Migration failed");
Hmm... if `deckPath` was empty while `TESTING_SCOPED_STORAGE` was `true`, `getDefaultAnkiDroidDirectory` would return: `getAppSpecificExternalAnkiDroidDirectory`. 

We should have more logging around changing `deckPath`, both on initial startup, and as a `Timber` during the migration

2021-08-07 21:23 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                Timber.w("Migration failed");
Yes, that's intentional. That way, for new installs, the app will set up the directory in the app-specific external directory, so there won't be a need to migrate (if ```TESTING_SCOPED_STORAGE``` is set to ```true``` of course)

2021-08-07 21:44 UTC, david-allison-1 commented
at 61d22b778343628730eef1971256c26f46cbce52

```
2021-08-07 22:38:46.797 14121-14121/com.ichi2.anki D/AnkiDroid: Startup - Application Start
2021-08-07 22:38:46.802 14121-14121/com.ichi2.anki I/UsageAnalytics: initialize()
2021-08-07 22:38:46.804 14121-14121/com.ichi2.anki D/UsageAnalytics: App tracking id 'tid' = UA-125800786-1
2021-08-07 22:38:46.882 14121-14121/com.ichi2.anki I/WebViewFactory: Loading com.google.android.webview version 92.0.4515.131 (code 451513133)
2021-08-07 22:38:46.956 14121-14121/com.ichi2.anki W/com.ichi2.anki: Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)
2021-08-07 22:38:46.956 14121-14121/com.ichi2.anki W/com.ichi2.anki: Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)
2021-08-07 22:38:46.956 14121-14121/com.ichi2.anki W/com.ichi2.anki: Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)
2021-08-07 22:38:46.964 14121-14121/com.ichi2.anki I/cr_WVCFactoryProvider: Loaded version=92.0.4515.131 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
2021-08-07 22:38:46.996 14121-14121/com.ichi2.anki I/cr_LibraryLoader: Successfully loaded native library
2021-08-07 22:38:46.998 14121-14121/com.ichi2.anki I/cr_CachingUmaRecorder: Flushed 8 samples from 8 histograms.
2021-08-07 22:38:47.003 14121-14121/com.ichi2.anki I/TetheringManager: registerTetheringEventCallback:com.ichi2.anki
2021-08-07 22:38:47.099 14121-14137/com.ichi2.anki W/System: A resource failed to call close. 
2021-08-07 22:38:47.160 14121-14172/com.ichi2.anki W/chromium: [WARNING:dns_config_service_android.cc(153)] Failed to read DnsConfig.
2021-08-07 22:38:47.480 14121-14121/com.ichi2.anki I/GoogleAnalyticsImpl: Not participating in analytics sample (sample percentage vs random: 10 90)
2021-08-07 22:38:47.481 14121-14121/com.ichi2.anki I/UsageAnalytics: setOptIn(): from false to false
2021-08-07 22:38:47.481 14121-14121/com.ichi2.anki I/GoogleAnalyticsImpl: Not participating in analytics sample (sample percentage vs random: 10 57)
2021-08-07 22:38:47.482 14121-14121/com.ichi2.anki D/UsageAnalytics: setOptIn() optIn / sAnalytics.config().enabled(): false/false
2021-08-07 22:38:47.483 14121-14121/com.ichi2.anki I/UsageAnalytics: setDryRun(): true, warning dryRun is experimental
2021-08-07 22:38:47.498 14121-14121/com.ichi2.anki I/CompatV26: Creating notification channel with id/name: General Notifications/AnkiDroid
2021-08-07 22:38:47.501 14121-14121/com.ichi2.anki I/CompatV26: Creating notification channel with id/name: Synchronization/Synchronization
2021-08-07 22:38:47.503 14121-14121/com.ichi2.anki I/CompatV26: Creating notification channel with id/name: Global Reminders/Cards due
2021-08-07 22:38:47.505 14121-14121/com.ichi2.anki I/CompatV26: Creating notification channel with id/name: Deck Reminders/Reminders
2021-08-07 22:38:47.580 14121-14121/com.ichi2.anki I/AnkiDroidApp: AnkiDroidApp: Starting Services
2021-08-07 22:38:47.586 14121-14121/com.ichi2.anki I/CollectionHelper: Begin openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
2021-08-07 22:38:47.638 14121-14121/com.ichi2.anki D/RustSupportSQLiteOpenHelper: createRustSupportSQLiteDatabase
2021-08-07 22:38:48.093 14121-14121/com.ichi2.anki I/Collection: Opening Collection Log
2021-08-07 22:38:48.100 14121-14121/com.ichi2.anki D/Collection: [1628372328] Collection.java:<init>(): /storage/emulated/0/AnkiDroid/collection.anki2,  2.16alpha9
2021-08-07 22:38:48.371 14121-14121/com.ichi2.anki I/NativeMethods: ExecuteCommand: localMinutesWest
2021-08-07 22:38:48.381 14121-14121/com.ichi2.anki D/Collection: [1628372328] SchedV2.java:_updateCutoff(): 2854,  1628391600
2021-08-07 22:38:48.407 14121-14121/com.ichi2.anki I/NativeMethods: ExecuteCommand: localMinutesWest
2021-08-07 22:38:48.408 14121-14121/com.ichi2.anki I/CollectionHelper: End openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
2021-08-07 22:38:48.409 14121-14121/com.ichi2.anki I/BootService: Executing Boot Service
2021-08-07 22:38:48.456 14121-14121/com.ichi2.anki D/IntentHandler: onCreate()
2021-08-07 22:38:48.462 14121-14121/com.ichi2.anki E/com.ichi2.anki: Invalid ID 0x00000000.
2021-08-07 22:38:48.507 14121-14121/com.ichi2.anki D/IntentHandler: onCreate() performing default action
2021-08-07 22:38:48.507 14121-14121/com.ichi2.anki I/IntentHandler: Launching DeckPicker
2021-08-07 22:38:48.617 14121-14121/com.ichi2.anki D/AnkiDroidApp: AnkiDroidApp::getLanguageConfig - setting locale to en_GB
2021-08-07 22:38:48.674 14121-14121/com.ichi2.anki D/DeckPicker: onCreate()
2021-08-07 22:38:48.676 14121-14121/com.ichi2.anki I/AnkiActivity: AnkiActivity::onCreate - DeckPicker
2021-08-07 22:38:48.705 14121-14121/com.ichi2.anki I/CollectionHelper: isLegacyStorage(): current dir: /storage/emulated/0/AnkiDroid
    scoped external dir: /storage/emulated/0/Android/data/com.ichi2.anki/files
    scoped internal dir: /data/user/0/com.ichi2.anki/files
2021-08-07 22:38:51.492 14121-14200/com.ichi2.anki I/CollectionHelper: closeCollection: migration to scoped storage
2021-08-07 22:38:51.492 14121-14200/com.ichi2.anki W/DB: Not in a transaction. Cannot end transaction.
2021-08-07 22:38:51.496 14121-14200/com.ichi2.anki I/NativeMethods: ExecuteCommand: closeCollection
2021-08-07 22:38:51.503 14121-14200/com.ichi2.anki D/DB: Database /storage/emulated/0/AnkiDroid/collection.anki2 closed = true
2021-08-07 22:38:51.505 14121-14200/com.ichi2.anki D/DB: Database /storage/emulated/0/AnkiDroid/collection.media.ad.db2 closed = true
2021-08-07 22:38:51.505 14121-14200/com.ichi2.anki I/Collection: Closing Collection Log
2021-08-07 22:38:51.507 14121-14200/com.ichi2.anki I/Collection: Collection closed
2021-08-07 22:38:51.511 14121-14200/com.ichi2.anki I/CollectionTask$MigrateToScoped: Starting Migration /storage/emulated/0/AnkiDroid to /storage/emulated/0/Android/data/com.ichi2.anki/files
2021-08-07 22:38:51.569 14121-14200/com.ichi2.anki E/ActivityThread: Rename recovery failed 
    android.system.ErrnoException: rename failed: EXDEV (Cross-device link)
        at libcore.io.Linux.rename(Native Method)
        at libcore.io.ForwardingOs.rename(ForwardingOs.java:190)
        at libcore.io.BlockGuardOs.rename(BlockGuardOs.java:350)
        at libcore.io.ForwardingOs.rename(ForwardingOs.java:190)
        at android.app.ActivityThread$AndroidOs.rename(ActivityThread.java:7589)
        at java.io.UnixFileSystem.rename(UnixFileSystem.java:368)
        at java.io.File.renameTo(File.java:1412)
        at com.ichi2.compat.CompatV21.moveDirectory(CompatV21.java:168)
        at com.ichi2.async.CollectionTask$MigrateToScoped.task(CollectionTask.java:272)
        at com.ichi2.async.CollectionTask$MigrateToScoped.task(CollectionTask.java:256)
        at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:200)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:162)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:109)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-08-07 22:38:51.570 14121-14200/com.ichi2.anki I/CompatV21: Rename failed /storage/emulated/0/AnkiDroid/backup to /storage/emulated/0/Android/data/com.ichi2.anki/files/backup
2021-08-07 22:38:51.570 14121-14200/com.ichi2.anki I/CompatV21: Attempting a copy-then-delete
2021-08-07 22:38:51.589 14121-14200/com.ichi2.anki I/CompatV26: Copied /storage/emulated/0/AnkiDroid/backup/collection-2021-08-07-20-54.colpkg to /storage/emulated/0/Android/data/com.ichi2.anki/files/backup/collect [...]

2021-08-07 21:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +            if (mIncreaseSinceLastUpdate > mProgressUpdateThreshold) {
Change this to "or once every 100ms", or it feels like progress has crashed.

Maybe change the threshold to 0.1% as well

2021-08-07 22:16 UTC, david-allison-1 commented
Migration failed after a 22 minute wait (~800MB collection)

```
2021-08-07 23:13:54.175 20044-20044/com.ichi2.anki D/Collection: undoAvailable() undo size: 0
2021-08-07 23:13:54.213 20044-20117/com.ichi2.anki I/CompatV26: Copied /storage/emulated/0/AnkiDroid/collection.media
2021-08-07 23:13:54.272 20044-20117/com.ichi2.anki I/CompatV26: Copied /storage/emulated/0/AnkiDroid/collection.media.ad.db2 to /storage/emulated/0/Android/data/com.ichi2.anki/files/collection.media.ad.db2
2021-08-07 23:13:54.321 20044-20117/com.ichi2.anki I/CompatV26: Copied /storage/emulated/0/AnkiDroid/collection.media.ad.db2-journal to /storage/emulated/0/Android/data/com.ichi2.anki/files/collection.media.ad.db2-journal
2021-08-07 23:13:54.363 20044-20117/com.ichi2.anki I/CompatV26: Copied /storage/emulated/0/AnkiDroid/card.html to /storage/emulated/0/Android/data/com.ichi2.anki/files/card.html
2021-08-07 23:13:54.406 20044-20117/com.ichi2.anki I/CompatV26: Copied /storage/emulated/0/AnkiDroid
2021-08-07 23:13:54.407 20044-20117/com.ichi2.anki W/CollectionTask$MigrateToScoped: java.nio.file.DirectoryNotEmptyException: /storage/emulated/0/AnkiDroid
        at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:242)
        at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
        at java.nio.file.Files.delete(Files.java:1126)
        at com.ichi2.compat.CompatV26$1.postVisitDirectory(CompatV26.java:140)
        at com.ichi2.compat.CompatV26$1.postVisitDirectory(CompatV26.java:108)
        at java.nio.file.Files.walkFileTree(Files.java:2688)
        at java.nio.file.Files.walkFileTree(Files.java:2742)
        at com.ichi2.compat.CompatV26.copyDirectory(CompatV26.java:108)
        at com.ichi2.compat.CompatV21.moveDirectory(CompatV21.java:185)
        at com.ichi2.async.CollectionTask$MigrateToScoped.task(CollectionTask.java:272)
        at com.ichi2.async.CollectionTask$MigrateToScoped.task(CollectionTask.java:256)
        at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:200)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:162)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:109)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-08-07 23:13:54.407 20044-20117/com.ichi2.anki W/CollectionTask$MigrateToScoped: Migration failed
```

`AnkiDroid` contains:

* `backup/`
* `collection.anki2`
* `collection.anki2-journal`
* `collection.log`

2021-08-07 22:39 UTC, farjadilyas commented
Ah, I should've realized the CompatV26 implementation throws an exception if the directory isn't empty while being deleted unlike the CompatV21 implementation of ```copyDirectory()```. I'll catch that (we only make a best effort to delete the source) and also look into why an 800MB collection took so long..

2021-08-07 22:58 UTC, david-allison-1 commented
There's about 14000 small media files, which presumably take a long time. Unsure if a wake lock would help here.

I can't access the folder from my phone, but will give a rough speed test of a "copy to root of phone" via Windows Explorer

2021-08-07 23:11 UTC, Arthur-Milchior commented
> at least 7000 files

? I don't get it. Did it only copy 7000 files? How long did it take? Do you know the size of the copied part?

2021-08-07 23:15 UTC, david-allison-1 commented
> > at least 7000 files
> 
> ? I don't get it. Did it only copy 7000 files? How long did it take? Do you know the size of the copied part?

The process crashed. I couldn't get a good estimate as the transfer didn't complete

2021-08-07 23:37 UTC, david-allison-1 commented
Second copy via `Files` internally on the Android copied 10,129 of my collection files in 20 minutes

2021-08-08 22:08 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                Timber.w("Migration failed");
We can assume that the files in /data/ were the result of the migration, rather than changing the path.

2021-08-09 00:14 UTC, david-allison-1 commented
We shouldn't directly use `com.ichi2.anki/files` without a subfolder as the user may potentially have multiple profiles, which would be migrated to the same location

2021-08-09 01:30 UTC, mikehardy commented
> We shouldn't directly use `Android/data/com.ichi2.anki/files` without a subfolder as the user may potentially have multiple profiles and use `deckPath` to switch between them.
> 
> If they do this, I assume they' be migrated to the same location

Is that true, or is our multiple profile "support" (implemented via entirely separate package names) going to put them under `<package name>/files` for each of `com.ichi2.anki`, `com.ichi2.anki.A` etc?

2021-08-09 04:05 UTC, david-allison-1 commented
> > We shouldn't directly use `Android/data/com.ichi2.anki/files` without a subfolder as the user may potentially have multiple ~~profiles~~ collections and use `deckPath` to switch between them.
> > If they do this, I assume they' be migrated to the same location
> 
> Is that true, or is our multiple profile "support" (implemented via entirely separate package names) going to put them under `<package name>/files` for each of `com.ichi2.anki`, `com.ichi2.anki.A` etc?

I misspoke, edited the comment.

This is multiple collection support, which is implemented in the same APK by changing the deck path property. 

It's better for a user to use the parallel APKs, but I presume many don't, and an attempt to change the path will result in incorrect copies being performed.

2021-08-09 15:27 UTC, mikehardy commented
Oh wow, I actually can't imagine anyone doing multi-collection support that way. The preferences are an important part of multi-collection support (like, what AnkiWeb account you are hooked up to) and I can't imagine someone wanting to do multi collections without also having a unique set of preferences connected to the collection, which is only achievable with the parallel builds.

But maybe I'm wrong. 

Then I guess if I were implementing this I would want it to be more prescriptive, how exactly could I derive a stable mapping from whatever the collection path was to the new migrated path? All the path segments in the current collection path are potentially arbitrary + non-unique but the entire path must be unique, so it would have to be a map from the whole path to a subfolder somehow based on the whole original path (either directly making it a tree or doing a hash of the path or something - whatever seems sensible) ?

2021-08-09 15:44 UTC, david-allison-1 commented
> Oh wow, I actually can't imagine anyone doing multi-collection support that way. The preferences are an important part of multi-collection support (like, what AnkiWeb account you are hooked up to) and I can't imagine someone wanting to do multi collections without also having a unique set of preferences connected to the collection, which is only achievable with the parallel builds.
> 
> But maybe I'm wrong.
> 
> Then I guess if I were implementing this I would want it to be more prescriptive, how exactly could I derive a stable mapping from whatever the collection path was to the new migrated path? All the path segments in the current collection path are potentially arbitrary + non-unique but the entire path must be unique, so it would have to be a map from the whole path to a subfolder somehow based on the whole original path (either directly making it a tree or doing a hash of the path or something - whatever seems sensible) ?

Example of 1, but I do this regularly (weekly) when testing on my main profile

* I use the API, which only works on `com.ichi2.anki`, so can't use a parallel build + API usage.
* When testing, I change to a new profile (`storage/emulated/.../AnkiDroidTzTest`)
* AnkiWeb detects it as a 'full upload' situation, which is great. I get a big warning prompt and I've never had an issue with accidentally wiping my data
* A long time ago, I spent some time streamlining the logon screen to two taps for a logon if the account is saved. I can and do happily wipe preferences on a regular basis due to testing PRs

2021-08-24 19:14 UTC, mikehardy commented
I just merged #9411 which I think affects this one by peeling a method out? Also I'm not sure what the state of this one is (sorry) - is it waiting for final review + merge?

2021-09-28 22:17 UTC, mikehardy requested changes
This looks good in general though the last commit concerns me as it appears to be reaching for even more performance using limited dev time vs any testing - I don't see any automated testing? - I have to admit I think I'm more interested in seeing a lot of automated testing of this code then in more performance items.

Since storage access is vastly slower than CPU I'm not sure more threads (producer/consumer) will add more parallelism vs just chewing through it single thread as we should be waiting on disk almost the whole time anyway

My other comments are pretty tiny but the testing question and the question on preempt on the dequeue maybe being racy are both important to me

On the whole though, this is a lot of code and honestly it looks pretty good. I'm kind of itching to either see automated tests and examine the results or determine some way to implement testing myself and start really hammering on this thing to get it live :-)

2021-09-28 22:17 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        // Block sync if 'legacyPath' preference exists, i.e, user data is currently being migrated
```suggestion
        // Block sync if migration source path preference exists, i.e, user data is currently being migrated
```

It would also be good if `migrationSourcePath` was a constant, just in case

2021-09-28 22:17 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        migrationServiceIntent.putExtra("deque", CollectionHelper.getInstance().getMediaMigrationDeque());
does this work? I thought everything went through serialization when it went to an Intent and was passed around :thinking:

2021-09-28 22:17 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            CollectionHelper.getInstance().getMediaMigrationDeque().putFirst(new Pair<>(sourceFile, CollectionTask.MediaMigrationProducer.ACTION_PREEMPT));
interesting - it seemed to me that this was actually functional prior to this dequeue draft commit - now I'm not sure if just putting it on the queue will result in it being available to the reviewer or not - is it multi-thread and racy and just in practice normally results in the consumer moving it in time, but if (for example) a really large video was currently being copied it might result in a broken sound or image?

2021-09-29 09:48 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
> +            // Increment number appended to AnkiDroid to obtain a new potentially unique directory name
A common use case for users is to use different profiles by changing the AnkiDroid directory they are using by accessing Settings - > Advanced - > AnkiDroid directory. So whenever the user selects a directory that is a legacy storage directory, it will need to be migrated. This is why we need to be able to dynamically create new AnkiDroid folders in the app-specific directory when the user selects a legacy directory which needs to be migrated

2021-09-29 09:49 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        migrationServiceIntent.putExtra("deque", CollectionHelper.getInstance().getMediaMigrationDeque());
It does work, but I'll look into that again

2021-09-29 09:54 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            CollectionHelper.getInstance().getMediaMigrationDeque().putFirst(new Pair<>(sourceFile, CollectionTask.MediaMigrationProducer.ACTION_PREEMPT));
It was functional prior to the commit but it was racy then. Because the Reviewer runs on the main thread and the migration is done in a background thread so there's a slim chance of both threads writing to the same file at the same time which would cause problems.

This draft commit actually fixes that. The deque is thread safe, the Reviewer can add to the front of it and there's one consumer so there's no risk of writing to the same location from two different threads.

Yes, this does introduce a risk that if the consumer is busy migrating some large file, then it won't copy the file in time for the Reviewer to load it, but I'm assuming that's better than a corrupted media file. 

David suggested using a thread safe deque for migrating media and this is my interpretation of what he meant. I don't know for sure if this is what he meant.

2021-09-30 00:17 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
> +            // Increment number appended to AnkiDroid to obtain a new potentially unique directory name
Oh yes! I remember David mentioning that. Okay so this is actually supporting a current use case for people and is really important. It looked correct either way :-). And it appears to get us started on handling multiple profiles, so that's great

2021-09-30 00:23 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            CollectionHelper.getInstance().getMediaMigrationDeque().putFirst(new Pair<>(sourceFile, CollectionTask.MediaMigrationProducer.ACTION_PREEMPT));
Okay - it does look correct in my read, just with that one risk of the media not being migrated before display if the consumer was busy. I don't know how to solve that without even more complication, like having some sort of thread mutex the reviewer waits on after a PREEMPT, and the consumer doing a notify on that mutex after processing a preempt? I guess that may not be so complicated after all. Now we introduce the possibility of an ANR if either the file they need is big or they preempt behind a big file.

Standard alternate solution then is listeners and events, I guess when you enqueue a preempt you could pass in a listener, pop a progress dialog (noting that it shouldn't animate if safe display is on - we have to have one of these somewhere already...) and then when the listener is called you kill the dialog and show the card.

Is this worth it? Not on a first pass I think, I'm much much more interested in testing :-).

And I think if it was already racy before, then this will not be worse at minimum. Worst I can imagine here is a missing media file during a review, not the end of the world.

2021-09-30 00:24 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
> +            CollectionHelper.getInstance().getMediaMigrationDeque().putFirst(new Pair<>(sourceFile, CollectionTask.MediaMigrationProducer.ACTION_PREEMPT));
(note: after you think through this - if you think it makes sense to make a listener for preempt completion and have the reviewer wait until listener is called, peel it to a separate issue as a "nice to have", in my opinion)

2021-09-30 00:28 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        migrationServiceIntent.putExtra("deque", CollectionHelper.getInstance().getMediaMigrationDeque());
If you test it and it works, I believe you. I would love to see tests in the PR - then you could just point at the e2e CI run :-)

2021-09-30 00:30 UTC, mikehardy commented
I think this is really close personally. I have not pulled it and tested it locally yet but other than some string constants and just some conversational questions that probably won't result in code here, this is really close for me :raised_hands:

2021-10-01 00:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        migrationServiceIntent.putExtra("deque", CollectionHelper.getInstance().getMediaMigrationDeque());
I worry whether there's a size limit on an intent and the queue is potentially unbounded (~100k items for some collections wouldn't surprise me). I wouldn't oppose moving this functionality to the service

2021-10-01 00:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                    srcDir.delete();
I'd leave a `migrated.txt` file in there to inform technical users of where the next directory is, rather than deleting it.

2021-10-01 00:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                    continue;
Probably want a `Timber.w` here

2021-10-01 00:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +            for (final File file : FileUtil.listFiles(srcDir)) {
This doesn't account for folders within the directory

2021-10-01 00:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                Timber.w(e, "Error during user media migration from %s to %s", mediaSourceDir, mediaDestinationDir);
This needs better user messaging, just showing a "migration failed" on startup with no way to understand the failure will lead to a lot of app uninstalls (potentially further worsening matters if they didn't have backups).

2021-10-01 00:41 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                    CompatHelper.getCompat().copyFile(srcFile.getAbsolutePath(), destFile.getAbsolutePath());
This can be performed on a folder instead of a file (folder doesn't exist & rename fails, my assumption is that this will be the default action for most of our users).

If this occurs, we can't preempt the queue

2021-10-01 08:59 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                    srcDir.delete();
I thought we could leave the ```migrated.txt``` under the AnkiDroid folder. Here, we're migrating the ```collection.media``` folder (hence, ```MediaMigrationProducer```). What do you think?

2021-10-01 09:24 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +        migrationServiceIntent.putExtra("deque", CollectionHelper.getInstance().getMediaMigrationDeque());
The queue is empty when it's passed to the Service since it has just been created so I'm not sure if size would be a problem, it hasn't been one so far during testing. I will move this functionality to the Service though since one problem with this approach is that if the app is closed, then started while migration is still in progress, the original Service wouldn't have died and would still be using the original deque, and we want the Reviewer to be able to get the same reference the Service has when the app restarts. So I'll initialize the queue in the service itself and make it available to the Reviewer in a safe way.

2021-10-01 09:25 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +            for (final File file : FileUtil.listFiles(srcDir)) {
It does, because ```renameTo()``` works on folders as well, and ```listFiles()``` lists both files and directories.

2021-10-01 09:27 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                Timber.w(e, "Error during user media migration from %s to %s", mediaSourceDir, mediaDestinationDir);
Totally agree. We should show a dialogue message for this.

2021-10-03 21:14 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                    srcDir.delete();
Deleting folders (unless we verify that they're empty) is a dangerous operation. 

I feel that as long as we have safety rails, we can delete, but also should get a second opinion. @mikehardy @Arthur-Milchior

2021-10-04 00:04 UTC, Arthur-Milchior commented
@mikehardy do you have any specific idea in mind for e2e testing ? In particular, if copying/moving data takes potential hours, how to do it without making all tests run (on dev computer and with github action) so long. 
What do we want to see tested?

I'm not even sure to know all the cases that can occur

@farjadilyas I'd like to note that your test fail is linting, so it's legit. I don't know whether it's because it's "a bit dirty", but it would be nice also too correct it

2021-10-04 00:07 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                    srcDir.delete();
When the migration occurs, if the user create/edit a card and add a media, does the media directly goes to the right folder?

I don't know whether any app that interacts with ankidroid adds media to the media collection. Technically, they could. That would be an issue in any case. But I guess it's nice to test whether the directory is empty/only contains image that are already copied so that recent modification are not lost.

2021-10-04 16:59 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
> +                    srcDir.delete();
Oh that's a good point @Arthur-Milchior - there is nothing stopping an AnkiDroid note edit from adding media, or a user of AnkiDroid API from adding media (there is an API to do so). Not sure how we want to handle that. If we spin through the files again to check before saying we are done, it will decrease the time window when it could happen, but will not make it zero. I think the only safe way is to make sure that once the migration starts all media goes to the new folder.

I *believe* though it needs testing, that this is the case - once migration starts, the storage folder for media is the new one, so new additions go to the new space.

2021-10-18 08:58 UTC, david-allison-1 commented
@farjadilyas Any updates on this?

2021-11-05 13:04 UTC, mikehardy commented
>              "message": "Your app currently targets API level 29 and must target at least API level 30.",

Alphas may not be launched any longer, this is now full blocker. I'll admit that makes me motivated where before I was not really devoting time to it

2021-11-05 17:45 UTC, mikehardy commented
I just rescued this from conflict entropy and re-pushed.

2021-11-05 18:18 UTC, mikehardy commented
Compile issue at the moment, looks trivial, will need to investigate

```
w: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt: (144, 46): Unchecked cast: Any? to LinkedBlockingDeque<Pair<File?, Int>>
> Task :AnkiDroid:compilePlayDebugKotlin FAILED
```

2021-11-20 14:04 UTC, AkechiShiro commented
Is this PR almost finished or is it still relevant for GSoC 2022 perhaps ?

2021-11-20 14:15 UTC, mikehardy commented
It's nearly finished, it's in the "testing, make it production-worthy" status.
it is not going to be GSoC 2022, and is probably a state now where it needs a very experienced Android and AnkiDroid dev to move it forward. Not to discourage: it could also be a great learning opportunity but if you do not have a lot of experience with Android and AnkiDroid it will be like taking a high level programming class all at once :-)

2021-12-23 09:51 UTC, voidplayer commented
Since this is a risky move and this 2.16 seems pretty big already, have you consider to ship this under a button where the user can manually trigger the migration instead of triggering the migration automatically?

Then, add it to the releases notes where plenty of people will notice and the brave and the willing will test it. Being the brave those with enough free time to deal with the consequences :)

That would probably be a less stressful 2.16 release, with less opportunity of something catching fire

2021-12-23 12:46 UTC, david-allison-1 commented
@voidplayer Already doing so: https://github.com/ankidroid/Anki-Android/pull/9949

Thoughts would be much appreciated.

The problem is, we really want people to migrate - if they uninstall the app, they permanently lose access to their `AnkiDroid` folder, and would need a PC + USB (or AnkiWeb) to recover their data.

I'm taking this on, and have a spec in for review currently. I'm confident I understand the problem, but obviously given the consequences of getting things wrong, it needs to be triple-checked.

2021-12-23 13:51 UTC, mikehardy commented
To me this is actually the only feature in 2.16 and it needs to ship fully on + ready to go
Everything else in 2.16 is just noise and none of it is that disruptive I think (at least relative to our test coverage, which I'm pretty confident in, and my daily use of 2.16 alphas, which is all fine to the point)

2021-12-23 14:12 UTC, voidplayer commented
#9949 looks better than expected. For some reason i thought you were going to trigger this behind curtains. I will comment a few things on the issue, but it looks way less scary than i was imaging it

2022-02-28 14:36 UTC, closed without merging

2022-02-28 14:58 UTC, mikehardy commented
@david-allison not sure if this was going to be harvested or if it's baked in to the PR stream that's working through development/review already? Stated differently, should this remain open?

2022-02-28 15:09 UTC, voidplayer commented
This bot sure is brutal!

I would not expect this to happen in this bug

2022-02-28 15:17 UTC, david-allison commented
I have the files locally. Fine to keep closed.

It'll be baked into the PR stream (notification service, task management & general operation structure)

2022-02-28 16:03 UTC, voidplayer commented
@mikehardy why do you think i am complaining?

I just made a joke about my nonstop fight with the bot for months [in another thread](https://github.com/ankidroid/Anki-Android/issues/8158#issuecomment-1053655534) which i finally conceded to the bot as i wouldnt not open the bug again

You joked there (worth of a melancholy haiku) and then i kept the joke going by making a silly haiku, which you understood as a joke too presumably by hearting it

Then i found it funny that the most important bug in this release got closed by the same bot within 24h and so, i used the same wording you did, calling it brutal!

Im sorry, i didnt intend to sound harsh or bitchy! I understand you like to keep the bug tracker clean and totally support that!

2022-02-28 18:10 UTC, mikehardy commented
Ah, just me being touchy perhaps, no worries. There is a lack of human connection when we are just trading text back and forth. The bot is brutal yes, nearly as brutal as the pace of PR review here ;-)