NF: clarify the actual set of API in CompatVN
ankidroid/Anki-Android pull request #9252
Opened 2021-07-12 04:46 UTC by Arthur-Milchior

2021-07-12 08:06 UTC, david-allison-1 approved these changes

2021-07-12 14:17 UTC, mikehardy reviewed
This will be a maintenance burden and go out of date, it requires documentation to stay in sync with code, but the documentation is not going to be next to the code that actually changes.

Suggest boilerplate comment at top of each class that specifies how to derive the covered APIs vs fixing the numbers (which creates the out-of-date documentation risk).

e.g.

"Baseline implementation of <compat>, covers APIs from the apps minSdkVersion through the next higher CompatVnn implementation" on the first one. Then each class should get one saying "This API-specific Compat implementation covers from the API specified in this classes name through the next higher CompatVnn implementation class"

2021-07-12 14:18 UTC, mikehardy commented
I'm sensitive to this because as near as I can tell, I'm the only one that actually maintains these objects, and I'm certain I'll forget to update the covered APIs in the header if I go in and add a new method back for some old API, requiring me to make a new CompatVnn object in between existing ones.

2021-07-12 14:19 UTC, mikehardy requested changes
request for more generic / derived style vs fixed style as noted

2021-07-12 22:13 UTC, Arthur-Milchior commented
Actually, @farjadilyas was adding code in those classes for copying folder. So at least one other person was adding code here. Clearly too soon to check whether any maintenance is due

2021-07-12 22:55 UTC, Arthur-Milchior commented
I totally redid the commit

2021-07-14 13:13 UTC, mikehardy approved these changes
Now the text will apply forever with no change, quite thorough!
Thanks @Arthur-Milchior - noted one typo, but otherwise good to go for me

2021-07-14 13:13 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
> + * deprecated, changed its behavior, or because the implementation of {@code methol} can be more efficient.
```suggestion
 * deprecated, changed its behavior, or because the implementation of {@code method} can be more efficient.
```
typo only

2021-07-16 12:58 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
> + * deprecated, changed its behavior, or because the implementation of {@code methol} can be more efficient.
Forever, maybe note. If we change min sdk or were to add a V22, I'd be in favor of updating examples. But that's up to future reviewers

2021-07-16 16:27 UTC, mikehardy commented
Fascinating, I couldn't understand how github wasn't showing a conflict with the same line changed here https://github.com/ankidroid/Anki-Android/commit/c318324dfc6eeff9055e9fc74b0f94d15861f9e3#diff-9344f849c42100ac6bbb9a883b4ce039e32e03c7f4bb68a4a218dbe7fc2d8e79R34 - so I even pulled your PR branch here locally, and rebased it against master, and...it worked fine. I guess if the exactly equivalent change is present even if two commits have it, rebase just handles it. I thought theoretically it was supposed to do this but it was still interesting to me to see.

Anyway :-), merging.

2021-07-16 16:28 UTC, merged

2021-07-17 12:55 UTC, Arthur-Milchior commented
Sorry, what is fascinating here ? I don’t get it

2021-07-17 13:47 UTC, mikehardy commented
2 PRs modified the same line but did not conflict.

2021-08-05 15:41 UTC, mikehardy commented
Hi there!

If you're already submitted something to OpenCollective for PRs merged in July 2021, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for July 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month)

Thanks!