feat: Dialog to handle gesture selection
ankidroid/Anki-Android pull request #9264
Opened 2021-07-14 13:49 UTC by david-allison-1

## Pull Request template

## Purpose / Description
Currently unused: adds `GestureSelectionDialogBuilder`

A screen with visual feedback allowing gesture selection via either user action, or via a spinner

The spinner exists to enhance discoverability of long/double tap gestures

Known Issues:
* Swipe does not appear on <= API 24. A static image is used
* Gesture unicode character not rendered on <= API 22
* Milliseconds of visual latency on taps (due to double tap checking)

## Fixes
Prep for #6052, layouts from #8078 with refactoring

## How Has This Been Tested?

Android 11, API 21, 22, 23, 24 and 25

<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/62114487/125629429-acffcc17-1c05-40b6-92c3-e3917715bd0a.png)

![image](https://user-images.githubusercontent.com/62114487/125629417-cab93598-a9b1-4baa-b9c8-57671fb294f7.png)

![image](https://user-images.githubusercontent.com/62114487/125629397-27df3bb7-65ba-44ba-bb37-551b012f1b49.png)

![image](https://user-images.githubusercontent.com/62114487/125629354-fce460ec-6386-4c76-86ec-c733049d9c13.png)

API 21: no gesture unicode char, or swipe feedback

![image](https://user-images.githubusercontent.com/62114487/125629329-9f992c59-128c-45d6-ad0d-92ccd00d8135.png)

</details>

## Learning (optional, can help others)
Android UI is still painful, especially so on lower APIs

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)
   * Only issue is the text contrast of the "OK" button in night mode

2021-07-14 13:52 UTC, david-allison-1 commented on AnkiDroid/src/main/res/layout/gesture_picker.xml
> +        app:layout_constraintTop_toBottomOf="@+id/gestureDisplay"/>
I wanted `Sample Data` here for the editor, but couldn't get it working from an array, gave up after about 20 minutes.

2021-07-14 13:52 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/ui/OnGestureListener.kt
> +        // TODO: There is visual latency here. We can do better.
Didn't feel this was worth the flaky code, but it's maybe 400ms latency, which isn't smooth. Users probably won't care

2021-07-14 13:53 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/Gesture.kt
> + * How the screen is segmented for tap gestures.
Could you focus on documentation here? I've made an effort to improve it, but I still feel it could do with improving (main aim is to explain why 9 and 4-point gesture modes aren't compatible, even though both use "top, left, right and down" as a base

2021-07-14 14:28 UTC, david-allison-1 commented
> com.ichi2.anki.tests.LayoutValidationTest > ensureLayout[gesture_picker][TestingAVD(AVD) - 11] FAILED 
	android.view.InflateException: Binary XML file line #34 in com.ichi2.anki:layout/gesture_picker: Binary XML file line #34 in com.ichi2.anki:layout/gesture_picker: Error inflating class com.ichi2.ui.GestureDisplay
	Caused by: android.view.InflateException: Binary XML file line #34 in com.ichi2.anki:layout/gesture_picker: Error inflating class com.ichi2.ui.GestureDisplay

2021-07-14 16:16 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/ui/GestureDisplay.kt
> +        mSwipeView.drawable?.mutate()
`NullPointerException` on `mSwipeView.drawable` during instrumented tests.

This seems like an instrumentation failure, so I'm handling it with a "don't mutate the drawable if it's null"

2021-07-16 14:16 UTC, mikehardy requested changes
I bikeshedded your comment by request :-)
I think there's an emoji that will work down to API21

Those are cosmetic though I think (except if the proposed emoji works it kills a big part of the change)

2021-07-16 14:16 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/Gesture.kt
> +        // The string appears as an "undefined character" before API 23
Suggest using an emoji that is present down to Android 5 vs eliding it?

Full set https://emojipedia.org/google/android-5.0/

Reasonable candidate? https://emojipedia.org/google/android-5.0/backhand-index-pointing-up/
https://emojipedia.org/emoji/%F0%9F%91%86/ (code point `U+1F446`)

👆

2021-07-16 14:16 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/Gesture.kt
> +     * edge which it is associated with, but the center and each corner is ambiguous.
```suggestion
     * The cardinal directions: up, down, left & right.
     * Draw a line from corner to corner diagonally, each touch target fully handles the
     * edge which it is associated with
     * four-point and nine-point are thus incompatible because the four-point center and corners
     * are ambiguous in a nine-point system and thus not interchangeable
```

2021-07-16 14:59 UTC, david-allison-1 commented
Thanks!

![image](https://user-images.githubusercontent.com/62114487/125967928-73a82154-7ec6-429f-a4d0-bca419136ebc.png)

Not implemented in this PR, but also works on the preference screen

![image](https://user-images.githubusercontent.com/62114487/125967932-499a9155-b3a3-43eb-9599-c288ca78baeb.png)

2021-07-16 15:55 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/ui/OnGestureListener.kt
> +        // TODO: There is visual latency here. We can do better.
This does seem like a set-it-once and very very rarely ever use it sort of feature.
Works for me

2021-07-16 16:00 UTC, mikehardy approved these changes
This looks amazing!
Going to pull it and test driver it, but pending merge

2021-07-16 16:09 UTC, mikehardy commented
@david-allison-1 How strange, I'm on commit 58c488559c7d3efde8722ec0507543399f91c1a1 but for some reason when I go settings --> gestures and tap one that is "no action" I get the old radio button interface still? Am I doing something wrong (quite possible)?

2021-07-16 16:49 UTC, david-allison-1 commented
> @david-allison-1 How strange, I'm on commit [58c4885](https://github.com/ankidroid/Anki-Android/commit/58c488559c7d3efde8722ec0507543399f91c1a1) but for some reason when I go settings --> gestures and tap one that is "no action" I get the old radio button interface still? Am I doing something wrong (quite possible)?

Intentional. First line of the PR is: 

> Currently unused: adds GestureSelectionDialogBuilder.

Once this goes in, we need a PR which changes from the legacy `(gesture -> command)` to the new `(command -> [gesture])`.

Since this is a preference upgrade, I want it to be as small as possible to figure out any bugs. This was the last "big" change before this happens

----

 Let me know if you'd like this behind a "dev" feature flag, or if you'd like a private branch

2021-07-16 17:25 UTC, mikehardy commented
Ah that explains it, with all the APIs you're exercising on it, and the depth+duration you've been at it, I'm fully prepared to trust.

2021-07-16 17:25 UTC, merged