fill_parent to match_parent
ankidroid/Anki-Android pull request #9272
Opened 2021-07-15 14:08 UTC by Akshay0701

change fill_parent to match_parent

2021-07-15 14:25 UTC, david-allison-1 commented
LGTM, could you confirm you've had a quick test of this on your phone?

2021-07-15 14:35 UTC, Akshay0701 commented
yes, I tested it, 
do you want a video of working? 
an area of changes is very big, and covering that in one video is hard/long,

2021-07-15 15:03 UTC, david-allison-1 approved these changes

2021-07-15 15:03 UTC, david-allison-1 commented
No need - will take it on trust

2021-07-16 14:34 UTC, mikehardy requested changes
The changes seem fine but the Description is just a tautology, as a reviewer I have no idea why this change is being made, and my most important job here is to reject change for change's sake. 

All change should advance the project, so the description should explain why this is needed - the PR template is a really useful guide to the information I want to know. I suggest copying it back in vs deleting it, and filling it in

2021-07-16 15:54 UTC, Akshay0701 commented
You're right I must give some context before actually rasing pr(sorry for this), now I edited the pr head comment 👍, 
let me know if you want more details.

2021-07-16 16:16 UTC, mikehardy approved these changes
I updated the head once more with a concise description - the PR history over time serves as documentation when we tackle future bugs, so rather than the logical fallacy of appeal to authority (references to groups and statements made, but no authoritative link) best to just link it, quote the doc that motivates the change and then it is minimal + complete I think

Either way - it's a good change :-)

2021-07-16 16:16 UTC, merged

2021-08-05 15:41 UTC, mikehardy commented
Hi there!

If you're already submitted something to OpenCollective for PRs merged in July 2021, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for July 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month)

Thanks!