Update usage of deprecated stream types in MediaPlayer and AudioManager
ankidroid/Anki-Android pull request #9280
Opened 2021-07-16 08:17 UTC by ShridharGoel

## Purpose / Description
Update usage of deprecated stream types in MediaPlayer and AudioManager.

Documentation links:
https://developer.android.com/reference/android/media/MediaPlayer#setAudioAttributes(android.media.AudioAttributes)
https://developer.android.com/reference/android/media/AudioManager#requestAudioFocus(android.media.AudioFocusRequest)

## Fixes
Fixes #9274 

## How Has This Been Tested?
Checked that audio functionality is working in note editor and reviewer.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-07-16 17:34 UTC, mikehardy requested changes
This should address #5022 (I think it does?) at which point you can add it to the Fixes list in the PR description and remove the "deprecation" suppression in the method signature https://github.com/ankidroid/Anki-Android/pull/9280/files#diff-be68cc2fe3602c809299eccfd2ad4a096ac832521298d1394f0f7676b74ccfd9R318

If it doesn't fix 5022 I'd be curious to know why and if it is possible to handle all of it at the same time?

2021-07-16 19:45 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
> +    private final AudioFocusRequest mAudioFocusRequest = new AudioFocusRequest.Builder(AudioManager.AUDIOFOCUS_GAIN)
I'm not sure `@RequiresApi` works like this? I think it is still the responsibility of the caller to never call an annotated method on an API lower than the one annotated, but in this case since it is a member variable it will be called no matter what as the class is instantiated, in order to initialize it.

My hypotheses is that this will crash on API < `Build.VERSION_CODES.O` - have you tested this on an API21 emulator?

2021-07-16 19:55 UTC, ShridharGoel commented
The deprecation warning is still there even after putting a check for API versions.

2021-07-16 19:57 UTC, ShridharGoel commented
`requestAudioFocus(AudioFocusRequest focusRequest)` and `abandonAudioFocusRequest(AudioFocusRequest focusRequest)` are available only for API 26 and above.

2021-07-16 20:13 UTC, mikehardy commented
Ah! That's more of a structural issue. You have to suppress the warning if you use them at all.
Normally we 

- make a [new API in Compat](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/compat/Compat.java)
- put a base implementation in whatever [the lowest compat is (V21 right now)](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java) - we suppress the deprecation there but it's obvious that it's handled, since it's in our compat infrastructure
- put the non-deprecated implementation in the first API where it appears, [V26 here](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java)

It's a little fancy, but works really well to mark which APIs are deprecated and handled and keep the suppression down in larger methods like the one where the API is used

2021-07-16 20:16 UTC, mikehardy commented
Here's a PR that just did a similar thing today even https://github.com/ankidroid/Anki-Android/pull/9275/commits/466448eedb9a57cecd40dc0b644929b97fd2e951

2021-07-16 21:08 UTC, ShridharGoel commented
@mikehardy Updated.

2021-07-16 21:08 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
> +    private final AudioFocusRequest mAudioFocusRequest = new AudioFocusRequest.Builder(AudioManager.AUDIOFOCUS_GAIN)
Yes, that was wrong. But the new implementation does not require that.

2021-07-16 21:09 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
> +    private final AudioFocusRequest mAudioFocusRequest = new AudioFocusRequest.Builder(AudioManager.AUDIOFOCUS_GAIN)
Thanks for informing about this.

2021-07-16 21:33 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
> +import androidx.annotation.RequiresApi;
This one and android.os.Build are no longer needed here now that you're in the Compat infrastructure

2021-07-16 21:34 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
> +import android.media.AudioFocusRequest;
This one might be unnecessary too? Android Studio will tell you all the unneeded imports now

2021-07-16 21:34 UTC, mikehardy requested changes
This looks nice now! All I can think of are unnecessary imports, a tiny nitpick.
Awesome!

2021-07-17 15:14 UTC, mikehardy approved these changes
:zap:

2021-07-17 15:15 UTC, merged

2021-07-17 15:47 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
> +        audioManager.abandonAudioFocusRequest(audioFocusRequest);
This doesn't seem correct, has it been tested?

From the documentation:

> `@param focusRequest the AudioFocusRequest that was used when requesting focus with requestAudioFocus(AudioFocusRequest)`

2021-07-17 15:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
> +        audioManager.requestAudioFocus(audioFocusRequest);
This no longer applies ducking, and instead stops the currently playing music

2021-07-17 16:12 UTC, mikehardy commented
Oh no! New issue to track review comments since it is post-merge? Sorry