Add onboarding library with support for dimmed background
ankidroid/Anki-Android pull request #9291
Opened 2021-07-19 09:36 UTC by ShridharGoel

## Purpose / Description
Add onboarding library with support for dimmed background.
https://github.com/sjwall/MaterialTapTargetPrompt.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-07-23 14:25 UTC, david-allison-1 requested changes
Could you take a quick look at the Decorator pattern and see if we can apply it here (we're very close, but adding in an interface, and coupling calling code to this interface will ensure that we don't "miss" methods that we're inheriting), and removes the inheritance from `PromptBackground`


----

The Wikipedia article is a rather confusing read, but I feel the example should be all that you need. It's very close to your implementation already: https://en.wikipedia.org/wiki/Decorator_pattern#First_example_(window/scrolling_scenario)

2021-07-23 14:25 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedPromptBackground.kt
> +        // Multiplying metrics.heightPixels by 2 to fix issue where bottom area of the screen does not become dimmed.
Can you check this on a tablet? If one metric is off, maybe the width is as well

2021-07-31 02:03 UTC, Arthur-Milchior requested changes

2021-07-31 02:03 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DimmedPromptBackgroundDecorator.kt
> +package com.ichi2.anki
gpl 3, please

2021-07-31 02:03 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DimmedPromptBackgroundInterface.kt
> +package com.ichi2.anki
gpl 3, please

2021-07-31 19:48 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedPromptBackground.kt
> +        // Multiplying metrics.heightPixels by 2 to fix issue where bottom area of the screen does not become dimmed.
Verified on Pixel C API 30 emulator. It's fine.

2021-07-31 19:49 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/DimmedPromptBackgroundDecorator.kt
> +package com.ichi2.anki
Updated.

2021-07-31 19:49 UTC, ShridharGoel commented on AnkiDroid/src/main/java/com/ichi2/anki/DimmedPromptBackgroundInterface.kt
> +package com.ichi2.anki
Updated.

2021-08-01 06:43 UTC, Arthur-Milchior submitted a review, later dismissed

2021-08-02 16:11 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedPromptBackground.kt
> +class DimmedPromptBackground(val mPromptBackground: PromptBackground) : DimmedPromptBackgroundInterface {
If this is a decorator, it should decorate a `PromptBackgroundInterface`

2021-08-03 20:51 UTC, david-allison-1 requested changes
Looks good, added some comments to explain the pattern:

Should be renamed:

* `DimmedPromptBackgroundAdapter` -> `PromptBackgroundAdapter`
* `DimmedPromptBackgroundInterface` -> `PromptBackgroundInterface`
* `DimmedPromptBackgroundInterfaceAdapter` -> `PromptBackgroundInterfaceAdapter`
* `DimmedPromptBackground` -> `DimmedPromptBackgroundDecorator`

2021-08-03 20:51 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DimmedPromptBackgroundInterface.kt
> +interface DimmedPromptBackgroundInterface {
```
interface PromptBackgroundInterface {
```

2021-08-03 20:51 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedPromptBackground.kt
> +     */
Move this documentation to the interface

2021-08-03 20:51 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedPromptBackground.kt
> +    // Taking PromptBackground and passing DimmedPromptBackgroundInterface to primary constructor
No need to explain the code

```suggestion
```

2021-08-03 20:51 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/DimmedPromptBackground.kt
> + * PromptBackground as a parameter in the primary constructor, it is better to use an interface.
```suggestion
* Decorator for [DimmedPromptBackgroundInterface]: Dims the background of the screen so that the highlighted view remains in focus.
```

2021-08-03 20:51 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DimmedPromptBackgroundInterface.kt
> + * Used for changing PromptBackground to DimmedPromptBackgroundInterface.
```suggestion
 * Converts from abstract [PromptBackground] to [PromptBackgroundInterface] to allow extensions of a [PromptBackground] without the requirement to inherit from an empty abstract class.
```

2021-08-03 20:51 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DimmedPromptBackgroundInterface.kt
> +interface DimmedPromptBackgroundInterface {
```
/**
  * Exposes [PromptBackground] as an interface
  * dev: [PromptBackground] is an abstract class with only abstract methods, this unnecessarily forces inheritance from consumers if they want to extend it. This interface allows extension via implementation, flattening the class hierarchy. It can be created by a [DimmedPromptBackgroundInterfaceAdapter] and converted back to a [PromptBackground] via a [DimmedPromptBackgroundAdapter]
 */
```

2021-08-04 08:26 UTC, ShridharGoel commented
@david-allison-1 Thanks for the suggestions, updated.

2021-08-04 16:05 UTC, david-allison-1 approved these changes
LGTM

2021-08-04 16:06 UTC, david-allison-1 commented
```
* What went wrong:
Execution failed for task ':AnkiDroid:ktlintMainSourceSetCheck'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.ConsoleReportWorkAction
   > KtLint found code style violations. Please see the following reports:
     - /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/build/reports/ktlint/ktlintMainSourceSetCheck/ktlintMainSourceSetCheck.txt
```

2021-08-04 21:44 UTC, Arthur-Milchior commented
Thank you very much, I didn't know this pattern design.
Can you please remove the third commit "update", or otherwise explain it/rename it. Appart from that, good to go

2021-08-05 16:14 UTC, mikehardy approved these changes
Arthur's request has been handled (thank you!) - looks good to me, let's go!

2021-08-05 16:14 UTC, merged