Implement elevation for popup menus in Night themes
ankidroid/Anki-Android pull request #9296
Opened 2021-07-20 07:24 UTC by tda1009

## Purpose / Description

AnkiDroid has 2 Night themes: Dark and Black.

Currently in these themes, especially the Black theme, the elevation of the popup menus is not easy to notice, making them look slightly off:

![overflow_before](https://user-images.githubusercontent.com/56965537/126275825-9b088cde-5a1d-4d8d-8184-c1c1e711749f.png)

There are 2 places having this problem: The toolbar's overflow menu (above picture) and the spinners' dropdown menu (following picture):

![spinner_before](https://user-images.githubusercontent.com/56965537/126275936-6c47b439-eab9-4fed-929b-187a7fe8900b.png)

## Approach

In [Material Design Guideline](https://material.io/design/color/dark-theme.html#properties), they suggest using a lighter background color to indicate elevation in these cases, which I think is appropriate.

Also according to Material Design Guideline, in Day themes (Light and Plain) we don't have this problem because in these themes we can use shadow to express elevation. However, shadow is either not possible or not effective in Night themes, because in these themes the shadow's color is either the same as, or very similar to, the theme's color. This makes elevation difficult to notice.

In this PR I proposed the idea that we define a separate color for popup menus to show their elevation.

For the Black theme, I chose a color value which is equivalent to a 8dp elevation (*) as stated in Material Design Guideline. Originally, this requires using a transparent overlay with an alpha component. Luckily there is a simpler way: we can use [this formula from SO](https://stackoverflow.com/a/2049362/3286500) to convert a RGBA color to a RGB color. Using this formula I got the 0x252525 value.

For the Dark theme, using the same formula above, I got value 0x434343.

(*) (I've tried values 4dp and 12dp but I think they were a little too dark and too bright respectively)

Here are the results after implementing elevation:

![overflow_after](https://user-images.githubusercontent.com/56965537/126276951-7835ee90-61d6-437e-9f42-66f65023b719.png)

![spinner_after](https://user-images.githubusercontent.com/56965537/126276969-42129ed1-22c7-4c84-87a4-f33e58b263c5.png)

## How Has This Been Tested?

I've verified (in both emulator and physical phone) that with this change, the popup menus are now easier to notice.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

2021-07-20 11:04 UTC, Akshay0701 requested changes
Thank you so much for the detailed explanation and purpose, it looks good

I just mentioned one cause-related unit test failing.
I think black and dark theme popup color is more similar to each other, maybe try overlay 8%(3dp)?

2021-07-20 12:36 UTC, tda1009 commented on AnkiDroid/src/main/res/values/theme_dark.xml
> +        <item name="popupBackgroundColor">@color/popup_background_dark_theme</item>
My bad, this is due to my last-minute naming change. I've fixed this with a new push. Thank you very much for pointing this out!

2021-07-20 12:36 UTC, tda1009 commented on AnkiDroid/src/main/res/values/theme_black.xml
> +        <item name="popupBackgroundColor">@color/popup_background_black_theme</item>
I've fixed this with a new push. Thank you very much for pointing this out!

2021-07-20 15:36 UTC, tda1009 commented
@Akshay0701 Thanks for your feedback!

I know that the values that I've chosen were subjective. So I will post here some screenshots of different elevation values for everybody to consider.

From left to right: 4 dp, 8 dp and 12 dp.

![popup_black](https://user-images.githubusercontent.com/56965537/126352608-494f4b8e-2b79-4db3-9be3-8e2e9b11bf09.png)

![popup_dark](https://user-images.githubusercontent.com/56965537/126352630-ad073ef4-cea8-400d-a7ba-e5001ba30391.png)

Please review these values and then I will make adjustments accordingly.

2021-07-20 21:43 UTC, prateek-singh-3212 commented
@tda1009 I think 8dp fine. So let's go with 8dp.

2021-07-27 15:43 UTC, mikehardy approved these changes
I like this! What a coincidence though, we have someone else very interested in black theme at the same time, with a separate PR (#9315) - curious what @bobiverse333 thinks?

In the same vein I think 8dp is fine as well.

Verified emulator tests are a remnant of #9282 and not material here as they are fixed on main branch already, okay to merge with that specific failure, pending any specific "don't merge this" feedback from interested parties with bias towards merging in a couple days in absence of feedback

Cheers!

2021-07-27 16:13 UTC, david-allison-1 approved these changes
I'll also tag @LemmusLemmus for thoughts, but looks good to me

2021-07-27 16:44 UTC, LemmusLemmus commented
Looks great! I usually like to keep as much as possible completely black, but since the dropdown menus 
are only open when one is interacting with them it is perfectly fine, if not preferable as is the case here, for them to not be completely black.

Out of curiosity (and consistency), is this the same shade of gray as the menu which appears when long-pressing a deck?
![image](https://user-images.githubusercontent.com/63229554/127193802-940fa5de-3045-4c98-ab0e-b2040f33e81e.png)

2021-07-27 18:45 UTC, bobiverse333 commented
I'm a fan of 8dp. Looks good!

2021-07-28 07:59 UTC, tda1009 commented
Thank you everybody for your comments!

If we all agreed on the chosen values, then we should use them, no more changes needed.

@LemmusLemmus : The FAB button and the dialog you mentioned both have different shades from the values I used in this PR (for the popup menus). According the design guideline from Google, they indeed should be different. However, how much different should they be? I think this also depends on personal tastes as well.

2021-07-28 20:05 UTC, merged

2021-08-05 15:40 UTC, mikehardy commented
Hi there!

If you're already submitted something to OpenCollective for PRs merged in July 2021, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for July 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month)

Thanks!