Updated strings from Crowdin 20210727
ankidroid/Anki-Android pull request #9318
Opened 2021-07-27 15:44 UTC by mikehardy

Standard I18N sync

2021-07-27 15:50 UTC, mikehardy commented on AnkiDroid/src/main/res/values-af/10-preferences.xml
> +    <string name="card_side_both">Question & Answer</string>
These are a problem:

```

ERROR:/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-ml/10-preferences.xml:320:45: Resource and asset merger: The entity name must immediately follow the '&' in the entity reference.
```

2021-07-27 15:50 UTC, david-allison-1 commented
Unit test failure. Likely caused by 

This was input as 

> `<string name="card_side_both">Question &amp; Answer</string>`

https://github.com/ankidroid/Anki-Android/pull/9289/files#diff-019694600ddf48c04a96ea5326a284af3b523cb16e8dc07af2120e791ec232fcR312

But came back as 

> `<string name="card_side_both">Question & Answer</string>`

2021-07-27 15:51 UTC, david-allison-1 commented
When editing in CrowdIn, it appears as `&amp;`, which is correct:

https://crowdin.com/translate/ankidroid/8173/en-ar?filter=basic&value=0

2021-07-27 15:55 UTC, david-allison-1 commented
Likely:

https://github.com/ankidroid/Anki-Android/blob/56e5194b2dd4c7c1d668296acdbc3bfccd4c601e/tools/update-localizations.py#L71

2021-07-27 15:57 UTC, david-allison-1 commented
We need either need a lint check to ensure that strings do not contain an `&` unless they're in a `CDATA` block (or fix the script)

See:

https://github.com/ankidroid/Anki-Android/blob/897f932b6f673327497246894dd2362d1917d287/AnkiDroid/src/main/res/values/02-strings.xml#L260

2021-07-27 23:23 UTC, mikehardy commented on AnkiDroid/src/main/res/values-af/10-preferences.xml
> +    <string name="card_side_both">Question & Answer</string>
Got lucky! Removing that single replacement line in the script seemed valid to me, pushed the results here

2021-07-27 23:25 UTC, mikehardy commented
@david-allison-1 I apologize this is a bit of a 3-in-1, I could untangle to separate PRs but I admit to not caring as much on maintenance / tooling-related items in non-primary languages here.

This should *definitely* be squash-merged though, otherwise the commit history will have a lint-failing commit

2021-07-27 23:31 UTC, david-allison-1 commented
Sorry to be a bother. Could you rebase this into two squashed commits so we can rebase this onto master, rather than squash.

I'm happy with the overall change, but having the "tool change" PR as a separate commit (first) is a strong desire, otherwise it will become lost in the noise of the standard translation sync.

2021-07-27 23:58 UTC, david-allison-1 requested changes
Adding the review for bookkeeping, see comment on rebasing

2021-07-28 00:31 UTC, mikehardy commented
no bother - my git-fu can easily handle that - will get it first thing tomorrow morning (my time)

2021-07-28 20:47 UTC, mikehardy commented
Had something unexpected come up all morning but finally mashed the changes around and have a new batch of commits, what do you think @david-allison-1  ?

2021-07-28 20:49 UTC, david-allison-1 approved these changes
LGTM, never any time pressure here!

2021-07-28 22:56 UTC, merged