added scrollable file list in media check dialog
ankidroid/Anki-Android pull request #9337
Opened 2021-07-30 12:48 UTC by dorrin-sot

## Pull Request template

## Purpose / Description
when the check media dialog is shown the user could not know which files were unused and were to be deleted

## Fixes
Fixes #8850

## Approach
added a linearlayout with two textviews for the dialog content. one contains the overall numbers and the other is scrollable and contains a list of unused files

## How Has This Been Tested?

https://user-images.githubusercontent.com/59933477/127655174-bacf3559-19fe-475b-ad5d-ddc6b63ea415.mov

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-07-30 15:27 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.java
> +                LinearLayout contentLinearLayout = new LinearLayout(builder.getContext()) {{
I like this feature a lot! Nice

I have a couple questions:

- Is there any benefit to building the view here vs using an .xml file to do the layout?
- Is there any way to visually show the area with the file names is an inset scrollview so users are immediately aware they can manipulate it? Something like a 1dp border and having the vertical scrollbar always show if report lines > view lines?

2021-07-30 18:52 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.java
> +                LinearLayout contentLinearLayout = new LinearLayout(builder.getContext()) {{
moved the linearlayout to another xml file and also added a light grey background color to the file list. final result looks like this:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/59933477/127698860-5061efaa-f445-40c1-b2ba-86a6f4516047.png">

2021-07-30 19:28 UTC, mikehardy requested changes
This looks great to me know visually, and is a great feature

- left one comment on a code style settings change that shouldn't be in here
- curious if the XML files for dialogs should have copyright headers? I think they should - could you root around anywhere else in the layout folder to find one with a copyright, and clone it (but with your details)? There must be at least one in there that conforms - we're trying to get all the files licensed up correctly

2021-07-30 19:28 UTC, mikehardy commented on .idea/codeStyles/Project.xml
> -    <JetCodeStyleSettings>
I think is the result of Android Studio popping up a little dialog asking you if you want to apply code styles? This started happening after Kotlin migration and we haven't examined + ingested the change yet

But for this PR it's a separate thing - can you remove this change from the PR?

2021-07-30 20:31 UTC, david-allison-1 reviewed
Second video looks great (I was about to comment on the scrolling)! Only a couple of very minor things

2021-07-30 20:31 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/strings.xml
> +    <string name="unused_strings">\n\nUnused files:\n</string>
Could this be in `03-dialogs` so our translators can pick this up

2021-07-30 20:31 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.java
> +                    fileListTextView.append(unused.stream().collect(Collectors.joining("\n")));
`TextUtils.join` is more idiomatic

2021-07-30 20:43 UTC, dorrin-sot commented on .idea/codeStyles/Project.xml
> -    <JetCodeStyleSettings>
done 😄

2021-07-30 20:50 UTC, dorrin-sot commented on AnkiDroid/src/main/res/values/strings.xml
> +    <string name="unused_strings">\n\nUnused files:\n</string>
done

2021-07-30 20:51 UTC, dorrin-sot commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.java
> +                    fileListTextView.append(unused.stream().collect(Collectors.joining("\n")));
done

2021-07-30 20:55 UTC, dorrin-sot commented
Is it ok if i switch the places for the positive and negative buttons? it looked to me like it would be a ux issue and would be a bit confusing since usually the main button would be on the right and the cancel/dismiss button on the left

2021-07-30 22:42 UTC, mikehardy commented
> Is it ok if i switch the places for the positive and negative buttons? it looked to me like it would be a ux issue and would be a bit confusing since usually the main button would be on the right and the cancel/dismiss button on the left

Good question - this actually intersects with our drive to get RTL (right-to-left) language support correct everywhere. In general I think whatever every other dialog does ("continue on the current path" button on the right in LTR languages / "hold up no, cancel this" button on the left in LTR languages) should be followed, and then in general I think the RTL languages will transpose / lay them out correctly for RTL devices ?

2021-07-30 22:44 UTC, mikehardy commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +
Odd blank space action here - no need to touch it if it's not really changing, this is somehow smaller than a nitpick though, it is like the ghost of a nitpick

2021-07-30 22:46 UTC, mikehardy commented
To be more clear / less philosophical:I think the buttons might be swapped and fit better, based on just re-watching the video. And "OK" should be "Cancel" I think?

2021-07-31 00:24 UTC, dorrin-sot commented on AnkiDroid/src/main/res/values/03-dialogs.xml
> +
done and also switched the buttons (tested for RTL and it changed automatically 👀)

2021-07-31 00:27 UTC, mikehardy approved these changes
This looks great to me!

2021-08-05 03:09 UTC, merged

2021-09-29 01:55 UTC, mikehardy commented
Hi there!

Apologies for the delay, and if you're already submitted something to OpenCollective for PRs merged in August 2021, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for August 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of August)

Thanks!