Don't allow v2 to v1 conversion [Anki Ecosystem]
ankidroid/Anki-Android pull request #9382
Opened 2021-08-06 15:48 UTC by Akshay0701

Fixes #9265

## Done

- removed schedVerPreference from xml and included in java.
- showing schedVerPreference only if user is on V1.
- Added help button in confirmation dialog of v1-> v2 scheduler.

<img src="https://user-images.githubusercontent.com/52353967/128537057-0e6b4613-03ef-45b2-932b-babece9eca46.jpg" width="250" height="500" />

## How Has This Been Tested?
tested on local & emulator devices.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-08-06 16:00 UTC, mikehardy requested changes
approach looks good

2021-08-06 16:00 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                                screen.removePreference(schedVerPreference);
since the pref is dynamic now it won't write into the SharedPreferences object, I don't think, but since in the future we may be going from 4 to 5 on scheduler version, I think we should still store the scheduler they are on. So this should have a prefs setting to 2 and an `.apply()`

2021-08-06 16:01 UTC, mikehardy commented
There's a conflict in here as well, somehow? Make sure you branch off current master before starting to work - rebasing off current master should fix this

2021-08-06 18:03 UTC, Akshay0701 commented on AnkiDroid/src/main/res/values-hu/10-preferences.xml
> +    <string name="sched_v2_summ">V2 schedule is the default, you are still on the V1 scheduler. We recommend upgrading your scheduler to V2</string>
oops, I will fix this, Thanks!

2021-08-06 18:05 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> -    private static final String SCHED_VER = "schedVer";
the reason why I removed the scheduler version as a preference is that we dynamically adding it through java code.

2021-08-06 18:20 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                                screen.removePreference(schedVerPreference);
like this 
``` java
        AnkiDroidApp.getSharedPrefs(getBaseContext()).edit()
        .putBoolean("scheduler_version", 2)
        .apply()

```

2021-08-06 19:40 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                                screen.removePreference(schedVerPreference);
Yeah, except I think it should be int  value 2, not boolean true? The idea is that in the future there will be a 3 (scheduler v3 already exists), and then a 4 etc. Eventually we're going to expose this again, in other words and need to track the version

2021-08-06 19:45 UTC, mikehardy commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="sched_v2_summ_new">V2 schedule is the default, you are still on the V1 scheduler. We recommend upgrading your scheduler to V2</string>
```suggestion
    <string name="sched_v2_summ_new">V2 scheduler is the default but you are still on the V1 scheduler. We recommend upgrading to V2</string>
```

2021-08-06 19:45 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> -            LEARN_CUTOFF, TIME_LIMIT, USE_CURRENT, NEW_SPREAD, DAY_OFFSET, SCHED_VER, NEW_TIMEZONE_HANDLING};
This SCHED_VER constant in the `sCollectionPreferences` array makes me think that I'm wrong about putting it in SharedPreferences - it appears this should actually go into the collection preferences? So my other comment saying "yes" to your question about putting it in android shared preferences and calling `apply` is incorrect.

It appears that we should retain the constant `SCHED_VER` and I think when you call `Collection.changeSchedulerVer` I *assume* (needs verification) that it will set the corresponding value in the collection?

2021-08-06 19:54 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> -            LEARN_CUTOFF, TIME_LIMIT, USE_CURRENT, NEW_SPREAD, DAY_OFFSET, SCHED_VER, NEW_TIMEZONE_HANDLING};
O you confused me 😂,

We already used to set scheduler version using .changeSchedulerVer(),

So we don't need to save it again in android.preferences 👍

2021-08-07 05:08 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> -            LEARN_CUTOFF, TIME_LIMIT, USE_CURRENT, NEW_SPREAD, DAY_OFFSET, SCHED_VER, NEW_TIMEZONE_HANDLING};
here the meaning of all sCollectionPreferences array elements is just the id of preferences buttons(which is in XML), this element has nothing to do with `Collection.changeSchedulerVer`.

and we programmatically adding the schedVerPreference preferences button,
and in order to save the sched version, all we need to do is `getCol().changeSchedulerVer(version)`

i.e I think `SCHED_VER` is not required.

2021-08-08 15:57 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> -            LEARN_CUTOFF, TIME_LIMIT, USE_CURRENT, NEW_SPREAD, DAY_OFFSET, SCHED_VER, NEW_TIMEZONE_HANDLING};
Oh interesting - I totally misread that then. Agreed

2021-08-08 15:58 UTC, mikehardy approved these changes
This LGTM then

2021-08-08 16:22 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                screen.addPreference(schedVerPreference);
yes and there is a reason behind it, actually all preference buttons above "About AnkiDroid" is included in the XML file,
and this "v2 scheduler, trigger test crash" button is included after that through java code,

let me know how we can insert this preference button at top of the layout?

2021-08-08 16:39 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                screen.addPreference(schedVerPreference);
I haven't done this but I suppose you need to find the preference group then add this to the same group and set the order? https://developer.android.com/reference/android/preference/Preference#setOrder(int)

2021-08-08 17:57 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                screen.addPreference(schedVerPreference);
Thanks!, I looked upon this in detail and found that we don't need to group in order to set the order,

now I set the scheduler button to its previous position, done!

2021-08-08 18:03 UTC, Akshay0701 commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="sched_v2_summ_new">V2 scheduler is the default but you are still on the V1 scheduler. We recommend upgrading to V2</string>
Okay, I understand,
then should I change the string here ?

if yes, then what it would be?

2021-08-08 18:16 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
> +                screen.addPreference(schedVerPreference);
Nice

2021-08-08 18:18 UTC, mikehardy commented on AnkiDroid/src/main/res/values/10-preferences.xml
> +    <string name="sched_v2_summ_new">V2 scheduler is the default but you are still on the V1 scheduler. We recommend upgrading to V2</string>
Good question - for now then I guess remove the change here - stick with original `sched_v2_summ`

2021-08-08 19:49 UTC, mikehardy approved these changes
Ok - LGTM - really hard to get these things just right! The scheduler is just so fundamental. Thanks for working through everything @Akshay0701 - @david-allison-1 any thoughts?

2021-08-08 19:56 UTC, david-allison-1 approved these changes
LGTM

2021-08-08 19:57 UTC, david-allison-1 requested changes
Actually, sorry for the nit: a string was removed in the second commit. 

I think this should have been in the first, otherwise the first commit would fail the lint checks

2021-08-08 21:42 UTC, mikehardy commented
Okay - pending merge after commit ordering so there isn't a time in the commit history lint fails

2021-08-09 18:18 UTC, Akshay0701 commented
Done!

2021-08-09 18:19 UTC, david-allison-1 approved these changes
Cheers!

2021-08-09 18:33 UTC, merged