Reset onboarding
ankidroid/Anki-Android pull request #9385
Opened 2021-08-08 16:43 UTC by Arthur-Milchior

This allow all onboarding flags to be reset. It is useful for testing, in order to avoid resetting AnkiDroid data. I also expect it may be useful for users if they want to see again everything, to either show the app to other people or just check whether they can learn new things.

I'd like a review from @ShridharGoel since it's your part of the code.

2021-08-08 19:44 UTC, ShridharGoel approved these changes
Thanks, just a small grammatical fix.

2021-08-08 19:44 UTC, ShridharGoel commented on AnkiDroid/src/main/res/values/constants.xml
> +    <string name="reset_onboarding_desc">Show all tutorial again</string>
Should be 'tutorials' instead of 'tutorial'.

2021-08-08 21:18 UTC, david-allison-1 requested changes
I'm likely misunderstanding something, I don't see how the preference works

2021-08-08 21:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +        fun addFeature(featureCategory: String) {
This doesn't appear to be used outside tests. How does the preference work?

2021-08-08 21:18 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +         * It ensures it gets resetted if asked. */
```suggestion
         * It ensures it gets reset if asked. */
```

2021-08-08 22:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +        fun addFeature(featureCategory: String) {
It is indeed not currently used. For the same reason that `isVisited` or `setVisited` is not used. 
It should be used when features are added. So if we merge @ShridharGoel 's PR first I'll add it myself and push. If this one get merged first, I'll ask him to add his features with this function so that "reset" reset his features

2021-08-08 22:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
> +         * It ensures it gets resetted if asked. */
done

2021-08-09 04:40 UTC, david-allison-1 approved these changes
LGTM

2021-08-09 15:27 UTC, merged

2021-08-10 04:39 UTC, Arthur-Milchior commented
@ShridharGoel can you please uses `addFeature` for all feature category you use for onboarding please?