Implemented Drawing Activity
ankidroid/Anki-Android pull request #9394
Opened 2021-08-10 07:43 UTC by Akshay0701

## Pull Request template

## Done

- created empty drawing activity
- extracted createInstance in a method of whiteboard
- change WeakReference<AbstractFlashcardViewer> to AnkiActivity in whiteboard to let other activities use whiteboard view.
- added drawing button in BasicImageFieldController

will upload a gif of working.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-08-10 07:44 UTC, Akshay0701 commented
I think commits should split, 
could you suggest me order for small commits?

2021-08-10 17:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.kt
> +        toolbar?.let { enableToolbar(it) }
```suggestion
        enableToolbar()
```

2021-08-10 17:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +            AbstractFlashcardViewer cardViewer = (AbstractFlashcardViewer) mAnkiActivity;
We need to use an interface here, rather than perform a cast (which will fail)

2021-08-10 17:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +        bitmap.compress(Bitmap.CompressFormat.JPEG, 95, new FileOutputStream(saveWhiteboardImageFile));
This code change was converted - we need to undo it

2021-08-10 17:32 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
> +        Uri uri = Uri.fromFile(new File(drewImagePath));
Will this work under scoped storage?

2021-08-10 17:33 UTC, david-allison-1 commented
I think these are good (only changed the order)

1. extracted createInstance in a method of whiteboard
1. change WeakReference to AnkiActivity in whiteboard to let other activities use whiteboard view.
1. created drawing activity
1. added drawing button in BasicImageFieldController

2021-08-10 17:36 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +        // we didn't handle multi-touch in draw activity because it will going to be empty
okay will remove it

2021-08-10 17:37 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +            AbstractFlashcardViewer cardViewer = (AbstractFlashcardViewer) mAnkiActivity;
how to do that, is there any previous example that I can refer?

2021-08-10 17:40 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
> +        Uri uri = Uri.fromFile(new File(drewImagePath));
i think we are saving whiteboard image in different folder outside of ankidroid media

but, i am not sure.

2021-08-10 17:41 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
> +        Uri uri = Uri.fromFile(new File(drewImagePath));
what we can do here instead?

2021-08-10 17:48 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
> +        Uri uri = Uri.fromFile(new File(drewImagePath));
The whiteboard code was changed to work under scoped storage very recently, you reverted the implementation in this PR (mentioned in another comment).

Once we move back to this new implementation, I expect it'll work

2021-08-10 17:49 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +            AbstractFlashcardViewer cardViewer = (AbstractFlashcardViewer) mAnkiActivity;
Something along the lines of https://github.com/ankidroid/Anki-Android/blob/806410f0e13d01d55bac641c9bd606833f9ab067/AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerUi.java#L19-L37

2021-08-14 01:07 UTC, farjadilyas commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
> +    Uri saveImage(Context context, Bitmap bitmap, String baseFileName, String extension, Bitmap.CompressFormat format, int quality) throws FileNotFoundException;
This return type change should probably be in a different commit/PR since it fixes a separate problem. Previously, the strings returned were inconsistent between implementations since CompatV21 implementation returned the absolute file path, but the CompatV29 implementation returned a URI string. Moreover, returning URI is a better approach since direct file path access generally won't work under Scoped Storage (it will for the directory whiteboards are saved in through). Hence, returning a URI will turn out to be more useful since we can definitely use the returned URI to access the saved file. Sorry you had to fix this!

2021-08-17 02:29 UTC, david-allison-1 reviewed
This looks great! One comment regarding the cast to `AbstractFlashcardViewer`, the rest are nitpicks

Blocked by #9409

2021-08-17 02:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.kt
> +            Timber.e(e)
```suggestion
            Timber.w(e)
```

2021-08-17 02:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +            AbstractFlashcardViewer cardViewer = (AbstractFlashcardViewer) mAnkiActivity;
Still pending this, PM me on discord if you'd like me to take it on

2021-08-17 02:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
> +            Timber.e("handleDrawingResult() no image path provided");
```suggestion
            Timber.w("handleDrawingResult() no image path provided");
```

2021-08-17 02:29 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
> +            Timber.e("");
```suggestion
            Timber.w(e);
```

2021-08-17 02:29 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/constants.xml
> +    <string name="drawing">Drawing</string>
Let's move this to 01-core

2021-08-17 02:30 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
> +    Uri saveImage(Context context, Bitmap bitmap, String baseFileName, String extension, Bitmap.CompressFormat format, int quality) throws FileNotFoundException;
Fixed in #9409

2021-08-17 05:29 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +            AbstractFlashcardViewer cardViewer = (AbstractFlashcardViewer) mAnkiActivity;
i wanted to learn interface, 

see, is this right https://stackoverflow.com/a/45602366/14148406

2021-08-17 05:39 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +            AbstractFlashcardViewer cardViewer = (AbstractFlashcardViewer) mAnkiActivity;
I'll message you, it's a little long for GitHub

2021-08-17 06:43 UTC, david-allison-1 reviewed
Much nicer!

2021-08-17 06:43 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +        }
Also, change the name, and add documentation 
```suggestion
        mAbstractFlashcardViewerUI = abstractFlashcardViewerUI
```

2021-08-17 06:43 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/WhiteboardMethods.java
> +public interface WhiteboardMethods {
Could do with a better name and javadocs, but this is exactly what we need code-wise

2021-08-17 06:43 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +public class Whiteboard extends View implements WhiteboardUi{
Shouldn't be needed

2021-08-17 06:44 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
> +    public static Whiteboard createInstance(AnkiActivity context, HandleTouch handleTouchControl, WhiteboardMethods abstractFlashcardViewerUI) {
add a `@Nullable`  annotation on abstractFlashcardViewerUI, and also for the variable

2021-08-18 21:16 UTC, david-allison-1 commented
unblocked, awaiting de-conflict

2021-08-20 17:21 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/WhiteboardMethods.java
> +public interface WhiteboardMethods {
``` java

/**
 * WhiteboardMethods interface will provide abstract methods to override by abstractflascardviewer class
 * for handling multi touch while whiteboard is on.
 */
public interface WhiteboardMultiTouchMethods {

```

see this, is this doc correct, it would be great if you could suggest me some names...

2021-08-20 17:32 UTC, Akshay0701 commented
sorry, I didn't get much time last week, but now I am free so let's get this done...

![](https://media4.giphy.com/media/7Sh3Pt6R9ELubdoH3K/giphy.gif)

2021-08-21 00:19 UTC, david-allison-1 reviewed
Two very minor things, but LGTM!

2021-08-21 00:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/WhiteboardMethods.java
> +public interface WhiteboardMethods {
Sounds great!

Slight change to the documentation. You want to try to avoid referencing a concrete implementation for an interface (although it's often useful to provide an example).

``` java
/**
 * Provides callbacks for multi touch handling on a whiteboard
 */
public interface WhiteboardMultiTouchMethods {
```

2021-08-21 00:19 UTC, david-allison-1 commented on AnkiDroid/src/main/res/menu/drawing_menu.xml
> +        android:enabled="true"
I don't know, but don't think this is necessary, could you comment if it is

```suggestion
        android:enabled="true"
```

2021-08-21 01:08 UTC, david-allison-1 commented
Tried this on an API 21 emulator and the image was far lager than the screen viewport

![Uploading image.png…]()

2021-08-21 05:50 UTC, Akshay0701 commented on AnkiDroid/src/main/res/menu/drawing_menu.xml
> +        android:enabled="true"
I copied this from another code and forgotten to remove it,

it is not required.

2021-08-21 06:35 UTC, Akshay0701 commented
> Tried this on an API 21 emulator and the image was far lager than the screen viewport

yes your right, what can we do for fixing this?

2021-08-21 18:13 UTC, david-allison-1 commented
> > Tried this on an API 21 emulator and the image was far lager than the screen viewport
> 
> yes your right, what can we do for fixing this?

We can calculate the dimensions of the screen, how about scaling the image to that before saving?

2021-08-22 08:39 UTC, Akshay0701 commented
yes we will do this,

but @david-allison-1 it is not the only problem of drawing activity even gallery photos also appear far larger in preview in devices API 21.

2021-08-22 08:41 UTC, Akshay0701 commented
@mikehardy what do you say,

do we have a userbase of API 21 or below?

should we rescale the image before saving it?

2021-08-22 12:52 UTC, mikehardy commented
Yes, minsdkversion is still 21, won't move for a while, the whole android ecosystem just moved up to it in fact. Probably a year or more before it goes higher. Still tens of thousands of users

2021-08-23 05:53 UTC, Akshay0701 commented
created an issue for this #9439

2021-08-23 06:21 UTC, david-allison-1 requested changes
Discussed with @Akshay0701, moving the issue of the image size to #9439

Could we find out which API version this issue is resolved with, and limit the feature to API versions that are working correctly (likely via `@Requires()` with a comment, and make the button `gone` if it's not  available).

Note that since we haven't diagnosed the issue, it may be screen size related, in which case we should get it fixed before getting this feature in.

2021-08-23 11:57 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
> +        }
I found #9439 valid till API 23..

2021-08-23 12:06 UTC, Akshay0701 commented
> Note that since we haven't diagnosed the issue, it may be screen size related, in which case we should get it fixed before getting this feature in.

David, I am sure this issue is not related to screen size, because 
I tried pixel 1(1080 x 1920: 420 dpi)  with  API version 21,22,23 and this issue occurred at all times.
and I tried again with the same devices pixel 1 with API version 24 and the issue didn't occur there.

2021-08-23 13:40 UTC, david-allison-1 commented
Could you add a comment on the API restriction listing the issue number, then good to go!

2021-08-23 15:37 UTC, Akshay0701 commented
i think i already did comment with issue number

2021-08-24 04:13 UTC, david-allison-1 approved these changes
Ah, was missed in the GitHub preview. LGTM!

2021-08-24 19:02 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
> +    }
This to me is `return internalizeUri(uri).getAbsolutePath()`, which is defined just below this method
In fact, there is a proliferation of methods like this:
- MediaRegistration::loadImageIntoCollection does it
- FileUtil::internalizeUri does it

Why are we duplicating the process of "take a URI, copy the contents of it into our local area and give me a file" in so many places? :thinking: 

I may be missing something, but I would love for this logic to be in one spot

2021-08-24 19:03 UTC, mikehardy requested changes
I like this a lot - it appears to me that all the things required for it to *actually work*, are working. Which is awesome. My only concern is that I've seen this URI-->File logic in so many places and it looks like this is adding another? Can we avoid it at all?

2021-08-25 11:18 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
> +    }
Great review, Thank you for letting me know about the `internalizeUri` method, I was unaware of this method,
Done now.

2021-08-25 13:51 UTC, mikehardy approved these changes
Nice! thanks for the shift to internalizeUri

2021-08-25 13:52 UTC, merged