Update anki URLs to use HTTPS by default
ankidroid/Anki-Android pull request #9400
Opened 2021-08-12 11:08 UTC by titze

## Pull Request template

## Purpose / Description

Replaces all `http://anki*` URLs with HTTPS.

For most, this is simply best practise, but e.g., for the `resetpw`, this could negatively affect a user if the connection is initiated over http.

## How Has This Been Tested?

All URLs are available via `HTTPS`.

## Learning (optional, can help others)
HTTP-URLs can be a security issue even if the http URL redirects to https on the server.

If is secure if the connection is already established, the connection is secure (assuming the server and client do not do anything wrong like disabling certificate checks)
But if an attacker is present on the network during the setup, he can just intercept the http-connection-setup, and forward that to their own server. Then you would never see the request on the server. This is not possible if the setup were already over https.

2021-08-12 16:15 UTC, Akshay0701 approved these changes
Thank you so much! @titze,
is there any reason to make 2 commits here?
I suggest squash merge two commits into one.

2021-08-13 06:06 UTC, titze commented
Updated as suggested. I did not know about the translations.

There was no particular reason for having two commits before, I expected them to be squashed before landing.

2021-08-13 07:10 UTC, Akshay0701 commented
Good, Thanks!

2021-08-13 14:35 UTC, mikehardy requested changes
Thanks for posting this! I agree completely with the direction here

@Arthur-Milchior made a great point here:

> For the translations, we should figure out what to do. Seems obvious to me anyway that having a link in the resource is a bad idea, as it makes any update complex. If you can remove the translations, it would be well

Here is the original (`/values/`, not language-specific) translation:

https://github.com/ankidroid/Anki-Android/commit/fca031c3fa9b1ec8ed789fbc13ecb800134d84b3#diff-55582f3477f88d22e8e7acfbac5e2fdea81e4f8f298e0b1b91ec60093e6e3a04R188

We need the string to be translatable but we need the URL to *not* be in the string, so that we may update it.

The download link should be added to constants, the current string should be removed (since it needs re-translating, unfortunately) and a new one should be added (same key perhaps, except with `_new` suffix?) that has a `%s` in it for the URL, then in the spot where that key is used the code needs a slight alteration to do a string format and interpolate the new link constant for downloads into the translated strings `%s` slot

2021-08-13 15:41 UTC, titze commented
Sure, I can change this.
But I am traveling the next two weeks, and can only handle this after that.

2021-08-13 16:02 UTC, mikehardy commented
It's open source, never any time pressure, it can certainly wait!
Thanks

2021-09-06 11:27 UTC, titze commented
@mikehardy why do we need the `_new` key? Couldn't I just change the string to 
```
        This is an Anki flashcards deck sent from <a href="%ANKIDROID_MANUAL_URL%">AnkiDroid</a>.
```

And then that gets translated eventually? Adding the string replacing then won't do much until this is translated.

Also I am unsure if this should be in the same PR, as it is a bit of a different task.

2021-09-06 11:54 UTC, david-allison-1 commented
> why do we need the _new key?

See docs [\[1\]](https://developer.android.com/guide/topics/resources/string-resource) [\[2\]](https://stackoverflow.com/questions/2397613/are-parameters-in-strings-xml-possible) for how Android handles translations idiomatically, these don't support named parameters. Breaking from standard convention without reasonable justification leads to maintenance burden, increased learning curve, and ultimately bugs.

Wit idiomatic Android, we need to wipe the key from CrowdIn (which is what a rename with `_new` does), otherwise we have some translated strings with a format string, and some strings without, which will fail CI/crash the program.

In addition, just changing the `values` to a format string means that we have strings which would still be using the hardcoded value, which is what this (series) of PRs should aim to fix. We likely have a few unmaintained languages and run under the assumption that our volunteer translators may never get around to it.

> Also I am unsure if this should be in the same PR, as it is a bit of a different task.

Happy to keep it in this PR as long as it's in an atomic commit: up to you. 

PS: Your git `user.email` isn't linked to your GitHub account, you may want to fix this (both the public email and the `noreply` GitHub email work for commit linkages). Let me know if you want elaboration on this point.

2021-09-08 20:43 UTC, titze commented
I see, I did not know how the format strings would be used in the code, but the links clarified this.

The thing I do not understand yet:
If I just add a `_new`, then this will only be there in the english version at first, and only once the translations are added will the message also be in that language. So for a while it will not be translated? Or am I missing something?

2021-09-09 01:16 UTC, david-allison-1 commented
> I see, I did not know how the format strings would be used in the code, but the links clarified this.
> 
> The thing I do not understand yet:
> If I just add a `_new`, then this will only be there in the english version at first, and only once the translations are added will the message also be in that language. So for a while it will not be translated? Or am I missing something?

Yes, by default, Android will use `values` if no other strings exist.

After we perform a sync with CrowdIn, each file will then contain the English strings.

2021-09-18 10:13 UTC, titze commented
I moved the URLs out of the strings.xml.

But I am still not sure I understand the translation process. If this PR is ok, would that just land, and the translatons of `export_email_text_new` will be missing, and then those will be added in another commit?

2021-09-18 15:48 UTC, mikehardy requested changes
Hi there - I suggested some links that are tested vs the old ones that appeared broken

I found an issue with the ankisrs donations link that I'll peel to another issue

But the most important bit is that the translation itself for the email HTML text did not appear functional - I made a suggestion there but it needs testing, to be specific, I/we need to hear "yeah, I made these changes locally and shared a deck and the translation was right with the correct links", because I don't think that hurdle was met prior and I believe running the real test would have shown it prior to commit

To your question about translations, yes - all translations start as entries in no other place except in the "values" directory, because they are not translated yet. That's step 1, we're doing that here with a new string. Step 2 is we hit the "Sync Translations" workflow here in GitHub, it runs some scripts that push the *untranslated strings / changes* out to crowdin.com where our translators do their thing, then it pulls in the results and commits them as a translation sync

If you're interested:
https://github.com/ankidroid/Anki-Android/blob/master/.github/workflows/sync_translations.yml
An example commit: https://github.com/ankidroid/Anki-Android/commit/647d84fd3bbba564de129a570e4abfd22b90e085

2021-09-18 15:48 UTC, mikehardy commented on api/src/main/java/com/ichi2/anki/api/AddContentApi.java
> +     * See the <a href="https://ankisrs.net/docs/manual.html#cards-and-templates">Anki Desktop Manual</a> for more help
Verified correct / current link

```suggestion
     * See the <a href="https://docs.ankiweb.net/templates/intro.html">Anki Desktop Manual</a> for more help
```

2021-09-18 15:48 UTC, mikehardy commented on api/src/main/java/com/ichi2/anki/FlashCardsContract.java
> + * <a href="https://ankisrs.net/docs/manual.html#the-basics">the basics section in the Anki manual.</a>
```suggestion
 * <a href="https://docs.ankiweb.net/getting-started.html#key-concepts">the basics section in the Anki manual.</a>
```

2021-09-18 15:48 UTC, mikehardy commented on README.md
> +A semi-official port of the open source [Anki](https://ankisrs.net/index.html) spaced repetition flashcard system to Android. Memorize anything with AnkiDroid!
```suggestion
A semi-official port of the open source [Anki](https://apps.ankiweb.net/index.html) spaced repetition flashcard system to Android. Memorize anything with AnkiDroid!
```

2021-09-18 15:48 UTC, mikehardy commented on AnkiDroid/src/main/res/values/constants.xml
> +    <string name="link_donation">https://ankisrs.net/support</string>
This is a strange one! I examined the link, and it's not valid. So I examined the "About AnkiDroid" dialog from the app directly (Settings --> Advanced --> About AnkiDroid) and there is no evidence of the link.
From [`AnkiDroid/src/main/java/com/ichi2/anki/Info.java`](https://github.com/ankidroid/Anki-Android/blob/12bce36712d212fa14e06e777e8886c8908c69cf/AnkiDroid/src/main/java/com/ichi2/anki/Info.java#L127) it should be link substitution 2 in array element 3 of [`AnkiDroid/src/main/res/values/03-dialogs.xml`](https://github.com/ankidroid/Anki-Android/blob/12bce36712d212fa14e06e777e8886c8908c69cf/AnkiDroid/src/main/res/values/03-dialogs.xml#L42) but there is only one substitution in that translation string array element

So, questions:

- is this link used in *any* translations? If not, the whole translation should be deleted, that is, this line in this file should simply be removed
- how is it that android lint is not recognizing this as a substitution failure and erroring / warning that there are more translations attempted for substitution than there are substitution slots ?
I will not block this PR based on investigation of this, intended outcome is that this comment is peeled off to a new issue (an easy github trick from the menu on comments...)

2021-09-18 15:48 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    </string>
This looks close, but now the "export_email_text" string needs to be removed. 
Stated differently for the avoidance of doubt: delete "export_email_text" line

And the substitutions need positional modifiers so that the right string goes in the right spot

```suggestion
    <string name="export_email_text_new">
        <![CDATA[
        Hi!
        <br/><br/>
        This is an Anki flashcards deck sent from <a href="%1$s">AnkiDroid</a>.
        Try to open it using one of the available <a href="%2$s">Anki distributions</a> and enjoy easy and efficient learning!
        ]]>
    </string>
```

2021-09-18 15:48 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.java
> +                .setHtmlText(mActivity.getString(R.string.export_email_text_new, mActivity.getString(R.string.link_manual), mActivity.getString(R.string.link_distributions)))
I can't see how this is correct :thinking: 
I think you need to `setHtmlText` with the result of a `String.format` *on* a `getString` of the translated string, substituting in the `getString`s of the links?

I believe like this, though this is just coded into a web text box, may not compile + needs testing

```suggestion
                .setHtmlText(String.format(mActivity.getString(R.string.export_email_text_new), mActivity.getString(R.string.link_manual), mActivity.getString(R.string.link_distributions))
```

2021-09-18 18:30 UTC, titze commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.java
> +                .setHtmlText(mActivity.getString(R.string.export_email_text_new, mActivity.getString(R.string.link_manual), mActivity.getString(R.string.link_distributions)))
https://developer.android.com/reference/android/content/Context#getString(int,%20java.lang.Object...)

> Returns a localized formatted string from the application's package's default string table, substituting the format arguments as defined in Formatter and String.format(String, Object...).

I tested this locally (which was not trivial, since at first I did not find the sharing this was used :/), and the string is filled as expected with my original code.

2021-09-18 18:30 UTC, titze commented
Removing `export_email_text` results in several
> warn: removing resource com.ichi2.anki:string/export_email_text without required default value.

But I guess that is ok / expected.

2021-09-18 18:34 UTC, titze commented on AnkiDroid/src/main/res/values/constants.xml
> +    <string name="link_donation">https://ankisrs.net/support</string>
I also did not see where this is used. Not sure this can even be found by the linter, since the `link_donation` is actually used in the code, but as you said, "incorrectly".

2021-09-19 15:24 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.java
> +                .setHtmlText(mActivity.getString(R.string.export_email_text_new, mActivity.getString(R.string.link_manual), mActivity.getString(R.string.link_distributions)))
Fascinating, I believe you (both that testing it was probably a pain, and that it works) but that means I have some incorrect understanding in my head. I'll re-read the diff here and think about it again, thanks for reporting your results

2021-09-19 16:23 UTC, david-allison-1 requested changes
This looks good to me! Awaiting a re-review from @mikehardy on the points that I've commented on.

Since you've fixed some links, I've fixed the rest as suggestions. The "fixing of links" should ideally be performed in a commit before the conversion to HTTPs, so could you rebase the commits around to look like:

* fix links to point to new documentation
* update HTTPs on links
* extract the formatters from the format string

The above will allow us to rebase+merge the commit, to retain the history for future developers to better understand the changes.

----

I'll move the "donations unused" to a separate issue. ~~We may be able to add unit tests to ensure that these translations are used, as the current mechanism is 'strange'~~ EDIT: We could, but it's quite a lot of work for little gain

2021-09-19 16:23 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.java
> +                .setHtmlText(mActivity.getString(R.string.export_email_text_new, mActivity.getString(R.string.link_manual), mActivity.getString(R.string.link_distributions)))
This looks correct to me from casual observation: the format strings should be inside `getString`, as they're placeholders in the .xml resource

2021-09-19 16:23 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/constants.xml
> +    <string name="link_donation">https://ankisrs.net/support</string>
This is used incorrectly (used in code, but not displayed). It's not picked up by our lint checks as we:

* Get the string from an array
* Apply substitutions to this string via `String.format`, rather than the Android `getString()`

It should be removed, but let's handle this in a separate issue/PR

2021-09-19 16:23 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/constants.xml
> +    <string name="link_distributions">https://ankisrs.net/#download</string>
```suggestion
    <string name="link_distributions">https://apps.ankiweb.net/#download</string>
```

2021-09-19 16:23 UTC, david-allison-1 commented on api/src/main/java/com/ichi2/anki/FlashCardsContract.java
> +     * <a href="https://ankisrs.net/docs/manual.html#searching">in the search section of the Anki manual</a>.
```suggestion
     * <a href="https://docs.ankiweb.net/searching.html">in the search section of the Anki manual</a>.
```

2021-09-19 16:23 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> + * @see <a href="https://ankisrs.net/docs/manual.html#cards">the Anki Desktop manual</a>
```suggestion
 * @see <a href="https://docs.ankiweb.net/getting-started.html#cards">the Anki Desktop manual</a>
```

2021-09-19 17:28 UTC, mikehardy commented on api/src/main/java/com/ichi2/anki/FlashCardsContract.java
> +     * <a href="https://ankisrs.net/docs/manual.html#searching">in the search section of the Anki manual</a>.
Thanks for these - I didn't scan the ones that were already https but yeah, Anki's upstream docs moved around quite a bit!

2021-09-19 17:31 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.java
> +                .setHtmlText(mActivity.getString(R.string.export_email_text_new, mActivity.getString(R.string.link_manual), mActivity.getString(R.string.link_distributions)))
I understand from David that getString is better, and after carefully re-reading, I see I was mis-counting open/closed parens leading to my further confusion as I thought they were balanced differently then they were. This is great

2021-09-19 17:33 UTC, mikehardy approved these changes
@david-allison-1 I'm concerned that on a first PR tacking on a whole lot of git overhead (commit separation + re-arrange) etc is a really high bar for not a lot of benefit on this specific PR. It's a clear step forward, all the specific changes look good to me at the moment, and I'd just squash+merge and move personally. What think you, sir?

@titze thanks for working with us to get this thing through :-)

2021-09-19 17:41 UTC, david-allison-1 commented
> It's a clear step forward, all the specific changes look good to me at the moment, and I'd just squash+merge and move personally. What think you, sir?

Sounds good to me, awaiting the proposed link changes, then good to merge

2021-09-19 18:09 UTC, titze commented
It wasn't really more complicated to create 3 commits, and looks much cleaner imo this way.

2021-09-19 18:27 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="export_email_text_new">
This presumably won't build, as the string constant has changed without changing the code

2021-09-19 18:28 UTC, david-allison-1 commented
Getting atomic buildable commits is a little effort, happy to see this squash-merged at this point.

We need each commit to build so we can `git bisect` any bug within the app

2021-09-19 18:29 UTC, david-allison-1 approved these changes

2021-09-19 18:31 UTC, titze commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="export_email_text_new">
:facepalm:

2021-09-19 19:47 UTC, mikehardy approved these changes
squeaky clean now, to my eye. very nice!

2021-09-19 19:52 UTC, mikehardy commented
> It wasn't really more complicated to create 3 commits, and looks much cleaner imo this way.

certainly cleaner but sometimes git stuff is a real burden for a contributor if people are trying to learn git and our codebase and android all at the same time, so I try to tread that fine line between pushing for perfect commits and still being biased towards getting things done and accepting that "perfect" is kind of an illusion anyway, while people progressively learn. I think you nailed this one though thank you!

2021-09-21 22:05 UTC, merged

2021-12-12 01:49 UTC, mikehardy commented
Hi there! **September OpenCollective Notice**

Apologies for the delay, and if you're already submitted something to OpenCollective for PRs merged in **September** 2021, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for September 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of August)

Thanks!