Introduce WindowInsets
ankidroid/Anki-Android pull request #9406
Opened 2021-08-13 14:33 UTC by noahwe145

## Pull Request template

## Purpose / Description
Deprecated UI-Flags should be replaced by WindowInsets.  

## Fixes
https://github.com/ankidroid/Anki-Android/issues/9332

## Approach
WindowInsets and WindowInsetsController are used

## How Has This Been Tested?
Unit tests
979 tests completed, 560 failed, 17 skipped

_Links to blog posts, patterns, libraries or addons used to solve this problem_
https://stackoverflow.com/questions/62643517/immersive-fullscreen-on-android-11
https://stackoverflow.com/questions/64151280/android-r-api-30-system-bar-visibility-change-call-backs

## Checklist
_Please, go through these checks before submitting the PR._

- [x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x] You have commented your code, particularly in hard-to-understand areas
- [x ] You have performed a self-review of your own code
- [x ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-08-14 17:33 UTC, david-allison-1 requested changes
Thanks for the PR!

This adds `@RequiresApi(api = Build.VERSION_CODES.R)` to many vital methods, we should instead be using, or adding methods to our `Compat`/`CompatHandler` infrastructure:

https://github.com/ankidroid/Anki-Android/tree/0c1a38ea34babb569ff5c1ff17ab96b337a55bb8/AnkiDroid/src/main/java/com/ichi2/compat

2021-08-19 10:07 UTC, noahwe145 commented
i added
`if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
       changes
} else {
         deprecated code
 }
`
to all changes so it should be backward compatible

2021-08-24 02:08 UTC, david-allison-1 requested changes

2021-08-24 02:08 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +        }
Thanks! Could you move this into our `compat` infrastructure.

See the following for an example:

https://github.com/ankidroid/Anki-Android/tree/0c1a38ea34babb569ff5c1ff17ab96b337a55bb8/AnkiDroid/src/main/java/com/ichi2/compat

You can also Ctrl+F for `CompatHelper.getCompat()` to find usages

2021-08-29 15:16 UTC, david-allison-1 requested changes
Thanks! Looks good. Could you do the same (using `Compat`) for the other changes

2021-08-29 15:16 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +            compat.setFullscreen(getWindow());
Much nicer! Just a nitpick

```suggestion
            CompatHelper.getCompat().setFullscreen(getWindow();
```

2021-08-29 15:16 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +
nitpick: could you avoid changing whitespace in a diff

2021-08-29 15:16 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
Could you go through and convert each of these usages to the Compat infrastructure?

2021-09-06 17:32 UTC, noahwe145 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
yeah sure

2021-09-24 12:19 UTC, noahwe145 commented
i moved all changes i could, some were not possible because they use private functions of Reviewer

2021-09-24 20:04 UTC, david-allison-1 commented
Thanks, please follow up if I haven't re-reviewed this by Sunday

2021-10-05 15:31 UTC, noahwe145 commented
@david-allison-1  sorry, forgot to remind you

2021-10-06 02:35 UTC, david-allison-1 reviewed
Sorry about the delay! This wasn't a good one to review on the phone.

A few nitpicks, my main concern is adding documentation as this is a fairly new area.

My other concern is `isImmersiveSystemUiVisible`. 

I'll further test this on my Android 11 after the stylistic changes and documentation are added

2021-10-06 02:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +import android.os.Build;
(minor/nitpick) a few of these imports are no longer needed

2021-10-06 02:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
> +            CompatHelper.getCompat().setFullscreen(getWindow());
Looks great!

2021-10-06 02:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +        CompatHelper.getCompat().hideSystembars(getWindow());
nit: Could you rename the method to `hideSystemBars`

2021-10-06 02:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
> +        //Hide System Bars
Doesn't need a comment - the method name is good enough

```suggestion
```

2021-10-06 02:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.java
> +
```suggestion
        CompatHelper.getCompat().setFullscreen(getWindow());
```

2021-10-06 02:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
> +
Aim to not change whitespace - it makes the diffs/git history harder to reason about 

```suggestion
```

2021-10-06 02:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV30.java
> +
This needs a copyright header. There should be a lint warning here with instructions on how to set this to be inserted manually

2021-10-06 02:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV30.java
> +/** Implementation of {@link Compat} for SDK level 30 and higher. Check  {@link Compat}'s for more detail. */
I love this comment, great!

```suggestion
/** Implementation of {@link Compat} for SDK level 30 and higher. Check {@link Compat}'s for more detail. */
```

2021-10-06 02:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV30.java
> +        window.getDecorView().getWindowInsetsController().hide(WindowInsets.Type.statusBars());
Could you add a comment to the interface listing what this does.

I'd expect the soft buttons (home/apps/back) to be hidden as well. Does this happen?

2021-10-06 02:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV30.java
> +        window.setDecorFitsSystemWindows(false);
Could you add a reference for where this code came from?

2021-10-06 02:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/compat/CompatV30.java
> +        return (window.getDecorView().getWindowInsetsController().getSystemBarsAppearance()) == 0;
There's no need for the brackets here.

Could you add a reference for why this is the case? 

0 maps to the deprecated https://developer.android.com/reference/android/view/WindowInsetsController#BEHAVIOR_SHOW_BARS_BY_TOUCH

And I haven't checked whether `WindowInsets.Type.statusBars() | WindowInsets.Type.navigationBars()` would map to 0 in all cases

2021-10-06 02:35 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
> +    void setFullscreen(Window window);
These would be great with comments to ensure that we've handled all the functionality

2021-11-01 23:39 UTC, david-allison-1 commented
@noahwe145 is this still active? (no worries if it's not)

2022-01-02 19:33 UTC, mikehardy commented
This appears to need a new dev, a lot of work has been invested in it already and it appears close to working to me if someone wants to pick it up, resolve the current conflicts and get it polished up for merge

2022-06-25 15:43 UTC, mikehardy commented
Has current work in #11531

2022-06-25 15:43 UTC, closed without merging