System Dark Mode
ankidroid/Anki-Android pull request #9408
Opened 2021-08-14 06:03 UTC by VishnuSanal

## Pull Request template

## Purpose / Description
To make the AnkiDroid Android App follow the system dark mode

## Fixes
Fixes #5685

## Approach
The `Switch` for toggling in-app dark theme is changed to a switch to toggle whether the app should follow the system dark mode or follow a theme that the user picks.

## How Has This Been Tested?

Tested on a real android device running Android 10

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

## Layout Changes

![SS](https://user-images.githubusercontent.com/50027064/129435811-00c3b6bb-9896-47f4-96e2-5c6e982953f5.jpg)

2021-08-14 07:09 UTC, prateek-singh-3212 requested changes

2021-08-14 07:09 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/themes/Themes.java
> +        throw new NullPointerException("Unable to getSystemService() - UIModeManager");
I think we can remove this null pointer exception because I don't see that any of the methods used here throws null pointer exception. If we are using this then we have to handle it whenever we are calling `isNightMode`

2021-08-14 08:38 UTC, VishnuSanal commented on AnkiDroid/src/main/java/com/ichi2/themes/Themes.java
> +        throw new NullPointerException("Unable to getSystemService() - UIModeManager");
Hello @prateek-singh-3212, thank you for your review!

> I think we can remove this null pointer exception because I don't see that any of the methods used here throws null pointer exception.

`getSystemService()` might return null. If it does, it'll throw an NPE. I added the throw statement to get log more details.

> If we are using this then we have to handle it whenever we are calling `isNightMode`

Should we? That's when the function throws an exception. Right?

2021-08-14 09:12 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/themes/Themes.java
> +        throw new NullPointerException("Unable to getSystemService() - UIModeManager");
> That's when the function throws an exception. Right?

Yaa, but I want you to approach in this way `if(!null)` then go ahead and complete the task. else return `false` (means this forces the Light Mode) and in else part add `Timber.w` message that unable to call system Service (like that). 

I think handling the exception is very lengthy task. Because we are calling this method 3 times in code

2021-08-14 10:23 UTC, Akshay0701 requested changes
Hey @VishnuSanal, Thank you for the contribution!

I only mentioned nits related to code style, and I recommend you to go through [CodeStyle](https://github.com/ankidroid/Anki-Android/wiki/Code-style).

I would like to test this application once I get back to pc.

2021-08-14 10:23 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +
remove the extra space

2021-08-14 10:23 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +
[not sure] but I think you had put too many spaces in this line which code base litter inconsistent with other code
what do you say?

2021-08-14 10:23 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +
remove spaces

2021-08-14 10:23 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +                closeDrawer();
```suggestion
            if (isChecked) {
                closeDrawer();
            }
```

2021-08-14 10:23 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +                    mNavigationView.getMenu().findItem(R.id.nav_night_mode_light).setChecked(true);
```suggestion
                if (isUserNightMode) {
                    mNavigationView.getMenu().findItem(R.id.nav_night_mode_dark).setChecked(true);
                } else {
                    mNavigationView.getMenu().findItem(R.id.nav_night_mode_light).setChecked(true);
                }
```

2021-08-14 10:23 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +                mFollowSystemThemeSwitch.toggle(); //TODO: This toggling does not work
todo..

2021-08-14 10:23 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +            closeDrawer();
```suggestion
        if (item.getItemId() != R.id.nav_night_mode) {
            closeDrawer();
        }
```

2021-08-14 10:23 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/themes/Themes.java
> +            }
```suggestion
            if (isNightMode(context)) {
                return Integer.parseInt(prefs.getString(NIGHT_THEME, Integer.toString(THEME_NIGHT_BLACK)));
            }
            return Integer.parseInt(prefs.getString(DAY_THEME, Integer.toString(THEME_DAY_LIGHT)));
```
implementor choice*

2021-08-14 10:23 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/themes/Themes.java
> +            return (uiModeManager.getNightMode() == UiModeManager.MODE_NIGHT_YES);
```suggestion
        if (uiModeManager != null) {
            return (uiModeManager.getNightMode() == UiModeManager.MODE_NIGHT_YES);
        }
```

2021-08-14 10:23 UTC, Akshay0701 commented on AnkiDroid/src/main/java/com/ichi2/themes/Themes.java
> +        throw new NullPointerException("Unable to getSystemService() - UIModeManager");
Agreed with Prateek,

>  else part add Timber.w message that unable to call system Service (like that).

maybe use `Timber.e`

2021-08-14 10:23 UTC, Akshay0701 commented on AnkiDroid/src/main/res/layout/night_mode_switch.xml
> +</LinearLayout>
could you please revert these changes?

2021-08-14 12:04 UTC, VishnuSanal commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +
Sure. I assume you meant to remove whitespaces, please correct me if I'm wrong.

2021-08-14 12:07 UTC, VishnuSanal commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +                mFollowSystemThemeSwitch.toggle(); //TODO: This toggling does not work
I put that `TODO` to let know that it does not toggle the switch... I should make it just a comment. Right?

2021-08-14 12:16 UTC, prateek-singh-3212 commented on AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
> +
@Akshay0701 This is temporary because toggle button is not working. This will not go in commit

2021-08-14 12:33 UTC, infinyte7 commented
@VishnuSanal 
Can you move the `Follow System Theme` to `Settings -> Appearance`?
May be checkbox will be used.
Only one menu for night theme in sidebar will be better.

2021-08-14 12:40 UTC, VishnuSanal commented
> Can you move the `Follow System Theme` to `Settings -> Appearance`?
> May be checkbox will be used.
> Only one menu for night theme in sidebar will be better.

Can those be separated? A single `CheckBox` or `Switch` will create confusion, IMO.

For example, the user can override the system theme from the sidebar. But, to revert it, the user would've to go to the appearance settings.

What do you think?

2021-08-14 13:01 UTC, infinyte7 commented
Then one menu `Theme` in sideabar, when user click a popup with three radio button
```
Follow System Theme
Night Theme
Light Theme
```

But when the options changed in popup then preference value should also be changed for theme in `Settings`.

2021-08-14 16:37 UTC, david-allison-1 requested changes
Thanks for the PR!

I don't feel the screenshot mirrors what was discussed on [the issue](https://github.com/ankidroid/Anki-Android/issues/5685#issuecomment-832064383):

I'd like to avoid adding more items to the nav bar.

From what I understand to be agreed.

* Allow a user to change between "follow system" and "single theme" in the Appearance preferences
* Allow a user to select the light and dark theme in the preferences
* Default new users to "follow system"
  * With no toggle in the nav bar
* If "Single Theme" is selected, show a toggle in the nav bar
* (optional) add a badge to the selected night/day mode in the preferences.


@mikehardy can you confirm this was your intention.

----

I'd like to consider 3 options: "single theme" "user selected" and "system selected". 

"Single theme" produces no toggle, and a single selection from our 4 themes. 
"user selected" is our current default, and "system selected" also shows no toggle and two selections for day/night

2021-10-15 02:58 UTC, mikehardy commented
🤫 stale bot

2021-11-07 09:41 UTC, david-allison-1 commented
@VishnuSanal Is this still active? 

@mikehardy How do we want to handle a user who doesn't have "follow system" as an option (older phone/not available in OS)? It feels we lose out on that functionality if we don't have "user selected"

2021-11-07 13:57 UTC, VishnuSanal commented
> @VishnuSanal Is this still active?

Yes & sorry for the delay - I'm having my exams, so I have to squeeze in lil lil time to work on this PR.

2021-11-07 19:17 UTC, mikehardy commented
I think the last sentence in my comment was unclear, I just edited it to read:

> So then there's just two choices, with "single theme" offering a selection of our current four themes, and "system selected" (or "follow system") produces two choices to make: select one of the two light themes, and one of the two dark themes

My intention is to have "single theme" produce (in preferences somewhere) a choice for the user from among our set of (currently 4) of themes, and then that one is used all the time. But the user may change it if they like, any time.

Choosing "follow system" (or "system selected") will allow the user to choose the preferred light and dark options from the set of 2 in each of those categories, then we'll auto-switch them according to system theme

2021-11-07 19:24 UTC, david-allison-1 commented
This moves "night mode" out of the sidebar and into the settings for those users. I'd still prefer 3 options as I predict negative feedback from the removal of the sidebar item without an alternative, but I understand the argument for consistency and I'm happy to go with it. 

Nothing stops us caving in to user feedback and having a 'new coke' moment if we're wrong 😉

2021-11-07 19:43 UTC, mikehardy commented
just gotta stop before we issue cherry coke in regular and two different sugar-free versions, the skew is crazy

2021-11-14 15:18 UTC, closed without merging

2021-11-14 15:31 UTC, VishnuSanal commented
I can't update this since I accidentally deleted my original fork. Will make a PR after resolving conflicts, soon. Sorry for the mess :(

2021-11-14 15:36 UTC, david-allison-1 commented
You can pull https://github.com/ankidroid/Anki-Android/pull/9408/commits/e04ae8899348bad9934941f725dfc23687f66a40 from GitHub, the commit still exists, and it'll also exist in your `git log` if you didn't delete your `.git` folder.

2021-11-14 15:37 UTC, david-allison-1 commented
Alternately, define `upstream` as a remote, and 

`git fetch upstream pull/9408/head:9408-recovery`

2021-11-14 18:06 UTC, VishnuSanal commented
Thank you for your suggestions. I did clone code from this PR & made changes - but wasn't able to update 'em with a push, even after applying your suggestions. Superseded this with #9894