Migrate CardTemplate to Kotlin
ankidroid/Anki-Android pull request #9495
Opened 2021-09-04 15:08 UTC by ShridharGoel

Migrate CardTemplate to Kotlin.

2021-09-15 17:10 UTC, david-allison-1 commented
Blocked on https://github.com/ankidroid/Anki-Android/pull/9480

2021-10-02 13:04 UTC, david-allison-1 requested changes

2021-10-02 13:04 UTC, david-allison-1 commented on AnkiDroid/kotlinMigration.gradle
> +def className = "com/ichi2/anki/cardviewer/CardTemplate.kt"
This doesn't compile. 

It should be `/com/ichi2/anki/cardviewer/CardTemplate.kt`

See: https://github.com/david-allison-1/Anki-Android/commit/632a20741914189a319d2e55bb5fef30a9fd2216#diff-4abf8497cb1570dab86199e9f63e1c416d78e9dc08341af3b96ae0f485bf530dR1

We should also add an example on the line above to ensure this doesn't happen again

2021-10-02 15:05 UTC, ShridharGoel commented on AnkiDroid/kotlinMigration.gradle
> +def className = "com/ichi2/anki/cardviewer/CardTemplate.kt"
Updated.

2021-10-03 22:24 UTC, david-allison-1 approved these changes
LGTM

2021-10-04 17:00 UTC, mikehardy approved these changes
:steam_locomotive:

2021-10-04 17:00 UTC, merged