Show Hint Key Shortcut for ankidroid
ankidroid/Anki-Android pull request #9565
Opened 2021-09-28 09:01 UTC by cdhiraj40

## Pull Request template

## Purpose / Description
A request to add a key shortcut for Show hint during review because it will help to do reviews with Controller and many of my cards have Hinted. Please add Key H for show hint (by @sajith855)

## Fixes
#7354 

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

still under testing

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or add-ons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-09-28 14:25 UTC, mikehardy requested changes
Nice one - this looks pretty close to merge and has been requested a couple times now, some of our users will be really happy you've implemented this.

My comments are really minor with regard to the actual code

I have some general comments in addition to the specific code review:

- don't post a PR until you have actually tested it. You list in the testing section "Still under testing" - this is problematic for review because until you have definitely tested it locally (and can show a screen shot or quick screen video of the feature in use) you will likely need to make changes to the code, which means you have asked for and used reviewer time for no purpose, which is inefficient
- if you write `Fixes #number` instead of just `#number` in the description GitHub will auto-link this PR to the issue it addresses. Edit your PR description to match this style and watch it in action, it's cool and we use this to accelerate our project management here

2021-09-28 14:25 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.java
> +    COMMAND_SHOW_HINT(R.string.toggle_hint,38);
our code style standard should enforce this? We put space between parameters https://github.com/ankidroid/Anki-Android/wiki/Code-style

```suggestion
    COMMAND_SHOW_HINT(R.string.toggle_hint, 38);
```

2021-09-28 14:25 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="toggle_hint">TOGGLE HINT</string>
Can you please find where ever "toggle_whiteboard" is defined in the xml strings files and put this next to that one so they are grouped?

Also, the string should not be all uppercase, to match style it would be "Toggle Hint" not "TOGGLE HINT"

2021-09-28 14:29 UTC, mikehardy commented
Oh, also if possible you should rebase / edit the commits on your work branch so that when we merge we have a clean commit history. In this specific case the series of command line things I would do is `git rebase -i HEAD~2` (to tell git I want to interactively rebase the last two commits, since you have two here), then in the editor that pops up I would take the "remove unnecessary changes" commit and I would alter it's status to "squash", then I'd save the editor and let rebase squash that change into your main change. The result will be a single commit containing only the necessary changes.

The same can be done with your work here to address my code comments - you can make a new commit with the changes I requested, then do a git interactive rebase that squashes them into the first commit.

Any time you rebase locally you will get an error when trying to push back to your fork's branch. You will have to force push to the branch, but then when I examine things here on github everything will be super clean

2021-09-28 18:01 UTC, cdhiraj40 commented
> Nice one - this looks pretty close to merge and has been requested a couple times now, some of our users will be really happy you've implemented this.
> 
> My comments are really minor with regard to the actual code
> 
> I have some general comments in addition to the specific code review:
> 
> * don't post a PR until you have actually tested it. You list in the testing section "Still under testing" - this is problematic for review because until you have definitely tested it locally (and can show a screen shot or quick screen video of the feature in use) you will likely need to make changes to the code, which means you have asked for and used reviewer time for no purpose, which is inefficient
> * if you write `Fixes #number` instead of just `#number` in the description GitHub will auto-link this PR to the issue it addresses. Edit your PR description to match this style and watch it in action, it's cool and we use this to accelerate our project management here

yes, I totally agree with your thoughts about posting PR before actually testing it but I was not sure about the code that's why I made PR to ask @david-allison-1 about where should I add the functionality,(the code isn't working yet) but I will make sure form next time to do it :}

2021-09-28 18:02 UTC, cdhiraj40 commented
> git rebase -i HEAD~2

sure, Can I do it after all the code is done and PR is ready to merge? It will be better to do it just once rather than doing it twice. Thanks for the help :)

2021-09-28 18:07 UTC, mikehardy commented
> > git rebase -i HEAD~2
> 
> sure, Can I do it after all the code is done and PR is ready to merge? It will be better to do it just once rather than doing it twice. Thanks for the help :)

I would discourage this pattern. I would maintain clean commits as a habit, and do it any time you make changes. It's difficult at the end to fix up a mess of 30 commits. Right now you only have two and just need to squash one, it's trivial.

And in general if you've never done it before then the right path is not to put it off, but to do it a bunch, immediately, in my opinion - that's learning :-)

2021-09-28 18:17 UTC, cdhiraj40 commented
> > > git rebase -I HEAD~2
> > 
> > sure, Can I do it after all the code is done and PR is ready to merge? It will be better to do it just once rather than doing it twice. Thanks for the help :)
> 
> I would discourage this pattern. I would maintain clean commits as a habit and do it any time you make changes. It's difficult at the end to fix up a mess of 30 commits. Right now you only have two and just need to squash one, it's trivial.
> 
> And in general if you've never done it before then the right path is not to put it off, but to do it a bunch, immediately, in my opinion - that's learning :-)

oh I'm sorry I didn't know, now that I think it's better to do it earlier stage as the 2nd commit is removing unnecessary changes. I will sure do it tomorrow(23.45 here) Thanks again :)

2021-09-28 18:21 UTC, david-allison-1 requested changes
This needs to implement the "show hint" functionality. Currently the action does nothing

This can be done here:

https://github.com/ankidroid/Anki-Android/blob/27dbaeed881d3a1ef7b775311dabdf0780d3fc7f/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L2694

2021-10-03 14:07 UTC, cdhiraj40 commented
Hey, @mikehardy @david-allison-1  I tried a lot but I'm not able to add functionality, can you give some hints which might help me?

2021-10-03 14:19 UTC, david-allison-1 commented
https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection - add a hint via AnkiDroid, find it in the HTML in the console, and write some code to expand it & test it works

Then, bring the behavior into the Java codebase by injecting the javascript.

2021-10-03 15:27 UTC, cdhiraj40 commented
> https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection - add a hint field via AnkiDroid, find it in the HTML in the console, and write some code to expand it & test it works
> 
> Then, bring the behavior into the Java codebase by injecting the javascript.

I tried adding accesskey in the HTML field for hint but it doesn't work (I don't have much experience in HTML/ js)

2021-10-03 15:53 UTC, david-allison-1 commented
You want to use JavaScript to trigger the hint. I presume it should be equivalent to the click event.

Then, once you have the code working in the dev tools `Console`, move it to the Java.

You don't want to be using `accesskey`.

2021-10-03 15:54 UTC, cdhiraj40 commented
> You want to use JavaScript to trigger the hint. I presume it should be equivalent to the click event.
> 
> Then, once you have the code working in the JS dev tools `Console`, move it to the Java.
> 
> You don't want to be using `accesskey`.

oh but when I inspect it only shows me HTML file

2021-10-03 15:55 UTC, david-allison-1 commented
> > You want to use JavaScript to trigger the hint. I presume it should be equivalent to the click event.
> > Then, once you have the code working in the JS dev tools `Console`, move it to the Java.
> > You don't want to be using `accesskey`.
> 
> oh but when I inspect it only shows me HTML file

Click "console" and you can enter JavaScript

2021-10-03 16:02 UTC, cdhiraj40 commented
> > > You want to use JavaScript to trigger the hint. I presume it should be equivalent to the click event.
> > > Then, once you have the code working in the JS dev tools `Console`, move it to the Java.
> > > You don't want to be using `accesskey`.
> > 
> > 
> > oh but when I inspect it only shows me HTML file
> 
> Click "console" and you can enter JavaScript

okay got it. and any reasons why it doesn't show  me inspection 
![image](https://user-images.githubusercontent.com/75211982/135761814-e6fed5e1-dab1-4515-948d-ec2ce6a3e225.png)

2021-10-03 18:22 UTC, mikehardy commented
No idea why it doesn't show for you. In my experience closely following the instructions shows it for me https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

2021-10-03 19:53 UTC, david-allison-1 commented
The console is a bit finnicky, but I've definitely had it working for emulators, typically just "give it another go/refresh", which isn't a great Developer Experience

2021-10-04 02:02 UTC, cdhiraj40 commented
> The console is a bit finnicky, but I've definitely had it working for emulators.
> 
> It is slightly better with a physical phone, typically just "give it another go/refresh", which isn't a great Developer Experience

I have tried with the physical device too but it didn't help much, I will still try and complete this work as soon as possible. Thanks for the help again :)

2021-12-17 21:37 UTC, closed without merging