lint[tests]: Copyright and VariableNamingDetector
ankidroid/Anki-Android pull request #9579
Opened 2021-10-02 16:11 UTC by Arnold2381

## Fixes
Related: #9538 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-10-02 17:03 UTC, david-allison-1 requested changes
Thanks!

Variable name needs to be lowercase. I've proposed one change, but this applies to all

2021-10-02 17:03 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.java
> +            GoogleAnalytics Analytics = UsageAnalytics.initialize(mMockContext);
```suggestion
            GoogleAnalytics analytics = UsageAnalytics.initialize(mMockContext);
```

2021-10-03 14:20 UTC, david-allison-1 approved these changes
LGTM, thanks!

2021-10-03 18:23 UTC, mikehardy approved these changes
cool thanks!

2021-10-03 18:23 UTC, merged