anki_eco: card previewer shows fields labels if all fields are null.
ankidroid/Anki-Android pull request #9739
Opened 2021-10-30 08:37 UTC by Arnold2381

## Purpose / Description
In anki desktop when we preview the card Template with all the note fields as null, it shows up card labels as field texts.

## Fixes
Fixes #9696 

## Approach

<ol>
<li> A function was created that returns all the field labels which is then stored in a list. </li>
<li> while  populating the field lines in the note editor </li>
     <ol> <li>if the model type is basic (type in the answer) the behaviour remains same (need a seperate issue maybe)</li>
              <li>else the labels using list(1) of all the fields of the selected model are stored in a list  [ex format used in anki desktop (Front), (Back)]</li>
     </ol>
<li>When the preview button is clicked</li>
<ol><li> If the model type is cloze then we change the first element of the list in (2 ii) as the new string (in the below commit) which is used in the anki desktop </li>
<li> if all the fields are null we are setting the fields texts with the labels stored in (2 ii) </li>
</ol>
<li> corner case </li>
      <ol> <li>Whenever the note editor is resumed (this is managed using onResume function where we check if all the fields entered are same as the list in (2 ii) we clear all the edit text or else the functionality works the same.)</li>
               <li> On note type change the setNoteType function is called (where we need to clear the edit texts (based on check if the texts are filled with labels only then) and the list created in (2 ii).
     </ol>
</ol>
   

## How Has This Been Tested?
Tested on my phone only. I couldnt write tests for this, because i couldnt find a way for previewing a card without adding it , and we cant add a note with all fields as empty.

https://user-images.githubusercontent.com/46752548/139526196-3c70b47d-f30c-41b6-b602-f13c675a22b7.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-10-30 09:26 UTC, david-allison-1 requested changes
I'm in the process of moving this code to the Anki Desktop backend. 

Could you add unit tests here, as we'll be changing the behavior soon, and there's a chance that we're introducing regressions.

There's also a likelihood that this will entirely be handled by the business logic, so won't need to be in the UI logic. Could you add `@RustCleanup("check if this code is still necessary")` to remind future maintainers about this

2021-10-30 16:01 UTC, david-allison-1 commented
Does this work for the card template preview: select "cards", then preview from there.

Anki Desktop doesn't have a "note preview". I agree that the card template preview should match, and it likely doesn't currently. I feel this makes sense from a note preview perspective

2021-10-30 16:08 UTC, Arnold2381 commented
It doesn't. 
Sorry I missed that. I got confused with the note preview and the card preview. 
I will add that too.

2021-10-30 16:14 UTC, Arnold2381 commented
Should I change it for the cloze?

2021-10-30 16:21 UTC, david-allison-1 commented
> Should I change it for the cloze?

Definitely, we want to match Anki Desktop. It's likely better to code this in `CardTemplatePreviewer` rather than `NoteEditor`

2021-10-31 20:54 UTC, Arnold2381 commented
needs some testing, not ready for review.

2021-11-03 18:03 UTC, Arnold2381 commented
@mikehardy please take a look once.

2021-11-09 13:42 UTC, mikehardy requested changes
Getting closer I think, this comment from David is still in effect:

> Could you add unit tests here, as we'll be changing the behavior soon, and there's a chance that we're introducing regressions.

I left some comments that were just formatting and dead code, it looks reasonable, just tests now I think to make sure that as cards run through this logic the answers are what we expect for the various cases

2021-11-09 13:42 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
> +        if(mAllFieldsNull && mCardType != null && mCardType.equals(getString(R.string.basic_typing_model_name))) {
```suggestion
        if (mAllFieldsNull && (mCardType != nul)l && mCardType.equals(getString(R.string.basic_typing_model_name))) {
```

2021-11-09 13:42 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
> +            fieldValues.set(1, getString(R.string.basic_answer_sample_text));
```suggestion
        if ((mCardType != null) && mCardType.equals(getString(R.string.cloze_model_name))) {
            fieldValues.set(0, getString(R.string.cloze_sample_text, "c1"));
        }
        if  ((mCardType != null) && mCardType.equals(getString(R.string.basic_typing_model_name))) {
            fieldValues.set(1, getString(R.string.basic_answer_sample_text));
```

2021-11-09 13:42 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
> +            getLabels(fieldValues);
```suggestion
        if (mAllFieldsNull) {
            getLabels(fieldValues);
        }
```

2021-11-09 13:42 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
> +                n.setField(i, fieldValues.get(i));
```suggestion
            if (mAllFieldsNull) {
                if ((mCardType != null) && (mCardType.equals(getString(R.string.cloze_model_name)) && (i == 0)) ||
                        (mCardType.equals(getString(R.string.basic_typing_model_name)) && (i ==1))) {
                    n.setField(i, fieldValues.get(i));
                } else {
                    n.setField(i, "(" + fieldValues.get(i) + ")");
                }
            } else {
                n.setField(i, fieldValues.get(i));
            }
```

reformatting comments per our coding standards for java - 
- https://github.com/ankidroid/Anki-Android/wiki/Code-style#1tbs-one-true-brace-style-must-be-used-that-means
- https://github.com/ankidroid/Anki-Android/wiki/Code-style#parenthesis-should-be-used-liberally-in-expressions-involving-mixed-operators-in-order-to-make-the-precedence-clear

2021-11-09 13:42 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="basic_answer_sample_text_user">exomple</string>
this one has a typo, and appears unused?
```suggestion
```

2021-11-09 13:47 UTC, Arnold2381 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="basic_answer_sample_text_user">exomple</string>
![image](https://user-images.githubusercontent.com/46752548/140935181-4f0f29c9-9ba2-4aec-8ef4-e7f562023aa9.png)
It is used as per anki desktop.

2021-11-09 13:49 UTC, Arnold2381 commented
> Getting closer I think, this comment from David is still in effect:
> 
> > Could you add unit tests here, as we'll be changing the behavior soon, and there's a chance that we're introducing regressions.

Yea, but that was before, now I didnt include any tests because `CardTemplatePreviewer` is already well tested.

2021-11-09 13:50 UTC, Arnold2381 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
> +                n.setField(i, fieldValues.get(i));
Sorry!

2021-11-09 14:08 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="basic_answer_sample_text_user">exomple</string>
Ah, okay. Then please fix the typo 
```suggestion
    <string name="basic_answer_sample_text_user">example</string>
```

2021-11-09 14:10 UTC, mikehardy commented
> Yea, but that was before, now I didnt include any tests because CardTemplatePreviewer is already well tested.

Indeed it is! We've worked hard on that: https://github.com/ankidroid/Anki-Android/commits/672c44eb664284339b697bff27ec8b37925c3c31/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java

You have added branching here with new conditionals. It would be nice to see those exercised and your expected new example/sample values asserted against

2021-11-09 14:14 UTC, Arnold2381 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="basic_answer_sample_text_user">exomple</string>
Thats not a typo :-) thats deliberately done. 

So that in the sample card its shown that the answer input is wrong

2021-11-09 14:30 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="basic_answer_sample_text_user">exomple</string>
Ahh that is subtle! And makes perfect sense. Thanks for explaining

2021-11-09 14:33 UTC, mikehardy commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="basic_answer_sample_text_user">exomple</string>
Okay, follow on thought then, I will not be the only person confused:

```suggestion
    <string name="basic_answer_sample_text_user comment="goes with basic_answer_sample_text but has tiny misspelling so user sees a highlighted difference">exomple</string>
```

what do you think?

2021-11-09 14:41 UTC, Arnold2381 commented on AnkiDroid/src/main/res/values/02-strings.xml
> +    <string name="basic_answer_sample_text_user">exomple</string>
Did that.
Thanks! Looks good

2021-11-09 14:44 UTC, Arnold2381 commented
I will include the tests by this weekend, little busy with college work!

2021-11-09 15:00 UTC, mikehardy commented
open source == never time pressure, thank you for contributing *anything*, and good luck in your courses

2021-11-14 17:45 UTC, Arnold2381 commented
@david-allison-1 i have added tests in this.

2021-11-25 14:23 UTC, Arnold2381 commented
@mikehardy I have added the test, this needs review in case you have missed.

2021-11-25 14:24 UTC, mikehardy commented
Apologies - been working nonstop last few weeks on some missed-at-this-point deadlines and just can't seem to get caught up. Working on it :sweat_smile:

2022-01-09 19:10 UTC, mikehardy requested changes
Just spacing nitpicks, I'm an approve otherwise, thanks @Arnold2381 !

2022-01-09 19:10 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
> +        if(mAllFieldsNull && (mCardType != null) && mCardType.equals(getString(R.string.basic_typing_model_name))) {
just a spacing nitpick
```suggestion
        if (mAllFieldsNull && (mCardType != null) && mCardType.equals(getString(R.string.basic_typing_model_name))) {
```

2022-01-09 19:10 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
> +        if((mCardType != null) && mCardType.equals(getString(R.string.basic_typing_model_name))) {
```suggestion
        if ((mCardType != null) && mCardType.equals(getString(R.string.cloze_model_name))) {
            fieldValues.set(0, getString(R.string.cloze_sample_text, "c1"));
        }
        if ((mCardType != null) && mCardType.equals(getString(R.string.basic_typing_model_name))) {
```

2022-01-09 19:10 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
> +        if(mAllFieldsNull) {
```suggestion
        if (mAllFieldsNull) {
```

2022-01-09 19:10 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
> +                if((mCardType != null) && (mCardType.equals(getString(R.string.cloze_model_name)) && (i == 0)) ||
```suggestion
            if (mAllFieldsNull) {
                if ((mCardType != null) && (mCardType.equals(getString(R.string.cloze_model_name)) && (i == 0)) ||
```

2022-01-09 19:12 UTC, david-allison-1 approved these changes
LGTM besides Mike's nitpicks

2022-01-16 19:23 UTC, mikehardy approved these changes
This looks great! Love closing the "ecosystem compatibility" issues, thanks so much for fixing this up

2022-01-16 19:34 UTC, merged

2022-03-06 21:53 UTC, mikehardy commented
Hi there! **JANUARY** OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [January 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-01-01..2022-01-31) (I'll follow this with the same process for February in a week)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of January)

Thanks!