docs: Kotlin Conversion
ankidroid/Anki-Android pull request #9747
Opened 2021-10-31 18:18 UTC by david-allison-1

Better to write this than to explain it. Reduces the 🚌 factor.

https://github.com/ankidroid/Anki-Android/pull/9480

Preview this PR: https://github.com/david-allison-1/Anki-Android/blob/c46ac3dd99696527b9d80cdee45e66eb3449f98d/docs/kotlin-migration.md

2021-10-31 18:23 UTC, mikehardy approved these changes
Nice!

2021-10-31 18:23 UTC, merged

2021-10-31 18:47 UTC, codingtosh requested changes
LGTM @david-allison-1 ,
just a few nits.

2021-10-31 18:47 UTC, codingtosh commented on docs/kotlin-migration.md
> +## References
Maybe add an example PR here, 
https://github.com/ankidroid/Anki-Android/pull/9738/commits

2021-10-31 18:47 UTC, codingtosh commented on docs/kotlin-migration.md
> +* Git rebase the first commit (`rename .java to .kt`)
I would elaborate upon this a little. Something similar to:

Open the Git tab from the bottom left(Alt + 9) > Right click on the bottom commit (rename .java to .kt) > Click on Interactively Rebase from here > Right click on the top commit > Stop To Edit (Alt + E) -> Start Rebasing

2021-10-31 18:47 UTC, codingtosh commented on docs/kotlin-migration.md
> +* `File - Sync Project with Gradle Files`, then `Build - Rebuild` to ensure the commit builds
Nit, ">" instead of "-" here and everywhere else
Example: Build > Rebuild

2021-11-01 11:08 UTC, Arthur-Milchior commented
I love it. Thanks forgot finding a way to deal correctly with git history