Refactor JS API and added check for on API with test
ankidroid/Anki-Android pull request #9749
Opened 2021-10-31 20:37 UTC by infinyte7

## Pull Request template

## Purpose / Description
I have created separated class for JS API constants and added check on API which modify contents in AnkiDroid.

Now it will be easier to add new api.

## Fixes
Fixes _Link to the issues._

## Approach
1. Created a separate class containing for api error code and api name
2. Extracted check on api to a function 
3. Added test on `bury` and `suspend` card and notes

## How Has This Been Tested?
Tested using chrome remote debugging and android devices

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
https://developer.android.com/reference/android/webkit/JavascriptInterface

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-11-02 14:36 UTC, mikehardy requested changes
I think this is a reasonable refactor and incrementally gets us closer to verifying the API calls without all the code in AbstractFlashcardViewer - thanks

Just one minor point that the example email should be safer

2021-11-02 14:36 UTC, mikehardy commented on AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
> +        script += "var jsApi = {\"version\" : \"0.0.1\", \"developer\" : \"dev@mail.com\"};\n"
A minor point, but when you need a "fake" email address, always use the RFC standard ones:

https://www.techrepublic.com/blog/it-security/use-rfc-2606-example-domains-for-example-emails/
https://datatracker.ietf.org/doc/html/rfc2606#section-3

2021-11-02 16:11 UTC, infinyte7 commented on AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
> +        script += "var jsApi = {\"version\" : \"0.0.1\", \"developer\" : \"dev@mail.com\"};\n"
Thanks, I learned new things.

2021-11-02 20:56 UTC, mikehardy approved these changes
These LGTM thanks

2021-11-08 12:35 UTC, david-allison-1 reviewed
Forgot to hit "comment", sorry

2021-11-09 12:46 UTC, infinyte7 commented
I will update it later.

2021-11-09 18:17 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPIConstants.kt
> +    @kotlin.jvm.JvmField
I have updated suggested change to `object AnkiDroidJsAPIConstants` and `const val`

2021-11-09 18:18 UTC, infinyte7 commented on AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPIConstants.kt
> +    var mCardSuppliedDeveloperContact = ""
The variable belongs to `AnkiDroidJsAPI` so I moved it to that class.

2021-11-09 18:20 UTC, david-allison-1 approved these changes
Awesome!

2021-11-09 18:27 UTC, mikehardy approved these changes
Nice!

2021-11-10 19:55 UTC, merged

2021-12-12 01:57 UTC, mikehardy commented
Hi there! November OpenCollective Notice

Apologies for the delay, and if you're already submitted something to OpenCollective for PRs merged in November 2021, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for November 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of August)

Thanks!