Remove html debug as default in debug
ankidroid/Anki-Android pull request #9752
Opened 2021-11-01 10:18 UTC by infinyte7

## Pull Request template

## Purpose / Description
The HTML Debug make tests slow. It is better to remove this. 

## Fixes
Fixes #9751

## Approach
Removed the code which make html debug default to true.

## How Has This Been Tested?
Tested on android devices

## Learning (optional, can help others)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-11-01 11:01 UTC, david-allison-1 requested changes
I think it's useful functionality that we should keep (I use it when doing support), but shouldn't be run during testing

2021-11-01 12:59 UTC, infinyte7 commented
> I think it's useful functionality that we should keep (I use it when doing support), but shouldn't be run during testing

I have created a variable in gradle to handle testing and debugging. 
May be there will be better solution for it.

2021-11-01 15:44 UTC, david-allison-1 requested changes
CI is failing. I'm sure there'll be a way to do better here

2021-11-01 16:04 UTC, infinyte7 commented
I am searching for better implementation for this.

2021-11-02 16:11 UTC, infinyte7 commented
I have tried this approach but I don't think it is better approach. I am still finding way to make boolean true in debug and false in testing.

https://stackoverflow.com/questions/28550370/how-to-detect-whether-android-app-is-running-ui-test-with-espresso
```java
        try {
            Class.forName ("android.support.test.espresso.Espresso");
            istest = true;
        } catch (ClassNotFoundException e) {
            istest = false;
        }

```

2021-11-06 04:12 UTC, infinyte7 commented
Currently I have no time to continue this PR.

2021-11-06 04:12 UTC, closed without merging