NF: Improving spinner code
ankidroid/Anki-Android pull request #9758
Opened 2021-11-01 21:57 UTC by Arthur-Milchior

While trying to solve #9755 I found a lot of things that I thought were worth improving in the DeckSpinnerSelection code. So here there are. It's NF, and I hope easier to read

2021-11-01 22:27 UTC, david-allison-1 requested changes
Most of this is great! Nitpicky comments

Unit tests are failing

2021-11-01 22:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +    public DeckSpinnerSelection(@NonNull AnkiActivity context, @NonNull Collection collection, @NonNull Spinner spinner, boolean showAllDecks, boolean alwaysShowDefault) {
nit: I feel the boolean variables would be better behind a `Builder`, rather than in the constructor

2021-11-01 22:27 UTC, david-allison-1 commented on AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.java
> +        cb.mDeckSpinnerSelection.getSpinner().setSelection(pos + 1);    //Adjusting for All Decks option at position 0
Was better previously ([Law of Demeter](https://en.wikipedia.org/wiki/Law_of_Demeter))

2021-11-01 22:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
> +                if (event.isCtrlPressed() && (mDeckSpinnerSelection.hasSpinner())) {
Awesome!

2021-11-01 22:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +                mDeckId = deckId;
It feels that this would want to be extracted

2021-11-01 22:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +            }
Likewise: better to have this extracted to a method

2021-11-01 22:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +                // We do not allow cards to be moved to dynamic deck.
comments are great!

2021-11-01 22:27 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +    public DeckSpinnerSelection(@NonNull AnkiActivity context, @NonNull Collection collection, @NonNull Spinner spinner, boolean showAllDecks, boolean alwaysShowDefault) {
I do like the unification of the two constructors

2021-11-01 23:29 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +    public DeckSpinnerSelection(@NonNull AnkiActivity context, @NonNull Collection collection, @NonNull Spinner spinner, boolean showAllDecks, boolean alwaysShowDefault) {
Given the small number of cases where it is used, and the number of options which remain small, I don't think it's worth the added code here.

2021-11-01 23:30 UTC, Arthur-Milchior commented on AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.java
> +        cb.mDeckSpinnerSelection.getSpinner().setSelection(pos + 1);    //Adjusting for All Decks option at position 0
I am not sure how much the law of Demeter applies here. Simply by the fact that the test is already forced to know that it must add one to take "all deck" into account, it was already using too much of internal logic to my taste. Not stating that this one is right. I'll remove it from the PR so that the nice one can get merged

2021-11-02 02:23 UTC, Arthur-Milchior commented
I removed the part that seemed to be up to discussion so that the easy part can be merged. 

The main trouble is that `selectDropDownItem` is bugged. `mDeckId` is set to wrong value in the note editor. This is not actually a problem because this value is never read in the note editor. But will create an issue if one day someone try to read it.  And making the code correct, while not hard, would make a function with more if.

2021-11-02 02:24 UTC, Arthur-Milchior commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +                mDeckId = deckId;
I don't see how to properly extract it. I believe that `selectDropDownItem` is a wrong abstraction. Not only it is buggy (as explained below) but we already have the deck id, so recomputing it is just wasted computation time

2021-11-02 06:34 UTC, Arthur-Milchior commented
I was able to recreate the PR with more steps, which hopefully ensure that some of the remarks you gave before are no longer relevant. 

I tested it on my phone in note editor, stats and browser, and the three still works fine

2021-11-02 12:40 UTC, david-allison-1 approved these changes
Looks good, a few of these can be improved further once we move to Kotlin (it has an auto-parcelable package, which saves so much code).

2021-11-02 14:42 UTC, mikehardy approved these changes
These all look great to me, thanks

2021-11-02 14:43 UTC, merged

2021-12-12 01:57 UTC, mikehardy commented
Hi there! November OpenCollective Notice

Apologies for the delay, and if you're already submitted something to OpenCollective for PRs merged in November 2021, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for November 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of August)

Thanks!