Kotlin migration
ankidroid/Anki-Android pull request #9787
Opened 2021-11-06 04:09 UTC by Arnold2381

Kotlin migration

2021-11-06 12:25 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/themes/StyledProgressDialog.kt
> +            return MaterialDialog.Builder(context!!)
The `!!`s here appear to be incorrect

2021-11-06 12:48 UTC, Arnold2381 commented
It failed. David I will check it.
if it doesn't get resolved I will ping you.

2021-11-06 16:05 UTC, Arnold2381 commented
Its failing. couldnt get it work.

2021-11-06 17:56 UTC, david-allison-1 commented
This one is a pain. Use this:

```kotlin
/*
 *  Copyright (c) 2021 David Allison <davidallisongithub@gmail.com>
 *
 *  This program is free software; you can redistribute it and/or modify it under
 *  the terms of the GNU General Public License as published by the Free Software
 *  Foundation; either version 3 of the License, or (at your option) any later
 *  version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT ANY
 *  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 *  PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with
 *  this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.ichi2.utils

import android.content.DialogInterface
import com.afollestad.materialdialogs.MaterialDialog

// Extension methods for MaterialDialog.Builder workarounds in Kotlin
// Previously the methods accepted null into a @NonNull parameter, 
// and fixing this made the fluent

fun MaterialDialog.Builder.titleNullable(title: CharSequence?): MaterialDialog.Builder {
    title?.let { this.title(it) }
    return this
}

fun MaterialDialog.Builder.contentNullable(content: CharSequence?): MaterialDialog.Builder {
    content?.let { this.content(it) }
    return this
}

fun MaterialDialog.Builder.cancelListenerNullable(cancelListener: DialogInterface.OnCancelListener?): MaterialDialog.Builder {
    cancelListener?.let { this.cancelListener(it) }
    return this
}
```

2021-11-06 18:56 UTC, Arnold2381 commented
The tests failed in my local, though I have pushed the changes.

2021-11-06 18:59 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/MaterialBuilderUtil.kt
> +// and fixing this made the fluent
```suggestion
// and fixing this broke the fluent interface
```

2021-11-06 19:01 UTC, david-allison-1 requested changes
This is also required

2021-11-06 19:01 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/themes/StyledProgressDialog.kt
> +                .show()
```suggestion
            return MaterialDialog.Builder(context!!)
                .titleNullable(t)
                .contentNullable(message)
                .progress(true, 0)
                .cancelable(cancelable)
                .cancelListenerNullable(cancelListener)
                .show()
```

2021-11-06 19:01 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/themes/StyledProgressDialog.kt
> +            context: Context?,
```suggestion
            context: Context,
```

2021-11-06 19:05 UTC, Arnold2381 commented on AnkiDroid/src/main/java/com/ichi2/themes/StyledProgressDialog.kt
> +                .show()
Still failing

2021-11-06 19:13 UTC, Arnold2381 commented
I think this should work!

2021-11-06 21:08 UTC, david-allison-1 requested changes
Looks good! Two small issues

2021-11-06 21:08 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/themes/StyledProgressDialog.kt
> +    fun setProgress() {
Variables were removed here, instead you should use `Suppress("unused_parameter")

2021-11-06 21:08 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/themes/StyledProgressDialog.kt
> -    private static boolean animationEnabled(Context context) {
This method was removed, it should be left for a further refactor

2021-11-07 01:28 UTC, Arnold2381 commented
@david-allison-1 once this goes. I will make changes in the SimpleMessageDialog because it needs the util methods.

2021-11-07 11:21 UTC, Arnold2381 commented
@david-allison-1 i think u missed this.

2021-11-07 12:26 UTC, david-allison-1 approved these changes
I did miss it! 😱 

Thanks for the reminder! Looks great

2021-11-07 18:44 UTC, mikehardy approved these changes
:zap:

2021-11-07 18:44 UTC, merged