[Kotlin Migration] AndroidUiUtils
ankidroid/Anki-Android pull request #9796
Opened 2021-11-07 00:22 UTC by codingtosh

2021-11-07 00:33 UTC, david-allison-1 requested changes
Doesn't compile

2021-11-07 16:00 UTC, codingtosh commented
> Doesn't compile

Hmm, I double checked that everything compiled and built without problems before sending the PR in. 
Going by the logs, 

> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/MaterialEditTextDialog.kt: (52, 52): Type mismatch: inferred type is EditText? but View was expected

it seems newer commits were made in main after I had committed locally. 

I've update the local codebase and patched this up, should I amend this in the previous commit(changes a different file as well) or make a third commit?

2021-11-07 16:59 UTC, david-allison-1 commented
> > Doesn't compile
> 
> Hmm, I double checked that everything compiled and built without problems before sending the PR in. Going by the logs,
> 
> > /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/MaterialEditTextDialog.kt: (52, 52): Type mismatch: inferred type is EditText? but View was expected
> 
> it seems newer commits were made in main after I had committed locally.
> 
> I've update the local codebase and patched this up, should I amend this in the previous commit(changes a different file as well) or make a third commit?

rebase onto master and keep it as 2 commits

2021-11-08 00:42 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MaterialEditTextDialog.kt
>          fun displayKeyboard(editText: EditText?, materialDialog: MaterialDialog) {
I feel the issue is that `EditText?` should be `EditText`, does that work?

2021-11-08 01:08 UTC, codingtosh commented on AnkiDroid/src/main/java/com/ichi2/anki/MaterialEditTextDialog.kt
>          fun displayKeyboard(editText: EditText?, materialDialog: MaterialDialog) {
So just to confirm, I should make EditText non null only here or everywhere else in the file too?

2021-11-08 01:15 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MaterialEditTextDialog.kt
>          fun displayKeyboard(editText: EditText?, materialDialog: MaterialDialog) {
> So just to confirm, I should make EditText non null only here or everywhere else in the file too?

Just here,

2021-11-08 01:33 UTC, codingtosh commented on AnkiDroid/src/main/java/com/ichi2/anki/MaterialEditTextDialog.kt
>          fun displayKeyboard(editText: EditText?, materialDialog: MaterialDialog) {
Hmm, not sure why it says 4 commits here, despite being ahead only 2 commits master locally. 🤔

2021-11-08 01:34 UTC, david-allison-1 requested changes
Two conversions have been combined here: CollectionUtils and AndroidUiUtils. AndroidUiUtils looks good

2021-11-08 01:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/CollectionUtils.kt
> +object CollectionUtils {
Why was this converted at the same time?

2021-11-08 01:44 UTC, codingtosh commented
> Two conversions have been combined here: CollectionUtils and AndroidUiUtils. AndroidUiUtils looks good

Ahh, I see what the issue is. I pushed from Android Studio a new branch a little while ago. I think it just pushed the commits to origin master instead of a new branch. I've cleaned it up, PTAL.

2021-11-08 02:56 UTC, david-allison-1 approved these changes
LGTM

2021-11-08 11:59 UTC, david-allison-1 commented
Did you mean to close this? @codingtosh

2021-11-08 12:04 UTC, codingtosh commented
@david-allison-1 No, my bad, I was cleaning up the old ones, didn't realise this one hadn't been merged yet.

2021-11-08 12:18 UTC, mikehardy approved these changes

2021-11-08 12:19 UTC, merged