[Kotlin Migration] ExceptionUtil
ankidroid/Anki-Android pull request #9820
Opened 2021-11-08 11:16 UTC by codingtosh

[Kotlin Migration] ExceptionUtil

2021-11-08 12:32 UTC, david-allison-1 requested changes
```
com.ichi2.utils.ExceptionUtilTest > exceptionMessageNull FAILED
    java.lang.NullPointerException: Parameter specified as non-null is null: method com.ichi2.utils.ExceptionUtil.getExceptionMessage, parameter e
        at com.ichi2.utils.ExceptionUtil.getExceptionMessage(ExceptionUtil.kt)
        at com.ichi2.utils.ExceptionUtilTest.exceptionMessageNull(ExceptionUtilTest.java:47)
```

2021-11-08 12:41 UTC, mikehardy commented
No line numbers here either, it's a real thing:

>         at com.ichi2.utils.ExceptionUtil.getExceptionMessage(ExceptionUtil.kt)

2021-11-08 13:21 UTC, mikehardy approved these changes

2021-11-09 12:51 UTC, david-allison-1 approved these changes
⚡

2021-11-09 12:52 UTC, merged