Kotlin migration SyncErrorDialog
ankidroid/Anki-Android pull request #9833
Opened 2021-11-08 18:36 UTC by Arnold2381

Kotlin migration SyncErrorDialog

2021-11-08 19:16 UTC, david-allison-1 requested changes

2021-11-08 19:16 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
> +            .content(message!!)
!

2021-11-08 19:16 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
> +            else -> null!!
This fails, but I feel it's fine as it's a logic error.

Maybe follow-up to use an enum so this won't happen

2021-11-08 19:16 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
> +    override fun getNotificationMessage(): String {
I think this is nullable in the base class (we might want to Kotlin convert the base class, or at least add a nullability reference here

2021-11-08 19:22 UTC, Arnold2381 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
> +    override fun getNotificationMessage(): String {
is it needed here? because it always return non null value.

2021-11-08 19:56 UTC, david-allison-1 reviewed
Forgot to press "Submit"

2021-11-08 19:56 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
> +    override fun getNotificationMessage(): String {
I believe `this.message` https://github.com/ankidroid/Anki-Android/pull/9833/files/d5dabac6c0e21a43456b987ad670820da9300522..3992c8a9b23cbb13b64e0dbe6495f5e6922d8bdf#diff-6d27b6a54b50b4dc28b250dd9461251a564e99a5e1c0aafea2ef5cf45095a35bR218 is nullable

2021-11-09 13:03 UTC, david-allison-1 approved these changes
LGTM

2021-11-09 13:11 UTC, mikehardy approved these changes

2021-11-09 13:11 UTC, merged