Kotlin migration DeckSelectionDialog
ankidroid/Anki-Android pull request #9834
Opened 2021-11-08 18:58 UTC by Arnold2381

Kotlin migration DeckSelectionDialog

2021-11-08 19:35 UTC, mikehardy approved these changes
All seems fine - thanks

2021-11-08 20:00 UTC, david-allison-1 requested changes
Minor changes

2021-11-08 20:00 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +        createDeckDialog.setOnNewDeckCreated { id: Long? ->
@Arnold2381 Could you flag this method for a follow-up to make the parameter `@NonNull` and check that it currently doesn't return null

2021-11-08 20:00 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +    open class SelectableDeck : Comparable<SelectableDeck>, Parcelable {
Add a `@KotlinCleanup` to auto-parcel this

2021-11-09 14:12 UTC, Arnold2381 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +        createDeckDialog.setOnNewDeckCreated { id: Long? ->
`setOnNewDeckCreated ` doesnt return null.

2021-11-09 14:39 UTC, david-allison-1 approved these changes
Gogo

2021-11-09 14:39 UTC, merged