Kotlin migration DatabaseErrorDialog
ankidroid/Anki-Android pull request #9835
Opened 2021-11-08 19:10 UTC by Arnold2381

Kotlin migration DatabaseErrorDialog

2021-11-08 19:19 UTC, david-allison-1 requested changes
Few issues, nothing major, we likely want to aim to get the base class converted so the overloads aren't erroneously returning null

2021-11-08 19:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +                    .content(message!!)
!

2021-11-08 19:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +                    .content(message!!)
!

2021-11-08 19:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +                builder.content(message!!)
!

2021-11-08 19:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +                builder.content(message!!)
!

2021-11-08 19:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +                builder.content(message!!)
!

2021-11-08 19:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +                builder.content(message!!)
!

2021-11-08 19:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +                builder.content(message!!)
!

2021-11-08 19:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +                builder.content(message!!)
!

2021-11-08 19:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +                    .content(message!!)
!

2021-11-08 19:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +        return message!!
Nullable

2021-11-08 19:19 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +    override fun getNotificationTitle(): String {
Make nullable

2021-11-08 19:30 UTC, Arnold2381 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +    override fun getNotificationTitle(): String {
same it always return non null value

2021-11-09 02:45 UTC, Arnold2381 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +    override fun getNotificationTitle(): String {
```
override fun getNotificationTitle(): String? {
        return res().getString(R.string.answering_error_title)
    }

```

2021-11-09 13:36 UTC, Arnold2381 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +    override fun getNotificationTitle(): String {
@david-allison-1 ?

2021-11-09 14:37 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +    override fun getNotificationTitle(): String {
Sorry, that's fine

2021-11-09 14:37 UTC, david-allison-1 approved these changes
LGTM

2021-11-09 14:58 UTC, mikehardy commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +            Timber.w(e)
Interesting. Multi-catch not supported, vote here if you like https://youtrack.jetbrains.com/issue/KT-7128

2021-11-09 14:59 UTC, mikehardy approved these changes
Alright!

2021-11-09 14:59 UTC, merged

2021-11-09 15:28 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
> +            Timber.w(e)
I don't see it happening soon, Exceptions are a rare case where Java allows sum types. I'd love to see it, but it's a paradigm shift