Changes for Issue 5844 - Forgotten AnkiWeb e-mail
ankidroid/Anki-Android pull request #9909
Opened 2021-11-17 23:20 UTC by sethbuchinger

## Pull Request - Changes for Issue 5844 - Forgotten AnkiWeb e-mail

## Purpose / Description
Allow user the ability to click a link for instructions on how to find their AnkiWeb Account Email

## Fixes
Fixes [Issue 5844](https://github.com/ankidroid/Anki-Android/issues/5844)

## Approach
This change adds a button on the login screen for the user to click to open up a web browser with instructions on how to find their AnkiWeb email. 

<img width="557" alt="Screen Shot 2021-11-17 at 6 09 39 PM" src="https://user-images.githubusercontent.com/65492746/142297359-b224352c-14d2-4cf9-9024-d3b6c6f83afc.png">

## How Has This Been Tested?

This was tested on a Pixel3A_API_31_arm64-v8a emulator with  SDK version: Android 12.0 (S)

## Learning (optional, can help others)

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-11-17 23:34 UTC, david-allison-1 requested changes
Looks great (and really concise!), thanks!

Two nitpicks, and one request on moving the constant

2021-11-17 23:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +        Uri lostMailUrl = Uri.parse("https://github.com/ankidroid/Anki-Android/wiki/FAQ#forgotten-ankiweb-email-instructions");
Could you move this to `constants.xml`

2021-11-17 23:34 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +        //Add new button to link to instructions on how to find AnkiWeb email
'new' is time relative, this comment will hopefully be here for 10 years :)

```suggestion
        // Add button to link to instructions on how to find AnkiWeb email
```

2021-11-17 23:34 UTC, david-allison-1 commented on AnkiDroid/src/main/res/values/04-network.xml
> +    <string name="lost_mail_instructions">Forgot AnkiWeb Account Email?</string>
Optional, I'd prefer this to be more concise. Implementer's choice

```suggestion
    <string name="lost_mail_instructions">Forgot Email?</string>
```

2021-11-18 00:10 UTC, sethbuchinger commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +        Uri lostMailUrl = Uri.parse("https://github.com/ankidroid/Anki-Android/wiki/FAQ#forgotten-ankiweb-email-instructions");
Added to url to `constants.xml`

2021-11-18 00:11 UTC, sethbuchinger commented on AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
> +        //Add new button to link to instructions on how to find AnkiWeb email
Removed "new" in comment

2021-11-18 00:11 UTC, sethbuchinger commented on AnkiDroid/src/main/res/values/04-network.xml
> +    <string name="lost_mail_instructions">Forgot AnkiWeb Account Email?</string>
Implemented as suggested for conciseness

2021-11-18 15:43 UTC, david-allison-1 approved these changes
Awesome, thanks so much!

2021-11-18 15:45 UTC, david-allison-1 commented
Just to note for future: You can add `Fixes #5844` to the PR description and it will automatically link + close the PR when merged.

I've edited your post to do this.

2021-11-18 18:35 UTC, mikehardy approved these changes
Nice! This looks really good, thanks for posting it

2021-11-18 18:36 UTC, merged

2021-12-12 01:56 UTC, mikehardy commented
Hi there! November OpenCollective Notice

Apologies for the delay, and if you're already submitted something to OpenCollective for PRs merged in November 2021, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for November 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of August)

Thanks!