Removed the unused string and updated the used link
ankidroid/Anki-Android pull request #9948
Opened 2021-11-26 05:38 UTC by thevar2002

… the issue #9400

Signed-off-by: Rakesh Prasanna R <rakeshprasanna72@gmail.com>

## Pull Request template

## Purpose / Description
**Unused string** in the codebase and usage of **http** over **https** for link

## Fixes

- Removed the unused string from the codebase _`AnkiDroid/src/main/java/com/ichi2/anki/Info.java`_ and from _`AnkiDroid/src/main/res/values/constants.xml`_
- Updated the link in  _`AnkiDroid/src/main/res/values/constants.xml`_ to use **https** over **http**

## Approach
Updating the method used for fetching unused file from the codebase and updating the string in the XML file.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [.] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [.] You have a descriptive commit message with a short title (first line, max 50 chars).
- [.] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [.] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-11-26 11:51 UTC, mikehardy requested changes
This looks like it might be correct, but you've not really filled out the PR template at all, so it's missing a lot of context.
The issue you linked is incorrect (should be #9525 and you haven't mentioned how you tested it or anything ?

Can you take a look at the PR template and pay attention to it as you would pay attention to the code? It's how we developers here communicate with each other and explain the changes to future people (as they read PRs linked to previous code changes while trying to read the code...). 

Over the long-term that as  important than the code changes

2021-11-26 17:00 UTC, thevar2002 commented
@mikehardy I have updated the PR template. Thanks for the feedback.

2021-11-26 18:16 UTC, david-allison-1 approved these changes
Looks good to me, thanks

Just to note: If you use `Fixes #9525` in the PR description, it links the issue and the Pull Request (see "linked issues" on the sidebar)

I've done this for you on this PR, but it's useful knowledge for the future.

Thanks again!!

2021-11-26 19:02 UTC, mikehardy approved these changes
Nice!
Just a note that any time you remove stuff in the XML you can test with this test: https://github.com/ankidroid/Anki-Android/blob/8de70d72a438fb8c14b97130f3c79159bd35a412/.github/workflows/lint.yml#L73

And if you change java you can use `./gradlew jacocoTestReport` with an emulator running

Our CI will do that for you as well, so these tests will be run, but it's how you can check things before pushing them up and having CI potentially go red on you :-)

Cheers

2021-11-26 19:02 UTC, merged

2021-12-12 01:56 UTC, mikehardy commented
Hi there! **November OpenCollective Notice**

Apologies for the delay, and if you're already submitted something to OpenCollective for PRs merged in **November** 2021, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for November 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of August)

Thanks!