Bump robolectric from 4.7.1 to 4.7.3
ankidroid/Anki-Android pull request #9966
Opened 2021-12-03 15:39 UTC by dikshamalik2552

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-12-03 16:38 UTC, mikehardy requested changes
Hi there! Thanks for giving this a shot
It's incomplete though, per the issue:
> As mentioned here - needs a slight tweak to our gradle scripts and a documentation update related to same: #9939 (review)

--->

> I believe this is going to need a new framework build id as well, to make sure it does not flake in CI (we pre-download in a retry loop)

https://github.com/ankidroid/Anki-Android/blob/1e9388f1098c38fd8f99269d37147982d0f8d7ca/AnkiDroid/robolectricDownloader.gradle#L25

That was the only reason I did not do it myself. It was the vital work. Can you examine your caches as mentioned for the new build id of the robolectric android jar for platform 31 and include that in the PR?

2021-12-03 16:56 UTC, dikshamalik2552 commented
Sure, I'll do it. Thanks for reviewing:)

2021-12-03 21:02 UTC, dikshamalik2552 commented
Hey, Can u please confirm if the new id will be : [androidVersion: "12", frameworkSdkBuildVersion: "7732740"]. I took this from https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/plugins/DefaultSdkProvider.java

2021-12-03 23:13 UTC, mikehardy commented
Oh interesting - they do not seem to be generating new artifacts for the 10 and 11 SDKs, those are the ones we have right now.

here are their numbers
```java
    knownSdks.put(Q, new DefaultSdk(Q, "10", "5803371", "REL", 9));
    knownSdks.put(R, new DefaultSdk(R, "11", "6757853", "REL", 9));
    knownSdks.put(S, new DefaultSdk(S, "12", "7732740", "REL", 9));
```

versus ours

https://github.com/ankidroid/Anki-Android/blob/1e9388f1098c38fd8f99269d37147982d0f8d7ca/AnkiDroid/robolectricDownloader.gradle#L25-L26

I guess the number doesn't actually change ? I'm really surprised by that.

There may be nothing to do here then, much to my surprise. I guess it is just the version number and that's it. Almost disappointing but I guess I know more about their releases now...

2021-12-03 23:14 UTC, mikehardy approved these changes
surprised, but...I think this is actually all that's needed

2021-12-03 23:45 UTC, david-allison-1 reviewed
Would be great to add a comment explaining what needs to be checked if this dependency is updated

On the same line, or immediately above the dependency - it will make future code reviews easier

2021-12-04 12:21 UTC, mikehardy commented
Immediately above the dependency with link to the SdkDownloader on github and mentioning robolectric gradle file I think, I agree

2021-12-04 12:23 UTC, mikehardy commented on AnkiDroid/build.gradle
> +    testImplementation "org.robolectric:robolectric:4.7.3"
```suggestion
    // robolectricDownloader.gradle *may* need a new SDK jar entry if they release one or if we change targetSdk. Instructions in that gradle file.
    testImplementation "org.robolectric:robolectric:4.7.3"
```

2021-12-04 12:24 UTC, mikehardy commented
I proposed a change on that one - @dikshamalik2552 sorry to be so hands on for this PR even though it is tiny. You can see how important testing is for the project I guess :sweat_smile: - also how subtle build systems can be! It is difficult to keep all the caching working so all the continuous integration is reliable (not flaky) etc...

2021-12-04 17:00 UTC, dikshamalik2552 commented
Yes, I have committed the changes. I learned a lot even though the pr was tiny. Thanks a lot for the experience! :)

2021-12-04 18:29 UTC, merged

2021-12-04 18:30 UTC, david-allison-1 approved these changes
Looks great, thanks!

![](https://media.giphy.com/media/g9582DNuQppxC/giphy-downsized.gif)

2022-01-16 19:17 UTC, mikehardy commented
Hi there! December OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for December 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of December)

Thanks!