(#7805) updated ACRA initialization to build style
ankidroid/Anki-Android pull request #9969
Opened 2021-12-06 20:09 UTC by jimrod942

## Pull Request template

## Purpose / Description
Changed the ACRA initialization from annotations to a builder style. This is necessary for updated the project from ACRA 5.7 to 5.8. Did not change build.gradle line 9 to actually update ACRA from 5.7.0 to 5.8. Let me know if that is necessary at this point.

## Fixes
Fixes #7805 

## Approach
The annotation initialization will not work with future releases of ACRA, so it needed to be changed to a builder style. This is done in onCreate() when mAcraCoreConfigBuilder is first initialized.

## How Has This Been Tested?
Passes all 7 test when running the androidTest ACRATest

## Learning (optional, can help others)
Researched builder styles, fluent APIs, and the ACRA documentation

https://dzone.com/articles/fluent-builder-pattern
https://github.com/ACRA/acra/wiki/BasicSetup#2-configuration

2021-12-07 16:12 UTC, mikehardy requested changes
This looks fantastic! Please do update the gradle dep as well, and if you haven't already, update the description with tags in form of `Fixes #XYN` for the issues it affects (a PR from dependabot and a deprecation issue I think)

Exciting to have this out of the way!

2021-12-18 04:22 UTC, jimrod942 commented
Hi Mike! Let me know if you have any insights for those errors. I can definitely do my best to address them. I would love to still get my PR merged!

2021-12-18 04:47 UTC, david-allison-1 commented
Hi! Thanks for the PR!

> `Inheritance from an interface with '@JvmDefault' members is only allowed with -Xjvm-default option (:33)`
>
> The first error is simple enough to fix by adding `kotlinOptions.freeCompilerArgs = ['-Xjvm-default=compatibility']` to the app's build.gradle file.

Could you link some documentation on our options here? There's a few values for `-Xjvm-default` 

We have an additional option, to resolve this: overriding the `@JvmDefault` method. In this case, I don't know whether I prefer it and we should discuss

`    override fun enabled(config: CoreConfiguration): Boolean = true`

**AnkiDroidCrashReportDialog.kt**

```
Unresolved reference: resIcon (:50)
Unresolved reference: title (:51)
Unresolved reference: positiveButtonText (:52)
Unresolved reference: negativeButtonText (:53)
```

Fix each of these: by removing the parentheses: a method was converted to a property `resIcon() => resIcon` 

> `'buildCustomView' in 'CrashReportDialog' is final and cannot be overridden (:68)`

@mikehardy - this one isn't reasonably solvable on our side - could you take a look? I feel it'll require making the method virtual in `ACRA`.

2021-12-18 04:58 UTC, david-allison-1 requested changes
Requested a manual test.

Code-wise: This looks good to go for me, as long as we remove the 'Fixes' link to the issue: this is a great first step towards getting the version number bumped, but additional changes will need to be made, some of which may take some time to get into an ACRA release.

2022-02-16 12:35 UTC, mikehardy commented
This *will* be harvested, it is certainly not dead, and it's a priority just a bit behind other priorities of course - marking keep open

2022-03-23 16:28 UTC, mikehardy commented
Here's a crash without this PR on main as of now https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/a504cd96-bc62-4004-80c4-d075158fe4ba
Here's a crash with this PR rebased to main as of now https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/52512b4c-1683-4cbc-83b8-39a88612f10b

Other than perturbations associated with exact app logcat path to trigger test crash and predictable runtime differences (timestamps etc) the crash with this PR is :100: 

Going to merge this

2022-03-23 16:33 UTC, david-allison commented
Looks good to me. We've resolved the JVM default method flags, so we can go further now. 

As previously stated, great first step!

2022-03-23 16:34 UTC, mikehardy commented
Re-pushed to fork with clean first comment and one touch-up so the DX on crash reporting is better, as fuzz-busted by me just now while testing this thing...

2022-03-23 16:46 UTC, mikehardy commented
Not seeing the CI actions here and GitHub was having issues, so I just ran this locally against an API24 + API31 emulator set with the command `./gradlew clean jacocoTestReport lint ktlintCheck` (which is our CI package of tests) so this is good to go

2022-03-23 16:47 UTC, merged

2022-03-23 16:49 UTC, mikehardy commented
@jimrod942 congratulations, it's merged :-) - thanks a bunch for your patience on this one. I'd like to think it is not representative of getting a PR through in an open source project in general. Crash reporting specifically is so vital (how do you know if it fails? A zen question...) and testing it is hard because it relies on dependent systems out of your control. This was basically good to go almost from the start though, which is my experience when making PRs to most projects. Hopefully you get an easy one that is satisfyingly fast next time you give it a shot :-). Either way, it's in and you are now an AnkiDroid contributor :clap:

2022-04-22 14:34 UTC, mikehardy commented
Hi there! MARCH OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [March 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-03-01..2022-03-31)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of March.

Please note that GSoC contributions are okay for this process. Our philosophy is that our users have donated to AnkiDroid for *all* contributions. The only PRs that will not go through the OpenCollective process are ones *directly* related to a GSoC project from a selected participant, since those receive a stipend from GSoC itself.

Please understand that this means the monthly budget we have for payments might be stretched a bit and the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!