Pull Request Issue #9935
ankidroid/Anki-Android pull request #9970
Opened 2021-12-06 22:15 UTC by souravmunjal

## Pull Request template

## Purpose / Description
Previously after selecting the deck from the deck selection dialog it was and then if we again open the dialog it should be scrolled down to the deck selected

## Fixes
Fixes #9935 

## Approach
I started the recycler view that was showing the deck list to from the particular selected deck
Basically the DeckSelectionDialog class used in 2 places 
1 DeckSelectionSpinner
2 CardTemplateEditor
So I made some necessary changes in 3 file to ensure the above feature 
and updated DeckNameComparotor.kt acc. to latest kotlin functions.
4 files were changed

## How Has This Been Tested?
<img width="321" alt="image" src="https://user-images.githubusercontent.com/30770269/144930911-99d03a43-3809-40ad-bf14-b10274e98387.png">
<img width="316" alt="image" src="https://user-images.githubusercontent.com/30770269/144931008-f8ba22d7-6ac6-447e-bb1f-657e3c846ad9.png">
You can test it through going statitcs, or Add Notes->Cards->Deck Override 
The deck selection dialog was called from many other places but these are the screens where it was called from DeckSelectionSpinner and CardTemplateEditor respectively, so both the cases are test and working fine

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [done] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ done] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ done] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ done] You have commented your code, particularly in hard-to-understand areas
- [ done] You have performed a self-review of your own code
- [done ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-12-06 22:25 UTC, souravmunjal commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +    private static SelectableDeck selectedDeck;
I had to create this as static as the method from which we are calling the DeckSelectionDialog is also static

2021-12-07 15:53 UTC, mikehardy requested changes
Thanks for posting this!
It has some issues with formatting - you can see it doesn't follow the conventions of code nearby, our style is documented here https://github.com/ankidroid/Anki-Android/wiki/Code-style (as we move to kotlin this will be automatically enforced but for the legacy java files we still have to do it manually)
The static thing is troublesome, though I understand based on your note why - because newInstance on the spinner is static. 
That needs some thought, in case it's possible for the calling objects to simply know at the time what the selected deck should be . It may be that the "currently selected deck" is sufficient, but I haven't thought through this thoroughly yet

2021-12-09 17:42 UTC, souravmunjal commented
> Thanks for posting this! It has some issues with formatting - you can see it doesn't follow the conventions of code nearby, our style is documented here https://github.com/ankidroid/Anki-Android/wiki/Code-style (as we move to kotlin this will be automatically enforced but for the legacy java files we still have to do it manually) The static thing is troublesome, though I understand based on your note why - because newInstance on the spinner is static. That needs some thought, in case it's possible for the calling objects to simply know at the time what the selected deck should be . It may be that the "currently selected deck" is sufficient, but I haven't thought through this thoroughly yet

@mikehardy any updates on this?

2021-12-09 19:10 UTC, mikehardy commented
I saw your comments.
I left my own, you have not addressed them
So I could ask,

@souravmunjal any updates on this?
left some comments on the pr

:thinking:

2021-12-10 00:52 UTC, souravmunjal commented
> I saw your comments. I left my own, you have not addressed them So I could ask,
> 
> @souravmunjal any updates on this? left some comments on the pr
> 
> 🤔

oh i thought you were going to review on that 😅 my bad so i read the doc i feel it is according to that only but you find any issues can you pin it like the namings of the variable( which are selectedDeck,currentSelecttedDeckId) it would be great help

2021-12-10 01:07 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +    private static SelectableDeck selectedDeck;
I don't think this is used in any `static` contexts. Which line breaks if this is an instance variable?

2021-12-10 01:08 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
> +        DeckSelectionDialog dialog = DeckSelectionDialog.newInstance(mContext.getString(R.string.search_deck), null,mDeckId, false, decks);
```suggestion
        DeckSelectionDialog dialog = DeckSelectionDialog.newInstance(mContext.getString(R.string.search_deck), null, mDeckId, false, decks);
```

2021-12-10 01:10 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/DeckNameComparator.kt
> +        return o1.size.compareTo(o2.size)
Can you revert this - good change, but not related to the PR

2021-12-10 01:14 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +            var deckSorted = decks.sorted()
Can we find a better strategy here? This couples the ordering of the decks and the position - it's probably best to pass in the selected deck id in via the parameters

2021-12-10 01:20 UTC, souravmunjal commented
> Thanks!
> 
> Went through the code style for you, could you keep the changes in mind for your next PR?

yeah yeah sure will update that 
this line will get affected in line no 747 CardTemplateEditor.java if we not keep that variable staic
DeckSelectionDialog dialog = DeckSelectionDialog.newInstance(title, explanation,(selectedDeck!=null) ?selectedDeck.getDeckId():ALL_DECKS_ID,true, decks);
            AnkiActivity.showDialogFragment(activity, dialog);

2021-12-10 01:25 UTC, david-allison-1 commented
> this line will get affected in line no 747 CardTemplateEditor.java if we not keep that variable static
> DeckSelectionDialog dialog = DeckSelectionDialog.newInstance(title, explanation,(selectedDeck!=null) ?selectedDeck.getDeckId():ALL_DECKS_ID,true, decks);
> AnkiActivity.showDialogFragment(activity, dialog);

Thanks! It's best to reply to individual comments in the threads: https://github.com/ankidroid/Anki-Android/pull/9970#discussion_r766269692

2021-12-10 13:06 UTC, souravmunjal commented
updated the code please check

2021-12-11 04:05 UTC, david-allison-1 reviewed
Looking much better!

@mikehardy Should be ready for re-review

2021-12-11 04:05 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
> +    private static SelectableDeck selectedDeck;
This shouldn't be required - the override deck is stored in the collection.

And before saving, we should be able to query the template's `did`

2021-12-11 04:05 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
> +        var decks: List<SelectableDeck> = getDeckNames(arguments)
This should likely exist inside the `DecksArrayAdapter`, so it's closer to where the `sort()` is handled, 

I also feel this can be reduced to a Oneliner, but that's on me to sugest.

2021-12-11 16:11 UTC, mikehardy commented
I thought the title was meaningless and the description did not have enough information to give the reviewer context, I changed them
I'll queue this for re-review

2022-01-19 06:40 UTC, balta2ar commented
@mikehardy friendly reminder :)

2022-03-03 19:36 UTC, mikehardy commented
Has a conflict now so needs a rebase to master, it appears to me whenever I check this that there were comments after the last comments from David and that the comments weren't resolved, so this isn't ready for review from anyone else yet

2022-06-25 14:41 UTC, balta2ar commented
Ping @souravmunjal

2022-12-19 14:11 UTC, balta2ar commented
Ping @souravmunjal

2023-02-17 18:46 UTC, balta2ar commented
*sigh* ping @souravmunjal

2023-02-17 21:24 UTC, david-allison commented
*sigh* #9935 is closed. Why is this being bumped?

2023-02-17 21:24 UTC, closed without merging