feat: improve asset helper mime type detect
ankidroid/Anki-Android pull request #9971
Opened 2021-12-08 02:36 UTC by lowwor

## Purpose / Description
improve asset helper mime type detect

## Fixes
fix #9963

## Approach
Some code from https://github.com/dankito/MimeUtils, to detect more mimetypes

## How Has This Been Tested?
Some common types added to AssetHelperTest

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-12-08 04:01 UTC, mikehardy requested changes
Oh wow! I like where this is going in general, but there is no way we're ingesting 4000+ lines of code to do a non-core feature :scream: - huge maintenance burden over time for no payoff.

Luckily the internet has solved this problem a few times, and there is one library that's really well maintained:
https://tika.apache.org/index.html

This artifact seems like it would serve as the only necessary gradle dependency:
`'org.apache.tika:tika-core:2.1.0'`

The necessary interface allows for a null InputStream, at which point it will just match from it's file extension database based on the filename sent through in metadata

https://tika.apache.org/0.10/api/index.html?org/apache/tika/detect/Detector.html

Please try using this library (or some other suitable, well-maintained library) as a dependency vs direct code ingestion. Over the long-term, code maintenance is the biggest cost here and it should be avoided if at all possible.

2021-12-08 05:42 UTC, lowwor commented
🤣 , yeah, it's a auto generated file though, most of it is the type mapping, the actual code is not that huge. I notice tika too, but I thought you would prefer a file intead of a dep. I had changed to use tika now.

2021-12-08 08:51 UTC, david-allison-1 commented
I don't think we need a dependency here. Just take the result, if it's null, check the extension against `js/mjs` and we're done.

Happy to accept it as is, but I do feel this could still be leaner

2021-12-08 14:44 UTC, mikehardy commented
"auto-generated file" means, now we have to do some auto-generation? Of what, mappings we maintain? Heck no, we are flashcard people. Maintenance tasks like that need to be imagined by you - personally! - as something stretching into the next decade. Do you want to maintain mime types for the next 10 years? Definitely not. But dependabot will tell us when to update a library to a new version, and the Tika folks are passionate about MIME type mappings.

That's the way to think about these things - lowest possible maintenance burden when magnified over decades.

The android build toolchain will take care of shrinking out anything unnecessary in the lib such that when packed into the release build it is effectively just a blob of compressed mime types as if it were a file.

You don't mention how this was tested on device but with the apache project we have had problems in the past with lower Android versions not supporting their newer-style code (Java 8 symbols etc, specifically in the Apache Compress lib). I need to know that won't happen here. Have you tried running it on an API21 emulator to make sure it will work? It's useful to keep one of those around if you work on AnkiDroid as it's our minSdkVersion right now. If you don't have one, I can pull the branch and check it

2021-12-08 15:43 UTC, lowwor commented
Auto-generated file doesn't mean we need to maintain mime types ourselves, MimeTypeDetector.kt the file itself is auto-generated by another kotlin class task in the lib https://github.com/dankito/MimeUtils/, it auto gather mimetypes from http://www.iana.org/assignments/media-types/media-types.xhtml and https://www.sitepoint.com/mime-types-complete-list/ and generate MimeTypeDetector.kt for us. As a flash card app, I thought we wouldn't need to sync with the newest mime types change. So I thought that a simple full mime list for now is enough. And as a single file, we can clearly check the logic of it. But like tika you mention, as a full lib not only targeting android, although it's well tested, but still more files, more uncertainty, we may not have enough time to invesgate into the logic under it and check if it's fully compatiable with all our version of android and device(though most time it should). And as tika itself progress, we don't have time to check its changes too, so there is still some uncertainty there too. But anyway, I tested it on sdk21, and you're right. 
```
MethodHandle.invoke and MethodHandle.invokeExact
are only supported starting with Android O (--min-api 26)
```

2021-12-08 18:17 UTC, mikehardy commented
> Auto-generated file doesn't mean we need to maintain mime types ourselves, MimeTypeDetector.kt the file itself is auto-generated by another kotlin class task in the lib https://github.com/dankito/MimeUtils/, it auto gather mimetypes from http://www.iana.org/assignments/media-types/media-types.xhtml and https://www.sitepoint.com/mime-types-complete-list/ and generate MimeTypeDetector.kt for us

So you propose buliding some sort of scripting infrastructure which will process that periodically, and maintaining that for a decade+?

This isn't a point I'm going to argue much further. Depending on a lib is in practice much easier code ingestion. It's tempting to argue the point until you realize how much effort it really takes to maintain code and infrastructure around it, and deal with little corner cases and all that.

There is uncertainty around a lib dependency, sure. But better to have all that work required packaged up behind a little uncertainty and the occasional need to forward port.

The min API thing is a terrible result though, I'm really bummed about that - I've not investigated at all but in the apache compress case at least we were able to just pin the dependency back in time to one that worked, marked as able to remove the pin with whatever API version it needed.

2021-12-09 03:15 UTC, lowwor commented
Well, what I mean is we don't need to maintain and sync with the newest mime type maps at all. But anyway, I tried to revert to tika 1.19, which can support sdk 21 but it has some bugs that cause runtime exception though. How about we just like @david-allison-1 said, remove the maybe useless effort here, and just check some extension like `js/mjs`、`css` and that's it?

2021-12-09 12:07 UTC, mikehardy commented
Let's go for the simple then and just check those extensions yes. Can you leave a comment there that Tika would be good if needed, and if minSdkVersion >= 26, to capture the investigative effort here in source at least?

2021-12-09 13:36 UTC, david-allison-1 commented
Sounds good to me! Could you add a unit test case for `mjs` while we're in the area, since that was specified in the issue.

My preference is for removing as much latency from the Reviewer as possible, Tika seemed a little heavy (it didn't seem like IO should be required for this task). If maintaining our own mapping turns out to be hassle in the long-term, I'm happy to go with this alternative.

2021-12-10 00:58 UTC, david-allison-1 commented on AnkiDroid/src/main/java/com/ichi2/utils/AssetHelper.kt
> +            else -> MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension) ?: "text/plain"
`getSingleton()` has no business logic - this is fine for performance.

2021-12-10 01:41 UTC, lowwor commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/utils/AssetHelperTest.java
> +        assertThat(AssetHelper.guessMimeType("test.css"), is("text/css"));
By default Robolectric's MimeTypeMap is empty, we need to add types ourselves, otherwise, the test would fail. Would you like me to do this and move it back?
```
ShadowMimeTypeMap mimeTypeMap = Shadows.shadowOf(MimeTypeMap.getSingleton());
mimeTypeMap.addExtensionMimeTypMapping("zip", "application/zip");
```

2021-12-10 02:18 UTC, david-allison-1 commented on AnkiDroid/src/androidTest/java/com/ichi2/anki/utils/AssetHelperTest.java
> +        assertThat(AssetHelper.guessMimeType("test.css"), is("text/css"));
Oh, that's a nightmare! Let's keep it in `androidTest`, could you add a comment to the top of the class explaining why it's in `androidTest`. 

It's fine as it is code-wise, but the commit history needs to be fixed so that we can `rebase merge` the PR, keeping the history (and thus the `git blame`).

* rebase the commit history, such that the first commit is a pure move of `AssetHelperTest.java`.
* The second commit is the current change
* No additional commits exist

2022-01-04 13:48 UTC, david-allison-1 approved these changes

2022-01-07 13:40 UTC, mikehardy approved these changes
This one was so much more subtle than it first appeared :laughing: - thanks for getting it through, it really will improve life for the folks trying to customize ankidroid with javascript, which is hopefully what our plugins do in the future, so should be a big help. Cheers

2022-01-07 13:41 UTC, merged

2022-03-06 21:52 UTC, mikehardy commented
Hi there! **JANUARY** OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [January 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-01-01..2022-01-31) (I'll follow this with the same process for February in a week)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of January)

Thanks!