Update DeckPicker.java(Corrected the multiple changes issue)
ankidroid/Anki-Android pull request #9992
Opened 2021-12-18 05:28 UTC by SSTG

## Pull Request template

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

2021-12-20 17:26 UTC, legarspol commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                            Connection.isOnline();
- [ ] My understanding is that this method has no side effects and you don't use the return value. So calling it has no effects hence it should be removed.
- [ ] The tests won't pass until you delete the sync_connection_error resource string, which is now unused. Look at the tests this PR initiated.

2021-12-21 10:09 UTC, ShridharGoel commented
@SSTG Can you fill the PR template? Also, it's important to link the issue in the PR description so that when this PR is merged, the linked issue automatically gets closed.

2021-12-24 14:54 UTC, SSTG commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                            Connection.isOnline();
Oh I didn't realise all this. I will correct them all Thanks

2021-12-24 15:09 UTC, SSTG commented on AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
> +                            Connection.isOnline();
I have updated the code just as you mentioned. But I cannot find this resource string anywhere. I have been looking for it for a while now

2022-01-02 19:40 UTC, mikehardy requested changes
Hi there! Thanks for taking this on

We must not hard code strings, we support lots and lots of languages and need to use the translation infrastructure: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#handling-translations

There is extra space (an extra line) which is unnecessary for the fix

As @ShridharGoel mentioned, you must fill out the PR template, you do link to the original issue now, but I don't see a description of how this PR affects that issue. Right now I'm not exactly sure how this change affects the related issue?

2022-03-01 15:16 UTC, mikehardy commented
Superceded by #10414

2022-03-01 15:16 UTC, closed without merging